### ISSUE TITLE
Doesnt download correct files

### ISSUE THREAD

**Issue by Ocsav** [Sonarr/Sonarr#1003]
I added the anime "GATE", and when searching for missing episodes (HD 720p) it added some compressed patch files to the download client.

The patches are used to correct the episode and add some stuff, like new subtitles. 

It happend for episodes 5-7, and 8-10.

Keep up the good work guys! :)

**Comment by markus101** [comment]
Please use the forums for support.

Couple things to do, set minimum sizes on the quality settings page or block releases with PATCH in the title (assuming its part of the title).
