### ISSUE TITLE
Drone Factory Folder Recursion

### ISSUE THREAD

**Issue by burkasaurusrex** [Sonarr/Sonarr#1004]
I haven't done extensive testing, but it doesn't look like the watched folder for the drone factory is scanned recursively down until it finds a video file. Would be great to have an option to recurse XX levels or recurse completely.

**Comment by markus101** [comment]
It will pull files out of the folder directly or in a well named sub folder, at a minimum it needs the series title in it, but could be the full release name.

We have no plans to alter the behaviour.
