### ISSUE TITLE
Next Air Date Is displaying "Last Tuesday"

### ISSUE THREAD

**Issue by wcomartin** [Sonarr/Sonarr#1005]
i have one show which is fully downloaded and has no next episode in the tvdb, but the "Next Airing" Column in the grid is "Last Tuesday" this seems like a bug to me. other shows that don't have a next episode lined up just show "Next Airing" as blank.

![screen shot 2015-12-17 at 4 11 17 pm](https://cloud.githubusercontent.com/assets/2801793/11882290/92797ef6-a4d9-11e5-9c0e-c43279ebe17d.png)

**Comment by markus101** [comment]
Once upon a time someone wanted it to show the last episode if it was within a certain number of days, so it does. Offhand I forget the rule around it, but its there and not a bug.
