### ISSUE TITLE
Correctly parse multi-season downloads

### ISSUE THREAD

**Issue by michaelarnauts** [Sonarr/Sonarr#1007]
When manually downloading a multi-season torrent (for example to upgrade quality of existing episodes), Sonarr only seems to detect the first season from the download.

All files from the first season are shown fine in the activity view (even though I didn't initiate the download trough Sonarr, but directly in the downloadclient, what is nice!)

I'm using Deluge as download client.

This issue is mentioned in #683 , but that issue is about preventing Sonarr from downloading these files.

**Comment by markus101** [comment]
The reasoning to not handle them is due to parsing and the added complexity of the multi-season packs. I think if we want to discuss this further it would be better to keep the conversation in a single thread, #683.
