### ISSUE TITLE
issues with after shows

### ISSUE THREAD

**Issue by astlaurent** [Sonarr/Sonarr#1008]
I am currently seeing an issue where a show and an after show are appearing under the same episode listing which is more of an indexer problem but sonarr is choosing to grab the after show and not the real show instead half the time. I see this mostly with reality tv crap like the challenge on mtv. It would be nice if sonarr would not grab a 30 minute after show if it now the real show is an hour. this would help with incomplete shows as well. It would also be helpful if i could exclude "after show" as a whole exclusion which would also fix this issue.

**Comment by markus101** [comment]
This belongs on the forums since its a support issue.

You can use a Release Restriction to prevent it. (Indexer Settings).
