### ISSUE TITLE
Short date format UI inconsistencies

### ISSUE THREAD

**Issue by michaelarnauts** [Sonarr/Sonarr#1009]
The dropdown for short date format contains the following items:

* Mar 5 2014
* 5 Mar 2014
* 03/5/2014
* 03/05/2014
* 25/03/2014
* 2014-03-05

The 3th, 4th and 5th items are not clear what they do. For further consitency with the Long Date Format, maybe the date should aways be the same (2014-03-25)? There is one issue regarding the padding of the zero of the day (2014-03-05 vs 2014-03-5), but who is using this format anyway? And why provide this option, but not for the padding of the month (3/05/2014).

Suggested list:
* Mar 25 2014
* 25 Mar 2014
* 03/25/2014
* 25/03/2014
* 2014-03-25

Remarks, suggestions, comments?

**Comment by markus101** [comment]
I'm not exactly sure where the list of date formats came from originally, but `MM/D/YYYY` is a valid format, used in the Tagalog/Filipino locale. Maybe no one is actually using it in Sonarr, but its innocuous.

**Comment by michaelarnauts** [comment]
Okay, sorry about that. But that still makes it unclear what 03/05/2014 is about. Maybe displaying it in the MM/D/YYYY format is more clear?

In my case, I wanted to pick DD/MM/YYYY, but I wasn't sure if I should pick 03/05/2014 or 25/03/2014. Especially since there were different reference dates used.

**Comment by markus101** [comment]
That gets tough, if everything shows 2 digit dates you can differentiate between MM/DD/YYYY (03/25/2014) and MM/D/YYYY (also 03/25/2014), the 25 is there throws things off for the one example its used in, which looks like an oversight.

**Comment by michaelarnauts** [comment]
True,  but the 25 is also used in the field below. It also makes it easy to see what is the day in the format.

**Comment by markus101** [comment]
Yeah, thats what I'm saying, the 25 is wrong, we'll have to fix that.

**Comment by wouterbaake** [comment]
That fix makes it very confusing to choose between MM/DD and DD/MM formats, because the date is valid in both notations. 
Please revert it back to 25/03/2014 for all cases so it becomes clear which option is which. Or use the current date or symbolic representation (ie MM/DD/YYYY) if that makes things clearer in your opinion.
