### ISSUE TITLE
Episode Status only loosely reflects actual status

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1014]
Downloading when episode is on disk: https://github.com/Sonarr/Sonarr/issues/722

Also when episode is queued or failed, but still in a downloading state, we show downloading, instead of the actual state (which we show on the calendar).

**Comment by SpaceK33z** [comment]
Is this related with the screenshot below? This episode failed downloading, and now it has an empty download bar.

<img width="310" alt="fullscreen_08-01-16_22_49" src="https://cloud.githubusercontent.com/assets/533616/12210424/243927e2-b65a-11e5-8384-361ff2d8bea4.png">

**Comment by markus101** [comment]
No, that looks like something else, trace logs would be helpful could you open a forum post (not a GHI)?

**Comment by SpaceK33z** [comment]
Of course, I just thought it was the same as this issue because it stays in the download state ;).

**Comment by markus101** [comment]
This is resolved in the v3 UI.
