### ISSUE TITLE
Make the log file location configurable

### ISSUE THREAD

**Issue by joukestoel** [Sonarr/Sonarr#1020]
I can't seem to find a way to change the location of the log files made by Sonarr.
Since I am running Sonarr on a small ARM device (an Odroid C1) with an SD inside I would like to prevent disk writes to the SD as much as possible.

**Comment by markus101** [comment]
You can try using the `--data=/path` switch to move the AppData directory or use a symlink to move it somewhere else.

**Comment by joukestoel** [comment]
Thanks! Changing the data directory with the `--data` parameter worked like a charm
