### ISSUE TITLE
API Documentation for Indexers

### ISSUE THREAD

**Issue by speedyflipper** [Sonarr/Sonarr#1023]
I would like to be able enable specific indexers when the VPN is running and disable when it's not. Every now and then I like to check public trackers to see if they have anything episodes that my private tracker hasn't uploaded. When I do this I make sure the VPN is on and manually enable the indexers, run the search and then disable them when I'm done.

I have scripts that run to make sure the VPN is enabled/disabled based on my current settings. I would like to add in a command to enable the public trackers when the VPN is enabled and then to disable the indexers when I decide to turn off the VPN.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
