### ISSUE TITLE
Filter "Cutoff Unmet" Panel by Quality Profiles

### ISSUE THREAD

**Issue by R-Jimenez** [Sonarr/Sonarr#1025]
Hopefully this is the right venue for this kind of thing (Trello seems to have been phased out), so feel free to move/redirect this as needed.

Title kind of says it all. I have a few different quality profiles set up for various purposes, with various widths to each. Some are lenient (such as standard TV series or daily programs), while others are extremely specific (archival collections). While this isn't a high priority, it would be fantastic to be able to set my archive from series creation, and monitor the entire profile's completion. 

As it stands, the entire unment pane is useless to me (or anyone with a wide collection; or anyone who follows long shows like Always Sunny), but with this small change, it could easily become a good addition to Sonarr's already extensive monitoring capabilities. Cheers for the work you guys are doing, and for creating such an accessible drone.

**Comment by markus101** [comment]
Sorting by Profile seems pretty arbitrary, would it sort by name, creation order, how far the current quality is for the cutoff or something else?

> it would be fantastic to be able to set my archive from series creation, and monitor the entire profile's completion.

If you're looking at a specific series wouldn't this information be better to be displayed on the information for that specific series or being able to filter cutoff unmet to show a specific series?

**Comment by R-Jimenez** [comment]
Apologies. In my late-night revelry I seemed to have chosen my words poorly. I meant to say *Filter*, not *Sort*. As you mention the sorting really is kind of arbitrary, and would do little to make the data more accessible. 

Specific use-case: I have a Collections profile which accepts only Blu-ray and cuts off at 1080, a general purpose General profile which accepts only Web and TV forms and cuts off at 1080, and a Flexible profile which accepts all and cuts off at 720. I would like to be able to disable reporting of the other profiles or otherwise view a tab to see the unmet files for my Collections profile alone, without the clutter of other series for which I'm not as interested in stable quality.

**Comment by markus101** [comment]
Closing in favour of https://github.com/Sonarr/Sonarr/issues/3657
