### ISSUE TITLE
Series with a lot of Seasons fail to load

### ISSUE THREAD

**Issue by lifeofguenter** [Sonarr/Sonarr#1026]
Series with a lot of Seasons get stuck at a endless loading page.

**Comment by markus101** [comment]
Please use the forums for support and let use know some example series along with the OS and system you're running Sonarr on.

**Comment by Mynx73** [comment]
Is this still considered a known issue?  When accessing Sonarr on my iPad (chrome or safari) the series page fails to load - any series regardless of number of seasons or monitored status.  Running sonarr on latest OS X on a Mac mini.  Issues has not presented itself when accessing sonarr via laptop or directly on the Mac mini (either direct or through screen sharing etc).  Screen snip attached.
