### ISSUE TITLE
Anime specials naming

### ISSUE THREAD

**Issue by thalweg** [Sonarr/Sonarr#1034]
When a show's Series Type is Anime, the Specials season still uses the Standard Episode Format instead of the Anime Episode Format when renaming:

![sonarranimespecialsnaming](https://cloud.githubusercontent.com/assets/554340/12038932/011458be-ae2a-11e5-8099-95f2df45e427.png)

**Comment by markus101** [comment]
The Anime format is only used when the episode has an absolute episode number, which I'm guessing these don't. The alternative is attempting to remove the Absolute Episode number from the naming format, or using `0`, both of which have their own issues.

**Comment by thalweg** [comment]
Ah, I see why that's tricky, OK.

Confirmed that these specials don't have absolute episode numbers in TheTVDB. I suspect the best solution is for me to see if absolute numbering is sensible for these titles, and get those changes to TheTVDB data.
