### ISSUE TITLE
Creation of hardlinks not working

### ISSUE THREAD

**Issue by jjsearle** [Sonarr/Sonarr#1041]
![capture](https://cloud.githubusercontent.com/assets/7019630/12080471/200a11f0-b253-11e5-9f8a-90e17598f975.PNG)

I have the hardlink option enabled within the settings but Sonarr seems to ignore it and just creates a copy instead (example above).

__Version__         : 10.0.0.37119
__Mono Version__ : 4.2.2 (Stable 4.2.2.10/7b87787 Mon Dec 21 19:36:52 UTC 2015)

I am running sonarr on arch linux and everything is sitting on a raid5 array. The file system is xfs.

As far as I can see there is nothing of note in the logs accessible via the interface / journal.

Any ideas?

**Comment by jjsearle** [comment]
Ah, found the debug options and I am getting this in the logs now.

<pre>
16-1-3 20:16:30.6|Debug|EpisodeFileMovingService|Hardlinking episode file: /data/torrents/btn/REDACTED.mkv to /data/torrents/btn/REDACTED.mkv
16-1-3 20:16:30.6|Debug|DiskTransferService|HardLinkOrCopy [/data/torrents/btn/REDACTED.mkv] > [/data/torrents/btn/REDACTED/Season 3/REDACTED.mkv]
16-1-3 20:16:30.6|Debug|DiskProvider|Hardlink '/data/torrents/btn/REDACTED.mkv' to '/data/torrents/btn/REDACTED/Season 3/REDACTED.mkv' failed.

System.InvalidOperationException: Operation not permitted ---> Mono.Unix.UnixIOException: Operation not permitted [EPERM].
  --- End of inner exception stack trace ---
  at Mono.Unix.UnixMarshal.ThrowExceptionForLastError () <0x40cef810 + 0x00013> in <filename unknown>:0 
  at Mono.Unix.UnixMarshal.ThrowExceptionForLastErrorIf (Int32 retval) <0x40cef7f0 + 0x00013> in <filename unknown>:0 
  at Mono.Unix.UnixFileSystemInfo.CreateLink (System.String path) <0x40cef570 + 0x0002b> in <filename unknown>:0 
  at NzbDrone.Mono.DiskProvider.TryCreateHardLink (System.String source, System.String destination) [0x00009] in /tmp/yaourt-tmp-joe/aur-sonarr-git/src/Sonarr/src/NzbDrone.Mono/DiskProvider.cs:160 
</pre>

**Comment by JigSawFr** [comment]
I think you need to fix permissions on your medias folder for Sonarr :)

**Comment by jjsearle** [comment]
if sonarr is able to write the copy then surely the permissions are correct..

The root download folder is 777 and the files are readable by everyone.

**Comment by JigSawFr** [comment]
Yes it writed files but, you want to copy them to another folder no ?

**Comment by jjsearle** [comment]
The other folder is created and owned by sonarr.

Anyway I think I know what the issue is. My torrent client is creating the downloaded files as 644 owned by the transmission user and transmission group. Apparently (something that I never knew), a user needs to have write access to a file before the user is able to create a hardlink, not just read access. The 'sonarr' user does not have write access to any of the files downloaded by transmission only read access.

I haven't tested it yet but I suspect this is the issue. I need to figure out how to reconfigure the umask and group for file creation within transmission first. I will update this with my findings.

**Comment by markus101** [comment]
Closing as this is a support issue (for the forums).
