### ISSUE TITLE
Suddenly Segment Faulting after months of happy use on FreeBSD

### ISSUE THREAD

**Issue by ghost2501** [Sonarr/Sonarr#1043]
Hi guys,

 I want to start by expressing how brilliant your work is here. Thank you so much!!

 However, a day ago it crashed giving me a SIGSEGV error and now will not run for more than a minute. 

 I know it is my environment as the nzbdrone.db works flawlessly on my windows machine but that is my games machine :p So I need to work out what has changed on my side and would love some suggestions.

I have already tried deinstalling & reinstalling mono. I have updated my packages (binaries) which noted that mono needed to be reinstalled again due to a shared library requirement, but this did not fix anything either.

This is a link to the error I am getting in the console: http://pastebin.com/AyZnVijF

Thanks for your time

**Comment by markus101** [comment]
Please use the forums for support.

This looks like an issue with MediaInfo, perhaps a problem with MediaInfo and the file that its trying to import, try upgrading MediaInfo to start.
