### ISSUE TITLE
qBittorrent in Wiki

### ISSUE THREAD

**Issue by pbaesse** [Sonarr/Sonarr#1044]
How to connect to qBittorrent is missing in the wiki,

Thanks for the help!

**Comment by markus101** [comment]
Not sure what information you're looking for, but we don't have guides on how to connect for most (if any?) clients.

**Comment by pbaesse** [comment]
Ok, I wasn't very clear. What I mean is that qBittorrent is not listed as one of the options and neither I can see the option to connect to it.  

https://github.com/Sonarr/Sonarr/pull/779

Thanks again.

**Comment by markus101** [comment]
Its only in develop, unless you are running those builds you won't see it.

**Comment by pbaesse** [comment]
Oh thanks. I didn't realize what version was it on. Any ideas when I will be the stable version??
