### ISSUE TITLE
Incomplete Downloads From Deluge are Imported

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1053]
When Deluge starts up and has a status of `checking` for downloads, Sonarr will interpret it as available for import and import an incomplete file. Deluge's proxy also doesn't log the response when trace logging is enabled so we need to reproduce this behaviour ourselves (as well as add the logging).

**Comment by cron410** [comment]
You really should have Deluge putting completed torrents in a separate folder. Deluge should only be seeding from the folder you have Sonarr looking at.

**Comment by markus101** [comment]
Not able to reproduce this and we explicitly check the state isn't `Checking` when it's finished before marking it as complete.
