### ISSUE TITLE
Not removing failed downloads from SAB 0.8.0 Beta4

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1054]
Not sure if the API changed or its failing to remove it for another reason, but failed downloads are stuck in SAB's history and need to be removed manually (Sonarr seems to think it was already removed).

**Comment by thezoggy** [comment]
nothing changed on api, try beta5 also

**Comment by markus101** [comment]
This seems to be a race condition in SAB and a couple commits not in 1.0 address it, but may not solve it. Closing.
