### ISSUE TITLE
Reformat Calendar view

### ISSUE THREAD

**Issue by xeddog** [Sonarr/Sonarr#1055]
Remove the "Upcoming" column since most of the information is redundant anyway.  Or at least provide an option to hide it.  The information that is not redundant, episode name and number, could be added to the calendar entry.

**Comment by markus101** [comment]
We're looking to make some changes to the calendar, so we'll consider a change to hide the upcoming view.

> The information that is not redundant, episode name and number, could be added to the calendar entry.

The problem with that is on smaller screens it becomes very cluttered and you end up with a lot of trimmed titles or a lot more vertical space used.

**Comment by xeddog** [comment]
I understand that.  **Personally**, I could do without the episode name and number on the calendar.

**Comment by niczoom** [comment]
Agreed, for me its not needed, just gets in the way of my month view on my UHD TV. I dont see a hide option in the settings??

**Comment by markus101** [comment]
Upcoming will be removed in v3 and more information will be on the calendar.
