### ISSUE TITLE
Start/Stop Sonarr with Synology Task Scheduler

### ISSUE THREAD

**Issue by Patrick1610** [Sonarr/Sonarr#1057]
Hi, 

Recently I discovered that Sonarr is the reason my Synology won't go into hibernation. 
SInce I read there was no solution to this problem I wanted to start and stop Sonarr on specific times each day to enable hibernation when it is stopped. I made a service with the Synology Task Scheduler. The task works with al my other packages but Sonarr won't start. 

Does anyone know a solution? 
Thanks!

**Comment by markus101** [comment]
You'll need to check Sonarr's logs to see if Sonarr is even being started and to see how its failing.

If you still have issues you can try opening a thread on the forums.
