### ISSUE TITLE
Choose subtitled or dubbed for Anime

### ISSUE THREAD

**Issue by JokerJim** [Sonarr/Sonarr#1060]
The title pretty much says it all, if we select type Anime, give us the option of selecting dubbed or subtitled versions of the episodes... or create two show types - Anime Dubbed and Anime Subtitled. It's annoying to have a show where some episodes are subtitled and others are dubbed. Another alternative would be to allow us to set that in the quality setting so that we could say that dubbed is preferred but we'll take subtitled... much like you do with DVD, Bluray and SD options;

**Comment by M0UL** [comment]
just blacklist the sub/release groups that have releases that you dont want.

**Comment by markus101** [comment]
AS @M0UL said use a release restriction to handle this, you can require (or reject) dubbed as part of the title with one, assign it a tag and that tag to a series.
