### ISSUE TITLE
Add a series with two languages

### ISSUE THREAD

**Issue by NTTAKR** [Sonarr/Sonarr#1063]
I am watching a series in native (English) language but also would like to download it for my girlfriend in german language. 
I cannot add the series two times with 2 different profiles attached, and I cannot add more than one language in a single profile, since it only downloads the first language it finds but not both.

**Comment by markus101** [comment]
Language Profiles (https://github.com/Sonarr/Sonarr/issues/274) will eventually support multiple languages in a profile, but only a single file will be kept by Sonarr (same as upgrading quality, deletes lower quality episodes).

**Comment by NTTAKR** [comment]
That's too bad, because it does not solve the problem. Is there no option to add a series a second time with a different profile? If I need a series in two different languages I cannot do that with Sonarr currently. :-(

**Comment by markus101** [comment]
No and thats never going to happen, its far too complicated to do that.

Multiple files per episode is something we've talked about, but not a short term goal. https://github.com/Sonarr/Sonarr/issues/312

**Comment by Tackyou** [comment]
This is far from complicated and a very basic feature.

**Comment by Elehiggle** [comment]
Its certainly possible. Add a few extra fields in the database, add language selection when adding a new show and adapting existing code. If the authors actually would need it theirselves, it could probably be done in a few hours of work, but motivation is often the issue. I would like it myself but I cba too hard to code it and make a pull request.

**Comment by alejandronop** [comment]
or store in diferent folders like EN/ DE/ ES/

**Comment by rochdev** [comment]
I'm facing this issue as well as I watch everything in English but most family members only speak French.

I'm thinking to try 2 separate instances of Sonarr, which would store movies into 2 different folders that would then be loaded in Plex as 2 libraries since Plex supports only a single language per library. I expect my users to use either English or French, but not both, except for movies from France where the original language is French.

I'll try to work something out in the next few weeks. I may need a separate instance of Ombi as well, not even sure if Ombi supports foreign languages at all. I'll report further findings in this thread.

@markus101 Do you think this makes sense? Any better recommendation?

**Comment by rochdev** [comment]
I guess one limitation of the approach I described above is series have to be manually added twice, instead of once with 2 languages. I may need to add something to sync the 2 instances.

**Comment by Elehiggle** [comment]
Have you checked if the content you download has both, English and French? I have switched to Sonarr a month ago and it works perfectly fine. Releases have both languages in 99% of the cases. And with language profiles in Sonarr Alpha, which btw works very smooth, you can even program upgrades once French becomes available in case you have downloaded the English one a while back.

**Comment by rochdev** [comment]
@Elehiggle In my experience, most releases don't contain both English and French, so while it could work for some series, the problem will still exist for others. If you have a source with 99% of MULTI releases I would be very interested to know about it.

Could you provide more information about Sonarr Alpha? My understanding is that it will upgrade to French by removing the English release, which I would prefer to keep as well.

**Comment by Elehiggle** [comment]
Yes, it would remove the English release. You need two Sonarr instances then.

Usually, those releases don't contain "MULTI". It just says eg. FRENCH, but also contains English. Amazon/Netflix WEBDL's always contain English audio, even Bluray releases. Only HDTV recordings don't contain two languages.

**Comment by rochdev** [comment]
Ok, I'll take a look at Netflix releases, but I'm also watching shows from many other providers. Not sure if they all have similar releases with multiple audio tracks.

Once I have a working setup, I'll explain what I did here. I'll also try to see if I can whip up a small app to sync between Sonarr instances. Of course the best case scenario would be if Sonarr can officially support this, but I don't know .NET well enough to contribute. I think it would also require quite a lot of UI changes such as the ability to filter by language etc.
