### ISSUE TITLE
Manual Import UI needs scrollbar for large seasons

### ISSUE THREAD

**Issue by fudge01010** [Sonarr/Sonarr#1068]
When performing "manual import" of large seasons of shows, if there are more than approx. 20 shows (on my 1080p monitor) or ~30 (at 1440p), the import button is off the page, and no scrollbar is shown. Zooming right out allows the button to be pressed.

**Comment by markus101** [comment]
Known issue: https://github.com/Sonarr/Sonarr/issues/745
