### ISSUE TITLE
/episode API returns HTTP 500 when seriesId is missing

### ISSUE THREAD

**Issue by mribeiro** [Sonarr/Sonarr#1070]
When targeting /episode (with no parameters), I get a NRE:

Request
URL: http://s.hip/sonarr/api/episode

Response:
{
  "message": "Object reference not set to an instance of an object",
  "description": "System.NullReferenceException: Object reference not set to an instance of an object\n  at Nancy.DynamicDictionaryValue.op_Implicit (Nancy.DynamicDictionaryValue dynamicValue) <0x88f1c98 + 0x0000d> in <filename unknown>:0 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object)\n  at (wrapper delegate-invoke) <Module>:invoke_bound_Nullable`1<int>_Closure_CallSite_object (System.Runtime.CompilerServices.CallSite,object)\n  at NzbDrone.Api.Episodes.EpisodeModule.GetEpisodes () [0x00000] in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\Episodes\EpisodeModule.cs:23 \n  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__c (System.Object options) [0x00000] in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\REST\RestModule.cs:111 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x8867448 + 0x0013b> in <filename unknown>:0 "
}

*Note* With the parameter "seriesId" works flawlessly

**Comment by markus101** [comment]
`seriesId` is a required parameter (updated the docs to reflect that): https://github.com/Sonarr/Sonarr/wiki/Episode though we should return a 400 instead of a 500.
