### ISSUE TITLE
Add support for seedr.cc

### ISSUE THREAD

**Issue by jpontius** [Sonarr/Sonarr#1074]
I just found seedr.cc and it looks pretty awesome.  Free web based torrent client.  They have an api https://www.seedr.cc/pulse/api-doc/.  Maybe we could get this added as a client.

**Comment by markus101** [comment]
These setups aren't viable until we support alternative transfer methods as there is no way to support importing files.

This is something we'll need to re-evaluate after https://github.com/Sonarr/Sonarr/issues/282 is implemented.

**Comment by anand2610** [comment]
Hi @jpontius @markus101 ,
 Is this possible to access seedr.cc  through rest api?
Can you share sample code if possible means...

Thank you,
Anand
