### ISSUE TITLE
BTN result showing escape character on manual search

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#1075]
```
16-1-19 01:28:53.9|Debug|Parser|Parsing string 'The.Royals.S02E10.The.Serpent.That.Did.Sting.Thy.Father\'s.Life.1080p.WEB-DL.DD5.1.H.264-NTb'
```

example:
![sonarr](http://zoggy.net/sonarr182.png)

on btn website it shows:
`The.Royals.S02E10.The.Serpent.That.Did.Sting.Thy.Father's.Life.1080p.WEB-DL.DD5.1.H.264-NTb`

**Comment by Taloth** [comment]
JSON: ReleaseName": "DC\\'s.Legends.of.Tomorrow.S01E01.Pilot.Part.1.1080p.WEB-DL.DD5.1.H.264-LoT",
"Size": "1840830905",
