### ISSUE TITLE
Choose tvdb metadata language

### ISSUE THREAD

**Issue by kwartel** [Sonarr/Sonarr#1076]
I added 'The Mole (NL)' to Sonarr, but the scene name is the Dutch name: 'Wie is de Mol'. Sonarr won't bite because the TVDB says it's called the international name:
http://www.thetvdb.com/?tab=series&id=81391
However, the dutch page says the right name:
http://www.thetvdb.com/?tab=series&id=81391&lid=13

It would be great if I could point Sonarr to the dutch page, so it can use the right data.

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/issues/269

**Comment by kwartel** [comment]
I'm so sorry... I thought I searched, but apparently I suck at that.
