### ISSUE TITLE
Inconsistent image URL in API

### ISSUE THREAD

**Issue by mribeiro** [Sonarr/Sonarr#1082]
When invoking the /calendar api, the images for the tvshow have a complete URL to TVDB (e.g. http://thetvdb.com/banners/fanart/original/257655-47.jpg).
However, if the /series api is called, I get the URI to get the image (e.g. /sonarr/MediaCover/2/fanart.jpg?lastWrite=635868980500000000).

Shouldn't this be coherent and always return the same thing?

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/428
