### ISSUE TITLE
[Request] - Transmission: download in a different folder

### ISSUE THREAD

**Issue by Jorman** [Sonarr/Sonarr#1083]
Hi, it's possible to add a functionality to download the files in a specified folder?

Tnx, J

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/issues/744

**Comment by Davst** [comment]
Need this for deluge as well.

**Comment by Taloth** [comment]
Deluge categories/labels have builtin support for directories in the deluge ui
