### ISSUE TITLE
Episode for incorrect series upgraded

### ISSUE THREAD

**Issue by Popsikill** [Sonarr/Sonarr#1088]
I have an issue where an episode is being downloaded (upgraded) incorrectly -

The original series of "Doctor Who" (pre 2005) has 26 seasons, every now and then a new episode will come out (on usenet) for the "Doctor Who 2005", to which sonnar will grab believing it to be Season 20 episode 05.

2005 != S20E05 :)

Releases being snatched are:
Doctor.Who.2005.Christmas.Special.2015.Extra.720p.BluRay.x264-SHORTBREHD (From OZNZB)
Doctor.Who.S20E05.Enlightenment.Part.4.DVDrip.XviD-SAiNTS (From Usenet-crawler)
Doctor.Who.2005.Christmas.Special.2015.BDRip.x264-HAGGiS (From Omgwtfnzbs)

Is this a bug or is there something else I can do to manage this?

Cheers

**Comment by Taloth** [comment]
Post the full releasename.

**Comment by Popsikill** [comment]
Have updated the post  to relect the releases but they are:

Doctor.Who.2005.Christmas.Special.2015.Extra.720p.BluRay.x264-SHORTBREHD (From OZNZB)
Doctor.Who.S20E05.Enlightenment.Part.4.DVDrip.XviD-SAiNTS (From Usenet-crawler)
Doctor.Who.2005.Christmas.Special.2015.BDRip.x264-HAGGiS (From Omgwtfnzbs)

**Comment by Taloth** [comment]
@markus101 The special gets parsed by the [Supports 1103/1113 naming](https://github.com/Sonarr/Sonarr/blob/f38d5de/src/NzbDrone.Core/Parser/Parser.cs#L129-L131) regex.
Which is used for these [crap](https://github.com/Sonarr/Sonarr/blob/f38d5de9/src/NzbDrone.Core.Test/ParserTests/SingleEpisodeParserFixture.cs#L15) releases.
(And [this](https://github.com/Sonarr/Sonarr/blob/f38d5de9463e155bd8ca42437764fd2a60d20c37/src/NzbDrone.Core.Test/ParserTests/PathParserFixture.cs#L21-L22) one but that's just a crap filename, gets parsed as series name instead reverting to folder)

Suggestions?

**Comment by markus101** [comment]
@Taloth LOL almost always uses 101 style naming in the file name (the release name isn't crap), once they get to 10+ seasons we start seeing it. I don't see an easy solution to this, its crap on both sides.

**Comment by thezoggy** [comment]
why i say dont use the filename but the releasename (nzbname) :)

**Comment by markus101** [comment]
Added this issue under #457 since that would allow us to properly handle it.
