### ISSUE TITLE
Metadata - URL type NFO

### ISSUE THREAD

**Issue by Popsikill** [Sonarr/Sonarr#1092]
Hi there!

I was just wondering if a feature could be added for just the URL-type NFO metadata for the series (for Kodi).

For instance placing only a single tvdb.com URL in the NFO file which Kodi would then pick up?
(filename stays the same)

Thanks!

**Comment by markus101** [comment]
Why not let Kodi determine that on its own? With both Kodi and Sonarr using the same source for information the folder name should match the series name Kodi will use to lookup the information.

**Comment by Popsikill** [comment]
I had an instance yesterday with a series called [The Magicians](http://www.imdb.com/title/tt4254242/reference).

I had added the correct series correctly through Sonnar, Sonarr downloaded the two episodes that was expected.

However when Kodi scanned the new series, with a directory name of 'The Magicians' it picked up [a 2011 series called the magicians](http://www.imdb.com/title/tt1830351/reference)

I have renamed the directory 'The Magicians (2015)' which also seems to have worked :)

**Comment by markus101** [comment]
I don't think we'll add such an option as this issue is pretty rare when folders and named properly and we'd rather not add another option for such a small usage.

**Comment by Popsikill** [comment]
No worries Mark.

If I can make another slight suggestion that may solve the issue - add a `{series year}` place holder for the `Series Folder Format`.

By manually putting the year on the folder that Sonarr created solved my issue - would be great if Sonarr could do it :+1:

**Comment by markus101** [comment]
Sonarr uses the series title to create the folder, which is included in TheTVDB title: http://thetvdb.com/?tab=series&id=299139

Unless the series folder was created outside of Sonarr or for some reason was created by Sonarr without the year in the title (which means someone added it to TheTVDB wrong) it should have been there.

Already have a ticket for the year as a separate renaming token https://github.com/Sonarr/Sonarr/issues/393

**Comment by Popsikill** [comment]
Great thanks!

I think the reason in my case is that I added this series quite a while ago, I would hazzard a guess that the TVDB entry didn't have the title in it at that point in time, and has since been updated.
