### ISSUE TITLE
Plex notification causes destructive update

### ISSUE THREAD

**Issue by squarefrog** [Sonarr/Sonarr#1093]
If I use sonarr to notify plex on download/rename etc, then the refresh causes my plex library to remove files from my library. 

My setup:

- files located on unRAID
- sonarr is run on unRAID box, in a docker vm 
- plex media server run on a Mac mini (running OSX)
- the network share for TV files is automounted in OSX using autofs 

I must stress that this does not cause any files to be deleted, so more of an annoyance that any serious issue. Just means I have to refresh my library manually. 

Could this be an issue with sonarr, and plex, having different file paths?

```
// file path in sonarr
/tv/show/season/file

// file path according to plex
/mnt/odin/tv/show/season/file
```

I should state that I'm unsure if this is a sonarr or plex issue. I'm not sure what the actual notification looks like, short of sniffing the network, I wondered if anyone else could shed light on the issue.

**Comment by markus101** [comment]
Please use the forums for support.

Sonarr tells Plex to rescan the library, if partial updates are possible (supported version of PMS and the setting is enabled) then Sonarr tells Plex to update that particular series. Sonarr never tells Plex to update a specific path.

I can't think of a scenario where this could happen unless Plex is set to watch the unsorted files. Sounds like a Plex issue, take a look at the PMS logs.

**Comment by squarefrog** [comment]
OK I'll move this there. I dont have this issue with Couch Potato, and didn't see this behaviour with SickRage, so presumed it was a bug.
