### ISSUE TITLE
ProcessDownloadDecisions Error

### ISSUE THREAD

**Issue by theOptimizer** [Sonarr/Sonarr#1094]
For the last few weeks I've been getting random errors when Sonarr tries to process a failed TV Show from NzbGet.  Below is an example from my logs tonight where two shows failed.

I'm not sure what the issue is as this tends to work sporadically.

![image](https://cloud.githubusercontent.com/assets/6667779/12603205/298852b6-c476-11e5-9ebe-acc17bee6d39.png)

![image](https://cloud.githubusercontent.com/assets/6667779/12603226/553a30c8-c476-11e5-966b-53aead506ca2.png)

**Comment by markus101** [comment]
Please use the forums for support.

You will need to supply logs with mono running with the `--debug` flag as the included logs do not show line numbers. Trace logs would be ideal as the response from NZBGet will be included.
