### ISSUE TITLE
IPTorrents search possibility?

### ISSUE THREAD

**Issue by Ricky54326** [Sonarr/Sonarr#1096]
Is IPTorrents searching a possibility? CouchPotato is able to do so even though there is a lack of a search API: https://github.com/RuudBurger/CouchPotatoServer/blob/e6fa8b8b9db3c7bdf936f8de66337a86bcaebda5/couchpotato/core/media/_base/providers/torrent/iptorrents.py

I'm happy to help if this is possible but I haven't looked through the Sonarr codebase yet, and I am not familiar with it.

**Comment by JayMan6014** [comment]
Jackett will allow a IPTorrents Search.

**Comment by Ricky54326** [comment]
Have Sonarr devs accepted that as the main solution? If so, totally fine. Just curious

**Comment by markus101** [comment]
We have no plans to support sites that don't have an API via screen scraping, Jackett is our recommended solution.

**Comment by ayancey** [comment]
IPTorrents actually does have the ability to search with RSS, it just isn't obvious, what with it not being mentioned anywhere.

# Example:

### Returns x265 results with no search query
```https://iptorrents.com/torrents/rss?u=OMITTED;tp=OMITTED;99;download```

```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
  <channel>
    <title>IPT</title>
    <link>https://iptorrents.com</link>
    <description>IPT</description>
    <item>
      <title>Shades of Blue S02E06 720p HEVC x265-MeGusta</title>
      <link>https://iptorrents.com/download.php/2257402/Shades.of.Blue.S02E06.720p.HEVC.x265-MeGusta.torrent?torrent_pass=<!-- OMITTED --></link>
      <pubDate>Mon, 10 Apr 2017 00:51:31 +0000</pubDate>
      <description>269 MB; TV/x265</description>
    </item>
    <item>
      <title>The Legend of Master Legend S01E00 Pilot 1080p HEVC x265-MeGusta</title>
      <link>https://iptorrents.com/download.php/2257398/The.Legend.of.Master.Legend.S01E00.Pilot.1080p.HEVC.x265-MeGusta.torrent?torrent_pass=<!-- OMITTED --></link>
      <pubDate>Mon, 10 Apr 2017 00:44:20 +0000</pubDate>
      <description>466 MB; TV/x265</description>
    </item>
    <item>
      <title>The Get Down S01E11 720p HEVC x265-MeGusta</title>
      <link>https://iptorrents.com/download.php/2257396/The.Get.Down.S01E11.720p.HEVC.x265-MeGusta.torrent?torrent_pass=<!-- OMITTED --></link>
      <pubDate>Mon, 10 Apr 2017 00:43:49 +0000</pubDate>
      <description>1.08 GB; TV/x265</description>
    </item>
    <!-- trimmed the rest of the results -->
  </channel>
</rss>
```

### Returns x265 results with a search query
```https://iptorrents.com/torrents/rss?u=OMITTED;tp=OMITTED;99;download;q="family guy"```

```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
  <channel>
    <title>IPT</title>
    <link>https://iptorrents.com</link>
    <description>IPT</description>
    <item>
      <title>Family Guy S15E17 720p HEVC x265-MeGusta</title>
      <link>https://iptorrents.com/download.php/2237336/Family.Guy.S15E17.720p.HEVC.x265-MeGusta.torrent?torrent_pass=<!-- OMITTED --></link>
      <pubDate>Mon, 27 Mar 2017 01:46:11 +0000</pubDate>
      <description>168 MB; TV/x265</description>
    </item>
    <item>
      <title>Family Guy S15E16 720p HEVC x265-MeGusta</title>
      <link>https://iptorrents.com/download.php/2228471/Family.Guy.S15E16.720p.HEVC.x265-MeGusta.torrent?torrent_pass=<!-- OMITTED --></link>
      <pubDate>Mon, 20 Mar 2017 01:32:30 +0000</pubDate>
      <description>168 MB; TV/x265</description>
    </item>
    <item>
      <title>Family Guy S15E15 720p HEVC x265-MeGusta</title>
      <link>https://iptorrents.com/download.php/2219033/Family.Guy.S15E15.720p.HEVC.x265-MeGusta.torrent?torrent_pass=<!-- OMITTED --></link>
      <pubDate>Mon, 13 Mar 2017 05:39:34 +0000</pubDate>
      <description>155 MB; TV/x265</description>
    </item>
    <!-- trimmed the rest of the results -->
  </channel>
</rss>
```

**Comment by Taloth** [comment]
Last year the IPT staff contacted us about them being interested in implementing the Torznab API specification. I haven't heard that they actually did that, but it was something they were considering. I don't know the status, might be interesting to inquire about that.
The thing is that the torznab spec is superior, especially for the indexer side. Coz the spec supplies separate fields for tvdbid (if available), season number & episode number in the form of `&tvdbid=1234&season=1&ep=3`. (or if tvdbid isn't available, `&q=My%20Series&season=1&ep=3`)
This isn't just easier for Sonarr, it's much more efficient on the indexer side, since they can deal with all the variations (S01E03, 1x03, S01E03E04, 'Season 3', etc) by parsing their release name and indexing the values in the database.

**Comment by Anahkiasen** [comment]
Any news on their progress implementing it or is it still at the planning stage?

**Comment by Taloth** [comment]
I haven't heard anything about it. I'm not going to be involved.
