### ISSUE TITLE
Ignore releases with codec

### ISSUE THREAD

**Issue by olehumborstad** [Sonarr/Sonarr#1098]
My arm based media center's can't play HEVC.x265 codec. Please add feature for ignoring releases with "HEVC.x265"?

**Comment by baz1860** [comment]
That option is available already; there's an option to blacklist certain
words, just add hevc and x265 and sonarr will auto-reject releases with
that in the title.

**Comment by olehumborstad** [comment]
Brilliant! I did not see that "Restriction" tab under "Settings" - "Indexers" until now, thanks! :+1:
