### ISSUE TITLE
Download Propers setting is causing multiple downloads

### ISSUE THREAD

**Issue by suneetk92** [Sonarr/Sonarr#1101]
Hi,
I have set the value of Download Propers to Yes. My Profile is set to 720p HDTV only. 
Just today i found this issue - For Suits Season 5x11 (71), sonarr added Suits.S05E11.720p.HDTV.x264-KILLERS[rartv] initially in the queue and after sometime it added Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS[rartv] also in the queue. now both these versions are in the queue for downloading through deluge torrent client.
I assume this is a bug, as when sonarr grab the REPACk version then it should have marked the previous (normal) version as marked as failed and also remove it from client download list so to block it from getting downloaded at the first place. 

Attaching some evidence: 
![queue tab](https://cloud.githubusercontent.com/assets/12783242/12653388/53d86114-c615-11e5-83e2-12c7577100e0.PNG)
![season history tab](https://cloud.githubusercontent.com/assets/12783242/12653406/6b666628-c615-11e5-9998-5ec37e3553d1.PNG)
![history tab](https://cloud.githubusercontent.com/assets/12783242/12653392/54780a16-c615-11e5-963d-e69c21bb1561.PNG)

Log files:
[nzbdrone.10.txt](https://github.com/Sonarr/Sonarr/files/108595/nzbdrone.10.txt)
[nzbdrone.11.txt](https://github.com/Sonarr/Sonarr/files/108596/nzbdrone.11.txt)

**Comment by markus101** [comment]
Please use the forums for support.

This is not a bug, the non-REPACK (a PROPER by the same release group) was grabbed first (nothing that could have been blocked). Sonarr does not remove downloads from the queue when a new one is found, something we're considering for a future release though.
