### ISSUE TITLE
Issue parsing iTunes style file format when episode number is followed by a number

### ISSUE THREAD

**Issue by rglink** [Sonarr/Sonarr#1103]
When parsing series which are managed by an iTunes library everything seems to work normally (format: Season {season:0}/{episode:00} Episode name), except in the case the episode number is followed by a number: '11 404.mp4'. When adding the season number in front like this: '2-11 404.mp4' everything seems to work fine. Another issue is when the episode title in this style contains another style: '07 The Big 1-2'. In this case the episode is not recognized because Sonarr probably prefers the '1-2' style as a convention. I tried to remove the minus sign but the issue persisted, after replacing it with an underscore the problem was solved. Manually adding season numbers or changing these episode names is a hassle. Since iTunes automatically adds the title of the episode to the file name, when fully automating your tv shows (and automatically adding metadata) these issues arise multiple times in my library.

**Comment by markus101** [comment]
Unfortunately the iTunes format is awful for automation especially in the cases you mention here. We're doing what we can to parse them, but unfortunately given the lack of explicit markers in the file names its all guess work and I don't see that changing without a improvement in the file names they use or a significant change to how things are parsed (and even then it would be a crap shoot).

Added these cases to: https://github.com/Sonarr/Sonarr/issues/457 we'll have to see what we can do when we pick that one up.
