### ISSUE TITLE
More information when Sonarr is unable to access a path

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1106]
`Import failed, path does not exist or is not accessible by Sonarr: W:\usenet\complete\TV\Criminal.Minds.S06E03.720p.WEB-DL.DD5.1.H264-NFHD` doesn't explain much about possible causes (or solutions).

On Windows we could check if the path is a Mapped Network Drive AND Sonarr is running as a service and point them at the FAQ about why its bad and how to fix it, although some people will likely not really understand how to fix it, so we'll have to explain it again anyways.

If the path is for a different OS we tell them to setup a remote path mapping and if we can't determine the issue, tell them to check the permissions and then check them again if its still happening because 99% chance its permissions.

**Comment by danielb2** [comment]
I've deleted the path because it's no longer relevant, but Sonarr keeps trying to import from there anyway. How can I get rid of these error messages in the log files ?

**Comment by lommaj** [comment]
I find the logs to be lacking some information so that I would be able to fix the issue.

![image](https://user-images.githubusercontent.com/177133/46831087-05a82a80-cd68-11e8-9726-a0724e730987.png)

Would be great to get the series name in the log that way we would be able to fix the series' path.

**Comment by lommaj** [comment]
perhaps this should go into a different issue

**Comment by markus101** [comment]
Go to Series Editor to view the series with that root folder. We're not going to list out every matching series.

**Comment by lommaj** [comment]
okay, so the process would be to look through every series in order to find the one that is being listed in the log by matching it up to the root folder?

**Comment by lommaj** [comment]
actually - im unsure of the value of this log at all if its not telling you which series it is having the issue with.
