### ISSUE TITLE
Adding Windows 8/10 Tile info

### ISSUE THREAD

**Issue by Gobelet** [Sonarr/Sonarr#1108]
Hello,

I was trying to pin a shortcut to my Sonarr install, and I saw that it used the MS Edge icon instead of a Sonarr icon. CouchPotato has a special tile design, however. Here's what's in the header of CouchPotato:

&lt;meta name="msapplication-TileColor" content="#f85c22">
&lt;meta name="msapplication-TileImage" content="/couchpotato/static/images/icons/windows.png">
&lt;meta name="msapplication-square70x70logo" content="/couchpotato/static/images/icons/windows.png">
&lt;meta name="msapplication-square150x150logo" content="/couchpotato/static/images/icons/windows.png">
&lt;meta name="msapplication-square310x310logo" content="/couchpotato/static/images/icons/windows.png">
&lt;link href="/couchpotato/static/images/icons/favicon.ico" rel="icon" type="image/x-icon" />

This would be a nice, easy addition to make Sonarr prettier when pinned on a W10 Mobile / Windows 10 home screen/start menu.

What do you think?

**Comment by markus101** [comment]
Hanselman guide: http://www.hanselman.com/blog/MakeAWindows81PinnedLiveTileForYOURWebsiteInMinutes.aspx

**Comment by markus101** [comment]
This is taken care of in the v3 work.
