### ISSUE TITLE
Transmission-Qt support

### ISSUE THREAD

**Issue by anonsubmitter** [Sonarr/Sonarr#1113]
Is [Transmission-Qt](http://sourceforge.net/projects/trqtw/) supported on Sonarr? [I see that Sonarr supports Transmission](https://github.com/Sonarr/Sonarr/wiki/Supported-DownloadClients), but I'm not sure if that applies to the Windows fork (Transmission-Qt) as well. If Transmission-Qt is not supported, could support be added for it?

**Comment by markus101** [comment]
Yes it does.
