### ISSUE TITLE
JDownloader 2 BETA support

### ISSUE THREAD

**Issue by anonsubmitter** [Sonarr/Sonarr#1114]
Could [JDownloader 2 BETA](http://jdownloader.org/) be added as a supported download client? It's a download manager for filehosting sites. If you need to add indexers for filehosting sites to get this to work, I know of a few good ones.

**Comment by markus101** [comment]
At this time we have no plans to support other protocols and will be sticking with Torrents and Usenet.

**Comment by anonsubmitter** [comment]
Ok.

**Comment by cschnack24** [comment]
Anything new to this topic?
Because when Drone Factory will be disabled, there ist no way automatically import files from other clients

**Comment by markus101** [comment]
No plans for other protocols.

You can use the API to automatically import still though, which is better because you tell Sonarr when to import, avoiding partial files from being imported. https://github.com/Sonarr/Sonarr/wiki/Health-Checks#drone-factory-is-deprecated covers the options available.
