### ISSUE TITLE
Sonarr has wrong season number

### ISSUE THREAD

**Issue by ProtoJazz** [Sonarr/Sonarr#1116]
Im trying to setup sonarr, and for the most part it works, but for some reason on one series it says season 13, but when it searches it looks for season 12. It is supposed to be season 13. Is this something I need to fix or setup ?

**Comment by markus101** [comment]
Please use the forums for support, but this is covered in the FAQ: https://github.com/Sonarr/Sonarr/wiki/FAQ#how-does-sonarr-handle-scene-numbering-issues-american-dad-etc
