### ISSUE TITLE
Sonarr removing completed download from uTorrent

### ISSUE THREAD

**Issue by niczoom** [Sonarr/Sonarr#1120]
In Sonarr I have 'Completed Download Handling' set to Enable=Yes and Remove=NO.

Once a download has completed in uTorrent, Sonarr then copies this file to another location (as per my setup), But it also physically removes (deletes) the file from the uTorrent download directory even though I have 'Remove=NO'.

It does not remove the entry in uTorrent though. This has only started happening around a few weeks ago...sometime in Jan I believe.

**Comment by markus101** [comment]
Please use the forums for support. We'll need Debug logs of the import to examine the bahaviour.

Also make sure the Drone Factory is not being used for importing.
