### ISSUE TITLE
Request: Ability to test all indexers

### ISSUE THREAD

**Issue by feld** [Sonarr/Sonarr#1121]
If you have an internet issue or some other anomaly that causes Sonarr to mark all your indexers unavailable it is very tedious to test all of your indexers if you have many setup. It would be fantastic if a button could be added that would allow you to test all of your indexers to get them back online quickly.

It might be reasonable to hide this under the "Advanced" settings option.

**Comment by markus101** [comment]
There are changes in the develop branch that prevent the back off from escalating if the connection fails, which should deal with the problem without having to test them all. We'll also be looking to improve this down the road, but its very unlikely that it will be in the form of a test all button thats sole purpose is to deal with this.

**Comment by Taloth** [comment]
See https://github.com/Sonarr/Sonarr/commit/0d19f645e8055b6d1fda2e58430b4844e930ce50

**Comment by Ozzah** [comment]
Almost 3 years later, this is still an issue. Saying the system will not escalate on a connection failure does not address the root concern. An internet connectivity issue is just one possible cause. One example: when using an abstraction layer such as Jackett, if that system is unavailable or unreachable (for any number of reasons), then the use still has to test each indexer one-by-one, which is exactly what this feature request is concerned with. I think a "Test All" button is definitely needed, and is trivial to implement. It does no harm and covers all use cases.

Also, there really needs to be visual cues on the indexers list so the user can immediately see which ones are unavailable (red background colour, a red triangle in the corner, etc.)

**Comment by lems111** [comment]
This feature would be useful, especially due to this issue:
https://github.com/Sonarr/Sonarr/issues/2802

**Comment by deecypher** [comment]
Still very much an issue...please see what you can do. I have dozens of indexers and the tedium is brutal.

**Comment by Resalith** [comment]
Still an issue ): Is there a cmd comman to test maybe? Maybe a workaround would be to write a script that re-tests. Anything to avoid refreshing one by one manually...

**Comment by neogamaes** [comment]
Yes, same issue here.. Testing them one by one is working and doing a Health Check does not help.
