### ISSUE TITLE
Add Safari 9.0 Pinned Tab Icon

### ISSUE THREAD

**Issue by nikdoof** [Sonarr/Sonarr#1122]
Sonarr currently doesn't have an icon for Safari 9.0's pinned tab feature

[Details on creating an icon](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html), Essentially its a black only SVG with transparent background.

**Comment by NathanTheGr8** [comment]
![sonarr2](https://cloud.githubusercontent.com/assets/2585114/12864987/e457d6fc-cc64-11e5-96ec-e57ec964db75.png)

That is obviously a png but I have the svg, how is that?

**Comment by NathanTheGr8** [comment]
![sonarr](https://cloud.githubusercontent.com/assets/2585114/12876810/53101820-cdcd-11e5-86de-06bf25e62fb9.png)

How is that for the black and white logo? svg below, wouldn't render


[sonarr.svg.zip](https://github.com/Sonarr/Sonarr/files/121015/sonarr.svg.zip)

**Comment by xelra** [comment]
Looks very nice. Goes with the whole translucent trend and is definitely a step upwards from the forced white backround. That is if, I hope, everything white in that picture is supposed to be transparent.

I think this would make a very nice new logo in general. Maybe for v3?

**Comment by NathanTheGr8** [comment]
https://gist.github.com/markus101/8b48c9e2a4de9d598338
That is the design I included in my fork. Mark made it obviously. I personally liked it with the circle but his is also much less janky then mine. I am not great with svg software and did some weird things to get the white transparent.

**Comment by xelra** [comment]
I think I kinda like it more with the circle. It also looks a bit like an eye. :)
