### ISSUE TITLE
Type Anime - Unable to parse episodes from release name

### ISSUE THREAD

**Issue by elryo** [Sonarr/Sonarr#1124]
Hello,

I've a problem with the serie type "Anime".
The indexer found the releases but i can't start the download.
I've the following rejection reason  "Unable to parse episodes from release name".
See the screehshots for more detail.

Have you got a bugfix or a simple work around?
Thank you.
Lorenzo.

PS : the version is 2.0.0.3732 - Jan 15 2016

![sonarr-cfg1](https://cloud.githubusercontent.com/assets/16834099/12865762/c7ac9c30-ccb5-11e5-92a6-77ef775d7892.PNG)
![sonarr-pb1](https://cloud.githubusercontent.com/assets/16834099/12865763/c7ae86a8-ccb5-11e5-905f-d8208f705cbf.PNG)

**Comment by markus101** [comment]
The series type isn't known/used when parsing as Sonarr needs to parse it to see if it matches a known series/episode.

These releases are not standard for anime and are not parsed as anime and there is no easy solution to make them parse as anime. Improving the parser is something we'll be working towards in https://github.com/Sonarr/Sonarr/issues/457.

I've added this as another use case to the advanced parser issue.

**Comment by elryo** [comment]
I understand.
I hope the advanced parser can resolve it.
Unfortunately, anime (manga) release use an absolute number and not the conventional naming "sxxexx" such as tv show.
Thank you for your reply.

**Comment by markus101** [comment]
They also use a pretty consistent naming convention, which these releases don't follow, `Naruto Shippuden 433 VOSTFR 480p HDTV x264 [Resistance]` should have no problems.

**Comment by kriefsacha** [comment]
In mine it doesn't find anything , i think because the name he has is Naruto Shippuuden with two "u" , do you know how i can tell him that it's just with one ? Give him another name to the anime ? I don't find how to do that
