### ISSUE TITLE
Manual Import ability to select or deselect items based on rejection reason

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#1127]
Basically running the indexer downloaddecision logic. Useful to bulk import wanted stuff from a portable mass storage device.

**Comment by markus101** [comment]
Taking this further we should allow users to unselect things that are rejected for certain reasons.

I think we’ll want to to pass back a enum for the rejection instead of relying on a long string as well.

**Comment by gimpyestrada** [comment]
> Taking this further we should allow users to unselect things that are rejected for certain reasons.
> 
> I think we’ll want to to pass back a enum for the rejection instead of relying on a long string as well.

I like the idea of selecting based on certain reasons, but I also don't want to hold up a more simple feature because the end goal is harder to do, if that makes any sense.  Rather than wait a year for feature 1, 2, 3, and 4 take an agile approach and just take the first bite of feature 1.

**Comment by gimpyestrada** [comment]
I wanted to comment here that there are a few ways I can see to accomplish the goal:

1. add a box that functions as "only select upgrades"
2. add a box that functions as "only deselect problem episodes"
3. allow the list to be sorted by column and then a shift-click on a range of red ones would also accomplish it, though less elegantly
4. Group the problem episodes all at the top or the bottom of the dialog, again allowing for shift-click selection.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
