### ISSUE TITLE
Replace with HEVC/X265 - Reduce Library Size

### ISSUE THREAD

**Issue by smidley** [Sonarr/Sonarr#1130]
It would be nice to have the ability for sonarr to replace existing files with the HEVC/X265 versions of the episode.  This could be an option that will only grab files that have the same quality (example: 1080p WEB-DL).

This would greatly reduce the file size of episodes in your library.

**Comment by markus101** [comment]
This may come as part of https://github.com/Sonarr/Sonarr/issues/385 (not yet determined if it will override existing files of the same quality), but there are no plans to support anything specific for x264 or x265.
