### ISSUE TITLE
Allow AppData directory to be configured via settings page 

### ISSUE THREAD

**Issue by eyegeegeewhy** [Sonarr/Sonarr#1132]
Please allow the AppData directory to be updated via the settings page.

**Comment by markus101** [comment]
This isn't possible, Sonarr needs to know the location when it is starting up and there is no way to know if the value is stored in settings.

**Comment by eyegeegeewhy** [comment]
Thanks for the quick answer, apologies if this is the wrong place to ask but is there a way of moving the  AppData path. I see some people mention -data at startup in forum posts bust cant find a good source of info on this.
