### ISSUE TITLE
REQUEST: Add SimplyNZBs to Add Indexer Newznab Preset

### ISSUE THREAD

**Issue by SimplyNZBs** [Sonarr/Sonarr#1134]
REQUEST: Add [SimplyNZBs](https://simplynzbs.com) to Add Indexer / Newznab Preset

![image](https://cloud.githubusercontent.com/assets/16881594/12918919/b198f476-cf39-11e5-8112-fab8ce4bd5ab.png)

**Comment by Taloth** [comment]
Done
