### ISSUE TITLE
Restart From Web UI Crashes App

### ISSUE THREAD

**Issue by magallz1** [Sonarr/Sonarr#1135]
**Platform:** OS X "El Capitan" (10.11.3)
**Mono:** v4.2.2
**Sonarr:** 2.0.0.3732

**Description**
In the web UI, going to System then clicking on the "Restart" button, causes the app to crash with the following error:
```
[Info] LifecycleService: Restart requested.
open: unrecognized option `--debug'
Usage: open [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-b <bundle identifier>] [-a <application>] [filenames] [--args arguments]
Help: Open opens files from a shell.
      By default, opens each file using the default application for that file.
      If the file is in the form of a URL, the file will be opened as a URL.
Options:
      -a                Opens with the specified application.
      -b                Opens with the specified application bundle identifier.
      -e                Opens with TextEdit.
      -t                Opens with default text editor.
      -f                Reads input from standard input and opens with TextEdit.
      -F  --fresh       Launches the app fresh, that is, without restoring windows. Saved persistent state is lost, excluding Untitled documents.
      -R, --reveal      Selects in the Finder instead of opening.
      -W, --wait-apps   Blocks until the used applications are closed (even if they were already running).
          --args        All remaining arguments are passed in argv to the application's main() function instead of opened.
      -n, --new         Open a new instance of the application even if one is already running.
      -j, --hide        Launches the app hidden.
      -g, --background  Does not bring the application to the foreground.
      -h, --header      Searches header file locations for headers matching the given filenames, and opens them.

```
This causes one to have to relaunch the app entirely instead of having a quick restart.

**Expected Behavior**
Clicking on the restart button should cause the app to simply reload with out having to start everything back up again.

**Comment by markus101** [comment]
The log shows the `open` application being executed, which Sonarr doesn't run. A restart runs `mono --debug /path/to/NzbDrone.exe`.

If you run `mono --debug /path/to/NzbDrone.exe` in terminal what result do you get? (Replace `/path/to/` with the proper path).

**Comment by magallz1** [comment]
When I run `mono --debug /path/to/NzbDrone.exe` from terminal, the restart does work.  I seem to be only having this problem when this command is run through launchd.  Since this is not a true bug with Sonarr, I'll close this out and concentrate on muscling launchd to play nice.
