### ISSUE TITLE
Manual Import: Add Filtering / File Selection Before Processing

### ISSUE THREAD

**Issue by Terebi42** [Sonarr/Sonarr#1142]
If you try to do a manual import against a folder with a lot of files in it (for example, the sonarr download folder) there are several problems

1) Takes a long time (several minutes) to render
2) UI is essentially unusable because action buttons are not visible due to div overflows and scrolling

Ideas : 
If a large number of files are detected, defer trying to identification of the files until after the selections have been made. 

Add filters (filename primarily?) to find what you are trying to import

By default exclude files that were already successfully imported (If sonarr missed one file due to bad naming, but its in the same download directory, you have to sort through all of the files that were already successful. (would require sonarr to keep an index of imported files?)

Move action buttons to locations that are always visible (absolute positioning? Outside the scrolling div?)

**Comment by markus101** [comment]
Are you not able to choose a sub folder?

1. Can't do much there, its because it needs to process them, which it would need to do to any comparison
2. Sounds like that is due to: https://github.com/Sonarr/Sonarr/issues/745

> If a large number of files are detected, defer trying to identification of the files until after the selections have been made.

I don't see us doing this, its going to be an arbitrary decision to what constitutes a large number.

> Add filters (filename primarily?) to find what you are trying to import

This seems reasonable, similar to the series filter, it would be based on the title I'd think.

> By default exclude files that were already successfully imported (If sonarr missed one file due to bad naming, but its in the same download directory, you have to sort through all of the files that were already successful. (would require sonarr to keep an index of imported files?)

This would require processing all the files + checking history, not opposed to it, but it would likely increase the wait time.

> Move action buttons to locations that are always visible (absolute positioning? Outside the scrolling div?)

This will be coming in v3.

**Comment by Terebi42** [comment]
I have sonarr configured to use a tag in the torrent client, and I have the torrent client configured to put the tag into a folder. But that still results in every show that sonarr downloads being in the same folder. 

So "choose a subfolder" doesn't really help, because everything is in the same folder.

Why would you need to process all the files first? Couldn't you filter out the filenames based on what had already been processed? (eg pretend that file doesn't exist?)

Another "fix" would be to add the series name as a tag, which would then at least split the folder structure for downloading some.
