### ISSUE TITLE
Manual/Automatic Searches Not Finding Results

### ISSUE THREAD

**Issue by JadeTiger** [Sonarr/Sonarr#1144]
When I try to get any searches, manual or automatic, there is nothing found. I've checked on various popular TV shows where results should be found, but I get nothing. Everything should be set up fine. I've got it linked in Utorrent, through KickAss Torrents. This is my first time doing anything like this, though. Does anyone know what I might be doing wrong? I would appreciate any help!

**Comment by markus101** [comment]
We use the forums for support, where you have already posted: https://forums.sonarr.tv/t/manual-automatic-searches-not-finding-results/9519
