### ISSUE TITLE
Audio Channels parsed instead of Season and Episode numbers

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1147]
```
Mad.Men.S05E01-E02.720p.5.1Ch.BluRay.mkv
And: Mad.Men.05x01-02.720p.5.1Ch.BluRay.mkv
And: Mad.Men.S05E01-02.720p.5.1Ch.BluRay.mkv
```

All get picked up as 5x01 only.

**Comment by Taloth** [comment]
@markus101 Test shows that it gets parsed properly. Do you know if it was fixed in the past?

**Comment by markus101** [comment]
Must have been, if there aren't any tests for it already let's add them and close it, otherwise close it?
