### ISSUE TITLE
Do not remove period from end of episode name (ie. in 24  100 A.M. - 200 A.M.)

### ISSUE THREAD

**Issue by Bodertz** [Sonarr/Sonarr#1151]
With 24, the renamer has to get rid of some invalid characters. `Day 3: 1:00 A.M. - 2:00 A.M.` would be changed to `Day 3 100 A.M. - 200 A.M.` to get rid of the colons. I would prefer that `:` was replaced with `꞉ (U+A789)` or similar, but that's not likely to happen, so I'm fine.

However, with 24, every episode name ends in a period, and for some reason, Sonarr doesn't like that. I thought it would be because Windows can't handle files named `example..txt`, but it seems to be able to, so I don't know. Is it just an aesthetic concern? If so, I'd prefer it check that the period in the episode name is actually touching the extension before removing it.

My episode naming scheme is `24 - 2x01 - 'Day 2 800 A.M. - 900 A.M.'.mkv`. Sonarr wishes to rename that to `24 - 2x01 - 'Day 2 800 A.M.-900 A.M'.mkv`. The removal of the spaces isn't Sonarr's fault (that's TheTVDB's or perhaps Fox's for inconsistently naming the episodes) but the removal of the final period is.

Why is the final period removed?
###### Finale period is removed

`24 - 2x01 - 'Day 2 800 A.M.-900 A.M.'.mkv` =>
`24 - 2x01 - 'Day 2 800 A.M.-900 A.M'.mkv`
###### Nothing

`24 - 2x01 - 'Day 2 800 A.M.-900 A.M.'.mkv` =>
`24 - 2x01 - 'Day 2 800 A.M.-900 A.M.'.mkv`

**Comment by markus101** [comment]
Its purely aesthetic, in the case you describe its because we're trimming the period without knowing that its at the end of the file name thats being built. I'm not sure of the original reason why we trim the trailing period, but it likely comes from it being weird to include it in this format: `24 - 2x01 - Day 2 800 A.M.-900 A.M.-ReleaseGroup.mkv` (as well as others).

I'll let one of the other devs weigh in, on what we want to do here, but I'm leaning towards not supporting this as there are a lot of edge cases with doing so and this looks like the more correct option.

**Comment by Bodertz** [comment]
I see that it also removes trailing ellipsis. I assume that's the usual way that dots end up at the end of an episode title.

`Breaking Bad - 1x02 - Cat's in the Bag...-ReleaseGroup.mkv` =>
`Breaking Bad - 1x02 - Cat's in the Bag-ReleaseGroup.mkv`

> I'll let one of the other devs weigh in, on what we want to do here, but I'm leaning towards not supporting this as there are a lot of edge cases with doing so and this looks like the least impacting option.

Oh well. I'd prefer Sonarr not to make those aesthetic choices, but I don't find the Breaking Bad example to be ugly, so I'm not really the one to ask.

It isn't too difficult to change it back to the original title anyway.

**Comment by thezoggy** [comment]
which naming token are you using? `{Episode.CleanTitle}` ? `{Episode.Title}`

**Comment by thezoggy** [comment]
and honestly, who looks at file names anymore? are you not just scraping your media into kodi/plex/emby/etc?

**Comment by Bodertz** [comment]
> which naming token are you using? `{Episode.CleanTitle}` ? `{Episode.Title}`

I'm using `{Episode Title}`.

> here is a good test show + ep for you: Marvel's Agents of S.H.I.E.L.D. - 3x06 - Among Us Hide...

I don't have that episode. I could create a fake one, but I think my Breaking Bad example covers it. It would become `Marvel's Agents of S.H.I.E.L.D. - 3x06 - 'Among Us Hide'.mkv`

> and honestly, who looks at file names anymore? are you not just scraping your media into kodi/plex/emby/etc?

All the more reason not to make aesthetic changes :wink:.

**Comment by Taloth** [comment]
Zoggy, the diff is that it should only clean up dots if the chosen separator is a dot.

But we're not gonna change the renamer without extensive testcases coz this crap has been changed arbitrarily too many times.

**Comment by Bodertz** [comment]
Just want to add that the series folder for "Marvel's Agents of S.H.I.E.L.D." has also had it's final '.' removed.  I'd prefer it not be removed.  I imagine our aesthetic preferences align in this case?  I doubt it's the case that people are adding '-ReleaseGroup' to the end of the series folder as well...

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; 

Edge cases only
