### ISSUE TITLE
TV series in Sonarr doesnt actually have all the episodes listed. 

### ISSUE THREAD

**Issue by 84n5h33** [Sonarr/Sonarr#1154]
The actual first episode is missing and messes up the rest of the season's episodes. What it has listed as episode one is actually two, so on and so forth. Is there a way to manually edit a season of a show to change the episode number? i dont want to have to manually download and add the new episodes.

**Comment by 84n5h33** [comment]
TV show is Star Wars Rebels

**Comment by Nelluk** [comment]
Please use the Forums or IRC chat for problems like this.

This is due to [theXem episode mapping](https://github.com/Sonarr/Sonarr/issues/1154) and is really Sonarr behaving as expected. You cannot manually override it.

If you come into IRC support we can explain it more.
