### ISSUE TITLE
Change default username to root

### ISSUE THREAD

**Issue by iamtyce** [Sonarr/Sonarr#1157]
I can't for the life of me figure out how to change the default `user:group` to `root:root`.

The reason for this is so I can run all of my other apps (SAB, Transmission, Plex etc) on the same `user:group` setup.

I'm currently on Ubuntu Server 15.10 and running the latest version of Sonarr.

Any thoughts on where I can make those changes?

**Comment by baz1860** [comment]
Why do you want to?

It's considered 'a really bad idea' to run as root, and by doing so, you
also ensure that only root has access to the downloaded files. Unless
you're running everything as root (and that's a horrible horrible idea)
this seems less than optimal..

**Comment by thezoggy** [comment]
@iamtyce you just need to google on how to use/setup an init script

**Comment by iamtyce** [comment]
Ended up doing the right thing and using `user:nogroup` + adjusting all my other apps to do the same.. I knew running as `root` wasn't great but took the advice and did it properly.
