### ISSUE TITLE
Add support for BTDigg 

### ISSUE THREAD

**Issue by TerrorFactor** [Sonarr/Sonarr#1159]
I'd like to request support for BTDigg (btdigg.org) as a tracker. They give more and better results -especially for older content- than other public trackers.
They provide a seach API, so I suspect integration would be relatively easy.

**Comment by markus101** [comment]
I took a look and they don't appear to have an API that supports searching or at least I couldn't find any information on it. If they have a proper API we could consider it, otherwise it will not be added. If API documentation is available please link us to it below and we'll consider re-opening it.

**Comment by markus101** [comment]
Looks like API access is available by request, made a request, we'll see what they reply with.

**Comment by Taloth** [comment]
One, BTDigg isn't a tracker, mostly irrelevant detail though.
Two, it isn't an indexer either, coz I can't ask for it to return season x episode x for series xyz (preferably by tvmaze/tvdbid).

Pretty sure the api won't give us indexed results either. But throw up the idea, maybe he'll grab newznab/nzedb and write a fully function torznab indexer based on dht, that would be something.

**Comment by TerrorFactor** [comment]
Thanks for the feedback guys. You do have to contact them to get access to the API. I am not sure how Sonarr searches for episodes. I figured it was just by name, so it wouldn't be an issue then?
(OT: one of the biggest problems with Couchpotato imo, not searching by name, but only on imdb-ID)

I wasn't really sure what the proper term was for BTDigg. Everyone understands tracker, so that was the easiest option :)

**Comment by xelra** [comment]
BTDigg or any DHT search engine is a great thing. It kinda works similar to a Usenet search engine. It's pretty much the only thing you need to support every public torrent available. 

Just supplying Sonarr with search results is less than ideal though. It kinda works similar to a Usenet search engine. Ideally it sorts and categorizes all the torrents it finds, like newznab, and then provides a torznab api.
It would work out-of-the-box with Sonarr then, but for the first part, there'd be quite some work involved from BTDigg's side. I'm wondering whether BTDigg's developer would be interested. It would certainly be an evolution from DHT search engine to DHT indexer.

**Comment by TerrorFactor** [comment]
@markus101 Did you get a response?

**Comment by markus101** [comment]
Nope. I was talking with someone else that tried to get access and they never got a response either.

**Comment by grillba** [comment]
BTDigg is no more - you can close this one.
