### ISSUE TITLE
Add timeframe for propers

### ISSUE THREAD

**Issue by subzero79** [Sonarr/Sonarr#1161]
This seems reasonable, sometimes propers appear in the feed so late and you probably already watched the episode.

Also would be good to have the possibility to add limits to propers. Sonarr grabbed the other day 3 propers including the original release (that's for downloads)

**Comment by markus101** [comment]
A time frame seems pretty arbitrary, if you haven't watched it then you'd want it, but there is no guarantee that you have within the limit. If the user is going to watch and store the files then the best quality on disk makes sense, if they are going to watch and delete then that should be handled with "Unmonitor deleted episodes".

**Comment by Taloth** [comment]
Probably better if you script something for kodi & co to just unmonitor/delete the episode if you already watched it.

**Comment by subzero79** [comment]
Sorry didn't mean to be arbitrary as to impose or hard-code the time frame. I was just thinking about an option to add the time in hours or zero to disable.
I'll think about the script for delete/unmonitor, I usually do vacuum cleaning every two or three months

**Comment by markus101** [comment]
Pretty sure we have a hardcoded limit already to prevent years old releases from getting propered, so it would be optional, but its still arbitrary, just something you chose.

00:00 is available and grabbed
00:15 release is available for watching
00:30: start watching
01:00 finished watching
02:00 proper is released.

If you had set "do not download propers" after 12 hours, then you'd still end up with a proper for something you watched.

**Comment by Taloth** [comment]
7 days after the file got added to the collection.

**Comment by subzero79** [comment]
Well there is no point if is already hard-coded.
I am working on something with the kodi-sonarr api to see if I can toggle the monitor status once watched.
