### ISSUE TITLE
[WIKI] Systemd autostart

### ISSUE THREAD

**Issue by d2dyno** [Sonarr/Sonarr#1162]
The Systemd autostart script example given on the wiki page '[Autostart on Linux](https://github.com/Sonarr/Sonarr/wiki/Autostart-on-Linux)', does not work on Linux (Ubuntu specifically). The first and last EOF lines cause an error, and the ExecStart arguments should be separated like so (found on internet):

```
Environment=statedir=/opt/NzbDrone
ExecStart=/usr/bin/mono  ${statedir}/NzbDrone.exe
```

**Comment by Taloth** [comment]
First: http://stackoverflow.com/questions/2500436/how-does-cat-eof-work-in-bash

Secondly, what's wrong with:   
ExecStart=/usr/bin/mono /opt/NzbDrone/NzbDrone.exe
