### ISSUE TITLE
Default Size Limit

### ISSUE THREAD

**Issue by Torkiliuz** [Sonarr/Sonarr#1163]
Lately I've been getting a few false positives that are only about 320 KB in size. I've personally fixed this by setting the **Size Limit** to more than 0 MB, but I'd like to request that the default value is set to something more than 0. From what I saw the limit doesn't need to be more than about 20 MB for the false positives to be ignored.

**Comment by thezoggy** [comment]
been using this for awhile, no issues so far:
![size](http://zoggy.net/sonarr-quality.png)

**Comment by jcchristian** [comment]
I'm also very interested in something like that. Currently I have this:

![image](https://cloud.githubusercontent.com/assets/4141392/23099323/858515e6-f642-11e6-8181-3094fd4bde9c.png)

I never download below HDTV-720p, so I ignored those.

**Comment by markus101** [comment]
Done in the v3 work.

**Comment by thezoggy** [comment]
just to follow up on this since 2016, that I had to bump my webdl720 and higher qualities by 10-15%? to accommodate the fact they are including better audio/more multichannel audio. 

currently using:
![sonarr](http://zoggy.net/firefox_2018-11-23_15-41-03.png)
