### ISSUE TITLE
Multiple Instances (or Adding Show 'Owner' Tags)

### ISSUE THREAD

**Issue by LeeThompson** [Sonarr/Sonarr#1167]
Currently I am using SickBeard but I'd like to move to Sonarr.    (Mostly since SickBeard is extremely dead.)

However, I have several SIckBeard instance that run: Current Shows, Backlog, Special Fills, and finally one for friends.    (Since the big difference between current shows, backlog and special fills are the saerch engine order, I could probably go down to two but...)

I have Sonarr set up to run on 4 different ports, with 4 directory locations but.... Sonarr appears to explicitly disallow this with the SingleInstancePolicy class.

So my questions are:

1. If I compile Sonarr myself and disable SingleInstancePolicy.cs is it going to explode?   (I guess the better question is, what is the reasoning behind this function?)

2. Any chance of having an optional flag to disable SingleInstancePolicy (and, preferably, not have it explode?)

3. Alternately, if it's just not feasble for whatever reason, any chance of having tags so I could say, separate out my shows from my friends'?   (They can go to the same directory but when manging shows, I could see 'oh that's Bob's show' after I go 'what the hell is this?').

**Comment by markus101** [comment]
1. Updating, possibly other things. Single instance makes a lot of things easier and less things to support (such as the `--data` flag)
2. Not something we're considering
3. Tags are already possible, they are lowercase + numbers + dashes and can be set when editing the series (eventually thing will be part of add series as well) and they can be used to delay grabs on a per-tag basis

**Comment by LeeThompson** [comment]
3. That'll work, any chance they could be listed/filtered on in the series lists?

**Comment by markus101** [comment]
Yeah, thats the plan:

https://github.com/Sonarr/Sonarr/issues/566

Closing it out as we have something actionable already.
