### ISSUE TITLE
Sonarr Not Post Processing

### ISSUE THREAD

**Issue by DemetersRest** [Sonarr/Sonarr#1168]
Post processing is not consistent since switching from Sabnzbd to NZBVortex.  Logs are not showing errors that I can see.  Have turned on Trace logging, copy of log file attached.
[nzbdrone copy.txt](https://github.com/Sonarr/Sonarr/files/156398/nzbdrone.copy.txt)

Sonarr is grabbing the eps, NZBVortex is downloading them, however then they just sit in the completed folder.

Thank you in advance for your assistance. 

EDIT : Found and attached trace log.

**Comment by markus101** [comment]
NZBVortex isn't returning anything for the category `TV Shows`, double check that the category is set properly. If you're still having issues please open a thread on the support forums (https://forums.sonarr.tv).

`16-3-3 19:54:26.3|Trace|NzbVortexProxy|Response: {"result":"ok","nzbs":[]}`
