### ISSUE TITLE
Series with Nordic in title means danish, norwegian and swedish in subtitles or sound

### ISSUE THREAD

**Issue by nic0dk** [Sonarr/Sonarr#1169]
![image](https://cloud.githubusercontent.com/assets/14346463/13491535/1fd289f6-e133-11e5-8c90-e620f41c0895.png)
the release are named nordic in their titles and hold subtitles for scandinavian countries or sound files. but Sonarr see them as non-english release, is there any way we can allow them to be downloaded anyway?
i have made a tag that include Nordic in title name, but no change - im running with version 2.0.0.3732.

i see that you have a feature request on multi language under quality profile maybe it could solve this request as well?

**Comment by markus101** [comment]
Multi-language would likely help, but you can also force the grab via manual search. Required words don't supercede the language selected in the profile, so you can't force it to automatically grab.

**Comment by nic0dk** [comment]
Cheers mate. I'll just do the Manual add ;) thanks for a great software

**Comment by anderslo** [comment]
Isn't it a bug that the word "nordic" is considered a release with Norwegian language?  At least the trackers I use it means Nordic subs.  However, if the word "norwegian" is found in the name, then the language should be considered Norwegian.

I think this should be changed.

**Comment by samip5** [comment]
@anderslo You can actually find the reason for that behavior as "nordic" tag is programmically tagged as Norwegian even when that's not the case.
