### ISSUE TITLE
Request: Add "device" field to pushover connection

### ISSUE THREAD

**Issue by Schrottpresse** [Sonarr/Sonarr#1171]
For a 100% Pushover Integration, a "device" field for setting up a specific notification channel for a device is missing. This would be really great if possible.

(https://pushover.net/api)

**Comment by markus101** [comment]
Sonarr already supports the device ID field, looks like device is a new field that does the same thing, but its not clear how they handle renaming a device.

In order to maintain backwards compatibility Wed need to migrate from device ID to device or make this part of v3 to make a breaking change.

**Comment by ceptonit** [comment]
In the mean time, a custom script connection can be used instead.
Here's an example bash script I use on "On Download" events to send the notification to my android phone and ipad only:
```
#!/bin/bash

function push {
   curl -s -F "token=abcdefghijklmnopq1234" \
   -F "user=abcdefg0987654321" \
   -F "device=ipad,phone" \
   -F "title=$1" \
   -F "message=$2" https://api.pushover.net/1/messages.json
}

push "Now Available!" "${sonarr_series_title} - ${sonarr_episodefile_seasonnumber}x${sonarr_episodefile_episodenumbers} - ${sonarr_episodefile_episodetitles} [${sonarr_episodefile_quality}]"
```

**Comment by markus101** [comment]
Done in the v3 work.

**Comment by asyba** [comment]
> Done in the v3 work.

Can you add it to v2 also?

**Comment by asyba** [comment]
> In the mean time, a custom script connection can be used instead.
> Here's an example bash script I use on "On Download" events to send the notification to my android phone and ipad only:
> 
> ```
> #!/bin/bash
> 
> function push {
>    curl -s -F "token=abcdefghijklmnopq1234" \
>    -F "user=abcdefg0987654321" \
>    -F "device=ipad,phone" \
>    -F "title=$1" \
>    -F "message=$2" https://api.pushover.net/1/messages.json
> }
> 
> push "Now Available!" "${sonarr_series_title} - ${sonarr_episodefile_seasonnumber}x${sonarr_episodefile_episodenumbers} - ${sonarr_episodefile_episodetitles} [${sonarr_episodefile_quality}]"
> ```

@ceptonit Can you help me? I try that and is not working. I'm on Windows 10
