### ISSUE TITLE
Trying to add show C.O.P.S dosn't work at all

### ISSUE THREAD

**Issue by morpheus2n2** [Sonarr/Sonarr#1173]
Trying to add the Kids animated show C.O.P.S (1988) http://www.thetvdb.com/?tab=series&id=74946
Will not work there is no error given, it just wont add to library
All that shows in the log is "Adding Series [74946][C.O.P.S.] Path: [H:\Kids TV Shows\C.O.P.S] "
bot nothing is actually added!

**Comment by Taloth** [comment]
Works fine here. My guess is that you got the main table filtered on continuing shows.

**Comment by morpheus2n2** [comment]
nope this is the only show this happens to have added about 15 old ended shows today so its not a filter problem, I press the + button and instead of it disappearing and popping up adding in dose nothing at all :(

**Comment by morpheus2n2** [comment]
Update, I have manually put all the files in my show folder and tryed the "Add existing show" and still no luck.
this is all I get in my log
16-3-8 09:03:50.0|Info|SeriesService|Adding Series [74946][C.O.P.S.] Path: [H:\Kids TV Shows\C.O.P.S]
16-3-8 09:03:52.7|Info|SeriesService|Adding Series [74946][C.O.P.S.] Path: [H:\Kids TV Shows\C.O.P.S]
16-3-8 09:03:56.3|Info|SeriesService|Adding Series [74946][C.O.P.S.] Path: [H:\Kids TV Shows\C.O.P.S]
16-3-8 09:03:57.4|Info|SeriesService|Adding Series [74946][C.O.P.S.] Path: [H:\Kids TV Shows\C.O.P.S]
16-3-8 09:03:58.4|Info|SeriesService|Adding Series [74946][C.O.P.S.] Path: [H:\Kids TV Shows\C.O.P.S]
As you can see there's no info given as it acts like its done but it doesn't do a think lol

**Comment by markus101** [comment]
Closing in favour of forum post: https://forums.sonarr.tv/t/tv-show-refuses-to-be-added-to-library/9917
