### ISSUE TITLE
Add extra parameters to release/push api endpoint

### ISSUE THREAD

**Issue by subzero79** [Sonarr/Sonarr#1176]
Could be possible to consider to send extra parameters to the push api.

I am thinking about just size and tracker name.

The history at the moment just displays "null" as origin, and the size can also help for the quality profiles.

**Comment by markus101** [comment]
You should be able to set any of the parameters that manual search would return:

https://github.com/Sonarr/Sonarr/wiki/Release#get

**Comment by subzero79** [comment]
Thanks for the clarification. It works, just the size needs to be adjusted as only in bytes I guess, otherwise throws an exception the curl
