### ISSUE TITLE
Sonarr Forgets /Data Path On Update

### ISSUE THREAD

**Issue by LeeThompson** [Sonarr/Sonarr#1177]
When Sonarr updates with a custom /data path, it does not pass that back in and you end up with an empty Sonarr configuration.

Fortunately if you shut down and re-start with the proper parameters it works fine, but this makes me not want to run it with automatic updates enabled.

If passing command line parameters around isn't desirable or possible, one way around this would be to go ahead and store a small XML in ProgramData\NzbDrone (or \Sonarr) that was just the pointer to the actual data folder.

I.e.

```
<Config>
   <Data Path>C:\My Custom Path\</Data Path>
</Config>
```

**Comment by markus101** [comment]
The data flag isn't a supported flag, it was implemented for testing purposes.

It should be preserved during reboot and updates, we'll need to see trace logs of the update being applied and the update logs themselves to diagnose further. Please open a thread on https://forums.sonarr.tv with that information.
