### ISSUE TITLE
Indexer failures and manual tests - add setting (feature request)

### ISSUE THREAD

**Issue by ste7enm** [Sonarr/Sonarr#1178]
Presently, if your internet connection drops, Sonarr will fail to connect to the indexers' RSS feeds and then disable the indexers "for an increasing amount of time (up to 24h)."

Recently, I've been having trouble with my ISP and this default configuration of Sonarr is a big pain point. I'd like to be able to set that indexer timeout manually in the advanced settings so that it was, for example, only an hour before it tried connecting again (and didn't increase). I'd also like it if there was an easier way to re-initialize the indexers without having to go into each one and run a test one at a time every time this happened.

**Comment by Taloth** [comment]
Dupe https://github.com/Sonarr/Sonarr/issues/751

Atm in develop, will be in the next master release.

**Comment by ste7enm** [comment]
Sorry, hadn't seen that other one / found it in my search. Thanks a lot! Looking forward to this change.
