### ISSUE TITLE
Api calls intermittently fail

### ISSUE THREAD

**Issue by ktiedt** [Sonarr/Sonarr#1181]
Looking at my JS console, I see all /api/ requests for /health and /diskspace and log requests are failing intermittently (seemingly due to Unauthorized) -- but if I take the API key and append it using query params it clearly works...

This is latest sonar running in a Docker container (only oddity about my setup) -- everything appears to be working fine (except this).

**Comment by Taloth** [comment]
Capture the http requests include request&response headers and see what's different. Coz without more information we can't help you.
You say it's intermittent, so saying x-api-key header isn't working isn't accurate.

**Comment by ktiedt** [comment]
The API call only failed with the header, none of the tests with the query string failed, so it was more accurate to say what I said I believe.

I'll try and get the extra data this evening once I get home, thanks!

**Comment by ktiedt** [comment]
This may have been a culprit of XDG_CONFIG_HOME not being set in my Docker environment... Things appear to be running more smoothly since I found a reference to this path. Will update again tomorrow after burning things in a bit with the added var.

**Comment by ktiedt** [comment]
That did indeed appear to be the root cause of this problem. Sorry for the noise!
