### ISSUE TITLE
Not seeing Network Shared Folder

### ISSUE THREAD

**Issue by sltyler1** [Sonarr/Sonarr#1182]
Not sure when the change happened in the last couple of days, but on the latest Dev build. And my Sonarr is not finding my Network Shared Folder through VMware Workstation with my video files. I can browse the folder in Explorer and CouchPotato isn't having an issue with the folder. The system disk space in Sonarr only lists the C:\ drive and not the network drive either. When I browse in Sonarr everything is showing blank, I attached a screenshot.
![screenshot_09](https://cloud.githubusercontent.com/assets/11649367/13796795/ec4f5426-ead6-11e5-85e8-97319a939554.png)

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/wiki/FAQ#why-cant-sonarr-see-my-files-on-a-remote-server If you're still having issues take a look on the forums, plenty of posts on the same subject.
