### ISSUE TITLE
Torrent blackhole rarbg

### ISSUE THREAD

**Issue by neox387** [Sonarr/Sonarr#1183]
1. Rarbg magnet are not saved as torrent files, so blackhole doesn't work.  

2. Recently rarbg giving allot of problems with no token set

3. Watchdir for completed torrents should be optional, prefer to nzbToMedia them back.

**Comment by thezoggy** [comment]
upgrade to latest, fix for rarbg issues in latest dev

**Comment by Taloth** [comment]
1. Not expected on short term
2. Upgrade to latest dev
3. Just set it to an empty dir

**Comment by xori** [comment]
I'm still having this issue with v2.0.0.3953
