### ISSUE TITLE
Incorrect season matching from existing show

### ISSUE THREAD

**Issue by csnewman** [Sonarr/Sonarr#1184]
I already had all the episodes to Red Dwarf in the media folder so I decided to add the show to Sonarr incase of new episodes airing however it seems to be interpreting all the episodes incorrectly, Sonarr has worked fine with all the other shows I've added however this one seems to be having issues even though the naming format is pretty standard. 

Input: "/media/Red Dwarf/Season 08/Red Dwarf - S08 - E01 - Back In The Red - Part 01.avi"
Matched to: "Red Dwarf - 1x01 - The End"
Should Be: "Red Dwarf - 8x01 - Back In The Red (1)"

**Comment by thezoggy** [comment]
`S## - E##` does not look like is a valid naming format. use `#x##` or `S##E##` or any of the other valid formats..

**Comment by markus101** [comment]
As Zoggy mentioned this isn't a supported naming format. In this case it ends up matching `Part 01`, but it could also potentially match the season or episode numbers. This isn't a format we're considering supporting at this time.
