### ISSUE TITLE
Generic 2160/1080/720 cutoffs?

### ISSUE THREAD

**Issue by baldock88** [Sonarr/Sonarr#1185]
Hi there! 

I want to put forth a suggestion to implement cutoffs for certain qualities of any format. When setting a show to 1080 WEB-DL, if HDTV is downloaded first, it will still continue to try for WEB-DL downloading a second copy of the same quality. Can we get it setup to be able to just choose a cut-off of any 1080 version is considered meeting the cut-off?

Thanks!

**Comment by baz1860** [comment]
Unless I'm massively misunderstanding what you want to do, this is already possible; select 1080 HDTV and the cutoff and put 1080 WEB-DL above it. If the WEB-DL is available first, you'll get that, if not, when the HDTV is downloaded it'll stop looking for anything else

**Comment by baldock88** [comment]
I sincerely apologize, for some reason when trying to do this in one of my browsers, I couldn’t re-order the options, but it appears to be working in Chrome. I tried in Safari and it didn’t show the ability to change the order of qualities. Now that I see I can re-order the qualities, that makes much more sense and will work perfectly. The default had HDTV-1080 below WEB-DL-720, so it would delete the HDTV-1080 when it found WEB-DL-720. Thanks so much for following up! Really appreciate it!

Drew
