### ISSUE TITLE
WEB shows up as HDTV

### ISSUE THREAD

**Issue by MarkPash** [Sonarr/Sonarr#1186]
There are new scene rules regarding the naming of WEB content [http://img.rlsblog.se/tv/14/THE.2016.WEB.AND.WEBRIP.SD.HD.X264.RULESET.v1.0-WDX264/NFO.txt](url)

However Sonarr cannot identify releases correctly.

Example:
Crowded.S01E01.1080p.WEB.h264-QCF is coming up as 1080p HDTV

**Comment by Taloth** [comment]
Is now supported on the develop branch, (considered WEB-DL).
