### ISSUE TITLE
Cannot add download to qBittorrent queue

### ISSUE THREAD

**Issue by majora2007** [Sonarr/Sonarr#1187]
As of today (3/17/16), Sonarr cannot add any torrents to qBittorrent via WebUI. I have confirmed that the webUI settings work and attempted to manually search and click "download" button, but the error is displayed and the torrents are not downloaded.

I suspect do to use of HTTPClient.

**Comment by Taloth** [comment]
Should be fix in the new develop version (2.0.0.3971).

**Comment by majora2007** [comment]
Confirmed it is working, thanks.
