### ISSUE TITLE
Manual download

### ISSUE THREAD

**Issue by ferllings** [Sonarr/Sonarr#1188]
Hello,

Is there a way to use the "Completed Download Handling", but keep the file download process manual?

My download client (Sab) is on a remote server.
But my Internet access has limited data per month, so I need to be careful with what I retrieve from that server.
So I'm looking for an option to monitor the grabbed episodes, and select which ones I want to download locally and sort/rename.

**Comment by markus101** [comment]
Since SAB is on a remote system Completed Download Handling will only work if you use a remote path mapping to tell Sonarr where to look for those files. You could set that to a path that you will manually copy files to.

Nothing in Sonarr will handle this for you automatically.

**Comment by ferllings** [comment]
Thanks.
Yes, I'm using remote path settings.
I was hopping for a way to manually select the files to "handle" instead for logging the remote machine and move the files around.

Thanks anyway.

**Comment by markus101** [comment]
Manual import on Wanted: Missing might be of some use, but still quite a manual process.
