### ISSUE TITLE
Since 2.0.0.3953 downloaded shows via Sabnzbd is not imported

### ISSUE THREAD

**Issue by webbson** [Sonarr/Sonarr#1189]
Since I updated to 2.0.0.3953 on my windows server 2012 my shows aren't moved and renamed after download completes in Sabnzbd. 

In the activity tab they are moved from Queue to History, but no file move and rename is initiated neither is any download completed notifications sent. 

I found a temporary fix in disabling Completed Download Handling and setting drone factory instead, but this is sub-optimal since it leaves history in Sabnzbd.

**Comment by markisoke** [comment]
+1, having the same issues. 

Windows Server 2012 R2
Sonarr: 2.0.0.3953
Sabnzbd: 1.0.0

**Comment by markus101** [comment]
Please open a thread on the forums with trace logs.
