### ISSUE TITLE
Setting up twitter notifications complains about empty keys

### ISSUE THREAD

**Issue by justanotherdev123** [Sonarr/Sonarr#1191]
I'm setting up Twitter notifications by creating my own keys but when I enter the keys it throws:
```

HTTP Error - Res: [GET] https://api.twitter.com/oauth/request_token : 401.Unauthorized
{"errors":[{"code":32,"message":"Could not authenticate you."}]}
Invalid request Validation failed: 
 -- 'Access Token' should not be empty.
 -- 'Access Token Secret' should not be empty.
```

It seems to think it's empty when it's not, thus not allowing you to set up Twitter notications

**Comment by markus101** [comment]
Access Token and Access Token Secret are set automatically when using the `Connect to Twitter` button. I'm not having any issues setting it up. If you're still having issues please open a thread on the forums with trace logs.
