### ISSUE TITLE
Daily shows break when broadcast twice a day

### ISSUE THREAD

**Issue by baudehlo** [Sonarr/Sonarr#1192]
Judge Judy (don't hate me - my wife loves it) often broadcasts twice a day.

Such series generate the following error: "DailyEpisodeMatchSpecification: Multiple episodes with the same air date found" despite being separate episodes. Example screenshot attached.

![image](https://cloud.githubusercontent.com/assets/662371/13908625/ef440c12-eedc-11e5-9342-1c85f70682e0.png)

**Comment by thezoggy** [comment]
why not use 'standard' since they put S##E## in it

**Comment by baudehlo** [comment]
That complained that it was a daily show.

**Comment by markus101** [comment]
Can't parse as standard unless the date is also handled, searching would be messed up if it relies on title searching only offhand I'm not sure what KAT uses).

**Comment by baudehlo** [comment]
If the screenshot doesn't give enough info I'm happy to add more.

**Comment by markus101** [comment]
It's more about whether we want to support a shitty format for releases, KAT is a hell hole for poorly named things.

**Comment by Taloth** [comment]
There really is no good way to upload that series. tbh, I think that naming pattern is relatively decent considering the circumstances, it could've been much worse, like 2016 02 25 part 1.
I don't know if we can make a good regex for it to get both airdate and sxxexx, then later handle dupe airdates by checking ep nr. But it's worth looking in to.

**Comment by markus101** [comment]
That was my thought, basically check the air date is there, but rely on the season + episode numbers.
