### ISSUE TITLE
Update page could use more padding between change log lines

### ISSUE THREAD

**Issue by chancez** [Sonarr/Sonarr#1201]
<img width="734" alt="screen shot 2016-03-23 at 4 24 10 pm" src="https://cloud.githubusercontent.com/assets/1400401/14003941/c554e10e-f113-11e5-8d02-ab0eef411545.png">

Using OS X w/ Chrome Version 49.0.2623.87 (64-bit)

As you can see the icons aren't all evenly spaced apart. Might be a good idea to increase the padding/margins. Not a big deal/priority, just noticed it looked a bit funky today.

**Comment by markus101** [comment]
I'm not seeing this behavior in Chrome Version 49.0.2623.87 on Windows.

**Comment by markus101** [comment]
Not seeing this in OS X either. Is it zoomed in or possibly an extension causing it?
