### ISSUE TITLE
Remove exclamation points from filename

### ISSUE THREAD

**Issue by machstem** [Sonarr/Sonarr#1210]
I noticed today after adding a new show, several filenames had an exclamation (!) point in their episode title.

This prevents my QNAP from correctly seeing the files and in turn, prevents my plex from seeing the episodes listed.

If sonarr allowed for episode renaming individually by each series, I could remove the exclamation point from that series with a simple fix.

**Comment by machstem** [comment]
I should also say that plex runs on debian 8, mounting its drives by nfs exports

**Comment by markus101** [comment]
You can use `{Series CleanTitle}` and `{Episode CleanTitle}` to remove special characters from the series and episode titles.
