### ISSUE TITLE
SABnzbd Doesn't remove files for completed history items

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1213]
When removing a completed download (in SAB's history) from Sonarr's queue Sonarr will tell the download client (SAB in this case) to remove it along with the files. SAB will remove it from it's history, but will leave the files in place (silently).

We should cleanup the path ourselves, which means we'll need to make sure we have the path and remove it from disk if it still exists (ask SAB to do it, but double check).

Possible issues:

- Sonarr and SAB not on the same machine
  - Remote Path Mapping would work, but not likely setup
  - What if the path SAB reports DOES exist on the machine running Sonarr, but it has different content?

**Comment by markus101** [comment]
Looks like this is actually a bug on SAB's end and it should be removing the files, but sometimes doesn't.

**Comment by Taloth** [comment]
Is it a known issue that's being fixed?

**Comment by markus101** [comment]
Yeah, they're looking for the root cause.
