### ISSUE TITLE
Link specific indexers to specific clients

### ISSUE THREAD

**Issue by Londonlad95** [Sonarr/Sonarr#1215]
Hi,

Due to being a member of a private site it would be nice to be able to link specific indexers to specific clients so that I can use a proxy on the public client and no proxy on the private site client. Is this something which may be on the cards?

**Comment by Xaelias** [comment]
Any chance this could be added to the roadmap?
It would be really nice to be able to send specific trackers to dedicated clients/instances with specific configs for these trackers.

**Comment by jpaige5408** [comment]
apologies for the dupe. but anyway, another +1 here

**Comment by samip5** [comment]
What would this actually require?

Re-write the decision making logic?

**Comment by Thirrian** [comment]
I'd say tags is the obvious route to go.

**Comment by samip5** [comment]
> I'd say tags is the obvious route to go.

If you mean the already existing tags, I don't know if I agree with you. 
I would like some input from the actual Sonarr devs.

**Comment by markus101** [comment]
Not tags, those link to series.

I think @Taloth and I landed on an indexer would have a specific download client linked to it, similar to release profiles being linked to either a specific indexer or none (which behaves like all).

**Comment by Taloth** [comment]
yup, giving tags multiple meanings would become confusing fast.
I think I prefer this feature to stay limited to either one or all download clients per indexer, so no multi select.
Some notes for implementation:
- New nullable integer column in database, not part of the setting json
- If the download client gets removed, Indexers associated with it must be disabled and changed to All

**Comment by samip5** [comment]
> yup, giving tags multiple meanings would become confusing fast.
> I think I prefer this feature to stay limited to either one or all download clients per indexer, so no multi select.
> Some notes for implementation:
> 
> * New nullable integer column in database, not part of the setting json
> * If the download client gets removed, Indexers associated with it must be disabled and changed to All

Could you elaborate more on the "no multi select"? What do you actually mean by that?

**Comment by Taloth** [comment]
meaning you can only restrict an indexer to one download client, not two out of three.

**Comment by BelgianMonster** [comment]
+1

Could definitely use this for separating public/private indexers

**Comment by samip5** [comment]
@Taloth "New nullable(default 0) integer column in database, not part of the setting json", settings json probably refers to the IConfigService?

**Comment by markus101** [comment]
No, that’s for app wide settings. Taloth means a new column in the download client or indexer table for that value, similar to priority for those is stored.

**Comment by samip5** [comment]
Ah, now I got the point, thanks. :)

**Comment by delbonis** [comment]
This would also be a very useful feature to me!

I'd be willing go contribute to a bounty if there was anything for that. 👍

**Comment by jonnes86** [comment]
I would love this; this would be immensely useful. I'd also be willing to contribute to a bounty.

**Comment by Jake-Neighbors** [comment]
+1 for this as well, also willing to contribute to a bounty

**Comment by WhuntCore** [comment]
+1 For this pleaseeee

**Comment by bakerboy448** [comment]
A simple +1 on the OP would suffice

Comments that are not productive to the issue at hand such as +1, me too, i want this too, when will this be in, any updates, etc. are poor etitique and do not result in issues being worked on any faster.  Repeated comments of this nature will result in the thread being locked.

**Comment by Aresime** [comment]
+1

We need this!
There ( to my knowledge ) is not much configuration after you have adding multiple download clients, other than round robbin and priority system witch is more or less useless
