### ISSUE TITLE
Ability to configure timezone different from OS time

### ISSUE THREAD

**Issue by ctlaltdefeat** [Sonarr/Sonarr#1216]
Often desirable when using a server in a different timezone, but wanting showtimes in local format.

**Comment by markus101** [comment]
Show times shown in the browser are relative to the computer accessing Sonarr (all dates with time are stored in UTC), if something is off the client's timezone is wrong.

**Comment by ctlaltdefeat** [comment]
I see, that's cool...
However, what about the calendar ICS times? I believe they're off.

**Comment by markus101** [comment]
They also use UTC.

```
DTEND:20160327T210000Z
DTSTAMP:20160403T185718Z
DTSTART:20160327T200000Z
```

The `Z` at the end indicates that they are UTC.
