### ISSUE TITLE
Sonarr does not set file date == air date for a specific show

### ISSUE THREAD

**Issue by Kumolo** [Sonarr/Sonarr#1217]
Hi,

I am running Sonarr 2.0.0.3953 - Mar 12 2016 on a QNAP. Works very well.

Recently, I have downloaded (without Sonarr) a TV show season 01 and 02 of "Full House". I imported and renamed with the aid of Sonarr. However, all file dates are set to 2nd of April instead of the air date of the show. I have never seen this issue with files that have been downloaded with Sonarr itself.

Here is my settings
Change File Date --> Local Air Date

Sonarr does know the airdates:

> 21		Mad Money	                        Apr 29 1988	SDTV	
> 20		The Seven-Month Itch (2)	Mar 18 1988	SDTV	
> 19		The Seven-Month Itch (1)	Mar 11 1988	SDTV	
> 18		Just One of the Guys	        Mar 4 1988
> 

But file dates are not correct, all still set to download date and time.

Anyboday any hint what might be wrong with my setup? I tried to "Update series info and scan disk" several times, but nothing happens and log is empty:

DiskScanService	Completed scanning disk for Full House	09:50
DiskScanService	Scanning disk for Full House	09:50
RefreshEpisodeService	Finished episode refresh for series: [70500][Full House].	09:50
RefreshEpisodeService	Starting episode info refresh for: [70500][Full House]	09:50
RefreshSeriesService	Updating Info for Full House	09:50

Thanks

**Comment by markus101** [comment]
Please open a thread on the forums for support, including debug logs.
