### ISSUE TITLE
Prowl no longer working

### ISSUE THREAD

**Issue by deadlyknapsack** [Sonarr/Sonarr#1221]
I noticed that Sonarr wasn't sending me Prowl notification after the last update. I updated my API keys, but still get an error. I changed the API key to XXXXXXXXXX for privacy. I tested it with a working API key in NZBGet and still get error in Sonarr. What can I do to fix?

Component	Message	Time
NzbDroneErrorPipeline	Invalid request Validation failed: 
 -- Unable to send test message	12:28
ProwlService	Unable to send test message: API Key: XXXXXXXXXX is invalid: API Key: XXXXXXXXXX is invalid	12:28
ProwlService	Invalid API Key: XXXXXXXXXX	12:28
NzbDroneErrorPipeline	Invalid request Validation failed: 
 -- Unable to send test message	12:27
ProwlService	Unable to send test message: API Key: YYYYYYYYYYYYY is invalid: API Key: YYYYYYYYYYYYY is invalid	12:27
ProwlService	Invalid API Key: YYYYYYYYYYYYY	12:27
NzbDroneErrorPipeline	Invalid request Validation failed: 
 -- Unable to send test message	12:27
ProwlService	Unable to send test message: API Key: YYYYYYYYYYYYY is invalid: API Key: YYYYYYYYYYYYY is invalid	12:27
ProwlService	Invalid API Key: YYYYYYYYYYYYY	12:27
NzbDroneErrorPipeline	Invalid request Validation failed: 
 -- Unable to send test message	12:24

**Comment by jrsdead** [comment]
I had the same problem.  Deleted the prowl connection and set it up again and was able to test successfully

**Comment by deadlyknapsack** [comment]
Not here. I tried four-five times and eventually decided to switch to Pushover.

**Comment by markus101** [comment]
Prowl is working in my tests, perhaps a temporary issue. If anyone else has issues please open a thread on the forums.
