### ISSUE TITLE
Nothing downloaded anymore since update to 2.0.0.3953

### ISSUE THREAD

**Issue by Blizzke** [Sonarr/Sonarr#1223]
I have been running Sonarr on my Synlogy for months without issues. Since I updated to the last version it hasn't downloaded a single episode anymore. I haven't changed anything configuration wise, my crawler does contain most of the episodes sonarr should find. I haven't reached the API limit and "test" in the Indexer reports the connection as working.

It just doesn't match anything anymore.
`RSS Sync Completed. Reports found: 100, Reports grabbed: 0`

I can't see any error message in the logs whatsoever and manual search also yields no results for the episodes. I've tried the manual search on episodes downloaded by the previous version, it now also says "No episodes found". 

Anyone can tell me what is going on?

(I'm using usenet-crawler "vip" as indexer)

**Comment by markus101** [comment]
Please use the forums for support.

`RSS Sync Completed. Reports found: 100, Reports grabbed: 0` is completely normal when no wanted episodes are currently on the RSS feed.

Verify that the the items you're expecting are on the calendar and not grey as that means unmonitored (and won't be grabbed via RSS). Debug logs of an RSS Sync with an episode you expect to be grabbed will be required to troubleshoot.
