### ISSUE TITLE
Additional History Columns

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1227]
Adding a new column for the source of the grab means it will be blank for non-grab events unless we added additional information for imports and failed downloads (failed downloads could show the source as well), maybe imports could show the import action (move, copy, hardlink)?

We could colour the grab icon based on the source as well, using the same colours we use in manual search.

**Comment by cryodream** [comment]
YES, we need a quick and easy way to see the source of the grabbed episodes in the history. I would very much like to be able to easily see, how many episodes come from usenet and how many from torrents.
What would be even better, is having a column for the indexer as well, so you could quickly see the download source (usenet or torrent) and the source of nzb/torrent. This would enable to easily spot the "reliability" of nzb indexers.

**Comment by markus101** [comment]
Also consider adding a column for the release group.

**Comment by markus101** [comment]
This is addressed in the v3 UI work.
