### ISSUE TITLE
"Ignore Deleted Episodes" feature and file detection breaks when series folder is deleted

### ISSUE THREAD

**Issue by Ptgtp** [Sonarr/Sonarr#1228]
The "Ignore Deleted Episodes" feature seems to work great when I delete individual episode files or season folders. However, when I delete the entire series folder, not only do files not get unmonitored, Sonarr seems to keep thinking that the files are still there when they are clearly not (even after series refresh).

To "fix" Sonarr in these cases, I had to re-create an empty folder for the series, run the refresh and then delete that empty folder. Then the refresh realises that the files are gone and un-monitors everything as expected.

Personally, when I finish a season, I delete the whole series folder because I don't want to have hundreds of empty series folders in my media. But whether this is good practice or not, the fact that Sonarr keeps thinking the files are there when they aren't definitely seems broken to me.

**Comment by Taloth** [comment]
It's by design to handle unmounted drives and shares.

**Comment by Ptgtp** [comment]
Is there an easy way to recover from this, when series folders were deleted?

Right now, my Sonarr is in a pretty broken state as a result. I have probably over 50 shows that I deleted, but Sonarr still thinks it has it's files and will continue to think it has those files forever.

Of course I can manually re-create the series folders, making sure their names are exactly as Sonarr expects, but I was wondering if there was a less manual/quicker way?

**Comment by Taloth** [comment]
Enable create empty series folders in the settings, then run Update Library twice. (first time creates the folders, second time to clear episodes from the db)
