### ISSUE TITLE
Hardlinks not working as intended (i think)

### ISSUE THREAD

**Issue by Begnaboo** [Sonarr/Sonarr#1230]
hello!
Found sonarr yesterday and spent the day setting it up, but i ran into a problem.

All the files i download gets moved and corrupts my seeding, i tried to disable hardlinks but it wont save, it autimaticly resets to hardlinks -> yes

any ideas how i can fix?

cuz atm when my torrentfile is complete it moves it instantly to the "correct location" but no file is left behind to seed with.

**Comment by markus101** [comment]
Please open a thread on the [forums](https://forums.sonarr.tv/) with the requested information in the template, we'll need debug logs of the import process as well as which download client you're using.
