### ISSUE TITLE
Allow option to keep exact time in history

### ISSUE THREAD

**Issue by hawler** [Sonarr/Sonarr#1231]
When viewing the history for an episode, any history that was not today loses the time information and only gets a date value (or 'yesterday' of relative day naming is enabled). It would be nice to have the option to keep the exact time in the history. This would help when looking back to try and decide on a good amount of time to wait for better qualities before grabbing something, I can look back at last week and see a bunch of 720p downloads and the right after i can see the 1080p version, but I don't know if it is 5 mins or 5 hours later

**Comment by Taloth** [comment]
Settings->UI->Show relative dates, you can also hover over the time and get the exact time.

**Comment by hawler** [comment]
The relative dates thing only changes 'Yesterday' to 'Apr 8 2016', it doesn't add the time to the display. But yes, the hover works, did not know that occurred, amazed I somehow didn't stumble on it.
