### ISSUE TITLE
Error getting torrent file through bridge.suumitsu.eu feed

### ISSUE THREAD

**Issue by FreesoulHV** [Sonarr/Sonarr#1232]
Hi,

I have been trying for a few days to make sonarr work with a "cpasbien"  rss feed through bridge.suumitsu.eu. "Cpasbien" is the best french tvshow tracker.

Indexer url : https://bridge.suumitsu.eu/?action=display&bridge=CpasbienBridge&q=vostfr&format=MrssFormat

The Rss feed works like a charm (even if not searchable) but torrent links are not working very well. 
It would be awesome if it works because it would enable all frenchs user to grab laster tvshows episode s with sonarr. 
what happens is  the cpasbien torrent link request goes through a cloudflare DDOS protection and create a delay before the file is served. When multiples links are queried from the rss feed, some are working because the consequent requests are proceed faster (no delay) but the first requests failed with this error in the logs :

MonoTorrent.TorrentException: Invalid torrent file specified ---> MonoTorrent.BEncoding.BEncodingException: Could not find what value to decode

is it possible for the processdownloaddecisions to wait for the file to be served so it should work every time ?

I have not found any other solutions so far as the only alternative (Kickass torrent) does not really track the french release (vostfr) reliably.

**Comment by FreesoulHV** [comment]
Ha well, it never worked at all.
Browsing the logs I see that the links that worked were picked from kickasstorrent just after I added the cpasbien feed. 
The cloudflare protection must prevent either deluge or sonarr to grab the files.

**Comment by markus101** [comment]
I'm not seeing CloudFlare's page coming up at all in my tests, I'm getting the torrent directly, perhaps they have made changes already.
