### ISSUE TITLE
[Proposal] Also search episodes based on TheTvDB alias names of the show

### ISSUE THREAD

**Issue by ceptonit** [Sonarr/Sonarr#1234]
If the automatic (or manual) search of an episode doesn't return any result, redo the search using the aliases of the show.

For example, right now, I've added "Mobile Suit Gundam **UC** RE:0096" anime serie but the search for episodes never returns anything because the release groups use "Mobile Suit Gundam **Unicorn** RE:0096" as the show name instead (which is what Trakt and TV Rage uses as well).
But TheTvDB does have "Mobile Suit Gundam **Unicorn** RE:0096" listed as one of the aliases of the show name.
So if Sonarr could use the alias, the search would return results no problem.

**Comment by markus101** [comment]
Right now the aliases that TVDB has aren't known by Skyhook (our TVDB proxy) or Sonarr, but this should fit into existing plans we have to improve Skyhook and have alternate names returned from various sources when fetching series information. Closing as its being tracked elsewhere.
