### ISSUE TITLE
Monitored shows not downloading new episodes

### ISSUE THREAD

**Issue by rolandoldengarm** [Sonarr/Sonarr#1235]
I've added a couple of shows, set them to monitored, but episodes are never downloaded automatically. They are just shown as "Missing from disk". I don't see any failed downloads; I'm using NZB. When I click automatic search, it works fine.
Can't seem to find errors in the logs.

Maybe related: What I did notice, is that in the Calendar view, the Monitored Only view does not show any episodes. If I switch to All, I see the upcoming episodes.
But, in the Series overview, I select "Monitored Only", and they all show up.

/Edit: One show I now see is working, but the other shows are not.

What can I check more?
Besides this, I love Sonarr (coming from Sickrage). Hopefully you can help!

**Comment by JigSawFr** [comment]
Same problem from a couple of weeks, automated download is not working.

**Comment by bnollar** [comment]
Also noticed that shows are not updating.  Manual search also does not show any results.

**Comment by markus101** [comment]
Please use the forums for support.

> I've added a couple of shows, set them to monitored, but episodes are never downloaded automatically.

Only new releases on RSS feeds will be grabbed, this is explained in the FAQ.

> Maybe related: What I did notice, is that in the Calendar view, the Monitored Only view does not show any episodes.

100% related, the episode and the series need to be monitored for it to be grabbed. Since one or the other isn't RSS will never grab it.

**Comment by rolandoldengarm** [comment]
> 100% related, the episode and the series need to be monitored for it to be grabbed. Since one or the other isn't RSS will never grab it.

Sorry, but the show IS monitored, but the calendar does not show it. This is a bug, which I will raise separately.
