### ISSUE TITLE
Ability to search for entire seasons

### ISSUE THREAD

**Issue by jabalsad** [Sonarr/Sonarr#1236]
Currently, Sonarr does not deal well with trackers that index entire seasons of TV series. 

The tracker I use does not index episodes individually if the season has finished, and instead opts for indexing a complete season torrent, e.g. `Futurama.S06.1080p.BluRay.x264-CtrlHD`.

If, for example, I'd like to download a season of a series that aired long ago, I have to download the torrent manually by going to my indexer and sending it to the torrent client. Of course, from hereon the process is automated as Sonarr detects the season if it was labeled correctly.

What would be nice is if I could simply search for a full-season torrent from within Sonarr and have it send the torrent to my download client directly.

**Comment by markus101** [comment]
You can, just search for the full season not a single episode.

Possible problems:

- All episodes aren't monitored
- Release isn't an upgrade for all episodes
- Your indexer doesn't return the results for Sonarr to process

Debug logs will show you what was returned in the search and how they were processed.
