### ISSUE TITLE
Calendar does not show monitored shows

### ISSUE THREAD

**Issue by rolandoldengarm** [Sonarr/Sonarr#1237]
None of my shows show up in the Calendar as monitored.

E.g. this show is set to monitored: 
![image](https://cloud.githubusercontent.com/assets/14539000/14438001/0ddaf5a8-0078-11e6-99ae-8113f7195c1f.png)

But the Calendar is empty. Only when I set it to "All" instead of "Monitored Only" the show will shop up:

![image](https://cloud.githubusercontent.com/assets/14539000/14437993/03dee582-0078-11e6-8e98-312723fb30ed.png)

This may be causing the issue that none of my shows is grabbing new episodes automatically: https://github.com/Sonarr/Sonarr/issues/1235

**Comment by markus101** [comment]
The series is monitored, but the episode likely isn't. Check on series details (to check all episodes), or click on the item in the calendar and monitor it (the bookmark icon on the top left needs to be filled in, not just an outline).

**Comment by rolandoldengarm** [comment]
Thanks for the quick reply @markus101 .
That seems to work!
I understand how it works: I've just added the show, so all episodes are set to not monitored. But, I would expect that upcoming shows (i.e. not aired yet) to be monitored.
Or at least it would be a good idea to document/highlight this somewhere after adding a show. Or provide an option "Monitor upcoming episodes".

**Comment by markus101** [comment]
There is a monitoring option when adding the series, Future will monitor all future episodes.
