### ISSUE TITLE
Backup Fail

### ISSUE THREAD

**Issue by Artkil** [Sonarr/Sonarr#1238]
Hi All,

I recently moved from Windows 7 to Windows 10..  And migrated my Sonarr with the backup feature..  Everything has been working great. Today I thought I would backup my Sonarr and got this error.

Error occurred while executing task Backup: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=0.86.5.0, Culture=neutral, PublicKeyToken=9dea7c6e17aa31ff' or one of its dependencies. The module was expected to contain an assembly manifest.

Any advice would be great here..

**Comment by markus101** [comment]
Please use the forums for support.

https://forums.sonarr.tv/t/unable-to-update-or-backup/10147
