### ISSUE TITLE
Unable to parse episodes from release name

### ISSUE THREAD

**Issue by rcmpayne** [Sonarr/Sonarr#1240]
Release rejected 

> Unable to parse episodes from release name

Here is the name of the parse
> Yukon.Gold.S04E08.400p.249mb.MQwebrip.x264-][ Double Down ][ 07-Apr-2016 ]

`16-4-12 14:27:27.2|Debug|Parser|Parsing string 'Yukon.Gold.S04E08.400p.249mb.MQwebrip.x264-][ Double Down ][ 07-Apr-2016 ]'
16-4-12 14:27:27.2|Trace|Parser|^(?<title>.+?)(?:(?:_|-|\s|\.)+(?<absoluteepisode>\d{3}(?!\d+)))+(?:.+?)\[(?<subgroup>.+?)\].*?(?<hash>\[\w{8}\])?(?:$|\.)
16-4-12 14:27:27.2|Debug|Parser|Episode Parsed. Yukon Gold S04E08 - 400 
16-4-12 14:27:27.2|Debug|Parser|Language parsed: English
16-4-12 14:27:27.2|Debug|NzbDrone.Core.Parser.QualityParser|Trying to parse quality for Yukon.Gold.S04E08.400p.249mb.MQwebrip.x264-][ Double Down ][ 07-Apr-2016 ]
16-4-12 14:27:27.2|Debug|Parser|Quality parsed: SDTV v1
16-4-12 14:27:27.2|Debug|Parser|Release Group parsed:  Double Down 
16-4-12 14:27:27.2|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unable to parse episodes from release name
16-4-12 14:27:43.3|Trace|Scheduler|Pending Tasks: 0`

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/215581/sonarr.trace.txt)

Branch: Develop
Version
2.0.0.4087
Mono Version
3.8.0 (tarball Sun Sep 28 11:03:43 EDT 2014)
AppData directory
/.config/NzbDrone
Startup directory
/usr/local/Sonarr

**Comment by markus101** [comment]
What an awful way to name releases... its getting caught on the `400p` in this case, but could also get caught on `249mb` as they are not standard in any naming except for the releases by this group. This is something we'll need to look at further when we look at the advanced parser https://github.com/Sonarr/Sonarr/issues/457
