### ISSUE TITLE
Sonarr not working after DSM 6 update

### ISSUE THREAD

**Issue by tebbittd** [Sonarr/Sonarr#1246]
Can anyone help - since the update to DSM 6 I cannot get sonarr / SABnzbd to work, it simply will not run at all.

I understand that this has something to do with the Mono package from Syno Community - will this be updated does anyone know?

Is there an alternative route I can take?

(p.s. -  I am a complete novice to this)

**Comment by markus101** [comment]
Please use the forums for support.

https://forums.sonarr.tv/search?q=DSM%206.0
