### ISSUE TITLE
Linux SSL instructions are a bit confusing

### ISSUE THREAD

**Issue by Ackis** [Sonarr/Sonarr#1248]
I found the current instructions a bit confusing

Current Instructions (I think - from what I was able to get out of the documentation):
1. Generate the key: `openssl genrsa -out sonarr.local.key 2048`
2. Generate the cert: `openssl req -new -x509 -key sonarr.local.key -out sonarr.local.cert -days 3650 -subj /CN=sonarr.local`
3. Convert the key/cert to pkcs12: `openssl pkcs12 -export -in sonarr.local.cert -inkey sonarr.local.key -out sonarr.local.pfx`
4. `openssl pkcs12 -in sonarr.local.pfx -nocerts -nodes -out sonarr.local.pem`
5. Edit the pem file removing the top few lines
6. `openssl rsa -in sonarr.local.pem -outform PVK -out sonarr.local.pvk`
7. Add to sonarr with httpcfg `httpcfg -add -port XXXX -pvk sonarr.local.pvk -cert sonarr.local.cert`

Suggested Instructions:
1. `openssl genrsa -out sonarr.local.pem 2048`
2. `openssl req -new -x509 -key sonarr.local.pem -out sonarr.local.cert -days 3650 -subj /CN=sonarr.local`
3. On a Windows machine.  Doing this with openssl requires a passphrase which breaks mono apparently. `pvk.exe -in sonarr.local.pem -topvk -nocrypt -out sonarr.local.pvk`
4. `httpcfg -add -port 8990 -pvk /opt/sslkey/sonarr.local.pvk -cert /opt/sslkey/sonarr.local.cert`

At this point I'm at least getting it to refuse my connection opposed to not allowing me to connect.

**Comment by markus101** [comment]
Only on Windows do you need to convert to pkcs12 (So it can be imported into the Windows certificate store).

I updated the page, hopefully its more clear.
