### ISSUE TITLE
[proposal] new series airing this month/week

### ISSUE THREAD

**Issue by FreesoulHV** [Sonarr/Sonarr#1249]
Hi,

Sonarr is so awesome that since I am not monitoring torrents for series anymore I miss the new shows airing !
A link or suggestion in the series page to list all the new airing series that could be add to my series would be great :)

**Comment by thezoggy** [comment]
this could be tossed into a 'trending' / 'recommendation' thing.. im sure theres already a github issue for that

**Comment by markus101** [comment]
Yeah, a dupe of https://github.com/Sonarr/Sonarr/issues/354
