### ISSUE TITLE
Sonarr crashes with 'invalid machine command'

### ISSUE THREAD

**Issue by marlemion** [Sonarr/Sonarr#1250]
I have sonarr running on a ARMv5 Kirkwood machine happily since a few months. Since a few days it crashes with 'invalid machine command'. Mono is at 4.4.0 and does not crash alone, e.g. without executing sonarr through it.

System ist a recent arch linux.

**Comment by marlemion** [comment]
Ok, I have downgraded to mono 4.2.2 and it works again.

**Comment by Taloth** [comment]
Yeah, Clearly there's something wrong with mono on that particular architecture. If I weren't feeling lazy today I would check their bugtracker, see if someone else brought it up already.
