### ISSUE TITLE
Sonarr snatching full BluRay discs instead of BluRay rip season packs

### ISSUE THREAD

**Issue by jant90** [Sonarr/Sonarr#1251]
For example when doing a full season 2 search for Homeland (with 720p quality profile) Sonarr snatches (using indexer NZBGeek): `Homeland.S02.Disc2MULTiCOMPLETE.BLURAY-FULLSiZE`. I've also seen it with more shows, like Breaking Bad: `Breaking.Bad.S02.DiSC3.MULTi.COMPLETE.BLURAY-UNTOUCHED`.

So a single BluRay disc is snatched instead of a season pack for those shows. **Can Sonarr be updated to recognize these unripped/fullsize/untouched BluRay discs and exclude them?**

Currently I solve it by deleting that release and blacklisting it. I have to repeat that a couple of times because a season usually consists of multiple BluRay discs.

On this note it would also be useful if we could do manual searches for season packs, as far as I know this is currently only possible for single episodes and for seasons Sonarr always performs an automatic search. It would be nice to have some insight into season pack search results.

**Comment by Taloth** [comment]
Use Indexers->restrictions must not contain to reject certain words

**Comment by jant90** [comment]
Great, thanks, hadn't thought of that yet. I added 'disc' to my ignore word list so I guess that should do it. :)

Still I think Sonarr should recognize that those releases don't match the Bluray-720p quality profile (for one because there isn't 720p in the title, so a match with Bluray-1080p would be more understandable I guess).

**Comment by Taloth** [comment]
There are also releases without resolution, so that's not possible.
