### ISSUE TITLE
Manually deleted series/episodes are remembered.

### ISSUE THREAD

**Issue by deadlyknapsack** [Sonarr/Sonarr#1257]
I wast testing a new download client with Sonarr and I manually deleted an episode to redownload after for testing purposes. When I deleted the episode manually from my diskstation, and restarted Sonarr, hit all the refresh tasks, it still said the episode was there. I am 100% confident it wasn't. Then, I deleted an entire series from my diskstation (at the series top directory), I went back to Sonarr and of course the series was still mentioned there, this is normal behaviour. However, Sonarr claimed all the episodes were supposedly still there, at the original location on my diskstation. Seems like a bug to me.

Details of setup:

- Synology DS716+ with DSM 5.2-5644 Update 7
- Sonarr version 2.0.0.3953

Please let me know what to do. I can provide logs if needed, no problem.

**Comment by Taloth** [comment]
The series folder must exist for Sonarr to remove the episodes from the db. That's by design to handle unmounted root folders.

**Comment by deadlyknapsack** [comment]
Pfff. First you fail to read my comment properly. Second you immediately close it. What's up with that?!

Again:

"I manually deleted an episode to redownload after for testing purposes. When I deleted the episode manually from my diskstation, and restarted Sonarr, hit all the refresh tasks, it still said the episode was there."

You completely ignore this part, where is this even remotely related to deleting a root series directory? This step (misunderstood, see below) is after this.

Second of all, I never stated that I deleted the root series folder. Maybe I didn't explain it very well, my bad, but I deleted a single series (sub)folder, like "The Simpsons" or "The Sopranos". 

Even after deleting the entire directory of the "The Simpsons" the episodes were still visible in Sonarr as if they were located within a folder called "The Simpsons" when I know for a fact, it wasn't.

Please re-open.

**Comment by Taloth** [comment]
I actually never mentioned deleted root folders (D:/tv), I mentioned deleted series folders (D:/tv/Arrow/). And it was an answer to the second part of your post. (considering that was your current state, it seemed the most relevant)

My post may have been a bit short, sry for that, but I'm on a phone and we usually direct support questions to our forum.

Either way, if you can reproduce the original problem with the single episode. Post some debug logs on the forum.
