### ISSUE TITLE
"Another Instance is already Running" - after multiple system restarts and Sonarr reboots

### ISSUE THREAD

**Issue by stevedawg85** [Sonarr/Sonarr#1258]
Running on Openmediavault
In the past, a system restart of my OMV machine would fix it, but now it is stuck.  I cannot get to the webgui, as it is just frozen.  How can I force kill it?  I'm currently disabling it in the OMV gui, and turning it back on.  

Piece from my log:
`
16-4-22 09:55:15.3|Info|Bootstrap|Starting Sonarr - /opt/Sonarr/NzbDrone.exe - Version 2.0.0.3953
16-4-22 09:55:15.7|Debug|ProcessProvider|Found 0 processes with the name: NzbDrone.Console
16-4-22 09:55:15.8|Debug|ProcessProvider|Found 2 processes with the name: NzbDrone
16-4-22 09:55:15.8|Debug|ProcessProvider| - [31814] NzbDrone
16-4-22 09:55:15.8|Debug|ProcessProvider| - [2365] mono-sgen
16-4-22 09:55:15.8|Info|SingleInstancePolicy|1 instance(s) of Sonarr are running
16-4-22 09:55:15.8|Warn|SingleInstancePolicy|Another instance of Sonarr is already running.
16-4-22 09:55:15.8|Debug|BrowserService|non-interactive runtime. Won't attempt to open browser.
16-4-22 09:55:15.8|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running
`

**Comment by markus101** [comment]
Please open a thread on the forums for support.
