### ISSUE TITLE
Can't get my server Sonarr to connect with my local Plex

### ISSUE THREAD

**Issue by corpseas** [Sonarr/Sonarr#1260]
Hello, I have a seedbox slot (WhatBox) which has Sonarr on it so it runs on the server, not locally on my computer. However, I can't get it to connect with my Plex Media Server like my Sonarr did when it was local on my computer. I literally copy and pasted it from my local Sonarr. I assume that because Sonarr is not running locally anymore, the private IP my local Plex has will not work with it. Is there a way to get it to detect my local PMS? Thank you in advance.

**Comment by markus101** [comment]
If Sonarr is running outside of your network you'd need to tell Sonarr to talk to the public IP that PMS is available at, a local IP can only be used on the local network.

Please open a thread on the support forums if you have any more questions.

**Comment by corpseas** [comment]
I probably should've mentioned that I tried my public IP as well, but that didn't work either.

Also if you mean the support forums on sonarr.tv, I actually made one a little while ago. I just couldn't figure out how to delete the one off here

https://forums.sonarr.tv/t/cant-get-my-server-sonarr-to-connect-with-my-local-plex/10533
