### ISSUE TITLE
Delay Profile - Torrent - does not work

### ISSUE THREAD

**Issue by rolandoldengarm** [Sonarr/Sonarr#1261]
I have set up a Default Delay Profile with "Prefer usenet" and 2880 minutes for Torrents. Nevertheless a show aired today is now being downloaded as torrent.

**Comment by markus101** [comment]
We'd need to see debug logs showing how it was grabbed.

**Comment by rolandoldengarm** [comment]
Sorry my bad. I have clicked "automatic search" manually for this episode...
