### ISSUE TITLE
Game Of Thrones Air Date/Time Incorrect

### ISSUE THREAD

**Issue by User40405** [Sonarr/Sonarr#1262]
Game of thrones S06E01 incorrect air Date/Time? Here is an image: http://s31.postimg.org/cp8supgxn/Capture.png

Should Have aired 3 AM April 24 for us? Says it has aired 21 April though? Tested on another PC as well and checked all PC time settings.

**Comment by markus101** [comment]
Someone changed the date on TheTVDB, its fixed now (and locked to prevent it from happening again). Please use the forums for questions/support next time.

**Comment by User40405** [comment]
Hi

Thanks so much for fixing it, so sorry for using wrong forum. Will use forum in future.

Regards
Karl
