### ISSUE TITLE
Custom post-processing script environment variables don't include the episode title

### ISSUE THREAD

**Issue by jzplusplus** [Sonarr/Sonarr#1263]
Not sure if there is a reason this was left out, since things like episode number and air date are included.

**Comment by markus101** [comment]
One reason is because it would need to be a comma separated array, if the episode title contained a comma it would need to be escaped and the consuming script would need to understand how to unescape it. Some basic information is given, but you can always use the API to get more information.

**Comment by jzplusplus** [comment]
I didn't think about using the API, that sounds like a simple workaround. I am currently using the Webhook as an alternative that provides all the info, the downside being that I have to keep a local web server running to receive the notification.

Thanks for the quick response!
