### ISSUE TITLE
Windows download exe infected?

### ISSUE THREAD

**Issue by xyxoxy** [Sonarr/Sonarr#1264]
Just tried to download the Windows NZBDrone.Master.exe installer and Norton flagged it as untrustworthy, with a threat name of WS.Reputation.1

Threat level is medium.

Is this installer safe to use?

**Comment by Taloth** [comment]
You might want to Google 'norton ws.reputation.1' to find out what it's really about.
Hint: It's not about virus detection.

**Comment by xyxoxy** [comment]
Thanks... I see that now. This is the first time that's come up for me so just being cautious.
