### ISSUE TITLE
HDBits RSS and API search results without timezone conversion

### ISSUE THREAD

**Issue by needo37** [Sonarr/Sonarr#1272]
HDBits RSS and API search results return with GMT. Conversion to the local timezone does not occur. This affects if you have a torrent delay as when a torrent is posted it shows as 6 hours old instead of 1 minute old which throws off the delay.

**Comment by markus101** [comment]
Please post a sample response from the RSS feed so we can see what we're dealing with.

**Comment by needo37** [comment]
<item>
<guid isPermaLink="false">314122</guid>
<title>Childrens Hospital S07 720p WEB-DL DD5.1 H.264-BTN</title>
<pubDate>Sun, 01 May 2016 23:31:20 +0000</pubDate>
<link>
https://hdbits.org/download.php?id=314122&passkey=xxxxxxxxxxxxxxxxxxxx&source=rss
</link>
<description/>
</item>
