### ISSUE TITLE
Vuze support based on Transmission protocol

### ISSUE THREAD

**Issue by hmemcpy** [Sonarr/Sonarr#1273]
I've been looking into adding Vuze support, based on this [forum request](https://forums.sonarr.tv/t/vuze-torrent-client-support/8700). It seems that Vuze "Support most of Transmission's remote API", according to the developers of the Vuze Web Remote (which are the same people as Transmission, looks like).

According to the post:
> * Vuze uses the same URL base "\transmission\' (confirmed with the in the Plugin logs in Vuze)
> * The version check fails, saying "Transmission version not supported, should be 2.40 or higher."

I've done some digging: sending a `session-get` to Vuze will return the following values:
```
rpc-version=14
...
version=0.5.11
```
0.5.11 being the version number of the Vuze Web Remote plugin. `14` is the RPC version number, corresponding to Transmission v2.40 (https://trac.transmissionbt.com/browser/trunk/extras/rpc-spec.txt#L747)

Now, it seems that [Transmission.cs](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/Clients/Transmission/Transmission.cs#L214) is checking the value of the `version` property to be at least 2.40, which explains why this fails with Vuze. After changing this to use the `rpc-version` instead, I was able to make it work with Vuze!

However, there is (at least) one more issue remains: Vuze reports downloaded directory incorrectly, whereas in Transmission it expects the path excluding the torrent name, Vuze reports it including the torrent name, so it fails to process the complete download. Also an easy fix.

Question: Given those relatively small changes, would Vuze support be a welcomed PR? It seems there is some reluctance to add it because the client is fairly old and could be abused, but... there are no technical reasons not to.

**Comment by markus101** [comment]
Implemented!
