### ISSUE TITLE
Episode Naming {Quality.Title}, {Quality_Title}, and {Quality Title} are all the same.

### ISSUE THREAD

**Issue by PanicPaintbrush** [Sonarr/Sonarr#1276]
{Quality.Title}, {Quality_Title}, and {Quality Title} all result in the same string (for the qualities I've tested).
eg. They all result in HDTV-720p or WEBDL-1080p

I thought they'd result in HDTV.720p, HDTV_720p, and HDTV 720p.

Personally I'd just prefer that the source and resolution were separate tags. (Although I guess source resolution and final resolution could be different)

**Comment by markus101** [comment]
Spaces are replaced with the character chosen, you'll need to alter the quality naming (on the quality settings page) and remove the dash.
