### ISSUE TITLE
Not able to add rtorrent

### ISSUE THREAD

**Issue by Naniq** [Sonarr/Sonarr#1278]
Hey!

I'm trying to set up a new server with sonarr.

I have used Sonarr on another host before and had no problem setting it up, it worked basicly on the first try, but this time I'm having issues and I can't seem to find the error.

If I try to add the information into client i get the following error:

Unknown exception: Error getting response stream (ReadDone2): ReceiveFailure

Personally i'm not sure if I use the right port number for rutorrent, can someone maybe guide me through it?

**Comment by markus101** [comment]
Please open a thread on the forums for support.
