### ISSUE TITLE
Notification of season end

### ISSUE THREAD

**Issue by eseelke** [Sonarr/Sonarr#1282]
It would be really cool is Sonarr would give a notification either via webui or email after it downloads the last episode of the season. This way, for those of us that wait until season ends to watch, we would know when we can start watching that season.

**Comment by kayone** [comment]
We discussed this a bit in https://github.com/Sonarr/Sonarr/issues/1206 the main issue is being able to detect the end of season reliably.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted

meta providers don't have this info reliably
