### ISSUE TITLE
Mark imported downloads in download client

### ISSUE THREAD

**Issue by kayone** [Sonarr/Sonarr#1283]
It would be nice to tag/add category to imported downloads in download clients (specially torrents)

That way the use could tell which downloads are imported and can be deleted from disk and maybe review why some have not been imported yet.

**Comment by therealzanfar** [comment]
Agreed, especially for download clients with no delete support.

Not sure if this belongs in the same ticket or a new one, but for torrents using a remote downloader (where Completed Download Handling doesn't work, there is a period of time from when the download finishes to when it is imported where Sonarr displays no status at all for the download--it appears exactly as if it was never scraped, added, or began downloading. Suggest that torrents remain in the "downloading" status on the Activity screen during this time, or a new status is applied as long as the download exists in the client.

**Comment by markus101** [comment]
Closing in favour of https://github.com/Sonarr/Sonarr/issues/2469
