### ISSUE TITLE
Stream Details in NFO files

### ISSUE THREAD

**Issue by IchabodFletchman** [Sonarr/Sonarr#1286]
I have Sonarr set up to fetch metadata for Kodi (NFO & images), then push the updates to Kodi.
My setup works fine, except I would like stream details in the NFO's file info.

This is an example nfo file from other nfo mangers:
```
<episodedetails>
	<title>Alicia</title>
	<season>3</season>
	<episode>3</episode>
	<aired>2014-04-20</aired>
	<plot>While Selina and her staff prepare for an Annapolis event where she will announce her candidacy, Dan gets word that "Saturday Night Live" has done a not-so-flattering sketch about her.</plot>
	<displayseason />
	<displayepisode />
	<thumb>http://thetvdb.com/banners/episodes/237831/4821926.jpg</thumb>
	<watched>false</watched>
	<rating>8.3</rating>
	<fileinfo>
		<streamdetails>
			<video>
				<aspect>1.778</aspect>
				<codec>h264</codec>
				<durationinseconds>1682</durationinseconds>
				<height>720</height>
				<scantype>progressive</scantype>
				<width>1280</width>
			</video>
			<audio>
				<channels>6</channels>
				<codec>ac3</codec>
				<language>eng</language>
			</audio>
			<audio>
				<channels>2</channels>
				<codec>ac3</codec>
				<language>spa</language>
			</audio>
			<subtitle>
				<language>spa</language>
			</subtitle>
		</streamdetails>
	</fileinfo>
</episodedetails>
```

Sonar doesn't have a `<fileinfo>` tag like in the example file.
These details make a big difference when pushing updates to Kodi. When Kodi fetches metadata for episodes, it doesn't fetch stream details, only after it has started playing, as it relies on the nfo providing those details. When the details are included, Kodi displays runtime, resolution, aspect ratio, audio streams, etc).

Can this be easily done? If so, I (and I presume others) would really appreciate it.

**Comment by thezoggy** [comment]
may want to be cautious of adding this / offer way to disable it:
http://forum.kodi.tv/showthread.php?tid=224364

**Comment by IchabodFletchman** [comment]
http://forum.kodi.tv/showthread.php?tid=224364
I believe that discussion is for when an NFO doesn't have stream details and Kodi needs to extract them itself.
It won't be an issue if Sonar added the details on download. Then Kodi will read that and not have to do anything. You can test this with other software that add the details, like CouchPotato, or an NFO manager like MediaCompanion.
