### ISSUE TITLE
Delay profile does not work for torrents

### ISSUE THREAD

**Issue by rolandoldengarm** [Sonarr/Sonarr#1287]
I have set up a Default Delay Profile with "Prefer usenet" and 2880 minutes for Torrents. Nevertheless a show aired today is now being downloaded as torrent.
Previous log entries DO show that certain items are ignored.
The show is set to 1080p minimal

Lower quality found (720p); there's a line that it's ignored because of the 2880 min delay
````
16-5-9 16:08:16.1|Debug|AcceptableSizeSpecification|Beginning size check for: Game of Thrones S06E03 RERIP 720p HDTV x264-AVS[rartv]
16-5-9 16:08:16.1|Debug|AcceptableSizeSpecification|Item: Game of Thrones S06E03 RERIP 720p HDTV x264-AVS[rartv], meets size constraints.
16-5-9 16:08:16.1|Debug|LanguageSpecification|Checking if report meets language requirements. English
16-5-9 16:08:16.1|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Game of Thrones S06E03 RERIP 720p HDTV x264-AVS[rartv]
16-5-9 16:08:16.1|Debug|ReleaseRestrictionsSpecification|[Game of Thrones S06E03 RERIP 720p HDTV x264-AVS[rartv]] No restrictions apply, allowing
16-5-9 16:08:16.1|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. HDTV-720p v1
16-5-9 16:08:16.1|Debug|QualityAllowedByProfileSpecification|Quality HDTV-720p v1 rejected by Series' quality profile
16-5-9 16:08:16.1|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
16-5-9 16:08:16.1|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
16-5-9 16:08:16.1|Debug|DelaySpecification|Waiting for better quality release, There is a 2880 minute delay on Torrent
````
Where it goes wrong, when it finds my required quality (1080p). No more line in the logs about the 2880 delay. I think the error is this line:

**16-5-9 16:27:56.6|Debug|DelaySpecification|Ignore delay for searches**

Please note that I was *not* searching. 

````
16-5-9 16:27:56.6|Debug|NzbDrone.Core.Parser.QualityParser|Trying to parse quality for Game of Thrones S06E03 1080p HDTV x264-BATV[rartv]
16-5-9 16:27:56.6|Debug|Parser|Quality parsed: HDTV-1080p v1
16-5-9 16:27:56.6|Debug|Parser|Release Group parsed: BATV
16-5-9 16:27:56.6|Debug|AcceptableSizeSpecification|Beginning size check for: Game of Thrones S06E03 1080p HDTV x264-BATV[rartv]
16-5-9 16:27:56.6|Debug|AcceptableSizeSpecification|Item: Game of Thrones S06E03 1080p HDTV x264-BATV[rartv], meets size constraints.
16-5-9 16:27:56.6|Debug|LanguageSpecification|Checking if report meets language requirements. English
16-5-9 16:27:56.6|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Game of Thrones S06E03 1080p HDTV x264-BATV[rartv]
16-5-9 16:27:56.6|Debug|ReleaseRestrictionsSpecification|[Game of Thrones S06E03 1080p HDTV x264-BATV[rartv]] No restrictions apply, allowing
16-5-9 16:27:56.6|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. HDTV-1080p v1
16-5-9 16:27:56.6|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
16-5-9 16:27:56.6|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
16-5-9 16:27:56.6|Debug|DelaySpecification|Ignore delay for searches
16-5-9 16:27:56.6|Debug|HistorySpecification|Skipping history check during search
16-5-9 16:27:56.6|Debug|MonitoredEpisodeSpecification|Skipping monitored check during search
16-5-9 16:27:56.6|Debug|SeriesSpecification|Checking if series matches searched series
16-5-9 16:27:56.6|Debug|DownloadDecisionMaker|Release accepted
````

**Comment by markus101** [comment]
Please use the forums for support.

Sounds like a usenet download failed so it resorted to searching, if the torrent release was the best quality release then it would be grabbed, otherwise it would have grabbed a usenet release (assuming usenet is the preferred protocol). Try setting a minimum age for usenet to rule out propagation issues.

**Comment by rolandoldengarm** [comment]
@markus101 
I appreciate you replying so quickly, but it is not a support issue. There was no failed NZB download; the show was not available at 1080p at news servers yet.
It looks like a bug, therefore I post it here. I've spent quite some time digging through the logs to grab the relevant lines, so some investigation would be appreciated.

And, additionally, I'm expecting that it waits 1 day before it tries torrents, even when there would be a failed download. But again, in my case there was no failed download.

Please reopen this bug.

**Comment by Taloth** [comment]
roland. 99% of the time when ppl claim something is a bug, it ends up not being one. So we usually start on the forum, and when something proves to be a bug we post a ghi to track it's progress.

Nonetheless, we appreciate that you searched the log files, looking for an answer.

In your case, the second log section indicates it's a search, there's no doubt about that. Whether you triggered it or whether Sonarr did (Failed Download Handling), can't be determined coz that's logged earlier in the log file.   
Given the series title, and that Failed download handling is a likely candidate for causing a search, we suspect there was an usenet download that was attempted and failed. The Episode History will likely show that.
If that's not the case, then something else triggered the search.

**Comment by rolandoldengarm** [comment]
What I did, was clicking on Manual Search to check if an NZB was available, but did not download any episode. So, the second part of the log is from my manual search I now believe. But maybe it's that clicking Manual Search it is setting some flag? IMO that should still not happen, it should still wait the delay.

Some time later I noticed it was downloading; not directly after clicking manual search. 

There is certainly no failed NZB, just checked.

**Comment by Mobrockers** [comment]
Can confirm, delay does not seem effective and nzb is never chosen over torrents in my case. When manually searching I can find 5+ equal quality nzb's from the same release even but a torrent is started instead.

**Comment by markus101** [comment]
> But maybe it's that clicking Manual Search it is setting some flag?

There is no flag, the release would be evaluated before it was grabbed.

> Can confirm, delay does not seem effective and nzb is never chosen over torrents in my case.

Is NZB set as the preferred protocol?

> When manually searching I can find 5+ equal quality nzb's from the same release even but a torrent is started instead.

Delays don't apply to searches, if you searched and only a torrent was available in the quality grabbed it would be grabbed, if you searched later and saw the NZBs it'd have been too late. One thing to note is that torrents are generally updated on the site in close to real time, since NZBs are pulled into indexers when they scrape the different groups there is usually a delay in picking them up of at least a few minutes (and typically uploads to usenet are after trackers have the content).

Without seeing debug logs from the time of the grab there isn't anything we can investigate or discuss. I have opened https://github.com/Sonarr/Sonarr/issues/1292 in relation to respecting delays when triggering a search after a failed download. If someone can provide logs showing a delay being ignored, we can take a look.

**Comment by Mobrockers** [comment]
I use sonarr on a system that is not online during the day when I'm at
work, coupled with being in Europe this means episodes are always available
on usenet by the time I get home from work. When I come home and boot up my
pc sonarr immediately loads up torrents for the episodes available instead
of nzb's. I have usenet set as preferred protocol and also set a delay on
torrents. When I manually search after seeing the torrent started, I can
generally find the exact same release a couple times in the list as nzb's.
I would expect sonarr to pick those up, but instead it picks up a torrent.

**Comment by markus101** [comment]
Enable debug logging and get them for us, also make sure Usenet is the preferred protocol (it should be by default, but check). Your issue doesn't seem to be related to delays though and really does belong on the forums until we can verify that there is an underlying issue...

**Comment by Mobrockers** [comment]
I've finally found the correct logs and the correct log entries. I'm not completely sure but I think it might have to do with me misspelling hevc in my ignored list, and hevc being seen as a higher quality release than a x264 release? If so then that's my bad, did not notice this before. Sorry!

**Comment by markus101** [comment]
> hevc being seen as a higher quality release than a x264 release

HDTV 720p x265 (hvec) and HDTV 720p x264 are the same quality, there isn't a preference given to either.

**Comment by Mobrockers** [comment]
Right, I looked a bit further and apparently my nzb indexer appears to go down for maintenance often, making sonarr skip the indexer for some time. My other indexer doesn't support backlog searches so can't be used, thus a torrent is fetched. Sorry @markus101, my fault after all.

**Comment by rolandoldengarm** [comment]
> Without seeing debug logs from the time of the grab there isn't anything we can investigate or discuss. I have opened #1292 in relation to respecting delays when triggering a search after a failed download. If someone can provide logs showing a delay being ignored, we can take a look.

I couldn't find the log entry where the torrent was grabbed... What is the action name I should be looking for? I've searched a couple of times.

**Comment by Taloth** [comment]
"Report sent to" it's logged at Info level. There are other related log entries, but most of em are logged at Debug or Trace.
Also relevant is the Info log entry "Reports grabbed" it's logged after each Rss Sync.

**Comment by markus101** [comment]
Closing this, if you find more information please let us know.

**Comment by rolandoldengarm** [comment]
I've monitored it for a couple of weeks, and as long as I don't do manual searches, it all works well. Thanks.
