### ISSUE TITLE
Episode Upgrade Notification

### ISSUE THREAD

**Issue by IchabodFletchman** [Sonarr/Sonarr#1288]
I would like the message for episode upgrades to display "Episode Upgraded". (I am using Prowl, haven't tested with other services).
Right now when an episode is replaced with a better version it still says "Episode Downloaded", so you don't know whether or not it's a new episode.
There is the option to notify on episode upgrades, but that doesn't change the message.

**Comment by markus101** [comment]
This would be handled as part of https://github.com/Sonarr/Sonarr/issues/328
