### ISSUE TITLE
Highest Peer option in Profile

### ISSUE THREAD

**Issue by vinchi007** [Sonarr/Sonarr#1289]
Hi,
Can you please please create an option (checkbox) in Profiles for "Highest Peers". The logic is to download the episode/season with the highest peer number first (to have media available as soon as possible) than let the backlog logic to download the highest quality that the profile has setup.
It will download content for the user to consume as quickly as possible and later backfill the profile quality set in the profile.

Thanks for making a great app!!!

**Comment by markus101** [comment]
We have no plans to change quality being the deciding factor, though there may be an option in the future to set the minimum number of seeders.

**Comment by vinchi007** [comment]
I was referring to having a second option in the profiles - instead of basing it on the quality of the media, second option is to base the download on the highest number of peers

**Comment by markus101** [comment]
I understand what you meant, but its not something we're considering.
