### ISSUE TITLE
Disable Episode Title in Notifications

### ISSUE THREAD

**Issue by IchabodFletchman** [Sonarr/Sonarr#1291]
I am using Prowl for notifications and would like the ability to disable the episode title in the notification.
Existing: "Series Title - 2x12 - Episode Title [WEBDL-720p]"
Proposed: "Series Title - 2x12 - [WEBDL-720p]"

I have prowl setup on my Apple Watch and the notifications are a bit too long and clutter up the notification. For me the episode title isn't something I need to know.

**Comment by markus101** [comment]
This would be handled as part of https://github.com/Sonarr/Sonarr/issues/328
