### ISSUE TITLE
Provide a way for episode images to be returned from the API if requested

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1293]
This will allow someone to opt-in to get episode images from the API which we don't normally return and should be able to be used in multiple places, such as `/api/episodes` or `/api/calendar` (to name a couple).

A query string parameter such as `includeImages=true` is the first idea that comes to mind.

Related to https://github.com/Sonarr/Sonarr/issues/464 in that we'll want a similar approach for both I think.

**Comment by thezoggy** [comment]
or do what i did for sb api, just open up a specific api call to get the banner/poster/whatever specifically for a show (tvdbid).. that way apps can request an image on demand when they load up the show/popup/etc..

**Comment by markus101** [comment]
This is done in the v3 work.

**Comment by morpheus65535** [comment]
@markus101 Thank you very much!
