### ISSUE TITLE
Posters not corresponding

### ISSUE THREAD

**Issue by BenoitMartin2** [Sonarr/Sonarr#1296]
Hi,

I migrated from SR to S today, Sonarr said to be lighter. And it seems to be BTW :)
"But", there's a serious mess up with the posters (~44/49) as they are not corresponding to the shows... There is absolutely nothing but the videos (even no NFO) in the folders so I don't understand why it failed. Any idea?
FYI I use Kodi.

Ex1 TBBT with Black Sails poster: http://imgur.com/ZsHRq8Pl.png
Ex2 Blindspot with CMs: http://imgur.com/ariXmpEl.png
Etc.

Here are their folders:
Blindspot: http://imgur.com/WgQXpAJl.png
Criminal Minds: http://imgur.com/yaBNbNIl.png
TBBT: http://imgur.com/9W28Gaxl.png
Black Sails: http://imgur.com/sMxOGcEl.png

Thanks for the support

**Comment by markus101** [comment]
Please use the forums for support.

Try another browser or disable all extensions and try again. Some extensions, specifically I know of one in Firefox that speeds up browsing, but it does heavy caching and ends up caching the series images. If that doesn't work, delete the MediaCover folder from Sonarr's AppData directory (the path is shown on System: Status) then refresh the series.

**Comment by BenoitMartin2** [comment]
Thank you
