### ISSUE TITLE
Can't add series path or any path (Arch).

### ISSUE THREAD

**Issue by DimT** [Sonarr/Sonarr#1298]
Hello,

After installing sonarr, I tried to add series but any path I have used is not acceptable and I don't know why. Also, when I tried to import from disk, sonarr wouldn't find my drives in /run/media/username/ .

There was a problem with gnome-disks not having permissions on external drives and I added a polkit following a guide. (I don't know if this is related at all)

P.S.: I'm totally new to Arch.

**Comment by markus101** [comment]
Please open a thread on the forums with the requested information.
