### ISSUE TITLE
Download the same release from 2 different indexers

### ISSUE THREAD

**Issue by smela** [Sonarr/Sonarr#1299]
Hey,

I'm just wondering if there is a way for tell Sonarr to download the same release of the same series, but from 2 different indexers? I'm using Sonarr with my seedbox mainly to achieve a good ratio on my 2 main trackers.

**Comment by markus101** [comment]
No, thats not possible, if they are the same quality Sonarr will only grab one, you'd need to run multiple instances of Sonarr (under different users and using different categories) to achieve that.
