### ISSUE TITLE
Custom script (slack.sh) not running when pressing test?

### ISSUE THREAD

**Issue by ratan12** [Sonarr/Sonarr#1300]
I added slack integration which works when I launch the file but when I press test in the Sonarr interface nothing happens.
I replaced the slack hook url with xxx but am using a valid one.

Name: Slack
Path: C:\ProgramData\NzbDrone\slack.sh
Arguments: https://hooks.slack.com/services/xxx/xxx

```
#!/bin/bash
curl -X POST --data-urlencode "payload={\"username\": \"Sonarr\", \"icon_emoji\": \":ghost:\", \"text\": \"$sonarr_eventtype: $sonarr_series_title S$sonarr_episodefile_seasonnumber E$sonarr_episodefile_episodenumbers ($sonarr_episodefile_quality)\"}" https://hooks.slack.com/xxx/xxx
```

Does anyone knows the issue?

**Comment by markus101** [comment]
Test verifies that the script exists, there isn't a good way to test that it executes as at best case it would be feeding in dummy data and worst case the script could try to act on it and do something that caused data loss. The best way to test that its working is importing an episode.

**Comment by ratan12** [comment]
Sonarr is displaying a succeeded message. The download has already finished but I see no message appearing.

**Comment by ratan12** [comment]
Okay I succeeded linking Sonarr with Slack using windows with Git Bash!

Creating a slack.bat file did the trick!
**slack.bat:**
```
cd **path to slack.sh**
start slack.sh
```

**slack.sh**
```
#!/bin/bash
curl -X POST --data-urlencode "payload={\"username\": \"Sonarr\", \"icon_emoji\": \":ghost:\", \"text\": \"$sonarr_eventtype: $sonarr_series_title S$sonarr_episodefile_seasonnumber E$sonarr_episodefile_episodenumbers ($sonarr_episodefile_quality)\"}" https://hooks.slack.com/services/xxx/xxx/xxx
```
note: replace "https://hooks.slack.com/services/xxx/xxx/xxx" with the slack hook you got.
