### ISSUE TITLE
Indexers fail, breaking functionality

### ISSUE THREAD

**Issue by ezraholm50** [Sonarr/Sonarr#1302]
Hey, first off thanks for this awesome app. I searched for this topic but found nothing in the Github issue tracker. Therefor a new issue.

When connected to a VPN the indexers seem to fail `No available indexers. check your configuration.`
It also shows up in the system tab, something like: tried multiple times but the indexers have been disabled.

Now when I run a test on the indexer, at the tab settings, indexers, indexer... it says successful and I am able to use the indexer again. The error in the system tab disappears and I'm able to search again. But just for a short while, like a day or so...

Is there a way to find out the test command to set it as a cron job or something like that?

Ubuntu 14.04
Sonarr: 2.0.0.4146
Mono: 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)

ps: can't find the log entry of the indexer issue anymore, have 1200 pages of logfiles... I'm sorry.

Kind regards,

Ezra

**Comment by markus101** [comment]
This thread really belongs on the forums.

Without knowing why it failed all we can really say is Sonarr will incrementally back off when connections to indexers fail and then when connections are successful it will back down, if the indexer fails it won't try connecting for 5 minutes to start all the way up to 24 hours after 8 incremental failures (5, 15, 30, 60 minutes then 3, 6, 12 24 hours).

> Is there a way to find out the test command to set it as a cron job or something like that?

I'm sure its possible, but its not recommended or something we support. You're much better off figuring out why its failing and fixing the cause, not the symptom.

Please open a thread on the forums with the relevant information if you are able to ascertain the cause of the failure.
