### ISSUE TITLE
Quality profile comparison issue

### ISSUE THREAD

**Issue by endquote** [Sonarr/Sonarr#1307]
I have a series with the profile set to "HD-All". This got mostly 720p files. I decided I wanted to upgrade to 1080, so I set it to "HD-1080p". Files which were "HDTV-720p" had their quality icons turn light gray and look like they'll be updated. Great!

Others which say "WEBDL-720p" stayed dark -- if I do a manual search on these, a "WEBDL-1080p" in the results has an exclamation next to it, which says "Existing file meets cutoff: HDTV-1080p" -- except the existing file is "WEBDL-720p".

A bug, or do I just not get how profiles work?

**Comment by markus101** [comment]
Not a bug, it sounds like you altered the order of the profile and put `WEBDL-720p` above `HDTV-1080p`.
