### ISSUE TITLE
Unknown series on Anime, impossible to download

### ISSUE THREAD

**Issue by bubez81** [Sonarr/Sonarr#1308]
Hi, i'm trying to set up an anime (Dragon Ball Super) to search for specific subber DBF Soft-Sub NIF, now  sonarr search and found this DBF - Dragon Ball Super #33 FULLHD - Sub-Ita -, the episode is exact what i want but i can't download the torrent because is find as unknown series, probably the cause is the "#" can i do something?

**Comment by markus101** [comment]
Please use the forums for support next time. Its the `DBF - ` at the start, you can download it manually and rename it in your client so Sonarr can parse it properly.
