### ISSUE TITLE
Remove Releases from Download Client when Series is Deleted

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1311]
If there are active downloads and the series is removed we could also remove the releases from the download client. Perhaps opt-in like deleting files is.

**Comment by RustyF** [comment]
I think you could include removing the downloads as part of the delete files opt-in (and avoid complicating the ui with another option).  I think if the user intends to keep the series files, then perhaps they are just pausing their subscription and thus any in-flight downloads would be the final part of the now-static series files.  Likewise, if you choose to delete the files then why would you want another file to appear? So I think they are tied.  I'm sure you can say all that with half the words :)

**Comment by dankots** [comment]
Related to issue https://github.com/Sonarr/Sonarr/issues/281

**Comment by bakerboy448** [comment]
No plans for this at this time; limited or no user interest; closing
