### ISSUE TITLE
Event timeline or additional connect events

### ISSUE THREAD

**Issue by Cheezykins** [Sonarr/Sonarr#1313]
It would be nice to have some way of being notified when a new show is added to Sonarr.

Either an event in the existing connect options so a tweet or email etc can be triggered when a show is added, or some sort of timeline view in the options. Even the ability to sort by date added in the home screen would work.

Currently I have to manually go through my entire show list to see if my (non-technial) housemates have added anything new then go and check each one manually to check they have the path and profiles right etc.

Anything to facilitate this would be appreciated.

**Comment by markus101** [comment]
I don't see us adding an event when the series is added at least at this time, but being able to sort by the date added is in the backlog https://github.com/Sonarr/Sonarr/issues/390.
