### ISSUE TITLE
Delay deletion of upgraded media by N minutes

### ISSUE THREAD

**Issue by modest** [Sonarr/Sonarr#1314]
Common scenario for me:

1. Initial release of an episode finishes downloading.
2. A user starts playing the episode.
3. An upgraded release becomes available very soon after (PROPER, REPACK, HD version, etc.)
4. The upgraded release gets downloaded.
5. The old releases are deleted, breaking the user's playback.

To avoid this scenario, it would be really nice if Sonarr could wait an hour or two before deleting or recycling deprecated releases.  (In the interim, 2 copies of the episode would exist.)

Is this crazy? Am I missing a more obvious solution?

**Comment by kayone** [comment]
One issue I see with this system is if your file name config isn't unique enough to give the new file a different name.
 For example if you don't have quality in the file name both files would end up with the same name and couldn't exist side-by-side.

**Comment by markus101** [comment]
Whats to say that the old copy isn't in use X hours later? I don't like the idea of maintaining two copies of a file if we're relying on hoping its not in use later.

Perhaps what we really need is a way to check if the existing file is in use (but I see that being a problem given things may exist on different systems with different paths) alternatively a way to run a script and savvy users can implement a solution that would tie into the import decision making process and allow it to reject the import (which would be tried again later). Either way something like this seems very 1%er and could cause issues in some cases (such as season packs where only some files were imported).
