### ISSUE TITLE
indexer support for gingadaddy.com

### ISSUE THREAD

**Issue by homerjsim** [Sonarr/Sonarr#1315]
Hello,

any chance to get a preset for the indexer at gingadaddy.com? the URL format is a little bit different.

It looks like this:
https://www.gingadaddy.com/rss.php?feed=dl&cat=85,69,66,72,67,75&passkey=(removed)&uid=30191&fid=10443

If necessary, I can provide an invite.

Regards
homerjsim

**Comment by markus101** [comment]
https://forums.sonarr.tv/t/sonaar-stopped-working/10014/9

Looks like they blocked Sonarr or otherwise don't support the standard newznab API (when they did before).
