### ISSUE TITLE
QBittorrent doesn't delete torrent when finished seeding

### ISSUE THREAD

**Issue by berserkwarwolf** [Sonarr/Sonarr#1316]
It would be really helpful if you could add this option forthe popular open source qbittorrent download client. I've read the API docs and it seems to support this:

https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#delete-torrent

**Comment by markus101** [comment]
This is not a bug, Sonarr has no way of knowing whether the torrent has finished seeding or it was stopped for another reason, Sonarr is playing it safe and not deleting it and won't until we have a way to determine that it finished seeding.

**Comment by cbodley** [comment]
hi @markus101, sorry for commenting on a closed issue, but the inability to clean up completed downloads really limits the qbittorrent client's usefulness for me. is there a better place to hold a discussion about this change?

i would really like to find a way to make progress on this, and would be willing to coordinate with the qbittorrent project to find a proper solution

it would also be nice if, in the meantime, we could add an option to the qbittorrent settings to disable this change, and allow the possibly-not-fully-seeded torrents to be removed anyway. would you consider merging a pull request that adds (and documents) such an option?

**Comment by markus101** [comment]
qbittorrent isn't the only client that has this limitation, rTorrent is has it as well, and Transmission/Vuze probably should but Transmission was released before we considered the consequences so it is grandfathered in (and Vuze only has minor differences from Transmission).

> i would really like to find a way to make progress on this, and would be willing to coordinate with the qbittorrent project to find a proper solution

A proper solution is one of two things:

1. qbittorrent adds a flag so Sonarr can see it's finished seeding
2. Sonarr is aware of the seeding goals (per tracker) that need to be met (time/ratio) and can get the required information from qbittorrent (and all other clients) to determine if it can be stopped and removed.

> in the meantime, we could add an option to the qbittorrent settings to disable this change, and allow the possibly-not-fully-seeded torrents to be removed anyway. would you consider merging a pull request that adds (and documents) such an option?

I'm not in favour of adding another option when there are better solutions even as a quick workaround to add a feature doesn't give any incentive to fix it the right way and hacks have a tendency to become the permanent solution. I'm not opposed to more discussion on this though. @Taloth what are your thoughts on this?

**Comment by Taloth** [comment]
Ref: https://www.reddit.com/r/sonarr/comments/53ihv2/sonarr_not_removing_completed_downloads_qbittorent/

It appears that there might be a way to get it working similar to how we do it with deluge. Meaning that sonarr checks the torrent ratio against qbit settings to determine whether it was paused due to finishing seeding, or paused by the user.

And yes, I don't want a workaround switch in it either. Invites disaster.

**Comment by sveken** [comment]
Sorry to bring this back up, 
This was working great with Qbit, 
However i have updated to the new 4.0.4 and im noticing sonarr is now no longer removing completed torrents from Qbit, where before it was previously,

**Comment by cbodley** [comment]
@sveken this is due to a separate issue, fixed in https://github.com/Sonarr/Sonarr/issues/2438
