### ISSUE TITLE
Tons of path errors, how do I track down where they are coming from?

### ISSUE THREAD

**Issue by sgtsquiggs** [Sonarr/Sonarr#1317]
**Version**
2.0.0.4146
**Mono Version**
4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)

The log is flooded with
```value [net:[4026532398]]  is not a valid *nix path. paths must start with /```
but no other contextual information. How can I track down this issue? Is there a debug mode?

I get the errors when performing a manual search. The search ends instantly and then the log is filled with these errors.

**Comment by markus101** [comment]
Please open a thread on the forums with the requested information.
