### ISSUE TITLE
rtorrent not available as a download option in the gui

### ISSUE THREAD

**Issue by tirrorex** [Sonarr/Sonarr#1318]
Hi, it seems rtorrent is not an option in the gui anymore (at least i don't have it).
I am using latest version from developp branch with https://github.com/tuxeh/docker-sonarr
I have enable advanced settings.
Is there something special to do? did you guys remove rtorrent as a download client option?

**Comment by markus101** [comment]
Which version are you running (shown in the footer or System Status)? I see it on latest develop:

![image](https://cloud.githubusercontent.com/assets/413544/15582920/38826368-2328-11e6-9224-e2c4b69bef8f.png)

**Comment by tirrorex** [comment]
Sonarr Ver. 2.0.0.2665

**Comment by markus101** [comment]
That version was released on January 21 2015, the latest version is `2.0.0.4163` (which should be shown System: Updates).

**Comment by tirrorex** [comment]
Hum. this is weird, the client should've been at last version already? had to manually update
Thanks for the intel, have a good day
