### ISSUE TITLE
Organize & Rename from Series panel has no effect

### ISSUE THREAD

**Issue by HairyScot** [Sonarr/Sonarr#1319]
I copied some episodes of Penny Dreadful into a series folder that was being handled by Sonarr.
When I tried the Organize & Rename function it seemed to complete with no problem but none of the episodes were renamed.
Those episodes that were downloaded via Sonarr and Sabnzbd were OK.

Any ideas on how I can track down the problem?

**Comment by delphiactual** [comment]
Click "Update Series" first then "Organize & Rename" will work correctly...
Also support is handled on the forums

**Comment by markus101** [comment]
If you're still having issues please open a thread on the forums.
