### ISSUE TITLE
sonarr does not remove original download

### ISSUE THREAD

**Issue by wesleyg86** [Sonarr/Sonarr#1321]
after downloading, sonarr post-process the video and moves it to the new location defined in sonarr.
the original file on the download location does not remove.
the original file should be removed.

**Comment by markus101** [comment]
Not if its a seeding torrent: https://github.com/Sonarr/Sonarr/wiki/FAQ#seeding-torrents-arent-deleted-automatically

If its from a usenet client, please open a thread on the forums.
