### ISSUE TITLE
Replace/Remove illegal characters not consistent from directory to files.

### ISSUE THREAD

**Issue by pashdown** [Sonarr/Sonarr#1322]
Replace Illegal Characters:  ON
Series Folder Format:
{Series Title}
Standard Episode Format:
{Series Title} - S{season:00}E{episode:00} - {Episode Title} - {Quality Title}

How "Cosmos: A Spacetime Odyssey" ends up:
`Cosmos A Spacetime Odyssey/Season 01/Cosmos- A Spacetime Odyssey - S01E01 - Standing Up in the Milky Way - Bluray-1080p.mkv`

Note the added "-" after "Cosmos" on the filename.  I don't really care about this, but apparently Plex gets confused by it.  It would also be nice to have the switch be Replace | Remove | Keep illegal characters, and also be able to define what those illegal characters are, since they differ broadly from Linux to Windows.

**Comment by markus101** [comment]
The inconsistency comes from the series folder that was used when the series was imported, if Sonarr creates the folder it uses the same format as the episode file.

We do not have plans to allow for illegal characters in filenames or the ability to select which characters are considered illegal.
