### ISSUE TITLE
Update Plex When Show is Added

### ISSUE THREAD

**Issue by wschlotter** [Sonarr/Sonarr#1323]
When new episode has been fully processed through Sonarr it triggers update trigger API in plex to refresh.

**Comment by markus101** [comment]
Not sure if this is a feature request, but you can already update Plex automatically when an episode is imported, you'll need to setup a Plex Media Server connection (on the Connection settings page).

**Comment by markus101** [comment]
Please add more information if the existing functionality isn't what you're looking for.
