### ISSUE TITLE
Add option to use TheMovieDB.org instead of TheTVDB.com

### ISSUE THREAD

**Issue by mattman86** [Sonarr/Sonarr#1324]
I'm finding that TheTVDB.com is increasingly inaccurate when it comes to kids shows and shows like River Monsters and Cutthroat Kitchen. However, TheMovieDB is very good and will allow edits on previous seasons in case it is wrong. It would be awesome to be able to choose which one to use on a show-by-show basis or system-wide.

**Comment by markus101** [comment]
> will allow edits on previous seasons in case it is wrong

The issue with editing on TheTVDB is they strictly follow the networks (sometimes its the production order, but thats less common), but the flip side is anything can be edited and things change without notice (which is not unlike the Mythbusters season changes on TheTVDB I suppose).

We had some discussions about how we can support other media sources in a unified way, but for the time being we haven't decided how we will approach that and which sites might be used (TMDB and TVMaze both seem reasonable, but they have far less information than TheTVDB does).

Closing this issue as its not something we're committing to right no and we are still discussing how it will be done.

**Comment by halali** [comment]
Is possible open discussion for this ?

im not able add any Czech or Slovak series

**Comment by Dnkhatri** [comment]
@halali 
Add them to tvdb yourself after that you will need wait 24hrs before adding them to sonarr

**Comment by halali** [comment]
They are there but only in slovak/czech lang title. And i cant add english title to them. I can edit everything but not title language

**Comment by markus101** [comment]
Due to people defacing the titles on TheTVDB they have prevented users from editing the titles. I believe the easiest way to correct that would be to open a thread on their forums.
