### ISSUE TITLE
http://apt.sonarr.tv uses weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by todthomson** [Sonarr/Sonarr#1326]
> https://github.com/Sonarr/Sonarr/wiki/Installation#linux

Just as an FYI (I suspect you know about this already) since upgrading to _Ubuntu 16.04_ when running `sudo apt-get update` _Apt_ prints the following warning:

```
W: http://apt.sonarr.tv/dists/master/InRelease: Signature by key
A236C58F409091A18ACA53CBEBFF6B99D9B78493 uses weak digest algorithm (SHA1)
```

I suspect the "fix" is just to use SHA256?

**Comment by M0UL** [comment]
this is already  posted here: https://github.com/Sonarr/Sonarr/issues/1202

**Comment by todthomson** [comment]
> this is already posted here: #1202 

Apologies => I did search but could not find an pre-existing issue.

Closing.
