### ISSUE TITLE
Some episodes not offering download even if present, 'Unknown Series' error

### ISSUE THREAD

**Issue by rimkashox** [Sonarr/Sonarr#1328]
For instance in my case the 1st episode of "The Story of God with Morgan Freeman" in 720p is not matched even if present, when I go into manual mode it says rejected because 'Unknown Series'.

The title starts with: 'ngc' which obviously stands for 'National Geographic Channel'.

![screen shot 2016-06-06 at 12 17 15](https://cloud.githubusercontent.com/assets/518555/15819079/4dc91bec-2be1-11e6-80d2-645b327cbdee.png)

**Comment by thezoggy** [comment]
this is by design.. as sonarr wouldnt know how to process it...  ideally a naming exception should be submitted so everyone benefits.

**Comment by markus101** [comment]
There is an issue open for this already as well:

https://github.com/Sonarr/Sonarr/issues/395
