### ISSUE TITLE
rTorrent uses the raw Webclient.

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#1329]
Xmlrpcnet uses the raw Webclient.

Meant that newer ciphersuites aren't supported (such as the ECDHE elliptic curve ciphers).

Workaround is to use RSA DHE with AES as crypto (iirc)

**Comment by markus101** [comment]
Given the curl fallback is unnecessary with mono 5+ and talking directly to SCGI is likely the best option I'm going to close this.

https://github.com/Sonarr/Sonarr/issues/2007 for using SCGI.
