### ISSUE TITLE
Synology Video Station compatibility

### ISSUE THREAD

**Issue by Popsikill** [Sonarr/Sonarr#1330]
Hi All,

Just putting an issue out there I've found when integrating my files into Synology Video Station.

Basically Video Station doesn't recognize the 'Specials' folder created by Sonarr in my (Synology) file system - instead it just creates a TV Show called 'Specials' with the files in it..

 It would be great to have the option to switch to 'Season 00' or 'Season 0' - Video Station seems to use work with this naming format, putting them under the correct TV Show under season '?'.

I believe most other applications (Kodi, Plex etc) support both 'Specials' and 'Season 0'/''Season 00'?

Thanks!

**Comment by markus101** [comment]
You can accomplish this by adding the Season folder to format to the episode file naming and turning off using season folders for each series (use series editor to disable them all). We don't plan to make it a separate option.
