### ISSUE TITLE
bad regex for series title

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#1334]
`How.Its.Made.Dream.Cars.S01E01.Morgan.Aero.Coupe.HDTV.x264-C4TV` is being accepted for `How Its Made` instead of an unknown series for newznab sites... believe it has to do with recent `S## - E##` regex...

**Comment by markus101** [comment]
As discussed on IRC the issue is with the TVRage or TVDB ID matching from the indexer and the surprises that brings.
