### ISSUE TITLE
invalid literal for int() with base 10: ',' Is Sonarr compatible with high grade SSL indexer?

### ISSUE THREAD

**Issue by BenoitMartin2** [Sonarr/Sonarr#1336]
Hi,

I use Sonarr with NZBhydra (~ Jackett for Usenet). With NZBhydra using HTTP  it's ok. But I recently setup a HTTPS NZBhydra (TLS1.2 only, https://i.imgur.com/tWQwWgS.png) and then Sonarr can't use it anymore.
Config is the same, only domain/tld and SSL cert changed. 

Here is the Sonarr log: http://pastebin.com/eCEnFWMh
And the NBZhydra one: http://pastebin.com/mHx4Acwv

**Comment by Taloth** [comment]
That's a nzbhydra error throwing an 500:InternalServerError. It's even in your nzbhydra log. 
Looks like an issue with the parsing of cat=5030,5040.

https://github.com/theotherp/nzbhydra/issues/285
