### ISSUE TITLE
[Feature Request] Delay renaming until after fully seeded torrent (even if Transmission is offline)

### ISSUE THREAD

**Issue by FireDrunk** [Sonarr/Sonarr#1338]
I've been sifting thru the code to find the lines where Sonarr makes the decision to make a hardlink/symlink or move a file to it's new location.

In the process of doing this, it decides that if the download doesn't yet meet the set ratio (in transmission) that it will hardlink the file instead of moving it (which is exactly what i want).

The problem is, that even though i have this setting on, occasionally Sonarr will still move the file, if it cannot contact Transmission (because it's not running) or for some unknown reason.

I would like for a button that will state:
"Wait for seeding to complete, before processing the file"

This means, that even though Sonarr can't contact Transmission, or the download is paused, or for whatever reason, it cannot make sure that the ratio has absolutely been met (including when Transmission is stopped/offline/unresponsive), it doesn't process the file, and mark it as "still being downloaded" (or something alike).

If you tell me where to look for this in the sources, i can assist in the coding, but this would be my first time coding for Sonarr, but happy to help, if it's required.

**Comment by Taloth** [comment]
If sonarr can't talk to transmission it won't import, simply because it doesn't know the download exists.
Unless you also configured the drone factory, that would be bad.

**Comment by FireDrunk** [comment]
Uh, ok, that's probably the issue. I have the Drone Factory enabled... :(
