### ISSUE TITLE
WEB getting detected as HDTV

### ISSUE THREAD

**Issue by Nyghto** [Sonarr/Sonarr#1339]
I started working with some private torrent trackers. And today i noticed that it automatically downloaded a web-dl release for Game of Thrones. While i created a profile that should only download 1080p HDTV releases. Checking further i discovered Sonarr indexes some web releases as HDTV and downloads them. After it happened the first time i replaced the latest episode for a HDTV release. But later this day it got replaced by a proper web-dl release again thinking it was a HDTV release. The strange thing is that in the overview page it displays it as a WEB-DL release.

![webashdtv](https://cloud.githubusercontent.com/assets/1236301/16019996/43a6410a-31ac-11e6-88f4-f18b7ccd7149.jpg)
![web-dl-overview](https://cloud.githubusercontent.com/assets/1236301/16019997/43a79852-31ac-11e6-95dd-9d9b1d71f8bd.jpg)

**Comment by MuriloCalegari** [comment]
I'm still seeing this issue. Was this commit ever published? Release is: 

> Brooklyn Nine-Nine 2013 S06E03 [MKV / H.264 / AC3/E-AC-3 / WEB / Legendado / Inglês / 1080p]

While Sonarr is identifying it as HDTV-1080p
