### ISSUE TITLE
Filtering on missing to exclude items already in the queue

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1341]
This is a bit tricky since queue is tracked in memory and missing episodes are pulled from the database a page at a time, but perhaps we can exclude items in the queue from the query.

**Comment by Taloth** [comment]
I vote no, just mark the queued status in the UI.
Doing it in the query is a pointless complication.

**Comment by markus101** [comment]
How would that work in the UI only? If we filtered them there we'd have pages that have less than the full page length of items.

**Comment by Taloth** [comment]
Not filter them in the UI, just show the progress bar (afaik we already do) or gray em out for more emphasis

**Comment by markus101** [comment]
Yeah, we show the progress already, the potential issue would be if you have 1000 missing and search for all missing and 999 are found and queued, there is one in there somewhere that wasn't queued, but it would be on one of those pages somewhere, so it could be nice to be able to see only that one. On the flip side the technical difficulties to exclude everything thats queued are there, having 999 things to ignore in a query would be pretty shitty and if you have 999 in the queue its not like adding one more item will make it appear faster.

**Comment by markus101** [comment]
Progress is shown in the UI in v3 and queued episodes are ignored when searching all missing, so I think we're good here.
