### ISSUE TITLE
Release Restrictions: Apply to tags/Do not apply to tags

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1343]
Right now its not possible to set a global restriction and block a term, such as `x265` and then in another restriction require `x265`and apply that to a specific tag. One thought that came to mind to get around that (without too much confusion and complication, I hope), would be to specify tags that the restriction applies to as well as tags the restriction doesn't apply to so you could apply it to all series (no tags) and tell it not to apply to a specific tag, say `x265-allowed` for example.

**Comment by M0UL** [comment]
i think i requested something like this a while back, but then for notifications.

**Comment by Taloth** [comment]
I think it's more relevant to specify the behavior if both required and restricted exists.

1) token is restricted in a tag.
2) token is required in a tag.
3) token is restricted in one tag. token is required in another tag. (required prevails)
4) token is restricted AND required n one tag. (restricted prevails)
5) token is restricted AND required n one tag. token is required in another tag. (restricted prevails)

Alternatively you could have a switch on a tag 'override' that overrides the global restrictions instead of being combined.

**Comment by Nelluk** [comment]
I feel like the intuitive way for this to work would be that blank-tag restrictions only apply to shows that have no tag. If a show has any tag, the blank-tag restriction no longer applies at all.

It's frequently tripped me up when someone tells me they can't do the blank-tag-restrict plus a nonblank-tag-require combo. Has never felt intuitive to me.

**Comment by thezoggy** [comment]
please add tag management first.. trying to hunt down what shows have tags/where they are used/etc.. is a huge pita. especially when you delete a tag

**Comment by smidley** [comment]
I agree with thezoggy.  I had this issue not too long ago.

**Comment by markus101** [comment]
@thezoggy @smidley thast not what this topic is about though, lets keep it on topic. Tag management is definitely on the list, lets not devolve other issues though.

**Comment by markus101** [comment]
> Alternatively you could have a switch on a tag 'override' that overrides the global restrictions instead of being combined.

I think I could get behind this, I don't think defining behaviour in a complex way makes sense and I feel like you're initial suggestion was quite complex. Would it be on the restriction or somehow linked to the tag? Seems reasonable to have another option on the restriction that overrides untagged restrictions.

> I feel like the intuitive way for this to work would be that blank-tag restrictions only apply to shows that have no tag. If a show has any tag, the blank-tag restriction no longer applies at all.

Tags could be used for a variety of reasons, it would be a pretty big side effect to want to use a tag for something else and have it drop your default restrictions/requirements.

**Comment by hbooo** [comment]
I got the same problem than OP, 

I had a restriction defined like this
![image](https://user-images.githubusercontent.com/242125/33066682-44e8e3d0-ceac-11e7-826f-4e0ffaf0a799.png)
but shows with tag "french" were never grabbed becaused logs said my release doesn't have vostfr fansub fastsub vost subfrench multi.

Tags should override no tags

**Comment by markus101** [comment]
With tag management and mass editing of tags in v3 I think we can avoid the complications of this, at least for the time being.
