### ISSUE TITLE
login

### ISSUE THREAD

**Issue by nyctallguy44** [Sonarr/Sonarr#1345]
any time i try to set up sabnzbd i get this screen or the one saying you must use an valid host without http. I'm trying to do this on my nas. 
![screen shot 2016-06-20 at 12 22 10 pm](https://cloud.githubusercontent.com/assets/20048690/16201957/abfbcd26-36e1-11e6-992d-36ea1f392082.png) i always enter an api, but i have taken it out for the picture in this post

**Comment by markus101** [comment]
Please open a thread on the forums with the requested information (when opening the thread).
