### ISSUE TITLE
Connections tab on series add

### ISSUE THREAD

**Issue by vinchi007** [Sonarr/Sonarr#1349]
Connections w/ Plex for example do not include "on Add" updates. When I added a new series to sonarr, notification was never sent to Plex server. All other "on upgrade" or "on download" work great!

![image](https://cloud.githubusercontent.com/assets/2197609/16279847/d3b26aa0-388a-11e6-8102-2fbfdda6c3e6.png)

**Comment by markus101** [comment]
If the series is empty why does Plex need to be notified?

**Comment by markus101** [comment]
If you can provide more information why this is needed we can consider it, but closing it for the time being.
