### ISSUE TITLE
Option to rename all Series

### ISSUE THREAD

**Issue by rigrassm** [Sonarr/Sonarr#1352]
Would be nice to have an option to scan and rename all files when a change is made to the naming format instead of having to do each series manually.

**Comment by markus101** [comment]
You can do this from `Series Editor` (Organize).

**Comment by keithfree** [comment]
@markus101 Are you sure the issue @rigrassm mentions is a current feature? He appears to be asking if you can trigger a scan/rename of all files within all series without going into each series and "organizing" individually.

**Comment by keithfree** [comment]
Nevermind, I figured it out.

**Comment by ElanHasson** [comment]
@keithfree Please share how you did it.

**Comment by Taloth** [comment]
@ElanHasson 

> You can do this from Series Editor (Organize).

**Comment by ElanHasson** [comment]
Thanks, didn't see the options at the bottom of the screen.

I do now.

**Comment by keithfree** [comment]
@ElanHasson Go to the Series page, click "Series Editor", click the checkbox on the top left of that page (which should select all of your series), click the red "organize" button on the bottom right of the page, and finally at the bottom of the modal window that pops up click the red "organize" button.

**Comment by IamDeMan** [comment]
@keithfree thank you for taking the time to write the steps out. I can see how it is not as intuitive to folks because it is a little out of the "normal" UI that they have trained us to use. Your post took me right to it.
