### ISSUE TITLE
Update Emby metadata support

### ISSUE THREAD

**Issue by LukePulverenti** [Sonarr/Sonarr#1353]
Hi guys,

Emby's default metadata format is nfo and has been for quite some time now. Here is a suggestion that will result in less work for you guys to support Emby.

Drop the separate Emby xml saver, and update the display name of the Kodi nfo saver to something like Kodi/Emby. This way Emby users are directed towards nfo rather than xml.

You can keep the xml format if you wish, but we consider it legacy now. In the event you do decide to keep it, please have some way of defaulting Emby support to nfo, and only utilizing xml if explicitly requested by the user. Thanks!

**Comment by markus101** [comment]
Thanks for reaching out @LukePulverenti, we do plan to phase out the old Emby XML (likely v3), but we can update the naming of the Kodi metadata generation before then.
