### ISSUE TITLE
Selects the wrong serie - Castle (2009)

### ISSUE THREAD

**Issue by Leverpastej** [Sonarr/Sonarr#1354]
Hi,

How do I change the serie/movie that Sonarr has associated with?
For some reason [Castle (2009)](http://www.imdb.com/title/tt1219024/?ref_=tt_rec_tt) looks like this:
![2016-06-27 20_10_57-castle - sonarr](https://cloud.githubusercontent.com/assets/20172244/16390524/8071e344-3ca3-11e6-9783-215b28d777f0.png)

I've tried google and here but couldn't find anything.

Any idéa?

**Comment by markus101** [comment]
You will need to remove the series and select the correct one when you import it.

**Comment by Leverpastej** [comment]
I just added all in my library (Y:\) and only this serie were wrong.
But I've removed it and added by searching for it (not in my own storage)

**Comment by markus101** [comment]
> I just added all in my library (Y:) and only this serie were wrong.

It likely picked the wrong one based on how the folder was named, if it was named `Castle` then it would pick that series by default. The import screen allows you to change the default series, Sonarr just tries to pick the best one given the folder name.

> But I've removed it and added by searching for it (not in my own storage)

Make sure the folder chosen automatically matches the folder on disk, given the fact it picked the wrong one when you imported it, it'll probably be pointed to a different folder.

**Comment by Leverpastej** [comment]
Thank you!
It solved the problem:)
