### ISSUE TITLE
Telegram Notifications 

### ISSUE THREAD

**Issue by UiharuKazari2008** [Sonarr/Sonarr#1355]
Coming from SickRage it would be nice to see Telegram Notification support so i can keep my typical work flow.

**Comment by GiroudMathias** [comment]
Hi,

Check this link: https://github.com/onedr0p/telegram-sonarr-bot ;)

**Comment by craigcabrey** [comment]
@GiroudMathias that is for interacting with sonarr *from* Telegram. @UiharuKazari2008 is asking for sonarr to send notifications *to* Telegram.

[Here](https://github.com/mmcdole/sonagram) is a workaround for now.

**Comment by xoniq** [comment]
The solution from @GiroudMathias is a two-way solution.

I use it for interacting with Sonarr from Telegram on my phone, but the same bot can be used for notifications using a custom script as notification in Sonarr.

Path: `/usr/bin/node`
Arguments: `/path/to/telegram-sonarr-bot/sonarr_notify.js`

Works perfectly, one bot for both notifications and interaction.

**Comment by peelos** [comment]
Would agree that a nice integrated telegram notification solution to sonarr would be the preferable solution here, especially for those not running on windows and without a premium pushbullet account 

PlexPy and Couchpotato both have a nice integrated solution

**Comment by PHoSawyer** [comment]
I've just created my own script for doing this and then used it as an external script. I'll see if I have time to try and fork and implement

**Comment by artbird309** [comment]
@PHoSawyer Correct I already built a Telegram notification it just needs to be merged.
