### ISSUE TITLE
Unable to communicate with qBittorrent

### ISSUE THREAD

**Issue by Mistywing** [Sonarr/Sonarr#1358]
Unable to communicate with qBittorrent. Input string '1.8446744073708044e+19' is not a valid integer. Path '[25].eta', line 1, position 12339

qBittorrent ver 3.3.5
Sonarr ver 2.0.0.4213 - Jun 29 2016 [develop]

Issue started happening today.
Issue persists after restarting both Sonarr and qBittorrent.
Authentication to qBittorrent has been verified as set to be correct (username/password).
The position of the error reported seems to vary quite a bit across application restarts, but the type of error (invalid integer) is always the same. I got position numbers from 4000 all the way up to 30000. The input string is constant too for the seventeen digits listed.

**Comment by markus101** [comment]
Please open a thread on the forums with the requested information.
