### ISSUE TITLE
Assignment outside of section. Ignoring.

### ISSUE THREAD

**Issue by VogelxPsycho** [Sonarr/Sonarr#1360]
I just tried setting up Autostart on Linux (https://github.com/Sonarr/Sonarr/wiki/Autostart-on-Linux#systemd) using the systemd method. When I run the service using `systemctl start sonarr.service` I get an authentication pup-up, I fill in my password and this shows up in the terminal: `Failed to start sonarr.service: Unit sonarr.service is not loaded properly: Invalid argument.
See system logs and 'systemctl status sonarr.service' for details.
` So I run `systemctl status sonarr.service` and I get this: 
```
● sonarr.service - Sonarr Daemon
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)

jul 01 15:34:33 VogelxPsycho systemd[1]: [/lib/systemd/system/sonarr.service:1] Assignment outside of section. Ignoring.
jul 01 15:34:33 VogelxPsycho systemd[1]: [/lib/systemd/system/sonarr.service:18] Missing '='.
jul 01 15:34:49 VogelxPsycho systemd[1]: [/lib/systemd/system/sonarr.service:1] Assignment outside of section. Ignoring.
jul 01 15:34:49 VogelxPsycho systemd[1]: [/lib/systemd/system/sonarr.service:18] Missing '='.
jul 01 15:40:49 VogelxPsycho systemd[1]: [/lib/systemd/system/sonarr.service:1] Assignment outside of section. Ignoring.
jul 01 15:40:49 VogelxPsycho systemd[1]: [/lib/systemd/system/sonarr.service:18] Missing '='.
jul 01 15:42:06 VogelxPsycho systemd[1]: [/lib/systemd/system/sonarr.service:1] Assignment outside of section. Ignoring.
jul 01 15:42:06 VogelxPsycho systemd[1]: [/lib/systemd/system/sonarr.service:18] Missing '='.
jul 01 15:44:34 VogelxPsycho systemd[1]: [/lib/systemd/system/sonarr.service:1] Assignment outside of section. Ignoring.
jul 01 15:44:34 VogelxPsycho systemd[1]: [/lib/systemd/system/sonarr.service:18] Missing '='.
```

My sonarr.service file is located in `/lib/systemd/system/sonarr.service` and looks like this:
```
cat > sonarr.service << EOF
[Unit]
Description=Sonarr Daemon
After=syslog.target network.target

[Service]
User=vogelxpsycho
Group=vogelxpsycho

Type=simple
ExecStart=/usr/bin/mono /opt/NzbDrone/NzbDrone.exe
TimeoutStopSec=20
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
```

**Comment by ajfried22** [comment]
this is mine, you could be having user permission issues or you are not pointing to the right directory
[Unit]
Description=Sonarr Service
After=network.target

[Service]
User=sonarr
Group=sonarr
ExecStart=/usr/bin/sonarr -nobrowser -data=/var/lib/sonarr
Type=simple
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target

**Comment by markus101** [comment]
If you need further assistance please open a thread on our support forums.

**Comment by VogelxPsycho** [comment]
I've added a new user using `sudo useradd -r sonarr` and used this account with the service file like @ajfried22 did, this fixed it. Thanks!
