### ISSUE TITLE
Feature request: Ability to specify language ID for TVDB search

### ISSUE THREAD

**Issue by Torkiliuz** [Sonarr/Sonarr#1364]
As the title suggests I see a need for the ability to also specify the language ID when adding a show by TVDB id. As it is now it's only possible to add a show by TVDB id if it has an english language id. This limits the ability to add for example norwegian TV shows to Sonarr.

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/269
