### ISSUE TITLE
.srt files are not being renamed

### ISSUE THREAD

**Issue by vinchi007** [Sonarr/Sonarr#1366]
along with .mkv there are .srt subs. Sonarr renames perfectly episodes (.mkv) but does not do so with .srt files

`
-rw-rw-rw-  1 921  mymedia  158322695 Jul  3 16:37 Continuum (Web Series) - S02E05 - Minority Reporting SDTV.mkv
-rw-rw-rw-  1 921  mymedia  158183853 Jul  3 16:37 Continuum (Web Series) - S02E06 - Artificial Intelligence SDTV.mkv
-rw-rw-rw-  1 921  mymedia  158029329 Jul  3 16:35 Continuum (Web Series) - S02E07 - The Wrath of a Con SDTV.mkv
-rw-rw-rw-  1 921  mymedia  158007478 Jul  3 16:37 Continuum (Web Series) - S02E08 - Phone Home SDTV.mkv
-rw-rw-rw-  1 921  mymedia  158113083 Jul  3 16:37 Continuum (Web Series) - S02E09 - The Final Frontier SDTV.mkv
-rw-rw-rw-  1 921  mymedia      49470 Jul  1 23:37 Continuum.S02E01.480p.vk007.srt
-rw-rw-rw-  1 921  mymedia      53108 Jul  2 00:35 Continuum.S02E02.480p.vk007.srt
-rw-rw-rw-  1 921  mymedia      51072 Jul  1 23:47 Continuum.S02E03.480p.vk007.srt
-rw-rw-rw-  1 921  mymedia      46781 Jul  2 00:29 Continuum.S02E04.480p.vk007.srt
-rw-rw-rw-  1 921  mymedia     110578 Jul  2 00:07 Continuum.S02E05.480p.vk007.mkv_thumbs_[2013.08.06_22.29.21].jpg
-rw-rw-rw-  1 921  mymedia      52775 Jul  2 00:07 Continuum.S02E05.480p.vk007.srt
-rw-rw-rw-  1 921  mymedia      62435 Jul  2 00:04 Continuum.S02E06.480p.vk007.srt
-rw-rw-rw-  1 921  mymedia      47610 Jul  1 23:45 Continuum.S02E07.480p.vk007.srt
-rw-rw-rw-  1 921  mymedia      54069 Jul  2 00:39 Continuum.S02E08.480p.vk007.srt
-rw-rw-rw-  1 921  mymedia      45475 Jul  1 23:34 Continuum.S02E09.480p.vk007.srt
-rw-rw-rw-  1 921  mymedia  158102681 Jul  3 16:36 Continuum.S02E10.480p.vk007.mkv
-rw-rw-rw-  1 921  mymedia      48012 Jul  1 23:53 Continuum.S02E10.480p.vk007.srt

`

**Comment by markus101** [comment]
Additional files (outside of the metadata files Sonarr can manage) are not moved or deleted by Sonarr.

https://github.com/Sonarr/Sonarr/issues/459
