### ISSUE TITLE
Moving to .Net Core

### ISSUE THREAD

**Issue by roly445** [Sonarr/Sonarr#1367]
Are you looking at moving the project over to .Net Core at all?

**Comment by markus101** [comment]
We need to investigate if it will be possible and which 3rd party libraries will need to support it first or if we can work around it.

https://github.com/Sonarr/Sonarr/issues/948

**Comment by Taloth** [comment]
It's not possible to move over at this point as it would break many platforms such as synology and likely freebsd as well.

**Comment by Snorflake** [comment]
Any update on the move?

**Comment by eberkund** [comment]
Any update on the move?

**Comment by dannymichel** [comment]
lidarr and radarr did this.
any news?
