### ISSUE TITLE
Multilanguage metadata

### ISSUE THREAD

**Issue by Ethras** [Sonarr/Sonarr#1371]
At the moment, it's only possible to get metadata (Kodi for example) in English. It would be great if we could setup a somewhere other language for metadata download. It's already possible with Sickrage why not Sonarr ;)

**Comment by markus101** [comment]
Metadata will use the language of the metadata downloaded by Sonarr, which at this time is only English.

https://github.com/Sonarr/Sonarr/issues/269

**Comment by GiroudMathias** [comment]
when do you add more languages? ...

**Comment by markus101** [comment]
Something we'll look at when we move to TVDB's new API...

**Comment by GiroudMathias** [comment]
The French community is impatient! this would be a really useful feature! good change for integration of new TVDB's API

**Comment by Miaourt** [comment]
Any news on that ?

**Comment by DesertCookie** [comment]
No news. Still doesn't allow you metadata in other languages other than English.
