### ISSUE TITLE
Empty Season folders left over after change in name

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#1372]
I recently changed the season folders from season 1 to season 01. Now many of my shows have empty season 1 left over. I would also like the option to delete season folders if all the video files of a completed season have been deleted.

**Comment by markus101** [comment]
If the folders are completely empty (no extraneous files left) they are removed automatically, if there is a file left over Sonarr leaves the folder to avoid deleting something that you may want that it wasn't tracking.
