### ISSUE TITLE
Aria2 Torrent Client

### ISSUE THREAD

**Issue by MikuroK** [Sonarr/Sonarr#1374]
aria2 can be run as a daemon and be controlled via an HTTP/websocket RPC which may make it suitable for use with Sonarr

**Comment by jeffmhasty** [comment]
I've been playing around with this and it's definitely feasible. I'm planning on submitting a PR, but I don't know when I'll realistically be able to finish it up.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
