### ISSUE TITLE
Blacklist: Separate Torrent & Nzb (or even specific Indexers)

### ISSUE THREAD

**Issue by blastagator** [Sonarr/Sonarr#1375]
Often times a release will be blacklisted on an nzb indexer and apply to other nzb indexers and torrent indexers.

It would be more prudent to blacklist a release listed nzb indexers if an nzb fails.  This would allow the "same" release to be downloaded via torrent, instead of not even trying.  Often an nzb fails due to usenet and not the fact the release is bad.  Torrent should be picking up the slack, not failing to even try.

**Comment by markus101** [comment]
A blacklisted usenet release will not block a torrent release with the same name. For torrents its blocked based on the torrent hash and for usenet releases this is the most in depth explanation: https://forums.sonarr.tv/t/blacklist-not-working/11239
