### ISSUE TITLE
I've Broke Sonarr, do i win a prize?

### ISSUE THREAD

**Issue by JaxEden** [Sonarr/Sonarr#1376]
I set my computers date to 2034 for 10 minutes and then reset it back to the correct date, and now nothing will work, won't search, won't refresh, can't add new series.... 

Go me.............

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
Restarting Sonarr should reset the last run time of the tasks and refreshing all the series from the main page will reset the last updated time of all the series. If you had any indexer failures you'll need to fix those manually for the time being, directly in the DB.

**Comment by markus101** [comment]
Also, no prizes because this belongs on the forums.

**Comment by JaxEden** [comment]
Directly in the DB?

**Comment by markus101** [comment]
In the `IndexerStatus` table, though I've filed https://github.com/Sonarr/Sonarr/issues/1386 which will take care of cleaning it up automatically.

**Comment by JaxEden** [comment]
Great. Thank you for getting in touch
