### ISSUE TITLE
Provide option to choose the installation path in Windows installer

### ISSUE THREAD

**Issue by techgeek03** [Sonarr/Sonarr#1378]
Hello,

Since you are creating a windows service that runs as "Local System" there is no need to hard code the installation path to C:\ProgrammData . If you are like me, I regularly clean this folder. "Local System" is one of the most powerful accounts and under Windows it has all permissions. It can read/write everywhere. More over, since the installer is also running under elevated  privileges you can set correct permissions to all folders the application is using at the installation process it self.

**Comment by Taloth** [comment]
Eum, C:\ProgramData is kinda important, it isn't a Temp dir. You can't just arbitrarily delete stuff from it, it contains the data from all applications that isn't specific to one user (Compared to the users AppData directory).   
Theoretically you could install Sonarr somewhere else, but it's appdata would remain in ProgramData anyway, so there's little point.
