### ISSUE TITLE
Indexers on Sonarr

### ISSUE THREAD

**Issue by carlsen2dk** [Sonarr/Sonarr#1379]
Hi

Suddenly my DanishBits indexer in Sonarr stopped working. I tested all settings, URL and API and everything was correct.
I then deleted the indexer and try re-config it, but now everytime I get the following error when trying to setup and pres test:
**"No results were returned from your indexer, please check your settings."**

In the log file it says:
**Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings.**

Any ideas? I have tried resetting the entire Sonarr system and setting up again. No luck
/CC

**Comment by markus101** [comment]
Sounds like a problem with your indexer, try contacting their support. If you're still having issues please open a thread on the forums.
