### ISSUE TITLE
Show remaining diskspace when choosing a rootfolder

### ISSUE THREAD

**Issue by Remco32** [Sonarr/Sonarr#1382]
To make this software a little more parent-proof, it would be great if the software would show the remaining diskspace that is left on the drive of the rootfolder when adding a new show.

This way, new shows won't all be manually added to the same drive.

**Comment by Taloth** [comment]
Not a bad idea.
The data is available, see the dialog when trying to add a new path, but adding it to the dropdown UI would be tricky.

I'm not opposed to the idea but some things that pop in my mind:
- Shows vary considerably with how much space they would take, so it doesn't necessarily solve the problem for ppl that are less computer proficient.
- There are solutions to grouping drives into a virtual one. That would eliminate it entirely.

**Comment by Remco32** [comment]
>  Probably impossible even, coz the dropdown content can't be styled, afaik.

I assume it isn't then as simple as printing both the root directory + the space left on the line? i.e "C:/test" becomes "C:/test [500GB left]"?

> Shows vary considerably with how much space they would take, so it doesn't necessarily solve the problem for ppl that are less computer proficient.

Sure, but people can then simply always pick the disk with most space left.

> There are solutions to grouping drives into a virtual one. That would eliminate it entirely.

I've looked into those, but I'm afraid it wouldn't work with external HDDs very well.

Thanks for your time.

**Comment by Taloth** [comment]
> I assume it isn't then as simple as printing both the root directory + the space left on the line? i.e "C:/test" becomes "C:/test [500GB left]"?

Ugly.

Take this, looks so much better... sadly it's a horrible hack that breaks the ui on some levels. It probably will have to wait till our new ui. (don't ask, no etas)... or until I get an epiphany.

![image](https://cloud.githubusercontent.com/assets/6383890/16929586/be7634ec-4d38-11e6-85b7-149173cefa57.png)

**Comment by markus101** [comment]
This is done as part of the v3 work.
