### ISSUE TITLE
Change kat.cr url to kat.al

### ISSUE THREAD

**Issue by moust4ki** [Sonarr/Sonarr#1388]
kat.cr has been shut down, could you please update the url to https://kat.al?
There is a reddit post about all the working URL, why not add them as a fallback?
https://www.reddit.com/r/kickasstorrents/comments/4txvlx/working_urls_wiki/

Thanks

**Comment by markus101** [comment]
`Unable to connect to indexer. Indexer responded with html content. Site is likely blocked or unavailable.`

That's from a test of kat.al in Sonarr, which means it won't work. At this time we plan to clear out the default URL, but any replacements will need to be properly configured and not return RSS using the Content-Type `text/html` (which is the same Content -Type you'd get if it was blocked by your ISP/proxy).

**Comment by th3m4ri0** [comment]
This is a mirror of an archive. The original functional website is gone and probably isn't coming back.
