### ISSUE TITLE
Request - bulk search for wanted items at a different quality

### ISSUE THREAD

**Issue by HarleyCarter1234** [Sonarr/Sonarr#1390]
it would be nice if there was a quick way of bulk updating, or bulk searching wanted items on a different quality to what is set at the actual series level

for example. Having a series set to SD and having downloaded a lot of episodes, there are some that have been missed. Going and doing a manual search on these episodes shows that there are downloads available at 720p.

it would be great to have something on the wanted items tab to search all or selected at a specific quality so that we could quickly and easily try to fill in the gaps with whatever is available

hopefully that makes sense

**Comment by markus101** [comment]
The series quality will always be respected, if you want to fill things in at a different quality you can either use a manual search or change the quality profile linked to the series and search, we don't have plans to alter the behaviour beyond that, though this might be of use whenever it gets implemented: https://github.com/Sonarr/Sonarr/issues/266
