### ISSUE TITLE
Deleted episode not being unmonitored

### ISSUE THREAD

**Issue by ThatWhiteMonster** [Sonarr/Sonarr#1395]
Hi,

I've been using Sonarr on Windows to some extent for a few month now. It's a great app! I love it!
There are some features that I wish it had but that's another conversation (*cough*cough*subtitle handling*cough*cough*) .
;)

Anyway . . .

Recently, I've reconfigured it to actually handle the media management properly (monitoring existing episodes and such), instead of just acting as an "indexer watcher". It worked nice for a few days but now I've noticed something is wrong.

I have "Ignore Deleted Episodes" option enabled and it was working fine. 
I tend to only keep the recent episode and delete the whole series folder with that one episode after I watched it.
But now I see that after I delete an episode manually via Explorer and go and hit "Update series info and scan disk" button in the series page, the episode remains monitored and the path to deleted file is still being displayed.
Then if I try to delete via Sonarr and hit rescan, the episode remains monitored and the icon describing the quality profile comes back from "Missing" to let's say "HDTV-1080p". In both attempts, the episode in question is completely deleted - it's not in the library, it's not in the Sonarr recycle bin, it's not in the torrent client queue or downloads folder.

There's nothing in the logs if I rescan after deleting the episode. Obviously, when I try to delete it again via Sonarr, it says that the file doesn't exists. Yet it still comes back (as if it exists) with the quality indicator and previous path after another rescan.

Does this mean I can't delete the series folder along with the episode? Please help, as it would be nice if I didn't have to keep empty series folders in my library folder. That's why I have "Create empty series folders" unchecked after all.

Thank you in advance,
mnstr

**Comment by markus101** [comment]
>Does this mean I can't delete the series folder along with the episode?

Yes, when the series folder is missing Sonarr doesn't assume that the it was deleted because that can cause issues in some setups. Ideally it would detect that they are missing regardless of the folder being present and either handle that as deleted or temporarily missing to deal with the issues that are currently caused in some setups. This is the relevant issue for that: https://github.com/Sonarr/Sonarr/issues/976

If you use Sonarr to delete the file, delete only the file from explorer or have Sonarr create empty series folders you won't run into the current limitation.

**Comment by ThatWhiteMonster** [comment]
Thank you for the explanation, @markus101 .

> when the series folder is missing Sonarr doesn't assume that the it was deleted because that can cause issues in some setups

I see. But if the scan is triggered manually by the user - if so, user should be aware if the drive is disconnected and understand that episodes in the rescanned series will be unmonitored.
 

> If you use Sonarr to delete the file, delete only the file from explorer or have Sonarr create empty series folders you won't run into the current limitation.

I think that Sonarr should delete the entry from the database and optionally unmonitor the episode if said episode is deleted manually from the episode properties. Even if the file is recognized as missing.

Instead, the entry comes back after another rescan and Sonarr states that the episode is present and gives you a false quality badge (i.e. even if the episode was WEBDL-1080p, the replaced badge says HDTV-720p). 
The user notices the missing file only after going through logs - there's no warning that some file is considered missing. That's really misleading.
