### ISSUE TITLE
Join by joaoapps API support to replace Pushbullet?

### ISSUE THREAD

**Issue by seriosbrad** [Sonarr/Sonarr#1397]
Pushbullet, starting August 1st is blocking access to some third party senders. This could include software such as CouchPotato, SABNzbd, Sonarr, etc..

I would highly recommend checking out Join to see if it can be integrated into Sonarr as Pushbullet is ultimately heading down an unfriendly paid route that will affect a lot of us using automated notifications.

**Comment by arebokert** [comment]
The devs are open to compromising in this scenario if the sonarr devs start clumping pushes together, as can be seen in their reddit thread here

https://www.reddit.com/r/PushBullet/comments/4ullh7/august_1st_deadline_to_block_scriptedautomated/d5qq3uz

I agree however that it would be great if other push services were supported in-case pushbullet is ruled out completely.

**Comment by markus101** [comment]
There is already a GHI for Join... https://github.com/Sonarr/Sonarr/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20join
