### ISSUE TITLE
"System - Disk Space" inaccurate; OSX autofs mount is "Unknown" type

### ISSUE THREAD

**Issue by doktorstick** [Sonarr/Sonarr#1399]
_Edit:_ `Sonarr` does use longest-path for series' mount computation; updated title to reflect root of the problem.

I'm on Mac OS X with a Synology NAS connected. The "System - Disk Space" only shows "/" despite my media folder being elsewhere. I've seen bugs opened and dismissed under the statement "it depends on what your OS reports". That's true, but not entirely accurate. Here's a sample program that shows my OS does in fact display the mounts (the code is at the bottom of the report):

```
$ mono free.exe
name: / free: 291654406144
name: /dev free: 0
name: /net free: 0
name: /home free: 0
name: /mnt/toaster free: 0
name: /mnt/toaster/videos free: 2215810793472
name: /mnt/toaster/music free: 2215810793472
```

In my particular case, the `autofs` system creates the mount points to `toaster` for `videos` and `music`. While `/mnt/toaster` reports as 0-bytes (because the root of the automounted filesystem isn't writable), the real mountpoints are writable.

What needs to be done in `NzbDrone.Core.DiskSpace.DiskSpaceService`[1] is to find the longest matching `DriveInfo` paths of the series' paths. For example, if I had the series:
```
Foo: /opt/series/Foo/
Bar: /mnt/toaster/videos/tv/Bar/
```
then the algorithm would determine the disk space locations as:
```
Foo -> /
Bar -> /mnt/toaster/videos/
```
because they are the longest matching paths of the series that match a mount.

```
# Psuedo-code
system_disk_space_list = []
for s in series:
    p = s.path
    while p not in mounts:
        p = dirname(p)
    system_disk_space_list.append(p)
system_disk_space_list = distinct(system_disk_space_list)
```

Sample code:
```c#
using System;
using System.IO;

namespace Examples
{
    public class FreeSpace
    {
        public static void Main(string[] args)
        {
            foreach (DriveInfo drive in DriveInfo.GetDrives())
            {
                Console.WriteLine ("name: {0} free: {1}",
                                   drive.Name,
                                   drive.AvailableFreeSpace);
            }
        }
    }
}
```

[1] Note I'm not familiar with `Sonarr`'s structure, so this may be the wrong place.

**Comment by markus101** [comment]
We do find the longest matching path:

https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Common/Disk/DiskProviderBase.cs#L396-L412

What are the drive types of those drives (`drive.DriveType` in your example code)? Sonarr expects it to be `Fixed`, `Network` or `Removable`, other types are ignored.

**Comment by doktorstick** [comment]
It appears they show up as "Unknown":
```
$ mono free.exe
name: / free: 299566891008 type: Fixed
name: /dev free: 0 type: Ram
name: /net free: 0 type: Network
name: /home free: 0 type: Network
name: /mnt/toaster free: 0 type: Network
name: /mnt/toaster/videos free: 2201541591040 type: Unknown
name: /mnt/toaster/music free: 2201541591040 type: Unknown
```

**Comment by markus101** [comment]
There may not be a series there (its used for a variety of things), 

Could you also post the contents of two files: `/proc/mounts` and `/proc/filesystems`? We also use those to locate other paths that DriveInfo fails to get us (or get us in the way we want).

**Comment by doktorstick** [comment]
Mac OS X doesn't have `procfs`.

**Comment by markus101** [comment]
Well that won't help us. Guess the easy answer is we include `Unknown`, but neither @Taloth or I is fond of that idea, to many unknowns (pun unintended), it may be the direction we go, but we need to think on it some more.

**Comment by doktorstick** [comment]
Here's some more information for the mounts that you may be able to use to determine if it's a Real Mount(TM).
```
$ mono free.exe
name: /
	free: 299517120512
	type: Fixed
	format: hfs
	ready: True
name: /dev
	free: 0
	type: Ram
	format: devfs
	ready: True
name: /net
	free: 0
	type: Network
	format: autofs
	ready: True
name: /home
	free: 0
	type: Network
	format: autofs
	ready: True
name: /mnt/toaster
	free: 0
	type: Network
	format: autofs
	ready: True
name: /mnt/toaster/videos
	free: 2201494503424
	type: Unknown
	format: afpfs
	ready: True
name: /mnt/toaster/music
	free: 2201494503424
	type: Unknown
	format: afpfs
	ready: True
```

**Comment by markus101** [comment]
That definitely helps, I opened a PR so Taloth can take a quick look.

**Comment by doktorstick** [comment]
To put a bow on it, I mounted it through Mac's `Finder` as AFP and SMB to see if a) it `Unknown` was `autofs` specific, and b) if it was limited to `afpfs`. It appears it's strictly `afpfs`.
```
name: /Volumes/videos
	free: 2201425260544
	type: Unknown
	format: afpfs
	ready: True
name: /Volumes/videos-1
	free: 2201425260544
	type: Network
	format: smbfs
	ready: True
```
