### ISSUE TITLE
Add Series: Default properties that are NOT NULL in the database

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1403]
For adding a series we have a limited number of properties that are required, but we have a larger number of fields that are required to successfully save it to the data base (`NOT NULL` DB columns), we should default anything we expect to not be null, but don't care if its been set or remove the `NOT NULL` restriction in the DB (and make sure they are being deserialized properly).

We can default it in the API resource, the model or directly in the DB.

**Comment by markus101** [comment]
Better yet we should fetch the details from skyhook before adding so even less information is required (title and title slug could be excluded).

**Comment by supavog** [comment]
The issue I'm having with PlexRequests references the Series.Images field.  Is there a version of Sonarr that I should roll back to that resolves it for now until a fix can be released?

**Comment by tidusjar** [comment]
@supavog Which version of Plex Requests? There is a workaround in place in the .NET version.

**Comment by supavog** [comment]
Sorry for the late response.  Plexrequests version is 1.15.0.

**Comment by tidusjar** [comment]
Meteor version or the .net version?

**Comment by supavog** [comment]
.NET 4.6.1
Meteor 1.2.1

**Comment by AlienXAXS** [comment]
This is happening with me when i attempt to load a tv show into the API.

Any news on a fix?!
