### ISSUE TITLE
Cannot add series as unmonitored using the API

### ISSUE THREAD

**Issue by tidusjar** [Sonarr/Sonarr#1404]
Hi,

I am attempting to add a series as unmonitoed.

Endpoint: /api/Series
Method: POST
Here is the payload being used:

```
{  
   "addOptions":null,
   "title":"Mad Men",
   "seasons":[ ],
   "rootFolderPath":"D:\\Media\\TV Shows",
   "qualityProfileId":1,
   "seasonFolder":true,
   "monitored":false,
   "tvdbId":80337,
   "tvRageId":0,
   "cleanTitle":null,
   "imdbId":null,
   "titleSlug":"Mad Men",
   "id":0
}
```

As you can see we are specifying the `monitored` bool as `false`.
But it's still being added in Sonarr as monitored.

I have also tried setting the `addOptions` properties but still cannot get the series to be unmonitored.

Any ideas?

**Comment by markus101** [comment]
Awesome, we're hardcoding it because we never bother to change it on the client. I'll get a fix for that into develop.

**Comment by tidusjar** [comment]
Oh damn! I was going crazy thinking what am I doing wrong?!?   

Ah ok. Got any suggestions for workarounds until the fix goes live? This means I can't release my new feature :cry:

**Comment by markus101** [comment]
Only thing that could really be done is to unmonitor it after adding it.

**Comment by tidusjar** [comment]
Thanks for the quick fix.

**Comment by tidusjar** [comment]
@markus101 Do you have the next Sonarr release planned?

**Comment by markus101** [comment]
We have some pretty big API changes in develop right now that we're waiting for feedback on so it may be a while. We don't tend to plan them beyond a few days in advance. The develop release is out now though. Even if we pushed this to master I wouldn't expect everyone to update, still ~10% of the users on master are running the previous release and some people are still running older releases than that.
