### ISSUE TITLE
Sonarr search for the wrong season

### ISSUE THREAD

**Issue by whitecollar17** [Sonarr/Sonarr#1405]
If i search for a season for the tv show Dexter's Laboratory Sonarr go's searching for the wrong season.

See image:
![image](https://cloud.githubusercontent.com/assets/2944704/17192406/9a1e2722-544e-11e6-9170-4ea3ac2c551c.png)

![image](https://cloud.githubusercontent.com/assets/2944704/17192441/c938ae7e-544e-11e6-9dd8-44652ee6e37f.png)

Logs says also "NzbSearchService	Searching 5 indexers for [Dexter's Laboratory : S00]"

**Comment by markus101** [comment]
That's because the episodes are remapped on thexem.de: http://thexem.de/xem/show/237 If you hover over the episode number you'll see the mapping that is taking place.
