### ISSUE TITLE
Resolution detection for manual import

### ISSUE THREAD

**Issue by IchabodFletchman** [Sonarr/Sonarr#1408]
I would like Sonarr to detect the resolution of an episode when it has been imported without Sonarr knowing the source and resolution from the file name.

Eg. Sonarr detects any mkv file as 720p, even if it is 1080p.
If Sonarr checked the codec info, it could see that it is 1080p and import it correctly.

I can't see anyway of detecting the source, but at least the resolution would be correct.
I had an issue where I imported my existing library and I had some shows that I ripped from blu-ray in 1080p, but Sonarr imported them all as 720p hdtv and began to re-download them as what it thought was a higher quality; it even replaced my blu-ray rips with hdtv.

**Comment by ThatWhiteMonster** [comment]
If there's 1080p in the filename, Sonarr assumes it's 1080p. Otherwise it's 720p. Annoying, I know ;) .

**Comment by markus101** [comment]
There is a GHI for this already: https://github.com/Sonarr/Sonarr/issues/448
