### ISSUE TITLE
File modification date for existing episodes

### ISSUE THREAD

**Issue by IchabodFletchman** [Sonarr/Sonarr#1409]
Sonarr needs the ability to change the file modification date to aired date (if enabled in settings) for existing episodes. New imported episodes all have the correct modification dates (date aired), but when imported the tv show collection into Sonarr for the first time, all episodes don't have the modification date changed.
I am not sure if there will be a slow down during a refresh as Sonarr would be checking all episodes and cross referencing them to the air dates. If that's the case, then maybe only do it when refreshing an individual show or a toggle in settings that says 'Correct file dates on next refresh', that when turned on, it will correct all dates, then turn back off... Just a few suggestions.

**Comment by markus101** [comment]
Sonarr already does this when the series is rescanned (every 12 hours), when the setting is set to anything other than `None`.
