### ISSUE TITLE
RARBG Indexer No Longer Works

### ISSUE THREAD

**Issue by a92nj2efnfsa** [Sonarr/Sonarr#1410]
The built in rarbg indexer stopped working recently. It now provides an error saying you need to complete a captcha before getting the token.

Unable to connect to indexer: HTTP request failed: [403:Forbidden] [GET] at [https://torrentapi.org/pubapi_v2.php?get_token=get_token]

HTTP Error - Res: [GET] https://torrentapi.org/pubapi_v2.php?get_token=get_token: 403.Forbidden
```
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | CloudFlare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>
<!--[if lte IE 9]><script type="text/javascript" src="/cdn-cgi/scripts/jquery.min.js"></script><![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>


</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="challenge_headline">One more step</h1>
        <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> torrentapi.org</h2>
      </div><!-- /.header -->

      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form" id="challenge-form" action="/cdn-cgi/l/chk_captcha" method="get">
  <script type="text/javascript" src="/cdn-cgi/scripts/cf.challenge.js" data-type="normal"  data-ray="2cb9b9570e8e21d4" async data-sitekey="6LfOYgoTAAAAAInWDVTLSc8Yibqp-c9DaLimzNGM" data-stoken="MmUc1xQXlXmRErXy49B2HyFLHrFxCYynHSmYnMAlpdVRAUDCW78T9riw52yTTN6_-Hb4dD0grnSf_1aRQrDryop5ExY5_k_8qkvhwTiTLIg"></script>
  <div class="g-recaptcha"></div>
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
    <div><div style="width: 302px">
      <div>
        <iframe src="https://www.google.com/recaptcha/api/fallback?k=6LfOYgoTAAAAAInWDVTLSc8Yibqp-c9DaLimzNGM&stoken=MmUc1xQXlXmRErXy49B2HyFLHrFxCYynHSmYnMAlpdVRAUDCW78T9riw52yTTN6_-Hb4dD0grnSf_1aRQrDryop5ExY5_k_8qkvhwTiTLIg" frameborder="0" scrolling="no" style="width: 302px; height:422px; border-style: none;"></iframe>
      </div>
      <div style="width: 300px; border-style: none; bottom: 12px; left: 25px; margin: 0px; padding: 0px; right: 25px; background: #f9f9f9; border: 1px solid #c1c1c1; border-radius: 3px;">
        <textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid #c1c1c1; margin: 10px 25px; padding: 0px; resize: none;"></textarea>
        <input type="submit" value="Submit"></input>
      </div>
    </div></div>
  </noscript>
</form>

              </div>
            </div>

            <div class="cf-column">
              <div class="cf-screenshot-container">
              
                <span class="cf-no-screenshot"></span>
              
              </div>
            </div>
          </div><!-- /.columns -->
        </div>
      </div><!-- /.captcha-container -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>

            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>

            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
          </div>
        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">CloudFlare Ray ID: <strong>2cb9b9570e8e21d4</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 107.191.36.*</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">CloudFlare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>

</body>
</html>
```

**Comment by ThatWhiteMonster** [comment]
You must be generating serious traffic to it. It still works for me.

**Comment by a92nj2efnfsa** [comment]
Serious traffic to an RSS feed? I get maybe 3 shows a day from it. Also, I've changed IPs and same issue. Glad you're not having the issue but several people are. There's even an issue about this on the sonarr reddit page.

**Comment by ThatWhiteMonster** [comment]
Several? I've only found two.

**Comment by a92nj2efnfsa** [comment]
Do you have a solution, or are you just complaining someone is having an issue that you aren't?

**Comment by markus101** [comment]
A 403 Forbidden response means you're blocked by RARBG, given its asking you to fill in a CloudFlare captcha its likely because of the proxy/VPN you're using. Opening the same URL in your browser may allow you to fill in the captcha and have it work in Sonarr, otherwise there is nothing we can do.

**Comment by markus101** [comment]
(Re-opening for visibility)

**Comment by markus101** [comment]
If you're blocked RARBG is looking for IP ranges to see why they are blocked to see what they can do to help: https://github.com/rarbg/torrentapi/issues/11

**Comment by a92nj2efnfsa** [comment]
thanks markus, I added the list of IPs i've gotten to that ticket you referenced.

**Comment by indiandennis** [comment]
This issue mainly seems to be for Private Internet Access VPN users. I had this issue, switched to another IP and got the Cloudflare Captcha and then switched back and everything seems to work fine. Directly accessing the website still gives me 403 but the api works fine.

**Comment by michaelgoodwin** [comment]
I was just having issues with this, it's very likely my fix was just coincidence but after multiple failed requests and tests I looked at the url https://torrentapi.org/pubapi_v2.php?get_token=get_token on my machine to find that i could get a token just fine.

SSH'd into my server:
`curl https://torrentapi.org/pubapi_v2.php?get_token=get_token`
Request went through fine; I got a token, and now everything works.
How often is a token requested and how long until they expire?

**Comment by anonaut** [comment]
https://torrentapi.org/apidocs_v2.txt
`Tokens automaticly expire in 15 minutes.`

**Comment by Quaternions-FTW** [comment]
I was getting the same error using sonarr because I am connected to the a PIA VPN server which is connected with Choopa, LLC. I solved this by going to 

Settings>General>Proxy Settings
and inputting the following


**Use Proxy >** YES
**Proxy Type >** Socks5 (This option supports Tor)
**Hostname >** proxy-nl.privateinternetaccess.com
**Port >** 1080
**Username >** x#######
**Password >** ################
**Addresses for the proxy to ignore >**
**Bypass Proxy for Local Addresses >** YES

I left "Addresses for proxy to ignore" blank, but you could add thetvdb.com or others if you wish for sonarr to not use the proxy.  

If using PIA, you should use the "SOCKS5" username that is found on your PIA profile page. It will be the same as your normal PIA username, except it will begin with "x" instead of "p". Also the "SOCKS5" username will have a different password than your normal password. This can also be found in your PIA profile page.

**Comment by Quaternions-FTW** [comment]
Not sure if it is related or coincidental, but in my sonarr logs, I am now receiving this html output:


# Error 502 Ray ID: ################ • 2016-08-10 03:47:18 UTC
## Bad gateway
You
### Browser
Working
Amsterdam
### CloudFlare
Working
torrentapi.org
### Host
Error
## What happened?

The web server reported a bad gateway error.
## What can I do?

Please try again in a few minutes.

CloudFlare Ray ID: ################ • Your IP: 109.201.138.227 • Performance & security by CloudFlare

**Comment by odaysawaqed** [comment]
Getting this error as well
Error 502 Ray ID: 2d010c732b8a473a • 2016-08-10 05:29:18 UTC
Bad gateway

I tried to make a request from both my private ip and my VPN SP's ip
Both returned the same error!

According to the logs, this started happening on 8/9/16 at 5pm EST time

**Comment by Taloth** [comment]
Please guys, stop cross-posting comments on two issues.
Bad Gateway is just the site being unavailable as that Cloudflare page explains, it happens, just try again later.
