### ISSUE TITLE
Series sort on series list and editor share the same collection/key in local storage

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1411]
Changing the sort on the series list affects the sort order on the series editor and vice versa, which causes things to sort in weird ways that is effectively hidden from the user. The fact that the collection is the same and the key in local storage are the same contribute to this issue.

**Comment by waxxxd** [comment]
@markus101 Are you saying that the Series List and the Series Editor should have separate sorting? 

i.e. Not all the sorting option are in the Editor, e.g. thus if you sort by season in the List then the Editor sorting in unintuitive.

So to resolve the sorting should be done via a filter that's applied differently per page.

**Comment by markus101** [comment]
Yes, exactly.

**Comment by markus101** [comment]
This will be resolved in the v3 UI.
