### ISSUE TITLE
Not detecting specials in folder

### ISSUE THREAD

**Issue by CyberMew** [Sonarr/Sonarr#1412]
Had a folder "Battlestar.Galactica.Miniseries.2003.**S00E01**.Part.1.720p.Hddvd.x264-SINNERS" with a .mkv file named "Battlestar.Galactica.Miniseries.2003.Part.1.720p.HDDVD.x264-SiNNERS.mkv"

Plex was able to detect this file, but Sonarr couldn't. Feature request, bug or wontfix?

**Comment by markus101** [comment]
Sonarr relies on the file name of the file, it should also contain 1S00E01` to be identified properly. `Part.1` could actually be detected as `S01E01` in some cases.
