### ISSUE TITLE
RSS Sync task freezes

### ISSUE THREAD

**Issue by fent** [Sonarr/Sonarr#1417]
Hello, I'm having trouble with Sonarr. It'll work fine for a few days, but every now and then it'll stop checking for new releases because it freezes while executing the RSS sync.

![screen shot 2016-08-03 at 12 05 13 am](https://cloud.githubusercontent.com/assets/933490/17453829/14c19e88-5b51-11e6-93b3-997121a20657.png)

![screen shot 2016-08-05 at 9 10 59 pm](https://cloud.githubusercontent.com/assets/933490/17453831/2535d2f2-5b51-11e6-9873-e52bd848c23c.png)

From the logs:
```
16-8-3 03:51:59.1|Info|RssSyncService|Starting RSS Sync
16-8-3 03:52:00.2|Info|DownloadDecisionMaker|Processing 100 releases
```

I'm also not sure how to stop the task other than by force killing the Sonarr process. Hitting restart via the Sonarr UI won't work either, it'll stop Sonarr, but it won't start back up. And if I check the list of processes, it's still there.

Let me know if I can provide more detailed logs from somewhere.

**Comment by markus101** [comment]
Please open a thread on the forums with the information requested when opening it.
