### ISSUE TITLE
Sonarr Moves to Next File Before Custom Script Completes

### ISSUE THREAD

**Issue by enz1ey** [Sonarr/Sonarr#1418]
When multiple downloads are queued in SabNZBD and then passed to Sonarr, I have a custom script set in Sonarr to run after renaming/moving. The custom script entails uploading the Sonarr target directory to an online storage provider. The script is invoked properly by Sonarr, however it moves on to the next file from the SabNZBD queue and begins moving the next file into the target directory while the previous file is still uploading via the custom script, leading to partial uploads and multiple instances of the script. 

I haven't found a way to either delay the import of the next file in the queue or have the custom script be included as part of the whole Sonarr process. For instance, when CouchPotato invokes a script after rename/move, SabNZBD won't begin post processing the next file in the queue until the custom script is complete, as it sees the custom script action as a part of the whole CP process rather than the CP process stopping after the rename/move and calling the script separately.

**Comment by markus101** [comment]
Sonarr waits for the script it called to exit before sending other notifications, running other scripts or importing any other files. If you script calls another application and doesn't wait for it to exist before exiting then Sonarr will consider it executed and move on to the next operation.

Here are the logs from running an import on multiple files:

```
16-8-13 12:35:20.9|Debug|CustomScript|Executing external script: C:\Test\CustomScriptDelay.exe
16-8-13 12:35:26.6|Debug|CustomScriptDelay.exe|Starting C:\Test\CustomScriptDelay.exe 
16-8-13 12:35:26.6|Debug|CustomScriptDelay.exe|Started at: 2016-08-13T12:35:26
16-8-13 12:35:26.6|Debug|CustomScriptDelay.exe|Current Process ID: 10172
16-8-13 12:35:26.6|Debug|CustomScriptDelay.exe|Sleeping
16-8-13 12:35:36.6|Debug|CustomScriptDelay.exe|Exit
16-8-13 12:35:39.0|Debug|CustomScript|Executed external script: C:\Test\CustomScriptDelay.exe - Status: 0
16-8-13 12:35:39.0|Debug|CustomScript|Script Output: 
8/13/2016 7:35:26 PM - Standard - Started at: 2016-08-13T12:35:26
8/13/2016 7:35:26 PM - Standard - Current Process ID: 10172
8/13/2016 7:35:26 PM - Standard - Sleeping
8/13/2016 7:35:36 PM - Standard - Exiting

16-8-13 12:35:39.6|Debug|CustomScript|Executing external script: C:\Test\CustomScriptDelay.exe
16-8-13 12:35:40.6|Debug|CustomScriptDelay.exe|Starting C:\Test\CustomScriptDelay.exe 
16-8-13 12:35:40.6|Debug|CustomScriptDelay.exe|Started at: 2016-08-13T12:35:40
16-8-13 12:35:40.6|Debug|CustomScriptDelay.exe|Current Process ID: 14536
16-8-13 12:35:40.7|Debug|CustomScriptDelay.exe|Sleeping
16-8-13 12:35:50.6|Debug|CustomScriptDelay.exe|Exiting
16-8-13 12:35:52.9|Debug|CustomScript|Executed external script: C:\Test\CustomScriptDelay.exe - Status: 0
16-8-13 12:35:53.0|Debug|CustomScript|Script Output: 
8/13/2016 7:35:40 PM - Standard - Started at: 2016-08-13T12:35:40
8/13/2016 7:35:40 PM - Standard - Current Process ID: 14536
8/13/2016 7:35:40 PM - Standard - Sleeping
8/13/2016 7:35:50 PM - Standard - Exiting
```

The script sleeps for 10 seconds to simulate doing something, but otherwise it's functional. If you're still having issues after verify your script doesn't return early, please open a thread on the [forums](https://forums.sonarr.tv/) with the relevant debug logs and we can take a look.
