### ISSUE TITLE
[req] Would it be possible to add support for www.eltrecetv.com.ar ?

### ISSUE THREAD

**Issue by ciroiriarte** [Sonarr/Sonarr#1419]
Would it be possible to add support for this site?:

www.eltrecetv.com.ar/capitulos-completos

That channels publishes in UHD format their series, would be awesome to be able to include support for it in Sonarr. It would be direct HTTP downloads, no Torrents involved.

**Comment by markus101** [comment]
We have no plans to support other protocols at this time.
