### ISSUE TITLE
weird import error

### ISSUE THREAD

**Issue by seanvree** [Sonarr/Sonarr#1420]
I've been getting this error with one particular episode:

Import failed, path does not exist or is not accessible by Sonarr: e:\media\plexdownloads\TV\Mr.Robot.S02E00.Hacking.Robot.101.720p.HDTV.x264-BAT

The episode is unmonitored, but I keep getting this error.

The file is NOT present in that directory. Why does it keep trying to import it?

Debug logs:

16-8-8 12:32:25.5|Debug|Parser|Parsing string 'Mr.Robot.S02E00.Hacking.Robot.101.720p.HDTV.x264-BATV'
16-8-8 12:32:25.5|Debug|Parser|Episode Parsed. Mr Robot - S02E00 
16-8-8 12:32:25.5|Debug|Parser|Language parsed: English
16-8-8 12:32:25.5|Debug|QualityParser|Trying to parse quality for Mr.Robot.S02E00.Hacking.Robot.101.720p.HDTV.x264-BATV
16-8-8 12:32:25.5|Debug|Parser|Quality parsed: HDTV-720p v1
16-8-8 12:32:25.5|Debug|Parser|Release Group parsed: BATV
16-8-8 12:32:25.5|Debug|ParsingService|Unable to find Mr Robot - S02E00 HDTV-720p v1
16-8-8 12:32:25.5|Debug|Parser|Parsing string 'Mr.Robot.S02E00.Hacking.Robot.101.720p.HDTV.x264-BATV'
16-8-8 12:32:25.5|Debug|Parser|Episode Parsed. Mr Robot - S02E00 
16-8-8 12:32:25.5|Debug|Parser|Language parsed: English
16-8-8 12:32:25.5|Debug|QualityParser|Trying to parse quality for Mr.Robot.S02E00.Hacking.Robot.101.720p.HDTV.x264-BATV
16-8-8 12:32:25.5|Debug|Parser|Quality parsed: HDTV-720p v1
16-8-8 12:32:25.5|Debug|Parser|Release Group parsed: BATV
16-8-8 12:32:25.5|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: e:\media\plexdownloads\TV\Mr.Robot.S02E00.Hacking.Robot.101.720p.HDTV.x264-BATV
16-8-8 12:32:26.7|Debug|Api|[GET] /api/queuesort_by=timeleft&order=asc: 200.OK (0 ms)
16-8-8 12:33:55.5|Debug|SabnzbdProxy|Url: http://localhost:38080/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
16-8-8 12:33:55.5|Debug|SabnzbdProxy|Url: http://localhost:38080/api?mode=history&start=0&limit=30&category=tv&apikey=(removed)&output=json
16-8-8 12:33:55.5|Debug|Parser|Parsing string 'warp!x=k35aJ3eYRIZihiJ8hzG0SKoaRdGIAzhL4z68AvZDRvh0hnpYAfgt4cMaGVQCAchK4V6TeVbxNc0B4C9feC50AKeiGT9Be1p8lK6KkcaTeTMINcAKJCaIeTh9e'
16-8-8 12:33:55.5|Debug|Parser|Unable to parse warp!x=k35aJ3eYRIZihiJ8hzG0SKoaRdGIAzhL4z68AvZDRvh0hnpYAfgt4cMaGVQCAchK4V6TeVbxNc0B4C9feC50AKeiGT9Be1p8lK6KkcaTeTMINcAKJCaIeTh9e
16-8-8 12:33:55.5|Debug|Parser|Parsing string 'Mr.Robot.S02E00.Hacking.Robot.101.720p.HDTV.x264-BATV'
16-8-8 12:33:55.5|Debug|Parser|Episode Parsed. Mr Robot - S02E00 
16-8-8 12:33:55.5|Debug|Parser|Language parsed: English
16-8-8 12:33:55.5|Debug|QualityParser|Trying to parse quality for Mr.Robot.S02E00.Hacking.Robot.101.720p.HDTV.x264-BATV
16-8-8 12:33:55.5|Debug|Parser|Quality parsed: HDTV-720p v1
16-8-8 12:33:55.5|Debug|Parser|Release Group parsed: BATV
16-8-8 12:33:55.5|Debug|ParsingService|Unable to find Mr Robot - S02E00 HDTV-720p v1
16-8-8 12:33:55.5|Debug|Parser|Parsing string 'Mr.Robot.S02E00.Hacking.Robot.101.720p.HDTV.x264-BATV'
16-8-8 12:33:55.5|Debug|Parser|Episode Parsed. Mr Robot - S02E00 
16-8-8 12:33:55.5|Debug|Parser|Language parsed: English
16-8-8 12:33:55.5|Debug|QualityParser|Trying to parse quality for Mr.Robot.S02E00.Hacking.Robot.101.720p.HDTV.x264-BATV
16-8-8 12:33:55.5|Debug|Parser|Quality parsed: HDTV-720p v1
16-8-8 12:33:55.5|Debug|Parser|Release Group parsed: BATV
16-8-8 12:33:55.5|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: e:\media\plexdownloads\TV\Mr.Robot.S02E00.Hacking.Robot.101.720p.HDTV.x264-BATV
16-8-8 12:33:55.6|Debug|Api|[GET] /api/queuesort_by=timeleft&order=asc: 200.OK (0 ms)
16-8-8 12:35:25.5|Debug|SabnzbdProxy|Url: http://localhost:38080/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
16-8-8 12:35:25.5|Debug|SabnzbdProxy|Url: http://localhost:38080/api?mode=history&start=0&limit=30&category=tv&apikey=(removed)&output=json
16-8-8 12:35:25.5|Debug|Parser|Parsing string 'warp!x=k35aJ3eYRIZihiJ8hzG0SKoaRdGIAzhL4z68AvZDRvh0hnpYAfgt4cMaGVQCAchK4V6TeVbxNc0B4C9feC50AKeiGT9Be1p8lK6KkcaTeTMINcAKJCaIeTh9e'
16-8-8 12:35:25.5|Debug|Parser|Unable to parse warp!x=k35aJ3eYRIZihiJ8hzG0SKoaRdGIAzhL4z68AvZDRvh0hnpYAfgt4cMaGVQCAchK4V6TeVbxNc0B4C9feC50AKeiGT9Be1p8lK6KkcaTeTMINcAKJCaIeTh9e
16-8-8 12:35:25.6|Debug|Parser|Parsing string 'Mr.Robot.S02E00.Hacking.Robot.101.720p.HDTV.x264-BATV'

Thanks

**Comment by markus101** [comment]
> The file is NOT present in that directory. Why does it keep trying to import it?

Because its being told its finished by your download client and Sonarr didn't import it, you can either remove it from the history of your download client, change the label (for torrents), change the category Sonarr uses in your download client or clear the history.

PS as this is more support related it should opened on our support forums.
