### ISSUE TITLE
Run ntp query on startup

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#1422]
Running an ntp query against a couple of time server on startup should help us detect if the system time is sensible.
This is mostly the case for raspberry, which doesn't have a battery backed RTC.
If the time isn't within a certain limit then we should just error out, instructing the user to have an ntp sync in their startup and have the services depend on it. (Yes, On Rasp ppl should bring network online, then an ntp burst/ntpdate and not start other services until that's ok.)

Consequences of running Sonarr with 2030+ dates is that all the scheduled tasks go on the fritz and can't be fixed without manually updating the database.

**Comment by markus101** [comment]
> Consequences of running Sonarr with 2030+ dates is that all the scheduled tasks go on the fritz and can't be fixed without manually updating the database.

On start Sonarr will fix the last run time for scheduled tasks to be the current time if they are in the future. IIRC the only remaining issue is indexer health issues will cause those indexers to be disabled until 2030.

**Comment by thezoggy** [comment]
~ http://raspberrypi.stackexchange.com/questions/8231/how-to-force-ntpd-to-update-date-time-after-boot
