### ISSUE TITLE
Releases in download client that can't parse the series title are not shown in queue

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1426]
If the item has a matching item in history (Sonarr grabbed it) then we should associate it with that series and episode(s) and flag it for manual import. Right now if the name is different than the source name from the indexer we might import it, but if neither can be parsed and parsing it as a special fails its never linked to the proper series and episode(s).

This ties a bit into the unknown series releases shown in queue, but isn't as involved.

Example: This release grabbed by Sonarr disappears: `[ The Last Ship S03E09 Paradise 720p WEB-DL DD5.1 H.264-Oosh ]`.

Ref: https://forums.sonarr.tv/t/cant-find-brackets/11715

**Comment by Taloth** [comment]
Markus: https://github.com/Sonarr/Sonarr/pull/681

**Comment by markus101** [comment]
@Taloth thanks for linking, I knew there was a PR, just forgot to actually link it. FWIW I don't think this should be handled via that PR, since we already know the series, Sonarr is just failing to match it properly.

**Comment by markus101** [comment]
Done in the v3 work. Ignoring my previous concern since that work does cover that case.
