### ISSUE TITLE
Completed Download Handling + TransmissionQT

### ISSUE THREAD

**Issue by RedwinX** [Sonarr/Sonarr#1429]
Hi,

the Completed Download Handling doesn't work with TransmissionQT (Windows x64 v2.84 Build 14386).
When the download are completed, Sonarr cannot remove the torrent and files. 
Any idea or suggestions ?

Regards,

**Comment by RedwinX** [comment]
Sonarr rename correctly the file and copy it to the correct destination. The option "Remove" in Completed Download Handling is already active. When the download has finised, the torrent is still in transmission list, so the first file is still there, and so duplicate...

**Comment by markus101** [comment]
This is explained in the FAQ: https://github.com/Sonarr/Sonarr/wiki/FAQ#seeding-torrents-arent-deleted-automatically
