### ISSUE TITLE
Let's Encrypt Certificate request and renewal

### ISSUE THREAD

**Issue by 7gartner** [Sonarr/Sonarr#1432]
I'd like to see support added to use letsencrypt.org certs with automatic renewal built into sonarr.

**Comment by markus101** [comment]
This is something we've discussed at a high level, though might not be something we intend to do in the near future.

Dev related: Nowin has middleware and an example on how to do this with acme.net: https://github.com/Bobris/Nowin We'd need to find a way to do it with Kestrel and make sure renewals are scheduled.

**Comment by deanishe** [comment]
>  LE may require the server to be hosted on port 80/433

It does currently. In any case, it'll have to be a port <1024 for obvious security reasons, which presumably poses the same problems in many cases.

**Comment by bluefrogdotca** [comment]
A possible workaround for now is you could use nginx and proxy_pass port 8989. Then configure nginx to route the ".well-known" directory so the LE configure tool will be able to autorenew. Change nginx's SSL to use LE's certificate directory.

**Comment by lattedesu** [comment]
I also use nginx + proxy_pass and install let's encrypt ssl to nginx (sub)domain. Works as a treat.

**Comment by markus101** [comment]
Not something we're planning to do at this time, there are plenty of command line tools to take care of this already (that support DNS entries instead of checking a live webserver).
