### ISSUE TITLE
wishlist: Support for snatching partial season packs

### ISSUE THREAD

**Issue by TouchMyBox** [Sonarr/Sonarr#1435]
Hi, Sonarr seems to ignore partial season packs for shows which put out partial season releases. The formatting of the names are Showname.SXX.PartX.Resolution.Source.Codec Not a huge deal, but it would be nice for the small amount of shows that do this.

**Comment by markus101** [comment]
We don't have plans to support partial packs because there is no easy way for Sonarr to determine which episodes are in that pack, which is the same limitation that would prevent grabbing of disk based releases as there isn't a way to determine which episodes are on which disk easily.
