### ISSUE TITLE
Add setting for calendar/ical feed to include all shows, no just monitored shows

### ISSUE THREAD

**Issue by Alives** [Sonarr/Sonarr#1442]
The Sonarr calendar page lets users toggle All vs. Monitored to display non-monitored shows, but the ical feed is limited to monitored only shows.  It would be nice to have a setting to allow ical feeds to include all shows as well.

**Comment by markus101** [comment]
Include `&unmonitored=true` in the URL to include unmonitored episodes.

**Comment by Taloth** [comment]
Add UI flag, related to the request to add tag support to the feed.
