### ISSUE TITLE
API: /wanted/missing : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by KrunchMuffin** [Sonarr/Sonarr#1452]
I am writing an app that uses the API and I am trying to invoke the `/wanted/missing` endpoint and I get the following message.

Version 2.0.0.4312 on Develop on Win10

`{
  "message": "Object reference not set to an instance of an object.",
  "description": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at NzbDrone.Core.Datastore.Extensions.PagingSpecExtensions.CreateExpression[TModel](String propertyName) in M:\\BuildAgent\\work\\6c3239faf2b92630\\src\\NzbDrone.Core\\Datastore\\Extensions\\PagingSpecExtensions.cs:line 32\r\n   at NzbDrone.Core.Tv.EpisodeRepository.GetMissingEpisodesQuery(PagingSpec`1 pagingSpec, DateTime currentTime, Int32 startingSeasonNumber) in M:\\BuildAgent\\work\\6c3239faf2b92630\\src\\NzbDrone.Core\\Tv\\EpisodeRepository.cs:line 199\r\n   at NzbDrone.Core.Tv.EpisodeRepository.EpisodesWithoutFiles(PagingSpec`1 pagingSpec, Boolean includeSpecials) in M:\\BuildAgent\\work\\6c3239faf2b92630\\src\\NzbDrone.Core\\Tv\\EpisodeRepository.cs:line 112\r\n   at NzbDrone.Core.Tv.EpisodeService.EpisodesWithoutFiles(PagingSpec`1 pagingSpec) in M:\\BuildAgent\\work\\6c3239faf2b92630\\src\\NzbDrone.Core\\Tv\\EpisodeService.cs:line 139\r\n   at NzbDrone.Api.NzbDroneRestModule`1.ApplyToPage[TModel](Func`2 function, PagingSpec`1 pagingSpec, Converter`2 mapper) in M:\\BuildAgent\\work\\6c3239faf2b92630\\src\\NzbDrone.Api\\NzbDroneRestModule.cs:line 29\r\n   at NzbDrone.Api.Wanted.MissingModule.GetMissingEpisodes(PagingResource`1 pagingResource) in M:\\BuildAgent\\work\\6c3239faf2b92630\\src\\NzbDrone.Api\\Wanted\\MissingModule.cs:line 39\r\n   at NzbDrone.Api.REST.RestModule`1.<set_GetResourcePaged>b__35_0(Object options) in M:\\BuildAgent\\work\\6c3239faf2b92630\\src\\NzbDrone.Api\\REST\\RestModule.cs:line 126\r\n   at CallSite.Target(Closure , CallSite , Func`2 , Object )\r\n   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)"
}`

**Comment by KrunchMuffin** [comment]
I think I know what it is, wasn't sending the required params. Probably would be better to get an appropriate message back tho.

**Comment by Taloth** [comment]
Yes, it should revert to some default instead of requiring the parameter.
`wanted/missing?sortKey=airDateUtc&sortDir=desc`

**Comment by KrunchMuffin** [comment]
I updated the api docs to reflect that only` sortKey` is required

**Comment by KrunchMuffin** [comment]
Same issue with `history`

**Comment by KrunchMuffin** [comment]
cool. thanks.
