### ISSUE TITLE
Enabled Indexers Do Not Have RSS Sync Enabled

### ISSUE THREAD

**Issue by delphiactual** [Sonarr/Sonarr#1454]
Sonarr: `2.0.0.4322`
Linux: `4.4.0-36-generic #55-Ubuntu` 
Mono: `4.4.2 `

Had to delete all indexers and just re-add them to get past this error

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
Running the `Check Health` will immediately re-verify the health as its not re-calculated constantly. If all RSS enabled indexers are disabled for some reason (failed responses, API usage) or none had RSS enabled you would see this message.
