### ISSUE TITLE
Plex Media Server: Refresh specific library

### ISSUE THREAD

**Issue by Deathspike** [Sonarr/Sonarr#1460]
When using Plex Media Server connection, Sonarr signals Plex Media Server to update every library. When you have a large number of libraries, the amount of scanning can become an incredible load on the machine. For most users with multiple libraries, the specification of one library to refresh should be sufficient. I therefore propose an advanced field to target which library to refresh, rather than everything (e.g. refresh only the 'TV Series' library).

If you happen to manage multiple series types with multiple libraries, e.g. a library for regular TV series and a library for anime, then you *want* the default behavior of refreshing everything, and you can keep using the default as it is. For those who may organize more media, you can narrow it if it suits your preferences (e.g. I do have 500+ anime series in a different library and scanning them whenever a TV series episode is added is a gigantic waste of resources, since Sonarr doesn't manage my anime).

**Comment by markus101** [comment]
Sonarr looks for the library with the series in it (relies on TheTVDB ID) and partial updates being enabled in PMS, if a matching show is not found or partial updates are disabled Sonarr refreshes all the show libraries. We don't plan to add an option to restrict refreshes to a specific library at this time.
