### ISSUE TITLE
Passwords not encrypted at rest

### ISSUE THREAD

**Issue by darknessgp** [Sonarr/Sonarr#1461]
This raises a huge red flag for me. I was poking around the sonarr sqlite database and discovered that all configuration is just stored in the database as plain text. This is very unexpected, as I would have expected passwords and api keys to be encrypted. Even though, most of the time it shouldn't matter. Some people host these services on shared servers and in places that have a higher risk of someone getting to the data files.

Encrypting the passwords and api keys should be standard development practice and is something that is very simple to do.

**Comment by deanishe** [comment]
> Some people host these services on shared servers and in places that have a higher risk of someone getting to the data files.

Would encryption provide meaningful protection in this scenario? The encryption key would presumably also have to be on the server for Sonarr to be able to use the credentials.

That or you'd have to enter it via the web interface each time you restarted Sonarr.

**Comment by darknessgp** [comment]
deanishe, that's a good point. And you are correct, the encryption key would have to be available somewhere... I know Jackett does AES encryption and has the key hardcoded into their source code... what I see this really aiming to prevent is someone just going and copying your database and very easily having access to the passwords. Presumably, it could use a key that's a predefined value plus a user set value on setup... might make it a little more difficult.

**Comment by deanishe** [comment]
A key in the source code would be a bit more secure, but only if you changed it and compiled the program yourself. If not, well, it's easier to grab the key from a public GitHub repo than someone's private server…

**Comment by markus101** [comment]
> Some people host these services on shared servers and in places that have a higher risk of someone getting to the data files.

On Windows the file is in a shared location (`C:\ProgramData\`), but that's not typically a platform that has shared servers on it. For non-Windows systems Sonarr puts the file inside the home directory, which is not world readable and would require the user to pass in a different location. Docker might be a concern depending how it's setup, lots of images out there and where docker stores it's data might not be locked down like the home directory is by default.

> A key in the source code would be a bit more secure, but only if you changed it and compiled the program yourself. If not, well, it's easier to grab the key from a public GitHub repo than someone's private server…

Pretty much this, it's just security theater. We can encrypt it using a common key, but that's only slightly better than nothing at all (way too many ways to dig in and find it). Even with the "I compiled it myself method" if they could get the DB presumably they could get a copy of the executables and `.pdb`/`.mdb` files and debug it to read it from the code.

Having to enter a password every time Sonarr started would be cumbersome and doesn't make much sense in an automation application. I can say with almost 100% certainty we won't do this.

With Windows we could lock it to the machine its running on, but then restoring a backup of the database would require entering all your passwords again (maybe that's not so bad), but without a way to do the same on other platforms it likely won't help with the shared system scenario.

> Encrypting the passwords and api keys should be standard development practice and is something that is very simple to do.

It's simple to do, but if it doesn't offer any actual security it's not really worth anything. Unfortunately we're also not the only application that has troubles in this area.

**Comment by Stephen2** [comment]
What am I missing?  Doesn't a one way hash solve this?  Sure the shared key means you could attempt to brute force to get a matching hash, but you still can't just download someone's DB and know their password instantly?

**Comment by deanishe** [comment]
A one-way hash is only useful for a service's *own* passwords, in this case a password you've set to protect access to Sonarr.

These are passwords/API keys for *other* services (indexers, download clients etc.). Sonarr needs the plaintext passwords to pass to those services. If it could just pass a hash of the password, well, that would *be* the password (or as good as).

**Comment by Stephen2** [comment]
Oh... Ok, so user passwords hashed, API keys not... Makes sense.

**Comment by deanishe** [comment]
More accurately, it's a client/server thing. Servers can store hashes. Clients need the actual password/API key to access the server.

When talking to indexers/download clients, Sonarr is the client.

**Comment by markus101** [comment]
Not something we can take action on, closing.
