### ISSUE TITLE
Sonarr  segfaults on Alpine Linux when libmediainfo is called

### ISSUE THREAD

**Issue by wilreichert** [Sonarr/Sonarr#1462]
Configuration:
[Alpine Edge](https://wiki.alpinelinux.org/wiki/Edge)
[mono 4.2.2.30-r1](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/mono) from testing repo
[libmediainfo & libzen](https://mediaarea.net/en/MediaInfo/Download/Source) compiled from source
sonarr master branch, develop behaves the same

Problem is as the title says, whenever libmediainfo.so.0 is called sonarr segfaults. Nothing gets written to the logs even with the --debug flag used. Here is a gist with an [strace](https://gist.github.com/wilreichert/460f687d22b813e7844c2650dc910ce2) of the crash.
I suspect this is likely a mono / musl issue, but figured I would report it anyway.

**Comment by thezoggy** [comment]
can you report back what  `grep MonoPosixHelper /etc/mono/config` shows ?

**Comment by wilreichert** [comment]
Should be stock values.

<img width="721" alt="screen shot 2016-10-13 at 9 00 38 am" src="https://cloud.githubusercontent.com/assets/4916864/19356747/b2ccac96-9123-11e6-83d4-89f7ff5b552f.png">

**Comment by markus101** [comment]
If you capture the stdout and stderr of the mono process that should help capture the stack trace and mono running with the `--debug` flag will give line numbers in our binaries. This could be related to https://github.com/Sonarr/Sonarr/issues/1501 which is due to a bug in mediainfo and a specific file type.

**Comment by wilreichert** [comment]
System updated a bit since the initial report but the problem persists:
Alpine 3.5
mono-4.6.1.5-r0 form the testing branch
libmediainfo & libzen compiled from git
sonarr master branch

No stack even with the --debug flag. Looks like for whatever reason Alpine decided to build [mono](http://git.alpinelinux.org/cgit/aports/tree/testing/mono/APKBUILD) with the'--without-sigaltstack' flag. I'll rebuild mono without that & give it another go.

FWIW if I enable trace logging in sonarr I get this:

```
16-11-28 11:40:21.7|Debug|DiskScanService|1 video files were found in /data/xfer/tv/Regular.Show.S01E01.720p.BluRay.x264-DEiMOS
16-11-28 11:40:21.7|Debug|ImportDecisionMaker|Analyzing 1/1 files.
16-11-28 11:40:21.7|Debug|QualityParser|Trying to parse quality for /data/xfer/tv/Regular.Show.S01E01.720p.BluRay.x264-DEiMOS/Regular.Show.S01E01.720p.BluRay.x264-DEiMOS.mkv
16-11-28 11:40:21.7|Debug|VideoFileInfoReader|Getting media info from /data/xfer/tv/Regular.Show.S01E01.720p.BluRay.x264-DEiMOS/Regular.Show.S01E01.720p.BluRay.x264-DEiMOS.mkv
16-11-28 11:40:21.9|Trace|HttpClient|Res: [GET] https://torrentapi.org/pubapi_v2.php?mode=list&ranked=0&category=18%3B41&limit=100&token=(removed)&format=json_extended&app_id=Sonarr: 200.OK (952 ms)
16-11-28 11:40:21.9|Warn|Rarbg|Indexer API call returned error 5: Too many requests per second. Maximum requests allowed are 1req/2sec Please try again later! - https://torrentapi.org/pubapi_v2.php?mode=list&ranked=0&category=18%3B41&limit=100&token=(removed)&format=json_extended&app_id=Sonarr

[v2.0.0.4408] NzbDrone.Core.Indexers.Exceptions.IndexerException: Indexer API call returned error 5: Too many requests per second. Maximum requests allowed are 1req/2sec Please try again later!
  at NzbDrone.Core.Indexers.Rarbg.RarbgParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000b5] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\Rarbg\RarbgParser.cs:40 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00008] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:286 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchReleases (NzbDrone.Core.Indexers.IndexerPageableRequestChain pageableRequestChain, System.Boolean isRecent) [0x0008e] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:143 

16-11-28 11:40:22.0|Trace|MediaInfo|Read file offset 0-32768 (32768 bytes)
```

**Comment by wilreichert** [comment]
trace w/ sysout, syserr, & mediainfo (not specific to this file, all media will cause the segfault) https://gist.github.com/wilreichert/dd2c81c3aff9d591a75eb8d0392e0c0f#file-gistfile1-txt

**Comment by thezoggy** [comment]
what version of mediainfo do you have installed?

**Comment by wilreichert** [comment]
master from https://github.com/MediaArea/MediaInfo.git built on the 28th
```
$ mediainfo --Version
MediaInfo Command line, 
MediaInfoLib - v0.7.90
```

**Comment by tinuva** [comment]
If it helps, Sonarr inside docker also segfaults, if the docker host is Alpine linux with the grsec kernel.

I was on linux-virtgrsec kernel package when it segfaults.

Did:
apk add linux-vanilla
apk del linux-virtgrsec

Rebooted, and the Sonarr inside the docker started working.

So the solution is probably to find out which grsec setting (paxctl) is required to have Sonarr work when running direct on Alpine Linux grsec kernel. Or to use non-grsec kernel, as I have no idea how to fix this for a dockerized instance of Sonarr.

**Comment by Lochnair** [comment]
@tinuva I've got a similar setup to you. Running Sonarr in a Ubuntu-based Docker-container on an Alpine host (w/grsec). To fix the segfaults I run the following commands when creating the image:

```bash
apt install paxctl
paxctl -c /usr/bin/mono
paxctl -c /usr/bin/mono-sgen
paxctl -m /usr/bin/mono
paxctl -m /usr/bin/mono-sgen
```

**Comment by Twanislas** [comment]
Hello !

Just FYI, workarounds by @tinuva and @Lochnair did not work for me.

I temporary rebased my container (https://github.com/Twanislas/docker-sonarr/commit/f1caf8ea8e023080614eede6c4aa08d49170c497) on ubuntu while I have time to investigate more...

Cheers ! :)
