### ISSUE TITLE
Sonarr won't start after update to 2.0.0.4332

### ISSUE THREAD

**Issue by rpicking** [Sonarr/Sonarr#1466]
After an automatic update 2-3 days ago sonarr now won't start.  Running it manually on omv debian produces sql logic error or missing database no such function: instr.  Restoring old backups results in the same issue.

[http://pastebin.com/29TeSekq]

**Comment by markus101** [comment]
Looks like you're using an old version of SQLite (from prior to December 2012).

http://stackoverflow.com/questions/17887558/why-does-sqlite-say-that-instr-doesnt-exist

**Comment by SimonW500** [comment]
I was experiencing exactly the same thing / error, also running OMV and thus presumably the same version of SQLite (?).

My workaround was to manually roll back to the last master branch release, it being a develop branch release that "broke" this for me/us, though guess the actual required fix is for the SQLite plugin to be updated. Forgiving my ignorance, is SQLite (/this instance) installed as part of Sonarr or A.N. Other? I know I have (and use for other purposes) a MySQL omv-plugin, though not sure if related?

Thanks in advance.

**Comment by markus101** [comment]
Turns out Debian Wheezy (which OMV is built upon) does not have a newer version of SQLite available, so updating is not a trivial task and may cause issues due to integration with other parts of the system. We'll be updating the migration to avoid using `instr`.

**Comment by SimonW500** [comment]
Terrific response, great support backing up a great project! Appreciate.

Will stick with the master branch until this is reverted. Thanks again.

**Comment by cazador481** [comment]
@markus101 how did you roll back your changes?

**Comment by markus101** [comment]
@cazador481 nothing was rolled back, how the DB migration was done was changed to work on really old versions of SQLite.
