### ISSUE TITLE
ERR_CONNECT_FAIL on http://localhost:8989/

### ISSUE THREAD

**Issue by westlinkin** [Sonarr/Sonarr#1469]
OSX 10.11.6

After 

```
- Download latest version of Sonarr's OSX package from https://download.sonarr.tv/v2/master/latest/NzbDrone.master.osx.zip
- Open the archive and drag the Sonarr icon to your Application folder.
- Open Sonarr.app
```

I open `http://localhost:8989/` in my browser, it shows `ERR_CONNECT_FAIL`

How can I fix it?

**Comment by markus101** [comment]
Have you checked the log files? Please open a thread on the [support forums] (https://forums.sonarr.tv/) I've you're still experiencing issues.
