### ISSUE TITLE
API: Trakt ID not included in /api/series

### ISSUE THREAD

**Issue by KrunchMuffin** [Sonarr/Sonarr#1472]
In the series API endpoint, the trakt id is not included though all the others are.

    "tvdbId": 248741,
    "tvRageId": 28416,
    "tvMazeId": 124,
    "imdbId": "tt1845307",

**Comment by markus101** [comment]
Sonarr doesn't have the Trakt ID for series. The UI creates it using the TVDB ID:

https://github.com/Sonarr/Sonarr/blob/develop/src/UI/Handlebars/Helpers/Series.js#L23
