### ISSUE TITLE
Seasons and Images no longer returned with the Series when attached to the episode

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1473]
This has broken things for NZB 360 and broke our API contract.

Removing: `episode.Series ??` from https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Api/Episodes/EpisodeModuleWithSignalR.cs#L94 will fix it, but does add extra DB queries.

**Comment by Taloth** [comment]
That's actually a bug in Marr (or a misconfiguration in our tablemapping), the `List<MediaCover> Images` gets properly loaded, but replaced in `InitOneToManyChildLists` with an empty list coz it thinks it's a relationship instead of a property.

**Comment by Taloth** [comment]
```
Series.Profile mapped as relationship.
Episode.EpisodeFile mapped as relationship.
Episode.Series mapped as relationship.

Series.Images wrongly mapped.
Series.Ratings wrongly mapped.
Series.Genres wrongly mapped.
Series.Actors wrongly mapped.
Series.Seasons wrongly mapped.
Series.Tags wrongly mapped.
Series.AddOptions wrongly mapped.
Episode.Ratings wrongly mapped.
Episode.Images wrongly mapped.
```
