### ISSUE TITLE
Blank White Page

### ISSUE THREAD

**Issue by fm-techbts** [Sonarr/Sonarr#1478]
Sonarr is still working and grabbing episodes but I cant get to the web interface. It just shows a blank white page. App is running on OSX. It happens on multiple devices as well in both Unix and Windows environments.

**Comment by markus101** [comment]
Sounds like the same issue as: https://forums.sonarr.tv/t/white-screen-after-login-on-mac-osx/12065

Please open a thread on the support forums if you're still experiencing issues after upgrading mono.
