### ISSUE TITLE
delete unmonitored episodes from wanted list

### ISSUE THREAD

**Issue by flipppy** [Sonarr/Sonarr#1480]
is there a way to do the above...i have 175 pages of unmonitored episodes in my wanted list

thanks in advance.....ps  im pretty new to this :)

**Comment by markus101** [comment]
Please use the forums for support/questions.

You need to unmonitor the episodes (or have a file on disk for them) if you don't want them treated as missing. https://github.com/Sonarr/Sonarr/wiki/Monitoring-Series-and-Episodes

**Comment by flipppy** [comment]
they are unmonitored already

**Comment by tekanoma** [comment]
There is a toggle above the status column which switches between showing monitored only and unmonitored only, you most likely have it set to show unmonitored only, if not then I don't really understand what you are trying to do

**Comment by markus101** [comment]
If the series _or_ episode is unmonitored it won't be in Wanted: Missing.

If you're still having issues please open a thread on the forums with screenshots of Wanted: Missing, the episode details and the series page.

**Comment by flipppy** [comment]
if i click on unmonitored only...it has like 20 pages of episodes i already have...just wanna delete them....the monitored tab just has the 2 episodes that im still waiting for..

**Comment by markus101** [comment]
They're unmonitored, Sonarr won't try to grab them and they're not soemthing you need to look at... just don't click on `Unmonitored Only` if you want to be able to click on that and not see them Sonarr will need to see a file on disk for that episode so it's not missing. Other than that you can't delete or edit that list.

**Comment by flipppy** [comment]
Ok thanks...at least i wont waste anymore time trying :)  just be nice to have a delete button! :)

**Comment by flipppy** [comment]
btw ... most of the files are on the disk

**Comment by markus101** [comment]
It's not something you can delete, it's based on the episode information coming from TheTVDB and information Sonarr has about the files. The only way to delete it would be to delete the episode information from TheTVDB and that doesn't make any sense to do.

> btw ... most of the files are on the disk

For the episodes listed there? Either they are named in a way that Sonarr can't understand them or not in a location where Sonarr expects them. If that's something you want to resolve, open a thread on the forums.

**Comment by flipppy** [comment]
yeah for eg   scream... bosch... sonar grabbed these. all episodes are there... renamed by sonar...weird
