### ISSUE TITLE
Periodically Sonarr Fails Automatic Search For New Episodes

### ISSUE THREAD

**Issue by LeeThompson** [Sonarr/Sonarr#1482]
I've been noticing an intermittent issue with Sonarr not downloading new episodes like it should.

Example: Last night "The Blacklist" aired a new episode, but it had not downloaded it (even showed red in calendar view), so I just clicked on it and did an automatic search and it found it right away.

This is not the first time I've had to do this.     

Unfortunately there's nothing in the logs.

Sonarr v2.0.0.4326
mono 4.2.2 (Stable 4.2.2.30/996df3c Thu Mar 17 11:46:47 CET 2016)

**Comment by markus101** [comment]
Please use the forums for support.

We'll need to see Debug Logs of an RSS Sync with something that was expected to be grabbed on it to see why it wasn't grabbed. It could be Sonarr never saw it on RSS or it did and it previously failed for some reason, but without logs we can only guess.
