### ISSUE TITLE
Nyaa indexer stopped working

### ISSUE THREAD

**Issue by AeonLucid** [Sonarr/Sonarr#1489]
http://www.nyaa.se/ enabled the cloudflare thing that shows "Checking your browser before accessing nyaa.se", now Sonarr has trouble accessing the page.

Gives a 503 http response with the cloudflare challenge.

**Comment by AeonLucid** [comment]
Looks like it works again.

**Comment by markus101** [comment]
Sounds like nyaa fixed the issue or it was a temporary IP restriction (especially if using a shared IP via VPN or a seedbox)
