### ISSUE TITLE
Multiple root folders with warning about missing folder

### ISSUE THREAD

**Issue by geolaw** [Sonarr/Sonarr#1490]
I have Sonarr set up with 2 different root folders.  As my collection has grown I have had to add NAS space to accommodate 

I incorrectly added a series that I already had on my hard drive and have since deleted the series and removed that root folder as directed by the wiki

![screenshot_00014](https://cloud.githubusercontent.com/assets/1840954/19113433/93c24f4c-8ad7-11e6-9b56-74eac8bb5b88.png)

That Star Trek: Osiris folder has been removed and no longer appears : 
![screenshot_00015](https://cloud.githubusercontent.com/assets/1840954/19113471/bf9c84c0-8ad7-11e6-86b9-ca3bcda00331.png)

I've restarted multiple times.  From the sound of the wiki, the only "fix" sounds like it is to relocate all of my series' to a single share.  and that would be a massive PITA

**Comment by markus101** [comment]
> I've restarted multiple times. From the sound of the wiki, the only "fix" sounds like it is to relocate all of my series' to a single share. and that would be a massive PITA

No, multiple root folders isn't an issue.

A missing root folder with the series title in the name means a series folder was incorrectly chosen as the root folder at one time, which sounds like you fixed, but there may be a series that is set to use a sub folder of that folder, which would trigger that warning. You can use Series Editor to check (as it lists the path next to the series).

P.S. Please use the forums for support next time.
