### ISSUE TITLE
Special eps moves into a subfolder, no way to turn off

### ISSUE THREAD

**Issue by ScuttleSE** [Sonarr/Sonarr#1492]
When I tell Sonarr to rename episodes of a series, it movies the Specials to a Specials subfolder, no way to turn this off in the UI

**Comment by markus101** [comment]
Sonarr will automatically use the `Specials` subfolder for episodes in Season 0 if `Use Season Folders` is enabled. If you don't want to use season folders turn it off, if you want it to use `Season 0` or `Season 00` you can do so by having it part of the episode naming format ie: `Season {season:00}\{Series Title} S{season:00}E{episode:00} {Episode Title}`
