### ISSUE TITLE
IPTorrents validation is incorrect

### ISSUE THREAD

**Issue by jonas747** [Sonarr/Sonarr#1493]
The IPTorrents url validation ([here](https://github.com/Sonarr/Sonarr/blob/7818f0c59b787312f0bcbc5c0eafc3c9dd7e5451/src/NzbDrone.Core/Indexers/IPTorrents/IPTorrentsSettings.cs#L19)) assumes that "download" will always be at the end, which it isn't always.

IPTorrents generated this rss url for me, which fails the validation and can't be added unless i move download to the end myself: 

`https://iptorrents.com/torrents/rss?u=snip;tp=snip;78;66;82;22;5;download;new`

**Comment by atrotors** [comment]
Came here to complain... learned how to fix the problem. Thanks random citizen

**Comment by jonas747** [comment]
I'd also like to add that the only error you get is the cryptic `Use Direct Download Url` which didn't help at all.
