### ISSUE TITLE
Indexer: TorrentDownloads

### ISSUE THREAD

**Issue by akafester** [Sonarr/Sonarr#1494]
A request to add this indexer to Sonarr. 
There's RSS support. 

https://www.torrentdownloads.me/

**Comment by markus101** [comment]
We will only add support for indexers that have an API. RSS only can be support with Torrent RSS if their feed is properly formatted and returns the correct `Content-Type`, which they do not. This is something they will need to fix on their end, they are return `text/html` and should return an XML/RSS content type (to match the actual content they return).
