### ISSUE TITLE
[CRASHES ON STARTUP SINCE ARCH LINUX UPGRADE]Probably somehow linked to libgdiplus.so

### ISSUE THREAD

**Issue by Rusk85** [Sonarr/Sonarr#1495]
Since I have upgraded my arch linux system this afternoon, sonarr crashes after about 30 seconds after starting the service. I could isolate one Exception:

`16-10-7 20:39:02.3|Debug|GlobalExceptionHandlers|Minor Fail: The type initializer for` ``'System.Drawing.GDIPlus' threw an exception.`
`[v2.0.0.4326] System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.so.0`
  `at (wrapper managed-to-native) System.Drawing.GDIPlus:GdiplusStartup (ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)
  at System.Drawing.GDIPlus..cctor () [0x000cc] in /build/mono/src/mono-4.6.1/mcs/class/System.Drawing/System.Drawing/gdipFunctions.cs:119 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_generic_class_init (intptr)
  at System.Drawing.Image.Dispose (System.Boolean disposing) [0x00000] in /build/mono/src/mono-4.6.1/mcs/class/System.Drawing/System.Drawing/Image.cs:794 
  at System.Drawing.Image.Finalize () [0x00000] in /build/mono/src/mono-4.6.1/mcs/class/System.Drawing/System.Drawing/Image.cs:789``

I have reinstalled sonarr, mono and libgdiplus and checked that the library in fact exists and is linked:

`$ yaourt -Q libgdiplus sonarr mono`
`extra/libgdiplus 4.2-1`
`local/sonarr 2.0.0.4326-1`
`extra/mono 4.6.1.3-1`

`$ ldconfig -p | grep libgdi`
`libgdiplus.so.0 (libc6,x86-64) => /usr/lib/libgdiplus.so.0`
`libgdiplus.so (libc6,x86-64) => /usr/lib/libgdiplus.so`

`$ ls -lah /usr/lib/libgdi*`
`lrwxrwxrwx 1 root root   19 Jul 14 19:57 /usr/lib/libgdiplus.so -> libgdiplus.so.0.0.0`
`lrwxrwxrwx 1 root root   19 Jul 14 19:57 /usr/lib/libgdiplus.so.0 -> libgdiplus.so.0.0.0`
`-rwxr-xr-x 1 root root 414K Jul 14 19:57 /usr/lib/libgdiplus.so.0.0.0`

I really don't know what else to check and would be grateful for any help. Might set up a small VM on my server just for sonarr or perhaps a Docker container.

Attached are trace and debug logs of sonarr.
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/516939/sonarr.debug.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/516940/sonarr.trace.txt)

**Comment by markus101** [comment]
Please use the forums for support.

Look like the same issue as: https://forums.sonarr.tv/t/sonarr-on-linux-now-crashing-after-a-few-secs/12254 - may be an issue with mono 4.6.

Have you tried downgrading mono?

**Comment by mmozeiko** [comment]
I had same issue. You need to install libraries libgdiplus.so file (x11 libs).
To determine which libraries are missing run `ldd /usr/lib/libgdiplus.so`. It will show you something like this:
```
$ ldd /usr/lib/libgdiplus.so
	linux-vdso.so.1 (0x00007ffcbbfc7000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f6509551000)
	libcairo.so.2 => /usr/lib/libcairo.so.2 (0x00007f6509262000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f6508fa5000)
	libXrender.so.1 => not found
	libX11.so.6 => not found
	libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007f6508d3b000)
	libtiff.so.5 => /usr/lib/libtiff.so.5 (0x00007f6508ab5000)
...
```
Here's you can see that libXrender.so and libX11.so files are missing. To get them install `x11` and `libxrender`.

I actually built for myself custom libgdiplus package that doesn't depend on x11 libraries (I don't have x11 running, because it's a server without display connected).

**Comment by Rusk85** [comment]
Thanks for your help. Managed to solve it. It was indeed a missing library libgdiplus was dependent on.

`$ ldd /usr/lib/libgdiplus.so | grep not`
        `libgif.so.7 => not found`

`$ yaourt -S giflib`
`resolving dependencies...`
`looking for conflicting packages...`
`:: giflib and giflib-nox11 are in conflict. Remove giflib-nox11? [y/N] y`

`Packages (2) giflib-nox11-4.1.6-5 [removal]  giflib-5.1.4-1`

`Total Download Size:    0.06 MiB`
`Total Installed Size:   0.22 MiB`
`Net Upgrade Size:      -0.29 MiB`

`:: Proceed with installation? [Y/n]`
`:: Retrieving packages...`
'
'`$ ldconfig -p | grep gif`
        `libgif.so.7 (libc6,x86-64) => /usr/lib/libgif.so.7`
      `  libgif.so.7 (libc6) => /usr/lib32/libgif.so.7`
    `    libgif.so (libc6,x86-64) => /usr/lib/libgif.so`
  `      libgif.so (libc6) => /usr/lib32/libgif.so`

`$ ldd /usr/lib/libgdiplus.so | grep not`
`>`

Since then sonarr is been working like a charm. 
Thanks again!
