### ISSUE TITLE
Feature suggestion: Favourite show tagging

### ISSUE THREAD

**Issue by Pho3niX90** [Sonarr/Sonarr#1496]
I have recentlymoved from Sickbeard to Sonarr. Best decision I have ever made. 

My suggestion/feature request is to have an option to tag favourite shows, I have a collection of 300 shows and around 20 of them I whatch religiously,  so the purpose of the favourite selection is to send it to a different category that will put it in the highest priority when downloading, and also to have a filter on the calendar to only see favorite shows and filter on the dash to only see favourite shows.

**Comment by markus101** [comment]
You can apply text-based tags to series, we don't have plans to have a favourite-only tag system. Currently you can't filter views based on tags, but that is something we have at least one issue filed for https://github.com/Sonarr/Sonarr/issues/566

Prioritization is heavily dependent on the download client being used, so I don't see a direct way to set that via tags, but possible via https://github.com/Sonarr/Sonarr/issues/402 - you'd use the same tag on the download client to indicate that you want it to use that one for your favourite series and then set the priorities as you see fit.
