### ISSUE TITLE
Unable to connect to indexer, check the log for more details

### ISSUE THREAD

**Issue by Titte95** [Sonarr/Sonarr#1506]
Been having this error for a few days. Tried different trackers, but same result.

> 16-10-13 14:03:09.4|Warn|HttpClient|HTTP Error - Res: [GET] https://XXX.XXX.XXX.XXX/jackett/torznab/hounddawgs/api?t=caps&apikey=(removed) 401.Unauthorized
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>401 Unauthorized</title>
> </head><body>
> <h1>Unauthorized</h1>
> <p>This server could not verify that you
> are authorized to access the document
> requested.  Either you supplied the wrong
> credentials (e.g., bad password), or your
> browser doesn't understand how to supply
> the credentials required.</p>
> <hr>
> <address>Apache/2.4.10 (Debian) Server at XXX.XXX.XXX.XXX Port 443</address>
> </body></html>
> 
> 16-10-13 14:03:09.4|Warn|HttpClient|HTTP Error - Res: [GET] https://XXX.XXX.XXX.XXX/jackett/torznab/hounddawgs/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100: 401.Unauthorized
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>401 Unauthorized</title>
> </head><body>
> <h1>Unauthorized</h1>
> <p>This server could not verify that you
> are authorized to access the document
> requested.  Either you supplied the wrong
> credentials (e.g., bad password), or your
> browser doesn't understand how to supply
> the credentials required.</p>
> <hr>
> <address>Apache/2.4.10 (Debian) Server at XXX.XXX.XXX.XXX Port 443</address>
> </body></html>
> 
> 16-10-13 14:03:09.4|Warn|Torznab|Unable to connect to indexer
> 
> [v2.0.0.4326] NzbDrone.Common.Http.HttpException: HTTP request failed: [401:Unauthorized] [GET] at [https://XXX.XXX.XXX.XXX/jackett/torznab/hounddawgs/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100]
>   at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x001a1] in <4f799f5bb7104eb690bf5945746e79cf>:0 
>   at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchIndexerResponse (NzbDrone.Core.Indexers.IndexerRequest request) [0x00058] in <cf3b823821944161902a2ac2cbb870dd>:0 
>   at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00000] in <cf3b823821944161902a2ac2cbb870dd>:0 
>   at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00024] in <cf3b823821944161902a2ac2cbb870dd>:0 
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>401 Unauthorized</title>
> </head><body>
> <h1>Unauthorized</h1>
> <p>This server could not verify that you
> are authorized to access the document
> requested.  Either you supplied the wrong
> credentials (e.g., bad password), or your
> browser doesn't understand how to supply
> the credentials required.</p>
> <hr>
> <address>Apache/2.4.10 (Debian) Server at XXX.XXX.XXX.XXX Port 443</address>
> </body></html>
> 
> 
> 16-10-13 14:03:09.4|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
>  -- Unable to connect to indexer, check the log for more details

XXX.XXX.XXX.XXX = Removed ip address.

**Comment by Taloth** [comment]
I'd think the error is pretty clear: "Unauthorized". So your api key is probably wrong.
