### ISSUE TITLE
Issue when adding a new series via Api

### ISSUE THREAD

**Issue by tidusjar** [Sonarr/Sonarr#1507]
Hello,

I am trying to add a new series using the following endpoint:

`/series` with a POST request, the JSON body is below

```
{
    " addOptions " : {
        " ignoreEpisodesWithFiles " : true,
        " ignoreEpisodesWithoutFiles " : true,
        " searchForMissingEpisodes " : false
    },
    " title " : " Narcos ",
    " seasons " : [],
    " rootFolderPath " : " D :  \ Media \ TV Shows ",
    " qualityProfileId " : 1,
    " seasonFolder " : true,
    " monitored " : true,
    " tvdbId " : 282670,
    " tvRageId " : 0,
    " cleanTitle " : null,
    " imdbId " : null,
    " titleSlug " : " Narcos ",
    " id " : 0,
    " images " : []
}
```

Now I cannot understand why it is setting the latest season in the series as monitored and non of the episodes:
![image](https://cloud.githubusercontent.com/assets/6642220/19365586/597bcf7e-918b-11e6-9d31-43c6fad257f3.png)

I would have expected no seasons to be monitored as I set both `ignore` option in the `addOptions` to true

Any idea what might be going on here?

Related Plex Request issue https://github.com/tidusjar/PlexRequests.Net/issues/587

**Comment by tidusjar** [comment]
Any idea guys?

**Comment by markus101** [comment]
The latest season is always left monitored, this is because more episodes may be added to the season and newly added episodes take inherit the monitored status of the season.

I'm a little unclear what the issue is here, telling Sonarr to ignore episodes with files and ignore episodes without files tells Sonarr to unmonitor any aired episode with or without a file, but the linked issue seems to be about it _only_ monitoring future episodes (which is what you're achieving here).

**Comment by tidusjar** [comment]
Basically I have changed the way we search for episodes and seasons.
Before we were calling the command and searching for all episodes (By passing an array of episode Id's).

I changed it to search for the actual season itself. 

So when a series does not exist on Sonarr, I want to add the series as unmonitoed so nothing downloads/searches and then set the appropriate seasons as monitored and then call the command endpoint and search for that series (So it should only search for the seasons that I selected as monitored).

This doesn't seem to work, the main problem seems that I cannot add a series to Sonarr and set all seasons as unmonitored.

If you have an idea of a better way to do this, that would be excellent.

**Comment by markus101** [comment]
> This doesn't seem to work, the main problem seems that I cannot add a series to Sonarr and set all seasons as unmonitored.

You can actually set all the seasons to unmonitored in the request to add the series and Sonarr will respect that:

```
"seasons": [
  {
    "seasonNumber": 0,
    "monitored": false
  },
  {
    "seasonNumber": 1,
    "monitored": false
  },
  {
    "seasonNumber": 2,
    "monitored": false
  },
  {
    "seasonNumber": 3,
    "monitored": false
  }
],
```

**Comment by markus101** [comment]
@tidusjar is there anything you need from us? It looks like the issue you linked is closed with a fix in the latest release.

**Comment by tidusjar** [comment]
Yeah thank you for your help.
