### ISSUE TITLE
Discord Notifications

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1511]
Somewhat similar to Slack, but a custom implementation to send to Discord: https://discordapp.com/

**Comment by FireEater64** [comment]
Note that this is achievable right now, using the Slack connector, and Discord's [Slack-compatible webhooks](https://discordapp.com/developers/docs/resources/webhook#execute-slackcompatible-webhook).

Simply generate a webhook URL for a Discord channel [per the documentation](https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks), and add `/slack` on the end. Then setup the Slack connector as you usually would.

![image](https://cloud.githubusercontent.com/assets/1670176/23339587/eb63ddb2-fc1d-11e6-826d-826f8c20fe68.png)

To this end, do we need a Discord-specific connector? What additional functionality would it provide?

**Comment by pcjmfranken** [comment]
Not sure why but I'm just getting a 400 error when I do it like that, even though a POST req to the same URL from Postman works fine

**Comment by hephinator** [comment]
I am on the fence about a discord specific connector. I dont think any discord specific features would be enabled or gained by it, but it also prevents people getting confused about having ot add /slack to the end of Discord webhooks when using the "custom webhook" integration.

However, it also seems that the ability to set an icon to an image URL is about 50% working 50% broken. Any idea why always appears as the default discord logo, 99% of the time?

Posts: https://puu.sh/vYALB/c46c13601f.png
Settings: https://puu.sh/vYASc/fca1deba9a.png

**Comment by alxlaxv** [comment]
Great idea @markus101

**Comment by markus101** [comment]
Discord notifications have been added to v3.
