### ISSUE TITLE
Auto search for missing episodes on start up

### ISSUE THREAD

**Issue by rj93** [Sonarr/Sonarr#1512]
When I turn my pc on sonarr doesn't automatically download episodes which aired overnight. Would it be possible to set it so it automatically searches for new episodes when it starts up, as I currently have to go to the episode and click automatic search manually before it will start to download.

**Comment by markus101** [comment]
We have no plans to automatically search for episodes, Sonarr will attempt to page backwards in the RSS feed to avoid missing items, if that fails Sonarr will log that there is a gap. Whether Sonarr can page back depends on whether the indexer supports it.
