### ISSUE TITLE
Does Sonarr run on .NET or Mono in Windows?

### ISSUE THREAD

**Issue by tsoernes** [Sonarr/Sonarr#1515]
I'm planning to implement torrent streaming support with Peerflix, which is written in NodeJS, and to do that it seems that I need [Edge.js](https://github.com/tjanczuk/edge#edgejs-net-and-nodejs-in-process-), which is supported on .NET but not on Mono. 

I've never developed on C# or .NET before, so I wonder, will it be possible to run Edge in Sonarr?

**Comment by markus101** [comment]
.net on Windows, mono everywhere else. It's not clear what you're trying to achieve here exactly, but Sonarr isn't a torrent/usenet client (nor do we want it to be) it it's self it integrates with other clients so at most I'd see Peerflix being another client, not integrated into the Sonarr codebase.

**Comment by tsoernes** [comment]
Yes, it will act as another client, which is best done using the underlying node module behind the interface of peerflix, which is torrent-stream.
