### ISSUE TITLE
Change style of Disk Space

### ISSUE THREAD

**Issue by delphiactual** [Sonarr/Sonarr#1516]
Any chance we can get an updated view on the Disk Space that shows a bar graph comparing the used to free space (see example from windows)

![screenshot 2016-10-20 14 35 07](https://cloud.githubusercontent.com/assets/4798491/19577108/059ca264-96d3-11e6-8069-cbd61c970f9e.png)

![screenshot 2016-10-20 14 36 41](https://cloud.githubusercontent.com/assets/4798491/19577118/0b4c934a-96d3-11e6-966f-0a3fddea6880.png)

**Comment by markus101** [comment]
This will be included in the v3 UI.
