### ISSUE TITLE
Plex media server not picking up or adding TV Shows sorted via Sonarr Ubuntu

### ISSUE THREAD

**Issue by rosscco** [Sonarr/Sonarr#1517]
My Plex media server not picking up or adding TV Shows sorted via Sonarr via Ubuntu.
Tested adding the same file downloaded to my Windows PC and plex notices it, adds it and metatags it.

Any ideas?

Thanks

**Comment by markus101** [comment]
This sounds like a Plex issue, perhaps permissions.
