### ISSUE TITLE
Supported Synology Architecture

### ISSUE THREAD

**Issue by balmhood** [Sonarr/Sonarr#1521]
Hi, 
I have tried to look for the information but could not really find it. I know that PPC will not work and Intel/ARM should work. However before I fork in the dollars to replace my dead DS213+ (which could not run it), Can you share whether Sonarr will run on the below Synology NAS?

**DS216 Play**

> CPU Model STM STiH412
> CPU Architecture  32-bit
> CPU Frequency Dual Core 1.5 GHz

**DS416Play** 

> CPU Model Intel Celeron N3060
> CPU Architecture  64-bit
> CPU Frequency Dual Core 1.6 burst up to 2.48 GHz

or
**DS716+II**

> CPU Model Intel Celeron N3160
> CPU Architecture  64-bit
> CPU Frequency Quad Core 1.6 burst up to 2.24 GHz

**Comment by markus101** [comment]
The `DS216 Play` may be fine, but it will come down to mono support on that processor, but either the `DS416 Play` or `DS716+II` should have better support overall and should provide better performance.

**Comment by balmhood** [comment]
Thanks Markus, 
in term of performance. I am planning to use it mainly to:
- run sonarr
-run couchpotato
-run sabnzb
- be accessible to my android TV for movie streaming using Kodi and DS Video
- be able to stream to IOS/Android phones/tablets

do you think that the 416play would suffice (i like the 4 bays)

**Comment by markus101** [comment]
It'll be okay as long as you don't need to transcode video for playback on the mobile devices (depends on the connection and whether the device can play the content natively). Anything CPU intense (par2 checks in SAB, transcoding, etc) is going to eat up the CPU though, but unless you get an i3/5/7 CPU in there ($$) that's going to be a limitation.

Bottom line, it should work for what you want, it's just not going to be the fastest.

**Comment by balmhood** [comment]
I finally got the 416Play... thanks !
