### ISSUE TITLE
Sonarr + Jackett   Unable to parse episodes from release name

### ISSUE THREAD

**Issue by MisterC925** [Sonarr/Sonarr#1522]
Recently I've noticed an issue with a private tracker I've added through the JAckett system to Sonarr.

First let me apologize if this is a Jackett issue and not a Sonarr one, but I figured I'd check here :)

Sonarr 2.0.0.4326 running on an Asustor NAS.

I added the new BBC Series "Class" and noticed it wasn't finding the episodes I knew were on the tracker.

I did a manual search from the Wanted page and it found the episodes just fine but wouldn't give me the option to trigger the download because of the "Unable to parse..." error.

The search result was: "Class S01E02 (22 October 2016) HDTV 720p [Webrip]" which is exactly what it is called on the tracker (ie Jackett isn't munging the title)

I'm pretty sure this tracker (with this same naming convention) used to work just fine so I was wondering if there were recent changes?

Thanks!
<img width="1006" alt="screenshot 2016-10-24 22 27 15" src="https://cloud.githubusercontent.com/assets/21995339/19673918/1ed2c75e-9a39-11e6-8837-4b4bb7ee5606.png">
<img width="996" alt="screenshot 2016-10-24 22 27 28" src="https://cloud.githubusercontent.com/assets/21995339/19673919/1ed380fe-9a39-11e6-92d1-f3a118cb3b60.png">

**Comment by MisterC925** [comment]
So I just checked again and a different tracker has the episode and it seems to work
Class.S01E01.720p.iP.WEBRip.AAC2.0.H264-JiTB[rartv]

Thanks

**Comment by markus101** [comment]
Those aren't ideal release names, but we can support them it just needs a small tweak for us to be able to parse them.

**Comment by i3laze** [comment]
Same here.
It would be great for a regular user to tweak keywords by himself.

I'm using RuTracker with Jackett and have multiple issues, like:
1. Every torrent on this tracker ought to have Russian audio track by tracker rules, so it is not mentioned in file's title - I wonder if that could be parsed/forced/overriden in Sonarr/Jackett somewhere.

2. Title's there ought to have director's name in (round brackets) after film's title. Parsing is failing here - it should better omit brackets:
Затерянный город Z / The Lost City of Z (Джеймс Грэй / James Gray) [2016, США, боевик, драма, приключения, биография, история, BDRip] Dub + Sub Eng + Original Eng

Failed to map movie, found title Z / The Lost City of Z ( / James Gray) [, expected one of: The Lost City of Z, The Lost City of Z

3. Some release title's there mention BDRip without actual resolution (1080/720) - these releases are put by Sonarr to DVD quality no matter of file's size :( I wonder if something could be done here.
