### ISSUE TITLE
Apply download client label per series or profile

### ISSUE THREAD

**Issue by ajthemacboy** [Sonarr/Sonarr#1525]
I'd like a way to add a download client label (such as "tv-sonarr" by default) per series or per profile. I can't find a way to do this currently.

**Comment by markus101** [comment]
I'm curious why would this be useful to you? Unless there is a compelling reason to do it, I don't see this being something we'd support.

**Comment by ajthemacboy** [comment]
Some trackers don't have all the shows I'd like to torrent. I have reallllly bad upload speeds so I try not to have to seed anything, thus I generally prefer public trackers that I can leech. 

However, if a private tracker has a series or show that I'm trying to get, I'd like a way to always download it from that tracker, but obviously I can't leech it; thus I'd use the Deluge Label plugin to override the default seed ratio I have set in Deluge settings, per label or per torrent.

For this to work reliably you'd also need a way to prioritize trackers, so that:
**1.** Public trackers are searched first
**2.** If no public trackers have the show, private trackers are searched. Any found torrents have a label applied to them so that Deluge will seed them for longer.

**Comment by markus101** [comment]
I think the underlying feature for that would be handled via `Specify Seed Ratio / Time per Indexer` on https://github.com/Sonarr/Sonarr/issues/468 prioritization is part of https://github.com/Sonarr/Sonarr/issues/320 (though quality will still win over the type of indexer).
