### ISSUE TITLE
ShanaProject support

### ISSUE THREAD

**Issue by kabitokaii** [Sonarr/Sonarr#1526]
Hi guys,

I use a service called Shana project to pull in torrents for anime based on subber and anime title automatically from an RSS feed.

shanaproject.com

currently i have a very intricate way of getting the rss feed read, then the torrents dl'd then to the sonnarr drone folder then into my plex library. my work flow would be super simplified if the rss feed could be read and downloaded by sonarr. It doesnt do magnet links though is this a deal breaker?

It may just be easier to implement support for Tokyotosho.info as a data indexer since all the data for Shanaproject is from there and i could just add my series in Sonarr.

**Comment by markus101** [comment]
> It doesnt do magnet links though is this a deal breaker?

Magnet links aren't required, but a proper API is. If it doesn't have an API you can add it as a Torrent RSS feed in Sonarr (assuming its a well formed RSS feed).

> It may just be easier to implement support for Tokyotosho.info as a data indexer since all the data for Shanaproject is from there and i could just add my series in Sonarr.

Not exactly sure what Shana Project is versus Tokyotosho.info, but whichever one has the RSS feeds that Sonarr can process new releases from and determine which to download is the one you'd want to add as a Torrent RSS indexer in Sonarr.
