### ISSUE TITLE
Reported minimal Mono Version incorrect

### ISSUE THREAD

**Issue by Senaxx** [Sonarr/Sonarr#1530]
Sonarr reports that the installation should require minimal mono 3.10. On my system mono says my system needs minimal version 3.10 while version 3.2.8 is installed. 

System: Debian Jessie 8.6

Version 2.0.0.4374
Mono Version 3.2.8 (Debian 3.2.8+dfsg-10)
AppData directory /root/.config/NzbDrone
Startup directory /opt/NzbDrone.

Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-10)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+fallback
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

**Comment by markus101** [comment]
The error message is correct, 3.2.8 is less than 3.10 (that's ten, not 1.0).
