### ISSUE TITLE
unable to communicate with unraid 

### ISSUE THREAD

**Issue by sch1308** [Sonarr/Sonarr#1538]
![image](https://cloud.githubusercontent.com/assets/7896067/19980587/fa2e6b4e-a1d4-11e6-99eb-ff833dd61188.png)

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
Sonarr can't connect to your download client named `unraid` the logs are cutoff and don't have line numbers so I can't say where exactly it is failing (I've opened a PR for the docker image to fix that going forward). All I can really suggest is to make sure the WebUI of deluge is working properly.


> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please use the forums for support next time.

**Comment by sparklyballs** [comment]
Unraid is the name of the OS hosting the docker, it's not a download client.
I'm suspecting that the user is trying to pass unraid as a download client to some setting in the webui or using unraid as part of the url to a client.

**Comment by CHBMB** [comment]
I've replied to your post on the unraid forums too.  Bottom line, you're posting the same thing in multiple places, but not posting enough information for anyone to help you.

**Comment by markus101** [comment]
Sonarr is logging that message because the download client has been named `unraid` in Sonarr's settings.

Posted here as well, with a bit more details. https://forums.sonarr.tv/t/unable-to-communicate-with-unraid-object-reference-not-set-to-an-instance-of-an-object/12616
