### ISSUE TITLE
Rearrange Qualities in profile

### ISSUE THREAD

**Issue by Casburggraaf** [Sonarr/Sonarr#1540]
With the latest update its not possible to arrange the qualities in a profile.  I'm the only one with this problem?
![screen shot 2016-11-06 at 17 20 24](https://cloud.githubusercontent.com/assets/373753/20039523/ae1c3c9a-a445-11e6-94b4-b7abdbd4c177.png)
As i recall of the previous version there were buttons on the right side to rearrange them

**Comment by Taloth** [comment]
Yup, and they still are, but only when 'Advanced Settings' are enabled. That hasn't changed.

![image](https://cloud.githubusercontent.com/assets/6383890/20039913/54afc0b6-a44d-11e6-9f7d-97a79e285e72.png)
