### ISSUE TITLE
Simple API for IFTTT + voice command integration

### ISSUE THREAD

**Issue by Mobrockers** [Sonarr/Sonarr#1542]
It would be very useful for IFTTT scripts if a simple version of the API exists that simply does best-effort-matching for given requests, and doesn't require a full JSON payload. I saw someone on reddit today that had the idea to tell sonarr through google home to start downloading an episode/series. When I went to try it out I noticed that this requires json processing (request series, pick series, send series payload back to sonarr), which I don't think can really be done in IFTTT.

My thought is you would do something like this: 

POST http://localhost:8989/simple-api/series/add/The%20Blacklist

Everything else would simply be the default values, and the whole series would get set to watched + start searching. There could be other endpoints to specify for example search for latest available episode only, etc.

**Comment by markus101** [comment]
> Everything else would simply be the default values

There aren't default values, everything is sent from the client the defaults that are stored are stored in the client and sent when adding a series. That could possibly change, but nothing planned at the moment, but it those options would probably be better coming from the client as options when making the request, but that would likely require something in the middle translating what the user requested into something Sonarr can understand.

The fact that there are a lot of similar series titles is a concern though, coupled with poor search results at times could lead to a really frustrating experience. I don'tr ally see this being something we support in the short term.

**Comment by Mobrockers** [comment]
I figured as much. Thanks.
