### ISSUE TITLE
armel debian packages

### ISSUE THREAD

**Issue by victornoel** [Sonarr/Sonarr#1545]
Hi,

Any reason there is no armel debian package?
Or is it simply no armel debian repository, because I understood sonarr only needed mono and wasn't tied to any specific architecture (there is a mono-devel package for armel coming from mono's debian repositories).

Thanks :)

**Comment by Taloth** [comment]
There are several dependencies, such as mediainfo, sqlite etc.

**Comment by Taloth** [comment]
**Milestone comment**: Packages require a platform to test on. markus has an idea on setting up an test environment for it, conditional on that we might be able to add a package for it during or after the v3 release.

**Comment by markus101** [comment]
With v4 we've dropped debian packages, no plans to reintroduce them at this time.
