### ISSUE TITLE
Not importing some multipart RAR episodes

### ISSUE THREAD

**Issue by tsoernes** [Sonarr/Sonarr#1546]
Some episodes that are packed in multiple RAR archives (.RAR, .R00, ...) are not detected on import/rescan, while others are. 

![screenshot from 2016-11-14 02-12-10](https://cloud.githubusercontent.com/assets/6782404/20250627/0147783c-aa11-11e6-94e2-1693f8c54437.png)

**Comment by markus101** [comment]
Sonarr doesn't process RAR files, your download client (or a script running from it) should extract the RAR files before Sonarr processes them.

It also looks like you have your sorted files and unsorted files mixed together, to keep things cleaner you should keep them separate.
