### ISSUE TITLE
support duplicate par recovery

### ISSUE THREAD

**Issue by orbisvicis** [Sonarr/Sonarr#1548]
About a year ago, NZBGet introduced the ability to repair across failed duplicates. See nzbget/nzbget#64. It doesn't seem to be supported by any external apps, but it works very well with NZBGet's builtin RSS reader. Whenever duplicate "titles" are added to the queue, and that "title" hasn't yet successfully downloaded, NZBGet downloads as much as possible from each NZB, and then performs a par recovery across the entire group. It is surprisingly successful, and is what has often allowed me to obtain movies that would otherwise fail. If using par1 sets this duplicate recovery is only possible across reposts. These days everyone uses par2, which will find blocks across even different archive sets. That's right - even if the same scene release was separately rar'd across several different (usenet) uploads, with different split-rar sizes, duplicate par2 recovery might still work.

Its frustrating to find 20 different uploads for a single episode, representing maybe 3 or 4 different scene releases (not reposts, but different uploads re-archived by different users), and have them all fail, knowing that in aggregate they could have been repaired.

To be fair, I don't know how compatible this is with Sonarr's NZBGet integration: upload 1st nzb, check status, delete failure, upload 2nd nzb, ... and so on. Sonarr might have to batch upload all episode releases with the same "title", let NZBGet do all the work for that batch, and then check the results.

Sonarr would also have to provide a duplicate key - a string that uniquely identifies a scene release of a particular episode. This is what I mean by "title". However, Sonarr already has such scene-matching capabilities.

This will greatly improve the reliability of usenet services.

**Comment by thezoggy** [comment]
just because something has the same 'title' doesnt mean it was posted + packaged by the same person.. so the parset a lot of times wont work since its for a different rarset. so to me it just seems like a waste of bw+time.. for what little possible gain. 

since chances are that if something posted in cleartext is dmca'ed.. all of them similarity would be. the ones that are obfuscated would still work.. but the cleartex parset wouldnt for it.

if you are having completion problems, you'd be best off just getting a 2nd usp (block/fill) from a different backend than your main.

**Comment by orbisvicis** [comment]
Duplicates don't have to be reposts, packaged by the same person, posted by the same person, share the same filenames, or even share the same rar split/part-size as long as the underlying content is *mostly* the same, for par2 duplicate recovery to work. In fact, the content can be so unrelated that NZBGet doesn't delete duplicates which donate recovery blocks to other uploads on the off-chance they aren't related.

NZBGet avoids duplicate par recovery on contents with less than 10% (arbitrary heuristic) completion to avoid dmca'ed content.

That's why I define "title" as a string that uniquely identifies a scene release of a particular episode. Sonarr has access to this sort of duplicate key, even for obfuscated content. Everything NZBGet has trouble with, Sonarr is well-placed to accomplish: identifying and managing/deleting duplicates.

The gain is more than you think.

**Comment by markus101** [comment]
This is an interesting idea, but not something we plan to support at this time. Labeled it so we can re-evaluate it again down the road and keep our issues manageable.
