### ISSUE TITLE
complete down handling - link nzbs, don't move, feature request.

### ISSUE THREAD

**Issue by thechile** [Sonarr/Sonarr#1550]
can i tell sonarr to **not** move completed NZBs but instead just link them in the same way torrents are handled ? 

I would like to sync both torrent and nzb downloads with cloud provider and it would be much easier to set this up if both torrent and nzb downloads remaining in one static 'completed' location. 

In the event that my local drives got trashed then i could sync/restore from cloud and then re-import everything thanks to Wanted/Manual Import and this https://github.com/Sonarr/Sonarr/pull/1513 new option that lets me link on import. 

thank you.

**Comment by thezoggy** [comment]
just use blackhole?

**Comment by thechile** [comment]
i don't see how blackhole will help ?

the nzb has already been sent to sabnzbd, downloaded and then **moved** by sonnar from the category download location configured in sabnzbd to the episode specified location. 

This is a non-configurable behaviour of sonnar. I want the option to link from the nzb download path instead of moving.

**Comment by Taloth** [comment]
You don't need to configure it in Sonarr, just setup a post-process script in sabnzbd/nzbget to hardlink the file to another directory and sync from there to the cloud.
Sonarr will wait for the pp-script to finish before importing, so it won't interfere.

So instead of syncing the sab/nzbget completed folder, you instead sync that other folder.

**Comment by thechile** [comment]
OK i guess i could do that, i was just hoping that sonarr could be even more awesome and allow link *or* move. 

At the moment in sabnzbd, i have sonarr label and category so on completion it gets moved into `nzb/completed/tv` directory. Currently Sonarr will then move it into the series folder.. to do as you suggest i would need to specify the sabnzbd category directory something like `nzb/staging/tv` and then pp-script that hard-links to `nzb/completed/tv` so when sonarr moved it from `nzb/staging/tv` everyone is still happy.

Not big deal, just seems i'm working around sonarr missing feature by using sabnzbd pp-script. Hence why asking for feature request to add this as new option.

**Comment by scw1937** [comment]
I'm with you, I guess.

I want Sonarr to:
1. make my download client download a missing episode,
2. remove and re-download on failure,
3. mark the episode as downloaded on success.

I do not want Sonarr to post-process/move any file when the episode is downloaded/imported on success.

**Comment by markus101** [comment]
No plans to support copying instead of moving at this time.
