### ISSUE TITLE
Sonarr does not detect episodes delete from disk

### ISSUE THREAD

**Issue by athei** [Sonarr/Sonarr#1555]
From time to time I delete old season from the disk manually. Sonarr does not detect that these episodes are gone. It still lists them as if the file still existed. Yes I did clicked  the "Scan Disk" button in Sonarr. Newest version. Mono 4.6. Freebsd.

**Comment by markus101** [comment]
Please use the forums for support. Check the debug logs files to see what Sonarr sees during the disk rescan.
