### ISSUE TITLE
Settings/Connect/Email/Series Filter - Not Saved When > 12 Characters

### ISSUE THREAD

**Issue by Yarli** [Sonarr/Sonarr#1559]
I setup a custom tag on certain series, which was 13 character long, so that I could have my system notify a friend when certain series are downloaded. Upon trying to add that tag to a new email notification the tag turns blue and is recognised as valid, but when I save the notification and go back in the tag is missing.

This happens when trying to update the field as well as populating it when creating a new notification.

Turns out that if I create a new tag which is smaller than 12 characters then it works. Anything longer than that, then it doesn't work. I suspect there's a limitation on the length of the field but I would have thought you would want to allow for a slightly larger field perhaps ? Maybe up to 30 characters ?

**Comment by markus101** [comment]
We don't impose a limit.

I was able to create one 26 characters long, which saved correctly and was there after reloading the page. Not sure why it didn't work for you, but it's not limited in length.

![image](https://cloud.githubusercontent.com/assets/413544/20584602/1dfa83d0-b1a9-11e6-9c02-9f575fa8b005.png)

**Comment by Yarli** [comment]
hmm. ok. Did you try adding that to a new Email Connector and save it, then check if it saved ?
It was letting me add them, and they appeared fine when adding but the problem was they didn't stay when you clicked save in the new Email connector. When I went back in after saving they field was empty and the only way I could get it to save was keeping that field under 12 characters.

**Comment by markus101** [comment]
The tag input is the same for all locations, but I just tried that and it worked as well.
