### ISSUE TITLE
Neither 'update' nor 'clean' are removing original videos from Kodi

### ISSUE THREAD

**Issue by Spence1115** [Sonarr/Sonarr#1564]
When a TV show is upgraded, the original is not being deleted from Kodi, so I get duplicates even though the file no longer exists.

Kodi version 16
Sonarr version 2.0.0.3357

What logs would help with this?

**Comment by markus101** [comment]
> Sonarr version 2.0.0.3357

That build is over a year old (`2015-07-20`), first off, update Sonarr.

There is a known issue with this due to how Kodi handles the update and then clean https://github.com/Sonarr/Sonarr/issues/455 not something we can easily resolve at this time, but there is a workaround listed there.

**Comment by Spence1115** [comment]
Cheers. No idea how I got such an old version, it got a clean install recently and was set to auto update. Will try the workaround. Thanks.
