### ISSUE TITLE
Show not downloading despite being monitored and episodes are available

### ISSUE THREAD

**Issue by xcorp** [Sonarr/Sonarr#1569]
I'm monitoring the show Westworld among many others but this is the only one not working that I've discovered.

It's marked as monitored in the settings for the show, but the calendar shows it as gray and new episodes are not downloaded even if they are available with the right quality, see screenshots for clarification/proof.

http://imgur.com/a/eBULB

If you need any logs/databases for troubleshooting I'm happy to provide them, unfortunately I have no experience with dotNet so I have no idea where too look.

**Comment by supremacy2k** [comment]
You have to make sure, it's actually marked on the show it self.
Not in the setting for the show.

I just tested on Planet Earth, and it's monitored according to settings, but the "flag" on the show, is off, hence the show is gray in the calendar, and now monitored.

**Comment by xcorp** [comment]
Thanks, 
The show was monitored both on the "flag" and in the settings (I think this is the same setting), but the season wasn't.

**Comment by supremacy2k** [comment]
Yeah the setting and show flag is the same thing, but not the seasons. (Oddly enough)
But glad you got it solved. :)
