### ISSUE TITLE
Unable to recognize an Episode for Marvel's Daredevil

### ISSUE THREAD

**Issue by iFredOS** [Sonarr/Sonarr#1573]
This is for a specific episode:

Marvel's Daredevil - S02E11 - .380 [WEBDL-1080p].mkv

I think Sonarr have a problem with the ".380"

Funny! Because Sonarr did the rename and moved the file but cannot recognize it.

![marvel s daredevil](https://cloud.githubusercontent.com/assets/732811/20944483/a7eae9e0-bbd1-11e6-868c-c830214787c4.png)

**Comment by markus101** [comment]
Probably related to https://github.com/Sonarr/Sonarr/issues/457 You can check the logs to confirm that.

> Funny! Because Sonarr did the rename and moved the file but cannot recognize it.

If the file was later not available Sonarr would need to re-parse it to discover it again, Episode history should indicate that.

**Comment by iFredOS** [comment]
I tried to everything and still don't work. I tried to move the file out, manual import, automatic import. Moved the file back in the folder, scan for it. Renamed the file. It change nothing.
