### ISSUE TITLE
SIGSEV crash on Ubuntu 14.04 with Mono 3.10.0

### ISSUE THREAD

**Issue by theotherp** [Sonarr/Sonarr#1574]
```
Stacktrace:


Native stacktrace:

        mono() [0x4b3f7c]
        mono() [0x50c30f]
        mono() [0x423637]
        /lib/x86_64-linux-gnu/libpthread.so.0(+0xfc90) [0x7fccfc14bc90]

Debug info from gdb:


=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

./startNzbDrone.sh: line 2:  7477 Aborted                 (core dumped) mono NzbDrone.exe
```

I didn't find the dump or any log files containing more info. If you tell me where I could find them I can post them. This is the first time it happened on a system that hasn't been changed in months.

**Comment by markus101** [comment]
Please open a thread on the forums with [trace logs] (https://github.com/Sonarr/Sonarr/wiki/Log-Files) leading up to and including the crash. It may be easier to capture standard output and standard error since Sonarr may be unable to log when mono crashes.
