### ISSUE TITLE
Proc Title

### ISSUE THREAD

**Issue by depraved22** [Sonarr/Sonarr#1576]
I'm trying to get the proc title changed somehow so I can monitor via the process name better.

If I look at anything running mono, it has the "Main" as the Process Name:

```
root@plex: ~# ps -ef | grep -i drone
felix     4044     1  7 09:51 ?        00:00:02 /usr/bin/mono /opt/NzbDrone/NzbDrone.exe -nobrowser
root      4168  3911  0 09:51 pts/1    00:00:00 grep -i drone
root@plex: proc# cd 4044
root@plex: 4044# cat status
Name:	Main
State:	S (sleeping)
Tgid:	4044
Ngid:	0
Pid:	4044
```

I've done some searching but can't tell if this is possible at all in mono so I figured I'd ask.

**Comment by markus101** [comment]
There is another issue that has a linked PR: https://github.com/Sonarr/Sonarr/issues/290 (closed, but might be something for v3), I'm not sure if it changes the name or not though.
