### ISSUE TITLE
Episode monitored status being reset

### ISSUE THREAD

**Issue by larrybeall** [Sonarr/Sonarr#1582]
So I took the plunge today and converted from SB to Sonarr.  Everything is working great except one minor thing.  When I imported my collection everything came over and it found a number of episodes that I no longer had on disk.  This of course made sonarr thing that they were wanted/missing episodes.  So I went through every one of my TV shows afflicted with this issue and change the monitor status at the season level.  Everything looked great, I came back this evening and it appears the season level monitor status is saved, but all of the episode monitor status have been flipped back on.  What can I do to prevent this? Or am I going about this situation the wrong way?

**Comment by markus101** [comment]
Please use the forums for support.

We'll need to see debug logs of a series refresh of the affected series as well as the requested information when opening the thread.
