### ISSUE TITLE
Error on download client response

### ISSUE THREAD

**Issue by margaale** [Sonarr/Sonarr#1586]
This week I've been playing with the code to add support for download station (Synology), I know there is an open pull request for this but I wanted to give It a try by myself. When I build the request using your client (not restsharp) after executing it I get an exception thrown at the part that it tries to create an encoding for the response data. It is happening because, after extracting it from the header, the content type is set to \\"utf-8\\". If I not mistaken that's the usual form of encoding the header, at least as i recall it happended to me before, with the extra slashes. I'm asking because it seems weird to me that it hasn't been reported to you before.... If it's an error I can fix it, if not please tell me how can I deal with it. 

Regards,

**Comment by margaale** [comment]
Sorry, the slashes where removed when posting. \\"utf-8\\"

**Comment by markus101** [comment]
What's the actual header value on the wire? Fiddler or Charles Proxy both should be able to intercept that and confirm. `\"` is expected in strings that contain slashes, to escape the slash, but the header value having slashes seems non-standard.

`utf-8 isn't a content type, `application/json` or `text/html` would would, `uft-8` is a `charset`.

**Comment by margaale** [comment]
Yeah, sorry, the actual response is content type set to text/plain and the charset set to utf-8. I'm at work right now, when i get home i'll try with postman to see what is the response but i'm pretty sure that there are the extra slashes in there because i debugged the code and i saw the expception being thrown in Encoding.GetEncoding method in the Content property of the response.

**Comment by margaale** [comment]
Checked with fiddler and postman, this is what they both show :

Server: nginx
Date: Wed, 14 Dec 2016 21:42:28 GMT
Content-Type: text/plain; charset="UTF-8"
Transfer-Encoding: chunked

There were no slashes, only the extra ".

Obviously adding  
`charset = charset.Replace("\"",""); `

after line 147 in Sonarr\src\NzbDrone.Common\Http\HttpHeader.cs fixes my problem, but is it the right fix to do?

**Comment by markus101** [comment]
Ahh that makes sense since we're looking up the encoding based on that value and it's not expected to be wrapped in quotes.

Yeah, I think that's probably the easiest fix for it, unless @Taloth has another suggestion.

**Comment by Taloth** [comment]
The http standard specifies the charset should be a `token`, an unquoted string. So strictly speaking charset="UTF-8" is not allowed. Although I didn't check all the relevant revisions.

I'm not too opposed to the workaround, it seems fairly harmless, but I would first like to know what is the source of the headers.
Also, the `text/plain` concerns me, it seems to be a wrong content type for the kind of data we handle.

Is the Download Station emitting this or is there an nginx proxy inbetween? What kind of data are we talking about... json? If so then I find the `text/plain` troubling, if Download Station emits that then a developer over there was rather lazy.

**Comment by margaale** [comment]
No proxy in between, all this is in my home network. I guess that the ngnix line that you see in there is the webserver handling the requests in my synology. And yes, it returns a json even when the content-type says text/plain so i had to call Json.Deserialize by hand at the proxy class. I'm gonna try sending the Accept header with json to see if it makes any difference...

**Comment by Taloth** [comment]
Well... https://forum.synology.com/enu/viewtopic.php?t=92064
I'll assume it's just a crappy Synology implementation that they haven't bothered to fix.
The synology forum seems to have more threads about syno being unwilling to fix api issues in general.

If you want to submit a PR, please include a UnitTest (which we seem to have skipped when GetEncodingFromContentType was first written).

**Comment by margaale** [comment]
Done. It's my first pull request so be patient with me please.

**Comment by margaale** [comment]
Already did the requested changes in pr. Did you have time to check them?

**Comment by Taloth** [comment]
Markus was reviewing it so I kinda kept out of it. But it looks good, merged it in.

Tnx for adding the tests btw. It helps preventing a regression in the future.
