### ISSUE TITLE
x264 tag always applied to rename

### ISSUE THREAD

**Issue by d2dyno** [Sonarr/Sonarr#1591]
I have a file, with the mediainfo below, that when renamed by Sonarr (and has the {MediaInfo Simple} tag), is renamed with 'x264'. Even though this file is unencoded.

So the file name by Sonarr is:

> Marvel's Jessica Jones S01E01 - AKA Ladies Night 1080p BluRay x264 DTS.mkv

But it should be something like

> Marvel's Jessica Jones S01E01 - AKA Ladies Night 1080p BluRay AVC DTS.mkv

Mediainfo (just video stream):

> Video
> ID                          : 1
> Format                      : AVC
> Format/Info                 : Advanced Video Codec
> Format profile              : High@L4.1
> Format settings, CABAC      : Yes
> Format settings, ReFrames   : 4 frames
> Codec ID                    : V_MPEG4/ISO/AVC
> Duration                    : 51 min 56 s
> Bit rate mode               : Variable
> Bit rate                    : 21.6 Mb/s
> Maximum bit rate            : 33.0 Mb/s
> Width                       : 1 920 pixels
> Height                      : 1 080 pixels
> Display aspect ratio        : 16:9
> Frame rate mode             : Constant
> Frame rate                  : 23.976 (24000/1001) FPS
> Color space                 : YUV
> Chroma subsampling          : 4:2:0
> Bit depth                   : 8 bits
> Scan type                   : Progressive
> Bits/(Pixel*Frame)          : 0.435
> Stream size                 : 7.84 GiB (89%)
> Title                       : MPEG-4 AVC Video / 22003 kbps / 1080p / 23.976 fps / 16:9 / High Profile 4.1
> Language                    : English
> Default                     : Yes

**Comment by Taloth** [comment]
They're the same thing. https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC
In the industry the identifier X.264 is most common, then H.264 and finally AVC, but they essentially mean the same thing.

Also... X.264 vs H.264 can't be determined from MediaInfo, if there's a h264 in the title it will preserve it otherwise it will assume the open-source encoder x264.

**Comment by RollingStar** [comment]
Shouldn't they just be all renamed to h.264 / h264 / AVC then (unless the original filename specifies x264)? Those would all be accurate descriptions of the media -- x264 is just an implementation of the spec.

https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC#Naming

**Comment by Taloth** [comment]
We do it the other way around because x264 is by far the most common implementation used. So if the filename contains h264 it will keep it, otherwise it will be x264.

**Comment by markus101** [comment]
Closing as this is intentional behaviour.

**Comment by d2dyno** [comment]
x264 is a piece of software, H.264 a standard. H.264 is to PDF what x264 is to Adobe Acrobat, x264 is software, that encodes videos that are H.264 compliant. think ... H.264/x264/VLC <---> HTML/Microsoft Frontpage/Google Chrome
HTML is a standard, Microsoft Frontpage can write HTML code for you, and Google Chrome is the "player".

**Comment by leonelwilliams** [comment]
C'est la vie
