### ISSUE TITLE
Sonarr on Synology DS416play

### ISSUE THREAD

**Issue by isalas16** [Sonarr/Sonarr#1594]
Hi,

I've been using sonarr on my synology for over 6 months without issues, this week however the sonarr services stops upon media scan, I've unninstall mono and sonarr, re-install and the issue remains, doest matter if I add 1 show or 100 it always stops, if I dont add any shows the service runs fine, but that kind of defeats the point of having sonarr.

Sonarr version is 20150731-8
Mono version is 4.6.2.7-8 
Both from the synocommunity repository.

I also tried installing the official mono from syno but when I try to install sonarr it install community mono as well.

anyone experienced this before? or have any suggestions I can take? thanks.

**Comment by markus101** [comment]
Please use the forums for support, looks like this is may be related to the (mono update] https://forums.sonarr.tv/t/sonarr-on-synology-stopped-working-after-mono-update/13048) if not open a new thread with the requested logs.
