### ISSUE TITLE
(Noob) Please someone explain why Sonarr is not grabbing my missing episodes automatically

### ISSUE THREAD

**Issue by achandab** [Sonarr/Sonarr#1596]
I read the following and still don't fully understand. 

https://github.com/Sonarr/Sonarr/wiki/FAQ

Why doesn't Sonarr automatically search for missing episodes?

My Sonarr has been offline for about a week or so. I ran a manual search on series and it managed to grab missing episodes from 3 seasons back. My question is if i didnt run this search manually would it of eventually fetched those episodes?

**Comment by markus101** [comment]
Please use the forums for support.

How Sonarr finds episodes is explained in the FAQ.

> My question is if i didnt run this search manually would it of eventually fetched those episodes?

If they appeared on an RSS feed again when Sonarr was running, yes (things do get reposted), but the quickest way to find them in this case is search.
