### ISSUE TITLE
"The 100" files not being seen

### ISSUE THREAD

**Issue by d2dyno** [Sonarr/Sonarr#1597]
I have files for every episode, for all 3 aired seasons of the show "[The 100](http://www.thetvdb.com/?tab=series&id=268592)". However, in Sonarr, it cannot see any of those files. I tried changing the parent directory from "The 100" to "The_100", tried deleting the show from sonarr, restarting sonarr then adding the show back. No matter what, Sonarr is not seeing files for this show. Not sure what to do.

When Selecting the directory for Sonarr to attach to for this show, I can see the 3 directories under "The 100" for each season (Season 1, 2, 3). So I believe it knows there are folders there.

**Comment by markus101** [comment]
Please use the forums for support. We'll need to see debug logs of Sonarr rescanning that folder (refreshing from the series page), the issue is likely related to: https://github.com/Sonarr/Sonarr/issues/457
