### ISSUE TITLE
Unable to parse episodes from release name

### ISSUE THREAD

**Issue by lattedesu** [Sonarr/Sonarr#1599]
Hello,

I've been struggling to parse release names over sonarr

It's "P lanet earth II"

This is the file names

> P lanet Earth II 2016 E01 1080p BluRay DD5.1 x264 VietHD

And this is the release name:

> P lanet.Earth.II.2016.1080p.BluRay.DD5.1.x264-VietHD

I'm trying to fetch the season pack from a certain bittorrent tracker. Changing type to daily or anime didn't help.

Any clue would be appreciated. 

Thanks in advance,

**Comment by markus101** [comment]
Please use the forums for support.

Sonarr can parse `P lanet Earth II 2016 E01 1080p BluRay DD5.1 x264 VietHD` (The space between `P` and `lanet` doesn't matter, but the extraneous `2016` will mean it won't match to the correct series without an alias being added for that series. https://forums.sonarr.tv/t/scene-naming-tvdb-naming-conflicts/137

`P lanet.Earth.II.2016.1080p.BluRay.DD5.1.x264-VietHD` is meaningless to Sonarr though. Sonarr requires the season number to be part of the release name for season packs (either `S01` or `Season 01`) so this is not something Sonarr can handle.

**Comment by lattedesu** [comment]
Thanks @markus101 , I thought this was a bug so I wanted to move here directly.

Thanks you for the prompt response.

Cheers,
