### ISSUE TITLE
Request: Custom search format per indexer?

### ISSUE THREAD

**Issue by MisterC925** [Sonarr/Sonarr#1602]
I have an indexer added through Jackett that doesn't always like the queries from Sonarr.

For example:
"[SHOW TITLE] [YEAR] [SxEx]" does not work but "[SHOW TITLE] [SxEx] [YEAR]" does.

It would be nice to have a way to specify the query format per indexer.

Thanks!

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
This is something Jackett should handle as Sonarr is sending the season and episode number as separate parameters to Jackett (you can see the URL Sonarr is hitting in Sonarr's debug logs).

**Comment by markus101** [comment]
Originally I thought the difference was between S01E01 style releases vs 1x01 releases, but I see issue is the year.

Re-reading this and I realized I read it wrong originally, but this looks more like a naming problem than how Sonarr is searching. Sonarr includes the year if it is part of the series title, it doesn't include it if it is not. If releases are moving the year after the season + episode numbers then that seems wrong (why the year is included at all is weird in that case) and should be included as part of the series title or not at all. If releases are typically don't have the series title, then that is a valid use for https://forums.sonarr.tv/t/scene-naming-tvdb-naming-conflicts/137, but if it's just this indexer that's changing it or it conflicts with another series we'd be unlikely to add it.
