### ISSUE TITLE
[Feature Request] Allow the use of rclone

### ISSUE THREAD

**Issue by DTrace001** [Sonarr/Sonarr#1605]
As amazon cloud and google drive have become more and more popular. People are mounting them and storing their videos on those drives/mounts. A nice feature would be to use "rclone" to copy the videos over to ACD or GD vs using normal "cp" or "mv".  This will avoid a lot of IO errors and would allow for retries on errors etc.

**Comment by Taloth** [comment]
These kind of things are best dealt with using layered/hierarchical filesystems. Those can use local caching and transfer new files to the cloud asynchronously while remaining completely transparent to the application.
One example I recently heard about was someone using a combination of unionfs, acdfs, rsync + cronjob to make that work. There was a bug in acdfs that caused it to lose connection on rare occasion, but acdfs is written in python... somebody gotta be able to debug that.

_PS: ACD is only viable up to (for example) 2TB or so in the cloud for the current pricing. Above that it costs em money and given enough excessive users the hammer will go down. I've heard about ppl storing dozens of TB in ACD, it's unrealistic to expect that'll last. Better to compare with pay-per-usage storage solutions and decide what's realistic. But then again, ACD shouldn't advertise 'Unlimited'._

**Comment by markus101** [comment]
No plans to support rclone for importing at this time.
