### ISSUE TITLE
Remove Piwik user tracking - breach of privacy

### ISSUE THREAD

**Issue by khromov** [Sonarr/Sonarr#1607]
The web UI sends tracking data to a [Piwik](https://piwik.org/) instance at http://piwik.sonarr.tv/

Tracking users like this should be opt-in, please either remove it or at least provide a simple way to turn it off.

**Comment by delphiactual** [comment]
`settings` -> `general` -> `analytics` off

**Comment by khromov** [comment]
Thanks!
