### ISSUE TITLE
Reordering via drag/drop not working in profiles

### ISSUE THREAD

**Issue by rcdailey** [Sonarr/Sonarr#1609]
I'm running Sonarr version 2.0.0.4472. The drag/drop ability of qualities in a profile is no longer working. It was working last I used it, a couple of releases ago. I tested in latest Chrome and Firefox. I am not able to reorder qualities in a profile now.

**Comment by Taloth** [comment]
You need to have Advanced Settings enabled for the drag-handles to show up.
