### ISSUE TITLE
Plex Transcoder merge / copy

### ISSUE THREAD

**Issue by Rycochet** [Sonarr/Sonarr#1610]
Plex now has the ability to pre-transcode media to improve streaming (very useful on a low powered NAS etc), and while there are various scripts around that can all do the same thing, Plex makes it almost one-click and simple (plus it's the final output for itself, so doesn't need to be tweaked and tested first).

The idea is similar to the Drone Factory, but with a few minor differences:

* The files are within the media folder, either<br>`/Plex Versions/<show name>/<encode type>/S00E00.mp4` or<br>`/<show name>/Plex Versions/<encode type>/S00E00.mp4`<br>(ie, give a path to scan, or look for the `Plex Versions` folder within the show folder when scanning).
* There may be other folders within this (such as `.inProgress`), but it's only the files that are relevant.
* The option would need to know what quality to replace the main file with (ie, encode type = "`Optimised for Mobile`" etc) - this version would replace the original regardless of quality change.
* Any types other than the chosen one would be left alone and not copied over (so multiple versions could exist if wanted - the original reason for the Plex Transcoder option).
* This would be a **copy** action, the transcoded file left alone for Plex to deal with when updated. The original episode should be deleted after the new file is copied next to it.
* Note: If the original file has the same `.mp4` file extension, then the copy needs to use a `.m4v` extension (Plex doesn't look at size / hash / date, just filename apparently).
* When Plex finds an episode that isn't "correct" on TheTVDB etc then the transcoded version is named with a date instead of an episode number - so should probably be left alone.

I'm almost half way through encoding 60k episodes / 35tb and manually copying them over (three months down so far...), and this would probably be of use to quite a few people ;-)

**Comment by markus101** [comment]
I'm not sure what you're asking for here.

- Sonarr doesn't currently support multiple files for the same episode https://github.com/Sonarr/Sonarr/issues/312
- Drone Factory isn't recommended for importing (and planned for removal in v3, but the underlying processing will be available in the API).

**Comment by Rycochet** [comment]
Plex supports multiple copes that it has made itself - so the first thing is for Sonarr to totally ignore the "`/Plex Versions`" folder whenever it's found (ie, not part of the replacing part) as that will contain the different versions.

Drone Factory can't do this - even if copying to the import folder for it, the transcodes are generally the same quality or lower (ie, I make sure all my TV Shows are 720p, but the original might have been 1080p, might be a different container, or might just have been remuxed so it's an almost identical file that's just better for streaming) - so Drone Factory refuses to replace them. In addition without the `mp4` to `m4v` extension replacement Plex won't realise it's a different file and will keep the transcoded version.

**Comment by markus101** [comment]
> Plex supports multiple copes that it has made itself - so the first thing is for Sonarr to totally ignore the "/Plex Versions" folder whenever it's found (ie, not part of the replacing part) as that will contain the different versions.

That's certainly possible.

I don't understand what Drone Factory has to do with this at all, or what Drone Factory-like solution you want implemented. What is the end goal here? If Sonarr doesn't see the optimized versions it would only be managing the file it imported.

**Comment by Rycochet** [comment]
It's that I want to only have one copy - so replace the original one already in the library with the new one - Drone Factory has two issues with doing it for Plex:

1. The quality may be lower so it'll skip importing it and replacing the original.
2. The temporary files are also in there, and they may match something that they're not meant to (so shouldn't be scanned).

There's also the fact that it's due to be removed in the future ;-)

**Comment by markus101** [comment]
> There may be other folders within this (such as .inProgress), but it's only the files that are relevant.

Within the `/Plex Versions/` folder or it's another folder under the series folder?

I still don't see what Drone Factory has to do with this, if the file is already in the series folder (in the `/Plex Versions/` folder) and Sonarr ignores that folder there is nothing to do.

Do you want the optimized version to replace the version Sonarr imported/is already there?
What are you expecting Sonarr to import? It's not going to import lower-quality episodes automatically.

**Comment by Rycochet** [comment]
When telling Plex to do it you get a choice of where - within the global folder for shows (ie, where Sonarr is told to add new shows), or within the show's own folders (I don't use it, but it might be within the season rather than the show - quite happy to test if wanted).

Sonarr directly needs to ignore the `Plex Versions` folder completely as anything inside there will be a duplicate episode.

> Do you want the optimized version to replace the version Sonarr imported/is already there?

Yes :-)

The request is specifically for it to import the new episodes regardless of quality as (if the option is turned on) it's there because people are wanting to keep "fixed" versions of the files for streaming (and possibly filesize).

Drone Factory is being used for an example because it's there already and I've tried to state where it can't do the job itself (otherwise I'd just point it at the `Plex Versions` folder and let it).

**Comment by markus101** [comment]
Ahh I understand now. I don't see this as being something we'll support directly, though it could be achieved using manual import and forcibly importing episodes even though the quality is lower. Adding Drone Factory-like functionality while Drone Factory is deprecated and planned to be removed seems like a bad idea and and option to ignore the quality using the API command that backs Drone Factory (which is staying) seems a bit overreaching since it could be misused and would require a lot of circumventing to ignore that during processing that isn't worth it.

Using the same approach as Manual Import (processes the files in the folder and gives a report whether it can be imported or not) and then telling Sonarr to import it anyways (two steps) seems like the best solution for someone with the want for that functionality and a bit of knowledge to query the API.

I see two things coming out of this:

1. Ignore the `Plex Versions` folder (similar to how Sonarr ignores the `Extras` folder)
2. Document the manual import API endpoints so it can be used in 3rd party scripts

**Comment by Rycochet** [comment]
Sounds good :-)

Just for completeness - here's the link to the Plex request for the replacing the original copy (over a year old now) - https://forums.plex.tv/discussion/comment/1190020

**Comment by markus101** [comment]
Issue opened for the API Docs: https://github.com/Sonarr/Sonarr/issues/1631
