### ISSUE TITLE
Latest Develop update (5/1/2017) Maintenence update

### ISSUE THREAD

**Issue by seed1234** [Sonarr/Sonarr#1611]
The latest update broke the Web UI access 
I have tried reinstalling sonarr on freenas throgh the plugin page
it runs after the install but when i update sonarr throgh develop channel ,The Web UI cannot be accessed

I am running Sonarr onFreeNAS-9.10.2 (a476f16)

nzbdrone log
http://pastebin.com/6SpqPeHF

sonarr log
http://pastebin.com/wTTXUD0e

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by brainykale** [comment]
Same issue here, running on QNAP 4.3 and Mono 4.6.2.  Rolling update back results in Sonarr working again.

**Comment by seed1234** [comment]
Can we get a fix for this cause i do not have a snapshot saved for sonarr

**Comment by brainykale** [comment]
@kayone Thanks, any chance of a develop branch push for this fix specifically?

**Comment by markus101** [comment]
Commits to develop result in builds for develop, it'll be there eventually (how ever long it takes to build and run tests).

**Comment by brainykale** [comment]
Thanks @markus101, I'll keep an eye out

**Comment by markus101** [comment]
> New version of Sonarr: 2.0.0.4503 (develop)

**Comment by brainykale** [comment]
Installed, issue confirmed resolved.

Thanks everyone, awesome response to this issue
