### ISSUE TITLE
One click option to search all individual episodes in season/show

### ISSUE THREAD

**Issue by ebalders** [Sonarr/Sonarr#1613]
Would like to be able to click a button on a season or show to search for all episodes in a show/season, evaluating each episode on it's own.

I currently have better results doing an automatic search on each episode vs an automatic search for the show/season.

**Comment by markus101** [comment]
Each episode is evaluated on it's own as well as within any season packs returned. Sonarr asks for all episodes in the season, it's up to the indexer's to handle that and return season packs + individual episodes (if available). Also make sure all episodes are monitored as unmonitored episodes in a series/season search are ignored. We have no plans to search for each episode individually when performing a series/season search.
