### ISSUE TITLE
Unable to parse episode info from <path>

### ISSUE THREAD

**Issue by DrSeussFreak** [Sonarr/Sonarr#1615]
Have a large amount of files formatted with the proper naming convention for the series, but when I have Sonarr scan the directory, I receive "Unable to parse episode info from path X:\Kids TV\Name\Name - 1930x10.avi".

**Comment by markus101** [comment]
This should already be fixed in the latest develop releases (2.0.0.4511), but not yet in the main release branch (no ETA on when it will land there).

If you're on `2.0.0.4511` already, we'll need to see trace logs of a series refresh.

**Comment by DrSeussFreak** [comment]
I am on "Sonarr Ver. 2.0.0.4472", I worked around the issue, but will switch to the dev branch to gain the benefit.
