### ISSUE TITLE
Sonarr pulling incorrect series - TV Series Taboo (2017)

### ISSUE THREAD

**Issue by starwarz99** [Sonarr/Sonarr#1616]
I had setup the new FX series Taboo in Sonarr, but it is pulling the schedule and files for a National Geographic series of the same name that began in 2002.  The graphics and information in Sonarr retrieves the new FX series, but the files and schedule appear to be the National Geographic one. 

I've not seen this before with any other series, so I assume this is a bug.

**Comment by markus101** [comment]
I see you already opened this up on the forums as well (the correct location for support).

https://forums.sonarr.tv/t/setup-new-fx-series-taboo-grabbing-national-geographic-series-instead/13325
