### ISSUE TITLE
Sonarr not detecting episode (sense8 special)

### ISSUE THREAD

**Issue by sigboe** [Sonarr/Sonarr#1617]
![image](https://cloud.githubusercontent.com/assets/2087930/21950241/21d4b05c-d9f9-11e6-90e7-599f283ff337.png)
![image](https://cloud.githubusercontent.com/assets/2087930/21950268/63b4d560-d9f9-11e6-9302-623327dc48c4.png)

Hoping that sonarr can in the future handle this better. thetvdb is not always correct. **Why can't I click the manual download?** maybe this can be handled better, or allow me download the file? Thanks 😃

**Comment by markus101** [comment]
This is already tracked, but not currently a priority.

https://github.com/Sonarr/Sonarr/issues/395
