### ISSUE TITLE
Enable Sonarr to monitor and replace Plex DVR recordings

### ISSUE THREAD

**Issue by markhaines** [Sonarr/Sonarr#1625]
Is it possible to somehow setup Sonarr to monitor a folder containing Plex DVR recordings and replace them with 'proper' downloaded versions of TV shows once they become available?

I currently have Plex record DVR shows to a separate folder but this isn't mandatory. It would mean that I could use the DVR feature to record shows and could suffer ads etc if want to watch it straight away ;-) but by the time I get round to watching most shows I'd have a proper HD rip waiting for me.

Would be a useful feature if not already possible!

**Comment by markhaines** [comment]
Did some more investigation on this: 

So I pointed Sonarr at an example DVR'd TV show and it's detected it and identified it as HDTV-720p (which it is). So in theory if there is a Web-DL 720p version released it will get replaced.
I'm not sure I can use this reliably with UK TV shows though as most of the downloaded versions are also HDTV-720p - but edited with the correct start / stop point and the adverts removed. If I set Plex DVR up to grab it OTA then Sonarr won't know to overwrite the OTA version with the 'edited' version... I guess you'd need to be able to either set Plex to add a 'tag' to the filename (?) to denote a new, lower, quality HDTV-720p-OTA (for example) that could then be replaced by HDTV-720p or a feature in Sonarr to be able to ID this content another way and do the same.

**Comment by markus101** [comment]
> So in theory if there is a Web-DL 720p version released it will get replaced.

Correct, the process is the same whether it was grabbed by Sonarr or not. The only way to avoid that would be to lower the quality, which would either require the filename to be changed to indicate a lower quality or overriding it via manual import, both of which would require a script to do it. You could also look at setting up comskip to flag to commercials, so Plex sees them as chapters you can skip or to remove them completely.
