### ISSUE TITLE
Sonarr on Qnap TS431 won't start

### ISSUE THREAD

**Issue by jul1792** [Sonarr/Sonarr#1626]
Hi there,

I installed Sonarr 2.0.0.4389 and Qmono 4.6.2.7 on my Qnap TS431 with QTS4.3.2 Beta. But Sonarr doesn't start. Everytime I click on the Open Button a new tab opens and it says the server can not be reached. 

I already tried installing and starting every version I found of Qsonarr and Qmono, but nothing helped. Then I upgraded to QTS 4.3.2 (before it was 4.2.2) but that didn't change anything.

I would love to show you the logfiles but I don't know in which directory on my Qnap they are located.

Does anyone have any solutions?

**Comment by markus101** [comment]
Please use the forums for support.
