### ISSUE TITLE
Series missing scene information start searching Season 0

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1627]
Pawn Stars is the issue in this case.

UI message:
![image](https://cloud.githubusercontent.com/assets/413544/22037887/e7ff9862-dcad-11e6-82dd-04eb511b1227.png)

Missing Scene info:
![image](https://cloud.githubusercontent.com/assets/413544/22037896/eafe8bea-dcad-11e6-8d41-b9a62539cd3c.png)

Has Scene info:
![image](https://cloud.githubusercontent.com/assets/413544/22037904/ee6c51f4-dcad-11e6-8179-925f634330ef.png)

The end result is a special from years ago gets picked up and sent to the download client.

Search results:

<img width="987" alt="screen shot 2017-04-17 at 12 04 58 pm" src="https://cloud.githubusercontent.com/assets/172505/25094645/26b0cbea-2366-11e7-923f-a4b56d753a6a.png">

**Comment by limetime** [comment]
Can confirm this is also the case for Dexter's Laboratory.  A season pack cannot be matched as a result.  Happy to provide any logs should devs require it for testing.  Thanks.
