### ISSUE TITLE
Provider request

### ISSUE THREAD

**Issue by Noorbertt** [Sonarr/Sonarr#1632]
Hi guys,

Maybe there is a way to import this (see the link) CouchPotatoProvider ? 
https://github.com/gala132/nCoreCouchPotatoProvider

Many Thanks :)

**Comment by Dnkhatri** [comment]
Ncore is already supported through cardigann https://github.com/cardigann/cardigann
And jackett https://github.com/Jackett/Jackett

**Comment by markus101** [comment]
They don't actually have an API, the all the methods listed here employee screen scraping, which we won't do.

**Comment by Noorbertt** [comment]
Jackett doing very odd thinks..:)
Thank you , I still love Sonarr
