### ISSUE TITLE
Move prefer "Torrents" vs "Usenet"

### ISSUE THREAD

**Issue by mommalongnips** [Sonarr/Sonarr#1633]
Not sure what the logic behind putting the perfer torrents vs usenet under "Profiles" was. But wouldn't it make a lot more sense to put this under indexers? 

Took me WAY more time than it should to find this.

**Comment by markus101** [comment]
Because it's a _Delay Profile_, making Profiles the most fitting place (and less things jammed into Indexer Settings). I don't see this being moved and could even see restrictions being moved since they are profile-like (and find them on indexer's a bit odd at times).

**Comment by ilovedudes69** [comment]
I am in agreeance with @mommalongnips , I have been lost multiple times looking for this setting after setting up a new server, or when I migrate. I do not understand why this is in a profile, this is a download client specific item, and should reside along with those other specific download type items.

Just my 2 cents. Maybe a symlink type thing on the UI that could help direct to this page?

**Comment by markus101** [comment]
I think the bigger issue here was it was an advanced setting (and no reason for it to be advanced). I've pushed a fix to make it a regular setting instead of advanced. No plans to move it to another page at this time.
