### ISSUE TITLE
Unable to parse episode from release name

### ISSUE THREAD

**Issue by zarmstrong** [Sonarr/Sonarr#1636]
Sonarr is unable to parse certain releases due to non-standard release name.

Example:  

**Series:** Planet Earth (2016)
**Episodes (most of them have this example):**  Planet.Earth.Ep05.Deserts.2006.720p.BluRay.DTS.x264-ESIR

**Comment by markus101** [comment]
That looks like it's from the original Planet Earth series.

This format should be parsable but conflicts with absolute episode parsing, so not something we can support at this time, I made a note to an existing issue to support it.

https://github.com/Sonarr/Sonarr/issues/457
