### ISSUE TITLE
Cross-contamination of missing queue sort settings from Radarr to Sonarr

### ISSUE THREAD

**Issue by rodti** [Sonarr/Sonarr#1637]
For info, I've also raised this as [issue 379 against Radarr](https://github.com/Radarr/Radarr/issues/379) in case a fix is required on both sides. 

I noticed that the Missing tab of the Wanted section in my Sonarr install isn't loading. In the Sonarr logs I receive the following error:

Request Failed: Instance property 'inCinemas' is not defined for type 'NzbDrone.Core.Tv.Episode'

The 'inCinemas' part of this error seemed more relevant to Radarr.

I went into my Radarr install and changed the Missing sort order to by physical release. Sonarr now gives this error:

Request Failed. GET /api/wanted/missing: Instance property 'physicalRelease' is not defined for type 'NzbDrone.Core.Tv.Episode'

The detail from the trace log for these is:

logs/sonarr.trace.txt:17-1-22 11:56:07.6|Trace|Http|Req: 206 [GET] /api/wanted/missing??page=1&pageSize=15&sortKey=inCinemas&sortDir=desc&filterKey=monitored&filterValue=true
logs/sonarr.trace.txt:[v2.0.0.4472] System.ArgumentException: Instance property 'inCinemas' is not defined for type 'NzbDrone.Core.Tv.Episode'

It looks like somehow these sort settings are leaking out of Radarr or being pulled into Sonarr and breaking the latter.

Develop build 2.0.0.4545 for Sonarr and develop build 0.2.0.196 for Radarr.

**Comment by galli-leo** [comment]
The fix is required on our side. For now you just have to change the sorting in Radarr to title or something that's also present in Sonarr.

**Comment by rodti** [comment]
Unfortunately, as far as I can see, there's no commonality between the user selectable sort orders in the two apps. The only common data column is 'Status', and that doesn't appear to have a sort option in Radarr. 

Although, thinking out loud, I suppose it could be sorted by Status in Sonarr....

**Comment by Taloth** [comment]
For those affected by the issue. in Chrome: F12. Application tab. Local Storage->http:/.../ item.
There you have a list of all settings stored in the browser. You can delete entries by rightclick.

As for a solution, the initial fix will need to be on Radarr's end. It also only happens when you use a reverse proxy to have sonarr & radarr on the same domain.

**Comment by galli-leo** [comment]
This is fixed in the latest release.

**Comment by rodti** [comment]
Yay! Really impressed by both projects, thanks for all your hard work.
