### ISSUE TITLE
items not showing on calendar

### ISSUE THREAD

**Issue by oziee** [Sonarr/Sonarr#1640]
So today Suits S06E11 comes out.. in the series info its lists as airing @ 12:00pm

but in the calendar it is not listed at all.. I had to manually set the ep to auto search for it to download

hard to know if any other shows are not showing in the calendar view

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
Please use the forums for support.

Sounds like the episode isn't monitored.

**Comment by oziee** [comment]
correct.. show season was not monitored
