### ISSUE TITLE
Bulk actions for Manual Import

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1643]
A page might work best (instead of modal), so a footer can be applied (like series editor/season pass) to make picking a series/season easier for multiple items.

**Comment by whiteatom** [comment]
agreed!!! I don't think it's a modal issue, just an ability to set the series and season to all checked items

**Comment by markus101** [comment]
This is addressed in the v3 UI work.

**Comment by desimaniac** [comment]
Can this be assigned a "milestones" tag so it can show up in the list?

**Comment by melikyuksel** [comment]
Can this be backported into v2? v3 is clearly not coming out anytime soon, and it's really annoying to choose episode names and seasons individually for tens of episodes.
