### ISSUE TITLE
Rename SeriesCleanTitle does not strip out all special characters

### ISSUE THREAD

**Issue by HiddenWolf** [Sonarr/Sonarr#1646]
My standard episode format is {Series.CleanTitle}.S{season:00}E{episode:00}.{Quality.Title}
For the show 'Allo 'Allo!, Sonarr proposes to re-add the special characters, where I would expect Allo.Allo.

**Comment by thezoggy** [comment]
`!` and `'` are special characters?

**Comment by Taloth** [comment]
@thezoggy It is a special char for scene, but not for anime.

I talked to markus yesterday about it, we suspect it has to do with xelra's anime rules. But we don't seem to have unittests verifying that behavior. A serious oversight imo.
The FileNameBuilder does have access to the series type, so in theory we could apply different rules for standard/daily vs anime.
Best route would be to write unittests for the various scenario's with at least one example for every special character replaced.

**Comment by alexanderkoch** [comment]
Scene only allows three non-alphanumeric characters.

`16) [ Directory Naming ]`
`16.1) Acceptable characters allowed for directories are:`
`ABCDEFGHIJKLMNOPQRSTUVWXYZ`
`abcdefghijklmnopqrstuvwxyz`
`0123456789._- `
From https://scenerules.org/t.html?id=tvx2642k16.nfo

Almost every other character (including but not limited to `!` and `'`) needs escaping in Linux

**Comment by thezoggy** [comment]
the 'scene' is not the only provider of content. and 'scene' releases get renamed by indexers using extracted metadata from files/nfo/etc due to obfuscation. so scene rules are not 100% to live by

**Comment by IsThisThingStillOn** [comment]
Dang, wrote the last comment with my wrong account. This is the quote @thezoggy is referring to:

> Scene only allows three non-alphanumeric characters.
> 
> `16) [ Directory Naming ]`
> `16.1) Acceptable characters allowed for directories are:`
> `ABCDEFGHIJKLMNOPQRSTUVWXYZ`
> `abcdefghijklmnopqrstuvwxyz`
> `0123456789._- `
> From https://scenerules.org/t.html?id=tvx2642k16.nfo
> 
> Almost every other character (including but not limited to `!` and `'`) needs escaping in Linux.

---

> so scene rules are not 100% to live by

I understand that, but file system "limitations" should be. And `CleanTitle` is inconsistent across Series and Episode.

Using this renaming pattern (not my actual):
`{Series.CleanTitle}.S{season:00}E{episode:00}.Episode.Title--{Episode.Title}-Episode.CleanTitle-{Episode.CleanTitle}`

Results in:
`You're.the.Worst.S03E03.Episode.Title-Bad.News-.Dude's.Dead-Episode.CleanTitle-Bad.News.Dudes.Dead.mkv`

The apostrophe for the episode title is removed, while it's kept/added for the series title.

**Comment by thezoggy** [comment]
lots of apps need the series name to match what its on the metadata provider.. otherwise it wont be scraped. removing characters could make it wrongly match another show.. `Betrayal` vs `Betrayal!`

**Comment by markus101** [comment]
Somewhat related is replacing `:` with `-` (from https://github.com/Sonarr/Sonarr/issues/1777). We should consider ` - ` instead of `-` in that case, but we'll want to know if it causes any issues (regardless of what we choose there there will be someone affected by it).

**Comment by markus101** [comment]
Closing in favour of https://github.com/Sonarr/Sonarr/issues/2028 which covers the same thing.
