### ISSUE TITLE
Dealing with formatting when importing existing shows from disk

### ISSUE THREAD

**Issue by HiddenWolf** [Sonarr/Sonarr#1647]
When starting to use Sonarr, a user might have a library previously set up somewhere.

When using the import from disk feature, it will not recognise shows if the folder name uses periods instead of spaces, or if a year is present.

Consider automatically stripping the formatting before running the search, to improve auto-detection of shows.

**Comment by markus101** [comment]
Covered by https://github.com/Sonarr/Sonarr/issues/918
