### ISSUE TITLE
Make size optional for Torrent RSS Feeds.

### ISSUE THREAD

**Issue by jasonm23** [Sonarr/Sonarr#1648]
When parsing RSS, documentation suggests that size is optional, however the parser rejects feeds which don't include a size.

I agree that size should be optional (although nice to have) and the code should be fixed.

I'm happy to submit a pull request to fix.

**Comment by markus101** [comment]
It is optional, you have to opt into that behaviour though.

![image](https://cloud.githubusercontent.com/assets/413544/22414720/9f4fd578-e676-11e6-8a4b-ba48ed742e4d.png)

**Comment by jasonm23** [comment]
Thank you
