### ISSUE TITLE
Add support for URL base to all download clients

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1651]
Reverse proxies that use a subfolder aren't usable when a download client is hiding behind it and we don't support a URL base for that download client.

We could either add a field to download clients for the URL base or look at combining protocol, host, port and URL base into one field (I recall discussing this before, but not sure if there is already an issue). The former could be hidden as an advanced setting so it's not always shown, but the latter is more flexible, but might be more confusing.

**Comment by dmwyatt** [comment]
FWIW, When adding indexers you just have a single url field.

**Comment by calebcall** [comment]
Has any progress been made on this.  Would be nice to be able to add my download client with the actual path instead of on the backend port.

**Comment by altryne** [comment]
Adding my 2 cents, this is currently limiting me from reverse proxying sab

**Comment by DivinityCycle** [comment]
+1, I have this issue as well.

The frustrating thing to me is that if Sonarr just gave a single space where you can input the correct & complete URL and then it just uses that single string whole-hog, that would actually work fine for what I'm doing. Hell, if the "Port" field wasn't subject to typecasting then we could just use that.
As it is, I tried hacking the sabnzbd config as it exists in my local nzbdrone.db to change my "port" value to "443/sabnzbd", but I'm getting typing errors like this now:
Could not convert string to integer: 443/sabnzbd. Path 'port', line 3, position 23.

Does "port" have to be an int?

If yes we'll need to add a new "basedir" setup field and then insert it into the URL when not empty. I haven't had a look at the code so I'm not sure how disruptive this will be, but on the face of it seems fairly straightforward.

**Comment by wonkieinc** [comment]
I'm also having issue with this. Moved my torrent client to Transmission running on an Ubuntu VM behind a VPN (Blocking all other traffic entirely for the user that Transmission runs under aside from Localhost) then reverse-proxied the WebUI so that it can be accessed only via 192.168.1.3/transmission

But now I am unable to utilise this with Sonarr.

**Comment by kappes** [comment]
have the same issue.

**Comment by vajonam** [comment]
+1 thanks

**Comment by markus101** [comment]
As always if you want to add your support (and don't have anything meaningful to add to the conversation), please add a reaction to the description/original post.
