### ISSUE TITLE
sonarr not working with jackett or torznab (just started happening after a year)

### ISSUE THREAD

**Issue by sethwarsh** [Sonarr/Sonarr#1652]
Jacket reports successfully being able to connect to all treackers but Sonarr cannot reach any through it just fails to connect on 0.0.0.0 or localhost, this problem just started with an upgrade  to jackett or sonnarr a few weeks ago. 

Im not sure whch logs would be best to post please advise and ill do so.

Its with all of my trackers

Thanks
Seth

Sonarrr and Jackett logs:

Sonarr:

Component	Message	Time
EventAggregator	HistoryService failed while processing [EpisodeGrabbedEvent]: database is locked database is locked	8:15pm
TaskExtensions	Task Error: database is locked database is locked	8:14pm
DownloadService	Report sent to Transmission. The Late Show with Stephen Colbert 2017 01 03 Oprah Winfrey 720p CBS WEBRip AAC2.0 x264-RTN	8:14pm
EventAggregator	HistoryService failed while processing [EpisodeGrabbedEvent]: database is locked database is locked	8:14pm
DownloadService	Report sent to SABnzbd. The.Late.Show.with.Stephen.Colbert.2017.01.31.Josh.Groban.Rachael.Ray.Japandroids.720p.CBS.WEB-DL.AAC2.0.H.264-monkee	8:14pm
Sabnzbd	Adding report [The.Late.Show.with.Stephen.Colbert.2017.01.31.Josh.Groban.Rachael.Ray.Japandroids.720p.CBS.WEB-DL.AAC2.0.H.264-monkee] to the queue.	8:14pm
TaskExtensions	Task Error: database is locked database is locked	8:13pm
TaskExtensions	Task Error: database is locked database is locked	8:12pm
NzbDroneErrorPipeline	Request Failed. POST /api/indexer/test: database is locked database is locked	8:12pm
NzbDroneErrorPipeline	[POST /api/indexer/test]: database is locked database is locked	8:12pm
TaskExtensions	Task Error: database is locked database is locked	8:11pm
TaskExtensions	Task Error: database is locked database is locked	8:10pm
NzbDroneErrorPipeline	Request Failed. POST /api/indexer/test: database is locked database is locked	8:10pm
NzbDroneErrorPipeline	[POST /api/indexer/test]: database is locked database is locked	8:10pm
TaskExtensions	Task Error: database is locked database is locked	8:09pm
DownloadDecisionMaker	Processing 7184 releases	8:09pm
FetchAndParseRssService	Error during RSS Sync: database is locked database is locked	8:09pm
TaskExtensions	Task Error: database is locked database is locked	8:08pm
Newznab	Indexer Dognzb.cr rss sync didn't cover the period between 1/21/2017 4:05:24 PM and 1/31/2017 2:33:35 AM UTC. Search may be required.	8:08pm
TaskExtensions	Task Error: database is locked database is locked	8:07pm
FetchAndParseRssService	Error during RSS Sync: database is locked database is locked	8:07pm
NzbDroneErrorPipeline	Request Failed. POST /api/indexer/test: database is locked database is locked	8:06pm
NzbDroneErrorPipeline	[POST /api/indexer/test]: database is locked database is locked	8:06pm
TaskExtensions	Task Error: database is locked database is locked	8:06pm
Newznab	Indexer NZBFinder.ws rss sync didn't cover the period between 12/20/2016 11:39:26 PM and 1/31/2017 11:42:00 AM UTC. Search may be required.	8:05pm
TaskExtensions	Task Error: database is locked database is locked	8:05pm
ConsoleApp	Address already in use. This can happen if another instance of Sonarr is already running another application is using the same port (default: 8989) or the user has insufficient permissions	8:04pm
Newznab	Indexer NZBgeek rss sync didn't cover the period between 12/21/2016 12:09:46 AM and 1/30/2017 7:58:54 PM UTC. Search may be required.	8:04pm
Newznab	Indexer Nzbs.org rss sync didn't cover the period between 12/21/2016 12:13:52 AM and 1/31/2017 7:25:21 AM UTC. Search may be required.	8:04pm
Newznab	Indexer NZBCat rss sync didn't cover the period between 12/20/2016 10:18:12 PM and 1/31/2017 6:55:00 AM UTC. Search may be required.	8:04pm
Torznab	Indexer HD4Free.xyz rss sync didn't cover the period between 12/20/2016 10:05:14 PM and 1/8/2017 11:57:25 AM UTC. Search may be required.	8:04pm
Newznab	Indexer NZBindex rss sync didn't cover the period between 12/20/2016 11:06:24 PM and 1/28/2017 9:15:20 PM UTC. Search may be required.	8:04pm
Newznab	Indexer Nzb.su rss sync didn't cover the period between 12/20/2016 11:19:42 PM and 1/31/2017 9:34:33 PM UTC. Search may be required.	8:04pm
Torznab	Indexer MoreThanTV rss sync didn't cover the period between 12/15/2016 7:41:00 AM and 2/1/2017 10:04:00 AM UTC. Search may be required.	8:04pm
Torznab	Indexer bithdtv rss sync didn't cover the period between 12/6/2016 12:21:53 AM and 1/31/2017 7:37:00 PM UTC. Search may be required.	8:04pm
Torznab	Indexer xthor rss sync didn't cover the period between 12/5/2016 8:21:48 PM and 1/31/2017 8:20:27 PM UTC. Search may be required.	8:04pm

Jackett:

b 01, 2017 08:16:14 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
Feb 01, 2017 08:16:14 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Feb 01, 2017 08:16:14 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Feb 01, 2017 08:16:14 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Feb 01, 2017 08:16:14 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Feb 01, 2017 08:16:14 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Feb 01, 2017 08:16:14 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Feb 01, 2017 08:16:14 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Feb 01, 2017 08:16:14 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Feb 01, 2017 08:16:14 PM	Info	
ApiControllerActionSelector SelectAction 
Feb 01, 2017 08:16:14 PM	Info	
AdminController ExecuteAsync 
Feb 01, 2017 08:16:14 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Feb 01, 2017 08:16:14 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Feb 01, 2017 08:16:14 PM	Info	
DefaultHttpControllerActivator Create 
Feb 01, 2017 08:16:14 PM	Info	
HttpControllerDescriptor CreateController 
Feb 01, 2017 08:16:14 PM	Info	
DefaultHttpControllerSelector SelectController Admin
Feb 01, 2017 08:16:14 PM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Feb 01, 2017 08:16:14 PM	Info	
  http://0.0.0.0:9117/Admin/GetLogs?_=1485954642051
Feb 01, 2017 08:11:50 PM	Info	
TorznabController Dispose 
Feb 01, 2017 08:11:50 PM	Info	
TorznabController Dispose 
Feb 01, 2017 08:11:50 PM	Info	
  Content-type='application/rss+xml; charset=utf-8', content-length=55364
Feb 01, 2017 08:11:50 PM	Info	
TorznabController ExecuteAsync 
Feb 01, 2017 08:11:50 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
Feb 01, 2017 08:11:50 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Call(String indexerID)'
Feb 01, 2017 08:11:50 PM	Info	
ApiControllerActionInvoker InvokeActionAsync 
Feb 01, 2017 08:11:50 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StringContent, Headers:
{
Content-Type: application/rss+xml; charset=utf-8
}'
Feb 01, 2017 08:11:50 PM	Info	
Found 50 (1 new) releases from AlphaRatio
Feb 01, 2017 08:11:50 PM	Debug	
IWebClient: Returning OK => {"status":"success","response":{"currentPage":1,"pages":200,"results":[{"groupId":495447,"groupName":"Stephen.Colbert.2017.01.31.Josh.Groban.HDTV.x264-SORNY","torrentId":495418,"tags":[""],"category":"TvSD","fileCount":35,"groupTime":"1485954494","size":488546692,"snatches":0,"seeders":0,"leechers":1,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495446,"groupName":"Father.Brown.2013.S05E12.HDTV.x264-RiVER","torrentId":495417,"tags":[""],"category":"TvSD","fileCount":25,"groupTime":"1485954349","size":337937449,"snatches":0,"seeders":0,"leechers":1,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495445,"groupName":"Seth.Meyers.2017.01.31.Robert.De.Niro.720p.WEB.x264-HEAT","torrentId":495416,"tags":[""],"category":"TvHD","fileCount":14,"groupTime":"1485954294","size":569349060,"snatches":0,"seeders":0,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495444,"groupName":"Father.Brown.2013.S05E12.720p.HDTV.x264-RiVER","torrentId":495415,"tags":[""],"category":"TvHD","fileCount":23,"groupTime":"1485954262","size":1007822367,"snatches":0,"seeders":1,"leechers":2,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495439,"groupName":"Father.Brown.2013.S05E08.HDTV.x264-RiVER","torrentId":495410,"tags":[""],"category":"TvSD","fileCount":22,"groupTime":"1485953971","size":285850500,"snatches":2,"seeders":3,"leechers":1,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495436,"groupName":"Father.Brown.2013.S05E08.720p.HDTV.x264-RiVER","torrentId":495407,"tags":[""],"category":"TvHD","fileCount":20,"groupTime":"1485953920","size":856663608,"snatches":0,"seeders":1,"leechers":1,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495433,"groupName":"Our.Dancing.Town.S01E02.720p.HDTV.x264-BARGE","torrentId":495404,"tags":[""],"category":"TvHD","fileCount":36,"groupTime":"1485953741","size":1682455326,"snatches":0,"seeders":0,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495421,"groupName":"Our.Dancing.Town.S01E01.720p.HDTV.x264-BARGE","torrentId":495392,"tags":[""],"category":"TvHD","fileCount":33,"groupTime":"1485952918","size":1549609957,"snatches":0,"seeders":0,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495417,"groupName":"Britains.Benefit.Tenants.S03E03.720p.HDTV.x264-BARGE","torrentId":495388,"tags":[""],"category":"TvHD","fileCount":21,"groupTime":"1485952111","size":916104851,"snatches":0,"seeders":1,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495410,"groupName":"Jimmy.Fallon.2017.01.31.Dakota.Johnson.HDTV.x264-CROOKS","torrentId":495381,"tags":[""],"category":"TvSD","fileCount":25,"groupTime":"1485951473","size":340930142,"snatches":0,"seeders":0,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495395,"groupName":"Lawless.Oceans.S01E04.HDTV.x264-CROOKS","torrentId":495366,"tags":[""],"category":"TvSD","fileCount":24,"groupTime":"1485949233","size":325802601,"snatches":0,"seeders":1,"leechers":2,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495390,"groupName":"Silent.Witness.S20E10.INTERNAL.1080p.HDTV.x264-CREED","torrentId":495361,"tags":[""],"category":"TvHD","fileCount":45,"groupTime":"1485948234","size":2136646941,"snatches":0,"seeders":1,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495388,"groupName":"Chasing.Classic.Cars.S05E20.Still.Racy.1080p.WEB.h264-EDHD","torrentId":495359,"tags":[""],"category":"TvHD","fileCount":25,"groupTime":"1485947983","size":1044672926,"snatches":1,"seeders":2,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495387,"groupName":"Chasing.Classic.Cars.S05E19.The.Curve.Ball.1080p.WEB.h264-EDHD","torrentId":495358,"tags":[""],"category":"TvHD","fileCount":22,"groupTime":"1485947708","size":1036511213,"snatches":0,"seeders":2,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495386,"groupName":"Chasing.Classic.Cars.S05E18.You.Dont.See.That.Everyday.1080p.WEB.h264-EDHD","torrentId":495357,"tags":[""],"category":"TvHD","fileCount":25,"groupTime":"1485947537","size":1047429339,"snatches":1,"seeders":2,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495384,"groupName":"Beware.the.Slenderman.2016.1080p.HBO.WEB-DL.DD5.1.H.264-monkee","torrentId":495355,"tags":["documentary","hbo"],"category":"TvHD","fileCount":1,"groupTime":"1485946665","size":3383038222,"snatches":3,"seeders":4,"leechers":1,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495383,"groupName":"My.Kitchen.Rules.S08E03.HDTV.x264-FQM","torrentId":495354,"tags":[""],"category":"TvSD","fileCount":28,"groupTime":"1485945875","size":380507600,"snatches":2,"seeders":3,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495378,"groupName":"Outsiders.S02E02.1080p.WEB.h264-JAWN","torrentId":495349,"tags":[""],"category":"TvHD","fileCount":53,"groupTime":"1485944154","size":2535678624,"snatches":2,"seeders":3,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495368,"groupName":"Teen.Wolf.S06E10.1080p.HDTV.x264-CRAVERS","torrentId":495339,"tags":[""],"category":"TvHD","fileCount":37,"groupTime":"1485941288","size":1732322175,"snatches":8,"seeders":9,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495367,"groupName":"Great.American.Railroad.Journeys.S02E07.720p.WEB.H264-GARJ207","torrentId":495338,"tags":[""],"category":"TvHD","fileCount":14,"groupTime":"1485940552","size":516543013,"snatches":1,"seeders":2,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495365,"groupName":"WWE.Smackdown.2017.01.31.720p.HDTV.x264-KYR","torrentId":495336,"tags":[""],"category":"TvHD","fileCount":61,"groupTime":"1485940189","size":2947434991,"snatches":2,"seeders":3,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495359,"groupName":"Dance.Moms.S07E10.720p.WEB.h264-HEAT","torrentId":495330,"tags":[""],"category":"TvHD","fileCount":19,"groupTime":"1485938167","size":836581880,"snatches":5,"seeders":6,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495358,"groupName":"At.Midnight.2017.01.31.1080p.WEB.x264-HEAT","torrentId":495329,"tags":[""],"category":"TvHD","fileCount":15,"groupTime":"1485938082","size":608470665,"snatches":2,"seeders":3,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495357,"groupName":"At.Midnight.2017.01.31.720p.WEB.x264-HEAT","torrentId":495328,"tags":[""],"category":"TvHD","fileCount":21,"groupTime":"1485938018","size":367796338,"snatches":0,"seeders":2,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495355,"groupName":"At.Midnight.2017.01.31.WEB.x264-HEAT","torrentId":495326,"tags":[""],"category":"TvSD","fileCount":15,"groupTime":"1485937976","size":246838016,"snatches":1,"seeders":3,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495353,"groupName":"Women.In.Blue.S02E01.HDTV.x264-FiHTV","torrentId":495324,"tags":[""],"category":"TvSD","fileCount":10,"groupTime":"1485937629","size":157616380,"snatches":1,"seeders":2,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495349,"groupName":"Women.In.Blue.S02E01.720p.HDTV.x264-FiHTV","torrentId":495320,"tags":[""],"category":"TvHD","fileCount":13,"groupTime":"1485937450","size":538072334,"snatches":3,"seeders":4,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495345,"groupName":"Escaping.Polygamy.S02E11.720p.WEB.h264-HEAT","torrentId":495316,"tags":[""],"category":"TvHD","fileCount":19,"groupTime":"1485936962","size":849587713,"snatches":1,"seeders":2,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495336,"groupName":"TMZ.on.TV.2017.01.31.SDTV.x264-AR","torrentId":495307,"tags":["tmz"],"category":"TvSD","fileCount":1,"groupTime":"1485936081","size":202518883,"snatches":3,"seeders":4,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495333,"groupName":"EPL.2017.01.31.Liverpool.vs.Chelsea.720p.HDTV.x264-VERUM","torrentId":495304,"tags":[""],"category":"TvHD","fileCount":73,"groupTime":"1485935579","size":3531904805,"snatches":1,"seeders":2,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495332,"groupName":"Dr.Phil.Show.2017.01.31.HDTV.x264-AR","torrentId":495303,"tags":["drphil"],"category":"TvSD","fileCount":1,"groupTime":"1485935574","size":212876158,"snatches":5,"seeders":5,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495330,"groupName":"Vet.Tales.S01E01.HDTV.x264-FiHTV","torrentId":495301,"tags":[""],"category":"TvSD","fileCount":10,"groupTime":"1485935335","size":158133479,"snatches":1,"seeders":2,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495329,"groupName":"Vet.Tales.S01E01.720p.HDTV.x264-FiHTV","torrentId":495300,"tags":[""],"category":"TvHD","fileCount":12,"groupTime":"1485935221","size":488379020,"snatches":3,"seeders":4,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495328,"groupName":"Tattoo.Girls.S01E02.Rosebutt.HDTV.x264-CRiMSON","torrentId":495299,"tags":[""],"category":"TvSD","fileCount":18,"groupTime":"1485934621","size":309501913,"snatches":1,"seeders":3,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495327,"groupName":"Forged.in.Fire.S03E14.The.Naginata.iNTERNAL.720p.HDTV.x264-DHD","torrentId":495298,"tags":[""],"category":"TvHD","fileCount":23,"groupTime":"1485933961","size":1021778471,"snatches":3,"seeders":4,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495325,"groupName":"EPL.2017.01.31.Liverpool.vs.Chelsea.HDTV.x264-VERUM","torrentId":495296,"tags":[""],"category":"TvSD","fileCount":60,"groupTime":"1485933791","size":1149328482,"snatches":2,"seeders":3,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495323,"groupName":"Intervention.S16E13.720p.WEB.h264-HEAT","torrentId":495294,"tags":[""],"category":"TvHD","fileCount":20,"groupTime":"1485933724","size":851536883,"snatches":3,"seeders":3,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495322,"groupName":"Silent.Witness.S20E10.1080p.HDTV.x264-PiECES","torrentId":495293,"tags":[""],"category":"TvHD","fileCount":46,"groupTime":"1485933501","size":2156673620,"snatches":1,"seeders":2,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495314,"groupName":"Shortland.Street.S25E234.HDTV.x264-FiHTV","torrentId":495285,"tags":[""],"category":"TvSD","fileCount":10,"groupTime":"1485933035","size":159229866,"snatches":4,"seeders":5,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495313,"groupName":"Shortland.Street.S25E234.720p.HDTV.x264-FiHTV","torrentId":495284,"tags":[""],"category":"TvHD","fileCount":13,"groupTime":"1485932850","size":526583984,"snatches":2,"seeders":3,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495311,"groupName":"Killing.Fields.S02E05.The.Raid.HDTV.x264-CRiMSON","torrentId":495282,"tags":[""],"category":"TvSD","fileCount":18,"groupTime":"1485932123","size":305649598,"snatches":4,"seeders":4,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495307,"groupName":"Killing.Fields.S02E05.The.Raid.720p.HDTV.x264-CRiMSON","torrentId":495278,"tags":[""],"category":"TvHD","fileCount":23,"groupTime":"1485931701","size":1002302390,"snatches":4,"seeders":5,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495306,"groupName":"Lawless.Oceans.S01E05.The.Victims.720p.HDTV.x264-DHD","torrentId":495277,"tags":[""],"category":"TvHD","fileCount":23,"groupTime":"1485930935","size":1047691045,"snatches":2,"seeders":3,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495305,"groupName":"Celebrity.Family.Feud.NZ.S01E03.HDTV.x264-FiHTV","torrentId":495276,"tags":[""],"category":"TvSD","fileCount":13,"groupTime":"1485930795","size":210594586,"snatches":1,"seeders":2,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495292,"groupName":"Being.Mary.Jane.S04E03.HDTV.x264-FLEET","torrentId":495263,"tags":[""],"category":"TvSD","fileCount":18,"groupTime":"1485927755","size":226950887,"snatches":3,"seeders":5,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495291,"groupName":"Being.Mary.Jane.S04E03.720p.HDTV.x264-FLEET","torrentId":495262,"tags":[""],"category":"TvHD","fileCount":17,"groupTime":"1485927729","size":704815723,"snatches":3,"seeders":5,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495287,"groupName":"The.Curse.of.Oak.Island.S04E12.720p.HDTV.x264-KILLERS","torrentId":495258,"tags":[""],"category":"TvHD","fileCount":30,"groupTime":"1485927327","size":1377756728,"snatches":17,"seeders":12,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495286,"groupName":"The.Curse.of.Oak.Island.S04E12.HDTV.x264-KILLERS","torrentId":495257,"tags":[""],"category":"TvSD","fileCount":29,"groupTime":"1485927288","size":398145315,"snatches":16,"seeders":17,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495283,"groupName":"Teen.Wolf.After.After.Show.S06E10.1080p.WEB.x264-HEAT","torrentId":495254,"tags":[""],"category":"TvHD","fileCount":24,"groupTime":"1485926844","size":437545758,"snatches":3,"seeders":4,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false},{"groupId":495280,"groupName":"Teen.Wolf.After.After.Show.S06E10.720p.WEB.x264-HEAT","torrentId":495251,"tags":[""],"category":"TvHD","fileCount":15,"groupTime":"1485926721","size":240749958,"snatches":5,"seeders":6,"leechers":0,"isFreeleech":false,"isNeutralLeech":false,"isPersonalFreeleech":false,"canUseToken":true,"hasSnatched":false}]}}
Feb 01, 2017 08:11:47 PM	Debug	
IWebClient.GetString(Url:https://alpharatio.cc/ajax.php?action=browse&order_by=time&order_way=desc&filter_cat[1]=1&filter_cat[2]=1)
Feb 01, 2017 08:11:47 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Call(indexerID=alpharatio)'
Feb 01, 2017 08:11:47 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='Call(indexerID=alpharatio)'
Feb 01, 2017 08:11:47 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Feb 01, 2017 08:11:47 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Call(String indexerID)'
Feb 01, 2017 08:11:47 PM	Info	
HttpActionBinding ExecuteBindingAsync Model state is valid. Values: indexerID=alpharatio
Feb 01, 2017 08:11:47 PM	Info	
ModelBinderParameterBinding ExecuteBindingAsync Parameter 'indexerID' bound to the value 'alpharatio'
Feb 01, 2017 08:11:47 PM	Info	
ModelBinderParameterBinding ExecuteBindingAsync Binding parameter 'indexerID'
Feb 01, 2017 08:11:47 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Feb 01, 2017 08:11:47 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'Call(String indexerID)'
Feb 01, 2017 08:11:47 PM	Info	
ApiControllerActionSelector SelectAction 
Feb 01, 2017 08:11:47 PM	Info	
TorznabController ExecuteAsync 
Feb 01, 2017 08:11:47 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.TorznabController
Feb 01, 2017 08:11:47 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.TorznabController
Feb 01, 2017 08:11:47 PM	Info	
DefaultHttpControllerActivator Create 
Feb 01, 2017 08:11:47 PM	Info	
HttpControllerDescriptor CreateController 
Feb 01, 2017 08:11:47 PM	Info	
DefaultHttpControllerSelector SelectController Torznab
Feb 01, 2017 08:11:47 PM	Info	
DefaultHttpControllerSelector SelectController Route='indexerID:alpharatio,controller:Torznab,action:Call'
Feb 01, 2017 08:11:47 PM	Info	
  http://localhost:9117/torznab/alpharatio/api?t=tvsearch&cat=5030,5040&extended=1&apikey=w0y4ehscyrgrpelojupm7yxwm3r0v6gz&offset=0&limit=100
Feb 01, 2017 08:11:47 PM	Info	
TorznabController Dispose 
Feb 01, 2017 08:11:47 PM	Info	
TorznabController Dispose 
Feb 01, 2017 08:11:47 PM	Info	
  Content-type='application/xml; charset=utf-8', content-length=1880
Close

**Comment by sethwarsh** [comment]
It looks like my sonarr database is in a locked state?

**Comment by markus101** [comment]
Please use the forums for support.

Make sure the user running Sonarr has write access to the DB and it's not corrupt.
