### ISSUE TITLE
Manual matching of episodes in the series folder

### ISSUE THREAD

**Issue by serialoverflow** [Sonarr/Sonarr#1653]
Hey,

i have a lot of shows that Sonarr thinks are missing a couple of episodes for completion when in fact those episodes exist and are properly named. Sonarr just won't recognize them.

<img width="129" alt="screen shot 2017-02-02 at 10 15 08" src="https://cloud.githubusercontent.com/assets/279131/22543375/8da45012-e930-11e6-8ff1-1b8373bd5125.png">

Please make it possible to manually match those files in Sonarr so that i can finally "complete" these shows.

**Comment by markus101** [comment]
You can use manual import on the series folder to achieve that already, but if they are properly named Sonarr should have no issue finding them. Debug logs will show why they are failing to match properly.

**Comment by serialoverflow** [comment]
Thank you for the quick response.
Do you mean "Series -> Add Series -> Import Existing Series On Disk"?

**Comment by markus101** [comment]
No, manual import from Wanted: Missing.

**Comment by serialoverflow** [comment]
Thank you. I'll try it out. I wouldn't have thought to look there though, i believe it would be more intuitive to have that button on missing episodes within each Series, too.
