### ISSUE TITLE
Prefer certain filenames when looking for releases

### ISSUE THREAD

**Issue by serialoverflow** [Sonarr/Sonarr#1655]
Hey,

i know there is a "Must contain" option when looking for posts on an indexer but is there something less absolute, like a "Should contain" option?
I want to prefer files that contain certain words, for example "Obfuscated" or a specific release group.

Is there a way to do that yet?

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/385
