### ISSUE TITLE
Support for non-torrents

### ISSUE THREAD

**Issue by J0quap01** [Sonarr/Sonarr#1659]
Could support for filhosters such as [share-online.biz](url) be added? I download my movies and tv-shows via [https://ddl-warez.to/](url) and there I get a link to a filecontainer form share-online. I'd like to use that with Sonarr.

**Comment by markus101** [comment]
We have no plans to support other protocols at this time.

**Comment by J0quap01** [comment]
Okey. Thanks for your work anyway…
