### ISSUE TITLE
Notifications on errors

### ISSUE THREAD

**Issue by uskyrt** [Sonarr/Sonarr#1662]
Issue: sometimes things don't work
e.g. tracker not working, utorrent unresponsive, HD full etc.

Would be nice to have a [Pushbullet] (or any other chosen channels to receive notification) to send warnings when they start happening e.g. after [X] occurrences

The notification section would need a way to detect error types or words to avoid spamming

**Comment by markus101** [comment]
This would be extremely hard to get right, there are lot's of variables at play and some errors are more important than others.

**Comment by markus101** [comment]
Closing in favour of: https://github.com/Sonarr/Sonarr/issues/1798 (same idea, just more explicit).
