### ISSUE TITLE
setting username/password on Settings --> General requires restart but logout button is shown before restart

### ISSUE THREAD

**Issue by geogolem** [Sonarr/Sonarr#1666]
I discovered this minor bug using radarr.... however I was also able to reproduce in sonarr..

Please refer to this issue in radarr for more details about this bug: 

https://github.com/Radarr/Radarr/issues/633

**Comment by markus101** [comment]
The UI does say it requires a restart in the tooltip, but that is a bit weird regardless.

I have addressed this in the v3 UI work.
