### ISSUE TITLE
Connect with Kodi: Display Time field

### ISSUE THREAD

**Issue by davkav** [Sonarr/Sonarr#1668]
When connecting Sonarr to Kodi and configuring the display time field, the connection will only test successful with an integer of 2 or more seconds.

**Comment by markus101** [comment]
A validation error is thrown if you choose less than 2 seconds. It's been a while, but I believe 2 seconds was the minimum Kodi required.

**Comment by davkav** [comment]
I remember reading something a while back about the 2 minute minimum alright, but it caught me out again.

I'm running an instance of Kodi on my server and a shared SQL database so that all of my clients will always be up to date without having to wait and refresh on boot up.

Anyway.... I should have said my first post, could the help message be updated in Sonarr to state 2 seconds minimum so it doesn't catch other users out?

**Comment by markus101** [comment]
You don't need to have Sonarr show notifications if you don't want them, just turn off `GUI Notification`. Are you not seeing an error message if you set the time less than 2?

**Comment by davkav** [comment]
This is my configuration. GUI notification isn't enabled but testing the communications with Kodi before saving will fail if the Display Time is less than 2.

![2017-02-09 17_17_22-settings - sonarr](https://cloud.githubusercontent.com/assets/10668453/22794614/a7be3902-eeeb-11e6-9764-fc2e3cfc908e.png)
