### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by drashna** [Sonarr/Sonarr#1669]
It would be nice to have the option to use MySQL/mariaDB/etc rather than SQLite.  

I already run mariaDB for MySQL support on a system on my network, so it would be nice/useful to be able to use that db server instead.

**Comment by markus101** [comment]
We don't have plans to support another DB engine at this time, it's a significant change that would require validating all migrations on every DB engine supported (adding MySQL would only open the doors to add more) and deal with differences in various versions (which we've run into with SQLite a few times).
