### ISSUE TITLE
[Feature Request] Check if the title is streamable before adding

### ISSUE THREAD

**Issue by WindfallProphet** [Sonarr/Sonarr#1674]
I think some people use Plex as a complement to some of the streaming services (Netflix/Hulu/Amazon, etc.). It would be a good idea, if possible, to hold off on adding the title, or episodes, to Sonarr if it is available on a streaming service to which you are subscribed. There could be an option in the settings that allows you to select which providers you are subscribed to. 

No idea if there's an API that would work with this idea.

**Comment by markus101** [comment]
Netflix removed their API for available shows a while ago, I don't know if other services have an API or not, but this isn't a feature we're considering at this time. There are too many variables to accomplish this easily and with the ever changing availability of content along with different support in different reasons it's complicated.
