### ISSUE TITLE
Download Station and Completed Download Handling

### ISSUE THREAD

**Issue by obouallou** [Sonarr/Sonarr#1676]
Hello,

First of all thanks for adding support for DS in Sonarr !

I've started to try it since it was merged in develop branch, and got some questions related to completed download handling.
Here's the description of the feature from the wiki : 

If the "Completed Download Handling - Remove" option is enabled in Sonarr's settings, Sonarr will delete the original file and torrent from your client, but only if the client reports that seeding is complete and torrent is stopped.

So if I understand correctly, once seeding is done, Sonarr is supposed to remove the torrent from Synology client (which it does) and delete the original files from the download directory (which it doesn't)

Is it working as inteded or do you think it should delete files ?

**Comment by margaale** [comment]
Hi, a few questions until some of the devs see this. How is your setup? Do you have sonarr runing in the diskstation? Any remote mapping? Permissions of your download directory? Laslty, any do you see any error in logs or any other info that could be useful?

**Comment by obouallou** [comment]
Sonarr is running on a different machine but the video folder is mounted with R/W permissions.
torrents are downloaded to /video/downloaded/sonarr and then processed to /video/series.

There are no errors in logs  (removed data & filename : 

```
17-2-12 20:34:38.4|Trace|CommandQueueManager|Publishing CheckForFinishedDownload
17-2-12 20:34:38.4|Trace|CommandQueueManager|Checking if command is queued or started: CheckForFinishedDownload
17-2-12 20:34:38.4|Trace|CommandQueueManager|Inserting new command: CheckForFinishedDownload
17-2-12 20:34:38.4|Trace|CommandExecutor|CheckForFinishedDownloadCommand -> DownloadMonitoringService
17-2-12 20:34:38.4|Trace|CommandQueueManager|Marking command as started: CheckForFinishedDownload
17-2-12 20:34:38.7|Trace|HttpClient|Req: [GET] http://192.168.138.1:5000/webapi/DownloadStation/task.cgi?api=(removed)&version=1&method=list&additional=detail%2Ctransfer
17-2-12 20:34:38.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-2-12 20:34:38.9|Trace|HttpClient|Res: [GET] http://192.168.138.1:5000/webapi/DownloadStation/task.cgi?api=(removed)&version=1&method=list&additional=detail%2Ctransfer: 200.OK (263 ms)
17-2-12 20:34:38.9|Trace|HttpClient|Response content (13674 bytes): {"data": ...}

17-2-12 20:34:39.2|Trace|EventAggregator|Publishing DownloadCompletedEvent
17-2-12 20:34:39.2|Trace|EventAggregator|DownloadCompletedEvent -> DownloadEventHub
17-2-12 20:34:39.4|Debug|DownloadEventHub|[<file>.mkv] Removing download from DS Download history
17-2-12 20:34:39.4|Trace|HttpClient|Req: [GET] http://192.168.138.1:5000/webapi/DownloadStation/task.cgi?api=(removed)&version=1&method=delete&id=dbid_1355&force_complete=False
17-2-12 20:34:39.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-2-12 20:34:39.8|Trace|HttpClient|Res: [GET] http://192.168.138.1:5000/webapi/DownloadStation/task.cgi?api=(removed)&version=1&method=delete&id=dbid_1355&force_complete=False: 200.OK (448 ms)
17-2-12 20:34:39.8|Trace|HttpClient|Response content (55 bytes): {"data":[{"error":0,"id":"dbid_1355"}],"success":true}

17-2-12 20:34:39.8|Trace|DownloadStationProxy|Item dbid_1355 removed from Download Station
17-2-12 20:34:39.8|Debug|DownloadStation|62E02739D824D892651440EF32CF6E991BCA671F:dbid_1355 removed correctly

```

**Comment by margaale** [comment]
And what about remote mapping entry?  In my setup I have one that points to /volume1/video of my syno

**Comment by obouallou** [comment]
got the same : /volume1/video/ to /nas/video/

**Comment by margaale** [comment]
Mine is the full path, in your case /volume1/video/downloaded/sonarr
Dont know if it makes any difference...

**Comment by obouallou** [comment]
What do you mean by the full path ?
In my case the default download directory in DS is set to /volume1/video/downloaded, in the sonarr DS client I set a "category": "sonarr" thus the /volume1/video/downloaded/sonarr.

Do you have any logs ?

**Comment by margaale** [comment]
Sorry for keep you waiting.You are right, the files aren't getting deleted. This is my log...

17-2-13 00:36:47.5|Debug|DownloadEventHub|[Supernatural.S12E01.720p.HDTV.X264-DIMENSION[rarbg]] Removing download from Diskstation history
17-2-13 00:36:53.3|Debug|DownloadStationProxy|Trying to remove item dbid_617
17-2-13 00:36:53.3|Debug|DownloadStation|264180A90757F0464FC89523BA358E7F1D886B13:dbid_617 removed correctly

@Taloth I've been debuging the code. IsReadOnly is false, outputPath points to the directory where the files are (tried with multifile torrent) and status is completed. Tell me if you need anything else...

**Comment by Taloth** [comment]
I didn't notice this in the PR reviews, but `deleteData` parameter isn't passed to the syno in the `DownloadStationProxy`.
If the syno doesn't support deleting the files along with the torrent. Then you'll have to implement that in the `DownloadStation` class. (In that case the `deleteData` parameter doesn't belong on the proxy.)
There's actually a [helper](https://github.com/Sonarr/Sonarr/blob/816cf608fcef07e375aa750a863d0a7365108981/src/NzbDrone.Core/Download/DownloadClientBase.cs#L89) method to do it for you, used in the blackhole client.

**Comment by obouallou** [comment]
You're right @Taloth, Syno doesn't support deleting the files because of the way it handles finished downloads and seeding.
Unfinished downloads are located in /volume1/@download and hardlinked to files in final directory (/volume1/video/downloaded in my case), once seed is done, syno handles deleting files from @download directory.

In fact, in DS case, files can be removed from the /downloaded directory as soon as they are imported to /series directory. DS handles seeding.
