### ISSUE TITLE
rename Windows executable to something more friendly

### ISSUE THREAD

**Issue by attritionorg** [Sonarr/Sonarr#1680]
Currently, downloading the Sonarr Windows binary from https://sonarr.tv/#download will result in a download of "NzbDrone.master.exe". Visually that has nothing to do with Sonarr. Recommend this be changed to a more standard scheme with "Sonarr" in the name and the version.

**Comment by markus101** [comment]
It will be renamed in v3 when we update all the binaries to Sonarr from NzbDrone.
