### ISSUE TITLE
Twitter notification format

### ISSUE THREAD

**Issue by timk95** [Sonarr/Sonarr#1681]
I'm not sure about notification behaviour in the official Twitter client but I'm using Tweetbot and unfortunately Tweetbot doesn't send a push notification if the user handle isn't at the beginning of a message.

So "Imported: show S01E01 [Bluray-1080p] @twitterusername" won't fire a push notification but "@twitterusername Imported: show S01E01 [Bluray-1080p]" would.

If there is no particular reason for putting the handle at the end, could it be moved to the front of the message?

I can't make PR at the moment because I'm not near a development setup for a while but changing [this line](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Notifications/Twitter/TwitterService.cs#L93) to prepend instead of append would do the trick.

**Comment by markus101** [comment]
The mention placement does have an effect on the result, if it's the first thing it doesn't appear in the sender's timeline, but if it's anywhere else it does. It also changes the first part of the message which has been a pain point for other notification channels (people want to see the content of the message immediately). I don't want to disrupt other's workflow to change the order, but I think this would fall under https://github.com/Sonarr/Sonarr/issues/328
