### ISSUE TITLE
sonarr - fails test when sab is running from source

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#1688]
Sonarr Ver. 2.0.0.4593

Sab installed running from `develop` branch so I can test some code, going to add it to sonarr the test returns back a warning message and it 'fails'.. but it actually worked fine.

```
17-2-16 07:46:12.4|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Sabnzbd develop version, assuming version 1.1.0 or higher.
```

`https://localhost:ip/api?mode=version&apikey=(removed)&output=json` returns: `{"version": "develop"}`

thought this was handled by:
https://github.com/Sonarr/Sonarr/commit/68ea8a551ce83f6ff001e5adf3f07358b28ad189

**Comment by markus101** [comment]
It's a validation warning, it will still save because the warning is only displayed when testing. That is expected behaviour because Sonarr has no way of knowing the actual version.

**Comment by thezoggy** [comment]
but it fails.. making me think that i have something misconfigured...  only was it until i looked at the debug logs before i realized it actually worked. seems like the 'warning' shouldnt mean fail the test?

**Comment by markus101** [comment]
The failed toast appears? Not sure about that behaviour, but it should mark any fields/the form with warnings (instead of errors).

**Comment by thezoggy** [comment]
the failed toast appears, then i get the message up top about being on dev..

**Comment by markus101** [comment]
Yellow text? Could you post a screenshot?

**Comment by thezoggy** [comment]
good settings on dev:
![sonarr1](http://zoggy.net/firefox_2017-02-16_22-31-29.png)
vs bad settings:
![sonarr2](http://zoggy.net/firefox_2017-02-16_22-30-56.png)

both show the same failed toast

**Comment by markus101** [comment]
Thanks, that makes sense. That behaviour will be much better in v3. 😄
