### ISSUE TITLE
Indexers unavailable due to failures

### ISSUE THREAD

**Issue by breezytm** [Sonarr/Sonarr#1689]
My indexers constantly and randomly stops working and I have to manual restart the application for them to work again. I know the indexers work because the same exact ones are working in Sonarr without any issues. After a reboot, the test runs successfully. After the issue occurs it states it's unable to connect. Both of them, same issue. 

In radarr

17-2-16 15:11:30.5|Info|RssSyncService|Starting RSS Sync
17-2-16 15:11:30.5|Warn|FetchAndParseRssService|No available indexers. check your configuration.
17-2-16 15:11:30.6|Info|DownloadDecisionMaker|No results found
17-2-16 15:11:30.6|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-2-16 15:26:40.3|Info|InstallUpdateService|Deleting old update files
17-2-16 15:26:40.3|Info|InstallUpdateService|Downloading update 0.2.0.368
17-2-16 15:26:40.3|Info|RssSyncService|Starting RSS Sync
17-2-16 15:26:40.4|Warn|FetchAndParseRssService|No available indexers. check your configuration.
17-2-16 15:26:40.4|Info|DownloadDecisionMaker|No results found
17-2-16 15:26:40.4|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-2-16 15:26:40.6|Warn|HttpClient|Failed to get response from: https://ci.appveyor.com/api/buildjobs/a5g7h6b5y9xumklf/artifacts/_artifacts/Radarr.develop.0.2.0.368.linux.tar.gz Error: SecureChannelFailure (The authentication or decryption has failed.)
17-2-16 15:26:40.9|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

In Sonarr

17-2-15 20:51:23.7|Info|NzbSearchService|Searching 3 indexers for [24: Legacy : S01E03]
17-2-15 20:51:25.9|Info|DownloadDecisionMaker|Processing 46 releases
17-2-15 20:52:11.6|Info|Nzbget|Adding report [24.Legacy.S01E03.1080p.Amazon.WEBRip.DD.5.1.x264-ViscaBarca-Obfuscated] to the queue.
17-2-15 20:52:12.4|Info|DownloadService|Report sent to NZBGet. 24.Legacy.S01E03.1080p.Amazon.WEBRip.DD.5.1.x264-ViscaBarca-Obfuscated
17-2-15 20:52:25.6|Info|RssSyncService|Starting RSS Sync
17-2-15 20:52:25.8|Info|NzbSearchService|Searching 3 indexers for [The Walking Dead : S07E09]
17-2-15 20:52:30.1|Info|DownloadDecisionMaker|Processing 225 releases

**Comment by markus101** [comment]
Did you mean to open this in the Radarr repo?

**Comment by breezytm** [comment]
Yes. Sorry. I was looking at Sonarr to see if I notice others reporting the same issue for it as well and accidently posted here. You can close it.
