### ISSUE TITLE
Sonarr upgraded episodes with wrong series

### ISSUE THREAD

**Issue by karirafn** [Sonarr/Sonarr#1692]
Sonarr just upgraded Berserk (2016) with bluray rips of the original Berserk series.

The bluray rips were named like this: berserk.e12.720p.bluray.x264-haiku.mkv

**Comment by markus101** [comment]
`Berserk` is an alias for `Berserk (2016)` on thexem.de: http://thexem.de/xem/show/3250 Sonarr doesn't have a way to know that that's for a different series.
