### ISSUE TITLE
Allow for seperate "move to" and "library" directories

### ISSUE THREAD

**Issue by Fmstrat** [Sonarr/Sonarr#1693]
One of the things that Couchpotato offers is a nice way of handling media placement. For instance, in one section of configuration, you can set where movies are moved from/to:

![capture1](https://cloud.githubusercontent.com/assets/971474/23098699/55675dac-f623-11e6-9a36-3733a26fa135.PNG)

And then in another section, you can configure where it monitors the library:

![capture2](https://cloud.githubusercontent.com/assets/971474/23098704/63f369e2-f623-11e6-9284-438ec9c7e8db.PNG)

The advantage of this is that if you do something like, say, keep half of your library on a cloud share like Amazon Drive and the other half on the local drive with UnionFS linking them together, it allows you to point the "move to" folder to the local drive but the "manage" folder to the linked UnionFS mount. This is getting more and more common with the advent of Rclone.

Perhaps even an advanced feature in a hidden place somewhere, where you could replace part of the root path for all "move to" actions. Like "/mnt/video" to "/mnt/external" etc to make it easier to develop since it's probably only a special case thing.

**Comment by markus101** [comment]
I thought union FS supported this as there are others doing it with ACD and UnionFS already, Sonarr writes to the local folder and eventually they appear in ACD, but Sonarr doesn't know the difference.

**Comment by Fmstrat** [comment]
Yes, that's exactly what happens now. The issue is if you have Movies and TV on separate drives you have to have multiple instances of UnionFS running:
- One for ACD and TV where the TV folder is the first or only writable block for Sonarr
- Another where Movies is the first writable block
There are workarounds, just not as clean. As I said, very specific use cases, so I get off it's not an area of focus, I get it.

**Comment by markus101** [comment]
At the moment it's not something we're looking at, though the thought of a similar feature (multiple locations, one writable, the rest read-only) has crossed my mind, the biggest deterrent has been usefulness, with the prevalence of pooling options it's not very common to need multiple series locations. This is another use case but like you said a very specific use case that we're support at this time.

**Comment by ion-storm** [comment]
this shouldnt be closed, searching google for multiple directories/multiple drives and sonarr has been requested everywhere
