### ISSUE TITLE
Indexer Delay

### ISSUE THREAD

**Issue by DFKnight** [Sonarr/Sonarr#1694]
I've noticed over the past year or so that some indexers get releases before they are available to download via usenet. After about 30 minutes to 2 hours, the release becomes available. The issue happens when sonarr blacklists the release because it fails to download (which is usually due to unavailability). These releases usually have a name, or whatever criteria sonarr uses for deduping releases, which matches on multiple indexers, and being blacklist means they get ignored when the correct release becomes available. 

As such, I believe there should be an option to add a delay to certain indexers before they are searched (via RSS/manual/automatic). While adding priority would be convenient, it won't help in this scenario because the indexers in question get the release titles well in advance (30 minutes to 2 hours) before it actually gets posted on usenet.

**Comment by markus101** [comment]
This is exactly what `Minimum Age` (on the indexer settings page) is for. Since indexers report the date posted usually (the good ones are, but even when they don't if they're scraping quickly it's pretty close), it will take care of this regardless of which indexer Sonarr sees it on first and even if Sonarr saw it on the indexer, 10, 20 60 minutes after the indexer saw it.

**Comment by DFKnight** [comment]
That applies to all the indexers. Using this on a per indexer basis would be convenient for the scenario I described.

**Comment by markus101** [comment]
If they're all using the same post time and from some testing before they are pretty close, per indexer is irrelevant. OMG has their own delay (when not using the newznab indexer), which delays their RSS feed, but beyond that I don't see this being something we'll implement.

**Comment by DFKnight** [comment]
My concern is with nzbs.in and the alt.binaries.kenpsx (and similar) groups which have encrypted releases in them. nzbs.in is one of the indexers that can decrypt the release names and display them properly. Many other indexers can't do that. When a release gets decrypted by nzbs.in, it gets posted on their website. Then sonarr doess the RSS scan and only sees the release at nzbs.in, so it tries to download it. My downloader fails to download this release likely because it has not finished uploading to usenet (I'm not entirely sure how the upload process works). When sonarr sees the failed release, it blacklists it. 

30 minutes later, then the release gets posted to a group with non-encrypted file names, sonarr sees it and ignores it, because it had already blocked it. At this point, if I try downloading the encrypted release from nzbs.in again it succeeds (likely because it has been uploaded now). 

Now, I could use the Minimum Age field, and this will delay ALL my releases by the time I set. But what about the scenario where one of the indexer gets the proper release within the delay period, and I would like to have it downloaded instead of waiting for the delay period in the Minimum Age field? I would have to either do it manually, or wait for the time to expire. 

Again, this request is all about convenience, but I do believe there is a valid use case for having a per indexer delay, as opposed to a global delay.

**Comment by markus101** [comment]
> Now, I could use the Minimum Age field, and this will delay ALL my releases by the time I set. 

From the post time, not from when Sonarr first sees it. If Sonarr is treating the other releases as dupes then it has a similar release time and thinks they are the same and already failed.

Have you tried setting the Minimum Age?

PS some indexers don't like their name mentioned and is enough to get you banned...

**Comment by DFKnight** [comment]
Thanks for the heads up. I've removed all references to the indexer in my comment. but this issue has been an annoying one for quite some time now. Those releases keep getting blacklisted by sonarr, and I know it has to do with the names popping up in their list before the upload is complete. I didn't notice the Minimum Age field, but I will try using it now. However, I still think having that minimum age on a per indexer basis would be a good idea.

**Comment by DFKnight** [comment]
Looks like there's a delay feature in the indexer I mentioned. I will use it for now. Thanks for your help!
