### ISSUE TITLE
Usenet presets and RSS Sync issue

### ISSUE THREAD

**Issue by Sat0rN** [Sonarr/Sonarr#1695]
When using a newznab indexer it's not possible to specify custom RSS configs supported by the newznab provider.

For example: nzbs.org uses feeds with a total length of 25 entries (default, this is being used by Sonarr). The website has the option to change the number of results returned with &num=100, you place this at the end of the RSS feed.

Sonarr doesn't support this at the moment so if you have RSS Sync enabled on a feed that get's updated frequently, you're likely to miss episodes.

Request: add the option to specify the RSS feed total entries.

**Comment by Taloth** [comment]
What you're talking about is the rss feeds, not the newznab api.
Sonarr only supports the newznab api, not generic rss feeds for usenet.

Additionally, Sonarr uses the newznab paging feature. So it's not 'missing' anything. The newznab api uses 100 entries, with the 'limit' query param.
