### ISSUE TITLE
Utilize Video Codec on Series Details

### ISSUE THREAD

**Issue by stevenolsen** [Sonarr/Sonarr#1696]
AVC and HEVC are already stored in .nfo files so this information is already available. It would be nice if a user could display which codec was stored. Currently only the resolution and source is displayed (e.g. 1080p Bluray, 720p HDTV, etc.). It would be great if "1080p Bluray HEVC" was displayed and HEVC/AVC could be prioritized in the desired profiles.

Additionally, upon scanning for changes if it's noticed that the files got smaller but switched to HEVC, the quality would remain the same but it would be decided that the user manually re-encoded the files to HEVC.

**Comment by markus101** [comment]
Display it where?

>It would be great if "1080p Bluray HEVC" was displayed and HEVC/AVC could be prioritized in the desired profiles.

There is another GHI for preferred words already.

> Additionally, upon scanning for changes if it's noticed that the files got smaller but switched to HEVC, the quality would remain the same but it would be decided that the user manually re-encoded the files to HEVC.

If the filename is the same, Sonarr won't even notice it's been changed, unless there is a change to media info that forces it to rescan Sonarr would still store the old media info. Checking if every file is the same is the same as what Sonarr thinks it is gets expensive so existing files are ignored when rescanning the series folder unless they have gone missing.

**Comment by stevenolsen** [comment]
> Display it where?

Here perhaps?

![capture](https://cloud.githubusercontent.com/assets/5187453/23147622/44320c26-f795-11e6-9955-c499ddb92c5e.JPG)

> existing files are ignored when rescanning the series folder unless they have gone missing.

This is the only workaround I have discovered. Is to remove the files, and re-add them. Then they are recognized as HEVC in the nfo and the new file size is refreshed.

**Comment by markus101** [comment]
Gotcha, I have a few ideas where to put that, though it'd be a separate column probably.

**Comment by Taloth** [comment]
markus, I assume you wanted to do it in v3 only.

**Comment by markus101** [comment]
Yeah, it will fit with some of the other work I've done there.

**Comment by stevenolsen** [comment]
What does GHI stand for? You've referred to it in two issues. I've never seen that acronym before and a search doesn't yield anything.

I went to the restrictions tab on the indexers page, but that appears to be a hard restriction and not a preferred word.

**Comment by Taloth** [comment]
GHI = Github issue.

**Comment by thezoggy** [comment]
id rather have you show it with the file details screen.. radarr shows them in a Media Info column like quality... which kills the limited horz space..  example: `AVC (1280x536) (02:12:52) DTS (English)`

**Comment by markus101** [comment]
Depends on https://github.com/Sonarr/Sonarr/pull/1717

**Comment by markus101** [comment]
This is done as part of the v3 work.
