### ISSUE TITLE
Change to BTN API URL

### ISSUE THREAD

**Issue by Jamesmaps** [Sonarr/Sonarr#1699]
Taken from the BTN news article:

"As many of you have noticed, the BTN API domain expired several days ago. Anyone visiting btnapps.net will be greeted by a "Renew Now" page - we're aware of this, but we're taking advantage of the situation to move the API over to our main domain.

As of now, the API is up and fully functional at https://api.broadcasthe.net, with the docs available https://apidocs.broadcasthe.net/.

This change has been in the works for some time now, but the domain expiry took us by surprise (the staff member that handles domains is currently away); we would have preferred to communicate this change to you all ahead of time and we need to apologize for the abrupt change. We should also point out that there's no need to reset your API keys, passwords, etc. While btnapps.net may currently show you a strange site, it's simply a placeholder page; there's no reason to believe that your API keys have been compromised.

We're sure that the various tools which use the API (Sonarr, Sickbeard, etc) will update shortly to account for this change, so be on the lookout for new versions."

**Comment by markus101** [comment]
Already fixed: https://github.com/Sonarr/Sonarr/commit/060b9f6fd1de36a8c15ae8877dd64bc9e737e567

And already had another issue opened for it: https://github.com/Sonarr/Sonarr/issues/1698
