### ISSUE TITLE
Textbox to set the file size in the Quality Definitions instead of slider. 

### ISSUE THREAD

**Issue by basmith7** [Sonarr/Sonarr#1701]
This seems like a bad UI decision to use a slider to set a number. I just want to type in the size I want. Trying to slide to 2GB exactly is an effort in futility.

**Comment by markus101** [comment]
It's size per MB, not a raw size for your limits, with examples shown for 30 and 60 minute episodes, series listed with 45, 120, etc minute run times use the same calculation to determine the maximum run time. I'm not sure a text entry doesn't make things better as you'd type in a value and still need to verify that it matches what you want.

**Comment by Taloth** [comment]
Someone give him a screenshot of how it looked back in 2014. :smile:

**Comment by markus101** [comment]
Added some advanced text fields in the v3 UI work, not entirely sure how useful they will be, but we'll see.
