### ISSUE TITLE
"This app cannot run on this PC" after update

### ISSUE THREAD

**Issue by moonjazz** [Sonarr/Sonarr#1704]
After one of the automatic updates by Sonarr today at roughly 2pm Central Time, I was unable to even run Sonarr. Everything was working fine earlier before the update so it is no doubt an issue with the update. It seems as if the EXE is corrupt or unable to run on Windows 10 anymore? I have attached a photo below of what is happening.

![untitled](https://cloud.githubusercontent.com/assets/24802018/23195346/6ea9602e-f878-11e6-9dbf-cb664392c4f5.png)

**Comment by markus101** [comment]
Both `NzbDrone.exe` and `NzbDrone.Console.exe` are running for me without issue on Windows 10.

It looks like the update process may have been interrupted as some files are older than others... Best to check the update log files to see if the update failed (inside https://github.com/Sonarr/Sonarr/))wiki/AppData-Directory) as well as the log files in that same folder.
