### ISSUE TITLE
Possiblity to change the scheduled intervals

### ISSUE THREAD

**Issue by royduin** [Sonarr/Sonarr#1708]
I'd like to come back on this one: https://github.com/Sonarr/Sonarr/issues/963 (Synology DSM hibernation), it would be nice if there was a option to change the task intervals. For example, instead of scanning my drone factory every minute, rss sync every 15 minutes, etc. I'd like to say: do everything with a minimum interval of x hours. So every x hours my NAS wakes up, run the tasks en goes back to sleep.

**Comment by markus101** [comment]
Both Drone Factory (setting it to zero and not using it at all would be the best as it's simply not required) and RSS Sync can have their schedules set, but there are still things that will be running in the background regardless of of those intervals, there are no plans to make those background tasks configurable, though there could be some automatic changing of them (based on current activity).

**Comment by mmartinortiz** [comment]
Is there a reason for having the [time interval hardcoded](https://github.com/Sonarr/Sonarr/blob/816cf608fcef07e375aa750a863d0a7365108981/src/NzbDrone.Core/Jobs/TaskManager.cs#L64)?

 If they were in a configuration file the intervals would be easy to change. The **CheckForFinishedDownloadCommand** is saturating my Raspberry Pi with IO operations, and I think that setting these intervals to other values would solve the issue.

**Comment by PiscisSwimeatus** [comment]
Or at least don't reset them on housekeeping, so changes advanced users does in the database makes them permanent.
