### ISSUE TITLE
Execute flag is removed on update

### ISSUE THREAD

**Issue by stoeff42** [Sonarr/Sonarr#1709]
I am running Sonarr on Ubuntu Linux 16.10.
I am using the apt repository for updates, which removes the execute flag on the executable on every update. This prohibits further starts of the executable and requires to set the execute flag  on the executableagain manually, which defeats the purpose of an automatic install.
Can you ensure the execute flag on the executable is not removed on every update?

**Comment by markus101** [comment]
Executable flag on `NzbDrone.exe`? Running through mono the `NzbDrone.exe` doesn't need to be executable.
How are you running Sonarr?

**Comment by Taloth** [comment]
@markus101 probably this: http://www.mono-project.com/archived/guiderunning_mono_applications/#registering-exe-as-non-native-binaries-linux-only
Basically telling the kernel how to run it. similar to the #!/bin/bash stuff in .sh files.
Still, it isn't advisable since that we can't set mono cmdline params like --debug

**Comment by stoeff42** [comment]
With the executable flag set, there is no need to run through mono. NzbDrone.exe is a normal linux binary and can be executed without an interpreter.
But in the installation notes you actually describe starting NzbDrone using mono:
[https://github.com/Sonarr/Sonarr/wiki/Installation#linux](url)
I will therefore not insist in running it in this way. Thank you for your support!

**Comment by Taloth** [comment]
Thank you for your understanding.

@markus101 Do we want to keep this issue open so we can change it in the v3 packages? Or leave it as is?

**Comment by markus101** [comment]
I'm tempted to leave it as-is. I think it's a minority feature (this is the first I've heard of anyone using it with Sonarr) and we're more a background service that wouldn't be started by clicking an icon on the desktop in most cases. It also doesn't include the debug switch as you pointed out and that's pretty important to us.
