### ISSUE TITLE
Ability to ignore episodes from queue page in the download client (will not be imported)

### ISSUE THREAD

**Issue by beeblebrox** [Sonarr/Sonarr#1710]
I noticed some torrents were remaining in the Activity list.  It turns out that I already have resulting episodes imported of equal or better quality.  This results in this log `07-2-23 03:48:10.7|Debug|UpgradeSpecification|This file isn't an upgrade for all episodes. Skipping <...>`

At this point the torrent seems to get stuck under activity and I don't think it ever gets cleaned up when seeding is done either.  Shouldn't the import logic go an extra step and mark it completed so it is removed from activity and move on?  In this situation, it seems like my only option is to click remove from download client on the activity list?  That isn't desirable.

What are your thoughts?

**Comment by markus101** [comment]
Since they aren't imported Sonarr doesn't see them as done and wouldn't do anything with them. We may need a way to manually set it as complete in that case, what do you think @Taloth? Would either need something new or a way to add it to history hidden (could also tie into our clearing of history, but really it's just hidden).

**Comment by Taloth** [comment]
It's basically an exceptional situation that requires user-intervention. I dunno if it offer a manual/force import, it probably should if it doesn't. The option is to force import (overwriting the non-upgrade file), or to remove the download. I don't think Sonarr should make a decision for the user.

**Comment by markus101** [comment]
I believe it will show manual import there, but there isn't a way to not import and ignore it, leaving the only option to delete it from the download client, change the category or import it and overwrite whatever quality it there.

**Comment by beeblebrox** [comment]
Changing the category was a very simple workaround, thanks @markus101!

The manual import is not so easy. I had over 80 items trigger this at once, and you can only do the import for a single item at a time.  ff it really was lower quality I don't want the import anyway.  

If I could make a request it would be marking the item in activity to make it clear that it is failing to import and requires manual intervention. Perhaps even a tooltip with the workaround in it? 

Here is my usecase in which this will probably happen again:  I did a search for missing and sonarr grabbed a ton of things thinking it was better quality (I guess?) the importer disagreed. I do this if my server has a disruption for a period of time which prevents Sonarr from operating.

**Comment by markus101** [comment]
> If I could make a request it would be marking the item in activity to make it clear that it is failing to import and requires manual intervention. Perhaps even a tooltip with the workaround in it?

The icon on the left should have the information why it's not importing, it doesn't explain how to fix it, but should point you in the correct direction.

> Here is my usecase in which this will probably happen again: I did a search for missing and sonarr grabbed a ton of things thinking it was better quality (I guess?) the importer disagreed. I do this if my server has a disruption for a period of time which prevents Sonarr from operating.

Depending how long Sonarr has been offline it might find releases via RSS and if the search was done at the same time it might have caused duplicate episodes to be added.

Multiple actions from the queue has it's own GHI (https://github.com/Sonarr/Sonarr/issues/792) and if implemented along with a way to ignore an item in the download client queue (if that's something we end up doing), would hopefully make this less on an issue.

**Comment by austinwbest** [comment]
How is this still not implemented... Is there any timeframe for this trivial (yet quite helpful) feature?

**Comment by markus101** [comment]
> How is this still not implemented...

Time and realistically, it's an enhancement, not a fix for a large issue.

>Is there any timeframe for this trivial (yet quite helpful) feature?

"Trivial", I disagree.

> So how about just simply removing them from the queue if they are imported

Sonarr already does that if the import path/ID from the download client matches the item in the queue, this change is for the edge case where it doesn't. If most/every download is doing that for you open a thread on the forums for support.

**Comment by austinwbest** [comment]
Trivial it is. When you click the button to remove from queue there is a step that sends a message to the download client to also remove it. That step being skipped is all that is being asked for.

And no it isn't most /every nor did I say it was. As with the nature of people naming things, it is often enough that things are not named properly or many other scenarios that lead to this issue. That should be obvious with a ticket from years past still being active. 

However I get your point of lack of importance. Thanks for the reply.

**Comment by markus101** [comment]
> When you click the button to remove from queue there is a step that sends a message to the download client to also remove it. That step being skipped is all that is being asked for.

It being in the download client is why it's in Sonarr's queue. We could just skip the removal, but then it'd show up in the queue a minute or so later. Sonarr needs a way to ignore them, it's not trivial, but it's not exactly complicated either, it's definitely not high priority.

If you import a poorly named release that Sonarr shows in it's queue from the queue page then Sonarr will effectively ignore it. If you do something manual or outside of that then it may not depending on what you do.

**Comment by austinwbest** [comment]
I have over 700 items in the download client that are not showing up in Sonarr. So after it is imported then there is a flag set (or similar) to tell Sonarr to not look for that anymore. Repeat this process and again, arrive at the end result without actually deleting the file. Basically do every step that is currently done except delete it.

Not trying to be a pain but i'm missing the difficult part, sorry.

**Comment by austinwbest** [comment]
`https://github.com/Sonarr/Sonarr/tree/phantom-develop/frontend/src/Activity/Queue`

I'll start here and work my way backwards, at some point i should run into the difficult part of this and then i'll have a better understanding i guess :)

**Comment by austinwbest** [comment]
BTW, I am trying to be helpful as I think the app is very well put together. If that means doing it myself so be it as I think this is more important than fully thought about. Seeding is critical so removing them is something to think on but for ppl like myself who dislike warning messages, it makes it difficult to do easily. I wouldn't take the time to post if I didn't think it was worth the effort. Been at this a long time & I can tell when something is taken care of (from a code perspective) so to speak & this is.

**Comment by austinwbest** [comment]
Another issue here, when deleting from the Queue using the X to the right of the line item you see the warning about removing from the download client. When removing from the top "Remove Selected" you dont so that also leads one to believe it isn't going to be removed from the client when doing it that way opposed to using the individual X :)

**Comment by austinwbest** [comment]
So i have merged the **phantom-download-processing** with the current **phantom-develop** so it could have the last couple months of changes. I have built it and have it running on my local against my current directory of files (only 1 merge conflict which was nice). I see your implemented changes so far but the "do not delete" checkbox is not enabled at this time. Can you email me or something and let me know where you left off with this so i can see what i can do to help finish/test this branch?

Thanks bud!

**Comment by austinwbest** [comment]
Alright so nevermind, good luck with it.

**Comment by beeblebrox** [comment]
Thanks @markus101!

**Comment by austinwbest** [comment]
👍
