### ISSUE TITLE
DS Station

### ISSUE THREAD

**Issue by foXaCe** [Sonarr/Sonarr#1711]
@Taloth @margaale 
After this patch 
DownloadStation proxy failing if non-bt/nzb downloads exist.

sonarr does not see the queue in DS Station

**Comment by Taloth** [comment]
I suspect it's a case sensitivity issue, if so it would fixed by https://github.com/Sonarr/Sonarr/commit/f7e3d9b4c2318f0051bd7353c99fd05b56b47090 
But I'm at work, so this is the best I can do right now.

**Comment by foXaCe** [comment]
thank fixed

**Comment by Taloth** [comment]
Tnx for letting me know.
