### ISSUE TITLE
Indexer: TorrentDownloads.me

### ISSUE THREAD

**Issue by ireun** [Sonarr/Sonarr#1722]
Hello!

I would like to ask You to add a new indexer, I'm talking about http://www.torrentdownloads.me/

It would be a good replacement for Kickass Torrents, that's dead as we all know. I can see that this was requested some time ago, has anything changed with the API support of this site?

**Comment by Taloth** [comment]
That's a question you should ask torrentdownloads.me, we don't actively monitor whether sites get api supports.
If you're active on the site, you might ask them whether they're interested in implementing torznab. It's fairly simple (depending now accurate they want it to be), and would mean most apps support it out of the box.
(Torznab is an api specification based on rss & query params to filter results, and thus supports a 'recent' feed and search capability)

**Comment by ireun** [comment]
Thanks, no, I'm not an active user of this site, i was just looking for a good alternative of KickAss and found it, also, could I ask why TorrentLeach indexer doesn't support searching? This feature is available on this site..

**Comment by markus101** [comment]
For the same reason, they don't have a proper API.

Torrent RSS is available within Sonarr to support indexers that don't have an API, but do have a sane RSS format (not all of them do) though.
