### ISSUE TITLE
qbitorrennt label inconsistently set

### ISSUE THREAD

**Issue by danpowell88** [Sonarr/Sonarr#1725]
Using qbitorrent 3.3.10 and latest sonarr  (2.0.0.4613) on Win 10 x64 labels/categories are not always applied to the torrents sent to qbitorrent.

When the label is applied it is the correct label name but it only happens sometimes, I cannot narrow down any particular behaviour that triggers it, ive had it happen with RSS downloads and manual searches.

Logs show nothing of interest in qbitorrent and sonarr

**Comment by markus101** [comment]
Setting the label comes after adding the torrent if either those operations fails (according to Sonarr) then that would do it.

Please open a thread on the forums with Debug logs and the other requested information.
