### ISSUE TITLE
Allow setting a default viewing mode when you view the series page.

### ISSUE THREAD

**Issue by t3xtb0ok** [Sonarr/Sonarr#1728]
Every time I open sonarr the series page is automatically on overview list mode. I prefer Poster viewing mode, so every time I have to manually switch it.

Can you please allow sonarr to keep a users preferred viewing mode in the sonarr config?

**Comment by markus101** [comment]
Sonarr saves it to a local storage variable, if your browser is clearing those automatically then it will be reset each time.
