### ISSUE TITLE
Completed download handling not fully working for Deluge

### ISSUE THREAD

**Issue by TerrorFactor** [Sonarr/Sonarr#1729]
I noticed that Sonarr is able to import torrents from Deluge, but it can't seem to delete them. 
Deluge is moving completed downloads to downloads\completed. It uses a plugin to stop seeding (general rule: after 15 minutes - private tracker: after a day).

The affected downloads are paused (there is no stop-status in deluge), so they are not seeding.
The files are imported to my tv library. I am using hardlinks instead of a move.

Settings>Download Client: Completed Download Handling: enable:yes, remove: yes.
No drone factory was set up.

Sonarr runs in a docker container, deluge runs also in a (different) docker container, both from linuxserver.io

If any logs are needed, which are needed?

**Comment by markus101** [comment]
Please open a thread on the forums for support, including Debug logs where the torrent should be deleted.
