### ISSUE TITLE
Sonarr fetches torrents with 0 seeders

### ISSUE THREAD

**Issue by BetaLeaf** [Sonarr/Sonarr#1730]
Sonarr is often fetching torrents with 0 seeder, only peers. As a result, no one has the completed download and it stays in limbo forever. Is there a way to enforce minimal seeders to at least 1 or more?

Labels: Enchancement; Proposal

**Comment by markus101** [comment]
Sonarr already requires a minimum of one seeder. If you're seeing different behaviour please open a thread on the forums that includes debug logs showing a grab f a release with need seeders, only peers. We'll also need to know which indexer is being used.
