### ISSUE TITLE
Systemd loses process after restart.

### ISSUE THREAD

**Issue by SamMousa** [Sonarr/Sonarr#1731]
When using systemd (directly copied configuration from the wiki) as service manager it will lose the PID after a restart.

Reproduce:
1. `systemctl stop sonarr` (just to be in a known state).
2. `systemctl start sonarr`
3. `systemctl status sonarr`:
````
● sonarr.service - Sonarr Daemon
   Loaded: loaded (/lib/systemd/system/sonarr.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-03-03 10:50:19 EST; 1s ago
 Main PID: 4699 (mono)
   CGroup: /system.slice/sonarr.service
           └─4699 /usr/bin/mono /opt/NzbDrone/NzbDrone.exe -nobrowser
````
4. Go to the sonar GUI choose restart.
5. `systemctl status sonarr`:
````
● sonarr.service - Sonarr Daemon
   Loaded: loaded (/lib/systemd/system/sonarr.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Fri 2017-03-03 10:54:53 EST; 22s ago
 Main PID: 4771 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/sonarr.service
           └─4829 /usr/bin/mono --debug /opt/NzbDrone/NzbDrone.exe /nobrowser /restart
````

Systemd loses the process after it restarts itself (and thus gets a new PID).

**Comment by SamMousa** [comment]
One option would be to use: https://www.freedesktop.org/software/systemd/man/systemd.service.html#RestartForceExitStatus=

If sonarr can die with a specific exit code after an update / gui restart command then systemd could restart it, this could be toggled by a command line argument.

**Comment by markus101** [comment]
Thanks for the info, closing in favour of the existing issue related t restarting from the UI: https://github.com/Sonarr/Sonarr/issues/971
