### ISSUE TITLE
Pushover not working on Synology

### ISSUE THREAD

**Issue by Logan09** [Sonarr/Sonarr#1733]
After the last couple of updates, pushover does not work anymore. Testing the connection results in a failed message.

Version
2.0.0.4613
Mono Version
4.6.2

**Comment by Logan09** [comment]
Forgot to mention, this is on Synology DS1515+ version:

DSM 6.1-15047 Update 1

**Comment by markus101** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please open a thread on the forums for support...
