### ISSUE TITLE
Health check callbacks to retest/revalidate

### ISSUE THREAD

**Issue by griddoz92** [Sonarr/Sonarr#1735]
I keep getting indexer failures and the ability to automatically retest all indexers with the Heath check task would be a lot less tedious than manually testing each one because I use 10 different indexers with jackett

**Comment by markus101** [comment]
The health check task is meant to report issues, not retest things automatically, though I'm not against having the ability to invoke a retest from the health check page.

**Comment by griddoz92** [comment]
That would be a great idea

**Comment by ronajon** [comment]
second that

**Comment by nhsqr** [comment]
That feature will be really great!
I am tired of doing retest after failure of all 16 trackers I have.

**Comment by EmilioMoreno** [comment]
Hi, +1 to that. My indexers are most of the time reported offline, and manual check always return ok, and jackett test does the same also. Logs suggest timeout, probably as some of them sometimes takes more than 1 min to check, but in any case, having to go manually one by one is a problem when you have several of them

Also, incremental delay up to 24h does not help; as this means everything can be working flawlessly but you are missing content, so this feature would be great.

**Comment by lutzky** [comment]
Is there an API call to perform an indexer test? I'd like to add a workaround cron job to periodically retest indexers.

**Comment by epheterson** [comment]
Can we please do this? I came here to file the same bug, I think a great way to do it would be to add a periodic task so that it shows up in the UI and can be triggered on demand.

**Comment by epheterson** [comment]
Looks like we're already getting this in v3

**Comment by markus101** [comment]
Yeah, this is in v3.
