### ISSUE TITLE
New episodes are not downloading. Error: Couldn't add report to download queue.

### ISSUE THREAD

**Issue by desimaniac** [Sonarr/Sonarr#1739]
Couldn't add report to download queue. APB.S01E05.720p.HDTV.x264-AVS[rartv]: Specified cast is not valid.	

http://pastebin.com/ziD2HfFH

Couldn't add report to download queue. APB S01E05 720p HDTV x264-AVS[PRiME]: Error: ConnectFailure (Connection refused)

http://pastebin.com/nhP6Bn8S

**Comment by markus101** [comment]
Please use the forums for support. We'll need the information requested when opening a thread to troubleshoot.

The first error could be an issue with mono 4.8 (being that it is new and we haven't seen much use of it), it's rather suspect.
The second was connection refused (by the remote host), firewall, wrong port and lots of other possible causes.
