### ISSUE TITLE
Request: host the api on different port than main system

### ISSUE THREAD

**Issue by Garderoben** [Sonarr/Sonarr#1740]
I would like to host the Sonarr api on a different port from the main system.

Sonarr cant be reached on http/https from the outside.
Sonarr Api can be reached on http/https from the outside.

I don't want to publish the whole Sonarr interface for the internet but the Api would be good.
In that way you can have other applications hosted in other sites talking to it.

**Comment by Taloth** [comment]
Just use a reverse proxy like with nginx, you can easily map multiple of your services using that. And you can centralize the https there.

We're not going to add another port just to expose the api separately.

FYI, Sonarr's WebUI is built on top of the api itself.
