### ISSUE TITLE
Filtering/Sorting Series via Genre or Rating

### ISSUE THREAD

**Issue by dlang123** [Sonarr/Sonarr#1743]
I mainly want to be able to view my shows, or my kids shows.

**Comment by markus101** [comment]
That would probably be better suited for filter via tags: https://github.com/Sonarr/Sonarr/issues/566

**Comment by markus101** [comment]
Filtering by Genre or sorting by rating seems valid.

This may require some server work to accomplish filtering by genre (to get the list of genres across all shows) and definitely requires more advanced filters.

**Comment by markus101** [comment]
Done in the v3 work.
