### ISSUE TITLE
Sonarr downloading previous week's episode

### ISSUE THREAD

**Issue by mattswest** [Sonarr/Sonarr#1744]
So far I have found two different series where Sonarr had been filling episodes with the one from the previous week. 

http://i.imgur.com/Fmyp041.png (nzbget queue was stalled)

http://i.imgur.com/N2KcBA6.png (I set all the 'bad' episodes to DVD to facilitate replacement)

Nothing helpful in the logs since debug hasn't been enabled.

```
17-3-5 20:35:00.6|Info|DownloadDecisionMaker|Processing 700 releases
17-3-5 20:35:06.9|Info|Nzbget|Adding report [The.Simpsons.S28E16.720p.HDTV.x264-FLEET] to the queue.
17-3-5 20:35:07.1|Info|DownloadService|Report sent to NZBGet. The.Simpsons.S28E16.720p.HDTV.x264-FLEET
```

The Simpsons has only been off for a few weeks, since a two-parter aired, (maybe that had something to do with it) but The Late Show has been getting the wrong episodes for about 3 months.

I've enabled debug logging to possibly catch more information if it happens again.

**Comment by markus101** [comment]
Please use the forums for support.

Recent post about The Simpsons: https://forums.sonarr.tv/t/sonarr-searching-for-future-episodes-of-the-simpsons-and-downloading-incorrect-files/13921/2
The Last Show is likely that they have the dates listed in a conflicting way (they air on one day but are listed as airing the day before).
