### ISSUE TITLE
Can't use example.com/example when adding download clients

### ISSUE THREAD

**Issue by StrayanDropbear** [Sonarr/Sonarr#1747]
Title pretty much explains it 
![chrome_2017-03-09_17-17-47](https://cloud.githubusercontent.com/assets/6562040/23743763/df6b63e0-04ec-11e7-9938-813a040dc54f.png)

returns "must be valid Host without http://"

**Comment by markus101** [comment]
Dupe of: https://github.com/Sonarr/Sonarr/issues/1651
