### ISSUE TITLE
Dynamically Alter Check For Finished Downloads interval

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1750]
With faster internet speeds and downloads finishing in seconds instead of minutes the `Check For Finished Downloads` task could run more frequently when there is work to do and slow down when the download client is idle/not as busy.

Right now it runs between 60 and 90 seconds apart, depending on when the timer ticked and how long it took to execute, so something that downloads in 20 seconds sits there for a while in addition to the queue never updating the progress (it's likely it will be imported before the queue actually updates in that case).

I'd like to see the timer tick every 5 seconds and the `Check For Finished Downloads` task would run by default every minute, if a download was sent from Sonarr to the download client we'd run it every 5 or 10 seconds, if it takes a long time to run it will be running a lot, but won't run multiple times, but won't run immediately back to back, the same thing would happen if Sonarr detected a new item in the download client queue, it would speed up until the item was complete or was removed and slow back down.

If the task takes a while to run (lot's of torrents maybe) we could increase the interval to average it out over the last X number of runs so it's running at most around 50% of the time (which would also help keep CPU usage down).

**Comment by Taloth** [comment]
I think you need to be real careful with this, we already have a noticeable impact on the api of certain clients, especially those with a large amount of torrents.

**Comment by LSL1337** [comment]
yeah, but if my deluge only runs a few torrents, than it can't be that big deal.
I'd love this feature, but I think still this is the most 'first world problem' I've ever seen :)

maybe make it download client setting, and if somebody wants to opt in, they can
just my 2cents

**Comment by ebalders** [comment]
I would like to add that this would not only speed up addition of completed downloads, but could potentially save lots of time when downloading episodes that have several bad releases. You could have a situation where every failed download takes up to 90 seconds to update in sonarr. With some older episodes, this greatly increases the amount of time required to successfully pull the episode down.

**Comment by jalmansor** [comment]
If the download client has a websocket, that seems like it would be a much better way of getting the completed status (I'm not sure how many do). Alternately if the download client has webhooks that could be another option. I personally just dislike scheduled tasks for things that could do better.

This is something that's been on my mine since upgrading to gigabit fiber last year, so I'm just tossing things out and seeing if anything sticks.

**Comment by markus101** [comment]
Unfortunately there has been maybe one or two clients that use websockets and one that was purely websockets so polling is the only real way forward here and aggressively polling will cripple some clients.

Throwing this into the someday maybe pile.

**Comment by winklevos** [comment]
Would be nice to have, even if just an options with a disclaimer. 

Not sure exactly how it works now but if the clients have APIs which only return completed items that could work or dynamically setting it based on how many items there are

**Comment by danbopes** [comment]
Just came here to this. 60 seconds with super fast download speeds lags the amount of time it takes to show the final result to the user. Would love to see lower refresh times supported.

**Comment by ZimbiX** [comment]
Workaround to externally trigger the refresh task every 5 seconds using [Managarr](https://github.com/Dark-Alex-17/managarr) on Arch Linux:

```
➜ cat /usr/lib/systemd/system/servarr-refresh-monitored-downloads.service
[Unit]
Description=Servarr Refresh Monitored Downloads
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=brendan
Group=brendan
ExecStart=/bin/bash -c "{ while :; do managarr radarr start-task --task-name refresh-monitored-downloads --disable-spinner; managarr sonarr start-task --task-name refresh-monitored-downloads --disable-spinner; sleep 5; done } >/dev/null"
Restart=always
RestartSec=1
StartLimitInterval=0

[Install]
WantedBy=multi-user.target
```

Edit: Just using NZBGet, the task takes 2 seconds for Sonarr, and 1 second for Radarr

**Comment by JohnCronk79** [comment]
Hey guys and gals, I know this is a very old topic, but the same polling delay is still present and I recently did some testing against it.

Using the same workload of 187 sabnzbd attempts, reducing sonarr's polling interval from 60 seconds to 15 seconds reduced the time sabnzbd had no pending work from 321 seconds to 163 seconds. It also did a much better job of keeping the sab queue populated on my 2Gb internet connection.

I opened a newer issue with a configurable polling interval proposal here: https://github.com/Sonarr/Sonarr/issues/8891

I have now implemented the setting in my custom sonarr v4 build and am doing larger benchmark testing with a 10 second polling interval. I thought anyone still following this old discussion might be interested in the results.

**Comment by LSL1337** [comment]
I think I already posted another solution somewhere else, maybe on reddit or on another topic, or in the radarr project, but the easiest and fastest workaround is to have the download client send an API call to force a refresh from sonarr/radarr. just an event on torrent complete. qbittorrent can do it based on labels, so 1 label to 1 API, and no need to do this work periodically with increased frequency, just leave it as is, and add an ad-hoc API call. This way it is possible to have a source uploaded, grabed from IRC in 0 seconds, sent to client, which can finish it in 10-20 seconds, and sonarr can pick it up in the next second. End-to-end process less than 1 minute from publish to media server. it's pretty sick :)

**Comment by jk1993** [comment]
> I think I already posted another solution somewhere else, maybe on reddit or on another topic, or in the radarr project, but the easiest and fastest workaround is to have the download client send an API call to force a refresh from sonarr/radarr. just an event on torrent complete. qbittorrent can do it based on labels, so 1 label to 1 API, and no need to do this work periodically with increased frequency, just leave it as is, and add an ad-hoc API call. This way it is possible to have a source uploaded, grabed from IRC in 0 seconds, sent to client, which can finish it in 10-20 seconds, and sonarr can pick it up in the next second. End-to-end process less than 1 minute from publish to media server. it's pretty sick :)

Also recently found this same workaround for sabnzbd, which requires no additional tools like managarr and unnecessary increased polling. Simple as creating a scripts folder in your sabnzbd config folder. Then in sabnzbd, ensure you have a scripts folder selected and mapped to the folder you created, then under "Notifications", enable a "Notification Script", select the script in your scripts folder and have the toggles enabled for "Job Finished" and "Job Failed". The script is as follows, mine is called "servarr-refresh,py":

```python
#!/usr/bin/env python3

import sys
import json
import urllib.request
import urllib.error

# ------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------

SONARR_URL = "http://YOUR_SONARR_IP:8989"
SONARR_API_KEY = "YOUR_SONARR_API_KEY"

RADARR_URL = "http://YOUR_RADARR_IP:7878"
RADARR_API_KEY = "YOUR_RADARR_API_KEY"


def refresh(name, base_url, api_key):
    url = base_url.rstrip("/") + "/api/v3/command"

    data = json.dumps({
        "name": "RefreshMonitoredDownloads"
    }).encode("utf-8")

    request = urllib.request.Request(
        url,
        data=data,
        headers={
            "Content-Type": "application/json",
            "X-Api-Key": api_key
        },
        method="POST"
    )

    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            print(
                "{}: RefreshMonitoredDownloads triggered (HTTP {})".format(
                    name, response.status
                )
            )
        return True

    except urllib.error.HTTPError as error:
        print("{}: HTTP error {}".format(name, error.code))
    except urllib.error.URLError as error:
        print("{}: Connection error: {}".format(name, error.reason))
    except Exception as error:
        print("{}: {}".format(name, error))

    return False


# SAB passes the notification type as the first argument.
# We only care about successful completed or failed jobs.
if len(sys.argv) < 2 or sys.argv[1] not in ("complete", "failed"):
    sys.exit(0)

sonarr_ok = refresh("Sonarr", SONARR_URL, SONARR_API_KEY)
radarr_ok = refresh("Radarr", RADARR_URL, RADARR_API_KEY)

sys.exit(0 if sonarr_ok and radarr_ok else 1)
```

**Comment by JohnCronk79** [comment]
@jk1993 
wow, thanks for showing me your script, i appreciate the time you took to post this. I'll have to look into this further. thanks again
