### ISSUE TITLE
Not downloading to proper configured download folder - rtorrent

### ISSUE THREAD

**Issue by testarea1** [Sonarr/Sonarr#1756]
Sonarr 2.0.0.4651

After update to 2326db0deabb387a1020466ae66e8cdbe5e6c2c2, Sonarr is downloading all files to the root of the rtorrent server client instead of using the configured path set in the "Directory" field in the Download Client area for rtorrent client. 

This was working fine before this update, but it now appears to not use the "Directory" field from the download client configuration any longer.

**Comment by Taloth** [comment]
Awesome, tnx for reporting, this is exactly why we have a develop branch.

**Comment by Taloth** [comment]
There you go, fixed and I tested it in an rtorrent docker container. Will be a bit till the build agent spits out a new release.

https://github.com/Sonarr/Sonarr/commit/2bf3b9e7dd799953b4f5c53db6212bf720ed41f1
