### ISSUE TITLE
Problem with Deluge

### ISSUE THREAD

**Issue by giacomofabbri** [Sonarr/Sonarr#1757]
Hi guys!!
Since last month I have this problem with Sonarr where it's able using Jackett to download from a private tracker and correctly add to Deluge but then it can't "communicate" between them to add it to Plex, etc.
And from Sonarr I get this error 
Unable to communicate with Deluge. Object reference not set to an instance of an object
I have installed the latest available public build of Sonarr and my Ubuntu configuration it's up-to-date.
P.S. Everytime that I reboot my dedicated server Sonarr doesn't show that error, but after some time it reappear the error!
Please help me, thanks so much! And if you need some other info just let me know, thanks!!

**Comment by markus101** [comment]
Please open a thread on the forums for support.
