### ISSUE TITLE
Setting for default page

### ISSUE THREAD

**Issue by deathbybandaid** [Sonarr/Sonarr#1761]
I, like many others have a larger library of shows. When I navigate to localhost:8989 , (or any other way I have set up to access Sonarr), the default page is the "Series" page. Even with the page set to display in "Table" the page takes a bit of time to load.

My workaround has always been to go directly to the calendar page, since it loads faster, and also provides the information that I want to see.

What I'm suggesting is an option within the settings to set a "default page", just to select which page loads when I go to Sonarr.

**Comment by markus101** [comment]
You can use a bookmark in your browser to do that, Sonarr will redirect from the login page to the page you attempted to load if authentication is required

We don't have plans to allow setting a default page, but do plan to improve the loading of the main page.

How many series are we talking about here?

**Comment by deathbybandaid** [comment]
I can easily set a bookmark, and I use muximux to go directly to the calendar page. I know a few people using Sonarr that have the same issue.

I currently have Sonarr handling 1355 series.
