### ISSUE TITLE
[Warn] DownloadService: Torrent Download client isn't configured yet.

### ISSUE THREAD

**Issue by kicker83** [Sonarr/Sonarr#1766]
Hi!,

I have configured my download client with a Download Station, and Sonarr is always saying this "[Warn] DownloadService: Torrent Download client isn't configured yet."

I tried to redefine the download client, restart Sonarr, and always say the same error.

Anyone could help me please?

Thanks!

**Comment by markus101** [comment]
Please use the forums for support.

It sounds like you may have setup a usenet download client instead of a torrent one.

**Comment by kicker83** [comment]
It's embarrasing for me v_v

I'm so sorry about that, I've been checking this about 2 hours.

Thanks

**Comment by Taloth** [comment]
> 2 hours.

I'd say that's punishment enough.

**Comment by Devo-McDuff** [comment]
I did the same thing, oops! Thanks for the fix.

**Comment by jfmou** [comment]
Lost a fucking day for the same reason. 
Maybe is there a quick ui win to avoid dumb people like us who aren't able to open our eyes ?
Love you product anyway 🥂

**Comment by darkjedeye** [comment]
I have this error Request Failed. POST /api/release: Usenet Download client isn't configured yet an i have setup utorrent as client and i have setup web ui and can use it externaly aswell... where did i go wrong?
