### ISSUE TITLE
TVDB API v2 - Flexible Seasons

### ISSUE THREAD

**Issue by Metigoth** [Sonarr/Sonarr#1767]
https://forums.thetvdb.com/viewtopic.php?f=3&t=36183

It allows better naming and lookup of files DVD, airdate, popular, default, and etc.  It will help with animated shows and ones that tvdb decided should be in a different order.

**Comment by Metigoth** [comment]
http://platypus.thetvdb.com/api

**Comment by markus101** [comment]
That looks to be their new site, nothing new from an API standpoint (which Sonarr would use). Their v2 API was announced/released a while ago and there is some work being done on that within Skyhook (but far from a place where it is ready to be used).

**Comment by markus101** [comment]
Looks like I was hasty in closing this and there is more than I saw originally:

Flexible seasons:

> Over the years, we've heard your complaints about how our episodes don't match up to what you'd expect.  We know that some series, like Firefly, make far more sense sorted by Joss Whedon's preferred order rather than the order the episodes were aired.  We know that our old air date, DVD, and absolute ordering system was restrictive and at times annoying.

>To get around this issue, we've implemented something called flexible seasons.  Our moderators are now able to enable any number of alternate orders for specific series (at their discretion).  The episodes exist outside the season structure, which means each episode can be attached to various types of seasons without needing to recreate the episode (and cause management issues).

> Not only does this allow us to handle things like Director's Preferred and Popular season types, but also gives us flexibility over series that use joined or split episodes depending on the format.  For example, Looney Tunes episodes that were originally aired individually, but later joined into two-part episodes, can now be structured both ways.

I've asked if this includes relationships between episodes in different seasons where one order has split episodes and the other joined and whether if I have the split episode I could find out the joined episode or having the joined episode find the split episodes.

**Comment by Taloth** [comment]
I don't see much difference. The reason we didn't have support for dvd order was because we'd have to track the chosen order somehow to prevent the renaming from becoming a total mess.
If you have 'Flexible seasons' that's definitely an improvement over dvd order and in theory could replace _some_ of the stuff currently on TheXEM, but we'd still have the same original issue to deal with.

**Comment by Metigoth** [comment]
Let the user decide if the show has already aired it would be easier to find dvd or bluray releases which would be in that order.  Animated shows would not be the default order thetvdb when posted as S01E01E02 , S01E03E-4 they would be S01E01, S01E02.  It would be more like the DVDorder metadata plugin for Plex not the default but be allowed to selected for manual override.

**Comment by markus101** [comment]
No short term plan for this, closing for now.
