### ISSUE TITLE
Healthcheck for download client wrongly failing

### ISSUE THREAD

**Issue by xcorp** [Sonarr/Sonarr#1771]
I got a healthcheck failing with the message 
"Unable to communicate with Deluge. Object reference not set to an instance of an object"
When testing the connection from the settings page it works fine.

**Comment by markus101** [comment]
Without debug logs from when the health check ran it's impossible to say why happened, except that it failed at that time. Restarting Sonarr or re-running the health check message should clear the health check warning though.

**Comment by xcorp** [comment]
Thanks, for the swift reply.
I've tried restarting Sonarr with no result.
This is what I get in the output, is it enough or do I need to start with some flag for debug?

```
[Error] DownloadClientCheck: Unable to communicate with Deluge
[v2.0.0.4645] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Download.Clients.Deluge.Deluge.GetItems () <0x4204c3c0 + 0x00309> in <filename unknown>:0
  at NzbDrone.Core.HealthCheck.Checks.DownloadClientCheck.Check () <0x420395c0 + 0x00130> in <filename unknown>:0
```

**Comment by markus101** [comment]
Mono needs to be running with the `--debug` switch. Debug logs are separate logs that need to be enabled in settings (https://github.com/Sonarr/Sonarr/wiki/Log-Files).

If the issue is re-occurring you may want to restart Deluge and the Deluge Web API to ensure it is functioning properly (though `Test` should verify the same thing).

**Comment by xcorp** [comment]
Thanks, after a restart of Deluge it seems to work. Strange that the test was successful before the restart though.
