### ISSUE TITLE
Apostrophe not removed in Series CleanTitle

### ISSUE THREAD

**Issue by IsThisThingStillOn** [Sonarr/Sonarr#1772]
Sonarr keeps/puts the apostrophe (') in the series title on rename.

My rename pattern: `{Series.CleanTitle}.S{season:00}E{episode:00}.{Quality.Full}-{Release.Group}`

However it does work with `Episode CleanTitle`

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/1646 (and some more information there)
