### ISSUE TITLE
Make tags profile/quality-specific, not show-specific

### ISSUE THREAD

**Issue by RikuXan** [Sonarr/Sonarr#1776]
I'm currently using tags to force Sonarr to get more specific releases for some of my shows (e.g. I'd rather get higher quality releases in the long run, but might watch the episode on another, faster release). Currently, I have to decide between tagging it and not being able to watch it until the higher quality release is out, or not tagging it and manually downloading the higher quality release afterwards.

I would love to be able to connect these tags to specific qualities, so that I can use Sonarr's cutoff functionality in a profile like:
```
WEBDL-1080p (AMZN)<- Cutoff
WEBDL-1080p (any)
WEBDL-720p (any)
```

Is there any way to replicate this behaviour with Sonarr's current feature set and if not, would you think this would be a good addition?

**Comment by markus101** [comment]
No way to do what you're looking for without: https://github.com/Sonarr/Sonarr/issues/385

We do not have plans to link tags back to anything but series as it could lead to a lot of confusion.

**Comment by joewragg** [comment]
I would also love this feature
