### ISSUE TITLE
Colon in series name replaced with a hyphen without space before it

### ISSUE THREAD

**Issue by bpaczkowski** [Sonarr/Sonarr#1777]
For example series "Star Trek: Voyager" is replaced with "Star Trek- Voyager" on the disk. Notice there's no space before the dash. Very minor, yes, but still annoying, to me at least.

**Comment by markus101** [comment]
It's a direct replacement because `:` is an invalid character on many file systems. `Series CleanTitle` might work better for you, but we don't have plans to change the established behaviour or complicate the code to try to handle it differently.

**Comment by desimaniac** [comment]
Is it possible to have a space before the dash (" -") --> "Star Trek - Voyager" ?

**Comment by markus101** [comment]
We'd want to see how that affects other cases which is something we can look into when we look at #1646.

**Comment by desimaniac** [comment]
Awesome!
