### ISSUE TITLE
Add option to mark download as failed when file is not found for import

### ISSUE THREAD

**Issue by colek42** [Sonarr/Sonarr#1778]
Sometimes when a downloaded file is extracted it does not contain the movie file available for import.  User should have option to remove from download client and blacklist release.  

https://github.com/Sonarr/Sonarr/blob/03b83ed22659355028711a8d44030bc56d71c725/src/NzbDrone.Core/Download/CompletedDownloadService.cs#L118

**Comment by markus101** [comment]
That option already exists in Activity: Queue.

Sonarr won't remove it automatically though, it could be an unpacked rar set, or something else, it will require manual intervention.
