### ISSUE TITLE
Update NZBgeek Default URL

### ISSUE THREAD

**Issue by stevenpall** [Sonarr/Sonarr#1779]
Hi there,

I just had a hard time getting NZBgeek set up as an indexer. After some trial and error, I figured out the issue. The API URL should be changed to https://api.nzbgeek.info/api from the current default of https://api.nzbgeek.info. After this change, everything worked smoothly. This is also partially the site's fault because they do not explicitly mention this in their documentation (I found the `/api` part in the Newznab API docs).

Thanks!

**Comment by markus101** [comment]
`/api` is appended automatically when Sonarr makes a request. Unless NZBGeek has it under the `api` subdomain and an additional `api` subfolder. that's in addition to newznab's path, which it doesn't look like it does it should work without the extra `/api` added (and I'd expect the extra `/api` to actually cause issues.).

I've had another user confirm that `https://api.nzbgeek.info` is working without appending `/api`.

Did you setup it as a Newznab indexer or a Torznab one? Newznab is the correct one.

**Comment by blussier01** [comment]
This was driving me crazy, and stevenpall's solution worked - so ignore markus101's response about /api. It does seem like (looking at the sonarr interface) you'd be doubling up on /api in the address if you do what stevenpall suggests, but it doesn't work that way. As soon as I did what stevenpall suggested, the "health" notification about the rss feed not being enabled went away and everything worked as it should.
