### ISSUE TITLE
Set forms password from bash

### ISSUE THREAD

**Issue by EWouters** [Sonarr/Sonarr#1780]
Hi, is it possible to set the forms authentication username and password from a bash script?

Thanks

**Comment by markus101** [comment]
Why would you need to?

Anything automated should use API credentials.

**Comment by EWouters** [comment]
I'm making a bash script to install some software on my server. I want to set the password after setup so I do not expose the interface to the internet after enabling a reverse proxy.

**Comment by markus101** [comment]
Ahh, that makes sense, I was thinking you were trying to access something via a bash script.

Nothing is officially supported in the API for getting/setting settings, but if you look at the requests your browser is making when saving General settings you can see how to set it.

How to authenticate is covered in the API docs: https://github.com/Sonarr/Sonarr/wiki/API

**Comment by markus101** [comment]
If you have any more questions please open a thread on the forums, closing this as there isn't anything for us to resolve.
