### ISSUE TITLE
Deleting Episode Files that do not exist fails

### ISSUE THREAD

**Issue by stuntguy3000** [Sonarr/Sonarr#1782]
Show List: (Directory was manually deleted)
![screenshot_2](https://cloud.githubusercontent.com/assets/1522389/24097748/24eb2fd6-0db7-11e7-8926-be4f268d8c65.png)

HTTP Responses when deleting files:
![screenshot_1](https://cloud.githubusercontent.com/assets/1522389/24097758/2d02cbca-0db7-11e7-959d-659d859a37e9.png)

Whilst this was fixed by performing a disk rescan, this error should be resolved.

**Comment by markus101** [comment]
What do the logs show for this scenario?
What response are you expecting here?

If the series folder is on an unmounted you'd get the same behaviour and it wouldn't make sense to remove Sonarr's record of it. It shouldn't return a 500 response, but whether it's successful or not will depend on whether Sonarr thinks the series folder is likely on an unmounted volume (root folder is missing/empty) or just that series folder is missing and the records should be cleaned up.

**Comment by stuntguy3000** [comment]
"What response are you expecting here?"
What kind of a question is this? The UI says the files are deleted except that's not the case.

"...and it wouldn't make sense to remove Sonarr's record of it."
If the user is attempting to delete the files and the file operation fails because the folder can't be found, then they should **absolutely** be removed from Sonarr.

"If the series folder is on an unmounted you'd get the same behaviour"
If the series folder is unmounted, it should say so and not let operations be performed.

"What do the logs show for this scenario?"
I don't have any, but in this scenario logs are irrelevant.

**Comment by markus101** [comment]
> "What response are you expecting here?"
What kind of a question is this? The UI says the files are deleted except that's not the case.

That's an important distinction vs Sonarr returned and nothing happened. The only information you provided was that there was a 500 response and it shouldn't.

> "...and it wouldn't make sense to remove Sonarr's record of it."
If the user is attempting to delete the files and the file operation fails because the folder can't be found, then they should absolutely be removed from Sonarr.

Again, not if the series is on an unmounted share/volume.

>"What do the logs show for this scenario?"
I don't have any.

Logs would be helpful to see exactly where it failed, though in this case it should be easy to reproduce.

**Comment by stuntguy3000** [comment]
> Again, not if the series is on an unmounted share/volume.

How realistic, common scenario though? _Hint:_ It's not.

> That's an important distinction vs Sonarr returned and nothing happened. The only information you provided was that there was a 500 response and it shouldn't.

![image](https://cloud.githubusercontent.com/assets/1522389/24293966/40c6c69a-10e4-11e7-98eb-9751b089623b.png)

When you modify season files and click Delete Files, **nothing happens**. HTTP Request Inspections show that when the files were deleted locally that it returns a 500 Server Error.

Unfortunately I have no logs to provide as my Sonarr instance is having issues, however logs will not provide more context.
