### ISSUE TITLE
If a torrent completes at the same time a manual import is being processed, the files from the torrent are not processed.

### ISSUE THREAD

**Issue by gtwy** [Sonarr/Sonarr#1783]
Downloaded a torrent of an entire season to fix a season that was missing a few episodes. At the same time, I was running a manual import of a different show. The torrent did not copy the missing episodes into the directory. I presume this was because of the manual import? I can't seem to find a way to trigger it. I would prefer to trigger it properly so that I can benefit from the hard links so I may keep seeding.

Version 2.0.0.4645
Mono Version 4.2.1
AppData directory /home/tor/.config/NzbDrone
Startup directory /opt/NzbDrone
rTorrent: 0.9.6/0.13.6
ruTorrent: v3.7

**Comment by markus101** [comment]
Please use the forums for support.

We'll need to see debug logs to make a proper assessment, without those it's impossible to say concretely what the issue might be, though a manual import should have no effect on the torrent download finishing (though it's possible it delays the import until the manual import completes).

Checking Activity: Queue for the torrent in question should give some information if you hover over the icon on the left if Sonarr hasn't processed it.
