### ISSUE TITLE
Download Station client - Permission Denied with 2-factor authentication

### ISSUE THREAD

**Issue by nswali** [Sonarr/Sonarr#1784]
**Synology: DSM 6.1-15047 Update 1
Sonaar: 2.0.0.4645**

I'm having trouble adding the Download Station download client; I'm getting the following permission denied exception:

NzbDrone.Core.Download.Clients.DownloadClientAuthenticationException: Permission denied
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.AuthenticateClient (NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x000d3] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:127 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Core.Download.Clients.DownloadStation.DiskStationApi api, System.Collections.Generic.Dictionary`2[TKey,TValue] arguments, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings, System.String operation, NzbDrone.Common.Http.HttpMethod method, System.Int32 retries) [0x0003c] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:57 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationProxy.GetTasks (NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00046] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DownloadStationProxy.cs:77 : Permission denied

I have 2-factor authentication switched on, could this be a cause?

I have Transmission and SABnzbd configured and these work, but would like to replace both with Download Station.

**Comment by margaale** [comment]
Hi, there is no current support for that type of authentication yet.

**Comment by nswali** [comment]
OK. Can this be added as an enhancement?

**Comment by margaale** [comment]
How often does the code change? If it changes too frequently is not going to wor, cause sonarr needs always to be connected with the client and you will end up with a lot of authentication errors in the logs...

**Comment by demonbane** [comment]
I'm not sure if this is related to 2FA. I just started getting this same error yesterday (after upgrading to 2.0.0.4668), but my DownloadStation setup has been working fine for about a month prior to that.

**Comment by demonbane** [comment]
It looks like Sonarr might be sending an invalid `session` parameter when trying to do the login. I set up a netcat listener to capture Sonarr's attempted login and then tried using that same call to log in to the DownloadStation:
```
$ curl 'http://<host:port>/webapi/auth.cgi?api=SYNO.API.Auth&version=2&method=login&account=<username>&passwd=<password>&session=563f7f73-7a63-4705-a4b0-4533ad5a6db9&format=sid'
{"error":{"code":402},"success":false}
```

Note the `session=563f7f73-7a63-4705-a4b0-4533ad5a6db9` part.

The Synology API documentation says that `session` should be `DownloadStation`. Trying the same call with just `session` switched out gives me this:
```
$ curl 'http://<host:port>/webapi/auth.cgi?api=SYNO.API.Auth&version=2&method=login&account=<username>&passwd=<password>&session=DownloadStation&format=sid'
{"data":{"sid":"<valid session id>"},"success":true}
```

I'm not sure what changed to cause this to just start happening with the latest update unfortunately. (I know next to nothing about C#, so trying to look through the code isn't getting me anywhere.)

**Comment by margaale** [comment]
Weird, it is working fine here...
@Taloth what do you think?
The 2- factor authentication is not supported, it is unrelated to your
issue.

**Comment by Taloth** [comment]
@demonbane Unless you have 2FA enabled, this is unrelated and could be considered thread hijacking.
Also, please include the DSM version next time.

@margaale Weird yes, the downloadstation spec seems to mention that about the session= param. But I read something about random somewhere else. Also, filestation api has it's own session=FileStation, which doesn't make sense from an client perspective. So does surveillance.
However, if your own Syno cached the auth tokens during tests then that could've caused us to miss it. Maybe restart your syno and sonarr, and check if it still works?

As for 2FA, I don't think it's wise to implement, the sid isn't cached long enough so the user would end up re-authenticating all the time. Unless it can be implemented in a way that's going to work permanently without re-authenticating.
I don't know if you can disable 2FA for specific users and just give Sonarr it's own user & creds with a proper long random password.

**Comment by demonbane** [comment]
Well sh*t. :) I was just about to clarify that I **do** have 2FA enabled, but I just realized that the account that I've been using for the DownloadStation setup doesn't have 2FA enabled (my primary account that I usually use to log into DSM **does** which is why I got confused.)

I'll open a separate issue for my problem then. I apologize for the noise.

**Comment by nswali** [comment]
@Taloth Doesn't look like the DownloadStation API uses 2-factor authentication anyway, as I am able to login, get tasks etc using the API with just a username and password.

**Comment by margaale** [comment]
It's a change that we did last week, radarr is not uptodate because i wanna be sure that it was ok... Gonna revert it later

**Comment by Taloth** [comment]
@nswali Thing is that we access the FileStation api as well. And it looks like 2FA is per user, so question is whether 2FA is enabled for the user you're using.

@margaale I'm ok with reverting it once @nswali confirms 2FA is enabled for that specific user AND works in the FileStation api with the same (DownloadStation) sid.

**Comment by nswali** [comment]
Right, so this is an issue with 2-factor authentication. The reason it was working in the browser for me is that I'd logged into my diskstation and verified the 2FA code and chose to remember it (which would have persisted a cookie with the info). 

Just tried the same API call in a completely different browser and it fails, until I log into the diskstation with the 2FA code, then the call succeeds.

Can't see any API call/params to support 2FA at the moment, so this will have to be parked for now.

For my case, I'll have to create a specific user with 2FA switched off.

**Comment by margaale** [comment]
In the auth api there is an opt_code that is use for the 2fa. But all comes
down to how long does it take for the code to expire...

**Comment by nswali** [comment]
Yeah saw this: https://forum.synology.com/enu/viewtopic.php?t=117664, seems to suggest the opt code isn't exactly easy to obtain.

**Comment by margaale** [comment]
Yes, theres no way that it could automatically be obtained by the api. You should configure it every time it changes...

**Comment by Nemrod7** [comment]
Hi,

Is it working now ?

Thanks
