### ISSUE TITLE
Indexer: Tabula Rasa

### ISSUE THREAD

**Issue by DariusIII** [Sonarr/Sonarr#1787]
Is there a possibility of adding [Tabula Rasa](https://www.tabula-rasa.pw) indexer to list of supported indexers? It is NNTmux based indexer that is compatible with newznab API.

**Comment by markus101** [comment]
You can add any custom newznab indexer you'd like.

But given they state it's a testing site, it doesn't seem like something we should add as a default in Sonarr.

```
This is newznab-tmux testing site
Sometimes it is slow, sometimes buggy, don't be too mad :)
```

**Comment by DariusIII** [comment]
Fair enough.
