### ISSUE TITLE
Request: Custom Calendar view

### ISSUE THREAD

**Issue by RacerBas** [Sonarr/Sonarr#1788]
I have a media server with multiple people on it and they're always asking me when episode X of show X is releasing. They don't want to have the calendar in their google agenda because it also lists all the shows they don't watch.

Would it be possible to create custom calendars with a select set of tv shows?
Like for instance a calendar with only the release dates of The Flash, Supergirl and Arrow.

**Comment by markus101** [comment]
You can do that with the iCal feed and tags already:

![image](https://cloud.githubusercontent.com/assets/413544/24249855/fffdbf36-0f91-11e7-916c-05b955b109cb.png)

If you tagged those shows with the tag `dc` you'd set the same tag there and the iCal output would only contain series tagged with `dc` (if a series with that tag was removed it'd disappear and new ones added would show up automatically).
