### ISSUE TITLE
Using a URL Base under "General Settings" breaks the link to the main logo.

### ISSUE THREAD

**Issue by akseanor** [Sonarr/Sonarr#1791]
The image is pointing to server:8989/tv/Content/Images/logos/128.png, but that just returns a JSON message with the content `{ "message": "NotFound" }`. The issue is not present when no URL Base is set.

**Comment by markus101** [comment]
Your URL Base is set to `/tv`?
Did you restart Sonarr after setting it up?
Did you Reload the page after?
Have you cleared the cache? A cached copy of the index page may be pointing to the wrong location because the file hasn't changed, but the URL it needs to use has.

**Comment by akseanor** [comment]
Closing as PEBKAC. Rebooting server resolved issue. Thanks @markus101.
