### ISSUE TITLE
logs > table view does not load in firefox 52+

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#1792]
sonarr ver: 2.0.0.4671
works fine in chrome however.
cleared cache, restarted sonarr, restarted browser, tried switching from form auth to popup (restarting sonarr) nothing works. page just fails to load.. xhr in firebug shows its failing.. only this xhr fails.. all other sonarr xhr work fine...  moul confirmed he sees the same problem in firefox 53.0b5

**Comment by Taloth** [comment]
According to M0UL was caused by adblock.

**Comment by M0UL** [comment]
it is caused by the easy privacy filterlist.

**Comment by Taloth** [comment]
Specifically, the EasyPrivacy list that blocks `/api/log?` and global pattern...

**Comment by thezoggy** [comment]
added whitelist filter: `localhost` all good now
