### ISSUE TITLE
Scheduling Issues

### ISSUE THREAD

**Issue by LindsayCole** [Sonarr/Sonarr#1795]
Hi All, 

 I have at least a couple shows that TVDB shows new episodes for, yet Sonarr is not seeing the release schedule (Examples: Grey's Anatomy, and Designated Survivor).

 How do I force Sonarr to see the proper schedule from TVDB?

Thanks,

**Comment by markus101** [comment]
Please use the forums for support.

You can refresh them in Sonarr and make sure the refresh is succeeding by checking the logs.

**Comment by LindsayCole** [comment]
Sorry, I found the problem anyway. It was stuck and hadn't ran the Refresh Series tab in over a month. Was hung on a corrupt show.

Sorry for going to the wrong spot!
