### ISSUE TITLE
Add ability to group Pushbullet notifications

### ISSUE THREAD

**Issue by Leapo** [Sonarr/Sonarr#1796]
Currently, every notification generated by Sonarr is sent-out as an individual push notification. This can generate a lot of notifications when adding a new series, potentially maxing-out a free Pushbullet account on its monthly allotment of notifications within a short period of time.

I suggest adding the option of grouping notifications by queuing them for N-minutes, merging them, and then sending as a single notification.

**Comment by Taloth** [comment]
Dupe: https://github.com/Sonarr/Sonarr/issues/1396

But yes, that's something we want to do, individual notifications is pretty much pointless anyway, imho.
