### ISSUE TITLE
Season Pass

### ISSUE THREAD

**Issue by attritionorg** [Sonarr/Sonarr#1797]
Under Series, clicking on a series gives the list of episodes where we can 'Toggle monitored status'. Having a way to mass toggle status on a per-season basis would be very handy.

**Comment by markus101** [comment]
Sounds like you're looking for for Season Pass, which is already part of Sonarr.

**Comment by attritionorg** [comment]
New to Sonarr, so not familiar with Season Pass or that reference.

**Comment by attritionorg** [comment]
And poking around further, the feature is in. Just missed it that the big status icon next to season can be toggled. Sorry!
