### ISSUE TITLE
Notifications on health check warnings/errors

### ISSUE THREAD

**Issue by evilvibes** [Sonarr/Sonarr#1798]
This feature would add notification about like proxy, download client and Indexers errors to connection notifications.

![healthcheck](https://cloud.githubusercontent.com/assets/17504733/24331503/f0aeadf2-11f2-11e7-98fa-7f4409741c4a.png)

**Comment by Kyrluckechuck** [comment]
Is this just waiting on development or also on approval / long-awaited-feature-before-implementation?

**Comment by popetackler** [comment]
This is a long overdue feature.

**Comment by Arindrew** [comment]
Agreed. My indexers crash daily (due to [sonarr bug](https://github.com/Sonarr/Sonarr/issues/2802) and it would be nice to know when that happens so I can restart sonarr to get them back up.

**Comment by DrSeussFreak** [comment]
https://github.com/Sonarr/Sonarr/issues/3514 - this is STILL happening

**Comment by markus101** [comment]
This issue should have been closed when the feature was implemented. Your issue is related to the feature, not the request.
