### ISSUE TITLE
Feature Request: configurable limit of API requests/day/indexer

### ISSUE THREAD

**Issue by frollic** [Sonarr/Sonarr#1802]
Hi,

and thnx for a great program!

Wonder if it would be possible to implement a max number of API hits per indexer ?
On some sites, you're only allowed to have a limited amount of requests per day.
Would be great if Sonarr would stop making request to those sites once the daily 
limit was reached. This would take the load off the indexers, but also generate less 
"Indexers unavailable" errors within sonarr.

thank you in advance.

**Comment by markus101** [comment]
If the indexer reports that the API limit has been reached Sonarr will respect that and not retry until it resets (based on when the indexer reports that it will reset), if it doesn't Sonarr will still back off based on the number of failures and retry periodically.

We do not have plans for specifying the limit and tracking that on each request.
