### ISSUE TITLE
Episode status in exported iCal link

### ISSUE THREAD

**Issue by io-node** [Sonarr/Sonarr#1804]
When using the iCal feature it doesn't show the status of the episode (Unaired Premiere / Unaired / On Air / Downloading / Missing / Downloaded / Unmonitored) which could be helpful if you don't want to keep checking Sonarr directly.

Would this be an option to add? Maybe even in the subject by a prefix (DL = Downloading / DF = Download Finished, etc)

**Comment by markus101** [comment]
Sonarr uses the status field and if the is a file it's accepted, otherwise it's tentative.

I don't see adding that to the title making sense (maybe the summary along with more information), but unless it syncs often it seems like something that would be mostly unused.

**Comment by markus101** [comment]
Closing as we don't plan to customize the calendar titles with this information.
