### ISSUE TITLE
Vuze Import of single file torrent fails on 5.7.5.0

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#1805]
Vuze version 5.7.5.0

Single torrent download with file `E:\Downloaded\Completed\Release Name.mp4`
Vuze reported `E:\Downloaded\Completed` as output, although in previous versions it supposedly included the torrent Name.

This caused Sonarr to import the entire completed folder and files into single series.

**Comment by Nukem51** [comment]
idk if this got implemented in april 6th update but it seems like the problem has gotten worse. every 3 hours the system forgets whats in the download folder and just keeps replacing random files.
