### ISSUE TITLE
[Feature] Send notification if new episode downloads when previous missing

### ISSUE THREAD

**Issue by Kryptonit3** [Sonarr/Sonarr#1806]
It is not a constant problem, maybe happens once or twice a month. Say sonarr was unable to download last weeks episode of a show for some reason, but it has no problem downloading this weeks episode. It would be nice to get an alarm for people who have setup notifications or at that moment have sonarr attempt another scan/search. I usually lets shows get 4 or 5 unwatched episodes and then binge watch so if it misses an episode it sucks. Currently I just randomly a few times a month check the calendar and see an episode was missing and then manually force a scan.

**Comment by markus101** [comment]
I see this being a very complicated feature to do correctly, there are a lot of variables at play here that could lead to false notifications. If there was an issue that prevented Sonarr from grabbing it, I'd much rather work to resolve any issues there than to try and notify that an episode was missed. I see this as something we want to commit to implementing at this time, but I'll label it so we can revisit it later.
