### ISSUE TITLE
Episode detection fails when episode name starts with a number [0-9]+

### ISSUE THREAD

**Issue by Grimeton** [Sonarr/Sonarr#1807]
Hi,

when an episode's name starts with a number then the detection fails and Sonarr assumes that the number is the last episode's number that's part of the file.

If the file is named like this: "Some Series - S01E03 - 33.mp4" then Sonarr thinks the file contains episodes 3 to 33 and marks all episodes as available which isn't the case. Happened multiple times now and I had to fix it manually. 

If the file gets renamed to "Some Series - S01E03.mp4" everything is fine. 

I understand that the dash "-" is used to tell Sonarr that there are multiple episodes in the file, e.g. like "Some Serie - S01E01-02 - Some Title.mp4" But then the dash isn't surrounded by spaces and the episode number is followed by another dash and a title. 

So I wonder if this is a bug or just a more complicated matter of detection?

KR,

G.

**Comment by markus101** [comment]
That's definitely complicated to check with no easy way to resolve it, but added it as a case when we improve the parser: https://github.com/Sonarr/Sonarr/issues/457
