### ISSUE TITLE
Unable to parse episodes from release name

### ISSUE THREAD

**Issue by Grimeton** [Sonarr/Sonarr#1808]
Hi,

I get the following message for multiple daily shows like the one in the screenshot:

![sonarr](https://cloud.githubusercontent.com/assets/2773919/24445602/c03f87e8-146a-11e7-8b7e-f870e45aa4e4.png)

Which results in Sonarr not downloading the shows.

To me it's quite obvious which show and episode this is, but it doesn't look like Sonarr gets it.

Happens with multiple shows including all the late night shows or BBC's Panorama.

The thing is, I can't even trigger the download manually, as Sonarr is not offering anything. That could be a temporary fix until this is fixed completely.

Cu

**Comment by markus101** [comment]
Please use the forums for support. It looks like you have the series type set to `Standard`, but it should be `Daily`.

**Comment by Grimeton** [comment]
Thanks, will check but looks like it was my fault.

**Comment by Grimeton** [comment]
So it turns out with some series it was my fault but BBC's panorama is coming up weekly but listed as daily. Switched to daily.

Thanks anyway
