### ISSUE TITLE
	Unable to communicate with nzbget. Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.

### ISSUE THREAD

**Issue by jestes** [Sonarr/Sonarr#1810]
I keep having the following error 

	Unable to communicate with nzbget. Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.

Everything works ok though 

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
Please use the forums for support, we'll need the information requested when opening a new thread there to troubleshoot.
