### ISSUE TITLE
Congrats on a well-made piece of software

### ISSUE THREAD

**Issue by jcollum** [Sonarr/Sonarr#1811]
I'm consistently impressed with this tool and thought the team would appreciate a note about that. Especially the in-place updates and the overall UI. Damn fine work. 

Close this issue whenever you want.

**Comment by addisonbabcock** [comment]
I had Rick and Morty downloaded before I even knew it was airing. That's amazing.

**Comment by markus101** [comment]
Thanks! Always great to hear from satisfied users!
