### ISSUE TITLE
Completed Season Search

### ISSUE THREAD

**Issue by Shiroihige** [Sonarr/Sonarr#1812]
When adding a new series with already completed seasons or doing an automatic search for a completed season in a series, sonarr makes an api call for each individual episode in the series before looking and deciding on the season pack to download.  

For shows with large seasons this not only takes forever to find the release it wants but it also seems to make a shit ton of api calls.

It usually ends up deciding on the season pack, but sometimes will start a download for a pilot episode then keep searching and get the season pack as well.

It seems that it would make more sense to search for a season pack first then look for individual episodes if one isn't found for the reasons above.

**Comment by markus101** [comment]
Sonarr does a season search when performing a search for an entire season regardless of whether the season is competed or not and all results are processed which will likely include individual results. Daily and anime series would require searching for individual episodes.

> It usually ends up deciding on the season pack, but sometimes will start a download for a pilot episode then keep searching and get the season pack as well.

Sonarr won't grab an individual episode then a season pack unless it was a second search after the fact and the individual episode wasn't in the queue any more (and not imported).

If you have a specific scenario with logs, please open a thread on the forums and we can investigate further.

**Comment by Shiroihige** [comment]
Thank you for the clarification.  I didn't realize anime required searching individually which is probably where I saw my issue.  It was when adding an anime and it grabbed the pilot episode and a season pack for it.

It would be nice if episode searching for anime wasn't a mandatory option.  For shows like One Piece or something else long running, thats like 900+ searches when most of the time they have season packs just like regular shows.
