### ISSUE TITLE
Support for Qnap Download Station

### ISSUE THREAD

**Issue by jasonyates** [Sonarr/Sonarr#1815]
Is it possible to have support for the QNAP Download Station client as a Download Client?

**Comment by markus101** [comment]
API documentation would be a huge help for anyone wanting to pick that up.

It looks like a ruby gem exists that unofficially documents  things: https://github.com/cyclotron3k/qnap-download_station

**Comment by dietbattleship** [comment]
qnap has some recently updated docs for the 4.3 version. http://download.qnap.com/dev/download-station-addon-developers-guide_v4.pdf if you need someone to test I'm willing.

**Comment by dietbattleship** [comment]
As an alternative, would it be possible for sonarr to expose an rss feed of files to be downloaded by the client?  many clients including qnap's download station support RSS feeds as inputs.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR

it doesn't appear QNAP has significant API documentation
