### ISSUE TITLE
Series history suggestion

### ISSUE THREAD

**Issue by jobrien2001** [Sonarr/Sonarr#1817]
Hello, 
I think of 2 great enhancements for sonarr.

1. I think it would be useful to have a history of the entire file activity within a series, similar to the history tab when selecting a particular episode.  Right now the only was to look at history is by looking at the activity and scrolling (through numerous files if you have a busy server).
2. Also, a search box would be great on activity>>history and activity>>blacklist.

**Comment by markus101** [comment]
History for a series already has a GHI: https://github.com/Sonarr/Sonarr/issues/273

No current plans for searching on those pages.
