### ISSUE TITLE
Audio Channels option in Episode Naming

### ISSUE THREAD

**Issue by Eisa-AlAwadhi** [Sonarr/Sonarr#1818]
Feature Request:-
When Sonarr renames, it's important to have the option of adding audio channels to the name. Especially when you have an audio system in your HTPC. I wish you can include it as an option.

Navigation Example:-
[Settings] > [Media Management] > [Episode Naming] > [Standard Episode Format] > [+] > [Audio Channels]

Standard Episode Format:-
{Series Title} S{season:00}E{episode:00} [{Quality_Full}] [{Audio Channels Full}]

Also, it will be great to have the option of choosing between:
[Audio Channels Simple] eg: (5.1) 
or [Audio Channels Full] eg: (DTS-HD 5.1)

Thanks (^ ^)

**Comment by markus101** [comment]
These options are already available:

`{MediaInfo AudioChannels}`
`{MediaInfo AudioCodec}`

**Comment by Eisa-AlAwadhi** [comment]
@markus101 
Thank you Markus for the response! I didn't know about that.
I thought all possible options were displayed when Advanced Settings are enabled.
Next time I'll make sure to check the wiki beforehand, I've checked after your response and it is clearly documented. https://github.com/Radarr/Radarr/wiki/Sorting-and-Renaming#rename-options

Thanks again (^ ^)
