### ISSUE TITLE
Feature Request: Remote Path Mapping Copy Progress Status

### ISSUE THREAD

**Issue by beefycheddar** [Sonarr/Sonarr#1821]
I use a remotely accessed nzb downloader and I use the remote path mapping feature. It works great. My local server has a slower (sub 10mbps) connection to the downloader, so when a file starts to copy over, my whole network connection can be saturated with no indication of how long this may last. I think it would be improved by adding a progress indicator (bar, pie chart, ##%) next to the file being copied in the show page or in the Activity page. 

What do you think?

**Comment by markus101** [comment]
It's not possible to add support a progress indicator as that is not something the framework supports and building our own copy mechanism to support that isn't something we plan to do. It may be possible to indicate it's being copied though.

**Comment by Taloth** [comment]
It's actually covered by the Transfer Provider concept we had to deal with rsync, btsync and other remote transfers. But that's just an idea we have in our minds, nothing concrete.

https://github.com/Sonarr/Sonarr/issues/282

**Comment by markus101** [comment]
Closing as this is already covered.
