### ISSUE TITLE
Feature Request: Remote copy temporary file extensions

### ISSUE THREAD

**Issue by beefycheddar** [Sonarr/Sonarr#1822]
It would be helpful if Sonarr could set the extension of a file incoming from a Remote Path Mapping file copy could have and extension added to the end of the file name, like this: show.mkv.temp. This extension should be removed once the copy is complete so Plex/whatever can pick up the new media file.

I copy over a sub 10mbps connection from the nzb downloader server. The copy works fine, but during the copy, Plex picks up the show as if it were ready to watch, but it's not ready yet. My connection speed fluctuates and a file copy can take an hour or more. This unwatchable show causes confusion and does not pass the wife test. 

What do you think?

**Comment by Grimeton** [comment]
Hi,

Plex picks up the .temp file too. It uses inotify or a similar technique depending on the os, to detect changes and then scans the folder again. To detect if the file is actually to be considered it does it's own magic (e.g. like mediainfo) on the file. And as soon as the file looks like a video or audio file, it's considered and added.

That acutally happens pretty soon after you start copying as the metadata is part of the beginning of the file.

Only option would be to copy the file over and sort it in afterwards by moving the file to it's final destination.

Also. When using Sonarr's Pickup folder to add new episodes it adds that temp tag to the file by creating another file ending in a "~". At least on Linux it does that.

Cu

**Comment by markus101** [comment]
AS pointed out, Plex ignores the extension and processes the file to determine if it's suitable so a temporary extension won't work. Copying to another location and moving it may work, but would require somewhere to stage the files for that and not something we have plans to do at this time.
