### ISSUE TITLE
Feature request: custom BackSearch option

### ISSUE THREAD

**Issue by Jorman** [Sonarr/Sonarr#1824]
Hi, if I understand well sonar search for old episode only on 2 situation, when a new series was added and when sonar is offline for a while.

But I don't know if there's a kind of option to set to search periodically old episode.

Because this kind of thinking is ok for series with the same language of the "owner of the system", so english/english etc etc.

But when I search for non local language series, a lot of times, maybe 99%, there's some time difference, I mean the original air-date is maybe 8 or 9 months ago. For example falling skies, the 3rd season was delayed 3 years here! LOL
So if I add this serie on my library sonar will search the episode (please note that I created a custom profile to search only my local language) sonar will search the missing episode but maybe the episode for my local language will be available in a week or months or others.

So, there's any way to automate the search in this case? Maybe a new option to set directly on the profile?

J

**Comment by Taloth** [comment]
> Hi, if I understand well sonar search for old episode only on 2 situation, when a new series was added and when sonar is offline for a while.

And there's the misunderstanding. What you're saying is true in the literal sense, but you're interpreting 'search' differently. It's also not about 'old episodes' but rather 'old uploads', that distinction is crucial.

The subject is covered in the FAQ:

https://github.com/Sonarr/Sonarr/wiki/FAQ#how-does-sonarr-find-episodes

https://github.com/Sonarr/Sonarr/wiki/FAQ#why-doesnt-sonarr-automatically-search-for-missing-episodes

**Comment by Jorman** [comment]
Ok, got it! Tnx I miss this :D
