### ISSUE TITLE
[Feature Request] Notify that files in the NZBDrone folder need attention/manual import.

### ISSUE THREAD

**Issue by Grimeton** [Sonarr/Sonarr#1827]
Hi,

I use Sonarr's NZBDrone folder to import new episodes as they have to go through a reencoding process first. Sometimes it happens that Sonarr is not able to deal with the file it gets there but it doesn't show a warning or anything.

I can only make this visible by doing a manual import on the drone folder. Would be nice to get a warning/notification in the lower right if there's a file that cannot be handled and needs manual attention.

KR,

G.

**Comment by markus101** [comment]
Drone Factory isn't something we recommend using and will be removed in v3 (everything that it does can be done via the API or Manual Import), we don't have plans to add any notification functionality there.
