### ISSUE TITLE
Some series can only be found via tvdb:$id and not name.

### ISSUE THREAD

**Issue by Grimeton** [Sonarr/Sonarr#1828]
Hi,

when adding new shows, some of them can only be found via the TVDB-ID and not the name. It's weird but it's like that. "Taboo" is one of those shows:

By name:

![grafik](https://cloud.githubusercontent.com/assets/2773919/24829774/76a88f88-1c78-11e7-9ffd-96a8f89f9387.png)

By ID:
![grafik](https://cloud.githubusercontent.com/assets/2773919/24829780/90e4af08-1c78-11e7-853e-a31527211802.png)

Cu

**Comment by markus101** [comment]
This is due to TheTVDB's API search, at this time there is nothing for us to do, consuming their v2 API may help there, but with Skyhook v2 we should be able to improve this as well.
