### ISSUE TITLE
Support imdb:imdbid searches when adding a series

### ISSUE THREAD

**Issue by Grimeton** [Sonarr/Sonarr#1829]
Hi,

would it be possible to use TheTVDB.com API so that one can search via the IMDB-ID?

They offer a simple interface at: 

http://thetvdb.com/api/GetSeriesByRemoteID.php?imdbid=tt3647998

that is kinda self explaining. 

It then returns TheTVDB-ID which could be used in the further lookup.

KR,

G.

**Comment by markus101** [comment]
This is something we can look at when we start using TheTVDB API v2.

**Comment by mooop12** [comment]
What about adding IMDB as a separate service?

**Comment by marksie1988** [comment]
Any idea on timelines for this? It's been open since 2017 just wondering if it would be anytime soon?

Also would love to see this implemented similar / same as Radarr. I thought the two projects worked together with the products being nearly identical.

**Comment by Grimeton** [comment]
Blocked, Closed, Closed and Closed.

Don't see this happen anytime soon...

**Comment by marksie1988** [comment]
@Grimeton the closed ones are duplicates of this so that makes sense to keep it tidy. 

I guess more asking when it's likely that skyhook will be sorted.

**Comment by klejejs** [comment]
Been using Sonarr for more than a year now and lately I have started noticing that TVDB doesn't work perfectly, some series cannot be found, other special episodes are grouped weirdly. It would be awesome to be able to choose between IMDB and TVDB when adding series.

**Comment by Thirrian** [comment]
That's a completely different question. This item is about being able to use the IMDb id to search thetvdb.com for series to add.

**Comment by klejejs** [comment]
Sorry, my bad, I did not understand the issue. I will create another ticket and maybe it can be considered separately.

**Comment by markus101** [comment]
IMDB as a metadata source will not be supported, no need for another issue.

**Comment by ekk88d** [comment]
There is now a reliable Chrome extension that adds a Sonarr icon to IMDB TV series' pages. However, searching can get messy because it can only search Sonarr by title. The extension's author has stated that he'd try to implement searching by IMDB ID from IMDB.com, but Sonarr doesn't yet support it.

IMDB.com gets hundreds of times more traffic than TheTVDB. While the TheTVDB remains as the source of metadata, searching Sonarr by IMDB ID is an excellent Sonarr enhancement.

If Radarr originally stemmed from Sonarr's Servarr architecture, can adding IMDB ID search functionality to Sonarr be eased by adapting some of Radarr's code?

**Comment by bakerboy448** [comment]
> If Radarr originally stemmed from Sonarr's Servarr architecture, can adding IMDB ID search functionality to Sonarr be eased by adapting some of Radarr's code?

Not at all.

Sonarr has nothing to do with the Servarr backend.  and Servarr's various components have nothing to do with skyhook.

Implementing something like this would require Markus/Taloth modify skyhook to support the functionality of searching by imdbid which may or may not be feasible

As previously stated - no plans to use IMDB data or it's API.

**Comment by ekk88d** [comment]
> > If Radarr originally stemmed from Sonarr's Servarr architecture, can adding IMDB ID search functionality to Sonarr be eased by adapting some of Radarr's code?
> 
> Not at all.
> 
> Sonarr has nothing to do with the Servarr backend. and Servarr's various components have nothing to do with skyhook.
> 
> Implementing something like this would require Markus/Taloth modify skyhook to support the functionality of searching by imdbid which may or may not be feasible
> 
> As previously stated - no plans to use IMDB data or it's API.

Thanks for the info. It was helpful.
Are there any plans for enabling Sonarr to search/add by IMDB ID?

**Comment by markus101** [comment]
This is now supported via Skyhook. Searching for `imdb:tt0496424` will list `30 Rock` as the top result.
