### ISSUE TITLE
[Feature Request] Different categories instead of priorities in download client settings

### ISSUE THREAD

**Issue by Grimeton** [Sonarr/Sonarr#1830]
Hi,

would it be possible to use different categories for recent/older episodes from a show instead of the priority? SabNZBd doesn't hand the priority information to the post processing script and it is gone the moment the job moves to the history queue. So I'm not able to distinquish between a recent episode (higher priority in encoding) and an older episode (lower prio in encoding queue) anymore :-/.

![grafik](https://cloud.githubusercontent.com/assets/2773919/24829840/be701452-1c79-11e7-97c2-6abe5f3bb517.png)

Having different categories like "tvrecent" and "tvold" would solve that problem.

KR,

G.

**Comment by markus101** [comment]
This sounds like something that should be added to SAB, we don't have plans to support different categories instead of/in addition to different priority levels.
