### ISSUE TITLE
Move files instead of copying?

### ISSUE THREAD

**Issue by puzl** [Sonarr/Sonarr#1833]
I would like the option of moving completed torrents rather than copying them.

I use cloud storage, with limited api accesses.

When I complete my torrent I use a deluge script to sync the files into a 'completed' folder on the cloud storage.

I would then like Sonarr to simply move and rename these files rather than copying them.

Copy + Rename + Delete uses twice the cloud storage API accesses so I would like to avoid that if possible.

**Comment by markus101** [comment]
Why have Deluge move them when Sonarr could move them?
By having Deluge do the sync then Sonarr moving them aren't you using the API accesses you want to limit?

We don't have plans to have an option to copy them, though this may fall under the concept of Transfer Providers: https://github.com/Sonarr/Sonarr/issues/282

**Comment by puzl** [comment]
I use rclone to manage the cloud storage.  
The data is mounted locally so that sonarr, sickbeard, plex etc can access the content.
However, it is much more reliable and efficient to use 'rclone copy' to push the data to the cloud storage.
Once the data is copied into a transient folder I then 'rclone move' it into the blackhole watch folder, which is more or less instant.

Sickbeard would then move the files from the blackhole into the season folder.
Sonarr copies the content and then deletes the original.

I have great stability issues having sonarr copy the contents directly from the deluge completed area.

So yes, transfer providers sound like they would be fantastic, if, for example I could have sonarr detect the completed download in deluge, then invoke the transfer provider to copy the contents into its final destination using an rclone transfer provider.
