### ISSUE TITLE
rtorrent: Unknown exception: Method not allowed

### ISSUE THREAD

**Issue by kragebein** [Sonarr/Sonarr#1834]
While trying to set up sonarr to work with rTorrent, I get this error: 

`CookComputing.XmlRpc.XmlRpcServerException: Method Not Allowed at CookComputing.XmlRpc.XmlRpcClientProtocol.ReadResponse (CookComputing.XmlRpc.XmlRpcRequest req, System.Net.WebResponse webResp, System.IO.Stream respStm, System.Type returnType) <0x40fe9050 + 0x00287> in <filename unknown>:0 at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke (System.Object clientObj, System.Reflection.MethodInfo mi, System.Object[] parameters) <0x40fcc090 + 0x007d7> in <filename unknown>:0 at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke (System.Reflection.MethodInfo mi, System.Object[] Parameters) <0x40fcc050 + 0x00027> in <filename unknown>:0 at XmlRpcProxy403ffdac-9019-4ef6-8f88-eb70c34f219c.GetVersion () <0x40fcbed0 + 0x0007b> in <filename unknown>:0 at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.GetVersion (NzbDrone.Core.Download.Clients.RTorrent.RTorrentSettings settings) [0x00017] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:58 at NzbDrone.Core.Download.Clients.RTorrent.RTorrent.TestConnection () [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrent.cs:183 : Method Not Allowed`

 rTorrent-PS 0.9.6/0.13.6

**Comment by markus101** [comment]
Please open a thread on the forums for support, but it looks like the request is being rejected by the rtorrent side, perhaps because the Url Path is being used, the help text on there offers some suggestions.
