### ISSUE TITLE
Anime dated on calendar by DUB release?

### ISSUE THREAD

**Issue by dephunk** [Sonarr/Sonarr#1835]
I watch both subbed & dubbed anime and have recently been watching Dragon Ball Super. I personally can't stand the JAP voice of Goku so I've been watching the dub, but the dub is like 4 seasons behind the sub. Is there a way to force DBS to follow the dub release calendar? In the calendar it is showing the subbed version releasing a new ep on Sunday - S05E10 where the dub will be releasing S01E14.
Thanks, this is my first post on github.

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
No that is not possible as TheTVDB does not have that information, that _may_ be possible in the future when their new site goes live depending on how it works on the API-side and if it's something we can support.
