### ISSUE TITLE
Sonarr not recognizing specific show

### ISSUE THREAD

**Issue by english06** [Sonarr/Sonarr#1836]
This follows the naming conventions that work elsewhere throughout my TV Shows folder. I don't know if it is the word "Dimension" (popular torrent uploader) or the "404" before the season/episode number. But these files can not be read when either doing a Disk Scan or Manual Import. Screenshot attached:

http://imgur.com/LgCLcNf

Error reason given is: "Unknown Series"

**Comment by markus101** [comment]
It's the 3 digit number before the season + episode number and the square brackets around the quality. Removing the square brackets around the quality should resolve it, we have plans to look into parsing things in a smarter way, but it requires significant work to how things are parsed, but is covered by: https://github.com/Sonarr/Sonarr/issues/457
