### ISSUE TITLE
Sonarr grabbing multiple versions of same epsiode (qbittorrent) on 4689 update

### ISSUE THREAD

**Issue by sch1308** [Sonarr/Sonarr#1837]
I have attached screenshots as well. https://www.reddit.com/r/sonarr/comments/64ox34/sonarr_grabbing_multiple_versions_of_same_episode/

**Comment by markus101** [comment]
Please use the forums for support. We'll need to know which version of Qbittorrent you're using in addition to the information requested when opening the thread, though it looks like API requests are being rejected by qBittorrent, but nothing has changed on Sonarr's side for qBittorent and that request recently.
