### ISSUE TITLE
Quality name separator always set as dash

### ISSUE THREAD

**Issue by Ninjouz** [Sonarr/Sonarr#1838]
Hey guys !

I was trying to setup custom names for my files with dot separator to match release name (much better for guessit / subliminal).

Problem is that when I use {Quality.Full} or {Quality.Title}, the quality (HDTV-1080p or WEBL-1080p etc ...) is always separated with the dash.

Thus, I get names like Show Title (2017).S01E01.Episode Name.HDTV-1080p.x264.DTS-DIMENSION
The best would be to have the dash to be tied to the group name only.

Is it normal behavior ?

**Comment by markus101** [comment]
You need to update the `Quality Definitions` in settings to use a space in the Title instead of the dash as it replaces spaces with your separator of choice.

**Comment by Taloth** [comment]
This is what I use: 
![image](https://cloud.githubusercontent.com/assets/6383890/24915717/37498812-1ed8-11e7-90c7-3b2904dc2158.png)
