### ISSUE TITLE
Sonarr not removing failed download from sabnzbd history list

### ISSUE THREAD

**Issue by Ninjouz** [Sonarr/Sonarr#1842]
Hey guys,

I've got an issue with the cleaning of sabnzbd history list.

I have this setup : 
Completed Download Handling  : Enable YES  - Remove NO
Failed Download Handling : Redownload YES - Remove YES

So I'd like to remove all failed job from sabnzbd history list but keep the downloaded list.
But it's not working, the failed download are not being removed. In the debug log I cant see any call done toward sabnzbd for deletion.

If I set Completed Download Handling  : Remove YES  then it works obviously but remove even the completed downloads. In the debug log : 

```
17-4-13 00:47:02.8|Debug|DownloadEventHub|[Release.Name.blabla] Removing download from Sabnzbd history
17-4-13 00:47:02.8|Debug|SabnzbdProxy|Url: http://localhost:8085/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
17-4-13 00:47:04.4|Debug|SabnzbdProxy|Url: http://localhost:8085/api?mode=history&name=delete&del_files=1&value=SABnzbd_nzo_UWNWdZ&apikey=(removed)&output=json
```

Something is not right in the DownloadEventHub.

Sonarr version : stable 2.0.0.4689
Sabnzbd version : stable 1.2.1

**Comment by markus101** [comment]
This was a bug introduced with some recent changes, thanks for the report.

Fixed in https://github.com/Sonarr/Sonarr/commit/f36d5dc88189b18855586b4480dfcf317cf1816a
