### ISSUE TITLE
RSS instead of API

### ISSUE THREAD

**Issue by lincalinca** [Sonarr/Sonarr#1843]
I know this might be a bit pie in the sky, but it would be great to be able to add a list of websites from which to source, not just via API, but also via RSS. Some APIs are a bit wonky, and most RSSs are pretty reliable. I'd like, for instance, to just add eztv.ag as an RSS and go from there.

Could that be implemented as an alternative?

**Comment by jobrien2001** [comment]
There is an active project called jacket where you can add a multiple public rss and or search capabilities to sonarr (including the one you mention), but i would agree it would be nice.

**Comment by markus101** [comment]
You can use TorrentRSS for that assuming it's publishing a supported format.
