### ISSUE TITLE
Series link to ZAPit.com

### ISSUE THREAD

**Issue by jobrien2001** [Sonarr/Sonarr#1844]
When looking at a series there are several links available to imdb, trackt, tv maze, etc.

Zapit is a source for scheduled broadcasts.

The TVDB returns a ZAPit ID (if available) on the API XML.  Can we have add a link to zapid.com if an ID is available for the series?

ZAPit is useful as sometimes the TVDB is missing episodes, and this would make it easier to contribute to the TVDB, which in turn helps Sonarr.

Here is an example of a retrieved TVDB XML tag and its URL link:
<zap2it_id>EP01360756</zap2it_id>
http://tvlistings.zap2it.com/tv/nightmare-next-door/EP01360756?aid=zap2it

**Comment by markus101** [comment]
Is there a format to it? It looks like the title slug is just ignored and it relies on the ID following the title slug only.

AFAIK we'll need to update skyhook (our TVDB Proxy) to capture this information and pass it along as well as update Sonarr to store it and finally put it in the UI. Things are getting crowed in the UI already, so I'll tag this for v3 and determine how we want to do it then.

**Comment by jobrien2001** [comment]
Seems like you are correct.

These yield the same result.

http://tvlistings.zap2it.com/tv/aaightmaffddnedsxtoor/EP01360756?aid=zap2it
http://tvlistings.zap2it.com/tv/nightmare-next-door/EP01360756?aid=zap2it

**Comment by thezoggy** [comment]
note that tvdb includes zap2it as part of their series info (has been there for ever now.. just cant see it until you edit the series, just like imdb/tv.com/etc) from their site:

*Zap2it / SchedulesDirect ID:* This field MUST correspond to the Zap2It ID, include the leading "EP" followed by eight digits.

example: `EP02104223`

**Comment by jobrien2001** [comment]
The url has changed for zap2it.

Now its

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
