### ISSUE TITLE
Add option to control whether an indexer can be used for episodes/seasons/both

### ISSUE THREAD

**Issue by Qdhcjv** [Sonarr/Sonarr#1847]
Some trackers I use are harsher on ratio/harder to seed on. When content is newly released (an individual new episode) it's fine to grab because it's small and seeds easily. A full season is large (harsh on my download usage) and difficult to seed because it's not fresh, high-demand content. I would like the ability to choose whether or not an indexer can grab episodes only, seasons only, or both (default). Anyone else?

**Comment by markus101** [comment]
I think this is covered by a couple existing issues.

Influencing season pack grabbing (a bit vague): https://github.com/Sonarr/Sonarr/issues/825
Ability to allow manual/automatic searching on individual indexers: https://github.com/Sonarr/Sonarr/issues/253
