### ISSUE TITLE
[API] Add ability to scan a folder

### ISSUE THREAD

**Issue by peatnik** [Sonarr/Sonarr#1848]
Please add an API endpoint where I can submit a path to a newly added Show/Season/Episode. Sonarr should then scan that path and either update the already existing show with the same (base) path or add it as a new show.
If the base path doesn't exist already and it has to be added as a new show, the response should contain info about that action (success/failure, chosen match, other possible matches).

This would help everyone who disabled sonarr post-processing and make it easier to use external tools like filebot. In my opinion, renaming is not a core competency of sonarr and it should be possible to externalize that functionality more easily.

**Comment by TylerBre** [comment]
I agree very much with this.

At the very least, allow users to create a custom pattern for episode naming. I believe even if you have renaming turned off, sonarr will use the episode naming template it uses for the renaming to scan for TV shows.

If there is already a way to do this, please let me know.

**Comment by markus101** [comment]
This isn't something we're planning to implement, but this can be achieved by getting all series (https://github.com/Sonarr/Sonarr/wiki/Series#get) checking if the path matches an existing series and then either rescanning it (https://github.com/Sonarr/Sonarr/wiki/Command#rescanseries) or adding it (https://github.com/Sonarr/Sonarr/wiki/Series-Lookup + https://github.com/Sonarr/Sonarr/wiki/Series#post).

> At the very least, allow users to create a custom pattern for episode naming. I believe even if you have renaming turned off, sonarr will use the episode naming template it uses for the renaming to scan for TV shows.

I don't understand what you mean, but this doesn't sound like the same thing.
