### ISSUE TITLE
Download stuck in Queue

### ISSUE THREAD

**Issue by Ninjouz** [Sonarr/Sonarr#1849]
Hey guys,

I have several downloads stuck in the Queue panel on Sonarr.

Those nzbs were completed by Sabnzbd but each time Sonarr scans the completed list, it reports that type of error : 

```
17-4-14 19:12:59.0|Debug|FullSeasonSpecification|Single episode file detected as containing all episodes in the season
17-4-14 19:12:59.0|Debug|VideoFileInfoReader|Getting media info from /usenet/series_sonarr/Game.Of.Thrones.S01E06.1080p.BluRay.DTS.x264-ESiR/Game.of.Thrones.S01.Ep06.1080p.BluRay.DTS.x264-ESiR.mkv
17-4-14 19:12:59.0|Debug|DetectSample|Runtime is over 90 seconds
17-4-14 19:12:59.0|Debug|UpgradeSpecification|This file isn't an upgrade for all episodes. Skipping /usenet/series_sonarr/Game.Of.Thrones.S01E06.1080p.BluRay.DTS.x264-ESiR/Game.of.Thrones.S01.Ep06.1080p.BluRay.DTS.x264-ESiR.mkv
```

while obviously it's a single episode.

I'm on the latest stable.

**Comment by Taloth** [comment]
ESiR made a typo. episodes are normally named S01E06 or S01.E06 not Ep06, that's likely what's getting the parser confused.
Easiest is just do a manual import (button on the far right).

I'll see about tweaking the parser a bit.

**Comment by Ninjouz** [comment]
Oh yeah, the folder / nzb are named ok (SXXEXX) but not the extracted mkv file.

I try renaming the file to the correct format (removing the dot) and auto import worked.
Manual import is also a nice feature, thanks for the tips.
