### ISSUE TITLE
Issue when adding series through the API

### ISSUE THREAD

**Issue by tidusjar** [Sonarr/Sonarr#1852]
Hi guys!

So i've come across what I think could be an issue.

I'm calling the `/api/series` endpoint with a `POST` with the following body:
```
{
  "addOptions": {
    "ignoreEpisodesWithFiles": true,
    "ignoreEpisodesWithoutFiles": false,
    "searchForMissingEpisodes": true
  },
  "title": "Homeland",
  "seasons": [
    {
      "seasonNumber": 1,
      "monitored": false,
      "statistics": null
    },
    {
      "seasonNumber": 2,
      "monitored": false,
      "statistics": null
    },
    {
      "seasonNumber": 3,
      "monitored": false,
      "statistics": null
    },
    {
      "seasonNumber": 4,
      "monitored": false,
      "statistics": null
    },
    {
      "seasonNumber": 5,
      "monitored": true,
      "statistics": null
    },
    {
      "seasonNumber": 6,
      "monitored": false,
      "statistics": null
    }
  ],
  "rootFolderPath": "D:\\Media\\TV Shows\\",
  "qualityProfileId": 1,
  "seasonFolder": true,
  "monitored": true,
  "tvdbId": 247897,
  "tvRageId": 0,
  "cleanTitle": null,
  "imdbId": null,
  "titleSlug": "Homeland",
  "id": 0,
  "images": []
}
```

Now what I am expecting is since all the seasons except season 5 are not monitored and since the `searchForMissingEpisodes` flag is true, I would expect Sonarr to only search for season 5, but it seems to be searching for every single season no matter their monitored status.

Is this intended? 
If so what is the best way to get around this? Is it to set the `searchForMissingEpisodes` flag to false and then separately ask Sonarr to search for the season?

Thanks

**Comment by markus101** [comment]
What is the monitored status of all the episodes after the series is added? Are episodes in other seasons monitored (regardless of the season being monitored)?

**Comment by tidusjar** [comment]
So the monitoring part is working, it's only monitored what I told it to, but its still doing a search for the whole series.

So all the episodes are unmonitored and all seasons are unmonitored except for season 5 in the example above.

**Comment by markus101** [comment]
It looks like the episode is monitored, despite the season being unmonitored due to `ignoreEpisodesWithoutFiles` being `false`. I think what we need to do here is ignore episodes if the season is ignored, regardless of the episode monitored flags, but still allow the episode flag to apply when the season is monitored (and we'd unmonitor the season if all episodes are unmonitored). I need to verify that this doesn't cause any issues.

Simplifying the API to only handle the cases the Sonarr UI exposes is also something we're considering, but that would break this specific scenario.

**Comment by tidusjar** [comment]
That does make sense. Let me know if i can be of any assistance.

**Comment by kdizzay** [comment]
Hi, I downloaded the latest Sonarr update 2.0.0.4748 but looks like this fix didn't make it in since the issue is still open. Would like to +1 this, thank you.

**Comment by tidusjar** [comment]
@kdizzay just keep in mind that there is probably plenty of work to be done, this is probably not top of the priority list :)
