### ISSUE TITLE
Add category to torrent depending on what indexer grabbed it.

### ISSUE THREAD

**Issue by Nivius** [Sonarr/Sonarr#1853]
id request this feature:
Add category to torrent depending on what indexer grabbed it.

so if i grab a torrent from my indexer "indexgrabber2" my torrent will get the tag "indexgrabber2" as well to the original one (tv-sonarr) (replace might even be easier)

That way we can treat torrents differently depending on where it was taken from. (Great for sites with different seed rules)

**Comment by markus101** [comment]
We do not have plans to support different categories based on the indexer.

Having Sonarr being able to differentiate and apply different seeding rules is something we have plans to do.

**Comment by Nivius** [comment]
cool, that kinda solves the problem as well. might be a hell tho as different clients support diffrent things. (qbittorrent don't even support seed over x time yet...)

**Comment by markus101** [comment]
Sonarr would need to know hoe long it has been seeding for and know the rules for that indexer to know when to remove it, it wouldn't need qbittorrent to enforce anything.

**Comment by Nivius** [comment]
If you can make that work it will be truly awesome and it whould remove a big headache for me
