### ISSUE TITLE
Specify Seed Ratio / Time per Indexer

### ISSUE THREAD

**Issue by daviddavo** [Sonarr/Sonarr#1854]
On the Download Client settings, it would be nice to customise the "remove" option.
For example, depending on tracker, on ratio, or on time served

**Comment by markus101** [comment]
This would be a per-indexer setting, but also linked to removing downloads from a download client so it will need to be done in a way that makes sense to tie into both (not removing if removing is disabled, regardless of the limits set on the indexer).

**Comment by Webreaper** [comment]
Would definitely be cool to have the torrent removed from the download client once a release from a particular indexer has been imported successfully. :)

**Comment by ElevatorCh** [comment]
+1 would be really helpful.

**Comment by markus101** [comment]
Implemented in https://github.com/Sonarr/Sonarr/pull/2272 any clients not yet supported should have a GHI opened to implement it.
