### ISSUE TITLE
Required/Ignored words applying to everything not just shows tagged

### ISSUE THREAD

**Issue by joshstrange** [Sonarr/Sonarr#1855]
I have a show that has both the main show and then a "Backstage" version that airs later. I had issues where the main show was downloading the behind the scenes version and so I added a restriction with the word and a tag which I then added to the main show. Recently I decided to start downloading the backstage version but Sonarr won't pick it up and when I do a manual search It say's it was rejected for containing a restricted word even though it doesn't contain the tag.

Example:
Series:
- Main Show | Tags: nobackstage
- Main Show: Backstage | Tags: N/A

Restrictions:
- Must Contain: N/A | Must Not Contain: Backstage | Tags: nobackstage

I also tried added a second restriction resulting in the following:

Series:
- Main Show | Tags: nobackstage
- Main Show: Backstage | Tags: backstage

Restrictions:
- Must Contain: N/A | Must Not Contain: Backstage | Tags: nobackstage
- Must Contain: Backstage | Must Not Contain: N/A | Tags: backstage

Sonarr Ver. 2.0.0.4645
Running in docker container on UnRaid

Am I misunderstanding how restrictions/tags work?

**Comment by markus101** [comment]
Please use the forums for support.

We'll need to see debug logs of the result processing to see why that's happening, but it may be how the releases are named/parsed by Sonarr.
