### ISSUE TITLE
Tag/Label Torrent based on Single or Season/Batch

### ISSUE THREAD

**Issue by xInsertx** [Sonarr/Sonarr#1856]
Some private trackers have different seed rules for single torrent vs batch torrent. It would be since if we could list two types of labels under torrent. 

A label for single torrents and one for batches. This would allow use to tie rules in deluge/rtorrent based on labels.

#1854 would be a similar way to achieve this if the rule applied separately on seasons vs episode downloads.

**Comment by markus101** [comment]
Similar to https://github.com/Sonarr/Sonarr/issues/1853 and as you pointed out, #1854 which would need to take season packs/batches into account.
