### ISSUE TITLE
Add Lithuanian language

### ISSUE THREAD

**Issue by mrVito** [Sonarr/Sonarr#1857]
Please add an ability to enter a custom language code when creating a profile as currently the list is pretty short and does not include many languages (Including the one I need - Lithuanian).

Thank you for your great work :)

**Comment by markus101** [comment]
No plans to support custom languages, but additional ones can be added. We'll need some examples of releases that are tagged with Lithuanian to ensure they are parsed properly.

**Comment by mrVito** [comment]
Here are some examples of releases with Lithuanian language:
`Prison.Break.S05E01.WEBRip.x264.AC3.LT.EN-CNN`
`The.Big.Bang.Theory.S08E01.1080p.BluRay.x264.DTS.LT.EN-CNN`
`A.Place.to.Call.Home.S03E01.720p.WEB-DL.x264.AAC.LT.EN-CNN`

Note that releases have both EN and LT locale provided in their name. It's because most releases have both original and LT audio tracks included.

**Comment by Taloth** [comment]
@markus101 Looks like we gotta be quite strict on that tag. How about being case sensitive in this case to avoid falce positives? Or should we wait for the advanced parser?

**Comment by markus101** [comment]
Case sensitive sounds good, I don't think we should kick this to the advanced parser work. Tagging this with v3 since it would disrupt the language profile changes there.
