### ISSUE TITLE
[Feature Request] Regex Replacement

### ISSUE THREAD

**Issue by Kikidy-cam** [Sonarr/Sonarr#1858]
Firstly, I would like support for the use of film naming conventions.
i.e. Sentence case for all words except articles, prepositions and coordinating conjunctions <= 4 letters.
e.g. a, an, the, with, from, down, to, etc.
Secondly, I would like support for the use of replacements for windows file-path restricted characters.
e.g. ':' -> ' -', '/' -> '⌿', '?' -> '¿', etc.
Thirdly, I would like support for the convention of numbers in names.
i.e. 3 -> Three, 11 -> Eleven, 1st -> First, etc. OR Three -> 3, Eleven -> 11, etc.

I believe all of which could be achieved with a list of regex replacement rules under 'Episode Naming'.

N.B. it doesn't have to, but it would be nice to cater for, a maximum length for titles before they are truncated or curtailed, as well. e.g. abcdefghijklmnopqrstuvwxyz -> abcdefghijklmnopqrst...

**Comment by markus101** [comment]
> i.e. Sentence case for all words except articles, prepositions and coordinating conjunctions <= 4 letters.
e.g. a, an, the, with, from, down, to, etc.

This is something that should be addressed at the source I feel, which would be TheTVDB, if they are wrong, though as they are titles different rules would apply.

> Secondly, I would like support for the use of replacements for windows file-path restricted characters.
e.g. ':' -> ' -', '/' -> '⌿', '?' -> '¿', etc.

Sonarr does replace some of these character already, we do not have plans to support customization of the replacement rules though.

> Thirdly, I would like support for the convention of numbers in names.
i.e. 3 -> Three, 11 -> Eleven, 1st -> First, etc. OR Three -> 3, Eleven -> 11, etc.

I don't see a lot of use for this, plus it is definitely a can of worms in that people are going to want different rules applied at different times and inevitably people will run into issues with regex and it's not something we want to support.

At this time this isn't something we plan to implement.
