### ISSUE TITLE
RSS feed results immune to Blacklist?

### ISSUE THREAD

**Issue by GregoryGHarding** [Sonarr/Sonarr#1861]
hello all,

whenever i blacklist a release and the indexers run to check for another, it goes successfully.. found or not a new release.. but give it the time duration for my RSS Scan to kick in and poof, the same release is added to my downloader.

is this a feature or a bug? i would like to say its the later... 

Thanks IA

**Comment by markus101** [comment]
They are not, there are several pieces of information Sonarr uses to determine whether a release is the same as a blacklisted release, which includes the indexer, the releases unique ID and the date of the release. If the unique ID changed Sonarr would treat them as different releases.

Please open a thread on the forums with the requested information (including debug logs) and the release in question so we can investigate further.
