### ISSUE TITLE
Full season pack downloaded after last episode

### ISSUE THREAD

**Issue by talentedmrripley** [Sonarr/Sonarr#1862]
Sonarr has been grabbing episodes of Hap and Leonard for me as they come out.  The last episode was downloaded yesterday.  For some reason though, today it grabbed a complete season pack.  With this series as I watch them I delete them.  And I have Ignore Deleted Episodes enabled.  I'm not sure what triggered it to grab the season pack as the only episode that was monitored was S02E06.  

Version 2.0.0.4689
Mono Version 4.2.3
OS Ubuntu 16.04LTS
Indexer BtN

**Comment by markus101** [comment]
To confirm, a single episode for S02E06 had not been downloaded before the season packs was grabbed?
