### ISSUE TITLE
Cannot add files in Sonarr and invalid Unix paths

### ISSUE THREAD

**Issue by Kryptonyte** [Sonarr/Sonarr#1863]
Verion: 2.0.0.4689
Mono version: 4.6.2
OS: Asustor ADM 2.7.1.RFT5 (4.4.24 kernel x86_64)

When going into Series -> Add Series -> Search for name of series and clicking the add button , the icon displays like it is loading, but then does not add the show to Sonarr.

Within the attached sonarr.debug.txt you can see this happening at 17-4-21 16:44:17.3

This has previously worked fine and the paths have not changed.  Could this be related to the mono version?

I am presuming not being able to add shows could also be related to other errors in the logs relating to this message:

[/volume1/Videos/TV Shows/Revenge] is not a valid *nix path. paths must start with /

[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/946580/sonarr.debug.txt)
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/946589/sonarr.txt)

**Comment by markus101** [comment]
Please use the forums for support.

It looks like instead of a space between `TV` and `Showw` that there is at least one Unicode character, that is likely messing things up.
