### ISSUE TITLE
How to disable update checking in docker container

### ISSUE THREAD

**Issue by mfgering** [Sonarr/Sonarr#1864]
When running sonarr inside a docker container, it is not a good thing to update the program -- the actual code will be reverted when the container is restarted, but the databases and config files will be retained and possibly become incompatible.

The check for updates task seems to be hardwired and the indicator will show when an update is available. I'd like to prevent the check by disabling the task. I see where to do it in the sqlite database, but doing that with a script is an ugly hack. What should be the best solution?

Thanks,
Mike

**Comment by markus101** [comment]
Disabling the interval would still allow the task to be run manually, but unless updating is enable no update would be installed during the scheduled execution.

Disabling it in the database would be reset everytime the container is restarted and the defaults a e written back to the database.

What exactly are you trying to avoid here, accidentally updating or just getting rid of the update notification messages (that say it's restarting to apply an update, but isn't really).

**Comment by Taloth** [comment]
There's a setting for that in Settings->General.

![image](https://cloud.githubusercontent.com/assets/6383890/25286578/851f63ac-26be-11e7-851d-0df3c80fe053.png)

**Comment by mfgering** [comment]
Sorry I didn't get back sooner. The Settings->General->Updates doesn't appear to prevent the program from *checking* there is an available update. Correct?

Markus101: About restarting the container, the database and other config settings are mapped to the host filesystem, so they persist between restarts. The updated code is in the container so it doesn't persist between restarts.

The docker image I'm referring to is [freenas/sonarr](https://hub.docker.com/r/freenas/sonarr/) and the parameter is '/config' . This image is derived from [linuxserver/sonarr](https://hub.docker.com/r/linuxserver/sonarr/).

**Comment by markus101** [comment]
> Sorry I didn't get back sooner. The Settings->General->Updates doesn't appear to prevent the program from checking there is an available update. Correct?

Correct. In addition Sonarr was reporting it was restarting to apply the update, even if there wasn't an update or the update check was aborted because automatic updates is disabled.

We don't have plans to disable update checking as that is still a valid thing to do and does let the user know that they should update the container (if they're running in a container) if not they can update directly in Sonarr as they may have automatic updates disabled for other reasons.

**Comment by mfgering** [comment]
Thanks. One last question: Is there documentation somewhere about the config.xml file?

**Comment by markus101** [comment]
No, the settings themselves are controlled via the UI, there should be almost no reason to edit it directly, except to update the logging level if Sonarr is failing to start or reset the authentication.
