### ISSUE TITLE
Support for download client priority

### ISSUE THREAD

**Issue by RaphaelJenni** [Sonarr/Sonarr#1866]
It would be nice if you can set a main download client and a fallback one (prioritize clients).

In my case, I use my normal work machine during the day. It has way more power than my nas, where sonarr is running on. So I want, that during the day, sonarr downloads the series via sabnzbd on my PC and switches to the sabnzbd on my NAS during the night (when my PC isn't running).

**Comment by markus101** [comment]
Perhaps something that could be useful in combination with disabling offline download clients, but we'd need to add the ability to prioritize them still. Definitely limited to a small number of users though.

**Comment by rnyberg** [comment]
Either **1)** This or **2)** toggle for being enabled but not accepting new downloads would be really nice. 

Another use case for the feature would be migrating from one download client to another on the fly. Older secondary client can still churn through whatever is in the queue while new one gets the fresh stuff.

**Comment by markus101** [comment]
Done in https://github.com/Sonarr/Sonarr/pull/2278
