### ISSUE TITLE
Health Checks on mount points

### ISSUE THREAD

**Issue by kyse** [Sonarr/Sonarr#1867]
Background: I noticed when messing with Ubuntu as a vm inside ESXi, using SATA controller instead of SCSI controller when using sata drives I exposed to the VM as a raw device mapping was a mistake.  The smart info wasn't available for the drives using the SATA controller, but worked fine with SCSI controller, and also I experienced errors in Sonarr once in a while where an import failed.  Obviously checking the logs it became apparent the access to path denied error wasn't so much related to permissions, but more so because of some error on the mount causing it to remount as read only.

So, I downloaded the source, and have been playing around with the health checker code, and grabbing series paths to determine mount points of interest to be monitored.  I figure mixing this with the procmount info, could we make the error message for a failed import a little more obvious for this scenario?

Or even a status alert that a mount point used in one of the existing series paths is mounted as read only.

Thoughts?  Is this something I should continue working towards a PR for you all?  Pretty sure I already fixed up my issue with my mount remounting read-only when I switched back to the SCSI controller, but figure this could be helpful during an issue in the future one day when drives start failing.

**Comment by kyse** [comment]
I was able to get this working.

Exposed the mount options in the underlying mono IMount interface implementation.  I ran into a problem at first because certain mounts (mainly the actual mounts one would probably care about) weren't having their mountoptions value passed in to the final list returned from the service.  This was due to the list being built by first grabbing disks from the System.IO library, then concating the list with any additional mounts found from the mono implementation.  Reversing this fixed that problem, and I was able to successfully parse mount options for rw, or ro to determine how the mount was mounted.  In the health check, comparing a distinct list of series mounts (cause why do we care about mounts series aren't targeting) to find any ro mounts resulted in the desired warning output.

I noticed a list being build in one of the services ignores mounts with a path of /var/lib saying folks wouldn't care about anything mounted here, but for my case, I have one drive mounted under /var/lib/plexmediaserver/... because that's the home dir of the plex user.  So just a thought, that if block might want to be rethought.

**Comment by markus101** [comment]
Improving messaging to users is definitely useful. This seems like a worthy improvement and we'd be interested in a PR for it.

> This was due to the list being built by first grabbing disks from the System.IO library, then concating the list with any additional mounts found from the mono implementation.

This is intentional to prefer the information in mono over the information in proc/mounts in the event we're parsing something wrong (or something similar), but perhaps a better middle-ground would be to take the information from mono and add in anything else provided by parsing proc/mount.

> I noticed a list being build in one of the services ignores mounts with a path of /var/lib saying folks wouldn't care about anything mounted here, but for my case, I have one drive mounted under /var/lib/plexmediaserver/... because that's the home dir of the plex user. So just a thought, that if block might want to be rethought.

It seems like an edge case that wouldn't affect most users, unless it's something that affects a number of people I don't see it being worth the effort to support an option for it or an alternative way of filtering it, especially since it could be mitigated by mounting it elsewhere (if it was something Sonarr would require checking).

**Comment by Taloth** [comment]
`/var/lib/plexmediaserver/... ` 

Change the filter from `/var/lib/` to `/var/lib/docker/` and I'm happy... see the comment in the code, it doesn't really matter anyway since it was mostly cosmetic.

**Comment by kyse** [comment]
I will work on getting a PR submitted based on your contribution documentation then since you see it being worth while, thanks.

To the last comment.  While I understand where you're coming from.  With Radarr being a fork of Sonarr, it seems like the two libraries might benefit eventually from actually using more of a common code structure rather than a fork.  Plus, I have a desire to build out an HTPC Manager app based on the common code as well that can integrate with both Sonarr and Radarr api + signalr, thus... that is why I figured that if check there would come back to bite me if I waned to monitor my ssd mounts for plex transcoding.

**Comment by markus101** [comment]
> With Radarr being a fork of Sonarr, it seems like the two libraries might benefit eventually from actually using more of a common code structure rather than a fork

It's something we've briefly touched on with the Radarr devs, but it'd be non-trivial and adds some development overhead and not something we're focused on.
