### ISSUE TITLE
Cannot access a disposed object.  Object name: 'System.Net.Sockets.NetworkStream'.

### ISSUE THREAD

**Issue by kyse** [Sonarr/Sonarr#1869]
Been noticing an error popping up in my logs recently.  Not sure, but think it only started happening after the latest update.

Unable to retrieve queue and history items from [my.nzbget.url] (NZBGet): Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.

**Comment by markus101** [comment]
Without knowing more details about your setup and the full stacktrace for the error there isn't anything actionable here, though this is best suited for the forums to troubleshoot further, so please open up a thread there.
