### ISSUE TITLE
Weird links in series description.

### ISSUE THREAD

**Issue by Crowley007** [Sonarr/Sonarr#1870]
This has started to happen recently. Many series descriptions have weird links in them, picture attached. I wonder what's going on.

Windows 10
Sonarr version: 2.0.0.4689 - 06 Apr 2017

 ![pic](https://cloud.githubusercontent.com/assets/23026322/25377168/71de90e4-29af-11e7-9f51-4d802e272bf2.PNG)

**Comment by anonaut** [comment]
This text is parsed from thetvdb.com. Since tvdb is community curated someone posted the link into the series description. I removed the link from the description and gonna file a report

**Comment by Crowley007** [comment]
Yeah, you are right. I guess the site has had a spam problem recently, those links appear in multiple series.

**Comment by thezoggy** [comment]
suggestion for devs: strip url from show description text to prevent malware/spam/etc

**Comment by Crowley007** [comment]
The spam links seem to be back. 

The suggestion above would be great if possible. They are working on it on TVDB https://forums.thetvdb.com/viewtopic.php?f=4&t=37093 but some anti spam check in Sonarr wouldn't hurt.

**Comment by markus101** [comment]
Our proxy has some additional checks to strip out the spam links from descriptions, which was deployed several hours ago, if there is a particular series you're seeing it with _after_ refreshing the series in Sonarr let us know, otherwise we'll close this out.

**Comment by Crowley007** [comment]
Yeah, refreshing again fixed this for all my series. Will report back if it happens again.
