### ISSUE TITLE
Wrong password notification/popup

### ISSUE THREAD

**Issue by mattya802** [Sonarr/Sonarr#1871]
There is currently not text/pop up/notification when you type in the wrong username/password when logging into Sonarr. Not a huge deal, but would be a nice, quick little addition. 

Thanks!

**Comment by thezoggy** [comment]
switch to form based auth

**Comment by mattya802** [comment]
I do have form based auth selected.

**Comment by thezoggy** [comment]
hmm could have sworn it used to show the blurp when you did invalid auth... apparently not

**Comment by markus101** [comment]
This is taken care of in the v3 UI work.
