### ISSUE TITLE
Cookies should have a path of /URLBASE when that option is set

### ISSUE THREAD

**Issue by bradmurray** [Sonarr/Sonarr#1874]
Cookies are all set to / which makes them collide with other apps that use the same cookie names on the same server. Plus it makes cookies bleed into other apps.

**Comment by Taloth** [comment]
You mean Sonarr's authentication cookie?

**Comment by bradmurray** [comment]
Yes and all sonarr cookies. If I have the site running in the subdirectory /sonarr/ on the server it should be setting cookies to only be on that url and below.
