### ISSUE TITLE
No results for Better Call Saul Tv Show

### ISSUE THREAD

**Issue by weslley39** [Sonarr/Sonarr#1883]
I'm using Jackett, for provide info for a big brazilian tracker called Bj-Share.

But, for some reason, when i try to do a manual search, the search goes like:

Searching 1 indexers for [Better Call Saul : 2017-04-24
![screen shot 2017-04-29 at 16 04 30](https://cloud.githubusercontent.com/assets/5286092/25558074/ba1c56e0-2cf5-11e7-9164-bf197874e02d.png)

and i think, that because of this type of search is not returning any results.

But when I try to search for Supernatural.

![screen shot 2017-04-29 at 16 07 23](https://cloud.githubusercontent.com/assets/5286092/25558089/f72fe682-2cf5-11e7-83b3-0a1faf3d1fb5.png)
![screen shot 2017-04-29 at 16 07 15](https://cloud.githubusercontent.com/assets/5286092/25558090/f7321be6-2cf5-11e7-9f18-97d422921073.png)

some results are found.

I can do something to fix this search. i think if instead of search by the date of the episode (like the Better Call Saul), and filter by season/episode (like Supernatural), will return results for.

**Comment by Taloth** [comment]
You erroneously set the series type to daily. You can edit it via the series detail page.

**Comment by weslley39** [comment]
@Taloth Thanks for your help.
