### ISSUE TITLE
New season of anime series with different Title is searched with absolute numbering

### ISSUE THREAD

**Issue by ramattos** [Sonarr/Sonarr#1887]
I just tried adding anime series "Saenai Heroine no Sodatekata" (imported as "Saekano: How to Raise a Boring Girlfriend" from TVDB).

The series is currently running a second season, which is named "Saenai Heroine no Sodatekata Flat". This is quite common in anime series, for a series to have a different name in a later season. The alternate Titles ("Saekano S2", "Saenai Heroine no Sodatekata Flat") are correctly grabbed and displayed under "Scene Information".

The search service will correctly attempt to search for the series by using those additional titles when searching for second season episodes for this show. However, the search is using absolute numbering (which is a problem).

17-5-1 02:49:11.2|Info|NzbSearchService|Searching 2 indexers for [Saekano: How to Raise a Boring Girlfriend : 13]
17-5-1 02:49:11.2|Debug|Nyaa|Downloading Feed https://www.nyaa.se/?page=rss&cats=1_37&filter=2&term=Saekano+13
17-5-1 02:49:17.9|Debug|Nyaa|Downloading Feed https://www.nyaa.se/?page=rss&cats=1_37&filter=2&term=Saenai+Heroine+no+Sodatekata+13
17-5-1 02:49:22.7|Debug|Nyaa|Downloading Feed https://www.nyaa.se/?page=rss&cats=1_37&filter=2&term=Saekano+S2+13
17-5-1 02:49:27.2|Debug|Nyaa|Downloading Feed https://www.nyaa.se/?page=rss&cats=1_37&filter=2&term=Saenai+Heroine+no+Sodatekata+Flat+13
17-5-1 02:49:31.6|Debug|Nyaa|Downloading Feed https://www.nyaa.se/?page=rss&cats=1_37&filter=2&term=Saekano+How+to+Raise+a+Boring+Girlfriend+13
17-5-1 02:49:36.1|Debug|NzbSearchService|Total of 0 reports were found for [Saekano: How to Raise a Boring Girlfriend : 13] from 2 indexers
17-5-1 02:49:36.1|Info|DownloadDecisionMaker|No results found

The problem here is that, for anime series with a different name for their n-th season (n>2), they never use absolute numbering. Relative numbering would work in that case instead, as you can see by clicking here: https://www.nyaa.se/?page=rss&cats=1_37&filter=2&term=Saenai+Heroine+no+Sodatekata+Flat+01

There needs to be a way to either tell the search service to use relative numbering when searching for season 2+ episodes with alternate scene provided titles. Otherwise, the only other option I see here is to unmonitor all episodes for the second season of that show, and find a way to add the second season as a completely different series with a different name.

**Comment by M0UL** [comment]
this is already fixed on thexem.de (http://thexem.de/xem/show/3717) with sonarr use for the numbering for anime. Next time something like this happens, join #xem support channel on irc.freenode.net.

**Comment by ramattos** [comment]
Thank you very much for your help.
