### ISSUE TITLE
Strange behavior with snatch and download

### ISSUE THREAD

**Issue by Jorman** [Sonarr/Sonarr#1889]
Hi, I'm using the 2.0.0.4724 - 29 Apr 2017  develop version of Sonarr

I don't know why but is a while that Sonarr download a HDTV-1080p version, then after that a WEBDL-1080p, then the HDTV-1080p and so on, for the same episode, for the same serie.
![snap](https://cloud.githubusercontent.com/assets/5203988/25614794/d3c0bed4-2f33-11e7-8fd5-936651268568.PNG)

Normally my Cutoff is set to WEBDL-1080p, but now I just changed it to HDTV-1080p to see if resolve the strange situation.

If I got it well the Cutoff is the point where Sonarr will stop to search if this or higher quality is reached during a search, am I right?

Jo

**Comment by Taloth** [comment]
Can you post a screenshot of the details of the import event?
What's happening is that the indexer release name contains web-dl, so sonarr grabs the download coz it's a web-dl, but when i gets around to importing it, it appears to be another quality. The import event will show which folder and file names sonarr sees during import.

**Comment by markus101** [comment]
I added a check on import to prevent the release from importing if the quality doesn't match the grabbed episode (when available), which means the original download would stay in the queue until manually imported or removed and would prevent other releases from being queued if the cutoff was already met.

**Comment by Jorman** [comment]
I hope this can help, tell me if any others log can be helpful:
https://pastebin.com/KzW3dJRT
https://pastebin.com/nMBWHM0f

**Comment by Jorman** [comment]
Tnx for your support.

What about a different aproach like:

If this happen, the download will be imported like the real quality
then the download is marked as failed, so Sonarr still search the correct
quality but don't download again the same release?

Make sense for you?

The good of the automatic programs is that you don't have to touch it to much, in that way one person have to check if some goes wrong
and with out any notification or any kind of place to see what need to be checked is "more" difficult, I think.

**Comment by markus101** [comment]
> If this happen, the download will be imported like the real quality only if the downloaded quality is better or is the cutoff than the already present one
then the download is marked as failed, so Sonarr still search the correct quality if neede and don't download again the same release?

It will block the import so it will need to be either imported manually or rejected, we have plans to use more information when importing to make a more informed decision, but for the moment some manual intervention is required to address this.
