### ISSUE TITLE
Indexer Issue

### ISSUE THREAD

**Issue by ForgottenSpecialist** [Sonarr/Sonarr#1891]
Hey,

New katcr.co will not be added?

I can add this to the Fork Radarr for movies without any issues, I've also tried though jackett but has the same result.

Seems sonarr is trying to go directly to " https://katcr.co/api?t=caps"??? But this is invalid, not sure why Radarr can handle this correctly.

**Comment by markus101** [comment]
No, they don't have an API.

It looks like Radarr removed KAT after re-adding it.

That looks like you added it as a Torznab indexer to Sonarr, not through Jackett since it's making a request straight to KAT's site, which yes, is invalid.
