### ISSUE TITLE
Parsing of episodes fails: "Invalid season or episode"

### ISSUE THREAD

**Issue by petwri** [Sonarr/Sonarr#1892]
System:
Ubuntu Linux 4.4.0-75-generic 
Mono Stable 4.8.1.0/22a39d7
Sonarr 2.0.0.4689

When trying to manually import via Drone Factory, the following episodes fail with the status `Invalid season or episode`:

- South.Park.S05.1080p.WEB-DL.AAC2.0.H264-jhonny2[rartv]/South Park S05E03 Super Best Friends (712x480) [Phr0stY].mkv
- South.Park.S14.1080p.BluRay.x264.DD5.1-Phr0stY[rartv]/South Park S14E05 200 (1920x1080) [Phr0stY].mkv	
- South.Park.S14.1080p.BluRay.x264.DD5.1-Phr0stY[rartv]/South Park S14E06 201 (1280x720) [Phr0stY].mkv

**Comment by markus101** [comment]
It's the release group in square brackets triggering the anime parser. It's covered by: https://github.com/Sonarr/Sonarr/issues/457

You can use Manual Import from Wanted: Missing to work around it.
