### ISSUE TITLE
Ability to specify seeding settings for Synology Download Station

### ISSUE THREAD

**Issue by Webreaper** [Sonarr/Sonarr#1894]
It would be great if it was possible to configure the setting ratio/time for torrents created by a DS download client, and have them pass through to DS. Then I could configure DS to seed longer/infinitely on private trackers, etc. It would even allow a number of DS clients to be created each with different seed time/ratio settings, so that stuff snatched from different location could be seeded as appropriately. 
Not sure whether this is possible, as I don't know the details of the DS API, but would be great if it's simple to do.

**Comment by margaale** [comment]
It would be the same that loging in into DS and mannualy configure it there. It's a global setting affecting the DS. There is no way to configure an specific radio/time for one torrent only...

**Comment by Webreaper** [comment]
Seeding time and ratio isn't a global setting, it can be edited and set on a torrent-by-torrent basis. 

But if the API for adding torrents doesn't allow you to specify it, then it probably can't be done. 

I'll have a look at the code and dig around into the API myself though.

**Comment by margaale** [comment]
Sorry, I meant from the api point of view...

**Comment by Webreaper** [comment]
Confirmed, not possible with current Synology API. :(
