### ISSUE TITLE
issues with hardlinks

### ISSUE THREAD

**Issue by matthewdias** [Sonarr/Sonarr#1896]
When I use manual import to move a series to my library location, the hardlink setting is not respected. The reference to the files is lost for transmission. I initially thought this might be an issue with hardlinks not working because I have transmission in a docker container. But doing an `ls -l` on the imported files shows only 1 reference, which if I'm not wrong means that those are the only references to the files, and the hardlinks were not created.

**Comment by matthewdias** [comment]
im not sure why this should break hardlinks on manual import tho, because sonarr should be creating the links in the location where the file was before it was moved right? unless my original assumption about docker not working with hardlinks is correct.

**Comment by matthewdias** [comment]
if this is indeed the case, i guess my workaround for import should be to dockerize sonarr as well, and name the volumes accordingly. but this still doesn't fix the hardlink issue (assuming that it is a valid issue)

**Comment by Taloth** [comment]
> I initially thought this might be an issue with hardlinks not working because I have transmission in a docker container. But doing an ls -l on the imported files shows only 1 reference, which if I'm not wrong means that those are the only references to the files, and the hardlinks were not created.

I don't see how 'but' applies, those things aren't mutually exclusive. `ls -l` simply shows there is no hardlink, it wouldn't prove any particular cause.

> This also breaks automatic imports, because sonarr tries to import from the location that transmission is reporting.

Remote path mapping (Settings->Download Clients) allows you to provide the mapping.

Hardlinks only work on the same filesystem. If you can't create a hardlink via `ln` cmdline, then sonarr can't either. Also, tracelogs will show that Sonarr attempts to hardlink.

But please, post support questions on the forums.
