### ISSUE TITLE
Importing existing series - "episode missing from disk"

### ISSUE THREAD

**Issue by Quiksmage** [Sonarr/Sonarr#1897]
Hi,

When importing an existing series, an episode which has a number in the episode title can cause the episode to not be imported correctly.

For instance, the below episode is shown as "missing from disk"

E:\How I Met Your Mother\Season 5\How I Met Your Mother - S05E03 - Robin 101 [1080p WEB-DL h264]-SA89.mkv

All other episodes in this series are properly importing.

Is there some way around this such as manually telling sonarr where this file is?

**Comment by Quiksmage** [comment]
Another few examples

S:\That '70s Show\Season 6\That '70s Show - S06E21 - 515 [1080p BluRay x264]-YELLOWBiRD.mkv
E:\New Girl\Season 5\New Girl - S05E14 - 300 Feet [1080p WEB-DL h264]-NTb.mkv
O:\Once Upon A Time\Season 1\Once Upon a Time (2011) - S01E10 - 715 A.M [1080p WEB-DL h264]-SA89.mkv
S:\Lost\Season 5\Lost - S05E06 - 316 [1080p BluRay x264]-HDMI.mkv
S:\The Man Show\Season 4\The Man Show - S04E14 - 100 Shots With Super Dave [DVDRip XviD]-NOGRP.avi
S:\Fringe\Season 3\Fringe - S03E20 - 602 AM EST [1080p BluRay x264]-FLHD.mkv

It was also unable to import a multi-episode properly which had a number in its name

O:\Seinfeld\Season 6\Seinfeld - S06E14E15 - The Highlights of 100 [720p WEB-DL h264]-NTb.mkv
It marked episode 15 as missing in this case.

**Comment by markus101** [comment]
It's the square brackets around the quality + the 3 digit episode number causing it to be treated as anime in the parser. This is being tracked via: https://github.com/Sonarr/Sonarr/issues/457 but in the mean time you can use Manual Import from Wanted: Missing to import those episodes correctly.

**Comment by Quiksmage** [comment]
So, if I change my naming convention to  (), The issue should go away? Thanks for the response

**Comment by markus101** [comment]
It should (I can't think of anything that relies on `()` to change how things are parsed), trying with an affected show to start would be advisable though.

**Comment by Protektor-Desura** [comment]
I should add that I use:
/New-TV/The 100 (2014)/Season 1/The 100 - S01E01 - Pilot [Bluray-1080p HEVC AAC].mkv

and it works just fine. If I do this:
/New-TV/The 100 (2014)/Season 1/The 100 - S01E01 - Pilot [1080p HEVC AAC].mkv

It does not work and isn't imported.
So there is definitely a bug if simply adding "Bluray-" makes it work.
