### ISSUE TITLE
Option for delay setting in Connect with external server after download

### ISSUE THREAD

**Issue by zenjabba** [Sonarr/Sonarr#1898]
When Sonarr downloads a file and pushes it to the final location, I have a "Connect" option configured to tell Plex to rescan just that specific tv show. I would like to have an advanced option to delay the "push to Plex" via the connect setting so the cloud drives can have a chance to sync up. It generally take 1-2 mins for everything to settle down after the upload has finished.

**Comment by markus101** [comment]
This sounds like something better suited for a custom script or something handled outside of Sonarr (have the refresh triggered after the cloud upload completes instead of after Sonarr imports it). This isn't something that we plan to add to Sonarr.
