### ISSUE TITLE
Odd HTTP errors with Sonarr

### ISSUE THREAD

**Issue by Rikumo1978** [Sonarr/Sonarr#1899]
Something really odd is happening with my Sonarr installation. Pretty sure it has nothing to do with me but I thought I'd check with the experts! Using latest version on Ubuntu 16.04 build. Ran great until today, seems to be getting these HTTP errors. Here is an example from my log. Every time it searches for a new TV Show or a new Episode of a Show I already have, or even just refreshing a TV show this is what I get:

HTTP Error - Res: [GET] http://services.sonarr.tv/v1/update/master?version=2.0.0.4689&os=linux&runtimeVer=4.8.1: 522.522
<!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>
<meta http-equiv="refresh" content="0">
<meta http-equiv="set-cookie" content="cf_use_ob=80; expires=Thu, 04-May-17 20:41:34 GMT; path=/">
<meta http-equiv="set-cookie" content="cf_ob_info=522:359e469e013e09fa:ATL; expires=Thu, 04-May-17 20:41:34 GMT; path=/">
<title>services.sonarr.tv | 522: Connection timed out</title>
<meta charset="UTF-8"/>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"/>
<meta name="robots" content="noindex, nofollow"/>
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"/>
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection"/>

<style type="text/css">body{margin:0;padding:0}</style>

<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>
</head>
<body>
<div id="cf-wrapper">
<div id="cf-error-details" class="cf-error-details-wrapper">
<div class="cf-wrapper cf-error-overview">
<h1>
<span class="cf-error-type" data-translate="error">Error</span>
<span class="cf-error-code">522</span>
<small class="heading-ray-id">Ray ID: 359e469e013e09fa &bull; 2017-05-04 20:41:04 UTC</small>
</h1>
<h2 class="cf-subheadline" data-translate="error_desc">Connection timed out</h2>
</div> 
<div class="cf-section cf-highlight cf-status-display">
<div class="cf-wrapper">
<div class="cf-columns cols-3">
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-browser"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc" data-translate="browser_desc">You</span>
<h3 class="cf-status-name" data-translate="browser_label">Browser</h3>
<span class="cf-status-label" data-translate="browser_status_label">Working</span>
</div>
<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-cloud"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc" data-translate="cloud_desc">Atlanta</span>
<h3 class="cf-status-name" data-translate="cloud_label">Cloudflare</h3>
<span class="cf-status-label" data-translate="cloud_status_label">Working</span>
</div>
<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-server"></i>
<i class="cf-icon-status cf-icon-error"></i>
</div>
<span class="cf-status-desc" data-translate="server_desc">services.sonarr.tv</span>
<h3 class="cf-status-name" data-translate="server_label">Host</h3>
<span class="cf-status-label" data-translate="server_status_label">Error</span>
</div>
</div>
</div>
</div> 
<div class="cf-section cf-wrapper">
<div class="cf-columns two">
<div class="cf-column">
<h2 data-translate="what_happened">What happened?</h2>
<p data-translate="connection_timed_out">The initial connection between Cloudflare's network and the origin web server timed out. As a result, the web page can not be displayed.</p>
</div>
<div class="cf-column">
<h2 data-translate="what_can_i_do">What can I do?</h2>
<h5 data-translate="if_website_visitor">If you're a visitor of this website:</h5>
<p data-translate="try_again_in_a_few">Please try again in a few minutes.</p>
<h5 data-translate="if_website_owner">If you're the owner of this website:</h5>
<p><span data-translate="522_owner_desc">Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources.</span> <a href="https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522" data-translate="addtl_troubleshooting">Additional troubleshooting information here.</a></p>
</div>
</div>
</div> 
<div class="cf-error-footer cf-wrapper">
<p>
<span class="cf-footer-item">Cloudflare Ray ID: <strong>359e469e013e09fa</strong></span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 162.213.237.29</span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
</p>
</div> 
</div> 
</div>

**Comment by Taloth** [comment]
Yup, we know, it's only happening to the Atlanta cloudflare datacenter, been happening for the last +12h.

**Comment by Taloth** [comment]
Our synthetics say the error got fixed just over 23min ago. :smile:

**Comment by DejaVu** [comment]
Trying to add my TV Shows to Sonarr, but this seems to happening again. 
Is the CloudFlare server having problems again?
