### ISSUE TITLE
Download client keeps failing to connect

### ISSUE THREAD

**Issue by edraven** [Sonarr/Sonarr#1901]
Apparently randomly, the download client of SABNZBd won't connect until I modify the host. 

eg. in Settings > Download Clients > Sabnzbd SSL > Host, if it's set to 127.0.0.1, I'll have to change it to localhost, or vice versa to get it to connect again. I've been doing this every few days for months, it persists across reboots and updates of Sonarr and Sabnzbd.

**Comment by markus101** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)
Please open a thread on the forums with the requested information including debug logs and we can troubleshoot this further.
