### ISSUE TITLE
Improve Manual Import UX

### ISSUE THREAD

**Issue by Webreaper** [Sonarr/Sonarr#1904]
Enhancement: When manually importing, the user needs to click on the episode row in the grid, under the 'Series' and 'Episode' columns, to select the series and episode. However, there's no UI clues that you need to do this - the column entries are just blank. As a n00b user, I clicked around for a while (clicking the episode title several times) before I realised exactly where to click to specify the series and title. 

Would make sense to have a 'Click to Select' indicator in each column for fields which need to be set for the import to succeed, just as a visual clue. :)

**Comment by markus101** [comment]
This is already addressed in the v3 UI work.

**Comment by Webreaper** [comment]
Awesome, thanks.
