### ISSUE TITLE
MediaInfo Library could not be loaded libmediainfo.so.0

### ISSUE THREAD

**Issue by Trouble-51** [Sonarr/Sonarr#1905]
I am using a QNAP TS-253 Pro. Sonarr continuously gives the following warning: MediaInfo Library could not be loaded libmediainfo.so.0. Wiki doesn't mention the problem. The file does exist:

[/share/CACHEDEV1_DATA/.qpkg/QSonarr/NzbDrone] # ls
CookComputing.XmlRpcV2.dll             Microsoft.AspNet.SignalR.Core.dll      NzbDrone.Host.dll.mdb
CurlSharp.dll                          Microsoft.AspNet.SignalR.Core.dll.mdb  NzbDrone.Mono.dll
CurlSharp.dll.config                   Microsoft.AspNet.SignalR.Owin.dll      NzbDrone.Mono.dll.mdb
CurlSharp.dll.mdb                      Microsoft.AspNet.SignalR.Owin.dll.mdb  NzbDrone.SignalR.dll
FluentMigrator.Runner.dll              Microsoft.Owin.Host.HttpListener.dll   NzbDrone.SignalR.dll.mdb
FluentMigrator.Runner.dll.mdb          Microsoft.Owin.Hosting.dll             NzbDrone.exe
FluentMigrator.dll                     Microsoft.Owin.dll                     NzbDrone.exe.config
FluentMigrator.dll.mdb                 MonoTorrent.dll                        NzbDrone.exe.mdb
FluentValidation.dll                   MonoTorrent.dll.mdb                    OAuth.dll
FluentValidation.dll.mdb               NLog.dll                               OAuth.dll.mdb
Growl.Connector.dll                    Nancy.Authentication.Basic.dll         Org.Mentalis.dll
Growl.CoreLibrary.dll                  Nancy.Authentication.Forms.dll         Owin.dll
ICSharpCode.SharpZipLib.dll            Nancy.Owin.dll                         Prowlin.dll
Ical.Net.Collections.dll               Nancy.dll                              RestSharp.dll
Ical.Net.Collections.dll.mdb           Newtonsoft.Json.dll                    SharpRaven.dll
Ical.Net.dll                           NodaTime.dll                           SharpRaven.dll.mdb
Ical.Net.dll.mdb                       NzbDrone.Api.dll                       SocksWebProxy.dll
ImageResizer.dll                       NzbDrone.Api.dll.mdb                   System.Data.SQLite.dll
LogentriesCore.dll                     NzbDrone.Common.dll                    System.Data.SQLite.xml
LogentriesCore.dll.mdb                 NzbDrone.Common.dll.mdb                UI/
LogentriesNLog.dll                     NzbDrone.Core.dll                      antlr.runtime.dll
LogentriesNLog.dll.mdb                 NzbDrone.Core.dll.config               antlr.runtime.dll.mdb
Marr.Data.dll                          NzbDrone.Core.dll.mdb                  libmediainfo.so.0@
Marr.Data.dll.mdb                      NzbDrone.Host.dll                      libmediainfo.so.0.so@

the two libmediainfo files are shown in blue

any help to solve this issue would be very much appreciated

**Comment by Taloth** [comment]
We don't provide the QSonarr package, that's done by some people over at the qnap forum. So you should check there for assistance.

**Comment by markus101** [comment]
Please open a thread on the forums for support.

`ls -l` (which includes the permissions would be better), though I'm not sure what `@` means at the end of the file name, but those don't look like the same filename since Sonarr is looking for `libmediainfo.so.0` not `libmediainfo.so.0@`.
