### ISSUE TITLE
Sonarr doesn't see mapped drives in Windows

### ISSUE THREAD

**Issue by voltagex** [Sonarr/Sonarr#1908]
I mapped a SMB share to a drive letter in Windows but Sonarr doesn't provide it as an option when adding show paths.

![image](https://cloud.githubusercontent.com/assets/159567/25769842/bb2be448-3267-11e7-804d-036d32938fd2.png)

**Comment by markus101** [comment]
Please use the forums for support. This particular question is covered in the [FAQ](https://github.com/Sonarr/Sonarr/wiki/FAQ).
