### ISSUE TITLE
Feature Request: Episode specific folders

### ISSUE THREAD

**Issue by jeliasson** [Sonarr/Sonarr#1909]
Hi all,

'Episode Naming' allows us to template the seasons folders and file episode format. However; I'm missing the capability to place the episode files in it's own folder, e.g. using the same file name, allowing us to store the episode (and subtitles, nfo, etc) in the same directory.

**Example**
File Name: Series.S01E01.HDTV.720p.XXX.mkv
Output File: <Series>/Season 1/Series.S01E01.HDTV.720p.XXX/Series.S01E01.HDTV.720p.XXX.mkv

Thanks!

**Comment by Taloth** [comment]
Well, just include a directory in your file naming pattern ;)
