### ISSUE TITLE
Cards in connect settings overview show on upgrade enabled when on download is disabled

### ISSUE THREAD

**Issue by kyse** [Sonarr/Sonarr#1911]
When disabling settings for push bullet, specifically the on download setting the form has on upgrade disappear. However when you go back to the connect overview page the card for that push bullet instance still shows on upgrade as enabled.

**Comment by Taloth** [comment]
Cosmetic, probably dealt with in v3. @markus101 ?

**Comment by markus101** [comment]
Yup, resolved in v3.
