### ISSUE TITLE
New series name same as old series

### ISSUE THREAD

**Issue by jpborjas** [Sonarr/Sonarr#1914]
There's a new show on National Geographic called Genius, but since there was one show with that name already in The TVDB (83714), they added it as "Genius (2017)" (322399). Now Sonarr is not finding Genius (2017) S01E0X, because on nzbplanet, for instance, is missing the (2017) part. 

Is there a way that I can do something about it, other than download it and manually renaming it, etc?

![screen shot 2017-05-09 at 8 55 09 pm](https://cloud.githubusercontent.com/assets/14253583/25878597/e6e6258c-34f9-11e7-918e-fd4a5617d76d.png)

**Comment by markus101** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

This belongs on the forums and already been covered: https://forums.sonarr.tv/t/tv-show-genius-2017-not-downloading/14664
