### ISSUE TITLE
UI Series Filter/Search Box autocomplete does not handle accents properly

### ISSUE THREAD

**Issue by Webreaper** [Sonarr/Sonarr#1915]
I've got a series called Bake Off Crème De La Crème in my series list, but the accents aren't being processed correctly. So for example, if I type "creme" in the 'Search for series in your library' box, I get no results ("bake" works fine). It's not really convenient to have to find the right unicode character to type in to search. Also, this is breaking the episode scan when looking for releases. Here's the output from the RSS feed scan - the release is rejected as being unknown.

`17-5-5 07:06:50.1|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series`
`17-5-5 07:06:50.1|Debug|Parser|Parsing string 'Bake Off Creme de la Creme S02E05 (2 May 2017) 720HD mp4'`
`17-5-5 07:06:50.1|Debug|Parser|Episode Parsed. Bake Off Creme de la Creme - S02E05 `
`17-5-5 07:06:50.1|Debug|Parser|Language parsed: English`
`17-5-5 07:06:50.1|Debug|QualityParser|Trying to parse quality for Bake Off Creme de la Creme S02E05 (2 May 2017) 720HD mp4`
`17-5-5 07:06:50.1|Debug|Parser|Quality parsed: Unknown v1`
`17-5-5 07:06:50.1|Debug|Parser|Release Group parsed: `
`17-5-5 07:06:50.1|Debug|AcceptableSizeSpecification|Beginning size check for: Bake Off Creme de la Creme S02E05 (2 May 2017) 720HD mp4`
`17-5-5 07:06:50.1|Debug|AcceptableSizeSpecification|Item: Bake Off Creme de la Creme S02E05 (2 May 2017) 720HD mp4, meets size constraints.`
`17-5-5 07:06:50.2|Debug|LanguageSpecification|Checking if report meets language requirements. English`
`17-5-5 07:06:50.2|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Bake Off Creme de la Creme S02E05 (2 May 2017) 720HD mp4`
`17-5-5 07:06:50.2|Debug|ReleaseRestrictionsSpecification|[Bake Off Creme de la Creme S02E05 (2 May 2017) 720HD mp4] No restrictions apply, allowing`

Would it make sense to always try with the non-accented characters first (i.e., replacing 'è' with 'e' and so on) so that the GUI search works intuitively, and more releases are picked up?

**Comment by Webreaper** [comment]
Interestingly, when I added it manually to Download Station and the download completed, Sonarr automatically imported it from the Drone Factory folder without me needing to do anything. So clearly there's _some_ accented character translation going on somewhere!

**Comment by Grimeton** [comment]
You sure you did everything right? When I run this:
```
perl -MNCDR::API::Sonarr::Client -MData::Dumper -e 'print Dumper(NCDR::API::Sonarr::Client->new()->seriesLookup->get("bake off creme de la creme"));'
```

It returns the correct series:

```
          {
            'seriesType' => 'standard',
            'qualityProfileId' => 0,
            'cleanTitle' => 'bakeoffcremedelacreme',
            'remotePoster' => 'http://thetvdb.com/banners/posters/309614-1.jpg',
            'year' => 2016,
            'added' => '0001-01-01T00:00:00Z',
            'tvdbId' => 309614,
            'images' => [
                          {
                            'coverType' => 'fanart',
                            'url' => 'http://thetvdb.com/banners/fanart/original/309614-2.jpg'
                          },
                          {
                            'coverType' => 'banner',
                            'url' => 'http://thetvdb.com/banners/text/309614.jpg'
                          },
                          {
                            'coverType' => 'poster',
                            'url' => 'http://thetvdb.com/banners/posters/309614-1.jpg'
                          }
                        ],
            'profileId' => 0,
            'airTime' => '20:00',
            'tags' => [],
            'overview' => 'Celebrated chef Tom Kerridge hosts the search for Britain\'s best team of pastry chefs. The teams must create elaborate patisserie and desserts for judges Benoit Blin, Claire Clark and Cherish Finden.',
            'seasonFolder' => bless( do{\(my $o = 0)}, 'JSON::PP::Boolean' ),
            'tvRageId' => 0,
            'monitored' => bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' ),
            'seasonCount' => 2,
            'tvMazeId' => 14710,
            'network' => 'BBC Two',
            'seasons' => [
                           {
                             'monitored' => $VAR1->[0]{'monitored'},
                             'seasonNumber' => 1
                           },
                           {
                             'seasonNumber' => 2,
                             'monitored' => $VAR1->[0]{'monitored'}
                           }
                         ],
                         ],
            'runtime' => 60,
            'ratings' => {
                           'value' => '10',
                           'votes' => 1
                         },
            'sortTitle' => "bake off cr\x{c3}\x{a8}me de la cr\x{c3}\x{a8}me",
            'imdbId' => 'tt5622304',
            'title' => "Bake Off Cr\x{c3}\x{a8}me de la Cr\x{c3}\x{a8}me",
            'genres' => [
                          'Food',
                          'Special Interest'
                        ],
            'firstAired' => '2016-03-28T22:00:00Z',
            'status' => 'continuing',
            'useSceneNumbering' => $VAR1->[0]{'seasonFolder'},
            'titleSlug' => 'bake-off-creme-de-la-creme'
          }
        ];
```

The WTF8 characters are shown as code points as this is just a dump. But as you can see there are multiple titles in the returned information. Have a look at "cleanTitle". 

So the API works quite well...

Cu

**Comment by Taloth** [comment]
> Episode Parsed. Bake Off Creme de la Creme - S02E05
> Quality parsed: Unknown v1

It's not being rejected as unknown, it's saying the quality is unknown.
Also, that's about rss / search, not about the library query box.

**Bug details**:
![image](https://cloud.githubusercontent.com/assets/6383890/25933002/f8335366-3614-11e7-8fce-55118e03a1a8.png)
Typing 'Creme' yields no results.

**Comment by Webreaper** [comment]
**Taloth**: I'm only going by the logs, and 

> 17-5-5 07:06:50.1|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series

Seems to agree with what I'm saying - but perhaps that log message is ambiguous. Also, I have 'unknown' in my 'Any' profile, and this series is set up for 'Any' - and other series with unknown qualities are being pulled in from the same RSS feed quite happily.

I wasn't sure if the logic was connected or not - I haven't looked at the code yet. 

**Grimeton**: I think you're doing an 'Add Series' search, and yes, in that case searching for 'creme' works (that's how I added the series). The problem here is matching the series from within an RSS search from my tracker, where the RSS search returns 'Crème'.

**Comment by Grimeton** [comment]
Hi,

ah I got that wrong. Sorry about that.

Cu

**Comment by Taloth** [comment]
@Webreaper That logline is at the start of the log you posted and thus doesn't show which release it applies to. It doesn't mention the series. And thus is no evidence at all. That's the problem with truncated logs.

I also prefer that you post that particular problem on the forums. I'll keep this issue for the UI search box only.

**Comment by Taloth** [comment]
The confusion is understandable, given that the timestamps are all the same.

PS: Unknown = Unknown v1 (v1 = normal release, v2 = Proper)
In all likeliness you have a different profile configured for that series. The episode is also not monitored according to that rejection.

**Comment by Webreaper** [comment]
Yeah, I should have scrolled up to see the other timestamps. 

Series/ep is monitored and profile definitely is 'Any' which has 'Unknown' so not sure what's going on. Will see if it works for next week's episode and if not ping the forum. Thanks for the help - and at least one part of the bug was valid. ;)

**Comment by Taloth** [comment]
> profile definitely is 'Any' which has 'Unknown'

Not by default. It isn't selected:
![image](https://cloud.githubusercontent.com/assets/6383890/25957831/7bff3ef8-366f-11e7-92a3-8f12282f3a89.png)

**Comment by Webreaper** [comment]
Sure. I checked it for 'any' when I set up Sonarr a couple of weeks ago, and then applied 'any' to all the series I'd imported.
