### ISSUE TITLE
Alternate names for anime

### ISSUE THREAD

**Issue by Kevenin** [Sonarr/Sonarr#1921]
Some anime series have a different name than what is shown in TVDB (example: Gin no Guardian on HorribleSubs and The silver Guardian in TVDB)

Would it be possible to add an alternate name to a series so that the indexers search with the alternate names if nothing is found with the normal name.

Thanks

**Comment by markus101** [comment]
https://forums.sonarr.tv/t/scene-naming-tvdb-naming-conflicts/137

For anime Sonarr relies on thexem.de to add alternate names (which they add fairly quickly).
