### ISSUE TITLE
Search broken on Nyaa.si

### ISSUE THREAD

**Issue by supremacy2k** [Sonarr/Sonarr#1923]
Using the nyaa.se indexer and changing the address to nyaa.si and Additional Parameters, it seems to return all the latest torrents, regardless of search criteria.

**Comment by markus101** [comment]
Does the nyaa.si support those search parameters? Debug Logs will show the URL Sonarr is using to query nyaa.

**Comment by gamesbe** [comment]
How did you change the additional parameters? Even with the url change I still see it trying to use the old stuff: https://nyaa.si/?page=rss&cats=1_37&filter=1&term=Little+Witch+Academia+19 for example.

**Comment by gamesbe** [comment]
After doing some testing around, the log shows https://nyaa.si/?page=rss&f=2&c=1_2&term=Little+Witch+Academia+19 which would just pull everything form the rss feed. 

The correct feed is https://nyaa.si/?page=rss&f=2&c=1_2&q=Little+Witch+Academia+19

No idea if that is possible fixing in the sonarr files.

**Comment by schindlershadow** [comment]
Also does not get the correct seeder/leachers and size numbers. everything is 0

**Comment by Taloth** [comment]
Dupe https://github.com/Sonarr/Sonarr/issues/1890
