### ISSUE TITLE
Calendar showing wrong release date and time

### ISSUE THREAD

**Issue by QT31416** [Sonarr/Sonarr#1924]
I reinstalled windows and all my programs yesterday. Sonarr used to show correct date and time for the shows' releases, it really worked amazingly!

After reinstalling sonarr, the calendar now shows wrong release date and time for tv shows. My computer location is set to where I live, so is computer timezone.

Attached is my week's releases. For example, Genius should release on Tuesday, May 16, but the calendar shows it aired 1:00pm earlier today.

Any ideas on how to correct the date and time? Thanks!

![sonarr wrong date time](https://cloud.githubusercontent.com/assets/26166095/26033353/576f0edc-385f-11e7-906c-942ef4664391.png)

O btw, Sonarr is updated.
![sonarr updated](https://cloud.githubusercontent.com/assets/26166095/26033390/2d7614b2-3860-11e7-9993-51fdf6914c4e.png)

**Comment by QT31416** [comment]
Oh, it seems the problem went away after manually setting my location to some incorrect location, then readjusting my location automatically via internet, then finally restarting Sonarr.

![sonarr correct date time](https://cloud.githubusercontent.com/assets/26166095/26033449/7792eff6-3861-11e7-8057-bd749cc15f56.png)

**Comment by markus101** [comment]
Times shown in the browser are based of the client's time/timezone, all times are sent from Sonarr to the browser as UTC times (ISO-8601 formatted to be exact). The time shown on the calendar are local to you, not the time it airs on the network in question in network's local timezone.

As long as the dates coming from TheTVDB are correct they are translated to UTC by our TVDB proxy (using the date, air time and UTC offset of the network).

Next time please use the forums for support related inquiries.
