### ISSUE TITLE
After last update, Sonarr won't startup - Cannot open assembly 'NzbDrone.exe': No such file or directory.

### ISSUE THREAD

**Issue by meoz** [Sonarr/Sonarr#1925]
After installing the last update v2.0.0.4753 on Synology Docker, Sonarr won't startup. Did not change anything except installing the update from withing Sonarr gui. 
Looking at the terminal this message keeps popping up: "Cannot open assembly 'NzbDrone.exe': No such file or directory."

**Comment by Grimeton** [comment]
Yeah that went wrong. Just recreate the container and be happy again.
Without logs of the update process we can't do anything about it so at least a log file would be nice.

**Comment by markus101** [comment]
Please open a thread on the forums for support.

Update logs will be helpful to see what the result of the update process was. You could extract `http://download.sonarr.tv/v2/master/latest/NzbDrone.master.tar.gz` to the location where NzbDrone.exe should be on the synology (not sure where there is offhand) as well. If you opt to reinstall the Sonarr plugin on Synology, make sure you backup _before_ removing the plugin (though backing up in any case would be a good idea).
