### ISSUE TITLE
Switching a show type does not change how the show is searched newznab indexers

### ISSUE THREAD

**Issue by alzeebum** [Sonarr/Sonarr#1927]
Changing a show between standard and anime does not change how sonarr searches for episodes, according to the debug log.  You have to remove the show from sonarr and then add it back in as the other type.  Tested this by changing an "anime" tagged series to "standard", then searching for a missing episode.  The API was still searched for the absolute episode number, not the season+episode number.

Ideally though, anime series should just issue both types of searches to the indexer(s).  Often anime series episodes are not tagged with absolute numbers anyway.

EDIT: Changing the type does not fix the issue after all.  There needs to be a flag/advanced setting somewhere in sonarr to override how it "thinks" a series should be searched for, regardless of what the tvdb or whatever says the format should be.

A test case for nzbgeek is Bleach, Episode 332 (season 15, episode 16).  Presently Sonarr can only find one nzb result for it's search in "anime" mode for "bleach+332", and it cannot parse the result.  It gets no results in "normal" mode, searching for "bleach+s01e332".  What it should (obviously) be doing is searching for "bleach+s01e16" which does work just fine.

**Comment by markus101** [comment]
> Changing a show between standard and anime does not change how sonarr searches for episodes, according to the debug log.

I'm seeing the categories search change (it searches the anime categories when the series type is set to `anime` otherwise it searches the "categories" set on the indexer in Sonarr (it's an advanced setting).

> Ideally though, anime series should just issue both types of searches to the indexer(s). Often anime series episodes are not tagged with absolute numbers anyway.

It depends on the indexer/series, but most are numbered absolutely, but for the most part it's not likely worth the extra load on the indexers with extra API calls.

> There needs to be a flag/advanced setting somewhere in sonarr to override how it "thinks" a series should be searched for, regardless of what the tvdb or whatever says the format should be.

Whatever you select in Sonarr decides how it's searched, an advanced setting to tweak that is not something we plan to implement.

Make sure your categories are setup properly in the NZBGeek indexer settings within Sonarr and that nzbgeek has things in the correct categories as it sounds like one end or the other is wrong.

**Comment by alzeebum** [comment]
I have my categories set correctly, and they do change when you change the series type.  What does not change is the episode # that sonarr searches for.  In my example, add Bleach as an existing anime series and then delete a high-numbered episode, S15E16 (absolute episode 332) in my example.  Search for it, the query goes out as "Bleach+332".  Now change the series type to standard and search again.  The categories change, but the episode in search does *not*.  It searches for Bleach, Season 15, Episode 332 (instead of episode 16).

It seems the only way to "fix" this for an end user is to delete the series from sonarr and add it back in as the other type.

**Comment by alzeebum** [comment]
I have to correct my previous comment, it's worse than I had stated.  Even removing and adding the series as "standard" does not address the issue.  When I navigate to Season 15 in the UI and click manual search on Episode 16, the log states:

"17-5-15 03:48:09.1|Info|NzbSearchService|Searching 1 indexers for [Bleach : S01E332]"

This is obviously incorrect.

**Comment by markus101** [comment]
This appears to be an oddity with the xem mapping for this series.

http://thexem.de/xem/show/771

For some reason the anidb <-> TVDB mapping is being pulled down and overriding the TVDB's episode number (which is normal when there is a scene <> TVDB mapping). You can see the effect of this mapping by hovering over the episode number on the series details page.

I've mentioned it to the admins of thexem.de on IRC, not sure what they'll need to do to correct it, but I don't believe there is anything in Sonarr that needs to change.

**Comment by alzeebum** [comment]
I see.

Regardless, it would certainly be nice if there were some way for us to simply override whatever it is that thetvdb, thexem, etc etc etc believe the search query should be and just enter it ourselves.

Since we are at sonarr's mercy in when and how to use such mapping, and cannot override or alter the behavior (without hacking on the source), pointing fingers elsewhere doesn't really help "us" (the end users).

**Comment by alzeebum** [comment]
FYI this is happening with another series (Fairy Tail) as well.  I'm reporting it to you, even though it's probably another thexem problem, since sonarr is the "product" I'm using.  I'd happily disable thexem integration if I could, I hadn't even heard of it before this issue.
