### ISSUE TITLE
New Feature: Audio quality

### ISSUE THREAD

**Issue by tiagoboldt** [Sonarr/Sonarr#1930]
Sonarr enables an easy selection of the video quality. But for the same video quality, there are usually multiple audio qualities: DTS, DD, AC3, MP3, etc. 

It would be useful if the audio quality was also selectable.

**Comment by markus101** [comment]
Audio language is less consistent in the file names, we don't plan to support it as a selectable quality like the video quality, but support it via preferred words:

https://github.com/Sonarr/Sonarr/issues/385
