### ISSUE TITLE
Replace Nyaa.se with Nyaa.si

### ISSUE THREAD

**Issue by boomshadow** [Sonarr/Sonarr#1931]
Sadly, Nyaa.se was shut down on May 1st. The community gathered together and recovered most of the torrents from the Nyaa.se database. Everything has been moved to a new site: Nyaa.si.

It would be nice to have Sonarr work with the new Syaa.si to have Indexer with Search.

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/1890 and https://github.com/Sonarr/Sonarr/issues/1923
