### ISSUE TITLE
No files found are eligible for import

### ISSUE THREAD

**Issue by francesco2013** [Sonarr/Sonarr#1935]
I keep on getting this a lot very annoying

Doctor.Who.2005.S07E02.Dinosaurs.on.a.Spaceship.720p.BluRay.2xRus.Eng.HDCLUB
No files found are eligible for import in /mnt/diskb/Usenet_Complete/Doctor.Who.2005.S07E02.Dinosaurs.on.a.Spaceship.720p.BluRay.2xRus.Eng.HDCLUB

**Comment by markus101** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please open a thread on the forums for support including debug logs.
