### ISSUE TITLE
Add "Manual Import" button on the TV show page

### ISSUE THREAD

**Issue by gjannece** [Sonarr/Sonarr#1941]
I suggest adding a "Manual Import" option on for each TV show page. When I am viewing a TV show page, and I click on the "Manual Import" button, I can assume that I want to manually import files for that show. Doing this can save time when importing files that the parser sees as unknown.

**Comment by markus101** [comment]
A manual import button has been added to the series details page in the v3 work, which points to the series' files (with the option to show all files for the series, not just unlinked ones).
