### ISSUE TITLE
More options for Slack connection

### ISSUE THREAD

**Issue by ameswarb** [Sonarr/Sonarr#1942]
Could we add a few customization options to the Slack integration? Good ones would be a checkbox + dropdown to only emit notifications on download of a show that's recently aired within the last x weeks, or an option to throttle / debounce notifications, batching notifications together within a set time window.

I currently run a custom script that does this for me with Slack webhooks, but I'm guessing that a lot of users might appreciate having some of these features canonized as options for the Slack connection in the mainline Sonarr distribution.

**Comment by markus101** [comment]
Covered by:

https://github.com/Sonarr/Sonarr/issues/407
https://github.com/Sonarr/Sonarr/issues/363

Which would apply to all notifications, not just one specific channel.
