### ISSUE TITLE
Problem with "Form" Auth Login? (Cannot login)

### ISSUE THREAD

**Issue by SCRPD** [Sonarr/Sonarr#1944]
I tried logging into my Sonarr installation today through my reverse proxy url an upon filling in the User & Pass it would just reload the login form page & not let me enter the WebGUI (Started to think maybe my login got compromised).

I changed the auth to "none" in the config & got back into the GUI. Reset the password/auth settings & restarted.

Now I get the same problem but not on my reverse proxy URL but on my localhost URL.

I tried clearing all cookies & ect but it didn't work.

I've never had this problem before. If I can provide anything that can help let me know.

EDIT: I could only get the localhost url & reverse proxy to start working again together by switching to basic login. I think Forms login for non reverse proxy urls might be broken by sending the url http://localhost:38082/sonarr/login?returnUrl=/ instead of http://localhost:38082/sonarr/login?returnUrl=/sonarr/. I'm not sure on this, it's just speculation.

Nginx Config:
```
location /sonarr {
	proxy_pass http://127.0.0.1:38082;
	proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header        Host            $host;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_redirect off;
	}
```

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
Related to: https://github.com/Sonarr/Sonarr/issues/1934 ?

We'll need to see some debug logs.

**Comment by SCRPD** [comment]
Might be, I also got that error when fixing the password problem but restarting Sonarr process fixed it for me.

What I just noticed when I click the Sonarr shortcut on my desktop it brings me to http://localhost:38082/sonarr/login?returnUrl=/

Shouldn't it be loading http://localhost:38082/sonarr/login?returnUrl=/sonarr/ from the desktop shortcut? If I change the URL to something like http://localhost:38082/sonarr/ after trying to login it shows I'm already logged in, but going to http://localhost:38082 sends me to http://localhost:38082/sonarr/login?returnUrl=/.

Some stuff from debug logs:
```
17-5-25 11:50:08.6|Debug|ProcessProvider|Found 0 processes with the name: NzbDrone.Console
17-5-25 11:50:08.6|Debug|ProcessProvider|Found 2 processes with the name: NzbDrone
17-5-25 11:50:08.6|Debug|ProcessProvider| - [6940] NzbDrone
17-5-25 11:50:08.6|Debug|ProcessProvider| - [2416] NzbDrone
17-5-25 11:50:08.6|Info|SingleInstancePolicy|1 instance(s) of Sonarr are running
17-5-25 11:50:08.6|Warn|SingleInstancePolicy|Another instance of Sonarr is already running.
17-5-25 11:50:08.6|Info|BrowserService|Starting default browser. http://localhost:38082
17-5-25 11:50:08.6|Info|ProcessProvider|Opening URL [http://localhost:38082]
17-5-25 11:50:08.6|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running
17-5-25 11:50:21.2|Debug|Api|[GET] /api/config/ui: 200.OK (3 ms)
17-5-25 11:50:21.3|Debug|Api|[GET] /api/system/status: 200.OK (5 ms)
17-5-25 11:50:21.3|Debug|Api|[GET] /api/health: 200.OK (3 ms)
17-5-25 11:50:21.3|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (10 ms)
17-5-25 11:50:21.3|Debug|Api|[GET] /api/profile: 200.OK (13 ms)
17-5-25 11:50:21.5|Debug|Api|[GET] /api/series: 200.OK (212 ms)
17-5-25 11:50:21.6|Debug|Api|[GET] /api/command: 200.OK (2 ms)
17-5-25 11:50:21.6|Debug|Api|[GET] /api/language: 200.OK (3 ms)
17-5-25 11:50:21.6|Debug|Api|[GET] /api/tag: 200.OK (5 ms)
17-5-25 11:50:21.6|Debug|Api|[GET] /api/health: 200.OK (3 ms)
17-5-25 11:50:21.7|Debug|Api|[GET] /api/health: 200.OK (4 ms)
17-5-25 11:50:21.7|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (6 ms)
17-5-25 11:50:21.7|Debug|Api|[GET] /api/diskspace: 200.OK (42 ms)
17-5-25 11:51:13.5|Debug|ProcessProvider|Found 0 processes with the name: NzbDrone.Console
17-5-25 11:51:13.5|Debug|ProcessProvider|Found 2 processes with the name: NzbDrone
17-5-25 11:51:13.5|Debug|ProcessProvider| - [2372] NzbDrone
17-5-25 11:51:13.5|Debug|ProcessProvider| - [6940] NzbDrone
17-5-25 11:51:13.6|Info|SingleInstancePolicy|1 instance(s) of Sonarr are running
17-5-25 11:51:13.6|Warn|SingleInstancePolicy|Another instance of Sonarr is already running.
17-5-25 11:51:13.6|Info|BrowserService|Starting default browser. http://localhost:38082
17-5-25 11:51:13.6|Info|ProcessProvider|Opening URL [http://localhost:38082]
17-5-25 11:51:13.6|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running
17-5-25 11:51:15.5|Debug|SabnzbdProxy|Url: http://localhost:38080/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
17-5-25 11:51:16.5|Debug|SabnzbdProxy|Url: http://localhost:38080/api?mode=history&start=0&limit=30&category=sonarr&apikey=(removed)&output=json
17-5-25 11:51:24.7|Debug|Api|[GET] /api/config/ui: 200.OK (3 ms)
17-5-25 11:51:24.7|Debug|Api|[GET] /api/system/status: 200.OK (5 ms)
17-5-25 11:51:24.8|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (8 ms)
17-5-25 11:51:24.8|Debug|Api|[GET] /api/health: 200.OK (4 ms)
17-5-25 11:51:24.8|Debug|Api|[GET] /api/profile: 200.OK (17 ms)
17-5-25 11:51:25.0|Debug|Api|[GET] /api/series: 200.OK (214 ms)
17-5-25 11:51:25.1|Debug|Api|[GET] /api/command: 200.OK (4 ms)
17-5-25 11:51:25.1|Debug|Api|[GET] /api/language: 200.OK (3 ms)
17-5-25 11:51:25.1|Debug|Api|[GET] /api/tag: 200.OK (6 ms)
17-5-25 11:51:25.3|Debug|Api|[GET] /api/health: 200.OK (5 ms)
17-5-25 11:51:25.3|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (8 ms)
17-5-25 11:51:25.5|Debug|Api|[GET] /api/series?sort_by=sortTitle&order=asc: 200.OK (228 ms)
17-5-25 11:52:44.5|Debug|SabnzbdProxy|Url: http://localhost:38080/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
17-5-25 11:52:44.5|Debug|SabnzbdProxy|Url: http://localhost:38080/api?mode=history&start=0&limit=30&category=sonarr&apikey=(removed)&output=json
17-5-25 11:52:44.5|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (15 ms)
17-5-25 11:53:20.3|Debug|Api|[GET] /api/health: 200.OK (4 ms)
17-5-25 11:53:20.4|Debug|Api|[GET] /api/health: 200.OK (11 ms)
17-5-25 11:53:20.4|Debug|Api|[GET] /api/diskspace: 200.OK (95 ms)
17-5-25 11:53:20.5|Debug|Api|[GET] /api/diskspace: 200.OK (38 ms)
17-5-25 11:53:21.7|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (13 ms)
17-5-25 11:53:21.7|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (9 ms)
17-5-25 11:53:22.6|Debug|Api|[GET] /api/log/file: 200.OK (4 ms)
17-5-25 11:53:22.6|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (8 ms)
```

**Comment by markus101** [comment]
I don't see nay login attempts there, were you already logged in?

It looks like if Sonarr opens the browser it won't include the `URL Base` so you get redirected back to the root after logging in (though that will work if it redirected you to the login page to begin with). This is something we can look at, though it's always been that way.

When you had the issue logging in was it only through the reverse proxy or always?

**Comment by SCRPD** [comment]
I logged out and in a few times. When I had the login problems this morning it was on both reverse proxy & localhost urls (type in user & pass and it would just refresh to the login form (I think it did sign in but just kept sending me back), I wasn't fully awake yet so I didn't think of trying different sonarr sub-directories on the reverse proxy url & went straight to AuthenticationMethod none). after AuthenticationMethod was set to none, restarted, new password set through setting I could login via reverse proxy no problem.

It's weird because I've never had the localhost problem with redirect with the form. This is the first time I've had the problem happen with reverse proxy too (I believe it was the same redirect problem as localhost but applied to reverse proxy url).

**Comment by markus101** [comment]
I think the localhost issue was likely due to where the cookie path is set when there is a URL Base set (which is a new change).

The reverse proxy failing as well I'm unsure of since your config doesn't seem to be changing the cookie path like in #1934. Disabling auth and resetting the password wouldn't clear any cookies, so I'm not sure how that fixed it. I'm not sure if there is anything actionable here since it's working now (although mysterious), unless you have logs from when it was failing (even info logs may show something).

**Comment by ChristopherHaws** [comment]
@markus101 I can confirm that I am having this issue as well. When I try to login, it keeps redirecting me back to `http://localhost/login?returnUrl=/`

I have cleared the cache and cookies in my browser, but the issue still happens. The error I get in my logs each time I click the login button is:
```
17-6-3 17:27:15.5|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.696] System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Api.Frontend.StaticResourceModule.Index() in C:\projects\radarr-usby1\src\NzbDrone.Api\Frontend\StaticResourceModule.cs:line 55
   at NzbDrone.Api.Frontend.StaticResourceModule.<.ctor>b__3_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Frontend\StaticResourceModule.cs:line 25
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by markus101** [comment]
If Sonarr isn't logging anything how do you know it's the same issue?
Do you have a `Url Base` set in Sonarr?

It'd be best to open a thread on the forums, so we can troubleshoot properly.

**Comment by ChristopherHaws** [comment]
I don't know for sure that it is the same issue, however it did start occurring at the same time for both apps, and it is the exact same behavior in both apps.

`Url Base` is empty. I am not using a reverse proxy to access sonarr.

What I am noticing is that it seems like this might be an an issue when logging in from multiple places. If I close all chrome instances, open a new one, login, it works. If I then open an incognito window and try to login it fails. When I close all windows again and open just and incognito window, I can login.

**Comment by markus101** [comment]
Have you tried another browser?
The fact that Sonarr and Radarr are doing it and they diverged such a long time ago is a little suspect.

The Radarr error above wouldn't prevent logging in, though it would prevent something from loading (depending what the request is).

**Comment by SCRPD** [comment]
I use radarr too & it didn't have my issue I had with sonarr. My sonarr problem has fixed itself somehow within like the last week or so.
