### ISSUE TITLE
When does Sonarr search for a new episode?

### ISSUE THREAD

**Issue by dzg** [Sonarr/Sonarr#1945]
E.g., "Fargo" aired 18 hours ago ... but I had to manually trigger a search to get latest episode.

What triggers a search for episode?

I am using Jackett and custom torznab links for my indexers.
(Latest version)

**Comment by markus101** [comment]
> What triggers a search for episode?

Nothing, Sonarr relies on RSS Sync for finding new episodes as explained in the [FAQ](https://github.com/Sonarr/Sonarr/wiki/FAQ).

There are lots of reasons why something wouldn't be grabbed when it was released, but we'd need debug logs to pinpoint why it failed. We use the forums for support though, so feel free to open a thread in the forums to troubleshoot further.
