### ISSUE TITLE
Issue with grabbing a specific Anime using private indexer

### ISSUE THREAD

**Issue by jtoaka** [Sonarr/Sonarr#1946]
Hi everyone,

So I've been having an issue with Sonarr grabbing 'Sailor Moon.' On Sonarr, I've listed it under Anime and selected the quality that will match the one's uploaded. I'm using a private indexer (BTN) and it's not grabbing what I select using Sonarr. It's able to grab Season 4 but not anything else. Any idea what the issue could be? For some reason, when i manually search for Season 1, it says "No results found." Here is the debug information for Sonarr:

> 17-5-26 07:17:06.9|Info|NzbSearchService|Searching 1 indexers for [Sailor Moon : 01]
> 17-5-26 07:17:06.9|Debug|BroadcastheNet|Downloading Feed http://api.broadcasthe.net/: getTorrents("(removed)", {"Category":"Episode","Name":"S01E01","Tvdb":"78500"}, 100, 0)
> 17-5-26 07:17:06.9|Debug|BroadcastheNet|Downloading Feed http://api.broadcasthe.net/: getTorrents("(removed)", {"Category":"Season","Name":"Season 1","Tvdb":"78500"}, 100, 0)
> 17-5-26 07:17:07.1|Debug|BackupService|Backup zip created
> 17-5-26 07:17:07.6|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (1 ms)
> 17-5-26 07:17:07.8|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (3 ms)
> 17-5-26 07:17:07.8|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (2 ms)
> 17-5-26 07:17:08.1|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (2 ms)
> 17-5-26 07:17:09.0|Debug|NzbSearchService|Total of 0 reports were found for [Sailor Moon : 01] from 1 indexers
> 17-5-26 07:17:09.0|Info|DownloadDecisionMaker|No results found
> 17-5-26 07:17:09.0|Debug|Api|[GET] /api/release?episodeId=4621&sort_by=releaseWeight&order=asc: 200.OK (2172 ms)

The weird part is if I search for Season 4, it finds the torrent that has been uploaded:

> 17-5-26 07:19:12.7|Info|NzbSearchService|Searching 1 indexers for [Sailor Moon : 02]
> 17-5-26 07:19:12.7|Debug|BroadcastheNet|Downloading Feed http://api.broadcasthe.net/: getTorrents("(removed)", {"Category":"Episode","Name":"S04E02","Tvdb":"78500"}, 100, 0)
> 17-5-26 07:19:12.8|Debug|BroadcastheNet|Downloading Feed http://api.broadcasthe.net/: getTorrents("(removed)", {"Category":"Season","Name":"Season 4","Tvdb":"78500"}, 100, 0)
> 17-5-26 07:19:14.8|Debug|NzbSearchService|Total of 1 reports were found for [Sailor Moon : 02] from 1 indexers
> 17-5-26 07:19:14.8|Info|DownloadDecisionMaker|Processing 1 releases
> 17-5-26 07:19:14.8|Debug|Parser|Parsing string 'Pretty.Soldier.Sailor.Moon.S04.480p.DVDRip.DD2.0.x264-Hi10P-SMC'
> 17-5-26 07:19:14.9|Debug|Parser|Episode Parsed. Pretty Soldier Sailor Moon - Season 04 
> 17-5-26 07:19:14.9|Debug|Parser|Language parsed: English
> 17-5-26 07:19:14.9|Debug|QualityParser|Trying to parse quality for Pretty.Soldier.Sailor.Moon.S04.480p.DVDRip.DD2.0.x264-Hi10P-SMC
> 17-5-26 07:19:14.9|Debug|Parser|Quality parsed: DVD v1
> 17-5-26 07:19:14.9|Debug|Parser|Release Group parsed: SMC
> 17-5-26 07:19:14.9|Debug|AcceptableSizeSpecification|Beginning size check for: Pretty.Soldier.Sailor.Moon.S04.480p.DVDRip.DD2.0.x264-Hi10P-SMC
> 17-5-26 07:19:14.9|Debug|AcceptableSizeSpecification|Max size is unlimited - skipping check.
> 17-5-26 07:19:14.9|Debug|AcceptableSizeSpecification|Item: Pretty.Soldier.Sailor.Moon.S04.480p.DVDRip.DD2.0.x264-Hi10P-SMC, meets size constraints.
> 17-5-26 07:19:14.9|Debug|FullSeasonSpecification|Checking if all episodes in full season release have aired. Pretty.Soldier.Sailor.Moon.S04.480p.DVDRip.DD2.0.x264-Hi10P-SMC
> 17-5-26 07:19:14.9|Debug|LanguageSpecification|Checking if report meets language requirements. English
> 17-5-26 07:19:14.9|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Pretty.Soldier.Sailor.Moon.S04.480p.DVDRip.DD2.0.x264-Hi10P-SMC
> 17-5-26 07:19:14.9|Debug|ReleaseRestrictionsSpecification|[Pretty.Soldier.Sailor.Moon.S04.480p.DVDRip.DD2.0.x264-Hi10P-SMC] No restrictions apply, allowing
> 17-5-26 07:19:14.9|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. DVD v1
> 17-5-26 07:19:14.9|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
> 17-5-26 07:19:14.9|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
> 17-5-26 07:19:14.9|Debug|SeriesSpecification|Checking if series matches searched series
> 17-5-26 07:19:14.9|Debug|DelaySpecification|Ignoring delay for user invoked search
> 17-5-26 07:19:14.9|Debug|HistorySpecification|Skipping history check during search
> 17-5-26 07:19:14.9|Debug|MonitoredEpisodeSpecification|Skipping monitored check during search
> 17-5-26 07:19:14.9|Debug|DownloadDecisionMaker|Release accepted
> 17-5-26 07:19:14.9|Debug|Api|[GET] /api/release?episodeId=4749&sort_by=releaseWeight&order=asc: 200.OK (2149 ms)

If I search for Seasons 1-3, 5 and the specials, I get the "No Results Found" error. I've tried changing the Series type from Anime to Standard and vice versa, different profiles but nothing has worked.

Is this an error with Sonarr or my end?

Thanks.

**Comment by markus101** [comment]
First off, please use the forums for support.

In this case BTN is not returning results, which is due to how the releases are named. If you look at season 4, there are two items, but Sonarr only gets one result back from BTN, the one labeled `Season 4`, but not the one labeled `Season 4 - Episodes 128-166`. Unfortunately as far as I can discern this search is an exact match for better or worse, so this isn't something we can improve on, unless @Taloth has any ideas.

**Comment by jtoaka** [comment]
Oh woops, sorry about that. Would you like me to close this and re-post in the forums? Didn't know to direct issues there.

**Comment by Taloth** [comment]
Fixed on next develop version.

![image](https://cloud.githubusercontent.com/assets/6383890/26497242/16121d82-422b-11e7-9302-72314e218424.png)
