### ISSUE TITLE
Feature Request: Manual Import Defaults

### ISSUE THREAD

**Issue by Quiksmage** [Sonarr/Sonarr#1949]
Hi,

Currently "manual import" defaults to move with no ability to change the default. I've found myself accidentally moving files when I'd like the default to be copy. That is obviously my fault, but Is there any way to change the default behavior currently?

If not, I'd like to request the ability to change the default selection for manual imports, either from a setting option, or from remembering the last selection used.

**Comment by markus101** [comment]
This is done as part of the v3 work.
