### ISSUE TITLE
Unable to connect to nzbgeek indexer over ssl on centos7

### ISSUE THREAD

**Issue by CaptainRedHat** [Sonarr/Sonarr#1950]
I noticed that I am unable to connect to my indexer over ssl recently. I use NZBgeek. When I try to add the indexer, it says "Unable to connect to indexer, check the log for more details"

Here's the log
https://pastebin.com/pnvfjYRJ

I'm running:
CentOS 7.3
Sonarr 2.0.0.4753
Mono mono-core-5.0.1.1-0.xamarin.3.epel7.x86_64

**Comment by thezoggy** [comment]
this is a mono 5 issue..  one sec

**Comment by markus101** [comment]
Also covered by: https://github.com/Sonarr/Sonarr/issues/1928

**Comment by jeremyforan** [comment]
edit /usr/lib/systemd/system/sonarr.service
and add under [Service] add
`Environment=MONO_TLS_PROVIDER=legacy`
Then reload the service
`systemctl daemon-reload`
`systemctl restart sonarr`

**Comment by CaptainRedHat** [comment]
Yeah, I've already had this fixed. The solution was in the link to #1928. Other folks may need to be aware that sonarr.service may also be in /etc/systemd/system/sonarr.service, depending on how they installed sonarr.
