### ISSUE TITLE
Wanted / Missing tab is empty, no new shows being added but Calendar has many missing

### ISSUE THREAD

**Issue by adamtopher** [Sonarr/Sonarr#1953]
Recently my Sonarr has stopped identifying missing episodes.  If I visit the Missing page and click on Missing there is nothing listed. If I go to the Calendar page then I see many Red Missing episodes and I can click through to the individual Series pages and do an automatic search.

I haven't changed any settings in the past 6 months, but just started happening in the past couple weeks.

I am running on Synology using Version 2.0.0.4753

![wanted](https://cloud.githubusercontent.com/assets/1127456/26662224/45143c0e-4637-11e7-8aa6-085aef2561ee.PNG)
![calendar](https://cloud.githubusercontent.com/assets/1127456/26662229/47c1699a-4637-11e7-8c82-96d187e4c818.PNG)

**Comment by markus101** [comment]
Please open a thread on the forums for support.

We'll need to see trace logs of the Wanted: Missing page being opened as well as the other requested information.
