### ISSUE TITLE
iTunesHD not treated as WEB-DL

### ISSUE THREAD

**Issue by AbGedreht** [Sonarr/Sonarr#1955]
I noticed that the tag "iTunesHD" is missing from the 720p WebHD quality profile.
The (german) RlsGrp "TVS" use it instead of WebHD therefore it won't show up at all in the list for matching releases.

**Comment by markus101** [comment]
Support for `iTunesHD` was added more than 2 years ago: https://github.com/Sonarr/Sonarr/commit/9d5d3ce4c333430c614367c762a28810d512c332
