### ISSUE TITLE
qBitTorrent 3.3.14 broken due to changed api

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#1956]
Looks like qbit added Origin: or Referer: header requirements on the api for 3.3.13: https://github.com/qbittorrent/qBittorrent/commit/087856d3d8d6d77881c3d8378a95d80d693af2dd

Needs to be verified first, and then we should probably just send out the Origin header as appropriate.

**Comment by Reaxer** [comment]
I just updated qbittorrent and got this issue. Anything I can do now, but wait for it to be fixed?

**Comment by baggar11** [comment]
@Reaxer 

I just ran into this too. wget https://launchpad.net/~qbittorrent-team/+archive/ubuntu/qbittorrent-stable/+build/12407433/+files/qbittorrent-nox_3.3.12-0ppa1~xenial_amd64.deb

Then dpki -i the deb and bump the service(or reboot).

**Comment by jeff15110168** [comment]
I just rolled back to 3.3.11 and won't update until it's fixed.

On Jun 12, 2017, at 6:19 PM, Reaxer <notifications@github.com<mailto:notifications@github.com>> wrote:


I just updated qbittorrent and got this issue. Anything I can do now, but wait for it to be fixed?

**Comment by Reaxer** [comment]
Thanks @baggar11 
Sorry for the troubleshooting here, 
I did that, but get dependancy errors, I only need libboost-system1.58.0, but I can't find it.
Furthermore i'm using 17.04 (zesty) and I can't find the version for that, it looks like it failed to build on launchpad or something?

Thanks for helping!

**Comment by kevinwlau** [comment]
Seems like this has been fixed and will make it to the next release of qBittorrent
https://github.com/qbittorrent/qBittorrent/pull/6887

**Comment by hitnrun30** [comment]
Any status on this.  I bet more and more torrent apps will be doing this in the future

**Comment by zSoulweaver** [comment]
qBittorrent has just released a new version which should relax the CSRF defence. Haven't tested yet but it should work.

**Comment by Taloth** [comment]
https://forums.sonarr.tv/t/qbittorrent-nzbdroneerrorpipeline/15402
