### ISSUE TITLE
Login Doesn't Work Without Deleting Cookie

### ISSUE THREAD

**Issue by kmlucy** [Sonarr/Sonarr#1962]
Recently, I have stopped being able to login to Sonarr without first deleting the ``_ncfa`` cookie. Without deleting it, after entering my login and password, the page just refreshes, but does not log me in.

I did not see anything relevant in my log files, but I can search them if there is something specific that you need.

**Comment by markus101** [comment]
Related:

https://github.com/Sonarr/Sonarr/issues/1934 - Behind a reverse proxy
https://github.com/Sonarr/Sonarr/issues/1944 - Seems to be related to a URL base and trying to login by hitting the base URL directly.

**Comment by kmlucy** [comment]
I turned on debug logging, and was watching the live logs while attempting to login, but there were no new entries.

In addition, I never had the ```proxy_cookie_path``` directive set in my nginx config. 

I am using both a reverse proxy and URL base.

Looking at the cookies, Sonarr appears to be setting a ```_ncfa``` cookie in both the root (```/```) and correct path (```/sonarr````). I need to delete the one in the root to be able to login.

**Comment by markus101** [comment]
Are the contents of both cookies the same?

When a URL base is set in Sonarr it won't write a cookie to `/`, unless the cookie existed from before the change, but then it'd be expired and wouldn't come back every login.

I know Radarr used to set the same cookie at `/` but they use a different cookie and also set it on the path in recent versions. If another fork of Sonarr (Lidarr for example) hasn't changed the cookie name that could cause this issue, but I nothing in Sonarr will set the cookie at the root.

**Comment by kmlucy** [comment]
Okay, I did some troubleshooting. It looks like it is actually Ombi that is setting the ``_ncfa`` cookie at ``/``. Whenever I clear that cookie, I am able to login to Sonarr again. So there is a conflict in Sonarr checking that cookie, but also with Ombi setting it. I will open an issue over there as well.

**Comment by markus101** [comment]
@Taloth the best way to fix this would be to change the token name we're using (we're already going to do that in v3), doing it now would effectively log everyone using forums auth out, but that happens every 2 weeks as it is, so it's not too bothersome. Thoughts?

**Comment by Taloth** [comment]
Yes, change it. We  could do some logic that renames the existing cookie, preserving the session, but I feel that's more effort than it deserves, so just change the cookie name.

**Comment by lkgarrison** [comment]
I had the exact same problem! Would love to see this get merged into master soon so that fewer people are experiencing a lock-out. I confirmed that my lockout was caused by Ombi having a cookie conflict with Sonarr.
