### ISSUE TITLE
Force-remote from torrent download client after successful import

### ISSUE THREAD

**Issue by Webreaper** [Sonarr/Sonarr#1964]
I raised this issue (https://github.com/Sonarr/Sonarr/issues/1894) to see if we could have separate seeding settings passed to the torrent client based on the indexer, but for Synology Download Station the API just doesn't exist to do this.

Wondering if another approach could be that for a particular indexer, as soon as the release is imported, the download could be deleted/removed from the client. It would really help to clean up completed/imported releases.

**Comment by markus101** [comment]
If Download Station tells Sonarr the torrent has stopped seeding, then it will remove it after importing it (if the setting is enabled), that would require a default seeding limit to be set in the client (not sure if download station supports that). Beyond that we generic plans to monitoring seeding goals and remove when the torrent reaches that goal, which would be set per indexer and only require Sonarr to be able to check the seeding time/ratio for the torrent (and not require Sonarr to set a limit at the client level).

**Comment by Webreaper** [comment]
Thanks. Yes, was more meaning that as a simple initial solution, Sonarr could have a "remove torrent on import" flag for each indexer, and then Sonarr would force-remove the torrent - regardless of seeding status - immediately when the torrent completes and the file is imported. That removes the need for Sonarr to try and monitor seeding goals and all that stuff, which is complex and dependent on the download client API supporting it.
