### ISSUE TITLE
Sonarr crashing after a few minutes.

### ISSUE THREAD

**Issue by SilverSix311** [Sonarr/Sonarr#1965]
Upon starting Sonarr it crashes after a few minutes of running. I tried both with and without using MONO_TLS_PROVIDER=legacy fix I saw from the recent reddit post. Let me know if you need any additional information.

Here are the logs: 
Sonarr: https://gist.github.com/SilverSix311/c33ea4bc3108eee4dc34d2fbdb5eb587
Mono: https://gist.github.com/SilverSix311/e5184e42949ed201c41f478ed95c06b4

**Comment by markus101** [comment]
Possible MediaInfo?

https://forums.sonarr.tv/t/sonarr-crashes-30-seconds-after-service-start/14921/3

It'd be best to capture the standard error/output of the mono process to capture any crashes (the mono log you posted doesn't provide that), please open a thread on the forums with that information (and the other requested information) so we can troubleshoot.
