### ISSUE TITLE
Deluge Daemon instead of/in addition to Web API

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1971]
Instead of only being able to connect to Deluge through the Web API (which can stop responding when it runs into an error) Sonarr should be able to connect to the Daemon directly.

**Comment by VA6DAH** [comment]
I would love to see this. If it ever happens let me know and I will paypal you $50.

**Comment by KyeRussell** [comment]
I'm increasingly having very weird reliability issues with the Deluge 'web' API (timeouts without resource constraints). The consensus seems to be that interfacing directly with the daemon is more reliable. If changing the interface method is a means of fixing these timeouts, I'd love to see a change here.

**Comment by chrisbonilla95** [comment]
Add another interested party. This is quite rare, but I recently was in a situation in which I had about 1,200 torrents running and the web api just gives up while the daemon keeps going (and thinclient works).

**Comment by bonebox** [comment]
+1. I'd love to use Sonarr (and Radarr) but unfortunately having to go back to CouchPotato/SickRage due to the unreliable nature of the web API. Sonarr fails connecting to it about 90% of the time for me, whereas the daemon connectivity has been solid through CP/SR.

**Comment by Dnkhatri** [comment]
1 problem I see is that the new deluge 2.0 daemon that will come out will might not be compatible with old  1.3 daemon. So if anyone working on it will have to keep that in mind.

**Comment by cinderblock** [comment]
I'm working on a [non-HTTP Deluge RPC client implementation](https://www.npmjs.com/package/deluge-rpc-socket). I've reimplemented the [rencode object serialization protocol in node](https://www.npmjs.com/package/python-rencode). It should work fine for Deluge 2 vs Deluge 1.x although I have not tested it with Deluge 2.

I'd love any feedback or to see another project use this library.

I just found Sonarr and am still unfamiliar with it. I might take a stab at integrating my library with Sonarr.

**Comment by Arzte** [comment]
Any thoughts on implementing the deluge daemon now that deluge v2, is out? If there's any potential issues or anything going this route (especially over the traditionally troublesome web api) I'd love to hear about it.

**Comment by MrAlfabet** [comment]
I'd love for this to be implemented as well. Being able to set download directories is why I'm still using couchpotato for movies instead of radarr.

**Comment by markus101** [comment]
Closing in favour of web API improvements https://github.com/Sonarr/Sonarr/issues/7318
