### ISSUE TITLE
Anime specials do not follow anime episode naming format.

### ISSUE THREAD

**Issue by exodius99** [Sonarr/Sonarr#1974]
I have a different name format set for anime and standard episodes. The main difference is that anime has the release group as part of the name. Any anime that is part of a regular season follows the format correctly but anything that falls under specials ignores that the series is set as an anime type and names the episode using the format for standard episodes.

**Comment by markus101** [comment]
If the episode doesn't have an absolute episode number, currently it will use the standard format instead of the absolute format, we have an issue to address that here: https://github.com/Sonarr/Sonarr/issues/1879
