### ISSUE TITLE
Omg added UHD categories

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#1977]
https://github.com/Sonarr/Sonarr/blob/d5965efccbaf589813e7b24ef1e71d1f95acdb53/src/NzbDrone.Core/Indexers/Omgwtfnzbs/OmgwtfnzbsRequestGenerator.cs#L94

Should now include catid 30 for UHD.

**Comment by thezoggy** [comment]
will let you know once this gets added...

**Comment by thezoggy** [comment]
these are live now. on both legacy and nn api
