### ISSUE TITLE
Issue after updating CentOS7

### ISSUE THREAD

**Issue by woogie55** [Sonarr/Sonarr#1978]
Jun 13 13:49:52 Server02 mono: at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x0009d] in <d1810f3a0e9846e3acb4cd1cb9652384>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x0007e] in <d1810f3a0e9846e3acb4cd1cb9652384>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in <d1810f3a0e9846e3acb4cd1cb9652384>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities (NzbDrone.Core.Indexers.Newznab.NewznabSettings indexerSettings) [0x00084] in <e875ff1e5e15495891c97fce19751838>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider+<>c__DisplayClass4_0.<GetCapabilities>b__0 () [0x00000] in <e875ff1e5e15495891c97fce19751838>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Common.Cache.Cached`1[T].Get (System.String key, System.Func`1[TResult] function, System.Nullable`1[T] lifeTime) [0x0006a] in <d1810f3a0e9846e3acb4cd1cb9652384>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities (NzbDrone.Core.Indexers.Newznab.NewznabSettings indexerSettings) [0x00046] in <e875ff1e5e15495891c97fce19751838>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Core.Indexers.Newznab.Newznab.get_PageSize () [0x0000c] in <e875ff1e5e15495891c97fce19751838>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Core.Indexers.Newznab.Newznab.GetRequestGenerator () [0x0000b] in <e875ff1e5e15495891c97fce19751838>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00007] in <e875ff1e5e15495891c97fce19751838>:0
Jun 13 13:49:52 Server02 mono: [Warn] Newznab: Unable to connect to indexer: Error: SecureChannelFailure (Object reference not set to an instance of an object)
Jun 13 13:49:52 Server02 mono: [v2.0.0.4753] System.Net.WebException: Error: SecureChannelFailure (Object reference not set to an instance of an object) ---> System.NullReferenceException: Object reference not set to an instance of an object
Jun 13 13:49:52 Server02 mono: at (wrapper managed-to-native) Mono.Btls.MonoBtlsSslCtx:mono_btls_ssl_ctx_new ()
Jun 13 13:49:52 Server02 mono: at Mono.Btls.MonoBtlsSslCtx..ctor () [0x00000] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at Mono.Btls.MonoBtlsContext.InitializeConnection () [0x00000] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at Mono.Btls.MonoBtlsContext.StartHandshake () [0x00000] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncProtocolRequest asyncRequest, Mono.Net.Security.AsyncOperationStatus status) [0x00004] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (Mono.Net.Security.AsyncOperationStatus status) [0x0006b] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation () [0x0000d] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at Mono.Net.Security.AsyncProtocolRequest.StartOperation () [0x0003c] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at Mono.Net.Security.AsyncProtocolRequest.StartOperation (Mono.Net.Security.AsyncOperation operation) [0x00024] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Net.LazyAsyncResult lazyResult) [0x00057] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: --- End of stack trace from previous location where exception was thrown ---
Jun 13 13:49:52 Server02 mono: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3753d1715b8842d8bb13a30db0388b60>:0
Jun 13 13:49:52 Server02 mono: at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Net.LazyAsyncResult lazyResult) [0x00078] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at Mono.Net.Security.MobileAuthenticatedStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) [0x0000c] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at Mono.Net.Security.Private.MonoSslStreamWrapper.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) [0x00006] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at Mono.Net.Security.MonoTlsStream.CreateStream (System.Byte[] buffer) [0x0007b] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at System.Net.WebConnection.CreateStream (System.Net.HttpWebRequest request) [0x00073] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: --- End of inner exception stack trace ---
Jun 13 13:49:52 Server02 mono: at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00058] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <1d7393d853954016b607e8e348b00ad1>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x0012d] in <d1810f3a0e9846e3acb4cd1cb9652384>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x0009d] in <d1810f3a0e9846e3acb4cd1cb9652384>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x0007e] in <d1810f3a0e9846e3acb4cd1cb9652384>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in <d1810f3a0e9846e3acb4cd1cb9652384>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities (NzbDrone.Core.Indexers.Newznab.NewznabSettings indexerSettings) [0x00084] in <e875ff1e5e15495891c97fce19751838>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider+<>c__DisplayClass4_0.<GetCapabilities>b__0 () [0x00000] in <e875ff1e5e15495891c97fce19751838>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Common.Cache.Cached`1[T].Get (System.String key, System.Func`1[TResult] function, System.Nullable`1[T] lifeTime) [0x0006a] in <d1810f3a0e9846e3acb4cd1cb9652384>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities (NzbDrone.Core.Indexers.Newznab.NewznabSettings indexerSettings) [0x00046] in <e875ff1e5e15495891c97fce19751838>:0
Jun 13 13:49:52 Server02 mono: at NzbDrone.Core.Indexers.Newznab.Newznab.TestCapabilities () [0x00013] in <e875ff1e5e15495891c97fce19751838>:0
Jun 13 13:49:52 Server02 mono: [Warn] NzbDroneErrorPipeline: Invalid request Validation failed:
Jun 13 13:49:52 Server02 mono: -- Unable to connect to indexer, check the log for more details
Jun 13 13:49:52 Server02 mono: -- Unable to connect to indexer, check the log for more details

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please use the forums for support.

https://forums.sonarr.tv/t/newznab-indexer-error-error-securechannelfailure-object-reference-not-set-to-an-instance-of-an-object-system-nullreferenceexception-object-reference-not-set-to-an-instance-of-an-object/14769
https://forums.sonarr.tv/t/nzbgeek-indexer-stopped-working/14905

And an existing issue for mono 5:
https://github.com/Sonarr/Sonarr/issues/1928
