### ISSUE TITLE
Manual Search for Season

### ISSUE THREAD

**Issue by nmiculinic** [Sonarr/Sonarr#1980]
I see there is the manual option for each episode, but for the season there is none, and I would like to use it since in one instance it finds an unsuitable download.

**Comment by markus101** [comment]
I find it ironic that a search related feature was added without [searching](https://github.com/Sonarr/Sonarr/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20Manual%20Search%20for%20Season) to see if it was already requested. 

Dupe of: https://github.com/Sonarr/Sonarr/issues/266

**Comment by nmiculinic** [comment]
My bad, it's late at night here.

Thank you for the reply!
