### ISSUE TITLE
No hardlink created

### ISSUE THREAD

**Issue by graille** [Sonarr/Sonarr#1982]
Hi !

I've configured sonarr to create hardlink from my torrent folder to my tv-show folder for each new episodes.
But when I check on the server, Sonarr copy the file, and doesn't create an hardlink

I've a kimsufi (OVH) server, sonarr works on a docker container on this server (container : https://hub.docker.com/r/linuxserver/sonarr/)

Torrents are downloaded with Deluge

**Comment by Taloth** [comment]
Please use https://forums.sonarr.tv/ for support or other questions. 

Hardlinks don't work across volumes.
