### ISSUE TITLE
CAPTCHA functionality for indexers?

### ISSUE THREAD

**Issue by awakenedbub** [Sonarr/Sonarr#1983]
As more people are using VPN's now (and more trackers are blocking them via CloudFront), is there any way to possibly integrate captcha functionality into the web GUI when setting up indexers? Even if a manual refresh is needed it would still be great to have some way of handling captcha from within Sonarr.

**Comment by Taloth** [comment]
Nope, it's virtually impossible with the current version of captcha used. We had it for Rarbg for a while, but now it's no longer feasible due to changes how recaptcha works.

So, don't use VPN for querying the indexer.
