### ISSUE TITLE
Distinguish between WEB-DL and WEB/WEBRip

### ISSUE THREAD

**Issue by heksesang** [Sonarr/Sonarr#1987]
Currently both WEB-DL and WEB/WEBRip releases fall under the WEB-DL category. This should be changed so they are two separate categories, as these are two different standards. With WEB-DL being higher quality (EAC-3 vs AAC, better video quality), but usually releasing later, it would be nice to be able to set it to upgrade from WEB to WEB-DL.

**Comment by markus101** [comment]
Covered by: https://github.com/Sonarr/Sonarr/issues/1781
