### ISSUE TITLE
Drone factory being REMOVED?  What about auto-extracting?

### ISSUE THREAD

**Issue by seanvree** [Sonarr/Sonarr#1990]
WOW.

why would you do this BEFORE implementing a solution to auto-extract .RARs?  

Those of use using torrents and on windows, rely on the drone factory!

MOOOOOMmmmmmmmm!

**Comment by markus101** [comment]
Replied to your other thread: https://forums.sonarr.tv/t/drone-factory-is-deprecated/15063
