### ISSUE TITLE
ArgumentOutOfRange for Specials

### ISSUE THREAD

**Issue by utegental** [Sonarr/Sonarr#1992]
Got AtgumentOutOfRangeException when tried to find Specials for 'Blue Exorcist'
Log:
`sonarr_1        | [Error] CommandExecutor: Error occurred while executing task EpisodeSearch 
sonarr_1        | 
sonarr_1        | [v2.0.0.4753] System.ArgumentOutOfRangeException: Can not search for Blue Exorcist - S00E02 it does not have an absolute episode number
sonarr_1        | Parameter name: AbsoluteEpisodeNumber
sonarr_1        |   at NzbDrone.Core.IndexerSearch.NzbSearchService.SearchAnime (NzbDrone.Core.Tv.Series series, NzbDrone.Core.Tv.Episode episode, System.Boolean userInvokedSearch) [0x00076] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:202 
sonarr_1        |   at NzbDrone.Core.IndexerSearch.NzbSearchService.EpisodeSearch (NzbDrone.Core.Tv.Episode episode, System.Boolean userInvokedSearch) [0x00046] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:71 
sonarr_1        |   at NzbDrone.Core.IndexerSearch.NzbSearchService.EpisodeSearch (System.Int32 episodeId, System.Boolean userInvokedSearch) [0x0000d] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:53 
sonarr_1        |   at NzbDrone.Core.IndexerSearch.EpisodeSearchService.Execute (NzbDrone.Core.IndexerSearch.EpisodeSearchCommand message) [0x00016] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\IndexerSearch\EpisodeSearchService.cs:87 
sonarr_1        |   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000f6] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:91 
sonarr_1        |   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
sonarr_1        |   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x00035] in <26aedeede9534b948c539f8734c8492d>:0 
sonarr_1        |   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
sonarr_1        |   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 `

**Comment by markus101** [comment]
The information is in the error message: `Can not search for Blue Exorcist - S00E02 it does not have an absolute episode number`

https://github.com/Sonarr/Sonarr/issues/1970 will handle that scenario.
