### ISSUE TITLE
Episodes Stopped Grabbing, no reason, nothing changed

### ISSUE THREAD

**Issue by jjlawless** [Sonarr/Sonarr#1994]
On Monday, my episodes stopped grabbing.

The RSS sync us working and all other syncs, all have ran in the past hour, I also manually ran the RSS sync as well from the series page.  The path to the files is correct and available.  If I manually search for the episode then it finds it and I can choose which one to download.  Also, if I click the magnifying glass for the episode, it finds the episode and downloads / processes it..  This means the indexers (nzbfinder.ws & oznzb) both work and so does the connection to SAB.

I double checked all of the API keys and they are fine, when testing indexer and SAB, everything works fine.  This is a standalone machine so nothing else should have interfered.

This is the error code that started Monday, but even with this, manual downloading / searching still works and sends to SAB:

	NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to SABnzbd, please check your settings ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8080 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.GetResponse() at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 76 at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 60 at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 70 at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 178 --- End of inner exception stack trace --- at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 186 at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.GetHistory(Int32 start, Int32 limit, String category, SabnzbdSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 120 at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.GetHistory() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Sabnzbd\Sabnzbd.cs:line 119: Unable to connect to SABnzbd, please check your settings

**Comment by jjlawless** [comment]
This is the error:

NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to SABnzbd, please check your settings ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8090 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.GetResponse() at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 76 at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 60 at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 70 at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 178 --- End of inner exception stack trace --- at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 186 at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.GetHistory(Int32 start, Int32 limit, String category, SabnzbdSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 120 at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.GetHistory() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Sabnzbd\Sabnzbd.cs:line 119: Unable to connect to SABnzbd, please check your settings

**Comment by markus101** [comment]
Please use the forums for support.

> No connection could be made because the target machine actively refused it 127.0.0.1:8080

If you changed the port to 8090, Sonarr is still trying to connect on 8080 and it's being refused by the host (A firewall, not listening on that port are the common causes of that).

**Comment by jjlawless** [comment]
I changed sonarr and sab to 8090 to test.  The connection was ok.  I did that in case there was a port conflict.  It was not.  Changed back to 8080.  I can search and nzbs grab but the auto grab stopped working




-------- Original message --------
