### ISSUE TITLE
Maximum download size

### ISSUE THREAD

**Issue by Safihre** [Sonarr/Sonarr#1996]
Like many usenetter's, I have a small SSD with the Temporary Download folder for SABnzbd that then unpacks to the larger drive (or maybe a NAS for other users).

My SSD is space limited, so I don't want 60GB season packs, I need separate episodes.
I have been handling this now by just Un-monitoring 1 epsiode of the season to force Sonarr to download them all separate.

It would be much easier to have a Maximum Download Size setting. 
For now this could be 1 global setting, but I can imagine users would like this on a per-Download-client level.

**Comment by markus101** [comment]
This sounds superfluous for most users and I see the potential for confusion with maximum quality sizes. @Taloth what do you think?

**Comment by Safihre** [comment]
Initially I was thinking of an option to disable Season-packs, but as #1997 shows, there are more ways in which downloads can be bigger than maximum quality sizes.
It is actually a bit confusing now that you set a maximum size, but downloads can still be bigger than that. 
Can of course be under the Advanced settings only to avoid confusion.

**Comment by Taloth** [comment]
I think it's a valid concern, just not sure on the 'right' way to fix it. I had some users request it before.
I'm think we could also use the free-disk space check, download size * 2, and use it as a 'temporary rejection'. Afaik Sonarr can already get the likely output dir for most download clients. Obviously not as waterproof as some config option.
I wouldn't want it per download client, but having a global option, similar to maximum age doesn't sound too bad, and obviously quite easily done. We could name it 'Maximum Release Size' and put it next to the Maximum Age option, that ought to be clear enough.

**Comment by Safihre** [comment]
> I'm think we could also use the free-disk space check, download size * 2, and use it as a 'temporary rejection'. Afaik Sonarr can already get the likely output dir for most download clients. 

This would not work on my system because when downloading is active, it can fill up almost to 100% capacity. But I have set SABnzbd to download only 1 download at a time and Pause during post-processing, so it will never fill above capacity. So depending when Sonarr would check, it could see only like 500MB free space left.

>We could name it 'Maximum Release Size' and put it next to the Maximum Age option, that ought to be clear enough.

Sounds good! Although where is this Maximum Age option? I can only find Minimum Age.

**Comment by Taloth** [comment]
I meant Minimum Age, yes.

**Comment by Thirrian** [comment]
Wouldn't it be easier to solve this with a pre-processing script in sab? https://sabnzbd.org/wiki/scripts/pre-queue-scripts
The examples even specifically target file size of the download to do stuff with it... :)

**Comment by Safihre** [comment]
That would be possible, but I think this feature is relevant enough to be handled by Sonarr. 
Especially because if sabnzbd sends it backs to sonarr, the whole cycle of searching for a new release will be repeated numerous times before finally getting to non-season packs.

**Comment by thezoggy** [comment]
just to note, other apps have the toggle to prefer or avoid season packs.. so its understandable that someone wants the same feature for sonarr.
back in SB days, the same issue would happen for people and I would just tell them to unmonitor one ep.. then tell the app to search for the season.. because you dont have the whole season monitored season packs get discarded... i think the same 'trick' can work for sonarr

**Comment by Safihre** [comment]
> i think the same 'trick' can work for sonarr

I do that already:
>I have been handling this now by just Un-monitoring 1 epsiode of the season to force Sonarr to download them all separate.

But that doesn't fix this special first/last episode of season-can-be-double thing.

**Comment by markus101** [comment]
Closed via https://github.com/Sonarr/Sonarr/commit/d25e5fe3298e21f811edc2bacf5869807138fa3c
