### ISSUE TITLE
Sonarr ignored maximum size for quality

### ISSUE THREAD

**Issue by Safihre** [Sonarr/Sonarr#1997]
With these settings:
![image](https://user-images.githubusercontent.com/5703454/27510541-325076b6-5913-11e7-9ca9-141729adb30c.png)

Using the profile `HD-1080p`, it downloaded [this NZB](https://github.com/Sonarr/Sonarr/files/1099905/super-secret-nzb.zip) which is 12.1GB, of which 1.6GB is `par2`. 

Following the link on the details page to the indexer's page also shows it:
![image](https://user-images.githubusercontent.com/5703454/27510558-8d219fe8-5913-11e7-846e-70c7f2e13918.png)

**Comment by markus101** [comment]
The first and last episode are allowed to be double the size to account for double episodes that are considered a single episode by TheTVDB, which is likely the issue here.

**Comment by Safihre** [comment]
That indeed makes sense indeed with the weird episode numbering sometimes.
It just circles back then to my general Maximum size issue: #1996.
