### ISSUE TITLE
3% naming exception

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#1998]
'3%' has a naming exception '3 Percent' as appropriate. But since '3%' = cleantitle '3' and thus still matches the wrong '3.S01' releases from another show.

Two options:
1) We could simply convert % to 'percent' in cleantitle, but I'm afraid what that will do for other shows (although we could add exceptions for those if need be).   
2) Otherwise we need a method to disable the original title and use the exception exclusively.
3) All of the above.

**Comment by thezoggy** [comment]
how many shows actually have `%` in their titles?

**Comment by markus101** [comment]
14 series according to skyhook:

![image](https://user-images.githubusercontent.com/413544/27622547-9e6f1afc-5b8c-11e7-8f71-d0ce1bbaf076.png)

Could we do what we did for some anime series and not strip out `%`?

**Comment by thezoggy** [comment]
two with `100%` ?
