### ISSUE TITLE
"Drone Factory is deprecated and should not be used"

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#1999]
Shouldn't this message be disabled if the user has `Drone Factory Interval` set to **0** ?
Since its disabling DF... the only way to get that warning to go away is to set the DF directory to nothing...

**Comment by Taloth** [comment]
I considered that (and actually had the code written), but I want both fields gone in v3.

**Comment by thezoggy** [comment]
It just caught me off guard because I never have used DF on this computer and I had it set to 0. There was a path filled it from when I migrated my config, but that path wasn't even valid.
