### ISSUE TITLE
Slack - notification

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#2000]
currently sonarr sends a slack notification that has text and an attachment. They are redundant of each other and take up some space and become quit busy looking once you have a few notices going.

example of what it is currently:
![slack1](http://zoggy.net/slack_2017-06-25_04-02-04.png)

example of what I suggest it's changed to (ignore app icon/notice color):
![slack2](http://zoggy.net/firefox_2017-06-25_04-28-53.png)

**Comment by markus101** [comment]
Customization will come with: https://github.com/Sonarr/Sonarr/issues/328

**Comment by seanvree** [comment]
Just so I'm clear on this...customizing the bot icon is NOT supported right now right?  

It worked with Slack...but I switched to the self hosted version MatterMost, and no matter what I put in the icon field, emojji or public link to .png, it always shows the default icon
![sonarricon](https://user-images.githubusercontent.com/8906637/27823332-9b349cd8-605d-11e7-98f5-4201cb1676c2.png)

**Comment by markus101** [comment]
> It worked with Slack...but I switched to the self hosted version MatterMost

Sounds like MatterMost doesn't handle it the same way, changing the icon _is_ supported, changing the format of the message is not.

**Comment by seanvree** [comment]
@markus101 

hummm....yeah, not working on Sonarr or Radarr but works on Plexpy, Headphones, and others.  Sounds like the code needs to be updated.

Thanks!

**Comment by markus101** [comment]
Please file an issue and we can take a look.
