### ISSUE TITLE
Unable to parse episodes from release name

### ISSUE THREAD

**Issue by jcchristian** [Sonarr/Sonarr#2001]
I've a bunch of working links for this series, but all Sonarr gives me is "Unable to parse episodes from release name". Everything is in there: name, episode absolute number, quality and group. How come it won't allow me to download?

![image](https://user-images.githubusercontent.com/4141392/27519604-bf020a60-59cd-11e7-8170-347349292243.png)

**Comment by Taloth** [comment]
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)
