### ISSUE TITLE
Bulk download partially upgrades Season

### ISSUE THREAD

**Issue by johnmarksilly** [Sonarr/Sonarr#2004]
- Sonarr finds higher quality content - An entire season just released on Bluray.
- Sonarr downloads the entire season at higher quality
- Download completes.
- Sonarr starts moving episodes and replaces lower quality versions.
- Sonarr's concurrent processing skips over a few episodes that still remain to be imported (on accident).
- Sonarr deletes the rest of the downloaded replacement season (thinks all content has been added when not really).
- Season is now left partially upgraded.

**Comment by markus101** [comment]
> Sonarr's concurrent processing skips over a few episodes that still remain to be imported (on accident).

Concurrent processing of what? Importing is a single thread and should be in episode order (if it's a single season pack)

> Sonarr deletes the rest of the downloaded replacement season (thinks all content has been added when not really).

Was it a season-pack torrent that finished was already finished seeding?

Without debug logs showing the import process (and why some files weren't imported) there isn't much to go on here.

**Comment by johnmarksilly** [comment]
Hmm, I was under the impression that the downloaded files watcher might be running tasks asynchronously (passing a path or something to another import service as a queue).

Anyway, I can publish some logs when I get home and maybe some screenshots to better describe what is happening. It is pretty consistent on it's behavior though.

To answer your question, 

> Was it a season-pack torrent that finished was already finished seeding?
Yes, it was a season-pack. It is really odd, because I assume it would grab all files within the folder, then after the last file has been handled in the list, delete the outer folder. 

However, based off of the import notifications I get, it happens out of sequence.

I will post some logs when I get home from work tonight. I can attach an example import notification screenshot though.
![image](https://user-images.githubusercontent.com/11224731/27648516-71a1ca70-5bf4-11e7-8a92-c6ce289e6bee.png)

**Comment by markus101** [comment]
Please open a thread of the forums with the relevant logs if you run into this again or have them from this occurrence and we can help troubleshoot there.
