### ISSUE TITLE
Refactor rtorrent api support to talk to a SCGI socket directly

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#2007]
Really just a nice to have since we wouldn't need rutorrent. SCGI is relatively straight forward.
Thing is that we'd have to redo the XML-RPC stuff, but I've not been exactly happy with the xmlrpc proxy using the external lib anyway, since it doesn't support curl.

Ref for the missing curl support: https://github.com/Sonarr/Sonarr/issues/1329

**Comment by Avamander** [comment]
Any updates on this?

**Comment by Taloth** [comment]
no

**Comment by markus101** [comment]
Given the limited interest in this over the years I'm closing, but will tag for future review.
