### ISSUE TITLE
Drone Factory relics

### ISSUE THREAD

**Issue by demonbane** [Sonarr/Sonarr#2009]
I just disabled the Drone Factory per the warnings in the most recent version and I noticed a few things that are left over even after disabling it.

1. "Rescan Drone Factory Folder" on the Wanted tab is still there, even though I've disabled Drone Factory altogether.
2. Drone Factory still shows up under Settings -> Download Client after it's disabled. Since it's getting removed, it would make sense to just hide the setting once it's disabled.

Both of these are largely cosmetic issues, I just wanted to get them documented so that when DF does get killed off for good there's a record of details to be handled.

**Comment by markus101** [comment]
Yeah, these will be removed in v3.

**Comment by Taloth** [comment]
Actually markus, hiding the Rescan Drone Factory Folder button is a sound option, even for v2.
Not gonna remove the Drone Factory folder field, it's already an Advanced Setting and people need to option to have it enabled in v2, despite the warning.
