### ISSUE TITLE
PushBullet - End-to-End Encryption

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#2013]
Looks like support end to end encryption is fairly easy to implement:

https://docs.pushbullet.com/#end-to-end-encryption

PBKDF2 in C#: https://lockmedown.com/hash-right-implementing-pbkdf2-net/ or https://www.owasp.org/index.php/Using_Rfc2898DeriveBytes_for_PBKDF2 though it looks like it's limited to SHA-1 so https://stackoverflow.com/questions/16341676/how-can-i-hash-passwords-with-salt-and-iterations-using-pbkdf2-hmac-sha-256-or-sis probably better.

**Comment by FireEater64** [comment]
Does pushbullet actually support E2E crypto for pushes? I was under the impression it was [just for SMS, notification mirroring and universal copy & paste](https://github.com/rharder/asyncpushbullet#end-to-end-encryption).

**Comment by markus101** [comment]
They give an example in JS that leads me to believe it is supported, but I saw that as well, so I'm not 100% sure it is.

**Comment by markus101** [comment]
Looking again it's only supported for Notification Mirroring, Universal Copy & Paste, and SMS. Closing this out.
