### ISSUE TITLE
Defender: NZBDrone Win32/Rundas.B

### ISSUE THREAD

**Issue by gnade** [Sonarr/Sonarr#2014]
As an FYI

It seems the latest version of Defender is detecting something malicious in NZBdrone. 
I assume it is a false positive, but worth  a note to the developers anyway. 
Anyone else getting the advisory?

On process start, receive Windows Defender warning
Category: Trojan
Name: Trojan: Win32/Rundas.B
Affected Items: NzbDrone.exe

**Comment by markus101** [comment]
One other report here: https://forums.sonarr.tv/t/windows-defender-blocking-sonarr-as-trojan/15135

Definitely a false positive, my guess is a heuristic check picked it up.
