### ISSUE TITLE
Unable to parse episodes from release name

### ISSUE THREAD

**Issue by ekleinem** [Sonarr/Sonarr#2017]
I have this added as a daily show, and sonarr is having troubles parsing it. I'm surprised by this because the release actually has the date in it. Any ideas on how to fix this?

![spectacle j10432](https://user-images.githubusercontent.com/26104677/27843615-959374a8-60e3-11e7-9be9-e29bbb513555.png)

**Comment by markus101** [comment]
Please use the forums for support.

Recent thread with a similar/the same issue: https://forums.sonarr.tv/t/tv-series-title-not-parsing-properly-in-both-daily-and-standard-series-type/15161

Support for this may come via: https://github.com/Sonarr/Sonarr/issues/457
