### ISSUE TITLE
Adding a series from the search result, resets the search and the results disappear

### ISSUE THREAD

**Issue by desimaniac** [Sonarr/Sonarr#2019]
So basically you are unable to add multiple shows in succession because it resets and you have to go back and retype in another name.  

This behavior is different from Radarr which allows you to add multiple movies one after another. 

Sonarr Ver. 2.0.0.4856
develop

**Comment by markus101** [comment]
This behaviour will be changing in v3, no plans to change the existing behaviour.

**Comment by desimaniac** [comment]
OK. Thanks for the info.
