### ISSUE TITLE
v2.0.0.4859 -- Slack notification broken now on dev

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#2020]
Slack was working before latest updates, going to try to Test notification you see it fail now with:
`[v2.0.0.4859] System.ArgumentException: Uri didn't match expected pattern`

**Comment by markus101** [comment]
@Taloth this was due to a leading space in the URL, which worked fine with RestSharp, but now fails with HttpClient, any concern with stripping leading/trailing spaces when parsing in `HttpURI`?

**Comment by Taloth** [comment]
Tbh I think we should deal with it in validation and not magically change urls. I'm not opposed to do some cleanup in HttpURI but i rather not, since it affects for example string comparisons.

**Comment by thezoggy** [comment]
perhaps just trim the url field when you save?

**Comment by markus101** [comment]
Yeah, @Taloth thoughts on changing: https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Api/ClientSchema/SchemaBuilder.cs#L134 to `propertyInfo.SetValue(target, field.Value.ToString().Trim(), null);` It seems a bit aggressive, but I'm not sure where else we'd do it. Also not sure if this would cause issues where people are expecting leading/trailing slashes.

**Comment by Taloth** [comment]
that would be pretty ugly. Why not add it to the validation code instead? You're gonna check if the string is an url anyway. So check if it has leading/trailing whitespace.

**Comment by markus101** [comment]
Our validation already checks that the URI is valid: https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Common/Extensions/UrlExtensions.cs#L14-L23

The problem is, it is valid, but our own parser is stricter. We could switch to parsing with `Uri`, but that screws up our segment replacing.
