### ISSUE TITLE
Update rename option in wiki to "Series TitleThe"

### ISSUE THREAD

**Issue by TheFreshPrinceOfBel-Air** [Sonarr/Sonarr#2022]
In accordance with commit [68290b0](https://github.com/Sonarr/Sonarr/commit/68290b038582a6134dc9bf9365b0f07ff75c72c0), mind updating the Sorting and Renaming wiki page to contain the correct rename option text?

The current text reads "Series Title The". It should read "Series TitleThe".

Tested and confirmed the latter works in Sonar v2.0.0.4855. Thanks!

**Comment by Taloth** [comment]
Updated it, tnx.

But fyi it's a wiki, anyone can edit :smile:

**Comment by TheFreshPrinceOfBel-Air** [comment]
Yea I tried to edit it first, but got a generic "Unable to save" error every time I tried to save :/

**Comment by Taloth** [comment]
that's odd... github hates you 😈...  well, tnx for reporting it.
