### ISSUE TITLE
Feature Request: Change seasons quickly for Manual Import like Series Editor page

### ISSUE THREAD

**Issue by desimaniac** [Sonarr/Sonarr#2024]
Sometimes it is easier to download entire series packs and to import them one by one and change the seasons for each one when it is not automatically recognized is tedious. 

One solution I think could help is having a similar toolbar that as the Series Editor page... where you could potentially select more than one item and define a Series to it at one go, and perhaps also a season number as well.

![image](https://user-images.githubusercontent.com/5501908/27925243-a8ea0bfe-6249-11e7-8676-2ccc060b7dc6.png)

**Comment by markus101** [comment]
This will be taken care of in the v3 UI. https://github.com/Sonarr/Sonarr/issues/1643

**Comment by desimaniac** [comment]
Sorry I submitted before editing..
