### ISSUE TITLE
DownloadStation doesn't get password from Sonarr

### ISSUE THREAD

**Issue by Fabniam** [Sonarr/Sonarr#2025]
If I set up "Sabnzbd" as DownloadClient everything works fine, but the "DownloadStation"-Client of Synology won't extract the archives, as it doesn't get any information about the password from Sonarr.
Instead the password is written inbetweeen "{{}}" right after the name.

<img width="782" alt="screen" src="https://user-images.githubusercontent.com/27829220/27927568-81e39b5e-628c-11e7-88eb-0940bcb5a1c1.png">

**Comment by markus101** [comment]
Sonarr doesn't pass any password information to the download client, SAB must be interpreting that itself. I'm not sure if Sonarr could even pass the password to the download station client if it did parse it out, but this sounds like something download station should add support for if that's a common pattern.

DS's auto-extract password support does seem to be limited: https://www.synology.com/en-global/knowledgebase/DSM/help/DownloadStation/auto_unzip
SAB supports retrieving it a couple ways: https://sabnzbd.org/wiki/advanced/password-protected-rars
