### ISSUE TITLE
Seems to be crashing hard every time it tries to RSS sync

### ISSUE THREAD

**Issue by Zer0t3ch** [Sonarr/Sonarr#2027]
https://hastebin.com/linujufazo

There's my system log. (from journalctl)

This seems to have started after a power failure sometime last night.

**Comment by Zer0t3ch** [comment]
Is there some kind of cache that I can clear to try and resolve this?

**Comment by Zer0t3ch** [comment]
My apologies. While it seemingly came out of nowhere from a functional install, updating to the most recent version *seems* to have fixed it. (I'm on Arch, so I'm using the most recent version on the AUR)

**Comment by markus101** [comment]
This is covered by: https://github.com/Sonarr/Sonarr/issues/1928

**Comment by Zer0t3ch** [comment]
@markus101 Good to know it's being handled. Thanks.
