### ISSUE TITLE
Implement Bulk-Rename Series-Folders to Convention

### ISSUE THREAD

**Issue by player8472** [Sonarr/Sonarr#2029]
It would be nice to have a Feature to Bulk-Rename (move) the Series into Folders matching the Pattern.

For Example you have;
*/somepath/Battlestar Galactica*
*/somepath/Battlestar Galactica (New)*

and after the Bulk-Rename it should be:
*/somepath/Battlestar Galactica (1978)*
*/somepath/Battlestar Galactica (2003)*

This would especially help people with old collections like mine which are very big and near to immpossible to rename manually. 

Sonarr already has all the data you need for it - so it would be the best tool to implement it in.

**Comment by markus101** [comment]
Covered by https://github.com/Sonarr/Sonarr/issues/392
