### ISSUE TITLE
Series files don't exit, but sonarr still thinks they exist

### ISSUE THREAD

**Issue by super94i** [Sonarr/Sonarr#2030]
I restored a backup and set up all the folders. I did a library update and sonarr picked up almost all the missing anime while the TV Shows where still considered "complete".

What to do?

**Comment by markus101** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please use the forums for support.

Check the logs, but it sounds like the root folder is empty so Sonarr won't rescan it and detect that files are missing, make sure at least one folder exists in the root folder and that the series paths are set correctly.

**Comment by super94i** [comment]
Hey, Could you please delete this issue? I would really appreciate it!
