### ISSUE TITLE
Roksbox metadata provider generates series, season, & episode images even when no types are selected

### ISSUE THREAD

**Issue by TheFreshPrinceOfBel-Air** [Sonarr/Sonarr#2031]
So I was in the process of writing a Sonarr wiki page detailing which files get created for each of the possible metadata types, and I believe I've found a bug in the Roksbox metadata provider:

If you enable the Roksbox metadata provider, even if you have no types enabled (so all types are toggled to "No"), the series, season, and episode images are all still created. Toggling the settings on and off again has no effect as well.

The season, series, and episode images that are being created are:

- {ShowName}.jpg
- Season ##/Season ##.jpg
- Season ##/{episodeFileName}.jpg

These correspond to the "Series Images", "Season Images", and "Episode Images" metadata types. Looking at the code it looks like those metadata type codepaths are being executed regardless of the selected types (so it is nothing to do with those specific images as far as I can tell).

I dug into the code a little bit, but haven't had a chance to dig deep. I did notice that the Roksbox file seems to be a clone of the WDtv file, so maybe some copypasta occurred. I can dig into the code further at a later time if no one else can take a look at this sooner :) Thanks!

The metadata provider/consumer file in question:

https://github.com/Sonarr/Sonarr/blob/03b83ed22659355028711a8d44030bc56d71c725/src/NzbDrone.Core/Extras/Metadata/Consumers/Roksbox/RoksboxMetadata.cs

It also may be worth noting: the only metadata option that is not auto-generated when Roksbox is enabled is the "Episode Metadata" option.

**Comment by markus101** [comment]
Thanks! Those settings were definitely unused, looks like the checks were never added (oops). I've fixed them now.

**Comment by TheFreshPrinceOfBel-Air** [comment]
Such a boss, thanks for the quick turnaround!

Looking at your change, the fix was right there in the Episode Metadata and I totally glossed right over it. 😝
