### ISSUE TITLE
Importing existing series from disk has issues with years in []

### ISSUE THREAD

**Issue by on2valhalla** [Sonarr/Sonarr#2033]
Very few of my folders will automatically import, while square braces seem to cause havoc with the search components. After deleting the brackets and year, the search typically finds the correct series in the first go.

Example folders (2 of 120):
\Media\TV\Walking Dead, The [2010]
\Media\TV\White Collar [2009]

**Comment by markus101** [comment]
This is something we'll be better able to support when we move to the new TVDB API (as search is handled by them and not very flexible). https://github.com/Sonarr/Sonarr/issues/918
