### ISSUE TITLE
Wrong Episode Names

### ISSUE THREAD

**Issue by rsanch1** [Sonarr/Sonarr#2034]
I noticed Teen Wolf Season 6 Episodes 11 - 14 have the wrong names and it's in spanish.  I looked up the series in TVDB and TvMaze and they both only have episode 11 (Said the Spider to the Fly) listed with the correct English title.

Sonarr has the following:

Episode 11 - Esta Serie Solo La Ven Mojabragas  (English translation - This series is only watched by fangirls)
Episode 12 - Mojabragas Dedicaros A Estudiar En Vez  (English translation - fangirls dedicated to study instead)
Episode 13 - Perder El Tiempo En Ver Esta Serie Solo  (English translation - waste time watching this series)
Episode 14 - Porque Los Personajes Son Guapos  (English translation - because the actors are beautiful)

Sonarr also has the air dates as being 7/9 Sunday, 7/10 Monday and 7/11 Tuesday which is also incorrect.

Is there a way to get this corrected?

**Comment by Taloth** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please use the forums for support.

Sonarr uses Tvdb as source, but there are several caches. Refresh the series in an hour or two.
