### ISSUE TITLE
Webhook API documentation is out of date

### ISSUE THREAD

**Issue by kaotik4266** [Sonarr/Sonarr#2035]
As of v2.0.0.4855, Sonarr now seems to be sending webhook messages with camel case field names, rather than pascal case as described in the [webhook documentation](https://github.com/Sonarr/Sonarr/wiki/Webhook).

I'm happy to update the documentation if this was an intentional change (and to be honest, I personally prefer it), just wanted to confirm first.

Sample message body:
```js
{
    "episodes": [
        {
            "id": 123,
            "episodeNumber": 1,
            "seasonNumber": 1,
            "title": "Test title",
            "qualityVersion": 0
        }
    ],
    "eventType": "Test",
    "series": {
        "id": 1,
        "title": "Test Title",
        "path": "C:\\testpath",
        "tvdbId": 1234
    }
}
```

**Comment by markus101** [comment]
Whoops, I hadn't realized it was pascal case before, but camel case is consistent with other JSON emitted by Sonarr (and was switched to camel case here as it's using the same serializer now).

A slightly breaking change (depending on the recipient), but I agree, it's preferred and the former was unintentional.

Thanks for letting us know, updating the documentation makes sense.

**Comment by kaotik4266** [comment]
Cheers, I'll do that this afternoon then close this issue. Might also add generalised interfaces in addition to example messages. Is `/src/NzbDrone.Core/Notifications/Webhook/Webhook.cs` the only place I need to look to see how messages will be formatted?

**Comment by markus101** [comment]
Yeah, that will show the models being used, all model properties are PascalCase, but the JSON emitted will be camelCase.

**Comment by kaotik4266** [comment]
Okay, [here's the JSON schema](https://gist.github.com/kaotik4266/ee29c515cb01c75c505b1e83100e0fab) I've inferred from the code. Let me know if you see any errors. I've tested that it validates a bunch of different messages pulled from my webhook's logs, but I haven't checked many invalid scenarios.

**Comment by kaotik4266** [comment]
I've updated the docs and added a [wiki page with the JSON schema](https://github.com/Sonarr/Sonarr/wiki/Webhook-Schema). If I've missed anything please reopen this issue and I'll fix it.

**Comment by markus101** [comment]
👍 That looks correct to me. Is there a good way to indicate in the schema that a value is deprecated? In v3 I plan to rip out the Episode File/Release information (quality, release group, scene name, etc) from the Episode to keep them more inline with output from the API, but marking it as deprecated now would be useful.

**Comment by kaotik4266** [comment]
There's an [open issue](https://github.com/json-schema-org/json-schema-spec/issues/74) in the JSON Schema spec repo to add a `deprecation` keyword to the hyper-schema, but it doesn't seem to have a great deal of traction. You can, however, add a `description` attribute to any property in the schema, as well as the `anyOf` branches, so that would probably be the easiest way to indicate what is deprecated.
