### ISSUE TITLE
Season packs searches / optimization of search functions in Sonarr

### ISSUE THREAD

**Issue by rarbg** [Sonarr/Sonarr#2037]
Hey guys
Are you planning to add season pack searches to sonarr ?
For example lets say i want to add Game of Thrones to my Sonarr
Currently for S01E01 i wont find any suitable torrents if i have only rarbg added as provider
On the API side sonarr searches for S01E01 
However we have Game of Thrones season packs with lots of seeds
If you search the API for .S01. you will find the season pack for example but Sonarr doesnt search for season packs
Maybe you should add this ... what do you think ?

**Comment by Taloth** [comment]
If you search for the whole season then Sonarr will query by S01: https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Indexers/Rarbg/RarbgRequestGenerator.cs#L37-L44
If you ask it to search for a single episode, then well,... it'll search for a single episode. :smile:

I'd say it's related to Manual Season Search: https://github.com/Sonarr/Sonarr/issues/266

**Comment by rarbg** [comment]
Hm , i might be missing something then. I see no way to manually search for a season ?

**Comment by rarbg** [comment]
Ok so even after adding Game of thrones and setting the full season 1 as "wanted" sonarr still doesnt automatically search for S01 :)

**Comment by Taloth** [comment]
Set the log level to debug/trace, you'll see it parsing and rejection reasons.

**Comment by rarbg** [comment]
17-7-10 15:42:02.4|Debug|QualityParser|Trying to parse quality for Game.Of.Thrones.S01.1080p.BluRay.x264-HD4U[rartv]
17-7-10 15:42:02.4|Debug|Parser|Quality parsed: Bluray-1080p v1
17-7-10 15:42:02.4|Debug|Parser|Release Group parsed: HD4U
17-7-10 15:42:02.4|Debug|AcceptableSizeSpecification|Beginning size check for: Game.Of.Thrones.S01.1080p.BluRay.x264-HD4U[rartv]
17-7-10 15:42:02.4|Debug|AcceptableSizeSpecification|Item: Game.Of.Thrones.S01.1080p.BluRay.x264-HD4U[rartv], meets size constraints.
17-7-10 15:42:02.4|Debug|FullSeasonSpecification|Checking if all episodes in full season release have aired. Game.Of.Thrones.S01.1080p.BluRay.x264-HD4U[rartv]
17-7-10 15:42:02.4|Debug|LanguageSpecification|Checking if report meets language requirements. English
17-7-10 15:42:02.4|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Game.Of.Thrones.S01.1080p.BluRay.x264-HD4U[rartv]
17-7-10 15:42:02.5|Debug|ReleaseRestrictionsSpecification|[Game.Of.Thrones.S01.1080p.BluRay.x264-HD4U[rartv]] No restrictions apply, allowing
17-7-10 15:42:02.5|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. Bluray-1080p v1
17-7-10 15:42:02.5|Debug|QualityAllowedByProfileSpecification|Quality Bluray-1080p v1 rejected by Series' quality profile


Ok i goofed up. I admit it.
Thanks
