### ISSUE TITLE
Prefer torrent with highest number of seeds

### ISSUE THREAD

**Issue by dkids** [Sonarr/Sonarr#2038]
Really happy with Sonarr.  One thing that happens when I add a new series is that Sonarr selected this torrent:

Brooklyn Nine-Nine S04E15 720p WEB-DL HEVC x265-RMTeam | The Pirate Bay | 114.8 MB | 4 / 3 |  
-- | -- | -- | -- | --

but I think it should have selected this one:

Brooklyn Nine-Nine S04E15 720p HDTV HEVC x265-RMTeam | The Pirate Bay | 117.3 MB | 200 / 7
-- | -- | -- | --

The first torrent is stalled out.   I did a manual search and selected the second torrent, then deleted the first one.

It often seems to happen that the number of seeders is overstated a bit.   So The Pirate Bay might report 3 seeds when there's actually none.   Or 5 when there's only 1.   With a number higher than 10 this doesn't seem to be an issue.   And where there's 200, well, that works well.   

I would suggest prioritizing feeds that have 2X (or higher - 50X in this case) number of seeds or maybe setting a floor or lower bound of 6-10 seeds.

**Comment by Taloth** [comment]
Sonarr does prefer more seeds, but Quality trumps everything, WEB-DL > HDTV in your profile so it's picked as long as it's not rejected by any particular rule.

And since the last version you can configure a Minimum seeds per indexer with Advanced Settings enabled.
