### ISSUE TITLE
Synology Download Station - downloads not Importing automatically, Manual Works fine.

### ISSUE THREAD

**Issue by Ltek** [Sonarr/Sonarr#2040]
I just changed from using Blackhole & DroneFactory (which worked perfectly) to using the built-in settings for Download Station. While Sonarr pulls in the torrent, and DL Station downloads it to the same folder it always has... Sonarr no longer Imports (nor moves) the video file as it did before.

How do I fix this?

settings in Sonarr:
host = 127.0.0.1   (running everyone on the Syno)
port = 5000
login = <admin> & PW
Category & Directory both blank
Not using SSL

**Comment by markus101** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please open a thread on the forums for support, we'll need to see debug logs.
