### ISSUE TITLE
Option to ignore missing files

### ISSUE THREAD

**Issue by scuppasteve** [Sonarr/Sonarr#2041]
So i was wondering about adding a feature to ignore episodes. So that say there was some episode that has been banned or never aired or what not, you are able to chose to ignore that episode so that it doesn't do searches for it, and it then shows that a show is 100% complete with available files. This would also apply for shows that had episodes that never aired and are not included in any release. That way i could have a better idea what shows are really missing episodes vs episodes that i very likely will never obtain.

**Comment by markus101** [comment]
If you unmonitor them and they will be ignored. Episodes that don't have an air date won't show up as missing in the episode count though.
