### ISSUE TITLE
Should search anime if absolute episode number gets added for aired episode

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#2044]
If standard episodes get added with their airdate in the past, Sonarr will search for it. It should do the same for anime episodes that get an absolute episode number.

**Comment by ignoremenow** [comment]
Anime and the tvdb have always had a love hate relationship. Most of the time the person that add's in the ep knows they should add in an absolute, but in some cases they don't, if it happens to be a show I am watching I go through and try to clean it up, and I assume others do this as well. I see anime the same way as normal shows and think they should be treated as same. This also goes for making changes at the xem sometimes to but that's out of scope for this.

**Comment by M0UL** [comment]
adding this sonarr would be great. especially since the tvdb has really slow latelty.
