### ISSUE TITLE
Resotre to new OS

### ISSUE THREAD

**Issue by Viper911** [Sonarr/Sonarr#2051]
I would like to move my windows install to Ubuntu. Is there a way to move the config to the new machine. All my files are on NAS so I just need the app to be moved (changing paths, etc for the new OS install). Or even if it didn't do the core config that is easy to recreate, its the library config I need.

Can I perhaps just do a bulk import of the media and it will rebuild the library and any way to bring over the list exclusions (which I have hundreds)

**Comment by Taloth** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please post on the forums instead.
