### ISSUE TITLE
Unable to communicate with NZBGet

### ISSUE THREAD

**Issue by Viper911** [Sonarr/Sonarr#2052]
It passed the test when added (running latest radarr version on Ubuntu 16.04).  This is a new install as I move over from Windows.

Unable to communicate with MyNZBGet. Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.

Any idea what this is?

**Comment by markus101** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please open a thread on the forums for support, we'll need debug logs and more details.
