### ISSUE TITLE
Series lookup & how does Sonarr differentiate between added and not added series

### ISSUE THREAD

**Issue by NickyHeuperman** [Sonarr/Sonarr#2053]
I'm working on a little something to interact with Sonarr, I thought that looking up a series through the api at series/lookup would show monitored to be false when the series actually hasn't been added, this seems to not be the case. I'd say it wouldn't be a big problem as apparently the web ui is still able to differentiate between added(monitored) and not monitored series. I however can't see how. Any insight in the matter would be greatly appreciated

**Comment by markus101** [comment]
Monitored means that the series has `monitor = true` (editable when editing a series), which indicated whether Sonarr will grab episodes for it. The API doesn't indicate if a looked up series already exists, but you can compare the existing series and check if that TvdbId was already added (this is what the UI does).

**Comment by markus101** [comment]
Please let us know if you need more information, but closing this one out.
