### ISSUE TITLE
[ Phantom Branch ]  All paths for any new show are invalid.

### ISSUE THREAD

**Issue by minthat** [Sonarr/Sonarr#2058]
Under the latest Phantom branch release, 2.0.0.4873, Adding a new show has become impossible.  It is no longer possible to add a show due to an "Invalid Path" error in the Root Folder option, regardless of path chosen.

![image](https://user-images.githubusercontent.com/7675921/28353039-9e7ca3b0-6c0e-11e7-9a15-70752bc61b20.png)
![image](https://user-images.githubusercontent.com/7675921/28353057-bb3688b8-6c0e-11e7-8a10-0e78c0e80286.png)
![image](https://user-images.githubusercontent.com/7675921/28353065-cbbe91c6-6c0e-11e7-9463-98b6e129651f.png)

**Comment by markus101** [comment]
This is not a currently supported branch, it's still a work in progress.

**Comment by minthat** [comment]
Is there a place I should have left the bug report instead?  Besides that one new bug it's absolutely amazing btw.

**Comment by markus101** [comment]
Not at the moment, bugs are too be expected, we'll have something when we're ready to do a public beta, but not until we finish with the breaking changes.
