### ISSUE TITLE
Allow manual override of search query

### ISSUE THREAD

**Issue by underyx** [Sonarr/Sonarr#2060]
After adding [_Code Geass: Lelouch Of The Rebellion_](https://en.wikipedia.org/wiki/Code_Geass) and initiating a search for the full first season on a Jackett indexer, the following queries seem to be generated:

- `Code Geass Lelouch Of The Rebellion 01`
- `Code Geass 01`

These match neither the S01 season, nor the S01E01 episode scene releases found on [corrupt-net](https://pre.corrupt-net.org/), which apparently are:

- `Code.Geass.Lelouch.Of.The.Rebellion.VOL01.MULTi.BDRip.x264-KAZETV`
- `Code.Geass.Lelouch.Of.The.Rebellion.E01.MULTi.1080p.BluRay.x264-KAZETV`

It would be great if overriding the query allowed users to work around such naming quirks.

**Comment by markus101** [comment]
This is covered by: https://github.com/Sonarr/Sonarr/issues/1128
