### ISSUE TITLE
Manual search not displaying results

### ISSUE THREAD

**Issue by dejected1** [Sonarr/Sonarr#2061]
Manual search not displaying results:

Version
2.0.0.4855

When i do a manual search for shows it never completes. I just get the dots bouncing back and forth forever. When checking the log it says it finished and parsed the results but it never displays them. This happens on multiple shows. The show i searched for was adventure time. The log says no results found but again, my display doesn't update, just bouncing dots. Windows 10 x64. Automatic search seems to work thou. It also doesn't seem to happen on all searches. I searched for the latest adam ruins everything and it popped up the results just fine. Weird.

Component | Message | Time
-- | -- | --
  | DownloadDecisionMaker | No results found | 10:00am
  | NzbSearchService | Searching 9 indexers for [Adventure Time : S09E10] | 9:59am

  | Component | Message | Time
-- | -- | -- | --
  | DownloadDecisionMaker | Processing 11 releases | 10:03am
  | NzbSearchService | Searching 9 indexers for [Adam Ruins Everything : S02E02] | 10:02am

**Comment by markus101** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please open a thread on the forums for support, we'll need to see debug logs as well as the browser you're using.
