### ISSUE TITLE
[feature request] Make use of Imdbid for searching in  Trakt

### ISSUE THREAD

**Issue by nockstarr** [Sonarr/Sonarr#2062]
As Sonarr already use Trakt, why not make use of the Imdb endpoint in the Trakt API?
Ref: http://docs.trakt.apiary.io/#introduction/website-media-links

I checked if this already exist in Sonarr with the following request.
`/api/Series/lookup?apikey=apikey&term=imdb:tt4158110`
Returns a empty list

**Comment by markus101** [comment]
Sonarr hasn't used trakt in years (since their v2 API was released and the various issues that brought along with it).

Searching by IMDB ID is covered by: https://github.com/Sonarr/Sonarr/issues/1829
