### ISSUE TITLE
Mapping for show names with % is required

### ISSUE THREAD

**Issue by kopfpilot** [Sonarr/Sonarr#2063]
I recently added the show 3%, and whenever I perform a manual search on one of the episodes a lot of unrelated matches are listed in the result, as long as the character '3' is present in the entry name.
If Sonarr would replace the '%' character with 'percent' the results would be clear.

thetvdb id: 250749

Though it might be an issue on how one of my indexers work.

**Comment by Thirrian** [comment]
Might be related: https://github.com/Sonarr/Sonarr/issues/1998
