### ISSUE TITLE
Rtorrent xmlrpc failing to import torrent when serching. "Request Failed. POST /api/queue/grab"

### ISSUE THREAD

**Issue by Firelfy** [Sonarr/Sonarr#2064]
Sonarr is unable to send a torrent to rtorrent via xmlrpc. The issue only occurs during search, and does not affect rss sync downloads. Testing the client succeeds, I have noticed if rtorrent crashes, I am able to send one search request after reinstating the client, then all future requests fail.

May or may not be relevant, but Radarr still works as intended (based off of old Sonarr build?).

The issue has been noted by another user [here](https://www.reddit.com/r/sonarr/comments/6mah63/sonarr_download_failing_request_timed_out/).

My logs can be found [here](http://s000.tinyupload.com/index.php?file_id=03104586072712848420), and here is a snippet of the log segment in question:

> NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to rTorrent, please check your settings ---> System.Net.WebException: The request timed out
>   at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00049] in <2b0d86369d72459baed0cee98a8e578a>:0 
>   at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <2b0d86369d72459baed0cee98a8e578a>:0 
>   at CookComputing.XmlRpc.XmlRpcClientProtocol.GetWebResponse (System.Net.WebRequest request) [0x00014] in <9d687fb9c46d481292a78781773c6116>:0 
>   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke (System.Object clientObj, System.Reflection.MethodInfo mi, System.Object[] parameters) [0x0015a] in <9d687fb9c46d481292a78781773c6116>:0 
>   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke (System.Reflection.MethodInfo mi, System.Object[] Parameters) [0x00000] in <9d687fb9c46d481292a78781773c6116>:0 
>   at XmlRpcProxy7e19d4c7-ece0-442c-ba60-664d44be4cc6.LoadRawStart (System.String target, System.Byte[] data, System.String[] commands) [0x00038] in <34740f30eb80466bb0c0919d037b289d>:0 
>   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy+<>c__DisplayClass5_0.<AddTorrentFromFile>b__0 () [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:126 
>   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.ExecuteRequest[T] (System.Func`1[TResult] task) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:218 
>    --- End of inner exception stack trace ---
>   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.ExecuteRequest[T] (System.Func`1[TResult] task) [0x00017] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:226 
>   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.AddTorrentFromFile (System.String fileName, System.Byte[] fileContent, System.String label, NzbDrone.Core.Download.Clients.RTorrent.RTorrentPriority priority, System.String directory, NzbDrone.Core.Download.Clients.RTorrent.RTorrentSettings settings) [0x00049] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:126 
>   at NzbDrone.Core.Download.Clients.RTorrent.RTorrent.AddFromTorrentFile (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String hash, System.String filename, System.Byte[] fileContent) [0x00021] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrent.cs:64 
>   at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x001b8] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\TorrentClientBase.cs:183 
>   at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x00148] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\TorrentClientBase.cs:117 
>   at NzbDrone.Core.Download.DownloadService.DownloadReport (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x00171] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\DownloadService.cs:69 
>   at NzbDrone.Api.Queue.QueueActionModule.Grab () [0x0002d] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\Queue\QueueActionModule.cs:108 
>   at NzbDrone.Api.Queue.QueueActionModule.<.ctor>b__7_2 (System.Object x) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\Queue\QueueActionModule.cs:41 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
>   at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 

Thanks for your time.

**Comment by markus101** [comment]
Please open a thread on the forums for support.

> The request timed out

rTorrent never responded to the request, rTorrent's logs may indicate why it never responded The behaviour in Sonarr is the same when sending a torrent via search and via RSS Sync, so it shouldn't behave any different on rTorrents side, unless it's a magnet vs a torrent file being uploaded.
