### ISSUE TITLE
Pages similar to Radarr

### ISSUE THREAD

**Issue by b-rockx** [Sonarr/Sonarr#2066]
In Radarr they have added a page size option to reduce the load time of the main series tab. (show 250 series instead of all 2k+). This would be a great feature for those with lots of series. 

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
This is something we'll be addressing in v3, though it won't be through paging.\, but virtualization of the list that drastically speeds up loading.
