### ISSUE TITLE
Download link missing in manual search

### ISSUE THREAD

**Issue by abarbaccia** [Sonarr/Sonarr#2067]
When I preform a manual search for an episode within the "Specials" season, the link to start downloading is missing (I believe the column is called 'auto search prioritization'). See below. Thanks!

**Comment by abarbaccia** [comment]
![image](https://user-images.githubusercontent.com/490858/28504860-a57c5daa-6feb-11e7-83fd-0b3bca1c3927.png)

**Comment by abarbaccia** [comment]
![image](https://user-images.githubusercontent.com/490858/28504869-b917b53a-6feb-11e7-9489-3752fb8e99d2.png)

**Comment by markus101** [comment]
If Sonarr isn't able to match it to a series + episode(s) no download link is shown:

https://github.com/Sonarr/Sonarr/issues/395
