### ISSUE TITLE
NzbSearchService.Get<T> may populate T.SceneTitles with duplicate values

### ISSUE THREAD

**Issue by Ingramz** [Sonarr/Sonarr#2068]
I'm speaking of this method:
https://github.com/Sonarr/Sonarr/blob/db15949704d5611f1a23c47747d69f155a5cc156/src/NzbDrone.Core/IndexerSearch/NzbSearchService.cs#L231-L246

If `_sceneMapping.GetSceneNames` returns a title that is equal to `series.Title`, the final list will contain two of the same title. This will eventually mean that per each indexer there would be an extra search request taking place, which can slow things down a little.

As a potential fix I'm suggesting changing `SearchCriteriaBase.SceneTitles/QueryTitles` & related from `List<string>` to type `HashSet<string>`, to get guaranteed unique values for free, but of course there are other options.

**Comment by Taloth** [comment]
But why would GetSceneNames return the same title? after all, if it's the same then there shouldn't be need for a naming exception.

I suppose we can throw in a `Distinct` to deal with it, but if it's happening it's gonna be really rare.

**Comment by Ingramz** [comment]
If I am understanding correctly, `GetSceneNames` gets this data independently from tvdb based on it's tvdb ID and doesn't involve accessing `series.Title` in any way. So let's say GetSceneNames returns [A,B,C] and the `series.Title` is also B, which makes the final list [A,B,C,B]. The problem is not `GetSceneNames` but the blind add operation done here: https://github.com/Sonarr/Sonarr/blob/db15949704d5611f1a23c47747d69f155a5cc156/src/NzbDrone.Core/IndexerSearch/NzbSearchService.cs#L242

I am having hard time reproducing this as I don't understand where and when tvdb information is populated however I have a database that exhibits the issue, which I am willing to share in private.

**Comment by Taloth** [comment]
The names come from TheXEM and our own database (requests are listed [here](https://forums.sonarr.tv/t/scene-naming-tvdb-naming-conflicts/137) but that's not the actual database) they're manually maintained.

As such, a dupe is not gonna happen often.
