### ISSUE TITLE
Ssl support for indexers on fedora 25

### ISSUE THREAD

**Issue by fsantiago07044** [Sonarr/Sonarr#2069]
Is there anything I can do to (re)gain ssl/tls support for indexers on fedora 25 Linux? This issue with mono is really hampering my index search options.

**Comment by Taloth** [comment]
See https://github.com/Sonarr/Sonarr/issues/1928 for a workaround.

**Comment by fsantiago07044** [comment]
yep i had found that after submitting my issue. thanks. works fine now.
