### ISSUE TITLE
Sonarr does not import downloaded episode, wrong file quality detention?

### ISSUE THREAD

**Issue by ToRvaLDz** [Sonarr/Sonarr#2071]
**Sonarr version (exact version): 2.0.0.4881
OS: Windows 10**

`17-7-24 13:43:15.0|Debug|Parser|Parsing string 'Supernatural.11x16.Casa.Sicura.ITA.ENG.720pBDMux.x264-Morpheus.mkv'
17-7-24 13:43:15.0|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
17-7-24 13:43:15.1|Debug|Parser|Episode Parsed. Supernatural - S11E16 
17-7-24 13:43:15.1|Debug|Parser|Language parsed: Italian
17-7-24 13:43:15.1|Debug|QualityParser|Trying to parse quality for Supernatural.11x16.Casa.Sicura.ITA.ENG.720pBDMux.x264-Morpheus.mkv
17-7-24 13:43:15.1|Debug|Parser|Quality parsed: SDTV v1
17-7-24 13:43:15.2|Debug|Parser|Release Group parsed: Morpheus
17-7-24 13:43:15.2|Trace|ConfigService|Using default config value for 'downloadedepisodesfolder' defaultValue:''
17-7-24 13:43:15.3|Debug|Parser|Parsing string 'Supernatural.11x16.Casa.Sicura.ITA.ENG.720pBDMux.x264-Morpheus.mkv'
17-7-24 13:43:15.3|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
17-7-24 13:43:15.3|Debug|Parser|Episode Parsed. Supernatural - S11E16 
17-7-24 13:43:15.3|Debug|Parser|Language parsed: Italian
17-7-24 13:43:15.3|Debug|QualityParser|Trying to parse quality for Supernatural.11x16.Casa.Sicura.ITA.ENG.720pBDMux.x264-Morpheus.mkv
17-7-24 13:43:15.4|Debug|Parser|Quality parsed: SDTV v1
17-7-24 13:43:15.4|Debug|Parser|Release Group parsed: Morpheus
17-7-24 13:43:15.5|Debug|ImportDecisionMaker|Analyzing 1/1 files.
17-7-24 13:43:15.5|Debug|Parser|Parsing string 'Supernatural.11x16.Casa.Sicura.ITA.ENG.720pBDMux.x264-Morpheus.mkv'
17-7-24 13:43:15.5|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
17-7-24 13:43:15.5|Debug|Parser|Episode Parsed. Supernatural - S11E16 
17-7-24 13:43:15.5|Debug|Parser|Language parsed: Italian
17-7-24 13:43:15.6|Debug|QualityParser|Trying to parse quality for Supernatural.11x16.Casa.Sicura.ITA.ENG.720pBDMux.x264-Morpheus.mkv
17-7-24 13:43:15.6|Debug|Parser|Quality parsed: SDTV v1
17-7-24 13:43:15.6|Debug|Parser|Release Group parsed: Morpheus
17-7-24 13:43:15.6|Debug|ImportDecisionMaker|Size: 2045886144
17-7-24 13:43:15.7|Debug|VideoFileInfoReader|Getting media info from D:\download\transmission\completed\Supernatural.11x16.Casa.Sicura.ITA.ENG.720pBDMux.x264-Morpheus.mkv
17-7-24 13:43:15.7|Trace|MediaInfo|Read file offset 0-32768 (32768 bytes)
17-7-24 13:43:15.7|Trace|MediaInfo|Read file offset 2045760948-2045777332 (16384 bytes)
17-7-24 13:43:15.8|Trace|MediaInfo|Read file offset 2045881301-2045886144 (4843 bytes)
17-7-24 13:43:15.8|Trace|MediaInfo|Read a total of 53995 bytes (0,0%)
17-7-24 13:43:15.8|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
17-7-24 13:43:15.8|Debug|SameFileSpecification|No existing episode file, skipping
17-7-24 13:43:15.8|Debug|Parser|Parsing string 'Supernatural S11e16�[BDMux 720p - H264 - Ita Eng Ac3 - MultiSub] BDMux by Morpheus'
17-7-24 13:43:15.9|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
17-7-24 13:43:15.9|Debug|Parser|Episode Parsed. Supernatural - S11E16 
17-7-24 13:43:15.9|Debug|Parser|Language parsed: Italian
17-7-24 13:43:15.9|Debug|QualityParser|Trying to parse quality for Supernatural S11e16�[BDMux 720p - H264 - Ita Eng Ac3 - MultiSub] BDMux by Morpheus
17-7-24 13:43:15.9|Debug|Parser|Quality parsed: HDTV-720p v1
17-7-24 13:43:15.9|Debug|Parser|Release Group parsed: 
17-7-24 13:43:16.0|Debug|GrabbedReleaseQualitySpecification|Quality for grabbed release (HDTV-720p v1) does not match the quality of the file (SDTV v1)
17-7-24 13:43:16.0|Debug|Parser|Parsing string 'completed'
17-7-24 13:43:16.2|Debug|Parser|Unable to parse completed`

**Comment by Taloth** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please post support questions on the forums instead.

The release title misses a space/separator.
