### ISSUE TITLE
Magnet files causes ruTorrent to soft-crash.

### ISSUE THREAD

**Issue by supremacy2k** [Sonarr/Sonarr#2073]
Hi.

Is it possible to add an option, to choose only to use torrent files, magnet files or both?
The indexer I'm using (nyaa.si) supports both torrent and magnet files, and Sonarr grabs the magnet files, causing ruTorrent on Feralhosting to soft-crash (webui is running, but extremely lagging), and requires a reboot of the software to fix it.

This only happens with magnet files, and not torrent files.

**Comment by Taloth** [comment]
I don't see why we should add an option as workaround.  Why haven't you filed an issue with rtorrent/rutorrent? If it can't handle it then there's obviously a problem there.

**Comment by supremacy2k** [comment]
When i add magnet links manually to ruTorrent, they work fine.
I just noticed when added from sonarr, they would not update and start downloading.

So i thought an option to prefer torrent files over magnet files or vice versa, where both are available, would be nice. :)

**Comment by markus101** [comment]
No plans to add an option at this time.
