### ISSUE TITLE
Same size detection not updating file names

### ISSUE THREAD

**Issue by trg237** [Sonarr/Sonarr#2074]
I have a quite a few video files that were not marked for quality, no sonarr labeled them as hdtv-720p.  Then when I had it do an search of the files, it downloaded webdl-720p.  It does not move the downloaded file because "file size is the same". but does not update the quality of the old file.  

So could Sonarr ignore the same file size check, and move the old (but same size) file to the recycle bin and import the new one, or at least update the quality label of the old file so I know it is a web-dl and not an hdtv and rename it as well.

**Comment by markus101** [comment]
Please use the forums for support.

> but does not update the quality of the old file.

The old file is never updated, only deleted if it's importing an upgrade.

> So could Sonarr ignore the same file size check, and move the old (but same size) file to the recycle bin and import the new one, or at least update the quality label of the old file so I know it is a web-dl and not an hdtv and rename it as well.

Yes, you'll want to use Manual Import from Wanted: Missing to import the files and forcibly import the files that are the same size (and ensure the quality is detected properly).

**Comment by trg237** [comment]
Sorry about not using the forums, but I thought this may have been a bug. I
did find out I could use the manual import, but I have hundreds of files
like this and there is no list of this particular error, it just gets lost
in the "queue".  And when I do a rescan of the series, it downloads the
file again as it is not recognizing it as the higher quality to meet the
profile cutoff.  I guess this is now technically a feature request to have
a option to disable the same size check and import the file anyways
deleting/recycling the old one.  Anyways, if you want I will gladly move
this to the official forums, and thanks again for the hard work.

**Comment by markus101** [comment]
If the release is still in the queue Sonarr won't grab it again. 

Does Manual Import not work for this scenario? If Sonarr has already grabbed the hundreds of episodes with this problem, it should just be a matter of importing them via Manual Import, which as long as they are named well enough should be pretty painless.

We don't have plans to disable that check via an option, at least at this time.
