### ISSUE TITLE
Exclusion Tags for Connect Services

### ISSUE THREAD

**Issue by IchabodFletchman** [Sonarr/Sonarr#2075]
Sonarr currently supports series tags that can be used for 'Connect' services (Filter series tags).
This is good to send notifications for just a few series... but not when you want to send notifications for all series except a select few.

I have a few shows that I don't want to send notifications for, but to do this I have to open every single show in sonarr (over 500) and 'Edit Series' so I can add a comman tag, then if I exclude the shows I don't want notifications for, then I can use the 'Filter series tags'... but I won't be doing that 😉

Is it possible to add an 'Exclude series tags' to 'Connect' services, or even a way to add tags in bulk to every show (maybe with series editor)?

**Comment by markus101** [comment]
We don't have plans to support excluded tags at this time, but do plan to implement the ability to add tags to multiple series in batch. https://github.com/Sonarr/Sonarr/issues/397
