### ISSUE TITLE
Failed Download Handling should put replacement downloads on top of the queue

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#2076]
When you're downloading a season, the episodes get queued in order. If a download fails and a replacement is found, it's added at the bottom of the queue.
It would be more helpful to put it a the top instead, thus preserving the download order as much as possible.

Ref: https://www.reddit.com/r/sonarr/comments/6q0bct/nzbget_put_new_downloads_at_the_top_of_the_queue/

**Comment by qcryptic** [comment]
Should be as simple as adding `bool AddToTop` to true. https://nzbget.net/api/append

But then this would only work for nzbget also

**Comment by NerdEli** [comment]
well this got fixed lol

**Comment by bakerboy448** [comment]
for posterity: this likely won't be happening anytime soon

**Comment by markus101** [comment]
I've looked into this and being able to add something to the top of the priority is not possible for SABnzbd and nzbget's development has mostly stalled out as the original fork has been archived on github. Not going to look into this further.
