### ISSUE TITLE
"Download wasn't grabbed by Sonarr and not in a category, Skipping." when CDH is enabled

### ISSUE THREAD

**Issue by CarbonCollins** [Sonarr/Sonarr#2079]
Hi,

got an issue when manually adding files to the download client on instances where Sonarr is unable to search for downloads (unable to find the episodes due to character replacement). The download will complete correctly and Sonarr with display the download icon / purple status display for that episode however once it has completed downloading and Sonarr is ready to import it displays "Download wasn't grabbed by Sonarr and not in a category, Skipping." as well as colouring that entry orange/yellow in the activity page. It then requires manually importing. This occurs with complete download handling enabled

currently running master 2.0.0.4855

**Comment by Taloth** [comment]
> not in a category

You MUST configure a category if you want manual downloads to be processed by Sonarr automatically. This is intentional to avoid unintended processing of movie and other custom downloads.
