### ISSUE TITLE
Unable to update to 2.0.0.4892

### ISSUE THREAD

**Issue by ignoremenow** [Sonarr/Sonarr#2080]
Currently running in develop and with 2.0.0.4889 installed.

There is newer release 2.0.0.4892 available that I am unable to install. When I attempt to install it and look in the logs I see this error message

Message
`Error occurred while executing task ApplicationUpdate: attempt to write a readonly database
not an error`

Exception
`System.Data.SQLite.SQLiteException (0x80004005): attempt to write a readonly database
not an error
  at System.Data.SQLite.SQLite3.StepBackup (System.Data.SQLite.SQLiteBackup backup, System.Int32 nPage, System.Boolean& retry) [0x0007e] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteConnection.BackupDatabase (System.Data.SQLite.SQLiteConnection destination, System.String destinationName, System.String sourceName, System.Int32 pages, System.Data.SQLite.SQLiteBackupCallback callback, System.Int32 retryMilliseconds) [0x000b5] in <61a20cde294d4a3eb43b9d9f6284613b>:0 `

**Comment by Taloth** [comment]
This means Sonarr can't make the Pre-Update backup. Can you check the `/tmp/nzbdrone-backup` directory?
There are some potential causes but most likely is that the permissions are wrong for that dir, possibly created when sonarr was running as a different user, should be easy enough for you to check.

If it's there, can you rename the directory (keep it for now, coz I want to know what's different if renaming it doesn't help).

**Comment by ignoremenow** [comment]
Just to mention this I am running this on a synology box. I was able to find the directory and the perms look ok.

root@blah:/tmp/nzbdrone_backup# ps aux | grep -i mono
nzbdrone 29167  3.3 21.5 188760 110536 ?       SNl  10:57   2:17 /usr/local/mono/bin/mono --debug /volume1/@appstore/nzbdrone/share/NzbDrone/NzbDrone.exe /nobrowser /restart

root@blah:/tmp# ls -lah | grep -i nzb
drwxr-xr-x  2 nzbdrone users   80 Jul 29 10:54 nzbdrone_backup

root@blah:/tmp/nzbdrone_backup# ls -lah
total 8.0K
drwxr-xr-x  2 nzbdrone users   80 Jul 29 10:54 .
drwxrwxrwt 14 root     root  1.9K Jul 29 12:05 ..
-rw-r--r--  1 nzbdrone users  517 Jul 29 10:40 config.xml
-rw-r--r--  1 nzbdrone users 4.0K Jul 29 10:54 nzbdrone.db

**Comment by ignoremenow** [comment]
Also the last update 2.0.0.4889 - Jul 28 2017 was properly applied.

**Comment by Taloth** [comment]
Not sure, but I think the backup is trying update the existing 4K file instead of performing a full backup. Kinda weird, coz it's going fine on my ubuntu server.

Step two is to rename the directory to confirm.

**Comment by DracoMilesX** [comment]
Having the same issue as well. Except I am running it in Docker. Removed backup folder and ran the update to create the directory automatically and it fails as well with the same error. Changed permissions to 777 same issue.

**Comment by ignoremenow** [comment]
Ok moved the directory
root@blah:/tmp# ls -lah | grep -i nzbdrone_backup
drwxr-xr-x  2 nzbdrone users   80 Jul 29 10:54 nzbdrone_backup_test

ran the install and got the same error message this is what it looks like on the drive
root@blah:/tmp# ls -lah nzbdrone_backup/
total 8.0K
drwxr-xr-x  2 nzbdrone users   80 Jul 29 12:23 .
drwxrwxrwt 15 root     root  1.9K Jul 29 12:23 ..
-rw-r--r--  1 nzbdrone users  516 Jul 29 10:58 config.xml
-rw-r--r--  1 nzbdrone users 4.0K Jul 29 12:23 nzbdrone.db

**Comment by Taloth** [comment]
ok, that's a problem (am so glad now I made the sensible call to defer the planned master release)

It doesn't make sense that it would do this during a new backup. I'm gonna check a few things.

@DracoMilesX can you check the sqlite3 version in your container?

**Comment by DracoMilesX** [comment]
@Taloth Sqlite version: 3.11.0 2016-02-15 17:29:24 3d862f207e3adc00f78066799ac5a8c282430a5f

Running the linuxserver.io container

**Comment by ignoremenow** [comment]
Yeah my syno also has 3.10.2

**Comment by Taloth** [comment]
How long ago did you start with this Sonarr instance/database?

We might be onto something, but I need some things to be checked.

can you run `sqlite3 nzbdrone.db 'pragma page_size'` on the original nzbdrone database (running it separately on this mini 4K one is good to, but I need the original)

**Comment by ignoremenow** [comment]
On the original

root@blah:/volume1/@appstore/nzbdrone/var/.config/NzbDrone# sqlite3 nzbdrone.db 'pragma page_size'
1024

On the mini
root@blah:/tmp/nzbdrone_backup# sqlite3 nzbdrone.db 'pragma page_size'
4096

**Comment by M0UL** [comment]
i ran it and gives 1024

**Comment by DracoMilesX** [comment]
Have been running the docker container for 15 days.

I just did a docker pull and recreated my docker container. It reverted back to 4888 and it updates properly now.

Perhaps the 4889 fix for database backup journal handling is the issue that in sqlite 3.10 and higher the structure has changed so it gives this error?

**Comment by ignoremenow** [comment]
For me the process has been running for 1.97 hours and the uptime on syno is 14 days

**Comment by ignoremenow** [comment]
I restarted it when I put the logging into trace. Not quite sure if that is needed to get the trace logs but for some reason I always do that restart

**Comment by M0UL** [comment]
that is not needed.

**Comment by ignoremenow** [comment]
cool thanks for the info i can stop doing that now :)

**Comment by Taloth** [comment]
Tnx guys, you've been an awesome help. Based on @ignoremenow response it's very likely the page_size.
I'm already making some changes to the backup logic to fix it, but...

**Note to any guest that visits this post later, do not execute this, this is for troubleshooting and testing only**

Can you:
1) Stop Sonarr 
2) Run `sqlite3 nzbdrone.db 'pragma page_size=4096; pragma journal_mode=truncate; VACUUM;'`
3) Run `sqlite3 nzbdrone.db 'pragma page_size'` to confirm it changed.
4) Restart Sonarr
5) System->Backups->Backup

**Comment by ignoremenow** [comment]
Just to confirm you want this done on the main nzbdrone.db not the one in tmp.

**Comment by Taloth** [comment]
yes, the main one.

**Comment by ignoremenow** [comment]
Ok ran the commands. Under backups

nzbdrone_backup_2017.07.29_13.23.57.zip

**Comment by Taloth** [comment]
excellent, update should work after that. I'm almost finished with the fix too.

**Comment by ignoremenow** [comment]
Ok going to test the update.

**Comment by ignoremenow** [comment]
Yep that worked I now have 2.0.0.4892 - Jul 29 2017 installed.

**Comment by Taloth** [comment]
To everyone else, if you experience this issue and you are using Sonarr 2.0.0.4891 or 4892, then use the following process:

**These steps are _ONLY_ for develop branch users with those two versions. If you experience similar issues with other versions, post on the forums for support instead.**

1) Determine which user sonarr runs as (hint: `ps aux | grep mono`)
2) Get your AppData dir (see System->About, that's where the nzbdrone.db resides)
3) Stop Sonarr
4) Run `sqlite3 nzbdrone.db 'pragma page_size=4096; pragma journal_mode=truncate; VACUUM;'` as the right user
5) Start Sonarr

This should allow you to update to 2.0.0.4893 or higher.

PS: If you think this wasn't fun, change over to the `master` release branch in Settings->General asap. 😈

**Comment by Taloth** [comment]
@ignoremenow @DracoMilesX @M0UL Thanks again for your assistance.

**Comment by M0UL** [comment]
that worked, thanks for quick fix

**Comment by ignoremenow** [comment]
I agree with @M0UL thanks for the excellent communication and fast fix.

**Comment by ignoremenow** [comment]
Just updated to 2.0.0.4893 - Jul 29 2017 with no issues.

**Comment by Taloth** [comment]
yes, for you the issue wouldn't return coz the page size is already changed. but .4893 makes it so that it doesn't matter what the page_size is.

**Comment by jun6lee** [comment]
Seeing this with the .4927  maintenance release. Am on .4926 [on a QNAP]

**Comment by Taloth** [comment]
@jun6lee You were on  .4926 and backup failed? Coz I was fairly explicit that those instructions were only for those 4891+4892 versions. In bold no less.
Can you reproduce it by changing back the page_size to whatever it was?

**Comment by claylevering** [comment]
Gotta say, @Taloth / @M0UL / @ignoremenow killed this thread.  One google search, a page scroll and a couple of command lines and I'm back in business.  Thanks, fam!

**Comment by haudankaivajasi** [comment]
Is there any other way to run this than sqlite3? Getting "command not found" error on my Qnap and can't figure out how on earth to get it on my device.

**Comment by DracoMilesX** [comment]
@haudankaivajasi Check under /usr/bin if you can find sqlite3 if yes try to execute it as /usr/bin/sqlite3 nzbdrone.db etc... if not just try to install it/download the binary from the sqlite site and place in in the sonarr folder.

**Comment by haudankaivajasi** [comment]
@DracoMilesX Found sqlite3 under one folder and ran it from there. It worked like a charm. Thanks!

**Comment by markhaines** [comment]
Worked for me too - thanks!

**Comment by coreyallen** [comment]
I'm getting an   “unable to open database file” on my Synology when I attempt to run the fix.

**Comment by justchil** [comment]
I've been putting this issue off for months.  Now Radarr does it too after the latest update.  At some random time either Sonarr or Radarr will "crash" and start using large amounts of CPU.  I am reading this issue again to see if I missed anything.
