### ISSUE TITLE
Sub-Zero (Plex plugin) not downloading subtitles due to Sonarr permissions?

### ISSUE THREAD

**Issue by JDFS404** [Sonarr/Sonarr#2083]
Hi,

I use Sonarr to download my TV shows and CouchPotato to download my movies. Plex (via Sub-Zero plugin) is making sure the SRT's get downloaded correctly. CouchPotato is working fine in tandem with Sub-Zero, however Sonarr is not... Sub-Zero is not downloading subtitles and I think that is due to permissions issues with my Sonarr setup. Please find my Plex logs here: http://www49.zippyshare.com/v/9BfBKMDi/file.html

My permissions are set as follows:
![schermafbeelding 2017-07-31 om 13 29 45](https://user-images.githubusercontent.com/26678110/28775839-53e75c42-75f4-11e7-81e0-5174e391b432.png)

Could you please help me out? I'm at a loss and already tried the Plex forum / Sub-Zero GitHub.

**Comment by markus101** [comment]
Please use the forums for support.

Why do you think it's the file permissions that are the issue? You're probably going to get more support from the Plex forums/where ever Sub-Zero does support though.
