### ISSUE TITLE
Series Editor: Path filter

### ISSUE THREAD

**Issue by douglas24** [Sonarr/Sonarr#2085]
Please make it possible to limit displayed series within Series Editor by path (e.g. shows on drive E:\ )in addition to the current display filtering of All, Monitored Only, Continuing Only, Ended Only.

Please also make it possible to 'move files' when changing the Root Folder within Series Editor so that files don't end up orphaned on their old path and redownloaded to the new path (because currently Sonarr thinks they're missing after a path change unless you manually move the files).

**Comment by markus101** [comment]
Filtering by root folder may be possible if the server returns the root folder for the series. Moving files via the UI is in part covered by https://github.com/Sonarr/Sonarr/issues/351

**Comment by markus101** [comment]
This is done in the v3 work.
