### ISSUE TITLE
Downloading episode from wrong season

### ISSUE THREAD

**Issue by Neaox** [Sonarr/Sonarr#2086]
Sonarr keeps downloading `American.Dad.S13E17.1080p.WEB-DL.DD5.1.H.264-ViSUM` and identifying it as American Dad 14x17 as seen in the screenshot below.

![image](https://user-images.githubusercontent.com/13699847/28855479-1527b21a-7791-11e7-9b07-1710229aad4e.png)

**Comment by markus101** [comment]
Please use the forums fro support.

This particular scenario is covered in the FAQ though: https://github.com/Sonarr/Sonarr/wiki/FAQ#how-does-sonarr-handle-scene-numbering-issues-american-dad-etc

**Comment by guilhermednt** [comment]
Sorry but this IS a bug. I don't understand why people keep throwing the blame on other services.

Either fix your interface or fix the search query builder. The UI shows S14 and searches for S13. How on earth would that have anything to do with third party services?
