### ISSUE TITLE
Blacklisted Releases re-downloading

### ISSUE THREAD

**Issue by seanvree** [Sonarr/Sonarr#2087]
OS:  Windows 10E 1703 x64
 Sonarr Ver. 2.0.0.4910 develop

Just saw this start to happen recently. The blacklist seems to be not working?

Keeps downloading the same release, same indexer, same downloader. 

See screenshot. 

Blacklist on left, history on right.

Release:  United.Shades.Of.America.S02E07.Appalachian.Coal.Country.720p.HDTV.x264-YesTV

![image](https://user-images.githubusercontent.com/8906637/28856830-068304f4-76fa-11e7-9370-5b398cd2d652.png)

**Comment by markus101** [comment]
Please use the forums for support.

We'll need to know which indexer and whether you're using Jackett or NZB Hydra to connect to the indexer instead of directly to the indexer.

**Comment by seanvree** [comment]
Sorry about that @markus101  - I thought this was a legit bug. I'll get back to you with those deets on the forum.
