### ISSUE TITLE
TLS Support not available

### ISSUE THREAD

**Issue by thejase** [Sonarr/Sonarr#2092]
Since the latest update (2.0.0.4919), I am unable to get Sonarr to connect to RarBG.  The error:

```
Rarbg2 Error: ConnectFailure (TLS Support not avaiable.): "https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=Sonarr
```

Anything I could try?  I've restarted several times, but to no avail.

**Comment by Taloth** [comment]
Which OS?

**Comment by jbrodriguez** [comment]
Same here, no indexer (miatrix, nzbplanet, nzbfinder) is available

```Unable to connect to indexer: Error: ConnectFailure (TLS Support not available.): 'https://nzb.is/api?t=caps&apikey='```

```
Version
2.0.0.4919
Mono Version
4.4.2
```

macOS Sierra (10.12.6)

**Comment by Kaminogoroshi** [comment]
Windows 10

**Comment by thejase** [comment]
macOS Sierra (10.12.6)

**Comment by Taloth** [comment]
Version 2.0.0.4928 started rolling out about half an hour ago and should resolve the issue for OSX. I'll keep this issue open till confirmation. Thank you.

**Comment by jbrodriguez** [comment]
4928 fixed it for me.

**Comment by thejase** [comment]
4928 also fixed it for me. Thanks!
