### ISSUE TITLE
Unable to connect to NZBGet after update to 2.0.0.4919

### ISSUE THREAD

**Issue by Torkiliuz** [Sonarr/Sonarr#2093]
After I updated Sonarr to 2.0.0.4919 it's no longer able to connect to NZBGet. This is with the same settings as before the update. It's trying to connect to a Nginx reverse proxied NZBGet running with let's encrypt SSL certificates. It's set up to connect through SSL in Sonarr, but NZBGet in itself is not running on SSL, only the reverse proxy is; although this worked fine in the past.

[Pastebin of trace log](https://pastebin.com/18fCTMk7)

**Comment by Taloth** [comment]
It should be working again with yesterdays update 4928.

**Comment by Torkiliuz** [comment]
Yes, it works now, thanks for the quick fix 🙂
