### ISSUE TITLE
& symbol ignored in name for combined episodes being imported

### ISSUE THREAD

**Issue by douglas24** [Sonarr/Sonarr#2095]
A combined episode such as S01E01&2 is detected for import as only S01E01 instead of S01E01-E02

This occurs in the manual import function.

**Comment by markus101** [comment]
`&` is not a standard separator for multi-episode files names, we'll need more information about the filename/release name to determine if it's something we can easily support, though it may be something we don't support.

**Comment by markus101** [comment]
Closing, we can reopen if more information is available later.
