### ISSUE TITLE
Basic authentication username/password getting deleted

### ISSUE THREAD

**Issue by twhitson** [Sonarr/Sonarr#2099]
Since updating to 2.0.0.4928 from 2.0.0.4855, any time Sonarr restarts, my basic auth username and password get deleted. If I go into config.xml and set `AuthenticationMethod` to `None` and restart Sonarr, I can get back in and set the auth, but it will be deleted on the next Sonarr restart.

**Comment by markus101** [comment]
That sounds like something is auto injecting a username and password in general settings and it's being saved then on restart it takes effect. You can confirm that by going to general settings and seeing if the username/password change and if general settings are saved when you click change (without changing anything).

**Comment by twhitson** [comment]
Those steps do not reproduce the error. After clicking save without changing anything, I get prompted for login again and it works correctly. If I look at the form, it has my username filled in correctly and the password field is filled. I have my server's IP excluded from all password managers.

However, if I SSH into my server and restart Sonarr with `docker restart sonarr`, the basic auth pops up but my username and password do not work.

**Comment by markus101** [comment]
> After clicking save without changing anything, I get prompted for login again and it works correctly. 

The authentication settings don't take effect until after a restart, not sure what's prompting you after saving.

I'm not able to reproduce this. I restarted my container with basic auth enabled and my username/password set and it was the same when it came back up.
