### ISSUE TITLE
canonot add omgwtfnzbs as indexer anymore

### ISSUE THREAD

**Issue by oshimo** [Sonarr/Sonarr#2102]
Sonarr was not pulling NZBs. Went to remove and re-add omgwtfnzbs as a indexer. Now receive "No results were returned from your indexer, please check your settings."

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please use the forums for support. It appears that OMG is not returning results from their RSS feed, which is why it won't work in Sonarr currently (and why it stopped in the first place).
