### ISSUE TITLE
Enhancement: Set min file sizes by edit box, not slider (or make refuse HVEC easy)

### ISSUE THREAD

**Issue by fjones3** [Sonarr/Sonarr#2103]
Doesn't seem to be an easy way to block HVEC files, and setting minimum size with the sliders is a HUGE pain.  Can you swap those to edit boxes, and have separate ones for the "30 min file" and"60 min file" set points?

**Comment by markus101** [comment]
If you don't want HVEC releases you can block them with Indexer Settings: Restrictions (Must Not Contain). We'll be making some changes to the min size sliders in a future version though.
