### ISSUE TITLE
[Feature Request] Add button to search manually for season packs

### ISSUE THREAD

**Issue by chmercesmoreira** [Sonarr/Sonarr#2107]
![spectacle n20064](https://user-images.githubusercontent.com/20016536/29033516-afa9cca0-7b6b-11e7-9b0c-bfe74c14c928.png)

I know that Sonarr can search for season packs when clicking on the button for automatic search for a specific season but I want to be able to see the results from this search and select manually what season pack I want to grab. Is this feature already existent?

**Comment by markus101** [comment]
Please search for existing issues before posting nee ones  It doesn't exist, but there is already an issue open for it. Https://github.com/Sonarr/Sonarr/issues/266
