### ISSUE TITLE
New quality CONVERT Issue

### ISSUE THREAD

**Issue by a92nj2efnfsa** [Sonarr/Sonarr#2109]
There is a stupid new CONVERT quality being posted now which is messing up the quality profile handler in sonarr. 

**"CONVERT: Native 23.976fps source converted to 29.97fps interlaced then 29.97fps progressive. The conversions resulted in blended frames throughout preventing restoring to the native frame rate. Rule 7.7.   Additionally this cannot be converted back to original framerate without droping unique frames.....hense the CONVERT tag. This release is ment to be a crutch between HDTV and WEBRip not the final quality copy."**

So what happens is sonarr will grab a 1080p CONVERT file and think it's a 1080 so it will never upgrade to a non convert 1080 copy.

Is there plans to add this annoying quality so that Sonarr will know it needs to upgrade to a non-convert 1080p copy once available?

The only solution I have at the moment is to use an exclude tag for CONVERT but I don't like that as it might exclude things that legitimately have the word convert in it.

http://4hi.us/a/a.png

**Comment by markus101** [comment]
No plans to add a convert quality, release restrictions would be the recommendation to block it, but https://github.com/Sonarr/Sonarr/issues/385 would give more flexibility to upgrading in the future.

**Comment by a92nj2efnfsa** [comment]
If it isn't added as a quality then you block all results with the word convert in it though.

**Comment by markus101** [comment]
Preferred words won't be so black and white, take a look at the comments on that issue for more details.
