### ISSUE TITLE
Replace separator characters from series folder names to spaces when importing existing series on disk

### ISSUE THREAD

**Issue by chernoes** [Sonarr/Sonarr#2110]
If the existing series folder name contains a `.` or a `-` etc. as a separator character when using Import Existing Series On Disk, Sonarr/TheTVDB can't find the show. I suggest to replace separator characters in the series folder name with spaces when using Import Existing Series On Disk.

**Comment by markus101** [comment]
The problem is in acronyms, the periods are valid and replacing them may cause the same issue. Once we're fully using TheTVDB API v2 this should be easier for use to resolve and can be handled in Skyhook.

**Comment by markus101** [comment]
Latest skyhook changes do best effort handling of periods, underscores and dash instead of spaces.
