### ISSUE TITLE
Connection: MQTT

### ISSUE THREAD

**Issue by jormus** [Sonarr/Sonarr#2111]
hi,

Could it be possible to add support for mqtt?
That would be a great feature to get info and/or support commands that can be integrated into almost everything :-) 

Thx

**Comment by markus101** [comment]
I assume you mean: http://mqtt.org/ ? It's an interesting idea, but if we were to do it, it's not something that would be a priority for the core team.

**Comment by fortepc** [comment]
Just stopping by to throw some support to this after Googling how to do it brought me here. My personal application would be to be able to get my data into https://github.com/home-assistant/home-assistant.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
