### ISSUE TITLE
Obfuscated downloads may be incorrectly marked as Sample and not imported.

### ISSUE THREAD

**Issue by andrewmantha** [Sonarr/Sonarr#2112]
If an obfuscated download has a few specific sequences of characters (such as smpl) in the final filename, Sonarr will not automatically import it because it believes the file is a sample.

This also affects manual-automatic import as well, which is likely easier for testing. It will show the specific error on manual-manual import.

**Comment by markus101** [comment]
Sonarr uses MediaInfo and the runtime (compared to the runtime of the series) to determine if a file is a sample, it does not use part of the file name. Please open a thread on the forums with debug logs if you wish to troubleshoot this further.
