### ISSUE TITLE
Add support for CZECH Language

### ISSUE THREAD

**Issue by halali** [Sonarr/Sonarr#2113]
Hi

Please add support for czech language

Tag is CZ

Thanks

**Comment by markus101** [comment]
How are CZECH releases released? We'll need some example release and file names.

**Comment by halali** [comment]
The.​Walking.​Dead.​S07E11.​WEB Rip.​XviD.​Louige-​CZ.​EN.​5.​1 [Seriály CZ/​SK dabing]
Logan.2017.BRRip.XViD.DD5.1.CZ-BST
