### ISSUE TITLE
Add Hebrew Language

### ISSUE THREAD

**Issue by rotem925** [Sonarr/Sonarr#2115]
Please add support for Hebrew language to the profiles.
Usually it is something like this:
Smurfs.​The.​Lost.​Village.​2017.​1080p.​BluRay.​REMUX.​HebDub.​x264-​iSrael

The HebDub is what matter

**Comment by markus101** [comment]
Is the same `HebDub` used for TV show? As you refer to a movie title here.

**Comment by rotem925** [comment]
Ohh, sorry, you are right. HebDub is for movies. 
I was sure that had to like a movie.
Just checked Israeli torrent files, They put nothing there:
Metim.Lerega.S02E30.720p.HDTV.x264-Yonidan

**Comment by rotem925** [comment]
Ok,
Checked again,
If it's not an Hebrew movie that is dubbed, then HebDub is correct:

Avatar.The.Last.Airbender.S01-03.DVDRip.HebDub.

So I guess the Hebrew language just have to support HebDub
