### ISSUE TITLE
Parsing results from Jackett

### ISSUE THREAD

**Issue by bormanua** [Sonarr/Sonarr#2117]
After the last update, sonarr can't parse results from jackett.

Sonarr Version
2.0.0.4944
Mono Version
4.6.2
AppData directory
/usr/local/nzbdrone/var/.config/NzbDrone
Startup directory
/volume1/@appstore/nzbdrone/share/NzbDrone

Jackett Version 0.7.1662.0

[Screenshot from Jackett search results](http://prntscr.com/g788s6)
[season_search_error_sonarr.txt](https://github.com/Sonarr/Sonarr/files/1217890/season_search_error_sonarr.txt)

**Comment by markus101** [comment]
Parsing was not recently changed in Sonarr. Jackett appears to be cleaning up some of the title, but leaving leading spaces and a slash. In order for Sonarr to properly parse it, Jackett will need to clean that up as it's not standard to have that there.

Example: `17-8-11 15:49:50.8|Debug|Parser|Parsing string '  / The Last Ship [S01-03] (2014-2016) WEB-DLRip  Generalfilm |  | LostFilm'`

**Comment by kaso17** [comment]
@markus101 example from the torznab response:
`<title>Последний корабль / The Last Ship [S01-03] (2014-2016) WEB-DLRip от Generalfilm | КПК | LostFilm</title>`
I suspect Sonarr strips non ASCII characters causing these results?

**Comment by markus101** [comment]
Either that or the logger does (not sure offhand). The issue is still present though since the title is still messed up by the prefix to it.

**Comment by Taloth** [comment]
I wonder of all rutorrent releases are like that, with 'russian title / english title'.
It doesn't look like a ReleaseTitle, but rather the generated name on the tracker.

**Comment by kaso17** [comment]
that's probably the core problem (lack of proper release names)
