### ISSUE TITLE
Scene Mappings with some FilterRegex don't work for imports

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#2118]
Release name: `Criminal Minds E05 1080p-NEXT` 
File name: `Criminal Minds E05 1080p-NEXT.mp4`

When `_sceneMappingService.FindSceneMapping(parsedEpisodeInfo.SeriesTitle, parsedEpisodeInfo.ReleaseTitle)` is called from `ParsingService` `parsedEpisodeInfo.ReleaseTitle` contains the extension as well as the release name, this means a `FilterRegex` of `-NEXT$` fails.

Should we be stripping the extension from the ReleaseTitle when parsing?

**Comment by Taloth** [comment]
But for ReleaseTitle we already [strip out](https://github.com/Sonarr/Sonarr/blob/766520b851bbadf325a73139a1643c4d050db4a0/src/NzbDrone.Core/Parser/Parser.cs#L319) the extension.
It just gets passed incorrectly [here](https://github.com/Sonarr/Sonarr/blob/766520b851bbadf325a73139a1643c4d050db4a0/src/NzbDrone.Core/Parser/Parser.cs#L358).

Gotta tread carefully there coz I do recall some significance of title vs simpleTitle vs releaseTitle.
