### ISSUE TITLE
RSS parsing fails on lowercase pubdate

### ISSUE THREAD

**Issue by dsc0815** [Sonarr/Sonarr#2120]
If a tracker uses a lowercase "pubdate", it does not match "pubDate" in the RssParser due to the case sensitive nature of XML. This is of course true for any tag using a different character casing.

Proposed change: Optional ignoreCase parameter in XElementExtension.TryGetValue.

**Comment by Taloth** [comment]
Wouldn't it be more appropriate to get the tracker to fix their feed? Coz that's obviously the actual issue and shouldn't be ours to fix.

**Comment by dsc0815** [comment]
Of course I ran into this issue on a particular tracker and they should be aware of it by now.

The case-sensitivy seems unnecessarily strict, though. Are there any tags that could only be distinguished by their character-casing? The performance hit to allow different character-cases would only be marginal, as most feeds (probably) conform to the RSS standard.

Seeing that this might be an (unnoticed) issue with other feeds, too, this could be an easy fix to avoid it altogether.

**Comment by Taloth** [comment]
My point is that it's wrong: The RSS standard specifies these attributes and it's case-sensitive. Feeds should conform to the rss standard, period.
Adjusted feed readers to handle it is the wrong approach coz it encourages non-conformity. (After all, why fix the feed if readers accept it, or worse: copy pasta from an already bad implementation)

There 'might' be other feeds with the issue, there might not. But those feeds will quite possibly run into issues with other rss readers. So having as many readers reject lower case 'pubdate' is the best thing you can possibly do, coz it alerts sites to their non-conformity allowing them to fix it.

**Comment by dsc0815** [comment]
I can live with that. Thanks!
