### ISSUE TITLE
how to change the limit=100 parameter to torznab requests ?

### ISSUE THREAD

**Issue by lrnv** [Sonarr/Sonarr#2125]
Hi !! 
I'm using sonarr with jackett's agregate feed, and this limit=100 parameter tricks me. I'd like to change it to a (much) bigger value, how can i do that ? 

Linking with my post on jackett's github : https://github.com/Jackett/Jackett/issues/1661

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by Taloth** [comment]
I strongly dislike cross-posts, you unnecessarily attract the attention from two dev teams and waste our time. Once the Jackett team can't answer you question, they can always ping us.

**Comment by lrnv** [comment]
Ok i unclose since we understoo that the issue stay's in raarr code and not in jackett's. 

The issue is : How can i set torznab parameter "limit" (which is setted up to "100" by default) while registering a new torznab indexer in sonarr ? (same in radarr, but i'm not gonna cros-post this time...)

**Comment by Ornias1993** [comment]
@Taloth Maybe your personal preference for form, shouldn't dictate if a (otherwise valid) issue gets close.

It's agressive, and arrogant.
