### ISSUE TITLE
Sonarr not respecting TMPDIR properly

### ISSUE THREAD

**Issue by aaronson2012** [Sonarr/Sonarr#2126]
Hello,

I have discovered an issue where sonarr is not respecting a cusom set TMPDIR properly. If you set TMPDIR to $HOME/.tmp, Sonarr interprets it as the literal string, and fails because that is not a valid path. However, if you set TMPDIR as a path while referencing no variables, it works as intended.

Thank you devs!

**Comment by aaronson2012** [comment]
I have something new to report. Lately I've been experianceing a new error. If you define a custom TMPDIR the update process almost finishes but fails at the end.

Here is what I get:

`[Info] InstallUpdateService: Deleting old update files
[Info] InstallUpdateService: Downloading update 2.0.0.4951
[Info] InstallUpdateService: Verifying update package
[Info] InstallUpdateService: Update package verified successfully
[Info] InstallUpdateService: Extracting Update package
[Info] InstallUpdateService: Update package extracted successfully
[Info] BackupService: Starting Backup
[Info] InstallUpdateService: Preparing client
[Info] InstallUpdateService: Starting update client /tmp/nzbdrone_update/NzbDrone.Update.exe
[Info] InstallUpdateService: Sonarr will restart shortly.
[Error] CommandExecutor: Error occurred while executing task ApplicationUpdate

[v2.0.0.4950] System.ComponentModel.Win32Exception (0x80004005): ApplicationName='mono', CommandLine='--debug /tmp/nzbdrone_update/NzbDrone.Update.exe 5124 /tmp/nzbdrone_update /mnt/mpatht/aaronson2012/programs/NzbDrone/NzbDrone.exe ', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0018b] in /mnt/mpatht/aaronson2012/mono-4.8.0/mcs/class/System/System.Diagnostics/Process.cs:737`

Please note my TMPDIR is not /tmp/ but is /home/aaronson2012/.tmp/

Its trying to execute a file from /tmp/ when it shouldn't

Thanks.

**Comment by markus101** [comment]
I'm not able to reproduce this issue with mono 4.8.0.

I set it with `export TMPDIR=$HOME/temp` and Sonarr properly updated using `/root/temp` (using the mono 4.8.0 docker image for testing: https://hub.docker.com/_/mono/)

**Comment by aaronson2012** [comment]
Very strange.......

I guess I'll have to figure out what's causing it for me then...

Thanks anyway.

**Comment by aaronson2012** [comment]
I figured out my issue. I just upgraded mono from 4.8.0 to 5.4.0.56.

Thanks!
