### ISSUE TITLE
Sonarr Copying instead of Moving Files, even though Torrent is "Completed" in qBittorrent 3.3.11

### ISSUE THREAD

**Issue by jeff15110168** [Sonarr/Sonarr#2128]
As the title says, Sonarr is continuing to copy files resulting in duplicate files in the download folder path set by Qbittorrent ("QBT") and where plex reads the media files (same disk).

I have rules set up for the Sonarr to explicitly stop seeding certain files after downloading (0.00 seed ratio rule). I also have tried manually pausing a torrent while it is tagged as Sonarr, and even downloading a tv series untagged, paused it once its finished downloading then added the Sonarr label and it still is copying files instead of moving them. This used to work just fine, as Sonarr/Radarr both use complete downloading handling and do not use the deprecated drone watch folder feature.

This issue also seems to be plaguing radarr as well, though i haven't downloaded enough movies in past week to know for sure. Below is what may be some relevant code from the regular log file. I just enabled debug and will see if that provides more info after a new tv series i just snatched is completed.

> 17-8-14 19:38:21.1|Warn|EpisodeFileMovingService|Unable to set last write time
> 
> [v2.0.0.4949] System.IO.IOException: The process cannot access the file 'Z:\TV\[Snatched TV Show]' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.Directory.OpenHandle(String path)
>    at System.IO.Directory.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
>    at NzbDrone.Common.Disk.DiskProviderBase.FolderSetLastWriteTime(String path, DateTime dateTime) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 255
>    at NzbDrone.Core.MediaFiles.MediaFileAttributeService.SetFolderLastWriteTime(String path, DateTime time) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\MediaFileAttributeService.cs:line 75
>    at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile(EpisodeFile episodeFile, Series series, List`1 episodes, String destinationFilePath, TransferMode mode) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 126
> 
> 17-8-14 19:38:44.3|Warn|EpisodeFileMovingService|Unable to set last write time
> 
> [v2.0.0.4949] System.IO.IOException: The process cannot access the file 'Z:\TV\[Snatched TV Show]' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.Directory.OpenHandle(String path)
>    at System.IO.Directory.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
>    at NzbDrone.Common.Disk.DiskProviderBase.FolderSetLastWriteTime(String path, DateTime dateTime) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 255
>    at NzbDrone.Core.MediaFiles.MediaFileAttributeService.SetFolderLastWriteTime(String path, DateTime time) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\MediaFileAttributeService.cs:line 75
>    at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile(EpisodeFile episodeFile, Series series, List`1 episodes, String destinationFilePath, TransferMode mode) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 126
> 
> 17-8-14 19:39:18.6|Warn|EpisodeFileMovingService|Unable to set last write time
> 
> [v2.0.0.4949] System.IO.IOException: The process cannot access the file 'Z:\TV\[Snatched TV Show]' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.Directory.OpenHandle(String path)
>    at System.IO.Directory.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
>    at NzbDrone.Common.Disk.DiskProviderBase.FolderSetLastWriteTime(String path, DateTime dateTime) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 255
>    at NzbDrone.Core.MediaFiles.MediaFileAttributeService.SetFolderLastWriteTime(String path, DateTime time) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\MediaFileAttributeService.cs:line 75
>    at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile(EpisodeFile episodeFile, Series series, List`1 episodes, String destinationFilePath, TransferMode mode) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 126
> 
> 17-8-14 19:39:58.3|Warn|EpisodeFileMovingService|Unable to set last write time
> 
> [v2.0.0.4949] System.IO.IOException: The process cannot access the file 'Z:\TV\[Snatched TV Show]' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.Directory.OpenHandle(String path)
>    at System.IO.Directory.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
>    at NzbDrone.Common.Disk.DiskProviderBase.FolderSetLastWriteTime(String path, DateTime dateTime) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 255
>    at NzbDrone.Core.MediaFiles.MediaFileAttributeService.SetFolderLastWriteTime(String path, DateTime time) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\MediaFileAttributeService.cs:line 75
>    at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile(EpisodeFile episodeFile, Series series, List`1 episodes, String destinationFilePath, TransferMode mode) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 126
> 
> 17-8-14 19:40:20.5|Warn|EpisodeFileMovingService|Unable to set last write time

Any help is greatly appreciated.

**Comment by jeff15110168** [comment]
> 17-8-14 21:23:24.6|Debug|Parser|Parsing string 'The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv'
> 17-8-14 21:23:24.6|Debug|Parser|Episode Parsed. The Strain - S04E03 
> 17-8-14 21:23:24.6|Debug|Parser|Language parsed: English
> 17-8-14 21:23:24.6|Debug|QualityParser|Trying to parse quality for The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv
> 17-8-14 21:23:24.6|Debug|Parser|Quality parsed: WEBDL-1080p v1
> 17-8-14 21:23:24.6|Debug|Parser|Release Group parsed: PSA
> 17-8-14 21:23:24.6|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (11 ms)
> 17-8-14 21:24:54.6|Debug|Parser|Parsing string 'SpongeBob SquarePants (1999-2015) [480p] [720p] [HEVC] [x265]'
> 17-8-14 21:24:54.6|Debug|Parser|Unable to parse SpongeBob SquarePants (1999-2015) [480p] [720p] [HEVC] [x265]
> 17-8-14 21:24:54.6|Debug|Parser|Parsing string 'The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv'
> 17-8-14 21:24:54.6|Debug|Parser|Episode Parsed. The Strain - S04E03 
> 17-8-14 21:24:54.6|Debug|Parser|Language parsed: English
> 17-8-14 21:24:54.6|Debug|QualityParser|Trying to parse quality for The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv
> 17-8-14 21:24:54.6|Debug|Parser|Quality parsed: WEBDL-1080p v1
> 17-8-14 21:24:54.7|Debug|Parser|Release Group parsed: PSA
> 17-8-14 21:24:54.7|Debug|TrackedDownloadService|Tracking 'qBitTorrent:The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv': ClientState=Completed (readonly) SonarrStage=Downloading Episode='The Strain - S04E03 WEBDL-1080p v1' OutputPath=H:\Downloads\Sonarr\The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv.
> 17-8-14 21:24:54.7|Debug|Parser|Parsing string 'The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv'
> 17-8-14 21:24:54.7|Debug|Parser|Episode Parsed. The Strain - S04E03 
> 17-8-14 21:24:54.7|Debug|Parser|Language parsed: English
> 17-8-14 21:24:54.7|Debug|QualityParser|Trying to parse quality for The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv
> 17-8-14 21:24:54.7|Debug|Parser|Quality parsed: WEBDL-1080p v1
> 17-8-14 21:24:54.8|Debug|Parser|Release Group parsed: PSA
> 17-8-14 21:24:54.8|Debug|ImportDecisionMaker|Analyzing 1/1 files.
> 17-8-14 21:24:54.8|Debug|Parser|Parsing string 'The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv'
> 17-8-14 21:24:54.8|Debug|Parser|Episode Parsed. The Strain - S04E03 
> 17-8-14 21:24:54.8|Debug|Parser|Language parsed: English
> 17-8-14 21:24:54.8|Debug|QualityParser|Trying to parse quality for The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv
> 17-8-14 21:24:54.8|Debug|Parser|Quality parsed: WEBDL-1080p v1
> 17-8-14 21:24:54.8|Debug|Parser|Release Group parsed: PSA
> 17-8-14 21:24:54.8|Debug|ImportDecisionMaker|Size: 470411757
> 17-8-14 21:24:54.8|Debug|VideoFileInfoReader|Getting media info from H:\Downloads\Sonarr\The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv
> 17-8-14 21:24:54.9|Debug|SameFileSpecification|No existing episode file, skipping
> 17-8-14 21:24:54.9|Debug|Parser|Parsing string 'The Strain S04E03 One Shot 1080p WEBRip 6CH x265 HEVC PSA mkv'
> 17-8-14 21:24:54.9|Debug|Parser|Episode Parsed. The Strain - S04E03 
> 17-8-14 21:24:54.9|Debug|Parser|Language parsed: English
> 17-8-14 21:24:54.9|Debug|QualityParser|Trying to parse quality for The Strain S04E03 One Shot 1080p WEBRip 6CH x265 HEVC PSA mkv
> 17-8-14 21:24:54.9|Debug|Parser|Quality parsed: WEBDL-1080p v1
> 17-8-14 21:24:54.9|Debug|Parser|Release Group parsed: 
> 17-8-14 21:24:54.9|Debug|Parser|Parsing string 'Sonarr'
> 17-8-14 21:24:54.9|Debug|Parser|Unable to parse Sonarr
> 17-8-14 21:24:54.9|Debug|VideoFileInfoReader|Getting media info from H:\Downloads\Sonarr\The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv
> 17-8-14 21:24:54.9|Debug|DetectSample|Runtime is over 90 seconds
> 17-8-14 21:24:55.0|Debug|Parser|Parsing string 'The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA'
> 17-8-14 21:24:55.0|Debug|Parser|Episode Parsed. The Strain - S04E03 
> 17-8-14 21:24:55.0|Debug|Parser|Language parsed: English
> 17-8-14 21:24:55.0|Debug|QualityParser|Trying to parse quality for The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA
> 17-8-14 21:24:55.0|Debug|Parser|Quality parsed: WEBDL-1080p v1
> 17-8-14 21:24:55.0|Debug|Parser|Release Group parsed: PSA
> 17-8-14 21:24:55.0|Debug|EpisodeFileMovingService|Copying episode file: H:\Downloads\Sonarr\The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv to H:\Media\TV Shows\The Strain\Season 04\The Strain - S04E03 - One Shot [WEBDL-1080p].mkv
> 17-8-14 21:24:55.0|Debug|DiskTransferService|Copy [H:\Downloads\Sonarr\The.Strain.S04E03.One.Shot.1080p.WEBRip.6CH.x265.HEVC-PSA.mkv] > [H:\Media\TV Shows\The Strain\Season 04\The Strain - S04E03 - One Shot [WEBDL-1080p].mkv]
> 17-8-14 21:25:17.7|Debug|UpdateEpisodeFileService|Date of file [H:\Media\TV Shows\The Strain\Season 04\The Strain - S04E03 - One Shot [WEBDL-1080p].mkv] changed from '8/15/2017 1:24:31 AM' to '7/31/2017 2:00:00 AM'
> 17-8-14 21:25:17.7|Debug|MediaFileAttributeService|Setting last write time on series folder: H:\Media\TV Shows\The Strain
> 17-8-14 21:25:17.7|Debug|MediaFileAttributeService|Setting last write time on series folder: H:\Media\TV Shows\The Strain\Season 04
> 17-8-14 21:25:17.8|Debug|EpisodeService|Linking [Season 04\The Strain - S04E03 - One Shot [WEBDL-1080p].mkv] > [[4556]One Shot]
> 17-8-14 21:25:17.8|Debug|NotificationService|No tags set for this notification.
> 17-8-14 21:25:18.0|Debug|NotificationService|No tags set for this notification.
> 17-8-14 21:25:18.0|Debug|PlexServerService|Sending Update Request to Plex Server
> 17-8-14 21:25:18.0|Debug|PlexServerService|Getting sections from Plex host: 192.168.0.185
> 17-8-14 21:25:18.0|Debug|X509CertificateValidationPolicy|Certificate validation for https://192.168.0.185:32400/library/sections failed. RemoteCertificateNameMismatch
> 17-8-14 21:25:18.1|Debug|PlexServerService|Getting metadata from Plex host: 192.168.0.185 for series: [276564][The Strain]
> 17-8-14 21:25:18.1|Debug|PlexServerService|Updating Plex host: 192.168.0.185, Section: 2, Series: [276564][The Strain]
> 17-8-14 21:25:22.5|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (10 ms)
> 17-8-14 21:25:27.6|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (24 ms)
> 17-8-14 21:26:03.2|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (15 ms)
> 17-8-14 21:26:06.3|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (8 ms)

**Comment by markus101** [comment]
Sonarr relies on either:

`max_ratio_enabled` being false _OR_ `max_ratio` being less than the torrent ratio

_AND_

The torrent state being `pausedUP` (uploading but paused).

If those cases are not being met then it will copy/hardlink not move. Trace logs may give you the details when Sonarr fetches the queue from QBit and testing the Qbit connection from within Sonarr will fetch the config, which may also be logged (offhand I'm not sure if it is).

Please open a thread on the forums to troubleshoot further if required.
