### ISSUE TITLE
Import not creating hardlinks as expected

### ISSUE THREAD

**Issue by jtpavlock** [Sonarr/Sonarr#2129]
With the create hardlinks feature on, sonarr is still copying files instead of hardlinking them (as shown by the number of links in ls -l).

Now, if I manually hardlink using the same directory set 

`ln /downloads/example_file /tv/season/example_file`

it works as expected and creates the hardlink. 

I tried to look at log files, but did not see anything related to importing. 

Running version 2.0.0.4949 on Debian under docker.

**Comment by Taloth** [comment]
Did you run `ln` inside the docker container?

**Comment by jtpavlock** [comment]
Ha, silly mistake on my part. I use mergerfs which has it's own way of dealing with hardlinks, but the issue was I wasn't exposing the entire data pool to sonarr, only certain folders so mergerfs couldn't do it's magic inside the container properly. Good it working now :) sorry about that.

**Comment by chriswiduta** [comment]
How did you implement this fix @jtpavlock ?

**Comment by jtpavlock** [comment]
@chriswiduta mounted all of my data drives to the docker container (in my case I had them under `/mnt/tank`) rather than just the tv folder which was `/mnt/tank/tv`

**Comment by jonatronnn** [comment]
@jtpavlock are you using the linuxserver/sonarr container? 

I am running into this hardlinking issue on my system (also using MergerFS/containers for everything)

I am unsure as to how you go about providing this container only one mount point and having the correct downloads/tv folders selected?

**Comment by jtpavlock** [comment]
Maybe this will help, I use docker compose and these are the volumes that I mount

                 volumes:
                         - /opt/appdata/sonarr:/config
                         - /mnt/tank/:/data
                         - /etc/localtime:/etc/localtime:ro

I then select the proper folders with data/ within sonarr itself

**Comment by jonatronnn** [comment]
Brilliant, thanks I'll give that a go.

What create polices/run options do you use with MergerFS?

I did a bit of reading that indcated using a non-path preserving create policy and ignorepponrename=true would help when using hardlinks.

**Comment by jtpavlock** [comment]
/mnt/disk* /mnt/tank fuse.mergerfs defaults,allow_other,direct_io,use_ino,category.create=mfs,minfreespace=50G,fsname=tank 0 0

**Comment by jonatronnn** [comment]
Up and running with what seem to be working hardlinks with my Deluge/Sonarr containers, thanks very much for the information!
