### ISSUE TITLE
Change Deluge label if file no longer exists in library

### ISSUE THREAD

**Issue by jtpavlock** [Sonarr/Sonarr#2130]
I'm not sure how the Deluge label plugin fully works, but I hope this is feasible. 

**Feature**
I am specifically asking for the ability for Sonarr to change a file's label in Deluge if that file no longer exists in Sonarr's database (usually due to an explicit removal in Sonarr or an automatic quality/profile upgrade). 

**Use Case**
Changing the label would allow me to automatically apply stricter seeding policies rather than permaseeding as those files are now taking up precious space I like to reserve for my media. 

Obviously this is for those who copy/hardlink to their collections from the download folder rather than moving (and removing from downloads).

**Comment by markus101** [comment]
I don't see this being something we want to integrate. It's specific to your scenario and could easily be complicated by Sonarr losing track of a file or it being renamed outside of Sonarr. A custom script could be used on import to deal with changing the labels for upgrades. I'd be weary to add a custom script being executed on delete in case it triggers when Sonarr loses track of the file for another reason.

Some ratio management would come with: https://github.com/Sonarr/Sonarr/issues/1854 though not specific to deleted files.
