### ISSUE TITLE
Size refresh

### ISSUE THREAD

**Issue by hugolapointe** [Sonarr/Sonarr#2132]
Little bug,

When a serie is refresh, the size occupied by the serie on the disk isn't updated in the info header of the serie. I try to clear cache/cookie, and that didn't do anything.

Thank you!

**Comment by markus101** [comment]
> When a serie is refresh, the size occupied by the serie on the disk isn't updated in the info header of the serie.

Did the size on disk actually change? Does it change on refresh?

> I try to clear cache/cookie, and that didn't do anything.

That information isn't cached, sounds like it's just not being re-rendered when that changes.

**Comment by markus101** [comment]
This is taken care of in the v3 work.
