### ISSUE TITLE
Torznab - Search for Freeleech only

### ISSUE THREAD

**Issue by antigravity83** [Sonarr/Sonarr#2138]
Hi,

I'd like to set my Jackett API's to search Freeleech content only.

I can see there's a "downloadvolumefactor" attribute, which when set to 0 will apparently only search Freeleech content- but unsure how to implement it in the Torznab Indexer settings?

Thanks

**Comment by markus101** [comment]
Is that supposed to be set in Sonarr;s settings or something that is set in Jackett?

Sonarr will append the `Additional Parameters` to query string when sending a request, so if that's how Jackett expects it, you could do `&downloadvolumefactor=0` and Sonarr will append it, beyond that it be best to follow up with with Jackett directly.

**Comment by antigravity83** [comment]
Sonarr has a field for "Additional Parameters", and downloadvolumefactor" is an official Torznab additional parameter- so one would assume you could use this somehow in the Sonarr Additional Parameters field?

If not- what are some of the additional parameters that can be used in Sonarr? I've only found four, and all of them are in the same format, and similar use case to the "downloadvolumefactor" parameter.

**Comment by antigravity83** [comment]
Just tried your suggestion- unfortunately doesn't work. Results return non-free leech results.

**Comment by markus101** [comment]
> Sonarr has a field for "Additional Parameters"

Yes.

> and downloadvolumefactor" is an official Torznab additional parameter

It's a attribute that the Torznab server (Jackett in this case) can return. I don't know whether Jackett accepts it as a parameter for RSS/search.

> Otherwise, what is the "Additional Paramater" field for?

Appending additional parameters to the request to the indexer, such as:

![image](https://user-images.githubusercontent.com/413544/29484125-f618df78-846c-11e7-8541-5cea5bf780c9.png)
(taken from a newznab indexer, which torznab is based on)

> Just tried your suggestion- unfortunately doesn't work. Results return non-free leech results.

Best to ask Jackett if they even support limited results that way, you can verify that Sonarr is sending it in the debug logs, but it'd be up to Jackett to filter out results (if that's something they want to do).

**Comment by antigravity83** [comment]
Ok great thanks for the detailed response. Will hvae a chat with Jackett to see what they say.

**Comment by Taloth** [comment]
downloadvolumefactor is an attribute, a property of the release.
Nowhere in the torznab specification does it mention that the attribute must be queryable.

Furthermore, this is a direct duplicate of https://github.com/Sonarr/Sonarr/issues/1882
