### ISSUE TITLE
Monitoring future episodes results in all of last season to be monitored

### ISSUE THREAD

**Issue by desimaniac** [Sonarr/Sonarr#2139]
When using Season Pass to change the show's monitoring to "Future Episodes", it ends up monitoring the entire last season.

![image](https://user-images.githubusercontent.com/5501908/29483420-9a3e51ca-846b-11e7-9f67-d394343c51a3.png)

![image](https://user-images.githubusercontent.com/5501908/29483422-a6e90122-846b-11e7-8ced-cb7001c0aacc.png)

![image](https://user-images.githubusercontent.com/5501908/29483428-b7f2c75a-846b-11e7-9e47-eafa6772480e.png)

Sonarr Ver. 2.0.0.4951
develop

**Comment by markus101** [comment]
I can't reproduce this behaviour when selecting `Future`, but selecting `Latest Season` gives me this result (though that's expected).

We'll need debug logs of you changing it via Season Pass to investigate further.

**Comment by desimaniac** [comment]
The debug logs: https://gist.github.com/desimaniac/42a9e545793e1ecd15b5325b5ea9f09f

**Comment by markus101** [comment]
Same output as I'm seeing.

Are other seasons being updated properly?

**Comment by desimaniac** [comment]
I'll check

**Comment by desimaniac** [comment]
Just tested on GOT. Same issue. I first went to season pass and set it to Unmonitor - All. Then did Monitor-Future, and it selected the entire last season (S6).

**Comment by desimaniac** [comment]
Sent a message to you on discord just now.
