### ISSUE TITLE
uTorrent and sonarr are not in sync when using destination sub-folders for series (default)

### ISSUE THREAD

**Issue by rafi-d** [Sonarr/Sonarr#2143]
Hi,
There is this files-sync problem (might has been reported in the past): 
1. Due to uT WebUI API limitation,  there is no way to specify the exact download location, such as a series sub-folder name, so, sonarr is using the uT default download path. This is a problem since all series are now all inter-mixed in the same root.
2. To "solve" this, sonarr provided a "Completed download handling" feature, that seems to import the downloaded file to another location. In my case - this a a sub-folder under that same default root path, and it is being *moved* their.
3. the problem resulted in #2 - seems to be that the uT client looses sync with that file, maybe even stops seeding.
4. There is another option - NOT to "handle" completed downloads in sonarr... This is leaving the user with a bad state, when all files are under the same path

I like to propose a solution (work-around) to that issue as follows:

0. Disable using of "Completed download handling" in Sonarr.
1. uTorrent  user will be advised to use uTorrent client features: "move completed download to" PLUS  "auto-append label" in torrent (see attached.). This might be available for other clients too (label==category).
2. In sonarr, for that to be useful,  there is only small fix required: In the Downloading Client settings->Category field - make it so that the user can specify also "{Series Title}", exactly like you do in Media Management-> Series Folder Format!
3. If you like to improve a bit on 2 above - make it so users could specify more the one category (like tags), something like: "{Series Title}, tv-sonarr" 
4. In the download processing/monitoring, after you Add that torrent job, you will also use the WebUI several times to add *ALL* categories/labels to that job. The first one should be used as the intended destination folder name.
5. After the download is complete, the files will be moved by the client. Sonarr will then have to do an additional scan of his  own destination folder (or that first category, which should be the same name). This way it will re-scan tit sub-folder, so to re-sync to the file moved by the uT client.

Seems pretty simply to me, and I hope helpful for you to fix that issue.

Thanks!

Rafi

![1](https://user-images.githubusercontent.com/2458280/29516047-92983b62-8677-11e7-8d62-4e4d30457164.png)

**Comment by Thirrian** [comment]
Looks like you're using your download client to sort (rename, move) files.
Sonarr is built around the idea that it is in control of sorting the files.

**Comment by rafi-d** [comment]
When you deal with any P2P client, the community's best interest is that you seed as much as possible. How can you accomplish that when Sonarr moves away (detach) files from it ? 

Anyways' my suggestion is to just add a dynamic/flexible category (like you do in media management) + a short scan. As simple as that. Users can still use it as it is today if they like.

**Comment by Thirrian** [comment]
You can have sonarr hardlink the files so you can continue seeding :)
Media Management --> (enable advanced settings) --> "Use Hardlinks instead of Copy" under the "Importing" header.

**Comment by rafi-d** [comment]
Well, yes, but due to the  limitation of uT WebUI, sonarr will still put EVERYTHING under one root, right ? This is definitely not something you want to have as your library for any player/Client...

**Comment by Thirrian** [comment]
> This is definitely not something you want to have as your media library for any player/Client...

No, but you'll have this issue with any download client if you point your media player to what is basically your downloads folder.
You should have e.g. X:\Series to use as a root folder in sonarr, so it can move/rename files there, and then point your media player to X:\Series to find files to play. Your download client need not be aware or do anything with X:\Series.

**Comment by markus101** [comment]
Sonarr relies on sorting downloads to the series folders on it's own, for torrent clients it does that via Hardlinking or Copying (depending on your settings/system), which will continue to seed (and hardlinking uses no extra disk space).

We do not have plans to support a label/category per series. Sonarr relies on sorting files when a file has finished so it can mark the episode as complete and no longer missing/downloading. You can have Sonarr not process completed downloads by disabling Completed Download Handling (and you should never use Drone Factory with torrents), but that will prevent Sonarr from seeing completed files until it does a disk rescan and will only see the files if the series folder Sonarr is aware of has the file.

A script executed by uTorrent could be used to tell Sonarr to scan a series folder using Sonarr's API when a download is complete. You could also use a custom script in Sonarr could be used to set the label in uTorrent to the series title.

**Comment by rafi-d** [comment]
Thanks for the feedback. I guess I'd need to learn about APIs to use in a uT script, and how to use Sonarr scripts... I was thinking this would be minimal effort, since {Series Title} format is already being used  in the Media Management tab :)

**Comment by markus101** [comment]
There are several issues with it:

- Not all clients support dynamically created categories/labels
- Not all clients allow multiple labels per item (which leads into the next point)
- Sonarr uses the category to filter things it doesn't care about, either when getting the list of downloads (preferred) or once it retrieves the list, anything dynamic wouldn't work for filtering when getting the list because it could be hundreds of API calls with 0 or more results and filtering after fetching would require each item to be parsed to see if the label matches something Sonarr knows about, which doesn't happen until later in the process, which would make it into a giant mess of spaghetti code

**Comment by rafi-d** [comment]
Well, I was referring only to uT. I thought the client configuration-setting dialog can be designed per client. Since  uT does support multi-dynamic-labels, I guess most of the above mentioned obstacles can be avoided. 
Maybe you can allow (only for uT) something like:  {Series Title}|<"user label">, tv-sonarr ... 

Anyways, I guess it might be easier for me/users to use uT RSS-downloader than develop scripts... 

Thanks
