### ISSUE TITLE
Option to force stop downloading other qualities

### ISSUE THREAD

**Issue by lifeofguenter** [Sonarr/Sonarr#2144]
unfortunately the quality parser is not good, so many times a episode gets downloaded multiple times (same quality / different release).

There should be an option to never download a episode (maybe except for the tag proper/fix) again once done.

**Comment by markus101** [comment]
> unfortunately the quality parser is not good

How so? We're going to need examples if we're going to improve it, please open a thread on the forums with information and we can troubleshoot further.

> There should be an option to never download a episode (maybe except for the tag proper/fix) again once done.

We do not have plans for a grab once and ignore the result/never upgrade. If the quality parsing doesn't work grabbing a fix/proper wouldn't be reliable anyways.

**Comment by lifeofguenter** [comment]
Why are there no plans to implement it?

**Comment by markus101** [comment]
Actually, I misspoke, we've had some conversation on it here: https://github.com/Sonarr/Sonarr/issues/426

Some concrete information on where the quality parsing is breaking down would be useful though, since not upgrading isn't going to work for everyone.
