### ISSUE TITLE
Not waiting long enough for indexer to return

### ISSUE THREAD

**Issue by francis-io** [Sonarr/Sonarr#2145]
I'm using the docker containers linuxserver/sonarr and linuxserver/jackett on the latest version.

I have confirmed the Jackett API is returning results from within the sonarr container (I can curl it and eventually return results) but it takes around **20-40s to return**. I'm running the following inside the sonarr container:

```
curl http://jackett:9117/torznab/all?apikey=<APIKEY>
```
Which I can confirm returns results.

Inside the sonarr web gui I have the following set:

![selection_005](https://user-images.githubusercontent.com/10199020/29567003-c3a497c4-8743-11e7-9e7c-b1c895cbe48d.png)

It returns the error "No results were returned from your indexer, please check your settings." within a few seconds, which seems to not wait long enough for the API to return.

If I'm right in my assumption that it's not waiting long enough for a response, is it possible for me to increase this?

**Comment by markus101** [comment]
The timeout is much longer than a few seconds.

> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please open a thread on the forums for support, we'll need debug logs as well as the other requested information.
