### ISSUE TITLE
How To Stop Auto Downloading 

### ISSUE THREAD

**Issue by Comfubar** [Sonarr/Sonarr#2147]
I just recently started to use Sonarr and Radarr Ive noticed that my Sonarr is auto starting my downloads in QBtorrent when i have QB set to once added pause them and no auto downloading so it gives me more control on when i start them 

What do i have to change to have Sonarr not auto download on me ?

**Comment by Saiboogu** [comment]
In the download client settings, "Add paused" ?

**Comment by markus101** [comment]
Sonarr doesn't current start the torrent, it just adds the torrent. It sounds like Qbit doesn't enforce that setting when torrents are added through the API.

**Comment by Comfubar** [comment]
What could i change to do this i have QB setup the same way when i was using sickrage to add them paused its still on as add as paused but when added from sonarr it starts the DL
