### ISSUE TITLE
NZB Search Query API

### ISSUE THREAD

**Issue by lemosm** [Sonarr/Sonarr#2148]
Search query does not provide accurate results (at least with nzbgeek)... say I search "Pokemon s20e03" on NZBGeek their search results us a query parameter of browseincludewords=Pokemon+s20e03.

When Sonarr does this same seach it uses:
q=Pokemon&season=20&ep=3
q=Sun%20and%20Moon&season=20&ep=3
tvdbid=76703&rid=31&season=20&ep=3

unfortunately none of these truly give the same results as the NZBGeek Search... investigating using the same api I can see why you don't want to use "browseincludewords" because that would return huge results but why doesn't Sonarr do:
q=Pokemon+s20e03

just another search but instead of specifying the season & ep query parameters wrap those into the "q" query parameter instead?

**Comment by markus101** [comment]
This is something that NZBGeek should likely address since it should be processing the items and extracting the season + episode numbers for searching.

We do not have plans to perform searches that add the season and episode number to the query parameter.
