### ISSUE TITLE
Request: Overwrite shows recorded by DVR

### ISSUE THREAD

**Issue by danseitz** [Sonarr/Sonarr#2150]
I've tried to figure out if this is possible but can't quite find the right settings, so this may actually be a new feature request.

Plex added Live TV/DVR functionality recently, and it creates files in a number of different formats depending on the tuner box on your network. I'd really like Plex to DVR my shows so I can watch them immediately, then have Sonarr overwrite the recording if it meets my typical download profile.

Is this possible given the current build?

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
If Sonarr sees a file in the series folder it doesn't know where it came from nor does it care. If Sonarr finds a release with a higher quality it can upgrade it (depending on the profile assigned to the series), but it won't upgrade it it if the file from the DVR is higher or the same quality.

There will likely be some flexibility to this with preferred words, but nothing currently. https://github.com/Sonarr/Sonarr/issues/385

If you have any more questions, please open a thread on the forums.
