### ISSUE TITLE
WebUI stops responding.

### ISSUE THREAD

**Issue by B3nihana** [Sonarr/Sonarr#2151]
The Sonarr WebUI appears to stop responding when running on systems that also use mono based applications (such as Radarr and Jackett). Restarting the NzbDrone service works temporarily.

Checking the main log shows no errors and the underlying application works fine, grabbing releases and processing them, it is only the interface that fails.

Happy to provide anything you need.

**Comment by B3nihana** [comment]
Changed logging to debug, still no entries in the logs that seems suspicious. Should I be looking at the mono logs instead?

**Comment by markus101** [comment]
Please open a thread on the forums for support.

You'll want to enable trace logging and capture the standard error and output of the mono process to a file so we can see why it's crashing (as Sonarr's file logs won't be able to log when mono crashes).
