### ISSUE TITLE
Option to enable/disable torrent/nzb per series

### ISSUE THREAD

**Issue by magicalyak** [Sonarr/Sonarr#2154]
I wanted to propose a feature add that would enable one to select only torrent or only nzb or both per series.  Many of the newer series are not best through torrents (for a couple reasons) and I think being able to specify series to be nzb only in a few instances would be of great benefit to many users. 

I could not find any similar request in the issues or the forum.

**Comment by markus101** [comment]
This feature already exists with `Delay Profiles`, you can different delay profiles to different series via tags.

![image](https://user-images.githubusercontent.com/413544/29888287-4c7d278c-8d75-11e7-8b4a-8f49182452f9.png)

**Comment by magicalyak** [comment]
Thank you for the fast response, I must have missed this.  Fantastic and thank you!
