### ISSUE TITLE
NZBDroneErrorPipeline (adding new or existant series) + ScenemappingService + CommandExecutor (refreshing on disk series) errors

### ISSUE THREAD

**Issue by runechronos** [Sonarr/Sonarr#2156]
**Hy I always get the same errors when I try to import an existant serie on disk, sometimes when adding a new one too:**

> 17-8-31 11:19:58.8|Trace|Http|Req: 69 [GET] /api/series?sort_by=sortTitle&order=asc
17-8-31 11:19:58.8|Trace|Owin|SQLite error (5): database is locked
17-8-31 11:19:58.9|Trace|Http|Res: 69 [GET] /api/series?sort_by=sortTitle&order=asc: 200.OK (123 ms)
17-8-31 11:19:58.9|Debug|Api|[GET] /api/series?sort_by=sortTitle&order=asc: 200.OK (123 ms)
17-8-31 11:20:00.6|Trace|Http|Req: 71 [GET] /api/rootfolder
17-8-31 11:20:00.6|Trace|Http|Req: 70 [GET] /api/profile
17-8-31 11:20:00.6|Debug|RootFolderService|Generating list of unmapped folders
17-8-31 11:20:00.6|Trace|Http|Res: 70 [GET] /api/profile: 200.OK (33 ms)
17-8-31 11:20:00.6|Debug|RootFolderService|0 unmapped folders detected.
17-8-31 11:20:00.7|Debug|Api|[GET] /api/profile: 200.OK (33 ms)
17-8-31 11:20:00.7|Debug|RootFolderService|Generating list of unmapped folders
17-8-31 11:20:00.7|Debug|RootFolderService|4 unmapped folders detected.
17-8-31 11:20:00.7|Debug|RootFolderService|Generating list of unmapped folders
17-8-31 11:20:00.7|Debug|RootFolderService|51 unmapped folders detected.
17-8-31 11:20:00.8|Trace|Http|Res: 71 [GET] /api/rootfolder: 200.OK (153 ms)
17-8-31 11:20:00.8|Debug|Api|[GET] /api/rootfolder: 200.OK (153 ms)
17-8-31 11:20:10.9|Trace|Http|Req: 72 [GET] /api/series/lookup?term=Claymore
17-8-31 11:20:10.9|Trace|HttpClient|Req: [GET] http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=claymore
17-8-31 11:20:11.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-8-31 11:20:11.0|Trace|HttpClient|Res: [GET] http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=claymore: 200.OK (52 ms)
17-8-31 11:20:11.0|Trace|Http|Res: 72 [GET] /api/series/lookup?term=Claymore: 200.OK (85 ms)
17-8-31 11:20:11.0|Debug|Api|[GET] /api/series/lookup?term=Claymore: 200.OK (85 ms)
17-8-31 11:20:11.1|Trace|Http|Req: 73 [GET] /api/series/lookup?term=Dragon+Quest+-+Dai%27s+Great+Adventure
17-8-31 11:20:11.1|Trace|HttpClient|Req: [GET] http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=dragon%20quest%20-%20dai's%20great%20adventure
17-8-31 11:20:11.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-8-31 11:20:11.2|Trace|HttpClient|Res: [GET] http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=dragon%20quest%20-%20dai's%20great%20adventure: 200.OK (88 ms)
17-8-31 11:20:11.2|Trace|Http|Res: 73 [GET] /api/series/lookup?term=Dragon+Quest+-+Dai%27s+Great+Adventure: 200.OK (128 ms)
17-8-31 11:20:11.2|Debug|Api|[GET] /api/series/lookup?term=Dragon+Quest+-+Dai%27s+Great+Adventure: 200.OK (128 ms)
17-8-31 11:20:11.2|Trace|Http|Req: 74 [GET] /api/series/lookup?term=One+Piece
17-8-31 11:20:11.2|Trace|HttpClient|Req: [GET] http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=one%20piece
17-8-31 11:20:11.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-8-31 11:20:11.4|Trace|HttpClient|Res: [GET] http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=one%20piece: 200.OK (99 ms)
17-8-31 11:20:11.4|Trace|Http|Res: 74 [GET] /api/series/lookup?term=One+Piece: 200.OK (131 ms)
17-8-31 11:20:11.4|Debug|Api|[GET] /api/series/lookup?term=One+Piece: 200.OK (131 ms)
17-8-31 11:20:11.4|Trace|Http|Req: 75 [GET] /api/series/lookup?term=The+New+Prince+Of+Tennis
17-8-31 11:20:11.4|Trace|HttpClient|Req: [GET] http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=the%20new%20prince%20of%20tennis
17-8-31 11:20:11.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-8-31 11:20:11.5|Trace|HttpClient|Res: [GET] http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=the%20new%20prince%20of%20tennis: 200.OK (37 ms)
17-8-31 11:20:11.5|Trace|Http|Res: 75 [GET] /api/series/lookup?term=The+New+Prince+Of+Tennis: 200.OK (59 ms)
17-8-31 11:20:11.5|Debug|Api|[GET] /api/series/lookup?term=The+New+Prince+Of+Tennis: 200.OK (59 ms)
17-8-31 11:20:14.7|Trace|Http|Req: 76 [POST] /api/series
17-8-31 11:20:14.8|Trace|ConfigService|Using default config value for 'downloadedepisodesfolder' defaultValue:''
17-8-31 11:20:14.8|Trace|HttpClient|Req: [GET] http://skyhook.sonarr.tv/v1/tvdb/shows/en/254899
17-8-31 11:20:14.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-8-31 11:20:14.8|Trace|NzbDroneErrorPipeline|Handling Exception
17-8-31 11:20:14.8|Fatal|NzbDroneErrorPipeline|Request Failed. POST /api/series

> [v2.0.0.4949] System.Net.WebException: Failed to read complete http response ---> System.Net.WebException: La demande a �t� abandonn�e�: La connexion a �t� interrompue de mani�re inattendue.
   � System.Net.GZipWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   � NzbDrone.Common.Extensions.StreamExtensions.ToBytes(Stream input) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Extensions\StreamExtensions.cs:ligne 13
   � NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:ligne 108
   --- Fin de la trace de la pile d'exception interne ---
   � NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:ligne 112
   � NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:ligne 53
   � NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:ligne 119
   � NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:ligne 55
   � NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:ligne 225
   � NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetSeriesInfo(Int32 tvdbSeriesId) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:ligne 40
   � NzbDrone.Core.Tv.AddSeriesService.AddSkyhookData(Series newSeries) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Tv\AddSeriesService.cs:ligne 77
   � NzbDrone.Core.Tv.AddSeriesService.AddSeries(Series newSeries) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Tv\AddSeriesService.cs:ligne 46
   � NzbDrone.Api.Series.SeriesModule.AddSeries(SeriesResource seriesResource) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\Series\SeriesModule.cs:ligne 119
   � NzbDrone.Api.REST.RestModule`1.<set_CreateResource>b__41_0(Object options) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\REST\RestModule.cs:ligne 155
   � CallSite.Target(Closure , CallSite , Func`2 , Object )
   � Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

> 17-8-31 11:20:14.8|Trace|Http|Res: 76 [POST] /api/series: 500.InternalServerError (107 ms)
17-8-31 11:20:14.9|Debug|Api|[POST] /api/series: 500.InternalServerError (107 ms)
17-8-31 11:20:17.0|Trace|Http|Req: 77 [GET] /api/health
17-8-31 11:20:17.0|Trace|Http|Req: 78 [GET] /api/diskspace
17-8-31 11:20:17.0|Trace|Http|Res: 77 [GET] /api/health: 200.OK (15 ms)
17-8-31 11:20:17.1|Trace|ConfigService|Using default config value for 'downloadedepisodesfolder' defaultValue:''
17-8-31 11:20:17.1|Debug|Api|[GET] /api/health: 200.OK (15 ms)
17-8-31 11:20:17.1|Trace|Http|Req: 79 [GET] /api/health
17-8-31 11:20:17.1|Trace|Http|Res: 79 [GET] /api/health: 200.OK (7 ms)
17-8-31 11:20:17.1|Debug|Api|[GET] /api/health: 200.OK (7 ms)
17-8-31 11:20:17.2|Trace|Http|Res: 78 [GET] /api/diskspace: 200.OK (158 ms)
17-8-31 11:20:17.2|Debug|Api|[GET] /api/diskspace: 200.OK (158 ms)
17-8-31 11:20:17.2|Trace|Http|Req: 80 [GET] /api/diskspace
17-8-31 11:20:17.2|Trace|ConfigService|Using default config value for 'downloadedepisodesfolder' defaultValue:''
17-8-31 11:20:17.3|Trace|Http|Res: 80 [GET] /api/diskspace: 200.OK (145 ms)
17-8-31 11:20:17.3|Debug|Api|[GET] /api/diskspace: 200.OK (145 ms)
17-8-31 11:20:18.0|Trace|Http|Req: 81 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc
17-8-31 11:20:18.0|Trace|Http|Res: 81 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (31 ms)
17-8-31 11:20:18.1|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (31 ms)
17-8-31 11:20:18.1|Trace|Http|Req: 82 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc
17-8-31 11:20:18.1|Trace|Http|Res: 82 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (13 ms)
17-8-31 11:20:18.1|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (13 ms)
17-8-31 11:20:24.1|Trace|Http|Req: 83 [GET] /api/log/file
17-8-31 11:20:24.1|Trace|Http|Res: 83 [GET] /api/log/file: 200.OK (6 ms)
17-8-31 11:20:24.1|Debug|Api|[GET] /api/log/file: 200.OK (6 ms)
17-8-31 11:20:24.2|Trace|Http|Req: 84 [GET] /api/log/file/sonarr.trace.txt
17-8-31 11:20:24.2|Trace|Http|Res: 84 [GET] /api/log/file/sonarr.trace.txt: 200.OK (10 ms)
17-8-31 11:20:24.2|Debug|Api|[GET] /api/log/file/sonarr.trace.txt: 200.OK (10 ms)
17-8-31 11:20:25.0|Trace|Scheduler|Pending Tasks: 1
17-8-31 11:20:25.0|Trace|CommandQueueManager|Publishing DownloadedEpisodesScan
17-8-31 11:20:25.0|Trace|CommandQueueManager|Checking if command is queued or started: DownloadedEpisodesScan
17-8-31 11:20:25.0|Trace|CommandQueueManager|Inserting new command: DownloadedEpisodesScan
17-8-31 11:20:25.0|Trace|CommandExecutor|DownloadedEpisodesScanCommand -> DownloadedEpisodesCommandService
17-8-31 11:20:25.0|Trace|CommandQueueManager|Marking command as started: DownloadedEpisodesScan
17-8-31 11:20:25.0|Trace|ConfigService|Using default config value for 'downloadedepisodesfolder' defaultValue:''
17-8-31 11:20:25.0|Trace|DownloadedEpisodesCommandService|Drone Factory folder is not configured
17-8-31 11:20:25.0|Trace|CommandQueueManager|Updating command status
17-8-31 11:20:25.0|Trace|Owin|SQLite error (5): database is locked

> 17-8-31 11:20:25.1|Trace|EventAggregator|Publishing CommandExecutedEvent
17-8-31 11:20:25.1|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
17-8-31 11:20:25.1|Trace|TaskManager|Updating last run time for: NzbDrone.Core.MediaFiles.Commands.DownloadedEpisodesScanCommand
17-8-31 11:20:25.1|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
17-8-31 11:20:25.1|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
17-8-31 11:20:25.1|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
17-8-31 11:20:25.1|Trace|CommandExecutor|DownloadedEpisodesScanCommand <- DownloadedEpisodesCommandService [00:00:00.0189917]
17-8-31 11:20:25.6|Trace|Http|Req: 85 [GET] /api/log/file/sonarr.trace.txt

**And when I try to refresh an existant serie i get this error like almost all the time, sometimes it does work but it almost never does...**

> 17-8-31 11:27:28.5|Trace|DiskProviderBase|Deleting file: C:\ProgramData\NzbDrone\logs\sonarr.txt
17-8-31 11:27:28.5|Trace|CommandQueueManager|Updating command status
17-8-31 11:27:28.6|Trace|Owin|SQLite error (5): database is locked

> 17-8-31 11:27:28.6|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-8-31 11:27:28.6|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-8-31 11:27:28.6|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-8-31 11:27:28.7|Trace|EventAggregator|Publishing CommandExecutedEvent
17-8-31 11:27:28.7|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
17-8-31 11:27:28.7|Trace|Http|Req: 104 [GET] /api/log/file
17-8-31 11:27:28.7|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
17-8-31 11:27:28.7|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
17-8-31 11:27:28.7|Trace|Http|Res: 104 [GET] /api/log/file: 200.OK (13 ms)
17-8-31 11:27:28.7|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
17-8-31 11:27:28.7|Debug|Api|[GET] /api/log/file: 200.OK (13 ms)
17-8-31 11:27:28.7|Trace|CommandExecutor|DeleteLogFilesCommand <- DeleteLogFilesService [00:00:00.1039324]
17-8-31 11:27:28.7|Trace|Http|Req: 105 [GET] /api/log/file
17-8-31 11:27:28.7|Trace|Http|Req: 106 [GET] /api/log/file
17-8-31 11:27:28.7|Trace|Http|Req: 107 [GET] /api/log/file/sonarr.trace.txt
17-8-31 11:27:28.7|Trace|Http|Res: 105 [GET] /api/log/file: 200.OK (23 ms)
17-8-31 11:27:28.7|Trace|Http|Res: 106 [GET] /api/log/file: 200.OK (32 ms)
17-8-31 11:27:28.8|Trace|Http|Res: 107 [GET] /api/log/file/sonarr.trace.txt: 200.OK (33 ms)
17-8-31 11:27:28.8|Debug|Api|[GET] /api/log/file: 200.OK (23 ms)
17-8-31 11:27:28.8|Debug|Api|[GET] /api/log/file: 200.OK (32 ms)
17-8-31 11:27:28.8|Debug|Api|[GET] /api/log/file/sonarr.trace.txt: 200.OK (33 ms)
17-8-31 11:27:28.8|Trace|Http|Req: 108 [GET] /api/log/file/sonarr.debug.txt
17-8-31 11:27:28.8|Trace|Http|Res: 108 [GET] /api/log/file/sonarr.debug.txt: 200.OK (19 ms)
17-8-31 11:27:28.8|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (19 ms)
17-8-31 11:27:28.8|Trace|Http|Req: 109 [GET] /api/log/file/sonarr.debug.txt
17-8-31 11:27:28.8|Trace|Http|Res: 109 [GET] /api/log/file/sonarr.debug.txt: 200.OK (10 ms)
17-8-31 11:27:28.8|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (10 ms)
17-8-31 11:27:30.0|Trace|Http|Req: 110 [GET] /api/series?sort_by=sortTitle&order=asc
17-8-31 11:27:30.0|Trace|Http|Res: 110 [GET] /api/series?sort_by=sortTitle&order=asc: 200.OK (34 ms)
17-8-31 11:27:30.0|Debug|Api|[GET] /api/series?sort_by=sortTitle&order=asc: 200.OK (34 ms)
17-8-31 11:27:36.8|Trace|Http|Req: 111 [POST] /api/command
17-8-31 11:27:36.8|Trace|CommandQueueManager|Publishing RefreshSeries
17-8-31 11:27:36.8|Trace|CommandQueueManager|Checking if command is queued or started: RefreshSeries
17-8-31 11:27:36.8|Trace|CommandQueueManager|Inserting new command: RefreshSeries
17-8-31 11:27:36.8|Trace|Http|Res: 111 [POST] /api/command: 201.Created (26 ms)
17-8-31 11:27:36.8|Trace|CommandExecutor|RefreshSeriesCommand -> RefreshSeriesService
17-8-31 11:27:36.8|Debug|Api|[POST] /api/command: 201.Created (26 ms)
17-8-31 11:27:36.8|Trace|CommandQueueManager|Marking command as started: RefreshSeries
17-8-31 11:27:36.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-8-31 11:27:36.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-8-31 11:27:36.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-8-31 11:27:36.9|Trace|EventAggregator|Publishing SeriesRefreshStartingEvent
17-8-31 11:27:36.9|Trace|EventAggregator|SeriesRefreshStartingEvent -> XemService
17-8-31 11:27:36.9|Debug|XemProxy|Fetching Series IDs from
17-8-31 11:27:36.9|Trace|HttpClient|Req: [GET] http://thexem.de/map/havemap?origin=tvdb
17-8-31 11:27:36.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-8-31 11:27:37.2|Trace|HttpClient|Res: [GET] http://thexem.de/map/havemap?origin=tvdb: 200.OK (276 ms)
17-8-31 11:27:37.2|Trace|EventAggregator|SeriesRefreshStartingEvent <- XemService
17-8-31 11:27:37.2|Trace|EventAggregator|SeriesRefreshStartingEvent -> SceneMappingService
17-8-31 11:27:37.2|Info|SceneMappingService|Updating Scene mappings
17-8-31 11:27:37.2|Debug|XemProxy|Fetching alternate names
17-8-31 11:27:37.2|Trace|HttpClient|Req: [GET] http://thexem.de/map/allNames?seasonNumbers=True&origin=tvdb
17-8-31 11:27:37.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-8-31 11:27:38.0|Trace|HttpClient|Res: [GET] http://thexem.de/map/allNames?seasonNumbers=True&origin=tvdb: 200.OK (749 ms)
17-8-31 11:27:38.2|Trace|HttpClient|Req: [GET] http://services.sonarr.tv/v1/scenemapping
17-8-31 11:27:38.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-8-31 11:27:38.3|Error|SceneMappingService|Failed to Update Scene Mappings

> [v2.0.0.4949] System.Net.WebException: Failed to read complete http response ---> System.Net.WebException: La demande a �t� abandonn�e�: La connexion a �t� interrompue de mani�re inattendue.
   � System.Net.GZipWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   � NzbDrone.Common.Extensions.StreamExtensions.ToBytes(Stream input) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Extensions\StreamExtensions.cs:ligne 13
   � NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:ligne 108
   --- Fin de la trace de la pile d'exception interne ---
   � NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:ligne 112
   � NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:ligne 53
   � NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:ligne 119
   � NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:ligne 55
   � NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:ligne 225
   � NzbDrone.Core.DataAugmentation.Scene.SceneMappingProxy.Fetch() dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Scene\SceneMappingProxy.cs:ligne 29
   � NzbDrone.Core.DataAugmentation.Scene.ServicesProvider.GetSceneMappings() dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Scene\ServicesProvider.cs:ligne 16
   � NzbDrone.Core.DataAugmentation.Scene.SceneMappingService.UpdateMappings() dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Scene\SceneMappingService.cs:ligne 152

> 17-8-31 11:27:38.3|Trace|EventAggregator|Publishing SceneMappingsUpdatedEvent
17-8-31 11:27:38.3|Trace|EventAggregator|SeriesRefreshStartingEvent <- SceneMappingService
17-8-31 11:27:38.3|Info|RefreshSeriesService|Updating Info for The Strain
17-8-31 11:27:38.4|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-8-31 11:27:38.4|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-8-31 11:27:38.4|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-8-31 11:27:38.4|Trace|HttpClient|Req: [GET] http://skyhook.sonarr.tv/v1/tvdb/shows/en/276564
17-8-31 11:27:38.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-8-31 11:27:38.4|Trace|CommandQueueManager|Updating command status
17-8-31 11:27:38.4|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-8-31 11:27:38.4|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-8-31 11:27:38.5|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-8-31 11:27:38.5|Trace|EventAggregator|Publishing CommandExecutedEvent
17-8-31 11:27:38.5|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
17-8-31 11:27:38.5|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
17-8-31 11:27:38.5|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
17-8-31 11:27:38.5|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
17-8-31 11:27:38.5|Error|CommandExecutor|Error occurred while executing task RefreshSeries

> [v2.0.0.4949] System.Net.WebException: Failed to read complete http response ---> System.IO.IOException: Impossible de lire les donn�es de la connexion de transport : La connexion a �t� ferm�e.
   � System.Net.GZipWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   � NzbDrone.Common.Extensions.StreamExtensions.ToBytes(Stream input) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Extensions\StreamExtensions.cs:ligne 13
   � NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:ligne 108
   --- Fin de la trace de la pile d'exception interne ---
   � NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:ligne 112
   � NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:ligne 53
   � NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:ligne 119
   � NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:ligne 55
   � NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:ligne 225
   � NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetSeriesInfo(Int32 tvdbSeriesId) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:ligne 40
   � NzbDrone.Core.Tv.RefreshSeriesService.RefreshSeriesInfo(Series series) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Tv\RefreshSeriesService.cs:ligne 57
   � NzbDrone.Core.Tv.RefreshSeriesService.Execute(RefreshSeriesCommand message) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Tv\RefreshSeriesService.cs:ligne 154
   � NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:ligne 95
   � CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   � System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   � CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   � NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:ligne 41

> 17-8-31 11:27:41.4|Trace|Http|Req: 112 [GET] /api/health
17-8-31 11:27:41.4|Trace|Http|Req: 113 [GET] /api/diskspace
17-8-31 11:27:41.4|Trace|Http|Res: 112 [GET] /api/health: 200.OK (27 ms)
17-8-31 11:27:41.4|Trace|ConfigService|Using default config value for 'downloadedepisodesfolder' defaultValue:''
17-8-31 11:27:41.4|Debug|Api|[GET] /api/health: 200.OK (27 ms)
17-8-31 11:27:41.5|Trace|Http|Req: 114 [GET] /api/health
17-8-31 11:27:41.5|Trace|Http|Res: 114 [GET] /api/health: 200.OK (14 ms)
17-8-31 11:27:41.5|Debug|Api|[GET] /api/health: 200.OK (14 ms)
17-8-31 11:27:41.6|Trace|Http|Res: 113 [GET] /api/diskspace: 200.OK (194 ms)
17-8-31 11:27:41.6|Debug|Api|[GET] /api/diskspace: 200.OK (194 ms)
17-8-31 11:27:41.6|Trace|Http|Req: 115 [GET] /api/diskspace
17-8-31 11:27:41.6|Trace|ConfigService|Using default config value for 'downloadedepisodesfolder' defaultValue:''
17-8-31 11:27:41.8|Trace|Http|Res: 115 [GET] /api/diskspace: 200.OK (151 ms)
17-8-31 11:27:41.8|Debug|Api|[GET] /api/diskspace: 200.OK (151 ms)
17-8-31 11:27:42.5|Trace|Http|Req: 116 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc
17-8-31 11:27:42.5|Trace|Http|Res: 116 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (38 ms)
17-8-31 11:27:42.6|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (38 ms)
17-8-31 11:27:42.6|Trace|Http|Req: 117 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc
17-8-31 11:27:42.6|Trace|Http|Res: 117 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (16 ms)
17-8-31 11:27:42.6|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (16 ms)
17-8-31 11:27:44.6|Trace|Http|Req: 118 [GET] /api/log/file
17-8-31 11:27:44.6|Trace|Http|Res: 118 [GET] /api/log/file: 200.OK (12 ms)
17-8-31 11:27:44.6|Debug|Api|[GET] /api/log/file: 200.OK (12 ms)
17-8-31 11:27:44.6|Trace|Http|Req: 119 [GET] /api/log/file/sonarr.trace.txt
17-8-31 11:27:44.6|Trace|Http|Res: 119 [GET] /api/log/file/sonarr.trace.txt: 200.OK (10 ms)
17-8-31 11:27:44.6|Debug|Api|[GET] /api/log/file/sonarr.trace.txt: 200.OK (10 ms)
17-8-31 11:27:47.0|Trace|Http|Req: 120 [GET] /api/log/file/sonarr.trace.txt`

**Thanks in advance for your help, I looked over the web but I don't get what is really not working.**

**Comment by markus101** [comment]
Please open a thread on the forums for support.

Based on the error the connection is being closed, likely by CloudFlare. We'll need to know if those URLs work in a browser from the same system running Sonarr.
