### ISSUE TITLE
MediaCoverMapper is case sensitive on windows

### ISSUE THREAD

**Issue by bengalih** [Sonarr/Sonarr#2157]
I changed my data directory using "--data=" and I apparently created the root folder as "nzbdrone" instead of "NzbDrone".

All my posters were gone.  I deleted the MediaCover folder and it got recreated and posters got downloaded again, but they wouldn't display at all.  I was getting all of these in the logs:

`File C:\ProgramData\NzbDrone\MediaCover\1\poster-250.jpg not found`

I would literally cut and paste that path and the image would pop up in my viewer...so the picture was there.  Well, technically it was here:

"C:\ProgramData\**nzbdrone**\MediaCover\1\poster-250.jpg"

This being a Windows system it shouldn't have mattered.

Honestly, this isn't a big issue...I can make sure this directory is named NzbDrone as is the default.  I'm just concerned there might be some other case-sensitive issues that the underlying OS doesn't care about but Sonarr might.

**Comment by markus101** [comment]
I'm not seeing this behaviour.

I've redirected the folder to `C:\Test\nzbdrone` and added a new series, I got saw `17-9-1 21:58:04.4|Warn|MediaCoverMapper|File C:\Test\nzbdrone\MediaCover\1\poster.jpg not found` because the file didn't yet exist, after the file downloaded the image loaded in the UI and the error didn't reappear.

> File C:\ProgramData\NzbDrone\MediaCover\1\poster-250.jpg not found

If it was redirected it wouldn't be looking at the old path, sounds like it's not being redirected try `/data=path` instead.

**Comment by bengalih** [comment]
Are you doing a shift+F5 refresh?  That was needed for me.  I just tested in again and still happening.

**Comment by markus101** [comment]
Tried Shift + F5, opening the dev tools so it's not cached and mapping to a folder with a different casing, it didn't make a difference.

This is all on NTFS, are you using a different file system on `D:\`?

**Comment by bengalih** [comment]
I'm on NTFS as well.  Are you sure that the the folder as it exists on your filesystem is a different case then what you have listed in the `--data` parameter?
As stated I can recreate this (and fix it) at will by simply changing the case.
It isn't really an issue for me as I solved it by figuring out the root cause on my system.
If you want more data to track it down I'm happy to help...but if you want to write this off as "works for me" I won't be perturbed.

**Comment by markus101** [comment]
Yes... 100% sure

Found out the difference though, different behaviour when debugging than when running in production mode. Also found the issue. Thanks for the information!
