### ISSUE TITLE
QualityParser "computes" quality instead of parses.

### ISSUE THREAD

**Issue by bengalih** [Sonarr/Sonarr#2159]
I'm trying to maintain original release and quality info in my file names without:
a) Keeping the file name as the original (as some clients don't like)
b) Appending the entire original name to the new name (as it is long/ugly and also may have client issue).

So I tried to set my naming like this:

`{Series Title} - {season}x{episode:00} - {Episode Title} [{Quality Title}] [{Release Group}]`

But this is what happens:
`24:08.5|Debug|Parser|Parsing string 'xxxx.xxxx.S02E19.HDTV.x264-RGROUP[rarbg]'
17-9-2 15:24:08.5|Debug|Parser|Episode Parsed. xxxx xxxx - S02E19 
17-9-2 15:24:08.5|Debug|Parser|Language parsed: English
17-9-2 15:24:08.5|Debug|QualityParser|Trying to parse quality for xxxx.xxxx.S02E19.HDTV.x264-RGROUP[rarbg]
17-9-2 15:24:08.5|Debug|Parser|Quality parsed: SDTV v1
17-9-2 15:24:08.5|Debug|Parser|Release Group parsed: RGROUP
17-9-2 15:24:08.5|Debug|EpisodeFileMovingService|Hardlinking episode file: D:\queue\pickup\tv\xxxx.xxxx.S02E19.HDTV.x264-RGROUP[rarbg]\xxxx.xxxx.S02E19.HDTV.x264-RGROUP.mkv to E:\Data\Media\Video\TV\xxxx xxxx!\Season 02\xxxx xxxx! - 02x19 - Title [SDTV] [RGROUP].mkv
17-9-2 15:24:08.5|Debug|DiskTransferService|HardLinkOrCopy [D:\queue\pickup\tv\xxxx.xxxx.S02E19.HDTV.x264-RGROUP[rarbg]\xxxx.xxxx.S02E19.HDTV.x264-RGROUP.mkv] > [E:\Data\Media\Video\TV\xxxx xxxx!\Season 02\xxxx xxxx! - 02x19 - Title [SDTV] [RGROUP].mkv]
17-9-2 15:24:08.7|Debug|MediaFileAttributeService|Setting last write time on series folder: E:\Data\Media\Video\TV\xxxx xxxx!`

So for the following file:

`xxxx.xxxx.S02E19.HDTV.x264-RGROUP[rarbg]`

I would expect to get:

`xxxx xxxx - 02x19 - Title [HDTV x264] [RGROUP].mkv`

But what I get is:

`xxxx xxxx - 02x19 - Title [SDTV] [RGROUP].mkv`

I have tried different tags from the GUI and from:
https://github.com/Sonarr/Sonarr/wiki/Sorting-and-Renaming

But i can't get it to show.  Since "SDTV" isn't anywhere within the title it clearly isn't getting parsed from the file name but somehow computed based on other factors.

Shouldn't we be able to parse out and save the quality according to the group that released it?

**Comment by markus101** [comment]
HDTV without a resolution is considered `SDTV`, though we're discussing separating that out to `HDTV-480p`, but for 99%+ of people the source in that cases doesn't matter and they're okay with 480p TV sources resulting in `SDTV`.

`x264` is the video codec, unrelated to the quality, you can have Sonarr show that if you choose to show Media Info in the file name.

If you want to show `HDTV` instead of `SDTV` you can change the text the renaming uses by changing it on the quality settings page.

**Comment by bengalih** [comment]
OK...fair enough (though what the heck is HDTV-480p??).

But my main point here is finding a way to preserve the data from the original filename without having to append the entire original filename.  For instance we could consider that a release name has 3 main parts:

{Show - Season - Episode - Title} | { Quality - Codec information } | {Release Group}

*something like Proper/Repack could probably be fit into either of the last two categories.

What I would like to be able to do is let Sonarr rename my file so that Part 1 is manipulated into a friendlier format but I would like to preserve Part 2 and 3 to append on in some organized way.

Right now I can pull out the release group and show that properly, but that Part 2 I can't seem to be able  save as-is.

**Comment by markus101** [comment]
> what the heck is HDTV-480p

HDTV source output at 480p instead of 720p/1080p.

Since _most_ "SDTV" content is `HDTV` source you can change the quality label for `SDTV` to `HDTV` on the quality settings page and add `{MediaInfo VideoCodec}` to get the codec, which will be `x264` for MKVs with `x264` in the original file name in most cases.

**Comment by bengalih** [comment]
Ok thanks.  I think what I was looking for was a way to preserve the actual title release data, even if it may disagree with how/what Sonarr thinks it is.  I've got a workaround instead of a custom script on download which will log both old and new name to a file.  I know that Sonarr keeps this in its database somewhere...but that isn't easy to get at without drilling down, and should anything happen to it (like the show gets removed and then re-added) all that is gone.
This way I have a delimited file to search if necessary.
