### ISSUE TITLE
Unable to set last write time

### ISSUE THREAD

**Issue by bengalih** [Sonarr/Sonarr#2160]
This may be nothing...but I'm seeing these almost all the time:

```
17-9-2 14:53:55.4|Debug|EpisodeFileMovingService|Hardlinking episode file: D:\queue\pickup\tv\xxx.xxx.S03E20.HDTV.x264-RGROUP[rarbg]\xxx.xxx.S03E20.HDTV.x264-RGROUP.mkv to E:\Data\Media\Video\TV\xxx xxx!\Season 03\xxx xxx! - 03x20 - Title [SDTV] [RGROUP].mkv
17-9-2 14:53:55.4|Debug|DiskTransferService|HardLinkOrCopy [D:\queue\pickup\tv\xxx.xxx.S03E20.HDTV.x264-RGROUP[rarbg]\xxx.xxx.S03E20.HDTV.x264-RGROUP.mkv] > [E:\Data\Media\Video\TV\xxx xxx!\Season 03\xxx xxx! - 03x20 - Title [SDTV] [RGROUP].mkv]
17-9-2 14:53:55.8|Debug|MediaFileAttributeService|Setting last write time on series folder: E:\Data\Media\Video\TV\xxx xxx!
17-9-2 14:53:55.8|Warn|EpisodeFileMovingService|Unable to set last write time

[v2.0.0.4949] System.IO.IOException: The process cannot access the file 'E:\Data\Media\Video\TV\xxx xxx!' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.OpenHandle(String path)
   at System.IO.Directory.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at NzbDrone.Common.Disk.DiskProviderBase.FolderSetLastWriteTime(String path, DateTime dateTime) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 255
   at NzbDrone.Core.MediaFiles.MediaFileAttributeService.SetFolderLastWriteTime(String path, DateTime time) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\MediaFileAttributeService.cs:line 75
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile(EpisodeFile episodeFile, Series series, List`1 episodes, String destinationFilePath, TransferMode mode) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 126

17-9-2 14:53:56.0|Debug|EpisodeService|Linking [Season 03\xxx xxx! - 03x20 - Title [SDTV] [RGROUP].mkv] > [[3970]Title]
17-9-2 14:53:56.1|Debug|XbmcMetadata|Generating Episode Metadata for: E:\Data\Media\Video\TV\xxx xxx!\Season 03\xxx xxx! - 03x20 - Title [SDTV] [RGROUP].mkv
17-9-2 14:53:56.1|Debug|MetadataService|Writing Episode Metadata to: E:\Data\Media\Video\TV\xxx xxx!\Season 03\xxx xxx! - 03x20 - Title [SDTV] [RGROUP].nfo
17-9-2 14:53:56.1|Debug|HttpClient|Downloading [http://thetvdb.com/banners/episodes/73141/6203748.jpg] to [E:\Data\Media\Video\TV\xxx xxx!\Season 03\xxx xxx! - 03x20 - Title [SDTV] [RGROUP]-thumb.jpg]
17-9-2 14:53:56.4|Debug|HttpClient|Downloading Completed. took 0s
```
So it looks to me like Sonarr is "Unable to set last write time" because it "cannot access"the video file that has been imported to the final destination (E:\Data\Media\Video\TV\xxx xxx!) "because it is being used by another process."

Sonarr should be the only thing accessing that file - since its job is to copy/move/link that from another location.  In my case it is copying it because the download client location is on another (local) drive.

It would appear that Sonarr is trying to write some data before the copy is done (at least until the file lock is released).

I'm not sure how important this "last write time" is... but this is something you may want to look into.

**Comment by markus101** [comment]
The setting of the last right time occurs _after_ the file has finished moving.

If you have Plex and it is configured to watch for changes to the directory structure that could explain the where the lock is coming from, other software could do the same, but it's not Sonarr causing the issue to itself.

Setting the last write time is not crucial, hence just a warning and not blocking the rest of the import process.

**Comment by bengalih** [comment]
I do have Plex.  Would it be better to turn that option off in Plex and simply send a connection notification from Sonarr?

What is that last write time used for and why would I miss it?

**Comment by markus101** [comment]
> Would it be better to turn that option off in Plex and simply send a connection notification from Sonarr?

That's how I've run it for as long as I can remember (but required due to having storage and Plex on different hosts).

> What is that last write time used for and why would I miss it?

IIRC it was for file systems that didn't properly propagate new files through the folder hierarchy without the file's last write time being updated.
