### ISSUE TITLE
(feature) hot/cold storage support: never auto monitor cold storage

### ISSUE THREAD

**Issue by pimlie** [Sonarr/Sonarr#2161]
Although sonarr is mostly meant for new stuff, I also use sonarr as a library tool to make sure all my old stuff is still up to date. There just arent much other tools out there which gives you such a quick and good overview of the state of your library as sonarr does.

As keeping a large number of disks continuously spinning can be quite expensive, I am using both hot and cold storage in my environment. Stuff that is ongoing is mostly stored on the hot storage (always on) while e.g. the old / finished stuff is on the cold storage as that shouldnt change anymore. The cold storage is used to save a bit on power/money and in this case is just a local raid set of which all member disks are put to sleep as soon as possible. This saves probably 5-10 watt per disk.

So to use the cold storage as it was meant, I currently have to manually set everything on the cold storage to `not monitored` to make sure sonarr is not scanning the disks for changes. Unfortunately its not really easy to see in any of the overview what the exact storage location is and I often forget to turn of monitoring for an item. Which means the cold storage is never put to sleep thus costing me money as power is not cheap here.

To prevent the disks in a cold storage location from spinning up every time sonarr updates the database, it would be nice if you could add some meta data about root folders. The main feature for this would be that everything in the cold storage root folder is _not_ monitored automatically (but preferably you could run a manual library update for a specific cold storage root folder).

Now I understand that this is probably stretching the main use of sonarr a bit, but I think it would be a valuable addition :)

**Comment by markus101** [comment]
> Unfortunately its not really easy to see in any of the overview what the exact storage location is and I often forget to turn of monitoring for an item.

Unmonitoring a series does not affect Sonarr rescanning the series folder, so it'd rescan anything in "cold" storage automatically regardless, which would be once very approximately 12 hours (during the series refresh/disk scan).

There is an existing GHI (https://github.com/Sonarr/Sonarr/issues/1592) proposing that we allow rescanning to be opt-out, but given it's once every 12 hours (from the end of the last refresh), your drives should be asleep most of the time.

**Comment by ghanjaeqemu** [comment]
Curious as to why this is necessary?  Save looking at the source for a possible motive/reason, every 12 hours seems excessive even just to spin drives (and many have multiple drives let's face it).  Is Sonarr prone to "losing" files/media?  Are you certain with Analyse [sic] Video Files set to enable it still only performs a ls and nothing more?  It seems unusually slow for doing just that.  This is an honest question, as the dev crew appears quite adamant to keeping this "feature" how it is.

**Comment by pimlie** [comment]
@ghanjaeqemu Not sure if your question was directed at me or at @markus101, but I dont think Sonarr is prone to losing files. The scanning every 12hours is probably just a measure to keep track of user actions. That's at least the main reason I would still like to have Sonarr check the cold storage, so at least we know when a [ID10T](https://en.wikipedia.org/wiki/User_error#ID-10-T_error) error happens (but running once weekly should be enough for this). A second reason would be in the off-case that after a series has finished it is re-booted for a new season, but I actually only know of one series where that happened (and they didnt create a new spin-off / sequel series).

**Comment by markus101** [comment]
> every 12 hours seems excessive even just to spin drives (and many have multiple drives let's face it)

12 hours is how often the series is refreshed, Sonarr ties the rescan to the same interval so it's rescanning the disk with the most recent information, which leads to Sonarr saving metadata files to disk if they need to be updated or episode images need to be downloaded.

> Is Sonarr prone to "losing" files/media?

No, but people delete files.

> Are you certain with Analyse [sic] Video Files set to enable it still only performs a ls and nothing more?

http://grammarist.com/spelling/analyse-analyze/

No, it does more than that, as mentioned in the UI: `Extract video information such as resolution, runtime and codec information from files. This requires Sonarr to read parts of the file which may cause high disk or network activity during scans.` If it's disabled then all Sonarr will do is get the list of files and process them, otherwise it will use media info to scan the files and extract information.
