### ISSUE TITLE
Sonarr wont find season packs through jackett indexer

### ISSUE THREAD

**Issue by king8084** [Sonarr/Sonarr#2166]
Hello

sonarr do not find shows in season packs through jackett indexers, can this be solved or does the indexer have to be naively configured within sonarr?

**Comment by markus101** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please open a thread on the forums.

Sonarr sends a request for the full season to the indexer, it's up to Jackett to translate that to something the indexer can process to return the appropriate results. You can see the query Sonarr sends to Jackett in the debug logs (in the URL it uses to talk to Jackett).

**Comment by king8084** [comment]
if i invite you to the indexer markus, can you do anything to work it out within sonarr?

**Comment by markus101** [comment]
One of the main purposes for Jackett is to talk to indexers Sonarr does not support because the indexer doesn't have a proper API. Unless they actually have an API there isn't anything to do on Sonarr's end. Which indexer?

**Comment by king8084** [comment]
will pm you on Sonarr.tv

**Comment by kaso17** [comment]
@markus101 I assume @king8084 is talking about automatic/manual search of individual episodes (@king8084: please clarify).
He explained it better in https://github.com/Jackett/Jackett/issues/1813

**Comment by king8084** [comment]
yea Mark knows since we talked about it some more on PMs, but we need a way to search individual eps and get season packs return if the season ended and the tracker now has a season pack instead of single eps, same way it works for the private tracker coded within sonarr
