### ISSUE TITLE
Anime searched in english name some trackers need the japanese names.

### ISSUE THREAD

**Issue by joshuasm** [Sonarr/Sonarr#2168]
Ive added an anime tracker using jackett and i have opened a ticket with them as well [here](https://github.com/Jackett/Jackett/issues/1799) I'm wondering if it is possible to convert it automatically  or if I would have to add each series manually.

possibly add the option to search using the Japanese name?

**Comment by Markieta** [comment]
Sonarr already does this. For example: "My Hero Academia" can also be found using "Boku no Hero Academia" as it is aliased in http://thexem.de/

**Comment by joshuasm** [comment]
I'm using jackett to add an indexer from https://animetorrents.me/ if you search for "My Hero Academia" on there you get no results, but if you search "Boku no Hero Academia" you get results on the tracker (it is a private tracker). I tested this in Jackett itself and on the indexer

**Comment by joshuasm** [comment]
so what is happening is when it is querying the indexer it uses the English name and not the Japanese name

**Comment by M0UL** [comment]
that series works fine. make sure that you have the series type set to anime and have anime turned on in the indexer settings in sonarr.

**Comment by joshuasm** [comment]
this is the indexer in sonarr 
![image](https://user-images.githubusercontent.com/13797385/30511238-a4f2db20-9ad4-11e7-9e42-6e21e6e8cfd8.png)

and this is in jackett
![image](https://user-images.githubusercontent.com/13797385/30511247-d1f6ab56-9ad4-11e7-8b2c-6387ba977713.png)

**Comment by Quiksmage** [comment]
test it in jackett's GUI. do a search for your show there and see if there are any results there.

**Comment by itzaname** [comment]
Its because the animetorrents.me search sucks. Sonarr searches for "Boku no Hero Academia 14" while the releases are named "Boku no Hero Academia - 14" so its missing the - and you get no results.

![image](https://user-images.githubusercontent.com/7243119/30603798-ae72ee06-9d36-11e7-9c15-463d282a35c1.png)
![image](https://user-images.githubusercontent.com/7243119/30603808-b8d4ff42-9d36-11e7-8d62-7e92ef8112cf.png)

**Comment by joshuasm** [comment]
ahhh... ok I see, so its more a problem in the way that animetorrents.me's search works they are remaking the site so hopefully that gets fixed, but for now I guess there is nothing we can do.

**Comment by walkerp1** [comment]
This is more of a Jackett fix. Something like this in AnimeTorrents.cs: [https://pastebin.com/HtTzDdrd](url)

**Comment by mnooblet** [comment]
I've just discovered sonar and try to set it up with jackett, in jackett when I search for an anime I find results, I added the Category TV/Anime in Sonarr but still it doesn't download anything, any ideas?

**Comment by mnooblet** [comment]
oh well nvm, I just saw that I have to add every indexer as torznab, I thought adding sonar once would work for all indexers added in jackett
