### ISSUE TITLE
Sonarr Not Automatically Pulling Episodes or Pulling into Folders/Plex

### ISSUE THREAD

**Issue by jeff15110168** [Sonarr/Sonarr#2169]
So I just moved an install over of Sonarr from my laptop to a new desktop pc. I moved all the data in nzbdrone folder from C:/programdata (as well as Plex data from local %appdata%, and now Sonarr and Radarr seem to be giving me issues with automatically pulling files and/or downloading files with RSS.

I think it may be some sort of authentication error, but I'm not too sure. I saw this in the trace log:

17-9-12 01:24:17.6|Debug|X509CertificateValidationPolicy|Certificate validation for https://192.168.0.185:32400/identity failed. RemoteCertificateNameMismatch
17-9-12 01:24:17.6|Trace|PlexServerProxy|Version response: {"MediaContainer":{

Does this mean anything? I'm going to give it a few days to check again if maybe it was just an error, but it has already missed two episodes (when I manually search, I see them with no exclamation mark posted 5-10 hours ago). I changed RSS sync interval to 10mins, but hoping its just an unlucky streak.

Let me know if there is anything that anyone here would suggest.

**Comment by jeff15110168** [comment]
any update?

**Comment by markus101** [comment]
Please open a thread on the forums for support.
