### ISSUE TITLE
Complete Download Handling Never Works

### ISSUE THREAD

**Issue by yunyunls** [Sonarr/Sonarr#2170]
So everything and anything that downloads through Sonarr never is properly processed unless I manually import or enabled Drone Factory which if I do starts giving me the annoying do not use drone factory message. I tried multiple docker distributions and even ran it through a VM machine for sometime and I still can't get complete download handling to work. So I've come to realize that this doesn't work because Sonarr is looking for the file inside a folder(named the same as the file) and not looking for it in my completed download directory. So would it be possible to change the way Completed Download Handling works and instead of looking for the file in a folder make it look for the file in the completed folder? or anyone has the solution to making complete download handling work???

**Comment by markus101** [comment]
Please open a thread the forums for support. We'll need logs and information about Sonarr/your download client.

>  So I've come to realize that this doesn't work because Sonarr is looking for the file inside a folder(named the same as the file) and not looking for it in my completed download directory.

Sonarr gets the path to import from from your download client (Remote Path Mappings are applied to those paths).
