### ISSUE TITLE
Automatically un-monitor older seasons

### ISSUE THREAD

**Issue by gcormier** [Sonarr/Sonarr#2173]
Two use cases

1) For a series, when a new season starts, stop monitoring older seasons. Not sure on the best condition for this to trigger - on download of first episode of new season, unmonitor all previous? Or, when new season information is available (probably not good)... or, when last episode in a season is downloaded, stop monitoring.

2) For a given series (perhaps added manually, or a newly added series), add an icon to "stop monitoring everything except latest season".

**Comment by Taloth** [comment]
1. Doesn't the quality cutoff take care of any previous season with existing files?

2. Already exists: Season Pass on the main view.

**Comment by gcormier** [comment]
2. Gotcha :)

1. Hmm, I'm not really sure. The last couple weeks I've had a ton of really old episodes (from seasons a few years back) for a few random shows start downloading.

**Comment by Taloth** [comment]
3. if the cutoff wasn't met yet and they reupped some bluray releases, then that could happen. but that's what you asked Sonarr to do: to find releases matching your criteria and automatically download them. :smile:

**Comment by gcormier** [comment]
Sure. I guess my thinking is, if a release wasn't "good enough" despite the quality cutoff, I'd re-download it. If it's sitting on my hard drive, by the time the next season airs, I don't care about anything at all about the old ones.

Doing Season Pass regularly just has that manual vibe to it - the point is automation :)

**Comment by markus101** [comment]
I'm torn on the usefulness of this for more than a handful of users, but could see it fitting in similar to some ideas I have for https://github.com/Sonarr/Sonarr/issues/314 but instead of deleting they'd be unmonitored.

The manual aspect of season pass could be automated, using the API (although `/api/seasonpass` is not documented right now), though I can think of a possible edge case in that a new season is listed, but hasn't aired so ignoring previous seasons would cause the most recently aired season to be ignored.

**Comment by ShakataGaNai** [comment]
I could see this being very useful. It doesn't even have to be "season" so much as "last X episodes". I'm not sure about OP's use case, but I follow some daily or semi-daily shows. The episodes from say... 1996 are of no interest (or even a month ago), but the most recent ones are. If they get snagged great! If not, well we should give up after a time.

**Comment by arkayenro** [comment]
sounds like it would be better off being a cutoff based on the number of days before an EP is automatically unmonitored, set per show, and possibly a default as well (show would override default)

also a way to apply it retrospectively.  or a scheduled task once a day that does it?

**Comment by markus101** [comment]
We'll look at this with #314 no sense in an almost duplicate staying open.
