### ISSUE TITLE
Feature request: notifications for system status

### ISSUE THREAD

**Issue by MaartenMol96** [Sonarr/Sonarr#2174]
In the system page there is showed if an indexer is not available or any other problems. I really like to see if we can also get these by notification from the connect settings. Like telegram! 

Is this possible?

**Comment by Renegade605** [comment]
+1. If there's an issue with the configuration it would be great to know right away instead of after a couple days of no downloads.

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/1798
