### ISSUE TITLE
Request for proper indexer - Sonarr re-downloads already downloaded series

### ISSUE THREAD

**Issue by MrDemocracy** [Sonarr/Sonarr#2175]
I have 5 non-raid hdd's connected to my media server. On these drives, there are series and movies scattered around where there's enough space. This means there are some seasons of a series on one drive, and the rest of the seasons on another drive. This seems to confuse Sonarr, as it occasionally download duplicates of individual episodes, or full seasons. This fills up all my hdd's with unnecessary data, and gives me a lot of work to clear the duplicates.
Can a proper indexer be implemented to Sonarr, that can manage a series being on more than one hdd.

A way for Sonarr to check if there's enough room on a hdd before choosing download location, would also be wonderful.

**Comment by markus101** [comment]
We currently do not have plans to support multiple folders per series, we recommend drive pooling software to achieve that, whether you want to use a parity drive with that is up to you.

**Comment by MrDemocracy** [comment]
Don't you have to format the pool drives anyway? Then a raid would basically be the same thing. I don't have 14TB of spare space to backup my drives to, before I format them...
