### ISSUE TITLE
how do i set catagory by show for indexers.    

### ISSUE THREAD

**Issue by tostane** [Sonarr/Sonarr#2179]
When searching tv shows some are normal tv but some are foreign.  since the same names can be used for different shows there needs be a way to add the 5020  category to the foreign shows.   

the only other way i see is to run multiple copys of sonarr some how.

**Comment by markus101** [comment]
It's not possible to add a category that is used only for a specific series. It'd be possible with https://github.com/Sonarr/Sonarr/issues/487, but the indexer would need to be added twice and would be a bit awkward for RSS syncing (since it'd need to check both and filter out any series that doesn't have a matching tag if one was set on the indexer), doable, but at the cost of more API hits.

**Comment by tostane** [comment]
So I end up having to run 2 copy's of sonarr then and have one do the English and other do non-English

I tested the 5020 along with the other 2 numbers and it gets the shows. I am just worried it will try to pull the English shows from the 5020 group as it carries the same shows in other languages. For now I just removed the 5020 as the size of the shows is still pretty large and until x265 gets adopted, its not piratical to pull those yet.
I hope you can figure a way to handle prioritizing the x265 over 264 in the future even if it means waiting a day or 2 and storing the rss pulls up and parsing them later.  Then the need for adding categories for the shows will be a bit more urgent.

I did notice you do a good job on lowering api calls.  

I turn off episode jpgs you have that on. I see no reason to store a jpg for every episode this should be off by default.
ty for sharing this nice ap.

**Comment by tostane** [comment]
Im still trying to figure this out   I have sonar and sickrage running now  I dont see how to run 2 copys of sonar as it spreads it data into another folder and if i try to start a second copy it just writes on the firsts ones data.   so its is useless.    I really be much easier if the program could handle  foreign and normal tv

Now i run into a new problem the file manager in sonar seems broken I will post a bug report on that next.
