### ISSUE TITLE
Can't find anime with English title

### ISSUE THREAD

**Issue by guuilp** [Sonarr/Sonarr#2180]
My Sonarr version: 2.0.0.4949
OS: Windows 10
Configured indexes: Nyaa Pantsu and Nyaa si (both of them with default setup)

The problem: animes which has different names in English and Japanese can't be found in Sonarr.
Exemple: Classroom Of The Elite (English) / Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e (Japanese)
Series Type (in Sonarr): Anime

Log message: Searching 2 indexers for [Classroom of the Elite : 11]

As you can see in the log message, it's trying to find the anime by the English name, when it is published with the Japanese name.

I've already tried to delete and add the serie many times, didn't work.

I'm new at Sonnar.

If you need any more details, please let me know.

**Comment by guuilp** [comment]
I found this article explaining how the Sonarr search with alias: https://forums.sonarr.tv/t/scene-naming-tvdb-naming-conflicts/137.

I entered in the site and I found the alias for this anime: http://thexem.de/xem/show/3777

So I think there's some kind of bug in the latest version.

**Comment by guuilp** [comment]
The logs: https://pastebin.com/N6rb4K6B

**Comment by markus101** [comment]
Please open a thread on the forums for support.

You'll need to look at debug logs (files, not the table) to see exactly which terms Sonarr is using to search.

```
17-9-20 17:37:16.3|Debug|Nyaa|Downloading Feed https://nyaa.si/?page=rss&cats=1_37&filter=1&term=Youkoso+Jitsuryoku+Shijou+Shugi+no+Kyoushitsu+e+11
17-9-20 17:37:16.4|Debug|Torznab|Downloading Feed https://nyaa.pantsu.cat/feed/torznab?t=search&cat=5070&extended=1&offset=0&limit=50&q=Youkoso%20Jitsuryoku%20Shijou%20Shugi%20no%20Kyoushitsu%20e+11
17-9-20 17:37:17.4|Warn|HttpClient|HTTP Error - Res: [GET] https://nyaa.si/?page=rss&cats=1_37&filter=1&term=Youkoso+Jitsuryoku+Shijou+Shugi+no+Kyoushitsu+e+11: 400.BadRequest
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>

17-9-20 17:37:17.4|Warn|Nyaa|Nyaa HTTP request failed: [400:BadRequest] [GET] at [https://nyaa.si/?page=rss&cats=1_37&filter=1&term=Youkoso+Jitsuryoku+Shijou+Shugi+no+Kyoushitsu+e+11]
17-9-20 17:37:17.5|Debug|IndexerFactory|Temporarily ignoring indexer Nyaa till 9/20/2017 5:52:17 PM due to recent failures.
17-9-20 17:37:17.9|Debug|Api|[GET] /api/v3/health: 200.OK (82 ms)
17-9-20 17:37:18.1|Debug|Torznab|Downloading Feed https://nyaa.pantsu.cat/feed/torznab?t=search&cat=5070&extended=1&offset=0&limit=50&q=Classroom%20of%20the%20Elite+11
17-9-20 17:37:20.9|Debug|NzbSearchService|Total of 8 reports were found for [Classroom of the Elite : 11] from 2 indexers
```

So nyaa.si isn't working, but nyaa.pantsu.cat is (and getting results for the Japanese title).

**Comment by guuilp** [comment]
I opened the thread, but looks like it haven't been approved yet. If you can review it, I'd appreciate.

```
17-9-20 21:40:41.6|Trace|Http|Req: 184 [GET] /api/release?episodeId=2532&sort_by=releaseWeight&order=asc
17-9-20 21:40:41.6|Info|NzbSearchService|Searching 1 indexers for [Classroom of the Elite : 11]
17-9-20 21:40:41.6|Debug|Torznab|Downloading Feed https://nyaa.pantsu.cat/feed/torznab?t=search&cat=5070&extended=1&offset=0&limit=50&q=Classroom%20of%20the%20Elite+11
17-9-20 21:40:41.6|Trace|HttpClient|Req: [GET] https://nyaa.pantsu.cat/feed/torznab?t=search&cat=5070&extended=1&offset=0&limit=50&q=Classroom%20of%20the%20Elite+11
17-9-20 21:40:41.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-9-20 21:40:47.2|Trace|HttpClient|Res: [GET] https://nyaa.pantsu.cat/feed/torznab?t=search&cat=5070&extended=1&offset=0&limit=50&q=Classroom%20of%20the%20Elite+11: 200.OK (5570 ms)
17-9-20 21:40:47.2|Debug|NzbSearchService|Total of 0 reports were found for [Classroom of the Elite : 11] from 1 indexers
```

This is my log file. In my case it's searching for English name yet.
