### ISSUE TITLE
cloud flare issue?

### ISSUE THREAD

**Issue by thenoid** [Sonarr/Sonarr#2181]
Probably not the place for this, but the forums/api service appear to be down?  Cloudflare reporting the backend host is unreachable?  IRC wasn't helpful - figured i'd try github...

**Comment by wrisk** [comment]
See https://forums.sonarr.tv/t/unable-to-add-show/16083/5

**Comment by thenoid** [comment]
Heh, if i could have gotten to the forums, that would have been helpful ;)  Thanks

**Comment by markus101** [comment]
Not cloudflare, server issues. Looks like we've sorted it out and we're working on moving some services to a new box.
