### ISSUE TITLE
The 100 Season pack Deluge but being handled

### ISSUE THREAD

**Issue by FrAllard** [Sonarr/Sonarr#2183]
I this Sonarr is still confused by The.100

I'm downloading a **torrent** of a season pack of The 100 called "The.100.S04.1080p.Bluray.x264-MIXED[rarrtv]"

I've added the torrent manually to deluge and assigned the right label so Sonarr should see it and monitor it in Activity, but it doesn't... I've read old posts regarding the "[" bug. I tried a single episode of an other show containing I have in my database and it does work, I also added it manually and it showed in the Activity list and the name contained "[rarrtv]".

I also had some problem with the season pack 03 and I had to move it manually (before I learn about manual import) but then I tried to rescan the folder to get the file to show in the show page but it seem the Sonarr could not find the files. I was able to manually import, Sonarr was able to detect the right show and episode number during the manual import. I don't remember if I assigned the label or not during the season 03 download... But the manual move into the right folder should have picked up the files during the rescan.

Then I tested searching manually for only one episode... Sonarr can find the episode on nzb but not on torrents... (I verified and the episode was present on r**g.to) I forced "Only torrent" and "Only Usenet" to do the tests...

**Comment by markus101** [comment]
Please open a thread on the forums for support.

Without debug logs it's impossible to be sure, but is likely caused by the `[rarbg]` at the end, which causes the parsing to treat it as anime, this is covered by https://github.com/Sonarr/Sonarr/issues/457
