### ISSUE TITLE
Nyaa.pantsu.cat not showing seeder/leecher info

### ISSUE THREAD

**Issue by Zunon** [Sonarr/Sonarr#2185]
Honestly I didn't know whether to post this here or on the nyaapantsu repo, but when searching using the default torznab configuration for nyaa.pantsu.cat it shows unknown seeders/unknown leechers, maybe it due to how nyaa have structured their torznab api?

**Comment by markus101** [comment]
I'm seeing seeding/leecher information for 2 day old content, though some show a seeder count and an unknown number of leechers, which may be due to excluding the leecher count when it is 0, but that'd be something for them to take a look at.

**Comment by Zunon** [comment]
For me none of them show seeder/leecher count
