### ISSUE TITLE
".NORDIC." found as NORWEGIAN. (No workaround with Norwegian profile)

### ISSUE THREAD

**Issue by Cykle** [Sonarr/Sonarr#2189]
Hi.

This issue is allready reported in thred #1169 where a workaround creating a Norwegian profile helped op.
This is´nt the case with me since using a Norwegian profile only being rejected as "Norwegian is wanted but found English"

![radarr](https://user-images.githubusercontent.com/1812295/30784350-e7ff0ae4-a153-11e7-8782-17fcb9c8c029.jpg)

**Comment by Cykle** [comment]
This release is .DKSubs. but its the same with .NORDIC.

**Comment by markus101** [comment]
`Nordic` is treated as Norweigian, `DKSubs` is not, hence the rejection message saying it found English. It's the opposite of the issue you linked and the reason the workaround there isn't working for you.

**Comment by markus101** [comment]
I don't think we want to add DKSubs to be treated as Norweigian (subs doesn't mean there is a matching language as well). In v3 there will be the ability to add multiple languages to a profile (just like qualities), though that may not help much here.
