### ISSUE TITLE
UI: Pop up shows wrong configuration for item clicked.

### ISSUE THREAD

**Issue by kevin182** [Sonarr/Sonarr#2191]
When I click on any item in setting to modify, it pops up correct then changes to 1 of my download clients (Sabnzbd). This happens whether I click another download client, profile, indexer, connect, etc. I really can't change anything or see how something is set because Sabnzbd keeps populating the pop up. The dialog title does stay correct but nothing else. Thanks.

**Comment by Taloth** [comment]
Sonarr version? Which Browser? Screenshot? Check the browser develop console for errors?

**Comment by kevin182** [comment]
Version 2.0.0.4949 but it has been happening for a few months now and I have been auto upgrading.
I found the problem. Using Lastpass password manager (only when logged in) to the Chrome extension, there is an error in the development console. 

downloadclient:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.

When I am logged out of Lastpass, it does not happen anymore.

**Comment by markus101** [comment]
I've never seen this behaviour with LastPass and Sonarr, though I switched to 1Password recently.

Without a screenshot of the issue I'm not 100% sure what LP is doing, but it sounds like it is trying to autofill in settings for your download client whenever the modal is opened. Not sure there is anything that we can do to prevent that, but seeing what you're seeing may help.

**Comment by markus101** [comment]
Closing, we can revisit if a similar issue is found in v3, but haven't seen this there either.

**Comment by ZombieEleos** [comment]
Yeah super easy fix , lastpass is trying to autofill info, just go to sonarr over a field where lastpass auto fills select info -> edit -> advanced edit -> disable autofill  will only disable it for that specific site url. relzied this is months later but came across this! thanks!
