### ISSUE TITLE
DownloadedEpisodesScan without triggering Copy/Move

### ISSUE THREAD

**Issue by kbzowski** [Sonarr/Sonarr#2192]
Can you add new option for importMode API command called "Skip" which will skip copying/moving episode to target location. 

Explanation.
My setup includes deluge + rar2fs to handle rared releases. It works smoothly. But I can not make hard links from rar2fs mount point and copying data would duplicates limited space. I would like to decide what will happen after downloading (using batch script). So I would expects only that the sonarr will be aware that the episode has been downloaded successfully and skip postprocessing.

**Comment by markus101** [comment]
Sonarr doesn't consider a download complete until a file has been imported and it is not a planned feature to support the behaviour you're looking for.

One possible workaround would be to create a symlink that points to the file on rar2fs mount and have Sonarr import the symlink, there may be other options as well.
