### ISSUE TITLE
x265 HEVC preferred quality 

### ISSUE THREAD

**Issue by screwfaze** [Sonarr/Sonarr#2193]
Hi,

First of all thanks a lot for Sonarr I really love this awesome program and cannot live without it now! I have recently come across the x265 codec and believe it will be a huge benefit to start changing my collections to this format to reduce space but cannot see this option in Sonarr. Is this possible to choose so that preferred quality is x265 so that my collection can be automatically upgraded to this?

Thanks

**Comment by 19wolf** [comment]
Seconded. I'd like x264 releases downloaded as soon as they're available, but then upgrade to x265 as soon as those are available (usually the next day). Or for older episodes/shows, download x265 unless there are none, then fall back on x264

**Comment by markus101** [comment]
This would be covered by https://github.com/Sonarr/Sonarr/issues/385
