### ISSUE TITLE
Allow Completed Download handler to move intead of copy

### ISSUE THREAD

**Issue by Rob4001** [Sonarr/Sonarr#2195]
Currently there is no way of telling the completed download handler to move files instead of copying/hardlinking.

This would be useful for those who use a remote downloader and rsync to pull the completed downloads to the local machine with sonarr.

**Comment by markus101** [comment]
You can pass in `importMode="mode"` where `mode` is `Auto`, `Move` or `Copy` (https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportMode.cs).
