### ISSUE TITLE
Suggestions take a while to load, blocking input

### ISSUE THREAD

**Issue by endquote** [Sonarr/Sonarr#2197]
The suggestions seem to take a long time to load for me, for whatever reason. Multiple minutes, sometimes. I'm not able to add a new movie during this time, because the suggestions loader overlaps the search results.

![screenshot 2017-09-29 20 44 20](https://user-images.githubusercontent.com/330010/31042186-29be9fa6-a557-11e7-8fa9-06fd20b6d068.png)

**Comment by markus101** [comment]
Looks like you're looking for https://github.com/Radarr/Radarr
