### ISSUE TITLE
Error occurred while executing task RssSync

### ISSUE THREAD

**Issue by CasperH2O** [Sonarr/Sonarr#2198]
nzbdrone version and branch: Sonarr Ver. 2.0.0.4949
System information

![afbeelding](https://user-images.githubusercontent.com/14330834/31044543-9c665cea-a5d1-11e7-8e01-47024d60ed59.png)

Browser Firefox 55.0.3 (64-bits)

Log message: 

`Error occurred while executing task RssSync: Er is een uitzondering opgetreden in een TaskScheduler.`

Exception:

`System.Threading.Tasks.TaskSchedulerException: Er is een uitzondering opgetreden in een TaskScheduler. ---> System.OutOfMemoryException: Er is een uitzondering opgetreden van het type System.OutOfMemoryException.
   bij System.Threading.Thread.StartInternal(IPrincipal principal, StackCrawlMark& stackMark)
   bij System.Threading.Thread.Start(StackCrawlMark& stackMark)
   bij System.Threading.Thread.Start(Object parameter)
   bij System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
   bij System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- Einde van intern uitzonderingsstackpad ---
   bij System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   bij System.Threading.Tasks.Task.InternalStartNew(Task creatingTask, Delegate action, Object state, CancellationToken cancellationToken, TaskScheduler scheduler, TaskCreationOptions options, InternalTaskOptions internalOptions, StackCrawlMark& stackMark)
   bij System.Threading.Tasks.TaskFactory.StartNew(Action action)
   bij NzbDrone.Core.Indexers.FetchAndParseRssService.Fetch() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\FetchAndParseRssService.cs:regel 47
   bij NzbDrone.Core.Indexers.RssSyncService.Sync() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\RssSyncService.cs:regel 47
   bij NzbDrone.Core.Indexers.RssSyncService.Execute(RssSyncCommand message) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\RssSyncService.cs:regel 68
   bij NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:regel 95
   bij CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   bij System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   bij CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   bij NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:regel 41`

Checked this morning and found Sonarr had stopped running. Reading back through the log I found this message/information. Not sure if it is enough or reproducible. Found another topic which stated it could be preferred to enable a trace log for more detailed info? 

It reads as out of memory, the computer has 8 Gb, under normal usage, only 5-6 is in use. Is there a way to trigger the sync so I can watch the RAM usage?

I'm surprised it I see text referring to M:\ as I don't have an M drive.

**Comment by Taloth** [comment]
Any of those tasks can be triggered in System->Tasks.

Applications do not use physical memory, they use virtual memory. So the 8 GB is entirely meaningless.
OOM exceptions are never truly 'out of memory', but rather "I couldn't find a continuous block of free virtual memory large enough".

As for M:, if you look at it more closely you'll see it refers to the source code files on our build server.

Finally, we prefer if you post support requests on our forums instead.

**Comment by CasperH2O** [comment]
@Taloth, thank you for the reply. Good to know about the type of memory usage. As per your suggestion I checked the forum and noticed that for this type of problem additional debug data is required. I'll do a restart and see if I can reproduce it. When I have more info I'll share it on the forum.

Ticket can be closed.
