### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by shaitand** [Sonarr/Sonarr#2200]
I'm not interested in chasing down the underlying cause. I'm certainly not bashing Sonarr, it is a great application and I appreciate the work that goes into it. But I'm going to be blunt, it crashes, early and often it crashes. First define crash, Anytime Sonarr is correctly working, and underlying infrastructure/connectivity and working, and Sonarr's operational state becomes such that it fails to check for and download new episodes or the GUI becomes unresponsible to interactive input (including updating that input, not merely switching between tabs of cached content) I define that as a crash. The underlying problem? Might be a dozen different things, locking, db contention, internal locking layered on top of db locking, locking and contention for other resources, etc.

This is a crash:

![ejuicecart1](https://user-images.githubusercontent.com/8183779/31058806-b65f4974-a6bf-11e7-9dfd-e36afc2d2e19.png)

What I am looking for is something to plug into a shell script that will detect this sort of crashed state. Like a wget or curl request or similar. If I just restart without concern there are problems, the download queue and most aspects of state seem to be handled without any sort of ledger so when the program crashes or gets a hard shutdown because it can't terminate in a reasonable timeframe (<15s) lots of important state information is losts (downloads in queue, ongoing search tasks, etc). In order to fix this I've been trying to find something like the above but it doesn't detect all crashes by a long shot.

Currently I do this with a 5s hard timeout:

/usr/local/bin/wget http://10.10.0.13:8989/system/status --no-cache -q -T1 -O - | /usr/bin/grep ApiKey

If the result doesn't contain the ApiKey or there is no result within the 5s this will trigger a restart. The idea being that content wouldn't be served up with Sonarr crashed, but apparently often the zombie is alive enough to give me this result, as it is at this very moment which I've pictured above. I need an operation that will fail on that zombie.

**Comment by markus101** [comment]
You're going to need to dig in and find out what is failing when the UI isn't loading, but the system status endpoint is responding since we can't guess as to what might be causing the UI to fail to load but other endpoints are working.

We use our forums for support and other questions. Please open a thread on the forums if you'd like us to help investigate the issue, we'll need to know more information about your setup and in this case see trace logs to understand the problem further.

**Comment by shaitand** [comment]
@markus101 
Thanks for input, I'm really not trying to tracedown the issue. Logging stops and as far as I can tell and so does all downloading. This isn't a single bug and you are absolutely right the request doesn't belong on github I just had hopped for an internal hook or trick you guys were using that can be used to ping an essential piece of framework and determines if it responds.

Honestly, I haven't looked into the code and I have essentially no mono/.Net experience so it's a given that you guys will take my off cuff impression with a grain of salt. For what it's worth but over 20yrs of Enterprise level *nix experience and a great deal of dev experience (says random internet guy) and from the little I've seen of the design I suspect most of these issues are related to concurrence and contention. Possibly in an underlying framework. I've seen similar issues in a number of related applications with web-ui's and running on .Net/Mono. The other obvious place you'll have issues is the on-disk db. Especially issues surrounding locks and contention. I'd suggest stepping up to a real sql like maria or postgres, possibly use redis for some bits. Also for most of the transactions occurring within the framework, one or more ledgers might be a good idea. Just some thoughts to consider if you ever go down a major overhaul and/or rework path because most of these problems are probably design decisions at this point or even inherited by you guys with the original code base.

For anyone else who experiences these kinds of issues and wants a bandaid over it. I'm currently trying to stat the nzbdrone.db-shm file and make sure it has a ctime update within the last 15min.
