### ISSUE TITLE
Lots of SIGEGV and Fatal errors 

### ISSUE THREAD

**Issue by maxcr** [Sonarr/Sonarr#2201]
I've attached a log file with the mono debug output listing all of the errors. I cannot run Sonarr for more than 5 minutes without it crashing. Plz help. Also, I'm using Arch Linux.

[monoerrors.txt](https://github.com/Sonarr/Sonarr/files/1350690/monoerrors.txt)

**Comment by markus101** [comment]
Please use the forums for support.

This issue appears to be the same as https://github.com/Sonarr/Sonarr/issues/1928 a workaround is listed there.
