### ISSUE TITLE
Translocation

### ISSUE THREAD

**Issue by deecypher** [Sonarr/Sonarr#2202]
Hello, I just recently updated to MacOS 10.13, fresh install. Upon installing and restoring Sonarr, I've gotten the following error:

`Cannot install update because startup folder '/private/var/folders/ht/cp3hrhns1q17fl8xyb3n5xjh0000gn/T/AppTranslocation/2D24EEA7-EA8E-4D70-BB89-77464DC32D29/d/Sonarr.app/Contents/MacOS' is in an App Translocation folder.`

The app is located in the Applications folder, so I'm not quite sure why this is happening.

MacOS: 10.13
Gatekeeper: Disabled
Machine: Mac Mini Server Late 2011

**Comment by Taloth** [comment]
It's likely related to this forum post https://forums.sonarr.tv/t/osx-update-fails-due-to-permissions/12544

_Please keep support questions on the forums._

**Comment by deecypher** [comment]
So sorry, will repost there
