### ISSUE TITLE
[Feature Request] Option to cancel active transfer on unmonitor

### ISSUE THREAD

**Issue by rwhapham** [Sonarr/Sonarr#2203]
I would like an option to have Sonarr automatically cancel any active transfer(s) for an item if it goes from monitored to unmonitored state. This would not only be a convenience, but would be beneficial in mixed DVR/download setups like mine. When a DVR recording starts, I automatically unmonitor the given episode in Sonarr. There are times, though, that the episode has already been grabbed where I would prefer the transfer be cancelled and the DVR recording allowed to complete.

**Comment by markus101** [comment]
Unmonitor only controls Sonarr's ability to grab it from an RSS feed and we don't plan to mix that with other operations.

You could however get the queue from Sonarr and tell Sonarr to remove that item from the download client. https://github.com/Sonarr/Sonarr/wiki/Queue

**Comment by rwhapham** [comment]
Thanks, I didn't realize there was a DELETE command for the Queue. I think that when I looked into it some time ago it perhaps didn't exist yet. Unfortunately, I cannot get it to work properly. If I send a properly authorized GET command to /api/queue I can see the list. But if I send a DELETE (again, with the proper auth header) to http://myserver/api/queue?id=75600316 using Postman, I get a 405 code back with the JSON body { "message": "MethodNotAllowed" }. Any ideas what I'm doing wrong? Thanks.

**Comment by markus101** [comment]
Yeah, ID is part of the url: `/api/queue/{id}`.
