### ISSUE TITLE
RSS Sync slowly processes 1374 results

### ISSUE THREAD

**Issue by Mark7even** [Sonarr/Sonarr#2205]
Recently, within the last few days with no changes to Sonarr, whenever there is an RSS Sync it never completes and gets stuck around 400/1374. Even after removing all indexers to just a single one, restarting and then changing to a different single indexer the 1374 number never changes.

Is there like a cache that needs to be cleared? This is causing high CPU usage on my server because it never finishes and then the next RSS Sync interval begins. 

I am running the Mac OS.

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
This is related to something that @Taloth has been looking into, https://github.com/Sonarr/Sonarr/pull/2119 he'll probably need some additional info (trace logs maybe) to confirm.

> This is causing high CPU usage on my server because it never finishes and then the next RSS Sync interval begins.

The interval is from when it last finished, Sonarr won't run multiple RSS Syncs at the same time.

**Comment by Mark7even** [comment]
Okay let me know.

**Comment by grphx7** [comment]
I too am having the same issue. High cpu usage and a high count of items to sync via rss.

**Comment by Senaxx** [comment]
Same problem here. Running latest Sonarr in a docker with completly new install on a 918+ synology nas. As soon as i start the docker and Sonarr starts, it starts with updating the rss. I have only 1 indexer trough jackett. It says "Processing release 471/471" but never finishes the task.

**Comment by jpdillingham** [comment]
I am also experiencing this problem.  My ```PendingReleases``` table had grown to over 3800 entries, and is presently growing by 16 entries after each RSS sync.  At a certain point RSS sync tasks fail to complete and consume ~25% of my CPU, or one core at 100%.

I turned on tracing and the only thing that jumped out was this:

```
17-10-25 11:07:10.1|Trace|Owin|SQLite error (5): database is locked

17-10-25 11:07:10.2|Trace|Owin|SQLite error (261): database is locked
```

I manually cleared the ```PendingReleases``` table and it solved the CPU issue, however the table still grows with each sync.  The SQLite errors went away after I cleared the table, save for one on startup:

```
17-10-25 11:08:55.9|Info|NancyBootstrapper|Starting Web Server
17-10-25 11:08:55.9|Trace|EventAggregator|Publishing ApplicationStartedEvent
17-10-25 11:08:56.0|Trace|EventAggregator|ApplicationStartedEvent -> QualityDefinitionService
17-10-25 11:08:56.0|Debug|QualityDefinitionService|Setting up default quality config
17-10-25 11:08:56.0|Trace|EventAggregator|ApplicationStartedEvent <- QualityDefinitionService
17-10-25 11:08:56.0|Trace|EventAggregator|ApplicationStartedEvent -> ProgressMessageTarget
17-10-25 11:08:56.1|Trace|EventAggregator|ApplicationStartedEvent <- ProgressMessageTarget
17-10-25 11:08:56.1|Trace|EventAggregator|ApplicationStartedEvent -> ProfileService
17-10-25 11:08:56.2|Trace|EventAggregator|ApplicationStartedEvent <- ProfileService
17-10-25 11:08:56.2|Trace|EventAggregator|ApplicationStartedEvent -> NotificationFactory
17-10-25 11:08:56.2|Debug|NotificationFactory|Initializing Providers. Count 20
17-10-25 11:08:56.2|Trace|EventAggregator|ApplicationStartedEvent <- NotificationFactory
17-10-25 11:08:56.2|Trace|EventAggregator|ApplicationStartedEvent -> CommandExecutor
17-10-25 11:08:56.2|Trace|EventAggregator|ApplicationStartedEvent <- CommandExecutor
17-10-25 11:08:56.2|Trace|EventAggregator|ApplicationStartedEvent -> CommandQueueManager
17-10-25 11:08:56.2|Trace|CommandQueueManager|Orphaning incomplete commands
17-10-25 11:08:56.2|Trace|EventAggregator|ApplicationStartedEvent <- CommandQueueManager
17-10-25 11:08:56.2|Trace|EventAggregator|ApplicationStartedEvent -> Scheduler
17-10-25 11:08:56.2|Trace|EventAggregator|ApplicationStartedEvent <- Scheduler
17-10-25 11:08:56.2|Trace|EventAggregator|ApplicationStartedEvent -> TaskManager
17-10-25 11:08:56.2|Trace|TaskManager|Initializing jobs. Available: 10 Existing: 10
17-10-25 11:08:56.2|Trace|EventAggregator|ApplicationStartedEvent <- TaskManager
17-10-25 11:08:56.2|Trace|EventAggregator|ApplicationStartedEvent -> IndexerFactory
17-10-25 11:08:56.2|Debug|IndexerFactory|Initializing Providers. Count 12
17-10-25 11:08:56.3|Trace|EventAggregator|ApplicationStartedEvent <- IndexerFactory
17-10-25 11:08:56.3|Trace|EventAggregator|ApplicationStartedEvent -> MetadataFactory
17-10-25 11:08:56.3|Debug|MetadataFactory|Initializing Providers. Count 4
17-10-25 11:08:56.3|Trace|EventAggregator|ApplicationStartedEvent <- MetadataFactory
17-10-25 11:08:56.3|Trace|EventAggregator|ApplicationStartedEvent -> DownloadClientFactory
17-10-25 11:08:56.3|Debug|DownloadClientFactory|Initializing Providers. Count 15
17-10-25 11:08:56.3|Trace|EventAggregator|ApplicationStartedEvent <- DownloadClientFactory
17-10-25 11:08:56.3|Trace|EventAggregator|ApplicationStartedEvent -> UserService
17-10-25 11:08:56.3|Trace|EventAggregator|ApplicationStartedEvent <- UserService
17-10-25 11:08:56.3|Trace|EventAggregator|ApplicationStartedEvent ~> ConfigFileProvider
17-10-25 11:08:56.3|Trace|EventAggregator|ApplicationStartedEvent ~> HealthCheckService
17-10-25 11:08:56.3|Trace|EventAggregator|ApplicationStartedEvent <~ ConfigFileProvider
17-10-25 11:08:56.4|Trace|Owin|SQLite error (5): database is locked
```

**Comment by jpdillingham** [comment]
I'll also add that the math works out to the problem having been introduced about a month ago, which is when I added an additional indexer and fiddled with some other indexer-related settings.  The configuration has otherwise not been touched, other than perhaps adding a series or two.

**Comment by Taloth** [comment]
@jpdillingham What kind of releases are in the PendingReleases table? I'd like to figure out why they're kept. It's possible to have that many pending releases, but only in specific configurations.
The performance issue is a separate problem which I'm hoping to address in a future date.

**Comment by jpdillingham** [comment]
Episodes from the same series, sequential seasons, and episode 01.  All were grabbed from RARBG, and all were added around a month ago which is when the problem began.  I would guess that they originally came in as part of the same RSS sync and somehow got stuck somewhere at the same time due to some edge scenario introduced while I was fiddling with settings.

@Taloth if you'd find it helpful I can send you a copy of my database through some non-public avenue.

**Comment by Taloth** [comment]
I already received a database from markus a few hours ago and I was able to find a bug that caused the same release to be duplicated on each RssSync (so exponentially). After a fix the sample db went from 1800+ to 18.

Are you on the develop branch?

**Comment by Taloth** [comment]
Not released to develop yet due to some build issues, hopefully tomorrow.

**Comment by Taloth** [comment]
Released to 2.0.0.5049 (develop)

@jpdillingham Can you let me know if that release resolves the issue. There are quite a bit of changes related to the Pending queue in that particular release, so please let me know if you see anything odd.

**Comment by sheikr** [comment]
@Taloth Fixed the issue for me. Thanks!

**Comment by CupricReki** [comment]
@Taloth Switched to develop from master just now. Issue fixed. Thanks!

**Comment by Mark7even** [comment]
I am having trouble locating where the development/master switch is.

**Comment by Dnkhatri** [comment]
@Mark7even 
https://github.com/Sonarr/Sonarr/wiki/Release-Branches

**Comment by Taloth** [comment]
@sheikr @CupricReki Thanks for confirming.

_PS: You might want to set the release branch back to 'master' after installing that develop version, it won't downgrade, but that'll automatically put you back on the right branch when the next master release goes out._

**Comment by jpdillingham** [comment]
@Taloth confirm fixed on my machine.  The "stuck" releases showed up in the releases section (they didn't previously) and I was able to delete them via the UI.  Thanks!

**Comment by markus101** [comment]
Fixed in develop, will be in the next release.
