### ISSUE TITLE
Adding existing series from network drive - wrong path selection

### ISSUE THREAD

**Issue by buffos** [Sonarr/Sonarr#2206]
If I select to add an existing series, from example from \\mynetwork\tvseries , the selected path
for any existing series, I select, is the first directory in the list of all subdirs of the above folder

For example, if I have a folder #recycle_bin , and when sorted this is the top subfolder of \\mynetwork\tvseries, the selected path for any series I choose to add, is \\mynetwork\tvseries\#recycle_bin

**Comment by markus101** [comment]
Please use the forums for support.

It sounds like you're selecting the path for the TV folder itself instead of the root folder that the series folder resides in. If you select `\\mynetwork\tvseries` you'll be able to choose which series under that folder you wish to import.

**Comment by buffos** [comment]
Νο \\mynetwork\tvseries  is the root folder and its definitely a bug. As a programmer I know when i hit a bug or the program is to be used differently. I am 100% sure it's a bug

When i select  \mynetwork\tvseries , on top... it says....
\\mynetwork\tvseries\{first_folder_sorted}

and then it lists all the series in the \mynetwork\tvseries CORRECTLY

Then if i try to add a series from disk, it associates it with \\mynetwork\tvseries\{first_folder_sorted}
and have to change it manually

**Comment by buffos** [comment]
try it in a network drive and you will see.

By the way, it used to work fine.
