### ISSUE TITLE
API get all episodes without seriesId

### ISSUE THREAD

**Issue by morpheus65535** [Sonarr/Sonarr#2208]
Would it be possible to call the "episode" endpoint of API without having to specify the seriesId parameters? If I want to get all episodes, I have to call the API for each series and it take, I'm pretty sure, more time for my end users.

Thanks!

**Comment by markus101** [comment]
Why do you need to fetch every episode?

That could easily 10's of thousands of episodes and would would a massive amount to serialize and then deserialize. I don't think it's it's something we want to add.

**Comment by morpheus65535** [comment]
Like we've talked before, I'm working on a subtitle companion for Sonarr. I need a way to update my database with episodes in Sonarr that have "hasFile" set to true. For now, I have no way to get only what's new since my last sync. Actually, it take me 18 seconds to update 2500 episodes by doing something like 140 call to the episode endpoint. You got a better idea? :-)

**Comment by morpheus65535** [comment]
To give you a preview:

![image](https://user-images.githubusercontent.com/5130500/31209799-8b5033a8-a95b-11e7-8a8b-ad06f863fda9.png)

**Comment by markus101** [comment]
Fetching the history filtered to imported events only would probably make the most sense, that way you get them chronologically ordered and don't need to re-process every episode multiple times. The one downside that comes to mind is episodes that are dropped in the series folder and not imported by Sonarr, but those aren't really going to work for subtitles since they won't have a scene name unless the user doesn't rename files.

If users are running this as a separate service why would they need to worry about how long it takes?

**Comment by morpheus65535** [comment]
In fact, I was more concerned about not taking to much processing time from Sonarr but it seems it doesn't even notice that I'm pumping all that data from the API. I can keep browsing the interface of Sonarr like nothing's happening.

I think I'll keep using the episode endpoint for now. The history endpoint filtered to imported still need to return me all of the imported episode since the initial scan of Sonarr, right? I can do paging but not based on a time stamp or something useful for me... :-/

**Comment by morpheus65535** [comment]
@markus101 would it be possible to add a filter to the history endpoint to get only the records since an epoch time stamp? Something like "since=1507224590" would be great for the automatic sync that should occur on a regular basis (~5 or 15 minutes probably).

**Comment by markus101** [comment]
I think we could do that, like every other date in Sonarr it'd be ISO-8601 though.

**Comment by Taloth** [comment]
Wouldn't it be easy enough to just fetch a page, and check the time yourself? It's basically how we do the rss feed of indexers that support paging.
(I'm not opposed to adding the filter option)

**Comment by morpheus65535** [comment]
I think that the more efficient way would be to get all required records with one single call to the history endpoint. I'm pretty sure that it's easier to do a SELECT with a WHERE clause on your side than for me do call the API until I get the last record required.

For the date format, I think I could make it work with an ISO-8601 formatted date. ;-)

Ok, now the question that hurt the most: when could you work on that? :-)

I think I'll would be able to release a first beta version in 2 or 3 weeks that include automatic episodes sync with Sonarr. For now, I can work with my call to the episode endpoint for each series but it would be really nice to release it with some kind of incremental sync.

Thanks guys!

**Comment by Dnkhatri** [comment]
Will your companion app be able to tell if the episode already has internal subs and does not need to download. These days many of the web dl already have internal english subs.

**Comment by markus101** [comment]
New API endpoint is `/api/history/since` and takes two query string parameters:

`date` (required): Ideally an ISO 8601 formatted date.
`eventType` (optional): Numeric representation of `HistoryEventType` (https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/History/History.cs#L32)

Example: `/api/history/since?date=2015-10-22T17:59:24Z&eventType=3`

**Comment by morpheus65535** [comment]
@Dnkhatri Yes, it detect internal and external subtitles. Indeed, the label of the subtitle language must be correct for the companion app to recognize it.

**Comment by morpheus65535** [comment]
@markus101 Thank you very much. I'll take a look at it in the next day. Working hard to integrate task scheduler actually. Should be fine within a week.

Here's a docker container if someone is interested in trying it:
https://hub.docker.com/r/morpheus65535/bazarr/

Everything is still in manuel mode (you have to click on a button in the web interface.

**Comment by morpheus65535** [comment]
When do you think you're going to merge this to master? I can't deploy it if only those using development branch ca use it... :-)

Thanks!

**Comment by markus101** [comment]
Not exactly sure when, I don't think it'll be much longer unless some issues arise.
