### ISSUE TITLE
Monitored daily shows off by exactly two weeks

### ISSUE THREAD

**Issue by rgrue** [Sonarr/Sonarr#2218]
I noticed that a daily series I monitor wasn't downloading last week, so I logged onto Sonarr to look in the Calendar, and noticed that they appeared to be downloaded, but when opening the episode in question, the file linked was from two weeks previous. 

Here's an example of an episode that aired on Oct 2nd, but is being linked with Oct. 16th (today is Oct 8th):

![sonarrdaily](https://user-images.githubusercontent.com/7606987/31318022-13507366-ac00-11e7-98e4-c5663b6a3f7e.PNG)

Not sure where to even start digging into this one, let me know what more information would be useful.

Thanks!

**Comment by markus101** [comment]
See https://github.com/Sonarr/Sonarr/issues/2215
