### ISSUE TITLE
Downloading Episodes - S01E01 - Downloading "101"

### ISSUE THREAD

**Issue by AdamWillford** [Sonarr/Sonarr#2220]
Hi there,

First issue I've posted on here so hoping I get all the details needed.

I'm trying to download some anime, in this case Dragonball Z.  

However with the episode namings:

Season 1, Episode 2 is picking up: Dragonball.Z.102.1080p.BluRay.x264-DHD-AsRequested - which is actually episode 102.

So it should be 002 instead (Dragonball.Z.002.1080p.BluRay.x264-DHD-AsRequested) 

The category is set to Anime.

Anyone come across this or can advise?

Thanks,

Adam

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by M0UL** [comment]
make sure the series type is set to anime.

i think there is a problem with sonarr and absolute  nubering with triple digits
https://github.com/Sonarr/Sonarr/issues/1125

**Comment by M0UL** [comment]
it probaly has to do with the 00, if there was a release with  2 sonarr wil probaly find it.

**Comment by AdamWillford** [comment]
I thought the same but sadly there is a 002 and a 102 and it picks the 102 one for S1E02.  

Series type is also set to Anime

Ta,

Adam

**Comment by markus101** [comment]
This has to do with Sonarr having no way to determine it should use absolute parsing for 102 instead of treating it as season+episode number (common with some release groups) as there is no release group or hash in square brackets at the beginning or end of the filename.
