### ISSUE TITLE
Check for "Empty" NZB's

### ISSUE THREAD

**Issue by Safihre** [Sonarr/Sonarr#2221]
Maybe this was already proposed somewhere, but couldn't find it:
I think Sonarr should do very basic processing of the NZB's it fetches. 
Many indexers return error codes in the body instead of sending failure headers (I assume Sonarr parses those already), for example Drunkenslug just gave me this:
```xml
<error code="501" description="Download limit reached, please upgrade your account or wait 24 hours. See https://drunkenslug.com for details"/>
```
SABnzbd will then say `Empty NZB file`, which is confusing for users ([example](https://www.reddit.com/r/usenet/comments/74fykx/i_dont_understand_these_empty_smb_errors_can/)).

I propose that the minimal it should do is check if the text `<nzb` is within the data it fetches.

**Comment by thezoggy** [comment]
in sickbeard/sr world, the app sends the url over to sab so it can just process it. 

sonarr is different because it handles the download then sends it over to sab. (why the failure nzb and other indexer related things dont work within sab since it doesnt talk to the indexer.. sonarr does).

**Comment by markus101** [comment]
There is an existing issue for this: https://github.com/Sonarr/Sonarr/issues/263

The fact that they're returning an error in the NZB instead of as a header (especially a 429 header which they _do_ return when API limits are hit normally, is news to me though. 😞
