### ISSUE TITLE
Configure sonarr using text based configuration only

### ISSUE THREAD

**Issue by redouaneB** [Sonarr/Sonarr#2226]
Is there a way to configure sonarr using only text based configuration (put under control), and not having to do any tuning by hand using the web interface ? It seems that only some system configuration parameters are managed by the `config.xml` file, but not general settings like indexers, profiles, quality or the download client.

**Comment by markus101** [comment]
You can use the API (see how the UI uses the API as everything it does is via the API). Generally if things are not documented they could change without notice, though we do our best to not do that.

`config.xml` only contains minimal settings required to start the web server and setup logging.
