### ISSUE TITLE
Feature Request: Sync between two+ instances of Sonarr

### ISSUE THREAD

**Issue by attritionorg** [Sonarr/Sonarr#2227]
For those that run Sonarr on two computers (e.g. home and laptop), the ability to sync the series and their attributes (e.g. which episodes you have downloaded) would be really nice. Thanks!

**Comment by markus101** [comment]
Sorry, but this isn't something that we have plans to do. You may be able to have something use Sonarr's API to achieve this, but not something we'd implement, at least at this time.
