### ISSUE TITLE
RSS Feed as download client option

### ISSUE THREAD

**Issue by matteosaitta** [Sonarr/Sonarr#2228]
Hello,

I'd like to have a RSS feed as a download client option(like an equivalent to a torrent blackhole, not checking the download status live but only rely on library updates) with a list of .torrent urls to be downloaded contained in the stream, due to my nas client being unable to use the blackhole option(qnap download station :/ ). Is there any plan to add this feature? If it isn't is there any download client code skeleton i could start with to create this?

**Comment by markus101** [comment]
That sounds like something they should add, but I digress. No this is not something we have planned, you could look at the Blackhole download clients to add it yourself, but the better way would be to add it to Sonarr as a download client instead of a workaround. https://github.com/Sonarr/Sonarr/issues/1815

**Comment by matteosaitta** [comment]
Understood, I'll circle around my torrent client options to see if there are no alternatives to make my own. In that case i will try to create a new rss feed download client made from the blackhole download client. Will that be acceptable?

**Comment by markus101** [comment]
For your own personal use, that'd properly work, but it's not something that we'd want to support. Time would probably be better spent adding a proper download client for QNAP, but I don't have any insight into how complicated that may be (Synology's Download Station is quite complicated from what I've seen).
