### ISSUE TITLE
Fedora install instructions are outdated (yum replaced by dnf)

### ISSUE THREAD

**Issue by Noedel-Man** [Sonarr/Sonarr#2229]
The install instructions are outdated for Fedora (https://github.com/Sonarr/Sonarr/wiki/Installation-Fedora-20) yum is replaced by dnf since Fedora 22, so things like `yum-config-manager` don't work anymore.
Also disabling SELinux seems like a bad work-around. 

Can this wiki please be updated to support Fedora 26, so I can enjoy this beautiful software :).

**Comment by markus101** [comment]
The wiki is community maintained, not something that we screen before content is added. Someone will need to go through the install and update the wiki accordingly.

**Comment by Noedel-Man** [comment]
Thank you for your reply,
however I'm now unable to install Sonarr. What other way is there to install Sonarr without using yum on Fedora?

**Comment by markus101** [comment]
The generic Linux installation instructions should still work: https://github.com/Sonarr/Sonarr/wiki/Installation#other
