### ISSUE TITLE
Add warning that disk is predicted to fill up based on sizes of files in queue

### ISSUE THREAD

**Issue by mturley** [Sonarr/Sonarr#2233]
First of all, Sonarr is great, I only just discovered it and have enjoyed it so far. I donated $10 to you guys.

I have a feature request / suggestion: One of the things that bugged me when I first started up Sonarr and imported my media library is, it detected a bunch of missing seasons of monitored series, and queued up enough downloads in Deluge that it would have filled the rest of my disk.  I'm glad I caught it and disabled the torrents before it filled up, but **it would be nice if there were some kind of warning on the Sonarr UI that the total size of the files in the Wanted queue is larger than the free space on disk.**

That's all!  Thanks again.

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by fryfrog** [comment]
This would probably make more sense being in the downloader like NZBGet, SABNzbd or any of the other torrent daemons. They have a better view of the download queue. Sonarr would only see TV shows in most setups.

**Comment by mturley** [comment]
That's fair. I just think Sonarr might be a nice place for that alert to be broadcast from, since I already have Sonarr integrated with Pushbullet and Discord for other notifications. It automates a lot of other stuff around files, and it does scan my disk already, it could just look at the available space on that disk.

**Comment by mturley** [comment]
Oh I see what you're saying, Sonarr might not necessarily know the expected file sizes of episodes in the queue.  Yeah, that's an issue.

**Comment by markus101** [comment]
I think it becomes complicated quite quickly and could easily be inaccurate depending on the user's setup. Even the difference in wanting a UI warning vs a notification adds to the complication and a separate issue (https://github.com/Sonarr/Sonarr/issues/1798).

If the user has a single location where series are stored it's not too complicated, add the size of all things in the queue and check if that exceeds the free space of the disk. If they have multiple locations they all need to be checked and apply only the downloads that apply to that drive and to complicate it even further, if multiple locations were actually on the same storage space, Sonarr may not know that they are part of the same storage and miscalculate it.

I see some benefit to this, but this isn't something we want to commit to doing at this time. Tagging this so we don't lose track of it completely, but closing it out.
