### ISSUE TITLE
Specify which indexer to use per show

### ISSUE THREAD

**Issue by jvacek** [Sonarr/Sonarr#2234]
Some people might have multiple indexers using both torrents and nzb set up and would like to have shows A B C only snatched from Torrent Indexer 1 (say BTN), shows D E F from Torrent Indexer 2 (e.g. Jackett+AnimeBytes) and shows G H I from Torrent indexer 3 (Say HDBits).
Currently it is possible to either restrict a show to torrent or nzb through delay profiles, but it is not possible to further specify which indexer. Knowing this feature exists I can imagine it being relatively simple extending it to trackers.

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/487
