### ISSUE TITLE
Add a new tracker

### ISSUE THREAD

**Issue by rootb3** [Sonarr/Sonarr#2236]
Can you please add [torbox](http://thepiratebay.torbox.net/) to the Torznab indexer? Thanks.

**Comment by M0UL** [comment]
it needs to support Torznab  for it to be added. i cannot find anything  on that site that it support Torznab.

**Comment by markus101** [comment]
It looks like this is a TPB clone which doesn't have an API and won't be supported directly by Sonarr. You may be able to use it with TPB in Jackett.
