### ISSUE TITLE
crashing when synology restart

### ISSUE THREAD

**Issue by Nakash23** [Sonarr/Sonarr#2238]
Sonarr version: 2.0.0.4949
Mono version (from synocommunity): 4.6.2.7-8

Hello,
i installed on my synology up to date (6.1.3-15152 update 8) mono and sonarr (and radarr) from the synocommunity.
Everything works except some crashs some times from sonarr.
It happens when the synology restart.

Thanks a lot for your help.

**Comment by markus101** [comment]
Please open a thread on the forums for support. We'll need trace logs to investigate further.

**Comment by Nakash23** [comment]
hello,

where is the forum please?
Thanks

**Comment by markus101** [comment]
https://forums.sonarr.tv - it's part of the template when you open a new issue here are well.

> Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)
