### ISSUE TITLE
Custom Script - On Download include Extra Files

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#2239]
Include extra files for custom scripts (similar to the actual video files).

**Comment by cuki** [comment]
Continuing discussion regarding environment variables here from [Improve handling of associated/extra files](https://forums.sonarr.tv/t/improve-handling-of-associated-extra-files/16449) forums topic.

Both on download/upgrade imported extra files should be listed which were moved/removed within a environment variable.

When extra files (e.g. `.nfo`,`.srt`) are deleted on upgrade they should be included in the existing environment variables (`sonarr_deletedrelativepaths`, `sonarr_deletedpaths`).

On download/upgrade introduce new environment variable(s) specifically for additional/extra files being moved/removed on download/upgrade.

My proposal for new environment variables would be the following:
- `sonarr_extra_relativepaths` or `sonarr_extrafile_relativepaths`, Pipe (`|`) separated list of extra files
- `sonarr_extra_paths` or `sonarr_extrafile_paths`, Pipe (`|`) separated list of full paths for extra files

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
