### ISSUE TITLE
Doesn't Detect My Mapped Network Drive

### ISSUE THREAD

**Issue by Bakerflix** [Sonarr/Sonarr#2242]
First time user...

When selecting a drive for setting it up, it won't let me select my S:\ drive which is a mapped NAS drive.

Any suggestions?

**Comment by markus101** [comment]
Please use the [forums](https://forums.sonarr.tv) for support, but first read the FAQ as this is covered there.

**Comment by Bakerflix** [comment]
I spent about 15 minutes trying to track down the FAQ. Did it disappear?

If not, could I get the link? Thanks

**Comment by markus101** [comment]
It lives in the Wiki: https://github.com/Sonarr/Sonarr/wiki/FAQ. It's also the first result when googling `Sonarr FAQ`.
