### ISSUE TITLE
Assume REMUX is BluRay

### ISSUE THREAD

**Issue by piejanssens** [Sonarr/Sonarr#2243]
I just did a manual import of a 2160p REMUX release, source is a UHD BluRay.
The name of the folder did not inlcude 'bluray', it did include '2160p' and 'REMUX', but it showed up as "2160p HDTV". It's more correct to assume that 'remux' is always bluray.
I guess this is also true for the matching automatic search results.

**Comment by markus101** [comment]
At the moment this is expected until REMUX is added as a separate quality, which is covered by https://github.com/Sonarr/Sonarr/issues/1774
