### ISSUE TITLE
Sonarr possible ignoring episodes with & symbol in the name

### ISSUE THREAD

**Issue by ignoremenow** [Sonarr/Sonarr#2244]
## Bug Report

This was working sometime before the 10th of this month. But for some reason if a series has an & in it, sonarr ignores it.

### System Information/Logs

**Sonarr Version:**
Develop - 2.0.0.5028

**Operating System:**
Synology

**.net Framework (Windows) or mono (macOS/Linux) Version:**
4.6.2

**Link to Log Files (debug or trace):**
https://pastebin.com/aUNr6rPB

### Additional Information

The logs are for the search of
https://www.thetvdb.com/?tab=series&id=289886
the xem listing for this that was working
http://thexem.de/xem/show/3962

So In sonarr for s02e01 I would expect to see downloads/listing's for Kekkai Sensen & Beyond s02e01

All the episodes I see have Blood Blockade Battlefront in the name and also some do have an & sign but I think that just seeing Blood Blockade Battlefront allows them to be shown.

I am expecting to see a listing that would include
[HorribleSubs] Kekkai Sensen & Beyond - 01 [1080]

**Comment by markus101** [comment]
This isn't a new issue, `&` is replaced with `and` when searching (pre-dates anime), but generally anime keeps the `&` in titles instead.

This will be done as part of https://github.com/Sonarr/Sonarr/issues/1225
