### ISSUE TITLE
Log table on /system/logs is blocked by some adblockers

### ISSUE THREAD

**Issue by jamesmacwhite** [Sonarr/Sonarr#2245]
Hi Team Sonarr.

A user of both Sonarr and Radarr highlighted that log table on `/system/logs` is blocked by some adblockers. Original issue info below:

https://github.com/Radarr/Radarr/issues/2209

I found that it looks like `/api/log` request is listed in the [EasyPrivacy list](https://easylist.to/easylist/easyprivacy.txt) as a generic regex rule. Confirmed on uBlock Origin and likely other plugins that make the use of the EasyPrivacy list (which I believe is pretty well used in various plugins).

The short term solution was to add a dissmissable alert box on this page to inform the user of this potential issue. Of course the user can whitelist the domain Sonarr/Radarr sits on to avoid this problem too.

The longer term solution, would probably to be tweak the API call, so it isn't flagged by EasyPrivacy. I don't think getting `/api/log?` removed from the EasyPrivacy list is realistic, because it probably matches some other ad services, but in the case of Sonarr and Radarr its a false positive, however as its part of the API, its maybe not easy as just changing it without causing breakage elsewhere!

I'm happy to PR the same change I made to Radarr for stop gap solution, but wanted to inform you guys of the issue too and get your thoughts.

Many thanks!

**Comment by markus101** [comment]
We've fixed this issue in v3 (different route). I'm not too concerned about updating the current view as it has the fortunate side effect of people looking at the log files instead of the logs table when reporting issues. Call it a happy accident. 😄

**Comment by jamesmacwhite** [comment]
@markus101 Thanks for your reply. Ha ha no worries then! Thanks for the update!

**Comment by Taloth** [comment]
Btw. It was a known issue: https://github.com/Sonarr/Sonarr/issues/1792

The thing is that EasyPrivacy is their most extensive blocklist, and it's ridiculous. It contains many generic regex that would easily break sites, but people don't know that and just enable whatever blocklist they can find. Their basic 'EasyList' is better suited for normal users.

**Comment by jamesmacwhite** [comment]
@Taloth My bad. Didn't know it was already reported as an issue on GitHub before.

Yeah I agree. I was looking through some of the rules and some of them are way too generic and probably do more harm than good. I guess what doesn't help either is often adblockers will pre-configure lists by default and its a common one to have enabled.

Good to know its been identified before. It would seem the only solution for Radarr is to also change the route.

Thanks for info!
