### ISSUE TITLE
Unrelated files getting silently renamed

### ISSUE THREAD

**Issue by EchterAgo** [Sonarr/Sonarr#2246]
### System Information/Logs

**Sonarr Version:** 2.0.0.4949

**Operating System:** Windows 10

**.net Framework (Windows) or mono (macOS/Linux) Version:** 4.7.1

**Link to Log Files (debug or trace):** https://pastebin.com/NsSNYnQ9

### Additional Information

Whenever Sonarr wants to rename a file, it also renames unrelated files. In my season folders I have files called complete.md5 which I use for listing purposes and for verifying checksums. I also have a original.txt file with more info about the source of the contents. These files get renamed to the same name as some of the episodes each time there is a file to rename. The logs say only 1 file got renamed, but clearly it is renaming much more files.

**Comment by markus101** [comment]
We need at least debug log files, better yet in this case trace log files.

**Comment by EchterAgo** [comment]
Will check on how to provide those.

**Comment by markus101** [comment]
Closing. We can reopen if additional information is available.
