### ISSUE TITLE
Telegram Notifications to Channels

### ISSUE THREAD

**Issue by Veldkornet** [Sonarr/Sonarr#2248]
Currently the notifications only go to users or groups. 
Ideally, I’d like to have messages sent to channels as well. 

Ive added my bit to the private channel, filled in the relevant information in Sonarr and tested this, but it fails.

**Comment by sayem314** [comment]
Telegram channel notification works for me. Here is my settings:

![](https://i.imgur.com/oGLsfkr.png)

See: https://imgur.com/a/quHQo

**Comment by Veldkornet** [comment]
I’ve done that, but I’m trying to add the channel by ID. 
Because the channel is private, and once you add a name then it’s a public group. 

But when I put it the group ID, it can’t validate it.

**Comment by sayem314** [comment]
Works fine for me on newly created private channel.

![](https://i.imgur.com/QpEaS7M.png)

I've used @getidsbot to parse channel id. Note that channel start with an `-` not `@` so you must use `-` with channel id.

**Comment by Veldkornet** [comment]
Ah, you are 100% correct. I always missed the "-" sign, didn't even notice it! :) My bad!
