### ISSUE TITLE
Flood as download client

### ISSUE THREAD

**Issue by liquidox** [Sonarr/Sonarr#2252]
I would like to see https://github.com/jfurrow/flood supported as Download client.

Not much else to write I think 👍

**Comment by markus101** [comment]
Looks like flood is just another frontend for rTorrent. I don't see any mention of an API that would be used instead of rutorrent, though that would be another failure point.

I think time would be better spent on https://github.com/Sonarr/Sonarr/issues/2007 instead.

**Comment by liquidox** [comment]
Ok, thanks for the quick response!

**Comment by markus101** [comment]
> rTorrent needs to be installed with XMLRPC configuration. If you are currently using a web UI for rTorrent, you've already done this.

(from https://github.com/jfurrow/flood#pre-requisites)

It requires the XMLRPC configured anyways (rutorrent, etc), so definitely an extra point of failure for no added benefit. It does look a lot prettier though
