### ISSUE TITLE
Feature Request: Open/play & Track Seen Episodes

### ISSUE THREAD

**Issue by sjorre** [Sonarr/Sonarr#2253]
## Feature Request

Hi, could you please consider inserting the following features into Sonarr:

- As the SONARR already has the path to the file, why not enable it to open the video file and run it using the default media player.
- A method of tracking the seen episodes, by a feature as simple as a checkbox. At the moment I'm using Tags in OSX to do just this, but having this all in one place makes it easier. Basically something analog to Sidereel.com

Thanks

sjorre

**Comment by markus101** [comment]
1. That is only possible in some cases and in others would require a browser plugin. We have no plans to support this functionality.
2. No plans to support a manual switch in the UI for this at this time, Media center apps, Plex, Kodi, etc are well suited for this. https://github.com/Sonarr/Sonarr/issues/309 and https://github.com/Sonarr/Sonarr/issues/314 both have some information on how we'd like to pull that information in from other apps if we make use of it.

**Comment by thoughtleader** [comment]
[Config]
path = /media/plex/TV/

[API]
url = hostname:8989
key = 8efusdjfoijsdfsdjjd0fjs0d9f9bullshit

[Series]
lastweektonightwithjohnoliver = 3
