### ISSUE TITLE
Feature request: Change series / season for multiple selection in manual import

### ISSUE THREAD

**Issue by IKatsu** [Sonarr/Sonarr#2254]
### What problem are you looking to solve?
When manually importing a series, you have to click and modify every file to set the series/season etc when the files are not recognized.
It would be nice to have a feature where you can just set the series/season for everything that's selected.
Some sort of custom pattern to ID the files would be nice too but that might be a bit too much work vs returns.

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/1643 (will be in v3).
