### ISSUE TITLE
Optimize RSS Sync process

### ISSUE THREAD

**Issue by tiagoboldt** [Sonarr/Sonarr#2259]
When there is no episode pending for download, syncing with RSS feeds is a pointless exercise, as nothing will ever be added to the download list. I suggest changing this behavior to only process the RSS feeds when there is at least one item pending to be downloaded.

**Comment by markus101** [comment]
Unless Wanted: Missing and Wanted: Cutoff Unmet are completely empty there is a reason to continue to run RSS Syncs, also that doesn't cover episodes that are released before their air date (sometimes airing the day before in another country) and typically Sonarr has the primary country, not the pre-release country.

**Comment by Dnkhatri** [comment]
I use sonarr for Asian dramas where many of release times are wrong by 12-14hrs unless tvdb allows to set GMT times. I would prefer the sync to stay on.

**Comment by tiagoboldt** [comment]
This suggestion wouldn't work well for all users so I'll go ahead and close the issue.
