### ISSUE TITLE
Sonarr System Status Disk Space - does not see OSX new APFS Volumes

### ISSUE THREAD

**Issue by paulodell** [Sonarr/Sonarr#2261]
## Bug Report
Sonarr System Status Disk Space - does not see OSX new APFS Volumes

### System Information/Logs

**Sonarr Version:**
Version 2.0.0.4949

**Operating System:**
MacOS High Sierra Version 10.13

**.net Framework (Windows) or mono (macOS/Linux) Version:**
Mono Version 5.2.0.224

### Additional Information
Since changing my drives to use APFS they are not visible on the Disk Space page of Sonarr, the Drive selection and link to data is fine, just the useful Disk Space feature does not show the drives at all

**Comment by paulodell** [comment]
Upgraded Mono Version

Mono Version
5.4.0.201 (2017-06/71277e78f6e Thu Sep 21 19:22:55 EDT 2017)

**Comment by kappaknight** [comment]
Is anyone else running Sonarr and Radarr on High Sierra? Both of my services crashed and can't be pulled up after the upgrade. I'm guessing it's the DB files, but not sure if a recovery will fix it permanently.

**Comment by markus101** [comment]
@kappaknight please use the forums for support and not an unrelated github issue.

**Comment by paulodell** [comment]
Why has this issue been closed? Apart from kappaknight hijacking it the problem still exists.

**Comment by markus101** [comment]
![image](https://user-images.githubusercontent.com/413544/33570435-af612e72-d8e1-11e7-83c1-d29a52e4d95b.png)


The issue has been fixed in the commit above. It's not fixed in the current release, but issues are closed when the fix is added.

**Comment by paulodell** [comment]
Great! Sorry I missed the commit, thanks for the fix, I look forward to trying it out.
