### ISSUE TITLE
Binding to localhost specifically doesn't work

### ISSUE THREAD

**Issue by sayem314** [Sonarr/Sonarr#2263]
## Bug Report

why changing `<BindAddress>*</BindAddress>` to `<BindAddress>127.0.0.1</BindAddress>` does not work? I'm using reverse proxy with multiple domains.

here is my reverse proxy config:

    sonarr.xxxxxx.me, s.xxxxxx.me {
        cache
        proxy / 127.0.0.1:8989{
            transparent
        }
    }

`<BindAddress>*</BindAddress>` works fine. But I want to block direct access!

sonarr config:

    <Config>
        <LogLevel>Info</LogLevel>
        <Port>8989</Port>
        <UrlBase></UrlBase>
        <BindAddress>127.0.0.1</BindAddress>
        <SslPort>9898</SslPort>
        <EnableSsl>False</EnableSsl>
        <ApiKey>xxxxxxxxxxxxxxxxxxxxxxxxxxx</ApiKey>
        <AuthenticationMethod>Forms</AuthenticationMethod>
        <Branch>master</Branch>
        <LaunchBrowser>False</LaunchBrowser>
        <SslCertHash></SslCertHash>
        <UpdateMechanism>BuiltIn</UpdateMechanism>
    </Config>

### System Information/Logs

**Sonarr Version:**
 2.0.0.4949

**Operating System:**
Debian 9 (Stretch)

**.net Framework (Windows) or mono (macOS/Linux) Version:**
5.4.0.201

**Link to Log Files (debug or trace):**
https://paste.ee/p/AD5bL

### Additional Information

Here is what I get after changing to localhost.

![](https://i.imgur.com/TwBH5Iq.png)

**Comment by markus101** [comment]
This is more of a question, not a bug report and really belongs on the forums.

It's how the binding actually works, it's binding to the host header, not to a specific IP/adapter. This is how the web server Sonarr uses does it, we'll be looking at options for another server in the future. If you want to block direct access a firewall would be your best bet at this time.

**Comment by sayem314** [comment]
@markus101 I see. Which web-server does sonarr use? Can you not embed nginx or caddy web server?

**Comment by markus101** [comment]
It's a .net managed web server (OWIN-based), which was the primary option for self-hosting (self contained web server), instead of relying on IIS, nginx, etc. Whether we could embed another webserver or not isn't really something we've investigated and not something we would want to support.

**Comment by kcobb** [comment]
ran into same issue when attempting to run behind a reverse proxy using nginx. To fix the Bad Request update your nginx config.

FROM: 
proxy_set_header Host $http_host;

TO:
proxy_set_header Host 127.0.01;

*this should only be done when changing the binding address to 127.0.0.1
