### ISSUE TITLE
Restricting on dual language ("DL") also grabs all WEB-DL

### ISSUE THREAD

**Issue by Elandril** [Sonarr/Sonarr#2264]
I have created a restriction tag "german-dl" to only consider dual language German releases with the following settings:
Must Contain: german dl

When applying this restriction normal releases are filtered as expected, but all WEB-DL releases are included, even if they are not marked as DL. Adding "WEB-DL" to the Must Not Contain does not solve the issue, since then all WEB-DL that are additionally marked DL are excluded.

Possible Solution:
Quality terms should not be considered as separate words, or alternatively be excluded from the filtering.

**Comment by fryfrog** [comment]
What happens if you put "german dl" and/or "german-dl" to make it one word?

**Comment by Elandril** [comment]
Also the "DL" doesn't have to follow directly after "german". Usually the "DL" is found a few words behind the "german".

**Comment by disrupted** [comment]
I ran into the exact same issue.

**Comment by Taloth** [comment]
if you want a space you can copy paste it from somewhere else (workaround). But it's better to anchor the keyword, like '.DL.', which would cover most scene releases.

Ignoring the quality part is out of the question, some ppl depend on it.

**Comment by Elandril** [comment]
Thanks for the tip with the anchoring, Taloth! I will give it a try.
