### ISSUE TITLE
Feature Request: Searching/Filtering the History API

### ISSUE THREAD

**Issue by pannal** [Sonarr/Sonarr#2265]
I'm the developer of the [Sub-Zero plugin](https://github.com/pannal/Sub-Zero.bundle) for the Plex Media Server environment.

SZ relies on detecting certain information about a media file partially from the filename itself. People like renaming their media files automatically using Sonarr, though.

In order to still being able to retrieve the original filename for matching suitable subtitles, I plan on using the history API of Sonarr for that. 

Unfortunately there doesn't seem to be a way of searching through the history by `importedPath` and extracting the `droppedPath` (as well as filtering the results by `"eventType": "downloadFolderImported"`.

Could something like this be implemented? Do you have a better idea for detecting the original pre-rename filename?

Thank you!

**Comment by markus101** [comment]
The episode file itself has a `SceneName` attached to it, which is the original name before importing, when known.

`importedPath` and `droppedPath` is extra data stored as JSON, not something that is meant to be searchable and there wouldn't be an efficient way to make it searchable.

Somewhat related (from the subtitles perspective at least): https://github.com/Sonarr/Sonarr/issues/2208

**Comment by pannal** [comment]
Oh, that sounds great.

> when known.
What exactly does that mean? Is that field only set if there was a rename action?

So how would the workflow here be?
- search (?) for the series ID via the API
- find the episode
- look for `SceneName`?

**Comment by markus101** [comment]
> What exactly does that mean? Is that field only set if there was a rename action?

Only set when imported from a download client I believe.

> So how would the workflow here be?
> - search (?) for the series ID via the API
> - find the episode
> - look for SceneName?

Pretty much, but once you have the episode you need to get the `episode file`, then use that to get the `SceneName`.

**Comment by pannal** [comment]
Thank you, works.

I already receive episodeFile data when querying the episode API endpoint. Is that intended or should I use a separate query to episodeFile?

**Comment by markus101** [comment]
If the episode file is there you can use it, no need to make another request for it.

**Comment by pannal** [comment]
OK great, thank you!

**Comment by pannal** [comment]
@markus101 how come the `sceneName` isn't always set? It seems to be linked to the `iNTERNAL` tag inside a filename. If that's there, `sceneName` isn't set.

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedEpisodes.cs#L149 and https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Parser/SceneChecker.cs cover the rules for it. Internal should have no effect on it, but maybe something else with how it's imported/the release name does.

If there is a specific issue with some releases, please open a new issue with the relevant bug information, closing this as this issue has been addressed already.
