### ISSUE TITLE
Feature Request: Allow Sonarr to re-sort the SABnzbd queue to force sequential episode downloading

### ISSUE THREAD

**Issue by CupricReki** [Sonarr/Sonarr#2266]
Here is the issue I run into:

Download fails 
Sonarr grabs replacement release
Sonarr adds new release to the end of SABnzbd queue 

<img width="776" alt="screen shot 2017-11-03 at 10 13 42 pm" src="https://user-images.githubusercontent.com/6509200/32402242-3543f106-c0e5-11e7-8d61-256ac9021fd8.png">

This results in episodes being downloaded out of order. Inconvenient if you just decided you wanted to watch a new series.

**Comment by markus101** [comment]
Close enough to https://github.com/Sonarr/Sonarr/issues/2076 I think.
