### ISSUE TITLE
Feature Request: top series search to add

### ISSUE THREAD

**Issue by ArmandH** [Sonarr/Sonarr#2267]
Hi,
Would it be possible  to build in a overview of for example top 25 series to be able to add them to your downloads, same as used in radarr movies section , for sure most be possible to use a list like 
top imdb tv charts
http://www.imdb.com/chart/toptv/?ref_=nv_tp_tv250_2
or
most popular tv shows:
http://www.imdb.com/chart/tvmeter?ref_=nv_tvv_mptv_4

So your able to read and select to add to sonarr, i think this would be a great addition to the app.

**Comment by markus101** [comment]
Issues that cover the same general idea:

https://github.com/Sonarr/Sonarr/issues/276
https://github.com/Sonarr/Sonarr/issues/354
https://github.com/Sonarr/Sonarr/issues/309

**Comment by ArmandH** [comment]
Ok thx I didn't find anything related but that suggestion is 2 years old and never implemented? Why not seems to me a very welcome option.

**Comment by markus101** [comment]
There are hundreds of open issues and only so much free time myself and anyone else contributing has to spend on Sonarr. Unfortunately no one else has found the time to implement it yet.
