### ISSUE TITLE
iptorrent indexer

### ISSUE THREAD

**Issue by archangel00uk** [Sonarr/Sonarr#2271]
Hi,

Have not looked at Jackett in awhile since I have setup, but have noticed overnight it's stopped communicating with my Sonarr server and have also noticed my Jackett version has been updated to 0.8.355.0.

I mainly use IPTorrent as my main tracker, but unable to find the indexer/tracker for IPTorrent in the list anymore - not sure if I am missing something? I was not able to find anything obvious on the forums or past issues.

Sorry if this has been asked/answered previously!

Thanks.

**Comment by markus101** [comment]
Please use the forums for support/questions.
