### ISSUE TITLE
NZBGet: Duplicate Keys and Scores

### ISSUE THREAD

**Issue by Nothing4You** [Sonarr/Sonarr#2280]
### What problem are you looking to solve?
Sonarr should have a download client setting to allow skipping dupe checking when importing.
When I add a new nzb to nzbget using the webinterface it allows me to mark a checkbox to skip dupe checking. This would allow downloading files even if they have previously been downloaded for other reasons.

![screenshot from 2017-11-09 22-37-12](https://user-images.githubusercontent.com/3694534/32630941-69b2f72e-c596-11e7-8d8c-8ab5baac69fe.png)

### Other Information
Related to #1721

**Comment by markus101** [comment]
What's the use case for ignoring the duplicate check in nzbget? (what problem does having it enabled cause?)

**Comment by Nothing4You** [comment]
I'm using the same nzbget instance for both sonarr and non-sonarr jobs. If I have for example downloaded some episode manually in the past and sonarr later fetches it via automatic search (manually triggered) it might find the same nzb on an indexer that I already downloaded manually. It will send the nzb to nzbget and it will just be moved to history as dupe right away instead of performing a download for processing via sonarr.

**Comment by markus101** [comment]
Gotcha, I think it'd make the most sense to handle this in a more automated fashion using nzbget's dupe keys/score. Disabling the dupe check entirely might make sense in some cases, but I think we should start with dupe keys/score.

https://nzbget.net/rss#duplicates

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
