### ISSUE TITLE
Bad parsing Quality

### ISSUE THREAD

**Issue by halali** [Sonarr/Sonarr#2281]
### System Information/Logs

**Sonarr Version:**
2.0.0.4991

**Operating System:**
Microsoft Windows 10.0.16299

**.net Framework (Windows) or mono (macOS/Linux) Version:**
.NET Framework 4.7.1

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**

### Additional Information

![sonarr](https://user-images.githubusercontent.com/17801420/32650347-ba4f8dc0-c5fd-11e7-8b92-af80e49584e6.png)

### What problem are you looking to solve?

Want to solve parsing problem for quality.
Victoria S01E07 - Motor zmen (CZ)[TvRip][HEVC][1080p]
is parsed as SDTV,

i think everything with tag TvRip is parsed as SDTV

**Comment by thezoggy** [comment]
the naming from a glance has glaring issues with it going against standards.. things in `[]` is an issue and info will get discarded.
it has tvrip.. which is assumed sdtv... but then inside that detection it looks for something to bump it up to highdef (HighDefPdtvRegex )..  like 'hr' or 'ws' but there is none.. and the 1080p in [] prob gets stripped out as the release group or sub group..   i suspect this torrent is coming in from jackett? you should prob have them 'fix' the torrents bad naming scheme to be compatible with what sonarr parsing

**Comment by halali** [comment]
yea i can replace regex in Definition

What it right format?

**Comment by UniverseXXX** [comment]
I've got a similar issue where HDTV being detected as SDTV.

> 17-11-17 10:59:09.1|Debug|Parser|Parsing string 'Van.Helsing.S02E07.HDTV.x264-KILLERS[ettv]'
17-11-17 10:59:09.1|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
17-11-17 10:59:09.1|Debug|Parser|Episode Parsed. Van Helsing - S02E07 
17-11-17 10:59:09.1|Debug|Parser|Language parsed: English
17-11-17 10:59:09.1|Debug|QualityParser|Trying to parse quality for Van.Helsing.S02E07.HDTV.x264-KILLERS[ettv]
17-11-17 10:59:09.1|Debug|Parser|Quality parsed: SDTV v1
17-11-17 10:59:09.2|Debug|Parser|Release Group parsed: KILLERS
17-11-17 10:59:09.2|Debug|AcceptableSizeSpecification|Beginning size check for: Van.Helsing.S02E07.HDTV.x264-KILLERS[ettv]
17-11-17 10:59:09.2|Debug|AcceptableSizeSpecification|Item: Van.Helsing.S02E07.HDTV.x264-KILLERS[ettv], meets size constraints.
17-11-17 10:59:09.2|Debug|LanguageSpecification|Checking if report meets language requirements. English
17-11-17 10:59:09.2|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Van.Helsing.S02E07.HDTV.x264-KILLERS[ettv]
17-11-17 10:59:09.3|Debug|ReleaseRestrictionsSpecification|[Van.Helsing.S02E07.HDTV.x264-KILLERS[ettv]] No restrictions apply, allowing
17-11-17 10:59:09.3|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. SDTV v1
17-11-17 10:59:09.3|Debug|QualityAllowedByProfileSpecification|Quality SDTV v1 rejected by Series' quality profile
17-11-17 10:59:09.3|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
17-11-17 10:59:09.3|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
17-11-17 10:59:09.3|Debug|DelaySpecification|Profile does not require a waiting period before download for Torrent.
17-11-17 10:59:09.3|Debug|HistorySpecification|Performing history status check on report
17-11-17 10:59:09.3|Debug|HistorySpecification|Checking current status of episode [2276] in history
17-11-17 10:59:09.3|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] SDTV is not wanted in profile

**Comment by thezoggy** [comment]
`Van.Helsing.S02E07.HDTV.x264-KILLERS` that is sd. hdtv is not the quality but the source. if it was HD it would contain the resolution tag with it 720p/1080p/etc.
