### ISSUE TITLE
Add the option that sonarr place episodes in files

### ISSUE THREAD

**Issue by ssccc** [Sonarr/Sonarr#2285]
Sonarr should place episodes in files for example the episode 8 should be in a folder named 08. And if i put them manually and rename the files sonarr put them out again

**Comment by markus101** [comment]
In folders you mean? You already can just add it to the episode naming format with the proper slash for your filesystem.

**Comment by ssccc** [comment]
i meant to put episodes in folders
@markus101
![image](https://user-images.githubusercontent.com/32818143/32742826-31760070-c8b3-11e7-92ce-b3cc6ec3dc78.png)
