### ISSUE TITLE
Sonarr unable to parse multiple season names

### ISSUE THREAD

**Issue by RukiaXi** [Sonarr/Sonarr#2289]
## Bug Report
Sonarr seems to be unable to parse shows that have multiple season names on thexem, it only seems to get the alias. Because of this, it's unable to find any eposides for anything other than season one. If I manually search for Season one episodes, it finds pretty much any season of episodes for that anime.

### System Information/Logs

**Sonarr Version:**
2.0.0.5059

**Operating System:**
Ubuntu 17.10 (GNU/Linux 4.13.0-16-generic x86_64)

**.net Framework (Windows) or mono (macOS/Linux) Version:**
mono (linux) version 5.4.1.6

**Link to Log Files (debug or trace):**
https://pastebin.com/kshax8rs

**Browser (for UI bugs):**
Chrome 62.0.3202.94 (Official build) (64-bits)

### Additional Information

Example: http://thexem.de/xem/show/3999

**Comment by markus101** [comment]
You need to look at debug logs to see the requests Sonarr is making, info logs the series title and the episode that is being searched for, not the alias or absolute episode number in that season.

```
17-11-14 12:22:27.1|Info|NzbSearchService|Searching 1 indexers for [Food Wars! Shokugeki no Soma : 44]
17-11-14 12:22:27.1|Debug|Torznab|Downloading Feed https://nyaa.pantsu.cat/feed/torznab?t=search&cat=5070&extended=1&offset=0&limit=50&q=Shokugeki%20no%20Soma+44
17-11-14 12:22:31.3|Debug|Torznab|Downloading Feed https://nyaa.pantsu.cat/feed/torznab?t=search&cat=5070&extended=1&offset=0&limit=50&q=Shokugeki%20no%20Souma+44
17-11-14 12:22:35.3|Debug|Torznab|Downloading Feed https://nyaa.pantsu.cat/feed/torznab?t=search&cat=5070&extended=1&offset=0&limit=50&q=Shokugeki%20no%20Soma%20S3+44
17-11-14 12:22:38.1|Debug|Torznab|Downloading Feed https://nyaa.pantsu.cat/feed/torznab?t=search&cat=5070&extended=1&offset=0&limit=50&q=Shokugeki%20no%20Souma%20San%20no%20Sara+44
17-11-14 12:22:41.0|Debug|Torznab|Downloading Feed https://nyaa.pantsu.cat/feed/torznab?t=search&cat=5070&extended=1&offset=0&limit=50&q=Shokugeki%20no%20Souma%20S3+44
17-11-14 12:22:44.8|Debug|Torznab|Downloading Feed https://nyaa.pantsu.cat/feed/torznab?t=search&cat=5070&extended=1&offset=0&limit=50&q=Food%20Wars%20Shokugeki%20no%20Soma+44
17-11-14 12:22:48.6|Debug|NzbSearchService|Total of 5 reports were found for [Food Wars! Shokugeki no Soma : 44] from 1 indexers
```

There aren't any episode mappings for season 3, so it's using episode 44 (the absolute episode for the entire series), thexem.de will need to update those mappings.
