### ISSUE TITLE
The second tag being ignored

### ISSUE THREAD

**Issue by UniverseXXX** [Sonarr/Sonarr#2291]
## Bug Report
I've got 2 tags: 264, 265 with must contain having x264,h264 and x265,h265,HEVC accordingly.
Serie has both tags (264 and 265) assigned. However, when RSS search is running, the second tag 265 being ignored. See log below.

### System Information/Logs
> 17-11-17 10:59:41.8|Debug|Parser|Parsing string 'Westworld (2016) Season 1 S01 (1080p BluRay x265 HEVC 10bit AAC 5 1 Joy) [UTR]'
17-11-17 10:59:41.8|Trace|Parser|^(?<title>.+?)\W(?:S|Season)\W?(?<season>\d{1,2}(?!\d+))(\W+|_|$)(?<extras>EXTRAS|SUBPACK)?(?!\\)
17-11-17 10:59:41.8|Debug|Parser|Episode Parsed. Westworld (2016) - Season 01 
17-11-17 10:59:41.8|Debug|Parser|Language parsed: English
17-11-17 10:59:41.8|Debug|QualityParser|Trying to parse quality for Westworld (2016) Season 1 S01 (1080p BluRay x265 HEVC 10bit AAC 5 1 Joy) [UTR]
17-11-17 10:59:41.8|Debug|Parser|Quality parsed: Bluray-1080p v1
17-11-17 10:59:41.8|Debug|Parser|Release Group parsed: 
17-11-17 10:59:41.9|Debug|AcceptableSizeSpecification|Beginning size check for: Westworld (2016) Season 1 S01 (1080p BluRay x265 HEVC 10bit AAC 5 1 Joy) [UTR]
17-11-17 10:59:41.9|Debug|AcceptableSizeSpecification|Item: Westworld (2016) Season 1 S01 (1080p BluRay x265 HEVC 10bit AAC 5 1 Joy) [UTR], Size: 8740258816 is smaller than minimum allowed size (10758390000 bytes for 10x 60min), rejecting.
17-11-17 10:59:41.9|Debug|FullSeasonSpecification|Checking if all episodes in full season release have aired. Westworld (2016) Season 1 S01 (1080p BluRay x265 HEVC 10bit AAC 5 1 Joy) [UTR]
17-11-17 10:59:42.0|Debug|CutoffSpecification|Comparing file quality with report. Existing file is WEBDL-1080p v1
17-11-17 10:59:42.0|Debug|CutoffSpecification|Cutoff already met, rejecting.
17-11-17 10:59:42.0|Debug|LanguageSpecification|Checking if report meets language requirements. English
17-11-17 10:59:42.0|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Westworld (2016) Season 1 S01 (1080p BluRay x265 HEVC 10bit AAC 5 1 Joy) [UTR]
**17-11-17 10:59:42.0|Debug|ReleaseRestrictionsSpecification|[Westworld (2016) Season 1 S01 (1080p BluRay x265 HEVC 10bit AAC 5 1 Joy) [UTR]] does not contain one of the required terms: x264, h264**

**Sonarr Version:**
2.0.0.5059
**Operating System:**
Linux (Linuxserver docker container)

**Comment by M0UL** [comment]
in this case file is already reject because it does meet the file size requirements and the cuttoff is already met.

**Comment by markus101** [comment]
If you require x264 and x265 it'll always be rejected, unless the release has both of those in the file name and it never should (if they are separate rules) you could make a single rule that requires all those and then it'd apply as long as any of the words is in the release name.
