### ISSUE TITLE
Add feature to list alternate URL for indexer

### ISSUE THREAD

**Issue by xelra** [Sonarr/Sonarr#2293]
Some indexers have alternate URLs and due to various reasons, not all URLs are always available. It would be great if one could simply enter a list of URLs in the indexer settings and Sonarr would try the alternates, if the first URL isn't reachable.

EDIT:
Simply creating multiple indexers is not a neat workaround, because it clutters the UI with health warnings.

**Comment by markus101** [comment]
Is there a particular indexer this would be used for? This seems like a very 1% feature that I don't see a lot of users needing/using. I'm leaning heavily towards `one-day-maybe`, but not committing to it, but maybe Taloth sees it differently.

Multiple active indexers would also use more API calls, but there would only be heath check warnings in the event one had failed and that' probably useful information.

**Comment by xelra** [comment]
In my case I noticed sporadic health check warnings regarding `nyaa.pantsu.cat`. I tried reaching the api with Postman and realized that the api on this domain wasn't accessible. I went to their IRC and learned that there are 2 alternate domains. When I tried accessing `nyoo.moe`, I had no connection issues. 

Since then I've monitored the situation and sometimes one of the domains isn't accessible. I believe it has something to do with either cloudflare, quotas or anything else ddos protection related.

The feature I'm asking for is not querying all of those domains at search time, but rather only fall back to another domain, when there's a connection error.

**Comment by Taloth** [comment]
We'd have to implement some kind of multi-url + retry logic on a pretty low level. If we do it at the indexer level it's far to complicated for a 1% feature.
If we instead implement it at the HttpClient layer, we could specify alternative domain names (aliases) similar to how we handle RateLimitService & the curl fallback. Allowing it to retry the alternative domain without having to construct the whole alt url.

But that said, you can probably whip-up a transparent failover balancer in nginx pretty easily. (https://serverfault.com/questions/480241/nginx-failover-without-load-balancing)

I'm leaning toward no, unless there's an argument that makes this more than just a 1% feature.

**Comment by xelra** [comment]
Let's say that 50% of Sonarr users also watch anime and 50% use torrents and this is one of 2 proper apis for anime. Then this would at least be a 12.5% feature an up. :blush:

**Comment by Taloth** [comment]
I talked to markus about it. We rather not implement this. It's another option that needs an UI, can confuse users etc. And won't be configured by default, so like only 1% of the anime users would use it.

This is basically an indexer issue with loadbalancing/ddos protection. Your alt url works _now_ because it's obscure and not well-known, once it's more publicly known then that's toast too.

Look at the nginx fallover proxy first, see if that helps.

**Comment by xelra** [comment]
I agree, the only way I see this having good UX is with it being right in the indexer settings with a field below the url field called "alternate urls" and an info popup behind it saying "comma-separated list of alternate urls".

Or alternatively making the original url field accept a comma-separated list and putting the info popup behind that.

**Comment by markus101** [comment]
Closing this out as we're not planning on adding it. If there is a valid use beyond a single indexer or other reasons to add this we can reopen it.
