### ISSUE TITLE
alternative query string when searching

### ISSUE THREAD

**Issue by stephenetyler** [Sonarr/Sonarr#2294]
## Feature Request
Ability to provide an alternative query string when searching for an episode.  Sometimes episodes are not found due to different naming schemes.  For example, The.Daily.Show.with.Trevor.Noah vs The.Daily.Show - sonarr only returns the former.

### What problem are you looking to solve?
Return all relevant query results.

### Other Information
When manually searching for an episode, perhaps you could allow the user to modify the query being sent?

Anyways, thanks for making sonarr.  Its great. :)

**Comment by markus101** [comment]
A list of alternate names is maintained, which Sonarr will use when searching by title.

https://forums.sonarr.tv/t/scene-naming-tvdb-naming-conflicts/137

Searching for an arbritary tirle in a one of search is something we have an open issue for though. https://github.com/Sonarr/Sonarr/issues/1128
