### ISSUE TITLE
Outdated 'Status' field

### ISSUE THREAD

**Issue by lewispurvis** [Sonarr/Sonarr#2297]
I'm not sure if this is a feature request or a bug report but seems more like a bug to me. It appears that Sonarr displays media information (when hovering over the 'status' field) for items such as an episodes size and quality incorrectly, if the file has been replaced with something else, outside of sonarr. This is understandable, but then re-scanning the hard drive/folders for media, should change this information to reflect what is on the disk, not what you downloaded via sonarr a long time ago. For example, if i downloaded media when it aired, but then replace that file with a blu-ray rip version, this change should be reflected in Sonarr. If not this may have the knock on effect that it might try and download 'propers' based on the quality at which it was downloaded through Sonarr at, rather than the current file (though this is just speculation). Minor issue, but if the current media status as far as quality was concerned wasn't important, it wouldn't be there.
Cheers

**Comment by markus101** [comment]
Which "Status" field are you talking about? There are lots of places where the quality of an episode is shown, I want to confirm which one you're talking about.

**Comment by lewispurvis** [comment]
When you enter any series, you have a page full of seasons and episodes. There is a column named 'status'.

**Comment by markus101** [comment]
Thanks for confirming. This has been addressed in the v3 UI work.
