### ISSUE TITLE
Fails to find or parse episodes for show "The Big Fat Quiz Of The Year"

### ISSUE THREAD

**Issue by GenericPolarBear** [Sonarr/Sonarr#2298]
The show "The Big Fat Quiz Of The Year" has a strange episode naming structure as each episode is for each year, and not episode numbers.
This causes Sonarr to ignore most of the search results, and fail to automatically import most of the episodes it does actually download.

The indexers added do have each episode actually available for download, so that's not the issue.

I'm sure there are other shows that use years for each episode name that could cause the same sort of issue as this show. I am guessing Sonarr is thinking each episode is from a different show or something.

Example episode names:

- The Big Fat Quiz Of The Year 2016
- The Big Fat Quiz Of The Year 2015
- The Big Fat Quiz Of The Year 2014
etc

Current version: 2.0.0.5054

**Comment by markus101** [comment]
At best Sonarr will treat those as season 20 episode 14/15/16, though it may fail to parse them at all. It's not a format that Sonarr supports and no current plans to support that format.
