### ISSUE TITLE
New downloads are not going into proper folder.

### ISSUE THREAD

**Issue by aprillia99** [Sonarr/Sonarr#2299]
So let's say I have TVshow1 the path is /Media/Shows/TVshow1

downloads TVshow1 S02E12  File name tvshow1.S02.E12.torrentman.HD.1080p 

When it is finished downloading sonarr will put the file in Media/Shows/tvshow1.S02.E12.torrentman.HD.1080p
Instead of putting it in /Media/Shows/TVshow1/Season 2...

I then have to manually import it to get it to move to the right folder and sonarr to see it. This started after an update, and I imported my existing library. 

Any thoughts?

**Comment by markus101** [comment]
> Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.
 
Please use the forums for support.

Sonarr will only move files to the series folder, it sounds like your download client is putting downloads in `/Media/Shows`. To determine why it's not importing automatically we'll need to see ((debug logs)) of the import process and what Sonarr shows for it in Activity: Queue.
