### ISSUE TITLE
Adding Torznab indexer via jackett with basic auth

### ISSUE THREAD

**Issue by sjdaniel10** [Sonarr/Sonarr#2301]
Sonarr works fine with adding indexer over http, however, i need to use jackett over https and require my basic auth to remain active, however, it does not seem like sonarr supports an indexer which is secured by basic auth, my jackett webpage requires some sort of auth, which means that disabling it is not an option, however, i do still need my sonarr to add torrents
Please assist
Kind Regards

**Comment by markus101** [comment]
Jackett API requests should be authenticated via an API key, not basic auth. If you're running a reverse proxy in front of Jackett (it sounds like you are), then it should not require basic auth for the API paths. Supporting basic auth for indexers is not something we plan to do.
