### ISSUE TITLE
Update no longer shows torrents under activity tab

### ISSUE THREAD

**Issue by sjdaniel10** [Sonarr/Sonarr#2302]
new update which was released a few hours ago seems to have broken the torrents being added to the activity tab, but also when manually adding a torrent, it will show an added symbol but will then disappear after the page is refreshed.
This is a core element of many people's auto import, is this just a once off-ocurrance on my system (as i was busy with it while it was update) or is this a dev fault?

Thanks and Kind Regards

**Comment by markus101** [comment]
Which version?
What do the logs show?
We need more information.

**Comment by sjdaniel10** [comment]
2.0.0.5054 - Nov 4 2017 is the update than i am on howver, it seems to be working now all of a sudden.
Sorry for the opening of a ticket for no reason
Thanks
