### ISSUE TITLE
[Query] Would a snap of sonarr make sense?

### ISSUE THREAD

**Issue by pantar85** [Sonarr/Sonarr#2303]
Just wondering if making a snap of sonarr would be useful to some people.

info here: 
https://build.snapcraft.io/

could make the linux installation a bit easier for more people. not sure how useful it would be for the sonarr devs.

just floating the idea.

**Comment by markus101** [comment]
Is the result a native package for the OS?
How are dependencies managed?

**Comment by pantar85** [comment]
> Is the result a native package for the OS?

Yes

>How are dependencies managed?

As I understand you can just bundle them with it as, its just some sort of clever zip file at the end of the day. There is also a way to highlight these so it won't pull them in if it doesn't need them. But I am actually not too sure about this.

>Trying to understand how it'd fit into our build system and what the output is.

From what i grasp of it, you can just link your github account and it will produce a snap for you. you can test it, and if everything is ok you publish to a release channel. I think you just define dependencies and some basics via a yaml file.

![screenshot from 2017-12-02 20-41-23](https://user-images.githubusercontent.com/10640625/33519570-3773d446-d7a1-11e7-8509-785a2d43fb9e.png)

more details from here.

https://docs.snapcraft.io/build-snaps/ci-integration

The output would just be a sonarr snap that would run on any distribution that has snapd installed, which is pretty much all of them. Well some of them have it by default but on all of them its in the repo. Updates are automatic.

I am not sure if its the right fit for this project but it could be. and it could make things a lot easier. I don't know yet, im still trying to learn about them myself. I have zeronet installed as a snap and it was literally snap install zeronet to install and keep updated, it even handled tor. it all works flawlessly. Would be kind of cool for the linux install instructions for all distros to just be a one liner;

`snap install sonarr`

i don't know, its worth some toilet time research. It would either save a lot of time and headaches or be a total waste of time.

**Comment by markus101** [comment]
In some ways this reminds of a docker, not entirely, but it's similar. I'm definitely interested in making it easier to install, but in the end I think there would still be standard OS packages, since some prefer those.

**Comment by markus101** [comment]
I think the lack of interest from others means we shouldn't commit to this right now, tagging it for looking at it again in the future and we can always reopen if there is more support for this.

**Comment by driscollw** [comment]
I came here looking to see if a snap was available. I can still do it in lxd, but was just looking for an easy way to do upgrades and reduce complexity. Thank you for your work on this software.

**Comment by eberkund** [comment]
AFAIK snapcraft only supports dotnet Core as a build plugin right now. Not to say you can't get it working with Mono but it will be a bit more involved.

**Comment by nafanz** [comment]
It would definitely be helpful

**Comment by Pantar2205** [comment]
It seems someone has all ready made it.

https://snapcraft.io/sonarr
