### ISSUE TITLE
[Feature] Allow the bulk refresh of Indexers and Download Clients

### ISSUE THREAD

**Issue by stuntguy3000** [Sonarr/Sonarr#2304]
I would like the feature to bulk refresh/test Indexers/Download Clients. Frequently when I load Sonarr i have to manually retest indexers which is annoying and painful.

Perhaps a scheduled task to do this is suitable?

**Comment by markus101** [comment]
>Frequently when I load Sonarr i have to manually retest indexers which is annoying and painful.

When you first start it? Or constantly?

The best thing to do would be to figure out why they are failing. Indexers/download clients start at being disabled for 5 minutes, then the disabled time increases if they continue to fail repeatedly. If they succeed they are no longer treated as disabled.

> Perhaps a scheduled task to do this is suitable?

This happens naturally as part of existing scheduled tasks, though disabled times are respected.

https://github.com/Sonarr/Sonarr/issues/1735 would allow retesting from System: Status.
