### ISSUE TITLE
Unable to delete media files (HTTP 409 Error)

### ISSUE THREAD

**Issue by stuntguy3000** [Sonarr/Sonarr#2305]
As shown in the image below, when deleting media files e.g. managing a season's episodes this happens.

![image](https://user-images.githubusercontent.com/1522389/33226305-b9f0b104-d1da-11e7-82b0-76e348d4b339.png)

**Comment by markus101** [comment]
This will occur if the root folder for the series is missing or empty (which will also prevent Sonarr from detecting the files are done when doing a disk re-scan), I've added some more logging around this case though.
