### ISSUE TITLE
Possible to ignore a word via tag ? 

### ISSUE THREAD

**Issue by lrnv** [Sonarr/Sonarr#2307]
Hi, 

First, you'll have to know that i'm french. I dont care that sonarr download english series cause i prefer watching them in english, but my girlfriend does not. Some series are needed in english vosten, some others in elgish vostfr, and last but not least some others in french. The problem i'm talking about here appends with the first and second cases, shows that are wanted in english (and i dont care about subtitles -- i'll re-download them if it's not the good one).

Secondly, you'll have to know that my primary indexer is also french. Therefore, i get a lot a releases names that are e.g : 

"The Big Bang Theory S11E07 FASTSUB VOSTFR 720p HDTV x264 AC3-ARKMR"

Wich sonarr throw away because "English is wanted, but found French". Wich is not entirely true : English is wanted, right. But the french is just the subs, not the sound -- Subtitles are not hardcoded anyway. 

So this is my question : How can i tell sonarr to just dont care about the "VOSTFR" tag ? Like is there some kind of whitelist somewhere, tags that are deleted from release names before they are checked ?

**Comment by M0UL** [comment]
not possible to overrule that.

**Comment by markus101** [comment]
Subtitles detected as the language is tricky, but covered under https://github.com/Sonarr/Sonarr/issues/280 We don't have a good solution to this problem at this time.
