### ISSUE TITLE
[request] (custom) background for overview page

### ISSUE THREAD

**Issue by Vilscon** [Sonarr/Sonarr#2308]
I was wow'd by the opaque tables with a series background on each series overview page. However, the homepage is very dull with a black background, slight graphic and dark gradient. This could be much more. I'd like to request either custom background options or more options incorporating at least a bit more contrasting background.

**Comment by markus101** [comment]
No current plans for customization there, but could possibly come as part of https://github.com/Sonarr/Sonarr/issues/1943
