### ISSUE TITLE
Pause Sonarr or ignore downloads for X show for a time period

### ISSUE THREAD

**Issue by Duwaynef** [Sonarr/Sonarr#2310]
Is there any way to stop sonarr from auto managing media from sabnzbd for a particular show, aka i start a download manually for a show listed in sonarr, the second it finishes sonarr takes over the file.

with my current media setup while i am using sonarr to go find the best download for old seasons, 
i need it to not auto manage the media once the download completes, but only for that particular show.

with torrents using deluge i can easily add the torrent then remove the sonar label and all is great.

but i can't find a way besides adding all downloads in a paused state then turn off sonarr and once the media is down downloading turn sonarr back on.

or is this capability possible via a different usenet downloader?

I tried un monitoring seasons and that don't work, i have found turning sab off is a solution however 
sonarr auto downloads items via torrents during this period that would be better from usenet.

Thanks,

**Comment by markus101** [comment]
It is not possible to selectively turn off post processing and not something we intend to add. You could change the category of the download (it'd need to be done before the download completes), possibly with a pre-queue script in SAB.
