### ISSUE TITLE
Allow Channel Override for Slack

### ISSUE THREAD

**Issue by grokdesigns** [Sonarr/Sonarr#2311]
### What problem are you looking to solve?
Allow user to enter which channel the Slack integration should post to. This is a matter of adding a field to the _Connections_ configuration for Slack on the front end and adding a `"channel": "#other-channel"` override to the JSON payload on the backend.

### Other Information
Currently a custom webhook must be configured solely for Sonarr so that alerts get pushed to the correct channel. Other apps allow you to specify which channel they get posted to, so the webhook can be used for multiple services, which then post to their respective channels.

Also requested in [Radarr](https://github.com/Radarr/Radarr/issues/2298).

**Comment by markus101** [comment]
Sonarr uses incoming webhooks in slack that are limited to the channel they are created for. The only way around that appears to be a Slack app, which would need to be installed in slack and appear to be more involved than simply sending a webhook.

We do not want to commit to redoing the slack implementation as an app at this time.

**Comment by grokdesigns** [comment]
Incoming webhooks are not limited to the channel they are created for. As mentioned, it only requires that the channel be specified (`"channel": "#other-channel"`) in the JSON payload pushed to the webhook. [Reference](https://api.slack.com/custom-integrations/incoming-webhooks#runtime_customizations)

**Comment by markus101** [comment]
Ahh, landed on the new docs page, not the legacy docs. In that case, yes, it can be added.

**Comment by grokdesigns** [comment]
Works perfectly, thank you!
