### ISSUE TITLE
Sonarr can't connect to Deluge

### ISSUE THREAD

**Issue by Ryzzzen** [Sonarr/Sonarr#2314]
## Bug Report

Sonarr doesn't seem to connect to Deluge anymore.. Yesterday it was still working though.
### System Information/Logs

> `17-11-29 13:00:13.8|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from Deluge
[v2.0.0.5054] System.NullReferenceException: La r�f�rence d'objet n'est pas d�finie � une instance d'un objet.
   � NzbDrone.Core.Download.Clients.Deluge.Deluge.GetItems() dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:ligne 102
   � NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) dans M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:ligne 89`

**Sonarr Version:**     2.0.0.5054

**Operating System:** Windows

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/1513714/sonarr.txt)

**Comment by markus101** [comment]
It looks like Deluge (or the OS) is rejecting the connection (another error in the logs).

Please open a thread on the forums to troubleshoot further.

**Comment by Ryzzzen** [comment]
I don't know if i should, if i shouldn't then i'm sorry, i just wanted to add more information about this issue.
About the fact that Deluge is rejecting the connection, it's not it's just that it wasn't started before, however I resolved the bug i'm talking about by removing all the downloads in Deluge and then rebooted it. I don't know what caused this.
