### ISSUE TITLE
Unable to determine if file is a sample

### ISSUE THREAD

**Issue by Fossil01** [Sonarr/Sonarr#2316]
Sonarr refrains from importing a lot of files due to the error "Unable to determine if file is a sample". This happens on obfuscated filenames like 32d0d33e168a4681a962f703c7608999.mkv

Seeing more and more stuff is uploaded this way it would be good if Sonarr could properly handle these. This particular file was 950MB and the only file in the RAR's so very unlikely to be a sample.

I would rather have it import the file automatically even if the file turned out to be a sample afterall. But I think it's pretty safe to say that 900+MB is not a sample.

### System Information/Logs

**Sonarr Version:**
2.0.0.5054
**Operating System:**
Synology

**Comment by markus101** [comment]
We'll need a link to trace logs for this issue.

**Comment by markus101** [comment]
Lots of progression in this thread: https://forums.sonarr.tv/t/sonarr-unable-to-determine-if-file-is-sample/16637/27

Going to close this out.
