### ISSUE TITLE
Possible memory leak (as seen on radarr)

### ISSUE THREAD

**Issue by Firelfy** [Sonarr/Sonarr#2317]
**Bug Report:** Possible memory leak when importing episodes. The memory usage spikes on file import (on Radarr others were seeing this issue too, but to a lesser extent). Here's an image showing the spike in memory:

![sonarr memory](https://user-images.githubusercontent.com/16787445/33451220-3a50e480-d673-11e7-93b9-3b51ac82c78a.PNG)

As you can see it looks like something is cleaning up the memory (mono or the OS). Might be in correlation with the amount of memory the system has as other Radarr users have seen smaller usage increases due to less memory (maybe) or smaller import files.

**System Information/Logs:** [sonarr.txt](https://github.com/Sonarr/Sonarr/files/1519220/sonarr.txt)
Because of the large file the issue occurs around here:

> 17-12-1 04:05:58.0|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /downloads/Game.of.Thrones.S07.1080p.BluRay.x264-DEMAND
> 
> 17-12-1 04:07:27.8|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /tv/Game of Thrones/Season 7/Game of Thrones - S07E01 - Dragonstone WEBDL-1080p Proper.mkv

**Sonarr Version:** 2.0.0.5054

**Operating System:** Linux, specifically running inside the Linuxserver.io Sonarr docker on unRaid 6.3.5

**mono (macOS/Linux) Version:** 5.4.1.6

I will upload debug logs when I have a similar event while it is on.

**Link to Radarr issue:**  Radarr/Radarr#1580

**Comment by markus101** [comment]
Existing issue on memory usage: https://github.com/Sonarr/Sonarr/issues/2296
