### ISSUE TITLE
Prioritize Usenet indexers over Torrent indexers

### ISSUE THREAD

**Issue by pabohoney1** [Sonarr/Sonarr#2319]
I know there is a long standing feature request for prioritizing indexers already (https://github.com/Sonarr/Sonarr/issues/320) but this request is different than what is asked there.  

What I'm looking for is an option to first search and use my Usenet indexers before even searching my Torrent indexers.  Usenet is much more reliable, faster and doesn't require seeding after the fact.  Couchpotato has this feature and it's really handy.

**Comment by markus101** [comment]
Delay Profiles allow you to prefer usenet or torrents, but searching will still happen on all indexers at the same time, then will be sorted by quality, preferred protocol, etc (quality always wins). We do not have plans to search some indexers, check for a result then search additional indexers (the same is true for RSS).
