### ISSUE TITLE
libmediainfo not able to load after yum update of all packages

### ISSUE THREAD

**Issue by abegosum** [Sonarr/Sonarr#2320]
## Bug Report

After updating all packages on system (including mono-core), sonarr no longer is able to link the libmediainfo library.  

### System Information/Logs

From Sonarr.Txt:

```
17-12-6 17:50:36.0|Error|VideoFileInfoReader|mediainfo is required but was not found

[v2.0.0.4230] System.DllNotFoundException: libmediainfo.so.0
  at (wrapper managed-to-native) NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo:MediaInfo_New ()
  at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo..ctor () [0x00006] in <837d6e3ef7fc43e8a2e1545f5ee25654>:0 
  at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo (System.String filename) [0x00021] in <837d6e3ef7fc43e8a2e1545f5ee25654>:0 
```
Installed libmediainfo packages and versions:

```
[root@host sonarr]# yum list installed | grep mediainfo
libmediainfo.x86_64                  17.10-1.el7                     @epel
libmediainfo-devel.x86_64            17.10-1.el7                     @epel
mediainfo.x86_64                     17.10-1.el7                     @epel
```

Systemd unit file (`/etc/systemd/system/sonarr.service`):

```
#
# Systemd unit file for Sonarr
#

[Unit]
Description=Sonarr Daemon

[Service]
Type=simple
User=usenet
Group=usenet
ExecStart=/usr/bin/mono /apps/sonarr/NzbDrone.exe /data=/apps/data/.sonarr
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target
```

Linking the file in the app directory solves the problem; but, should that be necessary.

```
ln -s /usr/lib64/libmediainfo.so libmediainfo.so.0
```

**Sonarr Version:**
2.0.0.5054

**Operating System:**
CentOS Linux release 7.4.1708 (Core)
Linux host 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**.net Framework (Windows) or mono (macOS/Linux) Version:**
5.4.1.6

**Comment by lloesche** [comment]
Can confirm the same happens on Fedora 26 after updating the system and Sonarr today (don't know which update caused the problem though, could have been either).

```
MediaInfo Library could not be loaded libmediainfo.so.0
```

Sonarr Version 2.0.0.5054
Mono Version 4.8.0

```
$ cat /etc/redhat-release
Fedora release 26 (Twenty Six)
$ uname -a
Linux blackhole 4.13.16-202.fc26.x86_64 #1 SMP Thu Nov 30 15:39:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ rpm -qa *mediainfo
libmediainfo-17.10-1.fc26.x86_64
mediainfo-17.10-1.fc26.x86_64
$ ldd /usr/bin/mediainfo | grep libmediainfo
	libmediainfo.so.17 => /lib64/libmediainfo.so.17 (0x00007f02589bb000)
```

**Comment by Taloth** [comment]
That's an issue with mediainfo upstream, and they fixed it, so I assume it will be resolved with the next libmediainfo.
