### ISSUE TITLE
Feature Request: Automatically extract frames from video file if no artwork is found

### ISSUE THREAD

**Issue by Zeusy123** [Sonarr/Sonarr#2322]
## Feature Request
Automatically extract frames from video file if no artwork is found

### What problem are you looking to solve?
Many times there is no image on tvdb as the eposide just aired.

**Comment by markus101** [comment]
This isn't something we want to commit to implement and would be better suited as a custom script, instead of adding dependencies that are otherwise not required for Sonarr to operate.
