### ISSUE TITLE
Spaces in download path for rtorrent

### ISSUE THREAD

**Issue by rubdos** [Sonarr/Sonarr#2324]
### System Information/Logs

**Sonarr Version:**  Sonarr Ver. 2.0.0.5085 

**Operating System:** Fedora 26/Docker

**.net Framework (Windows) or mono (macOS/Linux) Version:** linuxserver.io/sonarr docker image

**Link to Log Files (debug or trace):** n/a

**Browser (for UI bugs):** n/a

### What problem are you looking to solve?

I have the download path for rtorrent set to "/data/Downloads/TV Shows". rtorrent claims errornous trailing characters at end of file. I think this is because of the space in the path; rtorrent adds the download [CLOSED] to the default directory (/data/Downloads/Other)

### Other Information
n/a

**Comment by Taloth** [comment]
It's very unlikely that rtorrent has issues with spaces. 'at end of file' indicates either a file (.torrent perhaps) is corrupt, or that the filename has unrecognized characters at the end.   
Either way, you need log files.

**Comment by markus101** [comment]
We can reopen if appropriate logs are provided, but closing this for now.
