### ISSUE TITLE
Can’t connect to Download Client while it is downloading from filehosting

### ISSUE THREAD

**Issue by enchained** [Sonarr/Sonarr#2325]
### System Information/Logs

**Sonarr Version:** 2.0.0.5054

**Operating System:** Synology DSM 6.1.4-15217 Update 2

**.net Framework (Windows) or mono (macOS/Linux) Version:** 4.6.2

**Link to Log Files (debug or trace):** https://pastebin.com/2c6N8XPS

### Additional Information

I have Synology DS216+ii and I use its Download Station as my download client. It can download not only torrents, but files from filehostings too (the ones with countdowns and captchas). I added a few of filehosting downloads in its queue (NOT tagged as sonarr and NOT in sonarr folder) and it looks like it broke download client connection due to unrecognized statuses.

Sonarr System says: `All download clients are unavailable due to failures`

When I go to download clients and press Test it says:
`Failed to get the list of torrents: Error converting value "filehosting_waiting" to type 'NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationTaskStatus'. Path 'data.tasks[154].status', line 1, position 123112.`

or
`Failed to get the list of torrents: Error converting value "captcha_needed" to type 'NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationTaskStatus'. Path 'data.tasks[153].status', line 1, position 122570.`

I can provide a filehosting link to reproduce, but probably reproduceable with any synology-supported filehosting.

**Comment by margaale** [comment]
Hi, just saw this issue. I'm looking into it. I should be really simple to solve...

**Comment by margaale** [comment]
There it is...
Maybe @enchained could provide me a link so i can test if its works

**Comment by markus101** [comment]
Fixed via https://github.com/Sonarr/Sonarr/commit/747f3e171c752a18148c1d115679ba2b9710d260
