### ISSUE TITLE
Cannot connect to Download Client

### ISSUE THREAD

**Issue by kianrafiee** [Sonarr/Sonarr#2326]
### System Information/Logs

**Sonarr Version:** 
0.2.0.870

**Operating System:** 
--

Synology NAS DS218Play
DSM 6.1.4-15217 Update 2

--

**.net Framework (Windows) or mono (macOS/Linux) Version:**
5.4.1

**Link to Log Files (debug or trace):**
https://pastebin.com/fLqs9rkc

**Browser (for UI bugs):**

### Additional Information

When trying to add a Download Client, Download Station for Synology NAS, I get the following errors:

```
Failed to get the list of torrents: HTTP request failed: [500:InternalServerError] [GET] at [http://192.168.1.11:5000/webapi/DownloadStation/task.cgi?_sid=HICsOFKS7LnfE1780Q8N965707&api=SYNO.DownloadStation.Task&version=1&method=list&additional=detail%2Ctransfer]

Unknown exception: HTTP request failed: [500:InternalServerError] [GET] at [http://192.168.1.11:5000/webapi/DownloadStation/info.cgi?_sid=HICsOFKS7LnfE1780Q8N965707&api=SYNO.DownloadStation.Info&version=1&method=getConfig]
```

**Comment by markus101** [comment]
It failed because Synology returned HTML instead of a valid API response, with the message: `Sorry, the page you are looking for is not found.`

It looks like Download Station is not available on your Synology. Closing as this isn't a Sonarr bug. If you need further assistance please open a thread on the forums for support.

**Comment by kianrafiee** [comment]
Wait but I have Download Station installed and I am using it. I have used it with Sonarr before but I uninstalled Sonarr recently and now have it again.

**Comment by markus101** [comment]
>Sonarr Version:
0.2.0.870

That looks like a Radarr version, not Sonarr (and the logs indicate they're for Radarr).

> Wait but I have Download Station installed and I am using it. I have used it with Sonarr before but I uninstalled Sonarr recently and now have it again.

The URL Radarr is looking for isn't found.

**Comment by kianrafiee** [comment]
Sorry I posted the correct bug info in a new issue. I get the two confused and I am having the issue with both.
