### ISSUE TITLE
Cannot connect to Download Client (Installed on NAS)

### ISSUE THREAD

**Issue by kianrafiee** [Sonarr/Sonarr#2327]
### System Information/Logs

**Sonarr Version:** 
0.2.0.870

**Operating System:** 
--

Synology NAS DS218Play
DSM 6.1.4-15217 Update 2

--

**.net Framework (Windows) or mono (macOS/Linux) Version:**
5.4.1

**Link to Log Files (debug or trace):**
https://pastebin.com/fLqs9rkc

**Browser (for UI bugs):**

### Additional Information

When trying to add a Download Client, Download Station for Synology NAS, I get the following errors. I have Download Station installed on my NAS and it is useable in the NAS Web GUI. I have also used it before with Radarr before I uninstalled radarr for a while:

```
Failed to get the list of torrents: HTTP request failed: [500:InternalServerError] [GET] at [http://192.168.1.11:5000/webapi/DownloadStation/task.cgi?_sid=HICsOFKS7LnfE1780Q8N965707&api=SYNO.DownloadStation.Task&version=1&method=list&additional=detail%2Ctransfer]

Unknown exception: HTTP request failed: [500:InternalServerError] [GET] at [http://192.168.1.11:5000/webapi/DownloadStation/info.cgi?_sid=HICsOFKS7LnfE1780Q8N965707&api=SYNO.DownloadStation.Info&version=1&method=getConfig]
```

**Comment by markus101** [comment]
Why are you opening another issue for the same issue with _Radarr_?

**Comment by kianrafiee** [comment]
Can I ask why your not giving me a chance to correct my mistakes before just closing the issue? It seems logical to give the user a chance to say what they need before just wiping clean...

**Comment by markus101** [comment]
Because you posted the exact same thing as your last issue (same info, same logs)

![image](https://user-images.githubusercontent.com/413544/33814745-41e6b4b6-dde1-11e7-919e-1525c21b815d.png)

Why do you need to open a second one when the first one already exists?

**Comment by kianrafiee** [comment]
Oh my mistake, I thought when you close an issue that means you won't look at it anymore.

**Comment by markus101** [comment]
It means there is nothing actionable at that time, if more information is added so we can do something than we'll re-open it, but when it's the exact same wrong information we're just going to close the second one as well.

From the original issue:
> Sorry I posted the correct bug info in a new issue.

Which I'm not seeing here, the information is still all for Radarr.

Regardless, this is a support problem, which we do not handle here, you'll need to open a thread on the forums to troubleshoot further.

**Comment by kianrafiee** [comment]
https://github.com/Sonarr/Sonarr/issues/2328 thats the issue with all the righ info for sonarr including log.

isnt it a bug though since it cannot find the download client even though its there?

**Comment by markus101** [comment]
...a 3rd issue...

Not a bug with Sonarr. Sonarr is connecting to the correct endpoint and Synology is throwing an error that it can't find it, I can't tell you why that's happening, maybe someone on the forums can, but it's working for me with Download Station on `DSM 6.1.4-15217 Update 2`.
