### ISSUE TITLE
Cannot connect to download client

### ISSUE THREAD

**Issue by kianrafiee** [Sonarr/Sonarr#2328]
### System Information/Logs

**Sonarr Version:** 
2.0.0.5054

**Operating System:** 
--

Synology NAS DS218Play
DSM 6.1.4-15217 Update 2

--

**.net Framework (Windows) or mono (macOS/Linux) Version:**
5.4.1

**Link to Log Files (debug or trace):**
https://pastebin.com/yYBxLNNX

**Browser (for UI bugs):**

### Additional Information

When trying to add a Download Client, Download Station for Synology NAS, I get the following errors. I have Download Station installed on my NAS and it is useable in the NAS Web GUI. I have also used it before with sonarr before I uninstalled sonarr for a while:

```
Failed to get the list of torrents: HTTP request failed: [500:InternalServerError] [GET] at [http://192.168.1.11:5000/webapi/DownloadStation/task.cgi?_sid=PUOuTJbNoAioo1780Q8N965707&api=SYNO.DownloadStation.Task&version=1&method=list&additional=detail%2Ctransfer]
Unknown exception: HTTP request failed: [500:InternalServerError] [GET] at [http://192.168.1.11:5000/webapi/DownloadStation/info.cgi?_sid=PUOuTJbNoAioo1780Q8N965707&api=SYNO.DownloadStation.Info&version=1&method=getConfig]
```

**Comment by kianrafiee** [comment]
The reason I mistakenly posted the sonarr bug is because I get the two confused and I am having the same issue with both.

**Comment by markus101** [comment]
As mentioned in your other issues, please open a thread on the forums for support.
