### ISSUE TITLE
How do I remove the '+' sign from season naming?

### ISSUE THREAD

**Issue by Vilscon** [Sonarr/Sonarr#2329]
I can't find a reason why I should have a '+' sign at the season number naming for each series. Why is that and how can I remove it?

Just give me "Arrow - s01", instead of "Arrow - s01+".

**Comment by Taloth** [comment]
My guess is you have something in your naming format that causes that + to be there.

_PS: Support questions should go on our forum._

**Comment by Vilscon** [comment]
I honestly doubt it. That would suggest that my 'slash (/)' is causing the plus sign, as that is the only character after the season number..  (last line)

![screenshot 2017-12-11 om 16 19 10](https://user-images.githubusercontent.com/5602798/33838197-159911de-de8f-11e7-9622-ae43f29e76aa.png)

**Comment by markus101** [comment]
`/` is not not a valid path character so it would be replaced with a `+`. The season folder format doesn't need a slash added to it to create a folder, the value as-is is used to make/re-use a folder (with any illegal characters replaced).

**Comment by Vilscon** [comment]
Odd, but yeah.. that fixed it. Can you perhaps explain why a slash isn't converted to a plus sign at the `standard episode format` option that creates deep-folders for me? :)

But yeah, issue solved!

**Comment by markus101** [comment]
Standard Episode format allows slashes to be added to allow for further nesting, like you have in the middle of yours (perhaps a slightly unintended feature initially).

If the season folder format was more like the episode format you'd end up with an extra slash at the end, which could cause an issue depending how double slashes are handled.
