### ISSUE TITLE
Feature request: basic auth + ip whitelist

### ISSUE THREAD

**Issue by royduin** [Sonarr/Sonarr#2331]
It would be nice if there was an option to whitelist IP adreses just like in NZBGet which won't get a basic auth popup if configured.

That way I can whitelist my IP at home so I don't need to authenticate but I've to supply a username/password when I'm connected to another network.

**Comment by markus101** [comment]
We do not plan to do this, the ramifications to someone setting this incorrectly are as bad not enabling authentication at all and a flaw in our code could do the same. We'd much rather keep the on or off approach and let users that want more control do it another way.

A couple things:
- With Forms auth you have the option to `Remember Me` which will keep you logged in
- A reverse proxy that handles traffic from external networks and handles the authentication would be more reliable
