### ISSUE TITLE
Torrents with special characters in name

### ISSUE THREAD

**Issue by GregoryGHarding** [Sonarr/Sonarr#2332]
hey all, just wanted to point out that characters with special characters in the torrent name, break deluge connection with sonarr and stop all communication because sonarr detects a connection issue.

i believe the culprit is the directory identifiers /, and \ being used in the torrent name

**Comment by markus101** [comment]
Please include the requested information for a bug report: https://github.com/Sonarr/Sonarr/blob/develop/.github/ISSUE_TEMPLATE.md#bug-report

**Comment by markus101** [comment]
We can reopen if appropriate logs are provided, but closing this for now.
