### ISSUE TITLE
Property sceneName missing at times

### ISSUE THREAD

**Issue by pannal** [Sonarr/Sonarr#2335]
#2265 

### System Information/Logs

**Sonarr Version:** 2.0.0.5085

**Operating System:**  Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-108-generic x86_64)

**.net Framework (Windows) or mono (macOS/Linux) Version:** 5.4.0.201

**Link to Log Files (debug or trace):** not available yet

For example this one doesn't get recognized and has no `sceneName`:
`Sxxxxx.Things.S02E09.iNTERNAL.720p.WEB.x264-GRP.mkv`

**Comment by markus101** [comment]
Please provide the requested bug information, including debug logs of the import process so we can investigate this further.

**Comment by Taloth** [comment]
Also take note of the Episode History, and the details of those events.

**Comment by pannal** [comment]
I've updated the issue with the requested information. How would I go about retrieving those DEBUG logs for an episode that has already been imported?

Do I have to redownload it?

**Comment by markus101** [comment]
At the very least we'd need to know the complete path Sonarr imported the file from, but the debug logs will give more context. It really comes down to how the file is named and what information Sonarr had about the item from the download client it's importing.

**Comment by pannal** [comment]
OK, perhaps this is already enough:
The files get imported from nzbget, the file in question has this history:
Episode file deleted: `/path/series/Sxxxxxx Things/Season 02/Sxxxxxx.Things.S02E09.iNTERNAL.720p.WEB.x264-STRiFE-xpost.mkv
`Reason: Sonarr was unable to find the file on disk so it was removed`

Downloaded successfully: 
`Name: Sxxxxxx.Things.S02E09.iNTERNAL.720p.WEB.x264-STRiFE-xpost`
`Source: /download-path/complete/series/Stxxxxxx.Things.S02E09.iNTERNAL.720p.WEB.x264-STRiFE-xpost/Stxxxxxx.Things.S02E09.iNTERNAL.720p.WEB.x264-STRiFE-xpost.mkv`
`Imported To: /path/series/Sxxxxxx Things/Season 02/Sxxxxxx.Things.S02E09.iNTERNAL.720p.WEB.x264-STRiFE-xpost.mkv`

The final path is `/path/series/Sxxxxxx Things/Season 02/Sxxxxxx.Things.S02E09.iNTERNAL.720p.WEB.x264-STRiFE.mkv`

I'm using a postprocessing script in nzbget to get rid of the garbled release group names (xpost for example) - may that be the reason there's an "Episode file deleted"-event at the top of the file's history view?

**Comment by markus101** [comment]
> I'm using a postprocessing script in nzbget to get rid of the garbled release group names (xpost for example) - may that be the reason there's an "Episode file deleted"-event at the top of the file's history view?

No, that would happen before Sonarr imports it. If the file is renamed _after_ Sonarr imports it or it's removed from disk then you'd see that and if Sonarr re-imported it, it would not have a scene name because it wasn't imported from the download client, it's in the season folder already.

So the issue really is, why was Sonarr unable to find the file during a rescan which caused it to remove it?

**Comment by pannal** [comment]
I'm not sure, the file didn't get moved or anything, nzbget doesn't say anything meaningful, and Sonarr has the current file (without the -xpost) listed as existing. I'll try to disable the postprocessing script nevertheless and re-download that file.

**Comment by Taloth** [comment]
> Imported To: /path/series/Sxxxxxx Things/Season 02/Sxxxxxx.Things.S02E09.iNTERNAL.720p.WEB.x264-GRP-xpost.mkv

Meaning Sonarr imported it with -xpost. And then later something renamed it. Could be an external script or manually, but not Sonarr otherwise it would've been logged as such.

**Comment by pannal** [comment]
Hm yeah weird. Hasn't happened since. Will keep an eye on this an reopen the issue if it happens again.
