### ISSUE TITLE
Add originalFilePath to Episode Files when importing

### ISSUE THREAD

**Issue by pannal** [Sonarr/Sonarr#2336]
When querying the API it'd help massively with Sub-Zero subtitle matching, if the original filename was provided by the API no matter what, independent of whether the sceneName could be parsed or not.

**Comment by markus101** [comment]
`SourceTitle` in history has this information. For the the file itself if there are cases where scene name can't be found beyond a bug there is a good chance it's because the filename is not useful (hashed, reversed, etc).

We'll focus on the bug first and add in additional information if required. Once https://github.com/Sonarr/Sonarr/issues/2335 is closed we can reopen this if necessary.

**Comment by pannal** [comment]
Great, thank you.

**Comment by pannal** [comment]
Can we reopen this to further talk about it?

There definitely are cases where a sceneName can't be parsed, but Sub-Zero still benefits from knowing the original filename. Take `Series (2017) Season 1 Episode 2 WEB-DL.mkv` - I guess sceneName parsing would not happen here, but SZ'd still parse the `WEB-DL` information and provide proper subtitles.

**Comment by markus101** [comment]
I'm not sure if we'd want to store this separately or store it in the scene name field regardless.

**Comment by pannal** [comment]
Hmm. If you want to stay true to the property name, it should only contain a parsed sceneName. I don't know where the necessity for an explicit parsed sceneName (as opposed to originalName) came from, though.

**Comment by pannal** [comment]
@markus101 have you given this any though? Sub-Zero 2.5 is being released soon and we could really use that property.

**Comment by markus101** [comment]
Talking with Taloth we'll include an `orginalFilePath` that is stored when importing new downloads which includes the release's folder, any intermediate folders and the original file name. That'll provide all the information Sonarr had on the file when importing and should help deal with hashed files as well.

It'll look something like `Series.Title.S01E01.720p.HDTV-RlsGrp/Series.Title.S01E01.720p.HDTV-RlsGrp.mkv`

**Comment by pannal** [comment]
Awesome, thank you!

**Comment by markus101** [comment]
Yeah, that's what it'll be. Typing is hard. 😄

**Comment by markus101** [comment]
Need to wait for https://github.com/Sonarr/Sonarr/pull/2146 as there is some cleanup there that'll make this easier.
