### ISSUE TITLE
Grab multiple downloads at the same time.

### ISSUE THREAD

**Issue by evanrich** [Sonarr/Sonarr#2340]
I did a search for "multiple" in both open and closed issues, and didn't find this request, so forgive me if it's a duplicate.

I've been running Sonarr for quite some time, and absolutely love it.  The one thing I never understood though, is why it grabs only one completed download at a time when processing completed downloads.    It seems to me that it would make obvious sense to grab a download as it was flagged completed, yet when three(3) episodes get downloaded at nearly the same time, if I watch the destination folders, I see it like this:

folder1/file1.partial-> completed ->folder2/file2.partial->completed->etc

it should run in parallel:
folder1/file1.partial->completed
folder2/file2.partial->completed
folder3/file3.partial->completed

also I'm wondering how sonarr goes about grabbing completed downloads?  If I run iftop during a copy, it doesn't go very fast... If i CD to the mount where files are downloaded and do a "cp", it runs faster...from what I can tell python or something is dong the copy?  I'd rather have the first thing (parallel downloads from completed listings), but wondering about the second.

**Comment by Taloth** [comment]
We simply tell mono to copy. If it's being slow then you'll have to investigate that separately. Knowing which kind of mount would help.    

With proper configuration, a single transfer can saturate the connection, so doing multiple concurrently isn't really necessary (it would cause unnecessary random access on the source and destination drives).
Also, given Sonarr is automated, a faster transfer is hardly important as long as it happens in reasonable time. But yes, you got those people who are actively waiting for their new favorite episode to be ready... 😄

**Comment by evanrich** [comment]
@Taloth  thanks for the comment.   I agree that it should saturate the connection, however allow me to explain.

I use a seedbox for some downloads.   I mount the seedbox via SSHFS, so that I can grab files easily once they're done.  While fairly local, for whatever reason, performance via SSHFS is not very fast (I'm working with the provider to nail this down).   Whenever mono copies a file, the performance via SSHFS is around ~10-15Mbps, it can take 30 minutes to grab a ~800MB file.   Through testing, I've noticed that this appears to be per file, as with SFTP downloads, the same occurs (multiple SFTP grabs are limited to ~2MBps).   If I grab via HTTPS, I get 30-50MBps, but AFAIK, there are no easy way to instruct mono/Sonarr to grab files via HTTPS.

If Mono could grab multiple files at once, this would let me pull say 10 files at ~2MBps.

I understand this is probably a fringe case, so it probably won't get implemented, just tossing it out there since my seedbox provider seems unwilling to really assist in troublshooting on their end.   I've tried different mount options, ciphers, etc...can't get it to go above ~13-15Mbps.

**Comment by markus101** [comment]
We're not planning to import multiple files in parallel directly, but Transfer Providers (https://github.com/Sonarr/Sonarr/issues/282 and https://github.com/Sonarr/Sonarr/pull/2337) could allow for alternate transfer methods that internally use multiple connections to speed things up.
