### ISSUE TITLE
Unable to connect to Deluge. Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by SWu** [Sonarr/Sonarr#2341]
### System Information/Logs

**Sonarr Version:** Sonarr Ver. 2.0.0.5090

**Operating System:** Synology DSM 6.1.4-15217 Update 3

**.net Framework (Windows) or mono (macOS/Linux) Version:** Mono 4.6.2.7-8

**Link to Log Files (debug or trace):**
17-12-16 10:43:52.6|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from Deluge

[v2.0.0.5090] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Download.Clients.Deluge.Deluge.GetItems () [0x00063] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:103 
  at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads (NzbDrone.Core.Download.IDownloadClient downloadClient) [0x0000c] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:89 

### Additional Information

Testing the download client succeeds, it also appears that I can download files without any problems, and once I have some files downloading the notification goes away. I think the issue is when my download client doesn't currently have any items in its queue.

**Comment by markus101** [comment]
Looks like it could be the same issue with mono as in this forum thread: https://forums.sonarr.tv/t/sonarr-on-synology-unable-to-retrieve-queue-and-history-items-from-nzbget-cannot-access-a-disposed-object-object-name-system-net-sockets-networkstream/16226/ but you haven't included a debug log, only a partial snippet of the error.

**Comment by markus101** [comment]
Closing,we can reopen if additional information points to a different issue.
