### ISSUE TITLE
Unable to parse episodes from release name for anime episodes using absolute numbering starting with E

### ISSUE THREAD

**Issue by NickyHeuperman** [Sonarr/Sonarr#2343]
## Bug Report

For example; Sonarr is unable to parse episodes from release name for the following release:
Dragon.Ball.Super.E89.1080p.WEB.x264-ANiURL-Obfuscated

Which quite obviously is the 89th episode of dragon ball super in 1080p by the ANiURL release group

**Comment by markus101** [comment]
Sonarr doesn't have a way from that name to determine it's an absolute episode number instead of an episode number without a season, which Sonarr will treat as being part of season 1.

Covered by https://github.com/Sonarr/Sonarr/issues/457
