### ISSUE TITLE
Downloads not picked if torrent is in qBittorrent subcategory

### ISSUE THREAD

**Issue by MrDemous** [Sonarr/Sonarr#2346]
Sonarr doesn't see torrents that are in subcategories in qBittorrent e.g. BTN/Sonarr

Sonarr sends the torrent and sets the label correctly (BTN/Sonarr for me) in qBittorrent but then it seems that Sonarr doesn't see the torrent at all (doesn't show as downloading in Sonarr) if it's in a subcategory and therefore it doesn't import torrents when they finish downloading.

Sonarr version 2.0.0.5090
Windows 10 x64
qBittorrent 4.0.3

**Comment by Qstick** [comment]
This issue appears to be from qBittorrent not being able to handle an encoded API request. 

Sending this request in Postman gets results back:
`http://localhost:8080/query/torrents?label=RED/lidarr&category=RED/lidarr` returns results
Sending encoded request (as Sonarr and Lidarr do) gets no results:
`http://localhost:8080/query/torrents?label=RED%2Flidarr&category=RED%2Flidarr` returns `[]`

**Comment by markus101** [comment]
Given @Qstick's comment and  `/` being a reserved character in URLs it should be encoded and QBit should handle that on their side. I don't think this is something we want to work around and possible play wack-a-mole trying to encode some things and not others.

Closing this out, but if there is viable reason we should do something here, we can re-open it.

**Comment by MrDemous** [comment]
I opened an issue in qBittorrent's repo so hopefully, they can push an update that fixes this in the future.

https://github.com/qbittorrent/qBittorrent/issues/8168

**Comment by MrDemous** [comment]
Just an FYI. This is fixed in qBittorrent 4.1.0.
