### ISSUE TITLE
Cant add german TV Series

### ISSUE THREAD

**Issue by nuhll** [Sonarr/Sonarr#2347]
Hi, im using the latest sonarr version and it seems like u cant add german tv series.

E.g.
https://www.thetvdb.com/?tab=series&id=296987&lid=14

I tried "galileo", "wissensmagazin" and tvdb:296987

All result in: Sorry. We Couldn't Find Any Series Matching 'Tvdb:296987'

Same with "Spiegel TV" 
https://www.thetvdb.com/?tab=series&id=293495&lid=14
Sorry. We Couldn't Find Any Series Matching 'Tvdb:293495'

Any ideas?

**Comment by markus101** [comment]
This is covered in the FAQ: https://github.com/Sonarr/Sonarr/wiki/FAQ#why-cant-i-add-a-new-series-when-i-know-the-tvdb-id

Please use the forums for support.

**Comment by nuhll** [comment]
So this is a known "bug" u dont want to fix.

**Comment by markus101** [comment]
Where did I say we didn't want to support other languages?

See https://github.com/Sonarr/Sonarr/issues/269

**Comment by nuhll** [comment]
It sounds like?! What should the link tell me? Its 2 years old and it didnt got added... so i guess low prio?

**Comment by markus101** [comment]
It's blocked by other work, that has not been completed. When that work will be completed, I couldn't say.

**Comment by nuhll** [comment]
Thanks, i guess ill wait then... :)
