### ISSUE TITLE
Anime - Search for batch torrents on completed series.

### ISSUE THREAD

**Issue by Archmonger** [Sonarr/Sonarr#2350]
As far as I could tell from my testing, this is currently not a feature in Sonarr. Every so often, a batch result goes through for the episode, but it's pretty irregular, and seems to rely on a batch result showing up on Episode 1 search results.  This is even though Sonarr should always try to obtain a batch on completed series prior to beginning an episode search.
This would not only potentially reduce the total number of search requests, but also increase the chance of an automated search catching a result. This would be especially helpful for anime, as Sonarr currently fails many automated anime search requests due to searching for individual episodes rather than prioritizing batch searches. Nearly all anime torrents older than a year are found in batch form. 
Side note, if this feature was implemented it would be nice if there was a manual search option on each season/series that searched for batches, just as there is currently a manual search option on individual episodes.

**Paragraph Pseudocode** 
1) Check if series/season is marked as complete. If true, continue. If false, skip to individual episode searching (step 5).
2) If the series is single season, search for series name.
----- _SPECIAL CASE: Multi-Season_
----- 1) If the seasons are have the same name other than the addition of known season modifier values (2, S2, S02, X2, R2, 2nd, Second, I, II, etc) then search for the name of the series title _({Show Name})_. Then search for season titles _({Show Name} {Season Modifier})_ and create a merged pool of the all the search results. Use Sonarr's text parser on this pool to determine which results belong to a specific season..
----- 2) If the seasons have the names that are different beyond known season modifier values, search in separated result pools for _({Season Name})_ for each season. This will reduce the chance of Sonarr's parser mistaking a mistake while matching results under specific scenarios. Could be implemented with a merged search result pool as well, and would work in most situations.
----- 3) If no season names are known, fallback to merged pool of _({Show Name})_ and _({Show Name} {Season Modifier})_.
3) Begin torrenting the batch with the highest confidence value (the highest seeder value at the requested quality value, as long as the Sonarr's text parser matches it to the correct series and it does not contain blacklisted keywords).
4) If the discovered batch torrent was initiated but it is missing more than one episode to fill a series/season, then cancel the ongoing torrent and try another batch. (Can be checked by using the torrent's metadata to check the video file names).
----- _SPECIAL CASE: Single Episodes Missing_
----- 1)  If the batch contains all but one episode in a season (typically the last episode. It happens every so often.), then do an individual episode search for the single missing episode. 
----- 2) If the individual episode could not be found, then begin attempting other batch torrents
----- 3) If the new batch attempted does contain all episodes in the requested quality, then cancel the previous torrent and continue torrenting the newly found batch that is proper. 
----- 4) If the new batch tried does NOT contains all episodes in the requested quality, then cancel this and try the next batch.
5) If all discovered batches have been exhausted (or if series not yet complete), then resort to individual episode search. 

**Example search queries generated (single season):**
> Carnival Phantasm _<<< 95% of the time, searching for only the name of the series will work._

**Example search queries generated (multi season, major name differences):**
> JoJo's Bizarre Adventure
JoJo's Bizarre Adventure Stardust Crusaders
JoJo's Bizarre Adventure Diamond is Unbreakable

**Example search queries generated (multi season, minor name differences):**
> Mobile Suit Gundam: Iron-Blooded Orphans

**Parser: Types of scenarios expected:**
> _- Multiple seasons_
Mobile Suit Gundam: Iron-Blooded Orphans _<<< Assumed as first season_
Mobile Suit Gundam: Iron-Blooded Orphans S01
Mobile Suit Gundam: Iron-Blooded Orphans S02
Mobile Suit Gundam: Iron-Blooded Orphans S1
Mobile Suit Gundam: Iron-Blooded Orphans S2
Mobile Suit Gundam: Iron-Blooded Orphans Season 2
_- Different season names_
Jojo's Bizarre Adventure
Jojo's Bizarre Adventure Stardust Crusaders 
Jojo's Bizarre Adventure Stardust Crusaders S2
Jojo's Bizarre Adventure Stardust Crusaders 2nd Season
Jojo's Bizarre Adventure Stardust Crusaders 01-48
Jojo's Bizarre Adventure Diamond is Unbreakable
_- Multiple seasons in one torrent_
Durarara (S01, S02, OVA)
Durarara Complete
Durarara S1 Complete
Durarara Batch
Durarara S1 Batch
Durarara Complete (S01, S02, OVA)
Durarara Batch (S01, S02, OVA)
Durarara Complete Batch
Durarara (S1, S2)
Durarara S1 + S2
Durarara Season 1 + Season 2 + OVA
Hayate no Gotoku! (01-101)
Hayate no Gotoku! 01-101
_- Multiple season, irregular names, one torrent (this is hard to implement, and a pretty rare scenario. I would skip implementing this,)_
Monogatari Series Complete Batch
Bakemonogatari, Nisemonogatari, Nekomonogatari, Monogatari Series Second Season, Hanamonogatari, Tsukimonogatari
_- Series has two seasons a season are identically named, except are followed by ({Season modifier})_
JoJo's Bizarre Adventure Stardust Crusaders 01-48
JoJo's Bizarre Adventure Stardust Crusaders (S1 + S2)
_- Series name only followed by a quality_
Berserk 1080p
Berserk (1080p)
Berserk [1080p]
_- Parse out individual episodes during a batch search_
Jojo's Bizarre Adventure Stardust Crusaders Episode 2
Jojo's Bizarre Adventure Stardust Crusaders 02
Jojo's Bizarre Adventure Stardust Crusaders E02
Jojo's Bizarre Adventure Stardust Crusaders 2 _<<< For this scenario, can check torrent's metadata to confirm whether or not this is episode 2 or season 2 (if a second season is expected with this name). Alternatively, don't bother pre-checking metadata and allow this to be caught by step 4._ 

If I knew enough C# I definitely would have helped code this. Apologies in advanced for making a relatively large feature request. The majority of this appears to have already been implemented into the Sonarr parser, but it needs some refinement. I feel as if batch specific search prioritization would definitely put Sonarr as a perfect product, so I spent a decent amount of time thinking of some rough pseudocode to assist with the development cycle.

**Comment by xelra** [comment]
The examples you gave are actually pretty good. We've tried matching this kind of stuff simply through parsing in the paste in other projects than Sonarr. It just doesn't work. It's a bottomless pit.

I'm not exactly sure how the state of season parsing is in Sonarr right now, but I believe that the few positives you got mus have been from indexers that supported the newznab or torznab spec. Or from BTN.
And that's really all there is to it. Identifying content (and seasons) is the job of the indexer and Sonarr needs to get this information from there. Parsing is not the way to go.

**Comment by Archmonger** [comment]
I was under the impression that Jackett releases a list of that contains values of {uploadTitle}{magnetLink}{peers}{leechers}. If I'm understand what you're describing, seems like Jackett translates the uploadTitle into tokens and values, and Sonarr simply uses that data if it was found. I haven't analyzed the source code for Jackett or Sonarr, but that doesn't sound accurate. My impression was that Sonarr actively analyzers and parses uploadTitle names in order to determine matches. Looking at the rule sets, I can think of a few ways to implement a uploadTitle analyzer as a recursive descent parser that accurately matches all of the mentioned anime syntax.

I'd be willing to take a shot at creating an anime uploadTitle parser. If Jackett works as I assume it does, can someone shows me how to preview Jackett's output for a search query? Would be willing to learn C# to conform to the Sonarr project. Sounds like it'd be a fun summer project.

If this parser (more accurately I'm talking about a lexical analyzer + syntax analyzer) was implemented then all what would be needed to batch search is to have Sonarr search for [animeTitle] or [seasonTitle] for any non-episode specific search query, and have the parser handle the rest. Creating another parser to better handle individual episode search wouldn't be a monumental challenger either, based on what I've seen from the output of various nyaa.si searches.

Let me know if I can be of help.

**Comment by Archmonger** [comment]
I have reached the realization that the issue is due to Nyaa.si's API. Implementation within Sonarr to handle a public tracker's failure isn't a reasonable request.
