### ISSUE TITLE
Max number of tasks reached. Cannot add any more TV Shows.

### ISSUE THREAD

**Issue by BetaLeaf** [Sonarr/Sonarr#2352]
Sonarr Version: 2.0.0.5085 - Dec 7 2017 [Docker]
Mono Version: 5.4.1.6

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/1591702/sonarr.txt) (It's towards the end of the log, but there is other funny business going on as well.)

Basically, I try automatic and manual search (in sonarr) for my tv shows, but I get an error saying Max number of tasks reached. I manually added the magnet link in Synology Download Station, and it added just fine. What's going on here?

**Comment by Taloth** [comment]
Please provide Debug or Trace level log files, not Info. https://github.com/Sonarr/Sonarr/wiki/Log-Files

**Comment by markus101** [comment]
Old post, but potentially related to the user Sonarr is connecting to download station as: https://forum.synology.com/enu/viewtopic.php?t=69857

**Comment by BetaLeaf** [comment]
Here are the logs you requested:

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/1594659/sonarr.txt)
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/1594663/sonarr.debug.txt)
[sonarr.trace.0.txt](https://github.com/Sonarr/Sonarr/files/1594661/sonarr.trace.0.txt)

**Comment by BetaLeaf** [comment]
Issue resolved. Fix was to set the account that is doing the downloading as an administrator. Probably some quota limit in synology.
