### ISSUE TITLE
Less than / Greater than characters

### ISSUE THREAD

**Issue by Mistywing** [Sonarr/Sonarr#2353]
### System Information/Logs

**Sonarr Version:**
2.0.0.5085
**Operating System:**
Windows 10 Pro X64
**.NET**
.NET Framework 4.7.1 (461308)
### Additional Information

< and > symbols disappear inside certain fields, along with the text inside them. Very minor cosmetic issue.
Example is [this episode](https://www.thetvdb.com/?tab=episode&seriesid=333881&seasonid=726586&id=6469195&lid=7)'s description [parsed through Sonarr](https://i.imgur.com/0qlpIHK.png).

**Comment by Taloth** [comment]
Yes, due to the frequent spam on thetvdb, html tags are filtered out. Use the html entities &lt; &gt; instead. So this is intended behavior.

**Comment by Mistywing** [comment]
Gotcha. Thanks for answering and shame about the spammers ruining things for everyone as always.
