### ISSUE TITLE
[Feature Request]: Per-series indexer restrictions

### ISSUE THREAD

**Issue by faminebadger** [Sonarr/Sonarr#2354]
Currently, indexer restrictions is limited to globally specifying words that either must or must not be contained.

I've had some bother with bad subtitles of anime in the past, so it would be good to be able to specify that my indexer should require a keyword such as "HorribleSubs" (for example).

However, if I do that it applies to everything.  Therefore, it would seem a useful feature to be able to specify this per series - so I can just set it on the anime that I have trouble with.

**Comment by markus101** [comment]
You can specify them per series via tags. Add a tag to the restriction and the same tag to one or more series.
