### ISSUE TITLE
Improvement for non-English shows

### ISSUE THREAD

**Issue by piejanssens** [Sonarr/Sonarr#2360]
For non-English profiles there should be an option/checkbox to take the 'English' detected version if the episode is not found in the selected language. 

Why? Because in a lot of cases the (P2P) release will not contain the specific indicator such as 'DUTCH', but as an admin I know that this particular tv show does not exist in any other language so it's safe to take the release without language tag which Sonarr recognizes as 'English'.

**Comment by markus101** [comment]
No plans to add such an option.

Language profiles would allow you to select multiple languages and prefer one over another: https://github.com/Sonarr/Sonarr/issues/274
