### ISSUE TITLE
Sonarr preserves the . in front of series name for files, making them hidden on *nix style systems.

### ISSUE THREAD

**Issue by dwhagar** [Sonarr/Sonarr#2365]
### System Information/Logs

**Sonarr Version:** 2.0.0.5085

**Operating System:** Ubuntu Linux 16.04 LTS

**.net Framework (Windows) or mono (macOS/Linux) Version:** 5.4.1.6

**Link to Log Files (debug or trace):** None

**Browser (for UI bugs):** N/A (not a UI bug)

### Additional Information

This bug only effects linux-type systems where a `.` at the front of a filename makes it hidden.

### What problem are you looking to solve?

When a series name contains a `.` at the front of it, the system renames episode files to include that (but not the series name for the folder).  This prevents most applications from seeing the files.  In particular, I've tested this with my Plex server on the same system listed above.  Plex is incapable of being set to look for hidden files.

Since Sonarr correctly removes the `.` from the series name when creating the directory structure to import files, it should also remove the character from the file name as well.

### Other Information

This follows the same behavior even if one uses the "Clean" option for the series name, the `.` is still included.  The series tested was ".hack", the folder name came out "hack" (good), but all the files are considered to be hidden by the OS because they contain the dot in front.

**Comment by Taloth** [comment]
Can you include all your renamer formats for completeness?

**Comment by dwhagar** [comment]
Sorry for the long wait, here you go:
```
{Series Title} - S{season:00}E{episode:00} - {Episode Title} {Quality Title}
{Series Title} - {Air-Date} - {Episode Title} {Quality Title}
{Series Title} - S{season:00}E{episode:00} - {Episode Title} {Quality Title}
{Series CleanTitle}
Season {season:00}
```
That is, in order; Standard, Daily, Anime, Series Folder, and Season Folder.

**Comment by markus101** [comment]
@Taloth for folders we trim spaces and periods before using, for the file name we only trim spaces. Seems like a bit of an oversight to not do it for filenames, but has the impact of affecting every future filename.

I think we can either trim the periods for filenames as well or merge it with one of the other clean title issues https://github.com/Sonarr/Sonarr/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+cleantitle (we should probably combine a few of those issues into one, since they are almost identical).

**Comment by Taloth** [comment]
The cleantitle wip is a serious refactoring changing the actual behavior and this is just one specific scenario. So probably better to just add a unittest and fix this separately.
