### ISSUE TITLE
Limit Indexer & Download Client backoff logic during the first 5-10 minutes of startup

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#2366]
Particularly during OS startup the network, indexers and download client(s) might not yet be available.
This is especially applicable to non-24/7 systems. Where Escalation persists between startups.
An already escalated indexer/client, would immediately be blocked again for 24h (for indexers) and 3h (for download clients) after the first attempt.
Meaning that once the system gets into a significant amount of escalation, it would not get out of it again.

The solution would be twofold:
1) Do not increase `EscalationLevel` if already equal or above 1 if a failure occurs within 15 minutes of process startup. Allowing roughly 3 attempts before further escalation occurs. (Unless mandated by the indexer-provided `minimumBackOff`.)
2) Limit `DisabledTill` to 5 minutes since Now, even if the `EscalationLevel` requires a longer period. 

Both modifications should be done in the `ProviderStatusServiceBase` class.

**Comment by Safihre** [comment]
I would suggest actually to maybe have Sonarr back-off for that time after (system) startup instead? 
Maybe it's the Spectre/Meltdown patch but my startup has been a lot longer yesterday+today and it included Sonarr wanting full CPU power for probably a minute or 3 to process 2.000 RSS items. 

If it could also include a back-off timeout after coming out of standby, this would help a lot during those first few (~20) seconds in which (especially wireless) connections are re-established ([mentioned here](https://github.com/Sonarr/Sonarr/issues/1961#issuecomment-306287306)).

**Comment by daniel-loader** [comment]
I delay sonarr starting 2 minutes with systemd timers, windows can do delayed starts on services too.

**Comment by Safihre** [comment]
True probably (didn't test yet), but not when the laptop comes out of standy and is a few seconds slow with connecting to the network.
