### ISSUE TITLE
[FEATURE REQUEST] Multilanguage search for episodes of series

### ISSUE THREAD

**Issue by Atka122** [Sonarr/Sonarr#2368]
Dear Developers!

I miss a really big feature from the Sonarr. I am a Hungarian guy and there are a lot of Hungarian TV Series what I would like to download automatically with the Sonarr, but I cannot do that because the series has not got English title. For this, I have to use another software, but it could be really helpful if I could use the Sonarr for every series. As I think, that there are a lot of people who would like to use the Sonarr for downloading non-English series.
I found a ticket about this, but it is blocked now: https://github.com/Sonarr/Sonarr/issues/269?_pjax=%23js-repo-pjax-container

However, in the Radarr everything works well. So if I would like to download a movie in Hungarian language, the Radarr will search it in that language. Is it use another technology? Or can this feature be implemented in Sonarr too?

Thank you for your help!

**Comment by markus101** [comment]
Closing this as other languages is covered by #269 even though it is blocked until work on Skyhook supports multiple languages.
