### ISSUE TITLE
Restriction - How to insert a tag with 2 word?

### ISSUE THREAD

**Issue by Jorman** [Sonarr/Sonarr#2369]
Hi, I'm on Sonarr Ver. 2.0.0.5111
With Mono Version 5.4.1.6

Actually I use sonarr to keep update some series, some on original (English) language and some on my native language, so:
1. I added a new profile with my language (Italian in this case) I don't know what exactly do the program with that but I think is important.

But sonarr grab and download series with my Italian profile, in English or not on right language, for example the last one is Young Sheldon, sonarr grab and download this rel:

**Young Sheldon S01E01 [SATRip 720p - H264 - Eng Ac3 - Sub Ita] HDTV by AVS**

Basically I think that sonar search for some tag or I don't know, IMHO also the Italian title can be a good idea (a lot of times, when the episode is available on the country, the title change into the country title (most of time each country translate the title) but is only one example, lol)
Return to the problem, so I think that Sonarr see ita on title so think that the rel was ita, but no. Is with English audio AC3 and only sub ita.

So I added a new Restriction tag under Indexers page (see image) to exclude some codec that my player don't like so much and I added a rule to "try" to figure out a problem that I've
![1](https://user-images.githubusercontent.com/5203988/34908381-0d24bdfe-f88f-11e7-8018-827878183b74.PNG)

If I try to add sub ita sonar make 2 tag, so I copy/paste the whole "sub ita" word and I added to the tag, but sonarr still grab the rel

There's any other way to tell to sonarr to not download the sub ita rel?
I also see this post https://github.com/Sonarr/Sonarr/pull/2361#pullrequestreview-88642627
I don't know how to make reg expression, for me is quite impossible to understand that but if works I can try to find out a way to do that

I hope I've explained myself

Tnx, Jo

**Comment by markus101** [comment]
It's not currently possible to do multi-word restrictions. https://github.com/Sonarr/Sonarr/pull/2361 has not yet landed, until it does you can't use regex either, but that will be tole solution to it.

**Comment by Jorman** [comment]
So, I've to wait, right?

Tnx for the info

**Comment by markus101** [comment]
Yes, it won't be there until that PR lands and a build that contains it is out.
