### ISSUE TITLE
Updating not working

### ISSUE THREAD

**Issue by silentmiles** [Sonarr/Sonarr#2370]
## Bug Report

Attempting to update using the build-in mechanism is failing. I get the following error in the logs:

> GET /api/update: HTTP request failed: [521:521] [GET] at  [http://services.sonarr.tv/v1/update/develop/changes?version=2.0.0.4689&os=linux&runtimeVer=5.4.1.6]

In fact, when I browse this URL directly, I get a 503 or 504 error. Is this service undergoing maintenance?

### System Information/Logs

**Sonarr Version:** 2.0.0.4689

**Operating System:** Synology 

**.net Framework (Windows) or mono (macOS/Linux) Version:** Mono 5.4.1.6

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**

**Comment by markus101** [comment]
There were issues with the server hosting that service. They have been resolved now.
