### ISSUE TITLE
Multiple directories

### ISSUE THREAD

**Issue by atytel** [Sonarr/Sonarr#2374]
### What problem are you looking to solve?
The ability for sonarr to have shows exist in 2 locations at once. So you would add dir1 and dir2. Sonarr would check if there are ep in dir1, if not it would check dir 2. aswell it might be possible to tell sonarr to just write to one folder.
### Other Information
I know plex does something like that by allowing you to have multiple folders for media ingest under the same sub headder.

**Comment by markus101** [comment]
Previous GHIs on the subject:

- https://github.com/Sonarr/Sonarr/issues/1016
- https://github.com/Sonarr/Sonarr/issues/1762
- https://github.com/Sonarr/Sonarr/issues/1693

At this time we don't have plans to support more than one series folder.
