### ISSUE TITLE
Renaming file but not title and comments in file properties

### ISSUE THREAD

**Issue by CrazyLittleBunny** [Sonarr/Sonarr#2375]
When renaming and moving files everything seems to be fine but when playing a file it shows the title as the original download title. Then when checking the title and comments in the file properties it has the original file name.

Is there any way to change this that it replaces the title with the correct file name and clear the comments?

This is with using SABNZBD and Windows 10.

**Comment by markus101** [comment]
This isn't something that Sonarr would do directly, but it should be possible with a custom script in Sonarr.
