### ISSUE TITLE
Advacned Settings toggles should have a "red" colour when settings are hidden.

### ISSUE THREAD

**Issue by vajonam** [Sonarr/Sonarr#2378]
Both states are yellow and misleading. I spent 30 minutes debugging why i couldn't see a specific option!

https://pasteboard.co/H3HPtqd.png

https://pasteboard.co/H3HQ3Xa.png

Should have some difference in colo(u)r!

**Comment by markus101** [comment]
This is changed in the v3 UI work, no plans to change it in the v2 UI.
