### ISSUE TITLE
SeriesModule failed while processing []

### ISSUE THREAD

**Issue by JourneyOver** [Sonarr/Sonarr#2379]
## Bug Report
 
Various different tv shows have been throwing off this EventAggregator error constantly when trying to update a series either through API  or on the WebUI..

### System Information/Logs

**Sonarr Version:** 2.0.0.5124

**Operating System:** Windows 10 x64 bit latest updates on Fall Creators Update

**.net Framework (Windows) or mono (macOS/Linux) Version:** 4.0

**Link to Log Files (debug or trace):** https://paste.ee/p/2LNbV

**Browser (for UI bugs):**

### Additional Information
Doesn't happen on every single series but a huge portion of my shows throw this error off..

**Comment by markus101** [comment]
Fixed in: https://github.com/Sonarr/Sonarr/commit/90f9dce44a7526ea65fc64d6ad36a108c81df400

Just not in a build yet.
