### ISSUE TITLE
Filter by white space in Restrictions

### ISSUE THREAD

**Issue by SirSilent** [Sonarr/Sonarr#2380]
There needs to be a way to match white space in Restrictions.

" WEB " is used in fake WEB-DL/Rips which are actually HDTV, but it is not currently possible to be able to exclude these releases.

**Comment by Taloth** [comment]
Similar to https://github.com/Sonarr/Sonarr/issues/2264 (although it's not possible to add a space via the UI)

WEB is simply the scene's tag for WEB-DL, some torrent sites replace the dots with spaces, so they could certainly be valid releases. I'd suggest you find a more reliable way of dealing with fakes like this.
