### ISSUE TITLE
Torrents Aren't Removed from Transmission after Seeding is Complete

### ISSUE THREAD

**Issue by Hossy** [Sonarr/Sonarr#2382]
### System Information/Logs

**Sonarr Version:** 2.0.0.5085

**Operating System:** Docker on Synology DSM 6.1.1-15101 Update 4

**.net Framework (Windows) or mono (macOS/Linux) Version:** 5.4.1.7

**Link to Log Files (debug or trace):** Info logging was enabled at the time.  I have switched it to Debug.
[20180124-sonarr_logs-CLEANED.txt](https://github.com/Sonarr/Sonarr/files/1660246/20180124-sonarr_logs-CLEANED.txt)

**Browser (for UI bugs):** N/A

### Additional Information

I reviewed https://github.com/Sonarr/Sonarr/issues/1429, but Remove is enabled under Completed Download Handling.  I recently switched to Transmission from uTorrent.  Sonarr used to remove from uTorrent just fine, but hasn't been doing that for Transmission.

The torrent that wasn't removed is: SHOW-NAME.S01E01.1080p.HDTV.x264-RELEASE-GROUP[SITE]

**Comment by markus101** [comment]
We'll need to see trace logs that include the response from transmission (with the list of torrents).

The torrent needs to be paused in transmission for Sonarr to remove it.

Please open a thread on the forums with the relevant log files, if necessary we can reopen this issue if there is a bug.
