### ISSUE TITLE
UI unresponsive during tasks

### ISSUE THREAD

**Issue by jameseck** [Sonarr/Sonarr#2383]
Hi,

I'm running Sonarr inside docker within an Openshift cluster.  Openshift uses healthchecks to determine if the docker container is healthy and if it isn't, it will restart it.  The healthchecks poll Sonarr with an http GET request.
I've noticed that when Sonarr is busy during some tasks, the web ui becomes unresponsive.
This results in either the container being restarted due to failing healthchecks, or the need to have very large timeouts to prevent this from happening.

I just wanted to throw this out there to see if anyone else is experiencing a similar issue.

**Comment by markus101** [comment]
I don't recall anyone reporting a similar issue offhand.

You may have luck looking at the trace logs to see exactly what Sonarr is doing, but it shouldn't lock up like that and I haven't experienced that with Sonarr running in docker.

If you have some logs you think might be worth looking at, please open a thread on the forums and we can help troubleshoot there.
