### ISSUE TITLE
Subject Line in Notifications

### ISSUE THREAD

**Issue by Vacant0mens** [Sonarr/Sonarr#2386]
## Feature Request
Add a `Include Subject Line` option to notification templates. (ability to send notification without a subject line)

### What problem are you looking to solve?
Having the subject line included in notifications (especially in Slack and Discord) looks messy, especially when it says the same thing as the message body (other than 'Grabbed' or 'Imported') and takes up a lot of application real estate compared to a simple message.

Having it just send a simple message that says `Grabbed: [tvshow] [season][episode] ([quality])` or `Imported: [tvshow] [season][episode] ([quality])` with no subject line would be much nicer looking for the most part because it would just be a one-line message rather than a message block or post.

**Comment by markus101** [comment]
Covered by https://github.com/Sonarr/Sonarr/issues/328
