### ISSUE TITLE
Can't add linux paths for shows

### ISSUE THREAD

**Issue by Grimshad** [Sonarr/Sonarr#2394]
### System Information/Logs

**Sonarr Version: 2.0.0.5085

**Operating System: Docker

### Additional Information

I just migrated from windows to a docker. Everything went well except when I try to change the paths of the shows from S:\Video\Anime\Show to /tv/Anime/Show it does not take.

It either says path is not valid or the check box does nothing.

It allows me to browse the path fine, only when submitting the path does it fail.

![image](https://user-images.githubusercontent.com/16975293/35764042-c3b91554-0886-11e8-9f8e-d8e8c97a422b.png)

**Comment by markus101** [comment]
This is covered on the wiki page: https://github.com/Sonarr/Sonarr/wiki/Backup-and-Restore#restoring-from-backup

Switching OSes that use different paths is not supported, you'd need to manually edit the DB to fix the paths.
