### ISSUE TITLE
Series folder should be deleted when empty

### ISSUE THREAD

**Issue by adamradocz** [Sonarr/Sonarr#2395]
When I delete the last episode with Sonarr, it doesn't delete the Series folder and leave it empty.
The empty folder should have been deleted.

Sonarr Ver. 2.0.0.5085
Ubunti Server 17.10.1

**Comment by markus101** [comment]
Deleting the episode from the UI or when Sonarr sees that all files have been deleted during a disk rescan?

**Comment by adamradocz** [comment]
Both cases.
