### ISSUE TITLE
Show disk space used by episode files in footer of main Series view

### ISSUE THREAD

**Issue by nabingham** [Sonarr/Sonarr#2396]
On the main page (Series), at the bottom it currently shows the total number of series and episode files tracked by Sonarr.  A feature enhancement would be to also display the disk space consumed by the episode files.  When viewing an individual series the disk space is already displayed (at the top), so aggregating this seems do-able.

As fas as I know, there is not currently a way in Sonarr to currently check how much disk space all of your Sonnar-tracked episodes are consuming.  The workaround is to go into each series and manually sum up the storage space.  The System page displays total and available space but not space consumed by all episode files.

Sonarr Ver. 2.0.0.4949

**Comment by markus101** [comment]
Done in the v3 work.
