### ISSUE TITLE
Party of 1-2-3 won't recognize in Sonarr, but it's on theTVDB.com whassup?

### ISSUE THREAD

**Issue by dny238** [Sonarr/Sonarr#2397]
Trying to add a new show...
https://www.thetvdb.com/?tab=season&seriesid=342025&seasonid=749489&lid=7

Neither Party of 1-2-3 or tvdb:342025 seem to work.

**Comment by markus101** [comment]
>## Support / Questions
>Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

Please use the forums for support. You'll need to include the requested information (version, logs, etc) when opening the thread.
