### ISSUE TITLE
Option to use PFX certificate instead of hash thumbprint (for automation)

### ISSUE THREAD

**Issue by E-v-o** [Sonarr/Sonarr#2399]
## Feature Request
Use PFX certificates instead of a hash thumbprint.

### What problem are you looking to solve?
Using the hash works fine, but when using free CA's (such as Lets Encrypt) the expiry time can be only two months, this means every few month you need to manually import the cert and change the hash. If you could direct to where the cert is then multiple tools exist to automatically renew existing certificates, this means every two months I would just need to set a task schedule to restart the service and it would pick up and use the new certificate.

### Other Information
The programs main use is automation, so why not add a method for people to have everything automated :)

**Comment by markus101** [comment]
This is not currently possible given the web server Sonarr uses. When we switch web servers, likely after https://github.com/Sonarr/Sonarr/issues/948 this is something we'll look into.

Closing this out as this is on our radar as part of switching web servers.
