### ISSUE TITLE
Clean original filename

### ISSUE THREAD

**Issue by mueslo** [Sonarr/Sonarr#2401]
A lot of releases from indexers will have names such as "\<actual name\> English.mkv". I want to preserve the original filenames but also remove the language suffix which is not part of the actual release name.

**Comment by markus101** [comment]
A script that cleans up the filename after the download is complete, but before Sonarr imports the file would be the best to deal with this, alternatively a custom script in Sonarr run after inporting would work, but would result in Sonsrr needing to rescan the file.

Custom cleanup rules on the file before import isn't something we plan to do, at lest at this time.
