### ISSUE TITLE
Windows Toast Notifications

### ISSUE THREAD

**Issue by zbigniewzolnierowicz** [Sonarr/Sonarr#2403]
## Feature Request
Support for [Windos's BurntToast](https://github.com/Windos/BurntToast) or a similar program.
### What problem are you looking to solve?
Lack of toast notifications on Windows.
### Additional information
Alternatives I found on a short notice: [jithurjacob/Windows-10-Toast-Notifications](https://github.com/jithurjacob/Windows-10-Toast-Notifications).

**Comment by markus101** [comment]
Since it's a powershell module, a custom script would be the easiest way to use BurntToast and customize the notifications.

The python library is of no use to Sonarr, but https://github.com/noxad/windows-toast-notifications has a demo on how to achieve toast notifications.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
