### ISSUE TITLE
[Bug] Remove Completed Not Working

### ISSUE THREAD

**Issue by zero77** [Sonarr/Sonarr#2406]
Correct me if I am wrong but, the remove option under download clients should remove the completed torrent entry from the torrent client once it's been marked as downloaded.

It doesn't seem to be doing that, it just stays in the torrent client and under activity, with nothing else happening.

I am using the newest version and connecting by the httprpc plugin for rtorrent/rutorrent on Ubuntu.

**Comment by markus101** [comment]
It won't remove it if it's still seeding, in addition there is a warning when adding/editting rtorrent settings in Sonarr that says it's not supported.

**Comment by zero77** [comment]
So are you saying that it’s not possible at all in rtorrent/rutorrent ?

**Comment by markus101** [comment]
Correct.
