### ISSUE TITLE
[Feature Request] Move finished torrents to seeding folder and hard link to media folder

### ISSUE THREAD

**Issue by MrDemocracy** [Sonarr/Sonarr#2407]
### What problem are you looking to solve?
I would like Sonarr to move finished downloads to a seeding folder so that seeding files isn't in the same folder as the files currently being downloaded. I still want the seeding files to be hardlinked to my media folder while they're seeding.

**Comment by markus101** [comment]
That's something your client should take care of, not something that Sonarr would do.
