### ISSUE TITLE
ASD qwe$ gec GV

### ISSUE THREAD

**Issue by danvb329** [Sonarr/Sonarr#2408]
car maked under uche-aetck. 56proceed -0 c dd 07 -60me

**Comment by markus101** [comment]
![image](https://user-images.githubusercontent.com/413544/36136606-3e5fd9f2-1046-11e8-84a4-1d29ccaeca37.png)

**Comment by Taloth** [comment]
Thank you for the issue report "Cat bashing on keyboard", it's not really Sonarr related hence the closure, but I'll be happy suggest a solution:
Use so called 'environmental punishers' to dissuade the cat from jumping on table tops. For example, a light sheet draped over the edge of the table. This will work even if you aren't present, so the cat will associate the inevitable (light) tumble as their own mistake and learn from it.
Naturally, environmental punishers work best if good alternatives are available; An comfortable perch hanging on the heating radiator (if present) is particularly effective as it's both higher up and a nice temperature.
Please note that shooing, kicking, water sprays, traps and other kinds of punishment are counter-effective as it will teach the cat to fear you and all the consequences that brings. It might lead to the cat retaliating by scratching your eyes out or worse... post all your nudes online.
