### ISSUE TITLE
Sonarr won't hardlink anything

### ISSUE THREAD

**Issue by MrDemocracy** [Sonarr/Sonarr#2409]
### System Information/Logs

**Sonarr Version:**
Ver. 2.0.0.5085

**Operating System:**
Windows 10

**.net Framework (Windows) or mono (macOS/Linux) Version:**
.net Framework v4.7.02556

**Link to Log Files (debug or trace):**
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/1719358/sonarr.debug.txt)

**Browser (for UI bugs):**
Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)
### Additional Information
I don't think it's related to permissions since I have set the folder to give everyone full access, and I'm the current owner of the volume.

**Comment by markus101** [comment]
Please use the forums for support.

In the logs I don't see any attempts to import a file that failed to hardlink.

**Comment by MrDemocracy** [comment]
Isn't this a hardlink error? `|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr`

**Comment by markus101** [comment]
No that looks like a permissions problem.

**Comment by MrDemocracy** [comment]
I think I found out why this was happening...Sonarr isn't looking for the actual filename, but the download name given by the magnet-url. The filename in the error log is different from the filename of the actual file.
Should this be happening? [Zooqle](https://zooqle.com) always (I think) use `magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a&dn=([zooqle.com]movie-or-episode-name)` on all their magnet links.

**Comment by MrDemocracy** [comment]
It's looking for a path that doesn't exist. It's not because of permissions.
