### ISSUE TITLE
On Delete for Connections

### ISSUE THREAD

**Issue by adamradocz** [Sonarr/Sonarr#2410]
Hi,

Please add "On Delete" feature to the Connection tab. When I delete a Series or Episode with the Sonarr, it should update the Plex library.

**Comment by bakerboy448** [comment]
use[ plex_autoscan](https://github.com/Cloudbox/autoscan)

**Comment by markus101** [comment]
This is supported in Radarr and would support removing items from Trakt as well.

**Comment by Thirrian** [comment]
This would also open a lot of possibilities for custom scripts 😬

**Comment by RobinDadswell** [comment]
Assign this to me and I will start working on this over the next few weeks
