### ISSUE TITLE
Not getting responses when looking for new TV Shows or Sonarr maintinanace

### ISSUE THREAD

**Issue by campbc** [Sonarr/Sonarr#2411]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Sonarr Version:**
    2.0.0.5134

**Operating System:**
Ubuntu 16.04

**.net Framework (Windows) or mono (macOS/Linux) Version:**
    5.8.0.108

**Link to Log Files (debug or trace):**
Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources.

**Browser (for UI bugs):**
HTTP Error - Res: [GET] http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=big%20bang: 522.522
HTTP Error - Res: [GET] http://services.sonarr.tv/v1/update/develop?version=2.0.0.5134&os=linux&runtimeVer=5.8.0.108: 522.522
### Additional Information
Cloudflare Ray ID: 3ed0996bc11a1ffa

"error_desc" Connection timed out

### What problem are you looking to solve?
Cloudfare Dallas returning 522 error and not responding to requests since this morning.

**Comment by berndveit** [comment]
Same issue:

Sonarr Version:
2.0.0.5134

Operating System:
macOS 10.13

.net Framework (Windows) or mono (macOS/Linux) Version:
5.8.0.108

Forum:
Error 522 Ray ID: 3ed120b30d160c65 • 2018-02-14 15:41:16 UTC

**Comment by alaunay** [comment]
Same thing for https://forums.sonarr.tv/ using a classic browser.

**Comment by M0UL** [comment]
skyhook is down. use tvdb:[series id] to add shows to sonarr, til skyhook comes back online

**Comment by markus101** [comment]
The server hosting skyhook, services and the forums is currently down and we're waiting on the host to take a look (though they're usually on it quicker than this). Adding/refreshing series is not possible until it returns. When TVDB has issues adding by the ID does work, but skyhook being offline means that doesn't work.

**Comment by markus101** [comment]
Server had a dead motherboard and it's been replaced.

I misspoke before and you can add by TVDB ID when skyhook is down because CloudFlare is caching that data, it's just searches that will fail.

We're still working on upgrading skyhook to support redundant front ends to avoid these problems as much as we can in the future.
