### ISSUE TITLE
Deluge 2 Beta Authentication Support

### ISSUE THREAD

**Issue by danielloader** [Sonarr/Sonarr#2412]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Sonarr Version:**
2.0.0.5085

**Operating System:**
Ubuntu Server 16.04.3 LTS

**.net Framework (Windows) or mono (macOS/Linux) Version:**
Mono 4.2.1

**Link to Log Files (debug or trace):**
```
18-2-14 16:43:36.5|Error|Deluge|Unknown method

[v2.0.0.5085] NzbDrone.Core.Download.Clients.DownloadClientAuthenticationException: Unknown method
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult] (NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings, System.String method, System.Object[] arguments) <0x40fb7680 + 0x0019f> in <filename unknown>:0 
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.GetVersion (NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings) <0x40fb7620 + 0x00047> in <filename unknown>:0 
  at NzbDrone.Core.Download.Clients.Deluge.Deluge.TestConnection () <0x40fb6f70 + 0x000a0> in <filename unknown>:0 

18-2-14 16:43:36.5|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Authentication failed
```
**Browser (for UI bugs):**
Chrome Latest
### Additional Information
Deluge 2.0.0.dev7125 

### What problem are you looking to solve?
Be able to pass the test in the download client modal.

### Other Information

I think it's actually working and passes torrents correctly, just throws an error here.

**Comment by Subcode** [comment]
Having the same issue.
Sonarr:  2.0.0.5169
Deluge: Deluge 2.0.0.dev7126

**Comment by cocokola** [comment]
Having the same issue 
Sonarr: 2.0.0.5163
Deluge : 2.0.0.Dev7126

**Comment by BoKKeR** [comment]
I can take a look at this. The login seems to be going through. 

`5:06:30 [DEBUG   ][deluge.ui.web.auth            :61  ] Received a password via the 1.2 auth method
15:06:30 [INFO    ][deluge.ui.web.auth            :65  ] Login success (ClientIP 127.0.0.1)
15:06:30 [DEBUG   ][deluge.ui.web.auth            :61  ] Creating session for admin`

**Comment by BoKKeR** [comment]
The problem is with the `daemon.info` method. As of right now, it seems to be missing from the new deluge release. As it returns 
`"message": "Unknown method",` 
While the old 1.3.11 returned the version number in the json
`"result": "1.3.11",`
I think the best we can do is contact the developer and ask about it. I am sure it will be added sooner or later.

**Comment by MrMxyzptlk** [comment]
Has any progress been made on this? I'm still unable to authenticate in Sonarr to Deluge.

Latest Sonarr and 2.0b1 Deluge...

Webui and daemon work great outside of Sonarr..

Thanks!

**Comment by Taloth** [comment]
It's quite literally a deluge issue. They removed the daemon.info api call. There is an open issue about their own code expecting daemon.info to exist, see https://dev.deluge-torrent.org/ticket/2842
Anyway, I patched it a bit on our side, in the unlikely event that they release their beta as final.

**Comment by Matty666** [comment]
@Taloth you beat me to it, I was just setting up deluge (been meaning to for a while), came back to look at the issue and it's closed :)

**Comment by Taloth** [comment]
Ah, damn, I didn't hear back from you so didn't expect you to pick it up. Anything else you like to pick up? Alternatively, if you have a topic or subsystem that you're interested in then I could try find a related issue. Lemme know.
