### ISSUE TITLE
Move file instead of Copying from download location - even if not done seeding.

### ISSUE THREAD

**Issue by Knoxie** [Sonarr/Sonarr#2413]
### What problem are you looking to solve?

My client downloads to a /download folder and I then have it copy the completed file into a new sorted folder for Sonarr to pull it from without any permission/file in use issues. Sonarr then copies it from there to the correct folder but does not remove the old copy because it thinks that file is seeding.

**Comment by markus101** [comment]
That case will be covered by https://github.com/Sonarr/Sonarr/issues/282 (providing a way to tell Sonarr that files are copies and can be moved instead of only copied, even while seeding).
