### ISSUE TITLE
Separate Anime and TV-Shows into two lists.

### ISSUE THREAD

**Issue by LAP87** [Sonarr/Sonarr#2414]
## Feature Request
Separate Anime and TV-shows via lists/tabs/different pages.

### What problem are you looking to solve?
Not having my anime and tv-show libraries intermix in the main view.

### Other Information
I saw references to this request on trello, but couldn't see it answered/solved anywhere here or on the 'net.

**Comment by markus101** [comment]
No plans to support different lists for TV and Anime, though we do plan to add additional filters, such as by tags: https://github.com/Sonarr/Sonarr/issues/566
