### ISSUE TITLE
Secure Update URL

### ISSUE THREAD

**Issue by neutralvibes** [Sonarr/Sonarr#2415]
**The url checking for updates isn't using SSL.** not sure this was intended as it seems to support it.

### System Information/Logs

**Sonarr Version:**2.0.0.5085 - 07 Dec 2017  

**Operating System:**Linux (via docker)

**.net Framework (Windows) or mono (macOS/Linux) Version:**5.8.0.108

**Comment by markus101** [comment]
Intended at the moment because mono prior to 5.0 and .net 4.0 only clients do not support TLS 1.1/1.2.

Thanks for the reminder, this will be fixed in v3.
