### ISSUE TITLE
Foreign languages

### ISSUE THREAD

**Issue by MaddionMax** [Sonarr/Sonarr#2418]
Hello!

Possible with Sonarr search series in hungarian language?
I added my hungarian indexer throuth Jackett, but not able to seach in hungarian language, just in english.
This cause that I'm not able to download originally english series which are dubbed with hungarian language, because their titles also translated.

It's an issue or maybe I done something wrong?

**Comment by markus101** [comment]
Please use the forums for support and other questions.

If Sonarr has an alias for the Hungarian name it will, but without https://github.com/Sonarr/Sonarr/issues/269 or an alias it won't. See the FAQ for information on the aliases.
