### ISSUE TITLE
Multi-Episode naming error with specific format when selecting scene or prefixed range

### ISSUE THREAD

**Issue by juspamail** [Sonarr/Sonarr#2420]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

## Bug Report

Have sonarr set to rename like this:

s{season:00}e{episode:00} - {Episode Title}

When it is set like this getting:

Multi-Episode Example: Invalid format

When selecting either "Scene" or "Prefixed Range"

However, if I add an additional option to the naming format the error goes away and it properly formats the name, Example:

{Series Title} - s{season:00}e{episode:00} - {Episode Title}

### System Information/Logs

**Sonarr Version:**

Version 2.0.0.5085

**Operating System:**

QNAP QTS 4.3.4

**.net Framework (Windows) or mono (macOS/Linux) Version:**

Mono Version 4.6.2

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**

**Comment by markus101** [comment]
Fixed in https://github.com/Sonarr/Sonarr/issues/2359
