### ISSUE TITLE
Full season grabbed, but one or more file missing after the parsing phase

### ISSUE THREAD

**Issue by Jorman** [Sonarr/Sonarr#2422]
Hi, I'm on latest develop version of Sonarr, on Qnap system with Mono 5.4.1.6

Hi hope I can give you some details about this error, is not the 1st time that I expect this error but I always see the error months after, so

The problem came after a download, I think, and that is what happen
Sonarr grab an entire season
![1](https://user-images.githubusercontent.com/5203988/36498584-fc6796a2-173e-11e8-94cb-a3cd6d96b149.PNG)

Sonarr handle the downloaded files but after that one or more episode are missing
![2](https://user-images.githubusercontent.com/5203988/36498612-18ddf90c-173f-11e8-892a-70defd893700.PNG)

I uploaded 2 logs and I hope can help to investigate to that problem
[Log1](https://pastebin.com/YpXgybyv)
[Log2](https://pastebin.com/RS4a12t0)

Hope can help, Jo

**Comment by markus101** [comment]
Looks like this is why it wasn't imported:

```
18-2-21 12:02:09.7|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] File quality does not match quality of the grabbed release
```

It looks like the other files were had `WEB-DLMux` and this one had `WEB.DLMux` and caused it to be parsed differently.

I'll get a fix for the parsing in, though it would cause them to sit in Sonarr's queue until they are manually handled due to the quite horrible release name.

**Comment by Jorman** [comment]
Tnx, I don't know if was fully fixed, I'll see, but today I had to "re-download" some episode because of the same.
![1](https://user-images.githubusercontent.com/5203988/36538481-fedbb180-17d3-11e8-97e8-ddc01c3af624.PNG)

Always happen after a manual import
![2](https://user-images.githubusercontent.com/5203988/36538500-0d99a542-17d4-11e8-88da-5f6f6d4a443f.PNG)

The funny is that only on certain episode, not all episode.

If you need I've to see if I've full logs for dexter, in this case.

Let me know

**Comment by Jorman** [comment]
Ok made a test, re-downloaded all 1st season, selected only one episode to test, the result is:

Episode parsed but all other files deleted and no files on the recycled bin, so not so good, but I don' know why

I don't know why the quality result different. but the release say BDRIP 1080p but Sonarr see a different quality, is possible?

Anyway I attach a full log, hope that can help
https://ufile.io/c86dg
[Logs.zip](https://github.com/Sonarr/Sonarr/files/1747932/Logs.zip)

**Comment by markus101** [comment]
> Tnx, I don't know if was fully fixed

A fix was pushed, but a new build hadn't come out.

> The funny is that only on certain episode, not all episode.

If it's anything like the last pack there wasn't consistency in the naming.

Please open a thread on the forums for any additional support or troubleshooting, the underlying issue has been fixed, but the terrible naming on your indexer persists.
