### ISSUE TITLE
Import extras/specials even if they couldn't be parsed

### ISSUE THREAD

**Issue by zecakeh** [Sonarr/Sonarr#2423]
## Feature Request
Import automatically all the content in folder named :

-     extras
-     specials
-     shorts
-     scenes
-     featurettes
-     behind the scenes
-     deleted scenes
-     interviews
-     trailers

(list found in [Emby's movie naming convention](https://github.com/MediaBrowser/Wiki/wiki/Movie%20naming#movie-extras))

Put it all in Specials folder, since extras aren't supported for TV shows. Ideally, the names of the videos would be cleaned. Also I'd like the option to rename the files to include the season number it relates to.

### What problem are you looking to solve?
Most of the time, when I download a season pack that was ripped from a blu-ray, there's an extras/featurettes folder with all the extra content like interviews, behind the scenes, bloopers, etc. However if it's not parsed correctly, and since content other than specials doesn't usually appear on the TVDb, only few of those are imported. I would prefer to have them all available in my media library and not have to manually import them all.

**Comment by markus101** [comment]
We do not have plans plans to import files that can not be parsed and connected to an known episode at this time. A custom script would be your best bet to handle this.
