### ISSUE TITLE
Make it possible the search for missing episodes on the wanted page

### ISSUE THREAD

**Issue by MrDemocracy** [Sonarr/Sonarr#2428]
## Feature Request
Please make it possible to search for missing episodes on the `http://localhost:8989/wanted/missing` page.
### What problem are you looking to solve?
It doesn't look like there is any good way to find a specific missing episode on the missing page. Could there be added a search box on the missing page?
### Other Information
Another thing: Why can't I click the status column, to sort the list by status?

**Comment by markus101** [comment]
If there is a specific episode you're looking for why not use the series details page? We do have some plans for additional filtering there, but searching, probably not.

> Another thing: Why can't I click the status column, to sort the list by status?

Except for the few that may be in queue, they're all missing so they have the same status, in addition status is calculated on the client, but the paging is all done on the server.

**Comment by MrDemocracy** [comment]
I want to manually import them. Can that be done from the series details page? It doesn't look like it can.
I have over 400 finished files failing to import/hard link. I want to filter between downloading, missing and finished. I would also like to be able to find a specific file, so that I can remap the file-location and manually import it. 

Talking about manual import...why is there only "copy" and "move", and not a "hard link" option?

**Comment by markus101** [comment]
You asked about wanted missing, not manual import. So you want to filter manual import? What does manual import have to do with it? It's completely unclear to me what you want to filter and how manual import comes into this at all.

> Talking about manual import...why is there only "copy" and "move", and not a "hard link" option?

Copy will hard link if enabled/possible.

**Comment by MrDemocracy** [comment]
On the `http://localhost:8989/wanted/missing`-page you can select episodes, and click manual import to remap the file location and import the episode manually. 

I want to be able to search for what episode I want to do this with.

> Copy will hard link if enabled/possible.

Okay, I didn't know. Great 👍

**Comment by markus101** [comment]
Filter for manual import is covered here: https://github.com/Sonarr/Sonarr/issues/1142
