### ISSUE TITLE
Infini-scroll instead of paging on wanted and activity lists

### ISSUE THREAD

**Issue by MrDemocracy** [Sonarr/Sonarr#2430]
## Feature Request
Make it possible to toggle between paging and infinite scroll on all the `wanted` and  `activity` lists, in Sonarr's UI-settings.

### What problem are you looking to solve?
This will make it much easier to find what you're looking for. 
### Other Information
It could start by loading 25 rows, and load 25 new rows as you scroll down and reach the bottom of the list. But I would still like if there where a toggle to load all rows immediately, in the UI-settings.

**Comment by markus101** [comment]
No plans for infini-scroll, but v3 will allow the page size to be changed to show more items.
