### ISSUE TITLE
qBittorrent does not cooperate with Sonarr

### ISSUE THREAD

**Issue by tonyrulez** [Sonarr/Sonarr#2432]
## Bug Report

Previously I was using μTorrent. With that, the episode got downloaded, and Sonarr moved the video file to it's final folder while removing all the other downloaded files and folder that μTorrent made. Now I'm trying out qBittorrent (latest, v4.0.4), and it does nothing like this. Sonarr starts the episode download in qBittorrent, but after that, all Sonarr says is "Episode missing from disk", even while qBittorrent is downloading it or finished downloading. Episode does not get moved to it's folder, downloaded folder containing nfo, sample etc. does not get deleted. All in all, it just downloads the episode and Sonarr doesn't have a clue what's happening.

### System Information/Logs

**Sonarr Version:**
2.0.0.5085
**Operating System:**
Windows 10

**.net Framework (Windows) Version:**
.NET Framework 4.7.1

**Comment by markus101** [comment]
Please use the forums for support. We'll need debug logs.

There are also change not yet in the latest build that may help if it's a matter if unlabeled torrents.
