### ISSUE TITLE
[Request] Multiple Secondary Cutoff Support

### ISSUE THREAD

**Issue by zero77** [Sonarr/Sonarr#2433]
Can you please add support for multiple secondary cutoff options.

For example, I am looking for 1080p webdl and I end up with lots of the same downloads, for shows with only 1080p hdtv or webrip and not webdl downloads.
Thanks

**Comment by halali** [comment]
This is already implemented in unreleased Sonarr V3

**Comment by markus101** [comment]
This will be in v3.

**Comment by zero77** [comment]
Where can I find a milestone, ETA or something similar for V3.

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/milestones?direction=asc&sort=due_date

**Comment by zero77** [comment]
thanks
