### ISSUE TITLE
Deleteing subtitles on multiepisode files

### ISSUE THREAD

**Issue by halali** [Sonarr/Sonarr#2437]
**Sonarr Version:**
3.0.0.111

**Operating System:**
Windows 10

**Link to Log Files (debug or trace):**
https://gist.github.com/halali/a7fc2b49672b6dad994366097ef1382d

### What problem are you looking to solve?
Sonarr in every series refresh delete all subtitles in multiepisede files

### Other Information
in log search for Marvels.Agents.of.S.H.I.E.L.D.S05E01-E02.720p.HDTV.x264-AVS.cze.srt

**Comment by markus101** [comment]
> 18-3-2 10:18:11.1|Debug|EpisodeService|Detaching episode 26847 from file.
18-3-2 10:18:11.1|Debug|EpisodeService|Detaching episode 28546 from file.

Looks like the existing file is being unlinked which causes the extra files for it to be removed. Is there a duplicate copy of the file for those episodes?

**Comment by halali** [comment]
no its not, doing it at every multiepisode file

**Comment by Taloth** [comment]
@markus101 fyi, this is a phantom release.

> "Removing episode file from DB as part of manual override of existing file, not creating history event."
Only on phantom.

> SameFileSpecification|More than one existing episode file, skipping.
How did that happen? Well, no .Distinct() on the query.

But the real question is: Why is it even scanning these files, they should already been filtered out at this point?!

**Comment by halali** [comment]
Also when renaming 1 episode at seasson  it rename all subtitles in all seasons in series from *.cze.srt to *.srt

**Comment by markus101** [comment]
> "Removing episode file from DB as part of manual override of existing file, not creating history event."

That should only happen if Manual Import was used from the series page (the ability to change which episodes the file contains without removing and re-importing). It shouldn't ever hit that during a refresh due to the filtering, but it looks like the filtering was ignored during that scan.

> SameFileSpecification|More than one existing episode file, skipping.

Ahh yes.

> Also when renaming 1 episode at seasson it rename all subtitles in all seasons in series from *.cze.srt to *.srt

Logs?

**Comment by halali** [comment]
https://gist.github.com/halali/57ad8cee431df740636df0e63a6b8110

**Comment by markus101** [comment]
This should be fixed in the next release.
