### ISSUE TITLE
Feature request: Episode plot as variable

### ISSUE THREAD

**Issue by euphoria360** [Sonarr/Sonarr#2441]
I am using a custom Telegram notification script to alert me when a new episode is grabbed or downloaded.

It would be great if I can put the episode summary in the message.

I didnt find any variable related to this in Sonarr variables.
It would be also possible for me to grab that summary and any other info i may need from tvdb api, but it seems the tvdb needs episode's absolute number.

and i cant calculate that from sonarr's variables.

Can anyone shed a light on this?

**Comment by markus101** [comment]
Customizing notifications is covered by https://github.com/Sonarr/Sonarr/issues/328
