### ISSUE TITLE
Sonarr does not find anime when name gets added in english

### ISSUE THREAD

**Issue by DavidVentura** [Sonarr/Sonarr#2442]
### System Information/Logs

**Sonarr Version:**     2.0.0.5153

**Operating System:** Debian Stretch

**.net Framework (Windows) or mono (macOS/Linux) Version:**     4.6.2

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):** --

### Additional Information

I'm using Sonarr with Jackett, this is my situation:

1. Add new series: "Dagashi Kashi", mark as Anime
3. The series gets added as "Dagashi Kashi"
4. Do a manual search for some episode
5. Find results

```
[Info] NzbSearchService: Searching 3 indexers for [Dagashi Kashi : 05] 
[Info] DownloadDecisionMaker: Processing 68 releases 
```
----

1. Add new series: "Yuru camp"
2. The series gets added as "Laid-back camp"
3. Do a manual search for some episode
4. Find no results

```
[Info] NzbSearchService: Searching 3 indexers for [Laid-Back Camp : 08] 
[Info] DownloadDecisionMaker: No results found 
````
----

PS: Obviously I find results when looking for the correct name (in this case 'yuru camp' directly in jackett)

**Comment by DavidVentura** [comment]
I'm (now) aware of the aliases. That doesn't seem like a great solution, why not allow us to set aliases when adding/editing a series? It could be hidden under 'advanced' if necessary.

proposed workflow

1. Add new series: "Yuru camp"
3. The series gets added as "Laid-back camp"
4. Do a manual search for some episode
5. Find no results
6. Add alias to "Laid-back camp" => "Yuru camp"
4. Do a manual search for some episode
5. Find results

**Comment by markus101** [comment]
Anime often requires more than just an alias if there are multiple seasons, hence them going on TheXEM.de. Having central aliases means it's added once and works for everyone, we plan to improve this process, but no plans for local only aliases.

**Comment by DavidVentura** [comment]
I thought about having a local per-season alias and an option to upload the alias you submit. 
You could then have the users submit aliases without leaving sonarr and give them an instant way to download what they want. If you prefer I can open a feature request

**Comment by markus101** [comment]
Yeah, that's the idea, not something that can be done until our other upstream services support adding requests for aliases. No need for another GHI at this time.
