### ISSUE TITLE
Calendar duplication of events

### ISSUE THREAD

**Issue by vinchi007** [Sonarr/Sonarr#2443]
This is new, for some reason some shows are duplicated in the event calendar

![image](https://user-images.githubusercontent.com/2197609/37014257-5fde31c2-20cd-11e8-972d-d20d05898eb1.png)

`18-3-5 23:30:34.5|Debug|Api|[GET] /api/calendar?start=2018-03-05T05%3A00%3A00.000Z&end=2018-03-12T04%3A00%3A00.000Z&unmonitored=false: 200.OK (89 ms)

18-3-5 23:30:43.4|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (46 ms)
`

Sonarr inside FreeNas JAIL (10.3)
```
 mono --version
Mono JIT compiler version 3.10.0 (tarball Thu Feb  4 00:22:52 PST 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

```

**Comment by markus101** [comment]
Not duplicates, there are just multiple episodes released on the same day at the same time.
