### ISSUE TITLE
Sonnarr Failed to copy 40GB for a Season before Auto Delete EP cmd

### ISSUE THREAD

**Issue by 91ajames** [Sonarr/Sonarr#2444]
Sonarr failed to copy 40GB for a season and I had previously Scheduled a CMD Script to Auto Delete my episodes from a Torrent Location.

Complete a torrent at least 2hrs before the Schedule Task ran the Script.
Roughly 200GB left of Space so it had enough space for Sonarr to copy the files over to the directory I gave Sonarr. All my other individual episodes copy just fine but one torrent over exceeding 40GB or more, won't.

### System Information/Logs

**Torrent Application: qBitorrent**

**Sonarr Ver. 2.0.0.5153**

**Operating System: Windows XP** (don't hate, i have my own exp with windows and manual fixes)

**.net Framework (Windows) Version: 4.0**

**Link to Log Files: [Link](https://www.dropbox.com/s/rj1yfmw1gnr0eaa/sonarr.txt?dl=0)**

### What problem are you looking to solve?

To copy 10GB+ to my location of my other sonarr shows without having any issues in order reason it did not.

## Support / Questions
https://forums.sonarr.tv/t/sonnarr-failed-to-copy-40gb-for-a-season-before-auto-delete-ep-cmd/17925

----------------------------------------------------------------------------------

__Other Info__ Auto Delete Episodes 'X' Many Days
Sry if this is a wrong no no but I would like to help people on there quest to have auto delete episodes with a cmd script. and those of asking me how, so im just gonna type it below.

How to auto delete episodes from local HDD for a certain 'X' mount of days. And auto quite your "Torrent Application" and to "Re-Open Torrent Application" to continue to download.

Do some test files like textnotes or copy episodes to test successfully.

I have a video but can't upload it yet due to my device not turning on, charger port needs to be cleaned and also out of battery power.

[Auto-Delete.bat file](https://www.dropbox.com/s/wr0b48onkdttpgf/Auto-Delete.bat.txt?dl=0) More info in the bat txt file

[Forfiles.exe is needed](http://www.dllfixis.com/forfiles.exe.html)

**Comment by markus101** [comment]
This is a support question and you've already opened a thread on the forums. Not sure why you doubled down and posted it here as well.

Your logs aren't debug logs, so the information is limited and doesn't extend beyond it failing due to the file already existing, previous logs may have more information, take a look.

**Comment by 91ajames** [comment]
wasn't sure where to post, my bad. which logs is it? bc it happen a few days ago and i saw this log created from March 1. the 2nd log file perhaps?

**Comment by markus101** [comment]
You'll have to find the log that showed the initial import failure (the one before all the warnings start to get logged), which log it is will depend on how much has been logged. Update the thread on the forums and we can troubleshoot more there.
