### ISSUE TITLE
Unable to manually import episode because of "Unknown Series"

### ISSUE THREAD

**Issue by MrDemocracy** [Sonarr/Sonarr#2447]
### System Information/Logs

**Sonarr Version:**
2.0.0.5153
**Operating System:**
Windows 10
**.net Framework (Windows) or mono (macOS/Linux) Version:**
.net Framework v4.7.02556
**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**

### Additional Information
Could you please make it so that manual import overrides the series check? I have checked that the episode is from the right series, but because of the filename being shortened ("The Series Name" is "TSN"), it wont let me import the episode.

**Comment by markus101** [comment]
Select the series in manual import (click the cell under the series column). You'll also need to select the season and episode.

**Comment by MrDemocracy** [comment]
Thank you!
Sorry for opening an issue about this. I didn't know you could specify series, season number or episode number in manual import.
