### ISSUE TITLE
V2.0.0.5153 on Server 2012 R2 incorrect MediaInfo.dll

### ISSUE THREAD

**Issue by mhouston100** [Sonarr/Sonarr#2448]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Sonarr Version:** 2.0.0.5153

**Operating System:** Windows Server 2012 R2

**.net Framework (Windows) or mono (macOS/Linux) Version:**

```
[v2.0.0.5153] System.DllNotFoundException: Unable to load DLL 'MediaInfo.dll': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)
   at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo.MediaInfo_New()
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:line 41

```

Just reporting an error in the 'develop' branch I encountered. Sonarr updated automatically to V2.0.0.5153 and for a few days I didn't notice but the service had crashed.

After trying some different things I noticed the error above in the logs when starting the EXE manually.

To resolve the issue I just came on GitHub and downloaded the latest MediaInfo.DLL (17.10) I beleive and overwrote the current version in the Sonarr folder. Once it was overwritten I was able to start the service with no further changes.

Not sure what happened as the files are the same size, version etc

Just through I would report it in case anyone else has the same issue!

**Comment by markus101** [comment]
`2.0.0.5153` is the latest master release.

Sounds like that DLL was corrupted somehow on your system as we haven't seen any other reports and we haven't upgraded that DLL since early December (https://github.com/Sonarr/Sonarr/commit/e070eeda4a6ff8243bb705a3261c125bc51b1666).

**Comment by mhouston100** [comment]
Yeah no sweat at all, no issues since manually replacing the file.
