### ISSUE TITLE
Missing root folder issue, can't browse all folders

### ISSUE THREAD

**Issue by abienz** [Sonarr/Sonarr#2452]
### System Information/Logs

**Sonarr Version:**
2.0.0.5153 - Feb 28 2018 
**Operating System:**
Synology DSM 6.1.5-15254 Update 1
**.net Framework (Windows) or mono (macOS/Linux) Version:**
Mono 5.8.0.108-11
**Link to Log Files (debug or trace):**
https://pastebin.com/zE6fzV6z

### Additional Information

I get the issue in System that I am 'Missing root folder /volume1/video/television

According to the wiki I have removed this location, and have to add it back in the series editor.

When I use the Series editor I cannot browse my folder structure, I can find volume1 and video, but video is empty with no subfolders.  When I check the file system through SSH I can confirm that all folders are actually still present.

**Comment by markus101** [comment]
Please use the forums for support.

Likely related to the DSM permission changes.
https://forums.sonarr.tv/t/new-sc-download-setup-cant-access-files-even-with-full-permissions/17855
