### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by smoothrunnings** [Sonarr/Sonarr#2453]
I love this product but it would be nice to see this feature added, if its possible. 

I have the profile set to 720p/1080p. It would be nice if Sonarr could allow me to choose which one I have a preference for if its available, so if 1080p is my preference but only 720p is available then 720p get downloaded and added. However if the 1080p comes out afterwards as some torrent uploaders don't upload the 720p first. Then Sonarr should download the 1080p and replace the 720p one. 

Let me know if this is something you can tackle? 

Thanks!

**Comment by markus101** [comment]
That is already supported through the profile system.

https://github.com/Sonarr/Sonarr/wiki/Profiles

**Comment by Taloth** [comment]
@markus101 Lemme explain how the real corporate professionals do it:

"Absolutely, we can implement that feature for you. We estimate that such a feature would cost 40 man hours to implement, for a total of $2800."
