### ISSUE TITLE
Pokemon info not correct.

### ISSUE THREAD

**Issue by smoothrunnings** [Sonarr/Sonarr#2455]
## Bug Report

**Sonarr Version: 2.0.0.5153

**Operating System: Windows Server 2012 R2

### What problem are you looking to solve?

Pokemon is showing that some of the titles in S18 are actually S20 and I have even found others from S17 are S19. Not sure how Sonarr is getting it's catalog info but it looks like its not correct. Doing a simple GOOGLE search confirms this.

**Comment by Taloth** [comment]
Please note that this isn't a bug report, it's a support question and should go on the forums.

Sonarr gets it's information from TheTVDB. And what you're dealing with is a scene vs TheTVDB mapping issues. Which, for Pokemon, is rather nasty considering that Pokemon has both original Japanese releases and American reruns.
Sonarr uses TheXEM for mapping scene numbers, although not everything can be mapped. For example: If two release groups number releases differently then how the heck is Sonarr supposed to know which is which.

Here's the mapping http://thexem.de/xem/show/4042

If you have further questions, please post on the forums instead.
