### ISSUE TITLE
Bug in Sonarr updating video tags. 

### ISSUE THREAD

**Issue by smoothrunnings** [Sonarr/Sonarr#2456]
### System Information/Logs

**Sonarr Version: 2.0.0.5153

**Operating System: Windows Sever 2012 R2

### What problem are you looking to solve?

After downloading x265 HEVC 1080p DD 5.1 video and uploading to my Plex, when I get Sonarr to update the show in question, it shows the videos are HDTV 720p even though I have HDTV 1080p as the cut off in my video profile. Attaching image of my video profile. Technically the videos should show up as one of the 1080p's if Sonarr doesn't think its a HDTV 1080p which they don't.

![image](https://user-images.githubusercontent.com/6445945/37258909-7ac24366-2555-11e8-9bf8-a7429709977f.png)

**Comment by markus101** [comment]
Please use the forums for support.

Sounds like the file names don't contain the proper quality, so Sonarr defaulted to HDTV 720p, though that's just a given there aren't any debug logs of the import.
