### ISSUE TITLE
DownloadedEpisodesImportServic

### ISSUE THREAD

**Issue by rocksolid2018** [Sonarr/Sonarr#2457]
After the recent update of Sonarr on synology 2.0.0.5085 to version 2.0.0.5153. All downloaded episodes are failing imports from the download folder to the video folder. I have crossed checked all permissions as suggested by other users. but nothing seems to work. I have also noticed similar issue on Radarr after its recent update on Synology platform. Mono updated to latest. 

Am i missing something.

**Comment by markus101** [comment]
Please use the forums for support. This has already been covered there: https://forums.sonarr.tv/t/new-sc-download-setup-cant-access-files-even-with-full-permissions/17855/32
