### ISSUE TITLE
Highlight season finale similar to season premiere

### ISSUE THREAD

**Issue by brimur** [Sonarr/Sonarr#2461]
Hopefully this is a small change. In the calendar a season premier is highlighted in light blue. Could you also highlight the season finale in a different color, maybe dark blue or blue-purple to stick with the blue theme?

**Comment by brimur** [comment]
Understood. Thanks, feel free to close this so if you want.

**Comment by matmuilwijk** [comment]
Well, my experience is that data is always available up to either a season finale, or a mid-season break. So, this should be reliable enough, right?

All data used by Sonarr is community-driven, so reliability is always kind of an 'issue'.

**Comment by markus101** [comment]
This is done in the v3 work.
