### ISSUE TITLE
Add a file size cap to quality settings

### ISSUE THREAD

**Issue by puzl** [Sonarr/Sonarr#2465]
## Feature Request
Please add a file size cap to quality settings.

### What problem are you looking to solve?
I use cloud storage with a hard file limit of 15GB per file.
I can tweak my quality settings to give me a pretty good chance of ensuring that all files are under this limit but at the cost of quality on a normal length movie.

For example, if I set the limit of a 1080p bluray 140 minute movie to 15GB then all movies up to 140 minutes will copy to the cloud properly.  However, if movies longer than 140 minutes will not.

So now I can tweak my quality settings to, say, 10GB for a 140 minute movie and sure enough all movies up to ~210 minutes will copy up properly.  210 minutes should about cover everything, or enough of everything that manual intervention isn't a big deal.

However, this tweak has caused almost all of my normal movies to be limited to 10GB/140m which is obviously sub optimal.

Now, if there was a global setting "Maximum file size:"  I could set this to 15GB and then set my quality to what I want.    radarr could then start dropping down through the matching releases until it finds the first one that is under 15GB that satisfies the specific quality setting.

**Comment by Thirrian** [comment]
> Now, if there was a global setting "Maximum file size:" I could set this to 15GB and then set my quality to what I want.

There is: https://github.com/Sonarr/Sonarr/pull/2367

I think you meant to request this for Radarr? This is the Sonarr github :smile:

**Comment by puzl** [comment]
ooops... how embarassing
thanks for the reply.
