### ISSUE TITLE
Feature Request: Auto Update

### ISSUE THREAD

**Issue by xDeathwing** [Sonarr/Sonarr#2466]
## Feature Request

I think an auto updater for Sonarr would benefit it greatly, I forget to update my Sonarr constantly, having an optional setting on the "General" section right under "Open browser on start" called "Auto Update on start" might be useful, it would check for updates on every server restart. This can be improved with checking every X hour and installing if Sonarr is idle at that time.

### What problem are you looking to solve?

Updates bring a lot of bugfixes, but I usually forget to do it.

**Comment by markus101** [comment]
Sonarr has had auto ipdating since the beginning. On Windows it's always on, on other platforms it's disabled by default.

**Comment by xDeathwing** [comment]
I am on Linux, considering I only have access to the web dashboard, how can I enable it? It would be super useful.

**Comment by markus101** [comment]
Make sure advanced settings are shown, then they'll be there in general settings.
