### ISSUE TITLE
Seperate Series Type for Searching and Naming

### ISSUE THREAD

**Issue by aeonsablaze** [Sonarr/Sonarr#2467]
## Feature Request
I would like to be able to select Series Type (i.e. Standard or Daily) independently for searching and naming. For example, you could have a series that searched by Date, but saves using the Standard naming scheme.

### What problem are you looking to solve?
Plex can sometimes get confused with date based episode naming in shows where there are multiple episodes on the same date (particularly with specials that coincide with normal episodes as it tends to go with the lowest numbered season). Unfortunately, some of these shows are also searchable exclusively by date. Allowing these to be selected separately would solve this conundrum.

I came up with a few scenarios for the opposite (SxxExx searching, Date-based naming), but frankly none of them sounded all that plausible...

### Other Information
Yes, I am aware that I could change the Daily episode format under Settings > Media Management however this would change it for all such shows which I would rather avoid. Ideally  I would like to be able to select this on a show by show basis.
Alternatively: perhaps just the ability to define a custom naming format per-show? Not having really dug into Sonarrs code I'm not sure which would be easier to implement.

**Comment by markus101** [comment]
At this time there are no plans to change how Sonarr decides which format is used when naming and it'll be based on the series type.
