### ISSUE TITLE
Improvement for season episode matching

### ISSUE THREAD

**Issue by devbrian** [Sonarr/Sonarr#2470]
When attempting to import a season pack, sonarr does a very poor job "forcing" matches.  

It cannot recognize an episode structure of just "episode number - episode name" which is common on many pack trackers.

    /Series Title - Season 01
        -> 1 - Episode1Name.mkv
        -> 2 - Episode2Name.mkv 
        ....

This causes import to fail.  It would be very nice if sonarr could properly process this, several pack trackers I use follow this format and I have 300 season packs I need to manually process, I would prefer not to do that.

**Comment by Taloth** [comment]
Sonarr can't parse every format, it would make it far less reliable, ironically. The SxxExx format is nice coz it's very recognizable. We already have trouble keeping certain anime formats apart.
We do have a github issue to improve the parser with heuristics. And iirc we do support the itunes format, which is fairly similar. But the format you posted is pretty crappy (also doesn't contain source and quality tags).

Anyway, for you It might be easier to use a script (powershell script or anything) to rename the files before having Sonarr import them. Simply rename it to 1x01 - Episodename should already do it.

There's another issue for the advanced parser, so I'm going to close this.

**Comment by devbrian** [comment]
@Taloth Thanks, mind linking me to the other issue? Also, is it possible through sonarr to setup a script to run after download but before import?
