### ISSUE TITLE
Add Support for PushSafer Connections / Notifications

### ISSUE THREAD

**Issue by Veldkornet** [Sonarr/Sonarr#2471]
### What problem are you looking to solve?
Receive notifications via PushSafer, as you would with PushBullet or PushOver, when something is downloaded, snatched, upgraded, etc. 

### Other Information
PushSafer is very similar to PushOver with a few small differences

API: https://www.pushsafer.com/en/pushapi

**Comment by BoKKeR** [comment]
I will give this a try.

**Comment by BoKKeR** [comment]
There is an option to set a custom picture for the notification in the POST request. Should this be a textbox field in the settings? Or should I just add a picture of sonarr by default and if so, where should I link it from?  Or should this be ignored? @markus101

**Comment by Veldkornet** [comment]
Unless I’m mistaken, I don’t think that the picture is for the icon, I think it’s to literally send a picture as part of the notification. 
So I would say that you should ignore it.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
