### ISSUE TITLE
Feature Request: MediaInfo for episode files

### ISSUE THREAD

**Issue by kaysond** [Sonarr/Sonarr#2473]
It would be nice if there was an easy way to get mediainfo for the files straight from the web ui. Obviously I can just use the path to find the file and run mediainfo on it, but it would save a few steps and is convenient when I want to be extra-choosy about the particular release, for example, audio channels.

**Comment by markus101** [comment]
This will be added in v3.

**Comment by kaysond** [comment]
Awesome. Thank you!
