### ISSUE TITLE
Failed Download Notifications

### ISSUE THREAD

**Issue by samip5** [Sonarr/Sonarr#2474]
### What problem are you looking to solve?
No notification if download has failed or it has been manually marked as failed

### Other Information
I'll be referensing this from a PR.

**Comment by bakerboy448** [comment]
this likely won't happen.

you get a grab
you don't get an import

conclude that the download failed

**Comment by samip5** [comment]
It's not that simple, as the point was a way to programmically know if it failed aka not enough peers for example.

**Comment by markus101** [comment]
What’s be the goal there? If Sonarr recognized those downloads failed wouldn’t it just mark as failed and move on?

**Comment by samip5** [comment]
Send a message that it failed, so I could check or try another one manually if it's not done automatically.
