### ISSUE TITLE
Add connection for Matrix homeservers

### ISSUE THREAD

**Issue by Cerothen** [Sonarr/Sonarr#2476]
## Feature Request
 I would like to request that support be added for Matrix.org home servers in the connections area to provide notifications to a user though a room on their matrix home server. Ideally this would use a matrix user that is pre-created by the user and it would either start a direct chat with a specified user (or perhaps list of users?) OR it would send the messages to a room that is specified by its ID (#<roomname>:<domain>.<tld>).

Options:
**Homeserver:** `<any fqdn>` (default to global server `matrix.org`)
**Username:** `@<user>:<domain>.<tld>`
**Password:** `<password for the user>`
**Notify Users:** `@<user>:<domain>.<tld>` (For multiple separate with spaces | direct chat notifications | **This one could even be skipped if just the rooms one is done below.)
**Notify Rooms:** `#<room name>:<domain>.<tld>` (For multiple separate with spaces | Room name of an existing room)
Any other things that would typically be in a connection (Tag Filter, On Grab, On Download, etc.)

### What problem are you looking to solve?
 Adding a connection for this growing self hosted federated communication platform would be a good way to enable users to have self hosted push notifications and keep everything together. By posting the notifications to rooms updates could be spread among many users by having those users join those rooms (since the platform is federated any user from any server could join the room if public or users could be invited).

### Other Information
https://matrix.org/docs/api/client-server/

I don't know exactly how it works for things like this moving over to the other projects as well (radarr/lidarr) but ideally it would also be implemented there also.

**Comment by skoal** [comment]
Hi

setup a webhook appservice [ https://github.com/turt2live/matrix-appservice-webhooks ]
So you can use the webhook connect plugin.Also you don't have to setup a user for every bot on your HS this way

**Comment by Cerothen** [comment]
That isn't really an integrated solution, and would mean you need to have access to the actual home server to setup, in my case I have some people on my home server, some with their own home server and some on the global vector server but they all use Sonarr, that would mean the homeserver would have to have each appservice added to the home server and an extra program (node server) running for each.

Sure it might work, but it isn't practical at scale.

**Comment by skoal** [comment]
Your other option would be to register a user (for the bot) on a given HS,login with the user,get the access token,join the channel where you want to send the messages,get the internal id of the channel,and from a script construct a http POST to send the message.
[like so...](https://gist.github.com/RickCogley/69f430d4418ae5498e8febab44d241c9)

**Comment by Cerothen** [comment]
Sorry what I meant by at scale, is that for a typical user creating custom scripts etc isn't entirely practical. To ensure a low barrier of entry it would be nice to just have it so you create enter a username and password of an existing user, Sonarr then gets a token from that login and sends updates to the rooms/users specified as that user.

I don't have a proper appreciation for the complexity of that request, but if there was a template or something somewhere for creating connections I would try my hand at submitting a pull request.

**Comment by FunkenTom** [comment]
Isn't the webhook API compatible to the one of slack?
So you should be able to use the slack connection and just add the matrix details.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
