### ISSUE TITLE
Feature Request: Opt. to allow Minimum Seeders to only apply to RSS Sync or... 

### ISSUE THREAD

**Issue by Napsterbater** [Sonarr/Sonarr#2479]
## Feature Request

Option to allow Minimum Seeders to only apply to RSS Sync and not an automatic search and/or, be ignored if no other viable item is found during an automatic search.

### What problem are you looking to solve?

Allow minimum seeders to prevent weakly seeded torrents from being download while still "fresh" so NZB/Other methods can be used. But when adding older items and triggering automatic searches allow the Minimum Seeders option to be ignored completely or be ignored if no other viable alternatives were found (i.e. rather have it slow then not at all)

**Comment by Taloth** [comment]
Sonarr already prioritizes by the most seeds (divided in a couple of 'buckets'). So you should set your minimum seeders at the absolute minimum that you accept.
Additionally, having a modest delay profile would allow the Rss Sync process to collect a couple of candidates and pick the best one.
