### ISSUE TITLE
[Feature Request] Search for {Localized shows title} and add {Localized shows } as a Rename option

### ISSUE THREAD

**Issue by R91g** [Sonarr/Sonarr#2480]
Hi,

First thank to all contributors for her great job.
I'm a Spanish user and use Spanish Privates trackers but this problem exists for all non english users.

In this trackers the name of Shows are localized to spanish name. For example:
"Once upon a time" in Spain is "Érase una vez".
So if we search "Once upon a time" we don't found anything.

I think that we can use the language setting in profile to do this search.
In thetvdb we can use **lid** to indicate the language.

**Once upon a time Tvdb page (English)**:
https://www.thetvdb.com/?tab=series&id=248835
**Once upon a time Tvdb page (Spanish):**
https://www.thetvdb.com/?tab=series&id=248835&id=16

Radarr already implements it and search movies with localized named.
In Jackett, Spanish trackers is implement too and fixed the nomenclature format (Spanish uses 01x01 instead of S01E01):
https://github.com/Jackett/Jackett/issues/1468
I did somes fixed.

If Sonarr implements this feature then in Sonarr information about sinopsis and episodes name will be in our native language and then sonarr can rename it correctly.
If any information isn't in our language Sonarr get English version

**Comment by markus101** [comment]
This will be possible once TVDB data is available in other languages. https://github.com/Sonarr/Sonarr/issues/269

**Comment by R91g** [comment]
Sorry, I didn't knew that this is not posible yet.

**Comment by Diablobait** [comment]
radarr and sickrage do it why sonarr cant? 
Spanish ppl cant use it because only search on english name and dont find results
https://www.thetvdb.com/?tab=series&id=295829&lid=7
English
https://www.thetvdb.com/?tab=series&id=295829&lid=16
Spanish

They just put the lid of the language you want, spanish for example is always lid 16 and other languages has a fixed number
