### ISSUE TITLE
Searches to NZBHydra2 return incomplete results

### ISSUE THREAD

**Issue by biship** [Sonarr/Sonarr#2482]
**Sonarr Version:**  2.0.0.5163
**Operating System:** Win 10 x64 (latest insider build)
**Link to Log Files (debug or trace):**
### What problem are you looking to solve?
Correct search results
### Other Information
When manually searching for "60 Days In - 0x13 - Season 4: Where Are They Now?", NZBHyrda2 returns 1 results. Query sent was:
`18-3-29 07:13:56.8|Debug|Newznab|Downloading Feed http://htpc:5099/api?t=search&cat=5000,5020,5030,5040,5045,5050,5060,5070,5080&extended=1&apikey=(removed)&offset=0&limit=100&q=60+Days+In+Season+4+Where+Are+They+Now
18-3-29 07:14:00.8|Debug|NzbSearchService|Total of 1 reports were found for [60 Days In] Specials from 1 indexers`
When manually searching "60 Days In Season 4 Where Are They Now" in NZBHydra2 I also get the same single result. 
However, manually searching "60 Days In S04E00" in NZBHydra2 I get different 6 results (actually 18 different urls over 7 indixers). All are valid. 
Why isn't Sonarr using the episode id (S04E00)?

**Comment by biship** [comment]
NZBHyrda2 Results:
`

Title | Indexer | Category | Size | Details | Age | Links
-- | -- | -- | -- | -- | -- | --
60.Days.In.S04E00.Where.Are.They.Now.1080p.Amazon.WEB-DL.DD+.2.0.x264-TrollHD | DogNZB | TV HD | 3.28 GB | 1 | 2d |  
60.Days.In.S04E00.Where.Are.They.Now.1080p.Amazon.WEB-DL.DD2.0.x264-TrollHD | Drunken Slug | TV HD | 3.16 GB | 0 | 2d |  
60.Days.In.S04E00.Six.Months.Later.Where.Are.They.Now.720p.HDTV.x264-W4F | omgwtfnzbs | TV HD | 1.04 GB | 5 | 1d |  
60.Days.In.S04E00.season.3.where.are.they.now.720p.HDTV.x264-w4f | DogNZB | TV HD | 968.8 MB | 7 | 1d |  
60.Days.In.S04E00.Six.Months.Later.Where.Are.They.Now.HDTV.x264-W4F | omgwtfnzbs | TV SD | 313.46 MB | 3 | 1d | Send to Newsbin
60.Days.In.S04E00.Season.3.Where.Are.They.Now.HDTV.x264-W4F | omgwtfnzbs | TV SD | 285.99 MB | 4 | 1d |  

`

Sonarr Results:
`

Source | Age | Title | Indexer | Size | Peers | Quality |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
nzb | 12.8 hours | 60.Days.In.S04E00.Season.3.Where.Are.They.Now.720p.HDTV.x264-W4F | NZBHydra2 | 933.1 MB |   | HDTV-720p |   |  

`

**Comment by biship** [comment]
and now (about 30 mins later) they all show up in Sonarr:

`

Source | Age | Title | Indexer | Size | Peers | Quality |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
nzb | 13.3 hours | 60.Days.In.S04E00.Season.3.Where.Are.They.Now.720p.HDTV.x264-W4F | NZBHydra2 | 933.1 MB |   | HDTV-720p |   |  
nzb | 13.3 hours | 60.Days.In.S04E00.Season.3.Where.Are.They.Now.720p.HDTV.x264-W4F | NZBHydra2 | 963.2 MB |   | HDTV-720p |   |  
nzb | 38.8 hours | 60.Days.In.S04E00.season.3.where.are.they.now.720p.HDTV.x264-w4f | NZBHydra2 | 968.8 MB |   | HDTV-720p |   |  
nzb | 39.1 hours | 60.Days.In.S04E00.Season.3.Where.Are.They.Now.720p.HDTV.x264-W4F | NZBHydra2 | 932.6 MB |   | HDTV-720p |   |  
nzb | 39.3 hours | 60.Days.In.S04E00.Season.3.Where.Are.They.Now.720p.HDTV.x264-W4F | NZBHydra2 | 962.3 MB |   | HDTV-720p |   |  
nzb | 38.9 hours | 60.Days.In.S04E00.Season.3.Where.Are.They.Now.HDTV.x264-W4F | NZBHydra2 | 277.0 MB |   | SDTV |   |  
nzb | 39.3 hours | 60.Days.In.S04E00.Season.3.Where.Are.They.Now.HDTV.x264-W4F | NZBHydra2 | 286.0 MB |   | SDTV |   |  

`

`
8-3-29 08:19:57.5|Info|NzbSearchService|Searching 1 indexers for [60 Days In] Specials
18-3-29 08:19:57.5|Debug|Newznab|Downloading Feed http://htpc:5099/api?t=search&cat=5000,5020,5030,5040,5045,5050,5060,5070,5080&extended=1&apikey=(removed)&offset=0&limit=100&q=60+Days+In+Season+3+Where+Are+They+Now
18-3-29 08:20:04.9|Debug|FetchAndParseRssService|Found 100 from Newznab
18-3-29 08:20:04.9|Debug|FetchAndParseRssService|Found 100 reports
18-3-29 08:20:04.9|Info|DownloadDecisionMaker|Processing 101 releases
`

Confused. Attaching log.
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/1860042/sonarr.debug.txt)

8088 = qbittorrent
5099 = NZBHydraq2
8989 = Sonarr
All on the same host 'htpc'

**Comment by Taloth** [comment]
> Please use https://forums.sonarr.tv/ for support or other questions.

`S04E00` means 'any special in Season 4', so it's ambiguous and scene often also releases specials using `S04.Special`. That's why Sonarr searches for the episode title.   
Either way, with specials it's always going to be hit-and-miss.
