### ISSUE TITLE
finding shows with the right subtitles

### ISSUE THREAD

**Issue by MikunGit** [Sonarr/Sonarr#2484]
Hello..

When using danishbits who have most of the content with danish subtitles and nordic ( which includes subtitles for all countries in scandinavia).. It can only find the shows with danish subtitles if DkSubs is included in the filename, but it can't find it when Nordic is included, and most of the content is Nordic, so can maybe both be a part of when searching for shows with danish subs?

**Comment by markus101** [comment]
You could add DkSubs as a required word, but Sonarr won't change how searches are performed.
