### ISSUE TITLE
TvdbId filter for series

### ISSUE THREAD

**Issue by d8ahazard** [Sonarr/Sonarr#2486]
As the request says...it would be really, really, *really* great if I didn't have to make multiple requests to Sonarr in order to fetch information about a specific show.

I write an app that allows integration with multiple "fetcher" applications. When a user requests to dl new media, I go out and scrape TMDB and TVMaze, both of which spit out the tvdbId of a series.

I then take this data, and ideally, use it to look in Sonarr and see if the user already has the show added, and specifically, if they already have a specific episode set as wanted, snatched, etc.

Unfortunately, as Sonarr requires using internal ID to reference all series, this means I can't add sonarr URL in a multi-curl and just pull in episode data, I first need to query sonarr for list of episodes and internal ID's, then associate that with show title, tmdbId, etc, then go fetch episode status.

So, I realize it'd probably be a little bit of work, but if you could perhaps just make the episodes and show endpoints accept tvdbId= as a param instead of id=...that would be infinitely helpful!

**Comment by Taloth** [comment]
A REST api is based on internal ids, if you want the episodes for a particular show then you'll have to query the series api first. (If we provided tvdbid filter options to the episodes endpoint then we'd have to do those multiple queries ourselves)
You're going to have to use multiple queries.

PS: It sounds like you're creating your own Ombi.

**Comment by Taloth** [comment]
A REST api is based on internal ids, if you want the episodes for a particular show then you'll have to query the series api first. (If we provided tvdbid filter options to the episodes endpoint then we'd have to do those multiple queries ourselves)
You're going to have to use multiple queries.

PS: It sounds like you're creating your own Ombi.

**Comment by d8ahazard** [comment]
*Sniffle*

But I can't do a clean async fetch if I have to wait for data from query 1
before performing query 2, and Google only gives me 6 seconds in which to
perform queries and formulate a text response...

On that note - kinda like Ombi, but not really?

https://github.com/d8ahazard/Phlex

My app does what Ombi does, but also for music, and only via voice. ;)

**Comment by markus101** [comment]
This will be in v3 via `/api/v3/series?tvdbid=12345` which will return an array with either 0 or 1 series (depending whether a matching series is found).
