### ISSUE TITLE
Can't Find Chef's Table in Sonarr Search (text or TVDB)

### ISSUE THREAD

**Issue by jeff15110168** [Sonarr/Sonarr#2487]
**Sonarr Version:**
2.0.0.5163

**Operating System:**
Win 10 x64

### What problem are you looking to solve?
Sonarr can't seem to find this specific TV show even though it exists on tvdb (link: https://www.thetvdb.com/?tab=series&id=268972). I've used multiple iterations of the name (chef vs chefs vs chef's, searched just for first word, or just for "table" etc.) and tried the tvdb:268972 search term.

Nothing seems to be working. Anyone know how I can add this to my tv shows?

**Comment by markus101** [comment]
Please use the forums for support.

Should be able to add this series now, some bad data was cached preventing Sonarr from looking it up properly.
