### ISSUE TITLE
Sonarr can't download from automatic or manual but is abble to find .torrent file and peer

### ISSUE THREAD

**Issue by guiboubou23** [Sonarr/Sonarr#2488]
Hi everybody I first want to say sory for my bad english (I'm french) but I need some help with sonarr for automatic download.

My config : 
NAS synology DS414j
OS : DSM 6.1.6-15266
Sonarr Ver. 2.0.0.5163
Mono Ver. 5.8.0.108-11

I use Jackett to find torrent files trom french public trackers (3 trackers have the logo Ok while running test)

My sonarr is abble to find torrent files so ie guess my jackett is well configured but when I try do download in automatic it doesnt work.

When I go in Activity I see some episodes I want to download but there is no progression bar. On the left on every single line there is a yellow Hardrive. See the picture bellow

![sans titre](https://user-images.githubusercontent.com/38082593/38327540-c2d56e48-3848-11e8-9544-3117a6f56c96.png)

I also can't download in manual

![sans titre2](https://user-images.githubusercontent.com/38082593/38327534-bb0abd58-3848-11e8-8fc8-6b3cbff4b6a2.png)

For sonarr log :

Automatic : 

![capture4](https://user-images.githubusercontent.com/38082593/38327520-b532d64a-3848-11e8-9c88-86d653b98eae.PNG)

Manual : 

![capture3](https://user-images.githubusercontent.com/38082593/38327509-aad560f0-3848-11e8-8620-a869f3eb6cee.PNG)

I've search to change some settings in download clients my settings may be bad but with other settings I have no torrent files in Activity pannel.

![capture5](https://user-images.githubusercontent.com/38082593/38327494-a1ba2f0a-3848-11e8-9a1b-5c2d4f014e8b.PNG)

Thanks for the ones can help me.

**Comment by markus101** [comment]
Please open a thread on the forums for support, but Jackett is reporting an error that the torrent can't be grabbed, might be a problem with that indexer in Jackett.

**Comment by guiboubou23** [comment]
Sory for my mistake tanks ^^
If someone can delete :s
