### ISSUE TITLE
Option to disable - The option to disable: File quality does not match quality of the grabbed release

### ISSUE THREAD

**Issue by Zedjaw** [Sonarr/Sonarr#2489]
We should be able to trigger the option for Sonarr to ignore file quality checking or the such
Refer to https://forums.sonarr.tv/t/the-option-to-disable-file-quality-does-not-match-quality-of-the-grabbed-release-for-sites-like-animetorrents-jackett/18236  for more info and screenshots

It would be amazing for this to be added as it will make Sonarr much more flexible on what it does.

Thank you in advanced

**Comment by markus101** [comment]
Improvements to the import process, such as https://github.com/Sonarr/Sonarr/pull/2146 will allow us to remove this restriction. No plans to have an option until that work is done though.

**Comment by Zedjaw** [comment]
Hey mark is there any ETA?

**Comment by Taloth** [comment]
As a rule we don't do ETAs. But if you want one: 6-8 weeks.

**Comment by jj-uk** [comment]
Yes!! Almost every episode that is downloaded now results in the dreaded "File quality does not match quality of the grabbed release" error and I have to manually import the episodes, one by one.

**Comment by Zedjaw** [comment]
Yep I agree. A simple auto override so we don’t have to do this manually is
needed. It’s been a very long time since there was an update/fix in regards
to this

**Comment by ffuubarbuzz** [comment]
Since  #2146 is merged, is it possible to reopen this issue?

**Comment by spike229** [comment]
I'm having this issue as well, any word on this feature?

**Comment by jonny992** [comment]
Its hapen to my to in about 80% of all downloads. I have to manually do the work. Some way to solve that?

**Comment by DarkYamik** [comment]
Any more information about this issue? It¡s happening on almost all the downloads

**Comment by rdelmotte** [comment]
This thing is annoying to me as well. I am missing on new releases sometimes because I don't check on that queue that require manual imports often.

**Comment by hadim** [comment]
I am also having this issue.

**Comment by StableNarwhal** [comment]
Same here. Would be a great addition.

**Comment by TimMods** [comment]
Like most of you, i think we're all have this issue. Full automation is gone :(
This issue is known for almost 2.5 years and "WebRips" are becoming a standard. No content is imported automatically anymore. This should be seen as a core issue for the user experience.

**Comment by bakerboy448** [comment]
@TimMods; @StableNarwhal  please don't comment on a closed issue;  if it is still an issue then open a new one and fill out the template properly

**Comment by markus101** [comment]
Or in this case don't because it's been removed in v3 for a while now.
