### ISSUE TITLE
Join API error

### ISSUE THREAD

**Issue by Bruny07** [Sonarr/Sonarr#2490]
### System Information/Logs

**Sonarr Version:** 2.0.0.5163

**Operating System:** Ubuntu 17.10

**.net Framework (Windows) or mono (macOS/Linux) Version:** 4.6.2

**Link to Log Files (debug or trace):** [Trace logs](https://www.paste.org/92352)

### Additional Information
Since a few weeks join module started throwing "Error: SecureChannelFailure (The authentication or decryption has failed.)"

**Comment by markus101** [comment]
You'll need to upgrade to mono 5.0+ it properly supports secure connections. Join may have recently started enforcing secure connections, though that's just a guess.
