### ISSUE TITLE
[FEATURE REQUEST] Option to set a specific indexer for a specific tv series, and specific custom ratio as well

### ISSUE THREAD

**Issue by Meiden-fc** [Sonarr/Sonarr#2491]
## Feature Request

It would be very useful to be able to choose a specific indexer for a certain show. It would have a lot of sense for that kind of people who have mixed public and private trackers in their sources.

For example, I would like to find a certain show, from a specific private tracker and then set a custom seed ratio for it.

Related to: https://github.com/Sonarr/Sonarr/pull/2272

**Comment by markus101** [comment]
Specific indexer for Series would be via tags: https://github.com/Sonarr/Sonarr/issues/487
Seed time/ratio: https://github.com/Sonarr/Sonarr/issues/1854

**Comment by Meiden-fc** [comment]
And can you tell me how to do it? There's no information at all neither in that links nor in the documentation. I've set a few indexers' names in the tag gap but it isn't working, the search is made in all the indexers that I have available in my settings.

**Comment by Meiden-fc** [comment]
Oh well. Ok then. Thank you very much for your support, and I'll wait until the feature will be definitely implemented :)

Thank you very much for your great work. Thanks!
