### ISSUE TITLE
Disconnect between Sonarr and Jackett (the indexer)

### ISSUE THREAD

**Issue by smoothrunnings** [Sonarr/Sonarr#2492]
**Sonarr Version: 2.0.0.5163

**Operating System: Windows Server 2012 R2

**.net Framework (Windows) or mono (macOS/Linux) Version: 4.6.x

### What problem are you looking to solve?

There seems to be a disconnect between Sonarr and the latest Jackett. From Jackett I can find the tv shows that still have not downloaded, confirmed it on my torrent site. In site Sonarr I can run successful tests against my indexer but I scan for these TV shows Sonarr comes up empty forcing me to have to manually download them and install them onto Plex. A big time waster. 

This isn't a new installation, its been working for awhile without any issues until now. When I first set this up along side Jackett I as updating missing shows without any issues.

**Comment by markus101** [comment]
Please use the forums for support.

It's not really clear what you mean by scan, it sounds like you mean search, but I'm not sure. If that's the case, check the debug logs to see what Sonarr got back from Jackett for the search.
