### ISSUE TITLE
JSON RPC changes on kodi 18

### ISSUE THREAD

**Issue by Saner2oo2** [Sonarr/Sonarr#2493]
Hi, I'm having issues on my box with Kodi notations.

I am guessing it relates to this

https://forum.kodi.tv/showthread.php?tid=324598

` 

NzbDroneErrorPipeline | Invalid request Validation failed:   -- Unable to send test message | 1:33pm
-- | -- | --
  | XbmcService | Unable to send test message: The remote server returned an error: (404) Not Found. | 1:33pm
  | HttpProvider | Failed to get response from: http://192.168.1.54:8080/xbmcCmds/xbmcHttp?command=ExecBuiltIn(Notification(Test Notification,Success! XBMC has been successfully configured!,5000,https://raw.github.com/Sonarr/Sonarr/develop/Logo/64.png)) The remote server returned an error: (404) Not Found. | 1:33pm

     `

I get a 404 with various other commands.

Version
2.0.0.5163
Mono Version
5.10.0.160

**Comment by markus101** [comment]
Please post the debug logs files and link them here (as asked when opening this issue). The logs here look to be the fall back to supoort older versions of XBMC, pre-Kodi, which has long been removed.

**Comment by thezoggy** [comment]
is kodi really running on 192.168.1.54 and you have webserver bonded to 8080?

**Comment by markus101** [comment]
Closing this out.
