### ISSUE TITLE
Support new downloader goTorrent

### ISSUE THREAD

**Issue by deranjer** [Sonarr/Sonarr#2494]
Hi,

I am the author of goTorrent, a remote torrent client with a JSON over websocket API.  I would love for goTorrent to be added as a downloader to Sonarr.

While still in pre-release, the API should be essentially frozen and contain all the necessary endpoints for full Sonarr support.

Here is the project page: https://github.com/deranjer/goTorrent

Here is a link to the API docs: https://deranjer.github.io/goTorrentDocs/API/api/

Here is a link to a Javascript client that allows you to easily test the goTorrent API endpoints: https://github.com/deranjer/goTorrentAPITest

I will assist in any way possible, but I have never coded in C#, so hoping the team for Sonarr could at least get the websocket part setup, and I could perhaps do the rest.

**Comment by markus101** [comment]
Ideally things would be set to avoid a moving target, even a small one. It's also quite the chicken and egg problem, limited number of users and apps aren't supported so there is a a limit on the functionality.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
