### ISSUE TITLE
Feature request: bulk delete of activity queue

### ISSUE THREAD

**Issue by topendergit** [Sonarr/Sonarr#2495]
Accidently adding a monitored season which you didn't want leads to a large queue 
A bulk deletion would be appreciated. or delete without confirmation
Just had to delete 8 pages of spongebob episodes one by one from queue

**Comment by markus101** [comment]
You can delete directly from the download client (most of which support bulk actions), but bulk delete will be in v3.

**Comment by topendergit** [comment]
thanks. appreciated. deleting from download client leaves an orphan on the activity quest

**Comment by markus101** [comment]
Only until Sonarr sees that it's missing from the client, within a couple minutes.
