### ISSUE TITLE
The Walking Dead - Time per episode incorrect

### ISSUE THREAD

**Issue by Gingey231** [Sonarr/Sonarr#2499]
### System Information/Logs

**Sonarr Version:**
Sonarr Ver. 2.0.0.5163

**Operating System:**
Ubuntu 16.04 - Docker - Sonarr container: linuxserver/sonarr:latest

**.net Framework (Windows) or mono (macOS/Linux) Version:**
Mono Version: 5.10.1.20

**Link to Log Files (debug or trace):**
See Screenshots

**Browser (for UI bugs):**
Chrome - Version 65.0.3325.181 (Official Build) (64-bit)

### Additional Information
Please see the screenshots attached.

What seems to happen, is it will not pick up any new episodes for The Walking Dead when any 'Profile Quality' size options are set. I have attached my quality sizes, so most of the downloads should be able to be downloaded, however, as you can see by the screenshots, they just state that the size is bigger than the 1 minute episode?

![twd_1](https://user-images.githubusercontent.com/34947079/38528813-2497f9f2-3c59-11e8-9ff5-00734de9b48e.PNG)
![twd_2](https://user-images.githubusercontent.com/34947079/38528814-24b3d5be-3c59-11e8-9a4a-7fe87e95c621.PNG)
![twd_3](https://user-images.githubusercontent.com/34947079/38528923-cd7fa9b6-3c59-11e8-9d9c-14d0a2081f14.PNG)

**Comment by markus101** [comment]
Sonarr gets all series information from TheTVDB, if the runtime is incorrect it needs to be fixed there, it's not a bug with Sonarr.

**Comment by Gingey231** [comment]
Hi Markus, checking on TMBD, it has the episode runtimes at 42, 45, and 60 minutes, so where is it picking that 1 minute up from?
