### ISSUE TITLE
Sporadic rename of {MediaInfo VideoCodec}

### ISSUE THREAD

**Issue by CollinChaffin** [Sonarr/Sonarr#2500]
I was going to post this to the forum however I believe this may be a bug so will open here and you can redirect me if needed.

# Issue Summary
Sonarr renaming using the `{MediaInfo VideoCodec}` variable is inconsistent and does not match currently posted docs/posts expected behavior.  Files are not being properly renamed using the x264 identifier, regardless of original filename, codec identifier, or nzb/job name.

# Steps to Reproduce
1. File renaming enabled using the following standard episode template:

      `{Series.Title}.s{season:00}e{episode:00}.{Episode.Title}.{Quality.Title}.{MediaInfo VideoCodec}`

      Which shows the corresponding generated example proposed naming as:

      `The.Series.Title.(2010).s01e01.Episode.Title.(1).720p.HDTV.x264`

2. For educational purposes if we were to use the following randomly-selected recently posted media file original nzb/job name of:

      `Homeland.S07E09.Useful.Idiot.1080p.AMZN.WEBRip.DDP5.1.x264-NTb-postbot`

      Which has a raw underlying file name of:

      `9873ab684bf748178741f3c8269b5b29.mkv`

3. Allow Sonarr to process.  As you can see above, neither the nzb/job nor the original file name contain h264, yet Sonarr incorrectly produces the following final filename as:

      `Homeland.s07e09.Useful.Idiot.1080p.WebDL.h264.mkv`

# Additional Detail

After reading the wiki and as many open & closed issues I can find, the most relevant on this seems to be a post from a Sonarr team member in #1591 that actually states the exact opposite of what I see happening here with the post of:

      `We do it the other way around because x264 is by far the most common implementation used. So if the filename contains h264 it will keep it, otherwise it will be x264.`

I would be happy (and expect) what was explained in #1591 that x264 is the default.  However, that post does state if h264 is part of the original name it remains (something I would rather override if possible), yet in this case h264 is NOT part of the original name, yet using {MediaInfo VideoCodec} is doing the opposite of #1591 as well as what Mark posted which further supported this in the graphic in #2426 which also shows x264 as default.

I am seeing this in multiple file renames now, some with and others (including this one) without any prior use of the h264 identifier using 2.0.0.5169.  I understand the standards but I want to avoid Sonarr renaming to a new identifier when my entire library and possibly every single new file I download is already named x264 so is this a bug, or was that graphic and post not accurate and is there just a different variable we should be using to default to x264 for AVC, at least for files that do not already have the h264 on it?  And, is secondarily then can we go that one step further and ALWAYS use x264 for AVC even when a file is named using h264?

In the meantime, I will also start to dig into the code myself to try to help pin down exactly what might be happening but don't want to spend too much time since it sounds like v3 may be changing some of this anyway and hopefully is not to far off. :)

TIA!

**Comment by Taloth** [comment]
Thank you for the comprehensive post.

I recall we did some tweaks/changes/rewrites on that code, but the details is a bit fussy atm. I'll have to get back to you once I can take a closer look.
But I think all the x264 files I checked had the x264 as codec_library in mediainfo, and thus could be detected without parsing tags. Previously we didn't use the library info from mediainfo.

The logic dealing with the codec formatting can be found here https://github.com/Sonarr/Sonarr/blob/f1b2186313045559280db7b6cc82317a2cfc445d/src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs#L190-L339

A few pieces of info we'd like to know:
1) MediaInfo version. (And OS)
2) A copy of the mediainfo data from the database for that episode (sqlite database)
3) Manual output of Mediainfo for the same file
4) Directory + Filename. (unless it's the same file as you posted already)

**Comment by CollinChaffin** [comment]
Okay so I think I found the code responsible for this behavior and better understand it now.  It is not really as simple as whether the h264 identifier was in the source file.

https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs#L207-L215
````
if (videoFormat == "AVC" || videoFormat == "V.MPEG4/ISO/AVC")
   {
      if (videoCodecLibrary.StartsWithIgnoreCase("x264"))
      {
          return "x264";
      }

      return GetSceneNameMatch(sceneName, "AVC", "h264");
  }
````
And a cooresponding similar forum post I had previously missed here that defines this exact issue:
````
https://forums.sonarr.tv/t/mediainfo-videoc-is-defaulting-all-x264-to-h264/15864
````
So the question is since that post was just abandoned....how do we fix this or work around it?  Asking everyone with terabytes of x264 files labeled as such that now want to add new episodes that are even already named in the very same x264 standard (and yes fully understanding that technically h264 is the actual format name despite it not being used as often as x264) and only due to now apparenlty a tiny bit of missing encoder metatdata in the files really makes life tougher.  Apparently from the above post it looks like Mark confirmed the prior behavior that I quoted in my OP above had in fact changed so I'll wait for Mark to hopefully be able to help with a workaround to allow these x264 files to be renamed correctly.

**Comment by CollinChaffin** [comment]
Note the offending code causing this is line 214:

https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs#L214

Which, in this case because the metadata for the encoding library is not identified, yet the filename and media ID IS in fact x264, the if does not match and it falls through and gets the h264 instead. :(

**Comment by CollinChaffin** [comment]
....and then simply add one backfill support-level tokenhandler variable (ie {PREFER XIDENTIFIER}) (or better yet one simple configuration option asking the users' 26? ID preference (either x264/x264 or h264/h265), and adjust the code at:
````
https://github.com/Sonarr/Sonarr/blob/a023732c1c96141baa0e91ad05f91757ee4f23c7/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L496
````
And add a couple lines of code to apply that preference there upon resolving that tokenhandler right there when it goes to check the media (should make it easier)....just an idea.

**Comment by Taloth** [comment]
Can you still get me the requested information from my previous post?

We're definitely not going to add a configuration option for it, but I have a few tweaks in mind.

**Comment by CollinChaffin** [comment]
So sorry I totally missed your request! Here is is:

1. MediaInfo version. (And OS)
````
My mediainfo version if that is what you are asking (I am using the latest Sonarr DEV release) is:

C:\Data\Scripts> mediainfo --version
MediaInfo Command line,
MediaInfoLib - v18.03.1
````
2. A copy of the mediainfo data from the database for that episode (sqlite database)
````
Not sure what you are requesting here - can you clarify?
````
3. Manual output of Mediainfo for the same file
````
Here is yet another release randomly grabbed for this test (the writing library is forcing the inconsistent fallthrough in the above posted IF statement even though the others also with ID of AVC then do get named x264 only f that (IMO meaningless) writing library metadata does not indicate the "x" and not "h"):

R:\mediainfo '.\Killing.Eve.s01e02.I''ll.Deal.with.Him.Later.1080p.WebDL.h264.mkv'
General
Unique ID                                : 65049712415080889354525361522829564739 (0x30F01E705270E6381D6EFE8F7CD21B43)
Complete name                            : .\Killing.Eve.s01e02.I'll.Deal.with.Him.Later.1080p.WebDL.h264.mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 1.12 GiB
Duration                                 : 43 min 22 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 3 693 kb/s
Encoded date                             : UTC 2018-04-16 07:19:51
Writing application                      : mkvmerge v22.0.0 ('At The End Of The World') 64-bit
Writing library                          : libebml v1.3.5 + libmatroska v1.4.8

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 43 min 22 s
Bit rate mode                            : Variable
Bit rate                                 : 3 051 kb/s
Maximum bit rate                         : 15.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.061
Stream size                              : 946 MiB (83%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced Audio Coding 3
Codec ID                                 : A_EAC3
Duration                                 : 43 min 22 s
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 187.500 FPS (256 SPF)
Compression mode                         : Lossy
Stream size                              : 199 MiB (17%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 42 min 48 s
Bit rate                                 : 64 b/s
Count of elements                        : 690
Stream size                              : 20.3 KiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No
````
4. Directory + Filename. (unless it's the same file as you posted already)
````
Original release name (note both the original filename and release name use x264 there is NO usage of h264 in the original):
Killing.Eve.S01E02.Ill.Deal.with.Him.Later.1080p.AMZN.WEBRip.DDP5.1.x264-NTb

Sonarr renamed it to what is listed in mediainfo:
"Killing Eve\Season 01\Killing.Eve.s01e02.I'll.Deal.with.Him.Later.1080p.WebDL.h264.mkv"
````
As you can see, it is totally inconsistent.  50% of releases that are h264 are being renamed by Sonarr with the "h"264, and the other half as "x"264 due to what I am still trying to figure out would EVER make me choose (the WRITING LIBRARY metadata).  I know of no other software or system that is currently keying on whether a file is x264 or h264 based on that field - since as has been repeatedly pointed out - it is ALL the h264 standard and x264 simply became a common naming standard.  My point here is even though I very much prefer and use x264 in my library, I support Sonarr so much already that I honestly will take the time to go back and rename all of it to h264 but it doesn't pay since Sonarr clearly (right now) is so inconsistent and can look at 2 releases from the same group both even having x264 in the file AND release name, yet if the group botches (or omits) the (non-mandatory) "writing library" field I will wind up with literally one file named as h264, and the other as x264.  

I'm surprised more aren't pointing this out since it is pretty clear in the code it is currently impossible to get a predictable h264 final filename from Sonarr without first looking at the internal writing library metadata.

This:  `"if (videoCodecLibrary.StartsWithIgnoreCase("x264"))"` is the line of code that forces one to first look inside their h264 releases at a totally non-mandatory metadata field to be able to now predict how Sonarr will name the final file.  Not by the former method of trusting whether the x264 preference was already in the original filename, nor by which is used in the original release name, nor by the 4cc codec ID (AVC is h264 hence my config flag comment to just pick one or the other if AVC)

I hope this info helps!  Just let me know if there is anything else I can test on this.  Thanks!

**Comment by Taloth** [comment]
Ignore (2), it's not important given the specific mediainfo you posted.

First, I really don't wish to have a discussion about codec names in general. In the scope of scene release the tag x264 vs h264 denotes the difference between video streams encoded with x264 encoder specifically, and h264 essentially boils down to untouched original streams encoded with official licensed implementations. They both implement the MPEG-4 Part 10 aka AVC standard. What is called 'codec' is totally irrelevant from this perspective.

Secondly, WEB-DL (p2p) and WEB (scene) both denote untouched streams: just the stream downloaded from a site and DRM removed. WEBRip could be re-encodes (thus x264) or separate captures. AMZN releases have been going back and forth between WEB-DL and WEBRip since their streaming DRM got broken and fixed a few times already.
(Please note that WEB/WEB-DL untouched streams can in fact be x264, if the untouched stream was encoded with it, but it rarely is.)

If the _video_ writing library is x264, then it's x264. Example:

Lucifer.S03E01.Theyre.Back.Again.Arent.They.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
Lucifer.S03E01.Theyre.Back.Again.Arent.They.720p.AMZN.WEBRip.DDP5.1.x264-NTb

The 1080p file has the untouched stream and has no Video writing library header.
The 720p file is most likely a re-encode from that 1080p file and contains `Writing library : x264 core 148 r2638 7599210`.  Thus it has a x264 tag _and_ becomes a WEBRip.
That's why Sonarr reads the the video writing library. If it's x264, then it'll override whatever tag there might be in the url.

The mistake was not to honor x264 tags if no video writing library is specified.
_That's debatable to some extend, since scene rules mandate that the writing library property is set (or rather, scene disallows header stripping). But p2p does not mandate anything, nor do private re-encodes. So the tag should be honored if there is nothing else proving it wrong._

Therefore my first step should be to add x264 to https://github.com/Sonarr/Sonarr/blob/f1b2186313045559280db7b6cc82317a2cfc445d/src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs#L214 so that it's honored again. Even if it's not not necessarily true. Similar to how it is in `FormatVideoCodecLegacy`.

PS: I checked at the source: Killing.Eve.S01E02.Ill.Deal.with.Him.Later.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb	
meaning that it is, in fact an untouched stream. Same mediainfo as you, same unique id, and typical amazon encode parameters. (unlikely to be encoded using x264). So the file should have a h264 tag in the filename, and if Sonarr encounters the original file, it will keep that tag.
