### ISSUE TITLE
Update Anime Tosho API URL

### ISSUE THREAD

**Issue by animetosho** [Sonarr/Sonarr#2501]
Sorry to be a bother, but would it be possible to change the default URL for the Anime Tosho API/feed from https://animetosho.org/feed/* to https://feed.animetosho.org/* ?  
(all URLs under /feed/ have been moved to its own host)

I plan to eventually put in a 301 redirect for old references, sometime in the future, but I thought that it'd make sense to update any defaults before that (avoids the need for all clients to go through an extra redirect).

Moving the feed into its own subdomain just gives me a bit more flexibility with directing traffic should the need ever arise. There shouldn't be a further need for an URL change in the future.

Thank you!

**Comment by Taloth** [comment]
No bother at all. I'll change the default immediately although it'll take a while to get to master and the bulk of our users.
I also added a db migration that replaces the existing urls.

**Comment by animetosho** [comment]
Awesome, thank you!
