### ISSUE TITLE
Calendar not finding current and future episodes of a show (the late show with stephen colbert)

### ISSUE THREAD

**Issue by ecchi** [Sonarr/Sonarr#2502]
Last recorded episode was Monday (April 9th). Tuesday's (10th) and future episodes are not displayed on the calendar. Prior to the 9th, the series had been working without issue.
Not an tvdb issue, since tvdb has the current and upcoming episodes on it's episode list. Tried restarting, and swapping from daily to standard to daily again. Version 2.0.0.5163

**Comment by markus101** [comment]
Please use the forums for support. Make sure the series and the episodes within are monitored (or show unmonitored episodes on the calendar).
