### ISSUE TITLE
season and episode number instead of episode name in ICal feed

### ISSUE THREAD

**Issue by frumpymoons** [Sonarr/Sonarr#2504]
## Feature Request

Hello, would it be possible to add an option to have the season and episode number in the ICal feed title?

Right now it looks like this:
Gotham - A Dark Knight: That's Entertainment

What I expect:
Gotham - S04E18

**Comment by markus101** [comment]
For daily series it will show as `Gotham - A Dark Knight: That's Entertainment`, but for everything else it will show as `Gotham - S04E18 - A Dark Knight: That's Entertainment`. No plans to add an option to change it beyond that.
