### ISSUE TITLE
Sonarr not deleting lower quality individual episodes on quality/cutoff upgrade of episode

### ISSUE THREAD

**Issue by infamouswb** [Sonarr/Sonarr#2505]
## Bug Report

Example: I just checked an episode of a show Sonarr is monitoring...here is the history:

**The following happens automatically:**

Sonarr Downloaded SD file...thenan hour later
Sonarr Downloaded 720P File

At this point both remain, Sonar does not delete the SD file, however it does state in the history of the episode that it deleted it, with the little trash icon.

A few hours later....

3. Sonarr downloaded 1080 file, sonarr removed the SD and 720P files.

### System Information/Logs

Here is part of the file log:

`18-4-10 14:43:17.6|Error|Owin|SignalR exception thrown by Task: System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse'. at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.ResponseBodyStarted () [0x0001a] in <208c8ef8a4ba4b878f0e4420d5960bea>:0 at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.OnResponseBodyStarted (System.Object state) [0x00007] in <208c8ef8a4ba4b878f0e4420d5960bea>:0 at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream+OneTimeCallback.TryInvoke () [0x00019] in <208c8ef8a4ba4b878f0e4420d5960bea>:0 at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.FirstWrite () [0x00000] in <208c8ef8a4ba4b878f0e4420d5960bea>:0 at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00024] in <208c8ef8a4ba4b878f0e4420d5960bea>:0 at Microsoft.AspNet.SignalR.Owin.ServerResponse.Write (System.ArraySegment1[T] data) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Owin\ServerResponse.cs:50 at Microsoft.AspNet.SignalR.Infrastructure.BinaryTextWriter+<>c.<.ctor>b__0_0 (System.ArraySegment1[T] data, System.Object state) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BinaryTextWriter.cs:12 at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter+ChunkedWriter.Flush (System.Byte[] byteBuffer, System.Boolean flushEncoder) [0x00027] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:182 at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter+ChunkedWriter.Flush (System.Boolean flushEncoder) [0x00008] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:163 at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter+ChunkedWriter.Flush () [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:155 at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter+ChunkedWriter.Write (System.ArraySegment1[T] data) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:149 at Microsoft.AspNet.SignalR.Infrastructure.BinaryTextWriter.Write (System.ArraySegment1[T] data) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BinaryTextWriter.cs:31 at Microsoft.AspNet.SignalR.Transports.PersistentResponse.WriteMessages (System.IO.TextWriter writer, Newtonsoft.Json.JsonTextWriter jsonWriter) [0x00063] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Transports\PersistentResponse.cs:167 at Microsoft.AspNet.SignalR.Transports.PersistentResponse.Microsoft.AspNet.SignalR.Json.IJsonWritable.WriteJson (System.IO.TextWriter writer) [0x000f5] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Transports\PersistentResponse.cs:131 at Microsoft.AspNet.SignalR.Json.JsonNetSerializer.Serialize (System.Object value, System.IO.TextWriter writer) [0x0000a] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Json\JsonNetSerializer.cs:61 at NzbDrone.SignalR.Serializer.Serialize (System.Object value, System.IO.TextWriter writer) [0x0001f] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.SignalR\Serializer.cs:20 at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.PerformSend (System.Object state) [0x00085] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Transports\LongPollingTransport.cs:315 at Microsoft.AspNet.SignalR.Transports.LongPollingTransport+<>c.<Send>b43_0 (System.Object state) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Transports\LongPollingTransport.cs:157 at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.<Enqueue>b140 (System.Func2[T,TResult] next, System.Object nextState) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\TaskQueue.cs:85 at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod[T1,T2] (System.Func3[T1,T2,TResult] func, T1 arg1, T2 arg2) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\TaskAsyncHelper.cs:764 --- End of inner exception stack trace --- ---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse'. at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.ResponseBodyStarted () [0x0001a] in <208c8ef8a4ba4b878f0e4420d5960bea>:0 at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.OnResponseBodyStarted (System.Object state) [0x00007] in <208c8ef8a4ba4b878f0e4420d5960bea>:0 at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream+OneTimeCallback.TryInvoke () [0x00019] in <208c8ef8a4ba4b878f0e4420d5960bea>:0 at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.FirstWrite () [0x00000] in <208c8ef8a4ba4b878f0e4420d5960bea>:0 at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00024] in <208c8ef8a4ba4b878f0e4420d5960bea>:0 at Microsoft.AspNet.SignalR.Owin.ServerResponse.Write (System.ArraySegment1[T] data) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Owin\ServerResponse.cs:50 at Microsoft.AspNet.SignalR.Infrastructure.BinaryTextWriter+<>c.<.ctor>b__0_0 (System.ArraySegment1[T] data, System.Object state) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BinaryTextWriter.cs:12 at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter+ChunkedWriter.Flush (System.Byte[] byteBuffer, System.Boolean flushEncoder) [0x00027] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:182 at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter+ChunkedWriter.Flush (System.Boolean flushEncoder) [0x00008] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:163 at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter+ChunkedWriter.Flush () [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:155 at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter+ChunkedWriter.Write (System.ArraySegment1[T] data) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:149 at Microsoft.AspNet.SignalR.Infrastructure.BinaryTextWriter.Write (System.ArraySegment1[T] data) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BinaryTextWriter.cs:31 at Microsoft.AspNet.SignalR.Transports.PersistentResponse.WriteMessages (System.IO.TextWriter writer, Newtonsoft.Json.JsonTextWriter jsonWriter) [0x00063] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Transports\PersistentResponse.cs:167 at Microsoft.AspNet.SignalR.Transports.PersistentResponse.Microsoft.AspNet.SignalR.Json.IJsonWritable.WriteJson (System.IO.TextWriter writer) [0x000f5] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Transports\PersistentResponse.cs:131 at Microsoft.AspNet.SignalR.Json.JsonNetSerializer.Serialize (System.Object value, System.IO.TextWriter writer) [0x0000a] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Json\JsonNetSerializer.cs:61 at NzbDrone.SignalR.Serializer.Serialize (System.Object value, System.IO.TextWriter writer) [0x0001f] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.SignalR\Serializer.cs:20 at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.PerformSend (System.Object state) [0x00085] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Transports\LongPollingTransport.cs:315 at Microsoft.AspNet.SignalR.Transports.LongPollingTransport+<>c.<Send>b43_0 (System.Object state) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Transports\LongPollingTransport.cs:157 at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.<Enqueue>b_14_0 (System.Func2[T,TResult] next, System.Object nextState) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\Infrastructure\TaskQueue.cs:85 at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod[T1,T2] (System.Func3[T1,T2,TResult] func, T1 arg1, T2 arg2) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\Microsoft.AspNet.SignalR.Core\TaskAsyncHelper.cs:764 <---
`
**Sonarr Version:**

2.0.0.5163

**Operating System:**

Ubuntu 16.04 LTS

**.net Framework (Windows) or mono (macOS/Linux) Version:**

5.10.1.4

**Link to Log Files (debug or trace):**

I'm not sure if this will give private information. PM me if needed.

**Browser (for UI bugs):**

I'm not sure if this will give private information. PM me if needed.

**Comment by markus101** [comment]
The log snippet you posted isn't related. We definitely need logs, but we can't PM. Please open a thread on the forums, if we find something that needs to be addressed we'll open an issue, but right now there is nothing to go on.

**Comment by infamouswb** [comment]
@markus101 Which logs do you want me to send over?
