### ISSUE TITLE
Feature request: keep retrying failed indexers once a day for 30 days

### ISSUE THREAD

**Issue by PieMistake** [Sonarr/Sonarr#2507]
Very often an indexer goes down for more than 24 hours. As a result, Sonarr stops using it and presents an error which can only be resolved by logging in, finding the indexer and testing it. 

https://github.com/Sonarr/Sonarr/wiki/Health-checks#indexers-are-unavailable-due-to-failures

Rather than just give up after 24 hours, can we please make it so that Sonarr checks once every 24 hours for a period of 30 days? Based on my anecdotal experience, a good number of indexers go down for more than a day but less than a week. 

This change would mean that I don’t have to keep logging into Sonarr every couple of days to manually re-enable an indexer which has gone offline for longer than a day

**Comment by markus101** [comment]
> Rather than just give up after 24 hours

Sonarr doesn't give up after 24 hours, it doesn't try again for 24 hours (and it'll continue to try again every 24 hours until disabled or removed). It's already doing what you're asking for (minus the time limit, which isn't something we plan to do).

**Comment by PieMistake** [comment]
That’s odd. If an indexer comes back to life then Sonarr continues to report it as unavailable until I manually test it. If it’s really checking every 24 hours then it would know that it’s back up again and wouldn’t need to advise me to test it. 

Right now RARBG is reported as unavailable, despite the fact it’s been over a week since it came back up again. 

Should I file is as a bug report then?

**Comment by markus101** [comment]
Debug logs would be the first step, that'll report when a disabled indexer will next be used.

If RSS is disabled indexers won't automatically be retested.
