### ISSUE TITLE
Demonoid and other providers wrapping episode in .rar

### ISSUE THREAD

**Issue by dkids** [Sonarr/Sonarr#2508]
torrent | 0.6 minute | The.Expanse.S03E01 .720p.WEB-DL.HEVC. x265 | Demonoid - Jackett | 193.9 MB | 26 / 26 | WEBDL-720p |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
torrent | 0.3 minutes | The.Expanse.S03E01.720p.WEB-DL.HEVC.x265 | 1337x.to - Jackett | 193.9 MB | 26 / 19 | WEBDL-720p |   |  

Both of those files are a .mkv moved into a .rar   

https://www.demonoid.pw/files/details/3805390/?loadbal=NjY0YjlYOVd3M3JVdGsvd05DSEh3Zz09&show_files=1&page=1&ref=1523563574#file_list

Filename: t.s03e01.720p_www.demonoid.pw_.rar

I tried adding ".rar" as a "must not contain term" but that's had no effect.   I have to unrar the file, move it to my import directory and import it.

The size of the .rar file is basically the same as the .mkv file, making it impossible to set a lower bound for size to exclude compressed files.

I would prefer to exclude .rar files but if Sonarr handled everything (unrar, import, delete .mkv after import) automatically, that would work.

Sonarr and Mono versions on MacOS 10.13.4
Version
    2.0.0.5163
Mono Version
    5.8.0.129

grep -i expanse *0.txt
18-4-11 20:30:57.9|Info|RefreshSeriesService|Updating Info for The Expanse
18-4-11 20:30:58.3|Info|RefreshEpisodeService|Starting episode info refresh for: [280619][The Expanse]
18-4-11 20:30:58.4|Info|RefreshEpisodeService|Finished episode refresh for series: [280619][The Expanse].
18-4-11 20:30:58.4|Info|DiskScanService|Scanning disk for The Expanse
18-4-11 20:30:58.5|Info|DiskScanService|Completed scanning disk for The Expanse
18-4-11 20:30:59.1|Info|MediaCoverService|Downloading Fanart for [280619][The Expanse] https://www.thetvdb.com/banners/fanart/original/280619-6.jpg
18-4-12 05:39:14.2|Info|DownloadService|Report sent to Transmission. The.Expanse.S03E01 .720p.WEB-DL.HEVC. x265
18-4-12 08:35:13.6|Info|RefreshSeriesService|Updating Info for The Expanse
18-4-12 08:35:13.8|Info|RefreshEpisodeService|Starting episode info refresh for: [280619][The Expanse]
18-4-12 08:35:14.1|Info|RefreshEpisodeService|Finished episode refresh for series: [280619][The Expanse].
18-4-12 08:35:14.1|Info|DiskScanService|Scanning disk for The Expanse
18-4-12 08:35:14.2|Info|DiskScanService|Completed scanning disk for The Expanse

**Comment by markus101** [comment]
Currently unraring needs to be handled by the download client. Sonarr does not know if a download is going to contain a RAR prior to download, so it cannot be excluded.

There is https://github.com/Sonarr/Sonarr/issues/784 for supporting unraring, but for now your client needs to handle it or you need to avoid indexers with RAR files.
