### ISSUE TITLE
BiglyBT support

### ISSUE THREAD

**Issue by RimfireFoShizzle** [Sonarr/Sonarr#2511]
### What problem are you looking to solve?
Please add support for BiglyBT as a download client. See https://www.biglybt.com for more information about this software.

**Comment by markus101** [comment]
If it's the same API as Vuze, use the that in Sonarr. I don't see any API docs in my quick search, is there an API?

**Comment by RimfireFoShizzle** [comment]
According to the dev, it should be the same api.

I'm gonna test this tonight and will let you know.

**Comment by RimfireFoShizzle** [comment]
Works like a charm!

Issue closed.
