### ISSUE TITLE
Rename Action doesn't work immediately

### ISSUE THREAD

**Issue by wiwi95971** [Sonarr/Sonarr#2514]
Hi,

is it that possible to add a toggle or a bouton to check for new episodes who must be renamed and moved to their respective folder.
to be clear when I download some episodes manually for X raison, the renamed action doesn't work immediatly.

**Comment by markus101** [comment]
If you grab a release manually, make sure it has the correct label/category in your download client. If the download has already completed and you can't set the label/category you can use Manual Import from Wanted: Missing.
