### ISSUE TITLE
sonarr requires CSP script-src 'unsafe-eval'

### ISSUE THREAD

**Issue by timball** [Sonarr/Sonarr#2517]
### System Information/Logs

**Sonarr Version:** 2.0.0.5163

**Operating System:** Darwin myhostname 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

**.net Framework (Windows) or mono (macOS/Linux) Version:** 4.8.0

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):** chrome Version 65.0.3325.181

### Additional Information
This is both a feature request and potentially a bug. It is related to enabling Content Security Polices for Sonarr. See https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP for more information about CSP. 

## Feature Request
Make sonarr CSP compatible. 

### What problem are you looking to solve?
Have sonarr stop generating unsafe-eval javascript. 

### Other Information
my current CSP for nginx that almost works is: 
```
 add_header Content-Security-Policy "default-src 'none'; frame-ancestors 'none'; object-src 'none'; require-sri-for script style; base-uri 'self'; form-action 'self'; report-uri 'https://the-place-i-report-csp/errors/'; script-src 'self' 'sha256-SLaivCoiCEU5Xtj9f78zPqdd+ql57G5jbX71EyyGpy8='; style-src 'self' 'unsafe-inline'; img-src 'self'; font-src 'self'; connect-src 'self';" always;
```

Results in Chrome Console Errors:
```
lodash.underscore.js:4236 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'sha256-SLaivCoiCEU5Xtj9f78zPqdd+ql57G5jbX71EyyGpy8='".


    at Function (<anonymous>)
    at Function.template (lodash.underscore.js:4236)
    at backbone.backgrid.js:1296
    at backbone.backgrid.js:13
    at Object.81 (backbone.backgrid.js:22)
    at __webpack_require__ (bootstrap baaf0fd75373247a910e:50)
    at Object.80 (backgrid.js:3)
    at __webpack_require__ (bootstrap baaf0fd75373247a910e:50)
    at Object.0 (vendor.js:29)
    at __webpack_require__ (bootstrap baaf0fd75373247a910e:50)
template @ lodash.underscore.js:4236
(anonymous) @ backbone.backgrid.js:1296
(anonymous) @ backbone.backgrid.js:13
81 @ backbone.backgrid.js:22
__webpack_require__ @ bootstrap baaf0fd75373247a910e:50
80 @ backgrid.js:3
__webpack_require__ @ bootstrap baaf0fd75373247a910e:50
0 @ vendor.js:29
__webpack_require__ @ bootstrap baaf0fd75373247a910e:50
0 @ bootstrap baaf0fd75373247a910e:93
(anonymous) @ bootstrap baaf0fd75373247a910e:93
```
This seems related to https://github.com/lodash/lodash/issues/832 

While `unsafe-inline` for `style-src` isn't "great" it's not the worst. `unsafe-eval` is less good and would be great if sonarr could be made to work w/o it.

--timball

**Comment by markus101** [comment]
In v3 (not yet released), this works:

```
"default-src 'none'; frame-ancestors 'none'; object-src 'none'; require-sri-for script style; base-uri 'self'; form-action 'self'; report-uri 'https://the-place-i-report-csp/errors/'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self' wss:;"
```

The one issue that had to be eliminated was the `script-src` `sha256-SLaivCoiCEU5Xtj9f78zPqdd+ql57G5jbX71EyyGpy8=`, as that's going to change whenever the version of Sonarr changes (or anything within the inline script block), so the inline block had to go.
