### ISSUE TITLE
Sonarr is not see Anime formats "s3 - 02" or "S03 - 02"

### ISSUE THREAD

**Issue by Bryant2of3** [Sonarr/Sonarr#2518]
Sonarr could not find the following nzb anime file. I'm also using 5040.

"[Golumpa] My Hero Academia S3 - 03 (Boku no Hero Academia) [FuniDub 1080p x264 AAC] [734E9228]"

**Comment by markus101** [comment]
https://forums.sonarr.tv/t/scene-naming-tvdb-naming-conflicts/137 (the alias needs to be added on thexem.de).

**Comment by M0UL** [comment]
not possible in this case. not all release groups are using the same numbering for that shows.  the xem cannot handle that.
