### ISSUE TITLE
Force copy/hardlink for imported show

### ISSUE THREAD

**Issue by rbhalla** [Sonarr/Sonarr#2521]
## Feature Request

Right now all manually imported shows are being moved from the download folder to my media folder despite my torrent client seeding them. Sonarr does have a connection to my download client, so I'm not sure if it's failing to relate the files to the download happening. Ideally we should be able to specify default behaviour for manual imports like we do for normal post processing.

Unfortunately this means I just can't use manual import. This problem becomes a little bit more frustrating with the fact the only way I've found to get certain season packs is to download them manually since searching the indexers through sonarr yield incorrect results.

### What problem are you looking to solve?

I want to continue seeding after a manual import.

There is a slightly related issue here https://github.com/Sonarr/Sonarr/issues/1906 about being able to set this at the point of import. I felt this request was different enough to warrant a separate issue, but if you'd like to tackle both these problems in the same way feel free to close this one.

**Comment by Taloth** [comment]
The Manual import dialog has a dropdown in the bottom left corner allowing you to specify whether you want to Move or Copy(/Hardlink).

Secondly, you should add manual downloads to the correct category in your download client. In most cases that'll allow Sonarr to pick them up automatically.

**Comment by rbhalla** [comment]
Hey, thanks for the quick response! I think that's what I missed I was jumping to automatic import and assumed it would inherit settings but that seems like a good workaround. 

I'm not sure what you mean by correct category. Do you mean label? I assumed label was just for superficial benefits, but if it also helps imports that's good to know going forward.

**Comment by Taloth** [comment]
Yes, label, in Sonarr it's always called category but in the download client it's named differently depending on the client.
Having a category is important coz Sonarr will only auto import from that particular category. If no category is configured at all then Sonarr will refuse to auto import unknown downloads (otherwise it might try importing games and movies)

**Comment by rbhalla** [comment]
@Taloth thank you for your help, I appreciate this wasn't quite the feature request I thought it'd be and more my misunderstanding of sonarr. You're right, I am using deluge so label is what I had in my mind. I've set categories on my future downloads to make this all a little easier. Thanks again!
