### ISSUE TITLE
Including another View of "Running Only" Shows

### ISSUE THREAD

**Issue by fahadsgalaxy** [Sonarr/Sonarr#2525]
## Feature Request
Adding another View "Running Only" to display only the shows that are still running and new episodes are coming out.

### What problem are you looking to solve?

Resolving the issue to have a View that displays ONLY the shows that are currently running.
The View "Continuing ONLY" does seems to work, but for people like me who have many shows with most being on hiatus status displays way too many shows and makes it hard to focus on what show is running.

**Comment by markus101** [comment]
What about `Continuing Only` sorted by Next Airing?

Beyond that, the calendar is the best place to see what's actively airing. No plans for a similar, but different view at this time.

**Comment by fahadsgalaxy** [comment]
Actually thats exactly what I've been doing. 
its been working good, but it fills up the screen with shows that are not currently airing on TV.

I was hoping for a dedicated view only for shows that are "currently airing" on TV
Because it gives us a much clearer view of shows that we can expect to watch within a few days. Not wait for months for shows like GOT and others that just ended seasons, you can see where I am going 😁 

Next Airing sure is good, but I just felt there was a need for another view, to display just the shows we can expect to see within days 😀
