### ISSUE TITLE
Moving and deleting leftovers

### ISSUE THREAD

**Issue by LaChoz** [Sonarr/Sonarr#2527]
Hi all,

I seem to have lost the possibility to simply move completed downloads and deleting leftovers.
Today it seems my Sonarr only copy and leave the original unpacked folder il my completed download folder, taking quite some space and forcing me to come and clean manualy.

Am I missing a feature somewhere ?

I use Sonarr / Radarr and nzbGet with nzbtonzbdrone/radarr postprocess script and also transmission. 
I have disabled renaming and disabled "use hardlink instead of copy"
I have enabled "complete download handling"

Thx for any help.

**Comment by markus101** [comment]
Please use the forums for support and read the FAQ entry on seeding torrents.
