### ISSUE TITLE
Package Sonarr has snap

### ISSUE THREAD

**Issue by Alculete** [Sonarr/Sonarr#2528]
I had few issues installing Sonarr last time that I opted to use [AtoMiC-ToolKit](https://github.com/htpcBeginner/AtoMiC-ToolKit) because of some dependencies not satisfied.
Snap packages allows applications to have all dependencies inside the package reducing the work the end user would have  to install or update the app. 
Is there any change to package  Sonarr as snap?

**Comment by markus101** [comment]
No plans for a snap at this time, but the previous issue is tagged and may be looked at in the future https://github.com/Sonarr/Sonarr/issues/2303
