### ISSUE TITLE
Skip not-yet-aired episodes when searching for monitored episodes

### ISSUE THREAD

**Issue by kevinwlau** [Sonarr/Sonarr#2530]
Whenever a season/series search is initiated for monitored episodes, sonarr goes off to search for every monitored episode, including ones that have not aired.

### System Information/Logs

**Sonarr Version:** 2.0.0.5163

**Operating System:** Windows 8.1 64-bit

**.NET Framework:** 4.6

## Feature Request

It would be nice if in addition to being a monitored episode, a check was added to see if that status is not `TBA` or `not-aired`, or if an air date exists before sending a request to search for it.

### What problem are you looking to solve?

Optimizing the season/series search by reducing unnecessary requests

**Comment by Thirrian** [comment]
Sonarr doesn't search episode per episode when performing a season or series search.
Series search: season per season, as below.
Season search: one api call to each indexer to get all results for that season.

**Comment by markus101** [comment]
Just to clarify, it's one or more API calls per season, more being used is additional results need to be fetched because the indexer returned the maximum number of results (up to a maximum of 10 requests per indexer for a single season).

**Comment by kevinwlau** [comment]
Oh, I didn't realize it was all handled under one api call per season. From the slow-rolling notifications and the log of the api calls, it seemed as if they were per episode.

**Comment by kevinwlau** [comment]
In a test run season search, it took a little over a minute, according to the logs.

```18-4-30 19:38:44.0|Info|DownloadDecisionMaker|Processing 30 releases
18-4-30 19:38:45.1|Info|NzbSearchService|Searching 2 indexers for [Laid-Back Camp : 02]
18-4-30 19:38:55.9|Info|DownloadDecisionMaker|Processing 9 releases
18-4-30 19:38:56.1|Info|NzbSearchService|Searching 2 indexers for [Laid-Back Camp : 03]
18-4-30 19:39:03.9|Info|DownloadDecisionMaker|Processing 7 releases
18-4-30 19:39:04.0|Info|NzbSearchService|Searching 2 indexers for [Laid-Back Camp : 04]
18-4-30 19:39:11.9|Info|DownloadDecisionMaker|Processing 19 releases
18-4-30 19:39:12.3|Info|NzbSearchService|Searching 2 indexers for [Laid-Back Camp : 05]
18-4-30 19:39:19.9|Info|DownloadDecisionMaker|Processing 7 releases
18-4-30 19:39:20.0|Info|NzbSearchService|Searching 2 indexers for [Laid-Back Camp : 06]
18-4-30 19:39:27.9|Info|DownloadDecisionMaker|Processing 4 releases
18-4-30 19:39:28.0|Info|NzbSearchService|Searching 2 indexers for [Laid-Back Camp : 07]
18-4-30 19:39:35.9|Info|DownloadDecisionMaker|Processing 20 releases
18-4-30 19:39:36.5|Info|NzbSearchService|Searching 2 indexers for [Laid-Back Camp : 08]
18-4-30 19:39:43.9|Info|DownloadDecisionMaker|Processing 6 releases
18-4-30 19:39:44.1|Info|NzbSearchService|Searching 2 indexers for [Laid-Back Camp : 09]
18-4-30 19:39:51.9|Info|DownloadDecisionMaker|Processing 6 releases
18-4-30 19:39:52.0|Info|NzbSearchService|Searching 2 indexers for [Laid-Back Camp : 10]
18-4-30 19:39:55.9|Info|DownloadDecisionMaker|Processing 16 releases
18-4-30 19:39:56.2|Info|NzbSearchService|Searching 2 indexers for [Laid-Back Camp : 11]
18-4-30 19:39:59.9|Info|DownloadDecisionMaker|Processing 5 releases
18-4-30 19:40:00.1|Info|NzbSearchService|Searching 2 indexers for [Laid-Back Camp : 12]
18-4-30 19:40:04.0|Info|DownloadDecisionMaker|Processing 4 releases
```

**Comment by markus101** [comment]
Ahh, Anime, that'll use individual searches since there often aren't season packs, just batches which aren't always for the full season.
