### ISSUE TITLE
Mono 5.11.0 - sonarr not working

### ISSUE THREAD

**Issue by Blisk** [Sonarr/Sonarr#2531]
### System Information/Logs

**Sonarr Version:**
2.0.0.5163
**Operating System:**
qnap
**.net Framework (Windows) or mono (macOS/Linux) Version:**
mono 5.11.0
**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**

### What problem are you looking to solve?
Sonarr start but doens't open page in browser

**Comment by markus101** [comment]
Please use the forums for support. We'll need to see debug logs at a minimum.
