### ISSUE TITLE
More detail for Rename event in custom post processing scripts

### ISSUE THREAD

**Issue by RikuXan** [Sonarr/Sonarr#2539]
Currently, the Rename event in custom post processing supplies the following environment variables:
`sonarr_eventtype, sonarr_series_id, sonarr_series_title, sonarr_series_path, sonarr_series_tvdbid`

None of these variables contain any information as to which files have been renamed and what their new name actually is. For Download/Upgrade events, this information is supplied through for example the `sonarr_deletedpaths` and `sonarr_episodefile_path` variables.

Adding such information (previous and updated full path for every file that was renamed) to the Rename event would aid in creating more powerful post processing scripts, for example in trying to map such renames to a cloud storage.

**Comment by markus101** [comment]
No plans to extended the custom script to pass that information (it's ugly to do so in environment variables). You can get this information from the API though, see: https://github.com/Sonarr/Sonarr/issues/1541
