### ISSUE TITLE
Strip "www.torrenting.com - " from search results

### ISSUE THREAD

**Issue by dkids** [Sonarr/Sonarr#2542]
www.Torrenting.com - MAJOR.2nd.S01E04.720p.HEVC.x265-MeGusta
www.Torrenting.com - MAJOR.2nd.S01E04.1080p.WEB.x264-DARKFLiX
www.Torrenting.com - MAJOR.2nd.S01E04.720p.WEB.x264-DARKFLiX
www.Torrenting.com - MAJOR.2nd.S01E04.XviD-AFG
www.Torrenting.com - MAJOR.2nd.S01E04.WEB.x264-DARKFLiX
www.Torrenting.com - MAJOR.2nd.S01E04.480p.x264-mSD
www.Torrenting.com - MAJOR.2nd.S01E04.1080p.HEVC.x265-MeGusta

Release is rejected because it's an unknown series.

There's no option to manually force a download.

I don't find any options in settings to strip this.

**Comment by dkids** [comment]
lucasvanhalst: thank you, I'm familiar with that.   I use "must contain" with x265/h265/hevc since there's no other way to do that.   

I don't see where it helps with removing part of the torrent file name.  And I don't want to put in "must contain www.torrenting.com" because I don't want to only download those torrents.

**Comment by beschoenen** [comment]
Are you getting your feed via [Jackett](https://github.com/Jackett/Jackett)? If so you should create an issue on their repo.
