### ISSUE TITLE
Sonarr web ui on Chromebook

### ISSUE THREAD

**Issue by shnickelson** [Sonarr/Sonarr#2543]
I have Sonarr (and Radarr) installed on a Windows PC.  I was hoping to to be able to access the web ui on other computers in my home network, mostly on my Chromebook.  I've seen comments suggesting all you need to do is open the program as admin but I haven't had luck with that on two different computers.  Is this something that is possible?

**Comment by markus101** [comment]
> ## Support / Questions
>Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

Please use the forums for support and other questions and read the FAQ for some information on this exact issue.
