### ISSUE TITLE
Shows no longer updating since V2 of the TVDB website went live.

### ISSUE THREAD

**Issue by MrsAngelD** [Sonarr/Sonarr#2546]
I just wanted to let the powers that be over here know that ever since the TVDB launched the new version of their website, series are no longer updating with new episode information, I'm not sure if it is on their end or because someone on Sonarrs ends needs updated/changed.

**Comment by M0UL** [comment]
there are problems with thetvdb api. with it is causing the shows not updating.

**Comment by cagenuts** [comment]
I can't add any new shows (new as in newly released) either via the name or via the tvdb: ID.

**Comment by scottc439** [comment]
Any knowledge of workarounds (update Sonarr) or is there another Issue thread we should be following (close this and follow other reported issue)?

**Comment by M0UL** [comment]
just wait til the tvdb api gets fixed.  
latest info can be found here: https://www.reddit.com/r/sonarr/comments/8hob16/known_issue_thetvdb_series_metadata_not_being/

**Comment by cagenuts** [comment]
Thanks MOUL.

**Comment by Taloth** [comment]
Afaik the issues have been resolved and most shows updated. If there are remaining out of date shows, then they need to be retriggered via thetvdb by simply saving an unmodified episode.
