### ISSUE TITLE
[Feature request] Override option during a catch

### ISSUE THREAD

**Issue by Jorman** [Sonarr/Sonarr#2547]
Hi sometimes happen that:
I already have an episode downloaded from sonarr, for example
show S03E09 (sdtv)
Then sonarr after some time find only
show S03E09-10 (sdtv or higher)
The cutoff is set to sdtv
maybe the releaser is changed, I don't know why, but happen

Or happen that:
I already have an episode downloaded from sonarr, for example
show S03E01 (sdtv)
Then sonarr after some time find only
show S03 full season (sdtv or higher)
The cutoff is set to sdtv
in this case happen that one guy make a rel then a group make a full season rel, also this is happen for me

So, in both cases Sonarr don't download the release because there's already a show, right?

The idea is quite simple, if I activate an override, Sonarr will download anyway the release only if the new rel help to improve the number of episode/quality for the season, even if an episode is not wanted, can be excluded from import process and import only the wanted one.

Is that so stupid? or can be an option to develop inside Sonarr?

Jo

**Comment by markus101** [comment]
That's what manual search is for. There is an issue for manual search for seasons already open.

**Comment by Jorman** [comment]
You right.
Personally I think that the commodity of Sonarr and all automatic programs in fact is the automatic way behind the logic of the program itself.

Little ot start
For example can be quite cool a notification on error, so if a download complete was not imported due some reason (the classic yellow badge on download tab), Sonarr send a notification (if configured) to the user to say that must check manually the problem, but is only my opinion
Little ot end

Sonarr already decide what download and what don't, there's a logic behind, the problem is the releaser, in some case the releasers are crazy, like 3 episodes in an single rel and so on.
Became quite long check what release can be "forced" with a manual search, due to different situation like I said, 2 or more episode but one already downloaded or an episode already present but a full season are found. So if one have a lot of tv show in library, that is log, but like always is my personal thought.

The bypass idea is only for the same or major quality. If you think that is not a good option to add, don't do that.

All is only to speak and give my simple contribution, even with only some ideas

Thank you

J
