### ISSUE TITLE
Sonarr "upgrades" season 1 of 3% with 3-Gatsu no Lion

### ISSUE THREAD

**Issue by MrTimscampi** [Sonarr/Sonarr#2550]
### System Information/Logs

**Sonarr Version:** 2.0.0.5163

**Operating System:** Running in Docker on Ubuntu 16.04

**.net Framework (Windows) or mono (macOS/Linux) Version:** 5.10.1.20

**Link to Log Files (debug or trace):** n/a

**Browser (for UI bugs):** n/a

### Other Information

Woke up this morning to a torrent I didn't ask for being in my client. After investigation, Sonarr saw an upload for the anime 3-Gatsu no Lion (HEVC 1080p BluRay) and thought it would be a good upgrade for the show 3% (H.264 1080p Web-DL).

Obviously, it's not the same show, so it's not a good upgrade.  
Setting a different profile without Blu-Ray would work, but I'd like to upgrade to Blu-Ray if it eventually comes out.

**Comment by markus101** [comment]
At the very minimum we're going to need the release name(s) that Sonarr grabbed, but without debug logs it's hard to say why it happened exactly.

**Comment by MrTimscampi** [comment]
Debug logs were unfortunately not enabled at that time. I can try to reproduce by deleting the season and hoping for it to upgrade again, if that can help you track down the issue.

Release for 3-Gatsu no Lion was "3-gatsu no Lion [BD 1080p HEVC AAC]" and came from Jackett (with Animebytes)
The release for 3% (that was "upgraded") was 3.Percent.S01.1080p.WEBRip.X264-DEFLATE, coming from BTN.

**Comment by markus101** [comment]
Was there a different release name on the RSS feed? That name doesn't contain any season or episode information and isn't parseable by Sonarr in my tests.

**Comment by MrTimscampi** [comment]
Jackett sends it to Sonarr as this (Both are the same releases, duplicates are enabled on my end to fix a few shows Sonarr didn't find without it):

[CTR] 3-​gatsu no Lion S01 [Blu-​ray][MKV][h265 10-​bit][1080p][FLAC 2.​0][Dual Audio]
[CTR] 3月のライオン S01 [Blu-​ray][MKV][h265 10-​bit][1080p][FLAC 2.​0][Dual Audio]

**Comment by markus101** [comment]
Neither of those releases are parsed and linked to 3%. They both parse successfully though. If a release with either of those names were linked to 3% your indexer incorrectly linked the release to the wrong series and passed that information to Sonarr (TVDB ID for example).

Closing this out since it's not an issue with the release name, but possibly with a the release information from the indexer and we don't have the information from logs to diagnose it at this time.
