### ISSUE TITLE
build.sh uses the deprecated xbuild tool for Mono builds

### ISSUE THREAD

**Issue by talbenari1** [Sonarr/Sonarr#2553]
Just realized that as of Mono v5 from May 2017, the `xbuild` tool has been deprecated in favor of the now cross-platform `msbuild` and will be removed in future updates of Mono. See [the release notes for v5](https://www.mono-project.com/docs/about-mono/releases/5.0.0/#msbuild) for info about this. Sonarr should be using `msbuild` for both .NET and Mono builds.

**Comment by markus101** [comment]
Done in https://github.com/Sonarr/Sonarr/pull/3464
