### ISSUE TITLE
qBittorrent v4.1.0 integration broken

### ISSUE THREAD

**Issue by DarkSupremo** [Sonarr/Sonarr#2555]
## Bug Report

**Sonarr Version:**
2.0.0.5163

**Operating System:**
Windows 10 Build 1709

**.net Framework (Windows) or mono (macOS/Linux) Version:**
4.7.1

**Link to Log Files (debug or trace):**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/1986175/sonarr.trace.txt)

### Additional Information

After updating to qBittorrent v4.1.0 the integration with sonarr was broken, that version had changes to the WebAPI: https://www.qbittorrent.org/news.php

The Download Clients test is failing with that error:
`Failed to get the list of torrents: JSON integer 18446744073709474000 is too large or small for an Int64. Path '[1].eta', line 1, position 1379.`

**Comment by markus101** [comment]
That QBit bug has been around for a while, fixed recently in https://github.com/Sonarr/Sonarr/commit/03997e2a0d3c1418ed4723d839385e5a3fbf000f

**Comment by DarkSupremo** [comment]
Any idea when it will be added to develop version at least? switched to develop branch but was able to grab the 2.0.0.5200 version, that did not include this fix
