### ISSUE TITLE
Bug - Series Folder format {Series TitleThe} breaks recognition of episode of "The 100"

### ISSUE THREAD

**Issue by distinguished-git** [Sonarr/Sonarr#2557]
### System Information/Logs

**Sonarr Version:** 
2.0.0.5163

**Operating System:**
win10

**.net Framework (Windows) or mono (macOS/Linux) Version:**
3.5

**Link to Log Files (debug or trace):**
>>>
  | ExistingExtraFileService | Found 0 extra files | 06:07
  | ExistingOtherExtraImporter | Found 0 existing other extra files | 06:07
  | ExistingSubtitleImporter | Found 0 existing subtitle files | 06:07
  | ExistingMetadataImporter | Found 0 existing metadata files | 06:07
  | DiskScanService | Completed scanning disk for The 100 | 06:07
  | DiskScanService | Scanning disk for The 100 | 06:07
  | RefreshEpisodeService | Finished episode refresh for series: [268592][The 100]. | 06:07
  | RefreshEpisodeService | Starting episode info refresh for: [268592][The 100] | 06:07
  | RefreshSeriesService | Updating Info for The 100 | 06:07
  | SceneMappingService | Updating Scene mappings | 06:07

**Browser (for UI bugs):**
Chrome

### Additional Information
Episodes were originally moved to directory "100, The" by sonarr, but sonarr no longer recognizes them. It erroneously says I have 0 episodes. 

Attempting a manual import on the directory gives the error "Unknown series" for each and every episode. 

Sample episode name: The 100 - S01E02 - Earth Skills HDTV-1080p AVC DTS [EN+FR+ES+PT+DA+FI+NB+SV].mkv

Naming formats in use:

Standard Episode Format 
{Series Title} - S{season:00}E{episode:00} - {Episode Title} {Quality Full} {MediaInfo Full}

Daily Episode Format
{Series Title} - S{season:00}E{episode:00} - {Episode Title} {Quality Full} {MediaInfo Full}

Anime Episode Format
{Series Title} - S{season:00}E{episode:00} - {Episode Title} {Quality Full} {MediaInfo Simple}

Series Folder Format
{Series TitleThe}

**Comment by Taloth** [comment]
Did you  move the files yourself and _also_ updated the series folder in Sonarr? Please note that the Series Folder Format only applies to new additions, not existing shows.

**Comment by markus101** [comment]
@Taloth this is related to the square brackets around the language codes at the end, it's picking it up as anime. This is covered by https://github.com/Sonarr/Sonarr/issues/457

**Comment by Taloth** [comment]
If that's the case, then lets strip out `\[[A-Z]{2}(?:+[A-Z]{2})*\]` then, fairly strict regex and trivial change, and the advanced parser is not going to be there anytime soon.
