### ISSUE TITLE
Miscategorizes 1440p releases as 480p

### ISSUE THREAD

**Issue by distinguished-git** [Sonarr/Sonarr#2558]
Sonarr Version:
2.0.0.5163

Operating System:
win10

.net Framework (Windows) or mono (macOS/Linux) Version:
3.5

Browser (for UI bugs):
Chrome

Additional Information
I've seen this behavior for other shows that I've downloaded in 1440p, like All Wrong, but here is an example from the History tab under Played > Played - 1x10 - Secrets

  | Source Title > Played.S01E08.Pro.Gamer.1440p.BKPL.WEB-DL.H.264-LiGHT
  | Quality > WEBDL-480p
  | Date > Yesterday

**Comment by markus101** [comment]
We can drop these into WEB-DL 1080p, though that's not really correct, but given there is a very limited number of releases in 1440p resolution and it's limited to WEB releases we do not have plans to add a new quality for such a limited number of releases that most users won't even see.
