### ISSUE TITLE
Failed to save media management settings

### ISSUE THREAD

**Issue by kissgyorgy** [Sonarr/Sonarr#2560]
## Bug Report
When
1. Navigate to Settings / Media Management
2. click Show advanced Settings
3. Turn "Skip Free Space Check" to "Yes"
4. The error message "Failed to save media management settings" shows at the bottom and nothing happens.

Here is the request payload:
```json
{
    "autoUnmonitorPreviouslyDownloadedEpisodes": false,
    "recycleBin": "",
    "autoDownloadPropers": true,
    "createEmptySeriesFolders": false,
    "deleteEmptyFolders": false,
    "fileDate": "none",
    "setPermissionsLinux": false,
    "fileChmod": "0644",
    "folderChmod": "0755",
    "chownUser": "",
    "chownGroup": "",
    "skipFreeSpaceCheckWhenImporting": true,
    "copyUsingHardlinks": true,
    "importExtraFiles": false,
    "extraFileExtensions": "srt",
    "enableMediaInfo": true,
    "id": 1
}
```
Request URL: http://\<my ip\>:8989/api/config/mediamanagement
The request method is PUT, the server response is an empty 500.

### System Information/Logs
No error in logs at all:
```
máj 11 22:20:44 capeti mono[31153]: [Info] Bootstrap: Starting Sonarr - /opt/NzbDrone/NzbDrone.exe - Version 2.0.0.5203
máj 11 22:20:44 capeti mono[31153]: [Info] Router: Application mode: Interactive
máj 11 22:20:44 capeti mono[31153]: [Info] MigrationLogger: *** Migrating data source=/srv/sonarr/.config/NzbDrone/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
máj 11 22:20:44 capeti mono[31153]: [Info] MigrationLogger: *** Migrating data source=/srv/sonarr/.config/NzbDrone/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
máj 11 22:20:44 capeti mono[31153]: [Info] OwinHostController: Listening on the following URLs:
máj 11 22:20:44 capeti mono[31153]: [Info] OwinHostController:   http://*:8989/
máj 11 22:20:44 capeti mono[31153]: [Info] NancyBootstrapper: Starting Web Server
máj 11 22:20:45 capeti mono[31153]: [Warn] MonoDebugCheck: Mono is not running with --debug switch
máj 11 22:26:15 capeti mono[31153]: [Info] RssSyncService: Starting RSS Sync
máj 11 22:26:15 capeti mono[31153]: [Warn] FetchAndParseRssService: No available indexers. check your configuration.
máj 11 22:26:15 capeti mono[31153]: [Info] DownloadDecisionMaker: No results found
máj 11 22:26:15 capeti mono[31153]: [Info] RssSyncService: RSS Sync Completed. Reports found: 0, Reports grabbed: 0
máj 11 22:41:16 capeti mono[31153]: [Info] RssSyncService: Starting RSS Sync
máj 11 22:41:16 capeti mono[31153]: [Warn] FetchAndParseRssService: No available indexers. check your configuration.
máj 11 22:41:16 capeti mono[31153]: [Info] DownloadDecisionMaker: No results found
máj 11 22:41:16 capeti mono[31153]: [Info] RssSyncService: RSS Sync Completed. Reports found: 0, Reports grabbed: 0
```

**Sonarr Version:** 2.0.0.5203 from develop branch, but I tried the stable branch before with the same error.

**Operating System:** Ubuntu 16.04.4

**.net Framework (Windows) or mono (macOS/Linux) Version:** 4.2.3 (default from sonarr repo)

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):** Chrome and Firefox also

### Additional Information
My original problem is that Sonarr reports that is no empty space for a ZFS mount point, so I read I need to "Skip Free Space Check" and I wasn't be able to add any TV Show or save anything.  
The other thing I read that symlinks might be the problem so I moved the home directory to an empty directory with no symlinks, whatsoever.   
I tried to run it with different users, different home settings, from systemd service and manually, but I have no other ideas.  
The file permissions are fine.

**Comment by markus101** [comment]
What do the debug/trace logs show?

**Comment by kissgyorgy** [comment]
Nothing interesting, everything seems to be fine. Here is the FULL log: 
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/1996846/sonarr.txt)

**Comment by markus101** [comment]
Logging settings are saved separately and if they're not saving, you can enable it directly in the config file.

**Comment by kissgyorgy** [comment]
It would be actually fine if I could manually edit the configuration XML, but I did not find any documentation or tutorial about it.

**Comment by markus101** [comment]
Right in the Log Files wiki page: https://github.com/Sonarr/Sonarr/wiki/Log-Files

**Comment by kissgyorgy** [comment]
I restarted the systemd service, clicked the button, got the 500 response and the error message again, but I see no sign of it in the logs:
[sonarr (1).txt](https://github.com/Sonarr/Sonarr/files/1996860/sonarr.1.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/1996861/sonarr.trace.txt)
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/1996862/sonarr.debug.txt)

**Comment by markus101** [comment]
Can you grab the headers from the response as well?

**Comment by kissgyorgy** [comment]
This warning is strange also: 
`Warn|MonoDebugCheck|Mono is not running with --debug switch`
My systemd line:
`ExecStart=/usr/bin/mono --debug /opt/NzbDrone/NzbDrone.exe -nobrowser`

**Comment by kissgyorgy** [comment]
Ok, I updated mono to the stable release 5.12.0.226 and everything seems to be working fine. I can add Shows, save configuration. The warning is still there however:
`Mono is not running with --debug switch`
Thanks for the help!

**Comment by markus101** [comment]
> What is the XML node for "Skip Free Space Check"? I tried SkipFreeSpaceCheckWhenImporting but it doesn't seem to work.

It's not part of the config file, it's within the DB. The config only contains settings that are required before Sonarr starts.

> Warn|MonoDebugCheck|Mono is not running with --debug switch

Yeah, not sure what the issue is with that, but it's not working as expected.

Glad to hear it's working after the upgrade.
