### ISSUE TITLE
Still having issues with particular show since TVDB update

### ISSUE THREAD

**Issue by MrsAngelD** [Sonarr/Sonarr#2562]
I'm still having serious errors with one show in particular, while the data on the TVDB is correct sonarr seems to not be picking up corrections no matter how many times I refresh the show

https://www.thetvdb.com/series/the-young-turks/seasons/14 has the correct information listed however sonarr does not.

Version
2.0.0.5163
Mono Version
5.12.0.226

![sonarr-tyt](https://user-images.githubusercontent.com/2045159/39953328-caedc782-5577-11e8-8817-780f7e1baf39.png)
![thetvdb-tyt](https://user-images.githubusercontent.com/2045159/39953329-cafcb9fe-5577-11e8-8cb5-e7c338eba2e8.png)

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/1997268/sonarr.txt)

**Comment by Taloth** [comment]
I checked, it looks fine to me. Please note that changed on thetvdb takes between 15-60 min to propagate through the caches.

**Comment by Taloth** [comment]
Then it's something else coz I see this:

![image](https://user-images.githubusercontent.com/6383890/39961444-519e84e2-5636-11e8-9e73-f8bf352f1659.png)
