### ISSUE TITLE
qBittorrent client exception: initial state failed (HTTP error 400: resume BadRequest)

### ISSUE THREAD

**Issue by nistorj** [Sonarr/Sonarr#2565]
### System Information/Logs

Sonarr Version: 2.0.0.5163
Operating System: CentOS 7
mono (macOS/Linux) Version: 5.12.0.233 (from Mono repo)
Link to Log Files (debug or trace): https://pastebin.com/8NH1wMBk
Browser (for UI bugs): N/A

### Additional Information
The issue in short is that it appears that Sonarr is throwing a WARN message regarding communication to the qBittorrent web client due to a command not existing:
18-5-15 16:02:05.6|Warn|HttpClient|HTTP Error - Res: [POST] http://127.0.0.1:8080/command/resume: 400.BadRequest

This only happens at the start-up of a new torrent being inserted into qbt. It then goes on to error with:
[v2.0.0.5163] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://127.0.0.1:8080/command/resume]

Regarding the settings part it seems like a generic message to tell people to check their settings however operationally there is no impact to how the system is running, it's more of a benign error message.

I checked around but can't seem to find ayone with the same issue.

Thank you,

**Comment by nistorj** [comment]
Hi Markus,

Silly me didn't realize I didn't put in the trace logs,  here's a better sample I hope: https://pastebin.mozilla.org/9085527. The only thing I could find at first glance in the trace logs was that the resume request was being sent with all uppercase characters whereas the other hashes listed were lower case. (See line 7 and line 11)

qBt version is 4.1.0 running in daemon mode.  There really isn't much in terms of logging on qbt by the looks of it.  I restarted it in the foreground instead of background to grab any data but there isn't anything to show for it.  There doesn't seem to be a flag to enable debugging either.

I did find some documentation around this API which is here: https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#resume-torrents

**Comment by nistorj** [comment]
Thanks very much Markus, much appreciated!

**Comment by nistorj** [comment]
Here's the fix which will be pulled into QBT 4.1.1  and is currently in master, tested and works:

https://github.com/qbittorrent/qBittorrent/commit/88f2a66aacedecf2eb0c8c46d7ef9c9ce05ddbd7

**Comment by sbeaudoin** [comment]
By the way, it seems to works on sonarr.
