### ISSUE TITLE
System.Xml.XmlException: Syntax Error after '<!' characters. http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd Line 1, position 3.

### ISSUE THREAD

**Issue by chrisshiplet** [Sonarr/Sonarr#2575]
**Describe the bug**
I believe this is the same bug as #2554 and this thread: https://forums.sonarr.tv/t/xmlexception-syntax-error/18599

As far as I can tell this happens on both my indexers (omgwtfnzbs and nzbgeek). I've tried upgrading Mono to 5.2 which didn't help, and I've tried a completely fresh installation with my backed up config and database then upgrading Mono again, which also didn't help. I can provide any more information that would be helpful but I'm out of ideas on this one. I've tried everything mentioned in the two threads linked above.

**Screenshots**
<img width="238" alt="screen shot 2018-05-19 at 9 22 07 pm" src="https://user-images.githubusercontent.com/933501/40275645-c33ab624-5baa-11e8-8394-d306083608df.png">

**Logs**
Trace log: https://pastebin.com/VLGitdem (relevant stacktrace on line 563)
Sample NZB: https://pastebin.com/rtDq6ZWb

**Additional context**
 - OS: FreeNAS-11.1-U4
 - Version: 2.0.0.5163
 - Mono Version: First experienced problem with 3.10, upgraded to 5.2 and restarted jail hosting Sonarr and problem remains

**Comment by markus101** [comment]
Which version of mono does Sonarr say it's running under on System: Info?

**Comment by chrisshiplet** [comment]
Thanks for responding so quick!

Ha, indeed it is... I've been on that screen a lot this weekend and never even noticed that version number there. I did a little bit more digging after your message, and got it straightened out.

It appears that the Sonarr port for FreeNAS installs its own mono binary in `/usr/pbi/sonarr-amd64/bin`, while the one installed by `pkg install mono` lives in `/usr/local/bin`, so I did the following:

`mv /usr/pbi/sonarr-amd64/bin/mono /usr/pbi/sonarr-amd64/bin/mono-old`
`ln -s /usr/local/bin/mono /usr/pbi/sonarr-amd64/bin/mono`
`service sonarr restart`

and everything works great now. I'm not 100% confident it's going to survive an update yet... but I suppose this is more of an issue with the FreeNAS plugin for Sonarr shipping an outdated version of Mono, rather than Sonarr itself. I'll close this for now, but I hope it'll be helpful for someone searching this in the future. I'll have to investigate seeing if whoever is responsible for the FreeNAS package can update the Mono dependency.

**Comment by Technofrikus** [comment]
I have the exact same problem, but doing the above does not help. Mono is up to date, but Sonarr uses its own older mono. Linking the new mono in, as suggested by chrisshiplet above, results in Sonarr not starting anymore:

```
18-6-12 20:52:28.2|Info|Bootstrap|Starting Sonarr - /usr/pbi/sonarr-amd64/share/sonarr/NzbDrone.exe - Version 2.0.0.5163
18-6-12 20:52:28.6|Info|AppFolderInfo|Data directory is being overridden to [/var/db/sonarr]
18-6-12 20:52:28.7|Info|Router|Application mode: Interactive
18-6-12 20:52:28.8|Info|MigrationLogger|*** Migrating data source=/var/db/sonarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-6-12 20:52:28.9|Info|MigrationLogger|*** Migrating data source=/var/db/sonarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
```

I also tried changing the procname in the start up script to the new location of mono, as suggested in the other thread, linked above. But same error :(

**Comment by itsflashpoint** [comment]
@chrisshiplet Sonarr does not seem to start at all after this. I am not sure where FreeNAS keeps Sonarr Logs by default.

For anyone who is not sure on how to revert back to old settings:

```
rm -rf mono
mv /usr/pbi/sonarr-amd64/bin/mono-old /usr/pbi/sonarr-amd64/bin/mono
```

**Comment by Technofrikus** [comment]
Thanks for the help Flashpoint. Though, I dont see the difference between your solution and the one from Chris. Arent you doing the same except deleting the original folder instead of renaming it? Did you do something additionally to get Sonarr to start up again? For me it still wont startup.

**Comment by p-sebastian** [comment]
based on a few answers here and there. this is what worked for me https://forums.sonarr.tv/t/xmlexception-syntax-error/18599/19

if you did:
```
pkg update
pkg upgrade
```
chances are you updated sqlite3, which breaks mono for some reason, so you need to downgrade it.
```
pkg delete -f sqlite3
fetch "http://pkg.freebsd.org/freebsd:11:x86:64/release_0/All/sqlite3-3.13.0.txz"  
pkg add sqlite3-3.13.0.txz
pkg lock sqlite3
```
Then install mono and change the dir which sonarr looks for it:
```
pkg install mono
cat /usr/local/etc/rc.d/sonarr | grep mono
```
the last command will show where sonarr is looking for mono
edit the "/usr/local/etc/rc.d/sonarr" and change

> procname="/usr/pbi/sonarr-amd64/bin/mono"
to 
> procname="/usr/local/bin/mono"

Then restart the jail

**Comment by dcy85** [comment]
> @chrisshiplet Sonarr does not seem to start at all after this. I am not sure where FreeNAS keeps Sonarr Logs by default.
> 
> For anyone who is not sure on how to revert back to old settings:
> 
> **MAKE SURE THAT YOU'RE IN YOUR SONARR JAIL**
> 
> jls
> jexec # tcsh
> 
> ```
> rm -rf /usr/pbi/sonarr-amd64/bin/mono
> mv /usr/pbi/sonarr-amd64/bin/mono-old /usr/pbi/sonarr-amd64/bin/mono
> ```
> Edit:
> 
> Seemed to work after doing:
> 
> ```
> pkg upgrade
> pkg update
> pkg install mono
> rm -rf /usr/pbi/sonarr-amd64/bin/mono (you can back this up if you'd like. Look @chrisshiplet post)
> ln -s /usr/local/bin/mono /usr/pbi/sonarr-amd64/bin/mono
> ```

I no nothing about linux, but this Worked perfectly!  Thanks.

Since you guys are all experts on these, quick question;

I'm running freeNAS (FreeNAS-9.10.2-U6) and for some reason Sonar is not showing under the installed plugins section for a while now, any ideas?

**Comment by pklifter** [comment]
I really hope you guys can help me. I've been trying everything to resolve this issue but still cannot get it fixed.

My error is 
Request Failed. POST /api/release: Syntax Error after '<!' characters. http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd Line 1, position 3.

Sonarr - 2.0.0.5338, sonarr reports mono is 3.10.0
Freenas - 11.1-U7

cat /usr/local/etc/rc.d/sonarr | grep mono
returns the following 
procname="/usr/local/bin/mono"

From what I can tell I've done what everyone is saying has resolved it for them but still I get this error but only on some TV shows.
