### ISSUE TITLE
Sonarr not detecting and parsing release when Episode is EP instead of E

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#2578]
Many Asian shows have one season only so are released with Episode number only. When a release group uses E01 it is detected and parsed by sonarr correctly. But when a group release as EP01 sonar is unable to parse it. Example.
Sonarr is unable to parse
Love Rerun EP06 720p x265 AOZ.mp4
Sonarr is able to parse correctly
Love Rerun E06 720p x265 AOZ.mp4

**Comment by markus101** [comment]
Please provide all the information in the template when opening an issue.

This example parses fine though.

**Comment by Dnkhatri** [comment]
HI sorry my mistake the release name is actually Love Rerun 2018 EP01 in the website but the actual file is Love Rerun EP01. Though it has already been added to alternate name google drive file it is still not detecting. Though this show will end in a few weeks so I am not really that bothered by it. 
![capture](https://user-images.githubusercontent.com/7855682/40294015-36490ab0-5d06-11e8-9cc9-d37d32ac01c6.PNG)
That the error I am getting in search
Release Rejected
Unable to parse episodes from release name

**Comment by markus101** [comment]
That makes all the difference. Found the issue and pushed a fix.
