### ISSUE TITLE
Activity Page, sort by download client, and add a multi-select button

### ISSUE THREAD

**Issue by deathbybandaid** [Sonarr/Sonarr#2581]
I think the Activity Pages Queue tab could be separated into sections for each download client.

This would be easier to view what is being downloaded by which client.

Additionally, and the original idea I had for the request, is for the ability to "Remove From Download Client" multiple at a time. This would benefit greatly from the change requested above, as you might want to clear downloads for sabnzbd but not deluge.

**Comment by markus101** [comment]
Sorting by protocol/download client will be possible in v3. Separate queues for different protocols/clients is not something we're considering at this time.
