### ISSUE TITLE
Different Deluge category depending on Series type.

### ISSUE THREAD

**Issue by aktersnurra95** [Sonarr/Sonarr#2587]
I would like to have Sonarr set a different category in Deluge depending on what Series Type a series is set to.
I recently got into using Sonarr for my library management and the setup I have ended up with, which works the best for my Plex setup, is to let Sonarr fetch torrents and add them to Deluge, then let Deluge handle the rest.
After completion Deluge uses the Filebot plugin to rename the episode and copy it to the right folder, then it will remove torrent and data after seeding for x time/ratio.

My issue that I currently have is that I use different naming rules for anime vs series but I have no certain way of differentiating them from each other in Deluge. I currently filter them via trackers, but since I use a fair amount of different indexers I end up having different trackers every once in a while, which then defaults it to rename as a series. (so my anime episodes get thrown into my series library)

What I would appreciate having is an option to set the category label, in the download client options for Deluge, separately for Standard series and Anime (and daily just for good measure).

I hope that this is something that could be implemented and I thank you all for an otherwise outstanding software!

**Comment by markus101** [comment]
No plans for different categories based on the series type at this time.
