### ISSUE TITLE
Add "Add Series" to top navigation bar

### ISSUE THREAD

**Issue by SethGower** [Sonarr/Sonarr#2588]
Would it be possible to add an "Add Series" Button to the navigation bar to match the "Add Movie" button that is in Radarr?
![may25-15 05 44](https://user-images.githubusercontent.com/19225089/40562105-a1dbf6e6-602d-11e8-872c-08d9e69fc44a.png)
![may25-15 05 59](https://user-images.githubusercontent.com/19225089/40562106-a1f1aff4-602d-11e8-8fdc-e409271fabde.png)

**Comment by markus101** [comment]
There will be the ability to search for a new series from the search input in v3.
