### ISSUE TITLE
Sonar not saving settings

### ISSUE THREAD

**Issue by cerickso88** [Sonarr/Sonarr#2590]
Settings are not being saved.  If go to setting -> Download Client...  The page comes up but with old settings.   I change them to the new settings that I want.  Press the SAVE in the upper right.  Then click the TEST button.  It may or may not work (the TEST)...
If I leave this page and come back to it, the page will load showing the saved settings for 1 second or less..  They then change to the older settings on there own.

This happens on multiple forms and makes it very difficult to make the program work properly.

I just downloaded the latest updates from the download site and it still is happening.   Does anyone have any ideas why this is happening to me?   Obviously this can't be happening to others as this is a pretty serious issue.

Thanks,
ce

**Comment by markus101** [comment]
Please open a thread on the forums for support.
