### ISSUE TITLE
Add unmonitor and delete season button in each series page for each season

### ISSUE THREAD

**Issue by morpheus65535** [Sonarr/Sonarr#2591]
**Describe the problem**
I would like to have the ability to unmonitor and delete files on disk for a complete season directly in each season subsection of each series page. When I have watched every episode for a season, I can easily delete it from disk if required.

**Describe any solutions you think might work**
For now, we have to unmonitor the season and go trough the "Modify files for season" button, check each episode checkbox and hit delete button. It's kind of a long process for something that could be achieve with one click and a confirmation dialog box.

**Additional context**
n/a

**Comment by markus101** [comment]
With ignore deleted episodes on, deleting the episodes will unmonitor them, which would be a 4 click process (IIRC). No plans to add a delete button in addition to the manage button.
