### ISSUE TITLE
Request Failed. GET /api/manualimport: Sequence contains more than one element

### ISSUE THREAD

**Issue by PiscisSwimeatus** [Sonarr/Sonarr#2594]
**Describe the bug**
Unable to add files to some series:
Army - Behind the New Frontlines
Cops
Dice
Lockup

All result in Request Failed. GET /api/manualimport: Sequence contains more than one element

**Logs**
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/2057584/sonarr.debug.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/2057585/sonarr.trace.txt)
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/2057586/sonarr.txt)

**System Information**

 - Sonarr Version: 2.0.0.5212
 - Operating System: ubuntu 18.04
 - Mono Version 5.12.0.226

**Comment by markus101** [comment]
Do you have multiple series similarly named (or duplicates in general, somehow)? Sonarr is failing to look up the series by it's clean title which is essentially an all lower-case representation with most characters removed.

Without seeing the contents of the database it's hard to say, but you could check the Sqlite DB for dupes with:
```
SELECT
	CleanTitle,
	GROUP_CONCAT(Id, ',') AS Ids,
	GROUP_CONCAT(TvdbId, ',') AS TVDBIds,
    COUNT(*) RecordsPerGroup
FROM Series
GROUP BY CleanTitle
HAVING COUNT(*) > 1
```

That'll return any duplicates by `CleanTitle` (where this is failing), the ids (internal for your DB), the TVDB IDs and the number of duplicates.

**Comment by PiscisSwimeatus** [comment]
I did have dupes in the database. Which I did not see in the  web interface. I'll clean them up. Thanks!

![image](https://user-images.githubusercontent.com/4976642/40871514-3cabba2a-663d-11e8-8fba-ab298f3f551f.png)

**Comment by gnutix** [comment]
I had the same issue after adding "Star Wars: Clone Wars (2003)" and "Star Wars: The Clone Wars (2008)" TV series. Both had "starwarsclonewars" as "CleanTitle". I had to remove one of them for the manual import to work, which sucks, don't you think ? Especially as it should probably be "starwarsclonewars" and "starwarstheclonewars".
