### ISSUE TITLE
Add the ability to rename files/folders to alternative names

### ISSUE THREAD

**Issue by Deterio** [Sonarr/Sonarr#2597]
Would it be possible to choose between names of series and then Sonarr renames folders/files according to your choice?

E.g. An alternative name of MEGALOBOX is MEGALO BOX. When you choose MEGALO BOX instead of MEGALOBOX and you click on organize, the files get renamed. 

"MEGALOBOX\MEGALOBOX - S01E01.mp4" becomes "MEGALO BOX\MEGALO BOX - S01E01.mp4" for example.

**Comment by markus101** [comment]
Sonarr only uses the official title when renaming. We do not have plans to allow choosing an alternate titles for renaming, at least at this time.
