### ISSUE TITLE
Download Client QBittorrent - Initial State "Pause" does not work

### ISSUE THREAD

**Issue by joakimlemb** [Sonarr/Sonarr#2599]
**Describe the bug**
Download Client QBittorrent - Initial State "Pause" does not work, torrent is always added in "Start" state.

**System Information**

 - Sonarr Version: 2.0.0.5163
 - Operating System: Debian 9.4 (inside docker container: https://hub.docker.com/r/linuxserver/sonarr/ )

**Additional context**
Both the "Start" and "Forced Start" states work, it's only the Pause state that does not work.

**Comment by markus101** [comment]
Please link to the relevant debug logs as requested.

**Comment by travisboss** [comment]
I've had this happen with deluge also, if I do not set the pause option within Sonarr the torrent will start even though deluge is set to start torrents paused. I credit this to Sonarr is taking over my torrent client.  Try checking the add torrent paused option within Sonarr to see if that works.

**Comment by joakimlemb** [comment]
@markus101 sorry for the late reply, but seems you already fixed it before I managed to post debug logs. Thanks.
