### ISSUE TITLE
Animetosho via NZBhydra2

### ISSUE THREAD

**Issue by drakex90** [Sonarr/Sonarr#2600]
**Describe the bug**
While using Animetosho newznab indexer via Nzbhydra2 not able to download the NZB getting the following fatal error when am using the Animetosho newznab indexer directly there are no issues it only seems to be coming when used via Nzbhydra2.

**Error**
Request Failed. POST /api/release: Reference to undeclared entity 'raquo'. Line 4, position 585.

**Logs**
https://pst.moe/paste/wbsqfw

**System Information**

 - Sonarr Version: 2.0.0.5163
 - Operating System: Windows 8.1
 - .net Framework : 4.7.1

**Comment by markus101** [comment]
Without seeing the XML, my guess is Nzbhydra2 sending back invalid XML, such as this stackoverflow post https://stackoverflow.com/a/281703/882971 if that's the case then Nzbhydra2 needs to send valid XML. That coupled with the fact it works when Sonarr hits the indexer directly is a pretty good indication it's something Nzbhydra2 is doing.

Take a look at the XML and check for `&raquo` in there.

Closing as there isn't anything actionable given the information, we can re-open if there is a bug to fix on our side.
