### ISSUE TITLE
Lock by Indexer

### ISSUE THREAD

**Issue by legewiel** [Sonarr/Sonarr#2603]
**Describe the problem**
Sometimes when I download an specific series, I don't want it to come from a non trusted indexer, for example if i want to download an anime, I would prefer that It came from my anime indexers and not other general indexers, but still need to keep it around for other series. So I would love to lock some series in specific indexers.

**Describe any solutions you think might work**
Maybe the indexers could also become Tags, so i would add that tag to that series and it would only download from there.

**Additional context**
I tried locking by using the subber group name, but someone posted a file using that group name on a fake file in one of this non trusted indexers.

Thank you for your time!

**Comment by markus101** [comment]
Sounds like a dupe of https://github.com/Sonarr/Sonarr/issues/487
