### ISSUE TITLE
Suggestion: Better handling of grab preference via  custom quality definitions or weighted metric tags 

### ISSUE THREAD

**Issue by tastyratz** [Sonarr/Sonarr#2604]
**Describe the problem**
Currently, Sonarr has a rather blind preference of getting the file which has the highest quality for your profile. This ignores other feature or attributes which might otherwise influence your preference.

I might prefer a bluray rip over a webrip, however I would rather have a file tagged with HDR. I also would like a smaller file in H265 instead whenever it's available. 
Finally, I would rather have a file with surround sound instead of stereo but will accept it.

**Describe any solutions you think might work**
*Easiest option
It is possible to rename a quality definition, but I can't assign a tag to a quality. Allowing new quality definitions be easily created from the GUI with a "+" icon and assigning tags to a quality would allow more granular controls. I might allow the file to be bigger only if it's hdr for example, and I would re-order this above. This also means the ability to alter the order of quality definitions.

*Another possible option, less user friendly
Let's say every quality definition and every tag is assigned a metric. If I gave more points to HDR, negative points to stereo, etc. Sonarr might make better choices. This could be universal and downloads would be chosen by score.

**Additional context**
As it exists today, I can only block tags from ever downloading, set delays based on non-preferred tags (without future trumping download capacity), or set a tag universally preferred in a quality profile. This is more of a shotgun approach and won't skip quality definition levels. While easier, it's less powerful at guessing my choices.

**Comment by markus101** [comment]
> *Easiest option
It is possible to rename a quality definition, but I can't assign a tag to a quality. Allowing new quality definitions be easily created from the GUI with a "+" icon and assigning tags to a quality would allow more granular controls. I might allow the file to be bigger only if it's hdr for example, and I would re-order this above. This also means the ability to alter the order of quality definitions.

Easiest in what way?
This would be complicated to implement and hard for most users to understand, it'd be great for the some users, but not most users. Even re-order profiles causes more support questions that we would have guessed initially. We have no plans for custom qualities.

> *Another possible option, less user friendly
Let's say every quality definition and every tag is assigned a metric. If I gave more points to HDR, negative points to stereo, etc. Sonarr might make better choices. This could be universal and downloads would be chosen by score.

This is covered by https://github.com/Sonarr/Sonarr/issues/385
