### ISSUE TITLE
Random refused to connect

### ISSUE THREAD

**Issue by NasKar2** [Sonarr/Sonarr#2605]
**Describe the bug**
At random times when I go to the web page I get
This site can’t be reached
192.168.5.71 refused to connect.
Search Google for 192 168 8989 sonarr
ERR_CONNECTION_REFUSED
I can fix it by restarting the iocage jail

**Screenshots**
None
**Logs**
Link to debug or trace log files.
No error is shown in the logs after restarting the jail

**System Information**

 - Sonarr Version: [e.g. 2.0.0.1] 2.0.0.5163
 - Operating System: [e.g. Windows 10] Freenas 11.1U4
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
 - OS: [e.g. Windows]Windows 10
 - Browser: [e.g. chrome, firefox] Chrome Version 66.0.3359.181 (Official Build) (64-bit)
 - Version: [e.g. 22]

**Additional context**
Add any other context about the problem here. None

**Comment by markus101** [comment]
Please open a thread on the forums for support, if there is an underlying bug we can re-open this GHI, but for now there isn't anything to go on.

This sounds like mono is crashing and nothing is logged. Capturing the standard output and error is the easiest way to determine what may be causing it, but I'm not sure how easy that is with a jail.

Also need to know which mono version you're using, that's very important.
