### ISSUE TITLE
Skyhook failure when using Reverse Proxy

### ISSUE THREAD

**Issue by AcidRaZor** [Sonarr/Sonarr#2606]
I followed the instructions: https://github.com/Sonarr/Sonarr/wiki/Reverse-Proxy

I setup a reverse proxy from my web-facing NGINX server to my Sonarr install hosted on my local network. (https://www.myurl.com/sonarr goes to http://172.20.51.3:8989/sonarr)

When trying to search for a TV series to add, it fails with the following message:

> {
>   "message": "Search for '' failed. Invalid response received from SkyHook.",
>   "description": "NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for '' failed. Invalid response received from SkyHook.\n  at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewSeries (System.String title) [0x00124] in M:\\BuildAgent\\work\\b69c1fe19bfc2c38\\src\\NzbDrone.Core\\MetadataSource\\SkyHook\\SkyHookProxy.cs:103 \n  at NzbDrone.Api.Series.SeriesLookupModule.Search () [0x00000] in M:\\BuildAgent\\work\\b69c1fe19bfc2c38\\src\\NzbDrone.Api\\Series\\SeriesLookupModule.cs:24 \n  at NzbDrone.Api.Series.SeriesLookupModule.<.ctor>b__1_0 (System.Object x) [0x00000] in M:\\BuildAgent\\work\\b69c1fe19bfc2c38\\src\\NzbDrone.Api\\Series\\SeriesLookupModule.cs:18 \n  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 "
> }

Doing a cURL on the server to http://172.20.51.3:8989 yields a valid response, however, through the proxy address, it fails with above.

Here is the cURL (doesn't work):

`curl 'https://www.myurl.com/sonarr/api/series/lookup?term=east' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: order_dir_list_by=1A; resolve_ids=1; session_id=7c42819e9dd1d8597f484b4b27ebab459384de63; filemanager=t3h8pt0gbcogallds8h3rffr6p; _pk_id.1.1864=dbe962689e052a97.1528273781.2.1528284698.1528284698.; _pk_ses.1.1864=*' -H 'Connection: keep-alive' -H 'Referer: https://www.myurl.com/sonarr/addseries' -H 'X-Api-Key: 1ad55ede297e475a85b81d164b5592a1' --compressed`

Here is a working cURL:

`curl 'http://172.20.51.3:8989/sonarr/api/series/lookup?term=east' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: order_dir_list_by=1A; resolve_ids=1; session_id=7c42819e9dd1d8597f484b4b27ebab459384de63; filemanager=t3h8pt0gbcogallds8h3rffr6p; _pk_id.1.1864=dbe962689e052a97.1528273781.2.1528284698.1528284698.; _pk_ses.1.1864=*' -H 'Connection: keep-alive' -H 'Referer: https://www.myurl.com/sonarr/addseries' -H 'X-Api-Key: 1ad55ede297e475a85b81d164b5592a1' --compressed`

The same failure on Radarr happens. So I'm not sure if it's the setup (from above reverse proxy URL) or some other kind of failure.

TIA

**Comment by markus101** [comment]
A reverse proxy doesn't block communications from Sonarr outbound, a proxy or VPN would though.

Please open a thread on the forums for support, which will need to include the requested information, including debug or trace logs.

**Comment by Taloth** [comment]
@AcidRaZor 
> Search for '' failed

Pretty sure the reverse proxy config is causing nginx to strip out the `?term=east` query string part. Thus causing an empty string to be queried.

**Comment by AcidRaZor** [comment]
@Taloth Thanks, that is what I initially checked for as well and tried different configurations. 

As mentioned, according to https://github.com/Sonarr/Sonarr/wiki/Reverse-Proxy this should work, but I also tried 

```
location ~/sonarr(.*)$ {

        proxy_pass http://172.20.51.6:8989/sonarr$1;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host http://172.20.51.6:8989;
        #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header        X-Forwarded-Proto $scheme;
        #proxy_redirect off;
        #proxy_buffering off;
}
```

With no luck. The $1 does pass through the arguments as far as I can see unless I'm being a total idiot and missing something that my decade-old DevOps experience can't solve...

**Comment by Taloth** [comment]
Yesterday I checked the wiki example nginx config myself, worked flawlessly. I'm no nginx expert so I can't comment on your specific config, but i'm pretty sure that $1 doesn't match the query params coz the location does not contain the query string.
