### ISSUE TITLE
Download all seasons from one torrent

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [Sonarr/Sonarr#2608]
**Describe the problem**
Some shows (usually those that have been off the air for a while) will end up with complete torrents containing all episodes of the show. In my experience, Sonarr will download one of these and only extract the first season since the torrent name is something like ...S01-S04.Season.1-4.Complete...

**Describe any solutions you think might work**
While being able to manually search for seasons and possibly whole shows is underway (#266), it would be nice if Sonarr could parse S##-S## and Season#-# as a whole show torrent or even as a partial to download all seasons X-Y.
I put together a [super-basic regex](https://regex101.com/r/aDMWpD/1) to find torrents like this.

**Comment by markus101** [comment]
Sonarr doesn't support multi-season releases. At this time there is no plan to support them.

There is https://github.com/Sonarr/Sonarr/issues/683 already open to prevent grabbing them by mistake.

**Comment by Adrian-at-CrimsonAuzre** [comment]
Ah, didn't know that.
