### ISSUE TITLE
Disable Indexer

### ISSUE THREAD

**Issue by 5ll** [Sonarr/Sonarr#2609]
**Describe the problem**
Indexers can only be deleted not just disabled

**Describe any solutions you think might work**
A "disable"-Feature for an indexer

**Additional context**
As the config of an indexer sometimes involve api-keys and specific urls, it would be nice to be able to just disable an indexer so that you can quickly reactivate them without looking up all the specific information.

**Comment by Thirrian** [comment]
Disable both search and RSS for that indexer...

**Comment by 5ll** [comment]
That was my first thought an I already did that, but it is still being used to source torrent files.

**Comment by markus101** [comment]
Disabling search and RSS for an indexer disables it completely. If asearxh/RSS sync was already started when it was disabled then results could still come back from it.
