### ISSUE TITLE
explicitly specify the indexer for specific profiles

### ISSUE THREAD

**Issue by 5ll** [Sonarr/Sonarr#2610]
**Describe the problem**
Its not possible to control which indexer is being used for a specific profile

**Describe any solutions you think might work**
If it would be possible to assign an indexer to a specific profile one could control which indexer is used for specific profiles and thus content. This feature would also benefit dealing with multiple languages.

**Additional context**
If I have a specific indexer for content in language A and a profile which has set language A as the desired language, it would be good if I could specify that an index is only used for this category, even if sometimes this indexer also has content from language B.
Coming from a torrent-world this would let me control which indexer I use for specific languages and thus control to which indexer I let my traffic go.

**Comment by markus101** [comment]
Covered by https://github.com/Sonarr/Sonarr/issues/487
