### ISSUE TITLE
Free space is 1000x wrong on macOS

### ISSUE THREAD

**Issue by Bluebie** [Sonarr/Sonarr#2611]
I'm using the DownloadedEpisodesScan API to trigger an import. The import fails with this error message in the Sonarr logs:

```
FreeSpaceNotification: Not enough free space (28180480) to import:
/Users/bluebie/Transfers/Sample.S01E01.1080p.VRV.WEB DL.x264.mkv (319745152)
```

The example file "Sample" is 319mb big, and the external usb mounted hard drive I'm trying to import it to has around 28gb free. Sonarr appears to be using different units of measure to test free space than to measure file size, at least on macOS.

**API Request**
```bash
curl "http://localhost:8989/api/command" \
  -d "{\"name\": \"DownloadedEpisodesScan\", \"downloadClientId\": \"9908221234AC9REDACTEDB8DD7D9D25A72FFBF14\", \"path\": \"/Users/bluebie/Transfers/Sample.S01E01.1080p.VRV.WEB DL.x264.mkv\", \"importMode\": \"Move\"}" \
  -X POST --header "X-Api-Key:123redacted"
```

**System Information**

 - Sonarr Version: 2.0.0.5163 - Mar 18 2018
 - Operating System: macOS High Sierra 10.13.5 (17F77)
 - Mono macOS Version: 5.12.0.226
 - Sonarr installed via Homebrew a few days ago
 - Mac is a fresh High Sierra 10.13.5 install without system-level modification aside from installation of homebrew, and via homebrew: sonarr, npm, node, and homebridge

**Comment by markus101** [comment]
Please post the debug logs and link them here as requested.

> FreeSpaceNotification: Not enough free space (28180480) to import:

Nothing in Sonarr is named `FreeSpaceNotification`.

**Comment by Bluebie** [comment]
I haven't been able to reproduce this issue to gather the requested logs. I'm super confused, but it seems to not be reoccurring so hopefully it was cosmic rays. I'll reopen if i'm ever able to discover a reliable way to reproduce.
