### ISSUE TITLE
Sonarr unable to write -RLSGROUP or Media Tags

### ISSUE THREAD

**Issue by jorvi** [Sonarr/Sonarr#2612]
**Describe the bug**
Whenever I manually import a file, Sonarr is properly detecting video codec, audio codec, audio channels and release group name. However, when the time comes to automatically move it to my media folder and rename the file, Sonarr is unable to use the RELEASEGROUP tag and instead writes `Show.S01E01.1080p.BluRay.x264.DTS.5.1-SONARR.mkv`

What's more, I have some old imports laying around that use my old naming convention (without audio information). I have manually renamed these files from `-SONARR` back to `-EXAMPLEGROUP`. When Sonarr renames these old imports, it properly detects the RELEASEGROUP but now it strips out all codec and audio information, resulting in `Show.S01E01.1080p.BluRay.-EXAMPLEGROUP.mkv`

The full renaming convention I use is `'{Series.CleanTitle}.S{season:00}E{episode:00}.{QUALITY.REAL}.{QUALITY.PROPER}.{Quality.Title}.{MediaInfo.VideoCodec}.{MediaInfo.AudioCodec}.{MediaInfo.AudioChannels}-{RELEASE.GROUP}`

**Screenshots**
![screenshot_mediamanagement](https://user-images.githubusercontent.com/6699838/41238973-9d1bd0dc-6d97-11e8-8bec-763f5ff5b6e1.png)

(Note, these files were initially imported with -SONARR but manually renamed by me)
![screen shot 2018-06-11 at 17 17 00](https://user-images.githubusercontent.com/6699838/41241000-27521b4a-6d9c-11e8-824a-eda138638464.png)

**Logs**
https://paste.ee/p/bmt79

**System Information**
 - Sonarr Version: 2.0.0.5220
 - Operating System: Ubuntu Linux 16.04
 - mono (macOS/Linux) Version: 5.12.0

**Comment by Taloth** [comment]
Interesting...

Do you have Analyse video files turned on in Settings->Media Management->File Management? It's an advanced setting that's turned on by default.

**Comment by jorvi** [comment]
No, I have it specifically turned off to reduce stress on the server. When I import from my download folder (with manual import) the video codec, audio codec and audio channel are parsed correctly, its when I tell Sonarr to 'organise' my library that it can't detect those things (and thus enters nothing, which explains the `.-RELEASEGROUP`).

**Comment by Taloth** [comment]
If you rename the file manually, Sonarr loses track of the file and thus the mediainfo it detects during the original import (Because it runs analysis during import for sample detection). It then 'discovers' the new file and doesn't run analysis because you told it not to.

As for it detecting the original releasegroup name, post an example Release Name that it imported (check Episode->History). It only detects a few patterns.

**Comment by Taloth** [comment]
Click in the ? for The Newsroom -ROVERS, copy-paste the details shown in the popover.
It'll show the original filename.

**Comment by jorvi** [comment]
`The.Newsroom.2012.S01.1080p.BluRay.x264-ROVERS[rartv]/The.Newsroom.2012.S01E03.1080p.BluRay.x264-ROVERS.mkv`

**Comment by Taloth** [comment]
and the target filename? just post Name, Source and Imported To. Having all the info means I don't have to guess what I'm looking at.

I'm also not seeing an Grab event in the screenshot above and you mentioned you used manual import, so that's a clue.

**Comment by jorvi** [comment]
Name:
The.Newsroom.2012.S01E03.1080p.BluRay.x264-ROVERS

Source:
/downloads/rutorrent/NasTvTorrent/The Newsroom/The.Newsroom.2012.S01.1080p.BluRay.x264-ROVERS[rartv]/The.Newsroom.2012.S01E03.1080p.BluRay.x264-ROVERS.mkv

Imported To:
/tv/The Newsroom 2012/Season 01/The.Newsroom.2012.S01E03.1080p.BluRay.x264-SONARR.mkv

NasTvTorrent is just a folder I made in /downloads/rutorrent/ where I rsync'd all the TV shows from my NAS to.

**Comment by Taloth** [comment]
@markus101 Manual Import doesn't run Augment coz that happens in GetDecisions.

**Comment by jorvi** [comment]
@Taloth its working properly now, thanks a lot for the quick fix! : )

**Comment by Taloth** [comment]
Awesome, tnx, then we'll be able to finally do a master release :smile:
