### ISSUE TITLE
[Feature Request] Manual move of media

### ISSUE THREAD

**Issue by BobOkisama** [Sonarr/Sonarr#2616]
I know the system already has automated moves, but I would like a way to do a manual move.

Scenario: I have a Requests directory that I fill my requests into. After a certain period of time if I want to keep that show I would like to be able to force a move to a different directory, such as shows and out of requests and into a perm directory. Currently to achieve this, I have to delete the show from sonarr, then manually move the data to the new location, then re-add it to sonarr pointing to that new location.

**Comment by markus101** [comment]
You can use Manual Import on Wanted Missing.

To move a series from one folder to another, move the files and edit the series to point to the new path. There is also this https://github.com/Sonarr/Sonarr/issues/351

**Comment by BobOkisama** [comment]
That does not work for me, when I try to do that, it tries to add that as a root path to the system.

Example if I move Deadpool from /media/requests/deadpool to /media/action/deadpool I will show /media/action/deadpool as a root group now (if it even works) or it will error stating that this is already a root path and you cannot duplicate it.

I think it would be much better to just have the UI allow you to change the default directory and then a move button and the system will move the entire directory for you.

**Comment by markus101** [comment]
I think you should be looking at Radarr, not Sonarr since you're talking about movies...

**Comment by BobOkisama** [comment]
I actually use both, and have the same issue in both. I just recently relocated 10 shows to a different directory and the only way that worked we to delete from sonarr, move,b then readd.

**Comment by markus101** [comment]
Either edit each series or use Series Editor to change the root folder. The only way Sonarr will add a root folder is by selecting a new one when adding a series, using the series editor to add a new one or using import series to add a new one, none of those are what you need to do to move a series.

**Comment by BobOkisama** [comment]
So let me give a path example.
/media/Requests/Walking Dead - old
/media/Tv/Walking Dead - new

If I tried to edit the series and put in new path /media/Tv/Walking Dead it would try to add that as a new root, or error out. If I tried to put it in /media/Tv/ then half the time it would say root already exists, or would in some other way fail. I have a few "new root" paths now in my sonarr because I also see no way to go back and delete ones in the system.

**Comment by markus101** [comment]
> If I tried to edit the series and put in new path /media/Tv/Walking Dead it would try to add that as a new root,

Editing the series' path will not add a new root folder.

Using series editor and choosing a new root folder of `/media/Tv/Walking Dead` would.

> If I tried to put it in /media/Tv/ then half the time it would say root already exists, or would in some other way fail. 

That'd fail because:

1. It's already a root folder
2. It's a parent of a series already (a series folder can't be the parent of a series folder)

**Comment by BobOkisama** [comment]
Doing exactly what you said has lead me to having root folders now such as
/media/Tv/Top GearUK, /media/Tv/Rick and Morty, etc. One of them, Dirty
Jobs, even tried to make /media/Tv/Dirty Jobs/Dirty Jobs when I edited
series and pointed to the current directory it was in.
