### ISSUE TITLE
MediaInfo Library could not be loaded libmediainfo.so.0

### ISSUE THREAD

**Issue by davidfleischmann** [Sonarr/Sonarr#2623]
**Describe the bug**
The following message appears in the health status

**Screenshots**
https://imgur.com/a/hYhI2OP

**System Information**

 - Sonarr Version: 2.0.0.5223
 - Operating System: Qnap 4.3.4
 - OS: MacOS 10.13.5
 - Browser: Chrome
 - Version: 68.0.3440.25 (Official Build) beta (64-bit)

**Additional context**

**Comment by markus101** [comment]
Make sure libmediainfo is available. It may be part of the QSonarr package, but that is not maintained here.
