### ISSUE TITLE
[PARSER] Genius (2017) Unknown Series

### ISSUE THREAD

**Issue by mikafouenski** [Sonarr/Sonarr#2626]
**Describe the bug**
Episode search for Genius (2017) don't match perfectly named episode in automatic and manual search.

**Screenshots**
![screenshot from 2018-06-19 12-39-26](https://user-images.githubusercontent.com/11093325/41594991-90fc89fc-73c5-11e8-8a88-5cbdce50fd93.png)

**System Information**

 - Sonarr Version: 2.0.0.5225
Docker (linuxserver/sonarr@sha256:05062343206a399bd4911199cf5bf8c79354c8699c269522ce258aa058f643ad)

**Additional context**
Search result are provided by jackett via docker (linuxserver/jakett@sha256:c89fdd82da355d4cde6dfe5c6a362ac76ad49eea1614544939f31f7f7c89503f)

**Comment by markus101** [comment]
This is covered in the FAQ, though the lack of year may be problematic.
