### ISSUE TITLE
Sonarr Importing To Wrong Episode

### ISSUE THREAD

**Issue by IsamuDragon** [Sonarr/Sonarr#2628]
Have only seen this with Anime and when importing manually, but when importing a series with an alternative name (as based with XEM) it will import it to the wrong directory.

For example:
`[HorribleSubs] Shokugeki no Soma S3 - 23 [720p].mkv`
which through XEM should import it to S03E23, however it imported it to S01E23, and I had redownload both the original S01E23 and S03E23 files.

Before trying to re-import S01E23, I copied the redownloaded S03E23 and tried manual import again.(Thinking I had accidentally not noticed the S01 in the import screen) It stated S03 in the import screen and still imported to S01.

Edit: Running Win10PRO x64, Sonarr Version 2.0.0.5225 - 18 Jun 2018 
[sonarr.0.txt](https://github.com/Sonarr/Sonarr/files/2117892/sonarr.0.txt)

![Proof that it Imported to S01](https://user-images.githubusercontent.com/464964/41613999-742233f6-73b4-11e8-8beb-849f6c7551c2.png)

**Comment by markus101** [comment]
Please include the information requested when filing a bug report, including version, OS, debug logs (and everything else relevant).

**Comment by IsamuDragon** [comment]
Updated post

**Comment by markus101** [comment]
Related PR has been merged.
