### ISSUE TITLE
Jackett Search Issue

### ISSUE THREAD

**Issue by galacticat** [Sonarr/Sonarr#2629]
**Describe the bug**
I am unable to manually search with a Torznab indexer via jackett configured to use IP Torrents

In particular I tried to manually search for "The Bold Type Season 2 Episode 3" from the UI and it produced the error below.

I can confirm I can manually search directly from Jackett. I can also confirm that Radarr is able to Manually search via Jackett.

**Screenshots**
N/A

**Logs**

https://pastebin.com/mzx1T9mu

**System Information**

 - Sonarr Version: 2.0.0.5225
 - Operating System: Ubuntu 16.04 w/ Docker
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.4.1.6

**UI Bugs:**
N/A

**Additional context**
N/A

**Comment by markus101** [comment]
Looks like your DB is partially corrupt, though it's tough to say exactly what's wrong because the logs are showing `�` and `` characters.

You can run `UPDATE IndexerStatus SET LastRssSyncReleaseInfo = '{}'` in a SQLite editor to clear out the corrupt JSON.

**Comment by galacticat** [comment]
LOL, I was just about to close this. I fixed it by manually running the "Housekeeping" task.
