### ISSUE TITLE
Connections: Filter Series not in Tags

### ISSUE THREAD

**Issue by evertonstz** [Sonarr/Sonarr#2631]
**Describe the problem**
When making Connections you have the option the select certain tags in the "Filter Series Tags" space, with this the connection will work only for the shows that are inside that tag. We can't, tho, set a tag and have the connect run for all shows that aren't in that tag.

**Describe any solutions you think might work**
My proposal is to have is to have a "Filter Series Not in Tags", it's basically the contrary: the connection will run only for that **aren't** in that tag.

**Comment by markus101** [comment]
What's the use case?
Is it only because it's a pain to set tags on multiple series?

**Comment by evertonstz** [comment]
I have a "SRT" tag that I use to set the shows I need subtitles (90% of them), would be easier to have a "not SRT" tag for the 20% of the shows I down need it.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
