### ISSUE TITLE
Disable parser and use torrent name information instead

### ISSUE THREAD

**Issue by ivandelabeldad** [Sonarr/Sonarr#2632]
I've written the last days a Jackett indexer so I can download from a spanish torrent tracker. It's way too tricky, so naming conventions are no followed.

In order to make it Sonarr-compliant I added information like "spanish" at the end, season and episode naming like: s01e02.

The problem is, I have no control over the file downloaded, so I can face names like that:

```
The Handmaids Tale - Temporada 2 [HDTV][Cap.201][Espa�ol Castellano]\TheHandmaidsTale2x01 [www.sometorrentpage.com].avi
```

After the download, I always encounter the same error: **Invalid season or episode**.
I have to import manually every episode selecting both, season and episode number. So the task Sonarr should do (automate downloads) is now manual.

The question is: **Is there a way to use the torrent information to extract season and episode and disable Sonarr parser?**
And if not, what other path would you follow to solve this? (avoiding obviously manual imports)

I'm using Plex as media center, so doesn't matter so much if sonarr rename the episode or don't, Plex is capable of parse them, but should be good at least have them organized by folders or something.

Thank you by your time.

 - Sonarr Version: 2.0.0.5225
 - Operating System: Windows 10 and Ubuntu 17.10 (containerized).

**Comment by markus101** [comment]
Sonarr needs to be able to parse the file name in order to import it and link it to the correct episode in the series.

If the filenames are that poor, then there is nothing Sonarr will be able to do with it. The fact that there is no separation from the series title and the season number in the file name is a problem, it _may_ be possible to improve the parser to capture those, but that also could make things worse in other scenarios.

**Comment by ivandelabeldad** [comment]
Sonarr have information about the episode before. Even when it hasn't been downloaded it shows "Series, Episode (2x01) and Title" in the Queue, so Sonarr have that information.

I know it's way secure and prevent from wrong items to be added to parse the own file after parse the torrent, but in a scenario like this, where it's impossible to guess the naming pattern a **Disable parser** option under advanced settings would be a solution, and let Sonarr trust the information the indexer gave.

**Comment by ivandelabeldad** [comment]
Funny thing. In the file's metadata the name season/episode is separated from the title.

Looks like this:
```
The Handmaids Tale 2x01 [www.sometorrentpage.com]
```

That should be easy to implement, and without drawbacks. Add the metadata title as a fallback if the filename failed.

**Comment by ivandelabeldad** [comment]
Even with the solution above I cannot trust that every episode will have correct metadata, so I will write a script to rename the file after each download extracting the info of your amazing API, that should work like a "Disable parser".
