### ISSUE TITLE
Enhancement: Free space checks are checking the wrong directories, maybe...

### ISSUE THREAD

**Issue by jj-uk** [Sonarr/Sonarr#2633]
**Describe the bug**
The disk space displayed on the System -> Status page is for the following directories:
/downloads
/tv

This is a tricky issue I guess as it's possible to save series' in any directory when the series is added or moved etc by the user.

I'd like to see the Free space for the directories where series' are saved, so if different series are saved in different locations, it should show:

/tv           xxx,xxx,xxxMB
/tvdvd      xxx,xxx,xxxMB
/some/dir   xxx,xxx,xxxMB

Does Sonarr check Free space in the series' destination dir before copying from the download dir? or does it only check the folders listed in the System -> Status page?

**System Information**
 - Sonarr Version: 2.0.0.5225
 - OS: Docker unbder unRAID 6.5,3
 - Mono: 5.12.0.226

**Comment by markus101** [comment]
Are you looking for a enhancement or are you reporting a bug?

You've put enhancement in the title, but used the bug template...

Not really following what you're hoping to see. If there are multiple root folders for series, there should be multiple entries for those.

**Comment by jj-uk** [comment]
All my series are in the following path: /tv/<series_name>

And my System -> Status page shows this:

> Location | Free Space | Total Space
> / | 14.3 GB | 25.0 GB
> /etc/resolv.conf | 14.3 GB | 25.0 GB
> /etc/hostname | 14.3 GB | 25.0 GB
> /etc/hosts | 14.3 GB | 25.0 GB

If you're saying that is should show the location of the series, e.g /tv, then this is a bug.

I wasn't really sure what the System -> Status page was trying to show me. I thought it was just displaying the free disk space of the disk that sonarr is installed upon, not the disk space that the series are stored upon.

**Comment by markus101** [comment]
If Sonarr is able to get the disk space for `/tv` it'll be listed there, my mapped volumes in docker show up there, could be permissions/configuration preventing it from showing up. Please open a thread on the forums with the relevant debug logs to troubleshoot the issue further.
