### ISSUE TITLE
Folders on disk cannot be used again - ever

### ISSUE THREAD

**Issue by lostboy7** [Sonarr/Sonarr#2636]
**Describe the bug**
It is not possible to use or reference a folder that has ever been used or referenced before.  

Reproduce is easy.  Add a TV show series and pick a storage path that the application will accept.  Let it download a few episodes.

Now, remove the TV show, and just for completeness delete the episode files from the disk too.

Now, try to add some new TV show (or select import) and provide this same path to either function (obviously import wont ultimately be successful as all the files were deleted - but thats not the point).  When selecting save, it will reject with the ubiquitous "Path is already configured as a root folder".

It feels as if there is some architectural flaw in the design of how TV show folders are managed judged by the count of Google SERPs on variations of this issue.  I think it would be best to just let users input the exact folder names they want to store series into.  Not as them for some kind of "root" or base path and then calculate folder names based on the series' title or whatever.

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 2.0.0.5228
 - Operating System: Mac OSX Sierra
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.10.1.47

**UI Bugs:**
N/A

**Additional context**
I came across this issue as Sonarr had stored my series in disk paths like:

/Storage/TV Shows/Survivor/Survivor/Season 1

And I want

/Storage/TV Shows/Survivor/Season 1

I hoped simply editing the path name in the series setting "/Storage/TV Shows/Survivor", as would seem logical, would do it.. and then I move the files manually.. but same error.

I then removed the entire "Survivor" series from Sonarr all together.. still could not add it.

I then renamed the /Storage/TV Shows/Survivor whole file hierarchy on disk to "temporary", created a new "Survivor" folder and tried adding series.  Nope.

I then remove the entire /Storage/TV Shows/Survior folder itself and tried adding "/Storage/TV Shows" as the path.  Nope.

I then renamed the "temporary" back to survivor.  Moved the Series x folders into it (eliminating the Survivor/Survivor" duplication and then tried to "import" the series.  Nope.

Right now, I'm looking to see if I can hex edit (or some other editor) the underlying databases to override this problem or perhaps work around it on Linux using symlinks.  But such kludges should not be necessary.

**Comment by lostboy7** [comment]
For fun, and completeness, I just removed all series all together from sonarr.  It now report "You must be new around here, You should add some series." under the series area so it does seem to understand that all series are gone.

Now I try to add Survivor using the various paths indicated in my previous report.. same error.  It should not be possible to be in conflict with an existing 'root' path if there are no series existing anymore!

**Comment by markus101** [comment]
When you import series (or add a new one). You need to pick the root folder, not the path to a single series folder.

You'll want to remove any existing root folders, from the Add Series, Import Existing series modal and add `/Storage/TV Shows/`as the lone root folder.

Open a thread on the forums if you need to troubleshoot further.
