### ISSUE TITLE
More easily monitor/unmonitor episodes to/from "this one"

### ISSUE THREAD

**Issue by jbrains** [Sonarr/Sonarr#2638]
For some series I want to delete old episodes and not have to think about re-downloading them, but right now, to stop monitoring old episodes, I have to select them one by one to mark them `unmonitored`. For a dailiy show, this can be a lot of clicking. 

It would be nice to be able to select an episode and press "Unmonitor every episode before this one" or "Only monitor episodes starting with this one".

**Comment by jbrains** [comment]
I see a workaround now: delete the series (without deleting the files), then add the series back monitoring only Future episodes. Perhaps that provides a relatively quick way to implement this feature? (I haven't looked at the code yet.)

**Comment by markus101** [comment]
You can do the same thing without deleting the series from Season Pass.
