### ISSUE TITLE
Manual search results don't appear

### ISSUE THREAD

**Issue by antigravity83** [Sonarr/Sonarr#2642]
Manual serach results never appear - Only moving circles. 

I have deleted all cache from my browser, and also disabled my ad-blocker. Don't have any issues picking up content for "Auto Search". Radarr manual search works fine with the same indexers, Jackett etc.

In this example I tried to manually search for TV Show 19-2 (2014) S01E01. 

**Sonarr Version:**
2.0.0.5228

**Operating System:**
Linux Ubuntu 16.04

**.net Framework (Windows) or mono (macOS/Linux) Version:**
Mono 5.12.0.226

**Link to Log Files (debug or trace):**
https://drive.google.com/file/d/1VgQAZqTcS3FWg0XCl4aLiMouMSvN3EhG/view?usp=sharing
https://drive.google.com/file/d/1KDrmUZxBXiVvXLQHGRo80b3Gt5AJZ4WO/view?usp=sharing

**Browser (for UI bugs):**
Chrome OS

**Comment by markus101** [comment]
The log shows 454 results, which it starts processing.

```
18-7-1 10:28:06.5|Debug|NzbSearchService|Total of 454 reports were found for [19-2 (2014) : S01E01] from 28 indexers
18-7-1 10:28:06.5|Info|DownloadDecisionMaker|Processing 454 releases
```

17 seconds later results are still processing:

```
18-7-1 10:28:23.5|Debug|EpisodeRequestedSpecification|Release rejected since the episode wasn't requested: Game of Thrones - Season 01 HDTV-1080p v1
18-7-1 10:28:23.5|Debug|SeriesSpecification|Checking if series matches searched series
18-7-1 10:28:23.5|Debug|SeriesSpecification|Series [121361][Game of Thrones] does not match [276360][19-2 (2014)]
```

Note that one or more of your indexers is returning unrelated junk.

```
18-7-1 10:28:23.6|Debug|Api|[GET] /api/release?episodeId=48299&sort_by=releaseWeight&order=asc: 200.OK (143170 ms)
```

Shows the servers returning a successful response.

Have you tried another browser?
Dev tools (Console/Network tabs) may show something as well, but nothing in the logs indicates a problem.

**Comment by antigravity83** [comment]
Hi there

Just installed Firefox and tried to find 19-2 S01E01, and the same issue occurs. Just loads indefinitely. 

However I was able to get Manual Search Results for another program in Chome. 

It seems some shows allow manual search, and others dont.

**Comment by Taloth** [comment]
> 200.OK (143170 ms)

Two minutes. One or more of your indexers are horribly slow.

> http://localhost:9117/torznab/tvchaosuk/api?t=tvsearch&cat=5000,5020,5030,5040,5060,5080,100074,100075,100076,100078,100082,100083,100090,100091,100092,100098,100099,100100,100101,100103,100106,100107,100113,100114,100115,100118,100138,100139,100140,100141,100142,100148,100149,100166,100167,100168,100170,100172,100173,100174,100175,100176,100177,100178,100180,100181,100182,100183,100184,100185,100186,100187,100188,100189,100190,100191,100193,100194,100196,100198,100199,100200,100201,100202,100203,100204,100208,100209,100210,100212,100215,100216,100217,100218,100219,100220,100221,100222,100223,100224,100226,100227,100228,100229,100230

Why are you doing that with several dozen categories? That's rather redundant given the 5000 category.
5000 contains all 50xx categories. And most 100xxx categories maps to 5000 as well. A Release exists in multiple categories.
Also 100083 is pointless, "TV Aired Movies"

> 18-7-1 10:27:50.7|Debug|Torznab|Downloading Feed http://localhost:9117/torznab/blutopia/api?t=tvsearch&cat=5000,100002&extended=1&apikey=(removed)&offset=400&limit=100&q=19%202&season=1&ep=1
18-7-1 10:27:52.8|Debug|Torznab|Downloading Feed http://localhost:9117/torznab/blutopia/api?t=tvsearch&cat=5000,100002&extended=1&apikey=(removed)&offset=500&limit=100&q=19%202&season=1&ep=1
18-7-1 10:27:54.8|Debug|Torznab|Downloading Feed http://localhost:9117/torznab/blutopia/api?t=tvsearch&cat=5000,100002&extended=1&apikey=(removed)&offset=600&limit=100&q=19%202&season=1&ep=1
18-7-1 10:27:56.9|Debug|Torznab|Downloading Feed http://localhost:9117/torznab/blutopia/api?t=tvsearch&cat=5000,100002&extended=1&apikey=(removed)&offset=700&limit=100&q=19%202&season=1&ep=1
18-7-1 10:27:58.7|Debug|Torznab|Downloading Feed http://localhost:9117/torznab/blutopia/api?t=tvsearch&cat=5000,100002&extended=1&apikey=(removed)&offset=800&limit=100&q=19%202&season=1&ep=1
18-7-1 10:28:01.6|Debug|Torznab|Downloading Feed http://localhost:9117/torznab/blutopia/api?t=tvsearch&cat=5000,100002&extended=1&apikey=(removed)&offset=900&limit=100&q=19%202&season=1&ep=1
18-7-1 10:28:03.9|Debug|Torznab|Downloading Feed http://localhost:9117/torznab/blutopia/api?t=tvsearch&cat=5000,100002&extended=1&apikey=(removed)&offset=0&limit=100&q=19%202%20CA&season=1&ep=1

Why is blutopia returning 1000 results for 1 episode?
It appears it's returning every S01 season pack. Even though those titles do not contain '19'.

These are all indexer related issues.

**Comment by antigravity83** [comment]
Thanks for spotting that. I'm not sure why Blutopia is returning 1000 results, I've just connected to their API via Jackett. 

I've also removed the multiple categories for TVChaos - I wasn't aware that 5000 covered all of the 5xxx categories. 

I've removed these- and unfortunately I'm still not getting any manual search results for 19-2 S01E01. 

Could it be that there's an issue with the naming of this series, which means Sonarr gets too many search results (ala the Blutopia issue?)

**Comment by antigravity83** [comment]
Thanks @Taloth... Appreciate the detailed response. 

Where do you see how long each indexer takes to respond? I'd like to tidy up my indexers if possible.

**Comment by Taloth** [comment]
If you want to see it more accurately then enable Trace level logging, which will log the start and end of each http request to the indexer, including the duration.

**Comment by antigravity83** [comment]
Excellent- thanks again @Taloth. Much appreciated :)
