### ISSUE TITLE
Accessing network shares seems to be intermittent

### ISSUE THREAD

**Issue by TehWardy** [Sonarr/Sonarr#2646]
**Describe the bug**
Sonarr installed on windows uses a Linux based nas to store files but for some reason keeps complaining 
the nas directory does not exist.

**Screenshots**
![image](https://user-images.githubusercontent.com/6891030/42242788-0ce0c83e-7f07-11e8-96e1-81b7603e7b39.png)

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 2.0.0.5228
 - Operating System: Windows Server 2016 (sonarr install), Qnap (nas)
 - .net Framework (Windows) 4.6.2

**Additional context**
I have the nas setup so that from windows explorer no auth details are needed to talk to the nas so anywhere on my local LAN I can do \\nas\share using windows explorer and everything is fine and no auth info is asked for. 

For some reason though Sonarr is the only thing on my LAN that plas up with this setup, everything else is fine.
Do I need to do something special to get this to work?

**Comment by markus101** [comment]
Please open a thread on the forums for support.

The FAQ has some common solutions, though that's typically with mapped network drives.

If Sonarr is coming up before the network is available that could cause issues, though the message would disappear once checked again.

If Sonarr isn't have issues importing even though that message is present then it's something we could look into clearing up on import.

**Comment by TehWardy** [comment]
This is a sonarr issue only which is pretty much the only reason I reported it.
It seems to stop working when i see this message and it happens a few times a day ... basically my fix it constantly restart the service ... i'm close to having a windows job restart the sonarr service on the hour every hour just to get some decent level of activity out of it.

Never mind though ... i'm a .Net dev ... maybe I can look in to it ... just frustrating to have to tbh.
