### ISSUE TITLE
Sonarr not parsing date in torrent name for Come Dine With Me.

### ISSUE THREAD

**Issue by zang74** [Sonarr/Sonarr#2648]
**Describe the bug**
Sonarr is not seeing date in torrents added when series type "daily" is preferred when Torrent is searched for (through Torznab/Jackett).

Due to an inconsistency of the numbering scheme used by the capper of this show (Come Dine With Me) from the only source I can find it at (TVCUK), I've long used the dates as the way of discovering the episodes in a search. Her numbering scheme matches neither what's on thetvdb OR Channel 4's own scheme (they've now moved to date from S/E numbering).

The first screenshot below shows that Jackett is picking up the full torrent name just fine. She (the capper) includes the date in the .torrent name and TXT (no NFO) file, but not the folder or filenames (frustrating). However, I don't think this is why the file isn't showing up in searches, unless Jackett is somehow communicating the files contained within.

Manually adding a torrent doesn't help, because the date isn't in the video file name (just .torrent name), and so Sonarr doesn't see/know the date and parses the Season/Episode identifier.

**Screenshots**
![screen shot 2018-07-05 at 10 07 58 am](https://user-images.githubusercontent.com/5435684/42328523-7904707a-803c-11e8-96df-e58f2bee4e80.png)

**Logs**

Just the relevant part:

18-7-5 10:05:10.9|Info|NzbSearchService|Searching 14 indexers for [Come Dine With Me : 2018-07-03]
[…]
18-7-5 10:05:10.9|Debug|Torznab|Downloading Feed http://192.168.0.109:9117/api/v2.0/indexers/tvchaosuk/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Come%20Dine%20With%20Me&season=2018&ep=07/03
[…]
18-7-5 10:05:53.4|Debug|NzbSearchService|Total of 0 reports were found for [Come Dine With Me : 2018-07-03] from 14 indexers

**System Information**

 - Sonarr Version: 2.0.0.5228
 - Operating System: Ubuntu 16.0.4 / Raspberry Pi 3
 - .net Framework (Windows) or mono (macOS/Linux) Version: mono 5.12.0.226

**Additional context**

**Comment by markus101** [comment]
That date format is not parsed. In those releases the season and episode number is preferred when parsing.

Perhaps thexem.de can be used to handle the difference between those release season + episode numbers and TheTVDB's numbering, but Sonarr won't parse (or prefer) the date in that format/position.
