### ISSUE TITLE
Sonarr is crashing on DietPi v6.10 ARMv7 upon first web request

### ISSUE THREAD

**Issue by hellfirehd** [Sonarr/Sonarr#2650]
DietPi version: 6.10
Distro version : stretch
Kernel version: #1 SMP PREEMPT Thu Apr 5 12:46:33 UTC 2018
SBC device: Odroid XU3/XU4/HC1/HC2 (armv7l)
Power supply used: 12V 1.5A
SDcard used: Transcend Premium 32GB

See here for original issue: https://github.com/Fourdee/DietPi/issues/1896

**Comment by Taloth** [comment]
For posterity: Dealt with in DietPi by disabling the aggressive mono optimizations they recently applied.
