### ISSUE TITLE
Failed downloads are imported from NzbGet

### ISSUE THREAD

**Issue by JoshSchreuder** [Sonarr/Sonarr#2651]
**Describe the bug**
There is an existing bug in NzbGet where a download with no archives and par2 files will fail if articles are missing, but still be moved to DestDir. In this case the download is marked as `FAILURE` but it is copied to DestDir as if it is completed.

With unpacked video files if articles are missing often the video is playable but will skip and judder.

Sonarr imports these failed NzbGet downloads in spite of the `FAILURE` tag on the download.

**Screenshots**
N/A

**Logs**
N/A?

**System Information**

 - Sonarr Version: [e.g. 2.0.0.1]
`2.0.0.5227`

 - Operating System: [e.g. Windows 10]
`Lubuntu 18.04`

 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]
`Mono 5.12.0.226`

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

`N/A`

**Additional context**
See here for related NzbGet issue:
https://github.com/nzbget/nzbget/issues/562

**Comment by markus101** [comment]
It's going to depend on how Sonarr sees the failure. Going to need to see Trace logs of the response to see what Sonarr sees.

**Comment by JoshSchreuder** [comment]
> Going to need to see Trace logs of the response to see what Sonarr sees.

The ones that failed yesterday now have the missing articles present so I'm finding it hard to reproduce a download in NzbGet that fails in this manner. I'll keep an eye out today and try and get some logs for you.

**Comment by markus101** [comment]
Closing. If more information surfaces we can reopen it.

**Comment by JoshSchreuder** [comment]
@markus101 no worries. Apologies as I wasn't able to reproduce this again. NZBGet seems to have fixed this in one of their latest dev builds anyway so it's probably not a big deal. Thanks!
