### ISSUE TITLE
New web hook event to facilitate hard links via external web hook receiver

### ISSUE THREAD

**Issue by l3uddz** [Sonarr/Sonarr#2652]
**Describe the problem**

When using docker, hard linking becomes problematic, this would provide a possible solution to that.

**Describe any solutions you think might work**

Add another web hook event, OnDownloadCompleted.
This web hook would send everything the onDownload event sends (e.g. sourceFilePath of the file that WOULD/WILL be imported, the relativeImportPath of where the file should be imported).

The web hook receiver running on the host system, would then hardline the file to the destination and send a response to the web hook request, e.g.

HTTP 200 = File was hard linked, this would allow sonar to check for that response from the web hook event, if it was 200 response, check if the import destination exists, if it does, consider the import complete.

HTTP 501 = Hardlink failed, thus telling sonar to act normally and try to import as it usually would.

**Comment by markus101** [comment]
As long as they are on the same volume (same as any system) they aren't a problem.

Similar enough to https://github.com/Sonarr/Sonarr/issues/791

**Comment by l3uddz** [comment]
It mainly becomes an issue when you are using cloud based mounts. Unionfs is not reliable enough to handle torrent client activity, import activity, disk scan activity without major slowdowns / crashes, so running it off the same volume is not always possible...

Sorry, did not see the old feature request, will put my proposal there too.
