### ISSUE TITLE
Allow search for a different title language

### ISSUE THREAD

**Issue by pikax** [Sonarr/Sonarr#2653]
**Describe the problem**
Allow search for a different title (non-english).
Find an release by the original title is sometimes easier than by the english translated title.

This is a bit problematic for some animes, because the japanese title (written in ascii) is most of the times more accurate.
I'm having this issue specially on the anime `Chuukan Kanriroku Tonegawa` the english translation is `Mr TONEGAWA Middle Management Blues`, but no fansub will release with the english transalated name.

This doesn't affect only anime, searching by other language name could help to get releases dubbed in that language.

**Describe any solutions you think might work**
It could allow us to set a alias name and use that as the name when searching or it could use thetvdb to get the other languages descriptions and allow us to select which one we want the synopsis, episode names, etc. 

**Additional context**
Some examples of animes examples

| ENG | JAP |
| --- | --- |
| The Mystic Archives Of Dantalian | Dantalian no Shoka |
| Mr. TONEGAWA Middle Management Blues | Chuukan Kanriroku Tonegawa |

**Comment by Thirrian** [comment]
https://github.com/Sonarr/Sonarr/wiki/FAQ#why-cant-sonarr-import-episode-files-for-series-x--why-cant-sonarr-find-releases-for-series-x

Since they're anime: get them added with aliases to thexem.de, that should do it I think?

**Comment by pikax** [comment]
It's not only for anime, the anime could fix that, but would be nice to allow us to describe alias to the show and use that on the indexers, for example:

I want to get `CSI: Miami` first episode of the  season 10.
When I search sonarr will search on the indexers by: *CSI Miami S10E01*

the template seems to be something like this:
``` csharp

var SeriesName = "CSI: Miami";
var Season = "10";
var Episode = "01";

$"{sanitize(SeriesName)} S{Season}E{Episode}"
```

I will get most likely get the english version of it, as expected.

But if I want to get other language or filter by a specific keyword in there, like get it in Italian for example, the example above won't work, but if it was a way to define an alias to the series it would work.

the template could be like this:
```csharp
var SeriesName = "CSI: Miami";
var Season = "10";
var Episode = "01";
var Alias = "CSI: Miami ita";


$"{sanitize(Alias ?? SeriesName)} S{Season}E{Episode}"
```

or for anime

```csharp
var SeriesName = "Mr. TONEGAWA Middle Management Blues";
var Season = "01";
var Episode = "01";
var Alias = "Chuukan Kanriroku Tonegawa";


$"{sanitize(Alias ?? SeriesName)} S{Season}E{Episode}"
```

This could give an extra flexibility for the sonarr users, even to get specific releases.

**Comment by markus101** [comment]
There are no plans for local aliases, but there are plans to make requesting them easier.

There is also https://github.com/Sonarr/Sonarr/issues/1128
