### ISSUE TITLE
Non-portable getfsfile used by Mono.Unix.Native.Syscall.sys_getfsfile

### ISSUE THREAD

**Issue by frebib** [Sonarr/Sonarr#2657]
Recently @Adam-Ant & I have been putting in some legwork to get Sonarr & friends in Alpine. Today we ran across the non-critical issue (I don't think it causes any actual problems) producing this error:

```
[v2.0.0.5228] System.EntryPointNotFoundException: Mono_Posix_Syscall_getfsfile
  at (wrapper managed-to-native) Mono.Unix.Native.Syscall.sys_getfsfile(string,Mono.Unix.Native.Syscall/_Fstab&)
  at Mono.Unix.Native.Syscall.getfsfile (System.String mount_point) [0x00010] in <3a9afa14394e4833abac0216310954b8>:0 
  at Mono.Unix.UnixDriveInfo..ctor (System.String mountPoint) [0x00014] in <3a9afa14394e4833abac0216310954b8>:0 
  at NzbDrone.Mono.Disk.ProcMount..ctor (System.IO.DriveType driveType, System.String name, System.String mount, System.String type, NzbDrone.Common.Disk.MountOptions mountOptions) [0x0002b] in <cd50cb4f3a50490d80a10df172583553>:0 
  at NzbDrone.Mono.Disk.ProcMountProvider.ParseLine (System.String line) [0x000be] in <cd50cb4f3a50490d80a10df172583553>:0 
  at System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].MoveNext () [0x0003a] in <d1101c9fda204a27a79d4b9d3be50fcc>:0 
  at System.Linq.Enumerable+<OfTypeIterator>d__32`1[TResult].MoveNext () [0x00067] in <d1101c9fda204a27a79d4b9d3be50fcc>:0 
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00077] in <c827e12a54774c32b8b93a7069f68b10>:0 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <d1101c9fda204a27a79d4b9d3be50fcc>:0 
  at NzbDrone.Mono.Disk.ProcMountProvider.GetMounts () [0x0002c] in <cd50cb4f3a50490d80a10df172583553>:0 
```

The `getfsfile` function, whilst Unix, is [not Posix compliant](https://linux.die.net/man/3/getfsfile) and is therefore not implemented in musl libc, used by Alpine.

Realistically, this is an issue for upstream (mono) because the bug is with them but I'm opening this here to track it.

I might take a crack at implementing [`getmntent`](https://github.com/mono/mono/blob/master/mcs/class/Mono.Posix/Mono.Unix/UnixDriveInfo.cs#L144-L145) over with Mono but it looks like a relatively large task.

**System Information**

 - Sonarr Version: 2.0.0.5228
 - Operating System: Alpine Linux 3.8, https://github.com/spritsail/sonarr/blob/alpine/Dockerfile
 - Mono Version: 5.12.0.226, from source to work with Alpine

**Comment by Taloth** [comment]
Forgive me but I have to comment on the irony of using a minimal OS for the sake of simplicity and resource efficiency.... and then throw mono and Sonarr on it :smile:

We could make ProcMount a bit more resilient so it won't actually fail on it, but the same issue might occur elsewhere.

Personally I don't know how useful it is to track the mono issue here, since it's mostly just noise. But I'm ok with leaving it open for a while to see if we can come to some compromise.

**Comment by frebib** [comment]
Haha, yeah it does seem a bit dumb but honestly it's a fun project. We managed to get the Mono runtime down to ~50MB, + Alpine + Sonarr is <90MB; that's a 34MB download!
It feels like the last few days have been worth it, at least to us. I'm sure most would just install Debian and get on with their lives.

My first thought was just to "borrow" the class file from Mono and `s/getfsfile/getmntent/` but I quickly realised that without the native implementation I couldn't even do that.

I suppose we could fashion up a shim layer with good old `open(2)` and do the leg work within Mono instead of relying on native calls, at least until something more permanent is put in place upstream. Thoughts?

**Comment by frebib** [comment]
I ran into a crash when Sonarr attempts to move files for import. Surprise surprise, it's caused by another non-standard missing libc function, this time a GNU extension variant. Interestingly Mono actually seems to account for the fact that it may not be present but for some reason it still crashes :/

Why is Sonarr attempting to create a hardlink when they're explicitly disabled in the settings?

https://gist.githubusercontent.com/frebib/e81914bcc126ab36d92899248b7ae4f6/raw

**Comment by Taloth** [comment]
_Seems like i forgot to submit an earlier comment:_
The ProcMount class is simply intended to augment the information provided by the normal .net Drive functions. It uses UnixDriveInfo purely to check if it's available, and get freedisk space. There might be alternatives available for that, but it's possible that mono uses UnixDriveInfo in other places as well.

_Regarding the hardlink:_
That's actually got to do with an old mono+samba issue when moving files to smb shares. Cross-filesystem moves are basically 'read from source, write to destination, then delete source'. Sometimes the samba transfer times out, but reports success back to mono, causing mono to delete the source and you're left with a partial file at the destination.
Sonarr is not creating a hardlink between src and target, it's creating a hardlink to a temporary file at the source for backup purposes so it can move it, then checks the src vs destination filesize and rollback if needed. It's literally a workaround. But the hardlink is optional, if it can't do the hardlink then it does a copy instead.

**Comment by frebib** [comment]
Could we use `System.IO.DriveInfo` instead/as a fallback? I don't understand why the Mono class is calling the fstab anyway, there is little/no useful information in there that can't be obtained through `/proc/mounts` or elsewhere..

**Comment by Taloth** [comment]
Not all mounts appear in `System.IO.DriveInfo`, at least in our experience, otherwise we wouldn't need procmount.

**Comment by markus101** [comment]
Closing this out, we can reopen if there is something actionable.
