### ISSUE TITLE
Add variable for tvdb ID in naming scheme

### ISSUE THREAD

**Issue by saitoh183** [Sonarr/Sonarr#2659]
So I wanted to know if that would be possible. The reason behind the request is that for anime to show up properly in plex for the users that use the [hama agent](https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/README.md), you have the option of appending the tvdb ID to the show folder name in this format

**Anime_show [tvdb-tvdbID]** 

I won't go into details about how that all works but the result is that you will get different presentation of your anime in plex that can differ from your folder structure.
If i take my case for example.

I like my anime with absolute numbers and no season folder. But in plex for user convinience (especially for long running series) I want plex to show everything in a per season format instead of every episode under season 1.

screenshots of what i mean:

Folder layout:
![image](https://user-images.githubusercontent.com/1534197/42606125-b2dc81c2-8549-11e8-9c76-84d1aa98ce38.png)

Plex:
![image](https://user-images.githubusercontent.com/1534197/42606142-d674c194-8549-11e8-9854-b2a5c991b228.png)
![image](https://user-images.githubusercontent.com/1534197/42606240-67f8bdf0-854a-11e8-8224-d1a935b0088c.png)

Right now every time I add a anime, I have to edit the folder name to match the format I need. So if the tvdb ID could be added as a variable in the naming scheme section, i could do it there once and for all.

**Comment by markus101** [comment]
Seems reasonable, but depends on https://github.com/Sonarr/Sonarr/issues/798 being implemented first or it'll be a mess to import.

**Comment by saitoh183** [comment]
Wow..thats an old request...i remember seeing it back in the day..lol

**Comment by saitoh183** [comment]
Yes there is a issue of not being recognized if you already have the series, I just strip my tvdb portion, so lets hope you figure something out! :)

**Comment by markus101** [comment]
Done in the v3 work.
