### ISSUE TITLE
A way to ignore torrents from the Activity list

### ISSUE THREAD

**Issue by MrDemocracy** [Sonarr/Sonarr#2660]
**Describe the problem**
I have a few torrents that I have made and uploaded, but I don't want these to show up on the activity list making the torrent counter on the Activity icon have the orange warning label, since I never would want to import these with sonarr.

**Describe any solutions you think might work**
Adding a ignore option for selected torrents that ignore all files/episodes associated with that torrent.

**Additional context**
I'm using BiglyBT

**Comment by Thirrian** [comment]
I'm guessing here, since BiglyBT is based on Vuze, you can use categories?

If you set a category in sonarr, e.g. "tv", sonarr will only look at torrents with that category and ignore all others. Also, any torrent that is sent to your download client by sonarr will be assigned the "tv" category.

**Comment by MrDemocracy** [comment]
Thank you :) Hadn't thought of that.

**Comment by MrDemocracy** [comment]
Okay, so this is not what I want... I don't want it to create a new directory for sonarr downloads.
It looks like it also requires the files in the sonarr category to be in the sub-folder that sonarr creates for the category.
I can't just change the category for incomplete download, I have to also move them to the category sub-folder.
I don't want to make any new folders or move my ongoing downloads.

**Comment by MrDemocracy** [comment]
It also looks like I have tried this before since there's already a "Sonarr" folder with files in it, in my download directory.

**Comment by markus101** [comment]
Transmission doesn't support categories and Vuze (and Bigly) use the same API.

Categories and for these clients Folders acting as categories is the only way to ignore downloads you don't want Sonarr to see.

**Comment by MrDemocracy** [comment]
Why does it name the folder Sonarr with capital S, when I named the category with small s?
I deleted the sonarr folder that was already there. Or does it just name it "Sonarr" no matte what category name I choose?

**Comment by markus101** [comment]
It tells your client to put it in a subfolder named to match whatever category you entered, Sonarr doesn't create the folder itself.

**Comment by MrDemocracy** [comment]
Okay it works now, but now I have a lot of files (where I have removed the torrent from the client) that I have to move manually to either the sonarr or the radarr folder.
