### ISSUE TITLE
Deluge gives object reference not set error

### ISSUE THREAD

**Issue by Gijs735** [Sonarr/Sonarr#2664]
**Describe the bug**
Since a few days I am getting the error *"Unable to communicate with Deluge. Object reference not set to an instance of an object"* on my system page. When testing deluge under settings/download clients the testing succeeds. The issue showed up arround the 2.0.0.5239 release.

**Screenshots**
Testing deluge succeeds: [Image](https://user-images.githubusercontent.com/789255/42738051-afcd4034-887d-11e8-8658-ed995ecaba75.PNG)
Log window: [Image](https://user-images.githubusercontent.com/789255/42738052-afe52406-887d-11e8-8db5-5bf00c523b72.PNG)
Sonarr system page: [Image](https://user-images.githubusercontent.com/789255/42738053-affc9686-887d-11e8-8308-51f9d1999358.PNG)

**Logs**
[pastebin](https://pastebin.com/i7vMMDfh)

**System Information**

 - Sonarr Version: 2.0.0.5240 - *Develop branch*
 - Operating System: Windows server 2012 R2 Datacenter
 - .net Framework (Windows): Version: 4.7.0

**Comment by markus101** [comment]
Please post the debug log that includes this error.

**Comment by Gijs735** [comment]
Below is the debug log and stacktrace on pastebin:
[Stacktrace](https://pastebin.com/d9QVnhYa)
[Debug log](https://pastebin.com/vSpEhCAd)

In the stacktrace the error throws arround line 400.

**Comment by markus101** [comment]
Thanks @Qstick that it does.
