### ISSUE TITLE
Season search use cutoff , even if partially downloaded

### ISSUE THREAD

**Issue by bizen-ya** [Sonarr/Sonarr#2665]
**Describe the bug**
When i do a season search on a partially downloaded season , DecisionMaker use cutoff of existing file, ignoring the fact that there is other missing files to download.
**Logs**

18-7-16 18:56:32.8|Debug|CutoffSpecification|Comparing file quality with report. Existing file is HDTV-720p v1
18-7-16 18:56:32.8|Debug|CutoffSpecification|Cutoff already met, rejecting.

**System Information**

Version    2.0.0.5228
Mono Version    5.10.1.20
Linux

**Comment by markus101** [comment]
This is expected, Sonarr won't grab any release unless all episodes are viable upgrades; either there isn't a file or the cutoff hasn't been met and they need to be monitored as well.

https://github.com/Sonarr/Sonarr/issues/266 would be the way to forcibly grab them, once implemented.
