### ISSUE TITLE
Series View doesn't show Missing for Unmonitored

### ISSUE THREAD

**Issue by Vacant0mens** [Sonarr/Sonarr#2666]
**Describe the bug**
In the Series List view, all of my shows show up either blue, green, or red. The key at the bottom includes `[orange]Missing Episodes (Series not monitored)`. And while I know that some of my shows are missing episodes (e.g. showing `0/0` in green in the screenshot, I also came across a random missing episode just by chance, but the season showed up as `12/12` even in the seasons list view), it doesn't show any of them in orange. 

This could be because the shows that I would like to verify are complete are ended? But ended shouldn't take priority over unmonitored. I'd still like to know if I'm missing episodes whether the show is ended or not.

**Screenshots**
![image](https://user-images.githubusercontent.com/26305795/42847271-aad96790-89d8-11e8-960d-a4b00b4bd035.png)

**Logs**
Not sure if this would even show in the logs or not since it's a UI-based bug.

**System Information**

 - Sonarr Version: 2.0.0.5228
 - Operating System: Ubuntu 16.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 5.10.1.20

**UI Bugs:**
 - OS: Windows 10
 - Browser: Vivaldi
 - Version: 1.15.1147.47

**Additional context**

**Comment by markus101** [comment]
If none of the episodes are monitored and you don't have any episode files on disk then you have `0` of `0` files and is treated as complete (you're missing 0 episodes you want), which is what you see.

If you have files and the series is unmonitored, but all episodes are monitored, then you'd get an orange progress bar.

**Comment by Vacant0mens** [comment]
Is there a way to see all/any missing episodes (monitored or not)?

**Comment by Vacant0mens** [comment]
I'm not sure that makes sense. "Missing monitored episodes" would be more apt. The current one makes it sound like it should be doing what I was expecting (showing orange if any were missing, unmonitored series and/or episode). Also, why not just keep it red if it's missing any "wanted"?

**Comment by markus101** [comment]
Use Wanted: Missing, you can show Unmonitored episodes without files there.

At the core an episode needs to be monitored to be missing, if no episodes are monitored for a series nothing is missing.

If an episode is missing, but the series is Unmonitored it's effectively not monitored and will never be grabbed automatically, the colour difference is there to differentiate those cases.
