### ISSUE TITLE
Updated Mono - Service won't start anymore (radarr too)

### ISSUE THREAD

**Issue by ekleinem** [Sonarr/Sonarr#2667]
I'm not sure what exactly what went wrong but I upgraded mono to 5.12 from 5.4 because it was a requirement to have 5.8 at least for Jackett to function. Upgrading mono seems to have borked my sonarr/radarr installs. 

**Logs**
https://pastebin.com/3yenNXV0

**System Information**

 - Sonarr Version: not sure.. can't view the sonarr install because it won't run anymore.
 - Operating System: Kubuntu 18.04
 - mono 5.12

Radarr won't start either.

**Comment by markus101** [comment]
Please open a thread on the forums for support.

You're going to need to look at Sonarr's log files to see if they are being written to and what is in them.
