### ISSUE TITLE
Automatic Import doesn't automatically import

### ISSUE THREAD

**Issue by shadow7412** [Sonarr/Sonarr#2668]
**Describe the bug**
Automatically importing files from an arbitrary folder is not working.

I have a script that calls the api for scanning a specific folder. Here is the relevant part;
```
print(post(
     "http://localhost:8989/api/command",
     json={
         "name": "downloadedepisodescan",
         "path": BLACKBOX,
         "importMode": "Move",
     },
     headers={
         "X-ApiKey": "xxx"               
     },
 ).json())
```

The message is received by sonarr, and it returns the following JSON;

```
{
  "name": "DownloadedEpisodesScan",
  "body": {
    "sendUpdatesToClient": false,
    "sendUpdates": false,
    "path": "/mnt/conspire/files/downloads/zone/",
    "importMode": "move",
    "updateScheduledTask": true,
    "completionMessage": "Completed",
    "name": "DownloadedEpisodesScan",
    "trigger": "manual"
  },
  "priority": "normal",
  "status": "queued",
  "queued": "2018-07-20T03:14:45.138982Z",
  "trigger": "manual",
  "state": "queued",
  "manual": true,
  "startedOn": "2018-07-20T03:14:45.138982Z",
  "sendUpdatesToClient": false,
  "updateScheduledTask": true,
  "id": 2583707
}
```

Unfortunately, sonarr then does nothing.

I suspect the API isn't at fault here though, because doing the same thing via the UI (Wanted -> Manual Import -> Select folder -> Import File(S) Automatically) does nothing either. (Side note, that S in brackets shouldn't be captislised, but it's what it says on the UI. This is probably it's own bug).

**Screenshots**
This is a view of the Manual import screen. As you can see, the episode is correctly identified and doesn't show any reasons why it wouldn't import. Clicking Import on this screen works as expected.
![image](https://user-images.githubusercontent.com/286341/42981236-82d1e536-8c1e-11e8-8cb1-c1f0e069639e.png)

But as mentioned above, clicking Import Files Automatically on the previous screen does not import those files.

**Logs**
I was unable to see any relevant information in the log files displayed on the UI. Let me know if there is somewhere else I should be looking.

**System Information**

 - Sonarr Version: 2.0.0.5228
 - Operating System: Ubuntu 16.04.4 LTS
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono JIT compiler version 5.10.1.20

**UI Bugs:**
 - OS: Windows
 - Browser: Chrome
 - Version: 68.0.3440.59

**Comment by markus101** [comment]
> I was unable to see any relevant information in the log files displayed on the UI. Let me know if there is somewhere else I should be looking.

You're going to need to look at the debug logs to see why it didn't import it. There is a wiki page with where to enable/find them.

Based on the path used in Manual Import it looks like you're using the wrong path in the API command.

From: https://github.com/Sonarr/Sonarr/wiki/Command#downloadedepisodesscan
> A folder specified by the path variable is assumed to be a single download (job) and the folder name should be the release name.
