### ISSUE TITLE
Uneven behavior on episode naming

### ISSUE THREAD

**Issue by XtremXpert** [Sonarr/Sonarr#2669]
Why do when I set Standard Episode Format to:
{Series Title} - [S{season:00}E{episode:00}] - {Episode Title}

Sonarr reply on save : Produces invalid file names on save only, but it show it correctly in the example and gave Invalid format error for multi-episode example

While this is working setting Daily Episode Format to:
{Series Title} [{Air-Date}] {Episode Title}

![sans titre](https://user-images.githubusercontent.com/5651439/43008237-81b89d2c-8c08-11e8-9dd9-e2f2c454d407.png)

**Comment by markus101** [comment]
> Produces invalid file names on save only, but it show it correctly in the example and gave Invalid format error for multi-episode example

Sonarr can't properly parse back the multi-episode release when saving, thus the failure. We'll have to see what can be done there, but generally square brackets can cause issues with some file names.
