### ISSUE TITLE
Ssl issues with mono

### ISSUE THREAD

**Issue by ugokanain** [Sonarr/Sonarr#2670]
I'm using sonarr on a mac. Another program needs a new version of mono, and i started having issues with sonarr. It wouldn't connect to indexers with https. Found that if you loaded the certs and set the environment, it would work ok. 

Any chance that you can set the environment in the script that launches sonarr? My .profile file had MONO_TLS_PROVIDER=legacy, but seems sonarr isn't using it 

curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin
export MONO_TLS_PROVIDER=legacy

**Comment by markus101** [comment]
Sonarr supports the newer SSL stack in mono 5+, you shouldn't need to us the legacy provider.

You can open a thread on the forums to troubleshoot further, no plans to change the startup script in Sonarr.app.
