### ISSUE TITLE
is larger than maximum allowed 0 B (for 0Min)

### ISSUE THREAD

**Issue by SCRPD** [Sonarr/Sonarr#2673]
**Describe the bug**
A show like Adventure Time (10-11min runtime) isn't fetching correctly even with runtimes correctly entered on Trakt & TheTVDB.

**Logs**
No logs on this.

**System Information**
 - Sonarr Version: [e.g. 2.0.0.1]
 - Operating System: Debina Stretch 
 - Mono 5.12.0.226

Should be able to replicate it.

**Comment by markus101** [comment]
Need debug logs... also make check the runtime in Sonarr's UI.

**Comment by SCRPD** [comment]
I went to go get the debug logs tonight and it seems to have fixed itself overnight, just have to adjust my profiles now.
`177.8 MB is smaller than minimum allowed 307.0 MB (for 10min)`

**Comment by warsix4** [comment]
I am having this issue with EVERYTHING today after Sonarr updated.
