### ISSUE TITLE
Download wasn't grabbed by Sonarr and not in category, skipping

### ISSUE THREAD

**Issue by chniko** [Sonarr/Sonarr#2676]
### System Information/Logs

**Sonarr Version: 2.0.0.4689

**Operating System: Synology with DSM 6.0

**Link to Log Files (debug or trace): [logs.txt](https://github.com/Sonarr/Sonarr/files/2218515/logs.txt)

### Additional Information
Hi,
First of all thanks for Sonarr, it's a great application.
I'm running it on a synology along with Transmission (v2.94 on Synology).
Sonarr is able to monitor the transfers on Transmission but once the file is completed Sonarr can't process it.
![screenshot-sonarr](https://user-images.githubusercontent.com/13166494/43066106-091d6236-8e64-11e8-8ef0-dcea410836d9.png)

Note that If I process it manually, it's working.
I looked into the wiki for similar errors but could not find a solution.

Here are the trace logs of my Sonarr :[logs.txt](https://github.com/Sonarr/Sonarr/files/2218515/logs.txt)
I've looked into it but I could not find any error message that would explain why nothing happens after the file is being parsed.

Let me know If further logs or information are required.

Thanks

**Comment by markus101** [comment]
It needs to be in a category, which for Sonarr is a sub folder named to the same way that the category is named.
