### ISSUE TITLE
Sonarr does not query Jackett for show title containing "illegal" characters

### ISSUE THREAD

**Issue by curiositycasualty** [Sonarr/Sonarr#2678]
Sonarr does not query Jackett for show title containing "illegal" characters.
Both Sonarr and Jackett were pulled from master today.

Running Sonarr with `--debug` I see:
```
[Info] NzbSearchService: Searching 2 indexers for [OK K.O.! Let's Be Heroes : S01E52]
<snip>
[Debug] Torznab: Downloading Feed http://localhost:38881/api/v2.0/indexers/speedcd/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=<snip>&offset=0&limit=100&q=OK%20KO%20Lets%20Be%20Heroes&season=1&ep=52
[Debug] NzbSearchService: Total of 0 reports were found for [OK K.O.! Let's Be Heroes : S01E52] from 2 indexers
```

While in Jackett:
```
07-24 21:44:43 Info Found 0 releases from <snip> for: OK K O Lets Be Heroes S01E52
07-24 21:44:43 Info Found 0 releases from <snip> for: OK K O Lets Be Heroes S01E52
07-24 21:44:45 Info Found 0 releases from <snip> for: OK KO Lets Be Heroes S01E52
07-24 21:44:45 Info Found 0 releases from <snip> for: OK KO Lets Be Heroes S01E52
```
Manually searching in Jackett yields:
![](https://gist.githubusercontent.com/curiositycasualty/eb07d4a820c0cf82c6c54d373230fc59/raw/87d6381f9d42ed19ef35fa28390bc95bb1626fb1/Screenshot%25202018-07-24%252014.51.02.png)

I see there's already an entry on the "Scene Naming (Responses)" google sheet (row 144 under "Old Responses - July 23rd 2018"). But that doesn't seem to solve the problem for me.

Maybe I'm missing something but why can't Sonarr just query the Jackett indexer with HTML/URL escaped patterns?

**Comment by markus101** [comment]
Same underlying issue as https://github.com/Sonarr/Sonarr/issues/1225
