### ISSUE TITLE
WEBDL Profile Search Failing To Find Matches

### ISSUE THREAD

**Issue by thehomerepot** [Sonarr/Sonarr#2679]
**Describe the bug**
Search isn't finding episode matches even though they exist. I think the issue is the naming of the WEBDL profile. Even when I use the "ANY" profile, nothing is matched. When I search for the show on the torrent site itself, the show has a bunch of releases tagged with "WEB-DL". The profiles seem to be searching for "WEBDL". The log files in the webui don't seem to show any search logs. Is there somewhere I can look to investigate this and provide more details?

**Screenshots**
[Screenshots](https://imgur.com/a/C5M2Rdr)

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: [2.0.0.5228]
 - Operating System: [Ubuntu 16.04.04 Docker Container - linuxserver/sonarr]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [5.12.0.226]

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
The selected profile doesn't affect how searches are performed, Sonarr request all results for the selected episode from the indexer, you can see this in the URLs logged when debug logging is enabled.

Could be the wrong series type is selected or the wrong categories are enabled for you indexer. Feel free to open a thread on the forums to troubleshoot further.
