### ISSUE TITLE
Mediainfo button in episode summary

### ISSUE THREAD

**Issue by kaysond** [Sonarr/Sonarr#2681]
It would be nice if Sonarr provided an interface to mediainfo from the UI, so I can get more details about the episode file. I was trying to get framerates of certain TV shows the other day and ended up having to log in through putty and running mediainfo manually. I think the best place for this would be in the "Summary" tab, when you click an episode title. A small media info button next to the file name could bring up a box listing the mediainfo result. Formatting would be nice, but even the raw text would be a good start!

**Comment by markus101** [comment]
Sonarr only stores limited information from media info (mostly stuff it cares about for renaming/importing).

```
{
  "containerFormat": "Matroska",
  "videoFormat": "AVC",
  "videoCodecID": "V_MPEG4/ISO/AVC",
  "videoProfile": "High@L4.1",
  "videoCodecLibrary": "",
  "videoBitrate": 4146560,
  "videoBitDepth": 8,
  "width": 1280,
  "height": 720,
  "audioFormat": "DTS",
  "audioCodecID": "A_DTS",
  "audioCodecLibrary": "",
  "audioBitrate": 768000,
  "runTime": "00:42:16.5870000",
  "audioStreamCount": 1,
  "audioChannels": 2,
  "audioChannelPositions": "2/0/0.0",
  "audioChannelPositionsText": "Front: L R",
  "audioProfile": "",
  "videoFps": 25.000,
  "audioLanguages": "English",
  "subtitles": "",
  "scanType": "Progressive",
  "schemaRevision": 4
}
```

I'm not opposed to being able to show that in the UI, but it'll only return the information it has stored, it won't run mediainfo and dump the raw results.

**Comment by kaysond** [comment]
That would be great. I think that pretty much covers all the major stuff

**Comment by markus101** [comment]
This is done in the v3 work.
