### ISSUE TITLE
Multiple Download Clients Issue

### ISSUE THREAD

**Issue by fahadsgalaxy** [Sonarr/Sonarr#2683]
**Describe the bug**

Adding multiple (NZB) download clients wont create prioritization upon Grabbing.
I would love to see a prioritization system, eg, I have 2 computers both running NZBGet, one computer is my primary and other secondary. 

If my primary computer is offline, then Sonarr upon grab, instead of waiting for primary PC to be online, should just move to the next Client in priority to complete the download (secondary computer).

**System Information**

 - Sonarr Version: [e.g. 2.0.0.1]
 - Operating System: [e.g. Windows 10]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/issues/1866 and https://github.com/Sonarr/Sonarr/pull/2278 cover this.
