### ISSUE TITLE
In Ended shows Tab the "Next Airing sort" is useless change to Last Aired or Date ended.

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#2685]
The Ended Shows Tab on the main page the next airing sort is useless. I would recommend to change it to date ended by using the last episode date. I watch a lot of Asian shows and they have 1 season only so would like to be able to sort by the newest ended shows.

**Comment by markus101** [comment]
In v3 you will be able to choose `Previous Airing` as a column, but it won't switch automatically since it's a filter.
