### ISSUE TITLE
Sort Activity page by Air Date

### ISSUE THREAD

**Issue by TheRealNoob** [Sonarr/Sonarr#2686]
**Describe the problem**
The Wanted page can be sorted by air date.  This means that my show which has an episode airing tonight will be at the top, and my show which is 10 years old at the bottom.  Obviously.  

**Describe any solutions you think might work**
It would be nice I think to see the Activity (Queue) page have the same sorting feature.  This way my active downloads are displayed front and center on page 1 rather than the bottom of page 4, so to speak.  I have several constant (call them stale) downloads which are simply idling waiting for 100%, cluttering several pages.  This change would make the Activity page vastly more usable.

**Comment by markus101** [comment]
This is done in the v3 work.
