### ISSUE TITLE
Wiki/ssl: which pvk conversion to use

### ISSUE THREAD

**Issue by pven** [Sonarr/Sonarr#2687]
https://github.com/Sonarr/Sonarr/wiki/SSL#linux--os-x

There a 'PVK Conversion Tool' is mentioned. But unfortunately it points to a inactive website. When googling around, I found https://www.microsoft.com/en-us/download/details.aspx?id=40812. But is this the same?

**Comment by markus101** [comment]
Doesn't look like it.

GoDaddy lists: http://products.secureserver.net/forms/pvk.zip on their page for converting it.

https://ca.godaddy.com/help/converting-an-exported-pfx-code-signing-file-to-pvk-and-spc-files-using-windows-6034

I've updated the wiki page.

**Comment by pven** [comment]
Thanks!
