### ISSUE TITLE
Wrong naming convention settings used for Anime Specials.

### ISSUE THREAD

**Issue by Hakker1** [Sonarr/Sonarr#2689]
Sonarr uses "Standard Episode Format" naming convention instead of "Anime Episode Format" for any Anime episode that is imported to Specials Season folder of the Anime series.

 - Sonarr Version: 2.0.0.5228
 - Operating System: Synology DSM 6.2 / Docker
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.12.0.226

**Comment by markus101** [comment]
Please see the previous issue: https://github.com/Sonarr/Sonarr/issues/1974
