### ISSUE TITLE
Problem Mail connect

### ISSUE THREAD

**Issue by v1ru535** [Sonarr/Sonarr#2690]
Hi,

Same issue is on radarr:
https://github.com/Radarr/Radarr/issues/2859

On my mailserver, you can see:
`SSL_do_handshake() failed (SSL: error:1402710B:SSL routines:ACCEPT_SR_CLNT_HELLO_C:wrong version number) while in starttls state, client: **** using starttls, server: 0.0.0.0:587`

So, I think sonarr must support TLS1.1 or above.
The problem is: given TLS vulnerability and the status of downgrade attacks

Thanks for your reply.

**Comment by markus101** [comment]
Please provide all the details requested when filing a big report.

**Comment by markus101** [comment]
Closing as there is some activity on the related Radarr issue, we can re-open if there is something actionable.
