### ISSUE TITLE
Release uses "3rd Season" or "S3" in name file - Sonarr can't see it

### ISSUE THREAD

**Issue by v9999** [Sonarr/Sonarr#2693]
Hey guys, I noticed the following behaviour while asking Sonarr to manually search for My Hero Academia S03E16, intending for it to find Erai-Raws' release: "[Erai-raws] Boku no Hero Academia 3rd Season - 16 [1080p][Multiple Subtitle].mkv".

Sonarr won't list that result (Nyaa as indexer), but will find e.g.:
[HorribleSubs] Boku no Hero Academia - 53 [1080p].mkv
[Kuruje] Boku no Hero Academia - 53 [1080p].mp4

It won't find also:
[Ohys-Raws] Boku no Hero Academia 3 - 16 (NTV 1280x720 x264 AAC).mp4
Boku No Hero Academia S3 - 16 VOSTFR [1080p] [HardSub] Yass'Kun
[AnimeRG] Boku no Hero Academia S3 - 14 (My Hero Academia Season 3) [720p] [Eng Dubbed].mp4

Will the search function only work if the release uses the absolute episode number?

Sonarr fetches some wrong releases in that search, such as:
[SilVeR] My Hero Academia S3 - 04 (Boku no Hero Academia - 42) (WEB Dual Audio 1080p) [5383D0D8].mkv

Also, if the "[Erai-raws] Boku no Hero Academia 3rd Season - 16 [1080p][Multiple Subtitle].mkv" file is inside the Season 3 folder of that series, Sonarr will recognize it as S01E16 after a manual scan.

Whan can be done to automatize this?

**Comment by markus101** [comment]
Please use the forums for support and questions.

Results Sonarr receives is going to depend on aliases added to http://thexem.de/xem/show/4317 (for anime) and what the indexer returns. Look at debug logs to see the URLs Sonarr is querying (you can see the terms).

> Will the search function only work if the release uses the absolute episode number?

It's going to need it to match it and for the indexer to know what you want.

> Also, if the "[Erai-raws] Boku no Hero Academia 3rd Season - 16 [1080p][Multiple Subtitle].mkv" file is inside the Season 3 folder of that series, Sonarr will recognize it as S01E16 after a manual scan.

It needs to match The TVDB's numbering to be picked up properly from the series folder.
