### ISSUE TITLE
Move/Relocate Series

### ISSUE THREAD

**Issue by lucienorrin** [Sonarr/Sonarr#2696]
## Feature Request
**Move/Relocate Series** 

### What problem are you looking to solve?
Eliminate the need to 1)manually relocate shows to new directory/drive and 2) manually update the series folder path. (it can be done in bulk in the series editor but it's still manual and requires a lot of clicks if you have many root folders)

### Other Information
Basically I'd like to point the series to a new root folder and have Sonarr handle moving the series folder with the files. Since Sonarr did the moving it would already know where the files are eliminating the need for a re-scan.

**Comment by markus101** [comment]
This will be in v3. There is an already closed issue tied to that milestone

**Comment by lucienorrin** [comment]
Oh, that's great to hear! 
I did search around for any similar issues but couldn't fine any, perhaps I was using the wrong keywords. 
Thanks!
