### ISSUE TITLE
Can no longer access Sonarr interface from another machine in local network

### ISSUE THREAD

**Issue by jwvanderbeck** [Sonarr/Sonarr#2697]
**Describe the bug**
As of today I am suddenly no longer able to access the Sonarr web interface from a different PC on the local network.  The interface is accessible locally on the machine running Sonarr.

My setup is as follows:
Machine "Ryzen" is a Windows 10 PC that runs Sonarr, Roadarr, NZBGet, and Plex Media Server.  It is essentially headless, though I can connect it to my TV when I need to.
Machine GameBox is my main Windows 10 machine, normal setup.
Both machines are connected wired to the same local network

Normally I manage Sonarr remotely by accessing its web interface via the local network, via http://ryzen:8989.  This has worked fine until today.  Now I get no connection.

If I open localhost:8989 on the Ryzen machine, I see the Sonarr interface as expected and everything seems to be working.  I saw no errors in the logs.

Radarr - which is essentially a heavy fork of Sonarr, is suddenly experiencing the same problem.  However, I can access the web interfaces of NZBGet and Plex Media Server just fine as usual, so it isn't a problem with the network or the machine name.

**System Information**
 - Sonarr Version: [e.g. 2.0.0.5228]
 - Operating System: Windows 10

**UI Bugs:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by markus101** [comment]
Please open a thread on the forums for support, including trace logs of Sonarr Being started.

**Comment by jwvanderbeck** [comment]
Seriously? Why have a project on GitHub and not use the Issues feature?

Sigh.. I am so sick of signign up for forums everywhere.
