### ISSUE TITLE
TheXEM.de URL Override Setting

### ISSUE THREAD

**Issue by designgears** [Sonarr/Sonarr#2698]
**Describe the problem**
I've looked at a lot of the requests involving XEM, it looks like we won't be getting the ability to turn it off/on per show like you can in Medusa. I personally started running my own XEM custom private server to deal with the problems I have with certain shows and it works great.

**Describe any solutions you think might work**
I would like the ability to override thexem.de in the advanced general settings.

**Additional context**
I see XEM issues brought up a lot all over the place, I read about XEMv2 being thought about, but no development, no budging on per show setting because users can't be trusted to not to toggle things they shouldn't... etc. 

I realize I can compile it with my own custom url, I already do that, but I would rather not have to do that every time a new version pops up.

**Comment by markus101** [comment]
What about a hosts file or local DNS override?

Personally I'm against adding an option anywhere in the UI to override it, because if it's cleared or overridden and the user doesn't really know what they're doing we have to deal with the support fallout.

**Comment by designgears** [comment]
I've gone that route as well. I understand wanting to keep users from doing dumb stuff.

What about adding it to the config.xml? Out of the way, not possible for anyone to accidentally change it.

**Comment by markus101** [comment]
The config.xml is meant for things that need to be available before the DB is initialized, I don't think that is the correct location for such a setting and don't really think we want to support a setting for the aforementioned issue, even if it's hidden (which would make it that much harder to troubleshoot).

Unfortunately I don't think anyone is really pushing for TheXEM v2, but maybe some day a group will get together to do it.

**Comment by designgears** [comment]
OK, put the url in the database, then I can run a sqlite query to change it really quick.
