### ISSUE TITLE
Invalid request Validation failed:  when using torrent Black hole

### ISSUE THREAD

**Issue by mstrdraco** [Sonarr/Sonarr#2700]
**Describe the bug**
I have a windows 2008 server with mapped drive to a Linux host with winssh i can access the drive fine through explorer copy and delete with no errors. when i set up the black hole i get read and write errors. I'm running the app as me in the pic not as a service. I get  Invalid request Validation failed:  -- Unable to write to folder

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: [2.0.0.5228
]
 - Operating System: [server 2008]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [.net 4.7.2]

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
Please use the forums for questions and support. Also read through the the FAQ, there is an entry on this.

**Comment by mstrdraco** [comment]
the FAQ doesn't work for this instance, I've tried the FAQ here is what I'm seeing per my above comments, I don't run it as a service I have it in the startup folder and I've tried mapping UNC path directly to the share and it still gives me the same errr. 
![sonarrerror](https://user-images.githubusercontent.com/37802459/43833001-3d20af78-9ad7-11e8-934f-2c21ad11f982.png)
