### ISSUE TITLE
sonar file manager is not browsing to correct folder.

### ISSUE THREAD

**Issue by tostane** [Sonarr/Sonarr#2701]
**Describe the bug**
well. It all started with sonar not letting me have tv searches  separated from foreign and normal tv.

I use mhdffs on mint linux to manage the media for many years.   I was organizing the files like this
tv1 tv2 tv3      into  tvshare
mov1 mov2 mov3  into movieshare
drama1 drama2 drama3 into dramashare

i made a top folder  called mediashare and mounted   tvshare movieshare and dramashare  in it.

but  drives were getting near full so i had idea to create one large drive.

so i made
tv1 tv2 tv3 mov1 mov2 mov3 drama1 drama2 drama2  into mediashare
to keep the paths looking right  on tv1 tv2 tv3 i made a folder called tvshare and moved all files inside
on mov1 mov2 move3 i made folder called movieshare and moved the files inside
on drama1 drama2 drama3  i made folder called drama share and moved the files inside

now my mediashare opens and looks just like it did before but it is one large mhdffs drive.

It should have worked fine.  I started sonar and it seemed to read all the shows like before.   the problem was when I tried to go to series    then click any show   then click edit.    
It would show the shows path.   /mnt/mediashare/tvshare/showname    if i clicked the browse it should open and show me the files in that folder but it opens   /mnt/mediashare/tvshare  and shows me list of all the shows.

If i click the browse and scroll to the show and click its name then ok  it will update the path with a / at the end    so /mnt/mediashare/tvshare/showname/       
So i thought ok ill just edit all the shows and change the path to have /     but this took to long.

so i just deleted the database and had it reload the shows.   oh  also this took a long time.  you should try it some time its horrible you have to click ok for each show name like hundreds of times i used a mouse clicker do do that while i slept.
Finally i got all the shows loaded in again and well there is still no slash  and the file browser is still opening to the wrong location.

I may try changing the mediashare mount location next.       Also   radarr has the exact same problem   but sickrage works ok.

there is no errors in the logs  

on on mint linux 18     sonarr2.0.0.5228   mono 4.2.3

**Comment by tostane** [comment]
i deleted the folder /mnt/mediashare   that i was mounting mediashare into and just let the mhdffs in fstab create it  but this still did not fix the file explorer problem in sonar.     I need more ideas.

**Comment by markus101** [comment]
The file browser uses a last slash to determine which folder it should load folders for, I think we can improve that.

I'm really wondering why you went from the file browser opening to the parent folder to starting from scratch, feels like buying a new car because you got a flat tire or something equally as drastic.

**Comment by tostane** [comment]
I have had this working for years.. for some reason the / problem happened when I remaped my drives.
now sonar does not seem to be seeing the shows in the tv folders.
the only way i seem to be able to get it to work is edit every show and add a / to the end of the path.

I tried to export the database series    as a csv  then used notepad ++ to edit it and add the /  but I could not get it to import and over write the other series.        I dont  know how to use sql  to edit it and was not able to get it to load in open office.     
the source code for sonar is to complicated for me to understand so i could not find were it deals with that path.      It has to be something simple   but its beyond my ability.

**Comment by tostane** [comment]
oh i have over 1400 series i was tracking and editing this manually is a pain.

**Comment by markus101** [comment]
The slash has nothing to do with Sonarr being able to see your folders, it only affects the initial view of the file browser. If Sonarr can't see the series folder then it could be permissions, or something else, but the trailing slash is irrelevant.

If you're having an issue with Sonarr accessing the series folders (I'm not sure if you are based on the information you've provided), open a thread on the forums for support. We'll fix up the folder browsing when editing a series' path.

**Comment by tostane** [comment]
well yesterday it would access the series folder                today it will not.      all i changed was the mount for the drives

**Comment by tostane** [comment]
permissions are set to pretty much 777   on the files

**Comment by tostane** [comment]
i can make a video of the slash  not letting me see the files if that is what it takes

**Comment by markus101** [comment]
The folder browser when editing a series path doesn't show files.

If Sonarr can't see a folder, check the permissions, given you changed the mount and nothing else the issue must lie with that.

As mentioned, please open a thread on the forums for support.

**Comment by tostane** [comment]
oh   the way i found out about the slash is when i click edit  in the series  and it opens the browser to the root of the tv shows      instead of the show it self    i would find the show and click it then press ok.   that is when   sonar added the / in the path      I was not putting it there

**Comment by tostane** [comment]
i see the folder    mediashare/tvshows   permissions    for group    were set to access only    i change it to r/w and trying that now

**Comment by tostane** [comment]
no luck  still not opening the show folder.   here is what i do
open sonar in browser            click series button          then on any show in the list click the edit button on the far right that looks like a wrench.         a window opens   on that windows i go to path and on the right is a folder button.   I click that  and it opens        the root of my tvshows.           but in the path it says /mnt/mediashare/tvshows/dashow....            it should be showing me contents of dashow...

**Comment by tostane** [comment]
there was only one change i really made and that was adding  a tvshow folder to each drive.  Im going to change its permsiison to 777 and see it that helps

**Comment by tostane** [comment]
I did this because mhdffs was getting so slow.  I noticed if you put lots files in the root of a drive it slows way down.  So I put 1 folder on each drive then fill it with the files to keep speed faster.    but now i need fix this / dilemma.

**Comment by tostane** [comment]
gonna take a while to change permissions on these drives i have this running on an i7 i think it would be faster.

**Comment by tostane** [comment]
I went to a fresh ubuntu install with sonar on it and created a folder   /video/the 100
then in sonar I did add new show the 100 and pointed to that folder

now on the series browser i see the 100   so i click edit and look at the path  and it is  /video/the 100

so i click the folder to change path and i browse to the 100 folder again and press ok   and it changed the path to be  /video/the 100/     it now adds the trailing slash.       if i click save     
I get a error message    "path is already configured as a root folder "


why is this machine giving error when other does not.         the only difference is this second machine is not using a mounted drive.

**Comment by tostane** [comment]
I found this guys thread  but removing and readding the root did not fix it.   https://forums.sonarr.tv/t/path-is-already-configured-as-root-folder/2612/17

**Comment by tostane** [comment]
could this be caused by some updated that happened in Linux in the last few days.   But both machines seem to not see the /  and they are  mint and ubuntu    do i need to change to a differnt linux

**Comment by tostane** [comment]
what do you develop this on you dont seem to see the error i do ?

**Comment by tostane** [comment]
I just installed sonarr for windows.            and when you go to a series and click browse it actually opens the series folder.   this seems to be only a problem in linux

**Comment by tostane** [comment]
wait windows has the same problem  i noticed when i added the show it did not create the folder it just made a path for it.       but if you manually create the folder for the show  then go to the series   edit and browse   to the path and click ok    it changed the path to    c:\vid\the 100\        it uses a differnt slash \than linux / but does the same thing and changes the path to have a slash.    now if you browse again it will list the  items in the folder.
