### ISSUE TITLE
series path missing trailing slash / or \  depending on os    tested ubuntu mint and windows

### ISSUE THREAD

**Issue by tostane** [Sonarr/Sonarr#2702]
I tried this on 3 different os   with fresh installs and sonar needs to have the trailing slash on the path to work right it seems.  

windows needs /        linux needs \           How can I add the slash to the path of all my shows.   when it adds new shows it is not putting the slash.

**Comment by tostane** [comment]
I found this bit of code in the source    would it be possable to have it also add the trailing slash

     private static string FixSlashes(string path, OsPathKind kind)
        {
            switch (kind)
            {
                case OsPathKind.Windows:
                    return path.Replace('/', '\\');
                case OsPathKind.Unix:
                    return path.Replace('\\', '/');
            }

**Comment by tostane** [comment]
It is slowly finding and adding the shows even though there path does not have the trailing slash.   It is strange that this used to open the show folder,  now it is opening the root folder when you click browse on any show.

**Comment by markus101** [comment]
As I've said already, the trailing slash is only needed to tell the Folder Browser how to browse, and I've closed and tagged the issue appropriately. It is not the source of your other issues.

Please use the forums for support or any further questions.

**Comment by tostane** [comment]
thanks  I was only conserned as it was opening the series folder before. I thought it had broken after i moved drives.
