### ISSUE TITLE
cleanTitle issue with Magnum P.I. 1980 vs 2018

### ISSUE THREAD

**Issue by ressikanflute** [Sonarr/Sonarr#2703]
`Request Failed. GET /api/manualimport: Sequence contains more than one element`
https://pastebin.com/cnij9ubR

http://x.x.x.x:8989/series/magnum-p-i
http://x.x.x.x:8989/series/magnum-pi-2018

**Comment by markus101** [comment]
Please provide all the requested information, including the debug logs, not just a snippet that contains the error.

**Comment by ressikanflute** [comment]
Figured that wasn't needed as this has happened several times earlier with other series. Copy/paste solution.

**Comment by ressikanflute** [comment]
K. So:

Add series: Magnum, P.I. 1980
Add series: Magnum P.I. 2018
Download the 1980-version somewhere else and move the files to server. 
Attempt to import it, but get err.msg:
> Unable to load files for manual import. Check logs for more details.

Logs are in orig post.

Keyword "cleanTitle". Your comments on the other issues and forum threads are that maybe the cleanTitle-function shouldn't make the titles that clean. Short term solution is to manually change cleanTitle of those two series to make them distinguishable.

**Comment by markus101** [comment]
> Logs are in orig post.

Debug logs would show additional information including what is being processed, not just the error message.

There is no way to change how `cleanTitle` works in this case, the only difference in the title is the comma, which isn't used in release names and needs to be removed. The only viable solution here is an alias for the original series of `Magnum PI` and for the 2018 series a `Magnum PI 2018` alias (I'm assuming the releases will use that, if not it's going to be messier).

Refresh the series, it should be good now.
