### ISSUE TITLE
Search returning wrong results

### ISSUE THREAD

**Issue by kevin182** [Sonarr/Sonarr#2706]
Search for Saturday Night Live season 43 returns wrong episode numbers. Example shown: manual search for S43E04 returns results for S43E06. The log confirms that the wrong search peformed.

![image](https://user-images.githubusercontent.com/32300779/44028124-e3f78176-9ec6-11e8-8de5-8dfd8ed463d4.png)

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/2282704/sonarr.txt)

 - Sonarr Version: 2.0.0.5228
 - Operating System: Windows 10
 - .net Framework Version: 4.7.02556

**Comment by markus101** [comment]
This is because it's remapped on thexem.de and is expected because of that.
