### ISSUE TITLE
NotifyMyAndroid No Longer Exists

### ISSUE THREAD

**Issue by AtomicBones** [Sonarr/Sonarr#2709]
NotifyMyAndroid needs to be removed from the code base, as it's no longer available.

The Developer's behind NotifyMyAndroid shut it down on May 24th due to Concern's about the GDPR. This alone should concern people about how their data was being used.

Anyway, this Reddit Topic goes into further detail https://www.reddit.com/r/Android/comments/8l0cim/notify_my_android_is_dead/

It should be removed from Sonarr to avoid confusion, and to shrink the code a little 👍

**Comment by AtomicBones** [comment]
Also looks like PushALot is gone as well now.

**Comment by markus101** [comment]
Done in the v3 cleanup work.
