### ISSUE TITLE
Kodi NFO Show ID Improvement

### ISSUE THREAD

**Issue by Redundant1** [Sonarr/Sonarr#2711]
Sonarr creates NFO files like this:

```
<tvshow>
  <title>Dark Angel</title>
  <rating>8.4</rating>
  <plot>[...snip...]</plot>
  <episodeguide>
    <url>http://www.thetvdb.com/api/1D62F2F90030C444/series/76148/all/en.zip</url>
  </episodeguide>
  <episodeguideurl>http://www.thetvdb.com/api/1D62F2F90030C444/series/76148/all/en.zip</episodeguideurl>
  <mpaa>TV-14</mpaa>
  <id>76148</id>
  <genre>Action</genre>
[...snip...]
```
However, some features require a little bit more info (as described on the [Kodi Wiki](https://kodi.wiki/view/NFO_files#Troubleshooting)), such as the [Lite IMDB Ratings Update](https://forum.kodi.tv/showthread.php?tid=316342) addon.

In this instance, it’s looking for a **uniqueid** field for either IMDB or TVDB.  If the **id** field contains a TVDB identifier, then the **uniqueid** field should be as follows:

```
  <id>76148</id>
  <uniqueid type="tvdb" default="true">76148</uniqueid>
```

If the **id** field contains an IMDB identifier, then the **uniqueid** field should be as follows:

```
  <imdb>tt0204993</imdb>
  <uniqueid type="imdb" default="true">tt0204993</uniqueid>
```
The same would be true for movies. If there's interest in this request, I'll create another one for Radarr, as well.

I posted this on the Sonarr forums, but it looks like GitHub is the preferred place for "issues".

**Comment by CollinChaffin** [comment]
Just curious could this change (prior to it) be why recently sonarr has not been placing any "rating" in the metadata NFO/xml it creates for TV shows that DO have it available, when prior seasons (using older Sonarr versions) do have the rating element present in the file(s)?
