### ISSUE TITLE
 [Feature Request] adding 1337x tracker 

### ISSUE THREAD

**Issue by clappingmonkey** [Sonarr/Sonarr#2714]
I suggest adding 1337x tracker to the list of supported indexers.

The tracker is public, it is open, well organized, has huge db of old and new series. Good release groups like qxr upload there. So it'll be really nice to have it on Sonarr.

**Comment by RaizeTheLimit** [comment]
You can currently add it via Jackett

**Comment by markus101** [comment]
Unless there is an API (on the site, not an API via screen scraping) that I'm missing (didn't look too hard) this won't be added. Sonarr only supports indexers with proper APIs, Jackett can be used to screen scrape and convert it to a format Sonarr understands.
