### ISSUE TITLE
Consider adding a {Original FileTokens} renaming option that parses original filename for a string(s) and presents those as a list.

### ISSUE THREAD

**Issue by chrisallen** [Sonarr/Sonarr#2715]
**Describe the problem**
Right now we have no way to keep tokens such as `AMZN` or `NF` in the original filename.

**Describe any solutions you think might work**
Ideally we could have `AMZN` and `NF` in a list that you search for in the filename (using `.` or ` ` as a search delimiter) then present this list as a token called `{Original FileTokens}`

**Example:**

- **Original File Name:**
`The.100.S05E01.Eden.1080p.AMZN.WEB-DL.DD+5.1.H.264-CasStudio`
- **Search Strings:** `('AMZN', 'NF', 'iTunes')`
`{Original FileTokens}` = `('AMZN')` # based on what it found in the original filename
- **New FileName Format:**
`{Series.CleanTitle}.S{season:00}E{episode:00}.{Episode.CleanTitle}.{Quality.Title}{.Original.FileTokens}{.MediaInfo.VideoCodec}{.MediaInfo.AudioCodec}{.MediaInfo.AudioChannels}{-Release.Group}`
- **New FileName:**
`The.100.S05E01.Eden.1080p.WEB-DL.AMZN.h264.EAC3.5.1-CasStudio.mkv`

If there was more than one token found, we return them in the order found in the original filename, and use either "space" "period" or "underscore" as a seperator, based on how the user typed `{Original FileTokens}`

`{Original FileTokens}` = ` ` # single whitespace
`{Original.FileTokens}` = `.` # single period
`{Original_FileTokens}` = `_` # single underscore

**Comment by markus101** [comment]
Done in the v3 work through preferred words.
