### ISSUE TITLE
"Completed Download Handling -> Remove" does not work with Transmission

### ISSUE THREAD

**Issue by tmortagne** [Sonarr/Sonarr#2716]
I have the following setup:

![transmission](https://user-images.githubusercontent.com/89175/44857217-9969df80-ac6f-11e8-9112-2b80e4c58e31.png)

and I do have the following notifications in Activity:

![preacher](https://user-images.githubusercontent.com/89175/44857403-08dfcf00-ac70-11e8-874f-c5eb9a5e7fa7.png)

yet the file is still in Transmission history and in Transmission download folder.

**Comment by markus101** [comment]
The seed ratio needs to be met (and the likely the torrent paused in Transmission), see https://forums.sonarr.tv/t/sonarr-does-not-remove-torrent-from-transmission-list-after-it-finishes-the-import-and-when-it-has-status-seeding-complete/19466/8 for a recent discussion on this.

**Comment by tmortagne** [comment]
@markus101 the ratio of the torrent I'm talking about is 2.73 right now according to Transmission and I did not set any "Seed Ratio" in the indexer setup so I really don't see why it's not deleted.

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/blob/ca22a25842a3b1da76a0acd5e081f1fdd73f3ad6/src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs#L101-L103

Is the logic for it to be allowed to be removed, so it's going to depend what Sonarr is getting back for the status, seed limit and seed ratio limit. Trace logs will show all that.

**Comment by tmortagne** [comment]
Hmm the documentation of the `Seed Ratio` field seems to suggest that if Transmission does not have any "Stop seeding ..." configured Sonarr will never remove it, is that it ?

**Comment by markus101** [comment]
Sonarr has always required the torrent to be stopped to remove it. That was done whether stopped manually or via Transmission's seeding limits.

In addition to stopping the torrent, Sonarr now requires the ratio to be met before removing it, either via Transmissions built in ratio limit, or Sonarr specifying the seeding limits and transmission stopping it when that limit is reached (I'm not sure how it behaves if Transmission doesn't have seeding limits set globally, but Sonarr sets it for the torrent it added).

> Hmm the documentation of the Seed Ratio field seems to suggest that if Transmission does not have any "Stop seeding ..." configured (and Sonarr does not have any "Seed Ration" configured) Sonarr will never remove it, is that it 

Yes, that is the case.

**Comment by tmortagne** [comment]
OK thanks a lot for your help !

`Completed Download Handling -> Remove` documentation in the UI would deserve a bit more details on how Sonarr decide to delete a torrent since by default just enabling it won't do anything which can come as a surprise for most users :)
