### ISSUE TITLE
TV ratings no longer being added to many shows XML created by Sonarr

### ISSUE THREAD

**Issue by CollinChaffin** [Sonarr/Sonarr#2718]
**Describe the bug**

Many TV shows recently are missing the IMDB "rating", while others properly have it but it is missing more often than there in latest version of Sonarr.

Example #1 created with latest version 2.0.0.5246 (has IMDB but void of "rating" element):
LINK: https://www.thetvdb.com/series/castaways/episodes/6733434
NFO/XML produced by Sonarr
````
<episodedetails>
  <title>Abandoned</title>
  <season>1</season>
  <episode>1</episode>
  <aired>2018-08-07</aired>
  <plot>12 people embark on a journey into the unknown.</plot>
  <displayseason />
  <displayepisode />
  <thumb />
  <watched>false</watched>
  <fileinfo>
    <streamdetails>
      <video>
        <aspect>1.77777779</aspect>
        <bitrate>0</bitrate>
        <codec>x265</codec>
        <framerate>0.0</framerate>
        <height>720</height>
        <scantype></scantype>
        <width>1280</width>
        <duration>42.294216666666671</duration>
        <durationinseconds>2537.653</durationinseconds>
      </video>
      <audio>
        <bitrate>0</bitrate>
        <channels>2</channels>
        <codec>AAC</codec>
        <language></language>
      </audio>
    </streamdetails>
  </fileinfo>
</episodedetails>
````

Example #2 also created with latest version 2.0.0.5246, also has IMDB info on thetvdb, but properly has the "rating" element:
LINK: https://www.thetvdb.com/series/better-call-saul/episodes/6757077
NFO/XML produced by Sonarr
````
<episodedetails>
  <title>Something Beautiful</title>
  <season>4</season>
  <episode>3</episode>
  <aired>2018-08-20</aired>
  <plot>Jimmy puts a risky plan into motion; as alliances shift, Nacho finds himself in the crosshairs; Kim contemplates her future.</plot>
  <displayseason />
  <displayepisode />
  <thumb>https://www.thetvdb.com/banners/episodes/273181/6757077.jpg</thumb>
  <watched>false</watched>
  <rating>7.0</rating>
  <fileinfo>
    <streamdetails>
      <video>
        <aspect>1.77777779</aspect>
        <bitrate>10992661</bitrate>
        <codec>x264</codec>
        <framerate>23.976</framerate>
        <height>1080</height>
        <scantype>Progressive</scantype>
        <width>1920</width>
        <duration>42.420166666666667</duration>
        <durationinseconds>2545.21</durationinseconds>
      </video>
      <audio>
        <bitrate>640000</bitrate>
        <channels>6</channels>
        <codec>EAC3</codec>
        <language>English</language>
      </audio>
      <subtitle>
        <language>English / English / English</language>
      </subtitle>
    </streamdetails>
  </fileinfo>
</episodedetails>
````

**Screenshots**
See above

**Logs**
Metatdata above do not have specific logs but can clearly see the issue above and it is wide-spread on many TV shows lately.  Will assist in capturing newer logs if needed.

**System Information**

 - Sonarr Version: 2.0.0.5246
 - Operating System: Win7x64
 - .net Framework (Windows) or mono (macOS/Linux) Version: dotnet 4.8x

**Comment by markus101** [comment]
Ratings are only included when there are rating for the series (when generating series metadata) or the episode (when generating episode metadata). Valid being Sonarr has ratings and there is at least 1 vote. That episode has no votes and no rating so nothing is added to the XML.

**Comment by CollinChaffin** [comment]
Just a follow-up, where are you seeing the votes and rating on thetvdb at all?  I assumed it was pulling them from imdb when that link was on thetvdb sorry!  Why am I not seeing an actual numeric or star rating on thetvdb?  Damn my old age LOL!

**Comment by markus101** [comment]
I looked at the API because their UI was completely hosed for the episode.

![image](https://user-images.githubusercontent.com/413544/44867169-ecc23a80-ac3b-11e8-8b0e-306854b5e8c4.png)

For shows they used to show it in the UI somewhere, but I'm not seeing it (aka it's not jumping out at me).

**Comment by CollinChaffin** [comment]
Try again I've been getting that sporadically all day.....refresh and it pops up.

**Comment by CollinChaffin** [comment]
The "Better call saul" shows a rating of 7.0 in the XML that Sonarr is getting somewhere, I just can't find it on thetvdb (or any ratings for that matter) so I assumed it saw the IMDB show/ep link and got the rating from IMDB so now I've even more interested in how the metadata collection from Sonarr really works - because I've got many shows that IMDB show ratings (thetvdb whole site shows none), with new episodes of the exact same show that DOES have an overall rating (via Sonarr XML) in the past now not in new XML files.

Again not trying to argue just super-confused and want to try to get my metadata to reflect what I'm seeing online or at least be consistent.  It really seems that NEW stuff that Sonarr is grabbing does NOT have a rating that used to (same shows) so was pretty sure it was a Sonarr thing since it's what's creating that XML file.

Thanks again for explaining!

**Comment by CollinChaffin** [comment]
As a follow-up I did an additional test I certainly should have before opening the issue (my apologies) and deleted ONLY the metadata for an older episode of "Better Call Saul", and told Sonarr to refresh the entire season to see if it's newly re-created XML matched the old, or was missing the rating....and you're absolutely correct it was a perfect match so all I can think is that this numeric "star" like user-rating on thetvdb is ONLY even available/visible using API calls and NOT on the website itself (which is ludicrous IMO).

Next steps for me now will have to be to scrape via the API myself to determine which darn shows/episodes are missing ratings, and perhaps add at least a rating myself to add some consistency. :)

**Comment by CollinChaffin** [comment]
FYI, here is the official answer....which it sounds like you were also not aware of.  The answer is....thethdb USED TO support show ratings AND NO LONGER DOES!  This is/was due to the v2 site redesign (absurd IMO) and old/legacy shows pre-v2 site still have ratings and in such are still being handed out via the API but new shows added since the v2 cutover - DO NOT AND WILL NOT have the ability for users to add ratings.

Quote:
````
Ratings were a function of this site but the redesign made it impossible for users to continue using it. The shows that had ratings before the redesign continue to have it served through the API but the new shows do not and nothing happens for that field.
````
Source:  https://forums.thetvdb.com/viewtopic.php?f=116&t=47504


NOTE:  His answer does not, however, explain to me how brand new episodes of "Better Call Saul" and other old shows with new episodes are pulling down via API ratings for new episodes, unless they are simply (my guess) being carried forward from the series which ultimately is old enough to have existed pre-v2-cutover.

**Comment by markus101** [comment]
Another casualty of the v2 site.

I wonder if the ratings are coming through the API (I believe it was possible to rate episodes from media player applications previously) and people (well 1 person) has been rating these Better Call Saul episodes.

So far the first 3 episodes of season 4 have 1 person rating them, with scores of 10, 7 and 7, in order.

**Comment by CollinChaffin** [comment]
Ahh, very interesting!  Unless of course it is one of the site admins still having write-access to ratings, LOL!  I know I was on the list of not being a fan of the v2 myself I still remember those first days when they had deemed an "all seasons" was no longer needed and was simply gone and that backlash forcing a quick re-implementation.

I couldn't figure out either how given his comments any new episodes could be showing a rating.  I certainly cannot enter any rating via web but you're right perhaps there's still a player out there that can - but was a SET to ratings ever available via API?  This makes me want to begin digging deeper into their v2 API now even more.
