### ISSUE TITLE
"Access to Path Denied" when importing episodes

### ISSUE THREAD

**Issue by finch6** [Sonarr/Sonarr#2719]
**Describe the bug**
Sonarr doesn't seem to be able to access my NAS drive for transferring the episodes once downloaded. The episode downloads fine to the /transmission/ folder on my NAS, but when the download is complete, it doesn't transfer the epodes to the relevant series folder on the NAS.

**Logs**
<img width="920" alt="screen shot 2018-09-01 at 09 20 39" src="https://user-images.githubusercontent.com/42886484/44943535-596a4000-adc8-11e8-9151-178da247a06f.png">

<img width="781" alt="screen shot 2018-09-01 at 09 27 28" src="https://user-images.githubusercontent.com/42886484/44943608-49069500-adc9-11e8-9afd-8e35bda1b7e2.png">

<img width="782" alt="screen shot 2018-09-01 at 09 27 02" src="https://user-images.githubusercontent.com/42886484/44943609-49069500-adc9-11e8-9e63-d20e110c27ae.png">

<img width="785" alt="screen shot 2018-09-01 at 09 26 47" src="https://user-images.githubusercontent.com/42886484/44943610-499f2b80-adc9-11e8-835a-13bfaab786e1.png">

<img width="782" alt="screen shot 2018-09-01 at 09 26 21" src="https://user-images.githubusercontent.com/42886484/44943611-499f2b80-adc9-11e8-9514-5e8e2d128a86.png">

**System Information**
- Version 2.0.0.5245
- Mono Version 5.14.0.177
- AppData directory /mnt/dietpi_userdata/sonarr
- Startup directory /opt/NzbDrone

**Additional context**
This was all working perfectly but it seems that when I installed a whole fresh start to Sonarr (my dietpi image was old and needed a clean install, so I copied all the old setting from the old install to the new install. I did this by opening two webpages to the 2 systems UIs and made the setting of the new install the same as the old install.

**Comment by markus101** [comment]
Please open a thread on the forums for support. Sonarr either can't read and write the source or the destination path.
