### ISSUE TITLE
Are there any plans for a Telegram integration?

### ISSUE THREAD

**Issue by Pantar2205** [Sonarr/Sonarr#2721]
Are there any plans for a Telegram bot or something like that?

**Comment by markus101** [comment]
> Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

For questions please use the forums.

We do not have plans to create and maintain a telegram bot, Sonarr supports notifications through telegram and there is https://github.com/onedr0p/telegram-sonarr-bot (which hasn't been updated in a while, but there could be an active fork).
