### ISSUE TITLE
Combine multiple episodes of same show on same day in calendar

### ISSUE THREAD

**Issue by acrane13** [Sonarr/Sonarr#2724]
**Describe the problem**
With shows starting to release all their episodes on the same day, the calendar view can get a little long. Especially in the monthly view. Having one chicklet per episode is nice to quickly glance at to make sure all the shows have been downloaded, but if I'm trying to get an overall picture of the month it involves a fair amount of scrolling. More so towards the end of the month.

**Describe any solutions you think might work**
I think a nice solution to this would be to merge multiple episodes into one chicklet if there are more than 2 on the same day. This new chicklet could be colored like a progress bar to show the state of the episodes it represents and have a hover state that could list the episodes and their states as it does now.

**Additional context**

**Comment by markus101** [comment]
This is done in the v3 work.
