### ISSUE TITLE
Sharing Indexer and Download Configurationwith Xarr

### ISSUE THREAD

**Issue by hughesjs** [Sonarr/Sonarr#2725]
**Describe the problem**
It's a pain in the ass if you're running Radarr, Lidarr and Sonarr to go around and adjust your indexer and download client settings on each one separately when, in all likelihood, they're nigh identical (except maybe categories).

**Describe any solutions you think might work**
Either store these settings in an XML file and add a configuration option to set which file to load these configs from or add an export/import indexers mechanic.

**Additional context**
Lidarr Issue: https://github.com/lidarr/Lidarr/issues/479
Radarr Issue: https://github.com/Radarr/Radarr/issues/3010

**Comment by markus101** [comment]
The settings are stored in the database, no plans to change that.

As for updating, anything you can do in the UI you can do through the API, the endpoints may not be documented and could change, though for indexers they haven't in a while.

An interested person could write something to update all 3 at the same time or using Jackett/NZBHydra could ease the maintenance.

Sharing configuration with other apps isn't something we have plans to do.
