### ISSUE TITLE
Quality Definitions size limits don't match actual limits

### ISSUE THREAD

**Issue by danielb2** [Sonarr/Sonarr#2730]
**Describe the bug**

When setting max download limit to 444mb for a 25 minute episode, the cutoff as displayed by a manual search is shown as being 370mb.  The values should match.

**Screenshots**

Size limit settings:

> ![screen shot 2018-09-12 at 09 05 04](https://user-images.githubusercontent.com/26678/45438096-1da66480-b66b-11e8-806d-befa33c364e5.png)

Manual search results:

> ![screen shot 2018-09-12 at 09 06 00](https://user-images.githubusercontent.com/26678/45438139-3f075080-b66b-11e8-8403-cb3cb34c98a1.png)

when hovering over the info icon:

> ![screen shot 2018-09-12 at 09 05 32](https://user-images.githubusercontent.com/26678/45438146-462e5e80-b66b-11e8-9575-1d873f89eed5.png)

**System Information**

 - Sonarr Version: 2.0.0.5228
 - Operating System:  FreeBSD 11.1-RELEASE-p10
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono JIT compiler version 5.10.1.47

**Comment by markus101** [comment]
You set a limit of 440MB for a `30` minute show as shown in the tooltip: 
![image](https://user-images.githubusercontent.com/413544/45438689-a671d000-b66c-11e8-9373-5c1a45e88d4d.png)

The sizes are all calculated at MB per minute, at approximately 14.7MB per minute, the limit for a 25 minute show would max out at 367MB.

**Comment by danielb2** [comment]
@markus101 thanks for the explanation
