### ISSUE TITLE
Failing to add some new series

### ISSUE THREAD

**Issue by Stonepusher** [Sonarr/Sonarr#2733]
I've noticed a couple of series which I was unable to add to Sonarr recently.  Upon selecting add series and typing in the name (or part thereof) it responds 'Couldn't find any results for <Series Title>'.

I should point out that this occurrence is rare and of course mostly adding series works just fine.

Upon searching for the series at thetvdb I get a result and see the series number.  When I go to jacket and search for the failed results I get responses from my Indexers directly.

Clearly this series exists and both THETVDB and Jackett know about it.  (Yes I know Sonarr only uses thetvdb to determine series number etc.).

Upon enabling debug logging all I see when I search for the series is an entry that states:
|Debug|Api|[GET] /api/v3/series/lookup?term=<SERIES-TITLE>: 200.OK (520 ms)

Nothing else.  No success. No Failure.

If I try entering thetvdb:<SERIES-NUMBER-FROM-TVDB> into the add new series name field it responds:
Failed to load search results, please try again.

**System Information**

 - Sonarr Version: 3.0.0.232
- Mono Version: 5.14.0.177
- Linux container (lsiodev/sonarr-preview)
 - .net Framework (Windows) or mono (macOS/Linux) Version: Whatever you embed in the container

**Comment by markus101** [comment]
Please provide feedback on alpha issues on the forums/subreddit as requested.
