### ISSUE TITLE
Unable to add specific series.

### ISSUE THREAD

**Issue by Magma2222** [Sonarr/Sonarr#2734]
When attempting to add a certain series I get the following error.

NzbDroneErrorPipeline | Request Failed. POST /api/series: Failed to read complete http response

Logs below.

https://pastebin.com/Z0wbd14N

**System Information**

 Version 2.0.0.5228
 Unraid 6.5.3
 Mono 5.14.0.177

I restored a backup from yesterday and still receive the same error. Other series can be added without issue.

**Comment by markus101** [comment]
Please provide all requested information, including the mono version.

**Comment by Magma2222** [comment]
> Please provide all requested information, including the mono version.

My mistake. Updated original post.

**Comment by markus101** [comment]
Are you still seeing this error? There were server issues several hours ago that would have caused this (unfortunately mono doesn't gracefully handle that scenario it seems).

Next time also include the debug logs, the error itself often doesn't contain all the context.

**Comment by Magma2222** [comment]
Unfortunately still having this error and only for this particular show.

Here's the debug log during that error.

https://pastebin.com/Y2WrSA9D

**Comment by markus101** [comment]
I'm not having issues adding that series, but I've cleared the cache for it in case that was the issue.

Closing the issue as this doesn't appear to be a bug in Sonarr or skyhook. I see you also posted this on the forums, best to update your post there with the correct information and we can discuss it further there if necessary.

**Comment by Magma2222** [comment]
Updated forum post with new debug log. Issue still ongoing
