### ISSUE TITLE
sonarr fail to add series because the name is on spanish

### ISSUE THREAD

**Issue by icf20** [Sonarr/Sonarr#2735]
hello i am testing this app and i realize that it  fail to get any spanish tv series
i made tests with "los 100" and "vikingos" 

here are steps to reproduce

- have spanish only indexers ( using jackett there are 2 public)
- search on the indexer to see if there are any results and confirm there are  :heavy_check_mark: 
- using the keyword vikingos in the add new series search bar will produce nothing
- using the word "wikings" will show up the series but nothing will be found for the obvious reasons 

https://www.themoviedb.org/tv/44217-vikings?language=es-ES
https://www.themoviedb.org/tv/48866-the-100?language=es-ES

 - Sonarr Version: 2.0.0.5228
 - Operating System: freenas  11.2

**Comment by markus101** [comment]
Please read the FAQ. Sonarr uses TheTVDB, not TheMovieDB, only handles English metadata (at least for the time being) and we have a process for aliases/other language titles for series.

**Comment by icf20** [comment]
oh! that was unexpected
