### ISSUE TITLE
Adding some kind of .ignore-script to specific folders

### ISSUE THREAD

**Issue by pven** [Sonarr/Sonarr#2737]
I have a serie, lets say it is four seasons. Season 1 until 3 is at my disk as ISO, season 4 is a bunch of mkv's. When Sonarr scans this serie-folder, it tells me for S1 until S3 it has unknown files. So I want to exclude those three folders. But how? I am quite sure some kind of ignore-option for a folder is not available for Sonarr.

Can this be created? Is there a workaround?

**Comment by markus101** [comment]
You can unmonitor those series in Sonarr or name the files in such a way that Sonarr can parse them to their specific episodes.

An ignore option is not available and we do not have plans for one either.
