### ISSUE TITLE
SSK Synology documentation needs to be updated

### ISSUE THREAD

**Issue by LwsBtlr** [Sonarr/Sonarr#2738]
[https://github.com/Sonarr/Sonarr/wiki/SSL#wiki-pages-box](url)

Mentions entering a certificate hash in the Settings/General (Advanced) tab. There is no such field.

After following the synology instructions, Sonarr still will not respond on the SSL port, and logs the following at startup:

`var/nzbdrone.log:[Info] OwinHostController:   https://11.22.33.444:9898/ `

Where 11.22.33.444 is a stand-in for my IP. This is concerning since it needs to be binding to https://signeddoamin.tld:9898. If the Bind address is changed in sonarr to '*' sonarr still will no load a secure page (at least not according to Chrome).

I have scripted this, by the way, since installing a new cert every three moths is a pain: The values of the CERTROOT and ROOTDOM would be provided by the individual.

    SONARR="/volume1/@appstore/nzbdrone/var/"
	openssl rsa -in ${CERTROOT}/privkey.pem -outform PVK -pvk-none -out ${SONARR}/"${ROOTDOM}".pvk
	openssl x509 -inform PEM -in ${CERTROOT}/cert.pem -outform DER -out ${SONARR}/"${ROOTDOM}".cert

	su sc-nzbdrone -c "/volume1/@appstore/mono/bin/httpcfg -del -port 9898" 
	su sc-nzbdrone -c "/volume1/@appstore/mono/bin/httpcfg -add -port 9898 -pvk ${SONARR}/${ROOTDOM}.pvk -cert ${SONARR}/${ROOTDOM}.cert"

	/usr/syno/bin/synopkg restart nzbdrone

**Comment by markus101** [comment]
> Mentions entering a certificate hash in the Settings/General (Advanced) tab. There is no such field.

That's under the Windows section.

There is a lot of information there besides the Synology instructions that is relevant on that wiki page:

> Mono doesn't support intermediate certificates, which results in a broken chain and the browsers end up requesting a client certificate

And
> The easiest solution for the time being is a reverse proxy with nginx or apache.
This is still our recommendation until we're using a different webserver.

> I have scripted this, by the way, since installing a new cert every three moths is a pain:

Let's Encrypt (and virtually everyone else) uses an intermediate cert, which is not suitable.

If you set a bind address to a specific IP _only_ that IP can be used, other hostnames/IPs will be rejected.

**Comment by LwsBtlr** [comment]
OK, but the mono info about how mono is broken is under Linux/OS X. It's too bad, everything else on my synology is working with SSL, but sonarr isn't and it appears even if it were working, it would not be able to disable the non-SSL connections. Thanks for the info.

**Comment by markus101** [comment]
> OK, but the mono info about how mono is broken is under Linux/OS X.

So is the Synology section. Synology is *nix based.
