### ISSUE TITLE
Replacing old w/ new downloaded files

### ISSUE THREAD

**Issue by DaemonPhoenix42** [Sonarr/Sonarr#2740]
Just a thought, regarding my setup I download a lot of anime and sometimes the Japanese audio, is grabbed first due to release times.
but say I go in and get the English version some time afterward. by allowing the torrent client labels to handle importing, it completely deletes the first version. not so bad, keeps things clean mostly, but what if I wanted to remux the files with the new audio? or just import the old audio to the new file? the old version is not in the trash so I can no longer retrieve it and I either download it again or just wait till someone else does it or the Blue-Ray is released
Is it possible to prevent a complete overwrite and dump the files into the trash?

As a better solution, I'm going to mess with the restrictions but having dual audio options in the profiles would be interesting. not sure how that info is checked though.

Thank you for your software I use it so much now my system is probably configured.

**Comment by markus101** [comment]
If configured deleted files are put in Sonarr's `Recycling Bin` (Settings: Media Management, with advanced settings on), that is the only option to prevent total deletion.

**Comment by DaemonPhoenix42** [comment]
Ohh wow, sorry I didn't notice that, thank you.
Are you aware of a way to set that to the system recycling bin?

My points regarding language profiles still stand unless you can set a hierarchy for exclusion/inclusion tags!

**Comment by markus101** [comment]
There will be https://github.com/Sonarr/Sonarr/issues/274 in v3, but there won't be an explicit "dual" language option https://github.com/Sonarr/Sonarr/issues/385 might be valuable there.

We won't directly support the OS's Recycling Bin/Trash/whatever feature, but you found the location it looks like.
