### ISSUE TITLE
Add Video Encoder to Toolchain

### ISSUE THREAD

**Issue by hughesjs** [Sonarr/Sonarr#2741]
**Describe the problem**
Oftentimes we end up downloading poorly compressed media that is incompatible with our various devices (some smart TVs are really funny about format).

**Describe any solutions you think might work**
So we could add the option for an intermidiate step between download completion where we hook into a video encoder (perhaps handbrake of AME) and automatically transcode the video to a format determined in the profile outputting to the completed download folder.

**Comment by markus101** [comment]
You have the option of using a post processing script (NZBGet/SABnzbd) currently (since torrent clients don't indicate that a script is running it's not very useful) and there is already https://github.com/Sonarr/Sonarr/issues/791 but we do not have plans to do specific steps before import.
