### ISSUE TITLE
Manually added torrents (to Deluge) are not imported automatically

### ISSUE THREAD

**Issue by samsepiol59** [Sonarr/Sonarr#2744]
**Describe the bug**
Manually added torrents to Deluge are NOT processed by sonarr (renamed, moved to correct folder) - the tick in "Activity" becomes yellow and I get the "download wasn't grabbed by sonarr and not in a category skipping" message. Thing is, it works perfectly when downloading something via NZBGet!
This has ALWAYS happened, it's nothing new.

**Screenshots**
I can provide them, but I don't think they're needed

**Logs**
There's nothing in the logs relating to this issue

**System Information**

 - Sonarr Version: 2.0.0.5228
 - Operating System: Ubuntu 16.04
 - mono (Linux) Version: 5.12.0.226

**Additional context**
Nothing to add

**Comment by Dnkhatri** [comment]
Do you put manually added torrents to the sonarr label. I do that and rarely have sonarr miss any only when sonarr is unable to parse the tvshow data like name season or episode. Without logs no one can help you as we don't know what the problem is.

**Comment by samsepiol59** [comment]
It's not that I don't want to post the logs, it's that there is nothing there that indicates a communication and/or something that happened! There is no error, no issue, nothing! It's as if sonarr doesn't even recognise them as TV show files.

Honestly, never heard that "sonarr label" thing! Do I need to manually create it? How would I attach it to the torrents in deluge?

**Comment by markus101** [comment]
The label/category is an option in Sonarr's download client settings (for each client). One needs to be specified AND any manually added torrent needs that label set (Sonarr will also set that label when adding torrents).
