### ISSUE TITLE
Crash when getting media info on PDF file

### ISSUE THREAD

**Issue by benfishbus** [Sonarr/Sonarr#2745]
**Describe the bug**
One of my series has a PDF file associated with each episode (i.e., <episode1.mp4> has <episode1.pdf>).  When Sonarr tries to refresh this series, Sonarr dies.

**Screenshots**
N/A

**Logs**
Log segment taken from console, having launched Sonarr from the command line:
https://gist.github.com/benfishbus/e76ab7ad1beecd1425698040b18e017e

**System Information**
 - Sonarr Version: 2.0.0.5228
 - Operating System: QNAP QTS 4.3.4.0695 (08/30/2018)
 - mono (macOS/Linux) Version: 5.12.0.226

**Additional context**
These PDF files are viewable -- no apparent corruption.  I get valid results when running mediainfo on them at the command line (both with no options and with -Full).

**Comment by markus101** [comment]
We shouldn't be running media info on any non-video file, so something is off there.
