### ISSUE TITLE
Owner of file after Sonarr import is not changed

### ISSUE THREAD

**Issue by tommeh1337** [Sonarr/Sonarr#2746]
I encountered an issue where Sonarr cannot change file permissions (chmod) because the user running Sonarr service is not the owner of the imported file. 

**Scenario** 
1. Transmission downloads a file to /download/series, user owner of this file is now 'transmission' and group owner is 'multimedia' (both transmission and sonarr users are member of this group)
2. Sonarr imports this file to /videos/series using Hardlinks, owner of the imported file is still transmission : multimedia. 
3. Sonarr tries to set permission via chmod and returns an error because the operation is not permitted. This is the case because Sonarr can't change permission of the file without being the owner.

Sonarr should take ownership of the file during importing so the permissions can be set. Couchpotato does this for example. 

**Logs**
`Unable to apply permissions to: /media/Videos/Series/***********: Error setting file permissions: EPERM`

**System Information**
 - Sonarr Version: 2.0.0.5228
 - Operating System: FreeBSD 11.1 (FreeNAS-11.1-U6)
 - .mono (macOS/Linux) Version: 3.10.0

![image](https://user-images.githubusercontent.com/38126487/45954804-497ffd80-c00e-11e8-9664-6af62b956e70.png)

**Comment by markus101** [comment]
Only root can give files away or take them from another user. This is a limition of the OS, Sonarr can't do anything about it.

You should be able to set the user to the same and change the group.

**Comment by tommeh1337** [comment]
@markus101

Thanks for your fast response. How can Couchpotato do this without having root privileges? 

The user owner of the file which is downloaded by transmission is still transmission. But the hardlink file which is created during the Couchpotato import is owned by the couchpotato user. So it seems the owner of the hardlink "file" can be set upon creation without needing root permissions.

If this isn't possible with Sonarr, can you please explain how I am able to solve this issue?

**Comment by tommeh1337** [comment]
I was wrong about the Couchpotato import, it can't set permissions either without having root privileges..

I assume I am not the only one with this 'issue', is there any way to work around this?

**Comment by markus101** [comment]
The only thing that comes to mind is https://unix.stackexchange.com/a/115632/209938
