### ISSUE TITLE
Add sonarr season number to environment for custom scripts on grab (not release season number)

### ISSUE THREAD

**Issue by Yolley** [Sonarr/Sonarr#2748]
**Describe the problem**
I really need, before download of a grabbed episode starts, change directory of the download to series directory (every series has its own directory), so my client(rTorrent) would download an episode there (and not in default directory). I wrote a custom script, which is fired up on "Grab" event. This scripts determines episode season using environment variable "sonarr_release_seasonnumber" and changes directory in rTorrent. The problem is, that in this variable sonarr does not pass the real season (for which sonarr downloads file), but the season, which was parsed from file name I believe. For example, Sonarr grabs and episode of an anime with name "[HorribleSubs] Overlord III - 08 [1080p].mkv", "sonarr_release_seasonnumber" value would be "0", so my script thinks, that this episode is from season zero, and passes directory "Overlord/Season 0" to rTorrent for this download, which is not right. But, if I look in sonarr history I can find a record with eventType "grabbed" for this episode, and there I can see a row "seasonNumber" with value "3". So, if my script had this value, it would be able to determine the real directory for this episode. In my opinion, it is not very effective to also check sonarr history every time the script determines series directory (even if I try to do that, sonarr updates history after custom script exits).

**Describe any solutions you think might work**
It would be great to add the real season number (for which sonarr grabbed an episode) to environment variables for custom scripts on "Grab" event.

Thanks!

**Comment by fryfrog** [comment]
Just curiosity, but are you doing this to organize your seeding torrents or because you point your media player at this folder?

**Comment by Yolley** [comment]
> Just curiosity, but are you doing this to organize your seeding torrents or because you point your media player at this folder?

Both, separate folders for series, so plex could easily grab them, and I also need to seed torrents. I am aware, that sonarr can copy downloaded episodes to their series folder, or hard link them, but I don't want to waste extra space on drive or use hard links.

**Comment by fryfrog** [comment]
Ah, so your download location is also your "final" location. I'm surprised it is working.

I'm curious what your objection to hard links is, since they're basically perfect for what you're doing.
