### ISSUE TITLE
Highlight existing files in interactive search results

### ISSUE THREAD

**Issue by enchained** [Sonarr/Sonarr#2749]
Is it possible to somehow mark already downloaded file in the interactive search results? 
For example, with storing some data when grabbing the episodes, and also comparing checksums (when same file shows up on multiple indexers). This way it's much easier to compare what you alreasy have with other available options without switching tabs back and forth. It doesn't have to work perfectly, but I'm really missing the feature of seeing what you already got. Also, can be useful in case of "currently downloading" - with those slow and steady downloads that could go on for days or weeks.

I'm loving the v3 interactive search by the way, filters and especially labels are a nice addition. I've got a feeling that displaying currently selected filter could improve usability a bit, by saying Filter: FilterName instead of just Filter in the corner. It's probably already planned and too trivial for opening a separate ticket, so I'll just mention it here.

**Comment by markus101** [comment]
Rejections are the only way to see that, though it doesn't indicate which particular release was grabbed. We don't have any plans for that level of detail within the search results, at least at this time.

Displaying the active filter has been brought up previously, not quite sure what we're going to do there, but we'll be taking a look. If you have any more feedback for v3 please open a thread on the forums or the subreddit.
