### ISSUE TITLE
No results found when using MejorTorrent indexer

### ISSUE THREAD

**Issue by oscargb1** [Sonarr/Sonarr#2751]
I'm trying to download the first season of Game of Thrones in Spanish with mejortorrent.org indexer but when I tell Sonarr to search for missing files to download them, it starts the search but in the logs it says "No results found", while if i search the Game of Thrones S1 (Juego de Tronos in Spanish) in mejortorrent.org web it's available for download.
I don't know if it's because I configured it incorrectly but if not I hope you can fix it.

 - Sonarr Version: 2.0.0.5228
 - Operating System: Windows 10

**Comment by markus101** [comment]
Please use the forums for help and support.
