### ISSUE TITLE
Rework Profiles, Quality, Tagging systems for more advanced (and complete) searches

### ISSUE THREAD

**Issue by glc650** [Sonarr/Sonarr#2756]
**Describe the problem**
I have two Profiles I use the most.  One is built around HDTV as those usually include surround sound (except for the HEVC/h.265 encodes) and have desired video quality (unlike most WEBDL).  The other is built around Amazon and Netflix only WEBDL for the same reasons.  Problem is, I haven't figured out how to include both in my automatic searches.  For HDTV I use tags to prevent h.265 files from being downloaded and for WEBDL I use tags to make sure only Amazon or Netflix files are downloaded and h.265 is ok here.  I've found file sizes (Quality), thanks to h.265, to be unreliable.

**Describe any solutions you think might work**
Reworked profile and tagging system.  Maybe allow multiple qualities per series and allow tags to be applied to a series or quality.

**Additional context**

**Comment by markus101** [comment]
We do not have any plans to rework quality profiles in such a way or link restrictions to specific qualities only.

https://github.com/Sonarr/Sonarr/issues/385 might offer some flexibility to help achieve what you want once it's implemented, but not a silver bullet.
