### ISSUE TITLE
Make Sonarr validate a path on his side and return boolean

### ISSUE THREAD

**Issue by morpheus65535** [Sonarr/Sonarr#2758]
**Describe the problem**
In Bazarr, we do path mapping to be sure Bazarr can access an episode file even if he doesn't access it trough the same path. I would like to be able to do a API call to validate what the user have entered in a text field to be a valid path for Sonarr.

**Describe any solutions you think might work**
New API endpoint?

**Additional context**
Thanks! :-)

**Comment by markus101** [comment]
You want to validate whether a path sent to Sonarr exists?
Is it always a file or always a folder or could be either?

The file browser part of the UI does effectively handles the folder part of it, though an empty folder or one that doesn't exist would both get an empty result.

**Comment by morpheus65535** [comment]
I would like to be able to ask to Sonarr trough the API if a directory exist for Sonarr (i.e.: does `/media/series` exist for Sonarr). It would always be a directory.

That way, I would be able to confirm that `/media/series` is valid and can be mapped to `\\server\media\series` that is, after validation, a valid directory for Bazarr.

Sonarr path for an episode: `/media/series/24/S01/S01E01.mkv`
Bazarr path for the same episode: `\\server\media\series\24\S01\S01E01.mkv`

Path mapping in Bazarr would be (common part of both path):
/media/series == \\server\media\series

Does it make sense?

**Comment by markus101** [comment]
It'd be a lot simpler to get the list of series with their root folders and present the user with a drop down of the unique ones. No need to ask Sonarr if it exists, either it does or the user's setup is wrong anyways.

> P.S.: In a wet dream, I would like to be able to browse Sonarr file system trough the API but that would be a little bit more complicated to achieve... ;-)

You already can... take a look at how the UI browses via the file browser.

Given an API endpoint exists for what you ultimately want I'm not going to add anything for simple validation.

PS Sonarr is neither a him or a her. 😄

**Comment by morpheus65535** [comment]
Ok I'll take a look trough Chrome dev tools. Haven't been thinking about it. Thanks! :-)

PS My bad but in french, we don't care if it's a thing or a person, there is only two gender. For once, french is easier than English! ;-)

**Comment by markus101** [comment]
I figured it was a language thing, it's just funny to me as someone that has forgotten most of the French I learned in school.

If you have any questions about it, let me know, it _should_ be pretty straight forward though.
