### ISSUE TITLE
Can't connect to Twitter for notification 

### ISSUE THREAD

**Issue by Francis2b** [Sonarr/Sonarr#2759]
I can't connect to Twitter when I fill the form for Twitter notifiaction. I click the Connect to twitter button but nothing appear and when I click test it tells me to autenticate first.

Here is the log:

```
HTTP Error - Res: [GET] https://api.twitter.com/oauth/request_token: 403.Forbidden
<?xml version="1.0" encoding="UTF-8"?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>
```

**System Information**

 - Sonarr Version: 2.0.0.5228
 - Operating System: DSM 6.2-23739 Update 2 
 - mono Version: 5.8.0.108

**UI Bugs:**
 - OS: macOS 10.14 (18A391)
 - Browser: Chrome 69.0.3497.100 (Official Build) (64-bit) and Safari 12.0 (14606.1.36.1.9)

**Comment by markus101** [comment]
Please use the forums the support.

> Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings

Looks like that's your issue, unfortunately it looks like Twitter is locking down their developer portal and preventing regular users from connecting, which means long term Twitter support is likely in jeopardy.
