### ISSUE TITLE
Support foreign translations for seasons/episodes 

### ISSUE THREAD

**Issue by hazcod** [Sonarr/Sonarr#2762]
**Describe the problem**
Dutch/Flemish releases are not picked up because they often use a different naming convention.
e.g.
```
13 Geboden Se.1 afl.2-3-4 [VTM]
Professor T Se.3 afl.3 en 4
```

**Describe any solutions you think might work**
Handle `Se.` as an alias for `S`, `aflv.` as an alias for `E`.

***Extra***
Perhaps this could be linked whenever a quality profile is set to dutch/flemish.

**Comment by markus101** [comment]
Sonarr does not currently support any foreign season/episode identifiers in names and it's not likely to in the short term.

> Perhaps this could be linked whenever a quality profile is set to dutch/flemish.

Parsing happens before the series and it's associated profiles are known so this would not be possible.

**Comment by markus101** [comment]
More cases:

`Stagione` for `Season` in Italian.

**Comment by bakerboy448** [comment]
no plans for this at this time

**Comment by markus101** [comment]
Still useful to improve this behaviour.
