### ISSUE TITLE
pyLoad real-debrid download torrent

### ISSUE THREAD

**Issue by Floflobel** [Sonarr/Sonarr#2763]
Hello,

PyLoad recently added the ability to download torrents via files or magnets. Would it be possible to add pyLoad as a "download client".

The ticket reference is https://github.com/pyload/pyload/issues/3223

This would be a huge step forward for me as I could ditch the conversion work at real-debrid and reduce my CPU load on my torrent server.

If you need an account for your tests do not hesitate to contact me.

Thank you very much.

**Comment by markus101** [comment]
Similar to https://github.com/Sonarr/Sonarr/issues/2194 with a different inferface into it. No plans for us to support that at this time.
