### ISSUE TITLE
[Feature Request] Update Branch for v3

### ISSUE THREAD

**Issue by rebekah65** [Sonarr/Sonarr#2766]
Can you provide an update branch for Sonarr nightly v3.
Thanks

**Comment by AmineI** [comment]
What do you mean. What version are you on ?

As per what I've read from the forum, (by markus) _There is no direct path from v2 to v3 _ yet, as it is an alpha version and this seems too early to ask for.

And if you're already testing v3, the _develop_ branch is fine and will give you the test updates. [Source](https://forums.sonarr.tv/t/which-settings-for-test-updates/19585)

**Comment by markus101** [comment]
As per the forums and reddit announcement, please keep feedback to those locations.
