### ISSUE TITLE
Indexer search uses wrong search parameters

### ISSUE THREAD

**Issue by Nik--** [Sonarr/Sonarr#2768]
I've added a new series and tried to search for all the missing episodes, only to receive this error:
```
Nyaa HTTP request failed: [400:BadRequest] [GET] at [https://nyaa.si/?page=rss&cats=1_37&filter=1&term=Golden+Kamuy+13]
```
```
HTTP Error - Res: [GET] https://nyaa.si/?page=rss&cats=1_37&filter=1&term=Golden+Kamuy+13: 400.BadRequest
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```

It appears that sonarr uses "term" to search for episodes, while the website expects the following format:
```
https://nyaa.si/?page=rss&cats=1_37&filter=1&q=Golden+Kamuy&c=0_0&f=0
```

As you can see, I need to specify sonarr to use ```q=XXXXXXXX&c=0_0&f=0``` as search parameters instead of the default ```term=XXXXXXXX``` search parameter passed.

There is currently no way to change that, and is making indexer search quite unusable to download episodes from sites such as this.
Also just to point out, finding new episodes works fine with this site, only the indexer search is being utterly broken.

**Comment by markus101** [comment]
@Taloth this looks like a difference with nyaa.si from the original nyaa. Since the original is dead and nyaa.pantsu.cat supports Torznab should we change this?

**Comment by Taloth** [comment]
The indexer in Sonarr is for the defunct nyaa.se site api, not nyaa.si.
nyaa.si has a compatibility layer to support the old query params, but they don't support the cats=1_37 part that nyaa.se did, which the user can modify in the settings by replacing it with the appropriate category filter for nyaa.si.   
Given my bad experience with the nyaa.si dev staff, I'm not going to spend one more minute on it.

**Comment by hukasu** [comment]
Changing the 'cats' option of the 'additionalParameters' variable on src/NzbDrone.Core/Indexers/Nyaa/NyaaSettings.cs from 1_37 to 1_3 or 1_4 (don't know which would be the most correct) suffice?

**Comment by SHJordan** [comment]
Change it to &c=1_0&f=1 and it should work.

**Comment by 19wolf** [comment]
I'm suddenly having this issue- seems like it might relate to https://github.com/nyaadevs/nyaa/pull/594
