### ISSUE TITLE
Sonarr won't start after mono update

### ISSUE THREAD

**Issue by mokas01** [Sonarr/Sonarr#2769]
**Describe the bug**
Sonarr won't start after mono update. It starts the service again and again. Web access fails (502)

**Logs**
result of journalctl -u sonarr.service : 
https://paste.yunohost.org/zixenodono.vbs

**System Information**
 - Sonarr Version:   2.0.0.5252
 - Operating System: armbian (debian)
 - mono (macOS/Linux) Version: 
```
Mono JIT compiler version 5.16.0.179 (tarball Thu Oct  4 12:22:11 UTC 2018)
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-/)
	GC:            sgen (concurrent by default)

```

**Additional context**
I know the mono version is not the one recommended for Sonarr, but i updated from the repository it was on. Until now, no mono update had broken anything. I'd be happy to test further if you need me to. 

Thanks for your help

**Comment by markus101** [comment]
Somehow this is overflowing: `TimeSpan.FromHours(1)` which makes no sense to me. Either a problem with mono or that compiled version of mono. I don't see any reported bugs for mono.

Downgrading would be your best bet for the time being.

**Comment by 5ymph0en1x** [comment]
Same error here on Raspbian after the mono update !
Sonarr, Radarr and Jackett don't start anymore...

**Comment by mokas01** [comment]
downgrading did it.
I don't know but https://github.com/mono/mono/issues/11095 looks like it could be the related issue in mono…

**Comment by msdos** [comment]
> as a workaround until it is fixed, I suggest to use -O=-aot. You can set export MONO_ENV_OPTIONS='-O=-aot' so it will picked up by all programs using mono.

This works.

https://github.com/mono/mono/issues/11095#issuecomment-432955799

**Comment by markus101** [comment]
The mono issue has been fixed.
