### ISSUE TITLE
File corruption during media copy

### ISSUE THREAD

**Issue by xartle** [Sonarr/Sonarr#2770]
**Describe the bug**
Sections of video files are being lost (overwritten?) when the file is copied from the download directory to the video directory.  Maybe this is a request for file verification after copy?

**Screenshots**
Not really applicable.  The players all do the expected things when they hit regions of null characters.

**Logs**
Some example info.
```
-rwxrwxrwx+ 1 sc-radarr radarr 3580172539 Jul 29 04:42 /volume1/video/movies/movie.mkv
-rwxrwxr-x 1 admin users 3580172539 Jul 29 00:44 /volume1/download/movie.mkv

md5sum /volume1/video/movies/movie.mkv /volume1/download/movies/movie.mkv
56075aeffff86e3739fc0107a264db52 /volume1/video/movies/movie.mkv
d2e9e8173038f36721ba735510260b33 /volume1/download/movies/movie.mkv

```
Here's a snip of the hex diff of the binary file. This goes on for multiple megabytes and then the copy resumes.  Sometimes this happens 2 or 3 different times in a file.
```
061a2460: f2c6 d800 7737 16da 9d14 7cd8 7550 32c6 ....w7.... | 061a2460: 0000 0000 0000 0000 0000 0000 0000 0000 ..........
061a2470: 8f3f fe99 c2b9 84ad a751 7151 5ccf 62cc .?.......Q | 061a2470: 0000 0000 0000 0000 0000 0000 0000 0000 ..........
061a2480: f327 73af 5a4f 36c7 6b9e 482a 2624 0c24 .'s.ZO6.k. | 061a2480: 0000 0000 0000 0000 0000 0000 0000 0000 ..........
061a2490: 0c0b 899b 27f3 7876 ac28 9e25 45f2 93c0 ....'.xv.( | 061a2490: 0000 0000 0000 0000 0000 0000 0000 0000 ..........
061a24a0: 034d 920f 1d5c 34d2 3cf5 ae91 6724 12fe .M...\4.<. | 061a24a0: 0000 0000 0000 0000 0000 0000 0000 0000 ...
```

**System Information**

Sonarr Version 2.0.0.5228
Mono Version 5.8.0.108
Running on Synology DSM 6.2.1-23824

**Additional context**
I'm seeing the exact same behavior in Radarr but everything else seems to be working fine.  

Both the download and video folders are on the same media which is a 21TB btrfs volume (3x8tb drives plus a parity drive.  The data integrity scan with the parity on the volume was good. SMART tests are all green as well.

**Comment by markus101** [comment]
Sounds similar to issues with copy to/from a SMB share, though in those cases the file size is different.

We're going to need Trace logs of an import that results in the corrupt file to see what Sonarr did/sees. Sonarr verifies the file size is the same when importing to a different volume, depending how things are setup this could bypass that and Sonarr would never know (not that it would when the file size is the exact same).

I've heard of issues with synology + BTRFS and data corruption/loss though that was ~2 years ago, not sure what progress they've made there.

**Comment by xartle** [comment]
Happy to fetch one.  I just flipped my log setting to trace.  I'll try to trigger a move and hope(?) it fails.

**Comment by Taloth** [comment]
Sonarr logs won't say anything in this case.

The last modified date of the files are different, which means one of the files was touched after being copied.
Sonarr simply tells mono to copy the file, and mono does posix reads from one file and writes to the other with a simple buffer, very unlikely that anything would go wrong there.
If there's an issue, it's either with the filesystem or the source video.

My first guess would be a torrent file that hasn't been completely downloaded yet, but you didn't provide information about that.

> 21TB btrfs volume (3x8tb drives plus a parity drive)

I'm assuming btrfs on top of mdadm raid5, coz btrfs built-in raid5 is not reliable yet. afaik Synology uses mdadm by default.

**Comment by xartle** [comment]
Of course the last 6 copies have all gone perfectly.  I'll update again when something fails.

**Comment by xartle** [comment]
Interesting.  The torrent actually downloads on another server and then downloads to the synology when it's completed.  So a partial download shouldn't show up at all.  
I wonder if the synology is just returning nulls on the read if it gets behind or something?  That would actually explain how it was able to "lose" a section of the file and then catch up and be in sync again...  I'll try getting some iowait going and see what happens then.

**Comment by xartle** [comment]
It might be too soon to declare victory, but so far downloading to a tmp folder and then moving the completed download to the official download folder hasn't had any broken files for the last few days.  If that's really the trouble, is that the expected behavior?

**Comment by Taloth** [comment]
Yes, that is expected. Because your download client says the download is complete and ready for import, while your sync program is still in the process of transfering bits. Sonarr has no way to know that's happening.
That's why using remote mounts is usually easier because then everything is accessible the moment the download client is done. Transfer scripts always require a bit of work, because the transfer has to be atomic (appear in the target location as a whole). Please note that this applies for the _entire_ download, so in case of a multi-file torrent like season packs, every vid has to be transferred to a temp dir, and then the dir renamed/moved to the location where Sonarr expects it to be.

In the future we plan to support more methods, like Sonarr directly transferring over (s)ftp, but we're not there yet.

**Comment by xartle** [comment]
Ok, that makes sense.  Knowing that the download has to be atomic is key.  I must have missed that when I was reading the docs again to move off drone factory. 
Thanks for the help. I'll definitely +1 the SFTP transfers. :)
