### ISSUE TITLE
Can't add rss 2.0-feed - Indexer responded with html content

### ISSUE THREAD

**Issue by JoyBugs** [Sonarr/Sonarr#2771]
**Describe the bug**
Can't add rss 2.0-feed(**Add - Torrent RSS Feed**), the test:
`protected virtual bool PreProcess(IndexerResponse indexerResponse)`
in file:
_Sonarr/src/NzbDrone.Core/Indexers/RssParser.cs_
fails with:
> Indexer feed is not supported: Unable to parse indexer: Indexer responded with html content. Site is likely blocked or unavailable.

RSS-feed sends the headers:
```
Content-Type: text/html; charset=utf-8
Accept: text/html, application/xhtml+xml, application/xml;q=0.9, */*;q=0.8
```

witch in return get a fail(throw) on the:
```
if (indexerResponse.HttpResponse.Headers.ContentType != null
   && indexerResponse.HttpResponse.Headers.ContentType.Contains("text/html") 
   && indexerResponse.HttpRequest.Headers.Accept != null 
   && !indexerResponse.HttpRequest.Headers.Accept.Contains("text/html"))
```
 
Pagesource show the following result;

```
<?xml version='1.0' encoding='UTF-8' ?>
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<title>Search RSS for linux show</title>
		<link>http://www.somepage.org/</link>
		<description>The quality linux show torrents website</description>
		<language>en-us</language>
		<pubDate>Sun, 14 Oct 2018 23:31:28 +0200</pubDate>
		<lastBuildDate>Sun, 14 Oct 2018 23:31:28 +0200</lastBuildDate>
		<docs>http://blogs.law.harvard.edu/tech/rss</docs>
		<generator>Some RSS Generator</generator>
                <item><title>Linux-show</title><pubDate>14 Oct 2018 23:01:36 +0200</pubDate><link>https://www.somepage.org/Linux-show.html</link><category>Other - Other</category><size>5772258</size><description>Seeds: 0 , Leechers 0</description>
		<comments>https://www.somepage.org/Linux-show.html</comments>
		<enclosure url="http://www.somepage.org/torrent/8D54CCCF2E4190D3CC22E46D30E88514371B8F92.torrent?title=Linux-show" type="application/x-bittorrent" /></item>
```

with no HTML...

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Linux
 - .net Framework mono (Linux) Version: 4.2.3

**Comment by Taloth** [comment]
`Content-Type: text/html; charset=utf-8`

Is equivalent to the rss provider saying "The content is html". The rss provider should send the appropriate mime type 'application/rss+xml' as defined by the standard, or alternatively application/xml or 'text/xml'.

PS: `Accept:` is a header sent by the client, not the Rss server.
