### ISSUE TITLE
When a REPACK is downloaded, the renamed file gets the "PROPER" tag added instead of it's actual upgrade reason.

### ISSUE THREAD

**Issue by Raymoz101** [Sonarr/Sonarr#2772]
**Describe the bug**
When a REPACK is downloaded, the renamed file gets the "PROPER" tag added instead of it's actual upgrade reason.

**Screenshots**
![thisisusrepackvproper](https://user-images.githubusercontent.com/6777115/46936793-42975880-d0ab-11e8-9c69-5ac87ed92c4d.png)

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Synology/Docker
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 5.16.0.179

**Additional context**
Just flagging that since REPACK and PROPER have different contexts, it may be misleading for the renamed file to receive a different tag when it is imported and the original file upgraded.
If this is wrong, I do apologise.

**Comment by markus101** [comment]
Internally a repack and a proper are the same thing, a replacement for the original release because there was a problem for it. While there is a difference it's not something we plan to differentiate at this time.
