### ISSUE TITLE
Adding a TV show that is a reboot sometimes downloads the original show

### ISSUE THREAD

**Issue by apastuszak** [Sonarr/Sonarr#2775]
**Describe the bug**
I added the show Magnum P.I. a few days ago.  I went to download Episode 4, and it grabbed Episode 4 of the ORIGINAL Magnum PI from the 1980s.

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: [2.0.0.5228]
 - Operating System: [Docker on Ubuntu Linux]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**
If I do a manual search, I see shows listed as Magnum PI and Magnum PI 2018.  It seems the 2018 episodes and the ones I need.

**Comment by apastuszak** [comment]
Yes, all the graphics for the show are 2018 graphics.  Sonarr created the
folder Magnum PI, which made Plex think it was the original show.  I
manually changed the folder name to Magnum PI (2018) and updated Sonarr so
that Plex picked up the correct show.

**Comment by markus101** [comment]
The original show is `Magnum, P.I.` and the 2018 series is `Magnum P.I.` (they differ by the comma), that is apparently enough for The TVDB to differentiate and aliases should already be covered. If an additional alias needs to be added, please add it via the form and we'll get it added. Open a thread on the forums if there is anything else.
