### ISSUE TITLE
Rarbg api fails on rageid request

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#2777]
**Describe the bug**
Any request on rabg torrentapi that includes rageid appears to fail in an error thus triggering indexer backoff.
I didn't repro it myself yet, but once that's done we can report it to torrentapi to get it fixed; or alternatively disable rageid lookups altogether since it's not that useful anymore.

https://www.reddit.com/r/sonarr/comments/9oyl2e/indexer_unavailable_until_its_tested/

**Comment by markus101** [comment]
Looks like we don't actually use Rage ID when searching, but do use TVDB ID that said I don't see any issues and haven't seen other reports, so I'm closing this.
