### ISSUE TITLE
Error getting seeders/leechers and dimension on kat.li indexer

### ISSUE THREAD

**Issue by Jorman** [Sonarr/Sonarr#2778]
Hi, I casually found this problem during a manual search.
For example, if I search narcos s01 wgz see the various results:

From Jackett:
![jackett](https://user-images.githubusercontent.com/5203988/47233976-96b87a80-d3d4-11e8-8938-700146a39a6a.PNG)

Directly inside kat.li:
![katli](https://user-images.githubusercontent.com/5203988/47233997-a33cd300-d3d4-11e8-9b49-79492aa9d215.PNG)

And this is from sonarr:
![sonarr](https://user-images.githubusercontent.com/5203988/47234010-aafc7780-d3d4-11e8-9868-11547bb0885b.PNG)

Let me know if you need some more logs to better understand why this happen.

Have a nice day.

Jo

**Comment by Jorman** [comment]
Ok, so:
Sonarr Version 2.0.0.5252
Mono Version 5.14.0.177

I did a manual search about the 1st episode of narcors and
This's the log from Jackett
https://pastebin.com/ib2YLhW7
This's the log from Sonarr
https://pastebin.com/FNsVcVvC
And this's the command line curl of the request send to sonarr
https://pastebin.com/qtyR2de1

Hope can help, let me know if need more info.

**Comment by markus101** [comment]
That particular item has no seeder/peer information:

```
<torznab:attr name="seeders" value="0" />
<torznab:attr name="peers" value="0" />
```

Looks like that's not being processed properly on Jackett's side when returning the response to Sonarr.

**Comment by Jorman** [comment]
So is on Jackett side?
The 1st image I posted, all is ok.

Possible that inside Jackett all is ok but send wrong information?
I'll ask to Jackett team too

**Comment by Jorman** [comment]
Never mind, I found that sometimes kat.li don't report data, so N/A is given but inside the rel dettails the data are present
