### ISSUE TITLE
Feature request - list of replacement by language for foreign languages

### ISSUE THREAD

**Issue by Jorman** [Sonarr/Sonarr#2779]
Hi, due to some very bad releaser around the world, not only in Italy, I know also in France, Spain and who know also where... I'm asking a new little add on for sonarr

This little feature that I'm asking to sonarr team is to insert a new value during a search through Torznap.

Now sonarr search some like this
`http://192.168.2.100:9117/api/v2.0/indexers/shareisland/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Marvels%20Jessica%20Jones&season=2`
Well my idea is to add a new field in search and transform the search into this
`http://192.168.2.100:9117/api/v2.0/indexers/shareisland/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Marvels%20Jessica%20Jones&season=2&profile=italian`
So I want to add `&profile=italian` this is exactly the settings that every profile have
![37626426-4f670b30-2bd0-11e8-8d59-787c4dc1f788](https://user-images.githubusercontent.com/5203988/47234987-eba9c000-d3d7-11e8-9182-98b3cb72e113.PNG)
In that way sonarr tell to jackett that the actual searching profile is Italian or Spanish or french and so on.

Then the real dirty works in on jackett side, because here there will be a replacement table that make all search correctly over various indexer. In that way every indexer script remain with the same standard S01E01 or S01 but jackett can make more accurate searching replacing words or every is set in the replacement table.

I already spook to jackett team to this here
https://github.com/Jackett/Jackett/issues/2743
and kaso17 seems to have no problem to start a kind of normalization, but 1st sonarr have to make the request with the new tag.

What do you think about that? Is possible to have this?

Have a nice day.
Jo

**Comment by markus101** [comment]
In v3 language will not at the profile level and they would be one or more languages per "Language profile". I'm not sure how this would work with that and `profile` sounds like it should be `language` perhaps? Keep in mind anything non-standard won't be parsed by Sonarr properly.

If it's a per-indexer problem you can use `Additional Parameters` to work around this problem (if the indexer deals with that one language).

**Comment by markus101** [comment]
Sonarr can already handle `x01` or `x1` instead of `E01` when parsing names.

`Stagione completa 1` isn't something Sonarr would handle if it was `Complete Season 1`, bad/awkward release names isn't something Sonarr attempts to deal with.

This is really an "indexer" problem, it shouldn't really matter how a release is named, it should be able to return the requested results, as long as it can parse it. The problem is, most of these indexers aren't true indexers, it's just loose text searching and Jackett has to try to deal with that.

Passing a profile or language doesn't make sense for Sonarr, ideally in Jackett you would be able to add additional formats for searching so you could ask it to search different patterns automatically. Perhaps sending a list of languages makes sense, but it feels unnecessary if Jackett just does it automatically.

https://github.com/Sonarr/Sonarr/issues/2762 covers the translation of season to other languages when parsing.

**Comment by Jorman** [comment]
@markus101 
Please don't discard this little request quickly

I know that Sonarr already handle various situation, but all is about the rss sync, let me know if I wrong
If I'm wrong you're right, all is useless. But I see many people searching for this little, Dutch, Italian, French, Spanish ...

The problem is during a search, like you said is a indexer problem, but all indexer out there, have a similar problem, like you said are not very real indexer, because are more likely forum or portal where releaser post release without a real rules and any controls.
I'm not a programmer and I don't know how can be difficult put this mod into the Sonarr code, but I only know that can do the difference in a more global utilization.
In that way Sonarr always ask the standard format and Jackett do the dirty works and return always the standard format, so Sonarr have only to add an argument but don't pretend a reply to that argument

I made some search and for example
the blacklist s04e10 ita return no results on some idexer because are found only with
the blacklist 4x10 ita
And there's many more example out there

The problem is that the release use always the same name so the release are always 4x10 and on local indexer I resolved removing s04e10 and replacing with 4 10 so on all local indexer Jackett take the Sonarr request that is S04E10 and strip out all and mantain only 4 10, then at the end parse again all and return the desidered results, but this make a lot of useless results and this had to be replied to all local indexer, if not private and is not possible on non local indexer!

Like I said if Sonarr already handle that during a search this post are useless and can be removed, otherwise think also you if you want add this implementation or a kind of, maybe you've a better idea/solution, or maybe you're not interested to support international release, I don't know what is your idea
