### ISSUE TITLE
Filename with codec 'HEVC-4k' is being renamed to 720p HDTV

### ISSUE THREAD

**Issue by robertbaker** [Sonarr/Sonarr#2788]
**Describe the bug**

4k bluray remuxes incorrectly renamed:

My Title - S01E01 - EpTitle [HEVC-4k DTSHD-MA-6ch]

**Screenshots**
![image](https://user-images.githubusercontent.com/907301/47471504-62bbcb80-d7bf-11e8-8c1f-057b07360470.png)

**System Information**
Version 3.0.0.266
Mono Version 5.16.0.179

This should be 2160p and the quality

Here is my rename pattern:

{Series Title} - S{season:00}E{episode:00} - {Episode Title} [{MediaInfo VideoCodec}-{Quality Title} {MediaInfo Audio-}{MediaInfo AudioChannels}]

Also:
{MediaInfo AudioFormat} does not work, but 'Audio' does

**Comment by markus101** [comment]
`-4k` doesn't mean anything to Sonarr, looks like it fell back to the extension. The resolution from media info would now be used when importing, but wouldn't affect imports prior to that change (though it's been a few months).

Nothing Sonarr could do differently given the information here.

**Comment by markus101** [comment]
It's not mapped to 720p, it's a fallback because a quality couldn't be parsed.

I'll add 4k on it's own (it was left out since releases don't use 4k on their own typically), but it won't change the the detection of any current files.
