### ISSUE TITLE
API endpoint for Sonarr update status

### ISSUE THREAD

**Issue by mtehonica** [Sonarr/Sonarr#2790]
Would it be possible to add an API endpoint to provide information about an available Sonarr update?  I know I could probably just get the build number from the system-status endpoint and compare that to Github or whatever, but it would be much easier to just hit a Sonarr API endpoint :)

**Comment by Taloth** [comment]
You mean the existing api endpoint that the Sonarr UI uses to get the update info? 
Everything in the Sonarr UI uses the api. Just open up the browser dev console, browse to System->Updates and voila.

**Comment by mtehonica** [comment]
Thanks, I'll take a look.  I was just basing my ask off the API documentation.  It doesn't look like the update endpoint is documented at all.
