### ISSUE TITLE
Replace individual episodes with season packs

### ISSUE THREAD

**Issue by joewragg** [Sonarr/Sonarr#2791]
It is hard to explain this so bare with me. It would be nice if sonarr waited for a season pack to be available to replace it with individual episode torrents.

When it gets the season pack name the season folder to be the name of the season pack 
e.g. rename Season 3 to {SERIES}.S03.1080p.AMZN.WEB-DL.DD+2.0.H.264-{GROUP}

This way you don't have to manually delete torrents later, redownload the season pack, rename the season folder, force recheck and start seeding again.

**Comment by Taloth** [comment]
Sonarr isn't really intended as a seed manager. And the series folder is a library folder not a seed folder, files there usually get renamed.
What I think you're looking for is a script that monitors the torrent client for tracker error indicating the individual episode torrent has been removed, gets the matching torrent pack, moves the hardlinks around and voila.

Your usecase is pretty limited to trackers like BTN, so I don't see us implementing anything like this.

**Comment by joewragg** [comment]
Yeah I'm on BTN and yeah a script like that would be great.

**Comment by markus101** [comment]
I agree with @Taloth this isn’t what Sonarr is designed for and not something we have plans to do.
