### ISSUE TITLE
Upcoming list not updating automatically

### ISSUE THREAD

**Issue by Zandor300** [Sonarr/Sonarr#2792]
**Describe the bug**
The "Upcoming" list on the calendar page doesn't automatically update with downloaded status.

**Example**
The Supergirl episode hasn't been downloaded yet. It shows Red. I select it on the calendar on the same page and click auto search. It then finds the episode and downloads the file. In the calendar it shows up purple, but in the Upcoming list it still shows red. Refreshed the page and then it shows purple.

**Screenshots**
![image](https://user-images.githubusercontent.com/6069593/47648171-8002e800-db79-11e8-80e1-511c928ad914.png)

**System Information**
 - Sonarr Version: 2.0.0.5252
 - Operating System: Unraid 6.6.3
 - .net Framework (Windows) or mono (macOS/Linux) Version: No idea. Its the binhex/arch-sonarr docker container. (https://github.com/binhex/arch-sonarr)

**Comment by markus101** [comment]
Thanks for reporting, but not going to look at this ahead of releasing v3 where it isn’t going to be an issue.
