### ISSUE TITLE
FHD is recognized as "Unknown" quality

### ISSUE THREAD

**Issue by Hakujou** [Sonarr/Sonarr#2793]
Hello,

Currently on Sonarr, releases tagged "FHD" (which is Full HD, min. 1920x1080) are not recognized as 1080p quality.
This is especially common with some French anime releases on Nyaa. Would it be possible to add it to be treated in the same way than "1080p" is on release titles ?

Thanks

**Comment by markus101** [comment]
With some example file names we probably can.

**Comment by Hakujou** [comment]
Sure, here are some : 
Sword Art Online Alicization 04 vostfr FHD.mkv
Goblin Slayer 04 vostfr FHD.mkv
[Onii-ChanSub] SSSS.Gridman - 02 vostfr (FHD 1080p 10bits).mkv

Some torrent names : 
Bodacious Space Pirates - 01 [BDRIP/FHD/VOSTFR/FLAC]
[Miaou] Akanesasu Shoujo 02 VOSTFR FHD 10 bits

Please let me know if you need anything else.

**Comment by Taloth** [comment]
Potential conflicts:
- `Good.Luck.Charlie.S04E11.Teddy's.Choice.FHD.1080p.Web-DL` (WEB-DL not HDTV)
- `flashpoint.S05E06.720p.HDTV.x264-FHD`

**Comment by Hakujou** [comment]
Is there a way to put in on "low priority" (overrided by other quality if specified) ?

**Comment by markus101** [comment]
Those conflicts don't seem too bad if we make sure it's not at the very end, and the first potential conflict has 1080p regardless, we'd just want to treat `FHD` as `1080p` without an explicit source.

**Comment by Hakujou** [comment]
By "it's not at the very end", you mean of the name ?
Because for example, there's this release name : "Sword Art Online Alicization 04 vostfr FHD"
So FHD is meant for quality and is at the very end of the name.
