### ISSUE TITLE
Sonarr v3 wrong notifications

### ISSUE THREAD

**Issue by bokkoman** [Sonarr/Sonarr#2795]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Sonarr Version:**
Version 3 latest

**Operating System:**
Synology/mono/docker

I've been seeing wrong notifications messages to my Telegram since i updated from v2 to v3. 
I download web-dl but the notifications report HDTV.
The filenames do contain web-dl though.

**Comment by markus101** [comment]
1. This is the wrong place for v3 feedback, use the forums or the subreddit
2. Please include at least debug logs
