### ISSUE TITLE
Grouped Qualities in Profiles

### ISSUE THREAD

**Issue by hitnrun30** [Sonarr/Sonarr#2796]
Ok, I wanted to make it an official request.  Can you please add to profiles the ability to group qualities.  I get the same quality downloaded constantly more than once because of one type or another, i.e. webdl, hdtv, bluray... but all are 1080 or 720.  Once we get the right quality type who cares where its from.

Lidarr has learned to do it, I'm sure the original fork can.

**Comment by markus101** [comment]
Lidarr got that from the v3 work, see our v3 milestone.

**Comment by hitnrun30** [comment]
I know they did, but its a feature that should be part of regular.

**Comment by hitnrun30** [comment]
Ok, I get it, so when is v3 coming.  It looks like you just have 4 issues left, can i get that version now in beta?
