### ISSUE TITLE
No support for one-digit episode number

### ISSUE THREAD

**Issue by Hakujou** [Sonarr/Sonarr#2798]
Hello,

As of now, Sonarr doesn't seem to be able to handle files or releases when the name contains only one digit for the episode.
This is very common with anime.

Examples:
Tokyo Ghoul: RE S2 - Episode 4 VOSTFR (1080p).mkv
To Aru Majutsu no Index III - Episode 5 VOSTFR (1080p).mp4
[Prout] Steins;Gate 0 - Episode 5 VOSTFR (BDRip 1920x1080 x264 FLAC)

Would it be possible to add support for episodes with only one digit in their name ?
Thanks

**Comment by markus101** [comment]
Honestly, those are awful file names, a cross between absolute numbering and a mini series. It may be possible,but it may price too much of a pain.

**Comment by Hakujou** [comment]
I agree, but unfortunately it's the way it's done in many french anime releases :(

I did a patch for Jackett, which renames "Episode x" to "0x" so Sonarr is able to pick it and it works fine, but Sonarr can't parse the file name after that, obviously.

**Comment by Hakujou** [comment]
Just wanted to thank you a lot, you've been really helpful and patched my two issues very quickly, it's awesome !
