### ISSUE TITLE
Problem with category (YggTorrent)

### ISSUE THREAD

**Issue by samimaarouf** [Sonarr/Sonarr#2800]
Hello,

I'm using Jackett with Sonarr, and I found an issue when I'm searching an anime on yggtorrent.

This is my configuration with Sonarr : 
![image](https://user-images.githubusercontent.com/24414408/47966646-18efa280-e055-11e8-85e9-0fd69ef6f7ee.png)

And my configuration with Jackett : 
![image](https://user-images.githubusercontent.com/24414408/47966582-5acc1900-e054-11e8-9ee0-a9094dc8a660.png)

Then, when i search an anime on Sonarr, it's ONLY found if I put my anime on the "Standard" categorie.

For example : 
![image](https://user-images.githubusercontent.com/24414408/47966607-b1d1ee00-e054-11e8-88e0-f45f9a7ce3fb.png)

You can see, now it finds it when my anime is on the categorie "Standard" : 
![image](https://user-images.githubusercontent.com/24414408/47966624-e2198c80-e054-11e8-8d93-fc568d0b9527.png)

But, if I do it when I put my anime on the "anime" categorie, it won't work : 
![image](https://user-images.githubusercontent.com/24414408/47966707-d67a9580-e055-11e8-8af8-9f1381b69a0a.png)

![image](https://user-images.githubusercontent.com/24414408/47966686-8ef40980-e055-11e8-8557-81e6703336ec.png)
 
Btw, for Nyaa it's the same. But it doesn't match for the category "Standard" and works with the category "Anime".

**Comment by Hakujou** [comment]
I also have the same issue, animes are not matched on Ygg Torrent. Series works fine.

Jackett does find animes in the correct categories when using its search so I guess Sonarr uses some parameters on animes which breaks YggTorrent

**Comment by markus101** [comment]
It's due to the naming, they don't follow absolute numbering.

**Comment by Hakujou** [comment]
Isn't that supposed to work anyway ? It also breaks with one-season only animes, in which case absolute numbering is the same.

It does work fine on Nyaa (with same names) and works fine if we set Anime and YggTorrent in "Series" categories.

**Comment by markus101** [comment]
Only if the indexer maps the search for an absolute episode number to the standard numbering, which it sounds like Nyaa does.

**Comment by Hakujou** [comment]
I see, but in that case shouldn't it be working with animes that only have one season ? (Or even in season 1 of animes)

**Comment by markus101** [comment]
No. Only if they took absolute episode number 1 and automatically treated it as S01E01, but they're not actually getting a search title + absolute episode number, they're getting `Series Title 1` as the search term. Jackett may be able to auto translate it for you (since it's getting title + episode number), but it'd only work in limited cases.

**Comment by Hakujou** [comment]
What is the search performed by Sonarr ? 
It works in pretty much every case with Nyaa on Jackett (multiple season animes, one-season animes, absolute numbers or not...), but doesn't match anything on YggTorrent.

For example, releases tagged "S03E01" works on Nyaa but doesn't on YggTorrent.

**Comment by markus101** [comment]
You can see that in the debug logs.

**Comment by Crusnak** [comment]
Hi
We (the retards frenchies) use relative numbering most of the time for anime, is there a way to tell Sonarr to find relative and absolute when you are using Anime type ?
