### ISSUE TITLE
import and rename downloaded subtitle

### ISSUE THREAD

**Issue by j0n0russo** [Sonarr/Sonarr#2801]
Instead of downloading subtitles, I would be very happy with an option to move and rename downloaded subtitle together with the series file. Option to add language code to imported subtitle

_Originally posted by @SonarrBot in https://github.com/Sonarr/Sonarr/issues/300#issuecomment-100570342_

**Comment by markus101** [comment]
This already exists, if the language is in the subtitle file name it will be included when imported.

**Comment by j0n0russo** [comment]
Sorry, I did not know how to express myself. I would like to rename the subtitle by adding the language code. this language code could be configured in the import configuration. I always transfer video files with the subtitle but the subtitle does not come with the language code, so that would import the subtitle and add the language code.

**Comment by markus101** [comment]
No plans to set a default language for unknown language subtitles. A post-processing script in your download client could take care of this before Sonarr processes it, or something like https://github.com/Sonarr/Sonarr/issues/791
