### ISSUE TITLE
Skyhook sourcecode

### ISSUE THREAD

**Issue by NickyHeuperman** [Sonarr/Sonarr#2803]
I'd like to have my own skyhook service running locally as the service seems to be down sometimes,
I found https://github.com/CmdrShepard/Skyhook but this hasn't been updated for two years.
I was wondering if the source is publicly available?

Thanks in advance!
Nick

**Comment by markus101** [comment]
We've never released the Skyhook source code and never had plans to. That's not our code.

We haven't seen any Skyhook downtown recently. TheTVDB has been having site issues which may affect Skyhook's searching abilities if their API is having issues.
