### ISSUE TITLE
Toggle to Lock Core Series Meta Data

### ISSUE THREAD

**Issue by ozoak** [Sonarr/Sonarr#2805]
To limit the impact of poisoned/vandalised third party data sources causing changes to Sonarr data.
refer forum thread: https://forums.sonarr.tv/t/wrong-series-name-and-description/20232

Propose adding a system level toggle option along the lines of "Lock Core Series Meta Data After Adding" which, when toggled on, would retain the originally initially loaded Series Title and Series Description (+ Series Genre? + Series Poster?) even when new meta data is discovered when searching for new episodes at a later date.

From the above forum link, some annoyed people began vandalising entries at thetvdb.com by replacing descriptions and titles with inappropriate text.

Assuming when we first add a series we are happy with the meta data found, it seems reasonably that we wouldn't expect it to spontaneously change at some future date.

I wouldn't expect a "Lock Series Core Meta Data" to be a toggle at a series level, unless you felt like it had any real value.

**Comment by markus101** [comment]
We do not have plans for such a feature, when we're relying on TheTVDB's API v2 we'll likely be able to better handle this scenario.

**Comment by ozoak** [comment]
Top marks for response time on that one! :D 
No problem, just a suggestion. It's not exactly onerous to rescan a show when it's discovered the have gone wonky.
