### ISSUE TITLE
downloads stuck in queue

### ISSUE THREAD

**Issue by astlaurent** [Sonarr/Sonarr#2806]
Hello

I am on version 2.0.0.5270 and this problem was introduced several months ago. I am wondering if i have a broken install or if there may be some type of bug that is causing this. 

Essentially after a number of downloads it seems like some of them get stuck in the queue with no rhyme or reason. There is nothing in the sabnzb queue but sonarr still shows multiple downloads going. The other strange thing is if i remove the stuck download it disapears from the view but the counter never decrements and if i refresh the screen it comes right back. for example i have 67 items stuck right now, if i go through and delete 10 of them it will still say 67, if i refresh the page all the 10 i delete come back. It is typically only after deleting them over and over again along with restarting sonarr that is seems to clear out the queue. 

The other symptom that i noticed is that once the queue is stuck like this and i snatch an episode that new episode never enters into the queue but yet it does end up in sabnzb. The download will complete and Sonarr will not import the download. 

![image](https://user-images.githubusercontent.com/11797070/48141148-3fd9ee80-e278-11e8-8827-182641c94a15.png)

![image](https://user-images.githubusercontent.com/11797070/48141178-51bb9180-e278-11e8-88fc-030f8b449ed9.png)

**Comment by Taloth** [comment]
You checked System->Logs?

**Comment by astlaurent** [comment]
yea, the logs do not show anything significant. I am not sure if i need to enable something for better logging.

**Comment by markus101** [comment]
Please open a thread on the forums for support, trace logs will be the most useful in this case as well as OS and mono information.

**Comment by korvinous** [comment]
I am having a similar issues with downloads getting "stuck" and not being handled properly.  I see that this case was closed, what was the resolution?
