### ISSUE TITLE
Sonarr ignoring idle time remove of Transmission

### ISSUE THREAD

**Issue by neckaros** [Sonarr/Sonarr#2807]
**Describe the bug**
In transmission you can set two OR condition to stop a torrent: seeding over limit **or** idle time over max defined.

Before remonving torrents from transmission Sonarr check that seeding is over limit. But only seeding; making idle time limit in transmission useless.

parameter in transmission is:
"idle-seeding-limit": 15,
"idle-seeding-limit-enabled": true,

This avoid torrents with no demand to remain indefinately in download queue.

**Logs**
Problem seems to be here: https://github.com/Sonarr/Sonarr/blob/0d95873a05b640eaff02deaa1f4071cde4fa0b86/src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs#L101

only seedLimit is checked. I think an || should be added for Idle Time limit?

item.CanMoveFiles = item.CanBeRemoved =
                    torrent.Status == TransmissionTorrentStatus.Stopped &&
                    (item.SeedRatio >= torrent.SeedRatioLimit || item./idleTime/ >= torrent.idleTimeLimit;

Or if not possible add an option to remove as soon as stopped in client like before commit 
https://github.com/Sonarr/Sonarr/commit/2d86e44c63a3cb588663415ff110a805befee4ab   

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Unbuntu

**Additional context**
 - Transmission 2.92

**Comment by TGM** [comment]
This is a useful cleanup feature.

**Comment by iFredOS** [comment]
I hope this will be fixed soon.
