### ISSUE TITLE
Allow to specify configuration directory (at startup)

### ISSUE THREAD

**Issue by dpantel** [Sonarr/Sonarr#2808]
**Describe the problem**
Would like to be able to specify the directory where Sonarr stores its data.  A lot of us are running this as a service with a system user that doesn't have a home directory.  So it becomes confusing exactly where the .config/... is created.

**Describe any solutions you think might work**
Instead of having it configurable from the Settings, as suggested in #1132, make it configurable via command line, i.e. `... NzbDrone.exe -data=<directory>`.  This way the data dir is known and unambiguous at startup.

**Comment by Taloth** [comment]
lol....

You know, that exact parameter exists on the Sonarr commandline? https://github.com/Sonarr/Sonarr/wiki/Command-Line-Options

**Comment by dpantel** [comment]
Sorry. Looked around documentation for a while and did not find it.
