### ISSUE TITLE
TVDB Data in other Languages

### ISSUE THREAD

**Issue by jwillmer** [Sonarr/Sonarr#2809]
Since [the actual issue](https://github.com/Sonarr/Sonarr/issues/269) is locked - why?

**Additional context**
Some foreign series have episode information in multiple languages but they are in different states. For example: Tatort has the same meta data in English and German for 2016 and up but for 2015 and below the episode titles are missing for the English language [(link)](https://forums.thetvdb.com/viewtopic.php?f=7&t=52081).

**Proposal**
Use secondary language meta data when (primary) language is missing the title of the episode(s).

**Comment by markus101** [comment]
Dupe with virtually the same title... https://github.com/Sonarr/Sonarr/issues/269

**Comment by jwillmer** [comment]
have u even read the first sentence @markus101 ?

**Comment by markus101** [comment]
Apparently not.

Locked because the only comments added were “+1” comments, it was unnecessary noise that provided no value.

No plans to support multiple languages via falling back though.

**Comment by markus101** [comment]
It really doesn't. It means all the useless/mostly useless comments need to be read when it comes to implementing it.

We understand it's a wanted feature, but requires changes on Skyhook before it could be implemented.

**Comment by jwillmer** [comment]
What is `Skyhook`?

**Comment by markus101** [comment]
Essentially a proxy that cleans up TVDB data before it reaches Sonarr.
