### ISSUE TITLE
Password changes upon saving

### ISSUE THREAD

**Issue by adro21** [Sonarr/Sonarr#2810]
**Description of the bug**

Trying to set up authentication from Settings > General. I enter my password and it appears like this, as expect: https://d.pr/i/6RFVg9

Then when I hit save, the password changes to this: https://d.pr/i/7jqs1D

I'm hesitant to restart and have changes take affect, because I won't be able to log back in with the long password that appears after saving.

**System Information**

Sonarr Version: 2.0.0.5252
Operating System: MacOS

**Comment by markus101** [comment]
After saving it uses the hashed password for display, this is expected.

If you have issues you can always reset it: https://github.com/Sonarr/Sonarr/wiki/Forgot-my-Password
