### ISSUE TITLE
Sonarr not working after reboot, except if I reboot my NAS Synology

### ISSUE THREAD

**Issue by Nemrod7** [Sonarr/Sonarr#2812]
Describe the bug
When I reboot Sonarr, I can't access it, I go to DSM and launch it but still. The only workaround I found is to reboot my NAS.

To Reproduce

Go to 'Localhost:8989'
Expected behavior
Access to Sonarr

Screenshots
N/A

Desktop (please complete the following information):

OS: DSM 6.2.1-23824 Update 1
Mono Version: [5.8.0.108)
Browser and Version Safari 12.0.1
Version : Sonarr 2.0.0.5252

Debug Logs
http://pasted.co/e44ea372

**Comment by markus101** [comment]
Please use the forums for support/questions.
