### ISSUE TITLE
Synology DSM Transmission : temporary folder doesn't exist

### ISSUE THREAD

**Issue by Nemrod7** [Sonarr/Sonarr#2816]
Hi,

I'm trying to install transmission package but the installation is blocked with the following error  message : "temporary folder doesn't exist". Of course, the shared folder exist.

FYI:
<img width="700" alt="capture d ecran 2018-11-12 a 19 57 31" src="https://user-images.githubusercontent.com/9394310/48370347-5a1d2d80-e6b9-11e8-9238-4e7caef68a66.png">

I'm on DSM DSM 6.2.1-23824 Update 1

**Comment by markus101** [comment]
Again, use the forums for support/questions.
