### ISSUE TITLE
Won't launch on macOS 

### ISSUE THREAD

**Issue by Wdavery** [Sonarr/Sonarr#2818]
**Describe the bug**
The app will not launch. Turns out it was not executable.

**Logs**
LSOpenURLsWithRole() failed with error -10810

**System Information**
 - Sonarr Version: 2.0.0.5250
 - Operating System: macOS 10.14.1
 - mono Version: 5.16.0.179

**Additional context**
The only solution to the problem was to run `chmod +x /Applications/Sonarr.app/Contents/MacOS/Sonarr`

**Comment by markus101** [comment]
I'm not able to reproduce this on macOS 10.13 or 10.14 using the built-in zip utility. If you're using another extractor you may have issues (as galli-leo mentioned on the linked Radarr issue), but that's not an issue with the package.

**Comment by xvilo** [comment]
I'm also experiencing this issue from a fresh install (Mojave latest). It also seems that the chmod solution isn't working in my case. At first, I thought it could have been some kind of issue within Brew. So I manually downloaded the zip archive and used the CLI-`unzip` that is bundled with MacOS. Without doing anything else with it, I tried to run this version but I got the same results.

**Comment by formerandroider** [comment]
I've been having this exact issue since I started using Sonarr. The 'Sonarr' script isn't executable and as such the app bundle can't be opened.
