### ISSUE TITLE
Importing TV shows/episodes from Plex Media Server

### ISSUE THREAD

**Issue by mwhallberg** [Sonarr/Sonarr#2819]
**Describe the problem**
This feature would all you to import TV shows based on the content Plex has access to.

**Describe any solutions you think might work**
Then add series to Sonarr, there could be a button to add shows from a Plex Media Server.

**Comment by markus101** [comment]
No plans for such a feature, you can simply go to Add Series: Import Existing and Sonarr will look for any series folders it's not already aware of.
