### ISSUE TITLE
Cleanup of meta data

### ISSUE THREAD

**Issue by jwillmer** [Sonarr/Sonarr#2820]
**Describe the problem**
Files that are handled by Sonarr keep there meta data like the `Title` attribute. I noticed that Plex ignores the file title if it finds the `Title` attribute. If it finds the attribute it will display the attribute title as episode title and this is often far away from the real title.

**Describe any solutions you think might work**
- An option to clear all additional file attributes 
- Replace file title attribute with the real one

**Comment by Taloth** [comment]
Sonarr does not modify video files in any way, and we do consider that beyond the purview of Sonarr.
The attributes you describe are specific to the video container format.

You can setup post processing scripts in your (usenet) download client, people often use that for transcoding purposes. Alternatively you can set up a Custom Script in Sonarr which is called after import.
