### ISSUE TITLE
Sonarr grabbing files well outside of its size range

### ISSUE THREAD

**Issue by Serneum** [Sonarr/Sonarr#2822]
**Describe the bug**
Sonarr grabbed a video file that was just under 250mb when the quality is set for a minimum of 2.9gb for a 30 minute episode

**Screenshots**
The quality settings:
<img width="700" alt="screen shot 2018-11-18 at 10 48 57 pm" src="https://user-images.githubusercontent.com/1091716/48685472-7ff87580-eb84-11e8-9871-0dc9d43fbd8f.png">

History, listing file and quality that was grabbed:
<img width="990" alt="screen shot 2018-11-18 at 10 49 14 pm" src="https://user-images.githubusercontent.com/1091716/48685471-7ff87580-eb84-11e8-9f35-efe6f94cf710.png">

File size when viewing through a manual search:
<img width="971" alt="screen shot 2018-11-18 at 10 49 50 pm" src="https://user-images.githubusercontent.com/1091716/48685470-7ff87580-eb84-11e8-82b8-761eb9ab2982.png">

I originally noticed the filesize in my downloader, but deleted it before thinking to take a screenshot

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Ubuntu 18.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: 4.6.2

**Comment by markus101** [comment]
That’s within the size limits, the maximum size is set to 2.9GB, the minimum is zero based on your settings.

**Comment by Serneum** [comment]
Oh, I must have misunderstood the UI. I was looking at the values on the right. Sorry about that
