### ISSUE TITLE
NullreferenceException when trying to restore backup on fresh install

### ISSUE THREAD

**Issue by rthill91** [Sonarr/Sonarr#2823]
### System Information/Logs

**Sonarr Version:**  2.0.0.5252

**Operating System:** Rasbian Stretch 9.6

**.net Framework (Windows) or mono (macOS/Linux) Version:**  3.10.0

**Link to Log Files (debug or trace):** [sonarr.txt](https://drive.google.com/open?id=1E0dH0Ow277UmOSMmByFUHcUSV50LtyEs)

**Browser (for UI bugs):** N/A

### What problem are you looking to solve?

I have a fresh install of sonarr on a raspberry pi and am trying to restore a backup. Right after trying to start the web server I get a NullReferenceException

**Comment by markus101** [comment]
Based on the logs this is a fresh install, as a full database migration took place. Also make sure you're running Sonarr with `--debug` flag for mono, the logs currently don't help much.

I think the issue is the mono version, you'll want something in 4.x or higher as there are issues on some systems before then, probably 4.6+.

**Comment by rthill91** [comment]
@markus101 As soon as I get a chance I'll rerun with --debug, and then I'll try a mono update.

@Taloth I'm using a zip backup.

FWIW I was following (this guide)[https://www.htpcguides.com/install-sonarr-raspberry-pi-mono-310/] for the installation which is linked in the Raspberry Pi section. That's the reason I'm on mono 3.10

**Comment by rthill91** [comment]
Sorry,
* I've run Sonarr, it successfully spins up the web server, everything looks good.
* Stop Sonarr
* Removed config.xml & nzbdrone.db*
* Copied files from backup zip into NzbDrone config directory (config.xml, nzbdrone.db, nzbdrone.db-journal)
* Rerun Sonarr
* [Resulting Logs](https://drive.google.com/open?id=1zfNSqF8gqTHPQj-94Z8a6vs3uVwckbez)

NOTE: these steps and resulting logs were run using mono v4.6.2

**Comment by rthill91** [comment]
I was able to get an older backup loaded, so I think you were right, just a corrupted backup. Thanks for the help!

**Comment by Taloth** [comment]
Awesome, tnx for letting us know.

Can you check the original backup you tried, does it contain a zero length nzbdrone.db-journal file?

**Comment by rthill91** [comment]
@Taloth Yes the original nzbdron.db-journal file is 0 length

**Comment by Taloth** [comment]
Tnx. Kinda odd coz that backup shouldn't be corrupted that easily, I'll have to keep it in mind if more reports come in.

**Comment by rthill91** [comment]
Np, if you've got anything else you'd like me to try or other logs I can generate from them just let me know. I can spin up a separate instance easy enough to test

**Comment by Taloth** [comment]
Nah, at this stage there's no way of telling when the backup became corrupt. I'm just a bit concerned coz if somehow the backup function sqlite has builtin isn't actually reliable then we have somewhat of a problem.
