### ISSUE TITLE
{Air-Date} Not Working in GUI

### ISSUE THREAD

**Issue by Ashkaan** [Sonarr/Sonarr#2825]
**Describe the bug**
The GUI doesn't allow you to use {Air-Date} in the Daily Episode Format.  It reads "Invalid Format".

**Screenshots**
![image](https://user-images.githubusercontent.com/5667978/48793576-46bb2500-ecac-11e8-86b3-3640e7012e0b.png)

**Logs**
Doubt this is necessary.

**System Information**
 - Sonarr Version: 2.0.0.5252
 - Operating System: Ubuntu 16.0.4.5
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.4.1.6

**Comment by markus101** [comment]
> Doubt this is necessary.

Yes, please post the trace logs of this.

**Comment by Ashkaan** [comment]
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/2601099/sonarr.txt)

**Comment by markus101** [comment]
Those are info logs, we need trace logs please. https://github.com/Sonarr/Sonarr/wiki/Log-Files

**Comment by Ashkaan** [comment]
[sonarr.trace.0.txt](https://github.com/Sonarr/Sonarr/files/2605393/sonarr.trace.0.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/2605394/sonarr.trace.txt)

**Comment by Taloth** [comment]
Should be fixed on the next develop branch version. Thank you for the bug report.

**Comment by Ashkaan** [comment]
Why was this closed?

**Comment by Taloth** [comment]
That's why.... lightning mcqueen :smile:
