### ISSUE TITLE
Sonarr Phantom deb package doesn't support changing sonarr user/group

### ISSUE THREAD

**Issue by satmandu** [Sonarr/Sonarr#2828]
The sonarr service on a debian system has the user and group hardcored as sonarr

Changing the user and group for the service in /lib/systemd/system/sonarr.service isn't persistent as an update will overwrite the file.

One relatively simple solution here would be to use a /etc/default/sonarr file with user and group therein, and just pull those in with a EnvironmentFile=/etc/default/sonarr section in the sonarr.service file.

This way we can make local modifications to the user and group without causing problems.

(Alternately we could use a dpkg-divert option locally, but that seems kludgy in case a change is made in future with default mono options, etc.)

**Comment by markus101** [comment]
Please use the appropriate place for phantom feedback (forums/subreddit). This is something being worked on though.

**Comment by Taloth** [comment]
To add:

You can edit systemd units with `systemctl edit sonarr.service`, which is the standard way of systemd to provide overrides. Which survives updates.

However, I suggest you wait a bit, coz we're working on improving the deployment process on debian. Including using debconf to allow the user to provide the user and group as config.

**Comment by satmandu** [comment]
Also thanks @Taloth for educating me on the proper way to edit systemd units.
