### ISSUE TITLE
Task Error appears to prevent Sonarr from starting

### ISSUE THREAD

**Issue by sfunk1x** [Sonarr/Sonarr#2829]
**Describe the bug**
Sonarr appeared to stop working at some point in the past 24 hours with the following error repeated in the log:

`Nov 23 07:04:17 media Sonarr[12769]: [Error] TaskExtensions: Task Error
Nov 23 07:04:17 media Sonarr[12769]: [v2.0.0.5252] System.Data.SQLite.SQLiteException (0x80004005): unable to open database file
Nov 23 07:04:17 media Sonarr[12769]:   at System.Data.SQLite.SQLite3.Open (System.String strFilename, System.Data.SQLite.SQLiteConnectionFlags connectionFlags, System.Data.SQLite.SQLiteOpenFlagsEnum openFlags, System.Int32 maxPoolSize, System.Boolean usePool) [0x00074] in <61a20cde294d4a3eb43b9d9f6284613b>:0
Nov 23 07:04:17 media Sonarr[12769]:   at System.Data.SQLite.SQLiteConnection.Open () [0x00959] in <61a20cde294d4a3eb43b9d9f6284613b>:0
Nov 23 07:04:17 media Sonarr[12769]:   at Marr.Data.DataMapper.OpenConnection () [0x00024] in <1065f06e3ab04e5881367f857f748853>:0
Nov 23 07:04:17 media Sonarr[12769]:   at Marr.Data.DataMapper.Query[T] (System.String sql, System.Collections.Generic.ICollection`1[T] entityList, System.Boolean useAltName) [0x00065] in <1065f06e3ab04e5881367f857f748853>:0
Nov 23 07:04:17 media Sonarr[12769]:   at Marr.Data.QGen.QueryBuilder`1[T].ToList () [0x00052] in <1065f06e3ab04e5881367f857f748853>:0
Nov 23 07:04:17 media Sonarr[12769]:   at NzbDrone.Core.Datastore.BasicRepository`1[TModel].All () [0x0000b] in <85e2f5295c104ca3a3bcaa59e805585a>:0
Nov 23 07:04:17 media Sonarr[12769]:   at NzbDrone.Core.Jobs.TaskManager.GetPending () [0x00000] in <85e2f5295c104ca3a3bcaa59e805585a>:0
Nov 23 07:04:17 media Sonarr[12769]:   at NzbDrone.Core.Jobs.Scheduler.ExecuteCommands () [0x0000b] in <85e2f5295c104ca3a3bcaa59e805585a>:0
Nov 23 07:04:17 media Sonarr[12769]:   at System.Threading.Tasks.Task.InnerInvoke () <0x7f3deae6e6e0 + 0x00032> in <3833a6edf2074b959d3dab898627f0ac>:0
Nov 23 07:04:17 media Sonarr[12769]:   at System.Threading.Tasks.Task.Execute () <0x7f3deae6e520 + 0x00012> in <3833a6edf2074b959d3dab898627f0ac>:0
`

Sonarr then becomes unusable as the web interface is no longer accessible. 

**Logs**
https://gist.github.com/sfunk1x/e8fb043eb1fda3c94818429b6b27edcc

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Ubuntu 18.04 server
 - .net Framework (Windows) or mono (macOS/Linux) Version: mono 5.16.0.179

**Comment by markus101** [comment]
Either a corrupt database or it's inaccessible for another reason. If it's corrupt you'll need to restore from a backup (which Sonarr makes automatically).
