### ISSUE TITLE
Manually add show (which isn't on tvdb)

### ISSUE THREAD

**Issue by Zachary24** [Sonarr/Sonarr#2831]
**Describe the problem**
I've had several either old shows or less popular shows that aren't on tvdb, and its a pain to simply leave those in some random txt file, as many people use sonarr to also keep track of shows they need to find elsewhere.. 

**Describe any solutions you think might work**
Simply adding a button the add series section

**Additional context**
I've seen on the forum someone from sonarr said there were no intentions of adding other metadata sites, and I get that, but I think the user should be able to simply "make an entry", even if all the user can do is add a title.

**Comment by markus101** [comment]
There is already https://github.com/Sonarr/Sonarr/issues/699

But the key word is _yet_, the idea would be to add a show to a list and wait for it to be added later, if the show just hasn't been added to The TVDB then it should be added. WE have no plans for supporting manually added shows/episodes.
