### ISSUE TITLE
Settings won't save in Safari

### ISSUE THREAD

**Issue by Wdavery** [Sonarr/Sonarr#2832]
**Describe the bug**
None of the settings will save, except for those that are within a 'pop-out window'. The save button is unresponsive. 

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: macOS 10.14.1
 - .mono Version: 5.16.0.179

**UI Bugs:**
 - OS: macOS 10.14.1
 - Browser: Safari
 - Version: 12.0.1

**Additional context**
This is Safari specific, tested in Firefox and it worked properly.

**Comment by markus101** [comment]
Have you tried in private browsing in Safari (or whatever they call it)?
Any errors in the developer tools?

**Comment by Wdavery** [comment]
Private browsing fixed it. It was a cache/cookie issue.
