### ISSUE TITLE
V3 - Clicking through from Wanted then using Back resets the page you're on

### ISSUE THREAD

**Issue by bluenote73** [Sonarr/Sonarr#2834]
V3 is so frickin awesome, especially with the addition of preferred words that this is literally the only thing I can even complain about.
With say 5 pages of results in Wanted, clicking through to any series and then using the Back browser button always sends me back to page 1 of wanted, when preferably, I'd still be on page 3 or whatever I was on.

**Comment by markus101** [comment]
Please use the forums/subreddit for feedback on v3.

We might be able to do something here, but offhand I'm not sure.
