### ISSUE TITLE
SSHFS: no automatic import possible anymore

### ISSUE THREAD

**Issue by marlemion** [Sonarr/Sonarr#2836]
I have the follwing setup: transmission is running on machine A. Sonarr is running on machine B. The data directory of transmission on machine A is mounted via sshfs to a directory on machine B. Sonarr is set up to use transmission on machine A to download files and watches this folder and processes these files after a download was successful. This worked quite nicely until maybe a few weeks ago (unfortunatelty, I cannot be more precise).

The current behavior is that sonarr indicates that there is a new series downloaded (number in orange rectangle over activities). But when I click on it and hover over the entry, it says that allegedly no file is eglible for processing. When I click on manual import in the same UI context, it says that no video file was found in the selected folder.

However, when I click on wanted -> manual import -> select the sshfs mounted folder -> manual import, I can select and process the files without any problem.

Hence, there seems to be something wrong with picking up the files by sonarr for automatic processing.

Sonarr Version: 2.0.0.5252
Operating System: Arch Linux x86_64
Mono Version: 5.16.0

**Comment by markus101** [comment]
This behaviour hasn’t changed in Sonarr recently, please open a thread on the forums for support.

It sounds like either Sonarr doesn’t know where to look for the files or it doesn’t have permission to access them, given Manual Import works it’s likely the former; possibly a missing or incorrect Remote Path Mapping.

**Comment by marlemion** [comment]
Then why was it working in the first place?

Definitively no permission issue: sonarr runs as the same user as I am on that machine and I am able to access the folder. Even further: why should there be a permission problem if sonarr can process the files via manual import?

I have played with the settings 'directory' and 'category' in transmission, even set the directory explicitly. No change.

And I do not use remote path mapping. I use **SSHFS**.
