### ISSUE TITLE
NF.WEB is detected as HDTV

### ISSUE THREAD

**Issue by cremor** [Sonarr/Sonarr#2839]
**Describe the bug**
Beginning with episode S04E03 the NF.WEB.DDP5.1.x264-NTb[rartv] releases of Outlander are wrongly detected as HDTV in the manual search result list. Episodes 1 and 2 are correctly detected as WEBDL.

Bad (HDTV): Outlander.S04E03.The.False.Bride.720p.NF.WEB.DDP5.1.x264-NTb[rartv]
Good (WEBDL): Outlander.S04E01.America.The.Beautiful.720p.NF.WEB.DD5.1.x264-NTb[rartv]

The difference seems to be "DD5.1" vs "DDP5.1". But that shouldn't affect video source tagging, right?

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Linux (in Docker container linuxserver/sonarr)
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.16.0.179

**Comment by markus101** [comment]
Already fixed in https://github.com/Sonarr/Sonarr/commit/537e4d7c39e839e75e7a7ad84e95cd582ec1d20e
