### ISSUE TITLE
Invalid scene mapping found for: 344705, skipping

### ISSUE THREAD

**Issue by humansloth** [Sonarr/Sonarr#2840]
I keep getting this error in my logs:
`Invalid scene mapping found for: 344705, skipping`
I did a search for "344705" on thexem and it says "The requested show is invalid". Looks like an issue with Archer. It appears to not be listed on thexem. They are currently closed for registration thus I am unable to try to add the show myself. Could you please fix for Archer (2009-) if possible?

Says it happens at 12:36 in the log:
`18-12-4 12:35:24.9|Debug|Api|[PUT] /api/config/host: 202.Accepted (46 ms)
18-12-4 12:35:25.0|Debug|Api|[GET] /api/health: 200.OK (1 ms)
18-12-4 12:35:25.3|Debug|Api|[GET] /api/health: 200.OK (1 ms)
18-12-4 12:35:28.3|Debug|Api|[GET] /api/health: 200.OK (0 ms)
18-12-4 12:35:28.3|Debug|Api|[GET] /api/health: 200.OK (0 ms)
18-12-4 12:35:28.4|Debug|Api|[GET] /api/diskspace: 200.OK (96 ms)
18-12-4 12:35:28.5|Debug|Api|[GET] /api/diskspace: 200.OK (90 ms)
18-12-4 12:35:31.0|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (5 ms)
18-12-4 12:35:31.0|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (3 ms)
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Whose.Line.is.it.Anyway.US.S14E15.1080p.WEB.h264-TBS[rarbg]'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. Whose Line is it Anyway US - S14E15 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for Whose.Line.is.it.Anyway.US.S14E15.1080p.WEB.h264-TBS[rarbg]
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: TBS
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Whose.Line.is.it.Anyway.US.S13E08.1080p.WEB.x264-TBS[rarbg]'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. Whose Line is it Anyway US - S13E08 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for Whose.Line.is.it.Anyway.US.S13E08.1080p.WEB.x264-TBS[rarbg]
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: TBS
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'South.Park.S04.1080p.BluRay.x264-SHORTBREHD[rartv]'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. South Park - Season 04 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for South.Park.S04.1080p.BluRay.x264-SHORTBREHD[rartv]
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: Bluray-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: SHORTBREHD
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Archer.2009.S07E06.Bel.Panto.Part.II.1080p.WEB-DL.DD5.1.H264-BS[rarbg]'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. Archer 2009 - S07E06 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for Archer.2009.S07E06.Bel.Panto.Part.II.1080p.WEB-DL.DD5.1.H264-BS[rarbg]
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: BS
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Whose.Line.is.it.Anyway.US.S14E16.1080p.WEB.h264-TBS[rarbg]'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. Whose Line is it Anyway US - S14E16 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for Whose.Line.is.it.Anyway.US.S14E16.1080p.WEB.h264-TBS[rarbg]
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: TBS
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Whose.Line.is.it.Anyway.US.S14E13.1080p.WEB.h264-TBS[rarbg]'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. Whose Line is it Anyway US - S14E13 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for Whose.Line.is.it.Anyway.US.S14E13.1080p.WEB.h264-TBS[rarbg]
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: TBS
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Archer.2009.S07E10.Deadly.Velvet.Part.Two.1080p.WEB-DL.DD5.1.H264-BS[rarbg]'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. Archer 2009 - S07E10 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for Archer.2009.S07E10.Deadly.Velvet.Part.Two.1080p.WEB-DL.DD5.1.H264-BS[rarbg]
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: BS
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Archer.2009.S09.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv]'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. Archer 2009 - Season 09 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for Archer.2009.S09.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv]
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: NTb
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Whose.Line.is.it.Anyway.US.S14E14.1080p.WEB.h264-TBS[rarbg]'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. Whose Line is it Anyway US - S14E14 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for Whose.Line.is.it.Anyway.US.S14E14.1080p.WEB.h264-TBS[rarbg]
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: TBS
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Archer.2009.S07E04.Motherless.Child.1080p.WEB-DL.DD5.1.H264-BS[rarbg]'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. Archer 2009 - S07E04 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for Archer.2009.S07E04.Motherless.Child.1080p.WEB-DL.DD5.1.H264-BS[rarbg]
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: BS
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Game of Thrones S06 1080p BluRay x264-Belex - Dual Audio + Legendas'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. Game of Thrones - Season 06 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for Game of Thrones S06 1080p BluRay x264-Belex - Dual Audio + Legendas
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: Bluray-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: Belex
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Archer.2009.S07E03.Deadly.Prep.1080p.WEB-DL.DD5.1.H264-BS[rarbg]'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. Archer 2009 - S07E03 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for Archer.2009.S07E03.Deadly.Prep.1080p.WEB-DL.DD5.1.H264-BS[rarbg]
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: BS
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Archer 2009 Season 1-6 S01-S06 1080p BluRay x264-MIXED [RiCK]'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. Archer 2009 - Season 01 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for Archer 2009 Season 1-6 S01-S06 1080p BluRay x264-MIXED [RiCK]
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: Bluray-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: MIXED
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Game.of.Thrones.S02.1080p.BluRay.x264-belex.DualAudio.eng+ptbr+multi.subs'
18-12-4 12:35:54.1|Debug|Parser|Episode Parsed. Game of Thrones - Season 02 
18-12-4 12:35:54.1|Debug|Parser|Language parsed: English
18-12-4 12:35:54.1|Debug|QualityParser|Trying to parse quality for Game.of.Thrones.S02.1080p.BluRay.x264-belex.DualAudio.eng+ptbr+multi.subs
18-12-4 12:35:54.1|Debug|Parser|Quality parsed: Bluray-1080p v1
18-12-4 12:35:54.1|Debug|Parser|Release Group parsed: belex
18-12-4 12:35:54.1|Debug|Parser|Parsing string 'Beavis & Butthead'
18-12-4 12:35:54.1|Debug|Parser|Unable to parse Beavis & Butthead
18-12-4 12:35:54.2|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (2 ms)
18-12-4 12:36:01.2|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (2 ms)
18-12-4 12:36:04.2|Debug|Api|[POST] /api/command: 201.Created (7 ms)
18-12-4 12:36:04.2|Info|Database|Vacuuming Log database
18-12-4 12:36:04.2|Info|Database|Log database compressed
18-12-4 12:36:04.3|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (3 ms)
18-12-4 12:36:04.4|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (1 ms)
18-12-4 12:36:04.4|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (1 ms)
18-12-4 12:36:04.4|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (1 ms)
18-12-4 12:36:04.4|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (2 ms)
18-12-4 12:36:04.4|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (1 ms)
18-12-4 12:36:04.4|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (1 ms)
18-12-4 12:36:04.4|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (1 ms)
18-12-4 12:36:04.4|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (1 ms)
18-12-4 12:36:04.4|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (3 ms)
18-12-4 12:36:04.4|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (1 ms)
18-12-4 12:36:08.4|Debug|Api|[GET] /api/series?sort_by=sortTitle&order=asc: 200.OK (24 ms)
18-12-4 12:36:12.8|Debug|Api|[POST] /api/command: 201.Created (5 ms)
18-12-4 12:36:12.8|Debug|XemProxy|Fetching Series IDs from
18-12-4 12:36:13.0|Info|SceneMappingService|Updating Scene mappings
18-12-4 12:36:13.0|Debug|XemProxy|Fetching alternate names
18-12-4 12:36:13.8|Warn|SceneMappingService|Invalid scene mapping found for: 344705, skipping
18-12-4 12:36:14.0|Info|RefreshSeriesService|Updating Info for Archer (2009)
18-12-4 12:36:14.3|Info|RefreshEpisodeService|Starting episode info refresh for: [110381][Archer (2009)]
18-12-4 12:36:14.4|Debug|EpisodeAddedService|No new episodes, skipping search
18-12-4 12:36:14.4|Info|RefreshEpisodeService|Finished episode refresh for series: [110381][Archer (2009)].
18-12-4 12:36:14.4|Debug|RefreshSeriesService|Finished series refresh for Archer (2009)
18-12-4 12:36:14.4|Info|DiskScanService|Scanning disk for Archer (2009)
18-12-4 12:36:14.4|Debug|DiskScanService|Scanning '/tv/Archer (2009)' for video files
18-12-4 12:36:14.4|Debug|DiskScanService|2 video files were found in /tv/Archer (2009)
18-12-4 12:36:14.4|Debug|DiskScanService|[110381][Archer (2009)] Cleaning up media files in DB
18-12-4 12:36:14.4|Debug|ImportDecisionMaker|Analyzing 0/2 files.
18-12-4 12:36:14.4|Info|DiskScanService|Completed scanning disk for Archer (2009)
18-12-4 12:36:14.4|Debug|ExistingExtraFileService|Looking for existing extra files in /tv/Archer (2009)
18-12-4 12:36:14.4|Debug|DiskScanService|Scanning '/tv/Archer (2009)' for non-video files
18-12-4 12:36:14.4|Debug|DiskScanService|0 non-video files were found in /tv/Archer (2009)
18-12-4 12:36:14.4|Debug|ExistingMetadataImporter|Looking for existing metadata in /tv/Archer (2009)
18-12-4 12:36:14.4|Info|ExistingMetadataImporter|Found 0 existing metadata files
18-12-4 12:36:14.4|Debug|ExistingSubtitleImporter|Looking for existing subtitle files in /tv/Archer (2009)
18-12-4 12:36:14.4|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
18-12-4 12:36:14.4|Debug|ExistingOtherExtraImporter|Looking for existing extra files in /tv/Archer (2009)
18-12-4 12:36:14.4|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
18-12-4 12:36:14.4|Info|ExistingExtraFileService|Found 0 extra files
18-12-4 12:36:14.4|Debug|XemService|Scene numbering is not available for Archer (2009) [110381]
18-12-4 12:36:15.0|Debug|CleanExtraFileService|Cleaning missing metadata files for series: Archer (2009)
18-12-4 12:36:19.3|Debug|Api|[GET] /api/health: 200.OK (1 ms)
18-12-4 12:36:19.3|Debug|Api|[GET] /api/health: 200.OK (1 ms)
18-12-4 12:36:19.4|Debug|Api|[GET] /api/diskspace: 200.OK (94 ms)
18-12-4 12:36:19.5|Debug|Api|[GET] /api/diskspace: 200.OK (95 ms)
18-12-4 12:36:21.2|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (3 ms)
18-12-4 12:36:21.3|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn: 200.OK (3 ms)
`

**Comment by Taloth** [comment]
I forgot to mention, but I fixed somewhere tuesday. if you keep getting the error lemme know.
