### ISSUE TITLE
Episode search is a broken mess

### ISSUE THREAD

**Issue by h2xtreme** [Sonarr/Sonarr#2841]
**Describe the bug**
Sonarr doesn't download episodes.

When doing manual search the episodes are correctly listed but Sonarr somehow says it's an unknown series.

TV show matches the TVDB title. When manually using the search pattern on the trackers the results given are accurate.

We should have an option to manually customize the search pattern for a TV Show. And also another to force the download even when the Unknown Series thing hits.

**Screenshots**
https://i.imgur.com/NZ7DFAD.png
https://i.imgur.com/wtYYHES.png

**Logs**

18-12-5 14:13:18.4|Info|NzbSearchService|Searching 4 indexers for [WWE Monday Night Raw : 2018-12-03]
18-12-5 14:13:24.0|Info|DownloadDecisionMaker|Processing 31 releases

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Ubuntu Cosmic
 - mono 5.16

**Comment by markus101** [comment]
We maintains list of aliases for series, but since TheTVBD doesn’t support sports and this show has been classified as sports it’s not something Sonarr supports either.

There is already an issue for forcing downloads of unknown series.
