### ISSUE TITLE
Rejections and episode/season number doesn't update when manually selected

### ISSUE THREAD

**Issue by MrDemocracy** [Sonarr/Sonarr#2842]
**Describe the bug**
When I manually import a series and sonarr doesn't recognize what series it is, I still says "Unknown Series" even after I have selected what series it is. The same goes for "Not an upgrade for existing episode file(s)". It doesn't update when correct and change episode numbers on the episodes.
It would also be nice if sonarr added the season and episode number after I manually selected the series. And maybe sonarr could recheck the filenames for the series names I just added to the first episode, so I don't have to go through every file and add the same series name to each one.

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: .NET Framework 4.7.2

**UI Bugs:**
 - OS: Windows
 - Browser: Chrome
 - Version: 70.0.3538.110 (Official Build) (64-bit)

**Comment by markus101** [comment]
There is an existing issue for this already, on mobile, but I believe it’s to do with reprocessing after selecting the series.
