### ISSUE TITLE
Sonarr Indexer Issue

### ISSUE THREAD

**Issue by AcidRain999** [Sonarr/Sonarr#2843]
so i updated to the new sonarr (i think v3) and when i went to go add a indexer to my list it gives an error that no results were returned. i know there are results i checked myself and when i loaded the exact same information into Radarr it works no problem.

so im guessing its an error with Sonarr and API

i checked the settings many times while trying to troubleshoot it

LOG FILE INFORMATION:

18-12-6 14:55:25.3|Debug|Api|[GET] /api/v3/log/file: 200.OK (3 ms)
18-12-6 14:55:30.3|Debug|Api|[GET] /api/v3/config/indexer: 200.OK (5 ms)
18-12-6 14:55:30.4|Debug|Api|[GET] /api/v3/indexer: 200.OK (39 ms)
18-12-6 14:55:47.8|Debug|Api|[GET] /api/v3/indexer/schema: 200.OK (42 ms)
18-12-6 14:56:10.8|Debug|Newznab|Downloading Feed https://tabula-rasa.pw/api/v1/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100
18-12-6 14:56:13.4|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings.
18-12-6 14:56:13.4|Debug|Api|[POST] /api/v3/indexer/test: 400.BadRequest (2673 ms)
18-12-6 14:56:15.1|Debug|SabnzbdProxy|Url: http://(IP ADDRESS):2004/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
18-12-6 14:56:15.1|Debug|SabnzbdProxy|Url: http://(IP ADDRESS):2004/api?mode=history&start=0&limit=30&category=tv&apikey=(removed)&output=json
18-12-6 14:56:16.1|Debug|Newznab|Downloading Feed https://tabula-rasa.pw/api/v1/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100
18-12-6 14:56:16.9|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings.
18-12-6 14:56:16.9|Debug|Api|[POST] /api/v3/indexer: 400.BadRequest (866 ms)
18-12-6 14:56:18.4|Debug|Api|[GET] /api/v3/health: 200.OK (1 ms)
18-12-6 14:56:18.4|Debug|Api|[GET] /api/v3/system/status: 200.OK (1 ms)
18-12-6 14:56:18.6|Debug|Api|[GET] /api/v3/diskspace: 200.OK (130 ms)
18-12-6 14:56:19.6|Debug|Api|[GET] /api/v3/log/file: 200.OK (4 ms)

**Comment by markus101** [comment]
Please use the forums for help and support.

Looks like your indexers returned 0 results, perhaps your categories are wrong.
