### ISSUE TITLE
Manual torrent import

### ISSUE THREAD

**Issue by radicalentity** [Sonarr/Sonarr#2845]
I love sonarr’s ability to manage the torrent downloads and auto renaming and moving. However, it does not find the right torrent all the time for batches because they need to have 1-13 or something of the sort in the title and most anime batches of older shows don’t. I mainly use sonarr to download anime. So can we fix that issue or add the ability to import a magnet link or torrent in place of the search functionality?

**Comment by markus101** [comment]
Packs are hard because Sonarr doesn’t know the range if there are multiple packs for a “season”.

You can manually add the torrent/magnet to your client and set the appropriate label/category and Sonarr will pick it up if it can parse it.
