### ISSUE TITLE
skyhook.sonarr.tv and forums.sonarr.tv are down

### ISSUE THREAD

**Issue by trenb** [Sonarr/Sonarr#2847]
Unfortunately neither URL is accessible. I receive "Error 523 - Origin is unreachable". I've tried from multiple networks. Same issue with skyhook.sonarr.tv.

I apologize for logging a ticket, but the forums are unreachable. And the skyhook issue means no new shows can be added.

**Comment by Taloth** [comment]
We know, we get pinged if it goes down. No ETA for when it's back up.

**Comment by trenb** [comment]
Cool, thanks for the update. Good luck getting things fixed!

**Comment by trenb** [comment]
As a note for other people viewing this, you can add shows directly via their tvdb ID which you can get from thetvdb.com. Then use:
```
tvdb:73739
```
in the search dialogue.
