### ISSUE TITLE
Question: Which Mono Version?

### ISSUE THREAD

**Issue by breezytm** [Sonarr/Sonarr#2849]
Hello dev, 

Can you please tell us which version of Mono I should be using? At this point I can not tell. I installed version 5.10 and that was a disaster. I decided to go back to version 5.8 since a lot of people doesn't seem to be reporting any issues pre 5.10.

**Comment by markus101** [comment]
Please use the forums for support and questions.

5.10 should be fine, but if 5.8 is working that'll work. I think the bare minimum is ~4.8, but 5+ is good for the new SSL support. 5.16 is pretty broken, so avoid that.
