### ISSUE TITLE
Manually Search All Missing - Does not delete files or remove from torrent application

### ISSUE THREAD

**Issue by mcleaver01** [Sonarr/Sonarr#2850]
I have noticed that if I add a new show, it will download perfectly, get renamed and copied, and removed from my torrent application and files deleted from my completed directory. However, if I go to "Wanted" and search from there, files will still get renamed and copied, but it leaves the torrent in the app and does not delete the files.

**Comment by markus101** [comment]
How Sonarr find episodes doesn’t change how the import happens.

The difference here would be whether or not the torrent is still seeding, which is mentioned in the FAQ.

**Comment by mcleaver01** [comment]
So that was negative help

**Comment by mcleaver01** [comment]
It shows finished... To hell your smartassed comment. I'm not a rookie

**Comment by mcleaver01** [comment]
Just nevermind. These forums prove that y'all only just push shit on people
rather than help people

**Comment by markus101** [comment]
LOL, turning it up to 11...

> So that was negative help

What you said made no sense to how Sonarr operates, but I pointed you towards the most common misunderstanding with how torrent are imported, which is in the FAQ, here's a direct link 
https://github.com/Sonarr/Sonarr/wiki/FAQ#seeding-torrents-arent-deleted-automatically if you didn't find it already.

> It shows finished... To hell your smartassed comment. I'm not a rookie

There are several helpers to point you at our forums for support/questions yet you posted here. If this was a bug report you failed to provide even the bare minimum of information requested.

> Just nevermind. These forums prove that y'all only just push shit on people rather than help people

These "forums" aren't for support, that's what https://forums.sonarr.tv/ is for, the templates tell you to go there for this.
