### ISSUE TITLE
Log view is messed up.

### ISSUE THREAD

**Issue by samip5** [Sonarr/Sonarr#2851]
**Describe the bug**
Log view is messed up.

**Screenshots**
![image](https://user-images.githubusercontent.com/1703002/50150846-e5489f00-02c7-11e9-9242-0c168561f371.png)

**System Information**

 - Sonarr Version: [2.0.0.5252]
 - Operating System: [Windows 10]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [Mono 5.16.0.220]

**UI Bugs:**
 - OS: [Windows]
 - Browser: [Vivaldi, based on Chrome]
 - Version: [2.2.1388.34]

**Comment by markus101** [comment]
A really long message can push it out currently. No plans to make any changes to that view in the v2 app, but shouldn't be an issue in v3.
