### ISSUE TITLE
Folder is not writable by user abc

### ISSUE THREAD

**Issue by michaeltieso** [Sonarr/Sonarr#2853]
This issue has been written about a million times but there's a noticeable difference from this one between the others.

Notes:

- I am using [this Docker container](https://hub.docker.com/r/linuxserver/sonarr/).
- I have correctly setup PUID and PGID.
- The same exact settings have been configured for Radarr (also Docker). Same PUID and PGID too.

Despite all this, Sonarr reports that there's a write error for the user. I can confirm it's writing because Google Drive (using Rclone) has the write test file.

![screenshot_2018-12-19_09 00 27](https://user-images.githubusercontent.com/1500606/50206718-943eb680-036c-11e9-899c-73008889a2a3.png)

![screenshot_2018-12-19_09 04 42](https://user-images.githubusercontent.com/1500606/50206893-28108280-036d-11e9-80fb-653751581f8b.png)

**Comment by markus101** [comment]
Please open a thread on the forums for support.

**Comment by michaeltieso** [comment]
@markus101 Posted here because it's seen as a bug, not a support request. Also not ideal to have to sign up for yet another website to report a bug.

**Comment by michaeltieso** [comment]
[Posted here for reference](https://forums.sonarr.tv/t/folder-is-not-writable-by-user-abc/20655)

**Comment by markus101** [comment]
None of the requested information was provided and if you look at the logs you'll probably see Sonarr is failing to delete the file. Also the forum post has none of the information requested there.

I've used that docker container for years and it works fine, zero permission issues.

**Comment by michaeltieso** [comment]
None :roll_eyes: 
Okay, buddy.
