### ISSUE TITLE
Default/multi Language selection per indexer

### ISSUE THREAD

**Issue by razlebol** [Sonarr/Sonarr#2854]
**Describe the problem**
Release with multi are considered english releases

**Describe any solutions you think might work**
Choose what language a Multi release should be treated as like Radarr already do.

**Additional context**
see screenshot of Radarr

<img width="462" alt="radarr 2" src="https://user-images.githubusercontent.com/908936/50297291-78114700-044a-11e9-95d7-77c4cc4873f4.png">

This will need to also take these changes into account:
https://github.com/Radarr/Radarr/commit/efd4abfa3eaab0b476ff8d69a7ef4fc98ae1fd7d#diff-7d16ccb552b1c11242c9acf7197edeac45b9be87854c1f6ad3250aaf811f735fL78-L79

**Comment by razlebol** [comment]
I've seen ir used for Spanish and other languages. A setting per indexer fixes the issue as most are targeted at 1 language or 2.

**Comment by TiraelSedai** [comment]
I would guess it's always something + English

**Comment by maxtop51** [comment]
Need this function on Sonarr !

**Comment by Ansem93** [comment]
I think using a checkbox would be better. There are too many possible combination to write them down.
Basically every EU country will look for his language+ english.

**Comment by maxtop51** [comment]
Do you have news for that indexer multi language selection?

**Comment by bidossessi** [comment]
> I would guess it's always something + English

`multi` is quite common for non-western movies with international dubs (Asia, India, wherever). Anime is a usual suspect for JP-EN and JP-FR combos, so English is not always in the mix, and shouldn't be assumed.

**Comment by CorentinB** [comment]
Hi all, any news ref. that issue? Thanks!

**Comment by DeenOub** [comment]
Need it too !

**Comment by jbdujardin** [comment]
Anyone can do this ? ☹️

**Comment by maxtop51** [comment]
@jbdujardin  Normally yes because Radarr have this function and basically its a edited Sonarr for Movies ... Its try to use the edited code of Radarr on Indexer section for edited sonarr so I never compile c# ahah

**Comment by daxxi13** [comment]
It would be better if we can set default language to an indexer.
All releases from this indexer without language in filename would be set to this language.
All releases with MULTI in filename would be default indexer language and original release language.

Sorry for my poor English

**Comment by CorentinB** [comment]
So.. I'm ready to pay someone to implement this at this point

**Comment by TwistedFaith84** [comment]
I believe this can be handled on the indexer side (Mostly). If the site can search for syntax then its easy; just type in all the syntax you want to search for then do your search. for example my nyaa.si search is
 _**"dub"|"multi audio"|"multi-audio"|"multiaudio"|"dualaudio"|"dual-audio"|"dual audio" -jam_club -takeover_rus -[GAE] -1anime -wakanim -JET_CLUB -[HIS] -VodkaDub -[Jisedai] -[WGA] -[anime-miako]**_
then when I search I just copy the actual link and create a new search indexer (TORZNAB|Custom) and have it search that way.
then when it finds and downloads it only downloads from stuff that I have all ready narrowed down. Yeah there are still some minor issues with this but not as many.

**Comment by NicolasFerec** [comment]
Sorry to dig up this old subject but has this been solved in any way? I'm struggling with languages detection as well. I set the cut off on french language and selected english too. I manage to set up the downloading with keyword pretty accurate, it gets mostly MULTI releases and it's great, but it then import them as english. So later on, it keeps on downloading them to try to get some french content... And replace my multi releases.

**Comment by sarakha63** [comment]
Yes i don't really understand why this issue was closed . 

For now we really need a simple option to say treat Multi as .....

So we can choose what language will apply sonarr to the downloaded file. This will avoid what is happening now

For now lets say i'm french with language profile and jackett and prowlarr replacement, sonarr catches Multi as french. It's great..

But once it processes it it will apply English...... as sonarr considers multi as English.

and what happens next is..... sonarr will kee searching to upgrade the language.... and so on...


If you dont have time to improve a lot the language part of Sonarr, you can just for now add a simple and easy option wich will be consider multi as.... 

Please come on

**Comment by NicolasFerec** [comment]
> Do you think a simple "consider Multi as " option for post processing would be simple enough to be implemented ? As for now multi is always considered english.

Instead of just complain about it I thought maybe I can do it myself. Men I'm having a hard time. It's everything but simple. The project is very complex and huge, thousands of code lines. And I never worked with C# before (or any compiled language for that matter), it's Chinese for me.

I'll keep you posted if, by a miracle, I finally work something out.

**Comment by sypkeke** [comment]
hello ! nothing new for this issue ?

**Comment by AdrienDsng** [comment]
Hi, any updates from someone on this potential feature ? Not really familiar with C# although would love to help.. Also really needs this feature. @NicolasFerec did you by any chance find a way to do it or at least a workaround ? Thanks in advance

**Comment by AN1MATEK** [comment]
Hello there, is there an open PR for this issue? Everything is a little mixed up and I cannot seem to find it. Cheers.

**Comment by toniopelo** [comment]
Needed for me as well! I would gladly open a PR but I'm not a C# dev, is it currently under development / planned ?
Or at least, is the idea of bringing the feature as it is implemented on radarr accepted by the maintainers and would a PR be merged ?

**Comment by markus101** [comment]
As far as I'm aware no one has expressed interest in implementing this in Sonarr. It may be possible to cherry pick this from Radarr with some changes to fit Sonarr's differences. Any PR would be considered and merged if appropriate.
