### ISSUE TITLE
SignalR, cannot access disposed object

### ISSUE THREAD

**Issue by rmccu** [Sonarr/Sonarr#2855]
**Describe the bug**
Sonarr/Sonarr#1654 was closed, but is still happening. I haven't seen the exception in Sonarr itself, but I am seeing it in Radarr. The issues in Radarr all point to #1654 in the Sonarr project, but that defect has been closed.

See Radarr/Radarr#3249

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: [e.g. 2.0.0.1]
 - Operating System: [e.g. Windows 10]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
OS: FreeNAS 11.2 (FreeBSD 11.2)
Mono Version: 5.10.1.57 (5.10.1.57 Wed Oct 3 04:32:48 UTC 2018)
Browser and Version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
Version (Radarr): 0.2.0.1217

**Additional context**

**Comment by markus101** [comment]
Nothing has changed since that was closed. The comment there still stands.

> This happens when the browser is refreshed or closed and a message is sent out before the server realizes it, it doesn't have any impact except some noise in the logs. Until we upgrade signalR (which requires .net 4.5+) there is no action planned, but something we're looking at for v3.

To reiterate, this exception does not cause any adverse effects.

PS you included a Radarr version, not a Sonarr version.
