### ISSUE TITLE
Sonarr fails to read/parse some media file's metadata.

### ISSUE THREAD

**Issue by Zenjir0** [Sonarr/Sonarr#2857]
**Describe the bug**
Sonarr fails to read metadata of some media files. (See additional context)

**Logs**
System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper managed-to-native) NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo.MediaInfo_Open_Buffer_Continue(intptr,byte[],intptr)
  at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo.Open (System.IO.Stream stream) [0x00062] in <85e2f5295c104ca3a3bcaa59e805585a>:0 
  at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo (System.String filename) [0x0007b] in <85e2f5295c104ca3a3bcaa59e805585a>:0

**System Information**
 - Sonarr Version: 2.0.0.5252
 - Operating System: Debian 9.5 (x64) 
 - Mono Version: 5.16.0.220

**Additional context**
I re-encode some of my media to save space, and recently I have noticed that Sonarr was crashing when it performed the "Refreshed Series" Function. I was able to fix this by updating Mono as I was running 5.10 and I am now on 5.16.

On the updated version of Mono, and running Mono with the --debug, I got the following error: 
Unable to parse media info from file: <PathToMedia>/<MediafilenameS00E00>.mkv: Object reference not set to an instance of an object. (See Logs above for more detailed error)

Reading the more detailed error log it seems to be failing within: NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo

And correct me if I am wrong, but that object is what is called on to collect/read the metadata of the file, and is based from MediaInfo (https://mediaarea.net/en/MediaInfo). I use this standalone program as well and it does not have an issue reading the metadata. 

Also to note is that, Sonarr has no issue manually importing files that I have re-encoded in the past using different preset settings than what I do now.  I've also noticed that it is only on a certain preset I use that Sonarr gets the error. (I use Handbrake for encoding, version Nightly 20181023173755-177c1e3-master).

I figured this might be fixed in an upcoming release as MediaInfo has had some changes made to it, but I figured I should share my findings, just in case.

Any help/insight would be appreciated. I will provide any other info if requested.

**Comment by markus101** [comment]
Which version of libmediainfo did you install? Sonarr does not include it unless you’re using macOS or Windows and often the version in the OS’s repo is ancient.

**Comment by Zenjir0** [comment]
I have not installed any Libmediainfo on the Linux box. I only use MediaInfo on my Windows machine to check certain metadata information. 

I am only assuming that Sonarr uses mediainfo based off of the error. I could be completely wrong, I am not 100% certain.

I'm currently running a few more tests to ensure I can replicate this issue with other series. If i need to provide more logs or screenshots i'd be happy to provide them.

**Comment by markus101** [comment]
You need libmediainfo installed for Sonarr to use it under Linux. It’s a dependency of the Sonarr Debian package and if you didn’t explicitly install it then it would have installed whatever ancient version is in debian’s repo. You’ll need to upgrade it, media info has their own repository you can add and use.

**Comment by markus101** [comment]
0.7.91 is old, update to the latest directly from mediainfo’s repo.

The content within the mkv is what matters, if media info can’t understand it then it’s going to have a bad time.

Closing this out as it’s something with media info, best to open a thread on the forums or reddit if you need anything more for this.

**Comment by Zenjir0** [comment]
@markus101 Thank you so much for your help. Looks like the Default Debian repo is not fully up-to-date and updating libmediainfo from their official repo worked like a charm.
