### ISSUE TITLE
Sonarr no longer communicating with Deluge

### ISSUE THREAD

**Issue by the-Dakta** [Sonarr/Sonarr#2859]
Describe the bug
I had a bunch of torrents added to Deluge through both Radarr and Sonarr (only mentioning Radarr for the sake of the issue) and now neither see these torrents in activity and are not being handled for sorting after the fact. Newly added torrents work fine, and the Deluge test passes.

To Reproduce
Reproducible by viewing both "activity" and the logs.

Expected behavior
Torrents previously added by Radarr to Deluge should be viewable in activity, and then handled after completion.

Screenshots
https://imgur.com/a/YMNEs8V

Desktop (please complete the following information):

OS: Debian 9
Mono Version: 5.16.0.220
Version 2.0.0.5252

Debug Logs
https://www.dropbox.com/s/6o7wmgx0kp5kxa3/sonarr.debug.txt?dl=0
https://www.dropbox.com/s/wnncf9v4f5kjq1v/sonarr.txt?dl=0

**Comment by markus101** [comment]
Looks like something in deluge doesn’t have a title, but I can’t tell exactly where it’s failing because you don’t have mono running with the `--debug` flag. You’re going to need that on for us to look at this further.

**Comment by the-Dakta** [comment]
So I've stopped my normal Sonarr service, and launched it manually using the --debug flag on mono, and Sonarr isn't loading any logs. This is all that's been output:

https://pastebin.com/Ceu3jpRu

**Comment by markus101** [comment]
Looks like it's running as a different user since it ran all the migrations again. You'll either need to run it as the same user or alter the service file to include that mono switch and then it'll always be there.

**Comment by the-Dakta** [comment]
Yeah I noticed that when more things loaded into the logs and I had no settings saved.

[I put the --debug switch into the service](https://i.imgur.com/M7bbToh.png) and now sonarr is explicitly telling me that [mono isn't running with the debug switch](https://i.imgur.com/E1kFJqA.png). Any thoughts why this would be?

**Comment by markus101** [comment]
It's not always detected properly, if the switch is there it should be fine.
