### ISSUE TITLE
FR/Bug: Download Station dowloads with Unknown-state currently marked as NaN%

### ISSUE THREAD

**Issue by RowanKaag** [Sonarr/Sonarr#2860]
**Describe the bug**
Some Download Station downloads are reported as "NaN%" within Sonarr, whilst being "Unknown" in Download Station itself. From a programming perspective, I can perfectly relate to this behaviour. From an end-users perspective, having the downloads show up as "NaN%" is causing a disrupted user experience when sorting by 'Progress' in the Activity tab.

**Screenshots**

<img width="89" alt="image" src="https://user-images.githubusercontent.com/6907625/50389407-43dba600-072a-11e9-9ab1-af8aa02a0741.png">

**Logs**
None

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Synology DSM 6.2.1-23824 Update 2
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.8.0.108

**UI Bugs:**
 - OS: macOS 10.14.2 (18C54)
 - Browser: Safari 12.0.2 (14606.3.4), Chrome 71.0.3578.98 (64-bit)

**Comment by markus101** [comment]
This won't be fixed in v2, but is handled in v3.
