### ISSUE TITLE
there is the option for hardlinks instead of copy. can you add a move option? mv.

### ISSUE THREAD

**Issue by Theangelofspace15** [Sonarr/Sonarr#2861]
I would love if you add the option to move (mv) instead of copy or hardlink.
that would make easy to keep track of what movies have been already imported. I have deluge make a copy of completed download to a different folder than the seed folder so I want to be able to move those to the final destination. when the folder is empty, that means everything have already been imported.

**Comment by markus101** [comment]
Sonarr will only move the file if it's finished seeding. No plans for a forced move such as this, a custom script would be your path forward here.

**Comment by Theangelofspace15** [comment]
thanks. How can i make a script to delete source file after import?
