### ISSUE TITLE
Wrong file linked to multiple episodes

### ISSUE THREAD

**Issue by garlandkr** [Sonarr/Sonarr#2862]
**Describe the bug**
Sonarr is matching the wrong file to multiple episodes and marking them all as downloaded, including future episodes that have not aired yet.

Existing file: 2018-11-24.mkv
Linked with all future episodes and marked as downloaded.

**Screenshots**
https://imgur.com/J6MUjeK

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Ubuntu
 - mono Linux Version: 5.16.0.220

**Additional context**
After selecting the correct episode from a manual search Sonarr will download the episode but fails to move it to the show directory citing the version that exists already has more versions than needed.

**Comment by markus101** [comment]
Fixed by https://github.com/Sonarr/Sonarr/commit/9f16d9b2fcf9b937d4fc46631f9bd3d813eb43f5
