### ISSUE TITLE
"Monitor Future" when adding new series correctly flags episodes, but not series

### ISSUE THREAD

**Issue by goldcd** [Sonarr/Sonarr#2863]
When adding a new series and selecting "Monitor Future", Sonarr correctly only marks known future episodes as monitored.
However, previous series are flagged as monitored, even though none of their child episodes are.
i.e. Initially it looks like all episodes are monitored and user has to expand series to see this isn't the case.
e.g.
![image](https://user-images.githubusercontent.com/25711112/50538579-7aba1d80-0b69-11e9-98d5-a9ab7c41be55.png)
![image](https://user-images.githubusercontent.com/25711112/50538589-8c032a00-0b69-11e9-820d-c6e18e2c3aa4.png)

UX issue is:
a) It initially looks like a series is monitored, when it isn't.
b) To download an old series user has to set it to be unmonitored, then "re-monitor" it.

Very minor bug/enhancement - but would think the "add new series process" would be more intuitive if series flag was set to unmonitored, if all of the child episodes are unmonitored.

**System Information**
- Sonarr Version: [2.0.0.5252]

**Comment by Taloth** [comment]
This works correctly in v3, so you'll get it when v3 is released to mainstream. (Just be patient for the release)
I'm not sure if it already works correctly in v2, I don't have a v2 install readily available right now.

Before:
![image](https://user-images.githubusercontent.com/6383890/50539398-f9ba5080-0b7f-11e9-87f0-f72adb7e0e12.png)

After:
![image](https://user-images.githubusercontent.com/6383890/50539403-063ea900-0b80-11e9-8d61-ce34e9fe131f.png)

**Comment by goldcd** [comment]
Thanks for the quick response.
New UI implementation looks like a great improvement.
