### ISSUE TITLE
[yggtorrent] No result with Jackett

### ISSUE THREAD

**Issue by MoonLS** [Sonarr/Sonarr#2864]
Hi

I'm on Arch-linux

My Jackett version is Package Details: jackett 0.10.566-1 - Last Updated: 2018-12-29 00:53
My Sonarr version is Package Details: sonarr 2.0.0.5252-1 - Last Updated: 2018-10-09 17:20

I have configured 2 indexer in Jacket :
- yggtorrent
- nyaa

I have configured 2 custom indexer in Sonarr, the test are OK

- jackett_ygg
- jacket_nyaa

When I test to search in Sonarr with jackett_ygg, I have no result in auto and manual search
When I test to search in Sonarr with jackett_ygg, I have no result on auto but I have some in manual search

When I test to search in Jackett, I have result for both indexers.

This is the logfile of Sonar when i search with jackett_ygg
`18-12-29 19:24:54.5|Info|NzbSearchService|Searching 1 indexers for [Boruto: Naruto Next Generations : 87] 18-12-29 19:24:55.1|Info|DownloadDecisionMaker|No results found 18-12-29 19:24:55.1|Info|EpisodeSearchService|Episode search completed. 0 reports downloaded.`

This is the logfile of Sonar when i search with jackett_nyaa
`18-12-29 19:29:52.7|Info|NzbSearchService|Searching 1 indexers for [Boruto: Naruto Next Generations : 87] 18-12-29 19:29:53.1|Info|DownloadDecisionMaker|Processing 14 releases 18-12-29 19:29:53.2|Info|EpisodeSearchService|Episode search completed. 0 reports downloaded.`

**Comment by markus101** [comment]
Please use the forums for support/questions. We’ll need debug logs of the search.

**Comment by MoonLS** [comment]
The search isn't very good to match.
It search only the absloute number.
Why not "RWBY.S06E06" ?

`déc. 30 00:40:32 Agamemnon sonarr[544]: [Info] NzbSearchService: Searching 1 indexers for [RWBY : 74]
déc. 30 00:40:32 Agamemnon mono[542]: 12-30 00:40:32 Info Found 0 releases from YGGtorrent for: RWBY 74
déc. 30 01:08:26 Agamemnon sonarr[544]: [Info] NzbSearchService: Searching 2 indexers for [RWBY : 74]
déc. 30 01:08:26 Agamemnon mono[542]: 12-30 01:08:26 Info Found 0 releases from YGGtorrent for: RWBY 74
déc. 30 01:09:27 Agamemnon sonarr[544]: [Info] NzbSearchService: Searching 2 indexers for [RWBY : 73]
déc. 30 01:09:27 Agamemnon mono[542]: 12-30 01:09:27 Info Found 0 releases from YGGtorrent for: RWBY 73
déc. 30 01:09:42 Agamemnon sonarr[544]: [Info] NzbSearchService: Searching 2 indexers for [RWBY : 74]
déc. 30 01:09:43 Agamemnon mono[542]: 12-30 01:09:43 Info Found 0 releases from YGGtorrent for: RWBY 74
déc. 30 01:09:49 Agamemnon sonarr[544]: [Info] NzbSearchService: Searching 2 indexers for [RWBY : 74]
déc. 30 01:09:49 Agamemnon mono[542]: 12-30 01:09:49 Info Found 0 releases from YGGtorrent for: RWBY 74
déc. 30 01:23:11 Agamemnon sonarr[544]: [Info] NzbSearchService: Searching 2 indexers for [RWBY : 74]
déc. 30 01:23:11 Agamemnon sonarr[544]: [Debug] Nyaa: Downloading Feed https://nyaa.si/?page=rss&filter=1&term=RWBY+74
déc. 30 01:23:11 Agamemnon sonarr[544]: [Debug] Torznab: Downloading Feed http://localhost:9117/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=2000,5000,5070,102179&extended=1&apikey=khfrdmft44fp5
04fbii0hhcbumjg9n5f&offset=0&limit=100&q=RWBY+74
déc. 30 01:23:11 Agamemnon mono[542]: 12-30 01:23:11 Info Found 0 releases from YGGtorrent for: RWBY 74
déc. 30 01:23:11 Agamemnon sonarr[544]: [Debug] NzbSearchService: Total of 0 reports were found for [RWBY : 74] from 2 indexers`

**Comment by markus101** [comment]
Anime searches use absolute, searches for standard series use season + episode numbers.
