### ISSUE TITLE
Sonarr-V3 incomplete show data

### ISSUE THREAD

**Issue by WesNz** [Sonarr/Sonarr#2865]
iv noticed that the episodes listings seem to be incomplete with more than 1 show.
Data just seems incomplete....however the correct data is showing on tvdb.

Eg. Tanked shows upto s15ep3 on sonarr, but s15e10 is available. Eg2. Vikings on sonarr shows upto s5e11 (tba).. But s15e14 is available according to tvdb

Anyone else having these issues?

**Comment by markus101** [comment]
Looks fine on my end, check debug logs and open up a thread on the forums or reddit if you're still having issues.
