### ISSUE TITLE
Sort torrents by quality based on the seeders and the cutoff

### ISSUE THREAD

**Issue by Abdulla060** [Sonarr/Sonarr#2867]
**Describe the problem**
During my time using Sonarr, I have noticed that it tend to choose poor torrents usually ones with really low seeders. and upon digging around I discovered that this problem is mainly caused by the fact that Sonarr sorts by the quality before anything else. this has the potential to push any torrent no matter how good it is down the list and the bad ones up. Of course not sorting by the quality will solve this problem but will create many others.  

**Describe any solutions you think might work**
My solution to this problem is instead of sorting by the quality order from the profile. First sort the qualities in the profile by the total number of seeders in each quality first then use the new order to sort the torrents by their quality. and don't sort the whole profile instead sort the qualities that are equal or better than the cutoff quality.
so, for example, let say you have the following 720p-profile
https://i.imgur.com/G6ITB4o.png
which is the standard 720p profile in Sonarr
then your search for an episode for example and you find out the total number of seeders in each quality is as follows 

https://i.imgur.com/u3dBW9z.png 

since the cutoff is at HDTV-720p the qualities that are equal or better to the cutoff (HDTV-720p, WEBDL-720p, BluRay-720p) will be sorted based on their seeders and will become like this

https://i.imgur.com/7reBFga.png

then you can use the new order when you sort the torrents to make the decision.

and also if the cutoff is at WEBDL-720p for example then the order will become like this

https://i.imgur.com/1SbKh1E.png

and if the cutoff is equal to the highest quality in the profile, then no sorting will be done on the profile and everything will continue as it does now

this solution should solve the seeders problem while not affecting the current state of Sonarr too much. Maybe you can add a new checkbox that enables and disable this feature so people can experiment with it. or maybe they can have a separate profile for the initial download and then another one for maintaining the show which is much better than to download each episode manually which can take ages to finish.

**More Notes**
the only disadvantage that this will cause is if you set the cutoff to a low quality and then this low quality happens to also have the largest number of seeders while the other qualities have a smaller but very close number of seeders then Sonarr will choose the cutoff even though it could have chosen a better one (But this is a very specific case and can be solved by the log10 treatment)

also instead of instead of taking the total number of seeders maybe take only the torrent with the highest seeders and the others that are within 25% of it so the number total seeders don't get bloated if a certain quality has a lot of torrents that have 1 or 2 seeders.

Sorry of the long post but I really wanted to get this idea through

**Comment by markus101** [comment]
We do not have plans to change this, quality wins. You do have the option to set the minimum number of seeders at a per-indexer level, anything lower will be rejected. If the indexer is misrepresenting the number of seeders that's a problem with the indexer.

**Comment by Taloth** [comment]
I'd like to add that plenty of indexers do not even supply seeder info. What you really need in this case is stalled-torrent handling, so that downloads that cannot be finished are handled gracefully.
But that's only really relevant on public trackers.
