### ISSUE TITLE
Episode search matches decimal point numbers (e.g. 10 matches 10.5)

### ISSUE THREAD

**Issue by rcdailey** [Sonarr/Sonarr#2868]
**Describe the bug**

When doing an automatic search for S01E10 of Goblin Slayer (anime show), I get matches for episode `10.5`, which is incorrect.

**Screenshots**

![image](https://user-images.githubusercontent.com/1768054/50566347-3a3fd880-0cfe-11e9-9123-92168476e5a7.png)

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: [Docker Image](https://hub.docker.com/r/linuxserver/sonarr/)

**Comment by Taloth** [comment]
Edit to add background info:
Similar releases: `[HorribleSubs] Goblin Slayer - 10.5 [1080p].mkv`
10.5 is a recap episode so definitely shouldn't be grabbed.
Not to be confused with releases such as 10v2 which is a repack/proper.

**Comment by xelra** [comment]
We had .5 episodes in the past and I thought that Sonarr handled them correctly.
