### ISSUE TITLE
Option to deactivate manual processing

### ISSUE THREAD

**Issue by hr1232** [Sonarr/Sonarr#2869]
**Describe the problem**
If sonarr doesn't find importable media it puts the nzb/torrent on hold (probably to allow for extraction of archives or whatever). Same "problem" with any other manual processing exception (everything that doesn't get importet or blacklisted automatically but needs manual interaction.

**Describe any solutions you think might work**
This is very impractical because it goes completely against the concept of true automation. It requires the user to interact with Sonarr so a new episode may not come up in Plex automatically because Sonarr is waiting endlessly instead of just trying another nzb/torrent.

Please give us an option to dismiss and blacklist any nzb/torrent that cannot be processed automatically. If this option is activated, Sonarr should blacklist and replace ANY nzb/torrent that cannot be processed and imported without manual interaction and thereby become a truly automatic service.

I realize that users may miss out on some episodes because some nzbs/torrents can be imported correctly with manual interaction. However, in most cases nzbs/torrents that are marked for manual processing need to be deleted anyway and (considering the intent of the software) an option for COMPLETE automation should perhaps not only be there but it should maybe also be the default.

**Comment by hr1232** [comment]
Examples for the messages I am talking about:
- no files eligable for import found
- one file contains all episodes
- episode number mismatch in filename/nzb-title
- file with exact same filesize already exists
...

**Comment by markus101** [comment]
We have no plans for such an option. This will inevitably lead to people enabling it and not understanding what it does and complaining that Sonarr downloaded several copies, but didn’t import anything and kept trying other versions.

A notification of a failed download (https://github.com/Sonarr/Sonarr/issues/2474) with a custom script would be the way to automate this.

**Comment by hr1232** [comment]
People are too stupid to deal with such an option? Really? What kind of an answer is that?

Please remember the goal of Sonarr is to AUTOMATE downloads. Flooding the user with manual processing results is not really a good kind of automation. If they want to extract archives manually they would do so. They are using Sonarr because they want **AUTOMATION**.

I am not saying that manual post-processing should taken out of Sonarr completely. Just give us an option that will make Sonarr blacklist any release it would normally flag for manual post processing. How many lines of code will that actually be? 10? 15? Make it an advanced option if you want to. Give it a big-ass red level warning 'ATTENTION, you will probably loose releases, done by release groups wo provide top quality but are to fucked up to label their nzbs correctly'. Add another label 'we will laugh at you if you complain about releases being blacklisted with this option turned on'.

But saying people are too stupid to grasp automation is just wrong. Also, currently there is a kind of automation in place because people will click manual postprocessing, then realize the message is bullshit, then click delete, blacklist, ok. Please give us automation without mouse clicks.

----

**one file contains all episodes**
are often dvd/br rips which were mis-labled. and yes, i accept there are also things like "s01 first episode" which does only contain first episode but is parsed as season 1. this error is often truely a parsing error BUT it is a parsing error wich mostly leads to delete and blacklist so there should be an option to automate it, even if (in rare cases) it will through out a release that could have been imported.

**file with exact same filesize already exists**
is the most annoying one. it makes no sense at all to keep these for manual processing. Sonarr has sucessfully determined that a file with equal or better quality exists, yet it keeps the mis-labled release of poorer quality around and annoys the users by forcing them to deal with something that could be automated. This message serves no purpose at all except to annoy the users. Preventing import loops is important but Sonarr can do that on its own.

**episode number mismatch in filename/nzb-title**
does (in most cases) not refer to a parsing issue. It occurs when the nzb title says s01e02 and the file contained in it says s01e01. Most of the time this comes up with REALLY fresh releases when someone tries to be the first to release something and get everybody to download it. Sometimes it's just an old release with new title by somebody who wants to get hits or to annoy us. Sometimes these releases also contain little video messages like "got you, we logged you ip and we will sue you". In any case releases where the nzb title has a different episode number then the file contained inside are bullshit and should be ignored.

**no files eligable for import found**
mostly refers to archives. sometimes recursive unpacking doesn't work in nzbget/sabnzbd for several reasons. it seams that 'mark bad if password protected' only works if the first layer of archives is protected. if the second layer is password protected the first is unpacked and the release is marked a downloaded successful. This seems to be happening in nzbget and sabnzbd.
also refers to files with wrong extensions and/or mime types. some releases contain manipulated media files which cannot be recognized as such. they also contain a .bat script to remedy the situation and give you a working media file.
in case of the encrypted archive there's nothing to be done so the release must be deleted. Sonarrs position has always been "that's " the downloader's job, Sonarr will no extract archives. This is fine, but the logical consequense is that Sonarr has to delete archives because obviously the downloader wasn't able to deal with the problem.
in case of the bat file you need to check if the script actually converts the media file or just fucks up your system and then you need to execute it - provided you have Windows. This releases are bullshit and should be banned.

**And another one I forgot earlier:
sample found**
This one comes up, if the only media file found is much shorter than the actual media should be. You can deal with it automatically, because either it is a fake (or a mis-labeled dvd extra) or which comes up far more often the real media file is in an encrypted archive so Sonarr cannot get to it. No point in keeping these releases around.

**Comment by hr1232** [comment]
@markus101 
People are too stupid to deal with such an option? Really? What kind of an answer is that?

Please remember the goal of Sonarr is to AUTOMATE downloads. Flooding the user with manual processing results is not really a good kind of automation. If they want to extract archives manually they would do so. They are using Sonarr because they want **AUTOMATION**.

I am not saying that manual post-processing should taken out of Sonarr completely. Just give us an option that will make Sonarr blacklist any release it would normally flag for manual post processing. How many lines of code will that actually be? 10? 15? Make it an advanced option if you want to. Give it a big-ass red level warning 'ATTENTION, you will probably loose releases, done by release groups wo provide top quality but are to fucked up to label their nzbs correctly'. Add another label 'we will laugh at you if you complain about releases being blacklisted with this option turned on'.

But saying people are too stupid to grasp automation is just wrong. Also, currently there is a kind of automation in place because people will click manual postprocessing, then realize the message is bullshit, then click delete, blacklist, ok. Please give us automation without mouse clicks.

----

@Taloth 

**one file contains all episodes**
are often dvd/br rips which were mis-labled. and yes, i accept there are also things like "s01 first episode" which does only contain first episode but is parsed as season 1. this error is often truely a parsing error BUT it is a parsing error wich mostly leads to delete and blacklist so there should be an option to automate it, even if (in rare cases) it will through out a release that could have been imported.

**file with exact same filesize already exists**
is the most annoying one. it makes no sense at all to keep these for manual processing. Sonarr has sucessfully determined that a file with equal or better quality exists, yet it keeps the mis-labled release of poorer quality around and annoys the users by forcing them to deal with something that could be automated. This message serves no purpose at all except to annoy the users. Preventing import loops is important but Sonarr can do that on its own.

**episode number mismatch in filename/nzb-title**
does (in most cases) not refer to a parsing issue. It occurs when the nzb title says s01e02 and the file contained in it says s01e01. Most of the time this comes up with REALLY fresh releases when someone tries to be the first to release something and get everybody to download it. Sometimes it's just an old release with new title by somebody who wants to get hits or to annoy us. Sometimes these releases also contain little video messages like "got you, we logged you ip and we will sue you". In any case releases where the nzb title has a different episode number then the file contained inside are bullshit and should be ignored.

**no files eligable for import found**
mostly refers to archives. sometimes recursive unpacking doesn't work in nzbget/sabnzbd for several reasons. it seams that 'mark bad if password protected' only works if the first layer of archives is protected. if the second layer is password protected the first is unpacked and the release is marked a downloaded successful. This seems to be happening in nzbget and sabnzbd.
also refers to files with wrong extensions and/or mime types. some releases contain manipulated media files which cannot be recognized as such. they also contain a .bat script to remedy the situation and give you a working media file.
in case of the encrypted archive there's nothing to be done so the release must be deleted. Sonarrs position has always been "that's " the downloader's job, Sonarr will no extract archives. This is fine, but the logical consequense is that Sonarr has to delete archives because obviously the downloader wasn't able to deal with the problem.
in case of the bat file you need to check if the script actually converts the media file or just fucks up your system and then you need to execute it - provided you have Windows. This releases are bullshit and should be banned.

**And another one I forgot earlier:
sample found**
This one comes up, if the only media file found is much shorter than the actual media should be. You can deal with it automatically, because either it is a fake (or a mis-labeled dvd extra) or which comes up far more often the real media file is in an encrypted archive so Sonarr cannot get to it. No point in keeping these releases around.

**Comment by hr1232** [comment]
**and another one:
invalid season or episode**

This brilliant one leaves you with bullshit releases like this one.
NZB Title: Sons Of Anarchy S07 COMPLETE 1080p BluRay X264
Files:
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/010E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/10E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/11E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/20E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/21E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/30E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/31E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/40E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/50E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/60E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/70E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/80E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/90E70S.yhcranA.fo.snoS.mkv

available episode numbers in season 7: 1-13

They are all there and they are all in good quality, but will anybody really open up all media files in order to sort them to the correct episode numbers? i even checked for the sake of this ticket, because i noticed 0100E70S-90E70S at the end, but they are not in order, they are purely random! there are hundrets of other releases for season 7 and 99.9% of all users will blacklist this one in order to have Sonarr download another release. However this will only happen after manuall post-processing which ist absolutely annoying and not what people want.

**Comment by Taloth** [comment]
**"sample found" & "no file eligible for import found".**
Please add one of those post-processing scripts to nzbget/sabnzbd. Those will be quite effective in culling out fake releases.
Some of those scripts can also parse those bat files without executing them, and deobfuscate the release.
Btw. I never get those kind of fake releases. It may be a matter of indexers, coz certain indexers already nuke bad releases like that.

**Edit: "invalid season or episode"**
Awesome example, thanks. We already detect and automatically fix some of those reverse files. But I suspect it's stumbling over the 3-digit episode number in there.
I added https://github.com/Sonarr/Sonarr/issues/2871 for that. If you find other reversed titles, post them there so we can add them to our test suite.

"episode number mismatch in filename/nzb-title"
We're still considering options about what to do in this particular scenario, it's one of those situations we still need more statistics about. It usually boils down to unmoderated indexers.

**"one file contains all episodes"**
Please provide one or more examples (including both release titles and filenames). With some luck we might be able to detect the scenario.

**Comment by markus101** [comment]
People absolutely enable/disable options and wait to see what happens, in this case it could be days/weeks/months before they run into this case and have forgotten about the setting entirely. As Taloth has mentioned knowing exactly what is happening is important to address the issues that we can. Perhaps automating the blacklisting will make sense in some cases, we'll have to see, but as of right now it's not a consideration.

I agree that the same filesize rejection is annoying and was there to solve a problem with conflicting release and file names (the indexer says it's X, but Sonarr thinks it's Y at import time), this issue should be resolved though and this rejection can probably die, if people are actively running into repeated imports it's likely some misconfiguration and not something Sonarr should try to protect against.

> This brilliant one leaves you with bullshit releases like this one.
NZB Title: Sons Of Anarchy S07 COMPLETE 1080p BluRay X264

This looks like something Geek would do (though there may be others doing the same), taking separate episode releases and making them a single season pack, beyond the naming any take downs will likely cause issues with the whole pack, single episodes would be better, IMO.

If you want to automate this right now, you can use Sonarr's API to find anything in the queue that can't import then remove and blacklist it, it'll be more than 10-15 lines of code, but so would an option. https://github.com/Sonarr/Sonarr/wiki/Queue

**Comment by hr1232** [comment]
Using https://github.com/Sonarr/Sonarr/wiki/Queue through a php script triggered by cron seems to be an acceptable workaround.

will "delete and blacklist" be just that or will it also initialte a new search like it does in the gui? if it doesn't it's not really automation but just cancelation because after deteling and blacklisting the episode you would have to wait and hope that a new release will come up in rss....

**Comment by markus101** [comment]
The UI uses that exact endpoint so it will do exactly the same thing.

**Comment by hr1232** [comment]
> People absolutely enable/disable options and wait to see what happens, in this case it could be days/weeks/months before they run into this case and have forgotten about the setting entirely.
Stupid people shouldn't be the basis for decisions. Even in times when America makes it the basis for electing presidents.

>Perhaps automating the blacklisting will make sense in some cases, we'll have to see, but as of right now it's not a consideration.
That's why it should be an option, because - obviously there are the .1% who will actually do manual post processing and not just click delete and blacklist.

> I agree that the same filesize rejection is annoying and was there to solve a problem with conflicting release and file names (the indexer says it's X, but Sonarr thinks it's Y at import time), this issue should be resolved though and this rejection can probably die, if people are actively running into repeated imports it's likely some misconfiguration and not something Sonarr should try to protect against.
it's not mis-configuration. you know the code, you know why it's there, you know what it's doing. it's exactly that and nothing else. Releases are tagged incorrectly and therefor downloaded in vain. Nothing to do here in manual post-processing except to delete and blacklist the release.

> This looks like something Geek would do (though there may be others doing the same), taking separate episode releases and making them a single season pack, beyond the naming any take downs will likely cause issues with the whole pack, single episodes would be better, IMO.
it's true that many season packs cannot be processed correctly - far more errors than with single episode releases. Also, with season packs, takedowns occur much more often so availability is not that great. Yet, Sonarr obvsiously preferres season packs when you do a series search or season search. Why is that? Might be time to change that and to prioritize single episode releases over season packs...

> If you want to automate this right now, you can use Sonarr's API to find anything in the queue that can't import then remove and blacklist it, it'll be more than 10-15 lines of code, but so would an option. https://github.com/Sonarr/Sonarr/wiki/Queue

>The UI uses that exact endpoint so it will do exactly the same thing.

In that case I'll the the workaround myself and link it here in case someone else wants to use it.

**Comment by hr1232** [comment]
According to your docu, the following should delete an entry from the queue and blacklist the nzb:

`curl --request DELETE --data '{"id":1686316833,"blacklist":true}' http://127.0.0.1:8989/api/queue?apikey=12345678901234567890123456789012`

Sadly the response is

`{"message": "MethodNotAllowed"}`

So while GET method is working perfectly, DELETE doesn't seam to be implemented. I'm running Sonarr version 2.0.0.5252.

**Comment by Taloth** [comment]
The docs are incorrect on the Delete command. Delete verbs cannot have a post body so the parameters are passed by url. `/api/queue/{id}?blacklist=true`. Sonarr's api is for the most part a REST api.

**Comment by hr1232** [comment]
workaround is a little php script that can either be called locally or through the web interface by cron.

[https://github.com/hr1232/SonarrCleanup](https://github.com/hr1232/SonarrCleanup)
