### ISSUE TITLE
Reverse Title not handled

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#2871]
Sonarr doesn't handle this particular reverse title and gives an 'invalid season or episode' error.

NZB Title: Sons Of Anarchy S07 COMPLETE 1080p BluRay X264
Files:
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/010E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/10E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/11E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/20E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/21E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/30E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/31E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/40E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/50E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/60E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/70E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/80E70S.yhcranA.fo.snoS.mkv
XxQVHK4GJMP3n2dLpmhW/XxQVHK4GJMP3n2dLpmhW/MKV/90E70S.yhcranA.fo.snoS.mkv

Look to me like the regex doesn't handle the 3 digit episode number, or maybe that it doesn't have a anchor.

**Comment by thezoggy** [comment]
`010E70S` looks like typo as there is a E10 listed so it should be E01.. thus `10E70S` but no real way for you to know unless you scanned all the files in the set and applied logic to figure it out :/

**Comment by Taloth** [comment]
No, 10E70S is listed which reversed is S07E01... not 10. 
The 010E70S becomes S07E010 reversed, so episode 10. So all are unique and parseable.

**Comment by thezoggy** [comment]
all the episode in the file are only two digits with a leading 0 placeholder except the one `010E70S` which has three digits.. which is why it looks like a typo.
