### ISSUE TITLE
Single quote in special title prevents match

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#2872]
**Describe the bug**
The Profit 0x11 - An Inside Look: Sweet Pete's
Release title The.Profit.S06E00.An.Inside.Look-Sweet.Petes.720p.HDTV....

The specials parser normalizes both titles, but replaces the single quote with a space and therefore is rejected.

Adjusting the normalizer to always strip out the single quote is risky coz some releases might have spaces instead. Better is to follow up with a compare using CleanTitle over the normalized title, which removes all spaces.

**Comment by thezoggy** [comment]
pretty sure scene releases wont have `'` as they get stripped out..  now p2p/torrents is another story.
what about dropping the `'s` as Pete would still match?
