### ISSUE TITLE
Changes in series Editor and Season Pass don't stick after saving

### ISSUE THREAD

**Issue by saviodesign** [Sonarr/Sonarr#2873]
**Describe the bug**
When making changes in **Series Editor** and **Season Pass** in the Web UI, the modified changes do not stick after saving. Once saved, choose to either update, or navigate to an alternate page, and return, the items chosen have not been modified.

**Screenshots**
Will replicate issues and provide upon request

**Logs**
Will provide upon request.

**System Information**
  - Mono Version 5.10.1.57
 - Operating System: Linux - FreeNAS 11.2 

**UI Bugs:**
- Browser: Chrome, firefox]
- Sonarr Version 2.0.0.5252

**Additional context**
These two items have never worked for us, even after 2 updated version, if you think we may be doing something wrong, please let us know. This causes us to have to manually navigate back and forth, and add these settings to each show/category, along with specifying profiles for searching and tagging each season along with the unaired items/episodes manually. Could become a bit tasking after around 10 items.

**Comment by markus101** [comment]
Working fine for me, going to need trace logs at a minimum, you can also look at the dev tools in your browser (F12), network will show the requests.

**Comment by saviodesign** [comment]
Give me a bit, I try the items you've suggested.

**Comment by saviodesign** [comment]
Marcus, what your version installed 
http://local.host:8989/serieseditor ( shown on the bottom of the page)

I've tried your recommendation in (2) alternated browsers with no plugins ( Chrome and IE), same results

**Comment by markus101** [comment]
Same as you, 2.0.0.5252. Working in FF and Chrome.

I'm not sure what you mean by "choose to either update", do you mean reload the page?

> the items chosen have not been modified.

Meaning their unselected or the settings you just saved were wiped out?

How many series are you updating at once?
Have you tried 1 or 2? Instead of 10, 20 or more?

**Comment by markus101** [comment]
We can reopen this if we get more information, but as of right now I'm not able to reproduce.
