### ISSUE TITLE
MediaInfo AudioCodec Missing from Rename

### ISSUE THREAD

**Issue by ShiroiKuma** [Sonarr/Sonarr#2874]
**Describe the bug**
Some episodes are being renamed with correct MediaInfo AudioCodec, some files are missing this data. All from the same source/series.

Using mediainfo <filename> from within the container produces correct results when using mediainfo 18.12 on Ubuntu.

**Screenshots**
![image](https://user-images.githubusercontent.com/7948640/50620595-9cd5e600-0f43-11e9-9829-2669ced5d63f.png)

**Logs**
Episode 01 Information: https://pastebin.com/wB4XiAKV
Episode 02 Information: https://pastebin.com/vzCBaqYp

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Ubuntu 16.04.5 LTS (Xenial Xerus)
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.16.0.220

**Additional context**
It sounds similar to #2500, because if I rename Episode 2's h265 to x265 it will work as expected. But I cannot be sure if it truly is the same bug. Is there is any information that can be provided to help out further?

**Comment by markus101** [comment]
Have you determined if Sonarr actually has media info for those files stored?

**Comment by ShiroiKuma** [comment]
Once I renamed them to x265 instead of h265, detection and renaming worked fine. Another season is about to finish, so let me confirm the libmediainfo version and check as soon as that's done.

**Comment by markus101** [comment]
You shouldn't need `libmediainfo-dev`.

> Once I renamed them to x265 instead of h265, detection and renaming worked fine.

That sounds like Sonarr didn't have media info for those files previously and the rename pulled that information in.

Closing this out since it doesn't look like there is anything for us to do here, but we can re-open if there is more information available later on.
