### ISSUE TITLE
Title Slug Overlap

### ISSUE THREAD

**Issue by apclapp** [Sonarr/Sonarr#2875]
I see a message "Title slug 'manhunt' is in use by series 'Manhunt'" when trying to add the series Manhunt (2019), which presumably overlaps with Manhunt (2017)-- a series which has stopped airing.

Is it possible for me to add the new series and for the two series for me to coexist? I didn't see any way I can change the 'slug', and the folder namings are different already. Perhaps it is worth allowing overlapping slugs (or assigning a new ID for duplicate slugs) if a prior series has 'Ended'.

**Comment by markus101** [comment]
Both series are called `Manhunt`, one from 2017, the other from 2019. The 2019 series is incorrectly named on TheTVDB and should include the year (or possibly country if it's from a different country). TheTVDB will need to fix the naming, you can't have two series with the same title in Sonarr.

**Comment by apclapp** [comment]
I updated the namings for the show on TheTVDB-- one to be (2017) and the other to be (2019)-- is the name of the series what Sonarr uses for the slug, or is it the URI (which TheTVDB has as manhunt-unabomber and manhunt), or is the slug pulled from something entirely separate that users cannot edit?

**Comment by markus101** [comment]
> I updated the namings for the show on TheTVDB-- one to be (2017) 

The original series' title should not be changed, only the 2019 series with the same name.

> is the name of the series what Sonarr uses for the slug

It's based on the title, we don't track their slug at all (not even sure we can).

**Comment by apclapp** [comment]
Alright, it seems to be working now. Thanks again for the quick replies and for the help. Perhaps it could be worth looking into extracting their slugs from their url's? Those appear to be immutable and unique from series creation. Their V2 API returns both a 'name' and 'slug' value in the GET /series call, so it looks feasible (if useful).

**Comment by markus101** [comment]
It may be useful to use their slugs, something we'll have to look at when we move to the v2 API. Regardless you're going to have a bad time if you add multiple series with the same title, at best in this case it'd have run into a path conflict or problems matching releases later.
