### ISSUE TITLE
Sonarr hangs a long time on retrieving non-existent Root Path

### ISSUE THREAD

**Issue by irritatedcone** [Sonarr/Sonarr#2877]
**Describe the bug**
I switched file-servers a few weeks back and added my new path as the new root folder.
Everytime I went to request something it would take a long time to show me the paths I could use (manually adding them gave me the "already configured as root path" message).
When I removed the no longer existing path everything was near instant again.

It takes too long for Sonarr to stop trying to reach that path.
It also doesn't show you ANY path until it times out, and it doesn't say it's still searching for paths.

This issue is in Sonarr, Radarr and in Lidarr, so I'll create a bug report in all.

**Screenshots**
![root paths](https://user-images.githubusercontent.com/44037605/50725052-e8c98c00-10f7-11e9-9159-fecf2ee3992e.PNG)
0b = dead fileserver
12.5TB = new fileserver

**Logs**
There isn't really and log or error to speak of.
It doesn't show up in the logs.

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Windows Server 2016

**Comment by irritatedcone** [comment]
It was using the hostname. ($host.$domain - the entry is still in the defined DNS server, but the host itself isn't up anymore)

**Comment by Taloth** [comment]
So it's just the network timeout.

**Comment by markus101** [comment]
Is there anything we can actually do here? There might be an OS setting to control the timeout for shares, but that's definitely outside of what we'd do. Unless we're going to try to come up with something ourselves, but the payoff seems pretty low and just removing the path solves it.

**Comment by Taloth** [comment]
Yes, Task.Run and wait for that task for 3 seconds.
If it takes more than 3 seconds, don't return the freespace value. Let the Task continue to run in the background, likely timing out completely, and cache that result for x time.
The free-diskspace stuff is only cosmetic.
