### ISSUE TITLE
Backup / Export Sonarr Config to External Storage / Email

### ISSUE THREAD

**Issue by thewonderer73** [Sonarr/Sonarr#2878]
Automate a way to export Sonarr config data off the device it's running on without having to use  cli / other tools to export.  Even be able to easily edit the exported config would be great as importing the config into a newly built linux build with slightly different OS version / setting makes the import fail.

Exporting Sonarr of a headerless linux device like the rock64 to a Windows PC or a preconfigured email address would be very useful.

**Comment by markus101** [comment]
v3 will allow you to set the location for backups, no plans for sending backups to email/uploading to FTP or similar.

At this time we do not have plans to convert databases between different OSes.
