### ISSUE TITLE
Add option in interface to change tvdb url

### ISSUE THREAD

**Issue by Joe00** [Sonarr/Sonarr#2879]
Please add an option in the interface to change the tvdb link to another url.
In german we have glotz.info which contains all german airdates. So Sonarr searches only for new episodes if they are released in german.

**Comment by markus101** [comment]
> So Sonarr searches only for new episodes if they are released in german.

Sonarr doesn't search for episodes, it checks RSS feeds, this is covered in the FAQ.

No plans to have an option to change the URL used for TheTVDB in the UI.
