### ISSUE TITLE
Requests from Kodi?

### ISSUE THREAD

**Issue by Chris230291** [Sonarr/Sonarr#2881]
Hi. I looked and couldnt find exactly what I wanted. But if anyone knows of something please let me know.

I thought it would be neat to add shows/episodes to Sonarr from the Kodi EPG, the same way you would record a show.

Hope that makes sense.

Chris

**Comment by markus101** [comment]
It may be possible for someone to use Sonarr's [API](https://github.com/Sonarr/Sonarr/wiki/API) to achieve that, but that's outside of something we'd take on. Closing as this isn't a feature request for Sonarr itself.
