### ISSUE TITLE
[REQ] Add new indexer - WtFnZb - Custom!

### ISSUE THREAD

**Issue by wtfnzb** [Sonarr/Sonarr#2883]
RSS/API is accessed via apache auth, so there would be needed some workaround for it.

**AUTHENTICATED** Accessing RSS via browser:
`https://USER:PASS@wtfnzb.pw/user/rss.php?code=PRIVATECODE&user=USER&cat=MP3`

RSS Sample output:
```
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>WtF[nZb]</title>
<link>https://wtfnzb.pw/</link>
<description>WtF[nZb]</description>
<language>en-us</language>
<copyright>NoCopyLeft</copyright>
<atom:link href="http://wtfnzb.pw/" rel="self" type="application/rss+xml" />
<item>
<title>Duke_Demont_-_Club_FG-SAT-12-29-2018-TALiON_[aae5e0591]</title>
<link>https://wtfnzb.pw/user/dl.php?nzb=Duke_Demont_-_Club_FG-SAT-12-29-2018-TALiON_[aae5e0591]&amp;date=/2018/12/29/&amp;code=PRIVATECODE&amp;user=USER</link>
<pubDate>December 29 2018, 11:26:35</pubDate>
</item>
</channel>
</rss>
```

**Comment by Taloth** [comment]
Sonarr does not support rss feeds for nzbs. and we have no plans for adding it. Supporting the newznab api specification is fairly easy to do for indexers, so that's definitely the preferred approach.
