### ISSUE TITLE
Downloading an episode without an absolute episode number causes errors on the series page and the activity queue

### ISSUE THREAD

**Issue by demize** [Sonarr/Sonarr#2884]
**Describe the bug**
Trying to view a specific series is giving me an error page at the moment. I believe it may have to do with a download in progress for that series: there is no absolute number for the episode on thetvdb, so I added it to Deluge manually and gave it the tv-sonarr tag. Sonarr recognizes the download in progress, however I can now not visit the series page. The activity queue similarly does not work, however it does not show an error. For reference, the series is set to anime and the anime naming scheme is `{Series.CleanTitle}.S{season:00}E{episode:00}.{absolute:000}.{Quality.Full}-{Release.Group}`.

**Logs**
The only applicable log is the stacktrace from the error:

    TypeError: item.episode is undefined
    
        in Connect(EpisodeStatusConnector)
        in td
        in TableRowCell
        in tr
        in TableRow
        in EpisodeRow
        in Connect(EpisodeRow)
        in tbody
        in TableBody
        in table
        in div
        in Scroller
        in Table
        in div
        in div
        in div
        in SeriesDetailsSeason
        in SeriesDetailsSeasonConnector
        in Connect(SeriesDetailsSeasonConnector)
        in div
        in div
        in div
        in div
        in div
        in Scrollbars
        in OverlayScroller
        in PageContentBody
        in Connect(PageContentBody)
        in div
        in DocumentTitle
        in SideEffect(DocumentTitle)
        in ErrorBoundary
        in PageContent
        in SeriesDetails
        in SeriesDetailsConnector
        in Connect(SeriesDetailsConnector)
        in SeriesDetailsPageConnector
        in Connect(SeriesDetailsPageConnector)
        in Route
        in Switch
        in Switch
        in AppRoutes
        in div
        in div
        in Page
        in PageConnector
        in Connect(PageConnector)
        in Route
        in withRouter(Connect(PageConnector))
        in Router
        in ConnectedRouter
        in Provider
        in DocumentTitle
        in SideEffect(DocumentTitle)
        in App

I reproduced the issue with both debug and trace logs enabled, however neither log mentions the error on the series page or the failure to load the activity queue. The only other relatively applicable log message is from the regular log, but it relates to searching for the episode:

    19-1-12 15:47:19.8|Error|ReleaseModule|Episode search failed: Can not search for ENDRO! - S01E01 it does not have an absolute episode number
    Parameter name: AbsoluteEpisodeNumber

    [v3.0.0.348] System.ArgumentOutOfRangeException: Can not search for ENDRO! - S01E01 it does not have an absolute episode number
    Parameter name: AbsoluteEpisodeNumber
       at NzbDrone.Core.IndexerSearch.NzbSearchService.SearchAnime(Series series, Episode episode, Boolean userInvokedSearch, Boolean interactiveSearch) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:line 208
       at NzbDrone.Core.IndexerSearch.NzbSearchService.EpisodeSearch(Episode episode, Boolean userInvokedSearch, Boolean interactiveSearch) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:line 72
       at NzbDrone.Core.IndexerSearch.NzbSearchService.EpisodeSearch(Int32 episodeId, Boolean userInvokedSearch, Boolean interactiveSearch) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:line 54
       at Sonarr.Api.V3.Indexers.ReleaseModule.GetEpisodeReleases(Int32 episodeId) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:line 99

**System Information**

 - Sonarr Version: [e.g. v3.0.0.348]
 - Operating System: Windows 10 Pro
 - .net Framework: 4.7.2

**Additional context**
This problem persists after the episode finishes downloading, and the episode does not import successfully; that appears to be a separate issue, however, as the debug log says it rejected the release due to invalid season or episode number. 

Removing the label from the torrent in Deluge and restarting Sonarr made the series page and activity queue accessible again.

**Comment by markus101** [comment]
Please use the forums or subreddit for v3 feedback.

This issue should be fixed in the next release.
