### ISSUE TITLE
WebUI EXTREMELY slow

### ISSUE THREAD

**Issue by coolcat97** [Sonarr/Sonarr#2886]
**Describe the bug**
Application hangs when clicking on settings page. Doesn't load settings.. Help?

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Ubuntu 18.04
 - mono Version: 5.18.0.225

**UI Bugs:**
 - OS: Mac OS
 - Browser: chrome, firefox
 - Version: 64.0.2

**Additional context**

**Comment by markus101** [comment]
> Sonarr Version: CURRENT

Current isn't a version, we want a specific version because there are multiple branches and inevitably people claim to be on the latest and they're not, it's also not helpful when issues are possibly fixed later and we want to verify which version originally had issues with.

So it it slow or it never loads at all? I'm not seeing any issues in Chrome or FF.
What do the logs say?
Anything errors in the dev console in Chrome?

The requested information should be filled out before submitting it.

**Comment by coolcat97** [comment]
Please tell me where to find this info.

**Comment by markus101** [comment]
The version is shown in the UI at the bottom and in System: Info.
The wiki has information on the log files.
Usually F12 for Dev console (Windows/Linux), beyond that there are probably guides out there.

**Comment by coolcat97** [comment]
Getting this error in my firefox:
`starting signalR SignalRBroadcaster.js:9
Loading failed for the <script> with source “http://piwik.sonarr.tv/piwik.js”. downloadclient:1:1
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More] downloadclient
SignalR: [connecting] SignalRBroadcaster.js:32
SignalR: [connected] SignalRBroadcaster.js:32
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: http://zcleaver.com:8989/vendor.js?h=fe6fSQ+2JFtQUk7ty3Rvvw
Source Map URL: vendor.map[Learn More]
sync received, re-fetching collection`

**Comment by coolcat97** [comment]
> The version is shown in the UI at the bottom and in System: Info.
> The wiki has information on the log files.
> Usually F12 for Dev console (Windows/Linux), beyond that there are probably guides out there.

No errors in sonarr logs, but I'm not sure how to enable logging to be debug logging?

**Comment by coolcat97** [comment]
Updated original post with extra info

**Comment by coolcat97** [comment]
When trying to load settings pages i get this in my web console:

`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ vendor.js:9785:21
starting application main.js:35:6
starting signalR main.js:198:10
Loading failed for the <script> with source “http://piwik.sonarr.tv/piwik.js”. status:1:1
SignalR: [connecting] main.js:221:14
SignalR: [connected] main.js:221:14
sync received, re-fetching collection vendor.js:25246:18
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: http://zcleaver.com:8989/vendor.js?h=fe6fSQ+2JFtQUk7ty3Rvvw
Source Map URL: vendor.map[Learn More]
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: http://zcleaver.com:8989/main.js?h=ntIxVVg+PaTCDplgIArp7w
Source Map URL: main.map[Learn More]
sync received, re-fetching collection`

**Comment by coolcat97** [comment]
Back end seems to be working just fine however.

**Comment by coolcat97** [comment]
Solved. I moved to docker and all issues have been resolved! Thank you for the help!

**Comment by 19wolf** [comment]
I have this issue as well. Have since moved to Docker and recreated everything and no change.
