### ISSUE TITLE
qBittorrent Authenticate URL changed in 4.1+ (Removed in 4.2)

### ISSUE THREAD

**Issue by zero77** [Sonarr/Sonarr#2887]
When trying to test the connection or send torrents to qBittorrent it doesn't work and instead gets a 404 error.
I think this maybe because qBittorrent nightly has dropped support for their old API.

Also, i am using the most up to date nightly vershon of Sonarr V3

> HTTP request failed: [404:NotFound] [POST] at [http://163.172.39.74:9000/login]

API v2 Documentations:
https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#general-information

**Comment by markus101** [comment]
Which version of qBittorrent?

**Comment by zero77** [comment]
@markus101 
I am using the newest nightly.

**Comment by markus101** [comment]
Does it specify an exact version? 4.1.x?

Based on the docs they changed the URL in 4.1, but that's been out since May; trying to understand if they've only changed it recently or it's been broken for that long.

**Comment by zero77** [comment]
It look like 3 days ago.

> Drop legacy WebAPI support PR: #10145
https://github.com/qbittorrent/qBittorrent/commits/master

I am using qBittorrent v4.2.0 alpha but, i think the next stable update will also  drop legacy API support.

**Comment by itsbebbo** [comment]
qBittorrent has included v2 of the API since version 4.x of qBittorrent. The old API has been left enabled in qBittorrent until a commit a few weeks ago. I can only assume that Sonarr / Radarr etc still use the v1 API hence why they broke on removal of the old API.

**Comment by itsbebbo** [comment]
As the Radarr code I updated for qBittorrent was identical (forked from) Sonarr I will PR this and update it.

**Comment by itsbebbo** [comment]
Pull Request added and code updated to deal with V2 of the API
