### ISSUE TITLE
Sonarr with Jackett

### ISSUE THREAD

**Issue by SteffanCline** [Sonarr/Sonarr#2888]
<deleted>

**Comment by SteffanCline** [comment]
DescriptIon:
I use Sonarr with Jackett on MacOS X. After a while Sonarr can no longer connect to Jackett even though Jackett is up. I have to quit Sonarr and restart it in order to talk to Jackett again. It seems that this really came noticeable when I started using Radarr with Sonarr both connecting to Jackett. Once Sonarr is restarted, I have to go and edit ever tracker (not NZBs), click test and save in order to be able to use them again. 
System Info:
Mac OS 10.12.6, Mono 5.16.0.220, Sonarr 2.0.0.5252, Jackett 0.10.611.0
Browser:
Chrome 71.0.3578.98

**Comment by markus101** [comment]
Sounds like https://github.com/Sonarr/Sonarr/issues/2802 otherwise please use the forums for support. We'll need debug logs of the issue.
