### ISSUE TITLE
Sonarr not deleting from Vuze

### ISSUE THREAD

**Issue by SteffanCline** [Sonarr/Sonarr#2889]
I cannot get Sonarr to delete from Vuze once it completes downloading a file. I've checked all options i can think of but just can't get it to work. Seems like a bug but I'm open to whatever suggestions come up. 

System Info:
Mac OS 10.12.6, Mono 5.16.0.220, Sonarr 2.0.0.5252, Jackett 0.10.611.0,
Vuze:
Java 1.8.0_121 (64 bit)
  Oracle Corporation
/Applications/.install4j/jre.bundle/Contents/Home/jre
SWT v4528, cocoa
Mac OS X v10.12.6, x86_64 (64 bit)
V5.7.6.0/4 az3
Browser:
Chrome 71.0.3578.98

**Comment by markus101** [comment]
Vuze has the same logic as Transmission, see: https://github.com/Sonarr/Sonarr/issues/2716

If you're still having issues please open a thread on the forums/subreddit.
