### ISSUE TITLE
Path too long, but it isn't

### ISSUE THREAD

**Issue by Kedryn** [Sonarr/Sonarr#2894]
**Describe the bug**
Getting error for path too long while it isn't
path: "G:\Il mio Drive\media\series\Fear The Walking Dead"
filename: "Fear the Walking Dead - S03E11 - Lo scambio.mkv"
error: "Couldn't rescan series [290853][Fear the Walking Dead]: Percorso e/o nome di file specificato troppo lungo. Il nome di file completo deve contenere meno di 260 caratteri, mentre il nome di directory deve contenere meno di 248 caratteri."

**Logs**
System.IO.PathTooLongException: Percorso e/o nome di file specificato troppo lungo. Il nome di file completo deve contenere meno di 260 caratteri, mentre il nome di directory deve contenere meno di 248 caratteri.
   in System.IO.PathHelper.GetFullPathName()
   in System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   in System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   in System.IO.Path.GetFullPathInternal(String path)
   in System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   in System.IO.DirectoryInfo..ctor(String path)
   in NzbDrone.Common.Extensions.PathExtensions.IsParentPath(String parentPath, String childPath) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Extensions\PathExtensions.cs:riga 93
   in NzbDrone.Common.Extensions.PathExtensions.GetRelativePath(String parentPath, String childPath) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Extensions\PathExtensions.cs:riga 60
   in NzbDrone.Core.MediaFiles.DiskScanService.<>c__DisplayClass16_0.<FilterFiles>b__0(String file) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:riga 166
   in System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   in System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   in System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   in System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   in NzbDrone.Core.MediaFiles.DiskScanService.FilterFiles(String basePath, IEnumerable`1 files) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:riga 166
   in NzbDrone.Core.MediaFiles.DiskScanService.Scan(Series series) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:riga 105
   in NzbDrone.Core.Tv.RefreshSeriesService.RescanSeries(Series series) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Tv\RefreshSeriesService.cs:riga 151

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Windows 10

**Comment by markus101** [comment]
Please upload the debug logs and link them here as requested.

**Comment by Kedryn** [comment]
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/2771182/sonarr.debug.txt)
here it is

**Comment by markus101** [comment]
> filename: "Fear the Walking Dead - S03E11 - Lo scambio.mkv"

That file isn't too long, but one of the files in `G:\Il mio Drive\media\series\Fear The Walking Dead` is too long, you'll need to find the file(s) and shorten or it/them.

`dir "G:\Il mio Drive\media\series\Fear The Walking Dead" /s /b /o:gn` will list all files in the subfolders.

v3 will have support for long files under Windows 10 (when enabled), but until then long paths need to be addressed.
