### ISSUE TITLE
Option to Include Articles When Sorting by Series Title

### ISSUE THREAD

**Issue by rafakob** [Sonarr/Sonarr#2896]
**Describe the problem**
Sorting shows by name on main page ignores "the" prefix, eg:

> - Better Call Saul
> - The Big Bang Theory
> - Black Mirror
> - True Detective

I understand that this is done on purpose and I found a use case for this but personally it is so annoying. System folders does not follow that pattern and when I browse my TV directory the order is different.

**Describe any solutions you think might work**
Just add a checkbox in settings to choose which version should be used. Or add additional sorting option on the list like `Tile (including "the")`. Output of that should be of course:

> - Better Call Saul
> - Black Mirror
> - The Big Bang Theory
> - True Detective

**Additional context**
Simple as that ;) Sorry if it was already discussed, it's really hard to find a proper query for that case.

**Comment by thezoggy** [comment]
a, an, and the -- these are articles and most apps filter those out when you sort by titles. 
while I can understand why you would want the option (other apps have it) but to be fair you could also just search in the search box and get to the series that way.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
