### ISSUE TITLE
File name not parsed correctly

### ISSUE THREAD

**Issue by hr1232** [Sonarr/Sonarr#2899]
**Describe the bug**
Sonarr arrives at very disturbing conclusions about the season number in some cases.

**Screenshots**
Not a screenshot, but just as good:
NZB name: Atlantis.2013.S02E12.PART2.1080p.BluRay.X264-FLHD
File name: flhd-atlantiss02e12-part2-1080p.mkv
Error: Season number 1 was unexpected considering the folder name

**System Information**
 - Sonarr Version: 2.0.0.5252
 - Operating System: Ubuntu 18.04.1
 - mono Version: 5.18.0.240
 - running in docker container linuxserver/radarr

**Additional context**
File was flagged for manual post-processing because the recognized season number in the file name didn't match the recognized season number in the nzb title. So far so good, but I don't understand where in the filename Sonarr finds season 1. Maybe it "thinks" s02 is part of the series title because of the missing dash in front of it but any well formed regex should be able to extract s02e12 correctly.

**Comment by markus101** [comment]
It’s likely the part 2. There is another GHI open for that issue already
