### ISSUE TITLE
Download stops working after episode 99

### ISSUE THREAD

**Issue by Growiel** [Sonarr/Sonarr#2901]
**Describe the bug**
A series ("Mom's Diary – My Ugly Duckling") that was downloading fine for almost a year suddenly stopped working about 6 months ago, I was looking other things so I didn't bother to find out why until today.

Episodes 1-99 are all working perfectly (i tried to delete a few to make sure) while episodes 100+ are all rejected with the reason `Unknown series`.

Nothing changes, the indexer correctly returns a valid episode but for some reason Sonarr rejects them.

**Screenshots**

NOTE: Don't mind the weird file sizes or the lack of peers/seeds, this comes from a Korean site that doesn't show seeds/peers and handles file sizes weirdly. This is definitely not the issue as it's been download fine since episode 50 and all my options are set correctly to make Sonarr download those files.

Episode 98:
The 4th release is rejected because of quality, but the other 3 are fine to be downloaded.
![image](https://user-images.githubusercontent.com/5228735/51445778-43bece00-1d09-11e9-9cb1-e3082108d765.png)

Episode 100:
Rejected because of "Unknown Series".
![image](https://user-images.githubusercontent.com/5228735/51445797-75d03000-1d09-11e9-837b-85490c43cb2a.png)

Epise 113 (latest to date):
Both releases are rejected because of "Unknown Series'. While they are both perfectly fine.
![image](https://user-images.githubusercontent.com/5228735/51445812-bb8cf880-1d09-11e9-9b97-c6f095460ff1.png)

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System:: Synology NAS
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.8.0.108

Any ideas what's happening ? It's also pretty frustrating that I can't just force Sonarr to force download this release anyways.

Thanks.

**Comment by markus101** [comment]
Likely the E100 + the date, but trace logs will tell us for sure, we’ll need those.

**Comment by Growiel** [comment]
I've done some more digging:

The question is: Why was Sonaar happy with E1-E99 without the S1 but not with E100+ ? 
The answer seems to be an issue with the regexp used to parse the title:

Episode 75 is parsed with:

`^(?<title>.+?)(?:\W+(?:(?:Part\W?|(?<!\d+\W+)e)(?<episode>\d{1,2}(?!\d+)))+)` which we can clearly see only allow 2 digits for the episode number `\d{1,2}` and thus won't match our E100.

Episode 100 is parsed with this one instead (probably because the first one failed):

`^(?<title>.+?)?\W*(?<airyear>\d{4})[-_. ]+(?<airmonth>[0-1][0-9])[-_. ]+(?<airday>[0-3][0-9])(?![-_. ]+[0-3][0-9])` and when this regex is applied, then the entire `Mom's Diary – My Ugly Duckling E103` is considered to be the series title instead.

Shouldn't the first regexp accept any number of digits for the episode numbers ? Or at the very least change it `\d{1,4}` since the chances of a series going over 9999 episodes are very slim.

Tracelogs for E75: https://pastebin.com/swXEuQK3
Tracelogs for E117: https://pastebin.com/ehL8qpny

Since I have some control on what is returned by the indexer (I have a custom PHP script in the middle to handle searching for shows in Korean since Sonarr doesn't handle it), I changed the returned title from "E100" to "S1E100" and it works now, since yet  another regexp is used that allows episodes to be up to 3 digits (but also forces them to be 2 digits long, so `S1E1` won't match but `S1E01` would).

Tracelogs for S1E117: https://pastebin.com/TQN5nSTw

Thanks.

**Comment by markus101** [comment]
> The question is: Why was Sonaar happy with E1-E99 but not with E100+ ?

Because the regex is strict to limit the number of false positives. Allowing an unlimited number or even 4 digits could cause issues.

**Comment by Growiel** [comment]
If changing the regexp is not an option then what is ? My episode names are completely valid... up until 99. That doesn't makes much sense.

I can use my script to tweak the name file, this does make the download start, but Sonarr is not processing the file when it's done downloading because the actual file name doesn't match the one that Sonarr has (since I modified it).

I can't ask the Korean tracker to change the way they format their episodes names'.

**Comment by markus101** [comment]
I'm not saying it isn't an option, I'm saying there is a reason why it was done the way it was, but it wouldn't be be unlimited or 4, 3 will suffice for now and we can add/re-evaluate if we need to support 1000+

**Comment by Taloth** [comment]
Growiel, could you provide us with a variety of -NEXT and other Korean show release titles? You can subsitute the title with a fake, we just want to know what variety in formats exist for korean shows.
We're ok with adjusting or adding a regex, but we have to keep it strict enough to avoid false positives. So having a few samples would be nice to add to our automated test suite.
It'd be nice to know if other Korean release groups (if any) follow the same format, and with some samples.
Tnx.

**Comment by Taloth** [comment]
Thank you. That last one will be more tricky because it doesn't contain -NEXT.

**Comment by ogirardkaliop** [comment]
For now i'd be fine with the one with -NEXT working fine, as it's really the vast majority of them.
