### ISSUE TITLE
[Feature Request] Add Snyk Git Repo Bot That Finds Known Vulnerabilities

### ISSUE THREAD

**Issue by rebekah65** [Sonarr/Sonarr#2906]
I think its worth adding support for Snyk, which is a git hub bot that finds and can fix known vulnerabilities in open-source dependencies used in this repository. 

Its easy to implement and with out any coding needed, it can be set to automaticly run for every PR or build.

Also, Snyk can be set to send alerts when vulnerabilities are found, or new upgrades or patchis to fix the vulnerabilities are available.

To implement:

>  - Go to the integrations page and click “Connect to GitHub”.
>  - You need to grant Snyk additional GitHub permissions. Choose to give access to public and private repositories, or grant access to public repositories only.
>  - Next, you’ll see a list of all GitHub repos across your GitHub organisations. Select the repos you would like to test with Snyk. If you have supported manifest files at the root, or one or two directories deep, Snyk will automatically recognise and create projects for them.
>  - Click on the button at the bottom of the page “Add selected repositories to Snyk”. The selected repos appear in your projects, and will be continuously checked for vulnerabilities.
>  - Clicking “View report” on any project lets you view & fix vulnerabilities right away. You’ll be able to review the suggested remediations, and create a PR with the required upgrades or patches.

Git:
https://github.com/snyk/snyk

Documents/Wiki:
https://snyk.io/docs/github/

![snyk_test_in_pr](https://user-images.githubusercontent.com/43880872/51545583-306f4800-1e5a-11e9-80ba-fc8f0a0c1d75.png)

**Comment by markus101** [comment]
This isn't really a feature request for Sonarr and we're already using Snyk though it's not using the PR bot.

Your approach of spamming a dozen or so repositories with the same message doesn't look good even if your intentions are, especially on ones that don't even have language support in Snyk/Dependabot.
