### ISSUE TITLE
Cannot add flemish show

### ISSUE THREAD

**Issue by HazCod** [Sonarr/Sonarr#2907]
**Describe the bug**
I cannot add the following show to Sonarr using the tvdb notation `tvdb:285808`.
Show: https://www.thetvdb.com/series/285808/seasons/all
This returns `There Was An Error Searching For 'Tvdb:285808'.`.

**System Information**
Version
2.0.0.5252
Mono Version
5.12.0.226
macOS 10.14.2

**Additional context**
The show is in flemish.

**Comment by markus101** [comment]
Please use the fourms/subreddit for support. It doesn't look like there is English metadata for that series, so it can't be added.
