### ISSUE TITLE
Change search pattern

### ISSUE THREAD

**Issue by Baanor** [Sonarr/Sonarr#2908]
Hi,

I've just encouter something similar as [https://github.com/Sonarr/Sonarr/issues/1556](url) 
I need in my tracker i to search with a pattern like "saison XX episode XX" and i think it would be great to have a way to change the pattern for the search via regex or something.

Anyway, the user with the issue above seems to have find a way, but don't give much help on how. 

Regards,

B

**Comment by markus101** [comment]
Jackett should be translating the request Sonarr sends (a pretty standard newznab request) to something that the indexer can understand, I'm not sure how to accomplish that within Jackett, but we don't have plans to change our search pattern or an option to do so.
