### ISSUE TITLE
Sonarr stripping `-` (dash) from search query

### ISSUE THREAD

**Issue by au5ton** [Sonarr/Sonarr#2910]
**Describe the bug**

I am trying to monitor this show: http://www.thetvdb.com/?tab=series&id=354198
the show name in Sonarr is `Kaguya-Sama: Love Is War`. The show name on the indexer (via Jackett) is `Kaguya-Sama: Love Is War`, as well as some aliases. However, the problem arises when Sonarr strips some characters from the search query.

Sonarr console:
```
[Info] NzbSearchService: Searching 3 indexers for [Kaguya-sama: Love is War : 01]
[Info] DownloadDecisionMaker: No results found
```
Jackett console:
```
01-22 22:40:32 Info Found 0 releases from AnimeBytes for: Kaguya sama wa Kokurasetai Tensai tachi no Renai Zunousen 01
01-22 22:40:34 Info Found 0 releases from AnimeBytes for: Kaguya sama wa Kokurasetai 01
01-22 22:40:36 Info Found 0 releases from AnimeBytes for: Kaguya sama Love is War 01
```

Notably the `-` is removed from the query, resulting in an empty search.

**System Information**
 - Sonarr Version: 2.0.0.5298
 - Operating System: Gentoo Linux 2.6
 - .net Framework: Mono 5.12.0.226

I'm more than willing to provide more information if necessary.

**Comment by au5ton** [comment]
I can confirm that the requests being sent to Jackett do not include the `-` and this is not a Jackett issue.

```
01-22 22:48:19 Info Request starting HTTP/1.1 GET http://127.0.0.1:34343/jackett/api/v2.
0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=redacted&offset=0&limit=100&q=Kaguya%20sama%20Love%20is%20War+01
```

Most notably: `&q=Kaguya%20sama`

**Comment by markus101** [comment]
Same issue as https://github.com/Sonarr/Sonarr/issues/1225
