### ISSUE TITLE
Sonarr can't find files of shows with foreign names if they have an English name

### ISSUE THREAD

**Issue by jpborjas** [Sonarr/Sonarr#2911]
**Describe the bug**
I'm trying to add a series in Spanish that has a name in Spanish in thetvdb 345990 "Luis Miguel: La Serie", but even though I enter Spanish as the Profile, the series will be added with its English name, and it can't be found in any search, even though it exists with its Spanish name.

**System Information**

 - Sonarr Version: 345990 Develop
 - Operating System: OS X Mojave
 - mono (macOS/Linux) Version: 4.6.2

**Comment by M0UL** [comment]
sonarr only support english tvdb metadata

**Comment by jpborjas** [comment]
I understand and thank you for your prompt response. Can this please be made into a feature or enhancement request? I've seen a number of similar requests entered in the past and closed, but this is very much an issue. It will be a greatly appreciated addition to an absolutely great product.

**Comment by markus101** [comment]
There is already an open issue for supporting other languages, it's not actively being worked on and we don't have any short term plans for it.

https://github.com/Sonarr/Sonarr/issues/269

**Comment by jpborjas** [comment]
That case is closed, hard for you guys to gauge the need out there. I hope that it could be moved up in the To Do list. Thanks again.
