### ISSUE TITLE
Partially downloaded series seem to overwrite existing files, regardless of size or completion

### ISSUE THREAD

**Issue by brandonscript** [Sonarr/Sonarr#2915]
**Describe the bug**
This is a bit hard to reproduce (I don’t want to lose files) but my best guess series of events:

1. Take a series, for fun, a pretend one we’ll call “Chocolate Pirates”
2. Download all but epsodes 1 and 4 of season 1 from a location, to say 1080p BluRay quality.
3. Search for a copy of season 1 elsewhere, discover that only a season box set is available as a torrent, and download it, using the appropriate sonarr-tv tag in Deluge (didn’t test this in any other client, but I assume the outcome will be the same)
4. (Note: torrents become active immediately when added) In order to save space and bandwidth and time, mark the episodes already downloaded as **do not download**, resulting in potentially some partial episodes in the ~50-~900MB range depending on how fast it is downloading, and how soon I get around to it.
5. When the box set is complete, Sonarr knows to import the series, and it appears to do a full series import - possibly it checks the quality of the first episode? Or just parses the title on the folder? But somehow, instead of doing what I’d expect and validate each episode, failing on the partials as **sample**, it automatically imports all the episodes whether completed or not.

I confirmed this was definitely the case, as I ended up having small partial episodes replace my good ones, even though the originals were complete, and a larger file size.

**System Information**

Sonarr Version 2.0.0.5301
Mono Version 5.8.0.108
Synology DSM 6.2.1-23824 Update 1

**Comment by Taloth** [comment]
Step 4 is something that Sonarr does not support. It grabbed the torrent and expects it to be downloaded in it's entirety. If you don't want that, then you'll have to download is separately, in another category, and perform the import manually via Wanted->Manual Import.
We have no plans to change this behavior since the default automated workflow works as intended.

**Comment by brandonscript** [comment]
Ahhh ok good to know. Cheers.
