### ISSUE TITLE
Automatic Task Schedules

### ISSUE THREAD

**Issue by Samuel98** [Sonarr/Sonarr#2916]
**Describe the problem**
While running both Sonarr and Plex on my Synology unit I have discovered that if both apps run intensive processes at the same time, the unit essentially freezes. 

**Describe any solutions you think might work**
As a result, would it be possible to allow for greater customisability in terms of the setting of execution times for the tasks under /system/tasks/. By this I mean instead of utilising intervals, instead allow for the option to use intervals or set times of the day which it can run tasks such as the "Refresh Series" for example runs once a day at 2AM or something similar. Currently, when I am using Plex I have to disable sonarr in case it runs during recording/watching.

Regards.

**Comment by markus101** [comment]
We do not have plans to customize when scheduled tasks run. Ultimately that could (would in my experience) lead to a spike in usage on the services Sonarr hits at specific windows in time and causes more issues for more people.
