### ISSUE TITLE
Alias support for title

### ISSUE THREAD

**Issue by Hakujou** [Sonarr/Sonarr#2917]
**Describe the problem**
Sometime, the alias available on TheTvDB are not matching region-specific releases, or when it's not written in the same way.

**Describe any solutions you think might work**
A field where we can enter multiple aliases that would be considered possible aliases for title of the release.

Here's an example: There's currently an on-air anime named "Go-Toubun no Hanayome".
It also have the following aliases on TheTvDB : "5-toubun no Hanayome" or "The Quintessential Quintuplets" (localized title).

But a lot of releases are tagged "Gotoubun no Hanayome", a name that is not present on TheTvDB and therefore not searched by Sonarr. It would be nice if we could add it manually to fix the search.

**Comment by markus101** [comment]
Aliases for series is covered in the FAQ. There is a maintained list for non-anime series and anime series use thexem.de
