### ISSUE TITLE
Add option to display original title and set it in the default path

### ISSUE THREAD

**Issue by Hakujou** [Sonarr/Sonarr#2918]
**Describe the problem**
When adding some content, especially animes, the localized english title is used by default.
It's also true for the default path : english title is added to the path set, not the original one.

**Describe any solutions you think might work**
Plex resolves this issue by letting user chose which language he prefers, for example "Japanese (Kanjis)", "Japanese (Romajis)", "English", etc... It's not perfect since, for example, I prefer to have all my shows with original titles (Mostly english for TV shows, mostly Japanese in romajis for animes).

It would be nice to get an option to have the original title by default in all content, and not the english one.

**Comment by markus101** [comment]
Sonarr only uses English metadata.

https://github.com/Sonarr/Sonarr/issues/269
