### ISSUE TITLE
Import failed, path does not exist or is not accessible by Sonarr

### ISSUE THREAD

**Issue by EosEtIris** [Sonarr/Sonarr#2920]
**Description of Bug**
Sonarr no longer imports downloaded files from the mapped path unless they are in folders. Only when I create a folder and move the downloaded file into it does the manual import work.

Doesn't import: /downloads/completed/tv/[HorribleSubs] Kaguya-sama wa Kokurasetai - 03 [1080p].mkv
Does import: /downloads/completed/tv/[HorribleSubs] Kaguya-sama wa Kokurasetai - 03 [1080p]/[HorribleSubs] Kaguya-sama wa Kokurasetai - 03 [1080p].mkv

The error is listed as coming from the DownloadedEpisodesImportService in the logs.
`Import failed, path does not exist or is not accessible by Sonarr: /downloads/completed/tv/[HorribleSubs] Kaguya-sama wa Kokurasetai - 03 [1080p].mkv`

**System Information**
Version: 2.0.0.5301
Mono Version: 5.18.0.240
Operating System: Debian 9.3
Browser: Vivaldi

**Additional context**
This was not a problem a couple of weeks ago. I have changed nothing in the system other that update the docker containers of Deluge, Sonarr and Radarr.

**Comment by markus101** [comment]
If that file exists then the permissions of the file do not allow Sonarr to see/access it to import it.

If you’re still having issues after verifying permissions please open a thread on the forums or subreddit for support.
