### ISSUE TITLE
Increase maximum download size limits

### ISSUE THREAD

**Issue by antigravity83** [Sonarr/Sonarr#2921]
**PROBLEM**
With 4K content becoming increasingly popular- I've found that the current size limits that are available to choose from are restrictive. 

For example, say I want to download files up to 20GB, Sonarr currently doesn't allow me to do this. 

The current maximum size selection is 12GB.  As a result, Sonarr says I have to limit my file sizes to 12GB (which for 4K isn't reasonable), or choose unlimited (which I also don't want- I don't want to download any greater than 20GB)

I'm aware there is an indexer file size limit- however this would render season pack downloads impossible if I placed a hard limit of 20GB there. 

**SOLUTION**
A simple solution would be to increase the selectable download limit in the Settings>Quality section

**Comment by Fish2** [comment]
you can open the database with and sqlite editor and change the values to higher

**Comment by antigravity83** [comment]
What fields need to be changed in the database?

Not really a user friendly solution though.

**Comment by thezoggy** [comment]
just move the slider all the way to the right for 'unlimited'

**Comment by markus101** [comment]
v3 will double the limit.
