### ISSUE TITLE
v3 -- quality definitions

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#2922]
* you cant move the quality sliders with the keyboard arrow keys like you can in v2.

* slider + box max limits are not in sync
the min/max megabyptes per min has a max limit of 200
if you move the slider to unlimited, it reports the max 200
if you enter in 200 or adjust it manually to 200 using the number controls, it sets the slider one tick under unlimited

**Comment by markus101** [comment]
Known already, tracking elsewhere as we are with all v3 issues for the time being.
