### ISSUE TITLE
rTorrent start download issues

### ISSUE THREAD

**Issue by SuissoNaBisso9** [Sonarr/Sonarr#2924]
**Describe the bug**
Everytime a new torrent is sent to rTorrent, this torrent si set to "stopped", download does not start automatically.

**Screenshots**
See attached
![rtorrent](https://user-images.githubusercontent.com/46867682/51896504-e8e24200-23ac-11e9-8eea-7abed4391772.PNG)
.

**System Information**

 - Sonarr Ver. 2.0.0.5301
 - Seedbox (Ultraseedbox) no root access

**Comment by markus101** [comment]
Please open a thread on the forums/subreddit for support, we'll need to see debug logs of the torrent being added. Also make sure you don't have Sonarr set to add them stopped.
