### ISSUE TITLE
Indexer test fails

### ISSUE THREAD

**Issue by springjools** [Sonarr/Sonarr#2925]
**Describe the bug**
"Unable to connect to indexer, check the log for more details"

**Logs**
Link to debug or trace log files.
https://pastebin.com/H6s7YYQY
**System Information**
Raspbian stretch, latest mono, jackett and sonarr.
 - Sonarr Version: [e.g. 2.0.0.1]
 - Operating System: [e.g. Windows 10]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**
All 7 indexers fail like this. They worked yesterday. Same problem keeps repeating frequently.

**Comment by markus101** [comment]
Please use the forums/subreddit for support.

Looks like Jackett isn't responding within the allotted time (90 seconds I believe).
