### ISSUE TITLE
Unable to find anime 

### ISSUE THREAD

**Issue by Battler624** [Sonarr/Sonarr#2926]
**Describe the bug**

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: [e.g. 2.0.0.1]
 - Operating System: [e.g. Windows 10]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
Please open a thread on the forums/subreddit for support.
