### ISSUE TITLE
Anime related issues.

### ISSUE THREAD

**Issue by Battler624** [Sonarr/Sonarr#2927]
**Describe the bug**
Using both manual and automatic search doesn't yield results.

**Screenshots**
https://photos.google.com/lr/photo/AFDEZfO8xQEYZuqeUGJq87YejsUbMbtcmeWuazST0v7sxczZAaKKwtvqMDI7SrPePCFhGPsRsGi6UNdQnzclIoCYOF6-QYRCjw

**Logs**
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/2819595/sonarr.txt)
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/2819593/sonarr.debug.txt)

**System Information**

 - Sonarr Version: 3.0.1.363
 - Operating System: Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**
The search format of sonarr is wrong it tries searching for "That Time I Got Reincarnated as a Slime" which is technically correct but only the english dub is using that format and the english dub is behind by several episodes and is unwanted it should instead use "Tensei shitara Slime Datta Ken" which should show up.

All other series that I added face this issue but some face more, for example Sword art online S3 while it can find the series and it can find episode it is rejected because of "unknown series" probably because the name of Sword Art Online S3 has Alicization as a subtitle

Another weird issue is Dororo, I have no idea why it adds (2019) to the search thus making no results appear.

**Comment by markus101** [comment]
Your last issue was closed because this is support related. Please open a thread in the proper location.
