### ISSUE TITLE
API DownloadedEpisodesScan not working as expected

### ISSUE THREAD

**Issue by llawwehttam** [Sonarr/Sonarr#2932]
For some time I have heavily used the API to manage importing of media.
I use torrents and have transmission on a remote seedbox.

When transmission finishes downloading it automatically runs a script I have written.
This determines whether Sonarr or Radarr requested the download then extracts and transfers all media to Sonarr or Radarr for import.
Each torrent is copied via rsync to a separate folder which is named after the release.

The script then uses the "downloadedepisodesscan" API command over a VPN tunnel to request an import and this used to work well. The media was moved to my media library, the import directory was cleaned up and emby was notified via API.

However, since upgrading to the latest version the import does not occur. This is still working as expected for Radarr.

I have gone through the Sonarr logs but do not see anything regarding the API query even though I get a successful response. I have deliberately not set up the path mappings as this causes Sonarr to copy the media instead of moving it and cleaning up the import directory.

Version: 2.0.0.5301
Mono Version: 3.10.0
OS: FreeBSD

My script has a debug mode for troubleshooting and this is some of the output as an example of how I have been using the API (DNS name and API key obfuscated):

INFO: API: Sending API Request to sonarr
DEBUG: Full request is: "curl -s http://mysonarrmachine:8989/api/command -X POST -d {"name":"downloadedepisodesscan","path":"/ImportDir/You.S01E05.UNCENSORED.iNTERNAL.1080p.WEB.x264-STRiFE[rarbg]","importMode":"Move","downloadClientID":"1744DC6F53C738FBD34C803F4491FDC36C338E8A"}
--header "X-Api-Key:w8afygl4auiogobal93947""
DEBUG: API Response: {
  "name": "DownloadedEpisodesScan",
  "body": {
    "sendUpdatesToClient": false,
    "sendUpdates": false,
    "path": "/ImportDir/You.S01E05.UNCENSORED.iNTERNAL.1080p.WEB.x264-STRiFE[rarbg]",
    "downloadClientId": "1744DC6F53C738FBD34C803F4491FDC36C338E8A",
    "importMode": "move",
    "updateScheduledTask": true,
    "completionMessage": "Completed",
    "name": "DownloadedEpisodesScan",
    "trigger": "manual"
  },
  "priority": "normal",
  "status": "queued",
  "queued": "2019-02-02T00:16:47.121561Z",
  "trigger": "manual",
  "state": "queued",
  "manual": true,
  "startedOn": "2019-02-02T00:16:47.121561Z",
  "sendUpdatesToClient": false,
  "updateScheduledTask": true,
  "id": 1253529
}
DEBUG: API Response State: queued
INFO: Success response from API
INFO: Script completed successfully. Exiting.

**Comment by markus101** [comment]
Sounds like https://github.com/Sonarr/Sonarr/issues/2919 if it's not we'll need those requested debug logs...

**Comment by llawwehttam** [comment]
I agree, looks like the same issue.
My bad, I completely missed that bug report.

I'll live with it for the time being until I can get v3 set up and working.
