### ISSUE TITLE
Russian Doll is being rejected because of language

### ISSUE THREAD

**Issue by IsThisThingStillOn** [Sonarr/Sonarr#2934]
Russian Doll is not being downloaded, because Sonarr assumes the language is Russian.

`19-2-1 16:20:28.3|Debug|AcceptableSizeSpecification|Item: Russian.Doll.S01E02.The.Great.Escape.720p.NF.WEB-DL.DDP5.1.x264-NTG, meets size constraints.
19-2-1 16:20:28.3|Debug|MaximumSizeSpecification|Maximum size is not set.
19-2-1 16:20:28.3|Debug|LanguageSpecification|Checking if report meets language requirements. Russian
19-2-1 16:20:28.3|Debug|LanguageSpecification|Report Language: Russian rejected because it is not wanted, wanted English`

**Comment by markus101** [comment]
There is an existing GHI for this problem already.

For the time being you’d need to create a new profile for this series that has Russian as the language.
