### ISSUE TITLE
Error with a specific anime UI rendering

### ISSUE THREAD

**Issue by zenjabba** [Sonarr/Sonarr#2937]
**Describe the bug**
When trying to load the series Bonobono (anime) the following error comes up with the error 

**Screenshots**
![screencapture-sonarr-zenjabba-series-bonobono-2019-02-04-20_26_36](https://user-images.githubusercontent.com/679864/52248329-e5265200-28bb-11e9-815d-31b8b1fdc848.png)

![screen shot 2019-02-04 at 8 27 42 pm](https://user-images.githubusercontent.com/679864/52248433-6bdb2f00-28bc-11e9-872a-a57177d43bc3.png)

![screen shot 2019-02-04 at 8 27 37 pm](https://user-images.githubusercontent.com/679864/52248437-785f8780-28bc-11e9-81f0-8992161d0724.png)

![image](https://user-images.githubusercontent.com/679864/52248449-87ded080-28bc-11e9-9857-7f8bc20cc2f8.png)
**System Information**

![screen shot 2019-02-04 at 8 27 42 pm](https://user-images.githubusercontent.com/679864/52248432-67167b00-28bc-11e9-952f-cfb3c0ad99f8.png)

 - Sonarr Version: [3.0.0.348]
 - Operating System: [Linux Ubntu 16.04.05 LTS]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [5.18.0.225]

**UI Bugs:**
 - OS: [Mac OSX]
 - Browser: [Chrome]
 - Version: [71.0.3578.98]

**Additional context**

**Comment by markus101** [comment]
Please use the forums/subreddit for v3 feedback. This issue has already been fixed in `phantom-develop`.

**Comment by zenjabba** [comment]
oops sorry, thanks for the update.
