### ISSUE TITLE
Sonarr can't move finished downloads

### ISSUE THREAD

**Issue by MrTehes** [Sonarr/Sonarr#2939]
Hi,

I work with this service : 
<img width="431" alt="capture d ecran 2019-02-06 a 00 13 26" src="https://user-images.githubusercontent.com/28986768/52310658-7244d600-29a4-11e9-8fbf-ade2e5ab752c.png">

So Sonarr works with the user mrtehes
All of my folders owners are mrtehes too : 
All current downloads are in this folder 
<img width="510" alt="capture d ecran 2019-02-06 a 00 12 02" src="https://user-images.githubusercontent.com/28986768/52310702-96a0b280-29a4-11e9-9e9e-71c8ca7e0d4f.png">

When they are done they go to this folder
<img width="468" alt="capture d ecran 2019-02-06 a 00 12 54" src="https://user-images.githubusercontent.com/28986768/52310708-9bfdfd00-29a4-11e9-96b2-6b45626c7a81.png">

But I always get this error in my logs : 

<img width="1683" alt="capture d ecran 2019-02-06 a 00 12 26" src="https://user-images.githubusercontent.com/28986768/52310750-c780e780-29a4-11e9-8e96-631af150ebb2.png">

Does anyone know why ?
Thanks for your time !

**Comment by markus101** [comment]
You're going to need to open a thread on the forums or subreddit for support.
