### ISSUE TITLE
Support for reverse numbering

### ISSUE THREAD

**Issue by hr1232** [Sonarr/Sonarr#2943]
**Describe the bug**
It's becoming more and more popular with several release groups to create reverse filenames. Sonarr fails to recognize the file correctly and therefor marks it for manual post-processing.

Here is an example:

nzb title: Arrow.S05E05.1080p.WEB-DL.DD5.1.H264-RARBG
filename: 50E50S.worrA.mkv
error message: episode number 50 unexpected

Please consider adding support for reverse numbering and naming schemes so these nzbs can be post-processed automatically.

Sonarr Version: 2.0.0.5252
Operating System: Docker on Ubuntu 18.04 (linuxserver/sonarr:176)

**Comment by Taloth** [comment]
We already support a few reverse title formats, but this is one where the filename is shortened and ends directly after the episode number. I fixed it for our v3 beta.
