### ISSUE TITLE
profile language is ignored

### ISSUE THREAD

**Issue by icf20** [Sonarr/Sonarr#2944]
how to reproduce this bug

1 create a profile where the language is set to spanish

2 add some content for example GoT 

3 click search and you will get nothing 

why? because the name is fully translated and sonarr search for the title in english

**Comment by markus101** [comment]
The language does not control which titles Sonarr searches for, Sonarr only knows about the English title and plus any "scene names"/aliases from thexem.de. In this case the aliases were using the English title for searching, I've corrected that now.

Keep in mind, if the release name doesn't contain any explicit language Sonarr will assume it to be English.

**Comment by icf20** [comment]
so this should be fixed with release v2.0.0.5302 ?

**Comment by markus101** [comment]
Yes it was a server side fix. If you’re still having issues open a thread on the forums/subreddit for support.
