### ISSUE TITLE
[V3] Interactive Manual Import Improvement

### ISSUE THREAD

**Issue by devbrian** [Sonarr/Sonarr#2946]
I am looking for some improvement to the interactive manual import.  I am mostly downloading season packs of older tv shows.  Sonarr isn't the best at decoding these because of the poor naming conventions they have (no fault of sonarr, the packs are poorly named).  But, I would like some improvements to the UI to allow for more quickly importing these packs.  

![image](https://user-images.githubusercontent.com/34463288/52507465-3df53380-2bb7-11e9-90b4-2cc8f44ade77.png)

This is the UI I am speaking of.  It would be nice for quality and language to have a select all functionality like the Series/Season, as usually all episodes would be the same quality/language.  If any are different, you could manually change after.  Then another possible suggestion, would be to try and generate episode numbers matching the information you have. So after you manually force the Series/Season,Quality, and Language, you can press a button for sonarr to try and generate the episode numbers each matches to.

**Comment by markus101** [comment]
Please use the forums or v3 sub reddit for v3 feedback at this time.

> This is the UI I am speaking of. It would be nice for quality and language to have a select all functionality like the Series/Season, as usually all episodes would be the same quality/language.

Should be possible, I'll have to look into it further.

> Then another possible suggestion, would be to try and generate episode numbers matching the information you have. So after you manually force the Series/Season,Quality, and Language, you can press a button for sonarr to try and generate the episode numbers each matches to.

https://github.com/Sonarr/Sonarr/issues/1893
