### ISSUE TITLE
Support episodes that have multiple files in release format but were dually aired?

### ISSUE THREAD

**Issue by douglas24** [Sonarr/Sonarr#2948]
A generic example of this being needed is when a show airs two episodes in a row for a special, but later when the DVD is released, the episodes are separate instances. A lot of older shows will have this because of episodes pairs that get aired in one night, but are really separate episodes.

A specific example of this is Terra Nova where both the first two episodes and the last two episodes were aired back-to-back and sonarr treats each pairing as a single episode. The studio DVD release has thirteen episodes as opposed to sonarr's/thetvdb's eleven.

Since there's no guarantee that thetvdb would be changed for older shows and lead to updated sonarr listings, can a feature be added to sonarr that will accept paired/multiple files and append something like Part 1/Part 2 to their end?

I know that some with reply and say why not just merge the two files to make one? Not every user has that capability.

**Comment by markus101** [comment]
We do not have plans to support split (A/B, part 1/2 , etc) files for a single episode.

**Comment by douglas24** [comment]
They're not single episodes. They're separate episodes aired back-to-back and occur in source material as separate episodes.

**Comment by Taloth** [comment]
As per https://forums.thetvdb.com/viewtopic.php?f=7&t=6308 FOX itself listed Genesis as a single episode and explicitly called Instinct episode 2, hence the 11 episodes on thetvdb. As such, from Sonarr's perspective it's a single episode.
It boils down between calling something an 'episode' vs 'airing' and we're not going to have that discussion here.
