### ISSUE TITLE
[phantom-develop] Custom Torznab indexer "TypeError: props.value is null"

### ISSUE THREAD

**Issue by telans** [Sonarr/Sonarr#2949]
**Describe the bug**
Trying to add a custom Torznab indexer gives "There was an error loading this item".

**Screenshots**
https://i.imgur.com/pEKg1e8.png

**Logs**
Trace: https://pastebin.com/raw/KzPJwUrE (Doesn't look like there's any good info.)
Error Output: https://pastebin.com/raw/V2RxyLix

**System Information**

 - Sonarr Version: [3.0.1.368]
 - Operating System: [Unraid/Docker 18.09.1 (4.19.20-Unraid)]
 - mono Version: [5.18.0.240]

**UI Bugs:**
 - OS: [Ubuntu 18.10]
 - Browser: [Firefox]
 - Version: [65]
 - Firefox Console Output: https://i.imgur.com/I5W6GE6.png

**Comment by ryester27** [comment]
I'm having a very similar issue with the Torznab indexer, although my error is "TypeError: Cannot read property 'toString' of null"

**Comment by M0UL** [comment]
anything v3 related should be posted on the [forums](https://forums.sonarr.tv/).
