### ISSUE TITLE
Why is Sonarr so bad at processing files?

### ISSUE THREAD

**Issue by ochompsky** [Sonarr/Sonarr#2952]
50%-75% of the time files just sit in my completed folder and are never renamed and moved.  I can't find any rhyme or reason to it.  The scene release is all the same for the seasons so it's not like it's an unknown scene. Radarr never has these issues. 

**Logs**
https://pastebin.com/S3UJJeDs

**System Information**

 - Sonarr Version: 2.0.0.5301
-  Sabnzbd: 2.3.7 
 - Operating System: Windows Server 2012 r2

**Comment by markus101** [comment]
Please open a thread on the forums or subreddit for support.
