### ISSUE TITLE
Search Bar Sub-titles (comma/colon) syntax

### ISSUE THREAD

**Issue by deathbybandaid** [Sonarr/Sonarr#2954]
Example, 

    Star Trek: Discovery

I think the search should allow me to type the title of the show without the colon (some shows use a comma), and it show up.

**Comment by markus101** [comment]
This is entirely too ambiguous, there are at least 3 searches that come to mind. You've also not followed a template for either a bug or a feature request...

1. Adding a new series, though the colon doesn't matter
2. Searching your library for an existing series, it's meant to be a simple lightweight title search
3. Searching for releases for a particular series, these are done without most special characters, for the good and the bad.

Assuming it's 2, but it's unlikely we're going to enhance that further as that becomes more expensive to perform and isn't meant to be an exhaustive search, searching for `star trek` will give you the result already.
