### ISSUE TITLE
v3/Phantom: Warnings: Unable to format audio channels using ‘AudioChannels’

### ISSUE THREAD

**Issue by rodalpho** [Sonarr/Sonarr#2959]
**Sonarr version (exact version)**: 3.0.0.348
**Mono version (if Sonarr is not running on Windows)**:    4.6.2
**OS**: Ubuntu 18.04
**Description of issue**: 
My logs have thousands of these warning messages:

```
Unable to format audio channels using 'AudioChannels', with a value of: '6'
```
or 
```
Unable to format audio channels using 'AudioChannels', with a value of: '2'
```

Sonarr appears to work fine, but the thousands of error messages make it very difficult to look through logs when I do have problems. I see there was another post about this on the forums in 2018 but it got no responses and the thread was closed. Is this a known issue, and if not, is there any way to eliminate the log spam?

**Comment by markus101** [comment]
Please use the forums/subreddit for v3 feedback.

It looks like if you have an old version of media info extracted from the file and Sonarr can't find a better option it falls back to that, which would happen if you have `Analyse video files` disabled.

I'll take a look and lowering this to another log level or removing it entirely.

**Comment by rodalpho** [comment]
Thank you, appreciate it.
