### ISSUE TITLE
Season packs not correctly searched for in single-season shows.

### ISSUE THREAD

**Issue by KsaRedFx** [Sonarr/Sonarr#2960]
**Describe the bug**
Season Packs for shows that never had anything beyond one season don't always include a number in the title, and are missed when Sonarr combs through episodes available for a show. 

This causes it to instead pick up episodes one-by-one instead of grabbing a single pack and importing it when you add a new show to Sonarr that matches this case.

It also causes the entire pack to be missing from interactive/manual search.

Making it impossible to use Sonarr for that show if you want a pack that is missed.

**System Information**

 - Sonarr Version: v2.0.0.5301 & 3.0.0.348
 - Operating System: Linux

**Comment by markus101** [comment]
Two issues:

1. You're never going to get search results unless the indexer returns them when searching for season 1, them actually being returned is extremely rare
2. If there are results Sonarr won't be able to parse them

Issue 2 might be fixable, but would likely be error prone depending how they are named, but given issue 1 it's not something we're going to see outside of RSS feeds and if it's returned via Interactive Search in v3 then you should be able to force Sonarr to grab it.

This isn't really a bug, it's by design/limited by the information in a release, it's not something we plan to address, at least at this time.

**Comment by KsaRedFx** [comment]
Would it not be possible to mostly solve this issue entirely, and simply, by adding the option to search for just the show title when running the Interactive Search in v3? You are already searching for season packs, and you're letting the user interactively pick the one they want to import. 

You also already know that there is only one season for that show, which would make it easy to line up episodes for that singular season. 

I know this isn't something that would work for multi-season scenarios, but it is fixable via interactive.

**Comment by markus101** [comment]
> adding the option to search for just the show title when running the Interactive Search

That's pretty much what https://github.com/Sonarr/Sonarr/issues/1128 is, except it wouldn't be an option, because Interactive search is for a specific thing, episode or season, not something else.

**Comment by KsaRedFx** [comment]
That issue does have a lot more complexity to it than just searching for the existing known name without an episode number attached when doing an interactive season search... But it would solve the problem. 

Would a PR solving this in a simpler way be accepted? 
In the case of an interactive search -> Search for just the title, in addition to each episode

```
Show Name
Show Name 01
```
instead of 
```
Show Name 01
Show Name 02
```

**Comment by markus101** [comment]
It's more complex, but it's not going to start dumping in unexpected results into searches/sub optimally searching. Proper indexers with real APIs these results should be returned regardless and we tend to not optimize for the other case.

@Taloth might have a different opinion, but I don't think this is something we want to include.

**Comment by Taloth** [comment]
We don't search by title in most cases anyway. And the problem isn't searching, it's the parser. It's not easy to match full series releases, and it is might introduce false positives for other show specials, or worse, movies with the same name.
See it like this: You're talking about changing Sonarr to perform an automated download of a single release which you can just as easily grab manually. It's entirely outside of Sonarr's main usecase and not worth the added complexity.

**Comment by KsaRedFx** [comment]
Well, I was specifically talking about the case where it's an interactive search. 
Leaving automated parsing as-is.

This is just to provide more results on the interactive search for complete seasons. 

You already do search by the name of the show, I'm not referring to episode titles at all. Nor am I suggesting any changes for interactive search for a single episode.
