### ISSUE TITLE
Replace `:` with `space-` instead of just `-`

### ISSUE THREAD

**Issue by mouzzampk2014** [Sonarr/Sonarr#2961]
Hi, 

I have folder name Law & Order- Criminal Intent but I want Sonarr v3 to name like that Law & Order - Criminal Intent. 

Space between -.

Thank you :)

**Comment by markus101** [comment]
This has always been the case, `:` is replaced by `-`, you could strip them out completely with `{Series CleanTitle}`, but we don't have plans to introduce an option to replace it with a space + dash.

You could also update the series path in Sonarr (and rename it on disk) to force it into your preferred naming for existing series.

**Comment by Taloth** [comment]
markus, it wouldn't be an entirely ridiculous idea to replace ": " with " - ".

**Comment by mouzzampk2014** [comment]
@markus101 Thank you so much but large number of series has ":" but Sonarr rename it to "A- Title". If we have Replace with Space Dash Space. That would be great :)

But thank you for "Sonarr (and rename it on disk) to force it into your preferred naming for existing series" :)

**Comment by markus101** [comment]
I agree it's not really ridiculous to do that. I do think there will be some group of people that wants it as it's done now because it's how things have been done, feels like damned if you do, damned if you don't.

**Comment by mouzzampk2014** [comment]
You guys are great :) make everything so simple :)

**Comment by Taloth** [comment]
markus, generically yes. but I think in the case of ": ", most ppl will either prefer it to be gone entirely (cleantitle) or replaced with " - ", the spaces are significant there. ":" should not be replaced with " -" obviously.
I'd love to hear if I'm overlooking an edge-case where the other replacement is preferred. I was kinda afraid of titles where : isn't really a separator, but I haven't found them on skyhook.

Some examples
`The X-Files (2016)`
`NASA's Secret Files - The X-1 to the X-48`
`CSI: Miami` -> `CSI - Miami` vs `CSI.-.Miami` vs `CSI-.Miami`
`Fear The Walking Dead : Flight 462` (already contains a space)
`The Next :15` (no trailing space, not really nice 'The Next -15' either, but not my problem)

**Comment by markus101** [comment]
I don't think you're over looking anything. Of the 5k+ series there might be a few outliers, but the majority make sense. `Fear The Walking Dead : Flight 462` would get cleaned up when we remove double spaces, `The Next :15` is a mess and I agree, not our problem.

Not opposed to making the change and adding some tests.

**Comment by mouzzampk2014** [comment]
Thank you :)
