### ISSUE TITLE
Show conflicting TVDB ID for unknown series

### ISSUE THREAD

**Issue by zang74** [Sonarr/Sonarr#2963]
**Describe the bug**
Series "Get Krack!N" not being identified when released with safe titles.

**Screenshots**
<img width="1016" alt="screen shot" src="https://user-images.githubusercontent.com/5435684/53093307-0d7d9580-34e5-11e9-8ffc-2ed9bdb9e019.png">

**Logs**
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/2884695/sonarr.debug.txt)

**System Information**

 - Sonarr Version: 2.0.0.5301
 - Operating System: Ubuntu 16.04.5 LTS (GNU/Linux 3.14.79-117 aarch64)
 - Mono Version: 5.18.0.240

**Additional context**
Show title ("Get Krack!N") contains an exclamation point, and most releases are title-safe and don't contain the punctuation.

**Comment by markus101** [comment]
The FAQ has an entry specifically for this case. In this instance an alias for that title exists and linkes to https://www.thetvdb.com/series/get-krackin but you have added https://www.thetvdb.com/series/get-krack-n which appears to be a duplicate given the TVDB ID is higher and is incomplete compared to the first one. You'll need to remove the series and re-add the correct series.

**Comment by Taloth** [comment]
markus, we should include the tvdbid in 'Unknown Series' if possible.

**Comment by markus101** [comment]
The TVDB ID of the series the alias is linked to? That shouldn't be too hard to tie in. We'd need to do another lookup like we do in `ParsingService.GetSeries` (`_sceneMappingService.FindTvdbId(parsedEpisodeInfo.SeriesTitle, parsedEpisodeInfo.ReleaseTitle);`) if the series is unknown. Something like `Unknown Series. This is an alias for another series: {tvdbId}`?

**Comment by Taloth** [comment]
yes, something like that. Mainly to manage the confusion for users somewhat. In v3 we could probably turn it into a clickable link to tvdb, but that's more work and not strictly necessary.
"{parsed title} matches the alias for another unlisted series {tvdbId}" (or "...for another series {tvdbId} ({title})" if the series exists in the user collection)

**Comment by markus101** [comment]
There is a separate rejection for a search that matches to the wrong series (one that was added), so we just need to cover the case of a series that has not been added.

**Comment by Bluebie** [comment]
Adding the "Get Krackin" tvdb listing directly doesn't make this work either, because release filenames are "Get.KrackN" and sonarr finds no matches on BTN when it looks for "Get Krackin" with the i. Adding Get Krack!N to sonarr gets closer since it does find the files on BTN but then rejects them as Unknown Series.

**Comment by markus101** [comment]
That alias was already added and BTN searches are based on ID, not titles (it may fall back to the title of thebID search fails, offhand I’m not sure.

If you’re having issues open a thread on the forums for support.

**Comment by Bluebie** [comment]
On which forums? Does sonarr has forums? As far as I can tell, the issue I'm having is sonarr rejecting the files it finds as "unknown series" because of the filename being Get.KrackN... BTN doesn't seem to have any trouble fetching the releases.

**Comment by markus101** [comment]
Yes, there are links from several places (in app, from the main site), https://forums.sonarr.tv
