### ISSUE TITLE
Frozen Shortly After Startup

### ISSUE THREAD

**Issue by anon3e5f** [Sonarr/Sonarr#2964]
**Describe the bug**

Shortly after startup (within 60 seconds) when all the tasks are executing, sonarr just locks up. It appears that all threads are frozen (the http service isn't responsive, no background tasks execute, etc.). There is no CPU usage, there is no disk activity or network activity. There are no logs after sonarr appears to freeze (in trace mode).

**System Information**

 - Sonarr Version: v2.0.0.5301
 - Operating System: Linux (Ubuntu)
 - Mono Version: 5.18.0.240

**Additional context**

I am a .Net developer by day, I would love to debug this - is there anyway to attach a debugger to a mono instance or at least get a mini-dump from the process? I can't easily move my sonarr installation to a Windows server due to the way I'm storing data.

**Comment by Taloth** [comment]
Support questions should generally be posted on our forums.

You can't really debug mono mini-dumps. I don't think I ever attached a managed debugger, iirc you have to use Xamarin Studio and build Sonarr from scratch on linux.
But it's possible to attach gdb native debugger and use some mono specific commands to get managed stack details. You'll have to consult the mono documentation for that.

It's better to first check the trace level log files and console log to see what the last action is and whether it freezes consistently at the same point.

Can you open a topic on our forums (https://forums.sonarr.tv/)?
