### ISSUE TITLE
Ep downloaded using indexer not enabled for automatic search

### ISSUE THREAD

**Issue by arpitgupta** [Sonarr/Sonarr#2966]
**Describe the bug**
I have 3 indexers configured. Only one of them is setup for automatic search. However download of an episode ended up using the result from an indexer that is only setup for interactive search. The only thing i can see different is one had a lot more seeders (1000+ vs 20) than the one that should have been used.

**Logs**
I did not have debug/trace logs enabled and cant find any info in them on when the particular release was selected.

**System Information**

Version
3.0.1.374
Package Version
3.0.1.374-ls16 by linuxserver.io
Mono Version
5.18.0.240

**Comment by markus101** [comment]
> The only thing i can see different is one had a lot more seeders (1000+ vs 20) than the one that should have been used.

If an indexer is setup for interactive search only it will not be used at all in an interactive search. You can see this in the debug logs when performing an automatic search for an episode.

I'm not able to reproduce this behaviour, my indexer that is setup for interactive search only is not used in an automatic search.

**Comment by arpitgupta** [comment]
Yes that's my understanding as well. I have enabled debug logs in case it happens again.

**Comment by arpitgupta** [comment]
Happened again for 2 episodes. Debug logs show that the indexer used is the indexer that is not enabled for automatic search. 

`DownloadDecisionMaker|Processing release 'EP' from 'indexer'`

I cant see anything else in the logs that sheds light as to why an indexer that is not enabled for automatic search was used.

I am assuming automatic search is the same when sonarr periodically checks for available content on its own as thats what is happening here. Also interesting it is its not happening for all series. Some series it continues to use the appropriate indexer and for some its not.

**Comment by markus101** [comment]
> I am assuming automatic search is the same when sonarr periodically checks for available content on its own as thats what is happening here.

No, that’s RSS Sync, which is not the same as Automatic Search, if you left RSS Sync enabled for that indexer then Sonarr will use it to automatically grab releases (as explained in the FAQ).

If you haven’t we’ll need to see the entire debug log showing the search/RSS sync showing Sonarr using that indexer when it shouldn’t be.

As of right now the redacted snippet that it processed some release from some indexer doesn’t tell us anything.

**Comment by arpitgupta** [comment]
Ah that was it then rss sync was enabled.
