### ISSUE TITLE
NZBCat searches has 'English' added to release name when audio language is specified

### ISSUE THREAD

**Issue by fragande** [Sonarr/Sonarr#2968]
**Describe the bug**
When searching for releases using NZBCat the text string 'English' is added after the release name *if* English audio language is specified under media info on the site.

**Logs**
Example for specified audio language (containing **English**):
`Processing release 'Series.S01E01.1080p.BluRay.x264-GROUP English' from 'NZBCat'`
Example for non specified audio language:
`Processing release 'Series.S01E01.1080p.BluRay.x264-GROUP' from 'NZBCat'`

**System Information**
 - Sonarr Version: 2.0.0.5301

**Additional context**
I'm not sure if the issue is on Sonarr's or NZBCat's end, but the text string is not present in the RSS flow. I also realize this could easily be solved by using renaming but I personally prefer to keep the original release name and this problem is carried over when using {Original Title}.

**Comment by markus101** [comment]
That's NZBCat, Sonarr logs the entire "title" from the item in the RSS feed, which they have added the language. They should either disable that functionality or have an option to disable it (Sonarr can send additional parameters), but Sonarr won't clean that up.

**Comment by fragande** [comment]
I see, thank you for the response and sorry for the inconvenience.
