### ISSUE TITLE
Unknown Series - ampersand/AND

### ISSUE THREAD

**Issue by jpfingstmann** [Sonarr/Sonarr#2971]
I found other bugs related to the indexers and matching with special characters, but in this case, the indexer is returning matches (manual), but the series lists & in the title and the scene has chosen to use "and".  Having it match with both & and "and", would help, I think.  The series in question is 317301 and only a single episode out of about 300 matched because it got named with "&amp".  The other manual matches that show have "and", so they show as unknown series.

If matching both naming options isn't realistic, perhaps a place to override the searched series name would be handy?

I'm on the fence if I'd call this a bug or a feature request, the search doesn't work (auto), but only because of how it's being matched by Sonarr.

Version
    2.0.0.5301
Mono Version
    5.18.0.240

Docker release - linuxserver/sonarr

If someone would like me to generate debug logs, I can do so.

**Comment by markus101** [comment]
> Having it match with both & and "and", would help, I think

This is already done.

This sounds more like an alias is need, which is covered in the FAQ, but it looks like there is an alias for `Desus and Mero`, but it's linked to `Desus & Mero (2019)` (356163). The fact that a different series is using the exact same title is the issue, I've updated the alias to not apply to the old episodes.

> If someone would like me to generate debug logs, I can do so.

Next time please include them, it gives a more complete picture and tells us what Sonarr is seeing.

**Comment by Taloth** [comment]
@markus101 Euh, there was actually an open question to tvdb to see what they're going to do with that series https://forums.thetvdb.com/viewtopic.php?f=41&t=54155
