### ISSUE TITLE
Proposal: Check if a Series is avalable to stream

### ISSUE THREAD

**Issue by rovingrambler** [Sonarr/Sonarr#2972]
All too often I download something, only to see it later in Hulu or Netflix

https://api.guidebox.com/ 
Has an API that would seem to do it.They are not the only api I've seen

It would be awesome if you could set in the options what streaming services you have access to.

Then when you add a series available in one of the services it would say: 

The series is available $HERE are you sure you want to add? 
or in addition/even better 
Seasons 1 and 2 are available $HERE etc. would you like to add the missing seasons, add all or cancel?

I know I'm not the first to request this or something similar. 
I'd be interested in helping, I work with API's all the time, though usually in Perl, PHP, or Bash not Mono.

Always willing to learn something new though

**Comment by markus101** [comment]
This has come up before, though previously where to source it was the biggest hurdle (https://github.com/Sonarr/Sonarr/issues/1674).

In particular I think this is a major hurdle: constantly changing landscape of streaming services shows being added/removed, people living in different regions or not having the different services and even people not caring whether or not they can stream it or not as this goes from a simple check this API into a pretty major feature that needs to be supported and maintained.

There are also going to be the people that don't want to ask whether something is available for streaming or not be bothered by the prompt. 

I can see the want for this, but I'm not sure the value of it is outweighed by size of it. Tagging it for reconsideration in the future, but we're not going implement and/or support this feature at this time.

**Comment by bakerboy448** [comment]
Someone on Reddit [just posted/announced 'Excludarr'](https://www.reddit.com/r/sonarr/comments/rn1wl2/excludarr_a_cli_tool_that_excludes_series_that/)

Disclaimer: Have not at all looked into it but seems promising
