### ISSUE TITLE
Replacement search fails for some failed downloads

### ISSUE THREAD

**Issue by hr1232** [Sonarr/Sonarr#2973]
**Describe the bug**
If Sonarr downloads a multi-episode release (or a season release) which is broken, the search for an alternative release fails. The error happens as follows:

1) Sonarr downloads a release (e.g. "Star Trek The Next Generation S07E25E26 720p HDTV x264 F1rebladerunner").
2) Sonarr lists the two contained episodes (Start Trek TNG S07E25 and S07E26) seperately in its queue while the download is in progress. Both queue entries are linked to the same download.
3a) (automatic post-processing) "Check For Finished Download" task finds the download is failed. Sonarr post-processes S07E25 first, removes it from the queue and blacklists the release. S07E26 stays in the queue.
3b) (manual post-processing) User removes and blacklists the release manually because it has been marked for manual post-processing (for whatever reasen). S07E26 stays in the queue.
4) In both cases, the blacklisting of the release starts a search for alternatives, which ignores all results because "release in queue is of equal or higher quality". This is because S07E26 is still listed in the queue, even though the download has already been removed.
5) After 1 minute, Sonarr starts the "Check For Finished Download" task again and silently removes S07E26 because the release has been removed from the downloader.
6) No alternative release will ever be searched automatically. Sonarr will needlesly wait around until the user searches manually or a new release comes up through RSS.

The bug happens always, if a release has been marked for manual post-processing and the user handles it manually. User can evade it by manually post-processing the second release before the "Check For Finished Download" task starts again. For multi-episode releases this might be a workaround, for season-releases its impossible to process 20-30 episodes before they are silently.

For releases that can be handled automatically it is highly dependend on the processing speed of the server and the number of releases the indexer returns for the first episode. If post-processing of the second episode can start before it is silently removed, an alternative release will be downloaded. Espiecially with season-releases of popular searies with many releases, Sonarr has no chance to get to the last episode before it is silently removed.

**Expected behaviour**
Remove all queue entries related to one release during the first post-processing (should be easy because the release name is the same). After that, the search for alternative releases for the first episode will not fail anymore because there are no zombie entries left in the queue.

**System Information**
 - Sonarr Version: 2.0.0.5301
 - Operating System: Linux 4.15.0-43 in Docker (linuxserver/sonarr)
 - mono Version: 5.18.0.240

**Comment by hr1232** [comment]
Also, current behaviour is an andue burdon on indexers, because Sonarr hits them for every episode that is contained in the release without downloading a new release. Especially with season-releases, often  containing 20-30 episodes, that is completely moronic and maybe even gets you banned for "failure in automation". The fact that Sonarr seams to prefer season-releases doen't really help.

**Comment by markus101** [comment]
> because Sonarr hits them for every episode that is contained in the release without downloading a new release.

Do the debug logs show a search for each individual episode? If a season pack fails it should do a search for the full season, not the episode that it detected as failed only.

**Comment by hr1232** [comment]
Sonarr acually searches for every entry in the queue list. As they are all listed in the queue, Sonarr seams to treat them seperately.

In case of season-releases Sonarr actually does a season-search each time (probably because the failed release was a season-release). All that season-search does is leave Sonarr with more releases to ignore because "release in queue is of equal or higher quality".

**Comment by hr1232** [comment]
The problem is not so much that Sonarr does a (needless) search for every episode listed in the queue. The main problem is that Sonarr won't remove all queue entries related to the failed release.

During post-processing (manual *and* automatic), Sonarr has to remove all queue entries with the same release name before starting the search for alternative releases. The loop which processes the queue will have to account for some entries not being around anymore by the time they are up for post-processing...
