### ISSUE TITLE
Custom filters for Queue and History

### ISSUE THREAD

**Issue by skidaddl3** [Sonarr/Sonarr#2974]
Problem:
Difficult to drill-down the specific episode you're trying to manipulate while it is active in Sonarr and Torrent downloader.

Solution:
SickRage has a column-based text-input-based (Edit: and other types of headers, be it an already filtered check box, or some kind of drop down selection) filter at the header of each column allowing you to almost instantly filter out many pages that you don't need to click or scroll through, to find something you're after.
![sickrage history filtering](https://user-images.githubusercontent.com/13662868/53461229-c9176a00-3a8f-11e9-88af-1954216684df.jpg)

Additional context:
If you have a few thousand items that Sonarr is managing, then each page view with a tabular style option such as Series, Activity and even Wanted pages, have a pagination function at the bottom. If this pagination function provides more than, say 3 pages, it becomes quite tedious and time consuming to drill-down to the item you are trying to find. If there were a text-based filter (possibly jQuery?) on the top of each tabular column of the said pages, or even just a separate search function related to the page, then that would make drilling-down much more effective.

![series filter](https://user-images.githubusercontent.com/13662868/53461378-49d66600-3a90-11e9-9592-a9dd739696cf.png)
![activity-queue filter](https://user-images.githubusercontent.com/13662868/53461386-4f33b080-3a90-11e9-9bdd-6d339bd063b0.png)
![activity-history filter](https://user-images.githubusercontent.com/13662868/53461392-51960a80-3a90-11e9-8012-3c385c54e95b.png)

**Comment by markus101** [comment]
To set some expectations, we're not going to have a text-based search box/filter at the top of each column.

In v3 we already have Custom Filters, which will need to be extended to support History/Queue, it's already available for series (or you can use the series search input always at the top of the page). There is also per series/season history available on the series page.

**Comment by skidaddl3** [comment]
To question your decision, "not going to have a text-based search box/filter at the top of each column", what is the underlying reason for this decision? How do you filter and find the download progress for one particular download, in the mentioned issue?

"There is also per series/season history available on the series page." How do you filter one particular episode in the series, when you have say 20 seasons, each with 20 episodes?

If I am misunderstanding how to use the software, can you please provide a link to a wiki on how to achieve this?

**Comment by markus101** [comment]
> To question your decision, "not going to have a text-based search box/filter at the top of each column", what is the underlying reason for this decision?

Not all the fields are text based, some are also aggregates and it doesn't make sense to try and force a particular solution on them.

> How do you filter and find the download progress for one particular download, in the mentioned issue?

You could do that from the calendar, the series page or anywhere else that episode status for it exists. You'd also be able to filter the queue with a custom filter.

> "There is also per series/season history available on the series page." How do you filter one particular episode in the series, when you have say 20 seasons, each with 20 episodes?

Go to the history for that episode.

**Comment by skidaddl3** [comment]
> Not all the fields are text based, some are also aggregates
I understand what you mean by this now: You mean for each column? So, for eg. the Episodes column on the Series page has a tuple of 271/271? Yes, it is difficult to asses the logic for the type of column header, I know. I'm sure someone could find some use cases, but I haven't found the need personally, yet.

My main idea was for the episode Title in terms of a text-based filter, however SickRage does provide drop-down lists in different instances of types of columns I think? Such as in the Mass Editing mode. It was quite powerful and intuitive.

> _How do you filter and find the download progress for one particular download..._
> You could do that from the calendar
No you can't. You can't filter in the calendar. Not that I can see?

> Go to the history for that episode.
I don't think you're understanding what is to be achieved?

**In my screenshots for example, on the Queue page, I would like to filter and show only the two rows with episode titles beginning with "St."
It's as simple as that.**

**Comment by MollyBe** [comment]
I would like to be able to use custom filters for the Calander. 

This request seems to align with the title of this post, but not the contents of the thread. Would you be okay with another post requesting custom filters for the calander only.

**Comment by markus101** [comment]
It definitely deserves it's own issue and we can evaluate whether it's something we'll add. We'll need to know what you expect to be able to filter by to properly evaluate.

**Comment by MollyBe** [comment]
With iCal Link you can already create custom iCal Feed URLs based on tags. My scope is limited in that I would like to be able to create a Filter listing for these URLs which I can switch between on Sonarr's Calendar page.

An alternative and more robust resolution would be to apply the same Custom Filters logic found in Sonarr's Series page. Ideally this would create custom iCal Feed URLs based on the Customer Filter. This would do much more than I need, but perhaps other people would find it useful. 

My goal is to be able to switch between a calendar which shows all series, and a calendar which only shows series by tag. Either solution would achieve this, which one would you recommend I create a enhancement request for?

**Comment by markus101** [comment]
In both cases you're asking for a way to filter the calendar, both options are that are a perfect fit for the `Describe any solutions you think might work` section in the template.

I'm going to remove all these off topic comments. In the future it's better to open a new issue than to discuss in an issue for a different request.

**Comment by skidaddl3** [comment]
> In both cases you're asking for a way to filter the calendar, both options are that are a perfect fit for the `Describe any solutions you think might work` section in the template.
> 
> I'm going to remove all these off topic comments. In the future it's better to open a new issue than to discuss in an issue for a different request.

Still related to the Filtering capability of a page, which is why MollyBe asked, as it is simply for a different page in Sonarr. It would be user-end possible jQuery funtionality.

**Comment by markus101** [comment]
Not really any different than the multiple issues for filtering on different pages already open and the problem with larger issues is they take longer to implement, have more moving parts and often don't cover everything asked for and get broken into smaller issues, ultimately it's why I said it deserves it's own issue.

> It would be user-end possible jQuery funtionality.

jQuery isn't a magic bullet, but I'm not sure what you mean.
