### ISSUE TITLE
Show Spiral is aka Engrenages won't download

### ISSUE THREAD

**Issue by dny238** [Sonarr/Sonarr#2977]
We need a name mapping for Spiral
https://www.imdb.com/title/tt0477507/

This is a french show, the files are posted online with the name Engrenages
but Sonarr is searching for the english name. 

https://www.nzb.su/search/Engrenages

**Comment by markus101** [comment]
Please use the forums for support though requesting aliases is covered in the FAQ.

**Comment by dny238** [comment]
it's in the sheet and it's still not working. Thoughts? 

3/6/2019 10:26:09 | 82152 | Engrenages | Spiral (2005) | It's a french show | Already added |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
