### ISSUE TITLE
Restore backup

### ISSUE THREAD

**Issue by synofan** [Sonarr/Sonarr#2980]
Restore on Synology Nas not usable for "normal" users.
you can make and download a backup, but you are not able to restore.

Make backup & restore solution similar to as is done in Lidar.

would vastly improve Backup&restore

**Comment by Taloth** [comment]
Who do you think Lidarr got it from? :smile: This is in Sonarr v3:

![image](https://user-images.githubusercontent.com/6383890/53986058-74be5b00-411d-11e9-9645-2584272d5db8.png)

**Comment by synofan** [comment]
Blush, sorry for the dunb question, but synology only has version 2.0.0.5301 - Jan 23 2019 
am i missing a clue?

**Comment by Taloth** [comment]
Only a little bit. Lidarr forked of Sonarr v3 alpha/beta release, not of the current v2 stable.

**Comment by synofan** [comment]
Hope the new version 3 migrates to package soon. Good job guys.
