### ISSUE TITLE
In alias list but, Spiral aka Engrenages won't download

### ISSUE THREAD

**Issue by dny238** [Sonarr/Sonarr#2981]
I made sure that the Alias's are in for Engrenages and it will won't download. 
What else should I try? 

in https://docs.google.com/spreadsheets/d/1PiIvzijwcdALKQWfGE3j4lwnOqmDkhB48fyQTArJpI4/edit#gid=0

you can see:

3/6/2019 10:26:09 | 82152 | Engrenages | Spiral (2005) | It's a french show | Already added |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by markus101** [comment]
As I said yesterday, please open a thread on the forums for support/questions. You'll need to include debug logs of the search.
