### ISSUE TITLE
Sonarr incorrectly reporting Existing File Meets Cutoff

### ISSUE THREAD

**Issue by SSS475** [Sonarr/Sonarr#2983]
**Describe the bug**
When doing a manual search for an upgrade to an already downloaded episode, sonarr incorrectly reports that the existing file meets the HDTV-1080p Cutoff when the file name says 720p and the badge in the episode list shows 720p.

**Screenshots**
Line in episode list
<img width="1072" alt="Screen Shot 2019-03-08 at 2 36 19 PM" src="https://user-images.githubusercontent.com/12175376/54051464-ed6df780-41af-11e9-99e4-c89bd6989a03.png">

Episode View showing filename
<img width="989" alt="Screen Shot 2019-03-08 at 2 39 48 PM" src="https://user-images.githubusercontent.com/12175376/54051589-2a39ee80-41b0-11e9-88cb-05034a42f9ac.png">

Configuration for the Series
<img width="781" alt="Screen Shot 2019-03-08 at 2 36 30 PM" src="https://user-images.githubusercontent.com/12175376/54051553-1098a700-41b0-11e9-80f1-1ebc06f49399.png">

Line in manual search window
<img width="985" alt="Screen Shot 2019-03-08 at 2 36 55 PM" src="https://user-images.githubusercontent.com/12175376/54051563-1a220f00-41b0-11e9-84b5-5c6c3ac0f242.png">

**Logs**

**System Information**

 - Sonarr Version: 2.0.0.5301
 - Operating System: Docker linuxserver/sonarr
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.18.0.240

**UI Bugs:**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 72.0.3626.121

**Additional context**

**Comment by Taloth** [comment]
Check your Quality Profile. WEB 720p is higher in the list than the specified Cutoff quality.

**Comment by SSS475** [comment]
WEBDL-720p is not in the HDTV-1080p Quality
<img width="976" alt="Screen Shot 2019-03-08 at 2 57 03 PM" src="https://user-images.githubusercontent.com/12175376/54052506-8b62c180-41b2-11e9-800d-2116e4cb28e3.png">

**Comment by Taloth** [comment]
Click on the profile.

**Comment by SSS475** [comment]
TIL, sorry for the interruption.
