### ISSUE TITLE
Sonarr doesn't start

### ISSUE THREAD

**Issue by modem7** [Sonarr/Sonarr#2985]
Hey guys,

I changed Sonarr settings on Fedora to try and get reverse proxy working (changed enable SSL + URL base as per https://github.com/Sonarr/Sonarr/wiki/Reverse-Proxy) and now it seems that Sonarr refuses to start on my server (which is odd in and of itself).

Getting the following:

>    sonarr.service - Sonarr Daemon
>    Loaded: loaded (/usr/lib/systemd/system/sonarr.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Sun 2019-03-10 12:00:31 GMT; 494ms ago
>   Process: 17320 ExecStart=/usr/bin/mono /var/hda/web-apps/sonarr/html/NzbDrone.exe -nobrowser -data /var/hda/web-apps/sonarr (code=exited, status=1/FAILURE)
>  Main PID: 17320 (code=exited, status=1/FAILURE)
> 
> Mar 10 12:00:28 localhost.localdomain systemd[1]: Started Sonarr Daemon.
> Mar 10 12:00:30 localhost.localdomain mono[17320]: Press enter to exit...
> Mar 10 12:00:31 localhost.localdomain systemd[1]: sonarr.service: Main process exited, code=exited, status=1/FAILURE
> Mar 10 12:00:31 localhost.localdomain systemd[1]: sonarr.service: Unit entered failed state.
> Mar 10 12:00:31 localhost.localdomain systemd[1]: sonarr.service: Failed with result 'exit-code'.

After uninstalling and reinstalling Sonarr on Fedora and restoring the backups, if I run "/usr/bin/mono /var/hda/web-apps/sonarr/html/NzbDrone.exe -nobrowser -data /var/hda/web-apps/sonarr" sonarr starts with the correct settings and database.

Further note: Nginx is loaded on a raspberry pi, so no direct changes apart from the above have been done to the Amahi installation.

If I can start it normally, but the service can't, I suspect it might be directory permissions issues?

> [~]$ ls -la /usr/bin/mono
> lrwxrwxrwx 1 root root 9 Aug  2  2016 /usr/bin/mono -> mono-sgen

> [~]$ ls -la /var/hda/web-apps/sonarr
> total 4
> drwxrwxr-x   4 apache users    30 Mar 10 00:18 .
> drwxr-xr-x. 13 apache apache  176 Mar 10 00:18 ..
> drwxrwxr-x   4 sonarr sonarr 4096 Mar 10 00:18 html
> drwxrwxr-x   2 apache users    41 Mar 10 00:18 logs

Any ideas on what I've cocked up?

**Comment by markus101** [comment]
Please use the forums or subreddit for support.

You’ll need to include Sonarr’s logs, the logs from systemd don’t show us anything useful.
