### ISSUE TITLE
Prioritization of sources

### ISSUE THREAD

**Issue by Goob00000** [Sonarr/Sonarr#2986]
Is your feature request related to a problem? Please describe.
Currently there are a lot of public trackers that post fakes or malware. Quite often the first release of an item is a fake on torrents in particular. NZBs seem to have a lower likelihood of this.

Describe the solution you'd like
More flexibility in the prioritization of NZBs for a release within one hour of posting or the ability to provide trust rankings to individual indexers. The ability to then search based on that. It would be nice also to hand pick specific indexers for the first wave of searches.

Describe alternatives you've considered
Manual searching. Post processing to spot fakes that would then delete the release.

Additional context
Better fake spotting would be really nice as that is becoming more and more common.

**Comment by markus101** [comment]
V3 supports prioritizing releases based on the release name and indexer prioritization is covered in https://github.com/Sonarr/Sonarr/issues/320
