### ISSUE TITLE
Add "test all indexers" button to settings > indexers

### ISSUE THREAD

**Issue by pyrrhichios** [Sonarr/Sonarr#2987]
Hi,

I'd like to suggest a 'test all indexers' button on the settings > indexers page. I quite often have all indexers fail due to a jackett/mono issue and it'd save me a lot of clicks! I appreciate this is sort of fixing the **wrong** problem, but it could well prove useful to others :)

I don't know if this would help to speed up implementation - but Lidarr (which I believe is a fork and modification of Sonarr for music?) has implemented such a feature (see screenshot) - so perhaps there is something usable to pull in from their codebase?

Thanks!

![image](https://user-images.githubusercontent.com/20819234/54122891-3adba600-43f6-11e9-87f5-8415364ad5f1.png)

**Comment by Thirrian** [comment]
Lidarr likely got it from sonarr v3 😁

**Comment by pyrrhichios** [comment]
Oh neat! Is it already in beta? I'm on master branch. Well. Splendid!

**Comment by markus101** [comment]
As with almost everything in Lidarr it came from v3.
