### ISSUE TITLE
Sonarr (phantom-develop 3.0.1.403) update causes sonarr to fail to start

### ISSUE THREAD

**Issue by pentaflake** [Sonarr/Sonarr#2989]
**Describe the bug**
Sonarr fails to start after upgrading to 3.0.1.403. Logs below include the error. Nothing changed between .400 and .403. Rolling the install back to a previous snapshot with .400 allows sonarr to start fine.

[v3.0.1.403] System.ArgumentException: The string can't be left empty, null or consist of only whitespaces.
Parameter name: path

A look at the commits between .400 and .403 look like this is related to the changes in https://github.com/Sonarr/Sonarr/commit/5062d740411e898b3caa1a9124a14c125589c324

**Logs**
https://pastebin.com/d6rShft4 - Error in log
https://pastebin.com/6kgsNc3h - RCFile

**System Information**
 - Sonarr Version: 3.0.1.403
 - Operating System: freebsd11.2
 - .net Framework (Windows) or mono (macOS/Linux) Version: mono 5.10.1.57

**Comment by Taloth** [comment]
Build failed intermittently this morning and I was already at work. It should be ok now in .405, can you confirm?

**Comment by pentaflake** [comment]
Sonarr now loads properly on .405 however with the new version it is no longer properly storing the process id in the pid file when starting the service. I rolled back to my snapshot with .400 and the pid is properly stored again on service start.

**Comment by Taloth** [comment]
I don't recall changing any of that. Did an error show up "Unable to write PID file"?

**Comment by pentaflake** [comment]
Scratch that the pid file was owned by root for some reason. I stopped sonarr and then removed the pid file  and it is storing it properly again on multiple service starts/stops/restarts. This looks to be resolved and working now.

**Comment by Taloth** [comment]
phew :smile: 

Not sure what would cause it to chown to root, maybe the plugin install script does that?
