### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by mccorkled** [Sonarr/Sonarr#2990]
I am not sure how to word this and I'm sure it will require some sort of 3rd party downloader, but it would be a cool feature to be able to download shows from Netflix. A ton of shows I would like are from Netflix and not on DVD therefore they are never grabbed while searching indexers.

Would this be possible? I think it would be a great feature.

**Comment by markus101** [comment]
We have no plans to add additional download protocols at this time.
