### ISSUE TITLE
Update failed (Windows, 3.0.1.363 to 3.0.1.406)

### ISSUE THREAD

**Issue by snailium** [Sonarr/Sonarr#2991]
Tried to update Sonarr in System -> Status, but failed.

Log shows

> 19-3-13 00:08:37.7|Info|InstallUpdateService|Deleting old update files
> 19-3-13 00:08:37.8|Info|InstallUpdateService|Downloading update 3.0.1.406
> 19-3-13 00:08:38.0|Info|InstallUpdateService|Verifying update package
> 19-3-13 00:08:38.4|Info|InstallUpdateService|Update package verified successfully
> 19-3-13 00:08:38.4|Info|InstallUpdateService|Extracting Update package
> 19-3-13 00:08:44.9|Info|InstallUpdateService|Update package extracted successfully
> 19-3-13 00:08:44.9|Info|BackupService|Starting Backup
> 19-3-13 00:08:46.3|Info|InstallUpdateService|Preparing client
> 19-3-13 00:08:46.4|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate
> 
> [v3.0.1.363] System.IO.IOException: Cannot create a file when that file already exists.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
>    at NzbDrone.Common.Disk.DiskProviderBase.MoveFolder(String source, String destination) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 235
>    at NzbDrone.Common.Disk.DiskTransferService.TransferFolder(String sourcePath, String targetPath, TransferMode mode, DiskTransferVerificationMode verificationMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 70
>    at NzbDrone.Common.Disk.DiskTransferService.TransferFolder(String sourcePath, String targetPath, TransferMode mode, Boolean verified) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 51
>    at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 138
>    at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 236
>    at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 95
>    at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
>    at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41
> 
> 

**System Information**

 - Sonarr Version: 3.0.1.363
 - Operating System: Windows Hyper-V Server 2016 (Windows Server Core)
 - .net Framework 4.6.01586

**Comment by markus101** [comment]
You'll need to update manually. https://github.com/Sonarr/Sonarr/commit/cf327077e9bde9f613f788589be8f74882583002
