### ISSUE TITLE
Import of Season fails if all files not present.

### ISSUE THREAD

**Issue by halcyonforever** [Sonarr/Sonarr#2992]
**Describe the bug**
This is really more of a SNAFU than a bug.  First let me explain the setup.
Remote seedbox > Syncthing > Fileshare > Sonarr

Things work great for single episodes.
If Sonarr grabs a season pack, download handling kicks in and grabs a file from the resulting folder.  But the whole season isn't downloaded yet from the seedbox to the fileshare.  So it only grabs one episode then quits.  The other episodes download shortly thereafter but never get imported.

Is there a way to have Sonarr re-check, wait, or other method to catch the remaining episodes?

**System Information**

 - Sonarr Version: 2.0.0.5301
 - Operating System: Server 2016 Core
 - .net Framework (Windows) or mono (macOS/Linux) Version: 4.7

**Comment by markus101** [comment]
Covered by https://github.com/Sonarr/Sonarr/issues/282
