### ISSUE TITLE
Option to delete torrent based files immediately

### ISSUE THREAD

**Issue by halcyonforever** [Sonarr/Sonarr#2993]
Can we add an option to delete the torrent based download files immediately after import.
My seedbox is located separate from my Sonarr and they are linked by a file copy process.  The file that Sonarr imports is not the same file used for seeding.  

So while the seed will continue and remove itself just fine, the downloaded copy just fills up the transfer file-share.

**Comment by markus101** [comment]
Covered by https://github.com/Sonarr/Sonarr/issues/282
