### ISSUE TITLE
API returns Health of indexers

### ISSUE THREAD

**Issue by scopa90** [Sonarr/Sonarr#2998]
Would it be possible to extend the API to include health of indexers or return this as part of the system-status call?

**Comment by markus101** [comment]
Health of everything is available from `api/health`, indexer specific issues are returned with the source of `IndexerRssCheck`, `IndexerSearchCheck` or `IndexerStatusCheck`, the first two are settings based, the 3rd is when an indexer has been disabled due to a failure.

**Comment by scopa90** [comment]
Thanks. Didn't see that in the documentation

**Comment by markus101** [comment]
A lot isn't documented, but anything you can do/see in the UI comes from the API. If it hasn't been documented then it's something we could change without notice, but that's been rare.
