### ISSUE TITLE
Serie Image not showing

### ISSUE THREAD

**Issue by fontes31** [Sonarr/Sonarr#3000]
Hi,
Iam running sonarr 2.0.0.5301 on windows server 2016, and some tvshows are not showing the image, i call it the "little poster" on the screen where is all the series. Example - Deutschland 83 the image is dark with sonarr simbol transparent and the name of the serie. Some are ok other, like Deutschland 83 not. How can i fix this, adding a image?

Thanks

**Comment by markus101** [comment]
Please use the forums or subreddit for questions/support.

Sonarr uses TheTVD for all metadata and images, you'll need to ensure there is an image there for the English metadata for Sonarr to use it.
