### ISSUE TITLE
WEB wrongly parsed as HDTV

### ISSUE THREAD

**Issue by tnascif** [Sonarr/Sonarr#3001]
**Screenshots**
![Sem título](https://user-images.githubusercontent.com/1376614/54484759-ddf34c00-484a-11e9-9a19-b5459a01cc46.jpg)

**Logs**
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/2974734/sonarr.debug.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/2974735/sonarr.trace.txt)

 - OS: Windows 10 Pro
 - Browser: Chrome
 - Sonarr Ver. 2.0.0.5301

**Comment by Taloth** [comment]
WEB is only recognized with scene-style release titles, such as the ones at the bottom of your screenshot. The Release title shown looks like a specific tracker custom title.

WEB-RIP is fixable.

@markus101 Do we want to address this?

**Comment by markus101** [comment]
I think so, unfortunately WEB is used over WEB-DL and despite the (likely) tracker specific name it shouldn't be too complex to support, just something like `\/\sWEB\s\/`?

**Comment by markus101** [comment]
This is fixed in v3.
