### ISSUE TITLE
ruTorrent category flexibility

### ISSUE THREAD

**Issue by zinefer** [Sonarr/Sonarr#3002]
**Describe the problem**
My ruTorrent setup applies it's own dynamic label to each incoming torrent. When Sonarr later polls for completed downloads it will _only_ match torrents that match the category even when the category is left blank.

**Describe any solutions you think might work**
The simplest solution would be to simply ignore categories if the category is left blank. Another solution could be setting categories to `*` means it will match any, but I believe more code will need to be changed to prevent `*` being sent as a category when adding the downloads.

**Additional context**
https://github.com/Sonarr/Sonarr/blob/master/src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs#L92

**Comment by markus101** [comment]
This is the behaviour we use for all clients, Sonarr expects to get a limited list of results back (preferably a label instead of no label) so it doesn't have to process every single release in the client, I don't think we want to change this.

I think Taloth asked on Discord, but didn't get a response, why are you applying dynamic labels?

**Comment by zinefer** [comment]
Seems like an unfortunate choice that basically removes the ability to use a feature of the client. I understand the default settings and wanting the current functionality but it entirely prevents someone from touching labels on a Sonarr managed torrent.

I'm not sure it's relevant but I have an on-torrent-added script that will match the torrent against existing labels and folders in the download root with the first part of a download name to categorize them. For example, I can create an ubuntu directory and drag and drop a bunch of versions of ubuntu and ruTorrent will apply the Ubuntu label and set their download directory to the right place.

I don't want to change any default functionality, I just want to be able to choose to make my Sonarr instance do more work for my own convenience. I just like to browse my torrents by category.

I can't imagine there's some sort of assumption that matters inside Sonarr that prevents it from operating on all of my torrents or a subset. If there is I am interested though, because I plan on simply removing this line of code and running a personal build if it comes to it.

I would also like to add, that with a category setting of blank, I was under the impression that I was disabling the filtering. When my torrents were simply getting ignored I thought I had things set up incorrectly. When I turned debugging on I was still confused because it was pulling torrents and it took me a bit longer to realize it was only reading the torrents that had no label. I think this could be made a bit more obvious to save noobs, or someone helping a noob some time. :)

**Comment by Taloth** [comment]
For most clients a blank category means 'all', so I suppose we could do it the same way for rtorrent too.

However, I'd like to note that having a separate category for Sonarr is recommended, because we don't want Sonarr to try import stuff that it shouldn't. Having a blank category means that Sonarr is evaluating all downloads, including movies, ubuntu iso torrents etc. 

> I'm not sure it's relevant but I have an on-torrent-added script that will match the torrent against existing labels and folders in the download root with the first part of a download name to categorize them.

So, if I get this correctly you basically put a release "my.series.s01e01" in a label 'my'?

**Comment by zinefer** [comment]
> For most clients a blank category means 'all', so I suppose we could do it the same way for rtorrent too.

This would work well for my use case.

> So, if I get this correctly you basically put a release "my.series.s01e01" in a label 'my'?

That's a reasonable simplification... I am using some regex to get as much of the name as possible and I am also allowing partial matches on folder names. [Here](https://gist.github.com/zinefer/811c41696488a762225cccfc4a25a8ff) is the script for the curious.

**Comment by Taloth** [comment]
Tbh, that looks like a gross misuse of the category system. It makes sense to use a script like that to override the output dir to have a base folder per series, but to give each series it's own category is a bit ugly imo.

Anyway, I'll make the change regarding the empty category field.
