### ISSUE TITLE
Adding “Last Two Seasons” option to Add Series' Monitor dropdown box. 

### ISSUE THREAD

**Issue by brunott** [Sonarr/Sonarr#3005]
Currently in the "Add Series" Section when opening the Dropdown box "Monitor" there are a few options including one for First Season and also for "Last Season".
It would be nice to have an option that offers "Last 2 Seasons" - I am more likely to select "Last 2 Seasons" than to select "Last Season" only. As it stands right now, I select "Last Season" and then go to the series and select to have the 2nd last one Monitored too.. 

It's a nice to have and I understand it'a a lazy request ;-)

**Comment by markus101** [comment]
Why not the last 3 seasons or last 4, etc.? Adding one means people are going to want other options, which we don’t plan to do.
