### ISSUE TITLE
System.ArgumentException: Uri didn't match expected pattern

### ISSUE THREAD

**Issue by imadunatic** [Sonarr/Sonarr#3008]
Trying to get a remote server of mine to phone home to Hydra running on my primary. It hits the API fine, triggers a search fine, but trying to retrieve an NZB appears to be an issue, for some reason, I think it's adding an extra comma after ".org" in my dynamic dns address. 

I've tried retyping the URL in Sonarr, changing my base URL in hydra to no avail. The fact that it communicates fine, but can't download anything leads me to believe I may still have something configged incorrectly. 

**Logs**
```
19-3-24 09:11:25.8|Trace|HttpClient|Res: [GET] http://MYSTATICIP.duckdns.org/nzbhydra/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=295936&rid=48961&tvmazeid=1869&season=3&ep=1: 200.OK (5713 ms)
19-3-24 09:11:25.8|Debug|NewznabRssParser|Failed to parse Url http://MYSTATICIP.duckdns.org,/nzbhydra/getnzb/api/-805799082968497784?apikey=(removed) ignoring.

[v2.0.0.5319] System.ArgumentException: Uri didn't match expected pattern: http://MYSTATICIP.duckdns.org,/nzbhydra/getnzb/api/-805799082968497784?apikey=(removed)   at NzbDrone.Common.Http.HttpUri.Parse() in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpUri.cs:line 83
   at NzbDrone.Core.Indexers.RssParser.ParseUrl(String value) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\RssParser.cs:line 336
```
**System Information**

 - Sonarr Version: [e.g. 2.0.0.5319]
 - Operating System: [Windows 10]
 - .net Framework (Windows) 4.7.2

Any ideas? I can access and download NZB's from my remote server fine, so it appears all is working well (in a browser), but Sonarr doesn't like it for some reason. I'm assuming it's still a config issue.

**Comment by Taloth** [comment]
I highly doubt Sonarr is adding the comma, it's more likely nzbhydra is doing that in it's api response.

Query the `http://MYSTATICIP.duckdns.org/nzbhydra/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=295936&rid=48961&tvmazeid=1869&season=3&ep=1` url and see for yourself.

**Comment by imadunatic** [comment]
Good lord... I had my server names separated by commas in my NGINX config, been fighting this for 3 weeks and never thought to look there. Thanks for the help Taloth!

**Comment by Taloth** [comment]
> for 3 weeks 

ouch... well, at least it's fixed now 😅
