### ISSUE TITLE
Remote Path Mappings moves to wrong folder

### ISSUE THREAD

**Issue by barneh** [Sonarr/Sonarr#3010]
**Describe the bug**
I have setup the **Remote Path Mappings** and it work as expected. But I have season folders with leading zero, like Season 01, Season 02 and so on. So when the move is done by the **Remote Path Mappings** functionality it creates a new folder, if the season is less than 9, since it probably looking for folder names like Season 1, Season 2 and so on, without leading zeros.

**Logs**
I can't find any logs about it.

**System Information**
 - Sonarr Version: 2.0.0.5319
 - Operating System: Windows 10 - 1809
 - .net Framework (Windows) 4.6

**Additional context**
No.

**Comment by markus101** [comment]
Remote path mappings control where Sonarr imports _from_ not when it can’t access the path reported by the download client, not where it imports to.

Sounds like your Season Folder Format is wrong (in media management settings).

If you still need assistance, please open a thread on the forums or subreddit.

**Comment by barneh** [comment]
> Sounds like your Season Folder Format is wrong (in media management settings).
You where completely right @markus101 , in my _Season Folder Format in media management settings._ was with one digit, thanks!
