### ISSUE TITLE
Error on sqlite3

### ISSUE THREAD

**Issue by ElRochito** [Sonarr/Sonarr#3011]
Hi,

When I launch `mono --debug /opt/NzbDrone/NzbDrone.exe` I've got an error on sqlite3. It tells that sqlite3 is missing but it's installed. I launch "apt-get install sqlite3" => `sqlite3 is already the newest version (3.11.0-1ubuntu1.1).`

I don't understand why, someone has the same problem ?

**Logs**
[v2.0.0.5319] System.TypeInitializationException: The type initializer for 'System.Data.SQLite.SQLiteFactory' threw an exception. ---> System.DllNotFoundException: sqlite3

**System Information**

 - Sonarr Version: v2.0.0.5319
 - Operating System: Ubuntu 16.04
 - Mono Version 5.18.1.0

**Comment by markus101** [comment]
The Sonarr debian package depends on `libsqlite3-0 (>= 3.7)` if you installed another way you'll need to make sure that's installed and available for Sonarr to find it. This doesn't appear to be a bug with Sonarr given the number of users running without issue, but if you need further assistance open a thread on the forums or subreddit.
