### ISSUE TITLE
Search box - search not filtering correctly

### ISSUE THREAD

**Issue by oziee** [Sonarr/Sonarr#3013]
**Describe the bug**
Using the search box and typing is beings to filter shows correctly but then as more letters are entered into the search box the filtering of shows begins to add show names that do not match the entered text

**Screenshots**
<img width="245" alt="Screen Shot 2019-03-26 at 3 49 31 pm" src="https://user-images.githubusercontent.com/1471841/54974166-cd776a00-4fde-11e9-8352-7d86391be046.png">

Typing in "bu" lists the only tv show that has that combination

however, continuing to type more letters, the filter list now includes tv show names that do not match the entered text "bull" now matches other shows as if the entered text was something like b*ll

<img width="231" alt="Screen Shot 2019-03-26 at 3 49 47 pm" src="https://user-images.githubusercontent.com/1471841/54974170-cfd9c400-4fde-11e9-9070-5145ea330311.png">

**System Information**
Version 3.0.1.411
Mono Version 5.18.0.240

**UI Bugs:**
macOS 10.14 - Safari 12.1

**Comment by markus101** [comment]
This is due to the fuzzy matching, I think we can sort the results in order of score instead of strictly alphabetically, but it's still going to return those results.
