### ISSUE TITLE
Preferred terms being wrongly applied

### ISSUE THREAD

**Issue by Codehhh** [Sonarr/Sonarr#3015]
**Describe the bug**
Sonarr downloaded the incorrect file because it had +20 score

**Screenshots**
![firefox_2019-03-27_13-31-34](https://user-images.githubusercontent.com/12055335/55098893-1f7ac700-5095-11e9-8930-b8f1218dd012.png)
![firefox_2019-03-27_13-32-42](https://user-images.githubusercontent.com/12055335/55098894-1f7ac700-5095-11e9-9670-41b482c70bcb.png)

**Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/3014576/sonarr.trace.txt)

**System Information**

 - Sonarr Version: 3.0.1.411
 - Operating System: Docker (3.0.1.411-ls44 by linuxserver.io)
 - Mono Version: 5.18.1.0

**Comment by Codehhh** [comment]
I believe this is due to `S01E01.1080p`. 
How should I structure my preferred words to avoid this?

**Comment by markus101** [comment]
Like must contain/must not contain the whole release name is considered, so not a bug.

You could use regex, something like `/\b7\.1\b/`

**Comment by Codehhh** [comment]
Thanks for the tip, didn't know I could use regex!
Ended up using `/7\.1(?!080)/`
