### ISSUE TITLE
Anime searching - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by IndyNaessens** [Sonarr/Sonarr#3016]
**Describe the bug**
When doing a search for episode 76 of Black Clover I get the following error
> Couldn't evaluate decision on "episode" Object reference not set to an instance of an object

**Screenshots**
[screenshot link](https://imgur.com/UXwDNX0)

**Logs**
[log link](https://gist.githubusercontent.com/IndyNaessens/fbd1c6a0c9d5f2d5e9938094d4c815a1/raw/d5313ece848ba517dfe36a046d6a57098417438b/log.txt)

**System Information**
 - Sonarr Version: 2.0.0.5322
 - Operating System: unraid (docker, linuxserver/sonarr)
 - Mono Version: 5.18.1.0

**Additional context**

The serie type is set to Anime, I'm just going to the season and episode overview and doing an automatic search, the issue also remains when doing a manual search as seen in the provided screenshot. 
**I only have this error when doing a search for ep 76**

**Comment by markus101** [comment]
Do you already have a file for that episode?

We'll need the requested debug logs to look at this further, the info level logs don't give us a full picture of what Sonarr is seeing.

**Comment by IndyNaessens** [comment]
Problem has been resolved after restarting my docker containers.
