### ISSUE TITLE
Error after removing a series

### ISSUE THREAD

**Issue by mlsmithjr** [Sonarr/Sonarr#3018]
## Bug Report

After deleting a series I consistently get an error screen indicating that something went wrong. I have pasted below the only output available. The series does get removed but the error screen persists.  BTW, love the cartoon monster running away with the hardware.  Cute.

### System Information/Logs

**Sonarr Version:**
3.0.1.411
Package Version  3.0.1.411-ls44 by linuxserver.io
**Operating System:**
linuxserver.io running on docker on ubuntu server.

**.net Framework (Windows) or mono (macOS/Linux) Version:**
    5.18.1.0

**Link to Log Files (debug or trace):**
Log files never updated during the issue

**Browser (for UI bugs):**
Firefox 66.0.1

### Additional Information

```
TypeError: e is undefined

    in Connect(r)
    in div
    in div
    in t
    in t
    in t
    in r
    in r
    in Connect(r)
    in div
    in div
    in div
    in div
    in t
    in r
    in r
    in Connect(r)
    in div
    in div
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in r
    in zD
    in r
    in r
    in Connect(r)
    in Unknown
    in t
    in t
    in r
    in Sre
    in div
    in div
    in r
    in r
    in Connect(r)
    in t
    in withRouter(Connect(r))
    in t
    in n
    in r
    in Connect(r)
    in t
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in e
```

**Comment by markus101** [comment]
Which page do you get the error on?

**Comment by mlsmithjr** [comment]
Any.  I've removed 3 in the last couple of weeks and it happened on all.
It's not high priority - like I mentioned the removal still works, just
have to click to another page to clear it.
I removed titles but not media.  If it helps the titles were: Sopranos,
Miami Vice, Fullmetal Alchemist

**Comment by markus101** [comment]
Are you removing them from the details page or the list of all series?

**Comment by mlsmithjr** [comment]
Series main listing, wrench icon, then Delete.

**Comment by markus101** [comment]
Are you still seeing this with `3.0.1.418`? I was able to reproduce this issue a few days ago once, but I haven't been able to since.

If you are opening the dev tools (F12 on Linux/Windows, unsure on Mac), should give some additional information about the issue (files/line numbers) that we can use to narrow down the issue.

**Comment by mlsmithjr** [comment]
I've deleted and recreated the container and am on 3.0.1.418. I see you're
using react. I have a little experience with it so when I get time I'll try
to debug it myself since this really isn't a priority bug fix (it still
removes the series).

Steps I use to recreate:

1. Add a series. I don't think it matters what.  But I use Miami Vice.
2. On series list, click tool icon and delete.  Don't select "remove media".
3. Error splash screen.

Console log of error:

TypeError: "e is
undefined"
react-dom.production.min.js:198:186
    a SeriesIndexItemConnector.js:47
    gF SeriesIndexItemConnector.js:46
    l index.js:70
    BM index.js:30
    u index.js:84
    BM index.js:30
    React 16
    Redux 2
    dM middleware.js:22
    c Redux
    handleSeries SignalRConnector.js:218
    handleMessage SignalRConnector.js:148
    onReceived SignalRConnector.js:320
    jQuery 14

    received

    dispatch

    handle

    trigger

    triggerHandler

    triggerReceived

    processMessages

    each

    processMessages

    success

    p

    fireWith

    H

    o

**Comment by markus101** [comment]
Looks like this selector fires before a parent one in reaction to the series being removed, I've added a guard against that and will look to see if we can make it a bit more streamlined in some refactoring.
