### ISSUE TITLE
Queued Seed / Finished 

### ISSUE THREAD

**Issue by martinkeat** [Sonarr/Sonarr#3020]
**Describe the problem**

This is not so much an issue but a qwerk I have noticed when using uTorrent with Sonarr. I don't know if the designers can create a feature whereby Sonarr can detect when a torrent is set to "Queued Seed". 

The reason I ask this is that I have noticed that if the maximum number of torrents and the maximum number of downloads in uTorrent are set to the same, Sonarr will not move the completed download from the download folder to the series folder. 

**“Maximum number of active torrents (upload or download) must be set higher than “Maximum number of active downloads”.**

The reason for this is that if they are set the same, all of your active “torrent” slots will be filled with active “downloads”. This means that all torrents which have finished downloading will be queued for seeding. 

If completed downloads are queued for seeding, the “When uTorrent reaches the seeding goal” will not work because the torrent will not seed. If the torrent never seeds then it can never achieve the goal and therefore will not be set to “stop” and this means that sonarr will not know it has completed and will not move it to the correct folder, rename etc.
The first thing I do when I setup uTorrent to work with sonarr is to run the “setup guide” via Options > “Setup Guide”.

This will set the appropriate number of “active torrent” slots for you. Then goto preferences > queuing and set the number of “active downloads” to two less than the number of “active torrents. Job done! 

**Describe any solutions you think might work**

If possible, a slight modification so that Sonarr classifies both "Finished" and "Queued Seed" as finished downloads, perhaps with a toggle option to switch it on / off, however it would be on by default. 

**Additional context**
![Capture](https://user-images.githubusercontent.com/8785775/55207004-733dfb00-51d0-11e9-9dad-d76d06e59de1.PNG)

**Comment by markus101** [comment]
That's going to depend entirely on what uTorrent reports to Sonarr, trace logs with a response from uTorrent when a torrent is in that state should tell us what we need to know.

**Comment by markus101** [comment]
Closing as we need more information and it has not been provided.
