### ISSUE TITLE
Add support for using "Unlabelled" as preferred rtorrent category

### ISSUE THREAD

**Issue by IAmNotAUser** [Sonarr/Sonarr#3021]
Following the most recent update, which brought in the changes from #3002, my Sonarr instance started attempting to re-import 2500+ episodes into my library (looks primarily like things I already had in my long-lived seedbox and manually added to my library before using Sonarr), including deleting existing files and then re-importing the same ones from the rTorrent client.

All of these torrents had been previously hidden in Sonarr. as they had labels configured, while Sonarr's configuration had the category empty. This meant the system was only picking up unlabelled torrents.

It looks like the ones it actively overwrote are where quality had been mislabelled (i.e. HDTV-720/WEBDL-720) on first Sonarr library build.

It now seems to have stopped auto-importing, but with 1915 episodes left in my "Activity" tab waiting for manual intervention. There's now no way to tell Sonarr to ignore these forever, without setting a category and having a massive (and personally, detrimental) change to current workflow.

On the Activity page, I have the options to manually add these leftover torrents (getting the error "Import Rejected: Has the same filesize as existing file" in the popup when doing so), or remove them from my download client. Neither of these options I want to do, seeing as the files I want in my library already are in there (and showing in Sonarr on the relevant show pages), or are things I want to continue seeding but not import.

Seeing as the original #3002 change was made to support a particular edge-case workflow, and while I can get behind the "no category configured should capture all torrents within the client" logic, please consider adding a way to handle other users's flows while making this change, without negatively impacting them immediately after they upgrade.

This is my current workflow, which I consider to probably be much more common than the auto-labelling one describe in the previous issue:

- Manually add torrent (downloaded for a friend, retrieved from an unsupported/unconfigured tracker, etc) to client with no auto-labelling
- Sonarr automatically sees this torrent on the Activity page
- Torrent completes
- Manual import on Sonarr
- User manually sets torrent label based on tracker (enabling features like seed count/seed size total in ruTorrent)
- Torrents labelled without importing, removed from Activity page and no longer visible

This creates a position where the "unlabelled" category is effectively treated as a transient inbox, with "folders" for each tracker to signify processed seeds (whether that be Sonarr processing, eBooks copied to a reader, music converted to preferred file type, etc).

To support this, please add a way to allow "unlabelled" torrents to be the specified category in the Sonarr configuration, in place of another label.

Alternatively, I guess if users are preferred to change their workflow for this case after the change to the following:

- Manually add TV torrent
- Manually set label to be that monitored in Sonarr
- Perform manual import from Activity page
- Manually reassign label on torrent to desired final label

There should be some additional protections/defences against what's happened to me with following the upgrade, with files mass re-importing automatically, if no label configuration was previously present. This could be an alert on the System page, and the post-processing scripts become blocked until the the user is forced to configure a category in their rTorrent configuration.

**System Information**

 - Version: 2.0.0.5322
- Mono Version: 5.18.0.240

Happy to provide further clarification, screenshots, logs, etc to describe any part of the preferred/now-enforced workflows better.

**Comment by Taloth** [comment]
It's unfortunate that the change affected you negatively, however I didn't change it to support that particular edge-case, but rather to line up the behavior with the other clients since those other download clients already did consider empty to be 'all', so it was essentially a bug.
It wasn't my intention to wreck someone's library and I'll endeavor to keep it in mind for the future when dealing with bugs like this.

The Sonarr UI consistently warns people to use a category, especially when the download client is used for other downloads than Sonarr's and it remains recommended.

I'll discuss it with the other developers to see if we wish to make any further changes to allow users to filter solely on uncategorized items.

**Comment by IAmNotAUser** [comment]
As I said before, I appreciate that it was changed to bring it into line with the other clients, I did feel a bit XKCD  ["breaks my workflow"](https://xkcd.com/1172/) as I wrote it up! But I wanted to provide more detailed reasoning behind my request, considering it was really to re-enable my "current" flow, now the bug-fix is in place.

And thank you for at least considering the proposed change; no real harm done with the library, except for giving some disks on my NAS a good thrashing and a potential extra step in my non-Sonarr-initiated downloading now.

**Comment by markus101** [comment]
Avoiding setting the label and using Manual Import from Wanted: Missing may work as well (though less-so for single file torrents if they aren't in folders).

An option to specifically only handle unlabled torrents seems unnecessary for most setups and one I think is better left out at this time.
