### ISSUE TITLE
Can't add tv series What We Do in the Shadows 

### ISSUE THREAD

**Issue by weekender23** [Sonarr/Sonarr#3023]
**Describe the bug**
Im trying to add series What We Do in the Shadows by press the button "Add What We Do in the Shadows" but nothing happens.  The window just sits there.
**Logs**
Link to debug or trace log files.

9-3-29 10:46:46.7|Trace|Http|Res: 1267 [GET] /api/v3/rootFolder: 200.OK (451 ms)
19-3-29 10:46:46.7|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (451 ms)
19-3-29 10:46:48.4|Trace|Http|Req: 1268 [GET] /api/v3/series/lookup?term=%20b
19-3-29 10:46:48.4|Trace|HttpClient|Req: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=b
19-3-29 10:46:48.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
19-3-29 10:46:48.8|Trace|Scheduler|Pending Tasks: 0
19-3-29 10:46:50.1|Trace|Http|Req: 1269 [GET] /api/v3/series/lookup?term=What%20We%20Do%20in%20the%20Shadows
19-3-29 10:46:50.1|Trace|HttpClient|Req: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=what%20we%20do%20in%20the%20shadows
19-3-29 10:46:50.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
19-3-29 10:46:50.3|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=b: 200.OK (1840 ms)
19-3-29 10:46:50.3|Trace|Http|Res: 1268 [GET] /api/v3/series/lookup?term=%20b: 200.OK (1875 ms)
19-3-29 10:46:50.3|Debug|Api|[GET] /api/v3/series/lookup?term=%20b: 200.OK (1875 ms)
19-3-29 10:46:50.3|Debug|AddApplicationVersionHeader|Unable to set version header
19-3-29 10:46:50.8|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=what%20we%20do%20in%20the%20shadows: 200.OK (750 ms)
19-3-29 10:46:50.8|Trace|Http|Res: 1269 [GET] /api/v3/series/lookup?term=What%20We%20Do%20in%20the%20Shadows: 200.OK (780 ms)
19-3-29 10:46:50.8|Debug|Api|[GET] /api/v3/series/lookup?term=What%20We%20Do%20in%20the%20Shadows: 200.OK (780 ms)
19-3-29 10:46:53.9|Trace|Http|Req: 1270 [POST] /api/v3/series
19-3-29 10:46:54.0|Trace|HttpClient|Req: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/358211
19-3-29 10:46:54.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
19-3-29 10:46:54.7|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/358211: 200.OK (752 ms)
19-3-29 10:46:55.1|Trace|SonarrErrorPipeline|Handling Exception
19-3-29 10:46:55.1|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Title slug 'what-we-do-in-the-shadows' is in use by series 'What We Do in the Shadows'
19-3-29 10:46:55.1|Trace|Http|Res: 1270 [POST] /api/v3/series: 400.BadRequest (1202 ms)
19-3-29 10:46:55.1|Debug|Api|[POST] /api/v3/series: 400.BadRequest (1202 ms)

**System Information**

 - Sonarr Version: 3.0.0.348
 - Operating System: MacOS 10.13.6
 - mono (macOS/Linux) Version: 5.12

**Comment by markus101** [comment]
>19-3-29 10:46:55.1|Warn|SonarrErrorPipeline|Invalid request Validation failed:
-- Title slug 'what-we-do-in-the-shadows' is in use by series 'What We Do in the Shadows'

You already have a series with that exact same name added, you'll need to remove it first.

> Sonarr Version: 3.0.0.348

Also update Sonarr, this error should be shown in the UI in recent versions.
