### ISSUE TITLE
Issue when finishing downloads

### ISSUE THREAD

**Issue by MrTyton** [Sonarr/Sonarr#3024]
**Describe the bug**
Activity Monitor is not determining that there is a file to import when the torrent was only one file.

The system has copied the files over, and sent out the notifications, but if you go to the episode and the history it doesn't say that it's moved and it's just stuck in the activity window.

**Screenshots**
https://imgur.com/rzG8zps

 - Sonarr Version: 2.0.0.5322
 - Operating System: Windows 10

**Comment by markus101** [comment]
Looks like Sonarr has the correct path for a single file download, but it can’t find it and tests it like a folder if it can’t find a file or a folder, probably a permissions issue.

**Comment by MrTyton** [comment]
It wasn't an issue until the update from a few days ago. I didn't change any config settings, not sure how a permissions issue could have happened.

**Comment by MrTyton** [comment]
Not only that, but I double checked the permissions of the account accessing the NAS where the data is being stored. All permissions are enabled, no errors are being thrown anywhere except for what was stated above. Also the fact that it is moving the file and sending the notification that it's completed download has to mean something.

**Comment by markus101** [comment]
First off, which torrent client?
You're also going to need to provide all the information that was requested when you opened this issue, including the debug logs of the import that lead to this or the next time it happens.
Does it happen for every download?

**Comment by MrTyton** [comment]
Qbittorrent 4.1.5

It's happened for every download so far.

It's also not updating the file that it's imported in properly, even if I remove it from the torrent client (in the series page)

https://imgur.com/ptITCng

The error doesn't make sense because it is copying them over... but I did more digging and I think that the issue was that there was an older version of sonarr running on a different machine that started up (really old restart script that I thought I'd purged) and was actually fucking with the permissions. So you were right, but I'll keep monitoring in case.

Have a good one.
