### ISSUE TITLE
Convert frontend from Backbone/Marionette to React?

### ISSUE THREAD

**Issue by 0xdevalias** [Sonarr/Sonarr#3025]
_Note: This is mostly for my curiosity/gauging of potential future interest rather than a request to 'drop everything and use React'._

I was looking around the codebase today to see if/where I would have to touch to implement a feature, and noticed it's currently using backbone. I'm guessing this was a legacy decision from when the app was first written, but i'm curious if there is strong will to stick with it in the long run, or if people would be open to moving to something like React?

As someone who hasn't worked much with backbone/marionette before, I found the way it lays out the files/binds between things/etc a lot harder to intrinsically follow than a framework like React. That said, I obviously eventually managed to find my way around it, and i'm sure once you're familiar with it it doesn't pose that much of an issue.

For my own curiosity, I wanted to see if it was possible to have a 'hybrid approach' (both React and Backbone together), so that things wouldn't necessarily have to be converted all at once. From a little googling, it sounds like it is possible:

* https://medium.com/@denisraslov/7-tips-for-migration-from-backbone-to-react-redux-a006a927c39e
* https://blog.isquaredsoftware.com/2017/07/react-redux-backbone-integration/
* https://www.engineyard.com/blog/integrating-react-with-backbone

So yeah, I guess just interested in your (read mostly as: any core devs/contributors) thoughts around this topic?

**Comment by markus101** [comment]
> I'm guessing this was a legacy decision from when the app was first written

Yeah, from 5 years ago.

> For my own curiosity, I wanted to see if it was possible to have a 'hybrid approach' (both React and Backbone together)

It definitely is, I've done it a couple times.

> So yeah, I guess just interested in your (read mostly as: any core devs/contributors) thoughts around this topic?

Definitely, it's already been done and part of the v3 alpha: https://github.com/Sonarr/Sonarr/tree/phantom-develop/frontend

**Comment by 0xdevalias** [comment]
Ah, so cool! Is there any rough timeline around the v3 stuff by chance?

**Comment by markus101** [comment]
We're not going to give an ETA when it'll completely replace v2, but it's in alpha as I mentioned and you found the announcement for it.
