### ISSUE TITLE
Not grabbing high scoring releases

### ISSUE THREAD

**Issue by Chudz** [Sonarr/Sonarr#3028]
**Describe the bug**
I have a score of 100 added to keywords DUAL, MULTI AUDIO, MULTI.AUDIO however the automatic search is not checking this and just downloading anything.

**Screenshots**
![Release Profile](https://user-images.githubusercontent.com/1077083/55511109-b0ced800-5657-11e9-9583-b715e329243c.JPG)
![Quality Profile](https://user-images.githubusercontent.com/1077083/55511108-b0364180-5657-11e9-98d1-b596c06ffb0f.JPG)
![Interactive Search](https://user-images.githubusercontent.com/1077083/55511107-b0364180-5657-11e9-9396-91ff76b9880b.JPG)
![History for Automatic Search](https://user-images.githubusercontent.com/1077083/55511106-b0364180-5657-11e9-8a4d-02e25bba16b9.JPG)

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/3040687/sonarr.txt)

**System Information**
 - Sonarr Version: 3.0.0.348
 - Operating System: Ubuntu 19.04 LTS Using Docker (lsiodev/sonarr-preview)

**Comment by markus101** [comment]
This is fixed in a new version of Sonarr; you need to update. See https://sonarr.tv for the latest build information.

Next time please include the debug logs, not info logs.
