### ISSUE TITLE
quality meet but still obtained lower quality

### ISSUE THREAD

**Issue by intertan** [Sonarr/Sonarr#3029]
Had something happen in the beta
Had a season in a series with REMUX as my cutoff, this season was a remux and showed it in sonarr.
It was still monitored and sonarr found a 1080p quality of the season, sent it to get downloaded then processed removing the remux quality.

**Comment by markus101** [comment]
Without all the requested information (especially the debug logs to see what Sonarr saw at that time) we're unable to investigate this further.

**Comment by markus101** [comment]
Will reopen if there is something we can take action on.
