### ISSUE TITLE
Upgrading triggers "on download" notification

### ISSUE THREAD

**Issue by SturmB** [Sonarr/Sonarr#3030]
**Describe the bug**
Perhaps this isn't a "bug," but it definitely seems like one and is certainly an annoyance. If it should be labeled as a "feature request," please feel free to move it. Or just let me know if **I** need to do so.

My Discord notification settings (under Connections) are set so that they should only notify me when a new episode of a show is grabbed and then fully downloaded. However, as my second screenshot shows, it also notifies me when it grabs an upgrade to the episode. Now I agree that upgrading an episode is _technically_ an additional grab/download; however, this goes against expected behavior if I have the "on upgrade" option set to "No".

I could understand if I have both "on download" _and_ "on upgrade" selected, but it seems that if I have "on upgrade" deselected, I should only receive the first notification for a given episode.

**Screenshots**
Current settings:
![Screen Shot 2019-04-04 at 3 53 26 PM](https://user-images.githubusercontent.com/6216224/55584249-d0b2da00-56f1-11e9-850d-574856030689.png)

Too many notifications:
![Screen Shot 2019-04-04 at 3 49 49 PM](https://user-images.githubusercontent.com/6216224/55584060-597d4600-56f1-11e9-9656-0ddc2d35c8d8.png)

**Logs**
Not necessary in this case?

**System Information**

 - Sonarr Version: 2.0.0.5319
 - Operating System: Synology DSM / Linux
 - .net Framework (Windows) or mono (macOS/Linux) Version: N/A

**Additional context**
This Sonarr instance is running inside of a Docker container on my Synology NAS. Not sure if there's any other context that needs to be given.

**Comment by markus101** [comment]
On Grab is sent whenever an episode is grabbed, whether it's the first grab for that episode or the tenth, it doesn't care about there being a previous episode because that's not the intent.

`On Upgrade` isn't a conditional that applies to other event types, same as `On Rename` doesn't block `On Download` from triggering if the file was/wasn't renamed.

We do not have plans to have an `On Upgrade Grab` event, but it could be possible with a custom script or webhook that talks to Sonarr's API to determine more information.

**Comment by SturmB** [comment]
I'm sorry if I sound like a complete idiot here, but I have to ask: what's the purpose of an `On Upgrade` trigger if it just more or less echoes the `On Download` trigger when it's getting a better-quality version of the same episode?

**Comment by markus101** [comment]
Controlling being alerted when an episode is available for the first time as opposed to any time an episode is imported is probably the primary reason. With custom scripts it could do extra steps for a new file being downloaded that it doesn't need to do when an upgrade is downloaded, say write metadata to a special file.

**Comment by SturmB** [comment]
Okay, I'm definitely an idiot, because I'm having trouble parsing your answer and how it relates to my question. It sounds like you're explaining why `On Download` exists, whereas I was questioning why `On Upgrade` exists.

I was going to take a different tack and ask, is there any way to have a Connection **not** trigger when an episode is being upgraded, but **without** disabling the `On Download` trigger as well?…

However, as I was typing, I realized that's not the problem. It's when an episode upgrade is **grabbed** that I get the duplicated notification. This can even be seen in the second screenshot of my original post. I've confirmed this with two other shows that had episodes upgraded.

Thus, my solution, for now, is to just disable the `On Grab` trigger for the Connection. This way, our Discord channel will be notified on new episodes when they are finished downloading/imported, but not on the initial grab and, most importantly, not when an episode is upgraded.

I'll watch over the next week and see if, indeed, this is a solution I can live with. Admittedly, this still leaves the question of why `On Grab` still triggers when an episode is upgraded and `On Upgrade` is disabled. However, my discovery that this problem is actually with `On Grab` rather than `On Download` makes it less important for me to get resolved.

**Comment by markus101** [comment]
On Upgrade is a separate type of notification sent only when an episode is downloaded _and_ is an upgrade for an existing file, it’s not a condition that is used for other event types.

On Grab - sent when anything is sent to your download client, whether it’s and upgrade of not

On Download - Sent when an episode file is imported and there wasn’t an existing file

On Upgrade - Sent when an upgrade is imported

On Rename - Sent when a series has one or more filed renamed
