### ISSUE TITLE
Add support for Gotify notifications

### ISSUE THREAD

**Issue by stephanrenggli** [Sonarr/Sonarr#3033]
**Describe the problem**

Receive notifications via Gotify, the same as you would with Pushover or Pushbullet.

**Additional context**

Gotify seems similar to Pushover, though you are able to host it yourself.
Gotify: https://gotify.net/

**Comment by stephanrenggli** [comment]
I implemented this and it seems to work.

PR: https://github.com/Sonarr/Sonarr/pull/3034

**Comment by evertonstz** [comment]
Came here to ask for this support too!

**Comment by billysyrett** [comment]
@markus101 Can we get the Gotify notifications built by @stephanrenggli merged into a release?

**Comment by stephanrenggli** [comment]
Gotify notifications have been in sonarr for around a year now. You can set it up by going to `Settings > Connect > Add > Gotify`
![image](https://user-images.githubusercontent.com/5135902/79338222-35b92680-7f27-11ea-86c8-a5ecbf5ca4d1.png)

**Comment by Taloth** [comment]
Only in v3 beta, hence @billysyrett confusion. Sonarr v2 receives no new features.

**Comment by billysyrett** [comment]
Ah that makes sense. Cheers, I've switched to v3 now.
