### ISSUE TITLE
NZBGet transfer and delete.

### ISSUE THREAD

**Issue by martinkeat** [Sonarr/Sonarr#3040]
**Describe the bug**
I'm using NZB Get as a news source. It is sending the correct instructions from sonarr to NZBGet and commences the download. However the files are not being transferred and deleted from the NZBGet download folder to the \TV folder I have setup for all of the TV series. It works fine with utorrent but it just isn't doing it with NZB Get. 

Downloads in the activity screen are showing with a gold icon "downloaded" and S
"Download wasn't grabbed by Sonarr and not in a category, Skipping."

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: [e.g. 2.0.0.1]
 - Operating System: Windows 10
 - .net Framework V4

**Comment by markus101** [comment]
Please open a thread on the forums with the requested information and debug logs of the grab event. Also check the history in Sonarr to ensure the grabbed episode was added to Sonarr's history.
