### ISSUE TITLE
Windows service no longer works after update to 3.0.1.435

### ISSUE THREAD

**Issue by skywayskase** [Sonarr/Sonarr#3041]
**Describe the bug**
This morning I noticed that Sonarr wasn't running anymore. I went to start the service manually but I couldn't find it. After looking at the logs, I noticed that it updated last night and failed to restart itself afterwards. I then tried to run ServiceInstall.exe manually, but got the following error:
``` Unable to find Sonarr.Console.exe in the current directory ```
Sure enough, that file doesn't exist in C:\ProgramData\Sonarr\bin. I looked in the update logs and saw that it did say it copied the Sonarr.Console.exe file, but I couldn't find it in either the install directory or the temp directory.

**Logs**
Update logs here: https://pastebin.com/vZvTQekN
App logs from start of update to me manually starting app next morning: https://pastebin.com/V99anVBt

**System Information**
 - Sonarr Version: 3.0.1.435
 - Operating System: Windows 7
 - .net Framework (Windows): 4.7.02053

**Comment by skywayskase** [comment]
I also just noticed that it no longer seems able to connect to my local instance of Plex Server. Radarr can still talk to Plex, so it doesn't seem like it's a Plex issue. Looking back in my logs, it seems this was happening on 3.0.1.430 as well.

**Comment by markus101** [comment]
According to the logs the update was completed successfully and the service was started. Anti-virus is the likely cause of it's removal.

Not seeing the bug here, but if there is more information later that shows something actionable we can re-open.
