### ISSUE TITLE
Upgrade to v3 didn't change the update branch setting

### ISSUE THREAD

**Issue by addisonbabcock** [Sonarr/Sonarr#3042]
**Describe the bug**
I upgraded to v3 using the windows installer a few weeks ago. I noticed I wasn't getting any updates. Digging in it looks like the upgrade didn't change the update branch from `master` to `phantom-develop`. Changing the branch manually to `phantom-develop` allowed the automatic updating to work normally again. Should the installer change the update branch to `phantom-develop` automatically? 

**Screenshots**
N/A

**Logs**
N/A

**System Information**

 - Sonarr Version: Currently running 3.0.1.435. Initial upgrade would have been 3.0.1.418. 
 - Operating System: Windows 10 19H1
 - .net Framework (Windows) or mono (macOS/Linux) Version: Not sure how to figure out which version of .net is installed.

**UI Bugs:**
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
N/A

**Comment by markus101** [comment]
No the branch is not changed on install. We do however redirect requests to master/develop for v3 to `phantom-develop` if the version installed is at least 3.0.1.351 and the requested branch is master, develop or phantom and the branch will update once the update is successfully installed.

In my testing I'm not seeing any issues with this behaviour.

Debug logs prior to updating would be useful and we can reopen if there is something actionable for us.

**Comment by addisonbabcock** [comment]
That's fair. After reading your comment about the redirect I think maybe I was just impatient waiting for a v3 update after installing. I probably won't be going through the upgrade path again to gather a log since it seems to be working fine now.

Thanks for your help!
