### ISSUE TITLE
Add myshows.me integration

### ISSUE THREAD

**Issue by GutsyHeart** [Sonarr/Sonarr#3044]
**Describe the problem**
Find and add russian tv series

**Describe any solutions you think might work**
myshows.me has everything you need to search for Russian TV shows

**Additional context**
Api: https://api.myshows.me/shared/doc/

**Comment by markus101** [comment]
Please use the template for a feature request and explain what benefits this would provide.

**Comment by GutsyHeart** [comment]
Sorry, my English is not so good.

**Comment by markus101** [comment]
Thanks for clarifying, at this time we're not looking for other metadata providers, for now all series need to be on TheTVDB to be consumed by Sonarr.
