### ISSUE TITLE
Sonarr docker hogs all CPU and Ram

### ISSUE THREAD

**Issue by redxon** [Sonarr/Sonarr#3045]
So every few days sonarr behaves strangely, and just completely blocks anything from happening on the server. CPU and Ram is pinned in my dashboard on unraid at 100%, but on htop I don't see anything. I then have to kill the docker and restart it via SSH to get the system back. Attached is the log, anything I can do?
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/3072241/sonarr.txt)

**Comment by markus101** [comment]
This is better suited as a thread on the forums, including all the requested information (and trace logs in this case), please open a thread there.
