### ISSUE TITLE
Manual search result ranking, put matching episodes without matching qualities higher than non matching episodes

### ISSUE THREAD

**Issue by piejanssens** [Sonarr/Sonarr#3046]
** Update ** 
The reason it's not picking up an episode is because the quality doesn't match. I have set it to "HD Any" and the episodes are only available in SD. I now changed the title of the issue as it would be really useful to see at least the matching episodes on top of the results above the other non matching episodes.

**Describe the bug**
The latest season of Car SOS (S07) is not being picked up. When I manually search using Sonarr for S07E01 it's showing 175 matches, none of which are S07E01. I see in the trace (attached) that it calls the indexer with the query for "Car SOS : S07E01". When I execute that query directly in my indexer (NZBHydra) I get the exact and correct match for the Car SOS S07E01 episode.

I don't have the issue with any of my other series.

**Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/3072295/sonarr.trace.txt)

**System Information**
Version
    2.0.0.5322
Mono Version
    5.2.0.215

**Comment by markus101** [comment]
Order is determined by the order Sonarr would try the results if they were all a match it does not take the rejection reason into account.

v3 will have filtering that may be helpful, but getting results that don’t match depends on the indexer and it’s search capabilities.

No plans to alter this behaviour at this time.
