### ISSUE TITLE
No Meta Data showing on Added Shows

### ISSUE THREAD

**Issue by fahadsgalaxy** [Sonarr/Sonarr#3048]
**Describe the bug**
When searching for new shows, it does display all cover images of the shows, but upon adding them, I see no metadata whatsoever.

I started noticing this about month ago but still not fixing.

I thought it could be due to my location "China", they quite often block stuff, but I tried it via VPN as well, but no luck. 
Plex is able to pull all metadata.

I have tried to repeat all this on Mac, Windows and my NAS

**Screenshots**
https://ibb.co/SP9WTZM

**System Information**

 - Sonarr Version: [e.g. 2.0.0.1]
 - Operating System: [e.g. Windows 10]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Comment by markus101** [comment]
Please open a thread on the forums or subreddit for support. We'll need to see the debug logs of a show being added.
