### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by tscibilia** [Sonarr/Sonarr#3051]
**Describe the bug**
I cannot use sonarr, as the database is consistently 'malformed' and it won't let me access the webui. I've tried to restore backups, same issue, I've also started from scratch, initially works but same issue after importing shows. I've even tried the 3.0 dev version, same issue after importing shows.

**Screenshots**
n/a

**Logs**
[https://hastebin.com/eroqafakan.log](https://hastebin.com/eroqafakan.log)

**System Information**

 - Sonarr Version: 2.0.0.5321 & 3.0.1.441
 - Operating System: docker on ubuntu

**UI Bugs:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 73.0

**Additional context**

**Comment by markus101** [comment]
My first thought is you're storing `/config` on a network share, which is not supported and will cause issues (https://github.com/Sonarr/Sonarr/issues/1886) but given this is a support issue, and not a bug you'll need to open a thread on the forums or subreddit.

**Comment by tscibilia** [comment]
Thanks, its mounted on a glusterfs share. is there any difference with SMB/CIFS? or should that be considered the same potential issue?

**Comment by markus101** [comment]
SMB/SIFS definitely has the same issue (#1886 was originally opened for it).
