### ISSUE TITLE
Sonarr will download a Proper/Repair release even if a third release has already been downloaded and replaced the original one (that the proper is for)

### ISSUE THREAD

**Issue by gbougiakas** [Sonarr/Sonarr#3054]
Sonarr will download a Proper/Repair release even if a third release has already been downloaded and replaced the original one (that the proper is for)

at first it downloaded this: SomeTvShow.S08E01.SceneNameAlpha.1080p.mkv
then with a manual search I downloaded this SomeTvShow.S08E01.SceneNameBravo.1080p.mkv and it replaced the Alpha one.
then it downloaded this: SomeTvShow.S08E01.SceneNameAlpha.PROPER.1080p.mkv and mistakenly replaced the Bravo one.

I think it should check what scene is currently downloaded before grabbing a proper release for a previously downloaded (and eventually replaced) one.

**Comment by markus101** [comment]
Sonarr doesn't know which release was nuked when the proper was released. We do not have plans to support predb at this time (which may help) and repacks aren't limited to replacing the same release group (internally Sonarr doesn't differentiate between repack and proper, covered by https://github.com/Sonarr/Sonarr/issues/946).

**Comment by gbougiakas** [comment]
So no matter what release has been downloaded a Proper/Repack will replace everything up to that point no matter what the release group was?

**Comment by markus101** [comment]
For the exact same quality, yes. The repack issue will be addressed at some point.

**Comment by gbougiakas** [comment]
ok cheers!
