### ISSUE TITLE
Limit at 2.5GB but downloading a 4GB+ file

### ISSUE THREAD

**Issue by daviiiiiid** [Sonarr/Sonarr#3055]
So I've set up sonarr with sabnzbd for the first time today. It does not seem to respect the size limit I've input and saved. I have a limit of 2.5gb for everything and it is download 4GB+ files.

Anything I may be doing wrong?

For a show with a runtime of 54 minutes, and the 60 mins limit is at 2.5GB.

**Comment by markus101** [comment]
Premier and finales (based on the information Sonarr has) can be 2x the limit.
