### ISSUE TITLE
Web UI should have an option to copy the path to clipboard when it can't find a valid file

### ISSUE THREAD

**Issue by DanielO** [Sonarr/Sonarr#3058]
**Describe the problem**
Currently if it can't find a valid video file it will show an icon in the queue and you have to mouse over it then very carefully highlight the path and go to a terminal window and paste it then unpack the file.

**Describe any solutions you think might work**
Ideally it would unpack things automatically but that is a separate issue, in the interim there could be a (hopefully simple) UI change to allow quick copying of the path.

**Comment by markus101** [comment]
That path is part of a the error message so it alone isn't really something that can be copied, but I've added an Output Path column to v3 that'll show that information.
