### ISSUE TITLE
"Completed Download Handling" option not respected.

### ISSUE THREAD

**Issue by cybersteel8** [Sonarr/Sonarr#3059]
**Describe the bug**
Completed Download Handling option is not being respected, and torrent data is being deleted once seeding targets reached despite option being set to No.

**System Information**
 - Sonarr Version: 2.0.0.5322
 - Operating System: Fedora 27
 - ~~.net Framework (Windows) or~~ mono (macOS/Linux) Version: Mono 5.12.0.301

**Additional context**
I have this problem when using both QBittorrent and Transmission - when my seeding target is reached, Sonarr is deleting my torrent data from the hard disk. It is not being removed from QBittorrent or Transmission lists, so any attempt to re-seed or check the data fails and I must re-add and redownload the torrent again manually. I have the Sonarr option set to not do this, however it is behaving as if it is set to "Yes". 

If it is relevant to know - I also have the setting to use hardlinks instead of copy. The data is still intact, as the hardlink in the destination folder is still working.

I have also reported this in the [Radarr github issue tracker](https://github.com/Radarr/Radarr/issues/3481), as I am experiencing this bug in that application too.

**Screenshot**
![image](https://user-images.githubusercontent.com/17291212/56268644-3319ca80-6135-11e9-8a1b-ae0de471848a.png)

**Comment by markus101** [comment]
This is working as expected. If the torrent is seeding the file is moved, not copied/hardlinked, the torrent itself is not removed (that is controlled by the remove setting).

**Comment by cybersteel8** [comment]
So because I am hardlinking, the option is not respected? I should revert back to copying the data so that the torrent data will remain?

**Comment by markus101** [comment]
It has nothing to do with hardlinking.

If the torrent is no longer seeding, then Sonarr moves it. If it's seeding it's treated as read-only and copied or hardlinked depending on your settings/system configuration.
