### ISSUE TITLE
Season Folder Format not saving

### ISSUE THREAD

**Issue by pyiap** [Sonarr/Sonarr#3060]
When I change the Season Folder Format field to Season {season:00} and try to save it seems to always revert back.  It also creates saves episodes in the old Season {season} format.

 - Sonarr Version: 2.0.0.5322
 - Operating System: Windows 10
 - Browser: chrome

**Comment by markus101** [comment]
Please open a thread on the forums or subreddit for support.

Try another browser/private browsing (all plugins disabled), check the log files for errors and ensure Sonarr is reporting it's actually saved.
