### ISSUE TITLE
Hover Tooltips for Manual Import

### ISSUE THREAD

**Issue by Stanzilla** [Sonarr/Sonarr#3069]
**Describe the problem**
With the current UI of the manual import window, it is clear at all that you can click the column entries to change them.

Example: https://i.imgur.com/gkOTJFd.png

I did not know that I can click on the season number/episode number to change them

**Describe any solutions you think might work**
Add a tooltip on hover

**Additional context**

**Comment by markus101** [comment]
I'm not sure tooltips is the best option (especially on mobile), but hopefully it'll make it a bit less hidden.

**Comment by Stanzilla** [comment]
Awesome, thank you! And yes I know it's just a stop gap measure but certainly better than nothing :)
