### ISSUE TITLE
IPTorrents - "'Base Url' is not in the correct format.

### ISSUE THREAD

**Issue by Dwight2019** [Sonarr/Sonarr#3071]
**Describe the bug**
When adding the RSS feed to Sonarr it gives the error: "'Base URL' is not in the correct format."
I've tried adding both the direct download, and the web URL options, both giving the same issue.

**Screenshots**
![554b36a08b4bbf700fe2a21a0dd53fee](https://user-images.githubusercontent.com/49886326/56541266-726b6f80-65aa-11e9-96d2-70acb204d3d5.png)
![71a69ec96b479865bad079923dfeb352](https://user-images.githubusercontent.com/49886326/56541267-726b6f80-65aa-11e9-97c5-3a116a331e2b.png)

**System Information**

 - Sonarr Version: 2.0.0.5322
 - Operating System: Windows 10
 - .net Framework (Windows)

**UI Bugs:**
 - OS:  Windows
 - Browser: chrome
 - Version: 73.0.3683.103

**Additional context**
There was an issue very much the exact same as what i'm facing on the Lidarr forums. 
https://github.com/lidarr/Lidarr/issues/561

**Comment by SawkeeReemo** [comment]
Why was this closed with no resolution? It still does not work on Sonarr for Synology NAS. Any fix in the works?

**Comment by cdomansky** [comment]
Can confirm that this is still very much an active issue.

**Comment by lakersfankb81** [comment]
Also have this issue. Havent found anything resolving it yet

**Comment by bakerboy448** [comment]
@SawkeeReemo it was corrected with the linked commit

@cdomansky then make a new issue and fill out the template

@lakersfankb81 then make a new issue and fill out the template

Regardless, please do not necro old, resolved, closed issues. let alone ones for v2 and a version that is not actively developed

**Comment by markus101** [comment]
It was fixed v3, it was not and will not be backported to v2.
