### ISSUE TITLE
Sab category causing connection to fail

### ISSUE THREAD

**Issue by modem7** [Sonarr/Sonarr#3074]
If I leave the category out of the sab config, the connection test fails, but with a category (which I had to create to get this to work), it passes.

Sonarr Ver. 2.0.0.5322
OS: Fedora

![sonarr1](https://user-images.githubusercontent.com/4349962/56586525-c8a2d780-65d7-11e9-871e-a4dcb29a0ea4.JPG)

![sonarr2](https://user-images.githubusercontent.com/4349962/56586526-c8a2d780-65d7-11e9-9287-5ec6b097cbb2.JPG)

Radarr isn't behaving in this particular fashion, so it seems that the issue lies with Sonarr, or potentially, it's configuration (but not quite sure where)

**Comment by markus101** [comment]
It's a warning that only applies to testing, saving is fine. As it says a category is recommended.
