### ISSUE TITLE
Failed to load search results, please try again.

### ISSUE THREAD

**Issue by aimanzx** [Sonarr/Sonarr#3075]
i can't add any new series! everytime i try to add new series i get erorr (Failed to load search results, please try again.)
screenshot
![00099](https://user-images.githubusercontent.com/22063571/56616216-87391900-6625-11e9-898c-d33d111ce08c.PNG)

**Comment by markus101** [comment]
Please use the forums/subreddit for support, you'll need to supply the required information when opening a thread on the forums.
