### ISSUE TITLE
indexer checking and disabling

### ISSUE THREAD

**Issue by sundarnet** [Sonarr/Sonarr#3076]
**Describe the bug**
indexers are being disabled regularly after some sort of internal checks and are getting removed from the used list of used indexers, I have to regularly go in and re-test them to get the system to use them again this is extremely frustrating. 

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 2.0.0.5322
 - Operating System: UNRAID Docker
 - mono (macOS/Linux) Version: 5.16.0
**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
Please search before opening new issues.

https://github.com/Sonarr/Sonarr/issues/2802
