### ISSUE TITLE
V3 Rarbg search with jackett uses imdb id in search

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#3078]
Searching directly from jackett with S01E01 works fine but for some reason Jackett seem to be ignoring the season and episode when I search using sonarr. First I thought it might be sonarr not sending the season and episode but looking at the results and search words from other trackers this is only happening with rarbg. And sonarr is sending imdb number instead of show name

https://github.com/Jackett/Jackett/issues/5124
Version
3.0.1.454
Package Version
3.0.1
Mono Version
5.20.1.19
AppData directory
/var/lib/sonarr
Startup directory
/usr/lib/sonarr/bin
Mode
Console

**Comment by markus101** [comment]
Jackett is telling Sonarr that it supports searching by IMDB ID, so Sonarr tries. If no results are returned it should then search by the title.

If RARBG doesn’t actually support searching by IMDB ID Jackett should report it does.

**Comment by Dnkhatri** [comment]
> Jackett is telling Sonarr that it supports searching by IMDB ID, so Sonarr tries. If no results are returned it should then search by the title.
> 
> If RARBG doesn’t actually support searching by IMDB ID Jackett should report it does.

I get results but for all instead of just the episode I searched for is the implementation any different compared to v2 sonarr as that was searching with show name only not imdb number any way I have submitted the bug request for jackett.

**Comment by markus101** [comment]
Yes it's different. https://github.com/Sonarr/Sonarr/commit/24fba7a36dc0ff5300a02522f3d0b61bb35aca7f is the relevant change and the related PR: https://github.com/Sonarr/Sonarr/pull/2969
