### ISSUE TITLE
'Lost' series 1 information incorrect

### ISSUE THREAD

**Issue by 8bitleo** [Sonarr/Sonarr#3081]
While watching 'Lost' I noticed that it shows Season 1 as having 24 episodes when it in fact has 25. I'm unable to import the last episode (Exodus Part 3) as according to Sonarr it does not exist. 

![Screenshot_15](https://user-images.githubusercontent.com/31062255/56853228-c664b400-691c-11e9-8c23-0ec37bcea1d3.png)
![Screenshot_16](https://user-images.githubusercontent.com/31062255/56853229-c664b400-691c-11e9-8b5e-d5ff0170c39c.png)

 - Sonarr Version: 2.0.0.5322
 - Operating System: [e.g. Windows 10]

**Comment by Taloth** [comment]
Please post support questions on our forums. This is not a bug.

TheTVDB specifies 2 episodes, https://www.thetvdb.com/series/lost/seasons/1, Exodus (2) on tvdb was a double length episode that aired the 25th.
