### ISSUE TITLE
Alert on missing: If any episode is missing when one after is on disk

### ISSUE THREAD

**Issue by Fmstrat** [Sonarr/Sonarr#3083]
**Describe the enhancement**
Currently Sonarr already tracks missing episodes in the "Wanted" section. However, there is no alert system for missing episodes.

**Describe any solutions you think might work**
If an episode is downloaded where the one prior is not on disk (and both are monitored), send an alert via email. If the current episode has DL'd, you know the previous is missing. The only check required is for if a large scale DL is occurring and episodes are coming in out of order. An easy solution to this is to wait a certain amount of time after DLing has stopped before running the check for missing episodes.

**Additional context**
N/A

**Comment by markus101** [comment]
There are a lot of edge cases with sending alerts whenever a previous episode is missing, but this really boils down to the health of your library, which is covered by https://github.com/Sonarr/Sonarr/issues/1118. I've added a comment regarding this specific case.
