### ISSUE TITLE
Bug with episodes monitored using the Season pass

### ISSUE THREAD

**Issue by tidusjar** [Sonarr/Sonarr#3085]
**Describe the bug**
It seems when using the season pass functionality.
For example, add series "The Village (2019)" as unmonitored.
Then go into the season pass, select that series and set the `Monitor series` option to `Monitored` and `Monitor episodes` to `All`.

Only the currently aired episodes will be marked as monitored and all future episode will not be monitored.

**Screenshots**
![image](https://user-images.githubusercontent.com/6642220/56870561-49fbcf00-6a09-11e9-9a57-8fd9d60ac012.png)

**Logs**
Doesn't seem to be any information related to the API call here.
https://pastebin.com/xnAiB7Kf

**System Information**

 - Sonarr Version: 2.0.0.5322
 - Operating System: lsio docker
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.19

**Comment by markus101** [comment]
Yeah it's a bit buggy in v2. We're not fixing this in v2 and v3 already has this fixed (when using the v3 API and using `Monitor` instead of the `Ignore*` options). https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core/Tv/MonitoringOptions.cs#L12

**Comment by markus101** [comment]
To add I think you may be able to work around this in v2 by monitoring the latest season then monitoring all, the bug is `Ignore*` doesn't apply to unaired episodes because they neither have a file or are missing a file (since missing requires it to have aired).

**Comment by unfeomateo** [comment]
So I have to edit the file from the link above?
