### ISSUE TITLE
Episodes marked as "Cutoff Unmet" even though the quality meets or exceeds the cutoff.

### ISSUE THREAD

**Issue by schmittimillian** [Sonarr/Sonarr#3088]
**Describe the bug**
Sonarr sees some episodes as not meeting the cutoff, but the quality sonarr marks the episode as meets the cutoff. (Example: profile cutoff set at HDTV-720p, but an episode with Bluray-1080p quality gets put in the "Cutoff Unmet" queue)

**Screenshots**
Example of some episodes that get incorrectly flagged:
![image](https://user-images.githubusercontent.com/22268708/56923825-81b25780-6a99-11e9-90a2-ddfc3bcc4d51.png)

ChalkZone profile (_sd-cutoff):
![image](https://user-images.githubusercontent.com/22268708/56923866-98f14500-6a99-11e9-8431-d0bc9a212822.png)

Community profile (_hd-cutoff):
![image](https://user-images.githubusercontent.com/22268708/56923889-a60e3400-6a99-11e9-925d-dcc22491caf9.png)

_sd-cutoff profile settings:
![image](https://user-images.githubusercontent.com/22268708/56924552-2bdeaf00-6a9b-11e9-845f-9447210426c5.png)

_hd-cutoff profile settings:
![image](https://user-images.githubusercontent.com/22268708/56923948-ca6a1080-6a99-11e9-85ef-ec3419bb5809.png)

**Logs**
most recent logs:  
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/3129059/sonarr.txt)  
[sonarr.0.txt](https://github.com/Sonarr/Sonarr/files/3129061/sonarr.0.txt)  

**System Information**  
 - Sonarr Version: 3.0.1.467
 - Operating System: Windows Server 2019
 - .net Framework (Windows): .NET Framework 4.7.2 (461814)

**Additional context**
I have this happening with a bunch of episodes - the 4 included as examples are just a small sample. I had 20 episodes this was happening to by my last count.

**Comment by markus101** [comment]
The language cutoff is also applicable. So the language profile that is used is also relevant. You can optional show the language on Cutoff Unmet page to check that.

**Comment by schmittimillian** [comment]
Ah, yep. Okay so it's seeing the names of the files and is confusing the episode title with the language of the episode.

Example:
![image](https://user-images.githubusercontent.com/22268708/56924945-2afa4d00-6a9c-11e9-9072-43ebf5564448.png)

Is there any way I can manually define what the language of the episode is? I don't want to remove the episode title from the file name.

**Comment by markus101** [comment]
Yes, `Manage episodes in this season/series` on the series details page.

![image](https://user-images.githubusercontent.com/413544/56925085-5b81bd00-6a83-11e9-8316-02f6d3e2ab4c.png)

Select the episodes, change then change the language.
