### ISSUE TITLE
Slug conflicts cause imports to fail

### ISSUE THREAD

**Issue by jbd70** [Sonarr/Sonarr#3092]
**Describe the bug**
Importing the series [Blood+](https://www.thetvdb.com/series/blood) from `/tv/Blood+` fails when the series [Blood](https://www.thetvdb.com/series/blood-1) exists at `/tv/Blood`.

**Logs**
```
19-5-2 02:34:38.4|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Title slug 'blood' is in use by series 'Blood'
```

**System Information**
 - Sonarr Version: 3.0.1.467
 - Operating System: Debian x64
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.14.0.177

**Comment by markus101** [comment]
Blood+ will now get a slug of `blood-plus`, but depending on the release names used for these two series Sonarr may have issues matching since the titles are so similar.
