### ISSUE TITLE
Sonarr gives up even when there are downloads available

### ISSUE THREAD

**Issue by winterscar** [Sonarr/Sonarr#3093]
**Describe the bug**
Sonarr will give up trying to download an episode after a couple of failures. Sometimes, a usenet download will fail, and then Sonarr will try to download the next best candidate. 

However, if the download fails a few times, Sonarr will stop trying, despite there still being viable candidates available. 

You can prompt Sonarr to continue trying by running an automatic download. 

**System Information**

 - Sonarr Version: 2.0.0.5322
 - Operating System: Ubuntu (Running in docker)
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.19

**Logs**
[here](https://gist.github.com/winterscar/561ae0ceab0127c19df0664fd471d72a)

**Additional Context** 
This error most recently occured with the show Barry, S01E08, visible in the logs.

**Comment by markus101** [comment]
Please provide all the requested information including the debug logs.

We'll need to see the debug logs when Sonarr detects a failure and either doesn't search or fails to find a suitable release of the results returned. Without those there is nothing actionable for us.

**Comment by winterscar** [comment]
Sorry 😳. I was being lazy. I've updated my post. I'm not sure if I've added the right logs?

**Comment by markus101** [comment]
You need to enable debug logging and wait for the issue to happen so there is something for us to diagnose (it may end up being multiple log files since debug it chattier).

https://github.com/Sonarr/Sonarr/wiki/Log-Files#tracedebug-logs

**Comment by markus101** [comment]
This is likely related to https://github.com/Sonarr/Sonarr/issues/2973 if more info proves it's not then we can reopen.
