### ISSUE TITLE
Adding URL Base option in Sonarr v3 causes 'Epic Fail' error

### ISSUE THREAD

**Issue by 1aTa** [Sonarr/Sonarr#3094]
**Describe the bug**
Add URL Base option, restart Sonarr and service does not restart. Only way to restart Sonarr is to remove UrlBase option from config.xml.

**Logs**
https://gist.github.com/1aTa/ce4a65624a8b8eb3cab3d9ffc749d842

**System Information**

 - Sonarr Version: 3.0.1.467
 - Operating System: Windows 10
 - .net Framework: 4.8.03752
 - Browser: Chrome
 - Version: 74

**Comment by markus101** [comment]
It's an issue with permissions. Run `Sonarr.exe` or `Sonarr.Console.exe` as an admin once to register the new URL with Windows (HTTP.sys).

We may be able to show a better warning (instead of prompting to restart) though.

**Comment by 1aTa** [comment]
Thank you, sorted!
