### ISSUE TITLE
Suggestions on language management

### ISSUE THREAD

**Issue by GeoCookie** [Sonarr/Sonarr#3095]
Hello there,

I would like to report some problems I am facing with language management.
I am French and I like watching series in their native language. Therefore, I created several profiles with different languages. For English series, no problem, everything works fine. However, it gets complicated when I want to download a foreign serie. The main problem is the misinterpretation (in my opinion) of Sonarr of the terms related to the series language and subtitles. As a result, most episodes of foreign series do not download themselves

Some examples that I met: 
• If no term indicates the series language in the name of the torrent, Sonarr assumes that it is in English. In fact, most of the time, this means that the file is in the series original language.
(the serie below is in French, but found English by Sonarr)
![no language](https://user-images.githubusercontent.com/43962716/57134332-2688a980-6da6-11e9-883f-700ce96bc18a.png)

• The problem also arises for the term "VO". If Sonarr finds the word VO, it considers the file as English, which is not the case. A torrent with VO for an Italian serie means that it is in Italian, not in English
(I have no example right now)

• Some terms are misinterpreted, like "VOSTFR", "VF" or "Subfrench".
(the serie below is in Italian, but found French by Sonarr)
![vostfr](https://user-images.githubusercontent.com/43962716/57134339-2dafb780-6da6-11e9-8a98-06ba07262c08.png)

(the serie below is in Italian, but found French by Sonarr)
![subfrench](https://user-images.githubusercontent.com/43962716/57134348-343e2f00-6da6-11e9-840f-46006b08201c.png)

(the serie below is in French, but found English by Sonarr)
![vf](https://user-images.githubusercontent.com/43962716/57134351-3902e300-6da6-11e9-90a4-a612d5693a8b.png)

Some ideas that might help: 
• An very good point would be for Sonarr to deal with the original language of a serie. This way, it can knows to which language VO refers. For example, we can set "Original language" on the profile and Sonarr gets the language from the metadata (TheSerieDB have this information). 
• It would be nice if we could edit terms associated with a language. For example, that I can delete "VOSTFR" of the French language terms.

Many thanks for your work. Sonarr have really simplified my download process! :)

**Comment by markus101** [comment]
> If no term indicates the series language in the name of the torrent, Sonarr assumes that it is in English. In fact, most of the time, this means that the file is in the series original language.
(the serie below is in French, but found English by Sonarr)

Correct, there is no magic there. Sonarr needs to be told if it's not English.

> The problem also arises for the term "VO". If Sonarr finds the word VO, it considers the file as English, which is not the case. A torrent with VO for an Italian serie means that it is in Italian, not in English
(I have no example right now)

Same problem.

> (the serie below is in Italian, but found French by Sonarr)

Same problem, except the SUBFRENCH detects it as French.

> An very good point would be for Sonarr to deal with the original language of a serie

https://github.com/Sonarr/Sonarr/issues/269 though that's not a silver bullet, at best Sonarr _might_ be able to use the network, but that's not going to be perfect either.

> It would be nice if we could edit terms associated with a language. For example, that I can delete "VOSTFR" of the French language terms.

This is not going to happen.

I assume VO and VF are just indicators that the file is in the original language (if they're not please correct me), which means there isn't really anything we're going to be able to do at this time.

https://github.com/Sonarr/Sonarr/issues/2854 might be able to help to set the default language for a release, but that's not going to work on sites that release multiple languages.
