### ISSUE TITLE
Error opening database file

### ISSUE THREAD

**Issue by fvlaicu** [Sonarr/Sonarr#3096]
**Describe the bug**
The service crashes and the cpu stays pegged to 100%

**Logs**
https://pastebin.com/p2rCFLDW

**System Information**

 - Sonarr Version: 3.0.1.467
 - Operating System: Debian 9.9
 - mono Version: 5.20.1.19

**Additional context**
It seems that there might be a race condition here. It only happens if i have a few sonarr windows open. Today it occurred 2 times and i have 7 sonarr windows open. 
It worked fine for a week while i was on vacation and i didn't have any sonarr windows open :).

**Comment by Taloth** [comment]
TL:DR: Downgrading to mono 5.12 will likely workaround the issue. 

Mono > 5.12 appears to have an issue with sockets staying half open (`man lsof` will likely show that). And when the sonarr webui stays open long enough more and more of those sockets will end up stuck and gobble up file descriptors.

So until we can find the issue and workaround it and/or have mono fix it, you'll likely need to stick to mono 5.12.

**Comment by Taloth** [comment]
Hm, actually, it's also happening on 5.12 😒

**Comment by markus101** [comment]
Is this the same underlying issue as https://github.com/Sonarr/Sonarr/issues/2802?

**Comment by Taloth** [comment]
The underlying problem could be related yes, but that's hard to prove. Especially since I could repro on 5.12 and the Jackett issue appears not to be reproducible on 5.12.
But OPs issue is the same as I noticed myself, signalr connections starving the filedescriptor pool causing sqlite not to be able to connect anymore and the cpu pegged.

**Comment by Taloth** [comment]
@fvlaicu It should be better on 3.0.1.497

If you keep having issues let me know.
