### ISSUE TITLE
Add new series search shows duplicate entries

### ISSUE THREAD

**Issue by mcroach** [Sonarr/Sonarr#3099]
**Describe the bug**
When using the "Add New Series" search, the results can contain duplicate entries of an individual show (this is especially true for shows that have not yet aired, but has been seen on already aired as well). When this happens, one entry will be fully populated with show information (summary, poster, etc), while the other is just a generic blank entry with series title.

If you add the series using the entry that is missing the show information Sonarr will fail to successfully search for or download episodes once the show airs.

**Reproduce**
Searching for "in the dark" will return two entries for "in the dark (2019)" with only one containing any show information.

Relevant TVDB Link: https://www.thetvdb.com/series/in-the-dark-2019

**Logs**
This was the only information I could find in the logs related to the search activity:

```
19-5-4 22:45:59.7|Trace|Http|Req: 116613 [GET] /api/v3/series/lookup?term=in%20the%20dark%20
19-5-4 22:45:59.7|Trace|HttpClient|Req: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=in%20the%20dark
19-5-4 22:45:59.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
19-5-4 22:46:00.4|Trace|Http|Req: 116614 [GET] /api/profile?apikey=(removed)
19-5-4 22:46:00.4|Trace|Http|Res: 116614 [GET] /api/profile?apikey=(removed) 200.OK (2 ms)
19-5-4 22:46:00.4|Debug|Api|[GET] /api/profile?apikey=(removed) 200.OK (2 ms)
19-5-4 22:46:00.5|Trace|Http|Req: 116615 [GET] /api/v3/languageprofile?apikey=(removed)
19-5-4 22:46:00.5|Trace|Http|Res: 116615 [GET] /api/v3/languageprofile?apikey=(removed) 200.OK (1 ms)
19-5-4 22:46:00.5|Debug|Api|[GET] /api/v3/languageprofile?apikey=(removed) 200.OK (1 ms)
19-5-4 22:46:00.5|Trace|Http|Req: 116616 [GET] /api/series?apikey=(removed)
19-5-4 22:46:01.0|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=in%20the%20dark: 200.OK (1324 ms)
19-5-4 22:46:01.0|Trace|Http|Res: 116613 [GET] /api/v3/series/lookup?term=in%20the%20dark%20: 200.OK (1346 ms)
19-5-4 22:46:01.0|Debug|Api|[GET] /api/v3/series/lookup?term=in%20the%20dark%20: 200.OK (1346 ms)
19-5-4 22:46:01.9|Trace|Http|Res: 116616 [GET] /api/series?apikey=(removed) 200.OK (1393 ms)
```
**System Information**

- Sonarr Version: 3.0.1.473
- Package Version: 3.0.1.473-ls65 by linuxserver.io
- Mono Version: 5.20.1.19

**Comment by mcroach** [comment]
Example:

![image](https://user-images.githubusercontent.com/5669388/57188289-afe0ce80-6ec1-11e9-9a32-6b8be9c1135e.png)

**Comment by markus101** [comment]
This is due to the duplicates being deleted from the TVDB and The TVDB no longer removing duplicates from their old API so Skyhook doesn't know to purge them. We're working on some changes to improve that on the skyhook side, but in the mean time, if you see others please open a thread on the forums with the duplicate TVDB ID and we can nuke them.
