### ISSUE TITLE
UrlBase is always converted to lower case

### ISSUE THREAD

**Issue by postlund** [Sonarr/Sonarr#3101]
**Describe the bug**
Despite what is entered in the UrlBase configuration option, the input is always converted to lower case. This causes problems as I use a reverse proxy (kinda, Hass.io to be more precise) that is case sensitive. So requests to resources are filtered in my proxy before ever reaching sonarr.

**Screenshots**
No screenshots.

**Logs**
My example config looks like this:

```xml
<Config>
  <LogLevel>Info</LogLevel>
  <Port>8989</Port>
  <UrlBase>/api/hassio_ingress/obS8GUpZNbj25Wem4ImQ0vBXUXxRGpiHRzQoMLnEtDw</UrlBase>
  <BindAddress>*</BindAddress>
  <SslPort>9898</SslPort>
  <EnableSsl>False</EnableSsl>
  <ApiKey>fa71b3f0b65b49c5892c31b2ee1d1c4d</ApiKey>
  <AuthenticationMethod>None</AuthenticationMethod>
  <Branch>master</Branch>
</Config>
```
So I would expect my URL to be something along the line of `http://*:8989/api/hassio_ingress/obS8GUpZNbj25Wem4ImQ0vBXUXxRGpiHRzQoMLnEtDw`. But according to the startup, everything is lower case:

 ```
[Info] Bootstrap: Starting Sonarr - /opt/NzbDrone/NzbDrone.exe - Version 2.0.0.5322 
[Info] AppFolderInfo: Data directory is being overridden to [/data] 
[Info] Router: Application mode: Interactive 
[Info] MigrationLogger: *** Migrating data source=/data/nzbdrone.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationLogger: *** Migrating data source=/data/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] OwinHostController: Listening on the following URLs: 
[Info] OwinHostController:   http://*:8989/api/hassio_ingress/obs8gupznbj25wem4imq0vbxuxxrgpihrzqomlnetdw/
[Info] OwinHostController:   http://*:8989/ 
[Info] NancyBootstrapper: Starting Web Server 
```
Hass.io, my reverse proxy, then fails to find any resources due to this:
```
...
hassio_supervisor | 19-05-06 11:31:50 WARNING (MainThread) [hassio.api.ingress] Ingress for obs8gupznbj25wem4imq0vbxuxxrgpihrzqomlnetdw not available
...
```
**System Information**

 - Sonarr Version: 2.0.0.5322 
 - Operating System: Xubuntu Linux
 - .net Framework (Windows) or mono (macOS/Linux) Version: 2.0.0.5322

**UI Bugs:**
 - OS: Any OS
 - Browser: Any browser
 - Version: Any version

**Additional context**
I would expect that the exact URL would work fine in this case.

**Comment by Taloth** [comment]
That is expected behavior, if you change the UrlBase in the Sonarr UI it also autoconverts to lowercase as well.
Afaik hassio allows you to configure any ingress url, so the easiest approach is using random lowercase strings instead for your services.

**Comment by postlund** [comment]
Yeah, I saw that in the code. Is there any particular reason for doing so? Wouldn't it be more flexible if it kept casing as-is?

I don't think it's possible to modify the actual ingress URL. You can change the entry point using `ingress_entry` (and port using `ingress_port`), but that's only the subpath after the token. The URL is generated like this:

```python
    @property
    def ingress_url(self) -> Optional[str]:
        """Return URL to ingress url."""
        if not self.with_ingress:
            return None

        url = f"/api/hassio_ingress/{self.ingress_token}/"
        if ATTR_INGRESS_ENTRY in self.data:
            return f"{url}{self.data[ATTR_INGRESS_ENTRY]}"
        return url
```

**Comment by Taloth** [comment]
The ingress_token is generated somewhere, I've seen different length tokens for other ingress plugins including exclusively lower-case ones. But I don't use hassio so I cannot point you at the appropriate documentation.

We have no plans to support upper case url bases.
