### ISSUE TITLE
Parsing TV via Jackett (IPT) searches all seasons / episodes 

### ISSUE THREAD

**Issue by nduda78** [Sonarr/Sonarr#3104]
**Describe the bug**
I've noticed with many of the latest phantom-develop releases (specifically 3.0.1.478) when searching manually using Jackett (IPT)  the results will show random season/episodes with the notes:

- Episode wasn't requested:
- Wrong season

<img width="1242" alt="Screen Shot 2019-05-06 at 11 27 12 PM" src="https://user-images.githubusercontent.com/25825986/57269713-77bec480-7056-11e9-9d5d-46f8deaad1f2.png">

Rolling back to much earlier version of the phantom branch solve this. For example, 3.0.1.363 doesn't have this issue. For what it's worth I'm using docker images. 

**System Information**

 - Sonarr Version: 3.0.1.478
 - Operating System: Synology DSM , Docker

**Comment by markus101** [comment]
We need debug logs.

Logs from both versions would be useful.

**Comment by nduda78** [comment]
Here you go. I enabled debug on .478 and then did a few searches.

[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/3154620/sonarr.debug.txt)

**Comment by markus101** [comment]
It looks like it's searching by IMDB ID because Jackett says it supports it, but doesn't actually appear to for TV. There is a Jackett GHI for it here: https://github.com/Jackett/Jackett/issues/5124 (originally for RARBG, but this would be the same issue).

**Comment by nduda78** [comment]
I'm no dev or anything so I'll just wait until someone posts a fix...however, I pointed sonarr to another older jacket install which is working fine with another old sonarr instance and I still get the same problem. I'm guessing this is a sonarr issue, not jackett.

Thanks for the quick reply!

**Comment by Dnkhatri** [comment]
> It looks like it's searching by IMDB ID because Jackett says it supports it, but doesn't actually appear to for TV. There is a Jackett GHI for it here: [Jackett/Jackett#5124](https://github.com/Jackett/Jackett/issues/5124) (originally for RARBG, but this would be the same issue).

No tracker I know off supports imdb search with with season and episode. As imdb search is mostly for movies enabling it in sonarr with season and episode is breaking episode search. Sonarr should only use imdb search when doing full season or full show search.

**Comment by Taloth** [comment]
>  Sonarr should only use imdb search when doing full season or full show search.

No, as flightlevel already indicated on the linked GHI. Jackett advertises that it supports imdbid for tv searches. They're considering whether they really support that for tv search and will adjust Jackett accordingly. 
Otherwise they'll have to adjust their code to return an appropriate empty result if that particular imdbid search isn't possible or filter the results if the underlying indexer cannot search by imdbid _and_ episode number.

**Comment by Zalcore** [comment]
I can search IPT for series by IMDB ID just fine if I do it manually so issue might be how it search for specific episodes or something else.

Example: Strike Back.
Searching for tt1492179 s07e01 returns 4 results. 
Searching for Strike Back s07e01 returns the same 4 results.
