### ISSUE TITLE
Series Spanish Princess Sonarr thinks is Spanish

### ISSUE THREAD

**Issue by SJPadbury** [Sonarr/Sonarr#3106]
The new series The Spanish Princess did not download on Sunday, because for every release, it sees the word Spanish in the title, and reports "English is wanted, but found Spanish"

This show is most definitely in English, Spanish is just part of the title of the series.

**Comment by markus101** [comment]
Please use the templates when filing issues.

This is fixed in v3. https://github.com/Sonarr/Sonarr/commit/b3ff91608ea78bfd5499e1459eabe2f7b7d5a210
