### ISSUE TITLE
Option for using romaji titles or anime

### ISSUE THREAD

**Issue by viggy96** [Sonarr/Sonarr#3109]
**Describe the problem**
Its hard to search for anime with Romaji titles which are most commonly used over the English translated title. It would also make titles more consistent for anime, as some shows only have a romaji title, making it hard to know which shows are using which language for the title. 

**Describe any solutions you think might work**
Having the option to choose to use Romaji titles would be nice as I tend to remember Romaji titles more than the English ones when searching your existing library of media. It would also make it easier to add new anime.

**Comment by markus101** [comment]
Support for metadata in other languages is covered by https://github.com/Sonarr/Sonarr/issues/269

Searching for releases is based on the available aliases (which come from thexem.de for anime).
