### ISSUE TITLE
[Bug][Phantom branch] Interactive search uses TV category parameter for Anime.

### ISSUE THREAD

**Issue by kvn1351** [Sonarr/Sonarr#3112]
**Describe the bug**
_Interactive search_ uses TV as category instead of Anime even though the show is set as such. _Quick search_, however, does use the correct category as can be seen in the screenshot.

Due to this, the interactive search is rendered useless on anime.

Thanks a lot for all of your hard and amazing work by the way!

**Screenshots**

![image](https://user-images.githubusercontent.com/11823348/57581916-ecfb2100-74be-11e9-8766-d62723c956ee.png)

**System Information**

 - Sonarr Version: 3.0.1.492
 - Operating System: linux docker
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.19

**Comment by Taloth** [comment]
Please provide is with debug log files.

The screenshot you provided does not show which queries Sonarr performs.

**Comment by markus101** [comment]
Not able to reproduce this issue and the logs confirm this.

```
19-5-12 16:29:32.0|Trace|Http|Req: 30 [GET] /api/v3/release?seriesId=105&seasonNumber=3
19-5-12 16:30:08.4|Trace|Scheduler|Pending Tasks: 0
19-5-12 16:30:08.4|Info|NzbSearchService|Searching 1 indexers for [Attack on Titan : 38]
19-5-12 16:30:08.5|Debug|NzbSearchService|Total of 0 reports were found for [Attack on Titan : 38] from 1 indexers
19-5-12 16:30:08.5|Debug|NzbSearchService|Setting last search time to: 5/12/2019 11:30:08 PM
19-5-12 16:30:08.5|Info|DownloadDecisionMaker|No results found
19-5-12 16:30:08.5|Info|NzbSearchService|Searching 1 indexers for [Attack on Titan : 39]
19-5-12 16:30:08.6|Debug|NzbSearchService|Total of 0 reports were found for [Attack on Titan : 39] from 1 indexers
19-5-12 16:30:08.6|Debug|NzbSearchService|Setting last search time to: 5/12/2019 11:30:08 PM
19-5-12 16:30:08.7|Info|DownloadDecisionMaker|No results found
19-5-12 16:30:08.7|Info|NzbSearchService|Searching 1 indexers for [Attack on Titan : 40]
19-5-12 16:30:08.7|Debug|NzbSearchService|Total of 0 reports were found for [Attack on Titan : 40] from 1 indexers
19-5-12 16:30:08.8|Debug|NzbSearchService|Setting last search time to: 5/12/2019 11:30:08 PM
19-5-12 16:30:08.8|Info|DownloadDecisionMaker|No results found
```
