### ISSUE TITLE
Sonarr does not find anime packs that contains "INTEGRALE" in their title

### ISSUE THREAD

**Issue by benamib** [Sonarr/Sonarr#3113]
**Describe the bug**
I am looking to download some anime packs using Xthor (french torrent tracker) as an indexer but for some release I din't manage to do so because the results are not shown in sonarr even though jackett returns them.

I found out that most of the pack concerned by this issue contains "INTEGRALE" in their name

Does anyone know why that might be ?

**Screenshots**
<img width="1019" alt="Screenshot 2019-05-12 at 15 05 11" src="https://user-images.githubusercontent.com/2103806/57582628-81698180-74c7-11e9-972a-cd1c0feb9745.png">

<img width="1350" alt="Screenshot 2019-05-12 at 15 06 06" src="https://user-images.githubusercontent.com/2103806/57582631-87f7f900-74c7-11e9-9349-ed9364d94e6f.png">

**Logs**
Sonarr logs:
```
Info] NzbSearchService: Searching 1 indexers for [Fullmetal Alchemist: Brotherhood : 10]
[Info] DownloadDecisionMaker: Processing 2 releases
```

Jackett logs:
```
Builded query for "fullmetal alchemist brotherhood 10"... https://api.xthor.to/?passkey=XXX&search=fullmetal+alchemist+brotherhood+10&category=101

Querying tracker for results....

API State : Everything OK ... -> Ok
[ReleaseInfo: Title=FullMetal.Alchemist.Brotherhood.MULTI.VOSTFR.1080p.BluRay.x264-Dryl, Guid=https://xthor.to/details.php?id=68739, Link=https://xthor.to/download.php?torrent=68739&torrent_pass=XXX, Comments=https://xthor.to/details.php?id=68739, PublishDate=10/7/16 8:57:43 AM, Category=System.Collections.Generic.List`1[System.Int32], Size=152656692709, Files=65, Grabs=6, Description=, RageID=, TVDBId=, Imdb=, TMDb=31911, Seeders=0, Peers=1, BannerUrl=, InfoHash=, MagnetUri=, MinimumRatio=1, MinimumSeedTime=345600, DownloadVolumeFactor=0, UploadVolumeFactor=1, Gain=0]
[ReleaseInfo: Title=Fullmetal.Alchemist.Brotherhood.INTEGRALE.MULTI.VOSTFR.1080p.BluRay.x264-EBD, Guid=https://xthor.to/details.php?id=53046, Link=https://xthor.to/download.php?torrent=53046&torrent_pass=XXX, Comments=https://xthor.to/details.php?id=53046, PublishDate=7/23/16 5:09:55 PM, Category=System.Collections.Generic.List`1[System.Int32], Size=64020507924, Files=69, Grabs=51, Description=, RageID=, TVDBId=, Imdb=, TMDb=31911, Seeders=5, Peers=5, BannerUrl=, InfoHash=, MagnetUri=, MinimumRatio=1, MinimumSeedTime=345600, DownloadVolumeFactor=1, UploadVolumeFactor=1, Gain=298.118721339852]
05-12 13:03:58 Info Found 2 releases from Xthor for: Fullmetal Alchemist Brotherhood 10
```

**System Information**

 - Sonarr Version: 3.0.1.492
 - Jackett Version: 0.11.325.0
 - Operating System: Ubuntu Server 18.04.2 LTS
 - Mono (macOS/Linux) Version: 5.20.1.19

**Comment by markus101** [comment]
Sonarr doesn’t see it because it’s searching for a specific episode and that release does not contain it/Jackett does not know to return it, but even if Sonarr did get that result back it’d be unable to parse it. This isn’t something we can fix.

**Comment by benamib** [comment]
So there is no way to download from sonarr this release : "Fullmetal.Alchemist.Brotherhood.INTEGRALE.MULTI.VOSTFR.1080p.BluRay.x264-EBD" 
I also tried using the season interactive search but nothing was returned as well

**Comment by markus101** [comment]
Correct, no way to download it from Sonarr. Even if the result was returned Sonarr is unable to determine which series, season and episode the release is for and full series packs are not supported.
