### ISSUE TITLE
Attempting to search for season fails

### ISSUE THREAD

**Issue by RyanAStrouse** [Sonarr/Sonarr#3118]
**Describe the bug**
For some reason I can't get results to show when searching the BTN indexer for a season. I just recently updated from v2 to v3 sonarr running in a docker container. I can find the show on the website, and if I manually DL and import after it downloads it works. I've taken steps (using Jackett) to get the URL that is passed through and diagnosed it a bit. When I take out the "&ep=1" (or whatever episode I manually search on) parameter I get results in my browser for season packs. When I add in any "&ep=" then I get no results (even though they are on the site).
The pastebin I link is where I'm getting it to work with Jackett, rather than the program's default BTN indexer. My example show is using Ducktales. I've tried deleting the indexer and re-adding. Tried restarting container.

**Logs**
https://pastebin.com/XjuG1zw8

**System Information**
OS Ubuntu 18.06
Sonarr Version 3.0.1.493
Package Version 3.0.1.493-ls73 by linuxserver.io
Mono Version 5.20.1.19

**Additional context**
Workaround is manually added the files to downloader, then importing them from the queue once they finish.

**Comment by markus101** [comment]
As mention, this isn't a bug and doesn't belong here. BTN doesn't keep single episodes around, you need to use a season search.
