### ISSUE TITLE
Path change option to move files

### ISSUE THREAD

**Issue by JustinH2008** [Sonarr/Sonarr#3120]
**Describe the problem**
A clear and concise description of the problem you're looking to solve.

Would like to see a feature for adjusting paths after a series is already downloaded to move files to specified folder at the same time (Similar to the option to delete all files when removing a series.)

**Describe any solutions you think might work**
A clear and concise description of any solutions or features you've considered.

Unknown solution, but I do not think it would be a hard feature to implement since Sonarr already has file permissions of the folder the items are stored in.

**Additional context**

N/A

**Comment by markus101** [comment]
This is possible in v3.
