### ISSUE TITLE
Indexers Unavailable due to failures

### ISSUE THREAD

**Issue by sinister718** [Sonarr/Sonarr#3122]
Hello  i am having the problem with my sonarr docker binhex-sonarr i  consistently get the error indicated in the title every couple of hours i  am using unraid with indexers added via jackett. I also have radarr installed with indexers added from the same source  and it never seems to have this issue. I'm not using any proxies with  either container, i have gone as far as to to delete the container and  start all over from scratch im not sure what the issue is but would love  to resolve this months long issue i have been having
--

Version
2.0.0.5322
Mono Version
5.16.0

**Comment by markus101** [comment]
Use the forums or subreddit for support.

There is also https://github.com/Sonarr/Sonarr/issues/2802 (the 3rd issue in the list before you opened yours), unless you have something more than "me too" to add, please don't comment there.
