### ISSUE TITLE
Automatically Un-monitor an episode once a valid download has been achieved 

### ISSUE THREAD

**Issue by Lord-Malgus** [Sonarr/Sonarr#3129]
I am currently using the 'Preferred Words' option that was added to Sonarr (Thank you).  

However once a valid download for an episode is achieved,  I would like Sonarr to stop looking for any more releases..  Basically Un-monitor an episode once a download is completed. 

Currently I prefer HEVC, however most releases are still posted AVC first.  I would like Sonarr to stop looking for new releases once either a HEVC or AVC download is achieved, no matter the preferred words as when an AVC is found first I have it scripted to covert it to HEVC.   However what is happening is it will later download another HEVC release and over write the file I just converted.  

I was hoping the "Do Not Upgrade Automatically" under the "Propers and Repacks" might prevent this situation,  however it still continues to download a new release anyway.
![image](https://user-images.githubusercontent.com/9889229/58120554-828b6480-7bd3-11e9-965b-e2ac4434db6c.png)

So what I am asking for would be the option to automatically un-monitor an episode once any valid download is completed.  

Thank you.

**Comment by markus101** [comment]
A Custom Script would be best for that. We have no plans to automatically unmonitor when an episode is downloaded.

At this time we don't have anything planned for a "cutoff" for preferred words, but it's something we'll keep an eye on.
