### ISSUE TITLE
Unsupported MediaInfoLib encoding

### ISSUE THREAD

**Issue by cemalb** [Sonarr/Sonarr#3130]
I'm facing Encoding-MediaInfoLib issue with v3 beta and v2 on raspberry pi 3 b+ (Raspbian 9)

System.NotSupportedException: Unsupported MediaInfoLib encoding
  at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo.InitializeEncoding () [0x000b0] in <6a3dcbc5b3c2463890627fff9fca65cd>:0 
  at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo..ctor () [0x00011] in <6a3dcbc5b3c2463890627fff9fca65cd>:0 
  at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo (System.String filename) [0x00021] in <6a3dcbc5b3c2463890627fff9fca65cd>:0 

**System Information**

 - Sonarr Version: [v2.0.0.5322] (Also with v3 beta)
 - Operating System: Raspbian
 - Mono Version: 5.20.1.19

I'm facing same issue on app start. It throws from NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo.InitializeEncoding.

P.S: I'm quite sure, app founds mediainfo library and mediainfo is able to work from CLI or via GUI. For sure i had something wrong, first set-up v3 beta on raspbian faced this issue, removed safely and installed again nzbdrone-sonarr v2 and still facing same issue.

**Comment by Taloth** [comment]
Which version of mediainfo?

**Comment by cemalb** [comment]
Hello @Taloth 

MediaInfoLib version is v19.04 just installed last night from mediaarea debian repositories as mentioned in v3 Beta setup documentation early beginning.

**Comment by Taloth** [comment]
19.04 on my ubuntu intel system works fine.

I've added a bit more logging so it might output more useful diagnostic info. Wait for 3.0.1.500 and let me know what error it logs.

**Comment by cemalb** [comment]
Hello,

Just tried with 3.0.1.500 from source

MediaInfo Library could not be loaded Unsupported MediaInfoLib encoding, version check responses (may be gibberish, show it to the Sonarr devs): Option not known, O, Option not known

P.S: I have also tried to downgrade my mediainfolib so file and put directly next to Sonarr.exe too (just to be sure)

Run application with MONO_LOG_LEVEL=debug mono Sonarr.exe --debug | grep media 
and got results related with library like;

Mono: mono_w32file_find_next: Found [/opt/a/Sonarr/libmediainfo.so.0]
Mono: mono_w32file_find_next: Found [/opt/a/Sonarr/libmediainfo.so.0]
Mono: mono_w32file_find_next: Found [/opt/a/Sonarr/libmediainfo.so.0]
Mono: DllImport attempting to load: 'libmediainfo.so.0'.
Mono: DllImport loaded library '/opt/a/Sonarr/libmediainfo.so.0'.
Mono: DllImport searching in: 'libmediainfo.so.0' ('/opt/a/Sonarr/libmediainfo.so.0').
Mono: DllImport searching in: 'libmediainfo.so.0' ('/opt/a/Sonarr/libmediainfo.so.0').
Mono: DllImport searching in: 'libmediainfo.so.0' ('/opt/a/Sonarr/libmediainfo.so.0').
Mono: DllImport searching in: 'libmediainfo.so.0' ('/opt/a/Sonarr/libmediainfo.so.0').

**Comment by Taloth** [comment]
"Option not known"... meaning MediaInfo lib doesn't understand 'Info_Version' while that option has been present for over 12 years. So it likely can't properly parse the string we pass to it.

Maybe there's an odd locale/charset set on your machine?
Best bet is libmediainfo being badly installed.

**Comment by cemalb** [comment]
THANK YOU! [SOLVED]

I was using my Raspbian as a desktop environment (with Gui) so when i have install os, ordinarily picked up my native language.

Finally, I have just change my locale settings with English/ISO-8859-1 and ALL is fine
Stupid issue that coming from really deep, i have either tried to build mono, libmedia from source...

**Comment by Taloth** [comment]
It's still somewhat an issue either with Sonarr or mediainfo coz apis shouldn't be locale dependent, what locale was it set to?

**Comment by cemalb** [comment]
It was Turkish language with UTF-8 charset encoding. Probably "Info_Version" string become "ınfo_version" instead of "info_version" or something like this so mediainfolib could not recognize.

**Comment by Taloth** [comment]
tnx, I'll try that in a docker container when I have a bit of time.
