### ISSUE TITLE
Sonarr deletes files downloaded via Transmission before moving them

### ISSUE THREAD

**Issue by ThomasClemenceau** [Sonarr/Sonarr#3131]
**Describe the bug**
It is pure speculation but I think Sonarr deletes files downloaded via Transmission.
I usually download season folders for my series (like South Park), and when the import is launched after download has completed, only a few episodes of the show had been moved and the others are unreachable. So I decided to try something : disable "Remove" in "Completed Download Handling" section, and it worked as intended. 

My theory is that Sonarr asks Transmission to delete the torrent in the history AND the files (maybe bad API request, don't know)

### **EDIT:**
After looking at the code, the problem really comes from what I was thinking. "Remove" doesn't only remove the torrent, but also the files. So, two points :

First : 
Maybe it's a good idea to make two separate buttons, one to allow only Remove torrent, and the other to remove files.

Second : 
Actually, the remove of torrent + files appears during the import, which is not what intended. The solution is probably to wait for the import to be done before deleting anything.

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 2.0.0.5322
 - Operating System: Synology
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 5.18.0.240

**Additional context**

**Comment by markus101** [comment]
Sonarr will only automatically remove a torrent that has been imported and has finished seeding (according to the download client) and the files have been imported (at least one file).

Clicking remove from Activity: Queue will remove it from the torrent client, including the files. We’re not adding an option/other button to only remove and leave the files, you can do that from your client.

If you use manual import Sonarr could remove files automatically before everything is imported which is partially addressed in v3 currently and will have more improvements coming.

Related to https://github.com/Sonarr/Sonarr/issues/2393 and https://github.com/Sonarr/Sonarr/issues/668
