### ISSUE TITLE
Improved Indexer Backoff and Status handling logic

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#3132]
@theotherp @garfield69

I'm opening this issue to discuss a few options in improving the handling of indexer failures in Sonarr (and likely Radarr/Lidarr too), particularly in relation to NzbHydra and Jackett.

As you well know, Sonarr uses an incremental back-off logic that stops querying an indexer if it returns certain errors. There are some challenges with this, particularly for aggregators such as Jackett and NzbHydra. So I figured I'd work out the issues and possible solutions.

### No API usage/limit status in Newznab specification

Newznab indexers do not include the current user limits and usage in the query response.
It'd be useful if newznab responses contain the remaining queries and grabs allowed and at which time that limit will increment again. This means 4 attributes, 'remaining' and 'reset time' for both 'query' and 'grab' separately. Ideally we'd have the limit for each of those as well. (Which could be useful in prioritizing grabs to indexers with more liberal limits).
This of course means we have to talk to the newznab devs, see if they're interested in adding it to the codebase.
I suspect it is of limited use for Jackett/NzbHydra but I imagine it's useful in determining whether grab limits are (about to be) reached and to send appropriate responses back to Sonarr.

### Separate Query and Grab backoff counters

Sonarr currently initiates backoffs if either queries or grabs fail. _(Except when the failure is a dns/connection error, in which case it doesn't escalate since it's likely the user-connection that's down)_
We should instead maintain two separate backoffs, one for the queries and one for the grabs. Let's call those 'query-backoff' and 'grab-backoff'.
This would allow us to handle the grab limits more gracefully.

Sonarr should temporarily reject any release for indexers that are currently in the grab-backoff. In Sonarr's decision logic, permanent rejections mean a release is discarded entirely, but temporary rejections are put on the pending queue. At least until another release of equal or higher quality has been grabbed _and_ imported successfully.
So temporarily rejecting releases from indexers in an active grab-backoff, means those releases remain eligible to be grabbed later once the backoff expires.

### HTTP 429 'Too Many Requests' Handling

When Sonarr receives a 429 response with an optional Retry-After header, Sonarr will backoff for at _least_ the time specified in the Retry-After header.
However, the currently logic still uses the normal exponental backoff as well, so the effective backoff becomes the greater of the two. This is undesirable because there's no reason to backoff any longer than the Retry-After header specifies.
But that's easy to fix in Sonarr.

If the download client is currently offline, then Sonarr queues the release in the pending queue. Meaning the same release can be grabbed again later once the client gets back online.
We should do the same for releases that have a 429 http response. By putting them on the pending queue, we get the same behavior as the 'temporary rejection' mentioned earlier.

Jackett and NzbHydra should sent 429 responses with sensible Retry-After headers. Some indexers reset daily, some keep track of individual grabs and decrements the counter once a particular grab is 24h old. So it's really indexer specific.
Please note that some indexers do count attempted grabs as a grab, so it's important to wait an appropriate time.

### Aggregated Indexer Feeds

Jackett's /all endpoint and NzbHydra combine releases from multiple indexers. But grabs of those release are still proxied to those individual indexers and can fail separately. However it's not possible for Sonarr to know that a particular release belongs to a separate indexer and will therefore trigger the backoff indiscriminately.
If each item in the response contains an unique identifier for the indexer, then it would become possible for Sonarr to maintain separate grab-backoffs for those as well.

### Aggregated Indexer Feeds Sorting

One important thing I've been meaning to discuss is the sorting of items in aggregated feeds.
Sonarr RssSync queries newznab apis using a 'paging' mechanism. It keeps querying for additional pages until it encounters a release with a pubdate that's older (not equal) than what Sonarr has seen before for that indexer. This allows Sonarr to catch up after downtime for up to 24u but normally only has to request one page.
For normal indexers this works fine, because new items get added to the end of the feed and never in the middle.
For aggregators this can be an issue if the backend indexers are down or have different caching intervals.
How does Jackett and NzbHydra handle that? Do releases receive a new 'pubdate' to ensure newly discovered (but slightly old) releases end up at the top of the feed? Or are such releases mixed in?
Secondly, do Jackett and NzbHydra keep a complete 'history' of recent releases and return an appropriate continuous aggregated result for the normal t=tvsearch with only category as filter?

## Discussion

Obviously dealing with all this requires actions by all parties. What do you think about the problems and solutions mentioned?
If you have other issues regarding interfacing that you wish to discuss, please let me know.

If we can come up with a plan, i'll talk to galli and qstick too so that it can be implemented in Radarr & Lidarr as well.

**Comment by garfield69** [comment]
@Taloth Sorry I cannot contribute to this topic, its completely out of my knowledge base.
If you want a Jackett perspective, more suitable contributors are @kaso17 and @flightlevel. 
I am not involved with supporting Sonarr, NzbHydra, or any of these other related projects, and my contribution to Jackett involves coding yaml indexers and basic problem solving for jackett tickets.

**Comment by Taloth** [comment]
lol, I figured I'd just ping one random [active](https://github.com/Jackett/Jackett/graphs/contributors?from=2019-01-24&to=2019-05-23&type=c) dev. Sry about that.

**Comment by theotherp** [comment]
First let me say that I welcome this discussion but am kinda surprised. I asked @markus101 last week about a related issue and he told me that you (as in the Sonarr team or him personally, I don't know) would not make any changes to support aggregators in any special way. I might have misunderstood or you may have differing views on this?

I'd support any changes to the newznab API for better support of API limits and error handling. Unfortunately even now (as you may well know) no two indexers behave the same, requiring different query parameters or not supporting certain parameter combinations or not returning certain attributes. So any changes to the API spec would even increase the pain of getting it all to work. I'm also not sure how much indexers would want to improve the use of free or limited accounts. But we sure could try.

But let me answer each point separately:
**No API usage/limit status in Newznab specification**
See above, but I'd be happy to implement this and support it in Hydra any way I can.

**Separate Query and Grab backoff counters**
In most cases it would make more sense for Hydra to return a "Try another release" header or something like that. That's the problem I wanted to address on discord last week. If one indexer is offline and Sonarr can't download the NZB it will disable Hydra even though a different NZB (from a different indexer which Sonarr can't know) may be online. It *may* be possible for Hydra to recognize download errors and automatically return a different NZB. I'll look into that.

**Aggregated Indexer Feeds**
I'm pretty sure that Hydra already returns newznab attributes that identify the indexer from which the result originated. If not, that can be added easily. Sonarr could read that and use it which might also be a solution for the problem described above.

**Aggregated Indexer Feeds Sorting**
Hydra caches all found results for a certain query for 5 minutes. If a new request with an offset but the same query is made Hydra will use all the cached results first to answer. If the number of requested results (including the offset) is higher than the number of cached results it will make a new query using an increased offset. It is possible for new results to be included in there somehow. It was a pain in the ass to get this working properly and to be honest I would be wary of making any changes in that regard. I've tried multiple times to refactor the code and always gave up. Here as well some indexers which don't behave nicely make the process far harder than necessary (also raw search engines that don't return the amount of actual results are another problem).

**Comment by Taloth** [comment]
I think views differed only slightly. We still wouldn't want to add an option to disable the back-off, for example. Nor would we want to introduce nzbhydra specific stuff. But I discussed it with markus prior to opening this Github issue because I felt there was an opportunity to improve Sonarr's backoff logic in general and, with a bit of collaboration, extend it to aggregators in general.

**Separate Query and Grab backoff counters**

Being able to track api query and grab backoffs separately is basically the linchpin of the whole mechanism. It's actually also the thing that improves Sonarr's normal usecase :smile:

Anyway, with regards to grabs, there are a few responses possible:
- **200 Found**
Should reply with the actual nzb/torrent content
- **404 Not Found**
Should be returned if the release was deleted from the origin indexer and thus permanently unavailable.
Sonarr won't disable the indexer and move on to next best release in the list.
- **429 Too Many Requests**
Should be returned if the origin indexer grab limit has been reached.
Sonarr will put the release on the pending queue to be re-evaluated later.
Sonarr will also trigger a back-off logic for the time specified in the Retry-After header, defaulting to 1 hour.
- **5xx**
Interpreted as an error with the origin indexer server.
Sonarr will trigger a back-off logic for the indexer for an exponential time.
- **Dns/client connection errors**
Detected as an issue with the user's own internet connection.
Sonarr won't disable the indexer and move on to next best release in the list.

The only thing Hydra should do is respond with http 429 and a Retry-After header. See https://tools.ietf.org/html/rfc6585#section-4
The time specified in the Retry-After header should be accurate for the indexer. When in doubt don't set it below 6h to avoid accumulating 'grabs'.
You should not try to grab an alternate .nzb from another indexer since Sonarr will do that automatically. Basically, we'd want nzbhydra to inform Sonarr that that specific indexer is currently unavailable and for how long.

**Aggregated Indexer Feeds**

Looks like hydra [does](https://github.com/theotherp/nzbhydra2/blob/96e967acfcda9cebf506c46c32635b89b08af72b/core/src/main/java/org/nzbhydra/api/NewznabXmlTransformer.java#L86) however that is a hydra specific name. So we'll have to agree on something generic so it can be used by Jackett too.
Maybe `indexerID` and `indexerName`. `indexerID` would be a unique int or string to identify the indexer in the backend, `indexerName` would be an optional attribute with a short display name that could be presented to the user (bonus points).
Sonarr will be able to associate the 429 Retry-After in the previous section to this indexerID.
We should probably wait for input from Team Jackett before making any decisions.

**Aggregated Indexer Feeds Sorting**

Yes, years ago I had a discussion with the Jackett devs too about how complicated it is. In Sonarr we use Enumerators to pull in new pages as needed.
Please note that I'm only talking about the periodic RssSync, not a search for individual episodes or seasons.

> If the number of requested results (including the offset) is higher than the number of cached results it will make a new query using an increased offset.

Not each indexer has the same page count nor the same amount of releases in a particular timespan. How are the releases sorted in the final result? Do you keep that cache per indexer?
I know, odd questions, but it really determines whether Sonarr will be able to use paging logic.

**Comment by theotherp** [comment]
The thing is, the [newznab api](https://newznab.readthedocs.io/en/latest/misc/api/#newznab-error-codes) requires indexers to always return with HTTP code 200 but a specific newznab error code. I try to return the error code by the indexer. Changing that to return different HTTP codes would be a major change. I always complain about indexers not behaving properly so I'm not sure if I would want to switch. Is that how other indexers already behave?

I'd have no problem changing the attributes that identify an indexer. I think I added them for one particular user; if he still uses those he'd just have to update his code. Using the indexer's host (e.g. dognzb.cr or nzbs.org (RIP)) may be easiest.

Aggregated results are always sorted by age. The results are cached using a hash of all newznab parameters (except offset and limit) as a cache key. When a query is made using the same parameters but with a different offset and the cache does not contain enough results all indexers involved are queried for the next 100 results as long as either the number of needed results is reached or no indexer has any results left. Unfortunately returning a correct number of total results is impossible with indexers that either don't return that value themselves (like binsearch or nzbindex) or return an invalid number (I thing dog always returns 1000 or something like that.
If new releases were added between the first query and the second that won't matter because that would only mean that the next query (say with offset 100) will return some results already known, resulting in an effective offset that is slightly lower than 100.
I have a hard time explaining this correctly, half of the time I'm not sure I understand what's going on myself...

**Comment by Taloth** [comment]
>  a specific newznab error code

That's what you would expect, but newznab indexers don't actually use the api for downloading nzbs. They use something like `site.com/getnzb/asdfasdf`.
One site (newznab based) that I tested used that url and returned 429 with a html content warning about the limit and it included retry-after: 85871.
In fact, on the same indexer if I use `t=get&id=...` it redirects to getnzb.

nZEDb [redirects](https://github.com/nZEDb/nZEDb/blob/0.x/www/pages/api.php#L218-L227) api?t=get to getnzb, so that's consistent with newznab.
nZEDb also [returns](https://github.com/nZEDb/nZEDb/blob/0.x/www/pages/api.php#L85) the newznab error 429 with a string indicating the _api_ request limit, although not the time till next request.
Finally nZEDb [returns](https://github.com/nZEDb/nZEDb/blob/0.x/www/pages/getnzb.php#L43) the newznab API error 429 for getnzb as well.
On that note, nZEDb is broken since they accidentally [started](https://github.com/nZEDb/nZEDb/commit/9ffe607a892cfa3b093e2b33bba0e7691321810a#diff-da7e32248524c5a20d3ef8f9048824e2R914) returning the newznab error codes as http status codes 2 years ago. Prior to that change nZEDb returned a 200 status code, and used 501 instead of 429 for the download limit error.
Note that nZEDb is _not_ newznab, so it's not the 'truth'.

So basically, both Sonarr and hydra must be able to handle an api error (various) but also http status code 429.
Not all newznab sites are the same, but it's probably a decent rule of thumb.

> I try to return the error code by the indexer.

So if you do that then it'll should be fine, because it would be the same as if Sonarr was talking directly to that indexer. Pass along either the newznab api error, or http status error and I'll handle it on our end.
But it obviously only applies to newznab sites. For other sites that hydra supports, you'll have to do something yourself. I have a slight preference for getting a 429 status code for getnzb, simply because it provides a well-defined method of passing along the delay time. But the newznab spec is only for the api, so we have no specification on how getnzb is supposed to behave.
So ultimately it's your choice.

> When a query is made using the same parameters but with a different offset and the cache does not contain enough results **all indexers involved are queried for the next 100 results**

That sounds like the problem I was fearing. So the cache works on the aggregate and not the individual indexer. Which means Sonarr's paging mechanism won't properly work, it's a limitation you'll have to be aware off.
To explain, imagine one indexer that has like 10 releases per hour and one indexer that has 2 releases per _day_. So indexer 1 will return 100 results covering 10 hours, and the second indexer will return 100 results covering 50 days. The first page returned to Sonarr will contain mostly releases from indexer 1, page two will contain most releases from indexer 2. So Sonarr is never going to see the 24h old releases from indexer 1, since page 2 already contained months old releases so it's never going to ask for a third page. And even if it did, it would suddenly find that page 3 contains the 10-20h old releases from indexer 1.
I do have some ideas on how to improve that, but I gathered that you're rather reluctant to touch that code again so let's just leave it at that.

> I thing dog always returns 1000 or something like that.

yes, we actually just ignore that count and keep grabbing new pages till it returns < 100 items (or till x pages are read).

**Comment by theotherp** [comment]
You're right about the NZB downloads. I don't have much time currently, but when I do I'll update the coder to improve the error handling and return codes.

I'm aware that there are some downsides to using NZBHydra as aggregator in Sonarr. I've often recommended users to add `&limit=500` or something similar to the API parameters to mitigate that somewhat. But I'm not sure I understand how caching on indexer level would change anything. I only cache per unique request, for offset and that only for five minutes. If the same query is made (without offset) all indexers are called again. If Sonarr queries Hydra every 20 minutes all releases since the last call are returned. If that's less than 100 (i.e. the default limit) the first page will always contain all new releases. If more than 100 releases were added since then (which I've investigated and never found to be the case for any indexer) then some releases might be skipped, I think? 

But feel free to elaborate on your ideas on how to improve this. If I think it would be a major improvement I might be willing to change the code there.

**Comment by Taloth** [comment]
> I don't have much time currently, but when I do I'll update the coder to improve the error handling and return codes.

I'll work simultaneously on improving the code on my end. That way we can test the behavior with hydraIndexerID until we can agree with Jackett on a permanent attribute.

> I've often recommended users to add &limit=500 or something similar to the API parameters to mitigate that somewhat.

Sonarr is [coded](https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core/Indexers/Newznab/Newznab.cs#L23) to use the `<limits default="100" max="100" />` page size in caps. Which means adding `&limit=500` adds a duplicate query parameter.
So if you [provide](https://github.com/theotherp/nzbhydra2/blob/96e967acfcda9cebf506c46c32635b89b08af72b/core/src/main/java/org/nzbhydra/api/CapsGenerator.java#L104) a different 'default' in caps, then Sonarr would follow. _Please note that caps is only cached for like 7 days and only forcibly refreshed on restart._
I can look into allowing &limit= to override the caps default, but I'd still want to limit that to the caps max, so that would require adjustments in nzbHydra too to increase that maximum.

> But feel free to elaborate on your ideas on how to improve this. If I think it would be a major improvement I might be willing to change the code there.

Very well, I'll try to keep it short.
You need a few classes:
```java
class CachedApiQuery : SearchCacheEntry
{
  string key; // based on query params, and possibly some client identifier (ip, user-agent?).
  SearchRequest originalRequest; // original request with offset=0.
  List<Result> results; // results that have been aggregated
  List<CachedIndexerQuery> indexerQueries; // List of all indexers participating in the search.
  bool hasMoreResults; // Whether any indexer is may still have more items to add to 'results'.
}

class CachedIndexerQuery
{
  object indexerRef; // Reference to the abstraction of the indexer in nzbhydra
  List<Result> originResults; // Results fetched thus far from the indexer
  int nextResultIndex = 0; // Index of the next item in 'results' to be aggregated.
  bool hasMoreResults; // Whether the origin indexer may still  have more results available.
  function FetchMore();
  function Peek()
  function Pop()
}
```

Imagine a new search comes in.  You create a CachedApiQuery with empty 'results', and a CachedIndexerQuery for each participating indexer.
The former represents the search by the api user, the later represents the underlying search to the indexer. Both retain whatever state you require to satisfy the search or provide subsequent pages.
No actual queries have been made yet.
Next you're going to satisfy the SearchRequest, by checking if the items designated by offset->limit are already available in 'results'. If so, you can return them.
If not, and `hasMoreResults` is false, then the user reached the end of the list, and you return the remaining items (or zero, if offset >= results.length).
Otherwise you need to add more items to `results`...

This is the actual 'aggregation' and the core of the algorithm. You call 'Peek()' on _each_ CachedIndexerQuery (in parallel probably), find the one that's newest, then you call Pop() on that CachedIndexerQuery alone and add it to 'results'. Rinse and repeat until you have enough items to satisfy the request, or hasMoreResults becomes false.
Peek uses nextResultIndex to return the next _unprocessed_ item in `originResults` (which includes the previous origin indexer query result). Until nextResultIndex reaches the end of the list, at which point you call FetchMore to get one more page from the origin indexer, and append all them to `originResults`. (Optionally, this logic could also filter out duplicates)
Peek/Pop/FetchMore don't need to be members of CachedIndexerQuery, but you get the idea.

The result of this is that you're doing a 'sort' on the fly by using a IEnumerable/Queue abstraction _per_ indexer. Heck, it's essentially an AsyncQueue per indexer. This should work nicely on any origin indexer that returns results sorted by pubdate.
Origin indexers that don't return by sorted pubdate (title searches perhaps?) will not work perfectly, but should still work largely the same as they do now.

This is the algorithm in a nutshell, there are going to be some edgecases for specific indexers, but that should be abstracted away by the logic that fetches the actual indexer results.

I'm looking at Searcher.java and it's already largely in place, except for line 116, where all indexers are queried indiscriminately instead of selectively. Doesn't 'IndexerSearchResult' already roughly represent CachedIndexerQuery? It'll need some slight refactoring to include the necessary loop for multiple callSearchModules calls.
But that's just after a cursory inspection of the existing logic.

**Comment by DariusIII** [comment]
NNTmux will now report requests, api limit, grabs and download limit numbers:

9cc9ffc7573658b1b21b8baab9e6c200f64be910, 7382cd026acb181094a2ccbf475d6cadba65e8b8 , a9325f93727e5f2988d194eb58d0872cdf2eaea9

**Comment by theotherp** [comment]
@Taloth Kinda forgot about this...

I'm trying to implement a better error handling. Regarding the case that the API limit for an indexer is reached you wrote I should return code 429 and a Retry-After header.  

Say user has two indexers, A with a limit and B without one. Sonarr does a search and Hydra returns a result for A and for B. It tries to download the A result, Hydra tries to download the NZB, the indexer's limit is reached and Hydra returns a 429 with a Retry-Header of, say, 4 hours. Will Sonarr try to download release B or will it pause all connections to Hydra for 4 hours?

**Comment by Taloth** [comment]
> Does NNTmux reset the hits at midnight or is it a rolling time window? 

It's a rolling window. The `<newznab:apilimits apicurrent="3" apimax="100" ...  />` element has a few attributes but some of them are behind an indexer site option for newznab since they cost an additional db query. I don't remember if nntmux has them all enabled by default.

| name               |    type|required | description | 
| -----------------| -----------| ---| -----------| 
| apicurrent         | number | yes     | Used api calls in the last 24 hours                     | 
| apimax             | number | yes     | Maximum api calls allowed in a 24 hour period| 
| grabcurrent        | number | optional| Grabs in the last 24 hours| 
| grabmax            | number | yes     | Maximum number of grabs allowed in a 24 hour period| 
| apioldesttime      | string | optional| Time of the oldest unexpired api call (RFC 2822)| 
| graboldesttime     | string | optional| Time of the oldest unexpired grab (RFC 2822)| 

Note that `apioldestttime + 24h` is the next time the user will get one new api call.

Regarding the rest, I did some work on tracking indexers separately in Sonarr back when we talked about it, but I haven't completed that, it'll come, just not yet :smile:

**Comment by theotherp** [comment]
@Taloth You wrote 
> yes, we actually just ignore that count and keep grabbing new pages till it returns < 100 items (or till x pages are read).

Just to be sure, Sonarr wouldn't mind if I ignored the limit and just returned all the cached results in a bunch? So let's say Hydra contains two indexers and both return 100 results, I just return 200 and you would accept it? The reason I ask is that this would reduce the risk of missing any results when you make an RSS call and too many new results were indexed since the last call to fit into the 100 results of the page.

**Comment by Taloth** [comment]
It'll read in all 200 results in that case. It'll affect Sonarr's ability to request additional pages, but that doesn't work properly on hydra anyway.

**Comment by kaso17** [comment]
Hi,

jackett includes a `<jackettindexer id="example">Exmaple tacker</jackettindexer>` attribute in the aggregated feeds to identify the original source. No problem to change/add  this to something generic. But aggregation indexers cause a lot of general problems (I would prefer some sync API to automatically configure indexers in sonarr, etc.))

pubdate in jackett is usually the pub date from the corresponding tracker. Some trackers don't have a pub date, in this case usually the current time is used (changes with each query). The only reliable way of avoiding missed results is to go through all results an compare the `guid` attribute.

Jackett also in general doesn't do any caching/paginating (except of a very few indexers). Jackett doesn't have a corresponding abstraction layer at this time (it just converts the query accordingly).

**Comment by Taloth** [comment]
For Jackett we generally advice to add individual indexers to Sonarr because of that reason, without a reliable order by pubdate there's going to be various issues.   
I suggest we focus on best effort there in terms of grabs (to prevent one sub-indexer failing to grab to affect the others). Coz unless Jackett can provide a better aggregation mechanism I don't think we can improve the situation for /all regarding multiple pages.   
I'm not sure if jackett does it already, but you can increase the page size for /all or simply return more releases.

> Some trackers don't have a pub date, in this case usually the current time is used (changes with each query). The only reliable way of avoiding missed results is to go through all results an compare the guid attribute.

I presume those have no consistent order either. Currently sonarr pulls in additional pages until it found the previous 'last' release, either by pubdate being less than the 'last' or the DownloadUrl being exactly the same. It would be trivial for me to add guid to the list, but that'd only fix the individual indexer feeds, not the /all (in fact, it might make /all worse).    
Adding a cache to Jackett based on guid would make that more reliable, but I suspect the number of indexer affected by this is limited.

Anyway, once I add support to Sonarr for identifying sub-indexer we'll talk about a generic element/attribute. There's little point in changing stuff now till it's actually being used.   
In my preliminary work I had a indexerKey and indexerName, the first being the important unique id and the second being human readable. So fairly similar to what you have right now.

**Comment by theotherp** [comment]
@Taloth I'm taking a look at modifying the code so that paging works as expected. I analyzed the scenario you described. Sorry if I'm being dense, I might also just have misunderstood the algorithm you described, but I don't see how it improves the paging.

To understand what's going on I made a simpler example for me with two indexers and a page size of 5 results.

Let's say this is what the indexers would return:
```
Indexer a        Indexer b
Page1
a-2019-11-23     b-2019-11-23
a-2019-11-23     b-2019-11-22
a-2019-11-23     b-2019-11-21
a-2019-11-23     b-2019-11-20
a-2019-11-23     b-2019-11-18
Page2
a-2019-11-22     b-2019-11-17
a-2019-11-22     b-2019-11-16
a-2019-11-22     b-2019-11-15
a-2019-11-22     b-2019-11-14
a-2019-11-22     b-2019-11-13
```

The current implementation would combine the first pages of both indexers and then return the first, then the second five results. Then it would query the indexers for their second pages:
```
Page 1
a-2019-11-23
b-2019-11-23
a-2019-11-23
a-2019-11-23
a-2019-11-23
Page 2
a-2019-11-23
b-2019-11-22
b-2019-11-21
b-2019-11-20
b-2019-11-18
Page 3
a-2019-11-22 (Here's the result that's suddenly newer than b-2019-11-21)
a-2019-11-22
a-2019-11-22
a-2019-11-22
a-2019-11-22
Page 4
b-2019-11-17
b-2019-11-16
b-2019-11-15
b-2019-11-14
b-2019-11-13
```

If I understood you correctly then with the new implementation I would first return page 1 of indexer a, then page 1 of indexer b, then page 2 of indexer 1, then page 2 of indexer b:
```
Page 1
a-2019-11-23
a-2019-11-23
a-2019-11-23
a-2019-11-23
a-2019-11-23
Page 2
b-2019-11-23
b-2019-11-22
b-2019-11-21
b-2019-11-20
b-2019-11-18
Page 3
a-2019-11-22 (Same problem as above)
a-2019-11-22
a-2019-11-22
a-2019-11-22
a-2019-11-22
Page 4
b-2019-11-17
b-2019-11-16
b-2019-11-15
b-2019-11-14
b-2019-11-13
```

As you can see the order of elements is still wrong. I don't see how that would help.

Thanks for the help ;-)

**Comment by Taloth** [comment]
The problem is that you're querying the two indexers, sorting the result and returning that as page 1 & 2. You should not consider a page in the result to be related to a page of the indexers.
Instead you should put the page from the individual indexers into separate queues, and pick a release from whichever queue has the youngest release.
If a queue is empty, then you fetch a new page for that indexer.

Yes, this means that you have a short-lived persistent state to maintain the queues.

Like this:

Client request page 1
- You fetch page 1 from indexer A and indexer B. You put the results in to Queue A and Queue B. each has 5 items.
- You perform a loop of 1-5 in order to fill page 1 for the client:
   - Check which queue has the youngest release on top. both are 11-23, so lets pick Queue A as default.
   - Item 1 = a-11-23. We remove that from Queue A, which now has 4 items.
   - We repeated that 4 more times. The items were all 11-23, so Queue A is empty.
- We have 5 items, so we return page 1.

Client requests page 2
- We remember that we had 5 results already for page 1, we simply repeat the loop of 1-5 for page 2:
   - Check which queue has the youngest release on top. Queue A is empty, so we fetch page 2 of the indexer.
   - Queue A now has 5 new items all 11-22. Queue B still has it's page 1 results in the queue with 11-23 on top. So that one wins.
   - Item 1 = b-11-23. We remove that from Queue B, which now has 4 items. (Queue A has 5, from indexer A page 2)
   - For item 2, check which queue has the youngest release on top. Queue A has 11-22, Queue B has 11-22 on top too. Queue A was our default if they're the same. so...
   - Item 2 = a-11-22 (Queue A now has 4 items)
   - Repeat 3 more times. We now have b-11-23, a-11-22, a-11-22, a-11-22, a-11-22. And are ready to return page 2.
- note that Queue A has only one item left, the final a-11-22 item. Queue B still has 4 items.

Client requests page 3
- We remember that we had 10 results already for page 1&2, we simply repeat the loop of 1-5 for page 3:
   - Check which queue has the youngest release on top. Queue A has one item a-11-22, Queue B has 4 items, b-11-22 is on top.
   - Item 1 = a-11-22. We remove that from Queue A, so Queue A is now empty.
   - For item 2, check which queue has the youngest release on top. Queue A is empty, so we fetch page 3 of the indexer. (your example has no page 3, so let's assume it's release from a year ago)
   - Obviously Queue B contains 4 recent items. And those are returned. Queue B is now empty.
- We've finished page 3 for the client.

Client requests page 4
- Check which queue has the youngest release on top. Queue B is empty, so we fetch page 2 of the indexer.
- One by one we discover that Queue B wins from Queue A for the next 5 items. So we can return those. Queue B is now empty again.

This entire process depends on you keep some state in memory to cache those pages. Any time someone requests page 1 you throw away the state and start over.
The state should contain:
- The entire query param of the request, except page/offset. This serves as the 'key' for the state
- The number of items already returned
- Optionally, a list of already returned (aggregated) items
- Per indexer:
  - The next page to request
  - A queue/list of unaggregated items

Note that this _also_ works if individual indexers have different page sizes. You're simply fetching additional pages as needed to ensure that the queue isn't empty and pick releases from whichever queue has the youngest item.

I can explain it differently, but then I'll have to spend time putting together an animation :)

**Comment by theotherp** [comment]
I understand it now. Thanks for being patient with me! I probably shouldn't have started this while being on sick leave ;-)

The only downside I see is that it would require more API hits for the same amount of results. Right now with two indexers configured you get two pages for one hit per indexer, with the new approach you need one hit per page. I mean, it's still as many API hits as you would need if you didn't use Hydra, so I don't really see it as a problem. It's just something my users need to be aware of.

Thanks again.

**Comment by theotherp** [comment]
I think I got it - at least there aren't unexpected "time skips" anymore. I tested with one mock indexer with 100 results per day and one with 1 per day. I'm still beta testing but hope to release the next version soon. 

Is there any way I can it works as expected wrt Sonarr?

**Comment by Taloth** [comment]
if you want to test it with Sonarr, set one indexer on hydra's end to have far far less categories, it'll run behind.
Then with trace level logs in Sonarr you can see it pull in multiple pages. This should be visible on a season level search coz sonarr sends that out as a single query.

**Comment by markus101** [comment]
Pretty sure this has been dealt with now at least on the *arr side.
