### ISSUE TITLE
Season Pass: Monitor Latest Season

### ISSUE THREAD

**Issue by antigravity83** [Sonarr/Sonarr#3133]
**Describe the bug**
When selecting "Monitor Latest Season" in Season Pass, it monitors the season, but the episodes themselves remain unmonitored. 

I've tried selecting "Monitor All", then "Latest Season" but it still unmonitors the latest season. 

Seems to happen on some, no all TV Series. 

**Screenshots**
![image](https://user-images.githubusercontent.com/27241813/58241969-4867c180-7d91-11e9-8d4b-201660e55b1e.png)

 - Sonarr Version: 3.0.1.500
 - Operating System: Ubuntu 18.04
 - .Mono version: 5.20.1.19

**Comment by markus101** [comment]
Ahh forgot about https://github.com/Sonarr/Sonarr/issues/826 this isn't a bug, it's expect if the season ended more than 90 days ago, which is why it happened for some, but not all series.

**Comment by antigravity83** [comment]
Hi @markus101 I think i've found a related issue to the "Monitor Latest Season" 

It seems when selecting this option - it doesn't monitor episodes that have yet to air yet. 

So for example - I have Batwoman added, and "Monitor Latest Season" selected across my library, and whilst it's monitoring the season - it isn't monitoring the individual episode. 

As a result, I've had a bunch of new series not get picked up over the past few weeks

![image](https://user-images.githubusercontent.com/27241813/60579964-86f88f00-9dc7-11e9-97c5-e1848feb92d5.png)

Sonarr Version: 3.0.1.527
Operating System: Ubuntu 18.04
.Mono version: 5.20.1.19

**Comment by antigravity83** [comment]
Here's another one I've found - The Politician (2019)

![image](https://user-images.githubusercontent.com/27241813/60580082-caeb9400-9dc7-11e9-9aee-09d238757b20.png)
