### ISSUE TITLE
Streaming (downloading sequentially)

### ISSUE THREAD

**Issue by WhiteOnBlackCode** [Sonarr/Sonarr#3136]
## Feature Request
Add a button that will toggle torrent-client's "sequential download mode" for an ongoing torrent
and open the video file in a preferred (or hardcoded) video player.

### What problem are you looking to solve?
When one wants to watch a fresh episode he usually will use Sonarr to acquire the torrent magnet,
then manually set download to sequential mode and open the video file in a player,
this process may be automatized to minimize user tinkering and maximize satisfaction.

### Other Information
The button may be placed _instead_ of the two buttons: "Automatic & Manual search".
Or as an alternative - next to them once the download has already been started.

**Comment by markus101** [comment]
No plans for such an options.
