### ISSUE TITLE
Support custom patterns for download destination folder

### ISSUE THREAD

**Issue by tommyalatalo** [Sonarr/Sonarr#3138]
**Describe the problem**
Sonarr doesn't support setting a custom download directory path, such as /tv/seed/<series title>/season <XX>/. Instead the default directory of the download client is used.

This is a flaw in the case of long term seeding, because in that case it would be beneficial to keep the /seed/ directory structured as explained above, instead of just dropping everything in the same directory. The use case is to download to /tv/seed/<series title>/season <XX> and then hardlink to /tv/library/<series title>/series <XX>... with a custom naming scheme.

**Describe any solutions you think might work**
There should be a setting somewhere in the UI where you set up "Download Root Path" and then in the "Renaming" section define the folder structure naming scheme just as the renaming for files works now. So if "Download Root Path" is set to "/seed/" and we define the structure as "{series title}/season {NN}/" then the path "/seed/{series title}/season {NN}/" would be sent as the download path to the download client instead of whatever the default path is for the client.

Flexget does exactly this and it's a very useful feature currently missing from sonarr.

**Comment by markus101** [comment]
Due the complications of supporting this for all clients as well as dealing with RAR releases/upgrades/etc this is not something we're planning to support. We'd be interested in a root folder based download directory for seeding files and allowing hard links into the series folder.

If you want this exact behaviour a Custom Script when a release is sent to the download client would be your best path forward.
