### ISSUE TITLE
Delete button on mass edit page off screen.

### ISSUE THREAD

**Issue by cjaustin1792** [Sonarr/Sonarr#3142]
**Describe the bug**
When viewing the mass edit page and you have selected a few series to delete, the delete button is off the screen. I only noticed I could do this because I accidentally zoomed out.

**Screenshots**
[Screenshot](https://imgur.com/a/mQgUkI3)

**System Information**

 - Sonarr Version: 3.0.1.500 linuxserver docker
 - Operating System: 18.04 ubuntu
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
 - OS: Windows
 - Browser: Chrome
 - Version: 74.0.3729.169 (Official Build) (64-bit)

**Comment by markus101** [comment]
What resolution is your browser window?

**Comment by cjaustin1792** [comment]
> What resolution is your browser window?

Unsure how to check this...

**Comment by markus101** [comment]
What's the resolution of your monitor in Windows? And is your browser window the full screen width?

**Comment by cjaustin1792** [comment]
1280x800 13.3 Macbook Pro
