### ISSUE TITLE
Function to edit series/metadata

### ISSUE THREAD

**Issue by FunkenTom** [Sonarr/Sonarr#3143]
**Describe the problem**
It happened sometimes, that the information at thetvdb is not fully accurate or not fully usable for automatic scraping.
* So, sometimes there is a series called "The King's Avatar", but the tracker has it only listed as "The Kings Avatar" and can't find it.
* Also it occurs sometimes, that sonarr only knows about episode 1-11, but 12 is already available to download.

The last case can be solved by contributing to thetvdb, but the first one is really annoying.
It basically means that I need to do everything by hand.

**Describe any solutions you think might work**
It would be great if the user would be able, to edit the metadata of a series.
Stuff, that I would like to edit:
* Name and search aliases (**IMPORTNAT**)
* Adding/Editing (add absolute number) of separate episodes

**Comment by markus101** [comment]
The FAQ has an entry on how to deal with alternate names (we maintain a list). We have no plans for metadata editing.

**Comment by FunkenTom** [comment]
@markus101 
Could you please add a link to that FAQ entry?

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/wiki/FAQ#why-cant-sonarr-import-episode-files-for-series-x--why-cant-sonarr-find-releases-for-series-x

**Comment by FunkenTom** [comment]
@markus101 

- Add anime, use TheXEM for that
Its a closed/invite only community. I can submit anything there.
