### ISSUE TITLE
Sonarr uses the year as season number

### ISSUE THREAD

**Issue by devIlluSioN** [Sonarr/Sonarr#3144]
**Describe the bug**
When I try to do a manual search on the Chernobyl series I do not get any results. After a whireshark analysis I realize that the request is false.
Sonarr uses the year as season number and air date as episode number.
But with other TV Show like The 100 its work great

**Screenshots**
Wireshark Http request to jackett for Chernobyl Serie ERROR
![Chernobyl](https://user-images.githubusercontent.com/35778025/58753875-5b337200-84c6-11e9-90d8-c914c1814857.PNG)
Wireshark Http request to jackett for The100 Serie GOOD
![the100](https://user-images.githubusercontent.com/35778025/58753883-730af600-84c6-11e9-9420-3f5826d79ef5.PNG)

**System Information**

 - Sonarr Version: lasted
 - Operating System: W7

**Comment by Taloth** [comment]
Not a bug. You accidentally set the series to Daily format instead of Standard.

But kudos for investigating it yourself. :smile:
