### ISSUE TITLE
Naming of episodes when doing manual import is incorrect

### ISSUE THREAD

**Issue by smoothrunnings** [Sonarr/Sonarr#3146]
**Describe the bug**
For some reason at some point Sonarr as work correctly but has stopped working correctly. When episodes have more than one episode in it Sonarr changes the E to a "-" which doesn't work on the latest Plex Server for Windows, so I have to go in and manually change it back to an E# and refresh my Plex before the second episode appears.

**Comment by markus101** [comment]
Hangs the multi-episode naming style.
