### ISSUE TITLE
Jeopardy episodes not pulling from Jackett/IPT

### ISSUE THREAD

**Issue by joshedgarva** [Sonarr/Sonarr#3148]
**Describe the bug**
I have Sonarr properly pointed to Jackett which points to IPT. This is tested working as it pulls most other shows, but it is not properly pulling Jeopardy. It appears that Sonarr looks for Jeopardy by year and episode number (e.g. 2019x110) while IPT and pretty much every other torrent site I'm finding have it listed by air date since there are so many episodes (e.g. 2019 06 05).  I'm assuming this mismatch is why Sonarr is not pulling the episodes.

EDIT: For reasons I don't understand, Wheel of Fortune seems to be fine. Same mismatch exists though.

**Screenshots**
Self-explanatory file/torrent name discrepancy

**System Information**

 - Sonarr Version:  2.0.0.5322
 - Operating System: CentOS 7
 - .net Framework (Windows) or mono (macOS/Linux) Version: Uncertain but probably not applicable

**Comment by markus101** [comment]
Please use the forums for support/questions.

Change the series type to Daily to search/match by date instead of season + episode number.
