### ISSUE TITLE
TVDB Data in other Languages

### ISSUE THREAD

**Issue by TheUltimateC0der** [Sonarr/Sonarr#3150]
Currently sonarr gets the information for series by using sonarrs skyhook, which calls thetvdb. The problem is that the skyhook only requests content in english from TVDB, but there are shows that do not exist in other languages/translations. 

In SonarrV3 there is the `Language Profile` setting which could be used to determine the language code you need to send to the skyhook. Also it should be possible to fallback to english if there is no entry for the selected language.

This is effectively the same as https://github.com/Sonarr/Sonarr/issues/269
Since the issue is locked, and there is still no progress since 2015, ill open a new one.

**Comment by Taloth** [comment]
And since the situation has not changed, nor the reason for locking the discussion in 269. I'll close this one too. (wtf did you expect).
Support for other languages will come when we're ready for it, and not before, regardless of how much ppl push for it.

**Comment by TheUltimateC0der** [comment]
To answer your question in the same manner you asked it: I expected to be fucking done after 4 years.
