### ISSUE TITLE
Bad Request (Invalid host) when accessing Sonarr via hostname instead of IP

### ISSUE THREAD

**Issue by glc650** [Sonarr/Sonarr#3151]
**Describe the bug**
I have Sonarr installed on a 2018 Mac Mini with VLANs setup under macOS (so multi-homed).  I have one of the IPs from the VLANs setup in Settings > General > Bind Address.  When I access Sonarr via this IP everything is fine but when I try to access via a hostname that resolves to that same IP I get the following error:

Bad Request (Invalid host)

**To Reproduce**
1. Try accessing Sonarr via hostname instead of IP from any browser/client (I've tried Safari, Chrome & FF on macOS/Win 10 & Safari & FF on iOS).

**Expected behavior**
The hostname resolves to the IP specified in Sonarr's settings so I would expect it to work the same as when I access via IP.

**Desktop (please complete the following information):**
 - Mono Version: 5.20.1.19; installed on the Mac Mini where Sonarr is installed
 - Browser: Safari/Chrome/Firefox
 - Version: latest versions of all 3

**Comment by markus101** [comment]
The bind address binds the webserver to that address, but still listens on all IPs, this is not something we're going to be able to address until we switch web servers. At this time it's best not to use the bind address and use a firewall to prevent access on other interfaces.
