### ISSUE TITLE
Sonar ignores file size on collection or "internal" torrents

### ISSUE THREAD

**Issue by Unravelled1986** [Sonarr/Sonarr#3152]
**Describe the bug**
Sonarr ignores the file size on collection torrent (e.g. more than 1 file, s03, ...) and proper torrents (e.g. proper, internal, ...).

Examples:

Designated Survivor [S03] (2019) WEBRip 720p | Kerob --> 1,5 GB/ep. ; limit is 500MB
The 100 S06E05 iNTERNAL 720p WEB h264-BAMBOOZLE [eztv] --> 757MB ; limit is 500MB

**Screenshots**

![2019-06-07 20_06_56-The 100 - Sonarr](https://user-images.githubusercontent.com/1793611/59124409-d4681480-895f-11e9-8e60-6f59cb5671e2.png)
![2019-06-07 19_53_18-Settings - Sonarr](https://user-images.githubusercontent.com/1793611/59124411-d500ab00-895f-11e9-96c2-aec4b3e8f784.png)
![2019-06-07 19_52_51-Settings - Sonarr](https://user-images.githubusercontent.com/1793611/59124412-d500ab00-895f-11e9-99ba-ac48d0248a8b.png)
![2019-06-07 20_10_15-Settings - Sonarr](https://user-images.githubusercontent.com/1793611/59124560-55271080-8960-11e9-9bb7-7dfddd8bdac0.png)

**Logs**

[sonarr.3.txt](https://github.com/Sonarr/Sonarr/files/3267118/sonarr.3.txt)
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/3267119/sonarr.txt)

**System Information**

 - DSM : 6.2.2-24922
 - Sonarr version : 2.0.0.5322
- Mono Version : 5.18.0.240

**Additional context**

Running Sonarr on a synology NAS with Jackett also running on the nas?
Should I restrict the internal, ... tags on Indexers > Restrictions?
How does Sonarr handle the case where the file size is not in the feed?

**Comment by Taloth** [comment]
> How does Sonarr handle the case where the file size is not in the feed?

If it's not in the feed then sonarr can't make decisions based on it.

Best is to enable trace level logs in Settings->General. It'll contain more details about the information sonarr has and the decisions it makes.

**Comment by Unravelled1986** [comment]
I'v updated my settings, will update the issue when I get another case.

Found the source of both cases. Both came from Jacket and have the correct size in Jackett. The size is correctly reported to Sonarr, which ignores it for some reason. Maybe because it's downloading a revision? On the manual download tab it ends up being rejected.

Getting more info right now is difficult as Sonarr doesn't keep the file sizes in the response for the history tab.

Sidenote: I can't disallow zero sizes on Torznab indexers.

![2019-06-07 20_42_13-The 100 - Sonarr](https://user-images.githubusercontent.com/1793611/59126320-18114d00-8965-11e9-8504-530412807930.png)

**Comment by markus101** [comment]
The total size limit for a season pack is runtime * (episode count + 2) the +2 comes from the allowed double episode length for the premiere and the finale.

The runtime Sonarr has for The 100 will determine the total limit. Offhand I don’t recall if maximum size is only limited to Usenet, but the tooltip should specify.

**Comment by Taloth** [comment]
He's using the global maximum size, so episode count etc doesn't matter.
The global maximum applies to both usenet and torrent. It's simply dependent on the indexer reporting the correct size.

**Comment by markus101** [comment]
>  The size is correctly reported to Sonarr, which ignores it for some reason.

Was it correctly reported when Sonarr actually grabbed it? If the size is 0 then Sonarr will log `Release has unknown size, skipping size check.` in the debug logs, but the info level logs aren't adequate.

If the size is greater than 0 then Sonarr will log `Checking if release meets maximum size requirements. 768.1MB` (where the size is the actual size and proceed to check it).

Without debug logs (or as Taloth suggested Trace logs) from when Sonarr grabbed the release there is nothing we can investigate, of course if the indexer doesn't report the size accurately then that's an issue we cannot address.

**Comment by Unravelled1986** [comment]
Got another case 

iZombie.S05E07.720p.HDTV.x264-SVA[eztv] > 871,1 MB

Attached are the debug and trace log files.

[sonarr.trace.7.txt](https://github.com/Sonarr/Sonarr/files/3289347/sonarr.trace.7.txt)
[sonarr.debug.3.txt](https://github.com/Sonarr/Sonarr/files/3289348/sonarr.debug.3.txt)

![2019-06-14 08_46_12-Calendar - Sonarr](https://user-images.githubusercontent.com/1793611/59488862-f93d1a00-8e80-11e9-9654-b0e9e024960a.png)

Which all boils down to

> 19-6-14 03:13:27.3|Debug|DownloadDecisionMaker|Processing release 'iZombie S05E07 720p HDTV x264-SVA [eztv]' from 'Jackett'
19-6-14 03:13:27.3|Debug|Parser|Parsing string 'iZombie S05E07 720p HDTV x264-SVA [eztv]'
19-6-14 03:13:27.3|Debug|Parser|Episode Parsed. iZombie - S05E07 
19-6-14 03:13:27.3|Debug|Parser|Language parsed: English
19-6-14 03:13:27.3|Debug|QualityParser|Trying to parse quality for iZombie S05E07 720p HDTV x264-SVA [eztv]
19-6-14 03:13:27.3|Debug|Parser|Quality parsed: HDTV-720p v1
19-6-14 03:13:27.3|Debug|Parser|Release Group parsed: SVA
19-6-14 03:13:27.3|Debug|AlreadyImportedSpecification|Performing alerady imported check on report
19-6-14 03:13:27.3|Debug|AlreadyImportedSpecification|Skipping already imported check for episode without file
19-6-14 03:13:27.3|Debug|AcceptableSizeSpecification|Beginning size check for: iZombie S05E07 720p HDTV x264-SVA [eztv]
**19-6-14 03:13:27.3|Debug|AcceptableSizeSpecification|Release has unknown size, skipping size check.**
**19-6-14 03:13:27.3|Debug|MaximumSizeSpecification|Release has unknown size, skipping size check.**
19-6-14 03:13:27.3|Debug|LanguageSpecification|Checking if report meets language requirements. English
19-6-14 03:13:27.3|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: iZombie S05E07 720p HDTV x264-SVA [eztv]
19-6-14 03:13:27.3|Debug|ReleaseRestrictionsSpecification|[iZombie S05E07 720p HDTV x264-SVA [eztv]] No restrictions apply, allowing
19-6-14 03:13:27.3|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. HDTV-720p v1
19-6-14 03:13:27.3|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
19-6-14 03:13:27.3|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
19-6-14 03:13:27.3|Debug|DelaySpecification|Profile does not require a waiting period before download for Torrent.
19-6-14 03:13:27.3|Debug|HistorySpecification|Performing history status check on report
19-6-14 03:13:27.3|Debug|HistorySpecification|Checking current status of episode [22545] in history
19-6-14 03:13:27.3|Debug|DownloadDecisionMaker|Release accepted

Is there any way to ignore zero sizes? If not then I guess I gotta figure out which trackers is reporting the zero sizes.

Thank you for you're time and then this can be closed.

Thanks!

**Comment by markus101** [comment]
No plans to have a feature that ignores 0 byte files.

> 'iZombie S05E07 720p HDTV x264-SVA [eztv]' from 'Jackett'

You could add each indexer as it's own indexer in Sonarr or check the debug logs for the grab event (which wasn't in either log file you linked) as it might have a URL. Otherwise Jackett might have something in it's logs/history (if it has history).

**Comment by markus101** [comment]
Closing since this is an indexer issue.
