### ISSUE TITLE
Skyhook can't find series ID 167231 although it is available on thetvdb with english title

### ISSUE THREAD

**Issue by heikobornholdt** [Sonarr/Sonarr#3154]
**Describe the bug**
I want to add the series "Die Pfefferkörner" and therefore searched for "tvdb:167231" in Sonarr. However, it is not found. The series exists in [TheTVDB](https://www.thetvdb.com/series/167231) and also has an English title.

**Logs**
`````
[Trace] HttpClient: Req: [GET] http://skyhook.sonarr.tv/v1/tvdb/shows/en/167231
[Trace] ConfigService: Using default config value for 'proxyenabled' defaultValue:'False'
[Trace] HttpClient: Res: [GET] http://skyhook.sonarr.tv/v1/tvdb/shows/en/167231: 404.NotFound
{"message":"NotFound","description":"thetvdb.com does not have a series with the tvdbid 167231, it may have been removed."} (75 ms)
`````

**System Information**

 - Sonarr Version: 2.0.0.5322
 - Operating System: Ubuntu 18.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.19

**Comment by M0UL** [comment]
that probaly has to with that the english episode tittles  are missing. sonarr only support English tvdb data.

**Comment by markus101** [comment]
Some previous TVDB API issues marked it as deleted and we had to nuke the cache for it. It's good now on my end.
