### ISSUE TITLE
Not displaying manual search results

### ISSUE THREAD

**Issue by antigravity83** [Sonarr/Sonarr#3155]
**Describe the bug**
Sonarr doesn't display results of manual search, for single episode or season packs. 

**Screenshots**
![Screenshot_20190609-080712](https://user-images.githubusercontent.com/27241813/59152765-78e87480-8a8e-11e9-90d1-39be6aaa554a.png)

**Logs**
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/3268962/sonarr.debug.txt)

**System Information**
 - Sonarr Version: 3.0.1.506
 - Operating System: Ubuntu 18.04 
 - .mono (macOS/Linux) Version: 5.20.1.19

**Comment by antigravity83** [comment]
This occurs in both Chrome in Windows and Chrome in Android Mobile 74.0.3729.157

**Comment by markus101** [comment]
Have you tried another browser or incognito mode? Based on the logs the API response was successful and the UI will only show an error if the search request failed with a non-200 status code.

The response for the search is a 200 response: `19-6-9 08:00:13.2|Debug|Api|[GET] /api/v3/release?episodeId=11906: 200.OK (142184 ms)`

**Comment by antigravity83** [comment]
Yeah I thought the same. Happens on desktop Chrome at home and at work. I cleared full cache/cookies etc and still occured. 

Could it be related to the number of indexers? Although the search component seems to work ok

**Comment by markus101** [comment]
It did take over 2 minutes to respond, if you're using a reverse proxy it could be killing it before it actually responds.

Try another browser and check the network tab in the browser, given Sonarr is responding correctly this doesn't look like a bug. Closing, but we can reopen if there is something actionable.
