### ISSUE TITLE
Option to allow some tolerance before disabling indexer

### ISSUE THREAD

**Issue by jwvanderbeck** [Sonarr/Sonarr#3156]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

## Feature Request
An option to set some sort of tolerance on timeout/failure of an indexer before disabling the index.

### What problem are you looking to solve?
Often indexers are unreliable, sometimes down or sending bad data for periods of time.  It would be nice to have an option set some sort of tolerance value before the indexer is automatically disabled.

**Comment by markus101** [comment]
This is already what Sonarr does. The indexers are disabled for 5 minutes to start, up to 24 hours if they fail repeatedly.

**Comment by jwvanderbeck** [comment]
I think you misunderstand.  The  feature request was for options to control this.

**Comment by markus101** [comment]
We have no plans to make the backoff escalation customizable.
