### ISSUE TITLE
Non-Sequential Multi-Episode

### ISSUE THREAD

**Issue by W-Floyd** [Sonarr/Sonarr#3157]
I have multi-episode files that include non-sequential episodes (e.g episodes 1 + 7).

Might there be a way to allow specifying this? At present, naming them `s01e01+07` is the same as `s01e01-07`, while I would propose that  `s01e01+07` should include only 01 and 07, while `s01e01-07` should interpolate 01, 02, 03 etc.

I understand this isn't an ideal situation, and I'd much rather have split files, but this is the original airing order.

**Comment by thezoggy** [comment]
there are multiple multi-episode format. it sounds like you should be using Duplicate or Repeat
wher you'd end up with: `S01E01E07` / `S01E01.S01E07`

**Comment by markus101** [comment]
This is not a format Sonarr supports and not one we plan to support. The only work around is to split them into separate files.
