### ISSUE TITLE
Can't have empty category for qBittorrent

### ISSUE THREAD

**Issue by slokomisu** [Sonarr/Sonarr#3158]
**Describe the bug**
Before version 3.0.1.507, you were able to leave the Category field in the qBittorrent settings empty. Now there you get an error saying 

"Can not contain '\', '//', or start/end with '/'"

**Screenshots**
![image](https://user-images.githubusercontent.com/16639892/59170955-6f025800-8b06-11e9-833d-d4160e9a41d9.png)

**Logs**
Link to debug or trace log files.
Corresponding validation error message in logs

![image](https://user-images.githubusercontent.com/16639892/59171001-9822e880-8b06-11e9-9672-e3acb5ef98af.png)

**System Information**

 - Sonarr Version: 3.0.1.508
 - Operating System: Debian Docker Container (using [linuxserver/sonarr:preview](https://github.com/linuxserver/docker-sonarr) container)
 - mono (macOS/Linux) Version: 5.20.1.19

**UI Bugs:**
N/A

**Additional context**
I'm not that familiar with Sonarr's codebase but from a glance at the commit that added support for post-import labels, it seems that this issue is related to this check.

https://github.com/Sonarr/Sonarr/blob/39ea2dd32fe4a5d192e8393c06324a813d1db567/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs#L15

**Comment by markus101** [comment]
@Taloth @jtpavlock definitely related to that change, but we should also write a cleaner validator for this, does something as simple as `^.*?[\/\\].*?$` not work?

**Comment by jtpavlock** [comment]
My fault, I forgot to test for an empty string. Changing the regex to `^$|^[^/\\\\](((?!//)[^\\\\])*[^/\\\\])?$` will fix it (added `^$|` to beginning).

Your solution won't match empty string either btw. [It also will match things we don't want](https://regex101.com/r/6rhkcP/1)

**Comment by markus101** [comment]
Would a custom validator make more sense? It's be more verbose, but it'd be a lot more clean, especially if we want to extend this in the future.

**Comment by jtpavlock** [comment]
Clean for who though? It's a readable (with the help message) one-liner that's easily accessible for debugging. 

To me a custom validator seems like overkill if it only shows up twice in the codebase (both in one location). If we are worried about being extensible (not sure why it would arise), then we might want to also look at writing custom validators for all the download client's category regex requirements

**Comment by markus101** [comment]
Clean for a developer that actually has to debug what it's validating. It's a pretty convoluted regex overall because it's checking for the absence of certain strings. While `^$` works, it's strange to look at.

In this case this seems pretty relevant: https://xkcd.com/1171/

**Comment by jtpavlock** [comment]
My apologies, I think I misunderstood you and assumed you meant to just put that regex behind a method call. Breaking it up would help determining what case exactly is being tested if needed. Up to you if you are worried about needed to deal with it later. If you want, I can try to simplify it down tomorrow, but I’m not optimistic.

Is there a way to specify and inverse matching rule? Or perhaps negate a regex match? Instead a regex for what we want, in this case it would be easier to have a regex for what we don’t want.

**Comment by jtpavlock** [comment]
Not sure why I didn’t look this up earlier as it would have saved me some headache, [but here’s what qBittorrent uses for their category checking](https://github.com/qbittorrent/qBittorrent/blob/6f6033cf1c5273d868231fa2e7c42e3de2ce468d/src/base/bittorrent/session.cpp#L657)

**Comment by Taloth** [comment]
The qbit regex is convoluted too. Back when I reviewed the PR I didn't want to bother with cleaning it up,... I never learn.

`^[^\\\/](\/?[^\\\/])*$` with a separate empty check or `^([^\\\/](\/?[^\\\/])*)?$` with the empty check embedded.
I opted for the embedded one coz imo it's still readable enough.
