### ISSUE TITLE
Episode count wrong - Sonarr reports 9/9 but should be 9/10

### ISSUE THREAD

**Issue by dkids** [Sonarr/Sonarr#3160]
I had this happen with the same show but season 3.   I updated that season before realizing I should leave things as-is for help debugging.

Anyway, Sonarr clearly knows that the 8th episode of Season 2 there but is not showing it in the total.

![Screen Shot 2019-06-08 at 8 39 25 AM](https://user-images.githubusercontent.com/30055574/59299772-58611b80-8c42-11e9-9805-1d6aa331eac9.png)

This is with the current version running on a Mac.   

Version
    2.0.0.5322
Mono Version
    5.20.1.19
AppData directory
    /Users/kids/.config/NzbDrone
Startup directory
    /Applications/Sonarr.app/Contents/MacOS

**Comment by markus101** [comment]
To be counted the episode needs to have an episode file _or_ it must be monitored and have already aired. In your case you have 9 files with episodes and 0 episodes monitored, so 9/9 is the correct count. In v3 there will be additional information shown when hovering the `9/9`, but the same rules apply.
