### ISSUE TITLE
"Folder chmod mode" setting not applied when moving series

### ISSUE THREAD

**Issue by jobrien2001** [Sonarr/Sonarr#3161]
**Describe the bug**
I have "Folder chmod mode" set to 777, and works as intended in automation.  But if i decide to edit a series, change its folder, and choose to let Sonarr move the files, folder permissions of the new folders will be 755.

**Logs**
19-6-12 12:34:46.5|Info|MoveSeriesService|Moving Test Series from '/media.tv/Test Series' to '/media.tv.old/Test Series'

**System Information**
 - Sonarr Version: 3.0.1.513
 - Operating System: UNRAID OS

**Comment by markus101** [comment]
Please fill out the entire bug template.

**Comment by jobrien2001** [comment]
Done, thank you.

**Comment by jobrien2001** [comment]
Also, want to add that this bug also shows on files going to the recycle bin.  Folders in the recycle bin default to 755 and files to 644.

**Comment by markus101** [comment]
Not sure that's really a bug, the intent was only to apply it when importing to the series folder, moving whole series is new, but the recycle bin has never had that functionality.

**Comment by jobrien2001** [comment]
I was expecting the original permissions of the folder and files would be retained when sonarr is moving files around.

As it stands, if i move a series through the interface then i have to run a terminal and chmod after.

**Comment by Taloth** [comment]
Don't set chmod/chown in Sonarr it's only there to workaround bad setups, just use umask. A process umask specifies the default permission for new files&folders.
I have no idea what how the unraid package is configured so you'll have to figure out where to change the umask. Our systemd [unit defaults to 002](https://github.com/Sonarr/Sonarr/blob/phantom-develop/distribution/debian/sonarr.service#L8), which means 775. So unraid probably uses a different startup config.

**Comment by jobrien2001** [comment]
I see, i run the linuxserver docker so perhaps i will look for more info there.  Thanks for your explanation.
