### ISSUE TITLE
Feature Request: Two-factor authentication (2FA)

### ISSUE THREAD

**Issue by 475392689485** [Sonarr/Sonarr#3164]
**Describe the problem**
It would be nice to be able to enable 2FA for additional security when I your server is acessable from a public ip.

**Describe any solutions you think might work**
Let me enable TOTP additional to basic or advanced authentication.

**Comment by markus101** [comment]
We do not have plans to support 2 factor authentication at this time. Tagging for re-consideration in the future.

**Comment by chamaelion** [comment]
@markus101 - any chance this can get revisited?

**Comment by bakerboy448** [comment]
More than likely won't be done anytime in the near future at all.

auth on sonarr is really just a something is better than nothing case.

Its recommend  to use a reverse proxy of sorts with auth or some type of more proven/vetted auth for public *arr access.

**Comment by ZoltrixGFC** [comment]
Any updates?

**Comment by Mathpro** [comment]
Since the Authentication has been recently enforced, would it not make sence to add a multi-factor auth now?
