### ISSUE TITLE
Remote Path Mapping Host name is case sensitive

### ISSUE THREAD

**Issue by DilatoryCheetah** [Sonarr/Sonarr#3169]
**Describe the bug**
The Host name specified for Remote Path Mapping is case sensitive.  If the download client host has a different case, then completed files are not processed, i.e.: ds1019 vs. DS1019

**Screenshots**
![Download client - Host](https://user-images.githubusercontent.com/20565777/59548645-13b9d680-8f07-11e9-8f90-1737974610b9.png)
![Remote Path Mappings](https://user-images.githubusercontent.com/20565777/59548646-161c3080-8f07-11e9-8cc6-98d1e0e7769c.png)

**Logs**
There were no entries in the sonarr.txt files referencing any remote path mapping errors.

**System Information**

 - Sonarr Version: 0.2.0.1344
 - Operating System: Windows 10
 - .net Framework (Windows)

**UI Bugs:**
 - OS: Windows 10
 - Browser: chrome
 - Version: 75.0.3770.90

**Additional context**
There were no log entries to help me troubleshoot the issue.  I was able to discover the solution by random chance.

**Comment by markus101** [comment]
Please fill out all the requested information when opening an issue.

**Comment by DilatoryCheetah** [comment]
I have updated the issue with all of the information
