### ISSUE TITLE
[REQ] Bulk indexers import from Jackett

### ISSUE THREAD

**Issue by backsofangels** [Sonarr/Sonarr#3170]
**Feature description**
Import of indexers from Jackett after a file creation, to avoid the addition of every indexer manually.

**Possible solution**
The workflow would be similar to this one, already have posted the request on the Jackett repo:

- Add indexers to Jackett
- Hit the "Export indexers list" in Jackett
- Creation of a JSON file readable by Sonarr/Radarr
- Hit the "Import indexers from file" button in Sonarr/Radarr

**Comment by Taloth** [comment]
We have absolutely no plans to implement any kind of import function for this. Sonarr has an api which you can use, which third-party apps can use if they so desire.

PS: it's fairly bad form to just spam github issues in every project.

**Comment by hadim** [comment]
Would you be able to reconsider this feature?

As said in https://github.com/Jackett/Jackett/issues/5493#issuecomment-573713503, a structured file format is better as it is not tied to any software specification and could be reused in multiple projects.

**Comment by hadim** [comment]
According to a Jackett contributor, using the API directly in Jackett could be an option: https://github.com/Jackett/Jackett/issues/5493#issuecomment-573729775

**Comment by Thundernerd** [comment]
If you enable advanced settings then you can set the API Path for your torznab indexer to `/torznab/all/api`. This allows Sonarr to send only one query to Jackett instead of multiple separate ones.

![image](https://user-images.githubusercontent.com/5531467/72738939-ee7afe00-3ba2-11ea-9795-cd8165cf33ef.png)
