### ISSUE TITLE
Episode search searching for all episodes not the specific episode

### ISSUE THREAD

**Issue by henrywhitaker3** [Sonarr/Sonarr#3172]
**Describe the bug**
When searching for an individual episode, results for the whole show come up. Seems like it is just searching for the show name instead of showname + season/episode number

**Screenshots**
Screenshot is taken when searching for S08E01, but the exact same search results show up for any episode searched.

![sonarr v3 search bug](https://user-images.githubusercontent.com/36062479/59554639-75c11d00-8f95-11e9-89b6-ba5730e186b1.png)

**Logs**
```
19-6-15 18:43:12.0|Info|NzbSearchService|Searching 1 indexers for [Taskmaster : S08E01]
19-6-15 18:43:12.2|Info|DownloadDecisionMaker|Processing 32 releases
```

**System Information**

 - Sonarr Version: 3.0.1.514
 - Operating System: Debian 9
 - mono Version: 5.20.1.19

**Additional context**
The search function worked fine until updating from version 3.0.0.348 to 3.0.1.514

**Comment by henrywhitaker3** [comment]
Just updated sonarr to version 3.0.1.517 and the issue is still there

**Comment by markus101** [comment]
It's not. The debug logs will show exactly what query Sonarr sent to the indexer. Looks like Jackett is returning other results.

Post the debug logs as requested...

**Comment by henrywhitaker3** [comment]
```
19-6-15 18:54:21.5|Debug|Torznab|Downloading Feed http://10.0.0.7:9117/torznab/all/api?t=tvsearch&cat=5030,5040,100041,100005,100071,100075,100007,5000,100128,100006,100152,2000,100207,100505,100208,100201,100205,2040&extended=1&apikey=(removed)&offset=0&limit=1000&imdbid=tt4934214&season=8&ep=1
```

**Comment by markus101** [comment]
> &imdbid=tt4934214&season=8&ep=1

Sonarr is limiting the search to season 8 episode 1, Jackett is returning other results.

**Comment by henrywhitaker3** [comment]
Right, not convinced this is a jackett issue, I've just downgraded sonarr to version 3.0.1.351 and the results come back correct from Jackett. Debug log from version 3.0.1.351:
```
19-6-15 19:08:46.0|Debug|Torznab|Downloading Feed http://10.0.0.7:9117/torznab/all/api?t=tvsearch&cat=5030,5040,100041,100005,100071,100075,100007,5000,100128,100006,100152,2000,100207,100505,100208,100201,100205,2040&extended=1&apikey=(removed)&offset=0&limit=1000&q=Taskmaster&season=8&ep=1
```

Issue seems to be the newer version querying with the GET parameter `imdbid=tt4934214` instead of using `q=Taskmaster`

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/issues/3104 - Jakett advertises it supports IMDB ID, but it doesn't search correctly when it does.

**Comment by henrywhitaker3** [comment]
There any way to force the newest version to not use the IMDB ID? Could a toggle in advanced settings for the indexer be implemented maybe?

**Comment by Taloth** [comment]
You're probably on an outdated Jackett version.

**Comment by henrywhitaker3** [comment]
Jackett is at the current version

**Comment by Taloth** [comment]
There's no such thing as 'current version', specify the exact version. Jackett reported it fixed via https://github.com/Jackett/Jackett/commit/f86e8dd5b60ee71012e8d1b75eea7a057d3b2997 back in may.

**Comment by henrywhitaker3** [comment]
I'm on  Jackett Version 0.11.420.0, the latest release (from 5 days ago), output of Jackett updater logs:

Jun 18, 2019 05:50:01 PM | Info | Checked for a updated release but none was found. Current: v0.11.420 Latest: v0.11.420
-- | -- | --

**Comment by Taloth** [comment]
Restart sonarr.

**Comment by henrywhitaker3** [comment]
Seems like it's working for some shows and not for others, even though they use the same indexer in sonarr:

```
19-6-15 19:04:21.5|Debug|Torznab|Downloading Feed http://10.0.0.7:9117/torznab/all/api?t=tvsearch&cat=5030,5040,100041,100005,100071,100075,100007,5000,100128,100006,100152,2000,100207,100505,100208,100201,100205,2040&extended=1&apikey=(removed)&offset=0&limit=1000&imdbid=tt4934214&season=8&ep=1
...
19-6-18 19:05:10.8|Debug|Torznab|Downloading Feed http://10.0.0.7:9117/torznab/all/api?t=tvsearch&cat=5030,5040,100041,100005,100071,100075,100007,5000,100128,100006,100152,2000,100207,100505,100208,100201,100205,2040&extended=1&apikey=(removed)&offset=0&limit=1000&q=Celebrity%20Juice&season=21&ep=6
```

**Comment by Taloth** [comment]
Looks fine to me, the first line is from 3 days ago.
