### ISSUE TITLE
Sonarr not showing latest season of tv series

### ISSUE THREAD

**Issue by twisted-fire-starter** [Sonarr/Sonarr#3174]
i have attached a screenshot of a tv series i have set to download and i know its on season 19 but for some reason sonarr wont update it to season 19 it only shows the episodes as season 18 which mean i have to change the downloaded episode to the 1 thats listed it is running on my synology nas and i have updated it to the latest stable version of sonarr ther version im running is 2.0.0.5322 - Mar 25 2019 and the other bug with it is its no longer removing completed torrents from transmission

**Comment by markus101** [comment]
Please use the template when filing issues.

> i have attached a screenshot

Must be invisible...

**Comment by markus101** [comment]
We can re-open when more information is available.

**Comment by twisted-fire-starter** [comment]
what template n i filled in what the issue is

**Comment by twisted-fire-starter** [comment]
i have changed the issue to look right i think

**Comment by markus101** [comment]
Sonarr gets it's show information from TheTVDB (as mentioned in the FAQ), they don't have a season 19 listed and the series is locked, you'll probably need to reach out on their forums.

In the future please use our forums or subreddit for support questions (or one of other support channels we have).

**Comment by Taloth** [comment]
Asked TheXEM mods to update the mapping: http://thexem.de/xem/show/4688

**Comment by twisted-fire-starter** [comment]
@Taloth how do i ask them to update it plz pal ?

@markus101  ok i must of missed that bit in the FAQ thanks again.
