### ISSUE TITLE
Can't start Sonarr on armv5

### ISSUE THREAD

**Issue by ricebus** [Sonarr/Sonarr#3176]
**Describe the bug**
Sonarr doesn't start

**Logs**
https://gist.github.com/ricebus/67bd0477f8f95d25a5f654c20ebb52a8

**System Information**

 - Sonarr Version: 3.0.1.497
 - Operating System: Linux
 - Mono Linux Version: 5.20.1.27

**Comment by markus101** [comment]
Looks like issues with mono (unable to get the processor architecture) and SQLite (System.EntryPointNotFoundException: sqlite3_config).

Neither of these look like a bug with Sonarr directly, mono has limited support for arm in general and the fact that it's armv5 is doing it no favours.
