### ISSUE TITLE
Title slug 'sanctuary' is in use by series 'Sanctuary'

### ISSUE THREAD

**Issue by Aszar** [Sonarr/Sonarr#3179]
**Describe the bug**
Title slug 'sanctuary' is in use by series 'Sanctuary'

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: [e.g. 2.0.0.1] 2.0.0.5322
 - Operating System: [e.g. Windows 10] Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12] 4.7.2

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

Two different series with the same name, Sanctuary. Can't add both. 

sanctuary-2007 VS sanctuary-2019

**Comment by markus101** [comment]
Not a bug, if they have the same series they will end up with the same slug, but since TheTVDB doesn't allow duplicate titles, the 2019 series should be renamed to include the year.
