### ISSUE TITLE
Ability to specify Base URL with an environment variable

### ISSUE THREAD

**Issue by StFS** [Sonarr/Sonarr#3184]
I’m putting together a comprehensive set of services for my HTPC needs, these include Sonarr, Radarr, Deluge and more. I’m doing this using docker-compose.

As I’m starting multiple services that all have web UIs, I want to start an nginx reverse proxy as well that would simplify the way these web UIs are accessed, so instead of htpc-server:8989 for sonarr and htpc-server:7878 for radarr, I could simply go to htpc-server/sonarr and htpcs-server/radarr.

However, that means that I would have to configure the URL Base in the configuration file before starting the sonarr container. This is a bit of a hazzle (having to do some config file editing magic every time before the container start to make sure that the config option in config.xml matches the correct base url).

A much simpler solution would be if I could start the container up with an environment variable that specifies the URL base string.

I would imagine that this would be as simple as “if environment variable SONARR_URL_BASE is set, use that, otherwise fall back to old behavior of reading the config file”.

**Comment by markus101** [comment]
We don’t have plans to support environment variables for config values.
