### ISSUE TITLE
Sonarr Crashing in few minutes

### ISSUE THREAD

**Issue by M3rofio** [Sonarr/Sonarr#3185]
**Describe the bug**
Sonarr Crashing within minutes

**Screenshots**

**Logs**
Link to debug or trace log files.

[sonarr crash.txt](https://github.com/Sonarr/Sonarr/files/3336596/sonarr.crash.txt)
[sonarr log.txt](https://github.com/Sonarr/Sonarr/files/3336597/sonarr.log.txt)
**System Information**

 - Sonarr Version: [ 2.0.0.5322]
 - Operating System: DSM Version  : DSM 6.2.2-24922
- System : Synology Model : DS3617xs
CPU : INTEL Xeon D-1527
RAM : 48 GB
 - Mono Version : 5.18.0.240

**UI Bugs:**
 - OS: [Windows 10 ]
 - Browser: [ chrome ]
 - Version: [ 75.0.3770.100 (Official Build) (64-bit) ]

**Additional context**
I installed Sonarr three time and did fresh installation same problem

**Comment by markus101** [comment]
I don’t see anything in the logs that indicates Sonarr is crashing, but the logs are filled with permission issues.

Trace logs may reveal something worthy, but if mono is crashing Sonarr’s log files won’t have anything useful. Capturing the standard output and error may though.

That error wouldn’t cause Sonarr to crash it’s a red herring.

Please use the forums or subreddit for support/troubleshooting device specific issues.
