### ISSUE TITLE
WEBMux treated as HDTV

### ISSUE THREAD

**Issue by samta0** [Sonarr/Sonarr#3186]
**Describe the bug**

There are files containing the keyword "webmux" and different resolutions. 

For example:
https://nzbindex.com/search/?q=webmux&max=250&minage=&maxage=&hidespam=1&hidepassword=0&sort=agedesc&minsize=500&maxsize=&complete=1&hidecross=0&hasNFO=0&poster=

The bug:
sonarr v3 however applies the hdtv quality to them, messing up the quality priority system. 

Thus, could you add the webmux-480p, webmux-720p, webmux-1080p and webmux-2160p quality definitions to sonar, so that they can be used in the web* quality profiles? 

**System Information**

Version    3.0.1.522
Package Version    3.0.1.522-ls93 by linuxserver.io
Mono Version    5.20.1.19

Thanks

**Comment by markus101** [comment]
Webmux has never been detected as a quality in Sonarr and with v3 there is webrip and web DL, which is applicable here?

**Comment by Taloth** [comment]
Used almost exclusively by NovaRip in Italian releases. Anyway, x264 so WEBRip. (h264 would be WEB-DL)
