### ISSUE TITLE
Media Info column for episodes on Series Details

### ISSUE THREAD

**Issue by samta0** [Sonarr/Sonarr#3189]
**Describe the bug**

When a video file contains multiple audio tracks in different languages, only one language is shown in the Series page. The problem probably is not due to mediainfo, as the renamer uses more than one language. 

Could you enhance sonarr to show all the languages? You might combine the encoding and the language for each audio track and put the default track in the first position. 

Thanks in advance. 

Here a screenshot of the Views page (have a look at episode 4): 
![audio language info not complete in view](https://user-images.githubusercontent.com/44927859/60398746-3df0d280-9b5c-11e9-8900-314186d8a336.png)

Here a screenshot of the mediainfo window taken of the corresponding episode 4 file: 
![audio language info not complete mediainfo](https://user-images.githubusercontent.com/44927859/60398759-624caf00-9b5c-11e9-8bd3-8ef9fb0bac26.png)

**System Information**

Version: 3.0.1.522
Package Version: 3.0.1.522-ls93 by linuxserver.io
Mono Version: 5.20.1.19

mediainfo version: 17.12-1

**Comment by markus101** [comment]
The language is unrelated to the language of the audio tracks, it’s solely based on the release/file name. Media info contains the language track information.

A separate column for the track languages is probably doable though.

**Comment by samta0** [comment]
I wonder what use case there is for the language information based on the filename. 

Considering that you seem to want to keep the column with the language information based on the filename, I would be glad to have an additional column based on the audio tracks identified by mediainfo, specifying for each track the format and the language. 

By the way, I have on my ToDo list a point to ask for the addition of a column for the subtitle languages. It should however not only take into account the subtitles embedded in the file, but also the subtitles available as separate files next to the video file. (They should also somehow be marked as embedded or not when listed in the new subtitles column.) Do you want me to file a separate feature request for the new subtitle column?

**Comment by markus101** [comment]
Language is the single language Sonarr has detected as the language for the file, currently that is from the file name only, eventually it could be expanded to include media info and maybe multiple languages, but that is a significant overhaul.

Thinking about this further + the subtitles one, I don't think these are great ideas for columms, it's far too easy to have way too much information to display (some releases have 10+ subs), we already show all media info in the episode modal, probably better to pull that into it's own column as well that will show a tooltip with all the info. We have plans to include the extra files that are linked to the episode in the episode modal, I'm not sure that we'll ever see those are part of the table, it's not great tabular information.

PS you don't need to prefix with `v3 xyz:`, that's in the template and v3 (or later) is the only version they're going to be fixed in anyways.

**Comment by samta0** [comment]
I see what you mean and I realize, that it is in fact an issue of a clean layout vs displaying more pieces of information. 

The episode modal does not suit my use case: for a given series, I would like to have an overview to see the available audio and subtitle languages at least for a whole season. Having to perform an action for each episode to see that information is what I would like to avoid. 

What about the following idea: There already is an "Expand all" button on the overview page of a given tv show. What about renaming that button to "Expand all seasons" and add an additional button "Expand language information"? This way, it would be possible to keep the layout for a tv show the way it is and make the additional information available for who would like to see it. 

Expanding the language information would: 
- Add the two columns for the additional audio and subtitle information (I am assuming that you would like to keep the column of the language information derived from the filename)
- Dynamically compute the height of each episode box to accommodate for all the languages. The default language would be on top, the other languages would follow in alphabetical order, one language+format per line. 

You might have a better idea for the layout of the additional language information... 

What do you think about the additional "Expand language information" button? Could it be an idea that you would implement?

**Comment by markus101** [comment]
I don’t see how a different button changes anything, it just crams more stuff into a place it won’t be able to fit in many cases, IMO it’s just a convoluted way to do it as well.

**Comment by samta0** [comment]
The aim was to satisfy both categories of users: 
- those wanting a simple layout with few pieces of information
- those with big screens looking for more pieces of information 

Maybe a last tentative on the subject: what about taking the approach already used on the series page showing the list with all series? There is an "Options" button opening a modal where the user can choose the columns to display. 

In any case, thanks for all the responsivness you have already provided.

**Comment by markus101** [comment]
Options already exist, it’s just not elevated to the toolbar as it applies to the episode table only, use the cog (gear) icon above the actions in the table itself to control the columns.

My concern was less about adding it as I knew it wouldn’t always be visible, but could still take up way too much room.

**Comment by samta0** [comment]
You are right about the Options already existing in the scope of a season. I forgot about it, when writing the last message. 

That said, I might have an idea to make sure that the audio/subtitle do not randomly take up to much room: make sonarr not show all the available languages. The user first configures a set of languages he is interested in and sonarr than uses the information in this set to only display the availability of the languages the user is interested in. I suppose for most multi language users, it will be a set with two languages. 

This set of "user wanted languages" might also be useful for later enhancements; I am particularly thinking at already available feature requests about improving the renamer to also support non english filenames.

**Comment by winklevos** [comment]
This would be most useful when you have anime which has x language subtitles but different audio language, you can't see if it is dual audio unless you go into each media info
