### ISSUE TITLE
Default audio language information is not added to EAC3 tracks

### ISSUE THREAD

**Issue by samta0** [Sonarr/Sonarr#3190]
**Describe the bug**

The renamer in my sonarr v3 installation is configured to use {MediaInfo.Full}. I noticed that the audio language information is missing for EAC3 tracks. 
![audio language info omitted on eac3 tracks](https://user-images.githubusercontent.com/44927859/60399807-d68e4f00-9b6a-11e9-8575-09b2374cfa72.png)

In fact, the underlined substring in the filename should be: h264.EAC3[EN].[EN] (The second bracket contains the subtitle languages)

The problem does not occur for AC3 tracks. 

Could you have a look? 

Thanks in advance. 

============================================================

System Information

Version: 3.0.1.522
Package Version: 3.0.1.522-ls93 by linuxserver.io
Mono Version: 5.20.1.19

mediainfo version: 17.12-1

**Comment by Taloth** [comment]
That's by design, it omits the English audio tag since it's considered default and plastering it on every single download isn't particularly useful. There's no configuration option to control this behavior.

**Comment by samta0** [comment]
sonarr omitting a default language was unexpected. I am now wondering how it behaves on non-english systems; but that is more a retorical question, as my system is in english. 

The behaviour might also be a bit inconsistent, compared to the default language non being omitted for the subtitles. But I am getting that it is not omitted for subtitles, as there would not be anything indicating the presence of the default language subtitle. You might indicate the format of the subtitle and omit the language to make the behaviour consistent with the audio language. 

In any case, I would appreciate having a configuration option to disable/enable the omission of the default language, as I would disable the omission of the default language.
