### ISSUE TITLE
Manual Import failed – Missing season

### ISSUE THREAD

**Issue by vdubus** [Sonarr/Sonarr#3192]
**Describe the bug**
Sonarr automatically start a download, but was unable to import it automatically.
Reason: "Unable to parse file".

I tried to manually import it, but it also failed.
Reason: "Season must be chosen for each selected file".

Yet, there isn't any way for me to select this season…

Ever Sonarr is missing a mean to select the Series, the Season and the Episode to which the file should be imported. Or there is a bug which block this action.

**Screenshots**
![](https://framapic.org/JzF1Yhn0q04Y/BhwbUL1eNAFi)
![](https://framapic.org/QO16vhpjwf2T/Pd9SpOZaF7Dq)
![](https://framapic.org/ldzjmYwrGq0y/u1Hrg9uoPqhf)

**System Information**

 - Sonarr Version: 2.0.0.5322
 - Operating System: FreeNAS
 - mono Version: 5.10.1.57

**UI Bugs:**
 - OS: Windows
 - Browser: Firefox
 - Version: 68.0b14 (64 bits)

**Comment by markus101** [comment]
Not a bug, click under the season column, this behaviour is improved in v3.
