### ISSUE TITLE
Can't add certificate or private key (Broken Mono version 5.20.1.19)

### ISSUE THREAD

**Issue by russianbot1776** [Sonarr/Sonarr#3194]
**Describe the bug**
I am following the guide at https://github.com/Sonarr/Sonarr/wiki/SSL and when I try to use httcfg to import the key I get an error that the platform is not supported. This appears to be related to https://github.com/mono/mono/issues/14152 where Mono version 5.20.1.19 is broken. This is the same Mono version in my sonarr Docker build. I am filing this as a notice to try to get a newer mono version when available. 

```
$ docker exec -it sonarr httpcfg -add -port 9898 -pvk /config/domain.pvk -cert /config/domain.crt
error loading certificate or private key [Operation is not supported on this platform.]
Usage is:
        httpcfg -add -port NN [-cert CERT -pvk PVK] [-p12 P12 -pwd PASSWORD]
        httpcfg -del -port NN
        httpcfg -list

$ docker exec -it sonarr mono --version
Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 09:02:17 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

**Comment by markus101** [comment]
Sonarr doesn't use a specific mono version and we don't maintain a docker image, you'll have to reach out to the docker image maintainers.

**Comment by russianbot1776** [comment]
Thanks for letting me know. I filed an issue in the appropriate place.
