### ISSUE TITLE
2FA issues on an DSM dedicated account without 2FA

### ISSUE THREAD

**Issue by Nemrod7** [Sonarr/Sonarr#3195]
**Describe the bug**
I use Sonarr on a Nas Synology DS916+. Wanting to secure my NAS I activated the 2FA but I realized that Sonarr is not compatible.

So I created a second DSM account dedicated to Sonarr & Infuse, called Multimedia. First problem, if I stop Sonarr from the Administrator DSM account, I can't start or run it from the Multimedia DSM account.

Second problem, Sonarr displays, whatever the account, the message related to the 2FA.

Surprisingly, when creating the Multimedia DSM user, I didn't have to configure Sonarr, the configuration seems to have been taken from the Administrator account.

**Screenshots**
N/A

**Logs**
http://pasted.co/6301f0e8

**System Information**

 - Sonarr Version: 2.0.0.5322
 - Operating System: DSM 6.2.2-24922 
 - mono (macOS/Linux) Version: 5.18.0.240

**UI Bugs:**
 - OS: [e.g. Windows] macOS 10.14.5
 - Browser: [e.g. chrome, firefox] Safari
 - Version: [e.g. 22] 12.1.1

**Additional context**
N/A

**Comment by markus101** [comment]
Sonarr runs as a sonarr user on DSM and is part of sc-media. 2FA on your account will only prevent Sonarr from connecting to the torrent/usenet download clients if you’re telling Sonarr to connect with the 2FA account.

Which user Sonarr runs as is determined by the Synology package which is not maintained by use

**Comment by Nemrod7** [comment]
My point is that I would to use an account without any 2FA

**Comment by markus101** [comment]
That’s not something we control.

**Comment by Nemrod7** [comment]
Ok.

Do you know who to contact ? Thanks
