### ISSUE TITLE
Netflix Shows: Timezone PST or EST

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#3196]
2nd time I've seen this happen.. sonarr adjusts show airdate to be hours in the future which invalidates season packs from being grabbed. (tvdb says 3am, sonarr says 5am) but actual show came out at 2am (central). 

**System Information**

 - Sonarr Version:  2.0.0.5337
 - Operating System: Windows 7

![sonarr](http://zoggy.net/firefox_2019-07-04_03-10-29.png)
--
![sonarr2](http://zoggy.net/firefox_2019-07-04_03-17-27.png)

**Comment by markus101** [comment]
This sounds like a time or time zone issue with that show, what air time is it set to on TheTVDB.

IIRC skyhook is set to use PST for Netflix shows.

**Comment by thezoggy** [comment]
```
[03:07am] <_zoggy_> !skyhook stranger things
[03:07am] <XemBot> < Show: Stranger Things (Adventure, Drama, Fantasy, Horror, Mystery) :: Premiered: 2016-07-15 :: Runtime: 50 mins :: Airtime: 3:30 (Netflix) :: Status: Continuing :: TVRage: 15119 :: TVDB: 305288 :: TVMaze: 2993 :: IMDB: tt4574334 >
```
```
[03:07am] <_zoggy_> !tvdb stranger things
[03:07am] <XemBot> < Show: Stranger Things (Adventure | Drama | Fantasy | Horror | Mystery) :: Premiered: 2016-07-15 :: Airtime: Friday at 3:00 AM (Netflix) :: Status: Continuing :: URL: http://thetvdb.com/?tab=series&id=305288 :: TV.COM: -N/A- >
```

**Comment by markus101** [comment]
Looks like the east coast people think they’re more important and have set the show to 3am, instead of 12am which makes Skyhook treat it as 3am PST.

This is a data problem with TheTVDB since Netflix is definitely releasing in PST and things will continue to have issues as long as time time is wrong, but if all shows are wrong in this way we can fix it in Skyhook and as long as the trend continues they’ll be correct.

**Comment by markus101** [comment]
They’re showing as 3am in Sonarr for me, not 3:30.

**Comment by thezoggy** [comment]
yeah, this has been a long outastanding issue with netflix shows and tvdb. i thought you guys standardized/fixed it internally to be 2am local / 2am pst?

**Comment by markus101** [comment]
Everything is normalized to UTC and Netflix is set to US/Pacific for the timezone which results in everything being set to 3am PST , 5am CST and 6am EST. I've changed Netflix back to Eastern so the times will be correct now.

**Comment by markus101** [comment]
After talking with Taloth and digging into the issue a bit more I've reverted the change back to Pacific and posted on their forums to try and determine which timezone they want to follow https://forums.thetvdb.com/viewtopic.php?f=41&t=56973

If they decide EST we'll need to update Skyhook to use US/Eastern for the timezone and any shows that are wrong will need to be updated, if they decide PST we'll leave Skyhook as-is and the shows will need to be updated.

**Comment by markus101** [comment]
Switched to EST per their plans.
