### ISSUE TITLE
Add Series filter for Wanted/Cutoff Unmet

### ISSUE THREAD

**Issue by uchagani** [Sonarr/Sonarr#3198]
**Describe the problem**
As a Sonarr user
I would like to see only certain series that are wanted or have their cutoff unmet
So that I can search for only one series at a time.

**Describe any solutions you think might work**
* Add a select list on the Wanted page under both tabs(Missing and Cutoff Unmet).  
* The select list on the Missing tab should contain a list of all the series that have missing episodes.
* The select list on the Cutoff Unmet tab should contain a list of all the series that have episodes that haven't reached the cutoff.
* Selecting a series in the select list should filter the results on the page to only show the selected series.

**Comment by markus101** [comment]
Closing in favour of https://github.com/Sonarr/Sonarr/issues/3657
