### ISSUE TITLE
kodi metadata filename inconsistency

### ISSUE THREAD

**Issue by samta0** [Sonarr/Sonarr#3201]
![kodi metadata filename inconsistency](https://user-images.githubusercontent.com/44927859/61046411-5626e400-a3dd-11e9-9d0d-1897d64baea0.png)

As you can see from the screenshot, the string/substring "season" sometimes start with a lowercase s and sometimes with an upper case s. 

Moreover, it assumes that the season directory is of the format Season##, though the user has the possibility to change the name of the season directory, as there is a corresponding setting under Settings->Media Management. 

Thus, what about using the "Season Folder Format" string defined by the user in Settings->Media Management as a prefix for the filenames used for the kodi metadata?

**System Information**

Version: 3.0.1.527
Package Version: 3.0.1.522-ls93 by linuxserver.io
Mono Version: 5.20.1.19

mediainfo version: 17.12-1

Thanks

**Comment by markus101** [comment]
> As you can see from the screenshot, the string/substring "season" sometimes start with a lowercase s and sometimes with an upper case s.

Because they're two different things, `Season##` is used as a folder example, `season##` is part of the expected filename from Kodi.

> Thus, what about using the "Season Folder Format" string defined by the user in Settings->Media Management as a prefix for the filenames used for the kodi metadata?

I don't see this being viable as the user can turn season folders on/off at at per-series level and also add it as part of the episode naming format. I think the two options are:

1. Do nothing
2. Chang the example to exclude the `Season##\` since it's always going to exactly match the episode file's path

**Comment by samta0** [comment]
You are using season##-poster.jpg for posters of the seasons; however, you are using season-specials-poster.jpg for the specials. It would be more consistant if you also made it possible to use season-##-poster.jpg for the seasons, as Kodi understands this format. (same for the banner files) 

By the way, Kodi understands season-## also as name for the seasons folder. 

I don't know how flexible Kodi is with the pattern recognition of the name of the metadata files. But could you add the possibility to put a "-" between the word "season" and the season number, considering that it is recognized by Kodi?

Thanks in advance.

**Comment by markus101** [comment]
> You are using season##-poster.jpg for posters of the seasons; however, you are using season-specials-poster.jpg for the specials. It would be more consistant if you also made it possible to use season-##-poster.jpg for the seasons, as Kodi understands this format. (same for the banner files)

We're basing it off their docs, https://kodi.wiki/view/TV-Show_artwork unless there is a compelling reason to change I don't see the effort of migrating/dealing with duplicates worth it.

> I don't know how flexible Kodi is with the pattern recognition of the name of the metadata files. But could you add the possibility to put a "-" between the word "season" and the season number, considering that it is recognized by Kodi?

Again this is based off their docs, but we're not going to change the format to add a dash even if that's something they support unless there is a compelling reason to do so.

I'm going to update the episode metadata/image help text to `<filename>.nfo` and `<filename>-thumb.jpg` respectively, but have no plans to change anything else at this time.

**Comment by samta0** [comment]
You cannot simply change the format, as it would mess up the library of the people already using sonarr for some time. You have to leave the default as it is, otherwise, you are going to mess up the people's libraries with the new episodes ending up in a different season directory than the previous episodes. 

That's why I asked to create the option to add the dash. The default however has to remain as it is now. 

Actually, I wanted to migrate to sonarr as Media Manager. 

But considering that sonarr uses different filenames for the metadata and season folders, I have the choice between editing my current library to make it match with sonarr's filenames or continue to use the previous Media Manager... 

In any case, thanks for all the replies and help you have provided.
