### ISSUE TITLE
Addition to #269: Make filename and metadata language selection automatic

### ISSUE THREAD

**Issue by samta0** [Sonarr/Sonarr#3202]
**Describe the problem**

First, I am aware of issue #269. 

Comment 4 in the #269 thread asks to make the language selection available on the series level. That would be a fixed language chosen by the user for each series. What about going to the episode level and making the language selection automatic? 

**Describe any solutions you think might work**

Let the user indicate a set of languages with priorities that he is interested in. 

sonarr looks at the audio language in the file and if it corresponds to one of the languages in the user defined set, it uses the audio language with the highest priority for the metadata and for the filenames. If the audio language does not correspond to any language in the user defined set of languages, it uses a fallback language indicated by the user for the non-matching case. 

The **priority** definition in the set of the user chosen languages is necessary for the case where more than one audio language matches the languages in the set of languages defined by the user. 

**Additional context**

There is no need (except maybe for clarity) to give the user the explicit choice between fixed and automatic language selection. In fact, an **empty user language set**, would have the fallback language be used for each file, as no audio language matches a language in the user language set, since this is empty. 

I did not wait for #269 to be solved before posting this request to avoid having somebody implement a fixed language selection and later spend again time on it to make it automatic. The automatic selection might get implemented right away.

**Comment by markus101** [comment]
The point of #269 is to allow the user to select the language of series/episode information they'll see in the Sonarr UI, that would extend to metadata files created by Sonarr because the user has selected a specific language.

We have no plans to automate this at an episode level, it'd be the user's chosen language at the series level that would apply.

**Comment by samta0** [comment]
So, if I get you right, the language used for the series in the UI will also be used in the metadata and the filenames. (I was also assuming that it was the case, when I wrote this request). 

Further, I am assuming, that in most cases, the user will set the language for the metadata and filenames to be the same as the audio language of the file. (Of course, in the case of multiple audio languages, some method is necessary to pick one of the audio languages; hence the user defined ordered language set.) 

That's why I proposed to have it done automatically. That way, most language selection would be done without the need of user interaction. This does not prevent the user from changing the language of the wrongly mapped files. 

If you are not convinced, that automatically choosing the language would be helpful to the user, please, next to the series language, let the user also choose the language for each season, as the case of having seasons in different languages might be common, as dubbed versions tend to be broadcasted at a later time.

**Comment by markus101** [comment]
The fact that dubbed releases come out later has no impact on Sonarr fetching the metadata for the UI/metadata files. We're not going to allow setting the language at another level (season or episode), it'll be set at the series level and fetched as it is now, one request for the series and all it's episodes.

#269 is about two things

1. Allowing non-English series to be added without forcing users to add English series/episode information to TheTVDB
2. Selecting the language for information in the UI

If you want to have metadata files matching the language information of the file that would be better suited as a custom script that can create the relevant files after Sonarr imports the file.

**Comment by samta0** [comment]
Thanks for the explanations. I am probably considering sonarr to much like a media manager.
