### ISSUE TITLE
Cache parsed releases to a database to avoid wasting time on parsing them again

### ISSUE THREAD

**Issue by Abdulla060** [Sonarr/Sonarr#3203]
**Describe the problem**
I have a relatively low-powered pc that im using as an HTPC with Sonarr a few other programs.
I have setup Sonarr with 4 Indexers with each indexer yielding around 100 entries every time Sonarr does an RSS sync. the problem is that every entry requires about 1 second to be processed and with the 4 indexers that take quite a while to finish parsing the 400-ish entries from all of the indexers.

Another problem that im facing (although this one is a bit personal) is that sometimes the internet goes down for a while and on other times I have to turn off the HTPC for a few days. surly Sonarr will miss any releases that appear during this time. so I decided to set up an RSS feed cache using Python and Heroku. now if something happens I can simply add my cache as an index and let Sonarr search through it for anything that it might have missed. but again due to the large size of the cache, the parsing process takes a really LONG time to finish. even though most of the releases had already been parsed and searched before and doing that again is a just a massive waste of time.

**Describe any solutions you think might work**
My solution for this parsing problem is to simply store the results to a file and use the hash of the torrent as a unique identifier. so that in the future Sonarr could simply pull the results that it needs from the file instead of going through the slow parsing process.

**Comment by markus101** [comment]
There are several issues with this, the first being Sonarr may not know the series/season/episode(s) the release belongs to. Sonarr will still need to process each release to see if anything has changed.

There is also this issue for caching, mainly for failed download handling, but it's still valid. https://github.com/Sonarr/Sonarr/issues/422

**Comment by Abdulla060** [comment]
Ok, how about instead of using the torrent hash, take the raw data of that torrent directly from the RSS feed and hash it (excluding the number of seeders, leechers, comments...etc since those change very frequently and do not require parsing) then use that. this way if a new let's say episode comes in the RSS feed. you just need to hash its info and look for it in the hash DB. then if the hash matches you are guaranteed to have the correct information in the DB. and at the end just update the DB with the new seeds and leech numbers and you are done. this solves both of the aforementioned problems.

and as for how long does it take to actually do the hashing and searching, I did a little test:
1) I created fake data to hash (100 entries with each entry being 1 megabyte in size)
2) hashed all of them and using MD5 and added the hashes to a file
3) created 1000000 random MD5 hashes and added those to the file as well (to simulate a really filled up DB)
4) took my 100 entries again and hashed them again (to simulate that the same data is showing up again in the RSS feed)
5) using 2 for loops I looked for the hashes in the DB
6) the total time to find all the hashes was only 11.9 seconds

in a real-life scenario, the whole thing should take less than a second.

I think that implementing this in Sonarr is worth it even if it ends up re-processing all of the data (which is extremely unlikely) since the performance gain will rather substantial.

now the question is do you want to process each release more than 50 times while it passes through the feed or do you want to at least have a chance of only processing it once.
