### ISSUE TITLE
Not moving file when importing

### ISSUE THREAD

**Issue by khorchanov** [Sonarr/Sonarr#3204]
**Describe the bug**
When importing from download manager, I think that Sonarr is always trying to copy files (even when we specify that a move should be done) and even manually importing.

I noticed that it fails with a _Not enough free space_ when importing a file of 3Gb and available free space of 2G and choosing to move the file.

PS: I can move the file manually (via _mv) with the same situation

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 2.0.0.5322
 - Operating System: debian via docker
 - .net Framework (Windows) or mono (macOS/Linux) Version: mono 5.20.1.19

**Comment by markus101** [comment]
That's going to depend on the download client (seeding torrents will not move) and whether the move is happening on the same volume within the container if it's not Sonarr will often make a copy and move that to avoid issues with incomplete transfers, especially if SMB shares are involved.

Neither of the cases above are something we're going to invest time in resolving when space is that limited.
