### ISSUE TITLE
Sonarr : Depends: libmediainfo0v5 (>= 0.7.52) but it is not installable (V3)

### ISSUE THREAD

**Issue by Haggian** [Sonarr/Sonarr#3205]
Sonarr version 3.0.1.526 (Trying to upgrade from 2.0.0.5322)
Mono version 5.2.0.215
Debian 8 Jessie (ReadyNAS OS 6.10.1)
Hello all, I am trying to upgrade my Sonarr to v3 and running into this problem on my ReadyNAS OS 6 (Debian 8)
sonarr : Depends: libmediainfo0v5 (>= 0.7.52) but it is not installable

I have reached out to the people at Mediainfo and they have responded that Sonarr V3 package for Debian 8 needs to be revised to look for libmediainfo0 instead of libmediainfo0v5 (Debian 9)

Can you guys fix this so I can install?
Thanks!

**Comment by Taloth** [comment]
Yes, I was aware of it after reading (presumably your) post elsewhere.

**Comment by Haggian** [comment]
Ok cool, does that mean you guys will edit the package dependency?

**Comment by Taloth** [comment]
It should be fine now with Sonarr 3.0.2.x. Please close the issue once it's confirmed.

**Comment by Haggian** [comment]
Yes can confirm I was able to install with 3.0.2.x.  Thanks!
