### ISSUE TITLE
Rename "Root Folder" to "Library Folder"

### ISSUE THREAD

**Issue by tommyalatalo** [Sonarr/Sonarr#3207]
# What problem are you looking to solve?
The naming of folders in Sonarr is confusing, the name "Root Folder" doesn't explain what folder is referred to. Is it the download clients' root folder? The system root folder? Or the library root folder? Of course this is stated on the "Import" page, that it is in fact what everyone else calls the "Library Folder" which is intended.

Pretty much all other media solutions such as Plex, Kodi, Emby etc use the term "library" since it clearly explains what's intended. Sonarr should do the same for consistency and to minimize confusion on this topic (confusing download folder with "root folder") which is commonly seen in the support chat on Discord.

Add to this the fact that the Sonarr UI actually refers to "the library" in other circumstances, such as when adding an existing series to sonarr, the user gets the response "Already in your library".

# What is the proposed solution?
Rename "Root Folder" to "Library Folder". This is a small thing, but it will make is easier for new users to understand what sonarr is expecting as input, will be consistent with other media software, and makes the UI terminology more internally consistent.

**Comment by Taloth** [comment]
As Markus already explained on discord, there's always going to be users misinterpreting certain terms and renaming it from Root to Library isn't going to magically solve that problem.
We've has the same issue with other terms in the application and rarely have a clear solution for it.

There are a few things we've talked about in the past to more gently guide the user through this, such as minimize the reliance on mentioning those root folders in general. Such as asking the user to pick a series folder to put the series in and add the series folder name right there in the UI to show what it's gonna be, thus making it more visual.
But we're not going to track that here.
