### ISSUE TITLE
Import is not smart enough

### ISSUE THREAD

**Issue by springjools** [Sonarr/Sonarr#3208]
**Describe the bug**
Import only scans current folder and not the whole file path for deciding series name. Should be smarter or let user pick series. Here an example where game of Thrones is detected as A Season with Notre Dame Football, just because there is a season 1 subfolder.

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**
Version
2.0.0.5322
Mono Version
5.20.1.19
AppData directory
/home/pi/.config/NzbDrone
Startup directory
/opt/NzbDrone

**UI Bugs:**
 - OS: rpi
 - Browser: Brave

**Additional context**
![image](https://user-images.githubusercontent.com/5911982/61217095-a7a1dc80-a717-11e9-9592-d9a114e10d60.png)

**Comment by markus101** [comment]
You need to pick the _root folder_; the parent to the series folder, not the series folder as the UI mentions. V3 does a better job of explaining this.
