### ISSUE TITLE
Wont detect episodes if they are missing an air date

### ISSUE THREAD

**Issue by DigitalSteel7** [Sonarr/Sonarr#3209]
If I have sonarr scan a folder where episode files exist but no air date is listed, it will not detect them. I have verified this by finding and adding some air dates via thetvdb.com, and then when sonarr picks up on those changes it will all of a sudden find the files that were already in the folder.

**Comment by markus101** [comment]
Sonarr only needs an air date for daily shows (where the air date is used for matching). Please use the forums/subreddit for support/questions and include all the requested information.

**Comment by DigitalSteel7** [comment]
I noticed this was happening on anime specials

**Comment by markus101** [comment]
Anime specials are either going to need an absolute episode number or the episode title on TheTVDB matches the episode title in the filename (fuzzy matching that Sonarr will do only for specials).
