### ISSUE TITLE
Limit how many post processing scripts can run at one time

### ISSUE THREAD

**Issue by uchagani** [Sonarr/Sonarr#3212]
**Describe the problem**
Some post processing scripts take up a decent amount of processing power.  For example, converting videos to a standardized format.  If we can add a limit to the number of post processing scripts that can run at one time we can limit CPU usage.

**Describe any solutions you think might work**
Add an option to the Custom Script dialog that will configure how many instances of the script can run at one time.

**Comment by markus101** [comment]
In v3 import tasks are queued and custom scripts execute synchronously. Unless your script forks to its own process it’ll be limited to one execution.
