### ISSUE TITLE
Undefined Series

### ISSUE THREAD

**Issue by BugFinder2000** [Sonarr/Sonarr#3213]
**Describe the bug**
The Series:
`Hensuki: Are you willing to fall in love with a pervert, as long as she's a cutie?`

It didnt find the right result:
`Hensuki.2019.Ep02.Abc.Abc.Abc.Abc.Abc.123pAbc.Abc-Abc`

Same with:
`Arifureta - From Commonplace to World's Strongest`

It didnt find the torrent with the name:
`ARIFURETA.2019.Ep02.Abc.Abc.Abc.Abc.Abc.123pAbc.Abc-Abc`

https://i.imgur.com/Vva9ufa.png
**System Information**
 - Sonarr Version: 3.0.2.529
 - Operating System:Windows 10

**Additional context**
AniDB has a Anime name database that can be download too better find anime series that have a shorter name or other names.

**Comment by markus101** [comment]
This is covered in the [FAQ](https://github.com/Sonarr/Sonarr/wiki/FAQ#why-cant-sonarr-import-episode-files-for-series-x--why-cant-sonarr-find-releases-for-series-x)
