### ISSUE TITLE
Option to apply serie to all checked in manual import screen

### ISSUE THREAD

**Issue by Iguana9999phil** [Sonarr/Sonarr#3214]
Add the option to apply the chosen serie to all checkmarked files within the manual import screen. At the moment serie needs to be chosen per file. Example attached; this is a Dutch serie "Overspel" while Sonarr recognize it as "The Affair" all seasons are therefor not auto imported (not a big problem) but an option (button of dialog when choosing the serie for the first file for example) would be great.
![A189D99E-2DB5-4138-8F26-EB36EB0A5DEC](https://user-images.githubusercontent.com/40793267/61361907-dfde2200-a8b3-11e9-963e-760cae42740f.jpeg)

**Comment by markus101** [comment]
This us implemented in v3 already.

**Comment by Iguana9999phil** [comment]
Ok, how to use that then? Or is that the import function under the serie itself? Because that one only imports from the directory so I would need to transfer it there first, do a import etc. Would like to not do that "transfer to directory step" and import from the download directory. Just checked and if the serie manual import option would allow to go to other directories (download dir) this would be covered and I would finally use that button.
