### ISSUE TITLE
Sonarr Matching `Unknown Series` with valid release

### ISSUE THREAD

**Issue by miguemely** [Sonarr/Sonarr#3219]
## Bug Report

When attempting to search a series, for example, the anime The Ones Within, only the English alias is being matched, and the Japanese alias is being ignored. This is shown when it is matching `The Ones Within`.

[TheExem shows the right aliases and matchings](http://thexem.de/xem/show/4684)

![image](https://user-images.githubusercontent.com/1568683/61597088-cd2c5b80-abd9-11e9-9744-9549a608f060.png)

### System Information/Logs

**Sonarr Version:** 2.0.0.5322

**Operating System:** Ubuntu 18.04.2

**.net Framework (Windows) or mono (macOS/Linux) Version:**

`Mono JIT compiler version 5.10.1.20 (tarball Thu Mar 29 10:48:35 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)`

**Link to Log Files (debug or trace):** _Regarding this, what specific log file would I be looking for?_

**Comment by markus101** [comment]
> Regarding this, what specific log file would I be looking for?

The debug logs that include the search, enable debug logging first obviously, the wiki has the relevant info.
