### ISSUE TITLE
Unknown Series 

### ISSUE THREAD

**Issue by mvnitro** [Sonarr/Sonarr#3220]
Vi que tem outros topicos com o problema "Unknown Series" porém os lendo não cosegui identificar uma solução e se é o mesmo problema que o meu

O pessoal do jackett ja meu ajudou a consertar a busca do meu provedor torrent

porém agora o sonarr acha o torrent mas nã faz o download

log abaixo

19-7-22 14:12:31.5|Debug|DownloadDecisionMaker|Processing release 'Deuses Americanos (American Gods) - S02E01' from 'Amigos-share'
19-7-22 14:12:31.5|Debug|Parser|Parsing string 'Deuses Americanos (American Gods) - S02E01'
19-7-22 14:12:31.5|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
19-7-22 14:12:31.5|Debug|Parser|Episode Parsed. Deuses Americanos (American Gods) - S02E01 
19-7-22 14:12:31.5|Debug|Parser|Language parsed: English
19-7-22 14:12:31.5|Debug|QualityParser|Trying to parse quality for Deuses Americanos (American Gods) - S02E01
19-7-22 14:12:31.5|Debug|Parser|Quality parsed: Unknown v1
19-7-22 14:12:31.5|Debug|Parser|Release Group parsed: 
19-7-22 14:12:31.5|Debug|ParsingService|No matching series Deuses Americanos (American Gods)
19-7-22 14:12:31.5|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
19-7-22 14:12:31.5|Trace|DownloadDecisionMaker|Processing release 26/26
19-7-22 14:12:31.5|Trace|EventAggregator|Publishing CommandUpdatedEvent
19-7-22 14:12:31.5|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
19-7-22 14:12:31.5|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
19-7-22 14:12:31.5|Debug|DownloadDecisionMaker|Processing release 'Deuses Americanos (American Gods) - S02E01' from 'Amigos-share'
19-7-22 14:12:31.5|Debug|Parser|Parsing string 'Deuses Americanos (American Gods) - S02E01'
19-7-22 14:12:31.5|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
19-7-22 14:12:31.5|Debug|Parser|Episode Parsed. Deuses Americanos (American Gods) - S02E01 
19-7-22 14:12:31.5|Debug|Parser|Language parsed: English
19-7-22 14:12:31.5|Debug|QualityParser|Trying to parse quality for Deuses Americanos (American Gods) - S02E01
19-7-22 14:12:31.5|Debug|Parser|Quality parsed: Unknown v1
19-7-22 14:12:31.5|Debug|Parser|Release Group parsed: 
19-7-22 14:12:31.5|Debug|ParsingService|No matching series Deuses Americanos (American Gods)
19-7-22 14:12:31.5|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series

Pelo que entendi o nome do arquivo torrent é "Deuses Americanos (American Gods) - S02E01" tem nome em portugues e ingles no arquivo e não tem a qualidade, bom referente a qualidade eu entendo que não temos o que fazer ja que o provedor do torrent não segue um padrão e colocar o mesmo no nome do arquivo.

Porém sobre a busca do nome da serie não seria possivel deixar a mesma mais flexivel ? por exemplo mesmo que tenho o nome em portugues no arquivo junto com o ingles o mesmo deveria ignorar o portugues ? e busca somente por "Americana gods" e "s02e01" por exemplo caso encontre esse 2 termos estaria correto ? 
3274/5000
I saw that there are other issues with the problem "Unknown Series" but reading them I can not identify a solution and if it is the same problem as mine

The jackett guys already helped me fix the search for my provider torrent

but now sonarr finds torrent but does not download

log below

19-7-22 14: 12: 31.5 Debug DownloadDecisionMaker Processing American Gods - S02E01 'from' Friends-share '
19-7-22 14: 12: 31.5 | Debug | Parser | Parsing string 'American Gods' - S02E01'
19.7-22 14: 12: 31.5 | Trace | Parser | ^ (? <?> +?) (?: (?: [-_ \ W] (S) (? <D) (?: \ D {1,2}) (?! \ D +) } \ {{2,3} (?! \ d +)) (?: (?: \ - [ex] | \ W [ex] | _) {1,2} (2,3}}>>>>>>>>>>>>>>>>>)
19-7-22 14: 12: 31.5 | Debug | Parser | Episode Parsed. American Gods - S02E01
19-7-22 14: 12: 31.5 | Debug | Parser | Language parsed: English
19-7-22 14: 12: 31.5 | Debug | QualityParser | Trying to parse quality for American Gods - S02E01
Quality parsed: Unknown v1 19-7-22 14: 12: 31.5 | Debug | Parser | Quality parsed: Unknown v1
19-7-22 14: 12: 31.5 | Debug | Parser | Release Group parsed:
19-7-22 14: 12: 31.5 | Debug | ParsingService | No matching series American Gods (American Gods)
19-7-22 14: 12: 31.5 | Debug | DownloadDecisionMaker | Release rejected for the following reasons: [Permanent] Unknown Series
19-7-22 14: 12: 31.5 | Trace | DownloadDecisionMaker | Processing release 26/26
19-7-22 14: 12: 31.5 | Trace | EventAggregator | Publishing CommandUpdatedEvent
19-7-22 14: 12: 31.5 | Trace | EventAggregator | CommandUpdatedEvent -> CommandModule
19-7-22 14: 12: 31.5 | Trace | EventAggregator | CommandUpdatedEvent <- CommandModule
19-7-22 14: 12: 31.5 Debug DownloadDecisionMaker Processing American Gods - S02E01 'from' Friends-share '
19-7-22 14: 12: 31.5 | Debug | Parser | Parsing string 'American Gods' - S02E01'
19.7-22 14: 12: 31.5 | Trace | Parser | ^ (? <?> +?) (?: (?: [-_ \ W] (S) (? <D) (?: \ D {1,2}) (?! \ D +) } \ {{2,3} (?! \ d +)) (?: (?: \ - [ex] | \ W [ex] | _) {1,2} (2,3}}>>>>>>>>>>>>>>>>>)
19-7-22 14: 12: 31.5 | Debug | Parser | Episode Parsed. American Gods - S02E01
19-7-22 14: 12: 31.5 | Debug | Parser | Language parsed: English
19-7-22 14: 12: 31.5 | Debug | QualityParser | Trying to parse quality for American Gods - S02E01
Quality parsed: Unknown v1 19-7-22 14: 12: 31.5 | Debug | Parser | Quality parsed: Unknown v1
19-7-22 14: 12: 31.5 | Debug | Parser | Release Group parsed:
19-7-22 14: 12: 31.5 | Debug | ParsingService | No matching series American Gods (American Gods)
19-7-22 14: 12: 31.5 | Debug | DownloadDecisionMaker | Release rejected for the following reasons: [Permanent] Unknown Series

From what I understand the name of the torrent file is "American Gods - S02E01" has a name in Portuguese and English in the file and does not have the quality, good referring to the quality I understand that we do not have what to do since the provider of the torrent does not follow a pattern and put the same in the filename.

But about the search of the name of the series would not be possible to leave the same more flexible? for example even if I have the Portuguese name in the file along with the English the same should ignore the Portuguese? and search only for "Americana gods" and "s02e01" for example if you find that 2 terms would be correct?

Note
series that the tracket put the file name correctly my sonarr is doing the downlaod normally

**Comment by markus101** [comment]
Please use the forums/subreddit for support/questions.

Sonarr does not ignore parts of the release's series title, that could cause issues with similarly named series. In this case that naming format is not one Sonarr supports, we maintain a list of aliases for series titles, but do not support titles that contain multiple translations.
