### ISSUE TITLE
clean title rename not working (or is it not what I think it is?)

### ISSUE THREAD

**Issue by s0mm3rb** [Sonarr/Sonarr#3221]
hello there
I can't find proper information on how the 'cleantitle' option works
but for my understanding, it should remove any special chars, right?
if so, it does not work
![grafik](https://user-images.githubusercontent.com/38328575/61752216-2b5c6880-adab-11e9-9bfc-14e149416476.png)
I mean how are those clean titles?

or this
![grafik](https://user-images.githubusercontent.com/38328575/61752415-d10fd780-adab-11e9-9d3c-db5792affcf4.png)

but maybe I don't know how a clean title should look

also is there an option to force english filenames?
I would like to have sonarr name all files and folders only in english

thank you
regards

OS: Ubuntu 18.04
sonarr Version: 2.0.0.5322
Mono Version: 5.20.1.34

**Comment by markus101** [comment]
It doesn't remove them all, there is https://github.com/Sonarr/Sonarr/issues/2028 already tracking that.

The characters that are replaced are here: https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L69 looks like those are likely unicode characters that look similar, but are not the same.

Sonarr only gets English metadata, Hawaii Five-0's episode titles are named that way on TheTVDB.
