### ISSUE TITLE
[FEATURE REQUEST] Have 'CleanTitle' remove any special chars and replace them with ascii

### ISSUE THREAD

**Issue by s0mm3rb** [Sonarr/Sonarr#3223]
**Describe the problem**
especially when working through cli on headless servers any non ascii chars can cause issues
ex: hawaii five-o takes tis to a new level
as you can see the episode s09e01 can't even be displayed properly
(yes one could prob. fix this in the servers localisation settings, but why even keep those chars?)
![grafik](https://user-images.githubusercontent.com/38328575/61786710-99864700-ae0e-11e9-99c7-f5e605c167b1.png)
those filnenames are just ridiculous imho (no offense)

**Describe any solutions you think might work**
1. replace any unicode char with ascii
2. let user decide where to pull the episode title from
as markus101 pointed out here https://github.com/Sonarr/Sonarr/issues/3221#issuecomment-514410637 hawaii five-o's names are like this on the tvdb
but imdb does not use those special acent symbols
so pulling the names from imdb instead of tvdb would most likely fix this

thank you
keep up the great work

**Comment by markus101** [comment]
You’re aware of the existing issue already, thought it won’t be clean title, it’ll be something new.

**Comment by markus101** [comment]
Better yet there is https://github.com/Sonarr/Sonarr/issues/454

**Comment by s0mm3rb** [comment]
sorry if you think this request is a duplicate
but I think that the other requests don't cover it completely
