### ISSUE TITLE
Drag n Drop Order of Custom Filters

### ISSUE THREAD

**Issue by rsunde** [Sonarr/Sonarr#3225]
![image](https://user-images.githubusercontent.com/3204741/61951847-81e7c380-afb2-11e9-9f4d-78601e815ab0.png)

**Describe the problem**
I added a bunch of custom filters and then realized I added them in the "wrong" order.

**System Information**
- Version 3.0.2.537
- Package Version 3.0.2.537-ls103 by linuxserver.io
- Mono Version 6.0.0.313

**Comment by markus101** [comment]
They're listed in the order added, we do not have plans to support re-ordering them.
