### ISSUE TITLE
Edit Custom Filters

### ISSUE THREAD

**Issue by rsunde** [Sonarr/Sonarr#3226]
**Describe the bug**
"BUG" when editing/adding a custom filter, I first see a list of current filters, I go to edit/add and once I hit Save the custom filters dialog is closed...

I want to continue edit/add...

**System Information**
- Version 3.0.2.537
- Package Version 3.0.2.537-ls103 by linuxserver.io
- Mono Version 6.0.0.313

**Comment by markus101** [comment]
On save it will close and apply that filter, we don't have plans to change that. On cancel it should return to the list of custom filters to edit another/add a new one, that will be fixed in an upcoming release.
