### ISSUE TITLE
Duplicate Slug

### ISSUE THREAD

**Issue by Generalnoob** [Sonarr/Sonarr#3227]
there is now two After Life tv shows from Netflix this year, 
if i add one when i go to add the other i get

Title slug 'after-life' is in use by series 'After Life'
Path is already configured for another series

I'm not really sure what i should do about it any help would be appreciated

**Comment by markus101** [comment]
Please provide the TVDB links for the series you already have added and the one you're attempting to add.

If they're both named `After Life` on TheTVDB the Netflix one will likely need to updated to avoid the collision as two series cannot have identical names, if they are just similar we can do something to deal with that.

**Comment by Generalnoob** [comment]
Turns out I'm an idiot, I'm really sorry for wasting your time i got the name wrong :( super embarrassing lol really sorry
