### ISSUE TITLE
Down-/Upload instead of move

### ISSUE THREAD

**Issue by agncr** [Sonarr/Sonarr#3229]
**Describe the bug**
Sonarr is downloading and uploading a episode, when i want to rename it, instead of just renaming (like mv foo too) it. 

Version 537 didn't had this problem: I always got the following error:
`19-8-1 15:23:44.5|Debug|DiskProvider|Hardlink '/media/Serien/The Simpsons/xyz-simpsons-s22e22-720p.mkv' to '/media/Serien/The Simpsons/xyz-simpsons-s22e22-720p.mkv.backup~' failed.                      
[v3.0.2.537] Mono.Unix.UnixIOException: Function not implemented [ENOSYS].                                                                                                                                                              
19-8-1 15:23:44.5|Trace|DiskTransferService|Hardlink move failed, reverting to move.` 
but it did move the the file, without hassle

After version 537 something got fixed and Hardlinking works. A .backup file is created on the remote and the file is being down- and uploaded at the same time. This takes much longer instead of just moving it.

Can i somehow tell Sonarr to move it everytime instead of trying to create a hardlink? 

**System Information**

 - Sonarr Version: 3.0.2.537 (LinuxServer.io)
 - Operating System:  Debian 10 with Docker

**Comment by markus101** [comment]
Please use the forums/subreddit for support/questions.

We have not made changes to this behaviour in Sonarr. If you recently upgraded to mono 6 that could be the problems.
