### ISSUE TITLE
V3 no longer taking remote path mapping into account

### ISSUE THREAD

**Issue by Alcedema** [Sonarr/Sonarr#3231]
**Describe the bug**
Was working in V2 but now sonarr halts on import (after successful download) with:

> Import failed, path does not exist or is not accessible by Sonarr: /media/sf_Downloads/Finished/sonarr/...

When remote path map has always been:

> Host Remote Path Local Path
192.168.1.108 /media/sf_downloads/ /media/files/Downloads/

Must point out permissions on actual folder are ok. Deluge has been on remote machine and mappings have been working fine prior to upgrade of sonarr. Manual import works as expected through sonarr (Wanted - Manual Import) just searching in folder that doesn’t exist on local machine. 

**Screenshots**

**Logs**
Can link later, no debug/trace logs yet as not enabled. 

**System Information**

 - Sonarr Version: 3.0.2.553
 - Operating System: Linux Mint 18.3
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 6.0.0.313
- Download client: Deluge 

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by Alcedema** [comment]
Having jut read my own issue, I changed the remote mapping to the exact case of the folder deluge uses and it now works. I am assuming V3 now demands exact same case whereas V2 didn't.

**Comment by markus101** [comment]
Paths should have always been case sensitive (outside of Windows), so it looks like we fixed a bug along the way. Glad to hear you sorted it out.
