### ISSUE TITLE
Parse QxR/UTR release group/encoder names

### ISSUE THREAD

**Issue by TheCatLady** [Sonarr/Sonarr#3232]
Sonarr currently fails to recognize the encoder name in QxR & UTR's releases.

Here are a couple examples:

- Game of Thrones (2011) - S08E05 - The Bells (1080p AMZN WEB-DL x265 **_ImE_**).mkv
- Chefs Table S05E01 (2160p x265 10bit S96 _**Joy**_).mkv

I believe some other encoding groups may also use this convention, but these are the two that I'm aware of, and they are quite popular.

**Comment by theimmortal68** [comment]
I would also like to see this feature added. QxR and UTR are two of my preferred release groups and I always have to go in and manually edit the file. Which of course defeats the purpose of automation.

**Comment by markus101** [comment]
At this time we do not have plans to support this format, mostly because it's inconsistent and error prone.

Something like `The Lone Ranger (Complete TV Series In MP4 Format)` would result in `Format` being the release group, which is obviously wrong.
