### ISSUE TITLE
User configurable free space check

### ISSUE THREAD

**Issue by KenMurphy** [Sonarr/Sonarr#3233]
**Describe the problem**
Sonarr will sometimes fill up my staging drive before I can offload media to its permanent location. The free space check only fails if there is less than 100MB available. I would like to set this to leave a couple gigabytes free.

**Describe any solutions you think might work**
A size field just below the 'free space check' toggle which allows the user to set the amount of free space available before passing the check. I'm picturing something like:
Minimum free space: [1000] Megabytes
located below the 'Skip Free Space Check' option on the Media Management settings page

**Additional context**
I'm running a Cloudbox instance. My download drive is on a different partition than my local media dir. When downloading lots of media at once the local media directory can fill up before being able to offload to Google Drive (if I have already hit the daily upload limit for example). Because my local media drive is on my root filesystem this results in my system temporarily running out of disk.

I'm willing to implement this feature if a pull request is likely to be accepted for it but I wanted to check before doing the work. Are there any reasons this feature would be rejected given that it operates correctly?

**Comment by markus101** [comment]
Yeah, currently the limit leaves at least 100MB free, I've discussed with Taloth and we're both open to an option to control that and definitely open for a PR with it.

Thanks for reaching out!

**Comment by KenMurphy** [comment]
I've added a pull request for this issue, comments welcome. Thanks!
