### ISSUE TITLE
Daily Notifications of Sonarr logging into plex

### ISSUE THREAD

**Issue by orionshock** [Sonarr/Sonarr#3234]
**Describe the bug**
Im getting daily email notifications of a new device login coming from Sonarr

**Screenshots**
n/a

**Logs**
unknown

**System Information**

 - Sonarr Version: 2.0.0.5322
 - Operating System: Ubuntu
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.19

**Additional context**
Not sure what other information you need. However this daily notification is getting annoying.
Is there a way to integrate plex's SSO Framework into that plugin so it's not generating new login attempts every 24hrs?

**Comment by markus101** [comment]
Sonarr wouldn't only attempt to login if the toekn it's using is invalid (or Sonarr is restarted). Plex auth is changed in v3, it is not going to change in v2.
