### ISSUE TITLE
Copy/move fails because of failure to hardlink

### ISSUE THREAD

**Issue by Roman2K** [Sonarr/Sonarr#3235]
**Describe the bug**
I have Sonarr in a Docker container with the following bind mounts:

* `/torrents` read-only
* `/media` (destination) read-write

Upon download completion, I want to Sonarr copy instead of move+hardlink because the the sources of `/torrents` and `/media` aren't on the same physical volume. They're mounts themselves on the host (`/torrent` = cifs, `/media` = sshfs)

Up until a recently, I guess after recent update of the [linuxserver/sonarr](https://hub.docker.com/r/linuxserver/sonarr/), Sonarr did just that. I even had the hardlink option enabled and of course Sonarr must have failed to make them but the copy was considered successful, and imports marked as succeeded. That's what I expected and it did it.

Now however, the failure to hardlink make the import fail. I can see `.partial~` files being copied to their destination but then I see a hardlink exception in the debug log and the `.partial~` is not renamed and instead deleted, import marked as failed. And Sonarr retries that in a loop.

I disabled the hardlink option, and Sonarr still tries to hardlink and marks the import failed.

The previous behaviour was correct to me: copy to destination, don't delete the source file as torrent is seeding (and mount is read-only anyway, so don't try). Try to hardlink if option is enabled and mount allows, otherwise fail and log but consider the import successful.

Can that behaviour be restored?

**Logs**
[sonarr.debug.txt](https://gist.github.com/Roman2K/57cc91a474ceb6ecbff3d482cf9c21ed)

**System Information**

 - Sonarr Version: 2.0.0.5322 (same in 2.0.0.5337)
 - Operating System: linuxserver/sonarr Docker image (host kernel 4.18.0-16)
 - .mono (macOS/Linux) Version: unknown

**Additional context**
Apaprently similar issue: https://forums.sonarr.tv/t/sonarr-constantly-crashing-on-ubuntu-15-10/10008/4

**Comment by markus101** [comment]
Please use the forums for support, there are recent threads with similar issues noted (involving mono 6).

This behaviour has not changed in Sonarr. Mono 6.0 changes things, which is used in recent linuxserver images, mostly when SMB shares are involved.

> .mono (macOS/Linux) Version: unknown

This is shown in the UI of Sonarr.

> Apaprently similar issue: forums.sonarr.tv/t/sonarr-constantly-crashing-on-ubuntu-15-10/10008/4

Given that issue is 3 years old I don't think it's related.
