### ISSUE TITLE
RARBG links on the interactive search screen fail with 403 error

### ISSUE THREAD

**Issue by watschft** [Sonarr/Sonarr#3239]
**Describe the bug**
The links to RARBG on the interactive search results screen fail with “403 Forbidden“ error.

**Solution**
Add ”&app_id=Sonarr” to the link url and the link will work as expected.

**Comment by cremor** [comment]
@markus101 Why is this fix not included in the latest release?
You commited your fix on 4th of August and a release (2.0.0.5338) was created on 15th of August, but it didn't contain your fix.

**Comment by markus101** [comment]
It was fixed in the v3 branch and since it wasn’t a critical issue in v2 it wasn’t backported (same as most fixes in v3).

The reason for the update after that was for a mono issue otherwise there wouldn’t have been an update.

**Comment by cremor** [comment]
Does that mean that it will never be fixed in v2? That would be very sad because it is a very annoying issue and a very easy fix at the same time.

**Comment by markus101** [comment]
Correct, it will not be fixed in v2.

V3 is in beta and we’re not making changes to v2 while we finalize v3.
