### ISSUE TITLE
AutoSort Release Profile Preferred

### ISSUE THREAD

**Issue by LPiner** [Sonarr/Sonarr#3241]
**Describe the problem**
In the release profiles edit screen there is a priority section. This section allows for the addition of a string(title) and a priority but it does not allow you to re-arrange given tags/titles once they are created. This works fine for a limited number of tags but quickly becomes hard to read as priorities are never sorted. The only way to 'sort' is to delete and re-add your tags in the correct order.

**Describe any solutions you think might work**
Probably the best solution is to only allow the user to drag and drop priority's and simply do away with the number input. This would allow for easy maintenance of priorities and I think would greatly improve this section of the UI.

**Comment by markus101** [comment]
Please use the templates when filing issues.

This has come up before, but it’s not something we’re planning to do as it’s not going to be very friendly as things continually shift after changing the value.

**Comment by LPiner** [comment]
Yes but there are a ton of ways to do this besides shifting the values while a user is typing. As it stands now the only way to sort things is to manually shift the titles/values around which is a little insane. 

Maybe a simple drag/drop style would be better.

The current style quickly becomes worthless once you get past 3-4 tags.

**Comment by LPiner** [comment]
Updated request to use template.

**Comment by markus101** [comment]
> Yes but there are a ton of ways to do this besides shifting the values while a user is typing

Obviously that would be terrible and not what I was thinking when I said it would jump. What are some of the other ways you're thinking?

> Maybe a simple drag/drop style would be better.

Drag and drop is used for prioritization in other places in the UI, I think it implies the order matters and disagree that it's a good solution here.

Open for ideas here, but I'm pretty confident that drag and drop isn't going to be it.

**Comment by LPiner** [comment]
Hmm I would argue that order does matter, if you were to make the list order itself the priority instead of the user providing a number it then you essentially have the same thing. I compare this to IP tables where you're running down the list till a rule is matched and then taking the specified action.

But I digress, probably the simplest adjustment that could be made is to sort the values after the user submits the form so at least the next time the form is loaded the items are in the correct order.
