### ISSUE TITLE
Multi-user authentication and permissions

### ISSUE THREAD

**Issue by aetaric** [Sonarr/Sonarr#3242]
**Describe the problem**
I share access to my sonarr install with a few trusted people, but it would be nice to limit the scope of their access.

**Describe any solutions you think might work**
If possible this should be as modular as possible. I personally would be willing to craft up a SAML auth module if this was modular and allowed 3rd parties to create more tailored solutions. 
If nothing else allow a reverse proxy to pass the common REMOTE_USER var via a request header and have scoped perms handled within sonarr directly. A good example where this is already done in other software is nagios or, the livestatus frontend for it, thruk (though these are done via internal apache vars accessed because of fcgi, but it's easy enough to push this data via mod_rewrite and mod_headers).

**Additional context**
Currently, I'm using mod_auth_mellon as a SAML Service Provider and Duo Security's Duo Access Gateway as a SAML Identity Provider that ties back into OpenLDAP to provide multi-user authentication and authorization, but I have no way in sonarr to limit user access once logged in. Users are free to muck up my entire install should they decide to and this is a trade off I'm uncomfortable working with long term for the sake of allowing said users more advanced access than just the 3rd party Ombi to request media.

**Comment by markus101** [comment]
Multi-user support is covered by https://github.com/Sonarr/Sonarr/issues/1682 it's not something we have short term plans for at this time.
