### ISSUE TITLE
Couldn't import episode, then container gets stuck.

### ISSUE THREAD

**Issue by BodingClockchian** [Sonarr/Sonarr#3244]
**Describe the bug**
After the download client finished the download Sonarr copies the file to the right folder. When Sonarr should rename the file from tvserie.mkv.partial to tvserie.mkv the whole container gets stuck. 

**Logs**
[Debug dump](https://pastebin.com/xJXaQGwa)

I think the most important lines are:
```
System.IO.IOException: Lock violation on path /tv/Rick_and_Morty/Season 02
Unable to write data to the transport connection: The socket has been shut down. ---> System.Net.Sockets.SocketException: The socket has been shut down
```

**System Information**

 - Sonarr Version: Latest according to linuxserver.io
 - Operating System: Ubuntu 18.04.2 LTS (GNU/Linux 5.0.0-23-generic x86_64)
- Docker-compose version 1.23.2
- Docker version 19.03.1

**Additional context**
Im using CIFS to mount an SMB share on Ubuntu. I think this is related with the problem. The following thread says something about that issue. [Link](https://forums.sonarr.tv/t/strange-failures-on-cifs-mounts-solution/16741) Also, after the Sonarr container gets stuck I have to force reboot the whole system to get it up and running again.

**Comment by markus101** [comment]
Please use the forums/subreddit for support. This could be a mono 6 issue (you didn't include that piece of requested info).
