### ISSUE TITLE
Sort series by Start Year

### ISSUE THREAD

**Issue by LoganXShadow** [Sonarr/Sonarr#3245]
## Feature Request
The ability to sort series by the year it started
### What problem are you looking to solve?
It would make it easier to find series by how old they are.

**Comment by thezoggy** [comment]
in the meantime, you could sort by 'added' if your using v3. 
but could be useful to expose first ep airdate to sort by..

**Comment by LoganXShadow** [comment]
thezoggy I have tried sorting by 'added' but it only sort by the date that I added the series to Sonarr. When I first saw it in the sort column I hoped it was the date it was added to TheTVDB.com.
Nice idea about the first episode airdate.
