### ISSUE TITLE
Adding new Series issue via The TVDB

### ISSUE THREAD

**Issue by zetneteork** [Sonarr/Sonarr#3247]
Adding series https://www.thetvdb.com/series/311023 via `tvdb:311023` it is unable to search.

```
Couldn't find any results for 'tvdb:311023'
You can also search using TVDB ID of a show. eg. tvdb:71663
Why can't I find my show?
```

**Comment by markus101** [comment]
Please include all the requested information, including the logs.

**Comment by markus101** [comment]
This is covered in the FAQ. The series need English metadata, including a series title (which it lacks) on TheTVDB.
