### ISSUE TITLE
Auto clear Activity after given amount of days

### ISSUE THREAD

**Issue by sojab0on** [Sonarr/Sonarr#3251]
**Describe the problem**
The Activity tab stays on 19 in my installation even tough most of the media is gives there are already downloaded.

**Describe any solutions you think might work**
An option to either clear the full Activity list, or an automatic clean up after say 5-7 days in Activity 

**Additional context**
I have noticed that the sonar and even radar Activity list was ocupied by media already downloaded trough one of both systems, but to clear the list every time 1 by 1 is a teadious process and time consuming with 19 in it now.

**Comment by markus101** [comment]
Items are removed from Activity as they are imported. If they’re not being imported by Sonarr then they will stay there unless you disable Completed Download Handling in Sonarr.

If you want to troubleshoot this issue, open a thread on the forums or subreddit.
