### ISSUE TITLE
Sonarr can't find anime

### ISSUE THREAD

**Issue by Ansem93** [Sonarr/Sonarr#3256]
Hi!

I'm trying to set Sonarr so that it will be able to download anime too with the cat indexer.
For now I tried this two series: Carole & Tuesday and Lord El-Melloi .

If I try to search for any episode of Lord El-Melloi sonarr can't find it.
If I seatch for Carole & tuesday it finds only a little of the episodes, and I can't find the one from the group fansub that I want.

I think that the way sonarr search for anime shoul be changed. Most of the times group fansub will only write " [Group name] Anime name - Episode", sometimes they add the resolution, but not always.
If you search for the name of the episode is nearly impossible to find it.

**Comment by markus101** [comment]
Please use the forums or subreddit for questions/support.
