### ISSUE TITLE
Add the option to directly add torrents in the UI.

### ISSUE THREAD

**Issue by ay3w** [Sonarr/Sonarr#3258]
**Describe the problem**: Sometimes, for many reasons, Sonarr doesn't grab episodes when they exist on trackers. I think that no matter what solutions are implemented, will always be an issue on some level due to the breadth of compatibility issues. At the moment there are options to have sonarr import files from disk, but they only allow you to do so from within the managed folder for that show, which means lots of effort. You have to add it to your torrent client with the correct directory (can't just put in a watch folder and have it go into the default directory, which means you have to use the client interface), wait for it to download and then go into the sonarr UI and add it manually.

**Describe any solutions you think might work**
An option to directly input a magnet link or torrent file to sonarr via the UI for each episode, as well as for season packs. This is lower effort then existing workarounds that allow you to manually add torrents to sonarr, whilst hopefully being not that hard to implement.

**Comment by markus101** [comment]
We don’t have plans to add this to Sonarr. Adding it directly to the client in the correct category/label is the recommended way.

Not sure if torrent client support it, but Usenet clients support category subfolders in the watch folder to automatically set the category when the download is added.

You can also use Manual Import (from Wanted: Missing) to import downloads Sonarr is not tracking.
