### ISSUE TITLE
Better episode matching on bad release name.

### ISSUE THREAD

**Issue by BugFinder2000** [Sonarr/Sonarr#3259]
**Describe the bug**
The torrent file has this name:

> Test.Ep01-12.Complete.English.AC3.DL.1080p.BluRay.x264

And the episodes get not reconized.

I can force download it but then it download it only for the first Episode. But it contains all episodes

**Logs**
There is Nothing Special.

**System Information**

 - Sonarr Version: 3.0.2.577
 - Operating System: Windows 10 1903
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.12

**Comment by markus101** [comment]
> I can force download it but then it download it only for the first Episode. But it contains all episodes

Sonarr only shows the items in queue that it can parse from the release, at import time it'll parse each file, unless there is a single file it shouldn't be a problem.

> There is Nothing Special.

Let us decide that. Debug logs don't show a lot in this particular case, but trace logs do.

**Comment by BugFinder2000** [comment]
[sonarr.trace.1.txt](https://github.com/Sonarr/Sonarr/files/3502678/sonarr.trace.1.txt)
k here is the trace log if you need it. 

That is good that Sonarr parse all files at the end, but it cant autopick it when it cant see the episodes at the release parse and the episodes are in the release name.
