### ISSUE TITLE
Indexer default language

### ISSUE THREAD

**Issue by BugFinder2000** [Sonarr/Sonarr#3260]
**Describe the problem**
A file has as default language English, that is ok but some of my indexers provider only one language but the files that comes from that Indexer get reconized as english.

**Describe any solutions you think might work**
A option for a default language in the indexers, that will be taken when no language get found in the file name.

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/2854 (now with an updated title).
