### ISSUE TITLE
Prefer codec.

### ISSUE THREAD

**Issue by BugFinder2000** [Sonarr/Sonarr#3261]
**Describe the problem**
I have some local files importet that are x265.

I Setup sonarr so that it prefer the word x265 so now it dont know that the files are x265 and auto Imports x264 files. 

A option to set the prefered codec like the Resolution would be nice.

**Comment by markus101** [comment]
You could add the codec to the file name or use the UI, but preferred words is the way to prefer a codec, we don't plan to add anything else.
