### ISSUE TITLE
Can’t scroll on mobile for manual import

### ISSUE THREAD

**Issue by X8PX** [Sonarr/Sonarr#3264]
**Describe the bug**
Can’t scroll on mobile ui

**Screenshots**
![3550FC49-506D-4ECE-BAB9-7B9BFBC710B4](https://user-images.githubusercontent.com/8931530/63111783-70179180-bf5c-11e9-8db2-5265e7650872.png)

**System Information**

 - Sonarr Version: 3.0.0.348
 - macOS 10.14
 - mono 5.12.0.301

**UI Bugs:**
 - OS: iOS 12.4
 - Browser: Safari

**Additional context**
same issue as you go deeper into the manual import windows ex: the interactive import

**Comment by markus101** [comment]
This is an issue with iOS and modals, the nested scrolling (although they are in different directions) causes iOS to fail miserably, I'm not sure why it's so finicky.
