### ISSUE TITLE
Badly named files cant be detected automaticly

### ISSUE THREAD

**Issue by BugFinder2000** [Sonarr/Sonarr#3266]
**Describe the bug**
Test.test.S01.Ep.01.English.AC3.DL.1080p.BluRay.x264.mkv
Test.test.S01.Ep.02.English.AC3.DL.1080p.BluRay.x264.mkv
Test.test.S01.Ep.03.English.AC3.DL.1080p.BluRay.x264.mkv
Test.test.S01.Ep.04.English.AC3.DL.1080p.BluRay.x264.mkv

(The release was a Season package)
Error: File contains more than one episode. 

**Screenshots**
https://i.imgur.com/m7BEPDZ.png

**Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/3510557/sonarr.trace.txt)

**System Information**

 - Sonarr Version:  3.0.2.587
 - Operating System: Windows 10 1903
 - .net Framework (Windows)

**Comment by thezoggy** [comment]
there are a lot of unsupported naming formats out there... how many are actually like what you shared. if its just one release/group then prob not worth the energy to add support for it

**Comment by BugFinder2000** [comment]
Its one of Sonarr major features to automaticly include new episiodes and that should do it at its best even if it is a edge case like this. 
But if its too heavy to implement then can be added later, just too make sonarr a little bit better.

**Comment by markus101** [comment]
If it's feasible to support it, then we'll try to support it, but if it's a lost cause then we're not going to spend time on supporting it, you're free to to use `Manual Import` for those edge cases.

Unfortunately we have no idea if other releases from this release group do the same thing since you've modified the release names to hide both the title and release group and made the examples not tell a complete story with your editing.

**Comment by BugFinder2000** [comment]
You cant find the release group in public but thats there main naming too write with points and Ep. A small amout do that on public torrents too but in the private section this is used very often.
See:
https://i.imgur.com/IsuzR0U.png

But you dont need this to do it on high prio just add the support in the future. In the mean time i will use the Manual Import

**Comment by markus101** [comment]
So another p2p group that likes to be unique on a small private tracker...
