### ISSUE TITLE
Reverse Rename of episode files.

### ISSUE THREAD

**Issue by clem16** [Sonarr/Sonarr#3267]
**Describe the problem**
Ability to rename filenames back to their original from history in the database.
Being able to do this with both the API and the GUI would be nice, then I don't have to manually go in and do it for each and every episode.

**Describe any solutions you think might work**
Should be fairly simple logic to rename based on stored name in database.

**Additional context**
The problem is, I would like to utilize srrdb to repack some scene releases back to their original RARs and distribution format for backing up to external disks, with the benefits of .sfv for error checking etc. Currently I have to go in and rename all my files for each and every release.

**Comment by markus101** [comment]
You already can, just set Sonarr to use the Original file name instead of another renaming pattern and rename the files. We're not going to add a separate feature to do that though.

**Comment by clem16** [comment]
Ok, & Thanks. Didn't know that was possible to set it to use original file name. Will look into it more.
