### ISSUE TITLE
Please Add Scrape Feature

### ISSUE THREAD

**Issue by AnythingOldSkewl** [Sonarr/Sonarr#3271]
**Describe the problem**
Quite a few times, when older torrents are grabbed they have no seeds.

**Describe any solutions you think might work**
I think what would solve this, is adding a scrape feature, that will check the actual availability of the torrent. Or have the software request a tracker update of available peers.

**Additional context**
none.

**Comment by markus101** [comment]
We do not have plans to check torrents for seeders beyond what is reported by the indexer, you can increase the minimum number of seeders required for Sonarr to grab a torrent on a per indexer basis.
