### ISSUE TITLE
Ubuntu - Failed migration from v2 to v3 - permission issue?

### ISSUE THREAD

**Issue by sephrat** [Sonarr/Sonarr#3272]
**Describe the bug**
I have a running installation of Sonarr V2 and decided to upgrade to V3. I followed the instructions given at https://sonarr.tv/#downloads-v3-linux. Sonarr is up and running but my config from V2 was lost in the process, I ended up with a fresh install.
I noticed an error during the installation:
```
Can't exec "/tmp/sonarr.config.9n4nNk": Permission non accordée at /usr/share/perl/5.26/IPC/Open3.pm line 178.
open2: exec of /tmp/sonarr.config.9n4nNk configure  failed: Permission denied at /usr/share/perl5/Debconf/ConfModule.pm line 59.
```

**Logs**
[sonarr.log](https://github.com/Sonarr/Sonarr/files/3530088/sonarr.log)
It seems it doesn't say much about the upgrade process, is there a log somewhere else?

**System Information**
 - Sonarr Version: Version 2.0.0.5338 to  3.0.2.529
 - Operating System: Unix 5.0.0.25 (Ubuntu 18.04)
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono JIT compiler version 6.0.0.319 

**Additional context**
Sonarr V2 was installed according to the wiki instructions. It ran as a systemd service as sonarr:sonarr. /opt/NzbDrone was owned by sonarr:sonarr.
In the V3 installation popup I set the user and group as default to sonarr:sonarr.

I managed to revert back to V2 and I'm back to where I was before the upgrade: my config is still there.

**Comment by Thirrian** [comment]
https://forums.sonarr.tv/t/permission-issues-after-mono-6-upgrade/22876

**Comment by Thirrian** [comment]
https://forums.sonarr.tv/t/permission-issues-after-mono-6-upgrade/22876

**Comment by Taloth** [comment]
Sounds like /tmp is mounted noexec. Is this your system? coz that's sometimes done by vps providers.

**Comment by sephrat** [comment]
> Sounds like /tmp is mounted noexec. Is this your system? coz that's sometimes done by vps providers.

Good call! Yes this is my case, thanks for pointing that out. I edited /etc/fstab to fix it.
Thanks.
