### ISSUE TITLE
Show size in Mass Editor

### ISSUE THREAD

**Issue by jonnwhite1** [Sonarr/Sonarr#3273]
**Describe the problem**
Mass move in v3 doesn't show the size of the folder. This would be useful if you are moving large numbers of TV Shows it'll be good to have a rough idea of how much you are moving.
Moving series' to the cloud you can work out how long it'll take to upload etc. (Useful for people on slow uploads) 

**Describe any solutions you think might work**
Add Size Collum in Mass editor

**Additional context**

**Comment by fletchto99** [comment]
I'd like to +1 this request! I think it would be super useful to have this information as a column in either the mass editor or season pass on v3. If I have time I'll see if I can work together a PR for this.

**Comment by Meridian1701** [comment]
Is this one up for grabs? Never worked with react before, but this issue appears to be relatively simple.

**Comment by markus101** [comment]
Yeah, feel free to pick it up.

**Comment by fletchto99** [comment]
@Meridian1701 I never had time over the holidays to work on it and unfortunately I don't suspect I'll have much time now that work is starting up again. Thanks for offering to pick it up 🎉
