### ISSUE TITLE
Root Folders Marked Unavailable

### ISSUE THREAD

**Issue by Husky420** [Sonarr/Sonarr#3275]
**Describe the bug**
When trying to import new series, the root folders are always marked unavailable even though the folder exist and is accessible. No issues adding new series or downloading new episodes to the root folders. The "Skip Free Space Check" setting has been checked. This issue started with one of the recent commits in the past week as it was working fine last week.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/36979452/63645496-5b51a100-c6b4-11e9-9085-2db145f8060b.png)

**Logs**
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/3537849/sonarr.debug.txt)

**System Information**

 - Sonarr Version: 3.0.3.610
 - Operating System: FreeBSD 11.2
 - Mono Version 5.10.1.57

**Comment by Taloth** [comment]
> Unable to get free space for '/mnt/television/', unable to find suitable drive

Yeah, probably freebsd. coz it doesn't have /proc, System->Disk Space is probably also a bit empty.
You can try update to mono 5.20

**Comment by Taloth** [comment]
It doesn't 'fix' the issue coz Free Space is 0 B, the old version simply displayed 'unknown' as '0 B'. The 'unavailable' indicator wasn't added till the version you mentioned.
And evidently mono 5.20 still doesn't manage to provide the actual filesystem info.

But yes, there's a small bug in that stack that doesn't visualize the scenario properly. We can get that fixed, thanks for the details and trying the various releases.

**Comment by Taloth** [comment]
PS: build server has some delays, would be 3.0.3.617 or later.
