### ISSUE TITLE
Import multiple subtitles of the same language

### ISSUE THREAD

**Issue by Jelmerb** [Sonarr/Sonarr#3278]
**Describe the problem**
I have multiple subtitle files of the same language (English)
* `Pennyworth.S01E06.WEBRip.x264-ION10.en.srt`
* `Pennyworth.S01E06.WEBRip.x264-ION10.2.en.srt`

Only `Pennyworth.S01E06.WEBRip.x264-ION10.en.srt` is imported, but I would like to have both imported by Sonarr.

**Describe any solutions you think might work**
Check if the name of the video file is in the subtitle file and then copy/move it to the designated folder along with the video file.

**Comment by Jelmerb** [comment]
`Pennyworth.S01E06.WEBRip.x264-ION10.en.srt` is a SDH subtitle and `Pennyworth.S01E06.WEBRip.x264-ION10.2.en.srt` is the normal subtitle. The download didn't add the SDH subtitle properly so there is now way to know which is which.

**Comment by Jas0n99** [comment]
I just noticed that sonarr only imported my `file.en.srt` and not the `file.eng.srt`. I name my subs as follows:

- `file.en.forced.srt` = Forced
- `file.en.srt` = Non-SDH (or only one sub file)
- `file.eng.srt` = SDH

Plex doesn't recognize sdh naming so using 2 & 3 letter codes allows a consistent sort-order in the plex menus.

I couldn't find any documentation on subtitles in the wiki, just kind of gathered bits & pieces from the issues tracker.

Until there is more elaborate configuration, or even documentation, perhaps it would just make sense to copy _all_ existing files with the specified extension(s) in the "import extra files" box? Leaving it up to the user to have their own file-handling process to rename / move whatever files to the root folder with the video for the time being.
