### ISSUE TITLE
Change health check warning to differentiate between short and long term indexer failures

### ISSUE THREAD

**Issue by dkids** [Sonarr/Sonarr#3279]
I have some indexers failing:

![Screen Shot 2019-08-26 at 11 18 18 AM](https://user-images.githubusercontent.com/30055574/63712796-4596c580-c7f3-11e9-85bd-3eb75d03045e.png)

It would be very convenient to have them marked on the Settings, Indexers page so I can test them and hopefully reset them to working.

I could see changing the color to red instead of green or adding "failed at time on day".   It's possible that Sonarr is testing and there's an ongoing problem but it's hard to tell that with the information I have available.

![Screen Shot 2019-08-26 at 11 18 00 AM](https://user-images.githubusercontent.com/30055574/63713023-b211c480-c7f3-11e9-8a6d-5796e2193dfa.png)

**Comment by Taloth** [comment]
Sonarr v3 has a TestAll button in System.
But you do know that Sonarr will reconnect automatically after some time, right?

It's not a bad idea to differentiate between a short unavailability and 12+h. So I'll leave this issue open for that purpose.
