### ISSUE TITLE
MediaCover download doesn't use configured proxy

### ISSUE THREAD

**Issue by grandixximo** [Sonarr/Sonarr#3283]
thetvdb is blocked where i live (China), when i use sonarr i use a proxy extension in chrome, almost everything works, the only thing that does not work is MediaCoverService downloads of covers.

Thanks to the proxy extension in chrome, when i look for a tv show the covers are displayed, but after adding it to my shows, then the covers are not available because MediaCoverService failed to download them probably because it's not going trough chrome to download the covers.

Any solution to this? I am downloading the covers manually, i'd really love a internet proxy settings where sonarr will go trough proxy only when there is need to look on the internet rather than the internal network to manage everything else.

**Comment by M0UL** [comment]
sonarr get the tvdb data from skyhook. skyhook is sonarr tvdb proxy with some extra data. mediacovers and othere images. get pulled directly from thetvdb. with is why the tvdb meta-data works and images does not.

it has nothing to do with your browser.

**Comment by Taloth** [comment]
@grandixximo There is in fact a proxy setting in sonarr. Settings->General->Proxy Settings
It support a variety of protocols. And has several options to bypass the proxy for local or specific addresses.

**Comment by grandixximo** [comment]
I used proxy server, i set it up, i know it's working because i can look for series, but the covers are still not been downloaded

**Comment by rp4k** [comment]
so is there any solution to this.  because i would love to get back my images for sonarr.   i wish we could ask it to pull images from emby or something different other then tvdb since tvdb is blocked here.

**Comment by rp4k** [comment]
![image](https://user-images.githubusercontent.com/18055235/65432628-1c973e00-de4e-11e9-944f-3f7b159b3c50.png)

**Comment by Taloth** [comment]
Which version of Sonarr? Coz 24 days ago I adjusted the code to use the configured proxy.

**Comment by grandixximo** [comment]
I can confirm proxy is working properly on V3, thanks!
