### ISSUE TITLE
Pb with style.css on sonarr 3

### ISSUE THREAD

**Issue by nicovoirin** [Sonarr/Sonarr#3284]
I have to put back the style.css which are removed a lot of time.

**Comment by nicovoirin** [comment]
no i m not using custom css, maybe it is when it update but sonarr tell me the file is missing and i have to put it back from the tar.gz 

Envoyé de mon iPhone

**Comment by markus101** [comment]
During an update Sonarr’s updated would copy it. Check the update logs for any errors copying it, if it’s been copied successfully something else is touching it.

Given v3 has quite a few installs and the updater hasn’t been changed this sounds like an issue on your machine, not a bug in Sonarr.

But you’re missing critical information including the updater logs.

**Comment by nicovoirin** [comment]
thanks
regards

Envoyé de mon iPhone
