### ISSUE TITLE
Series information not being downloaded for 'China: A New World Order'

### ISSUE THREAD

**Issue by Col666** [Sonarr/Sonarr#3287]
**Describe the bug**
Only top level information is downloaded from thetvdb for series 368731 [China: A New World Order](https://www.thetvdb.com/series/china-a-new-world-order). Series 1 and its programmes are not.

**System Information**

 - Sonarr Version: [2.0.0.5338]
 - Operating System: [Windows 10]

**Additional context**
Appears to be a Sonarr issue. Information is downloaded if added to Sickbeard.

**Comment by Col666** [comment]
Import file into Sickbeard, refreshed in Sonarr and all of series 1 data appeared.

**Comment by Col666** [comment]
Seems this is not a programme specific issue.

[The Sky At Night](http://www.thetvdb.com/?tab=series&id=80428) will not add new episodes on 'Update series info'.

Presumably, a related issue.

**Comment by markus101** [comment]
Series information takes time to propagate through the various caches, usually around 90 minutes total. You'll need to wait for it all to update first.
