### ISSUE TITLE
Keyboard Shortcut to Cancel/Accept Confirmation Modals

### ISSUE THREAD

**Issue by ldexterldesign** [Sonarr/Sonarr#3291]
Hi,

Hope you're well

Thanks for amazing software

As a user, when I use the episode (manual) search results modal view, I want to action the "cancel/grab" dialog via keyboard so I don't get [R]SI

Screen cast: https://www.dropbox.com/sh/0fwdds6l0k3v210/AACyWlTSBf6OuMZBBC-76lp3a?dl=0

It would be kind if users can submit their choice (i.e. to cancel or grab) via keyboard shortcut (e.g. make the grab button auto-focused by default and enable press event(s) via enter or spacebar)

I see some keyboard shortcuts exists (shift + ?) so if this is roadmapped I just want to check this use case is considered

If you're reading and:

* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

Welcome feedback/input inc. other keyboard shortcut use cases

It's great we have an exit modal keyboard (esc) - I think this should/could be added to help documentation

If you have any issues (e.g. questions/queries) then happy to help

Hope to hear back

Keep up great work!

Yours faithfully

d:
<img width="1440" alt="Screenshot 2019-09-02 at 14 17 50" src="https://user-images.githubusercontent.com/1715809/64114154-92971080-cd8c-11e9-9d0a-52d23c2f970f.png">

r: https://en.wikipedia.org/wiki/Repetitive_strain_injury

**Comment by majora2007** [comment]
I like this idea, but I do worry about users which are vision impaired or use assistive technology and how the shortcuts might interfere there. 

I would say that it is very common when a modal opens, focus is shifted to it, actionable elements should be focusable (you can always add tabindex="0" to force it to be tabbable). When you press Escape, modal should always close. 

I think these + the manual import checkbox labels being clickable (aka linked with id) would be huge improvements.

**Comment by ldexterldesign** [comment]
Hi @majora2007,

Thanks for reply

The [my] major issue ATM is that Sonarr doesn't appear to shift focus to modals, meaning the user must tab all the way through the page in order to interact with keyboard, so this would be the first improvement step.

From brief research simply adding `tabindex=0` somewhere inside the modal when it's added to the DOM would be enough to facilitate keyboard focus

The addition of ARIA would handle the assistive technologies but this would need testing and is probably beyond the scope of this issue

Hope this helps

Regards

**Comment by majora2007** [comment]
Agreed 100%. They can add tabindex=0 on modal div and screen readers like NVDA should be able to do the rest.

**Comment by ldexterldesign** [comment]
😘
