### ISSUE TITLE
add a sort so that continuing shows are all at the top and ended ones at bottom

### ISSUE THREAD

**Issue by the-xlr8r** [Sonarr/Sonarr#3293]
please add a sort view (ended/continuing) so that continuing shows are seperated from ended ones at bottom (or top depending on view selected)
this makes it easier to see what shows you can binge-watch and not worry about next episodes.
I use this to watch old ended shows and sickbeards view makes this easy, would be great if Sonarr could do same ?

see screenshot

[https://i.postimg.cc/J4sKTx9c/active.png](url)

**Comment by markus101** [comment]
In v3 you can sort the status/monitored column and it'll do just that.

**Comment by the-xlr8r** [comment]
Ah cool

The little arrow is missing until u actually click where its supposed to be

[cid:image001.png@01D5633A.8A530FD0]

Then when u click the area at the red arrow, it appears. Minor bug

[cid:image002.png@01D5633A.8A530FD0]

**Comment by markus101** [comment]
Sort arrows aren't shown until the column is actually being sorted, that is intentional, not a bug. We do not have plans to show icons for sortable icons when they are not the active sort.

P.S. If you're trying to add images it's not working.
