### ISSUE TITLE
V3 beta - tv shows appear stuck on "downloading" after they are already downloaded ?

### ISSUE THREAD

**Issue by the-xlr8r** [Sonarr/Sonarr#3295]
after having imported all my existing shows on my nas into Sonarr

Im noticing all freshly donloaded tv shows now (stuck) as "downloading" even when they are already downloaded ?

[https://i.postimg.cc/85XBnRZ6/downloading.png](url)

how do i change the status of these ?

**Comment by markus101** [comment]
They'll show as downloading if Sonarr has a release in Activity: Queue for that episode that has not been imported. You'll need to look at Activity: Queue to see why it hasn't imported those files and possible the debug logs as well. Please open a thread on the forums or subreddit for troubleshooting further if necessary.
