### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by Stanzilla** [Sonarr/Sonarr#3300]
**Describe the problem**
A dark mode for the web UI

**Describe any solutions you think might work**
There's a pretty good guide by Google, https://material.io/design/color/dark-theme.html

I'd suggest a background color of #121212 as a start.

**Additional context**
I made this issue even though dark mode was touched on in https://github.com/Sonarr/Sonarr/issues/1943 but should be a separate thing, I think.

**Comment by markus101** [comment]
Closing in favour of #1943 we don't need two issues for the same thing. If implemented we can decide which direction to take.
