### ISSUE TITLE
please add metadata profile for mede8er owners

### ISSUE THREAD

**Issue by the-xlr8r** [Sonarr/Sonarr#3301]
these are the Metadata settings i used in sickbeard that worked perfectly. it would be great if these could be added to Sonarr's settings ? I want to migrate from Sickbeard but this issue is holding me back...

https://i.postimg.cc/wxC9vfc7/metadata.png

**Comment by markus101** [comment]
Based on the low interest in https://github.com/Sonarr/Sonarr/issues/386 we have no plans to implement mede8er metadata support. If someone is willing to open a PR with support for it, we'll review and accept if viable, but we have no plans to implement it on ourselves and won't be keeping this GHI open.

PS When opening an issue please use the templates.
