### ISSUE TITLE
Filling URL Base with any value causes a PortInUseException error on program startup

### ISSUE THREAD

**Issue by klutzydrummer** [Sonarr/Sonarr#3305]
### System Information/Logs

**Sonarr Version:**
v3.0.3.638

**Operating System:**
Windows 10 Home v1903

**.net Framework (Windows) or mono (macOS/Linux) Version:**
.net Framework v4.8.03752

**Link to Log Files (debug or trace):**
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/3613453/sonarr.debug.txt)

**Browser (for UI bugs):**
Firefox v69.0

### Additional Information
Program appears to crash after setting URL base, as the process remains open in task manager, but web ui becomes unresponsive.

Terminating the process and restarting it displays the error:
PortInUseException: Port 8989 is already in use, please ensure NzbDrone is not already running.

Manually deleting the URL Base in the config.xml file resolves the PortInUseException error
Have tried using several different URL Bases as options, but none seem to change anything.

Log is attached, but relevant sections seem to be

19-9-15 01:26:21.7|Info|OwinHostController|Listening on the following URLs:
19-9-15 01:26:21.7|Info|OwinHostController|  http://localhost:8989/sonarr/
19-9-15 01:26:21.7|Info|OwinHostController|  http://localhost:8989/
19-9-15 01:26:21.8|Debug|OwinAppFactory|Attaching NzbDroneVersionMiddleWare to host
19-9-15 01:26:21.8|Debug|OwinAppFactory|Attaching SignalRMiddleWare to host
19-9-15 01:26:21.8|Debug|OwinAppFactory|Attaching NancyMiddleWare to host
19-9-15 01:26:22.0|Info|SonarrBootstrapper|Starting Web Server
19-9-15 01:26:23.0|Fatal|WindowsApp|EPIC FAIL

[v3.0.3.638] NzbDrone.Host.Owin.PortInUseException: Port 8989 is already in use, please ensure NzbDrone is not already running. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied

**Comment by markus101** [comment]
Try running Sonarr as an admin to properly register the URL base with Windows, by default what Sonarr can register is limited. Alternatively check the output of `netsh http show urlacl` for other entries for port 8989.

**Comment by markus101** [comment]
Closing until we have more details.
