### ISSUE TITLE
"uniqueid" tag missing in episode nfo file 

### ISSUE THREAD

**Issue by monisriz** [Sonarr/Sonarr#3308]
**Describe the bug**
In Sonarr generated episode nfo files "uniqueid " tag is not written. As per the Kodi documentation this tag is required (https://kodi.wiki/view/NFO_files/TV_shows#nfo_Tags_2).

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: Linux via docker container (https://hub.docker.com/r/linuxserver/sonarr/)

**Comment by markus101** [comment]
Please include all the requested information when opening issues and remove the portions that aren't relevant (version/system info is always relevant).
