### ISSUE TITLE
Error adding indexers to sonar from Jackett

### ISSUE THREAD

**Issue by mbell420** [Sonarr/Sonarr#3310]
I keep getting this error when trying to add indexers to Sonar from Jackett

Unable to connect to indexer: Error: ConnectFailure (Connection refused): 'http://127.0.0.1:9117/api/v2.0/indexers/eztv/results/torznab/api?t=caps&apikey=qer4o4jvtuzzrrc3mzqu3tmx8jffaouv'

Not sure what to do about everything I see or read says to do it the way I am using the Torznab custom tab paste api key in and paste the url from the copy torznab feed button on Jackett.
I have tried with multiple different indexers same error everytime.
Not sure what else to do.

**Comment by markus101** [comment]
Please open a thread on the forums for support.

Generally connection refused means the wrong port or a firewall blocked it.

**Comment by mbell420** [comment]
lots of help thanks for nothing. Thought this was the support forum guess not

**Comment by mbell420** [comment]
if your talking about the sonar support thread why sonar works fine can add other indexers just not from jackett
