### ISSUE TITLE
Error in a RSS Feed

### ISSUE THREAD

**Issue by Rootax** [Sonarr/Sonarr#3311]
Hi,

**Describe the bug**
For a few days now,  I've the message "Invalid request Validation failed: 
 -- Indexer feed is not supported: Failed to find a valid download url in the feed."

With this rss fedd => https://ru.erai-raws.info/rss-1080/

It was working perfectly  for months. I've this feed under other apps like qbittorrent, working fine... I deleted it and added it again, no luck...

**Logs**
[v2.0.0.5338] NzbDrone.Core.Indexers.Exceptions.UnsupportedFeedException: Failed to find a valid download url in the feed.
   � NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.ValidateReleases(TorrentInfo[] releases, TorrentRssIndexerSettings indexerSettings) dans M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:ligne 274
   � NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.GetGenericTorrentRssParserSettings(IndexerResponse response, TorrentRssIndexerSettings indexerSettings) dans M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:ligne 144
   � NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.GetParserSettings(IndexerResponse response, TorrentRssIndexerSettings indexerSettings) dans M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:ligne 77
   � NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.Detect(TorrentRssIndexerSettings indexerSettings) dans M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:ligne 65
   � NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.DetectParserSettings(TorrentRssIndexerSettings indexerSettings) dans M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:ligne 55
   � NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.<>c__DisplayClass4_0.<GetParser>b__0() dans M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:ligne 32
   � NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) dans M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Cache\Cached.cs:ligne 81
   � NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.GetParser(TorrentRssIndexerSettings indexerSettings) dans M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:ligne 32
   � NzbDrone.Core.Indexers.TorrentRss.TorrentRssIndexer.GetParser() dans M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssIndexer.cs:ligne 31
   � NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() dans M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:ligne 333

(I don't have a "m:" btw...)

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: W10 1903
 - .net Framework (Windows) or mono (macOS/Linux) Version: Latest... ?

**Comment by markus101** [comment]
The RSS feed as it is right now looks fine and tests fine in Sonarr as long as `Allow Zero Size` is enabled.

Bets guess they broke something on the feed and have since fixed it.

> I don't have a "m:" btw...

It's not related to your system. Sonarr is compiled in that directory in our build system.
