### ISSUE TITLE
Add copy/move toggle for Completed Download Handling

### ISSUE THREAD

**Issue by Wundark** [Sonarr/Sonarr#3312]
**Describe the problem**
When complete download handling occurs, I don't want the source files to be deleted.

**Describe any solutions you think might work**
In addition to the complete download handling process. It would be great if there was a toggle to switch between copy and move.

**Comment by markus101** [comment]
Torrents will be copied/hardlinked when they are still seeding, but we don't have plans for copying in other cases.
