### ISSUE TITLE
DownloadedEpisodeScan API sometimes returns results from the previous request resulting in the task not completing

### ISSUE THREAD

**Issue by bugmancx** [Sonarr/Sonarr#3315]
I have a batch job which will process a number of directory full of episodes (each in its own subdir) that are ready for import and when the DownloadEpisodeScan request is made via curl, sometimes Sonarrv3 will return the results from the previous request instead of the one I made.

I have seen this happen consistently, in that it seems to happen randomly but still fairly often, and each time the problem is the same - the API returns the output from the previous request instead of the current one.

The script sleeps for 1 second between each request so as not to flood.

Here's the output from a successfully processed job and then the next request which returns the output from the previous request instead of the one requested. Note that the job "id" is the same even though the curl request was different.

`
/usr/bin/curl http://server.local:8989/api/command -X POST --header 'Content-Type: Application/JSON' --header 'X-Api-Key: redacted' --data '{"name": "DownloadedEpisodesScan", "path": "/media/automation/stage/The_100_S02E01_x265_1080p_BluRay_30nama_30NAMA.job"}'
{
  "name": "DownloadedEpisodesScan",
  "body": {
    "path": "/media/automation/stage/The_100_S02E01_x265_1080p_BluRay_30nama_30NAMA.job",
    "importMode": "auto",
    "sendUpdatesToClient": false,
    "updateScheduledTask": true,
    "completionMessage": "Completed",
    "requiresDiskAccess": false,
    "isExclusive": false,
    "name": "DownloadedEpisodesScan",
    "trigger": "manual",
    "suppressMessages": false
  },
  "priority": "normal",
  "status": "queued",
  "queued": "2019-09-24T11:22:53.376561Z",
  "trigger": "manual",
  "state": "queued",
  "manual": true,
  "startedOn": "2019-09-24T11:22:53.376561Z",
  "sendUpdatesToClient": false,
  "updateScheduledTask": true,
  "id": 470174
}

/usr/bin/curl http://server.local:8989/api/command -X POST --header 'Content-Type: Application/JSON' --header 'X-Api-Key: redacted' --data '{"name": "DownloadedEpisodesScan", "path": "/media/automation/stage/The_100_S02E03_x265_1080p_BluRay_30nama_30NAMA.job"}'
{
  "name": "DownloadedEpisodesScan",
  "body": {
    "path": "/media/automation/stage/The_100_S02E01_x265_1080p_BluRay_30nama_30NAMA.job",
    "importMode": "auto",
    "sendUpdatesToClient": false,
    "updateScheduledTask": true,
    "completionMessage": "Completed",
    "requiresDiskAccess": false,
    "isExclusive": false,
    "name": "DownloadedEpisodesScan",
    "trigger": "manual",
    "suppressMessages": false
  },
  "priority": "normal",
  "status": "started",
  "queued": "2019-09-24T11:22:53.376561Z",
  "started": "2019-09-24T11:22:53.379695Z",
  "trigger": "manual",
  "state": "started",
  "manual": true,
  "startedOn": "2019-09-24T11:22:53.376561Z",
  "stateChangeTime": "2019-09-24T11:22:53.379695Z",
  "sendUpdatesToClient": false,
  "updateScheduledTask": true,
  "id": 470174
`

Using version: 3.0.0.348

**Comment by Taloth** [comment]
Please update Sonarr, you're stuck on a rather old version. (see [here](https://sonarr.tv/#downloads-v3-linux))

The api returns the existing command if it's already running with the same parameters. Somewhere last year there was a bug fixed in the logic that compared those parameters. I think you have a version from before that.
