### ISSUE TITLE
Task of sonarr like refresh series.

### ISSUE THREAD

**Issue by postmanpaul** [Sonarr/Sonarr#3316]
i whould like to change the refresh time of tasks.
i have so many series in my sonarr, and it Goes over the 12 hours, then start again, so its 24/7 Scanning... i´m using sonarrV3, its whould be awsome to control tasks littel. even can i work out a manual/auto script refresh, if its possible to put some tasks on hold or someting..

Refresh Series | 11 hours ago | 11 hours ago

Greets.

PostmanPaul-Ozzy

**Comment by Taloth** [comment]
Yeah, scanning doesn't take that long. There's likely a performance issue somewhere. Probably mediainfo scanning vids? If your storage is in the cloud then that would slow that down too. Enable trace level logs and check those to see what it's actually doing.

_You didn't provide any information like exact Sonarr version, OS, etc. That's not helpful at all. I understand that you didn't open this issue to troubleshoot, but please try to provide info like that whenever you're posting issues on projects, devs love details._

**Comment by postmanpaul** [comment]
Version
3.0.2.601
Package Version
3.0.2.601-ls124 by linuxserver.io
Mono Version
5.20.1.34
AppData directory
/config
Startup directory
/usr/lib/sonarr/bin

we have over 500TB of data.. 💃 
alot of the work, alot of media is by rar2fs.  

Greets Postmanpaul 👯‍♂

**Comment by Taloth** [comment]
Tnx for the info. So the mediainfo scan is likely going to be slightly slower with that rar2fs, but I wouldn't expect it to be noticable much assuming rar2fs can do random seeks. You didn't mention cloud so i'm going to assume it's a local storage rack.

Lemme know what the trace logs tell you. You should be able to follow the refresh going through it's steps. Pay particular attention to the VideoFileInfoReader / MediaInfo.

**Comment by markus101** [comment]
Closing until we have more info.
