### ISSUE TITLE
Incorrect number of episodes / color

### ISSUE THREAD

**Issue by Treverr** [Sonarr/Sonarr#3318]
**Describe the bug**
Sonarr shows wrong number of episodes for the complete season

**Screenshots**
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/5624521/65792296-500ced80-e118-11e9-8b96-5cfb6a2e88bf.png">

**Logs**
[logs 2.zip](https://github.com/Sonarr/Sonarr/files/3664056/logs.2.zip)

**System Information**

 - Sonarr Version: [e.g. 2.0.0.1] 2.0.0.5338 
 - Operating System: [e.g. Windows 10] Ubuntu 18.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
 - OS: [e.g. Windows] Ubuntu 18.04
 - Browser: [e.g. chrome, firefox] Safari
 - Version: [e.g. 22] 

**Additional context**
It should be showing this red with the correct number of total episodes

**Comment by markus101** [comment]
They're unmonitored, thus not missing. Monitor them and it'll reflect that.
