### ISSUE TITLE
Manual Import Screen - quick select and sorting

### ISSUE THREAD

**Issue by aspratt** [Sonarr/Sonarr#3319]
**Describe the problem**
A clear and concise description of the problem you're looking to solve.

**Describe any solutions you think might work**
A clear and concise description of any solutions or features you've considered.

**Additional context**

**Comment by markus101** [comment]
Please fill out the template and elaborate on what you're looking for, there are many Manual Import screens.

**Comment by markus101** [comment]
Closing until we have more information.

**Comment by danstoll** [comment]
I think I know what the poster was asking. I've wondered this myself. 

In Radar, when you manually import, you can select the movie the file corresponds with and forces the match. This would be amazing in Sonarr. Especially after doing a bulk download and the file naming is off, and you need to go and adjust all the file names and sometimes the folders, so the import recognises. If would be fantastic if in the manual importer window you could select the show and episode the file corresponds with. and then on import, that match is forced and obviously get named appropriately based on your settings.

**Comment by markus101** [comment]
That's exactly how manual import works in Sonarr.

**Comment by danstoll** [comment]
lol... i was playing around with this, and clicking on the empty space and the sector pops up. bravo.. What threw me was in Radarr there is a link that says "Click here" in sonar it is just empty. :)
