### ISSUE TITLE
Missing seasons present in TVDB

### ISSUE THREAD

**Issue by arielbeje** [Sonarr/Sonarr#3320]
**Describe the bug**
While trying to add a new TV show, I noticed it was missing seasons which were present in [TVDB](https://www.thetvdb.com/series/hapijamot).

**Screenshots**
![image](https://user-images.githubusercontent.com/19347259/65874348-4987ab80-e38e-11e9-8053-2a3bc02559c3.png)
![image](https://user-images.githubusercontent.com/19347259/65874491-7c31a400-e38e-11e9-83e5-1234505848f1.png)

**Logs**
```
19-9-30 14:28:19.2|Info|AddSeriesService|Adding Series [85157][HaPijamot] Path: [F:\TV Shows\HaPijamot]
19-9-30 14:28:19.2|Info|RefreshSeriesService|Updating Info for HaPijamot
19-9-30 14:28:19.3|Warn|MediaCoverMapper|File C:\ProgramData\NzbDrone\MediaCover\166\poster.jpg not found
19-9-30 14:28:19.4|Info|RefreshEpisodeService|Starting episode info refresh for: [85157][HaPijamot]
19-9-30 14:28:19.4|Info|RefreshEpisodeService|Finished episode refresh for series: [85157][HaPijamot].
19-9-30 14:28:19.4|Info|DiskScanService|Scanning disk for HaPijamot
19-9-30 14:28:19.4|Info|DiskScanService|Completed scanning disk for HaPijamot
19-9-30 14:28:19.4|Info|SeriesScannedHandler|[HaPijamot] was recently added, performing post-add actions
19-9-30 14:28:19.6|Info|MediaCoverService|Downloading Fanart for [85157][HaPijamot] https://www.thetvdb.com/banners/fanart/original/85157-4.jpg
19-9-30 14:28:19.9|Info|MediaCoverService|Downloading Banner for [85157][HaPijamot] https://www.thetvdb.com/banners/graphical/85157-g.jpg
19-9-30 14:28:20.0|Info|MediaCoverService|Downloading Poster for [85157][HaPijamot] https://www.thetvdb.com/banners/posters/5b5b1af4d5e69.jpg
19-9-30 14:28:20.2|Info|MetadataService|Series folder does not exist, skipping metadata creation
```

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: Windows 10 Enterprise 1903, OS Build 18362.356 (64bit)
 - .net Framework 4.8

 - Browser: Firefox
 - Version: 69.0.1

**Comment by M0UL** [comment]
there are no episodes titles  in english with is bare minimum for sonarr to work.

**Comment by markus101** [comment]
Season 8 has no titles and no dates, so they are completely ignored by Sonarr. Once the series is updated on TheTVDB it'll take approximately 90 minutes before Sonarr is able to update and see the changes.
