### ISSUE TITLE
[Feature Request] Custom Search Format

### ISSUE THREAD

**Issue by zero77** [Sonarr/Sonarr#3321]
**Describe the problem**
When searching for an episode the default search format seams to be `series name and data` then `series and episode number`.
But, sometimes this does not return any results in particular this can happens with documentaries.

**Describe any solutions you think might work**
Instead, can you add the ability for users to change the search format to something different, for example: `series name and data` then `episode name`.

**Comment by markus101** [comment]
Related issues:

https://github.com/Sonarr/Sonarr/issues/332
https://github.com/Sonarr/Sonarr/issues/1128
