### ISSUE TITLE
add VFi in search of the French language

### ISSUE THREAD

**Issue by Floflobel** [Sonarr/Sonarr#3324]
Hello,
I have a movie that doesn't want to download automatically for the following reason: "French is wanted, but found English". 
My language is set to French but it doesn't detect VFi and thinks it's English.

Example movie name: "Vert.Emeraude.2016.VFi.1080P.mHD.X264.AC3-ROMKENT"

VFi (International French version) = VFF = Truefrench 

Is it possible to add this tag to the search list? 

Best regards,

**Comment by markus101** [comment]
Did you mean to post this to https://github.com/Radarr/Radarr?

**Comment by Floflobel** [comment]
Absolutely, thank you.
