### ISSUE TITLE
Scene Mappings conflict for tvdbids 277568,369143

### ISSUE THREAD

**Issue by r4m0n** [Sonarr/Sonarr#3325]
[v2.0.0.5338] NzbDrone.Core.DataAugmentation.Scene.InvalidSceneMappingException: Scene Mappings contains a conflict for tvdbids 277568,369143. Please n
otify Sonarr developers. ([Erai-raws] Babylon - 01 [720p][Multiple Subtitle]).

Series involved:
https://www.thetvdb.com/series/babylon-2014
https://www.thetvdb.com/series/babylon-2019

It's a new Anime conflicting with an older series with the same name, not sure if this will be an easy fix...

**Comment by joridiculous** [comment]
Just posted the same on the subReddit. Floods the logs :|

**Comment by NunoVilhenaSantos** [comment]
Hi,

Same here...

Couldn't process release.: Scene Mappings contains a conflict for tvdbids 277568,369143.
Please notify Sonarr developers. ([Erai-raws] Babylon - 01 [1080p][Multiple Subtitle])

Thanks for the amazing work.

**Comment by markus101** [comment]
Best we can do here is try and limit the original alias to specific release groups, this will likely lead to rejected/mismatched episodes because the anime releases use the same already used title. Worse for the previous series than the anime release, but it's lose-lose.

I've updated the alias.
