### ISSUE TITLE
Automate searching torrent indexers for episodes (RSS doesn't work for me as my laptop is usually off for days.)

### ISSUE THREAD

**Issue by Rajeh16** [Sonarr/Sonarr#3327]
I want the ability to search wanted/missing episodes on a schedule or interval as my laptop is usually off for days and by the time it is turned on episodes won't be coming up in RSS anymore.

**Comment by markus101** [comment]
Sonarr will already page back in RSS looking for results and, but multiple days will likely still be problematic. At this time we don't have plans for automated searches.
