### ISSUE TITLE
Multiple errors with Runtime 0,  but files are valid, not removed from DL client

### ISSUE THREAD

**Issue by neuman1812** [Sonarr/Sonarr#3328]
**Describe the bug**
Example: [/media/Plex/complete/Last.Week.Tonight.with.John.Oliver.S06E26.720p.WEB-DL.AAC2.0.H/Last.Week.Tonight.with.John.Oliver.S06E26.720p.WEB-DL.AAC2.0.H.mkv] has a runtime of 0, is it a valid video file?

**Screenshots**

![](https://i.imgur.com/eyfrBlV.png)

Logs: https://hastebin.com/hahuguxaqo.rb

**System Information**
Version 3.0.3.644
Package Version 3.0.2
Mono Version 6.4.0.198
AppData directory /var/lib/sonarr
Startup directory /usr/lib/sonarr/bin
Mode Console

**UI Bugs:**
 - OS: Rasbian Stretch
 - Browser: Chrome
- Deluge 1-13-15

**Additional context**
This error is showing up with multiple files/series.  The torrents are not getting removed from deluge client, leaving them in a paused state and causing them not to be imported into sonarr and consequently into plex.  The video files are valid and playable.

For context I have the following setup on my deluge client:

/media/Plex/Working -- Active torrents
/media/Plex/Complete -- Completed Torrents
/Media/Plex/TvShows/(show name) -- Data Directory/

**Comment by markus101** [comment]
This will happen when libmediainfo can't process the file; make sure you're running the latest available version (not the latest version in the default Raspbian repo).

If it's still an issue libmediainfo may need to make changes on their side, though that is rare.
