### ISSUE TITLE
Mass Editor's Root Folder change not working if any series path ends with "/"

### ISSUE THREAD

**Issue by vegahub** [Sonarr/Sonarr#3329]
In the Mass Editor if any of the selected Series has a path ending with "/", changing the Root folder does nothing.

Sonarr Version: [3.0.3.644]

**Comment by markus101** [comment]
Please fill out the appropriate template and include the log files.

**Comment by markus101** [comment]
Unable to reproduce, we'll need more info if it's still an issue.
