### ISSUE TITLE
Odd Debug Logs

### ISSUE THREAD

**Issue by nickkecooper** [Sonarr/Sonarr#3330]
Hey guys I wanted to see if anyone else saw some odd download phrasing happening in their debug logs. I have Sonarr looking at shows that are not in my list of shows. For example one line reads

`19-10-8 23:16:31.8|Debug|Parser|Parsing string 'Real German Latina Street Whore Pay For Sex in Berlin 1080p'
19-10-8 23:16:31.9|Debug|Parser|Unable to parse Real German Latina Street Whore Pay For Sex in Berlin 1080p
19-10-8 23:16:31.9|Debug|Parser|Parsing string 'Real German Latina Street Whore Pay For Sex in Berlin 1080p'
19-10-8 23:16:31.9|Debug|Parser|Unable to parse Real German Latina Street Whore Pay For Sex in Berlin 1080p
19-10-8 23:16:31.9|Debug|ParsingService|No matching series Real German Latina Street Whore Pay For Sex in Berlin 1080p`

Any information on how to stop this or if this is normal that would be great!! TIA

**Comment by markus101** [comment]
Not odd at all, that's how RSS feeds work, they aren't just lists of series you've added.
