### ISSUE TITLE
System.IO.IOException: Win32 IO returned 50

### ISSUE THREAD

**Issue by Luke-Thomas-Wood** [Sonarr/Sonarr#3332]
**Description**
Torrents are downloaded with qBittorrent to a folder on a NAS called 'torrents' mounted on my machine at /mnt/torrents. My entire NAS is mounted at /mnt/alexandria. Sonarr is able to send the download request to qBittorrent which can successfully download the file to /mnt/torrents, but Sonarr fails when trying to import the file with "Win32 IO returned 50"

**Logs**
https://pastebin.com/pG4V4bHB

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System:     Ubuntu 18.04.3 LTS
 - Mono Version: 6.0.0.327

**Comment by markus101** [comment]
Mono 6 changed disk access to use .net core and has had several issues related to that, especially with SMB shares.

Downgrading to mono 5.20 is advisable for the time being.

If you're still having issues please open a thread on the forums for troubleshooting.
