### ISSUE TITLE
Modals are re-rendered when rotating

### ISSUE THREAD

**Issue by bradtn** [Sonarr/Sonarr#3333]
While on Android device, only tested in Chrome. If you go to the manual import menu and choose either interactive import or quick import and then presented with your list of items once you rotate your device either into landscape mode or portrait mode you will be kicked out of your import where you must choose your import method again. Rotating the device will cause you to be kicked back to import method menu everytime no matter if you start your import in portrait or landscape

**System Information**
 - Sonarr Version: 3.0.3.644
 - Operating System: Unraid docker 
**UI Bugs:**
 - OS: Android 
 - Browser: Chrome

**Comment by Qstick** [comment]
What device, android version, and browser version are you using. I don't see this behavior on a pixel 2 running Android 10 and chrome 77.0. Could be some weird resolution thing..

**Comment by bradtn** [comment]
I have a Samsung s10+, android version is 9, chrome version is 77.0.3865.116. My devices display is set to the wqhd+ resolution which is 3040x1440

**Comment by bradtn** [comment]
For fun and for testing purposes I dropped my. Device resolution to FHD+ which is 2280x1080 and also dropped it to HD+ 1520x720 same issue persists on all. Maybe something to do with the way Samsung does rotation?

**Comment by markus101** [comment]
I can reproduce in Chrome by drastically changing the width. Not sure why it's happening, but easy enough to reproduce.
