### ISSUE TITLE
Manual Import: Allow sorting by size

### ISSUE THREAD

**Issue by bradtn** [Sonarr/Sonarr#3334]
When going to do a manual importation sonarr is quite good at figuring out what episode is what and so forth and I don't need to make nearly any changes when episode names match

When sonarr sees a file name which it can't parse or match to a show it will not select it automatically for importation for this reason which is great

The issue occurs for sample files when I am going to do a manual importation sonarrs red exclamation will state that it knows/believes this file is a sample but because the episode name etc match it preselects the episode season etc and by default enables it for importation which can be a big time sink unselecting all the samples

So my request is simple anything that sonarr detects as sample or likely a sample not be automatically set for importation even if episode/season names etc are correct.
 
And or maybe implement a file size threshold where it won't auto set certain file sizes for importation? 

Thanks love the software

**Comment by markus101** [comment]
Deselection based on rejection reason is covered by https://github.com/Sonarr/Sonarr/issues/1127

> And or maybe implement a file size threshold where it won't auto set certain file sizes for importation?

Samples are not detected by size, we’re not going to use size to determine whether or a should be selected. We can however allow sorting by size and then you can shift click to select/deselect items. I’ll update the title to reflect that and the remainder of the issue will be covered by the existing issue.

**Comment by bradtn** [comment]
Understandably so, but even with sonarr detecting it as a sample file in general not possible?

**Comment by markus101** [comment]
Not currently, it’s also a slippery slope, if we auto deselect what we detected as sample why wouldn’t we automatically deselect things that are reject for reason x, y and z?

**Comment by bradtn** [comment]
Agreed but I think 99.99% of people don't import them lot less slippery =)
