### ISSUE TITLE
TVshow 1992 - 1993 - 1994 

### ISSUE THREAD

**Issue by fontes31** [Sonarr/Sonarr#3335]
Iam trying to search episodes for the season 2 and 3 of the italian serie 1992 - 1993 - 1994.
For the season 1, ok no problem
For the season 2 and 3 i cannot get any episode
The strange is if i try a manual search on the S1E1 i get the S2E1 and S3E1 and so on.
Iam running Version 2.0.0.5338 on windows OS

**Comment by markus101** [comment]
Please use the templates when filling out issues, but for now, open a thread on the forums for support.
