### ISSUE TITLE
Maybe Add "1st, 2nd, 3rd, 4th Season" and so on to search possibilities?

### ISSUE THREAD

**Issue by v9999** [Sonarr/Sonarr#3336]
**Describe the problem**
There's an anime series group I download from that's been renaming their releases like this for the current season: "[Group1] Some anime 4th Season - 01 [1080p][Multiple Subtitle].mkv" . 

Sonarr won't list that episode in its search, but it will show, for instance: 
[Group2] Some anime - 64 [1080p].mkv (which shows that Sonarr picks absolute numbering)
[Group3] Some anime S4 - 01 (64) [SoftSub-720p].mkv (which shows that Sonarr picks seasonal episodes if there's S4 present).

**Describe any solutions you think might work**
So, the idea is to make sonarr search also for "4th season, 3rd season, 2nd season, 1st season" or simply "4th, 3rd, 2nd and 1st" or something similar while searching for an episode from the respective season.

If you guys want to try it out, you can use Boku no Hero Academia (My hero academia) season 4, episode 1, from Erai-Raws, found on Nyaa.

**Comment by markus101** [comment]
Aliases for anime come from TheXEM.de and it looks like that's already an alias for it. http://thexem.de/xem/show/4317

If more need to be added, that's the place to do it.

**Comment by M0UL** [comment]
no point in adding that alias since it use a different numbering than thexem has.
