### ISSUE TITLE
Expand on illegal characters

### ISSUE THREAD

**Issue by Iguana9999phil** [Sonarr/Sonarr#3337]
Is it possible to expand the illegal characters feature? Or possibly make it customizable? I'm using Plex autoscan and that one seems to have an issue when adding anything containing with a "&" character. When using "CleanTitle" this would be replaced (If I recall correctly) with "and" but it would also remove the parentheses around the year which would mess up Plex scanning.

**Comment by markus101** [comment]
We don't have plans to to expand it or making it customizable.

I haven't noticed issues with `&` causing issues in Plex scanning, probably worth raising it on their forums. Year outside of brackets also shouldn't be that big of a deal to the scanner, it's not that strict in most cases.
