### ISSUE TITLE
Default tag when adding new show.

### ISSUE THREAD

**Issue by deltafoxnine** [Sonarr/Sonarr#3339]
I've installed v3 and so far i love it. It is now possible to set a tag when adding a show. But would it be possible to set a default tag when adding shows?

Right now I have a release profile (untagged), which applies to all shows - by sonarr design.
When I want to add a show - and not inherit the untagged release profile - I have to make the untagged profile tagged, and update all the other shows with that tag.

Another solution would also be to make the option to exclude a certain profile, when adding a tag or show.

I hope this makes sense.

Right now I'm going to make the untagged profile tagged, and update all the shows. I just hope I remember to set the default tag for newly added shows in the future :)   

Thanks in advance.

**Comment by markus101** [comment]
Same as other settings when adding a series they are remembered in the browser, so as long as you use the same browser each time the tags will be remembered, if you use a different browser you'll need to set them the first time.
