### ISSUE TITLE
MediaInfo Library could not be loaded libmediainfo.so.0	

### ISSUE THREAD

**Issue by devIlluSioN** [Sonarr/Sonarr#3343]
Hello i have this error

> MediaInfo Library could not be loaded libmediainfo.so.0

on QNAP TS218.
I already have read all post about this error and Qmono don't have this library 
Is someone able to give me this file ? 

**System Information**

 - Sonarr Version: 3.0.3.644
 - Operating System: QNAP
 - mono : 5.20.1.19

**Comment by markus101** [comment]
This will either come as a dependency of the QSonarr package or along with it. It is not a package we maintain or can provide libmediainfo for. You may have better luck on the qnap forums.
