### ISSUE TITLE
Create an installation guide for CentOS 8 

### ISSUE THREAD

**Issue by bcornw2** [Sonarr/Sonarr#3344]
**CentOS 8 has been out for a few weeks now, and RHEL 8 long before that**
I can try to loosely follow the CentOS 7 installation guide for Sonarr, and while I was able to get it up and running in conjunction with SABnzbd, some packages from the EPEL for CentOS 8 are broken. Most notably, the package:  `libmediainfo`.

This package requires the dependency of `libtinyxml2` but that is a broken install on CentOS 8. Some other factors of the OS upgrade have caused it to be different enough from the CentOS 7 that the installation guide can not be adhered to. 

**Please confirm that the CentOS 8 build that requires libmediainfo has access to the required dependencies. Even better would be to build a Git repository that already includes all of this stuff.**
Thank you.

**Comment by markus101** [comment]
We don't maintain a package for centos and the installation instructions are on the wiki and contributed by someone else.

Sonarr needs libmediainfo, if there is an issue with that on centos 8 then a new libmedia package would need to be provided, but that isn't something we can provide and it doesn't look like it's something mediainfo has published a package for. https://mediaarea.net/en/MediaInfo/Download/CentOS

**Comment by MarkProminic** [comment]
Hope this helps:

https://github.com/Sonarr/Sonarr/wiki/Installation-CentOS-8

**Comment by freiheit** [comment]
EPEL8 has mediainfo and libmediainfo packages that work fine, and the instructions that @MarkProminic linked to include steps to get that installed.

**Comment by MarkProminic** [comment]
Centos 8 with Sonarr v3 Wiki has been created as well:

https://github.com/Sonarr/Sonarr/wiki/Installation-CentOS-8-V3-Beta

**Comment by Drazzilb08** [comment]
> Centos 8 with Sonarr v3 Wiki has been created as well:
> 
> https://github.com/Sonarr/Sonarr/wiki/Installation-CentOS-8-V3-Beta

Awesome. I'll get this up on https://wiki.servarr.com tomorrow some time.
