### ISSUE TITLE
Bad release name doesn’t parse quality correctly

### ISSUE THREAD

**Issue by Rumpa112** [Sonarr/Sonarr#3345]
**Describe the bug**
If you cant figure out the bug from the screenshot, go to bed.

This is identified as WEBDL 1080p
Legacies S02E02 This Year Will Be Different 1080p AMZN WEB-DL DDP5 1 H 264-KiNGS

Same name with dots instead of spaces is identified as HDTV 1080p ???
Legacies.S02E02.This.Year.Will.Be.Different.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS

**Screenshots**
![Untitled-1](https://user-images.githubusercontent.com/56738700/67119137-d207a800-f1e6-11e9-9e96-6302b499d220.png)

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: v3 latest
 - Operating System: win 10
 - .net Framework (Windows)

**UI Bugs:**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Additional context**
Rumpa

**Comment by markus101** [comment]
Please include the debug logs of the search.

**Comment by Rumpa112** [comment]
> 
> 
> Please include the debug logs of the search.

I don't have time to strip out all personal information.
According to the log.  Not the whole name is parsed. Probably because it contains dots and to long. 

> 19-10-19 08:53:03.4|Debug|DownloadDecisionMaker|Processing release 'Legacies.S02E02.This.Year.Will.Be.Different.1080p.AMZN.WEB...' from 'NoWhere'
19-10-19 08:53:03.4|Debug|Parser|Parsing string 'Legacies.S02E02.This.Year.Will.Be.Different.1080p.AMZN.WEB...'
19-10-19 08:53:03.4|Debug|Parser|Episode Parsed. Legacies - S02E02 
19-10-19 08:53:03.4|Debug|Parser|Language parsed: English
19-10-19 08:53:03.4|Debug|QualityParser|Trying to parse quality for Legacies.S02E02.This.Year.Will.Be.Different.1080p.AMZN.WEB...
19-10-19 08:53:03.4|Debug|Parser|Quality parsed: HDTV-1080p v1
19-10-19 08:53:03.4|Debug|Parser|Release Group parsed: 
19-10-19 08:53:03.4|Debug|AcceptableSizeSpecification|Beginning size check for: Legacies.S02E02.This.Year.Will.Be.Different.1080p.AMZN.WEB...
19-10-19 08:53:03.4|Debug|AcceptableSizeSpecification|Item: Legacies.S02E02.This.Year.Will.Be.Different.1080p.AMZN.WEB..., meets size constraints.
19-10-19 08:53:03.4|Debug|AlreadyImportedSpecification|Performing already imported check on report
19-10-19 08:53:03.4|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
19-10-19 08:53:03.4|Debug|UpgradableSpecification|Comparing preferred word score. Current: 500 New: 200
19-10-19 08:53:03.4|Debug|UpgradableSpecification|Existing item meets cut-off. skipping.
19-10-19 08:53:03.4|Debug|CutoffSpecification|Cutoff already met, rejecting.
19-10-19 08:53:03.4|Debug|LanguageSpecification|Checking if report meets language requirements. English
19-10-19 08:53:03.4|Debug|MaximumSizeSpecification|Maximum size is not set.
19-10-19 08:53:03.4|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
19-10-19 08:53:03.4|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. HDTV-1080p v1
19-10-19 08:53:03.4|Debug|QualityAllowedByProfileSpecification|Quality HDTV-1080p v1 rejected by Series' quality profile
19-10-19 08:53:03.4|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Legacies.S02E02.This.Year.Will.Be.Different.1080p.AMZN.WEB...
19-10-19 08:53:03.4|Debug|ReleaseRestrictionsSpecification|[Legacies.S02E02.This.Year.Will.Be.Different.1080p.AMZN.WEB...] does not contain one of the required terms: WEB-DL
19-10-19 08:53:03.5|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
19-10-19 08:53:03.5|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
19-10-19 08:53:03.5|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
19-10-19 08:53:03.5|Debug|UpgradableSpecification|Existing item has better quality, skipping
19-10-19 08:53:03.5|Debug|SeriesSpecification|Checking if series matches searched series
19-10-19 08:53:03.5|Debug|DelaySpecification|Ignoring delay for user invoked search
19-10-19 08:53:03.5|Debug|HistorySpecification|Skipping history check during search
19-10-19 08:53:03.5|Debug|MonitoredEpisodeSpecification|Skipping monitored check during search
19-10-19 08:53:03.5|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Existing file meets cutoff: WEBDL-1080p - English, [Permanent] HDTV-1080p is not wanted in profile, [Permanent] Does not contain one of the required terms: WEB-DL, [Permanent] Existing file on disk is of equal or higher preference: WEBDL-1080p v1 - English

**Comment by markus101** [comment]
The truncation is coming from your indexer, that’s not something Sonarr does (especially in the logs). In this case we can probably detect the quality properly with a fix, but if the quality was any more truncated that is going to fail.

**Comment by Rumpa112** [comment]
Bad release name? nothing wrong with the release name. If I click the link I get the torrent site where the full name is visible. I use Jackett if that's what you are referring to?

**Comment by markus101** [comment]
The release name being sent to Sonarr is truncated. Could be Jackett or the indexer doing that. Perhaps something to do with the indexer showing a truncated realease name in the results and Jackett using that.

**Comment by Rumpa112** [comment]
> 
> 
> The release name being sent to Sonarr is truncated. Could be Jackett or the indexer doing that. Perhaps something to do with the indexer showing a truncated realease name in the results and Jackett using that.

You are right hombre. Same thing happens on that indexer doing a manual search in Jackett =(
Do you have any contact with the devs over-there?
