### ISSUE TITLE
Torrents are not removed and files not deleted after torrents finish seeding and in paused state in Transmission.

### ISSUE THREAD

**Issue by vecnar** [Sonarr/Sonarr#3348]
**Describe the bug**
Torrents that completed seeding and in paused status are not removed from Transmission.

**Screenshots**
![CompletedDownloadHandling](https://user-images.githubusercontent.com/44214918/67204198-e45f2d00-f404-11e9-862f-bea476f28b4d.JPG)

**System Information**
 - Sonarr Version: 2.0.0.5338
 - Operating System: Linux mynas 4.4.167-1213-rockchip-ayufan-g34ae07687fce #1 SMP Tue Jun 18 20:44:49 UTC 2019 aarch64 GNU/Linu
 -  mono (Linux) Version:  5.20.1.34
running as docker on openmediavault.

**Additional context**
Radar manages to remove them so it appears to be problem with sonarr communicating or instructing transmission. From the logs i can see that status 0 is paused state which is because of transmission seeding limit  but not sure why nothing happens.
I tried to set seeding ratio on indexers as per [https://github.com/Sonarr/Sonarr/issues/2716](url) but didn't help.

**Logs**
Attaching trace log files but below i think is important information gathered from transmission calls.
Gets all transmission settings
`POST] http://transmission:9091/transmission/rpc: session-get(...)
HttpClient|Response content (1529 bytes): {"arguments":{"alt-speed-down":50,"alt-speed-enabled":false,"alt-speed-time-begin":540,"alt-speed-time-day":127,"alt-speed-time-enabled":false,"alt-speed-time-end":1020,"alt-speed-up":50,"blocklist-enabled":false,"blocklist-size":0,"blocklist-url":"http://www.example.com/blocklist","cache-size-mb":4,"config-dir":"/config/transmission-home","dht-enabled":true,"download-dir":"/data/Complete","download-dir-free-space":2394242826240,"download-queue-enabled":true,"download-queue-size":5,"encryption":"preferred","idle-seeding-limit":30,"idle-seeding-limit-enabled":false,"incomplete-dir":"/data/Incomplete","incomplete-dir-enabled":true,"lpd-enabled":false,"peer-limit-global":200,"peer-limit-per-torrent":50,"peer-port":53503,"peer-port-random-on-start":false,"pex-enabled":true,"port-forwarding-enabled":false,"queue-stalled-enabled":true,"queue-stalled-minutes":30,"rename-partial-files":true,"rpc-version":15,"rpc-version-minimum":1,"script-torrent-done-enabled":false,"script-torrent-done-filename":"","seed-queue-enabled":false,"seed-queue-size":10,"seedRatioLimit":1.5000,"seedRatioLimited":true,"speed-limit-down":100,"speed-limit-down-enabled":false,"speed-limit-up":100,"speed-limit-up-enabled":false,"start-added-torrents":true,"trash-original-torrent-files":false,"units":{"memory-bytes":1024,"memory-units":["KiB","MiB","GiB","TiB"],"size-bytes":1000,"size-units":["kB","MB","GB","TB"],"speed-bytes":1000,"speed-units":["kB/s","MB/s","GB/s","TB/s"]},"utp-enabled":false,"version":"2.92 (14714)"},"result":"success"}
`

Below is information about torrents and sitting in paused state.
`[POST] http://transmission:9091/transmission/rpc: torrent-get(...)
{"arguments":{"torrents":[{"downloadDir":"/data/Complete/tv-shows","downloadedEver":1103725410,"errorString":"","eta":-1,"hashString":"9f22224a22dad8bea89dd0e3c80bd4a1d4d94350","id":1,"isFinished":true,"leftUntilDone":0,"name":"the.block.au.s15e45.720p.hdtv.x264-orenji[eztv].mkv","seedRatioLimit":1.5000,"status":0,"totalSize":1074818393,"uploadedEver":1656094795},{"downloadDir":"/data/Complete/tv-shows","downloadedEver":938514084,"errorString":"","eta":-1,"hashString":"af9787b4e4f63e8201304717c8afff0a472b0670","id":2,"isFinished":true,"leftUntilDone":0,"name":"Law.and.Order.SVU.S21E04.720p.HDTV.x264-KILLERS[rarbg]","seedRatioLimit":1.5000,"status":0,"totalSize":907876463,"uploadedEver":1407873703},{"downloadDir":"/data/Complete/movies","downloadedEver":1732163238,"errorString":"","eta":-1,"hashString":"d064b8c21eb9824b6c8b480ca5eb6ef8d6bc068a","id":3,"isFinished":true,"leftUntilDone":0,"name":"Shaft.2019.REPACK.1080p.WEBRip.1600MB.DD5.1.x264-GalaxyRG[TGx]","seedRatioLimit":1.5000,"status":0,"totalSize":1721332914,"uploadedEver":2598298947},{"downloadDir":"/data/Complete/tv-shows","downloadedEver":593670793,"errorString":"","eta":-1,"hashString":"eff946d4f9c653413a2c60f62938d095b5579533","id":4,"isFinished":true,"leftUntilDone":0,"name":"Gold.Rush.S10E02.480p.x264-mSD[eztv].mkv","seedRatioLimit":1.5000,"status":0,"totalSize":586975279,"uploadedEver":891683815},{"downloadDir":"/data/Complete/tv-shows","downloadedEver":457921613,"errorString":"","eta":-1,"hashString":"b4193b748abc56b8618503c7fdcfff690366dc02","id":5,"isFinished":true,"leftUntilDone":0,"name":"the.block.au.s15e44.hdtv.x264-fqm[eztv].mkv","seedRatioLimit":1.5000,"status":0,"totalSize":422611411,"uploadedEver":687213110}]},"result":"success"}
`
[sonarr.trace.1.txt](https://github.com/Sonarr/Sonarr/files/3750664/sonarr.trace.1.txt)

**Comment by markus101** [comment]
After the seeding limits were added there were additional fixes that only landed in v3. By the time they landed we were no longer backporting changes, so v2 still has issues with those limits and transmission.

At this time the only work around would be to upgrade to the v3 beta.

**Comment by vecnar** [comment]
> After the seeding limits were added there were additional fixes that only landed in v3. By the time they landed we were no longer backporting changes, so v2 still has issues with those limits and transmission.
> 
> At this time the only work around would be to upgrade to the v3 beta.

Thank you Markus for letting me know. I will try to find docker with version 3 and test. When is a likely stable release to appear of v3, rough estimates?

**Comment by markus101** [comment]
Nope, as usual no ETA.

**Comment by vecnar** [comment]
> Nope, as usual no ETA.

Thank you for letting me know. Will try latest and if any problems revert to old one as deleting is not a major problem :)
