### ISSUE TITLE
All indexers are unavailable due to failures

### ISSUE THREAD

**Issue by J0n19** [Sonarr/Sonarr#3351]
Hi All,

I am repeatedly getting "All indexers are unavailable due to failures" i am using jacket o n the latest version to get my indexers, it had been working perfectly until the hdd filled up, i have since removed files and now constantly get the error even after a reboot.

Any help much appreciated

Thanks
Jon

**System Information**

Sonarr Ver. 2.0.0.5338
 Operating System:  Windows 10
 Jackett Version 0.12.847.0

**Comment by markus101** [comment]
See https://github.com/Sonarr/Sonarr/issues/2802 if you’re still having issues please open a thread on the forums to troubleshoot.
