### ISSUE TITLE
Add episode navigation buttons to episode view

### ISSUE THREAD

**Issue by mmaster23** [Sonarr/Sonarr#3352]
**Describe the problem**
I prefer to pick the release of the episodes I want. When you have the episode open, there is no way to switch to the next episode without closing the episode view and opening the new episode.

**Describe any solutions you think might work**
Add a PREV and NEXT button the top of the episode viewer. When clicked, it should should open the next episode in the view you're in (Summary, History or Search).

**Additional context**
![1](https://user-images.githubusercontent.com/21027839/67334700-dc95aa80-f522-11e9-80c8-7c7646eb20f2.PNG)
Plex screenshot for inspiration.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted
