### ISSUE TITLE
Port 8989 Open - Epic Fail When Starting After DB Restore

### ISSUE THREAD

**Issue by BzowK** [Sonarr/Sonarr#3353]
Hey Guys - 

Long time Sonarr/NZBDrone user.  Already resolved this issue, but wanted to open ticket so it may be addressed in future build if desired.

**The Issue**
This morning, I decided to move my Sonarr installation to another system so followed the below procedure:
1. Created Backup within Sonarr 3 on old system
2. Installed Sonarr 3 on new system & launched
3. Verified versions of old and new were the same
4. Copied over zip and choose to restore it from within Sonarr

The restore succeeded as files were replaced, but Sonarr never came back up.  When trying to launch manually, I got an error that port 8989 was in use by NZBDrone, however verified via netstat -ab that it was not.  I uninstalled Sonarr, then deleted references to it or NZBDrone from registry & file system then reinstalled but issue persisted.  I then tried changing the port in the XML which enabled it to work, but then tried changing back to 8989 within Sonarr and had the same issue upon restart.

_**Note:**  Interestingly enough, uninstalling Sonarr with issue then reinstalling allowed Sonarr to launch on port 8989.  It's only after restoring the files that the issue came about._

**Resolution**
After reading [this older post](https://forums.sonarr.tv/t/sonarr-fails-to-start-after-windows-insider-update/14320), I executed "netsh http delete urlacl http://*:8989/" from an elevated command prompt.  Afterwards, I was able to launch Sonarr without issue using port 8989

**System Information**

 - Sonarr Version: 3.0.3.652
 - Operating System: Windows 10 x64
 - .net Framework (Windows) or mono (macOS/Linux) Version: _Latest_

Thanks

**Comment by markus101** [comment]
Sounds like Sonarr wasn’t running as admin after it was restarted and couldn’t bind to localhost:8989 because it was bound to *:8989 under a different app ID.

With http.sys things are a bit awkward, but nothing actionable until we have a new web server (likely when we go to .net core).
