### ISSUE TITLE
Blacklist option not handled with manual api call

### ISSUE THREAD

**Issue by springjools** [Sonarr/Sonarr#3354]
**Describe the bug**
https://github.com/Sonarr/Sonarr/wiki/Queue
I'm trying to remove a torrent and blacklist it by manually calling the api method as described in above wiki. The server responds with 200 OK but the blacklist option is not triggered. I tried with GET and http://servername/sonarr/api/blacklist and I could thereby verify that the blacklist is not updated.

I tried with following commands:
http://servername/sonarr/api/queue/12345789

Body:
{
  'blacklist': true
}

as well as

http://servername/sonarr/api/queue/12345789&blacklist=true

Both times of course using the DELETE method

**Screenshots**

![image](https://user-images.githubusercontent.com/5911982/67566597-e42a9e80-f730-11e9-95c0-37e6aab1d90e.png)

**Logs**
Link to debug or trace log files.

**System Information**
Version
3.0.3.652
Package Version
3.0.2
Mono Version
6.4.0.198
AppData directory
/home/pi/.config/Sonarr
Startup directory
/usr/lib/sonarr/bin
Mode
Console

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**
The blacklisting obviously works when done using the GUI in sonarr.

**Comment by Taloth** [comment]
That url is wrong. '&' is the parameter separator, you'll looking for '?'. See https://en.wikipedia.org/wiki/Query_string

**Comment by springjools** [comment]
Yup, you're right. I'm sorry I didn't bother to make better tests before I opened an issue. Hope still that this can assist someone else with similar needs.
