### ISSUE TITLE
option to monitor only most recent X episodes?

### ISSUE THREAD

**Issue by acosmichippo** [Sonarr/Sonarr#3355]
**Describe the problem**
On certain shows, I'd like for Sonarr to only Monitor the most recent X episodes.  So for example, only the most recent episode, or the last 5 episodes, or whatever.  An option to automatically delete old unmonitored episodes would be nice too. 

**Describe any solutions you think might work**
Add an option to only Monitor the most recent X episodes, and delete old episodes.

**Additional context**
This would be handy for shows that I don't intend to keep - topical shows like John Oliver I have no interest in keeping long term.  I imagine it would be handy for some viewers of daily late night shows too.

Thanks for reading, and love everything you guys do.

**Comment by markus101** [comment]
Monitor what you want Sonarr to grab and enable ignore deleted episodes to automatically unmonitor episodes deleted from disk. To start you can monitor future episodes and it won’t grab any past ones.

https://github.com/Sonarr/Sonarr/issues/314 covers automatically deleting.
