### ISSUE TITLE
Joal integration

### ISSUE THREAD

**Issue by bubufofo** [Sonarr/Sonarr#3356]
torrents need ratio and or permaseed lets switch to "joal" seeding when ratio and seedtime is met and move the data to gsuite for streaming

https://github.com/anthonyraymond/joal

**Comment by markus101** [comment]
Please use the templates when opening issues.

You’re going to have to elaborate on what you’re looking for here, is this Jowl a torrent client? How would Sonarr integrate with it?

**Comment by bubufofo** [comment]
joal is an ratio/seeding faker... so I propose to move all torrents there after we completed the seeding requirements of the tracker and also move the files into gsuite for archival and streaming purposes

**Comment by markus101** [comment]
Sonarr expects files to remain in the series folder, moving the files would result in Sonarr seeing them missing.

Beyond telling the download client to remove torrents that have met the seeding ratio we don’t have plans to manage them further.

**Comment by bubufofo** [comment]
sonarr can use rclone and torrents right? so how can u successfully torrent from rclone? you cant... so you pretend you seed and move everything to gsuite after some ratiom requirements are met from the tracker ez no ide why is this so hard to comprehend
