### ISSUE TITLE
Completed Download Handler - allow parallel processing

### ISSUE THREAD

**Issue by brimur** [Sonarr/Sonarr#3358]
**Describe the problem**
In a cloud environment uploading to the mounted cloud filesystem is limited to 50Mbps on a 1Gb connection. This was not an issue with traditional storage as the full 1Gb would be used but in modern environments bandwidth throttling can be an issue

**Describe any solutions you think might work**
Add an option to specify how many files the CDHandler will process at once to fully utilize bandwidth

**Additional context**

**Comment by markus101** [comment]
At this time we do not have plans for simultaneous file transfers.
