### ISSUE TITLE
For some TV shows which have only one season, sonarr may just query the show name from indexers

### ISSUE THREAD

**Issue by apporc** [Sonarr/Sonarr#3362]
**Describe the problem**
For some TV shows which have only one season, many sources don't have a season flag 'S01'.
In my case with jackett for TV show "Something in the rain', most of the torrents have a name like "something in the rain", not "something in the rain S01", so when sonarr querys with season=1 from jackett, jackett will find nothing.

**Describe any solutions you think might work**
Because jackett doesn't know the number of seasons of a TV show, i think maybe it's easy for sonarr to handle this situation . Like, if there is only one season, query without season flag. I don't know whether this behaviour cooperate with other indexer types though.

If jackett handle this, it would be "regardless of the number of seasons, always query for show name without season number if handling season 01", this may be too hacky.

**Additional context**
None

**Comment by markus101** [comment]
The bigger problem is they are often named in a way that Sonarr doesn’t understand as it doesn’t understand complete torrents and it’s not something we have plans to support.

**Comment by apporc** [comment]
I understand yes there are many sources which are named in non standard ways, and there are nothing we can do for that. But i think this case i mentioned here is not like that. It seems most(if not all) TV shows from Asia, Chinese or Korean for example, have this problem. They just don't name those TV shows the standard way, because they don't have plan for further seasons from the beginning. This is kind of like anime's situation, isn't it? The TV show producer, the streaming service provider and the torrents maker, they all don't use the standard 'SxxExx' way to name those shows.

Furthermore, except for the missing 'Sxx' in those names, other parts are just the same as standard way, this is not like those other randomly named sources, it should be not hard to support.
