### ISSUE TITLE
<PUT> /series API call doesn't update quality profile ID

### ISSUE THREAD

**Issue by JagandeepBrar** [Sonarr/Sonarr#3365]
**Describe the bug**

When calling the API endpoint `<PUT> /series`, the quality profile ID is not updated. I am first calling `<GET> /series/{id}` as recommended, and updating the value `qualityProfileId` to a new profile ID. I have ensured that the object is being modified on my end before sending it back to the server.

When adding a series (`<POST>`) using the same method, it works correctly, but it does not update the quality profile ID when using a `<PUT>` request. Setting the path, monitor status, season folders, etc. all works as expected.

The returned object does not have the updated quality profile ID either.

**Screenshots**

Here is a terminal screenshot of debug logs from my application:

<img width="654" alt="Screen Shot 2019-10-29 at 1 49 03 PM" src="https://user-images.githubusercontent.com/3048295/67799197-ef443e00-fa52-11e9-89f8-d4e9dfef39ea.png">

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: Ubuntu Server 18.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: 6.4.0.198

**Comment by markus101** [comment]
`qualityProfileId` is provided in the v2 API for backwards compatibility, but `profileId` is the value that should be updated (I've updated the docs to reflect that, which changed years ago).
