### ISSUE TITLE
Language tags for individual selected or combination of languages 

### ISSUE THREAD

**Issue by nismanoku** [Sonarr/Sonarr#3367]
The language tag for audio and subtitles can only show all languages in the rename function. The problem with this is that some files have over 30 subtitle languages and up to 10 audio languages, so you get a name like [NL+EN+PL+DK+DE+Chinese+ and 20 more or so], this creates really long file names which causes problems with the filesystem because the path or filename becomes to long.

Would like to see a language tag to set individual languages or a combination of a few like [EN+NL]. Maybe something like { MediaInfo AudioLanguagesEN+NL} instead of the All one {MediaInfo AudioLanguagesAll}

To showcase a sample, i choose one with not that much subtitles, but you get the idea:
* Friends S01E01 Bluray-1080p Remux AC3 5.1 [EN] x264 [EN+FR+DE+ES+NL+Chinese+PT+DA+FI+NB+SV+JA] -PrivateHD

One other little problem with the complete written language in the tags is that if you have to reimport or rescan the folder sonarr picks them up as chinese in the sample, because that is not a shortcut but full name.

**Comment by markus101** [comment]
At some point cramming too much metadata into a file name is a bad idea, and why the information can be stored elsewhere.

Not really sure what we can do here. I don’t like the idea of one token per language and having a customizable token would be awkward, even a setting for selecting which ones appear seems odd (maybe you want different ones per series type or for specific series).

Chinese should Probably be reduced to a language code, but it’s not exactly one language.

Open to suggestions on how we could handle this, but I’m leaning to closing as something we won’t fix simply due to fact files names are a bad place to have this info.

**Comment by nismanoku** [comment]
If possible for future release (roadmap) to set the episode of a series to be completed if a certain language audio and/or subtitle is present in the set quality it would be awesome. Basically split language tag for audio and subtitles separatly. This would solve my problems for language tags to as sonarr would check this for me and the ones not fulfilled would show up in cutoff unmet.

The problem for me is that some series have dutch audio but there are also releases for the same series with english audio and dutch subs. Both get the dutch language set in sonarr and show them completed, not showing up in cutoff unmet because of missing dutch audio, because the NLSUB tag in the filename downloaded sets the language tag also as Dutch. 

So i use language filename tags to see if there is also dutch audio present in the episode. I know i can see the episode info also in the episode view with the info button behind epsiode path. But to check an entire season or tv-show at once with over 100 episodes aired before added to sonarr it gets time consuming to check all episodes individual this way. So i use language tags in filename and press the manage episodes of the tv-show and can check the entire show at once because of the language tags.

Hope you understand and would place language tags for audio and subtitles seperatly in sonarr on the roadmapp for future release. As that would be the Ultimate sollution to my problem and a lot of others as i read on forums and a real bonus feature for sonarr over others. 

But thought that a language tag for filename was easier to implement than to ad seperated tags in sonarr for language and subtitles so asked for the easiest solution for my problem. 

By the way i want to give the developers and all people involved a big thumbs up for sonarr beta (v3), as minor little hickups i had where solved and the great import function got even better.
