### ISSUE TITLE
Unable to Delete Record from DB

### ISSUE THREAD

**Issue by ghostmech007** [Sonarr/Sonarr#3368]
**Describe the bug**
I am unable to delete a series record from both within the UI and using a DB editor (using SQLiteBrowser).

**Screenshots**
![Screenshot from 2019-10-29 21-06-56](https://user-images.githubusercontent.com/40570775/67820528-02293380-fa90-11e9-83d3-cad6d1a47e1e.png)
This is the error that I am getting.  The file is set to write in permissions and even using root access I am unable to delete the record.

**Logs**
My logs are a giant mess do you permission errors because of LDAP server tanked.

**System Information**

 - Sonarr Version: [e.g. 2.0.0.5322]
 - Operating System: Debian 9.11
 - mono Version: 6.4

**Additional context**
I can't delete Lost for some reason.  I've been trying for days to figure this out and everytime I get the same message from the screenshot above.  I can delete other records but for some reason cannot for record 0.

**Comment by markus101** [comment]
There shouldn't be a record with an ID of `0` (IDs start at 1), looks like the DB is corrupt.

I'd start with repairing the DB, but beyond that rebuilding may be the only way.

If you want to troubleshoot it further please open a thread on the forums for support.
