### ISSUE TITLE
Sonarr isn't creating season 1 folder

### ISSUE THREAD

**Issue by nmbrg** [Sonarr/Sonarr#3369]
When the option to create season folders is left enabled (as default). Sonarr is only creating season folders for season 2 and onward. All season 1 episodes are left directly under the show folder without any season folder.

**System Information**
 - Sonarr Version: 2.0.0.5338
 - Operating System: Windows server 2012 R2

I'll try to add logs if I someday get a new show (season 1) and can get logs from that moment.

**Comment by markus101** [comment]
I'm not able to reproduce this behaviour in v3, on import the `Season 1` folder was created without issue (and the episode placed inside). On the off chance this is only affecting v2 (though I can't think of anything that changed from v2 to v3) it won't be something we'll fix in v2 as it's not a critical security issue.

Log would be useful to see what's going on, but closing until then.
