### ISSUE TITLE
Single episode name detected as entire season if Season missed in file name

### ISSUE THREAD

**Issue by Lonli-Lokli** [Sonarr/Sonarr#3370]
**Describe the bug**
Cannot parse season if title missed in file name

**System Information**

 - Sonarr Version: 3
 - Operating System: Synology NAS

**Additional context**
I have a season release of Friends with format when season is in folder name only and not in file name

./Friends Season 1 (BDRip 720p) 
01. The One Where Monica Gets a Roommate.mkv
02. The One with the Sonogram at the End.mkv
03. The One with the Thumb.mkv
04. The One with George Stephanopoulos.mkv
05. The One with the East German Laundry Detergent.mkv
... and so on

This  release is rejected with note "Single episode file contains all episodes in seasons" while I have the season number in folder name and series number in file name.

**Comment by markus101** [comment]
Close enough to https://github.com/Sonarr/Sonarr/issues/903 that I've updated it and will close this one.
