### ISSUE TITLE
Sonarr grabbed already downloaded episode

### ISSUE THREAD

**Issue by Adrillex** [Sonarr/Sonarr#3371]
Hi,
**Describe the bug**
Sometimes Sonarr download series that are already downloaded.
Recently, sonarr grabbed all seasons of games of thrones even if there were already downloaded. 
![image](https://user-images.githubusercontent.com/19326477/68025803-0d59aa80-fcae-11e9-9992-4faa3fbf57e0.png)
Here is my season 8 folder. All files are 1080P and I made a profile so 1080P is cutoff no matter bluray or webdl.

![image](https://user-images.githubusercontent.com/19326477/68026328-b2c14e00-fcaf-11e9-86f5-854d3df8af3e.png)

I found that torrent grabbed where added to tracker very recently, so its like sonarr discovered this torrents because they were recents, so he grabbed it.

![image](https://user-images.githubusercontent.com/19326477/68027204-0f256d00-fcb2-11e9-8ee3-8353ef9faa74.png)

maybe I missed something but I think it's a bug

**System Information**

 - Sonarr Version: 3.0.3.652
 - Operating System: linuxserver's docker image (on debian host)

**Comment by markus101** [comment]
Your screenshot shows a partial output of season 8, but seasons 1 and 2 were the ones grabbed.

Without debug logs it’s impossible to see exactly why Sonarr grabbed those releases, but with the information provided I don’t think there is a bug (and we’d likely be seeing a lot more reports).

**Comment by Adrillex** [comment]
@markus101 Hi, sorry I screenshoted the wring folder. In fact, I already had all season, but sonarr grabbed all again as new torrent of theses were added to the tracker.

![image](https://user-images.githubusercontent.com/19326477/68044323-5eca5f80-fcd7-11e9-841b-94cada6d04ae.png)

Here is the good season folder. Unfortunately my log wasn't set to debug, so I guess I can't provide more info on this. Now debug mode is set so if it happens again I should be able to give more info.
You say you don't think it's a bug, but I don't understand how it can't be one. My profile parameters are good, and sonarr was aware of the previous files.
Anyway I understand you can't find out what happens without debug logs. I hope this will happen again now that debug is activated so we can figure out.

**Comment by markus101** [comment]
> You say you don't think it's a bug, but I don't understand how it can't be one. My profile parameters are good, and sonarr was aware of the previous files.

The quality is part of it, but things like proper/repack (not at play here) or preferred words would also apply. Way too many variables to consider.

Those are the original files? 
What does the history show for Season 1 in Sonarr? That'll show the history of the import if done previously by Sonarr as well as any deletions for upgrades.

In all likelihood we'll close this issue until we have more information to go on, but can open once we have some.

**Comment by markus101** [comment]
Closing until we have something concrete to go on.

**Comment by Adrillex** [comment]
Hi, Since I enabled the debug mode, that happened again.

Sonarr grabbed Pearson S01E01 even if it meets cutoff.

![image](https://user-images.githubusercontent.com/19326477/68608412-1bc87300-04b3-11ea-9977-30d3187e3859.png)

the logs : 

`19-11-11 14:39:08.6|Debug|DownloadDecisionMaker|Processing release 'Pearson.S01E01.MULTi.1080p.WEB.H264-CiELOS' from 'Ygg limited query'
19-11-11 14:39:08.6|Debug|Parser|Parsing string 'Pearson.S01E01.MULTi.1080p.WEB.H264-CiELOS'
19-11-11 14:39:08.6|Debug|Parser|Episode Parsed. Pearson - S01E01 
19-11-11 14:39:08.6|Debug|Parser|Language parsed: English
19-11-11 14:39:08.6|Debug|QualityParser|Trying to parse quality for Pearson.S01E01.MULTi.1080p.WEB.H264-CiELOS
19-11-11 14:39:08.6|Debug|Parser|Quality parsed: WEBDL-1080p v1
19-11-11 14:39:08.6|Debug|Parser|Release Group parsed: CiELOS
19-11-11 14:39:08.6|Debug|AcceptableSizeSpecification|Beginning size check for: Pearson.S01E01.MULTi.1080p.WEB.H264-CiELOS
19-11-11 14:39:08.6|Debug|AcceptableSizeSpecification|Possible double episode, doubling allowed size.
19-11-11 14:39:08.6|Debug|AcceptableSizeSpecification|Item: Pearson.S01E01.MULTi.1080p.WEB.H264-CiELOS, meets size constraints.
19-11-11 14:39:08.6|Debug|AlreadyImportedSpecification|Performing already imported check on report
19-11-11 14:39:08.6|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
19-11-11 14:39:08.6|Debug|UpgradableSpecification|Comparing preferred word score. Current: 0 New: 150
19-11-11 14:39:08.6|Debug|LanguageSpecification|Checking if report meets language requirements. English
19-11-11 14:39:08.6|Debug|MaximumSizeSpecification|Maximum size is not set.
19-11-11 14:39:08.6|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
19-11-11 14:39:08.6|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. WEBDL-1080p v1
19-11-11 14:39:08.6|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Pearson.S01E01.MULTi.1080p.WEB.H264-CiELOS
19-11-11 14:39:08.6|Debug|ReleaseRestrictionsSpecification|[Pearson.S01E01.MULTi.1080p.WEB.H264-CiELOS] No restrictions apply, allowing
19-11-11 14:39:08.6|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
19-11-11 14:39:08.6|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
19-11-11 14:39:08.6|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
19-11-11 14:39:08.6|Debug|UpgradableSpecification|Comparing preferred word score. Current: 0 New: 150
19-11-11 14:39:08.6|Debug|UpgradableSpecification|New item has a better preferred word score
19-11-11 14:39:08.6|Debug|DelaySpecification|QualityProfile does not require a waiting period before download for Torrent.
19-11-11 14:39:08.6|Debug|HistorySpecification|Performing history status check on report
19-11-11 14:39:08.6|Debug|HistorySpecification|Checking current status of episode [2763] in history
19-11-11 14:39:08.6|Debug|DownloadDecisionMaker|Release accepted`

So it says that the release have a better score (150 vs 0). I guess it's the reason why it grabbed it. I thought that wouldn't happen if the release already meet cut-off.

> Once this quality is reached Sonarr will no longer download episodes.

this sentence confused me.
Is there a way to avoid download of any new file no matter the reason if the actual meet cut-off ?

**Comment by markus101** [comment]
Preferred words operate outside of regular quality upgrades.

At this time there isn't a cutoff for preferred words, the only way to limit the downloads (hopefully to one) would be to use a delay profile to delay grabbing until later so it doesn't grab the first available then upgrade after.
