### ISSUE TITLE
Sonarr does not dynamically update site (Signalr issue?)

### ISSUE THREAD

**Issue by haijeploeg** [Sonarr/Sonarr#3372]
**Describe the bug**
Sonarr does not properly refreshes UI. When in Sonarr and when I click on refresh or search series, sonarr grabs NZB's and adds them properly to the Sabnzbd queue, however the UI is not reporting back to me. Only a consistent animation of a loading circle on the place of the button.

When I open the console F12 in either chrome or firefox, I see;
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ jquery.js:9625
starting application main.js:31
starting signalR SignalRBroadcaster.js:9
```
Then when using sonarr, the UI is not live updating or sending me notifications over the actions it is doing.

After a while (2-4 minutes) I see; 
```
SignalR: [connecting] SignalRBroadcaster.js:32
Loading failed for the <script> with source “https://piwik.sonarr.tv/piwik.js”. queue:1:1
SignalR: [connected]
```
After those 2-4 minutes it works. 

Thereby I always need to manually refresh the page to see the activity updated. It seems all a signalr issue. 

**Logs**
No log messages in either debug or trace log pops up. The strange thing however, Radarr has not this issue.

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: Ubuntu 18.04 LTS
 - mono: 5.14, but also tried the latest 6.4

**UI Bugs:**
 - OS: Ubuntu 19.04, Windows 10
 - Browser: Chrome Version 78.0.3904.70 (Official Build) (64-bit) and FireFox 70.0

**Additional context**
I run Sonarr and Radarr on the same host with an Nginx reverse proxy. Accessing Sonarr through the reverse proxy as by connecting directly using port 8989, gives me the same behavior. I also tried setting the environment variable `XDG_CONFIG_HOME` to a directory the sonarr user has full access, but that hadn't any results. I also tried running sonarr in docker using the images of linuxserver. I tried both the latest stable and de 5.14 version (mono), those had both the same problems I encounter with a APT installation.

I also tried the preview version of the docker image from linuxserver, just to see how signalr would react there. Using this version signalr connects immediately.

Radarr however is updating the UI correctly and has no issues.

**Comment by markus101** [comment]
> Using this version signalr connects immediately.

Good to know and ultimately means that this issue something we’re going to spend time investigating as we’re not fixing issues in v2 outside of security issues.

Not sure what could’ve causing that delay, but the environment variable not being set would result in total failure.

It’d be worth trying another browser or incognito window to see if the issue persists.
