### ISSUE TITLE
Filter by missing episodes ONLY for monitored

### ISSUE THREAD

**Issue by nununo** [Sonarr/Sonarr#3374]
**Describe the problem**
I want to see just the missing episodes of the series I'm currently watching. I added several series which I stopped watching temporarily so they are unmonitored to put them on hold. Yet, whenever I choose the "missing" filter (the closest to what I want), all these unmonitored are still listed.

**Describe any solutions you think might work**
I'd like to have a new filter option for listing only missing episodes belonging series currently being monitored.

Thanks in advance,
Nuno

**Comment by markus101** [comment]
In v3 you can make a custom filter for this on the series page or use Wanted: Missing in v2 or v3.
