### ISSUE TITLE
Sonarr ignored a couple of eposides in season pack

### ISSUE THREAD

**Issue by ejalal** [Sonarr/Sonarr#3375]
**Describe the bug**
Just finished downloading The Expanse S03 full pack (manually added from Jackett), but Sonarr imported only the first 11 episodes, and ignored episode 12 and 13.

Content of the season pack
The.Expanse.S03E01.Fight.or.Flight.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv
The.Expanse.S03E02.IFF.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv
The.Expanse.S03E03.Assured.Destruction.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv
The.Expanse.S03E04.Reload.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv
The.Expanse.S03E05.Triple.Point.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv
The.Expanse.S03E06.Immolation.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv
The.Expanse.S03E07.Delta-V.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv
The.Expanse.S03E08.It.Reaches.Out.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv
The.Expanse.S03E09.Intransigence.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv
The.Expanse.S03E10.Dandelion.Sky.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv
The.Expanse.S03E11.Fallen.World.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv
The.Expanse.S03E12.Congregation.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv
The.Expanse.S03E13.Abaddon's.Gate.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv

**Screenshots**

**Logs**
No error in log file (trace wasn't enabled)

**System Information**

Version 2.0.0.5338
Mono Version 5.20.1.34
AppData directory /config
Startup directory /opt/NzbDrone

**UI Bugs:**
 - OS: Linux/Docker
 - Browser: Chrome
 - Version: 78

**Additional context**

**Comment by markus101** [comment]
Best guess files were transferring from seed box or being unrarred while Sonarr was trying to process them, thus it didn’t know the files existed and was done when it imported all available files.

This is a known limitation (and there is some work in progress to improve that behaviour), but without at least debug logs there isn’t anything more we can investigate.

**Comment by ejalal** [comment]
Hi @markus101 
Well the Transmission and Sonarr dockers run on the same machine, so Sonarr can't process the completed "download" before it's 100% completed.
Is there any workaround to process the whole season pack once again so the files are copied/hard linked correctly this time ?
Thanks for you help

**Comment by markus101** [comment]
It can if the files needed to be unpacked.

>Is there any workaround to process the whole season pack once again so the files are copied/hard linked correctly this time ?

You can use Manual Import from Wanted: Missing.

**Comment by ejalal** [comment]
Thanks for your support, just checked my old eposides and actually the new download was an upgrade @1080p to existing season pack @720p.

In my old files, episode 12 and 13 are in the same mkv file like so
`The Expanse - S03E12-E13 - Congregation & Abaddon's Gate.mkv`

That's probably the reason why eposides 12-13 have been ignored as the new ones are in separate files.
