### ISSUE TITLE
MacOS app bundle can't be opened - 'Sonarr' script not executable.

### ISSUE THREAD

**Issue by formerandroider** [Sonarr/Sonarr#3376]
**Describe the bug**
The 'Sonarr' script inside the Sonarr.app bundle isn't executable, and the app cannot be opened.

**Screenshots**
<img width="532" alt="Screenshot 2019-11-04 at 16 35 03" src="https://user-images.githubusercontent.com/1273489/68138890-2322d600-ff21-11e9-8e0b-330f0cd85258.png">

**System Information**
 - Sonarr Version: 3.0
 - Operating System: macOS 10.14 & macOS 10.15
 - .net Framework (Windows) or mono (macOS/Linux) Version: 6.4.0.198

**Additional context**
Running `chmod +x .../Sonarr.app/Contents/MacOS/Sonarr` allows the app to run.

**Comment by markus101** [comment]
This is due to how the zip is unpacked. The built in zip utility works fine, but other tools strip off the executable flag.

Previous issue (with links to the same issue in Radarr): https://github.com/Sonarr/Sonarr/issues/2818

**Comment by formerandroider** [comment]
@markus101 I've only ever used the macOS Unzip utility.

**Comment by markus101** [comment]
Where was it extracted to? This could be related to the disk access changes in 10.15 perhaps because it's unsigned. Not being executable seems to be pretty random though.

**Comment by formerandroider** [comment]
@markus101 The Downloads folder, but I should note that I had the same issue on 10.14 as well. I've never been able to open Sonarr after downloading it from the official site without adding the executable bit.
