### ISSUE TITLE
Choose where your temp downloaded files download to

### ISSUE THREAD

**Issue by TwistedFaith84** [Sonarr/Sonarr#3380]
**Describe the problem**
When downloading new episodes through Sonarr they all temporary download to currently (in my case) C:\Users\[Username]\Downloads before it is moved to location you have set for it to go (which is fine and all) except my C;\ drive is currently sitting at less then 2GB so nothing will download or at least be able to complete the download because of it.

**Describe any solutions you think might work**
Being able to set a temp download folder (per series or type (ie anime, daily, ect...)) to use for downloading before being moved to their permanent location would be very helpful.

**Additional context**
So for example lets say I store my anime on my A:\ drive; I would set up all my anime thats downloaded through Sonarr to be temporary downloaded to A:\Downloads and when the download is finished and automatically moved to its permanent location at A:\Anime\. The same would be for my TV shows where instead I would set those to be on my T:\ drive and the temp folder would be T:\Downloads and the permanent locations would be T:\TV Shows\Dailies\ and T:\TV Shows\Non-Dailies\ (or something like that) anyways allowing this would also help in speed (even if slightly) if to have you permanent locations for said items on another drive other then your standard C:\ as moving files to someplace on the same drive is almost instinct and moving from one drive to another does take time.

**Comment by markus101** [comment]
Your download client determines where they are downloaded to, in some clients Sonarr can specify (Transmission for example), but we're not going to do that per type.

**Comment by TwistedFaith84** [comment]
ok understandable. I'm using uTorrent a it has never ask where I want my files to go and I even have it set up to download to a specific folder already and yet it still uses my C:\ drive
