### ISSUE TITLE
Ability to Force Rename File and/or Folder

### ISSUE THREAD

**Issue by TwistedFaith84** [Sonarr/Sonarr#3381]
I'd like the ability to force rename a tv show and/or episode to the way I would like it
ie... 
1) lets say I would like the removal of all (or most/certain) special characters from the file and/or folder (except for " - " [space dash space] that goes between the show title and the episode title.
2) ability to set the case for the file like so (ALL UPPERCASE, all lowercase, First Letter Of Each Word, ect....)

**Comment by markus101** [comment]
Why the dupe?

https://github.com/Sonarr/Sonarr/issues/3382

**Comment by TwistedFaith84** [comment]
Dont know why the dupe. didn't notice it was duped.
