### ISSUE TITLE
Ability to Force Rename File and/or Folder

### ISSUE THREAD

**Issue by TwistedFaith84** [Sonarr/Sonarr#3382]
I’d like the ability to force rename a tv show and/or episode to the way I would like it
ie…

1) Lets say I would like the removal of all (or most/certain) special characters from the file and/or folder (except for " - " [space dash space] thats goes between the show title and the episode title and if the Show title needs a year with it to be the right one (ie… The difference between [The Flash and The Flash (2014)].

2) Ability to set the case for the file like so (ALL UPPERCASE, all lowercase, First Letter Of Each Word, ect…)

**Comment by markus101** [comment]
1. `{Series ClearTitle}`
2. `{Series Title}` (Matches title from TheTVDB), `{SERIES TITLE}` (All Caps) or `{series title}` (All Lower Case)
