### ISSUE TITLE
IPTorrents - 'Base Url' is not in the correct format.

### ISSUE THREAD

**Issue by Cylae** [Sonarr/Sonarr#3384]
Hello,

I can't add IPTorrents to my Sonarr, I have this error : 
`'Base Url' is not in the correct format.`

Sonarr Ver. 2.0.0.5338
Debian

I used this URL : https://iptorrents.com/t.rss?u=XXX;tp=XXX;90

I saw you already had a similar issue and fixed it, but it looks like this issue is back ;)

Thank you for your help :)

**Comment by markus101** [comment]
This is fixed in v3 and not something we'll be fixing in v2. v3 is currently in beta, more info is on sonarr.tv

**Comment by Cylae** [comment]
Wow ! Just discovered the v3, it's look awesome ! Thank you for your work !
