### ISSUE TITLE
Add “Change Quality” option for Manual Import

### ISSUE THREAD

**Issue by X8PX** [Sonarr/Sonarr#3388]
Using Sonarr v3.

In the manual import page, you can change the series and season. I think you should be able to change the quality here too. Useful for when 1080p releases are being marked as HDTV when they should be WEB-DL (usually anime).

![9E95F592-A773-4E6E-B71F-8C760DBD1350](https://user-images.githubusercontent.com/8931530/68548474-6bc40e80-03bb-11ea-8489-03a9563549ed.jpeg)

**Comment by Taloth** [comment]
You're on an ancient sonarr v3 version.

**Comment by X8PX** [comment]
> You're on an ancient sonarr v3 version.

Oh really? Damn. Does v3 not support updating through the Updates tab?

**Comment by Taloth** [comment]
It does support updating, except in some docker images. Latest is 3.0.3.654

There was a broken version well over a year ago. Always keep an eye on your beta software 😅

**Comment by X8PX** [comment]
Updated. Thanks!
