### ISSUE TITLE
Quality Definitions - "Reset to Default" Button

### ISSUE THREAD

**Issue by napei** [Sonarr/Sonarr#3390]
**Describe the problem**
A clear and concise description of the problem you're looking to solve.

In Sonarr v3 (phantom-deveop), I was playing around with the quality definitions sliders to allow for some hevc releases that sometimes are rejected because they're under the threshold despite being perfectly fine. After messing around for a bit I ended up making everything 0 to unlimited, however I wouldn't mind resetting these. Currently there's no way to do this easily.

**Describe any solutions you think might work**
A clear and concise description of any solutions or features you've considered.

Perhaps up the top, where the "Save Changes" button is there could be a "reset" button, that will just load the installation defaults for this.

Or, to save confusion with other pages in settings, this reset button could be an Advanced option, and appear next to the "Quality Definitions" title instead.

**Additional context**

Examples of potential changes:
![image](https://user-images.githubusercontent.com/8946502/68648152-c86a2980-0573-11ea-9e0d-53a3feae6b46.png)

![image](https://user-images.githubusercontent.com/8946502/68648440-82619580-0574-11ea-824e-2734ac7a73a9.png)

**Comment by markus101** [comment]
What about the titles, would you expect those to reset to default as well?

**Comment by napei** [comment]
@markus101 didn't think of the titles. 
Maybe two buttons, one above each column, one for the values and one for titles?
Or maybe just reset the whole page all at once?
