### ISSUE TITLE
Sonarr v3 won’t download release...

### ISSUE THREAD

**Issue by agneevX** [Sonarr/Sonarr#3391]
Sonarr v3 won’t grab the release because apparently the episode is 0min.

**Screenshots**

![IMG_0037](https://user-images.githubusercontent.com/19761269/68697834-a7bac780-05a5-11ea-92c8-9fea990f780f.jpeg)

![IMG_0038](https://user-images.githubusercontent.com/19761269/68697868-b5704d00-05a5-11ea-9a49-85749aa1c87d.jpeg)

**System Information**
Version 3.0.3.654
Package Version 3.0.2
Mono Version 6.4.0.198

**Comment by markus101** [comment]
Not a bug, TheTVDB data was missing a runtime.

https://forums.sonarr.tv/t/fails-to-get-eps-ofm-the-mandolorian/23769/5

**Comment by agneevX** [comment]
Is there a way to use another source? I see posters missing for several TV Shows.
