### ISSUE TITLE
Limit amount of torrents added to client

### ISSUE THREAD

**Issue by dmzoneill** [Sonarr/Sonarr#3392]
There needs to be some method of preventing sonarr for adding more than X amount of torrents to the download client.  

Deluge falls over at around 300 torrents. so trying to add thousands does not make sense.  

With an 22TB series collection, 997 series and some few thousands missing episodes, it is time consuming to enabling series in piecemeal fashion (micro managing)

I see there is already abstract method overridden in the clients that implement the ability to count the active torrents.  

public override IEnumerable<DownloadClientItem> GetItems()

Sonarr client should have some options for MaxTorrents and don't add more until torrents in the client have dropped below the desired amount.

**Comment by markus101** [comment]
Depending on the client the items Sonarr gets are limited to Sonarr's specific category/label in the client, but there are clients that are capable of handling a large number of torrents.

We don't have plans to support a limit on the number of items in a client.

**Comment by dmzoneill** [comment]
Hey,

Thanks for the swift feedback, however disappointing it is.

I disagree with your reasoning.

All clients have a limits, rtorrent falls over about about 1000 torrents and other torrent clients have similar scaling issues.

Sonarr is a solution to manage library of series, yet a fundamental features like not blowing the limits of the torrent client is left unchecked.

seems like flawed reasoning.  I will fork it, thanks!
