### ISSUE TITLE
torrents limited to 15 minutes share ratio

### ISSUE THREAD

**Issue by iammortimer** [Sonarr/Sonarr#3393]
**Describe the bug**
After installing 3.0.3.654 torrents are set with a 15 minute share ratio limitation. Setting them manually again to the global settings resets them and they continue seeding.
Previous version didn't have that problem.

**Logs**
19-11-13 06:42:26.1|Debug|QBittorrent|Downloading torrent for episode 'Castle Rock S02E06 720p HEVC x265-MeGusta' finished (4957 bytes from http://mynas:9117/dl/iptorrents/?jackett_apikey=(removed)&path=Q2ZESjhMM3hwTWZqSHFSSGw2Y0pibkY1OFAyUnFjSm9PN2F0RHp5dDZxSDhpOVM5N25EQTNIZ3E4UFh5Q0RuSGplQVlLbHVZVUNQTks2SmZ3NlM2bEo5UU1TbWNhNE1VREprV3JTTks5YTU5WEw3VHVLSnhVbzhoeUJBRGVWN0ZKaHlBUDRZZ3plRDFMcVZrTFczV1pVSjhmX24xZ25MaGN0ZlNwdTJMd2V4SmRaQUJZMy0yM0MtTWlIN1RmV0lkLU5OSTg3TkwtanA4bnFyaFZDVmV3QzVFUEVMS0dHelp1alpqM2RhcUowR25wQ1lvSmJ4QmhkeHNnRkRiMmlqSC1seFh2dw&file=Castle+Rock+S02E06+720p+HEVC+x265-MeGusta)
19-11-13 06:42:26.1|Info|DownloadService|Report sent to qBitTorrent. Castle Rock S02E06 720p HEVC x265-MeGusta
19-11-13 06:42:26.1|Debug|PendingReleaseService|Adding release Castle.Rock.S02E06.720p.HEVC.x265-MeGusta-Obfuscated to pending releases with reason Delay

**System Information**
 - Sonarr Version: 3.0.3.654
 - Operating System: Windows 10 1903
 - .net Framework (Windows): 4.8
 - qBittorent v4.1.5

**Comment by markus101** [comment]
3.0.3.654 made no changes to seeding limits. The only change is in the change log.

It's not clear what exactly the issue is (and your logs show a pending release, not something that was grabbed), but please open a thread on the forums to troubleshoot.

**Comment by iammortimer** [comment]
Previous version was 3.0.0.348.

I thought the description was pretty clear, i posted this part of the log because the problem arises from the way sonarr sends the get-command to qBittorrent and accompanying settings. Somewhere in those settings it now sends the attribute to limit the seeding time to 15 minutes.

**Comment by iammortimer** [comment]
Apologies, found the issue, wasn't aware of the seedtime setting on the indexers, that was apperently introduced in one of the inbetween releases.
