### ISSUE TITLE
Season Folder Format not consistent

### ISSUE THREAD

**Issue by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [Sonarr/Sonarr#3399]
Version
    3.0.3.654
Package Version
    3.0.3.654-ls149 by linuxserver.io
Mono Version
    5.20.1.34

## Summary
Series folder tokens ("${Series TitleYear}","${CleanTitleYear}" and "${TitleTheYear}") is not applied for all series. 
    
## Steps to reproduce
Go to settings, media management and enable "rename episodes". Set the "Series Folder Format" to any variable containing "Year". Apply renaming. 

## Expected
All series to apply the chosen token for "Series Folder Format"

## Actual
"${Series TitleYear}","${CleanTitleYear}" and "${TitleTheYear}" is only applied on subset of series / series that have naming collisions. 
          
## Notes
Suggestions for fix:
Introduce a variable to set if the folder format token should be applied on all series, or only those with duplicate naming 

Temporary fix
Change description to specify that its only applied to a subset / duplicate naming.

**Comment by markus101** [comment]
Series Folder format only applies when a series is added or "moved" (telling Sonarr to move series folders).

Additionally, the year is only added if it's not part of the series title.

**Comment by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [comment]
I should have provided the rename step, sorry about that. 

However, there is no such thing as "year is part of series title". Its a constraint provided by the provider of the metadata, in this case tvdb. Its not consistent with neither different providers nor software that handles them e.g. plex, kodi etc.

**Comment by fryfrog** [comment]
I think what @markus101 means is that the *default* `{Series Title}` is based on TVDB, where the first of the name generally does *not* have a year, but later ones do. So using this one, you'll end up w/ a mix of shows w/ names only and name w/ year. When you use one of the `{Year}` ones, it *only* adds the year to the ones that *don't* have the year. So you *will* end up w/ all of them having `Series Title (Year)`, but it can't blindly do that or you'd end up w/ `Series Title (Year) (Year)` if it didn't exclude the shows that already have the year in their title.

And *normally*, this template is *only* used when you initially add a show, so just changing it won't fix existing shows. And the mass rename *also* won't fix it. The only way to "fix" it is to use a kind of silly trick where you select all of your shows in one existing root folder, use the drop down to change them to the *same* root folder and then save. This will "move" and rename them to the right name at the same time.

And this is silly, no one ever figures it out. I'd love to see *that* made easier.

**Comment by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [comment]
Thanks for the explanation @fryfrog. I might have interpreted the label to literally. That is, "year" will always be part of the naming. Anyway, I see the complication(s) for very little gain. cheers
