### ISSUE TITLE
Deleted episodes when ran out of disk space on a season pack

### ISSUE THREAD

**Issue by lsvortex** [Sonarr/Sonarr#3400]
Sonarr automatically downloaded a season pack using bittorrent. After completion of the download and half way through copying the episodes to the correct directory the target drive ran out of disk space. I noticed approximately 4 hours later but after making space on the drive I hoped that it would complete the move but the files were already deleted. I then forced another download of the season pack only to have the system once again delete the two episodes I was missing.

**System Information**

 - Sonarr Version: 3.0.3.654
 - Operating System: [e.g. Windows 10]

**Comment by markus101** [comment]
Covered by https://github.com/Sonarr/Sonarr/issues/668
