### ISSUE TITLE
Sonarr adds html to downloaded image files

### ISSUE THREAD

**Issue by mirolm** [Sonarr/Sonarr#3401]
**Describe the bug**

Today i decided to add new anime season to download with sonarr. It started to dowload okay, but i noticed that all images are not showing in sonarr - poster, backdrop and so on simply does not show. I went to the download folder and opened the downloaded images with nano/vi editor. Strangely all images was containing html as the below:

````
19-11-15 12:08:08.7|Debug|HttpClient|Downloading [https://www.thetvdb.com/banners/fanart/original/5c3fa3a6b6a19.jpg] to [/home/nzbdrone/.config/Sonarr/MediaCover/75/fanart.jpg]

nano /home/nzbdrone/.config/Sonarr/MediaCover/75/fanart.jpg

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.17.5</center>
</body>
</html>
----- image file starts after ----
````

Seems that original URL is redirected with 301 to: 

````
root@altair:/media/lv2/download# wget https://www.thetvdb.com/banners/fanart/original/5c3fa3a6b6a19.jpg
--2019-11-15 12:36:09--  https://www.thetvdb.com/banners/fanart/original/5c3fa3a6b6a19.jpg
Resolving www.thetvdb.com (www.thetvdb.com)... 143.204.214.76, 143.204.214.42, 143.204.214.8, ...
Connecting to www.thetvdb.com (www.thetvdb.com)|143.204.214.76|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://artworks.thetvdb.com/banners/fanart/original/5c3fa3a6b6a19.jpg [following]
--2019-11-15 12:36:09--  https://artworks.thetvdb.com/banners/fanart/original/5c3fa3a6b6a19.jpg
Resolving artworks.thetvdb.com (artworks.thetvdb.com)... 52.222.158.165, 52.222.158.66, 52.222.158.123, ...
Connecting to artworks.thetvdb.com (artworks.thetvdb.com)|52.222.158.165|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 405508 (396K) [image/jpeg]
Saving to: ‘5c3fa3a6b6a19.jpg’
````

````
location: https://artworks.thetvdb.com/banners/fanart/original/5c3fa3a6b6a19.jpg
server: nginx/1.17.5
status: 301
````

Sonarr gets the redirect html that nginx returns and adds it atop of the image which results messed up images for the series, season and episodes.

**Screenshots**

![image](https://user-images.githubusercontent.com/9135358/68954550-eaaab400-07cc-11ea-9ea8-94c6eaffed3d.png)

**Logs**

https://drive.google.com/open?id=1jhKWFYetOCii465RTRbUyyJHdTurG4_v

**System Information**

 - Sonarr Version: 3.0.3.654
 - Operating System: Debian GNU/Linux 10 (buster)
 - .net Framework (Windows) or mono (macOS/Linux) Version: 6.4.0.198

**Additional context**

I opened a thread in the forums too: https://forums.sonarr.tv/t/sonarr-adds-html-to-downloaded-image-files-tvdb-related/23804

**Comment by Taloth** [comment]
Crap, I talked about this with the Lidarr devs. But never applied the fix...
