### ISSUE TITLE
Cannot Search IPT

### ISSUE THREAD

**Issue by MrTyton** [Sonarr/Sonarr#3405]
Even though in Jackett the IPT indexer works, any attempt to search for episodes through Sonarr v3 fail to find any episodes for anything in IPT. It passes the test in the Indexers tab, but nothing ever comes up in searches.

**Screenshots**

https://imgur.com/a/2KWggAS

**System Information**

 - Sonarr Version: 3.0.3.655
 - Operating System: Windows 10

**Additional context**
I already have Disney+, this is just for convenience.

**Comment by MrTyton** [comment]
This also applies to His Dark Materials, same situation.

**Comment by markus101** [comment]
Please open a thread on the forums to troubleshoot this issue, we'll need to see debug logs of the search at a minimum.
