### ISSUE TITLE
Webhooks stopped working

### ISSUE THREAD

**Issue by jamesking420** [Sonarr/Sonarr#3411]
## Bug Report
I am posting a webhook to my Home Assistant instance when Sonarr does certain things.  This appears to be due to a problem with a new SSL certificate.  Similar webhook notifications with Radarr have continued to work OK.
### System Information/Logs
19-11-19 16:15:00.4|Error|X509CertificateValidationService|Certificate validation for https://myurl/api/webhook/randomstring failed. RemoteCertificateChainErrors
19-11-19 16:15:00.4|Fatal|SonarrErrorPipeline|Request Failed. POST /api/v3/notification/test

[v3.0.3.655] System.Net.WebException: Error: TrustFailure (Authentication failed, see inner exception.): 'https://myurl/api/webhook/randomstring' ---> System.Net.WebException: Error: TrustFailure (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
**Sonarr Version:**
Version
3.0.3.655
**Operating System:**
QNAP QTS 4.3
**.net Framework (Windows) or mono (macOS/Linux) Version:**
Mono Version
5.20.1.34
**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**
N/A
### Additional Information
I've removed my URL from the above log.  The certificate is new, but valid.  Other test sites such as API tester work with it fine.  Other apps (e.g. radarr) work OK.  When I go there on my browser my browser believes the certificate to be valid (I'm sure it is).  Google home things its valid and works with my home assistant instance OK.  Everything works OK with my new certificate apart from sonarr...

**Comment by markus101** [comment]
Certificate validation is handled by mono (Boring TLS).

https://tirania.org/blog//archive/2016/Sep.html
https://stackoverflow.com/a/49799509/882971 - This is likely what you'll need to do.

Outside of that I'm not sure what you can try, but if you're still having issues please open a thread on the forums or subreddit for support.

**Comment by jamesking420** [comment]
Thanks - turns out it was my fault as I had not created my fullchain.pem currently from the chain file and the cert file. Correcting this file sorted out the problem.
