### ISSUE TITLE
missing all the sonarr-injected environment variables 

### ISSUE THREAD

**Issue by JySzE** [Sonarr/Sonarr#3413]
**Describe the bug**
 missing all the sonarr-injected environment variables 

**Screenshots**
https://pastebin.com/vtjWyDX5

![Screenshot_3](https://user-images.githubusercontent.com/25883052/69215179-cd078280-0b1d-11ea-88f7-b2b86d5b31e0.png)

Error in coordination with this:
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1086

**Logs**
https://pastebin.com/vtjWyDX5

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: Linux Mint
 - Mono: 6.4.0.198

**Comment by markus101** [comment]
Based on the logs, Sonarr had no issues setting the environment variables.

Opening a thread on the forums or subreddit would be the next step to troubleshoot this further.
