### ISSUE TITLE
Sonarr V3 - Binding to localhost/127.0.0.1 causes Sonarr to fail to boot

### ISSUE THREAD

**Issue by chemputer** [Sonarr/Sonarr#3414]
**Describe the bug**
Changing the bind address from * to 127.0.0.1 or localhost causes it to fail to boot.

**Logs** 
[Relevant log file](https://github.com/Sonarr/Sonarr/files/3870867/SonarrV3localhostFail.log)

**System Information**
 - Sonarr Version: 3.0.3.657
 - Operating System: Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: 4.8.03921 
I think, that's the max installed version, but I really have no idea which one it uses. In case it's useful, I also have the following versions installed (generated via [this powershell code](https://stackoverflow.com/a/3495491) that I found):

```
.NET Framework                   Product Version        Release
--------------                   ------- -------        -------
v2.0.50727                               2.0.50727.4927        
v3.0                                     3.0.30729.4926        
Windows Communication Foundation         3.0.4506.4926         
Windows Presentation Foundation          3.0.6920.4902         
v3.5                                     3.5.30729.4926        
Client                                   4.8.03921      528209 
Full                                     4.8.03921      528209 
Client                                   4.0.0.0               
```

**Additional context**
This is the V3 beta. The logs claim that port 8989 was in use already, but it was not. Without changing anything else, once I restored the bind address to * in the config file, it booted straight up. I checked with netstat, and nothing was on port 8989. I am very confused. I would ideally like to set it to localhost, but for now, I can live with it binding to all ports.

**Comment by markus101** [comment]
Same as https://github.com/Sonarr/Sonarr/issues/622

Won't be addressed until we switch web servers.

**Comment by chemputer** [comment]
Thanks for the quick response.

I could be wrong, but I looked over that issue thoroughly before submitting this one, and I'm fairly confident the two are very different. That issue has to do with having a bad request issue with the webserver when using a DNS hostname (including localhost, but *not* 127.0.0.1), while this issue is about the entire program not starting when you enter 127.0.0.1 as the IP/address to bind to. 

It could be due to the same fundamental underlying issue, I don't know, but there's a significant difference (to me anyway) to a Bad Request in the browser but the program still running, and the entire program failing to even start.

I'd really appreciate it if you could take a closer look at the issue, especially my log, which is truncated to just the relevant parts. This is my first issue report so forgive me if I did something wrong. 

I don't know how you classify things as being the same issue, so I'll obviously have to defer to your good judgment, but I'm very confused as to how they are the same when they are so different. I could see how they appear the same at a cursory look, but beyond that... is it that you already know the cause and it's a fundamental issue with the current webserver and that won't be fixed until you switch? I could see that, but how you could know that already unless you've experienced the issue yourself, I don't know.

I hope this doesn't come across as hostile or anything, I'm just really confused.

**Comment by markus101** [comment]
You're right it's not the exact same, but has to do with us always binding to localhost directly and the overall awkward bindings because you're not really binding to an IP address you're binding to a specific URL. It's something we need to overhaul, but it requires a new web server, which is the underlying cause for both issues.

If you only want Sonarr to bind to localhost you can clear the bindings that it's reserved and make sure it never runs as admin, but it'll limit requests to `http://localhost:8989` and will not be accessible from any other URL.
