### ISSUE TITLE
Random Series Posters in Cyrillic since 3.0.3.655

### ISSUE THREAD

**Issue by emeljay42** [Sonarr/Sonarr#3416]
Since updating to 3.0.3.655, various series posters display with cyrillic
 or other non english titles.

**Screenshots**

![Sonarr issue](https://user-images.githubusercontent.com/10142109/69292780-0eea1300-0c5b-11ea-86b6-1e5030334e23.jpg)

**Logs**
Link to debug or trace log files.
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/3872363/sonarr.debug.txt)
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/3872364/sonarr.txt)

**System Information**

 - Sonarr Version: [3.0.3.657
 - Operating System: QNAP 4.4.1.1117

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by jpartain89** [comment]
Same issue here! Its absolutely the weirdest thing.... 

**System Information**

- Sonarr Version: 3.0.3.657
- Operating System: Debian 10 on Raspberry Pi

**Comment by markus101** [comment]
Same as all the other issues with content, TVDB's API is returning the wrong things.

See https://github.com/Sonarr/Sonarr/issues/3415
