### ISSUE TITLE
Ability to PAUSE downloads

### ISSUE THREAD

**Issue by TwistedFaith84** [Sonarr/Sonarr#3417]
It would be nice to have the ability to PAUSE downloads either through the download client themselves or through SONARR itself. that way if your running low on disk space you dont have to worry about sonarr NOT auto-renaming and moving when you download completes after you start up your downloads again

**Comment by markus101** [comment]
Pausing a download in your client (either based on disk space automatically) or manually will still allow Sonarr to monitor it and wait for it to complete. If it's already complete then Sonarr will be trying to import at that point. We don't plan to have a pause function in Sonarr to pause individual downloads, if you want to pause all downloads in Sonarr disable the download clients and re-enable when you're ready.
