### ISSUE TITLE
Sonarr doesn't see all jackett search entries

### ISSUE THREAD

**Issue by mosath-s** [Sonarr/Sonarr#3421]
**Describe the bug**
In jackett I see much more torrents
for example I don't see this torrent in sonarr (take a look at screenshots):
`RuTracker | Dr.​ Stone [TV] [1-​21 24] [ ] [JAP, SUB] [2019, WEBRip] [1080p]`

I think something wrong with torrent name, but how I can ignore that?

**Screenshots**
jackett:
![image](https://user-images.githubusercontent.com/58134720/69493179-b74ae200-0ebc-11ea-94b7-5d193b581e27.png)
sonarr:
![image](https://user-images.githubusercontent.com/58134720/69493182-c92c8500-0ebc-11ea-98ba-e352a1718ca3.png)

**System Information**

 - Sonarr Version: [2.0.0.5338]
 - Operating System: [Windows 10]

**Comment by markus101** [comment]
Please use the forums or subreddit for support.

Sonarr only shows the results returned by Jackett, you’ll need to determine why Jackett didn’t return that result.

Wrong category maybe?
