### ISSUE TITLE
sonarr is unable to paste special character to jackett

### ISSUE THREAD

**Issue by kevnicolwynbay** [Sonarr/Sonarr#3423]
Hello,

I added the tvshow "L'effondrement" to sonarr

- TVDB Name - The Collapse
- Scene Name - L'effondrement

Sonarr does somes requests to jackett to find releases, he reachs the TVDB Name and  Scene Name, but the Scene Name has a special character. When you compare the Scene Name and the trace log, the special character is not include.

**Logs**
`19-11-24 10:23:52.4|Debug|Torznab|Downloading Feed http://192.168.2.3:9117/api/v2.0/indexers/yggcookie/results/torznab/api?t=tvsearch&cat=102184&extended=1&apikey=(removed)&offset=0&limit=100&q=LEffondrement&season=1&ep=1`

**System Information**

 - Sonarr Version: 3.0.3.657
 - Docker

**Screenshots**

The TVDB Name and  Scene Name
![sonarrscene](https://user-images.githubusercontent.com/58141187/69496501-23384500-0ed3-11ea-9c1a-a4ddca7898af.png)

Request without special character = no result
![sonarrjackettnodata](https://user-images.githubusercontent.com/58141187/69496500-23384500-0ed3-11ea-831c-6da2bb220fea.png)

Request with special character = results
![sonarrjackettdata](https://user-images.githubusercontent.com/58141187/69496499-23384500-0ed3-11ea-9f18-4880e359f5c5.png)

**Comment by markus101** [comment]
Special characters are stripped. There is an existing issue for this already.
