### ISSUE TITLE
XEM references disappeared on American Pickers

### ISSUE THREAD

**Issue by antigravity83** [Sonarr/Sonarr#3426]
American Pickers is notoriously bad on tvdb - however it has a comprehensive thexem listing. 

Historically Sonarr has listed scene references for this show, however I've just re-added it on a new installation of Sonarr V3 and the scene listings are no longer there?

Specific example, S01E13 of American Pickers should be really be referred to as S2010E13 in Sonarr (as per TVDB) with a scene listing of S02E01 (as per thexem)

However it simply appears as S01E13 in Sonarr V3? 

![image](https://user-images.githubusercontent.com/27241813/69623775-33951f00-108f-11ea-91b3-2a2fb7a6d622.png)

 - Sonarr Version: 3.0.3.658
 - Operating System: Ubuntu 18.04
 -  Mono 5.20.1.34

**Comment by markus101** [comment]
The TVDB made changes to the numbering so the xem mappings are accurate.

**Comment by antigravity83** [comment]
But Sonarr doesn't show the scene listings?

When hovering over the episode number of S01E13, shouldn't it show S02E01?

When searching for S01E13, Sonarr tries to find S01E13, not S02E01

**Comment by markus101** [comment]
http://thexem.de/xem/show/4806

Sonarr doesn't have a season 2010 anymore, so the mappings do not apply. The mappings will need to be fixed.

**Comment by antigravity83** [comment]
Ah ok thanks. Too bad thexem.de is closed and you can't even post to their IRC channel. 

Looks like that show is stuffed indefinitely then

**Comment by markus101** [comment]
You need to have a registered user to post because of spam issues with unregistered users.

**Comment by antigravity83** [comment]
Yeah registrations are closed

**Comment by markus101** [comment]
I meant registering on IRC: https://www.wikihow.com/Register-a-Nickname-on-Freenode

AFAIK registration was disabled on thexem.de due to the influx of users creating bad mappings that were never published, but were visible and blocked everyone that wasn't a full blown moderator from fixing the issue.

**Comment by antigravity83** [comment]
Ah ok thanks - I'll give that a shot

**Comment by antigravity83** [comment]
I'm now a bit confused. TVDB lists the seasons as Season 2010, Season 2011 instead of Season 1, Season 2 etc. 

Should Sonarr replicate the Season numbering of TVDB?
