### ISSUE TITLE
Add "miniseries" series type

### ISSUE THREAD

**Issue by TotalInsanity4** [Sonarr/Sonarr#3428]
**Describe the problem**
Currently Sonarr's "standard" series type defaults to a file naming scheme like "Series Title - S00E00 - Episode Name," which in most cases is what one would want. This becomes a minor issue when archiving miniseries for Emby, though, as Emby will assume that anything with a season number in the filename should be sorted into a season, even if it's not in a season folder.

**Describe any solutions you think might work**
Two possible solutions would work, one that I would consider "correct" and one that should be a pretty simple band-aid fix. The first option is to add a "miniseries" show type (alongside standard, daily, and anime) with the default naming scheme of "{episode:00} {Episode Title}." This should work across most media software, even in the case of season folders being used. The second option is to simply remove the requirement for both season and episode information to be present in the filename, and allow users to delegate the "anime" type for situations like this, considering the default anime naming scheme is identical to the standard type anyway. As I said, not ideal, but it would work for this.

This isn't urgent, by any means, but it would help clean up the libraries a bit of people with content along the lines of Good Omens and the old IT miniseries using software that doesn't have the ability to ignore season sorting.

**Comment by markus101** [comment]
Episode number only is going to conflict with absolute episode number, it's not worth the effort of fighting with that to support a different series type.

We do want to support episode only in the file name, but it will require a season folder to parse properly, we don't plan to relax the requirement when validating file names.

Using season from folder is covered here: https://github.com/Sonarr/Sonarr/issues/903
