### ISSUE TITLE
Custom Script 'Test' does not execute the script

### ISSUE THREAD

**Issue by zedrdave** [Sonarr/Sonarr#3429]
**Describe the bug**

When adding a custom post-process script, the UI correctly enforces that the script exists, but clicking on 'Test' returns `Testing MyScript succeeded` no matter what, seemingly without executing the script (according to the doc, the script should be called with a `test` event).

I tested this with the following script:

```
#!/bin/bash
env > /tmp/env_var.txt
```

Nothing appeared in `/tmp/env_var.txt`, no matter how many times I clicked on the Test button.

Eventually, when a real event occurred, the script was exectuted and the file created:

```
INVOCATION_ID=88c4c6c6c69c40b29f2921262ed074ea
OS_VERSION=10
sonarr_series_tvmazeid=216
sonarr_episodefile_episodenumbers=6
RUNTIME_VERSION=6.4.0.198
USER=sonarr
sonarr_eventtype=Download
[etc]
```

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: dietPi
 - mono (macOS/Linux) Version: 6.4.0.198

**Comment by markus101** [comment]
v3 will execute the script, v2 will not.

**Comment by zedrdave** [comment]
Ha. I missed that in the doc. Sorry for this.

Is there currently any way to trigger the script, other than waiting for a real event to happen through a download/rename etc?

**Comment by markus101** [comment]
No there isn't.
