### ISSUE TITLE
/api/episode?seriesId={id} Returns garbish

### ISSUE THREAD

**Issue by masterholdy** [Sonarr/Sonarr#3431]
**Describe the bug**
Im trying to use Bazarr for the first time. Bazarr throws an exceptions because its calling  /api/episode?seriesId={id} and the endpoint returns garbish
Example Response: https://pastebin.com/raw/wWVheHfy

Link to Bazarr Issue: https://github.com/morpheus65535/bazarr/issues/683

**Logs**
https://pastebin.com/raw/ewr5iXDZ

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: 4.8

**Comment by markus101** [comment]
Your DB is corrupt. 

You have four options in no particular order:

1. Repair the DB (it's SQLite)
2. Restore from backup (see the wiki)
3. Remove the series and re-add it (you'll lose history for the series/episodes, including the original name)
4. Manually remove the media info for that episode in the DB easiest would be `UPDATE EpisodeFiles SET MediaInfo = '{}' WHERE SeriesId = 12345`, where 12345 is the actual series ID)

**Comment by masterholdy** [comment]
how to i get the name of the show by id? i would like to test option 3

**Comment by markus101** [comment]
Unfortunately it’s not exposed in the UI. Either getting the response from the series API endpoint or querying the API for that series ID would be the easiest.
