### ISSUE TITLE
Synology - Manual Import, "Move Files" actually copies followed by delete

### ISSUE THREAD

**Issue by Presjar** [Sonarr/Sonarr#3433]
### System Information/Logs

SONARR Ver 2.0.0.5338:
MONO Ver 5.18.0.240:
Synology DSM 6.2.2-24922 Update 3:
Debug Log https://pastebin.com/9b2igNgu 2

When I run a manual import, in this case a 200GB Season Rip, I select the MOVE option, however Sonarr does not actually ‘move’ the file and rename. Rather :

“.backup” file with the original name shows up in the original import directory,
The new filename version is copied into the show directory with a “.partial~” extension. You can see the file size of this increase
The .partial~ is then removed for the file name and the original file in the import directory is deleted.

### Additional Information
Provided initial testing and feedback on forums [https://forums.sonarr.tv/t/manual-import-move-files-actually-copied-then-deleted/](Link)

**Comment by markus101** [comment]
Based on the logs I don't see anything being copied, instead it looks like Sonarr it hardlinking the file to the backup file and moving it. This allows Sonarr to validate the file was moved without truncation without actually copying the file.

Trace logs will confirm that's the case.

**Comment by Presjar** [comment]
Hi Markus, I can agree that the creation of the .backup file is instant, however why does the file in the destination folder with .partial~ grow in size from 0KB? I can hear the disk activity grinding away until the file size reaches 100%. Importing 200GB took something like 30min to complete, so it really is making a second copy of the data.

I also checked if (as suggested by forum user, _rhom_, )  "Settings > Media Management > Use Hardlinks instead of Copy", was enabled. It was enabled already.  I tested again after disabling this option also and there was no change to the behaviour.

**Comment by markus101** [comment]
What do the trace logs show? Without the only thing I can do is guess...

**Comment by Presjar** [comment]
> What do the trace logs show? Without the only thing I can do is guess...

I have attached the trace I just saved below. Imported one ~16GB file 

> Battlestar Galactica (2003) - S00E02 - Battlestar Galactica- The Miniseries (2) Bluray-1080p.mkv

[[Issue3433]sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/3920849/Issue3433.sonarr.trace.txt)

**Comment by markus101** [comment]
Thanks for the logs.

Looks like this is a limitation in v2 that has been addressed in v3. It's not something that will be backported to v2, so until you're able to upgrade (partially on us to get it out of beta), this behaviour will continue.

**Comment by Presjar** [comment]
Thank you for checking. Looking forward to v3!
