### ISSUE TITLE
Health Notification delay / N retries before notifying

### ISSUE THREAD

**Issue by dovry** [Sonarr/Sonarr#3436]
**Describe the bug**
Sonarr sends notification instantly if it can't detect a download client / indexer on boot, which might take a few seconds to respond,when deploying with docker-compose, for example. This usually means false alarm.

**System Information**
 - Version - 3.0.3.658
 - Package Version - 3.0.3.658-ls152 by linuxserver.io
 - Windows 10 - Docker linux container

**Additional context**
Being able to set a delay timer (automatic/manual), or N retries could prevent some spam, as Windows 10 reboots itself during off hours, resulting in containers restarting and potentially coming home/waking up to false alarm health issues.

**Comment by markus101** [comment]
Given the Sonarr container depends on other containers, then it should wait for those to start before starting itself.

With compose there is `depends_on`:
https://docs.docker.com/compose/startup-order/

Health checks are re-run automatically when changes are made or status change, we have no plans to add a configurable or set delay to them running on startup. The download client itself is tested every time a release needs to be grabbed.
