### ISSUE TITLE
Seasons 9 and 10 merged into season 8 not displaying/parsing correctly since update. 

### ISSUE THREAD

**Issue by zoomdbz** [Sonarr/Sonarr#3437]
**Describe the bug**
Episodes of season 9 and 10 are all in season 8 and not displaying correctly for Ancient Aliens TV show.

**Screenshots**
Shown here 
![sonar bug](https://user-images.githubusercontent.com/54127744/69936014-895d3300-14a4-11ea-8c4a-7334eb179a27.PNG)

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: Windows 10
 - .net Framework 4.8 Advanced Services

**Comment by markus101** [comment]
> Seasons 9 and 10 merged into season 8 not displaying/parsing correctly since update

There hasn't been an update to v2 since August 14th.

https://www.thetvdb.com/series/ancient-aliens

Doesn't show seasons 9 or 10, this is a problem with The TVDB. They'll need to fix it since the series is locked.
