### ISSUE TITLE
Support webtorrent for downloading

### ISSUE THREAD

**Issue by pvinis** [Sonarr/Sonarr#3438]
**Describe the problem**
It would be nice to have support for [webtorrent](https://webtorrent.io/)

**Describe any solutions you think might work**
Same as with the other supported torrent clients, it's nice for a tool to support my choice of client, rather than me needing to install and use a new client.

**Additional context**
Nothing.

**Comment by markus101** [comment]
Please use the template when opening a feature request.

I'm particularly interested in what problem this would solve, especially given it's designed for streaming, which doesn't align with Sonarr.

**Comment by pvinis** [comment]
I edited the original. No particular benefit from the streaming ability of webtorrent.

**Comment by markus101** [comment]
It looks like their docs describe how to use the package in a node.js app, but do they have docs on how to talk to their Desktop client via an API? If they don't have an API the best integration you can get with it is via torrent blackhole.

**Comment by markus101** [comment]
I was unable to find docs for talking to the web API, so I'm closing this. We can re-open if docs are eventually available.

**Comment by ChaitanyaPramod** [comment]
The advantage of webtorrent is that it lets us connect to compatible peers over WebRTC data channel in addition to TCP/UDP.

I've more success with WebRTC with my ISP
