### ISSUE TITLE
double episode - unable to parse name 

### ISSUE THREAD

**Issue by Dinth** [Sonarr/Sonarr#3439]
**Describe the bug**
Sonarr is unable to download double episodes, it errors with "Unable to parse episodes from a file name" (as per first result on the screenshot).
The error occurs if the double episode is marked in the following format SxxExx-xx. I believe everything works fine if the episode is marked with SxxExx-Exx format though (second result).

**Screenshots**

![Screenshot from 2019-12-04 09-08-05](https://user-images.githubusercontent.com/313674/70128954-cb899e80-1675-11ea-96e8-3b3ea4e727fe.png)

**Comment by markus101** [comment]
Please fill out the entire template, including the debug logs.
