### ISSUE TITLE
Missing scroll bar and/or auto fit on aphrodite

### ISSUE THREAD

**Issue by EnorMOZ** [Sonarr/Sonarr#3441]
**Describe the bug**
On a movie search result it does not auto fit the page width. Nor does it have a scroll bar to view the entire title of results ie; quality, peers, language etc

**Screenshots**
<img width="1183" alt="Screen Shot 2019-12-06 at 8 54 07 AM" src="https://user-images.githubusercontent.com/13998170/70329361-3a4b3100-1809-11ea-93cc-802c695a1a20.png">

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 3.0.0.2239
 - Operating System: Ubuntu 18.04.3
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
 - OS: All
 - Browser: All
 - Version: All

**Comment by Qstick** [comment]
Why are you posting Radarr bugs on Sonarr GitHub?

**Comment by EnorMOZ** [comment]
doh 🤦‍♂
