### ISSUE TITLE
MediaInfo Library could not be loaded libmediainfo.0.dylib assembly:<unknown assembly> type:<unknown type> member:(null)

### ISSUE THREAD

**Issue by devondragon** [Sonarr/Sonarr#3442]
### System Information/Logs

**Sonarr Version:** 3.0.3.663

**Operating System:** macOS 10.15.1

**.net Framework (Windows) or mono (macOS/Linux) Version:** Mono: 6.4.0.198

**Link to Log Files (debug or trace):**

### Additional Information

After the latest update I am now getting the error: MediaInfo Library could not be loaded libmediainfo.0.dylib assembly:<unknown assembly> type:<unknown type> member:(null) and Sonarr has stopped picking up newly downloaded episodes.  

I have see the libmedia library in the Sonarr application package, and I have also installed it via brew months ago.  Everything was working until the update today. 

Any ideas?

**Comment by devondragon** [comment]
[error.txt](https://github.com/Sonarr/Sonarr/files/3934523/error.txt)

**Comment by markus101** [comment]
Nothing in the latest update made changes related to media info.

Between Catalina (that aggressively blocks disk access) and mono 6.x changing how disk access happens it's very like not Sonarr's fault. Searching for `libmediainfo.0.dylib assembly:<unknown assembly> type:<unknown type> member:(null)` I cam up with https://github.com/mono/mono/issues/16521 which has been closed, but likely not in a released version.

**Comment by devondragon** [comment]
Okay I will try to downgrade Mono and see if that helps.  Thanks.  I love Sonarr and I'd hate to have to give it up, but since Catalina it has been really difficult to keep the system working...

**Comment by devondragon** [comment]
Downgrading to Mono 5.20.1 has solved this issue for me.  Thanks!!
