### ISSUE TITLE
Ability to disallow upgrades for Release Profiles

### ISSUE THREAD

**Issue by imathew** [Sonarr/Sonarr#3443]
Sonarr upgrades episode files when another is found with a higher Release Profile score. There seems to be no ability to disable upgrades.

Quality Profiles and Language Profiles both have an "Upgrades Allowed" checkbox. A similar checkbox and functionality would be useful in Release Profiles.

Release profiles are are very welcome feature to set my preference for initial downloads (thanks!), but once I have an episode I don't need them upgraded. Currently using version 3.0.2.560.

**Comment by Elehiggle** [comment]
Yes, definitely needed. I want Sonarr to prefer HEVC/x265/h265 on the initial search, but don't endlessly upgrade releases. From a logic standpoint maybe a score of 0 for HEVC etc. could work, but it has other drawbacks.

**Comment by arpitgupta** [comment]
This would be great. I wanted to use prefered terms to prefer certain sound qualities if multiple option s are found at search but not upgrade them. So having option for Upgrades allowed for prefered would work like a charm.

**Comment by Napsterbater** [comment]
I'm trying to get Sonarr to do the opposite, and can't. Did this change?

I want sonarr to upgrade a particular quality to the highest Release Profile/Prefered Term.

**Comment by bakerboy448** [comment]
set scoring and cutoffs appropriately

**Comment by imathew** [comment]
Thanks bakerboy for the consideration, I take your point and I can disable upgrades entirely in the quality profiles to prevent any kind of upgrade, and I have. It's not a perfect solution because sometimes I do want to upgrade qualities, but it meets most of my needs.

I do think the upgrade handling in Release Profiles is inconsistent, though (when compared to Quality and Language Profiles) and limits the usefulness of the otherwise great Preferred Terms, but I appreciate it's an edge case that affects only a few of us, if this ticket is any guide.
