### ISSUE TITLE
Failed Download Handling, expand support to Torrent Downloaders

### ISSUE THREAD

**Issue by roberestarkk** [Sonarr/Sonarr#3444]
## Feature Request
Periodically check for 'in-progress' downloads, to see if their torrent has been removed from the download client, and if so, mark them as failed.  
Either that, or have a mechanism within Sonarr itself to fail downloads whose progress hasn't changed for a configurable amount of time.

### What problem are you looking to solve?
Sometimes, indexers will not accurately represent the number of seeders of a torrent. This means that despite setting a minimum number of seeders, often torrents will be grabbed whose actual seed count is 0.  
This torrent will **never** complete.   
I want to fail this torrent and search for a new one automatically when this happens.  
Currently the way I have to do this is manually mark it as failed in Sonarr.

I've got my download client setup to automatically delete downloads if they have no seeders, but Sonarr (to my knowledge) does not handle this and won't re-try the download.

### Other Information
Looking at these sort of downloads in the 'Activity -> Queue' screen, I can see that their time left is 00:00:00 despite their progress being < 100%  
Perhaps that could be a way to check.  
That screen even gives the option to remove from download client, but I suspect that removal doesn't also trigger the failure of the download, and even if it did, we can't check the seeders from there, or the 'time active', so we can't say whether it's failed or just really slow.

**Comment by fryfrog** [comment]
I'd suggest digging through past issues, I'd be surprised if this doesn't already exist. It is a long standing issue w/ torrent clients, which just don't have an idea of failed downloads.

I've seen someone on Discord who created a Deluge plugin that added failure and linked back to Sonarr/Radarr via API to report it.

Usenet has failure, it lives in the download client. Personally, I think it belongs in the torrent client.

**Comment by roberestarkk** [comment]
I did, and have looked again. Couldn't find anything through the github search https://i.imgur.com/6DjehvW.png, but googling around for "stalled download handling deluge plugin for sonarr" I ironically found the actual issue #958 
No reference to the plugin you mentioned unfortunately, but there is an example of a quick and dirty script so there's some hope there. 

I did look for a plugin before posting this, and have looked again harder since seeing one existed. Any chance for a link? My Google-Fu is failing me hard.

I do agree that failure detection and handling belongs on the download client, which is why I installed the Deluge plugin that detects and acts on my definition of failure.    
What I'm suggesting now is just a 'standard' way to communicate that failure back to Sonarr which does already support handling failures from a download client to a degree.  
  
Obviously the most basic and native mechanism for communicating this would be by comparing states between Sonarr and Deluge. Deluge says "No such Torrent" but Sonarr's latest history says "Sent to Deluge". Clearly something has gone wrong here, we should fail this download.    
Even if Sonarr was not handling completion by removing the torrent, it would still retain it's own 'Download Completed' history status and know not to fail it after that point, presumably before which it would never not be in the download client.

**Comment by markus101** [comment]
Closing since this is covered by #958

**Comment by markus101** [comment]
> Deluge says "No such Torrent" but Sonarr's latest history says "Sent to Deluge". Clearly something has gone wrong here, we should fail this download.

That is not a failure state to Sonarr, removing items does not trigger failed downloads; only a download in the client that indicates it's failed is treated as a failure, that's how it's done in usenet clients.

A download that is completed wouldn't move to failed because once it's completed Sonarr stops processing updates for it.

**Comment by springjools** [comment]
I think it was me who talked about this in discord. I created a new feature for the deluge autoremove plugin that uses the sonarr api to remove it from sonarr queue, if torrent is in a failed state. It's here:

https://github.com/springjools/deluge-autoremoveplus

But currently there is some issue with the removal, for some reason the torrent is being removed twice, and that makes deluge crash.

**Comment by springjools** [comment]
Just a update: since sonarr v3 this works by blaclisting the torrent in sonarr and removing it internally in deluge.
