### ISSUE TITLE
Backups w/ version in file name not shown in UI

### ISSUE THREAD

**Issue by fryfrog** [Sonarr/Sonarr#3446]
**Describe the bug**
Backups *are* created, both scheduled and manual, but they are *not* shown in the UI.

**Screenshots**
[[https://i.imgur.com/sM5DHDD.png]]

```
0 ✓ fryfrog@apollo /var/lib/sonarr/Backups $ ls -ltr scheduled/ manual/
...
-rw-rw-r-- 1 sonarr sonarr 56923232 Dec  5 00:12 sonarr_backup_2019.12.05_00.11.29.zip
-rw-rw-r-- 1 sonarr sonarr 57067813 Dec  6 00:14 sonarr_backup_v3.0.3.661_2019.12.06_00.13.06.zip
-rw-rw-r-- 1 sonarr sonarr 57032917 Dec  7 00:15 sonarr_backup_v3.0.3.663_2019.12.07_00.14.38.zip

manual:
total 165970
-rw-rw-r-- 1 sonarr sonarr 56822055 Nov 15 13:47 sonarr_backup_2019.11.15_13.46.19.zip
-rw-rw-r-- 1 sonarr users  57054400 Dec  7 19:35 sonarr_backup_v3.0.3.664_2019.12.07_19.34.27.zip
-rw-rw-r-- 1 sonarr users  57054579 Dec  7 19:37 sonarr_backup_v3.0.3.664_2019.12.07_19.36.38.zip
```

**Logs**
```
19-12-7 19:45:20.7|Info|BackupService|Starting Backup
19-12-7 19:45:20.7|Debug|BackupService|Backing up config.xml
19-12-7 19:45:20.7|Debug|DiskTransferService|Copy [/var/lib/sonarr/config.xml] > [/tmp/sonarr_backup/config.xml]
19-12-7 19:45:20.8|Debug|BackupService|Backing up database
19-12-7 19:45:23.3|Debug|BackupService|Creating backup zip
```

**System Information**
 - Sonarr Version: 3.0.3.664
 - Operating System: Arch Linux
 - .net Framework (Windows) or mono (macOS/Linux) Version: 6.4.0

**Comment by Qstick** [comment]
https://github.com/Sonarr/Sonarr/blob/3cbdd6bfd3a8a7314457de9e598c021b2de16847/src/NzbDrone.Core/Backup/BackupService.cs#L42 Regex used for finding file doesn’t allow the ”v”

**Comment by fryfrog** [comment]
https://github.com/Radarr/Radarr/commit/7a95fb55bd9ba325cd01f08cbc0685ea44eb4ba0

^ This is @Qstick's fix on Radarr v3.

**Comment by Qstick** [comment]
@Taloth fixed this yesterday as well I believe, can't this be closed

**Comment by markus101** [comment]
Yup, fixed in https://github.com/Sonarr/Sonarr/commit/93b20960b8f640bc6ba2b1e19f488abcdfb1ea6d
