### ISSUE TITLE
Sonarr (and Radarr) won't connect to Download Station

### ISSUE THREAD

**Issue by dhruvbhutani** [Sonarr/Sonarr#3448]
My current set up has been 100% functional for the last 6 months or so. Over the last week, both of them no longer connect to Download Station. I can't see what the issue is at my end because nothing has changed in my set up. I've included the log file below. Can someone help me diagnose this? 

https://pastebin.com/aa931vcj

**Comment by markus101** [comment]
Please open a thread on the forums or subreddit for support.
