### ISSUE TITLE
Downloading nzb failed ---> System.Net.WebException

### ISSUE THREAD

**Issue by DatNoHand** [Sonarr/Sonarr#3449]
**Describe the bug**
Exception is thrown when there are too many redirects until sonarr gets the nzb file.

**Logs**
[Pastebin](https://pastebin.com/3L4mswXC)

**System Information**
 - Sonarr Version: 2.0.0.5338
 - Operating System: `Linux lw835 4.19.86-xanmod42 #1.191124 SMP PREEMPT Sun Nov 24 22:10:14 -03 2019 x86_64 GNU/Linux`

**Additional context**
As seen in the log, I have chained multiple NzbHydras. When sonarr tries to get a release from the chained hydra it will fail with this error. This setup has worked until I switched seedbox providers.

**Comment by fryfrog** [comment]
How many redirects is too many? Why can't you just... have one?

**Comment by DatNoHand** [comment]
Let's say my friend and I each have a server, he with his setup and I with mine. Now he happens to use different indexers than me, so we gave eachother access to our nzbhydras to have the most variety in indexers.

**Comment by fryfrog** [comment]
Sure, but instead of adding his to your nzbhydra... add it to your sonarr.

**Comment by DatNoHand** [comment]
You beat me, I just edited my post

**Comment by fryfrog** [comment]
Also, it sounds like you may have only had 2-3 redirects? Knowing might help devs if they want to allow this instead of fail.

**Comment by DatNoHand** [comment]
But nonetheless, I think there should be an option to set the max amount of redirects. Maybe make it an advanced one?

> Also, it sounds like you may have only had 2-3 redirects? Knowing might help devs if they want to allow this instead of fail.

Look at the pastebin, the requests look like:

[PasteBin) ](https://pastebin.com/3L4mswXC)
http://nzbhydra.dl.(removed).dev/getnzb/api/2622195321520193517?apikey=(removed) ->
https://nzbhydra.dl.(removed).dev/getnzb/api/2622195321520193517?apikey=(removed) ->
https://hydrashared.(removed).li:443/getnzb/api/1519619213240136179?apikey=(removed) ->
https://scenenzb.com/getnzb/06de9f1d368dc26e2957e7844bb1f7162802a5b1.nzb&i=1416&r=(removed)

**Comment by Taloth** [comment]
You should fix that http -> https redirect to the same server. Anyway, upped it from 3 to 5 max redirect.

**Comment by DatNoHand** [comment]
All Indexers are added via https:// in sonarr, but I will look into the issue

Thank you for increasing the limit!

**Comment by Taloth** [comment]
Hydra is probably configured to return http: nzb urls
