### ISSUE TITLE
Wiki API powershell example -- convertto-json -- include depth

### ISSUE THREAD

**Issue by drtcode** [Sonarr/Sonarr#3450]
On Sonarr Wiki, there is a powershell example where we pipe the episode body to "ConvertTo-Json", however the **Episode** object has children that go deeper than the default depth of 2 that that command uses. (e.g. **3**: Episode.**episodeFile.quality.quality**; etc)

https://github.com/Sonarr/Sonarr/wiki/api#examples

Suggest changing line:
`$params = @{"name"="RescanSeries";"seriesId"="$sonarr_seriesid";} | ConvertTo-Json`
to:
`$params = @{"name"="RescanSeries";"seriesId"="$sonarr_seriesid";} | ConvertTo-Json -Depth 100`
(depth of 100 chose arbitrarily; 3 seems to be all that is needed for this "Episode" example)

**Comment by markus101** [comment]
The wiki and it's example are user contributed, please feel free to update it.

**Comment by drtcode** [comment]
Thanks! Done. Hope it helps save someone else some time :)
