### ISSUE TITLE
1 Series = 1 Indexer

### ISSUE THREAD

**Issue by LithiumCFK** [Sonarr/Sonarr#3452]
Предлагаю реализовать привязку конкретного индексера к сериалу.
А то кода в сонарр добавлено несколько индексеров авто поиск новых серий производится по первому совпадению критериев.

****
I propose to implement the binding of a specific indexer to the series.
And then the code in the sonarr added several indexers auto search for new series is performed according to the first match of the criteria.

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/487
