### ISSUE TITLE
Sonnar is grabbing episodes already downloaded

### ISSUE THREAD

**Issue by ocr893sa** [Sonarr/Sonarr#3453]
**Describe the bug**
Sonnar is grabbing the same, link of rarbg shows is the exact same episode, twice from the same source AFTER moving it to the desired location and renaming it

**Screenshots**
![image](https://user-images.githubusercontent.com/54455270/70531296-eb790080-1b54-11ea-8de4-67f4a4588bd6.png)

**Logs**
https://privatebin.net/?22e796a53f51b408#36CYMPSX1MUdwWNBNzxVMU4LCyeKv4nZCNJy8ZQs159c

**System Information**

 - Sonarr Version: 3.0.3.664
 - Operating System: Windows 10
 - .net Framework (Windows) 4.8

**Additional context**
When the duplicate episode appeared in uTorrent I removed it manually. This isn't the first time this happened but it didn't until the last update I think.

**Comment by markus101** [comment]
> 19-12-10 13:37:18.4|Debug|UpgradableSpecification|Comparing preferred word score. Current: 0 New: 10
19-12-10 13:37:18.4|Debug|UpgradableSpecification|New item has a better preferred word score

It's your preferred words, which probably has something to do with the file name, which is different from the release name.

Release name: `Batwoman.S01E09.Crisis.on.Infinite.Earths.Part.2.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]`
File name: `Batwoman.S01E09.Crisis.on.Infinite.Earths.Part.2.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv`

`WEBRip` vs `WEB-DL` would be my guess unless `[rarbg]` is in there, you'll have to update your preferred words to account for this.
