### ISSUE TITLE
Add Series takes too long when dealing with a large collection.

### ISSUE THREAD

**Issue by shadow7412** [Sonarr/Sonarr#3454]
**Describe the problem**
I have a folder containing all the TV Shows I have acquired over the years.

When a new season of something I've already struck off the sonar list comes out, adding an existing folder takes a long time because for each folder a TVDB scan takes place before it shows me later folders.

**Describe any solutions you think might work**
Allow the user to select a folder from the list *first* - then do the scan. Alternatively, display the folders that haven't been scanned so they can be filled out later.

**Comment by markus101** [comment]
This behaviour is changed in v3, we're not going to change v2.

**Comment by shadow7412** [comment]
That's great news. I'll look into v3.
