### ISSUE TITLE
Password Forum login error

### ISSUE THREAD

**Issue by Corona-Groep-NL** [Sonarr/Sonarr#3455]
Got a error when logout when forum login is enabled and created fresh install latest version 

`{
  "message": "Object reference not set to an instance of an object",
  "description": "System.NullReferenceException: Object reference not set to an instance of an object\n  at Nancy.Authentication.Forms.FormsAuthentication.BuildLogoutCookie (Nancy.Authentication.Forms.FormsAuthenticationConfiguration configuration) [0x00000] in <91c66dca293e4531909364de82529d4c>:0 \n  at Nancy.Authentication.Forms.FormsAuthentication.LogOutAndRedirectResponse (Nancy.NancyContext context, System.String redirectUrl) [0x00008] in <91c66dca293e4531909364de82529d4c>:0 \n  at Nancy.Authentication.Forms.ModuleExtensions.LogoutAndRedirect (Nancy.INancyModule module, System.String redirectUrl) [0x00006] in <91c66dca293e4531909364de82529d4c>:0 \n  at NzbDrone.Api.Authentication.AuthenticationModule.Logout () [0x00016] in <20da08f0634d42cf91a879fec9ee7aa5>:0 \n  at NzbDrone.Api.Authentication.AuthenticationModule.<.ctor>b__2_1 (System.Object x) [0x00000] in <20da08f0634d42cf91a879fec9ee7aa5>:0 \n  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 "
}`

**Comment by markus101** [comment]
Please fill out the entire template. There are at least two versions people would call the latest version.

**Comment by markus101** [comment]
I'm not able to reproduce this in v2 or v3.
