### ISSUE TITLE
[Idea] Switch to .dotnet framework

### ISSUE THREAD

**Issue by samip5** [Sonarr/Sonarr#3456]
**Describe the problem**
No .dotnet support, not being able to contribute if not using Windows.

**Describe any solutions you think might work**
Re-work Sonarr to use .dot core framework instead of .net framework.

**Comment by Qstick** [comment]
This is a dupe of #948..... Also there is nothing stopping you from developing on any os.... People have contributed to  Sonarr from non windows development environments for 9 years now...

**Comment by samip5** [comment]
I see, closing this one.
