### ISSUE TITLE
SQL Exception while importing backup

### ISSUE THREAD

**Issue by Richigeht** [Sonarr/Sonarr#3458]
**Describe the bug**
Restoring a backup into latest Sonarr v3 and I got a SQL exception.

Exception: SQL Logic error or missing database no such file:
EpisodeFiles
WhileProcessing
ALTER TABLE "EPISODEFILES" ADD COLUMN "LANGUAGE" INTEGER NOT NULL DEFAULT "0"

**System Information**

 - Sonarr Version: 3 latest from today
 - Operating System: Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: NET Framework 4.8

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
> Sonarr Version: 3 latest from today

What is the exact version?

Please post the debug logs, but it looks like the backup may be corrupt.

**Comment by Richigeht** [comment]
Shit...
I seem to have issues with the pc (thought its the drive but looks like might be the ram or something else) and it hangs a lot of times that's why I didn't include those logs just yet. 

How do I reset the Software to import another backup? 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/wiki/Backup-and-Restore
