### ISSUE TITLE
Transmission uses sonarr favicon in Safari 13.0.4 (macOS 10.15.2) - DietPi v6.26.3

### ISSUE THREAD

**Issue by bbsixzz** [Sonarr/Sonarr#3460]
**Describe the bug**
https://github.com/MichaIng/DietPi/issues/3267

**Screenshots**

sonarr:
![](https://i.imgur.com/emmQRhm.png)

Transmission:
![](https://i.imgur.com/DDztwQ3.png)

**System Information**
Version
2.0.0.5338
Mono Version
6.6.0.161

**UI Bugs:**
 Safari 13.0.4 (macOS 10.15.2)

**Additional context**
 DietPi v6.26.3 on Raspberry Pi 4

**Comment by markus101** [comment]
Sonarr is using standard techniques for supplying the favicon as well as images for mobile pinning (the `apple-touch-icons). v3 does make some changes to this (to support newer standards), perhaps that'll work better for you (v3 is in beta).

**Comment by bbsixzz** [comment]
Yes I understand, but maybe you can explain this odd behavior (check the video):

https://github.com/MichaIng/DietPi/issues/3267#issuecomment-566805911

**Comment by markus101** [comment]
I'm not sure why Safari would be using the wrong favicon.
