### ISSUE TITLE
Failed to load queue

### ISSUE THREAD

**Issue by ocr893sa** [Sonarr/Sonarr#3461]
**Describe the bug**
Sonarr is not able to show the queue.

**Screenshots**
![image](https://user-images.githubusercontent.com/54455270/71047942-b6b10e80-213d-11ea-89d0-2f732501fe71.png)

**Logs**
https://privatebin.net/?25e65c437c7962cd#5hjqjmG8UDHgzvaWdN38vwoV4sJXqqQNewDTnfQPEnE2

**System Information**

 - Sonarr Version: 3.0.3.664
 - Operating System: Windows 10
 - .net Framework (Windows) 4.8

**Additional context**
Sonarr is talking to uTorrent because is able to import the downloaded files and is deleting them from uTorrent so I don't know why it's failing.

**Comment by markus101** [comment]
Please use the forums or subreddit for support.
