### ISSUE TITLE
More information from download clients

### ISSUE THREAD

**Issue by georgeduckett** [Sonarr/Sonarr#3462]
**Describe the problem**
The download client I use with Sonarr is used for multiple things (Radarr among others). Since my Synology box is under-powered I have a max of two concurrent torrents. Often downloads from Sonarr are queued. If this is the case, it would be useful to know what position the items were in the queue.

**Describe any solutions you think might work**
In place of `Time Left` the queue position could be shown (something like `Q: ##` or `Q Pos: ##` maybe), if applicable.

--
Another interesting possibility would be to optionally display the actual other items in the download client (in queue order ideally), although I'm not sure this is viable or wanted.

**Comment by markus101** [comment]
We don't have plans to track/display queue position for items in the download client.

**Comment by georgeduckett** [comment]
Hi Markus, Thanks for the quick reply. Is this something that you actively don't want in Sonarr, or isn't feasible, or is it just a case of limited resources and there being other other priorities? For example, if I were to take a look and possibly create a pull request, would it be considered for inclusion?

**Comment by markus101** [comment]
With the number of download clients and the likely limited number of people this would be useful for it's not something we want to support in Sonarr. At this time we're not interested in a PR to support it.
