### ISSUE TITLE
Custom Formats

### ISSUE THREAD

**Issue by nickp85** [Sonarr/Sonarr#3463]
**Describe the problem**
Radarr has introduced a way to implement custom tags so that you can look for media and prefer specifically things like hevc/h265 or atmos.  I am using this with rdarr and it works very nicely.

**Describe any solutions you think might work**
Implement custom formats like Radarr has

**Additional context**
![image](https://user-images.githubusercontent.com/59027847/71111557-b2b1da80-2197-11ea-9cee-6a317416bb8a.png)

**Comment by markus101** [comment]
We have no plans to add custom formats, but this is achievable with Preferred Words in Release Profiles in Sonarr v3.
