### ISSUE TITLE
Missing root folder        still happens after deleting them all in the movie editor.

### ISSUE THREAD

**Issue by tostane** [Sonarr/Sonarr#3472]
Im not sure if this is a bug of im not understanding.    i changed path on the movie drive.    So i used the movie editor to change all the paths.      but it seems every time a new movie is put on drive its trying to put it on the old path.       i have to edit every new movie now and change the path to the correct path.    and the error message about missing root continues to happen.           do you store that in some other place ?

**Comment by markus101** [comment]
Did you mean to post this to Radarr’s repository?

If you’re looking for support with Sonarr please use the forums or subreddit.

**Comment by tostane** [comment]
radarr is movie    sonarr   is tv   why post movie question to the tv ap ?
