### ISSUE TITLE
Bitrate limit in quality definitions

### ISSUE THREAD

**Issue by mistergoodwin** [Sonarr/Sonarr#3474]
**Describe the problem**
I believe bitrate is more a direct metric for determining the quality of media.
Currently we work off file size limits that only give examples of 30 and 60 minute lengths.

**Describe any solutions you think might work**
Two extra columns on the Quality Definitions page that allow you to directly set min and max bitrate instead of manually calculating like I have below.

**Additional context**
It's not perfect because you need to factor in that its a combined video and audio bitrate and master audio / surround tracks are significantly larger than regular stereo.

I currently work off the following when setting up sonarr instances.
450 MB for each 60 Min at 1 Mb/s:
1 Mb/s for 60 Min = 450 MB
2 Mb/s for 60 Min = 900 MB
3 Mb/s for 60 Min = 1350 MB
4 Mb/s for 60 Min = 1800 MB
5 Mb/s for 60 Min = 2250 MB
6 Mb/s for 60 Min = 2700 MB
7 Mb/s for 60 Min = 3150 MB
8 Mb/s for 60 Min = 3600 MB
9 Mb/s for 60 Min = 4050 MB
10 Mb/s for 60 Min = 4500 MB
11 Mb/s for 60 Min = 4950 MB
12 Mb/s for 60 Min = 5400 MB
13 Mb/s for 60 Min = 5850 MB
14 Mb/s for 60 Min = 6300 MB
15 Mb/s for 60 Min = 6750 MB
16 Mb/s for 60 Min = 7200 MB
17 Mb/s for 60 Min = 7650 MB
18 Mb/s for 60 Min = 8100 MB
19 Mb/s for 60 Min = 8550 MB
20 Mb/s for 60 Min = 9000 MB
21 Mb/s for 60 Min = 9450 MB
22 Mb/s for 60 Min = 9900 MB
23 Mb/s for 60 Min = 10350 MB
24 Mb/s for 60 Min = 10800 MB
25 Mb/s for 60 Min = 11250 MB
26 Mb/s for 60 Min = 11700 MB
27 Mb/s for 60 Min = 12150 MB
28 Mb/s for 60 Min = 12600 MB
29 Mb/s for 60 Min = 13050 MB
30 Mb/s for 60 Min = 13500 MB

**Comment by Taloth** [comment]
You mean like we have in Sonarr v3?

![image](https://user-images.githubusercontent.com/6383890/71404720-9d272f80-2633-11ea-95f5-668487f5fc4c.png)

**Comment by mistergoodwin** [comment]
Oh neat, it's so close but why megabytes per minute?
All sources (NFOs) and tools (handbrake, mediainfo, vlc, plex, emby, jellyfin, ... ) measure in bits per second. I would still need to convert to a bitrate:

7.5 MB for each 1 Min at 1 Mb/s:
1 Mb/s for 1 Min = 7.5 MB
2 Mb/s for 1 Min = 15.0 MB
3 Mb/s for 1 Min = 22.5 MB
...

**Comment by Taloth** [comment]
Coz it's stored like that in the database. Simple as that.
It's also a bit less technical for end users (vs bits/sec), but that wasn't an argument.
Either way, I don't expect you to change these values every day. 

These limits are supposed to be rather approximate, since the runtime is determined by the tvdb series level metadata. The real file runtime isn't known yet when Sonarr decides what releases to grab.

**Comment by mistergoodwin** [comment]
Fair enough if that's how the db is written.
I was going was more going for it to be hidden in advanced settings.
An yes I agree it's a once off setup with a little tweaking on the odd occasion if releases are missed.

Cheers for the answers, i'll stick to my conversions and will get v3.
