### ISSUE TITLE
SDR and/or HDR Version as additional profile for automatic upgrading the SDR to HDR Chain 

### ISSUE THREAD

**Issue by nismanoku** [Sonarr/Sonarr#3477]
**Describe the problem**
If i download a episode in SDR 2160P Remux and my quality profile for the tv-show is set at 2160P Remux with score in release profiles for HDR but that episode is not available at the moment in HDR it downloads the SDR version. Sonarr sees 2160P Remux so the episode is fulfilled, but then a HDR version comes out say two weeks later (or whatever time) sonarr does not upgrade to HDR version (RSS). Or am i wrong in this and is the release profile score of the current episode compared to that of any possible upgrades besides the quality profile.

**Describe any solutions you think might work**
Implement a hdr profile like that of the language profile. Would be nice to specify the kind of hdr version also as HDR10, HDR10+ or Dolby Vision as hdr profile to be fulfilled. May be an relative easy sollution as most of the language profile code can be used i guess or not. If not tell me, i smack myself behind the head. ;). 

**Additional context**
Would be a great addition as HDR is becoming a standard nowadays and i personally think a real benefit to movies and tv-shows as the visuals become more beatifull. I already saw some threads about it that where closed but they where more about hdr as a naming tag.

And man keeps getting harder and harder to come up with improvements for sonarr, truly a peace of great software (art).

**Comment by markus101** [comment]
This is supported via preferred words, we do not have plans to support a separate feature for HDR.

**Comment by nismanoku** [comment]
Does it also auto update from sdr to hdr version if the preferred score is higher for the hdr version over the sdr version with preferred words.

**Comment by markus101** [comment]
Yes, it does.
