### ISSUE TITLE
sonarr remaps files to wrong episode

### ISSUE THREAD

**Issue by miracle152004** [Sonarr/Sonarr#3478]
**Describe the bug**
Sonarr keeps remapping files to the wrong episode.
Sometimes Sonarr maps an already existing file to another episode after an automatic scan.
i.e. since today Sword Art Online moved up every episode of season three by one (resulting in episode 1 is now episode 2, episode 1 is missing), removed Season 4 episode 1 and 6 completly from the mapping and moved down Episode 7-11 by one.
A rescan of the folder does not change the mappings even though the files were not changed from the naming sonarr gives them after downloading.
Could you please take a look.
Thanks.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10463692/71548021-27f78980-29a8-11ea-9b7b-543efb59767a.png)

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: Ubuntu 18.04
 - mono 6.6.0.161

**Additional context**

**Comment by markus101** [comment]
Please use the forums or subreddit for support.

Sonarr tracks anime by absolute episode numbers, which means what was season 4 episode 11 and what is now season 4 episode 10 have the same absolute episode number so the files stayed linked.

If the episodes are actually linked to the wrong episodes now you’ll need to either remove the series and re add it or move the files, refresh/rescan there series in Sonarr, move the files back and refresh/rescan.

If the file naming is wrong now just rename them with Sonarr.
