### ISSUE TITLE
Incorrect series duration (due to specials?)

### ISSUE THREAD

**Issue by dbr** [Sonarr/Sonarr#3479]
**Describe the bug**
With the series "The Grand Tour (2016)", the episode summary lists it as "1 minutes" long. The actual episodes are all around 1 hour.

This causes all releases for any episode to be rejected due with messages like "1.2 GB is larger than maximum allowed 200.0 MB (for 1min) "

I guess this is cause by a majority of the episodes listed being "1 minutes (23 episodes)", https://www.thetvdb.com/series/the-grand-tour-2016

**Screenshots**
![](https://user-images.githubusercontent.com/509/71551125-2624d900-2a2f-11ea-9ba6-504bb213e953.png)

**Logs**
N/a

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: Linux (linuxserver/sonarr docker image)
 - .net Framework (Windows) or mono (macOS/Linux) Version: Whatever linuxserver/sonarr Docker image uses

**UI Bugs:**
N/a

**Additional context**
N/a

**Comment by markus101** [comment]
This is a problem with TheTVDB, not sure if an issue has been posted in their forums.
