### ISSUE TITLE
GUI hangs when running any task

### ISSUE THREAD

**Issue by Namaneo** [Sonarr/Sonarr#3480]
**Describe the bug**
Any task ran from the GUI hangs until I reload the whole page. Task execution is always listed and successful in the System > Tasks, but it seems that the interface is never aware of its end.  For instance, this apply:
* when clicking the Refresh button in the Activity view.
* when renaming episodes from the Mass Editor view.
* when clicking Refresh & Scan from any media view.

**Logs**
As far as I searched, nothing relevant, no error. Maybe I missed some part, but everything seems to be OK. Browser console is empty as well (only SignalR connection status is printed).

**System Information**

 - Sonarr Version: 3.0.3.671
 - Operating System: Docker version 19.03.5, build 633a0ea
 - Mono Version: 5.20.1.34

**UI Bugs:**
 - OS: Windows 10
 - Browser: Firefox (happens on Chrome as well)
 - Version: 71.0

**Comment by Qstick** [comment]
Fyi, https://github.com/Radarr/Radarr/pull/3982
