### ISSUE TITLE
Episode naming not working

### ISSUE THREAD

**Issue by modparts** [Sonarr/Sonarr#3481]
**Describe the bug**
I did a fresh install of docker linuxserver/sonarr:preview (3.0.3.677 - 29 Dec 2019) I did not change any settings yet.
When i go to Settings -> Media Management I get the following error (see screenshot 1),
I then changed all of the Media Management settings to the settings of my working Sonarr (version 3.0.3.66818 - 18 Dec 2019) (see screenshot 2) instance from another location, but keep getting the same error (see screenshot 3).

**Screenshots**
**New docker Install (3.0.3.677 - 29 Dec 2019) original settings**
![image](https://user-images.githubusercontent.com/58278486/71568453-b44c9e00-2ac7-11ea-90be-2b6cc42dd2a4.png)

**Docker Install Working (version 3.0.3.66818 - 18 Dec 2019)**
![image](https://user-images.githubusercontent.com/58278486/71568562-99c6f480-2ac8-11ea-8d9c-4beb744eafa9.png)

**New docker Install (3.0.3.677 - 29 Dec 2019) copyed settings**
![image](https://user-images.githubusercontent.com/58278486/71568649-4012fa00-2ac9-11ea-9904-037d8f6c7ee9.png)

**Logs**
http://file.modparts.be/sonarr.debug.txt
http://file.modparts.be/sonarr.txt

**System Information**

 - Sonarr Version: 3.0.3.677
 - Operating System: Synology DSM 6.2.2-24922 Update 4/Docker
 - Docker Container: linuxserver/sonarr:preview   
 - Mono Version 5.20.1.34

**Comment by Taloth** [comment]
Tnx! should be fixed in the next release.
