### ISSUE TITLE
Runtime per episode instead of Series

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#3482]
add episode runtime as table options to expose that info on the season table for the series. since its been an ongoing issue of episodes with 0 min runtime. dont think it needs to be added as a default for people, but the option to toggle it on would be nice

**Comment by markus101** [comment]
Until Sonarr actually has the runtime at the episode level this is of no use, runtime is a series level value in Sonarr until Skyhook uses a newer TVDB API and passes that to Sonarr.

**Comment by Taloth** [comment]
It's actually not on the tvdb api at all, they haven't added any of the new tvdb features to their api yet.

**Comment by thezoggy** [comment]
until that happens, is there a way to prevent sonarr from breaking on the 0 min runtime problem then ?

**Comment by Taloth** [comment]
Sonarr gets one series level runtime which is sometimes 1min, but I haven't seen 0min.

**Comment by markus101** [comment]
1 min seems to because they use the lowest runtime (including specials) for their series runtime. There aren't any series with it explicitly set to 0, but it will be zero if it's not returned at all.

**Comment by thezoggy** [comment]
gotcha, i've seen this a few times recently: `Series runtime is 0, unable to validate size until it is available`

**Comment by keithah** [comment]
Yeah I'm having this problem right now, on Snowpiercer S01E02, not sure if I manually grabbed the E01..

**Comment by Schmill** [comment]
Not sure if this is still a problem - but it seems to be.
From what I can tell the Series "episode runtime" is comprised from averaging all of the episodes in a season to give an "average season episode runtime", then taking each of those and averaging them again across the whole series to get an "average series episode runtime".
However this breaks badly for series' where occasional episodes are outside of the norm (I actually had the issue as described in #5072 ).
The TVDB webpage has the correct runtime for each episode, and PLEX gets the correct runtime for each episode, but Sonarr is assuming the 52 minute average and rejecting releases based on it. Does Plex use some other API to get the episode runtime, and if so what would stop Sonarr using the same one?

**Comment by thezoggy** [comment]
sonarr uses tvdb and gets runtime from series level, and currently uses tvdb v3 api. when tvdb v4 goes live and sonarr switches to it, then they can do per episode runtime.
plex gets data from tvdb/imdb/etc places an aggregates it together.

**Comment by Schmill** [comment]
> sonarr uses tvdb and gets runtime from series level, and currently uses tvdb v3 api. when tvdb v4 goes live and sonarr switches to it, then they can do per episode runtime. plex gets data from tvdb/imdb/etc places an aggregates it together.

How you have explained what it does _currently_ is what I'd read elsewhere, but I think it must have changed to what I described above.
Using Stranger Things - series 4 as an example, and episode 9 within that season.
When trying to download the episode was automatically rejected with: "7.5 GB is larger than maximum allowed 6.5 GB (for 52min)" (the _real_ episode length is 150 minutes according to TVDB (https://thetvdb.com/series/stranger-things/seasons/official/4)

The table below lists the runtime (in minutes) for all episodes of all seasons currently on TVDB.
The only way I get to the "magic 52" is by averaging all episodes in a season, then rounding down to the nearest whole number, repeat for all seasons, then average all of _those_ averages to get a "series average" and then round that down as well.

This means that _any_ significant variation from a consistent runtime for episodes is likely to trip up the validity check, especially considering that it is including "specials" in this calculation, which (certainly in this case) tend to be significantly shorter than "normal" episodes, and so bring the average runtime down even further.

<html>


  | Specials | S1 | S2 | S3 | S4 |   |  
-- | -- | -- | -- | -- | -- | -- | --
  | 26 | 49 | 48 | 51 | 78 |   |  
  | 24 | 56 | 56 | 50 | 77 |   |  
  | 25 | 52 | 51 | 50 | 64 |   |  
  | 17 | 51 | 46 | 53 | 79 |   |  
  | 18 | 53 | 58 | 52 | 76 |   |  
  | 15 | 47 | 52 | 60 | 75 |   |  
  | 23 | 42 | 46 | 55 | 98 |   |  
  |   | 55 | 48 | 78 | 85 |   |  
  |   |   | 62 |   | 150 |   | **Avg:**
**Avg.** | 21.14 | 50.63 | 51.89 | 56.13 | 86.89 |   | 53.33413
**Rnd Avg.** | 21 | 50 | 51 | 56 | 86 |   | **52**
</body>

</html>

**Comment by thezoggy** [comment]
stranger things
tvdbid: 305288

https://skyhook.sonarr.tv/v1/tvdb/shows/en/305288
runtime is 52

skyhook is sonarr proxy that pulls data down from tvdb and caches it for all of sonarr users. now sonarr may have pulled down the value awhile ago and then the site may have been updated since. also tvdb has dfiferent apis and what is stored in the db and whats displayed on the site is not the same as whats served up to the api. as skyhook is closed source, sonarr devs will have to answer how/where the time is coming from if its not from tvdb directly (back in the day it used to just be series runtime, if that was empty it would fall back to first ep added's runtime, so usually s01e01)

**Comment by Schmill** [comment]
Thanks for that, 

> stranger things tvdbid: 305288
> 
> https://skyhook.sonarr.tv/v1/tvdb/shows/en/305288 runtime is 52
> 
> skyhook is sonarr proxy that pulls data down from tvdb and caches it for all of sonarr users. now sonarr may have pulled down the value awhile ago and then the site may have been updated since. also tvdb has dfiferent apis and what is stored in the db and whats displayed on the site is not the same as whats served up to the api. as skyhook is closed source, sonarr devs will have to answer how/where the time is coming from if its not from tvdb directly (back in the day it used to just be series runtime, if that was empty it would fall back to first ep added's runtime, so usually s01e01)

Thanks for that, so I guess we have to just sit and wait for either TVDB API or skyhook to update (depending where the issue is) for problems like this.

> and to note, sonarr has built in logic to allow for double runtime of the first/last episodes to handle double ep scenarios.

That doesn't seem to have worked in this case, episode 9 is the last episode in the series, and yet still failed with a "52" minute message, or perhaps it did double it and tested for a 104 minute episode (but since the episode is a relatively massive 150 minutes it would still be short), but then in the error message only displayed the original "52" value. 
Either way, it didn't work and all we can do at this point is guess and wait :)

**Comment by thezoggy** [comment]
stranger things s4 part 2 is a odd bird where the last episode is 2+ hours (slightly more than double a normal episode).   So if you have really tight quality profile you would run up against a possible size issue. But easy fix is just bump the profile up slightly or just manually grab if you really dont want to do that. 

I personally didn't have sonarr run into any issues myself, or anyone else in discord when the series came out: 
![firefox_2022-09-01_11-15-49](https://user-images.githubusercontent.com/500882/187962998-79bc0d94-f161-4647-973a-ba1b84fd873f.png)

So it just sounds like you have some restrictive quality profile settings?

**Comment by Schmill** [comment]
Not particularly restrictive, I'm running with the defaults. I've updated it manually now, but you can see the top error here:

![image](https://user-images.githubusercontent.com/51209741/188001514-17d120e6-7865-431a-9987-f595b5dbcff2.png)

So WEB, h264, 7.6GB

Default settings are as:

![image](https://user-images.githubusercontent.com/51209741/188002011-ef487396-511b-474b-a801-86a8bc48cda6.png)

Although, looking at your screenshot you have the upper limits _much_ in excess of the defaults.
The default has a max of 130 MB / min, which based on its assumption of a 52 minute episode would give ~6.7 GB (which is arguably close enough to the 6.6GB the error message is showing.
If it was able to use the correct runtime of 150 minutes, then that would allow files of up to ~19GB - which would obviously be more than enough 😃 

So it looks like effectively you've increased your upper limits to compensate for the episode lengths not being available properly.
At least we know now why it worked for you, but stumbled for me. 

As I say, I've downloaded manually for now, but hopefully the relevant APIs get fixed up soon 👍

**Comment by thezoggy** [comment]
yes, most people need to change the defaults to what works for them. depending on the codec used, or if hd audio, or whatever is included you can see widely different sizes. so again your quality profiles are just outdated and need to be tweaked to cater towards what you want. sensible defaults for x264 varies a bit because some people want dual audio.. some people want low quality bitrate stuff. some people want hd audio... etc. hard to cater for everyone. 

several people just use trash guides -- https://trash-guides.info/Sonarr/Sonarr-Quality-Settings-File-Size/
