### ISSUE TITLE
Series Notes

### ISSUE THREAD

**Issue by wdaniel526** [Sonarr/Sonarr#3483]
I think there should be an option to take notes under a series in Sonarr. Doing this will make it easier to keep track of the current status on certain episodes for the series.

This can be used for re-encoding. Say I throw a few episodes in to handbrake and put them back in to Sonarr after, but it's an ongoing series so I don't know which ones have been re-encoded when I come back to it later. This way I can take notes on what episodes have been re-encoded.

This can also be useful for labeling stuff that needs to be fixed so if an anime has missing subtitles I can write it in the notes to go back later and fix it.

This would make managing a big library easier.

**Comment by markus101** [comment]
This isn't something we plan to support, at least at this time.
