### ISSUE TITLE
Importing a folder with a series name should interpret contained files as episodes of the same show

### ISSUE THREAD

**Issue by pathsny** [Sonarr/Sonarr#3485]
**Describe the bug**
A lot of anime batch torrents are named in this manner. 
Directory name:   Mob Psycho 100 
 Files:
     001 - Self-Proclaimed Psychic, Reigen Arataka (And Mob).ass
     001 - Self-Proclaimed Psychic, Reigen Arataka (And Mob).mkv
     002 - Doubts About Youth.ass
     002 - Doubts About Youth.mkv

Sonarr does not recognise anything in these cases. If I was to rename the folder as 
[DmonHiro] That Time I Got Reincarnated As A Slime - S01 (Bluray)
each file is treated as a multi-episode file containing all episodes.
**Screenshots**
<img width="1080" alt="Screen Shot 2020-01-04 at 1 27 11 AM" src="https://user-images.githubusercontent.com/126134/71770213-f2d6c400-2ede-11ea-91da-38afab68867c.png">

**Logs**
https://hastebin.com/girecuzelo.cs

**System Information**

 - Sonarr Version: 3.0.3.679
 - Operating System: 11.2-RELEASE-p9
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]:  5.10.1.57

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
> This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

Your logs don't exist.

> Importing a folder with a series name should interpret contained files as episodes of the same show

This is already assumed. Absolute episode number parsing is intentionally limited (a 2-3 digit number without any indication of what it is, is far too easily confused with something else).

**Comment by pathsny** [comment]
Thanks I've updated the logs so they should be visible. Is there some way to allow for this more dangerous parsing since thats the norm in the anime batch world? Skipping the series name in the files is very common.

**Comment by markus101** [comment]
In this case it's not possible until Sonarr can handle parsing things differently based on the series type, which falls under https://github.com/Sonarr/Sonarr/issues/457

With this file name, even if the series title was part of the file name Sonarr wouldn't be able to parse it properly.
