### ISSUE TITLE
SharpRaven error at Startup

### ISSUE THREAD

**Issue by mabek** [Sonarr/Sonarr#3493]
The intial Sonarr 3 version was running fine (Version3.0.2.529).
After installing the internal updates I get this error on startup:

/usr/bin/mono /usr/lib/sonarr/bin/Sonarr.exe -nobrowser 
NLog Exception: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.Instrumentation.Sentry.SentryTarget:_client' (0) due to: Could not load file or assembly 'SharpRaven, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at NzbDrone.Common.Instrumentation.NzbDroneLogger.Register (NzbDrone.Common.EnvironmentInfo.IStartupContext startupContext, System.Boolean updateApp, System.Boolean inConsole) [0x00030] in <d8de95dc251a4630b30db207932aeecd>:0
  at NzbDrone.Console.ConsoleApp.Main (System.String[] args) [0x00007] in <4090d06e88f24ca8859abaad9ee88782>:0

## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Sonarr Version:** 3 ?? after update

**Operating System:**  Ubuntu Linux 18.04.3

**.net Framework (Windows) or mono (macOS/Linux) Version:** Mono JIT compiler version 6.6.0.161 (tarball Tue Dec 10 10:36:32 UTC 2019)

**Comment by markus101** [comment]
> Could not load file or assembly 'SharpRaven

Make sure that file is included with the Sonarr executable.

If you're still having issues, try reinstalling and open a thread on the forums for support.
