### ISSUE TITLE
View other shows by Network

### ISSUE THREAD

**Issue by dannyvfilms** [Sonarr/Sonarr#3498]
Sonarr does not have a method to search by Network (A&E, Food Network, HBO). The Network of a show is listed in search results or on a show's page, it can't be clicked to see more shows from that Network (i.e. Trakt). 

I know search is powered by TVDB, so I looked and pages like this do exist. 

https://www.thetvdb.com/networks/Food+Network

Being able to search by Network, or being able to click on the Network of a show to see more listings would be a useful way to explore and add more content until (hopefully) List support is added and I can do the same thing via a Trakt list.

**Comment by markus101** [comment]
Unless The TVDB has an API endpoint for the same thing them having a page on their site for it doesn't help Sonarr.

At this time we don't have plans to enable searching for new series by network, especially as an interim solution before lists. Discovery is something we'd like to evaluate at some point, but it's not a short term goal.
