### ISSUE TITLE
Stuck Importing done episodes

### ISSUE THREAD

**Issue by ZerithZA** [Sonarr/Sonarr#3501]
**Describe the bug**
Sonarr is showing the downloads as 100% completed and busy being imported but it stays stuck in this state with no errors and no movement. It seems that it happens when it can't find the path for the download but does not show error in the UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/10301711/72050006-cc42cf80-32c8-11ea-9818-e7a50b6db9eb.png)
![image](https://user-images.githubusercontent.com/10301711/72050055-e5e41700-32c8-11ea-900c-cd5e4020fb93.png)

**Logs**
System.IO.DirectoryNotFoundException: Could not find a part of the path '/mnt/unionfs/sabnzbd/tv/Vikings S06E06 720p WEB H264-GHOSTS'.

**System Information**

 - Sonarr Version: 3.0.3.687
 - Operating System:  Ubuntu 16.04.6 LTS Linux 4.15.0-74-generic
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34

**UI Bugs:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79.0.3945.117 64bit

**Additional context**

**Comment by markus101** [comment]
Please post the full debug log and link it here.

**Comment by ZerithZA** [comment]
queue response body:

{
  "page": 1,
  "pageSize": 20,
  "sortKey": "timeleft",
  "sortDirection": "ascending",
  "totalRecords": 3,
  "records": [
    {
      "seriesId": 285,
      "episodeId": 37813,
      "language": {
        "id": 1,
        "name": "English"
      },
      "quality": {
        "quality": {
          "id": 8,
          "name": "WEBDL-480p",
          "source": "web",
          "resolution": 480
        },
        "revision": {
          "version": 1,
          "real": 0,
          "isRepack": false
        }
      },
      "size": 547805428.0,
      "title": "Vikings S06E06 WEB H264-GHOSTS",
      "sizeleft": 0.0,
      "timeleft": "00:00:00",
      "estimatedCompletionTime": "2020-01-09T11:06:38.131907Z",
      "status": "completed",
      "trackedDownloadStatus": "ok",
      "trackedDownloadState": "importing",
      "statusMessages": [],
      "errorMessage": "",
      "downloadId": "SABnzbd_nzo_TDsvl0",
      "protocol": "usenet",
      "downloadClient": "sabnzbd",
      "indexer": "nzbplanet.net",
      "outputPath": "/mnt/unionfs/sabnzbd/tv/Vikings S06E06 WEB H264-GHOSTS/",
      "id": 624665876
    },
    {
      "seriesId": 285,
      "episodeId": 37813,
      "language": {
        "id": 1,
        "name": "English"
      },
      "quality": {
        "quality": {
          "id": 5,
          "name": "WEBDL-720p",
          "source": "web",
          "resolution": 720
        },
        "revision": {
          "version": 1,
          "real": 0,
          "isRepack": false
        }
      },
      "size": 1159734895.0,
      "title": "Vikings S06E06 720p WEB H264-GHOSTS",
      "sizeleft": 0.0,
      "timeleft": "00:00:00",
      "estimatedCompletionTime": "2020-01-09T11:06:38.131916Z",
      "status": "completed",
      "trackedDownloadStatus": "ok",
      "trackedDownloadState": "importing",
      "statusMessages": [],
      "errorMessage": "",
      "downloadId": "SABnzbd_nzo_T612VB",
      "protocol": "usenet",
      "downloadClient": "sabnzbd",
      "indexer": "nzbplanet.net",
      "outputPath": "/mnt/unionfs/sabnzbd/tv/Vikings S06E06 720p WEB H264-GHOSTS/",
      "id": 1443169317
    },
    {
      "seriesId": 243,
      "episodeId": 37760,
      "language": {
        "id": 1,
        "name": "English"
      },
      "quality": {
        "quality": {
          "id": 4,
          "name": "HDTV-720p",
          "source": "television",
          "resolution": 720
        },
        "revision": {
          "version": 1,
          "real": 0,
          "isRepack": false
        }
      },
      "size": 179956539.0,
      "title": "The Daily Show 2020 01 08 Mo Rocca 720p HEVC x265-MeGusta",
      "sizeleft": 0.0,
      "timeleft": "00:00:00",
      "estimatedCompletionTime": "2020-01-09T11:06:38.131924Z",
      "status": "completed",
      "trackedDownloadStatus": "ok",
      "trackedDownloadState": "importing",
      "statusMessages": [],
      "errorMessage": "",
      "downloadId": "SABnzbd_nzo_DuBwyG",
      "protocol": "usenet",
      "downloadClient": "sabnzbd",
      "indexer": "nzbplanet.net",
      "outputPath": "/mnt/unionfs/sabnzbd/tv/The Daily Show 2020 01 08 Mo Rocca 720p HEVC x265-MeGusta/",
      "id": 1947562253
    }
  ]
}

**Comment by ZerithZA** [comment]
Logfile can be located at: [https://controlc.com/e3f77437](url)

**Comment by markus101** [comment]
> 20-1-9 06:42:17.2|Error|CommandExecutor|Error occurred while executing task ProcessMonitoredDownloads
> [v3.0.3.687] System.IO.DirectoryNotFoundException: Could not find a part of the path '/mnt/unionfs/sabnzbd/tv/The Daily Show 2020 01 08 Mo Rocca 720p HEVC x265-MeGusta'.

Instead of this task failing it should be caught and update the underlying tracked item, definitely a bug with the recent changes that were made.
