### ISSUE TITLE
Error importing folder with multiple episode in it

### ISSUE THREAD

**Issue by ziolupo68** [Sonarr/Sonarr#3502]
A lot of time there are two episodes in one folder. The folder name ha the following structure: SeriesNameS01E01-02-[quality|releaser|codec...]
Inside the folder there are two files with the following name schema:
SeriesNameS01E01-[quality|releaser|codec...].mkv
SeriesNameS01E02-[quality|releaser|codec...].mkv

In this case only one file is copied/imported and is named as the folder but with the extension of files:
SeriesNameS01E01-02-[quality|releaser|codec...].mkv

Of course it should copy/import both files keeping the original names.

![Asset 1](https://user-images.githubusercontent.com/50259612/72056819-9c49fb00-32cd-11ea-85f6-e2e66d235be4.png)

 - Sonarr Version: 3.0.3.687
 - Operating System:  Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Comment by markus101** [comment]
We absolutely need debug logs of such an import to investigate this.

**Comment by markus101** [comment]
Closing as we need more information and it has not been provided.

**Comment by ziolupo68** [comment]
Is it possible to reopen it?
I was out for business and couldn't check.
Attached you will get the log (same issue different series)
[
[seal.txt](https://github.com/Sonarr/Sonarr/files/4109567/seal.txt)
](url)

**Comment by markus101** [comment]
We can, but we do need debug logs, not info level logs.

My best guess for what's happening is there is only one video file when Sonarr attempts to process it, which results in the folder name being used, if both files existed it'd use the file names.

This can happen if you're unraring content after the download is marked complete or syncing files from a remote destination.

Debug logs will give us the information we need to troubleshoot this further.
