### ISSUE TITLE
The TVDB Api Update - Sonarr can't find TV Show

### ISSUE THREAD

**Issue by andrewflierman** [Sonarr/Sonarr#3507]
Trying to add the serie Succession it cannot find the TV show, while it is available in thetvdb.com. Also looking on the tvdbId it cannot find anything. 

I came across this: https://forums.thetvdb.com/viewtopic.php?f=3&t=61687 and https://www.reddit.com/r/sonarr/comments/emmlmp/sonarr_cant_find_show_even_though_it_exists_on/

**Comment by markus101** [comment]
Please look at the existing issues before posting a new one.

This is all covered by https://github.com/Sonarr/Sonarr/issues/3415#issuecomment-573177722 (it’s an ongoing issue, we don’t need multiple new issues for it).
