### ISSUE TITLE
Fails to create directory with special characters in name

### ISSUE THREAD

**Issue by jonathanklingberg** [Sonarr/Sonarr#3509]
If the TV Series name contains special characters such as ':' or '?' then Sonarr won't be able to create the catalogue on some file systems such as exFAT (& FAT32?) (while this is totally fine on NTFS formatted drives).

See example log for "Who is America?":
```
20-1-11 08:23:52.8|Error|EpisodeFileMovingService|Unable to create directory: /nas/TV Shows/Who Is America? (2018)

[v2.0.0.5338] System.IO.FileNotFoundException: Could not find file "/nas/TV Shows/Who Is America? (2018)"
File name: '/nas/TV Shows/Who Is America? (2018)'
  at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x0005e] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at System.IO.Directory.CreateDirectory (System.String path) [0x0008f] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at NzbDrone.Common.Disk.DiskProviderBase.CreateFolder (System.String path) [0x00048] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Disk\DiskProviderBase.cs:180 
  at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.CreateFolder (System.String directoryName) [0x0007a] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:206 
```

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: Ubuntu 18
 - Docker: "linuxserver/sonarr@sha256:449e585fd841820c521ca0ff9d08c7c1ff1d798481fe35c07bbd55f7163522a2" BUILD_DATE=2019-11-28T03:35:39-05:00

**Additional context**
Similar problem described here: https://unix.stackexchange.com/q/299667
Possible solution would be to either escape the special characters, replace them with some other character or simply strip them out completely.

**Comment by markus101** [comment]
Sonarr replaces `?` and other illegal characters when the series is added.

This is from v3, but the same logic exists in v2:
![image](https://user-images.githubusercontent.com/413544/72200517-3b224480-33ff-11ea-8672-b0d4e80bbc97.png)

If the series path was edited after the series was added it'd attempt to create the folder, but it would fail as you're seeing. Edit the series and either remove the `?` or change it to `!` (like Sonarr does when replacing them).

**Comment by jonathanklingberg** [comment]
Got it to work now, replaces '?' with '!' just as in your example!
The problem most likely related to me moving the library from NTFS to exFAT and something went wrong in the migration.
Thanks for the quick reply anyways!
