### ISSUE TITLE
Remove seeding torrents

### ISSUE THREAD

**Issue by Titanicoso** [Sonarr/Sonarr#3510]
**Problem description**
There is a grey are where people do want to remove their torrents when finished (even though they are seeding) but they dont want to limit their other seeding torrents.

**Possible solution**
I think of one solution where people who do want to seed and people who dont can live in harmony. Basically adding another value to the configuration stating that you dont want to seed and then checking it when asking if the torrent can be removed would work. Its a simple solution and really easy to implement.

**Comment by markus101** [comment]
There is already a per indexer seeding limit which when used with supported clients will set the torrent seeding limit on the client and allow Sonarr to remove them when they hit their seeding goal. Setting that to/close to zero will achieve that, we’re not going to add another option to achieve that.
