### ISSUE TITLE
Indexer request Filelist.ro

### ISSUE THREAD

**Issue by mnmll** [Sonarr/Sonarr#3511]
Filelist.ro added an api to the tracker as it was rss only before , is it possible to get them integrated into sonarr? If the devs need invites I can provide them.

This is the news posted about the API:

"Before we go on to the subject from the title which is mainly targeted at developers, we wish to bring to your attention something that impacts all users. A few days ago we made some improvements to how searching torrents works, more exactly:

 Torrents are now indexed in real time. Meaning that you can find it via search right after it's uploaded;
 We made some improvements to the way words are analyzed for indexing. To be more specific the search will now return much more accurate results;
 We have also greatly improved the algorithm which handles word positioning in the search engine, you can now find much shorter words and the relevance of the results is higher;

Let's go on with a short list of 'good-to-know' things for the API:

 You can find the API at: https://filelist.ro/api.php ;
 A 150 requests/hour/user limit is enforced;
 All API calls have to be sent as a GET request;
 The authentication is made using your username and passkey;
 The API can return responses as JSON as well as XML;
 At this moment there are two endpoints: search-torrents and latest-torrents;
 latest-torrents works the same way as the current RSS feed with the added benefit of being able to filter by IMDb;"

For more info visit: https://filelist.ro/forums.php?action=viewtopic&topicid=120435&page=last

*FIleList staff offers a bounty for who manages to do this: permanent VIP and Special Rank Status.

**Comment by who-knows** [comment]
I would say don't bother. Simply use an app like Jacket to configure an indexer for any torrent site you like :)
https://github.com/Jackett/Jackett

**Comment by Taloth** [comment]
@mnmlsv Does the indexer actually index the season and episode numbers as well?
In other words, by which fields can search-torrents be queried?

**Comment by mnmlsv** [comment]
Here is a example if I search for "NCIS New Orleans S05 E22" using the API:


[{"id":628224,"name":"NCIS.New.Orleans.S05E22.720p.HDTV.x264-LucidTV","imdb":"tt3560084","freeleech":0,"upload_date":"2019-05-01 07:08:41","download_link":"https:\/\/filelist.ro\/download.php?id=628224&passkey=xxxxxxxxx","size":1179164807,"internal":0,"moderated":1,"category":"Seriale HD","seeders":2,"leechers":0,"times_completed":93,"comments":0,"files":3,"small_description":"Drama"},{"id":628223,"name":"NCIS.New.Orleans.S05E22.HDTV.x264-LucidTV","imdb":"tt3560084","freeleech":0,"upload_date":"2019-05-01 07:07:39","download_link":"https:\/\/filelist.ro\/download.php?id=628223&passkey=xxxxxxxxxxx","size":361650355,"internal":0,"moderated":1,"category":"Seriale SD","seeders":15,"leechers":0,"times_completed":365,"comments":0,"files":3,"small_description":"Drama"}]

**Comment by ophishil** [comment]
@Taloth you can now also search as:

https://filelist.ro/api.php?action=search-torrents&type=imdb&query=tt0121955&name=s19e01&passkey=PASSKEY&username=USERNAME
https://filelist.ro/api.php?action=search-torrents&type=imdb&query=tt0121955&name=s19&passkey=PASSKEY&username=USERNAME

**Comment by markus101** [comment]
Searching by ID is a good start, but proper filtering (not name based) by season and episode is a requirement for indexers we add support for.

**Comment by ophishil** [comment]
Would something like: type=imdb&query=tt2193021&season=8&episode=7 be ok? With season and episode being optional. If yes, what other data, if any, do you need returned in the response besides the ones above?

**Comment by ophishil** [comment]
We've added two optional parameters for search-torrents: season and episode. 
Example: &type=imdb&query=tt219302&season=8 / &type=imdb&query=tt219302&season=8&episode=7

We've also added both in the response for TV categories. If it's a season pack, the value of tv['episode'] will be null.

**Comment by matrixn** [comment]
I for one would love see this one integrated into sonar...+1 on this

**Comment by Taloth** [comment]
@mnmlsv My apologies for not responding earlier.

It seems to satisfy all the requirements, those season/episode parameters are helpful, ty.
I'm ok with implementing the api as currently proposed and should be able to do so pretty soon.

However, I have to be bold and point out an alternative (if you're willing to indulge me further): 

Sonarr and Radarr both support a generic api specification called Torznab, it was derived from the [Newznab api specification](https://newznab.readthedocs.io/en/latest/misc/api/) (which is widely used across many usenet indexers).  
Lidarr (I dunno if filelist has music?), Jackett, flexget and some other tools support it as well.

Sonarr uses it primarily to talk to Jackett, but it's also used for some sites that implement it like AnimeTosho.

Torznab is basically an xml rss feed.
For example `site.me/api?t=tvsearch&imdbid=tt12345&season=1` queries all episodes/packs in season 1.
The nice part is that the query parameters are formalized and it has a `/api?t=caps` query that allows indexers to [advertise](https://torznab.github.io/spec-1.3-draft/torznab/Specification-v1.3.html#caps-format) what they support.
Meaning, if you support tvdbid in the future, you can advertise it and Sonarr will query by tvdbid automatically.

Years ago I started working on some documentation that explained everything, so [this](https://torznab.github.io/spec-1.3-draft) is actually a draft. But it should give you an idea of how it works. There's also an example response [here](https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core.Test/Files/Indexers/Torznab/torznab_hdaccess_net.xml).

Do you think torznab would be something useful to you? It would help unify the landscape a bit and gets you support with any tool also using torznab.
No hard feelings if you say no, I'll go for the json api then. Just say the word.

**Comment by ophishil** [comment]
@Taloth at this moment we'd rather not implement torznab. Maybe we'll consider it in the future, for a v2 or simply as an extension to v1, but that won't be in the near future so you can go ahead with the json api. 
If you need an invite you can go ahead and message either me or @mnmlsv.

Thanks a lot!

**Comment by samip5** [comment]
@ophishil & @mnmlsv So this should be implemented directly in Sonarr and not Jackett?

**Comment by Taloth** [comment]
I'm working on it, just the tvdb issues took precedence. And I need a new UI component so it takes a bit of time.

**Comment by Taloth** [comment]
btw. I'm ok if you want to take over, I can dump what I have on a branch. You'll need an account on filelist.ro coz I haven't yet reached that part.

**Comment by samip5** [comment]
You can continue working on that as you have already started doing it. 
I'm figuring out the hard coded branded notifications, as I want them to be customize-able which they are not currently.

**Comment by markus101** [comment]
Closed via https://github.com/Sonarr/Sonarr/commit/20a6284062d19211f981880c106cebc60920b01a
