### ISSUE TITLE
Manual Import - Sequence contains more than one element

### ISSUE THREAD

**Issue by TropperCZ** [Sonarr/Sonarr#3512]
**Describe the bug**
when manual import it end with error "Sequence contains more than one element"

**Screenshots**
<img width="816" alt="Capture" src="https://user-images.githubusercontent.com/48273838/72264051-54530d00-361a-11ea-8a23-da1bf9395a9d.PNG">

**Logs**
log: https://controlc.com/5a53067a
Debug log: https://controlc.com/70745993

**System Information**
Version 3.0.3.688
Package Version 3.0.3.688-ls167 by linuxserver.io
Mono Version  5.20.1.34

**Comment by markus101** [comment]
Looks like multiple series match with `The Team`, potentially a duplicate that was deleted. We can guard against the error in the dialog though.

**Comment by TropperCZ** [comment]
make sense i have series "A-Team, The (1983)" and Team, The (2015). Sonarr wrongly match second one for first. And i already have it so i add it but now cant manualy import.
