### ISSUE TITLE
Stuck at downloading

### ISSUE THREAD

**Issue by vogstar** [Sonarr/Sonarr#3516]
When Sonarr grabs the torrent file from the indexer it gets sent to the download client and it downloads, but then it just stays there and doesn't sort it and notify tyhat the unit was grabed and sorted.

This just started to happen as of Jan 10 2020

**Screenshots**
![image](https://user-images.githubusercontent.com/37817674/72352998-48fef080-36b1-11ea-998a-df99b1233b51.png)

![image](https://user-images.githubusercontent.com/37817674/72353009-4e5c3b00-36b1-11ea-8a0b-91590ea0427d.png)

**Logs**
Link to debug or trace log files.

**System Information**

 Version
2.0.0.5338
Mono Version
5.0.1.1
AppData directory
/home/user/.config/NzbDrone
Startup directory
/opt/NzbDrone

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
Please use the forums or subreddit for support. You’ll need to provide debug logs and look at activity queue (hover over the icons on the left) to see why it’s not importing.
