### ISSUE TITLE
Download quality and automation

### ISSUE THREAD

**Issue by 5abred** [Sonarr/Sonarr#3517]
i have 2 questions:
1- can i set Sonarr to download the latest episodes only not past episodes also on either the beta or regular version?
2-How can i stop episode re-download when changing location even if the Ignore deleted is set ON?

**Comment by markus101** [comment]
1. Set it to monitor future when you add the series or use season pass to update it after
2. That setting only applies when Sonarr detects the file was deleted, if you enabled it after the Sonarr detected the file was deleted (you moved it) then it will redownload.

If you have more questions please open a thread on the forums, this is not the place for support/questions.
