### ISSUE TITLE
Unable to access Sonarr Front End Ui due un-representable DateTime

### ISSUE THREAD

**Issue by jdsarge** [Sonarr/Sonarr#3518]
**Describe the bug**
While accessing the UI, the following error appears. 

Year, Month, and Day parameters describe an un-representable DateTime.
Version 3.0.3.688

Full traceback of that error is here:
https://pastebin.com/U84kywmc

Front end UI becomes unusable, Sonarr continues to function as normal on the backend (find shows, process shows, etc.) 

**Screenshots**

https://imgur.com/Cy2O3sO

**Logs**

https://pastebin.com/U84kywmc

**System Information**

 - Sonarr Version: Version 3.0.3.688
 - Operating System: Ubuntu 16.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
 - OS: Ubuntu 16.04
 - Browser: All browsers
 - Version: 3.0.3.688

**Additional context**
I've restored from multiple backups and the issue persists. From the code it seems that the Series Table in the sonarr.db needs to include a table named "PreviousAiring" which didn't exist in my db. I added that table manually with the exact same components as "NextAiring" Restoring that backup did not work either.

**Comment by Taloth** [comment]
>  that the Series Table in the sonarr.db needs to include a table named "PreviousAiring" which didn't exist in my db

Euhhh... No, it really doesn't. There's not supposed to be any such table or column.

What version of mono are you running? Coz it's definitely a bug in mono.

**Comment by jdsarge** [comment]
mono --version
Mono JIT compiler version 6.6.0.161 (tarball Tue Dec 10 10:36:47 UTC 2019

Will try downgrading and report back.

**Comment by Taloth** [comment]
Well, at least not like mono 4.8 or something :smile:

**Comment by jdsarge** [comment]
changing my mono-official-stable to deb https://download.mono-project.com/repo/ubuntu stable-xenial/snapshots/5.20.0 main

Fails out. I'll keep digging.

**Comment by Taloth** [comment]
Depending on how you installed mono first, you need to uninstall mono-complete and sonarr. And then autoremove the no longer needed mono packages.

Downgrading is tricky.

Removing sonarr won't delete the settings and db. so it's ok.

**Comment by Taloth** [comment]
It's probably the airdate of a single episode somewhere. But we're telling mono to _try_ parse the date+time. DateTime.TryParse in the stacktrace, which returns false if it fails, it shouldn't crash... ever.

But it might very well also exist in 5.20.

What you could do is query the sqlite database Episodes table to look for any weird Airdate, if any exist, post them and I'll check em out.

**Comment by jdsarge** [comment]
Best way to send that table to you?

**Comment by jdsarge** [comment]
Holy shit 5.2.0 fixed it!

**Comment by fryfrog** [comment]
*5.20.0 hopefully? :)

**Comment by jdsarge** [comment]
It was actually labeled  as this `deb https://download.mono-project.com/repo/ubuntu stable-xenial/snapshots/5.2.0 main`

 for my particular distribution.

**Comment by fryfrog** [comment]
That *might* be okay, or you might run into issues. I think modern Sonarr/Radarr/Lidarr want 5.8 minimum, 5.20 is better. Not 5.2.

**Comment by Taloth** [comment]
Reminder to self: I tested this with the db on many mono versions, but couldn't reproduce it. locale+timezone unlikely to be the issue but that has to be tested.

**Comment by ta264** [comment]
https://github.com/mono/mono/issues/16742 could it be that one?

**Comment by Taloth** [comment]
I'd say yes, but I tested every date in his database, against a dozen mono versions, in his timezone and language... no failures whatsoever.
