### ISSUE TITLE
Telegram unable to send test message

### ISSUE THREAD

**Issue by pshurgal** [Sonarr/Sonarr#3521]
**Describe the bug**
I am trying to enable Telegram integration at my server, but it doesn't work.
I have correct bot id and chat id, I can send message to the chat by entering request URL at my browser (with proxy enabled), but when I try enable Telegram integration I always get error message.

Telegram is blocked in Russian Federation, but it works using proxy server. I have tried to enable proxy at general setting but it seems that TelegramProxy doesn't use global proxy settings.

**Logs**
 > 20-1-15 17:37:26.0|Error|RestSharpExtensions|Error communicating with server
 > 
 > [v3.0.3.688] System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
 >   at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at System.Net.Sockets.SocketTaskExtensions+<>c.<ConnectAsync>b__2_1 (System.IAsyncResult asyncResult) [0x00006] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
 > --- End of stack trace from previous location where exception was thrown ---
 > 
 >   at System.Net.WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x0019b] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >    --- End of inner exception stack trace ---
 >   at System.Net.WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x00217] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x000cc] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at System.Net.WebOperation.Run () [0x0009a] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x00094] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at System.Net.HttpWebRequest.GetRequestStream () [0x00016] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at RestSharp.Http.WriteRequestBody (System.Net.HttpWebRequest webRequest) [0x00024] in <d763243987454e81b285f1d75ecfc7f5>:0 
 >   at RestSharp.Http.PostPutInternal (System.String method) [0x00015] in <d763243987454e81b285f1d75ecfc7f5>:0 
 >   at RestSharp.Http.AsPost (System.String httpMethod) [0x00007] in <d763243987454e81b285f1d75ecfc7f5>:0 
 >   at RestSharp.RestClient.DoExecuteAsPost (RestSharp.IHttp http, System.String method) [0x00000] in <d763243987454e81b285f1d75ecfc7f5>:0 
 >   at RestSharp.RestClient.Execute (RestSharp.IRestRequest request, System.String httpMethod, System.Func`3[T1,T2,TResult] getResponse) [0x00016] in <d763243987454e81b285f1d75ecfc7f5>:0 
 > 
 > 20-1-15 17:37:26.0|Error|TelegramProxy|Unable to send test message
 > 
 > [v3.0.3.688] System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
 >   at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at System.Net.Sockets.SocketTaskExtensions+<>c.<ConnectAsync>b__2_1 (System.IAsyncResult asyncResult) [0x00006] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
 > --- End of stack trace from previous location where exception was thrown ---
 > 
 >   at System.Net.WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x0019b] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >    --- End of inner exception stack trace ---
 >   at System.Net.WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x00217] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x000cc] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at System.Net.WebOperation.Run () [0x0009a] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x00094] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
 >   at NzbDrone.Core.Rest.RestSharpExtensions.ValidateResponse (RestSharp.IRestResponse response, RestSharp.IRestClient restClient) [0x001f7] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Rest\RestSharpExtensions.cs:52 
 >   at NzbDrone.Core.Rest.RestSharpExtensions.ExecuteAndValidate (RestSharp.IRestClient client, RestSharp.IRestRequest request) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Rest\RestSharpExtensions.cs:76 
 >   at NzbDrone.Core.Notifications.Telegram.TelegramProxy.SendNotification (System.String title, System.String message, NzbDrone.Core.Notifications.Telegram.TelegramSettings settings) [0x00070] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Notifications\Telegram\TelegramService.cs:41 
 >   at NzbDrone.Core.Notifications.Telegram.TelegramProxy.Test (NzbDrone.Core.Notifications.Telegram.TelegramSettings settings) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Notifications\Telegram\TelegramService.cs:51 
 > 
 > 20-1-15 17:37:26.0|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 >  -- BotToken: Unable to send test message

**System Information**
 - Sonarr Version: 3.0.3.688
 - Package Version: 3.0.3.688-ls167 by linuxserver.io
 - Mono Version: 5.20.1.34
 - Operating System: Ubuntu 19.10
 - Docker Version: 19.03.3, build a872fc2f86

**Comment by markus101** [comment]
Telegram and most connections use RestSharp which does not go through the proxy, the only workaround right now would be to use a custom script that does the communication to telegram, instead of Sonarr doing it directly.

**Comment by pshurgal** [comment]
Fixed at https://github.com/Sonarr/Sonarr/pull/3523
