### ISSUE TITLE
Remote download handling with remote paths, estimated time till completed

### ISSUE THREAD

**Issue by samip5** [Sonarr/Sonarr#3524]
**Describe the problem**
Currently there is no way to see what is the current status of a remote download import except that the task for it is running.

This is frustrating specially for a large season pack imports when you don't know it's actual status.

**Describe any solutions you think might work**
I would think that there would be near the task a estimated time, or in the activity page and also have which file/series/season is being currently imported.

**Additional context**
![image](https://user-images.githubusercontent.com/1703002/72613403-1286d700-3938-11ea-8c65-f660decdbb37.png)

**Comment by markus101** [comment]
This falls under the "transfer provider" idea in https://github.com/Sonarr/Sonarr/issues/282
