### ISSUE TITLE
Unable to add new series-Unable to communicate with SkyHook

### ISSUE THREAD

**Issue by aegisnetwork** [Sonarr/Sonarr#3526]
**Description of issue:** Having the same problem as @jackmeat and it all started today when trying to add new TV-shows either by name or by tvdbid.

**From log-file** 20-1-19 12:24:38.2|Warn|HttpClient|HTTP Error - Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=litt: 504.GatewayTimeout
**Version**: 3.0.3.688
**Package Version**: 3.0.2
**Mono Version**: 6.8.0.96
**OS**: Ubuntu 18.04

**Comment by Taloth** [comment]
Yup, tvdb was having issues
