### ISSUE TITLE
Restart or shutdown not working on Synology

### ISSUE THREAD

**Issue by houndtt** [Sonarr/Sonarr#3527]
**Describe the bug**
Of late I noticed that when I attempt to restart or shutdown Sonarr on my Synology NAS the package does not complete the desired action. For shutdowns the package does not actually stop and for restarts the package appears to stop but is unable to start again. In either case, the web interface stops responding as the action does not seem to complete.

**Logs**
Sample trace log file for a restart: https://paste.ubuntu.com/p/yjCDVtdVvQ/.

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: DSM 6.2.2-24922 Update 4
 - mono (macOS/Linux) Version: 5.18.0.240

**Additional context**
For the restart problem cited above the logs (nzbdrone.log - https://paste.ubuntu.com/p/k5kmF8pNTV/) seem to indicate that the original process never stopped. As such to fix the issue temporarily, I had to manually stop the existing process as follows:
```
cd /volume1/@appstore/python/bin
sudo ./start-stop-daemon -K -q -u "sc-nzbdrone"
```

**Comment by markus101** [comment]
Restart/shutdown depend on the service wrapper (systemd, upstart, etc) not restarting when Sonarr shutsdown, which is covered by https://github.com/Sonarr/Sonarr/issues/424 I know some people configured systemd to not restart if the exit code isn't an error, for the same to work on Synology the Synology package would need to be updated to handle that, it's not a package we maintain though.

**Comment by houndtt** [comment]
I was able to solve the issue. There was nothing wrong with Sonarr or the SynoCommunity package. There was however something off in the configuration database. I did a few changes to the 'Media Management' settings for the 'Separator' and 'Numbering Style', saved and then reverted to my original settings. This somehow updated the values and the application was able to reboot properly.
