### ISSUE TITLE
search function different than radarr

### ISSUE THREAD

**Issue by jhorath** [Sonarr/Sonarr#3532]
**Describe the bug**
Not really a bug but an annoyance and operation is different than similary coded sonarr.
When searching series you cannot select multiple results. Adding one series from the search results ends with a page refresh and blank page. In radarr the search results stay whole until you are done with selecting ALL series wanted and then new search. 

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: [e.g. 2.0.0.1]
 - Operating System: [e.g. Windows 10]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
This is not the case in v3, available in beta already.
