### ISSUE TITLE
piwik.sonarr.tv SSL certificate has expired and appears to be self-signed

### ISSUE THREAD

**Issue by interhive** [Sonarr/Sonarr#3533]
I stumbled onto this issue while testing a new web browser (Brave). When visiting my Sonarr installation, the browser showed that it was blocking https://piwik.sonarr.tv/piwik.js. I wasn't sure what this was and decided to check out the script. That's when I encountered the "Privacy error" that's thrown when an SSL certificate is out-of-date or otherwise insecure.

I checked out the certificate and it appears to have expired November 8, 2019 and, more importantly, this appears to be a self-signed certificate (localhost) with no certificate authority.

I've disabled analytics within Sonarr to stop it from being loaded but I did want to give a heads-up on the issue.

 - Sonarr Version: 2.0.0.5338
 - Operating System: FreeBSD
 - mono (macOS/Linux) Version: 5.10.1.47

![Screen Shot 2020-01-21 at 8 47 14 AM](https://user-images.githubusercontent.com/8636/72814508-c636e200-3c2a-11ea-8952-1927d8e14142.png)

**Comment by markus101** [comment]
Looks like piwik was pointed at an old server, it's pointed at the correct one now, though it may time a bit before it's updated. The requests are expected to fail as we haven't been using this service and is removed in v3.
