### ISSUE TITLE
[Request] Webhooks for updates

### ISSUE THREAD

**Issue by Ether009** [Sonarr/Sonarr#3534]
Currently the update choices include a couple of options. I would love the addition of say webhook as an additional choice there. One can do it through a script ofc, but it would be nice if not having to go through that. It would make it possible to as an example automate updates without using stuff like Watchtower in docker since you can use a webhook either to portainer (the easy way), directly to docker (if you expose the docker socket over tcp), or for the more advanced users, even by using the kubernetes API (at least from what I understand for the last one. I'm still very much a newbie when it comes to k8s).

Docker directly would normally require TLS verification which may be a bit of a pain to support. No idea about k8s, but at least portainer is straight forward. It doesn't even require TLS/SSL at all.

**Comment by markus101** [comment]
Script was originally added for Synology support, which ended up not being used, but never removed, we don't have plans to support webhooks or another mechanism at this time.
