### ISSUE TITLE
Get Selected button no longer works

### ISSUE THREAD

**Issue by christronyxyocum** [Sonarr/Sonarr#3536]
**Describe the bug**
The "Get Selected" button on the queue page no longer works.

**Screenshots**
https://sharex.tronflix.app/HoYA0/rOQIBoHO35.gif

**Logs**
UI problem so I don't think they'll help.

**System Information**

 - Sonarr Version: [3.0.3.688]
 - Operating System: [Docker]
 - mono Version: [5.20.1.34]

**UI Bugs:**
 - OS: [Windows]
 - Browser: [Chrome, Firefox, Brave]
 - Version: [All latest]

**Comment by christronyxyocum** [comment]
Seems the last time that this worked was with v3.0.3.679:

https://sharex.tronflix.app/HoYA0/dADIZalu37.gif

**Comment by christronyxyocum** [comment]
Looks like this is fixed in 3.0.3.690.

**Comment by markus101** [comment]
Yeah, fixed in https://github.com/Sonarr/Sonarr/commit/b93e8da23515559e56094dfa55a3f7847ef1ba8c
