### ISSUE TITLE
Releases with "Original Title (English Title)" aren't handled

### ISSUE THREAD

**Issue by rcombs** [Sonarr/Sonarr#3539]
**Describe the bug**
E.g. `[GJM] Eizouken ni wa Te wo Dasu na! (Keep Your Hands Off Eizouken!) - 02 [DA8C7CDE].mkv` doesn't match for episode 02 of this series: http://thexem.de/xem/show/4842

Both listed titles are in Xem, but Sonarr doesn't handle the "Original (English)"/"Alias (Title)" format.

**Comment by reloxx13** [comment]
Note: Manual starting a search for this episode uses the english name.

Autosearch: Orginal title
Usersearch: English title

**Comment by markus101** [comment]
Fixed via https://github.com/Sonarr/Sonarr/commit/a75e10c4c9e1bb65ef8defcd28336c1550dd8991
