### ISSUE TITLE
When importing series from disk hide already imported ones

### ISSUE THREAD

**Issue by tal** [Sonarr/Sonarr#3541]
When you import series from disk it shows the ones already imported. If you have many series in that folder it can be hard to find the one new one that isn't imported. 

Having the ability to filter out already imported directories would be very helpful for this.

**Comment by markus101** [comment]
Already imported series (within the same root folder) are already excluded during import, in both v2 and v3.

**Comment by tal** [comment]
Ah it appears as though these are occurring when I have multiple folders for the same series
