### ISSUE TITLE
Not all episodes are loaded from thetvdb

### ISSUE THREAD

**Issue by Lonli-Lokli** [Sonarr/Sonarr#3542]
**Describe the bug**
I am doing a manual import of this show 
https://thetvdb.com/series/tsarevni
List of available episodes for season 2 does not include all of them from thetvdb

**Screenshots**

**Logs**
[Logs](https://justpaste.it/7mwif) 

**System Information**

 Version
3.0.3.688
Package Version
3.0.3.688 by hotio
Mono Version
5.20.1.34

**Comment by markus101** [comment]
Same as https://github.com/Sonarr/Sonarr/issues/3415 things are cached for 24 hours on their end currently.

**Comment by Lonli-Lokli** [comment]
@markus101 I have added this episodes couple of weeks ago.

**Comment by Taloth** [comment]
I'm seeing all 14 episodes in season 2.
Refresh the series in Sonarr and check System->Events for any errors.

**Comment by Lonli-Lokli** [comment]
@Taloth I pressed Refresh & Scan button on tv page and still see only 7 episodes listed.
No errors on Event page

**Comment by Taloth** [comment]
Can you show a screenshot of the season page?

**Comment by Taloth** [comment]
![image](https://user-images.githubusercontent.com/6383890/73136269-e8c26400-404b-11ea-8337-dffa6f5ab2f0.png)

**Comment by Lonli-Lokli** [comment]
@Taloth When I expand series I was able to see all episodes. I was confused cuz in collapsed state it showed me only 7 episodes in title.
Now all is working, thanks a lot!

**Comment by Taloth** [comment]
That likely means those episodes are unmonitored.
