### ISSUE TITLE
Sonarr is downloading "the good doctor" when seearching for "doctor who (2005)" episodes

### ISSUE THREAD

**Issue by mcroach** [Sonarr/Sonarr#3543]
**Describe the bug**
When searching for season 1 & 2 episodes of "doctor who (2005)" sonarr is incorrectly matching and downloading episodes of "the good doctor (2017)" instead.

**System Information**
 - Version: 3.0.3.688
 - Package Version: 3.0.3.688-ls168 by linuxserver.io
 - Mono Version: 5.20.1.34

![image](https://user-images.githubusercontent.com/5669388/73156196-982a2580-40a2-11ea-9991-2accd2c9f22a.png)

**Comment by Taloth** [comment]
OZnzb.com assigned the wrong tvdbid to those releases. Check their site and click 'View series' next to the release and you'll see it direct to the wrong show. Report it to them and they'll be able to fix it.

**Comment by mcroach** [comment]
Thanks @Taloth for looking into this for me. 

Is there a configuration setting I can change so that "obvious" mismatches like this are caught and rejected from automatic downloads even when a tvdbid match is in play? Not downloading something is much preferred over grabbing the wrong content.

I would never had known this issue existed if I wasn't watching this particular auto search in real time and now I'm wondering how many other wrong episodes have been grabbed by my favorite robot helper that I don't know about.

**Comment by Taloth** [comment]
No, Sonarr generally trusts the indexer unless Sonarr was able to parse and match the title to another series. eg if you had The Good Doctor in your collection, it wouldn't have happened.

There's no configuration option to change any of this.

**Comment by mcroach** [comment]
Thanks for the insight on how this is meant to work.
