### ISSUE TITLE
Colons Replacement Options

### ISSUE THREAD

**Issue by gbolo** [Sonarr/Sonarr#3544]
Seems like sonarr replaces colons with dashes. It works fine, but it looks a bit "off". Was hoping that sonarr can have the same feature as radarr for options on how to deal with colons :) 

see https://github.com/Radarr/Radarr/issues/2140

**Comment by thezoggy** [comment]
this already exists?
`Replace Illegal Characters` and then also `CleanTitle` token

**Comment by markus101** [comment]
In v3 when illegal characters are replaced (not removed) `:` will be replaced in two ways depending on the usage.

`Series: Title` will become `Series - Title`, but `Series:Title` will become `Series-Title`. We don't have plans to make an option of it.
