### ISSUE TITLE
Unify custom filter options across all series table views

### ISSUE THREAD

**Issue by mcroach** [Sonarr/Sonarr#3548]
**Describe the problem**
Cannot replicate custom filters used to limit results on the Series list view when using the Mass Editor or Season Pass views. This greatly increases the workload when attempting to manage changes across a large library.

**Describe any solutions you think might work**
- Unify custom filter options so that the same attributes are available for use on the Series List, Mass Editor, and Season Pass views.
- Consider making "user created" custom filters available globally across the Series List, Mass Editor, and Season Pass views so that any custom filters created/modified are immediately available for use within the other views.
- Consider allowing the same column view options (which to show, how to sort, etc) the same across the Series List, Mass Editor, and Season Pass views. Today only the Series List supports customization of the columns displayed.

**Additional context**
![image](https://user-images.githubusercontent.com/5669388/73341474-4cae7d80-4242-11ea-8588-a67724e94db9.png)
![image](https://user-images.githubusercontent.com/5669388/73342601-83859300-4244-11ea-8875-fc118ba9d370.png)

**Comment by gimpyestrada** [comment]
I agree, I was extremely excited to see the custom filters in the Series list and then sadly disappointed when I realized I could not use these same custom filters to edit the in the Mass Editor.  This seems like a significant value add for media organization.
