### ISSUE TITLE
Existing episodes within season folders have misidentified season on import.

### ISSUE THREAD

**Issue by WhyKickAmooCow** [Sonarr/Sonarr#3549]
While importing an existing library into sonarr, series which have their episodes organised into season folders have their episodes misidentified as all being season 1.

For example:
![image](https://user-images.githubusercontent.com/13505247/73344992-23e0c380-42e8-11ea-8b28-0de3cc1219be.png)
episodes in the "Season 2" folder are identified as being a part of season 1, and so are not imported.

**System Information**

 - Sonarr Version: 2.0.0.5338
 - Operating System: Fedora Server
 - mono (Linux) Version: 5.14.0.177
- Docker Container: linuxserver/sonarr:5.14

**Comment by markus101** [comment]
Absolute episode numbers need to match what TVDB has, resetting per season like anime arcs do is not supported.

Using season folders for further identification is covered in https://github.com/Sonarr/Sonarr/issues/903 it may help with this case as well.
