### ISSUE TITLE
Exposing metrics

### ISSUE THREAD

**Issue by triggity** [Sonarr/Sonarr#3550]
**Describe the problem**
Currently, no system metrics are exposed for third party metrics collection systems (like prometheus) to parse. I've found third party exporters, but these rely on information returned from the public api, and cannot capture details about the inner workings like different processing times of steps. 

**Describe any solutions you think might work**
I propose the addition of an internal metrics registry and addition and exposure of these metrics. I propose using prometheus and it's java client, although am open to other libraries if one is preferred by this group. I am willing to implement this myself, but want to make sure
(a) this doesn't already exist and I just missed it
(b) Choice of using prometheus is not prohibitive to you

**Additional context**
Metrics captured:

Series:
    - downloaded, wanted, missing,
    - time in queue
    -  number in queue
Processing times:
    - indexing
    -

**Comment by markus101** [comment]
We're not opposed to a solution that can expose this information in some way, but we're not interested in a prometheus specific solution.

Out of the list of metrics you listed most should already be possible, the only one would be processing time of individual items, but overall RSS Sync time is already known based on the execution time of the task.

**Comment by onedr0p** [comment]
@triggity 

I have created a sonarr-exporter if you are interested, there are docker images available as well.

https://github.com/onedr0p/sonarr-exporter
https://hub.docker.com/r/onedr0p/sonarr-exporter

Also see my k8s manifest to see how I implemented it.

https://github.com/onedr0p/k3s-gitops/blob/master/deployments/monitoring/sonarr-exporter/sonarr-exporter.yaml

**Comment by markus101** [comment]
At this time we don't have plans to expose more metrics than are currently available.

**Comment by onedr0p** [comment]
With that said, feel free to check out my project for exporting metrics to prometheus

https://github.com/onedr0p/exportarr
