### ISSUE TITLE
Chilling Adventures of Sabrina Incorrect

### ISSUE THREAD

**Issue by Viceman256** [Sonarr/Sonarr#3553]
**Describe the bug**
This show is showing it as having season 1 and season 3, but there are only two seasons. The season 3 listing has caused all my episodes to show a warning.

**Screenshots**
![sabrina](https://user-images.githubusercontent.com/47254767/73584687-4ba26980-4457-11ea-8c30-1eb41f5eda11.JPG)
![sabrina1](https://user-images.githubusercontent.com/47254767/73584699-61b02a00-4457-11ea-9424-1e04889d7dc1.JPG)

**Logs**
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/4142020/sonarr.debug.txt)

**System Information**

 - Sonarr Version: 3.0.3.688
 - Operating System: Windows 1
 - .net Framework (Windows) or mono (macOS/Linux) Version: 4.8

**Comment by markus101** [comment]
Ongoing issue. https://github.com/Sonarr/Sonarr/issues/3415
