### ISSUE TITLE
The Late Show with Stephen Colbert not working correctly.

### ISSUE THREAD

**Issue by sparkie3** [Sonarr/Sonarr#3555]
**Describe the bug**
I am getting the following error when the searching tries to download episodes of **The Late Show with Stephen Colbert**:
`Unable to parse episodes from release name`
I have checked the spreadsheet and found that a manual exception has been added, but it is not functioning. Last updated in 2018. Row 121 of the spreadsheet as of this current time.
https://docs.google.com/spreadsheets/d/1PiIvzijwcdALKQWfGE3j4lwnOqmDkhB48fyQTArJpI4/edit#gid=675284162

**Screenshots**
N/A

**Logs**
N/A

**System Information**
I'm using the repo versions of Sonarr from the following guide:
https://github.com/Sonarr/Sonarr/wiki/Installation#Linux

 - Sonarr Version: 2.0.0.5338
 - Operating System: 5.3.0-29-generic #31-Ubuntu SMP
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono JIT compiler version 5.18.0.240 (Debian 5.18.0.240+dfsg-3 Mon Jun 24 08:50:44 UTC 2019)

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
In this case debug logs are absolutely required, likely not a bug, but support that should be asked on the forums.

**Comment by thezoggy** [comment]
the message is just saying it cant parse it because of your show type..  if your in 'standard' change it to 'daily'.

**Comment by markus101** [comment]
Please open a thread on the forums with debug logs if you're still having issues with this and we can troubleshoot it then.
