### ISSUE TITLE
Quality Size Definitions, Change Megabytes per minute to Megabit per second

### ISSUE THREAD

**Issue by RandomNinjaAtk** [Sonarr/Sonarr#3556]
**Describe the problem**
Currently Megabytes per minute does not simply translate well to average video bitrate because videos are typically handled in mbps rates. So you have to use a separate conversion calculation to be able to set a min/max to average video bitrate

**Describe any solutions you think might work**
Change the default calculation to use typical average video bitrate calculation and terminology. This should allow easier configuration because you can just specify the desired overall average video bitrate.

**Additional context**

**Comment by Taloth** [comment]
Duplicate of https://github.com/Sonarr/Sonarr/issues/3474 where I explain why it's that way and also why it's not 'accurate' anyway. We have no plans to change the unit used in the UI.

**Comment by RandomNinjaAtk** [comment]
Okay, thanks for the information
