### ISSUE TITLE
Pending Import still in import queue after removed from download client

### ISSUE THREAD

**Issue by Gamertech** [Sonarr/Sonarr#3557]
**Describe the bug**
If an complete automatic import fails (one cause is because it was replacing an existing season and I had a file with 2 episodes in 1 and was replacing with 2 separate files) then it will import all the other files and report a stalled import in the queue as intended.

If I manually import the remaining files myself (not through the queue as Sonarr has a habit of deleting additional files in a season if trying to import just 1 at a time) then it will spam the logs once per minute with "Import failed, path does not exist or is not accessible by Sonarr".

The error is identical to all the reports involving insufficient permissions or remote mapping, but in this case the perms and mapping are fine.

It simply can't locate the leftover files that were removed from the downloads directory and will continue looking for them even after I clear it from Transmission and the queue. It's apparently been doing it for the better part of the day, so no working timeout is evident.

The errors only stopped after I restarted Sonarr. If I recreated the folders it complained about, the errors stopped but Sonarr did nothing with them and the errors immediately started again if the folders were deleted.

Note, this is only happening on Sonarr v3, Sonarr v2 never had this log issue after doing the same action.

**Logs**
Just thousands of:
`20-2-1 21:17:02.3|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: \\HOMENAS\Videos\Downloads\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 11 [1080p].mkv. Ensure the user running Sonarr has access to the network share`
No other references in the logs.

**System Information**

 - Sonarr Version: 3.0.3.688
 - Operating System: Windows 10
 - .net Framework (Windows) Version: 3.5/4.8

**Comment by markus101** [comment]
Your single log line shows a release for a single episode, which can't be partially imported, it's either imported or not.

> If I manually import the remaining files myself (not through the queue as Sonarr has a habit of deleting additional files in a season if trying to import just 1 at a time)

Sonarr only deletes files that are linked to the episode you're importing to.

> The error is identical to all the reports involving insufficient permissions or remote mapping, but in this case the perms and mapping are fine.

Sonarr gets the list of what to import from your download client, removing it from history there to stop Sonarr from seeing it as ready to import, or use Manual Import from Activity: Queue to import it.

> after I clear it from Transmission and the queue

We do cache the queue, but evidently don't clear it when it's awaiting import and has been removed, that's an oversight.

**Comment by Gamertech** [comment]
> Your single log line shows a release for a single episode, which can't be partially imported, it's either imported or not.

As I said, one cause was a partial season import, the other 3 were folders. The logs were identical for all of them except the file/directory names.

The single file one was where it had already imported the file correctly, renamed it and everything, except Sonarr got messed up and continued to redownload the exact same file 2 more times.

The first time I cancelled the download and made sure the ep was showing in the series page as well as wasn't listed in Wanted or anywhere else. Second time it fully downloaded while I was AFK and got stuck importing as it was identical to the existing file, so I cleared it from Transmission, refreshed the queue and deleted the file.

Nothing untoward was shown in the logs, Sonarr legit thought it was still in the queue and didn't check the existing file to compare. Was still configuring a fresh Windows install, so put it down to that until the folders did the same thing and I noticed the rapidly growing log files.

> Sonarr only deletes files that are linked to the episode you're importing to.

Haven't tried in v3, but in v2, importing a episode from a season download via the queue (because you can only do 1 ep at a time) took that ep and deleted the rest of the folder. Was reproducible and is also the reason I finish things like that manually now.

Selecting completed files pending in the queue does not light up "Grab Selected" so can't do multiple at once.

> Sonarr gets the list of what to import from your download client, removing it from history there to stop Sonarr from seeing it as ready to import, or use Manual Import from Activity: Queue to import it.

Which is what I do with season downloads. Remove it from Transmission, refresh the queue so it's gone, then manually import the folder.

> We do cache the queue, but evidently don't clear it when it's awaiting import and has been removed, that's an oversight.

Just recreated another one. Replacing a season with a smaller HEVC release. The logs show it auto-imported all eps except one which was identical to all the other files, correctly binned all the files it replaced and left just the one file in the download folder.

Non-sample file detected: [\\HOMENAS\Videos\Downloads\The Simpsons (1989) Season 30 S30 (1080p AMZN WEB-DL x265 HEVC 10bit EAC3 5.1 ImE)\The Simpsons (1989) - S30E12 - The Girl on the Bus (1080p AMZN WEB-DL x265 ImE).mkv]

The queue however is showing all 23 files in the season still pending import and if I delete it from Transmission, clear the queue and import manually, it triggers the error spam.
