### ISSUE TITLE
Synology Download Manager

### ISSUE THREAD

**Issue by pcliff069** [Sonarr/Sonarr#3558]
After post processing the Torrent is moved from the download folder to @downloads at Synology root folder.
Is there any process or setting I am missing to prevent this from happening? 
The torrent sets correctly so that part is fine. It's just if I need to do any fixes etc.

**Comment by markus101** [comment]
Please use the forums or subreddit for questions.

The only place Sonarr will move (or hardlink/copy for most torrent clients) is to the series folder after the download completes.
