### ISSUE TITLE
[feature request] View file copy status and percentage

### ISSUE THREAD

**Issue by jdukleth** [Sonarr/Sonarr#3559]
There is no indication of how Sonarr copy files progress is going after a download finishes. You have to go manually check the filesize on the partial file.

It would be amazing to have a screen that shows which files are currently being copied from the downloads folder to the destination. With percentage and speed if possible.

This is not a request to troubleshoot but rather a feature request that I think would be invaluable.

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/3524 which is covered by https://github.com/Sonarr/Sonarr/issues/282
