### ISSUE TITLE
Option to disable restriction "Existing file on disk is of equal or higher preference"

### ISSUE THREAD

**Issue by SuberSeb** [Sonarr/Sonarr#3560]
I'm using Sonarr V3 app with Jackett. Every time when Sonarr wants to grab the release I see this error: "Existing file on disk is of equal or higher preference", so I need manually set lower quality for already existing episodes in Sonarr for example from WEBDL-1080p to HDTV-1080p. 
This happens because torrent trackers in my country usually puts every episodes of season in one torrent file (I can show you example if you don't understand), not in separate torrent files. For example: The Walking Dead S01E01-E16, not the The Walking Dead S01E01, The Walking Dead S01E02, The Walking Dead S01E03, etc. 
So when new episode comes up (WEBDL-1080p), this episode adding to the same torrent file but existing episodes alreary have WEBDL-1080p quality that prevents Sonarr from grabbing this release and this error "Existing file on disk is of equal or higher preference".
I really like Sonarr and need this option. A little checkbox in settings that can completely disable restriction "Existing file on disk is of equal or higher preference".

**Comment by markus101** [comment]
We have no plans to ignore the files already on disk and/or quality profiles. In v3 you can use manual search at the season level and override, but that's as close as it'll get.
