### ISSUE TITLE
Add jump bar to mass editor/season pass

### ISSUE THREAD

**Issue by EnorMOZ** [Sonarr/Sonarr#3561]
**Describe the problem**
Mass Editor is missing a jump bar to easily jump to Shows starting with X. This allows for easy navigation to edit specific movies without having to scroll. The scrolling is also buggy right now as well.

**Describe any solutions you think might work**
Add a jump bar similar to how series main page.

**Additional context**
<img width="45" alt="Screen Shot 2020-02-03 at 8 58 51 AM" src="https://user-images.githubusercontent.com/13998170/73659029-6812f180-4663-11ea-92d5-029d03ac527f.png">

**Comment by markus101** [comment]
v4 now has mass editor and season pass as part of the series list.
