### ISSUE TITLE
Preferred Words overrule season pack preference

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#3562]
**Describe the bug**

A bonus to a specific release group prevents Sonarr from grabbing season packs without such bonus since it will first grab the single episode (on btn) and then reject the pack.

A fix is a bit of a challenge since Preferred Words overrules Protocol too, so we can't just move episode count up.

**Comment by markus101** [comment]
Is this really a bug? It may be unexpected in some cases, but it still makes sense in the end.

**Comment by Taloth** [comment]
The pack likely contains the preferred episode too, it's simply not in the pack name coz it usually contains multiple groups.
It really depends on what's more important: having all episodes, or satisfy the preferred words. in this case the user is stuck with 1 episode and missing the rest. The only workaround is to add a regex to give season packs more priority in preferred words.

The simplest approach is to prefer a season pack over preferred words, but based on pack, not episode count (otherwise dual episodes would get preference).

The ultimate way would be to find the best season pack (according to the rules) _and_ find the right combination of single episodes (according to the rules). And then decide between the two best options to see which best satisfies the request that way a combination that gets all episodes automatically gets preferred over one with less episodes, regardless of score.
That's of course a lot more work but solves a number of other issues.

**Comment by bakerboy448** [comment]
Trash has some a preferred word schema for season packs as a good workaround
https://trash-guides.info/Sonarr/V3/Sonarr-Release-Profile-RegEx/#optional-preferred-preferences

**Comment by markus101** [comment]
> The simplest approach is to prefer a season pack over preferred words, but based on pack

This is easy, pull out:
https://github.com/Sonarr/Sonarr/blob/850552bf1769e663d6001a77b7cf76f88dad00a4/src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs#L108-L114

To a function called before preferred word score, but then you end up preferring season packs over protocol as well, which seems unexpected. We don't really have a way to prefer season packs over preferred words, but also below protocol. So do we make it a option?

**Comment by xfouloux** [comment]
leaving the choice for the user would be awesome, for my example, there is often some episodes in MULTI that i can grab from usenet/torrent, but not all because they are not all released i don't know, but then someone post a pack containing all episodes in torrent most often. Because it's the same quality, sonarr won't pick up the season pack because there is already episodes in the season, and then i miss having the complete season.
I reckon it's not something everybody needs, but having my second sonarr instance only for multi having this option set would be awesome.
