### ISSUE TITLE
Episode Search Mismatch for Multi-Episode Files

### ISSUE THREAD

**Issue by tkdrob** [Sonarr/Sonarr#3563]
**Describe the bug**
I was searching for episodes for season 6 of Paw Patrol, example being S06E21. RARBG has multi-episode results. A manual search in Sonarr gives no results. A search with jackett gives me S06E21E22. The logs indicate a different issue. It's searching for S06E12, not S06E21. Thetvdb shows that all episodes released prior to S06E21 were first aired on 11 unique days. S06E21 and E22 were both released on the 12th unique date. This is the only possible explanation I have for why Sonarr would search for S06E12 instead. Is this a Sonarr issue or is it a tvdb or other database one? My guess its Sonarr but I could be wrong. Thanks

**Logs**

DownloadDecisionMaker | No results found
NzbSearchService | Searching 15 indexers for [Paw Patrol : S06E12]

**System Information**

 - Sonarr Version: 3.0.3.690
 - Operating System: Synology - Docker
 - mono Version: 5.20.1.34

**Comment by markus101** [comment]
Not a bug, it's remapped on thexem.de that way (see the FAQ for info on that). http://thexem.de/xem/show/4814

If you have more questions about it, please open a thread on the forums or subreddit.
