### ISSUE TITLE
Completed download handling for specific quality profiles

### ISSUE THREAD

**Issue by MB053** [Sonarr/Sonarr#3564]
**Describe the problem**
I have 2 Profiles 1 of them i want to completely automate download and placing in the Season X Folder of the Serie. however the other one is a bit different. i manually want to look for the download because after downloading i need to do stuff manually. now the problem is if i enable completed download handling. everything across the Sonarr Server will be handled and i need to look in a lot of folders before i can edit. 

**Describe any solutions you think might work**
i would like an option to enable completed download handling for Profile A or B or  A, B and not C

**Comment by markus101** [comment]
This isn't something we have plans to support.
