### ISSUE TITLE
Tracked Downloads caching invalid episode ids

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#3565]
**Describe the bug**
When episodes/series get removed while there's still a tracked download. Then the queue will serve invalid queue items to the UI. Which then queries non-existent episodes (failing).

Solution is to force a reparse & remap of all tracked downloads when any series refresh/removal happens.

**Workaround**
Step 1: Optional: Run Housekeeping (if pending queue suffers from the same problem)
Step 2: Restart Sonarr

**Comment by Qstick** [comment]
Not saying it’s the right way, but this is how we fixed this in Lidarr < https://github.com/lidarr/Lidarr/commit/5defb69eb6100186dedf9eee62748d3336ad5ebe#diff-197500c5a96bf39d2f230c7f4181a5e4>
