### ISSUE TITLE
Disable scene mapping option for manual imports

### ISSUE THREAD

**Issue by iamcagn** [Sonarr/Sonarr#3567]
I understand this is a topic that has come up often, and that the developers have weighed in saying they won't offer an option to disable it completely, as that would cause it's own set of problems. That said...

**Describe the problem**
I convert 264 content to 265 once it's over a certain age. The converted content ends up in a folder that I then import into Sonarr using the manual import option, often 50+ episodes at a time. While I do look over the list, there have been times when I've missed that the filename and the episode that Sonarr has matched with are different, requiring a redownload of the episodes that are now incorrect.

**Describe any solutions you think might work**
An option to disable scene mapping on the manual import dialogue. The setting would not be persistent, and all the searching/downloading side of things would remain the same. This means that you can manually import files that are known to be correct, that are already in the same filename format used in Sonarr, without the chance of incorrectly matching to different episodes/seasons. An alert next to the size could be shown if file is ignoring the scene mapping.

**Comment by Taloth** [comment]
Why not drop the x265 back in the series folder you got it from? Doesn't really need a manual import. Sonarr assumes files in the series folder follow tvdb numbering.
A series refresh would pick them up automatically. Or for v3 with the series page Manual File Import.

**Comment by iamcagn** [comment]
My naming scheme is: {Series Title} - S{season:00}E{episode:00} - ({Quality Full}) ({MediaInfo Simple} {MediaInfo AudioChannels})

I include the codec in the name, which is how my script identifies which files need to be converted. If I dropped the files in the same folder, the renaming function doens't seem to do another mediainfo check, so it keeps the old h/x264 codec in the file name, which causes the script to think it needs to reconvert it.

**Comment by Taloth** [comment]
Replace the x264 with x265 in the filename during the transcode. Sonarr needs to see a new filename (or a new file). It'll then unlink the old x264 file and link the new file.
You can also just append something to the filename, like '.transcoded.mkv', but then you'd have to rely on running the rename function to get the filename fixed up.

**Comment by iamcagn** [comment]
I often covert episodes from multiple series, and the script I run currently just creates symlinks to the original files in a single folder, which I then point StaxRip to. I'd need to manually sort the files into the correct series/season folder, and then either run a scan on my entire library or go into each series and refresh them individually. Since it's also re-scanning the files I've already converted, or am not ready to convert yet, it would cause excessive and unnecessary IO and API calls to the various services like the TVDB. Yes, what you've suggested would work, but it would not be ideal.

If the releases were always consistent, with every release having the same season/episode number which matches the scene mapping, having the option always on would make perfect sense. But there are plenty of examples (American Dad, Futurama, Chilling Adventures of Sabrina, The Good Place, etc) where releases end up being labeled exactly what they are, which Sonarr them completely ignores thinking they are for a different episode.

I understand a global/per series/per season/per episode option to disable it is unlikely, but an option to toggle it during manual import, something a human needs to do and isn't automatic, makes sense.

**Comment by markus101** [comment]
> Since it's also re-scanning the files I've already converted, or am not ready to convert yet, it would cause excessive and unnecessary IO and API calls to the various services like the TVDB.

Rescan Series (API command) does not hit Skyhook (our TVDB proxy): https://github.com/Sonarr/Sonarr/wiki/Command#rescanseries
The IO it requires is 1 request for all files if nothing has changed then reading media info for each file it actually needs to import.

**Comment by markus101** [comment]
No plans to disable scene mappings for Manual Import, getting the files back into the series folder and having Sonarr detect the changed file (via https://github.com/Sonarr/Sonarr/issues/3366) is the best way to replace files like this.
