### ISSUE TITLE
Trace Logs for further investigation of #3569

### ISSUE THREAD

**Issue by Mattieo** [Sonarr/Sonarr#3570]
[Trace Logs.pdf](https://github.com/Sonarr/Sonarr/files/4182130/Trace.Logs.pdf)

**Describe the bug**
Refer closed forum #3569

**Comment by markus101** [comment]
Please open a thread on our [forums](https://forums.sonarr.tv), not another issue on github. Don't convert the text file to a PDF, upload the text file somewhere and link it in the forum post.
