### ISSUE TITLE
Be able to bulk assign show/season/episode number in manual import

### ISSUE THREAD

**Issue by juicetin** [Sonarr/Sonarr#3572]
Possible labels: ui/enhancement

**Describe the problem**
When manually importing, a lot of manual work is involved for more than a few episodes

**Describe any solutions you think might work**
* be able to set the season for a whole at once
* be able to set the show for a whole folder at once
* be able to assign the folder episodes in ascending order by default, as this would cover 95%+ of cases (main exceptions being if the folder is missing episodes, or when there are combined episodes)

**Comment by markus101** [comment]
This is possible in v3.
