### ISSUE TITLE
Magnet Link not getting parsed 

### ISSUE THREAD

**Issue by dgalli1** [Sonarr/Sonarr#3573]
**Describe the bug**
Sonarr crashes when a magnet link with the character &#039; is in the dn parameter
**Logs**
`System.FormatException: A field-value pair of the magnet link contain more than one equal'.
  at MonoTorrent.MagnetLink.ParseMagnetLink (System.String url) [0x002b0] in M:\BuildAgent\work\63739567f01dbcc2\src\MonoTorrent\MagnetLink.cs:93 
  at MonoTorrent.MagnetLink..ctor (System.String url) [0x00022] in M:\BuildAgent\work\63739567f01dbcc2\src\MonoTorrent\MagnetLink.cs:32 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromMagnetUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String magnetUrl) [0x00004] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TorrentClientBase.cs:208`

**System Information**

 - Sonarr Version: [e.g. 3.0.3.698]
 - Operating System: [e.g. Docker/Linux]
 - mono 5.20.1.34 

I tried fixing it myself and submitting a Pull request. Weirdly enough C# doesn't like to encode the string correctly via the Webutitlity.HtmlDecode function (Is this a mono quirk?). 
Not really sure if this is even Valid to have in a magnet Link but it seems like Transmission and similar clients can handle it without problems.

**Comment by markus101** [comment]
What leads you to believe the `'` is the culprit? At a glance I don't see `'` being handled by MonoTorrent in any special way and adding a `'` to the dn portion of a magnet link does not reproduce the same error for me.

> Weirdly enough C# doesn't like to encode the string correctly via the Webutitlity.HtmlDecode function (Is this a mono quirk?).

`Webutitlity.HtmlDecode` wouldn't encode anything, but HTML encoding is not the same as URL encoding.

Please provide an example magnet link that has this issue so we can reproduce.

**Comment by dgalli1** [comment]
magnet:?xt=urn:btih:2749695EE0BB9BC3856F4254664349B447D1A597&dn=DC&#039;s+Legends+of+Tomorrow+(2016)+Season+3+S03+(1080p+BluRay+x265+HEVC+10bit+AAC+5.1+Vyndros)&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.ilibr.org:6969/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://p4p.arenabg.com:1337/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce

> Webutitlity.HtmlDecode wouldn't encode anything, but HTML encoding is not the same as URL encoding.
Thing is &#039; is a HTML encoding and not a url encoding. This is also why it breaks the function which parses the MagnetLinks. This is also why i ment that the magnet url is strictly speaking not valid. I'm coming from a PHP background so i don't know the C# equivalent to this function https://www.php.net/manual/de/function.html-entity-decode.php. But this would fix the Magnet Link. The Parsing Logic now just splits the url on ; and &. But both of this characters are used in the example Magnet Link, so it obviously fails. This is why the Chars would have to get replaced beforehand.

**Comment by dgalli1** [comment]
Ups now i see the issue i didn't notice that Github automatically escaped & # 0 3 9 ; (minues spaces)

**Comment by Taloth** [comment]
Which indexer does this come from?

**Comment by dgalli1** [comment]
1337x via Jackett. But i still believe it should be fixed inside sonarr and not only jackett. Because every other Torrent Client i tried could handle a Magnet Like this

**Comment by Taloth** [comment]
I thought as much.

The problem is that simply html decoding is a hack, not a fix. It doesn't work if it contains for example `&amp;` or any other that results in '+', '&' or '='. Which would mean you have to do 'html decode unless it results in x,y,z'.

The torrent client I tested simply ignores the error and considered dn=DC, and ignored the rest.
We could add code that does the same, but that only hides the problem. You never would've noticed the problem.

Finally, on the 1337x website the magnet link is url encoded.

Check the api response from Jackett to Sonarr. If it's url encoded then it's a Sonarr issue, if it's not url encoded then it's a Jackett issue.

**Comment by markus101** [comment]
Is the URL encoded from Jackett to Sonarr?
