### ISSUE TITLE
Sonarr doesn't see all jackett results

### ISSUE THREAD

**Issue by K4nape** [Sonarr/Sonarr#3575]
### Describe the bug
In jackett I see much more torrents, for example we searching

`Torr | Vikings (S06E09) -​ Resurrection (2020) WEB-​DL TRL`

In **Jackett** i see:
![jackett](https://user-images.githubusercontent.com/10292911/74639544-c1584600-5176-11ea-8567-008aeaf512bd.PNG)

But don't see this torrent in **sonarr**:
![sonarr](https://user-images.githubusercontent.com/10292911/74639712-0a0fff00-5177-11ea-9b57-783def8b1096.PNG)

### Configuration
Jackett categories id: **5000**
![categoriesjackett](https://user-images.githubusercontent.com/10292911/74640372-1c3e6d00-5178-11ea-80fd-b45964bef31c.PNG)

Add in **Sonarr** categories id: **5000**
![Categoriessonarr](https://user-images.githubusercontent.com/10292911/74640417-35471e00-5178-11ea-9fec-2764a60dc5ef.PNG)

What we doing wrong?

**System Information**
 - Sonarr Version: [e.g.  2.0.0.5338]
 - Operating System: [e.g. Linux mint]

**Comment by markus101** [comment]
Please use the forums for support / questions.

This probably comes down to how Jackett translates the requests for the indexer, but how Sonarr queries Jackett is standardized.
