### ISSUE TITLE
Add `path` to queue items

### ISSUE THREAD

**Issue by armsby** [Sonarr/Sonarr#3576]
**Describe the problem**
When sonarr does not find the files where is expect it puts out a warning message, this message contains the path where it expect the files to be located, but there is no element for the path, can you please add path as an element like title.

**Describe any solutions you think might work**
add the expected path as an element, the information is already there in the message

**Additional context**

**Comment by markus101** [comment]
Not 100% sure what you mean by "element", please elaborate on exactly what you're looking for, bonus points for a mock image of it.

**Comment by armsby** [comment]
sorry xml element like

},
    "size": 715978385.0,
    "title": "The.Simpsons.S31E12.1080p.WEB.x264-XLF",
    "path": "/downloads/torrents/tv-sonarr80/",
    "sizeleft": 0.0,
    "timeleft": "00:00:00",
    "estimatedCompletionTime": "2020-02-17T07:38:54.497254Z",
    "status": "Completed",
    "trackedDownloadStatus": "Warning",
    "statusMessages": [
      {
        "title": "The.Simpsons.S31E12.1080p.WEB.x264-XLF",
        "messages": [
          "No files found are eligible for import in /downloads/torrents/tv-sonarr80/The.Simpsons.S31E12.1080p.WEB.x264-XLF"
        ]
      }
    ],

**Comment by markus101** [comment]
In v3 this is included in `/api/v3/queue` as `outputPath`.
