### ISSUE TITLE
Improve spanish language detection

### ISSUE THREAD

**Issue by egrueda** [Sonarr/Sonarr#3579]
Right now, Sonarr detects spanish language on files by looking for "spanish" string.
But most shws in spanish are not labeled using english, but spanish.
So we use the words "Castellano" or "Español" in the name.

We need Sonarr detects "castellano" or "español" as spanish language.
Can you implement it?

**Comment by markus101** [comment]
Should be possible, but we'll want example release names to make sure we're detecting it properly. If you can provide those we can look into it further.

**Comment by egrueda** [comment]
Sure! I greped some names from sonarr logs:

https://pastebin.com/GWt4CjjA

It comes from a well known spanish indexer

**Comment by VandrerenErik** [comment]
I might be able to take on this task if I'm free from work in the coming weeks.
