### ISSUE TITLE
Not Prompted to Restart Sonarr after resetting API Key

### ISSUE THREAD

**Issue by XenorPLxx** [Sonarr/Sonarr#3580]
**Describe the bug**
I've got Forms authentication turned on in Sonarr.
After resetting the API key by using the button available on the Setting/General page I'm getting the message visible on the screenshot below.
Trying Sonarr in a new browser with cleaned cache and in incognito mode doesn't help - after posting login data through Sonarr login form I'm getting the same message.

**Screenshots**
![image](https://user-images.githubusercontent.com/6712823/74775358-d5df3000-5295-11ea-9495-9ae2cc67d67d.png)

**Logs**
```
20-2-18 21:27:17.3|Info|Auth|Auth-Unauthorized ip 127.0.0.1 url 'http://mysonarrurl.pl:443/api/v3/series'
20-2-18 21:27:17.3|Info|Auth|Auth-Unauthorized ip 127.0.0.1 url 'http://mysonarrurl.pl:443/api/v3/tag'
20-2-18 21:27:17.3|Info|Auth|Auth-Unauthorized ip 127.0.0.1 url 'http://mysonarrurl.pl:443/api/v3/qualityprofile'
20-2-18 21:27:17.3|Info|Auth|Auth-Unauthorized ip 127.0.0.1 url 'http://mysonarrurl.pl:443/api/v3/languageprofile'
20-2-18 21:27:17.3|Info|Auth|Auth-Unauthorized ip 127.0.0.1 url 'http://mysonarrurl.pl:443/api/v3/config/ui'
20-2-18 21:27:17.3|Info|Auth|Auth-Unauthorized ip 127.0.0.1 url 'http://mysonarrurl.pl:443/api/v3/system/status'
20-2-18 21:27:17.3|Info|Auth|Auth-Unauthorized ip 127.0.0.1 url 'http://mysonarrurl.pl:443/api/v3/customFilter'
```

**System Information**

 - Sonarr Version: 3.0.3.698
 - linuxserver preview docker image run on Debian Stretch, Sonarr is behind nginx reverse proxy, but going directly through IP gets me the same result

**UI Bugs:**
 - OS: Windows
 - Browser: Chrome, Vivaldi, Edge
 - Version: most recent ones

**Comment by markus101** [comment]
You need to restart Sonarr after resetting the API key. This should be prompted after the reset, we'll have to look at why that's not happening.
