### ISSUE TITLE
Sonarr v3 won't connect to Plex Media Server

### ISSUE THREAD

**Issue by PrincessLuna2253** [Sonarr/Sonarr#3581]
After updating to Sonarr v3, I can no longer connect Sonarr to Plex to force a library update when new content is imported. The connection was working fine with v2, and continues to work fine with Radarr. The only fix I could find via google was to make sure Plex isn't set to require secure connections, which I did. I also tried it with "Use SSL" both disabled and enabled. I checked the logs, relevant part linked below, and the error doesn't seem to be helpful. I tried purposely entering the wrong IP/port and got the exact same error.

Sonarr error: https://i.imgur.com/l2oKU6S.png
IP and port are set correctly: https://i.imgur.com/ZKRm3E5.png

Relevant section of log file: https://pastebin.com/raw/d2bTAZGp

**System Information**
 - Sonarr Version: 3.0.3.698 (linuxserver.io docker with preview tag)
 - Operating System: Linux (Unraid)
 - .net Framework (Windows) or mono (macOS/Linux) Version: unknown

**Comment by markus101** [comment]
Please use the forums for support.

Sonarr is unable to get a response, but you don't include your mono version, so we can't rule out an issue there.
