### ISSUE TITLE
Fetures request. API history function should have lastAired as sorting option

### ISSUE THREAD

**Issue by spyvingen** [Sonarr/Sonarr#3582]
###Feature Request
In the API docs we have sortord3r on episode name and date of event if I am not mistaken now.

I would also like an option for sorting by firstAierd

### What problem are you looking to solve?
I want to list newest episode not the old ones that got downloaded last

**Comment by markus101** [comment]
You need to fill out the feature request template, not jam it into the subject line. Please update the issue using the correct template.

```
**Describe the problem**
A clear and concise description of the problem you're looking to solve.

**Describe any solutions you think might work**
A clear and concise description of any solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
```

**Comment by spyvingen** [comment]
Don't know how that got in there this is not my issue :) 
I wanted a way in the API to sort history on firstAired to be able to see new episodes higher up in the list :)

**Comment by markus101** [comment]
`firstAired` isn't part of history, history is a list of things that have happened (grabbed, imported, deleted). If you want to see upcoming or aired but not yet available episodes in history you can use the calendar. The series list also includes `nextAiring` and `previousAiring`.
