### ISSUE TITLE
Multiple Directories (one RW, rest possibly RO) directories for tv shows.

### ISSUE THREAD

**Issue by sjpotter** [Sonarr/Sonarr#3583]
**Describe the problem**
Currently, one can only specify a single directory for a TV show.  This works fine, except if one wants to move the show to different storage (say slower network or cloud storage).  I'd still like sonarr to know that the episodes exist (and if better versions turn up to "upgrade".  Today, I basically have the choice of moving them off the server and telling sonarr to ignore those episodes / seasons.

**Describe any solutions you think might work**
Being able to specify multiple directories with one being the "new content" directory and possibly specifying the others as RO (i.e. won't even try to delete content if upgrade) or RW (will delete content that has been upgraded on "new content", but wont write any new content there itself.

**Comment by markus101** [comment]
This isn't something we have plans to support at this time.
