### ISSUE TITLE
Don't show .files or .directories

### ISSUE THREAD

**Issue by dkids** [Sonarr/Sonarr#3586]
I have TV shows on /Volumes/TV.   MacOS requires certain directories on the drive.   Because they start with ., I don't think that Sonarr should be trying to map them.

It looks like Sonarr does know about most of these.   .bzvol is from BackBlaze, an online backup service.   The other two are from Apple.

ls -ald /Volumes/TV

-rw-r--r--     1 kids  staff    8196 Feb 16 14:28 .DS_Store
d--x--x--x     8 kids  staff     256 Feb 20 08:23 .DocumentRevisions-V100
dr-xr-xr-t     2 kids  staff      64 Jun  9  2017 .HFS+ Private Directory Data
drwx------     5 kids  staff     160 Jun  9  2017 .Spotlight-V100
drwx-wx-wt     3 kids  staff      96 Oct  5  2017 .TemporaryItems
drwx--x--t     2 kids  staff      64 Feb 16 14:50 .Trashes
drwxrwxrwx     6 kids  staff     192 Feb 20 15:48 .bzvol
-rw-r--r--     1 kids  staff       0 Sep  8  2017 .com.apple.timemachine.donotpresent
-rw-r--r--     1 kids  staff       0 Jun 29  2018 .com.apple.timemachine.supported
drwx------     3 kids  staff      96 Feb 20 09:04 .fseventsd

![Screen Shot 2020-02-20 at 1 58 13 PM](https://user-images.githubusercontent.com/30055574/74990887-5bc7bc00-53f9-11ea-8456-b92b08142d25.jpg)

Version 3.0.3.698
Mono Version 6.8.0.105
AppData directory /Users/kids/.config/Sonarr
Startup directory/Users/kids/Applications/Sonarr.app/Contents/MacOS

**Comment by Taloth** [comment]
I recommend you don't store the library in the volume root. 

Sonarr omits certain subdirectories like DS_Store, but we're not going to ignore everything starting with a dot.

**Comment by dkids** [comment]
I don't want to put the library in subdirectories, I want to turn people into dinosaurs.

Ooops, wrong thread.   I have spent several days going from /Volumes/WD4TB/Kid_Movies to /Volumes/Kid_Movies but fine, I'm switching to /Volumes/Movies/Kid.

Thanks for the advice.
