### ISSUE TITLE
Filter eventType option in history API

### ISSUE THREAD

**Issue by spyvingen** [Sonarr/Sonarr#3587]
**Describe the problem**
When i load history i get all different event.
The application i am building needs to show only imported episodes
So to get out like 50 results i need to load like 100-200 results to filter out the ones that are imported and get like 50.

**Describe any solutions you think might work**
A filter function for eventType so i can specify that i want 50 of the eventTyp="downloadFolderImported"

**Comment by Taloth** [comment]
You already can. It's possible in the UI already, so it's possible in the api.

**Comment by spyvingen** [comment]
Thanks for the input.
If i am not to stupid now (and that could be the case) i found out in dev console that gui use eventType=3 but when i try it on my server i only get several other eventType:s like file episodeFileDeleted, downloadFailed and so on.

This is my request
http://XXXXXXX/api/history?apikey=XXXXXXXXX&pageSize=20&page=1&eventType=3&sortKey=date&sortDir=desc

**Comment by Taloth** [comment]
it's an enumeration.
```
    public enum HistoryEventType
    {
        Unknown = 0,
        Grabbed = 1,
        SeriesFolderImported = 2,
        DownloadFolderImported = 3,
        DownloadFailed = 4,
        EpisodeFileDeleted = 5,
        EpisodeFileRenamed = 6,
        DownloadIgnored = 7
    }
```

**Comment by spyvingen** [comment]
But then my API request should work?

**Comment by spyvingen** [comment]
This is the response i get for that request 

https://pastebin.com/wkWiD5mB

**Comment by Taloth** [comment]
I didn't notice before but you're using the wrong (v2) api url, check the browser again.

**Comment by spyvingen** [comment]
Ohh ok.
How do i specify v3?

![image](https://user-images.githubusercontent.com/36534176/75095990-09be9c00-559b-11ea-8dca-f2b3bd9cb768.png)

Could this be the api  version? Im kinda noob at api:s overall :) And not really used to dev console yet

**Comment by spyvingen** [comment]
I am using Sonarr 3.0.1.490 according to sonarr

**Comment by spyvingen** [comment]
Ohh think i found it. It is /api/v3/ right? :)

**Comment by Taloth** [comment]
bingo. ;)

**Comment by spyvingen** [comment]
Ohh god my whole ap was based on v2 but i dont get any of the data i need in v3 version and need to do a fetch for each episode. Is there a way to simplify it a bit. I need like EP series name and so on and i got that in the v2 request :)

//J

**Comment by spyvingen** [comment]
Maybe for me it will o faster to do a v2 fetch of a couple of hundreds and filter out the ones i want instead of doing like 50+ requests to sonar?

**Comment by Taloth** [comment]
The UI does a single query to `api/v3/episode` to fetch all of them, not 50 requests.

**Comment by spyvingen** [comment]
Ok so I will fill an array with ep I'd or something and then request the episode API?

If you have time could you give me an example or something that points me in the right direction. This is the first API I ever used and kinda new to both Vue js and json

**Comment by spyvingen** [comment]
I am sooo proud I actually got the history API to work and list all My newly downloaded :)

**Comment by spyvingen** [comment]
Ok now i see (i think) it is one request and response but the data is not there as individual values it uses some logic to get it from filename and stuff?

Is that correct understanding?

**Comment by spyvingen** [comment]
Ok getting somwhere atleast :)

![image](https://user-images.githubusercontent.com/36534176/75099665-90d43a00-55c4-11ea-8057-a30898c32ad8.png)
