### ISSUE TITLE
Support Looking up Episodes by episodeFileId

### ISSUE THREAD

**Issue by tip2tail** [Sonarr/Sonarr#3589]
**Describe the problem**
I am working on a custom program for my specific setup which uses the Sonarr API.  In this program I query /episodefiles?seriesId=123 for all the files related to this series on the disk.  Depending on some checks, I may then want to query for and then update the Episode object.  However, with the information in the EpisodeFile object, I cannot directly GET /episode/{epId} as the episode ID is not included.

The result is a horrible mess of having to query for the Episodes in the first instance, which I really was not wanting to do unless I needed to.

**Describe any solutions you think might work**
Episode object ID value should be included in the EpisodeFile object response

**Comment by markus101** [comment]
Episode files don’t have a episode ID because that link doesn’t exist. One episode file can be linked to multiple episodes, but one episode can only be linked to one file.

The only way to return all the related episode IDs with the episode file would be to to join the them in making it needlessly more complex for most scenarios where it’s not needed.

No plans to add episode ID to episode files, but we could add a filter on the episodes endpoint. You’d get the same outcome without an impact for other API calls.

**Comment by tip2tail** [comment]
@markus101 thank you.

Your description of the episodefile <> episode link makes perfect sense 

I think that adding this new filter would be a good idea.  I'd be willing to give it a try myself as a fix, however if you can flesh out a bit more info on how you see it working (URL etc) and I can give it a shot!!

Thanks.

**Comment by markus101** [comment]
I think we'd want to do it similar to how it works for filtering by `episodeIds`, though in this case I think a single `episodeFileId` parameter is sufficient.

It'd live here:
https://github.com/Sonarr/Sonarr/blob/bcc8b655f7cda574e6e16855d627e19d73da469c/src/Sonarr.Api.V3/Episodes/EpisodeModule.cs#L27-L58

I'd suggest to refactor the throwing of a `BadRequestException` as the `else` in a `if/else if/else` block. And within the block handling the `episodeFileId` you just need to call `_episodeService.GetEpisodeByFileId`.

Let me know if you have any questions.

**Comment by tip2tail** [comment]
I'll give it a shot! :)

**Comment by tip2tail** [comment]
Hi @markus101 

Is this only being developed for V3 just now?  Can I add this new feature to V2 as that is what I currently use.

**Comment by markus101** [comment]
Outside of critical fixes, v2 is no longer being updated.
