### ISSUE TITLE
Can't add tvdb:340774 "Guepardes" TVShow

### ISSUE THREAD

**Issue by Aerya** [Sonarr/Sonarr#3590]
**Describe the bug**
Hello, can't add this French show Guépardes, tvdb ID: 340774  => `Couldn't find any results for 'tvdb:340774`
https://www.thetvdb.com/series/340774

**Logs**
`20-2-25 08:50:35.2|Trace|Http|Req: 35 [GET] /api/v3/series/lookup?term=tvdb%3A340774
20-2-25 08:50:35.2|Trace|HttpClient|Req: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/340774
20-2-25 08:50:35.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
20-2-25 08:50:35.5|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/340774: 404.NotFound
{"message":"NotFound","description":"thetvdb.com does not have a series with the tvdbid 340774, it may have been removed."} (285 ms)
20-2-25 08:50:35.5|Trace|Http|Res: 35 [GET] /api/v3/series/lookup?term=tvdb%3A340774: 200.OK (291 ms)
20-2-25 08:50:35.5|Debug|Api|[GET] /api/v3/series/lookup?term=tvdb%3A340774: 200.OK (291 ms)`

**System Information**
Linuxserver Docker

Version
    3.0.3.701
Package Version
    3.0.3.701-ls174 by linuxserver.io
Mono Version
    5.20.1.34
AppData directory
    /config
Startup directory
    /usr/lib/sonarr/bin

Thank you

**Comment by markus101** [comment]
Please use the forums for support.

There is not an English translation for that series.
