### ISSUE TITLE
Filename Exceeds 255 Characters

### ISSUE THREAD

**Issue by 19wolf** [Sonarr/Sonarr#3591]
**Describe the problem**
I'm getting the issue described in [2699](https://github.com/Sonarr/Sonarr/issues/2699):

`"/data/Media/Anime/Interspecies Reviewers/[HorribleSubs] - Interspecies Reviewers - 04 - Savage Succubi Will Squeeze the Life Out of You Even If You Say You Can't Go On, Salamander Girls Have Such Hot Bods, Hearts, Sals, and Manders, that You Can't Help But Get Fired Up A... [HDTV-1080p h264 AAC].mkv"`

I think what's going on is the episode title is being limited to [255 characters](https://github.com/Sonarr/Sonarr/pull/3061), but when it adds my directory/file structure, it goes above the limit and fails.

**Describe any solutions you think might work**
I would like a way to specify my own limit for episode titles (maybe 20 characters or something)

**Comment by markus101** [comment]
> I think what's going on is the episode title is being limited to 255 characters, but when it adds my other tags, it goes above the limit and fails.

Before episode titles are calculated the rest of the file name is calculated. Each section of the file name (folder or file) is limited to 255 characters, it looks like the file portion in this case is 260 characters.

> I would like a way to specify my own limit for episode titles (maybe 20 characters or something)

We have no plans to have a configurable limit.

This is a bug, not a feature request, we'll need all the information requested for a bug.

**Comment by 19wolf** [comment]
**Describe the bug**
As above
**Screenshots**
There is no error in the UI

**Logs**
https://pastebin.com/e2gm5QMx

**System Information**

- Version: 3.0.3.701
- Package Version: 3.0.3.701-ls174 by linuxserver.io
- Mono Version: 5.20.1.34
- AppData directory: /config (this is linked directly to the host harddrive, not network storage)
- Startup directory: /usr/lib/sonarr/bin

**Additional context**
The original request still is technically a "feature request", it's just *because* of the bug.

**Comment by PersonneAllie** [comment]
It's still a buggy, here is mine [sonarr.txt](https://github.com/Sonarr/Sonarr/files/4497509/sonarr.txt)

**Comment by markus101** [comment]
1. It hasn't been addressed (it's still open)
2. Info logs aren't very helpful for diagnosing issues, debug or trace are required

**Comment by markus101** [comment]
1. It hasn't been addressed (it's still open)
2. Info logs aren't very helpful for diagnosing issues, debug or trace are required

**Comment by ChibiTomo** [comment]
Here is a as short as possible trace log: 
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/4533214/sonarr.trace.txt)

I know it is a quite specific issue, but it would be nice if it could be addressed. I a few anime series that fall into this.

Thanks.

**Comment by xxsteven69xx** [comment]
I believe I'm having the same issues, especially in the anime categories. 
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/4562192/sonarr.debug.txt)

**Comment by Jerrk** [comment]
I also have this bug every now and again, here is a trace log for importing the specific episode.

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/4808237/sonarr.trace.txt)

**Comment by markus101** [comment]
This should be fixed by https://github.com/Sonarr/Sonarr/commit/fed2a429c7a3f0eeb83d36a3edbddde9a77a263e

**Comment by ChibiTomo** [comment]
> This should be fixed by [fed2a42](https://github.com/Sonarr/Sonarr/commit/fed2a429c7a3f0eeb83d36a3edbddde9a77a263e)

I just looked into the commit. How this should solve the bug ? 
The problem will continu to happend on automatic import and manual import with les than 100 files, isn't it ?

**Comment by markus101** [comment]
Wrong commit, https://github.com/Sonarr/Sonarr/commit/158e31d54aab2419e79b3a7b2f3ef918954a440b is the correct one.

**Comment by ChibiTomo** [comment]
> Wrong commit, [158e31d](https://github.com/Sonarr/Sonarr/commit/158e31d54aab2419e79b3a7b2f3ef918954a440b) is the correct one.

Thanks !

But it des not seems to take the file directory in account. Hope this will do the job.

**Comment by Taloth** [comment]
Please provide additional log files of whatever still goes wrong.
