### ISSUE TITLE
IRC XDCC support

### ISSUE THREAD

**Issue by KRDucky** [Sonarr/Sonarr#3592]
**Describe the problem**
There is no ability to utilize IRC/XDCC downloading

**Describe any solutions you think might work**
Add IRC client for downloading, Add indexers like Nibl for searching IRC bots

**Comment by markus101** [comment]
We do not have plans to support IRC or other types at this time.

**Comment by dgalli1** [comment]
Would you accept a PR for it if i implemented it?

**Comment by Taloth** [comment]
No, it'd be a third download client type and we're not willing to accept that at this time.
