### ISSUE TITLE
tracker update  format 

### ISSUE THREAD

**Issue by vinedu18** [Sonarr/Sonarr#3594]
hello i noticed that sonarr search method is title + season but since then can tracker use title.season. it would be easier to just search for the title is to compare the results with the chosen season
cordially vinedu18

**Comment by markus101** [comment]
Most trackers are integrated via jackett, which translates the API request to the indexer. We don’t have plans to change how Sonarr searches indexers.

If you’re having issues with a specific indexer please open a thread on the forums for support.
