### ISSUE TITLE
Release Profile not allowing save

### ISSUE THREAD

**Issue by jaywoodz** [Sonarr/Sonarr#3595]
I am unable to save a new release profile, stating "Indexer does not exist"
Please see attached screenshot.

Release: 3.0.3.707

![image](https://user-images.githubusercontent.com/22654506/75653713-1fcbfc80-5c2c-11ea-9577-ae8fc1d04785.png)

**Comment by wishbones** [comment]
Works in `3.0.3.703`, not working in `3.0.3.707`

**Comment by TRaSH-** [comment]
![image](https://user-images.githubusercontent.com/6155095/75696142-63198000-5cab-11ea-8a61-4e4ffa36cf6e.png)

was also broken in 3.0.3.706
someone reported it on discord.
after testing i get the same issue.
tested it with Any and a single indexer
```
20-3-2 17:27:58.6|Trace|Scheduler|Pending Tasks: 0
20-3-2 17:28:13.4|Trace|Http|Req: 223 [POST] /api/v3/releaseprofile
20-3-2 17:28:13.4|Trace|SonarrErrorPipeline|Handling Exception
20-3-2 17:28:13.4|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Preferred: Indexer does not exist
20-3-2 17:28:13.4|Trace|Http|Res: 223 [POST] /api/v3/releaseprofile: 400.BadRequest (3 ms)
20-3-2 17:28:13.4|Debug|Api|[POST] /api/v3/releaseprofile: 400.BadRequest (3 ms)
```
