### ISSUE TITLE
sonarr fails to parse quick import / DownloadedEpisodesScan imports. However, "interactive" import in the browser works fine.

### ISSUE THREAD

**Issue by etfeet** [Sonarr/Sonarr#3599]
**Describe the bug**
sonarr fails to parse quick import / DownloadedEpisodesScan imports. However, "interactive" import in the browser works fine.

is there a different api I can use for triggering an import from a python script Where i can provide the full path to the individual media file / directory  along with series and episodes id's?

ie script has the following info:

{
  "series": "House of Cards (US)",
  "series_id": 68,
  "season": 2,
  "episode": 11,
  "episode_id": 4390,
  "title": "Chapter 24",
  "tvdbid": 262980,
  "hasfile": false,
  "file": "my full path/House of Cards (US) - S02E11 - Chapter 24 - WEB-DL-2160p.mkv"
}

The series_id and episode_id fields are the sonarr ids for the series and episode. The only workaround I can think of would be  to move the episode file into the show/season directory and trigger a rescan.

**Screenshots**

**Logs**
20-3-2 22:11:20.7|Trace|Http|Req: 106338 [POST] /api/v3/command
20-3-2 22:11:20.7|Trace|CommandQueueManager|Publishing DownloadedEpisodesScan
20-3-2 22:11:20.7|Trace|CommandQueueManager|Checking if command is queued or started: DownloadedEpisodesScan
20-3-2 22:11:20.7|Trace|CommandQueueManager|Inserting new command: DownloadedEpisodesScan
20-3-2 22:11:20.8|Trace|Http|Res: 106338 [POST] /api/v3/command: 201.Created (28 ms)
20-3-2 22:11:20.8|Debug|Api|[POST] /api/v3/command: 201.Created (28 ms)
20-3-2 22:11:20.8|Trace|CommandExecutor|DownloadedEpisodesScanCommand -> DownloadedEpisodesCommandService
20-3-2 22:11:20.8|Trace|CommandQueueManager|Marking command as started: DownloadedEpisodesScan
20-3-2 22:11:20.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-3-2 22:11:20.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-3-2 22:11:20.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-3-2 22:11:20.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-3-2 22:11:20.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-3-2 22:11:20.8|Debug|Parser|Parsing string 'House.of.Cards.S02E12.2160p.NF.WEB-DL.DDP5.1.H265-Ao-RakuvArrow'
20-3-2 22:11:20.8|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
20-3-2 22:11:20.8|Debug|Parser|Episode Parsed. House of Cards - S02E12
20-3-2 22:11:20.8|Debug|Parser|Language parsed: English
20-3-2 22:11:20.8|Debug|QualityParser|Trying to parse quality for House.of.Cards.S02E12.2160p.NF.WEB-DL.DDP5.1.H265-Ao-RakuvArrow
20-3-2 22:11:20.8|Debug|Parser|Quality parsed: WEBDL-2160p v1
20-3-2 22:11:20.8|Debug|Parser|Release Group parsed: Ao
20-3-2 22:11:20.8|Debug|DownloadedEpisodesImportService|Unknown Series House.of.Cards.S02E12.2160p.NF.WEB-DL.DDP5.1.H265-Ao-RakuvArrow
20-3-2 22:11:20.8|Debug|DownloadedEpisodesCommandService|Failed to import
20-3-2 22:11:20.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-3-2 22:11:20.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-3-2 22:11:20.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-3-2 22:11:20.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-3-2 22:11:20.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-3-2 22:11:20.8|Trace|CommandQueueManager|Updating command status
20-3-2 22:11:20.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-3-2 22:11:20.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-3-2 22:11:20.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-3-2 22:11:20.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-3-2 22:11:20.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-3-2 22:11:20.8|Trace|EventAggregator|Publishing CommandExecutedEvent
20-3-2 22:11:20.8|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
20-3-2 22:11:20.8|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
20-3-2 22:11:20.8|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
20-3-2 22:11:20.8|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
20-3-2 22:11:20.8|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
20-3-2 22:11:20.8|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
20-3-2 22:11:20.8|Trace|CommandExecutor|DownloadedEpisodesScanCommand <- DownloadedEpisodesCommandService [00:00:00.0109270]
20-3-2 22:11:20.8|Trace|Http|Req: 106339 [GET] /api/v3/command
20-3-2 22:11:20.8|Trace|CommandQueueManager|Getting all commands
20-3-2 22:11:20.8|Trace|Http|Res: 106339 [GET] /api/v3/command: 200.OK (1 ms)
20-3-2 22:11:20.8|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
20-3-2 22:11:20.8|Trace|Http|Req: 106340 [GET] /api/v3/command
20-3-2 22:11:20.8|Trace|CommandQueueManager|Getting all commands
20-3-2 22:11:20.8|Trace|Http|Res: 106340 [GET] /api/v3/command: 200.OK (1 ms)
20-3-2 22:11:20.8|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
20-3-2 22:11:20.9|Trace|Http|Req: 106341 [GET] /api/v3/command
20-3-2 22:11:20.9|Trace|CommandQueueManager|Getting all commands
20-3-2 22:11:20.9|Trace|Http|Res: 106341 [GET] /api/v3/command: 200.OK (1 ms)
20-3-2 22:11:20.9|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
20-3-2 22:11:27.3|Trace|Scheduler|Pending Tasks: 0

**System Information**

 - Sonarr Version: 3.0.3.688
 - Operating System: Ubuntu 18.04
 - mono version: 5.20.1.34

**Comment by etfeet** [comment]
looking at the ajax calls I think this can be accomplished using /api/v3/manualimport and /api/v3/command
Are there any api docs for v3?

does the v3 /command still take downloadclientid as field argument?

**Comment by markus101** [comment]
> sonarr fails to parse quick import / DownloadedEpisodesScan imports. However, "interactive" import in the browser works fine.

Quick import will work if the path is a full path to the "job folder" (or directly to the file), same as https://github.com/Sonarr/Sonarr/wiki/Command#downloadedepisodesscan

You should be able to use that API command to achieve what you want without using manual import endpoints or commands, but it'll depend on what path you initially sent to Quick import. `House.of.Cards` wouldn't match `House of Cards (US)`, which is perhaps the issue here, but passing in a `downloadId` to the command would allow Sonarr to use that to help import.

There are not updated docs for v3; the `downloadedepisodesscan` command works the same way as documented for v2.

To go the manual import route you'd need to mimic the command that Sonarr is sending from the UI, you could probably skip the `/api/v3/manualimport` and fill in everything manually to satisfy the command.

The body would look something like:

```
{
  "files": [
    {
      "path": "my full path/House.of.Cards.S02E12.2160p.NF.WEB-DL.DDP5.1.H265-Ao-RakuvArrow/House of Cards (US) - S02E11 - Chapter 24 - WEB-DL-2160p.mkv",
      "folderName": "House.of.Cards.S02E12.2160p.NF.WEB-DL.DDP5.1.H265-Ao-RakuvArrow",
      "seriesId": 68,
      "episodeIds": [4390],
      "quality": {
        "quality": {
          "id": 4,
          "name": "HDTV-720p",
          "source": "television",
          "resolution": 720
        },
        "revision": {
          "version": 1,
          "real": 0,
          "isRepack": false
        }
      },
      "language": {
        "id": 1,
        "name": "English"
      },
      "downloadId": "abc"
    }
  ]
}
```

**Comment by etfeet** [comment]
Thanks for that.

another thing  i noticed that was odd. 
The particular episode download above was triggered from a sonarr season search - clicking the search for monitored episodes in season button on the show page. However, sonarr doesn't seem to have any record of requesting the episode to be downloaded. Ie it doesn't show up as a pending download on the activity page (/acitvity/queue uri). However, my download client (nzbget in this case) started downloading it and then the post-processing script failed. It mainly failed I think because sonarr didn't recognize the downloadclientid that it received since for some weird reason it had no idea it even requested the episode download.

the post-process script just a python  script that runs filebot with hardlinking turned on and then sends the resulting filebot processed directory path to the /api/command endpoint

ie
curl  -s -XPOST http://localhost:6789/api/command?apikey=my_api_key-d
```
{
"name": "DownloadedEpisodeScan",
"downloadClientId": "nzbget drone param",
"path": "/data/downloads/processed/shows/my torrent name",
"importMode": "Move"
}
```

I had about 20 or so episodes that sonarr requested for downloading that I think failed because somehow it didn't have a record that it requested them. Ie sonarr log threw an errror saying unknown downloadclientid during import and it was unable to  parse the episode names into the show name. for whatever reason it seems to want to parse the parent download folder despite  the folder being setup like so:

`/data/downloads/torrent/processed/series/Younger.S06E10.MULTi.1080p.HDTV.H264-HYBRiS/Younger/Season\ 6/Younger\ -\ S06E10\ -\ It\'s\ All\ About\ the\ Money\,\ Honey\ HDTV-1080p.mkv`

with the above directory path and sending
`/data/downloads/torrent/processed/series/Younger.S06E10.MULTi.1080p.HDTV.H264-HYBRiS` as the  path argument it tries to parse `Younger.S06E10.MULTi.1080p.HDTV.H264-HYBRiS` instead of the actual episode files. That also happens if send the full path to an individual episode as the path argument as well.

is there a different import folder structure / episode format that would work better for sonarr being able to parse the files during import?

main reason I've been using the post-processing script instead of the automatic download import is to work around sonarr having problems parsing the files during important and the download never gets imported.

**Comment by markus101** [comment]
> It mainly failed I think because sonarr didn't recognize the downloadclientid that it received since for some weird reason it had no idea it even requested the episode download.

Does Sonarr not have a record of that grab in it's history?

> `/data/downloads/torrent/processed/series/Younger.S06E10.MULTi.1080p.HDTV.H264-HYBRiS/Younger/Season\ 6/Younger\ -\ S06E10\ -\ It\'s\ All\ About\ the\ Money\,\ Honey\ HDTV-1080p.mkv`
> is there a different import folder structure / episode format that would work better for sonarr being able to parse the files during import?

I'd expect it to be named like so: `/data/downloads/torrent/processed/series/Younger.S06E10.MULTi.1080p.HDTV.H264-HYBRiS/Younger.S06E10.MULTi.1080p.HDTV.H264-HYBRiS.mkv` Before importing the files shouldn't be renamed.

> main reason I've been using the post-processing script instead of the automatic download import is to work around sonarr having problems parsing the files during important and the download never gets imported.

That'll happen if the name doesn't match what Sonarr knows (maybe it needs an alias).

Please open a thread on the forums with debug logs + other requested information to troubleshoot the issue.
