### ISSUE TITLE
DiskTransferService Failed rar

### ISSUE THREAD

**Issue by Jayotis** [Sonarr/Sonarr#3600]
I am running a script that will unrar a download for sonarr to process and transfer to the media server.  Looking at my logs It seems sonarr is detecting the partial unrar and starting the transfer before unpack completes and fails.  This leaves a partial file on the media server.  This brings up the old uncompress feature requests but also maybe some error handling could be useful here. 
I am going to unrar as a different name then rename on completion in my script.

**Comment by markus101** [comment]
You'll want to unrar to a different location then move the file to where Sonarr is looking to process it from. This will also happen with partial transfers from a remote server. https://github.com/Sonarr/Sonarr/issues/282 and https://github.com/Sonarr/Sonarr/issues/784 are relevant.
