### ISSUE TITLE
Sonarr stuck at "Downloaded - Waiting to Import"

### ISSUE THREAD

**Issue by darkdex52** [Sonarr/Sonarr#3602]
### System Information/Logs

**Sonarr Version:** 
3.0.3.712

**Operating System:**
Windows 10

**.net Framework (Windows) or mono (macOS/Linux) Version:**
latest

**Link to Log Files (debug or trace):**
debug: https://pastebin.com/X01HDjUb
tracelog: https://pastebin.com/NDthiyKU

### Additional Information

Completely fresh install.
Downloading from torrents to a local disk. Using qBittorrent. Torrent files aren't set to be removed but they do stop seeding in the client. Files download fine, they show in activity, but they just won't move to where they're supposed to. Sonarr is running as a service.

It seems core issue is this:
TinyIoC.TinyIoCResolutionException: Unable to resolve type: NzbDrone.Core.Messaging.Commands.IExecute`1[[NzbDrone.Core.Download.ProcessMonitoredDownloadsCommand, Sonarr.Core, Version=3.0.3.712, Culture=neutral, PublicKeyToken=null]] ---> TinyIoC.TinyIoCResolutionException: Unable to resolve type: NzbDrone.Core.Download.DownloadProcessingService ---> TinyIoC.TinyIoCResolutionException: Unable to resolve type: NLog.ILogger

**Comment by markus101** [comment]
Already fixed, you need to update.

https://github.com/Sonarr/Sonarr/commit/385c7fb0ce64eb3fa98e39cd642e3db180bd3225
