### ISSUE TITLE
Add IMDB ID & Series Type to Web Hook

### ISSUE THREAD

**Issue by darthShadow** [Sonarr/Sonarr#3603]
**Describe the problem**
I have recently migrated from a custom script for notifications to webhooks and noticed that the IMDB ID & Series Type fields are missing from the request body for Download/Upgrade.

**Describe any solutions you think might work**
Add IMDB ID & Series Type.

**Additional context**
NA

**Comment by markus101** [comment]
Closed via 50886ac928cb6d4a984dfef08f04d6f202e0644f
