### ISSUE TITLE
System->Events does not display event log

### ISSUE THREAD

**Issue by Zindaar** [Sonarr/Sonarr#3607]
The Event Log is not being displayed. This seems to be due to some sort of Database change that occured. (or possible database corruption)

**Logs**
Limited Trace Log.
At the bottom from, 20-3-5 10:39:07.7 onwards
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/4291803/sonarr.trace.txt)

Debug Log
At the bottom from 20-3-5 10:28:00.8 onwards
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/4291830/sonarr.txt)

**Additional context**
Do not know if it's an actual DB corruption or an upgrade error. I would suggest that because it is an event log, it should have a self heal if it gets corrupted.

Log database attached [logs.zip](https://github.com/Sonarr/Sonarr/files/4293139/logs.zip)
Select * from Logs: only returns rows from way back (there are entries with more recent dates in the VersionInfo table)
Select COUNT(*) from Logs: gives the same error as the log files "Result: database disk image is malformed"

**Comment by Zindaar** [comment]
Dropping and recreating the Logs Table restored functionality of the System->Events page, as well as restored data integrity of the Database.

This might be an isolated case of data corruption. 

**But** I would still like to request a "Self Healing" function for the logs database if it does corrupt itself.

**Comment by markus101** [comment]
Please fill in the complete template when filing issues.

https://github.com/Sonarr/Sonarr/issues/2134 covers database repair and we'll see if it makes sense to automatically recover the logs DB at that time.
