### ISSUE TITLE
Deluge fails to add download if it contains `%`

### ISSUE THREAD

**Issue by Enohriel** [Sonarr/Sonarr#3608]
Hello,

I dunno why, but I think that Preferred Words doesn't work in my case.

I've set 265 to be a preferred word over 264 to download x265 preferably.

![preferred word](https://user-images.githubusercontent.com/50456985/75997600-dddad900-5eff-11ea-85d1-164ce42386f4.jpg)

I get a perfect case where 2 releases are available (x264 and x265).

![avail release](https://user-images.githubusercontent.com/50456985/75997755-1b3f6680-5f00-11ea-84a6-568e38fe5553.jpg)

We can see that preferred words matches, and that it should prefer the x265 release.

The quality shoudn't be an issue as both qualities are in the same group.

![quality settings](https://user-images.githubusercontent.com/50456985/75997864-3f9b4300-5f00-11ea-8109-33339cd962ec.jpg)

However, Sonarr will get the x264 release instead of the x265 one.

Version
    3.0.3.713
Package Version
    3.0.2
Mono Version
    6.8.0.105

Running on Debian 9.

**Comment by markus101** [comment]
You need to upload your debug logs for that search and link them here.

**Comment by Enohriel** [comment]
It seems like 265 IS preferred, but there is an issue with how the name is handled.

I suspect the '%' to be the issue.
IIRC, I had a similiar issue with the '3%' TV show.

[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/4293962/sonarr.debug.txt)

**Comment by markus101** [comment]
Yeah Sonarr tried to grab it, but deluge failed to add it so Sonarr moved on to the next one. The encoding in the log file looks funny as well.

We might be able to encode it before sending to Deluge, but that may not help.

**Comment by Enohriel** [comment]
I'm facing to a similar issue with another TV Show.

But this time, I suspect 'À' char to be faulty.

[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/4294229/sonarr.debug.txt)

**Comment by markus101** [comment]
I'm unable to reproduce with a dev build of Sonarr 4.0.0.328 and Deluge 2.1.1, so it appears somewhere along the way this was resolved.
