### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Soyde** [Sonarr/Sonarr#3609]
## Bug Report
Episode is not recognized.
Original Folder name: The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]
Original episode name: The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org].mkv

Due to the fact that sonarr doesn't recognize episodes named Cap.1010, I run an script after downloading file that rename it to S{season:00}E{episode:00} format as follows: The Walking Dead - Temporada 10 [HDTV 720p][S10E10][AC3 5.1 Castellano][www.descargas2020.org].mkv

But I suppose that the parser is getting mesh with string [www.descargas2020.org]
Could you check it? 

### System Information/Logs
Version 3.0.3.713
But also fails at last stable v2
**Operating System:** Windows server 2012 r2
**.net Framework (Windows) 4.0.30319

**Link to Log Files (debug or trace):**
20-3-7 01:48:34.2|Debug|Api|[GET] /api/v3/command: 200.OK (0 ms)
20-3-7 01:48:34.2|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
20-3-7 01:48:34.2|Debug|Api|[GET] /api/v3/log/file: 200.OK (1 ms)
20-3-7 01:48:47.4|Debug|Api|[GET] /api/v3/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft&includeUnknownSeriesItems=false: 200.OK (4 ms)
20-3-7 01:48:47.4|Debug|Api|[GET] /api/v3/episode?episodeIds=1337: 200.OK (2 ms)
20-3-7 01:48:49.4|Debug|Api|[POST] /api/v3/command: 201.Created (4 ms)
20-3-7 01:48:49.4|Debug|DownloadedEpisodesImportService|Processing path: C:\1\D\Tv\The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]
20-3-7 01:48:49.4|Debug|Parser|Parsing string 'The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]'
20-3-7 01:48:49.4|Debug|Parser|Episode Parsed. The Walking Dead - Temporada 10 [HDTV ][Cap 1010][AC3 5 1 Castellano][www descargas - S20E20 
20-3-7 01:48:49.4|Debug|Parser|Language parsed: English
20-3-7 01:48:49.4|Debug|QualityParser|Trying to parse quality for The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]
20-3-7 01:48:49.4|Debug|Parser|Quality parsed: HDTV-720p v1
20-3-7 01:48:49.4|Debug|Parser|Release Group parsed: 
20-3-7 01:48:49.4|Debug|DiskScanService|Scanning 'C:\1\D\Tv\The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]' for video files
20-3-7 01:48:49.4|Debug|DiskScanService|1 video files were found in C:\1\D\Tv\The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]
20-3-7 01:48:49.4|Debug|ImportDecisionMaker|Analyzing 1/1 files.
20-3-7 01:48:49.4|Debug|Parser|Parsing string 'The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]'
20-3-7 01:48:49.4|Debug|Parser|Episode Parsed. The Walking Dead - Temporada 10 [HDTV ][Cap 1010][AC3 5 1 Castellano][www descargas - S20E20 
20-3-7 01:48:49.4|Debug|Parser|Language parsed: English
20-3-7 01:48:49.4|Debug|QualityParser|Trying to parse quality for The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]
20-3-7 01:48:49.4|Debug|Parser|Quality parsed: HDTV-720p v1
20-3-7 01:48:49.4|Debug|Parser|Release Group parsed: 
20-3-7 01:48:49.4|Debug|VideoFileInfoReader|Getting media info from C:\1\D\Tv\The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]\The Walking Dead - Temporada 10 [HDTV 720p][S10E10][AC3 5.1 Castellano][www.descargas2020.org].mkv
20-3-7 01:48:49.4|Debug|Api|[GET] /api/v3/command: 200.OK (2 ms)
20-3-7 01:48:49.4|Debug|Api|[GET] /api/v3/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft&includeUnknownSeriesItems=false: 200.OK (4 ms)
20-3-7 01:48:49.4|Debug|Api|[GET] /api/v3/command: 200.OK (2 ms)
20-3-7 01:48:49.4|Debug|DetectSample|Runtime is over 90 seconds
20-3-7 01:48:49.4|Debug|Parser|Parsing string 'The Walking Dead - Temporada 10 [HDTV 720p][S10E10][AC3 5.1 Castellano][www.descargas2020.org].mkv'
20-3-7 01:48:49.4|Debug|Parser|Episode Parsed. The Walking Dead - Temporada 10 [HDTV ][ - S10E10 
20-3-7 01:48:49.4|Debug|Parser|Language parsed: English
20-3-7 01:48:49.4|Debug|QualityParser|Trying to parse quality for The Walking Dead - Temporada 10 [HDTV 720p][S10E10][AC3 5.1 Castellano][www.descargas2020.org].mkv
20-3-7 01:48:49.4|Debug|Parser|Quality parsed: HDTV-720p v1
20-3-7 01:48:49.4|Debug|Parser|Release Group parsed: 
20-3-7 01:48:49.4|Debug|VideoFileInfoReader|Getting media info from C:\1\D\Tv\The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]\The Walking Dead - Temporada 10 [HDTV 720p][S10E10][AC3 5.1 Castellano][www.descargas2020.org].mkv
20-3-7 01:48:49.5|Debug|ParsingService|Unable to find The Walking Dead - Temporada 10 [HDTV ][Cap 1010][AC3 5 1 Castellano][www descargas - S20E20 HDTV-720p v1
20-3-7 01:48:49.5|Debug|AggregateLanguage|Using language: English
20-3-7 01:48:49.5|Debug|AggregateQuality|Using quality: HDTV-720p v1
20-3-7 01:48:49.5|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Invalid season or episode
20-3-7 01:48:49.5|Debug|Api|[GET] /api/v3/command: 200.OK (2 ms)
20-3-7 01:48:49.5|Debug|Api|[GET] /api/v3/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft&includeUnknownSeriesItems=false: 200.OK (2 ms)
20-3-7 01:48:49.5|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)

**Comment by markus101** [comment]
Same as https://github.com/Sonarr/Sonarr/issues/3579

But that format would parse the series title as `The Walking Dead - Temporada 10 [HDTV 720p][` which won't match anything. As shown here:
`20-3-7 01:48:49.4|Debug|Parser|Episode Parsed. The Walking Dead - Temporada 10 [HDTV ][ - S10E10`

You'd have to replace that entire format.

**Comment by Soyde** [comment]
Sorry, I don't see any similarity with #3579 

I have also tried replacing the entire format as follows: **The Walking Dead - S10E10 - Stalker.mkv**
But it is still failing...As I told before  I suppose that the parser is getting mesh with string [www.descargas2020.org] at folder name

0-3-7 02:58:18.2|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
20-3-7 02:58:18.2|Debug|Api|[GET] /api/v3/command: 200.OK (2 ms)
20-3-7 02:58:18.2|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
20-3-7 02:58:21.0|Debug|Api|[POST] /api/v3/command: 201.Created (4 ms)
20-3-7 02:58:21.0|Debug|Api|[GET] /api/v3/command: 200.OK (7 ms)
20-3-7 02:58:21.0|Debug|Api|[GET] /api/v3/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft&includeUnknownSeriesItems=false: 200.OK (8 ms)
20-3-7 02:58:21.0|Debug|Api|[GET] /api/v3/command: 200.OK (3 ms)
20-3-7 02:58:21.0|Debug|DownloadedEpisodesImportService|Processing path: C:\1\D\Tv\The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]
20-3-7 02:58:21.0|Debug|Parser|Parsing string 'The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano]**[www.descargas2020.org]'**
20-3-7 02:58:21.1|Debug|Parser|Episode Parsed. The Walking Dead - Temporada 10 [HDTV ][Cap 1010][AC3 5 1 Castellano][**www descargas - S20E20** 
20-3-7 02:58:21.1|Debug|Parser|Language parsed: English
20-3-7 02:58:21.1|Debug|QualityParser|Trying to parse quality for The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]
20-3-7 02:58:21.1|Debug|Parser|Quality parsed: HDTV-720p v1
20-3-7 02:58:21.1|Debug|Parser|Release Group parsed: 
20-3-7 02:58:21.1|Debug|DiskScanService|Scanning 'C:\1\D\Tv\The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]' for video files
20-3-7 02:58:21.1|Debug|DiskScanService|1 video files were found in C:\1\D\Tv\The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]
20-3-7 02:58:21.1|Debug|ImportDecisionMaker|Analyzing 1/1 files.
20-3-7 02:58:21.1|Debug|Parser|Parsing string 'The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]'
20-3-7 02:58:21.1|Debug|Parser|Episode Parsed. The Walking Dead - Temporada 10 [HDTV ][Cap 1010][AC3 5 1 Castellano][**www descargas - S20E20** 
20-3-7 02:58:21.1|Debug|Parser|Language parsed: English
20-3-7 02:58:21.1|Debug|QualityParser|Trying to parse quality for The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]
20-3-7 02:58:21.1|Debug|Parser|Quality parsed: HDTV-720p v1
20-3-7 02:58:21.1|Debug|Parser|Release Group parsed: 
20-3-7 02:58:21.1|Debug|VideoFileInfoReader|Getting media info from C:\1\D\Tv\The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]\The Walking Dead - S10E10 - Stalker.mkv
20-3-7 02:58:21.1|Debug|DetectSample|Runtime is over 90 seconds
20-3-7 02:58:21.1|Debug|Parser|Parsing string 'The Walking Dead - S10E10 - Stalker.mkv'
20-3-7 02:58:21.1|Debug|Parser|Episode Parsed. The Walking Dead - S10E10 
20-3-7 02:58:21.1|Debug|Parser|Language parsed: English
20-3-7 02:58:21.1|Debug|QualityParser|Trying to parse quality for The Walking Dead - S10E10 - Stalker.mkv
20-3-7 02:58:21.1|Debug|Parser|Quality parsed: HDTV-720p v1
20-3-7 02:58:21.1|Debug|Parser|Release Group parsed: 
20-3-7 02:58:21.1|Debug|VideoFileInfoReader|Getting media info from C:\1\D\Tv\The Walking Dead - Temporada 10 [HDTV 720p][Cap.1010][AC3 5.1 Castellano][www.descargas2020.org]\The Walking Dead - S10E10 - Stalker.mkv
20-3-7 02:58:21.1|Debug|ParsingService|Unable to find The Walking Dead - Temporada 10 [HDTV ][Cap 1010][AC3 5 1 Castellano]**[www descargas - S20E20** HDTV-720p v1
20-3-7 02:58:21.1|Debug|AggregateLanguage|Using language: English
20-3-7 02:58:21.1|Debug|AggregateQuality|Using quality: HDTV-720p v1
20-3-7 02:58:21.1|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Invalid season or episode
20-3-7 02:58:21.1|Debug|DownloadEventHub|[Vikingos - Temporada 6 [HDTV 720p][Cap.610][AC3 5.1 Castellano][www.descargas2020.org]] Marking download as imported from Transmission
20-3-7 02:58:21.1|Debug|DownloadEventHub|Transmission does not support marking items as imported
20-3-7 02:58:21.1|Debug|Api|[GET] /api/v3/command: 200.OK (3 ms)
20-3-7 02:58:21.1|Debug|Api|[GET] /api/v3/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft&includeUnknownSeriesItems=false: 200.OK (3 ms)
20-3-7 02:58:21.1|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)

**Comment by markus101** [comment]
Your issue is a symptom of Sonarr not being able to parse the folder name correctly. If we can find a quick fix we'll implement it, but otherwise the fix will be to be able to parse that format.
