### ISSUE TITLE
Expose file creation date on upgrades

### ISSUE THREAD

**Issue by uchagani** [Sonarr/Sonarr#3615]
**Describe the problem**
Media servers often use the file creation date to show users the Latest TV videos.  On upgrades in Sonarr, the file is newer so it shows up as a new video in the Latest TV section.  By exposing the file creation date a user could run a script to change their upgraded file's creation date to match the old file thus preventing the file from showing up in the Latest TV section in Plex/Jellyfin.

**Describe any solutions you think might work**
Add a new environment variable that is exposed on upgrades that contains the file creation date of the old file.

**Additional context**
This would also be nice as a sonarr feature itself but exposing the date could be the easiest thing to do at the moment without having to do any UI updates.

**Comment by markus101** [comment]
To set expectations, the closest we can get here is the date the original episode was imported to Sonarr.

**Comment by uchagani** [comment]
Is there a reason for that? Couldn't we just query the file for the
information?

**Comment by markus101** [comment]
That's not always reliable and not something we normally get.

**Comment by uchagani** [comment]
OS differences?  Jellyfin for example uses `FileSystemInfo.CreationTimeUtc` which could throw errors on some file systems.  It may not be 100% reliable but it may work for a majority of the cases.

```
On Unix platforms that do not support creation or birth time, this property returns the older of the time of the last status change and the time of the last modification. On other platforms, it returns 12:00 midnight, January 1, 1601 A.D. (C.E.) Coordinated Universal Time (UTC), adjusted to local time.
```

**Comment by markus101** [comment]
Yes, specifically thinking of running under mono.
