### ISSUE TITLE
Turn off monitoring after episode is downloaded and processed

### ISSUE THREAD

**Issue by Polychronopolis** [Sonarr/Sonarr#3616]
After I finish viewing an episode, I typically delete the file to save space and help me keep track which episode is next.  However, if I don't go back into Sonarr and turn off monitoring the episode will be downloaded again during the next scan.

Another use case example would be moving the files to a temporary location or different machine to convert the files into a different format.  While the files are processing in that other folder, Sonarr will typically perform an update before all of the conversions complete.

It would be extremely beneficial to have an option to automatically disable monitoring episodes after a file has been downloaded and successfully processed by Sonarr.  This would save time, bandwidth and storage space for those who use a similar workflow.

**Comment by markus101** [comment]
This already exists. `Ignore Deleted Episodes` in Media Management settings.

**Comment by Polychronopolis** [comment]
Well, I feel silly.  The naming of the feature didn't seem to match the description.  Thank you for the clarification!
