### ISSUE TITLE
"Add New" not working.

### ISSUE THREAD

**Issue by suodrazah** [Sonarr/Sonarr#3617]
Straight forward issue, "Add New" will not return results.

Heaps of these in the logs, I would assume one from each search.

`20-3-12 16:26:24.3|Warn|HttpClient|HTTP Error - Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=riverdale: 503.ServiceUnavailable`

`20-3-12 16:30:48.8|Warn|HttpClient|HTTP Error - Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=riverdale: 504.GatewayTimeout`

Appears to have started with 3.0.3.721 but I'm not home so haven't had a chance to properly analyse the issue. Likely issue with Sonarr Skyhook service.

**Comment by JoeBoJoe** [comment]
Having the same issue.

**Comment by suodrazah** [comment]
> Having the same issue.

Looks as though it is now resolved. Skyhook is now responding.

**Comment by JoeBoJoe** [comment]
> > Having the same issue.
> 
> Looks as though it is now resolved. Skyhook is now responding.

Just did a refresh, working again for me too.

Cheers for the reply.

**Comment by markus101** [comment]
Yeah, we were seeing multi-minute response times using TVDB v2 data/API. Back on v1 it's well under 1s. We switched earlier today to deal with TVDB API returning 0 episodes for a number of series.
