### ISSUE TITLE
Sonarr mass downloading previously unmonitored episodes

### ISSUE THREAD

**Issue by cptv** [Sonarr/Sonarr#3619]
According to markus101 this is happening because TheTVDB is restructuring the season/episode numbering for various shows. When the show is restructured, Sonarr mistakes newly structured old seasons as "new" and incorrectly monitors them. It then proceeds to download the missing episodes and can sometimes queue up 300+ unwanted episodes

This has happened for Pawn Stars, Judge Judy, Jimmy Kimmel, Family Guy, and a few other shows in the past few days. One possible fix would be to provide either a toggle or default setting that would not monitor "new" episodes if their air-date was over [X] amount of days. I know it's not the team's job to clean up TVDB's messes but I doubt this will be fixed on their end anytime soon. Please and thank you!

 - Sonarr Version:  3.0.3.721
 - Operating System:  Ubuntu 18.04
 - Mono Version:  6.8.0.96

Edit: Also worth noting is that the issue if also deleting the episode "history" for many downloaded files. For Family Guy specifically I noticed that Seasons 11-18 disappeared from Sonarr. Then upon manual refresh of the series they reappeared in a monitored state. Whatever episodes I had already on disk were picked up by Sonarr during the refresh but the histories of those files were lost

**Comment by chief-gif** [comment]
Fix it!

**Comment by markus101** [comment]
The monitoring is a problem, but the bigger issue is searching for “new” episodes that already aired. I think we can safely block that for episodes over a certain threshold. That’ll eliminate mass API calls to indexers as well as the grabbing of releases for those episodes.

**Comment by thezoggy** [comment]
I can confirm I'm seeing this too on latest v3, it tried to download a few seasons old of a show that I already have
![img](http://zoggy.net/firefox_2020-03-12_11-40-56.png)

**Comment by Taloth** [comment]
https://old.reddit.com/r/sonarr/comments/fhj8z9/important_zero_episodes_and_old_episodes/

https://forums.sonarr.tv/t/important-zero-episodes-and-old-episodes-reappearing-as-monitored-and-potentially-downloaded-unintentionally/25023

**Comment by gregcbrown** [comment]
So... it's just a coincidence that I received an update yesterday, and this happened??

**Comment by harrv** [comment]
Sonarr downloaded hundreds of old and unmonitored episodes of The Deadliest Catch and So You Think You Can Dance before I noticed! In all, about 300 GB of unwanted episodes. Thanks for the explanation about TheTVDB issue. I hope the Sonarr devs can find a way to prevent this in the future.

**Comment by cptv** [comment]
Just saw the update to Sonarr v3 that addresses this issue. That was amazingly quick- you guys rock!

**Comment by Taloth** [comment]
we're also holding back updates for [919 shows](https://hastebin.com/sakuwihaje.sql) on skyhook that currently have no episodes, to give sonarr instances time to update.

**Comment by markus101** [comment]
Closing as we released a fix last week, you'll need to update if your version was released before 2020-03-13.
