### ISSUE TITLE
Bad decision on automatic searching. Preferred words not applying.

### ISSUE THREAD

**Issue by Syanelys** [Sonarr/Sonarr#3621]
**Describe the bug**
Hello, i submit this issue because sonarr won't download the right release regarding the configuration and my understanding of it.

First, this is the configuration : 
- Release profile with some preferred words and scores.
![image](https://user-images.githubusercontent.com/62140453/76618547-1cd4e400-6529-11ea-9de9-090fe5ab53c2.png)

- Quality profile using only one group:
![image](https://user-images.githubusercontent.com/62140453/76618785-abe1fc00-6529-11ea-8a13-469599cd4516.png)

- TV Show configuration using the release and quality profiles mentionned above : 
![image](https://user-images.githubusercontent.com/62140453/76618858-dfbd2180-6529-11ea-8988-a6d9563078e0.png)

When i manually search for one episode and sort by score, i get the file i would expect Sonarr to download. Here it is : 
![image](https://user-images.githubusercontent.com/62140453/76619122-71c52a00-652a-11ea-8597-bf410b8158f5.png)

But, when i use the automatic search and download button, Sonarr download this file instead : 
![image](https://user-images.githubusercontent.com/62140453/76619293-c9fc2c00-652a-11ea-8587-e423cd845384.png)

The sonarr debug logs file shows that the release i'm expecting was accepted : 
![image](https://user-images.githubusercontent.com/62140453/76619614-966dd180-652b-11ea-9d1b-77b169620f65.png)

But in the end, Sonarr will select the other release.
The list open by default when you click on manual download and the list you get when you sort by quality seems to be the same. At least, on both cases, the release downloaded appears on top.
So, did i miss something in the configuration or is it a bug ?

**Logs**
Here is the full debug log : https://pastebin.com/jKK8x40C

**System Information**

 - Sonarr Version: 3.0.3.727
 - Operating System: Raspbian GNU/Linux 10 (buster)
 - Mono (macOS/Linux) Version: 6.8.0.105

**UI Bugs:**
 - OS: Windows
 - Browser: Chrome
 - Version: 80.0.3987.132

**Comment by markus101** [comment]
Without seeing the whole debug file (not a screenshot(?) of a snippet of it I can’t say for sure, but it looks like language may be the difference.

What does the language profile look like? If English is above French then Sonarr did exactly as expected as language is checked before preferred words.

**Comment by Syanelys** [comment]
Thanks for your fast reply.

I paste the entire debug log on pastebin.com and put the link on my first post. 
Here is it again : https://pastebin.com/jKK8x40C

Indeed, in my language profile, english is above french. I didn't pay attention at that because i thought the language was always based on the audio. It seems the subtitles can change it. Anyway, here is the profile : 
![image](https://user-images.githubusercontent.com/62140453/76632798-09834200-6544-11ea-94aa-7465137127e6.png)

So i just changed to put french above english and here is the new result i get : 
![image](https://user-images.githubusercontent.com/62140453/76633283-c37aae00-6544-11ea-84b8-4fba21fa0591.png)

The results changed but the file i expect is still not on top.

**Comment by markus101** [comment]
It looks like the last hurdle is repacks/propers are preferred (by default) over ones that aren’t, so that one is higher despite the preference.

You can change that behaviour on the Media Management settings page.

As for subtitle language that’s something that’s existed since the beginning of language detection in Sonarr that we need to address (back from when subtitles were often hard coded).

**Comment by Syanelys** [comment]
Indeed, that was the repack/proper setup by default.

I switched to "Do not prefer" and it works like a charm.

Sorry for having wasted your time and thanks for the explanations.
Hope this can help future users :)
