### ISSUE TITLE
Not Getting TV Show data

### ISSUE THREAD

**Issue by one4one141** [Sonarr/Sonarr#3622]
Had a few shows that are not dragging the show info correctly i.e missing seasons or episodes.

Example - 

Show "A" is showing on Sonarr as only having 2 seasons but on IMDB/Netflix showing 4 seasons. The seasons have aired and are available to download just not through Sonarr.

Has now happened on multiple shows.

Version - 3.0.3.717
Mono Version - 6.4.0.198
Operating System: MacOS 10.14.6 (18G3020)

**Comment by M0UL** [comment]
the shows data is coming from thetvdb.com.  so if it is not updated, you should check there.  make sure it has English data on the site.

**Comment by markus101** [comment]
See: https://forums.sonarr.tv/t/important-zero-episodes-and-old-episodes-reappearing-as-monitored-and-potentially-downloaded-unintentionally/25023

**Comment by one4one141** [comment]
Thanks

It was thetvdb.com missing seasons from 4 TV Shows I checked.

**Comment by reloxx13** [comment]
tvdv decided to seperate

2 seasons which gets grabbed
![grafik](https://user-images.githubusercontent.com/14855001/78184584-02c45c80-746a-11ea-8617-9c837994cbcc.png)

netflix 4 seasons
![grafik](https://user-images.githubusercontent.com/14855001/78184664-238cb200-746a-11ea-8daa-6f74de3e9a7e.png)
