### ISSUE TITLE
Running Sonarr v2 install after v3 causes it to be installed in v3 directory

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#3623]
**Describe the bug**
Install location is shared between the installers.

So running v3 installer, followed by v2 installer messes up the directory.

**Comment by bakerboy448** [comment]
@Taloth  @markus101  short of updating v2 and adding a check, I'm not sure if there is much to do here?

**Comment by markus101** [comment]
yeah, alternatively they can uninstall before installing, I don't see us fixing this before v3 releases.
