### ISSUE TITLE
Release not match

### ISSUE THREAD

**Issue by p3s** [Sonarr/Sonarr#3624]
**Describe the bug**

Sonarr não detecta corretamente o nome do seriado/episodio  mesmo estando correto
Sonarr does not correctly detect the name of the series / episode even if it is correct

**Screenshots**

![image](https://user-images.githubusercontent.com/2353264/76712274-e0a2ae80-66f5-11ea-926d-137d99704053.png)

**Logs**
`https://pastebin.com/Kfv24QnB

20-3-15 23:41:11.6|Debug|NzbSearchService|Total of 1 reports were found for [Gold Rush : S10E01] from 1 indexers
20-3-15 23:41:11.6|Debug|NzbSearchService|Setting last search time to: 3/15/2020 10:41:11 PM
20-3-15 23:41:11.6|Info|DownloadDecisionMaker|Processing 1 releases
20-3-15 23:41:11.6|Debug|DownloadDecisionMaker|Processing release 'Gold Rush: Alaska 2010 S10E01 1080p HDTV H.264 AAC Dublado ' from 'BJJAckett'
20-3-15 23:41:11.6|Debug|Parser|Parsing string 'Gold Rush: Alaska 2010 S10E01 1080p HDTV H.264 AAC Dublado '
20-3-15 23:41:11.6|Debug|Parser|Episode Parsed. Gold Rush Alaska 2010 - S10E01 
20-3-15 23:41:11.6|Debug|Parser|Language parsed: English
20-3-15 23:41:11.6|Debug|QualityParser|Trying to parse quality for Gold Rush: Alaska 2010 S10E01 1080p HDTV H.264 AAC Dublado 
20-3-15 23:41:11.6|Debug|Parser|Quality parsed: HDTV-1080p v1
20-3-15 23:41:11.6|Debug|Parser|Release Group parsed: 
20-3-15 23:41:11.6|Debug|ParsingService|No matching series Gold Rush Alaska 2010
20-3-15 23:41:11.6|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:41:11.6|Info|EpisodeSearchService|Episode search completed. 0 reports downloaded.

20-3-15 23:45:19.3|Debug|NzbSearchService|Total of 16 reports were found for [Game of Thrones : S08] from 1 indexers
20-3-15 23:45:19.3|Debug|NzbSearchService|Setting last search time to: 3/15/2020 10:45:19 PM
20-3-15 23:45:19.3|Info|DownloadDecisionMaker|Processing 16 releases
20-3-15 23:45:19.3|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 720p WEB-DL H.264 AC3 Dual ' from 'BJJAckett'
20-3-15 23:45:19.3|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 720p WEB-DL H.264 AC3 Dual '
20-3-15 23:45:19.3|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.3|Debug|Parser|Language parsed: English
20-3-15 23:45:19.3|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 720p WEB-DL H.264 AC3 Dual 
20-3-15 23:45:19.3|Debug|Parser|Quality parsed: WEBDL-720p v1
20-3-15 23:45:19.3|Debug|Parser|Release Group parsed: 
20-3-15 23:45:19.3|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.3|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.3|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 1080p WEB-DL H.264 AC3 Dual ' from 'BJJAckett'
20-3-15 23:45:19.3|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 1080p WEB-DL H.264 AC3 Dual '
20-3-15 23:45:19.3|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.3|Debug|Parser|Language parsed: English
20-3-15 23:45:19.3|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 1080p WEB-DL H.264 AC3 Dual 
20-3-15 23:45:19.3|Debug|Parser|Quality parsed: WEBDL-1080p v1
20-3-15 23:45:19.3|Debug|Parser|Release Group parsed: 
20-3-15 23:45:19.3|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.3|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.3|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 1080p WEB-DL H.264 E-AC-3 Legendado ' from 'BJJAckett'
20-3-15 23:45:19.3|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 1080p WEB-DL H.264 E-AC-3 Legendado '
20-3-15 23:45:19.3|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.3|Debug|Parser|Language parsed: English
20-3-15 23:45:19.3|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 1080p WEB-DL H.264 E-AC-3 Legendado 
20-3-15 23:45:19.3|Debug|Parser|Quality parsed: WEBDL-1080p v1
20-3-15 23:45:19.3|Debug|Parser|Release Group parsed: 
20-3-15 23:45:19.3|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.3|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.3|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 720p WEB-DL H.264 E-AC-3 Legendado ' from 'BJJAckett'
20-3-15 23:45:19.3|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 720p WEB-DL H.264 E-AC-3 Legendado '
20-3-15 23:45:19.3|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.3|Debug|Parser|Language parsed: English
20-3-15 23:45:19.3|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 720p WEB-DL H.264 E-AC-3 Legendado 
20-3-15 23:45:19.3|Debug|Parser|Quality parsed: WEBDL-720p v1
20-3-15 23:45:19.3|Debug|Parser|Release Group parsed: 
20-3-15 23:45:19.3|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.3|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.3|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 720p WEBRip H.265 AC3/E-AC-3 Dual ' from 'BJJAckett'
20-3-15 23:45:19.3|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 720p WEBRip H.265 AC3/E-AC-3 Dual '
20-3-15 23:45:19.3|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.3|Debug|Parser|Language parsed: English
20-3-15 23:45:19.3|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 720p WEBRip H.265 AC3/E-AC-3 Dual 
20-3-15 23:45:19.3|Debug|Parser|Quality parsed: WEBRip-720p v1
20-3-15 23:45:19.3|Debug|Parser|Release Group parsed: 
20-3-15 23:45:19.3|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.3|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.3|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 1080p WEBRip H.265 AC3/E-AC-3 Dual ' from 'BJJAckett'
20-3-15 23:45:19.3|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 1080p WEBRip H.265 AC3/E-AC-3 Dual '
20-3-15 23:45:19.3|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.3|Debug|Parser|Language parsed: English
20-3-15 23:45:19.3|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 1080p WEBRip H.265 AC3/E-AC-3 Dual 
20-3-15 23:45:19.3|Debug|Parser|Quality parsed: WEBRip-1080p v1
20-3-15 23:45:19.3|Debug|Parser|Release Group parsed: 
20-3-15 23:45:19.3|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.3|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.3|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 720p HDTV x264 AC3 Dual ' from 'BJJAckett'
20-3-15 23:45:19.3|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 720p HDTV x264 AC3 Dual '
20-3-15 23:45:19.3|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.3|Debug|Parser|Language parsed: English
20-3-15 23:45:19.3|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 720p HDTV x264 AC3 Dual 
20-3-15 23:45:19.3|Debug|Parser|Quality parsed: HDTV-720p v1
20-3-15 23:45:19.3|Debug|Parser|Release Group parsed: 
20-3-15 23:45:19.4|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 1080p Blu-ray x264 AC3 Legendado ' from 'BJJAckett'
20-3-15 23:45:19.4|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 1080p Blu-ray x264 AC3 Legendado '
20-3-15 23:45:19.4|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.4|Debug|Parser|Language parsed: English
20-3-15 23:45:19.4|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 1080p Blu-ray x264 AC3 Legendado 
20-3-15 23:45:19.4|Debug|Parser|Quality parsed: Bluray-1080p v1
20-3-15 23:45:19.4|Debug|Parser|Release Group parsed: ray
20-3-15 23:45:19.4|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 720p Blu-ray x264 AC3 Legendado ' from 'BJJAckett'
20-3-15 23:45:19.4|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 720p Blu-ray x264 AC3 Legendado '
20-3-15 23:45:19.4|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.4|Debug|Parser|Language parsed: English
20-3-15 23:45:19.4|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 720p Blu-ray x264 AC3 Legendado 
20-3-15 23:45:19.4|Debug|Parser|Quality parsed: Bluray-720p v1
20-3-15 23:45:19.4|Debug|Parser|Release Group parsed: ray
20-3-15 23:45:19.4|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 1080p Remux H.264 AC3/DTS Dual ' from 'BJJAckett'
20-3-15 23:45:19.4|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 1080p Remux H.264 AC3/DTS Dual '
20-3-15 23:45:19.4|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.4|Debug|Parser|Language parsed: English
20-3-15 23:45:19.4|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 1080p Remux H.264 AC3/DTS Dual 
20-3-15 23:45:19.4|Debug|Parser|Quality parsed: Bluray-1080p Remux v1
20-3-15 23:45:19.4|Debug|Parser|Release Group parsed: 
20-3-15 23:45:19.4|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 2160p Remux H.265 TrueHD Dual ' from 'BJJAckett'
20-3-15 23:45:19.4|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 2160p Remux H.265 TrueHD Dual '
20-3-15 23:45:19.4|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.4|Debug|Parser|Language parsed: English
20-3-15 23:45:19.4|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 2160p Remux H.265 TrueHD Dual 
20-3-15 23:45:19.4|Debug|Parser|Quality parsed: Bluray-2160p Remux v1
20-3-15 23:45:19.4|Debug|Parser|Release Group parsed: 
20-3-15 23:45:19.4|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 1080p Blu-ray H.264 AC3 Dual ' from 'BJJAckett'
20-3-15 23:45:19.4|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 1080p Blu-ray H.264 AC3 Dual '
20-3-15 23:45:19.4|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.4|Debug|Parser|Language parsed: English
20-3-15 23:45:19.4|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 1080p Blu-ray H.264 AC3 Dual 
20-3-15 23:45:19.4|Debug|Parser|Quality parsed: Bluray-1080p v1
20-3-15 23:45:19.4|Debug|Parser|Release Group parsed: ray
20-3-15 23:45:19.4|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 1080p BRRip x265 AC3/AAC Dual ' from 'BJJAckett'
20-3-15 23:45:19.4|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 1080p BRRip x265 AC3/AAC Dual '
20-3-15 23:45:19.4|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.4|Debug|Parser|Language parsed: English
20-3-15 23:45:19.4|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 1080p BRRip x265 AC3/AAC Dual 
20-3-15 23:45:19.4|Debug|Parser|Quality parsed: Bluray-1080p v1
20-3-15 23:45:19.4|Debug|Parser|Release Group parsed: 
20-3-15 23:45:19.4|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 480p DVD9 MPEG-2 AC3 Dual ' from 'BJJAckett'
20-3-15 23:45:19.4|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 480p DVD9 MPEG-2 AC3 Dual '
20-3-15 23:45:19.4|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.4|Debug|Parser|Language parsed: English
20-3-15 23:45:19.4|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 480p DVD9 MPEG-2 AC3 Dual 
20-3-15 23:45:19.4|Debug|Parser|Quality parsed: Raw-HD v1
20-3-15 23:45:19.4|Debug|Parser|Release Group parsed: 
20-3-15 23:45:19.4|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 480p DVD5 MPEG-2 AC3 Dual ' from 'BJJAckett'
20-3-15 23:45:19.4|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 480p DVD5 MPEG-2 AC3 Dual '
20-3-15 23:45:19.4|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.4|Debug|Parser|Language parsed: English
20-3-15 23:45:19.4|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 480p DVD5 MPEG-2 AC3 Dual 
20-3-15 23:45:19.4|Debug|Parser|Quality parsed: Raw-HD v1
20-3-15 23:45:19.4|Debug|Parser|Release Group parsed: 
20-3-15 23:45:19.4|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.4|Debug|DownloadDecisionMaker|Processing release 'Game of Thrones 2011 S08 1080p Remux H.264 AC3/DTS Legendado ' from 'BJJAckett'
20-3-15 23:45:19.4|Debug|Parser|Parsing string 'Game of Thrones 2011 S08 1080p Remux H.264 AC3/DTS Legendado '
20-3-15 23:45:19.4|Debug|Parser|Episode Parsed. Game of Thrones 2011 - Season 08 
20-3-15 23:45:19.4|Debug|Parser|Language parsed: English
20-3-15 23:45:19.4|Debug|QualityParser|Trying to parse quality for Game of Thrones 2011 S08 1080p Remux H.264 AC3/DTS Legendado 
20-3-15 23:45:19.4|Debug|Parser|Quality parsed: Bluray-1080p Remux v1
20-3-15 23:45:19.4|Debug|Parser|Release Group parsed: 
20-3-15 23:45:19.5|Debug|ParsingService|No matching series Game of Thrones 2011
20-3-15 23:45:19.5|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
20-3-15 23:45:19.5|Info|SeasonSearchService|Season search completed. 0 reports downloaded.
20-3-15 23:45:19.8|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
20-3-15 23:45:20.7|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
20-3-15 23:45:21.0|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
`

**System Information**
 - Sonarr Version:
    3.0.3.729
Package Version
    3.0.2
- .net Framework (Windows) or mono (macOS/Linux) Version:
    6.8.0.105

 - Operating System:
Linux Ubuntu 18 LTS

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
Looks like an alias is required, see the FAQ for information on how to request one.
