### ISSUE TITLE
Error occurred while executing task ProcessMonitoredDownloads

### ISSUE THREAD

**Issue by anthonws** [Sonarr/Sonarr#3625]
Bug:
"Error occurred while executing task ProcessMonitoredDownloads"
Sonarr not able to move downloaded files to destination folder

Logs:
https://pastebin.com/aXjKx8B4

System Information:
 - Sonarr Version: 3.0.3.712 (phantom-develop)
 - Operating System: Windows 10

**Comment by markus101** [comment]
This was fixed almost 2 weeks ago, you need to update.

Previous issue: https://github.com/Sonarr/Sonarr/issues/3602
