### ISSUE TITLE
Cannot add series that is on TVDB but not on skyhook.sonarr.tv

### ISSUE THREAD

**Issue by MLWeber** [Sonarr/Sonarr#3626]
Hi,

I am having trouble adding a TV show. When searching for the title or via tvdb:84829 sonarr says that there are no results. However, I can access the show on TVDB just fine: https://www.thetvdb.com/series/84829

**Logs**
```
[GET] http://skyhook.sonarr.tv/v1/tvdb/shows/en/84829: 404.NotFound
{"message":"NotFound","description":"thetvdb.com does not have a series with the tvdbid 84829, it may have been removed."}
```

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Centos 7, docker image: linuxserver/sonarr
 - mono Version: 5.20.1.34

**Comment by markus101** [comment]
See: https://github.com/Sonarr/Sonarr/issues/3415
