### ISSUE TITLE
Cannot add new Root folder to Sonarr v3.0.3.654

### ISSUE THREAD

**Issue by JimboJamez** [Sonarr/Sonarr#3628]
**Describe the bug**
After deleting my existing root folder from Sonarr I am trying to add a new one, but am not able to. The directory can be found, but when selecting 'OK' from the screen, it is disappearing but not saving my settings. This also occurs when adding a new series and selecting the directory via the 'Add New Path' option.

I have restarted the application multiple times but this has not resolved anything.

There are no errors logged either.

**Screenshots**
![image](https://user-images.githubusercontent.com/25968238/76924927-fef1ef80-692b-11ea-8dff-feda95d3e997.png)

![image](https://user-images.githubusercontent.com/25968238/76924996-2943ad00-692c-11ea-9564-cd95597afe7a.png)

**Logs**
No errors are being logged.

**System Information**

 - Sonarr Version: 3.0.3.654
 - Operating System: Windows 10
 - .net Framework (Windows)

**UI Bugs:**
 - OS: Windows
 - Browser: Chrome, Edge & Firefox
 - Version: All current version

**Additional context**

If this can't be resolved, is there any way of setting this manually in a config file?

**Comment by markus101** [comment]
Please use the forums or subreddit for support.
