### ISSUE TITLE
Feature Request: Add a Time Interval to the Webhooks Connections Options

### ISSUE THREAD

**Issue by tkdrob** [Sonarr/Sonarr#3630]
I am looking to have some way of knowing when my vpn goes down by getting a notification on my Discord. This is how I envision it working:

I would like to have an option to make Sonarr ping a webhook address every 10 minutes or so, most likely to healthchecks which is a cron job monitor. The idea is to have healthchecks alert me on Discord when it fails to here from Sonarr in a timely manner. 

Does anyone here know of a better way to do this?

Thanks

**Comment by markus101** [comment]
This isn't something we'd add to Sonarr. I'm not aware of a solution that would do this for you either.
