### ISSUE TITLE
Media file resolution not updating

### ISSUE THREAD

**Issue by tyhawk** [Sonarr/Sonarr#3633]
**Describe the bug**
Recently I've decided to save my media files with a resolution of 720p in stead of 576p. I've replaced a number of files with a higher resolution version, but Sonarr doesn't seem to pick up the new files and the new resolution, even though I've overwritten the old files.

If i completely remove the series and re-add it, the proper resolution is detected for all files. But simply scanning the files, automatically and manually doesn't update the resolution (stays on [SD] in stead of being updated to [HDTV-720p].

**Logs**
No errors in the logging (or any other clue pointing towards this issue)

**System Information**
 - Sonarr Version: 3.0.3.728
 - Operating System: Linux / Docker (linuxserver container)

**Additional context**

**Comment by markus101** [comment]
If the file name is the same then Sonarr won't reprocess the file. If Sonarr imports the files from the download client or using Manual Import then Sonarr will know the file changed and update the information during the import.
