### ISSUE TITLE
SSL crashes Sonarr

### ISSUE THREAD

**Issue by boekhold** [Sonarr/Sonarr#3636]
**Describe the bug**
After configuring SSL, Sonarr crashes on each SSL incoming connection

**Logs**
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/4360544/sonarr.txt)

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Linux Mint 19.2 (based on Ubuntu 18.04)
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 4.6.2.7+dfsg-1ubuntu1

**Additional context**
I could call this issue "don't know how to configure SSL in Sonarr", but I think I've done everything right and it's not working.

1. Got a certificate from Let's Encrypt. This certificate is valid, I've used it with other apps as well.
2. Converted the Let's Encrypt certificate/key to a PKCS#12 file:

```
openssl pkcs12 -export -out ~/certificate.pfx \
    -inkey /etc/letsencrypt/live/myhostname.no-ip.org/privkey.pem \
    -in /etc/letsencrypt/live/myhostname.no-ip.org/cert.pem \
    -certfile /etc/letsencrypt/live/myhostname.no-ip.org/chain.pem
```

3. Load this into the Mono environment: `httpcfg -add -port 9898 -p12 ~/certificate.pfx -pwd 'thepassword'`
3a. (I tried with separate CERT file and PVK key file as well, doesn't seem to make any difference)
4. Load CA certs into Mono environment: `yes "yes" | mozroot --import --quiet`
5. Flip on SSL in Sonarr, give 9898 as the port, restart

This produced the Stack Trace in the attached file for every attempted HTTPS connection. I tried with:

- Firefox: `Error code: SSL_ERROR_RX_MALFORMED_SERVER_HELLO`
- Chrome: `ERR_SSL_PROTOCOL_ERROR`
- Edge Chromium: `ERR_SSL_PROTOCOL_ERROR`
- Internet Explorer: this one is weird, it tells me that my site needs **my** (the browser user) certificate

Got the exact same issue with Radarr as well, which of course isn't surprising considering the shared code-base.

**Comment by markus101** [comment]
mono didn't previously (and I assume still doesn't) utilize intermediate certificates on the server side, this may have changed in mono 5+.

> Mono 4.6.2.7

This version of mono is pretty ancient, 3.5 years old roughly, it's time to upgrade to 5.20 (the last v5 release), whether or not it fixes your issue.

Our recommendation is to use a reverse proxy for secure connections to Sonarr. If you want to troubleshoot further after upgrading mono please open a thread on the forums. We don't have plans to fight mono and it's http.ssy implementation, but have plans to work on secure connections more when we change the web server.

**Comment by boekhold** [comment]
What about Mono 6.8.0 Stable (6.8.0.105)? That's the version directly available for download on the Mono-Project web site...

**Comment by markus101** [comment]
Mono 6 changed disk access, if you're using Sonarr to read/write to SMB you definitely want to avoid it, beyond that YMMV.

**Comment by boekhold** [comment]
> Mono 6 changed disk access, if you're using Sonarr to read/write to SMB you definitely want to avoid it, beyond that YMMV.

Don't use SMB here. So far things look OK. It certainly fixed the SSL issue!
