### ISSUE TITLE
Run script when creating/adding new show

### ISSUE THREAD

**Issue by Halfwalker** [Sonarr/Sonarr#3637]
Like many others, I use ZFS as a backend storage system.  The overall "TV" dataset is getting awfully large and unwieldy, especially with snapshots.  Deleting a 30G show leaves that data behind in snapshots until they age out, taking up space.

Ideally, it would be good to create a dataset per show.  That would reduce the size of the datasets, and more importantly, the snapshots.  Deleting a show would remove the whole dataset plus its snapshots, freeing up much more space.  Of course the onus is on the user to be **sure** s/he wants to remove the show ...

**So I'm looking for a script hook in the "Add series" code path, right when the _"mkdir /path/series_name"_ would be executed.  That would enable one to do any prep-work required to create the series directory.**

If the script were passed the series name, path and perhaps a few other parameters, maybe in the environment like Custom Scripts, that would work.  That would enable one to do 

`zfs create -o mountpoint=/media/TV/American\ Gods   tank/TV/American_Gods`

To get fancy sonarr might pass in both the raw series name (American Gods) as well as a safe/clean directory name (American_Gods), removing unsafe chars, replacing spaces/etc with _   But that's not really necessary - one can do whatever char-munging in the script itself.

Right now I'm starting to do this all manually.  Once the series has been added, I check the path/series_name.  Then I move it aside, create a new dataset with the same mountpoint and safe dataset_name, rsync the data over, and remove the original dir.  From then on, it all works fine.  I'm in the process of converting all the series into individual datasets.

**Comment by markus101** [comment]
If this is something we end up doing, I think we'd follow the trend of post operation events, so after the series is added. In your case you'd get the event, create your dataset, move the series folders then tell Sonarr of the new location via the API.

**Comment by Halfwalker** [comment]
Yup, that would work fine.  Sounds like the destination path would be a holding/scratch location.  I'm guessing that the series directory would be created, THEN the event fires to trigger the script.  That in turn would use parameters or env to pick up the series name and do the things to create the dataset and move whatever was in the scratch series location over.  Then, as you say, an API call to update the series in Sonarr with the new location.  Cool.

**Comment by markus101** [comment]
> I'm guessing that the series directory would be created, THEN the event fires to trigger the script. 

It'd be created if `Create Empty Series Folders` was enabled, otherwise it'd give you a path to a folder that wasn't there yet, but either way that shouldn't be a problem.

**Comment by keldian** [comment]
Still no plans for this? Seems strange for a "on series add" trigger to be missing when "on series delete" one exists.

**Comment by almightiest** [comment]
I would love to see this as well. Would be very useful for some initial set up tasks I want to run.

**Comment by bakerboy448** [comment]
Radarr Commit to backport - that added this for Movies https://github.com/Radarr/Radarr/commit/f890aadffa5ae579bcf65abdcf3e3948837084a9

**Comment by pentago** [comment]
Would love this trigger!
