### ISSUE TITLE
Twitter connect does not work

### ISSUE THREAD

**Issue by lundejd** [Sonarr/Sonarr#3638]
When setting up the Twitter connect with consumer key, secret, access token and secret you get a prompt:

Using Direct Messaging is recommended, or use a private account.

The same procedure works in Radarr

https://share.getcloudapp.com/X6uzn9zP

**Logs**
I can provide as necessary.

**System Information**

 - Sonarr Version: 2.0.0.5344 - Mar 13 2020
 - Operating System: macOS
 - Mono: 5.18.0.240

I had twitter working just fine but then Twitter banned my account so I had to switch to a new one with new API info.   Radarr worked just fine, Sonarr is complaining.

**Comment by markus101** [comment]
Please use the forums for support/questions.

That's a warning, not an error, it won't prevent you from saving or using it.

**Comment by lundejd** [comment]
No wonder it works for Radarr and not sonarr :(.  Nobody cares...

Sent from my iPhone

On Mar 21, 2020, at 5:59 PM, Mark McDowall <notifications@github.com> wrote:

﻿

Please use the forums for support/questions.

That's a warning, not an error, it won't prevent you from saving or using it.
