### ISSUE TITLE
Newbie problem with mounted disk

### ISSUE THREAD

**Issue by pikachukaki** [Sonarr/Sonarr#3642]
Im giving a shot to linux and im trying to install Radarr but i can't make the app see the NTFS disk that i have my movies in windows.
I search everywhere but im not able to find a solution.
The NTFS disk is mounted at /run/media/name/ but radarr said "Folder is not writable by user radarr"
### *THE PROBLEM IS THE SAME AS RADARR*
Any help? Thanks
![Screenshot_20200323_042600](https://user-images.githubusercontent.com/3009586/77337228-4bc13600-6d31-11ea-9c27-464046ffd740.png)
![Screenshot_20200323_042701](https://user-images.githubusercontent.com/3009586/77337236-4d8af980-6d31-11ea-8b71-0114c6421edf.png)

**Comment by markus101** [comment]
Please use the forums or subreddit for supprt/questions.
