### ISSUE TITLE
Sonnar not importing all seasons

### ISSUE THREAD

**Issue by lsaadeh** [Sonarr/Sonarr#3647]
**Describe the bug**
Sonnar is not correcting importing season packs, rather just import the first season in the pack.
e.g importing season 1 but not importing season 2-4.

**Screenshots**
[s1 imported s2-4 not imported](https://imgur.com/iqQsmTv)
[s1-4 marked as existing and unable to import](https://imgur.com/Lr07ClC)

**Logs**
[Link to debug or trace log files.](https://easyupload.io/0otuev)

**System Information**

 - Sonarr Version: Docker linuxserver/sonarr:preview
 - Operating System: ubuntu 16.04

**Comment by markus101** [comment]
You need to add the series to Sonarr, then import the episode files via manual import (either in Activity: Queue or Wanted: Missing). You're currently using the series import, which is used to import existing, already sorted series.
