### ISSUE TITLE
Interactive Search UI overlay error if Status column is updated in background

### ISSUE THREAD

**Issue by emilbes** [Sonarr/Sonarr#3649]
**Describe the bug**
Running multiple Interactive Searches on a series in quick succession sometimes leads to a UI error, as displayed in the screenshots below. It looks like updating the `Status` column in the background interferes with the Search panel overlay

**Screenshots**
### Example 1
a) "loading" gif before the `Status` column updates in the background
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/49895675/77948106-b9151f80-7279-11ea-8a19-4b438776f9c9.png">

b) Status column updated in background, circular "loading" gif disappears from UI
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/49895675/77947840-5d4a9680-7279-11ea-9ccd-a146677082a3.png">

### Example 2
If results are already loaded in search popup (ie: past the loading gif), then this error page appears as soon as the `Status` column is updated in the background
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/49895675/77948476-51ab9f80-727a-11ea-8430-9e6be55556b2.png">

**Logs**
Couldn't find any error in the log, operation seems normal other than the UI error

**System Information**
Synology DS918+
Version
    3.0.3.748
Package Version
    3.0.3.748-ls1 by linuxserver.io
Mono Version
    5.20.1.34

**UI Bugs:**
 - OS: macOS 10.15.4
 - Browser: Firefox 74

**Comment by markus101** [comment]
We'll need the error from the UI, which is collapsed by default when the error is shown, click the black triangle to expand it.

**Comment by emilbes** [comment]
Sorry didn't see that originally. Also the error only seems to trigger when the `Status` icon switches from the bookmark shape to either the "download cloud" or the progress bar icons

```
TypeError: a is undefined

    in iG
    in td
    in a
    in tr
    in GM
    in a
    in tbody
    in a
    in table
    in div
    in a
    in jM
    in div
    in hz
    in a
    in f
    in a
    in f
    in div
    in r
    in div
    in u
    in r
    in div
    in div
    in a
    in a
    in div
    in sO
    in a
    in a
    in f
    in a
    in div
    in div
    in div
    in div
    in ForwardRef
    in ForwardRef
    in a
    in a
    in td
    in a
    in a
    in f
    in tr
    in GM
    in a
    in f
    in tbody
    in a
    in table
    in div
    in a
    in jM
    in div
    in div
    in div
    in a
    in a
    in f
    in div
    in div
    in div
    in div
    in div
    in t
    in a
    in a
    in f
    in Connect(a)
    in div
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in a
    in UN
    in a
    in a
    in f
    in a
    in f
    in t
    in t
    in a
    in u9
    in div
    in div
    in a
    in a
    in f
    in withRouter(Connect(a))
    in t
    in n
    in i
    in f
    in t
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in e

```

**Comment by markus101** [comment]
I haven't been able to reproduce, but I think I found at least a related issue which will be fixed in an upcoming commit.

**Comment by emilbes** [comment]
That fixed the problem, can't reproduce it anymore thanks!
