### ISSUE TITLE
Manual Importer can not handle the character "!"

### ISSUE THREAD

**Issue by leftovernick** [Sonarr/Sonarr#3650]
## Bug Report
I had "Penn & Teller's Bullshit!" in my downloads folder. I was unable to load completed files and had to load each folder individually until I found the culprit. Any folder containing a file with a "!" cannot be read in Sonarr (it can in binhex-Radarr though). I have to go individually rename each file.

### System Information/Logs

**Sonarr Version:**
2.0.0.5344
**Operating System:**
UNRAID
**Browser (for UI bugs):**
Safari, Chrome
**.net Framework**
Mono 6.4.0

**Comment by markus101** [comment]
`!` should have no effect, but without logs it's impossible to say what might've gone wrong. This definitely isn't an issue in v3 though.

![image](https://user-images.githubusercontent.com/413544/77973795-2f317a80-72aa-11ea-9c58-58bdf4bbe495.png)
