### ISSUE TITLE
TVDB refresh not working for 1 show

### ISSUE THREAD

**Issue by mraniki** [Sonarr/Sonarr#3652]
**Describe the bug**
I updated data (in english) for 1 tv show https://www.thetvdb.com/series/305992 however the data doesn't refresh in sonarr after 5 hours.

**Screenshots**

![Screen Shot 2020-03-31 at 10 36 42 AM](https://user-images.githubusercontent.com/8766259/78038999-86336000-733b-11ea-89dd-f023ca3242e9.png)

![Screen Shot 2020-03-31 at 10 36 23 AM](https://user-images.githubusercontent.com/8766259/78038959-7b78cb00-733b-11ea-8085-1ea426890462.png)

**Logs**
20-3-31 12:32:31.3|Info|RefreshSeriesService|Updating Murders inâ€¦
20-3-31 12:32:31.3|Info|RefreshEpisodeService|Starting episode info refresh for: [305992][Murders inâ€¦]
20-3-31 12:32:31.4|Debug|EpisodeAddedService|No new episodes, skipping search
**System Information**

Version
    3.0.3.748
Package Version
    3.0.3.748-ls1 by linuxserver.io
Mono Version
    5.20.1.34
 - Operating System:  Ubuntu 18.04

**Comment by markus101** [comment]
It can take more than 24 hours for the cache on TheTVDB's side to expire.

**Comment by mraniki** [comment]
Noted

**Comment by mraniki** [comment]
FYI, Sonarr was refreshed after 36 hours.
