### ISSUE TITLE
Update sonarr.tv so that it's clear what Sonarr does

### ISSUE THREAD

**Issue by mattcoxonline** [Sonarr/Sonarr#3653]
**Describe the problem**
One of my friends told me to look up Sonarr but didn't really tell me what it did. I found the website sonarr.tv and still had no idea what it does. That's not because I'm an idiot (though that is also debatable) but because your website tells me these vague things about Sonar:

- Works great and looks even better doing it.
- Notifications and fully customizable quality profiles.
- Multiple Series views.
- Frequent updates. See what's new without leaving the comfort of the app.

Your website doesn't tell me what Sonarr does. I had to go to Twitter where I see:

- I am a PVR for newsgroup and torrent users.
- I watch for new episodes of your favorite shows to download, sort and rename.

**Describe any solutions you think might work**
The first point on Twitter is a bit techy. I would avoid using PVR because I still don't really know what that means. But the second point is great. And super useful to describe what Sonarr is. 

_Sonarr scans the internet for new episodes of your favourite TV shows and automatically downloads them._

It would be great if the carousel on the top of sonarr.tv was replaced with a header that hit straight to the point about what the software does and a download button.

**Comment by markus101** [comment]
This is something we've discussed previously and the site is intentionally a bit vague, but it's overly so currently.

Twitter shouldn't be the only source for finding out what it does, but if twitter is too technical then Sonarr itself will be too technical.

We'll continue to discuss and update sonarr.tv
