### ISSUE TITLE
Moving files using torrent client or importing from the same series directory

### ISSUE THREAD

**Issue by skobkin** [Sonarr/Sonarr#3654]
**Describe the problem**
For now starting to use Sonarr with already managed manually media library is not ideal.
I was using Transmission to download separate episodes or whole seasons manually, but I downloaded the directly to the target directory instead of using some intermediate "downloads" directory.

For example:

My shows media library: `/mnt/public/video/series`.

Then if I want to download new episode X from season Y of series Z, I'll just add some torrent to the transmission and set it to download directly to `/mnt/public/video/series/Z/season_Y`.

And it works perfectly, especially with Emby, Plex or something like them. Transmission also keeps seeding from the target directory without any problems.

But if I start to use Sonarr with such library I'll get intermediate "download" directory which I don't need. And even if I choose to use hardlinks, it'll show files in the default transmission download directory littering it.

**Describe any solutions you think might work**

* Support moving and renaming files using torrent client. Many torrent clients support it.

* Also probably supporting not moving downloading files at all and importing them with current path if they're in the correct series directory. Not sure if it's easy or possible with current architecture.

**Additional context**

Not sure if it's related but for me Sonarr for some reason not importing already downloaded episodes/seasons which are still in the transmission. It's showing status 'downloading' and that it's 100% but doing nothing with it. It also shows that already downloaded manually files can't be imported because they 'has the same size as existing files'.

![sonarr_not_importing_downloaded](https://user-images.githubusercontent.com/967576/78073951-799a2080-73aa-11ea-93fd-2ab840c77a4f.png)
![sonarr_not_importing_downloaded2](https://user-images.githubusercontent.com/967576/78073957-7a32b700-73aa-11ea-9822-66756c938dd1.png)

Probably I should file a separate bug report about it.

P.S. This issue is probably related to #744.

**Comment by markus101** [comment]
The file is already in Sonarr, so it doesn't need to import anything. Disabling `Completed Download Handling` should be all you need to do for the manually downloaded files.

We don't have plans to support downloading directly to the series folder, but you can probably achieve that behaviour with a Custom Script or Webhook On Grab event.

**Comment by skobkin** [comment]
> Disabling Completed Download Handling should be all you need to do for the manually downloaded files.

But after disabling it Sonarr ceased to process even downloads it added itself.
So now I have have some downloads in Transmission's default directory which isn't useful without manual moving.

Can I allow Sonarr processing downloads which were added only by itself? Isn't that what category in download client settings for? It will not solve the problem of two references to one file from different directories, but at least Sonarr will do it's work completely and I will not get many strange episode statuses from previous manual downloads. Am I right?

**Comment by markus101** [comment]
Using a category (which is a folder in Transmission) or a specific directory to download to will allow Sonarr to filter out downloads not in a subfolder named to match the category or not in a subfolder of the specified directory.

For example if you set the category to `sonarr-tv` it'd skip anything set to download to `/mnt/public/video/series` because there isn't a subfolder named `sonarr-tv` in that path. Similarly for directory setting it to download to `/mnt/public/video/series-downloads` would reject anything in `/mnt/public/video/series`.
