### ISSUE TITLE
Ability to filter Wanted > Cutoff Unmet by Quality

### ISSUE THREAD

**Issue by danyal** [Sonarr/Sonarr#3655]
**Describe the problem**
If you have a large collection, it's very hard to weed through the cutoff unmet tab and find shows that you want to manually investigate because they aren't at the right quality. 

**Describe any solutions you think might work**
Add a filter for quality on the page. Ability to sort the status column could also work.

**Comment by markus101** [comment]
Closing in favour of https://github.com/Sonarr/Sonarr/issues/3657
