### ISSUE TITLE
qBittorrent rechecking cause Sonarr copying file too early

### ISSUE THREAD

**Issue by Risu** [Sonarr/Sonarr#3658]
**qBittorrent settings:** qBittorrent Web -> Options -> Advanced -> Recheck torrent on completion [On]
In qBittorrent WebGUI statuses are going like that: downloading -> checking -> completed
_[I fixed my config regarding to discord discussion]_

**Sonarr version**: Sonarr 3.0.3.750 Windows 10 x64

**Problem:**
When status changing to "checking" Sonarr is firing EpisodeFileMovingService and DiskTransferService to make copy of unchecked file in destination.

**Expected behaviour:**
Sonarr should wait for checking to be completed (without checking finalize file could be corrupted on badly network or drive).

**Possible solution:**
In Sonarr/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
Move Line 174 'case "checkingUP":'
to line 199 
(to keep 'item.Status = DownloadItemStatus.Downloading;' instead of 'item.Status = DownloadItemStatus.Completed; item.RemainingTime = TimeSpan.Zero;')

**Comment by markus101** [comment]
This was already done in https://github.com/Sonarr/Sonarr/commit/9702d2e5ad837dc8dad499bde322ccb6b1045ad4

**Comment by Risu** [comment]
Thank you. I was checking only in Sonarr this morning and I didn't notice new commit.
