### ISSUE TITLE
Post-import category breaks remove completed downloads

### ISSUE THREAD

**Issue by ivooc** [Sonarr/Sonarr#3659]
**Describe the bug**
In Settings > Download Client, when adding or editing an existing download client, we have the option to set a category and a post-import category for qBittorrent client. So I have set tv-sonarr as category and tv-sonarr-imported as post-import category. The torrents keep seeding on the post-import category. However, they are not removed when finished seeding (I have configured qBit to pause the torrents once they reach seed ratio 3.00. Completed Download handling is also enabled for import and for remove completed downloads in Sonarr) and I checked the trace log, Sonarr is only checking for tv-sonarr category and never checks for tv-sonarr-imported, so it never removes de downloads. I disabled completed download handling and manually changed a few completed torrent category from tv-sonarr-imported to tv-sonarr and reenabled completed download handling and then Sonarr detected and removed and deleted the files correctly.

**Logs**
https://pastebin.com/qJKNJf5i

**System Information**

 - Sonarr Version: 3.0.3.750
 - Operating System: Windows 10
 - .net Framework: 4.8

**Comment by markus101** [comment]
That's because Sonarr only gets torrents for the original category (filtered in the request to qbit).

Changing the category speeds Sonarr up when fetching items from qbit, which to Sonarr is the only benefit (other's may use it for other reasons). I don't see us handling both cases so likely the fix will just be telling people this is the limitation.

**Comment by ivooc** [comment]
But isn't all that automatic handling one of Sonarr's main objectives? To free the user from manual handle?

Not like this option is a huge deal. I just ended up disabling the post-import category, as the download removal is a more crucial point for me and I would say for the majority of users too.

**Comment by markus101** [comment]
It is, but it’s a limitation of that particular option.
