### ISSUE TITLE
Money Heist ( La Casa De Papel ) episodes listing is wrong [reopen]

### ISSUE THREAD

**Issue by wuast94** [Sonarr/Sonarr#3661]
#2621 all necessary info is in this issue and it should be reopend. Things changed. 

The first thing as seen here is that TVDB offers to Namings:
Aired Order
![image](https://user-images.githubusercontent.com/16965460/78456542-a26d2f00-76a4-11ea-9cdc-8988880e5e37.png)
AND 
Netflix order: 
![image](https://user-images.githubusercontent.com/16965460/78456559-b6b12c00-76a4-11ea-8a1f-318646b0b2e3.png)

and also IMDB should be added as second/failover/choose what you want DB. there are many edge Cases were this makes sense

**Comment by markus101** [comment]
If anything a XEM mapping needs to be added, though I don’t know if it’ll solve this case since part of the issue is the number of episodes in a season changing. You’ll need to discuss with thexem.de on IRC.

IMDB will never be an alternate source, they don’t have a proper API we could use.

**Comment by vistalba** [comment]
@markus101 TheTVDB is listing both versions. Why not just let user select which one they want to use? This information should be available over the api as well?

**Comment by markus101** [comment]
Because that's not actually exposed in their API currently.

**Comment by miniliQuid** [comment]
TVDB is still working hard on their new API (when it was released it was rather bad and buggy I believe). They recently decided to add support for all kinds of different orders to fix issues with shows like money heist, anime and many others.

But like I said they are still working on the API from what I read on some of their forum topics, and they still have many things to fix which also seems to be slow going. Eventually the API should support the different orders, but the API may take a while to catch up to all the progress.

PS: unfortunately IMDB only provides a commercial license API. Discovered that late last year.

**Comment by mytvpro** [comment]
> Because that's not actually exposed in their API currently.

man this show is really getting under my skin. are you saying the netflix order is not exposed the in api? so there is no way to pick up the other 2 seasons ?

**Comment by mytvpro** [comment]
on april 7th, ( in response to some one here?) they said "Flexible season are currently not exposed on the API, but they will be on the v4 API which we are starting to build. Our apologies."

so i guess will keep am eye on when v4 API is released

**Comment by jeff15110168** [comment]
when should we expect v4 api to be released/incorporated into Sonarr and how would that release flow through into existing stable sonarr (2.0.0.5344) vs. beta sonarr (v3 it think?)?

**Comment by mytvpro** [comment]
> when should we expect v4 api to be released/incorporated into Sonarr and how would that release flow through into existing stable sonarr (2.0.0.5344) vs. beta sonarr (v3 it think?)?

I think only tvdb can say when their API will be ready. I think they have only just begun it
