### ISSUE TITLE
Incorrect Request URL (Parsing)

### ISSUE THREAD

**Issue by iot-resister** [Sonarr/Sonarr#3662]
**Describe the bug**
When I search manually or automatically on any indexer I get "No results found`  on a server  w/ version. 5344. This is an exmple of a request url for Devs(2020) S0E01
```
20-4-4 22:09:35.6|Debug|Omgwtfnzbs|Downloading Feed https://rss.omgwtfnzbs.me/rss-search.php?catid=19,20,30&user=(removed)&api=(removed)&eng=1&delay=30&search=Devs+2020 03 05
```

Here is the request with v 5338
```
20-4-5 01:47:51.2|Debug|Omgwtfnzbs|Downloading Feed https://rss.omgwtfnzbs.me/rss-search.php?catid=19,20,30&user=(removed)&api=(removed)&eng=1&delay=30&search=Devs+S01E01
```

When it is run on a server w/ version 
**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: [e.g. 2.0.0.5344]
 - Operating System: Debian
 - 5.20.1.34

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
You set the series type wrong. Set it to Standard, not Daily.

**Comment by iot-resister** [comment]
I'm dumb. I should no better. apologies for wasting your time.
