### ISSUE TITLE
CentOS Stopping Sonarr does not release port Listen

### ISSUE THREAD

**Issue by danner26** [Sonarr/Sonarr#3663]
**Describe the bug**
I have found an issue where when I stop a process on Centos, and then start it again the listen on the port is not removed and I get the port already used error. I have tried changing the port and it still holds the listen when restarting the service (can be found using netstat). 

No process is running anymore, sonarr is shut down and mono is not running anything but the process still has a LISTEN active. Please see the screenshots below. **The mono process seems to go defunct.**

There is also an issue where when the process is running, the UI takes forever to load if it ever does. Most of the time it takes a good 35-50 seconds to load the web page. Please let me know if you need anymore information and I would be happy to supply it.

**Screenshots**
![image](https://user-images.githubusercontent.com/8165027/78559616-af903800-77e2-11ea-80d6-5f3315529d2d.png)
![image](https://user-images.githubusercontent.com/8165027/78559698-d8b0c880-77e2-11ea-994e-6ed197537b95.png)
![image](https://user-images.githubusercontent.com/8165027/78559874-2299ae80-77e3-11ea-8b2d-005fd72f9922.png)

**Logs**
https://pastebin.com/QhknVWYB

**System Information**

 - Sonarr Version: Version 2.0.0.5344
 - Operating System: CentOS Linux 7 (Core)
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12] 
Mono JIT compiler version 6.8.0.105

**Comment by markus101** [comment]
If mono is going defunct there is likely nothing we can do, but we'd need to see trace logs of the shutdown, info level logs won't tell us anything.

**Comment by danner26** [comment]
Sorry about that, I thought using the debug switch with Mono would give that info, but looking closer it appears that isn't very verbose. 
I did some tasks I have been meaning to get around to, fixing jumbo frames as well as some other system optimization/maintenance tasks and all of the machines are running better and more efficient now. While I had high hopes, I was let down. Sonarr is still freezing up, please see this log with the errors:
https://pastebin.com/phu6swmH


Deluge was not running beforehand, which I fixed. Now it is. The error that has been present though this whole time is that one about the already existing partial. Once sonarr gets to this point and throws that error, it seems that it freezes. Any ideas why so?

Mono has not gone defunt yet, once I do a systemctl restart sonarr, that is when mono goes defunt and things start breaking again.

**Comment by danner26** [comment]
Also after the systemctl restart we get the: ConsoleApp: Address already in use. This can happen if another instance....
Which is another main issue highlighted here.

**Comment by danner26** [comment]
Downgrading from mono version 6.8.0.105-0.xamarin.3.epel7 to version 5.20.1.34-0.xamarin.2.epel7 seems to have fixed all of the issues

Besides not being able to upgrade mono, is there any downside of the downgrade of mono versions? also, since the mono version difference is a major version, is that the reason I am having the issue?

**Comment by markus101** [comment]
Mono 5.20 is the version we recommend due to other issues with 6.x. You should be good with it while the kinks are worked out.

This is the first time I’ve heard of this issue with 6.x, but something must have changed.
