### ISSUE TITLE
Activity Queue Shows Blacklisted Releases Until Refreshed

### ISSUE THREAD

**Issue by tkdrob** [Sonarr/Sonarr#3664]
Describe the bug
Whenever I blacklist a release, it shows up at the top of the current activity queue page. Changing the page doesn't make it go away. Only an F5 or clicking one of the other sidebar items removes the phantom item.

To Reproduce
1. Blacklist a release
2. Move page down or page up

Expected behavior
The blacklisted item does not reappear at the top of the list.

Screenshots

Desktop (please complete the following information):

OS: Linux Docker
Browser and Version: Chrome 80
Version 3.0.3.750
Mono Version: 5.20.1.34

**Comment by markus101** [comment]
This will be fixed when this PR lands.

https://github.com/Sonarr/Sonarr/pull/3634
