### ISSUE TITLE
Updated to new beta, all settings gone

### ISSUE THREAD

**Issue by cspencer49519** [Sonarr/Sonarr#3665]
That's it, updated today using the automatic web interface, upon restart all of my settings etc. are gone with no backup.

FreeNAS - Latest
Running inside of iocage jail.

**Comment by Taloth** [comment]
You're not providing any information whatsoever. Please put a bit more effort in it if you wish us to spend our free time.

Also, you don't update _to+ v3 via the sonarr webui, that's not possible. If you did it via some kind of third party UI, then you're posting this in the wrong place entirely.

**Comment by cspencer49519** [comment]
Umm ok. Sonarr v3, updated through the ui to the new phantom-develop branch. Running on latest freenas inside of an iocage jail. What other information can I provide?

**Comment by cspencer49519** [comment]
So I just set everything up again and re-imported everything. I looked at sonarrr this morning, it said there was an update, I updated through the ui, after update everything was gone. If there's any specific information you need I'd be happy to provide it.

**Comment by Taloth** [comment]
Ah, you didn't update to v3 beta, you were already on it and simply updated to a new version. ok.

'all settings gone', what all settings? including series, download clients, profiles? What about System->Events, what's the oldest event?

You checked log files? Including the update log files? To see what happened when.

Sonarr makes periodic backups, include prior to updates. Where are they?

**Comment by cspencer49519** [comment]
Not sure what happened, but I can only relate to my own impatience. After I updated, literally all my settings were missing, no shows, no settings, api key changed etc.. I re-setup everything and just went on about my day. Last night I noticed Sonarr grabbed a show I hadn't monitored when I reconfigured it. Checked this morning, and all my settings are back/the same. I think I might have just not waited long enough?

**Comment by Taloth** [comment]
If you weren't running inside a jail i'd think that you briefly ran it as a different user. We don't provide freenas install options so I don't know how it's normally configured.

If it happens again, check the AppData folder specified in system->about and compare it what you have now. It's the location where the database and logs reside.

For now I'll consider this issue closed.
