### ISSUE TITLE
Does not remove imported episodes

### ISSUE THREAD

**Issue by braunsonm** [Sonarr/Sonarr#3668]
**Describe the bug**
The issue only happens on Transmission from what I can tell on the phantom-develop branch. I do not have the same issue with Usenet.

When transmission finishes downloading an episode and reads "seeding complete", sonarr gets stuck in the activity saying "importing". The logs/events have no mention of the import at all but it does complete successfully. If I manually hit the button to remove the file in the activity window, sonarr removes it properly and detects the new episode imported on the disk properly.

**Logs**
```
20-4-6 19:03:05.0|Info|NzbSearchService|Searching 2 indexers for
20-4-6 19:03:05.8|Info|DownloadDecisionMaker|Processing 53 releases
20-4-6 19:03:06.9|Info|DownloadService|Report sent to Transmission. 
20-4-6 19:03:07.0|Info|EpisodeSearchService|Episode search completed. 1 reports downloaded.
20-4-6 19:07:33.1|Info|RssSyncService|Starting RSS Sync
20-4-6 19:07:34.0|Info|DownloadDecisionMaker|Processing 200 releases
20-4-6 19:07:35.9|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0
```
This is the latest logs from the file.

**System Information**

 - Sonarr Version: 3.0.3.750
 - Operating System: Docker on Synology
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34

**Comment by markus101** [comment]
Please open a thread on the forums for support. At a minimum we’ll need debug logs (the logs you posted are info) of the import, though trace logs will tell us exactly what transmission is telling Sonarr.

Sonarr will only remove torrents that have been paused and the seeding ratio has been met (and Remove is enabled for Completed Download Handling).
