### ISSUE TITLE
Release hashes

### ISSUE THREAD

**Issue by mihaifm** [Sonarr/Sonarr#3669]
Is there a way to verify the downloads from the website?

thanks

**Comment by markus101** [comment]
Sonarr doesn’t utilize or create hashes outside of the torrent hash being used to track a download in a torrent client.

**Comment by Taloth** [comment]
He means our sonarr release on the website.

It's kinda pointless though, because the downloads come from the same server as the hash would come. which would create a false illusion of security.

**Comment by mihaifm** [comment]
You can add the release hashes to github, at least, like a lot of open source projects do:

https://github.com/nzbget/nzbget/releases/download/v21.0/nzbget-21.0.sig.txt

If the website is compromised, this can be detected by checking the signature on github. 

Alternatively, add the release binaries on github as well. It just adds another layer of security.
