### ISSUE TITLE
Specify illegal characters

### ISSUE THREAD

**Issue by tijmenvn** [Sonarr/Sonarr#3670]
**Describe the problem**
Found out Plex's transcoder crashes when there is a "%" in the name. Always used {Episode Title} and not {Episode CleanTitle}. So switched to see if it would remove the "%". Turns out this is not seen as an illegal character, not sure where the list of illegal characters comes from

**Describe any solutions you think might work**
Add an option to add illegal characters, preferable even edit the current list, as ( ) ' " are all characters that haven't bothered me, so I would like to be able to _just_ replace/remove "%"

**Additional context**
If this can be quickly fixed in my case by editing some source file somewhere in sonarr directory, I'd like to know as well

**Comment by markus101** [comment]
Illegal characters are always removed, additional characters are removed when using clean title, but it's not all non-alphanumeric characters.

There is https://github.com/Sonarr/Sonarr/issues/2028 which covers the additional characters not being removed, but at this point there isn't plans to specify which characters will be removed.
