### ISSUE TITLE
Download only one file from season torrent?

### ISSUE THREAD

**Issue by evlo** [Sonarr/Sonarr#3671]
For example for tales from the loop, on trackers i'm on there is 2160p s01 pack, and 1080p s01e01.
I request just to download first ep. to see if I will like the show. I have profile set up to go up to 2160p.

But sonarr only sees the 1080p torrent with single episode while in the ideal world it would set up 2160p s01 one and just got the correct episode file from it.

Is it possible to set up that way?

In this case it is no bother really, but if there sas no s01e01 1080p available I think it would just not get any content, right?

https://github.com/Sonarr/Sonarr/issues/2608
https://github.com/Sonarr/Sonarr/issues/3188 - i think this one is most related
https://github.com/Sonarr/Sonarr/issues/1007

BTW Previously I used flexget, and I think (really not sure) it works that way there, but I like sonarr interface more.

I don't know if qbittorrent and other API even has support for file selection.

**Comment by markus101** [comment]
Sonarr won’t download a season pack if only one episode is monitored or the pack isn’t an upgrade for all episodes.

We don’t have plans to download a season pack in your scenario (or any scenario where less than the full season is wanted). You could manually change that in the client after Sonarr grabs it, but it will trip Sonarr up a bit when it doesn’t import all episodes (at least in the near future that will apply).
