### ISSUE TITLE
Downloads stuck in queue at 100%

### ISSUE THREAD

**Issue by guicha910** [Sonarr/Sonarr#3673]
Hi ! 

I am using Sonarr on my Synology on Docker. I used to use it with transmission on docker, but swapped recently to Download Station (not on docker). On transmission it was running smoothly. After passing to download station, I set the remote path and it's working fine.

But I am facing a problem where downloads are downloaded, imported and renamed, but they stay in queue at 100% with the message : "Downloaded - Importing".

On the monitor tab, all episodes are there, available on my Plex server, but their status is a purple bar with the message "Episode is downloading - 100%".

Refreshing does not change anything. I have no idea how to fix that. No more informations are found in logs. Only rebooting the docker manage to empty the queue.

Queue : 
https://imgur.com/RE3U01j

Monitoring : 
https://imgur.com/feAkZkw

 - Sonarr Version: 3.0.3.750
 - Operating System: DSM 6.2.2-24922 Update 4 
 - mono Version: 5.20.1.34

**Comment by markus101** [comment]
Please open a thread on the forums or subreddit for support.
