### ISSUE TITLE
Copy instead of hard link when permission is granted by group

### ISSUE THREAD

**Issue by dnut** [Sonarr/Sonarr#3675]
I configured Sonarr to use its own user but the same group account that owns all of the download and target directories and files on the same ext4 filesystem. The download client uses creates files using the same group but different user. Sonarr is configured to use hard links, but instead it copies the files. It will only hard link the files if I run Sonarr as the same user who owns the downloaded files. This should not be necessary since the group account has read and write access to every relevant file.

**System Information**
 - Sonarr Version: 2.0.0.5344
 - Operating System: Linux 5.5.10
 - mono Linux Version: 6.4.0.198

**Comment by markus101** [comment]
The log files will tell you why it failed to hardlink. Being the owner is not a requirement for hardlinking, but write access is I believe.

Please use the forums or subreddit for support/questions.

**Comment by dnut** [comment]
Wow, what a dismissive response. You give me zero credit and just assume the software is perfect without a second thought. 

This is a bug report. I wasn't asking a question or looking for support. I got it to work the way I want by switching the user. That was the only change I made. It already had write access through group permissions, as I said.

**Comment by markus101** [comment]
Sonarr doesn't make a differentiation between owner and group for importing via a hardlink (it's not even something we do directly in our code, it's passed to the framework to attempt to do it. We need debug logs at a minimum for bug reports and permissions making up a reasonable chunk of "bugs" or people seeking help. If permissions gave the group read and write access to the source and destination of the failed hardlink then downgrading to mono 5.20 might help, mono 6 introduced a lot of changes to disk access.

**Comment by Taloth** [comment]
> mono 6 introduced a lot of changes to disk access.

Not for this, mono passes the call straight into libc link function. The OS is saying no.
