### ISSUE TITLE
Manually add series data to Sonarr

### ISSUE THREAD

**Issue by BigJazzz** [Sonarr/Sonarr#3676]
**Describe the problem**
I am unable to manage the DiC-dubbed Sailor Moon through Sonarr (also possibly the VIZ dub however I haven't tried). The TVDB doesn't have it listed, and they refuse to allow me to make a separate show to support the data. I can foresee other shows having this problem, especially anime dubs.

**Describe any solutions you think might work**
A local database/tables in an existing database Sonarr references that we can input basic information, such as series title, numbers of seasons/episodes, and episode titles.

**Additional context**
This has been suggested in #2831 and hit on the head, however I believe this is a useful, basic tool to have when the data provider being used refuses to assist in this. I also seem to only be able to find the specific DiC-dubbed series info on IMDb.

**Comment by markus101** [comment]
Our position hasn't changed for this, we do not have plans for manual series in Sonarr.

This sounds like something TVDB's alternate numbering may be able to support, but that isn't of much use to Sonarr currently since they don't expose it.
