### ISSUE TITLE
Manual downloads automatically importing as the wrong season

### ISSUE THREAD

**Issue by Rojikku** [Sonarr/Sonarr#3677]
**Describe the bug**
Many times, and even right now, I choose to find download links manually because Sonarr doesn't always find the ones I like. I'm fine with that.
So I add a series, add the download to my preferred program, and look in activity.
I'd like it to just show one download for an unknown series, and let me manually import it. However, in this case, it identifies the series, and correctly identifies the episode and season number.
The weird part is, despite clearly saying "2x01", when it finishes and starts importing, it imports as "1x01". This can easily overwrite my existing download of season one, against my will, and I have no way to stop it from doing so after it starts importing.

This could be easily fixed with a small feature, like "Wait to manually import this torrent". A more complicated fix would fixing whatever it is that allows this to happen, where it can correctly identify an episode but import it incorrectly.

**Screenshots**
![SonarrBug1](https://user-images.githubusercontent.com/1676068/79078502-cea53300-7cd6-11ea-8e36-e7550947f18a.png)
![SonarrBug2](https://user-images.githubusercontent.com/1676068/79078519-e977a780-7cd6-11ea-8530-f65c4e7b4a76.png)
![SonarrBug3](https://user-images.githubusercontent.com/1676068/79078552-175cec00-7cd7-11ea-8ad8-ab7b010ae297.png)
Note: I took these screenshots mid-import because I'm impatient, thus why numbers differ. You get the idea.

**Logs**
~Unfortunately, I don't see anything relevant in my log files.~
I coincidentally found the same issue again. I had cleared my logs just a few minutes before I experienced the issue, so I'm just giving you ALL of my logs.
It's set to trace, which I assume is the most detailed, so I assume this is good.
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/4466987/sonarr.debug.txt)
[sonarr.trace.0.txt](https://github.com/Sonarr/Sonarr/files/4466989/sonarr.trace.0.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/4466990/sonarr.trace.txt)
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/4466991/sonarr.txt)

**System Information**

 linuxserver/sonarr:preview

**Additional context**
~In this case I'm using Kakegurui.
I tried to replicate this with logging set to trace, but SOMEONE presumably coded a "Don't import the same download twice" feature, because it refused to show up in activity, and then it got deleted as soon as it switched to completed. So tell me how to get around that and maybe I'll find logs. Otherwise, someone else can follow my replication steps.~

**Comment by markus101** [comment]
> linuxserver/sonarr:preview

This gives an approximate version, but specifically which version?

> It's set to trace, which I assume is the most detailed, so I assume this is good.

Sometimes overly detailed, but you have the debug log too so we have things to go by.

> A more complicated fix would fixing whatever it is that allows this to happen, where it can correctly identify an episode but import it incorrectly.

It's not correctly identifying the episode, it's identified the release name, but the file within is ambiguous to Sonarr in the format it's in (yes it says it's season 2, but that format does not match a known alias) (`Knights of Sidonia S2 - The Ninth Planet Crusade` being the English alias for season 2).

We already have a guard in place for results that have the file and folder parse as different seasons, but that explicitly skips absolute numbering because there isn't a season number in that case. One thing we'll do is improve that check so it specifically rejects it if it's not an expected episode for the release which can include anime and we'll see what we can do about it getting confused in the first place.

**Comment by Rojikku** [comment]
> > linuxserver/sonarr:preview
> 
> This gives an approximate version, but specifically which version?
> 
3.0.3.750-ls3 by linuxserver.io
> > It's set to trace, which I assume is the most detailed, so I assume this is good.
> 
> Sometimes overly detailed, but you have the debug log too so we have things to go by.
> 
Awesome
> > A more complicated fix would fixing whatever it is that allows this to happen, where it can correctly identify an episode but import it incorrectly.
> 
> It's not correctly identifying the episode, it's identified the release name, but the file within is ambiguous to Sonarr in the format it's in (yes it says it's season 2, but that format does not match a known alias) (`Knights of Sidonia S2 - The Ninth Planet Crusade` being the English alias for season 2).
> 
> We already have a guard in place for results that have the file and folder parse as different seasons, but that explicitly skips absolute numbering because there isn't a season number in that case. One thing we'll do is improve that check so it specifically rejects it if it's not an expected episode for the release which can include anime and we'll see what we can do about it getting confused in the first place.

Awesome. Personally, I'd really love a button to just "Set torrent to manual import." It'd solve my issue and it theoretically shouldn't be too hard to implement. I can easily manual import it correctly.

**Comment by markus101** [comment]
This was fixed in https://github.com/Sonarr/Sonarr/commit/54a267d860cdc87cb8c916f0b0a707fc640ddaaa (typo on the issue number)
