### ISSUE TITLE
Multiple season import support

### ISSUE THREAD

**Issue by samip5** [Sonarr/Sonarr#3678]
**Describe the problem**
When an download has a root folder named for example: `Alias S01-05`, Sonarr will only import the first season, but not even see the other's in it unless using manual import.

**Describe any solutions you think might work**
Improve the parsing/folder check logic.

**Additional context**

![image](https://user-images.githubusercontent.com/1703002/79082618-15734700-7d30-11ea-94bb-d57a1fb694ba.png)

**Comment by markus101** [comment]
This is not a passing problem. This is a multi-season release problem. Sonarr does not support multi-season releases and we don’t have plans to support them at this time.

For future bugs please include the relevant debug logs.

**Comment by samip5** [comment]
There were none logs about it that I could find. Maybe searched the wrong thing for them though, but either way, how is this a multi-season release problem? It's a season pack.

**Comment by Taloth** [comment]
It's a MULTI season pack download, which sonarr doesn't support.
