### ISSUE TITLE
Manual Import - Select tv show name and season number for multiple files

### ISSUE THREAD

**Issue by siwon** [Sonarr/Sonarr#3680]
**Describe the problem**
I try to import multiple files for the same TV show and, the show is not recognized by Sonarr. I have to manually set TV show name and season number of each episode of the folder I want to import. 

**Describe any solutions you think might work**
Is it possible to improve the manual import window to add a feature like Lidarr ? With a select box, you can set the TV show name for each file. And the same feature to set the season number. After setting these settings, Sonarr should be able to guess the episode number. I think this improvement could be a time saver (at least for me)

**Additional context**
Here is an example of Lidarr.

![image](https://user-images.githubusercontent.com/1249874/79210712-8bb59d80-7e45-11ea-9603-38e160541733.png)

PS: Thanks for your work.

**Comment by Taloth** [comment]
You forgot to include your sonarr version.

This is implemented in Sonarr v3 beta (where do you think Lidarr got it from :smile:)

**Comment by siwon** [comment]
F*ck ... My bad !I love you so much ^^

**Comment by siwon** [comment]
Thanks a lot :heart_eyes: :heart_eyes: :heart_eyes:! (and sorry for this useless feature request)
