### ISSUE TITLE
Renaming causes files to be copied

### ISSUE THREAD

**Issue by dbond007** [Sonarr/Sonarr#3681]
After moving to v3 of sonarr, and changing some media from 'Bluray-2160p' to 'Bluray-2160p Remux' then selecting preview renaming and then selecting Organize will cause the files to be copied. I currently have an rclone mount and on rename causes the file to be copied over the network to the sonarr server and back again. This can be seen be it taking hours to rename a small number of files which are 100's GB in size and via bandwidth usage and also the logs on the remote server showing new files created and old files being deleted.

![Screenshot showing rename tasks taking hours](https://user-images.githubusercontent.com/4145098/79258025-cee62f80-7e8a-11ea-802d-54cc756b02fa.png)
 

**Logs**
Small part of the logs, the file already exists repeats for all the metadata files.

[v3.0.3.750] System.IO.IOException: The file '/mnt/TV/4k/Westworld/Season 1/Westworld - S01E10 - The Bicameral Mind - Bluray-2160p-thumb.jpg' already exists.
  at System.IO.FileSystem.LinkOrCopyFile (System.String sourceFullPath, System.String destFullPath) [0x000b9] in <a1ae6166591d4020b810288d19af38d4>:0 
  at System.IO.FileSystem.MoveFile (System.String sourceFullPath, System.String destFullPath) [0x0003a] in <a1ae6166591d4020b810288d19af38d4>:0 
  at System.IO.File.Move (System.String sourceFileName, System.String destFileName) [0x00083] in <a1ae6166591d4020b810288d19af38d4>:0 
  at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal (System.String source, System.String destination) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:241 
  at NzbDrone.Mono.Disk.DiskProvider.MoveFileInternal (System.String source, System.String destination) [0x000a3] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\DiskProvider.cs:223 
  at NzbDrone.Common.Disk.DiskProviderBase.MoveFile (System.String source, System.String destination, System.Boolean overwrite) [0x000e1] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:228 
  at NzbDrone.Core.Extras.Metadata.MetadataService.MoveFilesAfterRename (NzbDrone.Core.Tv.Series series, System.Collections.Generic.List`1[T] episodeFiles) [0x000cb] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Extras\Metadata\MetadataService.cs:162 

20-4-14 09:13:19.7|Info|RenameEpisodeFileService|Selected episode files renamed for Westworld
20-4-14 09:13:19.9|Info|RenameEpisodeFileService|Renaming 10 files for Westworld

**System Information**

Version : 3.0.3.750
Package Version : 3.0.3
Mono Version : 6.8.0.105
Operating System: Ubuntu 18.04

**Comment by markus101** [comment]
That snippet doesn't show any media files being moved, that's a jpg being moved. Please upload the relevant trace logs and link them here, info logs are not sufficient for bug reports and trace will give us the info we need over debug.

**Comment by dbond007** [comment]
I turned on debug but that didn't show anything relevant, probably due to the issue not being triggered yet until the next file in the queue is to be renamed (which with the current renames, there are none left). So when its finished copying / renaming this file I will turn on tracing, issue a rename on a single file and then make available the trace log.

**Comment by dbond007** [comment]
Hi,
changed an episode from web to hdtv and then issued a rename, trace output:
20-4-15 16:42:02.0|Trace|CommandQueueManager|Updating command status
20-4-15 16:42:02.1|Trace|CommandExecutor|RenameFilesCommand -> RenameEpisodeFileService
20-4-15 16:42:02.1|Trace|CommandQueueManager|Marking command as started: RenameFiles
20-4-15 16:42:02.1|Trace|EventAggregator|Publishing CommandExecutedEvent
20-4-15 16:42:02.1|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
20-4-15 16:42:02.1|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
20-4-15 16:42:02.1|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
20-4-15 16:42:02.1|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
20-4-15 16:42:02.1|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
20-4-15 16:42:02.1|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
20-4-15 16:42:02.1|Trace|CommandExecutor|ProcessMonitoredDownloadsCommand <- DownloadProcessingService [03:53:10.2999190]
20-4-15 16:42:02.1|Trace|Http|Req: 1008 [GET] /api/v3/command
20-4-15 16:42:02.1|Trace|CommandQueueManager|Getting all commands
20-4-15 16:42:02.1|Trace|Http|Res: 1008 [GET] /api/v3/command: 200.OK (3 ms)
20-4-15 16:42:02.1|Debug|Api|[GET] /api/v3/command: 200.OK (3 ms)
20-4-15 16:42:02.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-4-15 16:42:02.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-4-15 16:42:02.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-4-15 16:42:02.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-4-15 16:42:02.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-4-15 16:42:02.2|Info|RenameEpisodeFileService|Renaming 1 files for Tom Clancy's Jack Ryan
20-4-15 16:42:02.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-4-15 16:42:02.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-4-15 16:42:02.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-4-15 16:42:02.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-4-15 16:42:02.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-4-15 16:42:02.2|Debug|RenameEpisodeFileService|Renaming episode file: [136016] Season 1/Tom Clancy's Jack Ryan - S01E01 - Pilot - WEBDL-2160p.mkv
20-4-15 16:42:02.2|Trace|PreferredWordService|Calculating preferred word score for 'Tom.Clancys.Jack.Ryan.S01E01.2160p.AMZN.WEBRip.DDP5.1.x264-NTb'
20-4-15 16:42:02.7|Debug|EpisodeFileMovingService|Renaming episode file: [136016] Season 1/Tom Clancy's Jack Ryan - S01E01 - Pilot - WEBDL-2160p.mkv to /mnt/TV/4k/Tom Clancy's Jack Ryan/Season 1/Tom Clancy's Jack Ryan - S01E01 - Pilot - HDTV-2160p.mkv
20-4-15 16:42:03.6|Debug|DiskTransferService|Move [/mnt/TV/4k/Tom Clancy's Jack Ryan/Season 1/Tom Clancy's Jack Ryan - S01E01 - Pilot - WEBDL-2160p.mkv] > [/mnt/TV/4k/Tom Clancy's Jack Ryan/Season 1/Tom Clancy's Jack Ryan - S01E01 - Pilot - HDTV-2160p.mkv]
20-4-15 16:42:06.6|Trace|CommandQueueManager|Publishing RefreshMonitoredDownloads
20-4-15 16:42:06.6|Trace|CommandQueueManager|Checking if command is queued or started: RefreshMonitoredDownloads
20-4-15 16:42:06.6|Trace|CommandQueueManager|Command is already in progress: RefreshMonitoredDownloads


######repeat many times#############

20-4-15 16:42:20.8|Trace|Scheduler|Pending Tasks: 7
20-4-15 16:42:20.8|Trace|CommandQueueManager|Publishing MessagingCleanup
20-4-15 16:42:20.8|Trace|CommandQueueManager|Checking if command is queued or started: MessagingCleanup
20-4-15 16:42:20.8|Trace|CommandQueueManager|Command is already in progress: MessagingCleanup
20-4-15 16:42:20.8|Trace|CommandQueueManager|Publishing ApplicationUpdate
20-4-15 16:42:20.8|Trace|CommandQueueManager|Checking if command is queued or started: ApplicationUpdate
20-4-15 16:42:20.8|Trace|CommandQueueManager|Command is already in progress: ApplicationUpdate
20-4-15 16:42:20.8|Trace|CommandQueueManager|Publishing UpdateSceneMapping
20-4-15 16:42:20.8|Trace|CommandQueueManager|Checking if command is queued or started: UpdateSceneMapping
20-4-15 16:42:20.8|Trace|CommandQueueManager|Command is already in progress: UpdateSceneMapping
20-4-15 16:42:20.8|Trace|CommandQueueManager|Publishing CheckHealth
20-4-15 16:42:20.8|Trace|CommandQueueManager|Checking if command is queued or started: CheckHealth
20-4-15 16:42:20.8|Trace|CommandQueueManager|Command is already in progress: CheckHealth
20-4-15 16:42:20.8|Trace|CommandQueueManager|Publishing RefreshSeries
20-4-15 16:42:20.8|Trace|CommandQueueManager|Checking if command is queued or started: RefreshSeries
20-4-15 16:42:20.8|Trace|CommandQueueManager|Command is already in progress: RefreshSeries
20-4-15 16:42:20.8|Trace|CommandQueueManager|Publishing RssSync
20-4-15 16:42:20.8|Trace|CommandQueueManager|Checking if command is queued or started: RssSync
20-4-15 16:42:20.8|Trace|CommandQueueManager|Command is already in progress: RssSync
20-4-15 16:42:20.8|Trace|CommandQueueManager|Publishing RefreshMonitoredDownloads
20-4-15 16:42:20.8|Trace|CommandQueueManager|Checking if command is queued or started: RefreshMonitoredDownloads
20-4-15 16:42:20.8|Trace|CommandQueueManager|Command is already in progress: RefreshMonitoredDownloads

#######end repeat################

20-4-15 17:54:53.5|Trace|ConfigService|Using default config value for 'filedate' defaultValue:'None'
20-4-15 17:54:53.5|Trace|ConfigService|Using default config value for 'filechmod' defaultValue:'0644'
20-4-15 17:54:53.5|Trace|ConfigService|Using default config value for 'setpermissionslinux' defaultValue:'False'
20-4-15 17:54:53.5|Debug|RenameEpisodeFileService|Renamed episode file: [136016] Season 1/Tom Clancy's Jack Ryan - S01E01 - Pilot - HDTV-2160p.mkv
20-4-15 17:54:53.6|Trace|EventAggregator|Publishing EpisodeFileRenamedEvent
20-4-15 17:54:53.6|Trace|EventAggregator|EpisodeFileRenamedEvent -> HistoryService
20-4-15 17:54:53.7|Trace|EventAggregator|EpisodeFileRenamedEvent <- HistoryService
20-4-15 17:54:54.4|Trace|EventAggregator|Publishing SeriesRenamedEvent
20-4-15 17:54:54.4|Trace|EventAggregator|SeriesRenamedEvent -> NotificationService
20-4-15 17:54:54.5|Debug|NotificationService|No tags set for this notification.

**Comment by darthShadow** [comment]
This looks similar to an issue posted on the rclone forums: https://forum.rclone.org/t/sonarr-rename-is-copying-files/15353

This is probably an issue with Mono that was fixed with this PR: https://github.com/mono/corefx/pull/395

That PR has been backported for the upcoming Mono version 6.10: https://github.com/mono/mono/pull/19428

**Comment by Taloth** [comment]
I figured as much. Downgrading to mono 5.20 would deal with it too.

**Comment by Taloth** [comment]
Copied part of that patch in https://github.com/Sonarr/Sonarr/commit/576275b6dad7a909a0dcdd077d94e10d5efaef45

Can you let me know if it works better in 3.0.3.761 once it's published? (30min or so)

@darthShadow Thank you

**Comment by dbond007** [comment]
Sure, will give it a go.
Thanks

**Comment by dbond007** [comment]
Did the update, but it appears to have failed, sonarr will no longer start. Looking into it now, tried a forced reinstall over the top didn't help:

20-4-18 09:43:52.7|Info|InstallUpdateService|Downloading update 3.0.3.761
20-4-18 09:43:54.0|Info|InstallUpdateService|Verifying update package
20-4-18 09:43:54.3|Info|InstallUpdateService|Update package verified successfully
20-4-18 09:43:54.3|Info|InstallUpdateService|Extracting Update package
20-4-18 09:43:55.6|Info|InstallUpdateService|Update package extracted successfully
20-4-18 09:43:55.6|Info|BackupService|Starting Backup
20-4-18 09:44:11.2|Info|InstallUpdateService|Preparing client
20-4-18 09:44:11.4|Info|InstallUpdateService|Starting update client /tmp/sonarr_update/Sonarr.Update.exe
20-4-18 09:44:11.4|Info|InstallUpdateService|Sonarr will restart shortly.
20-4-18 09:44:21.5|Info|InstallUpdateService|Deleting old update files
20-4-18 09:44:21.7|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v3.0.3.757] System.IO.IOException: Directory not empty
  at System.IO.FileSystem.RemoveDirectoryInternal (System.IO.DirectoryInfo directory, System.Boolean recursive, System.Boolean throwOnTopLevelDirectoryNotFound) [0x00114] in <a1ae6166591d4020b810288d19af38d4>:0 
  at System.IO.FileSystem.RemoveDirectory (System.String fullPath, System.Boolean recursive) [0x0000c] in <a1ae6166591d4020b810288d19af38d4>:0 
  at System.IO.Directory.Delete (System.String path, System.Boolean recursive) [0x00006] in <a1ae6166591d4020b810288d19af38d4>:0 
  at NzbDrone.Common.Disk.DiskProviderBase.DeleteFolder (System.String path, System.Boolean recursive) [0x00071] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:253 
  at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate (NzbDrone.Core.Update.UpdatePackage updatePackage) [0x000ee] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Update\InstallUpdateService.cs:110 
  at NzbDrone.Core.Update.InstallUpdateService.Execute (NzbDrone.Core.Update.Commands.ApplicationUpdateCommand message) [0x000f7] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Update\InstallUpdateService.cs:242 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000fb] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:97 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x00035] in <59093ef301a24e5a91cb0295fb832cca>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41

**Comment by dbond007** [comment]
removed it installed sonarr again and updated. Tested and rename now works, not copying anymore.

**Comment by dbond007** [comment]
If you want to look into why it didn't update properly I have a snapshot of the broken install if you want me to provide anything.

**Comment by Taloth** [comment]
> Did the update, but it appears to have failed, sonarr will no longer start.

My heart skipped a beat. "Did I break something horribly?". Then I noticed the old version number in the exception... phew

It's unable to delete the temp directory `/tmp/sonarr_update`. Maybe the updater was still running... 
But that should not prevent sonarr from starting.

```
20-4-18 09:44:11.4|Info|InstallUpdateService|Sonarr will restart shortly.
20-4-18 09:44:21.5|Info|InstallUpdateService|Deleting old update files
```

This makes no sense, the first line is literally the last thing that happens _in_ Sonarr for an update. after 'Sonarr will restart shortly', it executes the updater. The updater copies the new binaries into place and then terminates Sonarr.
The second line (10 seconds later) is normally happening earlier, before Sonarr unpacks the update download.
It almost feels like two update checks happened at once.
If two updates ran at once, then Sonarr was deleting `/tmp/sonarr_update` while the updater was running. Which would of course lead to an incomplete set of files being copied during that update.

Can you check the log for other mentions of `InstallUpdateService` around that time (+- 5 minutes)?

PS: Good news for the file move though. At least this way ppl won't have to wait for 6.10.

**Comment by dbond007** [comment]
No other instance in the log, only what I posted is there.
But I do know the update button was pressed 2 times. It was pressed the first time. appeared to be running, stopped, nothing came up about restarting sonarr to complete, but the update button came back, pressed again, sonarr shutdown, wouldn't start again.
But as you were thinking 2 instances could have been running because of that, but unless the second click didn't get logged, doesn't look like that happened.

**Comment by Taloth** [comment]
The second click could've done it, I'd expect some trace in the log, but I'll accept it as explanation. There's a tiny window where the user can initiate the update check again while the updater binary is running. 
I suppose we should protect against that by checking if the updater executable is still running.

Either way, thank you for testing the fix.
