### ISSUE TITLE
Sonarr cannot find season packs

### ISSUE THREAD

**Issue by hennning** [Sonarr/Sonarr#3682]
**Describe the bug**
Sonarr cannot find any season packs on any of my trackers. Both automatic search and interactive.
It can successfully find individual episodes.

**Screenshots**
https://i.imgur.com/m7vkB7Q.png

**Logs**
https://gofile.io/?c=YYYNy7

**System Information**

Version
3.0.3.754
Package Version
3.0.3.754-ls4 by linuxserver.io
Mono Version
5.20.1.34

Running in Unraid Docker

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
Please open a thread on the forums for troubleshooting and include a debug log of a season search.
