### ISSUE TITLE
Not matching Discovery Web-DL releases

### ISSUE THREAD

**Issue by piejanssens** [Sonarr/Sonarr#3683]
Example:  TV.Show.S13E03.Episode.Name.1080p.DISC.WEB-DL.AAC2.0.x264-RLSGRP

Do we need a fix in https://github.com/Sonarr/Sonarr/blob/master/src/NzbDrone.Core/Parser/QualityParser.cs#L19 and/or other places?

This might be in Phantom? I'm running 2.0.0.5344.

**Comment by Taloth** [comment]
Parses as WEBDL-1080p for me.

I suspect you jumping to conclusions regarding quality parsing, rather than providing information about your _actual_ problem.
