### ISSUE TITLE
Download file contains multiple language subtitles, how to keep them at the same time

### ISSUE THREAD

**Issue by SuperNG6** [Sonarr/Sonarr#3685]
**Version**
3.0.3.757
Package Version
3.0.3.757-ls5 by linuxserver.io
Mono Version
5.20.1.34
AppData directory
/config
Startup directory
/app/sonarr/bin
Mode
Console

**Describe the problem**
There are some BT seeds that contain multiple subtitle files, but sonarr can only move one subtitle file when moving the file or the first one is overwritten by the second one, can sonarr keep all the subtitle files when moving the subtitle?

**Describe any solutions you think might work**
Wish sonarr could add settings that give users the option to keep subtitles in multiple languages, or add SC, TC languages  

**Additional context**
This BT seed contains a video with subtitles in two languages (Simplified Chinese, Traditional Chinese)  
![qp0WTD](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/qp0WTD.png)

![Attachment-1](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/Attachment-1.png)

but sonarr only keeps one subtitle (Traditional Chinese), when moving the file after downloaded. I would like to keep both subtitles (Simplified Chinese and Traditional Chinese) or give the user the option to keep the subtitle of their choice.
![Attachment-2](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/JJDcxT.png)

**Comment by markus101** [comment]
Sonarr treats the `tc` and `sc` after the filename, but before the extension as the language code, but only maintains it if the language code is a valid code for a whitelisted language. `tc` is not a valid code and `sc` is Sardinian, which is not whitelisted.

One of a couple things could happen here:

- Do nothing, unsupported languages/metadata is lost during rename if Sonarr doesn't understand it
- Maintain anything that isn't a known language code which would fall under https://github.com/Sonarr/Sonarr/issues/2570

We'll discuss and update before closing.

**Comment by markus101** [comment]
Updated #2570 to reflect these tags should all be maintained.

**Comment by SuperNG6** [comment]
Thank you very much for your reply
