### ISSUE TITLE
Sonarr won't update using built-in updater

### ISSUE THREAD

**Issue by baz1860** [Sonarr/Sonarr#3689]
**Describe the bug**
Sonarr will not update past v3.0.3.741. The process runs but the update fails.

**Logs**
https://gist.github.com/baz1860/b9d088f09128cf6a738bbc63a5501298

**System Information**

 - Sonarr Version: 3.0.3.741
 - Operating System: macOS 10.15.4
 - mono version: 5.20.1.34
**Additional context**
Updater can see there are update available, it can download them, it's just stopped being able to install them.

**Comment by Taloth** [comment]
Update manually (install it from the site as you originally did). The mechanism was broken in 741.
