### ISSUE TITLE
Passwords with special characters are unable to be migrated to v3

### ISSUE THREAD

**Issue by vishhvaan** [Sonarr/Sonarr#3690]
**Describe the bug**
The password of my sonarr instance has special characters: "{} 

When I spin up a docker container (even v2), migration to the v3 db takes place. After migration, I am unable to login.

**Logs**
20-4-20 10:11:24.3|Info|Bootstrap|Starting Sonarr - /app/sonarr/bin/NzbDrone.exe - Version 2.0.0.5344                  
20-4-20 10:11:24.9|Info|AppFolderInfo|Data directory is being overridden to [/config]                                  
20-4-20 10:11:25.0|Info|Router|Application mode: Interactive                                                           
20-4-20 10:11:25.1|Info|MigrationLogger|*** Migrating data source=/config/nzbdrone.db;cache size=-10000;datetimekind=Ut
20-4-20 10:11:25.3|Info|MigrationLogger|*** Migrating data source=/config/logs.db;cache size=-10000;datetimekind=Utc;jo
20-4-20 10:11:25.4|Info|OwinHostController|Listening on the following URLs:                                            
20-4-20 10:11:25.4|Info|OwinHostController|  http://*:8989/                                                            
20-4-20 10:11:25.5|Info|NancyBootstrapper|Starting Web Server                                                          
20-4-20 10:11:56.7|Info|SceneMappingService|Updating Scene mappings                                                    
20-4-20 10:11:57.3|Info|RssSyncService|Starting RSS Sync                                                             

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Docker - latest LinuxServer

**Comment by markus101** [comment]
Please fill out the entire bug template.

**Comment by vishhvaan** [comment]
I'm sorry about this issue report. It was a problem on my side.
