### ISSUE TITLE
Activity Queue No Longer Clearing 

### ISSUE THREAD

**Issue by wastingaeons** [Sonarr/Sonarr#3691]
**Describe the bug**
Activity queue doesn't clear on version 3.0.3.764 and up. When hovering over the orange download icon, error states that episodes have already been imported and already exists with same file size. This doesn't happen on 3.0.3.761. See attached screenshot.

Using 'remove selected' options removes them from the list, but they reappear shortly after.

**Screenshots**
![aaaaaaaa](https://user-images.githubusercontent.com/2839483/79796011-adad9500-8309-11ea-8710-39bf7a80f55d.png)

**System Information**
Works as intended on: 3.0.3.761
Started on: 3.0.3.764 
Exists on: 3.0.3.765

Linux 4.19.107-Unraid
Docker: linuxserver/sonarr
Deluge 2.x

**Logs**

> 20-4-20 13:38:03.0|Debug|DownloadedEpisodesImportService|Processing path: /data/XXX.S01E01.480p.HEVC-XXX
20-4-20 13:38:03.0|Debug|Parser|Parsing string 'XXX.S01E01.480p.HEVC-XXX'
20-4-20 13:38:03.0|Debug|Parser|Episode Parsed. XXX - S01E01 
20-4-20 13:38:03.0|Debug|Parser|Language parsed: English
20-4-20 13:38:03.0|Debug|QualityParser|Trying to parse quality for XXX.S01E01.480p.HEVC-XXX
20-4-20 13:38:03.0|Debug|Parser|Quality parsed: WEBDL-480p v1
20-4-20 13:38:03.0|Debug|Parser|Release Group parsed: XXX
20-4-20 13:38:03.0|Debug|DiskScanService|Scanning '/data/XXX.S01E01.480p.HEVC-XXX' for video files
20-4-20 13:38:03.0|Debug|DiskScanService|1 video files were found in /data/XXX.S01E01.480p.HEVC-XXX
20-4-20 13:38:03.0|Debug|ImportDecisionMaker|Analyzing 1/1 files.
20-4-20 13:38:03.0|Debug|Parser|Parsing string 'XXX.S01E01.480p.HEVC-XXX'
20-4-20 13:38:03.0|Debug|Parser|Episode Parsed. XXX - S01E01 
20-4-20 13:38:03.0|Debug|Parser|Language parsed: English
20-4-20 13:38:03.0|Debug|QualityParser|Trying to parse quality for XXX.S01E01.480p.HEVC-XXX
20-4-20 13:38:03.0|Debug|Parser|Quality parsed: WEBDL-480p v1
20-4-20 13:38:03.0|Debug|Parser|Release Group parsed: XXX
20-4-20 13:38:03.0|Debug|VideoFileInfoReader|Getting media info from /data/XXX.S01E01.480p.HEVC-XXX/XXX.S01E01.480p.HEVC-XXX.mkv
20-4-20 13:38:03.0|Debug|DetectSample|Runtime is over 90 seconds
20-4-20 13:38:03.0|Debug|Parser|Parsing string 'XXX.S01E01.480p.HEVC-XXX.mkv'
20-4-20 13:38:03.0|Debug|Parser|Episode Parsed. XXX - S01E01 
20-4-20 13:38:03.0|Debug|Parser|Language parsed: English
20-4-20 13:38:03.0|Debug|QualityParser|Trying to parse quality for XXX.S01E01.480p.HEVC-XXX.mkv
20-4-20 13:38:03.0|Debug|Parser|Quality parsed: WEBDL-480p v1
20-4-20 13:38:03.0|Debug|Parser|Release Group parsed: XXX
20-4-20 13:38:03.0|Debug|VideoFileInfoReader|Getting media info from /data/XXX.S01E01.480p.HEVC-XXX/XXX.S01E01.480p.HEVC-XXX.mkv
20-4-20 13:38:03.0|Debug|Parser|Parsing string 'XXX.S01E01.480p.HEVC-XXX'
20-4-20 13:38:03.0|Debug|Parser|Episode Parsed. XXX - S01E01 
20-4-20 13:38:03.0|Debug|Parser|Language parsed: English
20-4-20 13:38:03.0|Debug|QualityParser|Trying to parse quality for XXX.S01E01.480p.HEVC-XXX
20-4-20 13:38:03.0|Debug|Parser|Quality parsed: WEBDL-480p v1
20-4-20 13:38:03.0|Debug|Parser|Release Group parsed: XXX
20-4-20 13:38:03.0|Debug|AggregateLanguage|Using language: English
20-4-20 13:38:03.0|Debug|AggregateQuality|Using quality: WEBDL-480p v1
20-4-20 13:38:03.0|Debug|AbsoluteEpisodeNumberSpecification|Series type is not Anime, skipping check
20-4-20 13:38:03.0|Debug|AlreadyImportedSpecification|Episode file previously imported at 4/20/2020 7:34:33 PM
20-4-20 13:38:03.0|Debug|EpisodeTitleSpecification|Episode title only required for bulk season releases
20-4-20 13:38:03.0|Debug|VideoFileInfoReader|Getting media info from /data/XXX.S01E01.480p.HEVC-XXX/XXX.S01E01.480p.HEVC-XXX.mkv
20-4-20 13:38:03.0|Debug|DetectSample|Runtime is over 90 seconds
20-4-20 13:38:03.1|Debug|SameFileSpecification|'/data/XXX.S01E01.480p.HEVC-XXX/XXX.S01E01.480p.HEVC-XXX.mkv' Has the same filesize as existing file
20-4-20 13:38:03.1|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Episode file already imported at 4/20/2020 7:34:33 PM, [Permanent] Has the same filesize as existing file

**Comment by markus101** [comment]
This issue began well before 3.0.3.761 and was due to episode history being lost when episode numbers changed, the series was removed or due to an issue where TVDB stopped returning episodes and history was lost when the episode was removed.

The same file size check has been removed, but you'll need to manually import (from the queue) or remove (but not delete from client) to get passed anything it already imported, but didn't mark the download as completely imported.

If you see this issue re-occur please upload the debug logs (and trace log if possible) somewhere from the original import of that download and link them here.
