### ISSUE TITLE
Sonarr v3 double entering Series name when adding a new show

### ISSUE THREAD

**Issue by alternativesurfer** [Sonarr/Sonarr#3696]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Sonarr Version:**
3.0.3.765

**Operating System:**
Ubuntu 16.04

**.net Framework (Windows) or mono (macOS/Linux) Version:**
Mono: 6.8.0.105

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**

### Additional Information

When I add a new show to Sonarr it autocreates the series folder within my specified path.
The folder it creates a folder with the series name duplicated before the release year which I then have to manually create and migrate to within Sonarr.

Ex. 
Show, The Outsiders (1990) 

Folder appears as "TheOutsidersTheOutsiders (1990)"

![image](https://user-images.githubusercontent.com/10135929/79908741-a1d8d600-83d0-11ea-8f20-dc9d4339db97.png)

**Comment by markus101** [comment]
Sounds like your `Series Folder Format` (advanced setting in Media Management Settings) is set to `{Series Title}{Series TitleYear}`.

**Comment by markus101** [comment]
Closing until we get more info.

**Comment by alternativesurfer** [comment]
Yep, that was it.
Thanks!
