### ISSUE TITLE
Possible Incorrect End of Line Indicator When Running Custom Scripts

### ISSUE THREAD

**Issue by tkdrob** [Sonarr/Sonarr#3699]
**Describe the bug**
When I try to test a python script, I get /usr/bin/env: ‘python\r’: No such file or directory

This seems to be an incorrect end of line indicator for my platform. I think its supposed to be \n

**Logs**
/usr/bin/env: ‘python\r’: No such file or directory

**System Information**

 - Sonarr Version: 3.03.770
 - Operating System: Synology Docker by linuxserver.io
 - Mono Version: 5.20.1.34

**Comment by markus101** [comment]
At the very minimum we need to see the full debug log, but trace would be ideal here. Upload them and link them here.

Is python even available in that docker image?

**Comment by Taloth** [comment]
Almost certainly you're uploading your script (or python script) from windows with windows line ending.

**Comment by tkdrob** [comment]
@Taloth Yep. Turns out copy and paste must have done it. I opened my script with HxD and removed the 0D immediately after python3. I was using this script here: https://github.com/l3uddz/TorrentCleanup/blob/master/TorrentCleanup.py

@markus101 Python is included in the linuxserver.io image. If not, apt-get does the trick. Hopefully this post with serve as help for others who may encounter this
