### ISSUE TITLE
Handle season names that are in TVDB but not Xem

### ISSUE THREAD

**Issue by rcombs** [Sonarr/Sonarr#3700]
TVDB now supports season names; see e.g. https://www.thetvdb.com/series/ghost-in-the-shell-stand-alone-complex/seasons/official/3
This should be possible to use for episode searches even when the season name isn't yet in Xem, at least where the episode mapping is trivial (as is the case here).

**Comment by thezoggy** [comment]
sadly there are many things that exists on tvdb site that are not exposed in their api (and some in reverse). forever now you can have series aliases which were only exposed on the site but never on the api. i have a feeling season level ones are the same. (i've yet to check)

**Comment by Taloth** [comment]
TheTvdb aliases are not really useful and unreliable.
Which is why we rely on aliases provided by TheXEM or our own [scene naming exceptions](https://forums.sonarr.tv/t/scene-naming-tvdb-naming-conflicts/137).

If you need an alias, submit it there or TheXEM, depending on whether it's anime or not.
