### ISSUE TITLE
Episodes downloading multiple times - Upgrade disabled

### ISSUE THREAD

**Issue by T0rm3nt** [Sonarr/Sonarr#3702]
**Describe the bug**
I have recently started using the 'release profile' tags to help filter down the releases that I prefer when it automatically searches for me.
But when I check the next day it has gone and downloaded then deleted the episode multiple times.
I dont understand why it does this as I have turned upgrade off so surely once it has found a suitable file it then marks that episode as done?
I have even added a delay profile so it has chance to wait for more releases so it can pick the most favorable, incase that was whats triggering it.

Not sure if its a bug or perhaps my own stupid error so any help or pointers would be great !

See my settings below.

**Screenshots**
![Annotation 091234](https://user-images.githubusercontent.com/60298506/80274871-90941000-86d5-11ea-958a-c355c18bfe36.png)
![Annotation 091312](https://user-images.githubusercontent.com/60298506/80274872-91c53d00-86d5-11ea-880f-e930568c86a7.png)

**Logs**
I had switched over to Trace logs for this, but didnt realise there would be so many! so will try and find the ones that relate to the times these downloads triggered!

**System Information**

 - Sonarr Version: 3.0.3.770
 - Operating System: Windows 10

**Comment by markus101** [comment]
Need at least debug logs (trace as well would be best) of a subsequent download, but probably something to do with perferred words. Upload them and link them here.

**Comment by T0rm3nt** [comment]
[sonarr.debug.1.txt](https://github.com/Sonarr/Sonarr/files/4532642/sonarr.debug.1.txt)
[sonarr.debug.2.txt](https://github.com/Sonarr/Sonarr/files/4532643/sonarr.debug.2.txt)
[sonarr.debug.0.txt](https://github.com/Sonarr/Sonarr/files/4532644/sonarr.debug.0.txt)

Thanks for the swift response, here are the debug logs.... ill have a look though all the trace logs to find the relevant ones that are showing this episode and get those up when i can

**Comment by markus101** [comment]
`20-4-24 23:25:01.0|Debug|UpgradableSpecification|Comparing preferred word score. Current: 0 New: 70`

But also:

`20-4-24 23:25:01.0|Debug|AlreadyImportedSpecification|Skipping already imported check because CDH is disabled`

If CDH is disabled how are episodes being imported?

It's likely that the file being imported lacks the details that the release name has and results in the score of 0 for the currently file, but trace logs will show what it's using to try and calculate the score.

**Comment by T0rm3nt** [comment]
im using script to convert to MP4 after the download has completed... in the setup for that it asks for the CDH to be disabled.... the script doesn't do any sort of renaming just simply converts the downloaded file then passes it back to Sonarr, or so im lead to believe?

But with upgrade disabled I assumed once it has selected the file to download using the scoring system it then moves on?

**Comment by markus101** [comment]
> the script doesn't do any sort of renaming just simply converts the downloaded file then passes it back to Sonarr, or so im lead to believe?

That may be part of the issue, depending on what Sonarr stores when importing. If the post processing script is running through SAB and doesn't mark the script as complete until the conversion is complete then CDH could still be used.

> But with upgrade disabled I assumed once it has selected the file to download using the scoring system it then moves on?

Having it disabled makes no difference to scoring, Sonarr still needs to be able to compare the old.

Those logs don't show the release processing, specifically we're looking for `Calculating preferred word score for` for both the new release and the existing file. We also need the

**Comment by T0rm3nt** [comment]
I've scanned through the logs and I can't seem to find the 'Calculating preferred word score' for this episode... perhaps I missed it when catching the logs. So ill wait until the next show downloads and keep a closer eye out. 

> It's likely that the file being imported lacks the details that the release name has and results in the score of 0 for the currently file, but trace logs will show what it's using to try and calculate the score.

To help with this, I noticed that the issue seems to happen on files that have obfuscated file name. So I have triggered a renaming script to run first to rename the media with the full job name... 
Do we think that will help with the details when scanning?

**Comment by markus101** [comment]
The obfuscated filename shouldn’t be a problem, it should instead use the folder name. But that might depend on whether the conversion tells Sonarr to import the file or the folder.

**Comment by T0rm3nt** [comment]
> That may be part of the issue, depending on what Sonarr stores when importing. If the post processing script is running through SAB and doesn't mark the script as complete until the conversion is complete then CDH could still be used.

I'm gonna try re-enabling CDH and seeing if it allows the script to run and complete before taking over and moving the file. As that would be the best of both worlds for me!

**Comment by claustralia** [comment]
I appear to be having a similar issue that when the preferred file is downloaded and then processed it will download the same release again because the processed file is not marked as "Existing file on disk is of equal or higher preference: WEBDL-1080p v1 - English."  The re-downloading stops when the file is out of the RSS sync but while it is, it continually re-downloads.  I do not have any trace log of this occurring but when it does happen again, I will post them.  Like you said previously, it may be that "It's likely that the file being imported lacks the details that the release name has and results in the score of 0 for the currently file."  Which if this is the case, I assume there is no way to fix that.

Thanks!

**Comment by claustralia** [comment]
Alright, the issue has happened again...hopefully I'm posting this in the right thread.  

Here is my tracelog:

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/4552991/sonarr.trace.txt)

Here is a SS of the download history:

![Download History](https://user-images.githubusercontent.com/7306196/80621112-77100280-8a0c-11ea-8358-c7165f9b328d.png)

Here is a SS of the search showing that it would still download these files even though it has a file that meets the preferred release already:

![Search](https://user-images.githubusercontent.com/7306196/80621167-8abb6900-8a0c-11ea-9176-5c99b4811840.png)

Hope this helps!  Again, this is only an issue while the release is available in the RSS sync.  Let me know if you need anything else.  Thanks.

**Comment by T0rm3nt** [comment]
Agreed, it only seems to happen on the RSS sync for new episodes.
Have tried to re-create this issue on an individual episodes automatic search but it doesnt happen.
I am waiting for my next big show to download where there are multiple releases to choose from and will post accordingly.

**Comment by markus101** [comment]
The issue here is source file/folder names are being truncated; when Sonarr compares the next release with a preferred release group it doesn't know the release group of the exist file.

```
20-4-29 11:15:47.1|Trace|PreferredWordService|Calculating preferred word score for 'Vanderpump.Rules.S08E17.Til.Death.Do.Us.Not.Part.1080p.AMZN.WEB-'
20-4-29 11:15:47.1|Trace|PreferredWordService|Calculated preferred word score for 'Vanderpump.Rules.S08E17.Til.Death.Do.Us.Not.Part.1080p.AMZN.WEB-': 0
```

Not sure which download client you're using, but in SABnzbd this is controlled by the `folder_max_length` in the `Special` config. Using a short download directory and/or increasing that setting will fix that issue.

**Comment by lsaadeh** [comment]
also having this issue, has anyone found a solution?

**Comment by bakerboy448** [comment]
> also having this issue, has anyone found a solution?

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
