### ISSUE TITLE
Can't find list of available time zones

### ISSUE THREAD

**Issue by jeffchew** [Sonarr/Sonarr#3704]
I'm setting up a docker container with Sonarr, and for the `TZ` config, I can't seem to find a list of available time zones I can choose from to set this to. Would be nice if there is documentation on this somewhere that has the available list. Better yet, a list to the available time zones to choose from linked from the docker documentation.

Docker documentation: https://hub.docker.com/r/linuxserver/sonarr/

**Comment by markus101** [comment]
That’s a docker question, not something specific to Sonarr. Any Linux timezone should work, like this Wikipedia page that is the first google result for “Linux timezone list”: https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones

If you have any questions about Sonarr please open a thread on the forums or subreddit.
