### ISSUE TITLE
Search for one-season series without specifying season number

### ISSUE THREAD

**Issue by fevecn** [Sonarr/Sonarr#3705]
Sonarr can search for season packs already but when the torrent is named ex: ¨Ping Pong¨, Sonarr will search for ¨Ping Pong Season 1¨ on the tracker and will not find Ping Pong.

A workaround would be if Sonarr detects if a series has only one season and search for it without the season number to get more results (at least for manual search) and maybe download the batch for these one-season series only.

I think this would be of huge help because one-season series are often named without the season sufix.

**Comment by markus101** [comment]
It shouldn't matter, if releases for standard series have the season number then results should be returned for those episodes. For anime Sonarr would search by absolute episode number, unfortunately it's not done per season because batches are more commonly used and Sonarr doesn't know how big the batches are for larger series.

One issue with searching without season number would be "complete" results that don't indicate the season/episodes in the batch, Sonarr is never going to be able to handle them and even a season interactive search wouldn't be able to link the release to the correct episodes and prevent grabbing.

**Comment by fevecn** [comment]
Yeah i got it that it´s not possible for anime larger series, but I´m not sure if i understood the issue for one-season series, because we don´t have the multiple seasons problem, so in my understanding it´s possible for Sonarr to assume that no specified season in the torrent means Season 1 because it is the only season possible. So how is the difference between searching for Season 1 instead of searching without season number in this case (assuming equal chances of the episodes being numbered listed in the pack)?

I´m asking this because i can´t get Ping Pong the Animation (and many other torrents listed like this on the tracker) to list on Sonarr (both manual and automatic) just because the torrent does not have S01/Season 1 in it´s name.

**Comment by markus101** [comment]
> in my understanding it´s possible for Sonarr to assume that no specified season in the torrent means Season 1

For individual episodes that just use season numbers or "part X" then yes, but not a "complete" pack, Sonarr needs to be able to parse the name to determine what it is and for a season pack (even if it's a single season) the season number would need to be a part of the name.

The only case this would fix is anime batches where Sonarr couldn't anticipate the batch size (I think in smaller seasons it'd be possible to guess that it's the entire season and search for that).

We don't have plans to search without a specific season number for season searches.

**Comment by fevecn** [comment]
> 
> The only case this would fix is anime batches where Sonarr couldn't anticipate the batch size (I think in smaller seasons it'd be possible to guess that it's the entire season and search for that).
>

Yes, that’s my point, but now i understand the problems for this feature, thanks for clarifying, and developing Sonarr.

**Comment by kSotin** [comment]
What if _Use Season Folder_ is used to toggle this feature on or off? Like Sonarr would search without season suffix only when _Use Season Folder_ is toggled _No_?
