### ISSUE TITLE
100% Cpu when running Sonarr V2

### ISSUE THREAD

**Issue by wwhitty0** [Sonarr/Sonarr#3707]
When running Sonarr on Ubuntu 18 server it seems to run for uptown 3-4 hours then I get a 100% Cpu problem.
Do you have any troubleshooting tips at all for this?

![2020-04-26 20 41 31](https://user-images.githubusercontent.com/22223728/80318011-12cc2380-87ff-11ea-8784-a7fdfef65b9b.jpg)

**System Information**

 - Sonarr Ver. 2.0.0.5344
 - Operating System: Linux Ubuntu 18
 - Mono Version 6.8.0.105

**Comment by Taloth** [comment]
Check the logs to see what's actually going on. Probably need Trace level logs. https://github.com/Sonarr/Sonarr/wiki/Logging-and-Log-Files
