### ISSUE TITLE
Adding Support For Blacklisting File Extensions

### ISSUE THREAD

**Issue by Thunder33345** [Sonarr/Sonarr#3709]
**Describe the problem**
Recently my sonarr instances have been grabbing fake .exe and .zip releases left and right

**Describe any solutions you think might work**
A possible solution is to allow user to manually blacklist file extensions, on per indexer level(or some other scope), but especially on a per indexer level for indexers that the user know that they don't use exe or zips

Another possible solution: to not grab it unless it's past it's release date(so sonarr won't grab early releases, eliminating the chances of grabbing fake releases)

**Additional context**
There's a new trend of fake anime releases, before their scheduled release date, making sonarr grabbing all of it, while this in itself is not harmful(since sonarr won't execute it), it's certainly annoying since sonarr treats it as a "real" release and wont go and grab the real one when it's released, thus clogging up the release with fake releases, needing the users to clean it out by hand

I am not sure if i am allowed to include links as examples, so i wont be and even if it's deleted on some indexer, there's still some aggregation trackers that are slow/not moderated

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/issues/969 covers grabbing before release, but there are a number of series that did at some point during their run release in another country before the release date.

As for blacklisting extensions I’m not sure that’s something we want to control and instead expect download clients to support that behaviour, marking it as failed and letting Sonarr blacklist it afterwards.

@Taloth what do you think about a list of extensions that we end up failing a download if it contains them? We could run it prior to import, for torrents we’d still want to remove from the client, which could have impacts on HnRs or other tracker rules.

**Comment by m-lant** [comment]
Setting a minimum size will weed those out. There's no way there is a legitimate release below 50MB (adjust as required, I don't know how small anime gets), unless it was recorded using PotatoCam 2000.

**Comment by Taloth** [comment]
I'd say get a better indexer. Any indexer that doesn't check for obvious fake .torrent isn't worth their salt. Seriously, where are you getting your anime?

@markus101 We can probably check for video and rar files in .torrent prior to downloading. Prolly better than before import. we could block .exe or even .zip but there could be legitimate cases of .zip for extra's and such. So hence a whitelist instead. (Inevitably someone will have a .torrent with .7z containing the actual vid coz his exotic tracker does it that way.)

**Comment by Thunder33345** [comment]
> As for blacklisting extensions I’m not sure that’s something we want to control and instead expect download clients to support that behaviour, marking it as failed and letting Sonarr blacklist it afterwards.

That's true initially when i made this issue, i failed to realize sonarr has no ability to "look inside" the torrent file (sonarr was suppose to just fetch torrent, and feed it into the client)
It might be possible for certain client using their web ui/api to check, but even so this wouldn't support blackhole clients.
So maybe #969 would been a better all rounded way to resolve this.

> which could have impacts on HnRs or other tracker rules.
> Inevitably someone will have a .torrent with .7z

It certainly shouldn't be enabled by default, but letting user choose to turn it on a per indexer basis
(if your tracker have HnR rules, it's probably decent enough that junk like that wont be getting in)

> Seriously, where are you getting your anime?

Nyaasi, Anime Tosho, was the source of these fake torrents,
Yeah nothing great, maybe I should just start spring cleaning...

> Setting a minimum size will weed those out.

Looks like someone anticipated such
![Torrent size of 1.358 GB](https://user-images.githubusercontent.com/9031498/80366498-f510c400-88bb-11ea-8748-096cfe263143.png)

**Comment by Taloth** [comment]
You asked them to filter out fake stuff? They should be able to do so for obvious fakes.

**Comment by kellyinvestor** [comment]
Adding a delay function that actually delays would help.  These are often removed within minutes, but sonarr has already grabbed them by then.

**Comment by markus101** [comment]
There is a delay system, as long as it's not the top wanted quality in the profile it will delay. It'd be easy enough to allow any higher quality, restrict grabs by having a super small max size or a huge minimum size then set the cutoff properly if necessary, but the default profiles would allow for delaying by default for weekly airings.

**Comment by bakerboy448** [comment]
No plans for this at this time.

See various solutions commented above
