### ISSUE TITLE
Release profile edit screen chops off function menu

### ISSUE THREAD

**Issue by rschmetzer** [Sonarr/Sonarr#3710]
**Describe the bug**
On the current  version of Firefox when trying to edit a Release Profile, the menu options icon on the right hand side is almost completely chopped off.

**Screenshots**
![image](https://user-images.githubusercontent.com/24754031/80370582-6cb00600-885e-11ea-9516-e4f3d100ed4a.png)

**System Information**

 - Sonarr Version: 3.0.3.774
 - Operating System: Windows 10
 - .net Framework (Windows) 4.0.30319

**UI Bugs:**
 - OS: Windows
 - Browser: Firefox
 - Version: 75.0

**Additional context**
This could have existed prior to this version of Sonarr.  Just discovered it.

**Comment by thezoggy** [comment]
trying myself in firefox 74 (havent restarted to upgrade)
![img](http://zoggy.net/firefox_2020-04-28_12-54-17.png)

**Comment by rschmetzer** [comment]
Issue is still present in Firefox 76.
