### ISSUE TITLE
Real IP not logged behind reverse proxy for authentication failures

### ISSUE THREAD

**Issue by rg9400** [Sonarr/Sonarr#3711]
**Describe the bug**
I use Sonarr behind a reverse proxy, and I have it locked with proxy authentication; however, to use the API remotely with apps such as LunaSea or NZB360, you need to open up the API endpoint since they have no mechanism to authenticate against the server-side authentication. 

To enhance the security of the now open API endpoint, I tested to see if Fail2Ban could be leveraged to ban IPs with consecutive authentication failures; however, it seems like the Arrs are not respecting the Real IP forwarded by NGINX and logging the failing IP to whatever the IP of the reverse proxy is (i.e. 127.0.0.1)

**Logs**
`20-4-27 09:19:12.6|Info|Auth|Auth-Unauthorized ip 127.0.0.1 url 'http://domain.com/sonarr/api/wrongstuff'`

**System Information**

 - Sonarr Version: 3.0.3.774 (applies to all the Arrs though)
 - Operating System: Windows 10 Pro 1909
 - .net Framework 

**Additional context**
NGINX config

```nginx
		location /sonarr/ {
                        # Organizr Authentication
			auth_request /auth-0;
			proxy_pass http://127.0.0.1:8989;
			proxy_set_header    Host                $host;
			proxy_set_header    X-Real-IP           $remote_addr;
			proxy_set_header    X-Forwarded-Host    $server_name;
			proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
			proxy_set_header    X-Forwarded-Proto   $scheme;
			proxy_set_header    X-Forwarded-Ssl     on;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection $connection_upgrade;
			location /sonarr/api { auth_request off;
					proxy_pass http://127.0.0.1:8989/sonarr/api;
			}
		}
```

**Comment by Taloth** [comment]
The challenge with this is to only thrust the X-Real-IP coming from a local ip, otherwise remote clients can just ddos you.

**Comment by rg9400** [comment]
I'm not well versed in this, so please excuse my ignore. Should that be done at the application (Sonarr) end or the reverse proxy (NGINX) end instead? I have some lines to set the X-Forwarded-For header to the real ips listed from trusted sources only, though I am not sure if that is actually solving the concern of others being able to spoof them or not.

Though I guess your concern would be that if someone is not using a reverse proxy, but instead just exposing it via port forwarding, would then be susceptible to that spoofing since they do not have any proxy in front to verify the headers. As of right now, the IPs being logged from those setups are probably correct compared to those using reverse proxies.

**Comment by Taloth** [comment]
> Though I guess your concern would be that if someone is not using a reverse proxy...

Exactly.
