### ISSUE TITLE
Send custom fomatted query to indexers

### ISSUE THREAD

**Issue by Minituff** [Sonarr/Sonarr#3712]
I am trying to download all the episodes for an anime, but Sonarr is missing a search term that is required to find this episode.

I have the show listed under the `anime` category. When I run a search, these are the queries that are sent to my indexers:

- My Hero Academia 84
- Boku no Hero Academia 4th Season 84
- Boku no Hero Academia S4 84
- My Hero Academy S4 84
- My Hero Academia 4th Season 84
- Boku No Hero Academia 2019 84
- My Hero Academia S4 84
- Boku no Hero Academia 84

However, in order to find the episode I am looking for, I need Sonarr to search for:
-  **My Hero Academia S4 E21**

I am requesting a way to tell Sonarr to send custom queries to my indexers. The format could be similar to how we can customize the episode names like `{Series Title} Season {season:00}`.

I would also like a way to view the query strings inside the GUI. The only way I was able to find them was to send the queries to NZBHydra2 and I can view the query history in there.

I appreciate the help.

**Comment by markus101** [comment]
> I would also like a way to view the query strings inside the GUI.

They're not in the GUI, but you can check debug logs.

Custom queries is covered by https://github.com/Sonarr/Sonarr/issues/1128
