### ISSUE TITLE
Option to auto-move entire shows between drive folders (on-demand, similar to file name organizing)

### ISSUE THREAD

**Issue by douglas24** [Sonarr/Sonarr#3713]
**Describe the problem**
Ability for Sonarr to move entire show folders between mapped folders (e.g. E:/sonarr/, F:/sonarr/, G:/sonarr/) based on space availability and prioritization

**Describe any solutions you think might work**
Maybe a dedicated tab in the 'Settings' section for 'Disks' where each disk that sonarr has a show location for will appear and users can set a minimum of free space to try and keep (e.g. for the main download drive) or maximum usage size in percent or MB/GB (e.g. 100% for a drive dedicated to only file storage).

**Additional context**
I'm not completely sure on the best way to implement the feature (that seems like something the devs would know best), but having to manually balance show files between drives is difficult and seems like something that could be easily accomplished in Sonarr.

Sonarr already knows the total available space on drives (System page) and the total size of files for each show. It shouldn't be hard for it to calculate if drive E: is running low on space and automatically move show X to G:/sonarr/ mapped path where other shows already exist to free up space on E:

Understandably some users may not want to make it an automatic feature, but on-demand instead so that a button can be pushed an a list of planned show moves can be shown for approval (similar to the file renaming organizing page).

I understand this is probably a low priority but useful. The same feature could hopefully be forked/integrated into Radarr as well.

**Comment by markus101** [comment]
We don't have plans to balance series on different drives based on available disk space. In v3 you can move series via the UI, so you could also do that via the API in an app/script to handle the logic of it.

**Comment by douglas24** [comment]
> We don't have plans to balance series on different drives based on available disk space. In v3 you can move series via the UI, so you could also do that via the API in an app/script to handle the logic of it.

Alright, I'll take a look at upgrading to v3. I've been putting it off since it was still flagged as beta last I saw.
