### ISSUE TITLE
Improve Series Naming

### ISSUE THREAD

**Issue by LongJohn-Silver** [Sonarr/Sonarr#3714]
**Describe the problem**
The capabilities for Sonarr to rename files and directories needs some improvement.

**Describe any solutions you think might work**
First of all, there's no option to add an author's category, which I think it's important if for example you would like to create a bigger folder with all of their works.
An example:

> - Shinichirō Watanabe:
>. Cowboy Bebop
>. Samurai Champloo
>. Kids on the Slope
>. etc

Then, I think that using "-" as a separator and "()" for the release date is not a good idea. 

Not all TV shows are productions from the United States, and some people (like me) would like to have the original name on its original language and a translation that they can understand, this is even more important for people who speak more than one language.

An example:
> The Pretenders - Los Simuladores

And when it comes to the "()", I think they can be used for romanizations of languages that do not use the roman alphabet.

An example:
> Alisa Knows What to Do! - Алиса знает, что делать! (Alisa znaet, shto delat!)

Therefore, I think the best option as a separator would be the ";".

An example:
>Author; Release Date; Translation - Original Title in its Original Language (Romanization)
>Yasuyuki Ueda; 1998; Serial Experiments Lain - シリアルエクスペリメンツレイン (Shiriaru Ekusuperimentsu Rein)

**Additional context**
I know this may seem a little extreme and long, but not everything one would watch is going to be from countries that to do not use the roman alphabet, since most of the content creation occurs in Europe and the USA. I also don't know the implications of the new system when it comes to interpretation by other software, but I wanted to create this issue anyway and see what can be done, at least partially.

**Comment by markus101** [comment]
> First of all, there's no option to add an author's category

This isn't something available to Sonarr from TheTVDB and not something we're planning to support, at least in naming on disk.

> Not all TV shows are productions from the United States, and some people (like me) would like to have the original name on its original language and a translation that they can understand, this is even more important for people who speak more than one language.

Getting series titles and information in other languages is covered by https://github.com/Sonarr/Sonarr/issues/269
