### ISSUE TITLE
RSS watch for season packs for cut-off unmet upgrades?

### ISSUE THREAD

**Issue by douglas24** [Sonarr/Sonarr#3715]
**Describe the problem**
Does the RSS feature watch for season packs for upgrading old(er) shows to things like BDRips when the cut-off for that season or any episode(s) in that season are unmet?

**Describe any solutions you think might work**
Add the ability for RSS monitor to grab newly uploaded season packs when the cut-off for that season or any episode(s) in that season are unmet (Grabbing the whole season to upgrade a single episode makes sense as long as proper seed ratio is set to not leech).

**Additional context**
Maybe this feature already exists and I just haven't been able to notice or find documentation on it? I've only ever seen sonarr grab a season pack for a fresh season not for upgrading something older. With more shows being added to streaming this opportunity happens a lot more often. It would be nice to take advantage of it.

**Comment by markus101** [comment]
Yes, that's how it works as long as they are monitored and the cutoff isn't met for any episode.

In the future, please use the forums or subreddit for questions.

**Comment by Taloth** [comment]
> BDRips when the cut-off for that season or any episode(s) in that season are unmet

**all** episodes must be upgrades for the pack to be accepted
