### ISSUE TITLE
Import Failed Error-Completed Downloads

### ISSUE THREAD

**Issue by lexguy2007** [Sonarr/Sonarr#3717]
**Describe the bug**
Recently I have started seeing this error "_Import failed, path does not exist or is not accessible by Sonarr: C:\NZBGet\completed TV shows\Name of the TV Show file Obfuscated. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder_"

This seems to have started after a recent (in the last month or so) of Sonarr. 
The files ARE being imported to the correct destination and no longer show in the file directory but they show in Sonarr Queue as WAITING TO IMPORT and they show in my NZBGet History whereas before they were removed. 

**System Information**
- Sonarr Version: [3.0.3.777 Phantom-Develop branch]
 - Operating System: [Windows 10]

Not sure what is causing this.

**Comment by markus101** [comment]
Sonarr doesn't have a record of importing them and still sees them in NZBget's history.

Removing them from NZBget either through NZBget directly or through Sonarr's queue will be the fix for existing items there. If you're having issues with _new_ imports from that point forward, we'll need trace logs of the import. Debug/trace logs are not optional, without at least debug logs showing this issue this isn't a bug we can begin to investigate.

> they show in my NZBGet History whereas before they were removed.

Is remove completed downloads enabled in Sonarr?

**Comment by lexguy2007** [comment]
> Sonarr doesn't have a record of importing them and still sees them in NZBget's history.
> 
> Removing them from NZBget either through NZBget directly or through Sonarr's queue will be the fix for existing items there. 

That is what I am having to do now. It was automatically removing them before.

>If you're having issues with _new_ imports from that point forward, we'll need trace logs of the import. Debug/trace logs are not optional, without at least debug logs showing this issue this isn't a bug we can begin to investigate.
> 
Debug Log https://pastebin.com/FkmvEygP

Trace Log https://pastebin.com/bxq4phNV



> > they show in my NZBGet History whereas before they were removed.
> 
> Is remove completed downloads enabled in Sonarr?

Yes I have REMOVE COMPLETED DOWNLOADS enabled in Sonarr

**Comment by markus101** [comment]
The only issue I see is:

> 20-4-28 14:40:28.3|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Quality of file (SDTV v1) does not match quality of grabbed release (Unknown v1)

This is already being improved by https://github.com/Sonarr/Sonarr/pull/3708

Do you have logs of a successful import that is not removed?

**Comment by lexguy2007** [comment]
I'm so sorry. I grabbed the wrong bit of logs. Let me recreate the issue exactly and I will paste the correct logs. Sorry again and thank you for helping.

**Comment by lexguy2007** [comment]
> The only issue I see is:
> 
> > 20-4-28 14:40:28.3|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Quality of file (SDTV v1) does not match quality of grabbed release (Unknown v1)
> 
> This is already being improved by #3708
> 
> Do you have logs of a successful import that is not removed?

Here are the Debug and Trace logs for one that Downloaded but was not removed. I confirmed that the file was indeed moved to the proper directory and physically removed from my TV Show Download directory. It is just left in Sonarr with the error and in my NZBGet History.

Trace Log https://pastebin.com/bxq4phNV

Debug Log https://pastebin.com/FkmvEygP

**Comment by markus101** [comment]
Thanks for the logs, helped find a case where we weren't marking things as imported when an external app/script told Sonarr to import via the API.

**Comment by lexguy2007** [comment]
Thank you for fixing this. I appreciate your help and all the work you do.
