### ISSUE TITLE
[SERIES NAME ISSUE] tvdb: 80725 picking up tvdb: 296512 releases

### ISSUE THREAD

**Issue by markmattdocker** [Sonarr/Sonarr#3720]
**Describe the bug**
Keeping up with the Kardashians (tvdb 80725) is not marking releases for Keeping up with the Kaimanawas (tvdb 296512) as "wrong series".

**Screenshots**
![screenshot](https://i.imgur.com/8XNsnPZ.png)

**Logs**
Link to debug or trace log files.

`20-4-29 16:43:34.4|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0
20-4-29 16:46:19.4|Info|NzbSearchService|Searching 2 indexers for [Keeping Up with the Kardashians : S01E07]
20-4-29 16:46:22.1|Info|DownloadDecisionMaker|Processing 7 releases
20-4-29 16:46:22.9|Info|Nzbget|Adding report [Keeping.Up.With.The.Kaimanawas.S01E07.HDTV.x264-FiHTV] to the queue.
20-4-29 16:46:23.1|Info|DownloadService|Report sent to nzbget. Keeping.Up.With.The.Kaimanawas.S01E07.HDTV.x264-FiHTV
20-4-29 16:46:23.1|Info|EpisodeSearchService|Episode search completed. 1 reports downloaded.
20-4-29 16:47:07.3|Info|SceneMappingService|Updating Scene mappings
20-4-29 16:47:08.7|Info|RefreshSeriesService|Updating Keeping Up with the Kardashians
20-4-29 16:47:09.8|Info|RefreshEpisodeService|Starting episode info refresh for: [80725][Keeping Up with the Kardashians]
20-4-29 16:47:10.0|Info|RefreshEpisodeService|Finished episode refresh for series: [80725][Keeping Up with the Kardashians].
20-4-29 16:47:10.0|Info|DiskScanService|Scanning Keeping Up with the Kardashians
20-4-29 16:47:10.1|Info|DiskScanService|Completed scanning disk for Keeping Up with the Kardashians
20-4-29 16:47:10.2|Info|ExistingMetadataImporter|Found 0 existing metadata files
20-4-29 16:47:10.2|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
20-4-29 16:47:10.2|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
20-4-29 16:47:10.2|Info|ExistingExtraFileService|Found 0 extra files
20-4-29 16:47:14.0|Info|RefreshSeriesService|Updating Keeping Up with the Kardashians
20-4-29 16:47:14.4|Info|RefreshEpisodeService|Starting episode info refresh for: [80725][Keeping Up with the Kardashians]
20-4-29 16:47:14.5|Info|RefreshEpisodeService|Finished episode refresh for series: [80725][Keeping Up with the Kardashians].
20-4-29 16:47:14.6|Info|DiskScanService|Scanning Keeping Up with the Kardashians
20-4-29 16:47:14.7|Info|DiskScanService|Completed scanning disk for Keeping Up with the Kardashians
20-4-29 16:47:14.7|Info|ExistingMetadataImporter|Found 0 existing metadata files
20-4-29 16:47:14.8|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
20-4-29 16:47:14.8|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
20-4-29 16:47:14.8|Info|ExistingExtraFileService|Found 0 extra files`

**System Information**

 - Sonarr Version: 3.0.3.780
 - Operating System: Windows 10 Pronet x64
 - .net Framework 4.8

**Additional context**

**Comment by markus101** [comment]
Your indexer has those linked to the wrong TVDB series, you can see this by going to the details page for those releases.

Next time please use the forums for mismatches like this and include a link to the full debug logs.
