### ISSUE TITLE
v3 - without TVDB 'Deleted' programs cannot add episodes

### ISSUE THREAD

**Issue by whemever** [Sonarr/Sonarr#3721]
I have Ghost in the Shell SAC 2045 in my SONARR list, its been there for some time and for a while was responding to TVDB. During this period it downloaded the fact that season 1 had 12 episodes.

These episodes have now arrived, I had to download them by hand and move them to the appropriate location, yet when I click on the Refresh and Scan button, it fails to even scan for the files, as it says that it can't find the program and that it may have been deleted.

I expected SONARR to understand that according to it's own stored info that (in this case) season 1 had 12 episodes and to match the files stored in the correct location against the 12 episodes in the database

![GITS](https://user-images.githubusercontent.com/17473475/80704987-81e69800-8add-11ea-8631-97037951f7b6.jpg)

![Events](https://user-images.githubusercontent.com/17473475/80705003-87dc7900-8add-11ea-929b-093182eb87b1.jpg)

![Health](https://user-images.githubusercontent.com/17473475/80705021-8ca12d00-8add-11ea-9c24-db50aadbb207.jpg)

Sorry for the second screen 

**System Information**

 - Sonarr Version: 3.0.3.780
 - Operating System: Synology NAS DS3617xs running DSM 6.2.2-24922 Update 6
 - .net Framework Mono 5.20.1.34

**Comment by whemever** [comment]
OK I see now that for some reason TVDB have decided to move this whole new series to be part of the Stand Alone Complex set of stories, and have marked it as season 3. Whilst it provides me with a cure for this Exact series, it does not allow workarounds for any of the other programs which are no longer available for whatever reason

**Comment by markus101** [comment]
Except in the edge case where TVDB's API has mucked something up and is reporting something as deleted there is a reason it was deleted, be it a duplicate entry or it was merged to a different season of a different series. We don't have plans to optimize for working with legitimate deleted series, including rescanning, but we do try to redirect duplicates to the correct series when we're aware that they exist.
