### ISSUE TITLE
v3 - Offer the option to use the Beta version of TVDB

### ISSUE THREAD

**Issue by whemever** [Sonarr/Sonarr#3722]
With all the problems the 'base' version of TVDB is displaying currently, it may be worth considering offering the option of using the beta version of the new form of TVDB in the mean time.

From what I can see everything to the end user (including the API) is the same except for the webaddress - the beta is at Https://beta.thetvdb.com

Theoretically if it is just the address that is different, switching between the 2 should be as simple as changing the address and probably the API key - if you could keep both you could allow us the ability to switch between them

**Comment by markus101** [comment]
Sonarr does not communicate with TheTVDB directly, so there is no switching between API versions. As for linking the the beta site, we don't have plans to support that.

**Comment by whemever** [comment]
Hi there,

 

Thanks for answering those queries, the beta was a suggestion to get round some of the funnies we’re seeing with TVDB, but I wasn’t up to speed as I thought you did query TVDB, it’s a case of find out something new each day.

 

 

In regard to the other issue about matching, I can understand the point you raise about this specific instance, however there are other series which have been affected and if you have them in your SONARR database, how are you supposed to index them off, to match the entries in the SONARR database with episodes that you have downloaded?

 

Many thanks for the prompt turn round

 

Simon
