### ISSUE TITLE
Incorrect detection of Season number

### ISSUE THREAD

**Issue by Draxter** [Sonarr/Sonarr#3724]
**Describe the bug**
Sonarr incorrectly detects season number due to the presence of the release year of the TV show within the filename.

**Screenshots**
![Image](https://i.postimg.cc/J0N3kkvV/Screenshot-2020-05-01-Activity-Sonarr.png)

**Logs**
Import Rejected: Has the same filesize as existing file

**System Information**

 -  Sonarr Ver. 2.0.0.5344 
 - Docker Container

**Comment by Taloth** [comment]
What's wrong about it?
Teletubbies started in 1997.
Teletubbies 2015 started in 2015. And it's clearly not season one on Teletubbies. https://www.thetvdb.com/series/teletubbies/seasons/official/15
