### ISSUE TITLE
Cutoff Unmet: Search All

### ISSUE THREAD

**Issue by azumukupoe** [Sonarr/Sonarr#3727]
**Describe the problem**
Search All button for Cutoff Unmet section like Radarr

**Describe any solutions you think might work**
A clear and concise description of any solutions or features you've considered.

**Additional context**
![image](https://user-images.githubusercontent.com/31339007/80892897-af635980-8d08-11ea-8c93-63b761e6487a.png)

**Comment by Taloth** [comment]
v3 beta
