### ISSUE TITLE
Sonarr defaults to HDTV for Anime, even though nowadays most Anime is WEBDL

### ISSUE THREAD

**Issue by kittydoor** [Sonarr/Sonarr#3728]
**Describe the bug**

When importing a 720p or 1080p anime episode, or manually or interactively searching and downloading it via torrent, if the release is Bluray, Sonarr can often correctly detect this.

However, as almost no non-Bluray releases specify WEBDL explicitly, for them Sonarr defaults to HDTV.

This should be changed to be the other way around, as it is very rare for Anime to be HDTV so it makes more sense to make marking it as HDTV the explicit action (for example for older batch releases), as opposed to having to mark every single new episode as WEBDL manually due to the faulty detection. 

**System Information**

 - Sonarr Version: v3
 - Operating System: Linux

**Comment by markus101** [comment]
If the file name does not contain a source it is assumed to be a TV source, we don’t have plans to override that based on the series type.
