### ISSUE TITLE
Can’t See or Add Emma. (AppleTV+ 2020)

### ISSUE THREAD

**Issue by imseandavis** [Sonarr/Sonarr#3729]
**Describe the bug**
When I do “Add New Series” and search for Emma. or tvdb:132908 it comes back blank. Any other show Ive searched works fine.

**Screenshots**
N/A

**Logs**
20-5-3 16:23:34.7|Debug|Api|[GET] /api/v3/series/lookup?term=tvdb%3A%20132908: 200.OK (691 ms)
20-5-3 16:23:38.0|Debug|Api|[GET] /api/v3/series/lookup?term=tvdb%3A132908: 200.OK (1056 ms)
20-5-3 16:23:41.7|Debug|Api|[GET] /api/v3/health: 200.OK (1 ms)
20-5-3 16:23:41.7|Debug|Api|[GET] /api/v3/system/status: 200.OK (1 ms)
20-5-3 16:23:41.9|Debug|Api|[GET] /api/v3/diskspace: 200.OK (181 ms)
20-5-3 16:23:49.1|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)

**System Information**

Version - 3.0.3.780
Mono Version - 5.20.1.34
OS - Synology 3615x - DSM 6.2.4 - Community App + In App Upgrade To 3.0.3.780

**Comment by markus101** [comment]
That’s listed as a movie, not a TV show.
