### ISSUE TITLE
Error when adding Download Station client - Related to certificate verification

### ISSUE THREAD

**Issue by Vlayke** [Sonarr/Sonarr#3731]
**Describe the bug**
In Sonarr v3 it appears that SSL certificates are being verified, as opposed to v2.
When configuring Synology Download Station as a client, using IP address as an address and enabling SSL, connectivity check fails with the following message:
"Unknown exception: Unable to connect to Diskstation, please check your settings"
This is due to the fact that SSL certificate on Synology is tied to DNS name and if IP address is used instead there is a mismatch, which there's no was to acknowledge.

If DNS name is used instead of IP address and all other settings are left as they are, connection suceeds.

**Screenshots**
![image](https://user-images.githubusercontent.com/12030056/80947133-c761d880-8def-11ea-8718-a059e69ddf86.png)
Failed connection

![image](https://user-images.githubusercontent.com/12030056/80947213-f11aff80-8def-11ea-8bc5-aa24cf880dbc.png)
Successful connection (I replaced my actual DNS name with an example)

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 3.0.3.784
 - Operating System: Synology DSM 6.2.2-24922 Update 4
 - mono Version: 5.20.1.34

**Additional context**
This is a changed behavior from Sonarr v2, to Sonarr v3, running directly on Synology.

**Comment by Taloth** [comment]
This is by design. A certificate without domain name would be pointless.

You can turn off certificate validation for local addresses in Settings->General... or just keep the dns.

**Comment by Taloth** [comment]
Based on Discord you suggest a different error message to make the problem more apparent.

**Comment by Vlayke** [comment]
I don't really agree that certificate without domain name is pointless. 
But even if that were the case, please make either error message more descriptive or add an instruction in the config screen that would make sure that it's understandable that SSL has to be paired with DNS name and IP address is not usable.

**Comment by bakerboy448** [comment]
likely was fixed by https://github.com/Sonarr/Sonarr/commit/91c395d0c6fb3c9cdde160258aeb681ddb82c874

This bug/issue seems stale.  Please check and see if it is still an issue on the recent v3 builds.  If it is an issue please open a new GHI with logs and full detail.
