### ISSUE TITLE
Change quality from download screen

### ISSUE THREAD

**Issue by raynotroy** [Sonarr/Sonarr#3732]
Sometimes I manually download a file that is rejected because it does not contain one of the required terms.  I want it to download the file and automatically replace it with a file that does contain one of the required terms when that file is available.

I've been solving this right now by downloading a rejected release (480p web-dl) then going to the series page and setting the quality of the file to SDTV so that it will be replaced.  I would like to be able to do this directly from the manual download screen or the calendar page (or both?).

Thanks

**Comment by markus101** [comment]
You can do it from the series page, Manage Episode Files then set the quality. No plans to do that right from interactive search or calendar.
