### ISSUE TITLE
Add option to set per show download location

### ISSUE THREAD

**Issue by florkssork** [Sonarr/Sonarr#3736]
**Describe the problem**
Right now all downloads go to the clients default download location and are then copied (and may be removed after torrent is marked as done/after seeding). As of now, some users have files moving from one drive to another and having a hard time managing or anticipate free storage space.

**Describe any solutions you think might work**
To better be able to manage file storage, users should have the option (set globally and per show) to have torrents instead be downloaded to the correct folder directly (based on naming setup, if using season folders, and so on) and just have the files renamed after torrent is done. This way tools like Plex will still correctly find the file in the correct location and there would be a lot less copied data, saving on the users hard disk space.

This might only work on some clients depending on the API I guess but without doing any in-depth research I'm guessing most APIs support a "save path"-parameter when adding a new torrent.

**Comment by markus101** [comment]
This isn't something we have plans to implement, at least at this time.
