### ISSUE TITLE
Serie not showing episodes that are not on disk

### ISSUE THREAD

**Issue by pven** [Sonarr/Sonarr#3737]
When I look at a serie I see season 1 has 26 episodes. When looking at the overview it shows 3/3. I've downloaded 3 episodes out of 26. So I expect to see 3/26 in there.

Screenshot:
![2020-05-07 09_36_34-The Avengers - Sonarr](https://user-images.githubusercontent.com/671621/81267327-9202f800-9046-11ea-9d76-b3114c5a7488.png)

 - Sonarr Version: 3.0.3.790
 - Operating System: Synology DSM 6.2
 - mono: 5.20.1.34

**Comment by markus101** [comment]
IF they aren't monitored (the season isn't so the episodes probably aren't) then they don't count. You have 3/0 which becomes 3/3 because it can'ts it if it's monitored or has a file.
