### ISSUE TITLE
wrong website download redirects for linux

### ISSUE THREAD

**Issue by mooseh** [Sonarr/Sonarr#3740]
Hi There

Your links for for linux are redirecting to the windows downloads.
https://services.sonarr.tv/v1/download/phantom-develop/latest?version=3&os=linux
is downloading Sonarr.phantom-develop.3.0.3.803.windows.zip

**Comment by Taloth** [comment]
Link is fine for me. You'll have to post the http headers of the redirect.

**Comment by markus101** [comment]
We can reopen if headers are provided.
