### ISSUE TITLE
Snap Path Invalid Path

### ISSUE THREAD

**Issue by urbandroid** [Sonarr/Sonarr#3742]
When installed with snap since sonarr directory is read only can't add path new series.

ame:      sonarr
summary:   Smart PVR for newsgroup and bittorrent users
publisher: Alberto Donato (ack)
store-url: https://snapcraft.io/sonarr
contact:   https://github.com/albertodonato/sonarr-snap
license:   GPL-3.0+
description: |
  Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple
  RSS
  feeds for new episodes of your favorite shows and will grab, sort and
  rename
  them. It can also be configured to automatically upgrade the quality of
  files
  already downloaded when a better quality format becomes available.
  
  The web interface is accessible by default at http://localhost:8989
  
  See https://sonarr.tv for more details.
services:
  sonarr.nzbdrone: simple, enabled, active
snap-id:      TSZAyHNSnTl1RyVD6AcCYH53XVwxIjGX
tracking:     latest/stable
refresh-date: today at 05:00 +03
channels:
  latest/stable:    2.0.0.5344 2020-03-21 (225) 31MB -
  latest/candidate: ↑                                
  latest/beta:      ↑                                
  latest/edge:      2.0.0.5344 2020-04-23 (237) 31MB -
installed:          2.0.0.5344            (225) 31MB -

clean install

**Comment by markus101** [comment]
Please use the forums for support, sounds like it could be permissions though.

**Comment by urbandroid** [comment]
> Please use the forums for support, sounds like it could be permissions though.

Stop assuming, with 0 knowledge what it is. this is not a support ticket you moron, your stupid app doesn't use correct directory in snap packaging to save its file so it is useless.

Yes it is a permission problem and what at fault is your brain dead packaging you can't access outside of your own app directory if you not created correct connection with snap which your low iq app like you doesn't. It will be okay if your low iq app like you used its own directory but it doesn't do that either.

**Comment by markus101** [comment]
So... a snap package we didn’t create is the issue and I’m the moron. Try again. Good luck.
