### ISSUE TITLE
Update status icon while waiting to import/importing

### ISSUE THREAD

**Issue by douglas24** [Sonarr/Sonarr#3743]
**Describe the problem**
There is currently no indicator of what torrent(s) in the Activity->Queue are being **automatically** imported when they've finished downloading.

**Describe any solutions you think might work**
Rather than add a new column for status, finished downloads already change their Timeleft column to 00:00:00 when Sonarr is either auto importing, soon to import, or will not auto import because of an issue or conflict.

**Additional context**
Any indicator of downloads in the Queue which are auto importing or soon to be imported would be useful to set them apart from downloads which have issues (need manual attention). While it may be easier for a new column option to be added to deal with this than amend the Timeleft column, it would be nice to make use of an existing default column that, when a download is completed, provides no further useful information (e.g. 00:00:00) when it could continue to show status relevant to the time left by saying whether it is being auto imported (or not).

This is likely a low priority QoL feature request as it doesn't deal with anything broken.

**Comment by m-lant** [comment]
Downloads with issues will indicate that with an icon, so I'm not sure I see the (pun slightly intended) issue?

**Comment by Derkades** [comment]
As far as I know the only way to check if sonarr is moving/copying a completed download is in the logs, not in the user interface. It would be nice to see that it's doing something in the web interface

**Comment by douglas24** [comment]
It doesn't show an icon in the queue view if a download isn't being imported and needs manual attention from what I've observed. Even if there isn't an issue, a UI change to show that a finished download is importing would be a nice feature to add because downloads can also be stuck on 00:00:00 when it's continuing to be seeded/queued for import when seeding is done. Calling this an 'issue' is probably a bit overstating it, that's why it's a feature request. :)

**Comment by markus101** [comment]
It absolutely shows you a different icon if there is an issue importing, it always has. The icon is the status timeleft wont be changing to importing or anything else, but shouldn’t be shown when it’s waiting to import/importing.
