### ISSUE TITLE
Completely Disable Quality Definitions

### ISSUE THREAD

**Issue by mason1171** [Sonarr/Sonarr#3744]
**Describe the problem**
Can there be an option implemented to completely disable the quality definitions feature?  In my opinion, its too much hassle to properly configure the sliders to account for every release as the sizing varies greatly between different releases/groups and codecs. 

**Describe any solutions you think might work**
Rather than using the definitions, can Sonarr utilize the release profiles and scoring system to completely ignore file size?

**Comment by markus101** [comment]
Just slide the limit to the edges and size would be irrelevant:
![image](https://user-images.githubusercontent.com/413544/81741783-eac1fe80-9453-11ea-82cb-c9f1258692b5.png)

**Comment by mason1171** [comment]
Oh. Thanks Markus, that fixed my issue. I appreciate it
