### ISSUE TITLE
Possibility to add/assign 'tags' to 'profile'

### ISSUE THREAD

**Issue by SirSillyButt** [Sonarr/Sonarr#3746]
**Describe the problem**
Noticed that 'Tags' has to be added manually to each show added/imported despite if using direct Sonarr UI or other 3rd party software like Ombi. I believe that it would be possible to add possibility to assign already created 'Tags' to created 'Profiles' that after adding TV Show/Anime with specific 'Profile' would grant 'Tag' which was selected in 'Profile' settings. Maybe it is not that really necessary for TV shows, but it would really improve anime search via indexers if you are looking for a specific release or specific video format like HEVC to be selected only.
As well it would improve automation while requesting through 3rd party software like Ombi and would lower the amount of human interaction needed after adding the TV show/Anime.

**Comment by markus101** [comment]
In v3 you can add tags when adding the series. No plans for linking tags to series via profiles though.
