### ISSUE TITLE
System -> Health: Cannot install update because startup folder '/opt/NzbDrone' is not writable by the user 'sonarr'.  Sonarr is the owner of the folder

### ISSUE THREAD

**Issue by Ackis** [Sonarr/Sonarr#3748]
**Describe the bug**
Sonarr owns the folder /opt/NzbDrone, however System Health complains:

> Cannot install update because startup folder '/opt/NzbDrone' is not writable by the user 'sonarr'.

**Logs**
There's nothing I've been able to find so far.

**System Information**

 - Sonarr Version: 2.0.0.5344 w/ Mono 6.8.0.123

**Additional context**

Sorry for the vague bug report but it's all I have to go on. It's not detecting the permissions correctly.

**Comment by markus101** [comment]
Please use the forums for support.

Sonarr tries to write to the folder, if that fails it can't write to it.

**Comment by Ackis** [comment]
Sonarr already has full access to the folder it's complaining about.  I even redid a `chown -R sonarr /opt/NzbDrone` to be safe - sometimes permissions can be messed up for no reason.  Still nothing.

I'm not asking for support, I'm reporting a bug - a vague one as I don't have log information (I'll get it if you can give me specifics to look for), but a bug none-the-less.
