### ISSUE TITLE
"Specials" appears in middle of Seasons 

### ISSUE THREAD

**Issue by chrono-badger** [Sonarr/Sonarr#3750]
The Specials section now appears in the middle of the Seasons list...
Attached image shows it hanging out between season 3 and 4, but it moves to different locations depending on the show.

Recreated in Chrome & Edge (old Edge, not checked the new chromium one). 

Sonarr Version 3.0.3.809

![special](https://user-images.githubusercontent.com/26445860/81972983-5d310b00-961b-11ea-9b81-c67c4992c739.PNG)

**Comment by Taloth** [comment]
I know what this is... thanks for reporting.

**Comment by Taloth** [comment]
It should be fixed if you refresh the show in about 1 hour from now for Continuing shows, and about 5 hours for Ended shows. Could be sooner, depends on cache expiration.
