### ISSUE TITLE
Sonarr not scanning for unmapped folders

### ISSUE THREAD

**Issue by kahn10** [Sonarr/Sonarr#3751]
**Describe the bug**
Sonarr does not scan for unmapped folders at all. I currently have two root folders mapped. Under Media Management, both folders show "0" under "Unmapped Folders". The problem persists with my existing database and with a new one with a single series added.

Going to "Import" and clicking on one of the root drives gives the message:
All series in /trans-temp/post-trans/TV Shows - Organized have been imported

The folder is a Google Drive, and Sonarr is inside a docker image. I have tried configuring the mount as a docker volume and as a bind, and have tried rclone, Google File Stream, and CyberDuck as the program managing the connection.

The "Rescan Series Folder after Refresh" setting is currently set to Always, though the problem persists regardless of its setting. 

I can browse the folders through the Sonarr interface and can create a new folder or file in the root folder using the docker sh interface. Episodes and seasons manually imported using the DownloadedEpisodesScan api call copy over without trouble.

**Logs**
Nothing in the logs seem to indicate it is attempting to scan these folders
```
20-5-14 20:02:00.6|Info|OwinHostController|Listening on the following URLs:
20-5-14 20:02:00.7|Info|OwinHostController|  http://*:8989/
20-5-14 20:02:04.3|Info|SonarrBootstrapper|Starting Web Server
20-5-14 20:02:09.0|Info|UpdaterConfigProvider|Update mechanism BuiltIn not supported in the current configuration, changing to Docker.
20-5-14 20:02:12.5|Info|UpdaterConfigProvider|External updater uses branch phantom-develop instead of the currently selected master, changing to phantom-develop.
20-5-14 20:02:14.4|Info|QualityProfileService|Setting up default quality profiles
20-5-14 20:02:15.3|Info|LanguageProfileService|Setting up default language profiles
20-5-14 20:05:45.2|Info|AddSeriesService|Adding Series [72389][3rd Rock from the Sun] Path: [/trans-temp/post-trans/TV Shows - Organized/3rd Rock from the Sun]
20-5-14 20:05:45.7|Info|RefreshSeriesService|Updating 3rd Rock from the Sun
20-5-14 20:05:46.6|Info|RefreshEpisodeService|Starting episode info refresh for: [72389][3rd Rock from the Sun]
20-5-14 20:05:47.2|Info|RefreshEpisodeService|Finished episode refresh for series: [72389][3rd Rock from the Sun].
20-5-14 20:05:48.1|Info|MediaCoverService|Downloading Banner for [72389][3rd Rock from the Sun] https://artworks.thetvdb.com/banners/graphical/72389-g2.jpg
20-5-14 20:05:54.6|Info|DiskScanService|Scanning 3rd Rock from the Sun
20-5-14 20:05:54.8|Info|MediaCoverService|Downloading Poster for [72389][3rd Rock from the Sun] https://artworks.thetvdb.com/banners/posters/72389-2.jpg
20-5-14 20:05:55.7|Info|MediaCoverService|Downloading Fanart for [72389][3rd Rock from the Sun] https://artworks.thetvdb.com/banners/fanart/original/72389-1.jpg
20-5-14 20:08:15.4|Info|DiskScanService|Completed scanning disk for 3rd Rock from the Sun
20-5-14 20:08:15.6|Info|SeriesScannedHandler|[3rd Rock from the Sun] was recently added, performing post-add actions
20-5-14 20:10:51.4|Info|ExistingMetadataImporter|Found 281 existing metadata files
20-5-14 20:10:53.6|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
20-5-14 20:10:54.3|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
20-5-14 20:10:54.5|Info|ExistingExtraFileService|Found 0 extra files
20-5-14 20:11:04.1|Info|SceneMappingService|Updating Scene mappings
20-5-14 20:11:11.5|Info|RefreshSeriesService|Updating 3rd Rock from the Sun
20-5-14 20:11:12.4|Info|RefreshEpisodeService|Starting episode info refresh for: [72389][3rd Rock from the Sun]
20-5-14 20:11:13.0|Info|RefreshEpisodeService|Finished episode refresh for series: [72389][3rd Rock from the Sun].
20-5-14 20:11:13.3|Info|DiskScanService|Scanning 3rd Rock from the Sun
20-5-14 20:11:36.7|Info|DiskScanService|Completed scanning disk for 3rd Rock from the Sun
20-5-14 20:11:51.1|Info|ExistingMetadataImporter|Found 0 existing metadata files
20-5-14 20:11:51.9|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
20-5-14 20:11:52.8|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
20-5-14 20:11:52.8|Info|ExistingExtraFileService|Found 0 extra files
```

**System Information**

 - Sonarr Version: 3.0.3.809 (Docker: Hotio) (the problem has persisted for the past month at least with each update)
 - Operating System: OSX 10.13.6
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 5.20.1.34

**Comment by markus101** [comment]
Please post the trace logs somewhere and link them here.

**Comment by kahn10** [comment]
[https://drive.google.com/file/d/1O2p4nBtKaHMJ9dGGAlZpC1bNSj67Saf8/view?usp=sharing](url)

I downgraded to 3.0.3.729 by hotio to see if the problem went back that far, which is where these logs were generated, it seems to still persist. I can upgrade it again if you need the most recent version. Thanks!

**Comment by markus101** [comment]
```
20-5-14 20:47:35.1|Trace|Http|Req: 58 [GET] /api/v3/rootFolder
20-5-14 20:47:35.5|Debug|RootFolderService|Generating list of unmapped folders
20-5-14 20:47:40.2|Trace|Http|Res: 58 [GET] /api/v3/rootFolder: 200.OK (5041 ms)
20-5-14 20:47:40.3|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (5041 ms)
```

The root folder is not returning the unmapped folders within 5 seconds and being returned without any unmapped folders. it should be incredibly fast to get folders so you should look at why that's slow, but we may be able to do better here and re-process when selecting the root folder.

**Comment by kahn10** [comment]
Aha, that explains it, and it explains why it stopped working after a point. It's a network folder with a few thousand folders in it, I could see how it might take more than 5 seconds. Thank you for looking into it.

**Comment by Taloth** [comment]
I know someone with 18k folders in one root in the cloud, took 1.5 seconds to list em. But the unmapped folder logic does a bit more.

**Comment by kahn10** [comment]
Sounds like I have something else going on then. If anyone has advice on configuring docker mounts, I'd be happy to PM. Thanks for the feedback, guys.

**Comment by Taloth** [comment]
Well, I was going to keep the issue open to investigate whether our logic doesn't scale at 18k folders....
