### ISSUE TITLE
Serie seasons marked as unmonitored automatically, specials marked as monitored

### ISSUE THREAD

**Issue by Xaroth** [Sonarr/Sonarr#3753]
**Describe the bug**
Sonarr has the tendency to - at irregular intervals - mark a bunch of series' seasons as unmonitored, and selecting unmonitored specials seasons as monitored.

I then have to manually (via Season Pass) select all series, and mark all their episodes as monitored.

This has been going on for quite a while, updating to the 3 branch has not resolved it.

**Screenshots**

**Logs**
[sonarr.debug.1.txt](https://github.com/Sonarr/Sonarr/files/4634887/sonarr.debug.1.txt)
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/4634888/sonarr.debug.txt)
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/4634889/sonarr.txt)
[sonarr.debug.0.txt](https://github.com/Sonarr/Sonarr/files/4634890/sonarr.debug.0.txt)

**System Information**

 - Sonarr Version: 3.0.3.809
 - Operating System: Ubuntu 18.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: 6.8.0.105

**UI Bugs:**
 - OS: [e.g. Windows] N/A
 - Browser: [e.g. chrome, firefox] N/A
 - Version: [e.g. 22] N/A

**Additional context**

As per the logs, you'll see that in [sonarr.debug.1.txt](https://github.com/Sonarr/Sonarr/files/4634887/sonarr.debug.1.txt) I marked all series as monitored just after midnight. I had to do this again today at 16:05 as the same issue happened again.

I have attempted to make and restore a backup, frequent restarts of the application, all to no avail. This issue seems particularly hard to track since the issue doesn't seem to happen at set moments.

**Comment by markus101** [comment]
> This issue seems particularly hard to track since the issue doesn't seem to happen at set moments.
Does it happen after a series refresh? (I don't see one in the logs, but there is a large gap between your logs...).
Are you using Ombi (or similar)?

Trace logs may show what's going on, but the first thing to do do is figure out when it happens, since those are going to be limited in time span. Logs without gaps would also be good.

**Comment by Xaroth** [comment]
The log files attached are the 3 debug logs between two events, there should be no gaps.

The setup I'm using is Plex with Sonarr and Couch, with a single NZBHydra endpoint for nzb feeds and whatnot

Not being able to time when/how it happens is what irks me as well, as I cannot reproduce it, even though it does keep happening.

What is weird is that the debug log shows messages of monitored status being changed, but I don't see anything that indicates they are being removed from monitored status.

**Comment by markus101** [comment]
> The log files attached are the 3 debug logs between two events, there should be no gaps.

`debug.1` ends at: 20-5-15 06:26:51.7
`debug` starts at: 20-5-15 13:47:03.1

More than 7 hours are unaccounted for which should be in `debug.0`

**Comment by Xaroth** [comment]
There is a debug.0 attached though, which starts at 20-5-15 06:26:51.7, and ends at 20-5-15 13:47:03.1

**Comment by markus101** [comment]
🙈 sorry, stopped looking at the links when they went to non-debug.

> What is weird is that the debug log shows messages of monitored status being changed, but I don't see anything that indicates they are being removed from monitored status.

That's because it's going through the season pass logic, if episodes were unmonitored individually then they wouldn't, since everything goes through the API, changing via the UI or directly through the API will log trace events.

I don't see any indication that Sonarr is automatically changing things (it should only do that after adding a series) and my only other thought at the moment is someone has access and is toggling monitoring settings, make sure Sonarr isn't exposed publicly and if it is, it's password protected.

Trace logs will be the next step.

**Comment by Xaroth** [comment]
I have checked all nginx access logs (I even went as far as verifying every internal IP to be accounted for), and it's not allowing external access, so that can be ruled out.

I have enabled trace logs, will update when it happens next (It happened again between 1600 and now, but trace logs were not yet on)

**Comment by Xaroth** [comment]
[sonarr.zip](https://github.com/Sonarr/Sonarr/files/4638539/sonarr.zip)

It just happened again, this time with trace logs enabled. Attached them all as a zip (9 files in total).

I cleared the trace logs every time I could visually confirm the series were still monitored properly, which is why they start at 11:26:26.

**Comment by Taloth** [comment]
> 20-5-16 12:28:45.2|Trace|Http|Req: 7612 [PUT] /api/series (from 127.0.0.1 python-requests/2.10.0)


You have an external process that's updating series and triggering season searches.

**Comment by Xaroth** [comment]
I have disabled all processes, will give it a few days to see if it still occurs.

Will re-open issue if/when this still persists.
