### ISSUE TITLE
Option to always sort releases in manual search pop-up by newest first

### ISSUE THREAD

**Issue by RedTedRedemption** [Sonarr/Sonarr#3755]
**Describe the problem**
Every time i do a manual search for an episode, Sonarr sorts releases by oldest first. I always have to change the sort order when I'm looking for a show that just aired.

**Describe any solutions you think might work**
Add an option to change default sorting of releases when searched manually, or always sort by newest first in the pop-up box.

**Comment by markus101** [comment]
> Sonarr sorts releases by oldest first.

Sonarr orders the results in the order it'd attempt to grab them  in (if they were accepted), quality being the biggest preference.

> I always have to change the sort order when I'm looking for a show that just aired.

If the episode just aired all the results should be within a that day, unless your indexer is returning results for other episodes/series in which case they should fix that.

At this time we don't have plans to change the default sort-order.
