### ISSUE TITLE
Handle anime with both english and japanese titles

### ISSUE THREAD

**Issue by TwistedFaith84** [Sonarr/Sonarr#3756]
So I just thought of this and though its not really important for TV Series its definitely important for anime; but how bout a feature where we can add like a list of download groups for when Sonar does it's searching that if said group is found it can actually download the file.

This would be more like a filter and since most groups put their group name in front of the filename it could really help with the finding and downloading. I'm sure I'm not explaining right but here's the best way I can think of explaining. Since sometimes Sonar see a file but wont download it cause it says the series doesn't exist (cause of the group name being in front of the filename) but if us users can manually add a list of groups to filter for (or something) Sonar can see if said group is listed and kinda actually see the file (by reading the filename from where the group name ends)

![Untitled](https://user-images.githubusercontent.com/11351824/82145116-2a029d80-980e-11ea-888e-9cf6ac3acec4.jpg)
for example with this if in my list of groups I had "[-KS-]" then instead of sonar saying it's an unknown series it would start reading the filename after the [-KS-] and actually see that the series for that file is actually "Welcome To Demon School Iruma-Kun" and be able to download it.

**Comment by Taloth** [comment]
It has no problem with the groupname in front. The problem with that show is that it contains both the english and the japanese title.

Workaround would be to have thexem.de add another alias. But i'll leave this github issue to see if we can do checks for concatenations like that.

**Comment by pandavova** [comment]
I switched to "phantom-develop" (Sonarr Ver. 2.0.0.5344 phantom-develop), but I still have this issue.

"Monster Girl Doctor" is the English Name of the Series and "Monster Musume no Oisha-san" is a valid alias, as seen here: http://thexem.de/xem/show/4938

> DownloadDecisionMaker|Processing release '[ok] Monster Musume no Oisha-san (Monster Girl Doctor) - 01 [Multi-Subs] [1080p].mkv' from 'nyaa.si'
> Parser|Parsing string '[ok] Monster Musume no Oisha-san (Monster Girl Doctor) - 01 [Multi-Subs] [1080p].mkv'
> Parser|Episode Parsed. Monster Musume no Oisha-san (Monster Girl Doctor) - 001 
> Parser|Language parsed: English
> QualityParser|Trying to parse quality for [ok] Monster Musume no Oisha-san (Monster Girl Doctor) - 01 [Multi-Subs] [1080p].mkv
> Parser|Quality parsed: HDTV-1080p v1
> Parser|Release Group parsed: ok
> ParsingService|No matching series Monster Musume no Oisha-san (Monster Girl Doctor)
> DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
