### ISSUE TITLE
Title slug 'the-yard' is in use by series 'The Yard'

### ISSUE THREAD

**Issue by hongkongkiwi** [Sonarr/Sonarr#3757]
I'm trying to add a series called "The Yard (2011)". Unfortunately it's conflicting with a more recent series called "The Yard (2018)" produced by netflix.

I've manually renamed the folder of the 2018 version to append year, but when I try to add the 2011 version it still conflicts with the slug with this message: Title slug 'the-yard' is in use by series 'The Yard'

How can I fix this? It won't let me add the 2011 series.

**Comment by Taloth** [comment]
Get thetvdb to fix the show title. They don't allow duplicate titles and it should get a year appended to it. (There are 3 'The Yard' shows, 2011, 2016, and 2018)

**Comment by hongkongkiwi** [comment]
After updating in TVDB, how can I get Sonarr to register the new title when I search? It still shows up as the old title.

I guess I need to clear the search cache somehow? 

I've just edited both titles in TVDB now (thanks for the tip).

**Comment by Taloth** [comment]
They're not supposed to be both edited. The original 2011 show gets 'The Yard' title. (please check tvdb rules for guidance)

It takes time for tvdb updates to filter through all the caches. hours potentially.

**Comment by hongkongkiwi** [comment]
Got it, I've updated.

Here's another tricky one. War and Peace (tvdb: 89381) and War & Peace (tvdb: 72128).

In this case, the titles are different, but Sonarr treats "&" character as "and" (or is this TVDB?) and so they end up being the same slugs.
