### ISSUE TITLE
Show current version on updates tab

### ISSUE THREAD

**Issue by principis** [Sonarr/Sonarr#3759]
**Describe the problem**
When I look at the updates tab, sometimes it would be useful to immediately see which version I'm currently running, to know how far ahead the branch is.

**Describe any solutions you think might work**
The version number could, for example, be displayed in the top right corner after the loading icon disappears.

**Additional context**
I'm currently running v3.0.3.822

**Comment by Taloth** [comment]
The problem is actually in services which hides all but the last 'maintenance' update even if it's the one the user has right now.

Throwing in the version there isn't a bad idea either, but not the entire solution.

Bonus points for updating sonarr to show a digest of all intermediate versions, rather than only the last one. That actually requires storing the changelog at the time the update is initiated.

**Comment by principis** [comment]
I didn't know that, thank you.

Could you elaborate what you mean with the digest? Currently there are only 5 versions shown (I'm not sure where the source code for the services api is), with their change log. 
Do you mean showing all versions which were installed?

**Comment by Taloth** [comment]
Once an update is installed, you get a popup with the 'changes'. that popup only contains the changes of the last release, rather than the changes between the previous installed version and the new one.

So yes, showing all versions which were installed.

**Comment by principis** [comment]
Ah yes, I forgot. I mostly skip it (by refreshing the tab) because the restarting message leaves too soon, so it seems that the update is done.
I'll look into it.

**Comment by Taloth** [comment]
I posted the details mostly for myself, coz services is closed source. That only leaves the popup as possible change on Sonarr's end.

**Comment by Taloth** [comment]
![image](https://user-images.githubusercontent.com/6383890/84056686-db809300-a9b6-11ea-9c3a-84bc205b83a7.png)
