### ISSUE TITLE
Show the rejection reason in 'Manual Import' without having to mouse over the exclamation mark

### ISSUE THREAD

**Issue by Makeshift** [Sonarr/Sonarr#3761]
**Describe the problem**
Every week or so I do a "manual import" on my Sonarr downloads directory to manually fix some of the releases that were rejected for whatever reason.

Usually, there's anywhere from 50-500 releases in there that might need manual attention. Having to individually mouse over each exclamation mark to see the reason for rejection, then move the mouse over to the left-hand side to tick or untick the release feels like an unnecessary step, and quickly adds up how long it takes to perform a manual import.

**Describe any solutions you think might work**
I would like to be able to see the rejection reasons in the table without having to mouse over the exclamation mark. I attempted to write a bit of JS to do this but I'm not incredibly familiar with the framework the UI uses so I had some trouble extracting the reason list.

It would also be nice to be able to "group" releases by rejection reason.

Additionally, it would be nice to be able to mark unneeded releases for deletion, but this is more of a stretch and is likely worthy of its own issue.

Finally, it would be really nice to disable the closing of the modal window if you accidentally click outside of it. It takes like 20 minutes to load a manual import, and sometimes longer than that to manually tick each of the ones you care about, so it's extremely annoying if you accidentally click outside the window and it closes.

**Additional context**
I wrote a couple bits of JS to assist with imports that I use. I'm unsure if these would be useful to add to Sonarr as buttons:

Unticks all releases that were rejected by Sonarr (In case Sonarr failed to import a legitimate release for whatever reason):
```javascript
document.querySelectorAll("[data-icon='exclamation-circle']").forEach(a => {
    let tick = a.parentElement.parentElement.parentElement.querySelector("input");
    tick.checked ? tick.click() : ""; 
})
```

Copies into the clipboard a list of all paths of unticked releases for pasting into the shell for deletion:
```javascript
copyText = "";
document.querySelectorAll(".Table\\/table\\/2C3O8")[0].querySelectorAll("input[type=checkbox]:not(:checked)").forEach(a => {
    copyText += ` "${a.parentElement.parentElement.parentElement.parentElement.children[1].innerText}"`
})
  var el = document.createElement('textarea');
  el.value = copyText;
  document.body.appendChild(el);
  el.select();
  document.execCommand('copy');
  document.body.removeChild(el);
```

**Comment by markus101** [comment]
We have no plans to list all the rejection reasons outside of the tooltip.

> It would also be nice to be able to "group" releases by rejection reason.

No plans for grouping, but filtering is covered by: https://github.com/Sonarr/Sonarr/issues/1142

> Finally, it would be really nice to disable the closing of the modal window if you accidentally click outside of it

This is something we could do.

> It takes like 20 minutes to load a manual import,

Sounds like you're loading a directory of tons of things you've already processed, ideally that'd be avoided.

**Comment by Makeshift** [comment]
> We have no plans to list all the rejection reasons outside of the tooltip.

That's a shame, I feel like it wouldn't take up much space but would make reaching decisions about manual importing much more of a "at-a-glance" job rather than having to throw my mouse around the screen (which is what prompted the "disable closing of the modal window" suggestion).

Do you happen to know where that tooltip information is retrieved from when hovered over? I can simply create a script to display it as per my needs if I know where the information can be found. I can see that it pops up in a Popover class div, but I'm unsure where it gets that data from, as it doesn't seem to be a hidden div or anything.

> Sounds like you're loading a directory of tons of things you've already processed, ideally that'd be avoided.

I'm loading a directory of things that Sonarr has failed to process. I have a fairly large collection, a percentage of which comes with various issues such as bad naming or Sonarr fails to detect whether something is a sample or not.

**Comment by markus101** [comment]
> Do you happen to know where that tooltip information is retrieved from when hovered over?

It's only rendered on mouseover, there isn't a hidden div.

**Comment by Taloth** [comment]
Wouldn't those downloads show up in Activity->Queue?

**Comment by Makeshift** [comment]
I'm a firm believer in of having as much information readily available at a glance as possible to assist in making decisions quickly, but I understand I'm definitely in the minority with that mindset, especially when it comes to UX design.

With that in mind, I made a horrendous frontend hack. It hooks into the xmlhttprequest that Sonarr does to get the manual import results, since I couldn't find where that information was stored after the request takes place.

This is good enough for my needs, so if you don't think the community as a whole would value the suggestions in the original post then please feel free to close the issue.

```javascript
(() => {
    let origOpen = XMLHttpRequest.prototype.open;
    XMLHttpRequest.prototype.open = () => {
        this.addEventListener('load', () => {
            if (this.responseURL.includes("/api/v3/manualimport") && this.response) {
                let results = JSON.parse(this.response);
                setTimeout(() => {
                    document.querySelectorAll("[data-icon='exclamation-circle']").forEach((a, i) => {
                        if (i === 0) return;
                        let rejections = results.filter(b => b.relativePath === a.parentElement.parentElement.parentElement.children[1].innerText)[0].rejections;
                        if (rejections) {
                            let html = "<ul><li>"
                            html += rejections.map(a => a.reason).join("</li><li>")
                            a.parentElement.innerHTML = html + "</li></ul>"
                        }
                    })
                }, 500)
            }
        });
        origOpen.apply(this, arguments);
    };
})();
```

**Comment by Taloth** [comment]
> This is good enough for my needs

The issue here is that you shouldn't have to go to Manual Import at all to clean stuff up. Which is why I asked about Activity->Queue.
The suggestion you made is an consequence of a particular workflow.
If the failing imports don't show up in Activity->Queue, then the question is why they're not.
If the failing imports show up there, then the question is why so many imports fail. For which reason; and if something can be adjusted to avoid the scenario from happening in the first place.
There are legitimate reasons why imports fail and cannot be remedied easily, but that should not occur often.

**Comment by psylenced** [comment]
Another option is a different icon per rejection type . And I agree with the original poster.

If you have 15-20 failures in there you literally have to mouse over 20 icons which is not a good user process. On top of that you have to keep moving your mouse left side - right side to tick or untick each individual row based on what the hover is. So for 20 failures, that's 40 side to side movements.

![image](https://user-images.githubusercontent.com/1967906/82318754-b92cd280-9a13-11ea-808a-a595471d829c.png)

This isn't a screen you use often - only if something goes wrong. So I see no reason why it should be completely "clean" with just icons.

Even if the full text isn't there - simple labels: _"Sample", "Size", "Not Upgrade", "Unknown"_ with a hover being the full rejection reason. This also allows sorting.

It's not as if the modal is taking up most of the screen - it's not starving for space.

**Comment by Makeshift** [comment]
> Wouldn't those downloads show up in Activity->Queue?

I just wanted to revisit this question - No, it seems not. My settings -> Download clients is set to remove after completed/failed download, so activity -> queue contains only currently downloading items.
![image](https://user-images.githubusercontent.com/345013/83237848-7397a480-a18d-11ea-814f-7f90fc4a7abe.png)

(Compared to the manual import of the download directory, where there are **575** rows)

![image](https://user-images.githubusercontent.com/345013/83238788-da698d80-a18e-11ea-9202-8e403a7a3e2e.png)


Is activity -> queue intended to be the place to manage failed/badly matched/whatever downloads? If so, does that require specific settings? I've always used manual import for that job. There seems to be a pretty significant disconnect somewhere between the nzb that is chosen for download and the files that are then downloaded.

**Comment by psylenced** [comment]
@markus101 I think you closed the wrong issue against that PR. Commit fd608fd seems to have nothing to do with this issue?

**Comment by Makeshift** [comment]
> @markus101 I think you closed the wrong issue against that PR. Commit [fd608fd](https://github.com/Sonarr/Sonarr/commit/fd608fd4113bd1d6fde42bca4d9879f826a8c6a9) seems to have nothing to do with this issue?

It references the issue by applying one of the fixes I suggested, but isn't really related to the original issue. However, from what Taloth is saying it seems that my issue is a process one caused by something else, so it's probably out of scope anyway.
