### ISSUE TITLE
Epic Fail with migrated installation

### ISSUE THREAD

**Issue by scottharman** [Sonarr/Sonarr#3762]
**Describe the bug**
Installation has halted at the point of trying to remove the existing Sonarr V2 service (which was stopped)
However that appears to be a red herring based on the logfile attached
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/4649333/sonarr.txt)

**System Information**

 - Sonarr Version: 3.0.3.824
 - Operating System: Windows 10

**Comment by scottharman** [comment]
Unable to halt the installation, nor able to close the installer window

**Comment by markus101** [comment]
Setup logging is enabled, so there should be a log file for the setup in your TEMP folder (`%TEMP%`), not sure if that logs the output of the process removing the service, but it'd be helpful to have that.

**Comment by scottharman** [comment]
Hey @markus101 Installer log is now attached

[Setup Log 2020-05-19 #001.txt](https://github.com/Sonarr/Sonarr/files/4655061/Setup.Log.2020-05-19.001.txt)

I managed a manual migration (which appeared successful) but the database was empty - no user accounts, downloaders or shows.

It could be something funky in my installation, as it's been running for at least a couple of years on Sonarr v2, and was using a startup shortcut due to issues with the service being able to access files on network drives when running as a service.
Cheeers
