### ISSUE TITLE
Sonarr sends A LOT of HTTP requests to, I assume, check if a download is done, even if it has been done for days

### ISSUE THREAD

**Issue by mortenmoulder** [Sonarr/Sonarr#3763]
**Describe the bug**
I run AdGuard as a self hosted DNS, so I can monitor my devices and see which sends the most requests. Sonarr does about 8% of my ~270.000 DNS requests so far. That's a lot.

**System Information**
 - Sonarr Version: 2.0.0.5344
 - Operating System: Docker on a Debian machine

**Additional context**
I am currently monitoring 3 TV shows and only about ~30 episodes total. Most of the requests are sent to SABnzb to `mode=queue` and `mode=history`. About 2 requests per minute, it looks like.

This seems like a bug. Why would Sonarr ask my client for history, when all are marked as "on disk"/downloaded? I'm not concerned about the amount of requests, but it just seems a bit weird.

**Comment by Taloth** [comment]
It's possible to add downloads to sab directly and sonarr would pick them up. That's one of the main reasons why it's continuously monitoring sab.

**Comment by mortenmoulder** [comment]
@Taloth Manually? I'm not interested in doing anything manual. That's why I am using Sonarr 😄

**Comment by Taloth** [comment]
Yup. Sometimes they grab releases that sonarr can't find or from indexers that don't have an api. It doesn't happen often, but if it happens it's nice that sonarr can pick them up afterwards instead of having to manual import as well.

**Comment by Taloth** [comment]
Anyway, this behavior is by design :smile:

**Comment by mortenmoulder** [comment]
@Taloth I understand that, but is there no way to disable that? I don't want to manually add files to SABnzbd for Sonarr to pick up, so it would make sense, I could disable this.. right? 😄

**Comment by Taloth** [comment]
Nope there's no mechanism to disable it. 
You did say the amount of requests weren't a concern, you just thought it might be a bug and was kind enough to report it :wink:

In theory it's possible to change the interval from 1 minute to something like 5 minutes if there aren't any active downloads, but atm it's not worth the effort.
