### ISSUE TITLE
Support using networked database

### ISSUE THREAD

**Issue by caewok** [Sonarr/Sonarr#3764]
When using Sonarr in k8s or docker swarm, database corruption is a significant issue because the typical solution for storage is to use NFS or GlusterFS or something similar to ensure the data is saved when the container is stopped and then started on a new node. Most of these solutions are incompatible with the sqlite setup currently in place for Sonarr. 

It would be great if the user could give Sonarr information on startup (maybe with environmental variables?) to use a networked database. This would make Sonarr much less dependent on the local storage device, and should alleviate database corruption issues. Related to #1669 and #1886.

**Comment by markus101** [comment]
We understand why this is wanted for some users, but it's not something we plan to support, at least in the foreseeable future.
