### ISSUE TITLE
[Request] Remove Duplicate Copies

### ISSUE THREAD

**Issue by zero77** [Sonarr/Sonarr#3767]
**Describe the problem**
Before the quality profile cut off is met there are sometimes multiple copies of the same film downloaded, that take up unnecessary disk space.

**Describe any solutions you think might work**
 Can you please add some kind of clean up that removes the duplicate copies ideally the lower resolution copies, thanks.

**Comment by markus101** [comment]
Lower quality files are removed from the series folder before importing the new file (assuming Sonarr had the file linked to the episode).

They are not removed from the queue, which is covered by: https://github.com/Sonarr/Sonarr/issues/370
