### ISSUE TITLE
cant exlude a term with spaces

### ISSUE THREAD

**Issue by Ae3NerdGod** [Sonarr/Sonarr#3769]
I Don't have hardware tat supports 10 bit videos, and I currently have no plans to upgrade. In the exclude section of Sonarr, I can exclude the term "10bit" and the term "10-bit" but some release get through because in the title its specified as "10 Bit," with a space. I'd like to set the term "10 bit" because I don't want to exclude releases with the term "10" or "bit" in them. Would it be possible to implement a comma separated system, or possibly an escape in the term that gets interpreted as space like backslash (\) or tilde (~)

PS i didnt add this to feature request because the exclude feature is already a feature, its just overlooking a use case. feel free to move

**Comment by Ae3NerdGod** [comment]
Maybe something like this? The brackets make it so the terms only get excluded if together / next to each other

![Annotation 2020-05-21 220133](https://user-images.githubusercontent.com/2036505/82623686-ba463700-9bae-11ea-91f9-502c5831a234.png)

**Comment by markus101** [comment]
Probably best to use reflex, `/10[ .-]?bit/` you should be able to paste it in and in v3 type directly.

**Comment by Ae3NerdGod** [comment]
@markus101 Ive upgraded to v3, now the "Restrictions" section is completely gone from indexers... was the setting moved in v3?

**Comment by Taloth** [comment]
Profiles->Release Profiles
