### ISSUE TITLE
Support for importing of settings during initial start up (like in docker env)

### ISSUE THREAD

**Issue by ravensorb** [Sonarr/Sonarr#3772]
t would be very helpful if there was an easy way to configuration radarr during initial started -- especially when used within a containerized environment (like docker).

Maybe a preference.json or a configure.json file that allowed for settings things like

media folders
indexers
downloaders

**Comment by markus101** [comment]
You can restore a backup or use the API to configure, but no plans for a different configuration file that seeds the configuration.
