### ISSUE TITLE
kodi - episode metadata uniqueid

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#3773]
**Describe the bug**
sonarr generates kodi metadata, the field `uniqueid` tells kodi the id and where it came from. so tvdb / imdb / etc.
https://kodi.wiki/view/NFO_files/TV_shows

sonarr sets this correctly as `tvdb` (or imdb if applicable) when doing the series metadata (tvshow.nfo) but for the episode nfo it wrongly does `sonarr`.
https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs#L269

**System Information**

 - Sonarr Version: 3.0.3.832
 - Operating System: Windows 7
 - .net Framework (Windows) or mono (macOS/Linux) Version: n/a

**Comment by markus101** [comment]
It does "sonarr" because that's Sonarr's ID for the episode, it doesn't store any other unique ID.

**Comment by thezoggy** [comment]
i see, it really is sonarr's episode id (poked around sonarr db to confirm).
