### ISSUE TITLE
Show Full Queue Status Popover on Calendar/Series Details

### ISSUE THREAD

**Issue by reinisb** [Sonarr/Sonarr#3775]
**Describe the bug**
I have set up Sonarr to monitor a TV show with multiple seasons and episodes in each season. When I manually add a torrent file of a monitored episode to Transmission, then Transmission downloads the episode properly, Sonar gets the info from Transmission and sees the downloaded episode but fails to import the file (there is no hard link created in the corresponding Season folder of that TV Show and the episode is not listed as Imported in Sonarr UI). The message states `Downloaded - Unable to import: Check logs for details`. Unfortunately I do not see anything suspicious in the logs. Moreover, I checked permissions and they should be correct - both Tranmission and Sonarr are run by user `debian-transmission` belonging to a user group of the same name `debian-transmission` and also all files and folders belong to the same user and user group.

The strange thing is that I have another TV show where I don't manually add the torrent file to Transmission, but let Sonarr watch the torrent tracker for new episodes and handle everything automatically. There everything works properly - once Sonarr sees a new monitored episode in the torrent tracker, it automatically initiates the download in Transmission and once the download is complete creates a hard link in the Season folder of that TV Show as well as show the episode as properly imported in the Sonarr UI.

**Screenshots**
<img width="1212" alt="Screen Shot 2020-05-25 at 14 07 03" src="https://user-images.githubusercontent.com/6346595/82810914-464eac00-9e98-11ea-9e83-b1cc412a662c.png">
<img width="1198" alt="Screen Shot 2020-05-25 at 14 00 01" src="https://user-images.githubusercontent.com/6346595/82810933-4fd81400-9e98-11ea-9563-0558742a9414.png">

**Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/4677016/sonarr.trace.txt)
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/4677017/sonarr.debug.txt)
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/4677018/sonarr.txt)

**System Information**

 - Sonarr Version: 3.0.3.832
 - Operating System: Raspbian Buster (Linux 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux)
 - mono (macOS/Linux) Version: Mono JIT compiler version 6.8.0.105 (tarball Tue Feb  4 21:26:24 UTC 2020)

**Comment by markus101** [comment]
Please use the forums/subreddit for support.

I don't see any attempted imports in the logs for that release or any other.

What does it show in Activity: Queue for that release?
Try the following:

1. Clear the log files
1. Restart Sonarr
1. Post the logs after a few minutes

**Comment by reinisb** [comment]
Exactly, I also don't see anything about attempted imports in the logs, thus I thought it is a bug and reported here.

I tried a new TV series just now, the same issue. Logs cleared and attached.
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/4680966/sonarr.debug.txt)
[sonarr.trace.0.txt](https://github.com/Sonarr/Sonarr/files/4680968/sonarr.trace.0.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/4680969/sonarr.trace.txt)
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/4680971/sonarr.txt)


_During download_
<img width="1508" alt="Screen Shot 2020-05-26 at 11 36 42" src="https://user-images.githubusercontent.com/6346595/82880438-17dbda00-9f47-11ea-954c-3f66bc247d36.png">


_After download_
<img width="1509" alt="Screen Shot 2020-05-26 at 11 46 26" src="https://user-images.githubusercontent.com/6346595/82880463-20341500-9f47-11ea-9fd3-4c3e8b6336ed.png">

**Comment by markus101** [comment]
What do you see in Activity: Queue? (Hover over the icon on the left).

**Comment by reinisb** [comment]
<img width="1503" alt="Screen Shot 2020-05-26 at 18 35 44" src="https://user-images.githubusercontent.com/6346595/82920280-c56adf80-9f7f-11ea-8688-8116b16ab2e6.png">

**Comment by markus101** [comment]
There's the answer then, if you're not using a category with transmission (which is just a subfolder in the download directory), you should, then anything you grab manually should be in that folder.

From our end we can improve the message shown in the episode list to show the reason it was rejected, instead of the wild goose chase in the logs.

**Comment by reinisb** [comment]
Oh, I would have never guessed that. Can you please elaborate on why such a requirement exists? I mean the when I leave the complete process to Sonarr to automat then it works great without any category withing transmission. I wonder why it is different when I add the torrent file to Transmission manually.

<img width="1069" alt="Screen Shot 2020-05-26 at 19 16 31" src="https://user-images.githubusercontent.com/6346595/82925414-5a70d700-9f86-11ea-81e8-d6f4e16f7866.png">

**Comment by markus101** [comment]
You're instructing Sonarr to process it that way, instead of leaving it to try and process everything, that way something it manages to parse that it shouldn't process. That's the requirement, if you want Sonarr to process it, use a category (you should regardless to avoid Sonarr having to process everything added to the client).

**Comment by reinisb** [comment]
I'm really struggling to follow, but I'm trying. I think that the confusion comes from the fact that I had absolutely no knowledge about the concept of `category`. I have been using a basic indexer without any search functionality and thus have not specified any category value in my download client settings (I still have no clue what it is for). I think that it would make sense to either rename this field or explain what it is for and provide an example of a category name.

<img width="1666" alt="Screen Shot 2020-05-26 at 22 21 44" src="https://user-images.githubusercontent.com/6346595/82941886-cdd31280-9f9f-11ea-9f19-db9ee69ec4cc.png">

**Comment by reinisb** [comment]
I can confirm that the following worked:
1. In Sonarr - Download Clients - Edit Download client - add any title to the Category field.
2. Create a folder with the same title in the download folder of your download client.
3. Manually initiate a release download at the download client and make sure it downloads to the newly created folder.
4. That's it - Sonarr will not pick up the manually initiated download and properly import it in the library (in my case create a hard link to the downloaded file in the dedicated TV Show/Season folder).

@markus101 - thanks for your help and I hope that my case could foster improving the error message as well as providing more context about what a category is and how it works.
