### ISSUE TITLE
Unable to parse file on import abc.xyz.mkv

### ISSUE THREAD

**Issue by cphmichael** [Sonarr/Sonarr#3776]
Sonarr version: 3.0.3.830
SABnzbd: 2.3.9
UnRAID: 6.8.3

I don’t know if this is a Sonarr or SABnzbd problem, but sometimes I get this error:

DownloadedEpisodesImportService:
Unable to parse file on import: [/downloads/completed/Series/Billions.S05E04.2160p.WEB.h265-NiXON-xpost/abc.xyz.mkv

After Sonarr has finished processing the series, there is a folder left in the ‘completed’ with a file abc.xyz.mkv

**Comment by markus101** [comment]
Please use the forums for support. We’ll need to see debug logs of the issue.
