### ISSUE TITLE
Remove specific chracters

### ISSUE THREAD

**Issue by mikeywaldron** [Sonarr/Sonarr#3778]
In sonarr its not possible to {Exclude . , ! "} 
The option states it removed special characters but it does not remove full stops and exclamation marks, is it possible these could perhaps change to the URL-Encoded versions, Or be able to specify characters you dont want. 
to maximize compatibility

**Comment by markus101** [comment]
None of those are illegal in paths, it's expected those remain.

Next time please use the appropriate template.
