### ISSUE TITLE
{MediaInfo VideoDynamicRange} not in {MediaInfo Full}

### ISSUE THREAD

**Issue by twdkeule** [Sonarr/Sonarr#3779]
**Describe the bug**
When configuring an episode format with {MediaInfo Full}, the final filenames do not contain the VideoDynamicRange configuration (eg "HDR"). The problem is not the recognition of HDR, when {MediaInfo VideoDynamicRange} is added, "HDR" is in the filenames.

**System Information**
 - Sonarr Version: 3.0.3.833
 - Operating System: Ubuntu 19.10
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono JIT compiler version 6.8.0.105 (tarball Tue Feb  4 21:20:20 UTC 2020)

**Additional context**
With only {MediaInfo Full}:
```
{Series Title} - S{season:00}E{episode:00} - {Episode Title} - {Quality_Full} {MediaInfo_Full:EN+NL}
Season 2/Sex Education - S02E08 - Episode 8 - WEBDL-1080p h265_EAC3_[EN+NL].mkv
```
With {MediaInfo Full} and{MediaInfo VideoDynamicRange}:
```
{Series Title} - S{season:00}E{episode:00} - {Episode Title} - {Quality_Full} {MediaInfo_Full:EN+NL} __ {MediaInfo VideoDynamicRange}
Season 2/Sex Education - S02E08 - Episode 8 - WEBDL-1080p h265_EAC3_[EN+NL] _ HDR.mkv
```

**Comment by Taloth** [comment]
That's intentional, Simple only contains the Codecs, Full only contains Codec & languages, not other MediaInfo details such as audio channels, hdr.
You'll simply have to compose those yourself.

**Comment by twdkeule** [comment]
No problem. I couldn't find a definition for Full so I assumed it contained all the other MediaInfo tokens.
