### ISSUE TITLE
Added a tag or title to drive locations

### ISSUE THREAD

**Issue by tellice** [Sonarr/Sonarr#3781]
**Describe the problem**
I have tv programs sorted on several drives, in alphabetical order, ie Drive 1: A to C, drive 2 D to G etc. Would it be possible to add a tag or title or description so when i add a series and the shown path is not the location but a this tag

**Describe any solutions you think might work**
A clear and concise description of any solutions or features you've considered.

**Additional context**

**Comment by markus101** [comment]
We don't have plans for such a feature at this time.

Drive pooling may be a better solution to deal with this so you don't need to select a specific root folder.
