### ISSUE TITLE
Remove Specified Characters 

### ISSUE THREAD

**Issue by mikeywaldron** [Sonarr/Sonarr#3782]
**Describe the problem**
Ive noticed some programs does not allow . in file names as it only looks for a .mkv .avi etc... 

**Describe any solutions you think might work**
be able to rename or remove . unless its to a file extension, ive noticed it on ubuntu similar to not allowing spaces without being escaped ",
this is now starting to cause a issue as media wont manually upload due to the . in file names e.g 
Marvel.Agents.Of.S.H.I.E.L.D causes a big problem, 
it would be idea if we could remove these or not allow them in file names

**Comment by markus101** [comment]
Same as yesterday, we have no plans to choose which characters are removed/replaced.

> Ive noticed some programs does not allow . in file names as it only looks for a .mkv .avi etc...

This is a bug they should fix, periods are valid characters in file names.
