### ISSUE TITLE
[BUG] Renaming sets the language to "Unknown" when it was previous known.

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [Sonarr/Sonarr#3783]
**Describe the bug**
Renaming sets the language to "Unknown" when it was previous known.

I did a mass rename of all my shows a while back, every single episode language was set to unknown.

**Screenshots**
https://i.imgur.com/kht52tq.png

**System Information**

 - Sonarr Version: 3.0.3.833
 - Operating System: Linux
 - Mono (Linux) Version: 5.20.1.19

**Additional context**
Any way to set the language back to what it was before the rename, so It won't keep downloading a new version?

**Comment by markus101** [comment]
That's just the history event not storing the language (will fix). You can "manage" the episodes and set the language (and quality).

Preferred words is the likely cause of the re-grabs, but you'd need to look at debug/trace logs to confirm.
