### ISSUE TITLE
Episodes constantly being duplicated in the deleted folder

### ISSUE THREAD

**Issue by GooseG17** [Sonarr/Sonarr#3784]
**Describe the bug**
A single season of a show is being constantly copied to the assigned deleted folder, creating hundreds of duplicate files until running out of disk space. The UI shows the episodes in the season being removed and re-added one-by-one in a loop. Manually removing the episode files from the import location, restarting Sonarr and manually moving the files back to their folder stopped the loop.

**Logs**
https://www.dropbox.com/s/0tsya8igk7budu6/logs.zip?dl=0

**System Information**
 - Sonarr Version: 3.0.3.833
 - Operating System: Windows 10 LTS 2019
 - .net Framework (Windows) or mono (macOS/Linux) Version: .NET 4.5

**Comment by markus101** [comment]
Which file(s) so I can search the logs?

**Comment by GooseG17** [comment]
All episodes in One-Punch Man Season 1.

**Comment by markus101** [comment]
It's unclear why it keeps trying to import that release even though all the episodes for season 1 have been imported. I've added some more logging which will be available in `3.0.3.835` (and later). Please update when it's available and upload the relevant trace and debug logs (debug logs will help narrow down the time range without digging through all the trace events).

**Comment by markus101** [comment]
Closing until we have more info.
