### ISSUE TITLE
Calendar API

### ISSUE THREAD

**Issue by iLewisssHD** [Sonarr/Sonarr#3786]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

## Bug Report

When the Calendar is opened via the API it just displays "[ ]" and no other data.
The API works fine with /system/status and other things.

### System Information/Logs

**Sonarr Version: 3.0.3.834**

**Operating System: Ubuntu 18.04**

**.net Framework (Windows) or mono (macOS/Linux) Version: Mono 6.8.0.123**

**Link to Log Files (debug or trace): https://we.tl/t-TTlckGKz2n**

**Browser (for UI bugs):**

**Comment by markus101** [comment]
That’s not a bug that just means there is nothing monitored for that range. If no range is provided it uses today as the start and 2 days from now as the end.

**Comment by iLewisssHD** [comment]
Well then it definitely doesn't work as I have things in the calendar 2 days from now. Also the specifying a date range as per below turns the same result.
https://sonarr.example.com/api/calendar?apikey=xxxxxxxxxxxxx&start+2020-05-26&end=2020-05-27

**Comment by markus101** [comment]
I assume since you deleted your reply it's because you figured out the request was wrong? `start+` instead of `start=`
