### ISSUE TITLE
No longer able to connect to nzbfinder using sonarr 3

### ISSUE THREAD

**Issue by miracle152005** [Sonarr/Sonarr#3787]
**Describe the bug**
A certificate verification failed error now happens if I am trying to connect to nzbfinder.
This does not happen if I use the same api call in firefox orI use the indexer in radarr.
I think it worked ok, before applying the latest sonarr updates yesterday evening.

Could you please take a look.
Thanks.
Best regards miracle152005

**Logs**
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/4705714/sonarr.txt)

**System Information**

 - Sonarr Version: 3.0.3.834
 - Operating System: ubuntu 18.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono JIT compiler version 6.8.0.123

**Comment by markus101** [comment]
Please use the forums for support.

> X509CertificateValidationService|Certificate validation for https://nzbfinder.ws/api?t=tvsearch&cat=5010,5030,5040,5045,5080,5090,5070&extended=1&apikey=(removed)&offset=0&limit=100 failed. RemoteCertificateChainErrors

It looks like their cert is invalid according to mono, you may need to update certs: https://www.mono-project.com/docs/faq/security/

**Comment by Taloth** [comment]
nzbgeek had an expired certificate in the chain, maybe nzbfinder too?

**Comment by miracle152005** [comment]
It seems to be the case that mono analyses an old certificate chain.
If mono communicates with the website it uses this intermediate certificate:
https://support.comodo.com/index.php?/Knowledgebase/Article/View/966/108/intermediate-1-sha-2-comodo-rsa-certification-authority

instead of this one
https://support.comodo.com/index.php?/Knowledgebase/Article/View/970/108/intermediate-2-sha-2-comodo-rsa-domain-validation-secure-server-ca

The second is used by chromium, openssl, firefox.
