### ISSUE TITLE
qBitTorrent seeding time is treated as the same setting as share ratio limit

### ISSUE THREAD

**Issue by Jadiction** [Sonarr/Sonarr#3788]
**Describe the bug**
Sonarr checks if a torrent is removed from qBitTorrent after download to prevent conflicts with their completion handling, in this check, it seems to detect the "seeding time after x minutes" as such as well. I'd like to have Sonarr copy over the files from the downloads folder -> destination folder and qBitTorrent can seed xx minutes and delete itself later on.

**Screenshots**
qBitTorrent setting:
![image](https://user-images.githubusercontent.com/8557785/83351749-49b8bc00-a30c-11ea-8a4a-33297841d8c9.png)
The files will not be deleted after the download is complete, so no conflicts should arise; currently Sonarr fails to connect to qBitTorrent:
![image](https://user-images.githubusercontent.com/8557785/83351771-78cf2d80-a30c-11ea-91a7-bc7ca25124b0.png)

**Logs**
Invalid request Validation failed: 
 -- qBittorrent is configured to remove torrents when they reach their Share Ratio Limit

**System Information**

 - Sonarr Version: Sonarr Ver. 2.0.0.5344
 - Operating System: Unraid (Linux)

**UI Bugs:**
 - OS: Windows 
 - Browser: Chrome
 - Version: 83

**Comment by Taloth** [comment]
Set it to Pause instead, sonarr will remove it once the seeding criteria have been met. Assuming Settings->Download Clients->Completed Download Handling->Remove is enabled as well.

**Comment by Jadiction** [comment]
Ah, I figured the remove option for the completed download handle would instantly remove upon transferring/copying the file(s) over.

**Comment by Taloth** [comment]
It'll wait for seeding to finish, or forever if no criteria is specified in the download client.

**Comment by Jadiction** [comment]
I'm 2 days new into Sonarr, so my apologies. Thanks for the information!
