### ISSUE TITLE
Import failed, path does not exist or is not accessible by Sonarr

### ISSUE THREAD

**Issue by Reemster** [Sonarr/Sonarr#3790]
**Describe the bug**
After updating Sonarr from v.2 to 3.0.3.834, Sonarr don't import any more after downloading

Error : **Import failed, path does not exist or is not accessible by Sonarr: C:\Users\etc.... Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder**

**Additional context**
Before Sonarr v2.0 i never has this problem.. The path is accessible (i checked) so no idea why Sonarr give this error or how to resolve this.

**Comment by markus101** [comment]
Please use the forums for support. If you're running Sonarr as a service either change the user, don't run it as a service or don't store downloads in the user folder.
