### ISSUE TITLE
Does not search for Anime shows (no trace log entries)

### ISSUE THREAD

**Issue by Elehiggle** [Sonarr/Sonarr#3791]
**Describe the bug**
Add Konosuba to Sonarr (should happen for any Anime): https://thetvdb.com/series/konosuba-gods-blessing-on-this-wonderful-world
Set show type to Anime.
Try to search for a season (eg. Season 1 interactive). Search will immediately show "no results", you can kinda tell it didn't even search.

**Logs**
Trace log, Sonarr does absolutely nothing.
```
20-6-1 17:56:17.4|Trace|Http|Req: 8786 [GET] /logfile/sonarr.trace.txt (from 192.168.1.30 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0)
20-6-1 17:56:17.4|Trace|Http|Res: 8786 [GET] /logfile/sonarr.trace.txt: 200.OK (0 ms)
20-6-1 17:56:19.5|Trace|Http|Req: 8787 [GET] /api/v3/release?seriesId=151&seasonNumber=1 (from 192.168.1.30 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0)
20-6-1 17:56:19.5|Trace|Http|Res: 8787 [GET] /api/v3/release?seriesId=151&seasonNumber=1: 200.OK (6 ms)
20-6-1 17:56:19.5|Debug|Api|[GET] /api/v3/release?seriesId=151&seasonNumber=1: 200.OK (6 ms)
20-6-1 17:56:20.7|Trace|Http|Req: 8788 [GET] /logfile/sonarr.trace.txt (from 192.168.1.30 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0)
20-6-1 17:56:20.7|Trace|Http|Res: 8788 [GET] /logfile/sonarr.trace.txt: 200.OK (0 ms)
```

**System Information**
Docker, Ubuntu
Version 3.0.3.834
Package Version 3.0.3.834-ls11 by linuxserver.io 
Mono Version 5.20.1.34

**Additional context**
This happens to Dragonball Super as well. I remember Sonarr's anime search working fine some months ago for this anime with Anime type.

**Comment by markus101** [comment]
Sounds like none of the episodes in that season are monitored, which for an anime season search will result in nothing being searched.

For interactive search that shouldn't be a requirement, but currently is/

**Comment by Elehiggle** [comment]
It was indeed unmonitored. But I have monitored the show + season + episodes now. Doesn't change anything. Also, when its set to Standard, it searches just fine.

**Comment by markus101** [comment]
I added the exact same series you did and searched for season 1, the same as you did, it yields results when all episodes are monitored and returns immediately when they aren't, I don't see any other issues, as long as the episode is monitored and has aired.

**Comment by Elehiggle** [comment]
Thank you for testing 👍 
Is there any other way you could explain the behavior in this video? https://streamable.com/sss3ir

**Comment by markus101** [comment]
Post updated logs.

**Comment by Elehiggle** [comment]
The logs are exactly the same (except if you want to see the logs from the working search when its set to Standard)

**Comment by Elehiggle** [comment]
Actually I found the issue. None of my indexers in Sonarr had Anime categories filled with 5070. Perhaps some logging should be added so its obvious and can be debugged.

**Comment by markus101** [comment]
This is why I wanted to see the logs, the logs tell a different story. No requests are made to any indexer in this scenario, though "enabled" indexers are searched. Additional logging is a bit tricky here, but we might be able to do something.

**Comment by Elehiggle** [comment]
Thank you :)

```
20-6-1 17:56:17.4|Trace|Http|Req: 8786 [GET] /logfile/sonarr.trace.txt (from 192.168.1.30 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0)
20-6-1 17:56:17.4|Trace|Http|Res: 8786 [GET] /logfile/sonarr.trace.txt: 200.OK (0 ms)
20-6-1 17:56:19.5|Trace|Http|Req: 8787 [GET] /api/v3/release?seriesId=151&seasonNumber=1 (from 192.168.1.30 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0)
20-6-1 17:56:19.5|Trace|Http|Res: 8787 [GET] /api/v3/release?seriesId=151&seasonNumber=1: 200.OK (6 ms)
20-6-1 17:56:19.5|Debug|Api|[GET] /api/v3/release?seriesId=151&seasonNumber=1: 200.OK (6 ms)
20-6-1 17:56:20.7|Trace|Http|Req: 8788 [GET] /logfile/sonarr.trace.txt (from 192.168.1.30 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0)
20-6-1 17:56:20.7|Trace|Http|Res: 8788 [GET] /logfile/sonarr.trace.txt: 200.OK (0 ms)
```

Those were the logs in all cases when it didn't work. Upon googling I found a few people with a similar issue, but I didn't realize Sonarr had a seperate Anime category field 👍
