### ISSUE TITLE
Error importing file after torrent downloading

### ISSUE THREAD

**Issue by tulkarxxx** [Sonarr/Sonarr#3792]
Hi,
Sometimes happens that after indexers are checked , torrent is downloaded , but when is going to be imported fails, this always happens with files  using episode numbering like "101" or "102" instead 1x01 , 1x02, etc. The problem is that is properly detected when sonarr send the torrent but not when going to be imported , so files remain there in error
**Screenshots**
![image](https://user-images.githubusercontent.com/66320480/83536696-db365280-a4f3-11ea-80cf-29904658daa6.png)

**System Information**

 - Sonarr Version: Version 3.0.3.845
 - Operating System: Linux
 - Mono Version 5.20.1.34

**Comment by markus101** [comment]
This issue is more than 101 instead of 1x01 or S01E01, it's a completely different format that breaks parsing because it doesn't follow the typical rules. It's covered by https://github.com/Sonarr/Sonarr/issues/457 already.
