### ISSUE TITLE
Anime Series folder format

### ISSUE THREAD

**Issue by 19wolf** [Sonarr/Sonarr#3795]
**Describe the problem**
There are three separate fields on the episode naming section of the settings, one for Standard, one for Anime, and one for Daily episodes.

I find myself wanting to change the Series Folder Format for Anime separately from Standard, but there does not appear to be a way to do that.

**Describe any solutions you think might work**
Add additional fields for "anime series folder format" and "daily series folder format"

**Additional context**
This could/should probably also apply to season and specials folder naming

**Comment by markus101** [comment]
> I find myself wanting to change the Series Folder Format for Anime separately from Standard, but there does not appear to be a way to do that.

To achieve what?

**Comment by 19wolf** [comment]
For use with Plex/Absolute Series Scanner - https://github.com/ZeroQI/Absolute-Series-Scanner#forcing-the-movieseries-id - Since my anime episodes are listed in absolute order without season folders, apparently I need to set the series folder format to "Series Title [tvdb3-12345]", but I don't want this for my standard shows.

**Comment by markus101** [comment]
Gotcha, this isn't something we have plans to support, but sounds like it'd fall under https://github.com/Sonarr/Sonarr/issues/926
