### ISSUE TITLE
Add filter for 'Specials'

### ISSUE THREAD

**Issue by Enteleform** [Sonarr/Sonarr#3796]
### Describe the problem
I have an `Unwatched` custom filter which is currently set to:
- `Monitored`&nbsp; `is`&nbsp; `true`
- `Episode Progress`&nbsp; `less than`&nbsp; `100`

The problem is that I've actually watched all of the `Season` episodes of many of the series that show up, but they still appear because I haven't watched all of the episodes that are in the `Specials` section.

I don't want to unmonitor those specials, because I might watch them one day, but I'd like to be able to filter them out so that I can keep track of actual unwatched non-special episodes.

### Describe any solutions you think might work
Add a filter like:
- `Episode Group`&nbsp; [`is`, `is not`]&nbsp; [`Season`, `Specials`]

&nbsp;  
`Season #` & `Specials` are the only episode groups I've come across, but if there are more & it is not possible to have hard-coded options, maybe the [`contains`, `does not contain`, `equal`, `not equal`] options that are used on `Network` could be used instead.

For example:
- `Episode Group`&nbsp; `contains`&nbsp; `Season`
- `Episode Group`&nbsp; `does not contain`&nbsp; `Specials`

**Comment by markus101** [comment]
We don’t have plans to separate specials in such a way, if they’re monitored then they count.

**Comment by Enteleform** [comment]
@markus101 

I'm confused. The data that dictates whether an episode belongs in `Specials` or `Season #` already exists. How else would they get grouped into the appropriate containers in the `Series` view?

![image](https://user-images.githubusercontent.com/10906415/83956870-4ce20980-a830-11ea-92fc-c48fdf0a8145.png)

&nbsp;
The feature request is for the existing data to be used by a new `Custom Filter` option:

![image](https://user-images.githubusercontent.com/10906415/83956785-b877a700-a82f-11ea-9da1-9841ce1f3549.png)

**Comment by markus101** [comment]
It exists when you go to the details page because Sonarr has every episode for that series. There is no such thing as "episode group".
