### ISSUE TITLE
Manual search keeps showing wrong episodes

### ISSUE THREAD

**Issue by mgrom** [Sonarr/Sonarr#3798]
**Describe the bug**
Sonarr keeps showing wrong episodes when manual search is used. It wasn't like this before.
This happens with 13 Reasons Why, Gangs of London, and others.

As shown on screenshot below I was looking for 5th episode of season 4, but almost all results were other seasons and episodes.

It like that from 2-4 weeks I think.

**Screenshots**
![image](https://user-images.githubusercontent.com/1607362/83938552-aa953800-a7d5-11ea-83fc-4fa74f4b9503.png)

**Logs**
20-6-6 08:20:06.8|Debug|EpisodeRequestedSpecification|Release rejected since the episode wasn't requested: 13 Reasons Why - S01E11 WEBDL-720p v1
20-6-6 08:20:06.8|Debug|SeriesSpecification|Checking if series matches searched series
20-6-6 08:20:06.8|Debug|SingleEpisodeSearchMatchSpecification|Season number does not match searched season number, skipping.
20-6-6 08:20:06.8|Debug|DelaySpecification|Ignoring delay for user invoked search
20-6-6 08:20:06.8|Debug|HistorySpecification|Skipping history check during search
20-6-6 08:20:06.8|Debug|MonitoredEpisodeSpecification|Skipping monitored check during search
20-6-6 08:20:06.8|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] 3.2 GB is larger than maximum allowed 2.6 GB (for 60min), [Permanent] Episode wasn't requested: 1x11, [Permanent] Wrong season
20-6-6 08:20:06.8|Debug|DownloadDecisionMaker|Processing release '13.Reasons.Why.S01E12.720p.WEBRip.X264-DEFLATE' from 'nzbplanet.net'
20-6-6 08:20:06.8|Debug|Parser|Parsing string '13.Reasons.Why.S01E12.720p.WEBRip.X264-DEFLATE'
20-6-6 08:20:06.8|Debug|Parser|Episode Parsed. 13 Reasons Why - S01E12 
20-6-6 08:20:06.8|Debug|Parser|Language parsed: English

**System Information**
 - Sonarr Version: 2.0.0.5344
 - Operating System: Raspbian
 - mono Version: 5.18.0.240

**Comment by markus101** [comment]
Sonarr just shows the results it gets back from your indexer. Unless your debug logs (a perfect example of why we ask for them) shows Sonarr searching for the wrong episode, this is an issue with your indexer.

**Comment by mgrom** [comment]
Sorry I've forgot to add log but I've just added it

**Comment by mgrom** [comment]
May I somehow force sonarr to not showing episodes with "Episode wasn't requested"

**Comment by markus101** [comment]
That's a snippet of the logs (upload the whole log somewhere and _link_ it here) and doesn't show the search request.

> May I somehow force sonarr to not showing episodes with "Episode wasn't requested"

No, not currently possible.

**Comment by mgrom** [comment]
Thanks for clarification. 

I've just checked that this is problem with indexer:

20-6-6 08:20:00.5|Debug|Newznab|Downloading Feed https://api.nzbplanet.net/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=13%20Reasons%20Why&season=4&ep=5

I've checked that this search returnes all unwanted episodes.

I'm closing this issue.
