### ISSUE TITLE
Allow indexers in manual search only

### ISSUE THREAD

**Issue by krugster** [Sonarr/Sonarr#3802]
It would be very useful to be able to configure an indexer to only be used in manual searches. I’ve configured a Jackett “all indexers” link in Sonarr but it is very slow and often returns results that I would otherwise not want (i.e. non-English) so I have it turned off for searches and RSS. However, for some hard-to-find episodes it can still be useful. Right now I am manually enabling it, performing a search and then disabling it but I can see how much easier it would be if it was simply enabled only for manual searches.

**Comment by markus101** [comment]
This is already possible in v3.

**Comment by krugster** [comment]
Awesome!  Thank you!
