### ISSUE TITLE
Episodes possibly parsed wrongly

### ISSUE THREAD

**Issue by Jadiction** [Sonarr/Sonarr#3803]
**Describe the bug**
http://g.recordit.co/AVTruJf3xA.gif
In this gif, you'll see this entire season labeled incorrectly for episode numbers. All videos that are being automatically imported are using the wrong episodes and then renaming them. 
For example, episode 1, in season 2:
**Name:**
Futurama - S02E05 - I Second That Emotion
**Source:**
/downloads/Futurama.S02E01.720p.WEB.H264-BATV[ettv]/Futurama - S02E05 - I Second That Emotion.mkv
**Imported To:**
/media/TV Series/Futurama/Season 2/Futurama - S02E01 - A Flight to Remember.mkv
_Episode 5 was imported as episode 1_

Episode 9, season 2:
**Name:**
Futurama.S02E05.720p.WEB.H264-BATV[eztv]
**Source:**
/downloads/Futurama.S02E05.720p.WEB.H264-BATV[eztv].mkv
**Imported To:**
/media/TV Series/Futurama/Season 2/Futurama - S02E09 - Why Must I Be a Crustacean in Love.mkv
_Episode 5 again, was imported as episode 9_

Episode 13, season 2:
**Name:**
Futurama.S02E09.720p.WEB.H264-BATV[eztv]
**Source:**
/downloads/Futurama.S02E09.720p.WEB.H264-BATV[eztv].mkv
**Imported To:**
/media/TV Series/Futurama/Season 2/Futurama - S02E13 - A Bicyclops Built for Two.mkv
_Episode 9 was imported as episode 13_

This was all done automatically from the Sonarr search, so I'm unsure how this happened, but perhaps I did something wrong. The whole season 2 is out of order and mislabeled and it concerns me for any other TV Series. I looked at a few episodes for a few season of this TV series and they seem fine, so not sure. I appreciate any help given.

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Linux (Unraid OS)
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono - 6.4.0

**Comment by markus101** [comment]
Not a bug, they're remapped on thexem.de, which applies unless they're already in the series folder.

http://thexem.de/xem/show/956

**Comment by Jadiction** [comment]
So it's a bug in thexem? Clearly the episodes aren't mapped correctly. It shows a few episodes from season 2 from season 1 and after that, it's all in disarray.

**Comment by Jadiction** [comment]
Hm, I see the issue. Season 1 in terms of original production order has 13 episodes (4 of the beginning of Season 2), but on Hulu and their DVDs, it has 9 episodes, thus the mapping being confused.
