### ISSUE TITLE
Designate indexers to certain download clients

### ISSUE THREAD

**Issue by jpaige5408** [Sonarr/Sonarr#3804]
**Describe the problem**
would like to be able to assign public torrent indexers to use my local download client instead of preferred seedbox download client

**Describe any solutions you think might work**
I think you could still keep the current ranking system in place for the download clients, but offer an ability to override / change from default on a per indexer basis. This way one could assign privatetracker.com to use a seedbox, while publictracker.com can be downloaded on one's local client. Thus maximizing seedbox storage and traffic.

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/1215
