### ISSUE TITLE
Ability to map private trackers to use only specific download client

### ISSUE THREAD

**Issue by samip5** [Sonarr/Sonarr#3805]
**Describe the problem**
Downloads from public trackers are going to the wrong download client, there should be a way to map indexers to specific download client, only by priority is not enough.

Private trackers most of the time require seed ratio of 1:1 per torrent, or time limit, and Sonarr will grab from public trackers as well and send them to the non-vpn'ed download client.

**Describe any solutions you think might work**
Have a clear list of your indexers which you can say which of them are private, and then have a download client setting to say it's for private ones only.

Check from Jackett API which tracker is private, and use that for the lists.

**Additional context**
N/A

**Comment by Qstick** [comment]
Dupe #1215

**Comment by samip5** [comment]
Oopsie, yup. Closing this one. Though there was none yet.
