### ISSUE TITLE
Promote Tasks

### ISSUE THREAD

**Issue by 19wolf** [Sonarr/Sonarr#3808]
**Describe the problem**
When you do anything in Sonarr, it goes into the task queue. Sometimes, multiple items end up in the queue. Example: I run a search for each season of a show that maybe has been off the air, then I want to search for an episode of a show that aired last night. Currently, I must wait for all the season searches I've queued up to finish before my single episode will be searched.

Additionally, when choosing "interactive search", it also goes to the bottom of the queue, causing the UI to 'lag' while prior tasks finish.

**Describe any solutions you think might work**
I'm hoping for the ability to 'promote' a task from the task queue, so it would be done as the next task. 

At the very least, "interactive search" tasks should be run immediately, or as close to it as possible.

**Comment by markus101** [comment]
> Additionally, when choosing "interactive search", it also goes to the bottom of the queue, causing the UI to 'lag' while prior tasks finish.

Interactive searches aren't queued at all, they happen immediately, though if indexers impose restrictions that require Sonarr to delay requests it'd take a bit longer to complete if there are other searches happening.

We don't have plans for queue management at this time, but tasks added to the queue by the user are prioritized over scheduled tasks.
