### ISSUE TITLE
Cannot add a new series neither with the name nor with its ID (tvdb: ID)

### ISSUE THREAD

**Issue by kestouf** [Sonarr/Sonarr#3809]
## Bug Report

Cannot add a new series neither with the name nor with its ID (tvdb: ID).
I don't know if it's Sonarr or TVDB that has a problem.

I am sorry if this problem has already been dealt with, but I did not find it.

Thx for your help
Best rergard
### System Information/Logs

**Sonarr Version: **
3.0.3.880

**Operating System: **
Docker on Synology

**.mono (macOS/Linux) Version:**
5.12.0.226

**Link to Log Files (debug or trace):**
https://drive.google.com/file/d/1W2F3nvVAmBRH1eTgVUoC0DHTXjATJOZ-/view?usp=sharing

**Comment by lvlie** [comment]
It's a sonarr API backend:

Message | Time
-- | --
  | HttpClient | HTTP Error - Res: [GET] http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=something: 520.520 | 13:38
  | HttpClient | HTTP Error - Res: [GET] http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=else: 520.520

**Comment by mangojuus** [comment]
Same here. "Search for 'black sails' failed. Unable to communicate with SkyHook."

**Comment by Danw33** [comment]
From u/TalothSaldono `Team Sonarr` 1 hour ago on /r/sonarr:

> skyhook down for a while, check back in 4-5 hours
Searching for new shows isn't possible atm.
In v2 you can probably add shows with tvdb:12345 since that hits the cache but that doesn't appear to work on v3.

> skyhook vm is down for some reason, gotta wait for markus to restart it.

https://www.reddit.com/r/sonarr/comments/h7iiyq/skyhook_down_for_a_while_check_back_in_45_hours/

**Comment by markus101** [comment]
Skyhook has been up for a few hours now.
