### ISSUE TITLE
Cannot open assembly 'Sonarr.exe': No such file or directory.

### ISSUE THREAD

**Issue by MemoryOverlord** [Sonarr/Sonarr#3810]
**Describe the bug**
Currently running Sonarr in Docker on Ubuntu 18 server. Rebooted machine, Sonarr wouldn't load. Rebuilt container, redeployed, container starts, but won't load.

**Log**
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0
100   169    0   169    0     0     11      0 --:--:--  0:00:15 --:--:--    33
100   169    0   169    0     0     11      0 --:--:--  0:00:15 --:--:--    42

tar: This does not look like a tar archive
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Cannot open assembly 'Sonarr.exe': No such file or directory.
Cannot open assembly 'Sonarr.exe': No such file or directory.

**Comment by markus101** [comment]
Looks like Sonarr.exe doesn't exist, also:

```
tar: This does not look like a tar archive
gzip: stdin: not in gzip format
```

Perhaps related to services not being available. If you're still having issues, open a thread on the forums for support.

**Comment by MemoryOverlord** [comment]
Thank you for your response.

It started working about an hour ago.
