### ISSUE TITLE
Health checks - Quick retest

### ISSUE THREAD

**Issue by Xalaxis** [Sonarr/Sonarr#3813]
**Describe the problem**

Quite frequently when the health checks run, a tracker is temporarily having issues with requests and is unable to respond straight away.  Alternatively, when my server is starting Sonarr will start momentarily before the download client and report a network error.  Sonarr will alert straight away (sending me a message), and wait six hours to clear the fault condition itself.  When I get the alert, usually I just manually re-run health checks and all the alerts are cleared.

**Describe any solutions you think might work**
When a health check is failed, a timer should be started for a configurable length of time (for example, five minutes).  By default, a notification should not yet be raised at this stage, however the service could still be marked as failed.  After this "quick retest" period has expired, the health tests should be re-run.  Any service which is still failed should at this point raise a notification.

**Benefit**

- Reduced notifications for services which are either briefly unavailable or still booting.
- Faster re-detection of services means that they can be used sooner than waiting for the six hour retest, which could avoid using undesired secondary sources.

**Comment by markus101** [comment]
> Reduced notifications for services which are either briefly unavailable or still booting.

Health checks don't run until ~10 minutes after start-up, if things are still booting at that time then Sonarr should be dependent on them another way.

> Faster re-detection of services means that they can be used sooner than waiting for the six hour retest, which could avoid using undesired secondary sources.

The overall health checks run every 6 hours, but indexers are disabled for increasing amounts of time, starting at 5 minutes and going up to 24 hours if they continue to fail. Download clients follow a similar pattern, but are also retried when a download needs to be sent to them (best effort delivery).

Sonarr's notifications go out immediately when the health check fails, at this time we don't have plans to change that behaviour.

**Comment by Xalaxis** [comment]
> Health checks don't run until ~10 minutes after start-up, if things are still booting at that time then Sonarr should be dependent on them another way.

I'm definitely seeing health check warnings go out immediately after service start.  I'll see if I can find some logs of this.

**Comment by Qstick** [comment]
Yea I’m pretty sure health checks run instantly on application startup event.. the thingiprovider status logic is what has a 15min grace period after startup (thus those checks may be prolonged already)
