### ISSUE TITLE
Enable authentication by default

### ISSUE THREAD

**Issue by Le-onardo** [Sonarr/Sonarr#3815]
As we all know Sonarr/Radarr/Lidarr don't impose any sort of authentication at the first start of the application. The result of this fact is that many people who are not able or who do not care enough to secure their systems and have exposed ports to their Sonarr/Radarr/Lidarr instance just leave the door open for anyone who is able to scan through bunch of ports, or just use a crawler to get full access to the instance.

- "Wizard"ish interface at the first start (where there might be more options) 
or
- It should not be too complicated to impose a standard username and password for the first start, that requires changing after the first login
or even
- Message under system -> status -> health to indicate that the instance doesn't have any authentication whatsoever

**Comment by Thirrian** [comment]
What about people running their sonarr instance and whatnot behind a reverse proxy which handles authentication? I don't have authentication in sonarr for that reason and wouldn't want it to be mandatory or have a health warning nag me about it...

**Comment by Le-onardo** [comment]
You are right. In this use case it should be also be possible to have an option to enable "self provided authentication" (e.g. basic auth behind a reverse proxy) which in turn disables such a health message. What I am trying to really get at is forcing each and everyone to have some kind of authentication from the start, as most people don't bother to change many of the default settings, it wouldn't make any sense to bury it somewhere (as it is right now)

**Comment by Xalaxis** [comment]
As most people in the world are running behind NAT, I would say manually port forwarding a service is consenting to the risks of exposing that service to the internet.  That being said, I've seen way too many unsecured instances, as you say.  I would suggest some kind of warning system which can be permanently dismissed as a compromise.

**Comment by markus101** [comment]
This is covered by https://github.com/Sonarr/Sonarr/issues/564
