### ISSUE TITLE
Manual import not working

### ISSUE THREAD

**Issue by dbond007** [Sonarr/Sonarr#3816]
**Describe the bug**
If you have items to be imported from the queue that have not been recognised. Going into queue (after ensuring that show unrecognised episodes is turned on), selecting the episode manual import icon then ticking the epsiode, select the show, it will then auto pick the season and episode number.
But after picking the show name a new blank, selectable, line will show in the list of episodes to be added.
After the show and season and episode number are correct, selecting import will take you back to the queue. The episode in the queue that you picked will not have been set to the show or season or episode that you selected.

EDIT: Might be that its just not showing that its now been added correctly, all the episodes are still unrecognised in the queue, but 1 that I set has just been imported.

**Screenshots**
After selecting the series, the second selection box appears, and the episode and season number appear.
![Screenshot from 2020-06-14 22-40-11-crop](https://user-images.githubusercontent.com/4145098/84603748-0ffdbe80-ae91-11ea-80d9-15a500439c69.png)

After selecting import, the episode and season do not appear

![Screenshot from 2020-06-14 22-43-47-crop](https://user-images.githubusercontent.com/4145098/84603753-1a1fbd00-ae91-11ea-8bab-d6d5b3e5f1bb.png)

**System Information**

 - Sonarr Version: 3.0.3.885
 - Operating System: Ubuntu
 - .net Framework (Windows) or mono (macOS/Linux) Version: mono 6.8.0.123

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: Vivaldi
 - Version: 8.1.307.32

**Comment by markus101** [comment]
The queue doesn’t update, you’re not telling the queue what the item is, you’re just telling Sonarr to import it. That item will disappear after the file is imported unless there is an error in the logs.

So what do the requested debug/trace logs show?

**Comment by dbond007** [comment]
It imports, just that my assumption was that it would no longer report it as unknown after I have told it what it was.
If its working as intended then its ok (it is importing it turns out). Just that I couldn't see anything reporting that it was and that it had taken what I had set.

So the only bug then is the UI, an extra blank line appears after selecting the series name under the file to be imported
