### ISSUE TITLE
Release rejected for matching an alias

### ISSUE THREAD

**Issue by tehniemer** [Sonarr/Sonarr#3817]
**Describe the bug**
Releases are being rejected for matching an alias, but that alias is the correct show. See screen shot below.

**Screenshots**
![Annotation 2020-06-15 082630](https://user-images.githubusercontent.com/11021632/84662822-ee78f300-aee1-11ea-9920-3d18958e0221.png)

**Logs**
[debug.log](https://github.com/Sonarr/Sonarr/files/4780517/debug.log)

**System Information**

 - Sonarr Version:  3.0.3.885-ls25 by linuxserver.io
 - Operating System: Docker

**UI Bugs:**
 - OS: Debian Buster
 - Browser: Firefox
 - Version: 77.0.1

**Comment by markus101** [comment]
Looks like you have added: `Star Wars: Clone Wars` (72244), but that result's title is an alias for `Star Wars: The Clone Wars` (83268), which is a different series. Unless a release group managed to use a conflicting alias (which will be somewhere between hard and impossible to deal with) there is nothing we can do.

If it's a conflicting alias, then see the [FAQ](https://github.com/Sonarr/Sonarr/wiki/FAQ#why-cant-sonarr-import-episode-files-for-series-x--why-cant-sonarr-find-releases-for-series-x) for information on requesting an alias, we'll need the full release name.

**Comment by tehniemer** [comment]
Huh, the series was added through Sonarr's built in search function, and on second look there are two entries with different years. Selecting the other entry seems to have solved the issue.
