### ISSUE TITLE
Manual Import: Update Rejections after Reprocessing

### ISSUE THREAD

**Issue by gimpyestrada** [Sonarr/Sonarr#3818]
Not sure if this would be considered a bug or a feature request...

**Describe the problem**
If you use the Manual Import dialog to pull in new episodes and the scanner fails to properly identify the show you get a red exclamation mark saying "Unknown Series."  If you then correctly identify the series (or season or episode), the dialog scans the episodes in the proper context but does not update the "error" column.

**Describe any solutions you think might work**
After resolving the unidentified item (Series or Season or Episode) and the episode scan completes, update the Error column with current data.

**Comment by markus101** [comment]
This is already done in v3.

**Comment by gimpyestrada** [comment]
I'm running V3 and it is not done.  Which means it is a bug and not a feature request.

**Comment by gimpyestrada** [comment]
@markus101 either this has not been pushed into a build or it is not working.

**Comment by markus101** [comment]
Looks like we don’t return the rejections reason on the second pass.

We also don’t reprocess if the episode is selected or the language/quality is changed.

**Comment by Qstick** [comment]
Wasn't this fixed here https://github.com/Sonarr/Sonarr/commit/a6b8a34ac970dd69ba2306a4dba6c5e65fbe0542

**Comment by markus101** [comment]
Returning updated rejections has been, but it doesn’t reprocess after selecting the episodes/quality/language.

**Comment by skidaddl3** [comment]
Is this https://forums.sonarr.tv/t/not-importing-after-grabbing-from-manual-search/26251 related too?

**Comment by cocokola** [comment]
Is this https://forums.sonarr.tv/t/not-importing-after-grabbing-from-manual-search/26251 related too?
Affects the same usability, it would be helpful.

**Comment by markus101** [comment]
No, this is completely unrelated to that.
