### ISSUE TITLE
calendar - agenda view -- background?

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#3820]
**Describe the bug**
bg artifact on the calendar > agenda view

**Screenshots**
![img](http://zoggy.net/firefox_2020-06-16_18-16-12.png)

it looks like this is by design? but only agenda view:
![img2](http://zoggy.net/2020-06-16_18-18-17.png)

**System Information**

 - Sonarr Version:  3.0.3.885
 - Operating System: ubuntu 18.04

**Comment by markus101** [comment]
Yes it's by design when `Enable Color-Impaired Mode` is true, the same BG is shown for items on the calendar as well.

**Comment by thezoggy** [comment]
thanks, caught me off guard. keith turned it on as a way to make one sonarr instance stand out

**Comment by keithah** [comment]
*whistles*
