### ISSUE TITLE
Allow user to keep notes on each show

### ISSUE THREAD

**Issue by key-equivalent** [Sonarr/Sonarr#3825]
With a large amount of shows, it can be easy to lose track of information.  It would be great if we could set notes in a freeform text field on the Edit menu for a show, next to tags perhaps.  Then it would be located natively in the place where we are doing the media management and included in Sonarr backups

"Upgrading show to 265"
"TVDB listing for this show is currently up in the air <tvdb link>"
"Physical quality wanted, season 3 pending"

**Comment by markus101** [comment]
Please use the appropriate template when making a feature request.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this.

Template was not used.

Limited use case.... pen/paper, excel, etc. all exist.
