### ISSUE TITLE
Season number N was unexpected considering the folder name

### ISSUE THREAD

**Issue by bjeanes** [Sonarr/Sonarr#3826]
**Describe the bug**

I've been seeing the error in the issue title and in the screenshot a lot recently as I've been downloading season packs to upgrade qualities.

It appears to be recognising multi-season packs as single-season packs erroneously.

**Screenshots**
![image](https://user-images.githubusercontent.com/2560/85184177-1b5a4b00-b2d2-11ea-9fcf-777ec03869de.png)

**Logs**

The logs are very verbose and repeated so I've taken the liberty of extracting an example instead. Let me know if you'd like more logs, though:

```
20-6-20 08:37:24.3|Debug|DetectSample|Runtime is over 90 seconds
20-6-20 08:37:24.3|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Season number 3 was unexpected considering the folder name Seinfeld.S01-S09.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb
20-6-20 08:37:24.3|Debug|Parser|Parsing string 'Seinfeld.S03E11.The.Alternate.Side.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv'
20-6-20 08:37:24.3|Debug|Parser|Episode Parsed. Seinfeld - S03E11 
20-6-20 08:37:24.3|Debug|Parser|Language parsed: English
20-6-20 08:37:24.3|Debug|QualityParser|Trying to parse quality for Seinfeld.S03E11.The.Alternate.Side.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv
20-6-20 08:37:24.3|Debug|Parser|Quality parsed: WEBDL-1080p v1
20-6-20 08:37:24.3|Debug|Parser|Release Group parsed: NTb
20-6-20 08:37:24.3|Debug|VideoFileInfoReader|Getting media info from /data/Downloads/completed/tv-sonarr-imported/Seinfeld.S01-S09.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb/Seinfeld.S03.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb/Seinfeld.S03E11.The.Alternate.Side.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv
20-6-20 08:37:24.7|Debug|AggregateLanguage|Using language: English
20-6-20 08:37:24.7|Debug|AggregateQuality|Using quality: WEBDL-1080p v1
20-6-20 08:37:24.7|Debug|AbsoluteEpisodeNumberSpecification|Series type is not Anime, skipping check
20-6-20 08:37:24.7|Debug|AlreadyImportedSpecification|No download client information is available, skipping
20-6-20 08:37:24.7|Debug|EpisodeTitleSpecification|Episode title only required for bulk season releases
20-6-20 08:37:24.7|Debug|FreeSpaceSpecification|Skipping free space check when importing
20-6-20 08:37:24.7|Debug|VideoFileInfoReader|Getting media info from /data/Downloads/completed/tv-sonarr-imported/Seinfeld.S01-S09.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb/Seinfeld.S03.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb/Seinfeld.S03E11.The.Alternate.Side.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv
```

**System Information**

**Version** 3.0.3.885
**Package Version** 3.0.3.885-ls25 by linuxserver.io 
**Mono Version** 5.20.1.34 - Operating System: [e.g. Windows 10]
**Operating system** Docker (linuxserver.io) on Ubuntu

**Comment by markus101** [comment]
> It appears to be recognising multi-season packs as single-season packs erroneously.

Multi-season packs are not supported (and no plans for support at this time). You'll need to use Manual import for those multi-season releases.

**Comment by bjeanes** [comment]
Fair enough, but Sonarr _fetched_ it. If you aren't interested in handling the imports, it would be nice if you could at least prevent Sonarr from fetching them in the first place then...
