### ISSUE TITLE
covers error

### ISSUE THREAD

**Issue by MiTvSpain** [Sonarr/Sonarr#3829]
Hello, after re-installing the application in ubuntu server 18, the posters and covers of the tv-shows no longer appear to me, how can I get the data and covers to download again thanks,

![image](https://user-images.githubusercontent.com/30379060/85325933-b880d380-b4cc-11ea-9c62-9c70027fd184.png)

**Comment by markus101** [comment]
Please use the forums/subreddit for questions/support.

`Update All` will refresh all series and pull down posters/other artwork.
