### ISSUE TITLE
Sonarr doesn't make second API call to Nzbhydra2

### ISSUE THREAD

**Issue by atg22896** [Sonarr/Sonarr#3830]
**Describe the bug**
When using Nzbhydra2 as an indexer, only 1 API call is made, the one using tvdid and tvmazeid. When directly adding indexer, if that API call returns no entries, it will make another using a q="name". 

Ex: 
```
20-6-22 14:55:33.6|Trace|HttpClient|Req: [GET] http://192.168.1.5:5076/api?t=tvsearch&cat=5000,5010,5030,5040,5045&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=374515&tvmazeid=42848&season=1&ep=8

20-6-22 14:55:33.6|Trace|HttpClient|Req: [GET] https://api.drunkenslug.com/api?t=tvsearch&cat=5000,5010,5030,5040,5045&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=374515&tvmazeid=42848&season=1&ep=8

20-6-22 14:55:35.6|Trace|HttpClient|Req: [GET] https://api.drunkenslug.com/api?t=tvsearch&cat=5000,5010,5030,5040,5045&extended=1&apikey=(removed)&offset=0&limit=100&q=Love%20Life%20US&season=1&ep=8

20-6-22 14:55:35.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'

20-6-22 14:55:35.9|Trace|HttpClient|Res: [GET] https://api.drunkenslug.com/api?t=tvsearch&cat=5000,5010,5030,5040,5045&extended=1&apikey=(removed)&offset=0&limit=100&q=Love%20Life%20US&season=1&ep=8: 200.OK (336 ms)
```
This second api call is not made to Nzbhydra2. This has resulted in me getting 0 results through nzbhydra2, while getting 3 when directly added to sonarr.

Trace 1 log shows this when searching for the problem show, while trace 0 shows it only making tvdb call because it returns entries for another show.

**Logs**
[sonarr.trace.1.txt](https://github.com/Sonarr/Sonarr/files/4815206/sonarr.trace.1.txt)
[sonarr.trace.0.txt](https://github.com/Sonarr/Sonarr/files/4815207/sonarr.trace.0.txt)

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Docker - [https://hub.docker.com/r/linuxserver/sonarr/](url)
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Comment by Taloth** [comment]
Please use the forums/subreddit for questions/support.

Sonarr only falls back to querying by title if the id-based search yields no results because it means there either are no releases, or the indexer does not have the id associated.    
There's no way to affect this behavior, except making sure that your indexers map releases properly. If a release isn't associated with the right tvdbid, report it to your indexer.

**Comment by atg22896** [comment]
@Taloth So because Nzbhydra2 software was able to get 1 single release using id-based search from all of my various indexers, it didn't resort back to title? Interesting. I have 5 indexers in Nzbhydra2 and only 1 indexer found 1 release using id, while manually searching via title I find tons of releases across all of the indexers.

**Comment by Taloth** [comment]
>  have 5 indexers in Nzbhydra2 and only 1 indexer found 1 release using id

So the other 4 don't have the id associated properly, find some relevant releases and report it to them. :wink:
