### ISSUE TITLE
Rescan video file codec info after file size/last mod change

### ISSUE THREAD

**Issue by jeff47** [Sonarr/Sonarr#3831]
It appears that Sonarr v3 only rescans files for codec, language, and other info when there is a change in the **filename**. 

Many people perform a number of post-processing steps that don't always result in a filename change.  A more robust method would be to rescan mediainfo if the file size or the last mod date changes.

**Comment by markus101** [comment]
Covered by https://github.com/Sonarr/Sonarr/issues/3366
