### ISSUE TITLE
Error converting field in the DataMapper

### ISSUE THREAD

**Issue by IDerr** [Sonarr/Sonarr#3832]
Hello :)
**Describe the bug**
The DataMapper was unable to load the following field: 'Images'

**Screenshots**
[image](https://media.discordapp.net/attachments/149249814834577409/724951487448612924/unknown.png?width=1442&height=283)

**Logs**

> Marr.Data.DataMappingException: The DataMapper was unable to load the following field: 'Images' value: '0'. Error converting value 0 to type 'System.Collections.Generic.List 1[NzbDrone.Core.MediaCover.MediaCover]'. Path '', line 1, position 1. ---> Newtonsoft.Json.JsonSerializationException: Error converting value 0 to type 'System.Collections.Generic.List1[NzbDrone.Core.MediaCover.MediaCover]'. Path '', line 1, position 1. ---> System.ArgumentException: Could not cast or convert from System.Int64 to System.Collections.Generic.List1[NzbDrone.Core.MediaCover.MediaCover].  at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable (System.Object value, System.Type initialType, System.Type targetType) [0x00067] in <d47de75a7e3f422ca4ca64a654c80495>:0   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast (System.Object initialValue, System.Globalization.CultureInfo culture, System.Type targetType) [0x00036] in <d47de75a7e3f422ca4ca64a654c80495>:0   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType (Newtonsoft.Json.JsonReader reader, System.Object value, System.Globalization.CultureInfo culture, Newtonsoft.Json.Serialization.JsonContract contract, System.Type targetType) [0x00117] in <d47de75a7e3f422ca4ca64a654c80495>:0    --- End of inner exception stack trace ---  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType (Newtonsoft.Json.JsonReader reader, System.Object value, System.Globalization.CultureInfo culture, Newtonsoft.Json.Serialization.JsonContract contract, System.Type targetType) [0x00149] in <d47de75a7e3f422ca4ca64a654c80495>:0   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0009b] in <d47de75a7e3f422ca4ca64a654c80495>:0   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <d47de75a7e3f422ca4ca64a654c80495>:0   at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00054] in <d47de75a7e3f422ca4ca64a654c80495>:0   at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <d47de75a7e3f422ca4ca64a654c80495>:0   at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <d47de75a7e3f422ca4ca64a654c80495>:0   at NzbDrone.Core.Datastore.Converters.EmbeddedDocumentConverter.FromDB (Marr.Data.Converters.ConverterContext context) [0x00029] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\Converters\EmbeddedDocumentConverter.cs:47   at Marr.Data.Mapping.MappingHelper.LoadExistingEntity (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Object ent, System.Boolean useAltName) [0x00061] in M:\BuildAgent\work\63739567f01dbcc2\src\Marr.Data\Mapping\MappingHelper.cs:66    --- End of inner exception stack trace ---  at Marr.Data.Mapping.MappingHelper.LoadExistingEntity (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Object ent, System.Boolean useAltName) [0x000aa] in M:\BuildAgent\work\63739567f01dbcc2\src\Marr.Data\Mapping\MappingHelper.cs:79   at Marr.Data.Mapping.MappingHelper.CreateAndLoadEntity (System.Type entityType, Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Boolean useAltName) [0x00012] in M:\BuildAgent\work\63739567f01dbcc2\src\Marr.Data\Mapping\MappingHelper.cs:40   at Marr.Data.Mapping.MappingHelper.CreateAndLoadEntity[T] (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Boolean useAltName) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\Marr.Data\Mapping\MappingHelper.cs:25   at Marr.Data.DataMapper.Query[T] (System.String sql, System.Collections.Generic.ICollection1[T] entityList, System.Boolean useAltName) [0x0008d] in M:\BuildAgent\work\63739567f01dbcc2\src\Marr.Data\DataMapper.cs:577   at Marr.Data.QGen.QueryBuilder1[T].ToList () [0x00052] in M:\BuildAgent\work\63739567f01dbcc2\src\Marr.Data\QGen\QueryBuilder.cs:279   at NzbDrone.Core.Datastore.BasicRepository1[TModel].All () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:61   at NzbDrone.Core.Tv.SeriesService.GetAllSeries () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:157   at Sonarr.Api.V3.Series.SeriesModule.AllSeries () [0x00064] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Series\SeriesModule.cs:117   at Sonarr.Http.REST.RestModule1[TResource].<set_GetResourceAll>b__33_0 (System.Object options) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Http\REST\RestModule.cs:123   at Nancy.NancyModule+<>c__DisplayClass14_01[T].<Get>b__0 (System.Object args) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0   at Nancy.NancyModule+<>c__DisplayClass16_01[T].<Get>b__0 (System.Object args, System.Threading.CancellationToken ct) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0   at Nancy.Routing.Route1[T].Invoke (Nancy.DynamicDictionary parameters, System.Threading.CancellationToken cancellationToken) [0x00017] in <e31b230dbd29407fadcc55713e0bbd0f>:0   at Nancy.Routing.DefaultRouteInvoker.Invoke (Nancy.Routing.Route route, System.Threading.CancellationToken cancellationToken, Nancy.DynamicDictionary parameters, Nancy.NancyContext context) [0x00086] in <e31b230dbd29407fadcc55713e0bbd0f>:0   at Nancy.Routing.DefaultRequestDispatcher.Dispatch (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken) [0x002b7] in <e31b230dbd29407fadcc55713e0bbd0f>:0   at Nancy.NancyEngine.InvokeRequestLifeCycle (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken, Nancy.Bootstrapper.IPipelines pipelines) [0x0011d] in <e31b230dbd29407fadcc55713e0bbd0f>:0 

**System Information**

 - Sonarr Version: 3.0.3.895
 - Operating System: Debian Buster
 - mono (macOS/Linux) Version: 6.8.123

Thanks for your work

**Comment by markus101** [comment]
Looks like your DB is partially corrupt. If you can't restore a working backup you'll either need to update the DB directly (`UPDATE Series SET Images = '[]'`) then refresh all series or start from scratch.

**Comment by IDerr** [comment]
I couldn't a restore a backup, so I updated the DB directly, thanks for your help !
