### ISSUE TITLE
Download Completed & Ended Shows don't get included in regular scans

### ISSUE THREAD

**Issue by jeells102** [Sonarr/Sonarr#3833]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### What problem are you looking to solve?
Daily scans of large databases taking a long time for Completed Shows in which all files have already been downloaded and accounted for. 

### Other Information
I think, when a show has got all episodes downloaded, and the show is ended, that instead of it being included in a daily scan, it should happen either once a month, or once a week. This option can be chosen by the user. This will help with large databases and adding content.

**Comment by markus101** [comment]
> the show is ended, that instead of it being included in a daily scan, it should happen either once a month, or once a week.

It's refreshed once a month, it's rescanned, which is nothing more than getting a list of files unless you've disabled scanning after refresh (in v3). We don't have plans for options beyond that.

**Comment by Taloth** [comment]
The periodic series refresh does not take long. If it is then you have a simple performance issue that you need to investigate.
And I'm talking about ppl with 15000 shows using cloud storage for whom it remains fast enough.

Try Sonarr v3 beta, I know some improvements were made there. Also if you use cloud storage, then absolutely do NOT enable the Metadata generation option.

If you keep having issues, enable trace level logs and find out what's taking unusually long and post on the forum for support.

Good luck.
