### ISSUE TITLE
Bug when Filename has umlauts

### ISSUE THREAD

**Issue by Filechaser** [Sonarr/Sonarr#3834]
**Describe the bug**
Sonarr doesn't seem able to process files with umlauts like äöü 

**System Information**

 - Sonarr Version: 3.0.3.895
 - Operating System: [docker alpine mono]
 - .net Framework mono 5.20.1.19

If a file on disk has an umlaut in its näme like "Fascht e Familie - S05E09 - Eröffnung.mp4" it will be shown as Missing in Sonarr and will not get picked up.

Could Sonarr be changed to ensure compatibillity with the Full UTF-8-Charset?

**Comment by markus101** [comment]
Please post the requested debug logs of that series being scanned.

**Comment by Filechaser** [comment]
Sorry it was my fault.
Cifs error with charset not sonarr's fault.
