### ISSUE TITLE
Sonarr downloading html as images.

### ISSUE THREAD

**Issue by crobibero** [Sonarr/Sonarr#3835]
**Describe the bug**
Downloading thumb from tvdb results in an html image file.

**Logs**
```
20-6-25 16:36:24.5|Debug|XbmcMetadata|Generating Episode Metadata for: /virtual/media/tv/files/Roadies (2016)/Season 01/Roadies - S01E01 - Life Is a Carnival [WEBDL-720p].mkv
20-6-25 16:36:24.6|Debug|HttpClient|Downloading [https://artworks.thetvdb.com/banners/episodes/307368/5512907.jpg] to [/virtual/media/tv/files/Roadies (2016)/Season 01/Roadies - S01E01 - Life Is a Carnival [WEBDL-720p]-thumb.jpg]
```

**System Information**
- Version:  3.0.3.895
- Package Version:  3.0.3.895-ls28 by linuxserver.io 
- Mono Version:  5.20.1.34

**Additional context**
The link https://artworks.thetvdb.com/banners/episodes/307368/5512907.jpg leads to a 404 html page. TheTVDB responds with a 200 success, but with 404 html. Sonar is still downloading the file and putting the html on disk as a jpg file

```
➜ cat /mnt/virtual/media/tv/files/Roadies\ \(2016\)/Season\ 01/Roadies\ -\ S01E01\ -\ Life\ Is\ a\ Carnival\ \[WEBDL-720p\]-thumb.jpg
<html>
<head><title>404 Not Found</title><script src="/cdn-cgi/apps/head/fmFm3KANnnfPtP1n_EgxUXUm2cE.js"></script></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

```

**Comment by Taloth** [comment]
There's tvdb for ya... "It's all fine, here, have some junk." :smile:

**Comment by Taloth** [comment]
Closed with https://github.com/Sonarr/Sonarr/commit/87a64cdacbb0945c89b878d02a7eb2ac28427026
