### ISSUE TITLE
Certain API calls are broken after Sonarr v3 update

### ISSUE THREAD

**Issue by DougParker1992** [Sonarr/Sonarr#3836]
**Describe the bug**
I updated Sonarr v3 and then I was unable to change the root folder or even click the update button (there was a newer release). Saving new download clients also doesn't work. The API calls were returning error 500.

**System Information**
 - Sonarr Version: 3.0.3.895
 - Operating System: Ubuntu 18.04
 - Mono Version: 6.8.0.123

**Additional context**
I reverted back to the last working version I was using (3.0.3.892) and these functions work fine again.

**Comment by markus101** [comment]
What do the requested debug logs show?

**Comment by DougParker1992** [comment]
Here is the log for your reference. Let me know if there is anything else you need from me.

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/4834575/sonarr.txt)

**Comment by DougParker1992** [comment]
Ah, it was a permissions issue. There was an mistake in my migration script when migrating to a new server. Sorry for the hassle.
