### ISSUE TITLE
Downloads the wrong season, but correct episode

### ISSUE THREAD

**Issue by gjannece** [Sonarr/Sonarr#3837]
**Describe the bug**
There are 2 shows I have that seem to do a search and download the wrong season, but correct episode. 

**Screenshots**
Included

**Logs**
I don't have them, sorry. I will get them next time I see this issue.

**System Information**
Version - 3.0.3.896
Package Version - 3.0.2
Mono Version - 6.8.0.105
AppData directory - /var/lib/sonarr
Startup directory - /usr/lib/sonarr/bin
Mode - Console
**UI Bugs:**
 - OS: Ubuntu 18.04
 - Browser: chrome & firefox
 - Version: 3.0.3.896

I'm also using Jackett for indexers
<img width="2073" alt="Screen Shot 2020-06-25 at 6 33 58 PM" src="https://user-images.githubusercontent.com/189567/85812208-e35d6880-b714-11ea-87bc-984d3be652cf.png">
<img width="2158" alt="Screen Shot 2020-06-25 at 6 34 34 PM" src="https://user-images.githubusercontent.com/189567/85812218-e9ebe000-b714-11ea-8a16-92570ed11613.png">

**Comment by markus101** [comment]
This is covered in the FAQ. https://github.com/Sonarr/Sonarr/wiki/FAQ#how-does-sonarr-handle-scene-numbering-issues-american-dad-etc
