### ISSUE TITLE
(Create empty series folders + Delete empty folders) possible problem?

### ISSUE THREAD

**Issue by Jorman** [Sonarr/Sonarr#3838]
Sonarr -> 3.0.3.896
Mono -> 5.18.0.240

Hi, maybe this's not a bug and this's the normal behavior.
For me is pretty strange this, I'll try to explain what happen:
If I activate both options
![image](https://user-images.githubusercontent.com/5203988/85883443-4ae0ea00-b7e1-11ea-90db-3101a615fef2.png)
The result is that a day or so (I think after a regular disk scan) I find all the tv show folder about seasons that are paused or ended and obviously there's nothing inside.
So for example let say that X-Files is monitored (and it's) so, for now is ended, but you know, keep it monitored is better, maybe one day a new episode will be released!
So, after a while, I'll find X-Files folder under the root folder structure.

Seems that the _**Delete empty folders**_ option was executed before the _**Create empty series folders**_ option, in that way Sonarr before Delete empty folder, then create again empty folder.

What do you think?

I don't have any log, let me know if you need any extra procedure to make a log for you, if needed.

Thanks, Jo

**Comment by fryfrog** [comment]
I remember talking about this recently on Discord and everyone's guess would be that they'd appear and disappear every 12-24 hours. They should probably be mutually exclusive, maybe a single drop down selector that only allows off, create or delete?

**Comment by markus101** [comment]
As far as foot guns go, this is as minor as they come. I’m not even sure it’s worth the effort to combine them, just don’t enable both options...

Maybe we could guard against creating if they’re supposed to be deleted, but then again, just don’t enable both options.

**Comment by Jorman** [comment]
Yep, both right!
The "problem" came randomly, appear and disappear, one time I see empty folder and the very next day all is gone. Sometimes I see my kodi player try to scan a tv show that I know is empty and the day after, no scan for the show.

@markus101 
I agree with you, is not a big problem, was good if working, I mean is pretty convenient, if one folder is missing during a scan or when the episode is downloaded, the folder is created, instead if the folder is empty is removed. This because I used to have a separate root folder for my colleague, and when I bring all the show to them I delete all folder too :D 
I'm pretty sure that the same bug is present on Radarr, I'll make an issue on it's side too.

For now I just enable the delete option

J
