### ISSUE TITLE
Add a refresh button for Interactive Search for Episodes/Seasons

### ISSUE THREAD

**Issue by vtruong68** [Sonarr/Sonarr#3842]
**Describe the problem**
When searching for episodes or season packs, indexers sometimes fail to find any relevant results despite there existing such an episode/season pack. The only way to retry is to close the menu and click the search button again. 

**Describe any solutions you think might work**
Adding a refresh button of some sort for these searches would be very useful as to avoid having to close in and out of menus. 

**Additional context**
I'm currently using the phantom-develop branch on v3 via docker. If I recall correctly, v2 allowed you to click the search tab again when searching for individual episodes in order to retry a search.

**Comment by markus101** [comment]
We don't have plans to introduce that same behaviour from v2 or a refresh button.

> When searching for episodes or season packs, indexers sometimes fail to find any relevant results despite there existing such an episode/season pack.

That's something that should be troubleshooted and resolved, I haven't seen any indexers behave that way first hand.
