### ISSUE TITLE
Add an option to grab original language

### ISSUE THREAD

**Issue by MayeulC** [Sonarr/Sonarr#3843]
**Describe the problem**
The new language profile are neat. However, most of the time, I prefer the original language, so I end up looking up what language it was originally filmed with, creating a new profile if it doesn't exist, and picking that one.

**Describe any solutions you think might work**
Add an "original language" option to the language profile list. The title metadata includes the original language in most cases, so it could be looked up after that.

**Additional context**
The "VOSTFR" (talked about in #280) [means](https://acronyms.thefreedictionary.com/VOSTFR) "Version Originale Sous-Titrée Français" (Original language with French subs). Ditto for NL-subs and just "VO". Multi (as discussed in #2854) often contains at least the original show language, plus various languages.

**Comment by markus101** [comment]
Original language is not possible until at least TVDB API v4. Tagging this for a look in the future.

**Comment by MayeulC** [comment]
Thanks for the info, I was not aware that the TVDB was the single source of truth. Couldn't something like wikidata [fill in some of the blanks](https://query.wikidata.org/#%23Original%20language%20label%20for%20a%20given%20imdb%20id.%0ASELECT%20DISTINCT%20%3Fitem%20%3Ftitle%20%3Foriginal_lang%20%3Fimdbid%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ5398426%3B%0A%20%20%20%20wdt%3AP1476%20%3Ftitle%3B%0A%20%20%20%20wdt%3AP364%2Fwdt%3AP424%20%3Foriginal_lang%3B%0A%20%20%20%20wdt%3AP345%20%3Fimdbid.%0A%20%20FILTER%28%3Fimdbid%20%3D%20%22tt0944947%22%29%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D)?

**Comment by markus101** [comment]
Besides that fact that those queries are incredibly slow (7+ seconds on first query), it's not something we're going to utilize.

**Comment by MayeulC** [comment]
> those queries are incredibly slow

That specific performance issue was due to the fact the query I wrote iterates over the whole list of series Wikidata has, and then filters by IMDB ID. [That one](https://query.wikidata.org/#%23Original%20language%20label%20for%20a%20given%20imdb%20id.%0ASELECT%20DISTINCT%20%3Fitem%20%3Ftitle%20%3Foriginal_lang%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ5398426%3B%0A%20%20%20%20wdt%3AP1476%20%3Ftitle%3B%0A%20%20%20%20wdt%3AP364%2Fwdt%3AP424%20%3Foriginal_lang%3B%0A%20%20%20%20wdt%3AP345%20%22tt0944947%22%20.%0A%7D) is much quicker (600ms on first iteration, less than 10ms after, and could be even quicker if someone was to extract the dataset before). Plus, I am pretty certain a query can be constructed to look every item at the same time, it that was useful.

> it's not something we're going to utilize

I can understand not wanting to add another metadata provider for better maintainability. But is there a specific issue with Wikidata? I can see it useful as a "backup provider", and it has some information that is otherwise hard to come by.
I don't really know of any project that makes use of these TV show metadata Wikidata has, to be honest. But that could incentivize more people to contribute to Wikidata as well.

Besides that, I get your point about waiting for the TVDB API v4. I can wait :)

**Comment by chescos** [comment]
Now that TVDB API v4 is out, would this be reconsidered?

**Comment by MayeulC** [comment]
I'd like to note that Radarr now supports this: https://github.com/Radarr/Radarr/pull/4980

**Comment by Bokaii** [comment]
Are there any plans on implementing this soon? If you watch a lot of foreign shows and don't want them dubbed, this is a really annoying issue. You have to manually create a new language profile for every langugage and also change edit the show to the correct profile. 

Using the "languages higher in the list" option is pointless as well, because it only means you will get a lot more dubbed versions.

As mentioned above, how Radarr solves it is perfect.

**Comment by Bokaii** [comment]
> would it make sense to allow us to simply create a language profile with no language checked, thus bypassing any language checks? I ask this while not knowing how sonarr verifies language tbh, but this seems like a way to create a profile basically saying "accept any language".

Original language is not the same as any language. It would mean you could get dubbed languages that is not wanted. I'd prefer the original language over a dubbed one, even if I know the dubbed language.

**Comment by krrishsgk** [comment]
Bump on this feature request. Been using it on Radarr, and love how simple it is.

**Comment by Ulrar** [comment]
Could this be re-opened ?
I understand if no one is willing to work on it now but it'd be nice to at least leave it open for later, since it's now possible to implement it

**Comment by Dnkhatri** [comment]
> Could this be re-opened ? I understand if no one is willing to work on it now but it'd be nice to at least leave it open for later, since it's now possible to implement it

its already been added but in V4 as v3 no longer getting new features. v4 still is in alpha 
https://github.com/notifications?query=repo%3ASonarr%2FSonarr

**Comment by VilhenaChen** [comment]
I belive Radarr already implemented this, can Sonnar also implement it?

**Comment by at-besa** [comment]
just casually asking if it is possible to bring this feature to sonarr too?
as it would be nice to have the renaming in the langauge the main language of the series or the platform is configured to, actually its always renamed to the english version. As far as i know tmdb and tvdb both supports searching in foreign languages, at least filebot is able to do so. Would be amazing to have sonarr to be able to have that.

**Comment by bonswouar** [comment]
For reference: https://trash-guides.info/Sonarr/Tips/How-to-setup-language-custom-formats/
It works fine, but it would be much cleaner to have the option backed in instead of creating a Custom Format just for that.

I believe this is something that basically 90+% of people would enable, nobody wants (only) dubbed audio nowadays.
