### ISSUE TITLE
Warrior Nun episode names brakes Quality Definitions

### ISSUE THREAD

**Issue by tedrock** [Sonarr/Sonarr#3847]
**Describe the bug**
It appears the episode names for Warrior Nun (Warrior Nun - 1x01 - Psalms **46:5** or Warrior.Nun.S01E01.Psalm.**46.5**.NF.WEB-DL.DD5.1.x264-NTG) are messing with the Quality Definitions. **Every result** for every episode is rejected because the size is larger than maximum allowed 0 B (for 0min),

**System Information**

 - Sonarr Version: [2.0.0.5344]
 - Operating System: [Ubuntu]
 - mono (macOS/Linux) Version: [5.20.1.34]

**Comment by markus101** [comment]
`for 0min` because the runtime in series is 0 minutes, looks like Skyhook has the correct value, so refresh, unless there is still CF caching in the way it'll fix it, otherwise wait ~1 hour then refresh.
