### ISSUE TITLE
Sonarr ignore release if the title has an unwanted language in the name

### ISSUE THREAD

**Issue by xderor** [Sonarr/Sonarr#3849]
this screenshot will show the bug better than any description I could give.

![sonarr](https://user-images.githubusercontent.com/9821753/86467703-c684ee80-bd2d-11ea-9f08-45a545163b8e.PNG)

**Comment by Thirrian** [comment]
See https://github.com/Sonarr/Sonarr/issues/861

**Comment by xderor** [comment]
Thanks, I through someone would have reported it already but a quick search had not turn up anything
