### ISSUE TITLE
qbittorrent season pack not moved when finished

### ISSUE THREAD

**Issue by evlo** [Sonarr/Sonarr#3850]
**Describe the bug**
After season pack is downloaded using qBittorrent it did not moved it to the correct location.
Weirdly if family members requested something using ombi it worked for them.
Might be because qbittorrent update to 4.2.5?
It seems that sonarr does not see torrent as completed.

**Screenshots**
https://i.imgur.com/MTzwcMt.png
https://i.imgur.com/Inuuizm.png
https://i.imgur.com/7OmC7hf.png
https://i.imgur.com/ajMjUcZ.png

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: [e.g. 2.0.0.5344]
 - Operating System: [debian]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [5.20.1.34]

**Comment by markus101** [comment]
Your fourth screenshot shows the reason why, the episode title was TBA and had recently aired.
