### ISSUE TITLE
Renaming issue when including audio/subtitles in name

### ISSUE THREAD

**Issue by DigitalSteel7** [Sonarr/Sonarr#3852]
##Bug Report

When renaming Anime using:
{Series Title} - S{season:00}E{episode:00} ({absolute:000}) - {Episode Title} ({Quality Title}{ MediaInfo VideoDynamicRange}{ MediaInfo VideoBitDepth}bit { MediaInfo Simple}{ MediaInfo AudioLanguages}{ MediaInfo SubtitleLanguages})

If the episode is missing an absolute number, such as if it is a special, it will not include the audio or subtitle language in the rename.

**Sonarr Version:** 3.0.3.896

**Operating System:** Windows 10

**Comment by Taloth** [comment]
Episodes without absolute number use the Standard naming format.
