### ISSUE TITLE
Release profiles - Preferred words causing the same episode to be downloaded

### ISSUE THREAD

**Issue by Cumminsc9** [Sonarr/Sonarr#3853]
**Describe the bug**
I have a preferred words setup for certain release groups, as I prefer these over others. However, I have noticed this is causing the same episode is downloaded multiple times. Sonarr removes the existing episode and replaces it with the exact same episode it just downloaded. Anyway, after some searching I came across a similar ticket #3702 which led me to enabling trace logging. I then waited until the next sync, and eventually Sonarr found the same episode and downloaded it, looking into the trace logs I found that essentially it had downloaded the same episode, as the one on disk did not contain the preferred word when comparing the new name with the existing name (see Logs 1)

So I assumed that if I included the {Release Group} tag in the episode naming format `S{season:00}E{episode:00} - {Episode Title} - {Release Group}` it should notice that the preferred word already exists within the existing download and ignore the new download, unless there was a release with a higher preferred word. I made the change and a couple of days pass, and well unfortunately today I had noticed it downloaded the same Snowpiercer episode 4 times, where 3 downloads were identical (as you can see from the screen capture) looking into the logs again (trace was still enabled) I could see that even though the existing file on disk contained the release group tag when it calculated the preferred word score the existing came out as 0 (unexpected) with the new one as 2 (expected) which causes it to be downloaded and overwritten.

Unfortunately for the meantime I'm going to have to disable my release profile, though I am curious is this a bug?

If any further details are required I should be able to retrieve them.

**Screenshots**
![image](https://user-images.githubusercontent.com/10427953/86581658-4d2d0c00-bf78-11ea-930b-5d1632cc718f.png)

**Logs**
Logs 1
> 20-6-29 12:10:00.9|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-720p v1 - English
> 20-6-29 12:10:00.9|Trace|PreferredWordService|Calculating preferred word score for 'Dark.S03E01.Deja-vu.720p.NF.WEB-DL.AAC5.1.x264-CHX'
> 20-6-29 12:10:00.9|Trace|PreferredWordService|Calculated preferred word score for 'Dark.S03E01.Deja-vu.720p.NF.WEB-DL.AAC5.1.x264-CHX': 0
> 20-6-29 12:10:00.9|Trace|PreferredWordService|Calculating preferred word score for 'Season 3/S03E01 - Deja-vu.mp4'
> 20-6-29 12:10:00.9|Trace|PreferredWordService|Calculated preferred word score for 'Season 3/S03E01 - Deja-vu.mp4': 0
> 20-6-29 12:10:00.9|Debug|UpgradableSpecification|Comparing preferred word score. Current: 0 New: 5
> 20-6-29 12:10:00.9|Debug|UpgradableSpecification|New item has a better preferred word score

Logs 2
> 20-7-6 09:00:06.7|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBRip-720p v1 - English
> 20-7-6 09:00:06.7|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBRip-720p v1 - English
> 20-7-6 09:00:06.7|Trace|PreferredWordService|Calculating preferred word score for 'Snowpiercer.S01E08.720p.WEBRip.x264-BTX'
> 20-7-6 09:00:06.7|Trace|PreferredWordService|Calculated preferred word score for 'Snowpiercer.S01E08.720p.WEBRip.x264-BTX': 0
> 20-7-6 09:00:06.7|Trace|PreferredWordService|Calculating preferred word score for 'Season 1/S01E08 - These Are His Revolutions - BTX.mkv'
> 20-7-6 09:00:06.7|Trace|PreferredWordService|Calculated preferred word score for 'Season 1/S01E08 - These Are His Revolutions - BTX.mkv': 0
> 20-7-6 09:00:06.7|Debug|UpgradableSpecification|Comparing preferred word score. Current: 0 New: 2
> 20-7-6 09:00:06.7|Debug|UpgradableSpecification|New item has a better preferred word score

**System Information**

 - Sonarr Version: 3.0.3.894
 - Operating System: Ubuntu 18.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 5.18.1

**Comment by bakerboy448** [comment]
This bug/issue seems stale.  Please check and see if it is still an issue on the recent v3 builds.  If it is an issue please open a new GHI with logs and full detail.

**Comment by markus101** [comment]
If it's still an issue please upload the related log and link it here, without seeing exactly which release was being processed in the logs (only which file was on disk) it's hard to see what the difference is.

Also a screenshot of the release profile(s), please.
