### ISSUE TITLE
Sorting Mass Editor by Language Profile and Tags

### ISSUE THREAD

**Issue by ldexterldesign** [Sonarr/Sonarr#3854]
**Describe the problem**

As a user, when I use Mass Editor, I want to be able to sort all columns (inc. series type and tags)

**Describe any solutions you think might work**

Implement existing sort feature (i.e. from title, quality profile, season folder, path etc.) for the aforementioned columns too

**Additional context**

<img width="1904" alt="Screenshot 2020-07-07 at 19 34 39" src="https://user-images.githubusercontent.com/1715809/86826645-f2370a00-c088-11ea-911c-69d9735e11a3.png">

<img width="615" alt="Screenshot 2020-07-07 at 19 34 48" src="https://user-images.githubusercontent.com/1715809/86826656-f4996400-c088-11ea-9049-3c2562c40b0d.png">

Sincerely

**Comment by markus101** [comment]
> series type

You can already sort by series type.

The only columns you can't sort on there are Language Profile and tags, Language Profile is an oversight, but tags was intentional at the time, what would you actual sort tags by? number of tags?

**Comment by ldexterldesign** [comment]
Thanks for quick reply

> You can already sort by series type

Hmm, I'm unable to sort by `series type` with my [version]

I'll update to latest version now and report back if it's fixed else consider testing this for yourself as it may be a bug

> The only columns you can't sort on there are Language Profile and tags, Language Profile is an oversight, but tags was intentional at the time, what would you actual sort tags by? number of tags?

Ahh, good point. A boolean type (i.e. has tags, does not have tags) would be better than nothing IMO.

Cheers

[version]:
Version: 3.0.3.790
Package Version: 3.0.3.790-ls1 by linuxserver.io
Mono Version: 5.20.1.34

**Comment by ldexterldesign** [comment]
> I'll update to latest version now and report back if it's fixed else consider testing this for yourself as it may be a bug

It's been fixed in the latest [version]

Be good to get sorting for `tags`

Aside, from a quick inspection I see there are other [views] without full column sorting support so perhaps this is a broader issue/task, in which case I recommend updating the issue title to something like "Add full table column sorting support for all views"

Sincerely

[views]:
activity > history > episode && episode title && quality
wanted > missing > episode && episode title && status

[version]:
Version: 3.0.3.896
Package Version: 3.0.3.896-ls30 by linuxserver.io
Mono Version: 5.20.1.34

**Comment by markus101** [comment]
Those views are server side, we don't have plans to sort by episode on those views. Sorting by quality is covered here by https://github.com/Sonarr/Sonarr/issues/702

**Comment by RobinDadswell** [comment]
@markus101 assign this to me and I will take a look at it

**Comment by bakerboy448** [comment]
Assigned

**Comment by RobinDadswell** [comment]
Cheers mate
