### ISSUE TITLE
File scanner ignores filenames with accents

### ISSUE THREAD

**Issue by TheSpad** [Sonarr/Sonarr#3856]
**Describe the bug**
File scanner ignores filenames with accents (é, í, ú, etc.). Removing the accent characters allows the file to be picked up by the scanner, but if you then use the Sonarr rename function it outputs the wrong character set (Looks like UTF-8/Latin-1 confusion).

From my POV either the file scanner should handle accents in filenames *or* the rename function shouldn't try to add them into filenames (and fail to do so correctly). If the scanner can't handle accents in filenames there should be some log or notification so that we're aware a file has been skipped.

**Screenshots**
With accents:
![Annotation 2020-07-08 123235](https://user-images.githubusercontent.com/8425502/86913911-4688cb00-c117-11ea-9352-58a96e53ead1.jpg)
![Annotation 2020-07-08 123300](https://user-images.githubusercontent.com/8425502/86913913-47216180-c117-11ea-9425-ad2eb7d3a98a.jpg)
No accents:
![Annotation 2020-07-08 123326](https://user-images.githubusercontent.com/8425502/86913916-47b9f800-c117-11ea-9101-b6784d818a75.jpg)
![Annotation 2020-07-08 123313](https://user-images.githubusercontent.com/8425502/86913915-47b9f800-c117-11ea-9ddc-7656eb131bf9.jpg)
Rename Function:
![Annotation 2020-07-08 123754](https://user-images.githubusercontent.com/8425502/86914495-5c4ac000-c118-11ea-8ea9-464d483bc28b.jpg)

**Logs**
```
20-7-8 12:34:51.6|Info|RefreshSeriesService|Updating 'Allo 'Allo!
20-7-8 12:34:51.7|Debug|Api|[GET] /api/v3/command: 200.OK (0 ms)
20-7-8 12:34:51.8|Info|RefreshEpisodeService|Starting episode info refresh for: [73940]['Allo 'Allo!]
20-7-8 12:34:51.8|Debug|EpisodeAddedService|No new episodes, skipping search
20-7-8 12:34:51.8|Info|RefreshEpisodeService|Finished episode refresh for series: [73940]['Allo 'Allo!].
20-7-8 12:34:51.8|Debug|RefreshSeriesService|Finished series refresh for 'Allo 'Allo!
20-7-8 12:34:51.8|Debug|XemService|Scene numbering is not available for 'Allo 'Allo! [73940]
20-7-8 12:34:51.9|Info|DiskScanService|Scanning 'Allo 'Allo!
20-7-8 12:34:51.9|Debug|DiskScanService|Scanning '/media/Allo Allo/' for video files
20-7-8 12:34:51.9|Debug|DiskScanService|81 video files were found in /media/Allo Allo/
20-7-8 12:34:51.9|Debug|DiskScanService|[73940]['Allo 'Allo!] Cleaning up media files in DB
20-7-8 12:34:51.9|Debug|ImportDecisionMaker|Analyzing 0/81 files.
20-7-8 12:34:51.9|Info|DiskScanService|Completed scanning disk for 'Allo 'Allo!
20-7-8 12:34:52.0|Debug|ExistingExtraFileService|Looking for existing extra files in /media/Allo Allo/
20-7-8 12:34:52.0|Debug|DiskScanService|Scanning '/media/Allo Allo/' for non-video files
20-7-8 12:34:52.0|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
20-7-8 12:34:52.0|Debug|DiskScanService|0 non-video files were found in /media/Allo Allo/
20-7-8 12:34:52.0|Debug|ExistingMetadataImporter|Looking for existing metadata in /media/Allo Allo/
20-7-8 12:34:52.0|Info|ExistingMetadataImporter|Found 0 existing metadata files
20-7-8 12:34:52.0|Debug|ExistingSubtitleImporter|Looking for existing subtitle files in /media/Allo Allo/
20-7-8 12:34:52.0|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
20-7-8 12:34:52.0|Debug|ExistingOtherExtraImporter|Looking for existing extra files in /media/Allo Allo/
20-7-8 12:34:52.0|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
20-7-8 12:34:52.0|Info|ExistingExtraFileService|Found 0 extra files
20-7-8 12:34:52.0|Debug|CleanExtraFileService|Cleaning missing metadata files for series: 'Allo 'Allo!
```

**System Information**

 - Sonarr Version: 3.0.3.896
 - Operating System: Docker
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 5.20.1.34

**Comment by TheSpad** [comment]
Just to note this seems to be a recent issue as I've just noticed a bunch of previously recognised files with accents in them have suddenly appeared in my "Missing" list.

**Comment by markus101** [comment]
This sounds the same as https://github.com/Sonarr/Sonarr/issues/3834 which was due to CIFS mounting.

The logs also show that Sonarr didn’t find any video files; there was nothing for it to reject just because it had an accent in the file name (which it doesn’t do).

If you’re still having issues, please open a thread on the forums or subreddit for support.
