### ISSUE TITLE
Feature Request: Redownload on BluRay release

### ISSUE THREAD

**Issue by nuentes** [Sonarr/Sonarr#3857]
**Describe the problem**
For all series, I basically want sonarr to grab whatever is available on initial episode release. This is obviously working fine. However, for some series' I would like for it to overwrite that file when a BluRay rip is available. Currently this would need to be a manual process.

**Describe any solutions you think might work**
This setting would probably be set at both the Series and Season level. The Series can have this enabled by default, but then you can disable it manually for Seasons where this has already been completed. At the Series level, this would be a simple on/off switch, and at the Season level it would be much the same. Think of it as a 2nd version of Monitored - Monitored for Secondary Release. Enabling this at the series level also adds a Secondary Profile box, where you can include your desired Blu-Ray profile.

Since Sonarr is not bundled with specific Blu-Ray profiles, there should also be a question mark to hover over that suggests you create these profiles before enabling this feature. If a user adds a Secondary Profile, there needs to be a check in place. Sonarr needs to confirm that the Secondary Profile and the Primary Profile have zero matching Qualities. If they have matching qualities, then you could essentially be telling Sonarr to redownload the same files again. Sonarr would block this with a simple red exclamation mark warning and disabling save.

**Comment by markus101** [comment]
This is how profiles already work, add blurry to the profile and set the cutoff accordingly.

**Comment by nuentes** [comment]
Hey, I just want to say thanks. The way this existing implementation is configured is way smarter than what I suggested. Sorry, still just getting my feet wet, apparently.
