### ISSUE TITLE
Settings option to disable RSS sync when nothing in "Wanted"

### ISSUE THREAD

**Issue by outis151** [Sonarr/Sonarr#3858]
Syncing RSS is not useful when nothing is in the "Wanted" list and causes unnecessary network and processor activity by default every 15 minutes.

This is a revival of issue (#2259) that was closed because "This suggestion wouldn't work well for all users".
In my opinion though this can be easily fixed using a settings option which is by default deactivated and wouldn't break anything.

**Comment by markus101** [comment]
We don't have plans for such a feature.
