### ISSUE TITLE
Feautre Request - Add Root Folders From Media Mangement to System => Status Page

### ISSUE THREAD

**Issue by ondrovic** [Sonarr/Sonarr#3860]
**Describe the problem**
Add the Media Management Root Folder Info under System/Status Disk Space

**Additional context**
It would be nice to see how much disk space is left in your root folders, for example I run Sonaar on a docker container and it displays only free space about my container, but my actual media is store on a file server. If would also be nice to have something like the following

![image](https://user-images.githubusercontent.com/3682042/87086200-d81b3a00-c1f6-11ea-9117-2c832cc6b4da.png)

**Comment by markus101** [comment]
Root folders are already included, though they bubble up to the mount point.

If you have `/volume1/tv` and `/volume1/tv2` as root folders, then only `/volume1` would appear. Volumes that Sonarr can't determine the total size/free space for won't be included.

If you're not seeing the mounts for your root folder(s) then take a look at the logs and open a thread on the forums/subreddit for support if necessary.
