### ISSUE TITLE
Email/Text Alerts for log mesages of a certain priority

### ISSUE THREAD

**Issue by baconwaifu** [Sonarr/Sonarr#3861]
Currently, when sonarr loses connection to a downloader or indexer, it records that in the log, but never actually notifies the user directly. This is occasionally a problem with deluge, because sonarr can *appear* to be working fine, and deluged can *be* working fine, but it can't talk to deluge because the webUI component broke for on reason or another (such as not having a default server to connect to on startup, so you have to manually connect it, or add a config file).

The current notification method for warnings is a popup in the "system" tab, but that requires logging into sonarr, and if you aren't adding new series or manually importing existing ones, you're not likely to see it. it also only works for some error types, such as an indexer failing.

Given that sonarr already has an SMTP sending component, used for notifications about downloads and imports, it shouldn't be too hard to extend that interface with an "optional" log alert interface (connections that support "freeform" information such as email) and add a menu to the standard log settings with a list of all "alert-capable" connections to enable alerting for, and a tab for what log level to trigger on (defaulting to warning?)

**Comment by markus101** [comment]
IN v3 Heath check failures can trigger notifications, but we don't have plans to send them based on logs of a certain level or of a specific message being logs.
