### ISSUE TITLE
Unable to add "Löwenzahn" by its TVDB id

### ISSUE THREAD

**Issue by hashworks** [Sonarr/Sonarr#3864]
I can't add a specific TV show by its TVDB id although is has an English title set.

Searching for a well known tv show works fine:
![onepiece](https://fb.hash.works/W8qyT/)

However, "Löwenzahn" can't be added by its TVDB ID:
![löwenzahn](https://fb.hash.works/e2i163n/)

The [TV show in question](https://www.thetvdb.com/series/84829-show) has an English title set, as stated as required [in the wiki](https://github.com/Sonarr/Sonarr/wiki/FAQ#why-cant-i-add-a-new-series-when-i-know-the-tvdb-id):
![englishtitle](https://fb.hash.works/78v7T/)

**System Information**
 - Sonarr Version: 3.0.3.899 (sonarr-phantom)
 - Operating System: Arch Linux
 - mono Version: 6.8.0

**Additonal information**

Searching for its title "Löwenzahn" doesn't work as well.

**Comment by markus101** [comment]
Please use the forums or subreddit for support.

I'm able to search by ID and title and see it come up. It may have been a cache delay as it can take over 24 hours for TVDB's API to update.
