### ISSUE TITLE
Custom Script doesn't trigger on Manual Import

### ISSUE THREAD

**Issue by 19wolf** [Sonarr/Sonarr#3866]
**Describe the bug**
Manual import doesn't trigger custom script

**System Information**

Version
3.0.3.899
Package Version
3.0.3.899-ls31 by linuxserver.io
Mono Version
5.20.1.34

**Comment by markus101** [comment]
Unless there is a tag restricting it, or it's not a "new download" (from outside of the series folder) then it should fire, but with the absence of the requested logs it's impossible to know. Look at the debug and / or trace logs.

**Comment by 19wolf** [comment]
https://www.dropbox.com/s/erxnr4qho8xl5wm/sonarrlog?dl=0

**Comment by 19wolf** [comment]
So I cleared the logs and tried again

https://pastebin.com/YN8s0EH8 -- trace
https://pastebin.com/12n0v3Z5 -- debug

**Comment by markus101** [comment]
> 20-7-13 00:21:17.4|Debug|NotUnpackingSpecification|/data/Media/Anime/Rental Girlfriend (2020) - 380654/[EMBER] Rent-a-girlfriend 01 WEBRip-1080p x265 AAC.mkv is in series folder, skipping unpacking check

It's already in the series folder, so it's not considered a new download that would trigger the `On Import` event.

**Comment by 19wolf** [comment]
So something I haven't figured out is how to manually import something on the series page that isn't already in the series folder...

**Comment by markus101** [comment]
Use Manual Import on Wanted: Missing

**Comment by markus101** [comment]
Closing since the file was already in the series folder when imported.
