### ISSUE TITLE
More telegram options

### ISSUE THREAD

**Issue by springjools** [Sonarr/Sonarr#3867]
**Describe the problem**
I want to send notifications from sonarr to telegram group. I don't want to have a pop-up when each message arrives, jut a silent notification.

**Describe any solutions you think might work**
This would be possible by adding the field "disable_notification=boolean" to the message method.  
See: https://core.telegram.org/bots/api#sendmessage

**Additional context**
Nothing really. A check box in sonarr telegram connect window would be needed also to allow user to toggle whether the message should be silent or not.

![image](https://user-images.githubusercontent.com/5911982/87306577-e338d780-c520-11ea-85cd-5e5172a84cdf.png)

**Comment by springjools** [comment]
![image](https://user-images.githubusercontent.com/5911982/87307004-8f7abe00-c521-11ea-8c6c-c48a3950224c.png)

**Comment by springjools** [comment]
Why not also add a corresponding windows to disable eweb page preview. It can be added with the field "disable_web_page_preview=boolean". It looks like this:
![image](https://user-images.githubusercontent.com/5911982/87307355-1f206c80-c522-11ea-9415-77dd4bef5941.png)

**Comment by Dtaggart** [comment]
> Why not also add a corresponding windows to disable eweb page preview. It can be added with the field "disable_web_page_preview=boolean". It looks like this:
> ![image](https://user-images.githubusercontent.com/5911982/87307355-1f206c80-c522-11ea-9415-77dd4bef5941.png)

I don't think this is need, sonarr doesn't send links in the notifications. Looks like Radarr.

**Comment by springjools** [comment]
Why not add the functionality now for future proofing?

**Comment by Dtaggart** [comment]
> Why not add the functionality now for future proofing?

You shouldn't add a option that doesn't do anything. Next thing you know you'll get asking why when they turn it off why aren't links being sent, and then when you do add it the next dev might not know it exists and forget to link it. If you want this, I would split this into a request for the feature to add links and add the requirement of this option in telegram.

**Comment by springjools** [comment]
It does do something, as described in telegram api, it prevents the loading of the preview. Don't assume what users want, that's what options are for.

**Comment by markus101** [comment]
There are no links sent from Sonarr for telegram messages, so it would be an option that does nothing. If at some point links are added the. It would make sense to add that option.

**Comment by Dtaggart** [comment]
> It does do something, as described in telegram api, it prevents the loading of the preview. Don't assume what users want, that's what options are for.

Right, it wouldn't do anything from the point as changing sonarr behavior. I wasn't making any assumptions, that functionality is not available. I would suggest again that if you would want this make a separate issue for that feature and include the telegram option in that enhancement request.

**Comment by springjools** [comment]
Right, maybe I assumed the functionality was similar between all the arrs. But the more important feature is the first one: to send messages silently.

Telegram includes that option and it would be easy to implement it. And quite a bit quality improvement for the end user.
