### ISSUE TITLE
[Feature Request] Automatical indexer sync with Jackett

### ISSUE THREAD

**Issue by lmarianski** [Sonarr/Sonarr#3868]
**Describe the problem**
Adding indexers manually from Jackett is pretty annoying.

**Describe any solutions you think might work**
Create a Connection, which queries Jackett and adds/removes the indexers automagically.

**Comment by Thirrian** [comment]
#3530
As mentioned there, you can copy indexers in sonarr (v3), which makes this less painful.

**Comment by lmarianski** [comment]
Ah, interesting, from what i see this feature isnt something thats gonna get implemented any time soon, but can we atleast get the ability to change Sonarr settings thru the api (including adding indexers) if someone wants to implement this themselves?

**Comment by Thirrian** [comment]
Anything you can do in the GUI, you should be able to do with API calls, although it's sometimes not documented on the wiki.
Easiest is to keep your browsers' dev console open and perform the action you want to do in the GUI and see what kind of request(s) are made 🙂
