### ISSUE TITLE
Media Management - Permissions error: Must contain a valid Unix permissions octal

### ISSUE THREAD

**Issue by shabbosgoy** [Sonarr/Sonarr#3869]
**Describe the bug**
When navigating into Media Management under Settings, enabling Show Advanced Settings and scrolling down to the Permissions section of the Media Management settings, ticking the `Should chmod be run when files are imported/renamed?` and then changing the `File chmod mode` to anything else than 0644 results in an input verification error saying `Must contain a valid Unix permissions octal`.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/29663190/87424653-9ca8b300-c5dc-11ea-91ab-80bde1f1bcce.PNG)

![Capture2](https://user-images.githubusercontent.com/29663190/87425147-6b7cb280-c5dd-11ea-8280-e0eb3c0d5aeb.PNG)

**Logs**
```
20-7-14 12:16:04.7|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- FileChmod: Must contain a valid Unix permissions octal
```

**System Information**

 - Sonarr Version: 3.0.3.899
 - Operating System: Ubuntu 18.04.4 LTS
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono JIT compiler version 6.10.0.104

**UI Bugs:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 78.0.2 64-bit

**Additional context**
None.

**Comment by 19wolf** [comment]
Having the same problem. Though I am able to set the permissions to `666`, it looks like anything with a `7` doesn't work.

Version
3.0.3.899
Package Version
3.0.3.899-ls32 by linuxserver.io
Mono Version
5.20.1.34

**Comment by FrequencyLost** [comment]
Also experiencing this problem. Unable to set to anything with a 7 on this (currently) latest version of Sonarr

Getting error "Must contain a valid Unix permissions octal"

Version
3.0.3.905
Package Version
3.0.3.905-ls35 by linuxserver.io
Mono Version
5.20.1.34

**Comment by Taloth** [comment]
It's mostly a UX thing, set it to 664. or anything like that.

**Comment by xen0m0rph2020** [comment]
still same issue on latest version. I need to use 755 so that other containers that run under different users can access and execute those files.

**Comment by shabbosgoy** [comment]
When is this issue going to be fixed? It's annoying and it keeps files from being copied and renamed properly.

**Comment by Taloth** [comment]
Told you it's a cosmetic thing... if you want file permissions 775 then fill in 664

**Comment by taylorcox75** [comment]
Similar issue on Radarr, problem was it's a file octal so they don't want to make them executable.
https://github.com/Radarr/Radarr/issues/5208#issuecomment-708286797

**Comment by bakerboy448** [comment]
https://github.com/Sonarr/Sonarr/pull/3999

**Comment by Taloth** [comment]
Closed via https://github.com/Sonarr/Sonarr/pull/3999
