### ISSUE TITLE
Automatically Add Tags Based on Series Attributes

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#3870]
**Describe the problem**
Right now there is no way to automatically set tags based on the series type or any other attribute, without a way to apply tags automatically users need to manually add tags for each series they add, which may differ for anime vs standard or adults vs kids shows.

**Describe any solutions you think might work**
A clear and concise description of any solutions or features you've considered.

A custom filter-like implementation where users can create rules that result in tags being added.

With series that have the type anime, add the `anime` tag, for ones in the `/tv-kids` root folder add the `kids` tag, etc.

To start these could be single rules resulting in one or more tags being added, in the future there could be more complex rules, such as `series type && root folder`.

Tag settings seems like a reasonable place for this to exist.

**Comment by douglas24** [comment]
I would like to +1 this.

I was about to request auto-tagging for another use case: An option to auto-tag series with the qualities of all the episodes (maybe in the Settings>Tags section?).

Currently you can only filter shows by what quality profile is assigned to the show. It would be very useful to be able to filter shows based on the actual quality of episodes currently downloaded (e.g. filtering to find any series with an SDTV quality episode or Unknown quality episode). Auto-tags would enable that filter ability superbly.

**Comment by rcdailey** [comment]
I am going to start working on this.

**Comment by undead9786** [comment]
> I am going to start working on this.

Has there been any progress with this? Would love to automate tagging for what quality I have in a series.

**Comment by undead9786** [comment]
> It's on my (very long) todo list, I just haven't had much time to commit to it. I will try to make more time for it since it's already been over a year (man, time flies...)

It definitely does, glad it still on the list of things to do and not dropped away though!

**Comment by Smexhy** [comment]
I would love to see this happen

**Comment by meelokun** [comment]
i too would love to see this happen. +1

**Comment by Feramance** [comment]
I would love to see this happen too, at least based on media management path
