### ISSUE TITLE
Poster Options on the Sonarr index/poster page are lost after closing browser

### ISSUE THREAD

**Issue by shabbosgoy** [Sonarr/Sonarr#3872]
**Describe the bug**
When navigating to the Sonarr index/poster page, click Options in the top bar. Change any Poster Options and hit Close. Then close the browser and visit the Sonarr index/poster page again. The changed Poster Options are no longer stored and it has reverted back to displaying the default Monitored status and the selected Quality Profile for each respective series.

**Screenshots**
N/A

**Logs**
N/A

**System Information**

 - Sonarr Version: 3.0.3.899
 - Operating System: Ubuntu 18.04.4 LTS
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono JIT compiler version 6.10.0.104

**UI Bugs:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 78.0.2 64-bit

**Additional context**
None.

**Comment by markus101** [comment]
Are you using private browsing or clearing local storage when the browser closes? Sonarr relies on local storage to store that information between sessions.

**Comment by shabbosgoy** [comment]
That is correct, I am. So I suppose it's by design.
