### ISSUE TITLE
Somehow Sonarr deleted all series and episodes

### ISSUE THREAD

**Issue by astlaurent** [Sonarr/Sonarr#3873]
Hello

I faced a strange issue today and I am at a loss as what could have happened. I have been using Sonarr for years and never had any issues. I am running version 3.0.3.899 on windows 10. I recently lost my OS drive due to a drive crash. All my TV episodes were not affected and were on a different drive. I reinstalled Windows, Sonarr and restored the database backup. Everything seemed to be fine and flash forward several days and at 10 AM EST today some process happened and Sonarr went through and deleted every show and episode files. I looked through the log and cannot find any sign of why it happened just that it happened. Log attached. I see a lot of complaining about some failed downloads in the queue that cannot be imported and the fact it can't connect to deluge which is understandable since I have not reinstalled that yet. 

Any thought as to what would have caused something like this, any help is appreciated
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/4928787/sonarr.txt)
.

**Comment by Thirrian** [comment]
Is your instance accessible from the internet?

**Comment by markus101** [comment]
To build on what Thirrian asked, this sounds like Sonarr was open to the internet, someone discovered it and deleted all the series + files.

Info logs won't show the API request(s) made to delete the series, but that wouldn't change much, just show that it was deleted through the API in some way (the UI uses the API too).

We have https://github.com/Sonarr/Sonarr/issues/564 to warn the user / possibly provide a default authentication mechanism.

**Comment by astlaurent** [comment]
thank you. That is my thinking. I had it opened up so i could easily manage it from nzb360 but lesson learned and i need to lock my shit down better.

**Comment by astlaurent** [comment]
Now I officially feel like a dumbass. I recently reinstalled Sonarr and imported my DB due to a hard drive crash. I kinda assumed it would have imported my security/creds settings and it didn't. So basically it had no authentication and i didn't realize it. So FYI if you restore a DC it may not bring in your authentication settings.

**Comment by markus101** [comment]
The DB has the authentication credentials, but authentication itself is enabled in the configuration file (useful when you need to disable authentication to fix a forgotten password). If you restore the backup from the UI it should restore both files, otherwise you'll need to restore both or enable authentication in settings manually.
