### ISSUE TITLE
Toggle switch to automatically fail downloads that require human intervention

### ISSUE THREAD

**Issue by MotherTrucker** [Sonarr/Sonarr#3875]
The Problem - 

This is especially relevant when performing a massive database overhaul (Upgrading quality, downloading a bunch of new shows), basically when performing a database upgrade, I have to manually go through all the time and manually select all the downloads with errors (Yellow download symbol) and toggle Blacklist, and delete and re-search. This also happens from time to time with new episodes, albeit, not as big a deal, but sort of throws a wrench in the automation of the whole thing.

Solution - 

A toggle in the settings, in the same place as the Failed downloads settings, to automatically handle downloads that have errors as failed downloads (Blacklist, re-search). 

Additional Context - 

I realize that sometimes the error is a simple naming issue or something along those lines, but I find it so much easier to blacklist and search again, than to check the manual import, and actually inspect the file for corruption or other errors. Too often in the past I would manually import only for it to be the wrong episode, or have corruption in the data. Sonarr is right 99.9% of the time with it's errors in my experience, enough that I think it would be smart to allow it to fail said downloads and find a new one.

See my reddit post about this same issue for maybe more details:  [Here](https://www.reddit.com/r/sonarr/comments/hqubrl/setting_to_blacklist_and_attempt_a_new_search_in/)

**Comment by markus101** [comment]
As pointed out on Reddit you could deal with this via the API, but we don't have plans to add a setting to override this behaviour, at least at this time.
