### ISSUE TITLE
Season 2 being automatically imported as Season 1

### ISSUE THREAD

**Issue by 19wolf** [Sonarr/Sonarr#3876]
**Describe the bug**
Episodes of season 2 of "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka" are being imported as season 1

**Logs**
https://gist.github.com/19wolf/c3f845d16d4f38d939c3359c6bf40a31
highlight `20-7-18 11:55:50.1|Debug|ParsingService|Using absolute episode number 1 for: Is it Wrong to Try to Pick Up Girls in a Dungeon? - TVDB: 2x01`

**System Information**

Version
3.0.3.899
Package Version
3.0.3.899-ls31 by linuxserver.io
Mono Version
5.20.1.34

**Additional context**
Season 2 doesn't have absolute numbers on TVDB?

**Comment by markus101** [comment]
Please use the forums/subreddit for support. I don't see an import anywhere in that log, looks like it's a search/RSS being processed.

> Season 2 doesn't have absolute numbers on TVDB?

Skyhook has them, as does the XEM mapping (to map from the season 2 name + season absolute number to the cross-season absolute number that TVDB has)

**Comment by 19wolf** [comment]
I'm not sure I understand how this is a support issue and not a bug. I have a ton of logs so I'll have to dig through them to find it, but in the meantime I was able to get a screenshot of the wrong episode being imported.

https://www.dropbox.com/s/qigkrgxhorie09t/Screenshot%202020-07-19%2019.21.54.png?dl=0
https://www.dropbox.com/s/g67al1saavmd3pn/Screenshot%202020-07-19%2019.22.11.png?dl=0
