### ISSUE TITLE
Problem with mass edit in episode language

### ISSUE THREAD

**Issue by lebnet** [Sonarr/Sonarr#3877]
Hello,

already asked on reddit but no solution.

I wanted to upgrade my entire library using the menu Wanted > Cutoff unmet > search all but this feature has download episodes that I already have (the exact same files) when I tried to understand why, I found that I had activated the language upgrade

![image](https://user-images.githubusercontent.com/7726777/87873571-fa654280-c9c2-11ea-95f2-6d453ededebf.png)

and most of my episodes have the language tag "unknown"

![image](https://user-images.githubusercontent.com/7726777/87873576-05b86e00-c9c3-11ea-9ea8-490d570630cb.png)

So when I search all in cutoff unmet menu, all episodes are downloaded again. Example : 
![image](https://user-images.githubusercontent.com/7726777/87873579-0c46e580-c9c3-11ea-9603-0efda93cc4c1.png)

**System Information**
 - Sonarr Version: 3.0.3.899
 - Operating System: Docker on unraid
 -  mono Version: 5.20.1.34

**UI Bugs:**
 - OS: macOS
 - Browser: Firefox
 - Version: 78.0.2

In the "manage episodes" menu, all episodes are tagged french
![image](https://user-images.githubusercontent.com/7726777/87873586-254f9680-c9c3-11ea-9879-efaec55dd543.png)

but not in history season => "unknown"
![image](https://user-images.githubusercontent.com/7726777/87873590-2c76a480-c9c3-11ea-9fba-9431c7f34e7b.png)

**Bug description**
I thought I had found the solution by forcing French in the "manage episodes" menu but that doesn't change anything, when I search all in cutoff unmet menu, all episodes are downloaded again.

Do you have any suggestion to mass edit my actual libray with "french" language tag because i'm sur that my library is fully french because the forcing way doesn't work ?

**Comment by markus101** [comment]
Without debug logs it's impossible to say for certain, but it looks like Sonarr thought the existing files on disk were HDTV and upgraded the quality.

Post the relevant debug logs and we can take a look.

**Comment by lebnet** [comment]
I will try to reproduce and provide the logs. thank you

**Comment by markus101** [comment]
The events in history are wrong due to them not storing the language in some cases, see https://github.com/Sonarr/Sonarr/issues/3783

If more information on the re-downloading becomes available we can re-open this.
