### ISSUE TITLE
Files downloaded using transmission is not picked up if they contain ':'

### ISSUE THREAD

**Issue by lego290** [Sonarr/Sonarr#3880]
**Describe the bug**
Episode files downloaded using transmission which contain a ':', are not picked up by sonarr when finished, as transmission replaces ':' with '_', thus making sonarr report these as 'manual action required: file not found'.

Workaround:
Copy/link the downloaded file with the correct name, then manually perform the import.

**System Information**
 - Sonarr Version: 2.0.0.5344
 - Mono Version: 5.20.1.34
 - Operating System: ubuntu xenial

**Additional context**
Example: A episode file named 'Example: Episode 01.mp4' will be saved by transmission as 'Example_ Episode 01.mp4', but sonarr will only search for a file named 'Example: Episode 01.mp4', and thus be unable to find it.

**Comment by markus101** [comment]
Please post trace logs that show the list of torrents from transmission in the response, Sonarr relies on the torrent name to determine the path, if that's different (`:` being changed to `_`) then we'd need that information from transmission and trace logs will show what we have to work with.

**Comment by lego290** [comment]
The following are the lines in the log files i found relating to this download:
`20-7-25 20:47:20.8|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /data/download/complete/Sonarr/[DeadFish] Magi: Sinbad no Bouken (2016) - 08 [720p][AAC].mp4
20-7-25 20:47:20.9|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /data/download/complete/Sonarr/[DeadFish] Magi: Sinbad no Bouken (2016) - 05 [720p][AAC].mp4
20-7-25 20:48:50.8|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /data/download/complete/Sonarr/[DeadFish] Magi: Sinbad no Bouken (2016) - 08 [720p][AAC].mp4
20-7-25 20:48:50.9|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /data/download/complete/Sonarr/[DeadFish] Magi: Sinbad no Bouken (2016) - 05 [720p][AAC].mp4`

As there are approximately 2100 identical lines throughout the log files i have only included these.

When i manually searched and selected a similar download the following was written to the log file:
`20-7-26 19:51:17.5|Info|NzbSearchService|Searching 8 indexers for [Magi: Adventure of Sinbad : 04]
20-7-26 19:52:06.4|Info|DownloadDecisionMaker|Processing 5 releases
20-7-26 19:52:29.1|Info|DownloadService|Report sent to Transmission. [DeadFish] Magi: Sinbad no Bouken (2016) - 04 [720p][AAC].mp4`

The name of the download that appeared in transmission is: `[DeadFish] Magi: Sinbad no Bouken (2016) - 04 [720p][AAC].mp4` and has one file with the name: `[DeadFish] Magi_ Sinbad no Bouken (2016) - 01 [720p][AAC].mp4`

**Comment by ak2766** [comment]
**Easier to read repost from lego290 above**

The following are the lines in the log files i found relating to these downloads:
```
20-7-25 20:47:20.8|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /data/download/complete/Sonarr/[DeadFish] Magi: Sinbad no Bouken (2016) - 08 [720p][AAC].mp4
20-7-25 20:47:20.9|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /data/download/complete/Sonarr/[DeadFish] Magi: Sinbad no Bouken (2016) - 05 [720p][AAC].mp4
20-7-25 20:48:50.8|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /data/download/complete/Sonarr/[DeadFish] Magi: Sinbad no Bouken (2016) - 08 [720p][AAC].mp4
20-7-25 20:48:50.9|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /data/download/complete/Sonarr/[DeadFish] Magi: Sinbad no Bouken (2016) - 05 [720p][AAC].mp4
```

As there are approximately 2100 identical lines throughout the log files i have only included these.

When i manually searched and selected a similar download the following was written to the log file:
```
20-7-26 19:51:17.5|Info|NzbSearchService|Searching 8 indexers for [Magi: Adventure of Sinbad : 04]
20-7-26 19:52:06.4|Info|DownloadDecisionMaker|Processing 5 releases
20-7-26 19:52:29.1|Info|DownloadService|Report sent to Transmission. [DeadFish] Magi: Sinbad no Bouken (2016) - 04 [720p][AAC].mp4
```

The name of the download that appeared in transmission is:
```
[DeadFish] Magi: Sinbad no Bouken (2016) - 04 [720p][AAC].mp4
```
and has one file with the name:
```
[DeadFish] Magi_ Sinbad no Bouken (2016) - 04 [720p][AAC].mp4
```

**Comment by markus101** [comment]
We still need trace logs showing the response from Transmission to see if there is anything that will tell Sonarr where to look instead of guessing it matches the torrent name.
