### ISSUE TITLE
V3 once again not deleting episode folders on upgrade

### ISSUE THREAD

**Issue by fragande** [Sonarr/Sonarr#3883]
**Describe the bug**
When having separate episode folders, the episode folder is not deleted on upgrade despite having `Delete empty folders` checked. Only the video file inside the folder itself is removed.

**System Information**

 - Sonarr Version: 3.0.3.899
 - Operating System: Windows 10
 - .net Framework (Windows): 4.8.03752

**Additional context**
I reported this exact bug almost a year ago (v3.0.3.644) and it was fixed, but it seems to be back in one of the latest versions (not sure which one, I can't figure out how to downgrade to test). No permission errors in logs.

**Comment by markus101** [comment]
What do the debug logs show?

**Comment by markus101** [comment]
Based on the code and the last change I don't think this ever worked as expected.
