### ISSUE TITLE
Sonarr Web UI locking out after multiple tries to import episodes that already exist

### ISSUE THREAD

**Issue by ivtechboyinpa** [Sonarr/Sonarr#3884]
**Describe the bug**
After trying to import multiple files that already exist or Sonarr cannot get permissions to (I have encountered both cases) the web UI seems to lock up and stop responding. Sonarr continues to run without error - the logs don't show anything about not being able to access the web UI and continues to process **some** things, but not all. For example, the imports take a major slowdown hit, as a series I was trying to import got imported over the span of two days when left unattended after these errors.

Running `curl localhost:8989` on the box I'm running Sonarr on hangs indefinitely until I restart the service manually, in which case it responds with `curl: (56) Recv failure: Connection reset by peer`. In addition to that, looking at the Console using the dev tools in FireFox and Chrome shows that it's sending a constant SignalR: Reconnecting request to the backend, and no response is being sent.

**Logs**
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/4980091/sonarr.debug.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/4980092/sonarr.trace.txt)
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/4980093/sonarr.txt)

**System Information**

 - Sonarr Version: v3.0.3.904
 - Operating System: CentOS 7 x64
 - .net Framework (Windows) or mono (macOS/Linux) Version: 6.12.0.86

**Additional context**
I originally encountered this problem on v3.0.3.899. Upgraded to v3.0.3.904 and problem still present. Also tried the past three iterations of mono: 6.8, 6.10 and the current pre-release 6.12. I had hoped upgrading to the latest mono pre-release would fix the issue as it seemed mono-related, but that is not the case.

Edit: Also, clearing out NZBGet's history fixes the problem, but it tends to rear it's ugly head occasionally.

**Comment by markus101** [comment]
If the destination already exists, how did it end up there?
Did Sonarr fail to import it previously? What do the logs show for that original failed import?
Are these local volumes or network shares or cloud drives?

After that error it looks like it's still trying to import another file, but that import never completes before the logs end, does Sonarr keep running or is that it?

**Comment by markus101** [comment]
We can reopen when there is more info.
