### ISSUE TITLE
Upgrade episodes based on preferred Codec or Preferred Words

### ISSUE THREAD

**Issue by CryptoMaximalist** [Sonarr/Sonarr#3887]
**Describe the problem**
From what I can tell, Sonarr only considers Quality Profiles, Languages, and Propers as reasons to upgrade. Release Profiles are only considered during a search and not as a reason for Sonarr to upgrade. I'll use 265 as an example.  With x265 becoming popular and x266 announced recently, this seems like it will continue to be a core part of media management

If I set x265 to be preferred, but an x264 copy is grabbed first, sonarr will not upgrade to the x265 version even if it sees it in the RSS feed or a manual search.  This also means that upgrading a library from x264 to x265 is a bit manual and clumsy

**Describe any solutions you think might work**
1- Allow codec preferences to be designated by the user, similarly to Language preferences.  Then also like languages, incorporate the codec into the episode upgrade logic

or

2- Release Profiles (preferred words specifically) should be added in the logic Sonarr uses to consider if a release should be grabbed to update an existing episode.  

**Additional context**
I don't know if codecs or Release Profiles should take precedence over languages or Quality Profiles, but having them somewhere in the upgrade logic so upgrades are possible would be amazing

**Comment by markus101** [comment]
> Release Profiles are only considered during a search

No, they're always considered.

Preferred words in release profiles will upgrade to the same quality (even if the cutoff is met). Preferred words won't upgrade to a better quality if the cutoff is met, or that quality isn't wanted and it won't downgrade the quality. The same rules apply for lanuage.
