### ISSUE TITLE
Make maximum filename length configurable or autodetect it

### ISSUE THREAD

**Issue by eikowagenknecht** [Sonarr/Sonarr#3888]
**Describe the problem**
I'm using sonarr on an encrypted Synology Diskstation volume. The maximum filename length (not path + filename) there is for technical reasons 143 characters.

Sonarr doesn't recognize this and thus often fails renaming longer episodes.

**Describe any solutions you think might work**
A solution would be either to make the max filename length user settable (advanced setting of course, default 255).
Alternatively it could be automatically detected by trying to write files with various length and seeing which succeed for example. This could also be triggered manually.

**Comment by markus101** [comment]
Is each segment limited to 143 characters? Or just the filename?
Does the 143 characters include the extension?
Are there limits on the total length of the path + filename?

**Comment by eikowagenknecht** [comment]
It is 143 characters for each segment, either directory or filename including expansion. There is as far as I know no limit for total length or at least it is so big that I have never encountered it yet.

So this is ok:
/143CharactersLongPath/143CharactersLongPath/143CharactersLongFilenameIncludingExtension

It is a limitation of the eCryptFS filesystem that is used by Sonology. More background [here](https://www.reddit.com/r/synology/comments/5xtmoa/how_do_you_deal_with_the_filename_limit_when_you/):

> The filename length problem comes because Synology has (correctly imho) decided to encrypt filenames as well as file contents. When any plain text is run through a decent encryption algorhythm the output is indistinguishable from a random bitstream and this is what happens to the filenames. Unfortunately a random bitstream that would randomly select characters from whatever language table you are using is not good for the underlying filesystem, so ecryptfs pushes the filename through uuencode to convert bytes from base256 to base64. This means each character space now only encodes 6 bits rather than 8 so the filename has to have more characters. ecryptfs also includes a prefix of ECRYPTFS_ which makes it easy to spot an ecryptfs when a sysadmin (or anyone I suppose) is trying to work out what is on a disk. The unfortunate downside of all of this is the filename length expansion.

**Comment by thezoggy** [comment]
cant change your path to just reduce the likelyhood of this happening? also 143 seems a bit short?

**Comment by eikowagenknecht** [comment]
Yes, of course, I already removed the series title from the filename for example. But for some episodes it is still happening, especially for files containing multiple episodes.

I can't really comment on the "143 seems a bit short" part, it is a technical limitation by eCryptFS / Synology. An official statement from a maintainer of eCryptFS can be found here: https://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs

**Comment by Taloth** [comment]
Encoding it with base-64 is kinda silly though, there are plenty of encoding schemes that are vastly more efficient. And they should've stored longer filenames in xattr or anything else that would deal with it transparently.

I'm not opposed to see if we can deal with it somehow on our end, but it's not a priority.

PS: If you're not dead set on using name encryption, you can actually just disable it.
