### ISSUE TITLE
Episode number column not wide enough for 2 warnings + episode no

### ISSUE THREAD

**Issue by danshilm** [Sonarr/Sonarr#3890]
**Describe the bug**
The episode number column in the page of a series is too narrow when there are 2 warnings. It's 65px afaik and increasing it to 80 seems to make it collapse back to the height of 1 row. It does seem a bit too wide now though...

**Screenshots**
This is as-is.
![Screenshot_84](https://user-images.githubusercontent.com/20923978/88930975-49498c80-d28d-11ea-9a62-cea2d259c68e.png)

This is with 80px.
![Screenshot_85](https://user-images.githubusercontent.com/20923978/88931001-52d2f480-d28d-11ea-8b94-9829e4e95bca.png)

**Logs**
Not applicable?

**System Information**
 - Sonarr Version: 3.0.3.904
 - Operating System: Ubuntu 
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34

**UI Bugs:**
 - OS: Windows
 - Browser: Firefox
 - Version: 79.0b9

**Comment by thezoggy** [comment]
better solution would to aggregate all warnings to the one icon's tooltip

**Comment by danshilm** [comment]
Unsure if I should post this here or make another issue.
Absolute episode numbers are here now and the column spills over again. 
Screenshot:
![Screenshot_86](https://user-images.githubusercontent.com/20923978/89134001-4ae7ae80-d532-11ea-858d-6d0abe1c2c5a.png)

Thank you for the quick fix in the first place @markus101.
