### ISSUE TITLE
Show/Season Searches should do Episode Searches if high quality Season Packs aren't found

### ISSUE THREAD

**Issue by lightmaster** [Sonarr/Sonarr#3891]
**Describe the problem**
Clicking to automatic search a monitored show preforms a season search for each monitored season, returning only the first 100 results. ie: Show Search for Rick and Morty while only Season 4 is monitored will call a similar API for each index setup `http://localhost:9117/api/v2.0/indexers/ettv/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Rick%20et%20Morty&season=4`. In this case, you wind up with a number of lists of 100 results, that may or may not contain the results you'd expect. Sonarr then proceeds to download the best matches for each episodes it can from these handful of 100 result lists

**Describe any solutions you think might work**
I propose that clicking the Show Search button first preforms a search for Season Packs and if a suitable one isn't found based on quality profile and preferred words, then Sonarr preforms Episode Searches for each episode instead.

ie:
* Quality profile is set to 2160p and 1080p and preferred words give a high score for the words 265, HDR, and 10bit.
* If a Season Pack is found that is 2160p and gives highest score, download it.
* If not, then do an episode search for each episode. Grab 2160p quality episodes with highest score.
* If some episodes from Episode Search have 2160p and some do not, grab each episode prioritizing Quality, then Preferred Words score, then available seeds.
* If no 2160p episodes from Episode Search exist, grab highest score 1080p Season Pack.
* If no 1080p Season Packs, grab each episode from Episode Search prioritizing Quality, then Preferred Words, then seeds.

**Additional context**
This requests spawns from [Automatic Search grabbing wrong quality episode](https://www.reddit.com/r/sonarrv3/comments/i0i02n/automatic_search_grabbing_wrong_quality_episode/), where Sonarr is grabbing a mix of 1080p and 2160p episodes for Rick and Morty when I do a Show or Season Search, but correctly grabs all 2160p episodes when I do a episode search for each episode in Season 4.

**Comment by Taloth** [comment]
> In this case, you wind up with a number of lists of 100 results, that may or may not contain the results you'd expect. Sonarr then proceeds to download the best matches for each episodes it can from these handful of 100 result lists

No, if the indexer returns 100 results then Sonarr will proceed to query `&offset=100&limit=100` to get the next page. It's up to your indexer to implement paging properly.
Debug/Trace logs will show that behavior and should allow you to check whether Jackett returns the results properly.

If you require further support, please open a topic on the forums instead.

Note that the `&season=4` query parameter implies both season packs and individual episodes in that season. We've no plans to query episodes individually in that scenario.
