### ISSUE TITLE
Changing root folder in Mass Editor while Refresh Series is running doesn't work

### ISSUE THREAD

**Issue by onedr0p** [Sonarr/Sonarr#3892]
**Describe the bug**
I am trying to change the root folder while the series refresh task is running, and the refresh series is just changing the path to what it was originally.

**Screenshots**
See GIF

https://imgur.com/IFNioVw

**System Information**

 - Sonarr Version: 3.0.3.904
 - Operating System: LinuxServerIO/Docker Image

**UI Bugs:**
 - OS: Mac
 - Browser: Chrome
 - Version: 84.0.4147.105

**Additional context**
A fix for me would be to add and initial delay (maybe like 10 minutes?) on start up to the Refresh Series task but it doesn't solve the real problem.

**Comment by markus101** [comment]
> A fix for me would be to add and initial delay (maybe like 10 minutes?) on start up to the Refresh Series task but it doesn't solve the real problem.

You could also not edit the series while refreshing, neither are fixes, both are bandaids.

**Comment by onedr0p** [comment]
Thanks for the fix, I know I could wait but I have a lot of series. The problem is I was migrating data to a new location, Sonarr was off for a couple days while I migrated my data. Once I started it back up the scan would kick in.
