### ISSUE TITLE
sonarr suboptimal handling of rejecting releases / retrying

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#3893]
**Describe the bug**
Sonarr re-downloading and rejecting the same episode 10+ times due to "Swedish" in episode title.

**Screenshots**
![img](http://zoggy.net/firefox_2020-08-02_02-28-57.png)
![img2](http://zoggy.net/firefox_2020-08-02_02-32-00.png)
**Logs**
Logs rolled :(

**System Information**

 - Sonarr Version: 3.0.3.904
 - Operating System: Windows 10

**Comment by markus101** [comment]
Covered by https://github.com/Sonarr/Sonarr/issues/861

**Comment by thezoggy** [comment]
yes, this would be a dupe if it would have just stopped and i had to manual import. this however is a new bug.. where that did not happen. but instead it then goes and tried to re-download the same release and then deleted over and over 10 times.
