### ISSUE TITLE
Creating a webhook by tv show added/modified/change/imported event to other opensource projects

### ISSUE THREAD

**Issue by PotatoQuality** [Sonarr/Sonarr#3895]
**Describe the problem**
A clear and concise description of the problem you're looking to solve.

Multiple opensource projects such as Bazarr and Ombi are running scheduled api calls to make sure there are up to date with the lasted status of Sonarr. It will be very great if the Devs can work together and making a webhook interface to make sure the scheduled api calls are not needed anymore and having a -almost- realtime interface.

**Describe any solutions you think might work**
A clear and concise description of any solutions or features you've considered.

Creating a realtime interface with webhook calls by tv show added/modified/change and imported event

**Additional context**

Example: https://bazarr.featureupvote.com/suggestions/57454/support-plex-webhooks-to-enable-immediate-searches-for-recently-added-recently-w

**Comment by markus101** [comment]
Sonarr already supports webhooks for import events.

Everything Sonarr does is published for consumption by the UI via signalR, signalR isn't limited to the UI, anything could utilize that, it'd just have to subscribe.

At this time we don't have plans for adding webhooks for every series/episode related event.
