### ISSUE TITLE
Coronation Street Episode Name AND Daily Details conflict and never gets grabbed.

### ISSUE THREAD

**Issue by Pantar2205** [Sonarr/Sonarr#3897]
**Describe the bug**
Show Name = Coronation Street
On almost all sites, this show will be listed showing both episode details but also daily date details. Manually the show can be found all the time, but automatically it will always be rejected because if set as standard will reject because of daily details, if show set as daily show, will be rejected because of episode details. Meaning the correct show is always found, but never grabbed. Its the only show I have found with this issue.

Is there anyway to force a daily show to ignore episode details or the exact opposite.

**Comment by markus101** [comment]
You’ve left out most of the required information for a bug. Please use the complete template, including debug logs at a minimum.

**Comment by Pantar2205** [comment]
There is a new episode tonight. I will just hang on until then and get the logs from that + screenshots etc.

#381 seems to be a different issue just from reading its description. this issue is from a show that is usually always listed and named as **both** a standard **and** daily show, therefore being **not** grabbed at all when selected as either a standard show or selected as a daily show. From the logs I have perused through so far, it just says that it couldn't find anything.

To illustrate
Add show as standard
search for show
results would be found with names like
Coronation Street S61E120 720p 03-08-2020
this will be rejected because it has timestamp and is a daily show


Add show as daily
search for show
results would be found with names like
Coronation Street S61E120 720p 03-08-2020
this will be rejected because it has episode details and it is a standard show

The logs will show the search for coronation street just finding nothing. Ill hang on until after tonight's episode and get "fresh" logs and screenshots of exactly what I am experiencing.

**Comment by markus101** [comment]
You're still missing all version and OS info for a bug.

In v3 that title correctly parses to: `Coronation Street S61E120`, if it parsed using a date it'd fail to find the series because the series title would also include the season + episode info and the resolution.

**Comment by Pantar2205** [comment]
Thank you for your help markus101 and sorry for the sloppy report. 
it looks like v3 this is fixed.
i am very sorry for wasting your time. thank you so much for your help.
