### ISSUE TITLE
Inconsistent Renaming for WEBRip Episodes

### ISSUE THREAD

**Issue by z4rqu0n42** [Sonarr/Sonarr#3898]
**Describe the bug**

_Settings > Media Management > Episode Naming_

Reaming a WEBRip Episode leads to an inconsistent result.

Choosing {Quality.Full} for the epsisode format (dot as separator) leads to an output of "WEBRip-720p" (or "WebRip-1080p" etc.) instead of the expected "720p.WEBRip". The elements are reversed and separated with a dash instead the selected dot.

Opposed to this WEBDL and Bluray releases are renamed correctly (e.g. "720p.WEBDL").

This behaviour seems to have been introduced in a release a couple of months ago. 
Before that it worked as expected.

**System Information**

 - Sonarr Version: 3.0.3.906
 - Operating System: Win 10 1909 x64
 - .net Framework 4.8.03752

**Comment by markus101** [comment]
You can change that by changing the title in Quality settings.
