### ISSUE TITLE
V3: deleted series with active downloads -> System.ApplicationException

### ISSUE THREAD

**Issue by dankots** [Sonarr/Sonarr#3904]
**Describe the bug**
There was an active download for a season, that was the only download in progress.
I deleted the series, and selected to clean up files.

**Screenshots**

**Logs**
relevant logs attached
[logs.txt](https://github.com/Sonarr/Sonarr/files/5037709/logs.txt)

**System Information**

 - Sonarr Version: 3.0.3.906
 - Operating System: Ubuntu 20.04.1 LTS
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]
ummm: docker container:     image: linuxserver/sonarr:preview

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
Due to the queue items still being linked to those episodes.

Did it lead to any errors in the UI?
Does it repeat every minute or two or was it just that one error?

**Comment by dankots** [comment]
The activity tab showed some error in the GUI in the frame of the list of things. I think I clicked away and back 3 times, so that's why the error was in the logs 3 times.
after stoping and starting sonarr, the error in the GUI is gone, and it showed the 1 active entry because it saw that in the download client directory I guess. 
it's been fine since.

**Comment by markus101** [comment]
Thanks for the info, this is the same issue as https://github.com/Sonarr/Sonarr/issues/3565
