### ISSUE TITLE
Can't connect to indexer drunkenslug

### ISSUE THREAD

**Issue by TheRealLouCipher** [Sonarr/Sonarr#3905]
**Describe the bug**
Sonarr fails to connect to indexer drunkenslug

**Screenshots**
N/A

**Logs**
[drunkenslug.txt](https://github.com/Sonarr/Sonarr/files/5051525/drunkenslug.txt)

**System Information**

 - Sonarr Version: 3.0.3.906
 - Operating System: Debian 10, docker package 3.0.3.906-ls36 by linuxserver.io
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34

**UI Bugs:**
N/A

**Additional context**
When visiting drunkenslug.com and logging in via browser you are now greeted with cloudflare ddos captcha.

**Comment by markus101** [comment]
Please use the forums/subreddit for support, though in this case you need to talk with DS to see why you're getting hit with a captcha, if you're using a VPN/proxy try turning that off as well.

**Comment by TheRealLouCipher** [comment]
You're right. DS support provided the solution. Thanks for the pointer!
