### ISSUE TITLE
Update Trakt Collection

### ISSUE THREAD

**Issue by geogolem** [Sonarr/Sonarr#3906]
**Describe the problem**
Trakt Collection could be kept up to date by Sonarr. A similar feature is being implemented in radarr

**Describe any solutions you think might work**
Please refer to the Radarr issue/solution here: 
https://github.com/Radarr/Radarr/issues/4521
https://github.com/Radarr/Radarr/issues/4838

It would be nice to be able to add to the trakt collection on download/import and remove from the trakt collection on deletion.

A script could be used for the initial setup of the Trakt Collection - the script could eventually be integrated into Sonarr/Radarr but is less of a priority then implementing the connections to keep the Collection in sync.

**Comment by rg9400** [comment]
I wrote a script that, using Sonarr's data and API, bulk adds all downloaded episodes to Trakt. A lot of this is baked into the Radarr PR, but I can help with any mapping if needed. Trakt is expecting a payload like below

```
   shows: {
        "title": title,
        "year": year,
        "ids": {
            "imdb": imdb_id,
            "tvdb": tvdb_id
        },
        "seasons": [
            "number": season_number,
            "episodes": [
                "number": episode_number,
                "collected_at": date_added,
                "media_type": media_type,
                "resolution": resolution,
                "audio": audio,
                "audio_channels": audio_channels
            ]
        ]    
    }
```

`media_type` can be mapped like below
```python
        source = episode_file['quality']['quality']['source']
        source_mapping = {
            "web":"digital",
            "webRip":"digital",
            "blurayRaw":"bluray",
            "bluray":"bluray",
            "television":"dvd",
            "televisionRaw":"dvd",
            "dvd":"dvd"
            }
        media_type = source_mapping.get(source, None)
```
`resolution` can be mapped as below

```python
        sonarr_resolution = episode_file['quality']['quality']['resolution']
        scan_type = episode_file['mediaInfo']['scanType']
        resolution_mapping = {
            2160:"uhd_4k",
            1080:"hd_1080",
            720:"hd_720p",
            480:"sd_480",
            576:"sd_576"
            }
        resolution = resolution_mapping.get(sonarr_resolution, None)
        if resolution in ["hd_1080", "sd_480", "sd_576"]:
            if scan_type in ['Interlaced', 'MBAFF', 'PAFF']:
                resolution = '{}i'.format(resolution)
            else:
                resolution = '{}p'.format(resolution)
```
`audio` can be mapped as below

```python
        audio_codec = episode_file['mediaInfo']['audioCodec']
        audio_mapping = {
            "AC3":"dolby_digital",
            "EAC3":"dolby_digital_plus",
            "TrueHD":"dolby_truehd",
            "EAC3 Atmos":"dolby_atmos",
            "TrueHD Atmos":"dolby_atmos",
            "DTS":"dts",
            "DTS-ES":"dts",
            "DTS-HD MA":"dts_ma",
            "DTS-HD HRA":"dts_hr",
            "DTS-X":"dts_x",
            "MP3":"mp3",
            "MP2":"mp3",
            "Vorbis":"ogg",
            "WMA":"wma",
            "AAC":"aac",
            "PCM":"lpcm",
            "FLAC":"flac",
            "Opus":"ogg"
            }
        audio = audio_mapping.get(audio_codec, None)
```

`audio_channels` can be mapped as below

```python
        audio_channel_count = episode_file['mediaInfo']['audioChannels']
        channel_mapping = str(audio_channel_count)
        audio_channels = channel_mapping
        #Below is when DTS-X is used and MediaInfo does not give object counts
        if audio_channel_count == 8.0:
            audio_channels = "7.1"
        #Below incorrect count can sometimes be 6.1 for DTS-HR tracks, but the vast majority of time, it is for 7.1 tracks
        #It happens when channels_original and channels differ. Out of 17 such cases, only 3 were actually 6.1, rest were 7.1
        elif audio_channel_count == 6.0 and audio == "dts_ma":
            audio_channels = "7.1"
        elif audio_channel_count == 6.0 and audio != "dts_ma":
            audio_channels = "6.1"
        #Not sure why this happens, but I noticed a few older 1.0 PCM tracks coming as 0.0 channel count in Radarr
        elif audio_channel_count == 0.0:
            audio_channels = "1.0"
```

The above results in accurate mapping of almost 35k episodes as well as all the relevant MediaInfo fields. Only a few cases where Trakt's episode counts mismatched with Sonarr/TVDB resulted in issues.

**Comment by rg9400** [comment]
This connection was pushed into Radarr and is working super well. 

See the commit here
https://github.com/Radarr/Radarr/commit/00f631c623e08699ed1c8dbb7e5566a1ab5c4152

Until Sonarr ports this over, users can use this custom post-processing Python script which uses very similar logic. I also have a one-time sync script available for both Sonarr/Radarr. Unfortunately, since I didn't want to handle oAuth, the scripts all assume you already have a bearer token or can do it separately


[sonarr_trakt_connection.zip](https://github.com/Sonarr/Sonarr/files/5079081/sonarr_trakt_connection.zip)
