### ISSUE TITLE
Rebuilt server will not show my TV Shows after Importing from Disk.

### ISSUE THREAD

**Issue by ak2766** [Sonarr/Sonarr#3907]
**Describe the bug**
I've rebuilt my media server over the weekend after the OS drive died.  I've deployed Sonarr as detailed at [Linuxserver.io](https://docs.linuxserver.io/images/docker-sonarr).  I've then imported my TV Shows by clicking `Add Series` and selecting `Import Existing Series On Disk` and let it run overnight to import the shows. In the morning, I was expecting to find the homepage as it was prior to disk failure, but I was instead met by the same welcome screen as just after first run.

**Screenshots**
Welcome screen:
![Selection_00699](https://user-images.githubusercontent.com/6629646/89846705-4f146b80-dbc5-11ea-8c44-8470ea2a4e27.png)
Importing TV Shows:
![Selection_00700](https://user-images.githubusercontent.com/6629646/89846808-9c90d880-dbc5-11ea-9801-3fa00d629930.png)
Back to main screen:
![Selection_00702](https://user-images.githubusercontent.com/6629646/89846871-bcc09780-dbc5-11ea-9981-27e1acda52b0.png)
System Screen:
![Selection_00703](https://user-images.githubusercontent.com/6629646/89846912-d661df00-dbc5-11ea-94eb-a0c60fdf703b.png)

**Logs**
Here's the [log file](https://pastebin.com/sw4NG2Cy).

**System Information**

 - Sonarr Version: `2.0.0.5344`
 - Operating System: `Ubuntu 18.04.4 LTS`
 - .net Framework (Windows) or mono (macOS/Linux) Version: `Mono JIT compiler version 5.20.1.34 (tarball Tue Jul 16 22:52:32 UTC 2019)`

**UI Bugs:**
 - OS: `Ubuntu 20.04.1 LTS`
 - Browser: `Firefox`
 - Version: `79.0`

**Additional context**
In the log file, I see lots of missing `.css` and `.js` files - I'm wondering if the docker deployment instructions are incorrect.  But prior to the disk failure, my environment was similar - only difference being that when I initially deployed, it was 2 years ago and hence using an older `docker image` and ultimately an older version of **Sonarr**.

**Comment by markus101** [comment]
Please use the forums/subreddit for support, if you're still having issues, open a thread there.

You have to click add for each one you want to add, they're not added automatically, it looks like you didn't do that.

**Comment by ak2766** [comment]
Please excuse my ignorance - I have no idea what/where forums/subreddit is.  Can you please provide a link?

It might also be a good idea to mention this when one is raising a ticket here.

**Comment by ak2766** [comment]
So, went hunting as I appear to not be getting any progress here and the [solution to this problem](https://www.reddit.com/r/sonarr/comments/5pfy6z/sonarr_importing_existing_series_some_work_some/) is just staggering:
1. Move all TV Shows to a different folder
2. Add all TV shows manually one by one (_god help you if you have more than a handful_)
3. Manually import from where you moved them in step 1

Lucky me - I only have 77 shows to do this for - :(

If **Import Existing Series From Disk** is supposed to do this automatically for me, then I'm flummoxed as to why this issue was closed so quickly without even a reference to an existing/duplicate bug???

I guess beggars don't always get what they want...

**Comment by markus101** [comment]
> Please excuse my ignorance - I have no idea what/where forums/subreddit is. Can you please provide a link?

It might also be a good idea to mention this when one is raising a ticket here.

There is a link directly from Sonarr, you can see it in your last screenshot.

> So, went hunting as I appear to not be getting any progress here and the solution to this problem is just staggering:

Based on your screenshot you didn't even get the same issue that user did, you just need to click add.

> If Import Existing Series From Disk is supposed to do this automatically for me, then I'm flummoxed as to why this issue was closed so quickly without even a reference to an existing/duplicate bug???

Besides searching for each series (for each folder it finds in the root folder) it doesn't do anything automatically, once the results are returned (or start coming back you need to click add for each series), there is no existing issue to link to, it's not a bug.

**Comment by ak2766** [comment]
@markus101 - You have to excuse us end users - we are not very good at reading.  Even for someone like me who is technically clued, when the end user hat comes on, the brain goes to rest - :(.  So, apologies for letting my frustration bleed though - I've done this several times and I'm getting nowhere fast.

I'll keep trying and maybe finally I'll understand how it all works.
