### ISSUE TITLE
Season images missing from metadata

### ISSUE THREAD

**Issue by desigi** [Sonarr/Sonarr#3908]
**Describe the bug**
In the metadata settings the series, season, and episode images are enabled under Kodi (XBMC).
When the series is refreshed only the series images and episode images are downloaded. No season images are downloaded.
There doesn’t appear to be any season image check at all in the logs.

**Logs**
[debug](https://www.dropbox.com/s/vzi4mu5u25tkoj1/debug.txt?dl=0)
[trace](https://www.dropbox.com/s/kfygc1w73wm2ax5/trace.txt?dl=0)

**System Information**
 - Sonarr Version: 3.0.3.906 (package version: 3.0.3.906-ls36 by linuxserver.io)
 - Operating System: Ubuntu 18.04
 - mono(Linux) Version: 5.20.1.34

**Comment by markus101** [comment]
This was due to an API change on TVDB's side, fixed now.

**Comment by desigi** [comment]
Thank you!
