### ISSUE TITLE
Incorrect episode names imported from 3rd party

### ISSUE THREAD

**Issue by agilob** [Sonarr/Sonarr#3909]
**Describe the bug**
A few months ago some series started getting incorrect episode names. Instead full episode title Sonarr wants to rename episodes to "Episode 201" "Episode 200" etc. The new name scheme applies to old episodes where title has been correct (back in ~May) and to newly added episodes. 

![image](https://user-images.githubusercontent.com/2544251/89951705-6a11ca80-dc1b-11ea-8711-d04ac1d81ee8.png)

I think it's the 3rd party API is providing incorrect details and Sonarr trusts it too much. Sonarr recognises the series in  `Trakt The TVDB IMDB TV Maze` but uses only the first one to pull episode info.

Can I change somewhere source of 3rd party info for the series, or can you suggest different solution?

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: docker - linuxserver.io

**Comment by markus101** [comment]
Sonarr gets series information from The TVDB (through our proxy SKyhook, we haven't used trakt in years.

You cannot change the source, but as long as the series is unlocked you can edit it on TheTVDB and Sonarr will show updates after 24+ hours (TVDB caches for 24 hours).
