### ISSUE TITLE
Manual import does not take user episode remapping into account

### ISSUE THREAD

**Issue by sephrat** [Sonarr/Sonarr#3910]
**Describe the bug**
My series episodes order is messed up when mapped automatically by Sonarr so I go with a manual import to remap the episodes. For the record, this is because "ParsingService|Using Scene to TVDB Mapping" is triggered but my episodes order was already correctly mapped.
All episodes are mapped using the automatically determined (wrong) order despite the changes I made in the list.
For instance, Sonarr initially maps the following:
`From   | To`
`S02E05 | S02E09`
`S02E07 | S02E10`
`S02E09 | S02E13`
`S02E10 | S02E15`
I go and fix S02E09 > S02E09 and S02E10 > S02E10 and unselect the first two lines. 
After import, S02E05 is mapped to S02E10, and S02E07 to S02E10.
I also receive 2 notifications for each file.
I tried to map S02E05 and S02E07 to other files so there is no conflict. Strangely enough, that did the trick for S02E09 but S02E10 is still mapped a hardlink from S02E07.

**Screenshots**
Initial mapping by Sonarr:
![image](https://user-images.githubusercontent.com/34862846/89978204-3fe8f880-dc6d-11ea-801c-5fc7da7a9176.png)

Modified mapping:
![image](https://user-images.githubusercontent.com/34862846/89978197-3790bd80-dc6d-11ea-9e79-de86084e8254.png)

Notifications:
![image](https://user-images.githubusercontent.com/34862846/89979032-14670d80-dc6f-11ea-804f-544e6aaa6f7d.png)

**Logs**
https://pastebin.com/955EQ9g5
From what I understand, Sonarr will hardlink both files to the same target.

> 20-8-12 07:44:39.3|Debug|DiskTransferService|HardLinkOrCopy
> [/media/Downloads/Torrents/Sonarr/Futurama.S02.1080p.WEB.h264-NiXON[rartv]/Futurama.S02E09.1080p.WEB.h264-NiXON.mkv] > [/media/SÃ©ries/Futurama/Season 2/Futurama - S02E09 - Why Must I Be a Crustacean in Love.mkv]
> 20-8-12 07:44:40.2|Debug|DiskTransferService|HardLinkOrCopy [/media/Downloads/Torrents/Sonarr/Futurama.S02.1080p.WEB.h264-NiXON[rartv]/Futurama.S02E10.1080p.WEB.h264-NiXON.mkv] > [/media/SÃ©ries/Futurama/Season 2/Futurama - S02E10 - Put Your Head on My Shoulder.mkv]
> 20-8-12 07:44:46.0|Debug|DiskTransferService|HardLinkOrCopy [/media/Downloads/Torrents/Sonarr/Futurama.S02.1080p.WEB.h264-NiXON[rartv]/Futurama.S02E05.1080p.WEB.h264-NiXON.mkv] > [/media/SÃ©ries/Futurama/Season 2/Futurama - S02E09 - Why Must I Be a Crustacean in Love.mkv]
> 20-8-12 07:44:46.4|Debug|DiskTransferService|HardLinkOrCopy [/media/Downloads/Torrents/Sonarr/Futurama.S02.1080p.WEB.h264-NiXON[rartv]/Futurama.S02E07.1080p.WEB.h264-NiXON.mkv] > [/media/SÃ©ries/Futurama/Season 2/Futurama - S02E10 - Put Your Head on My Shoulder.mkv]

**System Information**

 - Sonarr Version: 3.0.3.907
 - Operating System: Ubuntu / Docker
 - mono Version: 5.20.1.34

**Comment by markus101** [comment]
> 20-8-12 07:44:39.3|Debug|DiskTransferService|HardLinkOrCopy
[/media/Downloads/Torrents/Sonarr/Futurama.S02.1080p.WEB.h264-NiXON[rartv]/Futurama.S02E09.1080p.WEB.h264-NiXON.mkv] > [/media/SÃ©ries/Futurama/Season 2/Futurama - S02E09 - Why Must I Be a Crustacean in Love.mkv]
20-8-12 07:44:40.2|Debug|DiskTransferService|HardLinkOrCopy [/media/Downloads/Torrents/Sonarr/Futurama.S02.1080p.WEB.h264-NiXON[rartv]/Futurama.S02E10.1080p.WEB.h264-NiXON.mkv] > [/media/SÃ©ries/Futurama/Season 2/Futurama - S02E10 - Put Your Head on My Shoulder.mkv]

Looks like it used them, but then you also imported other files which were mapped to those same episodes:

> [/media/SÃ©ries/Futurama/Season 2/Futurama - S02E09 - Why Must I Be a Crustacean in Love.mkv]
20-8-12 07:44:46.4|Debug|DiskTransferService|HardLinkOrCopy [/media/Downloads/Torrents/Sonarr/Futurama.S02.1080p.WEB.h264-NiXON[rartv]/Futurama.S02E07.1080p.WEB.h264-NiXON.mkv] > [/media/SÃ©ries/Futurama/Season 2/Futurama - S02E10 - Put Your Head on My Shoulder.mkv]

That explains why you think it ignored the mapping and why you got two notifications.

Best guess Sonarr auto imported around the same time you manually imported and it messed it up, unless you manually imported a second time.

**Comment by sephrat** [comment]
Mmmmh I tested a bit more and it seems you were on a good lead.
I've tried manually importing at least 5 times already and the behaviour is consistent. Plus the timestamp is pretty much the same between the two conflicting mappings. 
Looks like when I manually import the episodes, the queue is also triggered and overwrites the files I manually imported. This also could explain the rare times where some episodes (usually the first one) was mapped fine when the others were not: manual import and queue are on a time race.
The queue was not cleared because I tried to import only a few episodes from a season pack, hence the consistent behavior.

My work around was to clear the queue and manual import again.

I'm not sure the queue/manual import conflict should be addressed so I'll leave the issue open. Feel free to close it.

**Comment by markus101** [comment]
While the manual import is happening the import job won't run, so as long as everything is imported it shouldn't behave this way, if you're cherry picking certain files to import you're going to see odd behaviour, but there isn't a way to prevent that without reverting to the behaviour of 1 episode imported treats everything as imported.
