### ISSUE TITLE
Wrong anime alias makes search results irrelevant and doesn't exist on the xem

### ISSUE THREAD

**Issue by enchained** [Sonarr/Sonarr#3912]
**Describe the bug**
Series: Re:ZERO -Starting Life in Another World-
Series type: Anime

I did a "refresh and scan" of the series beforehand. When I hover on the title (squares icon), it says "Alternate Titles: Judas".

Judas is an anime release group, not sure where it was taken from, but looks like it's not xem: http://thexem.de/xem/show/2992

And of course, with this the interactive search results are mostly irrelevant now.

Here is an example of the show where sonarr gets aliases right for me http://thexem.de/xem/show/4954
Looks like it's about naming the field "Season 1" vs "Alias". I already reported the issue on the xem IRC, however, possibly it would be better if sonarr caught things labeled "Season 1" for Alias too?

**Logs**
Trace log right before series refresh and scan: https://drive.google.com/file/d/1zydportbZ7mzh3hnJThY2n63QoTC7eI3/view?usp=sharing
Later found this link in logs: http://thexem.de/map/allNames?seasonNumbers=True&origin=tvdb Found no "Judas" there. And also, no difference between Re:Zero and SNAFU S1 - both labeled by "1" there.

**System Information**

 - Sonarr Version: 3.0.3.907
 - Operating System: docker 3.0.3.907-ls37 by linuxserver.io
 - mono Version: 5.20.1.34

**Comment by markus101** [comment]
Removed, should be reflected if you refresh the series in about an hour.

**Comment by enchained** [comment]
Thanks, that was fast! May I ask what could have caused that?

**Comment by markus101** [comment]
Somebody filled out a request for an alias on the google form (see the FAQ) which shouldn't include anime and it was noticed when it was added that it was anime and completely wrong.

I'm going to go with people are stupid (including myself) on this one.
