### ISSUE TITLE
Episodes keeps downloading but quality requirements already met

### ISSUE THREAD

**Issue by damousys** [Sonarr/Sonarr#3913]
Episodes keeps downloading but quality requirements already met
Show has requirement to be "SDTV" but get's upgrade to BlueRay 1080P
Show has requirement to be upgraded until Dutch language, but upgrade is from EN to EN 

Bug started when I enabled Upgrade until Dutch language in Language profile.
![image](https://user-images.githubusercontent.com/7858454/90136916-292dc900-dd75-11ea-849f-274cf900a37d.png)

![image](https://user-images.githubusercontent.com/7858454/90136821-0e5b5480-dd75-11ea-83b9-b6429845e006.png)

**Logs**
Don't know which logs to get

**System Information**

 - Sonarr Version: 3.0.3.907
 - Operating System: Windows 2019 Server
 - .net Frameworks 4.8

**Comment by markus101** [comment]
You need to enable debug logging and upload those, the wiki has information on how to do that.

**Comment by damousys** [comment]
Oke here are the log files
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/5069770/sonarr.txt)
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/5069771/sonarr.debug.txt)

**Comment by markus101** [comment]
Thanks for the logs.

Snippet for presevation:

```
20-8-13 16:35:22.3|Debug|QualityParser|Trying to parse quality for Alias.S03E08.720p.WEB.h264-NiXON
20-8-13 16:35:22.3|Debug|Parser|Quality parsed: WEBDL-720p v1
20-8-13 16:35:22.3|Debug|Parser|Release Group parsed: NiXON
20-8-13 16:35:22.3|Debug|AcceptableSizeSpecification|Beginning size check for: Alias.S03E08.720p.WEB.h264-NiXON
20-8-13 16:35:22.3|Debug|AcceptableSizeSpecification|Max size is unlimited, skipping size check
20-8-13 16:35:22.3|Debug|AcceptableSizeSpecification|Item: Alias.S03E08.720p.WEB.h264-NiXON, meets size constraints
20-8-13 16:35:22.3|Debug|AlreadyImportedSpecification|Performing already imported check on report
20-8-13 16:35:22.3|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is SDTV v1 - English
20-8-13 16:35:22.3|Debug|LanguageSpecification|Checking if report meets language requirements. English
20-8-13 16:35:22.3|Debug|MaximumSizeSpecification|Maximum size is not set.
20-8-13 16:35:22.3|Debug|MinimumAgeSpecification|Minimum age is not set.
20-8-13 16:35:22.3|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. WEBDL-720p v1
20-8-13 16:35:22.3|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Alias.S03E08.720p.WEB.h264-NiXON
20-8-13 16:35:22.3|Debug|ReleaseRestrictionsSpecification|[Alias.S03E08.720p.WEB.h264-NiXON] No restrictions apply, allowing
20-8-13 16:35:22.4|Debug|RetentionSpecification|Checking if report meets retention requirements. 0
20-8-13 16:35:22.4|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is SDTV v1 - English
20-8-13 16:35:22.4|Debug|UpgradableSpecification|At least one profile allows upgrading
20-8-13 16:35:22.4|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is SDTV v1 - English
20-8-13 16:35:22.4|Debug|UpgradableSpecification|New item has a better quality
20-8-13 16:35:22.4|Debug|DelaySpecification|QualityProfile does not require a waiting period before download for Usenet.
20-8-13 16:35:22.4|Debug|HistorySpecification|Performing history status check on report
20-8-13 16:35:22.4|Debug|HistorySpecification|Checking current status of episode [1297] in history
20-8-13 16:35:22.4|Debug|DownloadDecisionMaker|Release accepted
```

Technical info:
Because the language cutoff isn't met, it still accepts the release, which seems like it is intentional given the comment here:
https://github.com/Sonarr/Sonarr/blob/3fe659587f5d826484ede5078656dc73a507e885/src/NzbDrone.Core/DecisionEngine/Specifications/UpgradableSpecification.cs#L114-L115

but it's also unexpected.

Having separate specifications for cutoff, is upgrade allowed and it being an upgrade makes things a bit weird, combining them all and providing an accurate rejection reason would help clean things up.

**Comment by damousys** [comment]
If I read that comment correctly it is by design?
But when a SDTV dutch release comes by does it get downloaded, if the current is 1080p ?

**Comment by matthieu-hm** [comment]
I have the same problem.

Sonarr: v3.0.4.988

This is my configuration:
- Profile:
    - At least 1080p + Upgrades NOT allowed
    - Language can be "French" or "English" + Upgrades NOT allowed
    - Release must contain at least one of these terms: "multi", "vostfr", "vost+fr", "subfrench"
- Indexer:
    - I use only Torrent RSS Feed to auto-download
    - RSS Sync Interval: 60min

 It looks like every time RSS sync find a monitored episode, it download that episode no matter if I have it or not.

[RSS used](https://paste.ubuntu.com/p/j5ckkkyZFz/)

Log: [sonarr.txt](https://paste.ubuntu.com/p/sK8XrWydGq/)
Log: [sonarr.debug.txt](https://paste.ubuntu.com/p/9kYQ3DGmZj/)

![Sonarr - quality profile](https://user-images.githubusercontent.com/16086894/97109466-acec2600-16d3-11eb-9e6d-fa98f5b2915a.png)

![Sonarr - Language profile](https://user-images.githubusercontent.com/16086894/97109481-b9707e80-16d3-11eb-9105-f270af9de585.png)

![sonarr - release profile](https://user-images.githubusercontent.com/16086894/97109499-dad16a80-16d3-11eb-9bab-3ab16bfd46d4.png)

![Sonarr - indexer](https://user-images.githubusercontent.com/16086894/97109507-e886f000-16d3-11eb-9547-8806a702a641.png)

![Sonarr - poster](https://user-images.githubusercontent.com/16086894/97109510-ed4ba400-16d3-11eb-902d-e9dd18f6a893.png)

Grab the same release every 60min (except 14h10, RSS sync manually started)

![Sonarr - history](https://user-images.githubusercontent.com/16086894/97109515-f2a8ee80-16d3-11eb-96c0-209648c90965.png)

**Comment by matthieu-hm** [comment]
After reading the debug logs, it's looks like the release keep being downloaded because of the preferred words score. When download is over the file is copied and renamed, so the preferred words are deleted and the preferred words score become 0.

```
20-10-25 14:09:57.5|Debug|DownloadDecisionMaker|Processing release 'Dragon Quest : Dai no Daibouken (2020) S01 E04 VOSTFR WebRIP 1080P X264-BLV (S:143/L:0)' from 'YGG (Animation S?rie)'
20-10-25 14:09:57.5|Debug|Parser|Parsing string 'Dragon Quest : Dai no Daibouken (2020) S01 E04 VOSTFR WebRIP 1080P X264-BLV (S:143/L:0)'
20-10-25 14:09:57.5|Debug|Parser|Episode Parsed. Dragon Quest  Dai no Daibouken (2020) - S01E04
20-10-25 14:09:57.5|Debug|Parser|Language parsed: English
20-10-25 14:09:57.5|Debug|QualityParser|Trying to parse quality for Dragon Quest : Dai no Daibouken (2020) S01 E04 VOSTFR WebRIP 1080P X264-BLV (S:143/L:0)
20-10-25 14:09:57.5|Debug|Parser|Quality parsed: WEBRip-1080p v1
20-10-25 14:09:57.5|Debug|Parser|Release Group parsed: BLV
20-10-25 14:09:57.5|Debug|SceneMappingService|Found scene mapping for: Dragon Quest  Dai no Daibouken (2020). TVDB ID for mapping: 374191
20-10-25 14:09:57.5|Debug|SceneMappingService|Found scene mapping for: Dragon Quest  Dai no Daibouken (2020). TVDB ID for mapping: 374191
20-10-25 14:09:57.5|Debug|ParsingService|Using Scene to TVDB Mapping for: Dragon Quest: The Adventure of Dai - Scene: 1x04 - TVDB: 1x04
20-10-25 14:09:57.6|Debug|AcceptableSizeSpecification|Beginning size check for: Dragon Quest : Dai no Daibouken (2020) S01 E04 VOSTFR WebRIP 1080P X264-BLV (S:143/L:0)
20-10-25 14:09:57.6|Debug|AcceptableSizeSpecification|Item: Dragon Quest : Dai no Daibouken (2020) S01 E04 VOSTFR WebRIP 1080P X264-BLV (S:143/L:0), meets size constraints
20-10-25 14:09:57.6|Debug|AlreadyImportedSpecification|Performing already imported check on report
20-10-25 14:09:57.6|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBRip-1080p v1 - English
20-10-25 14:09:57.6|Debug|UpgradableSpecification|Comparing preferred word score. Current: 0 New: 90
20-10-25 14:09:57.6|Debug|LanguageSpecification|Checking if report meets language requirements. English
20-10-25 14:09:57.6|Debug|MaximumSizeSpecification|Maximum size is not set.
20-10-25 14:09:57.6|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
20-10-25 14:09:57.6|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. WEBRip-1080p v1
20-10-25 14:09:57.6|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Dragon Quest : Dai no Daibouken (2020) S01 E04 VOSTFR WebRIP 1080P X264-BLV (S:143/L:0)
20-10-25 14:09:57.6|Debug|ReleaseRestrictionsSpecification|[Dragon Quest : Dai no Daibouken (2020) S01 E04 VOSTFR WebRIP 1080P X264-BLV (S:143/L:0)] No restrictions apply, allowing
20-10-25 14:09:57.6|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
20-10-25 14:09:57.6|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBRip-1080p v1 - English
20-10-25 14:09:57.6|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBRip-1080p v1 - English
20-10-25 14:09:57.6|Debug|UpgradableSpecification|Comparing preferred word score. Current: 0 New: 90
20-10-25 14:09:57.6|Debug|UpgradableSpecification|New item has a better preferred word score
20-10-25 14:09:57.6|Debug|DelaySpecification|QualityProfile does not require a waiting period before download for Torrent.
20-10-25 14:09:57.6|Debug|HistorySpecification|Performing history status check on report
20-10-25 14:09:57.6|Debug|HistorySpecification|Checking current status of episode [4110] in history
20-10-25 14:09:57.6|Debug|DownloadDecisionMaker|Release accepted
```

I tried to add `{Preferred Words}` in media management or to check the checkbox in release profile popup to include Preferred when renaming, it doesn't work.

[sonarr.debug.txt](https://paste.ubuntu.com/p/9SGmx3J7Tz/)
[sonarr.txt](https://paste.ubuntu.com/p/bjwXKnFVZY/)

![sonarr - history 2](https://user-images.githubusercontent.com/16086894/97111610-1b36e580-16e0-11eb-9cf1-41aea52cb887.png)

**Comment by ciaw** [comment]
Will investigate all the discussion already here and enable my debug logs to try and help, but wanted to add that I'm also having a bug in the last week or two where the same version of a file will download sometimes up to 10 times. I have 3 indexers, so every new time the RSS task sees a new posting of it, it just keeps refetching. Titles are exactly the same.

It will also endlessly refetch the file on an Automatic search, and if I Manual there is no red notice saying that the file matches existing quality, it sees it as better endlessly there too.

Definitely has to do with preferred words, but never had this issue until the past weeks.

**Comment by damousys** [comment]
Is this issue fixed?
Because I don't use preferred words
Can I enable it again in my settings?

**Comment by bakerboy448** [comment]
@damousys if you look at the GHI you can see that it is closed and was closed in https://github.com/Sonarr/Sonarr/commit/10c770b116d79148482a8ac1c102e1a8ac77abe2

**Comment by damousys** [comment]
What is GHI ?
And if I look at the link you refering it talks only about Preferred words ?
That's not the original problem ?
