### ISSUE TITLE
Wrong video files selected

### ISSUE THREAD

**Issue by alexandrevryghem** [Sonarr/Sonarr#3914]
**Describe the bug**
I was wondering if you could maybe exclude certain files and folders when you scan your library, I made a similar request for radarr and it has been implemented (https://github.com/Radarr/Radarr/issues/4630) so I was wondering if you could maybe do the same thing for sonarr. This is an example of a season folder which causes problems:
```
/Game of Thrones
    /Season 08
        /Behind The Scenes
             Game of Thrones S08E01.mkv
             Game of Thrones S08E02.mkv
             Game of Thrones S08E03.mkv
             Game of Thrones S08E04.mkv
             Game of Thrones S08E05.mkv
             Game of Thrones S08E06.mkv
        /Featurettes
        /Other
        Game of Thrones S08E01.mkv
        Game of Thrones S08E02.mkv
        Game of Thrones S08E03.mkv
        Game of Thrones S08E04.mkv
        Game of Thrones S08E05.mkv
        Game of Thrones S08E06.mkv
        Deleted Scenes-deleted.mkv
```

**System Information**
 - Sonarr Version: 3.0.3.907
 - Operating System: docker
 - mono Version: 5.20.1.34

**Comment by Qstick** [comment]
Radarr Fix

https://github.com/Radarr/Radarr/commit/4f22d135d62cf8285cb8e6103fd5e18ada7ae9ec#diff-a2cb1baf6f8ea1fcf6b01729c67a181d

**Comment by r0747249** [comment]
Here is the page containig the [Extra File Naming and Folder Structure](https://github.com/contrary-cat/LocalTVExtras.bundle#extra-file-naming-and-folder-structure)

**Comment by thezoggy** [comment]
Create a subfolder called "Extras" (exactly this) and sonarr will skip anything in here.

**Comment by alexandrevryghem** [comment]
Yes but then I can't use those extra's with Plex

**Comment by Thirrian** [comment]
Wouldn't it make more sense to look at sonarr's settings? For example in my config, you *know* that season folders are `Season {season:00}` and specials reside in `Specials`.

Anything else, folder-wise, is by definition something not managed by sonarr so you can call it whatever you want.

**Comment by ajw107** [comment]
I realise Plex doesn't officially support extras for TV shows yet (only movies).  But there is hope it may one day, and a lot of season packs that sonarr grabs have the extras in a 'featurettes' folder.  I know with a lot of shows, all of the extras you find on discs are not included in TVDB's specials folder (just look at either Doctor Who as an example).  So being able to create a season by season 'featurettes' folder is a life saver.  Please consider adding this feature.  The work has already been done by Radarr, just copy and paste really (and changing the tests from Movie filenames to TV Show filenames).  If you add it as an advanced config option, people can also alter it to their own media player software settings.  This does seem to be a much requested feature.

**Comment by markus101** [comment]
> The work has already been done by Radarr, just copy and paste really (and changing the tests from Movie filenames to TV Show filenames).

Thanks for volunteering! Please take a look at https://github.com/Sonarr/Sonarr/blob/phantom-develop/CONTRIBUTING.md#development for information on getting started.

**Comment by alexandrevryghem** [comment]
TV Show extras are now officially supported with the new "[Plex TV Series (BETA)](https://forums.plex.tv/t/new-plex-media-server-tv-show-series-scanner-and-agent-preview/665778/232)" agent
