### ISSUE TITLE
Seems like Sonarr has not updated the XEM map for a particular show? Not finding episodes as a result.

### ISSUE THREAD

**Issue by ziwzih** [Sonarr/Sonarr#3915]
The [XEM map](http://thexem.de/xem/show/3334) for Jojo's Bizarre Adventure is definitely correct, but sonarr can't seem to find over half of the episodes that are uploaded to nzbgeek and named according to anidb. My _sincerest_ apologies if I am not understanding the functionality here, but I can't seem to get this to work.

**Comment by markus101** [comment]
Please use the forums or subreddit for support. Take a look at debug logs to see what Sonarr is searching for.
