### ISSUE TITLE
Scrollable Footer in Manual Import Episode Selection

### ISSUE THREAD

**Issue by darthShadow** [Sonarr/Sonarr#3916]
**Describe the bug**

The "Cancel/Select Episodes" footer section in the modal needs to be horizontally scrollable to accommodate very large import paths.

**Screenshots**

[
<img width="1085" alt="Screenshot 2020-08-15 at 10 08 56 PM" src="https://user-images.githubusercontent.com/6824881/90317026-17e6e700-df44-11ea-99b4-7a6be4961907.png">
](url)

<img width="1085" alt="Screenshot 2020-08-15 at 10 14 04 PM" src="https://user-images.githubusercontent.com/6824881/90317100-b1ae9400-df44-11ea-9b62-efa50e64bcf4.png">

**Logs**

N/A

**System Information**

 - Sonarr Version: 3.0.3.906
 - Operating System: Ubuntu 18.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34

**UI Bugs:**

 - OS: MacOS Catalina (10.15.6)
 - Browser: Brave
 - Version: Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by markus101** [comment]
Not scrollable, but that path should be truncated, the full path could still be shown in a tooltip.

In the mean time just select the episode folder so you don’t have a super long relative path.

**Comment by darthShadow** [comment]
Occasionally, it does seem to wrap the text too, which may be a better solution.

Example: 
<img width="1081" alt="Screenshot 2020-08-16 at 2 10 48 AM" src="https://user-images.githubusercontent.com/6824881/90321261-bc2d5580-df65-11ea-83bd-4e39f819a5f9.png">
