### ISSUE TITLE
Sonarr creating wrong directory

### ISSUE THREAD

**Issue by niftienev** [Sonarr/Sonarr#3918]
Sonarr Version etc.

About
Version
2.0.0.5338
Mono Version
6.8.0.105
AppData directory: /share/CACHEDEV1_DATA/SONARR_CONFIG
Startup directory: /share/CACHEDEV1_DATA/.qpkg/QSonarr/NzbDrone

Proglem:

When downloading "Grace and Frankie", Sonarr creates a new directory "Will and Grace" and puts the files in there.

Thanks,

**Comment by markus101** [comment]
Sonarr uses whichever path is set for the series, edit it and change it.

The path is set when added, unless it was named wrong before or it was imported as the wrong series it must have been edited after the fact.

**Comment by niftienev** [comment]
Thanks, you learn something every day.
