### ISSUE TITLE
Command api not returning data

### ISSUE THREAD

**Issue by clinton-hall** [Sonarr/Sonarr#3920]
**Describe the bug**
API not providing response for command endpoint

As reported by user in nzbToMedia
https://github.com/clinton-hall/nzbToMedia/issues/1766

**Additional context**
The command is being posted with json data, name=DownloadedEpisodesScan and path defined.

The return from Sonarr is `[]` with no id being returned to be able to verify when the process has completed.

Further manually hitting `http://localhost:8081/api/command?apikey=<apikey here>&name=DownloadedEpisodesScan&path=/mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2&downloadClientId=SABnzbd_nzo_bfdc8eom&importMode=Copy` via webbrowser also results in the same `[]` being returned.

Documentation suggests this should return data:
https://github.com/Sonarr/Sonarr/wiki/Command#returns-1

**Comment by markus101** [comment]
You've left out a lot of required information, including version and logs.

An empty array would be returned for a GET request to `http://localhost:8081/api/command`, (a webbrowser would be doing a GET request). If a URL base is set in Sonarr and not part of the request URL it will cause a redirection that ends up making a GET request. A POST to `http://localhost:8081/api/command` will never return an array, it would be an object or an error.

Both debug and trace logs will show the method used: `20-8-18 15:58:39.8|Debug|Api|[GET] /api/v3/command: 200.OK (4 ms)`

**Comment by clinton-hall** [comment]
Sorry for missing data. I myself don't have all of the details as it was reported by another user.

The user had confirmed use of the "latest" Sonarr package in Arch Linux using python 3.8 where the postprocess script is called from SABnzbd. I'll ask for specific version.

I had tested this some time ago and it was working for me. My test system (Asustor) has since been updated and I'll need to check for an updated Sonarr package to be able to verify this at my end.

I can confirm that the call from nzbToMedia is using POST, and the data is json

(Specific sequence of code from nzbToMedia to show the post data as follows)
```
url = '{0}{1}:{2}{3}/api/command'.format(protocol, host, port, web_root)
headers = {'X-Api-Key': apikey}
data = {'name': 'DownloadedEpisodesScan', 'path': dir_name, 'downloadClientId': download_id, 'importMode': import_mode}
data = json.dumps(data)
logger.debug('Opening URL: {0} with data: {1}'.format(url, data), section)
r = requests.post(url, data=data, headers=headers, stream=True, verify=False, timeout=(30, 1800))
try:
    res = r.json()
    logger.postprocess('Sonarr response: {0}'.format(res))
    scan_id = int(res['id'])
    logger.debug('Scan started with id: {0}'.format(scan_id), section)
except Exception as e:
    logger.warning('No scan id was returned due to: {0}'.format(e), section)
    scan_id = None
```

this is returning the following logging
```
DEBUG ::NZBDRONE: Opening URL: http://localhost:8081/api/command with data: {"name": "DownloadedEpisodesScan", "path": "/mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT", "downloadClientId": "SABnzbd_nzo_9wy5ledy", "importMode": "Copy"}
POSTPROCESS: Sonarr response: [] 
WARNING ::NZBDRONE: No scan id was returned due to: list indices must be integers or slices, not str
```

Initially I asked the user to use the URL posted above to see if any data would be returned. When none was I checked the docs and saw that POST was required, so I changed the logging to capture the results returned from the POST, as per code above.

I had originally not considered issues with URL base as I had expected that to give an error, but if this would redirect as a get, then that could explain what is happening.

I will try and get the user to check the url base, and also try and get logs debug logs from Sonarr at the time of the nzbToMedia post.

Thanks for your time to respond. Your response does confirm my expectation of a returned object or an error, and rules out recent changes to this api that would cause this.

**Comment by clinton-hall** [comment]
The user has confirmed that the wrong URL base was set after restoring an old config.
After correcting this, everything is working correctly again.

Thanks again for your explanation.
