### ISSUE TITLE
Size on Disk field fails in the Mass Editor

### ISSUE THREAD

**Issue by IonicEcko** [Sonarr/Sonarr#3921]
**Describe the bug**
When attempting to add the "Size on Disk" field in the "Mass Editor" page, you get an error.

**Logs**
Page output (details)
https://pastebin.com/k7EQ03bz

Doesn't appear to generate log issues, even with trace and debug enabled?

**System Information**
 - Sonarr Version: 3.0.3.911
 - Operating System: Windows Server 2019
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
 - OS: Windows 10 2004
 - Browser: Multiple
 - Version: Latest

**Comment by IonicEcko** [comment]
Another user commented on Discord mentioning its not happening for them so seems to be specific to my install. Happy to just close this off as one off if there's no benefit to looking into it. Chrome debug output at https://pastebin.com/Rjp7WMGU

**Comment by IonicEcko** [comment]
Fixed it >.<

Just in case someone else finds this and has the same issue. Noticed a bunch of shows with no 0B in Size on Disk (on the main series page). Just opened each one and hit "Refresh and Scan" and they got  the 0B entry and now it works. Sorry to waste everyones time :smile:

**Comment by markus101** [comment]
Re-opening so we can prevent it from exploding.
