### ISSUE TITLE
Include Renamed Files with Webhooks/Custom Scripts

### ISSUE THREAD

**Issue by Alexdc-12** [Sonarr/Sonarr#3927]
Hi guys
Love the functionality the webhook brings and am able to use that very well however i have one gripe, the rename event. 
If an episode is downloaded and we get the following filename for example Series - S01E01 - TBA.mkv the ondownload event will tell me this, however when the rename occurs i have no information that tells me the new file name, episode id or season id. Is it possible to add this extra information to the event? Currently all i can tell is something within that series has been renamed. 

Thanks

**Comment by markus101** [comment]
Please use the templates when filling out issues.

Why would this information be useful for your usecase? Keep in mind that this even is only trigged if you rename the files for a series sometimes after they’re imported (useful for media player connections so they can rescan that folder for changes), the original import + rename is handled by the on download event.

**Comment by Alexdc-12** [comment]
I have built a db to store some of the data so i can connect a player and query data. When an episode is renamed it breaks the file link so episode wont play. 
I have looked at all the other events and dont see anything get triggered when this happens. 

If i go into folder and rename file, i go into sonarr and do a refresh and scan on series, this then sees the incorrect name and gives me option to rename the file correctly. The webhook is setup for on download, upgrade and rename. 

An example.output is below, i manually renamed a episode, did a refresh and scan and then executed the rename. This is all the webhook received

{
  "eventType": "Rename",
  "series": {
    "id": 701,
    "title": "Hanna",
    "path": "/mnt/TVShows/Hanna",
    "tvdbId": 357690,
    "tvMazeId": 28449,
    "imdbId": "tt6932244",
    "type": "standard"
  }
}

**Comment by markus101** [comment]
> An example.output is below, i manually renamed a episode, did a refresh and scan and then executed the rename. This is all the webhook received

Yeah, I'm aware what is sent, currently Sonarr doesn't keep a record of the renamed files, should be doable at some point, but in the mean time you'd be best off to fetch all the episodes/files and figure out which ones have changed based on the path.
