### ISSUE TITLE
 [Request] Remove Duplicate Copies

### ISSUE THREAD

**Issue by zero77** [Sonarr/Sonarr#3928]
**Describe the problem**
 Before the quality profile cut off is met there are sometimes multiple copies of the same episode downloaded, which take up unnecessary disk space.

**Describe any solutions you think might work**
 Can you please add some kind of clean up that removes the duplicate copies of the same episode, ideally only the lower resolution copies, thanks.

**Additional context**

**Comment by markus101** [comment]
During import Sonarr will remove lower qualities. It will not remove downloads that haven't been imported, the closest to manage that would be https://github.com/Sonarr/Sonarr/issues/370 nor will it remove seeding torrents (and no plans to).

**Comment by zero77** [comment]
`During import Sonarr will remove lower qualities.` 

I may need to reopen this as a bug.
As, based on your statement it should have been imported and then removed, though i will have another look.

**Comment by markus101** [comment]
It's possible, but delete happens before Sonarr imports from the download client. If something else is putting files in the series folder then Sonarr  it will also need to remove previous files, SOnarr will not remove those.

**Comment by zero77** [comment]
That could be what's happening.

As the download client is on a different computer.
After the download is finished the files are transferred to the computer were sonarr is installed.

**Comment by zero77** [comment]
@markus101 
Is this scenario considered a bug or request.

**Comment by markus101** [comment]
Probably a feature, but not one that we have plans to support. Sonarr should be able to copy/move the files from the other computer instead of them being copied over.

**Comment by zero77** [comment]
But it won't remove duplicate copies in this scenario, is that correct.

**Comment by markus101** [comment]
If Sonarr isn't importing the files, then no, whatever is importing them should do that. Sonarr also won't delete lower quality downloads that are still seeding.

If you want to troubleshoot further or find a way to improve the import process so Sonarr can remove lower quality files from the series folder then open a thread on the forums or subreddit to dig in further.
