### ISSUE TITLE
Tell Plex to Scan only folder with new content

### ISSUE THREAD

**Issue by kilroyma** [Sonarr/Sonarr#3929]
**Describe the problem**
Whenever something new is added to Plex Sonarr sends a command to Plex to scan that entire library, but for those of us with huge libraries it takes a long time actually see the new content show up. It would be a much appreciated feature if you could have Sonarr only scan the directory where something was just added instead of the whole library.

**Describe any solutions you think might work**
Plex has a command line command that allows it to scan individual folders within a directory (link below). While I'm not programming savvy enough to figure this out myself I feel like it shouldn't be that hard to integrate that Plex command into Sonarr so that when something new gets added to a directory Sonarr tells Plex to only scan that one individual folder. 

**Additional context**
This is the link to the Plex command https://forums.plex.tv/t/update-individual-tv-shows/197053/20
Thank you so much for taking the time to read my request, your work is very much appreciated!

**Comment by markus101** [comment]
> Whenever something new is added to Plex Sonarr sends a command to Plex to scan that entire library

For a new series, yes, but for an existing series Sonarr will try and find that series (by TVDB ID) then update only that series, but it does require partial scanning to be enabled. This is all done via the API, Sonarr won't call that command, but you could have a custom script do it.
