### ISSUE TITLE
Try To Detect Source Quality from Metadata

### ISSUE THREAD

**Issue by turtleflax** [Sonarr/Sonarr#3930]
**Describe the problem**
In cases where media source quality is not explicitly specified by the title or filename, Sonarr currently seems to detect resolution on import and assign the lowest source quality (HDTV/SDTV).  So an unmarked 720p episode would be imported as HDTV-720p

**Describe any solutions you think might work**
I've noticed that sometimes there are indications of the source quality in the metadata of the file.  Can Sonarr use the same logic it would use to detect source quality from a filename or title, but also search the metadata?  

An example snippet is included below where it has assigned HDTV-720p, but from the metadata it could detect that it is WEB-DL.  The tag is found in the Movie Name metadata tag most often in my experience

**Additional context**

> $ mediainfo 3x08-The\ Hero\ \[HDTV-720p\]\[x265\].mkv 
> General
> Complete name                            : 3x08-The Hero [HDTV-720p][x265].mkv
> Format                                   : Matroska
> ...
> Overall bit rate                         : 4 351 kb/s
> Movie name                               : Nathan for You S03E08 The Hero 720p WEB-DL DD+2 0

**Comment by akyag** [comment]
Sorry to bump an old issue, but this is the same problem I am facing. If I successfully grab and finish a webdl-720p, the next time sonarr starts, it labels it as 720p hdtv and tries to upgrade it again by grabbing same release. If I disable upgrades, it marks the episode as cutoff unmet.
