### ISSUE TITLE
Season Pack searches only for "S##" and not "Season #"

### ISSUE THREAD

**Issue by epheterson** [Sonarr/Sonarr#3934]
**Describe the bug**
When searching for season packs, I noticed some results missing in Sonarr's interactive search. When digging closer I realized the difference is that Sonarr searches for season packs only using the format "S##" and doesn't also search for "Season{wildcard}#", where the wildcard could be " ", ".", "-", etc...

 - Sonarr Version: 3.0.3.911

**Comment by markus101** [comment]
Please include all the requested information, including debug logs when filing a bug.

On proper indexers (those that index by ID and season/episode numbers) Sonarr doesn’t actually search for a specific format. If you’re using Jackett it will do the same and Jackett translates that to a request to the indexer. Debug logs will show exactly how Sonarr is searching.

**Comment by LoicAuge** [comment]
I add my comment here too.

Describe the problem
I want to search 1st seson of a TV show, but the search is like Showname + S01, but in the index, this is Showname + Season 1 (this is the idea, i think there the same issue with different languages)

Describe any solutions you think might work
I think add a setting to change this "S01" for "Season 1" or "Saison 1" or whatever.

**Comment by epheterson** [comment]
@markus101 Sorry I never saw your message when I posted this and when I just tried again I didn't seem to reproduce this. If I hit it again I'll be sure to attach logs so we can track it down.

**Comment by LoicAuge** [comment]
![Capture](https://user-images.githubusercontent.com/35797273/94842150-56186700-041b-11eb-93ba-a425c4943ff5.PNG)
As you can see, Sonarr is searching S01 and don't found any result because, on the index, it's "Saison 1" and not S01

**Comment by epheterson** [comment]
@LoicAuge Can you attach your debug logs so @markus101 can re-open the bug and take a look?

**Comment by markus101** [comment]
Those don't look like Sonarr logs to me, even in Sonarr's logs when it says it's searching for a season and formats the season number, that is _only_ for logging.

As I mentioned before Sonarr passes the query off to the indexer/Jackett as title/tvdbid (TVDB ID being preferred) along with the season number (and episode number for episode searches), in the case of Jackett, it translates that request to a query it makes on the indexer, if that's incorrect (which appears to be the case here), then it needs to be fixed there.

**Comment by LoicAuge** [comment]
I updated my post, it's not a bug but just a request because it's impossible for me to download a show in French for the moment

**Comment by markus101** [comment]
It's a request you'll have to make to Jackett, Sonarr doesn't handle that.

**Comment by LoicAuge** [comment]
I don't think so, because it's Sonarr which format the string  for Jackett to make the search in that case. It can be easily handled

**Comment by markus101** [comment]
Please show the debug logs where Sonarr is sending a formatted string to Jackett.

**Comment by markus101** [comment]
Those are info logs, not debug.

I'll refer to my previous comment:
> even in Sonarr's logs when it says it's searching for a season and formats the season number, that is only for logging.

Again, that's just formatted for logging, it's not the request that was made to Jackett, enable debug logging and get the URL.

**Comment by LoicAuge** [comment]
![Capture](https://user-images.githubusercontent.com/35797273/94847413-d7bfc300-0422-11eb-9c61-c70534904f77.PNG)
Here are the lasts parts of the URLs

**Comment by LoicAuge** [comment]
I tried without "&season=1" and i have result, do you think there is an incompatibility with Jackett on this point ?

**Comment by markus101** [comment]
Not an incompatibility, Sonarr sends the season number and Jackett formats it before sending it to the indexer. Jackett will need to be updated to change how those requests are formatted and/or make additional requests for the various options. You'll have to discuss what is possible with them.

**Comment by kangbeicai** [comment]
> Not an incompatibility, Sonarr sends the season number and Jackett formats it before sending it to the indexer. Jackett will need to be updated to change how those requests are formatted and/or make additional requests for the various options. You'll have to discuss what is possible with them.

i just met another problem.
when i search the episodes in season 2, it didn't send the season number to jackett but just the total episode number, it only happens in this sery and other series seem work well 
![微信截图_20210109171238](https://user-images.githubusercontent.com/57837294/104087979-681d6780-529e-11eb-9f9e-1b67a78038e3.png)
![微信截图_20210109171402](https://user-images.githubusercontent.com/57837294/104087981-6a7fc180-529e-11eb-8dd0-629f03c54c24.png)


Another problem is , when grabbing from indexer , the language is chinese and after downloading the language changes to english,  although the language in files is exactly chinese but it makes some troubles when organize the series.
![1](https://user-images.githubusercontent.com/57837294/104088098-5be5da00-529f-11eb-91d3-7c83ca08e20a.png)

**Comment by bakerboy448** [comment]
the series is anime, thus it searches the absolute number

what's the media info on the file and a trace log of it being read by sonarr when importing?
