### ISSUE TITLE
Sonarr Crashes every 8 days or so

### ISSUE THREAD

**Issue by Brant-Salamon** [Sonarr/Sonarr#3938]
**Describe the bug**
Sonarr seems to crash periodically, I have `mono_crash.x.x.json` files produced which I will upload. I'm currently running sonarr with Trace logging enabled, however it will probably not crash again until the 12th/13th of Sept. I'll update this with the trace log prior to the crash once I have it.

**Screenshots**

**Logs**

[mono_crash.0.0.json.txt](https://github.com/Sonarr/Sonarr/files/5179237/mono_crash.0.0.json.txt)
[mono_crash.0.1.json.txt](https://github.com/Sonarr/Sonarr/files/5179238/mono_crash.0.1.json.txt)
[mono_crash.0.2.json.txt](https://github.com/Sonarr/Sonarr/files/5179239/mono_crash.0.2.json.txt)

**System Information**

 - Sonarr Version: Sonarr Ver. 2.0.0.5344
 - Operating System: Debian 10.5
 - .net Framework (Windows) or mono (macOS/Linux) Version: mono 6.10.0.104-0xamarin16+debian10b1

**Additional context**

**Comment by markus101** [comment]
Potentially the same as: https://github.com/Sonarr/Sonarr/issues/3824

Make sure you're capturing standard output and error to a file, Sonarr's own text logs will not be written to when mono crashes.

**Comment by Brant-Salamon** [comment]
@markus101 Will do, I'm running this under systemd, is there anything special that needs to be done for that? I assume the stderr and stdout will dump into `journalctl` ?

**Comment by markus101** [comment]
I'm not sure. but you should be able to verify that now by checking `journalctl`.

**Comment by Taloth** [comment]
`journalctl -u sonarr`

**Comment by markus101** [comment]
Will re-open if there is more information and it's different from https://github.com/Sonarr/Sonarr/issues/3824
