### ISSUE TITLE
 SABnzbd Status "Renaming done!" Not Imported due to Downloaded - Waiting to Import

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#3940]
**Describe the bug**
It appears downloads in SABnzbd (3.0.2) that have a status of complete, but display "Renaming done!" are not recognized as ready to import by Sonarr (3.0.3.913)
**Screenshots**
N/A
**Logs**
Response from SAB
https://pastebin.com/ezMan0JX

**System Information**
N/A?

**UI Bugs:**
N/A

**Additional context**
various files that are Downloaded - Waiting to Import: 

Chicago.Med.S03E18.720p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS

The.Real.Housewives.of.Orange.County.S12E05.Moving.In.Moving.On.and.Moving.Fast.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb

The.Real.Housewives.of.Atlanta.S09E10.Uncharitable.Behavior.1080p.BRAV.WEBRip.AAC2.0.x264-BTW

**Comment by markus101** [comment]
`Downloaded - Waiting to Import` means `Refresh Monitored Downloads` has processed it and it'll be imported when `Process Monitored Downloads` runs, either that task hasn't run or there is an error in the logs as to why it couldn't import it.

**Comment by bakerboy448** [comment]
Further digging into the db indicates `Process Monitored Downloads` appears to be getting stuck due to the DB being locked with high frequency.

Exception Thrown:
https://pastebin.com/cQxgmnS1
