### ISSUE TITLE
Set all TV series to Monitored/All Seasons. Now Specials are being picked up even though they aren't selected in Season Pass

### ISSUE THREAD

**Issue by severd8** [Sonarr/Sonarr#3941]
**Describe the bug**

**Actions Taken**
1. Go to Season Pass
2. Selected all TV series
3. Set to Monitored/All Seasons
4. Go to Wanted > Missing
5. Search all missing

Since I've done this, it is now downloading Specials for all of my shows even though Specials are not selected in the Season Pass area. See screenshot of 'Dr. Who' for example below. Let me know if anything else is needed from me or if this is expected.

**Screenshots**
https://imgur.com/a/EHJHiLS

**Logs**
Debug/Trace wasn't turned on when this happened. Here are general logs:
https://drive.google.com/file/d/1TpdOtEVcReRssunb57s9LC0ta9_eD2Rj/view?usp=sharing

**System Information**

 - Sonarr Version: Version 3.0.3.913
 - Operating System: Windows 10
 - .net Framework (Windows): 4.8.03761

**UI Bugs:**
 - No UI bugs

Let me know if I can provide any more details/logs.

Thanks!

**Comment by markus101** [comment]
Look at the actual episodes in the specials, the season can be unmonitored, but the episodes still monitored, but without debug logs it's impossible for us to say for sure what happened.

**Comment by severd8** [comment]
> Look at the actual episodes in the specials, the season can be unmonitored, but the episodes still monitored, but without debug logs it's impossible for us to say for sure what happened.

I'm not seeing any of the Special episodes monitored. Here are the some of the same episodes from my previous screenshot.

https://imgur.com/a/Huc5Bak

**Comment by severd8** [comment]
Ok, it looks like my search all is complete. What are your thoughts on doing this to try to duplicate the issue with debug logs on?

1. Set debug logs on
2. Set all series to unmonitored
3. Cycle Sonarr service
4. Set all to monitored
5. Run another search all missing

Let me know.

**Comment by markus101** [comment]
Why unmonitor them and then monitor them again? No need to restart Sonarr either.

You didn't have Wanted: Missing filtered to show `Unmonitored` episodes did you? I'm not able to reproduce this issue any other way.

**Comment by severd8** [comment]
No, I don't believe I had them Filtered.

I'll just set my logs to Debug from here on out and see if it happens again. 

Thanks for all that you do and the quick replies!

Tyler
