### ISSUE TITLE
Series import hangs on duplicate title slug

### ISSUE THREAD

**Issue by gimpyestrada** [Sonarr/Sonarr#3944]
Importing multiple titles from the Series->Import page

Apparently there is already another series that is using the name Hunted, so when I tried to import a second series names Hunted it died, but the UI is still spinning as if it were performing the import.  I've let it sit for a couple of hours and it has made no progress, so that means that this message is hanging the process:

20-9-8 10:48:02.1|Warn|SonarrErrorPipeline|Invalid request Validation failed:
 -- TitleSlug: Title slug 'hunted' is in use by series 'Hunted'

**Logs**
I don't have debug logs, but could retry with debug or trace turned on if that would be useful.

**System Information**

 - Sonarr Version: 3.0.3.913
 - Operating System: Ubuntu 20.04.1 LTS (Focal Fossa)
 - mono version: 6.10.0.104

**Comment by bakerboy448** [comment]
Trace logs would help.

**Comment by gimpyestrada** [comment]
Here are the info, debug and trace logs covering the time of the recreate.

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/5190089/sonarr.txt)
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/5190090/sonarr.debug.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/5190092/sonarr.trace.txt)

**Comment by markus101** [comment]
In this case trace logs don't help much since this is a UI issue. TVDB will need to fix the duplicate title issue before you can import both series, but we can fix the infinite spinner and show an error in the UI.

**Comment by gimpyestrada** [comment]
The duplicate slug isn't my beef, I just would like to see it either error out and show something, or recognize that it should skip that series and move on with the job (and probably report the error after).
