### ISSUE TITLE
systray - add icon to systray context menu

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#3945]
**Describe the problem**
Add icons to systray context menu

current:
![img](http://zoggy.net/2020-09-08_18-45-43.png)

example of others:
![img3](http://zoggy.net/2020-09-08_18-47-14.png)

![img2](http://zoggy.net/firefox_2020-09-08_18-46-20.png)
-- https://github.com/duplicati/duplicati/tree/master/Duplicati/GUI/Duplicati.GUI.TrayIcon

**Comment by markus101** [comment]
We can revisit one day, but not committing to it now.
