### ISSUE TITLE
Re-arrange custom filters

### ISSUE THREAD

**Issue by agneevX** [Sonarr/Sonarr#3946]
**Describe the problem**
The inability to re-order custom filters

**Describe any solutions you think might work**
Drag and drop to reorder custom filters.

**Additional context**
Ideally this feature should be designed to work on mobile devices too.

**Comment by markus101** [comment]
At this we do not have plans for reordering.

**Comment by agneevX** [comment]
Why even make a Feature Request template if you're gonna close it outright?

**Comment by markus101** [comment]
Not every request is implemented, we can't conceivably keep every feature request open and maybe do it some day, it's issue overload. At this time it isn't something we plan to do, so it's been closed.
