### ISSUE TITLE
rTorrent labels not compatible with Sonarr

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#3948]
**Describe the bug**
Manually added downloads into rtorrent with the label of "tv" are not picked up in Sonarr even if the category of tv is entered in the DL client config.

If the category is left blank in sonarr than only 15 of 24 torrents show up in queue. It is expected all 24 show. (screenshots) (Show Unknown Series Items enabled)

If "tv" is set as the category than nothing shows in queue.

**Screenshots**
![image](https://user-images.githubusercontent.com/55419169/92679502-3b584400-f2ee-11ea-91d3-d968ec1dbd7d.png)
![image](https://user-images.githubusercontent.com/55419169/92679566-5e82f380-f2ee-11ea-90bc-b36627d8ab1b.png)

**Logs**
https://pastebin.com/prSxM4Cc

**System Information**
Version
3.0.3.913
Mono Version
5.20.1.19

**UI Bugs:**
N/A
**Additional context**
N/A

**Comment by bakerboy448** [comment]
xref [Radarr 4984](https://github.com/Radarr/Radarr/issues/4984)

**Comment by markus101** [comment]
What do your rTorrent settings in Sonarr look like?

If Sonarr is set to use a specific label in rTorrrent it shouldn’t be getting movies back from rTorrent, unless you did that specifically for testing, but then the sceeenshots and any logs aren’t helpful because Sonarr uses the label specified not `tv` or any other label.

**Comment by bakerboy448** [comment]
setting the category to 'tv' in sonarr.rtorrent results in nothing at all being displayed even with that show any option enabled.

the kicker is the torrents in rtorrent were either manually grabbed or transferred from deluge meaning ARR did not grab them technically.  But if torrents match the category in settings and that option to display unrelated is checked, I would expect anything in that category to show.

See the xref'd radarr issue.  I was working with Q late last night and we confirmed this is a bug somewhere.

I'd also suggest pulling upstream from Radarr  [this commit](https://github.com/Radarr/Radarr/commit/a2e8d1d5d6b0b93f8681a983b62e3382ed806a4f)  as currently there is no other rtorrent logging for the response.

**Comment by Qstick** [comment]
That was just a quick log of the result since rtorrent doesnt use httpclient thus doesn't log requests on trace. Was to see what was coming back, it needs to be cleaned a bit so it's not fully formatted json in the log ( that was just for my convineince last night.

**Comment by bakerboy448** [comment]
appears possibly isolated to non-ARR grabbed torrents?

**Comment by markus101** [comment]
I'm not able to reproduce this issue. I setup a fresh docker container (`linuxserver/rutorrent:latest`) of rutorrent and added it to Sonarr. Then did 3 tests:

1. Added to rtorrent from Sonarr
1. Added to rtorrent manually with the label set when it was added
1. Added to rtorrent manually, label was set after adding

In all 3 cases the torrent has shown up in Sonarr's queue after a refresh.

I'm not sure what's going on in your setup, but Sonarr is making the correct request and rtorrent is returning the correct torrents in my pretty vanilla setup.

**Comment by bakerboy448** [comment]
appears to have been related to reverse proxy (needed to add support for webhooks) and front end timeouts....weird

**Comment by markus101** [comment]
That really should be figured out before filing a bug report.
