### ISSUE TITLE
Sonarr removing Release Group, replacing with "Sonarr"

### ISSUE THREAD

**Issue by wsegatto** [Sonarr/Sonarr#3949]
Can you please help me understand why would Sonarr perform such behavior and lose important information such as the Release Group?
My Sonarr is doing the following:

**Organize & Rename**
_All paths are relative to: /media/hdd/Plex Library/TV Shows/The Expanse
Naming pattern: {Series Title}.S{season:00}E{episode:00}.{Episode Title}.{Quality Full}.{Release Group}_
**-** Season 2/The Expanse.S02E04.Godspeed.Bluray-1080p.ROVERS.mkv
**+** Season 2/The Expanse.S02E04.Godspeed.Bluray-1080p.Sonarr.mkv

![image](https://user-images.githubusercontent.com/35738729/92734470-f31d3e00-f34e-11ea-9754-e8a93377468d.png)

Any ideas?

Will

**Comment by markus101** [comment]
Sonarr no longer has the release group stored (and it’s not preceded by a dash so Sonarr can’t parse it).

That will happen if the episode file is renamed outside of Sonarr or Sonarr loses track of the episode for any other reason.
