### ISSUE TITLE
Vuze RemoveTorrent doesnt work

### ISSUE THREAD

**Issue by shorbachuk** [Sonarr/Sonarr#3951]
I have Vuze Web Remote 0.6.5 and 
Vuze:
SWT v4716, win32
Windows 10 v10.0, amd64 (64 bit)
V5.7.6.0/4 az3

Sonar 2.0.0.5344 - Mar 13 2020
Windows 10

Removing torrents does not work. I can see in the trace logs that the API call was made and a 200 was returned, however the torrent was NOT removed. 
```
2020-9-11 12:23:18.0|Trace|HttpClient|Req: [POST] http://localhost:9091/transmission/rpc: torrent-remove(...)
2020-9-11 12:23:18.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2020-9-11 12:23:18.1|Trace|HttpClient|Res: [POST] http://localhost:9091/transmission/rpc: 200.OK (112 ms)
2020-9-11 12:23:18.1|Trace|HttpClient|Response content (37 bytes): {"result":"success","arguments":{}}
```

I think instead of this:

```
public void RemoveTorrent(string hashString, bool removeData, TransmissionSettings settings)
        {
            var arguments = new Dictionary<string, object>();
            arguments.Add("ids", new string[] { hashString });
            arguments.Add("delete-local-data", removeData);

            ProcessRequest("torrent-remove", arguments, settings);
        }
```

should be
```
public void RemoveTorrent(string hashString, bool removeData, TransmissionSettings settings)
        {
            var arguments = new Dictionary<string, object>();
            arguments.Add("ids", new int[] { int.Parse(hashString) });
            arguments.Add("delete-local-data", removeData);

            ProcessRequest("torrent-remove", arguments, settings);
        }
```

I have tested this in postman and this works:

```
{
  "method":"torrent-remove",
  "arguments":{
  "ids": [258],
   "delete-local-data" : true
  }
}
```
However this does not, although it still returns 200:

```
{
  "method":"torrent-remove",
  "arguments":{
  "ids": ["258"],
   "delete-local-data" : true
  }
}
```

**Comment by markus101** [comment]
Please fill out the entire bug template, including the exact version of Sonarr, "latest" isn't helpful.

**Comment by markus101** [comment]
According the the `rpc-spec` from the Vuze web API plugin:

```
 Request arguments: "ids", which specifies which torrents to use.
                  All torrents are used if the "ids" argument is omitted.
                  "ids" should be one of the following:
                  (1) an integer referring to a torrent id
                  (2) a list of torrent id numbers, sha1 hash strings, or both
                  (3) a string, "recently-active", for recently-active torrents
```

`hashString` is a `sha1 hash string`, which should remove it, Sonarr does not store a numeric ID for the for the torrent.

**Comment by shorbachuk** [comment]
Is there a way to log the Json body sent? Didn’t see it in the trace logs. I know whatever is being sent currently is not removing the torrent.

________________________________

**Comment by markus101** [comment]
Trace logs will have the most info. Removal works in Transmission, which Vuze's web API is based on, if Vuze is failing to remove when provided a valid identifier (the hash is valid) then it needs to be fixed on Vuze's side.

**Comment by shorbachuk** [comment]
I dug into this a little more (with WireShark) and it seems the problem is related to the **case** of the hashString:

This is what is returned via torrent-get
```
...
{
	"seedRatioLimit":0.0,
	"downloadDir":"D:\\Downloads\\sonarr",
	"totalSize":845233285,
	"downloadedEver":0,
	"name":"REDACTED",
	"eta":1827387392,
	"fileCount":1,
	"status":4,
	"errorString":"",
	"leftUntilDone":845233285,
	"id":393,
	"isFinished":false,
	"uploadedEver":0,
	"hashString":"588B201DBC43A3737C7F9AE505750FFF72127A55"
}
...
```

This is what Sonar sends (which doesn't work)


```
POST /transmission/rpc HTTP/1.1
User-Agent: Sonarr/2.0.0.5344 (windows 10.0.17763.0)
Accept: application/json
Authorization: Basic YWRtaW46UHVkZGxlczUy
Content-Type: application/json
X-Transmission-Session-Id: 0x1.3604d28759997p-1
Host: 127.0.0.1:9091
Content-Length: 161
Accept-Encoding: gzip
Connection: Close

{
  "method": "torrent-remove",
  "arguments": {
    "ids": [
      "588b201dbc43a3737c7f9ae505750fff72127a55"
    ],
    "delete-local-data": true
  }
}
```

When I send the upper case version of the hash string, it is removed as expected.

**Comment by shorbachuk** [comment]
It seems to be converted here:
https://github.com/Sonarr/Sonarr/blob/0f792f9eb9517a4165a54d7c4551f4f68822d18e/src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs#L60

Any reason why the case needs to be changed? Seems vuze doesn’t like that

**Comment by markus101** [comment]
Not sure why it was originally done that way, but it worked for Transmission and when Vuze was built off of it, no one noticed it not working. Thanks for digging in, we'll get it fixed.

**Comment by jjjshpmy** [comment]
@shorbachuk were you able to have sonarr automatically import completed downloads in Vuze?

**Comment by bakerboy448** [comment]
@jjjshpmy if you look at the issue you'll see Markus pushed a commit that fixed this

**Comment by jjjshpmy** [comment]
Yes, but I'm asking the author about importing

**Comment by bakerboy448** [comment]
Well there is a lack of reports and no report by the author that there were importing issues....

**Comment by jjjshpmy** [comment]
> Trace logs will have the most info. Removal works in Transmission, which Vuze's web API is based on, if Vuze is failing to remove when provided a valid identifier (the hash is valid) then it needs to be fixed on Vuze's side.

Your confidence is remarkably similar to Markus's.

**Comment by markus101** [comment]
This issue is about removing imported torrents, which was support for two years before this issue came up (hence my confidence it actually worked as expected). Why are you asking about importing completed torrents here on an unrelated issue?

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

**Comment by shorbachuk** [comment]
Markus committed the fix that resolved my issues
