### ISSUE TITLE
Import/Export Release Profiles

### ISSUE THREAD

**Issue by nemchik** [Sonarr/Sonarr#3952]
**Describe the problem**
Sharing information with others about how to setup a release profile could be easier.

**Describe any solutions you think might work**
Radarr has an option to import/export custom formats, I'd like to see the same for sonarr's release profiles.

**Additional context**
Would make setting these up way easier https://github.com/TRaSH-/Tutorials-FAQ

P.S. I'm not complaining that the current options too setup are hard, just saying it would be convenient to have import/export

**Comment by markus101** [comment]
Done in v4 with Custom Formats.
