### ISSUE TITLE
Change History/Grabbed Icon to match Status Colors

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#3956]
title...
rather than gray, be purple (in process) and then green (success) or red (failed)

xref Radarr https://github.com/Radarr/Radarr/issues/5009

**Comment by markus101** [comment]
I think this has a reasonable chance to be awful, in theory it would be nice, but in use I’m expecting it to look like a crappy rainbow.

**Comment by bakerboy448** [comment]
Fair enough on all the colors...may help to mock it up to see?; can we at least pull what is in the PR

**Comment by markus101** [comment]
I think you’re talking about a separate issue. As for migrating over a different PR, if someone wants to do that, we’ll take a look.

**Comment by markus101** [comment]
Sounds like @Qstick is on the same page as not necessary, so closing.
