### ISSUE TITLE
SonarrV3 traktlist import brocken by tvdbid

### ISSUE THREAD

**Issue by Mitnick84** [Sonarr/Sonarr#3959]
**Describe the bug**
i have a documentarylist on trakt.tv that cant sonarr import.
sonarr find a tvdbid that not exist and it abort the complete list. nothing is added.

sorry for my bad english. 

CommandExecutor | Error occurred while executing task ImportListSync: Validation failed:   -- TvdbId: A series with this ID was not found | 8:12am |  
-- | -- | -- | --
 

tvdbid 295279 was not found, it may have been removed from TheTVDB.

 - Sonarr Version: 3.0.3.924

**Comment by Thirrian** [comment]
Probably this pull request will address that: https://github.com/Sonarr/Sonarr/pull/3958
