### ISSUE TITLE
Some SD versions of indexer can not be downloaded

### ISSUE THREAD

**Issue by s0picky** [Sonarr/Sonarr#3960]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Sonarr Version:** 3.0.3.924

**Operating System:** QTS 4.4.3.1421

**.net Framework (Windows) or mono (macOS/Linux) Version:** 6.8.0.105

**Link to Log Files (debug or trace):** https://drive.google.com/file/d/1PtQn2y-b8SRkO_77BMc184fp45X-KYCU/view?usp=sharing

**Browser (for UI bugs):**

**Comment by markus101** [comment]
I don't see any `360p` releases, either they're not returned (wrong categories) or parsing as Unknown. If you're still having issues open a thread on the forums/subreddit for support.
