### ISSUE TITLE
Asian Series not match to tvdb

### ISSUE THREAD

**Issue by kvtong93** [Sonarr/Sonarr#3962]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Sonarr Version:** v3 latest

**Operating System:** unraid dockrr

**.net Framework (Windows) or mono (macOS/Linux) Version:**

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**

### What problem are you looking to solve?

Asian Series not match TVDB, for example naoki hanzawa has alias hanzawa naoki, and all asian indexer using the hanzawa naoki, but in sonarr it doesnt reconized the alias

**Comment by bakerboy448** [comment]
This is not a sonarr issue.

Sonarr uses it's data from TVDB. If TVDB is incorrect or missing an alternative title, than TVDB needs to be updated.

This request will be closed once someone who has the power to can close it.

**Comment by kvtong93** [comment]
> This is not a sonarr issue.
> 
> Sonarr uses it's data from TVDB. If TVDB is incorrect or missing an alternative title, than TVDB needs to be updated.
> 
> This request will be closed once someone who has the power to can close it.

you don know what i mean, sonarr is mismatch with tvdb, the tvdb info is mismatch with sonarr in some asian series. And even if I changed something on tvdb, there is no response to sonarr ,never

**Comment by bakerboy448** [comment]
TVDB may be cached for up to 24hrs on skyhook (sonarr backend)

Again, sonarr only pulls from TVDB (and the XEM, but that’s not relevant for this)

If TVDB doesn’t have the name then Sonarr never will.  I’m not sure what’s confusing about this?

TVDB -> Sonarr 
NEVER Sonarr -> TVDB

**Comment by kvtong93** [comment]
> TVDB may be cached for up to 24hrs on skyhook (sonarr backend)
> 
> Again, sonarr only pulls from TVDB (and the XEM, but that’s not relevant for this)
> 
> If TVDB doesn’t have the name then Sonarr never will. I’m not sure what’s confusing about this?
> 
> TVDB -> Sonarr
> NEVER Sonarr -> TVDB

thank you for your reply and sorry for my english, what i mean is like I checked a series one month ago that it has correct alias on tvdb, but I still can't see it in sonarr v3 today, only one name on sonarr v3 . And I edited the english translate name for a chinese series but there is no effect, a week later, still the same name in sonarr, no change.

**Comment by Thirrian** [comment]
You're both wrong in the sense that it's not the alias on the tvdb or the cache.

This is covered in the FAQ: https://github.com/Sonarr/Sonarr/wiki/FAQ#why-cant-sonarr-import-episode-files-for-series-x--why-cant-sonarr-find-releases-for-series-x

**Comment by markus101** [comment]
Yup, aliases don't come from TVDB, see the FAQ for requesting one.

Next time please use the forums or subreddit for questions/support.
