### ISSUE TITLE
Broken Sorting in Interactive Search

### ISSUE THREAD

**Issue by csandman** [Sonarr/Sonarr#3964]
**Describe the bug**
In Sonarr V3 the sorting is broken for both manual season search and episode search.  Each time I click one of the column headers, the results appear not to change. However the list gets longer so it appears to be appending the sorted results to the bottom of the list but it does not seem consistent.

For example, in the season search, for certain shows it seems to duplicate the list but merge them in a way was a single result appears over and over again at the top of the list, once for each time I sort.

I have tried this for at least 5 or 6 shows and it was broken for all of them but I could not identify a consistent pattern for how it is broken.

**Screenshots**
Better Call Saul S01E01
![image](https://user-images.githubusercontent.com/9214195/93249029-af677180-f75e-11ea-82a7-8cb8760c1401.png)
Schitt's Creek S06
![image](https://user-images.githubusercontent.com/9214195/93249968-1afe0e80-f760-11ea-8d72-ff1d347a25d8.png)

**Logs**
No debug or trace files that apply to this as far as I am aware, let me know if there is something I am missing for this

**System Information**

 - Sonarr Version: 3.0.3.924-ls41 by linuxserver.io (Also occurred on version 3.0.3.913)
 - Operating System: Unraid 6.8.3
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34

**UI Bugs:**
 - OS: MacOS
 - Browser: Chrome
 - Version: 84.0.4147.135

**Additional context**
Nothing that I am aware of, drop a comment if more information is required!

**Comment by markus101** [comment]
How many results are you getting back from your indexers (debug logs will tell you how many results it's processing)?

I haven't been able to reproduce this behaviour (we've had similar reports before) in my testing, definitely going to need a consistent way to reproduce this to diagnose further.

**Comment by csandman** [comment]
I have looked through the debug log and can't figure out where to find the number of releases being processed.  However I attached my log file here for an interactive search of Game of Thrones S01:

[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/5233812/sonarr.debug.txt)

In case this helps at all, I only use torrent indexers through torznab and jacket.  Here is my list of indexers:
![image](https://user-images.githubusercontent.com/9214195/93371150-e18cd800-f81f-11ea-8133-b674894d74bb.png)

And currently Kick Ass Torrents is unavailable due to failures.

Please let me know where I can find the total releases being processed specifically if you still need that!  I'd like to help as much as I can but I've never done much debugging on it before.

**Comment by markus101** [comment]
It will log `Processing x releases` where `x` is the count of releases then for each release it processes is logs `Processing release y/x`.

**Comment by csandman** [comment]
Ok I went through the logs and found the first one (for Game of Thrones Season 01):

```
20-9-21 11:33:03.3|Info|DownloadDecisionMaker|Processing 225 releases
```

However in the following lines I couldn't find anything else saying `Processing release y/x`. I just saw lines like this:

```
20-9-21 11:33:03.3|Debug|DownloadDecisionMaker|Processing release 'Il trono di spade Game of thrones S01 07e01 67 Mux 720p H265 Ita Mp3 Eng Aac SoftSub Ita Eng' from '1337x'
```

I also realized that first debug file was a truncated version of the whole list so here is a combined log file of the whole process:

[sonarr.debug.0.txt](https://github.com/Sonarr/Sonarr/files/5256528/sonarr.debug.0.txt)

Please let me know if there is any other way I can help!  I am a React developer so if you need me to try anything locally I can give it a shot.

**Comment by markus101** [comment]
Very inconsistent, so far I haven't been able to reproduce, but have seen it before.

**Comment by cocokola** [comment]
I've reported this in the past as well.   Markus101, I believe it happens when there is a large number of results, I can get it consistently with my setup.  You just need at least a dozen individual indexers and search for a common show.

**Comment by enchained** [comment]
@markus101 I noticed that the bug still reproduces if you have 2 different indexers of one source - i.e. nyaa.si from sonarr and nyaa.si from jackett. The sorting doesn't work in that case even on the latest v3.0.4.1106.
