### ISSUE TITLE
Episode > History tab Tooltip is a bit unstable

### ISSUE THREAD

**Issue by austinwbest** [Sonarr/Sonarr#3965]
**Describe the bug**
Click on an episode
- Mouseover the media info icon under the details page & it works
- Mouseover the info icon under the history tab and it loses its mind

**Screenshots**
Reported by another user on Discord but is also happening on mine. 
https://discordapp.com/channels/383686866005917708/383688189941907459/755845679439413289

**System Information**

 - Sonarr Version: 3.0.3.927
 - Operating System: Windows 10

**Comment by markus101** [comment]
Almost 100% certain this is because of https://github.com/Sonarr/Sonarr/commit/0a66e86cccc29d7fef6da7876b3b761deb414648

@Qstick is this not an issue in Radarr?

**Comment by austinwbest** [comment]
Not QStick but Radarr doesn't have that mouseover. It is a clickable dialog in the history tab.
