### ISSUE TITLE
Import series from another Sonarr instance based on source Sonarr tags

### ISSUE THREAD

**Issue by onedr0p** [Sonarr/Sonarr#3966]
**Is your feature request related to a problem? Please describe.**
It would be great on sonarr(1) to tag a series and have it import into sonarr(2).

In sonarr(2) we can provide source tags to import from sonarrr(1) in the list settings.

**Describe the solution you'd like**
I want to import series from my other sonarr instance based on tags.

See Radarr PR which added this feature

https://github.com/Radarr/Radarr/pull/4900

**Comment by Qstick** [comment]
I'll pull this over when I get a chance, it was added to Radarr midway thru the Sonarr PR

**Comment by onedr0p** [comment]
Oh hai! No worries, figured I would open the issue 👍
