### ISSUE TITLE
Path isnt set to right path

### ISSUE THREAD

**Issue by moom0o** [Sonarr/Sonarr#3967]
**Describe the bug**
When I set my path in sonarr for a specific show to G://sonarr it downloads to F://torrent in qbittorrent... Which causes qbittorrent to throw a system cannot find the path specified error.

**Screenshots**
https://i.imgur.com/3sv4RnL.png
https://i.imgur.com/AYjVdOs.png
**Logs**
Link to debug or trace log files.
none
**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Windows 10

**Comment by bakerboy448** [comment]
Support requests to the forums, subreddit, or discord.

Unlikely to be a bug, but would need trace logs regardless.

**Comment by moom0o** [comment]
ok, joined discord
