### ISSUE TITLE
Import error does not provide actionable feedback

### ISSUE THREAD

**Issue by gimpyestrada** [Sonarr/Sonarr#3970]
**Describe the bug**
I'm using the import screen to bring in a bunch of new shows.  I get the yellow triangle/exclamation mark that says Import Errors and the detail is "A series with this ID was not found."  It does not tell me which show has the error so I have no idea how to resolve the issue.

I go to the Events and I see: "tvdbid 79141 was not found, it may have been removed from TheTVDB."  Still nothing that I can use to help me solve the problem.

I even turned on Debug level logging and there is still  nothing useful to help me resolve the problem.

**System Information**

 - Sonarr Version: 3.0.3.928
 - Operating System: Ubuntu 20.04
 - mono (macOS/Linux) Version: 6.12.0.90

**Comment by gimpyestrada** [comment]
I turned on Trace and this is all I get:

20-9-18 12:41:31.7|Trace|HttpClient|Req: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/79141
20-9-18 12:41:31.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
20-9-18 12:41:32.2|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/79141: 404.NotFound
{"message":"NotFound","description":"thetvdb.com does not have a series with the tvdbid 79141, it may have been removed."} (484 ms)
20-9-18 12:41:32.2|Error|AddSeriesService|tvdbid 79141 was not found, it may have been removed from TheTVDB.
20-9-18 12:41:32.2|Trace|SonarrErrorPipeline|Handling Exception
20-9-18 12:41:32.2|Warn|SonarrErrorPipeline|Invalid request Validation failed:
 -- TvdbId: A series with this ID was not found
20-9-18 12:41:32.2|Trace|Http|Res: 15138 [POST] /api/v3/series/import: 400.BadRequest (536258 ms)
20-9-18 12:41:32.2|Debug|Api|[POST] /api/v3/series/import: 400.BadRequest (536258 ms)


Still not sure WHICH title is bad.

**Comment by markus101** [comment]
That ID is linked to a movie: https://www.thetvdb.com/movies/the-trouble-with-spies

Not sure how you could even attempt to import using that ID since it shouldn't come back as a search result to begin with.

**Comment by flthyrich** [comment]
Same thing is happening with lists. If you have a series on trakt that has been removed from the TVDB, the list importing fails.
