### ISSUE TITLE
Series->Manual File Import should not auto-select files in Extras folder

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#3971]
**Describe the bug**
When using Series->Manual File Import in Sonarr v3. You get a list of unimported files.
If you have a Extras folder, then the files in that folder are parsed and it auto-selects them for import.

Expected would be that they are deselected by default, thus allowing the user to select and forcibly import.

**Screenshots**
![image](https://user-images.githubusercontent.com/6383890/93675443-3b093700-faac-11ea-8f97-7952f2b001af.png)

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 3.0.3.894
 - Operating System: Ubuntu
 - .net Framework (Windows) or mono (macOS/Linux) Version: 6.8

**UI Bugs:**
 - OS: Windows
 - Browser: Chrome
 - Version: 85

**Comment by bakerboy448** [comment]
Also selects any samples I believe as well.

basically only unknown series/season/episodes are not selected

**Comment by Taloth** [comment]
samples shouldn't exist in the series folder though.

**Comment by Taloth** [comment]
Partial fix in https://github.com/Sonarr/Sonarr/commit/034ab0378fea5aeaba732781dbc9a58f0b183d6e

Extras folder is now excluded from the Manual File Import list entirely.

Everything is still selected as normal. I didn't want to tweak the UI code to deselect files with rejections.
