### ISSUE TITLE
VOSTFR removal from language parsing introduces issues to grab those

### ISSUE THREAD

**Issue by Hakujou** [Sonarr/Sonarr#3977]
Hello,

Since Sonarr 3.0.3.924, VOSTFR is no longer included in French language, as it's a subtitle tag.
However, this introduces issues: We now can't get subtitles releases only for a certain type of content.

We can't customize language profiles, so we can't tweak here, we must use "English". 
We can use release profiles to force "vostfr" string, but then if we want French-made content or releases which doesn't contain "vostfr" (subfrench, or even multi-subs releases like Erai-raws on Nyaa), we cannot.

Tagging is an option, but it has its own issues (almost all of my content needs vostfr, so I'd need to tag everything, not to mention Ombi/Auto-import would get broken since it would add TV shows/movies without vostfr tag).

So now we have no way of having sub-only releases for content conveniently. Either all of our content needs to have "VOSTFR", or we get english releases (preferred in release profile is not a good option, we'd still get english releases since VOSTFR always come later).

There is three fixes I can think of:

- Readd VOSTFR in French language parsing. If people wants french-dubbed/french-made content, they only need to blacklist "vostfr" and "subfrench", since it always means "subbed".
- Add a way to have a release profile overriding an other one. This way we could require vostfr by default, but be able to override it using some tags (for instance, a tag "erai" that would require "Erai" in release name but NOT vostfr).
- Add a "French Subs" language or equivalent (<-- Best "no comprise" option IMO)

Please let me know if you need more details/have questions.

**Comment by markus101** [comment]
> We can use release profiles to force "vostfr" string, but then if we want French-made content or releases which doesn't contain "vostfr" (subfrench, or even multi-subs releases like Erai-raws on Nyaa), we cannot.

A single release profile that requires all 3 of those terms would be successful if any exist. (`The release must contain at least one of these terms (case insensitive)`).

> Ombi/Auto-import would get broken since it would add TV shows/movies without vostfr tag).

Sonarr supports adding tags when the series is added, including when adding from import lists, if Ombi can't add tags currently then that's something they could add. There is also this request: https://github.com/Sonarr/Sonarr/issues/3870

> Either all of our content needs to have "VOSTFR", or we get english releases (preferred in release profile is not a good option, we'd still get english releases since VOSTFR always come later).

Preferred in release profiles + delay profiles (depending on the timing could also help).

> Readd VOSTFR in French language parsing. 

This is not going to happen.

> Add a way to have a release profile overriding an other one

The only way to do this be be by using different tags.

> Add a "French Subs" language or equivalent (<-- Best "no comprise" option IMO)

This would perform very similar to how tags + release profiles would work, this is something we've talked about, but have no short term plans for it.
