### ISSUE TITLE
Port already in use when using an URL Base

### ISSUE THREAD

**Issue by WoRsTiG** [Sonarr/Sonarr#3978]
The Sonarr.Console crashes when enabling a URL Base for reverse proxy.
When i set the URL Base to /sonarr, sonarr fails to start up and results in an 'EPIC FAIL!'
It seems to be caused by attempting to bind to 2 listening urls on the same port while 1 is expected...:

> .....
> [Info] OwinHostController: Listening on the following URLs:
> [Info] OwinHostController:   http://localhost:8989/sonarr/
> [Info] OwinHostController:   http://localhost:8989/
> [Info] SonarrBootstrapper: Starting Web Server
> 
> [Fatal] ConsoleApp: EPIC FAIL!
> 
> [v3.0.3.928] NzbDrone.Host.Owin.PortInUseException: Port 8989 is already in use, please ......

**Logs**
[Sonarr_Console.log](https://github.com/Sonarr/Sonarr/files/5267729/Sonarr_Console.log)

**System Information**

 - Sonarr Version: 3.0.3.928
 - Operating System: Server 2019 Standard (10.0.17763.1339)
 - .net Framework 4.7.03190

**Comment by Taloth** [comment]
> It seems to be caused by attempting to bind to 2 listening urls on the same port while 1 is expected...:

No it isn't. windows has a http.sys subsystem where urls need to be reserved for non-admin accounts to be allowed to listen.
Run sonarr _ONCE_ as administrator and it'll register/reserve the url.

**Comment by WoRsTiG** [comment]
@Taloth  Thanks for the info, running once as administrator fixed it.
Maybe add an extra info line on the general settings page explaining this when running on an non admin account.
