### ISSUE TITLE
Issue with duplicate series titles

### ISSUE THREAD

**Issue by onedr0p** [Sonarr/Sonarr#3981]
**Env**
Linux, Docker, 3.0.3.928

**Steps to reproduce**

Some weird bug here, add `Utopia (2013)` and then try to add the new Amazon series `Utopia (2020)`, this will fail with the error message:

> Title slug 'utopia' is in use by series 'Utopia'

I know this maybe an issue with TVDB, because there is already a completely different series with the name `Utopia (US)`. But I wanted to raise an issue incase TVDB refuses to change it and others came across this problem. In the meantime, is there any workaround to get this new series added w/o deleting the old one?

![image](https://user-images.githubusercontent.com/213795/94364822-1dcefc80-009a-11eb-9bf6-669a9b0205c1.png)

**Comment by Taloth** [comment]
Yeah, create ticket for tvdb, they don't allow series to have the same title. I seem to recall that tvdb rules say it should be named `Utopia (US) (2020)`, or `Utopia (2020)`. Probably the second since it's not a spinoff of the original Utopia.

If they refuse we can patch the slug in skyhook.

**Comment by markus101** [comment]
Does this actually require a ticket? Or just someone needs to edit the translation?

If it requires a ticket and they refuse we’d also need to add aliases to avoid conflicts when looking up by the clean title.

**Comment by markus101** [comment]
I edited the translation and it should be good whenever their API cache expires (24+ hours). We can re-open if there is something additional to do.

**Comment by Taloth** [comment]
Ok. I suggested the ticket, because I don't know for sure what name they want and changing it twice is probably not a good idea. They're not going to refuse. They never allowed duplicate names.   
Now let's hope that scene uses Utopia.2020. :smile:

**Comment by markus101** [comment]
With a ticket who knows when they'd actually fix it. So far Utopia 2020 seems to be used exclusively.

**Comment by onedr0p** [comment]
I'll try to add it later, thanks guys! I agree I'd rather not deal with those folks.
