### ISSUE TITLE
Allow for setting series type when using import lists

### ISSUE THREAD

**Issue by M0UL** [Sonarr/Sonarr#3982]
**Describe the problem**
when using trakt list import function. there is no way to set the series type.

**Describe any solutions you think might work**
add the abilty to set the series type in settetings of the trakt list.  of set the series type automatically.

**Comment by xfouloux** [comment]
Hi,

in the sonarr import list too please =)

**Comment by markus101** [comment]
The settings are the same for both, so adding for one will add for the other.
