### ISSUE TITLE
Check For Finished Downloads Interval

### ISSUE THREAD

**Issue by Mitnick84** [Sonarr/Sonarr#3983]
Hi, radarrv3 has a "Check For Finished Downloads Interval" option in the Download Clients Section. 
I need this feature also for SonarrV3. I have a Server with Hardwareraid and 2x3TB HDDs in RAID0. The Problem is the Raid is not fast enough when Sonarr download via rtorrent a big Scene Packet Series Season like 100GB. 
rtorrent unpack this big files in a extra folder in that Sonarr looks. But Sonarr grabb this extracted files in the same time when rtorrent extract the parts. rtorrent is not done and sonarr imported the litle extracted part and it say the episode is complete imported.

In radarr i can set a check Interval like 30 Minutes and the Problem is solved.

Sory for my Poor English, i hope you can understand the Problem.

**Comment by markus101** [comment]
We have no plans for adding this feature. It also would not prevent Sonarr from importing downloads before the unpacking completes, as it could run 10 seconds after the unpacking starts.

**Comment by Mitnick84** [comment]
Hm, okay. But can you not make a feature that compare the filesize, timestamp after import? I have so many corrupt episodes when sonarr copy files.
