### ISSUE TITLE
Season level monitoring options

### ISSUE THREAD

**Issue by austinwbest** [Sonarr/Sonarr#3987]
Season level monitoring.. So it happens sometimes a season gets un-monitored for whatever reason. I had the Peppa Pig S06 unmonitored as an example

52 episodes total in the season, I have 39 of them

So i want to monitor the missing ones without clicking 20 times or monitoring all an unchecking the ones i have (this is done on some episodes so they dont get stepped on by bad naming/XEM mapping)

When i click on the monitor icon at the series level, can it be a tooltip menu with

* Monitor All
* Monitor Missing
* Monitor New

Or a right click context menu with those options.. Doing this at the season level instead of series level because for some series changes are not needed across the board

**Comment by austinwbest** [comment]
Yea, I meant the season level monitored icon, not series. So a user can pick what to monitor in the season instead of doing 50 episodes when I don't need that.

Anyways, got the answer so that sums it up.

**Comment by markus101** [comment]
You can do range clicks too, click, then shift click and it'll update everything in between (inclusive). Unless it's all small groups of episodes that should really cut it down.

**Comment by markus101** [comment]
No plans for per season monitoring options at this time, but opened https://github.com/Sonarr/Sonarr/issues/3991 for series level ones.
