### ISSUE TITLE
crash after update

### ISSUE THREAD

**Issue by yodatak** [Sonarr/Sonarr#3989]
### System Information/Logs

**Sonarr Version:** cant run the program to know it but i do the latest update in the webinterface of sonaar

**Operating System:** Fedora 32

**.net Framework (Windows) or mono (macOS/Linux) Version:**Mono JIT compiler version 6.6.0.166

**Link to Log Files (debug or trace):**
/usr/bin/mono --debug /opt/Sonarr/Sonarr.exe -nobrowser -data=/var/lib/sonarr

Unhandled Exception:
System.BadImageFormatException: Could not resolve field token 0x04000004, due to: Could not load type of field 'NzbDrone.RuntimePatches.RuntimePatchBase:_harmony' (0) due to: Could not load file or assembly '0Harmony, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:/opt/Sonarr/Sonarr.RuntimePatches.dll type:RuntimePatchBase member:(null)
File name: 'Sonarr.RuntimePatches'
  at NzbDrone.Console.ConsoleApp.Main (System.String[] args) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Console\ConsoleApp.cs:27
[ERROR] FATAL UNHANDLED EXCEPTION: System.BadImageFormatException: Could not resolve field token 0x04000004, due to: Could not load type of field 'NzbDrone.RuntimePatches.RuntimePatchBase:_harmony' (0) due to: Could not load file or assembly '0Harmony, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:/opt/Sonarr/Sonarr.RuntimePatches.dll type:RuntimePatchBase member:(null)
File name: 'Sonarr.RuntimePatches'
  at NzbDrone.Console.ConsoleApp.Main (System.String[] args) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Console\ConsoleApp.cs:27

**Comment by bakerboy448** [comment]
Github is for bug and feature requests...this appears to be a support request... ->> discord, reddit, irc, or the forums

What do the updater logs say?
Initial thoughts are it looks like the install got borked, you can likely install over and you'll be good.

Any additional support, pop on over to one of the proper places for support.

**Comment by markus101** [comment]
Closing, but will re-open if there is a bug we need address here.
