### ISSUE TITLE
Series Monitoring Option On Series Details Page

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#3991]
**Describe the problem**
Only Series Editor (Mass Edit) and add/import series have the option to specify which episodes are monitored.

**Describe any solutions you think might work**
Add a similar option to the series details page.

**Comment by RobinDadswell** [comment]
@markus101 I've started looking at this, just figuring my way around the Java script! Do you assign things here?

**Comment by markus101** [comment]
Yeah, makes sense to link it to you.
