### ISSUE TITLE
About the "S01" with some normal situations again

### ISSUE THREAD

**Issue by reprover** [Sonarr/Sonarr#3993]
First of all, thank you very much for this project, but in the process of using it, I can hardly find any resources. I carefully observed the search keywords.
First, I mentioned a suggestion about whether to add "S1" or "Season 01" before. You said that in order to prevent the entire TV series from being searched, this feature will not be added. However, in addition to American TV series, many TV series are one season, so the "S1" keyword will not be added to the resource list. So I think many people like me want to control whether to use this keyword when searching.
The second situation, (by the way, all my resources are searched and downloaded by myself) Each episode of <Detective Conan> is named from 001-9xx, and the results of your search are divided into seasons by year. Fortunately, sonarr can allocate episodes through calculations. But during the serialization every Saturday, the latest episodes are not searched. Because your search keyword is "Detective Conan S01E965"... I don’t know if it’s my configuration problem or yours here, but in bt sites, it’s basically determined by episodes, similar to this Doraemon is also the case. But I think this may be able to control the results by controlling the keywords of S01?
So whether to consider adding this option, let us control whether to use keywords like S01 for different TV series?
(By the way, I'm sorry I am not a C# programmer, otherwise I can give you a suitable PR instead of complaining here)

**Comment by markus101** [comment]
Still no plans for searching without a season number.

For releases that use absolute episode numbers (anime) make sure the series type is set appropriately. If you have other questions or need support please open a thread on the forums or subreddit.
