### ISSUE TITLE
The Download Station connector moves the file while seeding

### ISSUE THREAD

**Issue by VincentMasselis** [Sonarr/Sonarr#3997]
### Infos
Sonarr Version: 2.0.0.5344

Operating System: DSM 6.2.3-25426 Update 2

mono Version: 5.20.1.34

### Context
I'm using Download Station to manage my torrents and I use a ratio based torrent provider to find the shows I'm looking for. All the apps Sonarr, Download Station and Deluge I mention below are installed on the same Synology device.

### The bug
I've seen that, when I'm using Download Station, my torrent are always moved from my `Download` folder to my `TV Shows` folder instead of being hard-linked or copied when the download is complete. Even if I set a minimal ratio and/or share time into Download Station or If I enable or disable `Use Hardlinks instead of Copy`, **my files are always moved** which block my torrent from being uploaded to my connected peers.

If I switch from Download Station to Deluge on the same synology, my files are correctly hard-linked and I don't face this bug anymore.

### Possible causes
I've found that, the root problem could be the way the field `CanMoveFiles` is computed. When I use Deluge, this field is computed this way:
```C#
item.CanMoveFiles = item.CanBeRemoved =
                    torrent.IsAutoManaged &&
                    torrent.StopAtRatio &&
                    torrent.Ratio >= torrent.StopRatio &&
                    torrent.State == DelugeTorrentStatus.Paused;
```
[LINK Here](https://github.com/Sonarr/Sonarr/blob/42343d528372c494b297e5c84125f7bdb6ab4eec/src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs#L175)

But for Download Station it uses the `IsCompleted` method which is write this way:
https://github.com/Sonarr/Sonarr/blob/42343d528372c494b297e5c84125f7bdb6ab4eec/src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs#L209

Git blame reveals this commit https://github.com/Sonarr/Sonarr/commit/ea1616586fc38d4f24e33bcb48c218981a1ec2d6. In this commit @Taloth say `Import from torrent Download Station should move since DS maintains an internal copy for seeding.`. It's partially true, DS really keeps an internal copy of the files BUT only when seeding, If seeding stops (because there is no connected peer or an internet connection failure), DS release the link to the internal copy and definitively loose the reference to the file because the file were moved by Sonarr. Even if the file reference is lost, DS doesn't fire any error, it keeps the torrent in the `Seeding` state but the seeding speed is always set to `0,0kb/s` if there is connected peers.

### My solution
IMO, the DS connector should not move the files if the torrent is in the status `Seeding` because the torrent is still active at this moment, it should wait for the `Finished` status ([DOC HERE go p.41](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/DownloadStation/All/enu/Synology_Download_Station_Web_API.pdf)) because that state is reach when the ratio / share time conditions are meet and the torrent is inactive.

**Comment by markus101** [comment]
Please use the template when filing issues, you're missing a lot of important information.

With Download Station Sonarr moves the files because Download Station has already made a hardlink from the original download location to the location they expose publicly. Previous issue reporting this was a bug https://github.com/Sonarr/Sonarr/issues/2520 and the original reason this was done https://github.com/Sonarr/Sonarr/issues/1764 unless this is a recent change they've documented this is working as we expect it to for their configuration.

**Comment by VincentMasselis** [comment]
Done

**Comment by Taloth** [comment]
@margaale I don't want to pull you into this discussion willy nilly (feel free to unsubscribe from notifications again) but is this behavior you've seen as well? Specifically: Does DS remove the temporarily hardlinked files in `@download` when there are no active peers?
Could it be changed DS behavior in recent DS versions? I mean, we implemented it 3 years ago.

**Comment by VincentMasselis** [comment]
I've added this comment into my first message about the behavior of DS when the reference is lost: "Even if the file reference is lost, DS doesn't fire any error, it keeps the torrent in the Seeding state but the seeding speed is always set to `0,0kb/s` if there is connected peers."

**Comment by margaale** [comment]
Hi @Taloth, how you been doing so long? Don't worry for the mention, however i don't have time for investigating this issue right know and I really don't remember about the behaviour you are asking me, sorry. Feel free to ask whenever you want

**Comment by VincentMasselis** [comment]
Hey everyone ! Any decision was make about this bug ?
