### ISSUE TITLE
Series View Overview - Not showing size on disk column

### ISSUE THREAD

**Issue by gold007eye** [Sonarr/Sonarr#4001]
## Bug Report
When selecting Series -> View -> Overview then going to Options and checking off "Show Size on Disk" the column never shows up.  I have tried this with All poster sizes as well (Small, Medium, Large).  I have also tried this with selecting no other options and a few options to see if that made a difference to no avail.

### System Information/Logs
Sonarr Version: 3.0.3.938
Operating System: Windows 7
.net Framework (Windows): 4.8.03761

Log Files:
Nothing showing in Debug or Normal Log files.

Browser (for UI bugs): FireFox Quantum 62.0.3 (64-bit)

### Additional Information
I'm not sure if it helps, but this specific option seems to work on Radarr  with no issues.

**Comment by markus101** [comment]
Fixed in https://github.com/Sonarr/Sonarr/commit/d105dd47e02b9ed3616edf31d77623ca2ceb791e
