### ISSUE TITLE
Add button to make default name scheme more linux friendly (replace spaces with whatever)

### ISSUE THREAD

**Issue by stormsz** [Sonarr/Sonarr#4002]
**Is your feature request related to a problem? Please describe.**
I think i can speak for 99.999% linux users that having file names with spaces is a pain to deal with and to read.
Stuff like: `'Spider\ Man: \Bla \bla'` instead of `Spider.Man:Bla_bla`

**Describe the solution you'd like**
A simple Check Box to automatically replace all the spaces of a file with whatever you guys are comfortable with, the ideal solution would be some sort of option, so we could chose a more normal scheme like `.` `-` `_`

- [ ] Optimize names for Unix like systems

**Describe alternatives you've considered**
Right now most people have to manually edit the naming scheme of the movies in order to replace spaces with dots or whatever. Granted that they only have to do this 1 time, but having this simple option to cater to the users that find the default name scheme good would be great. 

**Additional context**
Great project and great support team! Thanks.

**Comment by markus101** [comment]
No plans for this, all token helpers already have the option to insert using the chosen format, editing the format will need to be done once manually.
