### ISSUE TITLE
Season shows 'No aired episodes' if season is monitored but no episodes are

### ISSUE THREAD

**Issue by non-bin** [Sonarr/Sonarr#4003]
To reproduce turn on monitoring for a season, then individually un-monitor all episodes individually within it.
The season displays `No aired episodes` where it should display something like `No monitored episodes`, or automatically un-monitor the season

**Comment by non-bin** [comment]
Is there any reason to have a season un-monitored with all episodes monitored or vice-versa?

**Comment by markus101** [comment]
Unmonitoring all episodes and monitoring the season is valid if you only want the episodes that air in the future, but aren't yet in the list.

The tooltip is improved in v3, no plans to make further changes at this time.
