### ISSUE TITLE
Size on disk per episode in series details

### ISSUE THREAD

**Issue by g4m3r7ag** [Sonarr/Sonarr#4004]
**Describe the problem**
The total size of the season showing up next to the Season has been a big help for finding seasons which may not have great quality releases grabbed, but if the size on disk would also show for each episode in this screen it would make it quicker to tell if there's a bad episode in the middle of a season. Currently you have to click on each episode to see it's file size. 

![Screenshot from 2020-10-06 01-42-00](https://user-images.githubusercontent.com/46694420/95163108-2cda3c80-0775-11eb-98db-dcb71661e4e8.png)

**Describe any solutions you think might work**
A clear and concise description of any solutions or features you've considered.

**Additional context**

**Comment by markus101** [comment]
You can already do this. Hit the gear (above the search icon for the episode) and show that column

**Comment by g4m3r7ag** [comment]
Over a year on V3 and never realized that was clickable. Thank you.
