### ISSUE TITLE
HTTP URI validator not accepting valid URIs

### ISSUE THREAD

**Issue by mueslo** [Sonarr/Sonarr#4005]
https://github.com/Sonarr/Sonarr/blob/7d06e5d6842e6b81b8d4b4b0ab94f5bfba21cae6/src/NzbDrone.Common/Http/HttpUri.cs#L11

A URL with two subsequent forward slashes in the path component should validate, but erroneously doesn't.

**Comment by markus101** [comment]
While it's technically valid, it's based on the using an existing protocol, but depending where it's used it may not be useful. Where are you trying to use it?

**Comment by mueslo** [comment]
Some torznab providers are not perfectly configured and will return URLs like "https://domain.org//torrents.php?arg=whatever". Basically all web servers will still process this request normally as if there is a single slash.

**Comment by mueslo** [comment]
replacing the `[^/?#\r\n]+` part with `[^/?#\r\n]*` should probably be enough to fix it
