### ISSUE TITLE
Upgrade from v2 to v3 changes selected account from the Windows Service

### ISSUE THREAD

**Issue by redfellow** [Sonarr/Sonarr#4006]
I previously set up Sonarr to run as local system account so it may access network shares.

Upgrading to V3 changed it back to "run as this user".

Took me quite a while to recall why Sonarr suddenly could not see remote mapped files, so maybe this is something that could be improved in v2 to v3 the upgrade path.

**Comment by cocokola** [comment]
Similar to 4006?

**Comment by markus101** [comment]
LocalSystem was the default user in v2, which is terrible for security (LocalSystem is more power than an admin user). We'll mention that network shares will require the user to be changed.

@cocokola this is #40056, which other issue were you thinking of?

**Comment by cocokola** [comment]
Sorry for the late reply.  It was closed properly.
