### ISSUE TITLE
Some drop-downs not expanding

### ISSUE THREAD

**Issue by jpdsceu** [Sonarr/Sonarr#4009]
**Describe the bug**
Some drop-downs are unable to be expanded. Such as the dropdown in Language Profiles or Upgrade Until.
The layout of those dropdowns are also different, the right arrow is more to the left compared to other drop-downs.

**Screenshots**
![image](https://user-images.githubusercontent.com/7014736/95583483-7c05c300-0a3c-11eb-8300-27871f2bd176.png)

![image](https://user-images.githubusercontent.com/7014736/95583939-31387b00-0a3d-11eb-8a26-5c233fa6d324.png)

![image](https://user-images.githubusercontent.com/7014736/95584051-5af1a200-0a3d-11eb-8bbf-eb20222a4693.png)

**Logs**
Logs don't show any error

**System Information**

 - Sonarr Version: 3.0.3.965
 - Operating System: Windows 10

**UI Bugs:**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 85.0.4183.121

**Additional context**
Tried also on FireFox and Edge, same issue.

If more information is needed; let me know.

**Comment by markus101** [comment]
I am able to reproduce this issue  with 3.0.3.964, but I'm not able to reproduce in 3.0.3.965, which includes this fix for this issue: https://github.com/Sonarr/Sonarr/commit/e8854a26752409d251344e8c2326e025a517cfdc

**Comment by jpdsceu** [comment]
Is fixed with 3.0.3.965, thank you.
