### ISSUE TITLE
Breaking change to webhooks

### ISSUE THREAD

**Issue by rg9400** [Sonarr/Sonarr#4010]
**Describe the bug**
It seems that in version 3.0.3.966, WebhookEventType was changed to enum, whereas it was a string before. All existing webhooks are coded to expect strings, so this completely breaks them all. I'm not sure if this was intentional or not, so wanted to create an issue first before modifying the webhook triggers.

From commit https://github.com/Sonarr/Sonarr/commit/ee32829cdb90b9554f4dbfad185eebc2451cb5de

```cs
    public enum WebhookEventType
    {
        Test,
        Grab,
        Download,
        Rename,
        Health
    }
```

EDIT: On further testing, it seems like events shifted to lowercase, so "Test" became "test", "Download" to "download", etc. I can make my webhook case insensitive, which does seem to fix the issue at first glance, but just FYI as it may break other integrations.

**System Information**

 - Sonarr Version: 3.0.3.967

**Comment by markus101** [comment]
We serialize all enums to camel case strings, in the future we'll change it to camel case, so changing it to be case insensitive is a good idea.
