### ISSUE TITLE
The Spanish Princess - Sonarr thinks this is in Spanish

### ISSUE THREAD

**Issue by infomofo** [Sonarr/Sonarr#4012]
**Describe the bug**
I believe that the bug originally filed in https://github.com/Sonarr/Sonarr/issues/3106 which was marked as fixed is active again.

The series is in English but has the word Spanish in the title. It avoids automatically downloading on my system which has an English Language preference with the error:

```
Release Rejected

- English is wanted, but found Spanish
```

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Ubuntu
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34

**Additional context**

**Comment by markus101** [comment]
This is fixed in v3, it will not be fixed in v2.
