### ISSUE TITLE
THETVDB data not updated 

### ISSUE THREAD

**Issue by felho001** [Sonarr/Sonarr#4017]
Hi can you tell me why not updated this tv Shows sonarr? The new episods are there tvdb 1 week ago but not update.

Sonarr run synology Sonarr version?: 2.0.0.5344 - Mar 13 2020
synology 415+
Thetvdb data THETVDB.COM SERIES ID372014

<img width="942" alt="THETVDB-mintaapak" src="https://user-images.githubusercontent.com/45117257/96092129-bc48c380-0eca-11eb-8e32-7022597da462.png">
<img width="949" alt="sonarr" src="https://user-images.githubusercontent.com/45117257/96092133-bd79f080-0eca-11eb-8f1e-53ce7aa6a7ee.png">

**Comment by Taloth** [comment]
Should be ok in an hour or so. One of the episode titles disappeared which triggers a security mechanism in our proxy (tvdb api has been borked in the past, causing episode titles to suddenly disappear during those periods).

**Comment by felho001** [comment]
> Should be ok in an hour or so. One of the episode titles disappeared which triggers a security mechanism in our proxy (tvdb api has been borked in the past, causing episode titles to suddenly disappear during those periods).

Super know it works thanks.
