### ISSUE TITLE
Lostfilm Indexer categories not working from Sonarr

### ISSUE THREAD

**Issue by stasivanov** [Sonarr/Sonarr#4018]
**Describe the bug**
On a version 3.0.4.982, Lostfilm indexer doesn't work in Sonarr. However it DOES work in Jacket. I have played a bit around it, and the request without categories ids returns some results. However if we pass those default categories ids to the url to Jacket, it tells that Lostfilm doesn't allow this type of request.

**Logs**
```
20-10-15 12:56:36.6|Debug|Api|[GET] /api/v3/config/indexer: 200.OK (3 ms)
20-10-15 12:56:36.6|Debug|Api|[GET] /api/v3/indexer: 200.OK (43 ms)
20-10-15 12:56:37.5|Debug|Api|[GET] /api/v3/indexer/schema: 200.OK (27 ms)
20-10-15 12:56:44.4|Debug|Api|[POST] /api/v3/indexer/action/newznabCategories: 200.OK (13 ms)
20-10-15 12:56:56.1|Debug|Torznab|Downloading Feed http://192.168.1.70:9117/api/v2.0/indexers/lostfilm/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100
20-10-15 12:56:56.2|Warn|Torznab|Unable to connect to indexer

[v3.0.4.982] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: lostfilm does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported.
  at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000b8] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:42 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\RssParser.cs:55 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00052] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:308 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00044] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:342 

20-10-15 12:56:56.2|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
20-10-15 12:56:56.2|Debug|Api|[POST] /api/v3/indexer: 400.BadRequest (59 ms)
20-10-15 12:56:57.6|Debug|Api|[GET] /api/v3/health: 200.OK (2 ms)
20-10-15 12:56:57.6|Debug|Api|[GET] /api/v3/system/status: 200.OK (4 ms)
20-10-15 12:56:57.7|Debug|Api|[GET] /api/v3/diskspace: 200.OK (104 ms)
20-10-15 12:56:58.9|Debug|Api|[GET] /api/v3/log/file: 200.OK (4 ms)
```

**System Information**

 - Sonarr Version: 3.0.4.982
 - Operating System: LibreElec 9.2.4

**Additional context**
Test and Search in Jacket works just fine.

**Comment by Taloth** [comment]
What categories does it support? They should be visible in the dropdown.

**Comment by stasivanov** [comment]
In the Jacket it only shows this one 
<img width="583" alt="Screenshot 2020-10-15 at 13 09 05" src="https://user-images.githubusercontent.com/1454702/96109731-a269a980-0ee7-11eb-9973-c2a4034e3feb.png">

But to be honest, I don't really remember if that was such all the time, or smth was changed recently. For sure I see that this indexer was working on Tuesday still, cause it downloaded some series to me from it. 

And for the categories when I add it to the Sonarr, I see this list, but from what I understand it's just a default list, isn't it. 
<img width="498" alt="Screenshot 2020-10-15 at 13 11 48" src="https://user-images.githubusercontent.com/1454702/96110045-fffdf600-0ee7-11eb-87e7-fd83df902dd4.png">

**Comment by stasivanov** [comment]
Lostfilm recently moved to a new domain, maybe that's an issue. Please let me know if I can provide more information to help this issue be fixed.

**Comment by Taloth** [comment]
Could be the default, or the actual one provided by jackett.

Check `http://192.168.1.70:9117/api/v2.0/indexers/lostfilm/results/torznab/api?t=caps` for the raw list.

**Comment by stasivanov** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<caps>
  <server title="Jackett" />
  <searching>
    <search available="yes" supportedParams="q" />
    <tv-search available="yes" supportedParams="q,season,ep" />
    <movie-search available="yes" supportedParams="q" />
    <music-search available="no" supportedParams="" />
    <audio-search available="no" supportedParams="" />
    <book-search available="no" supportedParams="q" />
  </searching>
  <categories>
    <category id="2000" name="Movies">
      <subcat id="2010" name="Movies/Foreign" />
      <subcat id="2020" name="Movies/Other" />
      <subcat id="2030" name="Movies/SD" />
      <subcat id="2040" name="Movies/HD" />
      <subcat id="2045" name="Movies/UHD" />
      <subcat id="2050" name="Movies/3D" />
      <subcat id="2060" name="Movies/BluRay" />
      <subcat id="2070" name="Movies/DVD" />
      <subcat id="2080" name="Movies/WEBDL" />
    </category>
  </categories>
</caps>
```
Just in case, Lostfilm is mostly for the series. Not sure there are movies there. But anyway. It just looks strange to me that they called it "Movies". But maybe it's just a typo or mistake, and Movies/UHD would return series actually. Nevermind :)

I also tested the link (that Sonarr fails on it) and it works fine without categories parameters at all. But obviously not sure that's a good fix.

**Comment by Taloth** [comment]
Ask on the Jackett support channel whether it should be TV, or both. They'd be able to change it on their end.

In the past in Sonarr you could manually type category numbers, we changed that to the dropdown coz it's way more user friendly but we're also filtering out the Movies/PC/etc categories for convenience.

What I don't understand is that you're seeing the default (fallback) list, instead of an empty one.

**Comment by stasivanov** [comment]
Ah yes, if I put url first and then open dropdown for the categories, then it's empty. But it still puts 5030 5040 as default categories. I will contact Jackett support as well

**Comment by stasivanov** [comment]
While waiting for the response from Jackett support, can you plz describe what's the issue more detailed? So, they called categories with `Movies` prefix, while Sonarr filter those out? Or why it's actually Jackett issue and not Sonarr?

**Comment by Taloth** [comment]
It's twofold:
- Since recently we changed the comma separated category input to a dropdown containing the categories specified by the indexer capabilities. We filter out Movies categories because Sonarr doesn't do movies, or games or books etc.
(In this case it'd be nice to show the full list of categories if the filtered list is empty, but that's just bonus points.)
- Jackett specifies that this indexer only has a Movies category. That's probably wrong, it either needs both or just Series.
Presumably LostFilm has no categories at all so _anything_ will do.

**Comment by stasivanov** [comment]
Good. Fixed on Jackett side

**Comment by stasivanov** [comment]
However, with a new fix in Jackett it works fine, but the categories list still not appear. And I see an empty list on categories dropdown. 
```
<?xml version="1.0" encoding="UTF-8"?>
<caps>
  <server title="Jackett" />
  <searching>
    <search available="yes" supportedParams="q" />
    <tv-search available="yes" supportedParams="q,season,ep" />
    <movie-search available="no" supportedParams="q" />
    <music-search available="no" supportedParams="" />
    <audio-search available="no" supportedParams="" />
    <book-search available="no" supportedParams="q" />
  </searching>
  <categories>
    <category id="5000" name="TV">
      <subcat id="5010" name="TV/WEB-DL" />
      <subcat id="5020" name="TV/FOREIGN" />
      <subcat id="5030" name="TV/SD" />
      <subcat id="5040" name="TV/HD" />
      <subcat id="5045" name="TV/UHD" />
      <subcat id="5050" name="TV/OTHER" />
      <subcat id="5060" name="TV/Sport" />
      <subcat id="5070" name="TV/Anime" />
      <subcat id="5080" name="TV/Documentary" />
    </category>
  </categories>
</caps>
```

**Comment by stasivanov** [comment]
Any thoughts on it? @Taloth
