### ISSUE TITLE
sonarr not recognizing Days of our lives NZBs

### ISSUE THREAD

**Issue by KBlixt** [Sonarr/Sonarr#4019]
I have latest installation of sonarr. I've added days of our lives to sonarr and when I search for available nzb files to download it doesn't find anything. I'm using nzbgeek.info as a indexer and I've double checked on nzbgeek. they have 5-7 available versions for each episodes. I'd like to know why these aren't recognized by sonarr?

I don't get any errors in my log indicating any issues with my setup. 

It would be great if someone could take the time to confirm this bug for me?

**Comment by bakerboy448** [comment]
Support Requests ->>> Forums, Discord, IRC, or the subreddit.
