### ISSUE TITLE
Adding empty import list fails

### ISSUE THREAD

**Issue by WildOrangutan** [Sonarr/Sonarr#4022]
**Describe the bug**
Adding empty Trakt.tv "import list" fails. Error is displayed: 
"No results were returned from your import list, please check your settings". 
It works fine, if list is not empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/5972966/96522527-d6402880-1273-11eb-8971-2e0c34b84f7c.png)

**System Information**

 - Sonarr Version: 3.0.4.973
 - Operating System: Linux
 - Mono version: 6.10.0

**Comment by bakerboy448** [comment]
So you're saying one should be able to add an empty Trakt list?

What's the use case there?

**Comment by WildOrangutan** [comment]
@bakerboy448 Simply presume should not, that empty in future list will be.

**Comment by markus101** [comment]
> Simply presume should not, that empty in future list will be.

Those are all words I understand, but that order... 🤕 

@Qstick presumably this is the same for Radarr, thoughts on allowing empty lists?

**Comment by WildOrangutan** [comment]
That was my best Yoda impression ☺️

I basically just added a new list. Since it's new, it's also empty. But I don't intend to keep it empty in future. So I thought having this would make sense.

**Comment by Qstick** [comment]
> > Simply presume should not, that empty in future list will be.
> 
> Those are all words I understand, but that order... 🤕 
> 
> @Qstick presumably this is the same for Radarr, thoughts on allowing empty lists?

Yea it is the same, I'm up for it if we just want to check status code for failure instead of items

**Comment by markus101** [comment]
Looks like we already error if the response code is not 200, just need to allow them to be empty.
