### ISSUE TITLE
"Use Hardlinks instead of Copy" silent failure causing unwanted copies

### ISSUE THREAD

**Issue by zazard** [Sonarr/Sonarr#4025]
**Describe the bug**
I use the feature to leave files seeding in my rtorrent, but not use double space.
The problem arose because I am using sonarr in a docker container, with download dir and tv dir as two separate docker volumes mounted from the host.
It's not possible to hardlink between two different filesystems, which is the case here - That's quite OK. However, Sonarr seems to just attempt to hardlink, and if it fails, silently just copy instead.

It would be good to have a log message to signify this at least, or better, an alert in system/health page.

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Linux 4.15.0-64-generic (Ubuntu 18.04.5)

**Comment by bakerboy448** [comment]
For docker; fix your paths, see this https://wiki.servarr.com/Docker_Guide

v2 is in a critical break/fix state only; no further development will occur in v2.

I _think_ there is already a health issue for this in v3; markus or ta will correct me when they come by to close this issue

**Comment by zazard** [comment]
Yeah, issue is easily fixed by having a single mountpoint, that's OK. My point was only that it was failing silently, thus error-inducing.

Didn't notice that I was basically a major version late, apologies. Thanks for the help.

**Comment by markus101** [comment]
There isn't a warning in Sonarr v3, not sure if Radarr does.

Given this is an advanced setting that is enabled by default we have no plans to increase the log level above debug, it's not appropriate to spam errors/warnings if the user have different volumes. Even showing a health check error/warning isn't really appropriate if users are not running Sonarr in a docker container and even then it may be their decision to do so and without a way to dismiss those warnings it's just noise.

At this time we do not have plans to show a warning, at least not until https://github.com/Sonarr/Sonarr/issues/481, tagging and closing for later consideration.
