### ISSUE TITLE
Freezed shortly after startup

### ISSUE THREAD

**Issue by windlok1010** [Sonarr/Sonarr#4026]
**Describe the bug**
Sonarr freezed shortly after startup. The log hasnt been updated in hours and I cannot stop the container.

**Screenshots**

**Logs**
https://pastebin.com/YGqkKDEK

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Unraid with Docker
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono JIT compiler version 5.20.1.34

**Comment by markus101** [comment]
Please use one of the support channels for support. Forums, subreddit, discord, etc.
