### ISSUE TITLE
Notification stackup covers ADD button

### ISSUE THREAD

**Issue by itzxzac** [Sonarr/Sonarr#4027]
**Describe the bug**
When quicking adding one series after another, the notification stack starts to cover the ADD button, preventing the user from continuing to add more until they wait for the notifications to clear or zoom their page out.

**Screenshots**
https://i.imgur.com/dM1u018.png

**System Information**
 - Sonarr Version: 2.0.0.5344
 - Operating System: Windows 10
 - .net Framework: 4.5

**UI Bugs:**
 - OS: Windows
 - Browser: Firefox
 - Version: 82.0

**Additional context**
Windows Scale and Layout: 125%
Resolution of Monitor: 1920x1080
Firefox Page Zoom: 100%

**Comment by bakerboy448** [comment]
ah yeah, v2 is in a critical break/fix release state and will have no further major development work on it.

this is likely a non-issue in v3 given the UI re-write.

**Comment by markus101** [comment]
This is not something that will be fixed in v2 and not an issue in v3.
