### ISSUE TITLE
Conflicting quality between Release Title and File name prevents import even if quality profiles groups them

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#4028]
**Describe the bug**
If a Release Title is WEB-DL.1080p and File name WEBRip.1080p then sonarr doesn't know what it really is and blocks the import until the user intervenes.
However, we could make an educated guess and import as WEBRip (or WEB-DL) if, and _only_ if, the qualities are grouped in the quality profile (and perhaps preferred words scores are identical or higher). Because such scenario can't lead to download loops.

This scenario only happens with certain trackers that change their release titles willy-nilly.

**Comment by markus101** [comment]
I thought we already got rid of this check in favour of a release processing check that rejects it if it’s already imported. Which specification is rejecting it?

**Comment by Taloth** [comment]
Version was 3.0.4.986

@agneevX do you have logs of the import failure?

**Comment by agneevX** [comment]
Unfortunately, I do not, at the moment. 

Would you need debug or trace logs? I can get them next time this occurs.

**Comment by Taloth** [comment]
Trace logs is preferred, thank you.

**Comment by agneevX** [comment]
Here it is: https://paste.ubuntu.com/p/Nty3XmdCg7

**Comment by markus101** [comment]
Closing until we have logs of this issue.

**Comment by agneevX** [comment]
There's nothing I can do until the qBittorrent issue is resolved or a fix from your side is released.

**Comment by markus101** [comment]
Downgrading Qbit has been the work around for as long as the issue has existed.

**Comment by agneevX** [comment]
The repo I use doesn't keep older versions unfortunately so I'm SOL.
