### ISSUE TITLE
Set quality profile per-season

### ISSUE THREAD

**Issue by bdcarr** [Sonarr/Sonarr#4032]
**Describe the problem**
I monitor series that have been around for a long time (e.g. Saturday Night Live). Newer seasons should only download 1080p versions, but I want to set older seasons to Any because they might not even be available in HD.

Someone else was asking for the same thing [on reddit](https://www.reddit.com/r/sonarr/comments/af841s/resolution_profile_by_season/), but for a different purpose: they want to download current seasons in 1080p, while keeping watch on older seasons in case a 4k version is released.

**Describe any solutions you think might work**
Change the way quality profiles are associated so it's done per-season. By default, all seasons inherit the profile of the series, but can be overridden if required.

**Comment by bdcarr** [comment]
Oh, of course I only find a previous issue discussing this _after_ I post it.

https://github.com/Sonarr/Sonarr/issues/319

Leaving this open for maintainers to see though - maybe it's more feasible to implement in this new version?

**Comment by markus101** [comment]
Still no plans for different profiles per season at this time.
