### ISSUE TITLE
Specify RSS search URL for generic indexer

### ISSUE THREAD

**Issue by delbonis** [Sonarr/Sonarr#4034]
**Describe the problem**
If an indexer has a functionality to give an RSS feed for a search query, then it would be convenient to be able to specify a template in the UI next to the "Full RSS Feed URL".

**Describe any solutions you think might work**
I could add more copies for RSS feeds of the search results for the series that I watch and want to fill in old content for, but that seems a little excessive.  If this is all I wanted to do with it then it wouldn't be too much of an issue, as I've just started porting my things to Sonarr, but there's some missing pieces in my library.

I'm not sure how the internals work, but it seems like this wouldn't be too difficult to add since it just extends existing behavior slightly.

**Comment by markus101** [comment]
We have no plans for searching against generic RSS feeds.

If indexers have a proper API (searching by IDs preferably) then we’ll consider adding them, but they also need support searching by season/episode.

If you have a specific indexer in mind make sure if hasn’t been requested and make a request including API documentation. If they don’t have a proper API then you’ll likely need to use Jackett.
