### ISSUE TITLE
Telegram silent notifications feature is broken

### ISSUE THREAD

**Issue by agneevX** [Sonarr/Sonarr#4041]
**Describe the bug**
Telegram silent notifications aren't working, even though it's enabled.

**Screenshots**

<img width="540" alt="image" src="https://user-images.githubusercontent.com/19761269/97281167-3120e380-1863-11eb-8d1c-7c9e60bdb8f5.png">

*(Silent notifications are denoted by a bell emoji in the title.)*

<img src="https://user-images.githubusercontent.com/19761269/97281538-a68cb400-1863-11eb-8834-de2a87e8206d.jpeg" width="300">

**Logs**
Trace: https://paste.ubuntu.com/p/8XS4NqS5mc/

**System Information**

 - Sonarr Version: `3.0.4.991`
 - Operating System: Raspberry Pi OS Buster
 - .net Framework: `6.12.0.90`

**UI Bugs:**
N/A

**Additional context**
Probably broke in the last couple of updates.

**Comment by markus101** [comment]
> Probably broke in the last couple of updates.

Broken in https://github.com/Sonarr/Sonarr/commit/665b80f15c488d678562eeb6af66879dde408c38, more than a couple versions ago.

**Comment by agneevX** [comment]
I stand corrected 😅
