### ISSUE TITLE
Cannot import odd or long file names

### ISSUE THREAD

**Issue by da-pingwing** [Sonarr/Sonarr#4043]
**Describe the bug**
Importing any download with "[" "]" or that is quite long is failing. Manual import is still working

**Logs**
Import failed, path does not exist or is not accessible by Sonarr: /downloads/Archer.2009.S11E07.1080p.WEB.H264-CAKES[rartv]. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder

**Comment by markus101** [comment]
Please use one of the support channels for support. Forums, reddit, discord or IRC.
