### ISSUE TITLE
Batch Editing Options When Doing Manual Import

### ISSUE THREAD

**Issue by TuRDMaN** [Sonarr/Sonarr#4049]
**Describe the problem**
When doing a manual import of, let's say, an entire series, sometimes the series/season/episode data is not automatically parsed. In order to successfully import, you must manually go through each file and select the series, season, and episode data.

**Describe any solutions you think might work**
A way to make the process a bit less tedious would be to allow selecting all/some of the episodes, and applying the series/season data to the entire selection, instead of clicking on the same things for each one individually. Then at least you'd only have to go through and set the episode number individually, instead of everything.

**Comment by markus101** [comment]
You can do this in v3 already.

**Comment by TuRDMaN** [comment]
I wasn't even aware there was a V3. Thanks! Time to check it out!
