### ISSUE TITLE
Feature Request: "Undo" Import

### ISSUE THREAD

**Issue by 19wolf** [Sonarr/Sonarr#4050]
**Describe the problem**
An episode of one of my anime shows was replaced by a live action version of the same name, due to it being mislabeled on the indexer (I assume).

**Describe any solutions you think might work**
This is easily fixable using the "Recycle bin" feature already implemented, but what I'm proposing is a simple "undo/restore" button on the episode history modal that would allow me to re-import the old file directly from the recycle bin, rather than having to manually dig in the filesystem and fix the file.

**Additional context**
![image](https://user-images.githubusercontent.com/453443/97663633-7bb38300-1a50-11eb-9746-fd3780223325.png)

**Comment by markus101** [comment]
This is covered in https://github.com/Sonarr/Sonarr/issues/1984
