### ISSUE TITLE
Undefined JS variables in frontend

### ISSUE THREAD

**Issue by viki53** [Sonarr/Sonarr#4051]
**Describe the bug**

I just reinstalled Sonarr on macOS using Homebrew. After running the `chmod` command to be able to start it (even the cask has this bug!) I was able to access the Web UI.

I logged in normally but then I was stuck on the loading animation as the UI couldn't load.

I thought this might be because I'm accessing it via a reverse proxy (I use Nginx on my local server to manage HTTPS and a proper domain name)… but the same thing happened when accessing it directly via `localhost:8989`.

**Screenshots**

<img width="386" alt="image" src="https://user-images.githubusercontent.com/1763364/97697396-3e2e1480-1aa7-11eb-8771-34c39747b8d6.png">

**Logs**

See screenshot for JS errors.

Looking at the lines in question, I can see this:

```html
<script type="text/javascript">
    window.NzbDrone = {
        ApiRoot    : 'API_ROOT',
        ApiKey     : 'API_KEY',
        Version    : 'APP_VERSION',
        Branch     : 'APP_BRANCH',
        Analytics  : APP_ANALYTICS,
        UrlBase    : 'URL_BASE',
        Production : PRODUCTION
    };
</script>
```

Aren't there some missing quotes around those variables ?

**System Information**

 - Sonarr Version: latest
 - Operating System: macOS 10.15.7 (Catalina)
 - .mono (macOS/Linux) Version: 6.8.0.105

**UI Bugs:**
 - OS: macOS 10.15.7
 - Browser: Firefox
 - Version: 81.0.2

**Additional context**

My previous (manual) install of Sonarr kept returning 404 errors when trying to access the Web UI (even though the rest kept working) so I reinstalled it using homebrew.

**Comment by markus101** [comment]
> Sonarr Version: latest

We'll need an exact version.

> Logs
>See screenshot for JS errors.

Trace logs from the server side will be needed here as well.

> Aren't there some missing quotes around those variables ?

Everything there gets replaced by the server before hitting the UI, `APP_ANALYTICS` and `PRODUCTION` are both boolean values, or should at least. Something is amiss, but given v2 hasn't been updated in months and you had other odd issues previously there is unlikely to be a bug.

**Comment by viki53** [comment]
Weird, now it's working again though I haven't touched anything at all, with an uptime of 6 minutes. 🤔 

I have version 3.0.4.991 installed, I can see it now with the UI, couldn't find it without it this morning (the homebrew cask doesn't seem to be versioned).

**Comment by markus101** [comment]
`window.NzbDrone` is from v2, not v3, there is no reason that would come back from v3, unless somehow the v2 UI was in the v3 install or something was cached poorly.

**Comment by viki53** [comment]
I did clear my browser cache this morning, somehow that didn't seem to work… weird one. 

Thanks for your help, sorry I wasted your time!
