### ISSUE TITLE
Import failed, path does not exist or is not accessible by Sonarr

### ISSUE THREAD

**Issue by Bastien42** [Sonarr/Sonarr#4052]
**Describe the bug**
When DL is done and Sonarr tries to import the file it displays that error in the log 

**Screenshots**
service settings seup as local system account
![Capture d’écran 2020-10-31 160125](https://user-images.githubusercontent.com/37946663/97782550-63e41800-1b92-11eb-8ba5-7a079457c0cf.png)

service settings setup as local system account as local service account
![Capture d’écran 2020-10-31 161404](https://user-images.githubusercontent.com/37946663/97782858-4617b280-1b94-11eb-95c5-593e23ab1842.png)

Security settings for my DL folder 
![Capture d’écran 2020-10-31 161900](https://user-images.githubusercontent.com/37946663/97782953-e53caa00-1b94-11eb-8659-316e67b042b6.png)

**Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/5469282/sonarr.trace.txt)

**System Information**

 - Sonarr Version: 3.0.4.991
 - Operating System: Windows 10
 - .net Framework (Windows) Version: 4

**Additional context**
note that sonarr has been working for many months now and all the sudden that happen i've tried with the configuration shown in the screenshots none fixed my issue i also tried with user account the only one i have setup on my system and simply wouldn't launch the service

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.
