### ISSUE TITLE
Language in series name incorrectly used for detection

### ISSUE THREAD

**Issue by napei** [Sonarr/Sonarr#4056]
**Describe the bug**
One particular show named `The Spanish Princess` https://www.thetvdb.com/series/the-spanish-princess/ which is a 100% English-spoken series, and it appears to be incorrectly detected as `Spanish` language when the torrent title is not period-delimited.

I mentioned this in Discord a while back however I never got around to making an issue.

**Screenshots**
Note the Language column.
![image](https://user-images.githubusercontent.com/8946502/97798533-0d063d80-1c7b-11eb-858a-2248c77abff1.png)

**Logs**
Trace logs for running the previously shown search.
https://pastebin.com/raw/N98xUh7N

**System Information**

 - Sonarr Version: 3.0.4.991
 - Operating System: Win 10 Pro

**Additional context**

Existing files are also incorrectly detected, showing the `Spanish` language despite no Spanish audio track present.
![image](https://user-images.githubusercontent.com/8946502/97798630-ee547680-1c7b-11eb-897b-43911602efb2.png)

![image](https://user-images.githubusercontent.com/8946502/97798625-e4cb0e80-1c7b-11eb-943d-6fa63a62f773.png)

**Comment by markus101** [comment]
@Taloth it looks like whenever the episode title is included it’s wrong, is this known from when you worked on excluding the series title previously?

**Comment by teejo75** [comment]
I had this with The Great British Bake Off  S11E06 Japanese Week. It detected the release as being Japanese language. I had to manually initiate the download.

**Comment by dny238** [comment]
Also having this issue ++ for fix

**Comment by bakerboy448** [comment]
> Also having this issue ++ for fix

please don't make any comments like these; a simple +1 reaction to the original issue post would suffice

**Comment by dny238** [comment]
> > Also having this issue ++ for fix
> 
> please don't make any comments like these; a simple +1 reaction to the original issue post would suffice

That does make more sense! Next time...

**Comment by thezoggy** [comment]
To note that this goes with https://github.com/Sonarr/Sonarr/issues/861
