### ISSUE TITLE
Import vs Upgrade Notifications

### ISSUE THREAD

**Issue by m1lkman** [Sonarr/Sonarr#4058]
**Describe the problem**
When Sonarr upgrades files notifications indicate "Imported" when in-fact the file is being upgraded

**Describe any solutions you think might work**
Update notification text for upgrades to indicate "Upgraded". 

**Additional context**
This may only be the case for slack notifications as that's what I use. I'm assuming this is across the board. Thanks

**Comment by markus101** [comment]
Sonarr does not differentiate upgrades from new imports for most notifications, at this time we have no plans to change this, but something that could be done when notification messages are customizable in https://github.com/Sonarr/Sonarr/issues/328
