### ISSUE TITLE
ReadMe and Website Cleanup and Reorganize

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4060]
Subject.

Example
![image](https://user-images.githubusercontent.com/55419169/97909967-a894be00-1d0e-11eb-8573-17ddf6424e57.png)

Radarr PR for the readme https://github.com/Radarr/Radarr/pull/5291/files#

**Comment by Thirrian** [comment]
I'd put hotio's above the lsio docker, or just drop lsio altogether. People keep following their silly advice with multiple mounts 🙄

**Comment by markus101** [comment]
Alphabetically it does come first, but no to dropping it completely, it's still a valid image and they've done a lot for building out those images even if the volume issue is present.

**Comment by bakerboy448** [comment]
@markus101  thoughts on adding the version badges to the readme (given you don't have a download section like radarr)?
If so, any spot preferred, I'm thinking within this section https://github.com/Sonarr/Sonarr#-sonarr

also, I need to re-do the PR and update the marko file for the website, but did taloth talk to you about putting badges on yet?
https://github.com/Sonarr/sonarr.github.io/pull/12 👍  or 👎 ?

**Comment by Taloth** [comment]
Yeah, we did talk. If we're doing badges it'll be based on json from our services, not hotio. So that's a bit of work for us to add an endpoint.
We don't really like badges sprinkled everywhere. Thus we'll have to think about some middleground where they are actually contributing.

In terms of readme, our entry point is sonarr.tv and I don't want duplication of stuff. A link/badge for v2 and v3 sounds reasonable, but they should be linking to the right website section.

PS: I committed the other website changes separately.

**Comment by Qstick** [comment]
To be quite honest, Ive been meaning to cleanup/trim back the badges on Radarr side. When we took over it's was lit up like a Christmas tree on the readme, it's too much and distracts from the actual info we try to convey there IMO.

**Comment by bakerboy448** [comment]
I'm thinking for all the ARRs (@Qstick), it would be useful to have the latest version displayed on the site.  Or rather, I can't see a downside.  Obviously it is best if it pulls from skyhook and servarr.

**Comment by Wdavery** [comment]
> I'd put hotio's above the lsio docker, or just drop lsio altogether. People keep following their silly advice with multiple mounts 🙄

@Thirrian sorry to jump in here, but is there an issue related to this somewhere I can check out? I've been using their container exclusively and I'm interested in reading more about this.

**Comment by bakerboy448** [comment]
See the docker guide https://wiki.servarr.com/Docker_Guide

**Comment by Crashcart** [comment]
I agree with a severe update. I can't find any documentation on where stuff is now stored with the major overhaul. Almost everything is referred to as the old version. So far I have yet to figure out where or how it auto starts. example https://github.com/Sonarr/Sonarr/wiki/Autostart-on-Linux
It refers to systemd being the main way.. But the old version I originally made refers to /dev/null now

**Comment by bakerboy448** [comment]
@Crashcart wiki.Servarr.com is the new wiki for v3 sonarr/Radarr + lidarr/readarr

**Comment by bakerboy448** [comment]
Also closing;  v3 RC updates will cover this
