### ISSUE TITLE
Manual import crashes if picking quality before the season is picked & season doesn't exist

### ISSUE THREAD

**Issue by austinwbest** [Sonarr/Sonarr#4065]
**Describe the bug**
Manual import crashes if picking quality before the season is picked & season doesn't exist

**Screenshots**
![sonarr_1](https://user-images.githubusercontent.com/8321115/98179913-daa04e80-1ecd-11eb-8e73-1ff7cfdf75e5.png)
![sonarr_2](https://user-images.githubusercontent.com/8321115/98179926-e25ff300-1ecd-11eb-86ff-f15dd3f8ae32.png)

**System Information**
Version: 3.0.4.993
.net Version: 4.8.0
Windows 10

**UI Bugs:**
Chrome Version 86.0.4240.111 (Official Build) (64-bit)

**Additional context**
Manual import > pick a folder
- Corn & Peg\Season 04\
Episodes are listed such as "S04E01-Saddle Up Sidekicks.mkv"

Sonarr finds the series but not the season, episode or quality
Select all
Pick quality (WebRip-720 is what i picked)
Crash... all the season loader icons spin up and the console dumps the error

There is no log for this, it is all front-end and nothing is logged.

Now my guess is because there is no Season 4 for the series as Amazon has it as 4 and TMDb has it as the second half of 2

**Comment by austinwbest** [comment]
Still an issue (now **id** instead of **map**) I did a check all and went to set quality first so it wouldn't re-parse the season/episode (another pending issue) but it seems picking quality triggers the re-parse regardless. This time it didn't find the series prior to quality selection so i guess that is why :)

![Screenshot 2020-11-13 171516](https://user-images.githubusercontent.com/8321115/99126269-d2ce6180-25d3-11eb-9343-64a52365e600.png)

**Comment by markus101** [comment]
That'd be an issue if you selected it before selecting the series, so a different issue. Will fix, but closing this.
