### ISSUE TITLE
v0 Version Not Being Stored Properly During Import

### ISSUE THREAD

**Issue by enchained** [Sonarr/Sonarr#4066]
**Describe the problem**
Erai-raws is currently one of the biggest anime groups, and they've changed their naming convention recently, now there's no v2s, only v0s and no-version high quality releases following every v0.

Currently v0 doesn't auto-upgrade to no-version releases, cause it is counted as v1 already.

**Describe any solutions you think might work**
I hope it is possible to store releases named like `[Erai-raws] Kamisama ni Natta Hi - 04 [v0][1080p].mkv` as a v0, a version that needs upgrading to a v1 that is named like `[Erai-raws] Kamisama ni Natta Hi - 04 [1080p].mkv` for example.

**Comment by markus101** [comment]
Internally v0 is stored, please fill out the bug template, including trace logs so we can investigate this further.

**Comment by enchained** [comment]
**Describe the bug**
v0 doesn't auto-upgrade to v1, and on manual it says "Existing file on disk is of equal or higher preference: HDTV-1080p v1 - English". 
From the logs, it looks like MediaInfo could be involved in the wrong revisioning. I included MediaInfo output to my folder just in case. Also, I had to update MediaInfo (GUI) to v20.09 in windows, cause it was freezing completely on Erai videos. Could those issues be connected? Which MediaInfo version does sonarr use?

**Logs**
Trace logs folder with MediaInfo on gdrive: https://drive.google.com/drive/folders/1fpvdUayhq0Xlj6OsAOfO1JmLsM4ZmP-f?usp=sharing

**Actions**

1. Add new show that has v0, monitor future episodes.
2. Turn on trace
3. Manually select v0 to download (17:29):

sonarr.trace.5.txt
```
20-11-5 17:29:33.7|Debug|QualityParser|Trying to parse quality for [Erai-raws] Magatsu Wahrheit - Zuerst - 04 [v0][1080p].mkv
20-11-5 17:29:33.7|Debug|Parser|Quality parsed: HDTV-1080p v0
```

- Wait until it's grabbed and imported (17:34).

sonarr.trace.0.txt

```
20-11-5 17:34:19.3|Debug|TrackedDownloadService|Tracking 'DownloadStation:[Erai-raws] Magatsu Wahrheit - Zuerst - 04 [v0][1080p].mkv': ClientState=Completed SonarrStage=Downloading Episode='Magatsu Wahrheit - Zuerst - 004 HDTV-1080p v0' OutputPath=/downloads/sonarr/[Erai-raws] Magatsu Wahrheit - Zuerst - 04 [v0][1080p].mkv.
20-11-5 17:34:19.3|Debug|Parser|Parsing string '[Erai-raws] Magatsu Wahrheit - Zuerst - 04 [v0][1080p].mkv'
20-11-5 17:34:19.3|Debug|QualityParser|Trying to parse quality for [Erai-raws] Magatsu Wahrheit - Zuerst - 04 [v0][1080p].mkv
20-11-5 17:34:19.3|Debug|Parser|Quality parsed: HDTV-1080p v0
20-11-5 17:34:19.4|Debug|DownloadedEpisodesImportService|Processing path: /downloads/sonarr/[Erai-raws] Magatsu Wahrheit - Zuerst - 04 [v0][1080p].mkv
20-11-5 17:34:19.4|Debug|ImportDecisionMaker|Analyzing 1/1 files.
20-11-5 17:34:19.4|Debug|QualityParser|Trying to parse quality for [Erai-raws] Magatsu Wahrheit - Zuerst - 04 [v0][1080p].mkv
20-11-5 17:34:19.4|Debug|Parser|Quality parsed: HDTV-1080p v0
20-11-5 17:34:19.5|Debug|VideoFileInfoReader|Getting media info from /downloads/sonarr/[Erai-raws] Magatsu Wahrheit - Zuerst - 04 [v0][1080p].mkv
20-11-5 17:34:19.5|Trace|MediaInfo|Read file offset 0-1343488 (1343488 bytes)
20-11-5 17:34:19.5|Trace|MediaInfo|Read file offset 1405283904-1405314013 (30109 bytes)
20-11-5 17:34:19.5|Trace|MediaInfo|Read a total of 1373597 bytes (0.1%)
20-11-5 17:34:19.6|Trace|AggregateQuality|Considering Source Television (Fallback) Resolution 1080 (Tag) Revision v0 from FileName
20-11-5 17:34:19.6|Trace|AggregateQuality|Considering Source Television (Fallback) Resolution 1080 (Tag) Revision v0 from DownloadClientItem
20-11-5 17:34:19.6|Trace|AugmentQualityFromMediaInfo|Resolution 1920x1080 considered 1080p
20-11-5 17:34:19.6|Trace|AggregateQuality|Considering Source Unknown (Default) Resolution 1080 (MediaInfo) Revision  from MediaInfo
20-11-5 17:34:19.6|Debug|QualityParser|Trying to parse quality for [Erai-raws] Magatsu Wahrheit - Zuerst - 04 [v0][1080p].mkv
20-11-5 17:34:19.6|Trace|AggregateQuality|Considering Source Television (Fallback) Resolution 1080 (Tag) Revision v0 from ReleaseName
20-11-5 17:34:19.6|Trace|AggregateQuality|Selected Source Television (Fallback) Resolution 1080 (MediaInfo) Revision v1
20-11-5 17:34:19.6|Debug|AggregateQuality|Using quality: HDTV-1080p v1
20-11-5 17:34:19.7|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
20-11-5 17:34:19.7|Debug|ImportDecisionMaker|File accepted
20-11-5 17:34:19.7|Debug|QualityParser|Trying to parse quality for [Erai-raws] Magatsu Wahrheit - Zuerst - 04 [v0][1080p]
20-11-5 17:34:19.7|Debug|Parser|Quality parsed: HDTV-1080p v0
```

- Click on "search of monitored", which leads to rejection of every v1 for that episode, cause suddenly v0 became v1.


sonarr.trace.txt
```
20-11-5 17:35:29.4|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is HDTV-1080p v1 - English
20-11-5 17:35:29.5|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Existing file on disk is of equal or higher preference: HDTV-1080p v1 - English
```

**System Information**

 - Sonarr Version: 3.0.4.993
 - Operating System: docker linuxserver.io
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34

**Comment by markus101** [comment]
> Trace logs folder with MediaInfo on gdrive

FYI, that link is not public.

**Comment by enchained** [comment]
> FYI, that link is not public.
Sorry, I misread the link permissions. It should be working now.
