### ISSUE TITLE
Tags text look weird in Safari

### ISSUE THREAD

**Issue by agneevX** [Sonarr/Sonarr#4071]
**Describe the bug**
Tags text looks weird in Safari

**Screenshots**
<img width="457" alt="image" src="https://user-images.githubusercontent.com/19761269/98510124-8f4cbe00-2288-11eb-8e96-fd9acefda50b.png">

<img width="173" alt="image" src="https://user-images.githubusercontent.com/19761269/98510171-a1c6f780-2288-11eb-9d46-b4592257203f.png">

**Logs**
N/A

**System Information**

 - Sonarr Version: `3.0.4.993`
 - Operating System: `Raspberry Pi OS - Debian Buster`
 - mono Version: `6.12.0.90`

**UI Bugs:**
 - OS: `macOS 10.15.7`
 - Browser: `Safari`
 - Version: `14.0`

**Additional context**
N/A

**Comment by agneevX** [comment]
More info:

<img width="1266" alt="Screen Shot 2020-11-11 at 1 47 27 PM" src="https://user-images.githubusercontent.com/19761269/98787043-facb9280-2424-11eb-9906-3572e8153905.png">

**Comment by bakerboy448** [comment]
This is a bug on iOS as well

Chrome: 86.0.4240.93
iOS: 14.1
Device: iPhone 12P
Safari: 14.0 (supposedly)

![image](https://user-images.githubusercontent.com/55419169/99087318-3fc00800-2590-11eb-8a68-9f9a9f613761.png)
