### ISSUE TITLE
Download client with Category matching the series name

### ISSUE THREAD

**Issue by jcpoliveira** [Sonarr/Sonarr#4072]
I find myself needing a label on my rtorrent to match each series. It would be helpful to have Sonarr, using the Download Client Category, to be able to configure this when adding a new torrent.

I believe that having a mechanism where one can specify variables on the Category field my prove useful for me and hopefully to other users as well. 
So for instance I could specify a Category with _{{SERIES_NAME}}_ and when adding a new torrent the appropriate label would be used on my rtorrent.

**Comment by bakerboy448** [comment]
Use case in needing to label each torrent by series rather than the common labeling of tv/movies

**Comment by markus101** [comment]
We do not have plans for labels with variables in the download client, a custom script that sets them after Sonarr adds the torrent would be your best bet.

**Comment by jcpoliveira** [comment]
Thanks for the tip @markus101, I did not recall that route. I will probably go with a webhook and trigger the script/app on another machine and then use xmlrpc to add the tag to rtorrent. When I get to implement something I will post on the forums and/or here as well.
