### ISSUE TITLE
Sonarr V3 activity history is bugged out

### ISSUE THREAD

**Issue by redfellow** [Sonarr/Sonarr#4074]
**Describe the bug**
Activity history has items for year 2021, that are always first and there's no way to remove / clear history.

**Screenshots**
![image](https://user-images.githubusercontent.com/1110164/98585365-d5794000-22cf-11eb-9759-3011eee0c9a9.png)

**System Information**
 - Sonarr Version: 3.0.4.993
 - Operating System: Windows 10
 - .net Framework 4.8.0

**Additional context**
Would be great if you could select events and remove them, or just clear the complete history as a workaround.

**Comment by markus101** [comment]
The date shown is whatever is stored in the DB, which means at some point your clock was set to the wrong date and they were added.

Clearing history is covered by https://github.com/Sonarr/Sonarr/issues/307

We do not have plans for single/multi-select item removal. Updating the items in the DB with the wrong date to a date from this year is your best bet to correct this issue at this time.

**Comment by redfellow** [comment]
I did not have these faulty dates before the migration to v3, so I figured the update was the issue here. Updating the DB sounds like my best bet sure, but the linked issue did not clarify the process to me one bit. I'll try looking for more info in the issue tracker.
