### ISSUE TITLE
Sonarr Rename

### ISSUE THREAD

**Issue by victoriuspub** [Sonarr/Sonarr#4079]
Hello, I would like to know how to configure so that the name of the series and the date appear in Sonarr

When configuring to rename files, By default it looks like this:
{Series Title}

This returns
undated series name

I have looked in Sonarr's renaming settings and I have found this setting
{Series TitleYear}

I have tried it but it tells me that it is not possible

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.
