### ISSUE TITLE
No real reason for: [Permanent] Invalid season or episode

### ISSUE THREAD

**Issue by bugsyb** [Sonarr/Sonarr#4080]
**Describe the bug**
Fails to import what would look like somehow ok'ish named file:

**Logs**
```
20-11-11 20:42:44.4|Debug|Parser|Parsing string 'Desperate.Housewives.S0623.720p.WEB-DL.DD5.1.H.264-NOGRP.mkv'
20-11-11 20:42:44.4|Trace|Parser|^(?<title>.+?)\W(?:S|Season)\W?(?<season>\d{4}(?!\d+))(\W+|_|$)(?<extras>EXTRAS|SUBPACK)?(?!\\)
20-11-11 20:42:44.4|Debug|Parser|Episode Parsed. Desperate Housewives - Season 623 
20-11-11 20:42:44.4|Debug|Parser|Language parsed: English
20-11-11 20:42:44.4|Debug|QualityParser|Trying to parse quality for Desperate.Housewives.S0623.720p.WEB-DL.DD5.1.H.264-NOGRP.mkv
20-11-11 20:42:44.4|Debug|Parser|Quality parsed: WEBDL-720p v1
20-11-11 20:42:44.4|Debug|Parser|Release Group parsed: NOGRP
20-11-11 20:42:44.4|Debug|VideoFileInfoReader|Getting media info from /downloads/tv-sonarr/Desperate.Housewives.S06.720p.WEB-DL.DD5.1.H.264-NOGRP[rartv]/Desperate.Housewives.S0623.720p.WEB-DL.DD5.1.H.264-NOGRP.mkv
20-11-11 20:42:44.4|Trace|MediaInfo|Read file offset 0-163840 (163840 bytes)
20-11-11 20:42:44.4|Trace|MediaInfo|Read file offset 1494392856-1494414947 (22091 bytes)
20-11-11 20:42:44.5|Trace|MediaInfo|Read a total of 185931 bytes (0.0%)
20-11-11 20:42:44.5|Debug|AggregateQuality|Using quality: WEBDL-720p v1
20-11-11 20:42:44.5|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Invalid season or episode
```
**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Linux/Docker (LinuxServer)

**Additional context**
Started to fail recently and might be linked to recent Qbittorrent bump to v4.3.0 and as such falling into:
https://github.com/Sonarr/Sonarr/issues/3968

Though it finds files - so it doesn't seem to be exactly this issue.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

**Comment by bugsyb** [comment]
Use forums to report bugs? Ok => https://forums.sonarr.tv/t/invalid-season-or-episode-full-season-all-files/26944

**Comment by Taloth** [comment]
`Housewives.S0623.720p.W`

Typo in the filename.

**Comment by bugsyb** [comment]
Filename came from torrent.

**Comment by Taloth** [comment]
Sure, but as I said, it's not a valid filename.... you think sonarr can pull that 06 and 23 episode number out of thin air?

regardless, it's a bad download, just import it manually and move on.
