### ISSUE TITLE
Manual import results in no action

### ISSUE THREAD

**Issue by bugsyb** [Sonarr/Sonarr#4081]
**Describe the bug**
Import from disk fails with no action visible neither in UI nor in Trace logs.

**Screenshots**
https://paste.pics/ANTWR

**Logs**
No logs - even in trace - surprisingly.

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Linux/Docker LinuxServer

**UI Bugs:**
 - OS: Linux Mint 20/Ubuntu 20.04 LTS
 - Browser: Firefox
 - Version: 82.03

**Additional context**
The show is registered in Sonarr, misses all files from Season which failed to auto import as per:
https://github.com/Sonarr/Sonarr/issues/4080

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
