### ISSUE TITLE
NORDIC language

### ISSUE THREAD

**Issue by JohnnyHogh** [Sonarr/Sonarr#4083]
**Describe the problem**
Many releases on the net use the NORDIC tag for "Danish, Swedish, Norwegian and Finish" subtitles and language. I cant get sonarr to download the files if I set it to danish. 

**Describe any solutions you think might work**
Make the system get both Danish and nordic, Swedish and Nordic... if its set to Danish, Swedish and so on

**Comment by markus101** [comment]
Nordic isn't considered any particular language, so it'll be treated as English, previously it was considered Norwegian. At this time we don't have plans to support multiple languages, but something we'll re-evaluate.

**Comment by JohnnyHogh** [comment]
Please re-evaluate. Its is used alot in the nordic countries.
