### ISSUE TITLE
Max Path length doesn't seem to be taking remaining path length into consideration

### ISSUE THREAD

**Issue by AlpacaDesu** [Sonarr/Sonarr#4085]
**Describe the bug**
Getting the "System.IO.PathTooLongException: Path is too long." error while trying to rename a few files 

**Screenshots**
UI doesn't produce any errors. But here's the filename generated by Sonarr
```/tv/The Disastrous Life of Saiki K. (2013) [313435]/Season 1/The Disastrous Life of Saiki K. - S01E11 - Jump! Cyborg Cider-Man No. 2 + Industry-Leading, Top-Ranking Company!! Father’s Job + Cider-Man No. 2 vs. The Lemonade Fiend + Kusuo Saiki’s Holiday + Kusuo Saiki’s Woman T... [Bluray-1080p.x265.AAC]-Cerberus.mkv```

**Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/5529137/sonarr.trace.txt)

**System Information**
 - Sonarr Version: 3.0.4.994
 - Package Version: 3.0.4.994-ls71 by linuxserver.io
 - Mono Version: 5.20.1.34
 - Operating System: LSIO Docker on Unraid

**Additional context**
https://github.com/Sonarr/Sonarr/blob/c75c54688883461d0e5275f349fba957d992f765/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L171

The line here doesn't seem to be taking the remaining path length calculated for the file path upto that point, as seen here (sorry, not good with C#):
https://github.com/Sonarr/Sonarr/blob/c75c54688883461d0e5275f349fba957d992f765/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L196

**Comment by markus101** [comment]
> The line here doesn't seem to be taking the remaining path length calculated for the file path upto that point, as seen here (sorry, not good with C#):

The the limit is 255 characters per segment, the file name is exactly 255 characters, if this is an issue with your file system you can set a lower limit, see the commit linked to https://github.com/Sonarr/Sonarr/issues/3888

**Comment by AlpacaDesu** [comment]
Okay I think something else seems to be the issue here. I renamed two files, and both segments had 256 characters. One worked, and the other threw the System.IO.PathTooLongException.

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/5529341/sonarr.trace.txt)

This seems to be due to the apostrophes present in the file name that get converted into `â€™` which end up going over the limit.

**Comment by bakerboy448** [comment]
On an unrelated note: fix your paths (they'll currently result in slow i/o intensive copy/deletes)
https://wiki.servarr.com/Docker_Guide

**Comment by Taloth** [comment]
> This seems to be due to the apostrophes present in the file name that get converted into â€™ which end up going over the limit.

Problem with that is that the encoding depends on the various filesystem layer implementations. contrary to popular believe, filesystem work with bytes, they aren't actually unicode.

Perhaps we can err on the side of caution and count utf8 bytes.

**Comment by AlpacaDesu** [comment]
> On an unrelated note: fix your paths (they'll currently result in slow i/o intensive copy/deletes)
> https://wiki.servarr.com/Docker_Guide

I’m on unraid. Data is spread out across disks so hard links don’t really work as expected 😄 


> Problem with that is that the encoding depends on the various filesystem layer implementations. contrary to popular believe, filesystem work with bytes, they aren't actually unicode.
> 
> Perhaps we can err on the side of caution and count utf8 bytes.

Yes. When viewing the logs on the container, it was shown as regular apostrophes. Only when I opened the trace log file did i notice these weird characters :)

**Comment by bakerboy448** [comment]
Hard links do work on unraid...there is some magic unraid does so they function as hard links and are effectively hardliners but are not technically hard links...it's weird

**Comment by AlpacaDesu** [comment]
@bakerboy448 yes, but my downloads and media are on a completely different shares. Unraid hardlinks don't span across user shares by the looks of it :\
