### ISSUE TITLE
Unpacking rar archives

### ISSUE THREAD

**Issue by jancoow** [Sonarr/Sonarr#4086]
Hi,

How can I let sonarr automatically unpack rar archives? I've to check the que regularly now and unpack them manually. Or how can I disable it grepping rar archives ?

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

Sonarr won't extract rar files.

**Comment by jancoow** [comment]
It's a feature request..

**Comment by markus101** [comment]
1. Search before filing issues, this is a dupe of https://github.com/Sonarr/Sonarr/issues/784
2. Use the templates
