### ISSUE TITLE
Tag rules should somehow override the default Release Profile

### ISSUE THREAD

**Issue by keystorm** [Sonarr/Sonarr#4087]
### What problem are you looking to solve?

When a Release Profile exists without a tag (thus being applied to all releases) it may conflict with other Release Profiles linked to a tag. It would be nice to make any assigned tags override any such restrictions.

### Use case example:

Let's say I default to having all series download only x265 encoded releases. Its is pretty common nowadays to find groups who will specialise in this particular codec for mainstream series. So I decided to make it a default restriction, leaving the tag option blank:

![image](https://user-images.githubusercontent.com/12006627/98919027-a381fc80-24ce-11eb-9205-4c177253bca9.png)
![image](https://user-images.githubusercontent.com/12006627/98919045-aaa90a80-24ce-11eb-9530-14b279bea918.png)

However, I know for a fact that certain series do not have anyone consistently releasing such encodes and will have to resort to the more common x264 encodes. So I created a tag conveniently called `no_h265` to alleviate this issue and to have Sonarr download only non x265 releases and apply it to those rather fringe series.

![image](https://user-images.githubusercontent.com/12006627/98922204-79cad480-24d2-11eb-8566-0777c9135819.png)
![image](https://user-images.githubusercontent.com/12006627/98922253-85b69680-24d2-11eb-9bbf-8c9b72a7493a.png)

It seems, though, the default profile is still applying to all search results making any of the releases effectively undownloadable, for series with the `no_h265` tag attached to them.

![image](https://user-images.githubusercontent.com/12006627/98923799-67519a80-24d4-11eb-9db4-d07b89222c0e.png)

### Possible solutions

1. Adding "smart" logic that overrides any restriction based on the profiles assigned to a series, especially in regards of the "Must Contain" and "Must Not Contain" fields. The order of application of such profiles (particularly in the case of several tags attached to a series) will be relevant.

2. Adding a checkbox to any Release Profiles, that have a specified tag, to force override any default profile previously applied.

**Comment by markus101** [comment]
Previously we've discussed having anti-tags, so they would apply if they didn't have specific tags, but at this time we do not have plans for that. In v3 you're able to use the mass editor to apply tags in bulk (add, remove or replace) and do not currently have plans to implement anti-tags.

**Comment by keystorm** [comment]
I understand, @markus101.

Mass editing is a great solution for changing many series at once, but when adding new series having to manually set tags makes the process less streamlined.

How about being able to configure specifics tags to be assigned by default to all new Series?  

This wouldn't override any current logic with default profiles, but would allow for a more granular setting of profiles later on.
