### ISSUE TITLE
Import failed, path does not exist or is not accessible by Sonarr

### ISSUE THREAD

**Issue by ycodryn** [Sonarr/Sonarr#4088]
**Describe the bug**

This problem began some weeks ago. Until then, all was working nice and smooth, nothing was changed besides updating sonarr.  
Both sonarr and qbittorrent are using same paths (localhost, /downloads/), same PUID and PGID as main user.
Sonarr can browse and see what is inside /downloads/, manual import is working. 
User has full control on files and folders.
What is strange that other series are working.

**Logs**

Import failed, path does not exist or is not accessible by Sonarr: /downloads/Star.Trek.Discovery.S03E05.1080p.WEB.H264-CAKES[rartv]. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder
Import failed, path does not exist or is not accessible by Sonarr: /downloads/The.Walking.Dead.World.Beyond.S01E07.1080p.WEB.H264-GGWP[rartv]. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder

Completed scanning disk for The Mandalorian
Scanning The Mandalorian
Episode search completed. 1 reports downloaded.
Report sent to qBittorrent. The.Mandalorian.S02E02.1080p.DSNP.WEBRip.DDP5.1.Atmos.x264-PHOENiX[rartv]
Sarching 1 indexers for [The Mandalorian : S02E02]

**System Information**

 - Operating System: DSM 6.2.3-25426 Update 2, Docker
 - Sonarr Version: 3.0.4.994
 - Package Version: 3.0.4.994-ls71 by linuxserver.io 
 - Mono Version: 5.20.1.34
 - AppData directory: /config
 - Startup directory: /app/sonarr/bin
 - Mode: Console

**Additional context**

logs: https://pastebin.com/XqBHKXWL
docker creation: https://pastebin.com/9TsjyTDp

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

1) I'm assuming you're running Qbt 4.3+  [see this](https://www.reddit.com/r/sonarr/comments/jg5jfi/known_issues_with_qbittorrent_newer_than_425/)

2) it appears you are using the default LSIO paths...those suck and will result in i/o intensive copy/deletes...go through [this guide](https://wiki.servarr.com/Docker_Guide)

**Comment by ycodryn** [comment]
Thank you so much!
