### ISSUE TITLE
Manual import options resetting if not done in a specific order

### ISSUE THREAD

**Issue by austinwbest** [Sonarr/Sonarr#4089]
**Describe the bug**
Load a folder, pick the series, it matches the season & episodes. This particular one is not the right season so pick a different season. Now pick a quality. And at this point the season/episode is re-parsed and resets what you previously had picked.

Seems you cant pick quality inbetween doing other things

Used the step recorder is windows so it grabbed screenshots as i clicked through.

Also a side note, all qualities are the same but when doing a mass quality change it is **Unknown**. Dunno if intentional or not but noticed that as well.

**Screenshots**
```
https://user-images.githubusercontent.com/8321115/99020692-26d23b00-252d-11eb-97ab-67ff775272fb.png
https://user-images.githubusercontent.com/8321115/99020725-3b163800-252d-11eb-9e36-11e949f11d59.png
https://user-images.githubusercontent.com/8321115/99020752-45383680-252d-11eb-943f-304524756310.png
https://user-images.githubusercontent.com/8321115/99020773-4c5f4480-252d-11eb-9b51-11c2f39b4e46.png
https://user-images.githubusercontent.com/8321115/99020830-55e8ac80-252d-11eb-94b5-f2b49ba6607e.png
https://user-images.githubusercontent.com/8321115/99020842-5da85100-252d-11eb-884a-2785f4b91500.png
https://user-images.githubusercontent.com/8321115/99020858-64cf5f00-252d-11eb-84e3-fc63359b77cb.png
https://user-images.githubusercontent.com/8321115/99020870-6bf66d00-252d-11eb-9a82-dff792b6659e.png
https://user-images.githubusercontent.com/8321115/99020886-731d7b00-252d-11eb-9dea-f8402c3ca916.png
```

**Logs**
Link to debug or trace log files.

**System Information**

Version - 3.0.4.994
.net Version - 4.8.0
Windows 10

**Comment by markus101** [comment]
Use `Win + Shift + S` for screenshots, avoid the giant white space in every screenshot.

**Comment by austinwbest** [comment]
It's my second monitor, have to figure out how to make it grab only one of them 🤔

**Comment by markus101** [comment]
Added them to a code block so I don't need to see them and scroll 400 times to re-read the post. In this case 9 screenshots is not worth 9000 words.

> Seems you cant pick quality inbetween doing other things

You can't change language or quality after selecting season, but not selecting the episodes, the backend sees no selected episodes and thinks it needs to help you out.

> Also a side note, all qualities are the same but when doing a mass quality change it is Unknown. Dunno if intentional or not but noticed that as well.

It selects the first quality, which is unknown, in the real world the odds of someone mass editing the quality when they're all the same is close enough to 0 to not make it worth the effort to be smarter about it.
