### ISSUE TITLE
Import failing due to added 

### ISSUE THREAD

**Issue by nebbywan** [Sonarr/Sonarr#4090]
**Describe the bug**

**Screenshots**

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: [e.g. 2.0.0.1]
 - Operating System: [e.g. Windows 10]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
I guess you decided not to edit this one and instead opened #4091?

**Comment by nebbywan** [comment]
Honestly no idea how that happened...
