### ISSUE TITLE
Import failing due to added "/" at end of path from qBit, no error reported in UI

### ISSUE THREAD

**Issue by nebbywan** [Sonarr/Sonarr#4091]
**Describe the bug**
A torrent that failed in the past due to the way qBit 4.3+ handled sending back paths was tried with the latest update. It failed to import but also didn't throw an error in the UI, with the history simply showing the grab and nothing else. It looks like, for some reason, qBit or Sonarr added a forward slash at the end of the output string and this caused the problem since the host machine is running Windows. https://github.com/Radarr/Radarr/issues/1761 is another example of this kind of concatenation problem in an unrelated scenario.

**Screenshots**
![Screenshot 2020-11-13 153455](https://user-images.githubusercontent.com/12175293/99130670-ce9b4780-25c5-11eb-86e7-2cf9f19656c2.png)

**Logs**
[Log.txt](https://github.com/Sonarr/Sonarr/files/5539750/Log.txt)

**System Information**
 - Sonarr Version: 3.0.4.995
 - Operating System: Win 10 Pro 20H2
 - qBit Version: 4.3.0.1

**Comment by Taloth** [comment]
Is qbit running on the same machine?

**Comment by nebbywan** [comment]
@Taloth yessir, all on the same box.

**Comment by KierenConnell** [comment]
Started having the same issue.
Was working fine prior to recent update to 3.0.4.995.

**Comment by Taloth** [comment]
Please post actual trace level logs, including that of the qbit api response that is logged at trace.

**Comment by KierenConnell** [comment]
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/5539914/sonarr.trace.txt)
Attached trace logs

Started trace logging
Searched for release
Started downloading
Download complete
Disappears from Sonarr list with no warning.

**Comment by Taloth** [comment]
I'm not testing the same torrent, but for me I see proper backward slashes. Probably something specific to the torrent, maybe it depends on the OS the torrent was created on, but i'm not gonna dive deeper into that.

Fix will be out soon.

**Comment by KierenConnell** [comment]
Not sure if this is the right place to put it
Just got 3.0.4.997 in and re-ran the same torrents that failed with 995

All good and Sonarr is processing as expected

**Comment by Taloth** [comment]
That was quick. The linux package of 997 hasn't even finished building yet :)

Thank you for confirming.

**Comment by nebbywan** [comment]
Ack, he beat me to it! But, yeah, mine worked fine too with 3ff848b.

Thanks for the quick fix!
