### ISSUE TITLE
Copying fails when importing some large files

### ISSUE THREAD

**Issue by trisk** [Sonarr/Sonarr#4093]
**Describe the bug**
I have two files, 8GB and 5GB in size, that have completed downloading but are stuck in the queue as "Downloaded - Waiting to Import" or "Downloaded - Importing" with status "Failed to import episode". This hasn't occurred with other files (including files of the same size), but I rarely download files larger than 2-3GB.

The files stopped copying to the destination after a few hundred megs. The stack in the logs shows 
[v3.0.4.991] System.IO.IOException: Interrupted system call

**Screenshots**
![failtoimport](https://user-images.githubusercontent.com/207920/99138760-f78cfe00-2600-11eb-82b8-dbc6520ca337.png)

**Logs**
[sonarr (1).txt](https://github.com/Sonarr/Sonarr/files/5540133/sonarr.1.txt)

**System Information**

 - Sonarr Version: 3.0.4.991
 - OS: Ubuntu 16.04 lx branded zone on SmartOS (illumos kernel)
 - .net Framework (Windows) or mono (macOS/Linux) Version: 6.12.0.90

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

You can try downgrading mono to 5.20, especially if SMB/CIFS is involved.
