### ISSUE TITLE
Add option to display video codec next to each episode when looking at season list.

### ISSUE THREAD

**Issue by evanrich** [Sonarr/Sonarr#4095]
Problem:

I try to optimize my library  with 1080p HEVC / x265 files, but sometimes they're not available and I get a 720p or 1080p x264 file instead.   It's hard to go back later and figure out what I need to re-get as a HEVC/x265 version after the fact, and usually need to go through directory by directory and look for rather large files.

Proposed solution:
Add another column (and allow it to be toggled in settings) that displays the codec used, similar to this (forgive the crappy paint 3d mockup)
![image](https://user-images.githubusercontent.com/518320/99140038-e1784100-25f2-11eb-8aee-b26aee33ec1d.png)

**Comment by bakerboy448** [comment]
Use Preferred Words
https://trash-guides.info/Sonarr/V3/Sonarr-Release-Profile-RegEx/

**Comment by markus101** [comment]
Preferred words won't help here, but you can already show the video codec, hit the cog wheel in the "actions" column (beside status).

**Comment by evanrich** [comment]
@bakerboy448   As markus101 said, Prefered words don't help.  I already have a "prefer x265" profile.   The problem is that sometimes x265 content is not available and I get x264.    It would be nice if the "cutoff" field supported codec as well, so there could be an option for "stop seraching at x265", and then darken the field, similar to the "Webrip-1080p" in the screenshot.  This would tell sonarr to stop searching once a "1080p x265/hevc" Match was found

**Comment by evanrich** [comment]
FWIW, I think I've found a way to enforce X265, will try it out

https://imgur.com/a/XqZe5I1
