### ISSUE TITLE
Notify when manual import required

### ISSUE THREAD

**Issue by derekoharrow** [Sonarr/Sonarr#4096]
**Describe the problem**
Sometimes, shows won't automatically import after download, which could be for a number of reasons - e.g. incorrect series number, etc.
They can sit in the Queue forever until you notice them and manually import, or delete them.
It would be useful to have an option to have Sonarr send a notification in this situation so that you know to go and take a look at the queue.

**Describe any solutions you think might work**
Add an option to the Connections dialogue to notify "On Manual Import Required", and send a notification accordingly.

**Comment by bakerboy448** [comment]
Closing no plans at this time.

Existing notifications can work for this...or more specifically the absence of one after the grab.

**Comment by derekoharrow** [comment]
Sorry, but how can absence of a notification be an indication of an issue?

**Comment by bakerboy448** [comment]
You'd get a grab but not a import/upgrade

**Comment by derekoharrow** [comment]
> You'd get a grab but not a import/upgrade

Yes, but that doesn't help - I don't want notifications for every single episode that I download, so I don't use them, and even if I did that would mean having to pay attention to which ones were grabbed and then seeing if I had an import/upgrade notification for each. 
User friendly systems should, in the main, look after themselves, and tell you when attention is needed, as in this use case.

**Comment by bakerboy448** [comment]
You're not wrong and I don't necessarily disagree.

And it is in Lidarr 👀


@markus101 your $0.02?

**Comment by drowse7en** [comment]
Perhaps, this condition can be identified as a health-check failure?
