### ISSUE TITLE
Library Cleanup

### ISSUE THREAD

**Issue by mytvpro** [Sonarr/Sonarr#4098]
please consider feature to delete all files from libarary which are not mapped. 
please also consider an option to delete directories which are indicated as containing existing series during import or dedupe option to merge dirs and keep newer files.

my libarary is huge and unmanageable manually with hundreds of thousands of episodes. i really wish sonarr would help me remove orphaned directories and files and duplicate series

**Comment by bakerboy448** [comment]
Generally speaking it is not in the scope of *Arrs to deduplicate and cleanup your existing disorganized library.

Use Filebot or ~ + by hand to organize and cleanup.

We may enhance some of the import features, but not to this degree.

You can use the *arrs to mass move what you have organized in your library (change root folder -> move files)

also don't download to your library, I have a feeling you were doing that.

You can point manual import to your disorganized mess and pull whatever into your new organized library/root folder.

**Comment by mytvpro** [comment]
organizing the library isnt within the scope of sonarr? it doesnt seem to be a large task to add an option to delete unmapped files or dir? i guess i am looking at this wrong i was shocked that it wasnt already implemented. i really dont think this is an edge use case. i think its a very natural feature to use sonarr to organize the library beyond just selected root folders. sonarr knows what files are mapped or not. i dont. i hope that you will not dismiss this idea without weighing the cost benifit. its virtually impossible for anyone to delete every file which is not mapped and associated dirs but sonarr could do this quite easily i believe

**Comment by markus101** [comment]
We have no plans to have automated deletion of files, regardless of effort to implement it, it comes down to the risk of doing so; deleting files has an inherent risk and we only do so in limited cases.

The only place we're considering deletion is at the manual import level, which is available at the series level (`Manual File Import`) or more globally to import files outside the series folder.

Cleaning up a disorganized library is not Sonarr's primary goal, starting with a solid base and importing files then removing the left overs afterwards is your best bet.

**Comment by mytvpro** [comment]
that's really a shame. when a library has thousands of duplicates and Sonarr KNOWS it and wont do anything to help. i think the options to delete whatever doesnt "sync to list" is much more risky than a "user saying this is a duplicate delete it". the latter being far more valuable the end user where no such tool exists. i apologize if im thinking of something proprietary to radarr i cant recall now. im shocked that i can delete my entire library if its not on a list but cant choose to delete what sonnar finds to be a duplicate if i concur. it already tells me it exists but refuses to help. i am frankly amazed at how against this you are. it seems completely natural and within the scope of this project to maintain order in the library sonarr is managing.

**Comment by mytvpro** [comment]
also for the record accidently changing root folders when i didnt want to then changing back all the while doing downloads and imports has screwed my library up and i cant find a way back

**Comment by bakerboy448** [comment]
Organizing an organized library is not the purpose of sonarr....there are plenty of other tools and methods for that out there.

Sonarr's (and Radarr's)  purpose is to either add to your existing ORGANIZED library or upgrade it....Point is, it is not in scope to do what you're asking.

I already gave you a solution to get your library organized.  There's also a confirmation when you change root folders IIRC, so....don't blame the app there.  Your way back is to move whatever needs moving.

But it sounds like Sonarr may not be for you then.
 
also going off your name and a quick google search, it smells like you're hosting/profiting from a IPTV type service?
not explicitly forbidden, but frowned upon.

**Comment by mytvpro** [comment]
thats as far as dulicate dirs go. but as for unmapped files. how can i know which ones to delete and which ones to keep. i dont know what is mapped. i want to keep the mapped ones. again this seems perfectly within the scope to delete unmapped filles in series folder. how is keeping the library organized not one of Sonarr primary goals? have you considered maybe it should be? and that it would make it that much greater of a tool?

**Comment by bakerboy448** [comment]
get a nice clean library folder setup; add your shows to sonarr (if need be you can script create the folders for your shows and then bulk import);  then point manual import at your disorganized library and get everything imported.

once everything is imported, you can nuke the old folder.

It KEEPS a library organized, but it will not organize your mess of a folder for you per se.  Try Filebot or TinyMediaManager for that.

**Comment by mytvpro** [comment]
`Try Filebot or TinyMediaManager for that.`

i'll look there thank you

**Comment by mytvpro** [comment]
boy i sure wish i could just conveniently delete these files that have screwy episode naming 

![image](https://user-images.githubusercontent.com/47206457/100311636-4ed68b00-2f7e-11eb-8387-62b497bf6974.png)
