### ISSUE TITLE
exclude extensions

### ISSUE THREAD

**Issue by mytvpro** [Sonarr/Sonarr#4099]
possible to exclude extensions from downloads? would this have to be on the indexer or download client side? i cannot use m4v, mt2s, iso and many others yet stuck downloading them often

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

No, Sonarr doesn't know which file types are in the release until import time and won't reject based on extension.
