### ISSUE TITLE
Automatic search not finding anything, manual shos "Unknown Series"

### ISSUE THREAD

**Issue by flashkiller999** [Sonarr/Sonarr#4102]
**Describe the bug**
When adding the anime "Soul Land" (Douluo Dalu) [https://anidb.net/anime/13789]:
New available episodes show up as "Unknown Series"

**Screenshots**
![image](https://user-images.githubusercontent.com/36169259/99438985-830dd400-290c-11eb-844b-acaedcb7e175.png)

**Logs**
```
20-11-17 19:41:40.2|Debug|DownloadDecisionMaker|Processing release '[VipapkStudios].Douluo.Dalu.S2-129.[1080p]' from 'NZBGeek'
20-11-17 19:41:40.2|Debug|Parser|Parsing string '[VipapkStudios].Douluo.Dalu.S2-129.[1080p]'
20-11-17 19:41:40.2|Debug|Parser|Episode Parsed. Douluo Dalu S2 - 129 
20-11-17 19:41:40.2|Debug|Parser|Language parsed: English
20-11-17 19:41:40.2|Debug|QualityParser|Trying to parse quality for [VipapkStudios].Douluo.Dalu.S2-129.[1080p]
20-11-17 19:41:40.2|Debug|Parser|Quality parsed: HDTV-1080p v1
20-11-17 19:41:40.2|Debug|Parser|Release Group parsed: VipapkStudios
20-11-17 19:41:40.2|Debug|ParsingService|No matching series Douluo Dalu S2
20-11-17 19:41:40.2|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Series
```

**System Information**
 - Sonarr Version: 3.0.4.1009
 - Operating System: Ubuntu Server
 - mono (macOS/Linux) Version: 6.8.0.105

**Additional context**
This might be problem because this release group refers to these episodes as "S2", but according to TheTVDB we are in S6.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

> This might be problem because this release group refers to these episodes as "S2", but according to TheTVDB we are in S6.

Definitely. Either thexem.de will need to add an alias, if possible to support, or it won't work.
