### ISSUE TITLE
Table view progress option: episodes/episode count progress bar

### ISSUE THREAD

**Issue by yekul** [Sonarr/Sonarr#4105]
**Describe the problem**
Wasn't sure how to title this, but the problem is not being able to download future episodes whilst also monitoring older episodes to have a view count overall. 
Example to make it clearer: 
https://imgur.com/a/tXBy9Jl
From example above, the top entry will show 10/20 because I have all episodes monitored, but the overarching monitored checkbox for the series disabled. If new episodes come out, they will not automatically download as a result. Removing the individual episodes monitored status and enabling the series monitored checkbox will of course fix the automatic downloads, but then remove the total episode count from the progress bar. It would also mean when sorting low to high that series with 0/'total' episodes would always be at the top of the feed, useful for when you add a series you've seen but are not quite sure about yet. 

I would like a column that could show collected episodes per episode count basically. This would allow for easier viewing of missing episodes when you have a series you have started watching but not yet back-filled the library. It also allows to add a series and at a glance wait for x amount of episodes to have aired before starting downloads (for example if waiting till end of a season before downloading). 

I have seen a little push back about this based on previous google searches essentially saying if you don't have a series monitored you don't want to know anything about it. And for some use cases that's definitely fair. But for a lot of people without full libraries who are constantly filling in the gaps it's good to know at a glance just how much progress you have done on a series. 

**Describe any solutions you think might work**
Mostly described above, but basically just adding a new column under options that would show episodes/episode count in the progress bar format. Like all of the options, this would be a personal preference to choose between. 

Thanks for your time and consideration.

**Comment by markus101** [comment]
At this time we do not have plans for a progress that includes all episodes in the series.
