### ISSUE TITLE
[UI-bug] API Key Copy button does not work

### ISSUE THREAD

**Issue by kevinwlau** [Sonarr/Sonarr#4106]
**Describe the bug**
In **Settings -> General -> Security**, the copy button next to the API Key does not copy the key.

**Screenshots**
![image](https://user-images.githubusercontent.com/689163/99840508-4cb19e00-2b32-11eb-9a25-0069bb7adeda.png)

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Windows 10, Linux (docker)
 - mono Version: 5.20.1.34

**UI Bugs:**
 - OS: Windows
 - Browser: 
   - Chrome 87.0.4280.66
   - Firefox 80.0.1 

Tested using Chrome/Firefox on Windows, accessing two different Sonarr instances on Windows 10 and docker.

**Comment by bakerboy448** [comment]
V2 is only have critical bugs fixed at this point, which this is not.

If that feature is important to you, upgrade to v3
