### ISSUE TITLE
Season naming conventions

### ISSUE THREAD

**Issue by Paul5656** [Sonarr/Sonarr#4107]
For a while I've realized that some trackers name their TV shows as "TVShow Season X" but Sonarr via Jackett queries the search as     "TVShow S0X"...This means that all the trackers that label theirs as such are excluded since they can't be found. Is there anything that can be done about this issue?

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

Sonarr queries using a season number, not a specific format, Jackett/the indexer is responsible for formatting it in a way that makes sense.
