### ISSUE TITLE
Rename override for individual shows

### ISSUE THREAD

**Issue by DjRicko** [Sonarr/Sonarr#4109]
**Describe the problem**
Some of us prefer to keep scene names of releases, but some shows like mythbusters have completely fucked up naming, like ep01 for season one on scene, and seasons not matching thetvdb at all. Would be nice to have a override to toggle on renaming for individual shows, but keep it off for everything else.

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/926
