### ISSUE TITLE
Torznab indexer path no longer editable

### ISSUE THREAD

**Issue by DHandspikerWade** [Sonarr/Sonarr#4112]
**Describe the bug**
API path is not included in the URL when editing an indexer. Looking at the indexers table in SQLite shows expected data. Editing the domain and saving results in only the domain to be updated.

**Screenshots**
![no_path](https://user-images.githubusercontent.com/3298024/99891415-1bbf8f00-2c40-11eb-8151-c18b5c175ac9.PNG)

**Logs**
Switching to debug logging, clearing logs, then opening an existing index with the issue results in no logs.

**System Information**

 - Sonarr Version: 3.0.4.1017
 - Operating System: Ubuntu Docker image on UnRAID host
 - .net Framework (Windows) or mono (macOS/Linux) Version: mono 5.20.1.34

**UI Bugs:**
 - OS: Windows
 - Browser: Firefox
 - Version: 84.0b1

**Additional context**
Adding a new indexer does not seem to have issue. A new indexer correctly shows the path when edited.

**Comment by markus101** [comment]
API path is a separate (advanced) field. Close the modal and turn on advanced settings.
