### ISSUE TITLE
Mac M1/ARM Native Support

### ISSUE THREAD

**Issue by Casuallynoted** [Sonarr/Sonarr#4113]
### What problem are you looking to solve?

Currently, running Sonarr on an Apple Silicon Mac (Mac Mini, MacBook Air/Pro 2020) has the app running using the Rosetta (x86) compatibility layer. It would be awesome if Sonarr ran natively so as to have the best possible performance on these ARM-based CPUs.

**Comment by bakerboy448** [comment]
@ta264

**Comment by ta264** [comment]
For Sonarr I think this is more a case of getting the right mono build.

**Comment by Casuallynoted** [comment]
There currently is a macOS arm64 mono build, which I do have installed on my Mac at the moment:
![Screen Shot 2020-11-22 at 5 29 38 AM](https://user-images.githubusercontent.com/6272557/99901298-b8efe700-2c83-11eb-89e1-aeb4643f5394.png)

What's odd though is that when this build is on the computer, Sonarr refuses to start. The error it's providing is especially strange because it's referencing build files which are no longer on my computer. 

[Error] OsInfo: Couldn't get OS Version info 

[v3.0.4.1019] System.InvalidOperationException: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00045] in /Users/cas/Desktop/mono-main/mono/external/corefx/src/System.Linq/src/System/Linq/Single.cs:143 
  at NzbDrone.Mono.EnvironmentInfo.VersionAdapters.MacOsVersionAdapter.Read () [0x00041] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\EnvironmentInfo\VersionAdapters\MacOsVersionAdapter.cs:41 
  at NzbDrone.Common.EnvironmentInfo.OsInfo..ctor (System.Collections.Generic.IEnumerable`1[T] versionAdapters, NLog.Logger logger) [0x0003c] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\EnvironmentInfo\OsInfo.cs:61

**Comment by ta264** [comment]
Ok that is something we can fix Sonarr side hopefully. Probably need to fix up the mediainfo Dublin too...

**Comment by Casuallynoted** [comment]
> Ok that is something we can fix Sonarr side hopefully. Probably need to fix up the mediainfo Dublin too...

No problem!

I just tried out the new version (3.0.4.1020) and the error seems to have changed a bit. It's no longer referencing that directory:

[Error] OsInfo: Couldn't get OS Version info 

[v3.0.4.1020] System.InvalidOperationException: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0004a] in <b089191633fb46a781637e70f10e0d72>:0 
  at NzbDrone.Mono.EnvironmentInfo.VersionAdapters.MacOsVersionAdapter.Read () [0x00041] in <cc1c82c7c1194aa6b0500a537a3383e9>:0 
  at NzbDrone.Common.EnvironmentInfo.OsInfo..ctor (System.Collections.Generic.IEnumerable`1[T] versionAdapters, NLog.Logger logger) [0x0003c] in <b2a6866d6c72408cbd98ab5a71bfa22a>:0

**Comment by Casuallynoted** [comment]
Also I'm totally not sure if this helps but this link is a verbose output of the Sonarr boot, it's definitely a lot bigger than what you see above
http://s000.tinyupload.com/index.php?file_id=19715852101530662966

**Comment by markus101** [comment]
Please run it with the `--debug` mono switch and post Sonarr's log file, that should give us the lines where Sonarr is failing to start.

**Comment by dininski** [comment]
Wouldn't an [ARM compatible docker image](https://hub.docker.com/r/linuxserver/sonarr) resolve this? Not sure what mono version it is might be using, but I'm currently using sonarr with a Raspberry PI, which is also ARM-based.

**Comment by samip5** [comment]
> Wouldn't an [ARM compatible docker image](https://hub.docker.com/r/linuxserver/sonarr) resolve this? Not sure what mono version it is might be using, but I'm currently using sonarr with a Raspberry PI, which is also ARM-based.

There is already an arm64 (aarch64) Docker container of it, but Docker and Mac => Not a good combination in my experience.

**Comment by wyq977** [comment]
> Wouldn't an [ARM compatible docker image](https://hub.docker.com/r/linuxserver/sonarr) resolve this? Not sure what mono version it is might be using, but I'm currently using sonarr with a Raspberry PI, which is also ARM-based.

Althought Docker Desktop now have support for m1 but its still basically getting a VM inside ur machine. Using qemu i think. For some one who just use the mac mini for hosting Sonarr, jackett and download client, its still more resouce efficient to download the x86 app (throgh rosetta) than to use docker compose. 

A native build would be much appreciated but i havent installed mono with arm64 for now i havent seen it on mono's github repo not sure how to get stable version
```
$ mono --version
Mono JIT compiler version 6.12.0.122 (2020-02/c621c35ffa0 Wed Feb 10 00:51:43 EST 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by wyq977** [comment]
dotnet6.0 has added support for Apple Silicon/M1 (`os-arm64`) and I build Jackett with dotnet6.0 ([6.0.100-rc.1](https://dotnet.microsoft.com/download/dotnet/6.0)) and runs fine tho I have been using for a few hrs just now. 

Mono seems a bit late as I guess it will eventually keep up with dotnet6.0 at some point, i havent found a tracker issue in mono's repo tho, if anyone knows pls let me know

ty

**Comment by bakerboy448** [comment]
It's much more likely that sonarr will sooner switch to .net5 and then move to .net6 than mono getting their act together IMO

**Comment by wyq977** [comment]
OK, i guess the build.sh will need to be upgrade as [`BuildWithXbuild`](https://github.com/Sonarr/Sonarr/blob/08359e264c510c3fc300f6e95217b7bb2c45c5bd/build.sh#L104) for macOS now set the platform to `x86`

So the build for macos will also be dotnet or still using mono?

**Comment by bakerboy448** [comment]
It'll require Sonarr to switch to .net and update their build stream first.

That effort underway here: https://github.com/Sonarr/Sonarr/tree/widowmaker


For Downstream *Arrs (Radarr/Readarr/Lidarr) `once we switch to net6.0 we'll add Macos arm builds`

**Comment by wyq977** [comment]
I c, I guess the later update with dotnet will patch this issue, will keep an eye

**Comment by dvcrn** [comment]
Any insights on how the efforts to move to net6 are going? I'm not familiar with .net so I don't know how difference .net6 is from mono, or if you could just swap them out and monkey-patch the errors as they pop up (but I'd guess no 😅) 

(Thanks for the jackett tip @wyq977! Got it to build natively for osx-arm64 with .net6 as well and finally one less Intel process running)

**Comment by bakerboy448** [comment]
> Any insights on how the efforts to move to net6 are going? I'm not familiar with .net so I don't know how difference .net6 is from mono, or if you could just swap them out and monkey-patch the errors as they pop up (but I'd guess no 😅)

widowmaker branch does exist

**Comment by wyq977** [comment]
@dvcrn Now radarr has a [pre-release 4.0.0](https://github.com/Radarr/Radarr/releases/tag/v4.0.0.5745) with osx-arm64 build. I havent tried it but can you share you experience if u tried it?

Like the ram usage/CPU as well as the overall usability, i.e. crashes/freezes

**Comment by dvcrn** [comment]
Sure, I'll give it a go!

**Comment by dvcrn** [comment]
I tried the Radarr.develop.4.0.0.5745.osx-app-core-arm64.zip build but the app doesn't start here. Just getting a "The application “Radarr.app” can’t be opened." without any additional context or error message. The intel one is working fine though!

If dotnet6 is now supported I could giving building from source a try here next

**Comment by ta264** [comment]
I think you have to manually sign it before it will run. Apple really have made things difficult :/

**Comment by dvcrn** [comment]
Oh whoops - you were right! Self-signing the app made it start. I'll keep this version running for now to see if I notice anything 👀

**Comment by dvcrn** [comment]
Just reporting in - been almost a month and no issues here so far!

**Comment by dk4550** [comment]
> Just reporting in - been almost a month and no issues here so far!

I'm looking to test this as well... I'm trying to figure out how to self sign the app...

**Comment by dvcrn** [comment]
> I'm looking to test this as well... I'm trying to figure out how to self sign the app...

Create a self-signed code sign certificate in certificate assistant, name it "selfsigned". Then do

```
codesign -s "selfsigned" --force --deep  Radarr.app
```

**Comment by alexreg** [comment]
Does anyone know the status of .NET 6.0 support? Is the widowmaker branch almost ready for a pre-release?

**Comment by bakerboy448** [comment]
> Does anyone know the status of .NET 6.0 support? 

it's being worked on 

> Is the widowmaker branch almost ready for a pre-release?

No ETA

I would not expect a release anytime soon nor in the near future.

**Comment by alexreg** [comment]
@bakerboy448 Okay, thanks for the update.

**Comment by alexreg** [comment]
Hello. Are we any closer to .NET 6.0 support these days? I don't see much activity on the `widowmaker` branch lately, though perhaps it's moved more to `develop` now.

**Comment by bakerboy448** [comment]
It's in the GitHub develop branch which is already dotnet6 and v4 is in pre-alpha internal testing

**Comment by markus101** [comment]
Closing as .net 6 is in develop.

**Comment by ltto** [comment]
> There currently is a macOS arm64 mono build, which I do have installed on my Mac at the moment: ![Screen Shot 2020-11-22 at 5 30 49 AM](https://user-images.githubusercontent.com/6272557/99901314-e2a90e00-2c83-11eb-8df2-513caa18606b.png)
> 
> What's odd though is that when this build is on the computer, Sonarr refuses to start. The error it's providing is especially strange because it's referencing build files which are no longer on my computer.
> 
> [Error] OsInfo: Couldn't get OS Version info
> 
> [v3.0.4.1019] System.InvalidOperationException: Sequence contains more than one matching element at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00045] in /Users/cas/Desktop/mono-main/mono/external/corefx/src/System.Linq/src/System/Linq/Single.cs:143 at NzbDrone.Mono.EnvironmentInfo.VersionAdapters.MacOsVersionAdapter.Read () [0x00041] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\EnvironmentInfo\VersionAdapters\MacOsVersionAdapter.cs:41 at NzbDrone.Common.EnvironmentInfo.OsInfo..ctor (System.Collections.Generic.IEnumerable`1[T] versionAdapters, NLog.Logger logger) [0x0003c] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\EnvironmentInfo\OsInfo.cs:61

How did you successfully build and install mono 6.13.0????
