### ISSUE TITLE
Sonarr V3 import failed for some episodes

### ISSUE THREAD

**Issue by DFKnight** [Sonarr/Sonarr#4114]
**Describe the bug**
I'm not sure exactly how to replicate this issue, but some anime episodes that I download using Sonarr V3 are not getting imported automatically. I am seeing an "Import Failed" message on the series page, and "Waiting to Import" in the Activity -> History page.

**Screenshots**
![image](https://user-images.githubusercontent.com/295134/99905908-da5fcb80-2ca1-11eb-8b83-f850ede4127c.png)
![image](https://user-images.githubusercontent.com/295134/99906039-9f11cc80-2ca2-11eb-812c-db3a11702055.png)

**Logs**
https://mega.nz/file/VF4miC4b#XRO3vh7789mf8colYYcdnKpls2JxC0fzLcPZtsmnUoI

**System Information**

 - Sonarr Version: 3.0.4.1019
 - Operating System: TrueNAS 12.0-STABLE
 - mono Version: mono 6.8.0.96

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
