### ISSUE TITLE
Path name issues when migration from windows to linux

### ISSUE THREAD

**Issue by p928s1984** [Sonarr/Sonarr#4115]
When migrating from windows to linux, the path for the movies can not be edited via the "Series editor" for root path. 

Example:

Windows TV located at:
F:\TV\
Linux TV located at: 
/tv/

When you try to use the "root folder editor" 
you get "/tv/F:\TV\{seriesname}

No errors log files 

Server
 - Sonarr Version: 2.0.0.5344
 - Operating System: Docker

Client
 - OS: windows
 - Browser: Chrome and FF

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

Regardless, v2 is not seeing any significant future development....I also don't think this is a problem on v3.

**Comment by p928s1984** [comment]
I am sure that this is a very unique case. Just thought I would shoot over a bug so it was known.

**Comment by Taloth** [comment]
No you can't migrate, not without editing the database.

https://github.com/Sonarr/Sonarr/wiki/Backup-and-Restore#restoring-from-backup
