### ISSUE TITLE
Server Side Pushable Healthcheck

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4116]
**Is your feature request related to a problem? Please describe.**
In a handful of cases, it may be necessary to push a communication to end users as manual intervention is required.  Such as when the updater is broke due to permissions (whoopsie...)

**Describe the solution you'd like**
Dismissible health check that is triggered by a skyhook feed and can be targeted to various installations

**Describe alternatives you've considered**
Carrier Pigeons?
Smoke signals?
Reddit doesn't reach enough user base.
Discord doesn't reach enough user base.

**Additional context**
Notes from Q:
> Just make a feed from the server, keep track of which ones client has seen and dismissed. And be able to tailor them to client is, arch or runtime

Requires Skyhook changes as well

**Comment by markus101** [comment]
Related to https://github.com/Sonarr/Sonarr/issues/481

**Comment by Qstick** [comment]
I've renamed this to drop `dismissible` which as markus mentioned is already covered in #481. 

For reference, the implementation on downstream forks
https://github.com/Radarr/Radarr/commit/cae5badee09c1fbed2b04282a2bb4b1666add6b4

and Services side
https://github.com/Servarr/ServarrAPI.Update/commit/6137386830b3f4a9af694c77e259fa75c5a92392
