### ISSUE TITLE
Restart function shuts down the server

### ISSUE THREAD

**Issue by costaht** [Sonarr/Sonarr#4117]
**Describe the bug**
Every day when Sonarr tries to update itself, it fails to restart the service. The same behavior is seen when you try to restart the server using the GUI menu. In summary, I've been having to manually restart  my Sonarr every few hours.

**Logs**
These are the messages I see on journalctl in different days:

https://paste.centos.org/view/1ccd3136

I enabled tracing logs and tried to manually restart the service using the GUI:

https://paste.centos.org/view/9b4da367

**System Information**

 - Sonarr Version: 3.0.4.1021
 - Operating System: Fedora 33
 - .net Framework (Windows) or mono (macOS/Linux) Version: 6.8.0.123

**UI Bugs:**
 - OS: Fedora
 - Browser: Brave
 - Version: Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

**Comment by bakerboy448** [comment]
Likely going to close this as a support request

But for the love that is all sane; please put those logs in a pastebin and just link here

**Comment by costaht** [comment]
Do you think that's a problem with my setup?

**Comment by Taloth** [comment]
It's probably your setup yes.

What you want to check is two things:
- Your systemd unit file, it's possibly not configured properly. Particularly the KillMode= & Restart= options
- The UpdateLog log file, it details the update and restart process. Particularly the last part. 

Finally, Restart via the gui doesn't work with systemd involved. Don't use it. (It's a known issue) In fact, with the correct systemd unit the 'Shutdown' option actually causes a restart.

**Comment by costaht** [comment]
Can you give the link of an ideal init file? I'm using a adapted version from V2 tutorial and it doesn't mention anything about killmode

**Comment by costaht** [comment]
Just found on reddit someone using these two parameters:
```
KillMode=process
Restart=on-failure
```
After adding them, restart seems to work fine. If the service stays up until the end of the day I'll close this issue.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
