### ISSUE TITLE
Update causes systemd to lose track of sonarr process

### ISSUE THREAD

**Issue by springjools** [Sonarr/Sonarr#4118]
**Describe the bug**
Sonarr update causes systemd to lose track of the process. Sonarr is running but systemd shows it as dead. The reason seems to be in (20-11-23 14:08:14.1|Info|TerminateNzbDrone|Killing all running processes). 

It tries to kill all processes with the name Sonarr but cannot find any. I can also not manually find any running sonarr process with sudo killall Sonarr

**Screenshots**

**Logs**
Link to debug or trace log files.
Updatelog from the relevant update:
https://pastebin.com/G6F921nq

**System Information**
Debian 10 rpi 3b buster
 - Sonarr Version: [e.g. 2.0.0.1]
/usr/lib/sonarr/bin/Sonarr.exe - Version 3.0.4.1021
 - Operating System: [e.g. Windows 10]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]
Mono: 
Mono JIT compiler version 6.12.0.90 (tarball Fri Sep  4 14:28:48 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]
![image](https://user-images.githubusercontent.com/5911982/100067054-732b4e00-2e3e-11eb-861f-edf51812b50b.png)

**Additional context**
![image](https://user-images.githubusercontent.com/5911982/100066447-c94bc180-2e3d-11eb-92f7-0a15350456f5.png)

**Comment by Taloth** [comment]
And a few lines later it kills the running sonarr process.

Check your syslog for systemd messages about detecting that sonarr died. Systemd gets like 10 seconds to restart sonarr, and it doesn't.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

**Comment by springjools** [comment]
Ok, it kills 28864 but not processes 24113, 24114, 24115 or 24936, 26336 or any of the further processes

**Comment by springjools** [comment]
I also posted in support but I thought this was a bug
