### ISSUE TITLE
Not automatically importing because not correctly parsing Vuze Web API response

### ISSUE THREAD

**Issue by jjjshpmy** [Sonarr/Sonarr#4120]
### System Information/Logs

**Sonarr Version:**
hotio/sonarr:nightly (phantom-develop 3.0.4.1009)

**Link to Log Files (debug or trace):** 
https://pastebin.com/82X4JZcC

### Additional Information

As you can see from the trace, sonarr does not detect that the download has completed, hence no import is ever attempted.

Already went support channels, was determined that this is a bug since the Vuze API returns the correct response in Line 140, but sonarr isn't detecting it.

**Comment by markus101** [comment]
> Already went support channels, was determined that this is a bug since the Vuze API returns the correct response in Line 140, but sonarr isn't detecting it.

Please link to the discussion you had about this already. I don't see Sonarr processing it at all.

Do you have a category set in Sonarr's Vuze settings?
Does it show in Activity: Queue? If so, what does it show if you hover over the icon on the left?
Was this torrent previously grabbed and imported?

Please leave trace logging enabled, then restart Sonarr, after a couple minutes post the logs from the startup to Sonarr to the time you grab them.

**Comment by jjjshpmy** [comment]
This might be the issue, also note this is a code snippet from radarr but sonarr logic is the same
https://github.com/Radarr/Radarr/blob/master/src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs#L62

Category is set as sonarr
Directory is not set

1) sonarr sends Vuze a torrent-add request with download location sonarr (from category)
2) Vuze begins downloading file into "downloads/incomplete/sonarr/{show}" (from category)
3) sonarr checks in with Vuze, sees progress in "downloads/incomplete/sonarr/{show}"
4) Vuze finishes download, moves file into "downloads/completed/{show}"
5) sonarr checks in with Vuze, sees nothing in "downloads/incomplete/sonarr", sees files in "downloads/completed/{show}" but ignores them because sonarr is not in directory path (code snippet above)
6) no attempt at import is made

This is not a problem with other clients because 1) they don't use transmission API and 2) they can set the tag in the client. Right now category isn't actually acting as a category for Vuze, it's acting as a download directory

Possible solutions
- (user) Use the same folder for complete and incomplete files
- (user) Don't set a category
- (dev) Have sonarr send the cateogry to Vuze as a tag (either through modifying .torrent or transmission request)

**Comment by markus101** [comment]
> sonarr checks in with Vuze, sees nothing in "downloads/incomplete/sonarr", sees files in "downloads/completed/{show}" but ignores them because sonarr is not in directory path (code snippet above)

Yup, that'll do it and why I asked the questions I did.

> (dev) Have sonarr send the cateogry to Vuze as a tag (either through modifying .torrent or transmission request)

Does the Vuze API actually have a way to specify a category/tag/label (whatever they call it)? It's not listed here: https://wiki.vuze.com/w/Vuze_Web_Remote, but that hasn't been updated since 2014 nor do I see it in `rpc-spec.txt` included with the plugin.

If there is not a method in the API to support it then it's not something Sonarr can set and Sonarr will not modify torrent files.

The other requirement will be a way to filter on the category/tag/label either only getting results in the category back from Vuze (best) or a property with the category/label so Sonarr can filter.

**Comment by Taloth** [comment]
We still need the trace logs markus asked.

**Comment by markus101** [comment]
Still interested in knowing where it was determined this was a bug in Sonarr, because this looks more like an issue in Vuze (doesn't maintain the full relative directory structure when moving completed torrents).
