### ISSUE TITLE
Change interval lmport List Sync

### ISSUE THREAD

**Issue by fana13** [Sonarr/Sonarr#4123]
**Describe the problem**
Change interval lmport List Sync to reduce 1 per day

**Describe any solutions you think might work**
Unlike Radarr, have an option to choose the interval time to sync list

**Additional context**

**Comment by markus101** [comment]
> Describe the problem
Change interval lmport List Sync to reduce 1 per day

This isn't a description of the problem, please explain why an option to change the interval would be beneficial.

**Comment by fana13** [comment]
Sorry.
For example, i use a trakt watch list.
When i add a favorite serie on trakt, i would have a quick sync, not wait one day.

**Comment by knowair** [comment]
I 'd appreciate this too even if it were just a change from daily to hourly that'd be great. thanks.

**Comment by bakerboy448** [comment]
You can manually trigger a list import in tasks or via the api.

I don't see a use case not already covered via other means here.

**Comment by bakerboy448** [comment]
Closing

No plans for this, not the intended use case for lists, several acceptable workarounds; script it via the API if they do desire.

Lists are more of a hey add this eventually

If you want it now add it to sonarr directly; perhaps via Ombi or similar apps if you don’t want to go directly to sonarr.

Alternatively use the API to trigger a refresh

**Comment by fana13** [comment]
Could you give me the syntax of API to trigger of that task please ?
I've been search for but i don't found it
Thanks
