### ISSUE TITLE
[Bug] Proxy Not Working

### ISSUE THREAD

**Issue by zero77** [Sonarr/Sonarr#4125]
**Describe the bug**
I have added a socks proxy with "Bypass Proxy for Local Addresses" unchecked.
The proxy server has the Jacket and qBittorrent running on it.
But, when i change qBittorrent or Jackett to localhost it fails to connect.

I have an identical set up for Radarr and its working.
I have also tested connecting to qBittorrent with curl via the socks proxy and that also works.

**Screenshots**

**Logs**
https://pastebin.com/raw/ida8W8Mh

**System Information**

 - Sonarr Version: 3.0.4.1021
 - Operating System: Debian Sed
 - Mono Version:  6.8.0.105

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by Taloth** [comment]
That's not how proxies work.
You're telling sonarr that qbit is running on the same computer.

**Comment by zero77** [comment]
I should have mentioned, this is a reverse ssh proxy and i am trying to access the applications installed locally in the proxy server.
Like i said this is configured identically in Radarr and its working there.
