### ISSUE TITLE
Adventure Time: Distant Lands incorrectly classified as "specials" for main Adventure Time show.

### ISSUE THREAD

**Issue by irritatedcone** [Sonarr/Sonarr#4126]
**Describe the bug**
Adventure Time: Distant Lands incorrectly classified as "specials" for main Adventure Time show.
This breaks searching (since the search sees it as  different series, and the season and episode numbers don't match).
https://www.imdb.com/title/tt11165358/
![atdl1](https://user-images.githubusercontent.com/44037605/100445893-2057cd80-30ae-11eb-84e6-c46a64c30a76.PNG)
![atdl2](https://user-images.githubusercontent.com/44037605/100445896-2188fa80-30ae-11eb-91ab-b7b2e0f1ec02.png)

**System Information**
Version    3.0.4.1021
Package Version    3.0.4.1021-ls8 by linuxserver.io 
Mono Version    5.20.1.34

**Comment by bakerboy448** [comment]
Not a sonarr issue; fix the TVDB entry

**Comment by Taloth** [comment]
More a limitation, thexem can't map something like that.

**Comment by bakerboy448** [comment]
Scene needs to get onboard with TVDB handling of those episodes (or be using reasonable logic for TheXEM)
