### ISSUE TITLE
Sonarr Hard-links an episode file to a season file

### ISSUE THREAD

**Issue by ArGaMer** [Sonarr/Sonarr#4127]
**Describe the bug**
Sonarr is hard linking every single episode in a season pack to a single file Show.S0X.mkv thus preventing any single episode to be imported but one. the problem is it's renaming files when I don't have renaming enabled.

**Logs**
https://pastebin.com/H3RErQyY

**System Information**

 - Sonarr Version: 3.0.4.1021
 - Operating System: Unraid 6.8.3
 - mono (macOS/Linux) Version: 5.20.1.34

**Comment by markus101** [comment]
Please link a screenshot of your `Episode Naming` settings from Settings: Media Management.

**Comment by ArGaMer** [comment]
> Please link a screenshot of your `Episode Naming` settings from Settings: Media Management.

I don't have renaming enabled so the setting doesn't exist for me.

**Comment by markus101** [comment]
Right, missed that in your first post. This is the same underlying issue as https://github.com/Sonarr/Sonarr/issues/3056
