### ISSUE TITLE
Wrap Long Paths on Episode Detail Screen (Replace Current Truncate Behavior)

### ISSUE THREAD

**Issue by owine** [Sonarr/Sonarr#4131]
**Describe the problem**
On Episode Details screen, the Path is truncated rather than wrapped if it is too long to fit on the line. The full path appears on hover, but this is a pain for copy/paste. There seems to be space to wrap this path to a second line as is done on the History tab.

**Describe any solutions you think might work**
Wrap Path rather than truncate

**Additional context**
Current Episode Details behavior:
<img width="1239" alt="Screen Shot 2020-11-30 at 11 26 31 AM" src="https://user-images.githubusercontent.com/4283702/100643249-69529080-32ff-11eb-8733-47ed99f1c30d.png">
Current Episode History behavior (this would be more preferable):
<img width="1232" alt="Screen Shot 2020-11-30 at 11 27 20 AM" src="https://user-images.githubusercontent.com/4283702/100643258-6e174480-32ff-11eb-8508-9eb7b5b8b716.png">

**Comment by markus101** [comment]
This was fixed in https://github.com/Sonarr/Sonarr/commit/d29e254dcb731f98c115105414b2100218e52560 when it was converted to a table.
