### ISSUE TITLE
Add Original Show Language to local db

### ISSUE THREAD

**Issue by ditmarvisser** [Sonarr/Sonarr#4133]
**Is your feature request related to a problem? Please describe.**
With Tdarr we can remove unwanted language audio tracks from files. You can only configure it to remove certain languages, or keep certain languages. But there is no way to only keep the Original Show Language, since that information is not available.

**Describe the solution you'd like**
Store the Original Show Language to the local serie entry, so the Sonarr API can be called from within Tdarr to filter the audio tracks.

**Describe alternatives you've considered**
You could also make an API call to TVBD, however you would then have to match and parse all those results. It's also better to limit calling external APIs and keep everything in the local machine.

**Additional context**
Same request as in the Radarr repo: https://github.com/Radarr/Radarr/issues/5438. Maybe it's already stored, in that case please expose it to the Sonarr API.

**Comment by Qstick** [comment]
Complete in v4, OriginalLanguage is returned via API
