### ISSUE TITLE
Constant "requires the Mono Framework version 5.20 or later" error

### ISSUE THREAD

**Issue by Rorzzer** [Sonarr/Sonarr#4137]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

## Bug Report
Error when opening sonarr: "requires the Mono Framework version 5.20 or later"

### System Information/Logs

**Sonarr Version: v3**

**Operating System: 10.13.6**

**mono (macOS/Linux) Version: 5.20, 6.10 & 6.12 tried all 3**

**Link to Log Files (debug or trace): https://imgur.com/a/WVVSdFj**

### Additional Information
Note the mono-mdk install error when installing via brew. Also tried installing via the package etc no luck. Sonarr v2 worked fine and Radarr v3 works fine is thats any help.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
