### ISSUE TITLE
Import after torrent announcement: Square Brackets not escaped

### ISSUE THREAD

**Issue by pollev** [Sonarr/Sonarr#4139]
**Describe the bug**
Hello, Sonarr has issues when importing completed downloads if the top level folder of that download contains square brackets.
The error is show in the sonarr log. The issue is probably that the square brackets are not escaped properly. Removing the square brackets from the file and re-announcing the torrent completion will immediately fix the issue. I assume that this issue is Linux specific.

**Logs**
`DownloadedEpisodesImportService: Import failed, path does not exist or is not accessible by Sonarr: /home/polle/xxx/downloads/xxxxxxxxxxxxxx[rartv]`

**System Information**

 - Sonarr Version:     2.0.0.5344
 - Operating System: Ubuntu 18.04.5 LTS
 - .Mono Version: 6.12.0.90

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

Not a bug

You're using Qbt newer than 4.2.5 and that is not compatible with Sonarr v2

**Comment by pollev** [comment]
@bakerboy448 

Thank you. I was not aware their was a V3 version.
Is it stable enough to upgrade or do you recommend downgrading my qBT instance?

**Comment by bakerboy448** [comment]
v3 is considered by many to effectively be an RC, but is technically beta.
Many use it as their daily driver.

use that information as you wish
