### ISSUE TITLE
Filter Blacklisted results from Manual Search

### ISSUE THREAD

**Issue by zenbuffy** [Sonarr/Sonarr#4140]
**Describe the problem**
When doing a manual search, items which are rejected for all reasons are represented with the same icon (red warning symbol). It is the same symbol regardless of reject reason, which means that you have to hover over the symbol to get the actual reject reason. There is no easy way to see in the list, without checking each individually, if the item is rejected due to quality, size, or blacklisted. While you may still want to avoid blacklisted releases, you may manually override quality/size settings if this is the only release available.

**Describe any solutions you think might work**
Option one: A UI button or filter which allows you to hide releases which are rejected due to being blacklisted.
Option two: Additional UI icons which can better indicate _why_ a release was rejected - e.g. orange warning icon for quality/size, and retain the red icon for blacklisted.
Option three: implement both of the above, so that you can see at a glance a reject reason, and can filter blacklisted releases leaving only the others to filter through. 

Potential future expansion to have additional icons for some other common reasons, e.g. language, unless this is too noisy.

**Additional context**

All of these releases are rejected
<img width="485" alt="Screenshot 2020-12-02 at 12 51 47" src="https://user-images.githubusercontent.com/7373848/100875095-6ee5dd00-349d-11eb-9164-0936d09989af.png">
But you need to hover to see that not all of them are blacklisted, just some are too large.
<img width="517" alt="Screenshot 2020-12-02 at 12 51 56" src="https://user-images.githubusercontent.com/7373848/100875098-70afa080-349d-11eb-9b23-110da98c4926.png">
<img width="366" alt="Screenshot 2020-12-02 at 12 52 05" src="https://user-images.githubusercontent.com/7373848/100875102-71483700-349d-11eb-9674-4c0e6ed7f983.png">

**Comment by zenbuffy** [comment]
Similar effort here in the Radarr repo: https://github.com/Radarr/Radarr/pull/5008

**Comment by bakerboy448** [comment]
Duped by
#3955 
#4132
