### ISSUE TITLE
Toggle-able option to remove torrent from download client if better quality release exists in library already

### ISSUE THREAD

**Issue by douglas24** [Sonarr/Sonarr#4142]
**Describe the problem**
In certain circumstances, Sonarr will grab a quality of an episode that is not the most preferred. It then finds a better quality and begins a download for it, so two downloads are happening at once. If the better quality download finishes first, the worse quality download (which would be removed if it had existed in the library and replaced with the better quality) is left in the download client to finish downloading, but Sonarr won't import it (because it's worse quality) and it should ideally be able to remove that worse quality episode from the download client.

**Describe any solutions you think might work**
A toggle-able feature (some people may not want it automatic) in the download client section so that if sonarr deletes any worse quality releases from the download client if it already grabbed and imported a better version.

**Additional context**
For example, Sonarr grabs a release for Linux in 720p but before that finishes downloading, it finds and grabs a release for it in 1080p which downloads faster than the 720p release and gets imported. Sonarr leaves the 720p release in the download client instead of automatically deleting/overriding it (which it does when grabbing, importing, and replacing things in the library.

**Comment by markus101** [comment]
This is not something we have plans to support, the best way to avoid this issue would be to use delays to prevent grabbing a lower quality release immediately.
