### ISSUE TITLE
Sonarr (Container) freezes randomly / Locks Docker Daemon

### ISSUE THREAD

**Issue by davidh2k** [Sonarr/Sonarr#4144]
For some time I encounter random freezes of a Sonarr v3 Docker Container. It locks that hard, that only a reboot helps. You can't even restart the Docker Daemon.

The Container is frozen again now, my recent debug and trace log entries (last 40 ones) are as follows:

`tail -n 40 sonarr.debug.txt
20-12-3 00:28:52.2|Debug|Parser|Episode Parsed. Z Nation - S01E05
20-12-3 00:28:52.2|Debug|Parser|Language parsed: German
20-12-3 00:28:52.2|Debug|QualityParser|Trying to parse quality for Z.Nation.S01E05.German.AC3.DL.1080p.BDRip.x265-FuN.mkv
20-12-3 00:28:52.2|Debug|Parser|Quality parsed: Bluray-1080p v1
20-12-3 00:28:52.2|Debug|Parser|Release Group parsed: FuN
20-12-3 00:28:52.2|Debug|Parser|Parsing string 'Z.Nation.S01.German.AC3.DL.1080p.BDRip.x265-FuN'
20-12-3 00:28:52.2|Debug|Parser|Episode Parsed. Z Nation - Season 01
20-12-3 00:28:52.2|Debug|Parser|Language parsed: German
20-12-3 00:28:52.2|Debug|QualityParser|Trying to parse quality for Z.Nation.S01.German.AC3.DL.1080p.BDRip.x265-FuN
20-12-3 00:28:52.2|Debug|Parser|Quality parsed: Bluray-1080p v1
20-12-3 00:28:52.2|Debug|Parser|Release Group parsed: FuN
20-12-3 00:28:52.2|Debug|VideoFileInfoReader|Getting media info from /downloads/tv/Z.Nation.S01.German.AC3.DL.1080p.BDRip.x265-FuN/Z.Nation.S01.German.AC3.DL.1080p.BDRip.x265-FuN/Z.Nation.S01E05.German.AC3.DL.1080p.BDRip.x265-FuN.mkv
20-12-3 00:28:52.2|Debug|PlexServer|Performing library update for 1 series
20-12-3 00:28:52.2|Debug|PlexServerService|Sending Update Request to Plex Server
20-12-3 00:28:52.2|Debug|PlexServerService|Getting sections from Plex host: plex.willgucken.de
20-12-3 00:28:52.2|Debug|Parser|Parsing string 'Z.Nation.S01E05.German.AC3.DL.1080p.BDRip.x265-FuN'
20-12-3 00:28:52.2|Debug|PlexServerProxy|Url: https://plex.willgucken.de:443/library/sections?X-Plex-Client-Identifier=(removed)&X-Plex-Product=Sonarr&X-Plex-Platform=Windows&X-Plex-Platform-Version=7&X-Plex-Device-Name=Sonarr&X-Plex-Version=3.0.4.1011&X-Plex-Token=(removed)
20-12-3 00:28:52.2|Debug|Parser|Episode Parsed. Z Nation - S01E05
20-12-3 00:28:52.2|Debug|Parser|Language parsed: German
20-12-3 00:28:52.2|Debug|QualityParser|Trying to parse quality for Z.Nation.S01E05.German.AC3.DL.1080p.BDRip.x265-FuN
20-12-3 00:28:52.2|Debug|Parser|Quality parsed: Bluray-1080p v1
20-12-3 00:28:52.2|Debug|Parser|Release Group parsed: FuN
20-12-3 00:28:52.2|Debug|AggregateLanguage|Using language: German
20-12-3 00:28:52.2|Debug|AggregateQuality|Using quality: Bluray-1080p v1
20-12-3 00:28:52.2|Debug|Parser|Parsing string 'Z.Nation.S01E05.German.AC3.DL.1080p.BDRip.x265-FuN'
20-12-3 00:28:52.2|Debug|Parser|Episode Parsed. Z Nation - S01E05
20-12-3 00:28:52.2|Debug|Parser|Language parsed: German
20-12-3 00:28:52.2|Debug|QualityParser|Trying to parse quality for Z.Nation.S01E05.German.AC3.DL.1080p.BDRip.x265-FuN
20-12-3 00:28:52.2|Debug|Parser|Quality parsed: Bluray-1080p v1
20-12-3 00:28:52.2|Debug|Parser|Release Group parsed: FuN
20-12-3 00:28:52.2|Debug|EpisodeFileMovingService|Moving episode file: /downloads/tv/Z.Nation.S01.German.AC3.DL.1080p.BDRip.x265-FuN/Z.Nation.S01.German.AC3.DL.1080p.BDRip.x265-FuN/Z.Nation.S01E05.German.AC3.DL.1080p.BDRip.x265-FuN.mkv to /tvshows/Z Nation/Season 01/Z.Nation.S01E05.Home.Sweet.Zombie.Bluray-1080p.mkv
20-12-3 00:28:52.2|Debug|DiskTransferService|Move [/downloads/tv/Z.Nation.S01.German.AC3.DL.1080p.BDRip.x265-FuN/Z.Nation.S01.German.AC3.DL.1080p.BDRip.x265-FuN/Z.Nation.S01E05.German.AC3.DL.1080p.BDRip.x265-FuN.mkv] > [/tvshows/Z Nation/Season 01/Z.Nation.S01E05.Home.Sweet.Zombie.Bluray-1080p.mkv]
20-12-3 00:28:52.2|Debug|PlexServerService|Updating Plex host: plex.willgucken.de, Section: 11
20-12-3 00:28:52.2|Debug|PlexServerProxy|Url: https://plex.willgucken.de:443/library/sections/11/refresh?X-Plex-Client-Identifier=(removed)&X-Plex-Product=Sonarr&X-Plex-Platform=Windows&X-Plex-Platform-Version=7&X-Plex-Device-Name=Sonarr&X-Plex-Version=3.0.4.1011&X-Plex-Token=(removed)
20-12-3 00:28:52.2|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
20-12-3 00:28:52.2|Debug|PlexServerService|Finished sending Update Request to Plex Server (took 36 ms)
20-12-3 00:28:57.3|Debug|SabnzbdProxy|Url: http://sabnzbd:8080/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
20-12-3 00:28:57.3|Debug|SabnzbdProxy|Url: http://sabnzbd:8080/api?mode=history&start=0&limit=60&category=tv&apikey=(removed)&output=json
20-12-3 00:28:57.4|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
20-12-3 00:29:26.5|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
`

`tail -n 40 sonarr.trace.txt
20-12-3 00:28:57.4|Trace|CommandQueueManager|Publishing ProcessMonitoredDownloads
20-12-3 00:28:57.4|Trace|CommandQueueManager|Checking if command is queued or started: ProcessMonitoredDownloads
20-12-3 00:28:57.4|Trace|CommandQueueManager|Command is already in progress: ProcessMonitoredDownloads
20-12-3 00:28:57.4|Trace|CommandQueueManager|Updating command status
20-12-3 00:28:57.4|Trace|EventAggregator|Publishing CommandExecutedEvent
20-12-3 00:28:57.4|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
20-12-3 00:28:57.4|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Download.RefreshMonitoredDownloadsCommand
20-12-3 00:28:57.4|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
20-12-3 00:28:57.4|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
20-12-3 00:28:57.4|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
20-12-3 00:28:57.4|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
20-12-3 00:28:57.4|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
20-12-3 00:28:57.4|Trace|CommandExecutor|RefreshMonitoredDownloadsCommand <- DownloadMonitoringService [00:00:00.1269840]
20-12-3 00:28:57.4|Trace|Http|Req: 24298 [GET] /api/v3/command (from 84.*.*.206 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36)
20-12-3 00:28:57.4|Trace|CommandQueueManager|Getting all commands
20-12-3 00:28:57.4|Trace|Http|Res: 24298 [GET] /api/v3/command: 200.OK (1 ms)
20-12-3 00:28:57.4|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
20-12-3 00:29:09.1|Trace|Http|Req: 24299 [GET] / (from 127.0.0.1 curl/7.58.0)
20-12-3 00:29:09.1|Trace|Http|Res: 24299 [GET] /: 200.OK (0 ms)
20-12-3 00:29:26.5|Trace|Scheduler|Pending Tasks: 1
20-12-3 00:29:26.5|Trace|CommandQueueManager|Publishing MessagingCleanup
20-12-3 00:29:26.5|Trace|CommandQueueManager|Checking if command is queued or started: MessagingCleanup
20-12-3 00:29:26.5|Trace|CommandQueueManager|Inserting new command: MessagingCleanup
20-12-3 00:29:26.5|Trace|CommandExecutor|MessagingCleanupCommand -> CleanupCommandMessagingService
20-12-3 00:29:26.5|Trace|CommandQueueManager|Marking command as started: MessagingCleanup
20-12-3 00:29:26.5|Trace|CommandQueueManager|Cleaning up old commands
20-12-3 00:29:26.5|Trace|CommandQueueManager|Updating command status
20-12-3 00:29:26.5|Trace|EventAggregator|Publishing CommandExecutedEvent
20-12-3 00:29:26.5|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
20-12-3 00:29:26.5|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Messaging.Commands.MessagingCleanupCommand
20-12-3 00:29:26.5|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
20-12-3 00:29:26.5|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
20-12-3 00:29:26.5|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
20-12-3 00:29:26.5|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
20-12-3 00:29:26.5|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
20-12-3 00:29:26.5|Trace|CommandExecutor|MessagingCleanupCommand <- CleanupCommandMessagingService [00:00:00.0029280]
20-12-3 00:29:26.5|Trace|Http|Req: 24300 [GET] /api/v3/command (from 84.*.*.206 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36)
20-12-3 00:29:26.5|Trace|CommandQueueManager|Getting all commands
20-12-3 00:29:26.5|Trace|Http|Res: 24300 [GET] /api/v3/command: 200.OK (1 ms)
20-12-3 00:29:26.5|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
`

I'm a bit lost as to what causes this (sonarr itself, api notification for emby script, google drive...). No other container is having this issue.

Greetings
David

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

Capturing trace logs of standard output/error to a file will be the first step to troubleshoot.
