### ISSUE TITLE
Use theme from Radarr v3

### ISSUE THREAD

**Issue by andrewatwood** [Sonarr/Sonarr#4145]
**Describe the problem**
Radarr just released their first v3 releases which includes a new UI.

**Describe any solutions you think might work**
Wondering if anyone has explored borrowing this UI (screenshot attached) to implement in Sonarr.

![radarr_v3_ui](https://user-images.githubusercontent.com/8690529/101044809-634df100-3545-11eb-8a8e-6a3edaeb7a97.png)

**Comment by bakerboy448** [comment]
Sonarr has it on v3 (and had it first) radarr forked from that.

**Comment by andrewatwood** [comment]
Oh lol whoops nvm, I guess my auto-updates are off

**Comment by bakerboy448** [comment]
Or you're on v2 and not v3 (beta) phantom-develop
