### ISSUE TITLE
Sonarr doesn't find any releases for "The People's Court"

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [Sonarr/Sonarr#4146]
**Describe the bug**
Sonarr doesn't find any releases for "The People's Court". Nothing comes up when searching for episodes for the show. But searching on my indexer's website there are tons of matches.

**System Information**

 - Sonarr Version: 3.0.4.1023
 - Operating System: Linux
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 5.20.1.19
 - Branch: Dev

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.
