### ISSUE TITLE
"series" URL base breaks series pages in v3

### ISSUE THREAD

**Issue by danepowell** [Sonarr/Sonarr#4148]
**Describe the bug**
When Sonarr runs under a "series" URL base, trying to access any series page (i.e. for a particular TV show) from the web UI results in a 404 in Sonarr v3. This wasn't a problem in v2.

For instance, if my server is localhost and URL base is "series", and I'm trying to access American Ninja Warrior, the UI takes me to https://localhost/series/american-ninja-warrior, which results in a 404 because the link _should_ be https://localhost/series/series/american-ninja-warrior

**Logs**
https://pastebin.com/tiX89Gn7

**System Information**

 - Sonarr Version: 3.0.4.1023
 - Operating System: Ubuntu 20.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. .net 4.5 or mono 5.12]
 - Branch: phantom-develop

**UI Bugs:**
 - OS: MacOS
 - Browser: Chrome
 - Version: [e.g. 22]

**Comment by RobinDadswell** [comment]
Hi @danepowell,

I have just replicated this in my dev environment however I have a couple of questions: 
- Are you using a a reverse proxy solution? 
- Is using "series" a requirement or could you utilise another URL base (if you need a URL base at all)? 

URL base is meant to be used in reverse proxy scenarios to proxy a single domain to multiple different webpages. When setting a URL base all this actually does is enable a secondary listener address as per the following screenshot
![image](https://user-images.githubusercontent.com/19610103/101654911-ef29b680-3a38-11eb-9052-8d4e9b43cea6.png)

as such "https://localhost/series/american-ninja-warrior" would be an acceptable URL for the standard localhost binding.

**Comment by danepowell** [comment]
I use an Apache reverse proxy:
```bash
/etc/apache2$ cat conf-enabled/sonarr.conf
<Location /series>
  ProxyPass http://localhost:8989/series
  ProxyPassReverse http://localhost:8989/series
</Location>
```

I don't actually access it from localhost, but from elsewhere on the network via the hostname.

Of course I could choose any other URL base, I just chose "series" to be consistent with how Sonarr describes itself.

**Comment by thezoggy** [comment]
and did you set the needed setting in sonarr v3: settings > general > url base ?

**Comment by danepowell** [comment]
Yep I set the URL base:
![screenshot-daenerys-2020 12 09-16_45_03](https://user-images.githubusercontent.com/1984514/101706446-f1dada80-3a3d-11eb-9354-98974da524a7.png)

**Comment by thezoggy** [comment]
and if you change the base to 'sonarr' or 'tv' - do you see a difference?

**Comment by danepowell** [comment]
Yes, any other base works. It's only if the URL base is '/series' that the error occurs.

**Comment by thezoggy** [comment]
seems like an easy fix then, dont use series? as for why you cant register that url.. prob because sonarr already registered it for its app and cant do the same thing (nested) like `/series/series`

**Comment by bakerboy448** [comment]
@markus101 do we just add a validation to not use series and call it a day? or?

**Comment by markus101** [comment]
The logic to determine if the URL needs to be appended is pretty dumb, does this path start with the URL base, if yes, do nothing, if no, add it. It _might_ be possible to better handle that, but the effort to do so probably isn't worth the reward so a handful of people can use `/series` as their URL base.

Validation is the direction I've been leaning, we'd need to ignore any route that Sonarr uses, because using `/calendar` as your URL base (regardless of the reasons it doesn't make sense) would fail the same way.

I think we should take a quick stab at fixing it and allowing `/series` (or other UI paths) as the URL base then just validate and move on.

**Comment by RobinDadswell** [comment]
@markus101 do you happen to know where the code for the URL base is (assuming it's in the C# bit) and I will have a stab at it over the weekend

**Comment by markus101** [comment]
No, it's in the JS side. `Link.js` is responsible for appending the URL base when it's not part of the URL. There may not be cases where we pass in links with the URL base already appended, in which case the effort just becomes testing everything after removing that block.

**Comment by RobinDadswell** [comment]
sweet, assign it over and I will look at it this weekend

**Comment by danepowell** [comment]
Thanks all for owning this. I'm not particularly attached to `series` as a URL base (though supporting that would be ideal, it seems like an indicator of a deeper bug). My main concern is that no one else have my experience of the series pages inexplicably 404'ing, and having to spend hours debugging to find this as the root cause.
