### ISSUE TITLE
IPv6 IP host validation. Claims IPv6 address is "invalid"

### ISSUE THREAD

**Issue by Napsterbater** [Sonarr/Sonarr#4149]
**Describe the bug**
When adding a connection, such as Emby, supplying an Ipv6 address in the host field fails to validate, Sonarr compalins that it is not valid. This is with or without the brackets.

**Screenshots**
https://drive.google.com/file/d/1W1Qzg3pdeWPeYUvaa4lB5IoMj50rYmC1/view?usp=sharing

**Logs**
N/A

**System Information**

 - Sonarr Version: 3.0.4.1023
 - Operating System: Windows Server 2019 1809
 - .net Framework (Windows) or mono (macOS/Linux) Version: .net Version 4.7.2
 - Branch: phantom-develop

**Comment by bakerboy448** [comment]
xref; Radarr https://github.com/Radarr/Radarr/issues/5499

**Comment by Qstick** [comment]
Validation in question

https://github.com/Sonarr/Sonarr/blob/39589b8c02a95d1ebdb14387d07abf56302dd4e7/src/NzbDrone.Core/Validation/RuleBuilderExtensions.cs#L28

**Comment by RobinDadswell** [comment]
There is quite a good regex that can be found [here](https://community.helpsystems.com/forums/intermapper/miscellaneous-topics/5acc4fcf-fa83-e511-80cf-0050568460e4?_ga=2.113564423.1432958022.1523882681-2146416484.1523557976) for IPV6 but it will make that line that @Qstick has put in quite some monster! 
Once you remove the / it looks like this `^\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?\s*$` and this obviously then needs to have the existing regex validator added into this

**Comment by Cookie-Monster-Coder** [comment]
+1 still an issue in end of 2022
