### ISSUE TITLE
Sonarr refusing to accept connections

### ISSUE THREAD

**Issue by notthisperson21** [Sonarr/Sonarr#4151]
I've been having an issue for the last several weeks on ver 2.0.0.5344 where Sonarr will stop accepting connections when accessed via IP and the indexers seem to stop working.

Oddly enough, the logs show no errors whatsoever but also seem to stop adding new entries when the issue starts. It's easily fixed with a restart of docker, but the issue will inevitably recur within a few days

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.
