### ISSUE TITLE
Change backup location

### ISSUE THREAD

**Issue by corydorning** [Sonarr/Sonarr#4152]
**Describe the problem**
Allow changing the backup location, which would safeguard against disk failure

**Describe any solutions you think might work**
Radarr v3 currently provides this feature, allowing backups to be saved to iCloud on a Mac.

**Comment by markus101** [comment]
You can do this in v3 which Radarr v3 is built off of.

**Comment by corydorning** [comment]
Is it In a different location than radarr? Couldn’t find it.

**Comment by markus101** [comment]
It's at the bottom of General Settings:
![image](https://user-images.githubusercontent.com/413544/101650977-68052000-39f1-11eb-8741-442af98f45a2.png)

Make sure advanced settings are shown (same as Radarr).
