### ISSUE TITLE
Search for anime episodes with absolute AND seasonal episode formats

### ISSUE THREAD

**Issue by reconman** [Sonarr/Sonarr#4153]
**Describe the problem**
Some anime releases like Attack on Titan have different subbing groups with different naming schemes. Some use `Shingeki no Kyojin 60`, some `Shingeki no Kyojin S04E01`, and others `Shingeki no Kyojin S04E01 - 60`.

https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core/IndexerSearch/NzbSearchService.cs#L84 disables the seasonal search when single episodes are searched for.

The second naming scheme will never be found in the indexers, only the ones using the absolute episode numbers.

**Describe any solutions you think might work**
I would suggest doing both a seasonal and non-seasonal search for that episode and combine the results. Of course, duplicates should be eliminated before returning the list. The third naming scheme above will be found by both search methods.

**Additional context**

**Comment by reconman** [comment]
I debugged the source code a bit and guess I was wrong about how the code needs to be changed.

Most anime torrent sites don't have season and episode search support, which the "Standard" search relies on. So you would have to then put the SXXEXX string into the q= parameters instead of the absolute episode number.

**Comment by thezoggy** [comment]
Anime uses abs. Standard uses SxxExx. So just change series type and it will also change how to search/what matches

**Comment by reconman** [comment]
> Anime uses abs. Standard uses SxxExx. So just change series type and it will also change how to search/what matches

Except that Sonarr can't search for SxxExx on most anime indexers. It will simply skip them. Only animetosho via Jackett seems to work.

**Comment by thezoggy** [comment]
if its in standard naming format then it usually means your talking about scene releases rather than p2p stuff. and for standard naming just let it search normal indexers (rather than trying to force it on anime only). example of this is like pokemon.  works just fine as 'standard' (dont treat it as anime)

**Comment by reconman** [comment]
Afaik "scene" IS p2p for anime.

Name me one popular non-anime indexer which offers `Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari`. (I picked a random show from this season)

**Comment by thezoggy** [comment]
I'd be shocked if there was any scene releases for a non mainstream anime. yeah nothing in predb for "Suppose a Kid From the Last Dungeon Boonies Moved to a Starter Town"  but anyways, again if you want sonarr to use standard SxxExx then use standard. if you want it to do absolute then use anime.

**Comment by Sada-Mio** [comment]
> 
> 
> Anime uses abs. Standard uses SxxExx. So just change series type and it will also change how to search/what matches

I tried changing series type from anime to stand. But, for some reason log show it doesn't use/call any of my anime indexer. Have nyaa as indexer directly and nyaa.si via jackett.

**Comment by winklevos** [comment]
I think this discussion should be reopened. Anime while yes it uses absolute numbering does also have season based results, and by excluding them you will miss most of the batch / folder and download each ep individually when doing a full search. In the case of Attack on Titan for example I was getting poor results in Sonarr. However, manually searching season x returned many packs that were better

**Comment by bakerboy448** [comment]
@winklevos this discussion was never closed?

And you can toggle between standard and anime series types for shows as needed.

the issue generally lies around anime trackers not supporting any sane search and thus requiring text based queries combined with poor indexing

see the comments on 10 and 11 of Jan

**Comment by winklevos** [comment]
Yeah apologies @bakerboy448 the closed icon was there from the related mention. 

> And you can toggle between standard and anime series types for shows as needed. 
I understand it just limits possible outputs on shows which get treated in both. Plus some indexers are only configured for anime category and so switching won't search them.

You can do much about bad data but right now I cannot get good results for certain things, i think especially in interactive season or show searches it should do text base queries. Plus because it queries for each episode it is much slower
