### ISSUE TITLE
can't search tv show by tvdb id

### ISSUE THREAD

**Issue by TiburceRichardeau** [Sonarr/Sonarr#4157]
**Describe the bug**
When I search for this tvdb : 287306 sonarr doesn't find anything, maybe because the tvdb has 6 digits instead of 5 usually?
https://www.thetvdb.com/series/287306-show
others shows like 71663 works
**Screenshots**
![image](https://user-images.githubusercontent.com/1525387/101981117-db659680-3c6a-11eb-8c14-14d547bbd0b4.png)
![image](https://user-images.githubusercontent.com/1525387/101981130-fa642880-3c6a-11eb-8644-52c190ec072d.png)

**Logs**
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/5682858/sonarr.txt)

**System Information**

 - Sonarr Version: 3.0.4.1024
 - Operating System: Windows 10 20H2
 - .net Framework : Windows .net 5.0.1
 - Branch: master

**UI Bugs:**
 - OS: Windows 10 20H2
 - Browser: google chrome
 - Version: 87

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

That series lacks an English translation, this is covered in the FAQ.
