### ISSUE TITLE
Manual Import for All Files on Series Page is unreasonably slow

### ISSUE THREAD

**Issue by rg9400** [Sonarr/Sonarr#4161]
**Describe the bug**
If you need to remap files to episodes for a show, the best method I have found is to use the Manual Import option found on the Series Page. However, it seems like for any series with more than 10 episodes, switching the filter from Unmapped Files (which won't work since the targeted files have already been mapped) to All Files just spins until it usually times out. I have to often close the modal, then rerun the process maybe 3-4 times for it to finally load all the episodes. This indicates that it is loading some type of data but timing out before it finishes. I do use GDrive for the files, but it shouldn't have an issue for just pulling filenames. It may be slowing performance if Sonarr is actually scanning the files for MediaInfo, but I don't see why that would be needed for files that are already mapped.

I think there's probably some type of optimization required here, but a temporary workaround could be to give the option to run this import at a season level to avoid trying to load data for shows that may have over 100 episodes. Sometimes the remapping requires across season work, but most cases should be within a single season.

**Logs**
No errors in the logs, just extreme slowness. But let me know if you need some specific logs

**System Information**

 - Sonarr Version: [e.g. 2.0.0.1] 3.0.4.1024
 - Operating System: [e.g. Windows 10 2004] Docker (hotio image) running in WSL2
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. .net 4.5 or mono 5.12] Mono 6.10.0.104
 - Branch: Phantom-Develop

**UI Bugs:**
 - OS: [e.g. Windows] Windows 10
 - Browser: [e.g. chrome, firefox] Microsoft Edge
 - Version: [e.g. 22] Version 88.0.705.18 (Official build) beta (64-bit)

**Additional context**

**Comment by markus101** [comment]
Nothing in Sonarr will timeout, sounds like it's being used with a reverse proxy and that is timing out before Sonarr can respond.

> It may be slowing performance if Sonarr is actually scanning the files for MediaInfo, but I don't see why that would be needed for files that are already mapped.

That's definitely what's happening, anything Sonarr has store is ignored, it's not re-using the existing Media Info, or anything else and not something we have plans to do.

No plans for this at the season level either or not processing files in larger series at this time.
