### ISSUE TITLE
Reject (must not contain) according to MediaInfo?

### ISSUE THREAD

**Issue by cphmichael** [Sonarr/Sonarr#4165]
Version: 3.0.4.1026
Package Version: nightly-fac4b0c-230 by hotio

- - - - -

Sonarr finds "His.Dark.Materials.S02E06.2160p.WEB.H265-GGWP"

I rename with this string:

> {Series TitleYear} - S{season:00}E{episode:00} - {Episode CleanTitle} {[Quality Full]} {[Preferred Words]} {[MediaInfo VideoDynamicRange]} [{MediaInfo VideoBitDepth}bit] {[MediaInfo VideoCodec]} {[MediaInfo-AudioCodec}-{MediaInfo AudioChannels]}{MediaInfo AudioLanguages}{-Release Group}

That results in this Details:

> His Dark Materials (2019) - S02E06 - Malice [WEBDL-2160p] [10bit] [h265] [AAC-2.0]-GGWP

I don't want stereo (2.0) I have therefore setup a "Must Not Contain" AAC-2.0, AAC2.0, but because the indexer string don't include the AudioCodec, AudioChannels, the show is downloaded.

I have tried with "Must Contain" DD.5.1, DD5.1, DDP5.1, DD+5.1 - but then a lot of shows are not downloaded because the AudioCodec, AudioChannels information are missing in the indexer string.

Is it somehow possible to reject shows according to the MediaInfo AudioCodec/AudioChannels?

If not - could that maybe be something to consider implementing in a future version?

**Comment by bakerboy448** [comment]
i'll defer to Markus on this one, but it is not possible currently and I don't foresee it happening strictly from a usability/user not understanding it factor.

**Comment by markus101** [comment]
We do not have plans to reject an import because of media info.
