### ISSUE TITLE
New season of Animaniacs selecting multiple episodes on import

### ISSUE THREAD

**Issue by Kryptonit3** [Sonarr/Sonarr#4166]
**Describe the bug**
When sonarr goes to import the episode, for some reason it is adding it as a multi episode file when it is a single episode.

**Screenshots**
![image](https://user-images.githubusercontent.com/72818445/102252483-21716300-3ed4-11eb-9277-b2aa46837b22.png)

**Logs**
```
20-12-15 17:50:53.8|Debug|ParsingService|Using Scene to TVDB Mapping for: Animaniacs - Scene: 6x03 - TVDB: 6x08, 6x09, 6x10
20-12-15 17:50:53.8|Debug|AggregateQuality|Using quality: WEBDL-1080p v1
20-12-15 17:50:53.8|Debug|EpisodeTitleSpecification|Episode aired more than 1 day ago
20-12-15 17:50:53.8|Debug|EpisodeTitleSpecification|Episode aired more than 1 day ago
20-12-15 17:50:53.8|Debug|EpisodeTitleSpecification|Episode aired more than 1 day ago
20-12-15 17:50:53.8|Debug|SameFileSpecification|No existing episode file, skipping
20-12-15 17:50:53.8|Debug|VideoFileInfoReader|Getting media info from /Plex/Downloads/Complete/Shows/Animaniacs.S06E03.Of.Mice.and.Memes.1080p.HULU.WEB-DL.DDP5.1.H.264-NTb/27e8b171fcb4f59e58710c0932373fdd.mkv
```

**System Information**

 - Sonarr Version: [e.g. 2.0.0.1]
 - Operating System: [e.g. Windows 10 2004]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. .net 4.5 or mono 5.12]
 - Branch:

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by bakerboy448** [comment]
Not a bug; sonarr uses TVDB data and this Hulu Episode 1 has multiple TVDB episodes


For future reference for next time:
Please fill out the template you ignored and provide the trace logs of the manual import, as requested.

**Comment by Kryptonit3** [comment]
@bakerboy448 regardless of TVDB information, the file itself says it is a single episode. Why is Sonarr ignoring that and assuming the single episode file is a multi-episode file? The only solution is manually importing and assigning due to it assuming tvdb is correct.

**Comment by Kryptonit3** [comment]
How it is importing

![image](https://user-images.githubusercontent.com/72818445/102253590-85485b80-3ed5-11eb-8c50-ddd497d01140.png)

How it should import

![image](https://user-images.githubusercontent.com/72818445/102253695-a7da7480-3ed5-11eb-92bb-cdd5210a4691.png)

Synology -> Docker  linuxserver/sonarr:latest

Version
2.0.0.5344
Mono Version
5.20.1.34
AppData directory
/config
Startup directory
/app/sonarr/bin

**Comment by bakerboy448** [comment]
TheXem appears to be coming into play

http://thexem.de/xem/show/5026

given the size of the files; how you’re mapping it yourself is not actually how it is supposed to be.

For once this appears to be correctly being handled by sonarr as expected.  Not a bug

**Comment by Taloth** [comment]
NTb is one of the few groups that released the series by tvdb number. Thexem doesn't support multiple mapping so it's more a known limitation.
