### ISSUE TITLE
NZBGeek should include category UHD - "5045"

### ISSUE THREAD

**Issue by KnightHawk3** [Sonarr/Sonarr#4168]
**Describe the problem**
NZBGeek by default does not include the category for UHD TV

**Describe any solutions you think might work**
`src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs:48` should be approximately changed to: 

```csharp
                yield return GetDefinition("NZBgeek", GetSettings("https://api.nzbgeek.info", categories: new[] { 5030, 5040, 5045 }));
```

(I am not a c# dev so I didn't want to submit a pull request without running your tests)

**Comment by markus101** [comment]
UHD is not included by default, if people want it they can add it, but unless you want 4k content you don't need to waste time processing them so we have no plans to add it by default.

**Comment by KnightHawk3** [comment]
Is this to prevent extra scraping?

With the Ultra-HD quality being offered by default, there should be some indication to the average user that it's going to have a hard time finding 2160p content without adding the extra category - perhaps you could have NZBGeek-UHD as a second preset?

I also had to sign up for nzbfinderws to check their api documentation. [If you check here](https://nzbfinder.ws/rsshelp) you can see they also use 5045 as UHD and if we check the code we can see they get an exception, is there a particular reason that NZBGeek can't also have an exception for this?

```csharp
yield return GetDefinition("NZBFinder.ws", GetSettings("https://nzbfinder.ws", categories: new[] { 5010, 5030, 5040, 5045, 5090 }));
yield return GetDefinition("NZBgeek", GetSettings("https://api.nzbgeek.info"));
```
