### ISSUE TITLE
Importing Our Own Posters and such.

### ISSUE THREAD

**Issue by TwistedFaith84** [Sonarr/Sonarr#4170]
So I realized that some of my shows on Sonarr aren't showing posters while they have the posters on multiple sites (tvbd,trakt, tvmaze, ect) so how bout the ability to import our own images for the Posters and such.

**Comment by markus101** [comment]
Please use the correct template when opening issues. We do not have plans for this at this time.

**Comment by TwistedFaith84** [comment]
Well that sucks that you dont have plans for something as simple as this.

**Comment by bakerboy448** [comment]
Sonarr uses TVDB for source data

if you’re talking about writing episode/season/etc posters to your disc, that already exists Settings -> Metadata , Kodak/Embry

if it’s simple then just make a PR for it 🤪and maybe Markus will merge it.

but no plans to do this otherwise

**Comment by TwistedFaith84** [comment]
Yeah I know that Sonarr uses TVDB for source info but its not pulling everything from there. Im talking about there are some series when scrolling through what I have in Sonarr that the Poster is missing (showing Grey Box (sometimes with title other times not with title), Yet on TVDB and other places it has the poster there.

**Comment by bakerboy448** [comment]
I'd suggest checking the logs then.
https://wiki.servarr.com/Sonarr_Troubleshooting#Logging_and_Log_Files
and
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for those support/questions.

No need for a new feature when you want the feature to replace something that exists and isn't working right for you.

**Comment by TwistedFaith84** [comment]
Well yeah I'm requesting  a feature that isn't working properly for me but my request is slightly more then that. I want to be able to have the poster be what I want it to be. Say that I'm an artist and what to use my own work for the poster instead of what its pulling from where ever its pulling from. Just because it will happen to help the issue I'm having shouldn't be the factor for the feature that I'm requesting.

**Comment by Dnkhatri** [comment]
I had the same problem for a few shows most of them the cover available was not marked as english on tvdb. As some of them  were dual language cover I re-uploaded found english covers and uploaded those to tvdb 1-2 days later when I refreshed the show they showed up in tvdb. If no english cover is available sonarr should use another language cover. Another pet peeve of mine is if no language tag in the filename the episode is auto detected as eng where as technically it should default to the original broadcast language.
