### ISSUE TITLE
Upgrade on languages availability

### ISSUE THREAD

**Issue by moreje** [Sonarr/Sonarr#4171]
**Describe the problem**
Sonarr only  upgrades files  based on quality profiles. So when it reaches the requested quality, upgrading is stopped, even if other files with other languages are released

**Describe any solutions you think might work**
Add a second level profile based on languages or Tag.
ie : upgrade until Quality = UHD && tag=multi
or
upgrade until Quality is UHD && language = (english + french)

With this option, you could let Sonarr manage your library until everything you need is there, in terms of quality and languages.
and you keep the ability to download episodes as soos they are available, even if it is not yet best quality & language...

**Comment by markus101** [comment]
This already exists in v3, they're called Language Profiles.

**Comment by moreje** [comment]
It is not exactly the same.. Language profile upgrades until a language is found, but it does not assume that the second is also in the release.. You are not certain that you will get a multi languages file

**Comment by markus101** [comment]
Right, like I said on Discord, Sonarr ahs no concept of multi, and there will be a bunch that has to change for https://github.com/Sonarr/Sonarr/issues/2854 to work.
