### ISSUE TITLE
Add support for Premiumize.me as a download client 

### ISSUE THREAD

**Issue by barnabyjones** [Sonarr/Sonarr#4173]
**Describe the problem**
Add support for Premiumize.me as a download client for both torrents and nzbs.

**Describe any solutions you think might work**
Utilise the transfer/create method in the premiumize API to add files for download. This can then be used in conjunction with rclone or other method to expose the completed downloads to Sonarr for processing. 

**Additional context**

Premiumize.me API documentation - https://app.swaggerhub.com/apis-docs/premiumize.me/api/1.6.7

**Comment by markus101** [comment]
Given the limited interest this isn't something we're going to implement at this time.
