### ISSUE TITLE
Add the filename when grabbed release in the notification sended to the Telegram message bot

### ISSUE THREAD

**Issue by nicopasla** [Sonarr/Sonarr#4174]
**Describe the problem**
Maybe, have the filename in the notification sended on Telegram when the release is grabbed.

**Describe any solutions you think might work**
Add a new parameter to add the filename in the notification

**Additional context**

**Comment by RobinDadswell** [comment]
Do you want the full file path or just the file name once the file has been imported?

**Comment by markus101** [comment]
Not everyone is going to want to see that in the notifications, this is something that could be achieved via message templates in https://github.com/Sonarr/Sonarr/issues/328
