### ISSUE TITLE
Allow use of an external database 

### ISSUE THREAD

**Issue by 19wolf** [Sonarr/Sonarr#4175]
**Describe the problem**
Sqlite doesn't work well or at all on network/distributed filesystems, and I think being able to use an external database like mysql or similar would solve that issue. 

**Describe any solutions you think might work**
Don't use a network filesystem

**Additional context**
None

**Comment by markus101** [comment]
We do not have plans to support other database engines in the foreseeable future.

**Comment by cyberjacob** [comment]
This has been a highly requested feature for several years now, what's the reasoning behind this decision?

**Comment by bakerboy448** [comment]
#1669
#4372 
#4373

>We don't have plans to support another DB engine at this time, it's a significant change that would require validating all migrations on every DB engine supported (adding MySQL would only open the doors to add more) and deal with differences in various versions (which we've run into with SQLite a few times).
