### ISSUE TITLE
Sonarr doesn't clean up after an update

### ISSUE THREAD

**Issue by Arathen** [Sonarr/Sonarr#4178]
**Describe the problem**
When Sonarr performs an update on Linux using the built-in updater, it leaves behind a /tmp/sonarr_update directory. Looking at https://github.com/Sonarr/Sonarr/blob/25baf7bb45d92bdeb51063d5a14f8d1d9bc02253/src/NzbDrone.Core/Update/InstallUpdateService.cs#L112 it seems this directory only ever gets cleaned up at the start of an update, never afterwards, so it hangs around forever essentially. Its not huge, but this issue also trickles down to Radarr and Lidarr as they use the same update code, and between the three of them the leftovers can be over 1GB in size, which can fill up a /tmp filesystem on a headless linux server.

**Describe any solutions you think might work**
The obvious workaround is to make /tmp larger, but it would be nice if Sonarr cleaned up after an update, on first restart, or as part of housekeeping. Give the user a configuration toggle to choose this behaviour for extra credit.

**Additional context**
Default /tmp on a Fedora 33 server is 1GB, while cumulatively:
```
480M    /tmp/lidarr_update
317M    /tmp/radarr_update
89M      /tmp/sonarr_update
```

**Comment by bakerboy448** [comment]
@markus101 we should probably clean up after an update if and only if the update was successful

thoughts?

**Comment by markus101** [comment]
The updater is running from there so you can't really delete it, there is also a copy of the previous install there, useful if you wanted to roll back (and disabled updates).

We could delete it sometime after install during the update task, but that would delete the app backup, so when is a good time to do that?

The easiest thing to do is nothing and I'm inclined to do that. Changing the location of the temporary also solves it.

**Comment by Taloth** [comment]
My recommendation here would be to do it after the Housekeeping runs successfully.
