### ISSUE TITLE
System tab reports that device is read only despite drive having been remounted read write.

### ISSUE THREAD

**Issue by webleyg** [Sonarr/Sonarr#4180]
**Describe the bug**

While viewing the system tab I have a red icon and the following error.

**Mount containing a series path is mounted read-only: /dev/sdj1**

While this was true at one point the drive has since been remounted as read/write.
Here is the relevant output from mount.

**/dev/sdj1 on /media14 type ext4 (ro,relatime)
/dev/sdk1 on /media14 type ext4 (ro,relatime)
/dev/sdl1 on /media14 type ext4 (rw,relatime)**

I believe that sonarr is ony getting the first result despite there being other options. 
I completely understand that this issue is caused by a situation with my hardware on my side, however, sonarr isn't able to pull the correct mount point after this kind of failure on system hardware.

**System Information**

 - Sonarr Version: 3.0.4.1026
 - Operating System: Ubuntu Server. Kernel: 5.4.0-58-generic

**Comment by markus101** [comment]
That error is not updated in real-time. Either wait for the health check task to run, run it manually or restart Sonarr to clear it immediately.

**Comment by webleyg** [comment]
That does not resolve the issue. I have to do a full system reboot to clear error.
