### ISSUE TITLE
Sonarr fails to import because "no video files were found in the selected folder"

### ISSUE THREAD

**Issue by rdp1408** [Sonarr/Sonarr#4182]
**Describe the bug**
Sonarr fails to import TV Episodes downloaded by qbittorrent. This was working prior to updating Sonarr about a week ago. 
Error message is: "Import failed, path does not exist or is not accessible by Sonarr: /downloads/The.Expanse.S05E03.Mother.1080p.AMZN.WEBRip.DDP5.1.x264-NTG[rartv]
However, when I check the download directory, the episode is there, just under a different directory name: /downloads/The.Expanse.S05E03.Mother.1080p.AMZN.WEBRip.DDP5.1.x264-NTG[rarbg]

Note the only difference in file paths is [rartv] vs [rarbg] at the end. This is happening with all episodes since Sonarr was updated.

**Logs**
[Sonarr log](https://pastebin.com/McLea1ST)
[Sonarr debug](https://pastebin.com/k6Uc9idF)
[Sonarr trace](https://pastebin.com/ysHhUzhK)

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Unraid 6.8.3 running in docker (linuxserver/sonarr container)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.


Qbit 4.3+ and Sonarr v2 are not compatible 
Stay on 4.2.5 or upgrade to v3
