### ISSUE TITLE
[Feature Request] Filter/sort history/per-season history

### ISSUE THREAD

**Issue by danshilm** [Sonarr/Sonarr#4184]
**Describe the problem**
This is something that'd be especially useful for shows that have a good amount of seasons and episode. Since each episode's history isn't shown at first glance, and one has to click through each episode to see its history. This became an issue when going through many upgrades to a show since each episode would have a 'Successfully grabbed', 'Episode file deleted' and a 'Episode downloaded successfully'. 
An example of when the history of one show became massive was when I initially imported HIMYM that I had laying on a drive somewhere, then upgraded to a better version that I found on public trackers and then finally upgrading once more when I joined a private tracker.

With the addition of the season history, it became easier to sort through, but still not ideal imho.

**Describe any solutions you think might work**
 - A filter just like the one in Activity -> History with the same options (Grabbed, Imported, Failed, Deleted, Renamed, Ignored) in the history of a show (maybe even in the per-season history) 
OR
 - The ability to sort the history of a show/season by event (Grabbed, Imported, Failed, Deleted, Renamed, Ignored). 

Its my experience that sorting these massive tables is laggy, therefore a filter would be my preferred option.

**Additional context**
The filter I'm talking about that's already present in Activity -> History is this one:
![image](https://user-images.githubusercontent.com/20923978/102893287-c7940e80-447a-11eb-88b0-2735bb0b9d83.png)

**Comment by markus101** [comment]
No plans for filtering or sorting at the series/season level at this time.
