### ISSUE TITLE
Episode titles for foreign (German) series are shown as "TBA"

### ISSUE THREAD

**Issue by magicdude4eva** [Sonarr/Sonarr#4187]
**Describe the bug**
Added https://www.thetvdb.com/series/289005-show/allseasons/official as a series with German language. All episodes are retrieved as "TBA"

**Screenshots**
![image](https://user-images.githubusercontent.com/1632781/103034218-b3c4d700-4564-11eb-9422-9722fe45cf39.png)

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 3.0.4.1033
 - Operating System: Docker
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34
 - Branch:

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

TheTVDB caches their API responses for 24 hours, so it can take more than a day to update in Sonarr.

**Comment by Taloth** [comment]
Cache doesn't matter in this case, no English episode title.
