### ISSUE TITLE
Error with the latest qbittorent nightly

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#4189]
**Describe the bug** 
I am getting this bug with the latest qbittorent nightly on sonarr and radarr both I think something changed with the qbittorrent
so apart from a bug report it is also a heads that when the new version of qbittorent drops it will break sonarr
 
Unable to communicate with qbit. Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentTorrent]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly. To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path '', line 1, position 2.
**Screenshots**

**Logs**
https://pastebin.pl/view/64623dc9

**System Information**

 
Version
3.0.4.1033
Package Version
3.0.4 by Team Sonarr
Mono Version
6.12.0.107
AppData directory
/var/lib/sonarr
Startup directory
/usr/lib/sonarr/bin
Mode
Console
**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**
This started with the latest qbittorrent nightly and now sonarr and radarr cant seem to talk to qbittorrent

**Comment by markus101** [comment]
Please provide the requested trace logs.

**Comment by Dnkhatri** [comment]
> Please provide the requested trace logs.

tracelog link added

**Comment by Taloth** [comment]
Thanks for reporting it, I forwarded the issue to qbittorrent with the necessary details.

https://github.com/qbittorrent/qBittorrent/issues/14041

**Comment by Taloth** [comment]
And fixed upstream. Teamwork FTW.
