### ISSUE TITLE
Series with airing date January the 1st are given the wrong year by Sonarr

### ISSUE THREAD

**Issue by faxitydev** [Sonarr/Sonarr#4191]
**Describe the bug**
Series that are aired on January the first are displayed and treated in sonarr with the year before that.

Example 1: 
Show `Mr. Bean` `TVDB ID 76316` was aired in 1990 according to TVDB
Skyhook returns `"firstAired": "1990-01-01",`
Sonarr will display this as 1989 when doing a lookup: https://i.imgur.com/K237iON.png
When added to library 1989 will be put in directory name: 

Example 2: 
Show `The Circle (US)` `TVDB ID 368012` was aired in 2020 according to TVDB
Skyhook returns `"firstAired": "2020-01-01",`
Sonarr will display this as 2019 when doing a lookup: https://i.imgur.com/2VdXUCy.png
When added to library 2019 will be put in directory name: https://i.imgur.com/Kab5RWA.png

**Logs**
No years to be found in trace logs when adding it to the library.

**System Information**

 - Sonarr Version: 3.0.4.1033
 - Operating System: Synology Docker (lsio)
 - Branch: phantom-develop

**Additional Information**
User `DarkKnight #2447` noticed the issue on Discord

**Comment by RobinDadswell** [comment]
This appears to be timezone specific; running the same version of Sonarr in GMT on Centos 8 (Mono Version 6.12.0.107) this shows as 2020 as expected (https://i.imgur.com/3Xc5CgI.png); The Circle has an airtime of 3:00am in the UK which would mean in the US it was released in 2019. 

@faxitydev and DarkKnight mentioned they are in GMT+1 and GMT+5:30 respectively.

**Comment by Taloth** [comment]
airtime is irrelevant for first-aired date. It's just a bug somewhere. It sounds timezone related, but in reverse. Anyway easy fix.
