### ISSUE TITLE
Sonarr sends wrong episode name to indexers

### ISSUE THREAD

**Issue by josdemmers** [Sonarr/Sonarr#4195]
**Describe the bug**
Sonarr is having problems with some serie titels.
Problem occures by the Anime series: KING's RAID: Successors of the Will
Eventhough Thexem.de correctly finds the aliases (http://thexem.de/xem/show/5001):
King's Raid - Ishi o Tsugu Mono-tachi
King's Raid - Ishi wo Tsugu Mono-tach

However when Sonarr sends it to the indexers it changes the name.
`20-12-26 11:02:46.3|Info|NzbSearchService|Searching 2 indexers for [KING's RAID: Successors of the Will : 12]
20-12-26 11:02:46.3|Debug|Torznab|Downloading Feed http://192.168.0.17:9117/api/v2.0/indexers/nyaasi/results/torznab/api?t=search&cat=127720&extended=1&apikey=(removed)&offset=0&limit=100&q=Kings%20Raid%20Ishi%20o%20Tsugu%20Mono%20tachi+12
20-12-26 11:02:46.3|Debug|Torznab|Downloading Feed http://192.168.0.17:9117/api/v2.0/indexers/nyaasi/results/torznab/api?t=search&cat=127720&extended=1&apikey=(removed)&offset=0&limit=100&q=Kings%20Raid%20Ishi%20wo%20Tsugu%20Mono%20tach+12
20-12-26 11:02:48.3|Debug|Torznab|Downloading Feed http://192.168.0.17:9117/api/v2.0/indexers/nyaasi/results/torznab/api?t=search&cat=127720&extended=1&apikey=(removed)&offset=0&limit=100&q=KINGs%20RAID%20Successors%20of%20the%20Will+12`

In a more readable format:
KINGs RAID Successors of the Will 12
Kings Raid Ishi wo Tsugu Mono tach 12
Kings Raid Ishi o Tsugu Mono tachi 12

So as you can see Sonarr removes all "-" and "'" characters from the string.
Because of that the indexers are not able to find anything and return 0 results.

**Logs**
`20-12-26 11:02:46.3|Info|NzbSearchService|Searching 2 indexers for [KING's RAID: Successors of the Will : 12]
20-12-26 11:02:46.3|Debug|Torznab|Downloading Feed http://192.168.0.17:9117/api/v2.0/indexers/nyaasi/results/torznab/api?t=search&cat=127720&extended=1&apikey=(removed)&offset=0&limit=100&q=Kings%20Raid%20Ishi%20o%20Tsugu%20Mono%20tachi+12
20-12-26 11:02:46.3|Debug|Torznab|Downloading Feed http://192.168.0.17:9117/api/v2.0/indexers/nyaasi/results/torznab/api?t=search&cat=127720&extended=1&apikey=(removed)&offset=0&limit=100&q=Kings%20Raid%20Ishi%20wo%20Tsugu%20Mono%20tach+12
20-12-26 11:02:48.3|Debug|Torznab|Downloading Feed http://192.168.0.17:9117/api/v2.0/indexers/nyaasi/results/torznab/api?t=search&cat=127720&extended=1&apikey=(removed)&offset=0&limit=100&q=KINGs%20RAID%20Successors%20of%20the%20Will+12`

**System Information**
Version    3.0.4.1039
Package Version    3.0.4.1039-ls17 by linuxserver.io 
Mono Version    5.20.1.34

**Comment by markus101** [comment]
Sonarr never sends episode names to indexers, but it sounds like you mean series titles.

Proper indexers that organize by TVDB ID should have no issue by slightly different titles and really even slight differences in titles shouldn’t be a problem, but it is for some.

This is a super of https://github.com/Sonarr/Sonarr/issues/1225

**Comment by josdemmers** [comment]
Thank you for the response. I did indeed mean the series title as mentioned in the description.
The indexer i'm using is Torznab (for Jackett), unfortunately for this serie the naming by Sonarr is a problem.

The issue you linked was an interesting read. Too bad there is no solution yet.
Can I do anything to help out?
