### ISSUE TITLE
Existing file meets cutoff, no existing file on disk

### ISSUE THREAD

**Issue by crogers2287** [Sonarr/Sonarr#4196]
**Describe the bug**
Searching for episodes of a show, release rejected, existing file meets cutoff, episode wasn't requested. However there is no existing episode or files, and everything is monitored and has been requested.

**Screenshots**

![image](https://user-images.githubusercontent.com/5433396/103157735-3a0b3400-4784-11eb-94da-096dbb3ffd2a.png)
![image](https://user-images.githubusercontent.com/5433396/103157739-4abbaa00-4784-11eb-85e5-50ce4606ae23.png)
![image](https://user-images.githubusercontent.com/5433396/103157752-632bc480-4784-11eb-8706-a195e51bf849.png)

**Logs**
https://hastebin.com/raw/vijoziheyo 

**System Information**

 Version
3.0.4.1039
Package Version
3.0.4.1039-ls17 by linuxserver.io
Mono Version
5.20.1.34
AppData directory
/config
Startup directory
/app/sonarr/bin
Mode
Console
Uptime
10:14:33

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

> 20-12-26 14:13:05.1|Debug|ParsingService|Using Scene to TVDB Mapping for: Bert the Conqueror - Scene: 1x01 - TVDB: 3x01

That release is remapped to season 3, not sure that's correct, but it's been that way for more than 4 years. You'll have to discuss with the mods on thexem.de (via IRC).
