### ISSUE TITLE
Another obfuscated parser bug

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4198]
**Describe the bug**
Another obfuscated case, causing the obfuscated title to be parsed as the season

**Screenshots**
See Reddit 

**Logs**
Not needed
Full File Path: /mnt/shared/config/sabnzbd/sabnzbd/complete/tv/SEAL.Team.S04E03.The.New.Normal.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb/cwnOJYks5E2WP7zGuzPkdkRK3JkWw0.mkv

**System Information**

Version
3.0.4.1026
Package Version
3.0.4.1026-ls13 by linuxserver.io
Mono Version
5.20.1.34

**UI Bugs:**
N/A

**Additional context**
Reported via [Reddit](https://www.reddit.com/r/sonarr/comments/km1puk/cute_little_bug/?utm_source=share&utm_medium=mweb)

**Comment by g4m3r7ag** [comment]
S.W.A.T.2017.S04E07.Under.Fire.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb/s2e2fYzx5xJhuBjHn5ZXE07Ebi.mkv

**Comment by bakerboy448** [comment]
From Radarr: 39 Character Obfuscation as well

**Comment by g4m3r7ag** [comment]
Got another one

Nancy.Drew.2019.S02E02.The.Reunion.of.Lost.Souls.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb/46XuzmawYQeUBwNdH2Hw2996.mkv

Error is "Season number 29 was unexpected considering folder name"

**Comment by bakerboy448** [comment]
@g4m3r7ag PR is up for that one
