### ISSUE TITLE
Sonarr tracking Radarr downloads

### ISSUE THREAD

**Issue by maccasey** [Sonarr/Sonarr#4200]
Sonarr is trying to import (not in screenshot) and control Radarr downloads.  

![image](https://user-images.githubusercontent.com/74323861/103294459-e38a3980-49bf-11eb-910f-97516e2ab23d.png)

![image](https://user-images.githubusercontent.com/74323861/103294514-00bf0800-49c0-11eb-8e8e-c29d2f2c77bb.png)

Ubuntu server on vmware.  Storage on truenas box.  Radarr is new .net.  sonarr is running in mono.  Sonarr is not picking up lidarr downloads in the same folder.  Transmission DL client.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

use labels for sonarr and radarr (and lidarr for the matter)

**Comment by maccasey** [comment]
I was in "issues" i clicked new issue and clicked bug.  i don't know where you want this or how to flag this the way you want it flagged. 

maybe instead of just closing my issue you either move it or provide a little better instruction on how to file something correctly.  

This is a new thing that started with the current update and i thought that maybe someone would like to look into it.  

guess i wont try and help anymore.

**Comment by bakerboy448** [comment]
The ARRs will send a download request to your client, and associate it with a label or category name that you have configured in the download client settings.
Examples: movies, tv, series, music, etc.

settings -> download client -> your client -> label/category

From the text in the Bug New Issue:
> Support Requests will be closed immediately, if you are unsure go to our IRC, Forums, Reddit, or Discord first. Exceptions do not mean you found a bug!
