### ISSUE TITLE
Add support for Video compression preferences

### ISSUE THREAD

**Issue by MrD2** [Sonarr/Sonarr#4201]
After quality, add sub-category to select by video compression format:

mp4, x264, x265 etc...

**Comment by bakerboy448** [comment]
Use preferred words (and some regex)for x264 or x265

https://trash-guides.info/Sonarr/V3/Sonarr-Release-Profile-RegEx/

For Regex examples for 264 and 265 see TRaSH's radarr guides 


MKV and MP4 likely cannot be determined as it is extremely rare that would be included in the release name 

No plans to further complicate qualities
