### ISSUE TITLE
Sonarr says port in use, when setting urlbase

### ISSUE THREAD

**Issue by BadAd84** [Sonarr/Sonarr#4204]
**Describe the bug**
When setting the reverse proxy path, the web server seemingly attempts to bind to port 8989 twice, once as http://localhost:8989/ and again as http://localhost:8989/sonarr/. This then causes sonarr to crash as it says port 8989 is already in use.

**Logs**
https://pastebin.com/Ssz5gWgX
Log with path set (and crashes), followed by starting again without path set.

**System Information**
 - Sonarr Version: 3.0.4.1039
 - Operating System: Windows Server 2019
 - Branch: phantom-develop

**Comment by markus101** [comment]
You need to run Sonarr once as admin to register the URL base with windows (httpsys).
