### ISSUE TITLE
Webhooks not working with Synology Chat

### ISSUE THREAD

**Issue by jeryd** [Sonarr/Sonarr#4205]
**Describe the bug**
The built in webhooks do not work with Synology Chat / integrations. I used the synology provided URL and while Sonarr lists it as a success, nothing is posted into the channel.

**Screenshots**
NA

**Logs**
NA

**System Information**
 - Sonarr Version: [e.g. 2.0.0.1]
 - UnRaid / Docker
 - Synology 6.* (What ever is the latest version)

**UI Bugs:**
NA

**Additional context**
My guess is the Webhook message is not showing up in a format Synology is accepting. A possible solution is to add a section in the Sonarr webhook section to edit the data that is posted.

**Comment by bakerboy448** [comment]
Please fill out the additional information in the template you ignored and provide logs

**Comment by bakerboy448** [comment]
Also if you’re on v2, try v3

**Comment by markus101** [comment]
This is not a bug. Webhooks are sent in a specific format, they’re not intended to work for other third party services, unless they support the Sonarr webhooks format.

we do not have plans to support symbology chat/integrations, you’ll need to use a custom script or translate Sonarr’s webhooks to whatever structure symbology chat is looking for.
