### ISSUE TITLE
Stale Completed Download Paths

### ISSUE THREAD

**Issue by DirtyCajunRice** [Sonarr/Sonarr#4206]
**Describe the bug**
If a file is no longer downloading, but not marked as completed yet, the path information is saved only the first poll and never updated. Any type of post processing done prior to being marked ready for import by sonarr that is not completed by poll interval or is caught by poll interval will show the wrong path until restart. This is present in both sonarr and radarr.

**Screenshots**

**Logs**
Radarr logs, but same thing for both. Relevant search is "redwood" in this file. rtorrent responds with the proper path, but sonarr/radarr do not update their tracked item to reflect that.
https://bin.cajun.pro/raw/akekonafal

**System Information**

 - Sonarr Version: 3.0.4.1039
 - Operating System: linux/docker 
 - Branch: develop

**Additional context**
Conversation starting at this discord message https://canary.discord.com/channels/264387956343570434/264388019585286144/793907057911922688

**Comment by markus101** [comment]
> after QBittorrent update
> rtorrent responds with the proper path

If you're using rtorrrent (as the logs indicate) why is qbit mentioned?
Did you move from qbit to rtorrent? Or just change the paths in rtorrent?

**Comment by DirtyCajunRice** [comment]
@markus101 Qbittorrent update was my reference to the commit that was designed mainly around qbittorrent updates. Here is the PR for it https://github.com/Sonarr/Sonarr/pull/3346

**Comment by Taloth** [comment]
PS public void Import(TrackedDownload trackedDownload) needs to update the ImportItem as well, but it probably needs to do the checks done in Check(TrackedDownload trackedDownload) again in case something changed. So yeah, not a 1 line fix.
