### ISSUE TITLE
Preferred words not being considered when multiple releases in queue

### ISSUE THREAD

**Issue by g4m3r7ag** [Sonarr/Sonarr#4212]
**Describe the bug**
When Sonarr is set to not import releases for episodes that have title TBA for 24 hours, and preferred words are being used multiple releases can stack up in the queue for each episode. When the show refreshes and the title data is updated and it begins importing it doesn't appear to consider the preferred words. I've seen this before but was able to get logs this time. Cobra Kai S03 wouldn't import due to TBA titles. At first it grabbed a release from either GLHF or GGWP which have a preferred word score of 0. These releases stopped in queue as waiting to import due to the TBA title. A short time later it grabbed a pawel2006 release for each episode which had a preferred word score of 90. Finally a short time after that it grabbed an NTG release which had a preferred word score of 240. This resulted in 30 episodes sitting in the queue waiting to import when Title data was available or 24 hours had passed. 

When I manually refreshed the show and title data updated it began automatically importing the episodes that were in queue but did not consider the preferred word score. At the end all 30 releases had been imported. On two episodes the final release imported was the NTG release with a score of 240. On four of the episodes the final release was the pawel2006 with a score of 90. Meaning it had previously imported the 0 and 240 score releases and then deleted them in favor of the 90 score. Finally on four of the releases the final import was on the 0 score release, meaning both the 90 and 240 scores had been imported and subsequently deleted and replaced.

If the higher score is imported first, the other episode(s) should be rejected as not an upgrade and then require manual removal from queue I imagine. An even better outcome would be either parsing the scores in queue and importing lowest score to highest, this would leave the queue empty but at the cost of importing/deleting/importing which isn't that efficient. Or there could be a setting if enabled that automatically removes a lower scored release from queue that is waiting to import. Due to the potential for removing something that shouldn't be I assume that might not be the preferred way to handle it, which is why it could be a user selected option. 

**Screenshots**

**Logs**
Trace logs attached. Note I had to manually redact my Pushover token in these logs (indicated by "manually_redacted")
[sonarr trace logs.txt](https://github.com/Sonarr/Sonarr/files/5759714/sonarr.trace.logs.txt)

**System Information**

 - Sonarr Version: 3.0.4.1042
 - Operating System: Ubuntu 18.04/nightly-729b3bf by hotio
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 6.10.0.104
 - Branch: nightly

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

Preferred score for the different releases
GLHF - 0
GGWP - 0
pawel2006 - 90 (NF.WEBDL)
NTG - 240 (NF.WEBDL & -NTG)

Final import for each episode
e01/e04/e05/e06 GLHF/GGWP
e02/e07/e09/e10 pawel2006
e03/e08 NTG

This may be related to #3488 but I'm not sure due to that not taking into account releases in queue waiting to import just existing file on disk.

**Comment by markus101** [comment]
No explicit order for preferred word scores is used when importing, so lower items will be left in the queue (same as with lower qualities would be).
