### ISSUE TITLE
Switch to MailKit for Email Notifications

### ISSUE THREAD

**Issue by FingerlessGlov3s** [Sonarr/Sonarr#4213]
**Describe the bug**
I've setup the connection for SMTP alerts, username and password is correct but look to be getting a TLS error.

Mono packages installed to create docker container (libmono-cil-dev ca-certificates-mono curl mediainfo)

Email Server is Mailcow, with TLS 1.0 and 1.1 disable, TLS 1.2 and 1.3 enabled

**Logs**
https://pastebin.com/Wq288mTp

**System Information**

 - Sonarr Version: 3.0.4.1042
 - Operating System: ubuntu:bionic
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 6.12.0.107
 - Branch: phantom-develop

**Additional context**
Was working before but, I had notifying turned off for a while and gone to enable again no longer working.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

Looks like an issue with authentication, but that error is a bit unclear.

**Comment by FingerlessGlov3s** [comment]
Shall seek help on Discord.

I did some testing and enabling TLS1.0 on the mail server allows mail to send, but this isn't ideal for security reasons.
So its 100% TLS issue.

**Comment by FingerlessGlov3s** [comment]
Downgraded Mono to 5.20.1.34 still no change.
Set MONO_TLS_PROVIDER=btls had no change, but the original errors looks to be using btls anyway, but thought I'd try anyway.

Using Port 587, which uses STARTTLS as per the smtp spec of mono.

Only way currently to get it working is lowering TLS on the postfix server

**Comment by FingerlessGlov3s** [comment]
Checked Gmail and Outlook and they support TLS1.0, so this might be why its come cropped out yet?

**Comment by FingerlessGlov3s** [comment]
More testing later, I can connect to TLS1.2 websites under the same mono environment, is there an issue with the way SMTP class is setup in Sonarr? Do we need a way to force TLS1.2 connectivity for SMTP?

Code used for testing HTTPS TLS1.2
```
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace MonoTLS {
        internal static class Program {
                private static void Main() => Reproduce().Wait();

                private static async Task Reproduce() {
                        using (HttpClient httpClient = new HttpClient()) {
                                try {
                                        await httpClient.GetAsync("https://tls-v1-2.badssl.com:1012/").ConfigureAwait(false);
                                        Console.WriteLine("OK!");
                                } catch (Exception e) {
                                        Console.WriteLine("Exception: " + e.Message + " | Stacktrace: " + Environment.NewLine + e.StackTrace);

                                        while (e.InnerException != null) {
                                                e = e.InnerException;
                                                Console.WriteLine("Inner exception: " + e.Message + " | Stacktrace: " + Environment.NewLine + e.StackTrace);
                                        }

                                        Environment.Exit(1);
                                }
                        }
                }
        }
}
```

**Comment by markus101** [comment]
According [MS docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=net-5.0) they no longer recommend using `SmtpClient` for new projects, it looks like: [MailKit](https://github.com/jstedfast/MailKit) is recommended now.

I played with it a bit in LINQPad and it seems to work well, but some noteworthy changes are:

- Requires sender and recipient names, not a big deal, but would be a slightly breaking change for people since they'd lose automatic names from the mail client
- Supports SSL and StartTLS and seems to automatically handle StartTLS
  - Sending to google on port 587 works with SSL set to false
  - Sending to gmail on port 465 works with SSL set to true

Things I don't know:

- If TLS 1.2 works with `SmtpClient` on Windows
- If MailKit works with TLS 1.2

I think we can ignore the first question if the second one is yes.

https://github.com/jstedfast/MailKit#sending-messages super simple code block to test if it works in your setup.

**Comment by FingerlessGlov3s** [comment]
@markus101, finally got it compiled using mcs on Linux and that works to send emails as expected.

Postfix logs confirm TLSv1.2 usage
"using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)"

**Comment by FingerlessGlov3s** [comment]
Is there a roadmap point or anything for this enhancement?

**Comment by bakerboy448** [comment]
Radarr .net5 commit for future posterity
`Replace SmtpClient with Mailkit`
https://github.com/Radarr/Radarr/commit/e824c74e543f67f207d312f4eeffb53929e874f4

**Comment by Qstick** [comment]
That single commit can likely be cherry picked and pulled over as is @bakerboy448. There's just one small thing I need to fix (html/plain logic is backward)

**Comment by FingerlessGlov3s** [comment]
Happy to test once the commits are final 👍

**Comment by bakerboy448** [comment]
@Qstick I'll let you cherry pick and edit it over into a PR then, you know how well git and I get along
