### ISSUE TITLE
mono support

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#4217]
can we get a wiki page that talks about known issues with mono version and what is recommended for sonarr v2/v3. as mono 6.x is now stable i know 5.20.x is the recommended version but hard to keep track these days

As the install page simply recommends mono 3.6+
https://github.com/Sonarr/Sonarr/wiki/Installation#mono

and then from source:
https://github.com/Sonarr/Sonarr/blob/phantom-develop/docker/tests/run-all.sh#L33

**Comment by thezoggy** [comment]
also to note, doesnt look like tests are ran against 6.12

> The latest Stable Mono release is: 6.12.0 Stable (6.12.0.107)

**Comment by markus101** [comment]
Mono 5+ is required for everything, 5.20 is best, but 5.18+ is the target.

Relevant checks are here: https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core/HealthCheck/Checks/MonoVersionCheck.cs

We definitely do not run tests against every mono version.

We still recommend mono 5 over mono 6, but for the most part you should be fine with either.

Everything for v3 is now here: https://wiki.servarr.com/Sonarr, if something is missing (5.20 is mentioned) then anyone can link their github account or create another account and update it.
