### ISSUE TITLE
Unmonitored episode being swapped with wrong episode

### ISSUE THREAD

**Issue by velcropaste** [Sonarr/Sonarr#4218]
Have seasons 1-3 unmonitored, and sonarr picked up a dl for s04e05. When it was downloaded, sonarr interpreted it as s01e05 and replaces that episode despite not being monitored.

Seems strange that sonarr correctly identified the torrent at the dl stage, but then made another judgement when importing the file. Regardless, swapping out an episode of an unmonitored season shouldn't happen.

**Comment by bakerboy448** [comment]
Please fill out the template and provide logs
https://github.com/Sonarr/Sonarr/issues/new?template=bug_report.md

**Comment by markus101** [comment]
> sonarr interpreted it as s01e05 and replaces that episode despite not being monitored.

Being monitored only affects whether Sonarr will grab it automatically (outside of a search for that specific episode), importing will happen regardless of it being monitored or not.
