### ISSUE TITLE
Scheduled Backups Occurring more frequently than 1 Day

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4219]
**Describe the bug**
Backups are occuring every minute when set to every day.

**Screenshots**
![image](https://user-images.githubusercontent.com/55419169/103555741-5db23680-4e76-11eb-8bb2-68cf0cc1ef15.png)
![image](https://user-images.githubusercontent.com/55419169/103555699-483d0c80-4e76-11eb-84b6-c9506076627e.png)
![image](https://user-images.githubusercontent.com/55419169/103555734-5723bf00-4e76-11eb-96f1-788c682db32c.png)

**Logs**
Too noisy....309 in queue

**System Information**

 - Sonarr Version: 3.0.4.1052
 - Operating System: Ubuntu 18.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono Version 6.12.0.107
 - Branch: phantom-develop

**Additional context**

**Comment by markus101** [comment]
Already fixed... https://github.com/Sonarr/Sonarr/commit/ed2bb0d73aaade95d21041bac845470870f99b36
