### ISSUE TITLE
Better handling of empty XEM absolute scene episode numbers

### ISSUE THREAD

**Issue by Shiandow** [Sonarr/Sonarr#4222]
**Describe the problem**

Currently theXem seems to be reporting some missing absolute numbers as 0, when this clearly cannot be the case.

At the moment (build 3.0.4.1058) this leads to sonarr assuming that the the absolute number for those episodes is 0 which messes up search (though thankfully not RSS). 

**Describe any solutions you think might work**

I haven't yet been able to find legitimate uses of an absolute episode number 0 (it's sometimes used as a special, but as an absolute number it is weird), though there could always be a few special cases. You could probably count the exceptions on one hand though, so I reckon it's possible to assume absolute number 0 means 'undefined' and use the anidb / tvdb numbering in those cases.

At any rate when *all* absolute episode numbers are 0 it's probably safe to conclude they are meaningless.

**Additional context**

An example includes the recently started 'Otherside Picnic' with tvdb id 388381. An excerpt of [the mapping in Xem](http://thexem.de/map/all?id=388381&origin=tvdb) currently looks as follows:

```json
{
  "result": "success",
  "data": [
    {
      "scene": {
        "season": 1,
        "episode": 1,
        "absolute": 0
      },
      "anidb": {
        "season": 1,
        "episode": 1,
        "absolute": 1
      },
      "tvdb": {
        "season": 1,
        "episode": 1,
        "absolute": 1
      }
    },
    {
      "scene": {
        "season": 1,
        "episode": 2,
        "absolute": 0
      },
      "anidb": {
        "season": 1,
        "episode": 2,
        "absolute": 2
      },
      "tvdb": {
        "season": 1,
        "episode": 2,
        "absolute": 2
      }
    },
```

where it reports '"absolute": 0' for all scene releases at the moment.

**Comment by markus101** [comment]
Please fill out the complete bug template, including logs.

**Comment by Shiandow** [comment]
It's more of an enhancement request (as to my knowledge this would be *new* behaviour, not existing behaviour that's incorrect). I've adapted it to use the template for those.

If it is a bug it's on Xem's side, but for all I know it could be working as intended.

**Comment by markus101** [comment]
> At any rate when all absolute episode numbers are 0 it's probably safe to conclude they are meaningless.

It's been the way it is for years, I wouldn't assume nothing will break.

I'm not sure this is really a bug on thexem.de side. but unless there are a bunch of other series where this is an issue, we should just fix the mapping on thexem.de, that way we're not making assumptions that changing this behaviour will change nothing.

**Comment by Taloth** [comment]
Not a bug, just two shows with a bad mapping (wrong passthru). Afaik the xem mods have been pinged about it.

**Comment by Shiandow** [comment]
I see. Since it was happening consistently on multiple shows I figured it was just xem's way of telling people to not use the scene's absolute episode numbers (as in the current mapping is 'unknown' rather than incorrect).

**Comment by Shiandow** [comment]
Looks like [this commit](https://github.com/Sonarr/Sonarr/commit/6dfbc3c290a1d2247bb8223d2e325cd586156d77) made it possible for absolute episode numbers to be 0 (to fix issues with some series presumably, though it doesn't specify which).

That said it looks like xem also uses 0 when the number cannot be linked, which is unfortunate. I'll see if I can figure out if this is intended or not.
