### ISSUE TITLE
Series set to type anime not counting past 999

### ISSUE THREAD

**Issue by deadlock1981** [Sonarr/Sonarr#4224]
**Describe the bug**
I've got 1004 episodes but nothing above 999 is found on disk.

**Screenshots**
See this: https://i.imgur.com/HMarN3p.png

**Logs**
https://awesome-o.nl/sonarr.txt

**System Information**
 - Sonarr Version: 3.0.4.1058
 - Operating System: Windows 10 1909 fully patched
 - .net Framework (Windows): 4.8
 - Branch:

**Comment by markus101** [comment]
We need to see debug or trace logs of that series being refreshed, the current logs don't help.

An example of how those files are named would be helpful as well.

**Comment by deadlock1981** [comment]
How the files are named is in the screenshot...

**Comment by deadlock1981** [comment]
Debug log: https://awesome-o.nl/sonarr2.txt

**Comment by deadlock1981** [comment]
It's parsing episode 1004 as S10E04..

**Comment by markus101** [comment]
This is a known limitation, unless your file name contains the release group in square brackets at the beginning or the end to signal to Sonarr it's anime it'll be treated as a 4 digit number that is the combined season and episode number. You can add in a fake release group if necessary, but that's the limitation, there are no short term fixes the deal with this behaviour, though it may be improved with parsing changes in the future, namely https://github.com/Sonarr/Sonarr/issues/457.

**Comment by deadlock1981** [comment]
What do you mean there's no easy fix? If the series is set to a specific type why would you still look for other types of naming conventions? That seems like a bug to me, because otherwise this looks like a pretty straightforward set of conditions to me.
