### ISSUE TITLE
Brackets Cause Invalid Multi-Episode Format Error

### ISSUE THREAD

**Issue by farsayl** [Sonarr/Sonarr#4226]
Latest update on V3 (Docker Sonarr 3.0.4.1058):
Anything in brackets at the beginning of a naming scheme causes an "Invalid multi-episode format" error.
- This only seems to happen on "Extend" naming scheme, "Scene" works fine.
- Brackets can be either inside or outside braces for this issue to occur
- Importing existing episodes with this naming convention works as expected and Sonarr is able to properly parse the release group

For example: 
**Works**
`{Release Group} {Series Title} - S{season:00}E{episode:00} - {Episode Title} {[Quality Full]}` 

**Does not Work**
`{[Release Group]} {Series Title} - S{season:00}E{episode:00} - {Episode Title} {[Quality Full]}` 

Can confirm was working on (Docker Sonarr 3.0.4.1033)
Using linuxserver.io Docker repository specifically

[https://www.reddit.com/r/sonarr/comments/kr2iqu/not_sure_if_im_just_dumb_or_this_is_broken_but/](https://www.reddit.com/r/sonarr/comments/kr2iqu/not_sure_if_im_just_dumb_or_this_is_broken_but/ )

**Comment by markus101** [comment]
Please file out the bug template, including the relevant logs.

**Comment by markus101** [comment]
Square brackets are a great indicator to Sonarr that this is probably anime, this particular format (which results in the sample filename of `[RlsGrp] The Series Title! - S01E01-02-03 - Episode Title [HDTV-720p Proper]`), triggers several different regexes and fixing those breaks existing tests. This is something that will fall under the advanced parser, https://github.com/Sonarr/Sonarr/issues/457
