### ISSUE TITLE
Ended displayed for continuing show

### ISSUE THREAD

**Issue by mkomko** [Sonarr/Sonarr#4228]
**Describe the bug**
The "Ended" tag is displayed for a continuing show.

**Screenshots**
![image](https://user-images.githubusercontent.com/8350714/103835075-852b1e00-5085-11eb-8232-8dc474150053.png)
![image](https://user-images.githubusercontent.com/8350714/103835100-9a07b180-5085-11eb-9f1c-209299f6f0e5.png)
![image](https://user-images.githubusercontent.com/8350714/103835120-a855cd80-5085-11eb-82dd-cc16604571c6.png)

**System Information**
 - Sonarr Version: 2.0.0.5344
 - Operating System: Linux
 - Mono Version: 6.10.0

**Comment by bakerboy448** [comment]
Skyhook is current; refresh the show, likely TVDB updated and you had to wait for the TVDB 24hr cache.

https://skyhook.sonarr.tv/v1/tvdb/shows/en/315321

**Comment by mkomko** [comment]
@bakerboy448 @markus101 Damn it, I apologize for wasting your time. A refresh fixed it. Weird that the information was wrong before. Thank you!

**Comment by markus101** [comment]
Also a good reminder that TVDB’s API caches for 24 hours + skyhook has its own caching so any data issues are very unlikely to be bugs.
