### ISSUE TITLE
Adding a 'Search season packs only' button on Search All pop-up window

### ISSUE THREAD

**Issue by douglas24** [Sonarr/Sonarr#4229]
**Describe the problem**
When clicking the Search All button in the Missing section, Sonarr pops up a window asking if you're sure you want to search for all #### missing episodes. For older, and streaming service shows, it rarely finds results when looking for individual episodes.

**Describe any solutions you think might work**
It would be super useful to have a secondary choice on that pop-up window to 'Search season packs only' because: (1) after a show season finishes airing, it is rarely put up again as individual episode torrents; (2) nearly all streaming shows are only released as season packs; (3) searching for season packs reduces the amount of requests to indexers.

It would also be useful to have this feature for Cut-off Unmet section search all pop-up too.

**Additional context**
Sonarr already seems to have conflict detection method now when a season pack is grabbed and a better version for an individual episode is already on disk (e.g. a 720p pack for S02 is grabbed for an older show because it is the only result found in indexers, but disk already contains S02E02 as 1080p BluRay; Sonarr leaves that episode in queue for manual user attention which is good).

**Comment by markus101** [comment]
Sonarr already groups up missing episodes by series and season and makes requests for season packs for standard series. For daily it groups by year and for anime it searches individually (as does any season level search in Sonarr for anime).

We have no plans to separate that or make it explicit.

**Comment by douglas24** [comment]
> Sonarr already groups up missing episodes by series and season and makes requests for season packs for standard series. For daily it groups by year and for anime it searches individually (as does any season level search in Sonarr for anime).
> 
> We have no plans to separate that or make it explicit.

Okay thanks for letting me know it already looks for season packs when using the Search Missing for the Missing and Cut-off Unmet sections.

When it doesn't find any season packs, does it looks for individual episodes for the season right after that? or does the search all search for all season packs for all shows first and only then look for individual episodes? (the latter would still minimize indexer queries and errors from querying too much)

**Comment by fryfrog** [comment]
There is almost always just *one* search, for the entire season which gets both season pack *and* individual episode results. They all get weighted and sorted and the "best" result(s) are used. That'll be a season pack if it makes sense or individual episodes if it doesn't.
