### ISSUE TITLE
Sonarr 3.0.4.1058 Crashes with a Missing Method Exception

### ISSUE THREAD

**Issue by lrrosa** [Sonarr/Sonarr#4230]
**Describe the bug**
Sonarr fails to open its UI with an error: Method not found: string NzbDrone.Core.DataAugmentation.Scene.SceneMapping.get_SceneOrigin()

**Logs**
Jan 06 21:37:24 htpc service.sonarr[1088]: [Fatal] SonarrErrorPipeline: Request Failed. GET /api/v3/series
Jan 06 21:37:24 htpc service.sonarr[1088]: [v3.0.4.1058] System.MissingMethodException: Method not found: string NzbDrone.Core.DataAugmentation.Scene.SceneMapping.get_SceneOrigin()
Jan 06 21:37:24 htpc service.sonarr[1088]:   at System.Collections.Generic.List`1[T].ConvertAll[TOutput] (System.Converter`2[TInput,TOutput] converter) [0x0001a] in /home/thoradia/9.2.0/build.LibreELEC-Generic.x86_64-9.2-devel/mono-6.8.0.105/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:356
Jan 06 21:37:24 htpc service.sonarr[1088]:   at Sonarr.Api.V3.Series.SeriesModule.PopulateAlternateTitles (Sonarr.Api.V3.Series.SeriesResource resource) [0x00016] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Series\SeriesModule.cs:243
Jan 06 21:37:24 htpc service.sonarr[1088]:   at Sonarr.Api.V3.Series.SeriesModule.PopulateAlternateTitles (System.Collections.Generic.List`1[T] resources) [0x00011] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Series\SeriesModule.cs:233
Jan 06 21:37:24 htpc service.sonarr[1088]:   at Sonarr.Api.V3.Series.SeriesModule.AllSeries () [0x0009a] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Series\SeriesModule.cs:122
Jan 06 21:37:24 htpc service.sonarr[1088]:   at Sonarr.Http.REST.RestModule`1[TResource].<set_GetResourceAll>b__33_0 (System.Object options) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Http\REST\RestModule.cs:124
Jan 06 21:37:24 htpc service.sonarr[1088]:   at Nancy.NancyModule+<>c__DisplayClass14_0`1[T].<Get>b__0 (System.Object args) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0
Jan 06 21:37:24 htpc service.sonarr[1088]:   at Nancy.NancyModule+<>c__DisplayClass16_0`1[T].<Get>b__0 (System.Object args, System.Threading.CancellationToken ct) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0
Jan 06 21:37:24 htpc service.sonarr[1088]:   at Nancy.Routing.Route`1[T].Invoke (Nancy.DynamicDictionary parameters, System.Threading.CancellationToken cancellationToken) [0x00017] in <e31b230dbd29407fadcc55713e0bbd0f>:0
Jan 06 21:37:24 htpc service.sonarr[1088]:   at Nancy.Routing.DefaultRouteInvoker.Invoke (Nancy.Routing.Route route, System.Threading.CancellationToken cancellationToken, Nancy.DynamicDictionary parameters, Nancy.NancyContext context) [0x00086] in <e31b230dbd29407fadcc55713e0bbd0f>:0
Jan 06 21:37:24 htpc service.sonarr[1088]:   at Nancy.Routing.DefaultRequestDispatcher.Dispatch (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken) [0x002b7] in <e31b230dbd29407fadcc55713e0bbd0f>:0
Jan 06 21:37:24 htpc service.sonarr[1088]:   at Nancy.NancyEngine.InvokeRequestLifeCycle (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken, Nancy.Bootstrapper.IPipelines pipelines) [0x0011d] in <e31b230dbd29407fadcc55713e0bbd0f>:0

**System Information**
 - Sonarr Version: 3.0.4.1058
 - Operating System: Linux x64 (Libreelec 9.2.6)
 - .net Framework Version: mono 6.8.0.105

**Comment by markus101** [comment]
I’m not able to reproduce this issue. Does it occur after reinstalling? (Thinking bad update)

**Comment by lrrosa** [comment]
That was probably it. I reinstalled it and it worked again.
