### ISSUE TITLE
[Feature Request] Delay indexers

### ISSUE THREAD

**Issue by SonOfDiablo** [Sonarr/Sonarr#4232]
**Describe the problem**
I have multiple indexers, all prioritized differently.
However some times the low priority indexers are faster with new content than the high priority ones.

**Describe any solutions you think might work**
It would be great if you could put a delay on specific indexers instead of just profiles.
For example, I could delay low priority indexers by 30 minutes so the high priority indexers had a chance to catch up.

**Additional context**
While delaying the default Delay Profile would work, it also isn't quite what I'm after since it could delay grabbing new content from high priority indexers.

**Comment by markus101** [comment]
At this time this isn't something we have plans to support.
