### ISSUE TITLE
Sonarr copying and no deleting 

### ISSUE THREAD

**Issue by Hhhonlyfan** [Sonarr/Sonarr#4234]
usenet downloads to a folder and unpacks to /home/username/downloaded
sonarr then imports from /home/username/downloaded to /home/username/archive

the problem, is sonarr only copies files to the archive which means i have to manually clean out the downloaded folder every few days

Also a link to a Reddit thread from before which is similar issue to mine 

https://www.reddit.com/r/sonarr/comments/9ydocw/sonarr_is_copying_instead_of_moving_files/
**Screenshots*
I am on my phone so I cannot proceed these immediately 
**Logs**
On my phone il will try to supply logs layer 
**System Information**
Ubuntu 18.94 minimal 

Version
3.0.4.1059
Package Version
3.0.4 by Team Sonarr
Mono Version
6.12.0.107
AppData directory
/var/lib/sonarr
Startup directory
/usr/lib/sonarr/bin
Mode
Console

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**
This has only happened for the last couple of releases for myself. Before then it was doing it all fine. 
A Reddit thread with a similar issue to mine 
Can be found here 
https://www.reddit.com/r/sonarr/comments/9ydocw/sonarr_is_copying_instead_of_moving_files/

**Comment by markus101** [comment]
Same as your first issue this is going to be closed, this is not the correct avenue for support, we have dedicated channels for that: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

In the future if you're unable to provide the requested information please wait until you are able to do so, but in this case, at this point this is a support issue.
