### ISSUE TITLE
Feature: Failed download retires priority

### ISSUE THREAD

**Issue by dbond007** [Sonarr/Sonarr#4237]
I looked and couldn't find anything on this so..

**Describe the problem**
When downloads fail, they are not retried right away, they stay in the sonarr queue until the previous successful downloads are processed. If these take time to be moved / processed then there can be a fair amount of wait time until a new download is re-searched for and tried. 

**Describe any solutions you think might work**
I think that when the monitor download process detects a failed download it should immediately start a search and add to the download queue.

**Additional context**
If you download at 10MB/s and the processing / moving goes at 5MB/s, you have 10 x 10GB downloads, the first 5 download successfully, the last 5 do not. The first 5 will download in around 85 minutes, the last 5 will lets say take 85 minutes also to fail. The processing will be done for the first 5 will be done in 180 minutes.
So in this example, the minimum wait time for the last 5 to start a search would be that 180 minutes, but all downloads (including failed ones, downloading all the data, so shortest possible delay) is 170 minutes. So a 10 minute period of no downloading (best case). Worst case would be in this example, 95 minutes dead time (last 5 downloaded nothing).

**Comment by Taloth** [comment]
Which version of sonarr?

**Comment by dbond007** [comment]
Version
3.0.4.1059
Package Version
3.0.4 by Team Sonarr

**Comment by Taloth** [comment]
@markus101 Is it an idea to cancel the command after the import when the loop takes more than 2 minutes? And obviously prioritize processing failed trackedDownloads. Or alternatively refetch the TrackedDownloads if processing the last trackeddownload took a minute or more.

**Comment by markus101** [comment]
> Is it an idea to cancel the command after the import when the loop takes more than 2 minutes?

Why 2 minutes, why not 1 minute or 5 or 10? Sure it's something we could do, but I think any sort of time based metric is strange there, either every after download (not individual file in a season pack) you restart the process or we do nothing. Realistically though, to me this is such a low priority I don't see a reason to keep it open, if we decide to do it in however long it takes us to get through our existing backlog then we can reopen it.

**Comment by Taloth** [comment]
Coz that's the interval that the command runs, so cancelling the command would cause to restart immediately. Although I now realise it probably doesn't queue until the next taskscheduler cycle.
Regardless, A small refactoring of the DownloadProcessingService loop would fix this, the (arbitrary) time is just to prevent the GetTrackedDownloads method from being called at high frequency if imports happen much faster.

**Comment by markus101** [comment]
Not something we currently plan to address, but possibly we'll re-evaluate in the future.
