### ISSUE TITLE
Automatically set language based on audio language

### ISSUE THREAD

**Issue by viggy96** [Sonarr/Sonarr#4240]
**Describe the problem**
Anime is often tagged with the incorrect language in various indexers like Nyaa. They are often identified as being in English when in fact they are not. 

**Describe any solutions you think might work**
Sonarr already analyses the video files after importing and recognises the language of the audio tracks. Sonarr could use this information to properly set the language property for each episode.

**Comment by thezoggy** [comment]
and follow scene rules, if two audio 'dual' if more than two 'multi' tag

**Comment by NuGundam** [comment]
Yes I like this to happen to so then we use the Language Profile as it is attended and users can get the Japanese with subs and when available it will upgrade to English which is most of the time dual audio.

**Comment by geropan** [comment]
Sorry to hijack but this could also solve and issue that I am seeing:

I have a language profile containing two languages: Spanish and English (in this priority order). I have allowed upgrades and requested to the cutoff to Spanish.
![image](https://user-images.githubusercontent.com/57835069/105513094-cd734e80-5cc9-11eb-9a54-07ac6c6fc55a.png)

When an release is grabbed including Spanish language, upon import of the **downloaded file it is labelled as English (even though the title is in Spanish)**. This causes for the same released to be grabbed again in a periodic loop (due to my Language upgrade and cutoff settings):
![image](https://user-images.githubusercontent.com/57835069/105513530-568a8580-5cca-11eb-8c84-5441d72c3a74.png)

As the OP stated, **Sonarr already knows that the imported release has Spanish audio language**, but this information is not used in this context:
![image](https://user-images.githubusercontent.com/57835069/105513698-8a65ab00-5cca-11eb-98e4-1c1e12ad434d.png)

At the moment the only way to stop this is to manually unmonitor the episode once downloaded, although this defeats the purpose of automatic upgrades and so on (e.g. in a use case with a profile with 3 languages).

**Comment by viggy96** [comment]
@geropan Exactly the issue I'm seeing with my anime. I created a language profile with Japanese and English, preferring Japanese. Sonarr often downloads episodes again to get the "preferred" language, even though the existing file _already_ has Japanese audio.

**Comment by geropan** [comment]
I know that Radarr implementation is different (it relies on user defined custom format for upgrades), but I suspect it might be using MediaInfo to determine languages.

In the example below there are no hints on the filename to determine the languages, but they are still being identified correctly:
![image](https://user-images.githubusercontent.com/57835069/106671564-9db82680-65a6-11eb-926f-c691a96e8646.png)

Maybe however picks this up could have a look at Radarr's implementation for inspiration.

**Comment by winklevos** [comment]
Yes this would be great to have, it's very time consuming to check if you don't have dual audio on some episodes

**Comment by viggy96** [comment]
This continues to be a very annoying issue. My Sonarr instance continues to try to re-download a bunch of anime due to language, even though its already in Japanese, like I want it to be.

**Comment by arifer612** [comment]
This is not only limited to Anime. My Japanese and Korean drama collections are all identified as English even though they don't even have any subtitles in the first place and all the streams do show the right language. I do hope that this feature will be implemented.

**Comment by SergioRius** [comment]
Is this I'm experienced what this issue talks about?
![imagen](https://user-images.githubusercontent.com/1693727/180191856-728560bb-3b2a-4502-90d0-cf3e46592455.png)
![imagen](https://user-images.githubusercontent.com/1693727/180192035-0fa3890f-545c-4e6f-80f9-b219e335014b.png)
![imagen](https://user-images.githubusercontent.com/1693727/180192116-88b3ef9b-18a5-4f33-b2c5-faa4be07a6ed.png)

I'm seeing this issue still's open... So it happens that Sonarr does not support other languages than english?

**Comment by viggy96** [comment]
@SergioRius Not exactly. Sonarr uses what the indexer metadata says the language is to set the language property. Problem is, indexers often don't set the language property correctly.

What I propose is that after Sonarr imports the media and scans the video file itself, that it change the language property to match the audio language metadata from the video file.

**Comment by SergioRius** [comment]
> @SergioRius Not exactly. Sonarr uses what the indexer metadata says the language is to set the language property. Problem is, indexers often don't set the language property correctly.
> 
> What I propose is that after Sonarr imports the media and scans the video file itself, that it change the language property to match the audio language metadata from the video file.

Mmmm... But I don't have any indexers setup. I simply imported my library. The file names doesn't contain any tags either.

**Comment by viggy96** [comment]
Then did you select the correct language when you manually imported the files?

**Comment by SergioRius** [comment]
> @SergioRius Not exactly. Sonarr uses what the indexer metadata says the language is to set the language property. Problem is, indexers often don't set the language property correctly.
> 
> What I propose is that after Sonarr imports the media and scans the video file itself, that it change the language property to match the audio language metadata from the video file.

But I don't understand. If my language is Spanish, what does the language of the audio matters? I would want the synopsis and all the metadata to be in my language so I/we can read them. Isn't it?
Sorry is that I don't understand the language logic in the program. Had been using it in the past but left it for a while, and now that I'm using it again I can't make it work as I would want.

As I configured my library it changed all my Spanish existing metadata for an English one. I had to deactivate renaming and metadata sections and re-scrape all with an external program.
And without those functions active, I don't know if the program is very useful, honestly. Maybe there is something that I am not configuring correctly. All my media seems ok.

**Comment by SergioRius** [comment]
> Then did you select the correct language when you manually imported the files?

Yes.
Another example, all the files have all the tracks with language defined, like this:  (between brackets are the track titles)
```
===================================================================================================
********* (2021) - S01E08 WEBDL-1080p (1).mkv        11.6 Mb/s 4.568 GiB


Video  Spanish     10.1 Mb/s 3.96 GiB (87%)


Audio 1 Spanish         A_EAC3 6 channels       Default: Yes            CBR 768 kb/s  309 MiB (7%)
  [Castellano DD+ 5.1 Atmos @ 768 kbps]

Audio 2 English         A_EAC3 6 channels       Default: No             CBR 768 kb/s  309 MiB (7%)
  [Inglés DD+ 5.1 Atmos @ 768 kbps]

Subtitle 1 Spanish      Text S_TEXT/UTF8        Default: Yes Forced: Yes                527 Bytes (0%)
  [Castellano forzados]

Subtitle 2 Spanish      Text S_TEXT/UTF8        Default: No Forced: No          18.5 KiB (0%)
  [Castellano]

Subtitle 3 English      Text S_TEXT/UTF8        Default: No Forced: No          18.6 KiB (0%)
  [Ingles]
```
Manually imported selecting spanish (but I understand that is a profile, for searching new content)
But language is English, and all the metadata retrieved is english:
![imagen](https://user-images.githubusercontent.com/1693727/180662991-91d7ec4b-75e7-4784-9e2b-b9dca515dc6b.png)

**Comment by thezoggy** [comment]
language is determined by the filename not by mediainfo, as sonarr doesnt have access to the mediainfo when its parsing release names. you need to keep the required bits in your filename if you want it to be picked up, otherwise it will be assumed to be english. just like if you dont have quality in the filename its assumed to be sdtv for .avi/mp4 and hdtv for .mkv

**Comment by SergioRius** [comment]
> language is determined by the filename/releasename not by mediainfo, as sonarr doesnt have access to the mediainfo when its parsing release names. you need to keep the required bits in your filename (rename naming scheme) if you want it to be picked up, otherwise it will be assumed to be english. just like if you dont have quality in the filename its assumed to be sdtv for .avi/mp4 and hdtv for .mkv

I understand. Would you mind to tell me what's the required filename naming scheme so that Sonarr picks the files in the correct language?
![imagen](https://user-images.githubusercontent.com/1693727/181078725-b89bbf06-3aa5-46b4-b668-0cf69cbe6657.png)

I suppose that [spa] is not valid then?

**Comment by thezoggy** [comment]
github is not a valid support function, you should be asking on sonarr forums/discord/irc.

but anways, the lang regex for spanish group is:  `(?<spanish>\b(?:español|castellano)\b)`:
https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Parser/LanguageParser.cs#L20

and then the basic assumption if `spanish` is in the title:
https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Parser/LanguageParser.cs#L42

so in the end, if any of these words are in the title, its assumed lang is spanish:
- `spanish`
- `español`
- castellano

**Comment by bakerboy448** [comment]
@markus101 done in v4 with media info augmentation?

**Comment by markus101** [comment]
Yeah, added for v4, closing.
