### ISSUE TITLE
Manual File Import not grabbing extras

### ISSUE THREAD

**Issue by obsidiangroup** [Sonarr/Sonarr#4241]
**Describe the bug**
Whenever I do a Manual File Import and there are extras (subtitles), Sonarr does not import or rename these files. 
The option to Import Extra Files is selected, and Import Extra Files is set for 'srt,sub,idx'

Sonarr just ignores the extra files, and I cannot find a way to force Sonarr to handle the subtitles and have to manually rename the files to match the name of the media file.

For instance, **before** the rename, the files were called:
```
'SHADES of BLUE - S02 E13 - Broken Dolls (720p Web-DL).srt'
'SHADES of BLUE - S02 E13 - Broken Dolls (720p Web-DL).mp4'
```

**After** Sonarr Organize & Rename:
```
'SHADES of BLUE - S02 E13 - Broken Dolls (720p Web-DL).srt'
'Shades of Blue - S02E13 - Broken Dolls WEBDL-720p.mp4'
```
Sonarr correctly renames the actual media file, but does nothing with the subtitle nor does Sonarr have a record of the files having any extra information.

If any other information is required, Please let me know so I may provide it.
**Logs**
21-1-10 08:16:00.2|Info|RefreshSeriesService|Skipping refresh of series: Shades of Blue
21-1-10 08:16:00.2|Info|DiskScanService|Scanning Shades of Blue
21-1-10 08:16:00.4|Info|DiskScanService|Completed scanning disk for Shades of Blue
21-1-10 08:16:00.6|Info|ExistingMetadataImporter|Found 0 existing metadata files
21-1-10 08:16:00.6|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
21-1-10 08:16:00.6|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
21-1-10 08:16:00.7|Info|ExistingExtraFileService|Found 0 extra files21-1-10 11:12:30.3|Info|NzbSearchService|Searching 6 indexers for [Shades of Blue : S02E01]
21-1-10 11:13:03.5|Info|RssSyncService|Starting RSS Sync
21-1-10 11:13:06.3|Info|DownloadDecisionMaker|Processing 12 releases
21-1-10 11:14:48.3|Info|DownloadDecisionMaker|Processing 254 releases
21-1-10 11:14:54.5|Warn|RenameEpisodeFileService|File (/tv2/Shades of Blue/Season 2/SHADES of BLUE - S02 E10 - Whoever Fights Monsters (720p Web-DL).mp4) is not linked to any episodes
21-1-10 11:17:02.2|Info|RssSyncService|RSS Sync Completed. Reports found: 254, Reports grabbed: 0
21-1-10 11:17:35.8|Info|RenameEpisodeFileService|Renaming 13 files for Shades of Blue
21-1-10 11:17:47.6|Info|RenameEpisodeFileService|Selected episode files renamed for Shades of Blue
21-1-10 11:32:21.1|Info|RssSyncService|Starting RSS Sync
21-1-10 11:32:33.3|Info|DownloadDecisionMaker|Processing 258 releases
21-1-10 11:33:28.6|Error|CommandExecutor|Error occurred while executing task ProcessMonitoredDownloads

**System Information**

 - Sonarr Version: 3.0.4.1060
 - Operating System: Linux/Ubuntu 20.04
 - Package: 3.0.4.1060-ls24 by linuxserver.io
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34
 - Branch: phantom-develop

**Additional context**
Log file shows:

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

Get Trace Logs https://wiki.servarr.com/Sonarr_Troubleshooting#Asking_for_Help

**Comment by markus101** [comment]
Closing until we have the appropriate logs.
