### ISSUE TITLE
Different notification text for On Import  On Upgrade etc

### ISSUE THREAD

**Issue by leifalbor** [Sonarr/Sonarr#4242]
**Describe the problem**
Sonarr uses the same notification title text for Kodi, Join, etc when a file is Imported, Upgraded, etc,.  Currently it shows: "_Sonarr - Episode Downloaded_".

**Describe any solutions you think might work**
Sonarr should use discreet notification title text Upgraded episodes, ie:  "_Sonarr - Episode Upgraded_".

**Comment by markus101** [comment]
This will be possible when customizing is possible. https://github.com/Sonarr/Sonarr/issues/328
