### ISSUE TITLE
Langage parsing issue (Sonarr v3)

### ISSUE THREAD

**Issue by Wiirlak** [Sonarr/Sonarr#4243]
**Describe the bug**
Sonarr v3 doesn't parse well the langage data, compared to Sonarr v2

**Screenshots**
v3 :
![image](https://user-images.githubusercontent.com/36702513/104189206-a6d82c80-541a-11eb-82b1-3b01b014c841.png)
v2 :
![image](https://user-images.githubusercontent.com/36702513/104189215-aa6bb380-541a-11eb-83cf-05d735dd7457.png)
same episode but different result

**Logs**
-

**System Information**

 - Sonarr Version: :preview (v3.0.4.1060)
 - Operating System: Docker
 - Branch: phantom-develop

**Comment by bakerboy448** [comment]
v3 Parser https://github.com/Sonarr/Sonarr/blob/741fa57f0509c702d5f75f9817f2493a8ce45d87/src/NzbDrone.Core/Parser/Parser.cs#L407

Closing
Based on https://github.com/Sonarr/Sonarr/commit/b841d2e9b42c5bcc98aa7b61a6c198e48d171662 which was committed Jul 30, 2014  this is intentional behavior.

**Comment by bakerboy448** [comment]
Reopening per Markus "vostfr was removed as "french" in v3"

**Comment by bakerboy448** [comment]
Dupe #3977

VOSTFR is a subtitle, the audio is still English. Thus English is correctly expected.

**Comment by Wiirlak** [comment]
> Dupe #3977
> 
> VOSTFR is a subtitle, the audio is still English. Thus English is correctly expected.
> Not a bug; no plans to change.

Thanks, I didn't know that was removed. There is currently no alternative to that feature then, *There is currently no way to add "subtitle" langage choice* 

> **from #3977**
>*We can use release profiles to force "vostfr" string, but then if we want French-made content or releases which doesn't contain "vostfr" (subfrench, or even multi-subs releases like Erai-raws on Nyaa), we cannot.*
**answer :**
> A single release profile that requires all 3 of those terms would be successful if any exist. (The release must contain at least one of these terms (case insensitive)).

Well the answer provided isn't right, since MULTI can be anything, even not french.

French should still be a langage present on the release, in addition to English langage. 
Similar case in Radarr, but dealed with **Custom Formats** 
![image](https://user-images.githubusercontent.com/36702513/104386688-f52e1e00-5535-11eb-8046-5266c973ab96.png)

I went back to the V2 anyway so this can stay close, but i'm curious about it since this V3 look really interesting!

*Suggestion(s)* :
 - Add a subtitle langage option
 - Add subtitle langage to the release langage, in addition to the audio
