### ISSUE TITLE
Series Update and RSSSync buttons

### ISSUE THREAD

**Issue by myozone** [Sonarr/Sonarr#4247]
Series Update and RSSSync buttons no longer animate when clicked also other animated buttons stopped as well - tried with different browsers and it's the same. I'm using version 3.0.4.1061

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.
