### ISSUE TITLE
SetTorrentLabel removed for some download clients

### ISSUE THREAD

**Issue by rogerfar** [Sonarr/Sonarr#4250]
In the new version qBittorrent won't set a category anymore when you add a new torrent.

This commit removed that:
https://github.com/Sonarr/Sonarr/commit/39ea2dd32fe4a5d192e8393c06324a813d1db567
Line 47.

Was this an oversight or intentional change?

uTorrent and Deluge do still have this code, but RTorrent and QBittorrent got it removed.

**Comment by Taloth** [comment]
AddTorrentFromUrl on the proxy passes the label to qbit.

**Comment by markus101** [comment]
Yup, working just fine. `21-1-13 16:01:54.5|Trace|HttpClient|Req: [GET] http:/localhost:8082/query/torrents?label=tv-sonarr&category=tv-sonarr`

**Comment by rogerfar** [comment]
I suppose it would help to upgrade qBitorrent.. I didn't realize it was now passed as a parameter on the add api call.

**Comment by Taloth** [comment]
We've been doing that since 2018. I don't think the qbit version matters much.
