### ISSUE TITLE
Can no longer connect to Sonarr outside of network

### ISSUE THREAD

**Issue by kool2zero** [Sonarr/Sonarr#4251]
To be able to add shows when not connected to my home network, I have used port forwarding on my router to get to Sonarr.  Recently, in the last couple of weeks, I can not longer connect outside of my network using my external IP.  I can connect within the network using localhost and using the internal IP address.  The same issue is also happening with Radarr.  SABnzb seems to still work.
LEt me know what logs or traces you might need.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
