### ISSUE TITLE
Sonarr failing since the update of 3 days ago

### ISSUE THREAD

**Issue by r33mi** [Sonarr/Sonarr#4254]
**Describe the bug**
Sonarr starts and then stops directly, or sometimes it says: can't open this app

**Screenshots**

**Logs**
https://pastebin.com/u23kWmLn

**System Information**

 - Latest v3
 - Operating System: MacOS 10.15.7
 - mono (macOS/Linux) Version: [e.g. .net 4.5 or mono 5.12] Latest MacOS
 - Branch:

**Comment by r33mi** [comment]
https://pastebin.com/u23kWmLn

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

Database file: /Users/remischipperus/.config/Sonarr/sonarr.db is corrupt, restore from backup if available. See: https://wiki.servarr.com/Sonarr_FAQ#I_use_Sonarr_on_a_Mac_and_it_suddenly_stopped_working_What_happened
