### ISSUE TITLE
Sonarr doesn import from, Transmission when warnings are present

### ISSUE THREAD

**Issue by dgalli1** [Sonarr/Sonarr#4255]
**Describe the bug**
When a download via Transmission outputs warnings it will never be finished and imported into Sonarr.
This happens even when the File download is already completed and the warning has nothing to do with the download progress itself.
I noticed this issue when i got this error message:
Download warning: Tracker gave HTTP response code 0 (No Response)

**System Information**

 - Sonarr Version:  3.0.4.1069
 - Operating System: Docker/Linux
 - Branch: phantom

**Comment by bakerboy448** [comment]
Logs...?

**Comment by dgalli1** [comment]
I don't think their is anything relevant in the logs regarding this issue.
Anyways here is a trace of an attempted import:
https://pastebin.com/D9s9VPwv

**Comment by markus101** [comment]
Transmission doesn't differentiate between what type of warning it is, it's just treated as a warning by Sonarr. We're not going to try and guess if we should still try to import it or not.
