### ISSUE TITLE
Repo key for Ubuntu does not work

### ISSUE THREAD

**Issue by jlpza** [Sonarr/Sonarr#4258]
**Describe the bug**
The key for adding Sonarr to Ubuntu does not work. When running the following command extracted directly from the installation tutorial:
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0xA236C58F409091A18ACA53CBEBFF6B99D9B78493
```
The following error is returned:
```
Executing: /tmp/apt-key-gpghome.wICbdwoZf6/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 0xA236C58F409091A18ACA53CBEBFF6B99D9B78493
gpg: keyserver receive failed: Server indicated a failure

```

**UI Bugs:**
 - OS: Ubuntu

**Comment by bakerboy448** [comment]
Could not reproduce; likely your firewall
https://unix.stackexchange.com/questions/399027/gpg-keyserver-receive-failed-server-indicated-a-failure

also
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

```bakerboy448@server:~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0xA236C58F409091A18ACA53CBEBFF6B99D9B78493
[sudo] password for bakerboy448:
Executing: /tmp/apt-key-gpghome.EVoXJWwBLG/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 0xA236C58F409091A18ACA53CBEBFF6B99D9B78493
gpg: key EBFF6B99D9B78493: "NzbDrone <contact@nzbdrone.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

**Comment by Taloth** [comment]
use `--keyserver hkp://keyserver.ubuntu.com:80`
