### ISSUE TITLE
Truncation of file names does not account for the file extension

### ISSUE THREAD

**Issue by mattisdada** [Sonarr/Sonarr#4259]
**Describe the bug**
When dealing with very long file names, the truncation method does not include the file extension into the calculation and attempts to rename the file, but the OS (Windows) prevents the rename from taking place as it is too many characters.

This is very visible in the anime series "Suppose a Kid From the Last Dungeon Boonies Moved to a Starter Town"

Which attempts to rename into this monstrosity: 
```
X:\Anime\Suppose a Kid From the Last Dungeon Boonies Moved to a Starter Town\Season 01\Suppose a Kid From the Last Dungeon Boonies Moved to a Starter Town! - S01E02 - Suppose a majestic lion showed up to the petting section of a zoo and... HDTV-1080p (002).mkv
```
The OS will allow the file name `Suppose a Kid From the Last Dungeon Boonies Moved to a Starter Town! - S01E02 - Suppose a majestic lion showed up to the petting section of a zoo and... HDTV-1080p (002)` (without the extension). Sonarr attempt to fix this by replacing some of the text with an ellipsis (...), but it doesn't appear to have taken into consideration the file extension. 

(the full episode name being: `Suppose a majestic lion showed up to the petting section of a zoo and dozed off?`)

**System Information**

 - Sonarr Version: 3.0.4.1070
 - Operating System: Windows 10 10.0.19041.746 (without long file names enabled)
 - .net Framework (Windows) or mono (macOS/Linux) Version: .net 4.8.0
 - Branch: beta

**Comment by mattisdada** [comment]
Also as a side note, if it attempts to move the files, it will just delete them due to this bug, which is also not fun...

**Comment by Taloth** [comment]
it does account for the extension. Do you have log files? Trace level is a must here.

**Comment by mattisdada** [comment]
[sonarr.log](https://github.com/Sonarr/Sonarr/files/5823583/sonarr.log)
Attached

**Comment by mattisdada** [comment]
[sonnar.trace.log](https://github.com/Sonarr/Sonarr/files/5823601/sonnar.trace.log)

I cleared the logs, enabled trace and recreated the problem for you

**Comment by Taloth** [comment]
Thank you. Should be ok in the next release.
