### ISSUE TITLE
Managing Stalled Torrents

### ISSUE THREAD

**Issue by drowse7en** [Sonarr/Sonarr#4261]
**Describe the problem**
Sonarr does not automatically or proactively manage stalled torrents.

**Describe any solutions you think might work**
Is it possible to integrate or fork the logic from **autoremove-torrents** (https://github.com/jerrymakesjelly/autoremove-torrents) in order to automate the management of stalled torrents?

**Comment by bakerboy448** [comment]
various other issues cover this as well, but no immediate plans

Dupe #958
