### ISSUE TITLE
Notifications "on health restored"

### ISSUE THREAD

**Issue by grozan** [Sonarr/Sonarr#4262]
**Describe the problem**
There is an option to have notifications sent "On Health Issue", and also "Include Health Warnings"
I sometimes receive a notification telling me an indexer is unavailable.
I connect to Sonarr, click the "test all" button, and the error goes away. It was a very short-live problem, like some kind on network glitch or something.

It would great to avoid those kind of alarms
I see other tickets, like #3813, basically asking for a failure to have to happen twice in a row before raising an alarm.
That idea, that I find very good, has been dismissed it seems, unfortunately

**Describe any solutions you think might work**
As an alternative then, would it be possible to have the option to have notifications sent "on health restored", or something like that?
In my case I'd receive the failure notification, and some minutes later would receive the "back to normal" message, telling me I don't have to bother connecting to Sonarr to check what's going on.

Thanks

**Comment by Tuumke** [comment]
I had just openend the above reqest. Didn't see (guess didn't search right) this one. As this has no update for 1.5 year, can we get an update on this?

**Comment by markus101** [comment]
Updates are made when there is something to update on, no progress has been made on this, but I've updated the labels.
