### ISSUE TITLE
Import fails with square brackets at end of download directory

### ISSUE THREAD

**Issue by stephen-d-hill** [Sonarr/Sonarr#4263]
**Describe the bug**
Import fails with square brackets at end of download directory
In log we see:
```
21-1-16 22:08:19.0|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /var/lib/qbittorrent/downloads/tv-sonarr/The.Undoing.S01.COMPLETE.720p.AMZN.WEBRip.x264-GalaxyTV
```
On server filesystem though we see there's extra '[TGx]' at the end- 
```
root@radarr:~# ls /var/lib/qbittorrent/downloads/tv-sonarr
'The.Undoing.S01.COMPLETE.720p.AMZN.WEBRip.x264-GalaxyTV[TGx]'
```
**Logs**
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/5825255/sonarr.txt)

**System Information**
 - Sonarr Version: 2.0.0.5344
 - Operating System: Ubuntu 18.04.5
 - mono (macOS/Linux) Version: 6.12.0.107
 - Branch: release

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

Sonarr v2 and Qbit 4.3+ are not compatible

Upgrade to Sonarr v3 or downgrade Qbit to 4.2.5

**Comment by stephen-d-hill** [comment]
I upgraded to Sonarr v3.0.4.988, it still has exactly the same problem:
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/5825837/sonarr.txt)
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/5825838/sonarr.debug.txt)

**Comment by stephen-d-hill** [comment]
In Sonarr it told me there were updates, so I updated to the latest v3.0.4.1076, and this has fixed the problem :-)
