### ISSUE TITLE
Add the ability to move episode into own folder, without renaming media file.

### ISSUE THREAD

**Issue by aevans0001** [Sonarr/Sonarr#4264]
**Describe the problem**
The problem is that I like to download subtitles from Bazarr.  However I also like my directory structure nice and tidy.  Sometimes Sonarr or Bazarr do not pass along the scene name to each other.  This causes less than perfect subtitle downloads.  I would be willing to give up my custom naming of the file, basically show title - season episode - episode name (resolution), if I could at least get the individual episodes into their own folder.  Currently my episodes go into 
c:\Series\Season\Episode\Media File.mkv  

**Describe any solutions you think might work**
Add in a section similiar to season folder format.  But let me decide on a custome format for Episode
 
**Additional context**
Thank you very much for this well polished piece of software.

**Comment by Taloth** [comment]
`{Original Title}` contains the original name if available.

**Comment by bakerboy448** [comment]
Episodes in sub folders should be doable as well...just add the folder naming or schema  and a \  in your episode naming 

PS you should store group and quality in your names (and preferred words as well) just in case you ever lose your db (or sonarr loses track of the file)

**Comment by markus101** [comment]
With differences between TheTVDB and release (scene) numbering, not renaming is going to be problematic. As long as Sonarr doesn't lose track of the file after importing it should have the original title from importing. If it did then having information in the filename like Baker suggested could be a viable tradeoff.

Sonarr can already do what you're asking for though.
