### ISSUE TITLE
Sonarr search support for complete TV show pack

### ISSUE THREAD

**Issue by HLFH** [Sonarr/Sonarr#4268]
Hi,

**Describe the problem**
On the YGGTorrent indexer, I want to download the complete TV show pack for Sex and the City.
Sonarr only supports episodes, and season packs search.

**Describe any solutions you think might work**
Two keywords used for TV show pack I am aware of: "INTEGRAL", and "Complete".
<img width="1084" alt="Screenshot 2021-01-19 at 11 35 35" src="https://user-images.githubusercontent.com/2359059/105029631-80ce1000-5a4a-11eb-9aad-22d437c78987.png">

Can you support that?

Thanks,
HLFH

**Comment by markus101** [comment]
We do not have plans to support full series packs.
