### ISSUE TITLE
Skyhook requires refreshing - cannot import tvdb:54383

### ISSUE THREAD

**Issue by Iristyle** [Sonarr/Sonarr#4269]
**Describe the bug**

Attempt to `Add New` given either the name `Wolfwalkers` *or* `tvdb:54383` - no matches returned. FAQ at https://wiki.servarr.com/Sonarr_FAQ#Why_cant_I_add_a_new_series_when_I_know_the_TVDB_ID states that the reason is:

> Sonarr cannot add any series that does not have an English language title. If you try to add a series via TVDB ID that does not have an English title. If no English title exist for that series on TheTVDB it will need to be added (if available).

Checking Skyhook, the show id is indeed returning a 404 at https://skyhook.sonarr.tv/v1/tvdb/shows/en/54383 - but there is clearly an English title at https://thetvdb.com/movies/wolfwalkers, and the last modified date was about a month ago on Dec 14, 2020

Not sure if skyhook needs to be kicked / refreshed, or if there is some other skyhook bug.

**Screenshots**

Not necessary.

**Logs**

```
21-1-19 08:44:02.1|Trace|Http|Req: 2531 [GET] /api/v3/series/lookup?term=tvdb%3A54383 (from 172.18.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36)
21-1-19 08:44:02.1|Trace|HttpClient|Req: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/54383
21-1-19 08:44:02.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
21-1-19 08:44:02.6|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/54383: 404.NotFound
{"message":"NotFound","description":"thetvdb.com does not have a series with the tvdbid 54383, it may have been removed."} (452 ms)
21-1-19 08:44:02.6|Trace|Http|Res: 2531 [GET] /api/v3/series/lookup?term=tvdb%3A54383: 200.OK (458 ms)
21-1-19 08:44:02.6|Debug|Api|[GET] /api/v3/series/lookup?term=tvdb%3A54383: 200.OK (458 ms)
```

**System Information**

 - Sonarr 3.0.4.1077 — Jan 17 2021 phantom-develop (from container)
 - linuxserver.io container running on Synology
 - Version 3.0.4.1077
 - Package Version 3.0.4.1077-ls35 by linuxserver.io
 - Mono Version 5.20.1.34
 - Branch: phantom-develop

**Additional Info**

Search code in Skyhook looks fine, problem appears to be in the cached content - https://github.com/Sonarr/Sonarr/blob/182ad17b777fba11df0750620da2ce165688ed84/src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs#L40-L68

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.


As has been answered countless times, TheTVDB has a 24-hour cache, it'll take that long before Skyhook can get updated information, this is not a bug in Sonarr, this is their design.

**Comment by bakerboy448** [comment]
that TVDB entry will never be on Skyhook,  it's a movie

https://thetvdb.com/movies/wolfwalkers

**Comment by Iristyle** [comment]
Hah, thanks @bakerboy448 🤦
