### ISSUE TITLE
Issue for Episode number more than 100. Search and match are good, but import by activity panel, not

### ISSUE THREAD

**Issue by blackmessor** [Sonarr/Sonarr#4272]
For a show in absolute number with a lot of episode number. When i try to search episode 144 (show is set as anime for absolute number), the search is good, and it find and download episode 144. 
But when during the donwload i look at the activity panel, he is waiting for the 1x44. So at the end he download the episode 144 and it will replace the episode 44 with the new one. 

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: [e.g. Windows 10 2004]
 - .mono 6.10
 - Branch:

**UI Bugs:**
 - OS: Docker
 - Browser: firefox

**Comment by markus101** [comment]
This is going to be due to naming, though this behaviour is improved in v3. If this still persists there for you update this issue with the requested logs and we can reopen.
