### ISSUE TITLE
Filtering on "Type" is not working

### ISSUE THREAD

**Issue by DIDev1** [Sonarr/Sonarr#4274]
**Describe the bug**
When trying to set up custom filters on the "Series view"  and select "Type" as filter and write keyword like Anime,Standard or Daily it doesn't work and return no shows.

**To Reproduce**
On **Series Page**
Go To **Filter**
Click on **Custom Filters**
Then **Add Custom Filter**
Select **Type** as filter then **is/is not** and write Anime,Daily or Standard as values

**Expected behavior**
A Filtered page with my Daily, Standard or Anime shows

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): 5.20.1.34
 - Sonarr Version: 3.0.4.1061
 - Sonarr Branch: phantom-develop

**Comment by bakerboy448** [comment]
`Daily` does not work for filtering; ‘daily’ does

@markus101 suboptimal here; type is currently free text that should probably be some type of drop down, no?  If not then we should at least make it case intensive given the UI has proper casing

**Comment by DIDev1** [comment]
Hey,

Thanks for the reply.
Same for anime, it's working with lowercase.

Thanks for the reply, it's solving this issue.
It would remove some error like this one if this was a drop down list for sure
