### ISSUE TITLE
Add Hindi lanuage support

### ISSUE THREAD

**Issue by NewUser9** [Sonarr/Sonarr#4275]
Hi,

Please add support for Hindi language.

Regards.

**Comment by markus101** [comment]
Please use the templates when opening issues. We'll need example file names to consider this issue.

**Comment by NewUser9** [comment]
> 
> 
> Please use the templates when opening issues. We'll need example file names to consider this issue.

Here are some examples of releases with Hindi language:
```
The Witcher S01 E01-08 WebRip Dual Audio [Hindi 5.1 + English 5.1] 720p x264 AAC ESub
Tandav.2021.Hindi.S01.Complete
The Last Kingdom (2020) S04 Complete 720p NF WEBRip [Hindi+English] Dual audio
```
