### ISSUE TITLE
MediaInfo/Renaming - HDR (VideoDynamicRange) not picked up (Dolby Vision?)

### ISSUE THREAD

**Issue by stephenpope** [Sonarr/Sonarr#4276]
**Describe the bug**

When renaming HDR content .. the HDR `MediaInfo.VideoDynamicRange` does not seem to be picked up. 
I am not sure if this is because this is Single-layer Dolby Vision (a work-around to get DV to work in Plex) or its just a bug.

(Would be nice to get the HDR format (ie HDR10 / DV / HDR10PLUS) displayed but I can put that ina feature request :)

**To Reproduce**

Original file: `[SHOW].S01E02.[TITLE].2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.HEVC.mp4`
Renamed file : `[SHOW].2019.S01E02.[TITLE].WEBDL-2160p.HEVC.EAC3.Atmos.5.1.mp4`

Filename settings: `{Series.CleanTitleYear}.S{season:00}E{episode:00}.{Episode.Title}.{Quality.Full}.{MediaInfo.VideoCodec}.{MediaInfo.VideoDynamicRange}.{MediaInfo.AudioCodec}.{MediaInfo.AudioChannels}`

MediaInfo :
```
General
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (mp42/dby1/isom)
File size                                : 8.25 GiB
Duration                                 : 51 min 51 s
Overall bit rate                         : 22.8 Mb/s
Encoded date                             : UTC 2020-11-02 16:16:57
Tagged date                              : UTC 2020-11-02 16:16:57

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.2@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
Codec ID                                 : dvhe
Codec ID/Info                            : High Efficiency Video Coding with Dolby Vision
Duration                                 : 51 min 51 s
Bit rate                                 : 22.0 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 0)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.111
Stream size                              : 7.97 GiB (97%)
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 2020-11-02 16:16:57
Tagged date                              : UTC 2020-11-02 16:16:57
Color range                              : Full
Codec configuration box                  : hvcC+dvcC
```

**Expected behavior**

I would expect to see `[SHOW].2019.S02E01.[TITLE].WEBDL-2160p.HEVC.HDR.EAC3.Atmos.5.1`

**Screenshots**

N/A
**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.10
 - Docker: No
 - .NET Framework: 6.8.0.105 (Linux)
 - Browser and Version (Only needed for UI issues): N/A
 - Sonarr Version: 3.0.4.1083
 - Sonarr Branch: phantom-develop

**Trace Logs**
```
21-1-22 11:35:25.8|Info|RenameEpisodeFileService|Renaming 1 files for [SHOW]
21-1-22 11:35:25.8|Debug|RenameEpisodeFileService|Renaming episode file: [16541] Season 01/[SHOW].S01E02.Chapter.2.2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.HEVC-MZABI.mp4
21-1-22 11:35:25.8|Debug|EpisodeFileMovingService|Renaming episode file: [16541] Season 01/[SHOW].S01E02.Chapter.2.2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.HEVC-MZABI.mp4 to /mnt/tv-volume-4k/TV-4K/[SHOW]/Season 01/[SHOW].2019.S01E02.[TITLE].WEBDL-2160p.HEVC.EAC3.Atmos.5.1.mp4
21-1-22 11:35:25.8|Debug|DiskTransferService|Move [/mnt/tv-volume-4k/TV-4K/[SHOW]/Season 01/[SHOW].S01E02.Chapter.2.2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.HEVC-MZABI.mp4] > [/mnt/tv-volume-4k/TV-4K/[SHOW]/Season 01/[SHOW].2019.S01E02.Chapter.2-.The.Child.WEBDL-2160p.HEVC.EAC3.Atmos.5.1.mp4]
21-1-22 11:35:25.8|Debug|DiskProvider|Setting permissions: 755 on /mnt/tv-volume-4k/TV-4K/[SHOW]/Season 01/T[SHOW].2019.S01E02.[TITLE].WEBDL-2160p.HEVC.EAC3.Atmos.5.1.mp4
21-1-22 11:35:25.8|Debug|RenameEpisodeFileService|Renamed episode file: [16541] Season 01/[SHOW].2019.S01E02.[TITLE].WEBDL-2160p.HEVC.EAC3.Atmos.5.1.mp4
21-1-22 11:35:25.8|Debug|NotificationService|No tags set for this notification.
21-1-22 11:35:25.8|Debug|PlexServer|Scheduling library update for series 113 [SHOW]
21-1-22 11:35:25.8|Info|RenameEpisodeFileService|Selected episode files renamed for [SHOW]
```

**Comment by stephenpope** [comment]
It seems this file is missing `transfer_characteristics` + `colour_primaries` fields needed to match successfully in the `MediaInfoFormatter.cs => FormatVideoDynamicRange` function.

**Comment by Matty666** [comment]
Interesting! It seems newer mediainfo versions can provide the `HDR Format` property which can be used as well as the transfer characteristics, according to this post:

https://sourceforge.net/p/mediainfo/discussion/297610/thread/2da4fc24a4/

@Taloth, @markus101, would there be any issues with upgrading mediainfo to a version that supports this property? I can see the dll in the source code has had a few updates, but they seem to be specific to mac/windows, how does it work for linux?

**Comment by markus101** [comment]
> how does it work for linux?

The user provides their own mediainfo this might be different for some packages on some systems, but that's how it is for Ubuntu.
