### ISSUE TITLE
Path not supported

### ISSUE THREAD

**Issue by BjoernUsw** [Sonarr/Sonarr#4277]
Sonarr v3 suddenly stopped importing nzbget downloads after a recent update for the windows version (3.0.4.1080). Tried fixing it with uninstalling and installing of the latest windows version (3.0.4.1083), error persists. Downgraded to original installed version (3.0.4.1077, previously working, was installed as v2 replacement), same error.
Drive M: (from the log) never existed.
Errorlog:

Details
Message
Couldn't import episode D:\completed\[LostYears] Attack on Titan S03E19 (56) (WEB 1080p Hi10 AAC) [Dual Audio] (Shingeki no Kyojin)\[LostYears] Attack on Titan S03E19 (56) (WEB 1080p Hi10 AAC) [5AD1ACBD].mkv: Das angegebene Pfadformat wird nicht unterstützt.
Exception
System.NotSupportedException: Das angegebene Pfadformat wird nicht unterstützt.

   bei System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)

   bei System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)

   bei System.IO.FileInfo.Init(String fileName, Boolean checkHost)

   bei System.IO.FileInfo..ctor(String fileName)

   bei NzbDrone.Common.Extensions.PathExtensions.CleanFilePath(String path) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Extensions\PathExtensions.cs:Zeile 34.

   bei NzbDrone.Common.Extensions.PathExtensions.PathEquals(String firstPath, String secondPath, Nullable`1 comparison) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Extensions\PathExtensions.cs:Zeile 57.

   bei NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:Zeile 255.

   bei NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile(EpisodeFile episodeFile, Series series, List`1 episodes, String destinationFilePath, TransferMode mode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:Zeile 116.

   bei NzbDrone.Core.MediaFiles.EpisodeFileMovingService.MoveEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:Zeile 77.

   bei NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:Zeile 77.

   bei NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:Zeile 111.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.
