### ISSUE TITLE
QBitTorrent new web api

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#4279]
The QBitTorrent nighties from the last few days don't seem to work with sonarr. Pressing the test button it is looks like it is fine but the error comes back when sonarr tries to check for downloads or send torrents. If no one can reproduce and need debug logs let me know but it will take me a few days as I am away from my pc and cant remote in at the moment.      

Version
3.0.4.1083
Package Version
3.0.4 by Team Sonarr
Mono Version
6.12.0.107
AppData directory
/var/lib/sonarr
Startup directory
/usr/lib/sonarr/bin
Mode
Console

**Comment by Taloth** [comment]
Latest unstable (https://hub.docker.com/layers/linuxserver/qbittorrent/unstable/images/sha256-51e779db9706a14f6bb514508e6faf8b37340fa24acc0deb156c019e123074ee?context=explore) Tests fine for me. So it's likely some local issue, or specific to the torrents you have in the system.
Please check the logs once you can and investigate, reopen issue once there's something actionable.
