### ISSUE TITLE
/api/v3/system/backup/restore/upload: 404.NotFound

### ISSUE THREAD

**Issue by scottrobertson** [Sonarr/Sonarr#4281]
Version: 3.0.4.1083
Running on Windows

When trying to upload a backup, i get the following:

21-1-23 22:53:23.3|Trace|Http|Req: 43 [POST] /api/v3/system/backup/restore/upload (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36)
21-1-23 22:53:23.3|Debug|ArchiveService|Extracting archive [C:\Windows\ServiceProfiles\LocalService\AppData\Local\Temp\sonarr_backup_restore.zip] to [C:\Windows\ServiceProfiles\LocalService\AppData\Local\Temp\sonarr_backup_restore]
21-1-23 22:53:23.3|Debug|ArchiveService|Validating Archive C:\Windows\ServiceProfiles\LocalService\AppData\Local\Temp\sonarr_backup_restore.zip
21-1-23 22:53:23.4|Debug|ArchiveService|Extraction complete.
21-1-23 22:53:23.4|Trace|SonarrErrorPipeline|Handling Exception
21-1-23 22:53:23.4|Trace|Http|Res: 43 [POST] /api/v3/system/backup/restore/upload: 404.NotFound (165 ms)
21-1-23 22:53:23.4|Debug|Api|[POST] /api/v3/system/backup/restore/upload: 404.NotFound (165 ms)

**Comment by Taloth** [comment]
Means the backup zip file is empty or at least doesn't contain the necessary files.

**Comment by scottrobertson** [comment]
It has config.xml, and sonarr.db. Should it have anything else?

**Comment by scottrobertson** [comment]
Never mind, MacOS being stupid and putting a subfolder in there. Thanks @Taloth
