### ISSUE TITLE
Sonarr doesn't find all the release of my indexers (Jackett)

### ISSUE THREAD

**Issue by WoisWoi** [Sonarr/Sonarr#4283]
Hi,

Better than long talk :

![Marco Polo Jackett](https://user-images.githubusercontent.com/75491231/105761107-fce8bc00-5f52-11eb-8075-1476c2ddb18f.PNG)
![Marco Polo Sonarr](https://user-images.githubusercontent.com/75491231/105761108-fd815280-5f52-11eb-8162-90bd89617013.PNG)

Thanks a lot if you can help me :)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
