### ISSUE TITLE
Superscript numerals in titles aren't included in slug, can't add show Connections 2 or 3

### ISSUE THREAD

**Issue by CeeJayMI** [Sonarr/Sonarr#4285]
**Describe the bug**
When trying to add all 3 of the show Connections, after adding Connections, I cannot add Connections2 or Connections3, because the numerals are superscript and aren't included in the slug, causing a duplicate slug error. 

**To Reproduce**
Add show Connections (1978), then try to add Connections2 or Connections3

**Expected behavior**
Should be able to add the shows

**Screenshots**
![2021-01-26 10_24_45-Add New Series - Sonarr - Vivaldi](https://user-images.githubusercontent.com/43674199/105869616-686b7180-5fc5-11eb-94ce-1268ca17bc25.png)

**Platform Information (please complete the following information):**
 - OS: Windows 10
 - Docker: No
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): .net Version 4.8.0
 - Browser and Version (Only needed for UI issues): 
 - Sonarr Version: 3.0.4.1091
 - Sonarr Branch: phantom-develop

**Trace Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/5874487/sonarr.trace.txt)

**Comment by CeeJayMI** [comment]
my thoughts on a fix would be to either a) include the superscripted text in slugs (e.g. connections, connections2, connections3) or b) append a numeral to the end of a slug if there's a duplicate (e.g. connections, connections-1, connections-2).

**Comment by Haulien** [comment]
TVDB is also doing something weird with those shows. The listing for [Connections](https://www.thetvdb.com/series/connections)(1) has 3 seasons, [season 2](https://www.thetvdb.com/series/connections/seasons/official/2) and [season 3](https://www.thetvdb.com/series/connections/seasons/official/3) are [Connections2](https://www.thetvdb.com/series/connections2) and [Connections3](https://www.thetvdb.com/series/connections3), which also both have their own separate listings.

**Comment by CeeJayMI** [comment]
good find, it is showing all 3 seasons of Connections in the first season, so I don't need to add the other 2 shows, this report is moot for me now. but it still seems like a bug in the slug creation

**Comment by Thirrian** [comment]
I’m just here to say thanks for pointing me to this one, as if I don’t already have enough shows to watch in my backlog 😅

**Comment by austinwbest** [comment]
or just switch it to the tvdb id instead :)

**Comment by markus101** [comment]
This will be resolved the next time the series refreshes in skyhook.
