### ISSUE TITLE
Show season pack downloads as one item in the download queue

### ISSUE THREAD

**Issue by Archerofyail** [Sonarr/Sonarr#4286]
Right now season pack downloads come up as individual episodes in the queue, which makes the download queue cluttered, and honestly, pretty useless, especially when downloading a lot of things. I think it would be better if season packs just showed up as one line, listing the number of episodes e.g. 1x01-20.

**Comment by markus101** [comment]
We do not have plans to change this behaviour at this time.

**Comment by austinwbest** [comment]
> Right now season pack downloads come up as individual episodes in the queue, which makes the download queue cluttered, and honestly, pretty useless, especially when downloading a lot of things. I think it would be better if season packs just showed up as one line, listing the number of episodes e.g. 1x01-20.

Is a good idea though, would also fix the issue where it looks like 20 episodes are stuck because 1 is a TBA and the other 19 already imported but are still sitting in the queue lol
