### ISSUE TITLE
Assign Friendly Name to Root Folders

### ISSUE THREAD

**Issue by drowse7en** [Sonarr/Sonarr#4291]
**Describe the problem**
a clear and concise description of the problem you're looking to solve.

Importing content from another instance of Sonarr, using Sonarr's list feature is difficult as it automatically imports all of the content from Sonarr and doesn't discriminate between content type (television or anime in different root folders) and doesn't assign to matching root folders.

**Describe any solutions you think might work**
Is it possible to assign friendly names to root folders and automatically tag content by root folder?

This will make it easier to manage the import of content through Sonarr's list feature or Syncarr.

**Comment by markus101** [comment]
It is not possible nor something we have plans for at this time.
