### ISSUE TITLE
Some links generated by Jackett are not properly parsed

### ISSUE THREAD

**Issue by kekal** [Sonarr/Sonarr#4294]
This behaviour is reproduced with Anilibria indexer, which has a cyrillic part in titles, and it is very similar to #3573. I don't know, actually, why this bug related only to one title but here the situation:

#### 1. Sonarr queries the Jackett with the string "Horimiya 04" 
http://172.17.0.1:9117/api/v2.0/indexers/AniLibria/results/torznab/api?t=search&cat=5070,100001&extended=1&apikey=(removed)&offset=0&limit=100&q=Horimiya+04

#### 2. Jackett returns a proper list of results. One of them:
   ```xml
    <item>
      <title>Хоримия / Horimiya 2021 [WEBRip 1080p] - 1-4</title>
      <guid>https://www.anilibria.tv//upload/torrents/13703.torrent</guid>
      <jackettindexer id="AniLibria">AniLibria</jackettindexer>
      <comments>https://www.anilibria.tv//release/horimiya.html</comments>
      <pubDate>Sun, 31 Jan 2021 19:00:02 +0000</pubDate>
      <size>5650952371</size>
      <grabs>992</grabs>
      <description />
      <link>http://ds718:9117/dl/AniLibria/?jackett_apikey=didhp6534xfctqcmt4d20wvou4bdl4w3&amp;path=Q2ZESjhLUUtXRUtfMWN0SGt3QUNpQzExLXJpWUNSWnRUNDJTNW9RSVN5dGdudDZ3UlRodGxJVUJYUUpsN1NUXzE3M1RMUGRGdmxZdy0zaVJNQXV5MmdGWnM5SkhycE44NlJmQTM0Ml9uMlU3TzNwZ053T2NDTFRPMXZkbElZZUpmR0JHUUZKV0ZDN1g1aW5RQWtOWDJSSjRCYmlyNmpYc3lrMklvOVN6U1k1aWpCSWtlbW5nVjhUM0lWck5KOGlfQWY2S1ZR&amp;file=%D0%A5%D0%BE%D1%80%D0%B8%D0%BC%D0%B8%D1%8F+%2F+Horimiya+2021+%5BWEBRip+1080p%5D+-+1-4</link>
      <category>5070</category>
      <enclosure url="http://ds718:9117/dl/AniLibria/?jackett_apikey=didhp6534xfctqcmt4d20wvou4bdl4w3&amp;path=Q2ZESjhLUUtXRUtfMWN0SGt3QUNpQzExLXJpWUNSWnRUNDJTNW9RSVN5dGdudDZ3UlRodGxJVUJYUUpsN1NUXzE3M1RMUGRGdmxZdy0zaVJNQXV5MmdGWnM5SkhycE44NlJmQTM0Ml9uMlU3TzNwZ053T2NDTFRPMXZkbElZZUpmR0JHUUZKV0ZDN1g1aW5RQWtOWDJSSjRCYmlyNmpYc3lrMklvOVN6U1k1aWpCSWtlbW5nVjhUM0lWck5KOGlfQWY2S1ZR&amp;file=%D0%A5%D0%BE%D1%80%D0%B8%D0%BC%D0%B8%D1%8F+%2F+Horimiya+2021+%5BWEBRip+1080p%5D+-+1-4" length="5650952371" type="application/x-bittorrent" />
      <torznab:attr name="category" value="5070" />
      <torznab:attr name="seeders" value="30" />
      <torznab:attr name="peers" value="72" />
      <torznab:attr name="downloadvolumefactor" value="0" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
   ```

   It is a correct link and part with the title after reverse Q.P. reencoding looks well:
   ```file=%D0%A5%D0%BE%D1%80%D0%B8%D0%BC%D0%B8%D1%8F+%2F+Horimiya+2021+%5BWEBRip+1080p%5D+-+1-4```
   ↓
   ```file=Хоримия+/+Horimiya+2021+[WEBRip+1080p]+-+1-4```

#### 3. Click on the download button causes the error:
   ![image](https://user-images.githubusercontent.com/13663141/106401668-0b8d1280-642e-11eb-9333-385b41937974.png)

   Log exposes this messages:
   `21-1-31 23:09:41.4|Debug|ParsingService|Unable to find Ð¥Ð¾Ñ€Ð¸Ð¼Ð¸Ñ / Horimiya - S20E21 WEBRip-1080p v1`
   `21-1-31 23:09:41.4|Debug|Api|[POST] /api/v3/release: 404.NotFound (10 ms)`
   `21-1-31 23:09:44.4|Debug|Api|[GET] /api/v3/log?page=1&pageSize=50&sortDirection=descending&sortKey=time: 200.OK (9 ms)`

**Platform Information:**
 - OS: Synology 
 - Docker: Yes 
 - Mono 5.20.1.34
 - Sonarr Version: 3.0.3.970-ls55 by linuxserver.io

**Comment by bakerboy448** [comment]
Not that I’m sure it’ll solve your issue or not but you are a whole point and 100 versions behind latest is 3.0.4.1095

**Comment by kekal** [comment]
> Not that I’m sure it’ll solve your issue or not but you are a whole point and 100 versions behind latest is 3.0.4.1095

Reproducible on 3.0.4.1095
![image](https://user-images.githubusercontent.com/13663141/106402719-80168000-6433-11eb-9c9e-cb8b3aad52d6.png)

**Comment by Taloth** [comment]
The whole release title is in an unsupported format, Sonarr can't identify what the episode numbers are because it's not following any common standard.

**Comment by kekal** [comment]
@Taloth 
This is most likely true, but Sonarr successfully parses this title-pattern in dozens of other releases. As I see, the problem is in the encoding and inability to read the provided torrent URL, not in the name parsing.

Useful Sonarr function perfectly compensates the inability to read the distribution content automatically: interactive addition of an already downloaded torrent manually.

I don't think this is a reason to close our eyes to this issue. 
At long last, why the function of manually acquiring release exists, if not in case of parsing errors?

**Comment by Taloth** [comment]
As you can see in that log entry, it thinks the episode might be S20E21 which does not exist. That goes back to not being able to properly parse the release title.
The manual grab fails for the same reason. You could argue that it shouldn't allow you to attempt the grab, but in the end it doesn't matter: It not going to work.

> At long last, why the function of manually acquiring release exists, if not in case of parsing errors?

To allow people to pick releases they prefer. Or to pick releases that were rejected for other reasons, such as quality, age, size or keyword restrictions that the user configured.

**Comment by kekal** [comment]
@Taloth 
> in the end it doesn't matter: It not going to work.

Why? I will not be able to import the files manually? 

Generally speaking, this was an interactive search for a season, not an episode, so this numbering error looks even more counterintuitive.

And it's not entirely clear why Sonarr need to validate release (for episodes) after it has already successfully found an item. Does the release match the search criteria, but not the "download" criteria? I wouldn't have guessed.

As for the episodes: I have seen quite a few TV shows that, for example, were republished by FOX or Netflix with a different episode numbering, such as American Dad or Archer. Sonarr can only see original numbering from TVDB, so, in theory, I should not be able to download them?

This behaviour simply cuts the seemingly available functionality. 
Instead of a simple click, I need:
   1. Download torrent manually
   2. Change the location folder of the series in sonar to downloads location
   3. Add downloaded files
   4. Swap the location of the files back. 
   5. Apply manual rename.
     Besides, the series will disappear from the torrent client, and I will not distribute them to other peers, as is required by basic politeness.

OR
   I can copy files with NAS web control and should remember, that I need to remove downloads after seeding.

Is this messing around worth that rigidity of principles of naming releases somewhere on the Internet?
I guess I'm getting into some old holy war, and I'm nobody, and may not impose anything, but I think this is a somewhat one-sided approach of possible Sonarr usages.

**Comment by Thirrian** [comment]
> As for the episodes: I have seen quite a few TV shows that, for example, were republished by FOX or Netflix with a different episode numbering, such as American Dad or Archer. Sonarr can only see original numbering from TVDB, so, in theory, I should not be able to download them?

Not to be the “well, actually...” guy, but sonarr doesn’t exclusively use thetvdb numbering: https://github.com/Sonarr/Sonarr/wiki/FAQ#how-does-sonarr-handle-scene-numbering-issues-american-dad-etc

**Comment by kekal** [comment]
@Thirrian 
> Not to be the “well, actually...” guy, but sonarr doesn’t exclusively use thetvdb numbering: https://github.com/Sonarr/Sonarr/wiki/FAQ#how-does-sonarr-handle-scene-numbering-issues-american-dad-etc

Given the topic of this issue, you want to say that I need to submit a request for a new mapping of the TV show and in the end, Sonarr will allow me to grab the release? 
If this is what you meant, then I'm sure it is worth adding to the above "messing around" list.

**Comment by Thirrian** [comment]
I guess in this case that’s not going to help. I just wanted to say it’s not as clear-cut as “sonarr uses thetvdb and that’s it”.

As to why it won’t grab, I think it comes down to the fact that sonarr can’t handle the release name, as Taloth indicated.
The easiest would be to grab it manually, but that’s failing too, I understand.
So the next step down from automation is to add it to your download client manually, give it a decent, simple name and apply the sonarr category/label/however it works in your client. Sonarr will start tracking and eventually import it when done.

Since I don’t know anything about anime and any release name looks like “we’re just making shit up” to me, I can’t comment on what a simple name would look like.
For regular series, if I ever have this issue, I call them “series.name.exactly.as.in.sonarr.SxxEyy.1080p.bluray-releasegroup” for example and that works perfectly.

**Comment by kekal** [comment]
@Thirrian 

Actually, this is very beneficial information.
I didn’t know that [Sonarr can track downloads](https://github.com/Sonarr/Sonarr/wiki/Downloads-and-Importing#:~:text=If%20you're%20adding,the%20correct%20category) that weren't created by it. RTFM is my weak point.
I will definitely try it, and it should save me a lot of time if it works. Thanks.

Although, the essence of the current product position in this issue not clear to me. As you put it, “we’re just making shit up” is around everywhere and fighting it is like fighting the rain (or, maybe,  my moviegoer desires are unconventional©). But if the Sonarr gave an umbrella - I think not only I would be grateful.
