### ISSUE TITLE
Remember different name if selected with manual search

### ISSUE THREAD

**Issue by cjaustin1792** [Sonarr/Sonarr#4295]
**Describe the problem**
Naming was slightly different, I.E Sonarr wants "The Bay" but my indexer uses "The Bay (2019)" but they show up when you use manual search.  

**Describe any solutions you think might work**
If you were to use manual search and then download a file that shows up in manual search but doesnt perfectly match show title, It should ask you if you want too remember that name scheme.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/Sonarr_FAQ#why_cant_sonarr_import_episode_files_for_series_x_why_cant_sonarr_find_releases_for_series_x

No plans.
