### ISSUE TITLE
Indexers Categories unable to scroll & difficulty saving

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4296]
**Describe the bug**

Discovered in Readarr when attempting to edit an indexers categories
Mobile (iOS) is unable to scroll when there are a lot of categories.  This makes the webpage completely unusable.
Mobile (Android + iOS) is difficult to save
**To Reproduce**

See above
**Expected behavior**

User should be able to scroll regardless of device and also easily save without issue.

**Screenshots**

![image](https://user-images.githubusercontent.com/55419169/106800978-c6800080-6626-11eb-9eef-b89e25d4218d.png)

**Platform Information (please complete the following information):**
 - OS:  Agnostic
 - Docker:  No
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status):  Agnostic
 - Browser and Version (Only needed for UI issues):  Agnostic
 - Sonarr Version:  3.0.4.1098
 - Sonarr Branch:  phantom-develop

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
N/A

**Note: Cannot be reproduced in Chrome Dev Tools; device only**

**Comment by markus101** [comment]
I've sporadically been able to reproduce the scrolling issue in Safari on iOS, but it also means I have no idea if I've fixed it with a small tweak I've made. If it's still reproducible after the fix then it's likely a browser bug that we can't work around.
