### ISSUE TITLE
Table View column order is lost after page refresh 

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4297]
Reference:
https://github.com/Radarr/Radarr/issues/5861

Per Q, Sonarr issue.

Some columns stick after a refresh of index; some do not and reset to their original position

Edit: Repoed in Sonarr as well

3.0.4.1098

**Comment by markus101** [comment]
Which ones in Sonarr reset? I've tried `Size on Disk`, `Language Profile` and `Network` they're not moving.

**Comment by Qstick** [comment]
> Which ones in Sonarr reset? I've tried `Size on Disk`, `Language Profile` and `Network` they're not moving.

See Radarr dev channel

**Comment by bakerboy448** [comment]
![SonarrColumn](https://user-images.githubusercontent.com/55419169/106844049-239ea500-666d-11eb-9eb6-3c1cc3fea331.gif)
Gif

**Comment by protogen** [comment]
The columns that reset for me are `Size on Disk`, `Quality Profile` and `Status`.  See the screenshots in https://github.com/Radarr/Radarr/issues/5861.

Also, the resetting of the columns is inconsistent.  Sometimes `Size of Disk` will stick after a refresh, other times it will reset.  I haven't been able to predict the reset pattern, or work out how to move the columns to produce a predictable resetting.  I initially thought the reset depended upon how far you move a column, or which direction you move it (up vs down), when initially reordering (in Options), however my testing hasn't produced predictable results.

The best way I've found to see resetting occurring is to clear all browser settings for the site before performing a test.

**Comment by markus101** [comment]
Closed in linked commit.
