### ISSUE TITLE
RARBG API adds incorrect trackers to torrent clients

### ISSUE THREAD

**Issue by architdate** [Sonarr/Sonarr#4306]
**Describe the bug**

Downloads via RARBG are always stuck downloading metadata. The reason this happens is that the API for RARBG does not return the correct trackers for the torrent. Adding the torrent via a magnet link from rarbg works and downloads just fine. Copying over/merging trackers also works fine.

**To Reproduce**

The RARBG API should pull correct ports for the UDP trackers

**Screenshots**

**Platform Information (please complete the following information):**
 - OS:  Windows 10
 - Docker:  No
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status):  N/A
 - Browser and Version (Only needed for UI issues):  N/A
 - Sonarr Version:  2.0.0.5344
 - Sonarr Branch:  Tried on both master and phantom-develop

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
N/A for this issue but: https://pastebin.com/ZiD0CNhU

**Comment by fryfrog** [comment]
To be clear we know this isn't a Sonarr issue, this is some sort of issue w/ rarbg API. We're hoping sonarr devs have some special insight to their api or maybe know a guy or how to report api issues?

**Comment by markus101** [comment]
Closing as this isn't a bug, Taloth might have thoughts, but that should be discussed on discord.

**Comment by Taloth** [comment]
You should enable DHT+PEX for peer exchange. Regardless, rarbg has updated the ports on the api response for legacy clients that don't implement BEP 34. Still, DHT+PEX is recommended.
