### ISSUE TITLE
Input fields on General Settings page are encoded unexpectedly

### ISSUE THREAD

**Issue by MBRO95** [Sonarr/Sonarr#4309]
**Describe the bug**
Recently discovered a bug in the General Settings/config.xml files.
Text entered into these fields appears to be processed through a URL decoder or some hash function that is converting characters, causing certain character combinations in a text string to be stored improperly resulting in the password desired != the password being saved. This is happening in both master and develop branches latest release.
**This DOES affect Radarr v3 as well:** [view issue here](https://github.com/Radarr/Radarr/issues/5871)

**To Reproduce**
1. Go to page: http://localhost:7878/settings/general
2. Fields affected (so far): Basic Auth Password
3. Set User Password field in Basic Auth settings to the text Pa$$%20Word, save changes
4. _The certificate issue in the Radarr v3 issue is not applicable here as they changed the way certificates work and it requires a thumbprint instead **(MUCH BETTER)**_
6. Open sonarr.db > Navigate to 'Users' table > Notice 'Password' column is encrypted password
7. Calculate SHA256 hash for Pa$$%20Word. Notice it does not match the Password column contents.
8. Calculate SHA256 hash for Pa$$+Word. Notice it matches the Password column contents.
9. Caveat is that you can manually modify the database value to the proper text strings and they WILL work. So deducing it's the web interface field/processing behavior that's awry.

**Expected behavior**
Configuring Basic Authentication passwords properly in the General Settings page.
Having expected password written to sonnar.db.

**Platform Information (please complete the following information):**
OS: Windows 10 Pro 20H2
Docker: No
Mono or .NET Version (System -> Status): Yes (4.8.0)
Browser and Version (Only needed for UI issues): Chrome 88.0.4324.146 (Official Build) (x86_64)
Sonarr Version: 3.0.4.1100
Sonarr Branch: phantom-develop

**Trace Logs**
Not providing, I already remedied these issues manually, not going to screw it all up again.

**Comment by markus101** [comment]
Please update this issue to follow the template.

**Comment by bakerboy448** [comment]
and also edit for sonarr specific details; radarr is a fork of sonarr, they're not exactly the same

**Comment by markus101** [comment]
Turns out everything was being submitted to the UI via forms instead of JSON, fixed for everything now.
