### ISSUE TITLE
change label in downloader if import not necessary/requirements not met

### ISSUE THREAD

**Issue by jamiew0w** [Sonarr/Sonarr#4310]
**Describe the problem**
In the downloader options, sonarr has this awesome feature - 'post import category'. Sometimes sonarr downloads 720p + 1080p at the same time, sonarr will correctly import the 1080p but it leaves the 720p in the Activity Queue. 

It would be awesome if we could automatically flag these files to also be moved to the 'post import category' if they meet criteria. 

For example, if the file isn't an improvement on the current version it gets moved to the 'post import category'.
But if the import fails for any _NORMAL_ issue, it doesn't auto change label. This is to avoid imports failing and skipping import due to disk space, file permissions etc.

**Describe any solutions you think might work**
Not really sure how it'd be implemented tbh.

**Additional context**
I think this feature is a bit advanced and would be of low priority, but it would be pretty neat.

**Comment by bakerboy448** [comment]
Delay Profiles removes a need for this

**Comment by markus101** [comment]
No plans to support this behaviour.
