### ISSUE TITLE
Unable to restore from backup 

### ISSUE THREAD

**Issue by Trapperjohn61** [Sonarr/Sonarr#4314]
Unable to restore from different versions of sonarr backups.
I am using docker on synology.
I update weekly never had a problem.
Trouble started this week.

Using sonarr  3.0.4.1116-ls54 by linuxserver.io
Mono Version
5.20.1.34

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.
