### ISSUE TITLE
Able to delete a root folder despite import lists using the root folder

### ISSUE THREAD

**Issue by MrAnanas** [Sonarr/Sonarr#4315]
**Describe the bug**

if you make a new root folder (d:) and delete another root folder (c:) which you do not use anymore, then import lists continue to use the old "c:" folder despite showing the new "d:" folder in the lists setup form.... to avoid this you need to have two root folders and then select the other one and then back to the one you want to use.... I don't know why this is how it is but I checked the database and made sure this is the problem... Just wanted to let you know in case you want to do something about it... (I was getting movies added with "Root folder missing" errors)

**To Reproduce**

1. The root folder should not be deleted if assigned to anything!

**Screenshots**

**Platform Information (please complete the following information):**
 - OS:  unRaid 6.9.RC1
 - Docker:  Yes
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status):  .NET 5.0.2
 - Browser and Version (Only needed for UI issues):  Chrome
 - Sonarr Version:  3.0.4.1117
 - Sonarr Branch:  nighly

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

Xref:https://github.com/Radarr/Radarr/issues/5904

**Comment by markus101** [comment]
Import lists store the path, just like a series has a path, there is no reference to the root folder once the list is created. When editing the list the UI shows the first path if the saved path isn't present, which is probably why you didn't see the issue before looking in the DB.

> To Reproduce
> The root folder should not be deleted if assigned to anything!

This isn't how to reproduce, but given there is no link between an import list and a root folder, deletion will not be prevented.

> .net Framework (Windows) or mono (macOS/Linux) (System -> Status): .NET 5.0.2

Under docker Sonarr does not use .net

> Sonarr Branch: nighly

Sonarr does not have a nighly or "nightly" branch.
