### ISSUE TITLE
Health status labels display both warning and error states

### ISSUE THREAD

**Issue by the0neWhoKnocks** [Sonarr/Sonarr#4319]
**Is your feature request related to a problem? Please describe.**

If a User wants to get a quick understanding of any possible issues with their setup, they can look at the System section and see how many warnings/errors are currently present.

Currently, if a User has a mixture of warnings and errors, they appear to be rolled up into one error status which is confusing and makes the User think that there are more errors than there are.

![sonarr-status-issue-ex](https://user-images.githubusercontent.com/344140/107396980-1ccfc200-6ab3-11eb-8d8e-c6950e62ec01.png)

![sonarr-status-issue](https://user-images.githubusercontent.com/344140/107396647-cfebeb80-6ab2-11eb-9900-c179b6d3b153.png)

---

**Describe the solution you'd like**

Below is an example image with the proposed solution utilizing markup and classes that are already present in your code.
- Instead of rolling up all issues into one error state, display a separate warning and error status, at the `System` and `System -> Status` levels.
- Change the text color in the status items for contrast (since white on yellow isn't great for visually impaired people).

![sonarr-status-fix](https://user-images.githubusercontent.com/344140/107397902-f199a280-6ab3-11eb-8432-b12268caff13.png)

Clarification for the above screenshot -  the `color` should be set in the `danger` and `warning` label classes, not the root `label` class. Took the screenshot while I was trying different things, and should've cleaned that up.

**Comment by fryfrog** [comment]
If you do this for System -> Status, you also have to do it for Activity -> Queue. And sadly, the queue has 3-4 different states.

**Comment by the0neWhoKnocks** [comment]
> If you do this for System -> Status, you also have to do it for Activity -> Queue. And sadly, the queue has 3-4 different states.

@fryfrog I'm not certain of Sonarr's internals, but I would imagine that health status' and queue status' would be separate pieces of logic, and separate tickets.

**Comment by markus101** [comment]
Fry's comment is after we'd been discussing it.

It's the same logic, using the same components. We wouldn't change one and not the other, though we're leaning towards not changing it.

**Comment by the0neWhoKnocks** [comment]
Apologies, was replying on a tablet and didn't know fryfrog's relationship to the repo. How many status types need to be accounted for? I have another idea, but would need to know the full technical constraints.

**Comment by fryfrog** [comment]
Sorry, to be clear I like your idea. I was just saying if you do it in the one place that has numbers that change colors, it makes sense to do it in the other place. The problem I see is that when you do that, the UI looks very cluttered.

**Comment by the0neWhoKnocks** [comment]
Created a mockup on CodePen https://codepen.io/theOneWhoKnocks/pen/VwmKaPe. You can use the inputs at the top to increase/decrease the number of statuses for info, warning, and errors.

If it's still too bloated, maybe just switch the color of the rolled up statuses from red to blue?

**Comment by markus101** [comment]
There are two things the badge is communicating, the first being the number of items, the second being the worst state in that list of items, it’s not the number of items in the worst state.

I’ve discussed this with a number of people today and at least for the time being we have no plans to change how it’s displayed.
