### ISSUE TITLE
Add ability to rename file/folder with "Indexer name"

### ISSUE THREAD

**Issue by JhonnyMnemonic320** [Sonarr/Sonarr#4322]
**Is your feature request related to a problem? Please describe.**
I need a way to track from wich indexer the relases are downloaded.
I know that I can find this information clicking on the "i" of the snatched relase on the history tab of each series page, but is very unpractical when mass editing a lot of series.

**Describe the solution you'd like**
add the ability in "Media managment" to add the indexer name to the file (or folder) when renamed.
Using somenthing like this: {Movie Title} ({Release Year}) {indexer name}
In this way I can filter the series by Indexer name with a simple custom filter in the Series page.

Thanks

**Comment by markus101** [comment]
Adding the indexer to file/folder names is not something we have plans to support. You could use the API to get this information via a couple requests:

1. Get the episodes for the series: `/api/v3/episode?seriesId={id}`
2. Get the history for either the series or the episode: `/api/v3/history/series?seriesId={id}` or `/api/v3/history?episodeId={id}` respectively
3. Once you have the episode you can use the `episodeFileId` to get the history event (data.fileId), then use the `downloadId` to get the related grab event and the indexer.

**Comment by JhonnyMnemonic320** [comment]
I have zero programming skills so I don't know how to use your suggestion. However thanks for the answer.

**Describe alternatives you've considered**
as alternative is possible to make available a custom filter in the Series page that filter by "Indexer name"?

**Comment by bakerboy448** [comment]
There’s no relation between an indexer and an series.

markus can correct me, but I’m going to say no plans for that
