### ISSUE TITLE
Ensure Consistency of SSL option across download Clients

### ISSUE THREAD

**Issue by Paulus88** [Sonarr/Sonarr#4323]
I have all my web solutions behind a webproxy and this has been setup to only allow HTTPS/443 traffic.
It would be awsome if SSL will be added in Sonarr for all Download Clients.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

Closing- template not followed

and SSL already exists for download clients

**Comment by Paulus88** [comment]
An example, this client has no SSL option:
![image](https://user-images.githubusercontent.com/25663775/107853364-c990a300-6e15-11eb-9757-608cb5cf1dca.png)

It exists for some download clients, not all.

**Comment by bakerboy448** [comment]
Just looked:

only Utorrent is missing an SSL option

however, SSL is also not consistent across download down clients:
- some have it as advanced
- Some have help test, most don’t

**Comment by fryfrog** [comment]
@Paulus88: A *support* suggestion for you, running all this software through your reverse proxy is adding a single point of failure w/o benefit if your services are all on the same host or trusted lan. If they're crossing the wide open internet or an untrusted lan, it does make sense though.

**Comment by Paulus88** [comment]
> @Paulus88: A _support_ suggestion for you, running all this software through your reverse proxy is adding a single point of failure w/o benefit if your services are all on the same host or trusted lan. If they're crossing the wide open internet or an untrusted lan, it does make sense though.

Hi @fryfrog, thanks for the reply, I know this already but its not a corporate solution, its just a hobby solution that I like to keep secure from LAN and WAN. All environments also have their own host that automatically keep them selves up to date and clean with cronjobs/scheduled tasks and the entrance to these hosts is the webproxy very tightly configured with the firewalls on the hosts. This also allows me to turn an envirement off and replace it if ever needed without effecting other solutions.
Even if the webproxy fails it will have very little impact as it is only used to administrator applications through the browser and as you mentioned I also like to access it from other locations so webproxy seems the safest solution.

**Comment by fryfrog** [comment]
I'm absolutely not suggesting you stop using a reverse proxy, they're the bee's knees and I <3 it too.

I'm only suggesting you don't need to route your sonarr/radarr -> download client connection through it. Don't route your sonarr/radarr -> jackett/nzbhydra2 connection though it. That way reverse proxy issues don't prevent sonarr/radarr from queuing and processing downloads. And if you jackett, it can still receive results.

**Comment by Paulus88** [comment]
@fryfrog i know what your suggesting, I have my sonarr setup to only allow outgoing port 443 on LAN network. Everything is tightly configured haha
As I noticed in SickBeard you can connect all the download clients through HTTPS so it would be awsome if Sonarr could do the same.

**Comment by fryfrog** [comment]
Yeah, I think we all agree the SSL option should be cleaned up across all the download clients. :)

Glad you've thought about your setup, that's the important part.
