### ISSUE TITLE
Delete Lesser Quality Download When Requirements Already Met or Not An Upgrade.

### ISSUE THREAD

**Issue by drowse7en** [Sonarr/Sonarr#4324]
**Is your feature request related to a problem? Please describe.**
Sonarr does not delete content from downloader when an episode's requirements (quality, size, etc) have already been met.

**Describe the solution you'd like**
Sonarr should delete downloads from downloader when an episode's requirements (quality, size, etc) have already been met.

**Describe alternatives you've considered**
For now, this must be done manually by removing downloaded item from Sonarr's queue.

**Additional context**
Sometimes, Sonarr will request multiple downloads for new releases made in quick succession.  In this case, if the lesser quality download completes before the higher quality download, then Sonarr will upgrade the lesser quality file.  However, it does not do the reverse by relinquishing the lesser quality download.  Or, content may have already been obtained through alternative source while waiting for download completion (such as PVR or eMule) so that lesser quality download can be deleted, but is not.

![Sonarr - Not An Upgrade To Existing File](https://user-images.githubusercontent.com/4270365/107862375-8f75d000-6e1a-11eb-862d-b55c5fa2e1cd.png)

**Comment by markus101** [comment]
With torrents and hit n runs this is very complicated. We have no short term plans for doing it at this time.

**Comment by drowse7en** [comment]
But in this case, the downloaded file is already completed and waiting for import.

**Comment by bakerboy448** [comment]
Hit and run comments still apply
