### ISSUE TITLE
Ability to edit each and every Scheduled Tasks Interval

### ISSUE THREAD

**Issue by Paul5656** [Sonarr/Sonarr#4325]
**Is your feature request related to a problem? Please describe.**
The title basically covers it all. I'd like more control over how I manage my Sonarr instance and the timings just don't work for me.

**Describe the solution you'd like**
Ability to edit **_each and every_** Scheduled Tasks Interval

**Describe alternatives you've considered**
None. No reason to force everyone to use the same intervals.

**Comment by markus101** [comment]
We do not have plans to do this.

**Comment by Paul5656** [comment]
Lol I knew you would close this asap. Do u guys really need to manage everybody’s sonarr down to a t?

**Comment by Taloth** [comment]
You've requested a particular solution, you're not explaining the problem. What timings don't work for you and why? Explain both the problem and the usecase in which it occurs. Hop on discord or the forums and elaborate.
We don't make stuff configurable just for the sake of having it configurable, it'd only lead to accidentally misconfigured systems that are hard to diagnose. A significant portion of our time is spent on support, we have no desire to make that worse.

**Comment by Paul5656** [comment]
…and thats why alot of apps have advanced settings for the advanced users. No need to baby everybody around. Nobody is paying for the app so demanding customer service from people who’ve broken their app is another issue. Don’t mean to sound rude and thanks @Taloth btw for explaining the reason which could have been passed along before closing. Now the problem with dumbing it down and locking down the app is that you have folks wasting their time putting up so many suggestions for basic features that will never be implemented. Lots of people have different kinds of setups and forcing everyone to use the same settings is just insane imo. It seems mark has already made up his mind hence no need to continuing pleading the case. Thanks for taking your time tho.

**Comment by Taloth** [comment]
I didn't ask you for details to plead this case. I asked it because you have an underlying problem that you're attempting to address and I wanted to help you with that. After all, you didn't just ask for it to be configurable just for kicks, right? This is commonly known as the xy-problem.

In general we only get questions about the Series Refresh task. There's two known reasons why people wish to adjust them: 
1. Performance: Their scan takes > 12h, this is 100% of the time an underlying performance issue. For example a known issue is when users have a cloud setup and have metadata file generation enabled. Or some other local issue. We have users with 5000+ series for which the scan takes an hour or less. So if you're running into it, then either we need to adjust the configuration a bit, or there's a performance issue we're unaware of.
2. Disk spinups during the night when the PC sits next to someone's bed. Adjusting intervals won't _really_ fix that. And how to address that depends on the exact usecase. There's a potential new feature that can help, but it's not on the backlog.

I'm fine with letting this be. I just wanted you to know that if you want assistance, please contact us on Discord or the forums.

**Comment by Paul5656** [comment]
It’s all good. Leave it be. I just wished you guys opened your eyes abit and see that a major chunk of the suggestions are indirectly about opening up the app some more. But eh, those settings work for you guys, they’ll work for everyones system. G’day sir.

**Comment by bakerboy448** [comment]
@Paul5656 no need to be a dick about it (that’s how your replies come across; whether that’s intended or not, I don’t know)

But no we don’t make changes that are illogical and would create a significant support burden.  

taloth already explained out the why they’re not user configurable.

And regardless you never even bothered to explain your problem / what problem this solved, so you’d request would have been closed any as it did not follow the template that you butchered. Adding more customization for the sake of having more customization isn’t happening unless there is a rationale reason behind it.

being able to arbitrarily edit tasks scheduling is a support nightmare; if it’s such a huge issue for you then feel free to fork and build your own (note will be completely unsupported and you’d be on your own for any and all issues)  you can also edit the DB to suit your needs but again that is also largely unsupported and you’re on your own for any self inflicted problems...it’d also need to be redone after all updates I believe

For further discussion on this use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr).

Preferably discord if not the forums

if folks don’t want to waste their time (2 minutes...maybe to create a GHI) submitting requests that are instantly closed then they can discuss their idea on one of the various channels first.  That typically prevents an X/Y problem and results in better thought out feature requests

**Comment by Paul5656** [comment]
Wow real professional now your response is the one sounding like a dick @bakerboy448. 
How is it illogical to want more control over how I use my app and at what intervals set tasks run? I’ll reiterate what I said incase you are slow, dyslexic or something. Expecting everyone to use the same settings as you like them on your system, on their system, is plain silly. Basically what I got from this is the suggestion has been closed arbitrarily because people are too dumb, and if we let them change these settings they are gonna mess up their apps and we (devs) are the ones forced to help them fix afterwards. Not because of any proper reason. I already knew this suggestion was gonna be closed way before I posted it because I know you guys want everybody running it the way you guys want it, nothing else, because you guys run it best or are afraid of giving up some control to the end user. Why was the suggestion closed so fast? Was it a dupe? Why not let the community vote on it? I’m pretty sure people would vote for more control of their app thats why it was shut down immediately again because mark doesn’t want to give up that control. Oh and u can pound sand with your template obsession. The suggestion is self explanatory, no need to be verbose about it, oh unless you’re slow or something then you can find me on discord and I can break it down in a nice simple template for u. I already ended this issue not sure where u waltzed in from so… bye Felicia.

**Comment by markus101** [comment]
Was it a dupe?

Yes.
https://github.com/Sonarr/Sonarr/issues/2916
https://github.com/Sonarr/Sonarr/issues/1708
https://github.com/Sonarr/Sonarr/issues/963
