### ISSUE TITLE
Sonarr 3.0.4.1128 requires libc6 (>= 2.31) but 2.28-10 is to be installed (Debian 10.8)

### ISSUE THREAD

**Issue by dcampillo** [Sonarr/Sonarr#4332]
The last build 3.0.4.1128, requires libc6 >= 2.31, but debian Stable depends on 2.28

**Expected behavior**

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Debian 10.8
 - Docker: No
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): Mono JIT compiler version 5.18.0.240
 - Browser and Version (Only needed for UI issues): 
 - Sonarr Version: 3.0.4.1126
 - Sonarr Branch: phantom-develop

**Trace Logs**
sudo apt install sonarr
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sonarr : Depends: libc6 (>= 2.31) but 2.28-10 is to be installed or
                   libc6.1 (>= 2.31) but it is not installable or
                   libc0.1 (>= 2.31) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by Taloth** [comment]
It was reported yesterday on discord too. Took a bit to track down where the version change came from. 
Should be fixed in the 3.0.4.1129 package that's been published a minute ago, lemme know if it's still a problem.

**Comment by dcampillo** [comment]
Hi,

It is fixed with the last release 3.0.4.1129.

Thanks,

David
