### ISSUE TITLE
Request more season from Overseer

### ISSUE THREAD

**Issue by csihama** [Sonarr/Sonarr#4333]
Hello Everybody!

I use Overseer for Plex with Sonarr(index: Jackett) and qBittorrent

Everything works fine, except "request more season" from Overseer.

Example:
If I requested a tv show, season 01 only, it downloaded fine.
After this if I request more season for this tv show, there is an error in Sonarr: 
           Invalid request Validation failed: 
              -- This series has already been added

If it is an Overseer error/bug, then I will post there.

Thanks for the help :)

 - OS: Ubuntu 20.04
 - Install via: Snap
 - mono (Linux): 6.12.0.107
 - Sonarr Version: 2.0.0.5344
 - Sonarr Branch: master

**Comment by bakerboy448** [comment]
Overseer problem; not a Sonarr issue.

It appears Overseer is attempting to add the show twice when adding the season rather than changing what is monitored
