### ISSUE TITLE
No SSL option for an Emby connection

### ISSUE THREAD

**Issue by madcowGit** [Sonarr/Sonarr#4334]
**Describe the problem**
No SSL option for Emby notifications in Settings/connect
- i have tried removing and adding the Emby connection
- i have updated to the latest version of sonarr (2.0.0.5344) (linuxserver sonarr docker image)

**Describe the solution you'd like**
A 'Use SSL' checkbox in the UI when adding the Emby connection

**Describe alternatives you've considered**
Issue #2923 was fixed, but I still don't see a SSL button.

**Comment by Qstick** [comment]
Already in v3 I believe

**Comment by markus101** [comment]
It is.
![image](https://user-images.githubusercontent.com/413544/108275615-75decc00-712b-11eb-8d02-509136f0b9f8.png)
