### ISSUE TITLE
Detect SABNZBd Paused Status and Delay Retry

### ISSUE THREAD

**Issue by Casper042** [Sonarr/Sonarr#4335]
**Is your feature request related to a problem? Please describe.**
I run SAB Paused during "work hours" so as to not mess with my job or my kids online schooling.
I noticed the other day when a friend put in a request for Season X of Show Y, that the Indexer found a Full Season Download option and it added that.  Great!
However a few minutes later, Sonarr detected there had been no movement on that download, and to it seems to have gone off to look for alternates and then added 20+ individual downloads for SXXE01, E02, E03, etc.
So now those are all paused too.
This causes duplicate download requests to all be queued up in SAB waiting for my 6pm Auto Start to kick in.

**Describe the solution you'd like**
I'd like Sonarr to simply detect if SAB is in a Paused state, and delay any further searching for items in the queue until such time as it detects SAB is no longer Paused.
This way the initial item found is at least given a chance to download before it runs off to find alternates.

**Describe alternatives you've considered**
None, just let it ride as my primary providers are unlimited DL.
Just concerned about Block accounts I use for backup being hammered for no gain.

**Additional context**
None, but if needed I can probably simulate the behavior and grab logs if needed.

Thanks

**Comment by bakerboy448** [comment]
Sonarr only blacklists and continues searching if the download client indicates the download is failed or cannot be completed.

It won't search just because a download is stalled or paused.

**Comment by Casper042** [comment]
I'll go try this again and see if I can duplicate it.

**Comment by markus101** [comment]
Upgrades to quality, language, preferred words would all trigger another grab, but that's going to happen regardless of the downloads being paused, you can use delay profiles to limit the number of "dupes" in that case.

**Comment by Casper042** [comment]
Same friend has 2 more seasons currently paused.
Sure enough today it's not doing it.
Apologies, should have done more field testing.
