### ISSUE TITLE
Network Filter In Mass Editor

### ISSUE THREAD

**Issue by gtxr23** [Sonarr/Sonarr#4339]
**Is your feature request related to a problem? Please describe.**
i would like an option to bulk edit tv shows by "Network" if possible, thank you 

**Describe the solution you'd like**
 The option to mass edit series by sorting/filtering by "Network" eg Netflix/Hulu etc, Radarr does this by adding "studio" as a filter in mass editor, sonarr has the "network" filter already but is only available in the Series Part of the site and not in the mass editor section

**Describe alternatives you've considered**
sorting the shows manually one by one :( 

**Additional context**
Here is a screenshot of the feature im talking about but in radarr - https://prnt.sc/103dygj 
as i mentioned sonarr only has the network filter in the series section as seen here - https://prnt.sc/103dzmg
so would really like a network filter in the mass editor section of sonarr added here if possible - https://prnt.sc/103e0tb

Thank you

**Comment by markus101** [comment]
It's already there, if you don't see it update.
