### ISSUE TITLE
Sonarr Never Automatically Imports Files

### ISSUE THREAD

**Issue by corylowry12** [Sonarr/Sonarr#4340]
**Describe the bug**
Sonarr will automatically grab a monitored tv show, and it will import it into qbittorrent and when it finishes, it just stays in qbittorrent and never imports. 

**To Reproduce**
1. Go to TV Show
2. Click on Episode
3. Click download button
4. Let it download
5. Then it wont import

**Expected behavior**

I expect it to import properly. 

**Platform Information (please complete the following information):**
 - OS: Windows 10 2004
 - Docker: No
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): .net 4.8.0 
 - Browser and Version (Only needed for UI issues): Brave 1.20.108
 - Sonarr Version: Sonarr 3.0.4.1131
 - Sonarr Branch: phantom-develop

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
https://pastebin.com/pumgW4XQ

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
