### ISSUE TITLE
Redact/Edit announce url/passkey in json response of qbittorrent before passing into Sonarr logging system

### ISSUE THREAD

**Issue by delize** [Sonarr/Sonarr#4341]
**Describe the bug**
The json that qbittorrent passes back to Sonarr is not redacted/sanitized, and displays  the announce key/passkey in the trace log. 

**To Reproduce**
1. Go to Settings > General 
2. Enable `Trace Logging`
3. Send a torrent to qbittorrent by automatic searching/manual searching
4. JSON response from qbittorrent outputs all json data to trace log file bia sonarr
5. Announce URLs are NOT stripped from Sonarr logging system

**Expected behavior**
Announce URLs should DEFINITELY be stripped from. In the JSON response, these are the following fields:
```
"magnet_uri":  <data here>
"tracker": <data here>
```

**Screenshots**
Won't post screenshot - but support channel has proof.

**Platform Information (please complete the following information):**
Version
3.0.4.1130
Package Version
3.0.4.1130-ls63 by linuxserver.io
Mono Version
5.20.1.34
AppData directory
/config
Startup directory
/app/sonarr/bin
Mode
Console
Uptime

**Trace Logs**
Will not provide trace logs due to announce url/pass key not being redacted in certain situations.
```
{"added_on":1614036190,"amount_left":0,"auto_tmm":true,"availability":-1,"category":"tv/sonarr-qb","completed":797817900,"completion_on":1614036256,"content_path":"/pool/downloads/complete/tv/sonarr-qb/Conan.2021.01.18.Bob.Newhart.1080p.WEB.h264-BAE.mkv","dl_limit":-1,"dlspeed":263,"downloaded":808852634,"downloaded_session":808852634,"eta":8640000,"f_l_piece_prio":false,"force_start":false,"hash":"04513a85a6dd18975d999935b2e36a2e51381ede","last_activity":1614036256,"magnet_uri":"magnet:?xt=urn:btih&dn=Conan.2021.01.18.Bob.Newhart.1080p.WEB.h264-BAE.mkv&tr=https%3a%2f%2flandof.tv%%2f<ANNOUNCEKEYHERE>","max_ratio":-1,"max_seeding_time":525599,"name":"Conan.2021.01.18.Bob.Newhart.1080p.WEB.h264-BAE.mkv","num_complete":49,"num_incomplete":10,"num_leechs":0,"num_seeds":0,"priority":0,"progress":1,"ratio":0,"ratio_limit":-2,"save_path":"/pool/downloads/complete/tv/sonarr-qb","seeding_time_limit":-2,"seen_complete":1614036256,"seq_dl":false,"size":797817900,"state":"stalledUP","super_seeding":false,"tags":"","time_active":110,"total_size":797817900,"tracker":"https://landof.tv/<ANNOUNCEKEYHERE>/announce","trackers_count":1,"up_limit":-1,"uploaded":0,"uploaded_session":0,"upspeed":0},

```
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by bakerboy448** [comment]
comments from discord:

Starting Regex `(?<="tracker":)"(?<secret>[^"]+?)"` and `(?<="magnet_uri":)"(?<secret>[^"]+?)"`

Per Taloth we need to mask out the key itself and not the URL, so the above will go too far.

Need to verify or determine if the keys are in a consistent format across trackers
