### ISSUE TITLE
BroadcastheNet on V3 doesn't return season pack results

### ISSUE THREAD

**Issue by shmizan** [Sonarr/Sonarr#4343]
**Describe the bug**
I have two Sonarr installations on two different PCs, with BroadcastheNet indexer.
one has V2, and the other V3.
on the V2 one, I can go to an episode and manual search it to find seasons pack it contains.
on the V3 one, when I try to do interactive search on the same episode, it doesn't return any season packs.
the series is set to "Standard" on both installations.
it seems from the logs, that V3 is missing a query for "season only" that appears in V2:
`21-2-24 11:06:07.2|Debug|BroadcastheNet|Downloading Feed http://api.broadcasthe.net/: getTorrents("(removed)", {"Category":"Season","Name":"Season 2%","Tvdb":"347507"}, 100, 0)`
or am I missing some needed configuration in V3?

**To Reproduce**
go to a series,  click on an episode from any season that's not S01E01, and do an interactive search.

**Expected behavior**
the seasons pack for this episode are shown.

**Actual behavior**
"no results found"

**Platform Information (please complete the following information):**
 - OS: V3 - Microsoft Windows 10 Pro 10.0.19042 Build 19042
 - OS: V2 -  Microsoft Windows 8.1 Pro 6.3.9600 Build 9600
 - Docker: No
 - .net Framework 4.8.04084 on V3, 4.8.03761 on V2
 - Browser and Version Chrome/88.0.4324.182
 - Sonarr Version: 2.0.0.5344 / 3.0.4.1131
 - Sonarr Branch: develop / phantom-develop

**Trace Logs**
V3 logs: https://pastebin.com/w3Rd0W4t
V2 logs: https://pastebin.com/K2VbrkX4

**Comment by bakerboy448** [comment]
Markus can reopen if needed, but it appears this is intended behavior

Fixed: BTN will no longer include season packs for individual episode searches (https://github.com/Sonarr/Sonarr/commit/3b042707f51216f06487bc268ee2f48950250413)

**Comment by Taloth** [comment]
V3 has interactive season search. So the workaround for btn was removed.

**Comment by shmizan** [comment]
damn, I thought it went over all of the options, that one was a tough one to spot! had to google image search to find it (https://nzb360.com/forums/viewtopic.php?t=1342).
I thought that "interactive search for all episodes in this season" means it will try to search each episode and fail like it failed for a single one I tried.

anyway, thanks.

**Comment by whoisdecoy** [comment]
I had the same issue, doing it the old V2 way. The button is here BTW:
<img width="601" alt="Screen Shot 2021-03-11 at 11 12 32 AM" src="https://user-images.githubusercontent.com/40132135/110834560-ea081d80-825a-11eb-8786-930e4ad70201.png">
