### ISSUE TITLE
Backup import does not seem to work correctly

### ISSUE THREAD

**Issue by TheDutchMC** [Sonarr/Sonarr#4345]
**Describe the bug**

After creating a backup, and then trying to restore that backup, Sonarr will fail immediately with 'Error restoring backup'. No entries are added to log

**To Reproduce**

1. Export backup
2. Restore the backup on a different sonarr instance
3. Backup restores successfully

**Screenshots**

![image](https://user-images.githubusercontent.com/28569170/109225560-b68ab500-77bd-11eb-826c-fa14bced374e.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Docker: Yes, in Kubernetes
 - Sonarr Version: 3.0.4.1131
 - Sonarr Branch: Preview

**Trace Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6045981/sonarr.trace.txt)
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/6045982/sonarr.debug.txt)

**Comment by bakerboy448** [comment]
Browser console logs?

**Comment by markus101** [comment]
```
21-2-25 22:02:20.4|Trace|Http|Res: 111 [GET] /api/v3/system/backup: 200.OK (2 ms)
21-2-25 22:02:20.4|Debug|Api|[GET] /api/v3/system/backup: 200.OK (2 ms)
21-2-25 22:02:27.4|Trace|Http|Req: 112 [GET] /api/v3/log/file (from 192.168.1.203 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.63)
21-2-25 22:02:27.4|Trace|Http|Res: 112 [GET] /api/v3/log/file: 200.OK (2 ms)
21-2-25 22:02:27.4|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
```

The restore upload request never made it to Sonarr's API, like it should have:

Example of one that did:
```
21-2-25 14:06:22.5|Trace|Http|Req: 5845 [POST] /api/v3/system/backup/restore/upload (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36)
```

Are you going through a reverse proxy?

In addition to console logs, network logs from Chrome will be useful.

**Comment by TheDutchMC** [comment]
Good one. This responds with a 513, fixed this (NGINX configuration issue).

In the next step, the 'Restart' step, it's doing some funny business too. A lot of 502 and 401's in the browser console. See the attached screenshot and log export. 
[sonarr.k8s.thedutchmc.nl-1614291124049.log](https://github.com/Sonarr/Sonarr/files/6046018/sonarr.k8s.thedutchmc.nl-1614291124049.log)
![image](https://user-images.githubusercontent.com/28569170/109226401-fdc57580-77be-11eb-91c3-bfd8e08e3143.png)

**Comment by TheDutchMC** [comment]
After a lot of those errors, it does restore in the end. Backup seems to work fine then, but there's still something fishy going on
