### ISSUE TITLE
Interactive Search - Preferred words not found when release title is shortened.

### ISSUE THREAD

**Issue by MyParameter** [Sonarr/Sonarr#4347]
**Describe the bug**
In interactive search, preferred words are not found when the title is shortened if the preferred word is fully or partially in the removed part. Preferred words only appears to search the exact text as shown in the release title column, instead of the full title.

**To Reproduce**

1. Go to Interactive Search
2. Have a preferred word in the part of the title that is removed to shorten the title.

**Expected behaviour**
Preferred words should be found when the release title is shortened even if the preferred word is not displayed in the title column.

**Screenshots**
Preferred term 'joy', is not picked up in the first release as indicated by the score, but is in the second.  
![Screenshot-2021-02-27](https://user-images.githubusercontent.com/61542327/109354854-88e36000-78d2-11eb-8704-b6dd8a79c612.png)   
(background is altered to dark-mode, and does not affect behaviour.)

**Platform Information :**
 - OS: Windows 10
 - Docker: No
 - .net Framework (Windows): 4.8.0
 - Sonarr Version: 3.0.4.1132
 - Sonarr Branch: phantom-develop

**Comment by bakerboy448** [comment]
Closing:
- template not followed, no logs
- Sonarr does not truncate the release, that is your indexer
- Preferred words are based on the release name for searching
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
