### ISSUE TITLE
Failed to load UI settings from API (Safari Desktop only)

### ISSUE THREAD

**Issue by slappula** [Sonarr/Sonarr#4350]
After version 3.0.4.1131, the UI will no longer load in Safari on my Mac. It gives this message (after spinning for a few seconds):

Failed to load UI settings from API
Version 3.0.4.1131

It works fine in Firefox on my Mac or in Safari on my iPhone.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
