### ISSUE TITLE
Consistent freeze about 2 hours after Sonarr is run in Docker container (occurs in both LSIO and Hotio containers)

### ISSUE THREAD

**Issue by bi0shacker001** [Sonarr/Sonarr#4354]
**Describe the bug**

So, the sonarr container starts fine, runs mostly normally (Not able to view the "activity" queue, but I assume that's unrelated), and is perfectly performant. It works that way for about two hours, after which point it just completely stops responding. I can only reboot the host machine to restart it, and other containers are experiencing no issues. Container doesn't respond to 'docker kill', 'docker container restart', or 'docker container stop' commands, and I can't even forcibly restart the docker service once this starts happening. It even appears that logs stop being updated after this point (portainer doesn't show any updates)
**To Reproduce**

The container should continue being accessible
**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Archlinux
 - Docker: Yes
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): Mono 6.10.0.104
 - Browser and Version (Only needed for UI issues): Firefox, Chrome, and various mobile browsers
 - Sonarr Version: 3.0.4.1132 (package version nightly-c790731 currently installed, Linuxserver/sonarr:preview also tested)
 - Sonarr Branch: phantom-develop

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again.

No logs that appear relevant, attaching log file. Potentially risky directory names redacted. Issue had been occuring for 6 minutes prior to log pull, no log updates for 9 minutes.
EDIT: Didn't realize that trace log output wasn't mirror in the running log. Replaced log file with redacted trace file
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6073943/sonarr.trace.txt)

**Comment by bi0shacker001** [comment]
Well, I just looked at that log, and it looks like my container config got changed at some point. I'm going to completely nuke my sonarr setup and see if the issue still occurs.
Will reopen and upload new logs if the issue recurs

**Comment by bi0shacker001** [comment]
Issue still occurs with fresh configuration, manually readded all content, downloaders, and indexers. 
Trace output ended prior to standard log output. Final log entry from over an hour ago, container has been running this entire time.
Uploading trace and standard log
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6078548/sonarr.trace.txt)
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/6078549/sonarr.txt)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

Sounds more likely a docker issue or host issue than anything.  If this was a sonarr bug there would be a lot more reported issues of this occuring.
