### ISSUE TITLE
Number-words in folder names misinterpreted as season numbers

### ISSUE THREAD

**Issue by UneFaguette** [Sonarr/Sonarr#4355]
Sonarr appears to be recognising number words like "Zero" (vs. "0") in folder names as the season number, despite the season number (eg. "S2E21") appearing later on in the folder name. This can occur when the show title itself contains a number word, eg. "Re-Zero".

In at least some instances, where Sonarr correctly determines the season and episode numbers from the video file itself (eg. "S2E21"), but identifies a different season number from the parent folder's name (eg. "S0" from "Zero" in the show title), Sonarr will additionally reject the import of the file, with an error like "Season number 0 was unexpected considering the folder name [...]".

I have tested this with the Manual Import facility, however I suspect this _may_ also be stopping automatically downloaded episodes with similar naming from getting automatically imported as well.

**Steps to reproduce the behaviour**
1. Obtain an episode from a show where the show title contains a number word, like "Re:ZERO". This episode should be in a folder named something like "[EMBER] Re-Zero kara Hajimeru Isekai Seikatsu S2E21 [Episode-46] [1080p] [HEVC WEBRip] (Re-Zero - Starting Life in Another World)", where the number word and the actual season number (as a numeral) coexist. This folder should then have the video file itself within it, named something like "[EMBER] Re Zero kara Hajimeru Isekai Sei katsu S2 - 21.mkv".
2. In Sonarr, navigate to the Wanted tab, and select "Manual Import"
3. Navigate to the location where the above episode video file and its parent folder are stored on disk
4. Select "Manual Import"
5. You should now see the episode on the import list with the correct show title, season number, and episode number, BUT with a red exclamation mark next to it
6. If you hover over the exclamation mark, you should see a balloon appear with a message like "Import Rejected [...] Season number 0 was unexpected considering the folder name [EMBER] Re-Zero kara Hajimeru Isekai Seikatsu S2E21 [Episode-46] [1080p] [HEVC WEBRip] (Re-Zero - Starting Life in Another World)"
7. In your file browser of choice, remove the number word from the folder name, eg. rename it from "[EMBER] Re-Zero kara Hajimeru [...]" to "[EMBER] Re kara Hajimeru [...]"
8. Reattempt the manual import of this folder again, per steps 3..6
9. You should no longer see a red exclamation mark next to the episode, and thus should be able to import it

**Expected behavior**
Number words (eg. "Zero") in file/folder names should _only_ be interpreted as season/episode numbers as an absolute last resort, if Sonarr cannot locate these in a more standard form, eg. "Season 1", "S1", "S1E1", etc.

**Screenshots**
![2021-03-03 20-00-00 Cropped](https://user-images.githubusercontent.com/79981991/109812800-7ae16680-7c67-11eb-9904-710e243c227c.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu Server 19.10
 - Docker: No
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): Mono 5.18.0.240
 - Browser and Version (Only needed for UI issues): NA
 - Sonarr Version: 2.0.0.5344
 - Sonarr Branch: master

**Trace Logs**
https://pastebin.com/UXzi4Ahk

This does indeed appear to be affecting automatic imports of completed downloads, as well. See the following line in the trace logs:
21-3-3 21:51:14.3|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Season number 0 was unexpected considering the folder name [EMBER] Re-Zero kara Hajimeru Isekai Seikatsu S02E21 [Episode-46] [1080p] [HEVC WEBRip] (Re-Zero - Starting Life in Another World)

**Comment by bakerboy448** [comment]
Sonarr v2 is seeing no further development work.

I don’t believe this issue occurs in v3; if it does please open a new GHI with the appropriate details

**Comment by Taloth** [comment]
'Zero' isn't a problem, it's not parsing that as 0.

It's complaining about a mismatch between info gathered from the folder title and file title. Probably because one uses SxxExx and the other uses anime absolute numbering.

**Comment by UneFaguette** [comment]
@Taloth I don't think that's what's at play here, as per step 7, renaming the folder from "[EMBER] Re-Zero kara Hajimeru [...]" to "[EMBER] Re kara Hajimeru [...]" resulted in Sonarr no longer rejecting it in that manner, although that could also be due to it no longer seeing the folder name as a valid show name.
Either way, neither the folder nor the video file within use "anime absolute numbering", otherwise the episode would be 46.
I'll see what happens once I update to Sonarr v3, which I somehow overlooked (I thought I was up to date).
