### ISSUE TITLE
Activity>Queue>Remove Selected button stopped responding

### ISSUE THREAD

**Issue by mad-tunes** [Sonarr/Sonarr#4362]
Running 3.0.4.1139, with Transmission 3.00 on Windows Server 2019

Over the last few days I've found the Activity>Queue>Remove Selected button has stopped responding as it did/should.
I can tick torrents I'd like to remove, but clicking the button then does nothing. They're not removed and just remain selected.

I notice that if I click one of the cross buttons to the right of an individual torrent, I get the usual Remove window. If I hit the Remove button, the torrent's removed and _then_ I get the Remove window I should have previously seen after clicking Remove Selected.

I find the same using firefox and edge on a couple of different windows machines, and in firefox on android too.
Clearing caches and cookies etc don't seem to make any difference.

I've not made any config changes recently, just left Sonarr alone doing its thing.
I see its updated to 3.0.4.1139 today but it seems the same afterwards.

Anyone else find the same or have any idea whats up please?

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

also template not followed.
