### ISSUE TITLE
Wrong season detected for files in correct season folder

### ISSUE THREAD

**Issue by GodKratos** [Sonarr/Sonarr#4366]
**Describe the bug**

This issue happens with a lot of Anime shows that have season numbered episodes. (It makes no difference if the show is added as anime or standard series type)
I assume it is because the file name does not specifically use SxxExx notation so the episode number is detected only **however** the files are placed in Season folders correctly but are not identified as such.

**To Reproduce**
1. Add show "The Promised Neverland"
2. Add files as below

> The Promised Neverland\Season 1\\[SSA] Yakusoku no Neverland - 01 [720p].mkv
> The Promised Neverland\Season 1\\[SSA] Yakusoku no Neverland - 02 [720p].mkv
> The Promised Neverland\Season 1\\[SSA] Yakusoku no Neverland - 03 [720p].mkv
> The Promised Neverland\Season 1\\[SSA] Yakusoku no Neverland - 04 [720p].mkv
> The Promised Neverland\Season 1\\[SSA] Yakusoku no Neverland - 05 [720p].mkv
> The Promised Neverland\Season 1\\[SSA] Yakusoku no Neverland - 06 [720p].mkv
> The Promised Neverland\Season 1\\[SSA] Yakusoku no Neverland - 07 [720p].mkv
> The Promised Neverland\Season 1\\[SSA] Yakusoku no Neverland - 08 [720p].mkv
> The Promised Neverland\Season 1\\[SSA] Yakusoku no Neverland - 09 [720p].mkv
> The Promised Neverland\Season 1\\[SSA] Yakusoku no Neverland - 10 [720p].mkv
> The Promised Neverland\Season 1\\[SSA] Yakusoku no Neverland - 11 [720p].mkv
> The Promised Neverland\Season 1\\[SSA] Yakusoku no Neverland - 12 [720p].mkv
> The Promised Neverland\Season 2\\[SSA] Yakusoku no Neverland S2 - 01 [720p].mkv
> The Promised Neverland\Season 2\\[SSA] Yakusoku no Neverland S2 - 02 [720p].mkv
> The Promised Neverland\Season 2\\[SSA] Yakusoku no Neverland S2 - 03 [720p].mkv
> The Promised Neverland\Season 2\\[SSA] Yakusoku no Neverland S2 - 04 [720p].mkv
> The Promised Neverland\Season 2\\[SSA] Yakusoku no Neverland S2 - 05 [720p].mkv
> The Promised Neverland\Season 2\\[SSA] Yakusoku no Neverland S2 - 06 [720p].mkv
> The Promised Neverland\Season 2\\[SSA] Yakusoku no Neverland S2 - 07 [720p].mkv
> The Promised Neverland\Season 2\\[SSA] Yakusoku no Neverland S2 - 08 [720p].mkv

3. Import show and scan folder
4. Episodes are only recognised for season 1 (see screenshot below)

**Expected behavior**
Episodes in appropriate season folders should be classified under the correct season

**Screenshots**
Screenshot of detected episodes (season 2 files are detected as season 1)
![image](https://user-images.githubusercontent.com/692616/110261074-95269600-8013-11eb-9508-8741113e47d2.png)

**Platform Information (please complete the following information):**
 - OS: Windows 10
 - Docker: No
 - Sonarr Version: 3.0.4.1141
 - Sonarr Branch: develop

**Comment by markus101** [comment]
The files in the series folder need to follow TheTVDB's absolute numbers (ones that don't reset each season). Sonarr not support resetting absolute numbers in the series folder.

**Comment by GodKratos** [comment]
> 
> 
> The files in the series folder need to follow TheTVDB's absolute numbers (ones that don't reset each season). Sonarr not support resetting absolute numbers in the series folder.

Isn't absolute numbering only used when the Series Type is set to Anime? The problem occurs if the Series Type is Standard as well.

Regardless, having the ability to prioritise Season based off the folder when there are multiple episodes that match would be an improvement.
Or the ability to select whether the episodes are absolute or season numbered.

Why close an issue that is not actually resolved?

**Comment by markus101** [comment]
> Isn't absolute numbering only used when the Series Type is set to Anime? The problem occurs if the Series Type is Standard as well.

No, that only affects searching, you'd still have the same issue even if it didn't use absolute numbers, because that file name forces Sonarr to parse it as an absolute named title and even if it didn't `S2 - 01` likely wouldn't find a match.

Closed because that is how it works and we do not have plans to change that behaviour at this time.

**Comment by markus101** [comment]
To expand on this a bit the biggest issue here is Sonarr doesn't support "scene" numbering/titles in the file names inside the series folder, which is unlikely to change, it's a lot easier to always require that the files in the series folder match the metadata source than try to guess whether it's set properly.

It's possible a fix comes with https://github.com/Sonarr/Sonarr/issues/903 but that will only happen if we can reasonably detect that this is the case.

**Comment by GodKratos** [comment]
It seems to be a lot more common these days for anime releases to be season numbered rather than absolute and they typically use that numbering above 'S2 - 01'.
Plus it happens a lot where different arcs of a show have different titles and their own episode numbers but in TVDB they are multiple seasons of the same show (eg Sword Art Online)

I'm not sure if this helps to give some ideas but I use the [Absolute Series Scanner](https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/README.md) in Plex for anime shows and it supports a folder naming structure that identifies different types of episode numbering.

eg [tvdb2-id#] will use TVDB as the numbering source with the show matched to the specific TVDB ID and will recognise absolute numbered episodes but split them up into seasons in Plex.
[tvdb-id#] recognises the episodes as season numbered by folder
