### ISSUE TITLE
Can't Parse TV Shows with Episode 1000

### ISSUE THREAD

**Issue by pingadilim** [Sonarr/Sonarr#4367]
Hi, 

First of all, thank you for the great works.

I've got issue on Sonarr version 2.0.0.5344 with Mono version 5.20.1.34.
I can't download the episode 1000 automatically or manually.
In Manual Download the reason was "Unable to parse episodes from release name"
Below is the log while parsing episode 1000 from one of the release.
Seems like Sonarr read the episode as S10E00.

The Log:
```
21-3-8 15:45:43.4|Info|DownloadDecisionMaker|Processing 25 releases
21-3-8 15:45:43.4|Trace|DownloadDecisionMaker|Processing release 1/25
21-3-8 15:45:43.4|Debug|DownloadDecisionMaker|Processing release '[Erai-raws] Detective Conan - 1000 [1080p HEVC].mkv' from 'Nyaa'
21-3-8 15:45:43.4|Debug|Parser|Parsing string '[Erai-raws] Detective Conan - 1000 [1080p HEVC].mkv'
21-3-8 15:45:43.4|Trace|Parser|^(?<title>.+?)?(?:(?:[-_\W](?<![()\[!]))*(?<season>(?<!\d+|\(|\[|e|x)\d{2})(?<episode>(?<!e|x)\d{2}(?!p|i|\d+|\)|\]|\W\d+|\W(?:e|ep|x)\d+)))+(\W+|_|$)(?!\\)
21-3-8 15:45:43.4|Debug|Parser|Episode Parsed. Detective Conan - S10E00 
21-3-8 15:45:43.4|Debug|Parser|Language parsed: English
21-3-8 15:45:43.4|Debug|QualityParser|Trying to parse quality for [Erai-raws] Detective Conan - 1000 [1080p HEVC].mkv
21-3-8 15:45:43.4|Debug|Parser|Quality parsed: HDTV-1080p v1
21-3-8 15:45:43.4|Debug|Parser|Release Group parsed: Erai-raws
21-3-8 15:45:43.4|Debug|Parser|Parsing string '[Erai-raws] Detective Conan - 1000 [1080p HEVC].mkv'
21-3-8 15:45:43.4|Trace|Parser|^(?<title>.+?)?(?:(?:[-_\W](?<![()\[!]))*(?<season>(?<!\d+|\(|\[|e|x)\d{2})(?<episode>(?<!e|x)\d{2}(?!p|i|\d+|\)|\]|\W\d+|\W(?:e|ep|x)\d+)))+(\W+|_|$)(?!\\)
21-3-8 15:45:43.4|Debug|Parser|Episode Parsed. Detective Conan - S10E00 
21-3-8 15:45:43.4|Debug|Parser|Language parsed: English
21-3-8 15:45:43.4|Debug|QualityParser|Trying to parse quality for [Erai-raws] Detective Conan - 1000 [1080p HEVC].mkv
21-3-8 15:45:43.4|Debug|Parser|Quality parsed: HDTV-1080p v1
21-3-8 15:45:43.4|Debug|Parser|Release Group parsed: Erai-raws
21-3-8 15:45:43.5|Debug|ParsingService|Unable to find Detective Conan - S10E00 HDTV-1080p v1
21-3-8 15:45:43.5|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unable to parse episodes from release name
```

Thank you.

**Comment by bakerboy448** [comment]
Closing; V2 is no longer seeing further development work

this was fixed in v3 https://github.com/Sonarr/Sonarr/commit/8fe93eae38b25251efa13024ca8b961b6d6122d0

Also template not followed (3rd party apps ignore templates or you intentionally nuked and destroyed the template, hopefully the former :) )

**Comment by pingadilim** [comment]
Ahh..I see will try to use V3 then.

As for template currently I'm using docker image from linuxserver, but will try with the preview release instead of stable..

Thank you for the info.

Cheers.

**Comment by bakerboy448** [comment]
Reopening; slight feature gap in v3 that don't have the E/Episode prefix

v3.0.5.1143

https://pastebin.com/YD8GKFHK

relevant release
`21-3-9 08:40:26.4|Debug|Parser|Parsing string '[Cheetah-Raws] Detective. Conan - 1000 (YTV 1280x720 x264 AAC). mp4'`

Sonarr is reading that as S/E even with it set to anime
