### ISSUE TITLE
Email notifications not working with multiple email addresses

### ISSUE THREAD

**Issue by matthers** [Sonarr/Sonarr#4369]
I am on Version    3.0.4.1139, using Docker containers.

When using multiple addresses in the Settings->connect->Gmail->Recipient Address field, the test fails and the logs show:

21-3-9 14:42:40.0|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Server: Unable to send test email
21-3-9 14:42:41.3|Error|EmailService|To email address 'address@one.tld, address@two.tld' invalid

[v3.0.4.1139] MimeKit.ParseException: Unexpected token at offset 16

I've tried using both , and ; as separators.

This has been working on the "old" interface.

**Comment by bakerboy448** [comment]
1) You're out of date.  Update

2) Sonarr only supports 1 email address I recently learned

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

**Comment by bakerboy448** [comment]
Radarr Commit to pull https://github.com/Radarr/Radarr/commit/30def1f53a310a44a048fbd99a8023bba4b9c602
