### ISSUE TITLE
User directory appears empty.

### ISSUE THREAD

**Issue by jmanabc** [Sonarr/Sonarr#4370]
OS: Arch Linux
Sonarr version: 3.0.5

Upon update to v3, lost all settings, as if a completely fresh install. Re-added all my indexers and my download client, went to reimport my shows, but cannot select my tv folder as a folder to import from. My tv folder is located in /home/user/tv, but while I can see the folders in / and in /home, selecting /home/user just appears as an empty directory, when a simple ls shows this isn't the case on the system. Go to add my shows via adding them as a new show, would just scan disk and it should update, but I can't add any shows with the same directory as my old shows, because the user directory appears empty within sonarr.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

**Comment by jmanabc** [comment]
> Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

Already reached out in discord support channel, received no reply.

**Comment by bakerboy448** [comment]
Searched discord for

“arch”
“Home/user”
“Jmanabc”

no messages on the server at all today / recently requesting assistance.  So not sure what you said or didn’t say, but it doesn’t appear you came to discord with a problem...or you didn’t come to discord at all. 

Regardless no where does it say GitHub Issues is a support method.  Bugs and Feature Requests only.

![653D3FE9-6C1F-4BB8-AFB1-CC1406887DAE](https://user-images.githubusercontent.com/55419169/110564750-00a35d00-8113-11eb-97df-a0741ee71d79.png)
