### ISSUE TITLE
Specify a download subfolder per serie

### ISSUE THREAD

**Issue by Noxalus** [Sonarr/Sonarr#4371]
Hello everyone!

I use Sonarr with Transmission and I have a small Transmission script called when a download is complete to move the file to my Plex media folder using `transmission-remote` command to keep seeding:

```
transmission-remote localhost:9091 -n $USER:$PASS -t "${TR_TORRENT_ID}" --move "${destinationPath}"
```

In my example, the `destinationPath` correspond to the Plex media folder as prefix and the subfolders relative to the transmission download folder as suffix.

So what I would like is a subfolder that correspond to the "{Category}/{Serie Title}" but for the download, not the Sonarr complete file destination folder as I don't want to use the Sonarr's completed download handler.

From what I saw, the only way to create subfolders for download path is with the `Category` field (or `Directory` field with advanced settings) in the download client settings, and it works as expected for me, except it's global to all series and my subfolder must contain the serie title.

I also checked the "Use Season Folder" option in serie settings and it's a pretty neat way to organize the library, but it's only when a download is completed and only if we enable the Sonarr's completed download handler 😢 

The best way to do what I would like is to use this season folder but for the download client destination.

Does my case makes sense for you? Do you see a way to do what I want another way? 🤔

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.


This is what hardlinks are for.  You have no reason nor need to point your download client at your media library
