### ISSUE TITLE
MoveSeriesService log message shows original location not destination when successfully

### ISSUE THREAD

**Issue by ShannenR** [Sonarr/Sonarr#4375]
When reviewing the sonarr.txt log file after using the Move Files function I noticed it shows the Original Location the file where copied from instead of the Destination Location in the "successful" log message.

**Expected behavior**
The Log message should say "MoveSeriesService|The Queen's Gambit moved successfully to **/shared/TV Shows/The Queen's Gambit**" (maybe even be contained within ' characters to match the "Moving" log line)

**Screenshots**
|Info|MoveSeriesService|Moving The Queen's Gambit from '/incoming/The Queen's Gambit' **to '/shared/TV Shows/The Queen's Gambit**'
|Info|MoveSeriesService|The Queen's Gambit moved **successfully to /incoming/The Queen's Gambit**

**Platform Information (please complete the following information):**
 - Docker: Yes (linuxserver.io)
 - Sonarr Version: 3.0.4.991
 - Sonarr Branch: master

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

|Info|MoveSeriesService|Moving The Queen's Gambit from '/incoming/The Queen's Gambit' **to '/shared/TV Shows/The Queen's Gambit'**
|Info|MoveSeriesService|The Queen's Gambit moved successfully **to /incoming/The Queen's Gambit**

**Comment by ShannenR** [comment]
So I upgraded to the latest docker and it was correct for the **first** Show I moved but then on the **second** Show it was incorrect + it **corrupted the files** in the Destination Location :(

Correct Message and Files could play at Destination:
21-3-12 15:50:05.9|Info|MoveSeriesService|Moving Cavendish from '/incoming/Cavendish' **to '/shared/TV Shows/Cavendish**'
21-3-12 15:50:22.0|Info|MoveSeriesService|Cavendish moved **successfully to /shared/TV Shows/Cavendish**

Wrong Message and Files in Destination were the right size but corrupt and would no longer play:
21-3-12 15:53:02.7|Info|MoveSeriesService|Moving Children of Dune from '/incoming/Children of Dune' **to '/shared/TV Shows/Children of Dune**'
21-3-12 15:53:38.4|Info|MoveSeriesService|Children of Dune moved successfully **to /incoming/Children of Dune**

**Comment by bakerboy448** [comment]
Info logs are useless for any debugging and what it likely is mono copying across I’m going to guess network mounts?

0 info on your environment other than docker
Improper logs provided 

“latest docker” is not a version

Markus or Taloth will swing by overnight I’m sure.  This may just be a race condition somewhere as well.

**Comment by ShannenR** [comment]
Your right sorry, the version is Version: 3.0.5.1144, Package Version: 3.0.5.1144-ls98 by linuxserver.io, Mono Version: 5.20.1.34

Docker is running on Synology NAS and the mount points are different volumes on the NAS itself so no SMB / network transfer.
