### ISSUE TITLE
Place "Moving" Message and / or Tag 

### ISSUE THREAD

**Issue by ShannenR** [Sonarr/Sonarr#4376]
When you change a Folder of a TV Series and let Sonarr perform the "Move" of the files there is a log message in the bottom left of the screen where you usually see the "RSS Refresh" / "Refreshing TV Show" / etc messages BUT within the TV Show itself's page its not obvious a Move is in progress.

**Describe the solution you'd like**
To the right of to the Location name field on a TV Shows page if a Move is in progress put a red backgrounded tag / text saying something like "Moving".

**Describe alternatives you've considered**
Take it a step further and on the line under the row with the Location have a red backgrounded tag / text which shows the same message as in the bottom left (e.g. "Moving The Simpsons from '/incoming/Simpsons' to '/tv/The Simpsons')

**Additional context**
I did try to search for a similar Feature request but didn't find one.

**Comment by markus101** [comment]
At the moment Sonarr doesn’t know what the previous path is because it’s not stored anywhere, which is covered by https://github.com/Sonarr/Sonarr/issues/3933

We can look at adding information that it’s being moved when we implement that change.
