### ISSUE TITLE
Sonarr won't work in background

### ISSUE THREAD

**Issue by pikachukaki** [Sonarr/Sonarr#4378]
I saw this error in the logfile not sure why the folder is denied.
Sonarr wont fetch new episodes without me manually opening the app.

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/6135721/sonarr.txt)

> 21-3-12 00:55:29.3|Fatal|ConsoleApp|EPIC FAIL!
> 
> [v3.0.5.1144] System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Sonarr\config.xml' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
>    at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
>    at System.IO.File.ReadAllText(String path)
>    at NzbDrone.Common.Disk.DiskProviderBase.ReadAllText(String filePath) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 295
>    at NzbDrone.Core.Configuration.ConfigFileProvider.LoadConfigFile() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 321
>    at NzbDrone.Core.Configuration.ConfigFileProvider.<>c__DisplayClass47_0.<GetValue>b__0() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 231
>    at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Cache\Cached.cs:line 104
>    at NzbDrone.Core.Configuration.ConfigFileProvider.GetValue(String key, Object defaultValue, Boolean persist) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 229
>    at NzbDrone.Core.Configuration.ConfigFileProvider.get_LogLevel() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 182
>    at NzbDrone.Core.Instrumentation.ReconfigureLogging.Reconfigure() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Instrumentation\ReconfigureLogging.cs:line 25
>    at NzbDrone.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Host\Bootstrap.cs:line 66
>    at NzbDrone.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Host\Bootstrap.cs:line 41
>    at NzbDrone.Console.ConsoleApp.Main(String[] args) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Console\ConsoleApp.cs:line 42
>

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.
