### ISSUE TITLE
 Title slug 'perry-mason' is in use by series 'Perry Mason'

### ISSUE THREAD

**Issue by texasdaddy** [Sonarr/Sonarr#4379]
Error message received when trying to import Perry Mason (2020) and the original Perry Mason (1957) already exists:
Title slug 'perry-mason' is in use by series 'Perry Mason'

**To Reproduce**
1. Import Perry Mason 
2. Try to import Perry Mason (2020)
3. Receive error message

**Expected behavior**
Import as a separate title

**Platform Information (please complete the following information):**
 - OS: Unraid 6.9.1 (linux kernel 5.10.21, docker version 19.03.14)
 - Docker: Yes
 - Sonarr Version: 3.0.5.1144
 - Sonarr Branch: release

**Trace Logs**
21-3-14 08:46:08.6|Trace|Http|Req: 1785 [GET] /api/v3/series/lookup?term=Perry%20Mason%20(2020) (from 192.168.1.97 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36)
21-3-14 08:46:08.6|Trace|HttpClient|Req: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=perry%20mason%20%282020%29
21-3-14 08:46:08.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
21-3-14 08:46:15.1|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=perry%20mason%20%282020%29: 200.OK (6569 ms)
21-3-14 08:46:15.3|Trace|Http|Res: 1785 [GET] /api/v3/series/lookup?term=Perry%20Mason%20(2020): 200.OK (6693 ms)
21-3-14 08:46:15.3|Debug|Api|[GET] /api/v3/series/lookup?term=Perry%20Mason%20(2020): 200.OK (6693 ms)
21-3-14 08:46:15.7|Trace|Http|Req: 1786 [GET] /api/v3/series/lookup?term=Quantico%20(2015) (from 192.168.1.97 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36)
21-3-14 08:46:15.7|Trace|HttpClient|Req: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=quantico%20%282015%29
21-3-14 08:46:15.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
21-3-14 08:46:17.9|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=quantico%20%282015%29: 200.OK (2256 ms)
21-3-14 08:46:18.0|Trace|Http|Res: 1786 [GET] /api/v3/series/lookup?term=Quantico%20(2015): 200.OK (2367 ms)
21-3-14 08:46:18.0|Debug|Api|[GET] /api/v3/series/lookup?term=Quantico%20(2015): 200.OK (2367 ms)
21-3-14 08:46:24.7|Trace|Http|Req: 1787 [POST] /api/v3/series/import (from 192.168.1.97 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36)
21-3-14 08:46:25.0|Info|AddSeriesService|Adding Series [363026][Perry Mason] Path: [/tv/tv/Perry Mason (2020)]
21-3-14 08:46:25.0|Trace|HttpClient|Req: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/363026
21-3-14 08:46:25.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
21-3-14 08:46:25.2|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/363026: 200.OK (178 ms)
21-3-14 08:46:26.0|Trace|SonarrErrorPipeline|Handling Exception
21-3-14 08:46:26.0|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- TitleSlug: Title slug 'perry-mason' is in use by series 'Perry Mason'

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
