### ISSUE TITLE
“Taken” series (2002) won’t download

### ISSUE THREAD

**Issue by halesyeah3** [Sonarr/Sonarr#4383]
When I try to manually download the TV series ‘Taken’ from 2002 I see an error for missing series.  I have emailed the indexer and the TVDB, the latter of which said to contact you and if it’s an issue on their end you will notify them.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

Also template not followed.
