### ISSUE TITLE
Test all indexers button

### ISSUE THREAD

**Issue by ronnybugle** [Sonarr/Sonarr#4384]
It would be nice to have a single button to test all indexers.
Useful when jackett goes down and consequently all indexers become unavailable and each has to be re-tested and saved to use again.

**Comment by bakerboy448** [comment]
closing; template not followed

..also this exists
![image](https://user-images.githubusercontent.com/55419169/111235401-8d8c6180-85be-11eb-9275-f437749e10fb.png)
