### ISSUE TITLE
v3 needs 100 times more CPU

### ISSUE THREAD

**Issue by grasshide** [Sonarr/Sonarr#4386]
**Describe the bug**
v3 needs 100 times more CPU

**To Reproduce**
Download Image from Linuxserver.io, run it.

**Expected behavior**
Constant CPU usage of 4% -- 100 times more than v2.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4366857/111363510-6e5e0480-8690-11eb-9a80-47aa5c88ac8e.png)

**Platform Information (please complete the following information):**
 - OS: Debian 9, latest Docker version
 - Docker: Yes
- Version: 3.0.5.1144
- Package Version: 3.0.5.1144-ls98 by linuxserver.io 
- Mono Version: 5.20.1.34

**Trace Logs**
not needed
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
https://pastebin.com/QLQzuVLA

**Comment by markus101** [comment]
Please fill out the appropriate template.

**Comment by grasshide** [comment]
**Describe the bug**
v3 needs 100 times more CPU

**To Reproduce**
Download Image from Linuxserver.io, run it.

**Expected behavior**
Constant CPU usage of 4% -- 100 times more than v2.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4366857/111363510-6e5e0480-8690-11eb-9a80-47aa5c88ac8e.png)


**Platform Information (please complete the following information):**
 - OS: Debian 9, latest Docker version
 - Docker: Yes
 - Linuxserver.io image
 - Sonarr Version: latest

**Trace Logs**
not needed
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
not needed

**Comment by fryfrog** [comment]
You can edit the original post instead of making a comment. And please include *actual* versions, not just "latest".

**Comment by grasshide** [comment]
> You can edit the original post instead of making a comment. And please include _actual_ versions, not just "latest".

done

**Comment by Taloth** [comment]
Check Trace level logs to find out what it's spending it's time on.

**Comment by grasshide** [comment]
> Check Trace level logs to find out what it's spending it's time on.

Looking at the trace, there are two things I recognize:
1.) Sonarr checks almost every minute if there is any update from NZBGet, even though nothing is downloading.
  `CommandQueueManager|Publishing RefreshMonitoredDownloads`
2.) There seems to be some kind of database locking error:
  `Trace|Owin|SQLite error (5): database is locked`

I looked at the container to check if it is sonarr which generates the cpu load:
` PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                             
  253 abc       20   0 1389144 209456  20428 S   7.0  1.7 170:00.10 mono                                                                
    1 root      20   0     200      0      0 S   0.0  0.0   0:00.03 s6-svscan                                                           
   34 root      20   0     200      0      0 S   0.0  0.0   0:00.00 s6-supervise                                                        
  251 root      20   0     200      0      0 S   0.0  0.0   0:00.00 s6-supervise                                                        
24222 root      20   0   20188   3832   3384 S   0.0  0.0   0:00.05 bash                                                                
24232 root      20   0   38272   3516   3072 R   0.0  0.0   0:01.19 top`


Partial trace is here: https://pastebin.com/3Ck23ED6
I only removed the NZBget results.

**Comment by Taloth** [comment]
1. That's normal (also did so in v2). The logs says that RefreshMonitoredDownload spent 0.1 second each time it runs (wall, not cpu), that looks fine.
2. That's normal too, it's not actually an error. It can be used as an indicator of an io bottleneck _if_ there are dozens of those lines in quick succession. Hence being logged at Trace level.

The log is 5 minutes long, so I think you have to zoom in grafana to isolate a problem section. To see whether it's constant usage or correlates with specific tasks in Sonarr.

Also check System->Tasks to see if anything is running.

**Comment by grasshide** [comment]
The load really is constant and does not change much:
![Bildschirmfoto von 2021-03-17 11-09-46](https://user-images.githubusercontent.com/4366857/111451127-65614780-8711-11eb-931a-41b149b6e8d5.png)

Tasks look all right to me:
![Bildschirmfoto von 2021-03-17 11-12-11](https://user-images.githubusercontent.com/4366857/111451506-cc7efc00-8711-11eb-9d68-5a70e5122831.png)

**Comment by Taloth** [comment]
Interesting, I'll do some digging and get back to you later.

**Comment by hcoohb** [comment]
Hi, I have similar issue as well

**Comment by Taloth** [comment]
Lemme know how the performance is on 3.0.5.1189, and close the issue when it's ok.

**Comment by hcoohb** [comment]
@Taloth ,
Upgrading to the latest :develop container definitely fixed the issue for me.

Thanks a lot for quickly looking into this and fixing the issue!!!

Now, can't wait for radarr getting a release with this fix too!

![sonarr-cpu](https://user-images.githubusercontent.com/12975783/111865412-81374880-89b2-11eb-8066-66255107da4f.jpg)

**Comment by grasshide** [comment]
Same for me! Just upgraded to the dev container and no longer see the high CPU utilization.

<img width="366" alt="Bildschirmfoto 2021-03-20 um 16 27 53" src="https://user-images.githubusercontent.com/4366857/111875281-3bba5180-8999-11eb-9d5f-c2751b05271b.png">
<img width="720" alt="Bildschirmfoto 2021-03-20 um 16 24 40" src="https://user-images.githubusercontent.com/4366857/111875263-2cd39f00-8999-11eb-8783-ec8f5c6039ec.png">

Thank you very much for this fix!
