### ISSUE TITLE
Files are duplicated ? Normal ?

### ISSUE THREAD

**Issue by Whisper40** [Sonarr/Sonarr#4389]
Hello !

I'm using sonarr with rtorrent and docker compose.
Series are downloading and added to rtorrent in 
/data/downloads

Sonarr get them when they have finished downloading and copy it to /data/SeriesTV.
So it is good, but..
There is the copy that is in the old folder /data/downloads and the one in /data/SeriesTV

I understand that it can be for sharing, but i need to have a confirmation.
Sonarr doesn't have any policy to delete the one in /data/downloads ? How to delete it ?

Thanks

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

The FAQ covers this as well...
