### ISSUE TITLE
DB Migrator not handling restored schema

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#4390]
v2 was once repaired with dbbrowser.

Schema is like:
```
CREATE TABLE IF NOT EXISTS "Config" (
	"Id"	INTEGER NOT NULL,
	"Key"	TEXT NOT NULL,
	"Value"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
```

whereas originally is:
```
CREATE TABLE `Config` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Key`	TEXT NOT NULL,
	`Value`	TEXT NOT NULL
);
```

The migrator in sonarr parsers the schema, but can't handle the different (but valid) primary key syntax. Which makes migrating to v3 not possible.

**Comment by mitchese** [comment]
This issue is affecting me as well, and fo me it's the same, inspecting the create table and it is using the `PRIMARY KEY("Id" AUTOINCREMENT)` syntax.

Is there an easy way to workaround this temporarily?

**Comment by Qstick** [comment]
FYI this was fixed in Radarr a while back I believe if it helps

https://github.com/Radarr/Radarr/commit/539f495dbea611a8a74221d315802c781b1b9269

**Comment by Taloth** [comment]
I wrote some code for it yesterday. TBH I think that Radarr commit doesn't preserve primary key.
