### ISSUE TITLE
Sonarr won't update/connect if TSL 1.3 is enabled on windows 10

### ISSUE THREAD

**Issue by fuomag9** [Sonarr/Sonarr#4392]
**Describe the bug**
I cannot update sonarr since it'll error out with "Failed to fetch updates"

**To Reproduce**
1. click on the Updates tab in the UI

**Expected behavior**
Fetch updates

**Screenshots**
![image](https://user-images.githubusercontent.com/1580624/111707625-b160d900-8844-11eb-926f-6fced1857b6a.png)

**Platform Information (please complete the following information):**
 - OS: Windows 10 20H2
 - Docker: No
 - .net Framework .net 4.8
 - Browser and Version  chrome  89.0.4389.90 
 - Sonarr Version:  3.0.5.1144
 - Sonarr Branch: main

**Trace Logs**
https://pastebin.com/kP7VbkRc

**Comment by fuomag9** [comment]
Note: this seems to be fixed by reverting the enable of TLS 1.3 system-wide like this article showed https://www.itechtics.com/tls-1-3/, aka deleting the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3` key from the register. 

Nonetheless this should not happen even with tls 1.3 enabled

**Comment by fuomag9** [comment]
https://stackoverflow.com/questions/64212994/net-4-8-tls-1-3-issue-on-windows-10 This seems related to this issue as well

**Comment by fuomag9** [comment]
Relevant issue on github https://github.com/dotnet/docs/issues/4675#issuecomment-768880551

**Comment by bakerboy448** [comment]
> [There is no official roadmap/timeline for TLS 1.3 on .NET Framework (note that even the underlying OS - Windows does not support it in non-Preview builds yet).](https://github.com/dotnet/docs/issues/4675#issuecomment-768880551)

Windows itself does not appear to support TLS 1.3 until Windows 10 20H2, which literally just now rolling out.

Per the same comment
>There is no official roadmap/timeline for TLS 1.3 on .NET Framework 

Marking this as an external bug; not Sonarr issue until the .Net Framework supports it.  Would likely be fixed with the future/eventual switch to .Net 5 ( or maybe .Net 6)

**Comment by fuomag9** [comment]
> > [There is no official roadmap/timeline for TLS 1.3 on .NET Framework (note that even the underlying OS - Windows does not support it in non-Preview builds yet).](https://github.com/dotnet/docs/issues/4675#issuecomment-768880551)
> 
> 
> 
> Windows itself does not appear to support TLS 1.3 until Windows 10 20H2, which is literally just now rolling out.
> 
> 
> 
> Per the same comment
> 
> >There is no official roadmap/timeline for TLS 1.3 on .NET Framework 
> 
> 
> 
> Marking this as an external bug; not Sonarr issue until the .Net Framework supports it.  Would likely be fixed with the future/eventual switch to .Net 5 ( or maybe .Net 6)
> 
> 
> 
> Workaround of course: Don't use unsupported configurations. Given the underlying framework does not support TLS 1.3, that would then also mean Sonarr does not support TLS 1.3

TLS 1.3 can be actually enabled (for testing purposes) [since 1903](https://stackoverflow.com/a/59210166), but I agree that since the actual .net stable doesn't support it it'd need either a workaround or using the .net 5 when it releases. This issue would become more serious if TLS 1.3 becomes switched on by default on windows releases (At the moment I'm not aware of it being enabled by default)

**Comment by donig** [comment]
The NET 4.8 May 25, 2021 CU preview enables TLS 1.3 if it is enabled in the OS.

https://support.microsoft.com/en-us/topic/may-25-2021-kb5003254-cumulative-update-preview-for-net-framework-3-5-and-4-8-for-windows-10-version-2004-windows-server-version-2004-windows-10-version-20h2-windows-server-version-20h2-and-windows-10-version-21h1-69caa82d-225c-4833-b5ab-8b6c7cacd02d

**Comment by Vintodrimmer** [comment]
Is this Windows-only problem? I'm running a docker container from linuxserver.io on Linux and after forcing TLSv1.3 in Nginx (used as reverse proxy) Sonarr can no longer connect to Prowlarr.

**Comment by fuomag9** [comment]
> Is this Windows-only problem? I'm running a docker container from linuxserver.io on Linux and after forcing TLSv1.3 in Nginx (used as reverse proxy) Sonarr can no longer connect to Prowlarr.

Afaik this is a problem with all OS due to sonarr not being able to use (or allowing if there have been changes in the .net framework old version it's using) TLS 1.3

**Comment by markus101** [comment]
Sonarr v4 will use .net 6, which has support for TLS 1.3. If there are further issues once v4 has supported builds we'll investigate at that time.

**Comment by Locutus64** [comment]
This isn't just a Windows 10 issue. I just booted into Arch, went to remove Criminal Minds: Evolution and add Criminal Minds and got the Skyhook error.

```
Failed to load search results, please try again.
Search for 'criminal minds' failed. Invalid response received from SkyHook.
```

Running the latest 4.0 development version.

**Comment by Locutus64** [comment]
found I could cheat if I only type part of the name "crimi". Others seem to get found without issue 9-1-1 fbi.

**Comment by markus101** [comment]
Not related to this issue then. 
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
