### ISSUE TITLE
400 Bad Request when adding torrents to qBittorent

### ISSUE THREAD

**Issue by ADRFranklin** [Sonarr/Sonarr#4393]
**Describe the bug**

Sonarr tries to add a torrent to qBittorrent but seems to think it failed with a 400 bad request even though the torrent is added successfully. It also gets the same error when trying to track the torrents download progress. 

Another note is because of the failure to correctly track the progress of the torrent, there seems to be a coin flip of whether it will actually import the torrent or not, and even when it does the state of it is never correctly updated, so even when it manages to import a torrent from qBittorent, the queue manager remains showing it as always being imported until it is manually removed.

**To Reproduce**
Search for a torrent and have it be sent to your qBittorrent client.

**Expected behavior**
I expect Sonarr to be able to add the torrent correctly and track it's download progress.

**Screenshots**

None

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker:  Yes
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status):   Mono 6.12.0.122
 - Browser and Version (Only needed for UI issues):  Brave (1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit))
 - Sonarr Version:  3.0.5.1164
 - Sonarr Branch:  develop

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
https://paste.ubuntu.com/p/sG4fBJFzMg/ (relevant information)
https://paste.ubuntu.com/p/wbXGbXTMpd/ (full trace log)

**Comment by ADRFranklin** [comment]
Just to add to this, if you have multiple instances of qBittorent instances, and you have them with the same priority, then when the one it picks fails to add the torrent, it will move on to the next available client which results in the torrents being added to multiple clients and quickly filling up your storage.

**Comment by Taloth** [comment]
> Sonarr tries to add a torrent to qBittorrent but seems to think it failed with a 400 bad request even though the torrent is added successfully. It also gets the same error when trying to track the torrents download progress.

No, the Bad Request is a consequence of the same torrent being in both clients at one point, not a cause of it. The BadRequest you see in the logs you posted is about Import Attempts, not Adding the torrent. So you need to find where in the logs a particular torrent was added to one (or two) torrent clients.

Basically, the logs you posted the the aftermath, not the problem itself.

**Comment by Taloth** [comment]
One interesting part however, is line 7091, where qbit is rejecting _a_ (not _the_) torrent, for some reason.

**Comment by evulhotdog** [comment]
While not directly related due to different codebase, I'm seeing similar with Radarr.

Radarr:
> Version: 3.1.0.4761
> Package Version: 3.1.0.4761-ls38 by linuxserver.io
> .NET: Yes (5.0.4)
> Docker: Yes
> DB Migration: 192

Qbit: v4.3.3

https://pastebin.com/cPAF8kiQ

**Comment by Taloth** [comment]
@evulhotdog Do you have both a seed time AND ratio limit set?

**Comment by evulhotdog** [comment]
Closing the loop from discord conversation...

I only have seedRatio set. No seedTime (it's blank.)

**Comment by Taloth** [comment]
@ADRFranklin If you still have problems after the next version, then post the 'add' logs i mentioned in my first reply.
