### ISSUE TITLE
New "* Ended" items in Calendar view

### ISSUE THREAD

**Issue by the0neWhoKnocks** [Sonarr/Sonarr#4394]
**Is your feature request related to a problem? Please describe.**
Currently there's a "Premiered" icon on episodes in the Calendar view. In order to determine if a season has aired it's last episode, or if the series is over, you have to go into each individual series.

**Describe the solution you'd like**
I propose adding two new icons for "Season Ended" and "Series Ended". This way it's much easier to see at a glance the state of a season/series.
![sonarr--new-legend-items](https://user-images.githubusercontent.com/344140/111809446-38886e00-8892-11eb-87a3-d2213a3ce942.png)

**Comment by Taloth** [comment]
You can, top right 'Options', enable Icon for Finales.

**Comment by markus101** [comment]
If the series is marked as ended the tool tip will show `Series Finale`. We don't have plans to show different icons.

**Comment by the0neWhoKnocks** [comment]
@Taloth so series finales are covered 👍, but it's odd that it's hidden behind an opt-in wall, but Premiere is not. For consistency it seems that all series status icons should either be on by default or options that need to be enabled.

@markus101 Can you elaborate as to why a Season Ended icon won't be taken under consideration?

**Comment by markus101** [comment]
It's opt-in because the data isn't as stable. Sonarr is guessing that the last listed episode in a season is the finale, if episodes are added shortly before airing or there is a mid-season gap it's going to incorrectly show it's the finale.

We're not going to show a _different_ icon, both season and series finale episodes use the same icon.

**Comment by the0neWhoKnocks** [comment]
@markus101 , sorry, based on Taloth's and your reply, I didn't realize that the option for finales covered `series/season finales`, it read like it just covered `Series Finale`s.

Perhaps a clearer reply could've been
> There is already a feature that exists to display both Season and Series finales. Go into Options, and enable `Icon for Finales`.

Shame about the API instability, but that's understandable especially considering how things like environmental issues, or a pandemic can throw off production schedules. Thanks for taking the time to clarify things for me.
