### ISSUE TITLE
Priority for torrent indexers

### ISSUE THREAD

**Issue by newhollandaus** [Sonarr/Sonarr#4396]
I’m having the problem of Sonarr grabbing releases from torrent indexers (through Jackett) which I have little upload credits. Where the release is available on an indexer with much more upload credit. It would be very handy to create a priority of torrent indexers.

**A solution to this problem could be a numerical priority to favour torrent indexers** in which you have a high ratio/surplus upload credits.

I’d ideally like to setup a seedbox on the torrent indexer which I have little upload credit. But not all indexers have freeleech to really maximise seedbox time.

I’ve read Sonarr was originally designed for Usenet, so torrents through Jackett aren’t as straightforward. But like how software like NZBGET had priority for news severs. In this case it would be handy to have priority for certain torrent indexers which have great upload credit.

I see on my Sonarr version 3.0.5.1144 that my download client Qbittorrent is a higher priority than NZBGET after I selected ‘prefer torrents’ in the profile menu. As NZBGET has a ‘priority 2’ label on it.

**Comment by bakerboy448** [comment]
This exists.
Turn on advanced settings in your indexers

**Comment by newhollandaus** [comment]
Oops thank you Bakerboy448 for the fast response. 😅
