### ISSUE TITLE
Support "Series" along with "Season"

### ISSUE THREAD

**Issue by inspector71** [Sonarr/Sonarr#4399]
**Is your feature request related to a problem? Please describe.**

When scanning for a full single download with an entire "season" packaged together, Sonarr ignores the perfectly reasonable, often UK used term "Series".

**Describe the solution you'd like**

Support torrents named thus:

`<Show Name> Series XX (XXXX)`

... in the same manner as torrents named:

`<Show Name> sXX (XXXX)`

... or presumably (though not specifically tested at time of writing, to be fair):

`<Show Name> Season XX (XXXX)`

**Describe alternatives you've considered**

Renaming the torrents works so the issue is proven. Several times :) Most recently with Sonarr 2.0.0.5344 in the last 24 hours.

**Additional context**

Appreciate myriad naming schemes cannot be supported; 'the scene' overlords may have made "Season" the required naming ... but can we be a bit more reasonable instead of forcing users to feck around so much? Hopefully will make Sonarr even better. After all, there is seemingly nothing users can be done to stop uploaders using their localised terminology. Hard enough getting them to stick to a naming and numbering scheme, as Sonarr beneficiaries of a certain mostly-chaotic, at least in the past, UK tracker will attest.

**Comment by markus101** [comment]
If you can provide some concrete examples of release names we'll take a look, but Interactive search/Manual Import is the recommended way to deal with this. In v3 you can have Sonarr show items in the queue that it's not able to parse properly as well.

**Comment by inspector71** [comment]
Thanks for your reply.

Thought the idea of Sonarr is to be automatic?

When sourcing content from sites with a very strict ratio, automatic 
grabbing via RSS is not ideal. Perhaps not even possible (rare posts 
site admins want people to manually check).

So, already downloading manually, assigning a category for Sonarr 
manually. Possibly adding a new show manually.

Would be handy if Sonarr took over at least at this point.

Also, maybe the issue post was not clear. These torrents do not appear 
in the queue for manual import. Sonarr just seems to ignore them. No log 
entry I have seen or anything.

What you would consider concrete examples? Screenshots from a torrent 
client perhaps? Log might not help as there is nothing really to search 
for (AKA difficulty of proving a negative?).

If a regular expression change to support this was submitted as a pull 
request, is that likely to be ignored based on the "preferred" policy 
you mentioned?

Thanks again

------ Original Message ------
From: "Mark McDowall" ***@***.***>
To: "Sonarr/Sonarr" ***@***.***>
Cc: "inspector71" ***@***.***>; "Author" 
***@***.***>
Sent: 21/03/2021 12:01:50 PM
Subject: Re: [Sonarr/Sonarr] Support "Series" along with "Season" 
(#4399)

**Comment by bakerboy448** [comment]
Activity -> Options -> Show Unknown will show everything in sonarr's download client category

**Comment by markus101** [comment]
> Thought the idea of Sonarr is to be automatic?

If it's possible, but not everything can be automated.

> Possibly adding a new show manually.

The series is always going to need to be added to Sonarr manually if you're not adding via another app or a Trakt list.

> Also, maybe the issue post was not clear. These torrents do not appear
in the queue for manual import. Sonarr just seems to ignore them. No log
entry I have seen or anything.

That was clear, because unknown items are never shown in the queue in v2, as I said and baker pointed you to there is an option for that in v3.

> What you would consider concrete examples?

Full release/torrent names.

> Screenshots from a torrent client perhaps?

Definitely not screenshots, text.

> Log might not help as there is nothing really to search for (AKA difficulty of proving a negative?).

Trace logs contain the response from the torrent client, assuming things are in the correct category.

> If a regular expression change to support this was submitted as a pull
request, is that likely to be ignored based on the "preferred" policy
you mentioned?

Closed maybe, ignored, no. It's all going to depend on the examples.

**Comment by inspector71** [comment]
Is that a version 3 thing?

------ Original Message ------
From: "bakerboy448" ***@***.***>
To: "Sonarr/Sonarr" ***@***.***>
Cc: "inspector71" ***@***.***>; "Author" 
***@***.***>
Sent: 22/03/2021 1:04:02 AM
Subject: Re: [Sonarr/Sonarr] Support "Series" along with "Season" 
(#4399)

**Comment by bakerboy448** [comment]
Yes

**Comment by inspector71** [comment]
Thank you!

Have been contemplating moving to v3. Getting familiar with the user 
experience through using Lidarr and Radarr

------ Original Message ------
From: "bakerboy448" ***@***.***>
To: "Sonarr/Sonarr" ***@***.***>
Cc: "inspector71" ***@***.***>; "Author" 
***@***.***>
Sent: 22/03/2021 1:44:32 PM
Subject: Re: [Sonarr/Sonarr] Support "Series" along with "Season" 
(#4399)

**Comment by inspector71** [comment]
------ Original Message ------
From: "Mark McDowall" ***@***.***>
To: "Sonarr/Sonarr" ***@***.***>
Cc: "inspector71" ***@***.***>; "Author" ***@***.***
>
Sent: 22/03/2021 4:30:52 AM
Subject: Re: [Sonarr/Sonarr] Support "Series" along with "Season" (#4399)

Thought the idea of Sonarr is to be automatic?

If it's possible, but not everything can be automated.

Absolutely understand that. For example, the RSS reliance I can understand
and manually poke around to get Sonarr to search for episodes /
(series|seasons) when adding an old, ended show or after finding a running
show mid-way through.

Not ideal but fair enough.

Looking for log entries related to this issue, noticed there's one for
explaining the RSS limitation. Details timeframes when the feeds apply.
That's great feedback to have in the logs 🙂


Possibly adding a new show manually.

The series is always going to need to be added to Sonarr manually if you're
not adding via another app or a Trakt list.

Yep, understand that. Discovering, adding shows manually is step one in
Sonarr land. Did not intend this issue to suggest otherwise.


Also, maybe the issue post was not clear. These torrents do not appear
in the queue for manual import. Sonarr just seems to ignore them. No log
entry I have seen or anything.

That was clear, because unknown items are never shown in the queue in v2,
as I said and baker pointed you to there is an option for that in v3.

Cool, thanks.

What you would consider concrete examples?

Full release/torrent names.

OK, will see what I can do. Please bear with me if I am not able to meet
the criteria initially.


Screenshots from a torrent client perhaps?

Definitely not screenshots, text.

Fair enough. To copy and paste :)


Log might not help as there is nothing really to search for (AKA difficulty
of proving a negative?).

Trace logs contain the response from the torrent client, assuming things
are in the correct category.

Oh yeah, d'oh, apologies that I did not think of that. Will enable Trace
level.


If a regular expression change to support this was submitted as a pull
request, is that likely to be ignored based on the "preferred" policy
you mentioned?

Closed maybe, ignored, no. It's all going to depend on the examples.

OK, thanks.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Sonarr/Sonarr/issues/4399#issuecomment-803628451>, or
unsubscribe

**Comment by inspector71** [comment]
Here is an example. 

Not the cleanest (episodes missing `The ` prefix; ` DivX` appended to name; dot after episode number) but a start.

1. Manually downloaded `.torrent` file via browser
	- Name: 
		* `The Lovers - Series 1 (1970) DivX`
	- Folder: 
		* `The Lovers - Series 1 (1970) DivX`
	- Episodes:
			* `LOVERS S01E01. SARDINE SANDWICHES..avi`
			* `LOVERS S01E02. THE DATE..avi`
			* `LOVERS S01E03. FRECKLE FACE..avi`
			* `LOVERS S01E04. BRAINWASHING..avi`
			* `LOVERS S01E05. A PIPE AND A MOUSTACHE..avi`
			* `LOVERS S01E06. THE TRUTH GAME..avi`
2. qBittorrent triggered to handle download
3. Saved **without initially setting Category**
4. Enable `Tracing` log level in Sonarr
5. Manually set Category to `sonarr` (my Download Client [Category keyword](https://i.imgur.com/We430iT.png)) in qBittorent
6. Add `The Lovers (1970)` [in Sonarr using the magnifying glass (add and immediately search) mode](https://i.imgur.com/yEEwo23.png).
7. Trace log:
	1. `21-3-24 20:56:59.3|Trace|EventAggregator|CommandExecutedEvent <- TaskManager`
	2. `21-3-24 20:56:59.4|Debug|Parser|Parsing string 'The Lovers - Series 1 (1970) DivX'`
	3. `21-3-24 20:56:59.4|Trace|EventAggregator|CommandExecutedEvent -> TaskModule`
	4. `21-3-24 20:56:59.4|Debug|Parser|Unable to parse The Lovers - Series 1 (1970) DivX`
	5. `21-3-24 20:56:59.5|Trace|EventAggregator|CommandExecutedEvent <- TaskModule`
	6. `21-3-24 20:56:59.5|Trace|TrackedDownloadService|No Episode found for download 'The Lovers - Series 1 (1970) DivX', not tracking.`
8. Edit in qBittorrent to...
	- Name:
		* `The Lovers - Season 1 (1970) DivX`
	- Folder:
		* `The Lovers - Season 1 (1970) DivX`
	- Episodes not renamed (yet!)
9. Trigger `System -> Task -> Downloaded Episodes Scan` via Sonarr interface
10. **Result** :) 
	1. Download recognised
	2. Episodes one to five imported, renamed, etc


Yes, I understand you may need and/or want full logs but they do have a degree of privacy sensitivity. Is above enough? The `Trace` log does generate quite a lot of output when episodes are found. The episodes may have been scanned in reverse order as well which makes things a touch trickier, haha. Here's a chunk though (less obfuscated paths):

`21-3-24 21:13:52.3|Debug|EpisodeFileMovingService|Hardlinking episode file: Downloads\incoming\The Lovers - Season 1 (1970) DivX\LOVERS S01E01. SARDINE SANDWICHES..avi to tv\L\The.Lovers\01\The.Lovers.s01e01.Sardine.Sandwiches.SDTV.DivX-Sonarr.avi
21-3-24 21:13:52.3|Debug|DiskTransferService|HardLinkOrCopy [Downloads\incoming\The Lovers - Season 1 (1970) DivX\LOVERS S01E01. SARDINE SANDWICHES..avi] > [tv\L\The.Lovers\01\The.Lovers.s01e01.Sardine.Sandwiches.SDTV.DivX-Sonarr.avi]
21-3-24 21:14:10.1|Trace|Scheduler|Pending Tasks: 1
21-3-24 21:14:10.1|Trace|CommandQueueManager|Publishing CheckForFinishedDownload
21-3-24 21:14:10.2|Trace|CommandQueueManager|Checking if command is queued or started: CheckForFinishedDownload
21-3-24 21:14:10.2|Trace|CommandQueueManager|Command is already in progress: CheckForFinishedDownload
21-3-24 21:14:10.7|Trace|ConfigService|Using default config value for 'filedate' defaultValue:'None'
21-3-24 21:14:10.8|Debug|MediaFileAttributeService|Setting last write time on series folder: tv\L\The.Lovers
21-3-24 21:14:10.8|Debug|MediaFileAttributeService|Setting last write time on series folder: tv\L\The.Lovers\01
21-3-24 21:14:10.9|Trace|EventAggregator|Publishing EpisodeFileAddedEvent
21-3-24 21:14:10.9|Trace|EventAggregator|EpisodeFileAddedEvent -> EpisodeService
21-3-24 21:14:10.9|Debug|EpisodeService|Linking [01\The.Lovers.s01e01.Sardine.Sandwiches.SDTV.DivX-Sonarr.avi] > [[11135]Sardine Sandwiches]`

Impressed by Sonarr overcoming the dodgy episode naming! For the most part.
