### ISSUE TITLE
Interactive manual import dialog too big for mobile

### ISSUE THREAD

**Issue by 6cUbi57z** [Sonarr/Sonarr#4401]
**Describe the bug**

On mobile screens, the manual import dialog is too big. Only the title is visible for most entries. The series, season and episode selectors are all off the right side of the screen and the UI won't scroll when dragging.

**To Reproduce**

The UI should be usable on mobile.

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/3359745/111926648-a193ff80-8aa5-11eb-9367-eba2444bd38a.png)

**Platform Information (please complete the following information):**

 - OS: Android 10
 - Docker: Yes
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): Mono 5.20.1.34
 - Browser and Version (Only needed for UI issues): Firefox Mobile 86.1.1
 - Sonarr Version: 3.0.4.1141
 - Sonarr Branch: phantom-develop

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

Usability bug rather than an error so logs do not produce anything.

**Comment by markus101** [comment]
On mobile the manual import modal scrolls, as do other tables/table-like screens. I’m able to scroll on mobile devices and chrome emulating a mobile device without issue.

**Comment by 6cUbi57z** [comment]
Is that both horizontal and vertical scroll? Vertical scroll is working fine but I've never managed to scroll horizontally and the elements are off the screen to the right. I tried again before opening the issue but couldn't get it to work.

**Comment by 6cUbi57z** [comment]
I checked again and the dialog definitely won't scroll to the right which means that the series, season, episode, etc. can only be viewed by chaning the browser to desktop mode and going through the import again.

@markus101 please can this be re-opened? I'll look at providing some extra screenshots and a gif with touch actions visible tomorrow if it would be helpful.

**Comment by markus101** [comment]
In general if it's closed we're not going to re-open it until more information is provided. I've found the issue and will push a fix (not going to open it to close it again). Thanks for the info.
