### ISSUE TITLE
Pull Radarr Commits: Download Path Healthchecks

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4402]
Downloading in root folder
https://github.com/Radarr/Radarr/pull/6089

and

Path/access checks
https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs
and
https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core.Test/HealthCheck/Checks/RemotePathMappingCheckFixture.cs

**Comment by markus101** [comment]
Feel free to open a PR after that PR lands.
