### ISSUE TITLE
Unable to Scroll Small Window on Desktop

### ISSUE THREAD

**Issue by Iss-in** [Sonarr/Sonarr#4403]
**Describe the bug**
Unable to scroll using touchpad after browser window width is less than a specific value ( scrollbar works )

1. Open Sonarr in a firefox window
2. Keep reducing the window until the UI change from 3 column to 4 column and sidebar hide itself
3. Try to Scroll using touchpad
4. Nothing happens

**Expected behavior**
ui should scroll properly

**Platform Information:**
 - OS: Arch
 - Docker: No
 - mono 6.12.0.107-1
 - Browser and Version : firefox 86.0.1-1
 - sonarr 3.0.5.1144-1 ( arch package )

**Trace Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6189258/sonarr.trace.txt)

**Comment by markus101** [comment]
There are breakpoints that change how the page is scrolled when it crosses over into smaller screens, that behaviour is intended and we don't block any scrolling methods, but sometimes the browser reacts funny to change and needs to be reloaded to function properly. It appears to be the case here, when moving from desktop to mobile sizing. No plans to adjust the behaviour at this time, a reload will solve it.

**Comment by kushraj** [comment]
nah, reload does nothing. touch scroll remain unresponsive as before

increasing window width more than required is the only fix
