### ISSUE TITLE
IMDb List

### ISSUE THREAD

**Issue by sang-ook** [Sonarr/Sonarr#4405]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

There's already issue about this topic but it's closed so I would like to point it out again.

**Describe alternatives you've considered**

None.

**Additional context**

No.

**Comment by bakerboy448** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/276

**Comment by sang-ook** [comment]
Yes, it is. As I mentioned it's closed, so nobody can post there anymore...

**Comment by bakerboy448** [comment]
It is locked, not closed.

regardless intentionally opening duplicating issues is extremely poor etiquette.

when an update for that request exists an update will be posted...either via a commit, a pull request, or comment on that issue
