### ISSUE TITLE
Report health issue on services in Settings > Connect

### ISSUE THREAD

**Issue by onedr0p** [Sonarr/Sonarr#4408]
**Is your feature request related to a problem? Please describe.**

I recently had to change my Plex IP and forgot to update the connection info in Sonarr.

**Describe the solution you'd like**

Implement health issues on services we define in Settings > Connect so that we can be warned of any issues with our custom connections.

**Comment by Qstick** [comment]
Do we want the same “Status” logic and fallback as Clients and Indexers here?

**Comment by markus101** [comment]
Yeah, I think keeping it consistent would be good.
