### ISSUE TITLE
Meta info thetvdb Alternate Order 

### ISSUE THREAD

**Issue by LaBoss** [Sonarr/Sonarr#4409]
Hello, it is possible to define which order we want when it is parsing the episodes?

For example The money heist series have the original version and the netflix version
https://thetvdb.com/series/la-casa-de-papel/allseasons/official

https://thetvdb.com/series/la-casa-de-papel/allseasons/alternate

I wanted to use the netflix version and not the original version, is it possible?

**Comment by bakerboy448** [comment]
closing; numerous duplicates...you can search
