### ISSUE TITLE
Allow for the ability to import and export indexer (and download client) configurations

### ISSUE THREAD

**Issue by delize** [Sonarr/Sonarr#4410]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to easily export and import indexer and/or download client configurations.

The reason for this is if I have a complex indexer setup, I would prefer an easier way to add another instance (Example, sonarr, sonarr-4k - and more importantly Radarr in this example) and use an existing indexer configuration rather than set everything up by hand. 

**Describe alternatives you've considered**
I asked in Radarr's support group (and subsequently, I know this doesn't exist in Sonarr either - but I know that you all share PRs via servarr), but it seems the only option is to copy or use the DB itself which could be a nasty hacky solution.

**Additional context**
I am setting up a sonarr/radarr and a sonarr/radarr-4k instance, and I would like to use the custom indexer configuration I have to make sure I don't get hit with potential issues when it comes to ratios and/or download clients and seeding times.

**Comment by delize** [comment]
To follow up to this:

Ideally in a format that can be used on various systems (json, xml, plain text) and be relevant to other *arr's.

**Comment by markus101** [comment]
We do not have plans for importing/exporting from JSON. You can achieve this with the API though.
