### ISSUE TITLE
Wiki Link Typos

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4411]
https://github.com/Sonarr/Sonarr/blob/6c505937dacfa82e965adaaac407c888a1caacce/src/NzbDrone.Core/HealthCheck/Checks/ImportMechanismCheck.cs#L53

`#completed/failed_download_handling` -> `#completed_failed_download_handling`

**Comment by markus101** [comment]
More time to find the correct file in the branch (not the commit) and close the GHI than to fix it.
