### ISSUE TITLE
Flood download client does not import season packs

### ISSUE THREAD

**Issue by onedr0p** [Sonarr/Sonarr#4412]
**Is your feature request related to a problem? Please describe.**

Not sure if bug or feature request. Feel free to update.

Anyways, currently when using the Flood download client it will not import season packs, however it will import single file episodes just fine. 

The current behavior is that they stay in a `Importing` status, no logs are generated as to why they cannot be imported

**To Reproduce**
1. Set up Flood
2. Point sonarr to flood
3. download a season pack
4. watch it not import when completed

**Screenshots**
https://i.imgur.com/joslgSo.png

**Describe the solution you'd like**

Allow Flood download client to import season packs

**Platform Information (please complete the following information):**
 - OS: Ubuntu Focal
 - Docker: Yes
 - mono: 6.12.0.122
 - Sonarr Version: 3.0.5.1144
 - Sonarr Branch: main

@jesec feel free to and any additional comments

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

https://wiki.servarr.com/Sonarr_Troubleshooting#Downloads_and_Importing

Closing given not a FR, likely not a bug, and more than likely a support issue

**Comment by onedr0p** [comment]
@bakerboy448 I have confirm with @jesec this is an issue.

**Comment by bakerboy448** [comment]
Ah gotcha!

Then bud report with all the details would be the route to go :)

**Comment by onedr0p** [comment]
There are no logs about anything related to why they don't import. I don't know what other information I can provide.

**Comment by onedr0p** [comment]
This seems to be working as expected according to the author. I see it as a feature request, but I will open a bug issue instead.

**Comment by Taloth** [comment]
Just edit the top post with the details, no need to reopen another GHI.

**Comment by onedr0p** [comment]
Something is certainly off with a particular release. I have tried about 5 more season packs and they work without an issue. 

Sorry for buggin' you all. @jesec response to me made it seem like an issue with the way Sonarr inteacts with Flood on season packs. Maybe something got lost in translation... I dunno. 

I will go ahead and close this issue and re-open it with trace logs if I see it happen in the future.

**Comment by jesec** [comment]
> Something is certainly off with a particular release. I have tried about 5 more season packs and they work without an issue.
> 
> Sorry for buggin' you all. @jesec response to me made it seem like an issue with the way Sonarr inteacts with Flood on season packs. Maybe something got lost in translation... I dunno.
> 
> I will go ahead and close this issue and re-open it with trace logs if I see it happen in the future.

Naturally when someone came to me and said "Flood don't work with Sonarr", I would think that something went wrong with the integration between Sonarr and Flood. Either Flood does not properly send the directory to Sonarr, or Sonarr does not properly receive it. 

However, apparently the issue happens with only a particular release, as you said.

In that case, it is more likely that there is a problem with that release, and the issue is not really about Flood. 

I will be happy to help if there is indeed something wrong with the integration.
