### ISSUE TITLE
New variable for Post Processing Scripts - sonarr_series_network 

### ISSUE THREAD

**Issue by peskdale** [Sonarr/Sonarr#4413]
**Is your feature request related to a problem? Please describe.**
I want to be able to run certain post-processing scripts based on the network that airs a show. For example, I have a script that trims off the opening logo for a particular streaming network, which I want to run upon download of any series from that network.

**Describe the solution you'd like**
A new environmental variable `sonarr_series_network` that gives the name of the network.

**Describe alternatives you've considered**
I have considered manually tagging these series, and triggering the script to run for that tag only. However, this requires upkeep to tag any new series that are later added, and can also conflict with my other post processing scripts depending on run order. 

Similarly, I have considered having my script look for specific series names, but again this requires upkeep as new series get added.

The information is already present within the Sonarr web interface, so additional tagging seems like an unneeded exercise.

**Comment by Taloth** [comment]
You can call the Sonarr api to get such information. Just use the series id and query the series api endpoint.

I don't want to add every bit of information in environment variables.
