### ISSUE TITLE
Cloning Indexers copies unusable categories without a way to remove them 

### ISSUE THREAD

**Issue by Getn67** [Sonarr/Sonarr#4415]
Support Requests will be closed immediately, if you are not 100% certain this is a bug please go to our Reddit, Discord, Forums, or IRC first. Exceptions do not mean you found a bug! -->
**Describe the bug**
UI bug when cloning indexer to a differing category scheme. Cloning pulls the old categories to the new indexer page, and unless the categories are removed before editing the URL, the categories stay making the indexer fail on save in some cases.

**To Reproduce**
1. Go to indexer settings
2. Clone an indexer (I used Zooqle)
3. Change URL to create a new indexer that uses a different category scheme than the first (I used rarbg)
4. When checking the categories list, you will notice that the old categories are left behind. This keeps the indexer from functioning when it can't use the categories.

**Expected behavior**
I expect changing a URL in the modal will clear out existing categories when using the clone function to create a new indexer listing.

**Screenshots**
![image](https://user-images.githubusercontent.com/51862012/112759404-ad9d2700-8fa7-11eb-8bca-f272456a5a6a.png)

**Platform Information (please complete the following information):**
 - OS: Unraid 6.9.1
 - Docker: Yes. LinuxServer.io image: 3.0.6.1195-ls150
 - Mono 6.12
 - Browser and Version Chrome 89.0.4389.90
 - Sonarr Version: 3.06
 - Sonarr Branch: develop

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
https://pastebin.com/qxZFHbc0

**Comment by Taloth** [comment]
We intentionally don't reset categories when urls are changed, because the backend doesn't know whether the url is correct, and whether the categories were properly fetched from the indexer api (some require api keys to do so) and whether the categories are the fallback default newznab ones.

Modifying the categories will clear the unknown ones automatically. So you can remove the extra categories by simply toggling one of the present ones.

**Comment by Getn67** [comment]
With that being the case, you can see in my screenshot that the extra categories have not been removed. I have toggled categories, and the "dead" ones persist.

**Comment by bakerboy448** [comment]
That seems unlikely...

you need to open up the categories, which should trigger the cap call and then toggle one which will update them accordingly

**Comment by Getn67** [comment]
I've listed a few screenshots that (hopefully) show what I'm seeing. I have gone and toggled categories, and there are still leftover listings in the modal. (I hope I used the term 'modal' correctly. Let me know if I'm mistaken)

Before edits
![before](https://user-images.githubusercontent.com/51862012/112765594-b6e7bd00-8fc2-11eb-8b0e-5ca34f368ae3.JPG)
Category list before any changes
![catbefore](https://user-images.githubusercontent.com/51862012/112765603-be0ecb00-8fc2-11eb-8daa-f8524d183c4f.JPG)
Category list changes (I chose those two to show that I have both toggled on, and toggled off categories)
![catafter](https://user-images.githubusercontent.com/51862012/112765606-c2d37f00-8fc2-11eb-8720-a23c0e823db7.JPG)
Results
![after](https://user-images.githubusercontent.com/51862012/112765608-c7983300-8fc2-11eb-8067-87b6779da444.JPG)

You can see that in the results 5070 and 5080 are still listed despite having changed the categories, and despite not being recognizable by rarbg.

**Comment by Qstick** [comment]
You can uncheck and recheck the parent and they vanish

**Comment by Getn67** [comment]
You can see in the screenshot that I am not using any child categories in my steps. The categories I am using do not have a parent category that they are under. I'm not sure if I am missing any needed information, but I feel like I have been pretty clear in the steps that I have taken to show how this issue presents itself.

**Comment by Qstick** [comment]
They do though, 5000 series categories would parent to TV even though they aren't in list.

It works, trust me. I called it out as counter intuitive just the same when we pulled it to Radarr, before I knew exactly how to get it to clear.

I'll upload a gif later that I made a while back for another user if you can't figure it out.

**Comment by Qstick** [comment]
> That clarification clears things up for me quite a bit. It sucks that there isn't something to indicate how that works just yet though.

Yea I agree with you, it's not the clearest thing to figure out.
