### ISSUE TITLE
Sonar run is the minimum requirement required

### ISSUE THREAD

**Issue by zhenghaiyang** [Sonarr/Sonarr#4419]
Sonar helped me solve a lot of problems.
My friend's computer has 2G of memory, We're not running Sonar. My friend's update computer 4G of memory, running Sonar.
I have a feeling that it's not running Sonar because of memory. 
But I don't know that the Sonar run is the minimum requirement required?

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
