### ISSUE TITLE
Feature: Declerative configuration

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [Sonarr/Sonarr#4421]
Feature:
I'd love to see the declarative configuration of some sort instead of database files

Implementation:
json/yaml/toml/anything - just a file that would get updated instead of databases

Reasoning:
In most cases, at least generic ones like indexers/downloads configuration database schemes are not providing much if any advantages. Instead using a basic configuration file provides multiple conveniences:
1. Versioning is easy - just create a git repo
2. Sharing/Searching configuration is easy - Github search is great for that
3. Simplifies issue reproducibility
4. Backups are easy
5. Screwed something up and not sure what's wrong? Just do `git restore -p` 
6. Makes automated configuration/integration possible
7. Simplifies schema versioning since its just a couple of classes instead of relational data
8. Technically faster since IO operations are necessary for initial read and write operations only (nobody is going to notice the difference tho)
8. Declarative configuration is great, simple and I am sure that there are quite a few peeps like me that would love to see it implemented

EDIT: Just to clear things out - I do mean for configuration stuff only (basically settings menu). There is no point in setting up downloads tracking or anything similar in such manner. That would do more harm than good

**Comment by markus101** [comment]
We do not have plans to change how config is stored at this time.

**Comment by gytis-ivaskevicius** [comment]
If I were to make a PR for that - it would get rejected straight away as well?

**Comment by markus101** [comment]
Yes, because it's not something we want to support.
