### ISSUE TITLE
Thai and Tagalog as language options.

### ISSUE THREAD

**Issue by chevignon93** [Sonarr/Sonarr#4422]
**Is your feature request related to a problem? Please describe.**
I mostly download TV shows from Thailand and the Philippines and they are always tagged as English as there is no option for Thai and Tagalog in Sonarr.

**Describe the solution you'd like**
I would like Thai and Tagalog to be added to the 'Language List' that Sonarr maintains but also to the 'Language Parser' so that I don't have to manually select the language each time I download a new video.

**Comment by markus101** [comment]
We require examples of release names for both languages to consider if this is possible.

**Comment by markus101** [comment]
We can reopen if examples are provided.
