### ISSUE TITLE
Manual item removal from activity window does not remove from disk

### ISSUE THREAD

**Issue by SpencerXZX** [Sonarr/Sonarr#4423]
**Describe the bug**
Removing a completed item from the activity window using the "Remove Selected" button does not remove files from the disk. It removes it from the download client and from the activity window, but not the disk. 

**To Reproduce**

This can be reproduced by downloading a file that will trigger the 'Not a quality upgrade over existing file' error, or any error that will make a download hang in the activity page and show a yellow icon. Then, check the box next to the item and hit the 'Remove Selected' button, and after it removes it, check your disk and it will still be present.

**Expected behavior**
Files should be deleted when using the remove button from activity web interface.

I included logs for when I manually delete a file, as well as logs for when Sonarr automatically deletes a file, Sonarr automatically properly removes the files from disk, but if I do it manually from the activity page, they stay on disk. 

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Unraid
 - Docker: Yes
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): 5.20.1.34
 - Browser and Version (Only needed for UI issues): Any
 - Sonarr Version: 3.0.6.1196
 - Sonarr Branch: latest

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
[AutoDelete.txt](https://github.com/Sonarr/Sonarr/files/6260904/AutoDelete.txt)
[ButtonDelete.txt](https://github.com/Sonarr/Sonarr/files/6260905/ButtonDelete.txt)

**Comment by markus101** [comment]
Sonarr tells the download client to remove the download as well as the files. I don't know what you mean by "auto delete" and that working, because Sonarr doesn't auto delete files it hasn't imported.

**Comment by SpencerXZX** [comment]
Hi markus, I raised this issue over at SABnzbd first, and they said SAB does not delete files, and pointed me to Sonarr. 

See my issue here: https://github.com/sabnzbd/sabnzbd/issues/1850

**Comment by bakerboy448** [comment]
That behavior described on the SAB GHI makes sense

The edge case not handled are complete usenet downloads that are removed from queue.  Nothing deletes those at present time.  I've seen this before as well it's the cause for periodically needing to scrub your usenet folder

deleting in queue is not complete in SAB logic and sab handles

**Comment by markus101** [comment]
> I raised this issue over at SABnzbd first, and they said SAB does not delete files, and pointed me to Sonarr.

That’s a pretty key piece of information for this issue.

> By auto delete, I was referring to after a successful import.

Gotcha, that’s a completely separate flow (Sonarr moves the file and removes the sub folder) even if Sonarr is set to remove completed downloads.
