### ISSUE TITLE
Media library paths are sometimes not shown when adding a new show

### ISSUE THREAD

**Issue by CombeeMike** [Sonarr/Sonarr#4424]
When adding new shows, the `Path` dropdown often only shows the `Add a different path` option but not the already set up library paths. Using `Add a different path` is not possible in those situations since it tells me something like "path already exists" (not sure about the wording) when I select the path to my library then.

If this happens I usually wait some (random) time & try again later. Usually the entries are then shown. Unfortunately I have no idea how long I have to wait & what actually happens in the background so that the issue "gets fixed".

I have a feeling that this happens more often on my mobile but that might be misleading as I simply add shows more often when I'm on my mobile...

**To Reproduce**
Unfortunately I don't have any reliable reproduction steps as this doesn't happen everytime 🤷‍♂️

**Expected behavior**
The 2 "base paths" should always be shown in the drop down.

**Screenshots**
![image](https://user-images.githubusercontent.com/30658772/113279094-02f87180-92e3-11eb-8cf3-8a0bdf849e3c.png)

**Platform Information (please complete the following information):**
 - OS: `Ubuntu 20.04.2 LTS`
 - Docker: `No`
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): `Mono 6.8.0.105`
 - Browser and Version (Only needed for UI issues): `Firefox 87.0 (64 bit) desktop` & `Firefox mobile 87.0.0-rc.1` at the time of writing
 - Sonarr Version: `2.0.0.5344`
 - Sonarr Branch: `master` (i guess 🤷‍♂️)

**Trace Logs**
Here's a trimmed trace where I was looking for the terms "arrested" & "arrested development". Please let me know if you need the complete log.

[sonarr.trace.20.txt](https://github.com/Sonarr/Sonarr/files/6262778/sonarr.trace.20.txt)

**Comment by Thirrian** [comment]
Probably best to start by upgrading to v3, sonarr v2 is end of life.

**Comment by CombeeMike** [comment]
Interesting! Wasn't aware that I'm on an old major version. I'll give it a shot!
Thanks!

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

**Comment by CombeeMike** [comment]
@markus101 Why is this a support ticket or question? To me it seems like a bug in 2.x even if it might be fixed with the new version (still have to verify that...).

**Comment by Thirrian** [comment]
Because otherwise there would be more reports if something was actually wrong. So I guess it's something specific to your setup that causes issues.

**Comment by CombeeMike** [comment]
Seems to be fixed in v3 👍

@Thirrian "Is no general bug because no one else reported this" seems like a bold claim to me. However, I feel where you're coming from and since it seems to be fixed in v3, I won't argue any further 🤷‍♂️
