### ISSUE TITLE
Allow methods other than RSS for automatic/periodic downloads

### ISSUE THREAD

**Issue by scatter-dev** [Sonarr/Sonarr#4425]
**Is your feature request related to a problem? Please describe.**
For a particular show, its indexer gives all the content that has been uploaded (read: a lot of content) to the RSS feed. This leads it to miss the new episodes of this show often (I've actually only seen it automatically download once in the 3-4 months I've been using Sonarr), and it's borderline impossible to backpage to it if Sonarr wasn't running when the new episode was uploaded. This means, in order to download the new episodes of this show, I have to go into the Wanted tab and click the Search button myself.

**Describe the solution you'd like**
It seems pretty straightforward to automate this. Add a feature that will, every x amount of minutes, try to grab episodes from the Wanted tab (undownloaded monitored episodes), using the same method as the Automatic Search button. Being able to set this on a per-show basis would be ideal.

**Describe alternatives you've considered**
The alternative is I go to the Wanted tab and click a button every day. It's not that hard, but it'd be nice not to have to. This is currently the only manual interaction I ever have with Sonarr.

It's possible that the episodes not downloading automatically is due to a different problem than the RSS feed being overloaded, but I'm fairly sure that's what's going on.

**Comment by markus101** [comment]
In order to catch most releases Sonarr needs to be running 24/7. With a 15 minute interval and correctly configured categories it’s rare things are missed.

At this time we do not have plans for automatic backlog searching. If you want to troubleshoot missed episodes please use one of our support channels.
