### ISSUE TITLE
Feature Request: Failed Download Retry Priority

### ISSUE THREAD

**Issue by WebAddict** [Sonarr/Sonarr#4426]
Requesting new setting for Failed Download > Retry Priority.

Sonar generally adds all episodes of entire shows (or seasons) to the DL Client together, all eps in a row in low priority (for eps older than 14 days). This means an entire show is usually attempted all together in about the same time within a few minutes or hours of each other. But some/many episodes may be incomplete, and must be retried. Sonarr will retry failed downloads (when enabled) but the retry priority is based on the same 14 day rule. Adding these retry episodes to the END OF THE QUEUE.

I assume many of our Sonarr users are like me, adding shows faster than they can come down... Someone might have 1,000 to 10,000 queued items in the download client. Now a retry-item might take another few weeks to come down unless manually moved to the front of the queue.

![2021-04-07_14h50_10](https://user-images.githubusercontent.com/2932390/113941614-499f0d80-97b4-11eb-8c0e-bb7987cdf909.png)

This Requested Solution of custom Priority would move retry episodes to the TOP OF THE QUEUE (high or normal priority), and the entire show will generally become available all together. Instead of MISSING EPISODES all over the place.

I use High Priority for Recent Eps, and Low priority for Older Eps. I would like to select Normal Priority for these Retry Downloads.

Last consideration: Should default to the HIGHEST selected priority between the 14 day priority rules and Retry Priority. Then recent episodes would retry using the same HIGH priority instead of my selected NORMAL priority for regular retries.

Setting to be added to:
Settings > Download Client > Failed Download Retry Priority

![2021-04-07_15h17_54](https://user-images.githubusercontent.com/2932390/113941718-7c490600-97b4-11eb-9f5b-7fcf750678bb.png)

Use the same Form Pull Down Options as Recent Priority or Older Priority.

Thank you developers for the awesome software that we all love and use regularly! I'm a programmer too...

Note I did read the Github Open Request: [Feature: Failed download retires priority #4237](https://github.com/Sonarr/Sonarr/issues/4237)
But that didn't match my use case. I think my described use case would make a lot of people happy!

**Comment by fryfrog** [comment]
Have you tried enabling the sabnzbd option that automatically sorts by *age*? I think you could get really close to your goal that way, since retries are *mostly* going to come from the same usenet era. It won't *quite* be perfect, but it'd be closer than anything else I think.

**Comment by markus101** [comment]
It's an interesting idea, but I think the number of users that would utilize this functionality (as well as the number of clients that support more granular priorities) is low because most people don't have thousands of items queued most of the time.

This isn't something we have plans to implement at this time, but we'll tag it to re-evaluate it later.
