### ISSUE TITLE
Support listening on a unix socket

### ISSUE THREAD

**Issue by kevincox** [Sonarr/Sonarr#4427]
**Is your feature request related to a problem? Please describe.**
Right now Sonarr only supports listening on IP sockets. This means that all processes on the local system (other than sandboxed processes) can access Sonarr. This raises attack surface and can leak information if no authentication us used. 

**Describe the solution you'd like**
Sonarr should support binding to a unix socket instead of an IP socket. 

**Describe alternatives you've considered**

You can get similar security using firewall rules but this creates an overhead for all IP traffic on the system and configuring firewalls are complex and mistakes can easily break a system as they apply too all traffic on a system.

You can also use basic auth on Sonarr and provide the passwords to the clients. You could also pair this with a reverse proxy doing it's own auth before sending basic auth to Sonarr. This works but is much higher complexity.  

**Additional context** 

This is also good for handling auth in the reverse proxy as you can set the ACL on the socket so that only the reverse proxy can access it. This way there is no need to set up auth on Sonarr itself where as currently you would want to have SSO or other auth managed on the reverse proxy as well as auth between the proxy and Sonarr to ensure that other users or compromised services can't access the Sonarr port. 

unix sockets also have better performance than TCP which is a nice additional benefit.

**Comment by markus101** [comment]
At this time we we do have have plans to support unix sockets for connecting to Sonarr.
