### ISSUE TITLE
Quality Profiles not possible to be dragged and dropped on Mobile

### ISSUE THREAD

**Issue by RobinDadswell** [Sonarr/Sonarr#4429]
**Describe the bug**
Reorganizing qualities within a profile is not possible on a mobile device (tested on Safari/Edge on iOS) 

**To Reproduce**

Qualities possible to drag and drop into the order you want

**Platform Information (please complete the following information):**
 - OS: Windows 10 20H2 - iOS as issue platform
 - Docker: No
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): .net 4.8.0
 - Browser and Version (Only needed for UI issues): Edge on iOS 46.3.5
 - Sonarr Version: 3.0.6.1196
 - Sonarr Branch: main

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
No logs for this as is client end and not server side

My JS skills may not be good enough to fix this myself so would appreciate it if someone can take a look

**Comment by Thirrian** [comment]
Same with languages profiles.

**Comment by bakerboy448** [comment]
any relation to https://github.com/Sonarr/Sonarr/issues/4403

?

**Comment by markus101** [comment]
No, they're not related at all.

**Comment by markus101** [comment]
Closed in https://github.com/Sonarr/Sonarr/commit/684626ef73b13f0b5b50aa60c4f2be11c918e019
