### ISSUE TITLE
Sonarr should use a good password hash and salt.

### ISSUE THREAD

**Issue by kevincox** [Sonarr/Sonarr#4430]
**Describe the bug**

[Looking at the code](https://github.com/Sonarr/Sonarr/blob/90697d77a544549fa43f56f0b4418413b6bad2d9/src/NzbDrone.Core/Authentication/UserService.cs#L35-L44) it appears that Sonarr currently stores the SHA256 hash of the authentication password. This is not great some of the issues are:

- SHA256 is a fast hash.
- There is no salt.

Sonarr should use a proper password hashing algorithm with salt to prevent brute force attacks and rainbow tables.

**Comment by bakerboy448** [comment]
Slightly related https://github.com/Sonarr/Sonarr/issues/1461

deferring to Markus but I foresee this as being closed with no plans.

for external/internet access one should setup a reverse proxy with a well regarded security mechanism. This is also why forwarding the ports for access is not advised.

think of sonarr's auth as just locking the front door...meant to keep some folks out, such as on a LAN.

**Comment by kevincox** [comment]
I saw https://github.com/Sonarr/Sonarr/issues/1461 but it seemed to be talking about tracker API keys not the Sonarr password.

This issue is actually less related to Sonarr's auth as it isn't protecting much if local files can be accessed anyways. This is more to treat the password as a sensitive secret as the user may be reusing a password that they used elsewhere (obviously not a good idea). 

I agree that this isn't really a huge issue for security but it is also fairly easy to do correctly.

It is also worth noting that this is really the only way to protect Sonarr on a multi-user system as anyone can connect to the port directly. It isn't much of an issue for me as I have strong authentication on my reverse proxy and a random password between the reverse proxy and Sonarr but it would still be good to handle correctly.

**Comment by Taloth** [comment]
I think we can tack something on. I do think the benefit is minimal though. Considering most users have passwords that are brute forced with ease in the cloud. Rainbow tables aren't useful for longer passwords either. Salting definitely defeats them, but RBT were really intended for shorter passwords before the advent of cloud compute.

**Comment by markus101** [comment]
This will be done in v4.
