### ISSUE TITLE
Releases are grabbed/downloaded even though they aren't quality revision upgrades

### ISSUE THREAD

**Issue by Hossy** [Sonarr/Sonarr#4431]
**Describe the bug**
Sonarr is grabbing releases for download even though the importer will reject those releases for not being a quality revision upgrade.

**To Reproduce**
1. Confirm File Management > Propers and Repacks is set to Prefer and Upgrade
2. Have an existing episode that is a proper without a preferred word
3. Discover a release through Rss Sync that is the same quality, not a proper/repack, but has a preferred word
4. The release will be grabbed and sent for download
5. When the download completes, the queue item will be flagged orange with "Not a quality revision upgrade for existing episode file(s)"

**Expected behavior**
The release should not be grabbed when the Propers and Repacks setting is "Prefer and Upgrade" as this indicates that propers are preferred over preferred words.  The only exception to this is if the release had a preferred word and was also a proper (in the example above).

**Platform Information (please complete the following information):**
 - OS: Synology DSM running linuxserver/sonarr:latest
 - Docker: Yes
 - Mono 5.20.1.34
 - Chrome 89.0.4389.90
 - Sonarr Version: 3.0.6.1196
 - Sonarr Branch: main

**Trace Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6288980/sonarr.trace.txt)
There are two examples currently:
 - New.Amsterdam.2018.S02E06.Righteous.Right.Hand.WEBRip.1080p.DD.5.1.H265-d3g
 - Game.of.Thrones.S05E07.The.Gift.BluRay.10Bit.1080p.Dts-HD.Ma5.1.H265-d3g

**Comment by markus101** [comment]
We're going to need to see the logs from the grab as well.

**Comment by Hossy** [comment]
I'm not sure I can get those logs with the current retention period.  The debug and trace logs (with 50 rolling files) only span about 5 hours, so the odds of me catching that are next to nothing.  Can you tell me how to increase the retention?

**Comment by markus101** [comment]
That's the maximum number of files Sonarr will store.

**Comment by Hossy** [comment]
Thanks, @markus101!  Is this tied to a specific version release yet or do you know what that version will be?

**Comment by bakerboy448** [comment]
3.0.6.1205
