### ISSUE TITLE
Pull Radarr Commit 'New: End Jackett 'all' endpoint support'

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4437]
# Pull Radarr Commit 54c914d48fefa730728518d50fc9e49032d0947b

**Is your feature request related to a problem? Please describe.**

The Jackett `/all` endpoint serves no benefit and causes support headaches
**Describe the solution you'd like**

As discussed
- add validation to indexer URLs against `/indexers/all/` or `/indexers/all/results` (reference per jackett readme the access is `/api/v2.0/indexers/all/results/torznab`)and fail validation (with a message of: 'URL Validation Failed: It appears you are trying to use the Jackett /all endpoint which always causes problems. [See this FAQ entry for details](https://wiki.servarr.com/Sonarr_FAQ#jackett_all_endpoint).
- eventually add a healthcheck warning for the same
**Describe alternatives you've considered**

Do nothing and enjoy frequent support needs
**Additional context**

**Comment by markus101** [comment]
Going to start with validation, we can revisit the health check later on.

**Comment by bakerboy448** [comment]
Known partial Jackett /all URLs

[`/torznab/all/api`](https://discord.com/channels/383686866005917708/383688189941907459/831179055679275068) sourced from User's Logs

`/api/v2.0/indexers/all/results/torznab` sourced from jackett's readme
