### ISSUE TITLE
Sonarr generating 401 errors in logs

### ISSUE THREAD

**Issue by Whisper40** [Sonarr/Sonarr#4439]
**Describe the bug**

After 2 hours looking for the source of the 401 errors I had in the logs, I found that Sonarr, every minute or so made a request to rtorrent.
The problem is that this request returns a 401 while the connection between rtorrent and sonarr is OK.

This is what I can find in the traefik logs: 
```
141.101.105.79 - - [12/Apr/2021:17:31:04 +0200] "POST /RPC2 HTTP/1.1" 401 17 "-" "-" 9048 "rutorrent_me-router@docker" "-" 0ms
141.101.104.220 - - [12/Apr/2021:17:31:19 +0200] "POST /RPC2 HTTP/1.1" 401 17 "-" "-" 9093 "rutorrent_me-router@docker" "-" 0ms
162.158.111.206 - - [12/Apr/2021:17:32:34 +0200] "POST /RPC2 HTTP/1.1" 401 17 "-" "-" 9233 "rutorrent_me-router@docker" "-" 0ms
141.101.104.220 - - [12/Apr/2021:17:32:49 +0200] "POST /RPC2 HTTP/1.1" 401 17 "-" "-" 9274 "rutorrent_me-router@docker" "-" 0ms
```

I currently have radarr running next to it without generating errors in the logs and it too is connected to the same rtorrent.
Sonarr is the only application that produced these errors, because when I stop sonarr, the errors do not appear anymore.

sonarr logs : 
```
[Info] RssSyncService: RSS Sync Completed. Reports found: 61, Reports grabbed: 0 
[Info] Auth: Auth-Unauthorized ip 108.162.229.143 url 'http://me-sonarr-server.domain.me' 
[Info] Auth: Auth-Unauthorized ip 141.101.69.222 url 'http://me-sonarr-server.domain.me/favicon.ico?h=ZX67/60OXHGhAQ+8myebHg' 
[Info] Auth: Auth-Success ip 108.162.229.121 username 'me' 
```
**To Reproduce**

The connection between rtorrent and sonarr is working, so i should not have any 401 each minute in my logs
**Screenshots**

**Platform Information (please complete the following information):**
[Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/Sonarr.exe - Version 3.0.6.1196 
Docker installation

**Trace Logs**
No any 401 error while trace log was activated.. ( tested during 10 minutes )

**Comment by bakerboy448** [comment]
- Assuming these are all on the same server, don't connect through your reverse proxy there is 0 need for it and it adds a single point of failure.

The connection between rtorrent and sonarr is working, so i should not have any 401 each minute in my logs

- Causation != Correlation; you can verify 

- Not a bug, 401 means likely there's an improper configuration with your setup and RP auth. 

- if there was an issue, and the connection was failing, sonarr would be logging one or more errors

regardless not a sonarr issue

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

**Comment by Whisper40** [comment]
I need to use my reverse proxy to access to sonarr, because there is multiple other sonarr.
I'm not using the traefik auth, but only the sonarr auth on the app. (form)
Traefik is just serving the content no more.
Sonarr produces the error, not radarr.. (same configuration for those apps)

**Comment by bakerboy448** [comment]
Reverse proxy between sonarr and the client to clearify.

but sounds like a traeflick issue then if it's giving out 401s when there's is nothing to auth and more importantly sonarr isn't complaining.
