### ISSUE TITLE
Links to Sonarr force login, direct URL entry do not. 

### ISSUE THREAD

**Issue by OFark** [Sonarr/Sonarr#4440]
**Describe the bug**
Create a `<a href>` link to Sonarr, click it, and Sonarr will redirect you to the login page, regardless of if you have a valid authentication cookie. You can knock off the login/returnurl part and it'll carry on without actually requiring a login.
However, if you copy/paste a URL into Chrome it doesn't ask for login. 

So for this example, I could be using a Chome plugin that creates links in IMDB (for example) the link is fine, the a tag is fine, but Sonarr asks for Authentication when it's not necessary.

I know they're separate project but for reference, this is not a problem with Radarr.

**To Reproduce**
1. Create a link on another website, to Sonarr. 
2. Click on link
3. See the authentication page when it's not required.

**Expected behaviour**
No authentication screen when the authentication cookie is present no matter the source.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Window 10 
 - Version: 3.0.2.4552
Package Version: 3.0.2.4552-ls98 by linuxserver.io
.NET Core: Yes (3.1.10)
Docker: Yes
Branch: main
 - Browser and Version (Only needed for UI issues):  Chrome: 89.0.4389.114 (Official Build) (64-bit)

**Trace Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6298287/sonarr.trace.txt)

Checkout 21-4-12 17:17:52.8 That's where it starts.

I pulled up Chrome's debug too and the response header for the request is coming back 303
Response Headers:
content-length: 0
content-type: text/html
date: Mon, 12 Apr 2021 16:21:18 GMT
location: /login?returnUrl=/add/new/Jupiter's Legacy
server: nginx/1.18.0
x-application-version: 3.0.6.1196

The request looked like this:
General:
Request URL: https://sonarr.[redacted]/add/new/Jupiter's%20Legacy
Request Method: GET
Status Code: 303 
Remote Address: [redacted]:443
Referrer Policy: strict-origin-when-cross-origin

**Comment by markus101** [comment]
This is due to the cookie policy on `SameSite=Secure`, which Radarr is not setting, previously GHI: https://github.com/Sonarr/Sonarr/issues/4365

Re-reading we want this to be `Lax` which will allow the cookie to be sent when linked to from a third party site.
