### ISSUE TITLE
Do not monitor future seasons option

### ISSUE THREAD

**Issue by undead9786** [Sonarr/Sonarr#4443]
**Describe the problem**
No option to have a series monitored but not monitor new seasons (such as Top Gear)
I only want to keep searching for previous monitored seasons that had the old cast but it is still an ongoing series. I want to keep checking them but anytime there is a new season I need to go back and unmonitor.

**Describe the solution you'd like**
Have an option to have future seasons unmonitored by default.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bakerboy448** [comment]
Monitoring works top down; if a higher level item is not monitored then a lower level item will not be
series
season
episode

this optional already exists; closing
![image](https://user-images.githubusercontent.com/55419169/114803574-4c29d600-9d65-11eb-81bd-046f54240536.png)
