### ISSUE TITLE
Sabnzbd issue - Couldn't remove item x: Error response received from SABnzbd: 

### ISSUE THREAD

**Issue by jjbrunton** [Sonarr/Sonarr#4445]
I'm currently getting a large amount of messages in the event log within Sonarr when communicating with Sabnzbd, it is trying to remove a bunch of non existent (already imported) nzbs from Sab.

**To Reproduce**
- Manually / automatically search for episodes and wait for a grab to Sabnzbd
- Wait for the download to complete and then some time after for the import
- Notice eventually you get a message informing you (within the event log) that it was unable to remove the item from sab

**Expected behavior**
Sonarr not to spam the error messages within the log

**Screenshots**
![image](https://user-images.githubusercontent.com/8502823/114943977-c0847800-9e3e-11eb-9b78-42697bf90525.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 19
 - Docker: Yes
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): 
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6321351/sonarr.trace.txt)
6.12.0.122
 - Browser and Version (Only needed for UI issues): Chrome
 - Sonarr Version: 3.0.6.1207
 - Sonarr Branch: develop

**Trace Logs**
Trace log attached
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6321351/sonarr.trace.txt)

**Comment by bakerboy448** [comment]
Those logs are not the correct file

**Comment by jjbrunton** [comment]
Apologies, here's the log:
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6321350/sonarr.trace.txt)

**Comment by bakerboy448** [comment]
logs seem normal on the sonarr side; i'd defer to the sab trace logs and seek out sab support

**Comment by jjbrunton** [comment]
I'm trying to get an end to end flow in the logs as currently I can only see the spam Sonarr is sending to SAB in the logs.

Shouldn't this be more defensive? i.e if Sonarr asks SAB to delete a non existant NZB, shouldn't this drop off the Sonarr tracking instead of just hammering the SAB API over and over again?

**Comment by markus101** [comment]
Sonarr's queue is built from the queue and history responses of the download client. If you tell Sonarr to remove an item and it is failed to be removed from the download client Sonarr does not ignore it, the same is true if Sonarr is automatically removing them after import. If you tell Sonarr to ignore the download without removing it then it will ignore it. Masking the failed deletion by ignoring it solves the errors in the logs, but does not solve the error, we're not going to fix the symptom when the problem should be addressed.
