### ISSUE TITLE
Queue shows 1 item, but there is nothing in there

### ISSUE THREAD

**Issue by pven** [Sonarr/Sonarr#4446]
**Describe the bug**
My SABnzbd-queue is empty, but Sonarr shows 1 item in there. Did not restart yet, first wanted to log this issue.

**To Reproduce**
1. Go to Activity Queue

![2021-04-16 09_19_16-Queue - Sonarr](https://user-images.githubusercontent.com/671621/114987242-3c111400-9e95-11eb-825a-15c3639e6461.png)

**Expected behavior**
Empty queue

**Platform Information (please complete the following information):**
 - OS: Synology DSM 6.2
 - Docker: No
 - mono: 5.20.1.34
 - Sonarr Version: 3.0.6.1196
 - Sonarr Branch: main

**Comment by markus101** [comment]
Without logs of the network requests there isn't going to be anything we can do to investigate. If the item shows up after refreshing the page the responses from `/api/v3/queue/status` and `/api/v3/queue` would be helpful.

**Comment by markus101** [comment]
The likely cause of this is the queue status updates, but the UI doesn’t receive the update for some reason, going to the queue should refresh that information as well to clear it up.

**Comment by pven** [comment]
I did nothing to solve this, and it is ok now. When it happens again, I'll log a new issue and provide the requested logging.

**Comment by markus101** [comment]
We're going to make a change that should address this.
