### ISSUE TITLE
Sonarr not download available episodes automatically

### ISSUE THREAD

**Issue by MaddionMax** [Sonarr/Sonarr#4447]
Hi!

Sonarr don't want to download new episodes. To make it show what happen, I choosen a TV show.
In the log you can see, not found any new episodes, but if you check on the screenshot, there is a new episodes what is perfect to download.

What should I check or do?

Version: 3.0.6.1196
.net Version: 4.8.0
Branch: master

![image](https://user-images.githubusercontent.com/36500454/115109003-b4e69d80-9f73-11eb-93ee-0635620ddf6e.png)

21-4-17 11:48:03.9|Info|NzbSearchService|Searching 3 indexers for [The Man in the High Castle : S01]
21-4-17 11:48:04.4|Info|DownloadDecisionMaker|Processing 9 releases
21-4-17 11:48:04.9|Info|NzbSearchService|Searching 3 indexers for [The Man in the High Castle : S02]
21-4-17 11:48:06.0|Info|DownloadDecisionMaker|Processing 8 releases
21-4-17 11:48:06.0|Info|NzbSearchService|Searching 3 indexers for [The Man in the High Castle : S03]
21-4-17 11:48:08.0|Info|DownloadDecisionMaker|Processing 7 releases
21-4-17 11:48:08.0|Info|NzbSearchService|Searching 3 indexers for [The Man in the High Castle : S04]
21-4-17 11:48:10.0|Info|DownloadDecisionMaker|Processing 35 releases
21-4-17 11:48:10.8|Info|SeriesSearchService|Series search completed. 0 reports downloaded.

**Comment by MaddionMax** [comment]
If I use manually the interactive search, Sonarr download the episode in 720p, but it's not accepted by the rules under profile.

![image](https://user-images.githubusercontent.com/36500454/115109455-190a6100-9f76-11eb-81b6-d070783c1e1c.png)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.


Please see our [FAQ](https://wiki.servarr.com/Sonarr_FAQ for understanding how Sonarr works
