### ISSUE TITLE
[CRC32] being interpreted as [Group]

### ISSUE THREAD

**Issue by g4m3r7ag** [Sonarr/Sonarr#4449]
**Describe the bug**

Upon import, the part of anime filenames that is [CRC32 hash] is being interpreted as the release group, so the imported file name has the CRC hash in the release group location. 

In the example from the logs below the release folder/file name is 

[iKaos] [SoM] Dragon Ball Z COMPLETE (001-291) - Dragon Box Merge - Multi-Audio [v3]/Dragon Ball Z.001.DBOX.480p.x264-iKaos [v3] [6AFFEF6B].mkv 

The imported filename is 

Dragon Ball Z (1989) - S01E01 - 0001 - The New Threat [SDTV v3][8bit][x264][FLAC 1.0][JA+EN]-6AFFEF6B.mkv

**To Reproduce**

Import an Anime episode that has [CRC hash] at the end of the name with release group in the Sonarr naming scheme. 

**Expected behavior**

Release group to be properly determined, I realize this is a tall order when it comes to Anime. 

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker: Yes (hotio)
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): 6.12.0.122
 - Browser and Version (Only needed for UI issues): 
 - Sonarr Version: 3.0.6.1207
 - Sonarr Branch: phantom-develop

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6338356/sonarr.trace.txt)

**Comment by g4m3r7ag** [comment]
Per discussion on Discord, this appears to be due to the bad naming convention used on the release and is not something that can really be fixed. Closing issue.

**Comment by markus101** [comment]
The naming is absolute trash, but we can prevent it from choosing the CRC32 as the release group at least.
