### ISSUE TITLE
Disable TheXEM Scene Mapping

### ISSUE THREAD

**Issue by halsafar** [Sonarr/Sonarr#4450]
**Is your feature request related to a problem? Please describe.**
TheXEM Scene Mapping is great when it works and is beyond frustrating when it doesn't.  Case in point, American Dad.  Sonarr constantly downloads the wrong season.  Sure, the tvdb folks can argue until they are blue in the face, some consider the current season to be S18 but the scene mapping forces it to search S17.  

**Describe the solution you'd like**
Let us turn this off.

**Describe alternatives you've considered**
Blocking thexem host in the docker container running Sonarr.

**Additional context**
I don't want this to turn into some war about holistic TV listings.  I don't care how a season gets listed but let me decide if I want to have it scene mapped or not.

I'm well aware of the multiple locked requests for this across github and reddit.

**Comment by bakerboy448** [comment]
Closing; Dupe has OP has pointed out, thanks

one of said dupes
****
