### ISSUE TITLE
endless loop between propers and non-propers with higher preferred word score

### ISSUE THREAD

**Issue by glc650** [Sonarr/Sonarr#4454]
**Describe the bug**
See screenshot below.  Notice the release with a preferred word score of +6.  This has already been downloaded and imported (hence the red "!") so everything should stop here (unless a release with a score higher than +6 appears) but instead Sonarr grabs one of the propers with a score of +3 (notice how there is no red "!" beside them).  Once that gets imported Sonarr then grabs the release with a score of +6 again.

**To Reproduce**
Let Sonarr and preferred words do their thing.

**Expected behavior**
If a proper is available before a release with a higher word score then it should download.  But once a release with a higher preferred word score is available, downloaded, and imported, a proper (no release) with a lower score shouldn't be downloaded.

**Screenshots**
<img width="1392" alt="Screen Shot 2021-04-21 at 4 47 54 PM" src="https://user-images.githubusercontent.com/6758825/115637356-d4a7f980-a2c4-11eb-8064-074aee1bccd2.png">

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): Mono 5.20.1.34
 - Sonarr Version: 3.0.6.1196
 - Sonarr Branch: main

**Trace Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6354577/sonarr.trace.txt)

**Comment by bakerboy448** [comment]
not a bug

> Download Proper & Repacks
https://wiki.servarr.com/Sonarr_Settings#File_Management

https://wiki.servarr.com/Sonarr_FAQ#how_are_possible_downloads_compared

Propers and Repacks are considered quality

https://trash-guides.info/Sonarr/V3/Sonarr-Release-Profile-RegEx/#propers-and-repacks

**Comment by markus101** [comment]
Also https://github.com/Sonarr/Sonarr/issues/4431
