### ISSUE TITLE
Speeding up the manual import modal

### ISSUE THREAD

**Issue by Komic** [Sonarr/Sonarr#4458]
As my library keeps growing, the manual import modal gets more and more unusable. The scanning time by itself is pretty slow (that makes sense I guess, implementing a toggle to skip matching attempts could make sense here though?), but I'm mostly talking about how sluggish the UI (and my browser!) gets when displaying the whole file list. This thing badly needs pagination. 👍

**Comment by bakerboy448** [comment]
please edit and use the template you either ignored or your third party application you used to open the issue ignored
https://github.com/Sonarr/Sonarr/issues/new?assignees=&labels=&template=feature_request.md&title=

Manual Import won't analyze the files if there are more than 100; however, why do you need to manually import large quantities of data so often?  That seems like you're doing something incorrectly or have an extremely unique setup (likely the former)

**Comment by markus101** [comment]
> implementing a toggle to skip matching attempts could make sense here though

This is already done if the selected folder isn't parsed and matched to a series and it contains more than 100 items.

> This thing badly needs pagination

Definitely not pagination.

We recommend selecting specific job folders instead of a root folder/base of the download folder. What exactly are you trying to select that has hundreds or thousands of files?

**Comment by markus101** [comment]
Will reopen if needed once updated.

**Comment by Komic** [comment]
My apologies for the formatting.

> This is already done if the selected folder isn't parsed and matched to a series and it contains more than 100 items.

That's good to know, thank you!

I understand targeting a sub-folder would be far more efficient, but for a few reasons (I can't control all of them), a few lone files can end up at the root. Some of those can improperly match, hence the manual import. Maybe being able to directly target a file then?
