### ISSUE TITLE
Custom script variable HealthCheck Wiki returns wrong link

### ISSUE THREAD

**Issue by NiNiyas** [Sonarr/Sonarr#4461]
**Describe the bug**
When calling `sonarr_health_issue_wiki` from a custom script, it returns wrong wiki link from Servarr Wiki for `IndexerRssCheck` and `IndexerSearchCheck`.

**To Reproduce**
Create a custom script and call `sonarr_health_issue_wiki`.

**Expected behavior**
It should return the right link.

**Platform Information (please complete the following information):**
 - OS: Windows 10 20H2 build 19042.906
 - Docker: No
 - .net Framework (Windows): 4.8.0
 - Sonarr Version: 3.0.6.1196
 - Sonarr Branch: main

**Trace Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6366994/sonarr.trace.txt)

**Comment by markus101** [comment]
Please provide a link to the trace logs.

**Comment by bakerboy448** [comment]
ditto as Radarr
what's the links that are coming out?

Taloth/Markus - this may need to be a code change to swap in the fragment they should point to various entries (we'll need to create a few it seems) under https://wiki.servarr.com/Sonarr_System#Indexers

**Comment by NiNiyas** [comment]
> what's the links that are coming out?

For `IndexerSearchCheck` it returns `https://wiki.servarr.com/Sonarr_System#no_indexers_available_with_automatic_search_enabled_sonarr_will_not_provide_any_automatic_search_results` and for `IndexerRssCheck` it returns `https://wiki.servarr.com/Sonarr_System#no_indexers_available_with_rss_sync_enabled_sonarr_will_not_grab_new_releases_automatically`

**Comment by NiNiyas** [comment]
> Please provide a link to the trace logs.

Updated the post.

**Comment by NiNiyas** [comment]
Also for `DownloadClientStatusCheck` it returns `https://wiki.servarr.com/Sonarr_System#download_clients_are_unavailable_due_to_failures`

**Comment by bakerboy448** [comment]
> Also for `DownloadClientStatusCheck` it returns `https://wiki.servarr.com/Sonarr_System#download_clients_are_unavailable_due_to_failures`

This is correct in the code.  Fixed on the wiki;  anchors were missing the `s` in `failures`

**Comment by bakerboy448** [comment]
Closing as was resolved with wiki fixes

**Comment by markus101** [comment]
This should be fixed in 021fd4afa70e2e724f3ff3511bda08cf8a3efe0e
