### ISSUE TITLE
Repeated Indexer Notifications if all indexers are down

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4462]
Radarr Xref https://github.com/Radarr/Radarr/issues/6221

**Describe the bug**

Notification received for each and every indexer if using an indexer manager and it's down.

**To Reproduce**

Have all indexers down at the same time

**Expected behavior**

A single "All indexers are down" notification not one notification for each indexer.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS:  Ubuntu 20.04
 - Docker:  No
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status):  6.8.0.105
 - Browser and Version (Only needed for UI issues):  N/A
 - Sonarr Version:  3.0.6.1214
 - Sonarr Branch:  develop

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

https://gist.github.com/bakerboy448/860b5c40a7452c08939dfec1cac4281c

**Comment by markus101** [comment]
This was known when it was implemented, we don’t do aggregations on it, it’s definitely not a bug.

**Comment by markus101** [comment]
Definitely considered and deferred...

https://github.com/Sonarr/Sonarr/blob/a824fa44d21328d9c8bbb1ccfd6d247d4ff5c888/src/NzbDrone.Core/HealthCheck/HealthCheckService.cs#L147

**Comment by davidnewhall** [comment]
Adding my +1
![Screen_Shot_2021-12-11_at_1 15 38_PM](https://user-images.githubusercontent.com/2402929/145691965-8952eff4-a0a4-47ee-93ac-2115cb873180.png)
