### ISSUE TITLE
Explicitly disabled RSS should not generate an error in the UI

### ISSUE THREAD

**Issue by jerblack** [Sonarr/Sonarr#4465]
**Describe the bug**
If I disable RSS in all of my indexers and set RSS sync interval to 0, an error is displayed in the UI about not having RSS enabled. 
"No indexers available with RSS sync enabled, Sonarr will not grab new releases automatically"
I know this though, because this is an explicit choice that I made as the user. I don't use RSS so I turned it off to prevent Sonarr from wasting resources even trying. The fact that RSS is disabled is not an error state, it's a reflection of my wishes as the user. 

The problem with the error being displayed is that it's persistent in the UI, so every time I open Sonarr it looks like something is broken, so I go check and realize that no, it's just the tool complaining that is has a different opinion about it's configuration than I do. 
Please stop reporting this as an error.

![image](https://user-images.githubusercontent.com/5771102/116002366-437ba000-a5ae-11eb-8731-33ea7267354d.png)

 - OS: Debian 10 host, Sonarr Docker container is running Alpine
 - Docker: yes
 -  mono (macOS/Linux) (System -> Status): Mono 6.12.0.122
 - Browser and Version (Only needed for UI issues): Chrome 89.0.4389.128 (Official Build) (64-bit)
 - Sonarr Version: 3.0.6.1196
 - Sonarr Branch: Master, latest version from https://services.sonarr.tv/v1/download/main/latest?version=3&os=linux

**Comment by markus101** [comment]
Covered by https://github.com/Sonarr/Sonarr/issues/481
