### ISSUE TITLE
Enable season MONITORED toggle when series is UNMONITORED

### ISSUE THREAD

**Issue by pgdownload** [Sonarr/Sonarr#4466]
**Describe the bug**
If a series has been marked UNMONITORED then the SEASON tag are still coloured in and indicating MONITORED. Its not possible to toggle the MONITORED status of the season to OFF unless you re-enable SERIES monitoring and then toggle off SEASON monitoring and then disable SERIES MONITORING.

This probably is also the same with EPISODE MONITORING but untried. 

Note that with SERIES MONITORING OFF then SEASON MONITORING is also disabled (as expected) regardless of whether it is tagged MONITORED or not (So functionality is 100% this is more cosmetic)

**Expected behavior**

Two options:

1) If a SERIES is toggled to UNMONITORED then all SEASON and EPISODE tags should switch to UNMONITORED 

or probably better: 

2) If a SERIES is toggled to UNMONITORED then leave SEASON and EPISODE tags active so they can still be toggled by the user (currently disabled)

**Platform Information (please complete the following information):**
QNAP
Latest Sonar 3.0.6.1196
Master Branch

Screenshot: 

https://imgur.com/a/UAJqou3

**Comment by markus101** [comment]
This behaviour is intentional because people would enable season and/episode monitoring and be confused when things were still rejected for being unmonitored. We do not have plans to change this behaviour.
