### ISSUE TITLE
Close modal when clicking besides it

### ISSUE THREAD

**Issue by SonGokussj4** [Sonarr/Sonarr#4467]
**Is your feature request related to a problem? Please describe.**
I think in the 2x version there was a functionality to close search modal windows when clicked next to it.

**Describe the solution you'd like**
When I'm in a series and click on Manual Search of an episode, a modal pops up. When I click anywhere else I want it to go away. Now I need to click on the "Close" or "X" button.

**Describe alternatives you've considered**
ESC is working just fine. I want the same functionality for clicking with the mouse.

**Comment by markus101** [comment]
This is already possible in v3, though there is an unreleased bug fix in develop.
