### ISSUE TITLE
Anime can't be upgraded past first release group

### ISSUE THREAD

**Issue by Evil-Crab** [Sonarr/Sonarr#4468]
**Is your feature request related to a problem? Please describe.**
Because of this specification anime can't be upgraded past the first grabbed release group even when better ones(with the bigger score in the release profile) become available. https://github.com/Sonarr/Sonarr/blob/90697d77a544549fa43f56f0b4418413b6bad2d9/src/NzbDrone.Core/DecisionEngine/Specifications/AnimeVersionUpgradeSpecification.cs 
That makes release profiles pretty useless for the ongoing anime because you're getting stuck with the first release group that uploaded a new episode.

**Describe the solution you'd like**
Make it possible to disable that limitation.

**Additional context**
![image](https://user-images.githubusercontent.com/3776032/116817144-4c97de80-ab65-11eb-9ae8-1957efa490b9.png)
![image](https://user-images.githubusercontent.com/3776032/116817151-54f01980-ab65-11eb-96e3-791019fb7e78.png)
In that particular case, the episode was upgraded to the Erai-Raws(AnimeLab was not recognized as a release group), but after that, it was not upgraded to the SubsPlease even though it has a bigger score in the release profile.

**My setup**
The latest version of Sonnar running in the linuxserver's docker container with Propers and Repacks set to 'Do not prefer' and release profiles from the Trash Guides (with some minor changes to the scores).

**Comment by Taloth** [comment]
Btw. the underlying problem here is that the erai-raw releases are v0 'prerelease' ones. Which triggers the revision upgrade check.
The logic was intended to prevent v2 releases trumping other release groups. This causes problems with the preferred words logic since it's a hard rejection. Instead it should disable the 'revision' part of the quality comparer.

**Comment by markus101** [comment]
This behaviour was changed in response to https://github.com/Sonarr/Sonarr/issues/4066 why should v0 -> v1 (unlabelled) not be considered a version upgrade and get special handling? If you ultimately don’t want a Erai-raws release (especially a v0 one) use must not contain to reject v0 and/or Erai-raws.

**Comment by Taloth** [comment]
Coz there's a preference for SubsPlease, and the rejection is blocking Erai-Raws v0 -> SubsPlease v1.
This has to be changed from a rejection Specification to in the Quality Upgrade logic.

**Comment by markus101** [comment]
Because it is in fact a revision upgrade. All revision upgrades for anime are restricted to their intended release group, same as repacks are, unless we’re going to ignore that logic of repacks/propers are not preferred?

**Comment by Taloth** [comment]
No, 'revision' upgrades between release groups shouldn't be considered revision upgrades at all. That'd cause the quality be considered equal. And in turn the higher Preferred Words score will allow the release to be grabbed.
In the absence of a preferred word, the regular 'is same or lower quality' specification would kick in and reject the release.

**Comment by markus101** [comment]
> No, 'revision' upgrades between release groups shouldn't be considered revision upgrades at all.

Why does it need to be part of a mega specification?
Quality upgrades do not care about different release groups and rules around repacks/versions the separate checks for that can accomplish that and then you're introducing the situation where Sonarr rejects it for being equal and somebody says, "but v2 < v1, why didn't it upgrade?"

Allowing these checks to be ignored when do not prefer propers is enabled (which almost anyone using preferred words is going to do to control things) will solve the problem without having to have a mega specification.
