### ISSUE TITLE
French subtitled Animes (VOSTFR) aren't grabbed in V3

### ISSUE THREAD

**Issue by Wiirlak** [Sonarr/Sonarr#4469]
Hello,

First of all, I know that VOSTFR isn't part of French language since Sonarr 3.0.3.924.
This decision include a problem, that we actually can't grab french subtitled Animes.

**To Reproduce**
Add an Anime and set the desired language to French.

**Expected behavior**
Sonarr should like in V2 have french subtitled animes be grabbed here.
Audio : Japanese
Subtitle : French

**Screenshots**
Nyaa torrents with a basic search : 
![image](https://user-images.githubusercontent.com/36702513/116823758-a1981c80-ab86-11eb-9a22-db565ba3c34b.png)

Sonarr manual search : 
![image](https://user-images.githubusercontent.com/36702513/116823791-d310e800-ab86-11eb-9c39-6a213c9febab.png)
Parsing problem ?

other example on Sonarr: 
![image](https://user-images.githubusercontent.com/36702513/116824323-d659a300-ab89-11eb-87a0-b014fa0c9e11.png)
Wrong -> Audio : Japanese | Subtitle : French

**Further Details**
 - The language of the Anime in Sonarr is "French", I also created a release profile that contain ["vostfr", "subfrench", "french"].
 - VOSTFR can be included in MULTI too, which cannot be put here since MULTI can be anything, even not french.

I understand that VOSTFR is not a language but a subtitle language, but in the current version of Sonarr, it's not possible to grab any anime subtitled in french.

**Solution**
I heard from #3977 that re adding VOSTFR in french parsing is not an option. But in the current state, we don't have an option for *Subtitle language*.
Ideas :
 - Add a subtitle langage option
 - Add subtitle langage to the release langage, in addition to the audio (which is wrong for some Anime like showed before)

**Platform Information (please complete the following information):**
 - Docker: Yes (latest)
 - Sonarr Version: 3.0.6.1196

**Comment by markus101** [comment]
You can allow English in the profile and optionally allow prefer VOSTFR, at this time we don't have plans for subtitle language and will not be treating subtitle language as the release language.
