### ISSUE TITLE
Fails to recognize shows Animaniacs 2020

### ISSUE THREAD

**Issue by GJB85641** [Sonarr/Sonarr#4470]
Does not list Animaniacs 2020 tv show to load new series.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
