### ISSUE TITLE
lobby-music / elevator messages have little value

### ISSUE THREAD

**Issue by jadik** [Sonarr/Sonarr#4471]
I'm frustrated EVERY time I force-refresh the page. The collection of humor-based messages aren't well served after having heard them a single time, and every time there after bears exponentially lessor fun. 

I noticed this, a few years back, and at the time I was able to edit the php/css (main?) page & replace the messaging with something that served to inspire some personal / more intellectually aligned messaging. That capability was removed, at a major version, I believe.

One (probably not the best, but nonetheless) excellent example of some of these good quotes can be found here: https://www.inc.com/lolly-daskal/the-100-best-leadership-quotes-of-all-time.html

Should this not be the best alternative, code-wise, perhaps an option to target a text file with 1-line quote alternatives, could be provided. 

Underlying rationale: We ALL spend our time doing... being.... conscious... Should we fill this time with things of value, perhaps we may better ourselves, and those we love and hold dear.

Thank you for your ongoing efforts. They are GREATLY appreciated, and CERTAINLY VALUED!

FWIW: One of my most favorite leadership quotes comes from one of the most influential leaders in the space of technology, from > 100 years ago: 
"Whether you believe you can, or believe you can't... Either way, YOU ARE RIGHT!!"

many thanks -jadik

**Comment by bakerboy448** [comment]
No plans to change the loading messages....

also they're in this file
https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/frontend/src/Components/Loading/LoadingMessage.js
