### ISSUE TITLE
SignalR over websockets?

### ISSUE THREAD

**Issue by justinkb** [Sonarr/Sonarr#4474]
Is this actually even working? Cannot get this to work at all. It it using longPolling based on what I'm seeing with browser dev tools. Not seeing any websocket activity. Put logging to trace, not seeing anything SignalR related other than the SignalRMiddleware initialization thing

Couldn't reopen original ticket about it, reference below:

_Originally posted by @markus101 in https://github.com/Sonarr/Sonarr/issues/456#issuecomment-395982774_

**Comment by Taloth** [comment]
SignalR uses negotation. afaik it's mostly serverSentEvents or longPolling. It depends on the server OS, client OS and client Browser. In my case on WIndows with backend on linux it uses serverSentEvents.

**Comment by justinkb** [comment]
Ah, okay, that explains a lot. I'm on macos client, linux server, I'll
remove the websockets configuration entirely from my reverse proxy set up
then, if it isn't gonna use it anyway

**Comment by Taloth** [comment]
You should check out what reverse proxy config is required for serverSideEvents. They're basically long running http connections.

If you have further questions, post on our forums or discord. Good luck.
