### ISSUE TITLE
Remote Backup Location other than relative paths under Sonarr's AppData directory

### ISSUE THREAD

**Issue by villieb** [Sonarr/Sonarr#4477]
**Is your feature request related to a problem? Please describe.**
Recently I lost my Sonarr installation including all backups, which meant a re-installation and attempting to remember all shows that I had monitored

**Describe the solution you'd like**
An option in the backup to select any location, not just the relative paths under Sonarr's AppData directory

**Describe alternatives you've considered**
none

**Additional context**

**Comment by bakerboy448** [comment]
Closing; this exists

just type in the absolute path.
