### ISSUE TITLE
same connect type failure blocks others of the same type from firing off

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#4479]
I have multiple 'connect' noitifers in sonarr.
one for slack, one for living room kodi to do gui notifications, and then one for server kodi (headless) - to update library.

i noticed new shows not showing up in kodi and went to debug. 

i saw that the 'ongrab' kodi-living room one was failing then never saw the kodi-server one fire off..  removing the living room kodi notifier fixed the issue. my living room tv is not on all the time (so by proxy kodi isnt running all the time) - which is why it doesnt update and the notification is mainly just to let me know if something is downloading while im watching something.

just like how the slack notifier still fired off after the kodi-living room OnGrab failed I would have expected the kodi-server one to fire off as well. (and it used to). 

**Platform Information (please complete the following information):**
 - Sonarr Version: 3.0.6.1219
 - Sonarr Branch: develop

**Comment by thezoggy** [comment]
logs:
https://0bin.net/paste/KYInrrja#h5oTfCyXVlU5-P8IpGfjzR0OtNYIYgMptlUw6i8VVZJ

**Comment by markus101** [comment]
I've been unable to reproduce this issue, as long as both Kodi connections have notify or update library enabled the connection is attempted for each.

**Comment by thezoggy** [comment]
guessing that is the bug "GUI Notification" was not set on the server because its headless.. but because the tv one does it have it enabled and it failed the gui notification it aborted out on sending the server to notify of update.

seems like these should not be related?
