### ISSUE TITLE
sonnar can't connect to a box with NordVPN connected

### ISSUE THREAD

**Issue by yuriw** [Sonarr/Sonarr#4480]
Steps:

Scenario 1
Box A - Ubuntu 20.04 running transmission and NordVPN
Box B - Ubuntu 20.04 running sonarr 3.0.6.1196

Scenario 2
Box A - Ubuntu 20.04 running transmission and NordVPN and running sonarr 3.0.6.1196 - all on the same box

In sonnar setting have Download Client - Transmission set up

Scenario 1 - 

if NordVPN is not connected, Download Client - Transmission test pass
if NordVPN is connected, Download Client - Transmission test fails

Scenario 2 - 

if NordVPN is not connected, Download Client - Transmission test pass
if NordVPN is connected, Download Client - Transmission test fails

Note: NordVPN has local subnet whitelisted and all connectivity (e.g. `ssh`, `ping` etc.) work with or without  NordVPN connected.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

this is likely a split tunnel, or lack there of issue.

closing:
-No template
-GitHub is not for support issues
