### ISSUE TITLE
sonnar can't connect to a box with NordVPN connected

### ISSUE THREAD

**Issue by yuriw** [Sonarr/Sonarr#4481]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: 
 - Docker: 
 - mono (macOS/Linux) (System -> Status): 
 - Browser and Version (Only needed for UI issues): 
 - Sonarr Version: ]
 - Sonarr Branch: 

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/6444567/sonarr.txt)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

**Comment by yuriw** [comment]
@markus101 I guess you don't want bug reports as yo close them before they can be edited to match your requirements!  Too bad :(

**Comment by bakerboy448** [comment]
> Support Requests will be closed immediately, if you are not 100% certain this is a bug please go to our Reddit, Discord, Forums, or IRC first. Exceptions do not mean you found a bug!
Get started

You were told an hour ago to go to our help methods.

**Comment by yuriw** [comment]
> > Support Requests will be closed immediately, if you are not **100% certain** this is a bug please go to our Reddit, Discord, Forums, or IRC first. Exceptions do not mean you found a bug!
> > Get started
> 
> You were told an hour ago to go to our support help methods.

I was told ?!
By who?  I was entering a bug and collecting logs.

**Comment by yuriw** [comment]
@bakerboy448 

That's it?

`Support Requests will be closed immediately, if you are not 100% certain this is a bug please go to our Reddit, Discord, Forums, or IRC first. Exceptions do not mean you found a bug!
Get started`

How in the world do you know it's not a bug !?

**Comment by bakerboy448** [comment]
A connection time out error is absolutely not a sonarr bug. It is a local networking or configuration issue.

You were told over an hour go explicitly that it was not a bug and to use support methods.

You were told now multiple times that GitHub is not for support.

Please do not continue to spam GitHub.
