### ISSUE TITLE
Support FPS in renaming metadata

### ISSUE THREAD

**Issue by jdfalk** [Sonarr/Sonarr#4482]
**Is your feature request related to a problem? Please describe.**

Recently I started getting 60fps shows, it would be nice to be able to label these shows in the rename so that I know what is 60FPS and what isn't. 

**Describe the solution you'd like**

Either 
1. Add FPS to the full media info (probably a bad idea as it breaks existing expectations)
2. Add another media tag for renaming that contains FPS

**Describe alternatives you've considered**

Manually renaming has issues in that sonarr will automatically correct the names back to the standard format.

**Additional context**

**Comment by bakerboy448** [comment]
No plans to support FPS from MediaInfo at this time.
