### ISSUE TITLE
BlacklistSpecification error when performing interactive search

### ISSUE THREAD

**Issue by kingofzeal** [Sonarr/Sonarr#4487]
**Describe the bug**
When performing an interactive search, some results are flagged as rejected with the following message:

> BlacklistSpecification: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.

This also seems to prevent some episodes (primarily Anime) from being picked up automatically by RSS feed or from an external release push. In many cases, this is the only rejection reason provided.

**To Reproduce**
Perform an interactive search for an episode.

At this time, I do not know exactly what other conditions trigger this message. While it is more noticeable with Anime series such as One Piece or Boruto (due to them not being picked up properly for me as of late), I am seeing it with non-Anime shows as well such as Last Week Tonight and Family Guy. 

**Expected behavior**
Non-concurrent collection access should not result in the rejection of a particular item in the interactive search.

**Screenshots**
![image](https://user-images.githubusercontent.com/4563328/117647179-42bc3f80-b152-11eb-866f-f00ae59d06f2.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 16.04.4
 - Docker: Yes
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): 
 - Browser and Version (Only needed for UI issues): Edge 90.0.818.49
 - Sonarr Version: 3.0.6.1196
 - Sonarr Branch: master

**Trace Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6451441/sonarr.trace.txt)

**Comment by Taloth** [comment]
It's a timing issue during startup. Restart Sonarr.

**Comment by kingofzeal** [comment]
Interesting. That does seem to have removed the reason from the list.
