### ISSUE TITLE
Remove year from search string

### ISSUE THREAD

**Issue by RVX-28** [Sonarr/Sonarr#4493]
**Is your feature request related to a problem? Please describe.**
Search using indexers is ok but the in sonarr the problem was that the site that I used don't include the year in the torrent file.

**Describe the solution you'd like**
By Adding remove year from search string option like in radarr .Will make the search for shows easier and workable for many sites that don't include the year tag.

**Comment by markus101** [comment]
No plans for such an option. If the year is missing Sonarr will need an alias to accurately match it (if it's possible at all dude to conflicts with other series). The FAQ covers how aliases are handled.
