### ISSUE TITLE
Feature Request: Selective Renaming

### ISSUE THREAD

**Issue by DjRicko** [Sonarr/Sonarr#4499]
**Is your feature request related to a problem? Please describe.**
The option to turn on renaming only for certain shows, like MythBusters, Tanked and other shows where scene numbering is f***ed up. Every other show just import with original scene file name.

**Comment by bakerboy448** [comment]
Duplicate of #926
Duplicate of #2970

Please search next time

**Comment by jaenster** [comment]
To be fair, he did comment on #2970 in november and #926 is closed
