### ISSUE TITLE
V3 Docker Import Not Working

### ISSUE THREAD

**Issue by baxtmann** [Sonarr/Sonarr#4505]
I was able to add two directories for Sonarr to import, but then when I tried to add a 3rd it failed. I can see an error showing in the console so something clearly isn't working as expected. 

**To Reproduce**

Once a dir is added, sonarr should start scanning said dir. 
**Screenshots**
![sonarr no work](https://user-images.githubusercontent.com/18515115/119405150-d2173600-bcae-11eb-8fec-2ae5cb7e4790.png)

**Platform Information (please complete the following information):**
 - OS: Unraid 6.9.2 -> Docker image from binhex/arch-sonarr
 - Docker: Yes
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): Mono - 6.12.0
 - Browser and Version (Only needed for UI issues): Chrome 90.0.4430.212
 - Sonarr Version:3.0.6.1196 
 - Sonarr Branch: master I imagine? 

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6534901/sonarr.trace.txt)

**Comment by bakerboy448** [comment]
```
21-5-24 13:44:27.1|Trace|DiskProviderBase|Directory '/usr/mnt/plex-f/TV/' isn't writable. Access to the path "/usr/mnt/plex-f/TV/sonarr_write_test.txt" is denied.
21-5-24 13:44:27.1|Trace|SonarrErrorPipeline|Handling Exception
21-5-24 13:44:27.1|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Folder is not writable by user nobody
21-5-24 13:44:27.1|Trace|Http|Res: 5447 [POST] /api/v3/rootFolder: 400.BadRequest (23 ms)
21-5-24 13:44:27.1|Debug|Api|[POST] /api/v3/rootFolder: 400.BadRequest (23 ms)
```

Bugs/Exceptions are not errors.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

You'll also want to see https://wiki.servarr.com/Docker_Guide and https://trash-guides.info/hardlinks
