### ISSUE TITLE
Add anime trackers to the `Links` button for a series.

### ISSUE THREAD

**Issue by sparksis** [Sonarr/Sonarr#4506]
**Is your feature request related to a problem? Please describe.**
`Links` does not have have an option to link to MyAnimeList or anilist.co

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/1209861/119419206-fc6cf180-bcb6-11eb-8069-958230c5be74.png)
Addition of AniList and MyAnimeList to the links drop down.

**Describe alternatives you've considered**
N/A
**Additional context**
Perhaps these only need to appear if the "Series Type" is configured to "Anime"

**Comment by markus101** [comment]
Unless there is a way to do so with one of the IDs Sonarr already has this will not be possible. We'll need the specific URLs Sonarr can use to do so.

**Comment by sparksis** [comment]
Great question, markus.  How does TVDB handle this?  Is this something where we'd have to integrate the whole search API from each of the anime providers and then grab the internal IDs at the time we search?

**Comment by markus101** [comment]
Unless TheTVDB has a field for it (AFAIK they don't currently) or those sites allow lookup by TheTVDB IDs then it won't be possible. Sonarr/Skyhook won't search those sites to find IDs.

**Comment by sparksis** [comment]
So how does IMDB work?  It appears that sonarr already stores multiple DB specific IDs?  Would you mind sharing a schema (I'm on linux and development of this project is a PitA due to .NET [or it was last time I wanted to fork])

**Comment by sparksis** [comment]
Seems like
https://github.com/Sonarr/Sonarr/blob/93443f1db2d281bd7868b44e24543cc1668fdee4/src/NzbDrone.Core/Tv/Series.cs#L22-L28
could be amended to include a couple of anime specific fields.

**Comment by markus101** [comment]
Could add 100 fields, but if Sonarr doesn’t have the IDs it won’t do anything. The lack of data at this time means it’s not something we’re going to do.
