### ISSUE TITLE
Option to hardlink rather than delete renamed Usenet downloads (as with seeding torrents)

### ISSUE THREAD

**Issue by RibShark** [Sonarr/Sonarr#4512]
**Is your feature request related to a problem? Please describe.**
I am attempting to use https://github.com/boban-bmw/cross-seedarr alongside AutoTorrent to seed everything I download to as many trackers as possible. AutoTorrent works best if the files retain their original name. When downloading torrents, this works fine, as Sonarr will simply hardlink the files to rename them, rather than copying/deleting. When downloading from Usenet, however, Sonarr will copy/delete the files with no option to switch to hardlinking.

**Describe the solution you'd like**
I would like an option to hardlink downloaded Usenet files in order to rename them rather than copying/deleting them.

**Describe alternatives you've considered**
Mode hash_size in AutoTorrent: too high risk of false positives.

**Comment by markus101** [comment]
We do not have plans to add options to usenet clients for readonly importing like seeding torrents. You could use a custom script that executes after import to hardlink back to another location and seed from that.
