### ISSUE TITLE
Manually Disable TBA Limitation

### ISSUE THREAD

**Issue by quixote23** [Sonarr/Sonarr#4513]
Give me a toggle to allow the import of an episode that currently has a title of TBA or not. 

I understand the logic behind this, but this means that the import of episodes that I have downloaded and are ready to go become completely dependent on an outside, third-party source's means to update within a reasonable period of time, and frankly that just doesn't always happen. This is not something that should be imposed on the community without allowing us the ability to bypass it if it isn't something we care about for our personal collection.

**Comment by bakerboy448** [comment]
Closing
- template not followed
- Docs not read
- Settings not explored
This exists
