### ISSUE TITLE
Context switches skyrocket in latest releases

### ISSUE THREAD

**Issue by ngosang** [Sonarr/Sonarr#4514]
**Describe the bug**
Yesterday I updated Sonarr:
* Updating Sonarr from version 3.0.4.1139 to version 3.0.5.1143
* Updating Sonarr from version 3.0.5.1143 to version 3.0.6.1196

Since the update I have notice a lot of context switches in my server. Everything is working fine but the numbers are unusually high.
BTW, nice idle CPU usage reduction.

**Expected behavior**
Reduce the number of context switches. I'm running ~50 Docker containers and ~300 process in my server and Sonarr has more context switches than all other processes combined. Almost all context switches are voluntary, that means they are not caused by the OS. Sonarr is deployed without Docker with Mono.

**Screenshots**
Both updates ~20:00h
![image](https://user-images.githubusercontent.com/10577978/119808468-6fa77b00-bee4-11eb-8640-339398272dae.png)
![image](https://user-images.githubusercontent.com/10577978/119809360-5226e100-bee5-11eb-8fe6-0951fdb7287f.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: No
 - Mono Version:  5.18.0.240
 - Version:  3.0.6.1196

**Comment by Taloth** [comment]
Do you have some trace level logs for it too?

**Comment by ngosang** [comment]
Traces. Sonarr was idle, just Bazarr pooling from time to time.
[sonarr.trace.1.txt](https://github.com/Sonarr/Sonarr/files/6555944/sonarr.trace.1.txt)

Max resolution I have is 1 minute but I can't see any correlation between CPU neither Bazarr process.
![image](https://user-images.githubusercontent.com/10577978/119876949-bb7c1380-bf28-11eb-8b85-b78c44d75477.png)

**Comment by Taloth** [comment]
last timestamp in log is 21-5-27 19:32:42.2
got anything covering the > 20:10 period?

**Comment by ngosang** [comment]
Update was yesterday (26th) logs are from today.
![image](https://user-images.githubusercontent.com/10577978/119878019-f7fc3f00-bf29-11eb-83f4-e2b37b3a663f.png)

**Comment by ngosang** [comment]
The bug was in Prometheus process exporter. Sonarr good, Monitoring bad.
Sorry for your time and keep the awesome work!

**Comment by Taloth** [comment]
Awesome, thx for investigating. I was worried for a moment there.

**Comment by ngosang** [comment]
After fixing my metrics, there is an impressive improvement in Sonarr in both metrics.
* CPU improvement 50/27 = x1.85
* Context switching improvement 314/7 = x44

Don't look at absolute numbers, they mean nothing.

Last 2 days
![image](https://user-images.githubusercontent.com/10577978/119889598-0f8df480-bf37-11eb-9f6f-0143f3a73123.png)

Last 30 days. I updated Radarr 11/05 and there was a similar improvement. 
![image](https://user-images.githubusercontent.com/10577978/119890632-5e885980-bf38-11eb-8040-5e37e58bbeef.png)

Thank you so much!
Related https://github.com/ncabatoff/process-exporter/issues/193
