### ISSUE TITLE
Adding EZRSS as an indexer results in "UnsupportedFeedException: Failed to find a valid download url in the feed"

### ISSUE THREAD

**Issue by romainguinot** [Sonarr/Sonarr#4516]
**Describe the bug**

EZRSS feed no longer parsed. Not really sure why as the XML is valid and the debug / trace logs don't reveal much as to what exactly is failing. "Allow Zero Size" does not change the result, so that isn't the cause. 

EZRSS is what i previously used some time ago directly in the torrent client, but no longer use since moving to Sonarr / Jackett. Logging this regardless in case it helps others that may be using it directly.

```
[v3.0.6.1196] NzbDrone.Core.Indexers.Exceptions.UnsupportedFeedException: Failed to find a valid download url in the feed.
  at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.ValidateReleases (NzbDrone.Core.Parser.Model.TorrentInfo[] releases, NzbDrone.Core.Indexers.TorrentRss.TorrentRssIndexerSettings indexerSettings) [0x0010a] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:285 
  at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.GetEzrssParserSettings (NzbDrone.Core.Indexers.IndexerResponse response, NzbDrone.Core.Indexers.TorrentRss.TorrentRssIndexerSettings indexerSettings) [0x0002a] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:100 

```

**To Reproduce**

Add EZRSS feed as an indexer (https://eztv.re/ezrss.xml). Click Test. Error appears. 

**Expected behavior**

EZRSS correctly added as an indexer.

**Platform Information (please complete the following information):**
  - Docker: Yes
  - System status :  
Version
3.0.6.1196
Package Version
3.0.6.1196-ls106 by linuxserver.io
Mono Version
5.20.1.34

 - Sonarr Branch: master

**Trace Logs**
Attached.

**Comment by romainguinot** [comment]
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6566399/sonarr.trace.txt)

**Comment by Taloth** [comment]
Some of the items int he feed don't have an `<enclosure`, which is why it's being rejected.

**Comment by romainguinot** [comment]
@Taloth thanks ! wasn't sure what tag it was specifically looking out for. I've made a small test by copying over some missing enclosures and serve out the feed from a local server to see if it could be accepted by sonarr's test. And indeed, it's accepted by adding the enclosures. 

I'm wondering though if the parser should only fail if there isn't either an enclosure OR a magnet URI link for an entry item ?

**Comment by Taloth** [comment]
Maybe, but it's a bit ambiguous behavior. Kinda like driving on the highway and see a car swerve left and right, you'll want to keep your distance.

There are variations of rss parser in our code, and the one that's being used (ezrss format) always had enclosure. So if it sees a site doing something else it concludes it's not a format it's seen before. Possible to adjust it, but I dunno if that's worth the time.
