### ISSUE TITLE
Allow (a second) prioritization of indexers for UPGRADES only!

### ISSUE THREAD

**Issue by vladola** [Sonarr/Sonarr#4517]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
At the moment Sonarr will use the same exact indexers with the same exact priorities when it downloads something for the first time _and_ when it upgrades something to a better quality.

It would be great to have the ability to set a different set of priorities for the indexers (or even make no use of certain indexers) when it comes to upgrading to a better quality file.

Why would you want this?

Well, for those of us on private trackers _and_ usenet, it sometimes is more convenient and/or smart to have the first release via usenet (without consuming private tracker download credits, for example) and then, at a later date, allow for upgrades to 
a better quality using a high quality tracker (for example, use usenet to grab quick scene release of a TV show, then use BTN to torrent the bluray version when it comes out).

**Describe alternatives you've considered**
At the moment, the alternative is to set a non-upgrade profile for a series to download whatever is first available _AND_ disable or set to a lower priority the "good" media sources (private trackers, etc).

Then, when you want to upgrade, you set the profile to be upgradable and set the priority for the "good" media source higher than other (usenet).

This is obviously not optimal... :)

**Additional context**
n\a

**Comment by markus101** [comment]
We do not have plans for additional indexer prioritization at this time.
