### ISSUE TITLE
Add firewalld service config

### ISSUE THREAD

**Issue by k4my4b** [Sonarr/Sonarr#4518]
**Is your feature request related to a problem? Please describe.**

As firewalld is slowly taking over and most poeple are deploying it on their media servers it would appropriate to add the necessary service configs for firewalld to prevent users having to configure this manually each time.

**Describe the solution you'd like**

Add [firewalld service file](https://firewalld.org/documentation/howto/add-a-service.html)

**Describe alternatives you've considered**

Users will have to take care of this manually (very inconvenient)

**Additional context**

**Comment by markus101** [comment]
At this time we do not have plans to add support for firewalld.
