### ISSUE TITLE
Cant Authenticate with Trakt.tv

### ISSUE THREAD

**Issue by kl3mta3** [Sonarr/Sonarr#4521]
When Trying to authenticate Trakt.tv it reaches out to "https://api.trakt.tv/auth/signin"  which goes to a 500 error splash page.

If you remove the "api." and go to "https://trakt.tv/auth/signin" it will let you sign in.  But Sonarr seems to still be waiting for authentication. 

This is preventing the lists from updating shows.

**Comment by thezoggy** [comment]
i can confirm, 
```
$ curl -I "https://api.trakt.tv/auth/signin"
HTTP/1.1 500 Internal Server Error
Date: Wed, 02 Jun 2021 05:37:34 GMT
Content-Type: text/html; charset=UTF-8
```

looking at https://trakt.docs.apiary.io/#introduction/create-an-app

they say to use `https://trakt.tv/oauth/applications/new`  which redirects to  `https://trakt.tv/auth/signin`
```
$ curl -I "https://trakt.tv/oauth/applications/new"
HTTP/1.1 302 Found
Date: Wed, 02 Jun 2021 05:39:22 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Location: https://trakt.tv/auth/signin
```

**Comment by kl3mta3** [comment]
Is this something i can correct?
Is there a way on my end to change the address Sonarr is trying to access for Trakt.tv authentication?

**Comment by kz88au** [comment]
also the same here.

```
{
  "version": "3.0.6.1262",
  "buildTime": "2021-06-02T15:41:31.3414089Z",
  "isDebug": false,
  "isProduction": true,
  "isAdmin": true,
  "isUserInteractive": false,
  "startupPath": "C:\\ProgramData\\Sonarr\\bin",
  "appData": "C:\\ProgramData\\Sonarr",
  "osName": "Windows",
  "osVersion": "10.0.18362.0",
  "isMonoRuntime": false,
  "isMono": false,
  "isLinux": false,
  "isOsx": false,
  "isWindows": true,
  "mode": "service",
  "branch": "develop",
  "authentication": "forms",
  "sqliteVersion": "3.8.7.2",
  "urlBase": "",
  "runtimeVersion": "4.8.0",
  "runtimeName": "dotNet",
  "startTime": "2021-06-02T15:41:38.966446Z",
  "packageUpdateMechanism": "builtIn"
}
```

**Comment by Qstick** [comment]
> Is this something i can correct?
> Is there a way on my end to change the address Sonarr is trying to access for Trakt.tv authentication?

Sure, PR the change to Sonarr, once they accept it it’ll be fixed for all

https://github.com/Radarr/Radarr/commit/13ce3fc6da70ecd984bd0ecc44a14757c65676ff
