### ISSUE TITLE
sonarr does not search "ilcorsaronero" indexer

### ISSUE THREAD

**Issue by albatr0ss** [Sonarr/Sonarr#4522]
**Describe the bug**

Sonarr does not search ilcorsaronero.link indexer. Other indexers are searched and return results correctly. Searching for items in ilcorsaronero.link in jackett returns expected results correctly. Also, te.st button when configuring indexer in sonarr says everything works correctly

**To Reproduce**

Setup jackett with ilcorsaronero.link, check that searches work in jackett.
Configure sonarr's indexers with jackett's URL for ilcorsaronero.link. Select correct categories for the indexer.
Do automatic or manual search for items in your wanted library.

**Expected behavior**

Automatic or manual searches of episodes or seasons should show findings from ilcorsaronero.link

**Screenshots**

**Platform Information (please complete the following information):**
 - OS:   Raspbian 10 (buster)
 - Docker:  yes
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status):  Mono 6.12.0.122 
 - Browser and Version (Only needed for UI issues): 
 - Sonarr Version:  3.0.6.1196
 - Sonarr Branch:  master

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/6587936/sonarr.txt)

**Comment by markus101** [comment]
This isn't a bug, this is the indexer in Jackett missing the `season` and `ep` search parameters:
https://github.com/Jackett/Jackett/blob/0a38b26436373092c4824ce311da082c03c0ecda/src/Jackett.Common/Definitions/ilcorsaronero.yml#L50

vs

https://github.com/Jackett/Jackett/blob/0a38b26436373092c4824ce311da082c03c0ecda/src/Jackett.Common/Definitions/1337x.yml#L132

**Comment by albatr0ss** [comment]
markus101, excuse me if I am back again but this doesn't seam to be the root cause.

I got the Jackett developers to remove the keywordsfilter part you posted and downloaded the new ilcorsaronero.yml file.
Did some tests and it doesn't work neither.
I enabled "trace" logging and it seems that sonarr never uses ilcorsaronero to submit requests.

All indexers available
<img width="1285" alt="all-indexers" src="https://user-images.githubusercontent.com/39968575/120685437-1faa5480-c4a0-11eb-957d-dd140eeee956.png">

ilcorsaronero configuration
<img width="676" alt="ilcorsaronero-conf" src="https://user-images.githubusercontent.com/39968575/120685498-2df87080-c4a0-11eb-8478-07fe9203b38e.png">

log part with searches
<img width="1523" alt="search" src="https://user-images.githubusercontent.com/39968575/120685549-3d77b980-c4a0-11eb-92b2-f25211d9166c.png">
As you can see ilcorsaronero is never referenced

Full trace log
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6593287/sonarr.trace.txt)

Please tell me if there is some other information I can provide.

**Comment by Taloth** [comment]
Restart Sonarr if Jackett capabilities change, they're cached for 7 days.

**Comment by albatr0ss** [comment]
Restarted the docker container but still same result.
Can you please explain why I don't see ilcorsaronero indexer in the log?

**Comment by Taloth** [comment]
Check the trace log since sonarr restart. In the log you'll see 't=caps', query that url for ilcorsaronero.

You'll see that it does not advertise 'season' and 'ep' query parameters. So it's not searched.
The changed made in Jackett is not correct, since it doesn't add those query parameters.

Again, it's the lines that markus linked. Please check them out.

**Comment by albatr0ss** [comment]
Just to close this report.
Jackett's developer added season and ep advertising...
Everything is working as expected.
Thank you all for your patience and support.
