### ISSUE TITLE
Sonarr loses connection to qBittorrent after adding torrent

### ISSUE THREAD

**Issue by anast20sm** [Sonarr/Sonarr#4523]
Hello I want to use qBittorrent as Download Client but encountered the following problem: the downloads start but once they are added to qBittorrent, seems Sonarr loses connection to it and does not appear as "Downloading" and neither moves the files after the download is finished.

How can i fix this? Is it related to qBittorrent configurations? I used uTorrent until today and it worked perfectly and I tested qBittorrent with Radarr and works as expected.

Thanks in advance

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.
