### ISSUE TITLE
More than one download client for torrents

### ISSUE THREAD

**Issue by blackph0en1x** [Sonarr/Sonarr#4526]
**Is your feature request related to a problem? Please describe.**

I have some torrents that are aged and take a big while to get downloaded because seeders are not many nor always available. This gets locking up my download client (transmission in this case) which is waiting on these old torrents and doesn't start  new "weekly" torrents.
I have everything dockered so I fired up a new transmission docker (transmission_long) listening on a different port and did the search for the torrent with this new client the I configured as new download client in sonarr. I searched the shows I know will have the "aging" problem with transmission_long enabled and I have torrents (slowly) getting downloaded.
To be able to get ASAP new releases I am monitoring I enabled the first download client (transmission) and disabled transmission_long.
I noticed that in this situation sonarr doesn't monitor the disabled (transmission_long) download queue and finished torrents aren't imported into sonarr. Once I disabled transmission and enabled transmission_long this last download queue got picked up again but is not imported (as by now)

**Describe the solution you'd like**

It would be nice to be to have more than one download client enabled and be able to choose which one to use when you do a search for a show/anime/whatever like you do with quality profile, language profile and root folder.
Should the above not be possible it would be nice if sonarr would continue to monitor the download queue of the client that was used to start the download. There could be an active/passive options where the active download client is used to download new requests from sonarr while the passive(s) is only checked to see if there are finished downloads.

**Describe alternatives you've considered**

**Additional context**

**Comment by drowse7en** [comment]
As a temporary solution, if Transmission supports the option to ignore running torrents with download speeds less than a specified threshold you could enable that and it will not "count" those torrents in the number of allowed, active downloads.

You can also set a relatively high number of allowed, active torrents so the older torrents with low / no seeders don't take up all of your torrent client's download slots.

I have this enabled in qBittorrent, to allow up to 64 concurrent, active, downloading torrents and to ignore downloads running at 4.00 KB or less.  QBT simply cycles through slow or unresponsive torrents until it hits a torrent with active seeders.
