### ISSUE TITLE
Can't add another tv show with same title (but in a different folder)

### ISSUE THREAD

**Issue by Zamana** [Sonarr/Sonarr#4530]
Hi!

I'm trying to add the new series Time (2021), but the system complains that there is another tv show called "Time". But the matter is that this old one is a documentary (and it is in my "documentary" folder) and this new one will go to the "shows" folder.

![time2021](https://user-images.githubusercontent.com/6900313/121107614-9e73fa00-c7de-11eb-88d8-65efe30c48ad.png)

![slug](https://user-images.githubusercontent.com/6900313/121107624-a16eea80-c7de-11eb-896d-2f289d6f07ff.png)

Version: 3.0.6.1196
Package Version: 3.0.6.1196-ls106 by linuxserver.io
Mono Version: 5.20.1.34

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

Duplicate titles are not supported, the new series should have 2021 in the series name.

**Comment by Zamana** [comment]
> Please use one of the support channels: forums, subreddit, discord , or IRC for support/questions.
What kind of questions do you handle here?

> Duplicate titles are not supported, the new series should have 2021 in the series name.
And what can I do about?
