### ISSUE TITLE
Import indexers from Jackett

### ISSUE THREAD

**Issue by khumps** [Sonarr/Sonarr#4534]
**Describe the solution you'd like**
When creating a new indexer, have an "import from Jackett" button. This would prompt the user for the jacket api endpoint and their jackett API key. It would then list all indexers that jacket has, allowing you to add them in a similar fashion to importing TV shows. It could automatically pull in all tracker codes for TV/Anime etc based on what the jackett API says the tracker is good for

**Describe alternatives you've considered**
I already do it by hand but it is tedious to do it with all my trackers and may make it easier for others

**Comment by bakerboy448** [comment]
Please search next time

https://github.com/Sonarr/Sonarr/issues/3170
https://github.com/Sonarr/Sonarr/issues/3530

**Comment by Qstick** [comment]
Prowlarr is your friend 😁
