### ISSUE TITLE
Losing release group name when manually importing special episodes

### ISSUE THREAD

**Issue by ArabCoders** [Sonarr/Sonarr#4539]
**Describe the bug**
When manually selecting show, season  and episode specially Specials, the release group tag is ignored.

**To Reproduce**

add new show called "Deadman Wonderland" type: anime, create new tests file 
* A/[Amalgama] Deadman Wonderland Akai Knife Tsukai (Dual Audio) (BDRip 1920x1080 h.264 FLAC).mkv
* B/[Amalgama] Deadman Wonderland Akai Knife Tsukai (Dual Audio) (BDRip 1920x1080 h.264 FLAC)-Amalgama.mkv
* C/Deadman Wonderland - S00E01 - Akai Knife Tsukai [Dual Audio][BDRip 1920x1080 h.264 FLAC]-Amalgama.mkv

now, try to manually import the episode from wanted > manual import. Episode is Specials/01 or S00E01 try to manually pick them up.
file in A, and B will lose the release group tag.
but file C will be correctly tagged and no manual process is required and therefore the release group will be retained.

im not sure if this bug occurs when selecting non-special episodes. i only noticed it when import Specials.

**Expected behavior**
The release group tag to be imported as well as it's used in my naming scheme.

**Platform Information (please complete the following information):**
 Version
3.0.6.1196
Package Version
3.0.6.1196-ls107 by linuxserver.io
Mono Version
5.20.1.34
AppData directory
/config
Startup directory
/app/sonarr/bin
Mode
Console
Uptime
23:02:14

**Comment by markus101** [comment]
Sonarr can’t parse the release group from the file name (it looks like it can’t parse anything because it’s a special), the closest solution would be https://github.com/Sonarr/Sonarr/issues/3811
