### ISSUE TITLE
Windows installer version writes only major release version

### ISSUE THREAD

**Issue by mikeparkie** [Sonarr/Sonarr#4542]
This is fairly straight forward so I'll keep it simple. The Windows version for Sonarr installer (x64, not tested x86) shows the installed version as major version only e.g. 3.0 and not major.minor (3.0.6.1196). Can this be corrected? Radarr for example writes the corrected values.

**Comment by Taloth** [comment]
That's basically intentional since the autoupdater would make the build number inaccurate.

**Comment by mikeparkie** [comment]
Thats a shame, any plans to change this in the future? I only ask as the *arr apps can't be added to the Windows Package Manager [winget ](https://docs.microsoft.com/en-us/windows/package-manager/winget/) repo of installable apps.

**Comment by mikeparkie** [comment]
thinking about it, the major version will be fine, as winget can install that version and then the autoupdater will take care of the rest.
