### ISSUE TITLE
Add Download Client Modal - Incorrect Notice (Indexers)

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4545]
Add Download Client Modal has Indexer language which is incorrect

> Sonarr supports any downloadClient that uses the Newznab standard, as well as other downloadClients listed below.
For more information on the individual downloadClients, clink on the info buttons.

**Screenshots**

![image](https://user-images.githubusercontent.com/55419169/122589382-cb69ad80-d025-11eb-9a2c-e0ceac6e515f.png)

**Platform Information (please complete the following information):**
 - OS:  agnostic
 - Docker:  agnostic 
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status):  agnostic 
 - Browser and Version (Only needed for UI issues):  agnostic
 - Sonarr Version:  3.0.6.1264 (also exists on main 3.0.6.1266)
 - Sonarr Branch:  develop  (also exists on main )

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

N/A - UI

**Comment by Qstick** [comment]
What do we want here? Nothing or something like:

```
Sonarr supports many popular torrent and usenet download clients.
For more information on the individual download clients, click the more info buttons
```

**Comment by markus101** [comment]
I think the latter makes the most sense.

**Comment by bakerboy448** [comment]
> I think the latter makes the most sense.

I agree
