### ISSUE TITLE
Move directly to next checked episode on import modal when manually assigning episode names

### ISSUE THREAD

**Issue by Getn67** [Sonarr/Sonarr#4546]
**Is your feature request related to a problem? Please describe.**
Manually assigning episodes properly sucks, but I can't expect Sonarr to understand every single weird way that a show is packaged in a file.

**Describe the solution you'd like**
When interactively importing episodes, and all that is left is to assign episodes to the files, I would like a method of assigning an episode name, and moving immediately to the next checked files 'episode selection' modal as soon as I have assigned the previous episode. Ideally, I could work from top to bottom after deselecting frivolous files/special episodes. 

**Describe alternatives you've considered**
The other option I considered suggesting is allowing to define whether Sonarr assigns by keys like 'S22E5' or by episode name, however, I think the above will be simpler to implement.

**Additional context**
I totally understand that the goal of Sonarr is to automate the management process as much as possible, however, there seem to be fringe cases, and I don't see that changing. 
Here you can see that the episode is split into multiple parts, however, it isn't detected properly by Sonarr properly because of the S**E** format.
![modal](https://user-images.githubusercontent.com/51862012/122705062-cfeebb80-d209-11eb-8e2c-446fe800c7f8.JPG)

**Comment by markus101** [comment]
Sonarr supports selecting them in bulk as long as the files are in the correct order selecting multiple files then selecting the episodes will assign the episodes. For example if you have 10 files selected you need to select 10 episodes (or a multiple of 10 for double, triple episodes).

We don’t have plans to auto select the next file and open the episode select modsl.

**Comment by Getn67** [comment]
> Sonarr supports selecting them in bulk as long as the files are in the correct order selecting multiple files then selecting the episodes will assign the episodes. For example if you have 10 files selected you need to select 10 episodes (or a multiple of 10 for double, triple episodes).


My current issue here is that each “portion” of an episode is listed out as it’s own episode in tvdb, so selecting en masse and picking an episode doesn’t quite work out well. Am I missing an option to arrange the files, and assign ascending episode numbers automatically? It sounds as though there is an existing solution to my issue that I’m not seeing.

**Comment by markus101** [comment]
Order them by relative path, then use `Select Episodes` under the `Select...` menu. Using the S21E07 files as an example you'd select the 4 corresponding episodes from the list (S21 E21-E24 it looks like) and Sonarr will assign them in order. If you have any more questions about it please use one of our support channels (Discord, IRC, reddit or forums).
