### ISSUE TITLE
Add Join test server as an option for notifications

### ISSUE THREAD

**Issue by ChronoStriker1** [Sonarr/Sonarr#4547]
In connections add a dropdown, checkbox, or seperate entry to use the Join test server instead of the normal one.
This is usefull to people currently using the Join Destop App due to using firefox or other non compatible browsers instead of google chrome.

Normal APIAddress: https://joaomgcd.appspot.com
Test API Address: https://testsjoaomgcd.appspot.com

**Comment by bakerboy448** [comment]
Tagging the Downstream feature requests
https://github.com/Readarr/Readarr/issues/1074
https://github.com/lidarr/Lidarr/issues/2288
https://github.com/Radarr/Radarr/issues/6401
https://github.com/Prowlarr/Prowlarr/issues/254

**Comment by slimjim91** [comment]
I dont think this is necessary anymore with Join V3

https://www.reddit.com/r/JoinApp/comments/o69c7k/dev_join_30_works_in_firefox_and_edge_local/

**Comment by ChronoStriker1** [comment]
Agreed feel free to close this 

Jun 23, 2021 4:01:47 PM Salim Nanji ***@***.***>:

**Comment by bakerboy448** [comment]
Closing per https://www.reddit.com/r/JoinApp/comments/o69c7k/dev_join_30_works_in_firefox_and_edge_local/
