### ISSUE TITLE
Changes in Media Undetected if Replacement File has Same Filename

### ISSUE THREAD

**Issue by dioxin187** [Sonarr/Sonarr#4550]
I've noticed that Sonarr does not detect changes to episodes if the replacement files have the exact same filename as the previous file.

Example: If I replace a standard definition episode of a series with a high definition version and ask Sonarr to update, it will still show that episode as standard definition with the old file size.

I suppose there is a way where timestamps/hashes could be used instead of filenames to detect changes, which I believe would resolve the issue.

**Platform Information (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Sonarr Version: 3.0.6.1265

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/3366
