### ISSUE TITLE
Add Preference for TBA titled show downloads

### ISSUE THREAD

**Issue by dny238** [Sonarr/Sonarr#4553]
Shows keep not downloading automatically because their title on theTVDB hasn't been updated yet. It's still TBA, but I don't care. I want it to download automatically. 
Can this be made an option in the UI, or secret preference in the ini file or something? Please please with icecream on top? 

https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/EpisodeTitleSpecification.cs

                if (title.Equals("TBA"))
                {
                    _logger.Debug("Episode has a TBA title and recently aired");

                    return Decision.Reject("Episode has a TBA title and recently aired");
                }
            }

**Comment by bakerboy448** [comment]
already exists.......

advanced option
https://wiki.servarr.com/en/sonarr/settings#importing

**Comment by Taloth** [comment]
There is. Settings -> Media Management -> Importing -> Episode Title Required.

**Comment by dny238** [comment]
Duh, thanks guys!
Even tried to check the source code
