### ISSUE TITLE
When sonarr uses up last of the disk space it incorrectly fails the current release and all other releases.

### ISSUE THREAD

**Issue by addictivkaos** [Sonarr/Sonarr#4554]
**Describe the bug**

Sonarr is using a bittorrent and nzb client and while downloading the destination hard drive runs our of disk space. 
Sonarr fails the currently downloading show releases and then attempts to find other matching releases, adds them to the download client, but fails them all too. End up with heaps of downloads for the same episode in the download client all failed.
Sonarr doesn't repair the situation even after clearing up space and completing a download, because I think Sonarr thinks the download is marked as failed??

**To Reproduce**

Sonarr should treat a local full hard disk as a different error to a failed download. i.e. a full hard drive typically needs external intervention and sonarr shouldn't fail the download. Sonarr doesn't need to do anything, the download clients will handle the full disk and resuming once the disk space is freed up and sonarr can continue to monitor the episode for its completion.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS:  Windows 10 2004
 - Docker:  No
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status):  donet 4.8.0
 - Browser and Version (Only needed for UI issues): 
 - Sonarr Version: 3.0.6.1265
 - Sonarr Branch:  master

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

[logs.zip](https://github.com/Sonarr/Sonarr/files/6719946/logs.zip)

**Comment by bakerboy448** [comment]
Uploading 51 tracelogs is...well to be frank useless and a waste of effort.

[Please see the wiki for how to provide useful log files](https://wiki.servarr.com/sonarr/troubleshooting#logging-and-log-files)

**Comment by markus101** [comment]
In addition, exactly which download clients are you using?
Torrent clients don’t have the concept of failed downloads, but Usenet clients do; Sonarr gets failed downloads from the client, filters out some errors and then processes them, the most important information in this case would be founding the failed downloads in the response from the download client so we can see the failure message.
