### ISSUE TITLE
Series Details: Sort Episodes

### ISSUE THREAD

**Issue by AYColumbia** [Sonarr/Sonarr#4558]
**Is your feature request related to a problem? Please describe.**
Prior to v3 when you click on a series and go to the seasons/episodes list I was able to sort by the titles by clicking #, Title, Air Date, etc.  This is no longer the case in the v3 list.

**Describe the solution you'd like**
Please bring back the clickable header that sorts the episodes within the season, e.g., if I click the # header within Season 5 the list is sorted within Season 5.  Basically if it's currently ascending, clicking # would then sort in descending and so on.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
I highlighted the headers I'm referring to in the snapshot.  Thank you.
![2021-06-27 09_26_56 - sonarr seasons-episodes list no sortable header](https://user-images.githubusercontent.com/6758781/123548359-1a9c9600-d72a-11eb-844f-321d7b03ac39.png)

**Comment by ZackaryH8** [comment]
I'm working on this issue

**Comment by jack-mil** [comment]
This should probably be revisited in v4. 
Though I'm not sure if sorting series episodes in that view by anything other than sequence makes sense.

Perhaps to identify missing/cutoff unmet episodes?

**Comment by AYColumbia** [comment]
I agree, just sorting by the episode #/sequence is sufficient.  For my own purpose, I use the sort because I copy the info to my own managed data file and in that context, it's needed in ascending order.  Because it's in descending, I have to parse it and then pop it into a spreadsheet to sort it which is adding a lot of extra work.

Not sure what you use but seems like it's a simple implementation to order by using jQuery or similar that's initiated by a clickable # column header.  Just a thought :)  Thanks again.

**Comment by markus101** [comment]
Added in https://github.com/Sonarr/Sonarr/commit/113b0864b8e92b7b768acc8341bdf4c9e2e1a47f
