### ISSUE TITLE
Series monitoring option for "Notifications only"

### ISSUE THREAD

**Issue by derekantrican** [Sonarr/Sonarr#4560]
I pay for a Hulu subscription, so don't have a big need to download series. However, I really like Sonarr's flexible notification system (eg can get notifications through Discord for a variety of events) and was wondering if a "Series Monitor" option could be added for "Notifications only". So future episodes would be notified of, but not downloaded. Is this possible already? Or can this be added?

**Comment by markus101** [comment]
We do not have plans for such a feature at this time.
