### ISSUE TITLE
Filename parameter parsing like release group should have release name fallback

### ISSUE THREAD

**Issue by mhriemers** [Sonarr/Sonarr#4561]
**Describe the bug**
When an episode file or a season pack folder doesn't contain all the necessary information (like release group or other preferred words), Sonarr should fallback on the release name. 

Currently, when comparing the current downloaded release with those found on the tracker, the preferred word score of the downloaded and renamed file is compared to the release name of the one found on the tracker. When the episode naming format isn't properly adjusted, and the cutoff isn't met, this can cause the release to be re-downloaded when doing an automated search (only in the case of usenet or if the torrent has been removed from the client). The simple fix for this is including the parameters used in "Release Profiles" in the renamed filename. The problem is however, that these parameters used for renaming are only determined based on the downloaded filenames, not the release name.

**To Reproduce**
An example of this is the following: the release name is `Californication.S07.1080p.BluRay.Remux.TrueHD5.1.H.264-ABC`, but the torrent has the following structure: `Season 7/Californication.S07EXX.mkv`. In the downloaded file, there is no release group, audio codec, video container information, etc.

**Expected behavior**
Sonarr should fallback on the release name to parse the missing bits of information, the ones which it originally used to determine the preferred word score.

**Platform Information (please complete the following information):**
 - Docker: Yes
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): Mono 5.20.1.34
 - Sonarr Version: 3.0.6.1265-ls111 by linuxserver.io
 - Sonarr Branch: main

**Comment by markus101** [comment]
Please post the relevant logs where this is not working as expected. Sonarr already falls back to the folder name and the information from the download client.

**Comment by bakerboy448** [comment]
Before OP comes back with logs, assuming this is the same as discussed in discord yesterday's

the release name has the info; the downloaded folder ("season 7") does not; and the individual episodes are parsable, but do not contain the group.

it's basically a case of the release name not matching the data of the torrent not contained within the torrent

**Comment by bakerboy448** [comment]
Closing; Can reopen if OP ever returns with logs.
