### ISSUE TITLE
Score file suffixes when downloading full seasons

### ISSUE THREAD

**Issue by ddmf** [Sonarr/Sonarr#4564]
I've been backfilling a lot of old series, and I've noticed that it may take two or three or more different releases before an episode completes successfully. Once they do, they're typically from the same release, ie if you exclude the name and season / episode details the suffixes of the completed files are the same. 

What if the suffixes that complete are scored higher, and the failing suffixes are scored lower - this means successive episodes wouldn't have to go through the same few releases that will fail before getting to the ones that don't.

**Comment by markus101** [comment]
Interesting idea, but not something we're going to implement at this time.
