### ISSUE TITLE
Force a show to download only the dubbed versions?

### ISSUE THREAD

**Issue by jscottdouglas** [Sonarr/Sonarr#4565]
there is a show that is in french but also gives a dubbed version in english, for some reason sonarr downloads the french version labels the language as english even though it's french.  Plex picks it up properly as french.  There is however a dubbed version which is actually english but sonarr fails to pick it up.

**Comment by markus101** [comment]
Please use the proper template and search before opening issues.

If the file name does not include the language it will be treated as English. Plex detects it based on the track which already has an issue open: https://github.com/Sonarr/Sonarr/issues/4240

**Comment by jscottdouglas** [comment]
ok i did search by dubbed and couldn't find anything so is there a way to force a particular show to only download the dubbed version? your open issue doesn't exactly answer my question only about the language.
