### ISSUE TITLE
Trakt List Import Season support

### ISSUE THREAD

**Issue by IronCrystal** [Sonarr/Sonarr#4566]
**Is your feature request related to a problem? Please describe.**
I found a user trakt list for auto importing seasonal anime.
https://trakt.tv/users/sp1ti/lists/anime-summer-2021?sort=rank,asc
Some of the shows imported automatically, but about half of them were not.
I realized that the user had added the show as a "season" item rather than a full show.

**Describe the solution you'd like**
It would be nice if sonarr could parse season info from trakt lists and parse them as tv shows.

**Describe alternatives you've considered**
I couldn't find a way to convert seasons to tv shows on the website so I basically manually imported the shows.

**Additional context**
I assume you'll have to make a second api request to the following endpoint:
https://api.trakt.tv/users/sp1ti/lists/anime-summer-2021/items/seasons?limit=100

**Comment by markus101** [comment]
At this time we do not have plans to support seasons of shows from lists.
