### ISSUE TITLE
Missing episode file on disk when file already has title and title starts with a number.

### ISSUE THREAD

**Issue by UgurEkim** [Sonarr/Sonarr#4573]
**Describe the bug**

If i scan my library of anime and the files already have an episode title (example: XXX - S01E01 - 24 hour), Sonarr report this as "Episode file is missing on drive". It can't read this file, a workarround is to delete episode title and after that it recognizes it again. This only happends when you import existing library to Sonarr and it needs to scan the library.

**To Reproduce**

1. Add existing show to library (existing show has episodes with episode title already on it and an episode where title starts with a number).
2. Go to imported show.
3. Click on Refresh & Scan.
4. See errors regarding episodes where title starts with a number.

**Expected behavior**
It should recognize the episode.

**Screenshots**
Originale episode title name, showing missing file on disk
![1](https://user-images.githubusercontent.com/16925308/125008409-ba2f2200-e062-11eb-9bec-57d23f63bb21.PNG)

Removed episode title
![2](https://user-images.githubusercontent.com/16925308/125008446-d03ce280-e062-11eb-95ec-645acae5186e.PNG)

Clicked on refresh & scan, now episode file is not missing
![3](https://user-images.githubusercontent.com/16925308/125008472-dfbc2b80-e062-11eb-809b-0ea3847cae63.PNG)

Renamed the entire season, returns back to similar episode title name and it's not missing
![4](https://user-images.githubusercontent.com/16925308/125008513-efd40b00-e062-11eb-9256-f761187dcbbc.PNG)

**Platform Information (please complete the following information):**
 - OS: Windows 10 Pro
 - Docker: No
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): .NET 4.8.0
 - Browser and Version (Only needed for UI issues): 
 - Sonarr Version: 3.0.6.1265
 - Sonarr Branch: master (windows installer?)

**Trace Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6788013/sonarr.trace.txt)

**Comment by markus101** [comment]
Next time please ensure the trace logs have the file name that is being parsed.
