### ISSUE TITLE
Wiki Links are Broken and do not abide by WikiJS link standards

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4579]
- [ ] All Wiki Links in-app need to be corrected.  ref (https://github.com/Radarr/Radarr/commit/84d1a8983bee6ec17e4ca11bdcb97ff6254845f2)
- [ ] Review and add missing healthcheck links as needed (ref https://github.com/Radarr/Radarr/commit/5696fa2efef89b829274969c389875aea4b7b4e7)
- [ ] Code correction so useful/correct links are provided
> this seems wrong somewhere?  yet code looks similar to radarr's... but the outputs are not the same

https://github.com/Sonarr/Sonarr/blob/c3d54b312ef18b837d54605ea78f1a263fd6900b/src/Sonarr.Api.V3/ProviderResource.cs#L42-44
```c#
                InfoLink = string.Format("https://wiki.servarr.com/Sonarr_Supported_{0}",
                    typeof(TProviderResource).Name.Replace("Resource", "s"),
                    definition.Implementation.ToLower())
```
> radarr ref <https://github.com/Radarr/Radarr/blob/c23eea21fc544ebbfbd24bef5a395648af62ca6c/src/Radarr.Api.V3/ProviderResource.cs#L42-43>
```c#
                InfoLink = string.Format("https://wiki.servarr.com/radarr/supported-{0}",
                    definition.Implementation.ToLower())
```
> for lists that means the moreinfo link gives "https://wiki.servarr.com/Sonarr_Supported_ImportLists", for say trakt... which is fairly useless
- [X] Supported links need fixing, PR'd https://github.com/Sonarr/Sonarr/pull/4578
As a result of the MediaWiki -> WikiJS changes the wiki links are generally no longer valid. a proxy redirect is on the server to handle redirects in a best effort format, but that cannot modify the somepage#bookmark, bookmark links.  This effectively means the bulk of the in-app links are useless.

Ref previous wiki updates of:
https://github.com/Sonarr/Sonarr/commit/a697a69e886b841356ba5cf795ecf3a939de343d
https://github.com/Sonarr/Sonarr/commit/370280b4bf57ab9e9446f5008a032e8972550331
https://github.com/Sonarr/Sonarr/commit/b84f84ad0a0bab65580e72eb68926dd82bc9fa66
https://github.com/Sonarr/Sonarr/commit/e733529dc3e0c2fe9fbed86dbee6c295627d44f5

All wiki links must now be 1) lowercase and 2) any spaces replaced with `-` not `_` additionally pathing has changed e.g. Sonarr_System is now sonarr/system

**Comment by markus101** [comment]
Links should all be fixed in 021fd4afa70e2e724f3ff3511bda08cf8a3efe0e
