### ISSUE TITLE
Include the public IP in settings

### ISSUE THREAD

**Issue by lethalwallabies** [Sonarr/Sonarr#4581]
**Is your feature request related to a problem? Please describe.**

I route my Sonarr network through a VPN and it can be tedious to ssh onto the host to check the public IP so it could be useful to others with a similar setup to display the public IP in the settings tab.

**Describe the solution you'd like**

Add an additional variable in System/status/about with the output of "curl icanhazip.com"

**Describe alternatives you've considered**

I have tried to look through and see if I could make a fork to bring this feature in but I cannot find where these outputs are being generated to add an additional one so currently I access to docker container and run the command manually.

**Additional context**

**Comment by markus101** [comment]
We do not have plans to fetch the public IP and display it, dynamic DNS is probably your best bet to solve this.
