### ISSUE TITLE
GUI not showing mesages when scanning or anyuthing in lower left corner

### ISSUE THREAD

**Issue by tucker19** [Sonarr/Sonarr#4582]
Environment:
Docker-Compose - 2.4
OS - Ubuntu 20.4 LTS
Sonarr - 3.0.6.1265-ls113 by linuxserver.io

Expected:
When i click `Refresh and Scan` or `Search Monitor` to see messages on GUI in lower left corner of what Sonarr is doing like "searching indexers" and/or "pushing items to download clients"

Issue:
When I click anything I never see messages in the lower left corner anymore. I can open logs within Portainarr and see it but Sonarr no longer displays these messages.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/) [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Check for issues with SignalR in the logs as well as browser's developer tools (console/network tabs).

**Comment by tucker19** [comment]
I have tried and no one helps me. That is why I am opening a ticket up here. This is not a question either. I am reporting a issue I am having.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

from a quick look it does not appear this type of issue has been posted on Reddit nor the forums nor discord recently

regardless markus gave you a direction to look so check that and then swing by our support routes for further discussion if nothing stands out
