### ISSUE TITLE
Sonnar/Jackett use YYMMDD format for daily shows

### ISSUE THREAD

**Issue by arifer612** [Sonarr/Sonarr#4586]
**Is your feature request related to a problem? Please describe.**
I follow a lot of Japanese shows that usually show up with a YYMMDD format in trackers. Even if they do have episode numbers, they would usually be listed as XX回 or epXX on those same trackers.

One example that I had to deal with when setting up a new import is _Hinatazaka de Aimashou_, which is hosted on _aidoru-online_.

**Describe the solution you'd like**
It would be great if we could create search rules for certain indexers. For the same example ealier, the form for the indexer could use the file name tokens to look something like this:
    
    Name: aidoru-online (Hinatazaka de Aimashou)
    Enable RSS: [ ]
    Enable Automatic Search: [ ]
    Enable Interactive Search: [ ]
    Search rule: {AirDate YYMMDD} {Title} ep{episode:0}
    URL: xxxxxxxxxx
    API Key: xxxxxxxxx
    Categories: aaa bbb ccc
    Anime Categories: ddd eee fff

where the token {AirDate YYMMDD} would be a new token just to convert the datestamp into the appropriate format.

**Describe alternatives you've considered**
I have already tried all 3 series types but to no avail. Here are the reason why they all failed:
- Standard: The torrent titles are not listed in the S01Exx format so the query returns nothing.
- Daily: The torrent titles are not listed in the YYYY-MM-DD format so the query returns nothing.
- Anime: The torrent titles are not recognised as having any absolute episode number, so it cannot query.

**Comment by markus101** [comment]
This has less to do with searching than it has to do with parsing, Sonarr doesn't support information outside of release group in square brackets and some other information we can easily strip out to precede the title, so even if Sonarr could search for that format it'd fail to parse it.

We have no plans to support searching that format, but if you can provide some concrete release names that use that format we can look to see if we can make it parse properly, so it'll at least work with RSS.

**Comment by arifer612** [comment]
Thank you for replying and I respect that decision. This is a screenshot of a segment from one of the trackers I peruse for my Japanese TV shows. The standard on the tracker(s) uses YYMMDD for most of their shows.
![Screenshot from 2021-07-20 12-21-45](https://user-images.githubusercontent.com/46054733/126261471-5d8e98ba-38ce-4d8c-a3b4-b17ea8fa42ef.png).

**Comment by thezoggy** [comment]
YYMMDD is only used by some random asian releases.. thats not scene / standard. while the air-by-date format is.

**Comment by Taloth** [comment]
Of all those titles, only these would potentially be parsable if we throw away the prefixed date:
- SKE48 Zero Position ep150 (but 150 doesn't exist on tvdb)
- Hinatazaka de Aimashou ep117

That's it, the rest either aren't parsable or have bad titles. Atm I'm not convinced it's worth the effort.

**Comment by markus101** [comment]
Yeah, I'm thinking the same, going to close this as most are just unparsable.

**Comment by arifer612** [comment]
The shows that are missing in the TVDB database can always be added on afterwards, it's just a matter of data entry. The problem is that even when the prefixed dates are thrown away, these torrents cannot be searched from the tracker because the trackers treat these shows as ordered by date and not in the standard episode format.

Doing an interactive search for `Hinatazaka de Aimashou ep 117` on my trackers, a snippet of `sonarr.debug` gives me this:

```
2021-08-04 16:34:41.9|Info|NzbSearchService|Searching 7 indexers for [Hinatazaka de Aimashou : S01E116]
2021-08-04 16:34:42.0|Debug|NewznabRequestGenerator|Indexer capabilities lacking season & ep query parameters, no Standard series search possible.
2021-08-04 16:34:42.0|Debug|NewznabRequestGenerator|Indexer capabilities lacking season & ep query parameters, no Standard series search possible.
2021-08-04 16:34:42.0|Debug|Torznab|Downloading Feed http://192.168.10.10:9696/5/api?t=tvsearch&cat=5000,5050,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Hinatazaka%20de%20Aimashou&season=1&ep=116
2021-08-04 16:34:42.0|Debug|Torznab|Downloading Feed http://192.168.10.10:9696/1/api?t=tvsearch&cat=5000,5045,5040,5030&extended=1&apikey=(removed)&offset=0&limit=100&q=Hinatazaka%20de%20Aimashou&season=1&ep=116
2021-08-04 16:34:42.0|Debug|Torznab|Downloading Feed http://192.168.10.10:9696/7/api?t=tvsearch&cat=5000,5070&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=362695&season=1&ep=116
2021-08-04 16:34:42.0|Debug|Torznab|Downloading Feed http://192.168.10.10:9696/2/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&q=Hinatazaka%20de%20Aimashou&season=1&ep=116
2021-08-04 16:34:42.0|Debug|Torznab|Downloading Feed http://192.168.10.10:9696/6/api?t=tvsearch&cat=5000,5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Hinatazaka%20de%20Aimashou&season=1&ep=116
2021-08-04 16:34:43.3|Debug|Torznab|Downloading Feed http://192.168.10.10:9696/7/api?t=tvsearch&cat=5000,5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Hinatazaka%20de%20Aimashou&season=1&ep=116
2021-08-04 16:34:48.7|Debug|NzbSearchService|Total of 0 reports were found for [Hinatazaka de Aimashou : S01E116] from 7 indexers
```
where the 2 trackers that were not searched were the only 2 where the torrent is posted to.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

looks like that should be an anime search if you want 116 not a season episode search

**Comment by arifer612** [comment]
Thank you for your reply, but I believe that my comment above is relevant to this thread since it was the very reason why I opened the issue. Setting it as an anime type series would not work either because it does not have an absolute episode number: 

```
Search failed because its absolute episode number is missing. Try refreshing the series info and verify the necessary information is present before searching again
```

It's recorded as a standard TV series on TVDB with a season and episode number.

**Comment by bakerboy448** [comment]
The fix there would be the add the absolute number to TVDB

regardless it really comes down to release groups not following the existing sane standards and doing their own custom thing against the grain

**Comment by arifer612** [comment]
Well, this is the standard for the Japanese Idol TV shows on private trackers for almost a decade and only one of them gives the option of showing the `sane' date standards, but I digress. I just thought that it would be a good thing to be able to have some sort of regexp manipulation to fine-tune search terms like what flexget has.
