### ISSUE TITLE
Add upgrade options for audio (like exist for video)

### ISSUE THREAD

**Issue by TheFiZi** [Sonarr/Sonarr#4587]
**Is your feature request related to a problem? Please describe.**
It is not.

**Describe the solution you'd like**
Sonarr allows you to specify a maximum video quality to upgrade downloads to it would also be nice if I could specify the same for audio quality. For example if I get a 1080p stereo download of something and then a 1080p DD5.1 becomes available I'd like Sonarr to automatically upgrade my copy.

I realize audio in filenames is not as consistent as video quality but in theory if someone builds it, they might come?

I've dug through my download history and attempted to help get started. This list is from lowest to highest quality (with a priority on surround sound over stereo) to the best of my knowledge of audio codecs:

```
AAC 2 0
AAC2 0
LPCM 1 0
LPCM 2 0
DD
DD 2 0
DD2 0
AC3
AC3 5 1
DD 5 1
DD5 1
DDP
DDP 5 1
DDP5 1
DTS
DTS-ES
E-AC3
DTS-HD HR
DTS:X
TrueHD
TrueHD 5 1
TrueHD 7 1
TrueHD5 1
TrueHD7 1
DTS-MA (probably a typo)
DTS-HD MA
DTS-HD MA 2 0
DTS-HD MA 5 1
Atmos
```

Hopefully that will help save some time if this feature request is accepted. Again, this is my best guess on ordering (with a priority on surround sound over stereo). If I'm wrong, re-order them :)

I am going to submit a similar request to Radarr. Hopefully if they adopt it too uploaders will start adding the audio format to filenames more consistently.

**Describe alternatives you've considered**
I do this manually from time to time when the stereo mix of something is complete trash.

**Additional context**
N/A

**Comment by markus101** [comment]
At the moment we do not have plans to support upgrading based on audio, the closest you can get is to use preferred words in Sonarr or custom formats in Radarr.
