### ISSUE TITLE
simpler, radarr-like ssl support

### ISSUE THREAD

**Issue by 0000matteo0000** [Sonarr/Sonarr#4588]
I can't use prebuilt Sonarr dockers with HTTPS/SSL due to the lack of SSL configuration options.
I think an easy fix for this is using the same way Radarr manages SSL and enabling selecting a certificate from the system, making it easy to mount it in a docker volume.
Running the commands needed to add the certificate inside the docker is out of the question, since every reboot will undo the changes.

**Comment by Taloth** [comment]
In this case it's better to use a ssl-terminating reverse proxy container. For example with nginx. Easier to maintain up to date certificate too.

Regardless, Radarr and Sonarr use different runtimes which do https fundamentally different. So no 'easy fix'.

Embedded tls support will likely improve once we switch to a newer runtime, but that's not planned anytime soon.
