### ISSUE TITLE
Permission hell

### ISSUE THREAD

**Issue by cybercussion** [Sonarr/Sonarr#4589]
ODROID XU4, UBUNTU 18.04.

User Sonarr, Group Sonarr - no access.
Change to odroid user .. now API fails to start.
Uninstall
Try to find files to remove to reset it all
Try to change folder permissions.
Sticky settings won't let me get past it.

Need a cleanup script or something to completely defunk the install.

**Comment by Taloth** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK) for support/questions.
