### ISSUE TITLE
Error with SignalR in Sonarr with Bazarr 

### ISSUE THREAD

**Issue by Pedernalesiii** [Sonarr/Sonarr#4590]
Hi, I have this following issue about few days.

The problem:
Bazarr hang up when trying to config with Sonarr (with Radarr works fine), bazarr keep saying "BAZARR cannot parse JSON returned by SignalR feed. This is a known issue when Sonarr doesn't have write permission to it's /config/xdg directory", and I don't have any "xdg" directory on Sonarr Config Directory. With Bazarr support trying various alternatives, but with no luck.

The actions I took:
I delete everything about my htpc configuration, this include, delete all images in docker, delete all volumes in docker, delete all config directories... the only thing that, of course, i don't delete was my media files.
I install every app again with "docker-compose up", all images downloaded and services up again.
Again, no "xdg" directory on Sonarr, and bazarr config of Sonarr get stuck again with the same messages...

Environment
**OS: Docker Desktop 3.5.2 (66501), Engine:20.10.7 on Windows 10 WSL 2 Ubuntu 20.04 LTS
CPU architecture: x86_64 (Intel i5)
How docker service was installed:
From Official WebPage.

Command used to create docker container (run/create/compose/screenshot)
Docker-Compose.yml
---
sonarr:
container_name: sonarr
image: linuxserver/sonarr:latest
restart: unless-stopped
#network_mode: "host"
environment:
- PUID=${PUID} # default user id, defined in .env
- PGID=${PGID} # default group id, defined in .env
- TZ=${TZ} # timezone, defined in .env
- DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
- TP_THEME=plex
volumes:
- /etc/localtime:/etc/localtime:ro
- ${ROOT}/config/sonarr:/config # config files
- ${ROOT}/downloads:/downloads # download folder
- ${MediaDrv}/Series:/tv # TV Shows Folder

ports:
  - 8989:8989 # port for sonarr web UI to be reacheable from local network
***---- ***
Sonarr Version: 3.0.6.1265, Package Version 3.0.6.1265-ls113 by linuxserver.io
Mono Version 5.20.1.34
Bazarr Version 0.9.6
Radarr Version 3.2.2.5080
[docker_sonarr_log.txt](https://github.com/Sonarr/Sonarr/files/6869017/docker_sonarr_log.txt)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

**Comment by Taloth** [comment]
> `${ROOT}/config/sonarr:/config # config files`

`${ROOT}/config/sonarr/.config/.mono/` (aka `/config/.config/.mono/`) likely has the wrong permissions. But as bakerboy said, use the support channels please for further questions.

`/config/xdg` doesn't and shouldn't exist, it was an ancient old workaround used by linuxserver docker.

**Comment by Pedernalesiii** [comment]
Ok, thanks to both.
