### ISSUE TITLE
Sonarr is misidentifying the audio language

### ISSUE THREAD

**Issue by derekantrican** [Sonarr/Sonarr#4593]
**Describe the bug**

Sonarr interactive search screen:
![image](https://user-images.githubusercontent.com/1558019/127203282-d8947da3-120f-4751-8882-7bee2f706082.png)

NZBGeek listing (clicking on the hyperlink in the above screenshot):
![image](https://user-images.githubusercontent.com/1558019/127203365-3947ad59-4317-4c2b-8e8c-721d62ad7888.png)

Note that Sonarr lists the language as "English" while NZBGeek lists the language as "German" (NZBGeek is correct in this case)

**Expected behavior**
I would expect the language to be listed the same as the Indexer shows

**Platform Information (please complete the following information):**

 - OS: Windows 10
 - Docker: No
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): .NET Framework 4.8.0
 - Browser and Version (Only needed for UI issues):  Firefox 89.0.2
 - Sonarr Version: 3.0.6.1265
 - Sonarr Branch: main

**Comment by markus101** [comment]
Sonarr uses the release name for language detection, as the release name lacks the language it's treated as English by Sonarr. Unfortunately the information provided on the indexer site often isn't provided by the API (or at least in a consistent way) that Sonarr can utilize.
