### ISSUE TITLE
Episode renaming needs to follow CIFS/SMB standards

### ISSUE THREAD

**Issue by herkalurk** [Sonarr/Sonarr#4595]
**Describe the bug**
This is my first forray into sonarr, while playing with the episode renamer formatting, I ran into an issue where the naming of a show was hitting a name/word for reserved/restricted CIFS/SMB filenames.  This caused the files not to be named as to what sonarr thought it was naming them via the network share.

In this particular case I was testing the renamer on the show Con Man.  Apparently having the word 'Con' as a standalone is a no no and caused the issue.  I manually renamed all of the episodes from Con.Man to ConMan prefix and then the problem was resolved.  The renamer still wants to move them back - screenshot below.

CLI output from my nas via SSH where I can see the NAS has no problem with the names.

```
user@nas:/volume2/tv/Conman/S02$ ls
Con.Man.S02E01.WEBRip-480p.x264.EAC3.mkv  Con.Man.S02E05.WEBDL-1080p.x265.AAC.mkv  Con.Man.S02E09.WEBDL-1080p.x265.AAC.mkv
Con.Man.S02E02.WEBRip-480p.x264.EAC3.mkv  Con.Man.S02E06.WEBDL-1080p.x265.AAC.mkv  Con.Man.S02E10.WEBDL-1080p.x265.AAC.mkv
Con.Man.S02E03.WEBRip-480p.x264.EAC3.mkv  Con.Man.S02E07.WEBDL-1080p.x265.AAC.mkv  Con.Man.S02E11.WEBDL-1080p.x265.AAC.mkv
Con.Man.S02E04.WEBDL-1080p.x265.AAC.mkv   Con.Man.S02E08.WEBDL-1080p.x265.AAC.mkv  Con.Man.S02E12.WEBDL-1080p.x265.AAC.mkv
```
SMB client connected to the share, in this case Centos 7, but same filename experience was shown from Windows Explorer
```
[user@server S02]$ ls
C151LR~J.MKV  C1I92O~0.MKV  C3F775~A.MKV  C3YVCM~S.MKV  CACV52~N.MKV  CAHZLX~N.MKV  CAIPQM~M.MKV  CDF3W4~H.MKV  CF0SKZ~4.MKV  CKI8UD~M.MKV  CNHUI6~0.MKV  COCQAL~1.MKV
```
I renamed the files via the SSH session to NAS
```
user@nas:/volume2/tv/Conman/S02$ ls | while read line; do mv ${line} $(echo ${line} | sed 's/Con\.Man/ConMan/g');done
user@nas:/volume2/tv/Conman/S02$ ls
ConMan.S02E01.WEBRip-480p.x264.EAC3.mkv  ConMan.S02E05.WEBDL-1080p.x265.AAC.mkv  ConMan.S02E09.WEBDL-1080p.x265.AAC.mkv
ConMan.S02E02.WEBRip-480p.x264.EAC3.mkv  ConMan.S02E06.WEBDL-1080p.x265.AAC.mkv  ConMan.S02E10.WEBDL-1080p.x265.AAC.mkv
ConMan.S02E03.WEBRip-480p.x264.EAC3.mkv  ConMan.S02E07.WEBDL-1080p.x265.AAC.mkv  ConMan.S02E11.WEBDL-1080p.x265.AAC.mkv
ConMan.S02E04.WEBDL-1080p.x265.AAC.mkv   ConMan.S02E08.WEBDL-1080p.x265.AAC.mkv  ConMan.S02E12.WEBDL-1080p.x265.AAC.mkv
```
Now the client can read the filenames appropriately
```
[user@server S02]$ ls
ConMan.S02E01.WEBRip-480p.x264.EAC3.mkv  ConMan.S02E04.WEBDL-1080p.x265.AAC.mkv  ConMan.S02E07.WEBDL-1080p.x265.AAC.mkv  ConMan.S02E10.WEBDL-1080p.x265.AAC.mkv
ConMan.S02E02.WEBRip-480p.x264.EAC3.mkv  ConMan.S02E05.WEBDL-1080p.x265.AAC.mkv  ConMan.S02E08.WEBDL-1080p.x265.AAC.mkv  ConMan.S02E11.WEBDL-1080p.x265.AAC.mkv
ConMan.S02E03.WEBRip-480p.x264.EAC3.mkv  ConMan.S02E06.WEBDL-1080p.x265.AAC.mkv  ConMan.S02E09.WEBDL-1080p.x265.AAC.mkv  ConMan.S02E12.WEBDL-1080p.x265.AAC.mkv
```

**Expected behavior**

I understand you can't account for everything, but I hope you could modify the renaming service/function to validate the names aren't going to violate established standards.  Please review the KB I read to fix the issue [here](https://kb.synology.com/en-global/DSM/tutorial/file_or_folder_name_displayed_as_12HWA0_8).

**Screenshot**
![image](https://user-images.githubusercontent.com/2532699/127441064-5aa277f6-82d1-460a-87eb-b90916ed51e3.png)

**Platform Information (please complete the following information):**

 - OS: Centos 7
 - Docker: Yes
 - Sonarr Version: 3.0.6.1265
 - Sonarr Branch: main/master

**Comment by thezoggy** [comment]
CON is a reserved word on windows, not an issue to use it when you use the \\?\ notation though. honestly this is such an edge case.. personally i would just suggest to not have sonarr rename that show/remove it from sonarr  to stop it from renaming

https://github.com/sabnzbd/sabnzbd/pull/771#issuecomment-278032464
--

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.

talking about namespace about that when using \\?\ notation how the reserved words are not an issue:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#namespaces

**Comment by herkalurk** [comment]
While I appreciate those Microsoft articles, my report shows the same experience on Linux, it's a part of the file share protocols.  I know that really out of that list only Con is the one that's likely to creep up again.  I'm not planning on having Sonarr rename at this point.  The show is ended so I've marked as unmonitored and my settings only use the renamer for current downloads.  I don't plan on renaming my entire library when everything is working fine with Plex as is.

**Comment by bakerboy448** [comment]
Already fixed in nightly
