### ISSUE TITLE
Adding to Title Slug

### ISSUE THREAD

**Issue by Indochild56** [Sonarr/Sonarr#4596]
I know i'm probably thinking this is easier than it is, but is there any way to amend the show title slug when a show is added. It creates a lot of issues when shows have the same name or similar name.

one example is 60 Minutes (slug is 60-minutes)
and the streaming only version 60 Minutes+ (slug is also 60-minutes)

so users are forced to add only one of these shows because of this issue. maybe amending the year or the TMDB id would solve the issue?

**Comment by Taloth** [comment]
Nah, just report these duplicates on our support channels (discord, irc or forums) and we'll override the slug.

I've updated 397962, it should make it through the caches within an hour, probably way earlier.
