### ISSUE TITLE
Blacklist doesn't seem to work on delayed grabs

### ISSUE THREAD

**Issue by austinwbest** [Sonarr/Sonarr#4598]
**Describe the bug**
When an item is added to activity with a delay grab, you cant blacklist it. 

I had 2 items added but didn't want them as they where a rartv release so i clicked the x and picked remove from client (which you cant even do by the way because it is on a delay and not even grabbed yet so this is kinda wrong) and also checked to blacklist the release and hit save. It did remove the item from the activity but it **did not** blacklist the releases. A short time later they showed up in activity again but the delay had passed before i noticed so they where grabbed this time and stuck in the queue for dht errors, so i once again hit the x and removed from client and blacklisted. This time they did blacklist as expected.

**To Reproduce**
Blacklist something that is in a delay state

Expected behavior
Blacklist the release or remove the option

Platform Information (please complete the following information):

OS: Windows
Docker: No
.net Framework (Windows) or mono (macOS/Linux) (System -> Status): 4.8.0
Browser and Version (Only needed for UI issues): Chrome Version 91.0.4472.124 (Official Build) (64-bit)
Sonarr Version: 3.0.6.1278
Sonarr Branch: develop

**Trace Logs**
I searched the newest 3 trace logs for the release name and could not find anything related to the blacklist, only the entry into activity with the delay

**Comment by markus101** [comment]
I have a fix for this, but will wait for https://github.com/Sonarr/Sonarr/pull/4572 to land first.
