### ISSUE TITLE
Tooning Out The News: Episode search failed: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by JacquelineHyde** [Sonarr/Sonarr#4599]
"Object reference not set to an instance of an object" when searching for episodes

**To Reproduce**
1. Add Tooning Out The News, 
2. Set as series type daily
3. Click on Interactive search

**Platform Information (please complete the following information):**
 - OS: Synology DSM
 - Docker: Yes/No
- Version: 3.0.6.1265
- Package Version: 3.0.6.1265-ls114 by linuxserver.io
- Mono Version: 5.20.1.34
- Mode: Console

**Trace Logs**
https://pastebin.com/0HD8xJxg

**Comment by PearsonFlyer** [comment]
Daily type series cannot have multiple episodes with the same date. This causes an error in the system. You will need to unmonitor those episodes (both episodes with the same date) in order to eliminate the error.
