### ISSUE TITLE
Fix header/menu on Calendar page

### ISSUE THREAD

**Issue by Nedlinin** [Sonarr/Sonarr#4601]
**Is your feature request related to a problem? Please describe.**
I sometimes have a fairly large calendar and when I scroll to the bottom of it I have to scroll back up to the top in order to switch to the next/previous month.

**Describe the solution you'd like**
Have the CalendarHeader div be fixed to the top of that pane.

**Describe alternatives you've considered**
None?

**Additional context**

[Current behavior](https://youtu.be/ci-atbwgSE8)

[Desired behavior](https://youtu.be/ChKbBwRGlxU)

**Comment by Nedlinin** [comment]
Tinkering with this in uBlock origin I've gotten

```
div[class^='CalendarPage-calendarPageBody'] { inset: 45px 0px 0px 0px !important; }
div[class^='CalendarPage-calendarInnerPageBody']{ padding:0px 20px 20px 20px !important; }
div[class^='CalendarHeader-header']{ position:fixed; top:130px; width:100%; padding: 0px 20px 0px 20px; }
```

to work fairly nicely though I'm honestly garbage at CSS and I'm sure there is a better way to do this that doesn't require users to deal with an extra extension.  

Fairly confident this could use better selectors but the additional generated portion during builds would cause me to have to reedit this everytime so I'm using a prefix selector instead.

These changes have resulted in this: https://youtu.be/ywg5zrgZiYM which gives the sticky header without elements flowing behind the menu bar as in the "Desired" clip above.

**Comment by markus101** [comment]
This isn't something we plan to do at this time.

**Comment by Nedlinin** [comment]
@markus101 : Is this something you're willing to accept a community PR for or would it just be rejected?

**Comment by markus101** [comment]
In general it’s not something we want to have implemented and supported at this time. To properly support it would require an overhaul to the design in some ways and also support static day headers. At this time it’s not something we’re going to consider.

**Comment by Nedlinin** [comment]
In case someone else comes across this and wants a semi hacky uBlock Origin fix for this..

```
sonarr.domain.com#$#div[class^='CalendarPage-calendarPageBody'] { inset: 45px 0px 0px 0px !important; }
sonarr.domain.com#$#div[class^='CalendarPage-calendarInnerPageBody']{ padding: 0px 20px 20px 20px !important; }
sonarr.domain.com#$#div[class^='CalendarHeader-header']{ position:fixed; top:130px; width:100%; padding: 0px 20px 0px 20px; }
sonarr.domain.com#$#div[class^='CalendarDays-days']{ padding-top: 16px; }
sonarr.domain.com#$#div[class^='DaysOfWeek-daysOfWeek']{ position:fixed; top: 150px; width: 100%; }
```

Obviously if the HTML/styling changes significantly this won't continue to work but this works great in Version
3.0.6.1265.
