### ISSUE TITLE
possible issue? NFS share

### ISSUE THREAD

**Issue by madmann26** [Sonarr/Sonarr#4602]
So I built a TrueNAS box and moved my tv/movie/music storage to this. It's an NFS share. I can mount/browse/read/write/delete from the Ubuntu VM, Plex can browse it, Sonarr/Radarr/Lidarr can even browse it. I updated the root folders on all 3 apps and mass edited my content to reflect the new path.

Sonarr 'knows' about the content and can see it as it's reporting number of episodes/missing/etc. I also edited /etc/fstab and commented out the previous share and rebooted the VM a few times so it's definitely not seeing the old share.

But under 'System Status' it does not display the share and space. Same with Radarr but the weird thing is Lidarr displays it just fine.

Thoughts?

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
