### ISSUE TITLE
Sort Indexers in Settings by Priority or Enabled Status

### ISSUE THREAD

**Issue by misleadingrhino** [Sonarr/Sonarr#4605]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to sort indexers in the settings view by Priority and Enabled vs Disabled.

**Additional context**
Thanks to the release of Prowlarr, I have a lot of duplicate indexers that I don't want to delete since copying and pasting urls and API tokens is a pain. Would be nice to be able to have all of the enabled indexers at the top.

**Comment by markus101** [comment]
We do not have plans to change the sort order, if you're keeping duplicate indexers around you could edit the name to change the sort order.
