### ISSUE TITLE
"More Info" Links are generic and do not provide purposeful links

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4607]
breaking off from #4579

https://github.com/Sonarr/Sonarr/blob/develop/src/Sonarr.Api.V3/ProviderResource.cs 42-44
https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Api/ProviderModuleBase.cs 122-123

Download Clients, Import Lists, etc.  More Info Links are generic `https://wiki.servarr.com/sonarr/supported#downloadclients` and `https://wiki.servarr.com/sonarr/supported#importlists`

Option A - Remove the More Info Links given there is no purpose to have the same link for every item and it provides no unique use.  Just have a single More Info Link for each modal not each item within a modal.

Option B - Correct the code to match downstream so the links are relevant to the item the more info link is attached to.

e.g.  for List -> Sonarr Import we should get `https://wiki.servarr.com/sonarr/supported#sonarrimport`

**Comment by markus101** [comment]
Discussing on Discord, we don't need an issue for this.
