### ISSUE TITLE
Tags Getting Removed

### ISSUE THREAD

**Issue by fastgriz** [Sonarr/Sonarr#4610]
https://github.com/Sonarr/Sonarr/blob/38feeefea3fcab94ee20b2b61571e786d2511636/src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupUnusedTags.cs#L22

**Describe the bug**

Basically the clean tags process don't count indexers and lists as tags in use only the entities listed on that line

I put "trakt" in the "Sonarr Tags" field of an import list and set up a filter to display all series with where "Tags contains trakt".

Then a few days later, the Sonar Tags field in the import list settings shows up blank, and the filter has changed itself to "Tags contains "

**To Reproduce**

1. Navigate to Settings>Import Lists and create a new Trakt list
2. Populate the "Sonarr Tags" field with the text "trakt"
3. Navigate to Series and click the "Filter" pulldown, select "Custom Filters"
4. Click "Add Custom Filter"
5. Populate the "Label" field with the text "Test Filter"
6. Use the pulldown fields under "Filters" to select "Tags" "contains" "trakt"

**Expected behavior**
The "trakt" tab should be available whenever tags can be specified such as when creating a Filter or editing a series.   Series added by the list using that tag should show up when a filter is created to show series containing that tag.

**Platform Information (please complete the following information):**

- OS: Windows 10 Pro
- Docker: No
- .net Framework (Windows) or mono (macOS/Linux) (System -> Status): .NET 4.8.0
- Browser and Version: Chrome Version 92.0.4515.131 (Official Build) (64-bit)
- Sonarr Version: 3.0.6.1265
- Sonarr Branch: main

**Comment by markus101** [comment]
So the tag is being removed, not corrupted? Please fill out the complete bug template.
