### ISSUE TITLE
Multi episode not recognized by sonarr

### ISSUE THREAD

**Issue by Bazzu85** [Sonarr/Sonarr#4613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, as suggested from mrbakerboy here’s the issue

This file:
Teen Titans Go! (2013) - S04E44-E45 - Il 200 spettacolare episodio da narcisisti! [NetflixHD 720p HEVC] [ITA+ENG]
is not grabbed from sonarr

![image](https://user-images.githubusercontent.com/7345587/128601305-6a69838d-ba15-40ff-810c-2a206ff1e509.png)

![image](https://user-images.githubusercontent.com/7345587/128601314-b317b625-13f4-42da-ba73-95734daa8fbd.png)

![image](https://user-images.githubusercontent.com/7345587/128601325-05105e4b-a6c1-417f-8270-db1860aeb197.png)

![image](https://user-images.githubusercontent.com/7345587/128601405-a4a85ac5-822b-427b-bff4-7df9dbb54c88.png)

here’s the logs:
https://pastebin.com/fRLrm4L7

the problem is the “200” inside the file..

thx

### Expected Behavior

The file have to be recognized as multi episode 44-45

### Environment

```markdown
- OS: Windows 10 pro
- Sonarr: 3.0.6.1265
- Docker Install: no
- Using Reverse Proxy: no
- Browser: all
```

### What branch are you running?

Main

### Anything else?

logs: https://pastebin.com/fRLrm4L7

**Comment by bakerboy448** [comment]
it seems the 200 is causing the anime logic to be used; this also causes the release group to be detected improperly 

![D8C402D8-2B8A-4DAC-BF43-6FA51DB3E1F6](https://user-images.githubusercontent.com/55419169/128601747-6c628eef-3fcd-4240-8fca-dc6b3107b3bd.png)
![E6FCB47D-A9A9-4D9C-9833-9E8C38644F5A](https://user-images.githubusercontent.com/55419169/128601749-801b34dc-dae6-4d69-b814-84c7478676d8.png)

**Comment by Bazzu85** [comment]
Additionally, the series type is "standard"
