### ISSUE TITLE
Nyaa seeders/leechers not parsed properly anymore.

### ISSUE THREAD

**Issue by lotrez** [Sonarr/Sonarr#4614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During interactive research and probably automatic, a search using the predefined nyaa.si indexer returns unknown leechers and seeders. Making automatic grabbing impossible as it needds X amount of seeders.

### Expected Behavior

Nyaa.si seeders and leechers by torrent properly parsed, returning their numbers.

### Steps To Reproduce

Go on series where not all epsiodes are downloaded and click interactive search with a nyaa indexer.

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 3.0.6.1265
- Docker Install: As a service
- Using Reverse Proxy: Yes
- Browser: Chrome 92.0.4515.131
```

### What branch are you running?

Main

### Anything else?

Looks like [test files](https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core.Test/Files/Indexers/Nyaa/Nyaa.xml) for the nyaa indexers aren't right anymore.
`<description><![CDATA[1 seeder(s), 2 leecher(s), 0 download(s) - 2.35 GiB]]></description>`
is now
`<nyaa:seeders>1</nyaa:seeders>
<nyaa:leechers>2</nyaa:leechers>`

**Comment by snattack** [comment]
As of 19 march 2022, still not fixed. At least doesn't work on full seasons. "Sometimes" work on single episodes.

**Comment by bakerboy448** [comment]
> As of 19 march 2022, still not fixed. At least doesn't work on full seasons. "Sometimes" work on single episodes.

The issue is still open so of course it is not fixed.
