### ISSUE TITLE
Latest version of Sonarr not pushed to apt repository?

### ISSUE THREAD

**Issue by briandipalma** [Sonarr/Sonarr#4617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installing on a fresh LXC only grabs v3.0.6.1196 not v3.0.6.1266

### Expected Behavior

Installing on a fresh LXC should grab v3.0.6.1266

### Steps To Reproduce

.

### Environment

```markdown
.
```

### What branch are you running?

Main

### Anything else?

.

**Comment by briandipalma** [comment]
This is the Ansible script for the installation: https://github.com/briandipalma/proxmox-services/blob/main/ansible/roles/sonarr/tasks/main.yml just in case I'm making a mistake?

**Comment by bakerboy448** [comment]
The apt repo is updated on an ad-hoc periodic basis.

The repo should install with update_required and sonarr will update on its initial startup

**Comment by briandipalma** [comment]
OK, I see.
