### ISSUE TITLE
Sonarr renaming season posters (png, jpeg) as episodes and moving into season folders

### ISSUE THREAD

**Issue by frankrende** [Sonarr/Sonarr#4624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using the Plex season poster naming convention (i.e. season-1, season-2 ... season-12). If I perform a rename after adding new episodes, Sonarr seems to grab any season poster greater than season 9 and includes it as a file to rename. This keeps messing up my posters in Plex.

Recording: https://gfycat.com/parallellastamericanriverotter

I posted this issue to Reddit and one of the [devs confirmed](https://www.reddit.com/r/sonarr/comments/nvy069/sonarr_renaming_season_posters_png_jpeg_as/h1n9om0/) this is likely a bug.

### Expected Behavior

Image files are ignored and not moved. They also don't appear in the rename preview, so there's no expectation that they'd be modified.

### Environment

```markdown
- OS: Windows 10
- Sonarr: 2.0.0.5344 & 3.0.6.1265
- Docker Install: No
- Using Reverse Proxy: No
- Browser:
```

### What branch are you running?

Main

### Anything else?

Trace Log - Here's the portion where it finds "season-10.png" and processes it. It was in the root folder (**E:\TV Shows\Criminal Minds\season-10.png**) and after processing it was **E:\TV Shows\Criminal Minds\Season 1\Criminal Minds - S01E10 - The Popular Kids (WEBDL-1080p).png**

    21-6-9 21:24:15.4|Debug|Parser|Parsing string 'season-10.png'
    21-6-9 21:24:15.4|Trace|Parser|^(?:\[(?<subgroup>.+?)\][-_. ]?)?(?<title>.+?)(?:[-_. ]+(?<absoluteepisode>(?<!\d+)\d{2,3}(\.\d{1,2})?(?!\d+)))+(?:_|-|\s|\.)*?(?<hash>\[.{8}\])?(?:$|\.)?
    21-6-9 21:24:15.4|Debug|Parser|Episode Parsed. season - 010 
    21-6-9 21:24:15.4|Debug|Parser|Language parsed: English
    21-6-9 21:24:15.4|Debug|QualityParser|Trying to parse quality for season-10.png
    21-6-9 21:24:15.4|Debug|Parser|Quality parsed: Unknown v1
    21-6-9 21:24:15.4|Debug|Parser|Release Group parsed: 
    21-6-9 21:24:15.4|Debug|Parser|Parsing string 'season-10.png'
    21-6-9 21:24:15.4|Trace|Parser|^(?:\[(?<subgroup>.+?)\][-_. ]?)?(?<title>.+?)(?:[-_. ]+(?<absoluteepisode>(?<!\d+)\d{2,3}(\.\d{1,2})?(?!\d+)))+(?:_|-|\s|\.)*?(?<hash>\[.{8}\])?(?:$|\.)?
    21-6-9 21:24:15.4|Debug|Parser|Episode Parsed. season - 010 
    21-6-9 21:24:15.4|Debug|Parser|Language parsed: English
    21-6-9 21:24:15.4|Debug|QualityParser|Trying to parse quality for season-10.png
    21-6-9 21:24:15.4|Debug|Parser|Quality parsed: Unknown v1
    21-6-9 21:24:15.4|Debug|Parser|Release Group parsed: 
    21-6-9 21:24:15.5|Debug|Parser|Parsing string 'season-10.png'
    21-6-9 21:24:15.5|Trace|Parser|^(?:\[(?<subgroup>.+?)\][-_. ]?)?(?<title>.+?)(?:[-_. ]+(?<absoluteepisode>(?<!\d+)\d{2,3}(\.\d{1,2})?(?!\d+)))+(?:_|-|\s|\.)*?(?<hash>\[.{8}\])?(?:$|\.)?
    21-6-9 21:24:15.5|Debug|Parser|Episode Parsed. season - 010 
    21-6-9 21:24:15.5|Debug|Parser|Language parsed: English
    21-6-9 21:24:15.5|Debug|QualityParser|Trying to parse quality for season-10.png
    21-6-9 21:24:15.5|Debug|Parser|Quality parsed: Unknown v1
    21-6-9 21:24:15.5|Debug|Parser|Release Group parsed: 
    21-6-9 21:24:15.5|Debug|Parser|Parsing string 'season-11.png'

**Comment by Taloth** [comment]
First step should be to update sonarr. Coz you're on v2, and that's end of life. Check https://sonarr.tv/#downloads-v3-windows for instructions.

Let us know if the problem persists afterwards and we'll take another look.

**Comment by frankrende** [comment]
Hey @Taloth - thanks for the tip! I just upgraded and unfortunately the same behavior is still occurring in v3

**Comment by markus101** [comment]
Based on Plex's documentation the correct format for season posters is: `/TV Shows/ShowName/Season XX/SeasonXX.ext` not `TV Shows/ShowName/season-XX`, offhand I'm not sure if that format is supported by Sonarr, but the current files are being parsed as treated as absolutely numbered files.

https://support.plex.tv/articles/200220717-local-media-assets-tv-shows/
