### ISSUE TITLE
Sonarr destroys the torrent structure

### ISSUE THREAD

**Issue by issaccv** [Sonarr/Sonarr#4627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am a Chinese user, and when I use sonarr to grab a torrent from jackett indexer: tjupt.org, the torrent won't start automatically because the hash of torrent has been changed by sonarr, so the tracker won't return the proper peers.

### Expected Behavior

In the origin torrent file hosted by tjupt.org, there is an entry:
- encoding:UTF-8
And when my sonarr grabs the torrent from jackett and push it to qbittorrent, the entry should be reserved or it will change the hash of the torrent.

### Steps To Reproduce

1. Lastest stable sonarr
2. Grab a torrent has encoding:utf-8 entry
3. See the different torrent hash in qbittorrent.

### Environment

```markdown
- OS: Unraid 6.9.2
- Sonarr: Sonarr 3.0.6.1265
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome 92.0.4515.131(UI not related)
```

### What branch are you running?

Main

### Anything else?

To make it more clear, I use BEncode to show the difference between the file I download directly from the site, and the file I save from qBittorrent. And I also tried to download the torrent from jackett indexer which turns out to be same as the origin one.
- This one is download directly from site. Same as download from jackett.
![Download directly from site](https://user-images.githubusercontent.com/17275050/129372439-3526a98d-2023-41d8-96d2-d2e3c0643fc4.png)
- This one is saved from qbittorrent.
![Save from qBittorrent](https://user-images.githubusercontent.com/17275050/129372775-ffdb2a26-7320-4900-afb2-7c8ef08fd40e.png)

I guess the missing of encoding entry leads to the mess of behavior.

**Comment by thezoggy** [comment]
due to bad env ? (locale not setup)

**Comment by issaccv** [comment]
> due to bad env ? (locale not setup)

Unraid will setup it automatically, and here is the env info from `docker inspect sonarr` command:

```shell
"Env": [
         "TZ=Asia/Shanghai",
         "HOST_OS=Unraid",
         "PUID=99",
         "PGID=100",
         "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
         "HOME=/root",
         "LANGUAGE=en_US.UTF-8",
         "LANG=en_US.UTF-8",
         "TERM=xterm",
         "XDG_CONFIG_HOME=/config/xdg",
         "SONARR_BRANCH=main"
       ],
```

**Comment by issaccv** [comment]
I have changed download client and the problem has been solved. I don’t know if there is a problem with qbittorrent or sonarr.

**Comment by thezoggy** [comment]
pretty easy to isolate that. just try the download with just the torrent client (so not having sonarr adding the torrent to the client but you do) and see if the same issue happens. the client may just not support the utf code mapping or handle utf input via the api?

**Comment by issaccv** [comment]
I tried add torrent directly in qbittorrent, it works fine.So I guess it’s the api problem.

**Comment by markus101** [comment]
Since changing clients works it'd be helpful to report the issue to qbit, but glad to hear it's working with another client.

**Comment by Taloth** [comment]
Would be worth grabbing the exact torrent and post it to the qbit api.

**Comment by issaccv** [comment]
> Would be worth grabbing the exact torrent and post it to the qbit api.

I use python client `qbittorrent-api` from pypi. 
And I use url from jackett, it works fine.

```python
>>> import qbittorrentapi
>>> qb = qbittorrentapi.Client()
>>> qb.torrents_add(urls='http://172.17.0.1:9117/dl/tjupt/?jackett_apikey=(removed)&path=Q2ZESjhOb1RBNjZfU0hwSmxkajN4cHNLRnZxNzdQNDhzeDdQMmd1SU5odktnMldyUU9WNFFhcU1GRTZpeGlZMVduaW9fLTRuRUo1bHpXb0hfWlltNW5pTDNFNVE0cGZDeFZlT0NnakxLY1hXQ3dlcl9HeVFqSVA3bUNsVmJaX3dfNkRwT3Rzb0haMnhMa3FCR3JFalFGTl9RTnN6Wms0ckNCdlRTSml5M05CMlBVc0w&file=(filename)', category='tv-sonarr',use_auto_torrent_management=True)
'Ok.'
```

**Comment by Taloth** [comment]
> > Would be worth grabbing the exact torrent and post it to the qbit api.
> 
> I use python client `qbittorrent-api` from pypi. And I use url from jackett, it works fine.
> 

Sonarr does not send the url to qbit, it sends the actual torrent. So use the `torrent_files` parameter instead.
