### ISSUE TITLE
Sonarr not finding any episodes when a manual Jackett search finds plenty

### ISSUE THREAD

**Issue by glc650** [Sonarr/Sonarr#4632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With some shows (eg. Truth Be Told s02e01) Sonarr won't find any episodes on any indexers but if I do a manual search in Jackett I can find plenty of results.  The categories from the manual search in Jackett match the categories I've selected for the indexers in Sonarr.

### Expected Behavior

Whatever is found manually in jackett should also be found automatically by Sonarr.

### Environment

```markdown
- OS: Ubuntu 20.04.3 LTS
- Sonarr: 3.0.6.1265
- Docker Install:20.10.8, build 3967b7d
- Using Reverse Proxy: no
- Browser: macOS Safari and Firefox
```

### What branch are you running?

Main

### Anything else?

![Screen Shot 2021-08-20 at 1 30 46 PM](https://user-images.githubusercontent.com/6758825/130290469-66c9a9d9-b1a0-4f14-9399-2b80f6480d7a.png)
![Screen Shot 2021-08-20 at 1 31 49 PM](https://user-images.githubusercontent.com/6758825/130290483-4e45b4ee-b204-4a67-8271-7e5e56172658.png)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.
