### ISSUE TITLE
Allow sonarr to search for entire anime seasons as a standard tv show

### ISSUE THREAD

**Issue by yunyunls** [Sonarr/Sonarr#4633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When sonarr is searching for an anime, it will perform a search episode by episode even if the anime has finished airing, this takes a long time and many times results in sonarr not finding any results or downloading individual episodes when there are season packs available but when the anime is switched to "standard" sonarr proceeds to search for the anime entire season instead of episode by episode and will appropriately download a complete season pack.

### Describe the solution you'd like

If possible, before starting the search of an anime, sonarr should check if the season/anime has finished airing, if it has finished airing sonarr should search for a complete season pack of the anime instead of searching for individual episodes.

### Describe alternatives you've considered

I dont have any other alternatives.

### Anything else?

N/A

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

change the series type: this is covered on the FAQ and the search troubleshooting article on the wiki
