### ISSUE TITLE
Option to retain existing extra files (e.g. subtitles) in Manual Import for existing episodes

### ISSUE THREAD

**Issue by wsegatto** [Sonarr/Sonarr#4634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When I import a "Wanted" episode via Manual Import, if an episode file already exists, all files (including extra files) are deleted, which sometimes is not the wanted behavior.
For example, I may want to convert the existing files in my library to abide by certain container/audio/video standards (which could change if I wanted to at any time). In this case, I would convert and overwrite the e.g. MKV files e.g. converting EAC3 to AAC. In this case, I have to "rescue" existing subtitles (which were extensively searched and synchronized) from the trash for every episode.

### Describe the solution you'd like

Sonarr could give the possibility to retain extra files in folder when manual importing. A simple flag, leading to a single boolean, to an "IF" before the deletion of extra files.

### Describe alternatives you've considered

Other than having to dig the extra files from the Trash, I found no alternatives.

### Anything else?

No.

**Comment by markus101** [comment]
We do not have plans to leave extra files during import.

Two options:
- Also copy out the subtitles file and re-import
- Transcode in place and once https://github.com/Sonarr/Sonarr/issues/3366 is implemented Sonarr would see the media info changes
