### ISSUE TITLE
Xem season mapping incorrect

### ISSUE THREAD

**Issue by fhriley** [Sonarr/Sonarr#4636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, sonarr queries the xem `allNames` endpoint with `origin=tvdb` and [uses the returned season numbers as the scene season number](https://github.com/Sonarr/Sonarr/blob/dbd140d4ec0507221b677a00967ff96b9f5adc16/src/NzbDrone.Core/DataAugmentation/Xem/XemProxy.cs#L104). I believe this to be incorrect. It should be setting the returned season numbers as the tvdb season number. There are a couple reasons why:

First, the documentation on the `single` endpoint says this:

> the origin is the name of the site/entity the episode, season (and/or absolute) numbers are based on

It stands to reason that this would apply to the `allNames` endpoint as well, which means the returned season numbers are the tvdb season numbers.

Second, treating them as scene season numbers causes breakages. For example, [90 Day Fiance Pillow Talk](https://www.thetvdb.com/series/pillow-talk-tlc). You can see that each season is based on a season of another 90 Day show. The scene treats each season individually. So, for example, seasons 8, 9, and 10 would map to the scene like this:

```
S08E01 -> 90 Day The Single Life Pillow Talk S01E01
S09E01 -> 90 Day Fiance Happily Ever After Pillow Talk S06E01
S10E01 -> Darcey and Stacey Pillow Talk S02E01
```

With the way Sonarr is doing it, the xem `allNames` mapping would have to be this:

``` json
{ "90 Day The Single Life Pillow Talk": 1 }
{ "90 Day Fiance Happily Ever After Pillow Talk": 6 }
{ "Darcey and Stacey Pillow Talk": 2 }
```

But let's say season 11 of Pillow Talk is 90 Day The Single Life Pillow Talk Season 2. The mapping would then be this:

```
S08E01 -> 90 Day The Single Life Pillow Talk S01E01
S09E01 -> 90 Day Fiance Happily Ever After Pillow Talk S06E01
S10E01 -> Darcey and Stacey Pillow Talk S02E01
S11E01 -> 90 Day The Single Life Pillow Talk S02E01
```

And the xem `allNames` mapping would have to this:

``` json
{ "90 Day The Single Life Pillow Talk": 1 }
{ "90 Day Fiance Happily Ever After Pillow Talk": 6 }
{ "Darcey and Stacey Pillow Talk": 2 }
{ "90 Day The Single Life Pillow Talk": 2 }
```

This is obviously incorrect because Sonarr has an ambiguous mapping for seasons 10 and 11. If Sonarr were treating xem mapping seasons as tvdb seasons, the xem mapping would be this:

``` json
{ "90 Day The Single Life Pillow Talk": 8 }
{ "90 Day Fiance Happily Ever After Pillow Talk": 9 }
{ "Darcey and Stacey Pillow Talk": 10 }
{ "90 Day The Single Life Pillow Talk": 11 }
```

And everything would map properly. I think Sonarr is currently getting lucky that the current way of doing it is working due to the seasons almost always matching between tvdb and the scene.

### Expected Behavior

New seasons of Pillow Talk correctly map to the scene seasons.

### Environment

```markdown
- OS: 
- Sonarr: 3.0.6.1265
- Docker Install: Yes
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Main

### Anything else?

I have a proxy set up so I can inject what I want into the xem responses. For example, 90 Day Pillow Talk is not currently on xem so I use the proxy to correctly return the mapping. I can provide this if you want to use it.

**Comment by markus101** [comment]
> It stands to reason that this would apply to the allNames endpoint as well, which means the returned season numbers are the tvdb season numbers.

That is incorrect for at least Fairy Tail S2:
https://github.com/Sonarr/Sonarr/issues/1140
https://github.com/Sonarr/Sonarr/commit/942be364dc31028ec49d09256ef6f967441c17e9

> I have a proxy set up so I can inject what I want into the xem responses. For example, 90 Day Pillow Talk is not currently on xem so I use the proxy to correctly return the mapping. I can provide this if you want to use it.

This isn't something we're going to support and XEM itself is possibly going to have issues with such a complex mapping.

**Comment by fhriley** [comment]
> > It stands to reason that this would apply to the allNames endpoint as well, which means the returned season numbers are the tvdb season numbers.
> 
> That is incorrect for at least Fairy Tail S2:
> #1140
> [942be36](https://github.com/Sonarr/Sonarr/commit/942be364dc31028ec49d09256ef6f967441c17e9)

How do we know the XEM mapping isn't at fault on this one?

> > I have a proxy set up so I can inject what I want into the xem responses. For example, 90 Day Pillow Talk is not currently on xem so I use the proxy to correctly return the mapping. I can provide this if you want to use it.
> 
> This isn't something we're going to support and XEM itself is possibly going to have issues with such a complex mapping.

I'm not asking you to support it. XEM has no problems with this show when you treat the returned season number properly. I can prove it using this proxy.

**Comment by markus101** [comment]
Either that's covered in the previous GHI or that information has been lost (in all likelihood part of that conversation happened on IRC), I don't recall specifically what was discussed outside of that in something that was fixed 6 years ago, but that's the way it's been functioning since. In addition if the aliases were mapped to TVDB season numbers there would be multiple seasons with the same alias, which would introduce different issues. At this point even if that's wrong, it'd be impossible to fix without breaking something for someone.

XEM v2 would be able to improve this, but that's just an idea.
