### ISSUE TITLE
Add new Debian/Ubuntu Repos

### ISSUE THREAD

**Issue by darthdubu** [Sonarr/Sonarr#4641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to install on Bullseye. Need new release file for debian 11.

### Expected Behavior

To be able to install sonarr.

### Environment

```markdown
- OS: Debian 11
- Sonarr:
- Docker Install: No
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Main

### Anything else?

```
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Hit:4 http://mirror.hetzner.de/debian/packages bullseye-updates InRelease
Hit:5 http://mirror.hetzner.de/debian/packages bullseye-backports InRelease
Hit:6 http://mirror.hetzner.de/debian/security bullseye-security InRelease
Hit:7 http://deb.debian.org/debian bullseye-updates InRelease
Hit:8 https://download.docker.com/linux/debian bullseye InRelease
Ign:9 https://apt.sonarr.tv/debian bullseye InRelease
Err:10 https://apt.sonarr.tv/debian bullseye Release
  404  Not Found [IP: 37.187.255.43 443]
Hit:11 https://repo.jellyfin.org/debian bullseye InRelease
Reading package lists...
E: The repository 'https://apt.sonarr.tv/debian bullseye Release' does not have a Release file.
```

**Comment by aloysiusantioch** [comment]
I too have this exact issue.

**Comment by Taloth** [comment]
I'll check out if it works fine on bullseye and setup the repo, note you can just use buster release channel until it's been confirmed working, all package are still the same.

**Comment by alaunay** [comment]
Hello,

Still no bullseye repo :)

**Comment by markus101** [comment]
Also need to add Ubuntu 22.04 (Jammy Jellyfish)

**Comment by mohaqqani** [comment]
Facing the same issue on Ubuntu 22.04 (Jammy Release)

**Comment by bbsixzz** [comment]
Any ETA on this?

**Comment by luzpaz** [comment]
An aside, not sure why Debian/Ubuntu repos not visible at all on repology:

[![Packaging status](https://repology.org/badge/vertical-allrepos/sonarr.svg)](https://repology.org/project/sonarr/versions)

**Comment by hbednar** [comment]
@luzpaz 
It will only show the distrows that have sonarr packaged, looking in the Debian repo there is no sonarr packaged:
https://packages.debian.org/search?keywords=sonarr&searchon=names&suite=all&section=all

**Comment by gsmitheidw** [comment]
[https://apt.sonarr.tv/debian is still showing ](http://apt.sonarr.tv/debian/dists/) buster, jessie and stretch. These are all old now - with buster now "old-stable". Since Bullseye went stable. I see testing listed which I'll assume is still bullseye (Debian 12) but these need to be updated. If I was to change mine to testing and this was subsequently updated I'd potentially end up with a newer release than intended for a "stable" system.

**Comment by alaunay** [comment]
For Info:
- oldold stable: buster (Debian 10)
- old stable: bullseye (Debian 11)
- stable: bookworm (Debian 12)

**Comment by jazzi** [comment]
Yeah also look forward to the repos for Debian 12 too.

**Comment by mzeyrek** [comment]
can confirm not working with latest stable 12 - bookworm

I used both below and created a new gpg with https://itsfoss.com/apt-key-deprecated/ insructions but still cannot install

#deb [signed-by=/usr/share/keyrings/sonarr.gpg] https://apt.sonarr.tv/debian bookworm main
#deb [signed-by=/usr/share/keyrings/sonarr.gpg] https://apt.sonarr.tv/debian buster-develop main


W: The repository 'https://apt.sonarr.tv/debian bookworm Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://apt.sonarr.tv/debian/dists/bookworm/main/binary-amd64/Packages  404  Not Found [IP: 37.187.255.43 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by imthenachoman** [comment]
Did anyone ever figure this out?

**Comment by markus101** [comment]
With v4 we've dropped debian packages, no plans to reintroduce them at this time.

**Comment by imthenachoman** [comment]
@markus101 

> With v4 we've dropped debian packages, no plans to reintroduce them at this time.

Out of curiosity, why? Considering it's one of the biggest distros, with so many derivatives, why drop support for it?

**Comment by markus101** [comment]
We decided to no longer maintain the package specific to those distributions and focus on a more generic, more easily available distribution method.

This allowed us to move all builds and release hosting to GitHub and focus on releasing v4 and adding features and fixing bugs instead of dealing with packaging and distribution for Debian.

**Comment by imthenachoman** [comment]
@markus101 I think that is fair and understandable. Thanks for replying.

**Comment by cookieguru** [comment]
@markus101 is the issue with the packaging or distribution?  There are [helpers](https://github.com/marketplace/actions/build-deb-action) that can do the [packaging](https://github.com/marketplace/actions/build-debian-packages), as well as [distribution](https://github.com/marketplace/actions/github-pages-apt-repo) which can also be done from [the repo itself](https://jon.sprig.gs/blog/post/2835)

**Comment by holysoles** [comment]
For those looking for alternatives while still running debian, I'd suggest switching over to [a docker container](https://github.com/linuxserver/docker-sonarr). The cutover process was pretty painless between being able to map my media volume to the existing path, and restoring from a backup.
