### ISSUE TITLE
Don’t log number of indexers being searched

### ISSUE THREAD

**Issue by natebluehooves** [Sonarr/Sonarr#4642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I currently have a torznab and newznab indexer configured so newznab has SD and HD categories under "categories", and nothing under anime categories. The opposite (anime category is set for anime categories and nothing on standard categories) on torznab. Somehow both indexers are being used for every search no matter what type of show I'm trying to search. The bottom left pop up claims sonarr is "searching 2 indexers" for whatever if I use the automatic search function. 

### Expected Behavior

Unless I'm mistaken, this setup should exclude indexers with no categories set in the relevant field. 

### Steps To Reproduce

I'm on a VM under proxmox with an install of sonarr v3 installed over the top of v2. I can not confirm if this behavior was present in v2. 

### Environment

```markdown
- OS: Ubuntu 20.04.1 LTS
- Sonarr:3.0.6.1265
- Docker Install: no
- Using Reverse Proxy: no
- Browser: Probably not related, but Google Chrome 92.0.4515.159
```

### What branch are you running?

Main

### Anything else?

Managed to make a short enough trace for it to upload to hastebin. https://hastebin.com/amosotegob.yaml

**Comment by natebluehooves** [comment]
Apologies if I'm missing something, or if the trace logs were mandatory. This is my first github issue report, so let me know if I need to fix anything.

**Comment by bakerboy448** [comment]
Going to need trace logs showing it actually sending search queries to both for a standard series search and for an anime series search

https://wiki.servarr.com/sonarr/troubleshooting#logging-and-log-files

**Comment by natebluehooves** [comment]
I was on that page, but looking at my trace log I can't figure out what part of the log is relevant. I'll see if it fits in any of the other pastebin alternatives listed.

**Comment by bakerboy448** [comment]
A search for an episode of a series set to standard and for a series set to anime  should suffice;  shortly after "searching Xxx indexers for yyyy" should should be some REQ to the indexers

(Also I hope those are one torrent and one usenet tracker; if they are aggregate endpoints such as Jackett's /all or you have Hydra syncing as a "single" tracker, that is not advised, provides 0 benefit, and is full of draw backs; FAQ has more details)

**Comment by natebluehooves** [comment]
> A search for an episode of a series set to standard and for a series set to anime should suffice; shortly after "searching Xxx indexers for yyyy" should should be a REQ to the indexers
> 
> (Also I hope those are one torrent tracker and one usenet indeder; if they are aggregate endpoints such as Jackett's /all or you have Hydra syncing as a "single" tracker, that is not advised, provides 0 benefit, and is full of draw backs; FAQ has more details)

Okay, I've posted logs above. As a side note, it's one torrent and one NZB. I am trying to use jackett (animebytes) for anime, and dognzb for tv shows.

**Comment by bakerboy448** [comment]
Notice how `[How a Realist Hero Rebuilt the Kingdom : 09]` only sent a query to animebytes?

it's just a nuance/inaccuracy in the logging; this GHI should be renamed to `NzbSearchService indicating incorrect number of indexers searched when indexer disabled for a series type`


> 2021-08-28 19:03:02.0|Info|NzbSearchService|Searching 2 indexers for [How a Realist Hero Rebuilt the Kingdom : 09]
> 2021-08-28 19:03:06.4|Debug|NzbSearchService|Total of 18 reports were found for [How a Realist Hero Rebuilt the Kingdom : 09] from 2 indexers

**Comment by natebluehooves** [comment]
that can't be correct though. before setting priority, it downloaded a .nzb, and the traces here still show it finding nzb results. it's not just saying that it's searching two sources, it IS searching two sources.

**Comment by bakerboy448** [comment]
> traces here still show it finding nzb results

Logs do not show dog being queried at all nor any usenet results

**Comment by natebluehooves** [comment]
> Notice how `[How a Realist Hero Rebuilt the Kingdom : 09]` only sent a query to animebytes?
> 
> it's just a nuance/inaccuracy in the logging; this GHI should be renamed to `NzbSearchService indicating incorrect number of indexers searched when indexer disabled for a series type`
> 
> > 2021-08-28 19:03:02.0|Info|NzbSearchService|Searching 2 indexers for [How a Realist Hero Rebuilt the Kingdom : 09]
> > 2021-08-28 19:03:06.4|Debug|NzbSearchService|Total of 18 reports were found for [How a Realist Hero Rebuilt the Kingdom : 09] from 2 indexers

check line 1202. it's grabbing a .nzb as a possible candidate.

**Comment by natebluehooves** [comment]
To clarify, the line above 1202 is it starting to check the TV category on an anime. that may be what you're looking for more specifically.

**Comment by bakerboy448** [comment]
1201 and 1202
> 2021-08-28 19:03:13.2|Trace|HttpClient|Res: [GET] http://10.10.100.103:6969/api?mode=history&start=0&limit=60&category=tv&apikey=(removed)&output=json: 200.OK (27 ms)
> 2021-08-28 19:03:13.2|Trace|HttpClient|Response content (89523 bytes): {"history":

that is not a search nor has anything to do with a search.
that's a download client refresh that is normal activity and is totally unrelated to the search

**Comment by natebluehooves** [comment]
Would it help if I redo the priority so it downloads the .nzb result as it did previously?

**Comment by bakerboy448** [comment]
I don't follow?

There is no issue nor bug here other than some suboptimal logging.

The logs indicate sonarr is working perfectly fine and as expected.

**Comment by natebluehooves** [comment]
previously, before this log was taken, I hit automatic download and it got a dognzb result, then downloaded it. This log you have is from me doing the same again after tweaking the priority. I will redo the test and paste a new log where it's downloading from dognzb. 

why do RSS feed results ignore categories? that means I'm going to get garbage matches (bad release groups) in RSS updates to my anime.

**Comment by bakerboy448** [comment]
> previously, before this log was taken, I hit automatic download and it got a dognzb result, then downloaded it. This log you have is from me doing the same again after tweaking the priority. I will redo the test and paste a new log where it's downloading from dognzb.

that'll be interesting to see an automatic search, for an anime series type, searching an indexer that configured for anime categories in trace logs

> why do RSS feed results ignore categories?

that is a question for @Taloth or @markus101 

> that means I'm going to get garbage matches (bad release groups) in RSS updates to my anime.

only if you fail to properly configure sonarr to tune the release profiles, quality profiles, and language profiles to capture what you want.

**Comment by natebluehooves** [comment]
The issue is that my NZB sources are often not using the same naming schemes. I can set hard whitelists, but really don't want to. I often will try new release groups from animebytes, as everything there is often really high quality. 

At the very least if the RSS bit is true, that's surely not intended behavior? why have the automatic updates of new episodes ignore a part of your category rules?

Still in the middle of attempting to set up a test to check if the RSS bit is even the issue. it shouldn't be, since the nzb was obtained from a user-initiated automatic search.

**Comment by natebluehooves** [comment]
looks like it must have been an RSS thing. I can't reproduce that episode coming from automatic search, so that must have somehow been mis-remembered. 

However, I do have history showing it grabbed from .nzb at the very least from an RSS feed update. Is there a duplicate request for RSS feed updates to not ignore categories? Additionally, it'd still be very nice for it to not claim to be searching two indexers, as you've tagged this post.

**Comment by natebluehooves** [comment]
A side note: to be clear, the "searching 2 indexers" is shown to the user. it's not JUST a logging issue in that this bit of logging is shown on the frontend. it's pretty confusing. Hopefully that bit can be fixed

**Comment by natebluehooves** [comment]
> > that means I'm going to get garbage matches (bad release groups) in RSS updates to my anime.
> 
> only if you fail to properly configure sonarr to tune the release profiles, quality profiles, and language profiles to capture what you want.

Wait, this may not even work elegantly anyways. I can't set a release group whitelist without tagging every individual anime. I would have to set a whitelist globally, but I have non-anime in sonarr along with anime. a global whitelist would prevent every non-anime title (with no release group) from ever being downloaded. Am I missing some way to apply a whitelist to all anime shows and not "standard" shows?

**Comment by markus101** [comment]
Sonarr asks for specific categories, if it gets a result it doesn’t recheck that it’s in a requested category nor does it try to figure out if it’s miscategorized.

> A side note: to be clear, the "searching 2 indexers" is shown to the user. it's not JUST a logging issue in that this bit of logging is shown on the frontend. it's pretty confusing. Hopefully that bit can be fixed

The log message is what is shown in the UI, we’ve looked at changing this before, but the effort is not worth complexity; we have no plans to change it at this time.

**Comment by markus101** [comment]
Actually we can simply remove the count and avoid the issue with minimal effort.
