### ISSUE TITLE
Update Rating from TVDB to Trackt

### ISSUE THREAD

**Issue by Fringe09** [Sonarr/Sonarr#4643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Based on the discussion @ https://forums.thetvdb.com/viewtopic.php?t=65652, TVDB no longer uses ratings. Seems like they depreciated this feature.

### Describe the solution you'd like

Use ratings from Trackt

### Describe alternatives you've considered

Get rid of ratings

### Anything else?

No

**Comment by markus101** [comment]
Trakt is moving to TMDB for data, we’ll see what v4 brings, but no plans to switch to trakt for this at this time.
