### ISSUE TITLE
Allow downloading season packs to get missing episodes

### ISSUE THREAD

**Issue by bmtphoenix** [Sonarr/Sonarr#4644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Sometimes Sonarr gets stuck unable to find individual episodes, usually because whatever you're searching is old, so the single episode torrents have faded. 

### Describe the solution you'd like

A checkbox for allowing Sonarr to download season packs in order to get missing episodes

### Describe alternatives you've considered

I can do this on my own by searching for seasons packs from Sonarr, but it would be nice if it could do it automatically.

### Anything else?

I can't think of anything else to add.

**Comment by markus101** [comment]
We do not have plans to automatically grab season torrents in this case.
