### ISSUE TITLE
Improve Logging on Accepted Releases

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#4646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently the reasons why a release was accepted are partially logged via debug, but not detailed enough to determine why a preferred word upgrade was grabbed (among other things). This will allow users to (and support) to look at debug instead of trace logs for common issues.

### Describe the solution you'd like

Current:

`_logger.Debug("New item has a better preferred word score");`

Improved logging:

`_logger.Debug("New item has a better preferred word score. New: {0}. Current: {1}", newScore, currentScore);`

Taking this further we should return the reasons a release was accepted (like we do with why it was rejected) which can be logged like we do for rejections:

`_logger.Debug("Release accepted");`

becomes:

`_logger.Info("Release accepted for the following reasons: ...");`

### Describe alternatives you've considered

Default log level of trace.

### Anything else?

No.

**Comment by bakerboy448** [comment]
We should include the release name as well
