### ISSUE TITLE
Allow filtering for nyaa.si to override the default search parameters

### ISSUE THREAD

**Issue by Guyverix** [Sonarr/Sonarr#4647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently nyaa.si rss feed that is in use grabs all subtitled shows.  However using the c=1_2 value instead of c=1_0 will allow for english subtitled shows without misses due to subs in other languages, or without having to have an extensive ignore filter.

### Describe the solution you'd like

A radio button on "Indexer >> Nyaa >> Edit Indexer" that we can add our own integer into to override the default _0 value in the URL:  https://nyaa.si/?page=rss&cats=1_0&filter=1

### Describe alternatives you've considered

I have been building out ignore lists in my system, but that seems like a moving target that can change over time.  Already having this filtered on the nyaa side will make things easier long term to keep the view down to something smaller specific to my language.

### Anything else?

Suggested:
https://nyaa.si/?page=rss&c=1_2&f=0
1_2 == anime, english

Currently in use:
https://nyaa.si/?page=rss&cats=1_0&filter=1
1_0 == anime, any language

**Comment by markus101** [comment]
This is already possible (it's an advanced setting):

![image](https://user-images.githubusercontent.com/413544/131413704-c3660fd8-69b9-4978-bd23-c8ade3221ffe.png)

**Comment by Guyverix** [comment]
Gah!  And I swear I really did look!  Thank you for pointing that out to me.
