### ISSUE TITLE
Sonarr tries to bind twice on Windows with URL base

### ISSUE THREAD

**Issue by admlko** [Sonarr/Sonarr#4650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After a fresh install of Sonarr on Windows machine, it starts normally.
But if I set URL Base - for example - /sonarr, it won't start anymore.
The error message is:

```
PS C:\ProgramData\Sonarr\bin> .\Sonarr.Console.exe
[Info] Bootstrap: Starting Sonarr - C:\ProgramData\Sonarr\bin\Sonarr.Console.exe - Version 3.0.6.1265
[Info] Router: Application mode: Interactive
[Info] MigrationLogger: *** Checking database for required migrations data source=C:\ProgramData\Sonarr\sonarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationLogger: *** Checking database for required migrations data source=C:\ProgramData\Sonarr\logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController:   http://localhost:8989/sonarr/
[Info] OwinHostController:   http://localhost:8989/
[Info] SonarrBootstrapper: Starting Web Server
[Fatal] ConsoleApp: EPIC FAIL!

[v3.0.6.1265] NzbDrone.Host.Owin.PortInUseException: Unable to bind to the designated IP Address/Port (*:8989). Please ensure Sonarr is not already running, the bind address is correct (or is set to'*') and the port is not used ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied

...
```

If I remove UrlBase manually (set it to / ) from the config.xml file, it starts normally and everything works as expected.

It seems that when Base URL is set, it first starts Sonarr with it and after that tries to start again without Base URL.

### Expected Behavior

Sonarr starts with Base URL set and uses it.

### Steps To Reproduce

1. Install latest Sonarr for Windows
2. Set URL Base from Settings -> General
3. Restart Sonarr

### Environment

```markdown
- OS: Windows 10 Pro 20H2
- Sonarr: 3.0.6.1265
- Docker Install: no
- Using Reverse Proxy: no
- Browser: -
```

### What branch are you running?

Main

### Anything else?

See log about port binding.

**Comment by markus101** [comment]
Different URL bases do need to be registered separately, but make sure a bind address also hasn't been set as that can cause issues. Running Sonarr as admin at least once should also help.

If you're still having issues please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr).
