### ISSUE TITLE
Unable to change Quality

### ISSUE THREAD

**Issue by Gerben-W** [Sonarr/Sonarr#4651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After going to the Details of an episode the quality cannot be changed

### Expected Behavior

It used to be possible to click on the Quality of that episode to change it to something else.

### Steps To Reproduce

Click on a Serie
Expand a Season
Click on a title
Click on the Quality of the file.

### Environment

```markdown
- OS: Ubuntu 18.04.5 LTS
- Sonarr: 3.0.6.1265
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome 93.0.4577.63
- Browser: Firefox 91.0.2
- Browser: Safari 15.0
- Browser: Safari 14.1.2
```

### What branch are you running?

Main

### Anything else?

I'm using the linuxserver.io docker. (Package Version: 3.0.6.1265-ls119 by linuxserver.io )

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

series => manage episodes
