### ISSUE TITLE
Import Episodes in Sequential Order

### ISSUE THREAD

**Issue by ados8** [Sonarr/Sonarr#4652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have researched this and have not found a mention so I hope this has not been covered.
Currently there is no settings option to delay Sonarr importing (add to Plex) episodes that are downloaded but not in sequential order.

Example, season 1 of a series is sourced and they are in the queue but despite having them add in order some might fail and with new ones added but further down the list or fail completely. The completed ones get imported and then you might watch episodes thinking they are all there until you missed e.g. 6 and 10.

### Describe the solution you'd like

Hoping to have a settings of following:

To force importing only in sequential order, e.g. episode 7 will not import until 6 has completed and been imported and 6 will not do so until 5 has and so forth. So importing must be in 1 - X but the downloading can be in any order, its just waiting on the final import until its all there.

There can also be a user set duration before an alert is triggered via "Connect" to advise e.g. "show A is delayed while in wait for episode 6". I don't think there needs to be any time in which it then overrides and imports with missing episodes as I can't see why you would want content added and its not all available.

### Describe alternatives you've considered

Outside of not having the alert I cannot think of any alternatives 😊

### Anything else?

Just a thanks

**Comment by markus101** [comment]
We do not have plans to import in sequential order.
