### ISSUE TITLE
Allow indexer connections with host

### ISSUE THREAD

**Issue by ieaves** [Sonarr/Sonarr#4653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

URL validation rules applied to new indexers prevent host based connections (such as when adding a download client) prevent host based setups.

![Screenshot from 2021-09-08 11-41-00](https://user-images.githubusercontent.com/7785207/132550943-719dc2f8-69c3-4b78-8276-d5ae100f7dc1.png)
 

With the ubiquity of metasearch indexers like Nzbhydra2 which are often deployed parallel to sonarr it would be convenient to have the option for host based indexer lookup.

### Describe the solution you'd like

Host based connections for indexers similar to those for download clients.

### Describe alternatives you've considered

URL resolution works as well, host resolution for interprocess communication is just particularly handy in kubernetes.

### Anything else?

Something as simple as removing the `http(s)://` validation requirements would work but an alternative host based connection like that provided for downloaders would be very helpful!

![Screenshot from 2021-09-08 11-47-11](https://user-images.githubusercontent.com/7785207/132551083-3237e36e-2fff-4854-8bc7-570ceac94acc.png)

**Comment by owine** [comment]
Does this not work with `http://` in front? It works for me in a Docker Compose bridge network environment.

**Comment by markus101** [comment]
Yes, using a URI instead of just the host name is the correct solution.

**Comment by ieaves** [comment]
It does not work core coreDNS on Kubernetes AFAICT. :man_shrugging:

**Comment by markus101** [comment]
The actual requests Sonarr is making are all http requests, for download clients Sonarr asks for, host, port and whether it's using SSL or not, which get turned into the base URL: http://hostname:port, for indexers, Sonarr asks for it all in one field.

There is no difference in the request made for:

```
Host: localost:
Port: 8080
Use SSL: false
```

and

```
URL: http://localhost:8080
```

when Sonarr makes the request.

Is NZB hydra actually running on port 80 (the default for http) or do you need to specify a different port?

**Comment by ieaves** [comment]
I'm a little surprised to hear Sonarr is handling downloaders and indexers identically since sabnzbd works just fine while nzbhydra errors.

![Screenshot from 2021-09-08 16-40-01](https://user-images.githubusercontent.com/7785207/132589344-fdf5a36c-017e-4c9d-9015-9780fe7a8dbe.png)

It's not a port issue I don't think - especially since I can curl the service from inside the sonarr pod (I cut out my api key from the request below).

![Screenshot from 2021-09-08 17-01-17](https://user-images.githubusercontent.com/7785207/132591646-f0f71afd-03de-496d-b9d8-337ffc5be8e9.png)

**Comment by owine** [comment]
By default nzbhydra2 used port 5076 (not 80) so I would try `http://nzbhydra2:5076` for the indexer entry.

**Comment by ieaves** [comment]
The pod itself is listening on 5076 but unfortunately that's not the issue - I'm getting a 404 hitting 5076 directly but a 502 on 80.

```
NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://nzbhydra2-svc.media:5076/api?t=caps&apikey=(removed)
```

```
HTTP request failed: [502:BadGateway] [GET] at [http://nzbhydra2-svc.media/api?t=caps&apikey=(removed)
```
