### ISSUE TITLE
Multiple labels for convenient/automated management

### ISSUE THREAD

**Issue by sarunas-zilinskas** [Sonarr/Sonarr#4654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Feature: Assign multiple labels to individual TV shows.

Currently sonarr is only able to assign one label when passing to the download client (i.e. deluge). This is okay for distinguishing whether it was added by sonarr or something else but it makes it impossible to create more advanced automation for download client.
So it would be crucial for sonarr to support multiple labels in order to have even more advanced and automated solution.

### Describe the solution you'd like

Solution: sonarr has the ability to add multpiple labels per multiple tv shows which are monitored. I.e. show ABC has label "ABC" and show XYZ has labels "XYZ, DEF". 

This would allow for some rules to be set-up on download client i.e. 
1. Anything with label "ABC" should be moved to "FamilyTV" folder when finished.
2. Anything with label "XYZ" should be moved to "NotforkidsTV" folder when finished.
3. Anything with label "DEF" should limit bandwidth to only 5mbit/s or i.e. stop at seed ratio of 2.0.

The Result would be: 
1. ABC show episode is moved to appropriate folder for the show.
2. XYZ show episode is moved to appropriate folder for the show and set to stop at seed ratio of 2.0.

### Describe alternatives you've considered

For folder management I tried using sonarr's media management but I found it too complicated. When testing I even managed to overwrite (delete) the whole library and still it didn't work as I expected. 
Especially when deluge and sonarr are running in docker containers with different volume mount paths i.e. ~/docker/sonarr and ~/docker/deluge. 
I guess for it to work one would need to bind mount some common directory for both containers... no? I still don't understand the idea fully of how it should work...

### Anything else?

The proposed solution would be wayyy easier to setup rather than using maybe more advanced but surely much more complicated media management on sonarr. Just assign labels and create some rules on download client and all the TV shows end up in the correct folders.
I used to always move the folders manually as I found this functionality lacking on sonarr...

Also, I think this guy is referring to more or less the same issue he is facing just like me:
https://forums.sonarr.tv/t/send-download-with-a-label-when-you-send-to-a-torrent-client/25103/2

**Comment by bakerboy448** [comment]
Duplicate/Related to a few:
- https://github.com/Sonarr/Sonarr/issues/3644
- https://github.com/Sonarr/Sonarr/issues/2587
- https://github.com/Sonarr/Sonarr/issues/3451
- https://github.com/Sonarr/Sonarr/issues/4072
- https://github.com/Sonarr/Sonarr/issues/402

Closing; Dupe and based on the referenced issues, no plans for dynamic by series
