### ISSUE TITLE
Add total to season and show info bars

### ISSUE THREAD

**Issue by pbrink231** [Sonarr/Sonarr#4655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I dont monitor a lot of episodes but I would like an easy way to see shows that are missing episodes.  these are not monitored, just missing episodes.

### Describe the solution you'd like

in the season information and in the show information I would like the bar to be changed from:
` # / # `
to 
` # / # (#) `

The third # here would be the total in the season/show.
I would also like to add this same show summary bar in the header of the show

Currently you can hover over to see it on the show screen but would be great just to put it right in the summary bar.

![image](https://user-images.githubusercontent.com/8224560/132800153-77c51958-8892-4674-b5d5-3db21a83f4bc.png)
![image](https://user-images.githubusercontent.com/8224560/132800279-3dd86fef-fa99-4595-aebd-c7ab6d738cdd.png)
![image](https://user-images.githubusercontent.com/8224560/132800760-3b0e5a6b-0771-4ecb-a4e0-f8720847e132.png)

### Describe alternatives you've considered

hovering over the bars can give you the information you need but takes that extra step and having it at a glance would be really nice

### Anything else?

Pictures added for reference on a previous questions

**Comment by pbrink231** [comment]
Best option is to use the Season Pass

**Comment by pbrink231** [comment]
Having the total count on the season info bar inside of a season and on the series index page would still be really great to have.

series total includes specials but still nice to have.  would be nice to have non special episode count but that is for another issue.

**Comment by pbrink231** [comment]
Series index view does allow for adding a total episode count column but adding it this way makes it more standard on the season view so its similar accross all screens.

**Comment by markus101** [comment]
No immediate plans for this.
