### ISSUE TITLE
New Language: Malayalam

### ISSUE THREAD

**Issue by Adil-MohammedK** [Sonarr/Sonarr#4662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Add new Language Profile for Malayalam Series

### Describe the solution you'd like

Add language Malayalam option

### Describe alternatives you've considered

Make Indian suboption for Languages as India has high amount of content in different languages

### Anything else?

Nothine else

**Comment by markus101** [comment]
We need specific examples of release names using `Malayalam` as a language.

**Comment by Adil-MohammedK** [comment]
> We need specific examples of release names using `Malayalam` as a language.


Premam.2015.BRRip.720p.x264.Malayalam.ESubs-ViZNU [P2PDL]
KURUTHI (2021) 720p Malayalam HDRip - x264
Drishyam 2 (2021) Malayalam.1080p.WebRip .AVC.5.1-Rjaa
Indian Rupee (2011) Malayalam DVDRip XviD 5.1 ESub MTR
Body.Guard.2009.DVDRip.1CD.Malayalam.Xvid.MP3@Mastitorrents
KURUTHI (2021) Malayalam HDRip -​ x264 -​ AAC -​ 700MB ESubs
#Home.2021.1080p.10bit.AMZN.WEBRip.Malayalam.DDP5.1.ESub.HEVC

These are some of the torrent contents available
