### ISSUE TITLE
Season Finale Tag in Preferred Words w/in Media Management Settings

### ISSUE THREAD

**Issue by ekk88d** [Sonarr/Sonarr#4666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Series Finale Indicator within Preferred Words

### Describe the solution you'd like

As-is, finales are marked in the Calendar. That feature addition was extremely well-received.

Once finale episodes are downloaded, however, there isn't an file explorer or media player tag to identify the episode as a finale. Of course, the user can indefinitely choose to circle back to the Calendar for every curiosity. However, I think a better implementation is to carry the Calendar finale flag to a Preferred Words tag/indicator.

A simple Preferred Words indicator, like an asterisk(*) or caret(^), in the filename, would suffice.
The finale indicator's symbol could also be selectable by the user. Just like other Preferred Words, as long as the user places it after the episodes primary file naming data, the media library scrapers (Plex, Kodi, etc.) should have no issues with matching to their DBs.

### Describe alternatives you've considered

If there is a better way to flag a finale and keep it identified in a media player or library, I'm not sure of a better way than a symbol for Preferred Words. Just as the Calendar uses the (!) symbol, the Preferred Words symbol appears as the best solution. It could even be the exact same exclamation symbol.

### Anything else?

For those that want to try my manual workaround:
I have been manually renaming each continuing series' storage folder, in Sonarr, to include the show's season count and latest season's episode count (when known). Media Management's folder naming settings are left as default.

Each show's storage folder's is named as:
`[Series Name] [Latest Season Number]^[Total Episode Count] `
Example:
`Wu-Tang - An American Saga 2^10`
This show's latest season is S02 and E10 is its finale episode.

I also use Plex, which is picky with filenames. Sometimes, Plex needs help by manually matching the show, but that match sticks for future episodes. 

If Sonarr includes a season or show finale indicator, in Preferred Words, Media Managements settings can tag the _episode_ name. This feature request allows for automated finale indicating, with media library matches that are cleaner for metadata download.

**Comment by markus101** [comment]
At this time this isn't something we have plans to add. Currently the finale is applied to the last episode of a season, but some shows don't get updated episodes until the episode is about to air which could lead to many episodes being treated as the finale.

**Comment by ekk88d** [comment]
Thanks Markus. I remember that was the original issue when I suggested the Calendar's premiere+finale tag on the sonarr.tv forums.

If TV DBs contained a flag of whether/not their episode count is final, for the current season, this'd be much more reliable.

**Comment by thezoggy** [comment]
tvdb doesnt expose it, maybe in v4. its been one of the missing things that tvrage used to do that tvdb never did...

**Comment by ekk88d** [comment]
> tvdb doesnt expose it, maybe in v4. its been one of the missing things that tvrage used to do that tvdb never did...

I wasn't even aware that TVRage had that capability. Thanks for your input.
If you or anyone else recalls this thread, and TheTVDB has implemented that sort of identifier, maybe we can circle back.

Sonarr with an automated Preferred Word for episode finales would be awesome. However, that's only my suggestion for the best method of identifying finales in users' file explorer and media player. If there is a better method, I'm all for it.

**Comment by thezoggy** [comment]
just so you are aware, you are talking about two things that have no relation.

preferred words is used when the release name has x word not/in it. usually that is things like a certain release group or tag that groups use like 'uncut' or other pieces of text like 'hevc' or 'x265'.  the metadata from a scraper like tvdb has nothing to do here or is used.

**Comment by ekk88d** [comment]
> just so you are aware, you are talking about two things that have no relation.
> 
> preferred words is used when the release name has x word not/in it. usually that is things like a certain release group or tag that groups use like 'uncut' or other pieces of text like 'hevc' or 'x265'. the metadata from a scraper like tvdb has nothing to do here or is used.

Thanks. Yes, thanks for clarifying.
I was thinking of any method to generate a finale indicator, and came up with Preferred Words.
I'm sure a simple Settings toggle, to include a finale indicator in the filename, would suffice.
