### ISSUE TITLE
Hide overflow in Release Profiles 

### ISSUE THREAD

**Issue by the-lazy-fox** [Sonarr/Sonarr#4667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you create a release profile with bonus points from a regex, the overflow is now hidden.
![image](https://user-images.githubusercontent.com/35723598/135436408-c52b7ad9-e583-4d4b-8e0b-5fd946b850b6.png)

### Expected Behavior

Just have an overflow: hidden; css on the divs containing the rules display
![image](https://user-images.githubusercontent.com/35723598/135436539-2b6d52c2-ed2f-434d-b864-9b2abe04f7da.png)

### Steps To Reproduce

1. Open Settings
2. Open Profiles
3. Create a profile
4. Enter a long regex
5. Save

### Environment

```markdown
- OS: Docker
- Sonarr: 3.0.6.1335
- Docker Install: 3.0.6.1335-ls123 by linuxserver.io
- Using Reverse Proxy: No
- Browser: Firefox/Chrome
```

### What branch are you running?

Main

### Anything else?

I think it's ui-only and clear enough
Cheers

**Comment by neo-neo1** [comment]
Also experiencing this. I suggest abridging overflowing text and adding `...`

Painful to see every time `Profile` page is open. The overflowing example used is taken directly from [TRaSH-Guides.](https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx/)

![Sonarr_Overflow](https://user-images.githubusercontent.com/6996362/146636898-af63d3e3-d19d-4bb5-8cb4-a3d535bc481a.jpg)
