### ISSUE TITLE
skyhook.sonarr.tv Certificate Expired

### ISSUE THREAD

**Issue by cooper7692** [Sonarr/Sonarr#4670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

adding a new show or anything that requires a skyhook lookup fails due to a failed ssl connection due to a expired ssl cert.
probably related to certbots Authority change over.

### Expected Behavior

connection succeeds and episodes is added to sonarr

### Steps To Reproduce

type show , click add new.

### Environment

```markdown
- OS: ubuntu
- Sonarr: 3.0.6.1342
- Docker Install: yes
- Using Reverse Proxy: yes, but still doesnt work using only ip address
- Browser: chrome
```

### What branch are you running?

Main

### Anything else?

nope

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

The cert is fine.
![image](https://user-images.githubusercontent.com/55419169/135702366-3e9e10db-ee47-4f67-8525-c1c23877d730.png)
![image](https://user-images.githubusercontent.com/55419169/135702379-49699e68-812e-45b8-977b-6c2851e0efe3.png)
