### ISSUE TITLE
Discovers some plex DVR recordings as whole seasons

### ISSUE THREAD

**Issue by garbled1** [Sonarr/Sonarr#4671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have plex with a DVR, and record certain shows.  Some of these shows only record with dates, instead of the SxEx format, because the guide data is incomplete.  However, Sonarr often finds these files, and then imports them as almost the entire season, and getting it to un-register that file as the whole season is non-trivial.

![image](https://user-images.githubusercontent.com/6556271/135717197-3b7595e4-963d-4503-a7aa-6fd811639bac.png)

In the example, it thinks that episode is episodes 39-19 for some reason?

### Expected Behavior

Ideally it would understand the plex DVR date format, and then match the date of the episode vs the database, and find the right match.  In this case:

The Honeymooners (1955) - 1954-01-23 05 00 00 - Cottage for Sale.ts

Which matches episode 213 of the Specials, by name and date.

Failing that, it would at least not import it as 20 random episodes in season 1.

Failing that, maybe it would have an easy way to disassociate that file with those episodes so I can fix it?

### Steps To Reproduce

Run plex with a DVR
Record a show that has date based guide data instead of episode
Cry

### Environment

```markdown
- OS: Debian 10
- Sonarr: 3.0.6.1342
- Docker Install: No
- Using Reverse Proxy: No
- Browser: not UI
```

### What branch are you running?

Main

### Anything else?

N/A

**Comment by Taloth** [comment]
Dates before 1970 are always tricky. But biggest question: Why do you add this to Sonarr? 
Imo a low priority issue.

**Comment by garbled1** [comment]
This one is simply the easiest example, but it happens for other more modern series once in a while too.  For the more modern ones, I want to be able to track the series, in case an episode fails to record, and I need to download it.  In the case of the older series like this, once the mapping is corrected, I can use Sonarr to rename the files properly, and also use it to track when I have the entire series recorded.

The same thing happens with for example, Doctor Who, where sometimes, I am actually able to download missing episodes via Sonarr, but first I have to fix it's understanding of the existing.

**Comment by markus101** [comment]
> Failing that, maybe it would have an easy way to disassociate that file with those episodes so I can fix it?

You can do this with Manual File Import from the series page.
