### ISSUE TITLE
EpisodeFile.GetSceneOfFileName - FileName without extension?

### ISSUE THREAD

**Issue by Alanoll** [Sonarr/Sonarr#4675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Regular Expressions in PreferedWord expressions will match against the full filename including extension when a Scene Name isn't available. This means that using a $ in a regular expression is inconsistent between the two.

Scene Names don't seem to include file extensions.

### Expected Behavior

Just trying to open a discussion, and wasn't sure the "right" spot. Discord seemed more trouble-shooty/support.

### Steps To Reproduce

1. Create a Release Profile  : TestProfile
2. Add a Preferred Word expression (e.g. **/((\w{3}))$/i** )
3. Include Preferred when Renaming (so the rename format can show the match or not)

### Environment

```markdown
- OS: Windows 10
- Sonarr: develop branch
```

### What branch are you running?

Develop

### Anything else?

I'm really just seeing if this should be considered a bug, before I make a PR on it.

Some breadcrumbs of where I'm looking:
https://github.com/Sonarr/Sonarr/blob/7e175bf95ed0a7b624b04a397b953f27043211ae/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L666
https://github.com/Sonarr/Sonarr/blob/7e175bf95ed0a7b624b04a397b953f27043211ae/src/NzbDrone.Core/MediaFiles/EpisodeFile.cs#L44

It seems like this method is only used within the FileNameBuilder, so shouldn't affect PreferredWord scoring when selecting a download.

**Comment by Alanoll** [comment]
The core question I have is:
Should like in EpisodeFile be changed from:
`return System.IO.Path.GetFileName(RelativePath); `
to
`return System.IO.Path.GetFileNameWithoutExtension(RelativePath); `

**Comment by bakerboy448** [comment]
Will leave this up pending markus/taloth swinging by / discord discussions,  but discord covers these discussions as well :)

**Comment by Alanoll** [comment]
For my future reference for the Discord, is the Support channel the right one?

**Comment by markus101** [comment]
What about release names that have the extension included? (I'm looking you you anime)
I'm not opposed to changing it (and using the import (`using System.IO` instead of the full path for each call).

This is less support, more general territory.

**Comment by Alanoll** [comment]
Yeah, Anime could be tricky, though I'd be back to thinking the following:

- Is a file extension valid for a release name? I don't know of a good master "release" database to verify Anime releases (anidb comes close, but doesn't actually have file names)
- This method is highly localized to File name building and not release matching for downloading. So automated downloading itself wouldn't be effected.
- It's found in the XbmcMetadata class, but used only to scrape Video/Audio codec information (via tags in the name itself)
 
First thing that comes to mind would have been "I prefer MKV to OGM", but this method isn't used in that code path, so removing the extension doesn't seem detrimental.

**Comment by Alanoll** [comment]
re: Using the import instead of the full path for each call

The Full qualified path is used because there's a property **Path** existing on the class itself.

**Comment by markus101** [comment]
I'm just pointing out that some releases have the extension, sometimes, I'm not sure I've seen it outside of anime, but anime is a free for all.

> This method is highly localized to File name building and not release matching for downloading. So automated downloading itself wouldn't be effected.

My point is there are releases that have an extension (right or wrong) so a regex that checks for the end of the string would be affected there, including grabbing because preferred words matter for grabbing as well as renaming.

> First thing that comes to mind would have been "I prefer MKV to OGM", but this method isn't used in that code path, so removing the extension doesn't seem detrimental.

It could apply, but the release name would also have to include the extension, so I agree this "feature" isn't really valid.

> The Full qualified path is used because there's a property Path existing on the class itself.

Ahh right and `this.Path` isn't required to access that.

**Comment by Alanoll** [comment]
> My point is there are releases that have an extension (right or wrong) so a regex that checks for the end of the string would be affected there, including grabbing because preferred words matter for grabbing as well as renaming.

I see what you're saying, and didn't mean to imply preferred words aren't considered when downloading. However, this function is not called by that code path.

So I guess, there's already a potential disconnect between the two parts of the software:

- PreferredWord matching when performed via the Grab/Download process (Does not call the proposed modified function at all)
- PreferredWord matching when performed via the FileRename process

I don't know enough of the underlying architecture, but the SceneName attribute may unify the two to work the same for downloaded files, and the FileName operation (this method) in FileNaming is present for manually added files, so PreferredWord matches can still somewhat match and reuse some portions of the name.

**Comment by Alanoll** [comment]
Since it's such a small change, I submitted the PR, but won't be hurt if we end up just saying "nah, nevermind"
