### ISSUE TITLE
SSLHash Option missing in Linux

### ISSUE THREAD

**Issue by thisguyshouldworkforus** [Sonarr/Sonarr#4682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, on Linux:
- Version: 3.0.6.1342
- Mono Version: 6.12.0.107
- Mode: Console

the "SSL Hash" option is missing from the "Settings > General > Show Advanced Settings" menu.

I have worked with user "fryfrog" on Discord to help identify this as an issue.

Relevant code can be found [here](https://github.com/Sonarr/Sonarr/blob/develop/frontend/src/Settings/General/HostSettings.js#L112).

Where it appears to be limiting the "SSLHash" option to only Windows (`isWindows`)

If you install on Windows:
- Version: 3.0.6.1342
- .net Version: 4.8.0
- Mode: Tray

Then the "SSLHash" option appears as one would expect.

Attached screenshots of both Linux and Windows.

### **On Windows:**
![SonarrIssue_InWindows](https://user-images.githubusercontent.com/11758785/136076871-132ab804-ed66-4c19-99d7-5a831f1c6e88.png)

### **On Linux:**
![SonarrIssue_InLinux](https://user-images.githubusercontent.com/11758785/136076873-23ed06d4-6eb2-41e7-a0d8-17ca9078d777.png)

### Expected Behavior

The "SSL Hash" option should be independent of the running platform.

### Steps To Reproduce

In Linux, you can reproduce this by going to "Settings > General > Show Advanced Settings" menu and you will only see the option for "Enable SSL" and (if checked) SSL Port.

### Environment

```markdown
- OS: Linux 4.18.0-305.17.1.el8_4.x86_64 GNU/Linux
- Version: 3.0.6.1342
- Mono Version: 6.12.0.107
- Browser: Google Chrome Version 94.0.4606.61
```

### What branch are you running?

Main

### Anything else?

https://github.com/Sonarr/Sonarr/blob/943a3d80c4ff37cdffcd840190353d679c979493/frontend/src/Settings/General/HostSettings.js#L112

**Comment by fryfrog** [comment]
https://i.imgur.com/IHJ6vNj.png
