### ISSUE TITLE
Support remuxing files on import to rearrange audio tracks so that preferred language is track 1

### ISSUE THREAD

**Issue by mueslimak3r** [Sonarr/Sonarr#4691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

It's very common for desirable releases to have more than one audio track, and for the default (audio track 1) to be in a language other than my preferred language. for instance, my language is english, and its common it find a release that has ideal bitrates but has Hindi or Italian as the primary audio track, and english as a secondary track.

### Describe the solution you'd like

It is quite easy to remux/alter the video container to rearrange the audio tracks. It would be nice to have this be part of the 'media management' settings, similar to track renaming.

Ideally, sonarr would check if the default audio track matches the preferred language, and potentially check if it matches the original language of the release to avoid using dubs if not wanted. Then it would check if the release has an audio track that matches the preferred language, and remux the files so that this audio track is the default.

### Describe alternatives you've considered

A plugin/extension could be used too. I will look into making a docker plugin for the linuxserver images. This would present to sonarr as a 'connect' script.

### Anything else?

It would be interesting to heard community feedback about how a feature like this would work/conflict with the other features of sonarr. This feedback will be useful for making a docker plugin.

**Comment by thezoggy** [comment]
there is plenty of solutions out there to transcode media/strip subs/drop audio tracks/etc  these are usually found as post processing scripts that you fire off after the content is d/led not on sonarr side before import
