### ISSUE TITLE
Existing file score on UI + score breakdown

### ISSUE THREAD

**Issue by rg9400** [Sonarr/Sonarr#4693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Right now, there is no way to see an existing file's preferred word score on the UI. You can see scores during grab and in history, but history will only show you scores for imports that happened after a certain time. Plus, you may not have history for that episode, so then the score would not be visible. The only way to get existing scores reliably is to run debug/trace logging while doing searches to see the score compared to potential grabs. This is pretty inconvenient. The scores that are displayed are buried in the info part of history as well. All of this is to say that it is cumbersome to track the upgrade history of an episode due to scores.

Additionally, a score by itself is not always super useful. Users who use Trash's guides (https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx/) may have a huge number of messy preferred words. I myself have close to 100. The permutations and combinations of these scores is huge. Trying to deconstruct which regex matched can be time consuming (it took me roughly an hour the other day).

I assume this also increases the support work since it's hard for anyone to quickly determine which regex may be incorrectly defined and resulting in bad upgrades, or even which regex is missing, etc.

### Describe the solution you'd like

Honestly, Radarr's Custom Formats. Unlike what the devs have said in multiple prior issues, the current implementation of preferred words is *not* as good as Radarr's format. There's a detailed breakdown of why here - https://forums.sonarr.tv/t/build-out-some-custom-format-features-from-radarr-aphrodite/25875

However, it seems that the devs are not interested in using this system, which is okay. Still, there are shortcomings like this one that could ideally be patched.

The ideal fix would be showing preferred word score on the series page as an optional column, adding it as a column in history, and showing matched regex in both places, maybe as a popover, though ideally as a separate column. This of course leads into the issue of large and messy preferred words eating up space on the UI, and that could be solved by introducing labels for preferred words (which would also help in renaming, but that's a separate issue).

### Describe alternatives you've considered

Wasting a significant amount of time gathering the existing score and then deconstructing how that score was determined. Increasing support work for the team as they also try to help breakdown the upgrade decision with limited information.

### Anything else?

N/A

**Comment by ItsME6969** [comment]
+1 here

**Comment by ItsME6969** [comment]
mmh well not sure why my support comment was deleted but implementing this would go a long way in helping to understand  how the releases are scored and help with debugging. Attached screenshots showing the same release scored different and theres no easy way right now of me knowing how the same **exact** release got different scores. So I support this suggestion.
![Screenshot 2021-12-03 134100 - Copy](https://user-images.githubusercontent.com/89707006/144671592-e63e13db-11f9-4689-9e5f-bc0ddf1c15d4.jpg)

![Screenshot 2021-12-03 135156 - Copy](https://user-images.githubusercontent.com/89707006/144671599-c28e4843-e21f-4deb-8172-85657e46dcf7.jpg)

**Comment by bakerboy448** [comment]
For those interested in this feature. Simply +1 the Original Post.

comments shall be restricted to discussions on either working on or actively implementing this

**Comment by ItsME6969** [comment]
Lol u could have said that without the downvote, but ok I understand.

**Comment by markus101** [comment]
Being superseded in v4 for custom formats.
