### ISSUE TITLE
Hotlink the folder to open OS file browser in episode detail

### ISSUE THREAD

**Issue by mbelvadi2** [Sonarr/Sonarr#4696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When an episode is downloaded, there is a nice full Path to the file, but it's not clickable.
If I don't want to actually open the episode, but for instance copy the file to another device, it's just a bit of an annoyance to have to copy the path, edit out the filename, and then paste it in an open OS file browser (for Windows, File Explorer) to get to it.

### Describe the solution you'd like

Make the non-filename portion of the path clickable to automatically open a new File Explorer right to that folder. Or alternatively, add a button next to the "open series" button that does the same thing, eg "open folder".

### Describe alternatives you've considered

What I described in the problem.

### Anything else?

This isn't a huge problem, but seems like it would be a very easy thing to add to remove an inconvenience.

**Comment by Taloth** [comment]
This is not really feasible, there's no consistent method in browsers to open folders. Nor is it necessarily desirable since Sonarr quite often runs on (home) servers, and thus the path wouldn't be anything local to the browser.
