### ISSUE TITLE
Sonarr crashing multiple times a day since 3.0.6.1342 update

### ISSUE THREAD

**Issue by bitpushr** [Sonarr/Sonarr#4702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sonarr crashes with an out of memory exception. The system is not out of memory.

### Expected Behavior

Sonarr doesn't crash.

### Environment

```markdown
- OS: Windows 10
- Sonarr: 3.0.6.1342
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chromium
```

### What branch are you running?

Main

### Anything else?

https://pastebin.com/VW9z8Bt6
Additional reports here: https://www.reddit.com/r/sonarr/comments/qb17k3/sonarr_v3061342_keeps_crashing/

**Comment by Taloth** [comment]
Almost certainly not caused by the update itself. Typical 'correlation without causation' stuff, but doesn't make it any less of a problem.

What we need to find out is what Sonarr is doing in the minutes/hours before the crash. You should enable trace level logs. Check if anything stands out in those logs. Stuff like mediainfo comes to mind.

Also check how much memory Sonarr is actually using over the course of a day. I need numbers here, task manager->Details. Enable the 'Commit size' column there. And just check it periodically.
A good test here is. 1. start sonarr, note memory usage. 2. run refresh series, note memory usage. 3. run rss sync, note memory usage. This will be the baseline.

Bonus points for throwing `perfmon` at it to graph it. It's a tricky tool to configure though. So that depends on your tech experience level.

At this point you should be gathering information. It's caused by something specific on your system so it'll take some time to figure out.

Note that on Windows Sonarr runs as 32 bit process, it'll never be able to consume all your system memory (that's a good thing).

**Comment by Taloth** [comment]
Addendum: Long time in the past I had a windows user run into OOM too, at Sonarr Commit size of like 500 MB coz some antivirus app was doing weird shit in the memory manager causing massive virtual memory fragmentation. So getting the actual numbers in this case will be useful to steer us in a particular direction.

**Comment by bitpushr** [comment]
> Almost certainly not caused by the update itself. Typical 'correlation without causation' stuff, but doesn't make it any less of a problem.
> 
> What we need to find out is what Sonarr is doing in the minutes/hours before the crash. You should enable trace level logs. Check if anything stands out in those logs. Stuff like mediainfo comes to mind.
> 
> Also check how much memory Sonarr is actually using over the course of a day. I need numbers here, task manager->Details. Enable the 'Commit size' column there. And just check it periodically. A good test here is. 1. start sonarr, note memory usage. 2. run refresh series, note memory usage. 3. run rss sync, note memory usage. This will be the baseline.
> 
> Bonus points for throwing `perfmon` at it to graph it. It's a tricky tool to configure though. So that depends on your tech experience level.
> 
> At this point you should be gathering information. It's caused by something specific on your system so it'll take some time to figure out.
> 
> Note that on Windows Sonarr runs as 32 bit process, it'll never be able to consume all your system memory (that's a good thing).

Thanks for that. I've gone ahead and enabled trace-level logs so hopefully, it catches something before it happens next.
Usually (and I do monitor the machine that Sonarr runs off as it runs a lot of homelab-centric stuff for me) Sonarr sits around ~150MB RAM usage. Currently, it's sitting at 143MB and hasn't gone up since I last started it post-crash.
When freshly starting Sonarr manually, it has a commit size of 66MB. Then, after running a refresh series commit usage goes to around 104MB. Running an RSS sync pushes that to 107MB commit size. Happy to give it 24hrs or so (it usually crashes in that time) to see if it catches anything.
I've used Resource Monitor in the past but haven't used Perfmon. It's good that it can't use all the system memory haha.

**Comment by bitpushr** [comment]
> Bitdefender? Then 99% sure that's the cause.
> 
> Here's the previous thread on it. With technical analysis. https://forums.sonarr.tv/t/sonarr-crashes-on-windows-nzbdrone-exe-error-with-clrjit-dll/11346/32?u=taloth TL;DR: Sonarr crashed with only 530 MB, disabling bitdefender fixed it. PS: The analysis was done with a memory dump and WinDbg debugging tools.
> 
> And another user adding Sonarr to the bitdefender ignore list. https://forums.sonarr.tv/t/sonarr-keeps-shutting-down/17095
> 
> Sorry bud. I hate A/V with a vengeance because of crap like this. It might be a particular bitdefender setting that affects this, so you could investigate further in that direction and bug bitdefender support about it, but I never felt the desire to find out.

Hmm. Alright, appreciate the clarification. It's still yet to crash or anything, but I've manually updated BitDefender on that machine in case there's a definitions update or other patch that fixes it. That's the only thing I've done since responding to your initial reply so far.
If it crashes again (which I'm hoping it does so I can hopefully give you guys something useful) I'll get the relevant logs (it's still on trace level) and send them to you, as well as add it to BitDefenders exceptions. I still think it's odd that it started happening since the update given BitDefender hadn't updated or anything since before that, but... *shrug*
Sonarr's currently sitting at 121MB commit. If nothing else happens within the coming days I'm happy to close the issue, otherwise hopefully I get back with something useful.

**Comment by Taloth** [comment]
Sounds like a plan :smile:

**Comment by bitpushr** [comment]
Well, it finally crashed. Specifically, I got an outage notification and when I checked the machine Sonarr was still running with a commit size of about ~280MB and was still in the tray but I couldn't access the web GUI nor get anything when I right-clicked the Sonarr icon in the system tray. Seems like it might have not exactly crashed but locked up?

I closed it and re-opened it and it's all good now. Before doing that I grabbed the regular, debug & trace logs and have uploaded them all here:
https://drive.google.com/drive/folders/1Mr1AkkioeRlANT_PEwKwu5wzQ6Qj2lQu?usp=sharing

I've now whitelisted all the folders related to Sonarr, qBitTorrent and such in BitDefender as well so I'll see if that changes anything. If it keeps happening and doesn't look like (in the logs) it's related to Sonarr itself, I can remove BitDefender and see how that goes.

Let me know if you need anything else.
