### ISSUE TITLE
Failure to process imports properly when not all files are contained in the torrent.

### ISSUE THREAD

**Issue by rogerfar** [Sonarr/Sonarr#4704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This doesn't happen with all torrents, but I found a few that reproduce this issue consistently. 

I downloaded a full season torrent that is supposed to contain 10 episodes. But after downloading it only contains 9 episodes. So the queue consists of 10 pending downloads.

When the download is complete and it processes it, it can only find 9 episodes.

It processes those correctly, but the activity queue reports ALL episodes as `No files found are eligible for import in...`. It also will not do any further post processing, like removing the torrent.

### Expected Behavior

It should mark only the episodes that can't be found as an error, and still continue post processing the torrent.

### Steps To Reproduce

1. Search for a full season torrent, mark 1 file to NOT download.
2. Wait for the torrent to complete and report to Sonarr that it is done
3. Let sonarr import the files

### Environment

```markdown
- OS: Windows 10
- Sonarr: 3.0.6.1342
```

### What branch are you running?

Develop

### Anything else?

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/7384764/sonarr.txt)
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/7384765/sonarr.debug.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/7384766/sonarr.trace.txt)

**Comment by bakerboy448** [comment]
It's released based not file system based.

the release was for a season pack.
