### ISSUE TITLE
Search for different daily show formats. 

### ISSUE THREAD

**Issue by KBlixt** [Sonarr/Sonarr#4707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Hi, I'm unsure if this belongs here. if it doesn't I apologize.

basically. I'm using jackett to look for torrents for shows that my usenet downloader can't download. However, I'm having issues with Days of our Lives.  There are plenty of torrents, but sonarr can't find them. I guess it's because they use the wrong format. But I don't think that their format is unreasonable. would it be possible to add a format to the search?

The format is:  "Days of our Lives Monday October 18 2021" sometimes with apostrophes in the date. 

### Describe the solution you'd like

maybe just add additional searches against the jacket indexer.  and consider them all when determining which release to download.

### Describe alternatives you've considered

I've considered a manual approach where I manually add the torrents from the jackett interface to the torrent-downloader and then the import automatically mark them as sonarr related downloads. This also fail because sonarr don't recognize the format of the file and thus can't link the download to a series. if it could recognize the format in the downloader it would be a good middle ground. since searching and uploading to the downloader is a really quick maneuver. 

my current best working solution is to have it set to a standard show and hope the episodes gets put onto usenet since there the labeling is a lot more rigid. unfortunately they label their seasons and episode as a standard show. so I'm probably not ever going to have it find results from torrents as well as usenet since they use different naming schemes. however, usenet uploads are a bit flaky at best since the show isn't that popular. so a well working torrent solution would be preferable.

### Anything else?

not really. in the debug log when the download checker checks for download jobs it prints a weird log entry.

2021-10-21 21:15:40.9|Debug|Parser|Parsing string 'Days of our Lives Thursday, October 7, 2021.mkv'
2021-10-21 21:15:40.9|Debug|Parser|Episode Parsed. Days of our Lives Thursday, October 7, - S20E21 
2021-10-21 21:15:40.9|Debug|Parser|Language parsed: English
2021-10-21 21:15:40.9|Debug|QualityParser|Trying to parse quality for Days of our Lives Thursday, October 7, 2021.mkv
2021-10-21 21:15:40.9|Debug|Parser|Quality parsed: HDTV-720p v1
2021-10-21 21:15:40.9|Debug|Parser|Release Group parsed: 
2021-10-21 21:15:40.9|Debug|ParsingService|No matching series Days of our Lives Thursday, October 7,

as you can see the year 2021 gets picked up as s20e21. I should note that this is the case for both the show set as a daily show and a standard show.

**Comment by bakerboy448** [comment]
Closing; no plans

ref https://forums.sonarr.tv/
