### ISSUE TITLE
Wrong Show Name on telegram notification "Episode Downloaded" 

### ISSUE THREAD

**Issue by pong106** [Sonarr/Sonarr#4709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During Telegram notifications.

"Episode Grabbed": correct TV show name
"Episode Downloaded": wrong TV show name

### Expected Behavior

During Telegram notifications.

"Episode Grabbed": correct TV show name
"Episode Downloaded": correct TV show name

### Steps To Reproduce

1. Have two show with similar names
2. Download complete on one of the show
3. Telegram notifications : "Episode Grabbed" and "Episode Downloaded" will be triggered in sequence.

### Environment

```markdown
- OS: Linux theia 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64
- Sonarr: 3.0.6.1342-ls124 by linuxserver.io
- Docker Install: No
- Using Reverse Proxy: No idea (seedbox)
- Browser: Chrome
```

### What branch are you running?

Main

### Anything else?

![Screenshot 2021-10-22 at 2 02 04 PM](https://user-images.githubusercontent.com/12490740/138401148-a536fa04-55fd-490e-9bb4-b479bc7d9a36.png)

**Comment by CLHatch** [comment]
It looks like he grabbed an episode of the US version of Ghosts from 2021,
and it matched with the UK version of Ghosts from 2019. So yes, the
Telegram notifications would be correct based on that.
