### ISSUE TITLE
Add Bypass if Custom Format Above X for DelayProfiles

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Many people use release profiles to grab their preferred groups, etc.  Delay profiles allow for delaying releases to wait for the best one and can be overrode for quality only.

Some series have many releases in the highest quality, but at less than preferred word scores.  So currently users have two options: delay releases for an extended period of time and miss out on ratios and quick episode adds to their media server OR bypass if the highest quality is reached and have multiple/several upgrades occur wasting indexer grabs, download/upload usage, and storage space (first grab file would need to seed until X ratio on private trackers) as the initial highest quality was low quality based on release profiles.

### Describe the solution you'd like

Currently delay profiles only allow bypassing based on quality.  This should be enhanced to add a bypass if the preferred word score is > X.

Thoughts to consider:
- AND or OR relationship between Bypass for Quality & Bypass for Score
- Edge cases?

### Describe alternatives you've considered

Have perfectly suitable downloads sit held in delay and manually grab

### Anything else?

N/A

**Comment by fnfzlznddzn** [comment]
This would be most useful!

**Comment by bakerboy448** [comment]
For posterity - still applies for v4.  Custom Format score in lieu of preferred word score
