### ISSUE TITLE
Some anime movies no longer show up in Specials (for example Fate/Stay Night)

### ISSUE THREAD

**Issue by merc1031** [Sonarr/Sonarr#4724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not sure this is a bug or a "missing" feature
Some anime movies no longer show up in Specials (for example Fate/Stay Night)

I believe this used to work. In particular for Fate/Stay Night, the 3 Heaven's Feel movie/specials would be neatly collected in the show. This seems to no longer be the case. I am fairly sure I imported them via Sonarr, and now they do not appear in the Sonarr UI (or TVDB).

Its kind of a pain to have Sonarr manage the Show (and most of its specials), and then have to use Radarr and a bunch of manual work to manage the Movies(also Specials) related to the show.

Additionally the reply i got from TVDB was not particularly helpful

Reply from TVDB below

Any movies that are related to a series which are not already entered in as specials at this point should not be added.

Instead, they should be listed separately as movies.

See our guidelines here please.

Even if a series-related movie was released before the November 13, 2019 date, it still should not be added to a series if it does not exist now.

Thanks

### Expected Behavior

You can manage a full tv show Specials, Episodes, Seasons and Movies in sonarr under the shows tab

### Environment

```markdown
- OS:  ubuntu 20.04
- Sonarr: linuxserver/sonarr:develop-3.0.6.1357-ls213
- Docker Install: Docker version 20.10.8, build 3967b7d
- Using Reverse Proxy: docker traefik:v2.5.1
- Browser:
```

### What branch are you running?

Develop

### Anything else?

If i dont fill this in it deletes the entire rest of the form and forces me to fill it back in again. Terrible UI/UX

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

movies belong in radar

if TVDB classifies them as movies there is nothing to do

**Comment by merc1031** [comment]
Except these are not really movies. They are part of the show. 
And I imported them originally with Sonarr a while back (when they DID show up in the Specials section), so it was working and is now a regression.

Having radarr download them kinda ruins the entire flow of using radarr and sonarr and having sane paths / media directories for downstream apps to consume.

 and if TVDB's dumb choices can break things like this after the fact, it really doesn't make this stack sustainable moving forward.
