### ISSUE TITLE
Issue with : or - in search for TV files

### ISSUE THREAD

**Issue by niftienev** [Sonarr/Sonarr#4725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to download  "Taronga: Who’s Who In The Zoo" the ' is changed to .â€™

The tracker is returning  "Taronga-Who’s Who In The Zoo.

21-10-30 05:44:00.5|Info|RefreshSeriesService|Updating Taronga: Whoâ€™s Who In The Zoo
21-10-30 05:44:00.9|Info|RefreshEpisodeService|Starting episode info refresh for: [376916][Taronga: Whoâ€™s Who In The Zoo]
21-10-30 05:44:01.0|Info|RefreshEpisodeService|Finished episode refresh for series: [376916][Taronga: Whoâ€™s Who In The Zoo].
21-10-30 05:44:01.0|Info|DiskScanService|Scanning Taronga: Whoâ€™s Who In The Zoo
21-10-30 05:44:01.0|Info|DiskScanService|Completed scanning disk for Taronga: Whoâ€™s Who In The Zoo
21-10-30 05:44:01.0|Info|MetadataService|Series folder does not exist, skipping metadata creation

### Expected Behavior

Search to be corrected.

### Environment

```markdown
- OS: 
- Sonarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Main

### Anything else?

21-10-30 05:44:00.5|Info|RefreshSeriesService|Updating Taronga: Whoâ€™s Who In The Zoo
21-10-30 05:44:00.9|Info|RefreshEpisodeService|Starting episode info refresh for: [376916][Taronga: Whoâ€™s Who In The Zoo]
21-10-30 05:44:01.0|Info|RefreshEpisodeService|Finished episode refresh for series: [376916][Taronga: Whoâ€™s Who In The Zoo].
21-10-30 05:44:01.0|Info|DiskScanService|Scanning Taronga: Whoâ€™s Who In The Zoo
21-10-30 05:44:01.0|Info|DiskScanService|Completed scanning disk for Taronga: Whoâ€™s Who In The Zoo
21-10-30 05:44:01.0|Info|MetadataService|Series folder does not exist, skipping metadata creation

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

This looks like an encoding issue when logging and has nothing to do with searching.

**Comment by niftienev** [comment]
But it never adds the selected series either and cannot create the folder!

**Comment by bakerboy448** [comment]
That'd be permissions and ownership which is also a support issue and not a bug
