### ISSUE TITLE
Download client failed to add torrent

### ISSUE THREAD

**Issue by jules-datascientest** [Sonarr/Sonarr#4726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to add a tv show to be downloaded using the interactive search and it fails.

![Uploading Screenshot 2021-10-30 at 02.02.17.png…]()

### Expected Behavior

Should add the torrent without a problem

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 3.0.6.1342
- Docker Install: Yes
- Using Reverse Proxy: Traefik
- Browser: Firefox
```

### What branch are you running?

Main

### Anything else?

https://wyz.fr/6G-4R

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
