### ISSUE TITLE
Can't connect to my rTorrent instance (using SSL)

### ISSUE THREAD

**Issue by knovoselic** [Sonarr/Sonarr#4731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm unable to connect to rTorrent client using SSL from Sonarr.
I am using same settings in Radarr and Prowlarr and they can connect to my rTorrent instance without any issues.

### Expected Behavior

I expect it to connect to the rTorrent instance.

### Steps To Reproduce

Configure new Download Client - rTorrent like so:
Name: `rTorrent`
Host: `my.host.name`
Port: `443`
Use SSL: `True`
Url Path: `username`
Username: `username`
Password: `password`
The rest of the fields have default values.

Click Test. The test should succeed, but it fails. Identical config works fine with Radarr and Sonarr.

Here's attached trace log

### Environment

```markdown
- OS: Debian 10
- Sonarr: 3.0.6.1342-ls126 by linuxserver.io 
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox 93
```

### What branch are you running?

Main

### Anything else?

Here's part of the trace log when I hit test:

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/7461178/sonarr.trace.txt)

I'm pretty sure my SSL certs are fine (provided by letsencrypt.org) as this is the first time I'm having SSL related issues. Also tried a few online tester tools and they are showing everything as green. Also tried forcing just TLSv1.3 on nginx (which is in front rTorrent) and that didn't help.

Is this SSL issue or something else? How do I debug and hopefully resolve this?

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

syncing mono's certs will likely do it / don't believe this is a bug

Can reopen if needed / after troubleshooting on the support routes 

neither Radarr nor Prowlarr use Mono, hence the difference
