### ISSUE TITLE
Cannot add a custom Torrent RSS feed

### ISSUE THREAD

**Issue by junknstuff** [Sonarr/Sonarr#4732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am adding a private torrent tracker and receive the following error:

`Indexer feed is not supported: Unable to parse indexer: Rss feed must have a pubDate element with a valid publish date.`

### Expected Behavior

Expected the tracker to be added without any errors.

### Steps To Reproduce

Sonarr: Settings > Indexers > Add Indexer > Torrent RSS Feed

Full RSS Feed URL: https://my-private-tracker.com/rssdl.php:COOKIE:uid=xxxxx;pass=xxxxx

Cookie: https://my-private-tracker.com/rssdl.php:COOKIE:uid=xxxxx;pass=xxxxx

All other settings are left at their Default values. Hitting "Test" button produces the error:

`Indexer feed is not supported: Unable to parse indexer: Rss feed must have a pubDate element with a valid publish date.`

### Environment

```markdown
- OS: Unraid 6.8.3
- Sonarr: 3.0.6.1342
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 93 on MacOS 11.6
```

### What branch are you running?

Main

### Anything else?

Confirmed from the private tracker that the pubDate is present in their RSS feed:

'<pubDate>Tue, 02 Nov 2021 07:16:28 +0000</pubDate>'

And that the syntax is correct per:
'https://www.tutorialspoint.com/rss/rss2.0-tag-syntax.htm'

**Comment by bakerboy448** [comment]
Bug reports require logs as the template notes

**Comment by junknstuff** [comment]
> Bug reports require logs as the template notes

Ah my mistake, I understood it as being optional since it was under the "Anything else" section. I checked the Trace Log and it does not list anything related to RSS sync or Torrent indexer setup. Here are the sections before and after the error found in the Debug log:

https://www.toptal.com/developers/hastebin/raw/medesehoke

**Comment by bakerboy448** [comment]
Trace doesn't include the RSS feed at all I guess?

pretty sure that's going to be needed otherwise all we know is sonarr cannot parse a pub date from the feed and with nothing to go off of there's no action to take.  About as useful as going to the doctor and saying "a limb hurts" and not going for any tests or answering other questions 🤷‍♂️

**Comment by junknstuff** [comment]
I re-checked the Trace Log and searched while ignoring case sensitivity and was able to locate some related errors in the same time frame:

https://www.toptal.com/developers/hastebin/raw/kikudolebi

**Comment by markus101** [comment]
Please post a sample of the RSS feed so we can see what Sonarr is attempting to parse (with any private values replaced). The pubdate is required for each item in the feed, not the entire feed (not clear if this is the case with this feed), though the error messaging could be improved to indicate that.

**Comment by junknstuff** [comment]
Good idea, I didn't think to include a sample :)

Here it is:
https://www.toptal.com/developers/hastebin/raw/woteseyizo

**Comment by bakerboy448** [comment]
Doesn't appear each item has a pubdate - thus the RSS feed is truly invalid.

markus updated the error to clarify that in https://github.com/Sonarr/Sonarr/commit/4e28c7d190ca4845a03d0b937f2fb38aba6b2d28

[sidenote - should rename this issue to `Cannot add a custom Torrent RSS feed with missing item pubdate`]

**Comment by junknstuff** [comment]
Appreciate everyone's input and prompt response! I have notified the tracker and hope they can make the necessary changes to allow it to be added as a Torrent tracker in Sonarr.
