### ISSUE TITLE
Import File - Auto Retry or Overwrite

### ISSUE THREAD

**Issue by ColtenCaudle** [Sonarr/Sonarr#4733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Pretty often I am hit with an issue importing files where it says the destination file already exists.
![2021-11-02 (4)](https://user-images.githubusercontent.com/13925636/140000421-101c61b3-f4b9-47ce-b1a6-aa23164c57d7.png)
This is most likely due to my bad internet causing me to get disconnected from my NAS, leaving a partial file in the destination. When Sonarr reconnects to the NAS, it shows the above error and does not retry the import. To solve this, I delete the partial file and do a manual import like so:
![2021-11-02 (5)](https://user-images.githubusercontent.com/13925636/140000578-9516e4ea-41cb-4c3e-b201-e048b4cfba12.png)
While this solution works, it creates several steps for the user and requires the user to constantly check for importing issues.

### Describe the solution you'd like

The desired outcome would be to streamline this process for the user. Ideally, this could be solved by having Sonarr automatically restart failed imports or auto-overwrite files in the destination. Both of these solutions would work well as a simple toggle in the settings to fix the issue for users who are experiencing it.

### Describe alternatives you've considered

Alternatively, a simple retry button next to the manual import button could also be a quick fix, as long as it deletes the file in the destination as well or prompts the user to overwrite.

### Anything else?

Thank you all for your hard work!

**Comment by markus101** [comment]
This happens because Sonarr doesn't know that the partial file exists, tries to import it and it fails, eventually during the disk rescan every 12 hours (unless disabled).

In this case manual import serves as enough of a retry for most scenarios and we're not going to add another solution.

It'd be best to fix the underlying issue and find another way to sync the files across the unstable connection.
