### ISSUE TITLE
Series Detail Page - Add Genre data to page

### ISSUE THREAD

**Issue by scottc439** [Sonarr/Sonarr#4734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The current Series Detail page has almost all available data displayed except for GENRE. 
Adding this remaining data for a Series would help user from making additional steps to discover Genre for series.

### Describe the solution you'd like

Possible to display GENRE after the YEAR under the SERIES TITLE.

### Describe alternatives you've considered

It would be helpful to have Genre displayed and saving the effort to open a link to IMDb/TVDB/etc or have to go to the Series List page. The GENRE is not even available on the Series Edit page/function.

### Anything else?

![sonarr-request](https://user-images.githubusercontent.com/19492953/140065563-805f2d88-b675-41ee-a52d-a9f22aecd620.gif)

**Comment by markus101** [comment]
One thing to consider is how many genres should be shown.
