### ISSUE TITLE
Cannot connect to Aria2 using https (SSL)

### ISSUE THREAD

**Issue by J4gQBqqR** [Sonarr/Sonarr#4738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cannot connect to my Aria2 instance running on https

### Expected Behavior

Successfully add Aria2 client using the same configuration that I use in AriaNG

### Steps To Reproduce

1. Use LinuxServer.io Sonarr image and p3terx/aria2-pro Aria2 image.
2. Reverse proxy Aria2 to my subdomain using the swag image from LinuxServer.io, i.e. https://aria.example.com/
3. The rpc path is also reverse proxied, the root path is the current rpc path:
![image](https://user-images.githubusercontent.com/77554817/140617107-3079eb98-2f5f-494e-8cde-afaa0f3aca25.png)
4. I verified that I can connect to this https://aria.example.com/ instance using AriaNG from several different installations, e.g. Electron App, Chrome webpage, Chrome Plugin, etc.
5. Try it in Sonarr:
![image](https://user-images.githubusercontent.com/77554817/140617177-124ec966-51c9-4f64-8664-6bda0514eb6b.png)
6. Also tried to put the rpc path in Sonarr as "/", also no luck -> does not work

### Environment

```markdown
- OS: LinuxServer.io latest sonarr image
- Sonarr: v3.0.6.1342
- Docker Install: 
- Using Reverse Proxy: No for Sonarr, yes for Aria2
- Browser: Chromium Version 94.0.4606.81 (Official Build, ungoogled-chromium) (64-bit)
```

### What branch are you running?

Main

### Anything else?

```
sonarr          | [v3.0.6.1342] NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to aria2, please check your settings ---> CookComputing.XmlRpc.XmlRpcServerException: Internal Server Error
sonarr          |   at CookComputing.XmlRpc.XmlRpcClientProtocol.ReadResponse (CookComputing.XmlRpc.XmlRpcRequest req, System.Net.WebResponse webResp, System.IO.Stream respStm) [0x00038] in <a205b9da6b014c438c362c4bd859d7bc>:0
sonarr          |   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke (System.Object clientObj, System.Reflection.MethodInfo mi, System.Object[] parameters) [0x001a1] in <a205b9da6b014c438c362c4bd859d7bc>:0
sonarr          |   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke (System.Reflection.MethodInfo mi, System.Object[] Parameters) [0x00000] in <a205b9da6b014c438c362c4bd859d7bc>:0
sonarr          |   at XmlRpcProxy6c76fca1-91aa-440f-a014-10aa86328604.GetVersion (System.String token) [0x0001e] in <34d38c3a88a44cceb89b1d829cad6c91>:0
sonarr          |   at NzbDrone.Core.Download.Clients.Aria2.Aria2Proxy+<>c__DisplayClass4_0.<GetVersion>b__0 () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Aria2\Aria2Proxy.cs:79
sonarr          |   at NzbDrone.Core.Download.Clients.Aria2.Aria2Proxy.ExecuteRequest[T] (System.Func`1[TResult] task) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Aria2\Aria2Proxy.cs:209
sonarr          |    --- End of inner exception stack trace ---
sonarr          |   at NzbDrone.Core.Download.Clients.Aria2.Aria2Proxy.ExecuteRequest[T] (System.Func`1[TResult] task) [0x0000a] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Aria2\Aria2Proxy.cs:213
sonarr          |   at NzbDrone.Core.Download.Clients.Aria2.Aria2Proxy.GetVersion (NzbDrone.Core.Download.Clients.Aria2.Aria2Settings settings) [0x00036] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Aria2\Aria2Proxy.cs:79
sonarr          |   at NzbDrone.Core.Download.Clients.Aria2.Aria2.TestConnection () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Aria2\Aria2.cs:237
sonarr          |
sonarr          | [Warn] SonarrErrorPipeline: Invalid request Validation failed:
sonarr          |  -- Host: Unable to connect to Aria2
```

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

Likely missing the https://

of course if everything is on the same machine there is no point nor benefit of going through your RP and adding another point of failure

Also just the error spew is never helpful nor valid for  a bug report

**Comment by J4gQBqqR** [comment]
I figured out the problem, with some luck reading this [post](https://www.reddit.com/r/sonarr/comments/qg6eo1/comment/hi470qj/?utm_source=share&utm_medium=web2x&context=3).

**_Sonarr is using xml rpc instead of json rpc._** 
So user should connect to the end point of [xml rpc instead of json rpc](https://aria2.github.io/manual/en/html/aria2c.html#aria2.addUri) to talk to Aria2.

This is implicit and not well documented. Hope Sonarr team can document this properly.
Thanks for @bakerboy448 your reminder though. I am just leaving a message here for anyone having the same problem as me in the future to save them some hours in the configurations trail and error.

> Likely missing the https://

Also, "https://" in the "Host" field is not needed. If you put "https://" in the field, sonarr will complain and make you delete it.

> of course if everything is on the same machine there is no point nor benefit of going through your RP and adding another point of failure

I am not setting it in this way because I need all my download software to be under VPN. In Sonarr, the "Remote Path Mappings" is per Host. Since everything is under VPN, I simply cannot map like this:

- Host: vpn:9091 Remote path: /transmission/download
- Host: vpn:6800 Remote path: /aria2/download
- Host: vpn:6789 Remote path: /nzbget/download

This is not supported with Sonarr, since Sonarr think, "You are mapping a single host with three different remote path, I am confused.". I have to reverse proxy them to different hostnames.

**Comment by bakerboy448** [comment]
In docker - there is no reason to need a remote path map if everything is in docker.  Use of a remote path map for two docker containers on the same host is indicative of poor paths that use double space for seeds among other issues. See the docker guide on the servarr wiki for more info

**Comment by J4gQBqqR** [comment]
Thanks for your comment @bakerboy448 
Exactly, I followed the servarr documentation to set up my path, folder permission, and copy by hard linking.

The documentation is an awesome one.

There is one thing not covered by the documentation, each download client has their own path in side of their container.

For example,
Transmission: /download/completed
NZBGET: /data/download/completed
Aria2: download

Still, you need to do one of the following two things:
1. Modify each one of the download client's config file and match your setup in your Servarr app
2. Keep using the config file from the container, reverse proxy the download client and use remote path mapping in Servarr app.

Using the second method will enable the consumer to use VPN and access download client from outside of home network simultaneously.

**Comment by bakerboy448** [comment]
> Modify each one of the download client's config file and match your setup in your Servarr app

This is what you're supposed to do and what the [docker guide](https://wiki.servarr.com/docker-guide) says to do.  [Trash's guide](https://trash-guides.info/Misc/how-to-set-up-hardlinks-and-atomic-moves/) as well.  Generally speaking - docker container predefined paths should be ignored as they are always a done poorly.  Every container (automation wise) should just have a /config mount and a /data esque mount.

**Comment by J4gQBqqR** [comment]
Thanks for your time and explaination!
I think it make sense, I will follow your advice and reconfigure when I got the time.
