### ISSUE TITLE
Constant Crashing

### ISSUE THREAD

**Issue by ss44** [Sonarr/Sonarr#4745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After some time Sonarr crashes unexpectidly. 

### Expected Behavior

Not to crash.

### Steps To Reproduce

Just run and wait.

### Environment

```markdown
- OS: Ubuntu 
- Sonarr:3.0.6.1342
- Docker Install:
- Using Reverse Proxy: Yes
- Browser: Chrome

- Sonarr installed via apt repository. 

Mono Version: Mono JIT compiler version 5.20.1.34 (tarball Tue Jul 16 22:52:32 UTC 2019)
```

### What branch are you running?

Main

### Anything else?

Crash log from /var/log/syslog aound crash.

https://pastebin.com/P6BvB6t4

**Comment by bakerboy448** [comment]
My guess is mediainfo crashing on a file

Also info logs from syslog are not valid for bug reports typically
![image](https://user-images.githubusercontent.com/55419169/141347741-2e90538b-d345-47be-9ad4-7fb0e19d0c84.png)

**Comment by ss44** [comment]
thanks for the response. I checked the sonarr logs around the crashes but no errors seem to be present there. I'll try a release upgrade since I just read something about mono and certain linux kernal versions not playing nice. 

appreciate your time.
