### ISSUE TITLE
Importing cannot match with {tvdb-XXXX} in the series folder name (Plex naming guideline) 

### ISSUE THREAD

**Issue by PeterCDMcLean** [Sonarr/Sonarr#4748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I started to import my library which has been strictly named against Plex naming guidelines:
https://support.plex.tv/articles/naming-and-organizing-your-tv-show-files/

Specifically, I added the following:

> If you are using the “Plex TV Series” agent, you can optionally include the TMDB or TVDB show ID in the folder name to improve matching. If you choose to do that, it must be inside curly braces: ShowName (2020) {tvdb-123456} or ShowName (2020) {tmdb-123456} where 123456 is the show ID. An example can be found at the end of the article. 

To many of my series names. However, Sonarr fails to import every series named this way:

> Barry (2018) {tvdb-333072}
matches to
> Breakers (2018)

I already have my Sonarr naming scheme for renaming set to the same pattern. This means that even if I did import everything manually by fixing the matching, if I ever had to re-import the series I'd have to do the whole process again.

### Expected Behavior

Sonarr should try to recognize and strip out either everything within curling braces {} or patterns matching 'tvdb-XXXX'.

### Steps To Reproduce

Import series with {tvdb-XXXX} in the series folder name

### Environment

```markdown
- OS: Debian (RP4)
- Sonarr: 3.0.6.1342-ls128 by linuxserver.io
- Docker Install: Docker version 20.10.8, build 3967b7d
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Main

### Anything else?

NA

**Comment by bakerboy448** [comment]
Related Radarr Pulls
https://github.com/Radarr/Radarr/commit/6d0019ad00e348a3feb365ae5455c3968e13e2a1
https://github.com/Radarr/Radarr/commit/012fe53acc0426613d2e47fd696dddb1df8ba85e

**Comment by markus101** [comment]
Handling this on the skyhook side along with https://github.com/Sonarr/Sonarr/issues/1829

**Comment by markus101** [comment]
https://skyhook.sonarr.tv/v1/tvdb/search/en?term=Barry%20(2018)%20{tvdb-333072} now puts Barry at the top.
