### ISSUE TITLE
[Win10] constant crashing, may be due to locked DB

### ISSUE THREAD

**Issue by professionaltart** [Sonarr/Sonarr#4750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to have Sonarr go searching for new files on a series, I often have it become unresponsive.  This may be when mass searching for every episode in a season, or searching for specific episodes to filter for specific releases depending on what's available.  Refreshing the browser tab shows that Sonarr is offline - I get the default proxy placeholder page. 

When the service is restarted, it will resume again until *something* trips it again.  

In the past I've had this happen when hammering it with new data to fetch and filter, and also when I've barely touched it.

This behaviour has been ongoing for at least a few weeks, potentially longer than a month.

Debug logs were not super useful, so an hour ago I enabled trace logging, and noticed that, as per attached, a few instances of the database being locked and/or access denied.  Unsure if this is from being hammered, or an actual permissions issue.

### Expected Behavior

Service stays running and is reachable.

### Steps To Reproduce

On the Stargate SG-1 page, with a quality profile only accepting 720p content, and a tag filtering to only allow files with keyword 265, with the show and all seasons monitored, I click on the magnifying glass next to a couple of seasons and can see in log files that it's obtaining a feed from NZBHydra and parsing it.  Page stops responding, refresh shows proxy placeholder, manually restarting the service (to avoid waiting for timeout to restart) brings it back online.

Alternately, I just had it on that same page, pressed no buttons while typing this, went back to push something - hit refresh first - and it was down.

Pages/tabs left open in the background that were recently interacted with to be caught up in the crash, show this as a placeholder:

- Failed to load series from API
- Version 3.0.6.1342 

Refreshing the page will either show Sonarr as normal (if service has restarted), or proxy placeholder.

Queue is currently downloading, so there is some processing happening in the background as Sonarr checks things.

### Environment

```markdown
- OS: Windows 10, 21H1
- Sonarr: 3.0.6.1342
- Using Reverse Proxy: nginx
- Browser: Firefox 94.0.1
```

### What branch are you running?

Main

### Anything else?

https://pastebin.com/xvzTXVwb

**Comment by bakerboy448** [comment]
- logs show no DB locks
- Browser network tab in dev tools will show you why the page is failing
- This is likely your reverse proxy timing out

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

**Comment by professionaltart** [comment]
Thanks @bakerboy448: just so I understand you clearly, the 18 instances of SQLite error 5 - database is locked, and the single instance of SQLite error 2570 - access (to db) is denied, are expected behaviour?

**Comment by bakerboy448** [comment]
(sorry didnt see those when i skimmed on my phone)
Database locks are not a bug and fairly common.

Given yours are fairly frequent and back to back they may be causing an issue.  However, database locks are not a Sonarr issue and are due to insufficient disk access resources on your system.
