### ISSUE TITLE
Build x64 installers

### ISSUE THREAD

**Issue by Drapersniper** [Sonarr/Sonarr#4753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Partially, but I do understand I'm potentially a bit of an edge case.

I have a relatively large library, and I found my instance of Sonarr crashing every so often and when looking at the logs I was seeing `OutOfMemoryException`, this would be 100% reproducible in a few cases (This is not because the system run out of RAM, I have 64GB and when the crashes happened usage was around 30GB), 

All series refresh (Update all button), Search missing, Search cut off unmet are the 3 cases I could 100% repro on but every so often it would happen "randomly".

As a workaround I build an x64 installer and all the  `OutOfMemoryException` crashes have stopped (and obviously Sonarr is now using more memory than before) when doing any of the 3 tasks above example: 
![image](https://user-images.githubusercontent.com/27962761/142641271-def868cb-bc63-4187-80a9-9cea0a5e6b98.png)

### Describe the solution you'd like

In an ideal world having a Sonarr supported x64 installer would be perfect, my version is very hacky as I don't have any background knowledge of any potential issues I may not be taking into consideration.

### Describe alternatives you've considered

The alternative, in this case, would be to not use the 3 features above and hope Sonarr doesn't run out of memory.

IMHO feels like it's not the ideal option as not being able to use specific parts of the software because it may crash due to the x86 limitations.

### Anything else?

I no longer have the logs., that being said I'm more than happy to spawn the x86 version and reproduce the crash if you think it would be useful.

**Comment by Taloth** [comment]
Let's first start with some metrics: how many series, how many episodes and how many episodes do you search at once?
For example, 'All series refresh' should not cause that amount of memory usage, in any situation.

**Comment by Drapersniper** [comment]
On the TV show instance: ~9k shows, ~350k episodes.

on the anime instance ~3k anime and ~110k episodes.

to be fair the refresh all crash happened on the tv show instance and not on the anime instance.

**Comment by markus101** [comment]
x64 installers are part of the v4 beta.
