### ISSUE TITLE
Allow "Move" Operation to be Disabled

### ISSUE THREAD

**Issue by dark-swordsman** [Sonarr/Sonarr#4754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When adding files manually under "wanted" (since many file names can't be understood by sonarr for anime), on a new install or sometimes randomly, the method may change to "Move" instead of "Hardlink/Copy".

When you're bulk importing dozens of series, it's very easy to accidentally miss the dropdown for choosing "Move" or "Hardlink/Copy", so you may accidentally do a Move operation when you intended to Hardlink.

### Describe the solution you'd like

The ability to just disable "Move" operations overall in the settings would be great. I personally have the storage and capacity to seed all my files, so I'd like to be able to hardlink everything without worrying about it being completely screwed up. 

### Describe alternatives you've considered

I did consider if there was a modal that popped up, warning the user that they are about to do a move operation (since there is no way to easily revert the changes). To add, if users don't want the warning, there could also be a setting to turn the modal off. 

Though I think the ability to just block any move operation with an "opt out" would be better, especially since you may get into a habit of clicking buttons without reading much while bulk importing.

### Anything else?

I think the request is pretty self-explanatory.

**Comment by markus101** [comment]
No plans to disable move completely.

**Comment by dark-swordsman** [comment]
Okay, so then what at least about the alternative suggestion of having a warning prompt for a move operation?

**Comment by markus101** [comment]
It can't be reversed automatically, but it can be reversed. If you cut and paste a file in your OS it doesn't prompt you to be sure and I don't think it makes sense to force everyone that wants to legitimately move files to accept a warning or an option to turn it off because people will just do that and we've done the work for no reason.

> sometimes randomly, the method may change to "Move" instead of "Hardlink/Copy".

This will happen if you clear local storage as the value (like all UI values that are stored) is stored in local storage.

We're discussing whether changing the default from move to copy/hardlink makes sense.

**Comment by dark-swordsman** [comment]
I understand. Though, the issue is that when you have "rename" selected, it doesn't just cut and paste. It moves with a file name change.

Unless is it possible to have hardlinks with the new, proper name without having "rename" selected?

**Comment by bakerboy448** [comment]
> Unless is it possible to have hardlinks with the new, proper name without having "rename" selected?

no it is not possible to rename something without renaming enabled.

**Comment by dark-swordsman** [comment]
> no it is not possible to rename something without renaming enabled.

I see. So in that case, then some sort of adjustment is needed. I do like the idea of making copy/hardlink default, so looking forward to any changes in that direction.
