### ISSUE TITLE
Anime Episode Format - Absolute Episode Number

### ISSUE THREAD

**Issue by martabal** [Sonarr/Sonarr#4755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

With the latest episode of One Piece (the 1000th), the Anime Episode Format using this format : {Series Title} S{season:00} {absolute:000} has issues. Sonarr can not detect the 1000th episode on disk because of {absolute:000}

### Describe the solution you'd like

It would be great to give the possibility to have a new Absolute Episode Number : {absolute:0000}

### Describe alternatives you've considered

I haven't found solutions to this problem

### Anything else?

2021-11-21 12:24:39.6|Info|DiskScanService|Scanning One Piece
2021-11-21 12:24:44.0|Info|DiskScanService|Completed scanning disk for One Piece
2021-11-21 12:24:44.3|Info|ExistingMetadataImporter|Found 0 existing metadata files
2021-11-21 12:24:44.3|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
2021-11-21 12:24:44.3|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
2021-11-21 12:24:44.3|Info|ExistingExtraFileService|Found 0 extra files

**Comment by markus101** [comment]
Please use the correct template and provide the correct logs (debug at a minimum, trace preferred).

**Comment by markus101** [comment]
> It would be great to give the possibility to have a new Absolute Episode Number : {absolute:0000}

The format doesn’t affect parsing, the only thing it affects is renaming absolute episode numbers under 1000, with :000 it will add a zero before 99 making it 099.

**Comment by martabal** [comment]
Here is my trace for the scan of the episode:


[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/7576696/sonarr.trace.txt)

**Comment by bakerboy448** [comment]
Seems it's the Season that's throwing it off now

https://github.com/Sonarr/Sonarr/commit/aa19ddfbfd9eaef55e3eb9ac0b11a64e0eedeef4 Had otherwise fixed the parsing initially

**Comment by markus101** [comment]
This is an incredibly horrible format for parsing and while we can fix the issue, it's prone to failure because of how closely it resembles a standard format yet isn't.
