### ISSUE TITLE
Non-standard resolutions parsing

### ISSUE THREAD

**Issue by ItsME6969** [Sonarr/Sonarr#4757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sonarr parses 960p as 480p

### Expected Behavior

Parse it at the very least as 720p

### Steps To Reproduce

Find 960p content

### Environment

```markdown
OS: Ubuntu 20.04
Sonarr: Sonarr 3.0.6.1386
Docker Install: Yes
```

### What branch are you running?

Develop

### Trace Logs?

.

### Anything else?

Happens as well on 1440p content gets bumped to 1080. I'm not sure if there is enough content to warrant two new profiles for those resolutions, but I've come across quite a number now.

Short-term resolve would be to parse the 960p as 720p, not 480p as is currently.

![Screenshot 2021-11-23 154042 - Copy](https://user-images.githubusercontent.com/89707006/143141618-551a0c98-4631-43e7-a526-930096d93bb8.jpg)

**Comment by bakerboy448** [comment]
https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/MediaFiles/EpisodeImport/Aggregation/Aggregators/Augmenters/Quality/AugmentQualityFromMediaInfo.cs#L30-L54

MediaInfo would treat this as 720p

I dont think adding a new quality is in the cards, but treating as 720p in the parser would be easy enough if that's something markus and taloth want to do

https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/Parser/QualityParser.cs#L49

**Comment by markus101** [comment]
1440p = 1080p to Sonarr, that's expected. 960p hasn't come up before, so it falls into the lowest resolution bracket.
