### ISSUE TITLE
Imports stuck on `Downloaded - Importing`

### ISSUE THREAD

**Issue by IAmAProgrammerAmA** [Sonarr/Sonarr#4758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, I have many series that refuse to import. They currently look like this:
<img width="1301" alt="Screen Shot 2021-11-23 at 8 28 46 PM" src="https://user-images.githubusercontent.com/94947906/143175134-148686b1-3979-4e04-afac-06c0e7a6d35d.png">

These series survive import, refreshing the torrent client, and removing/adding the series. It's happened to a lot of series, but not all of the series, and it seems to happen somewhat randomly.

I'm willing to help debug this as much as possible.

### Expected Behavior

The series to import.

### Steps To Reproduce

I've not figured out how to get into state, but I've also not been able to get out of state, so I'm able to verify any fixes here.

### Environment

```markdown
- OS: Unraid OS 6.9.2
- Sonarr: 3.0.6.1342
- Docker Install: Yes
- Using Reverse Proxy: Yes
```

### What branch are you running?

Main

### Trace Logs?

I'm not super comfortable uploading the entire thing, but after doing some debugging, I've run across this exception for every stuck series, which seems to be causing it. I'm not sure exactly what is null on that line, but I'm also not super familiar with C#. Other than this, there's nothing related to this issue in the logs, as far as I can tell. It's just this error repeated for every series.

```
2021-11-23 19:59:34.3|Debug|DownloadProcessingService|Failed to process download: Specials

[v3.0.6.1342] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Download.CompletedDownloadService.Import (NzbDrone.Core.Download.TrackedDownloads.TrackedDownload trackedDownload) [0x0002c] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\CompletedDownloadService.cs:116 
  at NzbDrone.Core.Download.DownloadProcessingService.Execute (NzbDrone.Core.Download.ProcessMonitoredDownloadsCommand message) [0x00075] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\DownloadProcessingService.cs:65 
```

### Anything else?

I'm honestly not sure what branch I'm running. I'd assume main, but it's whatever [linuxserver.io](https://docs.linuxserver.io/images/docker-sonarr) uses.

The exception listed above seems to line up with the behavior described, but I'm not sure what would be causing an error there, it seems like a relatively innocuous line. Happy to do whatever debugging steps needed.

**Comment by bakerboy448** [comment]
> I'm not super comfortable uploading the entire thing, but after doing some debugging, I've run across this exception for every stuck series, which seems to be causing it. I'm not sure exactly what is null on that line, but I'm also not super familiar with C#. Other than this, there's nothing related to this issue in the logs, as far as I can tell. It's just this error repeated for every series.

logs are cleansed and certainly more than just the error is required for bug reports.  Just the error that it's having issues with something relating to Specials is like going to the doctor saying a limb hurts and not providing any more information or allowing the doc to check your limbs.

**Comment by IAmAProgrammerAmA** [comment]
My apologies. I had assumed a Stack Trace and exact Error was enough. I've uploaded the relevant section of the log files here. Let me know if this is still not enough.

https://gist.github.com/IAmAProgrammerAmA/57607bdcca4d14d3a1bec942c30aa7ab
