### ISSUE TITLE
Extend API for api/command/{id} to return actual result of job

### ISSUE THREAD

**Issue by Rouzax** [Sonarr/Sonarr#4759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I'm leveraging the API to import downloaded movies in Radarr but the API will always report back `completed` even when the underlying import job failed.
Have created a Feature Request for this at Radarr https://github.com/Radarr/Radarr/issues/5539 but they say it's so fundamental that it would need to come from Sonarr.

### Describe the solution you'd like

Do an import by calling the command uri with  "name": "DownloadedMoviesScan"  https://github.com/Radarr/Radarr/wiki/API:Command

All of this works fine and I get the ID back of the job. 

However, when I query that job ID I can get that the job was completed but it is not giving me the result of the import.
So POST would give me this:
```
{
    "name": "DownloadedMoviesScan",
    "body": {
        "sendUpdatesToClient": false,
        "sendUpdates": false,
        "path": "C:\\TEMP\\Torrent\\PROCD\\Radarr\\Gremlins.2.The.New.Batch.1990.1080p.BluRay.REMUX.AVC.DTS-HD MA 5.1-OMEGA",
        "importMode": "move",
        "updateScheduledTask": true,
        "completionMessage": "Completed",
        "requiresDiskAccess": false,
        "isExclusive": false,
        "isTypeExclusive": false,
        "name": "DownloadedMoviesScan",
        "trigger": "manual",
        "suppressMessages": false
    },
    "priority": "normal",
    "status": "queued",
    "queued": "2020-12-07T14:07:18.5350177Z",
    "trigger": "manual",
    "state": "queued",
    "manual": true,
    "startedOn": "2020-12-07T14:07:18.5350177Z",
    "sendUpdatesToClient": false,
    "updateScheduledTask": true,
    "id": 2317844
}
```
The job contains no actual result
```
{
    "name": "DownloadedMoviesScan",
    "message": "Completed",
    "body": {
        "sendUpdatesToClient": false,
        "sendUpdates": false,
        "path": "C:\\TEMP\\Torrent\\PROCD\\Radarr\\Gremlins.2.The.New.Batch.1990.1080p.BluRay.REMUX.AVC.DTS-HD MA 5.1-OMEGA",
        "importMode": "move",
        "updateScheduledTask": true,
        "completionMessage": "Completed",
        "requiresDiskAccess": false,
        "isExclusive": false,
        "isTypeExclusive": false,
        "name": "DownloadedMoviesScan",
        "trigger": "manual",
        "suppressMessages": false
    },
    "priority": "normal",
    "status": "completed",
    "queued": "2020-12-07T14:07:18.5350177Z",
    "started": "2020-12-07T14:07:18.5401521Z",
    "ended": "2020-12-07T14:07:18.6457371Z",
    "duration": "00:00:00.1055850",
    "trigger": "manual",
    "state": "completed",
    "manual": true,
    "startedOn": "2020-12-07T14:07:18.5350177Z",
    "stateChangeTime": "2020-12-07T14:07:18.5401521Z",
    "sendUpdatesToClient": false,
    "updateScheduledTask": true,
    "id": 2317844
}
```

While the log will say:
```
2020-12-7 15:07:18.6|Debug|DownloadedMovieImportService|Unknown Movie Gremlins.2.The.New.Batch.1990.1080p.BluRay.REMUX.AVC.DTS-HD MA 5.1-OMEGA
2020-12-7 15:07:18.6|Debug|DownloadedMovieCommandService|Failed to import
```

I would like the Job to have an actual return value with the job status.

### Describe alternatives you've considered

The current workaround is to keep a timer on how long the API job runs, if less then a second it will have failed in the backend

### Anything else?

None

**Comment by ZackaryH8** [comment]
Sonarr API link:
https://github.com/Sonarr/Sonarr/wiki/Command#downloadedepisodesscan

**Comment by Rouzax** [comment]
I know the API command but the returned job doesn't give a return value describing the result of the import.

**Comment by ZackaryH8** [comment]
> I know the API command but the returned job doesn't give a return value describing the result of the import.

I was adding it here as you provided information for Radarr, not Sonarr

**Comment by Rouzax** [comment]
Sorry, misunderstood your link

**Comment by Rouzax** [comment]
Thank you for this!
