### ISSUE TITLE
SignalR keypair issue: XDG_CONFIG_HOME environment variable ignored/overridden

### ISSUE THREAD

**Issue by klaegera** [Sonarr/Sonarr#4760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Context**

I am running Sonarr in Docker on Windows. This means Sonarr's config directory is mounted into the container, giving it (unmodifiable) `777` permissions. Sonarr attempts to generate a SignalR keypair into `<configdir>/.config/.mono/keypairs/` but fails, since the access to this directory is too permissive.

**Solution Attempt**

Users facing similar issues (although usually due to lack of write permissions, e.g. [here](https://forums.sonarr.tv/t/gui-update-issues/4195/20)) solve their issue by changing the value of the `XDG_CONFIG_HOME` environment variable, such that the keypairs are created in a different location with appropriate permissions.

This no longer seems to work - the `.config` directory is created in Sonarr's config directory regardless of the value of `XDG_CONFIG_HOME`, as briefly discussed [here](https://forums.sonarr.tv/t/docker-v3-signalr-issues-with-windows-share-volumes/22403).

**Research**

I am not familiar with Sonarr's code, but it seems [this](https://github.com/Sonarr/Sonarr/commit/5062d740411e898b3caa1a9124a14c125589c324#diff-290db56e7003f8c117ea65210070226dfc0c1ab28ca7b52ffc2f697564153a2dR140) commit from around the time of the discussion mentioned above changed how the SignalR keypair was handled, moving it from memory to a config directory.

The code seems to simply overwrite the current value of the `XDG_CONFIG_HOME` environment variable, thus overriding any externally set value.

### Expected Behavior

Sonarr should respect an externally set value of the `XDG_CONFIG_HOME` environment variable.

Perhaps the issue of the `keypairs` directory could be resolved in a way that avoids the issue of delicate access permissions altogether. It seems the keypair was moved from in-memory to file in the [commit mentioned above](https://github.com/Sonarr/Sonarr/commit/5062d740411e898b3caa1a9124a14c125589c324).

### Steps To Reproduce

1. Launch Sonarr with the `XDG_CONFIG_HOME` environment variable set to some path.
2. Connect to the web UI - Sonarr will create a `.config/.mono/keypairs` directory.
3. The directory is not created in the path given by `XDG_CONFIG_HOME`.

### Environment

```markdown
- OS: Windows
- Sonarr: 3.0.6.1342
- Mono: 5.20.1.34
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: -
```

### What branch are you running?

Main

### Trace Logs?

n/a

### Anything else?

I came upon this issue because Bazarr was causing constant high CPU usage, seemingly because it was trying to connect to Sonarr in a loop.

Bazarr's log message:
> BAZARR cannot parse JSON returned by SignalR feed. This is caused by a permissions issue when Sonarr try to access its /config/.config directory. You should fix permissions on that directory and restart Sonarr. Also, if you're a Docker image user, you should make sure you properly defined PUID/PGID environment variables. Otherwise, please contact Sonarr support.

**Comment by Taloth** [comment]
Whilst we do not support Sonarr in a docker container on windows (You should run it on windows itself), I can answer the question: The logic that overrides XDG_CONFIG_HOME has a few conditions. Specifically if you want the preset env var to be honored, the directory you point at must exist and cannot end with `/.config`.

**Comment by klaegera** [comment]
Thank you for your response.

I did not realize `Environment.SpecialFolder.ApplicationData` would correspond to the value passed to `XDG_CONFIG_HOME`. In that case the conditions are clear.

I would propose that an attempt be made to create the path specified by `XDG_CONFIG_HOME` before the value is overridden, since the current behavior seems to have lead to confusion in multiple threads, but of course I do not know the reasoning behind the current conditions and so cannot determine the downsides of such a change.

In that case I would now have to set `XDG_CONFIG_HOME` to a directory that is guaranteed to exist in the container, such as `/tmp`. The keypair would then not necessarily be persistent, but everything seems to work with this change.

I understand you do not officially support this setup, but could you let me know the downside if the keypair does not survive? It seems like the missing files are simply regenerated when needed.

**Comment by Taloth** [comment]
> I understand you do not officially support this setup, but could you let me know the downside if the keypair does not survive? It seems like the missing files are simply regenerated when needed.

The Sonarr UI will fail to reconnect to the backend when the container restarts, Sonarr restarts or gets updated. The keypairs are used by mono to encrypt a shared key between the signalr client and server that allows persistent communication.

**Comment by klaegera** [comment]
Alright, thank you for explaining. The keypair will survive simple container restarts and the UI can be reloaded if the container is recreated.
