### ISSUE TITLE
Identify Files with HDR colour space in 'Details'

### ISSUE THREAD

**Issue by oliv-j** [Sonarr/Sonarr#4761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

It is not currently possible to identify HDR files in Radar, so it makes it very difficult to identify and upgrade files in your library.

### Describe the solution you'd like

When going to a movie page's 'files' tab there is a 'details' button to show the video info, such as file size, language and codec. Currently this does not show Color space
Without showing the color space of a video it is not possible to know if a video file is HDR or SDR (a colour depth of 10bit or more does not mean that the video is HDR, it could still be SDR).

See [this](https://www.reddit.com/r/PleX/comments/7kwoy8/is_there_a_way_to_tell_if_a_file_is_hdr_from_the/) Reddit thread for a bit more background.

Top post from that thread:

"The only way to determine if a UHD video file is HDR or SDR is to us a program called MediaInfo. If the video is HDR it will have a color space of BT.2020 also know as REC.2020. If the video is SDR it will have a color space of BT.709 also known as REC.709. There is no commercial software available at the moment to convert HDR to SDR or vice versa. Only a few select UHD Blu-ray players can do this.
Edit: A video can can 8bit or 10bit and still be HDR or SDR. Color depth and color space are 2 different things."

### Describe alternatives you've considered

Using 3rd party software such as  MediaInfo (but I would have to log into the server to interrogate the local files directly to do this).

### Anything else?

<img width="479" alt="Screenshot 2021-11-26 at 09 38 25" src="https://user-images.githubusercontent.com/46562125/143559721-d28bcb35-7de6-4e00-8713-aa69f5cefb4c.png">

**Comment by bakerboy448** [comment]
Closing; this is sonarr not radarr

Both radarr and sonarr already use mediainfo (well radarr now uses ffprobe)

also not an issue as files can already be named accordingly with the HDR mediainfo tag
