### ISSUE TITLE
Provide health api endpoint that does not require API token

### ISSUE THREAD

**Issue by evanrich** [Sonarr/Sonarr#4766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I'm running sonarr in Kubernetes. Currently there are 2 ways for K8s to monitor the health of the sonarr service, a  TCP check and an HTTP check.  the TCP check only checks to see if it can open a socket to the 8989 port.   This doesn't necessarily guarantee that sonarr is up and ready to work.  A better check would be to use an http check which looks for a 200 response, indicating the API/service is up and running.  This would be made to the following:

/api/v3/system/status

Since there is no unauthenticated health point (like /healthz), this would require the following config:

```
 livenessProbe:
      httpGet:
        path: /api/v3/system/status
        port: 8989
        httpHeaders:
        - name: X-Api-Key
          value: abc123def456
```

This exposes your api key potentially to other people if they have access to your git repo.   K8s does not currently support using valueFrom and a secret.

### Describe the solution you'd like

Provide a health-only endpoint that does not require api key authentication, something like
```
/api/v3/system/health

or
/api/v3/health
```

this would return something back like "Ok" "UP", "Ready" etc. if sonarr is indeed functioning as expected/ready to work, and not timed out, hung, etc.  This way if anything other than a 200 is observed, kubernetes will restart the pod.

### Describe alternatives you've considered

there are no alternatives that I can find

### Anything else?

https://github.com/Sonarr/Sonarr/wiki/API
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
https://stackoverflow.com/questions/33484942/how-to-use-basic-authentication-in-a-http-liveness-probe-in-kubernetes

**Comment by markus101** [comment]
Added `/ping` endpoint (matches other endpoints we use for validating services are online) that will confirm it can access the DB and return a JSON result; if there is an error error information will be returned.

**Comment by onedr0p** [comment]
@evanrich until this is released you can write a probe like this using command instead of an http probe. You'll need curl and bash in the container.

```yaml
command: 
  - /usr/bin/env 
  - bash 
  - -c 
  - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while 
    read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
```
