### ISSUE TITLE
Sonarr keeps redownloading shows

### ISSUE THREAD

**Issue by vanth0me** [Sonarr/Sonarr#4770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For example Band of Brothers gets downloaded when the application searches. I already have the complete shows. I see this on others shows as well and regularly check the trash folder to see if something got replaced with something worse.

Upgrading is disabled in file management and in profiles

### Expected Behavior

Once a show is downloaded it will not be downloaded again. 

### Steps To Reproduce

1. Add a show.
2. Press search monitored or wait for an auto sync.
3. It gets downloaded

### Environment

```markdown
- OS: Windows 10
- Sonarr: 3.0.6.1342
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/7626195/sonarr.trace.txt)

### Anything else?

Nothing else really.

**Comment by PearsonFlyer** [comment]
You almost certainly have Proper/Repacks selected as an upgrade/replace, which is causing this behavior. That behavior overrides your upgrade settings.

**Comment by vanth0me** [comment]
No it is disabled. It actually just happend again with me telling to blacklist the episodes.
Here is your proof.
![image](https://user-images.githubusercontent.com/28623044/144062459-5752e6b8-b988-4a2d-8b6b-18b5132c3f46.png)

**Comment by PearsonFlyer** [comment]
Well, when you block list an episode, it automatically kicks off a new search.

But why it got it initially if you didn't specifically search for it, I don't know. We'd need logs for that behavior.

**Comment by vanth0me** [comment]
I uploaded my trace log from the moment it happend. Afaik there aren't any other kind of logs.

**Comment by bakerboy448** [comment]
Those logs show nothing related to band of brothers at all.

more than likely a release profile preferred word upgrade - which are ALWAYS upgrades and cannot be turned off

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

**Comment by vanth0me** [comment]
Sorry I updated my post with the correct files. I guess it was updated just before I downloaded it.

So if a profile contains a preferred term (like rarbg eg) used for searching, it will automatically upgrade? That sounds kinda stupid..

**Comment by PearsonFlyer** [comment]
That is correct. A preferred word is preferred, so it's an upgrade. That's exactly what you told Sonarr to do.

**Comment by vanth0me** [comment]
So is there any other way to tell Sonarr when searching what to pick up and not upgrade after that?
For example with anime you might prefer a few groups, but if both of them release the same episode you don't want it twice.

**Comment by bakerboy448** [comment]
Again, Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

GitHub issues are not for questions.

Again, preferred words are always upgrades and there is no way to disable that currently. This is covered in the docs.  If the score improves it, then it will be grabbed.

https://github.com/Sonarr/Sonarr/issues/4302

**Comment by vanth0me** [comment]
Well thanks I'll ask there. Upvoted the idea because this is not ideal imo.
