### ISSUE TITLE
Pinned Directories in Manual Adding

### ISSUE THREAD

**Issue by xagesz** [Sonarr/Sonarr#4772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

It is not a problem. Just an inconvenience. As an anime lover sorting bulk can be hell.  My media is always in subfolders in 1 or directories. Being able to pin a directory or 2 at the top of the manual import for quick finding of subfolders would be awesome. 

### Describe the solution you'd like

Just an icon next to directory or a checkbox when selecting the directory to mark it as a pinned directory.  

Then either have it at the top of recents.  or icons above the text bar for quick finding.

### Describe alternatives you've considered

Y'all are more inventive than me. Its a simple problem/inconvenience that I would like a solution too.

### Anything else?

No thanks

**Comment by markus101** [comment]
No immediate plans for such a feature, but something we'll re-evaluate in the future.
