### ISSUE TITLE
Give Names to Regexes

### ISSUE THREAD

**Issue by ItsME6969** [Sonarr/Sonarr#4775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When releases are rejected, sonarr will show you the whole regex and if its a complicated one, you start wondering what the regex does. It would be simpler if instead of showing the regex to just show the name of the regex, so naming is needed
![Screenshot 2021-12-03 123622 - Copy](https://user-images.githubusercontent.com/89707006/144664073-6adce731-e65f-408a-81e8-cdadc46f9506.jpg)
.

### Describe the solution you'd like

Custom Formats like on Radarr woulda been the ideal solution obviously, but not sure if that's out the window.

### Describe alternatives you've considered

Adding an extra Column just for the name
![Screenshot 2021-12-03 122656 - Copy](https://user-images.githubusercontent.com/89707006/144664106-2624ec38-c4ad-42ae-a469-339d217c89b6.jpg)
s.

### Anything else?

After naming them, maybe consider showing them when hovering over the score because it takes time trying to figure out why this release has 11, why this one has a 10, etc, etc
![Screenshot 2021-12-03 123622 - Copy](https://user-images.githubusercontent.com/89707006/144664290-fa404031-76e5-4fc8-80ab-365471cbb7e3.jpg)

**Comment by markus101** [comment]
We do not have plans to name regexes, showing the breakdown of the score is covered by https://github.com/Sonarr/Sonarr/issues/4693
