### ISSUE TITLE
UI: Allow custom text in HTML title bar

### ISSUE THREAD

**Issue by KarmicIT** [Sonarr/Sonarr#4778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

A common question lately for the *arr's is to allow a single instance of the application to support multiple versions of a download (i.e. 1080p and 4k versions). This is not currently possible and the workaround is to run multiple instances instead, one per download type.

I'd like to request the ability to "name" an instance and have that name shown in the HTML title bar, either next to - or replacing - the existing text of "Sonarr". This would let people easily see which instance they are currently browsing without needing to remember that the Sonarr instance on port 1234 is the 4k version versus the instance on port 4321 which is for 1080p.

This feature could be added within the Settings>General>Host area, with a freeform text box that is only visible when showing advanced options is enabled.

### Describe alternatives you've considered

Raw HTML files are not available to edit and would be overwritten by any updates.

### Anything else?

This capability already exists for hard-coded menus and TV names when you browse the GUI. I.e. if you go to the Settings menu the HTML title bar shows "General Settings - Sonarr". Likewise, if you are looking at a TV show it will say "Archer (2009) - Sonarr".

This request would enable the HTML title bar to show something similar to "Indexer Settings - 1080p - Sonarr" or "Archer (2009) - All Your Base Are Belong To Us - Sonarr", etc.

**Comment by Birdheezy** [comment]
I'd like to 2nd this

**Comment by markus101** [comment]
This was closed via the linked PR.
