### ISSUE TITLE
Preserve file dates on import

### ISSUE THREAD

**Issue by spooki3** [Sonarr/Sonarr#4786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

File date/timestamp gets updated on import to current system time on *nix.
Did not have experience this when running Sonarr on Windows.
At least in my running config with Sonarr and NZBGet as docker containers. I have a mounted/mapped a download share on the NAS where my containers are running to both Sonarr and NZBGet and a different share where Sonarr imports the shows.

I have NZBGet configured to preserve the files date of the files inside the archive upon extracting.
I would like to be able to keep the original file date on import using Sonarr.

Sonarr currently only has the following "Change File Date" options :"None", " Local Air Date"  and "UTC Aire Date" 
None does not preserve the file date of the downloaded files. Probably because of a "cp" instead of a "cp -p" 

### Describe the solution you'd like

Have the option to preserve the original file date/time stamp of the files on import.

### Describe alternatives you've considered

Switching back to my Windows setup however that would require to keep a machine running.
Wanted to move to a docker setup because the nas is always running.

Only alternative on the NAS is to move the downloads myself to the proper directories after download and not have Sonarr import them.

### Anything else?

Would help to prevent older episodes which have recently be downloaded to show up in MrMC (and probably Kodi) as recently added. But that is a personal preference

**Comment by markus101** [comment]
Sonarr does not use `cp` directly it is done through mono, we don't have plans to investigate this behaviour under mono as we're working towards dropping it for .net 6. In the mean time a custom script to change the date after import would be your best option.

**Comment by spooki3** [comment]
Thank you for the reply. I can completely understand it won't be investigated under mono when moving to .net 6.
It would be very nice for the .net 6 implementation though if this was possible

**Comment by Taloth** [comment]
> NAS where my containers are running to both Sonarr and NZBGet and a different share where Sonarr imports the shows.

You should fix this instead. Having different shares means files are being copied, rather than moved and renamed, which is bad for performance as well.
