### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by JamieSlome** [Sonarr/Sonarr#4787]
Hey there!

I belong to an open source security research community, and a member (@dwisiswant0) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by bakerboy448** [comment]
[discord](https://discord.gg/Ex7FmFK) and getting in touch with Markus or Taloth is likely be the best bet as far as the disclosure route, for now at least.

Same concept - albeit different discords and a different dev team - for Lidarr/Radarr/Readarr/Prowlarr for future reference.

**Comment by JamieSlome** [comment]
@bakerboy448 - thanks for the support here!

Just for reference the private report can be found here:

https://huntr.dev/bounties/c8e90d5b-c1df-449b-9a5e-b9a5a6189879/

It is only accessible to maintainers with write access to this repo 🤝

**Comment by Taloth** [comment]
Nice catch there, we should be able to fix it. Also thx for the SECURITY.md suggestion, most ppl can find us one way or the other, but having it explicitly in an .md file is a good idea.

**Comment by JamieSlome** [comment]
@Taloth - great, thanks for the confirmation!

If you think the report is valid, you can mark it on the report page, and the researcher will be awarded their bounty for their research.

Also, you can bag a bounty for fixing it too! 🤗

**Comment by dwisiswant0** [comment]
Any updates on this, @bakerboy448 & @Taloth?
