### ISSUE TITLE
Rename adds a "-" when {-ReleaseGroup} is used

### ISSUE THREAD

**Issue by ptheofan** [Sonarr/Sonarr#4795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Format
`{Series Title} - S{season:00}E{episode:00} - {Episode Title} {Quality Full} {-ReleaseGroup}`

### [BUG] Adds a hyphen "-" before release group
Will rename
`chuck.s05e13.1080p.bluray.x264-p0w4hd.mkv`
to
`Chuck - S05E13 - Chuck Versus the Goodbye Bluray-1080p -p0w4hd.mkv`

### [WORKS AS EXPECTED] Will not add release group when it cannot determine it
Will rename
`Chuck S04E09 Chuck Versus Phase Three (1080p x265 Joy).mkv`
to
`Chuck - S04E09 - Chuck Versus Phase Three HDTV-1080p.mkv`

### Expected Behavior

The expected behaviour of `{-ReleaseGroup} `
1. Add the Release Group without prepending a hyphen "-" when release group is known
2. To not add the release group if it cannot be determined

### Steps To Reproduce

1. Go to media management
2. Enable Rename
3. Append {-ReleaseGroup} to the Episodes format (all 3 of them)
4. Go to a series and click rename
5. In the preview you will see the behaviour

### Environment

```markdown
- OS: Unraid
- Sonarr: 3.0.6.1342
- Docker Install: 3.0.6.1342-ls128 by linuxserver.io
- Using Reverse Proxy: Yes
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

Not relevant

### Anything else?

![image](https://user-images.githubusercontent.com/880939/145713627-2d4bd54d-4a85-4909-802f-0e66aaccf47a.png)

**Comment by PearsonFlyer** [comment]
You are literally telling Sonarr to add the hyphen in your naming convention. Just use {ReleaseGroup} if you don't want the hyphen. It's doing exactly what you told it to do. Not a bug.

**Comment by Taloth** [comment]
This is really the best example of It's a Feature not a Bug. Gave me a good chuckle.

Yup, use `{Release Group}`.

**Comment by ptheofan** [comment]
If I use `{Release Group}` when it cannot identify the release group it adds `Sonarr` as a release.

**Comment by Taloth** [comment]
It's not specifically `-`, it's any separator that's inside the curly braces instead of outside, also at the end. This should satisfy your usecase:
 `{Series Title} - S{season:00}E{episode:00} - {Episode Title} {Quality Full}{ ReleaseGroup}`

**Comment by ptheofan** [comment]
Confirmed, adding the space does result in the desired output.
Many thanks.
