### ISSUE TITLE
Loggout button doesnt show up with authentication:basic

### ISSUE THREAD

**Issue by sachinhegde6** [Sonarr/Sonarr#4797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Logout button doesn't show up when authentication type is Basic(browser pop-up)
<img width="1232" alt="Screen Shot 2021-12-12 at 11 36 35 AM" src="https://user-images.githubusercontent.com/18535164/145726907-7c1aa302-355b-4678-972e-47dc8974ca16.png">

### Describe the solution you'd like

Logout button when Authentication is basic. Similar to when authentication is form based

### Describe alternatives you've considered

Changing authentication to form based

### Anything else?

I can help in fixing the issue, i have background in security domain, but this would be my first open source contribution, so will need some time and guidance.

**Comment by thezoggy** [comment]
Clear cookies?

**Comment by sachinhegde6** [comment]
I tried clearing cooking, did not fix the problem. My Sonarr is running on Unraid as a docker instance 


Version
    3.0.6.1342
Package Version
    3.0.6.1342-ls128 by linuxserver.io 
Mono Version
    5.20.1.34

**Comment by markus101** [comment]
This is expected behaviour, a log out button with basic auth relies on workarounds (read hacks) and still has the potential for the browser to still cache the old credentials. If you want a log out button use forms auth, otherwise you'll need to close the browser window to log out.
