### ISSUE TITLE
Error While Manually Importing Series - Files Moved, Never Removed from Queue

### ISSUE THREAD

**Issue by IAmAProgrammerAmA** [Sonarr/Sonarr#4803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are series that, when imported, do not leave the queue. The files are moved, but they are still marked as needing manual import, even though it was already done. It is impossible to clear these series.

When manually importing them, every step works, until at the very end the task fails and the series isn't removed from the queue. 

### Expected Behavior

The series to succeed, and to be removed from the queue.

### Steps To Reproduce

1. Manually import series.
2. Set all fields.
<img width="1257" alt="Screen Shot 2021-12-14 at 9 42 32 PM" src="https://user-images.githubusercontent.com/94947906/146130491-51187798-fbfa-4651-89e6-7e28fdbafd36.png">

3. See as the series files all move correctly, but the series errors out.
4. Repeat as desired.
<img width="1252" alt="Screen Shot 2021-12-14 at 9 42 40 PM" src="https://user-images.githubusercontent.com/94947906/146130497-4261926e-9bc9-46ca-852b-aa833c91a60c.png">

### Environment

```markdown
- OS: Unraid OS 6.9.2
- Sonarr: 3.0.6.1390
- Docker Install: Yes
- Using Reverse Proxy: Yes
```

### What branch are you running?

Develop

### Trace Logs?

https://gist.github.com/IAmAProgrammerAmA/2adc68cde71d3ca4a13655df1dc94fc7

### Anything else?

This has happened with a variety of series, this example is just the smallest one I could find. Everything imports correctly, but nothing is actually fixed once it does.

It makes cleaning out the queue tedious, as this is happening for many series in my queue.

**Comment by IAmAProgrammerAmA** [comment]
I've updated to 3.0.6.1412, which should have [8621ecf](https://github.com/Sonarr/Sonarr/commit/8621ecfec1e39fce52e18494bfcbb1a1b09cb50c) in it. This issue isn't resolved, it still occurs. New logs attached from the new version.

https://gist.github.com/IAmAProgrammerAmA/9539c43484bf1633d05a4278533573a7

**Comment by bakerboy448** [comment]
> [Arid] Liz and the Blue Bird [CBFC03C6]

is not a valid file name

**Comment by IAmAProgrammerAmA** [comment]
> neither
> 
> > [MTBB] Sora yori mo Tooi Basho (BD 1080p)
> 
> nor
> 
> > [Arid] Liz and the Blue Bird [CBFC03C6]
> 
> Are valid file names

This is during a manual import, in which I manually specify the correct naming scheme. Should that still cause it to fail?

Specifically I:
* Manually Import the file, filling out all fields as shown here:

<img width="1257" alt="Screen Shot 2021-12-14 at 9 42 32 PM" src="https://user-images.githubusercontent.com/94947906/146130491-51187798-fbfa-4651-89e6-7e28fdbafd36.png">

* It is hardlinked over, but is never removed from the queue, and so I have ~60 items stuck in this limbo.
