### ISSUE TITLE
Allow remote tag filters for Sonarr list import

### ISSUE THREAD

**Issue by kageurufu** [Sonarr/Sonarr#4804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I use two sonarr instances, one to manage 4k content exclusively. Currently i'm using Syncarr to auto-sync tagged items from the HD instance to the 4K instance, and auto-sync all items from 4K down to HD.

### Describe the solution you'd like

I can replace the 4K -> HD sync using the Sonarr list import. 

However, I only want select tags from the HD instance to sync to the 4K instance. I would like to be able to select tags to import from the remote instance.

### Describe alternatives you've considered

I currently use Syncarr for this purpose, but it would be nice to not need the extra docker container running for that.

### Anything else?

https://github.com/syncarr/syncarr

**Comment by bakerboy448** [comment]
Closing  - already exists

![image](https://user-images.githubusercontent.com/55419169/146267888-e31a370d-e3be-4352-88eb-a7b8150b3ea0.png)

**Comment by kageurufu** [comment]
Guess i'm just out of date. Sorry!

>

**Comment by bakerboy448** [comment]
should be on v3.0.6
