### ISSUE TITLE
Refreshing the Activity > Queue does not refresh the web page contents so the user can see the up to date data

### ISSUE THREAD

**Issue by ChaosBlades** [Sonarr/Sonarr#4805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you go to Activities > Queue on the Left side of the main page while a download is in progress (torrent in this case, may work differently with nzb?) and you click the Refresh button at the top of that page Sonarr will pull an update to the data presented internally but does not refresh the data presented to the user. The user then needs to refresh the entire web page in order to see the updated information.

### Expected Behavior

The refresh button should also update the web pages visual elements in addition to internal data.

### Steps To Reproduce

1. On main page select Activities
2. Go to Queue while a download is in progress
3. Click the Refresh button
4. Notice the visual elements on the web page do not change until you refresh the entire web page

### Environment

```markdown
- OS: Ubuntu 20.04.3 LTS x86_64
- Sonarr: 3.0.6.1342
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Brave 1.26.67 (Chromium: 91.0.4472.114)
```

### What branch are you running?

Main

### Trace Logs?

I don't think these are necessary in this case. Let me know otherwise.

### Anything else?

**Stretch Goal:** Would be nice if the refresh interval was shorter while the specific web page is being viewed.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

this is likely a browser issue or permissions issue in your app data folder

**Comment by ChaosBlades** [comment]
I doubt this is a permissions issue but it being an issue with Brave browser seems possible. I have made a thread on reddit to see what others experiences have been. I still think Sonarr isn't calling for the data to be updated in the browser unless you know this code exists. I thought the refresh button only triggered the refresh task but it would also need to call for the browser to pull that update as well in this case.

https://www.reddit.com/r/sonarr/comments/rhf2r3/browser_issue_refreshing_the_activity_queue_for/

**Comment by bakerboy448** [comment]
The code exists and is not a Sonarr issue.

if you go to your browser dev console you'll likely see no connections to signalr which handles the UI updates

which is a browser issue or permissions issue on your config mount - possibly too permissive given you're not using a reverse proxy 

anyway - see the support channels for further discussion

**Comment by thezoggy** [comment]
Or adblocker
