### ISSUE TITLE
Improper Quality

### ISSUE THREAD

**Issue by natethegreat14199** [Sonarr/Sonarr#4807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is expecting it to be 480p even if 2160p is in the title. Once downloaded, it goes ahead and adds it even though 1080p is highest requested.

### Expected Behavior

2160p should be recognized as 2160p or 4k, not as 480p

### Steps To Reproduce

Unknown, it just happens. I have a show listed as "Up to 1080p" and it downloads as 480 and imports as 2160p

### Environment

```markdown
- OS: Ubuntu 20.04.3 LTS Focal Fossa
- Sonarr: 3.0.6.1342
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Chrome but not UI related
```

### What branch are you running?

Main

### Trace Logs?

I waited too long to fill this out. My logs stops at 11:4? this morning and it occurred  before that.

### Anything else?

![image](https://user-images.githubusercontent.com/64567201/146621903-07aa6e85-c5f0-4341-846e-627e4912158f.png)
![image](https://user-images.githubusercontent.com/64567201/146622173-0f09983b-2aa1-4591-afbf-690a16a67319.png)

Release Name = Game.of.Thrones.S05E01.The.Wars.to.Come.2160p.BDRip.AAC.7.1.HDR10.x265.10bit-MarkII	

Game.of.Thrones.S05E01.The.Wars.to.Come.2160p.BDRip.AAC.7.1.HDR10.x265.10bit-MarkII
--

<br class="Apple-interchange-newline">

Game.of.Thrones.S05E01.The.Wars.to.Come.2160p.BDRip.AAC.7.1.HDR10.x265.10bit-MarkII
--

<br class="Apple-interchange-newline">

**Comment by bakerboy448** [comment]
Need the full release name

**Comment by natethegreat14199** [comment]
> Need the full release name

Release name for the OS or the show?

**Comment by thezoggy** [comment]
release name = the release

**Comment by markus101** [comment]
Copying and pasting the full release name instead of a screenshot is much more helpful.
