### ISSUE TITLE
Support Automatic "Downgrade"

### ISSUE THREAD

**Issue by orecus** [Sonarr/Sonarr#4808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

New Request.

### Describe the solution you'd like

It would be useful to have the option per Quality Profile to set if Sonarr should downgrade higher quality files, to the "Upgrade Until" quality.

This would be useful in going from a higher quality profile to a lower one, and you wish to "downgrade" all episodes to that quality, even if the currently downloaded ones are of a higher quality.

A checkbox on a Quality Profile page, which if checked would allow the downgrade of higher quality downloaded files, to the quality set in the "Upgrade Until" field, alternatively a "Downgrade Until" field, that is similar to the "Upgrade Until" field.

### Describe alternatives you've considered

Currently going trough each episode and doing a "Manual" search, time consuming and boring. Sonarr should be able to automate this, if you want.

### Anything else?

No

**Comment by Thirrian** [comment]
Already possible if you create a profile where you reverse the order of the qualities.

**Comment by orecus** [comment]
Ahh right. But then you need to have multiple profiles and remember to switch between them.

It would be much cleaner to have that integrated into the profile itself, instead of that workaround I think.

**Comment by bakerboy448** [comment]
Related to https://github.com/Sonarr/Sonarr/issues/2162

defer to markus/Taloth for this one if there are any plans

**Comment by markus101** [comment]
No plans to implement this at this time, but something we’ll reconsider in the future.
