### ISSUE TITLE
If a download completes but files aren't present immediately, the queue often fails to switch from "Waiting To Import" to "Importing"

### ISSUE THREAD

**Issue by bavis-m** [Sonarr/Sonarr#4811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My download folder is an SMB share on a remote server that I run rtorrent on. Rtorrent has scripts set up to hardlink files form the rtorrent download location to the SMB share immediately when the finish downloading, but if there are rar'd files in the release, they don't appear right away. When the files do appear, my sonarr box starts downloading them (after ~60 seconds for the refresh to happen), as verified by smbstatus, however the queue entry for that release will stay at "Waiting To Import". This is often annoying as it takes a couple of minutes for multi-gig releases to copy over WAN, and if I accidentally try and refresh or manually import the release, I can accidentally cause it to delete the in-flight file, which means spending more minutes downloading it again without me realising (a progress bar for "Importing" to mirror the one for "Downloading" would be amazing as well, but that's for another issue). Note: the issue doesn't happen every single time, but it does happen more often than not to me.

### Expected Behavior

If Sonarr picks up a file for a release sometime after the download has already completed, the queue entry should still update to "Importing"

### Steps To Reproduce

1. Point a file mapping to somewhere where Sonarr won't pick up completed downloads right away
2. Download a release through Sonarr, wait some time until Sonarr has changed to "Waiting To Import", and has had a chance to scan the downloads (it usually reports "No files found in /your/dir"
3. Hardlink the downloaded file to the mapped path
4. Use your choice of filesystem monitoring to see that Sonarr has opened the file and is copying it
5. Sonarr still says "Waiting To Import", even though it is copying
6. Sonarr will remove the item from queue without ever claiming the release is "Importing"

### Environment

```markdown
- OS: Arch Linux
- Sonarr: Radarr 3.2.2.5080
- Docker Install: binhex-radarr
- Using Reverse Proxy: yes, nginx
- Browser: chrome
```

### What branch are you running?

Main

### Trace Logs?

In this case, the release was Ocean's 8 through Radarr: https://pastebin.com/3WrhS5xw

### Anything else?

N/A

**Comment by bakerboy448** [comment]
This is Sonarr not Radarr.

This is not a bug, but is simply a suboptimally configured setup.
Users should not have files appear available to import if they are not fully there. Plenty of users run sync setups without issue. 

There is no point in having your download client hardlink to a different path as sonarr does that natively for importing anyway.

Also use Unpackerr rather than download client extraction scripts that always cause these issues.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

**Comment by bavis-m** [comment]
@bakerboy448 My download client and sonarr are on different machines, so it doesn't make sense to say that Sonarr will hardlink them (they can't be hardlinked on the Sonarr machine anyways, as the downloads and my local media folder are on different filesystems, cifs and ext4 respectively). Also, the unrar-ing happens in the rtorrent download location, and then the fully unrar-ed files are hardlink to the smb hosted directory, so no files appear to Sonarr that are not "fully there". The fact that it sometimes does switch to "Importing" and sometimes doesn't suggests that the correct behaviour is not being followed here.

**Comment by bakerboy448** [comment]
Then grab [trace logs](https://wiki.servarr.com/sonarr/troubleshooting#logging-and-log-files) of Sonarr doing what you're saying and 
swing by one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr) to look into this further.

ideally discord

For future reference - bug reports need trace logs, not info logs - which are informational only and almost never useful for debugging nor bug reports

**Comment by bavis-m** [comment]
Yeah, that's my bad, the most recent example I had was from Radarr and I guess I had turned trace logs on for Sonarr and not Radarr. I find it way more likely a movie release is rar'ed rather than TV releases on my tracker. I guess I'll post over there; I was under the assumption that they used the same backend codebase.

**Comment by bakerboy448** [comment]
> same backend codebase.

Similar

> I guess I'll post over there

The same bug report will likely be closed over there as well;  come vet it out on the support channels

Radarrs:

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.
