### ISSUE TITLE
PPA Repository Certificate

### ISSUE THREAD

**Issue by mpearon** [Sonarr/Sonarr#4813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Followed directions from [https://sonarr.tv/#downloads-v3-linux-ubuntu](here).

```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8
echo "deb https://apt.sonarr.tv/ubuntu xenial main" | sudo tee /etc/apt/sources.list.d/sonarr.list
sudo apt update
```
Response is as follows:
```
Err:11 https://apt.sonarr.tv/ubuntu xenial Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Hit:12 https://download.mono-project.com/repo/ubuntu stable-xenial InRelease
Hit:13 https://mediaarea.net/repo/deb/ubuntu xenial InRelease
Reading package lists... Done
E: The repository 'https://apt.sonarr.tv/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Visiting in the repository in a web browser yields a certificate error.

### Expected Behavior

Standard APT behavior

### Steps To Reproduce

Followed directions for 16.04.7 Xenial: https://sonarr.tv/#downloads-v3-linux-ubuntu

```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8
echo "deb https://apt.sonarr.tv/ubuntu xenial main" | sudo tee /etc/apt/sources.list.d/sonarr.list
sudo apt update
```
Response is as follows:
```
Err:11 https://apt.sonarr.tv/ubuntu xenial Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Hit:12 https://download.mono-project.com/repo/ubuntu stable-xenial InRelease
Hit:13 https://mediaarea.net/repo/deb/ubuntu xenial InRelease
Reading package lists... Done
E: The repository 'https://apt.sonarr.tv/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Visiting in the repository in a web browser yields a certificate error.

### Environment

```markdown
- OS: Ubunutu 16.04.7 LTS
- Sonarr: N/A
- Docker Install: N/A
- Using Reverse Proxy: False
- Browser: N/A
```

### What branch are you running?

Main

### Trace Logs?

This doesn't really apply, but I can provide logs if necessary.

### Anything else?

N/A

**Comment by thezoggy** [comment]
Update your certs / curl. Due to let's encrypt cert expired

**Comment by markus101** [comment]
Zoggy is correct, the certificate is valid, but your system is failing to validate it. You can put that URL in chrome and it’ll show it’s valid.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) if you have any more questions about this.

**Comment by mpearon** [comment]
@markus101 Are you talking about this URL?
https://apt.sonarr.tv/ubuntu

When I hit that in Safari (working from my phone right now), I get a cert error.  I'll check again when I'm back around my machine.

**Comment by mpearon** [comment]
Thank you @markus101 and @thezoggy 

If anyone else stumbles across this, my fix was to simply run
`update-ca-certificates`
