### ISSUE TITLE
Switch from MediaInfo to FFProbe

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

MediaInfo will crash on various video files for various reasons and is an annoying dependency.

This crashing frequently causes support issues and confusion for users.

Let's switch to FFProbe like Radarr has so we remove an external dependency and also bundle our own current version.

MediaInfo also detects incorrect Audio - See Radarr GHI https://github.com/Radarr/Radarr/issues/6057

### Describe the solution you'd like

MediaInfo => FFProbe

radarr relevant commits (possibly missed some)
- https://github.com/Radarr/Radarr/commit/f0f8a4ffaf65b892aa6e6fb6290096dfd8d5e7b2
- https://github.com/Radarr/Radarr/commit/26cedfd47dbc7fff951c538b8f85751f104d4f0d
- https://github.com/Radarr/Radarr/commit/7bbd2246c43cf6ff34e5539450e8d5e829588332
- https://github.com/Radarr/Radarr/commit/13e44ce19a75dad873866e460548616aee837130
- https://github.com/Radarr/Radarr/commit/75270d81510512d325953b745839ba78fd436d5c
- https://github.com/Radarr/Radarr/commit/fda1ad237bc9d93e420f637ece0c09d524b8b44b
### Describe alternatives you've considered

Keep MediaInfo - but why?

### Anything else?

N/A

**Comment by markus101** [comment]
Can ffprobe detect and report potentially malicious executables that is necessary to address https://github.com/Sonarr/Sonarr/issues/3331 ?

**Comment by bakerboy448** [comment]
> Can ffprobe detect and report potentially malicious executables that is necessary to address #3331 ?

Defer to @ta264 

presumably at worst it'd exit with a non-0
Would that be something that can be patched in?

**Comment by markus101** [comment]
This will land in v4.
