### ISSUE TITLE
manual Parsing Ignore list for TVshows as shows are not being parsed or parsed wrongly

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#4819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some of the Chinese trackers keep the chinese name in front of the english name of a torrent which results in sonarr not being able to parse the show. Or the chinese show name is put in brackets in front of the show name in that case although the show is parsed the chinese name of the show is parsed as the release group.

输赢.Win the Future.E09.2021.WEB-DL.2160p.H265.AAC-PTerWEB.mp4
[三生有幸遇上你].Lucky.With.You.2021.E06.4K.WEB-DL.H265.AAC-PTerWEB.mp4

As asian shows are usually 1 season only some groups release the season batch with complete instead of S01 and the parser is unable to parse. 

### Describe the solution you'd like

I see 2 solutions. 
1 is that sonarr auto ignores then Chinese name it gets from tvdb of every tv show when parsing. This though probably the more elegant solution is not practical as the tvdb data can be different or incomplete. 
2nd solution is that a user is able to add names/strings it wants the parser to ignore or replace when parsing. I think the 2nd solution is the better option as it gives more control. 

### Describe alternatives you've considered

none

### Anything else?

I know some of the devs don't like to add options that will break stuff because of user stupidity as they don't want to deal with the support requests. But I hope this is adopted.

**Comment by bakerboy448** [comment]
seems like some other parsing gaps as well

![image](https://user-images.githubusercontent.com/55419169/147428268-74bc0078-f86a-4d86-92cc-77c9040dd07c.png)
![image](https://user-images.githubusercontent.com/55419169/147428284-7dc5b7f0-05c4-4c96-bedb-8868d7d0cefb.png)

the 4k one may be handled by https://github.com/Sonarr/Sonarr/pull/4625

**Comment by markus101** [comment]
1. If properly separated Sonarr will be able to parse it (often times this is using non-standard brackets), but simply separated by a space or period will not, otherwise an alias will be required.
2. No plans to add a list of things that are cleansed from release names before processing
