### ISSUE TITLE
Sonarr show directories in recycle bin missing group write permission

### ISSUE THREAD

**Issue by dedworks** [Sonarr/Sonarr#4823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Sonarr puts media in its recycle bin, the show directories do not have write permission enabled for the group. 

The result is that I have to manually change the permissions of the recycle bin directories before I can move, rename or delete files in the bin. 

These are the permissions for the show directory after a Sonarr import, consistent with my "Set permissions" setting:
$ ls -al /mnt/media/tv/{show-name}\ \(2021\) -d
drwxrwxr-x 1 1025 users 388 Dec 29 20:30 '/mnt/media/tv/{show-name} (2021)'

These are the permissions missing group+write after Sonarr puts an episode in the recycle bin:
$ ls -al /mnt/media/tv/.recycle/{show-name}\ \(2021\) -d
drwxr-xr-x 1 1025 users 182 Dec 29 20:30 '/mnt/media/tv/.recycle/{show-name} (2021)'

### Expected Behavior

Ideally I would want the directories and files in Sonarr's recycle bin to honor the "Set permissions" option under Media Management settings. 

Or, it should at least retain the permissions the original show directory had before it was put in the recycle bin. 

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 3.0.6.1342-ls129
- Docker Install: yes
- Using Reverse Proxy: n/a
- Browser: n/a
```

### What branch are you running?

Main

### Trace Logs?

n/a

### Anything else?

n/a

**Comment by markus101** [comment]
Same as this issue: https://github.com/Sonarr/Sonarr/issues/3161 we do not have plans to set permissions when moving series to the recycling bin folder, nor does Sonarr change permissions now when doing so.

**Comment by bakerboy448** [comment]
The solution is to have the proper umask set for sonarr and your download client
