### ISSUE TITLE
only import items that are upgrades or improvements

### ISSUE THREAD

**Issue by jonoff** [Sonarr/Sonarr#4828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When manually importing, some items may be lower or the exact same quality of currently existing items in the database. These duplicate/lower quality items should be ignored/marked for skipping import.

### Describe the solution you'd like

When comparing new and existing files, duplicate/lower quality files shouldn't be imported.

### Describe alternatives you've considered

Carefully combing through files before import.

### Anything else?

n/a

**Comment by thezoggy** [comment]
one would ask, why are you trying to import the same items?

**Comment by markus101** [comment]
Sonarr does not reject equal quality imports, but lower quality imports are already rejected.

**Comment by jonoff** [comment]
Consider this request to only cover equal quality imports. Instead of replacing without improvement, can they be flagged/rejected instead.
