### ISSUE TITLE
Include Backup and/or Database Size on system/backup UI table.

### ISSUE THREAD

**Issue by davidnewhall** [Sonarr/Sonarr#4830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No specific problem. Having the database or at least zip file sizes on display will make it easier to identify a problem with the backup or the included Sonarr.db file.

### Describe the solution you'd like

I'd simply like a new column added to the `/system/backup` list that shows the backup file size. Bonus if a second column was added that shows the database size inside the compressed backup. I've seen 100MB backups extract to over a gigabyte, so having this would be doubly-useful for quick identification of issues. I understand the first is a file `stat` and the second probably requires storing some info, so it's understandable if that's not desirable. 

### Describe alternatives you've considered

The only way I can tell the file size is to download it. Not sure there is any alternative. 

### Anything else?

<3 snoarr

Here's a mock of what I think could be useful:

![Screen Shot 2022-01-01 at 1 17 46 PM](https://user-images.githubusercontent.com/2402929/147860419-b16dfeb7-cf7e-4627-83c2-9f7baf8da6b9.png)

**Comment by ZackaryH8** [comment]
I'm working on this feature

**Comment by davidnewhall** [comment]
Thank you!
