### ISSUE TITLE
Media Not Leaving Queue After Manual Import

### ISSUE THREAD

**Issue by IAmAProgrammerAmA** [Sonarr/Sonarr#4831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The fix from #4803 didn't resolve the issue, so I'll explain it better here, and hopefully give enough info for it to be resolved.

When manually importing media from the queue, everything works as expected, but it is never marked as completed and so remains in the queue forever. This happens to a variety of media, but I'll focus on one specific media, `[Arid] Liz and the Blue Bird [CBFC03C6]`. I'm aware this isn't valid naming, and this bug isn't about the automatic matching, which I would expect to fail. It's that a manual import doesn't remove the item from the queue.

This item persists across reboots/refreshes, so this isn't a UI Issue but a deeper issue.

### Expected Behavior

I'd like the manually imported item to be removed from the queue. Having a queue of 100+ already imported items is hard to deal with.

### Steps To Reproduce

1. Manually import media file
2. Fill out all fields correctly
3. Click import
4. File is imported, but not removed from the queue

Attached is a screen recording of the specific steps to go through this loop.

https://user-images.githubusercontent.com/94947906/147886474-1330825c-803f-4564-bda7-f80e850f4fe9.mov

### Environment

```markdown
- OS: Unraid OS 6.9.2
- Sonarr: 3.0.6.1432
- Docker Install: yes
- Using Reverse Proxy: yes
```

### What branch are you running?

Develop

### Trace Logs?

https://gist.github.com/IAmAProgrammerAmA/2adc68cde71d3ca4a13655df1dc94fc7

### Anything else?

If this new issue isn't welcome, please just close. I thought that using a new issue with more information and a more clear description on my part would be appreciated.

**Comment by markus101** [comment]
Next time please include updated logs so we can see any relevant errors.
