### ISSUE TITLE
Changing profile to regain disk space.

### ISSUE THREAD

**Issue by pumpkinpi85** [Sonarr/Sonarr#4834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Concerning feature request. I understand that you can select a profile for a series and that Sonarr will search for the selected profile until it is available to download. Even replace existing series files to achieve the desired profile, if existing series files are lower in profile than desired profile. 

### Describe the solution you'd like

Is it possible to have the feature described above work in reverse? For example, changing profile quality from 1080p to 720p on a series in the hopes of regaining disk space.

### Describe alternatives you've considered

Deleting series manually and selecting new profile was considered. However on a large media server it would be a lot of manual labour where automation makes more sense. Additionally you risk loosing data by possibly not finding the series again.

### Anything else?

If this is already a feature I've had no success on multiple series. Always, what was, at one time, the highest profile selected remaining on disk.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

You simply need to modify your quality profile and reorder your quality rankings
