### ISSUE TITLE
Can't connect to Download Station while Radarr is working fine

### ISSUE THREAD

**Issue by vinznsk** [Sonarr/Sonarr#4854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sonarr can't connect to Synology Download Station. 
In activity it shows "All download clients are unavailable due to failures"
and "Unable to communicate with Download Station. Unable to connect to Diskstation, please check your settings"

Error in DS Settings: "Unable to connect to Torrent Download Station"

### Expected Behavior

Radarr connects to the same Download Station without a problem, so I suppose Radarr should be able to do it too.

### Steps To Reproduce

1. Go to Settings
2. Setup DS
3. Test the connection

### Environment

```markdown
- OS: DSM 7.0.1 -42218
- Sonarr: 3.0.6.1342
- Docker Install: 3.0.6.1342-ls131 by linuxserver.io
- Using Reverse Proxy: Yes
- Browser: Chrome Version 97.0.4692.71 (Official Build) (64-bit)
```

### What branch are you running?

Main

### Trace Logs?

I'm sorry, I don't know how to get trace logs on Synology for Sonarr.

Here is the only log I could find: https://disk.yandex.ru/d/N7NOoyEYMRYYGQ
### Anything else?

Nope :)

**Comment by bakerboy448** [comment]
Trace logs and uploaded as required in the wiki.

Not some sketchy download site

https://wiki.servarr.com/sonarr/troubleshooting#logging-and-log-files

**Comment by hr1232** [comment]
A very similar thing is happening to me with SABnzbd since a few updates ago. Radarr and Lidarr can connect fine, while Sonarr is constantly having problems. Log just says "connection timed out" and new NZBs are accumulating in the Activity tab with status "Pending" or "Pending - Download client is unavailable". Althewhile Sonarr is connecting fine to SABnzbd to pick up finished downloads. When I push those NZBs manually via the download-button, they are added to the SABnzbd queue very quickly. qBittorrent is working fine, currently investigating NZBGet.

**Comment by bakerboy448** [comment]
for future reference @vinznsk you need to provide logs....and from a site that does not require downloading...

You've posted just the error spew and posted container logs not even sonarr logs.

> I'm sorry, I don't know how to get trace logs on Synology for Sonarr.

![image](https://user-images.githubusercontent.com/55419169/149598445-13ffafba-88b3-4c39-91c0-a61d31a16e11.png)
What was not clear in the template and the linked wiki? It is 6 simple steps to get and provide logs.
I have no idea how one is unable to see `Log Files` in the GUI in System as explained on the wiki.
I also have no idea - given you're running docker - how you're unable to view your synology's own file system.

with that said
![image](https://user-images.githubusercontent.com/55419169/149598531-6fbf8079-df1d-49c5-befc-a62c33eacee0.png)

Is not at all useful for a bug report and doesn't provide any information other than generic validation errors.
---

>[v3.0.6.1342] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to Diskstation, please check your settings ---> System.Net.WebException: Error: SecureChannelFailure (Authentication failed, see inner exception.): 'https://192.168.100.5:5555/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query&query=SYNO.API.Auth%2CSYNO.DownloadStation2.Task' ---> System.Net.WebException: Error: SecureChannelFailure (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION

**Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.**

This is not a Sonarr bug. You cannot use an self signed certificate HTTPS as it is not valid nor trusted.
An unsigned SSL certificate provides no security benefits and is nothing more than security theater.  There is also little reason to use SSL on your network as it implies your network is not secure and you have other issues to go deal with then.

You either need to not use SSL (and not have Synology redirect to SSL) or disable local address certificate validation.

--- 

@hr1232  Your issue has nothing to do with DownloadStation.  That sounds like your network has issue....Sonarr timing out is not a Sonarr bug. Please do not hijack GitHub Issues for support requests and unrelated issues.  If it's not a network issue than it's a SABnznbd issue.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.
