### ISSUE TITLE
Use Indexer as Release Group

### ISSUE THREAD

**Issue by danimart1991** [Sonarr/Sonarr#4868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Sometimes an Indexer has more than one Release Group, and instead, sometimes the same Indexer doesn't specify which Release Group makes the release. It could be useful if there is an option to use the Indexer name as Release Group.

Other times, the release in the torrent name comes with the Release Group but then, the filename doesn't come with this info or the name is not like Sonarr parser and detects the Release Name incorrectly.

### Describe the solution you'd like

An option in the indexer configuration to make its name the Release Group for all its releases.

### Describe alternatives you've considered

An option in Download Clients or Indexers section to use all indexers name as Release Groups for all Releases.

### Anything else?

Nothing. Sonarr is a great tool with great collaborators 😃

**Comment by markus101** [comment]
No plans to use the indexer as the release group if it cannot be parsed.
