### ISSUE TITLE
Backup options missing under Settings:General

### ISSUE THREAD

**Issue by tfbiii** [Sonarr/Sonarr#4873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

There is no way to change the frequency of automated backups via the current GUI (Version 3.0.6.1342)

### Describe the solution you'd like

Prowlarr and Radarr both have a section under Settings:General that lets you modify the path and the frequency of automatic backups.

I am asking for this to be added to Sonarr as well.

### Describe alternatives you've considered

There are no alternatives I am aware of.

### Anything else?

From Radarr:

![image](https://user-images.githubusercontent.com/22119002/151022224-75827e1f-e139-42fd-94d8-521e57a65ff5.png)

From Prowlarr:

![image](https://user-images.githubusercontent.com/22119002/151022308-36586111-4873-4303-9095-c5907870f881.png)

Thank you!

**Comment by PearsonFlyer** [comment]
They are there, you just don't have Show Advanced clicked in that Sonarr page.

orange = show advanced options only.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

**Comment by tfbiii** [comment]
Ugh, the advanced options. So sorry.
