### ISSUE TITLE
Log shows MediaCoverMapper warning after starting Sonarr

### ISSUE THREAD

**Issue by SmoothAdmin** [Sonarr/Sonarr#4879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The log shows MediaCoverMapper (File C:\ProgramData\NzbDrone\MediaCover\150\poster.jpg not found)

not sure if this normal or not and thought I would pass it a long. 

### Expected Behavior

no idea.

### Environment

```markdown
- OS: Winodws 2019 Server Standard Edition
- Sonarr: 2.0.0.5344
- Docker Install: none
- Using Reverse Proxy: (is that FlareSolverr?)
- Browser: MS Edge
```

### What branch are you running?

Main

### Trace Logs?

none

### Anything else?

none

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

Sonarr v2 is end of life and not supported upgrade to Sonarr v3

Missing Mediacovers are not a bug
