### ISSUE TITLE
User defined installation target folder

### ISSUE THREAD

**Issue by FaceCrap** [Sonarr/Sonarr#4890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not related to a problem, just a feature request to have the installer be able to allow users to specify a target folder of their choosing.

### Describe the solution you'd like

I would like the installer to allow selecting a different installation folder. 

### Describe alternatives you've considered

I'm fairly confident/experienced enough to do a manual installation by using the zip file instead of the installer, but I am very much aware that this doesn't apply to the ordinary user. I also am reasonably sure I'm not the only one that likes to keep his/her bootdrive solely dedicated to the OS.

### Anything else?

Nope, that's it.

**Comment by markus101** [comment]
We do not have plans to make the installation target part of the setup process, for advanced users, the option to install via zip is available, but Sonarr will continue to put it's application data in on the OS drive in `ProgramData` unless another location is provided, again for advanced users.
