### ISSUE TITLE
Requesting support for S3 object storage

### ISSUE THREAD

**Issue by ofersadan85** [Sonarr/Sonarr#4891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I'm storing my media on S3 object storage buckets, which is currently the cheapest and most common solution (in cloud computing) for storage. Since Sonarr only supports direct file system storage, it can be a real hassle to setup properly. 

### Describe the solution you'd like

I'd love for there to be direct support for S3. Instead of setting up "root folders" for media, we should be able to set up root folders as S3 buckets, providing just the proper settings (links and credentials)

### Describe alternatives you've considered

Personally I have a working solution, by using Sonarr as a docker container with a mapped volume, that volume is mapped on the host via Rclone mount to my S3 bucket. It's a real pain to set up properly, and it can still fail (for example, if rclone loses connection, or if files need to be renamed - which isn't directly supported on S3 without proper configuration).

### Anything else?

S3 is a very common storage solution these days, and is supported on all major platforms. It's very well documented and easy to work with as developers, while also being quite cheap for users as long-term storage. 

While we're on the subject, this can even be extended to support other storage solutions! For example: integration with Google Drive or Microsoft's OneDrive. Maybe even Nextcloud and other similar options. 

I'm imagining something like the following example under Settings -> Media Management:
: 
<img width="284" alt="s3" src="https://user-images.githubusercontent.com/18385610/153200214-136c2938-204d-44a5-ba7a-0533a6b48146.png">

Note - I've opened a related feature request here: https://github.com/Radarr/Radarr/issues/7020

**Comment by bakerboy448** [comment]
No plans for this

Use rclone to mount remote storage
