### ISSUE TITLE
Ability to force a default quality to specific Release group names (Megusta)

### ISSUE THREAD

**Issue by danesanford** [Sonarr/Sonarr#4893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently, users may wish to download releases from the release group named "Megusta"... The problem I have encountered is that this group does not put a 'quality' description in the filename of their releases. 

(I realize this is THEIR problem and not a problem with Sonarrs configuration, parsing or importing of files. )

### Describe the solution you'd like

I propose the option be added to the GUI (perhaps in the Settings/Profiles area?) to attach a specific quality profile (eg. WEB-DL or HDTV) to specific release groups names?

eg. -> (under a NEW heading) "Release Profiles (Forced)"
Megusta = WEB-DL

This will, of course treat ALL Megusta releases as WEB-DLs... But the user could have the option to force an associated quality profile when the group rarely includes this info!?

I know this may be viewed as an added feature that could unintentionally defeat the regular quality parsing the Sonarr has done perfectly (for me), but it may be the only way to fix this type of problem because quality profiles are a BIG feature that Sonarr uses to decide whether to upgrade a file, or not. I don't think this feature "Release Profiles (Forced)" would break anything and you offer a solution to these kinds of problems! :D

### Describe alternatives you've considered

I would add the word "Megusta|" right after "WEBDL|" in source code file: src/NzbDrone.Core/Parser/QualityParser.cs 
https://github.com/Sonarr/Sonarr/blob/36395decc7316d5b6bcbf949640975265629ed9a/src/NzbDrone.Core/Parser/QualityParser.cs#L19

BUT! How I'm using Sonarr is through a docker (specifically "mdhiggins/sonarr-sma" docker

### Anything else?

no

**Comment by markus101** [comment]
We do not have plans to treat non-quality information, such as a release group as quality.

In this scenario your best best is to group all qualities of the same resolution into the same group then rely on preferred words to upgrade to Megusta/WEB-DL.

**Comment by danesanford** [comment]
![quality profiles](https://user-images.githubusercontent.com/61180029/153316377-126c0b77-0ea5-407e-b3b1-c629f072a388.jpg)

how can I accomplish this? (confused)
***I would still like Sonarr to upgrade episodes as it does perfectly, I would just like the end result to be that all Megusta releases are treated (recognized) as WEB-DL, since the do NOT usually have a quality profile in the filenames?

**Comment by markus101** [comment]
You need to group the qualities, but if you have questions on that, use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) to ask that.

You're not going to get Megusta treated as WEB-DL because they fail to add it, but it will treat HDTV and WEB-DL equally so you can override that with preferred words (as well as prefer WEB-DL over HDTV for non-Megusta releases).
