### ISSUE TITLE
Clicking outside Interactive Search modal should close it

### ISSUE THREAD

**Issue by SonGokussj4** [Sonarr/Sonarr#4895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

It's not consistent with the behavior of other modals.

### Describe the solution you'd like

When I open Interative Search from the series page and click outside of the modal window, it won't close.

If I click on episode name, modal opens, I click outside, it closes so I hope that's the correct behavior. I'm missing this in Interactive Search modal.

### Describe alternatives you've considered

There is none

### Anything else?

There is not

**Comment by bakerboy448** [comment]
https://github.com/Sonarr/Sonarr/commit/37e1c4f2eb3f8dbe1ac21a7824dbc2a714f10c6c

This is intentional and to avoid users spamming their indexers with queries if they accidentally click or touch (if touch screen) outside the modal.

no plans to revert

**Comment by thezoggy** [comment]
may not help you, but you can hit ESC on the keyboard if you want to close it.

**Comment by SonGokussj4** [comment]
Did not know that. Thanks. I can connect that to a mouse macro :-)
