### ISSUE TITLE
Calendar feed ignores API key

### ISSUE THREAD

**Issue by scott-hpe** [Sonarr/Sonarr#4896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Calendar -> iCal Link button generates a URL for subscribing to the calendar feed that includes an API key. This URL looks like https://mysonar.home.com/sonarr/feed/calendar/Sonarr.ics?apikey=xxxxxxxxxxxxxxxxxxxxx

The API key is ignored during the request to /feed however. You can change the apices value or remove the param from the URL and the calendar is still returned.

### Expected Behavior

Expect the ical calendar feed to only be returned when using a valid API key

### Steps To Reproduce

1. Be on version 3.0.6.1342
2. Click *Calendar* then *iCal Link* button in the toolbar
3. Copy the shown calendar feed link and remove the *?apikey=xxxxxxx* portion
4. Use `curl` or `wget` to retrieve the calendar feed without the API key. 

### Environment

```markdown
- OS: Linux
- Sonarr: 3.0.6.1342
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: curl, wget, firefox, MacOS Calendar App
```

### What branch are you running?

Main

### Trace Logs?

N/A

### Anything else?

N/A

**Comment by Taloth** [comment]
That's partially correct. You probably do not have authentication enabled. The feed is accessible either via apikey or authentication.

**Comment by scott-hpe** [comment]
That's correct, I do not have authentication enabled.

I see other APIs do require an APIKEY, for example, /api/calendar requires an APIKEY. Looking at the [docs](https://github.com/Sonarr/Sonarr/wiki/API#authentication), it seems like APIKEY is needed for (all?) APIs even if authentication is disabled.

Even with Authentication disabled, when getting the iCal Link, the APIKEY is shown giving a false sense of security that the calendar is only available when the APIKEY is passed.

And though I hate to make this comparison, with authentication disabled in Radarr, the /feed/calendar API is protected by APIKEY.

**Comment by scott-hpe** [comment]
Quick proposed change to require APIKEY for /feed/calendar

**Comment by Taloth** [comment]
> What is the consensus on enforcing the apikey parameter on any feed/calendar request irrespective of the general authentication setting?

The feed url is in /feed not /api exactly for this reason. The /api endpoints are protected exclusively by ApiKey. Most urls other endpoints are either protected by regular authentication or a combination of both.

If you use a reverse proxy, you should take care of it there.
btw It's generally advisable to always have some kind of authentication in Sonarr. We'd probably force it if it wasn't a breaking change.

**Comment by scott-hpe** [comment]
If that's the case should APIKEY be removed from the URL if authors disabled?

**Comment by Taloth** [comment]
you can, but having the apikey in there doesn't hurt. Although you might want to use your own random key in your reverse proxy.

**Comment by jamesmacwhite** [comment]
I tested this quick NGINX config, which can check for the API key being present, the downside is hard coding the API key into a NGINX proxy configuration, but in reality it could actually be anything and not tied to Sonarr.

```
location /sonarr/feed/calendar/Sonarr.ics {
    if ($arg_apikey = <SONNAR_API_KEY>) {
        return 200;
     }

     return 401;
}
```

It needs to be more dynamic to handle the variants of /feed/vs/calendar and the older NzbDrobe,ics but I guess this is the best way with a reverse proxy.

**Comment by Taloth** [comment]
You can do one of two alternatives:
1. Enable authentication in Sonarr and have nginx send the appropriate authentication  header on regular non-api requests.
2. Expose your own .ics endpoint in nginx and have it pull the Sonarr.ics from /feed/. That .ics endpoint can be anything, including a random string to serve as key. Something like `location ~ "/sonarr/feed/calendar/9fjefkfefj39343k4j23h43434/Sonarr.ics"`. After all, it doesn't have to be called 'apikey', it can be any url.

Option 2 means changing the urls in the various devices, option 1 means dealing with it in nginx and live with it.

> I'm not particularly a fan of this though, it is interesting that sister app Radarr changed the behaviour and did enforce the API key on feed requests.

We're not going to change Sonarr's behavior. It's be a breaking change for those that rely purely on auth to access the endpoint.

**Comment by jamesmacwhite** [comment]
Thanks for the alternatives. The above works for my case, because of devices using the existing ical URL out there already with the apikey param on them, I might as well use it for what I originally thought it was doing after all! As you've pointed it out, it could be any URL with any string if required, given it is not tied to Sonarr really.

I could enable basic auth, but as Sonarr lacks what I'd define as user model (and I'm not saying it should) that's why I have third party auth and the reason why it is disabled. Equally I have the 8989 port firewalled so only localhost and the reverse proxy can talk to it directly, even on the LAN authentication goes through Authelia.

Authentication in most cases should be on of course, but these are more special cases with reverse proxy configurations and third party auth providers. It's good to know the behaviour has been clarified though. I have literally thought the feed path requires an API key for years.

I'd hope one day Sonarr will default authentication on, you only have to do a couple of facet searches on a certain website and find over 1,000 Sonarr installations wide open right now. Sad times.

**Comment by Taloth** [comment]
> I could enable basic auth, but as Sonarr lacks what I'd define as user model (and I'm not saying it should) that's why I have third party auth and the reason why it is disabled.

My suggestion was to enable auth in sonarr, and have the reverse proxy provide the auth header when the third-party authentication is validated. That way you can lock down index behind the auth provided by whatever mechanism you like, and expose api & feed normally. Obviously the user&pwd pair in Sonarr has to be sufficiently random.

**Comment by jamesmacwhite** [comment]
@Taloth Ah right. Yes I could pass the Authorization header I guess. There's a few options at least based on the original discussion, so it has been useful!

**Comment by scott-hpe** [comment]
Since this is a breaking change would it be appropriate for the 4.x release?

**Comment by Qstick** [comment]
> I'm not particularly a fan of this though, it is interesting that sister app Radarr changed the behavior and did enforce the API key on feed requests.

Just for color, this may have been lost in our move to ASP native, and not necessarily a design decision on the Radarr side. Either way it's likely already the same in the Sonarr v4 work, so we should decide how we really want this in v4.

**Comment by markus101** [comment]
I think it makes sense to lock it down behind the API key auth. iCal links generated in the UI already include the API Key so the number of disruptions should be small.

**Comment by markus101** [comment]
This is changed in v4, API key authentication is required.
