### ISSUE TITLE
Webhook(Notifications) doesn't support Japanese/Chinese

### ISSUE THREAD

**Issue by susundingkai** [Sonarr/Sonarr#4899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Characters in response body all become '???'. But it displays correctly in other notifications and sonarr's api.
`"series":{"id":27,"title":"Yuki Yuna Is a Hero","path":"/data2/anime/?????????????????????/...",`

### Expected Behavior

When getting grab/import event, the character should display correct code.

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 3.0.6.1457
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

`
2022-02-15 13:31:29.0|Debug|Parser|Parsing string '[璧炲窞涓鍕囪€呴儴'

2022-02-15 13:31:29.0|Debug|Parser|Unable to parse [璧炲窞涓鍕囪€呴儴 

2022-02-15 13:31:29.0|Trace|TrackedDownloadService|No Episode found for download '[璧炲窞涓鍕囪€呴儴'

2022-02-15 13:31:29.0|Debug|Parser|Parsing string '[璧炲窞涓鍕囪€呴儴'

2022-02-15 13:31:29.0|Debug|Parser|Unable to parse [璧炲窞涓鍕囪€呴儴
`

### Anything else?

just like that below:
![image](https://user-images.githubusercontent.com/43811498/154073720-ed0c3f5f-2d8e-4e52-b428-33b01874732e.png)

**Comment by markus101** [comment]
This appears to be a problem on the recipient side, I've tried with both a docker container and on Windows and it's successful:

Docker:
![image](https://user-images.githubusercontent.com/413544/154104920-cef5a358-322d-4417-b653-77ae493b40b3.png)

Windows:
![image](https://user-images.githubusercontent.com/413544/154105075-65ee2222-cd8d-409a-92b1-f1e12ce96cf5.png)

Bonus, Charles Proxy on Windows:
![image](https://user-images.githubusercontent.com/413544/154105215-079c6ac1-e331-45c7-a347-4ba853b54962.png)

**Comment by susundingkai** [comment]
thanks for your reply :). I tested it in windows11 and worked fine, maybe something wrong with Ubuntu environment?

**Comment by susundingkai** [comment]
@markus101 
> This appears to be a problem on the recipient side, I've tried with both a docker container and on Windows and it's successful

I've tried it many times and compiled sonarr by myself but all failed on Linux and sucessed on Windows.  It's so confusing. Can you tell me the tool name you used to receive the events?

**Comment by markus101** [comment]
I used https://requestbin.com/

**Comment by susundingkai** [comment]
@markus101 Thanks!!! I finally solved it by upgrading my endpoint to https, though i dont know why.
