### ISSUE TITLE
Calendar - add option to show episode filename or release group, similar to "Show episode title and number"

### ISSUE THREAD

**Issue by enchained** [Sonarr/Sonarr#4903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

As far as I know, currently we can only see cutoff indication in the Calendar as a quality, and not as a release group/preferred word etc. And even if it was possible, it could be really cumbersome to maintain with multiple release profiles. 

Currently, to review recent downloads, I often open Calendar to check downloaded episode release groups one by one, by clicking just to see the filename in the popup. This way I can check whether the most preferred release group was already reached to unmonitor it, or if the quality profiles or global preferred words caused an upgrade to a new release group that I need to rank or add to ignore in some cases. This process takes a while, and I may have to check some episodes by clicking again and again over time.

### Describe the solution you'd like

There's already an option to visually indicate whether the quality cutoff was met in the Calendar. For those who are also concerned about release groups, it could be useful to have a similar way to see a filename (or at least a release group) at glance in the Calendar cells instead. This way you can quickly unmonitor only those episodes where the most preferred release group was finally reached after some preferred words upgrades happened, or to upgrade manually if some new random poor quality release was downloaded (happens often with Anime).

If there would be such an option to display, a quick button to toggle monitor state right inside the cell would also be immensely useful addition.

### Describe alternatives you've considered

I suppose, since I have different release priority for different shows in mind, I could just create a new release profile for every show, but it is way more complex to maintain this way. An option to tie a release profile to a series type (standard, daily, anime) or to a root folder would surely make things easier, but to maintain a release priority (preferred words) up to date, I still return to the need to check up on Calendar, so that if any new release group appears, after testing it I can rank it or add to Must not contain restrictions. So things always come back to improving the effectiveness of processing newly downloaded releases in the Calendar.

As a visual implementation alternative, to not stretch the calendar cells even more, filename/release group could be displayed as a hint on hover over the episode cell, but this solution will only work with desktop browsers, and for the touchscreen sake would require some icon to intercept the click event and show the tooltip like the one in the Queue.

### Anything else?

-

**Comment by markus101** [comment]
We do not have plans to include file information or a toggle for monitored status directly on the calendar item.
