### ISSUE TITLE
Missing Episode Searches should take a break for higher priority tasks in between them

### ISSUE THREAD

**Issue by Relki** [Sonarr/Sonarr#4907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When I add several lists from Trakt, and tell them to start a search when items from the lists are added to Sonarr, the problem I'm having is that this has kicked off literally hundreds of requests for Missing Episode Search tasks. This isn't really a problem, except, the download client is downloading to an 8TB temporary storage location, and the final location the files get moved to for Sonar is an 140TB partition. Sonarr, when you queue up hundreds of Missing Episode Searches, doesn't take a break to check finished downloads and start moving them. Because of this, Sonarr will sit for literally days while hundreds of items are backing up in the Download client that are finished and are not being moved to the new location. Now the download client is running out of space because nothing is being moved until ALL the episode search tasks complete.

### Describe the solution you'd like

I feel like the "Refresh Monitored Downloads task", should run like clock work as soon as it's able to, in between all other tasks, regardless if other tasks are before it. This will prevent the download client from backing up with tons of completed downloads that are not being moved since there are hundreds of queued "Missing Episode Search" tasks ahead of it.

There is no functionality to cancel Missing Episode Searches except one at a time which isn't feasible. So, please make "Refresh Monitored Downloads" task higher priority than searching tasks so things actually get moved. Seems silly to not moving anything for days because there are a lot of Missing Episode Search tasks ahead of it. Let's keep this engine moving along.

### Describe alternatives you've considered

Alternative would be to not accidentally check "search on add" when adding a new list. But I really want to search on add. I just also don't want my Sonarr seized up for days and not move any downloads that have been finished for hours/days, filling up my temp download drive.

### Anything else?

![Capture](https://user-images.githubusercontent.com/45949455/154825389-b8933e23-9e05-4115-86f1-347604cf3bdd.PNG)

**Comment by thezoggy** [comment]
What's the specs of the machine you are running and how many series?

**Comment by bakerboy448** [comment]
> There is no functionality to cancel Missing Episode Searches except one at a time which isn't feasible.

This is incorrect.

Restart sonarr

**Comment by Relki** [comment]
Thanks for the reply. I've restarted sonarr and it jumps back into the task list, with refreshing downloads still 400 tasks down so doesn't help.

The only way I can get the search episode tasks to complete without canceling each one individually is to disable all the indexer. Then all the search tasks start completely quickly.

Sincerely,
Craig Garcia
________________________________

**Comment by Relki** [comment]
It's running on a 32 core dual xeon server with 300+GB of ram. The downloads folder is a 8TB (600GB 10k sas x 18~ drives raid) destination folder is 16TB sata enterprise x 10 drives raid.


Sincerely,
Craig Garcia
________________________________

**Comment by Relki** [comment]
I have 2500 series. Not sure how many it was actively trying to search for after I added a couple of trakt lists. It should still take breaks between search for episodes to process what's already been downloaded. This searching could go on for a few days before it decided to process any downloads.


Sincerely,
Craig Garcia
________________________________

**Comment by ZerithZA** [comment]
Hi, I'm still getting the same behaviour as described above.

![image](https://user-images.githubusercontent.com/10301711/155049823-19db69c5-a0db-4556-9ac0-491acf20702d.png)

![image](https://user-images.githubusercontent.com/10301711/155049867-c951b410-927f-47b1-81c7-dc75b80e8218.png)

**Comment by markus101** [comment]
The priority is set when the task is queued, Refresh/Process Monitored Downloads will now be queued at high priority, but any existing tasks would still be set at low priority, it'll need to be removed from the DB so Sonarr can requeue it.

1. Stop Sonarr
2. Open Sqlite DB
3. Run commands below:

```
DELETE FROM Commands WHERE Name = 'ProcessMonitoredDownloads';
DELETE FROM Commands WHERE Name = 'RefreshMonitoredDownloads';
```

4. Start Sonarr

**Comment by ZerithZA** [comment]
I only did the scheduling of the searches after I did the update to test if it works. Did as you described above to make sure but still same issue.

![image](https://user-images.githubusercontent.com/10301711/155051443-3b37546b-eba8-4abe-8995-ef8dca3d1347.png)

![image](https://user-images.githubusercontent.com/10301711/155051511-c887e81f-24f3-4b20-94f2-4247eeb72f3f.png)

![image](https://user-images.githubusercontent.com/10301711/155051476-3bdc2806-c7a8-490b-b5ae-9c6d99b41cd3.png)

**Comment by markus101** [comment]
Ahh, I was looking at your old screenshot. Pushed a fix for the priority being wrong for the refresh task and sorted the command queue in the API response.

**Comment by ZerithZA** [comment]
Working much better now. Was wondering can we include the same priority to Manual Imports? They can also sit in queue for long time until all searches are processed.
