### ISSUE TITLE
Typo in log line

### ISSUE THREAD

**Issue by jonoff** [Sonarr/Sonarr#4908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

RecycleBinProvider doesn't proper pass the variable to the format variable, instead using the literal string "[0]" on line https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/MediaFiles/RecycleBinProvider.cs#L98

### Expected Behavior

destinationFolder is passed as a variable as intended.

### Environment

```markdown
see code
```

### What branch are you running?

Main

**Comment by markus101** [comment]
No need to paste the same snippet of code multiple times.

**Comment by jonoff** [comment]
Removed extras, I think the fields were required.
