### ISSUE TITLE
Ability to resize posters other than the pre-defined sizes

### ISSUE THREAD

**Issue by gniting** [Sonarr/Sonarr#4909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not related to a problem

### Describe the solution you'd like

The ability to resize the posters using a slider vs the existing 3 pre-defined sizes. For example, I'd like the posters to be smaller than the current "small" size so that I don't have to scroll on my tiny laptop screen when viewing library.

### Describe alternatives you've considered

I used to use Medusa before switching to Sonarr and it had this feature.

### Anything else?

https://i.imgur.com/zUmr6lt.png

**Comment by markus101** [comment]
> Not related to a problem

You explain the problem as part of your solution, but we need more information.
How small is your "tiny" laptop screen (the resolution)?
How many total series are you trying to display without scrolling?

> The ability to resize the posters using a slider vs the existing 3 pre-defined sizes.

A slider still has points within it that translate to different poster sizes, maybe a slider is a better solution to this problem, but as of right now we lack the information needed to make that decision.

Poster sizes are based on the number of posters that can be displayed at the available width, currently each smaller size results in an additional poster being displayed per row.

**Comment by thezoggy** [comment]
That slider is just changing the css width for the poster, the actual image source doesn't change. While giving the user the ability to arbitrary set a width makes sense when you develop for no fixed size but goes against sonarr ui which is designed for specific resolutions and does breakpoints to serve up optimal sizes for those sizes.

**Comment by gniting** [comment]
Laptop screen is 1280x800, which is not that tiny but still, with 75 tracked shows, it requires scrolling. I know that there's no way to display all 75 shows without scrolling. 

It's just a personal preference to have smaller poster sizes. Feels restrictive if I, as the user, can determine what size I want the posters to be.

**Comment by markus101** [comment]
This isn't something we have plans for currently, labeled it for future reconsideration.
