### ISSUE TITLE
Authorized API request generates Auth-Unauthorized log entry for favicon.ico

### ISSUE THREAD

**Issue by stephanrenggli** [Sonarr/Sonarr#4910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When issuing an authorized API request, sonarr will write an Auth: Auth-Unauthorized log message for favicon.ico.

This creates unnecessary noise in the log.

**Context:**
This came up while setting up Uptime Kuma for checking if Sonarr is up. At first I pointed Uptime Kuma to `https://sonarr.mydomain.com/` which will generate an Auth-Unauthorized log entry as well because Uptime Kuma is not logged in and as such the request will redirect to `https://sonarr.mydomain.com/login?returnUrl=/`.
I then switched to the API request detailed below and noticed Sonarr will still generate the log entry, this time for `/favicon.ico`.

### Expected Behavior

Sonarr should not generate an Auth-Unauthorized log entry for an authorized request.

### Steps To Reproduce

1. Make request to `https://sonarr.mydomain.com/api/system/status?apikey=<myapikey>`
2. Check Sonarr Log Messages
3. Sonarr will write the following log entry `[Info] Auth: Auth-Unauthorized ip <myip> url 'http://sonarr.mydomain.com`

**Note:** Same behavior when using the new `/api/v3` endpoint `https://sonarr.mydomain.com/api/v3/system/status?apikey=<myapikey>`

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 3.0.6.1467
- Docker Install: Yes (linuxserver image)
- Using Reverse Proxy: Yes
- Browser: Chrome 98
```

### What branch are you running?

Develop

### Trace Logs?

`[Info] Auth: Auth-Unauthorized ip <myip> url 'http://sonarr.mydomain.com/favicon.ico`

### Anything else?

Even though the API request is made using https, the log message will show http. This is probably because TLS terminates at the reverse proxy and reverse proxy <-> sonarr is http but I'm not sure, maybe this is part of the issue?

**Comment by markus101** [comment]
The favicon.ico request should not require authentication, that will be addressed. As for the actual request, something is making a request for the favicon, API responses themselves will not trigger that, perhaps the reverse proxy is doing something there or Uptime Kuma is, I'm curious, but it's not an issue with Sonarr.

**Comment by stephanrenggli** [comment]
I must have mixed up things while testing. With the API request Uptime Kuma does not request the favicon.
