### ISSUE TITLE
current 3.6-develop version of sabnzbd is assumed to be 1.1.0 and can't test successfully

### ISSUE THREAD

**Issue by jobe08** [Sonarr/Sonarr#4911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sonarr does not work with sabnzbd develop. When testing a connection to current sabnzb develop the following is shown:
```
Test was aborted due to an error: Cannot combine OsPaths of different platforms ('' + 'downloads/complete')
Sabnzbd develop version, assuming version 1.1.0 or higher.
```

the logs show ``

### Expected Behavior

Sonarr should assume sabnzbd develop to be at least version 2.0 and be able to connect to it

### Steps To Reproduce

* run sabnzbd develop
* configure it
* test the connection

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 3.0.6.1342
- Docker Install: No, using Snap
- Using Reverse Proxy: yes
```

### What branch are you running?

Main

### Trace Logs?

https://www.toptal.com/developers/hastebin/xuwidodinu.yaml

### Anything else?

The reason seems to be that Sonarr maps "develop" to version 1.1.0: https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs#L338-L346

The code has a version gate of 2.0 to retrieve the correct paths for completed downloads
https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs#L219-L230

Since 1.1.0 is less than 2.0 sonarr expects the download folder configuration at the wrong place.

**Comment by thezoggy** [comment]
that code bit was back form 2017, as sab 2.x and older is defunct in various ways.. safe to assume anyone using sab develop is 3.x
