### ISSUE TITLE
Mark rejected releases with orange if only "equal or higher preference"

### ISSUE THREAD

**Issue by joachimtingvold** [Sonarr/Sonarr#4915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When doing interactive search to find a better/more suitable release, it's hard to differentiate between the rejection status. Regardless if they have one or more "rejections", and what type of rejection they are, they are displayed equally

### Describe the solution you'd like

Releases with rejection that is **ONLY** _Release in queue is of equal or higher preference_ **OR** _Existing file on disk is of equal or higher preference_ should be marked with an orange exclamation mark (rather than red). All releases with additional rejections (such as _Contains these ignored terms_, _Release is blocklisted_, etc) will be marked as before.

This way it's easy to find/pick releases within the same quality category (which is the usual scenario when doing this).

![orange-rejection](https://user-images.githubusercontent.com/359918/155397527-7bcfd38d-7848-4bbf-a5fa-2b8c95624c77.jpg)

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by markus101** [comment]
We do not have plans to change the colour of the rejection icon based on the possible rejections.

**Comment by joachimtingvold** [comment]
Maybe the issue can be rephrased. It does not need to be different color, but at least some way to easily identify only those episodes that are rejected due to "equal quality". Currently the only "custom filter" related is "rejection count", but that does not take into account what type of rejection it is.

Point being, it would be nice to be able to easily spot only those episodes that are rejected due to "equal quality" (which is **way** less severe than ignored search term, blocklisted, etc).

**Comment by joachimtingvold** [comment]
Usecase is if you want to (manually) find a specific release when doing interactive search (replace HDR with non-HDR, replace DV with non-DV, etc).

**Comment by markus101** [comment]
Differentiating those particular releases would work for your use case, but filtering would be much more agnostic. At the moment we don't have short term plans for filtering based on rejection reason, but it's something we've been discussing and there are previous issues on that subject https://github.com/Sonarr/Sonarr/issues/4132

**Comment by joachimtingvold** [comment]
Maybe adding "Rejection description" as a custom filter, where you can add the usual textual "contains/does not contain/equal/not equal". That would at least be more than sufficient for my use case, and you wouldn't need to "categorize" the rejections, or worry about any new or changed rejections in the future.
