### ISSUE TITLE
Evaluate release profiles regardless of existing quality when searching

### ISSUE THREAD

**Issue by joachimtingvold** [Sonarr/Sonarr#4916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Had problems with Dolby Vision releases not being able to be played. Created release profile to ignore such releases. Had to manually go through all previously downloaded DV-episodes to re-download again. Since DV and non-DV release would be of the same quality, a search would not take into account the new release profile.

### Describe the solution you'd like

When searching for releases, it should take release profiles into account, even if there are no upgrades available. Let's say the quality profile has 2160p WEB-DL as the highest quality. Prior to adding any release profiles, it downloaded an episode as 2160p WEB-DL with Dolby Vision. You then add a new release profile saying to ignore releases containing DV related tags. At this point, a non-DV episode would still be 2160p WEB-DL, and thus, a new search will not consider any new episodes as a replacement (since they are of equal quality), even if the existing episode technically is invalid with the new release profile.

I'd like for release profiles to be taken into account when searching, regardless of the current downloaded episode/version. If not automatically/at all times, at least as a manually triggered search, where you can see/approve the result before executing.

### Describe alternatives you've considered

The current manual workarounds (that I know of), consists of the following;
* Manually find the affected episodes and set it's quality to something lower (i.e. WEBRip if it used to be WEB-DL, etc). Then trigger a search to "upgrade" the episodes.
* Add the relatively new `mediainfo.videodynamicrangetype` episode format, and then search on the filesystem for files matching the DV tag. Delete those files, and trigger a scan to re-download episodes.
* Manual interactive search for each episode you want to replace.

All of which are cumbersome and time-consuming.

### Anything else?

N/A

**Comment by markus101** [comment]
Preferred words is the only aspect of release profiles that will apply to upgrades, in addition to adding DV to must not contain you can also add a negative preferred word score to DV is the same profile; you'd still need to search for episodes to replace immediately or wait for new releases to be posted.

No plans to change how must contain/must not contain function with the presence of an existing file.

**Comment by joachimtingvold** [comment]
So you're saying that a release profile with a negative preferred word score would cause an existing downloaded episode to be replaced with a new, even if they are of the same quality? I.e. it will override the quality aspect of a search? (existing 2160p WEB-DL release with a negative preferred word score, would be replaced by a new 2160p WEB-DL having a neutral preferred word score).

**Comment by markus101** [comment]
Yes, that's how preferred words work, doesn't matter if it's going from -1 to 0 or 0 to 100, it's an upgrade.

**Comment by joachimtingvold** [comment]
I just tried, but does not seem to work? 6 of 6 episodes of Hawkeye were DV. Added release profile having `.DV.` and `.DoVi.` as ignored word and negative preferred word score with a `-10` as score. Doing an interactive search, I can see that the releases matching those criterias are further down the list (with `-10` in the "Preffered word score" column). Doing a "search for monitored episodes in this season" does not result in any downloads/upgrades.

I can file that as a separate bug issue, if you'd like?

**Comment by markus101** [comment]
Either the filename or the "scene name" (original file name/release name) will need to contain one of those terms so the upgrade can be calculated.

I just tested this with the following setup:

Profile (`amzn` has a -10 score, `not-amzn` tag is applied):
![image](https://user-images.githubusercontent.com/413544/155424406-fafd4204-c0d6-489f-b1a8-e9270f1295fc.png)

Quality Profile (upgrades not allowed):
![image](https://user-images.githubusercontent.com/413544/155424648-5a755d90-be8c-4b68-939b-e0888aa3672c.png)

Tag On Series:
![image](https://user-images.githubusercontent.com/413544/155424357-fc4ea146-d831-48af-bc24-fc07f51077dc.png)

Existing File:
![image](https://user-images.githubusercontent.com/413544/155424292-480c1dd6-d94b-4fa8-8453-023987db133f.png)

Interactive Search:
![image](https://user-images.githubusercontent.com/413544/155424579-c1c38fb4-a15d-4033-b632-5e78471791bd.png)

The Two non-amzn releases are properly pushed above the `amzn` releases and are not rejected.

If you're still having issues, please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) to troubleshoot further.

**Comment by Alanoll** [comment]
Just dropping a note, I think I experienced this too and just haven't dug in to the why.
The Automatic search was terminating early according to the logs because it was already at quality level, but when doing a manual search there were releases that should have been pulled.

@markus101 in your example above, the issue would have only occurred when performing an automatic search, not the interactive. I don't see a mention of you performing an auto search in your steps, where as the op did (and mentions the interactive appeared to have calculated everything correctly.

Next time I see it happen, I'll try to reproduce and debug, just haven't had time.

**Comment by joachimtingvold** [comment]
We have found the issue. Me and @markus101 discussed this further on Discord, and forgot to update this issue.

It's caused by the original filename (pre-import) being considered as a valid "on disk" file when comparing potential upgrades. In many cases this will be an obfuscated filename (like `1SWeETNijv6vi4RDh6gZvHqgttNXtEy6CO.mkv`), and thus not evaluate the same way towards the release profiles. In the scenario where you're looking to ignore DV-releases (via word boundary regex like `\b(DV|DoVi)\b`), that will not match the obfuscated filename, which is then given a netrual preferred word score of zero, which is equal to the available releases, thus no files are marked as a valid upgrade.

Tracelog showing this: https://gist.github.com/joachimtingvold/96545c800ad97ca844f159e5c735c7ed
Dump of episode from DB: https://gist.github.com/joachimtingvold/072ba6d97bbacfc6a4570cf5354bbf4c

**Comment by joachimtingvold** [comment]
@markus101, I've updated the original post + title. Maybe we can re-open this until fix is commited?

**Comment by joachimtingvold** [comment]
Also, I notice a few other things;
- It's comparing score twice for the same name (`Hawkeye.2021.S01E01.Never.Meet.Your.Heroes.2160p.WEB-DL.DDP5.1.Atmos.DV.HEVC-TEPES`). Why?
- If the current filename on disk for some reason does NOT contain whatever you're trying to match, it will also fail to upgrade (since the filename will get a netrual score, same as the pre-import filename now). The filename on disk is rarely 1:1 to the release name, and release profiles are usually written to match on release names (and not filenames). In other words; it's not just enough to "ignore" the pre-import filename -- it must also ignore the current on disk filename (at least when it's given neutral score).

**Comment by markus101** [comment]
It's already fixed: https://github.com/Sonarr/Sonarr/commit/acdf02d5692e18df60031647d728f02c7474ae77

1. There are several things related to the file it checks, scene name (usually the file/folder name if it's not a hashed name), the file name from the original import (which is where the hashed name would come from, usually) and either the episode's relative or full path, depending what is available).
2. Yes, anything with matches for preferred words will win over something that does not. A 0 without no matches is just ignored (doesn't matter which source it comes from), a zero that was from a -10 and a +10 match would be treated as a zero

**Comment by joachimtingvold** [comment]
Ah, look at that. Nice! Can confirm that it works for the episodes I've tested on thus far. Thanks!

Trace logs from the release picked as upgrade, showing the word scoring (which previously yielded "same or equal quality"): https://gist.github.com/joachimtingvold/29ecd22d0dc5d1dd0950cf43edd3a124
