### ISSUE TITLE
Reduce query load on providers / Sync less often

### ISSUE THREAD

**Issue by peabnuts123** [Sonarr/Sonarr#4918]
### Is there an existing issue for this?

- [X] I have searched the existing issues. There are many.

### Is your feature request related to a problem? Please describe

I have several Usenet providers that have only a small daily limit of # queries allowed to their API. I believe that because Sonarr hits them for watched shows so often (every 15 minutes as far as I can tell?), I am often exhausting the number of queries I can make to these indexers/providers. For example several of these are Usenet indexers that I am trialling for quality before I subscribe and will have as few as 100 requests per day - most / all of which is being consumed by Sonarr (presumably also, Radarr etc. will do the same). 

### Describe the solution you'd like

I understand this has been asked over and over on here and usually that comes down to "why is this a problem" - well I'm here to say - the inability to change the interval at which watched shows are checked-for is causing me a problem. 

Solutions as far as I know would include:
  * Change the interval at which Usenet is queried
  * Disable certain indexers for scheduled querying / only use for initiating a search manually
  * Disable watching / remove all my watches
  
I have no need for Sonarr to check for watched shows every 15m or so - once a day would be more than enough. I understand that this feature request will likely be denied (as it has over and over again). But perhaps a solution to my actual problem exists? 

### Describe alternatives you've considered

As descibed above. As far as I can tell, the only alternative I have right now is to disable watching, or remove the indexer from Sonarr and evaluate it manually. 

### Anything else?

n/a

**Comment by markus101** [comment]
> I understand this has been asked over and over on here and usually that comes down to "why is this a problem" - well I'm here to say - the inability to change the interval at which watched shows are checked-for is causing me a problem.

There is no ability to change the RSS Sync interval, that has existed for years. Sonarr does not allow setting the RSS Sync interval on a per indexer basis, which has been asked for, but wouldn't work with how Sonarr is designed and would exist solely to rely on free indexers with a low daily cap, something we're not going to optimize for.

The FAQ has an entry specifically for how Sonarr finds episodes https://wiki.servarr.com/sonarr/faq#how-does-sonarr-find-episodes it'd be worth reading through that and additional entries to get a better understanding of some of the general functionality of Sonarr.

> Change the interval at which Usenet is queried

You can already change the interval for RSS Sync (how Sonarr checks for new releases). Settings: Indexers (it's an advanced option). Longer intervals means Sonarr will have to try and page back to avoid missing releases, which will use more than one API call, but possibly less than the 96 Sonarr requires. This is an advanced global setting, which applies to all indexers.
![image](https://user-images.githubusercontent.com/413544/155627909-64f03981-ba48-49cc-af57-0cf051681758.png)

> Disable certain indexers for scheduled querying / only use for initiating a search manually

This option also already exists, edit an indexer and you have 3 options. This is a per indexer setting.
![image](https://user-images.githubusercontent.com/413544/155627882-9a2f099f-694a-4927-947d-36fd7f21cb26.png)

> Disable watching / remove all my watches

Unmonitoring all shows wouldn't stop RSS sync from functioning (assuming that's what you mean by "watches"). But you can disable all RSS Syncing with the same interval setting as above, set it to 0 and it will never sync automatically.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for any additional questions on this or other topics.

**Comment by thezoggy** [comment]
change the setting:
settings > indexer > RSS Sync Interval
