### ISSUE TITLE
Issues Box

### ISSUE THREAD

**Issue by martinkeat** [Sonarr/Sonarr#4919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

It's more of an annoyance than an issue.

Where the Sonarr Queue is concerned, the number next to the "queue" button in the menu on the left turns yellow when there is an issue with a download. However, if you have a lot of items in the queue, you then have to go through all the pages to find the download with the issue. 

### Describe the solution you'd like

A box at the top of the Queue page which is headed "Issues". When a download has an issue (which warrants the number next to the "queue" menu option turning yellow) the download would be moved from the standard queue into the "issues" box at the top of the queue page so it is fully visible right at the top of the page.

The download would continue to act in the same way it normally would, but the move from the standard queue into the issues box would simply increase its visibility and stop the user from having to go and search for the offending download. 

### Describe alternatives you've considered

Nothing else to consider, really. 

### Anything else?

Nope

**Comment by markus101** [comment]
No plans to separate the queue into different sections. Currently you can sort by the status column in order to push those to the top/bottom of the queue) and filtering to only show warnings is covered by https://github.com/Sonarr/Sonarr/issues/2974
