### ISSUE TITLE
Add TVDb Episode ID to API responses

### ISSUE THREAD

**Issue by CollinHeist** [Sonarr/Sonarr#4921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

https://github.com/Sonarr/Sonarr/issues/3062 is related, and the response given was the ID was removed because it was "unstable," and using season and episode numbering was sufficient. However the TVDb ID's should be stable for old releases (which are the primary problem), and series numbering is insufficient for a lot of specials (repeated below)

### Is your feature request related to a problem? Please describe

TMDb allows for finding entries by external database ID (such as TVDb), this is extremely useful for the user to map TVDb episodes to TMDb episodes.

Without this information, matching the two has to be done by title (which don't always match), or season and episode number (which are frequently wrong for Specials, and DVD/aired ordering). This is even worse for long-running Anime because TMDb indexes absolute episode numbers completely differently than TVDb, making matching difficult.

### Describe the solution you'd like

I believe Sonarr already 'knows' the TVDb episode ID, and it is still listed in the API wiki [here](https://github.com/Sonarr/Sonarr/wiki/Episode). Adding this value could be added to API returns would be very useful.

### Describe alternatives you've considered

Existing alternatives are:
- Pay for a TVDb API subscription, query for the episode ID, and *then* match to other databases using that ID. Obviously not ideal since it is cost-prohibitive for many
- Don't utilize the ID matching available in TMDb, instead query by season and episode number and "deal with" the mismatches this creates manually (somehow)

### Anything else?

- TMDb API docs: https://developers.themoviedb.org/3/find/find-by-id
- Sonarr API /episode docs: https://github.com/Sonarr/Sonarr/wiki/Episode

**Comment by markus101** [comment]
> Add TVDb Episode ID to API requests

Do you mean API responses?

> TMDb allows for finding entries by external database ID (such as TVDb), this is extremely useful for the user to map TVDb episodes to TMDb episodes.

Okay, but what's the actual use case for using this with Sonarr? Sonarr doesn't exist for bypassing TheTVDB's API subscription and the IDs already exist on thedvdb.com in the URL.

> I believe Sonarr already 'knows' the TVDb episode ID, and it is still listed in the API wiki [here](https://github.com/Sonarr/Sonarr/wiki/Episode).

Those are API docs from v2 and predate it's removal in 2013 (which was mentioned in the issue you linked).

**Comment by CollinHeist** [comment]
> Do you mean API responses?

Yes I do, thank you - updated.

> Okay, but what's the actual use case for using this with Sonarr? Sonarr doesn't exist for bypassing TheTVDB's API subscription and the IDs already exist on thedvdb.com in the URL.

The use case here is pretty much any project that wants to associate the user's instance of Sonarr (and their associated files) with TMDb's (or any database's) metadata. For example, comparing episode title differences between the two, getting [some data](https://developers.themoviedb.org/3/tv-episodes/get-tv-episode-details) such as episode images to translations for an episode. Given that TVDb and TMDb have widely different types of data for any given entry, this could be many things.

> Those are API docs from v2 and predate it's removal in 2013 (which was mentioned in the issue you linked).

Yes, I linked them just so the API endpoint (and past behavior) I was referring to was more clear.
