### ISSUE TITLE
NZB Skip Dupe check- blacklisted option

### ISSUE THREAD

**Issue by tmurd87** [Sonarr/Sonarr#4922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Would be nice to have a option for Sonarr to add a episode to NZB downloader and force download of blacklisted file skipping the duplicate file check possible have Sonarr remove the information from NZB downloader history allowing it to be downloaded again.

### Describe the solution you'd like

You can already manually download a NZB file and skip the dupe check if you do it from NZBGet itself. it would be nice if Sonarr had the option if a file downloaded was blacklisted for some reason it gave you the option to try and download it again and skip the dupe check.

### Describe alternatives you've considered

Only alternatives That I can think of is doing it manually 

### Anything else?

Some insight into the file dupe check added to nzbget and how the process works. https://forum.nzbget.net/viewtopic.php?t=2370

**Comment by markus101** [comment]
> and force download of blacklisted file

What does blocklisting have to do with this request?

> skip the dupe check.

Are there API docs on how to achieve this with NZBgets API? `Accept(dupemode:force): *` appears to be a config option on their side.

**Comment by markus101** [comment]
We can reopen if additional information becomes available.
