### ISSUE TITLE
Add an option for filtering out blacklisted releases

### ISSUE THREAD

**Issue by ryhaltswhiskey** [Sonarr/Sonarr#4923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

![image](https://user-images.githubusercontent.com/100481516/155849251-141eba29-f5a1-4c0e-80a7-a5ec2cbbfe71.png)

Blacklisted releases show up in the list of releases. But they are blacklisted for a reason, so there's no point in having them there. 

### Describe the solution you'd like

A simple "filter out blacklisted" checkbox next to the Filter dropdown. 

### Describe alternatives you've considered

Option for filtering out blacklisted releases in the filters. I tried to make one but it didn't work. On reddit someone said it's not possible. 

### Anything else?

Nope I think that's enough

**Comment by markus101** [comment]
This falls under https://github.com/Sonarr/Sonarr/issues/4132 but no short term plans for it.
