### ISSUE TITLE
Global File Name Rename

### ISSUE THREAD

**Issue by MiddleSiggy** [Sonarr/Sonarr#4925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Looking for a function to correct all file names across all entries without having to go into each entry and then doing the "preview rename". I just want to have it correct everything.

### Describe the solution you'd like

Looking for a function to correct all file names across all entries without having to go into each entry and then doing the "preview rename". I just want to have it correct everything.

### Describe alternatives you've considered

None

### Anything else?

Nope

**Comment by bakerboy448** [comment]
this exists

Are you on v3 and not v2?

![image](https://user-images.githubusercontent.com/55419169/156627662-9c5cb2bb-2a84-4dfd-adad-edc6bd5577d7.png)
