### ISSUE TITLE
Ability to ignore sub directory for all future imports

### ISSUE THREAD

**Issue by frankrende** [Sonarr/Sonarr#4927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have 2 "unmapped" folders in my TV Shows directory. This is intentional because:

- 1 of them maps to an existing show, even though I treat it as a separate one in Plex ("Adventure Time - Distant Lands" mapping to "Adventure Time")
- 1 doesn't map to a show, but Plex is able to map it correctly ("Chef's Table - BBQ")

Every time I import a new TV Show I have to wait for both of these to be scanned, and then uncheck them.

### Describe the solution you'd like

Have an option to "blacklist" or ignore sub directories so they are no longer analyzed on future imports. Either through the import screen, or under settings.

### Describe alternatives you've considered

Originally I had these TV Shows on a harddrive I was rarely performing an import on. But I recently moved to a DrivePool so all my directories are unified in one place. Now they are seen every time I perform an import, so the previous workaround is no longer valid.

### Anything else?

![image](https://user-images.githubusercontent.com/4317891/156778340-071b8619-04fe-42f0-a41f-6faa24f69082.png)

![image](https://user-images.githubusercontent.com/4317891/156778404-232f796e-25c4-46a1-8cb2-12ebc24cf480.png)

![image](https://user-images.githubusercontent.com/4317891/156778447-1e4e2fd0-2feb-4a57-a4ea-245d46a2965a.png)

![image](https://user-images.githubusercontent.com/4317891/156778479-6c28781c-5d20-4597-983f-1b9b3f8f253e.png)

**Comment by markus101** [comment]
> Every time I import a new TV Show I have to wait for both of these to be scanned, and then uncheck them.

I'm curious why this is an ongoing event in your use case, after the initial import you shouldn't really need to import again. Adding a new series can be done without importing from an existing folder, why is it that you need to go through the import process so often?

I'm very much leaning towards this being something we'll not address, but I'm curious why this is an ongoing issue in your workflow.

**Comment by frankrende** [comment]
I don't have Sonarr set up to automatically download shows. I manually download, and then use Sonarr to rename and to notify me when a new episode is available.

So when I find a new show I want to add to Plex, my process is:

1. Download the show
2. Move to my HDD that Plex uses
3. Import into Sonarr
4. Rename in Sonarr
5. In Plex, scan the library to add the show
6. Continue to monitor with Sonarr for new seasons/episodes

**Comment by markus101** [comment]
Changing that process to:

1.  Download the show
2. Add series to Sonarr
3. Import files via Manual Import (on Wanted: Missing)
4. Continue to monitor with Sonarr for new seasons/episodes

Sonarr will handle the renaming during import and can optionally tell Plex that the files were imported.

**Comment by markus101** [comment]
The other thing that you could do is move those folders to another location and add that as an additional location in Plex. That way Sonarr doesn't see them, but Plex will.

As far as ignoring them in Sonarr, this isn't something we plan to do at this time.
