### ISSUE TITLE
540p Season packs wont import

### ISSUE THREAD

**Issue by austinwbest** [Sonarr/Sonarr#4928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/8321115/156780638-6854e8c9-93ef-49be-800f-0c45c7d49bb4.png)

WordGirl.S01.480p.AMZN.WEB-DL.DD+2.0.x264-RTN - Imported
WordGirl.S02.540p.AMZN.WEB-DL.DD+2.0.x264-RTN - Failed
```Found matching series via grab history, but release title doesnt match series title. Automatic import is not possible.```
WordGirl.S03.540p.AMZN.WEB-DL.DD+2.0.x264-RTN - Failed
```Series title mismatch; automatic import is not possible.```
WordGirl.S04.1080p.Amazon.WEB-DL.DD+2.0.x264-QOQ - Imported
WordGirl.S05.1080p.Amazon.WEB-DL.DD+2.0.x264-QOQ - Imported
WordGirl.S06.1080p.Amazon.WEB-DL.DD+2.0.x264-QOQ - Imported
WordGirl.S07.1080p.Amazon.WEB-DL.DD+2.0.x264-QOQ - Imported
WordGirl.S08.1080p.Amazon.WEB-DL.DD+2.0.x264-QOQ - Imported

### Expected Behavior

- Add 540p support as it is pretty common so it imports as it actually is
- Map 540p to 480p so it imports with what is currently supported
- Fix the error to actually make sense

A quality issue doesnt seem like it should be saying `but release title doesnt match series title` and `Series title mismatch` as that seems more like `WordGirl` in the release title doesn't match `WordGirl` in Sonarr :)

When hitting the manual import option it sends 540p down to 480p (as there is no 540p support) so do the same thing for automatic importing

### Steps To Reproduce

Add some tests with 540p i would think could reproduce it? Or grab a 540p season pack 

### Environment

```markdown
- OS: Windows
- Sonarr: 3.0.6.1475
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

Dont think they are needed since it just isn't handling 540p

### Anything else?

Nope

**Comment by Taloth** [comment]
Funnily it parses the release title fine if the `540p` is omitted completely. Probably a bug in the regex that has to be fixed.
We won't be adding a separate quality for it though.

**Comment by austinwbest** [comment]
I didn't figure it would be added, was just adding options i could think of to handle it and stop it from failing :)
