### ISSUE TITLE
Catch and Silence /proc/mounts

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

unable to access /proc/mounts throws a scary error and stack trace

### Expected Behavior

per taloth /proc/mounts is a warning not a bug

### Steps To Reproduce

n/a

### Environment

```markdown
- OS: linux OSes
- Sonarr: 3.0.6.1342
- Docker Install: agnostic
- Using Reverse Proxy: agnostic
- Browser: agnostic
```

### What branch are you running?

Main

### Trace Logs?

n/a

### Anything else?

on taloth's todo list

**Comment by telans** [comment]
Does this fail for everyone? I can call `mount`, as well as view `/proc/mounts` from within the container yet I get the stack strace anyway
