### ISSUE TITLE
`MediaInfo VideoDynamicRangeType` reports `DV` and misses the HDR10 fallback.

### ISSUE THREAD

**Issue by addisonbabcock** [Sonarr/Sonarr#4936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`MediaInfo VideoDynamicRangeType` reports `DV` and misses the HDR10 fallback when HDR10+ is also available. I confirmed that HDR10 fallback is present by playing the file on a PC that does not support Dolby Vision. 

### Expected Behavior

`MediaInfo VideoDynamicRangeType` should show `DV HDR10` even when HDR10+ is present. Or possibly `DV HDR10+`? The current result of `DV` isn't accurate since it leads the user to believe there is no fallback. 

### Steps To Reproduce

I'm not sure I can provide repro steps without also providing the file in question (DM me if it's needed). 

### Environment

```markdown
- OS: Windows 11 21H2
- Sonarr: 3.0.7.1477
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Microsoft Edge Version 100.0.1181.0 (Official build) dev (64-bit)
```

### What branch are you running?

Main

### Trace Logs?

I don't have trace logs since I'm not sure they would be helpful in this case. Mediainfo dump is here: https://pastebin.com/LrNtMNx2

### Anything else?

There was a conversation about this in the discord: https://discord.com/channels/383686866005917708/383688189941907459/950795769068273715

zoggy requested this be noted:
https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoModelExtensions.cs#L31 should also include `Hdr10PlusFormats` in the check not just `Hdr10Formats`

**Comment by markus101** [comment]
This should be addressed in the v4 beta after moving to ffmpeg.
