### ISSUE TITLE
Manage Episodes button grayed out if there are no episodes

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#4938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Manage Episodes button (previously series Manual Import) can be used to modify existing episode files or import unlisted ones. However the button is disabled when no episode file exists, preventing you from importing unlisted ones.

### Expected Behavior

Manage Episodes button always available to import files from series folder.

### Environment

```markdown
- OS: n/a
- Sonarr: 3.0.7.1477
- Docker Install: n/a
- Using Reverse Proxy: n/a
- Browser: n/a
```

### What branch are you running?

Main

### Trace Logs?

n/a

### Anything else?

![image](https://user-images.githubusercontent.com/6383890/157471908-1156b986-72ad-4244-8ae9-65e83cefff45.png)

**Comment by Thirrian** [comment]
Related/cosmetic: once you click the button, the screen is still called "Manual Import".
Not sure how related it is in the code though, I'm not a dev...

**Comment by CounterClops** [comment]
Seeing similar behavior myself, and it's worth noting this also affects each seasons entry. Meaning I can't import each season until there is at least 1 file added there. See along the right side where every season except 1 is greyed out.
![season list](https://user-images.githubusercontent.com/19741838/157696909-24c80c9c-0160-467c-8a34-fcb039da8434.png)

Not sure if related, but even once the button is enabled, the manual import won't automatically detect season/episode/quality from the file name anymore. Refresh and scan works without issue though, and will pick up all the above information.

**Comment by geezfools** [comment]
> Refresh and scan works without issue though, and will pick up all the above information.

Thanks, hadn't manually importing anything in forever and wondering why I was struggling, refresh and scan did the trick.

**Comment by markus101** [comment]
> Seeing similar behavior myself, and it's worth noting this also affects each seasons entry

This is expected for seasons without files.
