### ISSUE TITLE
Sonarr cannot find The Adam Project

### ISSUE THREAD

**Issue by iio7** [Sonarr/Sonarr#4941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Search for "The Adam Project" or use tvbd:147304

### Expected Behavior

That Sonarr finds https://thetvdb.com/movies/the-adam-project

### Environment

```markdown
- OS: Arch Linux
- Sonarr: 3.0.7.1477
- Docker Install: No
- Using Reverse Proxy: NGINX
- Browser: Firefox
```

### What branch are you running?

Main

### Trace Logs?

I am sorry, but there is too much private information in the trace log for me to share it here. I have looked through the log after doing a search, nothing useful shows up.

### Anything else?

![Screenshot from 2022-03-13 03-04-06](https://user-images.githubusercontent.com/12476695/158041865-d3177088-4113-4796-83f3-b03355ef8b87.png)
![Screenshot from 2022-03-13 03-04-36](https://user-images.githubusercontent.com/12476695/158041870-9e58983b-2918-4a99-ac33-863e5dbd57ba.png)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

sonarr is not for movies

**Comment by thezoggy** [comment]
Sonarr handles tv. Adam project is a movie. Use radarr for that.

**Comment by iio7** [comment]
I am soo sorry! I cannot believe I made this mistake. I have both Sonarr and Radarr installed. I must be too tired, I didn't notice I was in the wrong application.
