### ISSUE TITLE
API `series/lookup` statistics object all `0`

### ISSUE THREAD

**Issue by AnujRNair** [Sonarr/Sonarr#4942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When querying the API using the `series/lookup` endpoint, all `statistics` results (except `seasonCount`) come back as 0:
```
"statistics": {
  "seasonCount": 1,
  "episodeFileCount": 0,
  "episodeCount": 0,
  "totalEpisodeCount": 0,
  "sizeOnDisk": 0,
  "percentOfEpisodes": 0.0
},
```

This happens when the entire show and all seasons are monitored (which the `series/lookup` endpoint recognizes as `"monitored": true`)

### Expected Behavior

All of the properties in `statistics` should be properly populated when using the `series/lookup` endpoint, much like they are when using the `series` api endpoint

### Steps To Reproduce

1. Add a series to Sonarr using the WebUI, monitor the series, monitor a season, and have the episodes downloaded to disk
2. Query for the series name: `https://<HOST>/api/v3/series/lookup?term=<SERIES_NAME>&apikey=<API_KEY>`
  a. Ensure you replace `HOST`, `SERIES_NAME` and `API_KEY` with appropriate values
3. Find the series you downloaded episodes for, and inspect the `statistics` property.
4. Verify they are all 0 (expect for `seasonCount`)

### Environment

```markdown
- OS: macOS 11.5.2 (Docker Host)
- Sonarr: 3.0.7.1477-ls136 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No/Yes (Tried with both, both have empty `statistics` object)
- Browser: Chrome 99.0.4844.51
```

### What branch are you running?

Main

### Trace Logs?

I see some `database is locked` messages in there, although I am unsure if they are related or not given that the `series` endpoint correctly populates the `statistics` object

There is also a random line break in there, and a second call to the series lookup endpoint – I cleared my logs, performed the action once, and have pasted the trace logs exactly as is

```
2022-03-13 20:29:15.0|Trace|Http|Req: 5022 [GET] /api/v3/series/lookup?term=Ranking%20of%20Kings&apikey=(removed) (from 172.18.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36)
2022-03-13 20:29:15.0|Trace|HttpClient|Req: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=ranking%20of%20kings
2022-03-13 20:29:15.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-03-13 20:29:17.8|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=ranking%20of%20kings: 200.OK (2772 ms)
2022-03-13 20:29:17.8|Trace|HttpClient|Req: [GET] https://services.sonarr.tv/v1/dailyseries
2022-03-13 20:29:17.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-03-13 20:29:18.3|Trace|HttpClient|Res: [GET] https://services.sonarr.tv/v1/dailyseries: 200.OK (506 ms)
2022-03-13 20:29:18.3|Trace|Owin|SQLite error (5): database is locked

2022-03-13 20:29:18.4|Trace|Http|Res: 5022 [GET] /api/v3/series/lookup?term=Ranking%20of%20Kings&apikey=(removed) 200.OK (3471 ms)
2022-03-13 20:29:18.4|Debug|Api|[GET] /api/v3/series/lookup?term=Ranking%20of%20Kings&apikey=(removed) 200.OK (3471 ms)
2022-03-13 20:29:18.5|Trace|Owin|SQLite error (5): database is locked
```

### Anything else?

N/A
Thanks for looking into this!

**Comment by markus101** [comment]
`series/lookup` is for searching new series, that information is not populated, even for existing series.

You'll want to use `series/ID` (where ID is the internal Sonarr ID for the series) or `series?tvdbid=TVDBID` for existing series.

**Comment by AnujRNair** [comment]
Understood – just trying to further understand why there are some fields which are properly populated for for existing series, and some are not?

For example, `added` and `path` are properly reflected for an existing series, as is `seasonCount` in the `statistics` object.

If these properties won't ever reflect accurate information, could they be removed from the api response?

**Comment by davidnewhall** [comment]
> If these properties won't ever reflect accurate information, could they be removed from the api response?

Incompatible API changes are definitely not something I'd want to see as a maintainer of an API-consuming library. These two endpoints currently return the same data structure, which makes it very easy to use them interchangeably. Breaking my library and forcing me to maintain two data structures for what is essentially the same data is non-ideal.

**Comment by davidnewhall** [comment]
I'm glad I don't write libraries that depend on APIs you control. :)

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/blob/d02d1bbdfe8827e13c54ec46aba19339a6fcb17c/src/Sonarr.Api.V3/Series/SeriesLookupModule.cs#L48

This is for UI sugar, in the Sonarr UI it allows us to show the expected folder name, which prevents people from attempting to create a new root folder for each series when they add series individually.

https://github.com/Sonarr/Sonarr/blob/d02d1bbdfe8827e13c54ec46aba19339a6fcb17c/src/Sonarr.Api.V3/Series/SeriesLookupModule.cs#L49

This is to populate the stats that are available, which for a new series is just the number of seasons, it maintains the same general format because it's nice to work with a single response type, not multiple.

**Comment by AnujRNair** [comment]
Thanks, appreciate the explanation
