### ISSUE TITLE
Toggle monitoring an episode off in Calendar

### ISSUE THREAD

**Issue by rob49152** [Sonarr/Sonarr#4944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Right now I have to go into each episode of a given show and toggle off the monitor episode icon after the episode is downloaded and copied into its final folder location. 

If I don't Sonarr will keep downloading the same episode over and over (even when the cut-off is met when the first download happened). I've even deleted all the profiles so there are only two options
![Image](https://i.imgur.com/My0k762.png)
I set the series to [HD-1080p]. Sonarr will download the [HD-1080p] episode and copy it into the series/season folder. Then a few hours later it will download the [HD-1080p] episode again.
History page: Preferred Word Score is the same on each download
Media Management page: Propers and Repacks are set to Do not Upgrade Automatically
Profile page: Only HD-1080p with 2 groups (HDTV-1080p and WEB 1080p) and Upgrades Allowed is disabled

### Describe the solution you'd like

It would be handy if you could quickly toggle the monitoring for an episode on/off on the calendar screen. 
![Image](https://i.imgur.com/eW6Gu6z.jpg)

With this solution I don't have to look at any pop-up or load any pages and take me away from my calendar view.

### Describe alternatives you've considered

Looked into seeing if writing a script for a post-process event was possible.

### Anything else?

I still think it would be much better for Sonarr to automatically unmonitor the episode once the cut-off has been met. Wasn't the whole purpose of Sonarr to automate the whole process?

**Comment by markus101** [comment]
Unless preferred words are causing the upgrade, the cutoff being met will stop additional grabs (use a support channel to troubleshoot if that’s not happening).

No plans to add the monitor toggle directly to the calendar item.
