### ISSUE TITLE
Trakt - Sync collection rate limiting

### ISSUE THREAD

**Issue by Phil57** [Sonarr/Sonarr#4945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Hello

I setup Sonarr and it is working quite nicely itself. I recently added a Trakt connection to automatically add downloaded episodes to my Trakt collection.

If I download a season pack of let's say 13 episodes, when Sonarr import them, it sends 13 API calls to Trakt in a very short time. Some of these call are blocked by Trakt's rate limiting and I'm missing a few in my Trakt's collection.

This of course doesn't happen for individually downloaded episodes, it is just for bulk download/import.

### Describe the solution you'd like

Is there a way to modify this behavior and send episodes in bulk to Trakt ? Their API supports arrays for that purpose. This could be for exemple a scheduled tasks that sync episodes every 5 minutes if new ones have been imported.

### Describe alternatives you've considered

None

### Anything else?

No

**Comment by markus101** [comment]
This is the same underlying issue as https://github.com/Sonarr/Sonarr/issues/4273
