### ISSUE TITLE
Manage Episodes re-assign multiple episode to single episode

### ISSUE THREAD

**Issue by stevietv** [Sonarr/Sonarr#4946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a episode is accidently imported against multiple episodes and you want to reassign it to a single episode Sonarr will lot let this happen.

eg this episiode is assigned to s05e04-e05 but it should be just s05e04

![image](https://user-images.githubusercontent.com/1117625/159127284-7efd2046-6b17-4080-b2c6-cacf9db43276.png)

![image](https://user-images.githubusercontent.com/1117625/159127307-b4651f3b-70f4-4e75-a8fe-6e292af88b7b.png)

![image](https://user-images.githubusercontent.com/1117625/159127322-93573c3b-6baa-4663-ab4e-298e4b7e2177.png)

clicking import does not change the assignment

### Expected Behavior

Episode should be reassigned to a single episode.
It stays as the current assignment

### Steps To Reproduce

1. assign a release to multiple episodes
2. try to reassign to a single episode

### Environment

```markdown
- OS: ubuntu 20.04
- Sonarr: 3.0.7.1477
- Docker Install: 3.0.7.1477-ls137 by linuxserver.io
- Using Reverse Proxy: traefik2
- Browser: chrome
```

### What branch are you running?

Main

### Trace Logs?

see comment https://github.com/Sonarr/Sonarr/issues/4946#issuecomment-1073067128

### Anything else?

all above

**Comment by markus101** [comment]
Not sure what logs you attached, but those aren't Trace logs from Sonarr.

**Comment by stevietv** [comment]
well that was weird! opened the logs in my browser and did a save as. Guess because Sonarr is behind a reverse proxy with oauth that it pulled in the auth page during download!

here are the logs.

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/8309941/sonarr.trace.txt)
