### ISSUE TITLE
Upgrading preferred score for cutoff-met episodes

### ISSUE THREAD

**Issue by wloot** [Sonarr/Sonarr#4947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Episodes meets both quality and language cutoff i set in profiles, but sonarr tries to upgrade them to higher score release.

quality profile:
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/30223095/159184048-7992d52e-e3f5-4832-9a85-5c72a3a49d54.png">

language profile:
<img width="733" alt="image" src="https://user-images.githubusercontent.com/30223095/159184070-de275235-f9cb-41c7-8271-7cd94e3feacb.png">

series settings:
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/30223095/159184143-4c280d1b-92cc-46b1-817e-c3c09ea9ce90.png">

local files of season:
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/30223095/159184133-b8cf9871-3e74-4285-9230-b8b1ef9b1140.png">

the unwanted grabbed release(I set a higher preferred score for x264 1080p):
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/30223095/159184154-a5b72796-44b4-4113-9c51-f97ae2b80801.png">

### Expected Behavior

Do not upgrade if meet cut off.

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 3.0.7.1479
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

n/a

### Anything else?

n/a

**Comment by markus101** [comment]
Preferred words are always upgrades at the moment, this is covered by https://github.com/Sonarr/Sonarr/issues/4302
