### ISSUE TITLE
Beavis And Butt-Head missing season 8

### ISSUE THREAD

**Issue by mackbuddy4** [Sonarr/Sonarr#4948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Beavis And Butt-Head skips season 8 completely. It goes from 7 to 9.

### Expected Behavior

I should see season 8 with my own eyes. Its invisible.

.

### Environment

```markdown
- OS:Windows 10 
- Sonarr:2.0.0.5344
- Docker Install:no
- Using Reverse Proxy:no
- Browser:Chrome
```

### What branch are you running?

Main

### Trace Logs?

*.trace.*.txt

### Anything else?

![beavis](https://user-images.githubusercontent.com/102006002/159199204-5c66ef4f-4957-42da-9bfd-30d4e9af8986.jpg)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

This isn’t a Sonarr issue, TheTVDB doesn’t have a season 8… https://thetvdb.com/series/beavis-and-butt-head

Sonarr v2 is very out of date and no longer supported, v3 has been out for the better part of a year.
