### ISSUE TITLE
Adding VFQ as french detected release language

### ISSUE THREAD

**Issue by quamok** [Sonarr/Sonarr#4949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

VFQ in the release name means "Version Française Québécoise", or "Quebec French Version". However, when searching with Sonarr, releases with VFQ in the release name aren't detected as French.

Example: 
Release name: Les.Mecs.S01.720p.VFQ.WEB-DL.AAC2.0.H.264-BTN
Error: Release rejected - English is not allowed in profile French

### Describe the solution you'd like

I'd suggest to add VFQ in the regex used to match release language as a french release. 

### Describe alternatives you've considered

manually grabbing the release.

### Anything else?

![les mecs](https://user-images.githubusercontent.com/24906799/159276036-7c7a0505-f929-4c3d-9063-a1ec5e65c727.png)

**Comment by toniou** [comment]
Hi, it's the same problem with the keyword VF that mean "version française".

**Comment by amayii0** [comment]
Hi,
Found this while searching for support for VF2 (VFF & VFQ combined)
There seems to have a (pretty old, forgotten) PR for this : https://github.com/ta264/Sonarr/commit/b70016d082f321861bd2e74651ed848288cd925e
