### ISSUE TITLE
UI: Protocol preference is hidden in "Delay Profiles"

### ISSUE THREAD

**Issue by issueg2k4g34j2g** [Sonarr/Sonarr#4951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently it's very difficult to figure out where to change the sonarr protocol preference without reaching out for a manual.

The protocol preference is on the profiles page where it should be, but hidden inside a sub menu used to alter "Delay Profiles".  The user has to click the small spanner icon used to alter delay profiles in order to find the hidden protocol preference setting.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/101990239/159954830-17a3b4ac-5de4-4959-9bb4-98a2b392a950.png">

<img width="690" alt="image" src="https://user-images.githubusercontent.com/101990239/159954934-0f838335-36d6-40fb-9ed9-4bbdd892d9ab.png">

Given that the protocol preference is an arguably far more important setting than the delays, this isn't a good state of things.

### Describe the solution you'd like

Protocol preference should be clearly visible on the "Settings"->"Profiles" page

### Describe alternatives you've considered

I believe that the protocol preference setting should either be separated from Delay Profiles, or Delay Profiles and the "Protocol" column below should be renamed.

### Anything else?

Something like this would already be a huge improvement, although "Protocol Profiles" sounds clunky:
<img width="704" alt="image" src="https://user-images.githubusercontent.com/101990239/159955865-d4ea3bcf-b475-4594-ae6a-7eb0b99f1b8c.png">

**Comment by bakerboy448** [comment]
Updating "Protocol" to "Preferred Protocol" is probably the simplest and best solution  or perhaps mapping it 1x1 so rather than Torrent it says Prefer Torrent
