### ISSUE TITLE
Monitor Future Leaves Last Season Tagged as Monitored

### ISSUE THREAD

**Issue by techmattr** [Sonarr/Sonarr#4952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This may be intentional in how Sonarr would pick up the next season or it may just be a cosmetic bug.

When a show is set to monitor Future the last season is left in a monitored state. However, the episodes within the season are unmonitored.

### Expected Behavior

I would expect any season in which all episodes have already aired to marked as Unmonitored. 

### Steps To Reproduce

Set monitoring of any show that has either ended or in between seasons to Future. The latest season will remain in an monitored state. 

### Environment

```markdown
- OS: Ubuntu 20.04.4
- Sonarr: 3.0.7.1477
- Docker Install: n/a
- Using Reverse Proxy: no
- Browser: any
```

### What branch are you running?

Main

### Trace Logs?

N/A

### Anything else?

N/A

**Comment by thezoggy** [comment]
Sonarr inherits last season monitored status for future added seasons. So that's exactly why you see this behavior

**Comment by markus101** [comment]
This is intentional, Sonarr has no way to know whether a season has completed airing or is in some sort of a hiatus, like Breaking Bad's final season.
