### ISSUE TITLE
Batch add with url

### ISSUE THREAD

**Issue by ERasnier** [Sonarr/Sonarr#4954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

If I wanted to watch episodes of a show just to watch a specific charachter that's featured in that show, I'd have to either:

- Uncheck all episodes, and individually check each episode with a window on IMDB to check which is agonising.
- Make a list on IMDB, import the list to Trakt TV, and import it to Sonarr or Radarr which don't do often but is still pretty agonising having to relearn how I did it previously.

### Describe the solution you'd like

Just a Batch Add tab with a text box that I can copy/paste a bunch of URLs within. 

### Describe alternatives you've considered

There is the Web to Plex avenue and others described above but I don't use Plex and don't plan on doing so.

### Anything else?

Nope.

**Comment by bakerboy448** [comment]
- IMDb has nothing to do with Sonarr
- Sonarr uses TVDB
- don't believe there are any plans for this; you'd be better off either using Lists or creating the empty folders (ideally with the tvdbid in them) and then doing a library import
