### ISSUE TITLE
HEVC/265 Filter

### ISSUE THREAD

**Issue by CKades** [Sonarr/Sonarr#4957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No, there isn't a problem related around this

### Describe the solution you'd like

I'm personally someone who has invested converting all of my x264 video file formats to HEVC, i'm wanting the ability to find all of my x264 videos through Sonarr vs having to click on each show within the plex to find more video details.
Would be nice to support mulitple file formats, just having the ability to use a dynamic search (V9,x264,x265) would be appealing. This could even include audio type format.

I know Sonarr has the ability to see this, but i can't find any personal way to search or filter with it.

### Describe alternatives you've considered

The current path of opperation to even see this information is going to a series, looking at what's been collected, looking at the 'details' directory of that file to see if format

### Anything else?

.
![image](https://user-images.githubusercontent.com/72682200/160392896-a45d2701-caa2-4203-8ba2-ad0053e21338.png)
This is where i was pitching the ability to create filters or just show details by default.
Example would be TV-Show has x265 for season 1/2 but season3 i have x264 video file format. Sonarr should either pull up that show saying mixed format or calling out just season 3.

**Comment by markus101** [comment]
Sonarr has this information, but bringing it to the series level would be expensive, because every episode file for every series would need to get that information from the database then parse the JSON and then aggregate it in some way. This isn't something we have plans to do, at least at this time.
