### ISSUE TITLE
Failed to load series from API

### ISSUE THREAD

**Issue by skapytek** [Sonarr/Sonarr#4958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

with a big library forced library scanning is taking too long.
During this process im not able to access sonarr -> Failed to load series from API Version 3.0.7.1485

### Describe the solution you'd like

Access to sonarr during scanning
Add settings where we can disable scanning.

### Describe alternatives you've considered

Restarting sonarr so im able to access sonarr before it starts a new scan

### Anything else?

-

**Comment by markus101** [comment]
You can opt out of library scanning once you you’re able to load all the series from the API. No plans to change the current behaviour ahead of retiring mono.

**Comment by skapytek** [comment]
Thanks for the info. I cant find the option in the settings to disable the scans. Where can i find this option?

**Comment by markus101** [comment]
Settings: Media Management (it’s an advanced setting)
