### ISSUE TITLE
Sonarr Not Removing Completed Downloads From Deluge

### ISSUE THREAD

**Issue by jonatino** [Sonarr/Sonarr#4962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever sonar tries to delete torrents from my seedbox on deluge, it throws a DelugeException saying torrend_id X not in session.

My logs are filled with messages similar to this. All my torrents are in a "Paused" state in Deluge.

```
2022-03-29 06:33:03.1|Error|DownloadEventHub|Couldn't remove item Cosmos.Possible.Worlds.S01.1080p.AMZN.WEBRip.DDP5.1.x264-iKA[rartv] from client Deluge

[v3.0.6.1342] NzbDrone.Core.Download.Clients.Deluge.DelugeException: Failure: [Failure instance: Traceback (failure with no frames): <class 'deluge.error.InvalidTorrentError'>: torrent_id 8d07edb3b32d714219f745cb40355900749f84b7 not in session.
] (code 4)
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult] (NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings, System.String method, System.Object[] arguments) [0x00072] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:232 
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.RemoveTorrent (System.String hash, System.Boolean removeData, NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:129 
  at NzbDrone.Core.Download.Clients.Deluge.Deluge.RemoveItem (NzbDrone.Core.Download.DownloadClientItem item, System.Boolean deleteData) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:189 
  at NzbDrone.Core.Download.DownloadEventHub.RemoveFromDownloadClient (NzbDrone.Core.Download.TrackedDownloads.TrackedDownload trackedDownload, NzbDrone.Core.Download.IDownloadClient downloadClient) [0x0002b] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\DownloadEventHub.cs:92 
  ```

### Expected Behavior

Should delete a torrent regardless of it's status on deluge.

### Steps To Reproduce

1. Use sonarr in docker
2. Setup deluge client
3. Setup deluge to automatically pause torrents once seeding ratio is reached

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: Latest
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Main

### Trace Logs?

Log above

### Anything else?

Log above

**Comment by jonatino** [comment]
Deluge 2.0.5.

That torrent did indeed not exist, I posted the incorrect stack trace. Apologizes.

The problem I have, is I download a lot of season packs, and download them from my server using lftp. Sonar imports one file at a time (which works), but never ends up removing the download because it just in an infinite state of throwing errors that "Destination X Already exists"

Logs:
https://pastebin.com/UP7ufmZa

Sonar will just forever throw these errors until I manually delete the job from the queue.

**Comment by jonatino** [comment]
Screenshots of queue everything says already imported or destination exists.

https://i.imgur.com/fKm4nHq.png

https://i.imgur.com/kzQbRfX.png

**Comment by bakerboy448** [comment]
> download them from my server using lftp

and therein lies the problem, your workflow isn't exactly great.

For a remote download client you have two options:
- remote mount
- remote sync

There are signifcant caveats with remote sync namely both ends need to support hardlinks (ie. atomic moves), you need to use a complete and incomplete download folder in your client, and the files need to be completely hidden and not show up to sonarr in anyway until they are fully downloaded and local to sonarr

any other half-baked attempts will result in your issues and worst case result in corrupt video files imported

**Comment by bakerboy448** [comment]
Also those are not trace logs and are just error which isn't helpful. Nor did it seem to capture anything relating to deluge?

please review the gathering logs wiki that the bug report template links for how to get and gather trace logs.

**Comment by jonatino** [comment]
> > download them from my server using lftp
> 
> and therein lies the problem, your workflow isn't exactly great.
> 
> For a remote download client you have two options:
> 
> * remote mount
> * remote sync
> 
> There are signifcant caveats with remote sync namely both ends need to support hardlinks (ie. atomic moves), you need to use a complete and incomplete download folder in your client, and the files need to be completely hidden and not show up to sonarr in anyway until they are fully downloaded and local to sonarr
> 
> any other half-baked attempts will result in your issues and worst case result in corrupt video files imported

Kind of figured it was some weird sync issues between sonar and lftp. Remote mount sounds interesting. Is this just a basic ssh mount?

Sonar will copy the files from the mount to my local server?

**Comment by bakerboy448** [comment]
SSHFS mount yeah speed may vary and sync may be faster albeit more complex

Both will of course need a remote path map.


And your actual import issue is probably the underlying file system presumably doesn't like replacing a file with one named the same as the existing.

**Comment by jonatino** [comment]
It seems to be importing the files correctly. For some reason the Series page on sonarr isnt always updated after episodes are imported?

I had to manually go in and refresh the Series and it then detected all the files it previously imported (they were marked missing still) and marked the season as downloaded. After this happened sonarr quickly deleted the files from deluge.
