### ISSUE TITLE
Add "MediaInfo VideoDynamicRangeType" as a column when in a show 

### ISSUE THREAD

**Issue by undead9786** [Sonarr/Sonarr#4963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not a problem but a feature request.

### Describe the solution you'd like

Currently some of the columns available are Video Codec, Size, Release Group, etc. It would be great if there was also a MediaInfo VideoDynamicRangeType column so you can see if it's SDR, HDR, DV, DV with HDR fallback etc.

### Describe alternatives you've considered

Only thing I can think of is to enable renaming and then see the preview rename currently.

### Anything else?

I believe it is self explanatory.

**Comment by Qstick** [comment]
My only comment here is where would this stop with MI columns. We could have infinite.

**Comment by undead9786** [comment]
> My only comment here is where would this stop with MI columns. We could have infinite.

Not sure what you mean, is it possible to have more then 2-3 MediaInfo VideoDynamicRangeType?

**Comment by Qstick** [comment]
You are asking for MI VDR column, the next guy wants a MI number of streams column, the next guy wants a MI resolution column, then a guy thinks he needs to see a MI channels column. We will have 100 columns by the end for every mediainfo property we store, that's my only worry.

**Comment by quadcom** [comment]
+1

I can't use HDR at the moment but I still would like 2160 posts. Currently, UltraHD is an all-encompassing filter.

PS. Late to the party, just getting into Sonarr now. awesome job guys!

**Comment by markus101** [comment]
I'm not overly worried about there being a bunch of columns; minimal effort to create them and they're disabled by default, though I don't think automatically generating the ones we have makes a lot of sense with the current structure.
