### ISSUE TITLE
Alternative Titles

### ISSUE THREAD

**Issue by FrozenSource** [Sonarr/Sonarr#4966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Hi guys,

Something I can't find is how to use alternative titles for series.
When TVDB has an English title is sometimes doesn't go by that title in torrents...
Is there any way to force an alternative search title?

### Describe the solution you'd like

In the series settings an optional list of alternative titles; regex or not*

### Describe alternatives you've considered

-

### Anything else?

-

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

this is also covered on the FAQ entry of why can't sonarr find X
