### ISSUE TITLE
Delete seasons

### ISSUE THREAD

**Issue by Iguana9999phil** [Sonarr/Sonarr#4979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

At the moment Sonarr has the option to delete a whole serie. With autoscan accepting delete it makes it very easy to just delete the serie from sonarr and it will be deleted from disk and autoscan sends a scan request to Plex for it to scan and remove the serie. 

For some dailies / Kardashians / housewives series I only like to keep the current season available. An option per season to just delete the season would be very helpful in this case.

### Describe the solution you'd like

Extra option per season to delete the whole season with the same modal you get when deleting a whole serie.

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by bakerboy448** [comment]
This can already be done - click the manage episodes button for the season; select all; delete

![image](https://user-images.githubusercontent.com/55419169/162336926-427ed457-e24a-453c-80f6-7160c1d47dd5.png)

you can also set plex to delete an episode after watching or after x days and have sonarr unmonitor deleted episodes

Defer to markus/taloth on a delete seasons specific button/modal

**Comment by markus101** [comment]
No plans for adding another way to do that, manage episodes is the way.

**Comment by Iguana9999phil** [comment]
Damn, I should have looked closer ;-) no need for another way this will do just fine!
