### ISSUE TITLE
Support "Season 2 - 01" format for Anime

### ISSUE THREAD

**Issue by bitgladius** [Sonarr/Sonarr#4982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some anime series are not being picked up because groups are using Season 2 with season specific episode numbering

### Describe the solution you'd like

Search these formats if no results found

### Describe alternatives you've considered

User-specified search string so I can fix things myself once a season.

Manual downloads like a caveman.

### Anything else?

Was on Unraid 6.8.2 with a dated version of Binhex's docker. Updated to 6.9.2 and updated the container. The use standard for anime setting fixed S2 - 01 format but not Season 2 - 01

**Comment by markus101** [comment]
This is a pretty standard for anime, Sonarr doesn’t handle them directly, but via aliases and mappings from The XEM, we don’t have plans to support directly.

Their IRC channel or the #xem channel in the Sonarr discord is the best places to discuss these aliases.
