### ISSUE TITLE
Remove item from plex watchlist once downloaded or ignore item from future list imports

### ISSUE THREAD

**Issue by RileyXX** [Sonarr/Sonarr#4983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I'm using the new plex watchlist with sonarr list importing to automatically add shows from my plex watch list. Once they are downloaded and in my library I have no need for them to stay in my plex watchlist. And if I end up deleting the show in plex it will automatically redownload again in sonarr on the next list import unless I manually remove shows from my plex watch list.

### Describe the solution you'd like

Add an option under **Settings > Lists > Plex Import List** to **Remove item from watchlist once downloaded**

### Describe alternatives you've considered

Add option under **Settings > Media management > Importing** to **Ignore item from future import lists once downloaded**

### Anything else?

<img width="801" alt="Capture2sonarr" src="https://user-images.githubusercontent.com/49823202/163334150-36b74301-e72e-4785-8760-245d4c181e47.PNG">

**Comment by markus101** [comment]
We don’t have plans to remove items from the watchlist after adding to Sonarr.

When you remove the series from Sonarr you can add it to the import exclusion list so it is not added again.

**Comment by RileyXX** [comment]
> When you remove the series from Sonarr you can add it to the import exclusion list so it is not added again.

How do you add an item to import exclusion list if you delete the item through sonarr?

**Comment by bakerboy448** [comment]
![image](https://user-images.githubusercontent.com/55419169/163402338-43124c95-56e0-4c92-9f71-706174142536.jpeg)

Check add list exclusion when deleting the series from Sonarr
