### ISSUE TITLE
Remember `Add List Exclusion` setting when deleting series

### ISSUE THREAD

**Issue by RileyXX** [Sonarr/Sonarr#4984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I'm using the new plex watchlist with sonarr list importing to automatically add shows from my plex watch list. When I delete a series through plex or from my disk, it automatically downloads again from my plex watchlist import. So my only option is to manually delete items from my plex watchlist before I delete them in plex.

### Describe the solution you'd like

Add option under **Settings > Media management > File management** 

**Episodes deleted from disk are added to list exclusions for future list imports: _Y / N_**

### Describe alternatives you've considered

Only option is to delete the series manually through sonarr's interface and add it to future list import exclusions 

OR

Remove series from watchlist in plex and then delete it through plex

### Anything else?

<img width="814" alt="Capture4sonarr" src="https://user-images.githubusercontent.com/49823202/163339858-3f196854-f893-4e20-bd04-d73fd9af8c3e.PNG">

Also see:
https://github.com/Radarr/Radarr/issues/7226

**Comment by RileyXX** [comment]
> Episodes are not added from lists only series are, so I'm not sure what you're trying to accomplish?
> So if you delete one episode of a series, you want the entire series to be added to the import list exclusion? That seems rather extreme.

You are right that's a good point. I think in order to do this the right way list exclusions would need to be modified in order to also include single episodes and/or entire series. 

However, as a secondary option it could be implemented in a way so that only when an entire series is deleted, it is added to sonarr's list exclusions. I think this feature would still be very useful in that regard.

> How does unmonitor deleted episodes not already do what you want?

When a series/episode is deleted from the disk/plex interface it is unmonitored. However on the next list import it is automatically remonitored and downloaded again.

**Comment by bakerboy448** [comment]
> When a series/episode is deleted from the disk/plex interface it is unmonitored. However on the next list import it is automatically remonitored and downloaded again.

This should not be occurring; list are not configured to modify existing entries. Please get trace logs and screenshots of this happening and swing by (ideally) Discord or (less ideally) open up a bug report.

**Comment by markus101** [comment]
We're not going to create a setting for something that already exists, but do plan to make that selection remembered between deletions, so as long as you're using the same browser it will be persisted.
