### ISSUE TITLE
Next-Prev buttons

### ISSUE THREAD

**Issue by Kedryn** [Sonarr/Sonarr#4988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When i use those buttons in a show view, they move on the next show without respecting any filter

### Describe the solution you'd like

I think they should  respect the filter applied.

### Describe alternatives you've considered

none

### Anything else?

none

**Comment by markus101** [comment]
The filter only applies to the series list, we do not have plans to apply the filter when on the series details page and moving to other series.
