### ISSUE TITLE
Allow specifying url base with a command line parameter

### ISSUE THREAD

**Issue by craftyguy** [Sonarr/Sonarr#4989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Similar to https://github.com/Sonarr/Sonarr/issues/3184, but a command line option instead of an environment variable. This would be really helpful when sonarr is run in a container, allowing the url base to be set easily and dynamically when the container + sonarr is started.

### Describe the solution you'd like

A command line parameter to set/change the url base when sonarr is run, something like `/urlbase` would be fine, but honestly the name isn't super important as long as it's descriptive and functional 😄 

https://github.com/Sonarr/Sonarr/wiki/Command-Line-Options

### Describe alternatives you've considered

Manually configuring sonarr on first run to set the url base, which breaks any attempts to have a completely automated deployment of sonarr

### Anything else?

Here's one popular implementation of sonarr in a container that I use, and the issue that inspired me to file this ticket: https://github.com/linuxserver/docker-sonarr/issues/118

**Comment by markus101** [comment]
Same as #3184 we don’t have plans to support setting/overriding config file options from the command line either.

**Comment by craftyguy** [comment]
that's unfortunate.... thanks for the quick reply though.
