### ISSUE TITLE
Mushoku Tensei Season 1 Episodes Jump by 1

### ISSUE THREAD

**Issue by Neipas09** [Sonarr/Sonarr#4990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For whatever reason, the episode number in (#) for Episode 17 jumps up by 1.
I've looked at TVDB and can't find a reason for it (https://thetvdb.com/series/jobless-reincarnation-it-will-be-all-out-if-i-go-to-another-world) so i thought i would post it here.

![image](https://user-images.githubusercontent.com/58871039/163726568-80c3752c-2040-4f36-945f-96ce6b895515.png)

### Expected Behavior

Episode number in (#) to match the actual episode number.

### Environment

```markdown
- OS: Windows 10
- Sonarr: 3.0.7.1477
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

n/a

### Anything else?

all in the current behavior

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.
