### ISSUE TITLE
Tixati Support

### ISSUE THREAD

**Issue by tedztar** [Sonarr/Sonarr#4992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have personally tried all supported torrent programs available and none operate how I would like.

### Describe the solution you'd like

It would be neat if we could get support for Tixati as it now has some intergration access.

### Describe alternatives you've considered

I have tried all other torrent programs and none have worked well.

### Anything else?

na

**Comment by bakerboy448** [comment]
A quick search on their site and their forums indicates that still no API exists and thus nothing to integrate. Do you have links to their API docs?

Previous Sonarr GitHub issue requesting that client noted it would be the same implementation as a black hole client which already exists

**Comment by tedztar** [comment]
Ill look into the BlackHole method, and sorry I do not, when looking at the API was thinking of the web interface.
Had a huge brain missing moment on that one.
Ill see if I can get ahold of the devs and see if there is one as I take it the Web interface could not be used?

**Comment by markus101** [comment]
The existence of the web interface doesn't mean they have an API we can use to integrate, some apps including Sonarr have the web UI built on top of the API, but many do not.

**Comment by markus101** [comment]
This looks to be the closest thing to an API that someone implemented: https://github.com/PsychedelicShayna/tixati-python-api-cli

We're not going to integrate via screen scraping, if there ends up being an API in the future a new issue can be opened.
