### ISSUE TITLE
IRC XDCC support

### ISSUE THREAD

**Issue by AnimusTitanimus** [Sonarr/Sonarr#4995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

There is no ability to utilize IRC/XDCC downloading

### Describe the solution you'd like

Ability to utilize IRC/XDCC downloading

### Describe alternatives you've considered

N/A

### Anything else?

Issue #3592 asked this question about 2 years ago and the final response said at the end "...third download client type and we're not willing to accept that at this time." 

I'm just wondering if this has changed or not.

**Comment by bakerboy448** [comment]
Still no plans for protocols other than BitTorrent m/Usenet
