### ISSUE TITLE
Add custom series aliases

### ISSUE THREAD

**Issue by wloot** [Sonarr/Sonarr#4998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some series have more than one English translate titles. Since Tvdb API is not yet able to pull aliases infomation IIRC, searching keywords we processed may not cover all releases, especially some asian dramas.

### Describe the solution you'd like

Allowing users to add alias titles to series.

### Describe alternatives you've considered

None

### Anything else?

None

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

https://wiki.servarr.com/sonarr/faq#why-cant-sonarr-import-episode-files-for-series-x-why-cant-sonarr-find-releases-for-series-x
