### ISSUE TITLE
New Language: Ukrainian

### ISSUE THREAD

**Issue by Mokson** [Sonarr/Sonarr#5000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Missing language profile

### Describe the solution you'd like

Add the language to the parser

### Describe alternatives you've considered

-

### Anything else?

two letters: uk
three letters: ukr
https://en.wikipedia.org/wiki/Ukrainian_language

Almost always a torrent title contains multi-languages
![image](https://user-images.githubusercontent.com/41159986/164889455-d40c157f-88e1-41c7-bd8f-e600bdccd3f0.png)

**Comment by markus101** [comment]
Please provide full release names as text, not screenshots.

**Comment by Mokson** [comment]
**Movies**
Бетмен / The Batman (2022) WEBRip-AVC Ukr/Eng
Геркулес (Серія 1-2) / Hercules (Episode 1-2) (2005) DVDRip 2xUkr/Eng | Sub Ukr
7 годин на зваблення / 7 ore per farti innamorare (2020) WEBDLRip-AVC Ukr/Ita

**TV Series**
Гало (Сезон 1, серії 1-5) / Halo (Season 1, episodes 1-5) (2022) WEBRip-AVC Ukr/Eng
Архів 81 (Сезон 1) / Archive 81 (Season 1) (2022) WEB-DLRip-AVC Ukr/Eng | Sub Ukr/Eng
Книга Боби Фетта (Сезон 1) / The Book of Boba Fett (Season 1) (2021) WEB-DLRip Ukr/Eng
