### ISSUE TITLE
Plex API Path Scan 

### ISSUE THREAD

**Issue by justinglock40** [Sonarr/Sonarr#5001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not related to any problems

### Describe the solution you'd like

Implementation of using the Plex API to trigger a path scan

### Describe alternatives you've considered

Currently using Autoscan

### Anything else?

Radarr team implemented the following
https://github.com/Radarr/Radarr/commit/24206ad0a3095c4bf5c860af516d8543bd6525d6

**Comment by markus101** [comment]
How does this differ from updating the series path which is already supported?

**Comment by Qstick** [comment]
It doesn't make a big difference for Sonarr other than avoiding a full library scan on the first episode. Otherwise Sonarr already selective scans by metadata Id. With movies it's always the first episode outside of updates.

**Comment by justinglock40** [comment]
I think the only thing would be preventing the full library scan, but I think series path is good enough.
