### ISSUE TITLE
Naming pattern doesn't work anymore

### ISSUE THREAD

**Issue by Bazzu85** [Sonarr/Sonarr#5003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using my historical naming pattern (It's like this from months)

`{Original FileName} {MediaInfo AudioLanguages:IT+EN}`

Sonarr now throws an error:
![image](https://user-images.githubusercontent.com/7345587/165703613-2bdf9848-6daa-4257-8321-2b7aa81c6a0b.png)

Here's some example the results:
![image](https://user-images.githubusercontent.com/7345587/165703741-fdc7aaf5-62cd-424f-8bf2-a0ea46ffde67.png)
or a empty file name it the mediainfo doesn't have the desired pattern

tried also a simple `{Original FileName} {MediaInfo AudioLanguages}`, same error
with only `{Original FileName}` tag works

Talking on discord support I landed in this commit https://github.com/Sonarr/Sonarr/commit/ebb48a19cc792c71bfbd57d5f106067190d95339

If the error now is intended, can I know why?
if it's not intended (I hope so), can you fix? thx

### Expected Behavior

Sonarr append to the original file name the additional tags without errors

### Steps To Reproduce

1. Use the {Original FileName} {MediaInfo AudioLanguages:IT+EN} scheme
2. Try a rename

### Environment

```markdown
- OS: Windows 10 Pro
- Sonarr: 3.0.8.1507
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

No need of trace logs. It can be tested in the UI

### Anything else?

nope

**Comment by Bazzu85** [comment]
To test if is working I have to try the last develop branch? Ty

**Comment by massijay** [comment]
I think it still doesn't work correctly, my pattern is;
`{Series Title} - S{season:00}E{episode:00} - #ORIG#{Original Filename}`
After the #ORIG# it writes nothing.
I have also tried using Original Title instead, but sometimes doesn't work too.
I use this pattern because I want to keep the original file name and if I want to rename everything back I can do it very quickly

**Comment by CLHatch** [comment]
> I think it still doesn't work correctly, my pattern is; `{Series Title} - S{season:00}E{episode:00} - #ORIG#{Original Filename}` After the #ORIG# it writes nothing. I have also tried using Original Title instead, but sometimes doesn't work too. I use this pattern because I want to keep the original file name and if I want to rename everything back I can do it very quickly

The reasoning you use for that naming scheme is one of the reasons I chose to put each episode in it's own folder, with the original filename inside that.  I get a lot of flak for it, and I admit, it DOES make for long paths, but it works, and Plex hasn't had any issues with the extra folder.  This is my current naming scheme:

`{Series TitleYear} - S{season:00}E{episode:00} - {Episode Title} [{Air.Date}] {[Preferred Words]} [{MediaInfo VideoCodec} {MediaInfo VideoDynamicRangeType} {MediaInfo VideoBitDepth}bit {Quality Full}] [{MediaInfo AudioCodec} {MediaInfo AudioChannels}{ MediaInfo AudioLanguagesAll}]{ MediaInfo SubtitleLanguagesAll}{-Release Group}/{Original FileName}`

Doesn't help solve the issue with your current scheme not working, but it is an alternative to consider.

**Comment by Bazzu85** [comment]
Installed the last develop build and I think it's now fixed

**Comment by markus101** [comment]
Sonarr will only populate the original title/filename _if_ it has the file/release name (stored as scene name) when it's mixed with other episode identifiers (season/episode numbers, air date or absolute episode numbers), if Sonarr has to use the current file name for some reason it won't include the original title/filename because that will cause the information to be repeated every time the file is renamed.

**Comment by ThibaultNocchi** [comment]
Hello, I still have the same problem when adding the episode number to a string with original filename.

![image](https://user-images.githubusercontent.com/1619359/166141014-4a3cb90a-5984-44df-a94c-031fb7571794.jpeg)
![image](https://user-images.githubusercontent.com/1619359/166141019-ea9d6edb-7279-4cbf-90ba-bddad011693f.jpeg)

I am on the latest develop version.

**Comment by Bazzu85** [comment]
> Hello, I still have the same problem when adding the episode number to a string with original filename.
> 
> ![image](https://user-images.githubusercontent.com/1619359/166141014-4a3cb90a-5984-44df-a94c-031fb7571794.jpeg) ![image](https://user-images.githubusercontent.com/1619359/166141019-ea9d6edb-7279-4cbf-90ba-bddad011693f.jpeg)
> 
> I am on the latest develop version.
> 
> Edit: I tried a few more combinations:
> 
> * `{Original Filename}.E{episode:00}S{season:00}` works
> * `{Original Filename}.S{season:00}S{episode:00}` works (note that it is S and S, not S and E)
> * `{Original Filename}.S{season:00}E {episode:00}` works (note the space after the E)

Where did you have problems? From the UI seems ok..

**Comment by ThibaultNocchi** [comment]
I tried from the web UI. Weird, could you copy paste the exact sentence you had that worked please?

**Comment by Bazzu85** [comment]
> I tried from the web UI. Weird, could you copy paste the exact sentence you had that worked please?

I asked 'cause in your screenshot no error is showed. This is my pattern `{Original FileName} {MediaInfo AudioLanguages:IT+EN}` and with last develop build the red error (check top post) is gone .

Where did you get errors?

**Comment by ThibaultNocchi** [comment]
Oh my bad, there's no error but the result filename is only `.S01E01`, and resulting in Jellyfin not catching the file ^^

**Comment by Bazzu85** [comment]
> Oh my bad, there's no error but my problem is the resulting filename is only `.S01E01`, and resulting in Jellyfin not catching the file ^^

So the problem is in the renaming/import process.
BTW my pattern `{Original FileName} {MediaInfo AudioLanguages:IT+EN}` works. Where there's italian and english the words  [IT+EN] are appended. In the other scenarios nothing is puttend in the destination file name..
I suggest you to open a new issue so @markus101 can dig into..

**Comment by ThibaultNocchi** [comment]
You're right, will do. Thanks! :)
