### ISSUE TITLE
Keep the watched status in Jellyfin also when a new episode version is downloaded

### ISSUE THREAD

**Issue by lettore** [Sonarr/Sonarr#5008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When Sonarr download a new version with better quality or language it doesn't keep the seen status on Jellyfin, also if Jellyfin is correctly setup in Connect section.

### Describe the solution you'd like

When Sonarr download a new version with better quality or language it should check if the episode is already seen in Jellyfin and then after the file replacement it should update in Jellyfin the status in already seen.

### Describe alternatives you've considered

None

### Anything else?

No

**Comment by bakerboy448** [comment]
Sonarr does not control what jellyfin marks or doesn't make as watched. It sounds like jellyfin does not properly handle file replacements and you should reach out to them for support.

**Comment by markus101** [comment]
Baker is correct, this isn’t something Sonarr will deal with.
