### ISSUE TITLE
Ignore NCOP, NCED and OVA filenames when importing series from existing Library or Indexers.

### ISSUE THREAD

**Issue by mizz141** [Sonarr/Sonarr#5009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Sonarr currently has issues with "NCOP", "NCED" and "OVA" files when importing libraries, these files usually get recognized as invalid files (preventing import) or get marked as having every episode inside them (preventing import)

### Describe the solution you'd like

My solution would be to add a feature that allows "words to ignore" where the user can specify certain words (or even regex) that tells sonarr to ignore such files, every user would then be able to individually adjust the words they want to ignore, titles with ignored words will then be excluded from the import process.

The advantage of this solution would be an easier more streamlined import process for Anime users with the Disatvantage being more time taken up in development of the feature.

### Describe alternatives you've considered

An alternative would be almost the same as the above, just that the user wouldn't be able to specify ignored words themselves, rather them being pre-programmed into sonarr. 

The Advantage of this solution would be less work on the development side, but also increases the risk of issues significantly.

### Anything else?

Attached are a few images describing the above issue, NCOP and NCED files get marked as unable to import, while OVA files are broken in their entirety.

![sonarr_2](https://user-images.githubusercontent.com/20839616/166148776-16785561-7527-444f-be0f-3a8a612855a6.png)
![sonarr_1](https://user-images.githubusercontent.com/20839616/166148779-6535336e-c55b-4b8c-8554-1e182bba7cef.png)
![sonarr_3](https://user-images.githubusercontent.com/20839616/166148781-fdb1793d-5829-416b-a186-9456af2728fb.png)

**Comment by bakerboy448** [comment]
Your invalid episodes do not contain any season/episode or episode information.  That's agnostic from the terms you've mentioned

**Comment by markus101** [comment]
Sonarr can’t import files it cannot parse and in the event of it parsing something it thinks is incorrect it won’t import as well, allowing the user to correct it.

Ignoring these terms wouldn’t change that behaviour.
