### ISSUE TITLE
Add "Episodes Monitored" Column to Series > Table View

### ISSUE THREAD

**Issue by megasquid** [Sonarr/Sonarr#5012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not a problem per se.  I'm trying to reduce the number of episodes that I have monitored to prevent older series from getting upgraded with every new release.  But I still want to keep the series monitored in case there's a new season / revival.  I just want to go un-monitor all the existing seasons in a show once I've verified they're good quality.  Having a way to display the number of episodes monitored will help me do this.  (e.g. I don't need to monitor all 27 seasons of The Daily Show; I only monitor the latest season.)

### Describe the solution you'd like

Add a column that shows the number of episodes monitored in a series, similar to the "Episode Count" column that already exists.

### Describe alternatives you've considered

Going into each of the 464 series I'm currently monitoring and looking to see if I've already un-monitored old seasons.

### Anything else?

Negative.

**Comment by PearsonFlyer** [comment]
You want the Season Pass option. It's exactly what you're looking for.

**Comment by megasquid** [comment]
So it is, everything and more!  Thanks :)
