### ISSUE TITLE
Override download directory

### ISSUE THREAD

**Issue by gemorgan** [Sonarr/Sonarr#5014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Yes, sonarr can't pick up deluge downloads when deluge's view of the download path isn't exactly the same a sonarr's view. I know this has been discussed and the responses were always why would you want this. Here's the case. My deluge does more than just sonarr stuff. I have a deluge folder tree and a /data path points to the top level. Sonarr's /data points to subfolder in that tree because I don't want people using sonarr to have access to the other branches in the tree when they press the manual import button. To be clear, the folder structure from deluge container standpoint is /xxx/other/incomplete and /xxx/home/sonarr, while the root /data folder in the sonarr container points to /xxx/home/, under which there's a sonarr, radarr, lidarr etc folder that the labels move to. So in deluge the download folder path is /data/home/sonarr but in sonarr the path is simply /data/sonarr.

### Describe the solution you'd like

Be able to specify in sonarr where the download path is. If it's not specified, use the current scheme.

### Describe alternatives you've considered

Considered having deluge have a /data and /data1 but then they appear as two separate filesystems to the container and as such the moves require a full copy and then delete instead of a simple file table change. You can't hardlink across filesystems either. If deluge downloads say 10 videos sonarr requested, each at 5GB, the time to perform that transfer of 50GB across filesystems is significant in time and I/O resources. I also thought to install another container of deluge but I don't have much resources to begin with on this little system. 

### Anything else?

I don't see a way around either having a full copy/delete instead of a move and still have sonarr viewing ONLY the sonarr side of the folder tree.

**Comment by bakerboy448** [comment]
This is covered with remote path mapping.
