### ISSUE TITLE
Show Unknown Series Items Not Retained

### ISSUE THREAD

**Issue by silverbullettruck2001** [Sonarr/Sonarr#5016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I uncheck the `Show Unknown Series Items` checkbox on the `Table Options` menu from the `Activity>Queue` screen it does not save between sessions.  So if I set it, and then close the browser window and go back to it, it is now checked again even though I previously had set it to unchecked.  Can this setting be retained or can this option be configured on the `Settings` area?

### Expected Behavior

I would expect that the `Show Unknown Series Items` checkbox setting would be retained once set.

### Environment

```markdown
- OS: Ubuntu 20.04.4
- Sonarr:3.0.8.1507
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

There's nothing to trace on this.

### Anything else?

![image](https://user-images.githubusercontent.com/26559157/167266859-7e12b4db-0328-49ec-a339-a0cbe60988b7.png)

**Comment by bakerboy448** [comment]
This is stored in your local browser storage. Presumably something is wiping your cache and local storage between sessions

**Comment by markus101** [comment]
Baker is correct, this is related to local storage, make sure you're not clearing things when the browser closes. If you need assistance troubleshooting, please use one of our support channels.
