### ISSUE TITLE
Ability to specify Release Profiles per Quality Groups for each Quality Profile

### ISSUE THREAD

**Issue by Metropolis76** [Sonarr/Sonarr#5018]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe

N/A - No current problem. 

### Describe the solution you'd like

For me, and potentially many users, I use one single release profile which upgrades my episodes to my specific requirements. 

My idea is for Release profiles to be specific to quality groups. Eg.: one main Quality profile which may have 2 quality groups inside.(4K-720p WEB-DL/Rip and 4K-720p BluRay for example). 2 of these should take requirements from Release Profile 1 whilst the other takes requirements from Release Profile 2. 

This allows for users to download WEB-DL/Rip(s) from a specific encoder whilst their BluRay upgrades come from a different encoder all without having to create another Quality Profile and manually change shows to use that one. 

This also means that BluRay season packs won’t be downloaded twice just because the one it really wants wasn’t out at that point. 

### Describe alternatives you've considered

Creating multiple Profiles and manually changing shows which their current seasons have ended. And then changing back once a new season begins. 

### Anything else?

N/A

**Comment by markus101** [comment]
We do not have plans to link release profiles to specific qualities/groups of qualities though you may be able to do this with REGEX already.
