### ISSUE TITLE
Point to WikiArr for TitleSlug error

### ISSUE THREAD

**Issue by sevospl** [Sonarr/Sonarr#5020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When trying to add another show that happens to have same title as another one but not include a year, it will fail and throw the following error:

```
Path is already configured for another series

Title slug 'brotherhood' is in use by series 'Brotherhood'
```

### Describe the solution you'd like

The idea is to point a user to WikiArr, specifically this URL: https://wiki.servarr.com/sonarr/faq#title-slug-in-use 

This way further confusion could be avoided so that the user can know right away what to do, instead of having to go to Discord/elsewhere and ask for help with it.

### Describe alternatives you've considered

No alternatives.

### Anything else?

Nope.

**Comment by xfouloux** [comment]
i opened an issue at TVDB, can't have both tvshow :/

#TVDB-857831

https://support.thetvdb.com/tickets.php?id=12910

**Comment by xfouloux** [comment]
TVDB answer is :

There is no reason to change the URL slug for the Netflix series as it currently reflects the title in the series' original language.

what do we do in that case ?

Thx

**Comment by markus101** [comment]
They've since changed the Netflix series to include the year, which is what they should have done to begin with, because unless they've changed their rules, they don't allow duplicate titles, regardless of the original translation.
