### ISSUE TITLE
Renaming: Choose default language or add option to always display english

### ISSUE THREAD

**Issue by ChaosMarc** [Sonarr/Sonarr#5023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When choosing {MediaInfo AudioLanguages} for multi language releases everything is fine. Even for releases with a non English language it works as expected but it leaves out the [xx] string for english only releases (see https://github.com/Sonarr/Sonarr/issues/2593). {MediaInfo Full} prints out this information but leaves out others like {MediaInfo AudioChannels} instead.

Consider this setup: I don't use Sonarr to download shows but only to organize and rename them. After renaming I move them manually to external hard drives so Sonarr is configured NOT to quality upgrade. I only want releases in a non English language (German in my case). As I really want to see the AudioChannels in the filename and really don't care about subtitles I can't use {MediaInfo Full} and have to use a custom episode format (in my case `{Series TitleYear} - S{season:00}E{episode:00} - {Quality Title} {MediaInfo VideoCodec} {MediaInfo VideoDynamicRangeType} - {MediaInfo AudioLanguages} {MediaInfo AudioChannels} {MediaInfo AudioCodec}`). This is almost fine (as I don't need the [DE] information) for multi language and German only releases but for English only releases I loose the information which language is included in the filename. A left out String is really much harder to spot (and not searchable) than a "[EN]" one. If I accidently downloaded an English only release I probably will never find out until I start watching the episode.

### Describe the solution you'd like

Let us choose a default language **just for renaming** so we can decide for which language the [xx] string should be left out.

E.g.:
- Default setting: English is the default language:
<table>
<tr>
	<td>Show.XYZ.S01E01.1080p.WEB.x264-GROUP
	<td>Show XYZ - S01E01 - 1080p WEB-DL x264 - 5.1 AC3
<tr>
	<td>Show.XYZ.S01E01.GERMAN.1080p.WEB.x264-GROUP
	<td>Show XYZ - S01E01 - 1080p WEB-DL x264 - [DE] 5.1 AC3
<tr>
	<td>Show.XYZ.S01E01.GERMAN.DL.1080p.WEB.x264-GROUP
	<td>Show XYZ - S01E01 - 1080p WEB-DL x264 - [DE+EN] 5.1 AC3
</table>

- Custom setting: German is the default language:
<table>
<tr>
	<td>Show.XYZ.S01E01.1080p.WEB.x264-GROUP
	<td>Show XYZ - S01E01 - 1080p WEB-DL x264 - [EN] 5.1 AC3
<tr>
	<td>Show.XYZ.S01E01.GERMAN.1080p.WEB.x264-GROUP
	<td>Show XYZ - S01E01 - 1080p WEB-DL x264 - 5.1 AC3
<tr>
	<td>Show.XYZ.S01E01.GERMAN.DL.1080p.WEB.x264-GROUP
	<td>Show XYZ - S01E01 - 1080p WEB-DL x264 - [DE+EN] 5.1 AC3
</table>

### Describe alternatives you've considered

Include [EN] in the filename when renaming English only episodes with {MediaInfo AudioLanguages} or make it configurable.

E.g.:
<table>
<tr>
	<td>Show.XYZ.S01E01.1080p.WEB.x264-GROUP
	<td>Show XYZ - S01E01 - 1080p WEB x264 - [EN] 5.1 AC3
<tr>
	<td>Show.XYZ.S01E01.GERMAN.1080p.WEB.x264-GROUP
	<td>Show XYZ - S01E01 - 1080p WEB x264 - [DE] 5.1 AC3
<tr>
	<td>Show.XYZ.S01E01.GERMAN.DL.1080p.WEB.x264-GROUP
	<td>Show XYZ - S01E01 - 1080p WEB x264 - [DE+EN] 5.1 AC3
</table>

### Anything else?

This would be greatly improved by detecting the audio languages via MediaInfo instead of just using the filename. See https://github.com/Sonarr/Sonarr/pull/4737 but sadly @NicolasFerec hasn't been around for a while. Would it be possible to take over his PR and open another one with his code as a base?

**Comment by bakerboy448** [comment]
> MediaInfo Full/AudioLanguages/SubtitleLanguages support a :EN+DE suffix allowing you to filter the languages included in the filename. Use -DE to exclude specific languages. Appending + (eg :EN+) will output [EN]/[EN+--]/[--] depending on excluded languages. For example {MediaInfo Full:EN+DE}.

does this existing DJ functionality  not do what you want?

**Comment by ChaosMarc** [comment]
> does this existing functionality not do what you want?
In regards to showing [EN] for English only releases, yes. BUT despite of being named "Full" it doesn't print out all available information. Especially the audio channels are missing from "Full" but can be displayed be using {MediaInfo AudioChannels}. Another "solution" would be to fix "Full" to really show all information available. But as I already wrote using Full is not really a feasible solution for me as I don't want to see the subtitle information in the filename.

**Comment by markus101** [comment]
Full shows a good chuck of the information that was available for renaming at the time, but we're not going to change it to include more or less at this time.

That functionality isn't limited to `{MediaInfo Full:DE+EN}`, you can use `{MediaInfo AudioLanguages:DE+EN}` as well.

No plans to set a default language for renaming though.

**Comment by ChaosMarc** [comment]
@markus101 sorry to comment in an already closed issue but I have the feeling that I couldn't explain myself correctly. Please look at the following tests I did with a EN only, DE only, DE+EN release:

| Settings  | EN only | DE only | DE + EN |
| ------------- | ------------- | ------------- | ------------- |
| {MediaInfo AudioLanguages} |  | [DE] | [DE+EN] |
| {MediaInfo AudioLanguages:DE+EN} |  | [DE] | [DE+EN] |
| {MediaInfo AudioLanguages:DE+EN+} |  | [DE] | [DE+EN] |
| {MediaInfo AudioLanguages:DE+} | [-] | [DE] | [DE+-] |
| {MediaInfo AudioLanguages:EN+} |  | [-] | [EN+-] |
| ------------- | ------------- | ------------- | ------------- |
| {MediaInfo Full} | EAC3 | DTS[DE] | EAC3[DE+EN] |
| {MediaInfo Full:DE+EN} | EAC3 | DTS[DE] | EAC3[DE+EN] |
| {MediaInfo Full:DE+EN+} | EAC3 | DTS[DE] | EAC3[DE+EN] |
| {MediaInfo Full:DE+} | EAC3[-] | DTS[DE] | EAC3[DE+-] |
| {MediaInfo Full:EN+} | EAC3 | DTS[-] | EAC3[EN+-] |
| ------------- | ------------- | ------------- | ------------- |
| Not possible / What I want | [EN] or [-] | [DE] | [DE+EN] |

**Am I missing a configuration that does want I want?** I would have thought that {MediaInfo Full:DE+EN+} would do exactly what I want.

> No plans to set a default language for renaming though.
Does this mean that if I created PRs with any of the following functionalites they would be merged or not?
- Create a UI setting to define a default language which. Default: English
- Create a UI setting to NOT skip [EN] if it's the only language. Default: Disabled
- Add {MediaInfo AudioChannels} information to {MediaInfo Full} (in front of the subtitle languages)

**Comment by Taloth** [comment]
In `{MediaInfo AudioLanguages}`, English gets special treatment.
To get the desired behavior, use `{MediaInfo AudioLanguagesAll:DE+EN}` instead.

> Create a UI setting to define a default language which. Default: English

I don't think we need an option to change that atm, given the alternatives, but if there's more interest we can reconsider.

> Create a UI setting to NOT skip [EN] if it's the only language. Default: Disabled

Use AudioLanguagesAll as mentioned, no option needed

> Add {MediaInfo AudioChannels} information to {MediaInfo Full} (in front of the subtitle languages)

Full is simply a shorthand of the concatenation of multiple other individual options. 
`{MediaInfo Full}` -> `{MediaInfo VideoCodec} {MediaInfo AudioCodec}{MediaInfo AudioLanguages} {MediaInfo SubtitleLanguages}`, so ppl can add AudioChannels where they like.
So there's no reason to change Full itself.

**Comment by ChaosMarc** [comment]
@Taloth thank you so much ❤️ AudioLanguagesAll is almost exactly what I needed! Skipping [DE] would be better for my taste but I can happily live with this. As I now have a working alternative there is no need for any PRs from my side. Have a great day!
