### ISSUE TITLE
Whole season manual imports from manual NZB copy, then delete, instead of hard link

### ISSUE THREAD

**Issue by dodexahedron** [Sonarr/Sonarr#5026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I manually added an nzb for a whole-season video file for a series directly to sabnzbd, because sonarr couldn't find it.
I named it appropriately, so Sonarr noticed it and tracked progress.
After the download was done, it did not auto-import, because it was a whole-season file, for a season with multiple episodes.
I hit the manual import button in the queue in Sonarr, selected all episodes for the appropriate season, and hit import.
Then, Sonarr proceeded to _copy_ the file to the season folder, before deleting it from the completed download folder, rather than hard-linking and then deleting, like it normally does. As it was a multi-gigabyte file, that took some time.

This behavior is easily repeatable, and I did it for 5 more seasons.

### Expected Behavior

Regardless of import method, sonarr should respect the settings set in media management. In my case, that would be hard-linking.

### Steps To Reproduce

As described above.
Download an nzb for a whole-season video of a multi-episode season manually.
Import that nzb into your downloader, in a way that sonarr will pick it up.
Once the download is complete and sonarr doesn't automatically import it, manually import from the queue.
Problem reproduced.

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 3.0.8.1507-ls146
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

I'll have to reproduce again to provide logs, if they're wanted.

### Anything else?

.

**Comment by markus101** [comment]
This sounds like Sonarr is importing the file across volume where it can't hard link and for safety reasons copies the file to the destination, verifies then deletes the original.

> I'll have to reproduce again to provide logs, if they're wanted.

They're always wanted and should always be included, save for UI only issues.

**Comment by dodexahedron** [comment]
Will do.It's a single file system, though, and is the same file system that is used if sonarr owns the process from start to finish.

**Comment by markus101** [comment]
Closing, can reopen if additional information indicates an issue.
