### ISSUE TITLE
Maximum size for season pack

### ISSUE THREAD

**Issue by syco** [Sonarr/Sonarr#5031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I want episodes to be max 500mb each, the problem is that when I set this limit in the indexer settings, episodes are downloaded all individually, because season packs are always bigger.
This is a problem because often old shows miss peers for one or two episodes, but would be easily available as season packs.

### Describe the solution you'd like

The limit should be multiplied by the number of episodes when sonarr detects it's a season pack.
So I could set 500mb limit per episodes, and a season pack containing (for example) 10 episodes, would be capped at 5000mb.

### Describe alternatives you've considered

Only solution I can think of is to disable automatic searches and do interactive searches, but it's not viable in the long term.

### Anything else?

Thanks

**Comment by Taloth** [comment]
This is already supported... in Settings->Quality. Those limits are scaled by episode runtime and number of episodes.

Indexer Settings is the absolutely limit per download, mainly to manage download directory limits.
