### ISSUE TITLE
Add ability to automatically search and grab a Incomplete Season Packs if you are missing episodes

### ISSUE THREAD

**Issue by RileyXX** [Sonarr/Sonarr#5032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

**For example:**
- Show.S03.Part1.1080p.x264
- Show.S03.Part2.1080p.x264
- Show.S03.Part3.1080p.x264

**OR:**

- Show.S03.Incomplete.1080p.x264

When I do a search for the show season pack and sort by all I can see these torrents. But when I do a search for missing episodes sonarr doesn't grab these even tho nothing else is available. Is there a way to get sonarr to grab these releases automatically so it can import the episodes I need and delete the rest? Or a manual search and import the only option? This is for a season of a show that's still airing. And there are no induvial episodes listed and no complete season packs available. The only thing available are the Season in parts 1-3 and incomplete season packs. It would be nice to be able to grab these automatically as they come out if you are missing episodes and nothing else is available. Because the only other option is to do a manual search every once in a while for new parts.

### Sonarr's reason for rejection:

`Unable to identify correct episode(s) using release name and scene mappings`

### Describe the solution you'd like

Add an option to allow/disable download for incomplete season packs. It should only download and search incomplete season packs or season parts if you are missing episodes and nothing else is available. Then Sonarr should grab and import the episodes you need and delete the rest. If you are still missing episodes Sonarr should keep searching in other incomplete season packs or parts as they become available. To avoid duplicates Sonarr should note the title of the incomplete season packs you already downloaded and ignore them.

### Describe alternatives you've considered

Only other option is to periodically do a manual search and then import the files manually.

### Anything else?

My original question on reddit https://www.reddit.com/r/sonarr/comments/uvmiwy/is_it_possible_to_get_sonarr_to_download_and/

**Comment by bakerboy448** [comment]
Why is sonarr rejecting those - the red icon by them for manual search should tell you

**Comment by RileyXX** [comment]
> Why is sonarr rejecting those - the red icon by them for manual search should tell you

It says `Unable to identify correct episode(s) using release name and scene mappings`

**Comment by markus101** [comment]
That is accurate, Sonarr doesn't support partial season releases because it has no way to know which episodes are in which part. We're not going to support partial season packs of unknown episodes nor do we have plans to grab season packs and only grab some of the episodes within them.
