### ISSUE TITLE
Add series to the calendar without running any searchs

### ISSUE THREAD

**Issue by gheydon** [Sonarr/Sonarr#5033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

To get a series on the calendar you need to turn on monitoring. Then the series will download once the show has aired. However I want to have a series being displayed on the calendar and the colours being updated to show that the show has aired and then nothing.

I have shows I like on streaming services which I subscribe too and am happy to watch on these there, but I want a centralised place to see everything I want to watch.

### Describe the solution you'd like

A method of doing this is to add a new monitor option which will set the show to be monitored by not downloaded.

### Describe alternatives you've considered

none

### Anything else?

none

**Comment by bakerboy448** [comment]
> monitored by not downloaded.

No plans for any such feature and it is directly contradictory.  Something cannot be monitored AND not monitored at the same time.

Perhaps you can get creative with a must contain release profile combined with tags so those episodes will never be grabbed and always be missing instead.

> To get a series on the calendar you need to turn on monitoring. Then the series will download once the show has aired. However I want to have a series being displayed on the calendar and the colours being updated to show that the show has aired and then nothing.

sonarr is not a calendar tool, that's just an extra feature. There's millions of other calendar specific tools for your purpose.

calendar does not require a series to be monitored for it to show on calendar, just change your filter.
