### ISSUE TITLE
Indicate current “type” of monitoring (all eps, future eps, current season, etc…) especially on mobile. 

### ISSUE THREAD

**Issue by CaptSneeze** [Sonarr/Sonarr#5039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

In iOS, when viewing a currently subscribed series, navigating to More > Series Monitoring, the user is presented with a drop down that shows “No Change”. It would be more helpful to know what this setting is currently set to, so the user can determine if a change is needed/desired. 

### Describe the solution you'd like

Have the initial selection of the drop down menu be what the series monitoring is currently set to, and remove “No Change” from the menu. 

### Describe alternatives you've considered

Show the current setting above the drop down menu. 

### Anything else?

![D77F5100-5E17-47AF-81BF-142329991743](https://user-images.githubusercontent.com/4572350/171049727-e6a1769e-fa59-4bd1-bf18-b7c6a2d9ca1d.jpeg)

**Comment by markus101** [comment]
There is no "current setting" that is applied only at the moment of choosing and then that's it, it is not stored because storing it has no value.

**Comment by CaptSneeze** [comment]
Thanks markus101, I’m sure this is a misunderstanding on my part. Could you explain how then Sonarr knows to continually monitor a series for, for example, “missing episodes” instead of only “future episodes” if there is no stored setting for this?

**Comment by thezoggy** [comment]
think of it as an action not a 'setting'. 
if you were to select none, then it changes all episodes to monitor=false. if you select all episodes then it sets monitoring state to true for all. the others are just presets for convince like only x season or only the first episode 

![firefox_2022-05-30_14-59-49](https://user-images.githubusercontent.com/500882/171053526-67aa7566-3d6c-4e24-a8aa-7609c18aa38b.png)

**Comment by markus101** [comment]
Missing episodes = all episodes that are missing when the option is selected, anything added in the future is also considered missing (once it airs)
Future episodes = all episodes airing after right now, if this setting was persisted, episodes that didn't get an episode file before they aired would be considered in the past and unmonitored.

`No Change` a place holder so something other than a valid value is selected, otherwise the first value would be selected. It could be something other than `No Change`, but that made the most sense for the other fields so it was kept consistent.

**Comment by CaptSneeze** [comment]
I appreciate the answers, though it is still unclear to me how this isn’t a “setting”, but it might be getting into pedantic territory (on my part). I still feel it would be helpful to know if, when a series was added, whoever added it selected to monitor “only first season” instead of “all episodes”.

Using my example, would the little “monitoring flag” next to the series title become un-filled after season 1 was done and all of the files had been downloaded? I believe it would still be indicating that the series is being monitored. The user (me, at least) might have expectations that aren’t aligned with the current monitoring configuration (I’m trying not to use the word “setting” here). 

I’m perfectly willing to accept that I am an internet moron with dumb expectations if that’s the case. It just seems like it would be helpful (maybe just to me) to know the history of this selection for a series.

**Comment by markus101** [comment]
> Using my example, would the little “monitoring flag” next to the series title become un-filled after season 1 was done and all of the files had been downloaded?

No, the only time Sonarr will automatically unmonitor something is episodes and only when `Unmonitor Deleted Episodes` is enabled and the file is deleted.

The one edge case that applies to a couple options is that Sonarr will always monitor a new season, storing the value could resolve that, but that'd require the user to set it after the fact which wouldn't be super intuitive, the better solution would be a per-series setting (monitor new seasons) or some sort of global config with different options, such as always, never, if previous season is monitored, etc.

**Comment by CaptSneeze** [comment]
> The one edge case that applies to a couple options is that **Sonarr will always monitor a new season**…

This helps my particular situation, and was unknown to me. Just to make sure I’m understanding correctly, Sonarr will _always_ monitor for new episodes of a series (unless it’s been told to not monitor that series/season)? If that’s true, everything is making much more sense to me now. So if I select “only first season” for monitoring on a series, and then a week later season 2 start airing, those will still be downloaded too. 

If this understanding is correct, it does make me question what exactly “Future Episodes” means, as I would now expect that those would be monitored no matter what. 

Thanks again for helping me understand. I’m getting there now. :)

**Comment by markus101** [comment]
> So if I select “only first season” for monitoring on a series, and then a week later season 2 start airing, those will still be downloaded too.

Correct, as long as Sonarr was unaware of season 2 existing at the time it was added.

> If this understanding is correct, it does make me question what exactly “Future Episodes” means, as I would now expect that those would be monitored no matter what.

Basically, ignore whatever episodes have already aired, grab anything moving forward, which would apply mid season (useful for watch and delete types) or after the last season ended it'd behave just as it does now.
