### ISSUE TITLE
Custom Filters for "Wanted" list

### ISSUE THREAD

**Issue by markboynz** [Sonarr/Sonarr#5040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have a large library, and my Wanted queue runs to over 2000 pages. I'd love to be able to do a set of custom filters, so that I can Search All on a specific subset. Search on on 50k+ episodes is not feasible, and doing a page at a time is highly laborious with long load times between pages.

### Describe the solution you'd like

The ability to add custom filters to the existing Monitored/Unmonitored filter which appears on the Wanted pages. A replication of the facilities available on the filters page would be sufficient, although being able to also filter on episode title etc would be an excellent edition.

### Describe alternatives you've considered

-

### Anything else?

-

**Comment by markboynz** [comment]
Sorry - prior to posting, had searched and found nothing, but immediately after posting, saw an existing issue. Can't find a way to delete this myself, so closing.

**Comment by bakerboy448** [comment]
https://github.com/Sonarr/Sonarr/issues/3657
