### ISSUE TITLE
Custom filter OR operator

### ISSUE THREAD

**Issue by FredHaa** [Sonarr/Sonarr#5044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I currently use a custom filter to show upcoming shows using 'Next airing in the next 3 months'.
However, if the show airs and Sonarr for some reason doesn't download the show it is no longer shown, as there is no option to also show missing shows while showing the next airing shows.

### Describe the solution you'd like

This and many other problems would be fixed by being able to select whether OR or AND should be used between filters in a custom filter.

### Describe alternatives you've considered

None (an OR operator seems to be a very simple yet effective solution)

### Anything else?

![OR_filter](https://user-images.githubusercontent.com/6875946/171565861-8dbc4251-e524-423d-aed5-759ab9c965f4.png)

Here is a mockup of how the UI could look. The box with OR is of course switchable to AND.

**Comment by markus101** [comment]
This isn’t something we have short term plans for support. Tagging to revisit later.

**Comment by ProfessorCha0s** [comment]
This would definitely be useful for something like filtering on "x265 OR hevc" for a title for instance. Very basic logic flow and would be much easier to filter.

**Comment by Roxra** [comment]
Would love this, would come in handy so I don't have to keep swapping filters.

**Comment by ljlongwing** [comment]
+1.  My use case is an Upcoming OR Missing Episodes filter....currently two separate filters that I must switch between...but with an OR operator I would be able to have both in the same filter

**Comment by zachauker** [comment]
+1 would love this feature for looking for a specific tag in a release that may have different capitalization/formatting.

**Comment by professionaltart** [comment]
![image](https://github.com/Sonarr/Sonarr/assets/28383689/c869f7ed-8c6f-49bf-9fb7-1217e2084e40)
It looks like it may now be doing a version of this this - in a custom filter if you enter two values for a field, it inserts an OR between them (eg in the example pictured, I type x265, press enter, then HEVC and enter, it shows both with the OR conditional, working as @ProfessorCha0s requested at least.  Not quite like OP wanted, tho'.

**Comment by derekantrican** [comment]
@professionaltart Yeah, I think that's how it's always worked - for a single property (eg "Status" for me) you can have it match multiple values (eg "Continuing OR Upcoming" for me). The ask from OP is to allow "OR" between multiple properties

**Comment by Zarudd** [comment]
Adding a +1 to this.

Would make series management so much cleaner. While I'm "monitoring" shows that are currently running as best I can, some shows are revived (or changed back to continuing) after being tagged as ended. So, I remove them from Monitoring and then, since they won't show up in my Monitoring filter after they are changed back to continuing they can be lost in the shuffle.

Having an OR operator would allow me to say I want a filter for anything that I'm monitoring, OR anything which is continuing and would solve the above problem.

I really wish this would be reconsidered as a future implementation.
