### ISSUE TITLE
RSS Sync - Duplicate downloads

### ISSUE THREAD

**Issue by k29t59dh** [Sonarr/Sonarr#5045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After a successful download sonarr will redownload the same torrent, sometimes several times.

Note the same _Name_, _Indexer_, _Info URL_, and _Publish Date_
<img width="1089" alt="real time 1" src="https://user-images.githubusercontent.com/76966241/172011382-f9386a85-a708-49cd-83c2-741ba8ae9bcc.png">
<img width="952" alt="real time 2" src="https://user-images.githubusercontent.com/76966241/172011384-209aca7e-10c5-43c5-92c4-eaddccb1ea6e.png">
<img width="967" alt="real time 3" src="https://user-images.githubusercontent.com/76966241/172011389-d2224516-2234-482d-8ac6-7de1f96ccb73.png">
<img width="948" alt="real time 4" src="https://user-images.githubusercontent.com/76966241/172011394-fc571736-6e01-4671-adc6-ded28b1952a8.png">

### Expected Behavior

Don't redownload the same torrent?

### Environment

```markdown
- OS: unRAID/Slackware
- Sonarr: 3.0.8.1507
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

Trace logs enabled after 2nd download. I'll keep it enabled so in the next instance I catch all downloads.
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/8838120/sonarr.trace.txt)
[sonarr.trace.0.txt](https://github.com/Sonarr/Sonarr/files/8838121/sonarr.trace.0.txt)

### Anything else?

Nothing else.

**Comment by bakerboy448** [comment]
doesn't look like a bug

The back to back grabs without an import indicate that sonarr no longer saw the release in your download's client queue and thus never imported it.

it looks like you have a preferred word loop going on where the release matches preferred words, but not the downloaded file. Or sonarr is losing track of the on disk file and the preferred words are not in the file name.

or you have a release profile set to only a specific indexer and ignored the help text saying this would happen

**Comment by k29t59dh** [comment]
> or you have a release profile set to only a specific indexer and ignored the help text saying this would happen

Well now I feel stupid. Sorry about that.
<img width="497" alt="real time 5" src="https://user-images.githubusercontent.com/76966241/172013172-708d3b6b-384a-4951-acc6-31ed29a65a88.png">
