### ISSUE TITLE
Series Added Notification

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#5046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Series Added Notification

Radarr Commit https://github.com/Radarr/Radarr/commit/f890aadffa5ae579bcf65abdcf3e3948837084a9

### Describe the solution you'd like

Series Added Notification

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by Qstick** [comment]
Dupe #3637
