### ISSUE TITLE
can't have 2 tvshows with same name

### ISSUE THREAD

**Issue by Nexius2** [Sonarr/Sonarr#5050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, wanting to add missing (2003) but I have an error message "Title slug 'missing' is in use by series 'Missing'"
I already have a tvshow from 2020 with same name I guess sonarr doesn't like it.
I can't add missing from 2021 for the same reason.

### Expected Behavior

I was expeting to be able to add multiple tv shows with same name and different year.

### Environment

```markdown
- OS: unraid
- Sonarr: latest
- Docker Install: yes
- Using Reverse Proxy: no
- Browser:firefox
```

### What branch are you running?

Main

### Trace Logs?

2022-06-06 19:59:05.5|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- TitleSlug: Title slug 'missing' is in use by series 'Missing'

### Anything else?

thanks

**Comment by markus101** [comment]
This is covered in the [FAQ](https://wiki.servarr.com/en/sonarr/faq#title-slug-in-use) in the wiki.
