### ISSUE TITLE
Automatically determine series type

### ISSUE THREAD

**Issue by triesmon** [Sonarr/Sonarr#5051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When adding an anime show, the default series type value is set incorrectly to standard. If the value isn't changed, this can lead to no search results and user frustration without knowing what's going wrong. 

### Describe the solution you'd like

Sonarr should make a best guess about the correct series type to use. When the add show dialog is open, run a search with the connected indexers against the show, look at any returned episodes, and make a best guess at the proper series type value to initially provide. Or use any other relevant metadata (e.g. genre) to make an informed suggested default. If a suggest default cannot be determined, sonarr could then default back to standard. 

### Describe alternatives you've considered

Move the series type combobox to the top and/or force the user to suggest a value. Since series type is the easiest mistake to make to get no results, it should be more prominently featured in the dialog. 

### Anything else?

Overseerr is able to determine the series type, so looking at their algorithm may be useful. 

This issue has been previously suggested (https://github.com/Sonarr/Sonarr/issues/796) but closed and locked due to "lack of interest," but I think the issue should be left open for more than 2-3 months to gauge interest.

**Comment by bakerboy448** [comment]
Series type has nothing to do with the series and everything to do with how the series is being released by one's indexers.  In some cases, a series may be both standard and anime depending on the groups being targeted.

I'd make a large bet that Overseerr's guessing is not always correct. 

https://wiki.servarr.com/sonarr/faq#whats-the-different-series-types

**Comment by Qstick** [comment]
> I'd make a large bet that Overseerr's guessing is not always correct.

We shouldn’t let being correct 100% of the time stop us from being correct 80 % of the time if we are correct 50% of the time now. Seems like a stupid argument. I’d agree we could do something better here, but it’s going to rely on xem or skyhook changes.

**Comment by markus101** [comment]
The problem with guessing at what it might be is people will just automatically accept whatever is there, same as they do when importing series and Sonarr picked the wrong series. A similar issue exists when storing the default, but there is going to be a large percentage of people that only care about one series type or only care about it most of the time.

**Comment by markus101** [comment]
The previous issue was open for more than 5 years and the amount of interest was low. This is something we might tackle eventually, but no immediate plans to do so.
