### ISSUE TITLE
Multiple Paths (new twist)

### ISSUE THREAD

**Issue by obsidiangroup** [Sonarr/Sonarr#5057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I realize there have been other requests for this:
[https://github.com/Sonarr/Sonarr/issues/1016](https://github.com/Sonarr/Sonarr/issues/1016)

[https://github.com/Sonarr/Sonarr/issues/1762](https://github.com/Sonarr/Sonarr/issues/1762)

[https://github.com/Sonarr/Sonarr/issues/1693](https://github.com/Sonarr/Sonarr/issues/1693)
[Multiple directories #2374](https://github.com/Sonarr/Sonarr/issues/2374)

Using symlinks isn't really a solution especially if you're running Sonarr within a container.  If you create the symlink outside of the container, the paths don't match up (unless you have the paths on the host and container exactly the same), and creating a symlink within the container causes path problems outside of the container.

i.e. (symlink created outside of the container)
Say your media is /nas/media-1/tv/Hawaii Five-0 and /nas/media-2/tv/Hawaii Five-0.  If you create a sym link:
`ln -s /nas/media-1/tv/Hawaii Five-0/Season 1 /nas/media-2/tv/Hawaii Five-0/Season 1`
within the container, it cannot follow the path if you have `/nas/media-1/tv` mounted within the container as `/tv`, etc.  Inside the container, it will try to follow the complete path of /nas/media-1/tv/Hawaii Five-0/Season 1.

The opposite will be if you make the symlink within the container.  While sonarr will properly see the directory and follow, it could cause issues outside of the container, though this could probably be ignored unless you have other scripts / programs that will error out on invalid symlinks.

### Describe the solution you'd like

Since there are no plans to add support for a series having multiple directories, could there be an option to just mark a season as available?  I understand you can mark specific seasons as unmonitored, or only monitor new seasons but this doesn't exactly solve all problems. I'd like to be able to make seasons / episodes as available, so if you are missing a episodes across multiple seasons (say 1 episode per season) you can just have Sonarr look for all missing episodes and send them to your download client, instead of having to do each episode individually or Sonarr going and grabbing the entire season again.

### Describe alternatives you've considered

While UnionFS or other drive pooling methods is an option, it's not viable for all environments.  Creating Symlinks, as stated above can technically work, but using containers when the paths are not exactly the same causes broken links on one side or another.

### Anything else?

Even going through and manually marking each episode monitored/unmonitored could work, but this does not mark an item as available or not.  But the same way individual episodes can be marked monitored/unmonitored, can work for available/not available.

**Comment by thezoggy** [comment]
generally you handle this outside of sonarr, ideally at the os level.

how to accomplish this, differs for different os/setups.
for some people that means combing hdd storage via a nas and using that common share point. 
for some its just using raid or mergerfs or something of the like. in windows you can do junction points (symlink at folder level) but overall sonarr doesnt care it just needs a path to use.

**Comment by markus101** [comment]
We do not have plans for a separate state in Sonarr that indicates the files are available, but in a location Sonarr doesn't know about, at the end of the day that would be the same as unmonitoring them with some extra work. Placeholder files + unmonitoring is probably the best course of action, unmonitoring being important because you don't want Sonarr to start upgrading placeholder files.

**Comment by obsidiangroup** [comment]
Right, I specifically said that using mergerfs/unionfs is not a feasible option.  RAID has nothing to do with it, especially if you are using a different datasets/volumes.  Just because one has a RAID does not mean you can arbitrarily increase the size of the volume.  Again, at the OS level, under Linux / FreeBSD, I laid out why symbolic links would not work.  

The problem with "solutions" like MergerFS is, for instance, depending on what option you use, the same issue with disk space can happen once you hit the mindiskspace setting.  Or, files are just stored at random across however many drives are part of the pool.  MergerFS has its uses, but it's not the save-all solution.  And honestly, I do not want to use MergerFS across my NAS.

Symbolic links within the container itself will work, just causes invalid paths outside of the container, and, like I stated initially, unless you use the same mapping inside/outside the container, there's no avoiding this.

**Comment by obsidiangroup** [comment]
>  Placeholder files + unmonitoring is probably the best course of action, unmonitoring being important because you don't want Sonarr to start upgrading placeholder files.

DIdn't think of placeholder files.  Thanks, closing again.
