### ISSUE TITLE
Include instance name and external url in webhook notification and custom script env vars

### ISSUE THREAD

**Issue by onedr0p** [Sonarr/Sonarr#5059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have 2 Sonarr applications running, one for HD and another for UHD. I have a webhook and custom script set up to sending a notification to services and scripts where I'd like to know what instance of Sonarr is sending the webhook.

### Describe the solution you'd like

Include the `InstanceName` from the configuration in the webhook payload.

### Describe alternatives you've considered

Creating different webhook endpoints for each instance on my service, however it would be nice to have each Sonarr consume the same webhook.

### Anything else?

N/A

**Comment by Qstick** [comment]
@onedr0p did you want to open this back up against dev now?

**Comment by onedr0p** [comment]
Yeah, it's on my list of things to get to 😄 I'll need to start that PR from scratch though since it's not that large of a change.

**Comment by onedr0p** [comment]
@Qstick PR opened https://github.com/Sonarr/Sonarr/pull/5199
