### ISSUE TITLE
Configuration option for external Sonarr URL

### ISSUE THREAD

**Issue by onedr0p** [Sonarr/Sonarr#5060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When using notification services like Pushover, Discord, Webhook, Custom Script and many others it would be nice if you could link to the series URL from the notification app itself. This would only be possible if sonarr was aware of the the true external url is (e.g. https://sonarr.domain.tld).

### Describe the solution you'd like

In the application settings have a setting for configuring an external URL (e.g. https://sonarr.domain.tld) that notifications can use to link back to Sonarr.

This can provide rich notifications like with Pushover

https://media.discordapp.net/attachments/728283989604958258/987336382995394621/Screenshot_20220617-084157_Pushover.png

I would be able to click View series in Sonarr and be taken directly to the series in Sonarr.

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by bakerboy448** [comment]
Closed by https://github.com/Sonarr/Sonarr/pull/5063 ?

**Comment by markus101** [comment]
Yup, thanks!
