### ISSUE TITLE
A few feature suggestions / improvements

### ISSUE THREAD

**Issue by GregoryGHarding** [Sonarr/Sonarr#5067]
### Is your feature request related to a problem? Please describe

MANUAL IMPORT (INTERACTIVE):
- if a download is not accepted for whatever reason (not an upgrade, no match, sample, etc), there is no method to remove said downloads from the server, leading to a messy downloads folder and unnecessary bloat/space occupied

ACTIVITY QUEUE:
- some downloads get stuck in "Downloading Metadata" and are equalivant to stalled, however they currently show as queued in sonarr, and are indistinguishable from queued. leading to bloat and delay in download client and manual required intervention in order for sonarr to proceed finding a suitable replacement

### Describe the solution you'd like

MANUAL IMPORT (INTERACTIVE):
- include option to delete the selected downloads in order to free space and prevent stalling of imports.

ACTIVITY QUEUE:
- add category for "downloading metadata" so that user intervention is streamlined in such a way as a stalled download notice is displayed

### Describe alternatives you've considered

manual user intervention

### Anything else?

thanks for reading, and you're all doing an awesome job.

**Comment by markus101** [comment]
> if a download is not accepted for whatever reason (not an upgrade, no match, sample, etc), there is no method to remove said downloads from the server, leading to a messy downloads folder and unnecessary bloat/space occupied

These can be removed from Activity: Queue. Currently we do not have plans to add a delete function directly to Manual Import.

> some downloads get stuck in "Downloading Metadata" and are equalivant to stalled, however they currently show as queued in sonarr, and are indistinguishable from queued. leading to bloat and delay in download client and manual required intervention in order for sonarr to proceed finding a suitable replacement

Downloading metadata is a valid status, we do not have plans to have a separate status for these, if you're seeing a high number of these you might need to increase the minimum number of seeders because the indexer isn't reporting accurate numbers.
