### ISSUE TITLE
Stopping running tasks / better scheduling of tasks

### ISSUE THREAD

**Issue by ScuttleSE** [Sonarr/Sonarr#5069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The "Refresh series" is scheduled to run every 12 hours, in my setup that execution takes _hours_, and all processing of new downloads is halted until that task has been executed. Is there a way to cancel the task, and set it to run at a specific time, instead of "every 12 hours". Restarting Sonarr does nothing, it just restarts the scan...

### Describe the solution you'd like

An option to stop a running task, and an option to select a specific time when tasks are executed crontab-style

### Describe alternatives you've considered

n/a

### Anything else?

n/a

**Comment by markus101** [comment]
Can re-open if sufficient information indicates an issue.
