### ISSUE TITLE
Wrong run time used to grab some new episodes

### ISSUE THREAD

**Issue by brij1234** [Sonarr/Sonarr#5072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I noticed that Stranger Things has different runtimes for some episodes (S4E9). This causes the automatic release to be rejected:
_7.5 GB is larger than maximum allowed 6.5 GB (for 51min)_

The automatic search is looking at default runtime for the show? 51 minutes? The real runtime of that episode is [150 minutes ](https://thetvdb.com/series/stranger-things/episodes/8852957).

### Expected Behavior

The runtime used for matching a release needs to be per episode. Not the default runtime for the show.

### Steps To Reproduce

1. find a show with some episodes having different runtimes
2. do an interactive search for the episode
3. releases will be rejected based on the wrong runtime

### Environment

```markdown
- OS: Windows 10
- Sonarr: 3.0.8.1507
- Using Reverse Proxy: No?
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/9041367/sonarr.trace.txt)

This is a shortened version of the log file. I have kept the full trace log file if you need it.

### Anything else?

![image](https://user-images.githubusercontent.com/9251787/177198308-98752ed2-198c-42d3-8f6e-91945d1d3db9.png)

**Comment by markus101** [comment]
Sonarr doesn’t have runntimes per episode, only per series, this is covered by https://github.com/Sonarr/Sonarr/issues/3482

**Comment by brij1234** [comment]
@markus101 I'm new here. What is skyhook? Is it an open source?

**Comment by markus101** [comment]
Skyhook is the metadata proxy that we run for Sonarr, it is not open source. Sonarr won't have run times per episode until after Skyhook switches to TheTVDB API v4.
