### ISSUE TITLE
MiniDNLA Metadata File Generation

### ISSUE THREAD

**Issue by bdovaz** [Sonarr/Sonarr#5076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Depending on the media server, it expects the file names to have a certain name.

In my case (MiniDLNA on RPI) it expects for example in the case of videos that the exact name of the video matches.

### Describe the solution you'd like

Allow metadata editing forms to have fields to customize the format of the file names to be generated.

Example XBMC.

I understand that the options would need to be added here:

https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadataSettings.cs

And use them here:

https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs

### Describe alternatives you've considered

There are not beyond having a custom script that modifies the filenames afterwards but it is not useful because it is a process that requires manual execution of a script.

### Anything else?

NA

**Comment by markus101** [comment]
Please explain the problem further, you’ve provided limited information on the issue.

What format of the file name is expected?
Is this only for images or also the metadata text files?
What exactly is the format it expects?
Why an option to change the file name instead of a different implementation?

Part of metadata files logic is to link those files back to the implementation that created them/should manage them, if file names are arbitrary then that will fail. Additionally if we went the route of custom file names how would someone unaware of settings buried in Kodi metadata know that they’re supposed to use that for MiniDNLA?

Sounds like what you really want is MiniDNLA metadata.

**Comment by bdovaz** [comment]
I think I'm beginning to understand it better.

One thing is the consumers, that is, clients that are going to consume the metadata that right now there are 3: kodi, roksbox, wdtv. Each of these generate the metadata in the corresponding format for those clients.

And on the other hand there is the source from where they obtain the metadata that is what I still do not know what code does it and from what source it obtains it, I do not know if it is https://www.themoviedb.org/ or another.

In my case I use ReadyMedia (MiniDLNA) to server the videos: https://wiki.archlinux.org/title/ReadyMedia

I use it together with a Samsung TV. TVs usually implement the DLNA standard quite poorly so in the case of Samsung at least the only thing that works are the thumbnails at the video level and with the following format: movie.mkv -> movie.jpg.

So from what I understand it would only be to create a fourth consumer that in this case is super simple and all you have to do is generate the thumbnails per video with the title of the video itself.

**Comment by markus101** [comment]
> And on the other hand there is the source from where they obtain the metadata that is what I still do not know what code does it and from what source it obtains it, I do not know if it is [themoviedb.org](https://www.themoviedb.org/) or another.

It's the same source Sonarr uses for everything, TheTVDB, this is covered in the FAQ in the wiki.

Yes, the solution would be to to add a new consumer for `MiniDnla` and the corresponding settings to support the supported image types, which looks to be `<file>.cover.jpg` (probably only for movies as there isn't episode cover art) and `<file>.jpg` (thumbnails).

**Comment by markus101** [comment]
Not much interest in this, but if someone is interested in this please open a PR.
