### ISSUE TITLE
TMDb and IMDb support for search in 'Add New Movie'

### ISSUE THREAD

**Issue by ericthomasca** [Sonarr/Sonarr#5078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

This feature is not related to any problem.

### Describe the solution you'd like

To be able to search using a tmdb or imdb tag.

Current options for search:
 - 'Rick and Morty'
 - tvdb:275274

Proposed options:
- tmdb:60625
- imdb:tt2861424

### Describe alternatives you've considered

No alternatives. Just adding search options.

### Anything else?

Just a convenience feature.

**Comment by Qstick** [comment]
You can already do this

**Comment by Qstick** [comment]
Wrong Repo 😁. This will require metadata API support for lookup by external ID

**Comment by bakerboy448** [comment]
sonarr IMDb support already exists - https://github.com/Sonarr/Sonarr/issues/1829

**Comment by ericthomasca** [comment]
> Wrong Repo 😁. This will require metadata API support for lookup by external ID

Can you guide me in the right direction?

**Comment by bakerboy448** [comment]
> > Wrong Repo 😁. This will require metadata API support for lookup by external ID
> 
> Can you guide me in the right direction?

`Add New Movie` does not and will not exist in Sonarr.


Sonarr already supports tvdbid and imdbid (relies on TVDb to have it)

Radarr (movies) already supports tmdbid and imdbid (relies on TMDb) to have it.

anything beyond that tvdbid <=> tmdbid would need metadata rework.

**Comment by ericthomasca** [comment]
> > > Wrong Repo 😁. This will require metadata API support for lookup by external ID
> > 
> > 
> > Can you guide me in the right direction?
> 
> `Add New Movie` does not and will not exist in Sonarr.
> 
> Sonarr already supports tvdbid and imdbid (relies on TVDb to have it)
> 
> Radarr (movies) already supports tmdbid and imdbid (relies on TMDb) to have it.
> 
> anything beyond that tvdbid <=> tmdbid would need metadata and app rework

I meant 'Add New Series', sorry. The placeholder text only states tvdbid. I'm specifically after tmdbid.
