### ISSUE TITLE
Rename & DestinationAlreadyExistsException should add version

### ISSUE THREAD

**Issue by ValiDrv** [Sonarr/Sonarr#5079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When we have multiples version of an episode, and we try to automatically rename them, we end up with `DestinationAlreadyExistsException` exceptions.

This is OK, but since one version of the file is renamed correctly, and the other one is left where it was originally, it makes it a bit hard to clean up.

### Describe the solution you'd like

I suggest when an `DestinationAlreadyExistsException` exception is thrown, the file should still be renamed, but with a suffix.

Ex: 
`foo S00E00 1080p.ext` and the duplicate: `foo S00E00 1080p (copy 1).ext`

### Describe alternatives you've considered

In `Settings`>`Media Management` there should be an option to deal with "duplicates" like this.

### Anything else?

that is all

**Comment by bakerboy448** [comment]
Multiple versions are not currently supported.

that's covered in https://github.com/Sonarr/Sonarr/issues/4551

**Comment by ValiDrv** [comment]
> Multiple versions are not currently supported.

I understand, I'm suggesting to rename the files in a way so we can clearly find those duplicates, in order to clean up the folders easier.

**Comment by markus101** [comment]
No plans to change the behaviour when there are duplicates and still rename them, only one file is managed by Sonarr so the "wrong" file would be renamed in that case.
