### ISSUE TITLE
Parse the GM-team title 

### ISSUE THREAD

**Issue by penggongkui** [Sonarr/Sonarr#5080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[GM-Team][国漫][斗罗大陆][Dou Luo Da Lu][Douro Mainland][2019][215][AVC][GB][1080P]

Something like this title cannot parse release, I know this is not a normal pattern

Series name is: Dou Luo Da Lu
Episode number is : 215

I know the 2019 will confused the parser 
The pattern is in the third [] is Chinese title , and fourth [] is  English title 

### Expected Behavior

Correct parse the info 

### Environment

```markdown
- OS: 
- Sonarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

Na

### Anything else?

Na

**Comment by penggongkui** [comment]
If I can write a regexp rule in the webui to parse the title will be a great feature

**Comment by markus101** [comment]
What is the 2019 there? year?

**Comment by penggongkui** [comment]
YES, 2019 is the year

**Comment by baopc001** [comment]
我代表中国大陆网友要求加入这个功能，我们这里的bt站命名规则和你们是不同的，

**Comment by penggongkui** [comment]
@markus101 How about use the second english only as series name with in [], and use \[1?[0-9]{1,3}\] for parse the episode number

**Comment by penggongkui** [comment]
@markus101 thanks for add this parse, when I upgrade to v4, it can download auto, but it can't auto import, when i mannul import it find that because it cann't parse the title when import. 

![image](https://user-images.githubusercontent.com/49138427/205426976-ab7f6fca-8bab-432d-99db-fa7b9277a6ba.png)

don't know is v4 bug or the parse issue.

**Comment by penggongkui** [comment]
[GM-Team][国漫][Dou Luo Da Lu][Douro Mainland][2019][234][AVC][GB][1080P].mp4

**Comment by penggongkui** [comment]
I mean downloader can parse it, but importer cannot
bellow is when i search it, it can parse
![image](https://user-images.githubusercontent.com/49138427/205427744-b5e64407-90ef-4acb-afd5-455c80b46add.png)

**Comment by markus101** [comment]
They're different formats, the release has `[国漫][斗罗大陆]`, but the filename only has `[国漫]`

**Comment by penggongkui** [comment]
ok, i see

Can we also add some parse rule to parse it, thanks

**Comment by penggongkui** [comment]
[GM-Team][国漫][诛仙][Jade Dynasty][2022][09][HEVC][GB][4K]
Seems sonarr cannot parse the release, and 4k also not recognized

**Comment by penggongkui** [comment]
[GM-Team][国漫][元龙 第3季][Yuan Long Ⅲ][2022][03][AVC][GB][1080P]
Maybe this one also cannot parse, they are less [],than Dou luo da lu
