### ISSUE TITLE
Multiple episodes one file S01E0102 format

### ISSUE THREAD

**Issue by xbjfk** [Sonarr/Sonarr#5081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I downloaded a whole season pack of a show via the Sonarr UI, and it contains 2 episodes in one file like this:
Show.Name.S01E0102.Episode.Name.Info.mkv
Sonarr is getting tripped up on this and isnt finishing the season because of it

### Describe the solution you'd like

I think that episode numbers like that should be added to the filename regex

### Describe alternatives you've considered

Possibly the ability to add/edit regexes for recognition in the UI

### Anything else?

As a workaround I opened qbittorrent and renamed the file from S01E0102 to S01E01E02, and then sonarr recognized it after a refresh and scan

**Comment by thezoggy** [comment]
Not a valid/supported naming format

**Comment by markus101** [comment]
Yeah, this looks like a mistake in that release, Sonarr supports a lot of double episode formats, but the lack of separator between the first and second episode is going to break things.

You can use Manual Import from Activity: Queue or Wanted: Missing to handle this within Sonarr, but it's not something we're going to add handling for.
