### ISSUE TITLE
[Request] OneOm API Support

### ISSUE THREAD

**Issue by zero77** [Sonarr/Sonarr#5082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

N/A

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Anything else?

Can you please add support for oneom as it has an api and hosts tv shows.
https://oneom.is/
https://oneom.is/api

**Comment by markus101** [comment]
It looks like this site doesn't have an RSS feed, which is something Sonarr relies on quite heavily. At the moment this isn't something we're going to implement support for.
