### ISSUE TITLE
Don't automatically monitor latest season/future seasons When Adding Series

### ISSUE THREAD

**Issue by p-hueber** [Sonarr/Sonarr#5083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Right now, there is no way to monitor select seasons/episodes without monitoring future episodes.
This leads to confusing UX when adding new series using Monitor -> Pilot Episode and similar options. Its not clear that these options lead to a temporary state that can change without user interaction. The existence of a distinct "Future Episodes" option further pushed me as a user towards wrong assumptions.

A user limits monitoring to the first episode/season because they don't want to commit more resources until they watched the show some time later. Fetching more than that doesn't make sense.

But even for users aware of this behavior, it requires manual intervention for automated list imports just to stick with the episodes that were asked for.

### Describe the solution you'd like

Make monitored/active and "monitor future episodes" distinct states of a series.

Maybe there could be a bogus item like an empty season representing future episodes. I could imagine this blending in well with the current UI.

### Describe alternatives you've considered

Instead of monitoring pilots, first/last season etc. upon _add_, allow for a one-off search of these items without monitoring them.
That way the user could get exactly what he asked for without having to manually unmonitor the series afterwards.
This is an inferior solution for the lack of monitoring upgrades.

### Anything else?

.

**Comment by markus101** [comment]
Episodes within an existing season already follow the season's monitored state. At the moment the latest season and any new seasons are automatically monitored, which is the problem. Sonarr doesn't need to track whether someone chose Future or Pilot long term it just needs to track whether future seasons need to be monitored.

**Comment by p-hueber** [comment]
> Episodes within an existing season already follow the season's monitored state. At the moment the latest season and any new seasons are automatically monitored, which is the problem. Sonarr doesn't need to track whether someone chose Future or Pilot long term it just needs to track whether future seasons need to be monitored.

Yeah I agree that the "Pilot" option probably doesn't need to be tracked specifically.
I'm not sure about the latest season being monitored automatically. But maybe that happens for unfinished seasons? If that's the case, Sonarr would also need to track whether or not that should happen.

I think the monitoring state of series/season/episode shouldn't be a hierarchy at all, but treated equally.
series monitored -> watch for new seasons
season monitored -> watch for new episodes
episode monitored -> watch for new releases

Thus "Pilot Episode" could become (series not monitored, season(s) not monitored, S01E01 monitored).

What should remain hierarchical is how the monitored state is inherited for new items. E.g. a new season would become monitored if the series was monitored and so on.

But I'm aware that the overall requirements are rather complex and there might be lots of aspects I'm missing.

**Comment by mueslo** [comment]
I would propose instead a placeholder per-episode "future" season. If new seasons appear, they receive the state of this placeholder season. Much more intuitive.
