### ISSUE TITLE
ntfy.sh integration for notifications

### ISSUE THREAD

**Issue by mabed-fr** [Sonarr/Sonarr#5088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

no

### Describe alternatives you've considered

no

### Anything else?

Hello,

Can you add ntfy.sh integration for notifications?

https://ntfy.sh/

Regards,

**Comment by markus101** [comment]
Please fill out the template correctly. Putting "no" for every field is not acceptable.

**Comment by bakerboy448** [comment]
This seems like it can already be accomplished with the existing custom script functionality given that ntfy seems to simply takes data from curl sent to it.

all that's needed is for you to create the custom script to handle the middleware

**Comment by mabed-fr** [comment]
> This seems like it can already be accomplished with the existing custom script functionality given that ntfy seems to simply takes data from curl sent to it.
> 
> all that's needed is for you to create the custom script to handle the middleware

The same could be said for notifiarr or any other implementation we have.

 specific integration is more efficient and adapted

**Comment by austinwbest** [comment]
> The same could be said for notifiarr or any other implementation we have.
>
> specific integration is more efficient and adapted

Quoting the Radarr response isn't really valid at all here lol.. Notifiarr is not in Sonarr and was rejected even with a PR.  I do agree with your second statement though :)

**Comment by bakerboy448** [comment]
https://github.com/Sonarr/Sonarr/commit/f6e6bc98f7846328d158ab2f804ca65b49632912
