### ISSUE TITLE
Newznab indexers not searched by tvdb id when using Anime type

### ISSUE THREAD

**Issue by MurphyPuppy** [Sonarr/Sonarr#5090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When searching for 'Standard' shows on a Newznab indexer Sonarr will do a search by tvdb id, season, and episode number. Sonarr does not perform this search for 'Anime' style shows, even if the standard and anime categories are identical, and even if "Also search for anime using the standard numbering" is enabled.

### Expected Behavior

Sonarr should perform this id-based search for 'Anime'-style indexers. This causes Sonarr to miss some releases.

### Steps To Reproduce

1. Configure Sonarr with a Newznab indexer
2. Enable "Also search for anime using the standard numbering" (optional, used to demonstrate this option does not help)
3. Add something under the 'Anime' type
4. Perform search
5. Watch searches, see Sonarr does not perform a search by id (easiest way to do this is to use an indexer such as nzbhydra2 that supports logging a search history)

### Environment

```markdown
- OS: N/A
- Sonarr: 3.0.8.1507
- Docker Install: N/A
- Using Reverse Proxy: N/A
- Browser: N/A
```

### What branch are you running?

Main

### Trace Logs?

N/A

### Anything else?

N/A

**Comment by bakerboy448** [comment]
Trace logs are not optional for bug reports.

**Comment by bakerboy448** [comment]
The wiki the GitHub template links to is pretty clear that entire log files are not needed; only the context
