### ISSUE TITLE
Add ability to pause/schedule auto-imports

### ISSUE THREAD

**Issue by thomasbrooks4** [Sonarr/Sonarr#5091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

While importing large files, my Plex server might time out causing connection issues until importing is done.

### Describe the solution you'd like

To avoid this potential issue I'd like to have a manual toggle to disable auto-imports so I can continue to download but avoid importing until ready. Ideally I'd like to also schedule auto-importing to only auto-import during the early hours of the day to avoid impact on any users.

### Describe alternatives you've considered

If I am afraid that a download will lock the plex db then you can also just pause the download in the downloader before it finishes then manually turn it back on when you are ready to import.

### Anything else?

Somewhat related, it would be nice to pause imports while in progress. I wasn't aware that sonarr grabbed a file triple of what I was expecting (of the same quality) and I was forced to get locked out of Plex until my 100GB episodes to finish which took ~20 min. It would be nice to just pause/cancel imports if I decide otherwise.

**Comment by thezoggy** [comment]
just run sonarr with nice/ionice?

**Comment by thomasbrooks4** [comment]
Hello, thanks for the comment, I was wondering if there was a setting or something that I should have been doing to avoid needing this. I couldn't really find much on nice/ionice in terms of use with Sonarr. Could you point me (and others that might find this) to more info about using it?

**Comment by markus101** [comment]
We don’t have plans to schedule imports, I can’t help with nice/ionice, but it’s probably better to discuss in one of the support channels and post the answer here later.
