### ISSUE TITLE
Anime being reorder when a special episode is released

### ISSUE THREAD

**Issue by DataHearth** [Sonarr/Sonarr#5093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Found issue that might ressemble: https://github.com/Sonarr/Sonarr/issues/3785

I added a while ago the serie `Tengen Toppa Gurren Lagann`. Every episode were added except the special ones.

Yesterday, I went back to sonarr to rename a new serie, then I've seen the serie `Tengen Toppa Gurren Lagann` was missing files. I checked and the episodes `26/27` were missing. 
Episodes `06/08` have been moved into the first two special episodes. The two special episode are marked with an absolute number.

### Expected Behavior

Special episodes are put appart and can't take files already setted up in the "main" serie.

Or maybe a way to tell sonarr to exclude them completly/rearrange them back.

### Steps To Reproduce

1. Add a serie (anime in my case)
2. Add all episodes
3. (Don't have any how to trigger it manually) Wait for a special episode to be released and/or an update with TVDB
4. Check the serie, episode should be rearranged

### Environment

```markdown
- OS: linuxserver.io docker image
- Sonarr: 3.0.8.1507
- Docker Install:
- Using Reverse Proxy: swag from linuxserver.io
- Browser: firefox
```

### What branch are you running?

Main

### Trace Logs?

[logs.txt](https://github.com/Sonarr/Sonarr/files/9192216/logs.txt)

Note: I can't give you traces as I can't predict when I'm gonna have the issue

### Anything else?

Always happened to anime (at least for now)

**Comment by markus101** [comment]
This is the same as #3785, if TheTVDB changes absolute episode numbers it's going to cause issues, same as if they changed season/episode numbers for non-anime series.
