### ISSUE TITLE
Specific File Size Limits per Show

### ISSUE THREAD

**Issue by hellot1m** [Sonarr/Sonarr#5096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not related to any problem

### Describe the solution you'd like

There are some shows that i am ok with the 1080p format automatically grabbing over my preset limits or under my preset limits. Also there are a lot of cartoons that list on Sonarr that are 23 minutes or 12 minutes but the only format that these shows are available in are when 2-3 episodes are in each episode. This will bump up the file size but sonarr doesn't allow the download because of the global limits we have for them. So what i would like is an additional option during the process of adding a show to Sonarr and choosing where it will be saved and if its anime/standard/daily. On this screen, should include another option for the ability to override global size limits in in factors/ratios. like this

Global Filesize Handicap: +5%, +10%, -5%, -10%

something like this. 

this is just so a show can automatically grab episodes with more file size freedom at the users choice. 

### Describe alternatives you've considered

An alternative would be something like;

Ignore File Size Max Limit: Yes/No
Ignore File Size Min Limit: Yes/No
Prioritize smallest file size: Yes/No
Prioritize Largest File Size: Yes/No

### Anything else?

Nothing ATM

**Comment by markus101** [comment]
No plans for per series limits, this is the closest and almost a duplicate: https://github.com/Sonarr/Sonarr/issues/613
