### ISSUE TITLE
Ubuntu 22.04 packages

### ISSUE THREAD

**Issue by tonimelisma** [Sonarr/Sonarr#5098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Ubuntu 22.04 jammy has been out for a few months now. Is it possible to add an ```apt``` repository and packages for it?

### Describe the solution you'd like

Add apt repository for 22.04 jammy

### Describe alternatives you've considered

Compile from source or hack together something in docker

### Anything else?

N.a.

**Comment by Taloth** [comment]
It's possible but it'll be the same package as 20.04, so I haven't made it a priority coz ppl can use the 20.04 feed for it.

**Comment by markus101** [comment]
Closing in favour of https://github.com/Sonarr/Sonarr/issues/4641 to handle both.
