### ISSUE TITLE
Allow on API /queue DELETE specify to not delete from download client

### ISSUE THREAD

**Issue by xeviff** [Sonarr/Sonarr#5099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

yes, I want to keep the download on the torrent client so that the trackers doesn't block me. I'm using a personalized Java application to do some automations and one of the functionalities is use the Sonarr API to delete from queue a failed import download that the program copies to proper location using Google Drive API client...

### Describe the solution you'd like

it's as simple as adding a parameter where I can specify to not delete from download client, such as the web is actual allowing:
![image](https://user-images.githubusercontent.com/73612508/182303180-0afff4e6-cead-476f-920b-732442c624e6.png)

### Describe alternatives you've considered

maybe not deleting by default?

### Anything else?

Yes! I can share you my program:
https://github.com/xeviff/AfterDownloadCarer
it's interactuating also with Radarr which actually allows to specify this parameter.

One of the motivations of develop this program was the failed importing downloads, which forces me to manually manage them one by one every time
![image](https://user-images.githubusercontent.com/73612508/182303984-c2d1f22c-ceda-4d12-873c-22c6406b00b9.png)

**Comment by markus101** [comment]
The UI uses the API for everything, same as Radarr does. It should use the exact same parameter as well, `removeFromClient`, the default value is true, again the same as Radarr.
