### ISSUE TITLE
Automatically fail releases that contain certain extensions

### ISSUE THREAD

**Issue by oscdat** [Sonarr/Sonarr#5101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Just couple of minutes back, I downloaded and almost clicked on a Virus. It came in the form of "**.scr**" screen saver file type. I went to click it but thankfully I changed my mind and decided to google whether it can opened with VLC or not. That's when I disovered that it was actually a Virus file instead of a Video file.

### Describe the solution you'd like

So if you can please add a feature where it lets us select the file types to download like .mkv , .mp4 , flac , .mp3 ... It'll be really helpful. Right now I'm in a state of paranoia, I lost the confidence to insta-play any of my downloaded files without first checking the extension.

Thanks for your time and consideration.

### Describe alternatives you've considered

The only alternative that I can currently think of is to manually downloaded the files directly from trusted sources which defeats the whole purpose of using Sonarr.

### Anything else?

This Virus wrecks the entire system and can steal all the user data / information.

**Comment by PearsonFlyer** [comment]
Sonarr doesn't know what files are in the download until the downloader is done. At that point, it would have rejected a .scr file and not imported it for you. So it already does what you're looking for, doesn't it?

**Comment by oscdat** [comment]
> Sonarr doesn't know what files are in the download until the downloader is done. At that point, it would have rejected a .scr file and not imported it for you. So it already does what you're looking for, doesn't it?

But the virus was still there in my system, that's how I was about to click it. It didn't delete it.

**Comment by thezoggy** [comment]
1) your indexer should be filtering out nasty things
2) your downloader is a better place to 'detect' and abort bad releases
3) dont use public torrent sites which are known to have malware/spam

**Comment by oscdat** [comment]
> 1. your indexer should be filtering out nasty things
> 2. your downloader is a better place to 'detect' and abort bad releases
> 3. dont use public torrent sites which are known to have malware/spam
> 
> then finally, there is already: #3331

Maybe I saw those files inside the qbittorrent location. I was flustered, didn't stop to think, I immediately deleted that file. If it was in fact from the downloads folder, does Sonarr have any settings that automatically removes the downloaded files form qbittorrent other than deleting it after meeting the seeding requirement?
Thanks for the help.

**Comment by bakerboy448** [comment]
> does Sonarr have any settings that automatically removes the downloaded files form qbittorrent other than deleting it after meeting the seeding requirement?

no. Why would it?

**Comment by oscdat** [comment]
> no. Why would it?

Ummm... to delete the virus file maybe?

**Comment by Thirrian** [comment]
Sonarr is smarter in the sense that it sees no media file once the download is complete, and tells you so with a warning to check out what's wrong on the download client side, because it can't find anything to import.
It doesn't know what's specifically wrong other than that. It could also be a legitimate file that requires human intervention before sonarr recognises it, hence the warning that it can't do its thing automatically.

It's still your indexers' fault for allowing/advertising shit like that as "Some tv show season x episode y", so I'll echo the statement to find a decent indexer.

**Comment by oscdat** [comment]
> Sonarr is smarter in the sense that it sees no media file once the download is complete, and tells you so with a warning to check out what's wrong on the download client side, because it can't find anything to import. It doesn't know what's specifically wrong other than that. It could also be a legitimate file that requires human intervention before sonarr recognises it, hence the warning that it can't do its thing automatically.
> 
> It's still your indexers' fault for allowing/advertising shit like that as "Some tv show season x episode y", so I'll echo the statement to find a decent indexer.
Thanks for the breakdown, even if no new feature gets added. I'm glad I posted coz I learned a lot of things regarding the inner workings of Sonarr. That Indexer / Site is invaluable to me, if not for that one site, I wouldn't have any use for Jackett, Sonarr ... So I'll live with it. Thanks again to everyone for helping, truly appreciate it. <3

**Comment by markus101** [comment]
I'm not totally opposed to having a function that fails downloads based on the contents of the files within (maybe not as freeform, but explicitly `.exe`), but this could lead to issues on sites that have hit and run rules, because even if it's a fake torrent it could trigger those rules and make it a pain to deal with.

I think there would be a fair amount of work to do outside of just throwing things out to achieve this, we'll need to discuss if that's something we want to do.

**Comment by thezoggy** [comment]
to note, upcoming qbit 4.5.0 feature allows filtering out by extension  -- https://github.com/qbittorrent/qBittorrent/pull/17106

**Comment by oscdat** [comment]
> I think there would be a fair amount of work to do outside of just throwing things out to achieve this, we'll need to discuss if that's something we want to do.
Thank you for even considering it, I'll leave it to your better judgment.

**Comment by oscdat** [comment]
> to note, upcoming qbit 4.5.0 feature allows filtering out by extension -- [qbittorrent/qBittorrent#17106](https://github.com/qbittorrent/qBittorrent/pull/17106)

That's really good news. I know which extension is going there first. Thank you for the info.

**Comment by markus101** [comment]
Not going to fail the download, but going to through up a warning in the queue instead of a generic no video files found message.
