### ISSUE TITLE
Add More Loading Messages?

### ISSUE THREAD

**Issue by darylf** [Sonarr/Sonarr#5105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

N/A

### Describe the solution you'd like

I love the loading messages. I realize [not everybody is](https://github.com/Sonarr/Sonarr/issues/4471), but is there an appetite for adding more messages?  The 18 messages already defined are great, but I want more! :D

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by markus101** [comment]
Not something we have any short term plans for.
