### ISSUE TITLE
No a decent way to ignore language preference

### ISSUE THREAD

**Issue by wloot** [Sonarr/Sonarr#5107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I would like to completely ignore language attribute of a release, neither upgrade nor prevent from upgrading, so that I can control upgrades by preferrd words and quality profile.
I've tried checking all languages for a Language Profile, I enabled it's Allow Upgrades, and set Upgrade Until to lowest priority Unknown language. But it seems Sonarr prevent language downgrading even there is a higer preferrd words score release.

### Describe the solution you'd like

 An option?

### Describe alternatives you've considered

None

### Anything else?

None

**Comment by markus101** [comment]
In v4 we'll be moving from language profiles/release profiles for priority to Custom Formats like Radarr has which will resolve this behaviour, no plans to make changes until then.

**Comment by bakerboy448** [comment]
https://github.com/Sonarr/Sonarr/commit/89b0b04e08ce171e177933a1c46ea9e3856b87da
