### ISSUE TITLE
Simplepush integration 

### ISSUE THREAD

**Issue by andycarver101** [Sonarr/Sonarr#5108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Radarr has support for Simplepush.io can this be implemented in Sonarr?

### Describe the solution you'd like

Sonarr support for Simplepush.io just like Radarr. 

### Describe alternatives you've considered

I’m going to try a CURL but I’m unsure how to customise that to feature the episode name. 

### Anything else?

Can anyone help with how to customise a bash using curl to specify the episode name grabbed/downloaded?

EDIT: Radarr *has support 9/8/22

**Comment by markus101** [comment]
Had or has support, if it's the former then I don't see us adding something they've since removed.

**Comment by andycarver101** [comment]
Sorry, Radarr currently has support.

**Comment by andycarver101** [comment]
Awesome. Will this be in the next major update?
