### ISSUE TITLE
Support of Automation or Notification for Episodes not yet added to TVDB at time of RSS update

### ISSUE THREAD

**Issue by SF4L** [Sonarr/Sonarr#5109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

- Streaming services sometimes add episodes before the community is able to add them to TVDB, well before the "official" airdate by the network
- Scene often releases them when they're added to streaming services, thus popping up in RSS feeds for indexers
- People add them to TVDB after scene releases them
- Because TVDB/Sonarr doesn't know about them at the time of RSS updates containing them, these episodes are not automatically downloaded by Sonarr. And you don't get a notification that they weren't downloaded, so the show is basically going to remain out of sync until you do a manual search for that series. 

Here are two examples from the past week:
https://thetvdb.com/series/90-day-fiance-uk
https://thetvdb.com/series/battlebots-2015

(and a kicker: sometimes the airdate is actually in the future, because streaming services air them earlier than the TV Network, so even a manual search for a show like 90 Day Fiance UK today wouldn't download episodes 4 and 5, even though they have already been released by streaming services and scene groups)

### Describe the solution you'd like

I would like a notification (Activity Queue or Events?) that Sonarr found an episode in RSS feed for a Known/Monitored Show but was unable to match it to an episode in Sonarr/TVDB. Then the user can check TVDB to make sure everything is Kosher, check Skyhook, etc. and when all is ready, do a search for the show that we now know is slightly out of sync.

Possibly even the ability to automatically download the episode and keep it in the "Unmatched" queue until TVDB has had a chance to update itself, although I'm sure that may come with its fair share of problems as well.

Example Implementation of Downloading Logic:

Add a Flag that says "Allow unmatched downloading of future episodes"

Sonarr sees RSS item for Known Show, S0YE0X. Can match with existing episode? Great. Download. Can't match, then:

If (Flag), 
If (S0YE0X-1 exists), Download, 
else if (S0Y-1 is complete), Download. 
else (Log RSS unable to match item for existing show)

### Describe alternatives you've considered

- Search indexer any time any episode is added, even if it's in the future (probably very bad idea as explained to me by @fryfrog @bakerboy448  )
- Make sure TVDB is always up to date (we try, but due to streaming services not giving proper notification, it doesn't always work...)
 
- My current solution: every week, I go through all of "Wanted" and use `Search Selected` to search all shows that are missing something from the past week. A lot of manual work and probably extra queries on the sites, but I almost always get 5 or 6 new episodes every week, so clearly _something_ is a little off with the automation, and after a little more investigation, it looks like it's streaming services + TVDB not playing along nicely.

### Anything else?

Was discussed a little bit in the #sonarr Discord on 8/8 at around Noon EST

https://discordapp.com/channels/383686866005917708/383688189941907459/1006222741139099738

**Comment by markus101** [comment]
Sonarr automatically searches for episodes that are added to Sonarr after the air date. We don't have plans to add notifications when episodes match a series, but not a known episode.

**Comment by SF4L** [comment]
Perhaps we can add a few days to the grace period for searching here: https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/Tv/EpisodeAddedService.cs#L76 ? We discussed a little bit more with @bakerboy448 -- basically this issue arises any time a show airs on a streaming network a few days before it's supposed to air, _then_ is added to TVDB after it is released on a streaming platform, and the airdate either is not inputted into TVDB (nothing we can really do about that) _or_ is 2+ days from the date it is added to Sonarr (due to cache + existing rule of AddDays(1) for whether you should search it or not).

------------

Here I will continue adding episodes here that were skipped with existing rules and found during manual searches, so we can see how common it actually is...

https://thetvdb.com/series/90-day-fiance-uk
https://thetvdb.com/series/battlebots-2015
https://thetvdb.com/series/snake-in-the-grass (although this series is all sorts of discombobulated due to network vs. Peacock vs. TVDB)

**Comment by markus101** [comment]
> Perhaps we can add a few days to the grace period for searching here.

That's on day into the future, 14 days in the past, as long as it doesn't take 14 days to be added to Sonarr it it'll be caught by that, so delays due to caching don't make it worse unless it takes almost 2 weeks for them to be added after they've aired.

Listing out a bunch of series that had "a problem" without any sort of explanation of the timeline isn't helpful.

I didn't see any issues with Battlebots (2015) S07E01

Aired: 2022-08-04
Released: 2022-08-04
Grabbed: 2022-08-05, when the release was 25 hours old,

**Comment by SF4L** [comment]
Sorry, I explained the problem a little bit in the Discord chat. The list without context is not meant to be particularly useful, it's just a list of shows for which desired release (ie: original scene WEB-DL) is not downloaded due to TVDB not being updated at the time of scene release, thus _potentially_ causing issues if Airdate is not the same as Release Date (ie: a notification may be useful for said show).

-- The issue arises anytime the timeline of events goes something like:
- Episode Airdate is 8/11
- Episode/Scene Release Date is 8/8 AM
- Episode is added to TVDB on 8/8 PM or 8/9 (after the episode has been released into RSS feeds)
- Episode gets added to Sonarr on 8/9 or 8/10 due to TVDB cache; if it's on 8/9, it won't be added to search queue right now without the grace period (AddDays(1)).
- Something like this is what happened for both Snake in the Grass and 90 Day Fiance UK

I _believe_, although without being able to confirm exactly what happened with BattleBots, is something like this. Tbh, I'm not sure (all I know is both I and a friend of mine using Sonarr missed the release and didn't get it until Manual Search, and it was in the RSS feed; unfortunately I no longer have the trace log) --
- Released by scene on 8/4, 23:30 EST (8/5, 3:30 GMT)
- Added to TVDB on 8/5, with incorrect airdate (8/11 or non-existent perhaps?)
- Airdate updated to correct date on 8/5, but this did not make it to cache
- Sonarr picks up BattleBots on 8/5 or 8/6 with the incorrect airdate (either null or 8/11)
- Sonarr does not search for BattleBots because this release does not meet the current criteria?

Again, honestly, I'm not 100% sure what happened with BattleBots because if it was added correctly with the correct airdate, then the current logic definitely says to search for it, since it would've been added to Sonarr on 8/5 or 8/6 and triggered a search because 8/4 is in between X-2weeks and X+1days on 8/5 or 8/6. All I know for sure is that the episode was released by Scene groups before it was added to TVDB, and it didn't make it into at least two people's Sonarr instances who are monitoring the show.

Originally, I thought the best solution would to add an **optional** notification that an episode is in RSS that matches a monitored show but not a known episode. I still think this may be really helpful (specials, weirdly named releases, etc.), but I understand that a lot of people use public trackers etc and garbage releases would probably flood these notifications.

So after talking it through, it seems like the better solution may be to increase the grace period for "when should Sonarr search for new episode additions" by a few days, since streaming services seem to often have episodes a few days before the official network airdate and/or addition to TVDB (and by compiling this list of missed episodes/shows I'm hoping to see if this actually occurs often enough to be worth doing anything about)

**Comment by markus101** [comment]
I read a bit of the Discord chat, but it looked like you and baker were talking about a possible scenario that could possibly happen, but didn't necessarily happen.

- 90 Day Fiance UK looks to have episodes released the same day that the episode aired, if the data was updated after that it would have been searched for because it would have been within the previous 14 days (and the next 1 day wouldn't matter).
- Snake in the Grass - it looks like it had one 480p release 2 days before the air date, not sure when this series was updated, but this could have caused the issue, but we'd need information that would be longer be available.
- Based on my result with Battlebots I don't see any issues with the episode metadata having the wrong or no air date.

Yeah, such a notification would require a bunch of work for a small gain and potentially a lot of noise.

We definitely need more information in order to see if it's worth doing, as of right now it looks like _maybe_ one of the 3 series that were mentioned potentially would be solved by extending that grace period by ~1 day, but with that comes overhead as Sonarr would search for more episodes that probably haven't released because they haven't aired.

**Comment by SF4L** [comment]
> * 90 Day Fiance UK looks to have episodes released the same day that the episode aired, if the data was updated after that it would have been searched for because it would have been within the previous 14 days (and the next 1 day wouldn't matter).

Nah, with 90 Day Fiance UK I am 100% sure the Airdates were added for E04 and E05 as 8/14 and 8/21 on 8/7, _after_ they were already released by Scene (so RSS didn't pick them up, because they weren't in Sonarr at the time of being added). Placeholder episodes have now been added for the upcoming episodes (I'm pretty sure TVDB asks you not to do that, but whatever) so they should be added with RSS updates even if scene releases a batch of them again I think... 

https://discordapp.com/channels/383686866005917708/383688189941907459/1006210041306681394)

Will continue providing updates...

**Comment by SF4L** [comment]
Alright, now I'm even more confused than I was before... Yesterday, I checked Sonarr and saw "Living Smaller" only had 16 episodes even though 17-20 were uploaded by scene. I added episodes 17-22 to TVDB with the proper airdates (after 17-20 were released by scene); they all have episode airdates in the recent past (< 2 weeks ago -- July 31st and August 7th). Today I check Sonarr and all of the episodes have been added; I'm now missing 4 episodes (as I should be) -- it shows 16/20. But for some reason, those 4 new episodes from the recent past weren't downloaded -- if I do an interactive search right now, I see them on my indexer with no errors/warnings.

Here's my full grep results for Living Smaller in my logs folder from this morning; I triggered a manual search at 11-05 to confirm that indexers pick them up.

```
sonarr.0.txt:2022-08-09 16:18:52.0|Info|RefreshSeriesService|Updating Living Smaller
sonarr.0.txt:2022-08-09 16:18:52.1|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.0.txt:2022-08-09 16:18:52.1|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.1.txt:2022-08-09 03:49:44.9|Info|RefreshSeriesService|Updating Living Smaller
sonarr.1.txt:2022-08-09 03:49:45.0|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.1.txt:2022-08-09 03:49:45.2|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.2.txt:2022-08-08 15:15:09.6|Info|RefreshSeriesService|Updating Living Smaller
sonarr.2.txt:2022-08-08 15:15:09.8|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.2.txt:2022-08-08 15:15:09.8|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.3.txt:2022-08-08 03:04:04.1|Info|RefreshSeriesService|Updating Living Smaller
sonarr.3.txt:2022-08-08 03:04:04.2|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.3.txt:2022-08-08 03:04:04.3|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.4.txt:2022-08-07 02:49:08.8|Info|RefreshSeriesService|Updating Living Smaller
sonarr.4.txt:2022-08-07 02:49:08.9|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.4.txt:2022-08-07 02:49:08.9|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.4.txt:2022-08-07 14:56:23.5|Info|RefreshSeriesService|Updating Living Smaller
sonarr.4.txt:2022-08-07 14:56:23.7|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.4.txt:2022-08-07 14:56:23.9|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.debug.0.txt:2022-08-10 11:05:08.2|Info|ReleaseSearchService|Searching indexers for [Living Smaller : S01E17]. 2 active indexers
sonarr.debug.0.txt:2022-08-10 11:05:08.4|Debug|ReleaseSearchService|Total of 1 reports were found for [Living Smaller : S01E17] from 2 indexers
sonarr.debug.0.txt:2022-08-10 11:05:08.5|Debug|Parser|Episode Parsed. Living Smaller - S01E17
sonarr.debug.0.txt:2022-08-10 11:05:13.8|Info|ReleaseSearchService|Searching indexers for [Living Smaller : S01E17]. 2 active indexers
sonarr.debug.0.txt:2022-08-10 11:05:14.0|Debug|ReleaseSearchService|Total of 1 reports were found for [Living Smaller : S01E17] from 2 indexers
sonarr.debug.0.txt:2022-08-10 11:05:14.1|Debug|Parser|Episode Parsed. Living Smaller - S01E17
sonarr.debug.32.txt:2022-08-10 04:26:42.7|Info|RefreshSeriesService|Updating Living Smaller
sonarr.debug.32.txt:2022-08-10 04:26:42.9|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.debug.32.txt:2022-08-10 04:26:42.9|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.debug.32.txt:2022-08-10 04:26:42.9|Debug|RefreshSeriesService|Finished series refresh for Living Smaller
sonarr.debug.32.txt:2022-08-10 04:26:42.9|Debug|XemService|Scene numbering is not available for Living Smaller [420855]
sonarr.trace.1.txt:2022-08-10 11:05:08.2|Info|ReleaseSearchService|Searching indexers for [Living Smaller : S01E17]. 2 active indexers
sonarr.trace.1.txt:2022-08-10 11:05:08.4|Debug|ReleaseSearchService|Total of 1 reports were found for [Living Smaller : S01E17] from 2 indexers
sonarr.trace.1.txt:2022-08-10 11:05:08.5|Debug|Parser|Episode Parsed. Living Smaller - S01E17
sonarr.trace.1.txt:2022-08-10 11:05:13.8|Info|ReleaseSearchService|Searching indexers for [Living Smaller : S01E17]. 2 active indexers
sonarr.trace.1.txt:2022-08-10 11:05:14.0|Debug|ReleaseSearchService|Total of 1 reports were found for [Living Smaller : S01E17] from 2 indexers
sonarr.trace.1.txt:2022-08-10 11:05:14.1|Debug|Parser|Episode Parsed. Living Smaller - S01E17
sonarr.txt:2022-08-10 04:26:42.7|Info|RefreshSeriesService|Updating Living Smaller
sonarr.txt:2022-08-10 04:26:42.9|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.txt:2022-08-10 04:26:42.9|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.txt:2022-08-10 11:05:08.2|Info|ReleaseSearchService|Searching indexers for [Living Smaller : S01E17]. 2 active indexers
sonarr.txt:2022-08-10 11:05:13.8|Info|ReleaseSearchService|Searching indexers for [Living Smaller : S01E17]. 2 active indexers
sonarr.0.txt:2022-08-09 16:18:52.0|Info|RefreshSeriesService|Updating Living Smaller
sonarr.0.txt:2022-08-09 16:18:52.1|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.0.txt:2022-08-09 16:18:52.1|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.1.txt:2022-08-09 03:49:44.9|Info|RefreshSeriesService|Updating Living Smaller
sonarr.1.txt:2022-08-09 03:49:45.0|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.1.txt:2022-08-09 03:49:45.2|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.2.txt:2022-08-08 15:15:09.6|Info|RefreshSeriesService|Updating Living Smaller
sonarr.2.txt:2022-08-08 15:15:09.8|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.2.txt:2022-08-08 15:15:09.8|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.3.txt:2022-08-08 03:04:04.1|Info|RefreshSeriesService|Updating Living Smaller
sonarr.3.txt:2022-08-08 03:04:04.2|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.3.txt:2022-08-08 03:04:04.3|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.4.txt:2022-08-07 02:49:08.8|Info|RefreshSeriesService|Updating Living Smaller
sonarr.4.txt:2022-08-07 02:49:08.9|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.4.txt:2022-08-07 02:49:08.9|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.4.txt:2022-08-07 14:56:23.5|Info|RefreshSeriesService|Updating Living Smaller
sonarr.4.txt:2022-08-07 14:56:23.7|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.4.txt:2022-08-07 14:56:23.9|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.debug.0.txt:2022-08-10 11:05:08.2|Info|ReleaseSearchService|Searching indexers for [Living Smaller : S01E17]. 2 active indexers
sonarr.debug.0.txt:2022-08-10 11:05:08.4|Debug|ReleaseSearchService|Total of 1 reports were found for [Living Smaller : S01E17] from 2 indexers
sonarr.debug.0.txt:2022-08-10 11:05:08.5|Debug|Parser|Episode Parsed. Living Smaller - S01E17
sonarr.debug.0.txt:2022-08-10 11:05:13.8|Info|ReleaseSearchService|Searching indexers for [Living Smaller : S01E17]. 2 active indexers
sonarr.debug.0.txt:2022-08-10 11:05:14.0|Debug|ReleaseSearchService|Total of 1 reports were found for [Living Smaller : S01E17] from 2 indexers
sonarr.debug.0.txt:2022-08-10 11:05:14.1|Debug|Parser|Episode Parsed. Living Smaller - S01E17
sonarr.debug.32.txt:2022-08-10 04:26:42.7|Info|RefreshSeriesService|Updating Living Smaller
sonarr.debug.32.txt:2022-08-10 04:26:42.9|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.debug.32.txt:2022-08-10 04:26:42.9|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.debug.32.txt:2022-08-10 04:26:42.9|Debug|RefreshSeriesService|Finished series refresh for Living Smaller
sonarr.debug.32.txt:2022-08-10 04:26:42.9|Debug|XemService|Scene numbering is not available for Living Smaller [420855]
sonarr.trace.1.txt:2022-08-10 11:05:08.2|Info|ReleaseSearchService|Searching indexers for [Living Smaller : S01E17]. 2 active indexers
sonarr.trace.1.txt:2022-08-10 11:05:08.4|Debug|ReleaseSearchService|Total of 1 reports were found for [Living Smaller : S01E17] from 2 indexers
sonarr.trace.1.txt:2022-08-10 11:05:08.5|Debug|Parser|Episode Parsed. Living Smaller - S01E17
sonarr.trace.1.txt:2022-08-10 11:05:13.8|Info|ReleaseSearchService|Searching indexers for [Living Smaller : S01E17]. 2 active indexers
sonarr.trace.1.txt:2022-08-10 11:05:14.0|Debug|ReleaseSearchService|Total of 1 reports were found for [Living Smaller : S01E17] from 2 indexers
sonarr.trace.1.txt:2022-08-10 11:05:14.1|Debug|Parser|Episode Parsed. Living Smaller - S01E17
sonarr.txt:2022-08-10 04:26:42.7|Info|RefreshSeriesService|Updating Living Smaller
sonarr.txt:2022-08-10 04:26:42.9|Info|RefreshEpisodeService|Starting episode info refresh for: [420855][Living Smaller]
sonarr.txt:2022-08-10 04:26:42.9|Info|RefreshEpisodeService|Finished episode refresh for series: [420855][Living Smaller].
sonarr.txt:2022-08-10 11:05:08.2|Info|ReleaseSearchService|Searching indexers for [Living Smaller : S01E17]. 2 active indexers
sonarr.txt:2022-08-10 11:05:13.8|Info|ReleaseSearchService|Searching indexers for [Living Smaller : S01E17]. 2 active indexers
```

**Comment by SF4L** [comment]
Update: Turns out that as of now "Rescan Series Folder after Refresh" must be set to _Always_ for Sonarr to trigger searches of recently added episodes (mine was set to "After Manual Refresh"). So that explains the mystery of BattleBots and Living Smaller.

**Comment by SF4L** [comment]
https://thetvdb.com/series/red-rose one recent example of BBC show that had all episodes drop early on streaming service, but airdate of final episode isn't until September 6

(https://www.thetvdb.com/series/marriage should be picked up after airdate of final episode)
