### ISSUE TITLE
Possible to implement BTFS as a torrent downloader?

### ISSUE THREAD

**Issue by TuRDMaN** [Sonarr/Sonarr#5114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

n/a

### Describe the solution you'd like

No idea how feasible this is, but would it be possible to create a Downloader that would essentially blackhole a .torrent file, then mount it with BTFS (bittorrent filesystem), and then copy the required files from the .torrent into the destination? It would eliminate the need for external torrenting software, and could potentially save bandwidth by only grabbing the required files, and not everything from the .torrent if not needed.

I think the most difficult part would be error handling.

### Describe alternatives you've considered

n/a

### Anything else?

https://github.com/johang/btfs

**Comment by markus101** [comment]
It may be possible to achieve this with the existing blackhole integration, using the read-only option so it hardlinks/copies the file from the "completed" download. No sure if it'd work, but at the moment we're not going to implement a custom solution for this.
