### ISSUE TITLE
Collapsed series color coding

### ISSUE THREAD

**Issue by macbean101** [Sonarr/Sonarr#5117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When using 'Collapse Multiple Episodes' any unmonitored show uses the missing color coding (red) instead of unmonitored (grey).

### Describe the solution you'd like

when Collapse Multiple episodes is enabled, an unmonitored with multiple episodes show should show grey not red.  

### Describe alternatives you've considered

only alternative is ignoring the incorrect coloring or not using the collapse multiple episode option

### Anything else?

collapsed unmonitored:
![image](https://user-images.githubusercontent.com/25144645/184567664-0c190d11-db2a-4d46-9f82-fec036107b47.png)

expanded
![image](https://user-images.githubusercontent.com/25144645/184567690-af6b6ebc-43aa-48ff-b088-40635aaa183a.png)

**Comment by markus101** [comment]
This will affect any series where the series is unmonitored, but the episodes are monitored as it's not correctly including that in the check.
