### ISSUE TITLE
Set preferred indexer to search first

### ISSUE THREAD

**Issue by daemond99** [Sonarr/Sonarr#5120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Yes and no. The problem lies with the indexers, not with Sonarr itself.

Indexer A I have no issues with
Indexer B has tons of releases that are in .rar files that I cannot extract (this is a whole 'nother issue I have already tried to fix but came up empty handed).

### Describe the solution you'd like

The ability to prioritize which indexers to search first.

### Describe alternatives you've considered

Fixing my .rar extraction issue that I spent weeks looking into with tons of alternative programs that all failed or required even more manual input to get SOMETHING to auto extract, but nothing worked. 

### Anything else?

Anything to let me prioritize one tracker over another, or a "search first, search second" kind of thing.

**Comment by bakerboy448** [comment]
[Indexer priority already exists...but it is only a tiebreaker](https://wiki.servarr.com/sonarr/faq#how-are-possible-downloads-compared)

> Fixing my .rar extraction issue that I spent weeks looking into with tons of alternative programs that all failed or required even more manual input to get SOMETHING to auto extract, but nothing worked.

ah so an [X-Y problem](https://xyproblem.info/)

use unpackerr. If it doesn't work - then use their support methods.

Any other attempts to jerry rig some unpack script is futile

**Comment by daemond99** [comment]
Yes, definitely an XY problem haha. I'm at my wits end with the unpack
stuff.

I have come across unpackerr but I'm not familiar with the docker setup
stuff yet. I was also trying to figure out a solution that worked without
setting up yet another 3rd party tool. At this point I might just remove
the indexer for now as it's too much work. Obviously this isn't a huge
request but definitely a nice to have imo.

**Comment by bakerboy448** [comment]
Unpackerr doesn't require docker...?

**Comment by daemond99** [comment]
Oh.. Well that's embarrassing, and news to me. I will definitely check it
out then lol. I guess that's what I get for taking only a cursory glance at
the page.

**Comment by markus101** [comment]
No plans to add search priority, but you can prioritize grabbing when releases are otherwise equal, if rar content continues to be an issue.
