### ISSUE TITLE
Naming Files and Moving into Season Folder

### ISSUE THREAD

**Issue by duckie133** [Sonarr/Sonarr#5125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I downloaded and installed the newest version of Sonarr but would move the file but not rename it and move it to a season folder. I downloaded and installed the older version (2.0.0.5344) which I had before and it works fine. Is this a known issue and is there a fix?

### Expected Behavior

Rename the file and place it in a season folder.

### Environment

```markdown
- OS:Windows 10 
- Sonarr: 2.0.0.5344
- Docker Install:
- Using Reverse Proxy:
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

Don't have any since I uninstall the newer version

### Anything else?

No

**Comment by bakerboy448** [comment]
> is there a fix?

enable season folders for the series

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
