### ISSUE TITLE
Move episodes sequentially

### ISSUE THREAD

**Issue by giantsfan006** [Sonarr/Sonarr#5130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Most of the time I just want any and all episodes of a series whenever they are downloaded. But sometimes it would be nice to have the option to not move episodes of specific series (or seasons) until all previous episodes have been moved. 

### Describe the solution you'd like

Add an option to "Move Sequentially" so until S01E01 is found, downloaded, and moved the subsequent episodes remain unmoved even if they are already downloaded.

### Describe alternatives you've considered

I know there's already a "Pilot Episode" option but that requires going in and changing that setting once the pilot has been obtained and doesn't prevent, for example, episode 4 from being available before episodes 2 and 3.

### Anything else?

nothing else

**Comment by markus101** [comment]
Within the same download Sonarr will import in order, beyond that we do not have plans to avoid importing until prior downloads are complete.
