### ISSUE TITLE
French (MULTI) name for Search

### ISSUE THREAD

**Issue by YDeltagon** [Sonarr/Sonarr#5133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, here, with **Radarr**, no problem, it searches for the name with different languages, 
but **sonarr**, no, it remains stuck on English names, and, of course, finds nothing on my site, since it does not exist only in french

### Expected Behavior

Either change the search language, 
or do like Radarr, 
or modify the name by hand

### Steps To Reproduce

1. Windows version (nightly build)
2. hmm, euh
3. Search on YGGTorrent
4. Name in english, Yggtorrent not found

### Environment

```markdown
- OS: Windows 10 (nightly build) 
- Sonarr: 3.0.9.1555
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Google chrome 100
```

### What branch are you running?

Develop

### Trace Logs?

n.a.

### Anything else?

![NVIDIA_Share_XTpptMBzgT](https://user-images.githubusercontent.com/70691658/186722842-a96a199f-a240-4d0c-b9fd-9c4a4362ea22.png)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

In this case an alias would need to be request for each series, this is covered in the FAQ.
