### ISSUE TITLE
what about multiple languages supported in V3 now?

### ISSUE THREAD

**Issue by appotry** [Sonarr/Sonarr#5134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Many people want a multiple languages support for their mother tongue

### Describe the solution you'd like

add a multiple languages options in setting -> ui, like radarr has

https://github.com/Radarr/Radarr

### Describe alternatives you've considered

Radarr have developed this feature, migrate this feature from radarr ?

### Anything else?

I found a discussion for this feature many years ago

https://github.com/Sonarr/Sonarr/pull/692

**Comment by markus101** [comment]
That PR landed and is in v3.

**Comment by bakerboy448** [comment]
> That PR landed and is in v3.

I'm assuming they're talking about about true multi-language support

which is moot anyway as it's in v4

**Comment by appotry** [comment]
> > That PR landed and is in v3.
> 
> I'm assuming they're talking about about true multi-language support
> 
> which is moot anyway as it's in v4

So,  When is V4 coming?
