### ISSUE TITLE
Sonarr Repeating Searches in Indexers with "Offset"

### ISSUE THREAD

**Issue by King-Cole** [Sonarr/Sonarr#5136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems that for certain shows, and even certain episodes within shows, Sonarr will direct the Indexer to search with an iterating "Offset", which will eventually cause the search to timeout. Does anyone have an idea what this "Offset" means or why Sonarr is calling for it? I had the same issue with Jackett, so I ended up switching to Prowlarr, but find the same issue there. Attached is a log excerpt from Prowlarr, wherein you can see this "Offset" request, iterating by 100 with each search. This problem only arises when manually searching, the automatic search searches once with an offset of 0.

### Expected Behavior

I'd expect Sonarr to ask for one search of each Index and return the result, without requesting duplicate searches and eventually timing out.

### Steps To Reproduce

1. Manually search for a show. In this example, Harem in the Labyrinth of Another World, S01E01 shows the problem. No other episodes have this issue.
2. Check the logs of the Indexer and see the iterating offset.

### Environment

```markdown
- OS: Linux
- Sonarr: 3.0.9.1549
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

[Sonarr Timeout Trace Log.txt](https://github.com/Sonarr/Sonarr/files/9437369/Sonarr.Timeout.Trace.Log.txt)

### Anything else?

Attached is the error message I get once Sonarr times out from the search.
![Error Message](https://user-images.githubusercontent.com/10054044/187016315-093913ab-7074-411b-a642-6567b4392fd0.png)

**Comment by King-Cole** [comment]
Looks like I forgot to attach the Prowlarr log showing the increasing offset. Note that Prowlarr will only search each index once for every other episode of this show, and even this episode if done with an automatic search instead of manual.
[Prowlarr Log.txt](https://github.com/Sonarr/Sonarr/files/9437380/Prowlarr.Log.txt)

**Comment by PearsonFlyer** [comment]
The offset is pagination. It grabs 0-100 results. Then it grabs 101-200. And so on. 1000 results total, 10 API hits.

**Comment by bakerboy448** [comment]
The issue is your reverse proxy is timing out. Increase the timeout.

not a sonarr bug

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
