### ISSUE TITLE
Sonarr only searches with English keywords in spite of the selected language

### ISSUE THREAD

**Issue by edelgado092** [Sonarr/Sonarr#5137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to search for a new TV show but Sonarr does not find any item. 
For the search I am using an indexer provided by Jackett.
Debugging a bit I can see that Sonarr only uses English keywords despite having Spanish as the only language profile configured.

### Expected Behavior

Sonarr is expected to search according to the selected language profile.

### Environment

```markdown
- Sonarr: 3.0.9.1555
- Docker Install: Yes
- Docker Image: ghcr.io/linuxserver/sonarr:latest
```

### What branch are you running?

Main

### Trace Logs?

Sonarr logs:
```
[Info] ReleaseSearchService: Searching indexers for [House of the Dragon : S01E01]. 2 active indexers
[Info] DownloadDecisionMaker: No results found
```

Jackett logs:
```
Info Torznab search in XXXX for House of the Dragon S01E01 => Found 0 releases
```

### Anything else?

I have checked by manually searching Jackett that if the search keywords are "La Casa del Dragon S01E01" I can find download links.
Also I have checked that on the thetvdb.com there is metadata for the selected language, so sonarr could use it to perform the searches.

**Comment by markus101** [comment]
Sonarr only knows about the English title unless an alias for another language was requested and added, this is covered in the FAQ.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
