### ISSUE TITLE
Massedit to rename .srt like the .mkv files

### ISSUE THREAD

**Issue by klapvogn** [Sonarr/Sonarr#5139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I was starting to rename give my files a new naming scheme but could see it only rename .mkv files and the .srt files are not touched!

Here is a use case, and yes both mkv and srt was named the same, i checked before starting.

`9-1-1 - Lone Star (2020) S02E01 [WEBDL-1080p].mkv`
renamed correct!

`9-1-1 - Lone Star (2020) S02E01 [imdb-tt10323338] [WEBDL-1080p].da.srt`
didn't get touched! 

### Describe the solution you'd like

Add support so massedit handle .srt better when renaming

### Describe alternatives you've considered

Nothing

### Anything else?

Nothing

**Comment by markus101** [comment]
If the SRT is linked to the media file (before it is renamed) it will be renamed when the media file is renamed, for Sonarr to recognize it the filename must be the same as the media file. We do not have plans to have a separate rename for extra files.

If you want to troubleshoot what might've happened to not rename those files. please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by thezoggy** [comment]
since this keeps coming up to note,

these are the same:
`filename.mkv` 
`filename.srt` 

when their are multiple languages for subs externally, doing the language code after the filename and before the extension.. is not supported as the part before the extension are not the same:
`filename.mkv`
`filename.<lang>.srt`


sonarr ideally one day should support the srt with language codes since its been a pretty common thing over the years, but there is prob another github issue already for it

**Comment by markus101** [comment]
Language codes are supported, not every possible code, but `de` is.

**Comment by thezoggy** [comment]
aye, i do see recently there was 
https://github.com/Sonarr/Sonarr/issues/3278
 -- https://github.com/Sonarr/Sonarr/commit/d6dff451e0c4f675cf468612466eb990f416dbed

which looks to handle the 2+3 letter iso codes and some variants noted. 
```        private static readonly Regex SubtitleLanguageRegex = new Regex(".+?[-_. ](?<iso_code>[a-z]{2,3})([-_. ](?<tags>full|forced|foreign|default|cc|psdh|sdh))*$", RegexOptions.Compiled | RegexOptions.IgnoreCase);
```

so user might just not be on develop where this code has landed

**Comment by markus101** [comment]
Language support was in previously, that commit adds support for `forced`, `sdh` and other modifiers.
