### ISSUE TITLE
Add support for native Freebox Download Client 

### ISSUE THREAD

**Issue by YDeltagon** [Sonarr/Sonarr#5140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I would like to use the torrent downloader integrated into our FRENCH BOX Freebox

### Describe the solution you'd like

Use this API to communicate with us : https://dev.freebox.fr/sdk/os/download/

### Describe alternatives you've considered

The use of blackhall torrent, but, even if the freebox manages to add torrents etc..., it created ".mkv" files for example, which sonarr tries to import, but which are not finished
For the moment, I go through qBittorrent, however it's 1PC which remains H24 on while my box can do it.

### Anything else?

If you wish, I am 100% available for tests on a freebox

**Comment by bakerboy448** [comment]
> it created ".mkv" files for example, which sonarr tries to import, but which are not finished

you need a sync setup that keeps the files hidden until they are complete and local. The remote path map common problem section of the download troubleshooting article on the wiki has details for a remote mount/sync setup

**Comment by YDeltagon** [comment]
> 
Yes but, on freebox downloader, you don't HIDE files before finish :'(

![image](https://user-images.githubusercontent.com/70691658/187433183-8add0c81-5538-4a1b-8960-a43b3f252854.png)
![image](https://user-images.githubusercontent.com/70691658/187433291-66acebbd-365f-43ec-9517-fbe633147e4c.png)
![image](https://user-images.githubusercontent.com/70691658/187433364-834fd2a2-abcc-4224-b664-69ec3fb828e2.png)

**Comment by markus101** [comment]
I imagine most people aren’t going to attempt to add support for this u less they have a device when there are download clients others have requested that they could actually get their hands on, I’ve added the appropriate labels, but this may be closed in the future if there is no further interest.

**Comment by cgagnaire** [comment]
I'm interested and I might make this happen.
I've just set up a build environment and I'm looking into it.
