### ISSUE TITLE
Title Slug Override Super/Natural

### ISSUE THREAD

**Issue by Thebeerman90** [Sonarr/Sonarr#5144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Title slug 'supernatural' is in use by series 'Supernatural'. Check the FAQ for more information

Trying to add Nat Geo series [Super/Natural](https://thetvdb.com/series/423144-supernatural) and the title slug for the CW series [Supernatural](https://thetvdb.com/series/supernatural) is already in use.  I've opened a ticket with TVDB but no movement has been made, hoping to have it overridden in Skyhook.

### Expected Behavior

Expected behavior is to add Super/Natural to Sonarr and be appended with (2022) in it's folder name.  i.e "Super-Natural (2022)"

### Steps To Reproduce

1. Have CW series "Supernatural" in Library
2. Attempt to add Nat Geo series "Super/Natural" to Library
3. Receive "Title slug 'supernatural' is in use by series 'Supernatural'. Check the FAQ for more information"
![IMG_20220831_072209_886](https://user-images.githubusercontent.com/45335134/188268892-f675e5d8-400a-4e83-8055-912870372096.jpg)

### Environment

```markdown
- OS: ASUSTOR ADM 4.1.0.RKM1
- Sonarr:3.0.9.1549
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/9482491/sonarr.trace.txt)

### Anything else?

Screenshot pasted above

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

This problem goes beyond the duplicate slug and can result in mismatched releases if the releases also use a similar release name they can be grabbed and linked to the wrong series. We’ll fix the slug, but there may be additional challenges.

**Comment by Thebeerman90** [comment]
I posted it in the Discord #support channel and was told to open a ticket with TVDB (which I did same day) but there hadn't been any movement on it from the Moderators over there for several days now so I figured I'd try another avenue.

**Comment by thezoggy** [comment]
sonarr slugs are local to sonarr, tvdb cant really help you there. 

but anyways just hit up sonarr channel and they can 'fix' the slug on skyhook/sonarr.

**Comment by Thebeerman90** [comment]
> sonarr slugs are local to sonarr, tvdb cant really help you there.
> 
> but anyways just hit up sonarr channel and they can 'fix' the slug on skyhook/sonarr.

I mentioned that I did that already in the reply above, the support channel on Discord recommended opening a ticket on TVDB to correct the name.  TVDB hasn't moved on the ticket at all so I was hoping for a better outcome here.

**Comment by markus101** [comment]
The slug has been updated.
