### ISSUE TITLE
Requests per minute

### ISSUE THREAD

**Issue by SaschMie** [Sonarr/Sonarr#5145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some indexers temp ban sonarr for too many requests

### Describe the solution you'd like

It would be good to set a request limit in the settings, so that sonarr will not send all requests at the same time to an indexer. Sonarr could do a queue for the requests to pass the limit setting.

### Describe alternatives you've considered

I see no alternative for this.

### Anything else?

No

**Comment by markus101** [comment]
Sonarr already has mechanisms in place to adhere to request limits, which includes throttle requests temporarily.

We do not have plans to add a setting or space out requests to avoid hitting limits in the event the indexer has very aggressive limits, often seen with free/trial indexers.
