### ISSUE TITLE
"Download Linux .tar.gz" button on sonarr.tv provides windows zip instead of linux tar.gz

### ISSUE THREAD

**Issue by dansmith01** [Sonarr/Sonarr#5147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "Download Linux .tar.gz" button on [sonar.tv](https://sonarr.tv/#downloads-v3-linux-other) (screenshot below) provides different files based on unknown criteria.

<img width="735" alt="download_tar_gz" src="https://user-images.githubusercontent.com/2066273/188506186-a5ccb8f0-2ce6-4b00-9f1c-932046176498.png">

* Via Opera browser on Windows = `Sonarr.main.3.0.9.1549.linux.tar.gz`
* Via curl or wget from Ubuntu CLI = `Sonarr.main.3.0.9.1549.windows.zip`

Not a typo - windows users get linux.tar.gz and linux users get windows.zip!

Notably, `Sonarr.Mono.dll` is missing from windows.zip, leading to installation issues on linux.

### Expected Behavior

Since the button is labelled "Download Linux .tar.gz", I would expect it to provide me with Linux .tar.gz, regardless of my user agent or any other criteria drawn from my request headers.

### Steps To Reproduce

In Ubuntu 20.04:

```bash
# The button links to the URL below.
wget -L -o sonarr.tgz https://services.sonarr.tv/v1/download/main/latest?version=3&os=linux
file sonar.tgz
# It's a zip file
unzip sonar.tgz
ls Sonarr | grep Mono
# Sonarr.Mono.dll is missing
```

On a windows browser (tested in Opera here):
Go to `https://sonarr.tv/#downloads-v3-linux-other`.
Click "Download Linux.tar.gz"
Extract with 7zip or similar.
Sonarr.Mono.dll is present.

### Environment

```markdown
- OS: Ubuntu 20.04 / Windows 10
- Sonarr: 3.0.9.1549
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Opera 90.0.4480.78
```

### What branch are you running?

Main

### Trace Logs?

```bash
wget -L -o log.txt https://services.sonarr.tv/v1/download/main/latest?version=3
head -n 11 log.txt
--2022-09-05 13:00:28--  https://services.sonarr.tv/v1/download/main/latest?version=3
Resolving services.sonarr.tv... 104.26.0.163, 104.26.1.163, 172.67.70.98
Connecting to services.sonarr.tv|104.26.0.163|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://download.sonarr.tv/v3/main/3.0.9.1549/Sonarr.main.3.0.9.1549.windows.zip [following]
--2022-09-05 13:00:29--  https://download.sonarr.tv/v3/main/3.0.9.1549/Sonarr.main.3.0.9.1549.windows.zip
Resolving download.sonarr.tv... 104.26.1.163, 172.67.70.98, 104.26.0.163
Connecting to download.sonarr.tv|104.26.1.163|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20693823 (20M) [application/zip]
Saving to: 'latest?version=3'
```

### Anything else?

This appears to have been an issue for a while - the following Reddit post describes the same sort of behavior occurring eight months ago.
https://www.reddit.com/r/sonarr/comments/rvczio/sonarr_v3_wont_start_cant_find_sonarrmono_centos

**Comment by thezoggy** [comment]
when you download the windows package you are getting an installer. when you download the linux > other, your not getting a package but the source. think of it just like grabbing the source from github.  if you want a linux package you get it from your package manager / sonarr repo that you add to apt.

**Comment by dansmith01** [comment]
Oop, just realized I need to put the URL in quotes since it has an `&`.

`curl -L -o sonarr.tgz "https://services.sonarr.tv/v1/download/main/latest?version=3&os=linux"`

Grabs the expected linux.tar.gz
