### ISSUE TITLE
My Anime List integration

### ISSUE THREAD

**Issue by snoopy82481** [Sonarr/Sonarr#5148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The issue is not related to a problem.  My Anime List has an API for connecting to the lists available there.

### Describe the solution you'd like

The ability to add My Anime List as an option in `Settings > Import List`.

### Describe alternatives you've considered

Continue with manually adding Anime series to the application.

### Anything else?

[MyAnimeList authorization Documentation](https://myanimelist.net/apiconfig/references/authorization)
[MyAnimeList API (beta ver.) (2) Documentation](https://myanimelist.net/apiconfig/references/api/v2)

**Comment by thezoggy** [comment]
sonarr uses tvdb, i dont see tvdb info being returned on myanimelist? so doesnt look like it could be used

**Comment by markus101** [comment]
In addition to lacking TheTVDB information it appears there would be multiple entries for different "seasons" (as they are listed on TheTVDB) of the same series so even if the title matched for the original series it's likely going to result in bad matching.

I don't see this being something we'd implement or support given how poorly title based match can be.

**Comment by GNS7** [comment]
Support for Anilist would be good too, but I don't know if it is possible.

**Comment by snoopy82481** [comment]
> In addition to lacking TheTVDB information it appears there would be multiple entries for different "seasons" (as they are listed on TheTVDB) of the same series so even if the title matched for the original series it's likely going to result in bad matching.
> 
> I don't see this being something we'd implement or support given how poorly title based match can be.

I think if there is XEM linking it could work.  Since there is already logic for searching Anime against XEM to TVDB id.  Other option would be to add an additional metadata source to AniDB, then again using XEM to aggregate the data to TVDB id. It could allow for XEM to be updated programmatically instead of manually. 

I think the benefit of the additional metadata source would be better grabs on anime.  The downside, another metadata source to monitor for API changes and updates.

**Comment by thezoggy** [comment]
> > In addition to lacking TheTVDB information it appears there would be multiple entries for different "seasons" (as they are listed on TheTVDB) of the same series so even if the title matched for the original series it's likely going to result in bad matching.
> > I don't see this being something we'd implement or support given how poorly title based match can be.
> 
> I think if there is XEM linking it could work. Since there is already logic for searching Anime against XEM to TVDB id. Other option would be to add an additional metadata source to AniDB, then again using XEM to aggregate the data to TVDB id. It could allow for XEM to be updated programmatically instead of manually.
> 
> I think the benefit of the additional metadata source would be better grabs on anime. The downside, another metadata source to monitor for API changes and updates.

there are already a 1000+ shows in xem, that all it does is link anidb to tvdb.  ideally anidb isnt really needed.. except to deal with the crazy naming schemes and having an id helps. but only if the indexer supports returning results by the id.   now tvdb has many metadata fields, one could just get them to add anidb field and store it on tvdb, just like imdbid and the other related scraper fields. then can just keep using tvdb data and less dependent on others, while allowing it to be somewhat open to people to update.

**Comment by xndko** [comment]
Support for Anilist would be phenomenal. I believe Anilist has significantly better dev support compared to MAL, and provides an [API](https://anilist.gitbook.io/anilist-apiv2-docs/); similar tools like Flexget make use of it iirc. 

Managing anime is - as far as I'm aware - kind of limited at the moment. No simple method of tracking up-and-coming shows and importing them to Sonarr automatically. Being able to automatically import all shows from an Anilist user's "planning" or "watching" list would make managing anime on Sonarr significantly easier.

**Comment by Kurozeto** [comment]
Just as a note to keep the thread alive.

There is an old plugin for Plex called HamaTV that enables support for AniDB. If it gets an AniDB match, it can use AniDB's relation graphs to create a Plex Collection. This way un-categorized seasons and movies can be pulled together into one location, so you don't have to pull them under a "Specials" season.

I make this note simply to bring up that AniDB does have an overarching "Relation Graph" than can be queried to categorize shows and movies easily, and might be of use to the anime community that uses Sonaar. Here is an example of one of these aforementioned "Relation Graphs" detailing a rather complex show to catalogue in digital libraries. https://anidb.net/anime/6327/relation/graph

**Comment by mizz141** [comment]
Maybe Plex Meta Manager would be a solution for your problem.

https://github.com/meisnate12/Plex-Meta-Manager

https://metamanager.wiki/en/latest/config/myanimelist.html

**Comment by noggl** [comment]
Not completely the same thing, but I've created a script that adds your AniList "plan to watch" shows to Sonarr and Radarr. I'm in the middle of re-organizing the repo, but if you're interested in helping me test I'd appreciate it!
It's here if you want to give it a shot https://github.com/noggl/AniPlanrr

**Comment by markus101** [comment]
I don't think anyone is actively looking into this issue at this time.

**Comment by noggl** [comment]
@iceypotato, if you need help with relating MAL ids to something Sonarr can ingest let me know!

**Comment by markus101** [comment]
With Simkl Sonarr uses Servarr (cloud service hosted by the folks that worked on Radarr/Lidarr/Readarr) to handle the oauth redirect, this logic lives in `SimklImportBase`, it does a similar for Trakt (through Servarr's server). For Plex, Sonarr does the same, but it doesn't require the redirect URL so it doesn't go through another server.

`startOAuth` and `getOAuthToken` in `RequestAction` handle making the request and handling the response.
Servarr's auth logic is here I believe: https://github.com/Servarr/ServarrAPI.Auth

**Comment by noggl** [comment]
> > @iceypotato, if you need help with relating MAL ids to something Sonarr can ingest let me know!
> 
> @noggl Hello, I got to the step where I grabbed the animes on my user page, and now we are trying to figure out how we can get from MAL ids to TVDB ids. What do you suggest?

I'd use https://github.com/Fribb/anime-lists or https://github.com/manami-project/anime-offline-database, that's what I use for https://github.com/noggl/AniListToTVDB. If you have a repo I can clone I would be happy to write the translation for you and open a PR.

**Comment by DiegoFleitas** [comment]
While this is being worked on I decided to switch to sonarr v4 which supports custom lists already and make a fork of [another helpful project](screeny05/letterboxd-list-radarr) to create custom lists and successfully managed to add my personal MAL plan to watch list tracked on my sonarr instance.
[This is my fork](https://github.com/DiegoFleitas/mal-list-sonarr) which anyone can host for free on render, if anyone is interested
