### ISSUE TITLE
Activity > Queue : Sorting by name doesn't work

### ISSUE THREAD

**Issue by thelimp** [Sonarr/Sonarr#5151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,
In Sonarr (and Radarr too) sorting by name in the queue section doesn't work
![image](https://user-images.githubusercontent.com/41955403/189707156-5e7b9141-7b5c-4e47-b2d8-90b834a0a3b4.png)

### Expected Behavior

File names in correct order

### Environment

```markdown
- Sonarr: 3.0.9.1549
- Docker Install: yes
- Using Reverse Proxy: No
- Browser: Brave 1.43.89
```

### What branch are you running?

Main

### Trace Logs?

No

### Anything else?

No

**Comment by markus101** [comment]
Since most of the screenshot is redacted I can’t tell, are these items matched to a series and episode or failed to match?

An unedited screenshot of the entire queue would be helpful.

**Comment by markus101** [comment]
Despite the lack of details it looks like my assumption was correct, next time please provide the requested information so we don't have to guess whether we're solving the right problem.
