### ISSUE TITLE
Select Download client by TV show name

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#5152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have multiple nas drives and my shows divided between different drives. I would like to be able to select which download client a  tvshow  uses as that allows me to get hardlinks instead of copy for all my torrent downloads. After playing around with QBitorrent and sonarr I realised that I can add the same torrent client to sonarr but select different categories this way I can use one client but have qbittorrent download to different directories  according to the categories. But I am stuck as I require sonarr to send the tvshows to client according to the tvshow. 

### Describe the solution you'd like

a tag system where shows with a particular tag are downloaded with a particular client set in sonarr

### Describe alternatives you've considered

I have considered limiting shows to different trackers using tags and then those tracker to different clients. But that makes it a lot more complicated and at the same time dividing shows by tracker to different nas drives is not practical 

### Anything else?

a

**Comment by markus101** [comment]
This would be done by tags, which is covered by https://github.com/Sonarr/Sonarr/issues/402
