### ISSUE TITLE
Group CFs Feature

### ISSUE THREAD

**Issue by ItsME6969** [Sonarr/Sonarr#5153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Just putting this out there. Requesting a feature to group CFs. Kinda like folders. Been using v4 for some time now and the only thing I dont really like about CFs vs whats in V3 is that in v3 regexes could be grouped. So maybe a feature to be able to drag and drop or add however to groups.
PS I'm not suggesting a change in the way CFs work just a way to tidy up the interface i.e if somebody wants to group all CFs that deal with audio into a group of its own, they can.

### Describe the solution you'd like

Folder-like grouping of CFs

### Describe alternatives you've considered

None other

### Anything else?

Nope

**Comment by markus101** [comment]
At this time it's not something we have planned.
