### ISSUE TITLE
PageJumpBar - No longer shows on firefox

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#5157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

page jump bar no longer showing up on firefox, and on chrome while it appears the hit targets are very tiny and not like before. to note, radarr pagejump + target area is fine.

### Expected Behavior

work as it did before, show up and clickable

### Environment

```markdown
- OS: Windows 10
- Sonarr: 3.0.9.1555
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox 104.0.2
```

### What branch are you running?

Develop

### Trace Logs?

N/A

### Anything else?

![Discord_2022-09-16_17-25-42](https://user-images.githubusercontent.com/500882/190822106-81124b7b-b9c6-4635-80ca-b9a1b4b68ec4.png)

vs radarr:
![image](https://user-images.githubusercontent.com/500882/190822403-1266c6ef-2d04-4a04-9a1d-a43e60065aeb.png)

**Comment by markus101** [comment]
It only shows when you're sorting by title.
