### ISSUE TITLE
Sonarr not showing remote volume

### ISSUE THREAD

**Issue by daNutzzzzz** [Sonarr/Sonarr#5162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

System > Disk Space > Location does not show the docker volume that is mapped to the underlying host (ubuntu server) mount to a remote NAS CIFS share.

### Expected Behavior

System > Disk Space > Location displays the volume and the space stats.

### Steps To Reproduce

1. On underlying Docker Host (ubuntu server), mount remote CIFS share (//<REMOTE HOST IP>/Share   /mnt/<MOUNT NAME> cifs defaults,rw,credentials=/mnt/nas-credentials,uid=1000,gid=1000,nobrl)
2. Map Sonarr container volume to the above mount path.

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS
- Sonarr: 4.0.0.115 (v4-59225fc by hotio) (hotio/sonarr:v4)
- Docker Install: 20.10.18, build b40c2f6
- Using Reverse Proxy: No
- Browser: MS EDGE
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/9624857/sonarr.debug.txt)
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/9624858/sonarr.txt)

### Anything else?

This is also not working in Radarr
This is working correctly in Lidarr & Readarr

**Comment by markus101** [comment]
At this time we're not investigating issue with the pre-alpha version of Sonarr. Given this is also happening in Radarr we'll wait on the outcome of https://github.com/Radarr/Radarr/issues/7613.
