### ISSUE TITLE
Update Message doesn't go away after reload

### ISSUE THREAD

**Issue by jandreaucodes** [Sonarr/Sonarr#5163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just updated to the latest build and keep getting a popup saying "Sonarr has been updated to version 3.0.9.1549, in order to get the latest changes you'll need to reload Sonarr."

I reload, it comes back.
I X out of it, it comes back.
I restart, it comes back.

Anyone else seeing this or know a fix?

### Expected Behavior

Notification modal goes away after reload

### Steps To Reproduce

Upgrade to the latest build and refresh the app from the modal.

### Environment

```markdown
- OS: macOS 12.6
- Sonarr: 3.0.8.1549
- Docker Install: None
- Using Reverse Proxy: Yes
- Browser: All
```

### What branch are you running?

Main

### Trace Logs?

I can't get to them, because the UI won't let me out of this modal.

### Anything else?

Video or issue: https://share.cleanshot.com/rQgdNl

**Comment by jandreaucodes** [comment]
Note: After about fifty "reloads", it eventually went away, but was clearly an issue.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

We've seen this happen previously with reverse proxies that ignore the do not cache rules of some of Sonarr's files, namely CloudFlare.
