### ISSUE TITLE
Advanced Per-Show Usenet/Torrent Query Settings

### ISSUE THREAD

**Issue by rlad78** [Sonarr/Sonarr#5165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

On multiple occasions, there can be discrepancies between Sonarr's constructed search query and the format that release groups have chosen to use for their releases. This results in releases not being able to be found by Sonarr and requires manual intervention from users to pull in these episodes externally.

For example, consider the animated Castlevania series. According to Prowlarr, searching for the first episode in the fourth season of Castlevania will prompt Sonarr to send the following queries:
- Castlevania 2018 23
- Castlevania 23

However, there are no release groups that have titled their release using the season-agnostic episode number. They are all using S04E01 for their format. As a result, Sonarr isn't able to find any releases to parse.

### Describe the solution you'd like

A "Custom Query" button on the individual series page, most likely on the top where "Series Monitoring" and "Edit" are located. This button could open up a dialog window similar to the one used in *Settings -> Media Management -> Episode Naming -> Standard Episode Format" where users could supply variables like `{Series Title}` and `{Episode Number}` that Sonarr would fill in before submitting its query. Just like *Standard Episode Format,* it would be helpful to have a demo preview of what the resulting search query could look like.

A lot of the variable labels in *Standard Episode Format* could be carried over to this feature, but some additions and considerations would need to be made. For example, there is no way to specify whether to use episode numbers relevant to seasons vs. season-agnostic one (e.g. `S02E01` vs `13`).

Having the ability to define multiple of these queries would be a nice additional functionality, but I personally do not believe it is required.

This should be a sort of "last resort" feature that a user should only have to use if there are difficulties pulling in relevant releases from indexers/trackers.

### Describe alternatives you've considered

Prowlarr, NZBHydra, and other indexer managers can help find and download releases that Sonarr is not able to, but for larger series this can be a heavily manual procedure. Having the ability to edit the queries turns a "tasks per episode" manual workload into a "task per series" one.

### Anything else?

The *Standard Episode Format* dialog window that is referred to multiple times:

![image](https://user-images.githubusercontent.com/5733291/192337658-6f93a45b-7ea5-4f97-ac78-353604427db0.png)

**Comment by thezoggy** [comment]
- set the series to standard not anime if you want standard format S#E#  
- searching is generally done by tvdbid not by string search, that is only as a fall back or if site doesnt support id searching
- this sort of feature would cause support nightmare

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

you have the wrong series type, there's no issue to fix. Just a common user error.

https://wiki.servarr.com/sonarr/troubleshooting#wrong-series-type

**Comment by markus101** [comment]
As mentioned this is controlled by the series type. We do not have plans to add custom search options.
