### ISSUE TITLE
Enhancing webhook and custom script

### ISSUE THREAD

**Issue by zhdenny** [Sonarr/Sonarr#5166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

-

### Describe the solution you'd like

Radarr provides a means to transmit Custom Formats and Related Scores in their Settings-->Connect page. This is especially useful for Notifiarr to parse.

Can Sonarr enhance the webhook and custom script options to provide additional information to services like Notifiarr? For example Scores and Preferred Words / Custom Formats?

### Describe alternatives you've considered

-

### Anything else?

-

**Comment by Devon1984** [comment]
Id second this. If Notifiarr could be natively supported that would really be appreciated as its a big part of my system and many other peoples systems.

**Comment by bakerboy448** [comment]
Custom Scripts added with #5167 

webhooks outstanding
