### ISSUE TITLE
Add Thai as a Language 

### ISSUE THREAD

**Issue by Amandaville** [Sonarr/Sonarr#5170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I like to watch Thai language shows and there is no option in language profiles for Thai language.

### Describe the solution you'd like

Please add "Thai" to language profiles

### Describe alternatives you've considered

I don't believe there is an alternative.

### Anything else?

Nothing else.

**Comment by markus101** [comment]
We’re going to need example file names in order to know how to parse those releases.

**Comment by Amandaville** [comment]
> We’re going to need example file names in order to know how to parse those releases.

Thai Cave Rescue (2022) https://www.imdb.com/title/tt8726102

The Stranded (2019) https://www.imdb.com/title/tt9310400

Girl From Nowhere (2018) https://www.imdb.com/title/tt8824648

Remember Me (2022) upcoming but I can't find an imdb link

**Comment by Amandaville** [comment]
> We’re going to need example file names in order to know how to parse those releases.

Thai.Cave.Rescue.S01.THAI.1080p.WEBRip.x265-RARBG

Girl.from.Nowhere.S02.THAI.1080p.NF.WEBRip.DDP2.0.x264-PAAI[rartv]

The.Stranded.S01.THAI.1080p.NF.WEBRip.DDP5.1.x264-NTG[rartv]

Samui.Song.2017.THAI.1080p.BluRay.H264.AAC-VXT

**Comment by Amandaville** [comment]
Is that the information you were looking for, or do you need something else?

**Comment by Amandaville** [comment]
> We’re going to need example file names in order to know how to parse those releases.

I see this is still marked waiting-for-info 3 days later.  Is there something else you need from me other that what I provided?
