### ISSUE TITLE
Improper Importing

### ISSUE THREAD

**Issue by hellot1m** [Sonarr/Sonarr#5176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When fetching episode for Steven Universe Future, Sonarr imports to another show (within sonarr) and folder called Steven Universe. Two different shows (although the same... Steven Universe Future is technically Season 6 of Steven Universe but thats besides the point and not related to this error.)

### Expected Behavior

When fetching episode for Steven Universe Future, it should be imported to the Steven Universe Future folder. 

### Steps To Reproduce

1. Add Steven Universe
2. Add Steven Universe Future
3. Add any tracker
4. Search using interactive and selecting ANY file named Steven Universe Future

Use the interactive option so you can visually see that the file being grabbed is named for the correct show. 

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 3.0.9.1555 (this issue has been present since 2020, not a new issue)
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Any
```

### What branch are you running?

Develop

### Trace Logs?

too long. having issues pasting log here

### Anything else?

none.

**Comment by markus101** [comment]
I guess just like asking people to fill in the template... I've wasted enough time here then.

**Comment by markus101** [comment]
Alias has been corrected.
