### ISSUE TITLE
Sonarr not getting covers

### ISSUE THREAD

**Issue by Milincho** [Sonarr/Sonarr#5177]
Read https://github.com/Sonarr/Sonarr/issues/3043 and 3 years later this is still happening:

https://thetvdb.com/series/the-walk-in has a correct cover in TVDB but nothing is displayed in Sonarr.

How to fix this?

**Comment by Milincho** [comment]
Even more strange, the covers are correctly download in their proper folder: https://i.imgur.com/0dJGhoe.png

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

One of the most common causes is the images aren’t marked as English and instead as no language or another language.
