### ISSUE TITLE
Upgrade to multi-episode files = breaks import

### ISSUE THREAD

**Issue by spikysimonw** [Sonarr/Sonarr#5178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When upgrading an existing show, in my case using a season pack (not sure if this contributes to the problem), if there is a multi-episode file (like often the case for a double-header season finale), something falls over during the imported process.

End result is the old files gets removed but the replacement file is only assigned to the first episode, looking like the second part / next episode is missing.

Suspect it's a timing issue: episodes processed in order, when processing the penultimate episode the older file for the next/final episode is still on the disk.

Obviously exactly the same season pack works fine if downloaded from scratch (without already being older files to upgrade).

### Expected Behavior

Standard upgrade process: old files removed, replaced by newer files, mapping / metadata / filenames updated etc.

### Steps To Reproduce

1. Download a season of a show at lower quality, including a finale that spans two episodes but split across two files ("ABC - S01E09 - The Big Ending (1)" and "ABC - S01E10 - The Big Ending (2)".
2. Upgrade season to a better quality (using a season pack definitely does this) this time with double-header episode in a single file ("ABC - S01E09-10 - The Big Ending").

### Environment

```markdown
- Sonarr: 3.0.9.1555
- Docker Install: Yes (3.0.9.1555-ls307 by linuxserver.io)
- Using Reverse Proxy: No 
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

Unavailable

### Anything else?

Recently upgrade a whole load of shows using higher quality season packs. Stumbled into this error frequently (ie. whenever there was a double-header involved) although it took me quite some time to realise exactly what was going on - the "Activity" UI gets messy when there's an error involving a season pack as all the episodes relating to that pack show as erroring.

**Comment by markus101** [comment]
This particular case should be handled correct already, both files being replaced by the multi-episode file should be deleted and unlinked before the import, if that fails then the import shouldn’t continue. Unless Sonarr failed to parse the multi-episode file being imported.

We definitely need more information from the import, especially for the multi-episode file.

**Comment by markus101** [comment]
We can reopen if additional information provides enough information to investigate further.
