### ISSUE TITLE
No Scheduled Tasks

### ISSUE THREAD

**Issue by kylerw** [Sonarr/Sonarr#5181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No scheduled tasks are available

### Expected Behavior

Scheduled tasks would be available and running

### Environment

```markdown
- OS: Unraid
- Sonarr:latest
- Docker Install:yes
- Using Reverse Proxy:
- Browser:chrome
```

### What branch are you running?

Main

### Trace Logs?

NA

### Anything else?

![5EAFE3AF-846B-4590-BB14-B3004BBC84D4](https://user-images.githubusercontent.com/370860/194716964-69e218e2-73f7-41cb-bdb4-258f83e430ff.jpeg)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

database is corrupt see the malformed db entry in the faq
