### ISSUE TITLE
Import Trakt.tv list whit some not in list

### ISSUE THREAD

**Issue by RedBull01** [Sonarr/Sonarr#5182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi All.

I create a simple list (https://trakt.tv/lists/24083721):
All Streaming Service
2022-2022
English

Import some from other year like: 1998, 2008...

### Expected Behavior

Only 2022

### Steps To Reproduce

Import List
Trakt List
Add:
Username
List Name
Years: 2022

Authenticate with Trakt
Test
Save

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr:3.0.9.1549
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser:Chrome
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/9740424/sonarr.txt)

### Anything else?

![img](https://user-images.githubusercontent.com/47831034/194730667-68c06711-dd08-4163-8ee2-ec5de173b70b.png)

**Comment by thezoggy** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by markus101** [comment]
Your logs are not not trace logs, please provide trace logs.

Additionally please provide a screenshot of the list settings you used.

**Comment by markus101** [comment]
Can reopen if additional requested information is provided.
