### ISSUE TITLE
feature request audio description 

### ISSUE THREAD

**Issue by Mrpuppyz** [Sonarr/Sonarr#5183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently no options for audio description in language profiles

### Describe the solution you'd like

I would like the sonarr and radarr to have the option to add audio description under the add language profile. This would help for people that are blind and for people like me that would like to listen to a show/movie while driving.

### Describe alternatives you've considered

Alternative to this would be a Jellyfin/Plex plugin for download audio description similar to the way opensubtitles works on Jellyfin. I have tried searching for such plugin with no success. 

### Anything else?

In my case I would have two languages profiles one for just regular English without descriptions for nondriving watching and a second profile with English audio description for driving/listening.

**Comment by markus101** [comment]
This would be best handled with preferred words (v3) and custom formats (v4, pre-alpha).

We don’t have plans to add this to the existing language profiles.
