### ISSUE TITLE
Sorting queued items (Activity > Queue)

### ISSUE THREAD

**Issue by rhayy** [Sonarr/Sonarr#5184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When clicking on any of the column titles, the list of items stays as is, i.e. no sorting.
I need to refresh the page to make it work.

### Expected Behavior

I expect the list to be sorted alphabetically (or anti-alphabetically) on the click action.

### Steps To Reproduce

1. Reach the "Queue" page
2. Click on one of the columns in the table (e.g. Episode Title)

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-48-generic x86_64)
- Sonarr:Version    3.0.9.1549
- Docker Install: No
- Using Reverse Proxy: Yes (nginx)
- Browser: Firefox 105.0.2/Chromium 105.0.5195.125
```

### What branch are you running?

Main

### Trace Logs?

no events written

### Anything else?

I didn't notice anything else related to this event.

**Comment by bakerboy448** [comment]
F12 => browser dev console;   Is signalr connected successfully?

**Comment by rhayy** [comment]
Yes, it seems so:
![Capture d’écran du 2022-10-12 11-57-45](https://user-images.githubusercontent.com/34841166/195315830-801ae5c7-1456-41ac-9a96-5aa9611e4620.png)

**Comment by markus101** [comment]
Queue re-ordering via manual clicks does not rely on signalR, XHR requests are made for that, subsequent updates would come in via signalR though.

I'm unable to reproduce this issue in Chrome or Firefox on Windows or Chrome on iOS 16.

Please provide a screenshot of the items in the queue so we have more information on what's there (are they items matched to series/episodes are all unmatched, etc).

**Comment by rhayy** [comment]
I have done nothing but it is now working as expected.
I close the issue unless it happens again.
Thank you for your help.
