### ISSUE TITLE
Custom Named Duplicates Not Removed

### ISSUE THREAD

**Issue by hbednar** [Sonarr/Sonarr#5185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using a custom naming scheme:
name (year) - S01E01 1080x1920.mkv

At the moment when two copies of the same episode but with different quality are downloaded they are both kept. I then have to delete them my self.

I think it may be similar to this issue:
https://github.com/Sonarr/Sonarr/issues/4716

### Expected Behavior

When two copies of the same episode are downloaded the one with the lowest resolution should be deleted.

### Steps To Reproduce

1. Search and download episode
2.  Rename episode to custom format
3. Scan in import the new episode
4. Repeat the above steps and both episodes will be saved.

### Environment

```markdown
- OS: Debian 11 and Debian sid
- Sonarr: 3.0.9.1555
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Any
```

### What branch are you running?

Develop

### Trace Logs?

https://pastebin.com/raw/NwjwUs6m
### Anything else?

No

**Comment by bakerboy448** [comment]
> Which logs do you need.
>> Trace Logs (https://wiki.servarr.com/sonarr/troubleshooting#logging-and-log-files)
Generally speaking, all bug reports must have trace logs provided.
*** Info Logs are not trace logs. If the logs do not say trace and are not from a file like *.trace.*.txt they are not trace logs.***

from the bug report template

**Comment by markus101** [comment]
Before importing Sonarr deletes the existing file, if there is no file linked to the episode nothing is deleted, but if the delete fails it will not be imported.

Episode history should show whether the file was linked to the episode and you can also see which files are currently linked to each episode via manage episodes.

**Comment by zero77** [comment]
@bakerboy448
Thanks, I will provide a copy of these logs.
Do you want me to whate until this next happens or just use any logs i have now.

@markus101 
I Have to go through manually and check this so, i am not always aware when this is happening.

When clicking on an episode, i can see the file and full file path listed under details and under history i can see multiple episodes listed.

Even though there is only one file listed under details there are multiple on disk.

**Comment by hbednar** [comment]
@bakerboy448
Thanks, I will provide a copy of these logs.
Do you want me to whate until this next happens or just use any logs i have now.

@markus101
I Have to go through manually and check this so, i am not always aware when this is happening.

When clicking on an episode, i can see the file and full file path listed under details and under history i can see multiple episodes listed.

Even though there is only one file listed under details there are multiple on disk.

**Comment by hbednar** [comment]
As requested i have attached some logs, in this example some files are mkv and some mp4 but this does not always happen.

The first part is the directory contents, the second part is a rescan with trace turned on and the last is a rescan after i deleted all the mp4 files, i hope this helps.

https://pastebin.com/raw/NwjwUs6m

**Comment by markus101** [comment]
> When clicking on an episode, i can see the file and full file path listed under details and under history i can see multiple episodes listed.

Post a screen shot of this. Using Lost in Space, season 3 episode 6 I see two distinct files there, one is 1920x1080 in MKV format and the other is 1920x800 in MP4 format, which of these files did Sonarr actually originally import?

> Even though there is only one file listed under details there are multiple on disk.

Right, Sonarr only tracks one file per episode, if there are multiple because something duplicated then or converted to a similar quality and never cleared the original than Sonarr won’t do anything when upgrading quality.

A single instance of Sonarr is never going to import both an MP4 and MKV is slightly different resolutions, it looks like something else is mucking with your files and causing you issues.

Do you have something like tdarr running that is converting from MKV to MP4 and removing hardcoded black borders? Regardless of where they are coming from, this is beyond the scope of a Sonarr bug, this is coming from somewhere else, you may be able to get help via one of Sonarr’s support channels (Forums, Reddit, Discord, etc), but this is not a Sonarr bug.

**Comment by hbednar** [comment]
@markus101 
I have since realized there is three files per episode one is mp4 and the others are mkv and i believe all were downloaded by Sonarr.

Perhaps i have misunderstood but, i was under the impression that Sonarr would keep the highest quality copy and remove the lower quality copies, which is what i am after.

**Comment by markus101** [comment]
Yes, that's what it does, but as I said in my first reply if it fails to delete it won't import another copy. Unless there is something else making copies or importing to the same folder (be it multiple instances of Sonarr or other apps), there should be no reason that the folder would ever look like this. Nothing in the logs indicates that Sonarr imported a new file form the download folder and failed to delete a file, but still imported it anyways.

```
'Lost in Space (2018) - S03E06 1920x1080.mkv'
'Lost in Space (2018) - S03E06 1920x800.mkv'
'Lost in Space (2018) - S03E06 1920x800.mp4'
```

Yes, 3 different versions here, not two, but besides resolution and extension it's impossible to tell from the file names that they are different qualities and again, this isn't something Sonarr would keep around (and logs don't show it's doing that, just that it saw a different file for the same episode).

Episode history will give some indication where each episode was imported from (if it was from outside the series folder) and why existing episode files were unlinked, but that'd be best investigated in one of the support channels.

**Comment by hbednar** [comment]
Ok thanks, i will do some further investigating into why it was or wasn't imported and why is isn't being deleted.
