### ISSUE TITLE
Clone/Duplicate Feature for Release Profiles

### ISSUE THREAD

**Issue by AYColumbia** [Sonarr/Sonarr#5190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I always have to create a release profile from scratch rather than build from an existing one so it's a bit of a pain at times.

### Describe the solution you'd like

Please add a clone or duplicate feature like Quality Profiles.

### Describe alternatives you've considered

Not available from what I can see.

### Anything else?

The view is under Settings > Profiles.

**Comment by bakerboy448** [comment]
Why can't you just have multiple profiles and then apply them via tags?  Why do you need to duplicate the same profile and make minor changes rather than just segmenting those into their own profile?

**Comment by markus101** [comment]
Please describe the exact problem this would solve (why do you need to clone them multiple times).

What exactly are you needing to clone and repeat multiple times?
Why wouldn't tags work?
Are you using preferred words or must contain/must not contain?

**Comment by AYColumbia** [comment]
Hi,
So what you all have suggested was what I tried first but it's not working.  I first had created 2 release profiles, 1 for HD and 1 for SD.  The latter was the "fallback" profile.  I assigned tags to each one, i.e., HD and SDTV respectively.  I tried using the tags on the series but only the first tag was followed.  If no entries were found for the HD tag then SDTV was ignored.  I noticed this when I looked at why nothing matched and noticed the entries that matched SDTV were not included due to the reason stated which was something like "Does not contain one of the required terms: x265, hevc, 720, 1080, x264, h264, h.264, avc" which were only included on the HD tag's profile.

Maybe I'm not using the tags right due to misunderstanding how they work?  I also tried adding a series-specific tag that I added to both release profiles but, again, only the first tag's terms were adhered to.

For now, I created one release profile to cover what I need but the reason for cloning is just to help with not having to remember exact tag names and having to reenter the priority list in the Preferred list.

Thank you and let me know if you need anything else.

**Comment by bakerboy448** [comment]
Must contains across profiles means both profiles' must contains must be matched

It's an AND relationship across profiles

**Comment by markus101** [comment]
> For now, I created one release profile to cover what I need but the reason for cloning is just to help with not having to remember exact tag names and having to reenter the priority list in the Preferred list.

As of v4 preferred words will be no longer be a thing, they will be replaced with Custom Formats.

Release profiles apply to all series unless tags are used.

Given the most complicated part of Release Profiles is moving to a different section this isn't something we're going to add at this time.

**Comment by AYColumbia** [comment]
Okay, thanks for the update.  Looking forward to v4. :)
