### ISSUE TITLE
Allow season packs within during week of finale air date.

### ISSUE THREAD

**Issue by gl0ryus** [Sonarr/Sonarr#5191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

In the era of streaming services and exclusive shows. Many shows release the night prior the air date, for example Apple released its finale for See tonight the 13th but according to Sonarr its expected on the 14th. The individual episode will be accepted no problem, but will reject a season pack for "all episodes haven't aired".

### Describe the solution you'd like

Instead of requiring the dates to line up, I would like to see it be UTC-1 day to allow for these shows be pulled via release profiles I've got set up.

### Describe alternatives you've considered

No real alternatives to consider outside of monitoring and pulling manually.

### Anything else?

![image](https://user-images.githubusercontent.com/96798013/195752410-19380577-9a5f-48f1-bad0-03eb69dfecde.png)
![image](https://user-images.githubusercontent.com/96798013/195752321-4610ea3c-d15c-497d-966c-93a977cebc20.png)

**Comment by markus101** [comment]
Limiting season packs until all episodes have aired is intentional, we're going to need more information to decide if a buffer is acceptable (likely 24 hours, not a week).

If this is a streaming exclusive show why is the air date incorrect? It should reflect the release date, on TheTVDB this was treated as 00:00 2022-10-14, which Sonarr treats as EDT (GMT-4).
When was the season pack released?
Does Apple+ release their episodes at 00:00 in a different timezone?

**Comment by gl0ryus** [comment]
In the case of Apple/Amazon and possibly others, they will release their exclusive shows at "midnight" of that day (making the airdate valid). I'm finding conflicting information of which time zone, some say EST some do PST, but in the case of last night it was a few hours prior to midnight. 

In my personal experience Rings of Power releases ~2 hours the day before as well. (Same thing happened with the season pack rejection). 

Wish I had more concrete times to bring to you, but 24 hours I think would be a better solution rather than it being so strict.

**Comment by markus101** [comment]
Yeah, a little grace period (24 hours to start) seems reasonable for this.
