### ISSUE TITLE
No SSL Options for Sonarr

### ISSUE THREAD

**Issue by sgtcoder** [Sonarr/Sonarr#5192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is an option for SSL, but no way to put the SSL Cert Path and SSL Cert Password like Radarr has.

### Expected Behavior

Have an option to be able to specify this.

### Steps To Reproduce

1. Login to Sonnar, goto settings, then General
2. Click Show Advanced, enable SSL, no options to define.

### Environment

```markdown
- OS: AlmaLinux 8.6
- Sonarr: Latest version
- Docker Install: Yes, through Linux Server
- Using Reverse Proxy: Trying to via SSL, but using direct for now
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

I do not have any, but wouldn't say this is a feature if a feature is only partial

### Anything else?

Same issue as above, no way to define SSL settings.

**Comment by bakerboy448** [comment]
Duplicate of #4682

**Comment by markus101** [comment]
This will be in v4.
