### ISSUE TITLE
Connect Notification Trigger for Import Failed

### ISSUE THREAD

**Issue by AttackOfTheMoons** [Sonarr/Sonarr#5193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When an import fails, the only way I can tell is if I log into the Sonarr interface and check activity and see the orange !

### Describe the solution you'd like

With connect, it tells me when the indexers are down. I would also like to know if an import fails so I can go check on it. 

### Describe alternatives you've considered

The current alternative is looking at the grabbed episode connect notification and then waiting to see if there is no following episode imported notification.

### Anything else?

![image](https://user-images.githubusercontent.com/42690834/195968574-0e968762-8f37-4d73-b627-02371d65bb45.png)

**Comment by markus101** [comment]
I think https://github.com/Sonarr/Sonarr/pull/5200 covers this (in a slightly more inclusive way).

**Comment by StickieBE** [comment]
> With connect, it tells me when the indexers are down. I would also like to know if an import fails so I can go check on it.
Yes, I believe this is similar in the trigger but not in its usage. Seems interesting enough to see if they can be combined, though.
