### ISSUE TITLE
Delete series and files via list sync

### ISSUE THREAD

**Issue by jackfalveyiv** [Sonarr/Sonarr#5201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Using the List import feature for a separate 4K library, it looks like Radarr allows a List Update Interval and Clean Library Level option, Sonarr does not.  In Radarr I can manage the 4K library by utilizing a sync'd profile and the file will delete from my datastore automatically, without having to log in and manage the 4K instance manually.

Files attached for Radarr and Sonarr List import option screenshots, for comparison.
![Radarr](https://user-images.githubusercontent.com/15113284/196236962-afb1d396-e7f5-46e1-ab80-95b8f9622743.png)
![Sonarr](https://user-images.githubusercontent.com/15113284/196236964-ae765d9a-abd3-434c-a301-30f846d03212.png)

### Describe the solution you'd like

Sonarr to have the same or similar capability that Radarr does, so that the 4K library can be managed 100% through my existing, standard Sonarr instance.

### Describe alternatives you've considered

Manually log into the Sonarr4K library to delete old series occasionally.

### Anything else?

Found this issue when comparing the Radarr and Sonarr sync guides found on TRaSH guides:

https://trash-guides.info/Sonarr/Tips/Sync-2-radarr-sonarr/

**Comment by KaiStarkk** [comment]
+1 for this, allows for a really nice workflow (when combined with excludarr) that effectively makes the entire process automated such that the list (trakt or equivalent) becomes the only touchpoint

**Comment by alanman87** [comment]
+1 for this feature. I use trakt to sync lists to sonarr, however deleted items in trakt remain in sonarr, so it's a bit more cumbersome to manage vs radarr.

**Comment by miguelpruivo** [comment]
+1 really love it in radarr

**Comment by frankyw** [comment]
This is a good idea +1
