### ISSUE TITLE
scene mapping conflict

### ISSUE THREAD

**Issue by jamiep153** [Sonarr/Sonarr#5204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting this in logs and skipping that download...
Couldn't process release.: Scene Mappings contains a conflict for tvdbids 412366,79349. Please notify Sonarr developers. (Dexter.S09E01.Cold.Snap.1080p.AMZN.WEBRip.DDP5.1.x264-NTb)

### Expected Behavior

Says to notify developers, doesn't download

### Environment

```markdown
- OS: ubuntu 18.04
- Sonarr: 2.0.0.5344
- Docker Install: no
- Using Reverse Proxy: no
- Browser: chrome
```

### What branch are you running?

Main

### Trace Logs?

Couldn't process release.: Scene Mappings contains a conflict for tvdbids 412366,79349. Please notify Sonarr developers. (Dexter.S09E01.Cold.Snap.1080p.AMZN.WEBRip.DDP5.1.x264-NTb)

### Anything else?

It says Dexter in the logs but that's not what I'm downloading

**Comment by bakerboy448** [comment]
Sonarr v2 has been end of life and not supported for 1.5 years.

Upgrade to v3
