### ISSUE TITLE
Adding a notepad feature to the show entry

### ISSUE THREAD

**Issue by Muskehound** [Sonarr/Sonarr#5205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

As someone with a lot of shows and a bad memory, it would be neat to have a notepad on each show so I can leave information for myself for the future. 

ie 'S1-4 of this HEVC archive quality, don't replace. S5 currently airing and replace down the line'
or 'S1 is uncut and a pain to find.. DO NOT REPLACE!!!' 

Could also be useful for cutting/pasting specific show release notes too for reference.

### Describe alternatives you've considered

Keeping notes separately from the app, which isn't as fluid

### Anything else?

Nope! Thanks

**Comment by thezoggy** [comment]
pretty niche feature, but why not just put a .txt file in the series folder?

**Comment by Muskehound** [comment]
I rarely look at the series folder itself, personally, Sonarr gives me more information about the shows in my collection in a nicer interface than seeing a bunch of files.

**Comment by markus101** [comment]
Same as https://github.com/Sonarr/Sonarr/issues/3483 before, this still isn't something we have plans to implement.
