### ISSUE TITLE
TorrentAPI new limits/changes

### ISSUE THREAD

**Issue by rarbg** [Sonarr/Sonarr#5206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

--

### Describe the solution you'd like

No clue who's responsible for Sonarr right now but @bakerboy448 said to open an issue so here is it

To fix Sonarr potential issues please implement the following in your torrentapi code :

1. Increase the sleep between requests x2
2. if the API returns 429 retry in 2 minutes , 429 returns a custom json with rate_limit 1 - ignore it
3. if the API returns 520 retry in 3 minutes
4. if the API returns 200 with a json that contains rate_limit 1 retry in 5 minutes

That will cover all cases. Back-off is unnecessary if it really waits for 6 hours. I never experienced a back-off period in my Sonarr so far tho.

### Describe alternatives you've considered

--

### Anything else?

--

**Comment by roundaboutluke** [comment]
Will this change be made in V3? Currently it's completely unusable and just errors constantly, it's more effort than manually adding torrents and V4 from Discord comments I'm being told is not usable, recommended and has no support.

**Comment by rarbg** [comment]
@roundaboutluke works fine here.

**Comment by roundaboutluke** [comment]
> @roundaboutluke works fine here.

After changes to torrentapi code? Atm it's very hit and miss, more often that not getting rate limits to the point that Sonar then reports the tracker as broken, then refresh, can grab a couple of shows rate limited again etc. 

Assumed this was a result of needing the changes you've listed?

**Comment by rarbg** [comment]
@roundaboutluke the required changes should be implemented to fix issues for people that get issues like you. Most dont.

**Comment by ipaqmaster** [comment]
Its been a pretty unusable experience. Even on an unshared public IP rarbg still rate limits Sonarr after a single request for a few minutes at a time. If sonarr is downloading content single episodes at a time it will succeed once then fail for the rest and and put the indexer on timeout. If this is your only indexer, Sonarr just stops doing its job.

Not sure what's wrong with Cloudflare on these aggressive 520 responses. Makes me wonder if they're maybe targeting on other identifying features such as the UA string and parameters seen in Sonarr's query string such as the app_id= parameter?

---

Some thoughts,

Could Sonarr possibly cache these frequent and large 100-result queries it makes so frequently so it doesn't have to bug the service as often to avoid receiving 520 responses just for one show's worth of episodes?

Could Sonarr be updated to understand that rarbg do 520 responses and know that it only has to back off for a few minutes at a time? This would still allow Sonarr to handle plenty of work overnight.

**Comment by bakerboy448** [comment]
Rarbg 520 responses and generally seems to indicate their internal servers are overloaded - details below.
Sonarr caching RSS feeds negates the entire point of how sonarr works - see the first faq entry.  Unless a user is manually triggering a frequent RSS refresh normal Sonarr scheduled RSS functionality should not cause rate limiting.

There is already a PR #5347 to handle better rate limiting and backoff for shorter times as rarbg admin described.
Every user a rarbg - regardless of app - is having these issues, reducing 520 errors are something that only rarbg can fix.


> when rated limited cloudflare will return http code 429 with a json encoded string that includes rate limit 1
> when rated limited web returns http code 444 to cloudflare which returns 520 on cloudflare , there is no way to send 429 to cloudflare without it breaking the request properly and retrying it
> when rated limited code returns http code 200 with rate_limit 1
> 
> rate_limit : 1 is generally returned when you've exceeded the rate limit or when one of the many servers behind cloudflare is being overloaded - because cloudflare doesn't evenly redistribute requests equally its there so clients via api can see that they are rate limited , retry in lets say 5 seconds and they can get their request fullfilled on another backend ( cloudflare doesn't do stickiness ) in x time

ref https://github.com/Jackett/Jackett/issues/13663#issuecomment-1288190301
