### ISSUE TITLE
Strip Whitespace from Start / End of Preferred Words?

### ISSUE THREAD

**Issue by some-guy-23** [Sonarr/Sonarr#5207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I had a preferred word entered for "x265" and noticed I kept getting unexpected upgrades. I ended up tracing it back to having whitespace at the end of a preferred word (so releases with space in the name were getting upgraded to).

### Describe the solution you'd like

Not sure if it would make sense, but stripping whitepsace from start / end of preferred words, or at least making it more clear when whitespace is present somehow?

### Describe alternatives you've considered

Not accidentally hitting the spacebar or copying / pasting incorrectly. :P

### Anything else?

None

**Comment by markus101** [comment]
Preferred words are being replaced in v4 and v3 won’t have such a change before that release.
