### ISSUE TITLE
series posters are frequently re-downloaded

### ISSUE THREAD

**Issue by endquote** [Sonarr/Sonarr#5209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever the "refresh series" task runs, all posters and fanart are re-downloaded from artworks.thetvdb.org.

```
10/25/2022 3:54:01 AM
[Info] MediaCoverService: Downloading Poster for [313999][Atlanta] https://artworks.thetvdb.com/banners/posters/313999-2.jpg 
...
10/25/2022 3:58:58 PM
[Info] MediaCoverService: Downloading Poster for [313999][Atlanta] https://artworks.thetvdb.com/banners/posters/313999-2.jpg 
...
10/26/2022 4:05:26 AM
[Info] MediaCoverService: Downloading Poster for [313999][Atlanta] https://artworks.thetvdb.com/banners/posters/313999-2.jpg 
...
10/26/2022 4:09:14 PM
[Info] MediaCoverService: Downloading Fanart for [313999][Atlanta] https://artworks.thetvdb.com/banners/v4/series/313999/backgrounds/630a8fcead6a5.jpg 
```

### Expected Behavior

It doesn't seem necessary to re-download the artwork each time. The artwork seems to be stored on AWS S3 which includes support for [e-tag headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) that can be used to see if the content has changed before downloading. The response for the above poster shows this:

```
:status: 200
Content-Type: image/jpeg
ETag: "a28bd217fdc10d16cad290e64a98c3de"
Age: 8755254
Via: 1.1 801c4cdd177872a11b03f54a2b3b464e.cloudfront.net (CloudFront)
Date: Sun, 17 Jul 2022 14:50:56 GMT
Content-Length: 140477
Accept-Ranges: bytes
Vary: Origin
Last-Modified: Tue, 15 Oct 2019 15:08:52 GMT
x-amz-cf-id: EieR00t-rcpPZ9_r4-yk553J_3JSzJh0sf9jPzgCumDcmP0pCq1_Fw==
x-cache: Hit from cloudfront
Server: AmazonS3
x-amz-cf-pop: SFO53-C1
```

This file hasn't changed in three years but is being downloaded and written to disk every 12 hours.

Here is the file on disk, with a timestamp matching the last log above.

```
endquote@nas:~$ ls -al /volume1/docker/appdata/sonarr/MediaCover/97
total 896
drwxrwxr-x 1 docker users    224 Oct 26 16:09 .
drwxrwxr-x 1 docker users    614 Oct 24 19:30 ..
-rw-rw-r-- 1 docker users   1808 Oct 26 16:09 banner-35.jpg
-rw-rw-r-- 1 docker users   3355 Oct 26 16:09 banner-70.jpg
-rw-rw-r-- 1 docker users 141944 Oct 26 16:09 banner.jpg
-rw-rw-r-- 1 docker users  25217 Oct 26 16:09 fanart-180.jpg
-rw-rw-r-- 1 docker users  76504 Oct 26 16:09 fanart-360.jpg
-rw-rw-r-- 1 docker users 430164 Oct 26 16:09 fanart.jpg
-rw-rw-r-- 1 docker users  20045 Oct 26 16:09 poster-250.jpg
-rw-rw-r-- 1 docker users  57596 Oct 26 16:09 poster-500.jpg
-rw-rw-r-- 1 docker users 140477 Oct 26 16:09 poster.jpg
```

### Steps To Reproduce

I believe this will reproduce in any environment that uses the "refresh series" task.

### Environment

```markdown
Using Reverse Proxy: traefik/authelia
Version: 4.0.0.141
Package Version: v4-34a9b84 by hotio
.Net Version: Yes (6.0.8)
Docker: Yes
```

### What branch are you running?

Main

### Trace Logs?

Trace logs: https://gist.github.com/endquote/0222068c2819ef2e2f779d3e24d0db35

I do see [a HEAD request](https://gist.github.com/endquote/0222068c2819ef2e2f779d3e24d0db35#file-atlanta-update-log-L101) for the file before downloading, so maybe an e-tag is being checked? But the download still seems to be happening and the timestamp for the file on disk did change.

### Anything else?

I've been using Sonarr for many years with basically no issues, so thank you for such a reliable tool.

I only noticed because I started using Pi-hole, and the number one domain request from my network is artworks.thetvdb.com from sonarr. Of course verifying e-tags would still require DNS queries that go to pi-hole, but this still seemed worth reporting.

**Comment by bakerboy448** [comment]
it _shouldn't_ be downloading if the cover exists and isn't updated.

https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/MediaCover/MediaCoverService.cs#L112-L119

**Comment by endquote** [comment]
@bakerboy448 I updated my original post above -- the timestamps on the files match those in the logs, so I believe it is downloading.

Maybe I need to turn on trace logs and re-run the task.

**Comment by endquote** [comment]
Trace logs: https://gist.github.com/endquote/0222068c2819ef2e2f779d3e24d0db35

I do see [a HEAD request](https://gist.github.com/endquote/0222068c2819ef2e2f779d3e24d0db35#file-atlanta-update-log-L101) for the file before downloading, so maybe an e-tag is being checked? But the download still seems to be happening.

**Comment by markus101** [comment]
It's not checking etag, but the `Content-Length`, but that was being tossed out before it got where it needed to be.

**Comment by endquote** [comment]
My server is now running 4.0.0.142 and it looks like that change has made it in, since the file modification dates aren't changing. 👍

However I took a look at thetvdb API docs, and it looks like there's [an updatedAt property on artworks](https://github.com/thetvdb/v4-api/blob/main/docs/swagger.yml#L2402). Maybe that could be compared with the file modification date to avoid that HEAD call entirely.
