### ISSUE TITLE
[Telegram] add custom prefix (or sonar instance name)

### ISSUE THREAD

**Issue by psychowood** [Sonarr/Sonarr#5210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

EDIT: ok apparently I did not search enough, this could be related to #4349 .

### Is your feature request related to a problem? Please describe

Not a problem

### Describe the solution you'd like

I'm currenly using a single Telegram Chat with one bot that is shared with all the services (*arr and others) I need to monitor, but I noticed that sonarr is sending a message with the event without including the sender.

I'd like to ability to specify a prefix for each Telegram message that sonarr is sending. Currently the notifications are sent without context and it's difficult to identify which service is sending which message; this is useful also (but not just) with more than one sonarr instance.

An alternative implementation could be a generic flag "prefix sonarr instance name to each message" and avoid the text customization.

### Describe alternatives you've considered

The only workaround I've found is creating either dedicated chats or dedicated bots for each service, that while nice (different bot name and icon or different chat title) results in an excessive proliferation of bots/chats to manage.

### Anything else?

Something like this (red border added for highlighting:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/115389/198259415-990fdb0f-e840-4bc1-826f-b12f7e310447.png">

could result in this message being sent:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/115389/198260048-d820fc85-3d50-4217-8d75-2df2ee57aad9.png">

the #sonarr tag in the text is an added bonus to filter directly all the sonarr messages.

**Comment by markus101** [comment]
Yeah, that's part of a larger piece or work that needs to occur, instead of doing it as one offs. https://github.com/Sonarr/Sonarr/issues/328
