### ISSUE TITLE
Formula1 Searching / Alternative Naming Matches

### ISSUE THREAD

**Issue by ape-ck** [Sonarr/Sonarr#5211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Formula1 episodes are available in indexers, but sonarr does not locate them. 

### Describe the solution you'd like

Match with existing nzbs within indexers. For example: 

Formula1.2022.Round.03.Australian.GP.Race.F1TV.1080p.WEB-DL

should match to "Formula 1-2022x16-Australia (Practice 3)" in sonarr. 

### Describe alternatives you've considered

Manually downloading the nzbs and renaming / importing them.  I've searched extensively through forums and this looks like it is a desired function, but no one has a graceful solution. 

### Anything else?

no, thank you for hearing me out.

**Comment by bakerboy448** [comment]
- Sports are generally not supported
- Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.
- this called out on the FAQ https://wiki.servarr.com/sonarr/faq#why-cant-sonarr-import-episode-files-for-series-x-why-cant-sonarr-find-releases-for-series-x

**Comment by markus101** [comment]
The only way Sonarr could match this is with some sort of mapping (similar to how XEM works for anime), but it’s quite different.

At this time this isn’t something we have plans to support.
