### ISSUE TITLE
Debian 11 Sonarr not installing correctly.

### ISSUE THREAD

**Issue by DonW16** [Sonarr/Sonarr#5215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
sudo apt install sonarr
```

```
The following packages have unmet dependencies:
 libmono-corlib4.5-cil : Depends: mono-runtime (< 6.8.0.106) but 6.12.0.182-0xamarin1+debian10b1 is to be installed
 libmono-i18n-west4.0-cil : Depends: libmono-i18n4.0-cil (>= 4.0.0~alpha1) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

### Expected Behavior

Sonarr to be installed?

### Steps To Reproduce

```
sudo apt install sonarr
```

### Environment

```markdown
- OS: Debian 11
- Sonarr: sonarr/buster 3.0.9 all
- Docker Install: No
- Using Reverse Proxy: No
- Browser: NA.
```

### What branch are you running?

Main

### Trace Logs?

NA

### Anything else?

NA

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Looks like there are conflicting packages or something else is preventing those packages from installing.
