### ISSUE TITLE
Add length limit to {Episode Title}

### ISSUE THREAD

**Issue by pjaclark** [Sonarr/Sonarr#5222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some Japanese TV shows (live action and anime) have long names, and even longer episode titles. This can cause problems. I suggest a user-definable max length for `{Episode Title}` and `{Episode CleanTitle}` that works in a similar manner to `{season:00}`.

### Describe the solution you'd like

The format would be `{Episode Title:nnn}` where `nnn` is the maximum number of characters allowed. Titles over the limit would be truncated to (nnn-3) and have an ellipsis (3 dots) added to show the title has been shortened.

As an example, consider episode [S01E04 of Liar Game (tvdb 81763)](https://thetvdb.com/series/liar-game/episodes/361230), whose stunningly long episode title is `A stunning 4th episode!! X's true colors are revealed!! The outcome of X vs Akiyama is!! Making a comeback after turning the tables!!`. With `{Episode Title:20}`, this would then become the much more manageable `A stunning 4th ep...`.

### Describe alternatives you've considered

At the moment, I have set the Anime Episode Format to not use `{Episode Title}` due to the title lengths, and I also run a separate Japanese instance of Sonarr to have the Standard Episode Format drop the titles only for Japanese series. Would be nice to only use the 1 instance of Sonarr for this, and have titled for all Japanese TV and anime.

### Anything else?

Liar Game S01E04: https://thetvdb.com/series/liar-game/episodes/361230

**Comment by markus101** [comment]
No plans to add such a limit, Sonarr truncates to avoid exceeding maximum length restrictions though.

https://github.com/Sonarr/Sonarr/issues/926 is is somewhat related and could avoid a second instance.

**Comment by pjaclark** [comment]
Truncating the entire name is what I'm trying to avoid. I place the useful metadata goes at the end of the file name (release group, tvdbid, audio and quality info) and I don't want that getting truncated. Shortening the episode title is a better option.

**Comment by markus101** [comment]
That's how it's done, the rest of the file name is calculated and then the episode title(s) fill in the remaining space.
