### ISSUE TITLE
Download is marked as failed if Download Station has to extract the media file

### ISSUE THREAD

**Issue by aidenmitchell** [Sonarr/Sonarr#5223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Synology Download Station includes a feature to auto-extract any zipped torrent files. When enabled, when DS is extracting a file, Sonarr does not wait for extraction (or mark it as stalled), and instead fails the download.

### Expected Behavior

Sonarr waits for extraction to complete and imports the newly extracted file.

### Steps To Reproduce

1. Connect Download Station as your download client
2. Enable auto-extraction in Download Station
3. Get Sonarr to download a torrent where the media file must be unzipped
4. When the download is complete and in the process of extraction, Sonarr fails the download.

### Environment

```markdown
- OS: Windows Server 2022
- Sonarr: Sonarr 3.0.9.1549
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Microsoft Edge (Chromium-based) 107.0.1418.26 (Official build) (64-bit)
```

### What branch are you running?

Main

### Trace Logs?

(https://gist.github.com/aidenmitchell/44c232ea288b6ae6ee9c9ffb963a007d)
The failed download started here: `2022-11-04 10:45:57.8|Debug|TrackedDownloadService`

### Anything else?

I think Sonarr needs to look for the `"status_extra":{"unzip_progress":1}` value when querying Download Station and wait until the value is cleared, but I'm not an expert, and I'm not sure what Sonarr sees _after_ the extraction is complete.

Example download, where DS is in the process of unzipping:
```
"id":"dbid_20","size":2544726768,"status":10,"status_extra":{"unzip_progress":1},"title":"Better.Call.Saul.S04E08.iNTERNAL.1080p.WEB.X264-METCON","type":"bt","username":"(removed)"}
```

**Comment by markus101** [comment]
From the logs:

```
"status": 10,
"status_extra": {
    "unzip_progress": 1
},
```

Which in turn gets converted to an enum in Sonarr, but status 10 corresponds to `Error` not `Extracting`.

https://github.com/Sonarr/Sonarr/blob/fe476a319e1768a929e326e87a54b10bc5e4f402/src/NzbDrone.Core/Download/Clients/DownloadStation/DownloadStationTask.cs#L46-L60 (Extracting is the 10th item, but it's 0 indexed, so it's treated as Error).

The only API docs I've managed to find are ancient (from 2014 it looks like) is missing CaptchaNeeded:
![image](https://user-images.githubusercontent.com/413544/200047057-19aac6de-effb-4b28-b2e2-49e383dc2938.png)

Assuming that list starts at 1 our order is the same and a status of 10 means it's an error, if there is a different mapping we should use we'll need something to reference to make sure we're doing it correctly.

**Comment by bakerboy448** [comment]
found a newer api doc as of 2021
https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/FileStation/All/enu/Synology_File_Station_API_Guide.pdf

**Comment by aidenmitchell** [comment]
Looks like that's File Station, not Download Station. I can contact Synology Support for more API info, would that help?

I’m honestly not sure how I can help here, apologies.

**Comment by bakerboy448** [comment]
ah crap...yup that's FS not DS.
Looking further.  It does appear that Synology does not have any other additional more recent download station documentation.
https://kb.synology.com/en-my/search?sources%5B%5D=developer_guide&services%5B%5D=Download_Station

as an aside - using unpackerr is the much better route than any downloadclient unpacking for torrents. No client has been seen to do unpacking right and hide the in-progress unpacking files to avoid a corrupt file being imported and no client clean's up the extracted files.

**Comment by aidenmitchell** [comment]
Never heard of unpackerr, I'll check that out. I'll contact Synology and see what they say, but I agree, an app purpose-built to extract is better anyways.

**Comment by markus101** [comment]
I think DS might be the only torrent that maybe does have a state for it, but unfortunately there is something up with the status list they've provided and the status code they're returning.

**Comment by aidenmitchell** [comment]
Closing, Synology is not being helpful, and Unpackerr works perfectly.

**Comment by Mavyre** [comment]
That's a bit redundant having to install an extractor where Download Station integrates one. Synology is not well known to update their documentation files.
I'll check out Unpackerr only for *arrs, but if I can help on resolving this issue by giving lot of logs... That'd be great!
