### ISSUE TITLE
Series Rename Fails to Move Subtitle Files

### ISSUE THREAD

**Issue by tronyx** [Sonarr/Sonarr#5227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When renaming a Series, the subtitle files fail to be renamed as the video files are. I updated my naming convention to ensure season numbers are two digits, IE: `Season 1` to `Season 01`, along with the file names as listed below.

### Expected Behavior

Subtitle files should be renamed according to their corresponding episode files.

### Steps To Reproduce

Rename a Series that has subtitle files, view failures in the log. Using the following Media Management settings:

Standard Episode Format - `{Series TitleYear} - S{season:00}E{episode:00} - {Episode CleanTitle} [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels]}{MediaInfo AudioLanguages}{[MediaInfo VideoCodec]}{-Release Group}`

Series Folder Format - `{Series TitleYear}`

Season Folder Format - `Season {season:00}`

### Environment

```markdown
- OS: Ubuntu 18.04
- Sonarr: 3.0.9.1555
- Docker Install: Yes
- Using Reverse Proxy: Issues happens via RP or locally
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

https://gist.github.com/tronyx/4321fd0d9116b1bdd1010812e5ff0b14

### Anything else?

Some dir listings for reference:

https://gist.github.com/tronyx/74ca80388148f44a571d79ccd48cf64f

**Comment by markus101** [comment]
Fixed in https://github.com/Sonarr/Sonarr/commit/89ee7d4452ae3b476e24aede89b668a3df2344fc
