### ISSUE TITLE
Rarbg Not Fetching Results Through Prowlarr

### ISSUE THREAD

**Issue by seniorm0ment** [Sonarr/Sonarr#5229]
I setup Jackett, and RARBG wasn't working, so I set up Prowlarr which was a lot easier. However RARBG still does not fetch results.
For clarity, if I search directly on Prowlarr, it shows results (same with Jackett). But when I go into Sonarr, it does not.
Other trackers are not having issues.
Not sure what's going on, someone told me they are not having this issue with RARBG. The fact I replicated it with Jackett and Prowlarr seems to indicate it's more on the side of Sonarr but Idk.

Windows 10 Sonarr, Prowlarr.

**Comment by markus101** [comment]
Please don't the templates, but you need use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
