### ISSUE TITLE
Adding regex like importing for lists

### ISSUE THREAD

**Issue by nyxtyr** [Sonarr/Sonarr#5230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I was going to set up a trakt list to grab new shows on sonarr, but I have my shows split between two drive sets for example shows that start with SpecialCharacters-Numbers-ABCDEFG on drive one and HIJKLMNOPQRSTUVWXYZ on drive two.

### Describe the solution you'd like

Adding some sort of regex importing on the list under the folder tag.

Import shows starting with [user input]

Then when it's grabbing the list you made it'll only import those specified to that folder.

### Describe alternatives you've considered

Maybe alternatively for people with split drives you can set Anime, Live Action and so on or even shows that start with specific letters when adding the partitions

### Anything else?

Thanks you.

**Comment by markus101** [comment]
This isn’t something we have to support at this time, multiple lists or pooling your drives are your best alternatives at this time.
