### ISSUE TITLE
Add information on what Sonarr is on the website and wiki

### ISSUE THREAD

**Issue by Slater91** [Sonarr/Sonarr#5238]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I read about Sonarr through a post on the Proxmox subreddit and searched for it to learn what it is. When I landed on the website, though, I found no information at all on what Sonarr is and what it does. The main page does not describe Sonarr in any way. The wiki, under the FAQ, also does not feature basic things like "what is Sonarr?" or "who is Sonarr targeted at?". It seems like the website makes the assumption that one already knows what Sonarr is, but that is not necessarily the case, and being the website the main presentation of the project, I think it is important to explain what Sonarr is on it.

### Describe the solution you'd like

Add a simple description of what Sonarr is and what it does on both the home page of the website and the FAQ section in the wiki. The description given in the GitHub repo would be enough.

### Describe alternatives you've considered

None.

### Anything else?

Not really!

**Comment by bakerboy448** [comment]
It's already explained on the main Sonarr wiki page and the GitHub ReadMe.

- https://wiki.servarr.com/sonarr
- https://github.com/sonarr/sonarr#-sonarr

**Comment by markus101** [comment]
We'll get this added, but closing as the website isn't part of this repo.
