### ISSUE TITLE
Add 'HONE' to list of parseable groups

### ISSUE THREAD

**Issue by yammes08** [Sonarr/Sonarr#5243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Releases by the group HONE don't seem to be parsed by Sonarr, so don't get added to filenames post-import.

### Describe the solution you'd like

For HONE to be added to the list of parseable/exception groups.

### Describe alternatives you've considered

-

### Anything else?

Example release name:
TVShow (2021) S01 (2160p ATVP WEB-DL Hybrid H265 DV HDR10+ DDP Atmos 5.1 English - HONE)

**Comment by PearsonFlyer** [comment]
Release groups must be a dash followed by the release group. No space is allowed. So `- HONE` is not correct, but `-HONE` would be parsed properly. Please ask the release group to properly name their stuff based on scene group rules.

**Comment by bakerboy448** [comment]
> Release groups must be a dash followed by the release group. No space is allowed. So `- HONE` is not correct, but `-HONE` would be parsed properly. Please ask the release group to properly name their stuff based on scene group rules.

And yet Sonarr and Radarr support many groups that do not follow this. 

https://github.com/Sonarr/Sonarr/blob/f47abd0d99719907c734bab0f2ef5477d2054d0d/src/NzbDrone.Core/Parser/Parser.cs#L473-L478

Radarr also already supports HONE
https://github.com/Radarr/Radarr/commit/03a3f4522a02fcaaa915f2be79d97932377c8de0
