### ISSUE TITLE
System: Free space graph not being shown on Ubuntu 22.x

### ISSUE THREAD

**Issue by icenine9** [Sonarr/Sonarr#5247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When clicking the "System" menu option, the Disk Space graph is not rendering. Trace logs point to a permissions issue, however you can see the permissions are correct below.

Snip of logfile below (there are lots of these in the tracelogs, which are attached).
2022-11-27 13:49:47.9|Debug|DiskProviderBase|Failed to get mount for path /saspool1/tv/Indivisible - Healing Hate

[v4.0.0.183] System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---

So that's what the trace log says.... 

plex@lateralus:/var/lib/sonarr/logs$ cd "/saspool1/tv/Indivisible - Healing Hate"
plex@lateralus:/saspool1/tv/Indivisible - Healing Hate$ pwd
/saspool1/tv/Indivisible - Healing Hate
plex@lateralus:/saspool1/tv/Indivisible - Healing Hate$ ls -l
total 56
drwxrwxr-x 2 plex plex 8 May  3  2022 'Season 1'

Above shows that user 'plex' has perms

root@lateralus:/var/lib/sonarr/logs# ls -l / | grep saspool1
drwxrwxr-x    8 plex plex         10 Nov  5 12:31 saspool1

plex@lateralus:/saspool1/tv/Indivisible - Healing Hate$ ps aux | grep Sonarr
plex     2237374 12.3  0.7 4854824 232108 ?      Ssl  13:52   0:35 /usr/lib/sonarr/Sonarr -nobrowser -data=/var/lib/sonarr
plex     2296927  0.0  0.0  17732  2184 pts/8    S+   13:56   0:00 grep Sonarr
plex@lateralus:/saspool1/tv/Indivisible - Healing Hate$ 

And finally, ps output showing the process is owned by plex.

[sonarr.trace.0.txt](https://github.com/Sonarr/Sonarr/files/10099016/sonarr.trace.0.txt)
[sonarr.trace.1.txt](https://github.com/Sonarr/Sonarr/files/10099017/sonarr.trace.1.txt)
[sonarr.trace.2.txt](https://github.com/Sonarr/Sonarr/files/10099018/sonarr.trace.2.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/10099019/sonarr.trace.txt)

### Expected Behavior

For the disk space graph to display. See attached pic here for current output. 
![sonarr](https://user-images.githubusercontent.com/16182988/204155339-f712f20c-9d94-42bf-bf2c-a65fca41f58b.jpg)

### Steps To Reproduce

access sonarr via webint
click "System" on left menu

### Environment

```markdown
- OS: Ubuntu 22.10 
- Sonarr: 4.00.362
- Docker Install: n/a
- Using Reverse Proxy: yes, nginx
- Browser: chrome
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.0.txt](https://github.com/Sonarr/Sonarr/files/10099029/sonarr.trace.0.txt)
[sonarr.trace.1.txt](https://github.com/Sonarr/Sonarr/files/10099030/sonarr.trace.1.txt)
[sonarr.trace.2.txt](https://github.com/Sonarr/Sonarr/files/10099031/sonarr.trace.2.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/10099032/sonarr.trace.txt)

### Anything else?

![sonarr](https://user-images.githubusercontent.com/16182988/204155404-80f29251-2593-4ba1-b0ee-abae1c62a169.jpg)

**Comment by icenine9** [comment]
FYI, with no intervention, this problem appears to have solved itself. I went to look at it today and saw that the graph was populating correctly. 

Weird.

**Comment by icenine9** [comment]
Problem has returned. Can we re-open? Can help troubleshoot on Discord.

**Comment by icenine9** [comment]
Had another moment to look at this right now, This is what I'm seeing below. New 310TB pool, but here is one failure that may be contributing, perhaps? Bear in mind that despite this particular error, Sonarr *IS* downloading files and organizing them successfully. 

First, Sonarr process running as user plex: 
plex@lateralus:/pool1/tv/The Rookie (2018) [imdb-tt7587890]$ ps aux | grep Sonarr
plex     1850904 31.5  0.4 5482456 620272 ?      Sl   18:49   3:59 /opt/Sonarr/Sonarr /nobrowser /restart

Directory entry of logged failure, showing dir owned by plex:plex:

plex@lateralus:/pool1/tv$ ls -l | grep Rookie
drwxr-xr-x  7 plex plex  7 Jan 16 05:01 The Rookie (2018) [imdb-tt7587890]

plex@lateralus:/pool1/tv$ zpool list
NAME    SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
pool1   306T   136T   170T        -         -     5%    44%  1.00x    ONLINE  -
plex@lateralus:/pool1/tv$ mount | grep pool1
pool1 on /pool1 type zfs (rw,xattr,noacl)


2023-01-23 18:49:52.2|Debug|DiskProviderBase|Failed to get mount for path /pool1/tv/The Rookie (2018) [imdb-tt7587890]

[v4.0.0.362] System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_DriveFormat()
   at NzbDrone.Mono.Disk.DiskProvider.<>c.<GetAllMounts>b__16_0(DriveInfo d) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Mono\Disk\DiskProvide
r.cs:line 173
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.DistinctByIterator[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at NzbDrone.Mono.Disk.DiskProvider.GetAllMounts() in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 171
   at NzbDrone.Common.Disk.DiskProviderBase.GetMount(String path) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Disk\DiskProviderBase.cs:
line 463

Also have a look at the following, which I believe might be the c
[tmptrace.txt.zip](https://github.com/Sonarr/Sonarr/files/10484640/tmptrace.txt.zip)
all from the system menu option, which should be populating the mount list, I think....


2023-01-23 18:49:56.7|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the reques
t.

[v4.0.0.362] System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---

**Comment by markus101** [comment]
We should prevent the exception from breaking the response and allow it to return the paths it can sort out properly.
