### ISSUE TITLE
Linux.tar.gz download is actually for Windows

### ISSUE THREAD

**Issue by brianjmurrell** [Sonarr/Sonarr#5251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Download from https://services.sonarr.tv/v1/download/main/latest?version=3&os=linux

```
$ tar -C /opt -xzf Sonarr.main.3.0.9.1549.linux.tar.gz
$ file /opt/Sonarr/Sonarr.exe
/opt/Sonarr/Sonarr.exe: PE32 executable (console) Intel 80386 Mono/.Net assembly, for MS Windows
```

### Expected Behavior

`/opt/Sonarr/Sonarr` should be `ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2```

### Steps To Reproduce

See description for steps.

### Environment

```markdown
- OS: Fedora Linux (irrelevant however)
- Sonarr: N/A
- Docker Install: N/A
- Using Reverse Proxy: N/A
- Browser: Chrome on Fedora Linux
```

### What branch are you running?

Main

### Trace Logs?

N/A

### Anything else?

No.

**Comment by sakurachan00** [comment]
you will need to run this with mono like the instructions state

**Comment by markus101** [comment]
The linux.tar.gz is not for Windows, it's for Linux, like Sakurachan00 said, you need to run it through mono. If you don't want to use mono, use the Sonarr v4 beta.

**Comment by Capt758** [comment]
Sakurachan00 IS right

**Comment by brianjmurrell** [comment]
Yes, understood now.  Due to the significant lack of documentation on installing and running from the tarball, I went to the Radarr docs.  With Radarr being .NET and Sonarr v3 being mono, they didn't work very well.  Some better docs for installing Sonarr from tarball would be good.
