### ISSUE TITLE
Disable enforced authentication 

### ISSUE THREAD

**Issue by caevv** [Sonarr/Sonarr#5252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I already have SSO Auth using Cloudflare oath. How do I disable this second authentication that became required now?

### Expected Behavior

Disable auth

### Environment

```markdown
- OS: Ubuntu 
- Sonarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

No logs

### Anything else?

No

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

You can update the config file and set `AuthenticationMethod` to `External` to rely on external authentication instead.

**Comment by tzakrajs** [comment]
Unfortunately this functionality is not working. When I set the AuthenticationMethod to External, the dialog pops up requiring me to change it and Sonarr keeps adding more and more AuthenticationMethod lines to the configuration. I am using linuxservers sonarr:develop image.
