### ISSUE TITLE
Activity/Queue: Failed to load Queue

### ISSUE THREAD

**Issue by alucryd** [Sonarr/Sonarr#5257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There seems to be a regression in 4.0.0.189, the Activity Queue no longer loads.

### Expected Behavior

The Activity Queue should load fine.

### Steps To Reproduce

Have a transmission download client with some torrents and try to access the activity queue.

### Environment

```markdown
- OS: Arch Linux
- Sonarr: 4.0.0.189
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

https://paste.xinu.at/9cRhN7KIFyoD1LMD/

### Anything else?

![image](https://user-images.githubusercontent.com/1561084/204613652-5af9d054-9410-41dc-81fd-77137b6a93c8.png)

**Comment by alucryd** [comment]
Updated to 4.0.0.200, same error.

**Comment by sysmoon14** [comment]
Also seeing this issue. Version 4.0.0.166

**Comment by stevietv** [comment]
@alucryd gonna need to post more of the trace log than just the one line. Can you update it?

**Comment by alucryd** [comment]
@stevietv Updated. Please let me know if you need specific actions to be carried out to get some additional logs.

**Comment by stevietv** [comment]
@alucryd I don't think these are your trace logs right? Can you enable trace logging, replicate the error then post the trace log here.

**Comment by alucryd** [comment]
My bad, I didn't have trace logging enabled. Updated the logs with a pastebin link.

**Comment by stevietv** [comment]
hmm, I suspect that Sonarr is bugging out on an item in your download client but I can't see which one it may be.
Do you use categories for your transmission? At the moment it looks like Sonarr is getting everything from your DL client and not only the Sonarr items. I know transmission does categories in a fake way (with subfolders) but it may help.

**Comment by DeftNerd** [comment]
I'm having the same problem. As an experiment, I disabled my download clients in the sonarr settings. In theory that should prevent them from polling the clients. The error still occurs, even though Sonarr says no download client exists.

I also removed all downloads, in progress, completed, etc from all download clients so they would report NO items, even in other categories. The error still occurs. 

As odd as it sounds, could it be a problem with scene mapping? I know that's part of the activity queue display pipeline and I'm seeing weird stuff in my database. 

If I `select count(*) from Series where UseSceneNumbering = 1;` I get 69 items, but if I `select Series.Id,Series.TvdbId,Series.Title,SceneMappings.TvdbId,SceneMappings.Title from Series,SceneMappings where (Series.UseSceneNumbering = 1) and (Series.TvdbId = SceneMappings.TvdbId) GROUP BY SceneMappings.TvdbId ORDER BY Series.Title;` I only get 50 lines of results. 

This makes me think that I have 69 TV series that are flagged as having scene mappings, but only 50 of them actually have scene mappings. I blew out the SceneMapping DB and ran the `Update Scene Mapping` Task. Same results afterwards (with a total of 8891 SceneMappings entries... which seems low?)

Whatever is happening isn't actually related to the queue polling, I think. It's something that's done as part of the process pipeline. 

Interestingly, my downloads are still working just fine when the imports happen automatically. I just have no access to view the activity queue (or perform actions based on what's normally done in that queue, like manually importing items)

**Comment by stevietv** [comment]
1. Adding "The Ren & Stimpy Show" doesn't break my queue.
2. I have 7 shows `where UseSceneNumbering = 1` and only 6 of them actually have entries in the SceneMappings table. So the mismatch isn't directly related.

**Comment by alucryd** [comment]
I don't use categories in transmission unfortunately, I actually like that sonarr can see all torrents as I often download stuff manually because it's faster for me that way and I can just import them from the queue afterwards.

As @DeftNerd I also tried disabling the download client, but the error still occurs.

FWIW, the same torrent list was working fine in sonarr v3, it started occuring after linuxserver updated their develop container to v4 a week ago.

**Comment by markus101** [comment]
> I don't use categories in transmission unfortunately, I actually like that sonarr can see all torrents as I often download stuff manually because it's faster for me that way and I can just import them from the queue afterwards.

You can still do this with categories, it just needs to be in the category Sonarr is looking at. For transmission Sonarr uses subfolders for the category, so for transmission it just needs to be in the correct subfolder.

Looks like it's not failing from something in the client, but something in the pending releases that Sonarr might've stored before upgrading to v4 (because `Languages` is empty`).

**Comment by SuperDOS** [comment]
I still have this issue:
`2022-12-07 14:02:11.6|Fatal|SonarrErrorPipeline|Request Failed. GET /api/v3/queue

[v4.0.0.245] NzbDrone.Core.Exceptions.BadRequestException: Invalid sort key episode.title
   at Sonarr.Http.Extensions.RequestExtensions.ReadPagingResourceFromRequest[TResource](HttpRequest request) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Extensions\RequestExtensions.cs:line 89
   at Sonarr.Api.V3.Queue.QueueController.GetQueue(Boolean includeUnknownSeriesItems, Boolean includeSeries, Boolean includeEpisode) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Api.V3\Queue\QueueController.cs:line 101`

**Comment by markus101** [comment]
The result is the same, but the cause is quite different, next time it'd be better to open a new issue than comment on a closed one. Locking this, if someone else has a similar issue, open a new issue please.
