### ISSUE TITLE
add custom format score to the interactive search filter

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#5259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

add custom format score to interactive search filter

### Describe the solution you'd like

would like to add filter to say show me CF score above x 

### Describe alternatives you've considered

did not see any other options since 'rejections' is too vague now

### Anything else?

add to:
![sonarr](http://zoggy.net/firefox_2022-11-30_11-37-29.png)

**Comment by markus101** [comment]
Added in https://github.com/Sonarr/Sonarr/commit/998768bcf2c3308611a05a4518e7ef3fbcb473cc
