### ISSUE TITLE
Add UI for Parse Endpoint

### ISSUE THREAD

**Issue by Ravencentric** [Sonarr/Sonarr#5263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Sometimes I need to check whether something parses or not and for that, I use `/api/v3/parse?title=filename`. It works but isn't the most convenient experience. Existing options like Notifiarr's parse isn't ideal since it can't match the title with the correct show if it's a XEM alias. Plus a built-in solution would be preferable.

### Describe the solution you'd like

A front-end web page for the parse api in the web-ui making it easier to check parsing from Sonarr itself. 

### Describe alternatives you've considered

using the parse api `/api/v3/parse?title=filename` or notifiarr's parser

### Anything else?

For reference, medusa has this:
![image](https://user-images.githubusercontent.com/78981416/205264192-2de0c622-669e-45c1-8bc5-d53e69ac870e.png)

**Comment by thezoggy** [comment]
have you looked at using ARC (advanced rest client)? 
https://www.advancedrestclient.com/

but also if you just want a parser on demand, you can use the ones from trash/radarr/etc discords

**Comment by markus101** [comment]
Not sure where something like this would best exist, but open to discussing it.

**Comment by thezoggy** [comment]
> Not sure where something like this would best exist, but open to discussing it.

i could see the benefit of tossing the parser thing on the CF page so people could see what something parsed there would yield for relevant fields and what it would match...  that way it may make it easier to figure out what to tweak before they go off to set scores.

**Comment by Ravencentric** [comment]
I was thinking that maybe it could have its own tab in the left pane, but that also sounds great! Something that would be cool to see upon entering the string to parse is some of the info neatly presented along with the full JSON:
- Show in Sonarr that it matches, alert if it doesn't match any.
- SxxEyy it matches, alert if it doesn't match any.
- Expanding on what @thezoggy said, real-time CF scores, possibly with the option to select a quality profile as well.

**Comment by markus101** [comment]
> Show in Sonarr that it matches, alert if it doesn't match any.
> SxxEyy it matches, alert if it doesn't match any.

What do you mean by "alert"? I don't know that we need to do anything special besides present the data in a way that indicates something was/wasn't matched.

> Expanding on what @thezoggy said, real-time CF scores, possibly with the option to select a quality profile as well.

CF is realtime, but the scores aren't related to parsing the formats. If Sonarr matched the series then it could use that quality profile, but I don't think it makes sense to make that selectable otherwise.

**Comment by Ravencentric** [comment]
> What do you mean by "alert"? I don't know that we need to do anything special besides present the data in a way that indicates something was/wasn't matched.

Oh I just meant something like:
```
Parse: Peaky.Blinders.S06E01.WEB-DL.1080p.mkv
Matched Show: Peaky Blinders
Matched Episode: S06E01 - Black Day
CF: +10000
<extra stuff>
```
```
Parse: `Dr. Stone.S01E01.WEB-DL.1080p.mkv`
⚠️ Unable to match with any show
<extra stuff>
```
> If Sonarr matched the series then it could use that quality profile

Yea that works 👍
