### ISSUE TITLE
activity > history > sort CF score

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#5265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

cant sort by "Formats" column, so wanted to just sort by the Score and saw I couldnt sort by that either

### Describe the solution you'd like

Sort by score

### Describe alternatives you've considered

none

### Anything else?

sort:
![sonarr](http://zoggy.net/firefox_2022-12-02_15-55-16.png)

**Comment by markus101** [comment]
This would be incredibly inefficient, but likely both. CF values are dynamic and update as they are processed. That means we'd either need cache it for every item in history whenever a Custom Format was changed which would take longer and longer every time Sonarr added a history item. No plans to implement this.
