### ISSUE TITLE
Add support for more precise CustomFormat placement in Rename patterns

### ISSUE THREAD

**Issue by Alanoll** [Sonarr/Sonarr#5274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

v4 added Custom Formats, but seems to have removed the functionality added by #4453 (or at least, some quick code trolling in the areas didn't look like it did)

### Describe the solution you'd like

Really it's the same solution, just for Custom Formats instead.

### Describe alternatives you've considered

Not doing it. I used the functionality (since I added it), but I don't know if others did since it was never really advertised.

### Anything else?

I'm just opening this issue for discussion before I tried to port the functionality. Maybe it was removed on purpose vs it was just skipped during the CustomFormat work because it was desired to bring in-line with Radarr first.

CustomFormats can add wrinkles to the idea. The Preferred Word solution used the name of the profile, and then used the text matched in the token. Custom Formats _could_ work the same, but they're a more complicated structure. It could still be "Name" but could also be "Name:SubName" to be really precise.

**Comment by markus101** [comment]
Not seeing a lot of interest here, but it's hard to say if it's purely because it's a beta or because virtually no one was using it. I'm inclined not to implement given the lack of interest here and presumably on Radarr's side since the diehard CF users aren't asking for it either.

**Comment by Alanoll** [comment]
Yeah, that's fair. I even mostly ended up using it for Anime to retain the CRC32. 
Not sure of a good way to try and capture it for renaming. It could in theory be parsed (and only for Anime series) from release/filename, and if found it's available, otherwise not. Definitely shouldn't be a calc'd value.

**Comment by markus101** [comment]
While we do parse the hash from some releases it’s not something we store and given the relative niche usage of them it’s not something we plan to add.
