### ISSUE TITLE
Same import list options as Radarr

### ISSUE THREAD

**Issue by IVIrebox** [Sonarr/Sonarr#5280]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I would love if the import list options would be identical to radarrs, it currently only has trakt and plex

### Describe the solution you'd like

Port over from radarr the same features 

### Describe alternatives you've considered

None i dont know how to code :(

**Comment by markus101** [comment]
IMDB is covered here: https://github.com/Sonarr/Sonarr/issues/276 (added in v4 beta)
TMDb is covered here: https://github.com/Sonarr/Sonarr/issues/4959

What, specifically are you looking for that isn't one of those?

**Comment by markus101** [comment]
Closing this then since these are dupes that are found by searching. v4 beta has more options.
