### ISSUE TITLE
Sonarr not Importing from Sabnzbd

### ISSUE THREAD

**Issue by jrac86** [Sonarr/Sonarr#5284]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

on newest version 4.0.0.258. In addition to not loading the activity section, sonarr is not importing anything. It sends the download over to sabnzbd, but never imports the file once it's done.

### Describe the solution you'd like

Sonarr to import the completed files

### Describe alternatives you've considered

Don't have any

**Comment by jrac86** [comment]
Previously had reported in https://github.com/Sonarr/Sonarr/issues/5282, but it was marked as completed and told it was a different issue. They may be related to each other since the queue isn't being detected at all.

**Comment by jpdsc** [comment]
I tested this one NZBget and same result. It's not only affecting SABnzbd as per my testing

**Comment by stevietv** [comment]
Its not a download client bug.

**Comment by tronyx** [comment]
They provided 4.0.0.258 in the issue. I am seeing this same problem and am also running 4.0.0.258.

**Comment by jrac86** [comment]
Still present in 4.0.0.262

**Comment by tronyx** [comment]
> Still present in 4.0.0.262

Release notes for this version don't mention a fix.

**Comment by RandomNinjaAtk** [comment]
Still present in 4.0.0.263

**Comment by PearsonFlyer** [comment]
Here is a full trace log, including a search (where every result threw the instance error) and the attempt to import from sab the show The English. https://gist.github.com/PearsonFlyer/61033d1922202b6ac0e8e34bbfceab72

**Comment by markus101** [comment]
If the GHI is still open and the release notes don't mention a fix there is a very good chance that the issue is not fixed. If it does happen to be fixed, then comment, but "still broken in X" comments are just unnecessary noise. The fix is building now and the release notes will tell you it's fixed.
