### ISSUE TITLE
CF score of 0 for episodes from season pack on history

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#5291]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

season pack has score of 5, on ep import that episode has score of 0. even though it has the same CF matches as the season pack.
i went to grab another version of the episode and it shows up with correct score of 5 for having the same matches

### Expected Behavior

show correct CF score

### Steps To Reproduce

download season pack, compare season pack CF vs season pack episode's CF 

### Environment

```markdown
- OS: windows 10
- Sonarr: 4.0.0.277
- Docker Install: no
- Using Reverse Proxy: no
- Browser: firefox 107.1
```

### What branch are you running?

Develop

### Trace Logs?

![sonarr](http://zoggy.net/firefox_2022-12-11_04-05-23.png)

**Comment by thezoggy** [comment]
codec (4) + english (1)

codec being stuff that doesnt have x265 in it, and then english lang

**Comment by markus101** [comment]
Ahh, the CF's are parsed, but the score wasn't being calculated/stored on import.
