### ISSUE TITLE
Disable enforced authentication -- Regression since #5252

### ISSUE THREAD

**Issue by tzakrajs** [Sonarr/Sonarr#5294]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Unfortunately this functionality is not working. When I set the AuthenticationMethod to External, the dialog pops up requiring me to change it and Sonarr keeps adding more and more AuthenticationMethod lines to the configuration. I am using linuxservers sonarr:develop image (v4 Beta). Please correct this regression. Thank you!!!

This is what it is doing to my config:

```
<AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>

<AuthenticationMethod>External</AuthenticationMethod> # My manual edit, then restart sonarr

<AuthenticationMethod>None</AuthenticationMethod> # After restarting sonarr, this line is created
```

### Expected Behavior

Expecting that when I add 
`  <AuthenticationMethod>External</AuthenticationMethod>`
  
Sonarr will no longer ask me to enable Authentication

### Steps To Reproduce

1. sonarr:develop
2. Start sonarr
3. Set basic auth, disabled for local addresses
4. stop sonarr
5. edit config.xml to have 
  `<AuthenticationMethod>External</AuthenticationMethod> `instead of basic auth or whatever
6. restart sonarr
7. See prompt to configure authentication and the following line is appended to config.xml   `<AuthenticationMethod>None</AuthenticationMethod>`
8. cry

### Environment

```markdown
- OS: Rocky Linux 9
- Sonarr: develop (v4 beta)
- Docker Install: containerd latest
- Using Reverse Proxy: Istio/Envoy
- Browser: Safari/Firefox/anything
```

### What branch are you running?

Develop

### Trace Logs?

2022-12-11 21:54:54.2|Trace|ConfigService|Using default config value for 'episodetitlerequired' defaultValue:'Always'
2022-12-11 21:54:54.3|Debug|EpisodeTitleSpecification|Episode aired more than 48 hours ago
2022-12-11 21:54:54.3|Debug|EpisodeTitleSpecification|Episode aired more than 48 hours ago
2022-12-11 21:54:54.3|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
2022-12-11 21:54:54.3|Trace|ConfigService|Using default config value for 'minimumfreespacewhenimporting' defaultValue:'100'
2022-12-11 21:54:54.3|Debug|DetectSample|Runtime is over 90 seconds
2022-12-11 21:54:54.3|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
2022-12-11 21:54:54.3|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
2022-12-11 21:54:54.3|Debug|ImportDecisionMaker|File accepted

### Anything else?

This is most similar to issue #5252 but since the behavior no longer works its a new issue since this is a regression

**Comment by owine** [comment]
Stop the container before editing the config.

**Comment by tzakrajs** [comment]
> Stop the container before editing the config.

Makes no difference, same behavior

**Comment by owine** [comment]
> > Stop the container before editing the config.
> 
> Those were my steps to reproduce if you read the issue @owine

You also said `My manual edit, then restart` so it was not entirely clear.

The behavior you are describing sounds exactly like a live edit while the container is running and it dumps the config, overwriting your manual edit. I just tested on my own setup in both directions with the desired results and cannot confirm any regression.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

> See prompt to configure authentication and the following line is appended to config.xml <AuthenticationMethod>None</AuthenticationMethod>

This only happens is the `AuthenticationMethod` is not part of the config file when Sonarr is started, Sonarr sets it to the default value (`None`) and writes it to the config file. The only way I can reproduce it not working is to remove the line or change the property name.

If you use an invalid value for `AuthenticationMethod` it'll throw when accessed and if the XML is invalid it'll also fail to load.

**Comment by tzakrajs** [comment]
This issue was due to AuthenticationMethod: Basic being earlier in the config file. I am not used to configuration files that allow multiple keys of the same name. XML sucks ass. Can we use something else?

**Comment by markus101** [comment]
No, we don't have any plans to change the config file format nor something we'd consider doing at this time.
