### ISSUE TITLE
New Language: Latino

### ISSUE THREAD

**Issue by caroku** [Sonarr/Sonarr#5302]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Add new language Profile for latin american spanish, referred as Latino in torrent files.

Examples:
The.MorningShow.S01.2019.720p_Eng-Spa(Latino)_MovieClubMx
Chernobyl.Season.1.WEB-DL.720p.Complete.Latino.YG
Apache.La.vida.de.Carlos.Tevez.2019.WEB-DL.720p.Season.1.Latino.YG
Game.of.Thrones.S08E01.1080p.WEB.H264.Latino.YG
Los Simpsons latino,
X-Files (Temporada 11 Completa) Audio Dual Ingles/Latino 1920x1080
homeland 7x4 audio latino

### Describe the solution you'd like

Add Latino as a language option

### Describe alternatives you've considered

Add an option to create custom languages.

### Anything else?

Thanks for a great job.

**Comment by markus101** [comment]
I imagine we're going to see the same issues as we've seen with https://github.com/Sonarr/Sonarr/pull/5029

What are the appropriate language codes for Latin American Spanish?

**Comment by caroku** [comment]
It may be complicated, you may use latin as an alternative but it's a shorcut. I don't think people will watch a tv show in latin anyway.

**Comment by markus101** [comment]
We're not going to usurp another language for it... that's just going to lead to other issues.

This is for Java, but we might be able to use this info to build what we need: https://www.localeplanet.com/icu/es-419/index.html

**Comment by caroku** [comment]
That sounds promising. By the way I am just a user and I don't know anything about programming, so my answer was just an idea without knowing possible consequences. Thanks for take a look on this request.

**Comment by caroku** [comment]
I would like to add that sometimes español latino is referred as Lat in some releases.
The Soprano Temp 3 Dual (Lat - Eng) 720p
