### ISSUE TITLE
Simkl List integration

### ISSUE THREAD

**Issue by Amateur-God** [Sonarr/Sonarr#5306]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

In light of the current issues Trakt are having with their database it may be prudent to add other list integrations to sonarr such as simkl etc so that people that use both would be able to add one as a back up incase the other goes down

### Describe the solution you'd like

Simkl Lists as an option in import lists

### Describe alternatives you've considered

N/A

**Comment by masyk** [comment]
Getting user's Watching and Plan to watch TV Shows list:

https://simkl.docs.apiary.io/#reference/sync/get-all-items/get-all-items-in-the-user%27s-watchlist
type: tv
status:  watching , plantowatch
