### ISSUE TITLE
feature req: Sort resolution categories by filesize and have program (Sonarr/Prowlarr) DL the smallest one

### ISSUE THREAD

**Issue by GeneralUser-NonDev** [Sonarr/Sonarr#5309]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Files downloaded are not as "archive friendly" as they could be, unknown if there's a way to specify to download the smallest file size entry in X-resolution. If not please implement a way to specify to DL the smallest file size version or one with a specific release groups tag in it.

if it matters I'm running binhex version of sonarr and Prowlarr, I don't know which is responsible for the DL.

### Describe the solution you'd like

some sort of option/method to tell it to download either the smallest filesize or a specific tag "[XYZ-ReleaseGroup]" on a per show/series/entry basis. could also be ported to the other "Arrs" too.

### Describe alternatives you've considered

?

**Comment by markus101** [comment]
In v4 you'll be able to choose your preferred size. You can already prefer or require a specific release group.
If you have more questions please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr).
