### ISSUE TITLE
Option to exclude episodes before/(or without) their release date from RSS

### ISSUE THREAD

**Issue by NekoiNemo** [Sonarr/Sonarr#5312]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently Sonarr will search indexers for episodes without the release date. While this is find most of the time, for some shows with very different ways to count seasons between different platforms, this causes issue.

Case and point: Futurama's 8th season. It was only announced as maybe coming out in 2023, however that's by TVDb's season counting (which Sonarr imports), and according to IMDb - season 8 came out in 2013. So if someone publishes episodes using that numbering systems (and they did) - they will get wrongly pulled in and adopted into the Sonarr's library.

And since those episodes may already have the quality that meets the cutoff point - they will never get upgraded in the future when the real episodes come out, unless user notices it and manually intervenes.

### Describe the solution you'd like

There should be an option in the settings to toggle whenever or not Sonarr will include episodes without the release date (or before their official release date) in automatic search (manual/interactive search should be unfiltered, naturally). Ideally this would be a per show setting, but a global one would be fine too.

### Describe alternatives you've considered

The only alternative is to constantly keep an eye out for new seasons being added to Sonarr for monitored shows and disable that season's monitoring until it begins to come out. Which sort of defeats the whole point of automating the process

### Anything else?

There is already a similar feature implemented in Radarr called "Minimum Availability" for each movie, however because of the difference in how movies and shows are released i don't know how applicable it is.

**Comment by markus101** [comment]
No short term plans for this.
