### ISSUE TITLE
Allow Selective Renaming based on Series Type

### ISSUE THREAD

**Issue by Ravencentric** [Sonarr/Sonarr#5314]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Standard-type shows almost always have properly named files following the `SXXEYY` format and renaming isn't necessary most of the time while Anime type shows almost always need renaming. I would like to avoid altering files unless necessary which means I would like Sonarr to only rename a selected type. Considering Sonarr already allows different naming formats for each type, I think this would be a good addition,

### Describe the solution you'd like

Replace the "Rename Episodes" checkmark with one for each series type:
- "Rename Standard Episodes"
- "Rename Anime Episodes"
- "Rename Daily Episodes"

### Describe alternatives you've considered

Either not renaming any files and manually fixing the problematic ones or just letting it rename everything.

### Anything else?

![image](https://user-images.githubusercontent.com/78981416/208721230-7292609e-48d6-4b56-8136-524089c079a2.png)
![image](https://user-images.githubusercontent.com/78981416/208721865-13b90f76-2965-4fc4-a235-b818cd0bf991.png)

**Comment by markus101** [comment]
Sonarr already has renaming tokens to handle this, they start with Original. We don't plan to change how renaming is enabled.
