### ISSUE TITLE
Option to disable Scene numbering

### ISSUE THREAD

**Issue by lps-rocks** [Sonarr/Sonarr#5316]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

With the release of new web services and a large focus on P2P groups now within many trackers, the need for scene numbering to be force enabled via TheXEM on TV shows is no longer necessary. Even scene groups are not necessarily abiding by scene numbering anymore.

A good example of this is the numbering for American Dad! It's been re-released on various streaming platforms and captured by P2P groups that don't abide by scene numbering, even some scene groups do not abide by the previous scene numbering. 

The argument previously given is that American Dad! is a particularly *bad* representation of episode numbering problems. This is the *exact* use case that having a flag to enable/disable scene numbering is for. For edge cases where TheXEM is unable to solve the problem, and Sonarr cant handle the problem either. This is where the human element is needed, and precisely *why* a toggle should be available to the end user through an advanced or hidden setting, so that the end-user can be that necessary human element.

It's been 3 years since the last time this was seriously considered and was rejected because it was thought that putting more work into the TheXEM would solve the problem *eventually*

It's now 3 years later, the "scene" is becoming less relevant, P2P groups are becoming better, and TheXEM database is *still* unable to address too many edge cases like this one. 

### Describe the solution you'd like

Enable a per-series toggle that allows for an end-user to *disable* scene numbering checking. It's the simplest and most user-friendly way.

### Describe alternatives you've considered

N/A

**Comment by markus101** [comment]
We do not have plans to support disabling scene numbering on a per series basis. We do however support disabling it at the release group level through our database of scene mappings (aliases). This allows it to be fixed for everyone and both scene and TVDB numbering to work hand in hand. Outright disabling would lead to the problem being flipped.

**Comment by lps-rocks** [comment]
That's unfortunate because it requires the user to rely on someone else to:

- Update information in a timely manner
- Update information accurately
- React to every single new release / release group

I'll continue blocking thexem at a firewall level then.
