### ISSUE TITLE
Optional Custom Banner Txt

### ISSUE THREAD

**Issue by scuppasteve** [Sonarr/Sonarr#5320]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

I run a number of different copies of sonarr running in dockers, i have a bunch of libraries i would like to keep separate. I was wondering if there was a way to implement a way to differentiate between them by having a custom text in the header or some other location that is always visible on the main frames of the interface. Honestly anyway that can be implemented to differentiate between them would be fine with me. 

### Describe alternatives you've considered

I guess you could have editable secondary text on the window tab in the web browser. Like

"Sonarr - Anime"
"Queue - Sonar - Anime"

"Sonarr - 4k"
"Queue - Sonar - 4k"

It could be any text in place of Anime or 4k it would be consistent across each page though.

**Comment by Thirrian** [comment]
This is available (I think it was added in v4, not 100% sure) as an advanced option under Settings > General, and works exactly as you describe.

![image](https://user-images.githubusercontent.com/66218321/209326948-35ef7772-9c81-483d-bea6-da0328fdc172.png)
