### ISSUE TITLE
Allow UI to select External Authentication

### ISSUE THREAD

**Issue by Rycochet** [Sonarr/Sonarr#5321]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

With the new requirement it will popup a form on first loading, with options for how to authenticate. For some users who are already using an external method (Traefik / Cloudflare etc) there is an option to note this, but only by editing the configuration file manually (referenced in a comment in https://github.com/Sonarr/Sonarr/issues/5252).

The "Disable for Local Addresses" option is not relevant (and still requires a login to be generated).

### Describe the solution you'd like

An extra dropdown option in the UI to allow noting that an external authentication method is being used.

Potentially / optionally allowing it to specify a header to look for (there are some semi-standards, but they often rely on specific middleware etc).

### Describe alternatives you've considered

Locking my version of Sonarr to not require something as insecure as a userpass login.

**Comment by thezoggy** [comment]
if you can figure out how to do external auth, you can surely figure out how to modify a .xml file to set auth as External?

**Comment by Rycochet** [comment]
> if you can figure out how to do external auth, you can surely figure out how to modify a .xml file to set auth as External?

...Yes - and fortunately I have ssh access in order to actually edit a file on the server, rather than having no filesystem access to it as some providers supply...

**Comment by markus101** [comment]
We do not have plans to do this at this time.
