### ISSUE TITLE
Ability to "init" api key

### ISSUE THREAD

**Issue by shanehughes1990** [Sonarr/Sonarr#5322]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

So I want to setup sonarr again (I am moving from docker to k8s), in that process I am switching from docker-compose to terraform to deploy the sonarr container.

There is a provider for terraform that allows me to configure sonarr via api wrapper plugin for terraform which requires the api key (makes sense no problem so far).

The problem then in lies I cant make api calls automatically without knowing what the api key is FIRST, so I have to apply the sonarr container get the api key it seeds and then run the terraform plugin to configure it

### Describe the solution you'd like

Ability to init an api key that is specified by me, either making the initial api key what is specified OR updating the existing api key to the new one supplied if changed after sonarr is setup.

I see alot of other containers mount a secret file that would be okay, or an env variable that is set, either would work in my case as kubernetes encrypts environment variables that come from a secret anyway, docker users would be more secure if a file was present to load on container start. (OR again docker swarm has secret environment variable support too)

### Describe alternatives you've considered

A really hacky load the whole sonarr config file and overright the existing config that's present (error prone if sonarr updates that file I have to as well to match)

### Anything else?

docker run -e API_KEY=supersecurekey sonarrimage/sonarrtag

**Comment by bakerboy448** [comment]
> Ability to init an api key that is specified by me

Pretty sure this can be done already by precreating the config file with the apikey populated

**Comment by markus101** [comment]
No plans to add the ability to initialize it from environment variables, but Baker is correct you can setup a config .xml file for Sonarr with it set and Sonarr will use it (and add in the other settings as needed). No plans to change from XML to another format, but in the event we did, then it'd either be done with a major version upgrade or come with some sort of migration.

**Comment by shanehughes1990** [comment]
Yeah that was what I stated in the issue that does work, so are you able to tell me when/if that config file changes? I presume it's between major updates v2/v3/v4 etc?

**Comment by bakerboy448** [comment]
The config file can have attributes added at anytime. Major versions have no relevance.
