### ISSUE TITLE
wanted/missing： can't auto search missing episodes

### ISSUE THREAD

**Issue by 7x11** [Sonarr/Sonarr#5327]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

wanted/missing： can't auto search missing episodes
system/tasks：Refresh Monitored Downloads , nothing happend

when manual click "search" button it's will start downloading

### Expected Behavior

system/tasks
will check the 
wanted/missing list, and search the missing episodes

i dont thinks  that must need i to check “wanted/missing list” everyday.

### Environment

```markdown
Version
3.0.9.1549
Package Version
3.0.9.1549-ls171 by linuxserver.io
Mono Version
6.12.0.182
AppData directory
/config
Startup directory
/app/sonarr/bin
Mode
Console
```

### What branch are you running?

Main

### Trace Logs?

noting happed

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
