### ISSUE TITLE
Do not process ._ files on OS X

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#533]
When using a non-HFS+ file system OS X creates extra metadata files that match the file name, but are preceeded with `._`, such as `s01e01.mkv` and `._s01e01.mkv`. We should ignore the metadata files as they aren't actual video files.

**Comment by max6166** [comment]
DetectSample still tries to read ._ files. This results in the error:

`[_Incoming/._TV.SHOW.S01E01.HDTV.XviD-NONE.avi] has a runtime of 0, is it a valid video file?`

Doesn't sound like much, but it results in hundreds of log entries, making it hard to see other error messages.
