### ISSUE TITLE
Disabling `Upgrades Allowed` does not prevent custom format score upgrades.

### ISSUE THREAD

**Issue by bpoxy** [Sonarr/Sonarr#5330]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr is grabbing a release with a higher custom format score than the existing file even if `Upgrades Allowed` is unchecked, if the existing file's custom format score is lower than `Upgrade Until Custom Format Score`.

### Expected Behavior

`Upgrades Allowed` would apply to both quality and custom format score.

### Steps To Reproduce

1. Configure a custom format "Higher" that matches on release title for term "NTb".
2. Configure a custom format "Lower" that matches on release title for term "CAKES".
3. Configure a quality profile "Test":
    i. Score "Higher" as 1000 and "Lower" as 500.
    ii. Set `Upgrade Until Custom Format Score` to 1000.
    iii. Uncheck has `Upgrades Allowed`.
5. Add the show "Doom Patrol" and assign it "Test".
6. Do a manual search of S04E05 and trigger download of the CAKES release.
7. Once that's done, trigger an automatic search.
8. Notice the NTb release is grabbed.

### Environment

```markdown
- OS: Windows 10 x64
- Sonarr: 4.0.0.319
- Docker Install: No
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Develop

### Trace Logs?

https://0bin.net/paste/DsXRtXEL#E3dlScJCmuolo4EOyRvY1uHDLn5BXoCsCKcEhJdK7eY

### Anything else?

Setting `Upgrade Until Custom Format Score` sufficiently low can be used to prevent this but unchecking `Upgrades Allowed` hides this field, making it extra unintuitive. 

In my reproduction steps, I set `Upgrade Until Custom Format Score` to 500, for demonstration purposes. I realize this is a strange configuration, that a real user would likely never set up. In my actual case, it is set to 0 but the existing file's custom format score is negative so the cutoff is unmet. I realize this sort of scoring is also unusual but I still think that `Upgrades Allowed` not applying to custom format scores while also hiding `Upgrade Until Custom Format Score` is a confusing experience, hence the bug report.

**Comment by thezoggy** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by bpoxy** [comment]
> Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

I already asked about this on Discord and was told to use `Upgrade Until Custom Format Score` to prevent this.
This is definitely an option but is unintuitive.

**Comment by thezoggy** [comment]
"upgrades allowed" has nothing to do with CF, its for quality upgrades in the profiles. 
CF is all scoring based, which is why you set a min score and a upgrade until score.

**Comment by bpoxy** [comment]
> "upgrades allowed" has nothing to do with CF, its for quality upgrades in the profiles. CF is all scoring based, which is why you set a min score and a upgrade until score.

That's fair but, if that's the case, `Upgrades Allowed` shouldn't hide `Upgrade Until Custom Format Score`.

**Comment by bakerboy448** [comment]
Upgrades allowed should probably also apply to CF upgrades given the it hides the upgrade until score.

alternatively if CFs are intended to be disconnected from the upgrades allowed then the upgrade until score must always be displayed

**Comment by bakerboy448** [comment]
> "upgrades allowed" has nothing to do with CF, its for quality upgrades in the profiles.
> CF is all scoring based, which is why you set a min score and a upgrade until score.

Comparing to Radarr's  code this statement seems incorrect.

https://github.com/Radarr/Radarr/blob/7feda1c446caef07a5d1d57e1618ccf72740cd15/src/NzbDrone.Core/DecisionEngine/Specifications/UpgradeAllowedSpecification.cs#L45

it's an oversight in Sonarr it appears

https://github.com/Sonarr/Sonarr/blob/8fff59ff107d9a9fcfc0de1acb6aa635565e5d9b/src/NzbDrone.Core/DecisionEngine/Specifications/UpgradeAllowedSpecification.cs#L36
