### ISSUE TITLE
On Series Added Notification

### ISSUE THREAD

**Issue by dexn** [Sonarr/Sonarr#5337]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

There is a notification trigger for a series deletion but not for addition.

### Describe the solution you'd like

Implement a trigger for "On Series Added", similar to Radarr's "On Movie Added".

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/3637
