### ISSUE TITLE
"Couldn't import episode file x is not a child of folder y" aka NzbDrone.Common.Disk.NotParentException error moving files PLEASE HELP PLEASE!

### ISSUE THREAD

**Issue by FTWOblivion** [Sonarr/Sonarr#5338]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

completed downloads not being moved to respective folder

### Expected Behavior

downloads should be moved after completion

### Environment

```markdown
- OS: 11
- Sonarr:V3 & V4 specifically 4.0.0.328
 
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

*[v4.0.0.328] NzbDrone.Common.Disk.NotParentException: I:\torrent\TV \examplefileinfomedia.mp4 is not a child of I:\torrent\TV
at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath(String parentPath, String childPath) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 81
at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.GetOriginalFilePath(DownloadClientItem downloadClientItem, LocalEpisode localEpisode) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 182
at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 106

### Anything else?

Can someone please help me resolve this error? It will not import any downloads from qbit after completion and i have no clue what to do other than manually moving them. Used to work fine on previous version then latest V3 update broke it and i thought V4 beta would fix it but issue persists… Please if anyone can shed some light on my shadow of confusion here and resolve this issue i would be grateful.:

**Comment by bakerboy448** [comment]
- v4 is not `main` branch
- a single line error is not the required trace logs that is required for bug reports.
- is this qbit 4.5.0 which as undocumented breaking api changes and is not supported with Sonarr etc?   Based on that section of code it looks like qbit is incorrectly reporting the torrent as being in a folder when it is not?
- Alternatively is keep top level folder in qbit set to none when it needs to be original or create folder, whatever the exact options are

**Comment by FTWOblivion** [comment]
So i was able to resolve it by totally reformatting the drive it was attempting to pull from and entirely redownloading sonar from scratch. I believe there was a permissions issue with a failed hardlink. Total amateur guess. But booting in safemode and formatting the drive seems to fix it, sorry for ignorance regarding this troubleshooting process. I can upload full logs later if you are curious or need them but i just uploaded the part that was repeated with an error. I would be shocked if there was actually more valuable info beyond that section in the log but seriously-what do i know. I just got lucky brute forcing a solution to this issue today. Im sure there were more eloquent solutions and explanations for the issue. All i know is it wasnt working, now it is.. sorry and thanks for the attention. Like i said i can upload log files later if you like but i think even those are compromised in integrity now since i fully reinstalled the old logs are gone now i thinkSent from my iPhoneOn Jan 3, 2023, at 7:13 AM, bakerboy448 ***@***.***> wrote:﻿

v4 is not main branch
a single line error is not the required trace logs that is required for bug reports.
is this qbit 4.5.0 which as undocumented breaking api changes and is not supported with Sonarr etc?   Based on that section of code it looks like qbit is incorrectly reporting the torrent as being in a folder when it is not?
Alternatively is keep top level folder in qbit set to none when it needs to be original or create folder, whatever the exact options are

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
