### ISSUE TITLE
v3.0.9.1549 "spontaneously" changing episodes from  unmonitored to monitored

### ISSUE THREAD

**Issue by rrrevin** [Sonarr/Sonarr#5339]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Been running Sonarr for many many months without issues, this started about 2 - 3 weeks ago. When connecting to Sonarr in the morning, sometime overnight Sonarr has decided to change episodes that I previously marked as unmonitored months/years ago, to monitored. Going to the "Wanted" menu suddenly shows "new" items that should not be there. The only way to fix is to manually set them back to unmonitored. Come back the next morning, and there is a bunch more "new" items added to the wanted list. Again, all of these items were manually set to unmonitored previously, and are not the same items from the time before.

The debug logs (show name redacted) have the following for shows that Sonarr changes episode monitor status:
```
sonarr.0.txt:2022-12-29 23:17:47.0|Warn|RefreshEpisodeService|Show 280394 (xxxxx) had 31 old episodes appear, please check monitored status.
sonarr.0.txt:2022-12-29 23:19:01.7|Warn|RefreshEpisodeService|Show 366524 (xxxxx) had 9 old episodes appear, please check monitored status.

sonarr.0.txt:2022-12-30 11:25:33.8|Warn|RefreshEpisodeService|Show 297091 (xxxxx) had 18 old episodes appear, please check monitored status.
sonarr.0.txt:2022-12-30 23:28:22.3|Warn|RefreshEpisodeService|Show 277658 (xxxxx) had 1 old episodes appear, please check monitored status.
sonarr.0.txt:2022-12-30 23:28:34.0|Warn|RefreshEpisodeService|Show 266189 (xxxxx) had 29 old episodes appear, please check monitored status.
sonarr.0.txt:2022-12-30 23:28:47.8|Warn|RefreshEpisodeService|Show 85019 (xxxxx) had 65 old episodes appear, please check monitored status.
sonarr.0.txt:2022-12-30 23:29:44.6|Warn|RefreshEpisodeService|Show 361701 (xxxxx) had 6 old episodes appear, please check monitored status.
sonarr.0.txt:2022-12-30 23:32:54.1|Warn|RefreshEpisodeService|Show 401966 (xxxxx) had 4 old episodes appear, please check monitored status.
sonarr.0.txt:2022-12-30 23:32:58.2|Warn|RefreshEpisodeService|Show 336924 (xxxxx) had 30 old episodes appear, please check monitored status.

sonarr.0.txt:2022-12-31 23:42:20.1|Warn|RefreshEpisodeService|Show 363955 (xxxxx) had 23 old episodes appear, please check monitored status.
sonarr.0.txt:2022-12-31 23:47:29.9|Warn|RefreshEpisodeService|Show 84669 (xxxxx) had 26 old episodes appear, please check monitored status.
sonarr.0.txt:2022-12-31 23:47:57.3|Warn|RefreshEpisodeService|Show 393154 (xxxxx) had 3 old episodes appear, please check monitored status.

sonarr.txt:2023-01-03 00:06:06.1|Warn|RefreshEpisodeService|Show 402256 (xxxxx) had 1 old episodes appear, please check monitored status.
sonarr.txt:2023-01-03 00:06:16.0|Warn|RefreshEpisodeService|Show 280394 (xxxxx) had 95 old episodes appear, please check monitored status.
sonarr.txt:2023-01-03 00:06:21.0|Warn|RefreshEpisodeService|Show 85019 (xxxxx) had 28 old episodes appear, please check monitored status.
```
I've enabled trace logging and will update the trace section when something pertinent appears.

### Expected Behavior

episodes that are marked unmonitored, remain unmonitored, always.

### Environment

```markdown
Version: 3.0.9.1549
Package Version: 3.0.7 by Team Sonarr
Mono Version: 6.12.0.182
AppData directory: /var/lib/sonarr
Startup directory: /usr/lib/sonarr/bin
Mode: Console
```

### What branch are you running?

Main

### Trace Logs?

-

**Comment by PearsonFlyer** [comment]
This is an issue caused by TVDB's cache. Please see this reddit thread with more information.  https://www.reddit.com/r/sonarr/comments/zxjnsr/sonarr_showing_incomplete_seasons_or_episodes/

**Comment by rrrevin** [comment]
Thanks. If the episode already exists in Sonarr, and is unmonitored, why even update it in Sonarr to monitored?

**Comment by rrrevin** [comment]
OK.. I think I understand.

- TVDBs cache "removes" the episode from it's cache.
- Sonarr reads the show from TVDB
- Sonarr sees the episode no longer exists and happily removes it from it's own list.
- Sonarr later reloads/refreshes the show and sees a "new" eposide for the show.
- Sonarr (re)adds this previously removed episode back to the show, thinking it's new, and marks it as unmonitored.

Is that correct?

**Comment by markus101** [comment]
It’s mostly full seasons, but not limited to.
