### ISSUE TITLE
Make Season folder format part of Episode format

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#534]
Right now we have the season folder format and the per series use season folder option, both of these would need to be removed and we'd need to merge the season folder format into the episode formats.

Migration wise we need to only add it if the user wants it part of the each series type, which will remove some of the flexibility users currently have and we'll need to determine a way to validate whether season folders are wanted or not.

**Comment by Taloth** [comment]
I think it's a bad idea, complicates matters for 99% of the users while it's only useful for ppl that like to only have the episode number in the filename.
I think the 1x01 format is a good enough alternative.

**Comment by markus101** [comment]
Currently we do support both, I'd be happy with closing this one since we can do it, opt-in.
