### ISSUE TITLE
Add IMDB Link to Telegram Notifications

### ISSUE THREAD

**Issue by Zantag** [Sonarr/Sonarr#5342]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have telegram group with telegram bot connected to sonarr, radarr and bazarr. 
The notifications from radarr has imdb link... notifications from sonarr doesn't... in the example below you will see how bad look like the notification from sonarr without preview from the imdb link...
![image](https://user-images.githubusercontent.com/1080384/210436469-b49856a6-274e-42a8-b1bf-4c0ccb50b224.png)

### Describe the solution you'd like

I want just to add imdb link for the tv series in all notification connected to telegram bots... the same way used in radarr.

### Describe alternatives you've considered

Hope this will be not hard to be integrated in the notifications feature...

**Comment by markus101** [comment]
I imagine Radarr always has IMDB IDs, but for Sonarr that's not always the case, it'd be more reliable to have TheTVDB links instead.

**Comment by Zantag** [comment]
> I imagine Radarr always has IMDB IDs, but for Sonarr that's not always the case, it'd be more reliable to have TheTVDB links instead.
 Every TV series on my sonarr has IMDB link... The links from IMDB also has nice preview... So i prefer IMDB.
 
 
 
![image](https://user-images.githubusercontent.com/1080384/210616405-f1d42358-d65d-420f-88ad-452c64b07fa5.png)

**Comment by markus101** [comment]
Making it optional and giving a choice should be easy enough whenever someone picks this up.

**Comment by ricci2511** [comment]
I recently thought about this too.
I guess we can add the imdb url in the `GetMessage` method in `NotificationService.cs` just like Radarr does. But maybe you have something else in mind? @markus101

**Comment by Adair-GA** [comment]
I can do this, it does't seem to be really hard, but I'm a bit confused as how would I make it an optional feture. It seems that it could either be an option for the telegram connection, or it could be included in the `GetMessage` method, but that would make it appear on all connections, and I don't see how could I make that optional.

**Comment by markus101** [comment]
I don't think we want to add it to every message by adding to to `NotificationService`.

The simplest solution would be to add an option to `TelegramSettings`, then conditionally append it to the message before sending, which can be done with a function in `Telegram.cs` that takes the message input and outputs the updated message.

**Comment by qTipTip** [comment]
I'd be happy to take a shot at this if nobody else has given it a go. I've already put together a reference implementation that includes an IMDb link. However, I'm a bit uncertain about how to generate a TVDb URL from the ID. It would be great to have a conditional setting that allows you to pick the database you prefer, although we should be careful not to make it overly complex. If IMDb suits your needs, that would be the most straightforward option.


![Screenshot 2024-03-09 003426](https://github.com/Sonarr/Sonarr/assets/11932512/fe997cf6-d0fc-4105-9d24-f9befe7bfed6)
![Screenshot 2024-03-09 001358](https://github.com/Sonarr/Sonarr/assets/11932512/20dff9d6-683e-47fd-8215-1b4027eb9929)

**Comment by markus101** [comment]
>  I'm a bit uncertain about how to generate a TVDb URL from the ID

Series details uses the IDs to create links to the various metadata sites so you can see how it's done there.

> It would be great to have a conditional setting that allows you to pick the database you prefer, although we should be careful not to make it overly complex

There are quite a few examples where an enum is used to generate a select list on the UI (`ReleaseTypeSpecification` for Custom Formats is a recently added example).
