### ISSUE TITLE
Add Healthcheck warning for Download Clients with Remove Enabled in Client 

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#5343]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Similar to https://github.com/Sonarr/Sonarr/issues/4985

Add healthchecks to warn if the client is enabled to remove downloads for

- [ ] deluge
- [ ] Sabnzbd
- [ ] Qbit
- [ ] Nzbget 

also add Sorting healthcheck to nzbget 

### Describe the solution you'd like

Title/above

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by bakerboy448** [comment]
(edited to expand scope to common clients if they are set to removed download)

**Comment by markus101** [comment]
Closed via 7f2cd8a0e99b537a1c616998514bacdd8468a016
