### ISSUE TITLE
Importing video file subtitle suffix changed from [en] to [english.(us)] 

### ISSUE THREAD

**Issue by baruser123** [Sonarr/Sonarr#5345]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Last week I updated my docker instance of sonarr (linuxserver/sonarr) to the latest. And now I experience that when I'm importing a video file where the subtitle has the value enUS the subtitle suffix in the filename is changed from [en] to [english.(us)] and for enGB it has change to [english.(gb)].

In setting, media management, Standard Episode Format I use the value {mediainfo.subtitlelanguages:EN}. So i don't see all the subtitle suffixes in the filename. But the problem now that if the subtitle has the value enUS or enGB there don't appear a suffix [en] or something else in the filename.

I tried multiple values in mediainfo.subtitlelanguages: like enUS, ENUS or US to get the suffix back in the filename but no results

So 2 possible solution I'm thinking about is to roll back that enUS is back to [en] or a possibility to also allow enUS and usGB in mediainfo.subtitlelanguages

### Expected Behavior

1) changed back enUS and enGB in the suffix back to en
2) add new values in mediainfo.subtitlelanguages to also allow enGB and enUS

### Steps To Reproduce
1) add mediainfo.subtitlelanguages to Standard Episode Format
2) had a video file with the value enUS
3) import this video file
4) see that english.(us) is added as suffix
5) edit mediainfo.subtitlelanguages to mediainfo.subtitlelanguages:EN
6) import videofile again
7) see there is no suffix now
8) edit via mkvtoolnix the value enUS to en
9) import videofile again
10) notice that now there is a suffix [en]

_No response_

### Environment

```markdown
- OS: Synology / Docker
- Sonarr: 3.0.9.1549-ls171 by linuxserver.io 
- Docker Install: 3.0.9.1549-ls171 by linuxserver.io 
- Using Reverse Proxy: NO
- Browser: firefox but also chrome
```

### What branch are you running?

Main

### Trace Logs?

not necessary i think

**Comment by markus101** [comment]
What is your _exact_ Standard naming format?

> not necessary i think

Yes, they are necessary, let's see the logs of an affected import.

Please also include the media info for the file that shows all the subtitle information.

**Comment by baruser123** [comment]
hereby export from media info

[mediainfo.txt](https://github.com/Sonarr/Sonarr/files/10349074/mediainfo.txt)

**Comment by baruser123** [comment]
and just for extra info hereby a videofile with the suffix [en]


[mediainfo.txt](https://github.com/Sonarr/Sonarr/files/10349094/mediainfo.txt)

**Comment by bakerboy448** [comment]
Media info that sonarr sees from the file?

**Comment by baruser123** [comment]
> Media info that sonarr sees from the file?

? Sorry dont know what you mean. I run sonarr on a synology and not on a windows machine. i stalled media info from your lik nand install this and within media info i opened the mkv..

how can i get the media info via sonarr?

**Comment by markus101** [comment]
I'm not able to reproduce this with the v4 beta (which no longer uses media info), perhaps an issue with the media info version in that docker image.
