### ISSUE TITLE
Show total selected size when multiple shows are selected in Bulk Edit

### ISSUE THREAD

**Issue by douglas24** [Sonarr/Sonarr#5348]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Would it be possible to put a total selected size at the bottom in Bulk Edit mode when multiple shows are selected? Seeing a total size would be super useful when moving multiple shows (and movies/music/books if the code can be added to the other media managers)!

### Describe the solution you'd like

Add a Total Selected Size: #### info section to the bottom menu area of Mass Editor. Maybe an option to turn it on/off in Options menu on that page if not everyone wants to see it?

### Describe alternatives you've considered

Only alternative is to manually add up the sizes as far as I know there's no count of used space anywhere just total space (drive size) and free space (on drive).

**Comment by markus101** [comment]
No plans to squeeze more information into that view currently. You can see see used space on the series details page or at the bottom of the series index page.
