### ISSUE TITLE
Separate Completed Download Handling and Sorted Folders

### ISSUE THREAD

**Issue by justrhysism** [Sonarr/Sonarr#535]
My description my not quite describe what I'm looking to achieve, but basically, I want to import downloaded videos into iTunes.

I already have a third-party application which watches a folder, gathers metadata, converts to the appropriate format and then imports into iTunes.

What I really want Sonarr to do is use the iTunes media directory as it's sorted folder, but move the downloaded files to a different directory (so I can perform my own processing), rather than directly into the sorted folder.

If this is already possible, please describe how - I haven't been able to figure it out :disappointed: 

I currently don't have a Windows box, so I can't contribute towards development. Off topic a little, but it would be cool if the project could be written using Visual Studio Code :smile:

**Comment by markus101** [comment]
This isn't something we're going to support, but should be somewhat achievable via: https://github.com/Sonarr/Sonarr/issues/439
