### ISSUE TITLE
Sonarr V4 does not always display Custom Format condition titles properly

### ISSUE THREAD

**Issue by yammes08** [Sonarr/Sonarr#5357]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When updating the name of a condition within a custom format, in some circumstances the name appears truncated back on the main Custom Format screen.

### Expected Behavior

The name would not be truncated on the main Custom Format screen

### Steps To Reproduce

1. Create a new custom format in Sonarr V4. Here's the example I used, which can be imported then saved:
```json
{
  "name": "Language: English",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Not English",
      "implementation": "LanguageSpecification",
      "negate": true,
      "required": false,
      "fields": {
        "value": 1
      }
    }
  ]
}
```
2. Observe condition name on main Custom Format screen shows "Not English"
3. Open the Custom Format again, then the condition, and rename the condition to "Not English Language". Save the condition, then save the CF
4. Observe condition name on main Custom Format screen shows "Not Englis...glish Language"
5. Delete that CF. Import a new CF using the following:
```json
{
  "name": "Language: English",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Not English Language",
      "implementation": "LanguageSpecification",
      "negate": true,
      "required": false,
      "fields": {
        "value": 1
      }
    }
  ]
}
```
6. Observe condition name on main Custom Format screen shows "Not English Language"

### Environment

```markdown
- OS: Unraid/Docker
- Sonarr: 4.0.0.339
- Docker Install: v4-3dced0c by hotio
- Using Reverse Proxy: No
- Browser: Firefox 108.0.2 (64-bit)
```

### What branch are you running?

Develop

### Trace Logs?

Display bug, so uncertain if trace logs required.

**Comment by markus101** [comment]
Looks to be cause by `inline-block` with a `max-width` on Firefox (similar to https://stackoverflow.com/questions/24761305/inline-block-max-width-not-working-in-firefox), though Middle Truncate wasn't working quite right on there in Chrome even with some other tweaks, ended up ripping it out.
