### ISSUE TITLE
Housekeeping task breaks Quality Profiles

### ISSUE THREAD

**Issue by mirolm** [Sonarr/Sonarr#5359]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After version 4.0.0.342 i noticed that when i run the "Housekeeping Task" all my Quality Profiles break. By breaking i mean that all CF and scores in them get missing. If i try to search for an episode of a show scores do not apply.

When i restore from backup all gets fixed, till the next run of the Housekeeping Task.

### Expected Behavior

Quality profiles should show CF and their scores.

### Steps To Reproduce

1. Install sonarr 4.0.0.342.
2. Check your Quality Profiles have CF's and they have their respective scores.
3. Go to System --> Tasks --> Run Housekeeping task.
4. Go back to Settings --> Profiles --> Check a Quality Profile --> all profiles have their CF's and scores missing.
5. Go to a Show and click the "hourglass" icon to search episode. No CF scores are applied.
6. Restore from backup - all profiles and scores are fixed.

### Environment

```markdown
- OS: Debian Buster 10.13 x64
- Sonarr: 4.0.0.342
- Docker Install: None
- Using Reverse Proxy: Nginx
- Browser: Google Chrome 108.0.5359.125
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.trace.zip](https://github.com/Sonarr/Sonarr/files/10371859/sonarr.trace.zip)

**Comment by bakerboy448** [comment]
Confirmed/Repro'd

logs don't wouldn't show much
https://gist.github.com/bakerboy448/eee04bcaae7b0cc023101d4382f50f55
