### ISSUE TITLE
Make series tags clickable and searchable

### ISSUE THREAD

**Issue by dnnr** [Sonarr/Sonarr#536]
There are few things related to tagging that could make tags more powerful without adding significant clutter:
- **Make tags clickable:** Clicking a tag should lead to a search-results-like list of series with this tag. For consistency, this should perhaps also work for everything else that is presented like a tag, such as the quality, the channel, the episode length, and so on. Personally, as a new user, I was quite confused by these properties being styled as tags but behaving _nothing_ like tags usually do.
- **Search by tags:** This is kind of the logical consequence to the above... the search box should not only match show titles but also tags (and again, maybe the other properties as well). This of course increases the number of matching shows when searching, so a good visualization/ordering of the results is needed. For example, you could group the results by what matches, starting with series titles as the most important indicator and only listing shows with matching tags after that. Alternatively, a syntax with specific search qualifiers could be used (like on GitHub).

My proposal is similar to #470, but I feel that this here might be a smaller, first step towards increasing the usefulness of tags.

**Comment by markus101** [comment]
The search input will allow searching by tags in v3. Tags aren't clickable, but #470 has been implemented and it will be possible to add custom filters to the series list.
