### ISSUE TITLE
error atomohd pach start of the application

### ISSUE THREAD

**Issue by MiTvSpain** [Sonarr/Sonarr#5360]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

after installing sonnar from 0 and applying the atomohd patch, I get an error when starting sonnar from the web browser

### Expected Behavior

after installing sonnar from 0 and applying the atomohd patch, I get an error when starting sonnar from the web browser

### Environment

```markdown
- OS: ubuntu 18
- Sonarr: 3.0.9.1549
- Docker Install: no
- Using Reverse Proxy: no
- Browser: chrome, firefox
```

### What branch are you running?

Main

### Trace Logs?

The DataMapper was unable to load the following field: 'Languages' value: '[ { "language": 13, "allowed": false }, { "language": 0, "allowed": false }, { "language": 30, "allowed": false }, { "language": 17, "allowed": false }, { "language": 14, "allowed": false }, { "language": 3, "allowed": false }, { "language": 11, "allowed": false }, { "language": 18, "allowed": false }, { "language": 12, "allowed": false }, { "language": 15, "allowed": false }, { "language": 29, "allowed": false }, { "language": 24, "allowed": false }, { "language": 21, "allowed": false }, { "language": 8, "allowed": false }, { "language": 5, "allowed": false }, { "language": 9, "allowed": false }, { "language": 22, "allowed": false }, { "language": 27, "allowed": false }, { "language": 23, "allowed": false }, { "language": 20, "allowed": false }, { "language": 4, "allowed": false }, { "language": 2, "allowed": false }, { "language": 19, "allowed": false }, { "language": 16, "allowed": false }, { "language": 1, "allowed": true }, { "language": 7, "allowed": false }, { "language": 6, "allowed": false }, { "language": 25, "allowed": false }, { "language": 10, "allowed": false }, { "language": 28, "allowed": false }, { "language": 26, "allowed": false } ]'. ID does not match a known language Parameter name: id
Version 10.0.0.16667

### Anything else?

The DataMapper was unable to load the following field: 'Languages' value: '[ { "language": 13, "allowed": false }, { "language": 0, "allowed": false }, { "language": 30, "allowed": false }, { "language": 17, "allowed": false }, { "language": 14, "allowed": false }, { "language": 3, "allowed": false }, { "language": 11, "allowed": false }, { "language": 18, "allowed": false }, { "language": 12, "allowed": false }, { "language": 15, "allowed": false }, { "language": 29, "allowed": false }, { "language": 24, "allowed": false }, { "language": 21, "allowed": false }, { "language": 8, "allowed": false }, { "language": 5, "allowed": false }, { "language": 9, "allowed": false }, { "language": 22, "allowed": false }, { "language": 27, "allowed": false }, { "language": 23, "allowed": false }, { "language": 20, "allowed": false }, { "language": 4, "allowed": false }, { "language": 2, "allowed": false }, { "language": 19, "allowed": false }, { "language": 16, "allowed": false }, { "language": 1, "allowed": true }, { "language": 7, "allowed": false }, { "language": 6, "allowed": false }, { "language": 25, "allowed": false }, { "language": 10, "allowed": false }, { "language": 28, "allowed": false }, { "language": 26, "allowed": false } ]'. ID does not match a known language Parameter name: id
Version 10.0.0.16667

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

> Version 10.0.0.16667

This is not 3.0.9.1549 like you said above.
