### ISSUE TITLE
Sonarr v4 does not open anymore on LG WebOS tv browser.

### ISSUE THREAD

**Issue by mrmuiz** [Sonarr/Sonarr#5363]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr v4 does not open on LG WebOS webbrowser anymore. 
Only the favicon shows. Screen stays white.
It shows up fine on all other devices, PC, Phone etc. So nothing is wrong with that.
Latest version that opens up normaly : 4.0.0.333 
All versions after that till today wont open.

### Expected Behavior

Go to sonarr on the LG WebOS webbrowser and browse sonarr.

### Steps To Reproduce

Install version after version till i found when it went wrong.

### Environment

```markdown
- OS: Synology 7.1
- Sonarr: v4
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: LG WebOS browser
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/10396581/sonarr.trace.txt)

### Anything else?

![325172210_1676876699425623_4216614194680330550_n](https://user-images.githubusercontent.com/118138382/211936078-4fa99df7-63e8-4291-aa6f-852f4a52dadd.jpg)
It only shows the favicon.

**Comment by markus101** [comment]
Without logs from the browser it's going to be hard to identify what might be going wrong, doesn't help that webOS TVs use Chromium versions that are years out of date when they are first released.

Which model of web OS TV?
Which webOS version is it running?
What version of the web browser, if available?

**Comment by bakerboy448** [comment]
```
2023-01-11 23:52:26.8|Info|Sonarr.Http.Authentication.BasicAuthenticationHandler|Basic was not authenticated. Failure message: Authorization header missing.
```

similar weird issues with the UI being seen in Prowlarr as well for that entry. 
https://github.com/Prowlarr/Prowlarr/issues/1282

does it work if you change auth to forms instead of basic?

**Comment by mrmuiz** [comment]
> Without logs from the browser it's going to be hard to identify what might be going wrong, doesn't help that webOS TVs use Chromium versions that are years out of date when they are first released.
> 
> Which model of web OS TV? Which webOS version is it running? What version of the web browser, if available?

LG OLED55B16LA (July 2021)
WebOS 6.3.2
Latest firmware 03.34.50 (Few days old)

I dont know how to get logs of the tv.
Only thing i know its not the tv that does this but sonarr.
Till version 4.0.0.333 it opens fine. All versions after that do not. I tried them all.
And when i go back to 4.0.0.333 it works fine again.
So something must be changed since that version.

**Comment by mrmuiz** [comment]
> ```
> 2023-01-11 23:52:26.8|Info|Sonarr.Http.Authentication.BasicAuthenticationHandler|Basic was not authenticated. Failure message: Authorization header missing.
> ```
> 
> similar weird issues with the UI being seen in Prowlarr as well for that auth error entry. [Prowlarr/Prowlarr#1282](https://github.com/Prowlarr/Prowlarr/issues/1282)
> 
> does it work if you change auth to forms instead of basic?

Can you please tell me how i can do that?

**Comment by bakerboy448** [comment]
Settings => General => Security => Authentication

Or via the config file for auth method

**Comment by mrmuiz** [comment]
> Settings => General => Security => Authentication
> 
> Or via the config file for auth method

I tried all possibilities with that basic/Forms and both with and without disable for local adresses.
Only difference is that it shows login pages. But after entering name and pass the screen goes white again.

**Comment by markus101** [comment]
To my knowledge, webOS has never upgraded the browser engine within webOS (or the webOS version after release), 6.3 is webOS 6, which as you noted has Chromium 79.

4.0.0.334 added a change that relies on Chromium 81, which is why this broke on webOS 6, I'll see if we can solve it.

**Comment by mrmuiz** [comment]
I can confirm that version 4.0.0.346 is working fine again on WebOS tv.
Thx for the fix !
