### ISSUE TITLE
Release level CF is incorrectly applied to episode custom formats in season pack releases without groups or non-standard groups

### ISSUE THREAD

**Issue by grapexy** [Sonarr/Sonarr#5365]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If the season pack release is missing a release group, or the group is one of the exception-groups (releases that end with `RlsGroup)` or `RlsGroup]`, imported episodes inherit CF scores from the pack title, rather than parsing them per episode.

### Expected Behavior

CF scores for episodes imported from a season pack without release group or exception-group should be calculated on per-episode basis, rather than inherited from the pack title - as is the standard behavior for releases with groups or with standard naming groups.

### Steps To Reproduce

1. Create CF that would only be valid on the pack level, but not on the episode level (e.g. season pack):
```
{
  "name": "Season Pack",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Season Packs",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\bS\\d+\\b(?!E\\d+\\b)"
      }
    }
  ]
}
```
2. Import a season pack release that is missing a release group, or is using a release group in exceptions:
```
Show Name (2021) Season 1 S01 (1080p BluRay x265 HEVC 10bit AAC 5.1)
```
OR
```
Show Name (2021) Season 1 S01 (1080p BluRay x265 HEVC 10bit AAC 5.1 Silence)
```
3. Season pack CF is applied to all imported episodes, even though individual episode will not satisfy season pack CF regex:

![Screenshot](https://i.imgur.com/1tpLtyr.png)

4. Season pack CF is missing in the import history event, as it should be:

![Screenshot](https://i.imgur.com/smn66EZ.png)

### Environment

```markdown
- OS: Unraid
- Sonarr: 4.0.0.344
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Develop

### Trace Logs?

N/A

### Anything else?

Example of a season pack release with standard group, correctly missing the season pack CF on episode level:
![Screenshot](https://i.imgur.com/VwNRPLK.png)

**Comment by markus101** [comment]
Custom formats are dynamic, for history they are based on the source name, which varies based on the event type, but for imports/deletes that'd be the file name at time of deletion, from grabs that's the release name of the torrent.

With the cropped screenshots and mixing of reproduction steps and current/expected behaviour it's not clear exactly what the issue is. Please provide more context in your screenshots (without redactions) so we can see what's is happening.

**Comment by grapexy** [comment]
Adding unredacted screenshots.

### Unexpected scenario 1
Release from a release group present in naming exceptions 

https://github.com/Sonarr/Sonarr/blob/f742e1f1748f00b00f509d16732dd160063a985c/src/NzbDrone.Core/Parser/Parser.cs#L493

1. Season pack CF is present for individual, imported episodes (**not expected**):
![Episode list](https://i.imgur.com/QCM398z.png)
2. Season pack CF is present in individual, imported episode details (**not expected**):
![Episode details](https://i.imgur.com/46BDEdK.png)
3. Season pack CF is present in grab (**expected**):
![Grab](https://i.imgur.com/3NyZkkU.png)
4. Season pack CF is not present in individual episode import event (**expected**):
![Import](https://i.imgur.com/sESTTxX.png)

----

### Unexpected scenario 2
Release from a release group that can't be parsed by sonarr:

1. Season pack CF is present for individual, imported episodes (**not expected**):
![image](https://user-images.githubusercontent.com/100813784/212126131-5d569ec8-1980-4bed-9942-b949d47bb397.png)
2. Season pack CF is present in individual, imported episode details (**not expected**):
![image](https://user-images.githubusercontent.com/100813784/212126456-5fae40f0-8c57-4ebf-9451-a62c41b5c632.png)
3. Season pack CF is present in grab (**expected**):
![Image](https://user-images.githubusercontent.com/100813784/212126844-a084f254-3ae5-44db-a545-b2321d5f2e74.png)
4. Season pack CF is not present in individual episode import event (**expected**):
![Image](https://user-images.githubusercontent.com/100813784/212127155-81145472-456d-437c-aa2e-1c83e85bc984.png)

### Expected scenario

Release from a release group using proper naming standards:

1. Season pack CF is NOT present for individual, imported episodes (**expected**):
![image](https://user-images.githubusercontent.com/100813784/212128089-6318217d-ff06-46c5-8b30-b2ffc68ea722.png)
2. Season pack CF is NOT present for individual, imported episode details (**expected**):
![image](https://user-images.githubusercontent.com/100813784/212128604-2c95eaf6-4f83-406c-9d38-f0c194a77c70.png)
3. Season pack CF is present in grab (**expected**):
![Image](https://user-images.githubusercontent.com/100813784/212128946-63f6f9ff-f190-4dfd-837f-c68b91b38f67.png)
4. Season pack CF is not present in individual episode import event (**expected**)
![Image](https://user-images.githubusercontent.com/100813784/212129757-6719626f-234f-4169-a777-14f352527130.png)


### Notes

I may be misunderstanding how CFs are applied and this could be expected, however, I don't understand why there's a discrepancy. 

When there is a properly parsed group in the season pack release, season pack CF is not present for individual episodes (i.e. not inherited from pack release title), as is expected, but whenever a release group is missing / can't be parsed / is a special group, sonarr also applies CFs from the season pack release title to each individual episode it imports in episode details. Another discrepancy is that import event is properly NOT showing a season pack CF, but the resulting episode file from it - does.
