### ISSUE TITLE
Time stamp in Manual Import uses wrong TZ

### ISSUE THREAD

**Issue by KingIzzymon** [Sonarr/Sonarr#5366]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When manually importing a season set that didn't automatically import, there is a red warning signal on the right for each episode. Hovering the mouse over that will display the reason why each episode file wasn't imported (this time it was because the file was already imported, but hadn't been removed from transmission).

The problem is the time stamp for when things are imported is using the wrong time zone, even when the time is correct in the logs:

![image](https://user-images.githubusercontent.com/94716517/212128510-097524a0-a414-4cdd-a7b6-800919b86c3a.png)

### Expected Behavior

Expected that the time would be accurate.

### Steps To Reproduce

See above explanation

### Environment

```markdown
OS: Ubuntu 20.04.5 LTS
Sonarr: Sonarr 3.0.9.1549
Package Version: 3.0.9.1549-ls172 by linuxserver.io
Mono Version: 6.12.0.182
Docker Install: Yes
Using Reverse Proxy: No
Browser: Chrome Version 108.0.5359.125 (Official Build) (64-bit)
```

### What branch are you running?

Main

### Trace Logs?

[Trace-Logs](https://gist.github.com/KingIzzymon/6aa0b32f3ae87cb53bb750b8420eec0a/raw/4ebe9a897d84f13e0d8ba9064593f328ce451c2d/trace-logs)

**Comment by markus101** [comment]
Your trace logs logs don't show anything related to this. Please update them to include the related log message to that error so we can see what the issue is.

**Comment by KingIzzymon** [comment]
@markus101 I've been trying to find the exact match for "Episode file already imported at 1/12/2023 4:36:50 PM" and hadn't found it.

I was hoping my screenshot showing my computer's date/time including the error bubble message would be enough to cross compare with the trace I found for that episode to show that the error bubble message is using the wrong timezone.

If that's not enough info, then we can just close out this bug. Its super minor but thought it might be worth mentioning.

**Comment by bakerboy448** [comment]
Is your pc's timezone UTC-5 and it's displaying the value as UTC?

**Comment by KingIzzymon** [comment]
@bakerboy448 yes and yes, but that doesn't matter because of the discrepancy between the bubble and the logs I uploaded.

**Comment by bakerboy448** [comment]
`1/12/2023 4:36:50 PM UTC` is the same time as the logs `2023-01-12 11:36:50.5 [UTC-5]` - so seems like the UI is either A) converting it to UTC to be displayed erroneously or B) not converting it from UTC to be displayed in local time. depending on the timezone of the event stored in the database.

Seems just a UI issue then - and likely applicable to all imports.

**Comment by KingIzzymon** [comment]
@bakerboy448 well now im embarrassed. =')

**Comment by bakerboy448** [comment]
A bug is still a bug :)

**Comment by KingIzzymon** [comment]
I appreciate you!

**Comment by markus101** [comment]
I was trying to verify that the time in the logs was correct, but the logs you provided to show that didn't actually show that, thus asking for the correct logs to be included.

The time in the screenshot is helpful though.

> Seems just a UI issue then - and likely applicable to all imports.
The UI is completely unaware of the time in this case. Not sure what you mean about it applying to all imports, this is specifically about this error message.
