### ISSUE TITLE
Add `Series TitleWithoutYear` Renaming token

### ISSUE THREAD

**Issue by ColinHebert** [Sonarr/Sonarr#5369]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently when working with serie titles, some pre-embed the year, while others do not. This inconsistency in behaviour makes it difficult to customise the naming pattern.

For example the series Kingdom has the following title: "Kingdom (2019)", the different options for the title are:
`{Series Title}` -> Kingdom (2019)
`{Series CleanTitle}` -> Kingdom 2019
`{Series TitleYear}` -> Kingdom (2019)
`{Series CleanTitleYear}` -> Kingdom 2019

If I want to have a `CleanTitle`, while retaining parenthesis around the year "Kingdom (2019)", my options are to do `{Series CleanTitle} ({Series Year})` which would give me "Kingdom 2019 (2019)", or `{Series CleanTitleYear}` which would give me "Kingdom 2019".

No option really fits the needs.

### Describe the solution you'd like

Introduce `VanillaTitle` (and it's `CleanVanillaTitle` equivalent) which is the vanilla name of the series (ie. without the year) allowing to customise how the title and year are displayed.

### Describe alternatives you've considered

An alternative which would break backward compatibility is having `Title` and `CleanTitle` being the vanilla title.

### Anything else?

The introduction of "VanillaTitle" would remove the need for `TitleYear`, `TitleTheYear`, and any *Year equivalent, as the year can be managed entirely by the user however they want.

That said, the way `TitleYear` works currently assumes that [any 4 digits number specified in parenthesis in the title is a year](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L364-L368), and that it should be used as "the Year" for the series, taking precedence over `series.Year`.
Unfortunately the `{Series Year}` field only uses the `series.Year` entry and does not attempt to extract the year from the title.

An argument could be made for the sake of consistency for entries such as `Year`, `TitleYear`, and `CleanTitleYear` to either:
- Always have the year being `series.Year`
- Always have the year being the one specified in the non-vanilla series title, then fallback on `series.Year`

**Comment by markus101** [comment]
`Series VanillaTitle` is too generic, `Series TitleWithoutYear` is 4 characters longer and makes it abundantly clear what it's doing and it's not as though you need to type it often.

**Comment by markus101** [comment]
The number of series where year in the title is not the same as the year is going to be pretty low, but changing the established pattern is going to break things. Leaving it as-is and adding the option to add the year to a title without year covers it without breaking things.
