### ISSUE TITLE
Add media info to file deleted discord connect

### ISSUE THREAD

**Issue by i-am-at0m** [Sonarr/Sonarr#5372]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently when a file is deleted (either found by scan or due to upgrade), the discord connect message just says what episode and that it was deleted, but not what the filename was. The upgraded notification does have the filename and metadata. I can't tell by looking at the discord messages if it just replaced a file I wanted to keep (and should go unwatch)

### Describe the solution you'd like

Display (minimum) filename deleted for deleted messages on discord connect. Could include all metadata like all the other ones do too, don't really care. 

### Describe alternatives you've considered

Another option would be for the upgrade connect to list both filenames. 

Could probably get this to work differently using Notifiarr but I prefer a self-hosted solution (except for the discord server obv).

### Anything else?

![Screenshot_20230114-093552](https://user-images.githubusercontent.com/989019/212477211-5b1e037c-c847-4a2d-a944-051ff2887696.png)
This is what the notification looks like now. There's a grab, a delete, and then an upgrade message. The deleted message doesn't have a card or any info with it other than the series name and episode number.

**Comment by jack-mil** [comment]
May take a look at this in the coming weeks
