### ISSUE TITLE
Notifications should include instance name

### ISSUE THREAD

**Issue by yegle** [Sonarr/Sonarr#5378]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'm currently using Telegram to receive notification from Sonarr/Radarr/Prowlarr. Many of the notifications are in ~similar format without an easy way to distinguish them.

E.g. when there's a new update, the message will look like this:

```
Health Check Failure
New update is available
```

Or when there's an index failure:

```
Health Check Failure
Indexers unavailable due to failures: Foo, Bar
```

When any of this happen, I would have to go through all the *arr instances to find which one is the culprit.

I'd imaging this is also an issue if you are running multiple Sonarr instances.

### Describe the solution you'd like

Under Settings -> General, there's a "Instance Name" field to distinguish each Sonarr instances. We should use this field when sending notifications.

I.e. if "Instance name" is set to "MyAwesomeSonarrInstance", I'd like to receive an notificaiton like this:

```
[MyAwesomeSonarrInstance] Health Check Failure
New update is available
```

### Describe alternatives you've considered

If we can't do this by default, an alternative would be a per-notification setting to prepend the instance name.

E.g. in the Connection - Telegram setting page, I should have a checkbox to "Include instance name in the notification".

### Anything else?

Is there a way to upstream this change to other *arr projects? Do I need to file a bug to each of them?

**Comment by markus101** [comment]
This falls under https://github.com/Sonarr/Sonarr/issues/328
