### ISSUE TITLE
A popular use case that isn't accounted for currently (I don't think)

### ISSUE THREAD

**Issue by quadcom** [Sonarr/Sonarr#5381]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

_First, I tried to search the list of enhancements but couldn't figure out what to search for effectively._

This was spawned from my discussion on the forum  - https://forums.sonarr.tv/t/getting-seedbox-and-local-sonarr-working-together/31360

I, like many others, use an externally hosted seedbox for our torrent clients. But our library is at our home. Two different networks. I've tried to work out how to get Sonarr to recognize files that are synced from the seedbox to my home but to no avail. It was suggested that this could work, but the sync process needs to be real-time as the files are downloading. That seems like a nightmare for file corruption.

I have tried using Syncthing and Resilio, but both of those approaches are as slow as molasses for transfers. I use an open-source app called Seedsync. That app uses LFTP with multiple threads at once. On my 3gb/s connection, I see +90MB/s transfers. It also works a bit differently in that it will only sync the directory it is looking at. Sonarr needs to have all its sources in a designated folder. This folder would sit inside the sync folder. Seedsync doesn't handle this well. Once that folder is synced, it's pretty much ignored after that. 

That got me thinking about a change to how Sonarr works. It's a long shot, I know. But it's worth bringing attention to as it could potentially help everyone with the same workflow as me.

Sonarr AFAIK relies on labels and DIR structure to keep track of what it is working on. This is pretty simple to break and forces you to make exceptions to how the download client handles other torrents (in my case, rtorrent). As an example, Auto-move. It is stated to disable the auto-move functions so that Sonarr and Radarr can handle the move/rename task. This will stop any other torrents that are added manually, i.e. I DL the latest Ubuntu server ISO. That DL won't get transferred to my home automatically.

### Describe the solution you'd like

The possible solution is a significant change to how Sonarr manages DLs. 

Manage the list of seeds downloaded in a DB rather than via labels or directory structures. 

Sonarr knows what seeds it has added to the client. It knows where they are being downloaded to and where they need to be when the download is done. 

The remote mapping feature was a great idea and is helpful to tell Sonarr that it is currently running in a 'remote mode.' Using the DB data, it should be able to identify the files on the remote server and the files on the local server and process the local files accordingly. 

This approach will also allow people to use the Media Management functions to their full potential, as the locally hosted instance on Sonarr will have direct access to the local library. It knows where to rename and move the synced files and can see which episodes are missing in the local library. A remotely hosted Sonarr can't do this. It can only monitor a library that is stored on the remote host -which, yes, some people run Plex on their seedbox; I understand that. But keeping the library on the seedbox can either get expensive due to storage requirements or dictate a very small library that is often scrubbed clean, leaving no actual library to manage after all.

### Describe alternatives you've considered

I've considered keeping Sonarr on the seedbox and finding a solution to have rtorrent's auto-tools ignore anything Sonarr, and Radarr do. This has not been easy, and I don't think I have found a solution as yet.

The only alternative, AFAIK, at the moment is to use only a fraction of what Sonarr can do, which is how I have been using it so far. 

I use it to push a new episode to DL. After that and after the sync to my local storage happens, everything is a manual operation. I run Filebot on the DL's and manually move them onto the local library. Then tell Kodi to refresh the DB.

### Anything else?

The last thing I want is to come across as complaining or ungrateful. Sonarr, Radarr and all the other open-source apps I use are absolutely amazing. I am so grateful for all the hard work people put into tools that help everyone and are doing it either for free or at a very reasonable cost.

I would love to help out if I was able but the last bit of coding I taught myself was Coldfusion back in the Macromedia days. I'm pretty much a noob to things NIX but I'm trying.

Thanks again, everyone!

**Comment by thezak48** [comment]
That is an interesting idea and defo something to think about, we personally recommend to use qbit as your downloader as it works far better with automation tools

**Comment by quadcom** [comment]
Hey @thezak48, thanks for jumping in.

Perhaps a simplification approach that might make it into production. What if Sonarr had a watch folder function where we could tell Sonarr a folder to watch for files -in my case, the local sync folder? If it finds a show that it knows it is tracking, process it accordingly. Rename and move to the media management folder.

That would work and might be a simpler approach.

**Comment by fryfrog** [comment]
Hey @quadcom, I'd hop on Discord and jibber jabber there w/ folks about how to get your seedbox setup working good. This is a solved problem for years w/ a few good ways to do it.

I'm still trying to really grok your idea and what it is trying to solve, but there are some pretty big holes in it that I think make it more difficult than you think. For example, not all torrents have files directly... there are many that are packed in `.rar` files, so right there you've lost some big percentage of torrents. And Sonarr/Radarr also both support usenet, which *also* doesn't list individual files. They're literally all packed and/or obfuscated, so it wouldn't work there either.

Your folder monitoring idea is already there too, its the blackhole usenet and torrent client.

You say your LFTP based sync is fast, do you know what protocol it is using? From there, I'd look for "remote mount <that protocol>".

**Comment by markus101** [comment]
> It was suggested that this could work, but the sync process needs to be real-time as the files are downloading. That seems like a nightmare for file corruption.

No, this isn't the case at all. Sonarr needs to see the complete files all at once. When your download client says that the files are downloaded if Sonarr only sees a partial file then you're going to get a partial file imported. Usually this is done by syncing from the seed box to a location that Sonarr isn't monitoring then moving the files after they're all synced, but as Fryfrog chimed in with, this is a solved problem.

> Sonarr AFAIK relies on labels and DIR structure to keep track of what it is working on. This is pretty simple to break and forces you to make exceptions to how the download client handles other torrents (in my case, rtorrent).

Labels for most clients, the directory structure is just for Transmission or other clients that don't have a real concept of categories/labels. If you're using a client with real categories then the path doesn't matter and if it changes after downloading that is fine too. The reason you don't want to use auto movers is because people configure them to move the files to the series folder and that makes a mess.

> This will stop any other torrents that are added manually, i.e. I DL the latest Ubuntu server ISO. That DL won't get transferred to my home automatically.

Not sure what you mean, if you add it to the same category/label then Sonarr will know about it, if you don't then it won't. The benefit of using categories is Sonarr doesn't need to watch everything in your client and can also track things it didn't add.

https://github.com/Sonarr/Sonarr/issues/282 is probably the closest thing to this, but it has no short term plans to be implemented because it's a lot of work to do it and to handle a wide variety of setups is complicated.

Closing this out as we don't have plans to change the interaction with download clients and there a working solutions for working with seed boxes, which require some setup for a smooth experience, but are pretty well established.

**Comment by quadcom** [comment]
hey @fryfrog 

"You say your LFTP based sync is fast, do you know what protocol it is using? From there, I'd look for "remote mount (that protocol)"."

LFTP uses SFTP.
