### ISSUE TITLE
Non ASCII characters and alternate titles

### ISSUE THREAD

**Issue by bphd** [Sonarr/Sonarr#5382]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The non ability to get what really exist in term of release

### Describe the solution you'd like

I have a serie that I want to watch that is distributed in many languages, so its known by many names: alternate titles. TheTVDB list some of them, but not all. I want to know if SonArr/ProwlArr take into account those alternate titles to search the corresponding files? I want to know too if we can add manually in our SonArr/ProwlArr instance some more alternative titles? Because TheTVDB does not list them all

It's all the same serie in final, it's just that some group may release it without the name that SonArr know, and some with the name he know, and sometimes better quality are released without the known names, hence my interrogation

About ASCII character, it's about the same concern, many of those alternate title use non ASCII characters. If Son/Prowl don't use them to search, they will find nothing or near nothing. I want to know if these characters are supported and effectively used in searches?

### Describe alternatives you've considered

I can't do much because releasers will not use ASCII just for me. It's maybe better to adapt ServArr to the world than the contrary

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

TVDb aliases are not used at all.
https://wiki.servarr.com/sonarr/faq#why-cant-sonarr-import-episode-files-for-series-x-why-cant-sonarr-find-releases-for-series-x

**Comment by bphd** [comment]
How to set additional keyword for a particular serie in SonArr?
