### ISSUE TITLE
Indexer options for notifications

### ISSUE THREAD

**Issue by herkalurk** [Sonarr/Sonarr#5392]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Not a problem

### Describe the solution you'd like

In the fields for notification on grab and import I'd like the option to have the name of the indexer used when sending message.

### Describe alternatives you've considered

I haven't considered other alternatives other than looking through the logs/history.

**Comment by markus101** [comment]
That'd be something for https://github.com/Sonarr/Sonarr/issues/328
