### ISSUE TITLE
Upgrade by preffered word score

### ISSUE THREAD

**Issue by BugFinder2000** [Sonarr/Sonarr#5394]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I want a automatic upgrade by the preffered word score because it works very good in my case and i want the best entry that it can find and when it find a better entry it should upgrade.

![image](https://user-images.githubusercontent.com/52979239/214963926-a38c2574-a0d3-4eb8-854b-865ae2b1e765.png)

### Describe the solution you'd like

Automatic upgrade for preffered word score like for quality or language.

### Describe alternatives you've considered

currently none for that

### Anything else?

This feature for preffered words:
![image](https://user-images.githubusercontent.com/52979239/214964176-c3159089-3e67-4984-bd0e-1e886d8902f4.png)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Preferred words are always an upgrade (assuming the same quality), preferred words are being replaced with Custom Formats in v4 though.
