### ISSUE TITLE
Searching for episodes of anime genre, the episode search is not comprehensive enough

### ISSUE THREAD

**Issue by ZIZNAH** [Sonarr/Sonarr#5395]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I tried to search the anime My Hero Academia for the specified season and ep, but the search is missing badly. I opened the debug and found that the search keywords are searched according to the season and the number of episodes of the whole anime, resulting in missing content. I think when I specify the number of episodes, he should search for the content of season + the number of episodes of the current season.
![image](https://user-images.githubusercontent.com/47733889/215095069-e7d7698d-8c2a-4709-a42f-92f1ea138e08.png)
![image](https://user-images.githubusercontent.com/47733889/215095155-6e4f0e93-1beb-4d3e-99f8-a55688d4c609.png)

### Describe the solution you'd like

Add a keyword for the search: current season + number of episodes of the current season

### Describe alternatives you've considered

I have tried many ways, either add an "intermediary" between sonarr and indexers and change the search keywords myself before sending. Either that or give up using anime in sonarr altogether.

**Comment by ZIZNAH** [comment]
I tried to switch the type to Standard, because I saw in the issue that someone said Standard used this way, but after I switched, the search attempt had fewer keywords. And the format used is Season{number}E{ep}, I think I can try to add a search format S{number}+E{ep}.
And after using Standard type, the search keyword tries less types, you can see the comparison of the search in the upper and lower debug chart.
![image](https://user-images.githubusercontent.com/47733889/215096966-a14bd473-49cc-4b2a-aad7-6b98ffe2f6cf.png)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Sonarr uses aliases and mappings from https://thexem.info/ when searching anime. The aliases and mappings are based on common (and non-conflicting naming), if your particular indexer doesn’t follow that then things won’t line up and searching will fall short.
