### ISSUE TITLE
Sonarr v4 ping/health endpoint

### ISSUE THREAD

**Issue by modem7** [Sonarr/Sonarr#5396]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, in v3, we are able to use the `/ping` endpoint unauthenticated. 

This is quite useful for external monitoring tools such as Upptime and Uptimekuma where Sonarr may be behind an additional authentication system such as Authelia. 

This also applies to the `/api/v3/health` endpoint.

### Describe the solution you'd like

Requesting `/ping` and/or `/api/v3/health` endpoint to remain unauthenticated.

### Anything else?

Having an unauthenticated endpoint for an `OK` or `200` code would be exceedingly useful for a variety of services including Docker, Kubernetes and external (or indeed self hosted) monitoring solutions.

**Comment by Thirrian** [comment]
https://github.com/Sonarr/Sonarr/issues?q=is%3Aissue+is%3Aclosed+ping

https://github.com/Sonarr/Sonarr/commit/75fc550a3fb44e528ca3c311e83075f79f987a36

**Comment by Thirrian** [comment]
Is that not still available in v4?

**Comment by modem7** [comment]
> Is that not still available in v4?

The endpoints are, but they are behind authentication now.

https://sonarr.tv/docs/api/#/Ping and https://sonarr.tv/docs/api/#/Health respectively. 

I tested this yesterday on V4 and got a 401 message.

**Comment by KyleSanderson** [comment]
> Is that not still available in v4?

Just hit this myself. Looks like the the last time the controller was touched was in August last year in mega commits...

**Comment by KyleSanderson** [comment]
> Looking here (and I may be misunderstanding or misreading): https://sonarr.tv/docs/api/, is every endpoint under authentication? (I know the vast majority would be for the obvious reasons, but everything listed there has the "Available authorizations" padlock.)

It's not relevant unfortunately, this is a major (not documented) behaviour change.

**Comment by Qstick** [comment]
> It's not relevant unfortunately, this is a major (not documented) behaviour change.

Well technically, it is documented now in the API docs (the lock icon on the endpoint), and while it's a major change, it's behind a major version bump to suit.

**Comment by KyleSanderson** [comment]
> > It's not relevant unfortunately, this is a major (not documented) behaviour change.
> 
> Well technically, it is documented now in the API docs (the lock icon on the endpoint), and while it's a major change, it's behind a major version bump to suit.

Got it - is there a replacement for this? it's pretty brutal not having it. My install was papered over before which made https://github.com/Sonarr/Sonarr/issues/5402 less visible (by racing the timer). Had to recover from backup...

**Comment by markus101** [comment]
The `/ping` route should be unauthenticated, it's purpose is to verify whether Sonarr is up or not. While the change was intentional, a different approach should likely have been taken.
