### ISSUE TITLE
v4: custom formats mangled

### ISSUE THREAD

**Issue by KyleSanderson** [Sonarr/Sonarr#5399]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Upgrade to 4.0, all regex have trailing /.

### Expected Behavior

regex actually works.

### Steps To Reproduce

Upgrade to 4.0

### Environment

```markdown
- OS: linux
- Sonarr: v4-4.0.0.362
- Docker Install: y
```

### What branch are you running?

Develop

### Trace Logs?

.

**Comment by markus101** [comment]
Next time please include the original regex that didn't convert properly.
