### ISSUE TITLE
Add "dumb" HTTP fetch for recurring actions

### ISSUE THREAD

**Issue by kiler129** [Sonarr/Sonarr#5404]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This is a FR. The simplest way to monitor recurring jobs is to use so-called deadman switch. In short the application is supposed to periodically access a URL to prevent the monitoring system from marking it as malfunctioning.

### Describe the solution you'd like

Sonarr contains various periodic actions:

- Lists update
- Download clients queue update
- Update indexers RSS
- Various system tasks

The first 3 support various endpoints utilizing HTTP(S). However, since every single one of them contains subtypes which are verified upon save, it is not possible to add e.g. a fake indexer which is just a ping to a monitoring system. The simplest and probably quite easy solution would be to add a "Dummy HTTP" type to each one of them which simply requests a URL and returns nothing.

### Describe alternatives you've considered

An alternative to a deadman switch/push system is using a pull-based system. In such scenarios the monitoring system will connect to the application externally and verify if it's alive. However, this has a significant drawback: it usually requires the instance to be exposed to the internet.

### Anything else?

Issue was cross-posted to Radarr as well: https://github.com/Radarr/Radarr/issues/8048

**Comment by markus101** [comment]
That is the purpose of the `/ping` endpoint, though as you describe it it's a "pull" based system. We don't have plans to add a "push" based one.
