### ISSUE TITLE
Can we get a dark mode please? Same as radarr

### ISSUE THREAD

**Issue by KaranTrivedi** [Sonarr/Sonarr#5405]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Can we get a dark mode please? Same as radarr

### Describe the solution you'd like

Can we get a dark mode please? Same as radarr

### Describe alternatives you've considered

?

**Comment by markus101** [comment]
It's in the v4 beta already. https://www.reddit.com/r/sonarr/comments/z3nb82/sonarr_v4_beta/
