### ISSUE TITLE
Sonarr wont delete completed torrent from download client (rtorrent and qbittorrent)

### ISSUE THREAD

**Issue by wioo** [Sonarr/Sonarr#5407]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

This is totaly random behaviour. When torrent is finished (in rtorrent) it wont be deleted. Some torrents are and others are not.

From trace log I can see xmlrpc request and response is completed with success. It wont exexcute next steps, parse file names etc...

The same happens with qbittorrent but rarely.

### Expected Behavior

Delete finished torrents when "Refresh Monitored Downloads" task is run.

### Steps To Reproduce

Add new downloads to rtorrent (with rss, manual, search for monitored episodes...) and wait for download client set torrents to finished status.

### Environment

```markdown
- OS: Arch linux
- Sonarr:4.0.0.363
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Qutebrowser
```

### What branch are you running?

Develop

### Trace Logs?

https://gist.github.com/wioo/4e5cb5c0951650a195730992f419b97c

### Anything else?

It also happens with v3.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Removing torrents from rTorrent is pretty limited as described within the settings for rTorrent (it's not based on being in a finished state). For qbit the response indicated there are no torrents for Sonarr to process in the `tv-sonarr` category, which may mean you're using `Post-Import Category` which is incompatible with with removing torrents as described.

**Comment by wioo** [comment]
Yeah, qbit is just there because its enabled in settings. It does not have any torrents. Ok, so rtorrent  isnt optimal client for sonarr. Thanks.

**Comment by wioo** [comment]
I must say, downloading with rtorrent is not just pretty limited but its totally broken. Its like playing lottery. 
My advice to anyone reading this is just dont use it.
