### ISSUE TITLE
Option for Activity entry when new files detected

### ISSUE THREAD

**Issue by bugmancx** [Sonarr/Sonarr#5409]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The 'History' page doesn't track events for when an episode was added from outside of Sonarr but was imported into the database.

### Describe the solution you'd like

Whenever Sonarr scans a show directory and discovers/imports a new file for an episode that was put there from outside of Sonarr, it should include an entry in the History (similar to how it does for if a file is deleted outside of Sonarr.) This would be helpful in spotting where an episode file has been added to your collection from outside of Sonarr, and Sonarr has detected ad imported it.

### Describe alternatives you've considered

There are none.

**Comment by markus101** [comment]
This is intentional, we don't have plans to add history events for files already in the series folder.

**Comment by bugmancx** [comment]
I would just note that you already have precedent for this for when files are detected as deleted - this appears as a "history event".

**Comment by markus101** [comment]
Files being removed is a destructive event, which will occur automatically by Sonarr and allows better tracking of an import (as well as being able to display information as to why it was removed).

Tracking file imports adds a lot of unnecessary noise when existing series are imported and Sonarr adds all the files and while we could likely exclude those initial imports Sonarr would inconsistently store those events whereas it’s easier and more consistent to say we just don’t track files imported from the series folder.

If you want import events for files then Sonarr will need to import the file from outside the series folder (which is our recommendation regardless).
