### ISSUE TITLE
Allow customization of CleanTitle

### ISSUE THREAD

**Issue by dnnr** [Sonarr/Sonarr#541]
Currently, the behavior of .CleanTitle in the episode format strings doesn't seem to be clearly specified. From what I could tell, *some* special characters are removed or substituted, while some, such as diacritics, are not. I haven't looked at the actual implementation though.

So I'd like to suggest that:

1. The default behavior of CleanTitle should be explained somewhere, and probably be implemented as a whitelist rather than a blacklist, which is bound to be either very long or always incomplete.

2. Its behavior should be customizable in order to accommodate the users' varying needs. For instance, some users might prefer their episode titles to be without apostrophes, while others might not.

**Comment by markus101** [comment]
It replaces `&` with `and` and removes some characters and replaces others:

https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L59-L60

I believe diacritics should be removed, but currently are not.

1. Originally we whitelisted, but it became more of a pain than blacklisting.
2. Definitely not going to make it customized, the effort isn't worth the reward.

Opened a new issue for removing the diacritics: https://github.com/Sonarr/Sonarr/issues/542
