### ISSUE TITLE
Make use of download client's "category" for manual downloads

### ISSUE THREAD

**Issue by DorCoMaNdO** [Sonarr/Sonarr#5413]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When finding a download for an episode outside of Sonarr it often needs to be manually imported, because even when using the same download clients, with the "category" assigned to Sonarr downloads, they do not appear as active downloads in Sonarr and do not attempt to automatically import when complete as a result.
This is a problem because some series with many releases (or with search terms that pick up unrelated releases or episodes with the same digits, affects anime series the most) take really long to load a search for, and I find that automatic search often fails, usually because it fails to recognize batches correctly, sometimes seeing "season X part 1" as "season X episode 1", or thinking a batch for a "part" of a season is for the entirety of it, so multiple scans need to be initiated, so it often tends to be just easier to find the proper links externally, but that means giving up automatic import too.

### Describe the solution you'd like

Fetch all downloads labeled with the category assigned to Sonarr downloads, even those that were not initiated through Sonarr. Alternatively, allow manual use of download links (either direct torrent/sab or details page for supported providers) so that Sonarr could initiate the download with the download clients (this would also allow fetching more information regarding the release).

### Describe alternatives you've considered

Manual import.

### Anything else?

This is more of a ramble about the shortcomings of Sonarr with anime, but it provides some context for the use case of the above feature.

This is more of an issue as I recently got into more anime series, I typically watch them dubbed so the selection of releases is much smaller, this is the release profile I'm using for dub-tagged anime:
![image](https://user-images.githubusercontent.com/5393267/216809544-2824ad2b-d01c-4e80-9992-75f891faae79.png)
(regex to prevent a release from earning score multiple times for certain keywords)
I have some other release profiles for more generalized content but the only one that matters is a +100 score for releases containing HEVC/x265/h265.
With indexers for AnimeTosho (torrents and usenet), Nyaa.si and NZBGeek, automatic search after adding `Boruto: Naruto Next Generations` grabbed the following:
![image](https://user-images.githubusercontent.com/5393267/216809769-a3b3379b-7321-416c-a3ec-aa004fa5c158.png)
Further uses of "automatic search" and multiple days of waiting for it to automatically search for missing yielded no new downloads.
I've had a similar issue with `Spy x Family`'s first automatic search, as it grabbed a "season 1 part 1" release and stopped looking for additional episodes, I had to use manual search for all the then-current episodes (which took forever, also lead me to learn about Cloudflare's connection timeout), it did however download new dub releases as they came out.
`Demon Slayer` was another problematic one due to metadata, Season 1 and 2 grabbed just fine, Season 3 not so much, officially Demon Slayer has only 2 seasons, released in two parts, in Sonarr however they're split as Season 2 and Season 3, virtually all releases are named Season 2 part 1 (Sonarr's Season 2) and Season 2 part 2 (Sonarr's Season 3), so once again I had to manually grab the "part 2" release.

**Comment by markus101** [comment]
> Fetch all downloads labeled with the category assigned to Sonarr downloads

Sonarr already does this, provided it can parse the name in the download client. If it can't it will still show it in Activity: Queue, but it will need to be manually imported.
