### ISSUE TITLE
Search alternate titles when performing a manual import

### ISSUE THREAD

**Issue by Tuckie** [Sonarr/Sonarr#5417]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When importing an anime with a Japanese title, Sonarr can properly identify the show, however it cannot find any of the episodes within that are named the same exact way. 

### Describe the solution you'd like

It would be great if Sonaar could search on all naming variations (via XEM) for a show to improve the import process.

### Describe alternatives you've considered

The only alternative is to rename most files within my collection as they almost always use the Japanese title.

**Comment by markus101** [comment]
Sonarr should already be doing that, please provide more information (ideally with trace logs) where it’s not doing that.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

I've confirmed it's working as it should:
![image](https://user-images.githubusercontent.com/413544/217403910-a47195aa-b500-421e-96a5-2f3cc96bae89.png)

`Star Wars Andor` is an alias for `Andor`
