### ISSUE TITLE
Incorrect `Post-Import Category` used when there are multiple instances of the same download client

### ISSUE THREAD

**Issue by glitch452** [Sonarr/Sonarr#5422]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

General Description: 
When an indexer is configured to use a specific download client (note: there are multiple instances of the same download client), and the download client is configured to set a `Post-Import Category`, then the `Post-Import Category` is being set using the incorrect download client configuration.  It seems to be selecting the `Post-Import Category` from the first instance of the download client that was created. 

Specific Description: (see `Steps to Reproduce` for background information)
When downloads are completed, torrents started with `Indexer B` are being labeled in Deluge with `label-a`. 

I presume this is happening because Sonarr finds the first match for a download client with specific details and then uses the `Post-Import Category` from that, rather than looking up the download client that was used by the indexer that started the download.

### Expected Behavior

General Description: 
When an indexer is configured to use a specific download client (note: there are multiple instances of the same download client), and the download client is configured to set a `Post-Import Category`, then the `Post-Import Category` would be set using the label configured in the download client that the indexer was configured to use. 

Specific Description: (see `Steps to Reproduce` for background information)
When downloads are completed, torrents started with `Indexer B` should be labeled in Deluge with `label-b`

### Steps To Reproduce

What I am trying to accomplish: using Sonarr tags to set a label in Deluge when the torrent is imported. 

Configuration details:
- Let's say we have Sonarr tags `A` and `B` and various series tagged by them (a given series would only be tagged with `A` or `B`, but not both at the same time)
- We have indexers we'll call `Indexer A` and `Indexer B`, which are tagged with tags `A` and `B` respectively
- We have download clients we'll call `Deluge A` and `Deluge B` which point to the same deluge instance. 
- `Indexer A` is configured to only use `Deluge A` as it's download client
- `Indexer B` is configured to only use `Deluge B` as it's download client
- `Deluge A` has its `Category` set to `sonarr` and its `Post-Import Category` set to `label-a`
- `Deluge B` has its `Category` set to `sonarr` and its `Post-Import Category` set to `label-b`

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS 
- Sonarr: 3.0.9.1549-ls174 by linuxserver.io
- Docker Install: Yes (linuxserver/sonarr)
- Using Reverse Proxy: Yes (Traefik)
- Browser: Safari 16.3 / Chrome 109.0.5414.119
```

### What branch are you running?

Main

### Trace Logs?

None at this time. I can turn on trace logging and try to capture this in action if needed, please let me know.

**Comment by markus101** [comment]
> Deluge A has its Category set to sonarr and its Post-Import Category set to label-a
Deluge B has its Category set to sonarr and its Post-Import Category set to label-b

Use separate labels, Sonarr will attribute the download to the client that it pulls it from, not necessarily the one it sent it to, using the same category you're just confusing Sonarr and making everything attributed to whichever "download client" saw it first.

**Comment by glitch452** [comment]
Hmm, so you mean like this?
- `Deluge A` has its Category set to `sonarr-a` and its Post-Import Category set to `label-a`
- `Deluge B` has its Category set to `sonarr-b` and its Post-Import Category set to `label-b`

**Comment by markus101** [comment]
Yeah, exactly, full separation.
