### ISSUE TITLE
Better HTTP Error Messaging

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#5423]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently when connections time out or if users have dns / ipv6 issuers they receive non-intuitive exception messages.

### Describe the solution you'd like

catch HttpRequestException and TaskCanceledException with better validation messaging as applicable and logging for http requests app wide as applicable and improve ease of use troubleshooting 

### Describe alternatives you've considered

N/a

### Anything else?

some work done in prowlarr around indexer handling https://github.com/Prowlarr/Prowlarr/commit/f8082047a56adc74762f35d1e1e717417271a529

**Comment by markus101** [comment]
If you have specific examples where we could log better messages we can look into them, but  as is this request is too broad to be meaningful.

**Comment by markus101** [comment]
Closing until we have something definitive to implement.
