### ISSUE TITLE
Multiple instances running

### ISSUE THREAD

**Issue by blimeybloke** [Sonarr/Sonarr#5424]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Every few days, I look at the taskbar and there are multiple icons for sonarr.  When I mouse over them, they do disappear and only 1 remains, but this is still odd.

Here is a screenshot:
![SCR-20230210-de6](https://user-images.githubusercontent.com/20652035/218119398-1988ef9f-52d1-40f1-aeae-1030483a482f.png)

### Expected Behavior

not have multiple icons? lol

### Environment

```markdown
- OS: windows
- Sonarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

n/a

**Comment by markus101** [comment]
This is a limitation in how Windows functions, I looked into it years ago, but not going to investigate more effort into finding a solution for their issue.

**Comment by blimeybloke** [comment]
ok, thanks, just was curious.
