### ISSUE TITLE
Preferred and Blacklisted Release Groups for individual qualties

### ISSUE THREAD

**Issue by camjac251** [Sonarr/Sonarr#543]
I have noticed that DIMENSION with their 1080p releases are near bluray quality with a lot of shows, but BATV and IMMERSE also upload 1080p sometimes along side of DIMENSION and their quality isn't great at all, is it possible to setup a whitelist/blacklist sort of deal? To where on a certain profile or quality, I can type in release groups and it would grab them in that order, and then blacklisted ones would be ignored completely?

**Comment by markus101** [comment]
Use release restrictions link to a tag and have that same tag linked to the series that you want to apply the restrictions to.
