### ISSUE TITLE
A fatal error in the mono runtime or one of the native libraries

### ISSUE THREAD

**Issue by murk00** [Sonarr/Sonarr#5434]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I cannot login to webui for unraid, any help here is appreciated.

### Expected Behavior

logs show A fatal error in the mono runtime or one of the native libraries.

### Environment

```markdown
- OS: unraid
- Sonarr: linuxserver/sonarr:latest
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: chrome
```

### What branch are you running?

Main

### Trace Logs?

![crash log](https://user-images.githubusercontent.com/78495827/219478648-1d30ae70-2cce-43eb-9970-4480a996edca.jpg)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by Roxedus** [comment]
https://docs.linuxserver.io/faq#jammy
