### ISSUE TITLE
sonarr downloading seasons of shows that I have not requested to download

### ISSUE THREAD

**Issue by mhmm555** [Sonarr/Sonarr#5436]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

sonarr is downloading seasons of shows that I have not requested to download, i have added these series to my series list but i have not clicked the "start search for missing episodes" and some of these series have been added since a long time ago but they only recently started downloading episodes on its own.

### Expected Behavior

sonarr not to download episodes on its own

### Environment

```markdown
- OS: ventura 13.2.1
- Sonarr: Version 3.0.9.1549
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

i do not currently have trace logs as i have just started recording the logs as trace but i will be upoloading them as soon as it happens again

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

If the episodes are monitored Sonarr will grab the, if it sees them on the RSS feed from your indexer, this is explained in the FAQ.
