### ISSUE TITLE
Notification when series ended

### ISSUE THREAD

**Issue by fana13** [Sonarr/Sonarr#5438]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

not a problem

### Describe the solution you'd like

It will be great if we have a link with UI info when a serie is definitly ended.
Have a push notification by pushover or discord for example.
I've seen an old issue (7 years ago) but i think that UI info wasn't be implemented yet at this moment.

### Describe alternatives you've considered

not need

**Comment by markus101** [comment]
> not a problem

Then why would such a feature be useful for your work flow?

**Comment by fana13** [comment]
It's not a problem, just an enhancement.
Have this information is not primary but it will be a very cool possibility

**Comment by markus101** [comment]
I understand, but there is still a reason for adding it, which is the “problem” you’re trying to solve otherwise there is no reason to add it. What benefit would adding this give beyond “I’d get a notification”, why is that notification important?

Right now you’ve provided a solution, but we don’t understand what problem the solution is meant to solve, which is important because if we don’t understand why we’re adding something there is the risk of doing the wrong thing because we were presented with the first solution the requester thought of.

If you received this notification what would you do?


When would the notification be sent? After all the files in the season are imported? After the episode airs? The day it airs?

**Comment by fana13** [comment]
The problem is that i never know when a serie is stopped or ending. Sonarr find this and put an ended flag in UI. For me it's important to know this at least i'm not expected new season.

**Comment by bakerboy448** [comment]
> For me it's important to know this at least i'm not expected new season.

Why?

**Comment by fana13** [comment]
To not expect a season. It's the point

**Comment by markus101** [comment]
Your title and reply conflict, do you want to know when the whole series ends or when an individual season within the series ends?

What about series that get cancelled (and marked as ended) then get picked up by another network/streaming service? They’d then no longer be ended, but you’d have been sent a notification that it was ended.

Plus all the same questions I asked when it was about a season ending that you didn’t reply to.

**Comment by fana13** [comment]
It's about when the whole serie ends. Ends because it's really the end or because that was cancelled, same point for me.
When sonarr marked as ended, notification will be sent at this moment, doesn't matter if files are imported or not

**Comment by bakerboy448** [comment]
So send a notification the moment a series is considered `ended`?

again, what actions are you expecting to take from this notification?

What about a series that is ended today, but picked up by one of the streaming services and now continuing next month?

**Comment by manubell** [comment]
Seems completely informational to me. I'd probably enable that as well. 🙂

Sonarr displays in the UI whether a show is ended or not. 
What is being asked here is; can you make that event publish a notification towards a notification channel of choice.

**Comment by fana13** [comment]
Yes that's only informational.
That's exactly that @manubell 

> What about a series that is ended today, but picked up by one of the streaming services and now continuing next month as Markus asked?

Why not a notification to indicate that finally the series continues, it was really perfect.

**Comment by markus101** [comment]
Likely not because that'd be prone to duplicate notifications, even notifying on series end is going to be pretty unreliable if the the data isn't stable, we'll need to think about whether it's worth the effort.

**Comment by fana13** [comment]
Ok thank you whatever happens

**Comment by markus101** [comment]
We've discussed further, but this isn't something we're going to implement support for at this time.
