### ISSUE TITLE
Add catalan language

### ISSUE THREAD

**Issue by elboletaire** [Sonarr/Sonarr#5440]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

There's no way to chose catalan as language, so I cannot properly manage catalan movies (radarr) and tv shows (sonarr) downloaded.

### Describe the solution you'd like

Add catalan language to language selectors

### Describe alternatives you've considered

Ignore me I guess

### Anything else?

Some useful release names having catalan defined as language in some way:

-  Dr. Slump - Arale. Cas, Cat, Jap. DVD 13 al 16 
-  Merlí. Sapere Aude S02 (2021) [WEB-DL 1080p Castellano DD 5.1 - Catalán DD 5.1 Subs] [HDOlimpo] 
-  Misfits S02 (2009–2013)[BDRemux 1080p AVC Esp.DD2.0,Ing.DD2.0,Cat.DD2.0,Subs][HD-Olimpo][PACK] 
-  Farscape S02 (1999–2003)[BDRemux 1080p AVC Esp DD2.0,Ing DTS-HD5.1,Cat DD2.0 Subs][HD-Olimpo][PACK] 
-  Merlí S01 [WEB-DL NF 1080p EAC3 2.0 esp cat Subs][HDOlimpo] 
-  Merlí Sapere Aude S02E08 M+ WEBDL 1080p SPA-CAT DD5.1 SUBS x264 
> ^ except for the first one (Dr. Slump), all the "subs" in here reffer to the simple fact that they contains subs, but do not specify in which languages
- Inuyasha Kanketsu-hen 01 [HEVC 1080p][ESP-ENG Subs][CAT-JAP-ENG Audio]-inuyashafull
> ^ this one specified subs and audio languages in different groups. Something exceptional I've never seen before tbh.

**Comment by bakerboy448** [comment]
Relevant recent radarr commit with many new languages added

https://github.com/Radarr/Radarr/commit/c6e91e028b93a7b9be0ebc0c34c11518768797c2

**Comment by markus101** [comment]
Please provide example release names.

**Comment by elboletaire** [comment]
> Relevant recent radarr commit with many new languages added
> 
> [Radarr/Radarr@c6e91e0](https://github.com/Radarr/Radarr/commit/c6e91e028b93a7b9be0ebc0c34c11518768797c2)
> 
>     * Catalan
> 
>     * Croatian
> 
>     * Serbian
> 
>     * Bosnian
> 
>     * Estonian
> 
>     * Tamil
> 
>     * Indonesian

Oh, awesome, thanks. I guess this issue could be closed then, although I understand those commits are for the (still unreleased as stable) version 4, right?.

> Please provide example release names.

Some like these will work? 

- ¿Qué hacemos con Maisie? (2012) [FullBluRay 1080p AVC ES-CAT-EN DTS-HD MA 5.1 Subs][HDO] iso 
- Pacto de silencio (2012) [Custom Fullbluray 1080p AVC ES DD+ 5.1 CAT DD 5.1 EN DTS-HD MA 5.1 Subs][HDO] iso 
- Millennium Actress (2001) [Full UHD 2160 HEVC ES-JAP DTS-HD MA 5.1 - CAT DD 2.0 Subs][HDO] 
- Paddington 2 (2017) [Custom U-HD 2160p HEVC HDR10 -DV (2017) ] [ES Dolby TrueHD 5.1 CAT - EUS DD Inglés Dolby Digital 5.1 Subs] iso 
- Harry Potter y las Reliquias de la Muerte - Parte 1 (2010) BDRemux 1080p ESP CAT 5.1 ENG DTS-HD MA 5.1 x264 - EML HDTeam 
- Harry Potter y la cámara secreta (2002) BDRemux 1080p ESP CAT DD EX 5.1 ENG TrueHD 5.1 VC-1 - EML HDTeam 
- La Isla de los recuerdos y el espejo mágico (2011) BDREMUX ESP CAT DD 5.1 VAL DD 2.0 ING JAP True-HD 5.1 SUBS -ALiEN 

Note I just searched for "cat" in some of my trackers and tried to get some random release names (not sure if this goes against my trackers rules btw... I hope not).

**Comment by markus101** [comment]
Those are for movies, for Sonarr we need TV release names because while similar that aren't going to be the same and we'll need to ensure we're not getting false positives, especially for `CAT`.

**Comment by elboletaire** [comment]
Oops, you're right, my fault. Unfrotunately, most of the tv shows I'm finding in catalan right now don't have a "proper" release name. Some of these trackers show flags instead of putting the language in the release name, but here are the ones I could find:

-  Dr. Slump - Arale. Cas, Cat, Jap. DVD 13 al 16 
-  Merlí. Sapere Aude S02 (2021) [WEB-DL 1080p Castellano DD 5.1 - Catalán DD 5.1 Subs] [HDOlimpo] 
-  Misfits S02 (2009–2013)[BDRemux 1080p AVC Esp.DD2.0,Ing.DD2.0,Cat.DD2.0,Subs][HD-Olimpo][PACK] 
-  Farscape S02 (1999–2003)[BDRemux 1080p AVC Esp DD2.0,Ing DTS-HD5.1,Cat DD2.0 Subs][HD-Olimpo][PACK] 
-  Merlí S01 [WEB-DL NF 1080p EAC3 2.0 esp cat Subs][HDOlimpo] 
-  Merlí Sapere Aude S02E08 M+ WEBDL 1080p SPA-CAT DD5.1 SUBS x264

**Comment by markus101** [comment]
> Farscape S02 (1999–2003)[BDRemux 1080p AVC Esp DD2.0,Ing DTS-HD5.1,Cat DD2.0 Subs][HD-Olimpo][PACK]
Merlí S01 [WEB-DL NF 1080p EAC3 2.0 esp cat Subs][HDOlimpo]

Are these different audio tracks or just Catalan subtitles?

**Comment by elboletaire** [comment]
It's only audio.. I think that "subs" at the end is only to say there are subs, because I've checked the mediainfo and it does not include catalan subs, but subs for other languages.

**Comment by Qstick** [comment]
For what it's worth we mainly added this for the TMDb language mapping (original and translations) and ui translation aspect. We only match releases on `catalan` but there are very few I've seen in the wild.

**Comment by CarlesLlobet** [comment]
This would be a lovely addon! 💯 

I can help with providing several Catalan release names. Some examples that quickly come to mind are anime:

- Sakura la caçadora de cartes
- Cinturó Negre
- La màgica Doremi
- Doraemon El gat còsmic
- Bola de Drac
- Gat i Gos
- Rovelló
- La bruixa avorrida
- ...

And some catalan TV Shows:
- Merlí
- Plats Bruts
- El cor de la ciutat
- Joc de Cartes
- ...

Please reach out if you need more, I can look for other more popular TV Shows with catalan release title. 💪 

I look forward this feature 🎉

**Comment by bakerboy448** [comment]
None of those release names appear to be actual release names? If they are actual release names then they would never be parsable by sonarr and do not contain any indication of the season/episode/quality.

**Comment by CarlesLlobet** [comment]
They are not release names, just the catalan titles of these TV shows. 
However, since they are in catalan themselves, just by looking in any indexer it should retrieve valid results.

e.g: Looking for "Gat I gos" in Sonarr already gives the correct result (although its the 3rd suggested, not the first one):
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/6575422/220799615-57e582d3-8fe6-4817-af56-394d166146e1.png">

**Comment by elboletaire** [comment]
I've copy-pasted the release names I've been providing to the main post, so you (devs) can better track them. I also added some more I could find (and I'll probably be adding any new in there, to avoid adding more garbage to the thread).

I also added some notes to the ones that generated doubts.

**Comment by elboletaire** [comment]
Nice to see it's already done!

Just a question I already did, but maybe went unnoticed: should I open this issue in radarr project too? Or will they take these changes as upstream changes?

**Comment by markus101** [comment]
They have already added it, Baker linked the commit above.

**Comment by elboletaire** [comment]
O right, at the moment I read it, I thought it was about sonarr.

Thanks for the confirmation and thank you so much for the implementation 😄

**Comment by CarlesLlobet** [comment]
Hi @markus101,
When will this feature from develop be merged into main?
Super interested in having it in main release, but not sure about procedures from dev to main within ARR

**Comment by markus101** [comment]
Everything in develop will be released when v4 is released. There is no ETA when v4 will be released.
