### ISSUE TITLE
Disable import toggle

### ISSUE THREAD

**Issue by hellot1m** [Sonarr/Sonarr#5442]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

There are many shows like doctor who (1963/2005) and many animes that import incorrectly. For example with animes sometimes seasons are listed in indexers are parts or sequels (blue dragon, Blue Dragon II, Blue Dragon III) were the series numbering starts over at 01 for each season. When a anime is listed as anime type it keeps the numbers going between each season. Which is great for a majority of animes but problematic for animes that area each season as a sequel instead of a season. So animes like "Blue Dragon II - 02" auto-imports as "blue dragon - 02". Similar problem when grabbing entire seasons at once. Sometimes sonarr imports each episode from a single pack just fine. But sometimes it only imports the first episode in a pack and deletes the rest because of how the pack is numbers in the title. 

### Describe the solution you'd like

I would love a toggle in settings->media management->importing-> Auto Import ☑️. On by default. But when a user is working with a series with known importing issues like most famously doctor who, a user can go in and turn off importing while working with the series so all downloads remain in the Queue awaiting user interaction. This would allow us to manually select the show/season/episode for manual import. Similar to how sonarr reacts when it's not able to detect a show. 

Also to take this a step further, maybe to avoid conflicts when adding shows, add an additional options on the window for added down by "start search for missing episodes", "start search for cuttoff unmet episodes" and add a 3rd option "turn off auto-import for missing episodes". Which will still allow search for missing episodes but will keep the episodes in the queue for a set amount of days for user interaction. 

### Describe alternatives you've considered

An alternative would be to add a rule for downloads when using the interactive search that when a user selects the interactive search option for a particular episode that the episode is forced to import to the episode that's being grabbed completely ignoring the name of the file. Example is shown in the image. The two circles are tied together in a grab ignoring what sonarr thinks the episode should be going and forces the episode based on how the user initiated the search. 
![image](https://user-images.githubusercontent.com/51469357/220242612-031ac3c1-305a-4f57-9317-20fe6bdf3272.png)

**Comment by markus101** [comment]
You can already do this by disabling Completed Download Handling and there is already https://github.com/Sonarr/Sonarr/issues/5073 for preventing it during import.

**Comment by hellot1m** [comment]
omg just updated sonarr and you guys included EXACTLY the fix i was looking for. sad this was closed when it looks like something similar to this was already in the works. markus101, are you a dev or just someone that responds?

![image](https://user-images.githubusercontent.com/51469357/233913818-dfacfa69-535a-4acc-be5c-1fffe9238860.png)
