### ISSUE TITLE
Import Lists from Serializd

### ISSUE THREAD

**Issue by imcarvalho** [Sonarr/Sonarr#5443]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Trakt has become a bit clunky for managing TV Shows and has a paywall for some features. [Serializd](https://www.serializd.com/) does the same, but in a more straightforward way and with direct access to RSS feeds, which could potentially be easy to import into Sonarr.

### Describe the solution you'd like

Another option for Import Lists, with Serializd as a source.

### Describe alternatives you've considered

For sure there are more services for managing TV Shows; Serializd could just be another option 😊

**Comment by markus101** [comment]
Please provide a link to their API/RSS feed docs.

**Comment by imcarvalho** [comment]
@markus101 Oof you're right, I can't find a link to them. An example of a feed however looks like [this](https://www.serializd.com/api/user/cosmosbeast/currently_watching_page/1?sort_by=date_added_asc#)

**Comment by markus101** [comment]
That's unfortunate, I don't think we want to go down the path of implementing support in this case as it's unclear what might change as well as how we should access things.

Their "public" lists are quite different in both URL and content: https://www.serializd.com/api/list/2708

**Comment by imcarvalho** [comment]
I understand, it's a shame but indeed the lack of documentation is a deal breaker. Thank you for taking a look at this 😊
