### ISSUE TITLE
Manage Episodes Slow to Load for Series with Many existing Files

### ISSUE THREAD

**Issue by edrock200** [Sonarr/Sonarr#5449]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If I click System in Sonarr, the Free Disk Space section takes minutes to populate. This also happens when I click "manage episodes" on a show or show season. Sometimes it will eventually pop up the manage episodes window, sometimes it will give an error that it couldn't load the content.

### Expected Behavior

Free disk space populates in near realtime, and manage episodes only takes a few seconds to pop up as it did with Sonarr v3.

### Steps To Reproduce

Click System or manage episodes

### Environment

```markdown
- OS: Ubuntu 18.04
- Sonarr: 4.0.0.391-ls414
- Docker Install: linuxserver sonarr container
- Using Reverse Proxy: yes
- Browser: chrome
```

### What branch are you running?

Develop

### Trace Logs?

I turned trace logs on but literally the only entry shown is:
2023-02-24 22:31:11.5|Trace|Http|Res: 67250 [GET] /api/v3/manualimport?seriesId=11&seasonNumber=1&folder=%2Fmnt%2Funionfs%2FMedia%2FTV%2FTV-4K%2FDexter%20-%20New%20Blood%20(2021)%20%5Bimdb-tt14164730%5D%20%5Btvdb-412366%5D&filterExistingFiles=true: 200.OK (82049 ms)

You can see in the above case it took 82 seconds. 

### Anything else?

This may very well be something with my setup but I'm at a loss. Ive tried numerous things and am not sure what is causing it. The latest Radarr develop package on the same server with the same path mappings doesn't exhibit the same behavior. Here's what I've tried so far:

On the docker container, removed any unnecessary path mappings
Tried running it with root user/group
Tried giving the container "priviledged accesss"
Installed a "fresh" v4 sonarr, which was instant on the free disk space. Interestingly the fresh install doesn't show space for the root / dir, but mine does. Not sure if this is related.
Copied my existing DB to the "fresh" install, latency returned.
Ran trace logs - only entry logged is above
"Bashed" into docker container, did a df -h, and it's instant in enumerating drives and free space
Tried switching from linuxserver to hotio container
Tried toggling "don't check free disk space "
Tried same test with Radarr, and its near instant

I removed the NAS mapping and my existing sonarr became "instant" on enumerating free space, but adding my NAS path to fresh instance is also instant. This leads me to believe that Sonarr is doing some sort of show to folder mapping enumeration or comparison on both of these operations, free disk space check and/or manage episodes.

Their are two primary mounts, one on local disk and one on nas storage. The system has 10G connectivity to the NAS storage and browsing or running ls -R type operations are extremely fast.

I just can't tell what it is that Sonarr is trying to do when its spinning on the disk space or manage episodes loading screens. Even if someone could point me to the code section of the System/Disk Space portion of the app, maybe that could yield some clues as to what about my setup, or db, or config is causing this. Did anything significant change in enumerating free disk space between v3 and v4? Does the /  root dir showing up on the "slow" instances but not the "fresh" instance play into this at all?

Thanks in advance for any help.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

You're talking about two very different things here, which may or may not have any correlation. Manage Episodes uses Manual Import and processes existing files as well as any unmapped files, this has changed quite a bit in v4.

Disk Space checks several things, including series paths and disks/mounts. You can see this in `DiskSpaceService` which is called from `DiskSpaceController` that handles the `diskspace` path. If you have questions about this, use one of the support channels.

> I turned trace logs on but literally the only entry shown is
Don't include one line of trace logs, upload the file somewhere and link it here as requested. There are plenty more lines, including the line for the initial request.

**Comment by edrock200** [comment]
Understood and my apologies. It's really manage eps that I would like to get working. I'll upload the logs and link.

**Comment by edrock200** [comment]
Here you go, looks like around line 555 is the initial request:
https://pastebin.com/DDkpD6CL
