### ISSUE TITLE
Sonarr V4 - Enhancement of the languages/MULTI parsing

### ISSUE THREAD

**Issue by WoisWoi** [Sonarr/Sonarr#5450]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Yes, I managed to parse correctly MULTI (in my case : VO + VF) releases on Sonarr V3 which is impossible now on the V4 at this time.
Note that I have no issue regarding this point on Radarr either, it's specifically related to Sonarr V4.

### Describe the solution you'd like

Well either this one : https://github.com/Sonarr/Sonarr/issues/2854 (which is now easy (or easier, at least) to consider with the Custom Formats in place).

### Describe alternatives you've considered

AND/OR bring back the possibility to rate Custom Formats score by Indexer (as it was possible for Preferred words).

**Comment by bakerboy448** [comment]
> I managed to parse correctly MULTI (in my case : VO + VF) releases on Sonarr V3 which is impossible now on the V4 at this time.

This should already be possible with custom formats.

https://trash-guides.info/Sonarr/sonarr-collection-of-custom-formats/#multi-audio

**Comment by WoisWoi** [comment]
> 

I know this guide, yet it's not.
If the release just has "MULTI" and nothing else related to the language, Sonarr will not be able to determine which one it is.

**Comment by bakerboy448** [comment]
So this is a duplicate GHI of #2854 then considering the solution you're asking is for defining multi on a per indexer basis

**Comment by WoisWoi** [comment]
The "alternative" solution I mentionned is not a duplicate of https://github.com/Sonarr/Sonarr/issues/2854.

**Comment by markus101** [comment]
No plans to add per indexer custom formats like we had for preferred words, which would cause issues when used with preferred words. The solution is covered by #2854
