### ISSUE TITLE
Allow series downloader to filter for HDR or non-HDR content based on file name

### ISSUE THREAD

**Issue by mikejaques** [Sonarr/Sonarr#5454]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I noticed some of my content was HDR, and some non-HDR, not the worst thing in the world, but still sub-optimal. I was thinking a way to select HDR/non-HDR/Both as you ad a new series based solely on the title would be nice.

### Describe the solution you'd like

I know there are work arounds with custom formats, but that is cludgy and not built in by default, a simple name filter in the search phase of downloading media would be great. Although it can never be 100% certain with mislablled media, it will be as accurate as any other search compontent parsed on how reliable the titling is.

META-CODE

**(during adding a new series, and then accessible in each series  "Edit" options for later revision)**
Drop down selection box:    _Title search content allowed_: (options) **HDR** / **Non-HDR** / **Both**

( eg: user selects non-HDR only)

Logic: If title contains "HDR" then do not allow download during search function.

That is very simplistic meta-code, but that's the gist.

### Describe alternatives you've considered

Custom Formats as outlined in trash guides, but that is a cludgy work-around.

**Comment by thezoggy** [comment]
release profiles or custom formats can achieve this. this is one of the use cases its designed for. 
this way you have flexibility and control to do with it what you want. as HDR is not a quality, or HD audio, or UNCUT edits.. etc.

**Comment by markus101** [comment]
This is an intended feature of Custom Formats, not a work-around, we do not have plans to have another similar feature.

**Comment by mikejaques** [comment]
Release profiles I guess works, but custom formats is not a good solution really. Title-parsing is already a part of the selection process in other regards, is it not?

I think my request is a good one, and would be fairly easy to integrate, although I admit I'm not familiar with the code base. The UI elements are a couple of drop down box elements as in my meta-code, and the back end parsing is simply "grep-like" parsing and filtering of a tracker title during whatever round-robin decision-making you use for deciding what release to select to send to the download client for download?

It fixes the default behaviour where currently sonarr doesn't care if the release grabbed is HDR or not.

Please reconsider before dismissing it out of hand, or at a minimum don't close the and dismiss it so quickly. 🤞

**Comment by markus101** [comment]
If you only want HDR or not-HDR for all qualities then or want to build more complicated regex then Release Profiles will work.

We're not considering this because it's covered by other existing features without having to be set for each series and without having to add something similar for every possible combination someone might want. You want HDR, but what about if you only want DV or not-DV. Then there is/was 3D, or audio, I only want DD 5.1, so now you've just added more options and continue to have to add options because someone wants something specific.

**Comment by mikejaques** [comment]
I guess I see your point @markus101.

But it would be nice if some of these common things people look for, like hdr/no, hevc/no, dd5.1/ac3, etc, were baked into "release profiles" and maybe have them turned off by default. I know that's not currently possible, but it would be nice if they could be enabled/disabled with a check-box toggle, much like I can do with pfSense firewall rules can be.

Maybe that's something to consider for the future?
