### ISSUE TITLE
Misaligned rendering on episode summary actions header

### ISSUE THREAD

**Issue by datcactus** [Sonarr/Sonarr#5457]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The line underneath the actions (right of Formats, has the details/delete buttons) section on the Episode Summary -> Details tab is a pixel lower than the rest of the line render for the section.

### Expected Behavior

Line should render on the same plane.

### Steps To Reproduce

1. Click on the episode name of any show to bring up the Episode Summary (and default Details tab) screen
2. Observe that the actions section is 1 pixel lower than the rest

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.0.391
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox 110, Chrome 110.0.5481.177
```

### What branch are you running?

Develop

### Trace Logs?

N/A

### Anything else?

![image2](https://user-images.githubusercontent.com/107456394/221477559-5124f251-44be-476a-917e-7da903ca94ea.png)

Maybe somehow related to https://github.com/Sonarr/Sonarr/issues/5456

**Comment by markus101** [comment]
This can be fixed with https://github.com/Sonarr/Sonarr/issues/5456
