### ISSUE TITLE
Use `name` as primary key for indexers/downloaders/connect

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [Sonarr/Sonarr#5458]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I want to have a simple declarative setup where I pass to the container values where and how to connect to other services and it just works:tm:

### Describe the solution you'd like

Instead of using autogenerated `id` as the primary key - use `name` instead since it seems to be used as the primary key anyways (might be a bit of an oversight from REST/SQL design)

This way one could have a simple init container that just executes POST requests on startup without any fancy integrations

### Describe alternatives you've considered

1. First-class declarative support, config file instead of DB or configuration via env variables would be great
2. On each load init container would remove all configurations and post the expected one

### Anything else?

Just curious, this application is super monolithic, I assume it was done due to setup simplicity, just a single binary that needs to run - am I correct or are there any other reasons?

If it was more microservice based other projects like Radarr could integrate 

I'll admit, this is my inner architect OCD speaking

**Comment by markus101** [comment]
No plans to make such a change, it'd require a pretty major overhaul for such a niche use case.

The goal was never to integrate multiple solutions, such as Radarr or Lidarr (not that they existed at the time).

**Comment by gmile** [comment]
For what it's worth, I'd be interested in having ability to configure Sonarr declaratively too.

For context, I recently had to re-build my entire Qbittorrent/Sonarr/Radarr/Jackett/Plex set up on a new machine, and despite the fact that all services were as docker containers and part of a `docker-compose.yml`, I had to spend a few hours clicking through the UI to modify internal configuration of each app.

For Sonarr in particular, this involved:
* configuring the network location of Plex,
* configuring the network location of Qbittorrent,
* configuring the network location of Jackett (actually, a configuration per tracker in Jackett).

Not that it cannot be done, I just found it tedious and a bit inconvenient.

On the other hand, had there be a way to make configuration declarative, I can imagine how bootrapping a system could become much fater.

**Comment by gmile** [comment]
It just crossed my mind that all this set up could potentially be scripted by issuing a series of HTTP requests to [Sonarr API](https://sonarr.tv/docs/api/) using `curl`:

Per my needs above:

* Plex configuration: https://sonarr.tv/docs/api/#/Notification/post_api_v3_notification
* Qbittorrent integration: https://sonarr.tv/docs/api/#/DownloadClient/post_api_v3_downloadclient
* Jackett integration: https://sonarr.tv/docs/api/#/Indexer/post_api_v3_indexer

I think this won't be fully automatic yet (e.g. you need to generate & copy an API key from Sonarr), but suddenly it becomes much less tedious and doing it all manually.
