### ISSUE TITLE
Minor documentation update

### ISSUE THREAD

**Issue by kewarken** [Sonarr/Sonarr#5459]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The documentation on https://sonarr.tv/#downloads-v3-linux-ubuntu is using a deprecated method to add signing keys for your packages. apt-key is deprecated in favor of gpg.

### Expected Behavior

The equivalent behavior on new Ubuntus can be achieved with:
sudo mkdir -p /etc/apt/keyrings/ # if it does not already exist
sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/sonarr.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: n/a
- Docker Install: n/a
- Using Reverse Proxy: n/a
- Browser: n/a
```

### What branch are you running?

Main

### Trace Logs?

n/a

**Comment by kewarken** [comment]
I don't think my instructions are quite accurate.

**Comment by eXhumer** [comment]
I came across this while receiving a warning about apt-key deprecation warning, [this is what Mono project is doing, my suggestion is to do the same][mono-installation-page].
> `sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF`

We can use this to modify the existing `apt-key` command to the following `gpg` commands + change to assign keyring for Sonarr source.

## Example for debian buster
```
sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/sonarr-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8
echo "deb [signed-by=/usr/share/keyrings/sonarr-keyring.gpg] https://apt.sonarr.tv/debian buster main" | /etc/apt/sources.list.d/sonarr.list
```

I'll try to skim through the documentation later today when I'm free and see what needs to be changed and contribute the changes myself.

[mono-installation-page]: https://www.mono-project.com/download/stable/#download-lin-ubuntu
