### ISSUE TITLE
Add 'Minimum Age' to download profiles

### ISSUE THREAD

**Issue by Scratch-Mang** [Sonarr/Sonarr#5460]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No, not related to an existing problem. Not a problem at all.

### Describe the solution you'd like

When creating a download Quality Profile (eg: Default (SD) / HD - All HD - 1080p etc..) where one defines the quality of download wanted. it would be nice to also be able to add an "Age" (Min/Max) as there are some shows that have had both European and North American releases but years apart, so for example if a show originally aired in Europe Five years ago and the North American version was released 3 years ago it would be nice to specify that you are only looking for Show "X", Quality "Y" and must be at least "Z" Days old which would disqualify anything released int he past year or two and only look for episodes that were uploaded before a set date. If that makes sense.

For example.. 

There's two series of "Ghosts" One from the UK and one from the USA. The USA Version was released in 2021 whereas the UK Version was released in 2019. So when searching for season 1 or 2 of the UK version being able to say if S01E01 has a release date the is NOT Greater than 730 Days then ignore and only grab versions of S01E01 that are greater than 730 Days old.

Same would apply for the new Series "Night Court" and the Old Original Series of the same name. "Magnum PI" also springs to mind as another one. 

Anyway, just a thought..

### Describe alternatives you've considered

No alternative, the only thing one can do is manually search for older posts.

### Anything else?

Thanks for Sonarr.!

**Comment by markus101** [comment]
This is the same as https://github.com/Sonarr/Sonarr/issues/5312

The impossible part is things are reuploaded all the time, when things have close or conflicting titles and ambiguous releases there will be issues.

**Comment by Scratch-Mang** [comment]
Fair enough, and re-uploads would be an issue I agree. Thank you.

**Comment by Scratch-Mang** [comment]
> This is the same as #5312
> 
> The impossible part is things are reuploaded all the time, when things have close or conflicting titles and ambiguous releases there will be issues.

This is true.

However I have encountered times when looking for an older (Original Series) episode where it downloads the 'newer series' version and it would be a convenient option to tell Sonarr to ignore posts that are not at least "X" days old.

But again i understand your point...

**Comment by bakerboy448** [comment]
> looking for an older (Original Series) episode where it downloads the 'newer series' version

that's due to sites not supporting id based searches, returning incorrect results, or releases being named incorrectly and thus associated with the wrong series. Nothing Sonarr can really do and is something the sites and release groups need to correct
