### ISSUE TITLE
Not able to start sonarr after docker upgrade

### ISSUE THREAD

**Issue by antoinegomez** [Sonarr/Sonarr#5465]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

docker crash at startup

### Expected Behavior

docker running

### Steps To Reproduce

Start sonarr with this docker-compose.yml file on ubuntu 20.04 Proxmox CT container

unpriviledge and nesting=1

`services:
  sonarr:
    user: 0:1005
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /xxxx/:/tv
      - /yyyy:/data
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true`

### Environment

```markdown
- OS: ubuntu 20.04 LTS
- Sonarr: latest linuxserver.io
- Docker Install: 23.0.1
- Using Reverse Proxy: Not relevant but yes, traefik
- Browser: not relevant
```

### What branch are you running?

Main

### Trace Logs?

`docker -v
Docker version 23.0.1, build a5ee5b1`

`sonarr  | [migrations] started
sonarr  | [migrations] no migrations found
sonarr  | usermod: no changes
sonarr  | 
sonarr  | -------------------------------------
sonarr  |           _         ()
sonarr  |          | |  ___   _    __
sonarr  |          | | / __| | |  /  \
sonarr  |          | | \__ \ | | | () |
sonarr  |          |_| |___/ |_|  \__/
sonarr  | 
sonarr  | 
sonarr  | Brought to you by linuxserver.io
sonarr  | -------------------------------------
sonarr  | 
sonarr  | To support the app dev(s) visit:
sonarr  | Sonarr: https://sonarr.tv/donate
sonarr  | 
sonarr  | To support LSIO projects visit:
sonarr  | https://www.linuxserver.io/donate/
sonarr  | -------------------------------------
sonarr  | GID/UID
sonarr  | -------------------------------------
sonarr  | 
sonarr  | User uid:    911
sonarr  | User gid:    911
sonarr  | -------------------------------------
sonarr  | 
sonarr  | [custom-init] No custom files found, skipping...
sonarr  | [Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/Sonarr.exe - Version 3.0.9.1549 
sonarr  | mono_threads_pthread_kill: pthread_kill failed with error 11 - potential kernel OOM or signal queue overflow
sonarr  | 
sonarr  | =================================================================
sonarr  | 	Native Crash Reporting
sonarr  | =================================================================
sonarr  | Got a SIGABRT while executing native code. This usually indicates
sonarr  | a fatal error in the mono runtime or one of the native libraries 
sonarr  | used by your application.
sonarr  | =================================================================
sonarr  | 
sonarr  | =================================================================
sonarr  | 	Native stacktrace:
sonarr  | =================================================================
sonarr  | 	0x56241a22bffb - mono : 
sonarr  | 	0x56241a22c38d - mono : 
sonarr  | 	0x56241a1d9087 - mono : 
sonarr  | 	0x56241a22b57c - mono : 
sonarr  | 	0x7ff159d59520 - /lib/x86_64-linux-gnu/libc.so.6 : 
sonarr  | 	0x7ff159dada7c - /lib/x86_64-linux-gnu/libc.so.6 : pthread_kill
sonarr  | 	0x7ff159d59476 - /lib/x86_64-linux-gnu/libc.so.6 : raise
sonarr  | 	0x7ff159d3f7f3 - /lib/x86_64-linux-gnu/libc.so.6 : abort
sonarr  | 	0x56241a19b3c4 - mono : 
sonarr  | 	0x56241a480135 - mono : 
sonarr  | 	0x56241a49d5be - mono : 
sonarr  | 	0x56241a49dad7 - mono : monoeg_g_logv
sonarr  | 	0x56241a49db93 - mono : monoeg_g_log
sonarr  | 	0x56241a49229e - mono : 
sonarr  | 	0x56241a4925c7 - mono : 
sonarr  | 	0x56241a48d16a - mono : 
sonarr  | 	0x56241a48eb21 - mono : 
sonarr  | 	0x56241a4390e0 - mono : 
sonarr  | 	0x56241a449be3 - mono : 
sonarr  | 	0x56241a449e1f - mono : 
sonarr  | 	0x56241a44a32b - mono : 
sonarr  | 	0x56241a43a16b - mono : 
sonarr  | 	0x56241a43a54a - mono : 
sonarr  | 	0x56241a41df1d - mono : 
sonarr  | 	0x408578e7 - Unknown
sonarr  | 
sonarr  | =================================================================
sonarr  | 	Telemetry Dumper:
sonarr  | =================================================================
sonarr  | Pkilling 0x140674504980032x from 0x140674570739840x
sonarr  | Pkilling 0x140674502878784x from 0x140674570739840x
sonarr  | Pkilling 0x140674500777536x from 0x140674570739840x
sonarr  | Pkilling 0x140674524128832x from 0x140674570739840x
sonarr  | Entering thread summarizer pause from 0x140674570739840x
sonarr  | Finished thread summarizer pause from 0x140674570739840x.
sonarr  | Failed to create breadcrumb file (null)/crash_hash_0x91f8f5614
sonarr  | 
sonarr  | Waiting for dumping threads to resume
sonarr  | 
sonarr  | =================================================================
sonarr  | 	External Debugger Dump:
sonarr  | =================================================================
sonarr  | mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb
sonarr  | 
sonarr  | =================================================================
sonarr  | 	Basic Fault Address Reporting
sonarr  | =================================================================
sonarr  | Memory around native instruction pointer (0x7ff159dada7c):0x7ff159dada6c  05 00 44 89 e2 89 ee 89 c7 b8 ea 00 00 00 0f 05  ..D.............
sonarr  | 0x7ff159dada7c  41 89 c5 41 f7 dd 3d 00 f0 ff ff b8 00 00 00 00  A..A..=.........
sonarr  | 0x7ff159dada8c  44 0f 46 e8 e9 6d ff ff ff 0f 1f 00 48 89 ef e8  D.F..m......H...
sonarr  | 0x7ff159dada9c  10 a8 ff ff e9 29 ff ff ff 0f 1f 00 48 89 ef e8  .....)......H...
sonarr  | 
sonarr  | =================================================================
sonarr  | 	Managed Stacktrace:
sonarr  | =================================================================
sonarr  | 	 at <unknown> <0xffffffff>
sonarr  | 	 at System.Object:__icall_wrapper_mono_gc_alloc_obj <0x00076>
sonarr  | 	 at System.Object:AllocSmall <0x00103>
sonarr  | 	 at System.Text.RegularExpressions.RegexParser:NoteCaptureSlot <0x000d2>
sonarr  | 	 at System.Text.RegularExpressions.RegexParser:AssignNameSlots <0x00157>
sonarr  | 	 at System.Text.RegularExpressions.RegexParser:CountCaptures <0x004a3>
sonarr  | 	 at System.Text.RegularExpressions.RegexParser:Parse <0x000cb>
sonarr  | 	 at System.Text.RegularExpressions.Regex:.ctor <0x002f7>
sonarr  | 	 at System.Text.RegularExpressions.Regex:.ctor <0x00057>
sonarr  | 	 at NzbDrone.Common.Instrumentation.CleanseLogMessage:.cctor <0x00363>
sonarr  | 	 at System.Object:runtime_invoke_void <0x00086>
sonarr  | 	 at <unknown> <0xffffffff>
sonarr  | 	 at NzbDrone.Common.Instrumentation.NzbDroneFileTarget:GetFormattedMessage <0x0004b>
sonarr  | 	 at NLog.Targets.FileTarget:GetBytesToWrite <0x00038>
sonarr  | 	 at NLog.Targets.FileTarget:Write <0x00317>
sonarr  | 	 at NLog.Targets.Target:Write <0x00047>
sonarr  | 	 at NLog.Targets.Target:WriteAsyncThreadSafe <0x00100>
sonarr  | 	 at NLog.Targets.Target:WriteAsyncLogEvent <0x00326>
sonarr  | 	 at NLog.LoggerImpl:WriteToTargetWithFilterChain <0x0011f>
sonarr  | 	 at NLog.LoggerImpl:Write <0x00543>
sonarr  | 	 at NLog.Logger:WriteToTargets <0x00063>
sonarr  | 	 at NLog.Logger:WriteToTargets <0x0008b>
sonarr  | 	 at NLog.Logger:WriteToTargets <0x0005f>
sonarr  | 	 at NLog.Logger:Info <0x000cf>
sonarr  | 	 at NzbDrone.Host.Bootstrap:Start <0x000c7>
sonarr  | 	 at NzbDrone.Console.ConsoleApp:Main <0x00193>
sonarr  | 	 at <Module>:runtime_invoke_void_object <0x00091>`

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Make sure on of their FAQ entries isn't the issue: https://docs.linuxserver.io/faq
