### ISSUE TITLE
Local File Upload

### ISSUE THREAD

**Issue by hughesjs** [Sonarr/Sonarr#5466]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes, something isn't available on my indexers.
I might also have local backups of DVDs that I want to upload.
It's somewhat of a pain to have to SSH into my host server, make the relevant folder, SCP the file over, and import it.

### Describe the solution you'd like

Next to missing episodes, and when adding a new series, there should be the option to upload files from the local machine. These should then be imported and catelogued in a similar fashion to how a usenet download would be.

### Describe alternatives you've considered

Manually copying and then importing.

**Comment by hughesjs** [comment]
If people think this would be a good addition, I'm open to working on the feature myself, although the timeline for that could be quite extended as I'm very busy at the moment

**Comment by markus101** [comment]
Unfortunately for such a niche feature this isn't something we want to support and maintain long term and believe while its' close to Sonarr's use case it's outside the scope of it. Using something like sshfs to to transfer the files may be a viable option in some set ups.
