### ISSUE TITLE
Alias on older show is trumping actual name of new show

### ISSUE THREAD

**Issue by Extremity** [Sonarr/Sonarr#5468]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When trying to import an updated episode of a currently airing show, "Urusei Yatsura" (TVDB ID: 414096), the episodes - which are properly labeled (there are even variations, such as **[LostYears] Urusei Yatsura - S01E01 (WEB 1080p HEVC AAC E-AC-3) [Dual-Audio] (Urusei Yatsura (2022))** and **[LostYears] Urusei Yatsura - S01E01 (WEB 1080p HEVC AAC E-AC-3) [AA19DA44]**) will not automatically download as there is another show on TVDB that has its title as an alias.

Sonarr gives the following reason: 
Urusei Yatsura matches an alias for series with TVDB ID: 75113

...which is true. This is a remake of the older show, and they have different names. The names may be the same after translation, I don't know, but the fact remains that this is this show's name and the other's alias, and the logic that a series alias trumps a series' actual name doesn't seem right. 

### Expected Behavior

I would expect an alias to come secondary after a hard title. I think?

### Steps To Reproduce

1. Do a search for S01E01 of the show Urusei Yatsura (the new one) with AnimeTosho as an indexer. (I'm not sure if I'm allowed to link to the file)
2. Check the LostYears Dual Audio releases, which will not be grabbed as the error will be shown.

### Environment

```markdown
- OS: Windows 10
- Sonarr: 3.0.9.1549
- Docker Install: N/A
- Using Reverse Proxy: Yes
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

I don't have logs and already manually grabbed the episode, but I feel like this is simple enough that it's completely understood without a log. Sorry for not having one, I wasn't expecting this behavior and only decided to report after manually grabbing it.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Aliases trump original names so that we can override things and map similar names series to the correct series, but this is more of an alias problem, not a bug. Best to bring up with XEM.
