### ISSUE TITLE
Show Downloading Status in Progress Bar

### ISSUE THREAD

**Issue by TheFreedom90** [Sonarr/Sonarr#5474]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No visibility on when a missing episode is being downloaded in the main dashboard.

### Describe the solution you'd like

Currently, the bar is white if nothing is downloaded.
Red when episodes are missing.
Green when all episodes are downloaded.

But I want to see when it is downloading episodes. The bar, too turn orange/yellow (different color).
So I know that it is downloading episodes.

As of the moment, it can be downloading the episode but I have to open the series and to check.

### Describe alternatives you've considered

add status that is is downloading.

**Comment by markus101** [comment]
Orange is already used. It'd make more sense to use the same purple that we use for downloading, though my concern is doing so would be too expensive as it would need to pull in and process the whole queue to see if there was a match for that series.

![image](https://user-images.githubusercontent.com/413544/223469154-ff41c6b7-4eea-4c05-9bfc-278bb76ce27f.png)

**Comment by twolaw** [comment]
Or do like Medusa, add a +1 next to episode count.
Meaning 1 episode has been sent to download client.

![image](https://user-images.githubusercontent.com/10365746/223689927-d8a2cab9-fc05-4bbb-8b55-3da68a3c2ef9.png)

**Comment by TheFreedom90** [comment]
> Orange is already used. It'd make more sense to use the same purple that we use for downloading, though my concern is doing so would be too expensive as it would need to pull in and process the whole queue to see if there was a match for that series.
> 
> ![image](https://user-images.githubusercontent.com/413544/223469154-ff41c6b7-4eea-4c05-9bfc-278bb76ce27f.png)

Maybe make it yellow. 
Not sure if it is possible just an idea to given better visibility on the dashboard
