### ISSUE TITLE
Additional Filter Options for Calendar

### ISSUE THREAD

**Issue by HeHeHaHa456** [Sonarr/Sonarr#5476]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

On the Calendar page the filter options are "all" or "Monitored Only".

On the Series Page you can have "all", "Monitored Only", "Unmonitored Only", "Continuing Only", "Ended Only", "Missing Episodes", and "Custom Filters" with many options to do exactly what you want.

### Describe the solution you'd like

I would like to request the custom filtering options that are available on the Series page to be on the Calendar page. So that I can filter out the shows I'm not interested in but get for family (like the real housewives) and all the shows I am interested in (Like SEAL Team) and watch.

I use Quality Profiles to Separate show groups Like "Fav Shows", "Current Shows", "Ended Shows", "Reality Shows", "Documentary Shows".

So I would have Fav Shows on the calendar and hide everything else most of the time.

### Describe alternatives you've considered

I tried a couple of versions of having two Sonarr Installs but I ran into weird issues and it was kind of a pain to manage and switch between.

Or going back to one of the programs I used before Sonarr but they are not nearly as good. Sonarr doesn't care if you have 10 shows or 1000 it works the same and is amazing for managing a large collection.

Thanks for making, Maintaining and Improving Sonarr,

HeHeHaHa456

### Anything else?

All of the shows more got cut off at the bottom
![Before](https://user-images.githubusercontent.com/127435934/224118909-7a7c2981-4ca2-4857-a7fe-e61d61839f53.png)
Filtered shows I watch - Example
![zAfter](https://user-images.githubusercontent.com/127435934/224118912-23fa8e8c-cc44-47b6-9cd6-df9293b31365.png)

**Comment by HeHeHaHa456** [comment]
Also I would like to add the Enhancement Label but can't seem to find the button?

**Comment by markus101** [comment]
> I use Quality Profiles to Separate show groups Like "Fav Shows", "Current Shows", "Ended Shows", "Reality Shows", "Documentary Shows".

Besides different names are these actually different quality profiles? If not you should consider a single quality profile and use tags for separating them, that's of of the intended usages of them.

It's unlikely we will add full custom profiles to Calendar, because unlike series the filtering is not done on the client side and it doesn't make sense to move that filtering to the client. Tags is already something we support for filtering on the `ical` calendar output, so adding that would make sense, but filtering on quality profile is unlikely.

> Also I would like to add the Enhancement Label but can't seem to find the button?

You don't, we do if it's something we intend to add.

**Comment by HeHeHaHa456** [comment]
Your title is really what I am looking for "Additional Filter Options for Calendar" maybe a third option for filter by tag then?

> Tags is already something we support for filtering on the ical calendar output, so adding that would make sense, 

I do have one tag set up for the shows I watch and it sends pushover alert when an episode is downloaded.

I have had the ical set up (google calendar) for a while but it get mixed in with my regular calendar, don't like the layout since I have multiple show at the same time and I just don't use it.


> You don't, we do if it's something we intend to add.

Makes sense

Thanks

**Comment by JBake130** [comment]
>Tags is already something we support for filtering on the `ical` calendar output, so adding that would make sense,

I’m not sure this is working.  I just tried to filter by tag and when I hit ical link after setting a tag it’s showing all my upcoming episodes.

**Comment by markus101** [comment]
Looks like it's broken in v4, we'll get a fix for it out.

**Comment by HeHeHaHa456** [comment]
Calendar tags work great thanks
