### ISSUE TITLE
Calendar Agenda view has wrong status for unaired episodes

### ISSUE THREAD

**Issue by emilnymann** [Sonarr/Sonarr#5477]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

In the Agenda view of the Calendar, all unaired/future episodes have the unmonitored status, which is white according to the legend at the bottom.

![image](https://user-images.githubusercontent.com/98811735/224313337-e919affb-9473-436e-8518-d0eeb507e704.png)

### Expected Behavior

Future episodes should have the unaired status, which is blue according to the legend at the bottom.

### Environment

```markdown
- OS: Ubuntu Server 22.04.2 LTS
- Sonarr: 4.0.0.396
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chromium-based Edge 110.0.1587.63
```

### What branch are you running?

Develop

### Trace Logs?

Not relevant

**Comment by stevietv** [comment]
Fixed via PR:

![image](https://user-images.githubusercontent.com/1117625/224316680-b8a754dc-b691-4fe3-a28f-261abf0d266e.png)
