### ISSUE TITLE
SRT files doesn't get renamed when doing "preview rename"

### ISSUE THREAD

**Issue by xbette** [Sonarr/Sonarr#5480]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When i download a show manually and paste it to the series folder and rescan and rename them via "preview rename" then it only renames the mkv file.. 

"file name on mkv file is: Curlingklubben.paa.sabbataarsrejse.S01E01.DANiSH.1080p.WEB-DL.H.264.AAC2.0-RTBYTES.mkv"
"file name on srt file is: Curlingklubben.paa.sabbataarsrejse.S01E01.DANiSH.1080p.WEB-DL.H.264.AAC2.0-RTBYTES.da.srt"

EVEN if i change the srt file to "Curlingklubben.paa.sabbataarsrejse.S01E01.DANiSH.1080p.WEB-DL.H.264.AAC2.0-RTBYTES.srt" and do a rescan then sonarr actually sees the srt file but even there it doesn't rename the srt file. 

### Expected Behavior

i expected that sonarr renamed both srt and mkv file even if the srt file is named with a language code after the file name

i mean if the file name is "Curlingklubben.paa.sabbataarsrejse.S01E01.DANiSH.1080p.WEB-DL.H.264.AAC2.0-RTBYTES.da.srt" and mkv file is "Curlingklubben.paa.sabbataarsrejse.S01E01.DANiSH.1080p.WEB-DL.H.264.AAC2.0-RTBYTES.mkv" it still should see all files and rename it correct

### Steps To Reproduce

1: I downloaded the  series manually and pasted them into the series folder "Curlingklubben på sabbatårsrejse\Season 1"
2: made a rescan
3: presset "preview rename" selected one episode to test with

### Environment

```markdown
- OS: Windows Server 2008 R2
- Sonarr: 3.0.10.1566
- Docker Install: No docker
- Using Reverse Proxy: Nope
- Browser: Chrome Version 110.0.5481.177 (Officiel version) (x86_64)
```

### What branch are you running?

Main

### Trace Logs?

https://privatebin.net/?c2c36ce63aadd0de#CpVXeyUZW58WLs3A3e2LXz8vBjZWmQ8C1A6jUPGqQJDH

**Comment by stevietv** [comment]
I hadn't quite realised that you were putting the files into the folder yourself during our discussion on discord.
This is not how you should bring files into Sonarr to rename. Something manually downloaded should be imported into sonarr via the `wanted > manual import` function. When you bring a file in like that, does it then bring your subtitle file in and rename both also in one step?

**Comment by markus101** [comment]
I tested with these exact file names and renamed after previewing and had no issues. Perhaps this is something already fixed in v4.

**Comment by xbette** [comment]
> I hadn't quite realised that you were putting the files into the folder yourself during our discussion on discord. This is not how you should bring files into Sonarr to rename. Something manually downloaded should be imported into sonarr via the `wanted > manual import` function. When you bring a file in like that, does it then bring your subtitle file in and rename both also in one step?

I know this is not how it should be done by adding them manually, But since my source (DanishBytes) did not have thetvdb ID added on the torrent as i added it to sonarr, then i downloaded the files manually and put them in the folder.. 


I didn't know about the "wanted -> manual import" Just did that and worked like a charm :) Thanks!
