### ISSUE TITLE
season search does not do correct modal size for extraLarge breakpoint

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#5483]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

setting browser to 1450px+ width, episode search the modal is extraLarge but season search is only Large. 

### Expected Behavior

show correct modal size for the breakpoint regardless if its season or episode search

### Steps To Reproduce

use any browser and do interactive season + episode  search

### Environment

```markdown
- OS: Win 10
- Sonarr: 4.0.0.397
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox / Edge / Chrome
```

### What branch are you running?

Develop

### Trace Logs?

none

### Anything else?

user reported in discord, confirmed

**Comment by markus101** [comment]
> show correct modal size for the breakpoint regardless if its season or episode search

This isn’t a thing, modal sizes are set, not based on screensize.

**Comment by thezoggy** [comment]
ok, then can we get season search modal to be the same as episode search modal?
