### ISSUE TITLE
Sonarr Crashing upon install

### ISSUE THREAD

**Issue by SilverSix311** [Sonarr/Sonarr#5485]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

`    
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
=================================================================
	Native stacktrace:
=================================================================
	0x5626bcb38ffb - mono : 
	0x5626bcb3938d - mono : 
	0x5626bcae6087 - mono : 
	0x5626bcb3857c - mono : 
	0x7f6dca18b520 - /lib/x86_64-linux-gnu/libc.so.6 : 
	0x7f6dca1dfa7c - /lib/x86_64-linux-gnu/libc.so.6 : pthread_kill
	0x7f6dca18b476 - /lib/x86_64-linux-gnu/libc.so.6 : raise
	0x7f6dca1717f3 - /lib/x86_64-linux-gnu/libc.so.6 : abort
	0x5626bcaa83c4 - mono : 
	0x5626bcd8d135 - mono : 
	0x5626bcdaa5be - mono : 
	0x5626bcdaac73 - mono : monoeg_assertion_message
	0x5626bcd27f08 - mono : 
	0x5626bcc159f6 - mono : 
	0x5626bcaab047 - mono : 
	0x5626bcab97b6 - mono : mono_main
	0x5626bcaa84df - mono : 
	0x7f6dca172d90 - /lib/x86_64-linux-gnu/libc.so.6 : 
	0x7f6dca172e40 - /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main
	0x5626bcaa8b1e - mono : _start
=================================================================
	Telemetry Dumper:
=================================================================
Entering thread summarizer pause from 0x140109518504064x
Finished thread summarizer pause from 0x140109518504064x.
Failed to create breadcrumb file (null)/crash_hash_0x0
Waiting for dumping threads to resume
=================================================================
	External Debugger Dump:
=================================================================
mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb
=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7f6dca1dfa7c):0x7f6dca1dfa6c  05 00 44 89 e2 89 ee 89 c7 b8 ea 00 00 00 0f 05  ..D.............
0x7f6dca1dfa7c  41 89 c5 41 f7 dd 3d 00 f0 ff ff b8 00 00 00 00  A..A..=.........
0x7f6dca1dfa8c  44 0f 46 e8 e9 6d ff ff ff 0f 1f 00 48 89 ef e8  D.F..m......H...
0x7f6dca1dfa9c  10 a8 ff ff e9 29 ff ff ff 0f 1f 00 48 89 ef e8  .....)......H...
=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
* Assertion at gc.c:1005, condition `is_ok (error)' not met, function:mono_gc_init_finalizer_thread, Couldn't create thread. Error 0x0 assembly:<unknown assembly> type:<unknown type> member:(null)
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
=================================================================
	Native stacktrace:
=================================================================
	0x55f8856f4ffb - mono : 
	0x55f8856f538d - mono : 
	0x55f8856a2087 - mono : 
	0x55f8856f457c - mono : 
	0x7fa3edc6a520 - /lib/x86_64-linux-gnu/libc.so.6 : 
	0x7fa3edcbea7c - /lib/x86_64-linux-gnu/libc.so.6 : pthread_kill
	0x7fa3edc6a476 - /lib/x86_64-linux-gnu/libc.so.6 : raise
	0x7fa3edc507f3 - /lib/x86_64-linux-gnu/libc.so.6 : abort
	0x55f8856643c4 - mono : 
	0x55f885949135 - mono : 
	0x55f8859665be - mono : 
	0x55f885966c73 - mono : monoeg_assertion_message
	0x55f8858e3f08 - mono : 
	0x55f8857d19f6 - mono : 
	0x55f885667047 - mono : 
	0x55f8856757b6 - mono : mono_main
	0x55f8856644df - mono : 
	0x7fa3edc51d90 - /lib/x86_64-linux-gnu/libc.so.6 : 
	0x7fa3edc51e40 - /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main
	0x55f885664b1e - mono : _start
=================================================================
	Telemetry Dumper:
=================================================================
Entering thread summarizer pause from 0x140342045339776x
Finished thread summarizer pause from 0x140342045339776x.
Failed to create breadcrumb file (null)/crash_hash_0x0
Waiting for dumping threads to resume`

### Expected Behavior

Running correctly

### Environment

```markdown
- OS: Ubuntu 18.04 LTS
- Sonarr: Linuxserver.io version:- 3.0.10.1567-ls183 Build-date:- 2023-03-13T08:27:19+01:00
- Docker Install: Yes
- Using Reverse Proxy: Traefik
- Browser: Opera DX
```

### What branch are you running?

Main

### Trace Logs?

<html>
<body>

Linuxserver.io version:- 3.0.10.1567-ls183 Build-date:- 2023-03-13T08:27:19+01:00
--

</body>
</html>

**Comment by thezoggy** [comment]
You need to look at lsio docker for this issue. Basically you need to update your docker/kernel. Not anything wrong with sonarr itself

**Comment by bakerboy448** [comment]
Likely https://docs.linuxserver.io/faq#jammy

**Comment by markus101** [comment]
Looks like you have already received the correct answer, but please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
