### ISSUE TITLE
Complete Seasons

### ISSUE THREAD

**Issue by pcmodder2001** [Sonarr/Sonarr#5487]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

sometimes sonarr will find full season downloads but it seems to be rare. (for me anyway) 

so when its finding epsoides invidually its missing some (or just not able to find them) which then means ive to still go and find it most of the time resulting in me canselling sonarr task and just doing it my self. (making the system redundant)

### Describe the solution you'd like

just like how you can set your quality profiles. there to be some sort of download prefrance tab. so you can select which season you want it to find / download first and also the option to only use torrents are have the complete series. 

### Describe alternatives you've considered

im not really sure of any other work arround for this that i have managed to find. if there is one id love to hear about it though :)

**Comment by markus101** [comment]
Season packs are already preferred, but require your indexer to actually return those results, some indexers struggle to do that unless the search specifically looks for a season pack, but given they can be named many different ways it's not possible to do so (Prowlarr/Jackett may be able to help massage the search term for specific indexers).
