### ISSUE TITLE
Link from Health checks to appropriate settings page

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#549]
Some of our health checks are in response to settings not being set, in those cases we should provide links to the proper settings pages (IE: no indexers configured, or download clients not enabled).

**Comment by Taloth** [comment]
Don't we link to the wiki in most of these cases? I rather have the user check the wiki on it instead of be directed to a settings page with no clue about what, why and how.

**Comment by markus101** [comment]
A link to the wiki is good, but it would be nice to also link to the settings page too I think, since some of them are pretty self explanatory (I hope).

**Comment by markus101** [comment]
This has been added in v3.
