### ISSUE TITLE
SIGSEGV from rename_quality_profiles_add_upgrade_allowed on aarch64 Darwin Nix

### ISSUE THREAD

**Issue by chrisseto** [Sonarr/Sonarr#5490]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr crashes during the DB migration phase

```
 ❯ NzbDrone
[Info] Bootstrap: Starting Sonarr - /nix/store/rkhhxwx1dcdyxk4jaii5vi5hgw935b9n-sonarr-3.0.10.1567/bin/Sonarr.exe - Version 3.0.10.1567
[Info] Router: Application mode: Interactive
[Info] MigrationLogger: *** Checking database for required migrations data source=/Users/chrisseto/.config/Sonarr/sonarr.db;cache size=-10000;datetimekind=Utc;journal mode=Truncate;pooling=True;version=3;Full FSync=True ***
[Info] MigrationLogger: *** 128: rename_quality_profiles_add_upgrade_allowed migrating ***
[Info] rename_quality_profiles_add_upgrade_allowed: Starting migration of Main DB to 128
fish: Job 1, 'NzbDrone' terminated by signal SIGSEGV (Address boundary error)
```

### Expected Behavior

Sonarr should not crash.

### Steps To Reproduce

An on m1 mac, install nix and the sonarr package. Then start up sonarr.

```
nix-shell -p sonarr
NzbDrone
```

### Environment

```markdown
- OS: Darwin
- Sonarr: 3.0.10.1567
- Docker Install: No
- Using Reverse Proxy: No (N/A)
- Browser: N/A
```

### What branch are you running?

Main

### Trace Logs?

I can't seem to get trace logs as this is an issue at application start up.

### Anything else?

 Is there a flag I can use to get trace logs? `--help` appears to be ignored.

**Comment by markus101** [comment]
> Is there a flag I can use to get trace logs? --help appears to be ignored.

The wiki page in the template covers this. https://wiki.servarr.com/sonarr/troubleshooting#logging-and-log-files

Given you're trying to run this in a very non-standard way you should try the v4 beta, it should have much better M1 compatibility and changes to v3 will be virtually 0.

**Comment by chrisseto** [comment]
Not much additional info from the trace logs:
```
2023-03-16 20:34:56.8|Debug|ProcessProvider|Found 0 processes with the name: Sonarr.Console
2023-03-16 20:34:56.9|Debug|ProcessProvider|Found 0 processes with the name: Sonarr
2023-03-16 20:34:56.9|Info|Router|Application mode: Interactive
2023-03-16 20:34:56.9|Debug|Router|Console selected
2023-03-16 20:34:56.9|Info|MigrationLogger|*** Checking database for required migrations data source=/Users/chrisseto/.config/Sonarr/sonarr.db;cache size=-10000;datetimekind=Utc;journal mode=Truncate;pooling=True;version=3;Full FSync=True ***
2023-03-16 20:34:57.0|Info|MigrationLogger|*** 128: rename_quality_profiles_add_upgrade_allowed migrating ***
2023-03-16 20:34:57.0|Debug|MigrationLogger|Beginning Transaction
2023-03-16 20:34:57.0|Info|rename_quality_profiles_add_upgrade_allowed|Starting migration of Main DB to 128
```

> Given you're trying to run this in a very non-standard way

Oooooh, yes I'm painfully aware of that. 😅 I figure I might as well open the issue just case anyone else in the wild is running into this.

I'll give v4 a shot and report back!

**Comment by chrisseto** [comment]
v4 works! For posterity, I used `http://download.sonarr.tv/v4/develop/4.0.0.401/Sonarr.develop.4.0.0.401.osx-x64.tar.gz`.

@markus101, feel free to close this if you'd like! I'm happy to help debug the issue in v3 if others run into this problem but I'm also happy to chug along with v4.
