### ISSUE TITLE
Implement the possibility of setting the Initial State of downloads by tags

### ISSUE THREAD

**Issue by krisz-gemini** [Sonarr/Sonarr#5495]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I set the Initial State of the Download Client to Pause. It's necessary to avoid too many downloads coming from automatic lists and quality improvements. However, if I manually select something to watch (e.g. add it to Plex Watchlist), it'd be great if the download started automatically. (Adding a tag to an imported item from any list is already possible in Sonarr.)

### Describe the solution you'd like

The settings dialog  of a Download Client:
1) Rename Initial State to Default Initial State
2) Add 3 new input fields: "Use Pause/Start/ForceStart initial state if any of these tags are present:" and an input field to add the tags. 
 
Of course, any other equivalent solution is okay.

### Describe alternatives you've considered

The possibility of using different download clients by tags (not only priority) could be an alternative.

**Comment by markus101** [comment]
No plans to use tags for partial settings changes in download clients.

https://github.com/Sonarr/Sonarr/issues/402 covers tags in download clients.
