### ISSUE TITLE
Implement 'On Series Added' as an EventType / Connection

### ISSUE THREAD

**Issue by PuppyLover101** [Sonarr/Sonarr#5497]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Similarly to what Radarr v4 does, it would be great to have an 'On Series Added' as a Connection for Notification Triggers / API for Sonarr v4.

### Describe the solution you'd like

Similar to Radarr v4, Sonarr can send a json payload with the series that is added.

### Describe alternatives you've considered

I have considered using the 'On Grab' processing framework for my needs, however that requires Sonarr to grab a download in the first place.

### Anything else?

https://github.com/Radarr/Radarr/blob/dfc9f74116ca46e23f317fcc5163a81c753b9ee7/src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs#L158

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/3637
