### ISSUE TITLE
Custom Transmission url base

### ISSUE THREAD

**Issue by Madseason41** [Sonarr/Sonarr#550]
I have configured Transmission to use "xmsn" as the url base. When I configure this in settings the test fails and replies with:

Unknown exception: REST request failed: [404] [POST] at [http://localhost:9091/xmsn/transmission/rpc]

Any ideas?

I am running 2.0.0.3146 develop.

Thanks

**Comment by markus101** [comment]
Please use the [forums] (https://forums.sonarr.tv/) for support.
