### ISSUE TITLE
Run series refresh when series or season rename triggered

### ISSUE THREAD

**Issue by edrock200** [Sonarr/Sonarr#5500]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sonarr will rename sideloaded media files such as srt's, bif's, etc. when a media rename is done. Often times side loaded media assets are generated by programs external to sonarr, so sonarr is not aware of these assets between daily scans. If a rename operation is run when this condition occurs, the assets are not renamed, and are orphaned and unable to be used with the media.

### Describe the solution you'd like

Run a refresh series operation prior to rename operations.

### Describe alternatives you've considered

Manually run refresh operation prior to rename triggers.

**Comment by markus101** [comment]
Not everyone is doing this, making this largely unnecessary for most users, if this affects you then running a refresh before you rename your files is advisable or have the scripts/tools creating these files tell Sonarr to refresh the series after adding the files.
