### ISSUE TITLE
Season Packs rejected and do not appear to account for CF upgrades

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#5502]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Grey area between bug / feature request.

Currently a Season Pack will be rejected if the Pack is not a quality upgrade for all episodes, and appears to ignore custom formats.
Often times the most preferred season pack may be released after initial grabs occur, the pack is then rejected as it does not upgrade quality - yet matches or would upgrade all episodes.

This cannot be worked around with Custom Formats by giving an additional score to Season Pack as then a download loop may then occur given once imported the Season Pack CF no longer matches the episode files.

`2023-03-23 12:01:16.1|Debug|UpgradableSpecification|New item's custom formats [Season Pack, WEB Tier 01, AMZN, DD+, 2.0 Stereo] (1975) do not improve on [WEB Tier 01, AMZN, DD+, 2.0 Stereo] (1975, skipping`

However, this ignores the episodes that do not have those formats.

**Typo in the log line as well it appears**  

![image](https://user-images.githubusercontent.com/55419169/227281040-8ec8d72f-2365-48b2-8037-ba22456d245c.png)

### Expected Behavior

Season Packs should take into account Quality and CF Score improvements for all episodes and be grabbed if the Season Pack is equal in quality and custom format score for the partial season and if and only if it improves on one or more episodes within the season.

Alternative thoughts welcomed - the usecase being to grab the season pack when released, but avoid a download loop as is spreads across indexers.

### Steps To Reproduce

N/A

### Environment

```markdown
- OS: agnositc
- Sonarr: 4.0.0.412
- Docker Install: agnostic
- Using Reverse Proxy: agnostic
- Browser: agnostic
```

### What branch are you running?

Develop

### Trace Logs?

https://gist.github.com/bakerboy448/69b6454cb45a32b0ce1f89fa62eb2f05

### Anything else?

Season Pack CF

```json
{
  "name": "Season Pack",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Season Packs",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\bS\\d+\\b(?!E\\d+\\b)"
      }
    }
  ]
}
```

**Comment by markus101** [comment]
Season packs are only grabbed if they are an upgrade for _all_ episodes, in this case 18/20 episodes meet the CF score and only 2/20 don't, in which case Sonarr is doing what it intended to do.
