### ISSUE TITLE
Parse Release Term "DisneyHD" as WEBDL, rather than HDTV

### ISSUE THREAD

**Issue by PartTheSeas** [Sonarr/Sonarr#5507]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Not a problem specifically, but as my request for "HBOMaxHD" it would be huge to have the same thing for the German irregularity "DisneyHD"

### Describe the solution you'd like

Parse the Release term "DisneyHD" as WEBDL too, rather than HDTV

### Describe alternatives you've considered

Manual tagging, renaming, adjusting CFs

### Anything else?

Noooope =)

Ah wait, example releases: 

The.Quest.Helden.fuer.Everealm.S01E05.Tavora.greift.an.German.DL.1080p.DisneyHD.h264-4SF
The.Quest.Helden.fuer.Everealm.S01E07.Licht.in.der.Dunkelheit.German.DL.1080p.DisneyHD.h264-4SF

**Comment by thezoggy** [comment]
also to go with previous AmazonHD there is a SD variant: `AmazonSD`
```
Die.Rosenheim-Cops.S13E11.Ausgebacken.German.AmazonSD.h264-4SF
```
