### ISSUE TITLE
Release Profile "Preferred" term bug

### ISSUE THREAD

**Issue by jcouch93** [Sonarr/Sonarr#5512]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have two release profiles that have "Include Preferred when Renaming" checked, which I use as the "Custom Formats" in the Media Properties filename.  One for filenames containing 265 (to use HEVC in the name) and the other for filenames containing 264 (to use AVC in the name).  The HEVC one works with no issue.
![image](https://user-images.githubusercontent.com/16784547/228024678-8f3013ff-8502-4ef4-b158-f53d6bead9fd.png)
![image](https://user-images.githubusercontent.com/16784547/228024767-ab96f486-8f97-496d-824a-a7fca3e80c61.png)

HEVC RP works as expected.  The issue is on the AVC one, in that it appears Sonarr just ignores AVC in the preferred field.  I've tested by putting another term below AVC and performing a rename, and it only sees the second term, never the AVC.

### Expected Behavior

Sonarr should use the AVC term in the Preferred section of the Release Profile

### Steps To Reproduce

Version - 3.0.10.1567
Package Version - 3.0.10.1567-ls184 by [linuxserver.io](https://linuxserver.io/)
Mono Version - 6.12.0.182
AppData directory - /config
Startup directory - /app/sonarr/bin

1. Create RP using AVC in Preferred section
2. Verify "Include Preferred when Renaming" is checked
3. Add "Custom Formats" to Media Management filename
4. Preview Rename for a show or episode

### Environment

```markdown
- OS: unRAID 6.11.5
- Sonarr: 3.0.10.1567
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Vivaldi
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/11081736/sonarr.trace.txt)

### Anything else?

The show name is The 1900 House (so you can find it in the logs easier)

**Comment by markus101** [comment]
> 2023-03-27 13:59:17.2|Trace|PreferredWordService|Determining preferred word matches for 'The.1900.House.S01E10.A.Year.to.Remember.WEB-DL.AAC2.0.H.264-squalor'
2023-03-27 13:59:17.2|Trace|PreferredWordService|Determined preferred word matches for 'The.1900.House.S01E10.A.Year.to.Remember.WEB-DL.AAC2.0.H.264-squalor'. Count 0

Nowhere in the filename does AVC exist, which is required for preferred words to be included when renaming. It looks like the HEVC one probably works because the file/release name contains both 265 and HEVC. You can't arbitrarily use preferred words to add things to the file name, they have to match something.

In v4 (currently beta) you name custom formats and that name is used when renaming as opposed to what has matched.

**Comment by jcouch93** [comment]
Thank you for the explanation!  I understand what you're saying, but one of the files that the HEVC one is working on is "12 Monkeys (2015) - S02E06 - Immortal (HDTV-1080p) (x265).mkv" and also "1899 (2022) - S01E01 - The Ship (HDTV-1080p) (x265)" and neither have HEVC in the name and somehow works.  That's why I thought the HEVC one worked. I'm looking forward to v4 as I do this in Radarr using the Custom Formats and was thinking I can do it here too.  Thank you guys for all you do!
