### ISSUE TITLE
Add option to remove torrent from torrent client only once a better version of an episode is found

### ISSUE THREAD

**Issue by Emiliaaah** [Sonarr/Sonarr#5515]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'd like to keep seeding for as long as possible, But sometimes I later on download a better/ different version of an episode. I would just keep seeding, but that would mean I have to keep all the older versions which I don't really want to do.

### Describe the solution you'd like

I'd like to keep seeding a torrent forever unless I finish downloading a new version of a given episode.

### Describe alternatives you've considered

I could just never remove old versions, but still download the new version. This however would means that I'd be taking up the space of the new files combined with the old ones. This however isn't really viable for me since I don't have unlimited storage.

The other option would be to remove torrents after reaching x seeding ratio, or x time seeded. While this would work, I'd like to keep old torrents alive. So while this option would work it's not ideal.

**Comment by markus101** [comment]
> The other option would be to remove torrents after reaching x seeding ratio, or x time seeded. While this would work, I'd like to keep old torrents alive. So while this option would work it's not ideal.

This already exists.

This isn't something we have plans to add, but you could probably achieve it with a custom script run after importing, specifically an upgrade.

**Comment by Emiliaaah** [comment]
From my searching I couldn't find an issue resembling mine, would you mind linking it?

**Comment by markus101** [comment]
I'm not sure there is a similar one, but we've discussed advanced torrent management previously and it's not something we're intending to do.
