### ISSUE TITLE
Number Inputs Change When Focused and Scrolled Over

### ISSUE THREAD

**Issue by KyleSanderson** [Sonarr/Sonarr#5516]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When a field is selected, and you scroll on the page, the field is incremented / decremented with the page also scrolling.

### Expected Behavior

screen is locked to the field, or scrolling is disabled for inputs.

### Steps To Reproduce

Synaptics 2 finger scroll.

### Environment

```markdown
- OS: linux 5.19
- Sonarr: 4.0.0.421
- Docker Install: crio.
- Using Reverse Proxy: no
- Browser: Chrome 111 Windows 21H2 N
```

### What branch are you running?

Main

### Trace Logs?

![Ouch](https://user-images.githubusercontent.com/1184902/228670209-ef0b1a5f-9639-4b2a-8aad-837853d2ad70.gif)

### Anything else?

It's a quite common problem (in general), with all three solutions being valid.

**Comment by thezoggy** [comment]
solution?:
https://stackoverflow.com/questions/9712295/disable-scrolling-on-input-type-number

**Comment by markus101** [comment]
> screen is locked to the field, or scrolling is disabled for inputs.
> It's a quite common problem (in general), with all three solutions being valid.

I'm counting two solutions, might be your math skills that are brutal.

**Comment by KyleSanderson** [comment]
> > screen is locked to the field, or scrolling is disabled for inputs.
> > It's a quite common problem (in general), with all three solutions being valid.
> 
> I'm counting two solutions, might be your math skills that are brutal.

The third solution is to close the issue... Are you ok?

**Comment by markus101** [comment]
Yeah, just that I wouldn't call this brutal and would suggest something more descriptive, same as I shouldn't call the math brutal and instead ask what the third solution is. FWIW I don't think closing it is so much a solution as an option of not choosing to fix the problem.

**Comment by KyleSanderson** [comment]
Nice one - thank you
