### ISSUE TITLE
Add torrent manually in titles and seasons

### ISSUE THREAD

**Issue by yasumitsuru** [Sonarr/Sonarr#5518]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes Jackett does not find torrents correctly, mainly PT-BR torrents, because they are incorrectly classified as English.

### Describe the solution you'd like

I would like to manually add torrent to titles and seasons so that sonarr can send the torrent files to the client and then organize it automatically as it is already done.

Sometimes Jackett does not find torrents correctly, mainly PT-BR torrents, because they are incorrectly classified as English.

### Describe alternatives you've considered

manual addition of the torrent by the user

### Anything else?

N/A

**Comment by markus101** [comment]
We don't have plans to manually add torrents, but you can add them to your client manually and set the proper category for them to show up in Sonarr's queue.

**Comment by yasumitsuru** [comment]
> We don't have plans to manually add torrents, but you can add them to your client manually and set the proper category for them to show up in Sonarr's queue.


How do I do that? I know that when sonarr sends the torrent to eg: qbitorrent it creates a sonarr category, if I add it to that category how will sonarr know which series it is from?

**Comment by yasumitsuru** [comment]
@markus101 I did the test here and it worked, this already solves my problem, thank you very much
