### ISSUE TITLE
Update Script option for v4

### ISSUE THREAD

**Issue by rpx91** [Sonarr/Sonarr#5519]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I run two instances of Sonarr. When the main one tries to update it can't because the other one is also running. With v3 you had the option of running custom scripts on update - so I could shut the running version. Can you add that to v4?

### Describe the solution you'd like

Update script behaviour like previous versions

### Describe alternatives you've considered

Powershell scripts

**Comment by markus101** [comment]
Update scripts have only ever been supported when not running on Windows, we do not have plans to add them on Windows. https://github.com/Sonarr/Sonarr/issues/4790 is somewhat related
