### ISSUE TITLE
Add new "Change file date" option to apply to future files only, not existing

### ISSUE THREAD

**Issue by Silent-Remux** [Sonarr/Sonarr#5528]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This would be helpful to avoid unnecessary ffprobes in media apps if you change between "Local Air Date" and "Local UTC date". 

### Describe the solution you'd like

A tickbox to "apply to future imports only" (and not existing files) would help.

### Describe alternatives you've considered

Can't think of another option.

**Comment by markus101** [comment]
No plans to make changes around this feature, using a custom script that applies during import would be better suited for this customization.
