### ISSUE TITLE
Mono version of Sonarr v4

### ISSUE THREAD

**Issue by mreid-tt** [Sonarr/Sonarr#5530]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Since v4 we are including dotnet binaries and this is great! There are however some who are still running on old CPUs (e.g. ARMv7 and x86) who cannot run dotnet 6.x. These users are forced to stay with Sonarr v3 and not enjoy the latest features.

### Describe the solution you'd like

Would it be possible to include a version without dotnet which will still rely on mono? This release would live alongside the existing releases for ARMv8, ARM64 and x64. Would Sonarr v4 work with mono 6.x?

### Describe alternatives you've considered

We could try compiling dotnet for older CPUs (e.g. ARMv7 and x86) but this would be a challenge to maintain.

### Anything else?

I got the idea from looking at the Jackett [releases](https://github.com/Jackett/Jackett/releases) which seem to include a version for mono.

**Comment by markus101** [comment]
We've decided with v4 we will no longer support mono, while it may still be possible it's not something we will have releases for.
