### ISSUE TITLE
Add an option to ignore Quality rankings in favour of Custom Formats

### ISSUE THREAD

**Issue by natgreenwood** [Sonarr/Sonarr#5536]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have setup extensive quality profiles e.g.
+50 H265 1080p <1GB
+45 H265 1080P 1-2GB
+40 H264 1080P < 1GB
etc.

However when choosing between two releases as follows: 
File.Name.H265.HDTV1080p.nzb (1GB)
File.Name.H264.Bluray1080p.nzb (6GB)

Sonarr would pick the second, as my Quality order has Bluray 1080p above HDTV 1080p.

I appreciate before Custom Formats that quality was the only real choice, but with the fantastic feature that is Custom Formats we can choose between storage efficiency and quality based on the TV Series. However the Quality ranking over rules the custom formats in some scenarios.

### Describe the solution you'd like

Add a checkbox to prioritise Custom Format scores over Quality rankings/preferences.

OR

Make qualities part of the Custom Format scoring system.

### Describe alternatives you've considered

I have attempted to use differen combinations of custom formats and points allocations, but they are all over ruled by Quality.

**Comment by markus101** [comment]
You can already do this, just group all the qualities into one group, everything in the group is equal.
