### ISSUE TITLE
Add menu item to show application is running in MacOS X

### ISSUE THREAD

**Issue by jonathanwiesel** [Sonarr/Sonarr#554]
When using OSX, once the application is launched there's no way to know if it's actually running besides manually navigating to http://localhost:8989 or opening the Activity Monitor and look for the process.

I believe this would be a great and convenient addition.

**Comment by markus101** [comment]
There is a 3rd party extension for it already, which is probably about as close as you're going to get since Sonarr is run via mono as a command line application. We do plan to incorporate it as part of the OS X to make it more unified though: https://forums.sonarr.tv/t/sonarr-mac-helper-app/1418

**Comment by jonathanwiesel** [comment]
That's great, thanks
