### ISSUE TITLE
Clarify terminology RE: hardlinks for non-experts

### ISSUE THREAD

**Issue by KaiStarkk** [Sonarr/Sonarr#5542]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Appears to relate to #606, #4210, #1833, #3433, #4575, #4234, #2128, #738.

I came across this issue while trying to diagnose buffering from a media server (Jellyfin) that was trying to read from the same disk that Sonarr was furiously writing to during a copy from the torrent download client.

### Describe the solution you'd like

My suggestion is a description / tooltip or similar on the media management section to explain the meaning of hardlink / symlink.

For example (if this is correct):
```
In order to move your completed files rather than copying them (thereby reducing the number of disk I/O operations):
1. Check 'Use hardlinks' in Settings > Media Management > Importing
2. Check 'Remove completed' in Settings > Download Clients > [Your Client] > Completed Download Handling
```

### Describe alternatives you've considered

I've tried to propose the simplest solution.

An alternative (more complicated) would be to create a "Move" option in either of the above UI locations that ensures options are both selected correctly then disables them.

**Comment by markus101** [comment]
I don't think this directly relates to any of those issues you've linked.

Based on your example I'm not sure what exactly you're asking for as it seems more like you're looking for information on how you'd set up your system for hardlinks, versus what they actually are.

Hardlinks are not symlinks, and Sonarr will not create Symlinks. They also don't move files.

**Comment by KaiStarkk** [comment]
To clarify - everything is working fine for me now, this isn’t a technical bug, just a UX suggestion. My contention is that 99% of the population understands “copy” and “move” terminology, but the meaning of “hardlinks” is arcane. 

The tooltip I’m suggesting (when hovering over the word ‘hardlink’) would help dispel this. 

To carry home the point I’m a user since the beginning, and only just realised that I should have turned hardlinks on to prolong the lifespan of my hard drive by reducing unnecessary copying of inodes. I shudder to think of how many TB I’ve copied for no reason by having hardlinks switched off. 

The way that it relates to those previous issues is that in many cases the OP didn’t understand that what they wanted could be achieved with the existing hardlink option.

**Comment by markus101** [comment]
> The tooltip I’m suggesting (when hovering over the word ‘hardlink’) would help dispel this.

This would be somewhere between undiscoverable and annoying because people would either never hover over it or accidently hover it. Ignoring the UX concerns with your suggestion, I still don't know where you'd want more information to be added.

**Comment by KaiStarkk** [comment]
Good point, tooltip was a bad idea. Maybe just in the explainer text then per below?

![image](https://user-images.githubusercontent.com/1722064/231058506-4aaa85bc-84a3-4756-8a15-9f225a5f6702.png)

My post was verbose above but the concern boils down to "nobody knows what hardlinks are". Up to you but the evidence I can offer is that this comes up often enough:

![image](https://user-images.githubusercontent.com/1722064/231058664-d7fc5f00-d941-4c7b-8d6f-2e310bf8145d.png)
