### ISSUE TITLE
A way to change root path inside a show

### ISSUE THREAD

**Issue by Kedryn** [Sonarr/Sonarr#5544]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Every time i want to move a show i'm fixing, to another root path, or if i want to apply renaming to the folder name, i have to go back in main dashboard, search the show, use the multiselect to select it, then press the EDIT in the bottom and select the new or same root path, then apply

using the mass edit, but finding the show between thousands without using search (can't be used because it will open the show page, not filter the show list in dashboard), it's a pain

### Describe the solution you'd like

under the folder path inside a show edit window, i would like to have the same listbox as in the mass edit, to change the root path of that single show

### Describe alternatives you've considered

A button to rename the show folder, not the episodes. Will let rename the folder as per config, but no help in changing root folder if needed.

**Comment by Extremity** [comment]
Easy fix would be to have the suggested path populated beneath the folder naming field in the standard edit page when it detects you've changed the root folder location. For example, on Windows it would be as simple as seeing if the first character does not equal the initial value. If so, show a suggested input beneath of what a finalized path would be on that root drive, using the same method the mass editor uses.

So, I go to edit a show, I click the path entry field, and I change the root folder. A suggested full path appears beneath (like when suggestions appear when you're searching for something, you guys know what I mean) that you can ignore, or when clicked automatically populates the path field with the updated one.

In the meantime - you can't search in the mass editor, but filters still work. I have a filter set for each drive, that's an easy way to reduce the size of the list.
