### ISSUE TITLE
No way to search for anime 65447 on thetvdb

### ISSUE THREAD

**Issue by Kedryn** [Sonarr/Sonarr#5545]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have a folder named "See Me After Class (2012) [tvdb-65447]". I do an import, and it is found as "Beauty and the Beast (2012).
The real name is not found on the list of those proposed.
I tried with only the name, without year and tvdb id, but it found other non-related non-similar titles, but "See Me After Class" is nowhere to be found

if you go to thetvdb and search for "see me after class", there is only one result, the #65447

### Expected Behavior

That the show is found as any other show.

### Steps To Reproduce

Create a folder with name "See Me After Class (2012) [tvdb-65447]" or "See Me After Class" and try to import it.

### Environment

```markdown
- OS: unraid 
- Sonarr: 4.0.0.435
- Docker Install: yes from linuxserver.io
- Using Reverse Proxy: no
- Browser: chrome latest
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/11202468/sonarr.trace.txt)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

It's a movie...
![image](https://user-images.githubusercontent.com/413544/231223231-42d1045a-b86a-4d3a-80e1-eb05a10e2db3.png)
