### ISSUE TITLE
Option to use download client's native directory restructure.

### ISSUE THREAD

**Issue by somerandomguy24** [Sonarr/Sonarr#5549]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently if you want a proper structure for the episodes of a show on the filesystem, the only real option is to create hardlinks, which requires you to have one directory where shows are downloaded and another where the properly structured files are. This would not have all the issues with hardlinks, symlinks, copys and moves as mentioned in https://github.com/Sonarr/Sonarr/issues/967, with the only downsides being:
- Depends on download clients actually supporting this
- More complexity as different download clients may implement this differently

### Describe the solution you'd like

If you are using a download client that supports moving files within a directory (e.g. deluge), the option should be available for that download client.

### Describe alternatives you've considered

Using hardlinks like mentioned above. Moving files, but then I cannot seed. Copying files, doubles disk usage. Symlinks, headache to manage if you ever need to change anything.

**Comment by markus101** [comment]
We don’t have plans to support this in download clients. This is likely something achievable with https://github.com/Sonarr/Sonarr/issues/791 though.
