### ISSUE TITLE
Add an option to limit max number of downloads for each episode

### ISSUE THREAD

**Issue by YetAnotherDevWannabe** [Sonarr/Sonarr#5550]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The number of copies of each episodes as they get available is sometimes stupidly high (had 9 copies once within 2h).
Not everyone has unlimited space on their machine :)

### Describe the solution you'd like

It would really help if we could have an option to limit max number of downloads for each episode to avoid having the usual 6-7 copies of episodes as soon as they are out.

### Describe alternatives you've considered

-

**Comment by markus101** [comment]
We don’t have plans for such a feature, using the delay functionality could reduce the number of files that are actually grabbed though.

**Comment by YetAnotherDevWannabe** [comment]
The problem is, this really doesn't look like this is having the intended effect. I have a 1h delay and still get 2-4 copies every single time. For every single show.
Also to try and reduce the amount of possible copies any of my profiles have only 2 qualities activated but still.

**Comment by bakerboy448** [comment]
- fyi Delay is based on the release's age reported by the site
- v4 will also help with this with custom formats given the minimum custom format score and bypass for highest quality / bypass for above X score options
- for v3 adjust release profiles accordingly / v4 adjust custom formats accordingly to just target the releases you want
