### ISSUE TITLE
Add Pushsafer Notification Service

### ISSUE THREAD

**Issue by appzer** [Sonarr/Sonarr#5551]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

please add Pushsafer Notification Service

API description can be found here:
https://www.pushsafer.com/en/pushapi

### Describe alternatives you've considered

please add Pushsafer Notification Service

API description can be found here:
https://www.pushsafer.com/en/pushapi

**Comment by markus101** [comment]
Is there an advantage of Pushsafer over the plethora of options already present in Sonarr?
If there is user interest it's something we could look at adding, but it's unlikely we'll add it just because it's an option.

**Comment by markus101** [comment]
Closing as there doesn't appear to be interest in this currently.
