### ISSUE TITLE
[Feature Request] make a template for anime and shows

### ISSUE THREAD

**Issue by shifoc** [Sonarr/Sonarr#5552]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

have a default root folder for aniime and another for tv shows

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/32818143/231583592-15acb7ee-0879-4d29-b1e5-94783ee043fd.png)

Associate a root folder and quality profile based on the series type

### Describe alternatives you've considered

Have default values depending on tags

**Comment by markus101** [comment]
No current plans for this, but tagging to review in the future.
