### ISSUE TITLE
TVDB without Skyhook

### ISSUE THREAD

**Issue by tinyoverflow** [Sonarr/Sonarr#5558]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, all metadata fetching goes through Skyhook. Why is this? Wouldn't it be better for everyone to just be able to put in their API key and then let Sonarr directly connect to their database?

While [this Skyhook implementation](https://github.com/CmdrShepard/Skyhook) theoretically supports languages other than english, it just returns nothing when trying to call it with another language than english.

### Describe the solution you'd like

Being able to use TheTVDB without Skyhook.

### Describe alternatives you've considered

I don't think that your Skyhook is a great solution in the long run.

**Comment by PearsonFlyer** [comment]
That skyhook repo is entirely unrelated to Sonarr. It just happens to have the same name.

But there are no plans to move away from skyhook as the intermediate metadata server to tvdb.

**Comment by markus101** [comment]
Skyhook allows addition of data (time zone offsets is the big one), cleaning up data for all users without them needing to update Sonarr and probably the most important thing, TheTVDB API access without needing to provide their own key and pay for access.

That doesn’t come without it’s downsides in that we need to upgrade it to support multiple languages or alternative orders.

In short it wouldn’t be better to require every user to provide their own access to TheTVDB.

**Comment by tinyoverflow** [comment]
I do understand that. Especially the part about paying for API access. What about open-sourcing Skyhook then? It would allow for user contributions eg. for additional languages or features. The request to support other languages exists for around 8 years now, see #269. It got the blocked-by:skyhook label and has a medium priority.

What is the reason that this hasn't been done before? I would really love to contribute to this, if possible.

Adding support for alternative providers, like TMDB, would also be an option. TMDB, for example, does require an API key, but it is completely free. Synologys VideoStation uses that and it also requires the user to enter an API key. I think that this is pretty doable for the average user of Sonarr. TMDB has also a ton of TV-series listed.

Sonarr also implemented the UI localization framework of Radarr (#749) back in 2021, but it just has these 4 strings translated. But the ticket for this also exists since 2015. Doing this is not really hard, but tedious and repetitive. Would a PR for this be accepted?

**Comment by markus101** [comment]
I’ve answered why not open source on Reddit recently: https://www.reddit.com/r/sonarr/comments/11azkqn/who_owns_skyhook/j9vmisc/

Once support is added to Skyhook people will be able to contribute to the Sonarr portion of it.

Alternative metadata sources come with their own issues and support requirements, adding those in would need to be done with the limitations and concerns in mind.

Not sure where the number 4 came from, I’m seeing more than that, but regardless a lot more need to be. If someone wants to open a PR for that, it will be reviewed and accepted if appropriate.
