### ISSUE TITLE
urlbase function for transmission

### ISSUE THREAD

**Issue by sigboe** [Sonarr/Sonarr#556]
![capture2](https://cloud.githubusercontent.com/assets/2087930/7772458/9a5da49c-009e-11e5-9be0-4aa0f0a1bb95.PNG)

when entering an URLbase sonarr just adds the urlbase i entered in additon to the default urlbase.

**Comment by markus101** [comment]
That is expected. It is there to support seedboxes that have a URL base in addition to the transmission folder.

Are you using a reverse proxy to rewrite the entire URL?

**Comment by sigboe** [comment]
No, I am not using reverse proxy to rewrite the url, my urlbase setting in transmission is 
```
"rpc-url": "/torrent/",
```

And yes I am using a reverse proxy, but this does not go trough that.

**Comment by markus101** [comment]
@Taloth I think we need to do a migration to support a custom `rpc-url` (or for people with Url Base already set we would need to append transmission to the end). Thoughts?

**Comment by sigboe** [comment]
This ought to be documented by transmission. Because I do believe
transmission is very strict about the url and that it would never work with
address:port/something/transmission/rpc

Without the transmission rpc-url setting set to "/something/transmission/"

Except if it is possible to move the rpc file structure to the webserver
directory in folder "something". And that would be very bad practice.

**Comment by Taloth** [comment]
Maybe markus, but the urlbase was never made for rpc-url changes, it was made for seedbox reverse proxies.
I'm fine with a migration though, as long as the tooltip is updated too.
