### ISSUE TITLE
Search by query when advanced capabilities are missing

### ISSUE THREAD

**Issue by 2omsnF** [Sonarr/Sonarr#5562]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some trackers do not support season & ep parameters. In these cases, all that happens is that `Debug|NewznabRequestGenerator|Indexer capabilities lacking season & ep query parameters, no Standard series search possible.` is logged.

### Describe the solution you'd like

It would be nice if Sonarr gracefully fell back to the `q` capability in these cases, following common conventions:

- Season search: `<Show name> S01`
- Episode search: `<Show name> S01E01`

Alternatively, if just the `imdbid` was supported by the indexer, it would be nice if Sonarr instead searched with just the `imdbid` and then further filtered the results.

### Describe alternatives you've considered

The next best solution here is to emulate the season & ep parameters in the Jackett configuration.

**Comment by thezoggy** [comment]
what site do you see this with?

curious to know if you were trying to add a non newznab or modified newznab site to sonarr / if it is a variant of nn, nzedb/nntmux? as some sites also augment their caps page to not leak info from it.

**Comment by 2omsnF** [comment]
I'm connecting to UHDBits through Jackett. Jackett remaps the advanced search functionality (html form) on UHDBits into Torznab format.

Here's my caps query response from Jackett:

```
<?xml version="1.0" encoding="UTF-8"?>
<caps>
  <server title="Jackett" />
  <limits default="100" max="100" />
  <searching>
    <search available="yes" supportedParams="q" />
    <tv-search available="yes" supportedParams="q,season" />
    <movie-search available="yes" supportedParams="q,imdbid" />
    <music-search available="yes" supportedParams="q" />
    <audio-search available="yes" supportedParams="q" />
    <book-search available="no" supportedParams="q" />
  </searching>
  <categories>
    <category id="2000" name="Movies" />
    <category id="3000" name="Audio" />
    <category id="5000" name="TV" />
    <category id="100001" name="Movies" />
    <category id="100002" name="Music" />
    <category id="100003" name="TV" />
  </categories>
</caps>
```

I've also checked the advanced search page on UHDBits & confirmed that it doesn't support episode number search (or season number search, which is odd because Jackett reports support for that)

**Comment by markus101** [comment]
Based on your PR to Jackett the issue is `no single episodes allowed on this tracker, so it's ignored`, Jackett is reporting season support, but Sonarr is requiring both, even for season searches. I think we can improve that check for season searches so they're allowed, but individual episode searches are rejected.
