### ISSUE TITLE
Sonarr segfaults / coredumps on getting media info with libmediainfo v23.03

### ISSUE THREAD

**Issue by UbiquitousPhoton** [Sonarr/Sonarr#5565]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr core dumps on trying to get media info with libmediainfo0 v23.03 (released 2023-03-29 : https://github.com/MediaArea/MediaInfo/releases/tag/v23.03)

This will either happen during initial scan (should any information be missing about current files) or during import of a new release. Once it has happened, unless the library is removed, it will then happen 100% on boot of Sonarr from that point on. This is not, unfortunately an unavoidable bug on those systems with upgraded libmediainfo.

These problems go away with a downgrade of libmediainfo to v22.12

### Expected Behavior

Sonarr should not segfault on calling libmediainfo v23.03 (behaviour should be the same as with v22.12)

### Steps To Reproduce

See above. Cause Sonarr to try and get media info for a file - the easiest way to do this is to download a new release of something, and Sonarr will segfault and coredump.

### Environment

```markdown
- OS: OpenSuse Tumbleweed
- Sonarr: 3.0.9.1549-4.7 (also reproduced with 3.0.10 on Fedora)
- Docker Install: n/a
- Using Reverse Proxy: Nginx (but N/A, not browser issue)
- Browser: N/A (browser does not need to be attached to cause crash)
```

### What branch are you running?

Main

### Trace Logs?

Trace log shows no issues, it will generally just stop dead, after something along the lines of the following:

```
2023-04-14 02:26:20.3|Debug|ImportDecisionMaker|Analyzing 1/1 files.
2023-04-14 02:26:20.3|Debug|Parser|Parsing string 'Station.19.S06E14.720p.HDTV.x264-SYNCOPY'
2023-04-14 02:26:20.3|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
2023-04-14 02:26:20.3|Debug|Parser|Episode Parsed. Station 19 - S06E14
2023-04-14 02:26:20.3|Debug|Parser|Language parsed: English
2023-04-14 02:26:20.3|Debug|QualityParser|Trying to parse quality for Station.19.S06E14.720p.HDTV.x264-SYNCOPY
2023-04-14 02:26:20.3|Debug|Parser|Quality parsed: HDTV-720p v1
2023-04-14 02:26:20.3|Debug|Parser|Release Group parsed: SYNCOPY
2023-04-14 02:26:20.3|Debug|VideoFileInfoReader|Getting media info from /home/(removed)/.sabnzbd/downloads/complete/Station.19.S06E14.720p.HDTV.x264-SYNCOPY/b8ef54b3cda8455bbb65814bb94a2e13.mkv
```
I can provide further trace logs on request, but there are no errors whatsoever reported there prior to crash.

### Anything else?

Pulling the stack trace from the journal gives always the same trace:

```
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================
=================================================================
        Native stacktrace:
=================================================================
        0x55e480b77cd0 - /usr/bin/mono :
        0x55e480b78079 - /usr/bin/mono :
        0x55e480b26e71 - /usr/bin/mono :
        0x55e480b7189d - /usr/bin/mono :
        0x7ff21af68476 - /lib64/libmediainfo.so.0 :
=================================================================

at <unknown> <0xffffffff>
at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo:MediaInfo_Open_Buffer_Continue <0x000b8>
at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo:Open <0x000ff>
at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader:GetMediaInfo <0x00293>
at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader:GetRunTime <0x0004f>
at NzbDrone.Core.MediaFiles.EpisodeImport.DetectSample:IsSample <0x0016d>
at <>c__DisplayClass14_0:<GetNonSampleVideoFileCount>b__0 <0x00050>
at System.Linq.Enumerable:Count <0x000c8>
at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker:GetNonSampleVideoFileCount <0x001af>
at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker:GetImportDecisions <0x001c3>
at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker:GetImportDecisions <0x0005f>
at NzbDrone.Core.MediaFiles.DownloadedEpisodesImportService:ProcessFolder <0x0044c>
at NzbDrone.Core.MediaFiles.DownloadedEpisodesImportService:ProcessPath <0x000ef>
at NzbDrone.Core.Download.CompletedDownloadService:Import <0x0010e>
at NzbDrone.Core.Download.DownloadProcessingService:Execute <0x002b0>
at NzbDrone.Core.Messaging.Commands.CommandExecutor:ExecuteCommand <0x00210>
at System.Object:CallSite.Target <0x00122>
at System.Dynamic.UpdateDelegates:UpdateAndExecuteVoid3 <0x001bc>
at System.Object:CallSite.Target <0x00191>
at NzbDrone.Core.Messaging.Commands.CommandExecutor:ExecuteCommands <0x0032f>
at System.Threading.ThreadHelper:ThreadStart_Context <0x000aa>
at System.Threading.ExecutionContext:RunInternal <0x00191>
at System.Threading.ExecutionContext:Run <0x00042>
at System.Threading.ExecutionContext:Run <0x00063>
at System.Threading.ThreadHelper:ThreadStart <0x00042>
at System.Object:runtime_invoke_void__this__ <0x00091>

```
It is definitely the libmediainfo thread that is the one crashing. I installed lldb in order to give full native traces, but this gave no further help as to the site of the crash. I would strongly suspect that the reason is that libmediainfo 23.3 is not API/ABI compatible with the version you built the releases against.

**Comment by thezoggy** [comment]
There is already an issue on mediainfo about this. You can just downgrade package to fix your side. 

Additional, sonarr v3 no longer has been actively developed since v4 has been the main focus for a bit now. Which Sonarr v4 no longer uses mediainfo and instead switched to ffprobe (just like radarr v4 uses).

**Comment by UbiquitousPhoton** [comment]
I have rolled back for now, but given how utterly blocking this bug is, you may very much want to at least keep this issue pinned, as you don't have one here (preferably pointing at https://github.com/MediaArea/MediaInfo/issues/707). Posting asking for help on your Forums only confirmed that other people had the same issue, so I reported here.

I know that v4 is the future, however it has not been (officially) released yet, so migration to it is unlikely to happen for most people just yet, nor really for a while to come, so it doesn't make sense to just completely abandon V3 just yet.

**Comment by markus101** [comment]
Mediainfo 23.04 is now available.
