### ISSUE TITLE
Change default Multi-Episode style to be compatible with plex

### ISSUE THREAD

**Issue by chrisdecker08** [Sonarr/Sonarr#5572]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Plex does not (and will not) recognize the Extend Multi-Episode Style.  While it is easy to change the setting to one plex will recognize it would be nice if it worked right out of the box.

### Describe the solution you'd like

Make the default Multi-Episode Style Prefixed Range, this is supported by plex and its competitors.

### Describe alternatives you've considered

Adding support for the Extended Multi-Episode format in plex has led to many false positives 'DancingWiththeStars-S16E08-10426008-0.mkv', 'Futurama-S07E12-31st_Century_Fox-[Bluray-1080p].mkv', 'FamilyGuy-S12E13-3_Acts_of_God.mkv', ect

**Comment by thezoggy** [comment]
just change the "Multi-Episode Style" to what option works for you. not everyone uses plex

**Comment by chrisdecker08** [comment]
Not everyone uses plex but why would you not have a default that works with most if not all major platforms?  Also, the naming scheme isn't what I use but real world use cases in our attempt to support this style in plex.

**Comment by markus101** [comment]
I'm not opposed to changing the default, but at least in Sonarr supporting that format is not too much of a burden. Of the 3 problematic examples here the only one that failed is `Futurama-S07E12-31st_Century_Fox-[Bluray-1080p].mkv`, which was a small issue to address.

**Comment by thezoggy** [comment]
"Scene" should be the default, which i thought it already was?
