### ISSUE TITLE
Monthly Calendar View Today link should scroll to today

### ISSUE THREAD

**Issue by stuart-elliott-70** [Sonarr/Sonarr#5574]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

In the monthly calendar view, if you press TODAY, it only takes you to the beginning of the current month.

### Describe the solution you'd like

Ideally, it should take you to the current date, via a # anchor presumably.

### Describe alternatives you've considered

None, sorry.

**Comment by markus101** [comment]
For the implementation

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView or a bespoke method to scroll today into view would be more appropriate.
