### ISSUE TITLE
Keep subtitle types (forced, sdh, hi) in tact when importing

### ISSUE THREAD

**Issue by Hansaplast** [Sonarr/Sonarr#5577]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Issue: On manual import, subtitle types like "forced", "sdh" and "hi" are stripped from the filename and replaced with numbers 1, 2, 3, etc. 

Example, original files:

- xyz.**en**.srt
- xyz.**en.forced**.srt
- xyz.**en.sdh**.srt
- xyz.**en.hi**.srt

After import these files are now:

- abc.**1.en**.srt
- abc.**2.en**.srt
- abc.**3.en**.srt
- abc.**4.en**.srt

### Describe the solution you'd like

I'm sure this works as designed, but ideally one would want to keep these types indicators, since most media players actually use this (KODI, JellyFin, etc) so the viewer can select the proper subtitle.

Example:

- abc.**en**.srt
- abc.**en.forced**.srt
- abc.**en.sdh**.srt
- abc.**en.hi**.srt

### Describe alternatives you've considered

1) Under **Media Management**, **Import Extra Files**, I've tried an import with this set of file extensions:

`.en.forced.srt, .en.sdh.srt, .en.hi.srt, .en.srt, .srt`

Unfortunately this did not work, and resulted in the same filenames with numbers.

2) Next I tried only using these file extension (removed "**.srt**"):

`.en.forced.srt, .en.sdh.srt, .en.hi.srt, .en.srt`

Unfortunately now none of the SRT files get imported.

3) Considered running a custom script (under **Connect** - Add Custom Script).

Unfortunately there are no variables that can assist with this ([source](https://wiki.servarr.com/en/sonarr/custom-scripts)).

4) Tried running manual renaming scripts.

Unfortunately, it seems the order of the produced numbers is not consistent. 
Number 1 (.1.en.srt) could be ".en.srt", but could also be ".en.forced.srt", and with the next import this order can be different again.

### Anything else?

OS: Linux (QNAP)
Sonarr Version: 3.0.10.1567
Mono Version: 6.12.0.122

**Comment by augustuen** [comment]
I'm pretty sure this is related to Radarr/Radarr#7710, in which case I'll get a fix in in an hour or so.

**Comment by Hansaplast** [comment]
I'm sorry to say that I'm running v3. 
Not sure how to test this with v4 without potentially causing issues with my v3 setup (QNAP NAS).
On that note: I'm not even sure how to test the fix that **augustuen** provided impressively quick.

**Comment by augustuen** [comment]
> does this problem happen in v4?
> 
> sdh/forced/etc should be kept: https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Parser/LanguageParser.cs#L28

I verified that the issue still exists in V4 and in the current develop. 

Steps to reproduce:

* Add a subtitle file with one of the affect tags to an existing series (ex: `Loudermilk - S01E01 - A Girl in Trouble Is a Temporary Thing WEBDL-1080p.no.forced`) 
* Refresh the series to make Sonarr pick up the new subtitle
* Trigger a rename
* See the tag disappear from the filename

It only happens when you add a subtitle _after_ imports. If the file is import alongside the video files the tags are kept, even in future renames.

**Comment by thezoggy** [comment]
iirc, manually modifying subtitles wont be retained as that info has to be learned during import so it keeps track what is what. just like if you added a random blurp to ep title then rename.. its going to get discarded since its not coming from the db

**Comment by augustuen** [comment]
That's true for episode files, but I propose that subtitles are a special case. They're more likely to get added after import (either by users or tools like Bazarr) don't have the same information/need for information as episodes do, and we're already checking the language of existing files when importing them.

**Comment by Hansaplast** [comment]
> Does this issue apply to subtitle files that were imported with the original episode files?

Apologies - Somehow overlooked and forgot to answer this question.

With v3 this happens when importing the subtitles together with the original episode.
I have not tried a manual import after an episode had already been imported.
After refreshing a show, the subtitle filenames remain unchanged (forced, sdh, hi etc still in tact).
