### ISSUE TITLE
Option to not automatically redownload if failed attempt was interactive search

### ISSUE THREAD

**Issue by ThioJoe** [Sonarr/Sonarr#5580]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

In the Download Clients menu > "Redownload Failed" option, if this is enabled, it apparently will always try to redownload, whether the download attempt was an automatic search or manual. But if I'm doing a manual search ("interactive search") in the first place, I want control over which version is downloaded.

### Describe the solution you'd like

Add separate options for redownloading of automatic vs manual searches. 

### Describe alternatives you've considered

Maybe an option specific to a show

### Anything else?

I was having trouble with a specific episode of a show failing for multiple releases. I manually tried a release, which failed, then the software kept repeatedly initiating new downloads while I was trying to find a better one.

**Comment by augustuen** [comment]
I think making it an option is unnecessary - a manual grab is manual, and is as you say done manually for a reason. I think most users would expect/want manual grabs to not be replaced by an automatic one. Would also be a good fit with a fix for #3955.

**Comment by ThioJoe** [comment]
Yea that would make sense as well

**Comment by markus101** [comment]
I disagree, not everyone cares to manually control a replacement even though they grabbed something with interactive search.

**Comment by CLHatch** [comment]
> I disagree, not everyone cares to manually control a replacement even though they grabbed something with interactive search.

Yeah, myself I usually do a manual grab just to get the "best" copy available at the time. If I want to be sure it's not replaced later I'll just unmonitor the episode.
