### ISSUE TITLE
Sonarr does not restart after updating to version 2.0.0.3154

### ISSUE THREAD

**Issue by preginald** [Sonarr/Sonarr#559]
Hey there. Here is my systemd log for my sonarr.service.

As you can see, the update file is downloaded and extracted but when sonarr goes to  restart it throws a "main process exited, code=killed" error.

When I start the sonarr.service manually sonarr starts but is still showing Sonarr Ver. 2.0.0.3004 and there is a System message that there is a new version available. 

I am using linux arch linux and have made sure "/usr/bin/sonarr" and "/usr/lib/sonarr" are owned by the sonarr user.

Can anyone suggest a fix for this upgrade issue? Cheers.

● sonarr.service - Sonarr Daemon
   Loaded: loaded (/usr/lib/systemd/system/sonarr.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Sun 2015-05-24 19:48:46 AEST; 246ms ago
  Process: 22379 ExecStart=/usr/bin/mono /usr/lib/sonarr/NzbDrone.exe -nobrowser (code=killed, signal=KILL)
 Main PID: 22379 (code=killed, signal=KILL)
   CGroup: /system.slice/sonarr.service

May 24 19:48:43 xps mono[22379]: [Info] InstallUpdateService: Update package verified successfully
May 24 19:48:43 xps mono[22379]: [Info] InstallUpdateService: Extracting Update package
May 24 19:48:44 xps mono[22379]: [Info] InstallUpdateService: Update package extracted successfully
May 24 19:48:44 xps mono[22379]: [Info] BackupService: Starting Backup
May 24 19:48:45 xps mono[22379]: [Info] InstallUpdateService: Preparing client
May 24 19:48:45 xps mono[22379]: [Info] InstallUpdateService: Starting update client /tmp/nzbdrone_update/NzbDrone.Update.exe
May 24 19:48:45 xps mono[22379]: [Info] InstallUpdateService: Sonarr will restart shortly.
May 24 19:48:46 xps systemd[1]: sonarr.service: main process exited, code=killed, status=9/KILL
May 24 19:48:46 xps systemd[1]: Unit sonarr.service entered failed state.
May 24 19:48:46 xps systemd[1]: sonarr.service failed.

**Comment by delphiactual** [comment]
Please post your sonarr.service file from systemd

**Comment by markus101** [comment]
Please use the [forums](https://forums.sonarr.tv/) for support.
