### ISSUE TITLE
Feature Request: add an optional task for renaming all files after interval

### ISSUE THREAD

**Issue by shifoc** [Sonarr/Sonarr#5597]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

some episode titles are tba at first so it would be nice if they could get renamed once the name is available

### Describe the solution you'd like

some episode titles are tba at first so it would be nice if they could get renamed once the name is available

### Describe alternatives you've considered

none

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/issues/1118 is a bit more broad than just scheduling renames, but this falls under that.
