### ISSUE TITLE
Could not set profile language in 4.0.0.445

### ISSUE THREAD

**Issue by Zheaoli** [Sonarr/Sonarr#5599]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Could not set profile language in 4.0.0.445

![image](https://user-images.githubusercontent.com/7054676/235339607-46593134-657c-4b98-9809-1f8f6078c763.png)

### Expected Behavior

Can set language in profile setting and can set language for series monitoring

![image](https://user-images.githubusercontent.com/7054676/235339675-b830960f-2b3b-4980-a446-bd22d0a43faa.png)

### Environment

```markdown
- OS: Linux
- Sonarr: 4.0.0.445
- Docker Install:Yes
- Using Reverse Proxy:No
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

None

**Comment by thezoggy** [comment]
v4 does not have language profile, you now use custom format to prefer languages
https://wiki.servarr.com/sonarr/faq-v4#where-have-language-profiles-gone

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) if you have additional questions.
