### ISSUE TITLE
Add quality to series/episode information overview

### ISSUE THREAD

**Issue by PearsonFlyer** [Sonarr/Sonarr#5614]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When viewing a series, there are many columns available for information that is taken from the current file you have for a given episode. For some reason, quality (quality/resolution) is not one of them, and it seems like it should definitely be.

### Describe the solution you'd like

Add a column for quality to the selection box and display that information on the series overview. Here is an image showing what I mean:

![image](https://user-images.githubusercontent.com/15488393/235686512-68a49180-1dc6-48d2-88e8-afd0cb41f57d.png)

### Describe alternatives you've considered

The only way currently is clicking on each episode and seeing the quality for the file.

### Anything else?

It seems like that used to be there, but is gone now? I can't remember.

**Comment by markus101** [comment]
It’s shown under the status column when there is a file.

**Comment by PearsonFlyer** [comment]
Thank you, that's why I didn't see it. I knew it used to be there! :)
