### ISSUE TITLE
Don't search on list import when monitoring is set to none

### ISSUE THREAD

**Issue by edrock200** [Sonarr/Sonarr#5615]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I was excited to see the new "import from another sonarr based on root path" feature and setup a list accordingly, but set monitor to "None." 

Upon importing, it appears to still kick off a search for episodes though. 

### Describe the solution you'd like

When monitoring is set to none, do not kick off a search. 

### Describe alternatives you've considered

Manually killing search tasks

**Comment by markus101** [comment]
This is already the done, if the monitor type is set to None when adding a search is not performed.

https://github.com/Sonarr/Sonarr/blob/ca8b26138e3ebd793cc1a5fd51522ce3eda8a2e1/src/NzbDrone.Core/ImportLists/ImportListSyncService.cs#L128-L146

**Comment by edrock200** [comment]
OK, thank you. Let me re-enable the list, maybe I screwed something up. My apologies.
