### ISSUE TITLE
urlBase Undefined

### ISSUE THREAD

**Issue by jandreaucodes** [Sonarr/Sonarr#5624]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When loading Sonarr over a custom domain, console shows `cannot read properties of undefined (reading 'urlBase')`

The UI, after login, is a blank white screen. No errors in logs.

If I load the UI over localhost, it works perfectly.

### Expected Behavior

Sonarr works on a custom domain.

### Steps To Reproduce

1. In macOS, run Sonarr with a custom domain.
2. See that you're unable to use the UI.

### Environment

```markdown
- OS: macOS 13.2.1
- Sonarr: 3.0.10.1567
- Using Reverse Proxy: Yes
- Browser: All
```

### What branch are you running?

Main

### Trace Logs?

N/A

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
