### ISSUE TITLE
Organize & Rename Issue with trickplay subfolder - Sonarr 3.0.10.1567

### ISSUE THREAD

**Issue by sunnyd24** [Sonarr/Sonarr#5634]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When manually renaming a Series using "Preview Rename" it brings up the dialog box for the preview and shows all files renamed correctly, but also behind the scenes it also renames and moves other files to the season folder that include the same file name. 

The expected file formats for auto rename by Sonarr are video files (mkv, mp4, etc.), subtitles (srt, etc.), nfo files, etc.
There are also new files generated by Jellyfin, JellyScrub plugin that generate '-320.bif' and '-manifest.json' files using the filenames generated by Sonarr in a "trickplay" folder within each season, see below for structure:

Series Folder 1
->Season 1
----->Series Title - 1x01 - Episode 1 (Bluray-1080p).mkv
----->trickplay
 -------->Series Title - 1x01 - Episode 1 (Bluray-1080p)-320.bif
 -------->Series Title - 1x01 - Episode 1 (Bluray-1080p)-manifest.json

I now want to change the series naming convention to be "Series Title - 1x01 - Episode 1 (Bluray-1080p)" to "Series Title - 1x01 - Episode 1 - [Bluray-1080p]", and this works for all video files, subtitles and nfo files, but also for .bif and .json files which is ok, but they remove the appended "-320" and "-manifest" from the two file types .bif and .json, respectively.

So now after rename the folder and file structure looks like this in error:

Series Folder 1
->Season 1
----->Series Title - 1x01 - Episode 1 - [Bluray-1080p].mkv
----->Series Title - 1x01 - Episode 1 - [Bluray-1080p].bif
----->Series Title - 1x01 - Episode 1 - [Bluray-1080p].json
----->trickplay
-------->empty folder

### Expected Behavior

I am expecting Sonarr to rename the files in sub-folders including within subfolders (trickplay folder) but **keeping any appended text in filename**, and **not** moving it to the same location as video file, and **leaving it in the folder it was found**.

Series Folder 1
->Season 1
----->Series Title - 1x01 - Episode 1 - [Bluray-1080p].mkv
----->trickplay
-------->Series Title - 1x01 - Episode 1 - [Bluray-1080p]-320.bif
-------->Series Title - 1x01 - Episode 1 - [Bluray-1080p]-manifest.json

### Steps To Reproduce

1. Windows 11 with Sonarr v3.0.10.1567
2. Library already set up with multiple series within naming convention:
`{Series Title} - {season}x{episode:00} - {Episode Title} ({Quality Title})`
3. In Jellyfin using the Jellyscrub plugin to generate bif/json files for all videos in library
4. Change naming convention for series to:
`{Series Title} - {season}x{episode:00} - {Episode Title} - [{Quality Title}]`
5. Click on a series that you want to change to new naming convention
6. Click "Preview Rename"
7. Click "Organize"
8. Filenames and folder structure changes as described in current behaviour above
9. Requires manual moving of files back into trickplay folder from season folder and rename of .bif and .json files to append -320 and -manifest, respectively.

### Environment

```markdown
- OS: Windows 11
- Sonarr: 3.0.10.1567
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Edge/Chrome
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.33.txt](https://gist.github.com/sunnyd24/cb6dc1a2871c61318ac8f6c165fb5e5e)

**Comment by markus101** [comment]
Duplicate #5217
