### ISSUE TITLE
Simkl Anime List integration

### ISSUE THREAD

**Issue by funforgiven** [Sonarr/Sonarr#5635]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I believe that adding support for Simkl was a great idea. However, Simkl separates Anime and TV shows so it would be beneficial to be able to import Anime list from Simkl as well, as Sonarr already supports anime.

### Describe the solution you'd like

One potential solution could be to provide an option within the Import Lists feature, specifically in the Simkl User Watchlist section, to allow users to selectively import their desired media list, whether it be for TV Shows or Anime. Given the apparent similarity between the APIs of TV Shows and Anime, this implementation should prove to be relatively straightforward.

https://simkl.com/
https://simkl.docs.apiary.io/#

### Describe alternatives you've considered

N/A

#### Issue and pull request for Simkl List integration for TV Shows:
#5306
#5313

**Comment by thezoggy** [comment]
sonarr uses tvdb, which is why simkl list support for 'tv' was added (as they use tvdb). for sonarr to add 'anime' list would require sonarr to add anidb support which it does not do.

**Comment by funforgiven** [comment]
To my understanding, they also offer tvdb support for anime.

I have observed [an example in their API documentation](https://simkl.docs.apiary.io/#introduction/about-simkl-api/standard-media-objects), where they provided a tvdb id for an anime.

This is the example in their documentation:

```
{
    "title": "Attack on Titan",
    "year": 2013,
    "ids": {
        "simkl": 39687,
        "mal": 16498,
        "tvdb": 267440,
        "imdb": "tt2560140",
        "anidb": 9541
    },
    "seasons":[ 
        {
            "number": 2
        }
    ]
}
```

Are there some animes that do not provide tvdb ids?

**Comment by ShubhamPatilsd** [comment]
I would like to reserve this issue for our students over at [CodeDay Labs](https://labs.codeday.org/) during our summer session.

A bit about CodeDay Labs:

> CodeDay Labs provides “micro-internships” for college students. This means working on real issues on real-world projects. The best part about this is that we’re helping the open source community at the same time by providing opportunities for these students to work on open-source projects.

**Comment by jtnguyen45** [comment]
I am working on this from CodeDay Labs.
