### ISSUE TITLE
Radarr Backports

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#5637]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Various downstream changes and improvements exist that were never backported

### Describe the solution you'd like

Align Radarr and Sonarr HealthChecks and other logic

- [ ] Add ProviderAddedEvent
- [ ] Add Missing HealthCheck Wiki Fragments
- [ ] Add filterBlockedClients to Download Clients
- [ ] Add missing check on healthcheck conditions
- [ ] Cleanup various upstream healthcheck logic that was done downstream
- [ ] correct DownloadClientProvider logging for downstream
- [ ] review and correct ImportListRootFolderCheck for downstream

### Describe alternatives you've considered

Continue misalignment with downstream

### Anything else?

#5594  has the diff, but someone will need to go through 4 years of radarr commits to cherry-pick every single change as per markus's request.

**Comment by markus101** [comment]
That's not what I said, I asked you to split _your_ commit_ so you're not putting 6 different pieces of work into a single commit. When asked to split them up you created new commits for the changes, marked questions as resolved without commenting and said you weren't going to split up the commit. After I asked again and provided instructions on how to do it your response was to close your PR and open this issue.

**Comment by markus101** [comment]
All but one (in PR) has landed.
