### ISSUE TITLE
Trakt Recommended

### ISSUE THREAD

**Issue by ac1dburnz** [Sonarr/Sonarr#5639]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

i would like to pull recommended movies from Trakt

### Describe the solution you'd like

I want to be able to based of Tv shows from https://trakt.tv/shows/recommended/ 

### Describe alternatives you've considered

I can’t think of any

**Comment by stevietv** [comment]
then all you need to do is add an "import list" in Sonarr. this isn't something for a GitHub issue - feel free to join our [Discord](https://discord.gg/M6BvZn5) for support
