### ISSUE TITLE
Custom Formats: Add Media Info Conditions

### ISSUE THREAD

**Issue by owine** [Sonarr/Sonarr#5645]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

#5598 

### Describe the solution you'd like

Instead of relying on some combination of release/file name to determine CFs, add conditions that use the media info that is probed from files on disk. For parsing releases, a regex match is provided which utilizes the existing release name logic. However, if a file exists on disk, the regex is completely ignored in favor of the media info for the file. The two are paired together in the CF condition (see below mockup)

Some examples of media info conditions (ideally all of the probed and stored data is made available):
Audio/Video Codec
Video Dynamic Range
Video Dynamic Range Type
Subtitles

### Describe alternatives you've considered

Per the discussion in #5598 there are a number of inelegant things. I am of the opinion that it is not Sonarr's job to address improperly or poorly named releases (although some sort of general download loop protection would be nice)

### Anything else?

![image](https://github.com/Sonarr/Sonarr/assets/4283702/fefdd66f-8926-448f-8728-a3de8e2d3450)

Mockup courtesy of @nuxencs

**Comment by markus101** [comment]
Let’s keep the discussion in #5598 and not jump to different solutions until everything has been hashed out.
