### ISSUE TITLE
sonarr can not automatically import the first season of Bleach

### ISSUE THREAD

**Issue by PN62323424** [Sonarr/Sonarr#5649]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I changed the series type to anime, and then downloaded the first season of bleach, which is a total of 366 episodes, but after downloading, only the first season can be imported automatically. I checked that the downloaded files are named like S1E1 through S1E366.

### Expected Behavior

11

### Environment

```markdown
- OS: synology
- Sonarr:V4
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

11

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

I'm seeing no issues with this naming, though you're missing critical information if you truly think this is a bug.
![image](https://github.com/Sonarr/Sonarr/assets/413544/f13c3a50-cf2d-42e8-b718-02dec00d55de)
![image](https://github.com/Sonarr/Sonarr/assets/413544/52c28bb8-dfdb-4311-85ca-a976812f354d)
