### ISSUE TITLE
Capture Known Indexer HTTP Errors and Provide Better Messaging to users

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#5658]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Indexer servers may be down and generic "unable to connect to indexer xxxxxx" messaging is not clear to users that the server is unavailable.

### Describe the solution you'd like

- Add IsServerNotAvailable bool to HTTPResponse for common server is down codes like 502, 504, 503, 522, 524
- Improve ValidationFailure and Logging messaging to indicate that the server is not available

### Describe alternatives you've considered

Continue to provide users with technical errors that users don't understand

### Anything else?

Similar to https://github.com/Prowlarr/Prowlarr/pull/1666/files

Expect this to be closed per https://github.com/Prowlarr/Prowlarr/pull/1666#discussion_r1197831516 as it appears there was no upstream appetite for this.

**Comment by markus101** [comment]
If that PR adds value why was it closed? I'm not sure in what context "upstream" didn't want a change and why you brought a passive aggressive attitude to your comment in anything else.
