### ISSUE TITLE
Option to refresh sideloaded metadata (jpg, nfo, plexmatch, etc) on schedule vs daily

### ISSUE THREAD

**Issue by edrock200** [Sonarr/Sonarr#5659]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When enabling sideloaded data such as emby nfo files and poster/background/etc jpgs, Sonarr appears to refresh this data on the daily scans. In addition to causing a significant amount of metadata downloads, when media apps such as emby sees the modify date on an nfo or jpg change, it reprocesses that data, causing a singnificantly longer scan time.

The same appears to apply with Plex and plexmatch/jpg files.

### Describe the solution you'd like

Add a refresh interval which applies if metadata already exists, e.g.:
If metadata exists refresh every:
Never
1 week
1 month
3 months
6 months
1 year
Or whatever intervals seem appropriate.

### Describe alternatives you've considered

Presently I turn this option off, enable once a month, refresh all, disable again.

### Anything else?

Appreciate the consideration.

As I know code is sometimes shared between sonarr and radarr, I am noting a similar radarr request I made here:
https://github.com/Radarr/Radarr/issues/8536

**Comment by markus101** [comment]
Sonarr doesn't update images if a file with the same name on disk already exists. For series/episode metadata (nfo, Plex match, etc) Sonarr doesn't update the metadata if the hash for the file contents remains the same.

Unless metadata is constantly changing and which with rating not being something TheTVDB tracks anymore this is largely shouldn't be an issue.

At this time we don't have plans to only update metadata on a specific interval.

**Comment by edrock200** [comment]
Got it. Appreciate the quick response @markus101
