### ISSUE TITLE
Filter Series View based on Tags

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#566]
If we inherit tags based on series type then we could leverage that to get two birds stoned at once (-Ricky).

Multi-select (contains all), would be a good UI display, similar to GitHub issues.

**Comment by spooky69** [comment]
+1

**Comment by wants-to-play-with-radarr** [comment]
I don't suppose there's been any progress on this?

**Comment by LAP87** [comment]
Progress on this?

**Comment by xInsertx** [comment]
Any update? It would be nice to use one instance of sonarr, instead of a separate one for anime (due to no filtering).

**Comment by markus101** [comment]
Done in the v3 work.
