### ISSUE TITLE
2 Shows with the Same Name: Dead Pixels

### ISSUE THREAD

**Issue by Barry0901C** [Sonarr/Sonarr#5665]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

There are two shows with the same name: Dead Pixels.  One from 2019 and another from 2023.  Both cannot be added to Sonarr as they share the same name.  I've searched online for solutions and the consensus a Bug Fix needed to reported.

### Expected Behavior

One or both of the shows should have the year added to their title so they have distinct names.

### Steps To Reproduce

Add the Show from either year and then attempt to add the other and the error appears.

### Environment

```markdown
- OS: 
- Sonarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

I do not have these available for this issue

**Comment by markus101** [comment]
This needs to be addressed on TheTVDB, this isn't a Sonarr issue.

**Comment by CLHatch** [comment]
> This needs to be addressed on TheTVDB, this isn't a Sonarr issue.

More than that, it's not even an issue.  Just need to change the folder name to include at least one ID, duplicate show names isn't a problem.  Mine includes them all...

`{Series TitleYear} - {imdb{-ImdbId}} {tvdb{-TvdbId}} {tvmaze{-TvMazeId}}`

**Comment by Thirrian** [comment]
Nothing to do with folder naming. You can't _add_ both shows in sonarr because the name is the same, which isn't allowed as per tvdb rules and what sonarr counts on.

tvdb rule:
Original show is always without year, newer show(s) with the same name need to have the year added.

Show
Show (2000)
Show (2015)
etc

So it's correct that it has to be fixed on their end.

**Comment by CLHatch** [comment]
> Nothing to do with folder naming. You can't _add_ both shows in sonarr because the name is the same, which isn't allowed as per tvdb rules and what sonarr counts on.
> 
> tvdb rule: Original show is always without year, newer show(s) with the same name need to have the year added.
> 
> Show Show (2000) Show (2015) etc
> 
> So it's correct that it has to be fixed on their end.

Interesting.  Just tried adding both, and it complains about the "title slug" already being used.  Honestly, I would think this could be improved on the Sonarr side.  We have the other information to differentiate between them, so why allow an error on the TVDB side to cause an error on the Sonarr side?
