### ISSUE TITLE
Torrent Tracker Errors Prevent Import

### ISSUE THREAD

**Issue by pyro2927** [Sonarr/Sonarr#5666]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

There are times when a tracker returns a warning, but the download is still able to complete to 100%. Ones I have seen are "Tracker experiencing issues", or "Passkey not found". This presents as a [warning](https://github.com/Sonarr/Sonarr/blob/2016f11b1c322fcd5f9e2f09328ca19d2114629d/frontend/src/Activity/Queue/QueueStatus.js#L109-L113) in the Queue, and the file(s) will not import, even though the download itself is completed and the files pass integrity checksums.

### Expected Behavior

I would expect a file to be able to be imported if the progress is marked as 100%, regardless of the `status`.

### Environment

```markdown
- OS: Synology DSM 7.1.1
- Sonarr: 3.0.10.1567
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 113
```

### What branch are you running?

Main

### Trace Logs?

.

### Anything else?

<img width="402" alt="image" src="https://github.com/Sonarr/Sonarr/assets/39943/9ebc8904-570c-409f-ba51-158eabe557ec">

**Comment by markus101** [comment]
Which download client?
Please post the relevant trace logs as requested which will include the response from the download client.

**Comment by markus101** [comment]
In general clients report everything as an error and in their own verbiage so we can't make changes without the additional requested information. Closing until we have the information necessary.
