### ISSUE TITLE
Unable to determine series and episode

### ISSUE THREAD

**Issue by invinciberry** [Sonarr/Sonarr#5667]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr was unable to determine which series and episode this release was for. 
Show Name: [银光字幕组][名侦探柯南Detective Conan][871][信长四五〇事件][繁日][HDrip][X264-AAC][720P][MP4]

### Expected Behavior

Import correctly like [风车字幕组][名侦探柯南][871集][信长四五〇事件][简体][MP4][1080P][原OP]

### Environment

```markdown
- OS: Unraid
- Sonarr: 3.0.10.1567
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/11523055/sonarr.trace.txt)

**Comment by invinciberry** [comment]
Thanks for the quick fix! Much appreciated! When can I expect this enhancement to be merged into the main release?

**Comment by bakerboy448** [comment]
No ETA on when v4 (beta) will hit main

v3 is generally no longer in development
