### ISSUE TITLE
do not search all topics from inexes

### ISSUE THREAD

**Issue by Bl00d-B0b** [Sonarr/Sonarr#5669]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Movie available in multiple languages, but in indexer searches only English's language. Example:
[Peace! Friendship! Bubblegum!](https://thetvdb.com/series/mir-druzhba-zhvachka)
2020, Series #380993
Alternate Titles:
Мир! Дружба! Жвачка! ... Peace! Friendship! Bubblegum! ... Mir! Druzhba! Zhvachka!

I assume it should search all the titles, including alternative.
Also, It would be nice to specify in settings what description language I want to se, like in radarr. The description for this serial available in several languages, but i see ony english.

### Expected Behavior

expected to see description in other language, and to search in indexers with all names, including multiple languages

### Environment

```markdown
- OS: 
- Sonarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

n/a

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
