### ISSUE TITLE
Combine Multiple Release Profiles with Priority in One Profile

### ISSUE THREAD

**Issue by Eisa01** [Sonarr/Sonarr#5672]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently if `Must Contains` fails to get a match then there is no clear fallback.

### Describe the solution you'd like

Basically, what I am requesting is the ability to combine multiple Release Profiles under a new Profile. With priority defined based on order.

Similar to `Preferred Words` where you add `Term` and `Score`.
There will be a section that includes `Preferred Profiles` with `Profiles` listed based on order. Profiles higher in the list are more preferred, similar to the qualities section.
This is especially useful when using `Must Contain` or `Must Not Contain` is found in a release profile.

Let's say I have Profile (abcFanGroupProf) with `Must Contain` = `[abcFanGroup]`, and I have Profile (xyzFanGroupProf) with `Must Contain` = `[xyzFanGroup]`.

I'll create a profile (FanGroupProf) with Preferred Profiles having `abcFanGroupProf` first, and `xyzFanGroupProf` second. 
I'll add a tag for this profile called `FanGroup`.
Sample:
```
Preferred Profiles: 
     [x] abcFanGroupProf
     [x] xyzFanGroupProf
```
The following tag will now attempt to find `abcFanGroup` if there is no match then, immediately it will fall back towards `xyzFanGroup` because of the priority criteria.

### Describe alternatives you've considered

I have attempted creating one profile that does scoring with multiple conditions, but it never allowed me the same flexibility of having `Must Contains`. Also the following can allow for great flexibility in terms of fallback to the other exact profiles as needed.

**Comment by PearsonFlyer** [comment]
You're probably going to have a much better time making this work by switching to v4 (beta), which replaces preferred words with custom formats. These are a lot more flexible and would likely meet your needs.

**Comment by Eisa01** [comment]
Thanks for the prompt response, I'll update to v4 (beta) and provide my feedback. I am glad that this aspect is considered there in v4.
I will test and let you know if this request is resolved there.

**Comment by markus101** [comment]
Must Contain requires at least one of the terms to match, if you use must contain in combination with preferred words (or Custom Formats in v4), you could achieve a ranking must contain and releases with a higher preferred word or CF score are ranked higher, but still have the rigidity of must contain.

We don't have plans to combine multiple release profiles into one.
