### ISSUE TITLE
Add custom time settings for radarr and sonarr Check Health

### ISSUE THREAD

**Issue by PN62323424** [Sonarr/Sonarr#5675]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The current default is to check health once every 6 hours, but some sites may already be in failures after searching an anime. I wonder if it is possible to reduce this time?

Is there any reason for setting 6 hours?

Thank you for your help!

### Describe the solution you'd like

11

### Describe alternatives you've considered

11

**Comment by markus101** [comment]
The health checks run on a 6 hour schedule, but they also run in response to other things happening. If the status of an indexer changes between the scheduled runs it will update automatically. Indexer status is tracked separately from the health check, the health check just exposes it to the UI.
