### ISSUE TITLE
Corrupt archive?

### ISSUE THREAD

**Issue by aniceberg** [Sonarr/Sonarr#568]
The latest build at http://update.sonarr.tv/v2/master/mono/NzbDrone.master.2.0.0.3154.mono.tar.gz appears to be corrupt when I unzip/untar. File size is 5.53 MB (5,802,006 bytes), MD5: d58af68e28b534aab0fa1c24fcf582b2

**Comment by markus101** [comment]
Its untarring for me correctly, but my size is different:

![image](https://cloud.githubusercontent.com/assets/413544/7822032/a894985c-03a7-11e5-9049-56b607e787a0.png)

Sounds like an incomplete download on your end.
