### ISSUE TITLE
manifest.json: PWA is not installable when the URL base is not /

### ISSUE THREAD

**Issue by RosstheRoss** [Sonarr/Sonarr#5688]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The [manifest.json](https://github.com/Sonarr/Sonarr/blob/develop/frontend/src/Content/Images/Icons/manifest.json) does not produce a valid, installable progressive web app when *arr is installed to a non-default base URL (eg. example.com/sonarr)

### Expected Behavior

The manifest.json file at `/Content/Images/Icons/manifest.json` should produce a valid, installable progressive web app no matter what the root is

### Steps To Reproduce

1. Set a URL base other than `/`
2. The manifest.json is not installable, and the PWA cannot be installed.
   - The icons are absolute paths so any base URL other than `/` will point to a bogus path
   - The start_url is not set
   - The name field is empty

### Environment

```markdown
- OS: Ubuntu 23.04
- Sonarr: 3.0.10.1567
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Edge 115
```

### What branch are you running?

Main

### Trace Logs?

N/A (this is a problem caused by a [static file](https://github.com/Sonarr/Sonarr/blob/develop/frontend/src/Content/Images/Icons/manifest.json))

### Anything else?

Since the file is static and [relative URLs are allowed (under `src`)](https://developer.mozilla.org/en-US/docs/Web/Manifest/icons#values), simply patching the static manifest file should work.

Here is a rudimentary patch that made the PWA installable on Edge, I will make a PR of this if it works on other browsers too:
```patch
diff --git a/frontend/src/Content/Images/Icons/manifest.json b/frontend/src/Content/Images/Icons/manifest.json
index d14732f60..c00fab77e 100644
--- a/frontend/src/Content/Images/Icons/manifest.json
+++ b/frontend/src/Content/Images/Icons/manifest.json
@@ -1,17 +1,18 @@
 {
-    "name": "",
+    "name": "Sonarr",
     "icons": [
         {
-            "src": "/Content/Images/Icons/android-chrome-192x192.png",
+            "src": "android-chrome-192x192.png",
             "sizes": "192x192",
             "type": "image/png"
         },
         {
-            "src": "/Content/Images/Icons/android-chrome-512x512.png",
+            "src": "android-chrome-512x512.png",
             "sizes": "512x512",
             "type": "image/png"
         }
     ],
+    "start_url": "../../../../",
     "theme_color": "#3a3f51",
     "background_color": "#3a3f51",
     "display": "standalone"
```

The icon and name are absolutely required, the start_url may or may not be required.

**Comment by kid1412621** [comment]
Can this be merged into main? Facing the issue now.
