### ISSUE TITLE
TVDB season number is different from what is used in posted show

### ISSUE THREAD

**Issue by jerblack** [Sonarr/Sonarr#569]
I would like a way to change the season numbers for my shows, and have Sonarr use those new season numbers in its searches. Simliar to the alternate search string functionality in mylar. In my case, I am dealing with the PBS show Frontline. Sonarr shows the season number as the current year, but the shows are actually posted using the real season number. This means Sonarr is searching for something like frontline s2014e10 (no results) instead of frontline s32e10 (multiple results). I would like a way to change this on my end as needed for shows that require it.

**Comment by markus101** [comment]
Numbering issues are dealt with via thexem.de, specifically for this show: http://thexem.de/xem/show/1743

We have no plans to make it configurable from within Sonarr.

**Comment by jerblack** [comment]
Is there no way to select a different http://thexem.de/ list for a show or have sonarr use the title to pick the episode number from a different list?

**Comment by markus101** [comment]
No, you can't pick your own custom xem server or map them in another way.

As long as the series is kept up to date by one person it works for everyone, we don't see a reason to mess with that.
