### ISSUE TITLE
annoying to track every day show if in very different time zone

### ISSUE THREAD

**Issue by sjpotter** [Sonarr/Sonarr#5697]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sonarr handles these shows that air daily reasonably well, but I find it somewhat annoying to view sonarr and know what episodes i'm missing, because in the index it shows my time zone day that it aired, not the actual date.  

Ex Use case: A show airs at US Eastern 11PM.  I'm in London which is +5 .  Therefore a show that is the  May 24th, 2023 episode, will be listed in Sonarr for me as May 25th, 2023.  But no one would reference it as such, it always be viewed as the May 24th episode.  Now, sonarr, if it can find it, knows to download the May 24th episode, not the May 25th for this slot, but if I'm missing it and find a manual source for it it be nice to be able to easily determine if it has episodes I'm missing.  Currently its more work to do that.

### Describe the solution you'd like

Currently Sonarr has a global timezone that it gets from the system and this is how it decides to display time.  I believe it be a nice feature for Sonarr to be able to configure the default time zone itself (much like one can configure the other time entries) as well as configure a per series time zone (as one might be watching daily episodic shows from multiple world wide regions, so a global setting isn't sufficient)

### Describe alternatives you've considered

I thought about running it in a docker container with its own time zone that would be my preference for the majority of cases, but as noted, this doesn't really work in a global context.

**Comment by bakerboy448** [comment]
Pretty sure it's that Timezones are UTC in the database and then the frontend converts it to your local time based on your browser / system accessing sonarr's UI.

the system sonarr is running on wouldn't impact the frontend display

**Comment by markus101** [comment]
Anywhere Sonarr will show the date and time the time shown is relative to your time zone, this includes calendar, `Next Airing` on series list, `Air Date` episodes, `Airs` value in episode details.

In episode details in place of the season/episode numbers or absolute episode number shown when set to standard or anime series respectively, Sonarr will show the air date from the origin time zone, which is the same air date that Sonarr uses to match the release to the episode.

![image](https://github.com/Sonarr/Sonarr/assets/413544/149b4787-c369-4a12-b0dc-95e514f5b942)

We do not have plans to change the air date shown for daily episodes in other locations.
