### ISSUE TITLE
sonarrV4 cannot search for some episode titles

### ISSUE THREAD

**Issue by PN62323424** [Sonarr/Sonarr#5699]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

These titles are available in tvdb and there are no renames, and the titles I checked are correct

The Story Of Chuaner 2018 WEB-DL 1080p H264 AAC-HDCTV
I Told Sunset About You 2020 Complete WEB-DL 1080p H264 AAC

### Expected Behavior

11

### Steps To Reproduce

11

### Environment

```markdown
- OS: 
- Sonarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

11

**Comment by augustuen** [comment]
Please explain the actual issue, including steps to reproduce and expected behaviour. Otherwise your issue will be closed.
