### ISSUE TITLE
Display Monitored Status on Series Page

### ISSUE THREAD

**Issue by KarmaPoliceT2** [Sonarr/Sonarr#570]
Would like to see a way to determine monitored status visually and quickly on the table view of the series page (probably could easily add to other views too)... I think there are 3 statuses to note here:

Monitored Fully (all episodes/seasons)
Monitored Partially (some episodes/seasons)
Not Monitored (no episodes/seasons)

I would suggest using the "Continuing/Ended" icons and maybe outline them for unmonitored (like the bookmark tab thingy does when in the series page itself) 

Outlined = Not Monitored (dark outline as current, with white fill)
Light Fill = Partially Monitored (dark outline as current, with lighter shade of grey fill in)
Dark Fill = Fully Monitored (dark fill being how they look currently)

**Comment by markus101** [comment]
Whether or not the series is monitored is already shown, its shown as a Pause icon instead of the Play/Stop icon.

Whats the benefit of knowing whether or not its fully monitored?
What if specials aren't monitored is it still considered fully monitored?

**Comment by KarmaPoliceT2** [comment]
I'm not getting any pause symbols despite having several series listed but not monitored at all... 

The partial monitoring is really a stop-gap for an archival process I'm using... I'm not sure if there might be a better way, so am open to ideas... but essentially I have a lot of TV series that I want to keep, but not enough room to keep them all... so generally once they are watched, up to the cloud storage they go (amazon's cloud drive at 5$ a month for unlimited space works wonders)... Once in the cloud storage they lose all connectivity to Sonarr tracking them, and so I mark the seasons unmonitored to keep sonarr from re-downloading them... if the entire show is complete then I will mark the whole series unmonitored (though like i said, no pause signs showing up when i do that either)... 

Anyway, the gist of asking for this is so that I can visually tell what's archived (unmonitored) vs not (monitored) quickly from the series list...

**Comment by markus101** [comment]
The v3 UI will show the monitored status separate from continuing/ended.
