### ISSUE TITLE
Custom backup location

### ISSUE THREAD

**Issue by Asleep-at-the-wheel** [Sonarr/Sonarr#5701]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently using Sonarr in a container with the config volume local to the docker host. I want to automate the backups to a NFS share, this will mean an easy recovery should the host fail.  At the moment, as far as I am aware I have three choices:
1. Mount the entire config volume to NFS. I have done this before but found data base corruption over time.
2. Write a script that will go into the local config volume and pull out the backup files.
3. Manually download the backup files every now and then.

### Describe the solution you'd like

In the settings page, with the backup settings; could we provide a custom path to store the backups? This should make it easier to mount a dedicated NFS (or other type) volume for backups.

### Describe alternatives you've considered

Scripting will work, but requires users to have a good understanding of docker volumes and bash.

### Anything else?

I'd like to also put a huge thanks to everyone here. Your work is truly appreciated.

**Comment by augustuen** [comment]
![Screenshot_2023-05-29-10-15-35-40_3aea4af51f236e4932235fdada7d1643](https://github.com/Sonarr/Sonarr/assets/773150/83b74173-8bcf-49cb-8eb6-aee3f2005aad)

Settings -> General, Show advanced settings and scroll to the bottom.

**Comment by Asleep-at-the-wheel** [comment]
Wow, how did I not see that.

I really thought I had looked this through. Is this new?!

Thanks! I will close.
