### ISSUE TITLE
Open list of certains file error

### ISSUE THREAD

**Issue by Neptunespace** [Sonarr/Sonarr#5702]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

![Screenshot from 2023-05-30 12-22-43](https://github.com/Sonarr/Sonarr/assets/93327314/bd925a23-d5aa-4543-ad67-d771994c51fe)
![Screenshot from 2023-05-30 12-23-14](https://github.com/Sonarr/Sonarr/assets/93327314/5d493f9e-118d-4329-a720-8876c6fd274d)

When i open certain season to watch file with long name i get this error

File name with ls command :
![Screenshot from 2023-05-30 12-25-14](https://github.com/Sonarr/Sonarr/assets/93327314/4c4c6083-67e9-494c-a9cd-f5e752f9a283)

### Expected Behavior

![Screenshot from 2023-05-30 12-29-56](https://github.com/Sonarr/Sonarr/assets/93327314/63b434fe-4e6c-45e1-9315-f0d3d88ca740)

To see file like this ;)

### Steps To Reproduce

1. Click on the arrow to open a season to see file name / quality / other stuff

### Environment

```markdown
- OS: Ubuntu 20.04 with docker
- Sonarr: Package Version 4.0.0.520-ls488 by linuxserver.io 
- Docker Install: Yes (develop V4 Linuxserver)
- Using Reverse Proxy: Yes
- Browser: Firefox 113 Latest
```

### What branch are you running?

Develop

### Trace Logs?

{
  "message": "Response Content-Length mismatch: too many bytes written (19226 of 19015).",
  "description": "System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (19226 of 19015).\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.VerifyAndUpdateWrite(Int32 count)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FirstWriteAsyncInternal(ReadOnlyMemory\u00601 data, CancellationToken cancellationToken)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WritePipeAsync(ReadOnlyMemory\u00601 data, CancellationToken cancellationToken)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(ReadOnlyMemory\u00601 source, CancellationToken cancellationToken)\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionBody.WriteAsync(ReadOnlyMemory\u00601 buffer, CancellationToken cancellationToken)\n   at Microsoft.AspNetCore.Http.StreamCopyOperationInternal.CopyToAsync(Stream source, Stream destination, Nullable\u00601 count, Int32 bufferSize, CancellationToken cancel)\n   at Microsoft.AspNetCore.Internal.FileResultHelper.WriteFileAsync(HttpContext context, Stream fileStream, RangeItemHeaderValue range, Int64 rangeLength)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.FileResultExecutorBase.WriteFileAsync(HttpContext context, Stream fileStream, RangeItemHeaderValue range, Int64 rangeLength)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor.ExecuteAsync(ActionContext context, FileStreamResult result)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeNextResultFilterAsync\u003Eg__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeResultFilters\u003Eg__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/BufferingMiddleware.cs:line 28\n   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/IfModifiedMiddleware.cs:line 41\n   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33\n   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/StartingUpMiddleware.cs:line 38\n   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/UrlBaseMiddleware.cs:line 27\n   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/VersionMiddleware.cs:line 29\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"
}

**Comment by markus101** [comment]
The assumption that this is filename related is incorrect, it's related to the media info for one of the episodes in the season, one of them has an unexpected language code which results in that error. 

Can you post the response from `/api/v3/episodefile` for this show to gist or hastebin and link it here, that should give us the information to understand what is tripping it up and how we can best fix it.

**Comment by Neptunespace** [comment]
I could not explain, this error by it self, i do nothing and now good, cannot explain you

**Comment by markus101** [comment]
Okay, regardless this is an issue we need to look into further.
