### ISSUE TITLE
Add table column indicating if content is mostly made up of x264, x265 or AV1 codecs

### ISSUE THREAD

**Issue by gotens87** [Sonarr/Sonarr#5709]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

A way to sort shows by x264, x265 or AV1 majority content.

### Describe the solution you'd like

If a series contains say for example a specified threshold of x264, x265 or AV1 content it could be useful to have a label to sort against. Those shows might then get an allow upgrade profile applied manually applied by the user depending on what is found through 'Select Series'.

### Describe alternatives you've considered

Tags are an idea but without proper guidance on how to get a similar functionality I cannot say that is a known alternative.

### Anything else?

Some prefer to keep majority of their library as x265 (HEVC) content or AV1, or even x264. I'm only aware of those three codecs but if there's more of course they should be added. A similar function for audio codecs could also help but I'm not interested in that today.

**Comment by thezoggy** [comment]
if you care about codec, just do the needful with your release profile/custom format to control that. 

if your really just wanting to add something to the series page for a high glance as a form of a marker.. you could probably misuse 'tags' and surface those. add the tag to the series and then enable showing tags on the table.

**Comment by markus101** [comment]
This isn't something we could do without some significant changes to the stored data and isn't something we're planning to do.
