### ISSUE TITLE
Automatic updates do not reflect in Add/Remove Programs

### ISSUE THREAD

**Issue by benwa** [Sonarr/Sonarr#5710]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

With Sonarr's (and the other *arr's) update system, the Add/Remove Programs (ARP) entry does not reflect the actually installed version. This can cause problems with things like winget or other system monitoring tools.

### Expected Behavior

The ARP version string should be correctly updated.

### Steps To Reproduce

1. Install an older version of Sonarr
2. Note the version in ARP
3. Let the automatic updater update
4. Note the previous version in ARP

### Environment

```markdown
- OS: Windows 11 22H2
- Sonarr: 3.0.10.1567
- Docker Install: No
- Using Reverse Proxy: No
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

N/A

### Anything else?

My preference is that the `DisplayName` is simply "Sonarr" and the `DisplayVersion` is the correct, currently installed, version.

**Comment by bakerboy448** [comment]
That'd be expected given the internal updater doesn't reinstall at the OS level and simply updates the binaries in-place.
Any app that doesn't update via an installer that hits the registry will have the same effect.

Be a feature request, not a bug.
There is no Sonarr official winget package - so sounds like if winget is the issue you'd need to take it up with whatever third party built, creates, and maintains the sonarr winget package and they'll want to use package_info to disable the internal updater so winget handles updates.

**Comment by markus101** [comment]
Sonarr doesn't use the installer for updates and we have no plans to so that version will never be updated. We'll make a change so the version shown is just the major version that is installed, since major versions require a new installation.
