### ISSUE TITLE
Some episodes can be searched in jackett, but not in sonarr

### ISSUE THREAD

**Issue by PN62323424** [Sonarr/Sonarr#5713]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The title is: The Story Of Chuaner 2018 WEB-DL 1080p H264 AAC-HDCTV

The category is: 404

The site is：kp.m-team.cc

This image is the result of a search in jackett. You can see the title The Story Of Chuaner 2018 WEB-DL 1080p H264 AAC-HDCTV.But you can't see it in sonarr

https://i.ibb.co/mCg4hFS/Screenshot-2023-06-03-at-21-48-59.jpg

### Expected Behavior

111

### Steps To Reproduce

111

### Environment

```markdown
- OS: synology
- Sonarr:sonarr v4
- Docker Install:yes
- Using Reverse Proxy:
- Browser:chrome
```

### What branch are you running?

Develop

### Trace Logs?

111

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

That release doesn't have a season or episode number, Sonarr will not be able to parse it regardless of it getting the result back.
