### ISSUE TITLE
Manual Import multi-episode detection misinterpreting file name

### ISSUE THREAD

**Issue by cybersteel8** [Sonarr/Sonarr#5717]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Using manual import of entire show torrent (all seasons 1-8)
S07E10-E11 has been interpreted as S07E10-E10 it seems and it messed up the rest of the season's alignment.

### Expected Behavior

Correctly interpreting episode code for multi-episode files.
Also, it would make sense for each detection to be independent, so this doesn't misalign the entire season, just that episode be detected wrong and require manual intervention. I have to update every episode in the season because 1 detection was missed.

### Steps To Reproduce

As described in Expected Behaviour.

### Environment

```markdown
- OS: Unraid 6.11.5
- Sonarr: 3.0.10.1567
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome (unrelated)
```

### What branch are you running?

Main

### Trace Logs?

Not applicable.

### Anything else?
![image](https://github.com/Sonarr/Sonarr/assets/17291212/43589261-557c-4681-b171-2f4c9713853b)

![chrome_WtHieAo8eF](https://github.com/Sonarr/Sonarr/assets/17291212/89c9ed27-b53b-4acf-b05d-64af858fd151)

**Comment by thezoggy** [comment]
do you have sonarr set to rename, as its needed otherwise xem data wont be applied successfully
https://thexem.info/xem/show/3229

**Comment by cybersteel8** [comment]
> do you have sonarr set to rename, as its needed otherwise xem data wont be applied successfully https://thexem.info/xem/show/3229

Yes, these are my current settings

![image](https://github.com/Sonarr/Sonarr/assets/17291212/47058507-c7d8-44bb-b17c-8045e1a1bb5b)

**Comment by markus101** [comment]
Without trace logs showing the import it's impossible to say why this might have happened, but I'm not able to reproduce this behaviour.

**Comment by cybersteel8** [comment]
Hey @markus101 I have another example of this failing, and I can hold off on performing the import if you would like to use this example to debug what's happening here.
![image](https://github.com/Sonarr/Sonarr/assets/17291212/44b5c746-329b-4874-bde8-118be3cd6cba)

I turned on trace logs before opening this window, so I have some log files for you to have a look at.
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/12205451/sonarr.trace.txt)
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/12205452/sonarr.debug.txt)

I hope this helps!

**Comment by cybersteel8** [comment]
This is the xem show https://thexem.info/xem/show/3636
I think the issue here is that the data is already in TVDB formatting, not master.

The way the source is structured, is that I have 13 video files (in Season 3) that span 26 episodes as each video file spans 2 episodes. Because there are 13 video files, it may be assuming it is in master formatting, when the source files are actually already in TVDB formatting. This misunderstanding means it performs the master->TVDB mapping unnecessarily.

**Comment by markus101** [comment]
Files outside of the series folder almost always apply XEM mappings (the cases where it doesn't don't apply here), so this is expected behaviour. You'll need to override it with manual import.

**Comment by cybersteel8** [comment]
This is happening specifically with manual import. I tried selecting only the season instead of the whole series, but it looks like the same issue is happening.
What do you mean by "files outside of the series folder"? You mean for imports of files from an external source? Isn't that the primary use case of the manual import tool?

**Comment by markus101** [comment]
Yes, files that Sonarr doesn't have imported yet from an external source, which in this case is done via Manual Import.

Sonarr has no way of knowing that the files there correspond directly to TheTVDB numbering, which is why you're seeing it map the files as if they don't and why in this instance it's doing the wrong thing.

Based on the screenshot and the mapping on TheXEM it's doing what is expected, albeit wrong and it needs human assistance to resolve it.
