### ISSUE TITLE
TBD or TBA for "Episode Title Required" setting

### ISSUE THREAD

**Issue by Teamshake** [Sonarr/Sonarr#5718]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some episodes on TVDB that do not have the episode name yet, TBD is used as a placeholder.  Currently the setting "Episode Title Required" only appears to be looking for TBA.

### Describe the solution you'd like

For the "Episode Title Required" setting to look for both TBD or TBA and not download if either one exists.

### Describe alternatives you've considered

n/a

### Anything else?

an example is here of TBD being used instead of TBA
https://thetvdb.com/series/the-clearing-au/seasons/official/1

**Comment by bakerboy448** [comment]
TBD being used goes directly against TVDb rules and the episode names should be corrected.

https://support.thetvdb.com/kb/faq.php?id=31

**Comment by markus101** [comment]
This is a metadata issue, not going to add an additional guard for this in Sonarr.
