### ISSUE TITLE
Mid-season and Season Finale Indicators

### ISSUE THREAD

**Issue by ItsME6969** [Sonarr/Sonarr#5719]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Is it possible to have some visual Mid-season and Season Finale Indicators. This would save people time from having to go back and forth on TVDB checking if a season has ended/paused or not.

![Untitled - Copy](https://github.com/Sonarr/Sonarr/assets/89707006/63bea984-e6ae-4523-9940-826d5b2e42b9)

### Describe the solution you'd like

A visual indication somewhere of that status.

### Describe alternatives you've considered

None

### Anything else?

Mockup?
![Mock-up - Copy - Copy](https://github.com/Sonarr/Sonarr/assets/89707006/2b3033ce-55b9-4001-9e1b-62e310d64998)

**Comment by thezoggy** [comment]
on tvdb for an episode you can set the is_finale to 4 different options: none / season / mid-season / series

![firefox_2023-06-08_12-19-12](https://github.com/Sonarr/Sonarr/assets/500882/01858633-ed26-4946-b689-742deb30ed73)

**Comment by markus101** [comment]
Can you give some example shows where this has been an issue?

This logic is the same logic as we've used in the calendar for finales before they were actually available from TheTVDB, not bullet proof, but a number of series I checked that were completely lacking this information so we needed something. Ideally we wouldn't guess at all, but that means the metadata needs to be more reliable.

Only tagging it after it aired X days ago doesn't really solve the problem either, but could help with series that continually add an episode at a time.

**Comment by markus101** [comment]
I've updated it to make it more restrictive and only applies to series that have ended, after the episode has aired.

Currently Skyhook knows of over 102k shows that have ended, but only 63k of episodes that are series finales, so there is a huge lack of information on TheTVDB that is unlikely to be addressed any time soon.
