### ISSUE TITLE
[Development Branch] Rarbg results not linked

### ISSUE THREAD

**Issue by d2dyno** [Sonarr/Sonarr#572]
Hello,

Super excited to see Rarbg is already implemented in development version of Sonarr (expect a donation from me)!

However, I'm not sure if this is intentional or not: The search results for a manual search, that have results from Rarbg, are not linked to the respective Rarbg site page:
![arrow sonarr](https://cloud.githubusercontent.com/assets/2421939/7835237/2e871d98-0445-11e5-9102-578b0aa99634.png)

Here you can see that the KAT results are all linked, whereas the Rarbg results are not. Not a major issue, but something I noticed.

**Comment by Taloth** [comment]
Yes I know. Details url is not available in the api.

**Comment by d2dyno** [comment]
Thanks for the reply!

@rarbg is this something we can get coded into the API?

**Comment by Taloth** [comment]
For v2? probably.

**Comment by rarbg** [comment]
v2 will have it within 24h :)

**Comment by d2dyno** [comment]
Awesome!

**Comment by rarbg** [comment]
@Taloth Can you test pubapi_v2.php ?

**Comment by Bon3** [comment]
@d2dyno Could you help me in setting up rarbg as indexer im having issues doing so?

**Comment by d2dyno** [comment]
@Bon3 You must first change your Sonarr installation to the development version: https://github.com/Sonarr/Sonarr/wiki/Release-Branches

Then simply add the Rarbg Indexer, on the indexer page.

**Comment by Bon3** [comment]
@d2dyno sure i know that i have the dev branch installed but when i try to add the raring indexer i get an unable to connect to indexer, check logs error msg. :(

**Comment by markus101** [comment]
@Bon3 please use the forums for support. Include the logs when you open your thread there.

**Comment by d2dyno** [comment]
Not to rush anyone, but I haven't seen API v2 integrated yet. Any plans for this? Again, no rush. Just curious how things are going :)

**Comment by Taloth** [comment]
Already did, but wanted to wait till pushing it to develop till after my holiday week and feedback from other guys on the torrentapi v2 issue.

**Comment by d2dyno** [comment]
This issue is now resolved with API v2, which has been merged into the develop branch. Great work @Taloth and @rarbg
