### ISSUE TITLE
The problem with alias search

### ISSUE THREAD

**Issue by PN62323424** [Sonarr/Sonarr#5720]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

[**Original title**

```text
Ousama ni Sasagu Kusuriyubi S01E07 2023 1080p KKTV WEB-DL x264
```

**Problem Description**

I've checked that the alias romanization is already available on TVDB and I've waited for more than 72 hours, but I still can't search for the original title above.

I have tested several other older Japanese dramas with alias romanization, and as long as TVDB has them, they can be searched correctly with alias romanization

Reference：
The show "The Third Finger Offered To A King" has a Romanized alias "Ousama ni Sasagu Kusuriyubi" on TVDB.：https://thetvdb.com/series/ousama-ni-sasagu-kusuriyubi

### Expected Behavior

11

### Environment

```markdown
- OS: synology
- Sonarr:V4
- Docker Install:yes
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

11

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

TheTVDB’s aliases are not used by Sonarr, either aliases are added to XEM (primarily anime) or they’re added to Sonarr’s own list of aliases (scene mappings), which is explained in the FAQ.

Continuing to open issues for non-issues, questions or support will result in loss of privileges.
