### ISSUE TITLE
Sonarr not reporting in Qbittorent where new downloads come from like Radarr Does.

### ISSUE THREAD

**Issue by i-hate-utube** [Sonarr/Sonarr#5726]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

In the Category Column Radarr reports when it adds torrents to Qbittorrent, Radarr and Sonarr suppose to be made by the same programmers??? 

### Expected Behavior

In the Category Column Radarr reports when it adds torrents to Qbittorrent

### Environment

```markdown
- OS: win8.1
- Sonarr:3.0.10.1567
- Docker Install:n/a
- Using Reverse Proxy:no
- Browser:firefox and seamonkey latest
```

### What branch are you running?

Main

### Trace Logs?

Trace log will not show the issue

### Anything else?

![Screenshot at 2023-06-10 20-56-37](https://github.com/Sonarr/Sonarr/assets/119560831/778f4b9f-632d-41dc-bdaa-3c8d10403e1f)

**Comment by augustuen** [comment]
Please use the subreddit /r/sonarr or the Sonarr discord server for support questions.

**Comment by i-hate-utube** [comment]
Pls Delete as its human error

**Comment by bakerboy448** [comment]
- Sonarr is made by the Sonarr team
- Radarr is made by the Servarr team
- no idea who told you they're the same team, they're not
- You have a category configured for qbit in your radarr download client settings but not your sonarr download client settings
- Sonarr is doing exactly what it was told to do

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
