### ISSUE TITLE
Blackhole import is very weird (Good TV Show, wrong episode with very easy parsing name)

### ISSUE THREAD

**Issue by Neptunespace** [Sonarr/Sonarr#5730]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I men, 99% of file with blackhole working great but some time ???
File name in blackhole :
Chilling Adventures of Sabrina (2018) - S02E09 - Chapter Twenty-Nine - The Eldritch Dark HDTV-1080p x264 AAC[DE+EN+FR+IT+PT+UK] [AR+DE+EN+FR+IT+PT+UK] Multi Mycust Nameeeee.mkv

![image](https://github.com/Sonarr/Sonarr/assets/93327314/940e1466-cfb6-40b6-a1e3-287536b7d77e)

### Expected Behavior

Import the good episode in the good episode XD

### Steps To Reproduce

Import episode with blackhole

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: Latest avaible V4
- Docker Install: Yes
- Using Reverse Proxy: yes
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

[logfile_blackhole_wrong_episode.txt](https://github.com/Sonarr/Sonarr/files/11716102/logfile_blackhole_wrong_episode.txt)

### Anything else?

Sorry for the size of log :(

**Comment by markus101** [comment]
This is due to the mapping on Thexem.info.

https://thexem.info/xem/show/4636

**Comment by Neptunespace** [comment]
> This is due to the mapping on Thexem.info.
> 
> https://thexem.info/xem/show/4636

Oh thx for the reply, there is a way to avoid this problem then ?
