### ISSUE TITLE
JSON Responses from Indexers

### ISSUE THREAD

**Issue by braindonors** [Sonarr/Sonarr#5735]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have an indexer which exclusively returns JSON, which *arr is not expecting.

This indexer only emits JSON so in order to ensure that it is usable, a change to the api framework might be needed.

### Describe the solution you'd like

In the API Response area call this function first:
`public static bool IsJson(this string input){
    input = input.Trim();
    return input.StartsWith("{") && input.EndsWith("}") 
           || input.StartsWith("[") && input.EndsWith("]");
}`

this then determines if the response is json or xml (true or false)
then parse the output appropriately using the NewtonSoft JSON (or whatever is being used right now) to populate the list of downloads etc. for that query.

### Describe alternatives you've considered

The only thing I've really considered doing is writing a json to xml proxy, as a webservice, but that probably won't play well with the UI.

**Comment by braindonors** [comment]
This would need to be built into the upstream codebase so it can be inherited further down in the code.

**Comment by braindonors** [comment]
nzbindex.nl, yes they have a proper API, but it emits JSON (both v3 and v2)

**Comment by markus101** [comment]
That's not really an indexer, but a search engine for raw headers, it's not something we have plans to support.
