### ISSUE TITLE
Unlimited quality definitions not really unlimited

### ISSUE THREAD

**Issue by kinouzero** [Sonarr/Sonarr#5739]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Not related to any problem

### Describe the solution you'd like

Hi, now 2160p quality has become standard, but some episodes aren't downloaded because their size exceeds 4GB even when putting unlimited in the quality sliders.

<img width="1680" alt="Capture d’écran 2023-06-14 à 15 21 26" src="https://github.com/Sonarr/Sonarr/assets/4740176/70b2b705-2d5a-4b0f-a48c-e2b17d846847">

<img width="1680" alt="Capture d’écran 2023-06-14 à 15 21 17" src="https://github.com/Sonarr/Sonarr/assets/4740176/9010a2e8-dfb4-464a-9994-00ca7a59cfa6">

Can you put a real unlimited with no max size check for 2160p releases ?

### Describe alternatives you've considered

Maybe a checkbox to disable the max size instead

**Comment by augustuen** [comment]
According to the error message you've set a max size in your indexer settings. It's not complaining about your quality settings. And even if that was the issue, it should allow larger files than that. Your 1080p quality allows 9 GB/hr and From has a runtime of 50 minutes which would be well over the 5 GB size of that release

**Comment by kinouzero** [comment]
When you check the first screenshot it's marked "unlimited" but in the reality the numeric field indicate "400" so it's not very unlimited

**Comment by augustuen** [comment]
> When you check the first screenshot it's marked "unlimited" but in the reality the numeric field indicate "400" so it's not very unlimited

That may be, but your issue is unrelated to the quality definitions.
