### ISSUE TITLE
Season packs are ignored, even if they would be an upgrade

### ISSUE THREAD

**Issue by Schaka** [Sonarr/Sonarr#5740]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have Sonarr set up to use Custom Profiles to rank upgrades. I'm happy with how it works and overall, automatic grabs when using RSS seem to work mostly fine. However, they also seem to be ignoring season packs altogether. 

I have autobrr push new releases to Sonarr and I can see that the push was accepted in Sonarr, but no torrent is ever added to my client. This has now happened repeatedly and every time I have checked my logs to see if there is anything indicating why this is happening.

One example. There was a popular NF show releasing today. It first came out in 1080p x264, then in 1080p x265 (which I rank higher) and later 2160p x265. When the season pack for 2160p (higher res, better encoding, higher ranked release group) came out, it wasn't added to Sonarr although autobrr's push was  approved. 

Is there anything I can do to find out why this happening or is it intended behavior? If it is, I think it should be changed.

### Expected Behavior

If season packs are found, they should be used to overwrite single episodes if those are of lower quality according to the upgrade settings (resolution, codec, release group).

### Steps To Reproduce

1. Set up automatic upgrades for better quality
2. Download single episodes of some show
3. Make higher quality available or change profile weights
4. See season pack getting ignored

### Environment

```markdown
- OS: Unraid 6.11.5
- Sonarr: 3.0.10.1567
- Docker Install: Yes
```

### What branch are you running?

Main

### Trace Logs?

I have not enabled trace logging because I can't control when it happens. I might enable it (although it'll be spammy) if you think it will help.

**Comment by PearsonFlyer** [comment]
Please use the normal support channels (reddit when it's back off private, or github or the forum) for support issues. You will need trace logs to resolve this issue.

**Comment by addisonbabcock** [comment]
I think autobrr recently added the ability to redo a push. That should help isolating this in the logs.

**Comment by thezoggy** [comment]
sonarr only grabs a season pack if all episodes are monitored+wanted. 
if you have some episodes filled then a season pack wouldnt qualify.

the trick is to have the season pack be an upgrade (but has to qualify for all the episodes) + be wanted+monitored.

but again nothing for ghi, not a bug

**Comment by Schaka** [comment]
> the trick is to have the season pack be an upgrade (but has to qualify for all the episodes) + be wanted+monitored.
So it's intended behavior. I wasn't sure - hence the bug report.

In my case, all episodes (and the season) were monitored. It was a bump in quality according to my own profiles, hence why I don't understand it not upgrading. I would either expect Sonarr to reject the push or at least make a note as to why it was accepted and then left hanging. 

If those were individual episodes of higher quality, they would've started downloading and auto-upgraded. So I don't understand why season packs are handled differently. I'll make this a regular support request, but I still stand by this being essentially inconsistent behavior.

**Comment by markus101** [comment]
The consistency is all episodes must be an upgrade for it to be grabbed, if the release wasn’t an upgrade (quality and/or preferred words) then Sonarr wouldn’t grab it.

As to exactly why it was rejected or didn’t get sent to the client, trace or debug logs would be required.
