### ISSUE TITLE
Updating using Winget changes the service log on account, can cause "Missing root folder"

### ISSUE THREAD

**Issue by ak47uk** [Sonarr/Sonarr#5743]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When Sonarr updates via winget, it overwrites the service log on account with "Local Service". This can break access to file shares with errors such as:
Missing root folder
Import failed, path does not exist or is not accessible by Sonarr
Unable to find a volume mounted for the path

Editing the service's log on account to set it back to the local user that has permissions to access the file shares (UNC paths) fixes it. 

### Expected Behavior

When updating the program using Winget, the existing log on account for the service would be preserved. 

### Steps To Reproduce

Install Sonarr
Configure as necessary
Set the service log on account to a local user that has permissions to access network file shares
Update Sonarr using winget (in cmd/terminal `winget update TeamSonarr.Sonarr`) the service log on account will revert to "Local Service"

### Environment

```markdown
- OS: Windows 10 Pro
- Radarr: 3.0.10.1567
- Browser: Edge Chromium
```

### What branch are you running?

Main

### Trace Logs?

N/A

**Comment by bakerboy448** [comment]
Same response as radarr.

The sonarr team did not create nor maintains the winget package.   Winget uses the installer versus the internal updater simply replaces the files. There's no need/use for winget

**Comment by ak47uk** [comment]
> Same response as radarr.
> 
> The sonarr team did not create nor maintains the winget package. Winget uses the installer versus the internal updater simply replaces the files. There's no need/use for winget

Thanks, I excluded the same time as radarr. I use an auto update script that runs winget and updates all packages except the exclusion list to keep everything patched.

**Comment by markus101** [comment]
Sonarr’s installer isn’t meant to be re-run to update existing installs without touching the service, it’s more of a repair if rerun which will reset the service account to default.

Sonarr’s built-in updater should be used for keeping Sonarr up to date instead.
