### ISSUE TITLE
Show Open/Play button on hover

### ISSUE THREAD

**Issue by Milincho** [Sonarr/Sonarr#5744]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No way to open the file directly.

### Describe the solution you'd like

An Open/Play button on hover that would open the file with the system's default association.

![image](https://github.com/Sonarr/Sonarr/assets/60118859/57d8072e-34d6-424b-8b95-31098d02b151)

### Describe alternatives you've considered

Also inside the page

![image](https://github.com/Sonarr/Sonarr/assets/60118859/2def8759-7856-47d6-bf07-e6db68eae636)

**Comment by markus101** [comment]
This has been requested before, it is not something we're going to support.

**Comment by Milincho** [comment]
Can I ask the reason why?

**Comment by Taloth** [comment]
https://github.com/Sonarr/Sonarr/issues/5058
https://github.com/Sonarr/Sonarr/issues/2253
