### ISSUE TITLE
wrong ep number pick in folders

### ISSUE THREAD

**Issue by Kedryn** [Sonarr/Sonarr#5749]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

i have a lot of Anime managed via sonarr. Most of them have seasons subfolders.
Most of my downloads have only ep number, not seasons. I'm italian and almost no italian fansubs does not name files correctly.
When i download the first season, everything works, Sonarr recognize every EP and map it to the season.
The i use sonarr to rename every ep with the "SxxExx" naming format.
The problem arises when a second (or more) season pops up.
I start downloading all episodes on another subfolder (like "season 02"), and then Sonarr goes mad.
It start randomly remapping some EPs from season 2 to season 1, removing the already mapped from season 1
I'll attach some screens to show what i mean:

![image](https://github.com/Sonarr/Sonarr/assets/12759632/85d6d6b7-4dff-4d45-8538-8fc9aa8ce326)

This where 3 ep from season 1 where ripped of mappings (Season and Episode)

![image](https://github.com/Sonarr/Sonarr/assets/12759632/c5c92c0e-06cf-49ee-aa6f-da0cd4e67d20)

This where the same 3 episode were wrongly mapped to new downloaded in season 3

I think that something is wrong with this:

Folders, if "Sort episode in season folders" , can't be ignored when guessing Season for a EP that ha no season in filename (plex already does that).
an already mapped EP to a file with S01E08 in filename will not have to be remapped to another newer file if not by hand.
A filename with E08 doesn't have to take over one with S01E08. I don't know how radarr does that, but there must be some logic in place to prevent that.

### Expected Behavior

-  Mapped episodes from older seasons, must stay as they are, when downloading episodes for newer seasons,
- filenames with SxxExx format must have priority in mapping than files with only Exx.
- if a file has only Exx but is in a folder with "Season 2" or "02" have to be guessed as S02Exx and proposed to user in "Manage 

### Steps To Reproduce

Download a season, map and rename ep to match the right format, then download another season with only ep number in files, then open "Manage Episodes". chances are high that some mapping for ep from season 1 are switched so some of season 2.

### Environment

```markdown
- OS: unraid docker
- Sonarr: nightly
- Docker Install: 
- Using Reverse Proxy: no
- Browser: chrome latest
```

### What branch are you running?

Develop

### Trace Logs?

hard to make, because i don't really know when an ep will be downloaded

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

There is already https://github.com/Sonarr/Sonarr/issues/903 for getting the season number from the folder, but with absolute episode numbering and such poorly named files you're likely to have issues regardless.

**Comment by Kedryn** [comment]
I'm sorry but i think you missed the point.
The problem i wrote about is the one about already linked episodes<->files with season and episode number, get discarded in favor of newer episodes episode without sesason but same episode number gets added to the folder (with season folders or not) as per images i attached.

**Comment by markus101** [comment]
My response wasn't that this is a duplicate of that issue (nor should you respond to that issue with an off topic message), but that your issue is a support issue first and foremost, especially without any supporting details.

> I start downloading all episodes on another subfolder (like "season 02"), and then Sonarr goes mad.

This sounds like you are downloading directly to Sonarr's sorted series folder, which is neither recommended or supported.

Files in the series folder are expected to be renamed correctly, either including the season number or an absolutely episode number that does not reset every season. Which is why I referenced #903, it could potentially handle this scenario better, but isn't a fix for a poorly configured setup.

If you want to discuss/troubleshoot this further please join the Discord.

**Comment by Kedryn** [comment]
> 
> > I start downloading all episodes on another subfolder (like "season 02"), and then Sonarr goes mad.
> 
> This sounds like you are downloading directly to Sonarr's sorted series folder, which is neither recommended or supported.

You are right, i'm downloading anime episodes manually, because there is no other way to do that (mainly using IDM on fansub websites).

I thoght it was an issue (not a support issue) the fact that with an already matched S01E01 filename, the new E01 randomly wins in the race to get assigned as episode 1 in place of the previous and more precise filename. 
That's all

Anyway i'll get to discuss that in discord, as you said

**Comment by Kedryn** [comment]
I have an example:
Under te Queens' Umbrella is a Korean Drama
i have this file structure:

![image](https://github.com/Sonarr/Sonarr/assets/12759632/dcfc373a-8582-4e82-9bdd-47d2fc275b6a)

files in the root are already imported/linked with episodes, managed and renamed by Sonarr
now, if i go in the show page, and press again "Preview Rename" without touching anything, it asks me this:

![image](https://github.com/Sonarr/Sonarr/assets/12759632/1a2fd558-3525-4891-9c99-a7f327f6487a)

It wants to replace ep 1-4-6-8 that are already in the root and imported in Sonarr, with ones in the subdir.
why? i did not import/link them so why Sonarr thinks that NOW those ep are the right ones?

This is what "Manage Episodes" shows:

![image](https://github.com/Sonarr/Sonarr/assets/12759632/09637449-8337-4ba0-b48c-fbc2ccc91c5a)

i keep thinking that there is something wrong/missing in the logic Sonarr uses with importing/renaming episodes
