### ISSUE TITLE
Database corruption on OS X

### ISSUE THREAD

**Issue by leej0nes** [Sonarr/Sonarr#575]
I'm buying a UPS for the Mac Mini Server anyway but are there any plans to make it optional to use SQLite or another DB or should I just jump in and add support myself?  8 years .NET developer.

**Comment by markus101** [comment]
We don't have plans to support another database engine, we're not interested in supporting multiple migrations or queries.

SQLite on OS X has given us some trouble, but we've made some changes in recent releases to address those issues, if you're still experiencing issues please open a thread on the forums so we can troubleshoot (we don't use GitHub issues for support).
