### ISSUE TITLE
Settings -> Connections -> On Download Submitted

### ISSUE THREAD

**Issue by KyleSanderson** [Sonarr/Sonarr#5755]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It would be nice to be able to run a script when a unit of work is submitted by Sonarr somewhere (in specific, a download client).

### Describe the solution you'd like

Run a script when a download is submitted.

### Describe alternatives you've considered

There's no alternative besides busy looping it seems like. Not overly attached to the name.

### Anything else?

Just the infohash of the submission, similar to On Import.

**Comment by markus101** [comment]
`On Grab` does this already.

**Comment by KyleSanderson** [comment]
Oh jeez. thank you. I owe you a beer at Twin Sails or something.
