### ISSUE TITLE
Allow choosing sync profile from Prowlarr per series/search

### ISSUE THREAD

**Issue by toomanynights** [Sonarr/Sonarr#5756]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Not exactly a problem, just a thing that seems logical and would be nice to have.

I have a couple dozen of indexers. With this many to search, I often get an "Unable to load results" error. I know this is typically addressed by changing proxy limits, but I have no root and therefore no ability to fix the problem. This is where another solution comes in: Prowlarr's "[Sync Profiles](https://wiki.servarr.com/prowlarr/settings)".

This feature allows to separate indexers into groups. So, you can have one small group for interactive search, and another group with the rest of your indexers which will be used for automatic search.
This works well. With only a couple of indexers in manual search, I always get results. But what do I do when the required series can not be found in those indexers?

### Describe the solution you'd like

Would be really nice if I could choose Sync Profile to use:
- with manual search - upon initiating said search,
- with auto search - on per-series basis.

### Describe alternatives you've considered

Currently one thing I can do is:
- Have several small groups of indexers in Prowlarr.
- When search via first one fails, I go to Prowlarr and enable another group to be used in manual search only.
- Then I go to Tasks and sync changes to Sonarr.
- Then I go ahead and try the search again in Sonarr.
Can be done, but suboptimal.

### Anything else?

I can only say thank you for Sonarr. No matter what the decision on this feature request will be - I am very grateful. A month ago I didn't know anything like this was possible at all, and here I am now, managing my TV Show empire like a boss.

**Comment by toomanynights** [comment]
Sorry, I don't see how controlling 3 indexers settings takes sense away from this request..

Let's say I have one profile, that has `Enable Interactive Search` setting, there are 3 indexers in it. And the other for `Enable Automatic Search`, it's got 10 more. This means whenever I search manually, the search will be limited by 3 indexers in the first profile. If I want to extend the search, I would need to add a couple of indexers to the first sync profile in Prowlarr, sync changes and get back to manual search. Seems to me there is a lot of optimizing in this process.

Tags, once again, can hardly be used for situational control; if the manual search failed for this show, the best course of action would be to give some other search options straight away, IMO.

**Comment by toomanynights** [comment]
> Fix your bad proxy
It's not always that easy. I, like many, am on a shared server, where these parameters can't be configured on per-user basis.

> or use tags, your choice
I know what my current options are, I just think this FR would provide a better solution - and not just for my use case, mind you.

Consider this. I watch shows on English (or whatever the original language is), but I need subtitles (I believe this to be the case for a lot of non-native English speakers). Therefore, I have several indexers on my native language: often they have the releases I require (original sound + subtitles). But they never work with automatic search, because they don't use "English" in a release name, instead, they call it "Original". So those trackers are only useful upon manual search; a separate sync profile for those? Sure, but when the search fails, it would be nice to be able to switch to other options.

> I have way more indexers than you
I never mentioned how many indexers I had :) The numbers above are for the sake of example. In fact I have around 25 indexers.
And again: I will assume that you, unlike me, are on a dedicated/local server that you fully control.

This FR is not just a workaround for proxy issue (however it does serve that purpose), but it can have value in other use cases too. And it also makes overall sense to be able to switch between where you perform your _manual_ search through.

**Comment by markus101** [comment]
We do not have plans for fallback groups of indexers (if the search initially fails, search another group of indexers) or choosing a sync profile per search/series.
