### ISSUE TITLE
Additional Custom Filter option for Quality Downloaded

### ISSUE THREAD

**Issue by ItsME6969** [Sonarr/Sonarr#5758]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

You are on the landing page, you have a couple hundred shows, you want to quickly filter and see which shows you downloaded are in HD, 4k, 720p, etc
Currently I dont think there's any other way that manually tagging and creating custom filters from those tags and tagging each show manually is just tedious.

### Describe the solution you'd like

Additional Custom Filter option which checks for qualities downloaded. This suggestion is just mostly for the qualities but what would be even great is having more filters to work with eg check which shows I grabbed were in DV/HDR, etc pretty much anything you could regex from the release titles.

![Untitled (2) - Copy](https://github.com/Sonarr/Sonarr/assets/89707006/539dc601-961c-463a-b152-fe254cfef691)

### Describe alternatives you've considered

I was thinking an auto-tag feature would also handy to have. Say if I grab a 4k remux, the series gets auto-tagged as such, etc... of course that's an optional feature

### Anything else?

nope

**Comment by markus101** [comment]
We don't have plans to support filtering on the quality of one or more files in the series.
