### ISSUE TITLE
Seed ratio and time: different behavior UI vs. API

### ISSUE THREAD

**Issue by andreaswilli** [Sonarr/Sonarr#5759]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

In the indexer UI I can choose 0 for seed time and ratio. It shows a warning "should be greater than zero" but it's still possible to save.

The API seems to behave differently: When I try to sync indexers with these settings from Prowlarr it fails with this error:
```
2023-06-24 22:19:40.1|Trace|Http|Req: 237 [POST] /api/v3/indexer (from 172.18.0.1 Prowlarr/1.5.2.3484 (alpine 3.18.2))
2023-06-24 22:19:40.1|Trace|SonarrErrorPipeline|Handling Exception
2023-06-24 22:19:40.1|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- SeedCriteria.SeedRatio: Should be greater than zero
 -- SeedCriteria.SeedTime: Should be greater than zero
 -- SeedCriteria.SeasonPackSeedTime: Should be greater than zero
2023-06-24 22:19:40.1|Trace|Http|Res: 237 [POST] /api/v3/indexer: 400.BadRequest (3 ms)
```

Prowlarr logs:
```
2023-06-24 22:04:54.8|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.178.96:8989/api/v3/indexer: 400.BadRequest (700 bytes)
[
  {
    "isWarning": true,
    "propertyName": "SeedCriteria.SeedRatio",
    "errorMessage": "Should be greater than zero",
    "attemptedValue": 0,
    "customState": {
      "isWarning": true
    },
    "severity": "error"
  },
  {
    "isWarning": true,
    "propertyName": "SeedCriteria.SeedTime",
    "errorMessage": "Should be greater than zero",
    "attemptedValue": 0,
    "customState": {
      "isWarning": true
    },
    "severity": "error"
  },
  {
    "isWarning": true,
    "propertyName": "SeedCriteria.SeasonPackSeedTime",
    "errorMessage": "Should be greater than zero",
    "attemptedValue": 0,
    "customState": {
      "isWarning": true
    },
    "severity": "error"
  }
]
```

### Expected Behavior

API should accept these settings as well.

### Environment

```markdown
- OS: Ubuntu 22.04.2
- Sonarr: 4.0.0.544
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: 114.0.5735.133 (Official Build, ungoogled-chromium) (arm64)
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/11858093/sonarr.trace.txt)

### Anything else?

With Sonarr v3 I was able to sync these indexers from Prowlarr. Since I updated to v4 it's not working anymore.

Prowlarr recently changed the behavior for seed time and ratio in the UI after I opened https://github.com/Prowlarr/Prowlarr/issues/1692

**Comment by markus101** [comment]
The UI also uses the API, one save the API returns an error, but resaving tells the API to ignore the warning and to save anyways. Prowlarr can do the same thing.

**Comment by Qstick** [comment]
Yes, this is a Prowlarr issue, feel free to raise it there and we can discuss

**Comment by andreaswilli** [comment]
Thanks, I'll raise an issue with Prowlarr.

I am wondering: What do you think about adding an option to ignore the warnings and save with only one request? This way the Prowlarr sync could be sped up.

**Comment by Qstick** [comment]
We can already do that with Prowlarr via `ForceSave` API parameter, we just don't.

This is why I mentioned it's a Prowlarr issue.

**Comment by andreaswilli** [comment]
Ah, got it. Thanks for letting me know.
