### ISSUE TITLE
Search for All on Cutoff Unmet

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#576]
Add a search for all on Cutoff Unmet, same as search for all missing. The reason we haven't to date is due to the number of API calls it makes, do we want to do something smarter instead?

**Comment by Taloth** [comment]
Add it to Cutoff Unmet but make BOTH search buttons to first popup a confirmation modal with an estimate of api calls. ```"Executing this search will hit your indexers with a large number of api calls (at least x) and may cause you to reach the api call limit for your indexers." ``` x = number of episodes.
and maybe ```"Please do not execute a search periodically, Sonarr actively monitors the rss feed for new releases, if you searched previously then searching again will be pointless."```

A bit more work but educates ppl about why we don't normally search like that.

**Comment by otoolejp** [comment]
This seems to be the same as issue 344: https://github.com/Sonarr/Sonarr/issues/344

**Comment by markus101** [comment]
Thanks @otoolejp closed the other one because this has more detail.

**Comment by sadsack5000** [comment]
Would like to see this implemented too

**Comment by ounrequitedo** [comment]
Is this still in the works hopefully?

**Comment by markus101** [comment]
This is addressed in the v3 work.

**Comment by Hossy** [comment]
Is there an issue for the v3 work or something that I could subscribe to?  I would really love this feature. :-)

**Comment by markus101** [comment]
No issue and issues still need to be linked to the milestone, but: https://github.com/Sonarr/Sonarr/milestone/2

**Comment by Ashkaan** [comment]
+1 for this.  Some of us don't mind a ton of API calls.  Plus, the warning that we get from Search All Missing is great.

**Comment by Ashkaan** [comment]
It looks like this was closed a year ago because it's in the works.  Is this still in the works?

**Comment by JySzE** [comment]
I'm also interested in this being added.

**Comment by warsix4** [comment]
Also piqued in interest about this.

**Comment by Ashkaan** [comment]
Is there an API call I can make to accomplish this?

**Comment by methanoid** [comment]
Since this is closed it might explain the lack of response :-(

**Comment by maxexcloo** [comment]
Any news on this one?
