### ISSUE TITLE
New: Add CF and Score option for Discord on grab notifications

### ISSUE THREAD

**Issue by jack-mil** [Sonarr/Sonarr#5769]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

New in v4, support custom formats and custom format score fields into Discord webhook notification template.
This would require implementing code similar to Radarr.
https://github.com/Radarr/Radarr/blob/690bab3264f897e101a79bf881f8fd8ee3c746cf/src/NzbDrone.Core/Notifications/Discord/Discord.cs#L102C1-L109C31

### Describe the solution you'd like

Similar to how Radarr has implemented this feature.
![image](https://github.com/Sonarr/Sonarr/assets/62065280/538ffa0e-4133-4607-9c71-5bab94c68cd1)

### Describe alternatives you've considered

Could be accomplished similarily to #5493 

### Anything else?

I will attempt to make implement this change. The code is easy, but setting up the build environment will be more complex.
Is there a supported method for building and testing in Docker?
I use Linux and do not use Windows/Visual studio code,

**Comment by readstead** [comment]
Please also add the release group to the notifications (or an option to). I need to know what all the upgrades are about within the same quality profile.

**Comment by jack-mil** [comment]
There is currently the "Release" field that can be included in Discord, which is the full release title. 

I agree that the parsed release group would be a good addition.

I haven't used any of the other notification types, so I don't know what is available there. But it would be best if they all matched for sure.
