### ISSUE TITLE
Synology Indexer for Media Server missing directories

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#577]
Apparently directories need to be indexed separately for Media Server to find them (Video Station works).

See https://forums.sonarr.tv/t/possible-synology-indexer-notification-bug/5545

Not sure yet what's the cleanest solution, I rather not query a db somewhere, but it appears to be the only way.

**Comment by driesvandamme** [comment]
Are there any plans to query the synoindex db for share/series/season folders?
- Start from the deepest directory upwards, then reindex the one that isn't in the DB?

This issue has been open some time, and it's still a problem...

**Comment by slywoolmango** [comment]
I'd also love to know if there was a solution found to this bug. I'm running into this exact problem right now. Thanks!

**Comment by Michi491** [comment]
Same here

**Comment by markus101** [comment]
Going to close this given the age and lack of progress/interest.
