### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by logos88** [Sonarr/Sonarr#5771]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Nowadays Flatpak is becoming the new standar method in Linux to install packages, but Sonarr doesn't offer it.

### Describe the solution you'd like

It would facilitate a lot the installation if Sonarr would provide a Flatpak package, and even better if it would be officially uploaded to Flathub

### Describe alternatives you've considered

Snap or Appimage have lot less adoption

**Comment by Thirrian** [comment]
https://github.com/Sonarr/Sonarr/issues/3840

**Comment by markus101** [comment]
Similar to docker we don’t have plans to maintain a Flatpak package.
