### ISSUE TITLE
Full season release rejected. All episodes haven't aired yet.

### ISSUE THREAD

**Issue by WoodC2011** [Sonarr/Sonarr#5773]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The episode was finished in 2008, but sonarr still shows “Full season release rejected. All episodes haven't aired yet”

https://thetvdb.com/series/tian-dao

### Expected Behavior

11

### Steps To Reproduce

11

### Environment

```markdown
11
```

### What branch are you running?

Main

### Trace Logs?

11

**Comment by augustuen** [comment]
There are episodes in that season without air dates, so Sonarr assumes they haven't aired yet. You've got to add the correct dates to TVDB.
