### ISSUE TITLE
Take the time of the last episode of the finished season as the air time of all episodes

### ISSUE THREAD

**Issue by WoodC2011** [Sonarr/Sonarr#5774]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

For non-English episodes, many on tvdb only mark the last episode or certain episodes with the air date. This results in sonarr's search results as "Full season release rejected, All episodes haven't aired yet"

Considering that changing each episode is very time consuming, for episodes that don't exist, can we use the last episode of the finished season as the time for all episodes (newer shows don't have people marking the last episode, so it doesn't matter)

This would solve the problem that a lot of episodes with unmarked episode times cannot be downloaded automatically. Because it's always easier to mark the last episode than to mark the airtime of all episodes

In fact, tvdb editors, including myself, have a headache marking the airtime of each episode because many episodes have too many episodes

### Describe the solution you'd like

a

### Describe alternatives you've considered

a

**Comment by thezoggy** [comment]
If the show has a lot of episodes just ask a tvdb  mod to fill it in (open a ticket). They can do bulk stuff that normal users can't. 

Fix the data, don't change logic to handle your scenario because it's inconvenient to spend some time to fix it.

**Comment by WoodC2011** [comment]
OK, I will try to contact tvdb mod to fill it

But it's actually faster to modify the last episode than to wait for the tvdb mod to fill it. And quite a lot of these non-English episodes are not marked with the time of each episode, but I think this is a feature worth improving

**Comment by WoodC2011** [comment]
For example, the ninth season of this series does not have any episode airtime, and the last episode is marked as season finale, while tvdb has locked the episode modification permission, but it is actually available for download.

https://thetvdb.com/series/the-brokenwood-mysteries/seasons/official/9

If sonarr allows seasons with season finale or series finale time to download, it can solve this problem

**Comment by bakerboy448** [comment]
TVDb mods can update the locked series as well...

**Comment by bakerboy448** [comment]
Yes.  They can take a few days to reply.

**Comment by markus101** [comment]
This issue should be addressed by ensuring the metadata is correct. at this time we're not going to change this behaviour within Sonarr.

**Comment by WoodC2011** [comment]
> If the show has a lot of episodes just ask a tvdb mod to fill it in (open a ticket). They can do bulk stuff that normal users can't.
> 
> Fix the data, don't change logic to handle your scenario because it's inconvenient to spend some time to fix it.

Or I have another suggestion, which is to stop denying season pack downloads for unfinished seasons.

Reason:
1. old episodes from non-English speaking countries, many of them lack final season time information on tvdb making them unavailable for download, and updating the time information is a huge amount of work due to the need to manually update each episode (I contacted tvdb to try to batch update, and there was no reply for a month)

2. personally, I've never once encountered an unfinished season being released, and I think this is almost never the case with newer dramas (and even if it is, it's really just the publisher's problem, not sonarr's)

**Comment by WoodC2011** [comment]
> If the show has a lot of episodes just ask a tvdb mod to fill it in (open a ticket). They can do bulk stuff that normal users can't.
> 
> Fix the data, don't change logic to handle your scenario because it's inconvenient to spend some time to fix it.

Or I have another suggestion, which is to stop denying season pack downloads for unfinished seasons.

Reason:
1. a lot of old episodes from non-English speaking countries lack final season time information on tvdb making them unavailable for download (I can figure out 20 of these old episodes out in 10 minutes), and updating the time information is a huge amount of work due to the need to manually update each episode (I contacted tvdb to try to batch update them, and had no answer for a month).

2. personally, I've never once encountered an unfinished season being released, and I think this is almost never the case with newer dramas (and even if it is, it's really just the publisher's problem, not sonarr's)
