### ISSUE TITLE
Calendar only "Monitoring"

### ISSUE THREAD

**Issue by sebeksd** [Sonarr/Sonarr#5778]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Right now I'm using Medusa (previously SickRage, SickChill) and I heavily use "Archived" flag for episodes.
I would like to convert to Sonarr because Medusa is extremely slow (order of magnitude slower then Sonarr, at least in my case).
Unfortunately Sonarr lacks few major function (without them I will not be able to convert to Sonarr).

One that is kind of important is to be able to see feature episode for show on Calendar but do  not download them automatically.
In Medusa this is done by "default episode status" that can be set to "skipped". Medusa will show the show on calendar (in medusa it is called Schedule) but will not download new episodes.

From my testing this is impossible to set in Sonarr right now, only shows that are monitored will show on calendar.

### Describe the solution you'd like

I don't know how Sonarr works internally so my ideas will be just guessing.

Maybe new type "Monitor but do not download" for new episode? But because In Sonarr this is preconfigured combo box list maybe this should be additional flag here:

![image](https://github.com/Sonarr/Sonarr/assets/18705953/48afbac6-db7b-426d-8729-25e122b5f58f)

Than it would make released episodes as Unmonitored or something like that.

### Describe alternatives you've considered

Not sure

### Anything else?

It would be nice if Calendar could display show posters, however I will not request this feature right now because I can probably live without it.

**Comment by thezoggy** [comment]
There are some filter/controls there on the calendar (more so on v4).

**Comment by sebeksd** [comment]
Perfect :)

![image](https://github.com/Sonarr/Sonarr/assets/18705953/aa6f191c-ec84-49d5-847c-5d496b70fd71)
