### ISSUE TITLE
Add Custom Format Score column to Activity Queue

### ISSUE THREAD

**Issue by nemchik** [Sonarr/Sonarr#5780]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Not a big problem, but there's no way to see the Custom Format Score in the Activity Queue. In the Activity History it exists as a column. In the Activity Queue I can see the Formats column, but not the Custom Format Score.

### Describe the solution you'd like

Add the ability to see the Custom Format Score as a column in the Activity Queue.

### Describe alternatives you've considered

Wait for the download/import to finish and see the score in the Activity History.

### Anything else?

The reason I'm asking for this is because of manually added items, not searched through Sonarr. For example if I grab something directly from Prowlarr (or directly from an NZB site, or a magnet link from a tracker, etc) and I set the download category in the download client so that Sonarr can see and import the download, the Formats column still populates, but there is no way to see the score until after the download completes and I can see it in history. Being able to see the score during download might help me decide to search for an alternate download if the score is low or negative based on my CF preferences and scores, so seeing the score right when the DL is added would save time/bandwidth/etc.

**Comment by jack-mil** [comment]
Working on this in upcoming PR
