### ISSUE TITLE
Add support for episode mapping in `.plexmatch`

### ISSUE THREAD

**Issue by Ravencentric** [Sonarr/Sonarr#5784]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

`.plexmatch` support was partially added in https://github.com/Sonarr/Sonarr/commit/890f10746788f4deaec8008462802e1854646ebb. This is limited to just the series title, year, tvdb id, and tmbd id.

### Describe the solution you'd like

`.plexmatch` also supports per-episode mapping and if Sonarr could write these that would be great. The potential use case would be to avoid renaming altogether (so as to keep the files in their original state) while still having perfect matching in Plex.

### Describe alternatives you've considered

Continue renaming files to make them match in Plex

### Anything else?

Details on .plexmatch episode mapping https://support.plex.tv/articles/plexmatch/#toc-3

**Comment by markus101** [comment]
Why would this be an improvement over renaming the files? Seems like a bunch of work to implement this for a very small audience.

**Comment by Ravencentric** [comment]
I like to keep my original files as is and most of the time things match without issues. There are cases where this doesn't work, notably anime and some series. I can't selectively enable/disable renaming per show or show type so this seemed like the other best option. Not needing to rename files at all while still getting things matched.

**Comment by CLHatch** [comment]
> Why would this be an improvement over renaming the files? Seems like a bunch of work to implement this for a very small audience.

I've always been of of the mind that unless absolutely necessary, I keep the original filename (and rename the folder instead).  That way, I know exactly what release I have, even if I lose the data inside Sonarr.

**Comment by bholland-bh** [comment]
> > Why would this be an improvement over renaming the files? Seems like a bunch of work to implement this for a very small audience.
> 
> I've always been of of the mind that unless absolutely necessary, I keep the original filename (and rename the folder instead). That way, I know exactly what release I have, even if I lose the data inside Sonarr.

Why not use a better renaming format, to capture this information, as well as renaming the file.

For example: `{Series TitleYear} - S{season:00}E{episode:00} - {absolute:000} - {Episode CleanTitle} [{Custom Formats }{Quality Full}]{[MediaInfo VideoDynamicRange]}[{MediaInfo VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo AudioLanguages}{-Release Group}`

`The Series Title! (2010) - S01E01 - 001 - Episode Title 1 [Surround Sound x264 HDTV-720p v2][10bit][AVC][DTS 5.1][JA]-RlsGrp`

**Comment by CLHatch** [comment]
> > > Why would this be an improvement over renaming the files? Seems like a bunch of work to implement this for a very small audience.
> > 
> > 
> > I've always been of of the mind that unless absolutely necessary, I keep the original filename (and rename the folder instead). That way, I know exactly what release I have, even if I lose the data inside Sonarr.
> 
> Why not use a better renaming format, to capture this information, as well as renaming the file.
> 
> For example: `{Series TitleYear} - S{season:00}E{episode:00} - {absolute:000} - {Episode CleanTitle} [{Custom Formats }{Quality Full}]{[MediaInfo VideoDynamicRange]}[{MediaInfo VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo AudioLanguages}{-Release Group}`
> 
> `The Series Title! (2010) - S01E01 - 001 - Episode Title 1 [Surround Sound x264 HDTV-720p v2][10bit][AVC][DTS 5.1][JA]-RlsGrp`

Actually, a lot of people tell me I capture "too much" in my naming pattern.  I just don't put it in the filename.  You could actually have two different scene releases that will be renamed into the same filename with your pattern.  Then if you lose the Sonarr DB, you don't actually know which release you had.

`{Series TitleYear} - S{season:00}E{episode:00} - {Episode Title} [{Air.Date}] {[Custom Formats]} [{MediaInfo VideoCodec}{ MediaInfo VideoDynamicRangeType}{ MediaInfo VideoBitDepth}bit{ Quality Full}] [{MediaInfo AudioCodec}{ MediaInfo AudioChannels}{ MediaInfo AudioLanguagesAll}]{ MediaInfo SubtitleLanguages:EN+}{-Release Group}/{Original Title}`

**Comment by CLHatch** [comment]
> Why would this be an improvement over renaming the files? Seems like a bunch of work to implement this for a very small audience.

For the reason I mentioned... The original filename is a piece of information that would be lost if you had to re-import.  I look at the original title/filename as part of the "metadata" that I include in my naming scheme.  If I don't include that in my naming scheme, that information is lost later (since it is then only stored in the Sonarr database).  Sonarr also doesn't always get things right when naming files (say, not recognizing the release group).  But since I keep the original filename, I can always fix it in the folder naming based on that.   Fully supporting the `.plexmatch` file would make matching in Plex a lot more full proof though.

**Comment by m1dy** [comment]
I also like to keep the original filenames. I wrote a python script to generate these with information from the sonarr database automatically with sonarr connect or manually via cli. 

If anyone is desperate you can find my scripts here:
[writeplexmatch.zip](https://github.com/Sonarr/Sonarr/files/12998732/writeplexmatch.zip)

You probably have to change the paths to the sonarr database and in the trigger shell script. 

In sonarr connect I just execute the python script via shell script on import, upgrade, rename. I have set it to only execute on tag "plexmatch" so I can choose for which shows a plexmatch file is generated. 

For the python script that you can use manually you can search for the shows name using sonarr database and it will generate a new plexmatch file. 

It's all a bit hacky but works for me without problems for over a year now.

**Comment by Dukobpa3** [comment]
> Why would this be an improvement over renaming the files? Seems like a bunch of work to implement this for a very small audience.

There is support for episodes mapping in all available metadata integration except plex.
(Kodi, Roxbox, Wdtv doing it)
So at least for consistency would be great to provide the same functionality.

There also a lot of reasons to keep original filenames:
– Because Sonarr not supports Original Names and only Eng
– Because Different mediaservers supports different episodes pointing like 1x25 vs S1E25. And what do you suggest? If I keep couple mediaservers I should rename episodes each time?
– Because there can be not so good ripped episodes like couple in one file. And not always them will be in the same order like in TVDB bases. I can map them manually in Sonarr, but in some cases I want to keep Release numering

etc etc etc.

**Comment by mthole** [comment]
I found this thread today looking for exactly this feature. +1 to adding the episode mapping support to the `.plexmatch` generation.
