### ISSUE TITLE
EPIC FAIL: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Jaymz** [Sonarr/Sonarr#579]
Sonarr has been crashing a couple of times a day with the same error message for a while now, at least before the last update.

I'm running 2.0.0.3154, link below is to a log file with Trace logging enabled. Running on Ubuntu server 14.04.

http://pastebin.com/efUn3q0w

I have a cron job which checks if Sonarr is running and starts it if it isn't every 15 minutes. Crash in the log file is at 11:01:38.2.

Any clues as to what's causing it and how I can stop it would be appreciated. Let me know if you need more info than what's in the logs.

**Comment by markus101** [comment]
Yes, see the sticky in the support forums. https://forums.sonarr.tv/t/native-mono-crashes/4985

**Comment by Jaymz** [comment]
I could be wrong, but the stack trace in my crash appears different to what's reported in that thread.

System.NullReferenceException: Object reference not set to an instance of an object
  at System.Threading.Timer+Scheduler.SchedulerThread () [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0

At first glance appears not to be a native mono crash.

Apologies if it is, close again if so and I'll wait for the kernel update.

Cheers!

**Comment by Taloth** [comment]
It is.
Analogy:
The native crash is the table legs being sawn off, only visible if you look in the console log.
The crash you see is the table falling down. Everybody is like: wtf happened here?
Same problem, same cause, same solution.
