### ISSUE TITLE
Digital Core provider RSS feed repeats downloads infinitely

### ISSUE THREAD

**Issue by SnippetSpace** [Sonarr/Sonarr#5790]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr seems to grab torrents from Indexer digitalcore over and over. This leads to prowlarr bad stats showing 1372 grabs when in reality I grabbed maybe 20 torrents in the last weeks.
![dc stats](https://github.com/Sonarr/Sonarr/assets/917744/0e260d42-161c-4569-860a-8f9b715ceda7)

regardless of the torrent being present in qbittorent it gets regrabbed at every refresh. this hammers the indexer, breaks stats, and makes manual torrent management very difficult as sometimes I want to manually kill a download.

To illustrate:
![bsg issue](https://github.com/Sonarr/Sonarr/assets/917744/0437cb3b-c6c1-4dba-93ba-046794046aae)

### Expected Behavior

When using RSS refresh, do not take entries into account that were in the previous RSS sync. This can perhaps be done based on "initial post date"

### Steps To Reproduce

1. add digitalcore indexer
2. wait
3. check grabs in prowlarr

For trace logs I cleared logs, ran RSS sync for sonarr and radarr twice. this time it did not re-add the torrent. will keep logs running to catch it when it happens again.

### Environment

```markdown
- OS: Synology DSM
- Sonarr: 4.0.0.552
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Ms Edge (Chroomium)
```

### What branch are you running?

Develop

### Trace Logs?

Issue did not occur during these traces, it seems to be intermittent. Will continue trace logs for while to see if I can capture the moment it grabs the bsg torrent again.

Sonarr: https://logs.notifiarr.com/?1fb0d5a3b5d0afdc#HeJ6pjAquEWEG5w4oMzQvhGpgspyjZwf7JTTG9pDRdxY
Prowlarr: https://logs.notifiarr.com/?69b69225e36bb317#GR3GgXnAa14DouTrYzcn1Q9DFoU1ZN1gEKstSuZwA5cq

### Anything else?

RSS query: contains Battlestar Galactica torrent with original post date. it seems the indexer still includes it, probably due to low posting in the freeleech category.

https://[digitalcore.club/api/v1/torrents?categories[]=10&categories[]=11&categories[]=8&categories[]=9&categories[]=13&categories[]=14&categories[]=12&dead=true&extendedDead=true&extendedSearch=false&freeleech=true&index=0&limit=100&order=desc&page=search&section=all&sort=d&stereoscopic=false&watchview=false](https://digitalcore.club/api/v1/torrents?categories[]=10&categories[]=11&categories[]=8&categories[]=9&categories[]=13&categories[]=14&categories[]=12&dead=true&extendedDead=true&extendedSearch=false&freeleech=true&index=0&limit=100&order=desc&page=search&section=all&sort=d&stereoscopic=false&watchview=false)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
