### ISSUE TITLE
Add original language parsing in title

### ISSUE THREAD

**Issue by Natans8** [Sonarr/Sonarr#5805]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Many multilanguage releases don't explicitly mention the included languages, but rather the original language plus the translated language. For example, instead of "rus + eng" they write "rus + original".
And very often in such cases, only the explicitly stated language is detected.

For example, the following release detects only Russian despite clearly stating that the original language (English) is included.
`Beef / S1E1-10 of 10 [2023, HEVC, HDR10, Dolby Vision, WEB-DL 2160p] [Hybrid] 3 XX + Original + RUS`
![image](https://github.com/Sonarr/Sonarr/assets/52584161/6b9e1b8a-19d9-4351-9d49-728ce2ac2266)

A lot of titles in indexers like RuTracker are built like this after checking "Strip Russian letters" and "Add RUS to titles" in Prowlarr or Jackett.

### Describe the solution you'd like

The simplest solution would be to parse "Original" or "ORIG" or similar expressions in release titles in the exact same way as any other language like "ENG" or "ITA".

### Describe alternatives you've considered

It is possible to manually add a custom profile for detecting original language in release titles, but release title conditions are not quite compatible with language conditions.
For example if I create a custom format with at two conditions: French Language and "Original" in title, it will still require at least both conditions to comply, because at least a language match and at least a title match is required, and not a single one.
I know it is doable with multiple conditions, but overall it is just a mess, with treating languages as other traits.

### Anything else?

#2854 
This issue solves part of the common problem with multilanguage releases when not all languages are stated explicitly. But I feel like original language parsing is an obvious and a simple fix to small issues like in my example.

**Comment by GlassedSilver** [comment]
This is a very needed fix and there are many shows where I would specifically like to avoid their English title, typically because a show never made it outside my country, the show is only really known as XYZ, but someone on TVDB deemed it necessary to translate the title (not rarely poorly) to English just so there is an English title, and then you have this situation where you manually adjust the show folder name and can't really use the rename feature for files anymore...
