### ISSUE TITLE
Custom Format size restrictions should accept MB or 0.1GB

### ISSUE THREAD

**Issue by rosierazorex** [Sonarr/Sonarr#5809]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

1GB max file size is too large for some media, particularly cartoons.

Eg theres no way to setup for large, high bitrate 1080p releases for one show, and lower, smaller 1080p releases for another show. Custom formats help a little, but can't be fine tuned enough yet.

The root of the problem is no quality sliders per profile (see alternative solution), but since I don't see that really being addressed anywhere, we probably need more fine tuned custom formats to account for that.

### Describe the solution you'd like

Simply change the min and max size restrictions for custom formats to accept values in MB.

### Describe alternatives you've considered

Preferred solution would be to have the Quality sliders page _per profile_.

They can all be disabled by default inside the profile and defer to the global settings, but when enabled then any size-per-time quality setting inside the profile should override the global setting.

This would allow profiles like "Small 1080p cartoons" and "Large 1080p high-bitrate shows"

**Comment by jack-mil** [comment]
this could solve having to run multiple instances for anime and western shows!

**Comment by rosierazorex** [comment]
It looks like accepting MB in Custom Formats won’t really solve the original issue. I didn’t realise you still have to select the quality profiles, so you’re still restricted by global quality settings.

The best solution is still per-profile quality sliders.
