### ISSUE TITLE
Improve pagination of wanted episodes

### ISSUE THREAD

**Issue by fryfrog** [Sonarr/Sonarr#581]
I would love to see an improvement to pagination. I like to flip through the wanted list and look for shows and episodes I might want to search for immediately. The addition of sorting in the last update or two really made things nice, but I think there are two things that would improve the experience a little more. Add pages between the < and > buttons and allow the url to specify page.

For the bottom bar with |< << 1/500 >> >|, I'd love to see some pages too. Like |< << 1 ... 5 6 7 ... 500 >> >|. This would still allow quick navigation to next / previous, first / last, but it'd also let you jump around a little more quickly. I'm open to suggestions on how many pages to show and how to show them. Three is probably the bare minimum, more would be better. And really, showing the first and last is redundant because of the |< and >|.

It would also be great if the page were reflected in the url, so I could just spit that in if I wanted. I'll take or leave that, nbd if the first suggestion is done well enough.

**Comment by markus101** [comment]
You can click the page number and select the page number you want to jump to.

We don't plan on altering the URL based on the page number though.

**Comment by fryfrog** [comment]
Dang, I didn't even *think* to click that. Maybe make it a little more obvious? :+1:
