### ISSUE TITLE
Option to remove series download/history 

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#5815]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

from discord convo of user asking:
"Do you know a way of totally nuking the show history?"

deleting a series from sonarr doesnt touch the history/download.
which in some cases it might be useful to give the user an option to delete said history/download for said files when removing instead of having to direct users to go modify their db manually.

### Describe the solution you'd like

give an option to delete download history for said series/files when removing

### Describe alternatives you've considered

none

**Comment by markus101** [comment]
History is removed when a series is removed, both the history you see in the UI and the history Sonarr uses separately to track partially imported releases.
