### ISSUE TITLE
[Development Branch] Edit Newznab - categories required even tho it says no

### ISSUE THREAD

**Issue by KrunchMuffin** [Sonarr/Sonarr#582]
I believe the categories were pre-populated? Anyway, I went to delete them cause I don't care about daily shows, it also said in the tooltip they aren't required, as well as the anime cats. Went to save and got what you see in the screenshot below.

[error screenshot](http://i.imgur.com/7mkUw2T.png)

**Comment by markus101** [comment]
Do you get the same error if anime has a value? You definitely need one of the fields populated.

The standard ones covers both standard and daily shows though.

**Comment by KrunchMuffin** [comment]
No, don't get an error if i populate anime. They both say to leave blank to disable. So it's working correctly, just the verbiage needs to change I guess? A little misleading.

**Comment by markus101** [comment]
Fixed the error message when both fields are blank.
