### ISSUE TITLE
Jellyfin/Emby Update by Name

### ISSUE THREAD

**Issue by JeWe37** [Sonarr/Sonarr#5826]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, Jellyfin and Emby are notified of changes to files [via the path of the series](https://github.com/Sonarr/Sonarr/blob/dee8820b1f31e9180c55c6d29b950ff6cfe0205f/src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs#L34C25-L34C25), which doesn't work when, for instance, Jellyfin and Sonarr are in containers with different mounts.

### Describe the solution you'd like

Especially when Metadata is on, Jellyfin's title and year should line up with Sonarr's, allowing us to obtain the path from Jellyfin's API and use that rather than Sonarr's. This should be an option as for cases where Metadata is off, there may be edge cases where this mapping won't be definitive.

### Describe alternatives you've considered

One alternative would be to integrate some form of remote path mapping into the connection, however that will be difficult with the current menu system and presents problems if in addition to using a different base directory, the names of your files do not actually line up between Sonarr and Jellyfin(either via some form of filesystem that causes that or maintaining a hardlink set). I happen to use such a setup in order to get some Jellyfin features that are very particular about the naming and incompatible with what I need for my Sonarr library.

### Anything else?

There seem to be [some problems](https://github.com/jellyfin/jellyfin/pull/7965) with some parts of the Jellyfin API that might be useful here when using an API token as Sonarr would, but those are fixed in development versions so can be used now.

**Comment by bakerboy448** [comment]
Plex has a remote math map already, the same logic could apply

**Comment by JeWe37** [comment]
Do you mean the Plex watchlist? I couldn't find anything resembling path mappings in any other menu. Those aren't really path mappings per-se, I don't think they would work for multiple different library paths. I already have a PR open doing it via names/ids though, it should work pretty well.

**Comment by bakerboy448** [comment]
No - the Plex Media Server Connection. 

https://github.com/Sonarr/Sonarr/commit/de08d372677052f5dcf9ee689cd48282746bfbec

V4 beta only; much like all the other dev work since 3.0.9 / hot fixed 3.0.10 were released quite awhile ago

**Comment by JeWe37** [comment]
Ah, my production setup is still on V3, need to find the time for the upgrade. But that seems to have the same issue with only being able to have a single mapping? I suppose you could use multiple connections potentially. This would still present problems with complex library mappings like I explained above though.

**Comment by karserasl** [comment]
I dont understand this one..

Is it just a single path mapping ?
Cause usually, we have like 3-4 paths in a single library

**Comment by JeWe37** [comment]
Well it got mixed up a little. There's two things added here: A path mapping and an update by trying to figure out which series in Jellyfin corresponds to the one updated in Sonarr. 

For you: If you have a filesystem with functional inotify(or whatever the Windows analog may be), you don't need any of this anyway, just enable real-time updates in Jellyfin. If you do not, then if you are running the Jellyfin develop branch the name mappings will take care of this. If you are running 10.8.x, then Sonarr previously already didn't support your use case and doesn't now either.
