### ISSUE TITLE
Updates page says "The latest version of Radarr is already installed"

### ISSUE THREAD

**Issue by pendingthecynic** [Sonarr/Sonarr#5830]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

pages says Radarr and not Sonarr

### Expected Behavior

Should say Sonarr

### Steps To Reproduce

navigate to /system/updates

### Environment

```markdown
- OS: Windows 10
- Sonarr:4.0.0.575
- Docker Install: no
- Using Reverse Proxy: no
- Browser: edge/chrome
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/12136648/sonarr.trace.txt)

**Comment by pendingthecynic** [comment]
![sonarr](https://github.com/Sonarr/Sonarr/assets/140258690/1e883010-a91f-456d-9ba9-8c3b91642bd2)

**Comment by PearsonFlyer** [comment]
You are on develop (beta), not main. But, translations are currently actively being worked on, this will get fixed shortly. Thanks!
