### ISSUE TITLE
Import List & Search on add

### ISSUE THREAD

**Issue by Minxster** [Sonarr/Sonarr#5831]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I've looking at the online manual : [https://wiki.servarr.com/sonarr/settings#import-lists](https://wiki.servarr.com/sonarr/settings#import-lists)

I note there is/should be an option to "Search on add", but I cannot find this when I create a custom import list. I'm currently using Docker 

### Describe the solution you'd like

The ability to Search on add

### Describe alternatives you've considered

I'm aware that this can cause issues, e.g. downloading too many files/shows/episodes. But I believe this functionality did exist at some point?

### Anything else?

I'm currently running Docker, 4.0.0.575.

I'm fully aware that Search on add can be an issue for many reasons, and have seen people discussing (on Reddit) and why it can be a bad thing. But after recently creating my own curated list(s) and getting Sonarr to collect this list, I now find I need to manually search for missing episodes (if it's an older show).

So I'm not sure if this is a feature request, or a bug, or what? The manual/wiki states there should be a Search on add, but it doesn't seem like an option for my just now?

**Comment by PearsonFlyer** [comment]
Import lists do search on add, there is no option not to (at least, on v4).

**Comment by Minxster** [comment]
@PearsonFlyer thanks for the response, really good to know 👍
