### ISSUE TITLE
Revert to full path parser if ^S0x filename

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#585]
The Parser should detect filenames starting with S01E06 and include the parent folder as series name.
The same logic can be applied to that parent folder, if it starts with S0x or Season.
That way we can get to the show name.

We can't do the same for just 01 coz we won't know if it's really the episode number, absolute number or just a number.

**Comment by bakerboy448** [comment]
This bug/issue seems stale.  Please check and see if it is still an issue on the recent v3 builds.  If it is an issue please open a new GHI with logs and full detail.
