### ISSUE TITLE
config.xml - read only

### ISSUE THREAD

**Issue by janholtzhausen** [Sonarr/Sonarr#5858]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sonarr (and indeed all other *darrs) complains when config.xml is read-only, which is the state it must be in for mounting as a config map in kubernetes.

### Describe the solution you'd like

Eliminate to write attempt to config.xml if it already correct? Maybe a flag in the xml to allow read-only?

### Describe alternatives you've considered

Saving config to volume, this works but negates config map goodness.

**Comment by markus101** [comment]
Sonarr and the other arrs write to the config file when relevant settings are changed; it can't be read only.

The primary difference is whether those settings are required for Sonarr to start up and not something we're going to look into changing.
