### ISSUE TITLE
EPIC FAIL error, NullReferenceException on scheduler

### ISSUE THREAD

**Issue by talz13** [Sonarr/Sonarr#586]
Sonarr has died several times lately, and looking at the logs, this is the last message I see before I started the service back up again:

15-5-30 05:52:05.3|Fatal|GlobalExceptionHandlers|EPIC FAIL: Object reference not set to an instance of an object

System.NullReferenceException: Object reference not set to an instance of an object
  at System.Threading.Timer+Scheduler.SchedulerThread () [0x00000] in <filename unknown>:0 
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0 

Version info is:

Version 2.0.0.3154
Mono Version 3.10.0 (tarball Wed Nov 5 12:50:04 UTC 2014)

**Comment by Taloth** [comment]
See https://forums.sonarr.tv/t/native-mono-crashes/4985

Dupe #579
