### ISSUE TITLE
Autotag: Monitored

### ISSUE THREAD

**Issue by ManiMatter** [Sonarr/Sonarr#5863]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hi,

Context:
- I have two Sonarr instances (4k & 1080p.
- I want to download each tvshow that is I have in 4k in 1080p as well.
- Reason: To avoid transcoding

Challenge:
- When I download a series on the 4k-Sonarr instance, I also want it to be deletd in the 1080p instance
- In radarr, I have a auto-tag "Monitored", and I sync between the two instances only those movies that have the that "Monitored". Thereby, deleted movies do not get synced
- In sonarr, the possibility to add an auto-tag based on monitoring status is missing

Enhancement:
- Add auto-tag based on Monitoring Status, same as it is in radarr

### Describe the solution you'd like

Add auto-tag based on Monitoring Status, same as it is in radarr

### Describe alternatives you've considered

- Tried syncarr (does not work on ARM & is not making use of the Sonarr built-in "List" feature)
- Tried to filter by "root folder", but that syncs all shows (even those that have been deleted from the root folder)

**Comment by markus101** [comment]
This is already being implemented in https://github.com/Sonarr/Sonarr/pull/5843

**Comment by ManiMatter** [comment]
Hi Markus, thanks for the super-fast answer.

I see in Sonarr (4.0.0.585) the ability to auto-tag by the following options:
- Genre
- Root folder
- Series Type

In Radarr (4.7.4.7743) I see:
- Genre 
- **Monitored** 
- Root Folder 
- Year

I am missing the "Monitored" in Radarr. 

Any ideas why I am not seeing it, if it's really implemented?

**Comment by markus101** [comment]
It's being implemented, not has been implemented. and as Bogdan said, the PR is still open.
