### ISSUE TITLE
Allow different Transmission download folder

### ISSUE THREAD

**Issue by lamarios** [Sonarr/Sonarr#587]
Now it's only possible to download torrents in the default folder when using Transmission. It would be good to be allowed to change it to somewhere else.

Thanks !

**Comment by delphiactual** [comment]
set category to .sonarr in your download client settings for transmission. Also support is offered on the forums/irc.

**Comment by Taloth** [comment]
The dot is optional btw

**Comment by lamarios** [comment]
I see, It's not ideal, but it'll do, thanks a lot.
