### ISSUE TITLE
Whole season gets deleted instead only 1 episode

### ISSUE THREAD

**Issue by Milincho** [Sonarr/Sonarr#5875]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Went to remove the episode I just watched...

![image](https://github.com/Sonarr/Sonarr/assets/60118859/7c6fc6ad-86d0-4613-ba2d-fe6eb23b0d6f)

And Sonarr deleted the whole season. Just 86 unrecoverable GB... 🤦🏻‍♀️

![image](https://github.com/Sonarr/Sonarr/assets/60118859/2dc1a543-e3cb-4700-bdc1-f3f1e7cb6a7d)

### Expected Behavior

Not removing and deleting the whole season files, or AT LEAST warn it will do that...

### Environment

```markdown
- OS: Windows 11
- Sonarr: 4.0.0.589
- Docker Install:
- Using Reverse Proxy:
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

Not needed

**Comment by markus101** [comment]
You told Sonarr to remove the whole download, it's in the top of the modal title and the body of the modal message.

If you want to remove an individual file that Sonarr has imported you can do that from the series details page or calendar.
