### ISSUE TITLE
Bad title for Kitchen Nightmare French TV Show (the good title is Cauchemar en Cuisine) no épisode are found

### ISSUE THREAD

**Issue by tifo71** [Sonarr/Sonarr#5878]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The title of the French program "Kitchen Nightmares (FR)" is incorrect. The correct title is "Cauchemar En Cuisine", so there are 0 results for the indexer because it is noted Kitchen Nightmares (FR) instead of Cauchemar En Cuisine.

As a result, no episode is found.

![image_2023-08-05_022540925](https://github.com/Sonarr/Sonarr/assets/130233722/e30f43b3-c9d1-47c7-b204-bc2b25ff532d)

### Expected Behavior

The title of the French version should be renamed in french"Cauchemar En Cuisine" instead of Kitchen Nightmares (FR) so that the indexer can find the episodes, as no episodes are currently found.

![image_2023-08-05_022704349](https://github.com/Sonarr/Sonarr/assets/130233722/56f3a542-e715-4db4-8c40-30d93d5eadb8)

The torrents are marked in French "Cauchemar En Cuisine" and not Kitchen nightmare FR

![image_2023-08-05_022802059](https://github.com/Sonarr/Sonarr/assets/130233722/06330ec7-3899-408b-9185-9779a7379114)

### Steps To Reproduce

add kitchen nightmare FR and you will see that there are no episodes of found. Episodes are indicated "Cauchemar En Cuisine" and not Kitchen Nightmare FR

### Environment

```markdown
- OS: Windows 11 
- Sonarr: 3.0.10.1567
- Docker Install: no
- Using Reverse Proxy: no
- Browser: Opera One (version : 101.0.4843.25)
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/12265339/sonarr.trace.txt)

### Anything else?

here is the result link for nightmare in the kitchen on the YGGTorrent site :[Link]( https://www3.yggtorrent.wtf/engine/search?name=cauchemar+en+cuisine&do=search&order=desc&sort=publish_date)

You can see that the titles are well "cauchemar en cuisine" in french and not Kitchen Nightmare FR

**Comment by thezoggy** [comment]
Please use one of the support channels: <a href="https://forums.sonarr.tv/" rel="nofollow">forums</a>, <a href="https://www.reddit.com/r/sonarr/" rel="nofollow">subreddit</a>, <a href="https://discord.gg/Ex7FmFK" rel="nofollow">discord </a>, or <a href="https://web.libera.chat/?channels=#sonarr" rel="nofollow">IRC</a> for support/questions.

**Comment by tifo71** [comment]
> Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

ok thanks
