### ISSUE TITLE
SeriesScannedHandler|[#TVShow#] was recently added, performing post-add actions - S01E01

### ISSUE THREAD

**Issue by Minxster** [Sonarr/Sonarr#5881]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

My indexer has an API/search hard-limit of 100 results. When adding a new show, the "ReleaseSearchService is searching for [#TVShow# : S01]" is not getting all the results, so episodes can be missed.

### Describe the solution you'd like

Have the ability (settings/indexers/indexer/tickbox) to tell "SeriesScannedHandler|[#TVShow#] was recently added, performing post-add actions" to queue multiple searches for SxxExx, rather than just Sxx. A simple tickbox, off by default 😉, to tell the function/process to queue up multiple searches.

I can see posts on similar topics, in other places, stating "this is just how Sonarr works", but I feel this addition can help (certain) others and gives people more options.

### Describe alternatives you've considered

(1) I'm currently trying to speak with the Indexer to see if there is a way to raise the API/search limit of 100. But I can see this has been asked in the past and refused. But there's no harm in me asking again 🤷‍♂️

(2) Writing my own set of scripts with a DB; all to monitor Sonarr and re-trigging searches as/when new shows are added. This is far (far) from ideal.

**Comment by bakerboy448** [comment]
So to be clear you want your indexer to be hit with
13-25 (assuming a 12 or 24) episode season * every alias => So perhaps several hundred to thousand searches for a single series?

I can't see how that is something that your indexer wants and most will easily ban users for that type of abusive searches.

**Comment by markus101** [comment]
The point of searching for the entire season is to keep the number of API requests down and is something an indexer should be able to handle properly.

Such a setting is not something we're going to implement as it will resulted in users and potentially Sonarr as a whole being banned from indexers.

Instead of asking your indexer to raise their API request limit or is to implement a feature that we've previously explained why we won't you should ask your indexer to improve their search capabilities to return the appropriate results when searching for a season or replace the indexer with ones that do.

**Comment by Minxster** [comment]
Well that was all very short lived, dramatic, and not not too useful.

I mean, I do understand what you're both saying. But striking this down on the grounds of not bombarding an indexer, is one thing, but I don't see other safeguard, elsewhere in Sonarr, to also help this type of situation? I could make a new instance of Sonarr and throw in a tonne of new shows and it would cause a problem with an Indexer. Let alone not having the option to manage/maintain aliases, which also a big problem of too many calls to an indexer.

... Asked, answered, and begrudgingly understood.
