### ISSUE TITLE
Import List - Allow Enable Automatic Add, but disable the auto searching feature

### ISSUE THREAD

**Issue by Minxster** [Sonarr/Sonarr#5882]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The auto search function, when a show is added via Import List, won't necessarily work with my Indexer. As such, I'm wasting space, bandwidth and api requests with my Indexer, whenever a new show it added.

### Describe the solution you'd like

In Import Lists, the ability to "Enable Automatic Add" but also have "Don't auto-search on add" (something to that affect).

### Describe alternatives you've considered

In a recent Feature Request, I was basically told to use another Indexer; though an option, ergo an alternative I've considered, it seems un-fair. Especially since the Indexer I use is one of the few listed in Sonarr by default 🤷‍♂️

I don't want to mark a new Show as unmonitored as this just means lots more manual clicks to get things moving and downloading.

**Comment by rsunde** [comment]
I deal with this/similar issue by adding certain lists with **Monitor: None**..
.. and then manually changing the monitor state accordingly.

but thinking about the problem at hand, this might be a solution;
1. add a tag called AUTOSEARCH or whatever to your import list(s).
2. in your indexer(s) add the tag from step 1.

**Comment by Minxster** [comment]
Thanks @rsunde that does give me an idea of having a null index that literally does nothing. Then when an import list adds something, it'll be blocked it from auto searching. The lists I'm using are my own heavily filtered lists, so I don't expect to get many new shows, maybe 1 every few months.

It would be nice to have some more control over these sorts of processes in Sonarr.
