### ISSUE TITLE
override for media in root folder

### ISSUE THREAD

**Issue by Tom-Neverwinter** [Sonarr/Sonarr#5889]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

media in root folder. 

I've run it this way for a decade starting with snazbeard so dont see any reason to change and no actual good reason was ever given for this claimed method

### Describe the solution you'd like

override for preventing media in root folder

### Describe alternatives you've considered

reverting back to previous version of sonarr. 

not wasting my time on claimed root media bad

**Comment by markus101** [comment]
You could disable completed download handling and have your client sort downloads to the root folder, but they'd be missing to Sonarr. We do not have plans to support media outside of series folders.
