### ISSUE TITLE
T411 Indexer: API Available

### ISSUE THREAD

**Issue by thibautd** [Sonarr/Sonarr#589]
Hello,

The T411 private tracker now provides an API (http://api.t411.io/). The API seams really simple to use and I would really enjoy to have an indexer for t411 available in Sonarr.

Would this be possible ?

Thanks,

**Comment by KiLMaN** [comment]
Take a look at : https://github.com/KiLMaN/T411-Torznab

**Comment by Taloth** [comment]
@thibautd I hope you can understand our reluctance to implement every indexer out there.
It would be much better if indexers/trackers implemented a standardised api specification, at least when recent/search is concerned.

**Comment by thibautd** [comment]
Thanks for your answers. Unfortunately I don't know C# else I could have make it. Maybe an "indexer scripting" tool in a scripting language could help to solve this kind of issue. But it's a lot of work :-)

**Comment by Diaoul** [comment]
[Until not so long ago](https://github.com/Jackett/Jackett/issues/93#issuecomment-159041208) Jackett used to support T411.
The code is available [here](https://github.com/Jackett/Jackett/blob/v0.6.45/src/Jackett/Indexers/T411.cs).
I guess it requires some work to be integrated in Sonarr but this is a good starting point for anybody interested.

**Comment by KiLMaN** [comment]
My tools is still in dev, but is still working for T411 : https://github.com/KiLMaN/T411-Torznab
I'm using it every day and it's works fine (for what i need) Feel free fork it off :) :+1:

**Comment by JigSawFr** [comment]
@KiLMaN very good, but it will be better to add it to https://github.com/Jackett/Jackett

;)
