### ISSUE TITLE
Add the ability to pin/favourite locations in Manual Import

### ISSUE THREAD

**Issue by kramttocs** [Sonarr/Sonarr#5891]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Windows 11. Latest version of Sonarr.
When obtaining files outside Sonarr, they are stored in a subfolder of X. This subfolder changes and is deleted by the import process automatically. 
When performing a manual import, the folder picker always starts with a list of the drives and requires navigation to the aforementioned subfolder. This requires a lot of clicking.

### Describe the solution you'd like

The ability to specify a default starting folder for the manual import process. In my case this would be X and would require a single click to select the subfolder.

### Describe alternatives you've considered

The manual import does save recently used folders but as these are the subfolders they often are no longer valid folders (deleted by the import process).
Just selecting X isn't ideal as there are other items and subfolders in X that I don't want Sonarr to try to parse.

**Comment by markus101** [comment]
A default location isn't something we're going to do as many people need more than one, but you can already achieve a default-ish behaviour by using your preferred location and then selecting it from recently used each time as a starting point.

We've discussed and a favourite locations so they remain at the top of the list, that would reduce the clicks, with the cost probably being an extra click once setup.

**Comment by kramttocs** [comment]
Pinning would be great!
Good point on people having multiple defaults.
Adding the ability to disable the mru would be great also. So I could pin 5 folders, disable the mru, and never see anything else in that list.

I say this under the assumption that if I had a pinned folder (parent), clicked it, then selected the child folder and imported, the child folder would show up in the list below the favorites? Which would be easily ignored but still not really needed.

**Comment by fryfrog** [comment]
![Screenshot 2023-08-08 at 12 07 02 PM](https://github.com/Sonarr/Sonarr/assets/87748/a803d890-bf55-43f7-845b-22c3e0060038)

^ This is how I'd do it!

I would also suggest that favorited paths should bubble up to the top *and* if you x them to delete, should pop up warning it is a favorite and are you sure you want to delete?
