### ISSUE TITLE
.5 episode imported as main episode

### ISSUE THREAD

**Issue by washedszn** [Sonarr/Sonarr#5893]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr imports episode `x.5` as episode `x`, instead of the actual episode `x`. 

### Expected Behavior

Sonarr imports episode 11.5 as episode 11, instead of the actual episode 11. 

Xem mapping = https://thexem.info/xem/show/5165

![image](https://github.com/Sonarr/Sonarr/assets/48860738/5ac392af-8fdf-4f58-a468-6fe6b2ac862a)

Also have this happening with other animes like Nura: Rise of the Yokai Clan

### Steps To Reproduce

Adding the following anime:

![image](https://github.com/Sonarr/Sonarr/assets/48860738/fb408e7a-6d8a-4035-b679-bbc113292697)

### Environment

```markdown
- OS: Ubuntu 20.04.2
- Sonarr: 4.0.0.603
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: not related
```

### What branch are you running?

Develop

### Trace Logs?

I don't have any trace logs, don't feel as though it is necessary for this bug. I asked on your discord first and they said it would be worth creating an issue for this as it's likely an easy change

### Anything else?

Issue is slightly related to #457. I imagine this could just be a simple change to a regex for ignoring `.5` after episode numbers, or treating them as specials if matched

**Comment by markus101** [comment]
Please provide the release names in text.

**Comment by washedszn** [comment]
`[TTGA] 86 - Eighty Six (2021) (Season 1 (EP: 01-11) + Special) [BD Remux] [1080p Dual Audio FLAC AVC] V2`

Episodes:

`S01E11.5 [SP]-The Poppies Bloom Red on the Battlefield.mkv`

**Comment by stevietv** [comment]
what if the title of the episode began with a 5? `show.title.s01e11.5.ways.to.eat.soup`

**Comment by washedszn** [comment]
Could cross check with the title of the anime. Can imagine there's access to the series title - possible to have a negative lookahead for that title?

**Comment by markus101** [comment]
There isn't, Sonarr has no knowledge of what it is until after parsing.

**Comment by markus101** [comment]
Are there other examples of this format being used or is this a one off scenario?

**Comment by washedszn** [comment]
English name is Nura: Rise of the Yokai Clan.

```
[Anime Time] Nurarihyon No Mago (S01+S02) [BD] [Dual Audio] [1080p][HEVC 10bit x265][AAC][Eng Sub]
    - [Anime Time] Nurarihyon no Mago - 12.5.mkv
    - [Anime Time] Nurarihyon no Mago - 24.5.mkv
    - [Anime Time] Nurarihyon no Mago - 12.mkv
    - [Anime Time] Nurarihyon no Mago - 24.mkv
 ```

Does seem to be a pretty rare scenario - happened only these 2 times out of 70 ish series

**Comment by mizz141** [comment]
It's definetly a more rare scenario since .5 episodes are usually used for Recap episodes and other Specials,

Searching nyaa for Web-DL's with a .5 episode there are around 65 results since 2012, but that easily extends onto BD releases since the naming usually is adapted.

In other even more rarer cases such as Eighty Six, there are multiple episodes with the .5 prefix, 11.5, 17.5, 18.5 and 21.5.

https://nyaa.si/?f=0&c=1_2&q=%22.5%22+Horriblesubs+1080p
https://nyaa.si/?f=0&c=1_2&q=%22.5%22+subsplease+1080p

**Comment by Ravencentric** [comment]
`n.5` is indeed commonly used in the anime scene to indicate `S00` or Specials.

and the naming scheme here `S01E09-Goodbye.mkv` (with no show name) isn't widely used. It's mostly isolated to the group [`[TTGA]`](https://nyaa.si/?f=1&c=1_2&q=TTGA)
