### ISSUE TITLE
 Creating custom format for Language Original is not possible

### ISSUE THREAD

**Issue by AntoineCardon** [Sonarr/Sonarr#5897]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When you try to add the Original language to a custom format it returns that
'Value' must be greater than or equal to '0'.

### Expected Behavior

It will let me add the Original language as a possible value. This would allow to create negative or positive filters that match the Original language

### Environment

```markdown
- OS: Linux Synology
- Sonarr:  4.0.0.604
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: 115.0.3
```

### What branch are you running?

Develop

### Trace Logs?

2023-08-09 17:13:06.6|Trace|SonarrErrorPipeline|Handling Exception
2023-08-09 17:13:06.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Value: 'Value' must be greater than or equal to '0'.

### Anything else?

Following https://github.com/Sonarr/Sonarr/issues/5886
and the commit https://github.com/mynameisbogdan/Sonarr/commit/d99a07c4e5b7401ed6b300a11608c27bbe26e48d#diff-a4fbb27b4497ed8fa52fe63bc688c012e161577b16c082b7435daf621a2d5f67R13

RuleFor(c => c.Value).GreaterThanOrEqualTo(0);

blocking creation of custom format with "original" lang, because this one as a value of '-2'

**Comment by markus101** [comment]
This regressed when allowing Unknown languages, because Original Language has a value of `-2`...
