### ISSUE TITLE
Parse and optionally strip year from TVDB show name 

### ISSUE THREAD

**Issue by brainiac19** [Sonarr/Sonarr#5899]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It's TVDB's rule that newer shows with names same as an old one should append (year) to its title. The thing is I configured sonarr to do all the scraping, while streaming service only read the .nfo file, which leads to that the \<title\> (\<year\>) is displayed as series title. Not a big problem, but quite inconsistent.

### Describe the solution you'd like

Add the capability to parse and optionally strip the (year) when writing metadata. If sonarr uses unique ids to handle shows then it should be an easy fix, if not then it will need to be discussed.

### Describe alternatives you've considered

Maybe parse the title when fetching data from TVDB, which can make sure the title in metadata is the same as within sonarr? But that'll very likely mess things up, so probably no go.

### Anything else?

I found this issue which could be relevant #5665 
Then there's the relevant TVDB rules https://support.thetvdb.com/kb/faq.php?id=15

> For remakes with new series entries please append the year of the remake to the end of the series to differentiate it from the original.

**Comment by markus101** [comment]
For file names you can use `{Series TitleTheWithoutYear}`, but for any metadata written Sonarr uses the title it uses for everything else (coming from TheTVDB).

Adding an option to not include the year in metadata generated by Sonarr is not something we're going to invest time in at this time. Perhaps an external tool offers this option.
