### ISSUE TITLE
Question about generic torrrent RSS parsing

### ISSUE THREAD

**Issue by callumgare** [Sonarr/Sonarr#590]
Hi,
I'm trying to work out what changes need to be made to bit-hdtv.com's (a private torrent tracker) feed in order for Sonarr to successfully parse it.
Mostly by trial and error, bouncing back and forth between Sonarr's log output and it's source code I have gotten Sonnar to accept the Bit-HDTV's feed when "Allow Zero Size" is set to yes. However I'm having trouble getting it to read the size.

This is an example of Bit-HDTV's unaltered feed: https://gist.github.com/callumgare/b088d4f424c3e45b33a2

And this is that same example with a couple of changes made: https://gist.github.com/callumgare/79e21a59a1c14208d1f1

Those changes are as follows (regex is the vim flavour):
- rename the "added" tag to pubDate and remove " Added: " prefix: 
  - `%s/<added> Added: /<pubDate>/g`
  - `%s/<\/added>/<\/pubDate>/g`

- copied contents of size field into the description field
  - `%s/\(<size>\)\(.\{-}\)\(<\/size>\_.\{-}\)\(<\/description>\)/\1\2\3\2\4/g`

Any idea what I need to change to get it to parse the size? A nudge in the right direction would be immensely appreciated.

Thanks a mill for such awesome software,
<3 callumgare

**Comment by markus101** [comment]
As long as size is part of the description Sonarr will be able to parse it, I ran a test to confirm that `Size: 685.67 MB` parses properly.

**Comment by Taloth** [comment]
Add timezone to pubdate (or +0000 if UTC), not critical, but preferred.

As for size, it's parsing the kbps mediainfo stuff, probably a bit too accepting :smile:
I also found some other inconsistencies in the parser with regards to Size, i'll shoot in an issue so we can look into that at a later date.
Anyway, you can fix that by adding ```<enclosure url=".." length="12319230" type="application/x-bittorrent" />```
 or rename ```<size>``` to ```<Size>```.

**Comment by Taloth** [comment]
Did some improvements on the develop branch.

Please note that that rss feed is a bit ugly with all those field with markup (Category:, Size:, etc) in there.

**Comment by callumgare** [comment]
Wonderbar! Thank you muchly :)
I've posted on the bit-hdtv forum and am awaiting a reply to try and change the feed.

**Comment by Taloth** [comment]
While you're at it point them at https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer :wink: if they can get their hands on tvrageids for each torrent :)

**Comment by callumgare** [comment]
Hmm, looks interesting. I've never heard of tvrage before. Is the tvrage official api the best place to fetch a torrent's id? I ask because at the time of writing the site seems a bit flakey. More often than not, hanging for a minute and timing out. Is this just a bad timing or is it typical? Archive.org's saves seem to drop off in 2014 http://web.archive.org/web/*/http://services.tvrage.com/info.php

**Comment by Taloth** [comment]
Nope it's not specific to torrents. It's just a site like thetvdb, but instead of following official guides it (mostly) follows the scene. In this case the only goal is to track which series a torrent belongs to.

Torznab has search queries by rageid+seasonnumber+episodenumber which is better than text wildcard searches. It allows efficient usage of bit-hdtv database indexes. But obviously the difficulty is to associate with the proper tvrageid with each torrent on the site, not something that's done in an afternoon.

**Comment by callumgare** [comment]
Are there any conventions or strategies to mapping ambiguous series names to a rageid? Or is the best/only approach about extracting as much information as you can from the file name of the torrent and using that to filter down the results to (hopefully) just one result?

**Comment by timeisapear** [comment]
@callumgare How are you dynamically generating the correctly syntaxed (pubdate field) RSS for Bit-HDTV consumption by Sonarr?
