### ISSUE TITLE
v4: release/push api results in a "waiting" state when there's a stuck NZB import

### ISSUE THREAD

**Issue by KyleSanderson** [Sonarr/Sonarr#5900]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Reproduced on a litany of versions, most recently 4.0.0.603. Presently when there's an ineligible for upgrade NZB sitting in Sonarr (through release/push), all future pushes seem to stall and are not added to the torrent client. Sonarr RSS and Manual don't appear to be impacted.

### Expected Behavior

When I delete the pending NZB in Sabnzbd, it shouldn't only then continue to send files to the torrent download client.

### Steps To Reproduce

SABnzbd and qBittorrent
release/push on NZB, wait until it doesn't upgrade but stay as "waiting to import" being ineligible, then release/push a torrent and it should give a clock. Delete the NZB from your download client, and the torrent should then submit.

### Environment

```markdown
- OS: lin6.1
- Sonarr: 4.0.0.603
4.0.0.582
4.0.0.559
4.0.0.526
4.0.0.448
4.0.0.435
- Docker Install: yes
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

I've tried, no manual triggers hit it. Not seeing any db corruption either.

**Comment by markus101** [comment]
A stuck import will be treated as being part of the queue, if that prevents a release from being grabbed, it's likely because Sonarr does not consider it an upgrade. Release push uses the same logic as RSS sync to determine if a release is eligible for grabbing.

Without at least debug logs showing the issue it's impossible to say what might've have happened.

**Comment by markus101** [comment]
Potentially related to https://github.com/Sonarr/Sonarr/issues/5598

Closing this until we have more actionable information.

**Comment by markus101** [comment]
Nice find, ID 0 is never valid so if we don't have an indexer ID then I think either `RecordFailure` should ignore it or we should never call `RecordFailure` to begin with. There is some value in trying to prevent additional grabs (and some indexers might get upset that we keep trying), but without the correct information I don't think we should try to do it.

Would it be worth upgrading the push debug logging from debug to a warning so that it'll maybe get fixed?

**Comment by KyleSanderson** [comment]
> Nice find, ID 0 is never valid so if we don't have an indexer ID then I think either `RecordFailure` should ignore it or we should never call `RecordFailure` to begin with. There is some value in trying to prevent additional grabs (and some indexers might get upset that we keep trying), but without the correct information I don't think we should try to do it.
> 
> Would it be worth upgrading the push debug logging from debug to a warning so that it'll maybe get fixed?

In my specific case, these are from Prowlarr which based on the behaviour today queues these up to be snatched as the limit naturally resets on a daily basis (so the next series of episodes are grabbed - if they were lost that would be tragic). The implication is right now it's blocking the entire pipeline as all indexers come in at id 0. I don't mind if Sonarr hits Prowlarr, but indeed as you mentioned I'd be quite perturbed if it kept hitting a tracker.

As cheap as it sounds, if the id is 0 can we just hash the indexer string and store that as the ID? It papers over a lot of existing code so I don't know the implications, but on paper as an ignorant end user it sounds like a fine idea.

**Comment by markus101** [comment]
> It's gonna fill the logs with warnings for autobrr users that have no control on the request body.

Unless the indexer name that autobrr provides can be matched to Sonarr's indexer name.

Where does autobrr get the indexer name it's sending to Sonarr?
Can Sonarr and autobrr not know the indexer by the same name?

If there is something we can do to make it so autobrr can communicate the indexer better so Sonarr can make use of it then we could look at doing that, but hashing the indexer name to fake an indexer ID is hacky at best and I don't think it should try to handle any failures from an unknown indexer.

**Comment by KyleSanderson** [comment]
> At this time autobrr sends the `identifier` from [their definitions](https://github.com/autobrr/autobrr/tree/develop/internal/indexer/definitions).

Kind of. There's also feeds from Newznab, Torznab, and RSS that prepend the respective "type" to the user entered string. I'm sure as it sits there's going to be additional identifiers in the future. These (real site) links are provided directly to Sonarr, without an indexerid set and with a `rss-bogdans-feed` indexer sent. If this is required to interact with Sonarr, even for these non-user facing strings, we're going to have to put additional thought into how data is stored internally.

Outside but related to the issue, we're also running up against this with downloadClientID. The hack we have is for the user to supply the (optional) number, which is far from ideal.

Personally speaking for the entirety below:

It sounds like there's some steps missing here for integrating calls with Sonarr in general. ID or a string can be provided in the API today for purposes of identifying the source indexer. One way to enforce this is to have a per client key, and have Sonarr optionally do an inflight check (return missing indexer or something to the caller, and warn the API client in Sonarr).

I'm suspecting autobrr is far from the only consumer of the API, so the entire ecosystem has to change if Sonarr is unable to handle this transparently. I don't know if this should be an API bump (breaking change == bump typically, which filling error logs would do), or if v4 has been marked as released yet.

The only other thought that comes to mind is base it on the URI and drop the concept of IDs and Names entirely. The caveat being there'd still be a hack in there for Jackett and Prowlarrs unique URL schemes, to uniquely identify the target site. There are sites that expose these endpoints natively as well, so perhaps it's a fools errand. 

Anyway, this is an ancient bug. For autobrr the string is stable from the product per indexer. Anything else would require active synchronization, which would then "leak" specified indexers to Sonarr, which I'm not sure is desired from a user perspective either (different source/upgrade profiles per "arr").

**Comment by markus101** [comment]
> That's why I suggested using the indexer name as key for the provider status.

We shouldn't use anything except the primary key for tracking status and changing the primary key would be a breaking change across the API.

The other issue with using the name is we could have multiple representations for the same indexer because Sonarr has one name for it and anything using the push API could have another.

> The only other thought that comes to mind is base it on the URI and drop the concept of IDs and Names entirely.

Dropping the ID and name is a breaking change, we could add support for looking up by URL, but as you mention Prowlarr and Jackett can proxy through different URLs and that would fall apart.

> For autobrr the string is stable from the product per indexer. 

The indexer name string?
Could autobrr send this as a different parameter than the indexer name so Sonarr can use it for matching by a different property on the indexer?

What if Sonarr added a tag-like field for "automation identifiers" that's used to lookup indexers based on the sender's unique and stable identifier?

This would require some initial configuration on the Sonarr (or Prowlarr side if syncing) to add autobrr's identifier, but then Sonarr could look up the indexer via that and we don't need to try and get user's to synchronize a name across different apps.

We still need to fix the bug of trying to report status for unknown indexers and anything unknown could be rejected and dropped, but if people want Sonarr to properly track indexer status for pushed items they have an option to configure that.

**Comment by KyleSanderson** [comment]
> > That's why I suggested using the indexer name as key for the provider status.
> 
> We shouldn't use anything except the primary key for tracking status and changing the primary key would be a breaking change across the API.

I haven't connected with him since spinning through this earlier last week, but I would suspect this is around using the indexer string for the "blocking" of indexers, as opposed to the id. The bug would still be there, but it would go back to the behaviour previous to the back-offs that were added.

> The other issue with using the name is we could have multiple representations for the same indexer because Sonarr has one name for it and anything using the push API could have another.

Yeah - we have the same problem with feeds. Each feed is considered a unique indexer to autobrr, and would be sent uniquely to Sonarr. They have the same consistent string for the indexer, but they're plentiful.

> > The only other thought that comes to mind is base it on the URI and drop the concept of IDs and Names entirely.
> 
> Dropping the ID and name is a breaking change, we could add support for looking up by URL, but as you mention Prowlarr and Jackett can proxy through different URLs and that would fall apart.

I misspoke, Sonarr could accept any combination of the three*, but autobrr could not send the indexer name to make it use the URI that's passed instead if that helps.

> > For autobrr the string is stable from the product per indexer.
> 
> The indexer name string? Could autobrr send this as a different parameter than the indexer name so Sonarr can use it for matching by a different property on the indexer?

We could, but I suspect the same headaches will remain unless if both sides are well maintained from a user configuration perspective.

> What if Sonarr added a tag-like field for "automation identifiers" that's used to lookup indexers based on the sender's unique and stable identifier?

We could send the list of indexers on startup and configuration modification. The one problem with this though is access to sonarr does not necessarily mean there's access to autobrr and vice-versa. Neither side has RBAC today, so this is an odd, but active limiting control. These would have to be considered half indexers (no search / etc), not modifiable by the client and only there for deletion - and they'd have to support a flag from a passed source (client configures autobrr, jackett, mylar, etc).

> This would require some initial configuration on the Sonarr (or Prowlarr side if syncing) to add autobrr's identifier, but then Sonarr could look up the indexer via that and we don't need to try and get user's to synchronize a name across different apps.

Yeah, the rub here is if it's manual I have around "70" indexers today, and if I was actually on-top of my stuff there would be over 160 in both clients. That's major fiddly work, right now we're (autobrr) lucky because it's hard to notice and sonarr naturally runs rss on its known indexers, which hides the issue well.

> We still need to fix the bug of trying to report status for unknown indexers and anything unknown could be rejected and dropped, but if people want Sonarr to properly track indexer status for pushed items they have an option to configure that.

The cheap hack for me is I'd create 2 bogus indexers, one for NZBs and one for Torrents and submit against those 2. Unless if we make a fairly significant investment in Sonarr integration (not saying it won't happen, but it's not necessarily cheap) as an end user that's what I would end up doing to "fix" my setup.

**Comment by markus101** [comment]
> Yeah, the rub here is if it's manual I have around "70" indexers today, and if I was actually on-top of my stuff there would be over 160 in both clients.

Yeah, keeping it all in sync sounds like a pain.

Marked this as a bug so we can fix the underlying issue, but I don't think it makes sense to try and block a pseudo indexer that a user can't test or unblock.

**Comment by KyleSanderson** [comment]
Nice one - thank you.

**Comment by KyleSanderson** [comment]
Are you sure this is fixed? I'm seeing the same behaviour on 4.0.0.710

**Comment by markus101** [comment]
Sonarr won't add more instances, but anything remaining will be a problem, I'll add a migration to remove the old data.

**Comment by markus101** [comment]
Yeah, saw I missed that as well.
