### ISSUE TITLE
Freeze Top Row on Series List

### ISSUE THREAD

**Issue by bifa2** [Sonarr/Sonarr#5901]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The table view of all series could benefit from a fixed table header option, to help with lots of columns and/or lots of series.

### Describe the solution you'd like

Under "Table options" (when viewing all series) adding an option to freeze the top row.

### Describe alternatives you've considered

N/A

**Comment by bifa2** [comment]
Adding the following CSS to the element: `#root > div > div.Page-main-3AyGO > div.PageContent-content-B3Bmu > div.SeriesIndex-pageContentBodyWrapper-1tN6d > div > div.SeriesIndex-contentBody-2lSSk.PageContentBody-contentBody-1kgeZ > div.SeriesIndex-tableInnerContentBody-2rJI5.PageContentBody-innerContentBody-V-w79 > div > div.SeriesIndexTable-tableContainer-CjzmI.VirtualTable-tableContainer-HXhSR.Scroller-scroller-_8_uO.Scroller-horizontal-3VThA.Scroller-autoScroll-2_rs9 > div.VirtualTableHeader-header-2KbSq` using Chrome dev tools:

```
    position: fixed;
    z-index: 100;
    background-color: #4f566f;
    color: white;
```

... gets some of the way, but there are two issues with that:

1) Not all columns are highlighted, but they are fixed:
![image](https://github.com/Sonarr/Sonarr/assets/54040596/bcc4a665-5c05-427b-92e0-463dba569c31)

2) When scrolling, the series goes behind the header:
![image](https://github.com/Sonarr/Sonarr/assets/54040596/ca181d1b-ef01-471e-a933-746dc3c3b662)

**Comment by markus101** [comment]
To do this right it would require a significant redesign of the UI to support `position: sticky`, but that's not something we're going to commit to doing at this time.
