### ISSUE TITLE
Searching for whole season downloads all search hits.

### ISSUE THREAD

**Issue by Nilleftw** [Sonarr/Sonarr#591]
Hey,

So I've tried the "Search for all episodes in season X" thing a few times. And sometimes it just freaks out and downloads **everything** it finds. Like now when I tried to download the first season of Gotham, Sonarr decided to download 784 torrents. So now it's basically crashing Deluge over and over again. 

Seems to be easiest to reproduce with Gotham. A quick read through the logs made it seem like Sonarr didn't like how long the file names were. Tried downloading a single episode and ended up with 31 torrents in Deluge.

Logs: [ProcessDownloadDecisions](http://pastebin.ca/3016645) and [ImportApprovedEpisodes](http://pastebin.ca/3016648).

Sonarr version 2.0.0.3154 (Host OS), Deluge 1.3.11 (VM)

**Comment by markus101** [comment]
We use our forums for support.

Deluge is returning an error to Sonarr's request (although it sounds like it actually accepts the torrent) so Sonarr tries a different one. Check Deluge's logging for more details.

The import issue looks to be it trying to create a file that is too long, maybe the file name is too verbose or the structure is too long.

Open a thread in the forums if you need anything else.
