### ISSUE TITLE
Different Colour on Calendar when Cutoff hasn't been met

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#592]
Similar to how we have a different colour for season premiere's this would let people differentiate between something thats met the cutoff and something that hasn't right from the calendar.

Dark green when cutoff hasn't been met and keep the existing green for when it has.

**Comment by ewascome** [comment]
+1

**Comment by Toxic-Waste-** [comment]
this is a good idea, but would it be possible to use it in the series overview aswell? That you have 2 progress bars or it has different colours, so you can see in a blink which TV show has all the episodes where the cutoff is met and which one is downloaded but below cutoff quality? 

For me this would be perfect as I can see in an instant which shows still need to be upgraded from HDTV to BluRay quality :)

**Comment by markus101** [comment]
This is done in the v3 work.
