### ISSUE TITLE
Recycle bin per root folder

### ISSUE THREAD

**Issue by bbtufty** [Sonarr/Sonarr#5926]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This is mentioned in #1984, but as a specific issue if you have sonarr across multiple root folders on different volumes the recycle step can be very slow since it needs to move from one volume to another. With tags, you can get downloads to different folders so the import step is fast, but the recycle step remains slow

### Describe the solution you'd like

The most general solution I see would be to have a recycling bin defined per root folder, perhaps where those are set up:

> Path - Recycle Bin - Free Space - Unmapped Folders
> /vol1 - /vol1/recycle - XTB - 0
> /vol - /vol2/recycle - XTB - 0

Alternatively some way to may the current recycling bin box to different root folders would also work

### Describe alternatives you've considered

I've tried merging recycling bins over multiple volumes using mergefs but a) sonarr doesn't see this and b) because it checks paths to decide whether to move or copy (as far as I understand), this solution won't work

**Comment by bakerboy448** [comment]
> merging recycling bins over multiple volumes using mergefs but a) sonarr doesn't see this 

this is your easiest solution. if sonarr can't see it then your mergerfs command does not allow the user and group sonarr is running as to access the drive.

**Comment by bbtufty** [comment]
> best case would be the move your whole setup to mergerfs if using multiple drives. it makes things signifcantly simplier

I've just done this on top of the multiple volume download directories (keeping libraries separated so I can still tell where the files actually are), and that seems to be working. Thanks for the suggestion here, speedy imports are back!
