### ISSUE TITLE
Import List Sync intervals

### ISSUE THREAD

**Issue by MaelRivera** [Sonarr/Sonarr#5927]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Import List Sync runs currently every 5 minutes. Even when there are no lists

![Screenshot 2023-08-15 144252](https://github.com/Sonarr/Sonarr/assets/142318345/f00247d2-5d1a-465a-b491-17f3095984e6)

### Describe the solution you'd like

Is there a way to set it to run at longer intervals? Perhaps a configurable option like Radarr has - List Update Interval?

Or even disabling the service altogether when no lists are found?

Thanks!

### Describe alternatives you've considered

.

**Comment by MaelRivera** [comment]
Thanks.

Reduced logging could be an option.

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/927ae86e4415455ca94cdabe0b3d93f1eaf33df1 looks like it may knock this out?

**Comment by markus101** [comment]
Looks like that's solving a different issue with empty lists resulting in movies being cleared.
