### ISSUE TITLE
Additional view in the calendar

### ISSUE THREAD

**Issue by NMe84** [Sonarr/Sonarr#593]
Sometimes, an upcoming episode is missing from Sonarr because it is not on TVDB yet. To identify these problems, I use the calendar so that I can compare what aired last week to what airs this week and fill in any gaps. This is pretty annoying in the first week of the month, however, because I can't simply scroll up to see last week.

I think it would be nice to have another view on the calendar in addition to "day", "week" and "month" where you display the previous week, the current week and possibly next week.

**Comment by markus101** [comment]
Looks like this might be possible via a [custom view] (http://fullcalendar.io/docs/views/Custom_Views/) for the calendar (after https://github.com/Sonarr/Sonarr/issues/469), but I'll let Taloth weigh in before accepting it.

**Comment by Taloth** [comment]
Personally I think this a 1% feature. why not just open two windows? :confused:

**Comment by NMe84** [comment]
I would, but Sonarr is not very well-suited to run in multiple tabs or windows. As per your own suggestion I avoid doing that whenever I can. Even if I don't did open a new tab, loading it up from the spinner on its black background takes well over 10 seconds on my system.

I realize it's a feature that is not exactly going to be required for 95%+ of your users but at the same time: making this easier to spot for me and people like me means that problems on TVDB can be fixed before they actually arise, which in turn makes using the software more enjoyable for everyone. Much like [issue 486](https://github.com/Sonarr/Sonarr/issues/486) in that respect. :)

**Comment by markus101** [comment]
Not going to do a two week calendar view, but there will be an Agenda view that may be useful in this scenario.
