### ISSUE TITLE
Hidden Files Are Ignored

### ISSUE THREAD

**Issue by hellot1m** [Sonarr/Sonarr#5931]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

any video file that starts with a period are not being identified through Sonarr v4. This issue has been present for a long time (probably started during the transition between v3 to v4) but i have ignored it thinking i was just getting bad grabs. Full conversation of this issue and steps taken were discussed in the support channel on discord starting **[here](https://discord.com/channels/383686866005917708/383688189941907459/1141468643704701008)**

### Expected Behavior

Per a previous fix in 2017, the period at the beginning of a filename are to be ignored, allowing sonarr v4 to view all video files within a grab. The fix for this in 3.0.9 is found **[here](https://github.com/Sonarr/Sonarr/commit/8bc55c5305ca0f6526341b8a04c16f2c7947e133)**

### Steps To Reproduce

1. Open Sonarr 4.0.0.629
2. Most common grabs presenting this issue are obstructed grabs. the grab i used while discussing my issue on discord was from xpost with an anime called "Undead Murder Farse episode 7"
3. import fails with no video files found (can't remember the exact message)

### Environment

```markdown
- OS: Unraid 6.11.5
- Sonarr: 4.0.0.629
- Docker Install: cr.hotio.dev/hotio/sonarr:v4
- Using Reverse Proxy: No
- Browser: Netscape Navigator
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.trace.7.txt](https://github.com/Sonarr/Sonarr/files/12364191/sonarr.trace.7.txt)

### Anything else?

Discord Conversation: **[Click Here](https://discord.com/channels/383686866005917708/383688189941907459/1141468643704701008)** 
Previous Fix for same issue: **[Click Here](https://github.com/Sonarr/Sonarr/commit/8bc55c5305ca0f6526341b8a04c16f2c7947e133)**

**Comment by markus101** [comment]
Pretty sure this is related to changing to `EnumerateFiles` as the default apparently excludes hidden/system files.

https://learn.microsoft.com/en-us/dotnet/api/system.io.enumerationoptions.attributestoskip?view=net-7.0#system-io-enumerationoptions-attributestoskip

**Comment by bakerboy448** [comment]
@markus101 https://github.com/Sonarr/Sonarr/commit/d493f8762fcb1684b44e182753c21d7a493db787 fixed?
