### ISSUE TITLE
Title slug collision: Animaniacs (1993) and Animaniacs (2020)

### ISSUE THREAD

**Issue by origintopleft** [Sonarr/Sonarr#5932]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I can't download both the original and Hulu reboot of Animaniacs at the same time. I get this error: `Title slug 'animaniacs' is in use by series 'Animaniacs'. Check the FAQ for more information`

According to Google, this is not user serviceable and I have to file an issue. 

### Expected Behavior

I expected the year of the reboot to be automatically appended to the show's title slug (which I'm assuming is the directory name). 

### Steps To Reproduce

1. Monitor Animaniacs (1993)
2. Monitor Animaniacs (2020)

### Environment

```markdown
- OS: Fedora 37
- Sonarr: 3.0.10.1567
- Docker Install: no
- Using Reverse Proxy: no
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

N/A, not a "bug" per se, but "Title Slug Conflict" was not a template. 

### Anything else?

Sonarr lists the two series as separate, but TVDB has them as one series. https://thetvdb.com/series/animaniacs

This might be part of our problem.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

As covered whenever duplicate slug issues are posted. TheTVDB's rules require series with the same name from subsequent years to have the year appended to the duplicate titles, but if the 2020 series was already removed from TheTVDB, remove it from Sonarr and only add the 1993 series.

The duplicate slug prevents other issues where you have colliding names, though it'll likely change int he future with a change to Skyhook.

**Comment by bakerboy448** [comment]
For Posterity - the FAQ link the error references
https://wiki.servarr.com/sonarr/faq#title-slug-in-use
and the specific instance markus described
https://wiki.servarr.com/sonarr/faq#duplicate-names-no-year

**Comment by origintopleft** [comment]
Sorry to bother you.
