### ISSUE TITLE
Suggested improvements to Interactive Manual Import - Fill multiple entries at once

### ISSUE THREAD

**Issue by Baa14453** [Sonarr/Sonarr#5938]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When using the interactive manual importer, sometimes it can't auto-detect the series I'm importing.
When this happens, it will give me the list of files, but I'll need to manually input the Series, Season, Release Group etc.

Usually when I'm doing this, I'll be importing a single directory's files which are all from the same series, Season, and Release Group. However, there is no way to quickly enter these for every file listed, I have to do it manually for each individual file, which takes a long time.

### Describe the solution you'd like

I can tick multiple files on the left, if editing the series for one file applied that edit to all files ticked then this process would be much faster.

### Describe alternatives you've considered

Well, I do it manually right now...

### Anything else?

If I've not explained this clearly enough let me know...

**Comment by PearsonFlyer** [comment]
You can do this by using the drop-downs at the bottom of the screen already.

**Comment by Baa14453** [comment]
> You can do this by using the drop-downs at the bottom of the screen already.

Ah that's exactly what I needed, thanks.
