### ISSUE TITLE
Suggested improvements to Interactive Manual Import - Tab switching and hotkeys for data entry

### ISSUE THREAD

**Issue by Baa14453** [Sonarr/Sonarr#5939]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Complimentary to my other suggestion #5938:
When using the interactive manual importer, sometimes it can't auto-detect the series I'm importing.
When this happens, it will give me the list of files, but I'll need to manually input the Series, Season, Release Group etc.

One reason this process is very slow is the lack of keyboard controls and hotkeys available. The physical process looks a bit like this:

1. Use the mouse to click on the first piece of missing information e.g. the first file's Series.
2. Switch to the keyboard to type in the name.
3. Switch to the mouse to click the first result.
4. Use the mouse to click the next piece of missing information.

It's a lot of switching between mouse and keyboard etc.

### Describe the solution you'd like

I should be able to:

- Use Tab to scroll through text input boxes starting from the top-left and working my way to the right and downwards.
- Once I'm on an entry I'd like to fill I should be able to press Spacebar or Enter to open the dialogue box.
- Then I press Enter to complete.
- Then I tab to the next box.
The above is normal behaviour you see from desktop applications etc.

In addition, we could make this better by:
 - Press Space to open the first missing field, starting from the top-left, moving right and then downwards.
 - Type the name, press enter to confirm.
 - Press Space again to open the next field.

### Describe alternatives you've considered

Currently I use the initial method I described.

### Anything else?

Well my initial issue was immediately resolved because I missed a UI element so I don't need these hotkeys so quickly now, but it might still be useful for someone.

**Comment by markus101** [comment]
This is an interesting idea, but not something we're going to commit to undertaking at this time.

**Comment by Baa14453** [comment]
ok cool
