### ISSUE TITLE
Include Status Message When Qbit is Downloading Metadata

### ISSUE THREAD

**Issue by ManiMatter** [Sonarr/Sonarr#5940]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hi,

In qBittorrent, there is a status called "METADATA". Downloads that fail to fetch metadata may strand in this status forever, for instance when trackers are dead or no seeders are available.

In Sonarr/Radarr, the status that is shown for these downloads is "QUEUED".
Therefore, it is not possible to differentiate between such "broken" torrents and those that are truly queued.

I would like to run a script that kills downloads that are in the "METADATA" state for too long, but for that I'd need to have more information on the /api/v3/queue-response.

Here is what the /api/v3/queue response contains currently for a download in "METADATA" state as per qBittorrent:
```
      "status": "queued",
      "trackedDownloadStatus": "ok",
      "trackedDownloadState": "downloading",
      "statusMessages": [],
```

The tracelogs from Sonarr shows that in the response to the call to qBittorrent, the relevant information would be available:

> 2023-08-18 19:31:51.2|Trace|HttpClient|Res: [GET] http://qbittorrent:8080/api/v2/torrents/info: 200.OK (7881 bytes) (7 ms)
> 2023-08-18 19:31:51.2|Trace|HttpClient|Response content (7881 bytes): 
> [...] "state":"metaDL" [...]

### Describe the solution you'd like

I would like that on the response from /api/v3/queue I can distinguish between a) queued torrents and b) torrents that stuck fetching metadata . This applies both to RADARR and SONARR.

Right now, both are coming through as "Queued".

Suggest to add the following status message: "qBittorrent is downloading metadata" such that the two queue-statuses can be separated

A download that is in qBittorent marked as "MEDATADA" would then return the following response on /api/v3/queue:
```
      "status": "queued"
      "statusMessages": ["qBittorrent is downloading metadata"]
```

A download marked in qbittorrent as "QUEUED" would return:
```
      "status": "queued"
      "statusMessages": []
```

### Describe alternatives you've considered

Writing a script that hits the qbittorrent API directly

**Comment by markus101** [comment]
We're not going to introduce a new status to track when a download client is downloading metadata because Sonarr doesn't need to track that separately. If this level of granularity is needed you can refer to the Qbittorrent UI or API directly.

We already show that qbit can't resolve magnet links when DHT is disabled and the status is `metaDL`, so I'm not opposed to adding a status message to the effect of `qBittorrent is downloading metadata`.

**Comment by ManiMatter** [comment]
a status message would work perfectly. Let me update the initial request to reflect his
