### ISSUE TITLE
Rating for All Series is Zero

### ISSUE THREAD

**Issue by pven** [Sonarr/Sonarr#5947]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I look in the list shown all the series in table-format, I can select an option to show the rating. This rating shows 0% for all series.

### Expected Behavior

I want to have a realistic rating, or the rating from ie IMDB of TvDb

### Steps To Reproduce

Go to the series-overview
Select Rating in Options
Look at the rating that is shown

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- Sonarr: 3.0.10.1567
- Docker Install: 3.0.10.1567-ls204 by linuxserver.io
- Using Reverse Proxy: no
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

NA

**Comment by thezoggy** [comment]
ratings come from tvdb, but right now with tvdb v4 api their ratings are broken due to how things are calculated. so for now they are disabled on sonarr's skyhook side. which is why they are all 0%.

**Comment by markus101** [comment]
The bigger problem is TheTVDB has removed ratings from their site, anything that is there is limited to pre-site upgrades anyways.

TMDb is likely the only option for this because $150k/y for IMDB data is a little pricey... we'll need to see how feasible this would be.

**Comment by bakerboy448** [comment]
Perhaps https://developer.imdb.com/non-commercial-datasets/ for IMDb?

otherwise tmdb should be pullable

**Comment by tonyrking** [comment]
tvcharts.co is specific for ratings also. I believe they use the imdb identification method too. Might tie in rather nicely.

**Comment by markus101** [comment]
Skyhook now returns IMDB's ratings for series that have a matching IMDB ID, updated daily.
