### ISSUE TITLE
Import Season Deletes Episodes before Importing

### ISSUE THREAD

**Issue by GioCirque** [Sonarr/Sonarr#5949]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I've searched for, downloaded, and imported a season pack for a show multiple times. Each time it imports 10/12 episodes and deletes the other two. The two deleted seem to be randomly selected.

### Expected Behavior

All applicable files are imported before they are deleted.

### Steps To Reproduce

1. Add a show to the library
2. Manually search for a season pack
3. Select it for download
4. Wait for it to download
5. Observe the download client still has the files
6. Observe the Events in the System section indicating that multiple episodes couldn't be found for import
7. Observe the download client folder has been deleted
8. Observe the missing episodes
9. Repeat hoping it'll not randomly delete downloaded content

### Environment

```markdown
- OS: Ubuntu 22.04.3
- Sonarr:3.0.10.1567-ls203 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Main

### Trace Logs?

I wasn't expecting the issue, so I wasn't tracing.

### Anything else?

This seems like a for loop calling an async method without an await and then calling a delete after the loop. It mostly works, but the ways in which it doesn't are extremely frustrating and unpredictable.

**Comment by markus101** [comment]
Please elaborate on your setup. Sonarr doesn't actually mark a download for deletion until all episodes in the season are imported, unless you're downloading the same release multiple times. This is not something that has been reported en masse and season packs are very common so without logs showing exactly what Sonarr saw and did it's going to be impossible to investigate.

**Comment by markus101** [comment]
Closing as we don't have anything actionable at this time.
