### ISSUE TITLE
Ability to refresh library in Plex/Kodi/Emby

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#595]
We should provide a way to rescan the entire library (possibly a single series) with the click of a button in the UI, which would force a refresh in the enabled media centers (ones with on download enabled?).

**Comment by ecnahc515** [comment]
Sonarr already can cause plex to refresh it's library on snatch/DL, I also think that applies to Kodi/XBMC as well. I don't see why you need a button in the UI for this when you can simply use the UI in Plex/Kodi to refresh.

**Comment by M0UL** [comment]
adding the automatic updating of plex/kodi when episode/series is deleted/renamed whould  be great.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR

various alternatives exist.
