### ISSUE TITLE
Custom Filter "Language: Original" always selects English

### ISSUE THREAD

**Issue by imanel** [Sonarr/Sonarr#5954]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After creating custom filter for [Original Language](https://trash-guides.info/Sonarr/Tips/How-to-setup-language-custom-formats/#language-original-only) all non-English releases are rejected, leaving only English versions, no matter the original language.

Examples:
- [Cyberpunk: Edgerunners](https://thetvdb.com/series/cyberpunk-edgerunners) - language JP, [rejected](https://i.postimg.cc/hJc2jMwY/Screenshot-2023-08-24-at-01-13-56.png)
- [The King's Avatar](https://thetvdb.com/series/the-kings-avatar) - language CN, [rejected](https://i.postimg.cc/HrGZGTtd/Screenshot-2023-08-24-at-01-16-01.png)
- [Battlestar Galactica](https://thetvdb.com/series/battlestar-galactica-2003) - language EN, [accepted](https://i.postimg.cc/tg2ktdK9/Screenshot-2023-08-24-at-01-35-52.png) (while other languages rejected)

Additional observation: multi-language and unknown languages are always accepted.

### Expected Behavior

Language selected should match TVDB.

### Steps To Reproduce

1. Import [Language: Original Only](https://trash-guides.info/Sonarr/Tips/How-to-setup-language-custom-formats/#language-original-only) Custom Filter
2. Set it to score "Language: Not Original" -10000 in [Quality Profile](https://i.postimg.cc/3x3bXwkC/Screenshot-2023-08-24-at-01-38-55.png)
3. Manually search for episode in non-EN series
4. Non-EN releases will have negative score, while EN releases will remain not impacted

Modification for false positive:
3. Manually search for episode in EN series
4. Non-EN releases will have negative score, while EN releases will remain not impacted (proving that it's not reverse filter, but always-EN filter)

### Environment

```markdown
- OS: QNAP
- Sonarr: 4.0.0.646
- Docker Install: Yes (linuxserver/sonarr:develop)
- Using Reverse Proxy: No
- Browser: Safari 16
```

### What branch are you running?

Develop

### Trace Logs?

None generated

### Anything else?

Perhaps it's related to fix to [this regression](https://github.com/Sonarr/Sonarr/issues/5897)?

**Comment by markus101** [comment]
Please provide the relevant logs.

**Comment by imanel** [comment]
The only two lines I get on manual search request are:
```
[Info] ReleaseSearchService: Searching indexers for [The King's Avatar : S01E01 (01)]. 3 active indexers 
[Info] DownloadDecisionMaker: Processing 64 releases 
```

Log level is set to Trace, and I even restarted server just in case, as it's suspiciously low number. I'm using Prowlarr (1.8.3.3880) for search, but that shouldn't impact filtering, right?

**Comment by markus101** [comment]
Those look to be console logs, which don't show trace logs unless configured directly in the file, you need to upload the trace log file and link it here. The wiki link in the template contains more information.

**Comment by imanel** [comment]
Managed to find it. Here's the log from this manual search:
https://gist.github.com/imanel/8e3fd6a478397d9000ccb9b7b6b72535

**Comment by imanel** [comment]
Interesting part is that there's plenty of lines like this:
```
Language couldn't be parsed from release, fallback to series original language: English
```
Meaning that for some reason [this series](https://thetvdb.com/series/the-kings-avatar) is seen as a series in English, despite what TheTVDB says.

**Comment by imanel** [comment]
Just as a sanity check I removed the series and added it again, and now it works correctly:
```
Language couldn't be parsed from release, fallback to series original language: Chinese
```
Is it possible that my database got corrupted at some point? I have it for quite a while. Is it possible to rebuild all metadata, without a need to re-add all series from scratch?

**Comment by imanel** [comment]
Ok, not sure what happened, but after all of those operations and running "refresh all" once again, it's working flawlessly now, so it looks like it was an issue with my configuration. It's a bit weird that previous refresh did not fixed the problem, but since it got away I will close it for now to not bother you, and monitor the situation. Thanks for your support!
