### ISSUE TITLE
Support preserving title tag when renaming subtitle files

### ISSUE THREAD

**Issue by JeWe37** [Sonarr/Sonarr#5955]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Jellyfin allows for the [specification of the titles](https://jellyfin.org/docs/general/server/media/external-files/) of subtitle files
> Any arbitrary text not parsable to a language or flag will be combined and used as the title of the stream (if there is not a stream title already embedded in the file metadata).

These titles, if present on existing imported subtitle files, will not be properly preserved when a Sonarr rename operation is executed. 

### Describe the solution you'd like

Sonarr should parse these titles and include them when renaming of the episode is requested.

### Describe alternatives you've considered

Can't think of any.

### Anything else?

This is especially nice for extracting subtitle files from media files, as the subtitle streams are often tagged with identifying information as a title, such as whether they are commentary tracks or the like.

**Comment by bakerboy448** [comment]
Example names? standard language tags are already supported 

xyz.en.srt
xyz.en.forced.srt
xyz.en.sdh.srt
xyz.en.hi.srt

https://github.com/Sonarr/Sonarr/commit/b20e247feb24084348261ef2fad61a05f1fd69e8
https://github.com/Sonarr/Sonarr/commit/3141bf7f9d8afcce676c3fbfccbde66e5b317b2b

**Comment by JeWe37** [comment]
EPISODENAME.Full Subtitles.eng.default.srt
EPISODENAME.eng.Signs & Songs.forced.ass

**Comment by JeWe37** [comment]
I don't follow, I'm not sure we mean the same thing. What I mean is that with current Sonarr the following will happen: 
```
EPISODENAME.Full Subtitles.eng.default.srt > EPISODENAME.eng.default.srt
EPISODENAME.eng.Signs & Songs.forced.ass > EPISODENAME.eng.forced.ass
```
In my testing sure the matcher itself was sufficiently robust to handle this without issue. The issue is that the title tags are lost.

**Comment by JeWe37** [comment]
Maybe it'll be clearer when I explain what actually needs to change in the code:
The LanguageTags parser needs to be changed to take anything that isn't a language tag but still isn't just the part of the name of the corresponding EpisodeFile and put it into the SubtitleFile as a title. From there that title needs to be used in rename operations, if it is present, and added to the list of tags.

**Comment by markus101** [comment]
Is support for this style of naming limited to Jellyfin/Emby or do Plex and Kodi also support it? If it's only the former I'm inclined to not handle that as it's not a standard implementation and could lead to files being renamed incorrectly for the majority of users.

**Comment by JeWe37** [comment]
I can't test Plex, but according to https://www.reddit.com/r/PleX/comments/p28jp2/proper_external_subtitle_filename_if_using/ it would just not be used and otherwise fine. Kodi for its part seems to [support this](https://forum.kodi.tv/showthread.php?tid=347361). Jellyfin is just what I happen to use. 

Parsing would definitely have to be investigated. I'd definitely limit this to existing extras only, which should somewhat help. Beyond that I guess it's best to check how Kodi and Jellyfin do it.

**Comment by JeWe37** [comment]
My educated guess at what those do is essentially require that the filename be the episode file name plus tags/title and extension. The issue is that currently Sonarr's requirements for considering something an existing extra are loser, it only needs to be parsable to the same episode as the media file it is matched with. An option would be first trying stricter parsing with by some definition closely matching filenames, which could extract the episode title, then failing that try parsing as is currently done and do not try to extract a title.

**Comment by JeWe37** [comment]
Having thought this over some more, the following algorithm might work: Take all known dot-separated subtitle tags and exactly one unknown tag that serves as the title. Whatever remains try parsing to an episode/season. If that fails, fail, and revert to the current logic. If it works, accept the data as parsed. This should only incorrectly parse titles if the file name contains dots that aren't supposed to be part of the tags at all and no title tag, which should be acceptable.

**Comment by markus101** [comment]
For existing files (wouldn't work with https://github.com/Sonarr/Sonarr/issues/4931) you could trim the extension and rely on a match that way, if that doesn't find a match then do the fallback.

**Comment by JeWe37** [comment]
I've been messing with this a little... I do have a draft of what could work, the issue with my initial idea of requiring the name to match is that this is supposed to be useful for renaming, i.e. exactly when it doesn't match. I guess I'll drop another draft PR later.
