### ISSUE TITLE
Sorting on Activity Queue does not actually sort

### ISSUE THREAD

**Issue by cwanja** [Sonarr/Sonarr#5960]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When viewing the current Activity Queue, if you sort ascending or descending, nothing in the UI changes to follow the sorting behavior you have selected the UI to do. Looks to effect all columns.

### Expected Behavior

The column that you are sorting would comply with the desired sort order. 

### Steps To Reproduce

1. Open Sonarr
2. Go to Activity > Queue
3. Click on a column to sort, and notice no change. Click again and see no behavioral change.

### Environment

```markdown
- OS: Ubuntu
- Sonarr: 3.0.10.1567
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Safari from macOS
```

### What branch are you running?

Main

### Trace Logs?

https://hastebin.com/share/cujetowobu.bash

### Anything else?

![Screenshot 2023-08-24 at 2 43 38 PM](https://github.com/Sonarr/Sonarr/assets/54645561/6009ac59-5733-4ba0-af79-f5230f48150b)
![Screenshot 2023-08-24 at 2 43 32 PM](https://github.com/Sonarr/Sonarr/assets/54645561/cbef04ae-a848-43cb-ad75-128647a1a956)

**Comment by markus101** [comment]
This has already been addressed in the v4 beta.
