### ISSUE TITLE
Streaming platform for shows

### ISSUE THREAD

**Issue by lamergamerx** [Sonarr/Sonarr#5966]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When adding a show or even on shows already added have a section near info that tell whether or not the show is streamed on a platform and which, or if available only on the original tv station or such.

I noticed today that i have shows that are streamed on platforms i have access to. Such a feature would save time and bandwidth.

### Describe the solution you'd like

Add info on what platform a show is streamed. 

### Describe alternatives you've considered

A link to a tv series search engine or such to manually search what platform would be streaming the show.

**Comment by markus101** [comment]
This data isn't something we currently have available, might be something we could get, but not something we're going to commit to doing at this time.
