### ISSUE TITLE
`includeSeasonImages` is not working when fetching a single series

### ISSUE THREAD

**Issue by JagandeepBrar** [Sonarr/Sonarr#5971]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When fetching the list of series (`/api/v3/series`), you can pass the query parameter `includeSeasonImages` to include the season images for each series.

However when passing the same query parameter when fetching a single series (`/api/v3/series/{id}`) this query parameter is not respected and no season images are returned with the series.

### Expected Behavior

`includeSeasonImages` should be respected and season images should be included when fetching an individual series by ID.

### Steps To Reproduce

1. Fetching the series list (`/api/v3/series`) with the query parameter `includeSeasonImages` set to true
2. Find a series that has a season poster image
3. Fetch the series by ID (`/api/v3/series/{id}`) with `includeSeasonImages` set to true to see no season images are included

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.0.629
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

Not really relevant here but can be supplied if really needed.

### Anything else?

<img width="500" alt="Screenshot 2023-08-28 at 11 45 10 AM" src="https://github.com/Sonarr/Sonarr/assets/3048295/d0405bd5-087c-4150-b1cc-65b1edbc377e">

<img width="500" alt="Screenshot 2023-08-28 at 11 45 22 AM" src="https://github.com/Sonarr/Sonarr/assets/3048295/32b41193-6a5d-4e51-93a8-f12602a1eabd">

**Comment by markus101** [comment]
@Qstick @mynameisbogdan this is happening because of removing https://github.com/Sonarr/Sonarr/blob/v3/src/Sonarr.Api.V3/Series/SeriesModule.cs#L130 since `RestGetById` is handled by the base `RestController` overriding this is a little trickier and just trying to handle it directly in `SeriesController` will cause duplicate routes.

**Comment by markus101** [comment]
Yeah, that's why I didn't go with that fix as we should have the docs reflecting it correctly as well.

**Comment by markus101** [comment]
We don't have local images for seasons currently.

**Comment by JagandeepBrar** [comment]
@mynameisbogdan thanks for the heads up and the fix! No worries on my end, easy for me to just check for the existence of either property.
