### ISSUE TITLE
Please fix cors errors

### ISSUE THREAD

**Issue by rainepretorius** [Sonarr/Sonarr#5974]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Requests to sentry.sonarr.tv fail from local address and external domain. See the attached screenshot. This behaviour makes the UI extremely slow and unable to use Sonarr.
![image](https://github.com/Sonarr/Sonarr/assets/64652244/933fc633-d033-4f84-9bef-eb34f70f1892)

### Expected Behavior

Should have a function to add your IP address and external domain to sentry.sonarr.tv's cors.

### Steps To Reproduce

Running in truenas Jail.
Going through nginx reverse proxy.

### Environment

```markdown
- OS: Truenas Jail
- Sonarr: 3.0.10.1567
- Docker Install: No
- Using Reverse Proxy: yes
- Browser: Chrome and Edge
```

### What branch are you running?

Main

### Trace Logs?

Here is the trace file
[sonarr.fsrl.pretoriusse.net_logfile_sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/12463933/sonarr.fsrl.pretoriusse.net_logfile_sonarr.trace.txt)

### Anything else?

Allow users to add their domains to sentrys cors or disable cors.

**Comment by markus101** [comment]
Closing as this is a server side issue that does not affect the operation of Sonarr outside of an error in the web console logs.

**Comment by rainepretorius** [comment]
> Closing as this is a server side issue that does not affect the operation of Sonarr outside of an error in the web console logs.

It makes it super slow to use the web ui. It takes 5 minutes to load the ui.

**Comment by markus101** [comment]
That request does not block the loading of the web UI. If the UI is taking that long to load, please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) to troubleshoot.

You can also disable `Send Anonymous Usage Data` in Settings: General to short circuit the initialization of sentry.

**Comment by rainepretorius** [comment]
> That request does not block the loading of the web UI. If the UI is taking that long to load, please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) to troubleshoot.
> 
> You can also disable `Send Anonymous Usage Data` in Settings: General to short circuit the initialization of sentry.

Thank you. I will give that a try.

**Comment by rainepretorius** [comment]
I am sorry to bug again. I have tried everything except a fresh install for the slow UI. It is the API call that fetches the series, that is slowing down the app. I do not have many TV
 shows as seen in the attached file.
[series.txt](https://github.com/Sonarr/Sonarr/files/12475048/series.txt)
