### ISSUE TITLE
Can't save form in Authentication Required modal if invalid settings are present in config

### ISSUE THREAD

**Issue by mynameisbogdan** [Sonarr/Sonarr#5979]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If you have invalid settings in your config.xml doesn't let you save in Authentication Required modal.

### Expected Behavior

To be able to save.

### Steps To Reproduce

1. Have these 3 settings in your config.xml:
```xml
<Config>
  <EnableSsl>True</EnableSsl>
  <SslCertPath></SslCertPath>
  <AuthenticationMethod>None</AuthenticationMethod>
</Config>
```
2. Open http://localhost:8989/
3. Click on save in Authentication Required Modal

### Environment

```markdown
- Sonarr: develop branch
```

### What branch are you running?

Develop

### Trace Logs?

```
2023-08-29 20:44:18.5|Trace|Http|Req: 110 [PUT] /api/v3/config/host (from 127.0.0.1 ...)
2023-08-29 20:44:18.5|Trace|SonarrErrorPipeline|Handling Exception
2023-08-29 20:44:18.5|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- SslCertPath: 'Ssl Cert Path' must not be empty.
2023-08-29 20:44:18.5|Trace|Http|Res: 110 [PUT] /api/v3/config/host: 400.BadRequest (7 ms)
2023-08-29 20:44:18.5|Debug|Api|[PUT] /api/v3/config/host: 400.BadRequest (7 ms)
```

```json
[
  {
    "propertyName": "SslCertPath",
    "errorMessage": "\u0027Ssl Cert Path\u0027 must not be empty.",
    "attemptedValue": "",
    "severity": "error",
    "errorCode": "NotEmptyValidator",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Ssl Cert Path",
      "propertyValue": ""
    }
  }
]
````

**Comment by markus101** [comment]
We have at least a few options here:

- Add the ability to force the save via another property/param in the request that ignores the errors
- Send only the values we care about and ensure validation doesn't apply (I think everything would need to become nullable) to null values
- Add another endpoint to handle auth specifically
