### ISSUE TITLE
Preferred size in size custom format

### ISSUE THREAD

**Issue by francoiseger** [Sonarr/Sonarr#5981]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

#5281 allowed the specification of a preferred size for qualities. This is currently the lowest priority criteria for ordering releases. If one however wants to order this as preferred to certain custom formats, this is not possible though, as the corresponding size custom format is purely binary.

### Describe the solution you'd like

Optimally it would somehow become possible to specify a preferred size in a custom format. 

### Describe alternatives you've considered

More control over the release comparison ordering might also help alleviate this, however to really make this work, the logic would require some further changes as it would have to be possible to mix the options listed [here](https://github.com/Sonarr/Sonarr/blob/610cc916891de771a53aa9eda4b674d089f88d1d/src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs#L31-L42) with the custom format conditions.

Another option is simply having several size buckets each with their own score in the list of custom formats. This is however cumbersome to implement for the user.

### Anything else?

This idea might be problematic in that all custom formats are currently binary conditions, this however would have to order things even within the custom format being matched. How exactly that would fit into the logic likely requires some further debate.

**Comment by markus101** [comment]
This was covered in https://github.com/Sonarr/Sonarr/issues/5496

More granular control of size is covered by https://github.com/Sonarr/Sonarr/issues/613
