### ISSUE TITLE
Invalid quality profiles can be added via API

### ISSUE THREAD

**Issue by francoiseger** [Sonarr/Sonarr#6005]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Using the API a custom profile can be added, which does not contain all qualities. This will result in [`GetIndex`](https://github.com/Sonarr/Sonarr/blob/447d8cfbb9a7a9b5e3f2f985e7300c1d2b251388/src/NzbDrone.Core/Profiles/Qualities/QualityProfile.cs#L57) returning the default index 0, which may be incorrect and thereby incorrectly register the quality profile as satisfied.

### Expected Behavior

The custom profile should be rejected. Likely there should be an additional validator.

### Steps To Reproduce

1. Create a quality profile in Sonarr with the devtools open
2. Get the json data sent in the request
3. Delete the quality profile again
4. Put that in a file called `test.json` and remove one of the items from the `items` array
5. Run
    ```
    curl -X POST -H "Content-Type: application/json" -d @test.json -H "X-Api-Key: XXXXXXX" "http://localhost:8989/api/v3/qualityprofile"
    ```
6. Take a look at the quality profile in the Sonarr web UI. The Item that you deleted will be missing.

### Environment

```markdown
Not relevant
```

### What branch are you running?

Develop

### Trace Logs?

Not much to see
```
2023-09-05 18:49:06.1|Trace|Http|Req: 5793 [POST] /api/v3/qualityprofile (from 10.0.2.100 curl/8.2.1)
2023-09-05 18:49:06.1|Trace|Http|Res: 5793 [POST] /api/v3/qualityprofile: 201.Created (12 ms)
2023-09-05 18:49:06.1|Debug|Api|[POST] /api/v3/qualityprofile: 201.Created (12 ms)
```

**Comment by markus101** [comment]
Please include all requested information (Environment details are relevant).

**Comment by francoiseger** [comment]
- OS: Flatcar Linux
- Sonarr: Latest develop
- Docker Install: Yes(Podman)
- Using Reverse Proxy: No
- Browser: Firefox
- Database: SQLite
