### ISSUE TITLE
Delay "go to series" notification

### ISSUE THREAD

**Issue by Thirrian** [Sonarr/Sonarr#602]
When you add a new show, a notification with a "Go To Series" button is displayed.
When you click it, you'll go to the series details page which doesn't have a poster or background yet (possibly other things are not yet updated, not sure).

*Then* the refresh series task runs & completes.

To be able to see the series you've just added in all its glory (artwork etc), you are forced to refresh the page, or go back to your series list and select the show again, or any other way to reload the details page.

Idea (if possible):
Display the notification with the "Go To Series" button *after* the refresh task has completed.
Or keep it around longer (at least until the refresh has happened)?

**Comment by markus101** [comment]
When the images are updated the fanart and poster will automatically update now, better than guessing when it might be done. When you first load the page you won't see images, but they will refresh once they are downloaded.
