### ISSUE TITLE
Add option to suprress failure for a Connection

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#6021]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Give me option on connection to tell sonarr to not care about failures.

I have sonarr setup to notify my kodi instance that runs on my nas to update library. This is important and I want to know if it fails.

I have sonarr setup to nofiy my kodi instances on one or more tv instances to let the user know if something grabbed/downloaded. Which is great if kodi is running at the time, but most of the time kodi is not running. So sonarr then generates system>status>health warnings when this is the case.

### Describe the solution you'd like

Add check box to dictate if sonarr should care if it should generate health warnings for the connection.

### Describe alternatives you've considered

Not use sonarr connection?

### Anything else?

I've also seen where if you have multiple connections for the same type (so 5x kodi connections) and one fails then it caused others to not fire off..  So I've had to re-name things to make sure my 'nas' instance goes first. So I'd hope this indirectly would fixup that scenario where you are okay with certain connections failing.

**Comment by markus101** [comment]
Currently no plans to suppress warnings for failing connections, but if multiple connections of the same type aren't being triggered properly that is something we'll want to look into with logs and further information.
