### ISSUE TITLE
Interactive searches throwing error

### ISSUE THREAD

**Issue by klepp0906** [Sonarr/Sonarr#6030]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When doing an interactive search for some episodes/seasons I'm met with the following error
![image](https://github.com/Sonarr/Sonarr/assets/10392920/77bb6ab3-e493-4caf-a345-f43e6e94f117)
In this case it was Game of Thrones Season 8.   I tried Season 7 and 6 and the result was the same.  

After doing some digging it was suggested to refresh the series and  remove-re-add.  Neither bore fruit.   I did find an issue report from a few years back saying it was addressed in a nightly build and nothing since. 

### Expected Behavior

Interactive searches should be presenting a list of results as opposed to "Search failed because its object reference not set to an instance of an object"

### Steps To Reproduce

1.  Run an interactive search for season 8 of game of thrones.  (have had it appear on other shows as well but wasnt keeping track of which until now)
2.  Receive an error as opposed to results. 

### Environment

```markdown
- OS: Windows 11
- Sonarr: 4.0.0.671
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Brave 
- Database: Sqlite 3.36.0
```

### What branch are you running?

Develop

### Trace Logs?

https://privatebin.net/?27c50d87a75cb1f9#AxbHZYbRTCNYnNgMtHKBLa8C5LcJkamtuCXzDAjbCYpy

### Anything else?

If you guys need more logs or anything just lmk.

**Comment by markus101** [comment]
Assuming you're using multiple indexers, could you try to narrow down to a specific indexer and provide the full logs of the search? In a particular I'm looking to see whether there is another error earlier that leads to this because I'm unable to reproduce and don't see an obvious way that this could be occurring.

**Comment by klepp0906** [comment]
definitely using multiple indexers :P never considered attempting indexer by indexer either.  I'll go ahead and disable them 1 by 1 and see what happens. 

will report back asap.

**Comment by klepp0906** [comment]
here are the results https://privatebin.net/?121cb50c8b26a101#HAQx2kxNYHHstE3H3prVirsfcXteToHyViBKAEwrYizu

turns out its this guy causing the mayhem.

![image](https://github.com/Sonarr/Sonarr/assets/10392920/1b566e3f-070a-4c29-bc1d-67a0b0b24e7e)

**Comment by markus101** [comment]
Yeah for sure, I'm just surprised it got this far, I'd expect it to have been thrown out way earlier.
