### ISSUE TITLE
PWA manifest.json missing content

### ISSUE THREAD

**Issue by effree** [Sonarr/Sonarr#6031]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When trying to install as a PWA app, it does not work.
The manifest.json is showing that the name and URL are missing.  Although i am up to date, and in the GitHub repo it appears to have a name and URL.

### Expected Behavior

Should have a name and URL which would allow it to be installed as PWA

### Environment

```markdown
- OS: Docker Container
- Sonarr: 3.0.10.1567-ls206 by linuxserver.io
- Docker Install: 
- Using Reverse Proxy: NGinx Proxy Manager
- Browser: Brave/Chrome/Edge
- Database:
```

### What branch are you running?

Main

### Trace Logs?

none

**Comment by markus101** [comment]
This is already fixed in the v4 beta, which is what `develop` is.
