### ISSUE TITLE
Sonarr displays GB/TB units for values in GiB/TiB

### ISSUE THREAD

**Issue by trentks** [Sonarr/Sonarr#6034]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Everywhere that I've done comparisons, sonarr displays units of gigabytes/terabytes (10⁹ B = 1 GB, 10¹² B = 1 TB) when the values associated with those units are actually in gibibytes/tibibytes (2³⁰ B = 1 GiB, 2⁴⁰ B = 1 TiB).

### Expected Behavior

The values should have the correct units.

### Steps To Reproduce

Compare number of bytes of a file with number of gigabytes or terabytes that sonarr associates with that file in any view. It will be incorrect. The, unit should be GiB/TiB.

### Environment

```markdown
- OS: Any
- Sonarr: 3.0.10.1567 
- Docker Install: N.A.
- Using Reverse Proxy: N.A. 
- Browser: Firefox
```

### What branch are you running?

Main

### Trace Logs?

Irrelevant

**Comment by stevietv** [comment]
This is changed in v4 to GiB

**Comment by raidenlal** [comment]
I have just noticed sonarr using units noone actually uses except "but aktshually it is not megabyte because mega is 1000000" people.
