### ISSUE TITLE
Not Downloading episode

### ISSUE THREAD

**Issue by Kiseichu** [Sonarr/Sonarr#6037]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I use the docker version sonarr v4 and my version of sonnar does not download new episode automaticly and i don't know why.

### Expected Behavior

I am not sure if i am the problem or the application

### Environment

```markdown
- OS: Alpine Linux
- Sonarr: 4.0.0.657
- Docker Install: sonarr developp
- Using Reverse Proxy: No
- Browser: Brave
- Database:
```

### What branch are you running?

Main

### Trace Logs?

[trace.txt](https://github.com/Sonarr/Sonarr/files/12658491/trace.txt)

**Comment by stevietv** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
