### ISSUE TITLE
Local NZB import

### ISSUE THREAD

**Issue by ScarAce1989** [Sonarr/Sonarr#6038]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I ripped and uploaded my own Blu-rays to usenet and now have a folder of NZB files. I want to add this local NZB folder as a indexer.

### Describe the solution you'd like

I want to import my NZB folder and get them listed under 'Search' like any other indexer.

### Describe alternatives you've considered

Could not find any other solution.

**Comment by TRaSH-** [comment]
We explained twice in Radarr discord how you can accomplish this
The same counts for Sonarr.
You will need to setup a own usenet indexer that you add later to prowlarr or Radarr and Sonarr.

**Comment by markus101** [comment]
We do not have plans to support an indexer based on NZB/torrent files within a folder on disk.
