### ISSUE TITLE
Support for Plex Universal Watchlist (Plex RSS Watchlist)

### ISSUE THREAD

**Issue by joshthor3222** [Sonarr/Sonarr#6041]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Plex has a universal watchlist feature, but Sonarr only integrates with the users specific watchlist. Radarr allows for both, so my friends watchlists can show up in my Radarr, it would be very useful if Sonarr could do the same thing. 

### Describe the solution you'd like

The easiest solution in my mind is to take the RSS url plex provides and input it. The only current option for plex watchlists is authenticating. Radarr has a solution in place to do exactly this already, and if they work similarly behind the scenes it might be easy to do the same thing.

### Describe alternatives you've considered

Alternatively updating the authentication step to grab both rss feeds at once.

**Comment by markus101** [comment]
This is already in the v4 beta.

https://github.com/Sonarr/Sonarr/commit/6d88a98282d1441f903d567470a9f1ce6ba0b52f
