### ISSUE TITLE
Allow episode title character limit

### ISSUE THREAD

**Issue by ShanaryS** [Sonarr/Sonarr#6046]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have seen #5222 but it has a large oversight, it doesn't consider subtitles. I have a file that is 253 characters long, the linux limit is 255 characters. This means I cannot replace .mkv with .en.srt as it would now be 256 characters long.

### Describe the solution you'd like

Please allow the option to limit episode title. For example, to limit it to 100:

{Episode CleanTitle:100}

### Describe alternatives you've considered

Reduce the overall limit to something like 240.

### Anything else?

https://thetvdb.com/series/zombie-land-saga/episodes/6827086

That episode title alone is 199 characters long.

**Comment by Qstick** [comment]
This is already something that happens automatic when needed. If there are instances that are not handled incorrectly, we should handle those in the long path logic.

**Comment by ShanaryS** [comment]
@Qstick I think you misread my post.

**Comment by Qstick** [comment]
I did not infact, my suggestion is we handle the situation better.

**Comment by ShanaryS** [comment]
I don't see what handling there is to be done? Sonarr is not the one dealing these subtitles.

The only solution is to set a hard limit on the number of characters so when whatever external script wants to use the filename it doesn't crash the program.

This is no just subtitles. The long filename breaks a few of my scripts.

**Comment by stevietv** [comment]
Whilst I agree with QStick that this could be handled better if Sonarr is the one creating or renaming the Extra Files associated with the episode, I do think that a fixed limit could be a nice addition for those that want to arbitrarily limit the length of titles in the filename.

If we are to handle it the first way, then we should check what happens if the filename is at is limit, would `LongFileShowName.mkv` be truncated to `LongFileShowNa.en.srt` if the same logic is applied to the extra file, which may cause external players to not pick up the srt file (as the filenames don't match).

**Comment by markus101** [comment]
Sonarr can already enforce limits based on environment variables, both `MAX_PATH` and `MAX_NAME` are supported.

You'll want to set the `MAX_NAME` environment variable to your expected maximum length and Sonarr will ensure file names are below that, which will apply whether long path support is enabled on Windows or not, if it's not enabled you may also want to set `MAX_PATH`.

I'm not sure there is a lot of additional value doing this with renaming tokens.

**Comment by ShanaryS** [comment]
@markus101 Thanks! This is exactly what I was looking for. I'm considering this issue solved but it seems there is more discussion to be had.

**Comment by markus101** [comment]
Closing it out as it's not something we're going to invest time into at this time.
