### ISSUE TITLE
Trace Logs do not filter out private tracker info

### ISSUE THREAD

**Issue by Rubicj** [Sonarr/Sonarr#6047]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues

### Current Behavior

Reopen of https://github.com/Sonarr/Sonarr/issues/4341

The return from QBittorrent includes secrets about trackers. These secrets seem to not be redacted properly. I've attached a manually redacted file where I've replaced my keys and the website names.

### Expected Behavior

```
"tracker":"https://t.foo.com/tracker.php/p6jqYMVbKn7FNoAz7NLdU6JRv548M30V/announce",
"magnet_uri":"magnet:?xt=urn:btih:4da7319561bf054dfd6135c284587b844ec16efc&dn=Nikki%20St.%20Crowe%20-%20Midnight%20Harbor%2003%20-%20Hot%20Vampire%20Next%20Door%20Season%20Three.epub&tr=https%3a%2f%2ft.foo.com%2ftracker.php%2fp6jqYMVbKn7FNoAz7NLdU6JRv548M30V%2fannounce"
```
should be replace with
```
"tracker":"[REMOVED]",
"magnet_uri":"[REMOVED]"
```

### Steps To Reproduce

1. Add QBittorrent as a download client
2. Turn on Trace logging
3. Observe that the full logs are printed without redaction

### Environment

```markdown
- OS: Unraid
- Sonarr: 4.0.0.682 and Readarr 0.3.5.2217
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Default
```

### What branch are you running?

Develop

### Trace Logs?

[fakelogs.txt](https://github.com/Sonarr/Sonarr/files/12719917/fakelogs.txt)
Note that I replaced the actual 32 digit passkey with one I made up, `p6jqYMVbKn7FNoAz7NLdU6JRv548M30V`

### Anything else?

The regex used is visible in https://github.com/Sonarr/Sonarr/commit/e67864fecb4a66792152ff8fb0889ee1a176919f , but it doesn't look like normal regex to me -- the bars and forward slashes are confusing me.

I do see that it's only matching lowercase letters, and my secret contains uppercase.  That might be it? In my opinion, it's actually preferrable to mask out the whole website name -- I'd actually expect it to redact the entirety of the magnet uri and the tracker.

**Comment by Rubicj** [comment]
I just looked though some other trackers, and I see private keys with other symbols -- dashes, periods, dollar signs, forward slashes. I don't think we can reasonably make any assumptions about the format the secret will be in.

**Comment by markus101** [comment]
If you have examples of passkeys that have the same format, but aren't actually the yours they would be useful for ensuring those case are covered as well.

**Comment by Rubicj** [comment]
https://foo.bar.fee/a/uf85w3azbatzjbrc0umb5bypmeztjsl2/announce
http://foo.bar.fee:12345/856KKd-V29o6IIoTdot1$95e9M3s$5Fb/announce
https://foo.bar/announce.php/passkey=wE2iyacdRu7B$ZUipJ42KYZ5VSX5wTE6
https://foo.bar/announce/DqXODn%2EACp7fFTgjVBeU546zYtM3KfrxOUipJ42

**Comment by Rubicj** [comment]
Sorry to necro this, but an important part of the inital bug is that passkeys can contain non-alphanumeric symbols. I have a passkey AAAAA-AAAAAAAAAAAAA$AAAAAAA$AA that doesn't get filtered at all in trace logs, and shows up as the unfiltered secret key. I'm sure if I scraped trace logs from here and Discord, I'd end up with a respectable collection.
