### ISSUE TITLE
Moving sonarr conig files to a Dropbox folder

### ISSUE THREAD

**Issue by leej0nes** [Sonarr/Sonarr#605]
Hi,

Is this currently possible.  Saves me the cost of a UPS right now.

**Comment by baz1860** [comment]
You could always 'soft-link' the config file into your Dropbox folder?

**Comment by Taloth** [comment]
config file hardly changes. if you're taking about db-file then why not rely on the backups mechanism? (You probably shouldn't sync those db files using dropbox anyway, db vs db-wal consistency and all)

If it's on osx, try latest master where we enabled fullfsync on the db file. (You can thank osx for not obeying fsync).
