### ISSUE TITLE
Windows installer should default to "as service" for consistency with Radarr, Lidarr, Prowlarr

### ISSUE THREAD

**Issue by kriswilk** [Sonarr/Sonarr#6053]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Almost every *arr application defaults to installing as a service in Windows.

Strangely, and inconsistently, Sonarr (and Readarr) defaults to installing via a startup group item.

BACKGROUND: I discovered this inconsistency after using "winget" to install all of the *arrs. Sonarr and Readarr both created tray icons, which I was not expecting. I had to re-run the installers to fix this.

### Describe the solution you'd like

Set the default install behaviour for Sonarr (and Readarr) to "as a service".

### Describe alternatives you've considered

No alternative. Please make this consistent across apps.

**Comment by markus101** [comment]
This was an intentional change with v3 as many people ran into issues with permissions when running as a Windows service. We do not have plans to change the default back to running as a Windows service.

**Comment by kriswilk** [comment]
> This was an intentional change with v3 as many people ran into issues with permissions when running as a Windows service. We do not have plans to change the default back to running as a Windows service.

I thought it was Sonarr and Readarr but it turns out Readarr was updated in August to default to "as service" as well.

That means Sonarr is the ONLY app from the entire family NOT to install as a service. All the others do: Radarr, Lidarr, Readarr, Prowlarr, and Whisparr. This doesn't seem logical at all.

If, in fact, there was a usability issue with installation as a service, shouldn't ALL of the apps default to running via the Startup group? For the record, I'd be fine with that, too.

@markus101 or anyone else with authority, please clarify the reasoning for this conspicuous inconsistency.

**Comment by markus101** [comment]
I can't speak for @Qstick or other members of the team as to why the other apps weren't changed and why Readarr was changed back. In Sonarr this change was made 3 years ago: https://github.com/Sonarr/Sonarr/commit/43cb44dd3823b712da66e2ed01a41f8097afb59d and Radarr cherry picked the change here: https://github.com/Radarr/Radarr/commit/02c95658c4a5d38e1d0997ed5ef9bbd219ffc32c but without the change to the start up.

**Comment by Taloth** [comment]
Here's "anyone else with authority". Installing Sonarr as a service requires special care to be taken with regards to network share permissions and home directory permissions. 
Often, users would install QbitTorrent (which is often ran as System Tray task) and default download in to their HOME directory. A directory to which a service would not have permission to access by default. They'd run into issues where Sonarr was unable to access the downloaded media, and have difficulty configuring their system appropriately. This leads to numerous support requests and user frustration.

Therefore, it's a 'safe default' to have Sonarr install as System Tray task, which given the above is very conscious decision and in my opinion remains the correct one and as such I agree with Markus that no changes should be made in this respect.

**Comment by kriswilk** [comment]
@Taloth and @markus101, I understand it was a conscious decision, and don't disagree with it (as far as support goes...). My question is: if this was decided consciously for Sonarr, WHY was the (presumably) conscious decision made to do the OPPOSITE for every other *arr application?

As I said in my last message, I'd be perfectly fine if ALL of the apps defaulted to running from Startup group on Windows. That would at least be CONSISTENT and have sensible reasoning.

The way it stands right now, Either Sonarr should get in line with all the others, or all the others should be changed to match Sonarr.

Don't users of Radarr and Lidarr complain about exactly the same things that Sonarr users would??

I hope you understand my point this time.

**Comment by Taloth** [comment]
Neither Markus nor I maintain the other apps. So you're asking the wrong people.

**Comment by kriswilk** [comment]
Thanks for the clarification. Based on the consistency of everything else in the apps, I assumed that there is a high level of communication/synergy between devs.

I'll redirect my inquiry to the other teams.
