### ISSUE TITLE
Series TitleFirstCharacter Special Characters

### ISSUE THREAD

**Issue by ZTiKnl** [Sonarr/Sonarr#6055]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hi there, new Sonarr user here, please take this into consideration if I overlooked something obvious ;)

I have ran into a slight issue adding series which start with a special character ([example](https://thetvdb.com/series/the-80s-greatest-us))

Sonarr is configured to use the following folder format:
`{Series TitleFirstCharacter}/{Series CleanTitleYear}`

On manually importing the related files, Sonarr will try to create the _{Series TitleFirstCharacter}_ folder, and fails here because, well, it is a special character, and (I assume) internal code catches it...

### Describe the solution you'd like

Feature request:
Add another label: **{Series CleanTitleFirstCharacter}**
This label should use the first character from the {Series CleanTitle} label, effectively disallowing special character folders

### Describe alternatives you've considered

I don't really see any alternative solutions, but I'm very open to suggestions!

### Anything else?

I searched the Issue tracker for similar requests, but did not see any with the terms I used.
The only comment related I found was [this one](https://github.com/Sonarr/Sonarr/issues/5410#issuecomment-1416878727), but I don't think it is relevant really?

Thank you for your time and this wonderful collection of software!

**Comment by ZTiKnl** [comment]
I was able to resolve this issue for this particular show, by manually creating the folder with the special character myself.
Then Sonarr was able to create the {Series CleanTitleYear} folder inside it and import the corresponding files.

I would call this a temporary workaround, and not really a fix, as I fear this will fail again when I run into a show starting with a different special character.

Also, Sonarr fails silently on importing this example, there are no messages (bottom left corner, just disappears within <1 sec), nor does this import appear in the Activity/History tab.
Not complaining, just FYI ;)

Logfile, the corresponding part is at the end:
[logfile_sonarr.txt](https://github.com/Sonarr/Sonarr/files/12773867/logfile_sonarr.txt)

**Comment by markus101** [comment]
This is probably the most relevant discussion, https://github.com/Sonarr/Sonarr/pull/5909 I don't think we'd want to have yet another renaming token for this, but instead should improve the existing behaviour.

> Logfile, the corresponding part is at the end:
[logfile_sonarr.txt](https://github.com/Sonarr/Sonarr/files/12773867/logfile_sonarr.txt)

This isn't a log file... looks like you saved the html to a text file?

**Comment by ZTiKnl** [comment]
Not sure what happened there, here is there actual log file :)
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/12773920/sonarr.txt)

Thanks for the Radarr issue link, didnt cross my mind to check there as well!
I would find a # character acceptable as a 'catch-all' for special chars, but in all honesty, I think my own solution is cleanest of all.
Regardless, I have no say in the matter, just a personal opinion ;)

Do you have any indication when this Radarr fix will be integrated into Sonarr?
