### ISSUE TITLE
Add option to disable upgrading within release profile

### ISSUE THREAD

**Issue by Zalhera** [Sonarr/Sonarr#6060]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

At the moment it is only possible to disable upgrades in the quality profile. E.g upgrading from WEB 1080p to Bluray-1080p.
I would like to also disable upgrading of episodes within a release profile.

Example:

Given I have a release profile with some preferred terms and custom scores.
A new episode from a show is released first on Netflix. Sonarr will grab this episode, because there is nothing else.
Now some time later the same episode is uploaded on an indexer from Amazon. Because of the preferred terms the episode from Amazon has a higher score and Sonarr will grab this episode.

### Describe the solution you'd like

I would like to have an option to disable Sonarr from downloading an episode with a higher score from within a release profile. As soon as I have downloaded an episode all "better" episodes should be ignored.

### Describe alternatives you've considered

A possible alternative to a checkbox to disable this behaviour would be to add another option to unmonitor episodes after they have been downloaded.

**Comment by augustuen** [comment]
Already sorted in V4 with the switch to custom formats.
