### ISSUE TITLE
Bulk import from queue

### ISSUE THREAD

**Issue by wogam** [Sonarr/Sonarr#6061]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hi, would it be possible to add a feature to bulk import from the queue? For an example, in the screenshot below, automatic import hasn't been possible. I've manually checked the files but to import them, I'd have to do it one by one which is very time-consuming. I can't use wanted ⇾ manual import since the file names are encrypted, so it doesn't match up.

Next to the 'grab selected' on the top, there should be 'import selected' which would import all the selected files.

![Screenshot 2023-10-02 121552](https://github.com/Sonarr/Sonarr/assets/48340127/89210370-c60c-40bc-9021-723c95f681f3)

### Describe the solution you'd like

Next to the 'grab selected' on the top, there should be 'import selected' which would import all the selected files.

### Describe alternatives you've considered

 I can't use wanted ⇾ manual import since the file names are encrypted, so it doesn't match up.

**Comment by augustuen** [comment]
If they're part of the same download the files should all show up when you go to do a manual/interactive import (person icon on the right)

**Comment by wogam** [comment]
> If they're part of the same download the files should all show up when you go to do a manual/interactive import (person icon on the right)

They're all separate downloads/separate folders, so it isn't possible, unfortunately.

**Comment by markus101** [comment]
We do not have plans to support bulk import for individual downloads.

For naming discrepancies such as this we do maintain a list of aliases and add things when it makes sense. The FAQ has information on how to request them.
