### ISSUE TITLE
New Folder Name token, cleaned with 'the' prepended

### ISSUE THREAD

**Issue by ZTiKnl** [Sonarr/Sonarr#6066]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I am missing a token allowing for both cleaned names, as well as prepending words like 'The' to the end of the name.

example show: **The '80s Greatest (2018)**
desired outcome: **80s Greatest, The (2018)**
(take notice of the apostrophe)

There is no option to have both clean and prepended 'The'.
There are clean tokens for:

- _{Series CleanTitle}_: **The 80s Greatest (2018)**
- _{Series CleanTitleYear}_: **The 80s Greatest (2018)**
- _{Series CleanTitleWithoutYear}_: **The 80s Greatest**

but none that result in reordering syncategorematic words like 'The'.

There are tokens that reorder these words, but none of them clean the name as well.

### Describe the solution you'd like

I am proposing a new token:
_{Series CleanTitleTheWithoutYear}_

This would just be one new token, where people can still manually add {Series Year} to get the desired outcome.

The alternative proposal would be to make a clean variant of each non-clean variant token :(

### Describe alternatives you've considered

current options: 

- _{Series TitleTheYear}_: **'80s Greatest, The (2018)**
- _{Series CleanTitleYear}_: **The 80s Greatest (2018)**

I don't think there are any alternatives?

### Anything else?

I opened another feature request for something _somewhat_ related, and there it was said that:

> I don't think we'd want to have yet another renaming token for this, but instead should improve the existing behaviour

Please don't think of this ticket as me not listening.
After conversing on Discord on how to approach this, I was told that 'this wasn't a bad idea for a feature request', and although it might be a waste of time, it might not...
Thank you for understanding ;)

**Comment by stevietv** [comment]
I would support this, but actually more support the addition of corresponding Clean tokens for all Title options,. There are three tokens that don't have a corresponding Clean version:

* `{Series TitleThe}`
* `{Series TitleTheYear}`
* `{Series TitleWithoutYear}`
* `{Series TitleTheWithoutYear}`

This would mean the addition of 4 extra tokens however, so we'd need the input of Markus if he's on board. If so I can throw it together.

**Comment by ZTiKnl** [comment]
In that case, I would like to mention _{Series TitleFirstCharacter}_ one last time for a potential fifth

In the example used above _{Series TitleFirstCharacter}_ results in a folder named _apostrophe-character_
A clean version would result in a folder named '8'

This was of course my intent with my other feature request, which will be fixed (in a slightly roundabout way) sometime soon.
The fix will allow for all special chars and numbers to be listed under {Series TitleFirstCharacter} '#'

**Comment by stevietv** [comment]
take a look at PR #6059
We're now looking at taking the first or second alphanumeric character for `TitleFirstCharacter`, and defaulting to`_` when neither of these are alphanumeric. This helps with shows that begin with an apostrophe. That means that `The '80s Greatest` would map to `8`. I would stress though that I struggled to find many more examples where this PR proves to be useful.

**Comment by ZTiKnl** [comment]
Excellent, that seems like the best of both worlds!

I'm withdrawing my mention of _{Series TitleFirstCharacter}_ ;)

**Comment by ZTiKnl** [comment]
Maybe worth mentioning that the show ''[Allo 'Allo! (1984)](https://thetvdb.com/series/allo-allo)' also starts with an apostrophe, so the impact of this could be a bit bigger than expected?

Wouldn't call this an 'obscure' show by any means ;)

**Comment by markus101** [comment]
Yeah, it seems reasonable to include clean tokens for those ones as well.
