### ISSUE TITLE
Previous Airing in Series Overview shows incorrect date

### ISSUE THREAD

**Issue by ZTiKnl** [Sonarr/Sonarr#6068]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

In the Series overview list, when selecting option 'Previous Airing', the airdate shown is incorrect in certain cases:

- I have added the show Gruen
- I set the series to monitor only for new episodes
- I added some old episodes, with the latest episode of year 2018
- I updated the show

Now in the Series overview list, the Previous Airing for Gruen is listed as 2018, while this show has had many episodes since.
It appears that the Previous Airing in the Series Overview is calculated from the last _**'available'**_ episode, or the last _**monitored**_ episode.

### Expected Behavior

Previous Airing should always be the last previous episode, regardless of wether that particular episode is available or even monitored.

### Steps To Reproduce

Take any show you have, where you are missing a few recent episodes

Unmonitor the latest season with all its files

Refresh the series data

Check the Series Overview Previous Airing, it'll be the date for the last available episode in storage OR it will be the last monitored episode (regardless if the file is in storage or not).

### Environment

```markdown
I'm running both a docker and the synocommunity (not at the same time ofcourse), the issue is present in both.
Below is synocommunity package info, skipping docker details until asked to avoid cluttering:

Version: 4.0.0.688
Package Version: x64-7.1_20230426-2 by SynoCommunity
.NET: Yes (6.0.13)
Database: Sqlite 3.40.0
AppData directory: /volume5/@appdata/sonarr/.config/Sonarr
Startup directory: 
/volume5/@appstore/sonarr/share/Sonarr/bin
Mode: Console
```

### What branch are you running?

Develop

### Trace Logs?

I'm not sure trace logs will show anything, but I'm willing to remove then add/import this show again?
Do let me know if this is desired, but I'm awaiting further notice as it seems ... irrelevant?

### Anything else?

Screenshots, lots of screenshots (I added the red circles to guide where the issue can be seen.):

Turned on Previous Airing in the overview:
![options selected](https://github.com/Sonarr/Sonarr/assets/53024556/ee67ff33-228f-4ec8-9878-1e00ca534f6e)

Gruen lists previous airing as 04/07/2018
![gruen](https://github.com/Sonarr/Sonarr/assets/53024556/95141b57-f372-4dc9-b01c-df66fb383cb2)

This date coincides with the last _available_ episode in storage, but not the actual last airing:
![gruen details](https://github.com/Sonarr/Sonarr/assets/53024556/a4d54f4c-27fd-4a6f-a61e-49c2a3e0e7b2)

If I now monitor some episode after 2018 but before the most recent airing:
![monitor episode](https://github.com/Sonarr/Sonarr/assets/53024556/bedf8606-08b1-4d9f-a73e-391e3a320e13)

I get Previous Airing date of the last _monitored_ episode, but not the actual last airing:
![date updated](https://github.com/Sonarr/Sonarr/assets/53024556/30cc103f-bf41-4c02-ae53-bdac5614fdf1)

I think this is related to issue : https://github.com/Sonarr/Sonarr/issues/6067
But I think they're the _same cause_, but _different symptoms_?

**Comment by markus101** [comment]
This will be changed to only show monitored episodes, instead of monitored episodes or episodes with files as it's doing currently.

No plans to have it include all episodes same as the calendar won't show items that aren't monitored by default.
