### ISSUE TITLE
Daily NPE

### ISSUE THREAD

**Issue by andrewmr** [Sonarr/Sonarr#607]
Description:

    EPIC FAIL: Object reference not set to an instance of an object: Object reference not set to an instance of an object

Exception:

    System.NullReferenceException: Object reference not set to an instance of an object
      at System.Threading.Timer+Scheduler.SchedulerThread () [0x00000] in <filename unknown>:0 
      at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0 

Happens almost every day, no predictable errors logged before the exception is thrown. In this case, the preceeding error is:

    [/path/to/file.mkv] has a runtime of 0, is it a valid video file?

**Comment by markus101** [comment]
We use our forums for support and this issue is stickied there: https://forums.sonarr.tv/t/native-mono-crashes/4985/133

**Comment by andrewmr** [comment]
Aha, thanks.
