### ISSUE TITLE
Permanent warning of SAB setting that I want enabled

### ISSUE THREAD

**Issue by jackfalveyiv** [Sonarr/Sonarr#6071]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Upgraded to v4, works phenomenally well for me.  I use Sonarr/Radarr/Lidarr daily.  I use LunaSea on my mobile device and it allows me to quickly review my SAB download history every morning to know what's hitting my server in one concise place.  I have SAB clean up downloads older than 1 day, and this works well for me.  On Sonarr v4, I get a permanent "error" message alerting me that "Download client SABnzbd is set to remove completed downloads.  This can result in downloads being removed from your client before Sonarr can import them."  I've been using this software in this way for 5 years and this workflow is best for me.  I want to suppress this "error" message, as it's not an error message for me.  I asked on the Discord channel but was unable to find someone sympathetic to my request, only suggesting that I "send notifications somewhere".  I do that already on a Discord server, but again, the SAB download history queue on LunaSea on my mobile device is a much better, more efficient way for me to keep an eye on things.  If I have to, I will just leave this setup the way it is and deal with always having an error message on Sonarr, but I'd prefer to suppress it altogether as it's not an error for my setup.  
<img width="1179" alt="Screen Shot 2023-10-05 at 8 10 49 AM" src="https://github.com/Sonarr/Sonarr/assets/15113284/c84ce498-d784-463a-94c9-eb5be9dc2609">

### Expected Behavior

I'd just like the "error" message to go away as it is not actionable for me.

### Environment

```markdown
- OS: Unraid
- Sonarr: 4.0.0.688
- Docker Install: lscr.io
- Using Reverse Proxy: Yes
- Browser: Chrome 117.0.5938.92
- Database: Sqlite 3.41.2
```

### What branch are you running?

Develop

### Trace Logs?

https://gist.github.com/jackfalveyiv/d9492a8e7a9c3991e6f4c96e68406a5d

### Anything else?

If there is a better way to achieve what I want here I'm open to that, but I find the Discord notifications to force me to do a lot more scrolling to get all the information I want.  I'd just like to keep things the way they are as that's what works well for my setup.

**Comment by stevietv** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions. 

You can remove the health check by setting clean up to 14 days, or enabling removed completed downloads in sonarr and letting sonarr manage it by cleaning up what it imports.
We have introduced this healthcheck to ensure that downloads can be imported into sonarr before they are removed from the sab history.
Dismissable health checks are something that would be on the to-do list for a long time away.
