### ISSUE TITLE
Import loop when at least one episode from a season pack is rejected 

### ISSUE THREAD

**Issue by mynameisbogdan** [Sonarr/Sonarr#6075]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Start with a mix of 1080p and 2160p episodes:
![1](https://github.com/Sonarr/Sonarr/assets/707714/3dff93c6-f8c6-41d7-ad49-c2736bbfd56c)

Then have a manually grabbed season pack:
![2](https://github.com/Sonarr/Sonarr/assets/707714/f52740a6-643e-46d4-8b77-b7f3290e0ba9)

When at least one episode of the season pack is reject it goes into a import loop every few seconds.

### Expected Behavior

To prevent the import loop, even reject the whole season pack to need manual intervention.

### Steps To Reproduce

1. Start with a mix of 1080p and 2160p episodes
2. Manually grab a 2160p season pack non-HDR while you use the SDR custom format so it has a negative CF scoring.
3. The queue should get start an import loop. 

### Environment

```markdown
- OS: Unraid
- Sonarr: 4.0.0.688
- Docker Install: Y
- Using Reverse Proxy: N
- Database: Sqlite
```

### What branch are you running?

Develop

### Trace Logs?

https://privatebin.net/?9584c724785aaf4e#7TfpgMUoesZEk49YNWnH3JkchcoGK5V8eQUjvE2ujF6Q

**Comment by markus101** [comment]
Can you show the history for an episode that is being imported multiple times as well?

**Comment by markus101** [comment]
Looks similar to https://github.com/Sonarr/Sonarr/issues/5625 which was due to two different downloads with the same content fighting back and forth.

**Comment by markus101** [comment]
Ahh, that would do it. Rejecting if that download ID is already imported regardless of the last grab would make sense then.
