### ISSUE TITLE
Add languages from Settings > UI

### ISSUE THREAD

**Issue by DavidHenryThoreau** [Sonarr/Sonarr#6077]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

At the moment it's not possible to change language from UI

### Describe the solution you'd like

Can you add the possibility to change languages ?

### Describe alternatives you've considered

Other arr have this feature

**Comment by stevietv** [comment]
This is possible in V4 of Sonarr - You will need to either upgrade to the beta or wait for its release.
