### ISSUE TITLE
Option to set last modified date when importing files

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#608]
Similar to setting it to UTC/local we could set the import time when importing episodes. Would we also want to set it when rescanning (like the air date options).

**Comment by Taloth** [comment]
I'm a bit torn on this, coz what is the problem that we would be solving with this?
- Kodi/Plex not showing it as recently imported? isn't that their problem.
- 0sec setting wrong mtime? nuke em or deal with it with a sab/nzbget pp-script.

Ppl might be confusing ctime vs mtime btw.
On rescan/organize it would be rather messy when ppl reinit the sonarr db. Might wanna copy ctime to mtime.

**Comment by thezoggy** [comment]
yeah, and not all os handle it the same.. personally the only time ive wanted to change the time is on those 0SEC releases where they had no time set.. but those are one off.. and probably easy enough to script to catch when the Custom Commands gets added

**Comment by markus101** [comment]
Not really interested in expanding this, we've tossed around the idea of dropping the existing date setting and letting people do that through custom scripts, but haven't pulled the trigger on that, but I'd rather not add more.
