### ISSUE TITLE
Missing section in Wanted tabs show unmonitored episodes

### ISSUE THREAD

**Issue by Phil57** [Sonarr/Sonarr#6084]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When using the Monitored filter of the Missing section in the Wanted tab, all episodes of a series are shown, even thoose not monitored.

### Expected Behavior

Show only monitored episodes.

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 4.0.0.694
- Docker Install: 
- Using Reverse Proxy: Traefik 
- Browser: Chrome
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

/

**Comment by stevietv** [comment]
thanks for the report, this appears to be a regression in `4.0.0.694`
My guess would be that it comes from here (https://github.com/Sonarr/Sonarr/commit/bfaa7291e14a8d3847ef2154a52c363944560803), but Markus can confirm.
