### ISSUE TITLE
Allow scrolling when long titles push series details out of view

### ISSUE THREAD

**Issue by Extremity** [Sonarr/Sonarr#6087]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sorry if this has already been posted, I've spent some time searching and can't find anything related to it.

When viewing the details for an added series, if the series title is long enough (relative to the size and dimensions of the screen), it will push all other content outside of the frame on a mobile device. This means you can't see any information other than the title itself.

Here is an example screenshot from the cover screen on a Galaxy Fold 3: https://images4.imagebam.com/24/09/df/MEPF477_o.png

### Describe the solution you'd like

Solutions for this already exist in regards to frontend markup. You could have the container automatically allow scrolling only when the child content exceeds the capacity of the container, or you could have a maximum vertical size for titles that either truncates or itself allows scrolling (if you want to be really fancy, you could have the title self-scrolling; ie, it's cut off but the title scrolls by on repeat. Think of, like, a cable box guide screen when a title is too long.)

Easiest solution is to simply allow scrolling specifically within the upper portion of the series overview page when applicable. There are other options; you could make it so tapping the title forces it to a single line, tapping again reverts. There are a multitude of options, scrolling is just the most obvious. I'm happy to whip up some examples if it helps. 

### Describe alternatives you've considered

I don't think this really applies. 

### Anything else?

Again, sorry if this is a known issue or has already been posted. I felt like it was better off here rather than in the bug report section since, according to the source on mobile, it's acting as intended.

**Comment by thezoggy** [comment]
as sonarr does a bit with media queries breakpoints to try and make a decent mobile experience but there will always be compromises.  you might want to look at just using nzb360 / lunasea for a much better experience

**Comment by Extremity** [comment]
I do use NZB360, but sometimes you just need to use Sonarr itself. I get that there will always be UX issues across the myriad of existing devices, but this isn't something that requires a ton of thought or work to fix - and that fix would effectively fix the issue across all of said devices.

I'm not trying to act like this is a huge deal, but it's easily resolved. I don't think "use different software" should ever be the rationale behind not improving a piece of software.

**Comment by stevietv** [comment]
The PR #6089 should address this without introducing scrolling text. instead the font size is reduced on mobiles.

This:
![image](https://github.com/Sonarr/Sonarr/assets/1117625/722855f7-7b64-4dfd-b9b1-80ed139cb4c6)![image](https://github.com/Sonarr/Sonarr/assets/1117625/71e3abb9-be58-41de-b1aa-df161571060a)
