### ISSUE TITLE
Renaming manually imported Episodes should rename Subtitles and Metadata

### ISSUE THREAD

**Issue by emhl** [Sonarr/Sonarr#6092]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I get some series that were published on public tv via [mtv_dl](https://github.com/fnep/mtv_dl), which also Downloads some Metadata and Subtitles. When I import the files into sonar, to get them into the correct naming scheme for jellyfin, the .srt and .nfo files don't get renamed and copied.

### Describe the solution you'd like

rename files, that have an identical filename to the video (apart from the extension) as well

### Describe alternatives you've considered

using filebot to rename them instead would be an option. but i'd like to do it in sonarr

### Anything else?

i don't know if there is an issue for this, but additionally sonarr currently only fetches the english tvdb data. it would be nice to use foreign titles and metadata if the language profile for the series is set to that. Currently many Episodes just have the title TBA even though a Geman title is availible

**Comment by stevietv** [comment]
Enable `Import Extra Files` in your media management settings and and `srt,nfo` to the types of files.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
