### ISSUE TITLE
The quality score is displayed incorrectly when importing, making it impossible to import

### ISSUE THREAD

**Issue by WoodC2011** [Sonarr/Sonarr#6095]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

There was no problem with the download，The problem occurs when the episodes are automatically upgraded, the results of the sonarr auto-search show a quality score of 3000+, but when imported it becomes -10000，Causes the import to fail

This is the quality score displayed when searching:
![截屏_-_10月12日_下午11_56](https://github.com/Sonarr/Sonarr/assets/57359623/345de840-115a-41be-a616-7c115535e058)

This is the quality score I see when the auto import fails and I try to import manually:
![截屏_-_10月12日_下午5_48](https://github.com/Sonarr/Sonarr/assets/57359623/0d6d5c7d-4eb1-4395-923c-61ef5c918221)

### Expected Behavior

none

### Environment

```markdown
- OS: synology
- Sonarr: 4.0.0.697 Oct 10 2023
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: chrome
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

```
One or more episodes expected in this release were not imported or missing from the release
S1E1.mkv
Not a Custom Format upgrade for existing episode file(s)
```

**Comment by stevietv** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions. 

The quality score on grab was based on release name, and on import is based mainly on filename. The filename S2E4.mkv contains no where near enough information to parse your custom formats.
