### ISSUE TITLE
TV Shows Specials over 100 not updating for Married at First Sight USA

### ISSUE THREAD

**Issue by reefermajic** [Sonarr/Sonarr#6099]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I am using Win11 Sonarr v4.0 and the same was happening on V3.0 whereby the show Married at First Sight has over 100 episodes in Special season category but it is not updating in Sonarr and my file name structure in Windows appears to be consistent.  A member in the Sonarr discord chat suggested if upgrading to V4.0 does not resolve the issue that there must be a bug and hence I am opening this ticket.  I am sending some screenshots.

### Expected Behavior

Sonarr recognizes that I have episodes 103 and 104 etc.
![Pic 1](https://github.com/Sonarr/Sonarr/assets/33611102/26c89b77-6151-48e7-9e4f-ff83d44d7f36)
![Pic 2](https://github.com/Sonarr/Sonarr/assets/33611102/238aef37-d79b-44c9-a8e2-568f96c74752)
![Pic 3](https://github.com/Sonarr/Sonarr/assets/33611102/ac31ee78-b1f4-4529-92f6-6396945ccb59)

### Environment

```markdown
- OS: Win11
- Sonarr: V44.0.0.697
—
Oct 10 2023
develop
Currently Installe
- Docker Install: 
- Using Reverse Proxy: no
- Browser: MS Edge
- Database: Windows
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/12887951/sonarr.trace.txt)

### Anything else?

I have provided screen shots.  Hopefully nothing more for me to add.

**Comment by markus101** [comment]
```
2023-10-12 19:42:31.0|Debug|Parser|Parsing string 'S00.E104.Married at First Sight - Special 104 - Kicking off Denver.mkv'
2023-10-12 19:42:31.0|Trace|Parser|^(?:\[(?<subgroup>.+?)\][-_. ]?)?(?<title>.+?)(?:(?:_|-|\s|\.)+(?:e|ep)(?<absoluteepisode>(\d{3}|\d{4})(\.\d{1,2})?))+[-_. ].*?(?<hash>\[\w{8}\])?(?:$|\.)
2023-10-12 19:42:31.0|Debug|Parser|Episode Parsed. S00 - 104 
```

Looks like this might be an issue with your particular naming format. Do you see the same issue if you rename the file to `S00E104.Married at First Sight - Special 104 - Kicking off Denver.mkv`?

**Comment by reefermajic** [comment]
Yes that resolved the issue.  Thanks so much for your quick response.
