### ISSUE TITLE
Sonarr https client does not support TLSv1.1 or TLSv2

### ISSUE THREAD

**Issue by marvink87** [Sonarr/Sonarr#610]
Today I tried to configure spotweb using the newznab option but somehow this isn't working. I have isntalled Spotweb on Debian 7.8 using apache which redirects all HTTP traffic to HTTPS and has a valid certificate. I tried configuring sonarr/nzbdrone using the http and https prefix but both do not work. When I check my apache logs I notice sonarr/nzbdrone connecting to the http port but I never see a connection to my https port. Also I have checked the URL from the log manually and I without delay receive a valid XML page. Also I have the same configured with Couchpotato and that seems to work.

It seems to be that https is the issue but I have found examples online where https is used. At this point I am unable to troubleshoot any further on my own, please help me.

Log from the HTTP GET until the timeout (I have substituted my URL with something else and filtered out entries involving sabnzbd):

    15-6-8 20:41:05.7|Debug|Newznab|Downloading Feed https://www.substitute.com/spotweb/api?t=tvsearch&cat=5030,5040&extended=1&apikey=<removed>&offset=0&limit=100
    15-6-8 20:41:05.7|Trace|HttpClient|Req: [GET] https://www.substitute.com/spotweb/api?t=tvsearch&cat=5030,5040&extended=1&apikey=<removed>&offset=0&limit=100
    15-6-8 20:41:19.2|Trace|Scheduler|Pending Tasks: 0
    15-6-8 20:41:49.2|Trace|Scheduler|Pending Tasks: 2
    15-6-8 20:41:49.2|Trace|CommandQueueManager|Publishing CheckForFinishedDownload
    15-6-8 20:41:49.2|Trace|CommandQueueManager|Checking if command is queued or started: CheckForFinishedDownload
    15-6-8 20:41:49.2|Trace|CommandQueueManager|Inserting new command: CheckForFinishedDownload
    15-6-8 20:41:49.3|Trace|CommandExecutor|CheckForFinishedDownloadCommand -> DownloadMonitoringService
    15-6-8 20:41:49.3|Trace|CommandQueueManager|Marking command as started: CheckForFinishedDownload
    15-6-8 20:41:49.3|Trace|CommandQueueManager|Publishing DownloadedEpisodesScan
    15-6-8 20:41:49.3|Trace|CommandQueueManager|Checking if command is queued or started: DownloadedEpisodesScan
    15-6-8 20:41:49.3|Trace|CommandQueueManager|Inserting new command: DownloadedEpisodesScan
    15-6-8 20:41:49.3|Debug|DiskScanService|Scanning '/srv/buffer/automated/done/series_sonarr_watchdir/' for video files
    15-6-8 20:41:49.3|Debug|DiskScanService|0 video files were found in /srv/buffer/automated/done/series_sonarr_watchdir/
    15-6-8 20:41:49.3|Trace|ConfigService|Using default config value for 'removecompleteddownloads' defaultValue:'False'
    15-6-8 20:41:49.4|Trace|ConfigService|Using default config value for 'downloadclienthistorylimit' defaultValue:'30'
    15-6-8 20:41:49.4|Trace|CommandExecutor|DownloadedEpisodesScanCommand -> DownloadedEpisodesCommandService
    15-6-8 20:41:49.4|Trace|CommandQueueManager|Marking command as started: DownloadedEpisodesScan
    15-6-8 20:41:49.4|Trace|ConfigService|Using default config value for 'removecompleteddownloads' defaultValue:'False'
    15-6-8 20:41:49.4|Trace|EventAggregator|Publishing TrackedDownloadRefreshedEvent
    15-6-8 20:41:49.4|Trace|EventAggregator|TrackedDownloadRefreshedEvent -> QueueService
    15-6-8 20:41:49.4|Trace|EventAggregator|Publishing QueueUpdatedEvent
    15-6-8 20:41:49.4|Trace|EventAggregator|QueueUpdatedEvent -> QueueModule
    15-6-8 20:41:49.5|Trace|EventAggregator|QueueUpdatedEvent <- QueueModule
    15-6-8 20:41:49.5|Trace|EventAggregator|TrackedDownloadRefreshedEvent <- QueueService
    15-6-8 20:41:49.5|Trace|CommandQueueManager|Updating command status
    15-6-8 20:41:49.7|Trace|ConfigService|Using default config value for 'downloadedepisodesfolder' defaultValue:''
    15-6-8 20:41:49.7|Trace|DownloadedEpisodesCommandService|Drone Factory folder is not configured
    15-6-8 20:41:49.7|Trace|CommandQueueManager|Updating command status
    15-6-8 20:41:49.7|Trace|EventAggregator|Publishing CommandExecutedEvent
    15-6-8 20:41:49.7|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
    15-6-8 20:41:49.7|Trace|TaskManager|Updating last run time for: NzbDrone.Core.MediaFiles.Commands.DownloadedEpisodesScanCommand
    15-6-8 20:41:49.7|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
    15-6-8 20:41:49.7|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
    15-6-8 20:41:49.7|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
    15-6-8 20:41:49.7|Trace|CommandExecutor|DownloadedEpisodesScanCommand <- DownloadedEpisodesCommandService [00:00:00.2232890]
    15-6-8 20:41:50.1|Trace|EventAggregator|Publishing CommandExecutedEvent
    15-6-8 20:41:50.1|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
    15-6-8 20:41:50.1|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Download.CheckForFinishedDownloadCommand
    15-6-8 20:41:50.1|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
    15-6-8 20:41:50.1|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
    15-6-8 20:41:50.1|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
    15-6-8 20:41:50.1|Trace|CommandExecutor|CheckForFinishedDownloadCommand <- DownloadMonitoringService [00:00:00.1753660]
    15-6-8 20:42:19.4|Trace|Scheduler|Pending Tasks: 0
    15-6-8 20:42:45.7|Warn|Newznab|Unable to connect to indexer: The request timed out
    
    System.Net.WebException: The request timed out
      at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
      at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0 
      at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00000] in <filename unknown>:0 
    
    15-6-8 20:42:46.1|Trace|NzbDroneErrorPipeline|Handling Exception
    15-6-8 20:42:46.1|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
     -- Unable to connect to indexer, check the log for more details

**Comment by marvink87** [comment]
OK I've found that Sonarr does not support TLSv1.1 or TLSv2 and besides that it does not support the cipher ECDHE-RSA-AES256-GCM-SHA384.

While I can understand Sonarr not supporting that cipher, isn't it time for Sonarr to support a better SSL protocol?

**Comment by markus101** [comment]
We're limited to what .net 4.0 supports at the moment. v3 will require .net 4.5 (or whatever is current when it comes out). .net 4.0 when 4.5 is installed has better support, but mono is severely lacking.

TL/DR: We're limited by the framework.

**Comment by Taloth** [comment]
mono 4.0.1 or something like may have support. But I haven't tested that. I'm still on 3.10 myself.

**Comment by hashworks** [comment]
I'm on mono 4.4 and it still won't work with this cipher:
`ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"`

What is the "minimum" I can set here? Currently I'm using the nginx default, however that is quite unsecure.
