### ISSUE TITLE
Spelling mistake in Filters

### ISSUE THREAD

**Issue by Matthewenderle** [Sonarr/Sonarr#6103]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When you click on Filters from the webUI "Ended" reads as "Enderd"
![image](https://github.com/Sonarr/Sonarr/assets/1463854/3fe3d930-70bd-4c0f-bb0c-77b2b6278468)

### Expected Behavior

It should read as "Ended"

### Environment

```markdown
- OS: Ubuntu
- Sonarr: 3.0.10.1567
- Docker Install: 3.0.10.1567-ls194 by linuxserver.io 
- Using Reverse Proxy: no
- Browser: Firefox 118.0.1 (64-bit)
- Database: 6.12.0.182
```

### What branch are you running?

Main

### Trace Logs?

na

**Comment by markus101** [comment]
That's a custom filter that you setup with that spelling mistake. The ended filter that is included with Sonarr is labeled `Ended Only` with the correct spelling.
