### ISSUE TITLE
Add user SSL certificate functionality in the Sonarr similar to Prowlarr, Radarr, and Lidarr

### ISSUE THREAD

**Issue by AntonTerehov** [Sonarr/Sonarr#6106]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, in the Prowlarr, Radarr, and Lidarr dockers, you can go to Settings->General and specify the user's pfx certificate that will be used for HTTPS connection. Note: you have to enable advanced settings before.
Sonar docker doesn't have this functionality.
I haven't found an easy way to add an SLL certificate to the Sonarr. I'd like to have the ability to use my personal SSL certificate (any of these would work - pfx/pem/cert+key.
Initially, I thought that it was just the UI bug, so I manually updated the config.xml file, but it didn't work and config removed "extra" properties in the container initialization phase.
Thank you!
![Prowlarr](https://github.com/Sonarr/Sonarr/assets/5038548/03c7031a-3776-4c9e-b689-b14e40f99766)
![Radarr](https://github.com/Sonarr/Sonarr/assets/5038548/1acae303-1cf7-49af-9a39-1e99d69dfca1)
![Sonarr](https://github.com/Sonarr/Sonarr/assets/5038548/4507ca19-9265-4198-9020-0b2e2056a71d)

### Describe the solution you'd like

Could you please add SSL path feature to the Sonarr that already exists in the Prowlarr, Radarr, and Lidarr?

### Describe alternatives you've considered

Any other alternative/documentation on how to add a custom, user's SLL (it may be any of these: pfx/pem/cert+key).

**Comment by markus101** [comment]
This is already in the v4 beta.
