### ISSUE TITLE
Database gone after update/restart

### ISSUE THREAD

**Issue by bakman2** [Sonarr/Sonarr#611]
How is it possible that Sonarr is completely empty after a restart ? All my settings gone, tv shows everything. I have had this issue twice and it is starting to annoy me.

Running on Freenas 9.3.

**Comment by markus101** [comment]
Please use the forums for support.

Changed the user its running under or something external to Sonarr caused the files to be deleted (stored in a non-permanent location). The only possible way Sonarr could delete its settings is during an upgrade and the plugin for Sonarr has incorrectly configured the AppData directory under the App (start-up directory).
