### ISSUE TITLE
Giving extra points to season packs causes CF scores to be lost when imported

### ISSUE THREAD

**Issue by WoodC2011** [Sonarr/Sonarr#6112]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I set it up so that S1 such would have an extra 500 points, i.e. 500 points for S1 and 0 points for S1E1

This led to a misrecognition when importing, as in the example below: the download was a season pack, so the score was 2901, but the files in the season pack were single episodes, which led to a single episode score of only 2401 (500 points less), which led to a failure of the import.

![3](https://github.com/Sonarr/Sonarr/assets/57359623/d569ef8c-cd54-4532-99f2-fa04272590d3)

![2](https://github.com/Sonarr/Sonarr/assets/57359623/87b1a8b3-1c11-4347-ab17-cf3474fa9360)

### Expected Behavior

Correctly calculated score

### Environment

```markdown
- OS: synology
- Sonarr: v4
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: chrome
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

none

### Anything else?

none

**Comment by stevietv** [comment]
There is enough warning on trash guides about using a [season pack preference](https://trash-guides.info/Sonarr/sonarr-collection-of-custom-formats/#season-pack).

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by WoodC2011** [comment]
> There is enough warning on trash guides about using a [season pack preference](https://trash-guides.info/Sonarr/sonarr-collection-of-custom-formats/#season-pack).
> 
> Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Sorry to add due to the fact that I don't understand English very well.

Does it mean that if I use Seasonal Priority, I may face the problem of repeated downloads, & the need to select manually?

**Comment by bakerboy448** [comment]
Related to / dupe of https://github.com/Sonarr/Sonarr/issues/5598
