### ISSUE TITLE
Include Recycling Bin Path in Custom Script

### ISSUE THREAD

**Issue by oraclesod** [Sonarr/Sonarr#6114]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have a post processing script to deal with the backup files that Sonarr creates, however the current post processing information provided to the script doesn't contain the final filename and path of the backup file. This has made it difficult to identify the file for other post processing tasks. 

What it does contain is the sonarr_deletedrelativepaths and sonarr_deletedpaths, but this refers to the file in its original location, if a file with the same name exists in the final backup path, Sonarr appends an incrementing number (eg _1) to the filename which there is no reference to in the arguments passed to the script. Sometimes i may have 3-4 files for the same as it upgades

At this point I use code to try and detect the new filename of the backup file but this perfect and exact, on 1000 files i may get 10-20 issues with the detection

### Describe the solution you'd like

My request is to add the final backup file full paths into the available post processing arguments

### Describe alternatives you've considered

Alternatively updating the sonarr_deletedrelativepaths and sonarr_deletedpaths to be the final backup file would also work

**Comment by markus101** [comment]
I don't follow what the issue is. Sonarr only keeps one file per episode and whatever file it deletes for the upgraded file is based on the path it has stored for the file, if there are other files that Sonarr is not tracking then they won't be included. If you have multiple episode files in the series folder it's not Sonarr importing them as failing to delete the previous file will cause the import to fail.

**Comment by oraclesod** [comment]
Sorry ill clarify.

When Sonarr has a file downloaded, eg: show - 1x01 - epname.mp4, and it finds a better match, it will move to say "/backup/show/season 1/show - 1x01 - epname.mp4" and set sonarr_deletedrelativepaths to be "season 1/show - 1x01 - epname.mp4"

Now say it finds another even better match, it will again move the file however it renames and doesnt overwrite, so the new backup file will be "/backup/show/season 1/show - 1x01 - epname_1.mp4" and the issue is that sonarr_deletedrelativepaths is still setto be "season 1/show - 1x01 - epname.mp4" and not "season 1/show - 1x01 - epname_1.mp4", same goes for sonarr_deletedpaths

So when passing sonarr_deletedrelativepaths to my post process script at the time of the second replacement, the script cant reference the correct file

**Comment by markus101** [comment]
Deleted relative path refers to the path when the file was in the series folder. It has nothing to do with the recycling bin folder, Sonarr does not maintain any reference to files in the recycling bin.

**Comment by oraclesod** [comment]
Yep i do understand that, this is a feature request: My request is to add the final backup file full paths into the available post processing arguments

Although Sonarr doesnt need to maintain the reference to files in the recycling bin path, im asking to add it to the final output to post processing script so that it can be used externally, after its sent to the post processing script Sonarr can continue to not store or use the information, but at least its been passed on so externally we know where the file went
