### ISSUE TITLE
Add an option to let the Preferred Words score override quality and other settings - General improvements on the scoring/parsing system

### ISSUE THREAD

**Issue by HerrCraziDev** [Sonarr/Sonarr#6115]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

At the current time, Preferred Words seems to be used as the last resort test when deciding between two releases. Quality completely overrules the Preferred Words score, which is for my usage absolutely not desirable ; as if a lesser quality release (as in bad encoding, bad subtitles, etc) with a higher quality setting (eg. BluRay-1080p over HDTV-1080p) is released before, it will be grabbed immediately and will lead to the release I'm more interested in (the one with the larger word score) being ignored (Sonarr will refuse to "downgrade" to a lower quality setting even if it has a better word score).

This also causes episodes from different teams being grabbed depending on the availability and quality settings. I have regexes with my preferred teams in my profiles, and they end up being overridden by other settings out of my control, leading to episodes from mixed teams. This is not desirable, and requires manual selection for each episode. 

Manual selection is always possible but defeats the point of automation. Moreover, while manually selecting a season pack isn't especially cumbersome, doing so for an airing series for each new episode can be a hassle. 

Another issue is that languages are rarely properly parsed. Multi-language releases should match all languages present. French language is rarely detected on anime series from nyaa.si if at all, despite being in the release titles, as variants of "FR", "FRE", "FRENCH", "VOFR" or "VOSTFR" - the latters are the usual abbreviations for French, litt. "Original version, french" (**V**ersion **O**riginale **FR**) and "Original version, subtitled French" (**V**ersion **O**riginale **S**ous-**T**itrée **FR**). This may constitute a separate issue. (I'll create one if needed)

### Describe the solution you'd like

Ideally :

- Quality should not trump the Preferred Words score ; the reasoning being that if the user took the time to write regexes to rank candidate releases, it's (assumedly) for a good reason.
- Preferred Words score should be computed on all releases, even those that can't be parsed. Sometimes, Sonarr is unable to parse a release returned by the indexer, and will thus reject it. The score should still be computed, so that the release appears higher in the list, and may even be grabbed despite not being parsed (leaving it to be manually imported later).
- Ideally all items (at least quality, but that could also include whether or not the release is a season pack, etc) would be contributors towards a global score counter that would be configurable by the user. This would allow the user to set what's truly most important in their eyes ; quality, languages, the team, etc...
- There should be an option to prioritize team consistency over best quality ; if a specific team has been used for previous episodes, Sonarr should override other settings and keep downloading from that team if available, only defaulting to other sources in the meantime or if the team does not/stops publishing episodes for the series.
- Languages should be parsed correctly, especially matching all languages of a MULTi release, and properly matching the French "VOSTFR" acronym as French. 
- The user may want to provide additional regexes for matching specific language acronyms or patterns.

Allowing more user control, via regexes or other methods, is especially a need in the field of Japanese anime series, as they've always been a mess in terms of conventions and following naming schemes. Nyaa.si is full to the brim of badly-named releases, which are often ironically the ones users may be looking for. Allowing users to rank their favorite teams, tinker regexes matching their local languages, naming patterns, and whatever their local usages in the fansubbing fandoms may dictate would be a significant improvement in the experience with these platforms. Often times, as described above, Sonarr's behavior may be counter intuitive and confusing, and requires manual intervention. 

### Describe alternatives you've considered

There are sadly no real alternatives to manual intervention in the cases I've described above. Mostly,
 - Nyaa.si is the main (and practically only) anime indexer with a good availability of series (+ it's free)
 - The internal release selection system is an opaque box to the user, for whom the Preferred Score setting is a good customization lever, albeit insufficient. This is further exacerbated by indexers with traditionally poorly followed standards, like Nyaa. 
 - The language filter is basically useless for French if not matching "VOSTFT", "VO" and "VOFR"

### Anything else?

Many thanks for the good work on Sonarr, a very precious tool that has been the backbone of my series consumption for a good while now! :heart: Y'all rocks!

I *may* look into implementing some of the changes I suggest here in a PR, if I have the time and Sonarr's codebase doesn't devours my soul (I've never looked into it yet, I'll admit, but that would be a starting point). I'll waddle around until some feedback is brought here anyways. 

Cheers from Brittany <3

**Comment by thezoggy** [comment]
this is already addressed in sonarr v4 which uses custom formats now. language profile is removed with it. you should look at upgrading

**Comment by HerrCraziDev** [comment]
Oh, this is totally unexpected, would be awesome! Has this update been pushed to the Debian repo yet ? (I'm running in a good ol' Debian box)

**Comment by HerrCraziDev** [comment]
PS : I'm running 3.0.10, which is the latest version according to the update menu. The website also only advertises Sonarr v3. Is v4 out yet?
![image](https://github.com/Sonarr/Sonarr/assets/28117703/4b44111c-d2bc-4942-8e20-8de26cef4196)

**Comment by markus101** [comment]
As Zoggy said, the v4 beta improves upon a lot of this.

- If you want CF/preferred to trump quality, group all the qualities together
- In v4 CF's are not calculated if the release cannot be parsed as information missing from failing parsing is not available
- No plans for a global score
- Sonarr does this for anime already, no plans for everything
- VOSTFR is intentionally not French as it's original use is in subtitles
- Language parsing is still limited to specific regex/terms, but with Custom Formats you have more control over things

v4 is still beta, there is not a debian package currently.

**Comment by HerrCraziDev** [comment]
Eager to see it out then, thanks !
