### ISSUE TITLE
Add SEV/D0ct0rLew/Kira to the list of exception release groups

### ISSUE THREAD

**Issue by Metropolis76** [Sonarr/Sonarr#6118]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sonarr currently doesn't match D0ct0rLew's SEV releases or a number of Kira's SEV releases with the SEV release group. 

D0ct0rLew Single Episode Release:
 - Loki S02E03 1893 4k to 1080p DSNP WEBrip x265 DDP5.1 D0ct0rLew[SEV]

D0ct0rLew Multi Episode Releases:
 - Foundation S02E09 & 10 4k to 1080p ATVP WEBrip x265 DDP5.1 D0ct0rLew[SEV]
 - Gen V S01E01-E02-E03 4k to 1080p AMZN WEBrip x265 DDP5.1 D0ct0rLew[SEV]

Kira Season Pack (As seen in Sonarr):
 - The Continental From the World of John Wick Season 01 S01 2023 1080p AMZN UHD WebRip x265 DDP 5.1 Atmos Kira-SEV

Kira Single Episode Releases:
 - Mr. Robot S04E04 404 Not Found 1080p AMZN WebRip x265 DDP 5.1 Kira [SEV]
 - Invincible - S01.E06 - You Look Kinda Dead 1080p AMZN WebRip x265 DDP 5.1 Kira [SEV]
 

### Describe the solution you'd like

Add D0ct0rLew and Kira to the list of exception release groups so their release are matched properly within Sonarr.

### Describe alternatives you've considered

When wanting to add D0ct0rLew or Kira to a Custom Format, using the Release Title option is currently the only way. This works for scoring, but doesn't help if you have the "-RlsGrp" tag when renaming files due to the fact sonarr doesn't match D0ct0rLew[SEV] or some of Kira's releases to a release group.

**Comment by stevietv** [comment]
to be clear, the release group here is `SEV`, not `D0ct0rLew` or `Kira` right?

**Comment by Metropolis76** [comment]
Correct. SEV is the group, D0ct0rLew and Kira are uploaders/encoders for said group. And the only two that exist as far as i know.
