### ISSUE TITLE
Group search results by release group

### ISSUE THREAD

**Issue by SAKUJ0** [Sonarr/Sonarr#612]
Assuming NZB Titles are identical, things like this could be avoided:

![Suboptimal UI](https://i.imgur.com/tr3zyNL.png)

Instead, what I propose, is to group _identical_ NZB Titles in a way that
1. No duplicate NZB Titles occur, as is the case with Torrents, which you would be able to see for yourself in the bottom of the picture, if it were not for a hundred `IMMERSE` and `0sec` entries.
2. Size and age are averaged and summarized in this list
3. To steamline NZB results with Torrent results, each set-up indexer should get one entry.
4. Clicking on such a group title, gives the current view (I, personally, do not care about this)

What do you think? I believe this is highly low priority, as ideally, people can trust a perfect and automated search to begin with. Regardless, this seems to be a clear improvement with the only drawback being the time put in.

_Edit_ Titles are written in caps, right? :grin:

**Comment by markus101** [comment]
So clicking on the group would show you all the duplicated results? If I want to pick a specific release from a specific indexer I would need to click twice? What if some of the dupes are blacklisted, or rejected for some reason (we're not likely to differentiate between rejection reasons at the UI level)?

All NZBs are not created equal, two indexers almost always have something slightly different between them, not to mention the reasons for the dupes can be numerous, different groups, reposts, fixed nzbs, etc, all reasons why we overhauled the blacklisting system to be a lot more strict on what it treats as the same release.

I don't see the effort to group being worth it, overall manual search could use some improvements giving it the ability to filter, but grouping seems like extra work that doesn't offer a ton of value.

**Comment by Taloth** [comment]
See https://github.com/Sonarr/Sonarr/issues/375 and possibly https://github.com/Sonarr/Sonarr/issues/260. The first one also deals with better visualisation of rejections.
It would be better to just put 0sec in the rejected keyword list and then have the UI filtering deal with it.

I agree with markus on the grouping. Grouping multiple releases with the same name would be a bad idea.

**Comment by SAKUJ0** [comment]
*Please do not waste time on this, if you just disagree*. That is absolutely fine. You know far more about UI design than I ever will. I mainly ask, in order not to waste time on making a PR, we disagree with categorically.

> So clicking on the group would show you all the duplicated results?

The idea is that sometimes you would need individual release information. I am only talking about avoiding redundancy on a UI perspective. So I would prefer the search results to only show unique entries.

So instead of having many pages of search entries (sometimes up to tens), the user is mainly interested in having upper screenshot collapsed into two entries like this

nzb | age | name | indexers | size
--- | --- | ---- | -------- | ----
nzb | 200-790 days | Episode.Name.YYYY.Source.Codec-IMMERSE | PFMonkey (5), NZBsu (2) | Average size
nzb | 201-791 days | Episode.Name.YYYY.Source.Codec-0sec | PFMonkey (10), NZBsu (1), DOGnzb (1) | Average size

That information would summarize the same search results in two lines, instead of more than a hundred. From a UI perspective, it seems like a vast improvement.

> What if some of the dupes are blacklisted, or rejected for some reason (we're not likely to differentiate between rejection reasons at the UI level)?

That is why I suggested to keep the exact view you have implemented right now, and merely to *collapse* it, to give the relevant information on first glance. The same way you do not expand every season when you click a series page. You collapse the seasons as we are likely only interested in season summaries (except for the latest season).

A user would be mainly interested if *no*, *all* or *some* of the search results are blacklisted / ignored. So instead of having ~ 150 lines that either have an icon indicating that, I find a number of blacklisted search results greatly superior.

> All NZBs are not created equal, two indexers almost always have something slightly different between them, not to mention the reasons for the dupes can be numerous, different groups, reposts, fixed nzbs, etc, all reasons why we overhauled the blacklisting system to be a lot more strict on what it treats as the same release.

And those commits were great. It actually was an issue for me, I used to just avoid blacklisting altogether, for this. I am not suggesting to "throw away" information. I am not suggesting to suggest different *internal* behavior.

I am merely suggesting to avoid redundancy. A user does not want to see duplicate information repeated over many lines. It does not really matter if it is ~ 100 search results or 3. The NZBs being different is only relevant to the user as an answer to "How many NZBs are there for this episode?" or "How old are those NZBs"? Maybe size, too - I tend to pick larger ones as I suspect they have more par2 files - but I can't recall when I last had a failed download either way.

> I don't see the effort to group being worth it, overall manual search could use some improvements giving it the ability to filter, but grouping seems like extra work that doesn't offer a ton of value.

Now I really believe we are talking on cross purposes. I am really only suggesting a change on a CSS / HTML level. I am quite sure you misunderstood me. I am not suggesting to change any underlying code or any data structures (whatsoever). I am just suggesting to add one of those [+] buttons, that expands search results, so we get the details only when we want / need them.

**Comment by thezoggy** [comment]
i think sakuj0 is just wanting 'grouping' by the releasegroup..
personally i'd like to see something like:

http://mottie.github.io/tablesorter/docs/example-widget-grouping-filter-childrows.html

where one could sort/filter and use groups to collapse similar named releases..

**Comment by SAKUJ0** [comment]
> 'grouping' by the releasegroup..
Pretty much. To re-iterate, only a visual change in markup / CSS is proposed, as it would greatly improve the manual search. I just mentioned "group by nzb name", as the NZB name (case-insensitive) should only deviate in the releasegrp. It is O.K, if there are a few outliers, which would create duplicated groups (as everything is only visual and no change in algorithms or data structures is proposed). That would be the indexer's job, to deduplicate IMO.

Exactly like that example zoggy supplied. (The same way that Sonarr does not show all 100-200 episodes on the series page at once, unless you "expand" the collapsed seasons)

**Comment by markus101** [comment]
Custom filtering will be in v3, at this time there are no plans for grouping.
