### ISSUE TITLE
[Bug] Title Slug <for show> Is In Use By Series <another show>

### ISSUE THREAD

**Issue by janusn** [Sonarr/Sonarr#6126]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr refused to import the second show, reported an error
`Title slug 'my-home-hero' is in use by series 'My Home Hero'. Check the FAQ for more information`

2 shows on https://thetvdb.com/ returned the same title. Worse yet, they are released in the same year. They are just 2 adaptations of the same comics. One being a live action and another being an anime.
The series are:
[My Home Hero](https://thetvdb.com/series/my-home-hero)
[My Home Hero](https://thetvdb.com/series/my-home-hero-live-action)

### Expected Behavior

Both shows can be imported successfully.

### Steps To Reproduce

1. Click Series on the left pane.
2. Select Add New from the drop down menu.
3. Fill the search field with "My Home Hero" and click the search button.
4. Add the 2 shows with the title matching "My Home Hero" precisely. (Both are 2023)

### Environment

```markdown
- OS: Ubuntu 23.04 64bit / Linux 6.5.0-9-generic
- Sonarr: 3.0.10.1567
- Docker Install: 24.0.6, build ed223bc
- Using Reverse Proxy: yes, nginx
- Browser: Google Chrome for Mac Version 118.0.5993.88 (Official Build) (x86_64)
- Database: sqlite3
```

### What branch are you running?

Main

### Trace Logs?

[https://pastebin.com/Kh1r6z29](https://pastebin.com/Kh1r6z29)

**Comment by markus101** [comment]
There are several previous issues on this, one of the series titles should be updated per TheTVDB's rules.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
