### ISSUE TITLE
series monitoring - existing seasons

### ISSUE THREAD

**Issue by yuval987** [Sonarr/Sonarr#6127]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

no , just a new feature that will help me a lot.

### Describe the solution you'd like

another option in series monitoring of existing seasons

### Describe alternatives you've considered

all episods

### Anything else?

i hope to getting an api that do it too.

thanls

**Comment by markus101** [comment]
Please elaborate on exactly what you're looking for.

How would this be different from monitoring all episodes?

**Comment by yuval987** [comment]
I hope you're doing well. I wanted to bring up a feature request that could enhance the usability of Sonarr. Currently, when adding a new series, I utilize the Python library and the "addshow" function with existing episodes monitored to prevent immediate downloads. This approach has been effective for me.

However, after adding the series, I find myself in a situation where I have to manually access the user interface (UI) and select the monitor option for specific series, which I would like to download. Alternatively, I've been using the API to find all episodes of a particular series and change the monitor status for each episode to 'true' using a PUT request.

While this workaround serves its purpose, I've noticed an unintended consequence. When I use the API to mark episodes as monitored, it seems that all episodes within the series are monitored, but not the series itself. This has raised some uncertainty regarding whether Sonarr may attempt to download the entire series package at once or individual episodes one by one.

To streamline this process, I'd like to propose an enhancement. It would be incredibly helpful if Sonarr could offer the option to monitor entire series, specific seasons, or even individual seasons through the UI and the API. This feature would offer greater control and flexibility in managing series monitoring and further improve the user experience.

Thank you for your time and consideration. I believe this enhancement would be valuable to many Sonarr users, including myself. Please let me know if you need any additional details or clarification.

**Comment by markus101** [comment]
This is already possible with the existing API commands. A PUT to update the series monitoring and all series will monitor all episodes. You can also PUT to edit the series monitored state then use season pass to update the monitoring option to monitor all.

Series PUT: https://sonarr.tv/docs/api/#/Series/put_api_v3_series__id_
Season Pass: https://sonarr.tv/docs/api/#/SeasonPass/post_api_v3_seasonpass

If you have questions on how to use the API please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr).

**Comment by yuval987** [comment]
I've been exploring the Season Pass functionality of the Sonarr API (https://sonarr.tv/docs/api/#/SeasonPass/post_api_v3_seasonpass) and encountered an issue. When I set the 'season' parameter to true, it doesn't seem to monitor all episodes as expected. Interestingly, when I perform the same action through the user interface, it works correctly.

Is there any additional configuration or parameter that I might be missing in the API request? I'd appreciate any guidance or insight on how to make it work as intended through the API.
example:
<img width="1284" alt="image" src="https://github.com/Sonarr/Sonarr/assets/88144647/100aa5bf-9e2c-4c93-957f-c093118bf529">


Thanks in advance for your help!
