### ISSUE TITLE
Ended and Missing Episodes colors indistinguishable, even with "Color-Impaired Mode" on

### ISSUE THREAD

**Issue by riley-martine** [Sonarr/Sonarr#6129]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I am red-green colorblind. I cannot tell these two colors apart. (Ended and Missing Episodes)

<img width="282" alt="Screenshot 2023-10-25 at 1 55 33 PM" src="https://github.com/Sonarr/Sonarr/assets/10540915/34b7d46f-0e76-4b12-8898-19c2c6eefc2d">

### Expected Behavior

To be able to tell the colors apart when "Color-Impaired Mode" is turned on.

### Environment

```markdown
- OS: 
- Sonarr: 
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Main

### Trace Logs?

N/A

**Comment by markus101** [comment]
Please fill out all the requested information, the environment information is never optional as it's invaluable for triaging.

In v3 that setting does not correctly affect the series page, but does in v4 (currently in beta).

![image](https://github.com/Sonarr/Sonarr/assets/413544/49cacddd-b4d1-4b89-92dc-0a2165814dae)
