### ISSUE TITLE
Invalid password set by sonarr

### ISSUE THREAD

**Issue by PlanZV** [Sonarr/Sonarr#6130]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Disabling username and password login on the LAN will result in the domain name of sonarr v4 being accessed without an account password as well

### Expected Behavior

none

### Environment

```markdown
- OS: synology
- Sonarr: 4.0.0.700
- Docker Install: yes
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

none

**Comment by markus101** [comment]
Sounds like Bogdan has the fix for you, but please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by PlanZV** [comment]
> You need to forward the client IP instead of proxy IP in your reverse proxy.

I didn't use nginx or anything like that, just forwarded port 8989
