### ISSUE TITLE
Rejecting multi-language release that contains the desired language

### ISSUE THREAD

**Issue by jonathanturcotte** [Sonarr/Sonarr#6132]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr is rejecting a multi-language release that contains my desired language (English):

![image](https://github.com/Sonarr/Sonarr/assets/6924367/db51525a-898d-48eb-9b67-62a6ae9ad422)

![image](https://github.com/Sonarr/Sonarr/assets/6924367/0c61402c-8376-44df-9791-781e5bec00fe)

![image](https://github.com/Sonarr/Sonarr/assets/6924367/acd48350-64cd-439f-88d3-266b0aa57c50)

### Expected Behavior

I would expect the release to be valid because [ENG] is listed in the release name as well as the other languages.

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 3.0.10.1567
- Docker Install: No
- Using Reverse Proxy: Yes 
- Browser: Firefox 119
- Database: N/a
```

### What branch are you running?

Main

### Trace Logs?

Relevant section: 

```
2023-10-27 11:45:07.0|Debug|DownloadDecisionMaker|Processing release '[Erai-raws] Jujutsu Kaisen 2nd Season - 14 [480p][Multiple Subtitle] [ENG][POR-BR][SPA-LA][SPA][ARA][FRE][GER][ITA][RUS]' from 'Nyaa'
2023-10-27 11:45:07.0|Debug|Parser|Parsing string '[Erai-raws] Jujutsu Kaisen 2nd Season - 14 [480p][Multiple Subtitle] [ENG][POR-BR][SPA-LA][SPA][ARA][FRE][GER][ITA][RUS]'
2023-10-27 11:45:07.0|Trace|Parser|^\[(?<subgroup>.+?)\][-_. ]?(?<title>[^-]+?)(?:(?<![-_. ]|\b[0]\d+) - )(?:[-_. ]?(?<absoluteepisode>\d{2,3}(\.\d{1,2})?(?!\d+)))+(?:[-_. ]+(?<special>special|ova|ovd))?.*?(?<hash>\[\w{8}\])?(?:$|\.mkv)
2023-10-27 11:45:07.0|Debug|Parser|Episode Parsed. Jujutsu Kaisen 2nd Season - 014 
2023-10-27 11:45:07.0|Debug|Parser|Language parsed: Italian
```

**Comment by stevietv** [comment]
language behaviour has changed in v4.
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by jonathanturcotte** [comment]
@stevietv Sorry, could you give a bit more information? I'm on v3, and from what information I can find v4 is still in beta. Is the policy to push people with v3 issues to use v4 before it's released as stable? 

It would also be great if you could let me know:
 - If v4 fixes the above issue
 - When v4 will be released as stable if it does

**Comment by stevietv** [comment]
As you can see, this one would be parsed as multiple languages in v4:"

![image](https://github.com/Sonarr/Sonarr/assets/1117625/45c66310-510b-48b6-857d-0ae7cddd8f3a)


There is no dev work or fixes happening in v3 for a year now. V4 beta has been around for a year and is very stable.
No timeline on the 'formal' release of it yet, if you want to ask more about it drop by our Discord.

**Comment by jonathanturcotte** [comment]
That's good to know, thank you! My final comment would just be that since v3 isn't being supported anymore, I'd recommend just biting the bullet and pushing v4 to stable. It doesn't make much sense to put new users on v3 when it's abandonware 😉
