### ISSUE TITLE
Partial Library Scan by Connection to Plex Media Server

### ISSUE THREAD

**Issue by EarzFish** [Sonarr/Sonarr#6141]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently connections from Sonarr to PMS trigger an entire library scan on changes to the media directories. This is exhaustive and resource consuming.

### Describe the solution you'd like

Trigger only a partial scan in PMS of only the subfolder that contains the changed media

### Describe alternatives you've considered

Using Autoscan from Cloudb0x but this is janky compared to having the solution built into Sonarr itself

**Comment by markus101** [comment]
Sonarr has always tried to scan just the folder that changed, but in v3 that depends on Sonarr being able to find the matching series in Plex.

In v4, Sonarr improves upon this by trying to find a matching library as well as adding the ability to do a path remapping.
