### ISSUE TITLE
Add default download location per profile to better library management

### ISSUE THREAD

**Issue by ZerkerEOD** [Sonarr/Sonarr#6143]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

With a lot of us spinning up multiple instances to handle different libraries, it is becoming cumbersome. While the program remembers the last location it would be nice to add a default destination per profile.,

### Describe the solution you'd like

Add a default download location per profile, this way a user only needs to have one server to manage different libraries. On Reddit, I see it common for people to have a 4k server, a normal 1080p server, and an anime server because it is easier to handle. With version 4 though being able to set CF per profile could allow a user to merge the servers and manage multiple libraries depending on the release profile (mainly for TV content and Anime usually have different library directories). Having this default based on the profile would make it easier to remember that if I select a TV profile to go to the TV directory, vs if I select an Anime profile to go to the Anime directory. 

### Describe alternatives you've considered

The alternative right now is to have multiple servers so that the saved last location never really changes. This brings higher upkeep though with managing and updating multiple servers (three based on the example above, two in my case). This also helps end-users make requests through stuff like overseerr to not have to know the server directories and rather just tell them to select the anime profile if it's an anime or tv for tv and it goes to the right destination once grabbed. 

### Anything else?

I can't think of anything else to add, I don't know how much work this would be since I am not a programmer myself, but I would love to see something like this in order to manage multiple libraries.

**Comment by bakerboy448** [comment]
Sonarr doesn't download anything. Are you requesting that quality profiles are tied to root folders?   Though both are selected when adding the series.

**Comment by ZerkerEOD** [comment]
> Sonarr doesn't download anything. Are you requesting that quality profiles are tied to root folders? Though both are selected when adding the series.
> 
> what if a user doesn't have any relation to root folders and quality profiles? how should those work? How about if a quality profile changes or a root folder linked to a quality profile changes? Should existing series be automatically moved? Promoted to move?
> 
> based on your usecase that's really something the request app can and should handle
> 
> for getting both 4k and non-4k content this doesn't fix anything for users having multi instances
> 
> release profiles (preferred words) were already assignable to series by tags, so custom format scoring at a quality profile level v4 don't change much

Yes, I think the root folders. I agree not a huge case for 4k, as usually you wouldn't have a 4k tv root folder and a TV root folder. For me I have a couple friends that that I allow to request with overseerr and right now they have to select the TV or anime server and I don't want them to have to worry about remembering to change the root folder also if possible.

It's probably not a huge deal or a high priority, but I think that's the only thing preventing me from being my anime sonarr with the tv series sonarr instance I have.

**Comment by markus101** [comment]
This is something that we've discussed before, but it's not something we have plans to implement at this time.

**Comment by ZerkerEOD** [comment]
@markus101, That makes me sad, but I understand. Is there a reason why there are no plans for it though? I would assume people that are hosting a library per server for less manual management would love to see this option added now that the CF can be placed per QP.
