### ISSUE TITLE
Add new Release Groups

### ISSUE THREAD

**Issue by tejasgadhia** [Sonarr/Sonarr#6146]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some release groups name their files differently, specifically QXR, UTR, Joy, and Vyndros. I've included a list of sample file names that do not get their Release Group automatically identified. 

### Describe the solution you'd like

The following are QXR releases that follow the same format:
Curb Your Enthusiasm (2000) - S11E01 - The Five-Foot Fence (1080p HMAX WEB-DL x265 afm72).mkv
Grey's Anatomy (2005) - S01E01 - A Hard Day's Night (1080p DSNP WEB-DL x265 Garshasp).mkv
Wednesday (2022) - S01E01 - Wednesday’s Child is Full of Woe (1080p NF WEB-DL x265 Ghost).mkv
Carnival Row (2019) - S01E01 - Some Dark God Wakes (1080p AMZN WEBRip x265 ImE).mkv
Marvel's Agent Carter (2015) - S02E04 - Smoke & Mirrors (1080p BluRay x265 Kappa).mkv
Snowpiercer (2020) - S02E03 - A Great Odyssey (1080p BluRay x265 Kappa).mkv
The Witcher (2019) - S01E01 - The End's Beginning (1080p NF WEBRip x265 MONOLITH).mkv
Enaaya (2019) - S01E01 - Episode 1 (1080p WEB-DL x265 Natty).mkv
SpongeBob SquarePants (1999) - S03E01-E02 - Mermaid Man and Barnacle Boy IV & Doing Time (1080p AMZN WEB-DL x265 RCVR).mkv
Invincible (2021) - S01E02 - Here Goes Nothing (1080p WEB-DL x265 SAMPA).mkv
Loki (2021) - S01E02 - The Variant (1080p DSNP WEB-DL x265 Silence).mkv
Star Wars Andor (2022) - S01E12 - Rix Road (1080p DSNP WEB-DL x265 t3nzin).mkv
Game of Thrones S08E01 Winterfell (1080p BluRay x265 10bit Tigole).mkv
Doctor Who (2005) - S12E01 - Spyfall (1) (1080p BluRay x265 Panda).mkv
The Bad Batch (2021) - S01E01 - Aftermath (1080p DSNP WEB-DL x265 YOGI).mkv
Line of Duty (2012) - S01E01 - Episode 1 (1080p BluRay x265 r00t).mkv

The following uploaders seem to lack consistent naming schemes:
Marvel's Runaways (2017) - S01E01 - Reunion (1080p AMZN WEB-DL x265 Vyndros).mkv
The Witcher S01E07 Before a Fall [1080p x265 10bit Joy].mkv
Rich & Shameless - S01E01 - Girls Gone Wild Exposed (720p x265 EDGE2020).mkv

This uploader is weird because UTR get identified as the Release Group when it should be Qman:
You S02E01 A Fresh Start.1080p.NF.WEB-DL.x265.10bit.EAC3.6.0-Qman[UTR].mkv

### Describe alternatives you've considered

Discussed in the Discord and created this issue per instructions of StevieTV

**Comment by stevietv** [comment]
thanks for adding these.
Markus - these would typically fall under the releasegroup exception regex https://github.com/Sonarr/Sonarr/blob/165e3dbae8c9ba478d4aac4bd1b8514f54f0dfec/src/NzbDrone.Core/Parser/Parser.cs#L522
but this list is growing and maybe it needs to be tackled in a different way for releasegroups ending in )

what I can see out of this list the following need adding:

* Garshasp
* Kappa
* Natty
* RCVR
* SAMPA
* YOGI
* r00t
* EDGE2020

**Comment by bakerboy448** [comment]
@stevietv some of these should be exact groups.  Check downstream in radarr where most of these are implemented already

agree on a better way to maintain given the exception and exact exception lists are getting a little lengthy unfortunately
