### ISSUE TITLE
Import List for Plex - add config option to sync watchlists from friends

### ISSUE THREAD

**Issue by jay-kub** [Sonarr/Sonarr#6152]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

In order to sync a watchlist you have to authenticate via Plex, which can be difficult to do for another user who is not on the same physical network as Sonarr, as they would essentially need to share their username and password with you.

### Describe the solution you'd like

Plex added a new feature allowing you to see your friend's watchlists. Under the config for _Import List > Add List > Plex Watchlist_ it would be great if there was an option to sync watchlists from your friends.

### Describe alternatives you've considered

You could share username/passwords or opening up your Sonarr instance to the internet, both of which are security concerns.

**Comment by markus101** [comment]
This is already possible in v4 using the RES feed from Plex (requires Plex Pass).
