### ISSUE TITLE
Remove embeded covers during import

### ISSUE THREAD

**Issue by Doublemyst** [Sonarr/Sonarr#6153]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When you are downloading TV series not in English, you are downloading often them from 3rd party translation groups on their resources. They like adding season covers on all their translated episodes, so Plex is automatically displaying them (which leads, that all the episode thumbnails are looking exactly the same in the overview).

### Describe the solution you'd like

It would be awesome, if there would be a possibility (checkbox in the settings) to automatically delete covers while importing (pickup from download client) new episodes. 

### Describe alternatives you've considered

At the moment the only workaround out there is using programs like Mp3tag in order to delete covers from existing files on the file system.

**Comment by markus101** [comment]
We have no plans to update/alter files during import, you will need to use a custom script to do it.
