### ISSUE TITLE
Automatic import messes TV series

### ISSUE THREAD

**Issue by konradbjk** [Sonarr/Sonarr#6158]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Downloading one episiode each from Series A and Series B. During an import, the downloaded episode for Series B is imported into both Series A and Series B. So while trying to watch series A it plays me series B...

### Expected Behavior

When I download Series A, it imports the right episodes

### Steps To Reproduce

Download two series at the same time - the downloads are correct on the torrent client.

### Environment

```markdown
- OS: TrueNAS scale
```

### What branch are you running?

Main

### Trace Logs?

Too late

### Anything else?

Please repair this frickin import feature. It makes me furious for over a month. I already filed one issue, but it was autoclosed....

**Comment by konradbjk** [comment]
What is worse, I cannot just re-import the series. I need to SSH to the server where series are stored, manually remove the wrongly imported file and download it again. 

If I try to re-import via UI, it does nothing.

**Comment by augustuen** [comment]
Github isn't for support. Please join us on Discord and provide trace logs like you were asked in your previous issue.

**Comment by markus101** [comment]
Based on this and your previous issue it sounds like something is misconfigured in your setup and either something else is importing things or multiple downloads are pointed at the same path and Sonarr is unable to import things correctly (or something to that effect).

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) to troubleshoot this further, with Discord being the best place for it.

**Comment by konradbjk** [comment]
[log-import-episode.log](https://github.com/Sonarr/Sonarr/files/13317177/log-import-episode.log)
grab your logs 

there is some serious mess - primo it searches TV series I am not monitoring, secundo fetching series I do not even have added to sonarr

In the logs, I am trying to Interactively import s04E12. In the UI I can see 2 files, sample and the movie (1.7gb vs a couple of MB). Even though I have selected the 1.7gb file, it imports the sample

I do not care for support, I am rasing you a bug that you are too proud to even consider...you are a very toxic maintainers... @markus101 & @augustuen

**Comment by konradbjk** [comment]
The sonarr has been working for me for like 2y. Since recently it has stopped working

**Comment by konradbjk** [comment]
<img width="1271" alt="Screenshot 2023-11-10 at 09 31 11" src="https://github.com/Sonarr/Sonarr/assets/31480935/cd68a448-d036-40e1-a353-3a4c843de4f2">

After I remove manually the sample file from the import folder, and restart the interactive import, suddenly it recognizes the main file as a sample
