### ISSUE TITLE
Sonarr doesn't overwrite qbittorrents "seeding limits" action.

### ISSUE THREAD

**Issue by radry** [Sonarr/Sonarr#6159]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When sonarr is set to "remove completed" and a download is completed (and seeding limit set through sonarr is reached) sonarr will trigger what is set in qbittorrents "seeding limits" option. For example it will pause the torrent when this is set like that in qbittorrent.

### Expected Behavior

Sonarr should remove the torrent and delete the downloaded files, regardless of what options are set in qbittorrent.
Sonarr can overwrite the seeding limit and seeding time, so it should also overwrite the action that is taken once the limit is reached.

### Steps To Reproduce

1) Add qbittorrent in sonarr as downloader and set the option "remove completed"
2) In qbittorrent "seeding limits" choose any seeding ratio or time (will be overwritten by sonarrs settings) and choose "then: pause torrent"
3) trigger a download through sonarr  and wait for it to complete
 
Result: completed torrent will be paused instead of removed

### Environment

```markdown
- OS: Debian 10
- Sonarr: 4.0.0.682
```

### What branch are you running?

Develop

### Trace Logs?

2023-11-08 17:24:58.6|Debug|CompletedDownloadService|All episodes were imported for _redacted_
2023-11-08 17:24:58.6|Debug|DownloadEventHub|[_redacted_] Marking download as imported from qBittorrent

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Once the torrent is paused in qbit and the seeding goals that are set on the torrent are reached Sonarr will remove the torrent.

**Comment by radry** [comment]
This is not the issue here. When I set qbits "seeding limit" action to "remove torrent" it will remove the torrent but not delete the file!

Sonarr doesn't delete the file correctly!

> Once the torrent is paused in qbit and the seeding goals that are set on the torrent are reached Sonarr will remove the torrent.

That doesn't make ANY sense. Currently sonarr will trigger the "seeding limit" action from qbittorrent, if it's set to pause it will pause. The torrent/file is not deleted afterwards.

**Comment by stevietv** [comment]
Sonarr does this correctly, there is no bug here around this. If its not working in your setup please come to one of our support channels as indicated by Markus

**Comment by radry** [comment]
Maybe I didn't describe the problem clearly enough. If Hardlinks are NOT used, but instead the completed file is copied to the media folder by sonarr. It will not delete the original torrent/download files EVEN if it's completed (and seeding limit reached).

**Comment by stevietv** [comment]
Sonarr does do this, with hardlinks or copy enabled, Sonarr tells qBit to remove the torrent via the qBit API once the seeding goal is reached and PAUSE mode is entered. Sonarr itself doesn't delete the files, but instructs qBit to delete them. Our support channels are open for you to debug this further.

**Comment by bakerboy448** [comment]
> When I set qbits "seeding limit" action to "remove torrent" it will remove the torrent but not delete the file!

"It" in your statement is Qbit removing the torrent prior to Sonarr does/can.  Qbit being configured to remove torrents is not compatible with having Sonarr do the same and is not supported
