### ISSUE TITLE
No files found are eligible for import - mishandling of the scenario?

### ISSUE THREAD

**Issue by mbentley** [Sonarr/Sonarr#6160]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This seems similar to the request in #5754 but in this case, I think there may be a scenario that isn't being handled where it actually does make sense for it to be or at least I would have expected that it would be.

The situation that I am seeing is that with my Sonarr (version `3.0.10.1567` & SABnzbd (version `4.1.0`) setup, if a NZB is added and the download fails because the requested files are not found on my configured usenet server(s), SABnzbd is showing the release as: `Download failed - Not on your server(s) - https://sabnzbd.org/not-complete`

The thing is that in Sonarr, it is showing two entries on the queue for a given release:
* `Download failed`
   * `Download wasn't grabbed by sonarr, skipping`
* `Downloaded - Waiting to Import`
   * `No files found are eligible for import in /etc/sabnzbd/downloads/complete/TV/<TV show directory here>`

I understand the "download failed" message because it did fail.  I would expect that it would blocklist that and move on.  I am not sure if it is getting some sort of unexpected response from SABnzbd or what but it seems like there is some sort of unhandled scenario here that really should not need manual user intervention as I don't think a file not being on a server is exactly a corner case.  I'm not sure if the 2nd line item is what is preventing Sonarr from moving on and trying another release but that seems like it might be the case.

### Describe the solution you'd like

I would think that Sonarr would handle this scenario (or SABnzbd would report the scenario in a way that Sonarr expects).  Could very well be that something in SABnzbd changed response wise that's causing Sonarr to do something it did not use to do.

### Describe alternatives you've considered

Manually blocklist the releases - less than ideal.

**Comment by markus101** [comment]
This is more of a support issue than a feature request or bug. Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) to troubleshoot the issue further. Trace logs will definitely be required.

> The thing is that in Sonarr, it is showing two entries on the queue for a given release

Sonarr will show one queue entry for each down, in this case SAB must be reporting multiple entries.

> Download failed
Download wasn't grabbed by sonarr, skipping

Sonarr does not handle failed downloads for things it did not grab.
Either it didn't sent it to SAB or something on SAB's side caused the ID to change after it was added

> Downloaded - Waiting to Import
No files found are eligible for import in /etc/sabnzbd/downloads/complete/TV/<TV show directory here>

Does that folder actually exist, what's in it?

We do not have plans to treat downloads without a file as failed.
