### ISSUE TITLE
Sonarr Custom Search

### ISSUE THREAD

**Issue by crucio95** [Sonarr/Sonarr#6166]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes it would give better result to manually input a text for the research instead of having sonarr doing it automatically. This would allow user to use prowlarr to search on multiple indexers at once for a manual research instead of google the research or going through trackers one by one

### Describe the solution you'd like

Manual search textbox

### Describe alternatives you've considered

Google for torrents

**Comment by stevietv** [comment]
If you want to do it manually, search through Prowlarr and then assign the download to Sonarr's category in the DL client.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by alexs20** [comment]
Could you be more specific how to send the custom search result to Sonarr? There is not "Sonarr" downloading app in Prowlarr settings settings. There is only regular download clients that just grab the release.

And I also think that either adding custom search capability on Sonarr level or Allowing to add a custom alternative / alias Title is very useful for internationally language speaking users, where releases in torrent trackers have only localized names but Sonarr using names from TvDB as is and they are 99.99% using latin keyset. 
For example the sow - "Kesha dolzhen umeret" which will never find any release, while there are plenty of sources for correct name "Кеша должен умереть"
