### ISSUE TITLE
Remove/Replace ReturnUrl parameter Google Marks sites using ReturnUrl parameter as phishing sites. 

### ISSUE THREAD

**Issue by jjulicher** [Sonarr/Sonarr#6177]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I use nginx to reverse proxy my sonarr instance and I had google marking my site as a phishing site. 

However, whenever I went to sonarr.domain.me/login it would be fine but when I went to sonarr.domain.me it would redirect to sonarr.domain.me/login/?ReturnUrl=%2F. As soon as you do that it displays the infamous Deceptive site ahead phishing warning and prevents you from accessing the login page.  The actual problem is the %2F in combination with ReturnUrl (note it is case sensitive).

remove the ReturnUrl parameter as it's not needed? Or replace with returnUrl - allthough I suspect this will be flagged in the future. 

Not sure if this happens with non subdomain sites or .com sites. 

I registered with .me because it was a) cheap and b) looked good. 

### Expected Behavior

No deceptive site warning to be showed. 

### Steps To Reproduce

1. Setup a reverse proxy with a subdomain for sonarr. 
2. access the base subdomain. 
3. redirects to /login?ReturnUrl=%2F
4. Displays deceptive site. 

### Environment

```markdown
- OS: Ubuntu 23.04
- Sonarr: 3.0.10.1567
- Docker Install: No
- Using Reverse Proxy: Nginx
- Browser: Chrome latest
- Database: Built in?
```

### What branch are you running?

Main

### Trace Logs?

Not required

### Anything else?

No

**Comment by markus101** [comment]
Like Bogdan said, it's just a slash and plenty of other sites on the internet do the exact same thing and this shouldn't have any impact on Google's interpretation. Namecheap does this: https://www.namecheap.com/myaccount/login/?ReturnUrl=%2f

In theory someone could replace `%2F` with a different domain, but all that would do is redirect after logging the user in.

No plans to rewrite the login process to migrate away from this method at this time.

**Comment by jjulicher** [comment]
Sorry your point is? That's the properly formed URL. Google detects a redirect to '/ or %2F' as a phishing site.

**Comment by jjulicher** [comment]
Well you could just change the casing of the parameter - as returnUrl doesn't trigger this response from google.

**Comment by jjulicher** [comment]
Actually I see that you already have returnUrl in the code - any idea why ReturnUrl would be coming back?

**Comment by markus101** [comment]
Looks like it comes from ASP.net MVC itself, though we change the case if the login fails when redirecting the user back to the login screen.

Looks like we can override it by default as well, if google changes their mind and starts being case insensitive then so be it.
