### ISSUE TITLE
Issues Starting 4.0.0.720

### ISSUE THREAD

**Issue by abs3ntdev** [Sonarr/Sonarr#6178]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

sonarr unable to start

https://pastebin.com/JsMdU6n3

### Expected Behavior

sonarr starts without error

### Steps To Reproduce

1. running current develop version of sonarr
2. start sonarr

### Environment

```markdown
- OS: Unraid
- Sonarr: develop
- Docker Install: yes 
- Using Reverse Proxy: yes
- Browser: all
- Database: postgresql14
```

### What branch are you running?

Develop

### Trace Logs?

https://pastebin.com/JsMdU6n3 

### Anything else?

#6150 seems to be where the issue was introduced

**Comment by abs3ntdev** [comment]
https://pastebin.com/LktydpS9

i get a similar error and sonarr is still unable to start even with no config.xml

**Comment by abs3ntdev** [comment]
after testing more everything up to 4.0.0.719 works this behavior was introduced in 4.0.0.720

**Comment by bakerboy448** [comment]
> https://pastebin.com/LktydpS9
> 
> i get a similar error and sonarr is still unable to start even with no config.xml

So empty /config mount and thus would be sqllite and it still won't start?

**Comment by abs3ntdev** [comment]
i deleted my config.xml to test and i got the logs you are replying to. i can try with changing my /config mount so its entirely empty and try again.

**Comment by abs3ntdev** [comment]
just changed my /config mount to /mnt/user/appdata/sonarrTESTING which is a completely empty directory and got the same error logs as here 


> https://pastebin.com/LktydpS9
> 
> i get a similar error and sonarr is still unable to start even with no config.xml

**Comment by markus101** [comment]
On Discord you mentioned 4.0.0.719 was working correctly, which means the issue would lie with the ffprobe bump in .720, is this correct?

Which docker image are you using?
I'm using .720 with linuxserver and not seeing any issues.

**Comment by abs3ntdev** [comment]
that is correct. I am currently running lscr.io/linuxserver/sonarr:develop-version-4.0.0.719 without issue. lscr.io/linuxserver/sonarr:develop-version-4.0.0.720 gives me the error logs i reported.

**Comment by markus101** [comment]
The .720 release didn't contain anything that should have caused this to fail (it's just a one line change to a dependency that has nothing to do with configuration).

Are you still seeing this issue with 4.0.0.731 or later?
Did you try with a completely empty `/config` directory?
What environment variables do you have configured with that container?

**Comment by abs3ntdev** [comment]
this ended up being a local issue unrelated to the changes in 720. my image was corrupting when downloading due to hardware issues of my own. after fixing my issues I don't have the reported problems anymore so closing.
