### ISSUE TITLE
Auto-update path for new title or release year

### ISSUE THREAD

**Issue by ilike2burnthing** [Sonarr/Sonarr#6179]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Having to manually update the path for a series if the title or release year changes after adding it to Sonarr. Requires user to be aware this has happened and then manually change it.

### Describe the solution you'd like

When a default path is used for an unreleased series,
e.g. `/media/TV/Title - Original Subtitle (2024)`,
but the title or release year changes, this should auto-update the path as well,
e.g. `/media/TV/Title - New Subtitle (2025)`.

This could also be disabled for those who don't want this behaviour.

### Describe alternatives you've considered

Add a `reset to default` button for the path field which would update the path with the new title and/or release year. Still manual, but less effort on the part of the user.

**Comment by markus101** [comment]
Going to bundle this up under https://github.com/Sonarr/Sonarr/issues/1118
