### ISSUE TITLE
Sonarr importing samples

### ISSUE THREAD

**Issue by 2fst4u** [Sonarr/Sonarr#6180]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr version  4.0.0.720 is importing sample files which contain "sample" in both the directory they are in and the filename itself. All files this has happened to are also sub 90 seconds.

In the trace log it starts around line 837

### Expected Behavior

Ignore sample files.

### Steps To Reproduce

Not really sure what to put here, a download containing a sample was grabbed and it automatically imported without intervention.

### Environment

```markdown
- OS: Ubuntu host
- Sonarr:  4.0.0.720
- Docker Install: yes
- Using Reverse Proxy: 
- Browser: 
- Database: sqlite
```

### What branch are you running?

Develop

### Trace Logs?

https://pastebin.com/6UsPu7tB

**Comment by bakerboy448** [comment]
> All files this has happened to are also sub 90 seconds.

Logs / sonarr / ffprobe disagree `2023-11-15 19:12:55.2|Debug|DetectSample|Runtime is over 90 seconds`

**Comment by markus101** [comment]
Which docker image are you using?

I've looked at this release under both Windows and docker (linuxserver) and the sample file is correctly being detected as a sample file and it's not imported.

**Comment by markus101** [comment]
What ffprobe output do you get for that sample file?

This is the output from the sample file I got:

```
ffprobe version 5.1.4 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 9.3-win32 (GCC) 20200320
  configuration: --prefix=/ffmpeg/build --bindir=/ffmpeg/bin --logfile=/ffmpeg/bin/log.txt --disable-autodetect --disable-iconv --enable-libdav1d --disable-programs --enable-ffprobe --disable-avdevice --disable-swresample --disable-swscale --disable-postproc --disable-avfilter --disable-network --disable-everything --enable-protocol=file --enable-demuxers --enable-parsers --enable-decoders --enable-bsf=av1_frame_split --enable-bsf=av1_frame_merge --enable-bsf=av1_metadata --enable-cross-compile --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-ldexeflags=-static --extra-libs='-lpthread -lm'
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
Input #0, matroska,webm, from 'brawn.the.impossible.formula.1.story.s01e01.1080p.web.h264-ethel.sample.mkv':
  Metadata:
    encoder         : libebml v1.4.4 + libmatroska v1.7.1
  Duration: 00:00:59.28, start: 0.000000, bitrate: 6008 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      BPS             : 5924617
      DURATION        : 00:00:57.600000000
      NUMBER_OF_FRAMES: 1440
      NUMBER_OF_BYTES : 42657246
      _STATISTICS_WRITING_APP: mkvmerge v74.0.0 ('You Oughta Know') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 256 kb/s (default)
    Metadata:
      BPS             : 256000
      DURATION        : 00:00:57.600000000
      NUMBER_OF_FRAMES: 1800
      NUMBER_OF_BYTES : 1843200
      _STATISTICS_WRITING_APP: mkvmerge v74.0.0 ('You Oughta Know') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: subrip
    Metadata:
      title           : English
      BPS             : 97
      DURATION        : 00:00:58.480000000
      NUMBER_OF_FRAMES: 16
      NUMBER_OF_BYTES : 714
      _STATISTICS_WRITING_APP: mkvmerge v74.0.0 ('You Oughta Know') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

**Comment by 2fst4u** [comment]
> Which docker image are you using?
> 
> I've looked at this release under both Windows and docker (linuxserver) and the sample file is correctly being detected as a sample file and it's not imported.

Linux server.

What should I run to check ffprobe? That duration is correct for the file it imported, not even 60 seconds.

**Comment by 2fst4u** [comment]
> > All files this has happened to are also sub 90 seconds.
> 
> Logs / sonarr / ffprobe disagree `2023-11-15 19:12:55.2|Debug|DetectSample|Runtime is over 90 seconds`

Unhelpful.

**Comment by bakerboy448** [comment]
`docker exec -it sonarr /app/bin/ffprobe <filename>`

**Comment by markus101** [comment]
Baker's PR probably addresses this because the `90 seconds` was hardcoded, but the actual sample detection is based on the run time of the series, which is now 58 minutes, but if it was less than 3 minutes yesterday before all the episodes air the minimum runtime would be only 15 seconds.

**Comment by 2fst4u** [comment]
Could be, there were very few details about the episodes before the release downloaded so I wouldn't be surprised if the runtime was wrong. It also happened on .719 so reverting didn't help.

So just to clarify does that mean a fix is coming in the next update?

**Comment by markus101** [comment]
A change to the logging is coming in a future update, which will at least give accurate information to debug it further, but assuming your instance already refreshed the series and the runtime is now 58 minutes then it's "fixed".

**Comment by 2fst4u** [comment]
Shouldn't the "sample" in the directory and file name both have prevented this too though?

**Comment by markus101** [comment]
No, the only thing that matters is the run time.

**Comment by 2fst4u** [comment]
Any reason why? Surely that's a simple first check.

**Comment by markus101** [comment]
Because it's a fairly common word and leads to false positives.

**Comment by konradbjk** [comment]
Not some new issuee
- https://github.com/Sonarr/Sonarr/issues/6094
- https://github.com/Sonarr/Sonarr/issues/6158

**Comment by bakerboy448** [comment]
> Not some new issue, the team keeps on ignoring it
> 
> * [Sonarr keeps on importing SAMPLE instead of main files #6094](https://github.com/Sonarr/Sonarr/issues/6094)
> * [Automatic import messes TV series #6158](https://github.com/Sonarr/Sonarr/issues/6158)

No one is ignoring anything. You're on a version that's getting no updates, call everyone toxic, and actively refuse/fail to provide valid bug reports by failing to provide any trace logs as required and asked for.
