### ISSUE TITLE
Req: Add a trigger for New Series Creation to run before the series is created

### ISSUE THREAD

**Issue by Halfwalker** [Sonarr/Sonarr#6182]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No problem, just ease of functionality

### Describe the solution you'd like

I use a ZFS dataset for my various media, currently a single TV dataset.  I want to transition to a dataset-per-show model for more granularity.

Right now the list of triggers https://wiki.servarr.com/sonarr/settings#connections does not have one for when a New Series is created.  Ideally, that trigger would be available _before_ anything is done to the disk - ie. to be able to pre-create the zfs dataset for the show.

In conjunction with this, a "safe naming" version of the Series would be nice, but not critical (can be done in the script to create the dataset).  This would be a safe/valid name to serve as the series dataset name and directory name.  Replace spaces/apostrophes/etc with underscore for example.  ZFS in particular can use any alphanumeric plus hyphen (-), colon (:), period (.) and underscore (_) in the dataset name.

Although, if not providing a "safe naming" for the directory, it would need a way to pass back a generated one to use.  For example, `DC's Legends of Tomorrow` might come back as `DCs_Legends_of_Tomorrow`.  Since the script won't be executed until the user clicks **Add** there needs to be a way to let Sonarr know what directory to store the new series in.

Probably easier just to provide a _series_name_ and _series_name_clean_ variable to the script ...

### Describe alternatives you've considered

Right now a manual process works, but it's manual and ugly.  Before creating a new series, I manually create the dataset for it.  Then in the New Series dialog I manually select the new dataset directory.

Perhaps this doesn't need to be a trigger for connections per-se ?  It could be a checkbox in that dialog to run/not-run a pre-create script.

### Anything else?

I run Sonarr as a docker container as most probably do.  I'm not sure what the execution context of the script would be ...  If running within the container, then it would need access to the zfs binaries and libraries - at least in my specific zfs dataset case.  Probably also for most cases though.

**Comment by markus101** [comment]
The v4 beta already has a `On Series Add` that triggers _after_ the series is added, there is no script that triggers before the series is added to Sonarr because it would lack most information about the series.

No plans to add a script that triggers before adding the series and allows information to be changed, if something like that is necessary for your work flow you'd need to use Sonarr's API to add the series with the necessary information set.

**Comment by Halfwalker** [comment]
I suppose it doesn't need to be _before_ the series is added, just before anything is done to the target disk location ...  It's literally going to be 
```
zfs create -o mountpoint=/media/TV/series_name  tank/series_name_cleaned
chown user.user /media/TV/series_name
```
where `series_name` and `series_name_cleaned` are variables passed to the script (along with any others available)

Reading more about the triggers, it doesn't really seem a **Connection** type trigger is best applicable.  Feels like a checkbox in the New Series dialog would do it "Run Pre-create script" which would be configured elsewhere in Settings.

Anyway, hopefully something for the roadmap.

**Comment by bakerboy448** [comment]
Nothing on the roadmap for that. Sounds like you need to write a script that handles the add series connect event, creates the dataset, and then updates the series assigned path in sonarr using the api
