### ISSUE TITLE
Support reflinks on zfs 2.2.0+

### ISSUE THREAD

**Issue by fryfrog** [Sonarr/Sonarr#6183]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Of course hard links are the best links. But they do have one vulnerability, if you modify any "copy" it modifies *all* copies. This will cause a torrent to fail its hash check, for example.

### Describe the solution you'd like

> Block cloning (https://github.com/openzfs/zfs/pull/13392) - Block cloning is a facility that allows a file (or parts of a file) to be "cloned", that is, a shallow copy made where the existing data blocks are referenced rather than copied. Later modifications to the data will cause a copy of the data block to be taken and that copy modified. This facility is used to implement "reflinks" or "file-level copy-on-write". Many common file copying programs, including newer versions of /bin/cp on Linux, will try to create clones automatically.

- [zfs-2.2.0](https://github.com/openzfs/zfs/releases/tag/zfs-2.2.0)

We already support reflinks on btrfs, lets add zfs?

This is what seems to do it, mainly limited to linux.
https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Mono/Disk/RefLinkCreator.cs#L15

This is what limits it to btrfs.
https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Common/Disk/DiskTransferService.cs#L347

The tricky part would be limiting it to zfs will have a lot of failures since 2.2.0 is new. But maybe we could spew something like "need to use 2.2.0+ for reflinks" or maybe reflinks could be a toggle paired w/ hard links?

### Describe alternatives you've considered

I could use btrfs, but I'd rather not lose my data! ;)

**Comment by markus101** [comment]
Closing in favour of the existing issue: https://github.com/Sonarr/Sonarr/issues/5470
