### ISSUE TITLE
Update UI after POST requests (/api/command)?

### ISSUE THREAD

**Issue by rfgamaral** [Sonarr/Sonarr#619]
Although I miss a couple of things from SickRage (subtitles for instance) I'm really digging Sonarr. I understand it has a somewhat different philosophy than SickRage (no backlog searches) but the simplicity and the UI are much better.

However, I really dislike the fact that the UI does not react to the response of the POST actions (the ones I noticed were all calling `/api/command`).

For instance, the following actions do not update the UI:

 - "Update series info and scan disk" (arrows icon keep spinning indefinitely).
 - "RSS Sync" / "Update Library" (spinner keeps spinning indefinitely).
 - "Clear Logs" / "Clear Log Files" (spinner keeps spinning indefinitely).

These are just a few examples... For the UI to update, a full page refresh is needed. This is not a good user experience. It would be nice if the UI could react to those actions and just stop the icons spinning (and enable the buttons again) and really update the UI whenever necessary (for instance, the log table or the series data should be changed without a full page refresh).

I understand that this is very low priority but nice to have, none the less. Just a thought.

P.S: Hopefully this is not some bad configuration on my end, ahahah :)

**Comment by thezoggy** [comment]
i do not see the scenarios you experience...  you have really low cpu? locked down browser blocking local js/ajax updates? reverse proxy wrongly setup?

**Comment by markus101** [comment]
The UI definitely responds to these changes. I've only heard of this happening when running under mono and mostly on FreeBSD/FreeNAS. There are a few forums on our support forums about it, you can verify its the same issue by checking if connections to signalR are returning 500 response codes.

https://forums.sonarr.tv/t/signalr-problem/5785

Please open a thread on the forums if you have any other issues.

**Comment by rfgamaral** [comment]
It was the same issue as pointed on this [thread](https://forums.sonarr.tv/t/gui-update-issues/4195).

I just want to leave this here in case someone comes looking for this issue here on GitHub.

By default, the environment variable `XDG_CONFIG_HOME` is equal to `$HOME/.config` (if it's not set or empty). And `$HOME` will be relative to the user account running Sonarr.

Basically, that directory needs to exist and be writable by the same user account.
