### ISSUE TITLE
Add "Import per Script" support

### ISSUE THREAD

**Issue by YoSiJo** [Sonarr/Sonarr#6198]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have the possibility to use reflinks with btrfs via nfsv4.
Later I would also like to implement this with bcachefs, but currently there is only the hardlink or move option.
To be really sure that reflinks are used, I would like to use a script like radarr.

### Describe the solution you'd like

Radarr already has an "Import by script" option, which would be suitable for me here if it were also available in Sonarr.

### Describe alternatives you've considered

Further support if reflinks FSes in Sonarr, with corresponding option to select this.

**Comment by Qstick** [comment]
It was in Sonarr first

**Comment by YoSiJo** [comment]
I am sorry if I have generated spam here.
However, I cannot see from the current documentation that storing a "Custom Script" under "Connection" replaces the import process.
This is more intuitive with Radarr.
It seems to me as if this would run in addition to the import process, is this a misunderstanding?

**Comment by augustuen** [comment]
No, you're correct that using the Custom script would run in addition to Sonarr's import process.

The option you're looking for is in Settings -> Media Management -> Importing -> Import using script. If it's not there you either need to enable "Show advanced settings" or upgrade to V4.

**Comment by YoSiJo** [comment]
Many thanks for the information, the fact that this is only the case from version V4 onwards was the decisive hint.
