### ISSUE TITLE
Make the log location chanable via the config.xml file

### ISSUE THREAD

**Issue by iio7** [Sonarr/Sonarr#6200]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The logs goes into the default installation directory where the binary files resides. On my setup that has limited space.

### Describe the solution you'd like

Log file location needs to be configurable from within config.xml

### Describe alternatives you've considered

I could not find anything.

**Comment by markus101** [comment]
No plans to make to log file configurable independent of the "AppData" directory, but you can use `--data` to configure the location of the of that directory in general. The `MediaCover` directory will generally exceed the size of the logs files which cap out around 150MB with debug/trace enabled.

**Comment by iio7** [comment]
> No plans to make to log file configurable independent of the "AppData" directory, but you can use `--data` to configure the location of the of that directory in general. The `MediaCover` directory will generally exceed the size of the logs files which cap out around 150MB with debug/trace enabled.

Where exactly is that documented? I cannot find anything about an `--data` option.

**Comment by iio7** [comment]
Hmm. I guess making the log directory not-writeable would be another solution until the logs are actually needed.

**Comment by stevietv** [comment]
or potentially just symlink the logs folder to a different location

**Comment by iio7** [comment]
Where is `--data` documented? I can't find it.

**Comment by markus101** [comment]
Mistake on my part, it's `-data=`, not `--data`, but it's on the wiki.

https://wiki.servarr.com/en/sonarr/appdata-directory
