### ISSUE TITLE
Add 576p Bluray Resolution

### ISSUE THREAD

**Issue by zakkarry** [Sonarr/Sonarr#6203]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

https://github.com/Sonarr/Sonarr/blob/c7824bb593291634bf14a5f7aa689666969b03bf/src/NzbDrone.Core/Parser/QualityParser.cs#L150-L155

This causes 576p to incorrectly parse, not as 576p but 480p instead.

This also applies to 360p and 540p but those are admittedly much less common than 576 would be.

### Describe the solution you'd like

Correctly identify 576p

### Describe alternatives you've considered

.

**Comment by markus101** [comment]
This will need to be a new separate quality, for existing profiles it'll be added, but not enabled. For the default profiles it should be enabled in Any/SD profiles.

**Comment by Voyex** [comment]
I'm currently working on this and I will put in a PR once I have finished testing.

**Comment by zakkarry** [comment]
@Voyex have you abandoned this?

**Comment by Voyex** [comment]
> @Voyex have you abandoned this?

Yes, due to hardware issues, I was unable to get my dev environment setup in a stable manner so I am unable to do any more work on this.

**Comment by zakkarry** [comment]
@thezak48 will be so happy @markus101, I know you said he was pressuring you since he had very limited space.

All kidding aside, thanks.

**Comment by paigomez90** [comment]
hi i'm having an issue where the new 576p quality is not showing up in my current profiles. it only shows in new profiles.

**Comment by zakkarry** [comment]
I see it in my already made profiles, just as a note.

**Comment by markus101** [comment]
Please show a screenshot of an existing profile where it wasn't added.

**Comment by paigomez90** [comment]
@markus101 
![image_2024-09-16_161350809](https://github.com/user-attachments/assets/887ec233-0d5c-467b-a43f-4790d898e813)

**Comment by paigomez90** [comment]
@markus101 this is after trying to save.
![Screenshot 2024-09-16 161432](https://github.com/user-attachments/assets/d7a54ae1-e43a-425c-bc52-be11ee5ef9b5)
