### ISSUE TITLE
The language is Chinese when searching and Korean when importing

### ISSUE THREAD

**Issue by PN62323424** [Sonarr/Sonarr#6206]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

This is the language displayed when searching: Chinese
![截屏_-_11月24日_上午1_40](https://github.com/Sonarr/Sonarr/assets/83660264/75a2925f-bdba-44ee-b172-2e797f5c0691)
This is the language displayed when importing: Korean.
![截屏_-_11月24日_上午1_39](https://github.com/Sonarr/Sonarr/assets/83660264/7634cad0-36c2-435c-b05d-95973c05126a)

Why the language displayed when importing is different from the language displayed when searching, because I set the Chinese language to have an extra 1600 points, resulting in the import score to be 1600 points lower, and then lead to import failure.

### Expected Behavior

none

### Steps To Reproduce

none

### Environment

```markdown
- OS: synology
- Sonarr: V4
- Docker Install: yes
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

if needed

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

The release name says it's Chinese, but importing also uses language information from the video file, which indicates it's Korean.

**Comment by PN62323424** [comment]
I don't quite understand what you mean.

I understand that the release name says it's Chinese, but at the same time the language field in the search results also shows the language as Chinese, how does sonarr determine the language type when searching, based on the release name?

If sonarr determines the language based on the release name, and the search determines the language based on the release name, this will lead to a lot of import failures!

This issue is essentially the same as the one in this link, and will lead to score conflicts:
https://github.com/Sonarr/Sonarr/issues/6112
https://github.com/Sonarr/Sonarr/issues/5598

**Comment by PN62323424** [comment]
Another thing that doesn't make sense is that I set the release name to include [chinese] to have a score, and even though the language detects that it's actually Korean, why does it go against the custom formatting score I set and remove the score for the release name to include [chinese]?

**Comment by thezoggy** [comment]
Because the lang in release name is assumed spoken/audio lang. But when importing it's looking at file metadata and sees it's Korean
 So release badly says Chinese (as maybe they were trying to say it has Chinese subs) which in the end is just bad naming. But all of this and more can be checked if you use sonarr support options as noted above, GitHub is not for user support.
