### ISSUE TITLE
Advanced Transcoding Integration for Plex Library Management with Emphasis on AV1 Format

### ISSUE THREAD

**Issue by martinkeat** [Sonarr/Sonarr#6207]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Annoyance of things being moved prior to transcoding

#### **Summary**
This proposal introduces enhancements for Tdarr, Radarr, and Sonarr, aimed at improving integration and management of media files for Plex, with a special focus on the transcoding process and efficient library updates. The adoption of the AV1 format by Plex serves as a primary trigger for this proposal.

---

#### **Detailed Features**

**On Tdarr's Side:**

1. **Source Directory Enhancement:**
   - Implement an option under the "source" directory in Tdarr's interface.
   - Indicate the inclusion of a Plex 'tbp/' folder and a '.plexignore' file.
   - Set `/[root folder]/` as the source, with Tdarr processing files in `/[root_folder]/tbp`, and moving them to `/[root folder]/` after transcoding.

2. **AV1 Plugin Addition:**
   - Introduce a specific AV1 plugin to Tdarr, simplifying the transcoding process for users and embracing the latest video encoding standards.

---

**On Radarr/Sonarr's Side:**

3. **New 'Transcoding' Tab in Settings:**
   - Add a "Transcoding" tab within the Settings menu of Radarr and Sonarr, focusing on streamlined transcoding workflows.

4. **Transcoding Settings Page Enhancements:**
   - Feature a tickbox for creating a 'tbp' folder and a '.plexignore' file in the root directory.
   - Facilitate the handling of files destined for transcoding and protect against misclassification by Radarr and Sonarr.

5. **Integrated Workflow and Automation:**
   - Configure Radarr and Sonarr to recognize `/[root folder]/tbp` as a temporary storage for files awaiting Tdarr transcoding.
   - Ensure these systems update their libraries to reflect file presence in both directories, and automate Plex library updates post-transcoding.

---

#### **Collaboration and Flexibility:**

- The enhancements proposed can be independently implemented by Tdarr, Radarr, or Sonarr. 
- Even if only one party adopts these changes, the new setup will still offer benefits and can be utilized effectively.
- However, as part of a collaborative community, synchronized adoption would greatly enhance user experience and operational efficiency.

#### **Benefits:**
- Provides a more streamlined process for managing and transcoding media files, especially with the AV1 format.
- Reduces manual intervention and error in media file handling.
- Enhances user experience through a unified, automated workflow.

#### **Suggested Implementation Timeline:**
- Development and beta testing over 3-6 months.
- Full deployment and integration within 6-12 months, subject to feedback and testing results.

---

### Describe alternatives you've considered

Many, but this is the simplest for everyone

### Anything else?

nope

**Comment by markus101** [comment]
> Feature a tickbox for creating a 'tbp' folder and a '.plexignore' file in the root directory.

What is `tbp`?
Why does this need to be something Sonarr handles?

> Facilitate the handling of files destined for transcoding and protect against misclassification by Radarr and Sonarr.

What do you mean by this?
How is Sonarr supposed to know what you want transcoded?
How would Sonarr protect against misclassification?

> Configure Radarr and Sonarr to recognize /[root folder]/tbp as a temporary storage for files awaiting Tdarr transcoding.

You could already achieve this with Remote Path Mappings, but we have no plans to re-introduce what would effectively be `Drone Factory` (importing random files from a folder on a schedule, but you can use the API to achieve that).

> Ensure these systems update their libraries to reflect file presence in both directories, and automate Plex library updates post-transcoding.

We have no plans to support files in two different directories being treated as downloaded and available.

What we've suggested in the past is using Remote Path Mapping to remap the path that Sonarr sees for completed downloads to a different directory, by doing this you can have a script run after a download completes (up to your download client to trigger) to either transcode or hard link and then Sonarr can import from there. Using a `On Download` Custom Script in Sonarr you can clean up the files as needed after importing.

You may also be able to use `Import Using Script` available in the v4 beta to better handle transcoding, but managing transcoding or more tightly integrating into the transcoding process is not something we intend to do at this time.

**Comment by markus101** [comment]
We've discussed this a bit more and it's not something we're going to implement beyond what we've already implemented.
