### ISSUE TITLE
[Feature] Minimum seeders

### ISSUE THREAD

**Issue by d2dyno** [Sonarr/Sonarr#621]
Hello,

Unless I'm blind, I cannot find a way to only allow torrents with x amount of seeders to be downloaded. If this is not already a feature, would it be possible to add it? I know just today, torrents with 1/0 seeders were being added instead of ones with 24/5 seeders. I was forced to manually correct this.

Anyways, let me know :)

**Comment by markus101** [comment]
We don't plan to expose a configurable minimum, but do plan to make the selection within the same quality smarter, assuming these are the same quality.

**Comment by vinchi007** [comment]
Please expose "min seed" option so that users can change it at will. There are so many older backlog series that have few seeds - current automatic select does not pick the highest seed count.

**Comment by meffect** [comment]
i get lots of 0 seeder torrents

**Comment by Kyrluckechuck** [comment]
Completely agreeing with this -- it's needed. There are far too many shows that keep getting put into my queue with 0-2 seeders where if it's more than 0, they usually flake out before I even have 1% of it done.. 

I keep needing to remove them manually and go find them since I can't know from the WebUI if it's a decently seeded file

**Comment by meffect** [comment]
I think issue still cause what happens is my torrent client is behind blocklists. my pvr software may or may not be behind the same blocklists depending. so while the pvr software thinks it's being smart, it doesn't know that their may be 4 out of 5 seeds getting blocked from my blocklists. likewise, the person on the other end may be blocking me. i'm sure their's various other conditions that cause the tracker reported seeds to not be accurate. just adding a pov maybe not considered yet.

it would be nice to set a minimum so I can add my own educated buffer of seeds I think I wont be able to connect with. even nicer would be sonarr evaluating torrent state through acquisition process and making decisions.

**Comment by donisewell** [comment]
Would love a configurable minimum. On private trackers I don't really need to worry about it having 0 seeders. All this is currently doing for me is making me "late" to torrents and cutting the amount of time I could have been seeding to others.

**Comment by cmgraz** [comment]
Is there a reason that this isn't exposed?  Without it, I'm forced to go through and do quite a few things manually, especially for older seasons.

What if I'm looking at a show that has 1 seeder at 720p, but 30 seeders at 480p?  I'd prefer to take the lower quality than have something sit in Deluge and not actually download.

What's the negative recourse for exposing some sort of parameter that allows a user to select minimum # of seeders?

**Comment by meffect** [comment]
any response from dev's?

**Comment by wdaniel526** [comment]
Please add this feature, Sonarr keeps fetching dead torrents, it's hard to clean up and manage. Most indexers announce 1 seeder when there really aren't any on torrents.

**Comment by geek2009** [comment]
So many dead torrents. A 100% must have feature!

**Comment by dareeude** [comment]
This is still a huge issue. Please revisit it if at all possible!

**Comment by llbranco** [comment]
radarr have this option exposed, and if radarr is fork of sonarr, so sonarr can have it too.
thank u devs, I cant imagine my life w/o sonarr anymore

**Comment by lundgrenolof** [comment]
Yes, please add this option...
