### ISSUE TITLE
Scheduled Task should have their own queue/thread

### ISSUE THREAD

**Issue by nexus671** [Sonarr/Sonarr#6211]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently if you manually add things to the task queue it will get full, and the scheduled task will not start until it's their turn. Now if a lot of downloads have completed the refresh monitored downloads will not start until all searches etc. have completed. Even though their are downloads ready to import but now searches are clogging queue. 

### Describe the solution you'd like

Add a separate queue for scheduled tasks.

### Describe alternatives you've considered

none.

**Comment by markus101** [comment]
All tasks share a common thread pool, this allows Sonarr to correctly deduplicate and schedule tasks that affect other tasks correctly. There is a task priority system and refreshing monitored downloads already get queued at a higher priority (high) than a search queued by the user (normal). Processing of completed downloads is also a high priority task.
