### ISSUE TITLE
Add content layout parameter in qbittorrent settings on torrent addition 

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#6213]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Many of the private trackers I use don't use folders for single episode torrents. This results in all the files to be saved in the download folder. And then when sonarr imports those episodes if the folder has subtitles of other show they are imported as well. Qbittorrent has a setting where a folder can be added for a torrent without folders when the torrent is added. This can be done globally or per torrent. I prefer to keep this setting for only torrent sent by sonarr as they are single episode torrent that will be deleted anyway once the show is batched. But for other torrents can follow the original file structure. I need it this way as the private trackers I use also provide subtitles which I auto download in to the download folder automatically. 

### Describe the solution you'd like

The solution I would like is for sonarr to give the option in advance settings for give better control to the user. I asked about it in discord but one of the mods said this setting was not available through the web api but it seems to be availble looking at the latest api document 
https://qbittorrent-api.readthedocs.io/en/latest/apidoc/torrents.html

### Describe alternatives you've considered

I have considered enabling set subfolder option globally in qbittorrent but I think that is not the optimal way to do it the optimal way should always be make it available to user through the settings

**Comment by markus101** [comment]
Not sure which mod you spoke to, but based on Qbit's API docs, they are correct, it is not part of the official API documents: https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1).

The python client docs help to support it's possible, but are not accurate to the format the API actually requires.

**Comment by Dnkhatri** [comment]
thanks

**Comment by markus101** [comment]
Not sure why you closed the issue.

**Comment by Dnkhatri** [comment]
> Not sure why you closed the issue.

I thought your pull request solved it but it still has not gone into the development build
