### ISSUE TITLE
Ability to change "Authentication Required"

### ISSUE THREAD

**Issue by anuradhaedirisuriya** [Sonarr/Sonarr#6214]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, there is no option to disable forced authentication. 

### Describe the solution you'd like

I'd like to request the ability to disable authentication for local addresses

### Describe alternatives you've considered

I have seen this feature in both Radarr and Prowlarr

![image](https://github.com/Sonarr/Sonarr/assets/7523370/adf864ae-243e-4be5-aab2-b55c41eb18c7)

### Anything else?

No

**Comment by markus101** [comment]
This option already exists in the v4 beta.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/sonarr/faq-v4#forced-authentication

**Comment by gardner** [comment]
Something like this might help:

```
cp sonarr/config/config.xml sonarr/config/config.bak
docker compose stop sonarr
sed -i 's/AuthenticationMethod>None/AuthenticationMethod>External/' radarr/config/config.xml 
sed -i '/AuthenticationRequired/d' sonarr/config/config.xml
docker compose restart sonarr
```
