### ISSUE TITLE
show update fail

### ISSUE THREAD

**Issue by nodiaque** [Sonarr/Sonarr#6217]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I click on "refresh & scan", it end with an error

### Expected Behavior

No error

### Steps To Reproduce

Select a show, click on "refresh & scans"

### Environment

```markdown
- OS: Unraid 6.12.4
- Sonarr: 3.0.10.1567
- Docker Install: Yes - binhex/arch-sonarr
- Using Reverse Proxy: No
- Browser: All (edge, firefox, chrome)
- Database: I don't know
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/13467178/sonarr.trace.txt)

### Anything else?

Looking at the log, it fail to resolve skyhook.sonarr.tv. I opened a shell on this docker and radarr (both have the same problem) and they both fail to resolve it. I tried resolving other website like google and such and they all work. I tried with other docker on the same network and they all resolve it. I've looked at resolve.rc file and they all have the same configuration so I really don't understand what's going on.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
