### ISSUE TITLE
Please add RSS List as an option for Import Lists

### ISSUE THREAD

**Issue by GodKratos** [Sonarr/Sonarr#6221]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sonarr has the ability to add a Plex Watchlist as an Import List but this is limited in what it can do, it cannot be connected to a secondary user within a plex account and it stops working periodically requiring the plex account to be reauthenticated. These issues can be avoided by using the watchlist RSS feed which works very well in Radarr but unfortunately Sonarr does not have an RSS List import option.

### Describe the solution you'd like

The ability to add an RSS List to Sonarr as an Import List the same way that Radarr allows it (there are many other import lists options in radarr as well but RSS is a very important one)

### Describe alternatives you've considered

The only alternatives are using the existing import list options but they do not cover the required scenarios.

**Comment by markus101** [comment]
This is already implemented in the v4 beta.
