### ISSUE TITLE
Runtime is Blank for Episodes on Series Details

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#6223]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Title; See screenshots

![image](https://github.com/Sonarr/Sonarr/assets/55419169/49a4b6b6-236e-432c-99c9-ea9f9a10008f)
![image](https://github.com/Sonarr/Sonarr/assets/55419169/5db237c4-5ec4-438d-9b90-657b7dcc991b)
![image](https://github.com/Sonarr/Sonarr/assets/55419169/32527016-01ee-463a-a1e6-a3453485058a)

### Expected Behavior

Show Runtime in series details

### Steps To Reproduce

N/A - UI

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.0.733
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome Version 119.0.6045.199 (Official Build) (64-bit)
- Database: Postgresql 14.10
```

### What branch are you running?

Main

### Trace Logs?

N/A - UI

### Anything else?

N/A - UI

**Comment by PearsonFlyer** [comment]
(also, you're not on Main) :)

**Comment by bakerboy448** [comment]
Should we consider adding File Runtime to match the other file properties available and renaming run time to episode runtime for clarity or similar?
