### ISSUE TITLE
When sorting by Next Airing show Continuing shows before the Ended shows

### ISSUE THREAD

**Issue by daniel-sousa-me** [Sonarr/Sonarr#6228]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When sorting by Next Airing most shows don't have a date and are sorted alphabetically.

Since we can't add a secondary sort, could we at least have the Continuing shows before the Ended shows?

### Describe the solution you'd like

When sorting by Next Airing show Continuing shows before the Ended shows

### Describe alternatives you've considered

Ideally, we could choose other columns to sort by in case of a tie, but that seems hard to implement in the UI.

The fallback sort could also be by previous airing, but I don't think there would be a consensus about that, and I can see different people preferring that to go in either direction.

**Comment by markus101** [comment]
If you're primarily concerned about airing shows why not filter to only show shows that haven't ended?

**Comment by daniel-sousa-me** [comment]
Because I may also want to see those, but not as much.

This way I can have all of them in my home, but the current ones are on top

**Comment by markus101** [comment]
We've discussed this, but it's not something we're going to change at this time.
