### ISSUE TITLE
Modify the "Series Monitors" to monitor episodes for ended shows as well

### ISSUE THREAD

**Issue by jmsprsns** [Sonarr/Sonarr#6237]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Yes, Monitoring the latest season won't monitor episodes under that season if the show is ended. 

### Describe the solution you'd like

Modify the "Only First Season" and "Only Latest Season" Monitor options to automatically monitor/download all episodes within that season, whether the show is ended or not.

Alternatively, creating new options for this would also suffice. But I think modifying this functionality would be best - when I select to monitor "Only Latest Season" on an ended show, it doesn't monitor the episodes under that season, which means this is functionally broken for "Ended" shows. 

It does work fine for shows that are currently running, though.

### Describe alternatives you've considered

Writing a custom script to accomplish this myself.

**Comment by augustuen** [comment]
Please search for existing issues before submitting. Already fixed in 5d86329
