### ISSUE TITLE
Ability to increase release cache time

### ISSUE THREAD

**Issue by ShanaryS** [Sonarr/Sonarr#6239]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'm using sonarr to search for releases and storing the results so I don't need to constantly hit the indexers. Currently releases are cached for 30 min before I have to do another search.

### Describe the solution you'd like

I would like to increase this to 6 hours in my case. The releases being "outdated" does not matter in this scenario.

### Describe alternatives you've considered

Add an option on the GET /release endpoint to specify how long it should be cached for.

**Comment by markus101** [comment]
No plans to increase this timeout, if you're processing them another way you could use release push to push it up and bypass the cache.

**Comment by ShanaryS** [comment]
This seems to work for me. Should I use guid or downloadUrl as the link @markus101

**Comment by markus101** [comment]
The GUID isn't guaranteed to be a link, it's just what Sonarr defaults to if a separate element isn't provided, so best to use `downloadUrl`.
