### ISSUE TITLE
Prefer a season pack download even if existing file is the same quality

### ISSUE THREAD

**Issue by Pukabyte** [Sonarr/Sonarr#6242]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Not updating media properly. Sometimes my indexers will only pick up one episode of a season, but when searching for seasons it won't download a full season because there's already an episode downloaded.

### Describe the solution you'd like

Sonarr to allow a download of a season pack even if there is already a file (1 episode) downloaded of the same quality.

### Describe alternatives you've considered

Deleting existing file and then manually searching again

**Comment by markus101** [comment]
With interactive search you can override Sonarr's rejection and grab it, at this time we do not have plans to grab season packs unless it's an upgrade for all episodes.

Related to https://github.com/Sonarr/Sonarr/issues/5502

**Comment by Pukabyte** [comment]
What about allowing same qualities for auto?
