### ISSUE TITLE
Notification for "Episode grab failed due to quality settings"

### ISSUE THREAD

**Issue by caveman250** [Sonarr/Sonarr#6244]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have been running Sonarr with semi aggressive file size limits due to the weak hardware in my server. 99% of the time i am able to grab releases with my settings, however some times there just isn't a release within my size limits. Raising the size limits to fit these outliers isn't really a good solution as Sonarr begins downloading everything in these larger file sizes, which is something i would like to avoid.

### Describe the solution you'd like

If Sonarr could let me know when this situation occurs (there is a release available, but its too large, or only available in a different profile ect) that would make keeping up to date with my media much easier.

### Describe alternatives you've considered

While filling out this form realised my issue could also be solved if there was a "prefer smaller files" option of some kind.

**Comment by stevietv** [comment]
Sonarr v4 has file size preferences in the Quality Definitions.
We couldn't make a notification for each file that fell outside of your requirements, you'd be getting hundreds of notifications
