### ISSUE TITLE
Estimated Bitrate Custom Format

### ISSUE THREAD

**Issue by luki28** [Sonarr/Sonarr#6245]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When I grab releases, I think it would be useful if I could specify a wanted bitrate range also in Custom Formats.

### Describe the solution you'd like

Additionally to the "Size" Custom Format, maybe you could add a "estimated Bitrate" Custom Format.

### Describe alternatives you've considered

I am aware of the "Quality" Settings, but they are not on the same hierachy level as Custom Formats.

**Comment by markus101** [comment]
Duplicate of https://github.com/Sonarr/Sonarr/issues/5496
