### ISSUE TITLE
Add Support For Sending Notifications Via Apprise

### ISSUE THREAD

**Issue by warieon** [Sonarr/Sonarr#6251]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'd like to be able to send notifications from Sonarr through Apprise, allowing me to leverage Apprise's enhanced and comprehensive list of different notification providers.

### Describe the solution you'd like

A new notifications connection template for Apprise allowing a user to enter the URL of their Apprise installation, or one of the connectors defined in Apprise.

### Describe alternatives you've considered

Custom script?

**Comment by augustuen** [comment]
Already in Sonarr V4
