### ISSUE TITLE
Removal of ` (grave accent) when using cleantitles

### ISSUE THREAD

**Issue by soultaco83** [Sonarr/Sonarr#6255]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I am having issues with transcoding files due to the file names have a `` in them. Example:
S01E003 - My Ex Has a Confession to Make You Didn`t Do Anything Weird Did You!(Subbed).mkv

I would expect that the CleanTitle would remove these but appears to not. 

### Describe the solution you'd like

I would like to request that cleantitle remove `` addionally. If possible make it configurable to remove any undesired characters. But mostly add ` to the list of removed items

### Describe alternatives you've considered

n/a

**Comment by markus101** [comment]
Same underlying reasoning as https://github.com/Sonarr/Sonarr/issues/2028, closing in favour of that existing issue.
