### ISSUE TITLE
Have multiple paths per show

### ISSUE THREAD

**Issue by amcgready** [Sonarr/Sonarr#6256]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I currently use a project called Plex Debrid to essentially stream torrent files via my Plex server and Real Debrid. The issue I'm seeing is that Sonarr can't look multiple places for the same file. Real Debrid is mounted to my computer (Windows 11) to drive R and Plex Debrid sorts the torrents into 'default', 'tv' and 'movie' categories but does not make specific show or movie folders inside this structure. The reason for wanting this is so Sonarr can scan the real debrid mount and if a file is not found it will begin a search for downloading.

### Describe the solution you'd like

The solution I'm looking for comes in a few parts:
1) Allow Sonarr to scan multiple paths for a file
2) Set a different download path for a file if it is not found (i.e. if file is not found on drive R or another root drive, file is saved to separate drive such as drive Z)

### Describe alternatives you've considered

I've tried setting up delays in searches, but this has failed. For example, setting up a release delay for Sonarr to search giving Plex Debrid the opportunity to find the file first. Since Sonarr can not scan the real debrid directory and save elsewhere, there is a problem where Sonarr will download shows regardless of if Plex Debrid already found them.

I have tried making a shortcut to 'R" inside of the root folder that Sonarr is scanned but Sonarr does not appear to read the shortcut.

**Comment by augustuen** [comment]
This sounds like

1. It would be really complicated to implement and support
2. It would only be useful for using Real Debrid, which isn't supported by Sonarr for good reason.

**Comment by amcgready** [comment]
What about allowing Sonarr to scan shortcut paths? I'd have to manually set this up for each show but it may be easier to implement.

**Comment by markus101** [comment]
Sonarr won't follow shortcutsd, but you might be able to do something with folder mounting/junctions, but this isn't something we're going to actively support.
