### ISSUE TITLE
Finally fix #255 in v4 please (DVD Order)

### ISSUE THREAD

**Issue by dandud100** [Sonarr/Sonarr#6261]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Many users have this problem that they can't select that sonarr should look at the DVD Order on TVDB.

I also see this question very often in the Discord.

One more example for the list is SpongeBob SquarePants.

### Describe the solution you'd like

Select in the metadata settings what order I want to use from the metadata provider like I can do in Jellyfin.

### Describe alternatives you've considered

Idk

### Anything else?

#255

**Comment by stevietv** [comment]
the issue #255 remains open - there is no need to open another issue for this.
