### ISSUE TITLE
Clear Passwords/API keys when Cloning Connections/Indexers/Download Clients

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#6265]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

https://github.com/Sonarr/Sonarr/commit/570be882154e73f8ad1de5b16b957bcb964697fd  results in the API Key literally being `********` when cloning an existing indexer 
![image](https://github.com/Sonarr/Sonarr/assets/55419169/6b9fedec-9f53-4d6c-8d97-106e23f43bbc)

### Expected Behavior

indexer cloning (and download client or other cloning) should get and clone the credentials from the database give then are not in the api

### Steps To Reproduce

1. Clone Indexer
2. Realize API Key did not get cloned

### Environment

```markdown
- OS: ubuntu 22.04
- Sonarr: 4.0.0.738
- Docker Install: Yes - nightly-374ea5c by hotio
- Using Reverse Proxy: N/A
- Browser: N/A
- Database: Postgresql 14.10
```

### What branch are you running?

Develop

### Trace Logs?

API/UI/Backend - trace is N/A

**Comment by markus101** [comment]
Clone is purely a UI helper, it does not communicate to the backend, thus it has no knowledge what the value is. The value should be cleared instead of copied as-is though.
