### ISSUE TITLE
Change either search settings for series or episode search pattern options

### ISSUE THREAD

**Issue by drakus72** [Sonarr/Sonarr#627]
What I am meaning is the thetvdb and others, some do show as season 1 -7, but most say American Pickers is Season 2015 and when searching it won't find the current show due to it searching season 2015 and not season 7 as it is posted.

Is there a way to fix this or a setting or something else?

**Comment by markus101** [comment]
Please use the forums for support. This question has been asked and answered there before (and is in our FAQ: https://github.com/Sonarr/Sonarr/wiki/FAQ#how-does-sonarr-handle-scene-numbering-issues-american-dad-etc). Sonarr uses thexem.de to deal with numbering differences.
