### ISSUE TITLE
Queue should have the option to show Grab Date

### ISSUE THREAD

**Issue by Rubicj** [Sonarr/Sonarr#6270]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When looking at a large queue of downloading items, I would like to be able to see the oldest/newest items in the queue.

### Describe the solution you'd like

Add "Grab Date" as an option in the "Table Columns" options of the Queue:
![image](https://github.com/Sonarr/Sonarr/assets/14086872/86208e4e-2ec6-4943-a87c-382dda5b244a)

### Describe alternatives you've considered

I can use the download client's organization to modify downloads there, but then Sonarr gets confused about downloads dissapearing, and sometimes attempts to regrab the same download later.

### Anything else?

I think the columns in https://github.com/Sonarr/Sonarr/blob/e291834393ce29a1c5c631875e47c62362031e1d/frontend/src/Components/Table/TableOptions/TableOptionsModal.js

are autopopulated from 
https://github.com/Sonarr/Sonarr/blob/e291834393ce29a1c5c631875e47c62362031e1d/src/Sonarr.Api.V3/Queue/QueueResource.cs#L18

which only has access to the fields in the Queue defined in 
https://github.com/Sonarr/Sonarr/blob/e291834393ce29a1c5c631875e47c62362031e1d/src/NzbDrone.Core/Queue/Queue.cs#L13

which doesn't include add date. I _think_ a  NzbDrone.Core.Queue.Queue is a Database object, but I can't find where Queue objects are created using GitHub's online search.

I know that the Grab Date is knowable, because it shows up in individual items History, which is presumeably written at the same time that the Queue object is created. 

I'm not sure how much this project tries to avoid database migrations, but the most direct solution seems to be adding "Grab Date" to the Queue object, and populating that information when the Queue is added to the DB.

**Comment by Rubicj** [comment]
If a database migration is to be avoided, it's probably possible to populate this field from the History table, rather than inserting a new column in the Queue table -- it'll just be a bit messy to pull from multiple tables in the QueueResourceMapper.

**Comment by markus101** [comment]
There is no queue table, queue is built from things Sonarr gets from your download client and anything in pending releases.

`Queue` and `QueueResource` would need a new property, `QueueService` would need to populate it, probably the same way `Indexer` is done from the `TrackedDownload`.

> I can use the download client's organization to modify downloads there, but then Sonarr gets confused about downloads dissapearing, and sometimes attempts to regrab the same download later.

Not sure how this applies to this request.

**Comment by Rubicj** [comment]
> Not sure how this applies to this request.
Just describing alternate ways of doing this -- I could go in my download client and sort by `Date Added` there, but it's a pain, plus if I delete files though there they don't get blacklisted, so the *arr might pick them up again later.

> QueueService would need to populate it, probably the same way Indexer is done from the TrackedDownload.
<3 I see

**Comment by Rubicj** [comment]
Going to try to do this myself

**Comment by Rubicj** [comment]
I see two ways to do this -- use the time from the Download client, or use the time from the History. The time in the Download client is probably more accurate, but requires me to check that it works for EVERY supported download client, and that seems unreasonable. Doing the suggested History change, same as the Indexer.
