### ISSUE TITLE
Show which download client a pending download is waiting for

### ISSUE THREAD

**Issue by fryfrog** [Sonarr/Sonarr#6274]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes a download ends up in a pending state. This is *usually* caused by a setup which accidentally crosses usenet w/ torrents, but occasionally by tags or indexers assigning disabled download clients.

![image](https://github.com/Sonarr/Sonarr/assets/87748/164c7cbb-081b-4710-9418-3ec97114783d)

### Describe the solution you'd like

When a pending download is waiting for a *specific* download client, we should show its name like "Pending - Download client Nzbget is unavailable".

### Describe alternatives you've considered

Guessing.

**Comment by markus101** [comment]
Ended up making more sense for this to utilize the `Download Client` column, because the messaging is only based on a status.
