### ISSUE TITLE
Let me remove auth

### ISSUE THREAD

**Issue by mzrimsek** [Sonarr/Sonarr#6278]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I don't understand why we are removing features for authentication with the latest updates. Why can I no longer use my well configured and secured Authelia middleware as my auth and keep Sonarr unauthenticated? This has to be the single stupidest decision I have ever seen in an open source project to date. Just make it something you have to configure manually in some files that isn't available in the UI? Why remove features and make the product objectively worse?

### Describe the solution you'd like

Make it configurable in a file somewhere

### Describe alternatives you've considered

Just stop updating my applications because they are getting objectively worse.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

This is also already covered on the wiki.

**Comment by mzrimsek** [comment]
Please refer me to the notes so I can understand why this moronic decision was made.

**Comment by mzrimsek** [comment]
Obviously idiots running this project now if this is how you guys are going to "make things secure". I had 2 factor auth protecting my instances and they are actually less secure now. My disappointment is immeasurable I wish more than anything that someone will fork this project and Sonarr dies now.

**Comment by thezoggy** [comment]
rather than spend your energy attacking the project you are using, perhaps spend the effort to read the page or wiki that talks about your specific scenario and how to accomplish it. the change was done to make things more secure out of the box.

**Comment by mzrimsek** [comment]
My problem is my setup is LESS secure now! You guys can't just enforce this and not provide robust options for AT LEAST two factor auth. Anything short of that is just making things worse.

**Comment by mzrimsek** [comment]
Alright I was a bit a cunt here. I am very frustrated I've had to monkey around with settings and have things that have "just worked for over as year now" just break on me this morning with covid no less. Unwarranted attacks on a project I use aside, you guys actually have done exactly what I asked for so apologies are in order.

**Comment by johnhaley81** [comment]
For anybody wondering, you can check out the [V4 FAQs](https://wiki.servarr.com/en/sonarr/faq-v4#forced-authentication) for more details on the auth change.
