### ISSUE TITLE
Skip already existing series when adding new

### ISSUE THREAD

**Issue by Morten242** [Sonarr/Sonarr#628]
When adding a new series from disk it would be nice if it skipped look-up of the folders which are already added to Sonarr. Or have an option to not display them.

**Comment by markus101** [comment]
It will exclude any matching paths, if you have multiple ways to access the same files (Shared Drive letter and UNC path for example), then it will include them because they are different paths.

**Comment by Morten242** [comment]
Strange. I _was_ seeing different behaviour. Looks like it only started ignoring paths after finishing processing the folder. Guess I was too quick when moving a folder in to the same parent directory and then adding that.

Well, anyway, thanks! :smile:
