### ISSUE TITLE
Un-monitor seasons when it's completely downloaded

### ISSUE THREAD

**Issue by mscheltienne** [Sonarr/Sonarr#6281]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

IMO, sonarr succeeds best at fetching good quality release either when fetching an entire season, or episode per episode _in the period following the official release_. However, months or years after the official release, it often grabs one episode randomly within a season. Likely a re-upload or a new _different_ upload badly named; which gets grabbed and replace the existing release.

### Describe the solution you'd like

I would like a settings which says: "Automatically unmonitor season when fully downloaded".
I would like sonarr to stop monitoring seasons which have been entirely retrieved, and thus to stop replacing some of its episode with poorly chosen releases.

### Describe alternatives you've considered

The cut-off on quality is not sufficient as it will sometime still grab badly named/wrong language release because of the higher quality.

**Comment by stevietv** [comment]
Sonarr will only grab a new release if it is considered better than the one you already have.
Instead of un-monitoring you need to better define your quality profiles. Unmonitoring completed downloads is a not a feature that is planned.

Please use one of the support channels for more assistance here: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by mscheltienne** [comment]
@stevietv A settings to only unmonitor completed download is not a wanted feature. I understand that much and it's well founded.
However, sonarr lacks settings to set **rules** to automatically unmonitor episodes, seasons or shows. Example of rules:

- unmonitor a season when the season is entirely downloaded
- unmonitor a show 2 years after the last episode

IMO, sonarr lacks a tool, besides the API, to unmonitor automatically episode/season/shows. Consider the following scenarios:

- Sonarr sees a new release of a 3 year old show, in blu-ray instead of the current webdl. Thus, it choose to update. But instead of being a good blu-ray rip, which would have been released years ago, it's a re-upload with badly set name/metadata, e. g. in a different language.
-> I already had sonarr replace a perfectly good episode with something from an entirely different show, years later.

- A TV shows which stopped 8 years ago is finally getting a new season! Well, 8 years ago the quality was rather low, e.g. 720p, and now sonarr sees a ton of new episode coming in, some badly named/with erroneous metadata, in higher quality. It will grab some of those episode to replace episodes from the previous seasons thinking that's where they belong.
