### ISSUE TITLE
Season year token

### ISSUE THREAD

**Issue by Grimthorr** [Sonarr/Sonarr#629]
It would be nice to have the ability to add the year to season folder names.

For example:

![image](https://cloud.githubusercontent.com/assets/5190473/8251773/46a15f3a-1677-11e5-8995-1fa07b55f7b2.png)

Which would rename the season folder to the release/running year of that season, for example:
- Game of Thrones season 4: `Season 4 (2014)`
- Breaking Bad season 5: `Season 5 (2012-2013)`

I believe SickRage supports this by allowing full use of date tokens, such as `Y` for year and `M` for month in all rename fields.

**Comment by markus101** [comment]
What would you get for a series that spans two years because it runs in the fall/winter?

For Breaking Bad Season 5 Sonarr wouldn't know that it spans two years until the 2nd half of the season started and if it updated to `(2012-2013)` the existing episodes would be left in the existing `(2012)` folder until they were renamed.

**Comment by Grimthorr** [comment]
Good point, I assume the year would be obtained from the `FirstAired` date so it would be fine to use the first year for a season that spans 2 years, so Breaking Bad season 5 would be `(2012)`.

On this note, is there a possibility that the media manager could use existing season folders if it detects them? So for example, if the season 5 folder for Breaking Bad already exists with the name `Season 5 (2012-2013)`, could Sonarr check for it's existence (detect if a folder already exists that contains the season folder format (`Season 5`) in the name?) and then use that folder instead of creating a new folder?

**Comment by nfarrar** [comment]
Appears that this this still not an option, but something I think is really valuable. To clarify:

|  Support  |               Format                         |          Name               |
| --------- | ------------------------------ | -------------------- |
| Current   | {Series.Title}                              | Planet.Earth              |
| Desired   | {Series.Title}.({ReleaseYear})   | Planet.Earth.(2006) |

As it is right now, I manually create every season folder with the desired name and reconfigure every series to use the correct folder.

**Comment by desimaniac** [comment]
Have to say I would like this too: Season Folder: `{Series CleanTitle} ({ReleaseYear})` 

- basically year in parentheses, but still have a clean title.

**Comment by rcedwards** [comment]
This would be especially useful for weekly shows like John Oliver or SNL.

i.e. `Saturday Night Live/Season 44 (2018-2019)/...`

**Comment by LyhjeHylje** [comment]
ReleaseYear -token would definitely be useful. Sometimes Plex struggles to match shows without it. And then there are series with same names

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR

This issue seems stale.  Please check and see if it is still an issue on the recent v3 builds.  If it is an issue please open a new GHI with logs and full detail.
