### ISSUE TITLE
Ubuntu 22.04 Install Issue(s)

### ISSUE THREAD

**Issue by below9k** [Sonarr/Sonarr#6291]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When running the install script (`sudo curl -o- https://raw.githubusercontent.com/Sonarr/Sonarr/develop/distribution/debian/install.sh | bash`) shown on the download page, the installation is not elevated unless the user becomes root `sudo -s`.
After doing this the script gets past the `echo "Please run as root."` but fails on checking the group

### Expected Behavior

The script should prompt for user and user group, then complete the install successfully.

### Steps To Reproduce

Have a relatively fresh install of ubuntu server 22.04 & attempt to run the install script.

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: v4 (Jan 2 2023)
- Docker Install: No
```

### What branch are you running?

Develop

### Trace Logs?

```
Running Sonarr Install Script - Version [1.0.1] as of [2023-12-29]
This will install [Sonarr] to [/opt/Sonarr] and use [/var/lib/sonarr/] for the AppData Directory
Sonarr will run as the user [app_uid=$(echo "$app_uid" | tr -d ' ')] and group [app_guid=$(echo "$app_guid" | tr -d ' ')]. By continuing, you've confirmed that that user and group will have READ and WRITE access to your Media Library and Download Client Completed Download directories
groupadd: 'app_guid=$(echo "$app_guid" | tr -d ' ')' is not a valid group name
```

### Anything else?

Running the commands manually seems to work

```
root@dlbox:/home/below9k# app_guid=$(echo "$app_guid" | tr -d ' ')
root@dlbox:/home/below9k# echo $app_guid

root@dlbox:/home/below9k# app_guid=${app_guid:-media}
root@dlbox:/home/below9k# echo $app_guid
media
root@dlbox:/home/below9k# groupadd "$app_guid"
groupadd: group 'media' already exists
root@dlbox:/home/below9k#
```

**Comment by stevietv** [comment]
sorry about this, seems I didn't realise that piping to bash didn't allow for the user input prompts. 
the website commands will be updated: https://github.com/Sonarr/sonarr.github.io/pull/35
