### ISSUE TITLE
Show Monitor button on hover

### ISSUE THREAD

**Issue by Milincho** [Sonarr/Sonarr#6292]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Not a problem, but a suggestion for more streamlined workflow.
A Monitor button on hover would be useful.

### Describe the solution you'd like

A button that appears on hover, same as the search button that can be enabled in Options.

![image](https://github.com/Sonarr/Sonarr/assets/60118859/bcc30b0f-3fb0-4180-9c2a-9608fe871b1e)

### Describe alternatives you've considered

None come to mind.

**Comment by markus101** [comment]
This isn't something we directly support via any of the views and after discussing not something we plan to introduce to the poster via and others at this time. Labeling to reconsider in the future though.

**Comment by Milincho** [comment]
Ok. Thanks anyway for the consideration. I think it will save time.
