### ISSUE TITLE
[macOS] version numbers are wrong, app claims to be version 3.0 instead of 4.0

### ISSUE THREAD

**Issue by core-code** [Sonarr/Sonarr#6294]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

after downloading version 4.0.0.748 the app claims to be version 3.0

### Expected Behavior

i expect version 4.0.0.748 to be version 4.0.0.748 and not 3.0

### Steps To Reproduce

1.) download sonarr 4.0.0.748 on a Mac
2.) look at its version numbers in the Finder using "Get Info", "Quick Look" or "Column View". all of them show "3.0" instead of "4.0.0.748"

### Environment

```markdown
- OS: macOS
- Sonarr: 4.0.0.748
```

### What branch are you running?

Main

### Trace Logs?

N/A

### Anything else?

here are screenshots illustrating the issue

<img width="460" alt="Screenshot 2024-01-02 at 23 17 10" src="https://github.com/Sonarr/Sonarr/assets/1261954/5ce881ec-8d86-4269-ac6e-3618
<img width="349" alt="Screenshot 2024-01-02 at 23 16 54" src="https://github.com/Sonarr/Sonarr/assets/1261954/03776e5c-bcb1-45ee-8ef9-994a3abd7e6d">
5517cfd0">
<img width="261" alt="Screenshot 2024-01-02 at 23 16 34" src="https://github.com/Sonarr/Sonarr/assets/1261954/5e3a1553-be74-4153-b149-a105c183e009">

the technical cause of the bug is the wrong ```CFBundleVersion``` and ```CFBundleShortVersionString``` entries in your ```Info.plist``` file - those are set to 3.0 but should be set to 4.0.0.748

also the ```Contents/MacOS/bin/release_info``` file containing the version number disappeared in 4.0

**Comment by core-code** [comment]
<img width="460" alt="Screenshot 2024-01-02 at 23 17 10" src="https://github.com/Sonarr/Sonarr/assets/1261954/4b73cdf4-eb85-4314-80bd-9bd1ccd2c4a2">

**Comment by suschizu** [comment]
yes right - I can confirm this

**Comment by markus101** [comment]
Just like v3, they will not be the final app version (4.0.0.478), they'll be 4.0 so they aren't wrong when a new update is installed.

**Comment by core-code** [comment]
ugh, they need to be updated when the app is updated.

**Comment by AmnaSN** [comment]
I can confirm this as well!
