### ISSUE TITLE
Change the scheduled tasks frequency

### ISSUE THREAD

**Issue by bugsysiegals** [Sonarr/Sonarr#6300]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

My media server continues to spin up/down the disks multiple times per hour and is going to wear them out prematurely.

### Describe the solution you'd like

Adjust how often the tasks should be triggered as Jellyfin does.

### Describe alternatives you've considered

Stop using Sonarr ... I'd rather not, it's a nice app.

**Comment by markus101** [comment]
This has come up before, we have no plans to make the task interval variable, outside the ones that already are.

Most things Sonarr is doing is done against the database and logs, you can disable Sonarr's disk rescanning after updating series information as outside importing files that'd be the one to wake up your data disks.
