### ISSUE TITLE
Support broken for SABnzbd 4.2.0+

### ISSUE THREAD

**Issue by justy777** [Sonarr/Sonarr#6302]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

SABnzbd downloads the file, and Sonarr is unable to locate it.

### Expected Behavior

It's expected that Sonarr will import the file from SABnzbd and move it into the proper folder.

### Steps To Reproduce

1. With Sonarr v4 and SABnzbd 4.2.0 running on Docker
2. Configure Sonarr to work with SABnzbd
3. Grab a release

### Environment

```markdown
- OS: Fedora 39
- Sonarr: Sonarr 4.0.0.748
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 121.0
- Database: Sqlite 3.44.2

- SABnzbd: 4.2.0
```

### What branch are you running?

Main

### Trace Logs?

https://pastebin.com/UF2c1Ez8

### Anything else?

https://www.reddit.com/r/sonarr/comments/18y9wf5/new_series_not_being_imported/

**Comment by bakerboy448** [comment]
Logs show nothing other than tracking a download in sab and no completed download nor import / failed import attempts?

**Comment by thezoggy** [comment]
have you tried restarting your dockers?

**Comment by justy777** [comment]
Weird, that solves the issue. 
Thanks Guys!

Someone is gonna want to tell the guys on Reddit.
