### ISSUE TITLE
Lowest Custom Format Score Column In Series List

### ISSUE THREAD

**Issue by duckman** [Sonarr/Sonarr#6305]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When going through my series looking to upgrade to better versions, I have to click into them each to see if a series needs an upgrade.

### Describe the solution you'd like

If there was a column that contained the lowest CF score in the series, it would help me find which series has episodes that aren't up to snub.

### Describe alternatives you've considered

Another option would be to group by series in the Cutoff Unmet page

**Comment by markus101** [comment]
At this time it'd be quite inefficient to run for each file in each series and nothing something we're currently going to implement.
