### ISSUE TITLE
Long Term Search Missing

### ISSUE THREAD

**Issue by Biztactix-Ryan** [Sonarr/Sonarr#6309]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I've seen several Sonarr Instances with thousands of missing episodes, possibly 10s of thousands that are still wanted
They may appear at some point, However Many indexers even paid, have daily API limits, which you will easily hit searching missing.

### Describe the solution you'd like

I'd like a way for the system to perform a sort of ongoing search each day, an hour before the end of the day, UTC generally but probably needs to be configurable per indexer. 
Where it will search say the first 1000 today, the next 1000 tomorrow and so on and so on... 
That way you can maximise the API per indexer and also you're not searching the same first 1000 in the list of missing
in theory it could just be a daily job to grab 500-1000 at a time and search them at a specific time... So another system job.

### Describe alternatives you've considered

 alternatively, the search missing button could just have start at option. so when you manually click it, you can say, start searching at the 5000th item in the missing list... 

### Anything else?

I could be completely misunderstanding how the search missing works and it's already efficient or at least random... But generally if you're looking for 20+ year old content, it's not available always, but it does pop up from time to time. So we should at least try and whittle that list down daily.

**Comment by thezoggy** [comment]
ideally you dont tell sonarr to do massive backlog searches for multiple series... but there are tools to handle this such as missarr or upgradinator that solve what you want

**Comment by Biztactix-Ryan** [comment]
Those do sound like a good solution, I didn't consider an external option, and of course there is something... 
However an inbuilt solution would seem to be clean and not considerably complex given it already has all the info in the system to do so
Even if it searched for the next 10 episodes every hour... just trying to whittle that backlog down.

**Comment by Qstick** [comment]
Sonarr is built specifically to avoid this type of mass searching on indexers. The inability to do this is intentional and in my opinion this should remain as is.

**Comment by markus101** [comment]
We don't have plans to support automatic backlog searching, unless you've added an indexer or made significant changes to profiles backlog searching is inefficient and a burden on indexers.

Sonarr does store the last time an episode was searched for, which could be used with this issue to support filtering and searching on a manual basis https://github.com/Sonarr/Sonarr/issues/3657
