### ISSUE TITLE
Regarding support for the Chinese language on the UI.

### ISSUE THREAD

**Issue by mm519897405** [Sonarr/Sonarr#6310]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After attempting to translate some of Radarr and Sonarr into Chinese, I discovered that Sonarr does not have the capability to switch languages.
Why doesn't Sonarr offer the option to switch UI languages, yet it provides requests for translations?

### Expected Behavior

I've been using Sonarr/Radarr for over two years now, and I hope that Sonarr will support language switching in the future.

### Environment

```markdown
- OS: synology
- Sonarr: 3.0.10.1567
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: chrome
- Database: Unrelated
```

### What branch are you running?

Main

### Trace Logs?

Unrelated

**Comment by stevietv** [comment]
upgrade to v4, it does there.

**Comment by mm519897405** [comment]
> upgrade to v4, it does there.

Oh, thank you for telling me this exciting news
