### ISSUE TITLE
Expansion of Custom Script Events?

### ISSUE THREAD

**Issue by jsaddiction** [Sonarr/Sonarr#6312]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

First off, thank you for continuing to develop such an amazing project!

Media devices/software are unaware of changes to metadata stored within NFO files.  Specifically, Kodi is unaware of title changes on an episode unless manually refreshed.

### Describe the solution you'd like

I am currently writing a python script for use as a "Custom Script" that intelligently manages a shared Kodi library.  I can get into the details of why but it's a long story and basically a result of my unrelenting need for accurate library representation of media.  This script is triggered by every "Event" Sonarr exposes and handles them accordingly.  As I move through the initial development phase, I have noticed that changes to NFO data are updated however this change isn't handled in any of the events (I think). I am not sure if the embedded Kodi connection handles these events.  Has there been any discussion on expanding the current iteration of custom script Events? Maybe an "on_metadata_change" event with some environment variable depicting what those changes were.

### Describe alternatives you've considered

I could write a script that periodically checks for updates to metadata through API calls to both Kodi and Sonarr however, this seems inefficient and subject to propagation delays extending beyond TMDB caches. Additionally, this may require storing modified times in a database to identify these changes.

### Anything else?

I am not sure if changes to locally stored images happen very often however the same issue may apply.  Essentially, robust communications between Sonarr and media software is essential to maintaining a fully TMDB synced UI.

**Comment by markus101** [comment]
We do not have plans to add an event when metadata files are updated.

You could listen to SignalR event coming from the API (that's how the UI auto updates) when are triggered per series when series metadata is refreshed, though a refresh doesn't necessarily mean Sonarr has received updated information.
