### ISSUE TITLE
'Prefixed Range' multi-episode style not picked up by Plex when using SxEE format

### ISSUE THREAD

**Issue by treyturner** [Sonarr/Sonarr#6316]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When Sonarr renames multi-episode files using SxEE format (ie. `{season:0}x{episode:00}`, like `1x01`), the `Prefixed Range` style produces filenames that aren't correctly picked up by Plex.

Example: Season 1, Episodes 1-3
Current behavior: Results in `1x01-x03`; Plex detects only `1x01` and not `1x02` or `1x03`

### Expected Behavior

Expected behavior: Plex could pick up all 3 episodes in range if the dash were omitted, ie. `1x01x03`

The `Repeat` style comes closest to this, as it produces `1x01x02x03`, however Plex doesn't like this either: it detects only episodes 1 and 2, and not 3. **Plex seems to expect either a single episode in SxEE format, or the boundaries of a range (not every member).**

### Steps To Reproduce

1. Import a three or more episode file using a multi-episode style of `Prefixed Range` and a format that includes `{season:0}x{episode:00}`.
2. See that the resulting filename includes `SxEE-xEE` (with the first and last of the range)
3. See that only the first episode of the range is picked up by Plex
4. Rename the file by hand to `SxEExEE` (the first and last of the range)
5. See that Plex now correctly identifies all episodes in the range

### Environment

```markdown
- OS: Alpine 3.18
- Sonarr: Sonarr 4.0.0.748
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Brave 1.61.114, Chromium 120.0.6099.199 (64-bit)
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/13852331/sonarr.trace.txt)

### Anything else?

I downloaded and imported an S01E01E02E03 episode just before creating the trace logs. Apparently Sonarr decided that due to scene -> episode mapping for the show I picked, the file contained episodes E01-E09, which isn't correct but is unrelated. The important bit is how Sonarr named the resulting file and to understand Plex will only detect the first episode as being present.

**Comment by markus101** [comment]
Plex has their own support article for naming episodes: https://support.plex.tv/articles/naming-and-organizing-your-tv-show-files/ including multi-episode files, that format is not listed there.

**Comment by treyturner** [comment]
Very true. Documentation aside, Plex does support SxEE including ranges just as I described it, so it's a shame Sonarr users with this preference can't be accommodated.

**Comment by markus101** [comment]
Sonarr uses the format you've specified (as long as renaming is enabled), it absolutely supports Plex's naming if you configure it to do so.
