### ISSUE TITLE
RSS stops updating

### ISSUE THREAD

**Issue by talz13** [Sonarr/Sonarr#633]
I just opened up Sonarr to check on any missing downloads... Found several series that missed episodes, and on looking at the log file, it had stopped scanning on 6/16 at 18:36.  No indication that anything is wrong from the front end, just that the log stopped writing until I browsed the page:

```
15-6-16 18:21:18.2|Info|RssSyncService|Starting RSS Sync
15-6-16 18:21:21.1|Info|DownloadDecisionMaker|Processing 200 releases
15-6-16 18:21:22.9|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0
15-6-16 18:36:49.8|Info|RssSyncService|Starting RSS Sync
15-6-16 18:36:52.3|Info|DownloadDecisionMaker|Processing 200 releases
15-6-16 18:36:53.9|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0
15-6-22 15:28:53.2|Warn|GlobalExceptionHandlers|SignalR Heartbeat interupted
```

Please let me know if this is a known issue, and any other information that would help identify the problem.

    Ubuntu 14.04.2
    Kernel 3.13.0-48
    Sonarr 2.0.0.3212
    Mono 3.10.1

**Comment by markus101** [comment]
Please use the forums for support.

https://forums.sonarr.tv/t/scheduled-tasks-not-running/5828
