### ISSUE TITLE
Separate colors for Premiere/Special/Finale on Calendar

### ISSUE THREAD

**Issue by Nisheshg5** [Sonarr/Sonarr#6331]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The Icons for all three are identical and can't be distinguished without hovering over them
<img width="206" alt="Screenshot 2024-01-11 021646" src="https://github.com/Sonarr/Sonarr/assets/46001977/59e76946-861b-4e55-b8f6-83b0ae1383a5">

### Expected Behavior

All three icons should have different colors so they are easily distinguishable like in v3.x
Note: This is in `Full Color Events` mode

### Environment

```markdown
- OS: Windows 11 (23H2)
- Sonarr: 4.0.0.748
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.36.0
```

### What branch are you running?

Main

### Trace Logs?

No

**Comment by markus101** [comment]
They do have different colours:

![image](https://github.com/Sonarr/Sonarr/assets/413544/48db51f4-a842-4d0b-bc57-b290b5784eab)

Unless you've set the calendar to use 'Full Color Events', in which case you can use the season and episode number to differentiate between the different indicators.

The premiere color is wrong in the legend though, it's supposed to be a light blue color when not using 'Full Color Events'.

**Comment by Nisheshg5** [comment]
> They do have different colours:
> 
> ![image](https://private-user-images.githubusercontent.com/413544/295708899-48db51f4-a842-4d0b-bc57-b290b5784eab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MjA2NzgsIm5iZiI6MTcwNDkyMDM3OCwicGF0aCI6Ii80MTM1NDQvMjk1NzA4ODk5LTQ4ZGI1MWY0LWE4NDItNGQwYi1iYzU3LWIyOTBiNTc4NGVhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQyMDU5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2M4M2QzNGFhNTA3NTM1ZDhiYjgxZjgwNmQ5NTYyNGFmMmI2ZTEyNzUzZGI5ZjEwY2E0NmMxMmVhZmY4YTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y0t4QXHSvIvWteca40rNSJlMn1tARAlpc-kS8vfd0GQ)
> 
> Unless you've set the calendar to use 'Full Color Events', in which case you can use the season and episode number to differentiate between the different indicators.
> 
> The premiere color is wrong in the legend though, it's supposed to be a light blue color when not using 'Full Color Events'.

Yes, I meant in the `Full Color Events` only
In v3, it was different colors but now they are the same colors
It doesn't make sense that in full color mode, all the icons are in the same color but in the normal mode, they are the same color

**Comment by markus101** [comment]
It makes sense when you consider that these colors do not work well on full color backgrounds, beyond looking bad it's a visibility issue for people.

Missing premiere:
![image](https://github.com/Sonarr/Sonarr/assets/413544/9ec5a5be-2916-4336-a3fb-b459537f375b)

Missing premiere with color impaired mode:
![image](https://github.com/Sonarr/Sonarr/assets/413544/464ced4c-8bd8-45e9-bb69-fd63afcae9ad)

Missing special:
![image](https://github.com/Sonarr/Sonarr/assets/413544/66e51ad5-c322-4549-adcd-ad4bf2668388)

We're not going to reintroduce a visual issue to separate the colors as they are by default, but will take a look at what we can do to differentiate them better.
