### ISSUE TITLE
Manual Import: Show Existing Custom Format Score in Rejection message

### ISSUE THREAD

**Issue by johnpyp** [Sonarr/Sonarr#6337]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When clicking manual import in the activity queue, for example with a season pack that says the existing show has a custom format score or quality greater than the new one, you can't see what it's comparing against without opening up a new sonarr tab, going to the series (or closing the manual import and clicking the series), so you don't really know if it actually should be ignored or if there's something maybe wrong with your setup causing these files to get downloaded but not used.

### Describe the solution you'd like

It would be great to be able to see an inline comparison of the filenames and custom format scores just in case it's indicative of a problem with the setup. Something like this:
![image](https://github.com/Sonarr/Sonarr/assets/20625636/d86fd3ff-2440-4fe8-89e5-de169c5a39f2)

### Describe alternatives you've considered

The manifestation of the feature could be done in a couple ways...
- Add a column or row underneath each entry for the existing match
- Add it in the hover tooltip

### Anything else?

This seems most useful for custom format score, but I think may also be useful for the other "ineligible release" reasons

**Comment by markus101** [comment]
The rejection message should definitely show the scores like the logged messages should have. I don't think showing the file name is necessary because that's not the sole place CFs will be pulled from, but being able to show which CFs are from the existing source could also be useful.

**Comment by johnpyp** [comment]
I think the file names are very useful not because it’s the only place CF are coming from, but to be able to manually see which file you actually want. Basically I want to see at a glance whether or not my rules are handling the scenario correctly

**Comment by bakerboy448** [comment]
> I think the file names are very useful not because it’s the only place CF are coming from

eh it could be using scenetitle not necessarily filename ( a different discussion / issue) which would not at all be visible to the end user easily

**Comment by johnpyp** [comment]
Right, but for the most part I think the end user can tell whether or not the “import should happen” based on the file names alone, even if the actual scoring takes into account some other things. At the very least, I’d definitely want to see the filename even if it isn’t the full picture
