### ISSUE TITLE
Parsing support when season/episode is stated twice; ex. `ABC Season 2 S02E01 - 01 [DEF].mkv`

### ISSUE THREAD

**Issue by zwimer** [Sonarr/Sonarr#6338]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sonarr should be able to parse something like:
```
[SubsPlease] TSUKIMICHI -Moonlit Fantasy- Season 2 S02E01 - 01 [Web][MKV][h264][1080p][AAC 2.0][Softsubs (SubsPlease)][Episode 1]
```

Right now it fails with something like:
```
Debug|Parser|Parsing string '[SubsPlease] TSUKIMICHI -Moonlit Fantasy- Season 2 S02E01 - 01 [Web][MKV][h264][1080p][AAC 2.0][Softsubs (SubsPlease)][Episode 1]'
Debug|Parser|Episode Parsed. TSUKIMICHI -Moonlit Fantasy- Season 2 - S02E01 
...
Debug|ParsingService|No matching series TSUKIMICHI -Moonlit Fantasy- Season 2
```

Where as this works fine:
```
Debug|Parser|Parsing string '[OZR] TSUKIMICHI -Moonlit Fantasy- S01 [Blu-ray][MKV][h265 10-bit][1080p][FLAC 2.0][Dual Audio][Softsubs (OZR)]'
Debug|Parser|Episode Parsed. TSUKIMICHI -Moonlit Fantasy - Season 01 
...
Debug|CutoffSpecification|Comparing file quality with report. Existing file is WEBDL-1080p v2
```

### Describe the solution you'd like

If Sonarr cannot find the series `ABC Season 2`, it should attempt to find `Season 2` of the series `ABC`.

### Describe alternatives you've considered

Remove the items matching the regex `Season ?\d+` from a parsed series' title

**Comment by markus101** [comment]
Right now `Season 2` isn't part of the alias, but `S2` and `2nd Season` are.

https://thexem.info/xem/show/5224

But `Season 2` actually being part of the release name is common as shown in this screenshot from XEM:

https://thexem.info/xem/show/5224

So you can't simply remove that information and expect to get back the right thing in a number of other cases being accounted for.

This should be added as an alias, we're not going to try to overcome an established standard (as poor as it is) to guess at what things might be.

**Comment by thezoggy** [comment]
and additionally, the release is `[SubsPlease] Tsuki ga Michibiku Isekai Douchuu S2 - 01 (1080p) [0316510F]` which is why the alias exists and why it works. so your indexer is modifying the release name to make it invalid.. if your using prowlarr you prob have stuff set incorrectly to make the 'fake' name.
