### ISSUE TITLE
Clarify download client priority

### ISSUE THREAD

**Issue by nc7s** [Sonarr/Sonarr#6356]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The "client priority" setting in a download client's setting dialog does not clarify which direction the priority goes. As a comparison, indexers have this clarification.

### Describe the solution you'd like

Add description in `PriorityHelpText`, i18n. I can send in a PR, but needs confirmation of the direction (i.e. is 1 highest or lowest?).

### Describe alternatives you've considered

No?

**Comment by markus101** [comment]
It's the same as indexers, 1 is the highest priority.

https://github.com/Sonarr/Sonarr/blob/7e011df2b2c66ede0a0fbb3507a6ab89a7a08673/src/NzbDrone.Core/Download/DownloadClientProvider.cs#L93-L96

**Comment by stevietv** [comment]
this'd be a fine improvement.
It'd be best to rename the translation key to `DownloadClientPriorityHelpText` in [`frontend/src/Settings/DownloadClients/DownloadClients/EditDownloadClientModalContent.js`](https://github.com/Sonarr/Sonarr/blob/7e011df2b2c66ede0a0fbb3507a6ab89a7a08673/frontend/src/Settings/DownloadClients/DownloadClients/EditDownloadClientModalContent.js#L136) and the translation in `en.json` updated to be more inline with the IndexerPriorityHelpText

1 is highest priority. and 1 is the default priority

**Comment by nc7s** [comment]
I see that translations are synced from Weblate. Should I update the key only and submit translation updates there? Or is it OK to go for a direct change in code?

**Comment by markus101** [comment]
Only `en.json` should be updated, everything else comes from webplate.
