### ISSUE TITLE
Avoid too long target filenames under import

### ISSUE THREAD

**Issue by Morten242** [Sonarr/Sonarr#636]
When importing a file, if the filename (or full path) exceeds the max limit in the _target location_ then it'll silently throw an error and skip the file. A possible solution would be to truncate the target filename so that it fits but still contains the necessary details (S**E**).

Furthermore, manually moving the file in to its correct folder and then opening the organize and rename preview on that particular series will cause it to silently throw an error while continuing to look like it is loading.

OS: Windows (so, the entire 260 character full path etc.)

Example file:
Daily Lives of High School Boys ep 2 (whose full name is 209 characters long. That leaves 51 characters for the path..)

**Comment by markus101** [comment]
> Furthermore, manually moving the file in to its correct folder and then opening the organize and rename preview on that particular series will cause it to silently throw an error while continuing to look like it is loading.

Is there an error logged?

From an automation perspective we may be able to do something, but could cause issues if there is a parsing problem of the file and Sonarr sees a file thats really one episode, but tries to rename it as if it has multiple episodes (we've seen this happen before).

The fact that this is the episode title: `Morning Journey / Convex Mirror Girl / Friendship Power / Literary Girl 2 / Traditional Events / The Time of Childhood / Ghost Stories 2 / The Daily Life of a Lady` is absolutely crazy, it looks like there are 8 stories in that one episode...

**Comment by Morten242** [comment]
Yeah, it's a similar error to when it fails on importing:

"Request Failed: For lang bane eller for langt filnavn eller begge deler. Det fullstendig kvalifiserte filnavnet må ha færre enn 260 tegn, og mappenavnet må ha færre enn 248 tegn."
-- Basically that the full path needs to be less than 260 character and the folder needs to be less than 248 characters (I never liked that windows uses localized errors.)

With exception:
```System.IO.PathTooLongException: For lang bane eller for langt filnavn eller begge deler. Det fullstendig kvalifiserte filnavnet må ha færre enn 260 tegn, og mappenavnet må ha færre enn 248 tegn.
   ved System.IO.PathHelper.GetFullPathName()
   ved System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   ved System.IO.Path.GetFullPathInternal(String path)
   ved System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   ved System.IO.FileInfo..ctor(String fileName)
   ved NzbDrone.Common.Extensions.PathExtensions.CleanFilePath(String path) i m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Extensions\PathExtensions.cs:linje 30
   ved NzbDrone.Common.Extensions.PathExtensions.PathEquals(String firstPath, String secondPath) i m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Extensions\PathExtensions.cs:linje 43
   ved NzbDrone.Core.MediaFiles.RenameEpisodeFileService.<GetPreviews>d__c.MoveNext() i m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:linje 90
   ved System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   ved System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   ved System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   ved System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   ved NzbDrone.Core.MediaFiles.RenameEpisodeFileService.GetRenamePreviews(Int32 seriesId, Int32 seasonNumber) i m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:linje 70
   ved NzbDrone.Api.Episodes.RenameEpisodeModule.<>c__DisplayClassf.<GetEpisodes>b__b() i m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\Episodes\RenameEpisodeModule.cs:linje 36
   ved NzbDrone.Api.NzbDroneRestModule`1.ToListResource[TModel](Func`1 function) i m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\NzbDroneRestModule.cs:linje 37
   ved NzbDrone.Api.Episodes.RenameEpisodeModule.GetEpisodes() i m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\Episodes\RenameEpisodeModule.cs:linje 36
   ved NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__c(Object options) i m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\REST\RestModule.cs:linje 111
   ved CallSite.Target(Closure , CallSite , Func`2 , Object )
   ved Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)```

**Comment by gamicklisafisher** [comment]
For deletion or handling of long name i check that "Long Path Tool" software should be try, many articles refer this for such solutions.

**Comment by counterfit** [comment]
I've been running into this too, thanks to an exceptionally long episode name.

**Message**:
`Failed to properly rollback the file move [/Volumes/Plex/SABnzbd/Complete/TV/Clerks S01 E05 DVDrip X264-BUYMORE/Clerks S01 E05 DVDrip X264-BUYMORE.mkv] to [/Volumes/Plex/TV/Clerks/Season 1/Clerks - S01E05 - Dante and Randal and Jay and Silent Bob and a Bunch of New Characters and Lando, Take Part in a Whole Bunch of Movie Parodies Including But Not Exclusive To, The Bad News Bears, The Last Starfighter, Indiana Jones and the Temple of Doom, Plus a HS Reunion DVD.mkv], incomplete file may be left in target path.: Path is too long. Path: /Volumes/Plex/TV/Clerks/Season 1/Clerks - S01E05 - Dante and Randal and Jay and Silent Bob and a Bunch of New Characters and Lando, Take Part in a Whole Bunch of Movie Parodies Including But Not Exclusive To, The Bad News Bears, The Last Starfighter, Indiana Jones and the Temple of Doom, Plus a HS Reunion DVD.mkv `
**Exception**:
`System.IO.PathTooLongException: Path is too long. Path: /Volumes/Plex/TV/Clerks/Season 1/Clerks - S01E05 - Dante and Randal and Jay and Silent Bob and a Bunch of New Characters and Lando, Take Part in a Whole Bunch of Movie Parodies Including But Not Exclusive To, The Bad News Bears, The Last Starfighter, Indiana Jones and the Temple of Doom, Plus a HS Reunion DVD.mkv
  at System.IO.File.Delete (System.String path) [0x0007b] in /private/tmp/source-mono-mac-4.0.0-bug-33585-hotfix/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.4/mcs/class/corlib/System.IO/File.cs:166 
  at NzbDrone.Common.Disk.DiskProviderBase.DeleteFile (System.String path) [0x00068] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Disk\DiskProviderBase.cs:178 
  at NzbDrone.Common.Disk.DiskTransferService.RollbackPartialMove (System.String sourcePath, System.String targetPath) [0x00026] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Disk\DiskTransferService.cs:253 `

**Comment by markus101** [comment]
v3 will have long path support that was added in .net 4.6 I believe (as long as it's enabled in the OS).
