### ISSUE TITLE
Feature: Max custom format score of 10k

### ISSUE THREAD

**Issue by Ksdmg** [Sonarr/Sonarr#6370]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When I was setting up custom format scores, I set a specific rule to 10000 points. I didn't know that this was the hidden limit the score could reach

### Describe the solution you'd like

The UI should add limits and hints to the spin boxes under "Upgrade Until Custom Format Score" so you are aware of these limits.

### Describe alternatives you've considered

-

**Comment by fryfrog** [comment]
Scores over 10,000 or under -10,000 work fine for me. Can you show what you mean or where you see something that implies a limit of 10,000? I would suspect the limit is more likely to be what ever a .net signed integer is, if anything.

![Screenshot 2024-01-16 at 8 42 20 AM](https://github.com/Sonarr/Sonarr/assets/87748/eaaa8fb8-c35a-4ba6-bf5c-ebadeb60daeb)
![Screenshot 2024-01-16 at 8 41 34 AM](https://github.com/Sonarr/Sonarr/assets/87748/062db32d-90d4-4acc-9364-c47918b99694)

**Comment by Ksdmg** [comment]
And this is exactly where the issue is. I did set one format to exactly 10k points. When I searched for releases and already had one in the library, they would always show the error "Not an upgrade..." even if the computed custom score is above 10k and the current release is below.

**Comment by markus101** [comment]
The maximum limit for maximum custom format score on the backend is +/- 2,147,483,647, at 10,000 you could have over 214,000 items to hit that limit. Sonarr does not impose a artificial limit at 10,000 or other.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
