### ISSUE TITLE
Stop Auto Downloading on Transmission

### ISSUE THREAD

**Issue by ollie2a** [Sonarr/Sonarr#6373]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I just installed 4.0.0.748 and when a torrent is found, it is automatically sent to Transmission but contrary to Radarr, the torrent start downloading despite the fact that transmission deamon is set to pause the torrent. I used RPC to connect to the deamon. There must be something that Sonarr does differently to Radarr when submitting the torrent to Transmission. 

### Expected Behavior

I would be great if the torrent respect the deamon setting and does not start automatically downloading - I would want to manually trigger the download in the torrent client.

### Steps To Reproduce

Find an episode, 
click the button to transfer it to the torrent client
the torrent start to download automatically in transmission rather than being paused 

### Environment

```markdown
- OS: Ubuntu / Docker
- Sonarr: 4.0.0.748
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Main

### Trace Logs?

I dont have much logs .. 

2024-01-16 21:22:44.2|Info|DownloadService|Report sent to Transmission. Indexer SceneTime. Lupin S03E07 720p HEVC x265-MeGusta
2024-01-16 21:23:49.6|Info|DownloadService|Report sent to Transmission. Indexer SceneTime. Lupin S03E07 720p HEVC x265-MeGusta

**Comment by ollie2a** [comment]
gosh I found the settings in the transmission config on sonarr .. Add Paused ... sorry

**Comment by ollie2a** [comment]
Setting found using advanced setting under the transmission config in sonarr

**Comment by markus101** [comment]
And the issue related to this from searching that was closed over 6 years ago: https://github.com/Sonarr/Sonarr/issues/795

**Comment by ollie2a** [comment]
yeah .. found the feature by looking at the source code ... cheers for the reference
