### ISSUE TITLE
Error applying update using UI from v4.0.0.748 to v4.0.1.929 

### ISSUE THREAD

**Issue by khahlil** [Sonarr/Sonarr#6384]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Update logs show this message

`[v4.0.1.929] System.IO.IOException: No space left on device`

I have 8 GB free storage space

### Expected Behavior

Update Sonarr version to newest version using UI

### Steps To Reproduce

1. Fresh install Sonarr v4.0.0.748
2. Run Install Update using UI
3. Message complete
4. Reload browser
5. Not showing modal Update Success

### Environment

```markdown
- OS: Armbian 20.10 Bullseye
- Sonarr: v4.0.0.748
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome 120
- Database: Sqlite 3.34.1
```

### What branch are you running?

Main

### Trace Logs?

[UpdateLogs](https://hastebin.com/share/ebecabowex.bash)

### Anything else?

Re-running the installation script can fix this problem.

`wget -qO- https://raw.githubusercontent.com/Sonarr/Sonarr/develop/distribution/debian/install.sh | sudo bash`

Sonarr updated to newer version without lossing any data and settings.

**Comment by bakerboy448** [comment]
Not a sonarr bug that your /tmp ran out of space

**Comment by khahlil** [comment]
Maybe yes. But there is 1.2 GB free on tmpfs. Btw how much Sonarr need during update?

**Comment by bakerboy448** [comment]
the zip, the extracted zip, and the existing binaries - which would seem to total to more than 1.2gb

**Comment by khahlil** [comment]
Thanks, I'll increse it to 2.8 GB so this problem will not happen in the future update.
