### ISSUE TITLE
calendar - series w/ Collapse Multiple Episodes slightly offset height

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#6395]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

stuff with multi ep that cause the expand icon as the 3rd row, makes the div have a slightly different height than stuff that has the normal time.. see image

### Expected Behavior

be the same height regardless if its multi-ep or not

### Steps To Reproduce

look at calendar when there is a series with multiple episodes airing on the day vs one that doesnt, more visible when using full bg

### Environment

```markdown
- OS: unraid
- Sonarr: 4.0.1.953
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: firefox/chrome
- Database: sql
```

### What branch are you running?

Develop

### Trace Logs?

ui bug

### Anything else?

firefix 121.0.1 - light/dark full color or not
![image](https://github.com/Sonarr/Sonarr/assets/500882/4beffe9c-b8f8-4eed-9b64-f2d2ccd7243e)
![image](https://github.com/Sonarr/Sonarr/assets/500882/48ac963d-a625-4605-9c3a-1daff9adc175)

chrome 120.0.6099.225
![image](https://github.com/Sonarr/Sonarr/assets/500882/6169772f-d2c1-4f9b-91b8-82e72851bd2c)

**Comment by markus101** [comment]
It's because the icon isn't as tall as the text, 14px vs 18.33px. Not really a bug...

**Comment by thezoggy** [comment]
i mean you dont expect each calendar entry to be the same height? i would have thought the whole reason of doing the collapse icon is so you could get it to be the same as others..
