### ISSUE TITLE
Application crashes frequently

### ISSUE THREAD

**Issue by murrayju** [Sonarr/Sonarr#640]
Just about any time I go to look at the webapp, I find that it has crashed and must be restarted on the server.

I'm running Ubuntu 14.04.2, and followed the instructions on the wiki (including installing mono).
```
$ mono --version
Mono JIT compiler version 3.10.0 (tarball Wed Nov  5 12:50:04 UTC 2014)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
```

**Comment by murrayju** [comment]
I have a hunch that it may be related to processing completed downloads, but I have no evidence. Let me know where I might find some log files with a stack trace or something that might help.

**Comment by markus101** [comment]
Please use the forums for support, but its likely this issue (stickied on the forums): https://forums.sonarr.tv/t/native-mono-crashes-kernel-fix-released/4985
