### ISSUE TITLE
Add Custom Format Language Helptext

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#6408]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Add to the UI description that the condition looks at all languages detected in the file as a contains 

### Describe the solution you'd like

See above 

### Describe alternatives you've considered

N/a 

### Anything else?

Ux improvement

**Comment by markus101** [comment]
Has there been some confusion with this? AKA, what problem does this solve since you put the solution in the problem field.

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/issues/9669#issuecomment-1904228497
