### ISSUE TITLE
Pushbullet Channel Support

### ISSUE THREAD

**Issue by M0UL** [Sonarr/Sonarr#641]
add support for pushbullet channels, for easy sort of notications like coachpato does.

**Comment by markus101** [comment]
What benefit would this add to Sonarr? What do you mean by "easy soft of notifications"?

**Comment by M0UL** [comment]
the way in currently is that sonarr notification get placed in the everything section, if it supports channels then it gets its own section.  see screenshot
http://prntscr.com/7limbn

**Comment by halkeye** [comment]
are pushbullet channels not super public? IS there a way to lock them down at all now?

**Comment by markus101** [comment]
If its not featured you need to know the tag for the channel, not secure, but also not public. It'd be awesome to be able to make them private, but I'm not sure if they are planning to do that (I will ask though).

**Comment by markus101** [comment]
Looks like the channel tag will accept dashes, so its pretty painless to create a unique channel using a GUID.
