### ISSUE TITLE
Daily Episode Search Date Adjustment/Offset

### ISSUE THREAD

**Issue by pantaryl** [Sonarr/Sonarr#6411]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

For certain daily shows that air between 00:00 and 01:00, some broadcast networks label the show as occurring the day before (airs at 00:30 on Jan 17, the broadcaster would say it airs on Jan 16).

The scene often follows the broadcaster, which then leads to a discrepancy in Sonarr.

### Describe the solution you'd like

When adding a new daily series or editing a daily series, it would be nice to have a "Search Date Adjust" which allows for a +/- of a specific number of days. Chances are we only need +/- 1 day.

When a daily episode is searched, the date adjustment would be applied before the date is searched. For example, if the episode were to air at 00:30 on January 24rd and you had a -1 day adjustment applied, the search  would instead look like this:
![image](https://github.com/Sonarr/Sonarr/assets/2659753/ca5c40a9-0ca1-4a26-80d7-2391dd49c4bc)

It might be worthwhile, if that search is not fruitful, to then search the normal date provided from TVDB without any adjustment.

### Describe alternatives you've considered

Currently this mismatch can be rectified by fighting on TVDB about the actual air date or manually downloading episodes. Since the automatic search/indexer will search with the actual date, it means we're often missing files for quite a while.

If TVDB supported a 25-hour time, with episodes airing at 00:00 or 00:30 being allowed to selection 24:00 and 24:30, respectively, that may also help.

### Anything else?

Late night shows are hit by the the most, as the broadcasters (and therefore the scene) consider them airing the night of X at 24:30, when they really air on X+1 at 00:30.

The current show I'm seeing this with is After Midnight (CBS).

**Comment by thezoggy** [comment]
have you tried opening a ticket with tvdb about correcting the data?

**Comment by pantaryl** [comment]
> have you tried opening a ticket with tvdb about correcting the data?

I've edited the data myself at times to reflect Jan 16th. 

> first episode was on the 16th not the 17th?

But it truly aired the "night" of Jan 16, or 00:30 on Jan 17, which leads folks to continue to change it back on TVDB.

I can raise a ticket to try to get things locked down?

**Comment by markus101** [comment]
Due to how broadcasting days typically operate TheTVDB has in the past had these episodes listed as airing at 24:00 for midnight or 24:30 for 12:30am, which Skyhook properly accounts for already.

If their stance has changed or users aren't following those rules then Skyhook would need to be updated, but a ticket with them is the first step.

Closing this as it doesn't apply to Sonarr directly if they end up saying things have changed then it'd be best to discuss further on Discord (where this topic has recently been discussed).

**Comment by pantaryl** [comment]
> Due to how broadcasting days typically operate TheTVDB has in the past had these episodes listed as airing at 24:00 for midnight or 24:30 for 12:30am, which Skyhook properly accounts for already.

If you have a moment, could you link me to an example? Looking at what I can edit for a series myself, I do not see 24:00 or 24:30 as options. If you have an example, that would help me provide an example to the TVDB admins.

Thanks!

**Comment by markus101** [comment]
I looked for some, but it looks like they are old out of date series. The Late Late Show With James Corden was one that came to mind, but it's data on TheTVDB aligns with the releases (Season 8 Episode 1 aired on 2022-09-06 and the releases use that same date).

**Comment by pantaryl** [comment]
Yeah, that's unfortunate. Without either the scene changing how they report this series or TVDB changing its rules/reporting, I suspect this show will just have to be handled manually by users for the time being.

**Comment by kevinrenskers** [comment]
I'm running into the same problem with After Midnight, where the episodes don't download correctly. I was also searching for some kind of date offset, would be a good feature to have in case TVDB data is incorrect/inconsistent with what's on Usenet.
