### ISSUE TITLE
Parity with Radarr's IMDB List functionality

### ISSUE THREAD

**Issue by madAndroid** [Sonarr/Sonarr#6412]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I can add an IMDB watchlist to Radarr, for different types - lists prefixed with `ls`, or user watch lists prefixed with `ur` - with Sonarr (`4.0.1.953`), I can only add lists prefixed with `ls` - it would be great if both systems functioned in the same way

### Describe the solution you'd like

To be able to add different types of lists, not just `ls` prefixed lists

### Describe alternatives you've considered

Linking several different systems to have the shows synced into Sonarr

### Anything else?

The functionality already exists in Radarr, so it should be possible to replicate it from there

**Comment by markus101** [comment]
What do those prefixes mean?
Is there a difference in the output or are they interchangeable?

**Comment by madAndroid** [comment]
> What do those prefixes mean? Is there a difference in the output or are they interchangeable? Do you gave a user watch list you can share for testing?

If a user adds items to their watchlist, they're added to an list prefixed with `ur`, this needs to be shared publicly in order to be visible to Radarr - an example for testing is: `ur174993069` - and here's a screenshot from Radarr:

<img width="500" alt="2024-01-23_07-35-53" src="https://github.com/Sonarr/Sonarr/assets/1321437/ad6be3d0-9b1a-43ed-88d4-e86bca7cbff3">

The lists prefixed with `ls` are user created lists, as far as I know

**Comment by markus101** [comment]
I've discussed this with Qstick and the issue issue these lists don't have an easily accessible export, but it is possible to find the `ls` list that is backing the `ur` list:

 https://www.reddit.com/r/radarr/comments/7pdk66/how_to_add_an_imdb_watchlist_in_radarr/

We do not have plans to add ur -> ls list conversions to Sonarr or it's public APIs.

**Comment by madAndroid** [comment]
Okay, thanks - that's a bit annoying, but okat because there are workarounds.. btw, the article linked above is 6 years old, here's a more recent one showing how to find the `ls` equivalent of a `ur` watchlist: https://www.reddit.com/r/sonarr/comments/174fccz/comment/k490vty/?context=3
