### ISSUE TITLE
Health Check Indexer Improvement Suggestion

### ISSUE THREAD

**Issue by BeardMatt** [Sonarr/Sonarr#6417]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

With *arr supporting multiple indexers, there's almost one indexer that always temporarily has a small outage. This causes *arr to send an email alert informing you one 1 out of 7 indexers had a small outage blip.

### Describe the solution you'd like

Have an option to only send an email if ALL indexers are down. The health check on indexers is almost worthless because I wake up to about 100 emails from various sites flapping all night, but it's never really a problem as there are several backup indexers and 99% of the time by the next check the site comes back as healthy anyway. Or, maybe have an option that says only alert if an indexer doesn't go back green after x amount of health checks?

### Describe alternatives you've considered

Disabling health alerts altogether dude to becoming desensitized to the alerts.

**Comment by markus101** [comment]
Notifications for health checks are all or none and at this time we don't have plans to make them more granular than that. Sonarr already has logic to increasingly back off the time between attempts when indexers are continually down.

**Comment by idolize** [comment]
It would be great to at least get an option to keep health check alerts but disable indexer health check alerts because they do generate _a lot_ of noise
