### ISSUE TITLE
DownloadStation: No default destination returned via API

### ISSUE THREAD

**Issue by DChiuch** [Sonarr/Sonarr#6421]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I can't add Download Station as a download client, it comes up with the following error:
DownloadClientDownloadStationValidationNoDefaultDestination

It was working fine until I reinstalled Download Station in Synology DSM. The default destination is definitely set in Download Station and Sonarr has access to that directory.

### Expected Behavior

I should be able to add Download Station as a download client.

### Environment

```markdown
- OS: Running through Container Manager on latest Synology DSM
- Sonarr: 4.0.1.929
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: N/A (not UI related)
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

2024-01-25 13:42:43.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- TvDirectory: DownloadClientDownloadStationValidationNoDefaultDestination

**Comment by markus101** [comment]
One line with the warning is not sufficient, please post the relevant trace logs and link them here.

**Comment by DChiuch** [comment]
> One line with the warning is not sufficient, please post the relevant trace logs and link them here.

My mistake, here you go:

> 2024-01-25 14:38:03.5|Trace|Http|Req: 1851 [POST] /api/v3/downloadclient/test (from 192.168.50.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
> 2024-01-25 14:38:03.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
> 2024-01-25 14:38:03.5|Debug|TorrentDownloadStation|Download Station api version information: Min 1 - Max 2
> 2024-01-25 14:38:03.5|Trace|HttpClient|Req: [GET] http://192.168.50.223:5000/webapi/DownloadStation/info.cgi?_sid=SM7tuhIdlEh4966nkORwekxem0Gg5ko1w86j0Fb3158FdiSt5e-HdKuy23fjKRGumMF_7CzUFmqEU1b_jOzfNY&api=(removed)&version=1&method=getConfig
> 2024-01-25 14:38:03.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
> 2024-01-25 14:38:03.5|Trace|HttpClient|Res: HTTP/1.1 [GET] http://192.168.50.223:5000/webapi/DownloadStation/info.cgi?_sid=SM7tuhIdlEh4966nkORwekxem0Gg5ko1w86j0Fb3158FdiSt5e-HdKuy23fjKRGumMF_7CzUFmqEU1b_jOzfNY&api=(removed)&version=1&method=getConfig: 200.OK (286 bytes) (66 ms)
> 2024-01-25 14:38:03.5|Trace|HttpClient|Response content (286 bytes): {"data":{"bt_max_download":0,"bt_max_upload":20,"default_destination":null,"emule_default_destination":null,"emule_enabled":false,"emule_max_download":0,"emule_max_upload":20,"ftp_max_download":0,"http_max_download":0,"nzb_max_download":0,"unzip_service_enabled":false},"success":true}
> 
> 2024-01-25 14:38:03.5|Debug|DownloadStationInfoProxy|Trying to get config
> 2024-01-25 14:38:03.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
> 2024-01-25 14:38:03.5|Trace|HttpClient|Req: [GET] http://192.168.50.223:5000/webapi/entry.cgi?_sid=SM7tuhIdlEh4966nkORwekxem0Gg5ko1w86j0Fb3158FdiSt5e-HdKuy23fjKRGumMF_7CzUFmqEU1b_jOzfNY&api=(removed)&version=1&method=list&additional=detail
> 2024-01-25 14:38:03.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
> 2024-01-25 14:38:03.5|Trace|HttpClient|Res: HTTP/1.1 [GET] http://192.168.50.223:5000/webapi/entry.cgi?_sid=SM7tuhIdlEh4966nkORwekxem0Gg5ko1w86j0Fb3158FdiSt5e-HdKuy23fjKRGumMF_7CzUFmqEU1b_jOzfNY&api=(removed)&version=1&method=list&additional=detail: 200.OK (56 bytes) (12 ms)
> 2024-01-25 14:38:03.5|Trace|HttpClient|Response content (56 bytes): {"data":{"offset":0,"task":[],"total":0},"success":true}
> 2024-01-25 14:38:03.5|Debug|DownloadStationTaskProxyV2|Trying to get tasks with additional detail
> 2024-01-25 14:38:03.6|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IDownloadClient>
> 2024-01-25 14:38:03.6|Trace|SonarrErrorPipeline|Handling Exception
> 2024-01-25 14:38:03.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
>  -- TvDirectory: DownloadClientDownloadStationValidationNoDefaultDestination
> 2024-01-25 14:38:03.6|Trace|Http|Res: 1851 [POST] /api/v3/downloadclient/test: 400.BadRequest (104 ms)
> 2024-01-25 14:38:03.6|Debug|Api|[POST] /api/v3/downloadclient/test: 400.BadRequest (104 ms)
> 2024-01-25 14:38:06.4|Trace|Http|Req: 1852 [GET] /logfile/sonarr.trace.txt (from 192.168.50.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)

**Comment by DChiuch** [comment]
I see that Download Station is returning its default_destination as null, but it's definitely set within Download Station:

<img width="516" alt="image" src="https://github.com/Sonarr/Sonarr/assets/6777430/6ce49617-de07-4260-b11a-7da891f28881">

And torrents that I download manually in Download Station are working correctly and being put in that directory.

**Comment by markus101** [comment]
Unfortunately since DownloadStation doesn't return that path to Sonarr it's unable to use it. This seems like it could be a bug on the Synology side, but I'm unable to reproduce with DownloadStation 3.9.3-4609 on DSM 7.1.1-42962 Update 6.

Since DS isn't returning the default path you can specify the same path in Sonarr's DS `Directory` setting.

**Comment by DChiuch** [comment]
> Unfortunately since DownloadStation doesn't return that path to Sonarr it's unable to use it. This seems like it could be a bug on the Synology side, but I'm unable to reproduce with DownloadStation 3.9.3-4609 on DSM 7.1.1-42962 Update 6.
> 
> Since DS isn't returning the default path you can specify the same path in Sonarr's DS `Directory` setting.

I'm on DSM 7.2-64570 Update 1 and Download Station 4.0.1-4709, maybe it was introduced later. Or maybe it only happens when you uninstall and reinstall Download Station from the Package Center like I did, since it was working fine before I did that.

I'm having trouble with your workaround though, if I fill out the Directory setting then I still get the same error:

<img width="498" alt="image" src="https://github.com/Sonarr/Sonarr/assets/6777430/fefd0337-d816-46ce-bfad-0c98a31fd203">

> 2024-01-25 17:32:37.5|Trace|Http|Req: 4155 [POST] /api/v3/downloadclient/test (from 192.168.50.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
> 2024-01-25 17:32:37.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
> 2024-01-25 17:32:37.5|Debug|TorrentDownloadStation|Download Station api version information: Min 1 - Max 2
> 2024-01-25 17:32:37.5|Trace|HttpClient|Req: [GET] http://192.168.50.223:5000/webapi/DownloadStation/info.cgi?_sid=SM7tuhIdlEh4966nkORwekxem0Gg5ko1w86j0Fb3158FdiSt5e-HdKuy23fjKRGumMF_7CzUFmqEU1b_jOzfNY&api=(removed)&version=1&method=getConfig
> 2024-01-25 17:32:37.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
> 2024-01-25 17:32:37.5|Trace|HttpClient|Res: HTTP/1.1 [GET] http://192.168.50.223:5000/webapi/DownloadStation/info.cgi?_sid=SM7tuhIdlEh4966nkORwekxem0Gg5ko1w86j0Fb3158FdiSt5e-HdKuy23fjKRGumMF_7CzUFmqEU1b_jOzfNY&api=(removed)&version=1&method=getConfig: 200.OK (286 bytes) (45 ms)
> 2024-01-25 17:32:37.5|Trace|HttpClient|Response content (286 bytes): {"data":{"bt_max_download":0,"bt_max_upload":20,"default_destination":null,"emule_default_destination":null,"emule_enabled":false,"emule_max_download":0,"emule_max_upload":20,"ftp_max_download":0,"http_max_download":0,"nzb_max_download":0,"unzip_service_enabled":false},"success":true}
> 
> 2024-01-25 17:32:37.5|Debug|DownloadStationInfoProxy|Trying to get config
> 2024-01-25 17:32:37.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
> 2024-01-25 17:32:37.5|Trace|HttpClient|Req: [GET] http://192.168.50.223:5000/webapi/entry.cgi?_sid=SM7tuhIdlEh4966nkORwekxem0Gg5ko1w86j0Fb3158FdiSt5e-HdKuy23fjKRGumMF_7CzUFmqEU1b_jOzfNY&api=(removed)&version=1&method=list&additional=detail
> 2024-01-25 17:32:37.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
> 2024-01-25 17:32:37.6|Trace|HttpClient|Res: HTTP/1.1 [GET] http://192.168.50.223:5000/webapi/entry.cgi?_sid=SM7tuhIdlEh4966nkORwekxem0Gg5ko1w86j0Fb3158FdiSt5e-HdKuy23fjKRGumMF_7CzUFmqEU1b_jOzfNY&api=(removed)&version=1&method=list&additional=detail: 200.OK (56 bytes) (12 ms)
> 2024-01-25 17:32:37.6|Trace|HttpClient|Response content (56 bytes): {"data":{"offset":0,"task":[],"total":0},"success":true}
> 2024-01-25 17:32:37.6|Debug|DownloadStationTaskProxyV2|Trying to get tasks with additional detail
> 2024-01-25 17:32:37.6|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IDownloadClient>
> 2024-01-25 17:32:37.6|Trace|SonarrErrorPipeline|Handling Exception
> 2024-01-25 17:32:37.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
>  -- TvDirectory: DownloadClientDownloadStationValidationNoDefaultDestination
> 2024-01-25 17:32:37.6|Trace|Http|Res: 4155 [POST] /api/v3/downloadclient/test: 400.BadRequest (139 ms)
> 2024-01-25 17:32:37.6|Debug|Api|[POST] /api/v3/downloadclient/test: 400.BadRequest (139 ms)
> 2024-01-25 17:32:39.6|Trace|Http|Req: 4156 [GET] /logfile/sonarr.trace.txt (from 192.168.50.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)

**Comment by stevietv** [comment]
when you hover over the (i) it shows you this additional details:
```You must login into your Diskstation as {Username} and manually set it up into DownloadStation settings under BT/HTTP/FTP/NZB -> Location.```
Is this also set?

@markus101 - looking at this test it seems that we always require default_dir to be set, even if using an override dir:
https://github.com/Sonarr/Sonarr/blob/9a870a37090bfb5dfcf26bc4108c767614c163e7/src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs#L193-L227

i.e. the test exits with the validationfailure when its not set before going on to check the manual destination. I think that we could remove the first `if` completely and still validate ok. Looking at GetDownloadDirectory() it appears that we expect Either a default_dir + category or a manually set path.

**Comment by DChiuch** [comment]
@stevietv That's totally it, I didn't realise that the default directory was set on a per user basis. Thanks.

**Comment by markus101** [comment]
Oh, I missed the user requirement because I only had the one on my test device.

@stevietv good catch, we definitely shouldn't require the default directory if the directory is set.

**Comment by stevietv** [comment]
> @stevietv good catch, we definitely shouldn't require the default directory if the directory is set.

I'll PR it in
