### ISSUE TITLE
Manual Import: Multi-Episode selection disabled for specials

### ISSUE THREAD

**Issue by salomj** [Sonarr/Sonarr#6429]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Multi-Episode selection is disabled in certain cases

### Expected Behavior

I should always be allowed to multi-episode select. This was allowed before I upgrade to the latest version, please bring it back. It makes it really hard to manage certain series which have 100+ specials.

I last upgraded at the end of November, before upgrading to the latest version.

### Steps To Reproduce

1) Go to any series that has specials
2) Select 3 episodes and set their season to "Season 0" or "Specials"
3) Attempt to multi-select which episode they are
4) Notice that is is not possible and "Select Episodes" is disabled

![86](https://github.com/Sonarr/Sonarr/assets/23242186/90f46518-9ce1-4750-b141-f750e75dc8dd)

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-1044-raspi aarch64)
- Sonarr: 4.0.1.929-ls222 by linuxserver.io
- Docker Install: Yes
- Docker Image: https://hub.docker.com/layers/linuxserver/sonarr/arm64v8-4.0.1/images/sha256-ff8aa2b28a916fb08925a7e60ee886946c93e8a5ebea43d4a13f520e0d363a4c?context=explore
- Using Reverse Proxy: No
- Browser: Chrome 120.0.6099.225
- Database: Sqlite
```

### What branch are you running?

Main

### Trace Logs?

Really don't think it will be useful, but it is required to open the ticket.
[trace.txt](https://github.com/Sonarr/Sonarr/files/14069497/trace.txt)

**Comment by markus101** [comment]
Does this only happen if season 0 is selected?

**Comment by salomj** [comment]
> Does this only happen if season 0 is selected?

I see 2 cases where this happens, when it didn't used to:
- If any episode selected is from season 0.
- If any episode selected does not have an assigned season.

Seems to work fine when selecting episode across multiple seasons.
