### ISSUE TITLE
Refresh updated images in metadata

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#643]
Currently we don't update the images used for metadata when the images change (but we do update the images shown in the UI).

We shouldn't blindly update the images (we don't want to alter files on every rescan), but should have a hash/details on the file to compare.

**Comment by typhoe** [comment]
Thank!

And maybe the nfo should also be included, not only the images (description of the show can also change).

**Comment by markus101** [comment]
The nfo is already updated.

**Comment by typhoe** [comment]
Ok, perfect already then!

**Comment by M0UL** [comment]
any news for this?

**Comment by typhoe** [comment]
@markus101 Would it be possible to add an action "Force write images to disk from sonarr database" to launch manually at will? Thanks!

**Comment by thezoggy** [comment]
the same goes for nfo generation.. you re-write them on each update.. thus making a lot of uneeded disk io on a nas

**Comment by alxlaxv** [comment]
A really need that :)

**Comment by bakerboy448** [comment]
This bug/issue seems stale.  Please check and see if it is still an issue on the recent v3 builds.  If it is an issue please open a new GHI with logs and full detail.
