### ISSUE TITLE
Bring Back Score

### ISSUE THREAD

**Issue by salomj** [Sonarr/Sonarr#6430]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

"Custom Formats" is terrible, bring back "Score", it was way easier to manage and way less confusing.

Not Sure how this is better than "Score" on "Profiles":
![CustomFormat](https://github.com/Sonarr/Sonarr/assets/23242186/47440a60-dd80-4103-a3ad-f8e6c23440f6)
![CustomFormat2](https://github.com/Sonarr/Sonarr/assets/23242186/37e58fde-e606-41f7-9909-7dae9b1b6011)
![Release Profile](https://github.com/Sonarr/Sonarr/assets/23242186/29ffa351-598c-45db-a05a-e73bfd81c923)

### Describe the solution you'd like

Bring back "Score" on "Release Profiles". "Score" was all in one place, was way less messy, and made sense. This "Custom Format" doesn't even have an option for determining which values are higher preference than other values. Also, now I have no way of adjusting episode "Scores" anymore, even though it is clear that episodes still have score values.

![86](https://github.com/Sonarr/Sonarr/assets/23242186/142ad8a1-c0eb-4c18-a157-17787158ffc6)

### Describe alternatives you've considered

The alternative is reverting to a previous release that supports "Score". I was previously using a release from late November which supported this feature.

The other alternative is to disable Sonarr from managing titles and importing everything manually.

You don't have any alternative solutions in the current release, you removed "Score" from "Release Profiles" and "Custom Formats" does not have parity with "Score". Also "Score" was way better and significantly less confusing.

**Comment by stevietv** [comment]
your old preferred words from v3 don't migrate too well to v4, you should better remove them all and remake them as custom formats. Sonarr won't be reverting to preferred words.

Trash Guides has some guides on Custom Formats.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by salomj** [comment]
Trash guide still shows score being used.

https://trash-guides.info/Radarr/radarr-setup-quality-profiles-anime/

**Comment by PearsonFlyer** [comment]
Yes, that's because scores are still used. They're on your quality profile after you add custom formats.
