### ISSUE TITLE
Option to skip the episode-by-episode search

### ISSUE THREAD

**Issue by jojolll** [Sonarr/Sonarr#6435]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues
Related to #1128 (same feature), but since the issue is closed, I'll take the liberty of opening a new one.

### Is your feature request related to a problem? Please describe

Hello,

When using some torrent indexers for anime, the search by episode is very annoying and does not bring anything more than the first requests. 

For example on my main indexer, the answer takes almost 30 seconds to arrive PER REQUEST and I can be IP BAN if I spam the indexer (Cloudflare & flaresolver + Ratelimit). Here's an example for My Hero Acadamia S04 (typical anime). 
Sonarr 4.0.1.987 will search for (non-exhaustive list): 
- "Boku"+"no"+"Hero"+"Academia" (Main Title)
- "My"+"Hero"+"Academia" (Alt Titles)
- ...
- "Boku"+"no"+"Hero"+"Academia"+"S04E01"
- "My"+"Hero"+"Academia"+"S04E01"
- Many more request per episode
- ... ... ... 
- "Boku"+"no"+"Hero"+"Academia"+"S04E25"
- "My"+"Hero"+"Academia"+"S04E25"

Here is a screenshot of the prowlarr queries just for the S04E05 search in my S04 request:
![image](https://github.com/Sonarr/Sonarr/assets/26553241/452a84f6-030a-4a5a-a9f1-f0300a0043e8)

It's 13 queries PER EPISODE, my season has 25 episodes, which makes more than 350 queries in total S04 (or 2000 indexer queries for the entire anime).

I have the impression that each query is parralellized with one or two others, but it still takes almost 20 minutes to get all the results for the 350 queries, and it's impossible to do an interactive search on anime (UI will timeout, I launched my automatic search for S04 at 1:05 pm, and the download started at 1:23 pm...).

### Describe the solution you'd like

For me, the real problem with not having this option is that in some cases, like torrents, there's NO added value to a search by episode. 

If Sonarr could only perform the "Main Title" and "Alt Titles" queries, from most indexers it would get ALL the results for the series, including all seasons, all episodes, all season packs... 
![image](https://github.com/Sonarr/Sonarr/assets/26553241/494db963-7409-4b86-81b3-ac07ee0ca464)
In my example, in two minutes and 15 requests to my indexer, it would have found exactly the season 4 release it downloaded after 20 minutes of useless searching episode by episode.

Even if there had been no season pack in the results, all the results episode by episode would still have been listed by the indexer's response.

### Describe alternatives you've considered

I would have liked to be able to modify the behavior myself on my instance, but I don't think that's possible, and what's more, it would be useful for a lot of people.

### Anything else?

I'll take this opportunity to add that despite the 'My Hero Academia S5' listing in the Prowlarr search text, the actual query is '"My "+"Hero "+"Academia', without the S05. I found this strange, but maybe it's out of Sonarr?
![image](https://github.com/Sonarr/Sonarr/assets/26553241/4306cd19-61c5-4b99-9d15-874cdae9367a)

**Comment by bakerboy448** [comment]
- anime series type has no concept of season packs
- Series packs are not supported
- Searching for just the series will likely mean missed results as with pagination only up to 1000 results are gotten per indexer.   Of note very few indexers in prowlarr and jackett support pagination making this problem even worse

**Comment by jojolll** [comment]
"anime series type has no concept of season packs"

Since V4 I no longer have a problem downloading season packs on Anime with this indexer option:
![image](https://github.com/Sonarr/Sonarr/assets/26553241/e3435804-d1b1-4773-abf4-f118e78c0a5a)


After the 350 requests, Sonarr chose a season pack:
![image](https://github.com/Sonarr/Sonarr/assets/26553241/4e39d80c-735e-48fa-91c7-6b618e1901d6)

**Comment by bakerboy448** [comment]
For that series given it appears to be standard format it appears you have it set to the wrong series type

**Comment by jojolll** [comment]
This is indeed a misinterpretation on my part. I thought that the option to search for anime like standards allowed them to be managed as such. But that only adds one layer to the anime search ?

Overseer does not give you a choice and imports animated series in anime type on Sonarr. Since it is obviously the "real type" of the serie and since V4 Sonarr has been downloading the season packs, I thought it was good.
