### ISSUE TITLE
Discord notification for complete seasons

### ISSUE THREAD

**Issue by nakda** [Sonarr/Sonarr#6436]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes, you don't want to start watching a season until it's complete because you don't like waiting every week for an episode to air. 

Discord notifications can be triggered when an episode is imported, but it doesn't tell you if the season is complete (all episodes downloaded). As Sonarr's admin of my own instance, I can go and check if all episodes are there (fastidious, but I can), but other users have to ask me or check on Plex how many episodes there are while looking online for how many episodes there should be.

### Describe the solution you'd like

The best solution would be to get a Discord notification only when all episodes of a season have been imported. To clarify, I'm not talking about a season pack being imported (even tough the condition would be met and a notification fired), but when Sonarr finally downloads the last missing episode either because it was aired recently or because one episode was slow to download/hard to find. It doesn't matter: as soon as we have all episodes for a season, fire the notification.

Another acceptable solution, probably easier to implement (idk), would be to add a "season progress" field on the existing "import" event. For example: an episode is imported and the associated notification contains a "03/10" meaning we have only imported 3 episodes out of 10 so far (so, episodes are missing).

### Describe alternatives you've considered

Writing a custom script executed everytime an episode is added, to get the related information via Sonarr's API and checking how many episode the season it belongs to contains, and how many are downloaded (`totalEpisodeCount` vs `episodeFileCount`).

### Anything else?

Obviously, false-positive "complete season" notification can be fired if Sonarr thinks there should be only 2 episodes just because the season metadata are not ready yet. But my guess it those would be rare, especially because the file themselves are proably not available online yet.

**Comment by stevietv** [comment]
This is likely not going to be supported. How would it work for shows that don't have all their episodes added yet to TVDB, there would be multiple times that it'd trigger.

**Comment by nakda** [comment]
I understand that "invalid" notifications can be an issue for some, even tough I would personally be ok with that considering it shouldn't happen too often. 

What about the alternative solution of providing extra fields to the existing event, so that anyone can decide to rely on it or not?

**Comment by markus101** [comment]
A custom script or we hook would definitely be the way to do this so you can customize it as much as you want.

I wouldn't be opposed to sending the Finale Type (when set on TheTVDB), as part of the notifications so the logic could potentially be handled without having to use the API, but sending a separate event is not something we're going to do, nor do we have filtering on the events already being sent.

**Comment by nakda** [comment]
Regarding the Finale Type, it won't always fit my request because sometimes the final episode of a season can be imported while some others are still missing. If we were only waiting for the final episode to air though, I see where it can help.

I consider I got my answer and I will implement the requested behavior via custom script, so I guess I can close the issue.

Thank you the really quick feedback.
