### ISSUE TITLE
Ignore 'Other' Directory

### ISSUE THREAD

**Issue by salomj** [Sonarr/Sonarr#6437]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The problem is that Sonarr will attempt to match files in the `Other` directory which is annoying when auto-importing a series, and also makes it messy when trying to manually import a series.

### Describe the solution you'd like

I would like it if Sonarr ignored all of Plex's `Extras` directories. It seems to ignore all of them by default excluding `Other`.

### Describe alternatives you've considered

It would also be nice if you could override what sonarr excludes with something like a `.sonarrignore` file, similar to how plex has a `.plexignore` file, which works similar to a `.gitignore` file.

### Anything else?

- https://support.plex.tv/articles/local-files-for-trailers-and-extras/
- https://support.plex.tv/articles/201381883-special-keyword-file-folder-exclusion/

The directory 'Other' is one of the directories supported by plex for adding videos associated with a TV Show/Movie, but does not fit in with Seasons/Specials.

Plex Supports the Following Folders:
- Behind The Scenes
- Deleted Scenes
- Featurettes
- Interviews
- Scenes
- Shorts
- Trailers
- Other

And the following postfixes:
- -behindthescenes
- -deleted
- -featurette
- -interview
- -scene
- -short
- -trailer
- -other

Plex also ignores anything in the `extras`, `samples`, `bonus`, and `bonus disc` folders by default.

It is worth noting that the folders and files which are not `Extras` show up as `Extras` in plex. 
![image](https://github.com/Sonarr/Sonarr/assets/23242186/a8122788-d979-4279-9192-45cf52d9ad3c)
![image](https://github.com/Sonarr/Sonarr/assets/23242186/097557b4-3d98-433b-899c-045285e0e0ad)
![image](https://github.com/Sonarr/Sonarr/assets/23242186/e674e9ee-3aa5-4716-804b-4137f7118f9d)

**Comment by stevietv** [comment]
seems reasonable to add it to https://github.com/Sonarr/Sonarr/blob/70807a9dcf0fbbd39768779ec8b416c78e6804f8/src/NzbDrone.Core/MediaFiles/DiskScanService.cs#L72
