### ISSUE TITLE
Add Max Length for `{Series CleanTitle}` and `{Episode CleanTitle}`

### ISSUE THREAD

**Issue by salomj** [Sonarr/Sonarr#6438]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Plex really does not like extremely long names, and animes are notorious for having very long episode names and series names. When both of those are combined, plex will often fail to find entire seasons or even an entire series.

### Describe the solution you'd like

It would be nice if sonarr had some max length capabilities per field. I could see something like `{Series CleanTitle:64}` or a seperate text box for setting maximum length on at least `CleanTitle`. 

### Describe alternatives you've considered

Manually renaming each episode, and maybe adding a checkbox to tell sonarr to never rename specific episodes/series, because I am a dummy and will sometimes tell sonarr to rename everything and run into this problem once again.

**Comment by stevietv** [comment]
already in #6424 and a dupe of #6416

**Comment by salomj** [comment]
Looks like this is actually a duplicate of https://github.com/Sonarr/Sonarr/issues/6416 . I'm just bad at searching.
