### ISSUE TITLE
Add Custom Name to Series and Episodes

### ISSUE THREAD

**Issue by salomj** [Sonarr/Sonarr#6439]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes TVDB picks the worst possible name for a series or episode, when those series/episodes have better or more appropriate names.  

### Describe the solution you'd like

I would like to see the ability in `Edit Series` and when you double-click an episode title, the ability to edit their names.

### Describe alternatives you've considered

An alternative might be a drop down for using alternative names, as it seem that Sonarr does have all the alternative names for the series listed.

### Anything else?

This would also help for the handful of Series I have which have the same title and were created the same year.

**Comment by thezoggy** [comment]
sonarr has a process for all of this, 
https://forums.sonarr.tv/t/scene-naming-tvdb-naming-conflicts/137

and also covered in the wiki
