### ISSUE TITLE
Add Granular Quality Profiles

### ISSUE THREAD

**Issue by salomj** [Sonarr/Sonarr#6440]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some series span 30+ years, and other have gaps of over 40+ years. So a lot of these will probably never have a 1080p copy, while the latest season will. It is annoying that Sonarr will consider these cutoff unmet when it is the best possible and will probably be the best ever possible, while it would be nice for Sonarr to continue to monitor these episodes.

### Describe the solution you'd like

It would be nice if you could assign quality profile to seasons and even to individual episodes. It might be nice to also have the ability to add tags to seasons and episodes as well and support release profiles, delay profiles, indexers, etc.

### Describe alternatives you've considered

The only alternative is to go into the series and unmonitor those episodes and seasons that will never meet the quality profile and to manually add episodes which will exceed the quality profile.

### Anything else?

This would be especially useful in the `Specials` folder where some of the `Specials` are movies that come out in 2160p, whereas the rest of the series is only 1080p or less.

**Comment by thezoggy** [comment]
just set the quality profile to include the qualities you are okay with, and order it to the ones you want. and then finally if you want something to upgrade enable that. pretty much covered on wiki or trash guides if you use his stuff

**Comment by salomj** [comment]
> just set the quality profile to include the qualities you are okay with, and order it to the ones you want. and then finally if you want something to upgrade enable that. pretty much covered on wiki or trash guides if you use his stuff

Yeah, but when you have literally 1000s of show managed by Sonarr. I want to think about it once and not have a running list of 100s of shows I need to manually make changes to.

**Comment by markus101** [comment]
You can't have it both ways, either Sonarr monitors them and the cut off is unmet or you unmonitored them and in the small chance a higher resolution comes out Sonarr will upgrade to that.

We do not have plans for more complex quality profiles or different profiles per season.
