### ISSUE TITLE
Calendar colour coding broken for collapsed multi episodes airing same day

### ISSUE THREAD

**Issue by Mahava** [Sonarr/Sonarr#6441]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Whenever "Collapse Multiple Episodes" is set in Calendar options, the visible tile is colour coded as 'missing' instead of 'downloading' even though when the list is expanded, the episodes are downloading.

### Expected Behavior

I expected that the collapsed tile colour would indicate the colour of the status of the individual episodes... especially if all are downloaded or downloading etc.

### Steps To Reproduce

On Windows Firefox or Edge, and Sonarr 4.0.1.1014
in Calendar Options:
Switch on "Collapse Multiple Episodes"
Switch on "Full Colour Events"
Look at a multi episode item airing on the same day and that is downloading and should be coloured purple.  Instead, the visible tile is coloured red for Missing.

### Environment

```markdown
- OS: 
- Sonarr: 
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/14073219/sonarr.trace.txt)

### Anything else?

I think this began after pixels were added to the collapsed tile to make it bigger?

**Comment by markus101** [comment]
Next time please fill out the template completely.

> I think this began after pixels were added to the collapsed tile to make it bigger?

All that did was add 4 pixels to the height, this issue existed before then.
