### ISSUE TITLE
Youtube Downloader

### ISSUE THREAD

**Issue by hughesjs** [Sonarr/Sonarr#6445]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It's not uncommon for full shows to be released straight to Youtube now. These rarely make it onto Usenet or Torrents due to them just being available freely. TVDB has these shows and Sonarr lets you add them with "Youtube" as the channel, but there's no way to download them. 

Helluva Boss would be one example.

### Describe the solution you'd like

For shows that are published to Youtube and present in TVDB, we can just download them straight from Youtube.

### Describe alternatives you've considered

Some sort of YT -> Torrent bridge

**Comment by hughesjs** [comment]
There is a closed issue that talks about YT Feeds, but I think this is different as it refers to a download source rather than a feed

**Comment by thezoggy** [comment]
fundamentally it wouldnt work to 'search' for youtube to know what really is what you want then to send youtube url to what to download and so on. if you really want to rip youtube stuff yourself then just manually import. but that whole process would not make sense for \*arr to try and handle within itself

**Comment by hughesjs** [comment]
Tbh I was hoping/assuming that there would be some way to tie the tvdb info with a specific YT URL rather than having to search and make a best guess... But I've just had a look and there doesn't seem to be a URL on their pages annoyingly

**Comment by markus101** [comment]
Integrating with another "protocol" of sorts to support youtube-dl or similar is not something we have plans to do.
