### ISSUE TITLE
"On Manual Interaction Required" notification not working

### ISSUE THREAD

**Issue by fatSquirrel42** [Sonarr/Sonarr#6448]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have set up a connection to send a notification when a manual interaction is required. My understanding is that a waiting import is such an event, but sonarr does not send a notification.

### Expected Behavior

Sonarr should issue a notification when an import is waiting to be imported and a connection is set up with "On Manual Interaction Required".

### Steps To Reproduce

Sonarr has a download that it can't import automatically.

In my case, the name of the downloaded file is different from the grabbed title and the import is no longer a custom format upgrade.

### Environment

```markdown
- OS: Debian 6.9.12-2
- Sonarr: 4.0.1.929-ls222 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

https://privatebin.net/?0ce5c7dfb3962134#Fzmmcp8tKNEhWPKvssrPQWncq4dG7oEnvmSwXNRqsgSo

### Anything else?

Let me know if the event is missing in the logs. After enabling trace logs, I changed the category from the download client and back to trigger the import again.

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/14077362/sonarr.trace.txt)

![connect](https://github.com/Sonarr/Sonarr/assets/72809254/90efe681-cf9b-40ea-9671-e761e4a4c5b8)
![Screenshot_20240128-132444_ntfy](https://github.com/Sonarr/Sonarr/assets/72809254/4503d392-c9ca-47ef-8fc1-0434afda8264)
![act2](https://github.com/Sonarr/Sonarr/assets/72809254/022a23eb-362f-4414-98d2-45d389273e14)
![act1](https://github.com/Sonarr/Sonarr/assets/72809254/b8857307-3a47-49ff-86bf-12b2a32f4e5a)

**Comment by markus101** [comment]
Notifications are only sent when the reason for not importing is due to a series title mismatch, be could probably be expanded to include other reasons.
