### ISSUE TITLE
Renaming issues "Source and destination can't be the same"

### ISSUE THREAD

**Issue by OverlordQ** [Sonarr/Sonarr#645]
I get this error quite a bit if I do an organization of my library. Turning on verbose debugging doesn't give any additional information

    [Warn] DiskProviderBase: Source and destination can't be the same \\freenas\freenas\tv\xxx\Season 02\xxxx.S02E20.xxx.DVD-thumb.jpg

**Comment by markus101** [comment]
Please use the forums for support including trace logs of the rename.
