### ISSUE TITLE
Conditional Release Profiles

### ISSUE THREAD

**Issue by beschoenen** [Sonarr/Sonarr#6451]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I would like to be able to apply a release profile conditionally.

My use case is that I would like to block Dolby Vision files unless they're marked as Hybrid.

### Describe the solution you'd like

Maybe there could an "unless contains" option for release profiles that disables the release profile when a keyword is found in the release.

### Describe alternatives you've considered

None.

### Anything else?

I would like to try to implement it myself, but I'm unsure if the solution I suggested is the correct way to do it.

**Comment by stevietv** [comment]
You can do that already with the CF conditions.
Have the CF only apply when it meets DV and doesn't meet Hybrid. Examples can be found on trash guides/

For assistance on this you could drop by one of our support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by beschoenen** [comment]
Ok I'll check it out. Thanks
