### ISSUE TITLE
Login input fields should support AutoFill features with `autocomplete`

### ISSUE THREAD

**Issue by tylerdak** [Sonarr/Sonarr#6452]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sonarr's login fields<sup>1</sup> don't trigger the Password AutoFill on iOS devices (tested on Safari, iOS 17.3). There's already an input=password attribute on the password field, but this is not enough in some contexts. 

<sup>1</sup>Not the basic HTML form but the custom fields, to be clear

### Describe the solution you'd like

This would be fixed with `autocomplete` attributes as outlined [on Apple's documentation on this topic](https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element) and [web.dev](https://web.dev/learn/forms/autofill). While Safari is where I personally experience the issue, fixing this will ensure all supporting browsers suggest or autofill the relevant password when a password is available.

### Describe alternatives you've considered

This is a pretty simple solution and kind of a binary thing between supporting or not supporting password autofill. The alternative is not supporting it or relying on the browser or operating system to determine if it needs to autofill a password. 

This works in some contexts (in particular, desktop browsers where extensions have a lot more freedom with reading site content) but adding this `autocomplete` attribute would allow for less invasive autofill methods to work such as the one on iOS to work.

### Anything else?

[Here's an example of what the keyboard with Password Autofill triggered looks like on iOS.](https://docs-assets.developer.apple.com/published/4f083b37c4/3001200@2x.png) And [this is what the keyboard looks like without the autofill triggered](https://github.com/Sonarr/Sonarr/assets/20099759/386bf151-baa1-4365-8e92-a0567c48cc7a) (yes, I have the username field selected here. For security, iOS doesn't include the keyboard in screenshots when a password field is selected. The keyboard looks the same when the password field is selected).

Once again, you can read more about the `autocomplete` attribute on the following pages:
https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element
https://web.dev/learn/forms/autofill

**Comment by tylerdak** [comment]
I noticed `autocomplete='off'` in the input field for the email. Not sure if this is an established change or just something that was leftover from when the file was created. It's been there since the file was created according to the git history.

**Comment by thezoggy** [comment]
you do this so people dont save things with their insecure browsers.
https://www.beyondsecurity.com/resources/vulnerabilities/autocomplete-not-disabled

if users use a password manager it can easily override this (usually a toggle to ignore it / or you just fill on demand).

**Comment by markus101** [comment]
This is the login screen on Safari, 17.2.1.

![image](https://github.com/Sonarr/Sonarr/assets/413544/2e199c0d-538a-40f5-be5a-7d7e95a65510)

This is to Sonarr running behind a reverse proxy that provides a secure connection. If I connect to an insecure instance (or bypass the proxy) then Safari does not provide the password entry. With an insecure connection and setting autocomplete to `password` or `current-password` doesn't change the behaviour.

Not sure why we went with `autocomplete="off"` for the username input, but this doesn't appear to have any negative effects on how Safari handles password entry, but the type of connection does. Chrome doesn't appear to have this restriction for whatever reason.

**Comment by tylerdak** [comment]
Ah that makes sense. Thanks for the clarification
