### ISSUE TITLE
Incorrect Search Results for Olympus

### ISSUE THREAD

**Issue by naaronne** [Sonarr/Sonarr#646]
When doing a manual search for the series/episode 'Olympus - 1x12 - Door To Olympus'.

I get many results, all of which are incorrect and none for Olympus.

See screenshot for results.

![olympusresults](https://cloud.githubusercontent.com/assets/10212075/8394262/a7e83c00-1cfd-11e5-8f38-66b2c80c5804.png)

**Comment by markus101** [comment]
Please use the threads for support. Sonarr shows the results returned by your indexer, likely because its not doing a TVRage ID search.
