### ISSUE TITLE
Naming Format space replacement doesn't work

### ISSUE THREAD

**Issue by spanasiuk** [Sonarr/Sonarr#6460]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I specify space replacement for naming formats, it doesn't change anything.

### Expected Behavior

When I specify that spaces in the name should be replaced with the period, it should allow me to save the change and when I rename the file, all spaces (even the ones in the title) should be replaced with the period (or other separator)

### Steps To Reproduce

1. Open Settings -> Media Management;
2. Press the blue question mark button next to any of the custom name formats: 
<img width="76" alt="image" src="https://github.com/Sonarr/Sonarr/assets/36239821/3e5eb34f-ee8d-4340-ba49-696d46655278">

3. Change from `Space ( )` to `Period (.)`:
<img width="1069" alt="image" src="https://github.com/Sonarr/Sonarr/assets/36239821/b18f2798-ed5e-485d-86c9-5434e9deaa1d">

4. Observe that there's no way to save the change. If you also try to change other fields, the space replacement doesn't persist;
5. Try making the PUT request at `https://sonarr.host/api/v3/config/naming` with the body:
```
{"renameMovies":true,"replaceIllegalCharacters":true,"colonReplacementFormat":"delete","standardMovieFormat":"{Movie Title}.{Release Year}.{Quality Full}.{MediaInfo VideoDynamicRangeType}.{MediaInfo VideoCodec}.{MediaInfo VideoBitDepth}bit.{MediaInfo AudioLanguages}.{MediaInfo SubtitleLanguages}.{Custom Formats}","movieFolderFormat":"{Movie Title}.{Release Year}","includeQuality":false,"replaceSpaces":true,"separator":".","id":1}
```

6. Observe that even though the `replaceSpaces` in the request body was `true`, the response contains `"replaceSpaces": false`

### Environment

```markdown
- OS: hosted on Debian GNU/Linux 12 (bookworm), Linux 6.1.0-rpi7-rpi-v8 aarch64. Testing through the browser/Postman from macOS 14.3 (23D56)
- Sonarr: Sonarr 4.0.1.929
- Docker Install: Yes, Docker version 25.0.0, build e758fe5
- Using Reverse Proxy: Yes, Traefik
- Browser: Safari Version 17.3 (19617.2.4.11.8), Chrome Version 108.0.5359.98 (Official Build) (x86_64), Postman Version 10.22.6
- Database: Sqlite 3.41.2
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/14128880/sonarr.trace.txt)

### Anything else?

The same issue is present in Radarr. 
I'm using the `ghcr.io/hotio/sonarr` docker image.

**Comment by markus101** [comment]
That dropdown changes _new_ tokens you add to the naming format to use a `.` instead of ` `, but existing tokens are not changed. You need to change you existing tokens to use periods instead of spaces.

In this case the API docs are incorrectly showing that properties from v2 are still available and will need to be removed.

All these properties no longer exist:

```
includeSeriesTitle
includeEpisodeTitle
includeQuality
replaceSpaces
separator
numberStyle
```

**Comment by spanasiuk** [comment]
@markus101 thanks for the reply! It took me some time to understand what exactly you mean by that, but now I get it - I need to add the separator in the tokens I have. Awesome, thanks a lot!
