### ISSUE TITLE
Feature Request: Verify seeder count

### ISSUE THREAD

**Issue by SnowDrifterr** [Sonarr/Sonarr#6468]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some trackers, such as 1337,  misreport their seeders/leechers. It's a common frustration where something appears to be well seeded, but on inspection, appears to be a dead torrent.

### Describe the solution you'd like

Per-indexer settings that check the listed number of seeders against actual - effectively an automated version of webtorrentchecker, to validate actual numbers, check against minimum seeder settings, and either try again for the next-best match, or continue to download

### Describe alternatives you've considered

- Minimum seed counts: Impossible to find a middle ground. Some are falsely listed as 100+ seeders when the torrent is dead. Likewise, some listed as 1 are alive and well
- Manual search + shotgun approach: Feels, frankly, impolite. Downloading 5-6 of the same thing hoping that one of them is valid is both labor intensive, and a poor use of other's bandwidth if it turns out more than 1 is available

**Comment by markus101** [comment]
Effectively this would require Sonarr to have torrent client capabilities and likely require inbound connections to ensure magnets could be resolved and seeder counts could verified, this is not something we're going implement.
