### ISSUE TITLE
An error about custom format score

### ISSUE THREAD

**Issue by kristianvmd** [Sonarr/Sonarr#6479]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If I use ^Murder and check the opposite, anything that doesn't start with Murder is matched successfully

I just want to not match ones that start with Murder, I don't want everything that doesn't start with Murder to be matched

### Expected Behavior

none

### Steps To Reproduce

none

### Environment

```markdown
- OS: synology
- Sonarr: V4
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: chrome
- Database:
```

### What branch are you running?

Main

### Trace Logs?

none

**Comment by PearsonFlyer** [comment]
Please use discord for support issues, which this is. It's not a bug, it's how the negate checkbox works.

**Comment by kristianvmd** [comment]
Do you mean that as long as the opposite is checked, it will match all that don't start with   ```Murder```   ?
