### ISSUE TITLE
Deferred Plex Media Update

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#649]
When importing two season packs my plex server didn't register all of em, just 3 out of 40 episodes.
We should probably use some kind of deferred update mechanism when scanning whole sections or series.

**Comment by markus101** [comment]
The only way I can see it being this bad is if the last scan that completed was triggered when there was only 3 episodes in the library, but regardless I think this falls under: https://github.com/Sonarr/Sonarr/issues/363 I can't see a lot of people wanting multiple notifications for their client, so we could show "Downloaded - Series Season 1" or something like that.

**Comment by hagabla** [comment]
Happens to me on every season import, since plex scans the whole library, which takes some time.

**Comment by bakerboy448** [comment]
This bug/issue seems stale.  Please check and see if it is still an issue on the recent v3 builds.  If it is an issue please open a new GHI with logs and full detail.
