### ISSUE TITLE
Moving instead of Copy when Seed Ratio is reached before the completion (qBittorrent)

### ISSUE THREAD

**Issue by fabricionaweb** [Sonarr/Sonarr#6490]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have the `Use Hardlinks instead of Copy` enabled and I've notice qBittorrent errors from missing files. Only for a specific indexer, and also not always.

I also use `Post-Import Category` with should not remove completed from the client (if that matters)

After investigation, with a help, we figured that:
- If a seed ratio value exists (from the indexer) and it have been reached (on the client) during the **download in progress**: the file will be moved by Sonarr when importing
- If a seed ratio value exists (from the indexer) and it have **NOT** been reached (on the client) during the **download in progress**: the file will be hardlink/copy by Sonarr when importing
- If a seed ratio value **NOT** exists (from the indexer): the file will be hardlink/copy by Sonarr when importing

### Expected Behavior

Should not move when I have the Hardlinks option enabled. 
Even if the seed ratio is reached, qBittorrent will pause the torrent to me.
Moving the files but let the torrent on client will show as errored.

### Steps To Reproduce

1. Have the `Use Hardlinks instead of Copy` enabled
2. Use `Post-Import Category` or disable `Remove Completed`
3. Set a lower `Seed Ratio` to an specific indexer (like 1.0 or maybe less)
4. Try to grab a release from this same indexer that you hope it will reach the seed ratio **before it gets complete** (thats more trick)

### Environment

```markdown
- OS: Unraid
- Sonarr: 4.0.1.929
- Docker Install: Yes (hotio/sonarr)
- Using Reverse Proxy: Yes (traefik)
- Browser: Chrome 121.0.6167.139 (Official Build) (arm64) MacOS
- Database: Sqlite 3.41.2
- qBittorrent: 4.6.3 (hotio/qbittorrent)
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://logs.notifiarr.com/?924824895e7b3a3d#6EmjphvRrQ2TB1vKfrUrsfFL49qjeTJjuFYXczXHokoG)

### Anything else?

The release that got moved on my log is: `[SubsPlease] Metallic Rouge - 05 (1080p) [9BE9A5F3].mkv` got from `Nyaa.si (Prowlarr)`
The index `Nyaa.si (Prowlarr)` have the Seed Ratio set to `1.0`
The index `Nyaa.si (Prowlarr)` have qBittorrent client pointing to `http://qbittorrent:8090`

**Comment by markus101** [comment]
> Should not move when I have the Hardlinks option enabled.

Seeding torrents are hardlinked or copied, if the torrent isn't seeding then it's moved. The help text for the hardlink setting specifies _seeding_ torrents, torrents that have reached the seeding limit are no longer seeding.

Why do you set seeding goals if you want to resume them again? Why not just let them seed forever or set a higher seeding goal?

**Comment by markus101** [comment]
> I didn say I want to resume the torrent. I was expecting qBittorrent to handle the share limits by itself, as it does if it dont reach the goal before importing.

My misunderstanding based on "Moving the files but let the torrent on client will show as errored." I assumed you were resuming to see that error.

> I was expecting qBittorrent to handle the share limits by itself, as it does if it dont reach the goal before importing.

What does qbit normally do? With Sonarr it should only pause.

> Its not considered normal to have errored torrents in the client and I was wondering why I had that.

Gotcha, you could tell Sonarr to remove completed torrents, which when combined with Post-Import Category would only do so when completed before importing (and combine with the move).
