### ISSUE TITLE
Parsing Season/Episode separated by period

### ISSUE THREAD

**Issue by Dukobpa3** [Sonarr/Sonarr#6492]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some releases named in formats which can't be recognized by sonarr automatically
`s03.05` for example my last one

### Describe the solution you'd like

Would be great to have some options like in Total Commander group renaming tool with search and replace by pattern.
Default sonarr parsers works great in most cases so it should be like some button or checker in the interactive import popup: "I want to set my own numbering pattern" and only after that some dialogs will be shown to be able to do it, or just input field appeared.

### Describe alternatives you've considered

Two options:
- Import manually and set mappins for each episode one by one in the interactive import dialog. It is ok for 1 season with about 10 episodes but veeeeryyyy annoying in case of importing whole show with 240 episodes per 10 seasons

- go to hdd, rename files using Total Commander, then import them to sonarr, then rename back (I'm using hardlinks and want to keep seeding this files, so need to keep original names in downloads)

**Comment by markus101** [comment]
With Manual Import you can multi select the files and then choose the episodes, so long as they are in the correct order Sonarr will assign the chosen episodes in order to those files.

No plans to add support for selecting how things should be parsed.

**Comment by Dukobpa3** [comment]
@markus101 
Ok then look at it.
Each file mapped to all episodes in the season.
With numbering I've provided. `s01.10`
It is tv show with 240 episodes. So I just have to make 240х3 clicks

![Screenshot 2024-02-09 at 18 50 49](https://github.com/Sonarr/Sonarr/assets/1858880/08a01c13-a0d0-44ab-aab6-e5b78bd793b4)

**Comment by markus101** [comment]
You don't need to do 240x3 clicks, Sonarr supports range selection of files as well as applying seasons/episodes to those selected files.

The screenshot does give some additional information that would have been a lot more useful than a partial, snippet of that file name, but we need additional information to determine whether we can handle that format, specifically trace logs. Please provide trace logs of this manual import that includes the files being parsed.

**Comment by Dukobpa3** [comment]
How can I do it step by step to provide you all needed info?

**Comment by markus101** [comment]
You enable trace logging then reproduce the issue, upload the trace logs (gist is a good spot) and link them here.

Trace Logs:
https://wiki.servarr.com/sonarr/troubleshooting#logging-and-log-files

**Comment by Dukobpa3** [comment]
https://gist.github.com/Dukobpa3/087c214ab5c49a033413c3c90e5806cb
