### ISSUE TITLE
Issue with episodes numbering

### ISSUE THREAD

**Issue by Dukobpa3** [Sonarr/Sonarr#6496]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

couple days ago i've got tv show with episodes numbered like: `s04.03` and sonarr can't import them properly.
It was mapped all episodes together to each file

![Screenshot 2024-02-09 at 18 50 49](https://github.com/Sonarr/Sonarr/assets/1858880/08a01c13-a0d0-44ab-aab6-e5b78bd793b4)

### Describe the solution you'd like

I've suggested one complicated solution. It was declined. An I agree that maybe it is too much.
https://github.com/Sonarr/Sonarr/issues/6492
But the issue still present.
It is ok to link files to episodes manually in case there is just one season with 10 episodes. But in my case it was 10 season, each with 20+ episodes (240 total)

### Describe alternatives you've considered

– rename files with TotalCommander multirename tool
– import to sonarr (I'm using hardlinks)
– rename back to keep seeding them

**Comment by bakerboy448** [comment]
Nonstandard naming presumably only done by eastern european trackers?

**Comment by markus101** [comment]
Please don't open new issues to discuss already closed issues... if you want to continue the discussion you should use one of the support channels.

> It is tv show with 240 episodes. So I just have to make 240х3 clicks

No, you use `Select Episodes` under `Select...`

**Comment by Dukobpa3** [comment]
> you use Select Episodes under Select...

you see result on picture

**Comment by Dukobpa3** [comment]
> already closed issues...

Issue still present. Even task not closed just cancelled.

**Comment by markus101** [comment]
It's the same issue with additional information you added after that issue was closed, but closed doesn't mean it's never going to be reopened or replied to. Locking this and will reply to the other issue as we need more information.
