### ISSUE TITLE
skyhook.sonarr.tv not reachable via IPv6

### ISSUE THREAD

**Issue by breucode** [Sonarr/Sonarr#6502]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

skyhook.sonarr.tv is not reachable via IPv6. Since my server only has an IPv6 address, I am not able to user sonarr properly.

### Expected Behavior

skyhook.sonarr.tv is reachable via IPv6, which makes IPv6 only machines able to connect.

### Environment

```markdown
- OS: Linux
- Sonarr: 3.0.10.1567
- Docker Install: 
- Using Reverse Proxy: nginx
- Browser: Firefox
- Database: sqlite
```

### What branch are you running?

Main

### Trace Logs?

Feb 11 10:57:27 arthur NzbDrone[30630]: [v3.0.10.1567] System.Net.WebException: Error: ConnectFailure (Network is unreachable): 'https://skyhook.sonarr.tv/v1/tvdb/se>
Feb 11 10:57:27 arthur NzbDrone[30630]:   at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in <8b90e4d65a104a9b940f2e7b63f7f4ea>:0
Feb 11 10:57:27 arthur NzbDrone[30630]:   at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in <8b90e4d65a104a9b940f2e7b63f7f4ea>:0
Feb 11 10:57:27 arthur NzbDrone[30630]:   at System.Net.WebConnection+<>c.<Connect>b__16_1 (System.IAsyncResult asyncResult) [0x00006] in <8b90e4d65a104a9b940f2e7b63>
Feb 11 10:57:27 arthur NzbDrone[30630]:   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endF>
Feb 11 10:57:27 arthur NzbDrone[30630]: --- End of stack trace from previous location where exception was thrown ---
Feb 11 10:57:27 arthur NzbDrone[30630]:   at System.Net.WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToke>
Feb 11 10:57:27 arthur NzbDrone[30630]:    --- End of inner exception stack trace ---
Feb 11 10:57:27 arthur NzbDrone[30630]:   at System.Net.WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToke>
Feb 11 10:57:27 arthur NzbDrone[30630]:   at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellat>
Feb 11 10:57:27 arthur NzbDrone[30630]:   at System.Net.WebOperation.Run () [0x0009a] in <8b90e4d65a104a9b940f2e7b63f7f4ea>:0
Feb 11 10:57:27 arthur NzbDrone[30630]:   at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x00094] in <8b90e4d65a104a9b940f2e7b63f7f4ea>:0
Feb 11 10:57:27 arthur NzbDrone[30630]:   at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeo>
Feb 11 10:57:27 arthur NzbDrone[30630]:   at System.Net.HttpWebRequest.GetResponse () [0x00016] in <8b90e4d65a104a9b940f2e7b63f7f4ea>:0
Feb 11 10:57:27 arthur NzbDrone[30630]:   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net>
Feb 11 10:57:27 arthur NzbDrone[30630]:    --- End of inner exception stack trace ---
Feb 11 10:57:27 arthur NzbDrone[30630]:   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net>
Feb 11 10:57:27 arthur NzbDrone[30630]:   at NzbDrone.Common.Http.HttpClient.ExecuteRequest (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer coo>
Feb 11 10:57:27 arthur NzbDrone[30630]:   at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00008] in <1e046deedc9e46859e87c68>
Feb 11 10:57:27 arthur NzbDrone[30630]:   at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in <1e046deedc9e46859e87c687818>
Feb 11 10:57:27 arthur NzbDrone[30630]:   at NzbDrone.Common.Http.HttpClient.Get[T] (NzbDrone.Common.Http.HttpRequest request) [0x00000] in <1e046deedc9e46859e87c687>
Feb 11 10:57:27 arthur NzbDrone[30630]:   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewSeries (System.String title) [0x000ff] in <36de8bde5c044e5>

**Comment by markus101** [comment]
You should upgrade to v4, but closing this since it's not a Sonarr bug.
