### ISSUE TITLE
If series has anime tag > do not automatically search

### ISSUE THREAD

**Issue by absywabsy** [Sonarr/Sonarr#6507]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Adding series as anime (automatically by overseerr for e.g.) means it searches as anime series type and Sonarr's anime implementation using absolute episode is terrible, the best scored season packs are not picked, instead sometimes German is picked or a bad nzb file is picked instead of AnimeBytes' season packs. All the while using up 1000 searches for 50 episodes or so, you get the picture.

Basically, Anime should be done manually in sonarr's current state, it's just not feasible, it's too big a can of worms to tackle automatically.

Currently Overseerr attaches "Anime" i.e. "Absolute" numbering episode search to all Anime added.
The tag 'anime' can be attached, but there's nothing in Sonarr to detect the tag and stop the automatic search.

### Describe the solution you'd like

Instead, can the series be added, but not automatically searched, so that the user can come home, manually search for the correct season pack from say, Animebytes and use that.

### Describe alternatives you've considered

I'll use an example of Naruto Shippuuden:

Add Naruto Shippuuden as an anime series type (absolute) episodes.
Search for one episode 2x01 for e.g.

https://i.imgur.com/tuV6cci.png

Repeatable steps:
Searching Season 2x01 of Naruto Shippuuden gives a total runtime of 11500 minutes, this is incorrect.
Season 2 only has 21 episodes, 21*23 minutes is 483 minutes. My minimum is 5Mb so 5*483mins is 2.4Gb, instead it's rejecting everything under 56.2Gb.

Since the series is added automatically as ANIME type, it has to search episode by episode, wasting API hits on usually a scale of 1 episode is 5 searches, because of all the aliases it has to search under, you'll easily hit 500 hits for 50 episodes sometimes. Instead, if the user could manually go in, change the type to Standard, search for the whole season, it would perform just a few searches for the whole season and 500 hits are not wasted getting wrong or bad quality content due to most releases being rejected because of the aforementioned inaccurate runtime calculation. (I already have Trash Guides implemented and follow it to the letter by the way, so it's not that).

I know Overseerr could implement something but it's better to tackle this from both ends as the anime implementation just isn't very good at the moment.

Just a stopgap measure until the anime implementation is improved.

**Comment by PearsonFlyer** [comment]
The decision on whether to search or not is a checkbox you check (or don't check) when adding a series. Simply do not check that box, and your problem is solved.

**Comment by markus101** [comment]
No plans to disable searching based on the series type or tag, if Sonarr is told to search for a series when it is added it will search for that series when it is added. If you disable automatic search for the indexers that have anime categories you could have Sonarr "told to search", but not actually search.

**Comment by absywabsy** [comment]
> The decision on whether to search or not is a checkbox you check (or don't check) when adding a series. Simply do not check that box, and your problem is solved.

Yes I'm aware of that but you won't be able to do that if the series is added via overseerr. But Overseerr does automatically add the tag 'anime' to anime series.

**Comment by PearsonFlyer** [comment]
It seems like your request would be better suited to overseerr, if you want overseerr series request behavior changed.

**Comment by absywabsy** [comment]
It's mainly due to sonarr's bad anime implementation of absolute episode searching at the moment. If there was an option for e.g. for all anime to be added as standard, it might fix some of the issues. Most anime these days use season pack methods, especially due to the most popular trackers and therefore absolute is no longer the main option.

I wanted to come at it from both angles.

**Comment by PearsonFlyer** [comment]
Again, there's no need for a change in Sonarr. Sonarr searches when you tell it to search. Overseerr, in this case, is telling it to search. If you want it to not do that, turn on approvals in overseerr or request a change.

**Comment by absywabsy** [comment]
Ok thanks I have done that. I hope Sonarr's Anime implementation gets better and https://github.com/Sonarr/Sonarr/issues/6495 is given some serious consideration. Thanks for contributing to an otherwise great arr.

**Comment by Krandor1** [comment]
If I add an anime and tell it to search now I want it to search now and don’t want to have to manually do a search afterwards. Please do not do this. On Feb 13, 2024, at 18:43, absywabsy ***@***.***> wrote:﻿
Ok thanks I have done that. I hope Sonarr's Anime implementation gets better and #6495 is given some serious consideration. Thanks for contributing to an otherwise great arr.
