### ISSUE TITLE
zero point downloads replacing higher point downloads

### ISSUE THREAD

**Issue by nekotome** [Sonarr/Sonarr#6512]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have a label which assigns for example 120 points to certain combination of tags.  This release is downloaded.  Another release comes along and replaces it but has a weight of zero.

### Expected Behavior

Higher point releases should not be replaced with lower point releases

### Steps To Reproduce

Create a label with [ReleaseGroup][Multi] name, auto download release.  Wait for another group named [Foo] to make a release, this 0 point release replaces the [ReleaseGroup][Multi] which is 120 points.

### Environment

```markdown
- OS: Synology
- Sonarr: 3.0.10.1567
- Docker Install: N
- Using Reverse Proxy: N
- Browser: Chrome
- Database: N/A
```

### What branch are you running?

Main

### Trace Logs?

n/a

### Anything else?

n/a

**Comment by stevietv** [comment]
Please first upgrade to v4 of Sonarr, v3 is no longer supported.
Examples with faked names will never help for us to debug the situation, but you might be better using one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by markus101** [comment]
No they're not.
https://github.com/Sonarr/Sonarr/releases/tag/v4.0.1.929

Also https://sonarr.tv/#download
