### ISSUE TITLE
SQLite Error "no such column: false"

### ISSUE THREAD

**Issue by SkyTheCodeMaster** [Sonarr/Sonarr#6515]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I start a fresh install Sonarr, and it immediately errors with `no such column: false`

### Expected Behavior

The expected behaviour is for Sonarr to start.

### Steps To Reproduce

1. Install Sonarr
2. Start Sonarr
Error

### Environment

```markdown
- OS: Ubuntu 18.04
- Sonarr: 4.0.1.929
- Docker Install: No
- Using Reverse Proxy: No N/A
- Browser: N/A
- Database: Sqlite 3.45.1
```

### What branch are you running?

Develop

### Trace Logs?

https://paste.skystuff.cc/VugCPQIS

**Comment by markus101** [comment]
> no such column

We've only seen this against old versions of SQLite, like the versions that ship in the default repos for Ubuntu 18.04.

> 3.45.1

It's likely this is the version of SQLite tools, not the SQLite engine.

Please try switching to a `develop` (pre-release) build, which includes additional logging about the SQLite engine Sonarr is actually using at startup. Sonarr also shows this information in the UI in all v4 versions, but that requires it to start up, but would be possible by running Sonarr briefly on a system with a known newer version of SQLite and then transferring the DB to that system.

**Comment by markus101** [comment]
Closing this after discussing on Discord and you'll likely want to look at upgrading Ubuntu to a newer release that supports a newer version of SQLite.

**Comment by SkyTheCodeMaster** [comment]
Yeah I eventually just rebuilt the entire machine on Ubuntu 22.04, it's working flawlessly, forgot to close the issue though.
