### ISSUE TITLE
Use TheTVDB ID Matching over TV Rage

### ISSUE THREAD

**Issue by nuxencs** [Sonarr/Sonarr#6517]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

`Stitch!` was wrongfully identified and downloaded as `Lilo & Stitch: The Series` because the TVRage id was incorrect on the tracker.

### Expected Behavior

I would expect the TVRage ID check to be removed, because that site hasn't been functioning correctly for a long time now (see linked issue). In my opinion a more sensible alternative/replacement would be TVMaze.

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Sonarr: 4.0.1.1131
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox 122.0.1
- Database: Sqlite 3.41.2
```

### What branch are you running?

Develop

### Trace Logs?

https://logs.notifiarr.com/?672e829b1638bde0#NETZHtXSxoHo6USvec28TjDKgbL1jFNvXEwEWxPQYT6

### Anything else?

https://github.com/Sonarr/Sonarr/issues/2048

**Comment by thezoggy** [comment]
report the issue to the indexer so they can fix their issue?

**Comment by bakerboy448** [comment]
Keep it only for auto and interactive search perhaps for legacy?

**Comment by thezoggy** [comment]
```
2024-02-17 19:38:50.1|Debug|QualityParser|Trying to parse quality for 'Stitch.S02.1080p.DSNP.WEB-DL.AAC2.0.H.264-ViETNAM'
```
i assume your talking about:
```
2024-02-17 19:38:50.1|Debug|ParsingService|Found matching series by TVRage ID 98661, an alias may be needed for: Stitch
```
thats a typo there, its tvdb not tvrage id its showing, theres already a fix for that cosmetically.

the tvdbid 98661  is correct for the show - https://thetvdb.com/series/stitch

now about your issue, the reason why it suggests an alias might be needed is because series is `Stitch!` while releasename has `Stitch`, so they dont match.

**Comment by nuxencs** [comment]
> thats a typo there, its tvdb not tvrage id its reporting.

I know that, the TVRage ID (4247) is wrong on the tracker that the release got grabbed from.

> then about the TrollHD releases for the other lilo series, you just need to use the correct series for that (not clear if your importing into the wrong one or what going on from your limited logs)

the TrollHD releases for the other lilo series are the ones I already have for `Lilo & Stitch: The Series` so those are not the issue. The issue is that the `Stitch!` releases got grabbed because they matched the id from a service that has been defunct for multiple years.

**Comment by markus101** [comment]
> Keep it only for auto and interactive search perhaps for legacy?

Lilo and Stitch aired before TV Rage became defunct.

Sonarr doesn't use TVMaze IDs for matching, but does send it for searches.

We're not going to remove TV Rage matching, but it shouldn't be used if there is a TVDB ID that points at a different series.

**Comment by nuxencs** [comment]
> We're not going to remove TV Rage matching, but it shouldn't be used if there is a TVDB ID that points at a different series.

sounds like a sane approach, thanks 👍🏼
