### ISSUE TITLE
Performance on low powered devices

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#652]
Performance is quite bad on low powered devices such as Syno DS211J and DS212+. I suspect this is partly because of memory pressure.
We should think about ways to analyze this problem and see if we can improve at least UI performance and report using healthcheck if there is an external cause.

**Comment by guillaume86** [comment]
I'm interested in this (having a DS212+), do you have any pointers?
Just looking at the chrome tools, I see SignalR use XHR long polling, is it expected?
I don't think it's a memory pressure problem, but more of a CPU usage problem (by looking at the NAS performance monitor).
I could patch a personal build to include MiniProfiler (I'll just have to figure out how to build and replace the right files).

**Comment by Taloth** [comment]
There are quite a few caches involved. But the best would be to start with a vanilla install, see how long it takes for a specific point is reached, for example "Debug|IndexerFactory|Initializing Providers." and the memory usage at that point.
Then adding stuff, such as series. see if the startup time changes.

As for the UI, yes, long polling is used in SignalR coz we need .net 4.5 before we can start thinking about websockets.
UI performance is most likely related to the duration of the API calls. These can be analyzed of course, see what takes the longest.

**Comment by bakerboy448** [comment]
This bug/issue seems stale.  Please check and see if it is still an issue on the recent v3 builds.  If it is an issue please open a new GHI with logs and full detail.
