### ISSUE TITLE
standards

### ISSUE THREAD

**Issue by Tom-Neverwinter** [Sonarr/Sonarr#6524]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

https://github.com/Radarr/Radarr/releases/tag/v5.3.6.8612
https://github.com/Prowlarr/Prowlarr/releases/tag/v1.14.0.4286
https://github.com/Lidarr/Lidarr/releases/tag/v2.2.0.4045
https://github.com/Readarr/Readarr/releases/tag/v0.3.19.2437
sonarr is also doing the same thing.

develop for one then master for another.

can we have some consistency in the community?

https://github.com/Prowlarr/Prowlarr/issues/2037
https://github.com/Readarr/Readarr/issues/3327
https://github.com/Lidarr/Lidarr/issues/4597

### Describe the solution you'd like

standardize branches

### Describe alternatives you've considered

making my own build bot

**Comment by bakerboy448** [comment]
Servarr all do nightly => develop => master
Sonarr does develop=> main

refer to the App's FAQs for branch details

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

**Comment by markus101** [comment]
We do not have plans to introduce a nightly build.

**Comment by markus101** [comment]
In that case, tags/releases are branch independent and main doesn't get commits until a commit is going to land.

We could have a single branch, but it would make hotfixes to main/master less straight forward and you can also look at the tagged commit for a release to see what it contains.
