### ISSUE TITLE
Language details are getting lost while episode was "missing"

### ISSUE THREAD

**Issue by DiniMuetter85** [Sonarr/Sonarr#6525]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If the episode can't be found on the storage, while Sonarr is performing a scan, then the histoy section creates a entry which is mentening the "Episode File Deleted". Thats all correct and good.
But once the file is back on the storage, and Sonarr is performing again a scan, the file will be displayed in Sonarr agin, but the language is then always English as standard. (Maybe because my Sonarr is in English).
Even if I perform a new scan of the serie and the ffprobe is showing as example "German / Japanese", the language stays unchanged.
There is no change even if the "Analyse video files" function is enabled or disabled. 
![image](https://github.com/Sonarr/Sonarr/assets/57333849/b25407f2-cfe5-4005-a960-dc1d60ab0459)
![image](https://github.com/Sonarr/Sonarr/assets/57333849/f96ec7ac-a0a0-44e6-ac89-d101983a19d6)

### Expected Behavior

 The expectation would be that Sonarr is able to update the language field once ffprobe has read the metadata. I don't know if it makes sense to add a function where you can manualy prevent this "override" of language details.
Under the current setup, Sonarr would try to download a new episode because it thinks that the current saved file is only in english, and not in German or any other needed language.

### Steps To Reproduce

1. daownload / save a episode which isnt in english audio language.
2. scan the folder in sonarr
3. check the language
4. remove the file from the folder
5. scan the folder in sonarr again
6. review if the episode is mentioned in the history section with a new entry "Episode File Deleted"
7. restore the episode back to the series / season folder
8. scan the folder in sonarr again
9. review if the language is still english or is it showing the correct information which was pulled from ffprobe.

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.1.929
- Docker Install: Yes
- Using Reverse Proxy: no
- Browser: Brave Browser
- Database: Sqlite 3.41.2
```

### What branch are you running?

Main

### Trace Logs?

![image](https://github.com/Sonarr/Sonarr/assets/57333849/fd858c70-381b-4b5a-9c17-ed0c47bac55b)

**Comment by markus101** [comment]
I've confirmed that when `Analyse video files` is enabled Sonarr correctly parses the languages from the file name during linking from within the series folder. If you enable it after Sonar has linked the file it will not update the languages, it will only update the metadata and you will need to assign the languages manually (via Manage Episodes at the series or season level) or via removing the file so Sonarr no longer sees it then importing it again.

Since language can be overridden manually we do not plan to alter them if media info is rescanned after import.
