### ISSUE TITLE
Doesn't grab a new episode

### ISSUE THREAD

**Issue by Hastelo** [Sonarr/Sonarr#6526]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hello.
The problem is that Sonar does not capture the new episode of the series. The torrent is updated by adding new series to it, the sonar sees this series but cannot capture it due to the reason "Existing file on disk is of equal or higher preference". I can't figure out what exactly the problem is. Thank you!

### Expected Behavior

I wish it worked

### Environment

```markdown
- OS: Synology
- Sonarr: 4.0.1.929
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

[LOG.txt](https://github.com/Sonarr/Sonarr/files/14349515/LOG.txt)

### Anything else?

![Screenshot_4](https://github.com/Sonarr/Sonarr/assets/58543599/8bb0deb2-a061-4ab4-aa14-fedd11d426ca)

**Comment by augustuen** [comment]
This is a support issue which we don't do on Github. See our discord server or the Sonarr forum.

Your issue is that the file you have on disk is considered better than the downloaded file, according to how you've set Sonarr up.
