### ISSUE TITLE
Season Collapse by Default

### ISSUE THREAD

**Issue by noah1019** [Sonarr/Sonarr#6527]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some shows with lots of seasons can load very slowly while trying to display so many episodes. 

### Describe the solution you'd like

I think that having a toggle in the UI settings menu to collapse all seasons by default would fix this issue. This would give the option to collapse them by default to people who want it but also the option to leave it at the default for most people.

### Describe alternatives you've considered

Alternatively you could make them collapsed by default or only expand one season at a time but I feel that it would be best to leave the current functionality and add an option to change it.

**Comment by markus101** [comment]
If a season has aired recently it defaults to expanded as do upcoming seasons, otherwise they are closed by default. No plans to introduce an option to alter that behaviour.
