### ISSUE TITLE
I just want to know how to modify that damn tvdb data source！

### ISSUE THREAD

**Issue by qx** [Sonarr/Sonarr#6535]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I just want to know how to modify that damn tvdb data source， it totally messed up my data

### Expected Behavior

I just want to know how to modify that damn tvdb data source， it totally messed up my data

### Environment

```markdown
- OS: dsm
- Sonarr: 
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Main

### Trace Logs?

I just want to know how to modify that damn tvdb data source， it totally messed up my data

**Comment by bakerboy448** [comment]
[TVDb](https://thetvdb.com/) is a community maintained site also linked from the UI.
all contributions to TVDb should follow their rules.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
