### ISSUE TITLE
linux-musl-arm/arm32

### ISSUE THREAD

**Issue by radumamy** [Sonarr/Sonarr#6536]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Can you please add a build for linux-musl-arm / linux-musl-arm32 ?
There is an arm64 variant but no arm32. Thank you.

### Describe the solution you'd like

Add missing musl build for architecture arm32. Thank you.

### Describe alternatives you've considered

n/a

**Comment by Roxedus** [comment]
for most people arm32 died years ago.

**Comment by markus101** [comment]
Based on the number of users for Radarr's arm32 packages we decided that it was not worth the on going time to build them for such a small subset of users, at this time we do not have plans to create them.

**Comment by kimboslice99** [comment]
The other Arr's still build them 🤷
