### ISSUE TITLE
Allow for specific shows to automatically force import, instead of needing to manually import.

### ISSUE THREAD

**Issue by eroc1990** [Sonarr/Sonarr#6538]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, certain weekly shows that are subbed and released fairly quickly get caught up in Sonarr as having released too recently, or having other problems related to how quickly the releases are made available.

### Describe the solution you'd like

I would like the ability, as an advanced and explicitly turned on option, to be able to force individual shows to ignore the flags that prevent automatic import, and force import those automatically. Some flavor text warning people of the dangers of turning this on should be included to let users that attempt to toggle this on that it could result in importing incorrect/bad files.

### Describe alternatives you've considered

To my knowledge, there is no other way of accomplishing this.

**Comment by thezoggy** [comment]
if you use sonarr v4 this already exists, called 'override' when your manually grabbing. if its more than a one off, then you should just do the needful to request an alias or whatever is needed. follow the sonarr wiki for more info. or actually use sonarr support (not github)

**Comment by markus101** [comment]
Please be more specific, exactly what issues are created by releases being released too quickly? Week to week aliases shouldn't be required and if they are then Sonarr will not be able to keep up.

Are we talking about XEM mappings being out of date, titles not being updated on TheTVDB and thus Sonarr (which already has an option to ignore TBA titles).

We're not going to add an option that blindly ignores issues that requires manual importing, but more information may help to resolve the issues in other ways.

**Comment by eroc1990** [comment]
> if you use sonarr v4 this already exists, called 'override' when your manually grabbing. if its more than a one off, then you should just do the needful to request an alias or whatever is needed. follow the sonarr wiki for more info. or actually use sonarr support (not github)

I am aware that override exists for manual grabbing. The manual grabbing is what I would like to avoid for some shows. I want Sonarr to just import the file, overriding it automatically on a per-show basis.

**Comment by eroc1990** [comment]
> Please be more specific, exactly what issues are created by releases being released too quickly? Week to week aliases shouldn't be required and if they are then Sonarr will not be able to keep up.
> 
> Are we talking about XEM mappings being out of date, titles not being updated on TheTVDB and thus Sonarr (which already has an option to ignore TBA titles).
> 
> We're not going to add an option that blindly ignores issues that requires manual importing, but more information may help to resolve the issues in other ways.

I'll get you more specifics once I have another show that triggers this. I can't recall what the blocks were on this one. TBA was one of them (which I realized I never toggled off when I rebuilt a while back, so I just fixed that). It's usually more than just that though, if I remember correctly.

**Comment by eroc1990** [comment]
Reported behavior hasn't happened in a few days (maybe it was the TBA thing all along, which if it is sorry for wasting your time haha) so I'm just going to close this issue. I'll open it again if I can get you more concrete information re: my original issue.
