### ISSUE TITLE
Import Import List Monitoring matches the source instance’s monitoring

### ISSUE THREAD

**Issue by nrlcode** [Sonarr/Sonarr#6542]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have import lists to keep my various instances in sync (4k, 1080p, etc…).

When a user requests a show and monitors certain season(s), the import list is not aware of this, and my only options are the default monitor options. So I end up with instances out of sync in terms of what seasons they are monitoring. 

### Describe the solution you'd like

I would like the ability to match the monitoring status on imports as well. So if a new show is added to the source instance, and only Season 3 is monitored, then when it is imported via the list function, only Season 3 would be monitored. This would keep all of the monitoring intact. 

### Describe alternatives you've considered

What would be even easier than Import Lists would be the ability to store multiple versions of the same file (choosing multiple quality profiles). 

There is an existing issue that was opened for this, but it never was implemented: 
https://github.com/Sonarr/Sonarr/issues/4551

I know a lot of people struggle with multiple instances, it becomes a lot of overhead and unnecessary confusion when things aren’t properly working. I myself have 4 radar and 4 sonarr instances right now.

**Comment by markus101** [comment]
> I have import lists to keep my various instances in sync (4k, 1080p, etc…).

What "import list" are you using to keep them in sync?

**Comment by nrlcode** [comment]
You go to Settings > Import Lists > Click the + Button > Sonarr

The options for monitoring items imported by these lists are just the default choices for monitoring. But again like in my example.

Sonarr 1080p:
 - Add a show that has 8 seasons, but I only monitor Season 3

Sonarr 4k:
 - Has an Import List connecting it to Sonarr 1080p
 - It imports the new show, but my options for Monitoring are All Seasons, First, Last, New Episodes, etc... Nowhere do I get the choice of only Monitoring Season 3 like I am in the 1080p instance
