### ISSUE TITLE
Support for MegaSync / Mega.NZ

### ISSUE THREAD

**Issue by paytah232** [Sonarr/Sonarr#6543]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Especially for older shows, sometimes torrents are not the best way, or have no peers at all.

### Describe the solution you'd like

I currently will manually run MegaCMD to start the download, and import manually. I am hoping that there could be a Download Client for Sonarr, that will automate this process:
* I would not expect Sonarr to check for downloads on Mega.NZ. I would need to give it the direct folder/file link from Mega.
* Sonarr should control this through MegaCMD in the backend, importing once complete (I use `mega-get -m -q --ignore-quota-warn link_to_file/folder`)
* It would be free for everyone, it would just pause every 4ish hours after you've downloaded enough. Not really an issue if the torrent was 1KB/s anyway.
* Could be options to add a username for a premium mega account for unlimited download.
* Once downloaded, Sonarr then imports the files as per standard process.

### Describe alternatives you've considered

I don't want to pay for other features like Usenet, so this is a good free alternative, assuming you already have access to some shows through Mega.

**Comment by markus101** [comment]
We do not have plans to add support for file sharing sites like mega.
