### ISSUE TITLE
Cleaned series name imports with incorrect file name

### ISSUE THREAD

**Issue by Mr0Cake** [Sonarr/Sonarr#6546]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

It is not possible to automatically import this file. 
It seems to use the wrong file name, where the colon is 'cleaned' to a low dash `_`
Series name: 
`Frieren: Beyond Journey's End`
Tries to grab the following file:
`/downloads/complete/tv-sonarr/Frieren_ Beyond Journey's End E24 A Perfect Replica 2160p B-Global WEB-DL x264 [Japanese] (AAC 2.0) MSubs_ToonsHub_.mkv`
File on filesystem is actually:
`/downloads/complete/tv-sonarr/Frieren: Beyond Journey's End E24 A Perfect Replica 2160p B-Global WEB-DL x264 [Japanese] (AAC 2.0) MSubs_ToonsHub_.mkv`

It is possible to manual import this file.

### Expected Behavior

I would expect that it grabs the file correctly and only clean the file name upon copying. 

### Steps To Reproduce

1. have a series with a colon in the name
2. have a downloaded file with a colon in the name
3. automatically import the file

### Environment

```markdown
- OS: Unraid
- Sonarr: 4.0.1.929
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: /
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

https://gist.github.com/Mr0Cake/b3da8a77b34c5d05ea109bc5807e723e

**Comment by thezoggy** [comment]
from what limited logs you provided the folder already has _ from your downloader. guessing your using a renaming script or something? anyways not a sonarr bug..  join the proper sonarr support for further help

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Sonarr gets the path to import from your download client and uses that to import, while Sonarr will replace illegal characters while importing (only the destination file name), it replaces `:` with `-`, not `_`.

**Comment by Mr0Cake** [comment]
No renaming scripts are present. 
If sonarr gets this filename back from transmission then it will probably be transmission (also latest version) that reports the incorrect filename.
As stated before, I can find the exact filename back correctly when I escape '\:', manual import also correctly escapes this I presume.

Found [this](https://www.reddit.com/r/sonarr/comments/i6l9yc/issues_automatically_importing_series_with_a/) issue on reddit, which seems the opposite case and found multiple issues in transmission referencing the low dash.

Anyway I'm not going to dig through both of them, I guess that show will stop eventually and then my issue will be over.

**Comment by thezoggy** [comment]
Unpackerr? If you are a windows user:
> On Windows systems, files and directory names cannot be created with a colon (:).

**Comment by Mr0Cake** [comment]
Unpackerr is active, torrent does not contain rar files.
I assume it did not touch any files in this case.
(Also, running Linux and file exists)
Not sure if there are more logs that I can gather, maybe from the point it found the torrent during search?
