### ISSUE TITLE
Don't reorder anime episodes when absolute numbers change on TVDB

### ISSUE THREAD

**Issue by rg9400** [Sonarr/Sonarr#6547]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Considering there is a renewed interest in enhancing anime behavior recently (as evidenced by the willigness to explore https://github.com/Sonarr/Sonarr/issues/6495), I would like to reopen the conversation around the way anime episodes are closely coupled with the absolute episode number. I described this earlier in https://github.com/Sonarr/Sonarr/issues/4705 which was a dupe of https://github.com/Sonarr/Sonarr/issues/3785, but both were closed. It would be good to re-explore this discussion now.

What happens is that nowadays, TVDB is often reordering the absolute episode order. This is due to both A) the relatively recent decision to remove movies from specials, which impacts a fair number of anime, as well as B) their new ability to handle different orders through the UI and view them separately.

Maybe at one point, anime was closely coupled with the absolute episode order, but that is no longer the case. Now, often times, specials are interjected into the order or removed from the abs order, causing chaos for any episodes mapped to those absolute episode numbers or higher. Sonarr treats the absolute order number as sacroscant, so when it gets changed, instead of keeping the file mapped to the season + episode number, it moves the files around.

Take the below example. These files were originally episodes 12 and 13 of season 3. But some random specials got assigned an absolute order, bumping up every subsequent episode. Suddenly, these get mapped to episodes 9 and 10 simply because of the absolute order number matching now. This is definitely incorrect behavior and requires a lot of manual correction. It happens fairly frequently with anime, with multiple shows suddenly getting reordered every few weeks. Anecdotally, I have never seen this behavior work in a way that makes sense, it is incorrect every single time. But also logically, I cannot see a usecase for moving the files around due to episode order numbers. Specials suddenly don't belong in the actual season list and vice versa, a regular episode will not suddenly move to the specials list.

![image](https://github.com/Sonarr/Sonarr/assets/39887349/67ef3e34-505c-4515-9ddb-2f15d5c83324)
 

### Describe the solution you'd like

Anime episodes should be treated like standard series episodes. They are mapped to the season + episode number. In the same way that Sonarr does not reorder content when episode titles or air dates change, similarly it should not reorder anime simply when the absolute order number changes. This can still be reused in naming, and how it behaves in search/parsing can remain the same. The only thing to modify is the reordering behavior. In the rare case that a file does need to be moved to specials and vice versa, then in those cases manual import can be used via user intervention, as those cases should be rare and treated manually due to potential complexity instead of handling it for the user.

### Describe alternatives you've considered

Just constantly using manual import to reorder anime when the absolute order changes. But this is cumbersome, and if you do not notice this happening prior to an upgrade, it can wreck havoc. It also doesn't get logged super well in history, so as episodes get moved around, you can lose the history of that episode possibly, making it hard to reverse engineer where it should have belonged unless you maintained the original title. For example, I had a DVD special suddenly end up in the main episode list for Black Clover, A bluray release was grabbed from the RSS feed and upgraded the episode, but this was not the original episode which had gotten moved into specials. As I tried to restore everything back to the way it was, I was forced to regrab the entire 170 episodes of the show because I could not figure out which episodes had been remapped to which files.

**Comment by markus101** [comment]
If absolute episode numbers are changed after files are on disk isn't there always going to be issues because now everything is off by how ever many episodes they moved?

**Comment by markus101** [comment]
Gotcha, in this case (adding absolutely numbers to specials) it makes sense. For individual releases that follow absolute episode numbers in specials will likely cause some issues, but that is probably something XEM can help resolve.
