### ISSUE TITLE
Series List Seach box does not handle foreign letters

### ISSUE THREAD

**Issue by pgdownload** [Sonarr/Sonarr#6549]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Not sure if its all search boxes but the main SEARCH that filters through your shows can't handle the foreign characters that go on top of vowels sometimes. e.g. Shōgun (2024)

### Expected Behavior

Typing SHO into the SERIES LIST SEARCH box should find both Shōgun and Shogun. 

### Steps To Reproduce

Add the new SHOGUN (2024) show to SONARR
Return to the main SERIES LIST
Type SHO into the SEARCH bar at the top
SHOGUN will not be short listed

### Environment

```markdown
Device: QNAP NAS
Version: 3.0.10.1567
Package Version: 3.0.10.1567-ls213 by linuxserver.io
Mono Version: 6.12.0.200
Mode: Console
```

### What branch are you running?

Main

### Trace Logs?

Shouldn't be needed. Issue is easy to replicate.

**Comment by thezoggy** [comment]
sonarr 3.x is a few years old. do upgrade to 4.x

**Comment by Thirrian** [comment]
Might be due to the number of series I have, but I also have this one in sonarr v4, and it only showed up in the search results when I typed "shogu".

Anything less and I got (what look to me) random results:
![image](https://github.com/Sonarr/Sonarr/assets/66218321/760b1bed-402f-4278-a20b-c08f2098fbee)

They are consistently the same results, so looks like search is fuzzy, not absolute?

**Comment by markus101** [comment]
It is fuzzy searching. If you search for `gun` you see Shogun, but `sho` doesn't. Definitely a case of foreign letters not working properly there, but should that title have a foreign character? As it's an English translation I don't think it should.

**Comment by markus101** [comment]
Since Sonarr utilizes alternate titles for series when searching the we've added an alias to correct this, which is better than trying to convert these characters while searching. We may make additional changes when translations other than English are supported, but this is sufficient for now.
