### ISSUE TITLE
NotificationService failed while processing [ManualInteractionRequiredEvent]

### ISSUE THREAD

**Issue by tillkruss** [Sonarr/Sonarr#6558]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I occasionally see this in my logs:

```
NotificationService failed while processing [ManualInteractionRequiredEvent]: Object reference not set to an instance of an object.
```

### Expected Behavior

No log message?

### Steps To Reproduce

N/A

### Environment

```markdown
- OS: x64-7.1_20240114-4 by SynoCommunity
- Sonarr: 4.0.2.1183
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Safari
- Database: Sqlite 3.40.0
```

### What branch are you running?

Main

### Trace Logs?

2024-02-27 12:13:29.6|Error|EventAggregator|NotificationService failed while processing [ManualInteractionRequiredEvent]

[v4.0.2.1183] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Notifications.NotificationService.Handle(ManualInteractionRequiredEvent message) in ./Sonarr.Core/Notifications/NotificationService.cs:line 236
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)

**Comment by markus101** [comment]
We need additional information, trace logs, not just the error message and more information on the item that is requiring manual import.

**Comment by bakerboy448** [comment]
Info logs of a single line exception are not the required trace logs the bug report asks for and requires

**Comment by tillkruss** [comment]
> @tillkruss I opened a PR with a possible fix, but you still need provide the asked trace logs with more context to the error.

I can enable trace logging, but this error only occurred once and I don't know how to trigger it.
