### ISSUE TITLE
actualización 

### ISSUE THREAD

**Issue by Wannacry-ops** [Sonarr/Sonarr#6566]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

intente instalar la actualización automática y no se instalo ahora esto
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
  "title": "Not Found",
  "status": 404,
  "traceId": "00-c0eac1390a8c4077b6b6049be6405b9d-ae60bddd7d2d7433-00"
}

despues intente instalar manual  lo mismo por igual no abre

### Expected Behavior

que se actualice  

### Steps To Reproduce

intente instalar la actualización automática y no se instalo ahora sale esto
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
  "title": "Not Found",
  "status": 404,
  "traceId": "00-c0eac1390a8c4077b6b6049be6405b9d-ae60bddd7d2d7433-00"
}

### Environment

```markdown
- OS: 
- Sonarr: windows 10 
- Docker Install: 
- Using Reverse Proxy: no
- Browser: chorme 122
- Database:
```

### What branch are you running?

Main

### Trace Logs?

ninguno

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
