### ISSUE TITLE
rTorrent Ratio Groups

### ISSUE THREAD

**Issue by timelf123** [Sonarr/Sonarr#657]
![Screenshot](http://puu.sh/iKhDv/3f7f61c0fe.png)

**Comment by timelf123** [comment]
Just had a brainfart and realized this is for rutorrent. Any plans to support the rutorrent webui?

**Comment by tYGjQCsvVI** [comment]
I'm pretty sure this functionality exists in rTorrent:-

`'group.insert'
'group.insert_persistent_view'
'group.seeding.ratio.command'
'group.seeding.ratio.disable'
'group.seeding.ratio.enable'
'group.seeding.ratio.max'
'group.seeding.ratio.max.set'
'group.seeding.ratio.min'
'group.seeding.ratio.min.set'
'group.seeding.ratio.upload'
'group.seeding.ratio.upload.set'
'group.seeding.view'
'group.seeding.view.set'`

[Source](https://code.google.com/p/gi-torrent/wiki/rTorrent_XMLRPC_reference), although it may been removed in the latest version (Not sure why I believe this, but something in my head is telling me that that has occurred).

**Comment by xelra** [comment]
This would probably become an obsolete feature with per-indexer seedratio and -time support.

**Comment by sataris** [comment]
Given the recent release of the per-indexer seedratio  and -time support. 

Is this still on the agenda?

**Comment by ZerithZA** [comment]
Hi, is there any plans to make this happen? I'm a bit more interested in the removing of torrents once done seeding though.

**Comment by xelra** [comment]
@ZerithZA We have per-indexer seedration and -time support in Sonarr now. There's no need anymore to mock something up yourself in rTorrent.

**Comment by ZerithZA** [comment]
The reason why I asked this is because I have a hosted seedbox from where I sync back the content locally to my synology nas.  During this time it continues being seeded on the seedbox, I set it so that hard links are made at the time of import so when the torrent gets removed from seeding / deleted from the disk, it also remove the link in the sync directory. 

I don't see any nice clean way of currently doing this. I'm somewhat excited for #282 as I'm hoping that it will take away some of the requirements from syncing and better handling of imports in season packs etc.

**Comment by xelra** [comment]
@ZerithZA If you do custom file transfers, you can use the API endpoints to make Sonarr understand what you're doing. That way you can fully integrate any custom processing you're doing on your own into Sonarr's Completed Download Handling.

The endpoint that is probably most interesting to you would be https://github.com/Sonarr/Sonarr/wiki/Command#downloadedepisodesscan.

**Comment by sataris** [comment]
@xelra I'm also interested in this, but according to https://github.com/Sonarr/Sonarr/wiki/Indexer-Seed-Ratio

rTorrent doesn't support this?

**Comment by xelra** [comment]
@sataris Oh, yes. Looks like rTorrent isn't supported. There's probably a reason for that, because if it were possible, I'm pretty sure it would be.

@Taloth What is the reason why this doesn't work? Missing functionality and api in rTorrent?

**Comment by Taloth** [comment]
Nah, rtorrent supports it afaik, it's simply not implemented on our end.

**Comment by timelf123** [comment]
I switched to transmission ¯\_(ツ)_/¯

**Comment by sataris** [comment]
Fair enough, 

It looks like I will be switching to transmission

**Comment by ZerithZA** [comment]
I've always been using transmission but one major thing that I found after switching to rTorrent is that it shows torrents that is trying to fetch metadata and get stuck where as transmission doesn't. This makes it easier to request and bad list these torrents. Also it has native support for cookies per host, which doesnt hurt.
