### ISSUE TITLE
`{Release Hash}` Renaming Token

### ISSUE THREAD

**Issue by Alanoll** [Sonarr/Sonarr#6570]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This an Anime problem, and really only if you want to retain the CRC hash on the files.
e.g. 
```
[FroZen-EviL]_Miyuki_-_06_[DVD][2EDD54DC].mkv
[AEOG][1080p] A Couple of Cuckoos - 02 [BD HEVC 10bit Dual Audio AC3][6FB18E24].mkv
```

At the moment, there's no way to retain the hashes. They are currently parsed via **Parser**, but nothing is retained.

### Describe the solution you'd like

I'd like to add the `{Release Hash}` token (maybe just for Anime to avoid confusion?) to the **FileNameBuilder**.

I don't want to retain anything in the database from the initial parse, but have it be treated similar to `{Original FileName}` where it's reparsed out to make it available via the token at the time of rename. 

If the file is ever renamed without a CRC (via Sonarr or externally), it's gone and would have to be manually re-added to the filename. Sonarr would just have an empty token. Sonarr would never attempt to hash the file itself.

### Describe alternatives you've considered

I used to use Preferred Words to keep the CRC, but it was decided in #5274 not to keep the functionality with the move to CustomFormats.

Even if #6431 is completed, CustomFormats uses the name of the CustomFormat as it's token value and not the matched value.

### Anything else?

I'm just checking to see if there's any push back against the idea. I'll submit the PR. 
I just thought of it when looking into what the effort would be for #6431

**Comment by Alanoll** [comment]
So, I may be missing something.

`{Original Title}` returns the SceneName (and the FileName when SceneName is empty), while `{Original FileName}` is meant to return the filename from `EpisodeFile.Path` or `EpisodeFile.RelativePath`.

https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L1089

But there's a case when `GetOriginalFileName` can return the empty string. Shouldn't the token `{Original FileName}` always returns the filename?

So [this line](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L624) should be passing `true` for the `useCurrentFilenameAsFallback`?

**Comment by markus101** [comment]
Not if it's an existing file, otherwise subsequent renames cause the file name to grow and grow.
