### ISSUE TITLE
Only download episodes from certain day of week

### ISSUE THREAD

**Issue by AdamZane** [Sonarr/Sonarr#6572]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I want to grab episodes hosted by Jon Stewart on the Daily Show, as he only hosts the program on Mondays.
I understand that I can manually uncheck episodes https://ibb.co/9c2RYfB but, as you can see here, they only offer the episodes for a couple of days in the future (In this case March 7th) and thus would force the user to check into sonarr every week rather than functioning as an automatic tool.

Like in this reddit thread https://www.reddit.com/r/sonarr/comments/1amxqaa/just_one_day_a_week/ and this one as well https://www.reddit.com/r/sonarr/comments/1ak1g3q/i_only_want_sonarr_to_grab_daily_show_episodes_on/.

### Describe the solution you'd like

Allow some way to download episodes that occur on a certain day of the week, or to download 1 episode then skip the next 3 (as the daily show does 4 episodes a week and the first is always on Monday)

### Describe alternatives you've considered

Manually unchecking episodes that aren't on Mondays

**Comment by markus101** [comment]
Using the API with something to check the date and monitor based on the day of the week it airs is our recommendation. Given the limited number of future episodes and the fact that this affects only a single series we don't have plans to add functionality to support this.
