### ISSUE TITLE
skyhook parses 10.00pm as 10am

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#658]
Series Mock the Week

**Comment by thezoggy** [comment]
Mock the Week -- http://thetvdb.com/?tab=series&id=79761
`Air Time: 	10.00pm`

http://skyhook.sonarr.tv/v1/tvdb/shows/en/79761
`timeOfDay": {"hours": 10},`

**Comment by Taloth** [comment]
Fixed the parser in skyhook.
