### ISSUE TITLE
Sonarr can't connect with plex

### ISSUE THREAD

**Issue by whitecollar17** [Sonarr/Sonarr#659]
When i try to connect sonnar with plex is not working (i get the erorr: "Unable to connect to Plex Server")  and in my error log i found the following errors:

Message
Unable to connect to Plex Server: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

Exception
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   bij Newtonsoft.Json.JsonTextReader.ParseValue()
   bij Newtonsoft.Json.JsonTextReader.ReadInternal()
   bij Newtonsoft.Json.JsonTextReader.Read()
   bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   bij Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   bij Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   bij Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   bij NzbDrone.Core.Notifications.Plex.PlexServerProxy.CheckForError(String response) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\Plex\PlexServerProxy.cs:regel 124
   bij NzbDrone.Core.Notifications.Plex.PlexServerProxy.GetTvSections(PlexServerSettings settings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\Plex\PlexServerProxy.cs:regel 40
   bij NzbDrone.Core.Notifications.Plex.PlexService.GetSectionKeys(PlexServerSettings settings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\Plex\PlexService.cs:regel 65
   bij NzbDrone.Core.Notifications.Plex.PlexService.Test(PlexServerSettings settings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\Plex\PlexService.cs:regel 114

**Comment by markus101** [comment]
Please use the forums for support.

Check your credentials, or look at Trace logs for the full response.
