### ISSUE TITLE
Sorting has many inconsistencies

### ISSUE THREAD

**Issue by rmichelena** [Sonarr/Sonarr#6590]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Series screen, filter:all, sorting: previous airing (descending)
it's only taking into account the monitored episodes ; e.g. "Young Sheldon", I'm only monitoring the upcoming episodes and one past one: S06E14 ; for the sort, that's the date it takes (S06E14), instead of the actual previous airing (S07E03) which is not monitored. And then any unmonitored series has no "previous airing date" and is put in the list alphabetically. Any upcoming series (of which there is no "previous airing" is also put there alphabetically.

Series screen, filter:all sorting:next airing (descending)
All series that do have a "next airing" date are treated correctly, but then all others are just put alphabetically.

### Expected Behavior

for "previous airing", it should take the actual "previous airing" date (iow the last aired episode), regardless of whether the series or episode are monitored. It will basically sort the series by age.
for "next airing", it should assign the "previous airing" date to series that do not have a "next airing" date. That way the sorting would be logical. Alphabetical never makes sense when sorting by date.

### Environment

```markdown
- OS: Ubuntu 22
- Sonarr: 4.0.2.1183
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: any
- Database:
```

### What branch are you running?

Main

### Trace Logs?

no need

**Comment by markus101** [comment]
This is the intended behaviour. Some discussion around this in https://github.com/Sonarr/Sonarr/issues/6068
