### ISSUE TITLE
Update Sonarr to .NET 8

### ISSUE THREAD

**Issue by Gauvino** [Sonarr/Sonarr#6597]
- [X] I have searched the existing open and closed issues

### Describe the solution you'd like

Update Sonarr to .NET 8

To make it happen :

 - [X] Update project ot .NET 8 : https://github.com/Sonarr/Sonarr/pull/6580
   - Update project to .NET 8
   - Update .NETFramework to 4.8.1
   - Update NuGet packages
   - Update Dockerfile from focal to jammy
   - Fix mono version
- [ ] Remove unsed mono part 
- [ ] Add FreeBSD support for .NET 8

**Comment by markus101** [comment]
What discussion needs to happen in this issue that can't happen in the PR you've already opened?

> Remove unsed mono part

Unless there is something very specific that doesn't work with .net 8 this should not be included.
