### ISSUE TITLE
Tags are seemingly ignored now? Just started happening over the last couple months. 

### ISSUE THREAD

**Issue by ShaneIsrael** [Sonarr/Sonarr#6609]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have tags for all of my anime series so that Sonarr only downloads from specific release groups. These have always worked perfectly up until a couple months ago. I am not sure what changed, but suddenly it seems like sonarr is ignoring my tags and downloading episodes from one specific release group. 

![image](https://github.com/Sonarr/Sonarr/assets/1677199/8246c3fa-72e0-441c-b40e-df267b033a61)

![image](https://github.com/Sonarr/Sonarr/assets/1677199/df5e02b7-2b83-41e8-a943-a3341ea1e014)

Multiple shows I have are now downloading initially from this `-kawaii[EZTVx.to]`. However, if I remove the episode and manually search Sonarr finds the correct episode that matches my tag. 

Here is how I have my tag. This also happens with my other tags for various other release groups as well, and I have them in the exact same format. Again, this only started happening about 2 months ago and I've had sonarr setup this way without issue for a couple years now. 
![image](https://github.com/Sonarr/Sonarr/assets/1677199/786bd4b8-94e2-4982-9e7c-61bdabd16521)

### Expected Behavior

Only download episodes with titles that contain the "must contain" episodes listed in the tags.

### Environment

```markdown
- OS: Unraid
- Sonarr: 4.0.2.1183
- Docker Install: Yes
```

### What branch are you running?

Main

### Trace Logs?

none

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by ShaneIsrael** [comment]
@markus101 this isn't a support question, it's a bug. What makes you think this is a support question?

**Comment by Thirrian** [comment]
My $0.02:
It's a _very_ slim chance of a simple functionality like this suddenly breaking. All support channels would be flooded with users reporting this. There's not even a single "me too" here...

For what it's worth, I have multiple "must contain" rules working fine. Also, seems a bit redundant to include the same term with and without braces. It's just a simple "does the text (release) contain this or not" comparison iirc...

Finally: no evidence of the perceived bug (debug or trace logs) is provided.

If this was at work, where I have dev colleagues who get paid for stuff like this, they'd shrug and close my ticket.

**Comment by ShaneIsrael** [comment]
@Thirrian I have both because releases will often be either `[EMBER] some relase name title etc` or `EMBER some release name title` and like I said, I've had these set without issue for a couple years now and only over the last 2 months have they started picking up the wrong release. What's weird is that its always picking up this "kawaii" release from "EZTV.to". 

Not just my EMBER tag, but I have other tags in the same format. These tags are also specified to only grab releases from my Nyaa.si indexer. However, these releases they are now grabbing are coming from my EZTV indexer. So that to me is very clearly sign of a bug. 

Even if the "must contain" I have is incorrect, the tag clearly states the indexer to use but its instead grabbing stuff from my other indexers. 
![image](https://github.com/Sonarr/Sonarr/assets/1677199/c6addbd3-2305-4757-b8d6-ba4c19d27785)

Here is another example I just found. As you can see it doesn't _always_ happen. This week, it grabbed the correct episode with the `[SubsPlease]` tag. But last week, it grabbed the `kawaii.to` release. 
![image](https://github.com/Sonarr/Sonarr/assets/1677199/f28efbb6-b661-45e1-82da-47211234818d)
![image](https://github.com/Sonarr/Sonarr/assets/1677199/2c6600c0-272b-4d87-a14e-b51aa38ac41d)

Notice the title? It doesn't contain my tag requirements at all.
![image](https://github.com/Sonarr/Sonarr/assets/1677199/7b58f407-7b95-4d37-a5b8-7cca12efa23e)

And when you do an interactive search, that `kawaii.to` release doesn't show up at all. In fact the release it should have grabbed shows up correctly right at the top as you'd expect. 
![image](https://github.com/Sonarr/Sonarr/assets/1677199/2910ca61-2303-4b04-a6ac-a1558ea431fd)

So I have no idea why it is grabbing this `kawaii.to` release from my EZTV indexer when the tag clearly states to only use Nyaa.si and also clearly states that it must container `SubsPlease` or `[SubsPlease]`. 

Something somewhere is bugged. My theory is that the first time it does the search for the episode when a new episode releases, if it doesn't see one that matches the tag, its automatically searching other indexers and grabbing the first thing that comes up that matches the shows name, which seems to always be the `EZTV` release by `kawaii.to`

**Comment by ShaneIsrael** [comment]
Just to add to my last reply, I deleted that `kawaii.to` episode. Told it to re-search (using automatic) and it immediately found the correct episode like it should. So I'm pretty convinced that its only an issue when Sonarr kicks off the first automatic search on a new release. 
![image](https://github.com/Sonarr/Sonarr/assets/1677199/5b375af6-d60f-40f8-a149-76a1129c44c3)

**Comment by markus101** [comment]
Incomplete bug reports that are very likely not bugs aren't going to be kept open. To add onto Thirrian's response, especially when support channels and GitHub issues aren't filled with a "bug" that has existed for months for a heavily used feature. Sometimes our first look is wrong and issues can be reopened when proven to be bugs. Opening bugs for misconfigurations is a waste of everyone's time, I have no doubt if you'd hopped into Discord (for real-time support) this issue would already be resolved.

Your first example doesn't show that the series has the tag `uploader-ember`, but also the release profile is limited to only Nyaa.si, so anything from another indexer would not require that uploader. Your history doesn't show any information about the grabbed release other than it was grabbed. Did that release even come from Nyaa.si? I did a quick search on Nyaa and didn't see a release with that name and given it's tagged with EZTV it's much more likely it came from not Nyaa given they have two releases total with `eztv` in the name.

> when Sonarr kicks off the first automatic search on a new release.

This is not how Sonarr finds episodes, how Sonarr finds episodes is explained in the FAQ.

If you have further questions, please use one of the support channels mentioned above.

**Comment by ShaneIsrael** [comment]
> the release profile is limited to only Nyaa.si
> 

This I believe was the root of the issue. For some reason I misread this as only using this indexer. So my thought was that any show using this tag, would only search from that indexer.
![image](https://github.com/Sonarr/Sonarr/assets/1677199/7dc2de0b-6e5a-4387-80d7-9b5620d710ef)

I believe changing that back to `any` will solve the problem. 

I apologize for stressing that it was a bug, that misunderstanding on my part made it seem very much like a bug. Maybe the wording around that can be improved?
