### ISSUE TITLE
tvdb title slugs with unicode characters not handled correcly

### ISSUE THREAD

**Issue by con-f-use** [Sonarr/Sonarr#6612]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr assumes the tvdb title slug to be unique, but doesn't take into account that tvdb slugs seem to allow unicode and normalizes them to ascii, which leads to collisions.

Seen via the conflict between [Shogun (1980)](https://www.thetvdb.com/series/shogun) which has the slug `shogun` and [Shōgun (2024)](https://thetvdb.com/series/shogun-2021) which also has the slug `shogun`.

![image](https://github.com/Sonarr/Sonarr/assets/11145016/4485ec36-7b5c-49e8-bc0b-abdedfbd407c)

### Expected Behavior

Normalized title-slug includes the year.

### Steps To Reproduce

1. Add Shogun 1980
2. Try and fail to add Shogun 2024

### Environment

```markdown
- OS: NixOS 23.11
- Sonarr: 3.0.10.1567
- Docker Install: no
- Using Reverse Proxy: nginx
- Browser: firefox
- Database: any
```

### What branch are you running?

Main

### Trace Logs?

```
Invalid request Validation failed: 
 -- TitleSlug: Title slug 'shogun' is in use by series 'Shogun'. Check the FAQ for more information
```

**Comment by markus101** [comment]
> Sonarr: 3.0.10.1567

Time to upgrade to v4.

It's best to report these issues on Discord as it's not a bug with Sonarr directly, it'll be fixed when when the various caches with Skyhook expire.
