### ISSUE TITLE
Add rename token: 'remaining custom formats'

### ISSUE THREAD

**Issue by gehrleib** [Sonarr/Sonarr#6615]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The new "{Custom Format:Format}"  allows you to choose the location of a custom format within renaming. However, when used with "{Custom Formats}", it creates a duplicate. Without this new token, multiple "{Custom Format:Format}" entries would be necessary for other formats, such as the web source, which would make the renaming convention rather long.

### Describe the solution you'd like

I'd like a new "{Remaining Custom Formats}" that would use all remaining custom formats that are not already mentioned in a {Custom Formats:Format}.

For example, 

{Series TitleYear} - S{season:00}E{episode:00} - {Episode Title} {Custom Format:Repack} ({Quality Title} {Remaining Custom Formats} {Mediainfo VideoCodec} {MediaInfo VideoBitDepth}bit {MediaInfo VideoDynamicRangeType} {Mediainfo AudioCodec}{ Mediainfo AudioChannels} {Release Group})

Whereas {Remaining Custom Formats} would include values such as the source, e.g. AMZN.

Otherwise, we would have to do something similar to:

{Series TitleYear} - S{season:00}E{episode:00} - {Episode Title} {Custom Format:Repack} ({Quality Title} {Custom Format:AMZN}{Custom Format:HBO}{Custom Format:DSNP},etc... 

### Describe alternatives you've considered

To use a "{Custom Format:Format}" for every format.

or

Allow {Custom Format:Format} to work on formats that have "Include Custom Format when Renaming" deselected so that we can specify formats that would not be included in "{Custom Formats}" to prevent duplicity.

### Anything else?

Nope

**Comment by markus101** [comment]
This is probably best implemented as `{CustomFormats:-}` where the `-` is followed by a comma separated list of names to exclude, this would match the existing behaviour of media info tokens. This would be more consistent with other methods and not require tracking of tokens through the whole renaming process.
