### ISSUE TITLE
Start of the week in calendar view is a day off as well as it's recognising today as the wrong day (i.e. it thinks it's Sunday when it's Monday)

### ISSUE THREAD

**Issue by acollien** [Sonarr/Sonarr#6619]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Calendar view is off by a day in some views. 
Looking in Calendar, Sonarr is registering that it's Sunday, when it's currently Monday.
It is also showing the wrong week start-day. I have it set to Monday, but it's showing Sunday.

- WeekView - showing that it's currently Sunday, when it is in fact Monday. Also showing Sunday as start of week when I have it set to Monday.
- ForecastView - showing it's 'Yesterday' (Sunday), when it's currently 'Today' (Monday). This view is also showing Friday (2 days behind) as the start of the week - unsure if this is intended, but 'Forecast' suggests future, not past.
- AgendaView - This is showing the next thing on is Monday, but I supect this is because I have no shows on Sunday, so guessing if I did, it would show that it's still Sunday here too (1 day behind)
- DayView - Showing it's Sunday, when it's currently Monday

### Expected Behavior

Expected to see the current day highlighted in-line with current timezone (AUS/Hobart), which should be Monday.
Also expect to see Monday as the start of the week.

### Steps To Reproduce

1. Click Calendar.
2. Click any calendar view (day/week/month/forecast/Agenda)
NB: I checked that the container has the correct date/time. Set it again. Rebooted docker. Also checked that unRAID (my OS) has correct timezone.

### Environment

```markdown
- OS: Docker via unRAID
- Sonarr: 4.0.2.1183
- Docker Install: 24.09
- Using Reverse Proxy: No
- Browser: Edge/Chrome/Firefox/Opera/Duckduckgo
- Database: Sqlite 3.44.0
```

### What branch are you running?

Main

### Trace Logs?

[tracelog.txt](https://github.com/Sonarr/Sonarr/files/14556472/tracelog.txt)

### Anything else?

![DayView](https://github.com/Sonarr/Sonarr/assets/8148297/70b915f6-31da-486e-8f25-8b856a6bd97c)
![AgendaView](https://github.com/Sonarr/Sonarr/assets/8148297/2bddbcb7-fbf2-4c14-ba0a-cc98e3f299e7)
![ForecastView](https://github.com/Sonarr/Sonarr/assets/8148297/77921d0e-4998-4115-ab89-a9b1a6265779)
![WeekView](https://github.com/Sonarr/Sonarr/assets/8148297/42da9291-360a-40fe-914f-86fe287b03d7)

**Comment by markus101** [comment]
You can change the starting day of the week in the options for the calendar.

The current date/time is determined from the computer the browser is running on, if you're using a private browsing feature that changes your timezone to UTC then it will be wrong, if your date/time/timezone on the computer are wrong it will be wrong.

Given it's early Tuesday morning in AUS/Hobart I was able to verify that Tuesday is correctly selected without issue.

![image](https://github.com/Sonarr/Sonarr/assets/413544/b43f82bc-cc15-4bc0-8520-ede048652411)

If you want to investigate further, please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by acollien** [comment]
@markus101 

I've double-check everything.
Unraid server has correct time zone (AUS/Hobart)
The docker container Sonarr is running is correct too.
The machine/s I access it, via the browser on, are all correct time zone too - not using any VPN/proxies or private browsing. All caches/cookies cleared.
Monday is the day set for 1st day of the week in Sonarr settings (though I toggled from one to the other just for the sake of it - no avail.)
Time of writing this, for me is, ~1:40PM (NB: exact time is out as it took time to get each window in place to screenshot) Tuesday 12-MAR. Sonarr is still highlighting yesterday - Monday - as if it's today, and showing Sunday as week start (which it definitely set to Monday in settings)

Attached - image shows what Sonarr is showing re: day behind, terminal window of the Unraid server showing date/time, terminal window of the docker container showing date/time, and windows clock app showing date time.

![synced](https://github.com/Sonarr/Sonarr/assets/8148297/9fbd0a28-66b7-452e-ae12-9489543fadba)
