### ISSUE TITLE
choose torrent based on number of seeds

### ISSUE THREAD

**Issue by 4rtemis-4rrow** [Sonarr/Sonarr#6620]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

a lot of the times, sonarr would choose torrents that are 10s of gigabytes in size, with only a few seeds, idk about other people, but for me, that's too few seeds

and when I look at sites like 1337x.to, I find the same show but in smaller size and  hundereds of seeds

### Describe the solution you'd like

an option to choose the torrent with highest number of seeds, as long as said torrent meets a required quality

### Describe alternatives you've considered

honestly, nothing comes to mind, I'm not waiting days for a single show to finish downloading

**Comment by markus101** [comment]
https://wiki.servarr.com/sonarr/faq#how-are-possible-downloads-compared

If qualities are grouped and no CF rules apply the number of seeds will apply in most scenarios. No plans to change the order in which these "rules" apply.
