### ISSUE TITLE
Multi-part episode numbering breaks when episode numbering changes from 99 to 100 within same file

### ISSUE THREAD

**Issue by bugmancx** [Sonarr/Sonarr#6631]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Episodes named, for example "Showname.S01E95-96-97-98-99-100.Title.mkv" will recognise the sequence of numbers 96-99 and process and associate those episodes, but it does not recognise the "-100" as episode 100, potentially due to the change in the number of digits from 99 to 100 in the same filename.

In the trace logs, you can see that Sonarr is only processing this file for the episodes 95-99 and ignoring 100.

### Expected Behavior

Sonarr should recognise that the number sequence goes beyond 2 digit to 3 digit.

### Steps To Reproduce

1. Name any multi-part episode file as S01E95-96-97-98-99-100
2. Rescan episodes.
3. Notice that the episode 100 is ignored.

### Environment

```markdown
- OS: Debian
- Sonarr: 4.0.2.1341
- Docker Install: 25
- Using Reverse Proxy: Yes
- Browser: Firefox
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/14638484/sonarr.trace.txt)

**Comment by markus101** [comment]
Please link to the trace logs that show the whole import process, including the parsing (the most important part when raising an issue with parsing).

**Comment by bugmancx** [comment]
In this case they were existing files in the show directory which were detected during a series refresh. I did not go via the importer.

**Comment by bugmancx** [comment]
[input-sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/14639125/input-sonarr.trace.txt)
Here is the show detecting only 4/5 episodes via the Manual Import method
