### ISSUE TITLE
Download decision comparison not working as expected

### ISSUE THREAD

**Issue by lldsolitude** [Sonarr/Sonarr#6636]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

During automatic search, among torrent releases with the same quality, CF score, episode count/number (all season packs) from the same indexer, the release with fewer peers is selected instead of the release with the most peers.
Apparently the release comparison process wasn't logged even in trace log. After all releases found were processed and some deemed accepted, the wrong release was directly sent for download without any log entry explaining why it was selected among the accepted releases.
![screenshot](https://github.com/Sonarr/Sonarr/assets/11805475/0d108619-3b8b-46c7-844e-6c0845317005)

### Expected Behavior

Among torrent releases with the same quality, CF score, episode count/number from the same indexer, the release with the most peers should be selected.

### Environment

```markdown
- OS: Debian 12
- Sonarr: 4.0.2.1183-ls230 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Edge 122.0.2365.92
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/14662607/sonarr.trace.txt)

**Comment by stevietv** [comment]
The [decision engine](https://github.com/Sonarr/Sonarr/blob/381ce61aefd9ea3e48fbef2c13ac9c81b4442a07/src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs#L136C1-L150C1) works on a rounded Log10 base for number of Seeders

Math.Round(Math.Log10(32)) = 2
Math.Round(Math.Log10(103)) = 2

so they are considered equal for seeders/peers

**Comment by lldsolitude** [comment]
> The [decision engine](https://github.com/Sonarr/Sonarr/blob/381ce61aefd9ea3e48fbef2c13ac9c81b4442a07/src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs#L136C1-L150C1) works on a rounded Log10 base for number of Seeders
> 
> Math.Round(Math.Log10(32)) = 2 Math.Round(Math.Log10(103)) = 2
> 
> so they are considered equal for seeders/peers

I see... So basically any number between 32 and 320 is considered sufficient for finishing the download with reasonable speed.
In my case, since number of peers was considered equal, the release closest to preferred size was selected.
