### ISSUE TITLE
Tags being removed after "Refresh & Scan"

### ISSUE THREAD

**Issue by vchatela** [Sonarr/Sonarr#6638]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I set a tag on a serie, then I hit "Refresh & Scan" and new tag is being removed.
Before :
![image](https://github.com/Sonarr/Sonarr/assets/6717940/88c55121-c662-4e29-bc70-fbbd0393f17f)
After refresh & scan : 
![image](https://github.com/Sonarr/Sonarr/assets/6717940/7d68826f-d381-4a82-baaf-fcb9b9897595)

See log attached
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/14671000/sonarr.txt)

### Expected Behavior

Tags must be persistent

### Environment

```markdown
- OS: Docker on Synology
- Sonarr: Version 4.0.2.1183
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/14671007/sonarr.txt)

**Comment by markus101** [comment]
This is most likely caused by Auto Tagging rules (Settings: Tags) you've setup as those can be removed if they no longer apply and those changes are logged, but no at info, which is why you were asked for Trace logs.

**Comment by vchatela** [comment]
Thanks a lot @markus101, very clear. I misunderstood this auto tagging configuration, so I fixed it. We can close. Thanks again!
