### ISSUE TITLE
Series with international characters gets unlinked (Shōgun)

### ISSUE THREAD

**Issue by nodrood** [Sonarr/Sonarr#6657]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

As soon as an episode is imported, it gets unlinked. It only happens to series with international characters in them. (I've noticed the same behavior in Radarr, for instance Hammarskjöld just now.)

### Expected Behavior

I expect Sonarr to handle 'ō' as 'o', or as 'ō' – but _not_ as an unexpected character.

It might be a language setting that I need to change, but I can't find any clues in any other bug reports.

### Environment

```markdown
- OS: macOS Monterey
- Sonarr: 4.0.2
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
- Database: ?
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/14747414/sonarr.trace.txt)

### Anything else?

2024-03-25 18:14:24.7|Debug|Parser|Parsing string 'Shōgun 2024 S01E05 Broken to the Fist 1080p DSNP WEB-DL DDP5 1 H 264-NTb'
2024-03-25 18:14:24.7|Debug|SceneMappingService|Found scene mapping for: Shōgun 2024. TVDB ID for mapping: 392573
**2024-03-25 18:14:24.7|Debug|AggregateLanguages|Language couldn't be parsed from release, fallback to series original language: English**
2024-03-25 18:14:24.7|Debug|AggregateLanguages|Selected languages: English
2024-03-25 18:14:24.7|Debug|TrackedDownloadService|Tracking 'SABnzbd:Shōgun 2024 S01E05 Broken to the Fist 1080p DSNP WEB-DL DDP5 1 H 264-NTb': ClientState=Completed SonarrStage=Downloading Episode='Shōgun 2024 - S01E05 WEBDL-1080p v1' OutputPath=/Volumes/mardrom/#downloads/complete/sonarr/Shōgun 2024 S01E05 Broken to the Fist 1080p DSNP WEB-DL DDP5 1 H 264-NTb.

**Comment by markus101** [comment]
![image](https://github.com/Sonarr/Sonarr/assets/413544/a75bd3c8-9815-471f-9a7a-2041ae85e186)

This appears to be an issue with your system, likely an issue with the file system not properly handling unicode characters. 
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by stevietv** [comment]
ref reddit issues: 
* https://www.reddit.com/r/sonarr/comments/1bofzpv/if_the_name_of_a_tv_folder_contains_a_character/
* https://www.reddit.com/r/sonarr/comments/1bofzpv/if_the_name_of_a_tv_folder_contains_a_character/

**Comment by markus101** [comment]
Thanks for reopening and digging into this issue @stevietv!

**Comment by rr0ss0rr** [comment]
> It appears that Mac OS X stores unicode characters decomposed, causing the comparisons to fail. The strings will need to be normalised before comparison.

How would one normalize the Folder/Series/Episode Name?  I've tried {Series CleanTitle} and {Episode CleanTitle} with no change.  Sonarr wants to rename them back with the diacritical mark.
