### ISSUE TITLE
Multiple Root Folders

### ISSUE THREAD

**Issue by davidbaguetta1** [Sonarr/Sonarr#6658]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, a show always has one root folder. This means you can’t have that same show in multiple folders at the same time, so you are forced to share that show’s folder with every other user. This leads to a less personalized experience in your media server (your shows library has other users’ shows you are not interested in) and less private (users can guess and judge what other users watch if the library isn’t large)

### Describe the solution you'd like

Have the possibility of specifying multiple root folders for a show. When sonarr imports the show, instead of just hard linking into one folder, it gets hard linked to all the specified root folders.
Each user would only have access in the media server to their own folder.

### Describe alternatives you've considered

The only current alternatives are:
- **Use 1 sonarr instance for all users,** and have the same shows available for everyone. This is what almost everyone does and has gotten used to.
**_Pros:_** Easier to manage 
**_Cons:_** Less organized, less personalized, less private (in media server)
- **Use multiple Sonarr instances, one for each user.** Each user only interacts with their own instance, which downloads to their own folder, and has 0 knowledge of other users libraries. 
**_Pros:_** More private and personalized to each user. 
**_Cons:_** Have to maintain multiple sonarr instances (Quality Profiles, CFs…); have to redownload same content multiple times if more than one user wants to watch it (using more ratio and storage space than necessary); more difficult to scale the more users there is.

### Anything else?

This is how I would depict an ideal scenario for this feature if it also later integrates with Overseerr

1. Bob requests Game of Thrones in Overseerr (using his own `/data/media/bob` folder)
2. Sonarr downloads the show and imports it into `/data/media/bob`
3. A month later, Amy decides to request Game of Thrones in Overseerr as well (using her own `/data/media/amy` folder)
4. Sonarr knows it has already downloaded this show before for Bob, so it skips downloading it again and just creates a new hardlink for `/data/media/amy`)

This feature could finally provide an option to split libraries per user instead of having a global library for everyone (for those that which to do that)

**Comment by markus101** [comment]
I don't see this being something we'll support, especially in the short term, but you might be an able to achieve something with custom scripts that run after files are imported.
