### ISSUE TITLE
Media Management Folder Bug

### ISSUE THREAD

**Issue by tbutz12** [Sonarr/Sonarr#6660]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When selecting media management -> Folders, there are two options, one for Create and one for Delete. As it sits, both options are able to be enabled.

### Expected Behavior

Toggling one option should disable the other.

### Steps To Reproduce

1. go to sonarr page
2. go to media management
3. go to folders section
4. enable one of the options
5. select the other option

### Environment

```markdown
- OS: Unraid
- Sonarr: binhex
- Docker Install: 24.0.9, build 2936816
- Using Reverse Proxy: no
- Browser: firefox
- Database:
```

### What branch are you running?

Main

### Trace Logs?

I enabled trace logging, restarted container, and clicked "save changes" after enabling both, but there were 0 logs for that event thats housed in the UI for logging, therefor I am not including trace logs.

**Comment by thezoggy** [comment]
this is by design, and there are github issues about it before or even todays chat about it in discord or here is one not to long ago also
![ArmCord_2024-03-26_11-55-02](https://github.com/Sonarr/Sonarr/assets/500882/c9936155-ad57-4d1b-a764-b0e48494ee8f)

**Comment by tbutz12** [comment]
I'm not in the discord, therefor did not see it. I searched media management folder and the create delete text and found no github issues, but maybe I didn't search properly. Thanks.

**Comment by bakerboy448** [comment]
https://github.com/Sonarr/Sonarr/commit/4f15cd55be5f7332ebde608d8b438384865e9dc1
