### ISSUE TITLE
Get a localized poster for the language I have chosen instead of default english poster.

### ISSUE THREAD

**Issue by DavidHenryThoreau** [Sonarr/Sonarr#6663]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Get a localized poster for the language I have chosen instead of default english poster.

### Describe the solution you'd like

Search if Sonarr language is set for example as french and if french poster exists download french poster

### Describe alternatives you've considered

Sonarr can fetch from another website  in order to get a localized poster for the language I have chosen to get good poster.

### Anything else?

Can you add any information : (poster, description,..) in language I have chosen instead of default english

I've also opened a feature request for radarr too.
https://github.com/Radarr/Radarr/issues/9863

**Comment by markus101** [comment]
Metadata language is not the same as the UI language, this is part of https://github.com/Sonarr/Sonarr/issues/269
