### ISSUE TITLE
Change/disable "Refresh Series" scheduled task interval

### ISSUE THREAD

**Issue by Suddow** [Sonarr/Sonarr#6665]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I don't need an 8 minute scan of all my existing files and series every 12 hours.  It's a pointless read operation on my drives, sonarr already handles the downloads and updating what it needs to as the files are downloaded.  

### Describe the solution you'd like

Option to adjust the interval or disable the task.

### Describe alternatives you've considered

The only alternative is removing the series from the list, which is counterproductive.

**Comment by markus101** [comment]
There is an option for this already.

![image](https://github.com/Sonarr/Sonarr/assets/413544/db89bf71-cb81-42d9-945f-6b21a6b231eb)

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/sonarr/faq#why-does-sonarr-refresh-series-information-so-frequently

**Comment by markus101** [comment]
You can't stop Sonarr from refreshing series data, you can stop it from rescanning the disk.

**Comment by markus101** [comment]
Yes, completely normal, logs, database, images are in the config folder. Logs are rotated (debug/trace will log more), up to 50 1MB files for debug/trace.
