### ISSUE TITLE
Pushes from autobrr don't get their RSS key cleansed in logs

### ISSUE THREAD

**Issue by nuxencs** [Sonarr/Sonarr#6666]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When a BHD announce from autobrr get's sent to Sonarr, the RSS key will not be cleansed from the logs.

`2024-03-27 14:54:47.6|Info|ReleasePushController|Release pushed: The Good Doctor S07E04 Date Night 1080p AMZN WEB-DL DDP 5.1 H.264-FLUX - https://beyond-hd.me/torrent/download/auto.343576.non-removed-rss-key`

### Expected Behavior

The RSS key should be removed from the logs like for example the API key for Prowlarr.

### Steps To Reproduce

1. click download logs
2. RSS key is not removed

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Sonarr: 4.0.2.1367
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: 124.0.1
- Database: Sqlite 3.44.2
```

### What branch are you running?

Develop

### Trace Logs?

Don't have trace logs but these debug ones should show the issue.
I replaced all the real RSS keys with `key`.

https://logs.notifiarr.com/?5ce6471fdca090c0#JCVSWMuhvsXKFoSF9MsZVyYKdcVVi4H9jnQZH45ffwoH

**Comment by bakerboy448** [comment]
Probably relevant

https://github.com/Prowlarr/Prowlarr/commit/b1f7d300212b8597d881ec2631c86ff87c1556cc

in general: https://github.com/Prowlarr/Prowlarr/blob/develop/src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs
