### ISSUE TITLE
 crawl files bugs. A big problem

### ISSUE THREAD

**Issue by wanglinyuan1979** [Sonarr/Sonarr#6669]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Unable to correctly crawl files like "Above the Rivers S01E01-E26 2024 2160p WEB-DL H.265 AAC-HHWEB" or "Above the Rivers S01E25-E26 2024 2160p EDR WEB-DL HEVC DDP2.0-HDVWEB", but able to crawl correctly Take "Above the Rivers S01 2024 2160p WEB-DL H.265 AAC-HHWEB". This is a very big problem.

### Expected Behavior

 correctly crawl files like "Above the Rivers S01E01-E26 2024 2160p WEB-DL H.265 AAC-HHWEB" or "Above the Rivers S01E25-E26 2024 2160p EDR WEB-DL HEVC DDP2.0-HDVWEB".

### Environment

```markdown
- OS: windows 10
- Sonarr: 4.0
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Main

### Trace Logs?

Unable to correctly crawl files like "Above the Rivers S01E01-E26 2024 2160p WEB-DL H.265 AAC-HHWEB" or "Above the Rivers S01E25-E26 2024 2160p EDR WEB-DL HEVC DDP2.0-HDVWEB", but able to crawl correctly Take "Above the Rivers S01 2024 2160p WEB-DL H.265 AAC-HHWEB".

**Comment by markus101** [comment]
Sonarr has no problems parsing those release names, but may not find them when searching if your indexer doesn't return them for some reason, but 
please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
