### ISSUE TITLE
Some downloads will not be fully added to queue

### ISSUE THREAD

**Issue by MrGundum** [Sonarr/Sonarr#6677]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When manually downloading a file the file does not get added to the download queue window in sonarr.
It successfully gets sent to the download client.
It say's added to queue in sonarr.
It shows in queue history as completed.
It does not import the file.

"added to download queue"
![image](https://github.com/Sonarr/Sonarr/assets/24597120/18262027-fea0-40f8-814a-b48c846184ea)

Doesn't actually show up in the queue 
![image](https://github.com/Sonarr/Sonarr/assets/24597120/04977618-64bd-4577-b526-ee83cbc2633f)

Shows as grabbed and sent to download client
![image](https://github.com/Sonarr/Sonarr/assets/24597120/32b9a93a-d9e0-44d2-ba99-5d6d1dd273cf)

Client downloaded successfully
![image](https://github.com/Sonarr/Sonarr/assets/24597120/e0f2bfcf-234f-4776-96bf-cb447fd5b027)
![image](https://github.com/Sonarr/Sonarr/assets/24597120/12fcf942-506a-4512-b3f2-14d8fbbdfc02)

Not imported still listed as missing
![image](https://github.com/Sonarr/Sonarr/assets/24597120/0125b689-45e2-420b-8738-cac19068a0f1)

### Expected Behavior

The manually downloaded file to be added to the queue and imported on download completion

### Steps To Reproduce

Manually download a file.

### Environment

```markdown
- OS: Unraid 6.12.6
- Sonarr: 4.0.3.1413
- Docker Install: Yes
- Using Reverse Proxy: no
```

### What branch are you running?

Main

### Trace Logs?

https://gist.github.com/MrGundum/f33a9936358300cddca5e84fbfe9ff75

### Anything else?

I have a feeling it may have something to do with the docker pathing but im not sure. Most of the time everything works fine. It is only the manual downloading that is really having issues.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Your logs don't show the response from your download client for the queue/history, but check that the category for those items matches the category Sonarr is using.
