### ISSUE TITLE
Episodes are not automatically unmonitored after DiskScanService cleans media file in DB

### ISSUE THREAD

**Issue by cospking** [Sonarr/Sonarr#6678]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After the recent update **4.0.3.1413**, it seems disk scanning is working differently or incorrectly.
In previous versions after deleting a file and pressing Update All with Sonarr, said TV-show would go from 1/1 to 0/0 and automatically unmonitor given episode.

However after the recent update it sticks to 0/1 and scanning monitored redownloads the episode I've previously deleted.

**Despite trace log showing:**
> 2024-04-02 12:53:44.2|Debug|DiskScanService|[392573][Shōgun] Cleaning up media files in DB
> 2024-04-02 12:53:44.2|Debug|MediaFileTableCleanupService|File [D:\Downloads\Series\Shōgun (2024)\Shogun.2024.S01E07.DV.HDR.2160p.WEB.H265-SuccessfulCrab.mkv] no longer exists on disk, removing from db
> 2024-04-02 12:53:44.2|Trace|EventAggregator|Publishing EpisodeFileDeletedEvent

===
This happens to other series without any special symbols in it's name such as **Curb your Enthusiasm**

> 2024-04-02 12:57:48.1|Debug|DiskScanService|Scanning 'D:\Downloads\Series\Curb Your Enthusiasm' for video files
> 2024-04-02 12:57:48.1|Trace|DiskScanService|0 files were found in D:\Downloads\Series\Curb Your Enthusiasm
> 2024-04-02 12:57:48.1|Debug|DiskScanService|0 video files were found in D:\Downloads\Series\Curb Your Enthusiasm
> 2024-04-02 12:57:48.1|Trace|DiskScanService|Finished getting episode files for: [76203][Curb Your Enthusiasm] [00:00:00.0012507]
> 2024-04-02 12:57:48.1|Debug|DiskScanService|[76203][Curb Your Enthusiasm] Cleaning up media files in DB
> 2024-04-02 12:57:48.1|Debug|MediaFileTableCleanupService|File [D:\Downloads\Series\Curb Your Enthusiasm\Curb.Your.Enthusiasm.S12E09.Ken-Kendra.1080p.AMZN-WEB-DL.DDP5.1.HEVC-X265.POOTLED.mkv] no longer exists on disk, removing from db

### Expected Behavior

1: Sonarr automatically downloads episode
2: I watch the episode
3: I remove file from folder after I finished watching it
4: I press 'Update all' in Sonarr which should unmonitor the episode I just removed.

### Steps To Reproduce

1: Remove file from folder (keep empty folder)
2: Update All in Sonarr

Optional: Search Monitored

### Environment

```markdown
- OS: Windows 11
- Sonarr: 4.0.3.1413
- Docker Install: N/A/
- Using Reverse Proxy: No
- Browser: Firefox
- Database: Sqlite 3.36.0
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/14835587/sonarr.trace.txt)

### Anything else?

**Relevant settings:**
Create Empty Series Folders = Off
Delete Empty Folders = On
Rescan Series Folder after Refresh = Always
Unmonitor Deleted Episodes = On

**Screenshots of the two shows in Sonarr after Update All;**
https://imgur.com/a/1mySKOm

**Comment by cospking** [comment]
> Is `Unmonitor Deleted Episodes` enabled?

Ah yes forgot to add that to Relevant settings, that one is turned on yes:
![firefox_nhH0NwzCVj](https://github.com/Sonarr/Sonarr/assets/108274310/4ad95239-29ae-4bc3-aad5-9a5603161e73)

**Comment by stevietv** [comment]
Any chance we can get a copy of the trace logs where this occurs, your logs are starting after the two quoted excerpts

**Comment by cospking** [comment]
> Any chance we can get a copy of the trace logs where this occurs, your logs are starting after the two quoted excerpts

[sonarr.trace.30.txt](https://github.com/Sonarr/Sonarr/files/14841764/sonarr.trace.30.txt)
[sonarr.trace.31.txt](https://github.com/Sonarr/Sonarr/files/14841767/sonarr.trace.31.txt)
[sonarr.trace.32.txt](https://github.com/Sonarr/Sonarr/files/14841768/sonarr.trace.32.txt)
[sonarr.trace.33.txt](https://github.com/Sonarr/Sonarr/files/14841769/sonarr.trace.33.txt)

One of these should contain the information required, I only started logging trace after that time.
