### ISSUE TITLE
Extended times for scheduled tasks 

### ISSUE THREAD

**Issue by medwards180** [Sonarr/Sonarr#6692]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have a lot of user created lists for artists.  Many of them have passed away, so the likelihood that an import will find something new is low. 

### Describe the solution you'd like

I would like a way to configure the frequency of list imports. This could be done as a config on the list page (for global) or on the individual monitor page of a single list. 

I second related would be when the last item was added by the import of a list. 

### Describe alternatives you've considered

I’m considered going through my list of imports looking for deceased actors in order to disable the lists.  That option is very time consuming and the list needs to reenable every so often to make sure something isn’t missed.

**Comment by markus101** [comment]
Same as https://github.com/Sonarr/Sonarr/issues/6427 we have no plans to allow interval configuration.
