### ISSUE TITLE
Health check for Writable Update Folder

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#671]
Health checks show no issues.. however when trying to update or switch branches it errors out with:
`Update process failed: Cannot install update because startup folder '/opt/NzbDrone' is not writable by the user 'username'.`

seems like this could be easily caught and shown? i cant see anyone wanting to do this by design.. and if they did.. offer a way to suppress the error for the session (reset on each update/reboot).

**Comment by markus101** [comment]
There is already a health check in place for this: https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/HealthCheck/Checks/UpdateCheck.cs#L32 which runs on start up and every few hours (I forget offhand), if you restart Sonarr do you get that error message (might take a minute to run).

Dismissing them is in another issue: https://github.com/Sonarr/Sonarr/issues/481
Unless the current health check is bugged about the only thing we may be able to do if publish a warning via health check in realtime, which would be something we might be able to look at down the road.

//cc @Taloth

**Comment by thezoggy** [comment]
yeah, doesnt look like its working (keith is on master.. so not sure if it has it). i only discovered the issue when trying to move him over to develop and found out that i couldnt...

**Comment by Taloth** [comment]
Health check is only shown when auto-update is enabled.

**Comment by markus101** [comment]
Guess I should have read the code :unamused: - realtime health checks would still be nice :smile:

**Comment by thezoggy** [comment]
makes sense.. he does not have auto update enabled

**Comment by markus101** [comment]
Opened up a new proposed issue for handling events and running health checks.

https://github.com/Sonarr/Sonarr/issues/677
