### ISSUE TITLE
Feature Request - Honor custom formats from release name and media details in addition to file name.

### ISSUE THREAD

**Issue by ZachRL94** [Sonarr/Sonarr#6710]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When using Sonarr, files sometimes get picked up on the basis of the release name matching a custom format, but the files contained therein don't. As an example, for anime, something such as  `[Release Group] Title - SXXEXX (WEB 1080p x264 AAC) [Dual-Audio] | Japanese Title | Other Media Info` may get picked up on the basis of being dual audio, but when the file is downloaded, the file name is closer to `[Release Group] Title - SXXEXX (WEB 1080p x264 AAC) [FILEHASH].mkv `

This behavior results in Sonarr picking up content thinking that it matches a custom format. Unfortunately, when the content is downloaded, because some of the custom formats are not presented in the file name, the quality score for the file is dropped. In many cases, this quality score being dropped prevents the file from automatically being imported. Moreover, for file renaming, the custom format is not appended to the file name. Above all else, it also means that Sonarr will go and fetch a new file.

### Describe the solution you'd like

When configuring custom formats, provide an option for Sonarr to honor custom formats from the release name when importing the content. This options would coexist with the current behavior of honoring file names. This would allow for more flexibility for the users.

Moreover, another idea to assist in this is to allow Sonarr custom formats to also honor the contents provided by the file's metadata. If "Dual Audio" fails to be present in the filename, Sonarr could instead reference the file's metadata and see that the contents therein are 

`Audio Channels
2
Audio Codec
AAC
Audio Languages
eng/jpn
Audio Stream Count
2
Video Bit Depth
10
Video Codec
x265
Video Fps
23.976
Resolution
1920x1080
Run Time
23:42
Scan Type
Progressive
Subtitles
eng/eng`

Rather than relying exclusively on filenames for custom format matching, Sonarr should also have options to _optionally_ honor the contents of the metadata when evaluating the custom format score AFTER download. This data is often present in filenames, but just as often, it isn't and is part of the release name. Allowing users to have the flexibility to evaluate these values after downloading the file will allow for a smoother file import process and less headaches.

As a side note, I understand that files can be renamed in accordance with the file meta data already. I see no reason why that information can't be used when evaluating custom conditions as well.

Something like this would be phenomenal!

![image](https://github.com/Sonarr/Sonarr/assets/102282734/7c7a00a6-25f2-4012-b95c-9d95629c53f4)

### Describe alternatives you've considered

The best alternative would be to stop using releases that don't offer consistent file names. This would be ideal but is not realistic and proves to be a chore.

**Comment by augustuen** [comment]
Covered by #5598
