### ISSUE TITLE
Sonarr error: Database is locked

### ISSUE THREAD

**Issue by mreid-tt** [Sonarr/Sonarr#6716]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I recently installed the SynoCommunity package version 20240114-4 for Sonarr v4 on my DS920+ (x86_64). Over the past 2-3 weeks, I've noticed that a particular series isn't updating from TVdb. Upon investigating the logs, I discovered a recurring "database locked" error.

### Expected Behavior

All series should be updating as expected.

### Steps To Reproduce

1. Connect to WebUI
2. Go to a Series
3. Hit "Refresh Series"

### Environment

```markdown
- OS: DSM 7.2.1-69057 Update 4
- Sonarr: 4.0.3.1413
- Docker Install: N/A
- Using Reverse Proxy: N/A
- Browser: Chrome (Windows)
- Database: Sqlite 3.40.0
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.traces.txt](https://github.com/Sonarr/Sonarr/files/14956960/sonarr.traces.txt)

### Anything else?

Issue raised on behalf of user report at https://github.com/SynoCommunity/spksrc/issues/6070.

**Comment by stevietv** [comment]
the database being locked is not an issue.
Episode information not being updated is a result of an ongoing issue with the TVDB API not returning all the information is should - see this issue for reference: https://github.com/thetvdb/v4-api/issues/323
