### ISSUE TITLE
Sonarr stopped sync 1 of tv series from thetvdb

### ISSUE THREAD

**Issue by joskis** [Sonarr/Sonarr#6717]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Link of TV Series https://thetvdb.com/series/farai

Last sync was in the end of march

Sonarr info

Version 4.0.3.1413
.NET Yes (6.0.13)
Database Sqlite 3.40.1
Database Migration 205
AppData Directory /var/lib/sonarr
Startup Directory /opt/Sonarr
Mode Console

I have tried to install sonarr on different PC and got the same problem

### Expected Behavior

The series is not synced, but the rest tvdb syncs fine

### Steps To Reproduce

Add farai to sonarr

### Environment

```markdown
- OS: Debian 12
- Sonarr: 4.0.3.1413
- Docker Install: No
- Using Reverse Proxy: No 
- Browser: Edge/Chrome
- Database: sql lite
```

### What branch are you running?

Main

### Trace Logs?

I have no log for this

**Comment by stevietv** [comment]
Is because of a known issue with TVDB API:
https://github.com/thetvdb/v4-api/issues/323
