### ISSUE TITLE
Custom Format Improvements

### ISSUE THREAD

**Issue by johnkennyuk** [Sonarr/Sonarr#6738]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The current design of the Sonarr V4 Custom Format (CF) settings GUI has led to some challenges and frustrations. The scoring system in V4 is difficult to understand and use effectively. Additionally, some functionalities present in versions prior to V4 have been lost, and the current CF design cannot compensate for these missing features. There are also issues with profiles ignoring CFs and selecting titles below the profile’s minimum score.

### Describe the solution you'd like

I propose a redesign of the Sonarr V4 Custom Format settings GUI to a No Code Low Code (NCLC) Logic Designer GUI, similar to the Azure Logic Apps designer. This approach could simplify the implementation process and potentially require fewer changes to the existing logic.

The introduction of an NCLC designer could help novice users like myself to design more effective CFs. It could also address the issue of CFs being ignored in profiles and ensure that titles are not selected below the profile’s minimum score.

I understand that this redesign would require significant work and may necessitate changes to the existing logic. However, I believe that there might be an existing modular approach that could simplify this implementation process. I look forward to any feedback or suggestions on this proposal.

### Describe alternatives you've considered

I have considered other PVR type apps such as Medusa etc which only has basic logic workflows but it does use a modular parser called "Guessit" which seems to work as far as I could see but I still haven't decided if I want to commit to changing my libraries organiser app yet?  

Many other apps and services seem to have adopted a LCNC type designer for various purposes which was what made me think that Sonarr could use something like this, using a plugin system could open up new ideas for Sonarr especially modules like the Parser and CF's and Logic.

**Comment by markus101** [comment]
> The current design of the Sonarr V4 Custom Format (CF) settings GUI has led to some challenges and frustrations. The scoring system in V4 is difficult to understand and use effectively.

Can you elaborate? The biggest challenge is usually around matching things, but that's why we highly recommended Trash's collection of CFs, especially as a starting point https://trash-guides.info/Sonarr/sonarr-collection-of-custom-formats/ and you can use the test parsing built-into Sonarr to test anything around the title being parsed.

> Additionally, some functionalities present in versions prior to V4 have been lost, and the current CF design cannot compensate for these missing features

Such as?

> There are also issues with profiles ignoring CFs and selecting titles below the profile’s minimum score.

There's always the potential for bugs, but without trace logs showing the issue it's going to be impossible to troubleshoot that further.

We do not have plans to redo them completely and add a work flow designer to the UI to accomplish that, but we are very much interested in improving things where possible so any concrete examples where CFs fall short of preferred words or specific challenges you've faced will help.

**Comment by johnkennyuk** [comment]
@markus101 thanks for the reply, to be honest I wasn't really trying to open an issue regarding the CF issues but to state some possible feature change wishes such as the gui for CF's to help expand and simplify the current logic flow plus possibility for a modular customisable parser.

But to your questions I've found that the CF match scoring isn't uniform accross modules I.e the score is different if looking at the queue to the titles items or titles history, additionally ive been unable to determine why profiles are ignoring there minimum score for grabs even when I'm only using profiles with custom formats, I do know about steps to troubleshoot but I've been unable to determine where the issue lies. 

The main reason for thinking of the CF gui with wysiwyg logic flows comes from being unable to combine CF's in such a way that I can clearly understand or implement current logic as easily defined AND & OR logic?

**Comment by markus101** [comment]
The differences could be due to different data being available, but for the most part we see this when the titles are similar, but not identical. Closing this as we're not going to redesign the UI at this time.
