### ISSUE TITLE
Use release title to import single episode

### ISSUE THREAD

**Issue by AtomBoyC** [Sonarr/Sonarr#6741]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When download and import single episode, like:
The indexer site's single episode release title is fine, such as "One Piece S01E01 ....".
But the torrent file's structure is always in this way : "One.Piece.S01.... /One.Piece.S01.E01....".
It will import the single episode as season package.
This issue only show up in v4, and it's fine when I using sonarr v3.

### Expected Behavior

I guess sonarr using the folder name rather than indexer site's relese title when importing that file. That causes this issue.
Could you please change that way to using indexer site's relese title? 

### Steps To Reproduce

Importing single episode file in season package.

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.4.1491
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.37.2
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/15039417/sonarr.trace.txt)

### Anything else?

Like this issue: https://github.com/Sonarr/Sonarr/issues/6472

Formerly, someone pointed out this issue, but it he didn't get proper handle on it.
Our dear manager said that "need to manually clean it up"... , but I'm afraid that's not a good way to go, because it will cause log file too large so that when clicking "history" button on series page, it will get stuck, especially some very long series like Detective Conan.

This is a serious problem, because many trackers prefer releasing single episode in that way for the convinence to cross-seed and no need to re-download when season finale repacking.

**Comment by AtomBoyC** [comment]
Moreover, it can lead to wrongly repeatly delete and import of the other irrelevant episode in the season package when importing the single episode.
![2024-04-19 191705](https://github.com/Sonarr/Sonarr/assets/111679227/cef8cd0e-f5cf-4599-a32d-45bdd2c9a221)

**Comment by stevietv** [comment]
The release name for this download was `Delicious in Dungeon S01 1080p NF WEB-DL DDP.5.1 H.264-CHDWEB`. That implies a full season. Sonarr is then warning you that the remaining episodes were not found inside the grab.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by AtomBoyC** [comment]
> The release name for this download was `Delicious in Dungeon S01 1080p NF WEB-DL DDP.5.1 H.264-CHDWEB`. That implies a full season. Sonarr is then warning you that the remaining episodes were not found inside the grab.
> 
> Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

That's not my Trace Logs... I just put https://github.com/Sonarr/Sonarr/issues/6472 on here.
But the issue does exist.

**Comment by stevietv** [comment]
there were trace logs in original issue post that you've since removed. Share your trace logs of this issue to determine if its an issue we should reopen or not.

**Comment by AtomBoyC** [comment]
> there were trace logs in original issue post that you've since removed. Share your trace logs of this issue to determine if its an issue we should reopen or not.

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/15040448/sonarr.trace.txt)
![2024-04-19 203954](https://github.com/Sonarr/Sonarr/assets/111679227/f0b1d6a6-795f-40c5-aae5-e77377adb005)

Try to reproduce the issue, please check about that. Thank you!
