### ISSUE TITLE
Allow disabling the log database

### ISSUE THREAD

**Issue by onedr0p** [Sonarr/Sonarr#6743]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I am using Sonarr with Postgres and it's a bit inconvenient to have to have 2 databases per instance of Sonarr. In my setup I have logs via stdout which are also going to a log aggregator (Loki), Sonarr also writes the logs to disk and writes logs to another database. I don't see the need to have 3 places for the logs.

### Describe the solution you'd like

It would be awesome if there was a way in the `config.xml` to disable the log database completely and disable any feature in the app that relies on it (if any).

### Describe alternatives you've considered

There really isn't any alternative.

### Anything else?

Radarr ref: https://github.com/Radarr/Radarr/issues/9110

**Comment by markus101** [comment]
Not something we're going to commit to doing at this time, if someone is interested in picking this up we'll leave the issue tagged.

**Comment by sillock1** [comment]
I'd be happy to pick this up after this [issue](https://github.com/Sonarr/Sonarr/issues/6744) is done.

I did open a Radarr PR for toggling the log database. Is this something you'd be happy for me to bring into here?
https://github.com/Radarr/Radarr/pull/9943
