### ISSUE TITLE
Environment variable configuration for items in `config.xml`

### ISSUE THREAD

**Issue by onedr0p** [Sonarr/Sonarr#6744]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

There's currently no support for configuring Sonarrs `config.xml` with environment variables. This is **extremely** helpful for deploying Sonarr as a container.

This was last brought up in https://github.com/Sonarr/Sonarr/issues/4699 but this was nearly 3 years ago and I think that got really off topic so I wanted to see if there was any interest in supporting this now.

### Describe the solution you'd like

Support for setting environment variables for configuration, specifically options set in config.xml.

Precedence could probably be

1. use environment variables, if an option is not set in env...
2. read it from the `config.xml`

### Describe alternatives you've considered

N/A

### Anything else?

List of environment variables (which is currently everything in config.xml) could be:

```
SONARR_LOG_LEVEL
SONARR_URL_BASE
SONARR_UPDATE_MECHANISM
SONARR_API_KEY
SONARR_BIND_ADDRESS
SONARR_PORT
SONARR_SSL_PORT
SONARR_ENABLE_SSL
SONARR_LAUNCH_BROWSER
SONARR_SSL_CERT_PATH
SONARR_SSL_CERT_PASSWORD
SONARR_POSTGRES_HOST
SONARR_POSTGRES_PORT
SONARR_POSTGRES_USER
SONARR_POSTGRES_PASSWORD
SONARR_POSTGRES_MAIN_DB
SONARR_POSTGRES_LOG_DB
```

Prowlarr ref: https://github.com/Prowlarr/Prowlarr/issues/777

**Comment by markus101** [comment]
Not something we currently have plans for.

**Comment by onedr0p** [comment]
If someone was to contribute this feature, would you be open to it?

**Comment by markus101** [comment]
Sure, there is already some support for Postgres environment variables `PostgresOptions`, but it's using `ConfigurationBuilder` which results in all the underscores being doubled (unless `:` is used instead).
