### ISSUE TITLE
Spoiler Free setting to suppress episode titles from appearing

### ISSUE THREAD

**Issue by Zautix** [Sonarr/Sonarr#6745]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Many daily game shows title their episodes using contestant names, revealing who the winner of the previous day is if that is the format of the show (i.e., Jeopardy.) Knowing the names of episodes can also reveal plot points people may not want to see in advance.

### Describe the solution you'd like

Implement a spoiler free mode to avoid seeing episode names entirely and replace them with a generic <name> <season> <episode> for serial shows, or <name> <air date> for daily shows.

### Describe alternatives you've considered

Table Options allows me to suppress show titles and replace them with file names, but the episode title will still appear on the calendar as well as if I manually search for an single episode, so it is not a complete solution.

**Comment by thezoggy** [comment]
somewhat related, kodi offers up ability to hide various stuff for 'unwatched' items to prevent spoilers
![kodi_2024-04-24_11-42-43](https://github.com/Sonarr/Sonarr/assets/500882/6adda110-1dcc-4167-9327-d59f9f2bc716)

while sonarr has no concept of 'watched', one could leverage similar context by using airdate.. to not show stuff until x days after..  


but this is higher niche, as usually its the episode details that would be the spoiler not the title. and 'titles' a lot of time are TBA until show airs for streaming sites to prevent leaking of info..so sonarr also wouldnt have the info until later anyways.

**Comment by markus101** [comment]
You can hide episode information on the calendar, but it's title as well as the season/episode numbers.

No plans to add a setting to hide episode titles to the calendar or other locations at this time.
