### ISSUE TITLE
Priority was given to downloading S1E1-E4 and S1E5-E6 instead of S1E1-E8

### ISSUE THREAD

**Issue by PN62323424** [Sonarr/Sonarr#6748]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

![1713431754685](https://github.com/Sonarr/Sonarr/assets/83660264/15533eef-151f-462f-b4ed-6cf867b7be96)
![1713431553970](https://github.com/Sonarr/Sonarr/assets/83660264/032a3ec5-7bbe-4711-8744-67f70b15e09d)

### Expected Behavior

Can anyon please tell me why S1E1-E4 and S1E5-E6 are prioritized to be downloaded instead of S1E1-E8?thanks

S1E1-E8 has 6160 points, S1E5-E6 has 5860 points, instead of prioritizing the 5860 points, and this has been updated to episode 8, shouldn't it be S1E1-E8 first?

I haven't had a problem with any of my other episodes, just this one.

### Steps To Reproduce

none

### Environment

```markdown
- OS: synology 
- Sonarr: 4.0.4.1515
- Docker Install: yes 
- Using Reverse Proxy: no
- Browser: chrome
- Database:
```

### What branch are you running?

Main

### Trace Logs?

none

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

The order than Sonarr selects things is explained in the FAQ.

https://wiki.servarr.com/sonarr/faq#how-are-possible-downloads-compared

This looks to fall to the number of episodes, which isn't covered in the FAQ, but in code it's as follows:

- Season packs are always preferred
- For series with the type set to Anime, batch releases are preferred (more episodes is better)
- For series with the type set to Standard less episodes are preferred as generally multi-episode releases are combined into single files making it impossible to automatically upgrade to single episode releases later
