### ISSUE TITLE
Cannot manually remove items from Activity when no downloader for type is setup

### ISSUE THREAD

**Issue by mikestecker** [Sonarr/Sonarr#675]
In my setup, I had originally had both NZB and Torrents set up with trackers and downloaders for each. I have since removed the torrent downloader but had forgotten to remove the torrent tracker. Now I have some downloads in the Activity tab listed as torrents, but when I click the X to remove them and then click the remove button in the modal, it just spins and never finishes removing the torrent download from the activity list.

Manually re-loading this screen still shows the torrent downloads in the list. How can I clear these? I have since removed the torrent tracker so that this won't happen in the future.

**Comment by markus101** [comment]
Please open a thread on our forums for support with debug logs showing the removal from the queue.
