### ISSUE TITLE
Recognize title pattern "S1E1-8 of 8" as full season

### ISSUE THREAD

**Issue by fuckoffel** [Sonarr/Sonarr#6757]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'm using prowlarr's rutracker indexer and almost all the releases there contain this format `S1E1-8 of 8`. This format is recognized by prowlarr - see [here](https://github.com/Prowlarr/Prowlarr/blob/b29bc923fc870b9f2c0582ca20db0d16adb541d5/src/NzbDrone.Core/Indexers/Definitions/RuTracker.cs#L1724). But sonarr returns `"fullSeason": false` for such releases and they are not grabbed automatically because of that.

### Describe the solution you'd like

The solution I'd like is for sonarr to consider releases of format `S$1E$2-$3 of $4`, where `$3` is equal to `$4`, to be full season.

### Describe alternatives you've considered

I considered modifying some configuration either in Prowlarr or Sonarr which would instruct it to replace `S1E1-8 of 8` with `S1`. However I haven't found such configuration. If it exists and you can point me to it I would happily use it.

**Comment by markus101** [comment]
Please provide some example release names.

**Comment by fuckoffel** [comment]
> Please provide some example release names.

Here are the examples I see in the logs:

```
Resident Alien / S3E1-8 of 8 [2024, WEB-DL] + Original RUS
Resident Alien / S3E1-8 of 8 [2024, WEB-DL 1080p] 4 x + Original + RUS
The Gentlemen / S1E1-8 of 8 [2024, WEB-DL 1080p] + Original + RUS
The Gentlemen / S1E1-8 of 8 [2024, HEVC, HDR10, Dolby Vision, WEB-DL 2160p] 4 x + Dub (Red Head Sound) + Original + RUS
Fallout: / "Fallout: Nuka Break" the series / S1E1-6 of 6 (Vincent Talenti) [2011-2012, WEBRip 1080p] MVO + VO + Original RUS
Fallout / S1E1-8 of 8 [2024, WEB-DL 1080p] + Original + RUS
Resident Alien / S2E1-16 of 16 [2022, WEB-DL] RUS
```
