### ISSUE TITLE
Also Explude "Sample" Folder / Files

### ISSUE THREAD

**Issue by Konrni** [Sonarr/Sonarr#6759]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Right now folders or files with "Sample" in them aren't excluded on a DiskScan.

### Describe the solution you'd like

either add and "?" to "samples" in "ExcludedExtrasSubFolderRegex" or add "sample" to "ExcludedExtraFilesRegex"
Both are in "DiskScanService.cs"

option 1:
`        private static readonly Regex ExcludedExtrasSubFolderRegex = new Regex(@"(?:\\|\/|^)(?:extras|extrafanart|behind the scenes|deleted scenes|featurettes|interviews|scenes|samples?|shorts|trailers)(?:\\|\/)", RegexOptions.Compiled | RegexOptions.IgnoreCase);
`
option 2:
`        private static readonly Regex ExcludedExtraFilesRegex = new Regex(@"(-(trailer|other|behindthescenes|deleted|featurette|interview|scene|short|sample)\.[^.]+$)", RegexOptions.Compiled | RegexOptions.IgnoreCase);
`

(additioanlly it would be good to add a test für "sample" into "ScanFixture.cs")

### Describe alternatives you've considered

crying in silence why this one group choos to only provide one sample file and therefore name the folder in singular and not plural.
(Would probably just delete it from disk)

**Comment by markus101** [comment]
Sample video files during import are ignored based on the run time, not the folder name.

Unless they are also adding extra files (subtitles, nfo, etc) in that folder it won't matter.

**Comment by Konrni** [comment]
does this runtime check only work if there is another file to compare too?

I had every sample file listed as possible import. I could just irgnore delete the import suggestion so it wasn't much of a problem but still unexpected.
It might be after the extracted video files were moved and not kept under torrent-Root.

Layout:
Torrent-Root
- .rar, .rar00-99, .nfo, .sfv
- Sample
- - .mkv

**Comment by markus101** [comment]
No, it always works, otherwise it would have been imported.

The problem here is you have archived files that need to be extracted, not that a sample file exists in a folder.

**Comment by Konrni** [comment]
aha ok, i guess it is no problem then.

**Comment by stevietv** [comment]
> aha ok, i guess it is no problem then.

You should use unpackarr for dealing with rar'd packs
