### ISSUE TITLE
Prioritize regular episodes when absolute numbers clash

### ISSUE THREAD

**Issue by NMe84** [Sonarr/Sonarr#676]
This only happens when TVDB is edited by a monkey, but it does happen somewhat often: people will add a new season or a new special and enter an absolute number that is already in use for an existing episode. Sonarr responds to this like this:

![Screenshot](http://devven.nl/drone/absolute-mismatch.jpg)

Note how the two duplicate episode numbers cause the actual episodes to disappear from season 1 while the already downloaded episode is recognized as one of the new specials.

I would like to propose that Sonarr gives precedence to preexisting episodes when this happens, or if that is complicated to at least give precedence to regular season episodes over specials. The use case here is that the current behavior is very likely to cause issues with renaming, especially once [issue 317](https://github.com/Sonarr/Sonarr/issues/317) is built.

**Comment by thezoggy** [comment]
why not just discard absolute numbers for specials?

**Comment by NMe84** [comment]
Because anime has a habit of getting an extra episode that is released later on. If there are 12 episodes in a typical anime, about 2-3 months later they'll often release what they can an OVA, which often gets numbered episode 13 by the scene. Sonarr being able to pick up on that is actually a good thing. :)

**Comment by thezoggy** [comment]
so if there is a special with abs13 and a normal ep with abs13.. how is sonarr to know which it is?

**Comment by NMe84** [comment]
That shouldn't happen, absolute numbers on TVDB should be unique. When they're not, the screenshot above happens. Generally if there were twelve regular episodes and an OVA with absolute number 13, the next season would start with abs 14 on TVDB.

**Comment by thezoggy** [comment]
perhaps just discard duplicate abs numbers? first use wins?

**Comment by thezoggy** [comment]
:monkey:

**Comment by NMe84** [comment]
With the amount of monkeys already editing TVDB especially for anime (combined with how slow the mods tend to be) this change will be more than welcome. :P Thanks, Markus. :)
