### ISSUE TITLE
Filters for Blocklist

### ISSUE THREAD

**Issue by Dalethium** [Sonarr/Sonarr#6763]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

In some situations, you may want to remove certain items from the block list, but it becomes difficult to find them. For example, you add new NZB hosters to your Sabnzbd want to remove the block listed items from that protocol, you simply can't.

### Describe the solution you'd like

Similar filters as there are on searching individual episodes and the filter is available on the download list.

### Describe alternatives you've considered

Manually going through and checking the indexer used on each individual block listed item across over 500 pages.

**Comment by markus101** [comment]
Filters for Series and Protocol would be a good start.
