### ISSUE TITLE
Add a way to distinguish between indexers in the download clients

### ISSUE THREAD

**Issue by Barina** [Sonarr/Sonarr#6777]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'm having a problem to distinguish between my private tracker and the public ones.
There's a list of trackers in the side pane but it is very long and you cannot filter it.. qBittorrent is awesome but here it kinda sucks.

### Describe the solution you'd like

I'm currently dealing with qBittorrent so..:
Either using Tags (the preferred way) or Categories withing QBT.

### Describe alternatives you've considered

Setting a Tag manually when a torrent starts. this is bad.
Filtering the torrent list in QBT by the desired trackers. also bad.
Launching a second instance of QBT that'll handle downloads separately for private trackers and use Sonarr\Radarr Tags to set the appropriate download client. 

### Anything else?

There's a similar issue in Radarr's repo here:
https://github.com/Radarr/Radarr/issues/7588

**Comment by markus101** [comment]
This isn't something we have plans to support, you may be able to do something with a custom script or webhook on grab.

**Comment by bakerboy448** [comment]
- qbit_manage or various qbit tools let you add tags based on trackers
- Qbt webui does allow filtering by tracker url

**Comment by oOStroudyOo** [comment]
I also would love to see this.
I currently use qbit_manage to do this but it genuinely would be incredible to add a qBittorrent tag via Prowlarr, Sonarr and etc.
