### ISSUE TITLE
Unable to add TV show Frontier (2016) after adding TV show Frontier (2023)

### ISSUE THREAD

**Issue by teo4all** [Sonarr/Sonarr#6780]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I've added the series Frontier(2023) and I've tried adding tv show Frontier(2016) and I'm recieving the following error message
```
Invalid request Validation failed: 
 -- TitleSlug: Title slug 'frontier' is in use by series 'Frontier'. Check the FAQ for more information
```

### Expected Behavior

I should be able to add two different series with the same name, but different years

### Steps To Reproduce

Add series Frontier(2023) then try to add series Frontier(2016)

### Environment

```markdown
- OS: Windows
- Sonarr: 4.0.4.1491
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: 
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

2024-05-01 23:44:16.6|Trace|HttpClient|Res: HTTP/2.0 [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/316517: 200.OK (11494 bytes) (80 ms)
2024-05-01 23:44:16.8|Trace|SonarrErrorPipeline|Handling Exception
2024-05-01 23:44:17.0|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- TitleSlug: Title slug 'frontier' is in use by series 'Frontier'. Check the FAQ for more information
2024-05-01 23:44:17.0|Trace|Http|Res: 3575 [POST] /api/v3/series: 400.BadRequest (507 ms)

**Comment by stevietv** [comment]
ss the error says, you can check the FAQ for fixes: https://wiki.servarr.com/en/sonarr/faq#title-slug-in-use

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
