### ISSUE TITLE
Remove Failing Pending Items

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#679]
If a pending download fails a number of times we should remove it from the pending queue instead of trying over and over. Recently I've seen cases where the torrent has ben removed or there is no torrent client to be sent to.

**Comment by Taloth** [comment]
Far more critical now due to us deferring items if the download client is unavailable.

Solution: The handling ReleaseDownloadException should raise an appropriate event allowing Pendingservice to remove the release.
