### ISSUE TITLE
Overview shows a different airing time as series view when using postgresql

### ISSUE THREAD

**Issue by nuxencs** [Sonarr/Sonarr#6790]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The overview page shows a different airing time as show view when using postgresql. The overview page shows the UTC airing time regardless of the timezone set in the docker compose. The series view shows the correct airing time respecting the timezone set in the compose.

Tested on both fresh install with empty postgres DB and migrated install coming from sqlite.

### Expected Behavior

Displayed airing times should be consistently using the correct timezone across all pages.

### Steps To Reproduce

1. Use Postgresql DB
2. Add Show
3. Check show view to see correct airing time
4. Check overview page to see incorrect (UTC) airing time

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.4.1616
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox 125.0.3
- Database: Postgresql 14.11
```

### What branch are you running?

Develop

### Trace Logs?

-

### Anything else?

![image](https://github.com/Sonarr/Sonarr/assets/47067662/38a4712d-1578-4806-ab75-193ea2e0eaa6)
![image-1](https://github.com/Sonarr/Sonarr/assets/47067662/0cc2c6b0-30d4-401f-9d71-05adc18c32f1)

**Comment by saltydk** [comment]
I can confirm that this setting does not affect the issue here as mine is 
```ini
timezone = 'Europe/Copenhagen'
```
and I recreated the issue that @nuxencs had while we talked on discord. That config option is automatically generated when using the TZ env in the container we both used for this test.

**Comment by saltydk** [comment]
To further illustrate this point, override your browser's timezone and you will see that the value in the season listing uses the browser's timezone and not the one set in Sonarr nor Postgres' environments.

**Comment by markus101** [comment]
I image changing the timezone to `Etc/UTC` would solve it then. @mynameisbogdan has done some digging and looks like when converted to a string representing the date the timezone information is lost, which is why you're off by a couple hours.

> To further illustrate this point, override your browser's timezone and you will see that the value in the season listing uses the browser's timezone and not the one set in Sonarr nor Postgres' environments

Yes, but Sonarr handles everything for dates as UTC, which SQLite also does, but Postgres doesn't. I misspoke and it's not when Sonarr/Postgres have different timezones, it's just when Postgres is not using UTC.

**Comment by saltydk** [comment]
>I image changing the timezone to Etc/UTC would solve it then. @mynameisbogdan has done some digging and looks like when converted to a string representing the date the timezone information is lost, which is why you're off by a couple hours.

I also tried that and it made no difference as far as I could tell at least. Bogdan is the one we both were talking to on discord as well. I'm sure he understands the problem better than me.

**Comment by saltydk** [comment]
PG with UTC:
```
2024-05-05 15:00:00+00
```
But the displayed values are the same as before inside of the newly recreated Sonarr instance. 17:00 in season list and 15:00 on the other.
