### ISSUE TITLE
Error on Import French Daily TVShow (Date VS Episode number)

### ISSUE THREAD

**Issue by bebert0x42** [Sonarr/Sonarr#6799]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I search for the French TVShow "Quotidien" via the indexer, the episode is found and downloaded. During the import, Sonarr is unable to match the downloaded file name with the corresponding episode (see the screenshots).

<img width="1389" alt="image" src="https://github.com/Sonarr/Sonarr/assets/45731948/1a7b6993-4f94-4d28-9326-1e1149233e81">
<img width="1387" alt="image" src="https://github.com/Sonarr/Sonarr/assets/45731948/6a1526cf-3956-43e6-880c-36b4bd3f3391">

### Expected Behavior

Matching between Sonarrs'Search and Sonarrs'Import file when it's found on the first case.

### Steps To Reproduce

1. Add show "Quotidien"  : https://www.thetvdb.com/series/315932-show
2. Download manualy one Episode (Indexer YGG torrent Prowlarr)
3. Check if Episode name matching
4. Check if Episode is imported

### Environment

```markdown
- OS: Synology DSM 7
- Sonarr: 4.0.4.1491-ls237 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/15246362/sonarr.trace.txt)

**Comment by markus101** [comment]
Sonarr expects the date to be in the format `yyyy.mm.dd`, which it is when it is grabbed. `dd-mm-yyyy` and `mm-dd-yyyy` are ambiguous and Sonarr has no way of knowing which is being used if the day is less than 13.

**Comment by bebert0x42** [comment]
I understand. Could it be possible to add a tag or save the file name found by Sonarr during the search on indexer so as not to re-analyze it later? This might be a deeper change to the Sonarr system itself, but it could make sense.

**Comment by markus101** [comment]
Sonarr uses all the data it has at the time of import, both to make sure the indexer hasn't made a mistake and to ensure that multi-episode releases are properly accounted for.

In this case we may be able to change the parsing behaviour to not incorrectly parse this, which should fall back to the release name, but that may not be sufficient and in that case Sonarr will not be able to handle these downloads automatically as they are named.

**Comment by markus101** [comment]
For ambiguous dates (where day is less than 13) we'll raise an exception while parsing them, which should allow fallback to folder/download name, it won't completely solve the issue, but it will improve the messaging around it.
