### ISSUE TITLE
Add a minimum step for custom formats score upgrades

### ISSUE THREAD

**Issue by catch-404** [Sonarr/Sonarr#6800]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I use a custom format to add a +1 score to any release that has a freeleech flag, so that if multiple indexers have the same release, Sonarr will always grab it from an indexer that has it freeleech, if any. 

Here is the issue that can arise from this method. 
Let's say Sonarr searches for a show and grabs a release from RlsGroupA, with a score of 1000. Multiple indexers have that release but none of them have it freeleech.
Later on, an indexer releases the same show by RlsGroupB, which by default has the same CF score as RlsGroupA (1000); however, this release is freeleech, so it will get the CF bonus and have a score of 1001. Sonarr will thus see it as an upgrade from the previously grabbed release by RlsGroupA and replace it, even though both RlsGroup are otherwise treated as equivalent and shouldn't be considered upgrades from one another.

### Describe the solution you'd like

I realize that what I describe above is Sonarr working as intended, but I believe Sonarr could benefit from a tweak that could resolve this issue without fundamentally impacting how upgrades work.

I think it could be nice to have the ability to set a minimum step in score upgrades before Sonarr considers one release an upgrade from another. For instance, in the situation described above, I could tell Sonarr to only consider upgrading a release if another one gets a CF score of at least 5 more points; i.e., the release from RlsGroupA with a CF score of 1000 wouldn't be upgraded by the release from RlsGroupB with its CF score of 1001, but it would get an upgrade from a release by RlsGroupC that has a score of 1005 or above. 

### Describe alternatives you've considered

I can't think of any alternative that doesn't involve giving up on the freeleech CF method.

**Comment by neo42JBR** [comment]
I'd love to see this implemented. Have a lot of unnecessary upgrades because the score changed slightly.

**Comment by Bretterteig** [comment]
I'd love to see this implemented. Have a lot of unnecessary upgrades because of slight score increases.
