### ISSUE TITLE
Multiple season doenload only replaced first episode of each season

### ISSUE THREAD

**Issue by GajodeBruin** [Sonarr/Sonarr#6804]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I grabbed "Longmire (2012) Season 1-6 S01-S06 (1080p BluRay x265 HEVC 10bit AAC 5.1 Silence)" All episodes of season 6 were repleced by the new 1080p version of the episodes. 
However, for each of seasons 1-5 only the first episode was replaced with  the newer file,

### Expected Behavior

All episodes are replaced for all dowloaded seasons

### Steps To Reproduce

1 with a multiseason series that has a low quality version of each episode
2: grab a collection that contains a better version of the episodes for multiple seasons
3: only some of the episodes are replaced

### Environment

```markdown
Version
4.0.4.1491
Package Version
4.0.4.1491-ls237 by linuxserver.io
.NET
Yes (6.0.13)
Docker
Yes
Database
Sqlite 3.44.2
Database Migration
205
AppData Directory
/config
Startup Directory
/app/sonarr/bin
Mode
Console
Uptime
```

### What branch are you running?

Main

### Trace Logs?

.

### Anything else?

.

**Comment by markus101** [comment]
Sonarr does not support multi-season releases. You'll need to use Manual Import to process all files.
