### ISSUE TITLE
Remove all older seasons/Remove older than current episodes

### ISSUE THREAD

**Issue by genefyx** [Sonarr/Sonarr#6805]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

After a DB corruption, and recovery. I had all shows start seeking from Season 1.
Now all old shows are downloading old seasons and I have to edit them 1 by one when I have time.

### Describe the solution you'd like

If there was an option, to mass: 
* [unmonitor up to current season]
* [unmonitor up to current episode]

### Describe alternatives you've considered

Alternative would be to Manage Shows Individually using the Activity Section. [Activity > Queue or Activity > Show Mgmt]
I had to set shows automatically paused due to the season issues. So maybe an option
to manage the show and un-select seasons all at once as they show up in the Queue/History.
This way there's only one page to handle the fires as they come.

**Comment by thezoggy** [comment]
github is not the place for support questions. use proper places for that.
you can bulk edit the series from the main page and set monitoring levels for what you want (only latest season or whatever).

**Comment by markus101** [comment]
This functionality already exists.

1. Select Series
2. Select the series you want to change (or select all)
3. Update Monitoring
4. Select `Last Season`
5. Press Save
