### ISSUE TITLE
Add "Remove Series and Keep Files" and "Remove Series and Delete Files" to "Clean Library Level" option in "Import Lists" tab

### ISSUE THREAD

**Issue by soredake** [Sonarr/Sonarr#6812]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Right now, sonarr don't have this option in "Clean Library Level" parameter.

### Describe the solution you'd like

Similar to Radarr:
![image](https://github.com/Sonarr/Sonarr/assets/5204968/0ee792d0-7cc9-4a46-b375-1354555caa0a)

### Describe alternatives you've considered

Not having such options.

**Comment by markus101** [comment]
Unfortunately this leads to a lot of problems for people when they enable it and nuke their library. 

At this time we do not have plans to add this to Sonarr.
