### ISSUE TITLE
Keep seeding until x amount of seeders are back

### ISSUE THREAD

**Issue by Prankish8407** [Sonarr/Sonarr#6814]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

N/A --> enhancement request for download handling.

### Describe the solution you'd like

I personally download most my content via private trackers, and always use the function to seed the torrent until x amount of ratio.
I would love to see an option added in the list of the download client to specify x amount of seeders to remain.

The idea is to keep torrents alive on smaller private trackers until at least x amount of seeders are active and ratio is reached.
So if i set the ratio in the download client to 3 it should at least reach that AND it should stay alive until (for example) 5 seeders are back.

Hope this is something you can implement.

### Describe alternatives you've considered

N/A --> could not find a suitable solution

### Anything else?

Either way (yes or no) im happy with all the *rr applications, cheers devs!

**Comment by thezoggy** [comment]
doesnt qbit manage already take care of this?

**Comment by Prankish8407** [comment]
i use Transmission, its lightweight.

**Comment by markus101** [comment]
Torrent management to this degree is bit something we have plans for.

If this is something qbit manage does there may be solutions for transmission or other clients already or it may be worth switching clients as qbit is quite efficient without being as barebones as transmission.
