### ISSUE TITLE
Episodes Not Appearing in Queue During Download Process

### ISSUE THREAD

**Issue by MaximeMohandi** [Sonarr/Sonarr#6815]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When Sonarr grabs an episode, it is correctly processed through the download client, and I can see it in the following places:

- History (once finished)
- Download client
- Episode list

However, the episode does not appear in the queue. This is problematic when manual interaction is needed, as I cannot see or act on the download in the queue.

### Expected Behavior

The episode should appear in the queue during processing, allowing for manual interactions if needed.

### Steps To Reproduce

    1. Sonarr grabs an episode.
    2. The episode is processed through the download client.
    3. Check the queue in Sonarr.

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.4.1491-ls238
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: Firefox
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

https://gist.github.com/MaximeMohandi/8c9296754b27e16292ac38475c3b504b

**Comment by augustuen** [comment]
This is a support issue. Please join us in the Sonarr forum or the Sonarr discord server. And bring full **trace** logs.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
