### ISSUE TITLE
Deleting an episode does not delete the folder

### ISSUE THREAD

**Issue by shifoc** [Sonarr/Sonarr#6816]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

my current format is `{episode:00}\{Series Title} - S{season:00}E{episode:00} - {Episode Title}` for standard episodes and `{episode:00} ({absolute:000})\{Series Title} - S{season:00}E{episode:00} ({absolute:000}) - {Episode Title} -{Quality Full}` for anime and when I delete an episode from Sonarr it does not delete the folder

### Expected Behavior

delete the folder as well

### Environment

```markdown
- OS: windows 10
- Sonarr: 4.0.4.1668
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.36.0
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/15285619/sonarr.trace.txt)

**Comment by markus101** [comment]
Folders are only deleted if the folder is empty and `Delete Empty Folders` is enabled.

![image](https://github.com/Sonarr/Sonarr/assets/413544/b6757c54-4e3c-48b7-af23-b1c17e883aeb)

**Comment by augustuen** [comment]
> Folders are only deleted if the folder is empty and `Delete Empty Folders` is enabled.

Does that also apply for *episode* folders? I've only seen it used with series/season folders so far.

**Comment by markus101** [comment]
Yeah, it'll recursively delete empty folders.
