### ISSUE TITLE
Option to Exclude Files that are being Downloaded from the Wanted Section

### ISSUE THREAD

**Issue by Orski174** [Sonarr/Sonarr#6823]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It's not.

### Describe the solution you'd like

In the wanted section you can only filter by monitor status, an option to exclude files that are already being downloaded would greatly help so one wouldn't accidentally search again for stuff that are already being downloaded.

### Describe alternatives you've considered

Not available.

**Comment by markus101** [comment]
This would fall under: https://github.com/Sonarr/Sonarr/issues/3657 though potentially not feasible due to how that would actually be filtered.

**Comment by Orski174** [comment]
> This would fall under: #3657 though potentially not feasible due to how that would actually be filtered.

I'm not really sure it does because custom filters also don't include an option for stuff that are being downloaded. 

And if you can elaborate more on its feasibility, according to @mynameisbogdan 's snippet it should be fairly simple.
