### ISSUE TITLE
Unable to automatically download when there are available sources that meet the requirements.

### ISSUE THREAD

**Issue by 53nemu** [Sonarr/Sonarr#6826]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Because I am not a native English speaker, my expression may be a bit strange, and I apologize for that. I have created a series of custom formats according to my needs and confirmed that they can run normally. However, when I actually use Sonarr to search and try to download, Sonarr does not download automatically.
As shown in my images below, there are multiple sources that meet the requirements, but Sonarr does not initiate the download. (I have confirmed that when I manually click download/override, qBittorrent downloads correctly.)

![QQ截图20240519005428](https://github.com/Sonarr/Sonarr/assets/153263868/1f29fe3f-545b-4bcc-a468-cfef68d9c8e4)

### Expected Behavior

To download the sources that meet my requirements in order of their scores.

### Environment

```markdown
- OS: win10
- Sonarr: 4.0.4.1491
- Docker Install: nope
- Using Reverse Proxy: Sorry, I don't understand what this option means.
- Browser: 
- Database: Sqlite 3.36.0
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/15367890/sonarr.debug.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/15367896/sonarr.trace.txt)

**Comment by 53nemu** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing open and closed issues
> 
> ### Current Behavior
> Because I am not a native English speaker, my expression may be a bit strange, and I apologize for that. I have created a series of custom formats according to my needs and confirmed that they can run normally. However, when I actually use Sonarr to search and try to download, Sonarr does not download automatically. As shown in my images below, there are multiple sources that meet the requirements, but Sonarr does not initiate the download. (I have confirmed that when I manually click download/override, qBittorrent downloads correctly.)
> 
![B2AF2C8E030A7660ADC629D98FD093B6](https://github.com/Sonarr/Sonarr/assets/153263868/909866ab-4c95-4e8d-bf46-5ce4f77473e0)

> 
> ### Expected Behavior
> To download the sources that meet my requirements in order of their scores.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Environment
> ```
> - OS: win10
> - Sonarr: 4.0.4.1491
> - Docker Install: nope
> - Using Reverse Proxy: Sorry, I don't understand what this option means.
> - Browser: 
> - Database: Sqlite 3.36.0
> ```
> 
> ### What branch are you running?
> Main
> 
> ### Trace Logs?
> [sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/15367890/sonarr.debug.txt) [sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/15367896/sonarr.trace.txt)
> 
> ### Anything else?
> _No response_

**Comment by 53nemu** [comment]
I'm very sorry, because the first image submission was incorrect, I wanted to edit it, but for some reason, it got sent again...

**Comment by augustuen** [comment]
This is most likely a support issue, not a github issue. Please join us in the Sonarr discord so that we can help you properly

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
