### ISSUE TITLE
Manage the target directory by tag for the Download client

### ISSUE THREAD

**Issue by Zheaoli** [Sonarr/Sonarr#6827]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

For now, I use Sonarr to manage a lot of series including

1. TV Series
2. Animation Series
3. Documentary Series
4. etc

I would like to download the series into a different directory

1. TV Series -> /volume1/Media/tv
2. Animation Series -> /volume2/Media2/Animation
3. etc...

### Describe the solution you'd like

I think maybe we can setup some tags in download client settings, and reference the tags in series setting. So we can set different target directory for different seriesdirectories

### Describe alternatives you've considered

N/A

**Comment by stevietv** [comment]
Where they download to doesn't matter, that is only an interim location until they are imported into Sonarr Media Library.
You can set up different root folders in Sonarr and assign the right root folder for each show type.

**Comment by markus101** [comment]
This can be achieved using multiple download clients in Sonarr and using tags to direct downloads to each client for the tagged series.

You can use automatic tagging to automatically tag series based on different rules.


If you have more questions on how to achieve this please reach out in one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/) or [discord](https://discord.sonarr.tv/).
