### ISSUE TITLE
Add configurable timeout for health issue check on download clients 

### ISSUE THREAD

**Issue by thewan056** [Sonarr/Sonarr#6828]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I scheduled my download client, qbittorent container, to restart twice a day. This is to solve some random disconnects that happen every now and then without requiring me to go in and restart the container manually.
Back to Sonarr, the Notification Trigger for Health Issue regarding download client disconnects triggers every time my scheduled restart happens, which is getting annoying.

### Describe the solution you'd like

I would like to keep the Health Issue trigger while filtering out my automatic restarts. Since the duration for a restart to happen is predictable, a configurable timeout for when your download client disconnects would be nice to have. That way I can still receive notifications when my download client disconnects for longer than a specific time, among other health issues. 

### Describe alternatives you've considered

Currently I just disable the health issue notification which is not ideal since I wont receive any other health issue.

**Comment by Thirrian** [comment]
Schedule an api call to sonarr to disable/enable the health check?

**Comment by markus101** [comment]
No immediate plans for this as it would require quite a lot of changes to handle correctly, but potentially something that can be done as part of #6836
