### ISSUE TITLE
qbittorrent force reannounce

### ISSUE THREAD

**Issue by z4j3biz** [Sonarr/Sonarr#6829]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When grabbing new releases with setup of autobrr > sonarr/radarr > qbittorrent I often am "too early" to grab it and as a result only manage to grab it after tracker announce period (normally 30 minutes).

### Describe the solution you'd like

It would be great if there was possibility to configure qbittorrent in sonarr/radarr download clients section in a way that after configurable x amount of seconds sonarr/radarr would check if: **a)** downloading of a release is active and/or **b)** connection to seed(s)/peer(s) is established. If neither **a** or **b** is true then force reannounce would take place to achieve this. Same would repeat after x amount of seconds until download has started and/or connection to seed(s)/peer(s) is established.

### Describe alternatives you've considered

Delay in autobrr, though it is tricky to figure out "correct" delay period to configure per tracker.

### Anything else?

https://github.com/qbittorrent/qBittorrent/issues/11419#issuecomment-554553451

**Comment by markus101** [comment]
This seems like something that would better fit into qbit manage or another tool, we do not have plans to manage torrents to this this degree.
