### ISSUE TITLE
Prevent grabbing multi-season packs

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#683]

**Comment by tymanthius** [comment]
If you implement this, make it a toggle of some sort.  

Maybe set it so sonarr asks when you add a series & search for back eps if multi SP are ok, as well as a global default setting.

**Comment by Taloth** [comment]
No, because Sonarr can't parse/import Multi season packs at all.

**Comment by markus101** [comment]
Do we have specific examples that we want to prevent? I assume `Series Title S01-06` would be a culprit as `Series Title - Complete Series` would fail in parsing.

**Comment by naq90** [comment]
I apologize if my thinking is incorrect, (I'm new to the whole concept of usenet), but would it be possible to prevent Sonarr from sending one large nzb file to the downloader? With the season packs it's usually one 40-50GB nzb as opposed to much 10 x 4-5GB ones. Again, sorry if my thinking is wrong, this is just what I've observed.

**Comment by l3uddz** [comment]
The Wire S01-05 WS BDRip X264-REWARD-No Rars

Detects as a singular episode 1x05 (this is torrent)

**Comment by thezoggy** [comment]
of course its torrents..
