### ISSUE TITLE
Enable RSS feed for only Anime or vice versa

### ISSUE THREAD

**Issue by Swedish-Wiking** [Sonarr/Sonarr#6835]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sonarr sometimes grabs a "better" Anime release as an upgrade from my non Anime RSS feed, when a specific Anime RSS feed is enabled and the personally preferred one. 

### Describe the solution you'd like

As with Torznab indexers you are able to set specific Anime categories so what would prevent the implementation of a checkbox or two to enable the RSS feed for Anime and/or Standard content as the shows are already marked with Anime/Standard content categories?

### Describe alternatives you've considered

I have considered the use of tags but then I will have to set an Anime tag for all the media that is already "tags" as Anime.

**Comment by markus101** [comment]
Anime Categories won't prevent Sonarr from grabbing a release for an anime series from a standard category on an indexer, it just limits which categories are used for the RSS feed and when searching.

Tags is the way to do it, you can use Auto Tagging to set the tag based on the series type (and other values).
