### ISSUE TITLE
Remove `seriesTitle` from EpisodeResource

### ISSUE THREAD

**Issue by tillkruss** [Sonarr/Sonarr#6841]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When using the `/calendar` API endpoint does not populate the `Episode.SeriesTitle` field, this forces an additional requests of the `/series` endpoint.

### Describe the solution you'd like

Populate the `seriesTitle` fields in the JSON.

### Describe alternatives you've considered

Performing 2 API requests, instead of one.

**Comment by markus101** [comment]
That property is from the old API and shouldn't exist, you can use `includeSeries` to include the series object to get that information. https://sonarr.tv/docs/api/#/Calendar/get_api_v3_calendar
