### ISSUE TITLE
[Typo] "Updates" mentioned in subtitle for general settings

### ISSUE THREAD

**Issue by TDuffinNTU** [Sonarr/Sonarr#6843]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

As per the screenshot, Sonarr's settings menu mentions "updates" in the subtitle for "General Settings", but this is actually managed under the *System* menu. Nice easy fix if not intentional!

### What branch are you running?

Main

### Anything else?

![image](https://github.com/Sonarr/Sonarr/assets/43959652/6e50a571-ddab-4798-b94d-9e2ac8db4fc2)

**Comment by markus101** [comment]
It's referring to the update settings, which are under general, they're just advanced settings.

![image](https://github.com/Sonarr/Sonarr/assets/413544/00bde960-20ef-4741-8099-cb52e017107a)
