### ISSUE TITLE
A way to make sure that an episode is the right one

### ISSUE THREAD

**Issue by phirestalker** [Sonarr/Sonarr#6847]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

As we all know, some series have been numbered differently by some release groups causing duplicate or missing episodes.

### Describe the solution you'd like

I was thinking of OCR for the first half of the episode and search it for the episode name. This wouldn't require a database, but I'm not sure if all series have the episode name displayed in the episode. Every frame shouldn't need to be checked either.
The other possibility would be to have a database with the subtitles or CC that could be matched to the correct episode. This would be a major pain unless someone had started one already.

### Describe alternatives you've considered

The only other possibility I can think of (and the way I have been doing things), is to wait until I watch it and realize it is out of sync and manually correct the problem.

**Comment by bakerboy448** [comment]
- I was thinking of OCR for the first half of the episode and search it for the episode name
non starter

- series have the episode name displayed in the episode
they don't

- The other possibility would be to have a database with the subtitles or CC that could be matched to the correct episode. This would be a major pain unless someone had started one already.
sonarr has nothing to do with subs. not all episodes have embedded subs, many do not.

This is already solvable and covered on the FAQ.
https://wiki.servarr.com/sonarr/faq#how-sonarr-handles-scene-numbering-issues

XEM for adjustments generally and Exemptions if they follow TVDb

**Comment by phirestalker** [comment]
I guess that's why this doesn't happen very often then. It seems it may have been one poster. I guess I was just hoping for something that could trigger a redownload when someone Fs up.

**Comment by markus101** [comment]
This may be possible with a script or additional tooling in the future, but it's not something we're planning to do.
