### ISSUE TITLE
Notify during Manual Import if the new file is the same as the current

### ISSUE THREAD

**Issue by Noxillio** [Sonarr/Sonarr#6848]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It doesn't make sense to import the same file twice and there are scenarios where users may end up with the same files being downloaded twice, or completed downloads not being deleted after import. Clearly indicating whether these files are the same would save time and potentially storage space as well.

### Describe the solution you'd like

When performing a Manual Import it would be useful to run a comparison on each file (after selecting the episode) against the current media file for the episode. It could then display whether the proposed import is the same as the already-existing file, possibly as a rejection. The comparison could be run using file hashes, but a much quicker and more reliable option would be the `cmp` command on Unix-based operating systems or the `comp` command on Windows.

### Describe alternatives you've considered

The only alternative is to do this manually using terminal commands, which is very time consuming when dealing with multiple episodes.

**Comment by Noxillio** [comment]
> There's already a rejection if the new file is not an upgrade, either by quality or custom format scoring, to prevent import loops.

If it's exactly the same, nothing happens. This is at least the case with Manual Imports. Please try it for yourself and see what I'm talking about. This is why I've made the feature request. If this is not intentional then it should be a bug report instead but either way this issue is valid.

**Comment by Noxillio** [comment]
> Like I said, if it's the same name and you have a proper naming format, it should be rejected.
> 
> Maybe add some details like names, custom formats scores, etc.

Name is not data. This feature request proposes that the files be compared, not the names. In any case, the same name also results in the same effect. Like I said, please try it yourself and see what I'm talking about. Please also keep in mind that this refers to Manual Imports, not automatic.

**Comment by bakerboy448** [comment]
Yes. Manual imports are already marked as rejected if they are not upgraded. Presumably you're failing to maintain critical data for your files in your naming thus the new files are always upgrades

**Comment by markus101** [comment]
We used to do this, it was based on exact same file size, but people would queue up duplicate downloads and those duplicates would get stuck in queue so we decided that it was better to just import them given the cost for this is minimal with atomic moves or hardlinks.

https://github.com/Sonarr/Sonarr/commit/be3b3df9036ca7d4f970fffc53af5e4d553ab0e5

No plans to reintroduce this functionality even if it's restricted to manual imports only.

**Comment by Noxillio** [comment]
> Yes. Manual imports are already marked as rejected if they are not upgraded. Presumably you're failing to maintain critical data for your files in your naming thus the new files are always upgrades
> 
> Your new files have a better quality and/or custom format score then your existing files. debug logs should clearly show this comparison

They're exactly the same file, including the name. Not sure what else to say.
