### ISSUE TITLE
[Feature] Only upgrade when bigger

### ISSUE THREAD

**Issue by FrozenSource** [Sonarr/Sonarr#6854]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hi guys been using sonarr for many years and very much enjoy it! but I have on feature request that kind of bothers me.
I am the hoarder that likes his 4K quality and such mainly 264 or 265. But these days you also have the encoding styles from google and the likes.

The result is that sometimes I go from a 64 GB bluray to some weird supposed 2 GB bluray file.

### Describe the solution you'd like

While I could exclude the supposed encoding names should they contain them. I would like an option that saids "upgrade but only if the size is bigger."

### Describe alternatives you've considered

see above

### Anything else?

Love your work!

**Comment by bakerboy448** [comment]
Use custom formats to avoid grabbing micro sized encodes / groups

**Comment by markus101** [comment]
Also set your size restrictions appropriately (currently on Settings: Quality) to prevent extremely small files from being grabbed. No plans to add a setting to enforce larger files only at this time.
