### ISSUE TITLE
SQL Logic error on fresh install

### ISSUE THREAD

**Issue by ghost** [Sonarr/Sonarr#6862]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr refuses to start at all due to from what looks like is SQL logic error. This is completely fresh install. This is what logs say (I won't post the whole log unless needed):

`[v4.0.5.1710] System.Exception: SQL logic error
no such column: −1
While Processing:
"UPDATE "NamingConfig" SET "RenameEpisodes" = 1 WHERE "RenameEpisodes" = −1"
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such column: −1
`

'[v4.0.5.1710] NzbDrone.Common.Exceptions.SonarrStartupException: Sonarr failed to start: Error creating main database
 ---> System.Exception: SQL logic error
no such column: −1
While Processing:
"UPDATE "NamingConfig" SET "RenameEpisodes" = 1 WHERE "RenameEpisodes" = −1"
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such column: −1
'

`[v4.0.5.1710] NzbDrone.Common.Exceptions.SonarrStartupException: Sonarr failed to start: Error creating main database
 ---> System.Exception: SQL logic error
no such column: −1
While Processing:
"UPDATE "NamingConfig" SET "RenameEpisodes" = 1 WHERE "RenameEpisodes" = −1"
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such column: −1
`

### Expected Behavior

It's supposed to start an be accessible from http://localhost:8989

### Steps To Reproduce

1. Install Sonarr using "curl -o- https://raw.githubusercontent.com/Sonarr/Sonarr/develop/distribution/debian/install.sh | sudo bash"

### Environment

```markdown
- OS: Linux Mint 21.3
- Sonarr: Version 4.0.5.1710
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Not applicable
- Database: SQLite 3.37.2
```

### What branch are you running?

Main

### Trace Logs?

Not applicable because it doesn't even get to the point where it could make these.

**Comment by stevietv** [comment]
Can you try updating your SQLite install to a more up to date version?

**Comment by stevietv** [comment]
> > Can you try updating your SQLite install to a more up to date version?
> 
> Did and it did not help, although not sure why that would even help when the error has to do with missing columns in the database file

What version did you update to? It has to do with how some versions of SQLite handle booleans.

Can you try deleting sonarr.db and restart again, then share the the full trace log of that?

**Comment by stevietv** [comment]
I think I remember this issue now, to do with locales in the system I think.
Can you try to `dpkg-reconfigure locales`
Another user solved it by selecting `en_US.UTF-8`, and setting `LC_ALL` flag

**Comment by stevietv** [comment]
> Well.. I tried it on also Xubuntu 24.04 just in case and that same issue is there too. Xubuntu uses 3.45.1 of SQLite so looks like the version of the SQLite does not matter for this at all.

I'm sure its the locale - didn't you see my other comment?
what locale is your system using?

**Comment by jessenic** [comment]
I ran into the same issue, I worked around it by adding `Environment="LC_ALL=en_US.UTF-8"` to the sonarr service. I think this bug should be fixed in the code though, for example by settings the locale in the code itself.

`$ sudo nano /etc/systemd/system/sonarr.service
`
```
[Unit]
Description=Sonarr Daemon
After=syslog.target network.target
[Service]
Environment="LC_ALL=en_US.UTF-8"
User=sonarr
Group=media
UMask=0002
Type=simple
ExecStart=/opt/Sonarr/Sonarr -nobrowser -data=/var/lib/sonarr/
TimeoutStopSec=20
KillMode=process
Restart=on-failure
[Install]
WantedBy=multi-user.target
```
