### ISSUE TITLE
Info button to show additional info about a queue item

### ISSUE THREAD

**Issue by Dalethium** [Sonarr/Sonarr#6864]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

![brave_4Z6MIPExz3](https://github.com/Sonarr/Sonarr/assets/22735418/6e4802f5-6c34-4d1b-8f93-2eb376087ce8)
It would be awesome to have something similar to this inside of the import queue as it would allow For more precise handling of whether a torrent should be moved to the post-import category or just completely removed from the download client.

### Describe the solution you'd like

A simple info box like the image above with all the information from the actual grab.

### Describe alternatives you've considered

Manually searching the download name inside the actual download client and checking the trackers to see what's going on.

### Anything else?

The reason for this comes down to whether or not a torrent should be left to seed or not, due to it being from a private tracker.

**Comment by markus101** [comment]
The indexer and other information is already available in the queue, you can show these additional columns under options or cog icon at the top of the actions column.
