### ISSUE TITLE
Custom filter for Rejections in Manual Import

### ISSUE THREAD

**Issue by danillopanta** [Sonarr/Sonarr#6865]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

I want a custom filter that allows me to select files that are not upgrades so that I can mass delete them. This filter should identify and exclude files that represent upgrades (such as higher quality versions of existing files) and focus on selecting only those files which do not offer any improvement or additional value compared to what is already present. This will help in efficiently cleaning up unnecessary files while retaining the best available versions.

### Describe alternatives you've considered

Manual Review and Deletion:

Description: Manually inspecting each file to determine if it is an upgrade or not and then deleting the non-upgrade files.
Pros: Ensures precise and deliberate deletion, minimizing the risk of accidental data loss.
Cons: Extremely time-consuming and impractical for large volumes of files.

**Comment by danillopanta** [comment]
<img width="1759" alt="image" src="https://github.com/Sonarr/Sonarr/assets/37481984/afdb531e-eea3-4d6e-9c11-7aa07592bb6e">

**Comment by markus101** [comment]
Related to #4132 as it will also need rejection reasons for files surfaced in a way that can be used by Custom Filters.

**Comment by markus101** [comment]
Closing in favour of https://github.com/Sonarr/Sonarr/issues/6960
