### ISSUE TITLE
Failed import does not properly fail

### ISSUE THREAD

**Issue by cliny** [Sonarr/Sonarr#6873]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When an import fails with this message,
'Found matching series via grab history, but release was matched to series by ID. Automatic import is not possible. See the FAQ for details',
the 'trackedDownloadState' remains as 'downloading'.

### Expected Behavior

The 'trackedDownloadState' should change from 'downloading' to 'importPending' or 'importFailed'.

### Steps To Reproduce

Any time this failed import warning message appears. It also occurs in Radarr.

### Environment

```markdown
- OS: Arch linux
- Sonarr: 4.0.5.1710-ls241 by linuxserver.io
- Using Reverse Proxy: Yes
- Browser: Firefox
- Database: Sqlite 3.45.3
```

### What branch are you running?

Main

### Trace Logs?

For logs see here:
https://github.com/ManiMatter/decluttarr/issues/120

Let me know if you need me to set sonarr logs to trace, and I can try to catch an instance of it occurring, it hasn't happened for a few days.

**Comment by markus101** [comment]
It's not `importPending` because it's rejected before it even gets to the point where it's passed off for importing, it's not `importFailed` because that isn't a valid state. Currently it is intentionally left as `downloading` so it will be reprocessed whenever additional alternate names are added.

**Comment by bakerboy448** [comment]
Suggestions for an additional status if that is something on the table:
- AwaitingInteraction
- Downloaded
- DownloadedPending
- ImportBlocked
