### ISSUE TITLE
Optional Filtering For Release Date In Searches

### ISSUE THREAD

**Issue by shiribailem** [Sonarr/Sonarr#6876]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Debated on whether it's a problem at all

### Describe the solution you'd like

Just an option in Custom Format to check for age vs expected release date.

ie. being able to have some profiles may accept things released early, some may refuse to accept things until late (maybe you're just waiting for better releases to sort themselves out later)

### Describe alternatives you've considered

Filtering by regex or being select with indexes isn't really suitable, some indexers are great at certain content but horrible at others, and of course bad entries get reposted across indexers (but over time get quickly overshadowed by good entries)

### Anything else?

I searched and found closed issues, but all of the closings fail to address the actual concerns. We're all aware of inconsistent timings of release between different countries (though usually the release date pulled into the system will be the earlier of those times, and nobody has asked for "local release date" as a metric) or that bad copies might be reposted again (these usually get overshadowed by the good copies once good copies are available... this is to choose to wait for good copies to definitely be available first so bad copies aren't downloaded as the only ones available)

And additionally I'm specifically suggesting this under Custom Formats as it can be applied per show. Most shows things work fine, but sometimes issues crop up with specific shows, and this gives the freedom to go and flip a setting on those shows to address that issue (ie. some shows I grab have bad copies posted a week early consistently, or untranslated copies marked improperly... but I also know the listings are consistently good when searched on or after the release date. So I know firmly that I want to apply this to those shows, and I'll accept missing a leaked early release over addressing the constant annoyance)

I also understand if no current developer want's to work on it, but closing it over that isn't fair or reasonable (it hides it from contributors who may be willing to, as well as creates repeat posts over and over again because it's clearly a concern users have and an open listing puts the conversation in one place)

**Comment by bakerboy448** [comment]
It is unclear what the actual request is here.

Regardless it sounds like using custom formats to avoid low quality groups and possibly a delay profile with a custom format score bypass would solve this

**Comment by shiribailem** [comment]
The basic suggestion was a custom format option (which I referred to as filters because that's what they're doing) for age.

ie. a shows scheduled time is on 9/10, a torrent/whatever dated 9/8 would have an age of -2 and one dated 9/13 would be 3.

Having it as a custom format would use existing systems to drastically minimize code support needed.

It would also be preferable to a whack-a-mole with bad groups or other similar messy situations.

**Comment by bakerboy448** [comment]
Filters != custom formats

custom formats do not filter anything. They add information and then your scoring assists the filtering.

so TLDR of the request: a custom format for a releases age 

this seems like an easy footgun for users with limited use that likely can be handled via existing methods (I.e. avoiding bad groups)

**Comment by markus101** [comment]
We do not have plans to have a custom format for release date.
