### ISSUE TITLE
Fansub

### ISSUE THREAD

**Issue by KlausStortebeker** [Sonarr/Sonarr#6878]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Fansub should be removed from add indexer.

### Describe the solution you'd like

Fansub is shut down so there is no longer necessary for that addition.

### Describe alternatives you've considered

Clearly nothing as is not a feature request or a bug.

### Anything else?

Take your time.

**Comment by markus101** [comment]
Fanzub supports other indexers that implement the same API, similar to newzbin, AnimeNZB was one such site. Given others may be using it for other sites it's not something we plan to remove at this time.
