### ISSUE TITLE
Does not launch on El Capitan 10.11 Public Beta

### ISSUE THREAD

**Issue by psthompson** [Sonarr/Sonarr#688]
Not sure what information I can provide to help with this. Double clicking the app icon causes it to look like it's launching but it never does.

**Comment by psthompson** [comment]
Saw this is being discussed on the forums so never mind.

**Comment by arjunmayilvaganan** [comment]
@psthompson Has this been fixed yet?
btw, where's the discussion on Sonarr being held?
