### ISSUE TITLE
Setting urlBase through api breaks web app

### ISSUE THREAD

**Issue by SrGesus** [Sonarr/Sonarr#6881]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When i try changing the URL Base on the app it works fine, but when i try to do it through the api the whole web app becomes broken, the page is blank and some "ChunkLoadErrors" on the js console.

I tried on both linux with docker, and on windows 11 and the same issues arise.

### Expected Behavior

It should simply work the same way as changing the setting manually in the WebUI, and be able to access the UI under http://localhost:8989/[baseURL]

### Steps To Reproduce

1. Simply install and run sonarr on Windows, or use docker on linux like so:
```bash
sudo docker run -d \   
  --name=sonarr \                                                                       
  -e PUID=1000 \           
  -e PGID=1000 \                                    
  -e TZ=Etc/UTC \                      
  -p 8989:8989 \
  -v ./data:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/sonarr:latest
```
2. Get the API Key from the config.xml file or from the WebUI
3. Get whatever the current config is with `curl http://localhost:8989/api/v3/config/host?apikey=YOUR_API_KEY` 
4. Copy the json result of the previous request and change the urlBase from "" to "/sonarr", and try 
```bash
curl -X 'PUT' \
  'http://localhost:8989/api/v3/config/host/1?apikey=YOUR_API_KEY' \
  -H 'accept: text/plain' \
  -H 'Content-Type: application/json' \
  -d '
  YOUR_JSON
'
```
or use https://sonarr.tv/docs/api/#/HostConfig/get_api_v3_config_host to do the queries
6. Observe a blank page in http://localhost:8989/sonarr and this in your logs:
```
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/Content/965-a175a15e417d6c2abf63.css not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/767-b358f3ba5f72b363e80a.js not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/965-8247822d1e180a9bc6d4.js not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/Content/965-a175a15e417d6c2abf63.css not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/767-b358f3ba5f72b363e80a.js not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/965-8247822d1e180a9bc6d4.js not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/767-b358f3ba5f72b363e80a.js not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/965-8247822d1e180a9bc6d4.js not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/Content/965-a175a15e417d6c2abf63.css not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/767-b358f3ba5f72b363e80a.js not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/Content/965-a175a15e417d6c2abf63.css not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/965-8247822d1e180a9bc6d4.js not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/767-b358f3ba5f72b363e80a.js not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/Content/965-a175a15e417d6c2abf63.css not found 
[Warn] StaticResourceMapper: File /app/sonarr/bin/UI/sonarr/965-8247822d1e180a9bc6d4.js not found 
```

### Environment

```markdown
- OS: Arch Linux 6.6.32-1lts / Windows 11
- Sonarr: Sonarr 4.0.5.1710
- Docker Install: Yes (Linux) / No (Win)
- Using Reverse Proxy: Tried with and without Traefik on Linux
- Browser: Firefox 126
- Database: ???
```

### What branch are you running?

Main

### Trace Logs?

Doesn't seem to have much relevant.
[sonarr.trace.txt](https://github.com/user-attachments/files/15848223/sonarr.trace.txt)

### Anything else?

[sonarr.txt](https://github.com/user-attachments/files/15848250/sonarr.txt)

**Comment by stevietv** [comment]
After changing UrlBase you will need to restart your instance of Sonarr.

**Comment by SrGesus** [comment]
How silly of me, i thought i was restarting but i had the restart api request wrong :facepalm:
