### ISSUE TITLE
Real IP not logged behind reverse proxy

### ISSUE THREAD

**Issue by Salvora** [Sonarr/Sonarr#6884]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hi,
This might be a repeat of the issue outlined below
https://github.com/Sonarr/Sonarr/issues/3711

I just see the reverse proxy ip address on the logs during authentication.
I use Synology Reverse Proxy which uses nginx on the backend and looking at the configuration headers, everything seems to be set correctly.

```nginx
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name sonarr.mydomain.org ;
    if ( $host !~ "(^sonarr.mydomain.org$)" ) { return 404; }
    include /usr/syno/etc/www/certificate/ReverseProxy_736ba569-3396-4b4c-9bcd-3f4a8dc764ba/cert.conf*;
    include /usr/syno/etc/security-profile/tls-profile/config/ReverseProxy_736ba569-3396-4b4c-9bcd-3f4a8dc764ba.conf*;
    proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    location / {
        proxy_connect_timeout 60;
        proxy_read_timeout 60;
        proxy_send_timeout 60;
        proxy_intercept_errors off;
        proxy_http_version 1.1;
        proxy_set_header        Upgrade            $http_upgrade;
        proxy_set_header        Connection            $connection_upgrade;
        proxy_set_header        Host            $http_host;
        proxy_set_header        X-Real-IP            $remote_addr;
        proxy_set_header        X-Forwarded-For            $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto            $scheme;
        proxy_pass http://localhost:8989;
    }
```

### Expected Behavior

Sonarr should log real client ip behind reverse proxy.

### Environment

```markdown
- OS: Docker on Synology
- Sonarr: 4.0.5.1710
- Docker Install: Yes
- Using Reverse Proxy: Yes 
- Browser: Firefox 127.0
- Database: Sqlite
```

### What branch are you running?

Main

### Trace Logs?

2024-06-17 01:50:53.6|Warn|Auth|Auth-Failure ip 192.168.50.52 username 'asdasd'
2024-06-17 01:50:57.1|Warn|Auth|Auth-Failure ip 192.168.50.52 username 'afavgwa'
2024-06-17 01:51:00.6|Warn|Auth|Auth-Failure ip 192.168.50.52 username 'r343'

**Comment by markus101** [comment]
Things have changed since that, but I am unable to reproduce using traefik as a reverse proxy, though people run many different setups without reported issues.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
