### ISSUE TITLE
Create New Filter for Percentage of Seasons Monitored

### ISSUE THREAD

**Issue by jbstark** [Sonarr/Sonarr#6896]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently you are able to filter for shows that have an unmointored season, but not for shows that have a monitored season or what percentage of seasons are monitored. This would be helpful for showing shows that the currents seasons you have "completed". By unmonitoring seasons for which you don't want to search for any more downloads, but keeping the show monitored, you can track your progress.

### Describe the solution you'd like

Create a Percent of seasons monitored filter to replace HasUnmonitoredSeason

Would be able to see if all seasons are monitored by using =100
Would be able see if any season is unmonitored by using <100
Would be able to see if all seasons are unmonitored by using = 0
Would also allow for any number in between (like 50%)

Migrate any filter using HasUnmonitoredSeason to the new version:

<code>HasUnmonitoredSeason is True</code> and <code>HasUnmonitoredSeason is not False </code> becomes <code>SeasonsMonitored Less than 100</code>
<code>HasUnmonitoredSeason is False</code> and <code>HasUnmonitoredSeason is not True</code> becomes <code>SeasonsMonitored equal 100</code>

### Describe alternatives you've considered

Two other options I came up with were:
Create a HasMonitoredSeason filter

The first is by far the easiest as it is just duplicating the HasUnmonitoredSeason code but changing the != to =. This would also make it unnecessary to delete HasUnminotredSeason as they would not overlap entirely, but some logic would be able to do be done with either

Create a SeasonMonitorState filter with options of All Seasons Monitored, Seasons Mixed, and All Seasons Unmonitored

The second works well, and might be easier to understand than my preferred solution but doesn't offer as much flexibility

### Anything else?

Preferred outcome
![image](https://github.com/Sonarr/Sonarr/assets/33739840/cd5caff5-9041-4ac1-afd9-a33268ba4225)

Edited because I messed up the formatting

**Comment by markus101** [comment]
I see no reason to overcomplicate things and make it a percentage based calculation.

- Just adding `HasMonitoredSeason` is the simplest way to add this functionality without migration.
- `SeasonMonitorState` would be a bit more flexible with a single filter, but would require migrating `HasUnmonitoredSeason`

**Comment by markus101** [comment]
The migration will require altering the JSON in the `filters` column, similar to how the encryption was changed in https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Datastore/Migration/201_email_encryption.cs

For the migration, `210` should be safe to use currently.

**Comment by jbstark** [comment]
Just finished writing the migration for the json using 210, and wrote tests for the migration. Let me know if there is anything else I should do before submitting a pull request.

**Comment by markus101** [comment]
No sense in not opening a PR at this point so we can review and provide feedback.
