### ISSUE TITLE
Custom colon replacement option

### ISSUE THREAD

**Issue by Zerauskire** [Sonarr/Sonarr#6898]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No problem. Just a request.

### Describe the solution you'd like

Currently the only options to handle colons are to delete them or replace them with hyphens. I was curious if it could be considered to replace the standard Colon (Punctuation) symbol with the Colon (Letter) symbol? I know this may sound odd to anyone unfamiliar but the standard colon symbol we have bound to our key on our keyboard is the Colon (Punctuation) symbol however, there exists another symbol for the Colon which is recognized by filesystems as a letter. Windows and MacOS which block the punctuation version in file names, allow the letter version in filenames. I'd like to see if it would be possible to allow the option to replace the punctuation colon with the letter colon. If this is not an option that's fine. Just putting it out there.

### Describe alternatives you've considered

Alternatives considered? Just the good old trusty " - ". lol

### Anything else?

For those interested in knowing more here are some links about this:
https://en.wikipedia.org/wiki/Colon_(letter)
https://en.wikipedia.org/wiki/Colon_(punctuation)
https://en.wikipedia.org/wiki/Filename

A lot of web apps and search engines allow you to use these interchangeably. Plex being one of them. You can actually search in Plex using the Colon (Letter) or Colon (Punctuation) in the movie or show title and it will find the same results. Plex will scan movie files with Colon (Letter)'s in the names and recognize them just fine.

At the same time, you could even implement this interchangeability in to Sonarr as well. Right now using the search feature in Sonarr with the Colon (Letter) does not work in movie titles.... But it could... I don't know enough about the complexities of how everything is handled in the background of Sonarr so I don't know if implementing the ability to use them interchangeably is a easy task or not. I'm assuming there's already a function that exists to validate and clean up data from input fields. This could just be updated to swap the Colon (Letter) with the Colon (Punctuation) when searching or querying indexers etc... This way it doesn't matter what the user enters, it will still return the same results.

If you want to try for yourself,
This is a Colon (Letter) - ꞉
This is a Colon (Punctuation) - : 
While they look identical, they are not. Give it a try. Copy the first one and paste it in a file name. You'll see that it allows it and looks identical to the standard colon we typically use.

As far is being concerned with how this could impact any code or things like that, it should have no impact on this at all. No coding languages should misinterpret this as the punctuation version and shouldn't even need to be escaped. While we see them as identical. Coding languages see them as totally separate characters. 

I currently do this in FileBot today. I replace the regular colon with the Colon (Letter) and it works just fine. Plex sees the file and associates it with no issues. I know nothing about the impact this has in Jellyfin though because I don't use Jellyfin.

**Comment by CLHatch** [comment]
This is actually a feature I've been wanting for quite a while now.  I use https://github.com/rmcrackan/Libation to rip my Audible library to the PC, and it has a feature of using "global" character replacement list (not just for `:`, but `?`, etc).  I was looking at the repo, and it appears this is where the main work for that is done: https://github.com/rmcrackan/Libation/blob/master/Source/FileManager/ReplacementCharacters.cs

**Comment by Zerauskire** [comment]
Just one more thing to note. If you find that the letter version of the colon causes any issues, you can try using the Ratio symbol which also look identical to the colon but is acceptable in filenames.

This is the Ratio symbol - ∶

**Comment by CLHatch** [comment]
> Just one more thing to note. If you find that the letter version of the colon causes any issues, you can try using the Ratio symbol which also looks identical to the colon but is acceptable in filenames.
> 
> This is the Ratio symbol - ∶
> 
> Also, on a related subject. There are symbols that are acceptable in filenames to replace forward slashes and backslashes too. This came to mind when I was trying to replace one in the movie title for "50/50 (2011)". You can actually use this and it's acceptable and looks similar "50∕50 (2011)".
> 
> / = ∕ \ = ∖
> 
> Definitely not as important as the colon but just food for thought.

Those are very likely the same characters I have Libation replacing with for my audiobooks.  They work out very well.

![image](https://github.com/Sonarr/Sonarr/assets/13066223/0025f8fd-30d7-455c-8453-3815ac23df12)

**Comment by woodfill-mike** [comment]
I think a - or something would be better, rather then introducing characters that may translate badly, or even cause confusion by end users

**Comment by Zerauskire** [comment]
Sure. Certainly a valid concern. I would note that I currently use the Colon (Letter) in all my libraries for Movies and for TV Shows (Radarr and Sonarr). I have yet to run in to any issues with these characters being in my file names. I have also tested using the Ratio symbol as well and no issues there either. Plex also handles it perfectly fine.

The only "issue" I've encountered so far (and I wouldn't even really call it an issue) is that when searching for a show, I can't use the Colon (Letter) or Ratio symbol in the search field to find the show because it doesn't recognize it as being the same as the Colon (Punctuation). That's not really a big deal though because it's not likely anyone would be searching that way when typing. Since the Colon (Punctuation) is the one bound to all keyboards, anyone typing in to search would use that and it would work just fine. Using the search field is not searching for the file names, it's searching for the Show/Movie titles themselves which contain the Colon (Punctuation). It would be no different than if someone tried to search for a Movie or Show using " - ". It would have the same issue.

So I guess if the developers wanted to go above and beyond and just enable that ability to interchangeably use theses other symbols when searching for a movie like the Plex developers did, that's up to them. I don't think it's necessary. 

I can't really speak for any potential issues the other characters for the backslash and stuff could cause and it's why my initial/main request is just for the colon replacement option. The other characters could be something to maybe consider down the road. They certainly aren't as common as the colon so their use case isn't big.

**Comment by CLHatch** [comment]
> I think a - or something would be better, rather then introducing characters that may translate badly, or even cause confusion by end users

I'm not sure how it could cause confusion to the end user to give them the option to replace with any string the end user wants. If the end user chooses to replace with a unicode character, they knew what they were doing.

**Comment by markus101** [comment]
Instead of trying to deal with all the different permutations of file systems and potential replacement characters outside of what is already provided, we've decided to add a custom option which will allow you to replace the colon with that character. No immediate plans to bring this to other characters.

**Comment by CLHatch** [comment]
> Instead of trying to deal with all the different permutations of file systems and potential replacement characters outside of what is already provided, we've decided to add a custom option which will allow you to replace the colon with that character. No immediate plans to bring this to other characters.

If you might consider adding the same for `?`, that would be great.  `:` and `?` are likely the two most common "illegal" character you'll see in a name.  I understand that the reason you likely did it for `:` and not others is that it was modifying existing code, where `?` would require adding code, of course.  Low-hanging fruit. :)
