### ISSUE TITLE
Increase Absolute Episode Number for S1EXX

### ISSUE THREAD

**Issue by maodun96** [Sonarr/Sonarr#6902]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Through [jproxy](https://github.com/LuckyPuppy514/jproxy), I can modify the confusing Chinese BT seeds into names suitable for sonarr, but sonarr cannot currently recognize the absolute episode number of S1EXX.
![image](https://github.com/Sonarr/Sonarr/assets/43996175/7b76f82c-6d35-4745-830d-7a01376fe816)

For example, S1E62 is recognized as the absolute episode number: 62.

I thought about it and it seems that this change will not affect the existing operating logic.

### Describe the solution you'd like

Add rules：the Absolute Episode Number of S1EXX is XX.

### Describe alternatives you've considered

I tried to modify jproxy's regular expression, but the software's logic changed the torrents containing Absolute Episode to -XX.

**Comment by maodun96** [comment]
This is a great software, it uses regular expressions to split and reorganize messy Chinese seed names into:

{title} {season}{episode} {language}{subtitle}{resolution}{quality}{dynamic_range}{group}

It also replaces Chinese TV series names with the English TV series names from TVDB or TMDB.

In theory, it should also be compatible with English names of seeds.
Maybe a similar approach will end some of the endless debates about "Anime" type.

**Comment by bakerboy448** [comment]
SYEXX is Standard Episode Formatting and can/will never match Anime Absolute Numbering

https://wiki.servarr.com/sonarr/faq#whats-the-different-series-types

**Comment by maodun96** [comment]
> SYEXX is Standard Episode Formatting and can/will never match Anime Absolute Numbering
> 
> https://wiki.servarr.com/sonarr/faq#whats-the-different-series-types

In my understanding, isn't yy in S1Eyy the Anime Absolute Numbering? Absolute Numbering is only used for RSS searches of anime type. It does not affect any running logic in essence.
I raised this requirement because I think this is the best solution at the moment.

If there is no Sxx, but only Eyy, do you think yy should be considered as Absolute Numbering?

**Comment by bakerboy448** [comment]
Your understanding is incorrect - see the FAQ. The formatting is also detailed when adding a series for the Series Type.

**Comment by markus101** [comment]
If you want absolute numbering you need to use absolute numbering. As mentioned putting a season number in there makes it standard numbering.

There are plenty of examples n the tests that show the expected formats for absolute numbering that you can follow to have Sonarr parse the release name as an absolute number instead of standard.
