### ISSUE TITLE
Respect X-Forwarded-Prefix header

### ISSUE THREAD

**Issue by richard087** [Sonarr/Sonarr#6905]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The urlbase value in config.xml is clunky to setup, and fragile. The X-Forwarded-Prefix header is generally used for the purpose and it more robust and doesn't require any configuration of sonarr to implement.

Increasing prevalence of docker-compose and k8s setups make this an increasingly common scenario.

### Describe the solution you'd like

Follow [Fielding's intent](https://ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm#sec_5_1_6 ) to provide a layered system. As such, the server process (Sonarr) should not assume to have the path for the client (via the urlbase configuration parameter).

[urlbase](https://github.com/Sonarr/Sonarr/blob/ea4fe392a0cc4774bb28c969fb3903db264c8d6c/frontend/src/index.ts#L6) should be overridden if an X-Forwarded-Prefix header is part of the request.

### Describe alternatives you've considered

In a deployment of all the servarr components, rewrite all the config.xml files.

### Anything else?

MS discussion of how to work with reverse proxies: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-8.0&branch=pr-en-us-32295#forwarded-headers

Misplaced report, including demonstration of the issue (and typical struggles) https://github.com/Prowlarr/Prowlarr/issues/2161

**Comment by markus101** [comment]
The URL base is also configurable via Environment variables.

The problem with using the prefix from the request would be around cached html files that require the URL base to know which paths to set. If Sonarr gets different requests with different prefixes things are going to break for one or the other.

This would be a feature that would  go mostly untested and unused by the vast majority of the user base and be another point for reverse proxy support to be misconfigured so I'm not sure it's worth the added complications of supporting it.

**Comment by markus101** [comment]
No current plans for this.
