### ISSUE TITLE
Stuck on 'waiting to import'

### ISSUE THREAD

**Issue by gouthamravee** [Sonarr/Sonarr#6906]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Finished items regardless of downloader type is getting stuck at 'waiting to import' 

### Expected Behavior

Finished items move from waiting to import, to importing, and then finish. 

### Environment

```markdown
- OS: Debian 12
- Sonarr: 4.0.5.1778
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox x64
- Database:     Sqlite 3.45.3
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.trace.txt](https://github.com/user-attachments/files/15981458/sonarr.trace.txt)

### Anything else?

I checked the info and debug logs, and didn't see anything about moving/importing/errors.

**Comment by markus101** [comment]
Based on the limited logs, `ProcessMonitoredDownloads` is already executing or queued to run. I'm not able to reproduce this behaviour, but if you're still having issues please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr).
