### ISSUE TITLE
Feature Request: Add custom filter conditions to release profiles

### ISSUE THREAD

**Issue by arthurmelton** [Sonarr/Sonarr#6908]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The current problem that can arise is say you only want to grab single episodes from a said indexer but want to allow all other indexers to grab everything normally. Release profiles are already setup to do filtering based on the indexer source, but what they are able to filter by is not as powerful as custom filters. Being able to use the custom filter conditions inside a release profile would be very helpful.

### Describe the solution you'd like

I believe the easiest way that this could be solved is if the custom filter conditions were added to release profile. It would be able to do very complex filtering on a per index bases.

### Describe alternatives you've considered

The other solution that I though of is what if custom filters has another condition for the indexer that it came from, but I felt that this would become very confusing very quickly as all of your normal custom filters would be in the same place as your per index filters. If the location for per index filtering already exists, might as well put it in that location instead.

**Comment by markus101** [comment]
Further enhancing release profiles is not something we are going to commit to at this time, this may change in the future, but nothing in the foreseeable future.

**Comment by arthurmelton** [comment]
Would a PR of the proposed change be looked at?

**Comment by arthurmelton** [comment]
So when you look at the conditions for custom formats you have things like: Release Title, Language, Indexer Flag, etc. I would like to be able to use these "filters" on a specific indexer. Release profiles already allow you to filter results to have a specific piece of text in them, while only doing it on a per index bases. My idea would be to add the custom format conditions into release profiles, so I could make a specific indexer having to follow a specific Release Title, Language, Indexer Flag, etc.

So like the end product would be that you could for example make RuTracker only be able to grab torrents if the language is Russian. It would be like custom formats but only for a specific tracker.

I am somewhat doing a xy problem here, where I would like the functionality to limit the size of torrents grabbed from a specific indexer (a custom filter condition). I felt that implementing all of the custom filter conditions to release profiles might help some other people who maybe want to do some complex filtering behavior based on indexers.

**Comment by stevietv** [comment]
An indexer specification could perhaps help here?

**Comment by arthurmelton** [comment]
@stevietv what do you mean?

**Comment by bakerboy448** [comment]
You keep mixing custom filters and custom formats - they are not at all the same. Which are you talking about?

Adding an Indexer Condition to Custom Formats is an outstanding feature request. Everyone but OP seems to believe this will address this request.

>  I was currently working on my pr for adding the specifications to release profiles, but if you all think that an indexer specification should be added

Porting Custom Format Conditions to Release Profiles is a non-starter

**Comment by markus101** [comment]
Adding Custom Format specifications to Release Profiles would be a lot of duplication and a lot of potential for confusion by users and support. I think if anything is added it'd make sense to add `Must Contain Custom Format` and `Must Not Contain Custom Format` options to Release Profiles, this way you're not duplicating things and allows for more control within Release Profiles. It does mean the potential for additional Custom Formats to be created, but they wouldn't change the behaviour of things if the score was left at 0.

**Comment by arthurmelton** [comment]
> You keep mixing custom filters and custom formats - they are not at all the same. Which are you talking about?

Whenever I mix the two, I am always talking about custom formats / the custom format conditions.

> Adding an Indexer Condition to Custom Formats is an outstanding feature request. Everyone but OP seems to believe this will address this request.

Its just that for me at least using TRaSH, my custom formats are already really long and its specifically made to try and search for what I consider the best quality stuff. I don't really want to have to mix my per indexer grabbing settings and quality sorting stuff. This also has the same problem when you are looking in your qualities, they will both be mixed together. I atleast would prefer to have both of these separate, but that could just be that for my unique use stance where they will be separate, others might use them together.

> It does mean the potential for additional Custom Formats to be created, but they wouldn't change the behaviour of things if the score was left at 0.

For me atleast I feel like that would almost have the same outcome as if an indexer condition was added to custom formats. The user could just do the same thing TRaSH does and set the score to something like `-10000` and have the same outcome.

> Porting Custom Format Conditions to Release Profiles is a non-starter

My current idea was to make `Specifications` more of a global item and not necessarily tied to  `Custom Formats`, that would still give the ability to only have to edit one place to get them added to both. When I was working on doing that though, I realized that I might be over complicating thing, and that in the end it might just be better to add a indexer condition.

> I think if anything is added it'd make sense to add `Must Contain Custom Format` and `Must Not Contain Custom Format` options to Release Profiles

If this was done then the `Must Contains` and `Must Not Contains`, could be obsolete because there is already a specification / condition to do searches on the title.

**Comment by markus101** [comment]
> For me atleast I feel like that would almost have the same outcome as if an indexer condition was added to custom formats. The user could just do the same thing TRaSH does and set the score to something like -10000 and have the same outcome.

My point was that if you do nothing with a custom format a score of zero has zero impact on the processing of results, setting something to -10000 does.

>If this was done then the Must Contains and Must Not Contains, could be obsolete because there is already a specification / condition to do searches on the title.

Sure, but adding CF specifications to release profiles would do the same thing, unless ones that operate on the release title are ignored those can't easily be migrated, eventually they could be removed in a future major version.

Sounds like Indexer as a CF specification has been requested elsewhere previously, so probably makes the most sense to go with that, which will handle the majority of cases, later we can decide if release profiles makes sense to also consume CFs (or whether it would make more sense to remove and rely solely on CFs + scoring).

**Comment by stevietv** [comment]
reference open radarr FR https://github.com/Radarr/Radarr/issues/6697

**Comment by arthurmelton** [comment]
> How are you going to deal with the persistent data regarding the indexer data in EpisodeFiles? Id, name? These can change and might lead to some useless grabs along the way.

Release profiles use the indexer id. If they work the same as prowlarr, its a always incrementing number so even if you remove one indexer, the rest of them will still have the same id. As for if the specification required a specific indexer and that indexer does not exist anymore, I think making the specification still work as attended and thus now will not match any indexer, effectively doing nothing.

**Comment by arthurmelton** [comment]
If I understand what you are saying, cant this happen in lots of different situations and not only this one? Why does it require the scoring to be the same though. The ultimate reason I want this feature is so that I could create a script so that the *arr's won't grab too many releases and eat my buffer if I turn off free leech only.

**Comment by arthurmelton** [comment]
> I already explain why the score needs to be the same to prevent download loops

I mean why does it cause download loops. Is it because it searches the torrents and gets the score, then on important it scores it again, then there is the risk that something else could now have a score that is higher? That is what I am asking. That is what I mean by this could happen in a lot if different situations. Couldn't you edit any of your custom formats and now something else could have a higher score?

> Overall the indexer specification for custom formats is just a bad idea trying to fix your buffer issues

Well, my ratio is really good because I have mainly sticked to freeleeches for so long, but I would like to have a safety net for the *arrs. I don't want to disable RSS and automatic searches because now there is almost no point to the *arrs. I just want to make sure that for example some large (tv) show I have downloaded does not have an upgrade overnight and eats up tbs of my buffer.

**Comment by markus101** [comment]
> I mean why does it cause download loops. Is it because it searches the torrents and gets the score, then on important it scores it again, then there is the risk that something else could now have a score that is higher? That is what I am asking. That is what I mean by this could happen in a lot if different situations.

Yes, because a download isn't 1:1 with an episode it needs to recalculate the score + it needs to recalculate it whenever something changes with CF specifications.

> So if remove an indexer and then add it again and update the custom format, you might get a download loop because the existing file lost some points in the scoring because it can't match the initial indexer anymore.

This can help for other reasons as well, remove and re-add a series when you have Release Type would do it as well.

We could mitigate this to some degree by also storing the indexer name, but if you removed, re-added and changed the name you'd have issues.
