### ISSUE TITLE
Regex match inconsistant (develop version)

### ISSUE THREAD

**Issue by TheNexter** [Sonarr/Sonarr#6917]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

In the first screenshot we can see only the first one is HEVC tag other are not :
![image](https://github.com/Sonarr/Sonarr/assets/17613028/16578f09-3dd8-4e53-8286-f3f869514df8)
Example for other that is not tag :
![image](https://github.com/Sonarr/Sonarr/assets/17613028/76bcac62-7f5c-4d86-a145-897e74b62453)

### Expected Behavior

All HEVC / X265 need to get the good score

### Steps To Reproduce

My regex is :
`(((x|h)\.?265)|(HEVC))`

![image](https://github.com/Sonarr/Sonarr/assets/17613028/e8e6de39-7a00-47dc-82d0-7c876b45022f)
![image](https://github.com/Sonarr/Sonarr/assets/17613028/45812d1a-24f1-442a-a250-80e546265deb)

### Environment

```markdown
- OS: Unraid
- Sonarr: 4.0.5.1778 — Jun 26 2024 develop (almost latest, i will update soon to verify if bug continue)
- Docker Install: yes, image linuxserver
- Using Reverse Proxy: yes
- Browser: firefox
- Database: default sqlite from linuxserver
```

### What branch are you running?

Develop

### Trace Logs?

[error-match-hevc.txt](https://github.com/user-attachments/files/16041685/error-match-hevc.txt)

**Comment by TheNexter** [comment]
Another example in the same episode :
![image](https://github.com/Sonarr/Sonarr/assets/17613028/a39aa43d-fa58-43d4-9054-34fac312192e)

**Comment by stevietv** [comment]
please update 1791 - this may have fixed it.
report back if not. Note that if running develop you should always update to the most recent version before reporting a bug

**Comment by TheNexter** [comment]
> please update 1791 - this may have fixed it. report back if not. Note that if running develop you should always update to the most recent version before reporting a bug

I confirm, 1791 fixed the problem ;)
