### ISSUE TITLE
After running for some time sonarr act weird (fail to add content and communication lost between sonarr and ombi) 

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Sonarr/Sonarr#6931]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After running for some time the sonarr start to act weird like when I do interactive search to add content it fails or when pair with ombi, some issues happen and ombi do not communicate with sonarr

### Expected Behavior

Adding content work  

### Steps To Reproduce

1. Add content via interactive search 
2. Or, Via ombi (communication get lost by sonarr) 

### Environment

```markdown
- OS: Debuab sed
- Sonarr: 4.0.6.1805
- Docker Install: 4.0.6.1805-ls244 by linuxserver.io
- Using Reverse Proxy: yes, nginx
- Browser: Brave
- Database: Sqlite 3.45.3
```

### What branch are you running?

Main

### Trace Logs?

https://logs.notifiarr.com/?c23b318d7142f04e#9T8pfhDHHT3Tp6THwAonm5zwRHVGoDreMKivv9imJE3r

### Anything else?

no

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
