### ISSUE TITLE
Ability to use any newznab attribute in custom format conditions

### ISSUE THREAD

**Issue by amdavie** [Sonarr/Sonarr#6932]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

I would like to be able to use non-standard newznab attributes from RSS results in custom formats. I'm thinking this would be a new custom format condition (specification) with 2 fields - attribute name and attribute value regular expression.

Some examples:
```xml
<newznab:attr name="grabs" value="250"/>
<newznab:attr name="nuked" value="1"/>
<newznab:attr name="encrypted" value="1"/>
<newznab:attr name="haspretime" value="0"/>
```

Being able to tap into these attributes would allow for improved scoring of releases.

### Describe alternatives you've considered

Some indexers might have a way to filter results with query parameters as desired but not always.

### Anything else?

I just wanted to start a conversation to see if I'm not missing something that already allows this feature, and if not then is it a welcome feature.

I'm willing to contribute if so.

**Comment by markus101** [comment]
One problem is going to be the dynamic nature of these, using your snippet, if you grab it at 250, then it's on another indexer with 300 then Sonarr then Sonarr is potentially going to see if as an upgrade (depending on your CFs).

Nuked and encrypted could be useful, but will lead to a similar problem if changed after grabbing. Not sure what `haspretime` refers to be able to say whether it would be useful or problematic.

@mynameisbogdan I imagine you have some insight here since you did the indexer flags work.

**Comment by amdavie** [comment]
> One problem is going to be the dynamic nature of these, using your snippet, if you grab it at 250, then it's on another indexer with 300 then Sonarr then Sonarr is potentially going to see if as an upgrade (depending on your CFs).
> 
> Nuked and encrypted could be useful, but will lead to a similar problem if changed after grabbing. Not sure what `haspretime` refers to be able to say whether it would be useful or problematic.
> 
> @mynameisbogdan I imagine you have some insight here since you did the indexer flags work.

I guess `grabs` is not a great example as you pointed out but `haspretime` is actually one that I'm specifically interested in being able to use to prioritize scene releases on a specific indexer. Because it is a non-standard attribute, it seemed the most reasonable to just have the ability to use any attribute even though most of them may not be practical to use in custom formats.

**Comment by thezoggy** [comment]
> > One problem is going to be the dynamic nature of these, using your snippet, if you grab it at 250, then it's on another indexer with 300 then Sonarr then Sonarr is potentially going to see if as an upgrade (depending on your CFs).
> > Nuked and encrypted could be useful, but will lead to a similar problem if changed after grabbing. Not sure what `haspretime` refers to be able to say whether it would be useful or problematic.
> > @mynameisbogdan I imagine you have some insight here since you did the indexer flags work.
> 
> I guess `grabs` is not a great example as you pointed out but `haspretime` is actually one that I'm specifically interested in being able to use to prioritize scene releases on a specific indexer. Because it is a non-standard attribute, it seemed the most reasonable to just have the ability to use any attribute even though most of them may not be practical to use in custom formats.

then you pass the argument to your indexer to only return those results..  (which may be different per the indexer or whats supported depending if they are using nn/nzedb/nntmux/custom or what). for example: `pred=1`  

you dont need to do this AFTER the fact with nzb metadata which you wouldnt know until you got the nzb. which would be highly suboptimal.  but also you can just use trash's `scene` custom format to go that route as well to target those releases

**Comment by amdavie** [comment]
> > > One problem is going to be the dynamic nature of these, using your snippet, if you grab it at 250, then it's on another indexer with 300 then Sonarr then Sonarr is potentially going to see if as an upgrade (depending on your CFs).
> > > Nuked and encrypted could be useful, but will lead to a similar problem if changed after grabbing. Not sure what `haspretime` refers to be able to say whether it would be useful or problematic.
> > > @mynameisbogdan I imagine you have some insight here since you did the indexer flags work.
> > 
> > 
> > I guess `grabs` is not a great example as you pointed out but `haspretime` is actually one that I'm specifically interested in being able to use to prioritize scene releases on a specific indexer. Because it is a non-standard attribute, it seemed the most reasonable to just have the ability to use any attribute even though most of them may not be practical to use in custom formats.
> 
> then you pass the argument to your indexer to only return those results.. (which may be different per the indexer or whats supported depending if they are using nn/nzedb/nntmux/custom or what). for example: `pred=1`
> 
> you dont need to do this AFTER the fact with nzb metadata which you wouldnt know until you got the nzb. which would be highly suboptimal. but also you can just use trash's `scene` custom format to go that route as well to target those releases

Right, the problem is one of my indexers does not support a search parameter of `pred=1` or similar which led me to looking at other options. I could try to take it up with the indexer though.

**Comment by markus101** [comment]
> I don't find them suitable for custom formats or indexer flags

If `haspretime` indicates its a scene release wouldn't that be the same as the `Scene` indexer flag that already exists?

> I don't see any of them in the [spec](https://newznab.readthedocs.io/en/latest/misc/api.html) so I don't know how widely used they are.

This is definitely a concern, but the spec hasn't really been updated and I think we already use some not documented things.

Nuked would be nice, but really that should be a hard exclude and wait for the proper/repack + Sonarr won't keep the nuked status in sync as relying on that alone wouldn't upgrade a nuked release after it was grabbed.

**Comment by amdavie** [comment]
So it looks like `IndexerFlags` is only populated on the torrent side of things at the moment but extending that to usenet releases would indeed be a simple change - specifically for the `Scene` bit.

The non-standard nature of these gives me pause to use in code, but at the same time something like `haspretime` really can't be mistaken for anything else (i.e. give a false positive). I can look at a few indexers and see if there is any commonality in non-standard attributes.

**Comment by amdavie** [comment]
I'm not really seeing any commonality. Across 6 or 7 indexers I see 2 attributes would set the `Scene` bit for usenet releases:

```xml
<newznab:attr name="haspretime" value="1"/>
<nZEDb:attr name="prematch" value="1"/>
```

I'd be happy with that, but I'm not familiar with the implications that would cause for Prowlarr so I'll leave it up to you or any others to weigh in on whether it would be worth it.

**Comment by amdavie** [comment]
I used to use that but it's pretty limited. I have some of my own custom formats that have expanded on it but they aren't perfect either.
