### ISSUE TITLE
[Duplicate Title Slug] Heroes (2006) and Heroes (2024)

### ISSUE THREAD

**Issue by ExNihilius** [Sonarr/Sonarr#6939]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hope this is ok, was told creating an issue on github is fine.
While trying to add Heroes (2024) (https://www.thetvdb.com/series/tian-xing-jian) (tvdb:445600) I get an error, because it uses the title slug "Heroes" reserved for Heroes (2006) (https://www.thetvdb.com/series/heroes) (tvdb:79501).

### Describe the solution you'd like

Fix via Skyhook.

### Describe alternatives you've considered

None, other than removing the old show as I was mainly keeping it for nostalgia.

### Anything else?

Hope this is acceptable and thanks! <3

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

This should be fixed on TheTVDB by fixing the title for the new series so it does not conflict with the original series.
