### ISSUE TITLE
Automatically remove torrent for existing episode when a different episode version is found

### ISSUE THREAD

**Issue by SnowySailor** [Sonarr/Sonarr#6940]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When you've got many different shows that you're tracking in sonarr, new versions of episodes come out all the time (quality improvements, better encoders, better sources like BR, etc.) and when those get picked up, the previous version's torrent remains in your torrent client until you manually remove it. With dozens of different shows, this becomes impossible to manually keep track of and duplicate episodes eat up disk space. While it is possible to set a seed ratio limit, some users prefer to seed their torrents forever.

### Describe the solution you'd like

Add a checkbox (or some sort of setting) that allows for the following: when a new match is found for an episode, automatically delete all existing torrents for that episode from the torrent client (which should remove them from disk as well) before adding the new one. If a season batch torrent is found, iterate over the episodes in that batch and remove all the torrents for them in the torrent client.

### Describe alternatives you've considered

Manually going through every day and clearing out old torrents that are no longer used
Limiting the seed ratio so they are automatically removed after reaching a certain ratio (this one doesn't work well since there are also non-sonarr torrents in qbittorrent that I don't want to delete after reaching a specific ratio)

**Comment by markus101** [comment]
We do not have plans to remove previous torrents when a new torrent is added, setting seeding goals and having Sonarr remove them is the recommended way to handle this. This will not affect torrents not added by Sonarr.

**Comment by SnowySailor** [comment]
Is there a specific reason for this? It seems like you could just associate a specific torrent with a specific episode in the database when it's downloaded (if that's not already done) and then just ask the torrent client to remove it when a new version is found. I haven't looked at the codebase, but this doesn't sound like a complicated feature request. Unless I'm not thinking of some edge cases that are too difficult to work around?

**Comment by augustuen** [comment]
It's not a technical issue. Sonarr finding an upgrade to your existing episode doesn't eliminate your obligation to seed the first version. That's why Markus told you to set seed limits instead. If you prefer to perma-seed and use hardlinks, you can use qbitmanage to set seed limits for upgraded torrents.

Either way, this won't be implemented in Sonarr, so if you require further help you should join us over in the Discord, or check out qbitmanage's support channels if you go that route.

**Comment by SnowySailor** [comment]
Thanks for the recommendation. That looks like it'll do what I want.
