### ISSUE TITLE
New colour code on Calendar for "grabbed" items

### ISSUE THREAD

**Issue by Mahava** [Sonarr/Sonarr#6945]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hi everyone,
since completed download handling can be disabled,  can you add a colour code for items that are completed by the download client but isn't downloaded to disk?

I don't ever download to disk, currently, so all my grabbed items are coloured Red for 'missing'.

### Describe the solution you'd like

I want to know when my items are grabbed by reading the Calendar tiles' colour coding....regardless of whether they have been downloaded to disk.

### Describe alternatives you've considered

I think there used to be an icon on the tiles that denotes 'grabbed'?  I don't have that anymore.

**Comment by markus101** [comment]
This isn't a state that Sonarr tracks, when Completed Download Handling is enabled completed downloads are removed from Sonarr's queue without further processing, to Sonarr they are missing.

We do not have plans to continue tracking those downloads so they can be displayed in the UI as completed. One potential work around would be to leave CDH enabled, but prevent Sonarr from importing by using an invalid Remote Path Mapping, then everything would be in the queue as downloading.

**Comment by Mahava** [comment]
Thanks for the workaround, Markus.
I hope you guys will reconsider.  Hear me out:  Some people treat the cloud as a disk, so when it's finished downloading there, it could be considered finished in sonarr as well.
