### ISSUE TITLE
Add "tags" as a poster option to sonarr series. 

### ISSUE THREAD

**Issue by hacshacdgacs** [Sonarr/Sonarr#6946]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently it's difficult to see what tags have been applied to what shows at a glance. 

### Describe the solution you'd like

Add tags as an option to be shown on the poster view.
![image](https://github.com/Sonarr/Sonarr/assets/85550264/1909d9b7-b58d-4693-bc00-9eb5049b1bf5)

### Describe alternatives you've considered

I can see tags in emby and in the tags section but neither of these are useful at a glance.

### Anything else?

![image](https://github.com/Sonarr/Sonarr/assets/85550264/c2199364-aed3-4e91-9668-9d398a961356)
Having tags be added underneath the poster like the profile quality currently is would be nice.

**Comment by markus101** [comment]
Tags are also visible on the series details page and optionally under table. The concern with all them to the poster view is the lack of space to show many short tags or less longer ones.

**Comment by hacshacdgacs** [comment]
That's understandable. From my perspective I prefer the poster view and I only have at most two tags applied to a series at a time so the lack of space wouldn't be an issue personally.
