### ISSUE TITLE
Natural sorting for Custom Filters and Tags

### ISSUE THREAD

**Issue by Nocifer** [Sonarr/Sonarr#6955]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

As of #6334, Custom Filters that contain numbers are sorted alphabetically instead of naturally.

For example, if I create the filters `Rating 1`, `Rating 2` and `Rating 10`, they will be sorted like this:
```
Rating 1
Rating 10
Rating 2
```

### Expected Behavior

Custom Filters should be sorted naturally, like this:
```
Rating 1
Rating 2
Rating 10
```

### Steps To Reproduce

1. Create the custom filters `Rating 2` and `Rating 10`
2. Observe that they are sorted alphabetically instead of naturally.

### Environment

```markdown
- OS: Arch Linux
- Sonarr: 4.0.6.1805
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox 128
- Database: Sqlite 3.45.3
```

### What branch are you running?

Main

### Trace Logs?

N/A

**Comment by Nocifer** [comment]
Perhaps this would do the trick:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#numeric_sorting

**Comment by markus101** [comment]
If you have concrete things that are wrong then list them, but "probably some other stuff as well" isn't very useful.

**Comment by Nocifer** [comment]
> If you have concrete things that are wrong then please list them, but "probably some other stuff as well" isn't very useful.

My apologies; what I meant by it is "probably anything and everything in the UI that sorts entries by using the localeCompare() function".

I can't know for sure because I'm not Sonarr's developer and I'm not familiar with the code base (even for Tags I can't really be certain, I can only assume) but it's a fair bet that any other "stuff" in there that makes use of that kind of sorting is probably affected as well, so whoever takes up the task of fixing this issue should also make an effort to search for and look into all that other "stuff" as well, even if they're not mentioned here explicitly, in order to provide a proper and complete fix. That's all.
