### ISSUE TITLE
NZBindex API updated

### ISSUE THREAD

**Issue by YESIHACK** [Sonarr/Sonarr#6964]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Type {Torrent|Usenet}: Usenet
Tracker {Name}: NZBindex
URL {URL}:https://nzbindex.com/api/v3

API for Usenet NZBindex has been updated. prowlarr/sonar/radarr/etc.. needs to be updated to support the V3 API

### Expected Behavior

https://nzbindex.com usenet to sonnar

### Environment

```markdown
- OS: Unraid
- Sonarr: 4.0.6.1805
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.45.3
```

### What branch are you running?

Main

### Trace Logs?

2024-07-14 23:05:05.6|Trace|HttpClient|Res: HTTP/1.1 [GET] https://api.nzbindex.com/api/v3?t=caps&apikey=(removed) 200.OK (37568 bytes) (501 ms)
2024-07-14 23:05:05.6|Trace|NewznabCapabilitiesProvider|Unexpected Response content (37568 bytes): 
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>NZBIndex - We index, you search</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="/favicon.ico" type="image/x-icon" rel="icon"/><link href="/favicon.ico" type="image/x-icon" rel="shortcut icon"/><link rel="stylesheet" href="/css/bootstrap.min.css?v=6.1.43"/><link rel="stylesheet" href="/css/bootstrap-responsive.min.css?v=6.1.43"/><link rel="stylesheet" href="/css/nzbindex.min.css?v=6.1.43"/><link rel="stylesheet" href="/css/highlight.min.css?v=6.1.43"/><script src="/js/jquery.min.js?v=6.1.43"></script><script src="/js/jquery.cookie.min.js?v=6.1.43" defer="defer"></script><script src="/js/bootstrap.min.js?v=6.1.43" defer="defer"></script><script src="/js/nzbindex-all.min.js?v=6.1.43" defer="defer"></script><script src="/js/highlight.pack.js?v=6.1.43"></script>    <script async defer src='https://www.hCaptcha.com/1/api.js'></script>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>

			<a class="brand" href="/search">
				NZBIndex
			</a>

			<div class="nav-collapse collapse">
				<ul class="nav">
					<li class="active"><a href="/locale/en_US">English</a></li>
					<li><a href="/locale/nl_NL">Nederlands</a></li>
				</ul>

				<ul class="nav pull-right">
					<li><a href="/search">Search</a></li>
					<li><a href="/groups">Groups</a></li>
					<li><a href="/faq">FAQ</a></li>

									</ul>
			</div>
		</div>
	</div>
</nav>

	<div class="main container-fluid">
		<div id="news" class="alert alert-info hide"></div>
		<div></div>
		<style>
h2 {
    padding-top: 50px;
}
</style>

<h1>API v3 documentation</h1>

<div class="row-fluid">
    <div class="span8">
        <h2 id="introduction">Introduction</h2>

        <p>
            This document will describe the NZBIndex API specifications version 3. Through this API you are able to
            search, retrieve and download NZB data.

            The API is accessible through HTTPS:
            <pre>https://api.nzbindex.com/api/v3/</pre>

            Every request will require an API key (contact us if you have any questions regarding this key):
            <pre>https://api.nzbindex.com/api/v3/?<strong>key=abcdef</strong></pre>

            All API responses are <code>JSON</code> encoded.
        </p>
    </div>

    
    <div class="span3 offset1 hidden-phone">
        <ul class="nav nav-tabs nav-stacked">
            <li><a href="#introduction"><i class="icon-chevron-right"></i> Introduction</a></li>
            <li><a href="#search"><i class="icon-chevron-right"></i> Search</a></li>
            <li><a href="#syntax"><i class="icon-chevron-right"></i> Search syntax</a></li>
            <li><a href="#collections"><i class="icon-chevron-right"></i> Collections</a></li>
            <li><a href="#groups"><i class="icon-chevron-right"></i> Groups</a></li>
            <li><a href="#download"><i class="icon-chevron-right"></i> Download NZB files</a></li>
            <li><a href="#usage"><i class="icon-chevron-right"></i> API Usage</a></li>
        </ul>
    </div>
</div>

**Comment by markus101** [comment]
You need to update the URL Base to use that updated endpoint in your setup.
