### ISSUE TITLE
OnDownload notifications still being sent after update with OnImportComplete

### ISSUE THREAD

**Issue by fent** [Sonarr/Sonarr#6965]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After the fix to https://github.com/Sonarr/Sonarr/issues/363, I'm still getting "on download" notifications on Pushover. This is likely due to the "on download" option getting removed from the UI there, but still there in the settings. There's no way to turn it off since the option was removed.

This is the request from my Network tab, notice that `onDownload` is there:
![image](https://github.com/user-attachments/assets/de755995-8608-48b4-86f0-98c91f2efd81)

### Expected Behavior

I expect for one of
- not have the "on download" notification anymore
- turn off the "on download" notification when "on import complete" is turned on
- keep the "on download" option in the UI so users can choose to turn it on or off regardless of "on import complete"

### Steps To Reproduce

1. Have a previous version of sonarr with "on download" notifications
2. Set a notification for something like Pushover in the Connect set
3. Update to the latest version of sonarr
4. Update your notification to have "on download complete" enalbed
5. download a season of something
6. see that you still get the "on download" notification, and also the "on import complete"

### Environment

```markdown
- OS: Unraid 6.12.10
- Sonarr: 4.0.6.1847
- Docker Install: Yes
- Using Reverse Proxy: no
- Browser: Chrome
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

I don't think this bug requires trace logs, but ask if it does and i'll provide them

**Comment by markus101** [comment]
The setting still exists, it's called `On File Import` in the UI, previously it was `On Import`. `On Upgrade` will similarly be renamed to `On File Upgrade`.
