### ISSUE TITLE
Latest 4.07.1863 has some permission issues on Unraid

### ISSUE THREAD

**Issue by Kp1003** [Sonarr/Sonarr#6967]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When upgrading to the Latest 4.0.7-1863 release i get some weird permission issues of some kind. Running Sonarr on Unraid in Docker.

When a file is ready to be imported, it just stalls on importing, because of a permission issues. Although im still kind of a noob with Unraid and Docker, i know for sure that my permissions is good. I downgraded back to 4.0.6-1805, and then the importing works as intended.

### Expected Behavior

Sonarr should just be able to import like it always did. No problems on 4.0.6-1805.

### Steps To Reproduce

OS: Unraid 6.12.4
Sonarr 4.0.7-1863
Docker Install: Yes
Using Reverse Proxy: No
Database: Sqlite 3.45.3

### Environment

```markdown
- OS: 
- Sonarr: 
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Main

### Trace Logs?

I cant give you tracelogs for now, since i just reverted back instantly.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
