### ISSUE TITLE
Restriction

### ISSUE THREAD

**Issue by Varity** [Sonarr/Sonarr#697]
Hi let me try to explain this.

I have Anime "A" and Anime "B". 
I need an option to give only for anime "A" some specific restrictions/words which have to be in the torrent name.
And anime "B" need his own restrictions, because i need some content in english and german and i cant get my automation done without doing it manually.

Is there any way to have for every series/movies his own restriction? Not like we have it actually where all my content is being checked by the same restriction

**Comment by markus101** [comment]
Please use our forums for support.

Yes, use Release Restrictions (On indexer settings) and tags, series will need to be tagged as well.
