### ISSUE TITLE
The content layout option for qbittorrent is missing the NoSubfolder option

### ISSUE THREAD

**Issue by bobbintb** [Sonarr/Sonarr#6977]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I think this more of an oversight than anything. It's more of a feature request than a bug anyway. The "content layout" option for qbittorrent was added to the download client settings in a previous PR. The qbittorrent API shows the options `Original`, `Subfolder`, and `NoSubFolder`. The Sonarr options are `Default`, `Original`, and `Subfolder`. The default is whatever the default option is for qbittorrent, so it makes sense that it wouldn't be in the API. Unless I am misunderstanding something, the `NoSubfolder` option is missing.

### Describe the solution you'd like

The `NoSubfolder` option should be available no it never includes a subfolder.

### Describe alternatives you've considered

I wanted to make sure I wasn't misunderstanding and after looking at the code, it just seems to have been omitted from the original PR.

**Comment by markus101** [comment]
`NoSubfolder` would break any torrent with multiple files (season pack, video with sample, etc) so it's intentionally excluded.

**Comment by bobbintb** [comment]
> `NoSubfolder` would break any torrent with multiple files (season pack, video with sample, etc) so it's intentionally excluded.

Ah, ok, but I'm a little confused as to how. That would just tell qbittorent to change the setting, qbittorrent is what would handle the changes to the folder structure. I don't see how issuing the API command would break things. Wouldn't that mean having `NoSubFolder` set as the default setting in qbittorent also break thing? Just trying to understand, thanks.

**Comment by markus101** [comment]
Yes, it tells qbit to change the setting for that download, which has the potential to break downloads in Sonarr so we don't allow it.

If the user changes it in Qbit to `NoSubfolder` (and they have) then that can also cause issues for Sonarr.
