### ISSUE TITLE
Ability to add shows that aren't on TheTVDB yet

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#699]
When shows are going to be released, but no information is available on TheTVDB (pre-production) it would be nice to be able to maintain a list of them within Sonarr that would periodically search TheTVDB for them and notify the user when its available to be added (which will serve as a sanity check to make sure it is the correct series).

**Comment by tidusjar** [comment]
This is a bit more difficult than you think. Since we could store somewhere e.g. "The Flash 2" but it could actually end up on TheTVDB as "The Flash: 2" which then wouldn't find a match. 
The best way to implement this is to include another 3rd party data provider that means we could possibly have more coverage.

**Comment by Taloth** [comment]
Personally I see this as a 1% feature. I would say if ppl want to add new unlisted shows they should keep track of those elsewhere.
But if such a feature is implemented you still need some kind of source. If we could identify a useful source we might be able to do some tracking in skyhook.

**Comment by T8OO** [comment]
I can't say how much of needed feature this is for everyone else but for myself whenever a new show is announced especially online I can't add it in Sonarr and that happens muliple times a year.
As for the colon and other things could it not search for shows just via key words in the title? Ones that have been created on TheTVDB after the date the show has been added to the list in Sonarr? 
For example it would only search for shows with 'Flash' in the title that appeared on TheTVDB after July 22nd 2015.

**Comment by tidusjar** [comment]
It is possible. You just also have to think about the implementation detail and maintainability. Along with that possible mis-matches and how you will deal with that.

**Comment by T8OO** [comment]
Like markus said the user could be notified when something is found and they choose whether it's added or not. The fact that it only throws up newly added shows could keep the matches fairly low I would have thought. I know very little about the fine details, I'm just spitballing.

**Comment by dlmarston** [comment]
Perhaps a simpler/interim step is to maintain the list somewhere in sonarr, but not perform an automatic search. The end user could then review the list on an adhoc basis.

I'm probably part of the 1% mentioned by Taloth above, however it is something that comes up for me quite often.

(Great app by the way, good work!)

**Comment by danshep** [comment]
If a show is announced but not yet in the tvdb database, you can just add it to the tvdb - that's the joy of a community operated database.

**Comment by enchained** [comment]
@danshep Not sure of how it was back then, but right now, as far as I know, it's against the rules to add a show without specific premiere date to the tvdb. And usually, there is no premiere date at the moment of the announce. 

Just started using sonarr and already found out that some of the series I'd like to add can't be added, and the tvdb policy is the reason why. On the contrary, tvmaze lists shows in different states of production, even with tba- or year-dates. Of course, multiple metadata source support is out of the question cause its complexity, but I have another proposition: allow adding shows to the waiting section. 

It could go like that:

I try to add Cloak & Dagger. No results from the tvdb (or all results wrong). At the bottom of the search there is a proposition to "Search on tvmaze (for shows without premiere date)". Then there's a list of results from their search api:
http://api.tvmaze.com/search/shows?q=cloak%20dagger
Where `show.externals.thetvdb` shows 'null', that result can be chosen to go to the "waiting list". And there should be a schedule (weekly? monthly? at least no more than usually comes between the date announce and the premiere) running through every item on the list, checking (http://api.tvmaze.com/shows/15307) if the tvdb id has been finally added. Then it will auto-add the show from tvdb or prompt for the user reaction.

**Comment by markus101** [comment]
One day, maybe.

**Comment by TwistedFaith84** [comment]
You know the easier way for this to be fixed is too just sign up for thetvdb and that way you can add/edit new/existing shows. Although depending on the show/s you would still have to follow tvdb's guidelines; but I can tell you from my experience that depending on the show it might still get removed from tvdb but if you add it there first and then come to sonar and search for it (with tvdb id number) you can immediately scan it in and do everything with sonar that you can until it gets pulled from tvdb (if it does get pulled) but atleast you'll get an error message on sonar saying that that show was deleted from tvdb.
