### ISSUE TITLE
Ani-cli for downloading anime

### ISSUE THREAD

**Issue by ManuXD32** [Sonarr/Sonarr#6996]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Finding anime sources with good quality and all of the episodes is kinda hard with torrenting.

### Describe the solution you'd like

Ani-cli would solve this problem, is another open sourced resource so it might be not that tricky to implement.

### Describe alternatives you've considered

I've been using ani-cli for downloading anime and not adding anime titles to sonarr to avoid conflicts, it would be nice to make ani-cli the default tool for downloading anime.

**Comment by PearsonFlyer** [comment]
There are no plans to have any direct-download clients in Sonarr. Torrents or usenet are your options.

**Comment by ManuXD32** [comment]
> There are no plans to have any direct-download clients in Sonarr. Torrents or usenet are your options.

Oh okay. Thanks!!
