### ISSUE TITLE
MediaInfo Simple stopped reporting Atmos

### ISSUE THREAD

**Issue by mjc** [Sonarr/Sonarr#6998]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Previously this pattern:
`{MediaInfo Simple}`

Would produce, for example:
`h265 EAC3 Atmos` and `x265 TrueHD Atmos`

But it now produces `h265 EAC3` and `x265 TrueHD` instead.

Here is the relevant output from mediainfo cli for these files:
```
❯ mediainfo Season\ 2/*S02E08*mkv | grep -i dolby            
Commercial name                          : Dolby TrueHD with Dolby Atmos
Title                                    : Dolby TrueHD/Atmos Audio / 7.1 / 48 kHz / 3952 kbps / 24-bit
❯ mediainfo Season\ 1/*S01E08*mkv | grep -i dolby  
Commercial name                          : Dolby Digital Plus with Dolby Atmos
```

### Expected Behavior

I would expect Atmos files to have that in the {MediaInfo Simple} output, or some other way to specify that files contain atmos audio descriptors in them.

### Environment

```markdown
- OS: NixOS 24.05 or windows 
- Sonarr: 4.0.7.1863
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: n/a
- Database: Sqlite 3.45.3
```

### What branch are you running?

Main

### Trace Logs?

I'm not sure how to get a trace of this specific thing, should I trace the file rescanning or the rename?

**Comment by markus101** [comment]
In v4, Sonarr uses ffprobe for "mediainfo" and ATMOS is only included for specific audio codec information. `thd+` for TrueHD and `ec+3` for EAC3 which comes from the primary audio stream's `CodecTagString`.

**Comment by thezoggy** [comment]
sonarr v4 doesnt use mediainfo but uses ffprobe

you prob should hit up sonarr support for help on what your trying to do, and most likely you just want to leverage trash's custom format for audio stuff if your trying to prefer that
https://trash-guides.info/Sonarr/sonarr-collection-of-custom-formats/#truehd-atmos

**Comment by mjc** [comment]
Ah I'm trying to have atmos in the filename after they're organized by sonarr, for further post-processing

**Comment by thezoggy** [comment]
> Ah I'm trying to have atmos in the filename after they're organized by sonarr, for further post-processing

create CF for atmos and add that cf token to be included in your renaming. hit up trash discord if you need help on setting that up

**Comment by markus101** [comment]
I've checked files that contain TrueHD Atmos and DDP5.1 (EAC3) with Atmos and Sonarr correctly includes Atmos in the file name when renaming and in the info shown in the UI. If you're still having issues 
please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr).
