### ISSUE TITLE
qBittorrent seeding time mismatch

### ISSUE THREAD

**Issue by 0a8d234ff1e9b1a5f141** [Sonarr/Sonarr#7000]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

qBittorrent `max_seeding_time` is an integer measured in seconds while the indexer `Seed Time` and `Season-Pack Seed Time` in Sonarr is measured in minutes (based on the GUI label). When querying the qBittorrent WebUI API, the value for `max_seeding_time` is the exact same as `Seed Time` and `Season-Pack Seed Time` in Sonarr.

### Expected Behavior

Either:
A. qBittorrent `max_seeding_time` should be set to 60 times what is set in Sonarr for both `Seed Time` and `Season-Pack Seed Time` if this is only the case for the qBittorrent download client.
B. The GUI label in Sonarr for the time measurement should be changed from `minutes` to `seconds` if this is the case for all download clients.

### Environment

```markdown
- OS: 
- Sonarr: 
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Main

### Trace Logs?

N/A

**Comment by markus101** [comment]
Please fill out all the requested information, including trace logs.

**Comment by markus101** [comment]
Their API docs have` max_seeding_time` in minutes for the global config, but seconds for torrents, but in the UI it shows minutes and I've confirmed that whatever I set in minutes there also comes back in the API (it's not multiplied by 60) and whatever I set in the API via Sonarr is also the same in the UI in qbit. This behaviour is consistent in qbit 4.5.2 and 4.6.5.

If there is further evidence that indicates this has changed in another version please provide all the requested information as well as information on which version of qbit you are using.
