### ISSUE TITLE
PREVIOUS AIRING missing from SERIES report 

### ISSUE THREAD

**Issue by scottc439** [Sonarr/Sonarr#7002]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

 [Previous Airing] DATE/TIME is not being displayed correctly for TV series. Only a small few TV series are displayed - cannot see any pattern why those are displaying vs TV series that are not correctly displaying. [NEXT AIRING] is working correctly. 

### Expected Behavior

 [Previous Airing] should display DATE/TIME after an episode completes and time elapses.

### Steps To Reproduce

Start Sonarr
Goto left menu SERIES
Make sure  [Previous Airing] is selected as a displayable column
Sort on  [Previous Airing] for Ascending or Descending. If TV exist in database and any have recent airings, the  [Previous Airing] should display a DATE/TIME 

### Environment

```markdown
- OS: Windows 11
- Sonarr: 4.0.8.1874
- Docker Install: 
- Using Reverse Proxy: 
- Browser: Chrome
- Database: Sqlite 3.36.0

Version 4.0.8.1874
.NET Yes (6.0.13)
Database Sqlite 3.36.0
Database Migration 211
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/user-attachments/files/16368328/sonarr.trace.txt)

### Anything else?

![sonarr-support-prev_air-20240724](https://github.com/user-attachments/assets/cf095cb4-034e-4f38-afc2-3ee27803661c)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

I see no issues with this, but keep in mind Previous and Next Airing only includes monitored episodes
