### ISSUE TITLE
Media info showing all languages but scoring and detected language show single language

### ISSUE THREAD

**Issue by tws101** [Sonarr/Sonarr#7013]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

![image](https://github.com/user-attachments/assets/157a1e79-dd55-4696-ab02-61612c254d12)

Media info shows 2 audio stream one eng and one jpn...  Yet detected languages say English

***This is not just a display glitch as it applies to the custom format score as you should in the below screenshot see original Language and dual audio 

![image](https://github.com/user-attachments/assets/2e06f029-cab0-4920-af5b-e14e4b99d903)

This problem is intermittent.. here in the same set of shows it is not present
![image](https://github.com/user-attachments/assets/dee681f0-9633-423c-864b-a5ba2978973f)

You can see it shows Multi language and the custom formats are as expected 
![image](https://github.com/user-attachments/assets/74f79c22-307b-4900-8fad-a5b14a644e6e)

The majority of my files in the past would see dual audio and multi language now something has changed and sonarr somehow does not complete see that there is a jpn stream...  the media info says there is one yet all areas of sonarr no longer see that stream 

Output from an ffmpeg probe on the file in question appears good... pasted below 

(This is just the stream sonarr does not see)

```
2:{
"index":2
"codec_name":"ac3"
"codec_long_name":"ATSC A/52A (AC-3)"
"codec_type":"audio"
"codec_tag_string":"[0][0][0][0]"
"codec_tag":"0x0000"
"sample_fmt":"fltp"
"sample_rate":"48000"
"channels":2
"channel_layout":"stereo"
"bits_per_sample":0
"initial_padding":0
"r_frame_rate":"0/0"
"avg_frame_rate":"0/0"
"time_base":"1/1000"
"start_pts":0
"start_time":"0.000000"
"bit_rate":"192000"
"disposition":{
"default":0
"dub":0
"original":0
"comment":0
"lyrics":0
"karaoke":0
"forced":0
"hearing_impaired":0
"visual_impaired":0
"clean_effects":0
"attached_pic":0
"timed_thumbnails":0
"captions":0
"descriptions":0
"metadata":0
"dependent":0
"still_image":0
}
"tags":{
"language":"jpn"
"title":""
"BPS":"182156"
"NUMBER_OF_FRAMES":"71055"
"NUMBER_OF_BYTES":"32357828"
"_STATISTICS_WRITING_APP":"mkvmerge v73.0.0 ('25 or 6 to 4') 64-bit"
"_STATISTICS_WRITING_DATE_UTC":"2023-01-16 16:43:59"
"_STATISTICS_TAGS":"BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
"ENCODER":"Lavc59.37.100 ac3"
"DURATION":"00:23:41.120000000"
```

### Expected Behavior

If a file has multiple audio streams with properly defined language tags sonarr should in ALL cases see the file as having multi audio stream and apply correct custom formatting ...   This is not the current case

### Steps To Reproduce

***UPDATE***
After a rescan of the media all files are now showing bugged 
*****

Unknown not all files present have the error
90% are affected but a few are not.... I have been combing through the files trying to find a difference in the XML output 

Broken (Full file XML)
[data.txt](https://github.com/user-attachments/files/16395321/data.txt)

Working (Full file XML)
[data (1).txt](https://github.com/user-attachments/files/16395332/data.1.txt)

I dont see why one of these sonarr would not see the second language and apply custom formats and the correct score and not the other....

Custom format being used that is failing due to sonarr not seeing the second language 

```
{
  "name": "Dual Audio (Eng Jpn)",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "English",
      "implementation": "LanguageSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": 1
      }
    },
    {
      "name": "Japanese",
      "implementation": "LanguageSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": 8
      }
    }
  ]
}
```

### Environment

```markdown
- OS: TrueNAS Scale / jailmaker / Debian
- Sonarr: 4.0.8.1874-ls248 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser:  Chrome
- Database: Sqlite 3.45.3    migration 211
```

### What branch are you running?

Main

### Trace Logs?

....  if a log file is needed please advise I have found no log error sonarr is just missing the additional audio stream....

**Comment by markus101** [comment]
For the file with the missing language you've highlighted here, since Sonarr is only showing English I suspect that the file was imported before Sonarr had support for multiple languages (v2/v3/v4 beta), since that migration didn't add additional languages from media info.

When was that file imported?

**Comment by tws101** [comment]
> How about not making them required?
> 
> ```json
> {
>   "name": "Dual Audio (Eng Jpn)",
>   "includeCustomFormatWhenRenaming": false,
>   "specifications": [
>     {
>       "name": "English",
>       "implementation": "LanguageSpecification",
>       "negate": false,
>       "required": false,
>       "fields": {
>         "value": 1
>       }
>     },
>     {
>       "name": "Japanese",
>       "implementation": "LanguageSpecification",
>       "negate": false,
>       "required": false,
>       "fields": {
>         "value": 8
>       }
>     }
>   ]
> }
> ```


I have tested with just putting the format as find Japanese ONLY...   NOT required then again as required  both attempts do not see the JPN stream.....   

This is invisible to sonarr

```
{
  "name": "Japanese",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Japanese",
      "implementation": "LanguageSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 8
      }
    }
  ]
}
```



*****UPDATE*****
Now that sonarr completed a rescan of the files ALL files are now bugged NOT even some are showing correct.... 
Updating original request to say it is no longer intermittent

**Comment by tws101** [comment]
> For the file with the missing language you've highlighted here, since Sonarr is only showing English I suspect that the file was imported before Sonarr had support for multiple languages (v2/v3/v4 beta), since that migration didn't add additional languages from media info.
> 
> When was that file imported?

Orignial
![image](https://github.com/user-attachments/assets/9e1fbaeb-d70a-4df3-87ff-b251a89685cb)


But the file was since re-encoded the streams changed how do I make sonarr assume it is a new file and reimport/rescan ?

**Comment by tws101** [comment]
Also It is interesting that in the 4K sonarr install I am also seeing different issues


Says audio jpn and only jpn and that is correct yet the left side says English....    AND custom formatting also says English
![image](https://github.com/user-attachments/assets/26f765b6-735b-439a-9c05-5618e7b33ba8)
![image](https://github.com/user-attachments/assets/56dcc66f-5606-42d4-afab-b46f964d74a7)

its not English

Formatting that is triggering

```
{
  "name": "English Audio",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "English",
      "implementation": "LanguageSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": 1
      }
    }
  ]
}
```

**Comment by tws101** [comment]
Also I did do an update to this version this week ....    was working just prior...  

lscr.io/linuxserver/sonarr:4.0.8.1874-ls248

from 

lscr.io/linuxserver/sonarr:4.0.5.1710-ls242

**Comment by markus101** [comment]
Custom Formats does not use any Media Info / ffprobe information directly, it relies on the Languages that are extracted and stored in the DB. For CFs that use language the only thing that really matters is what was extracted when the file was imported. Which for files imported before v4 would only be what was in the release name unless updated after the fact.

If there are languages missing or wrong for files imported before v4 then you'll probably want to update them in the UI or via the API. Alternatively if the file name or size changes Sonarr will reprocess them automatically, assuming `Analyse Media Files` is enabled it'll grab updated "media info".

This behaviour has not changed recently and I'm not seeing anything here that is unexpected from how Sonarr actually functions, just some issues from assumptions in previous versions.

**Comment by tws101** [comment]
> Custom Formats does not use any Media Info / ffprobe information directly, it relies on the Languages that are extracted and stored in the DB. For CFs that use language the only thing that really matters is what was extracted when the file was imported. Which for files imported before v4 would only be what was in the release name unless updated after the fact.
> 
> If there are languages missing or wrong for files imported before v4 then you'll probably want to update them in the UI or via the API. Alternatively if the file name or size changes Sonarr will reprocess them automatically, assuming `Analyse Media Files` is enabled it'll grab updated "media info".
> 
> This behaviour has not changed recently and I'm not seeing anything here that is unexpected from how Sonarr actually functions, just some issues from assumptions in previous versions.

Okay why would they have been correct yet changed after I did a scan???

So I used the UI and just imported them again and manually change the language and that works....  but I cant do that manually for the whole DB....

Also The Media info Analyze in enabled and it is in fact updating correctly but how do I get the rest of the UI and the custom formatting to check the media info and correct itself ?

How are the languages determined initially and stored in the DB?  Can I make sonarr rescan all files and update the DB based on the media info?

**Comment by markus101** [comment]
> Okay why would they have been correct yet changed after I did a scan???

Not sure what you did when you say "I did a scan", refreshing a series won't change anything if the files haven't changed (and by default Sonarr rescans files periodically). Custom Formats are processed when returning items from the UI, so any changes you make to CFs are reflected automatically.

> Also The Media info Analyze in enabled and it is in fact updating correctly but how do I get the rest of the UI and the custom formatting to check the media info and correct itself ?

The first file you showed hasn't been changed recently, unless there is history for it you're not showing.

> How are the languages determined initially and stored in the DB?

They're now extracted by information in the file name and audio tracks in the files.

> Can I make sonarr rescan all files and update the DB based on the media info?

No, Sonarr only reprocesses existing files that aren't linked to an episode or the file changes.

**Comment by tws101** [comment]
> > Okay why would they have been correct yet changed after I did a scan???
> 
> Not sure what you did when you say "I did a scan", refreshing a series won't change anything if the files haven't changed (and by default Sonarr rescans files periodically). Custom Formats are processed when returning items from the UI, so any changes you make to CFs are reflected automatically.
> 
> > Also The Media info Analyze in enabled and it is in fact updating correctly but how do I get the rest of the UI and the custom formatting to check the media info and correct itself ?
> 
> The first file you showed hasn't been changed recently, unless there is history for it you're not showing.
> 
> > How are the languages determined initially and stored in the DB?
> 
> They're now extracted by information in the file name and audio tracks in the files.
> 
> > Can I make sonarr rescan all files and update the DB based on the media info?
> 
> No, Sonarr only reprocesses existing files that aren't linked to an episode or the file changes.

Two days ago the file was reprocessed and renamed...

history

![image](https://github.com/user-attachments/assets/16973304-6ddc-4b34-8816-2511fc1c2777)

after the transcoding and renaming the information that was correct changed back to what sonarr must have read years ago... why it reverted I do not know but it happened to everything....    The files was converted in tdarr, renamed in sonarr after a series refresh/notify then today when I was updating custom formats the old and correct formatting just started disappearing from all files....  the only other things that change was I updated sonarr....

latest history but the custom formatting was different than in this screen shot as I posted the results of this file above 

seems like me updating my custom formatting made what was right in the UI revert to the old DB info



So I did refresh the series and the file had changed....  and the data displayed decided to go back to an old version.....

**Comment by tws101** [comment]
> > Can I make sonarr rescan all files and update the DB based on the media info?
> 
> No, Sonarr only reprocesses existing files that aren't linked to an episode or the file changes.

So the file did change....  if that is the case it should have been scanned and the media info updated and the db updated based on the scan.....

This did not happen, it reverted to old DB info

**Comment by markus101** [comment]
I've verified that Sonarr correctly updates the extracted media info and languages when changing the file name and replacing the file with a different file with the same name. If there was a bug it is no longer present.
