### ISSUE TITLE
Manual Import on Mobile Too Long with Some Translations

### ISSUE THREAD

**Issue by jokerigno** [Sonarr/Sonarr#7015]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I can’t see import button in manual import windows.

### Expected Behavior

Able to see the button also on mobile browser 

### Environment

```markdown
- OS: unraid
- Sonarr:     4.0.8.1874
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Safari
- Database:     Sqlite 3.45.3
```

### What branch are you running?

Main

### Trace Logs?

Will add shortly

### Anything else?

![IMG_7304](https://github.com/user-attachments/assets/f09c3c37-6e26-412a-a1a5-f284ef5f37df)

**Comment by stevietv** [comment]
There are no issues with manual import in safari mobile browser.
The rings show that the directory is loading, perhaps you have way to many files in that folder that sonarr is taking a long time to parse it?

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by jokerigno** [comment]
I made the screenshot before finishing loading. @stevietv if I post another screenshot when loading if finished and I show you that the issue exist do you will reopen it?

**Comment by jokerigno** [comment]
![image](https://github.com/user-attachments/assets/a4e9717e-cb4a-472c-b3e2-a96a2e369ea1)

1st screen from my iPhone 12 mini

**Comment by jokerigno** [comment]
![image](https://github.com/user-attachments/assets/02762891-2463-4709-af92-46c4ad03998b)

Second screen fro my wife's iPhone 14

**Comment by jokerigno** [comment]
As you can see the issue is in both photo and not related do display screen

**Comment by stevietv** [comment]
no issue for me here in english, I see that the translation length in the first is causing the issue.

this should be fixed to a fixed width
