### ISSUE TITLE
Group import and delete notifications to 1 single notification on Discord

### ISSUE THREAD

**Issue by kristianvld** [Sonarr/Sonarr#7017]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently when a season pack is grabbed only a unique Discord notification is sent.

However when this season pack is imported, a new notification for every episode in the season pack is sent, spamming Discord with multiple notifications per second.

This is even worse when it is an upgrade, as currently when deleting one or more episodes, a unique notification is sent per episode that is deleted. So when upgrading a season pack, two different notifications are sent per episode in rapid succession, spamming both Discord and any notifications or phones listening for those notifications.

### Describe the solution you'd like

It would be nice if both import and delete notifications could be grouped similar to how import notifications currently are grouped.

### Describe alternatives you've considered

N/A

### Anything else?

Looking at related issue, the most relevant is #363 however this one seems to mainly focus on the grabbing of torrents, which has been implemented and in my opinion works great.

Issue #4273 also mentions something similar. This issue is still open, though when they say "download" I would assume this means grabbing the torrent, which has already been implemented, however if they by "download" mean "import" after downloading. However this issue mentions nothing about deleting episodes.

Issue #1585 seems similar to #4273, however this issue was at the time closed due to being a dupe of #363 before #363 was closed.

There is a vague relation to #1396, but this one mainly focusing on rate limits when using PushBullet.

**Comment by augustuen** [comment]
Doesn't #6937 solve it?

**Comment by markus101** [comment]
File level events are triggered once per file, On Import complete is triggered when the full release is imported (and not sent if that doesn't happen). No plans to group file events together.

**Comment by plexecutor** [comment]
This is fucking retarded. Why are you not fixing this?
