### ISSUE TITLE
Make forced authentication optional

### ISSUE THREAD

**Issue by mikea** [Sonarr/Sonarr#7024]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

As many in the tracker I am frustrated by the decision to include forced authentication. I read the wiki and I know the option to disable auth on local network. I still have to configure authentication and local network detection doesn't work for my case.

### Describe the solution you'd like

"None" option should be perfectly accessible for authentication.

### Describe alternatives you've considered

I will be stuck with v3 for now.

**Comment by mikea** [comment]
As of now it does not let me to disable authentication

**Comment by CLHatch** [comment]
If you actually read the wiki you would know that it already is optional.  You need to manually edit the config file to turn it off.  They did that so someone doesn't accidentally do it.  That said, if you do turn it off, you better have some other sort of authentication set up, or you're setting yourself up to get hacked.

**Comment by stevietv** [comment]
There is a method to disable it via the config, as described on our wiki. https://wiki.servarr.com/sonarr/faq-v4#forced-authentication.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by mikea** [comment]
I would still like to be able to disable authentication via UI. _so many_ people have asked for it. What's wrong with that? Why do I have to mess with XML? 

Why you need to send people to FAQ every time they request it. It was totally fine to use sonarr without authentication. This forced decision is very inconvenient.

**Comment by mikea** [comment]
I would also like the tool not to patronize me. I am perfectly capable to make this kind of decision myself.

**Comment by CLHatch** [comment]
> I would still like to be able to disable authentication via UI. _so many_ people have asked for it. What's wrong with that? Why do I have to mess with XML?
> 
> Why you need to send people to FAQ every time they request it. It was totally fine to use sonarr without authentication. This forced decision is very inconvenient.

You were fine with it.  How about the trackers that everyone had access to because idiots left their systems wide open without authentication.  There's literally a website that tracks people open radarr and sonarr instances, you know.

**Comment by CLHatch** [comment]
> I would also like the tool nor community not to patronize me. I am perfectly capable to make this kind of decision if to enable authentication and which one myself.

Your lack of care for security DOES affect other people.

**Comment by mikea** [comment]
> There is a method to disable it via the config, as described on our wiki. https://wiki.servarr.com/sonarr/faq-v4#forced-authentication.

The official instructions do not work. My config before starting sonarr:

```
<Config>
  <LogLevel>Info</LogLevel>
  <Port>8989</Port>
  <UrlBase></UrlBase>
  <BindAddress>*****</BindAddress>
  <SslPort>9898</SslPort>
  <EnableSsl>False</EnableSsl>
  <ApiKey>*****</ApiKey>
  <AuthenticationMethod>None</AuthenticationMethod>
  <AuthenticationType>Enabled</AuthenticationType>
  <Branch>main</Branch>
  <LaunchBrowser>True</LaunchBrowser>
  <UpdateMechanism>Docker</UpdateMechanism>
  <InstanceName>Sonarr</InstanceName>
  <AuthenticationRequired>Enabled</AuthenticationRequired>
  <SslCertPath></SslCertPath>
  <SslCertPassword></SslCertPassword>
</Config>
```

I have added `  <AuthenticationType>Enabled</AuthenticationType>` as FAQ suggested, and I am still presented with forced authentication

**Comment by mikea** [comment]
```
  <AuthenticationMethod>None</AuthenticationMethod>
  <AuthenticationType>DisabledForLocalAddresses</AuthenticationType>
```

doesn't work either. @CLHatch @stevietv sorry wiki instructions do not work. It is _not possible_ to run sonarr without authentication anymore.

Very sad. Someone needs a fork.

**Comment by CLHatch** [comment]
> ```
>   <AuthenticationMethod>None</AuthenticationMethod>
>   <AuthenticationType>DisabledForLocalAddresses</AuthenticationType>
> ```
> 
> doesn't work either. @CLHatch @stevietv sorry wiki instructions do not work. It is _not possible_ to run sonarr without authentication anymore.
> 
> Very sad. Someone needs a fork.

Interesting.  I'll need to tell my Sonarr and Radarr systems to stop working then.  Because obviously they shouldn't be working with their authentication disabled like I have it set up (I use external authentication, or I would never have disabled the built-in authentication).

**Comment by stevietv** [comment]
please read the FAQ again. It tells you to set AuthenticationMethod to External

**Comment by mikea** [comment]
If someone will take a look here: all it takes is a tiny patch to get you running again : https://github.com/Sonarr/Sonarr/pull/7025

**Comment by CLHatch** [comment]
> If someone will take a look here: all it takes is a tiny patch to get you running again : #7025

Or you could actually read the wiki link instead of skimming over it and edit the config file correctly.  Or, as you were told to do, go the the correct place for support issues (it's not a bug, it is working as it's supposed to).

**Comment by mikea** [comment]
> please read the FAQ again. It tells you to set AuthenticationMethod to External

Thanks, this actually works! Unfortunately faq isn't clear this is what is needed when you need to disable auth completely.
In fact next paragraph gets everything more complicated.

Thanks for help, but I would still like the issue open: UI needs to accept "None"

**Comment by mikea** [comment]
>  Or, as you were told to do, go to the correct place for support issues (it's not a bug, it is working as it's supposed to).

this is feature request. Issue tracker is perfectly reasonable place for them, no?

**Comment by CLHatch** [comment]
> > Or, as you were told to do, go to the correct place for support issues (it's not a bug, it is working as it's supposed to).
> 
> this is feature request. Issue tracker is perfectly reasonable place for them, no?

They were pretty much forced to put the feature of forcing authentication so Sonarr and Radarr didn't get blocked by trackers because of people leaving their systems wide open like idiots.

**Comment by stevietv** [comment]
We will not allow auth to be disabled by UI.
We enabled this round about way via the config to ensure that users don't turn it off without considering the consequences. There were too many open, unprotected Sonarr instances out there exposing API key to clients and indexer, which as you would understand indexers would not be happy about.

It stays like this from now on to keep Sonarr able to use indexers.
Wiki updates are welcome for better wording if you think it needs it.

**Comment by zakkarry** [comment]
I think the wiki is pretty clear under methods what is supported, it doesn't have the word `None` anywhere on the link's entire page.

**Comment by CLHatch** [comment]
> I think the wiki is pretty clear under methods what is supported, it doesn't have the word `None` anywhere on the link's entire page.

Yeah. Reason I didn't just tell him how to do it. If he can't even read simple instructions, it didn't seem likely he was knowledgeable enough to be messing with it.
