### ISSUE TITLE
Show Transmission torrents without metadata in list of activities

### ISSUE THREAD

**Issue by scheduld** [Sonarr/Sonarr#7029]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

If we add a movie from torrent using a magnet link, with Transmission as a client, the movie item is not added to the list of activities in Sonarr/Radarr until Transmission retrieves the metadata about the torrent.

While this works for most of the torrents, it can happen for transmission to not be able to retrieve the metadata for a long time (or never) for some torrents (trackers lying about number of seeders, etc). In such case, there's no way to cancel this activity from Sonarr/Radarr and we must manually remove it from the transmission's UI. Also, the release/torrent cannot be added to the blocklist in Sonarr/Radarr so it won't try to download it again.

(Note: the on grab event is triggered even before retrieving the metadata)

### Describe the solution you'd like

The grabbed torrents should appear in the activities list in Sonarr/Radarr even if the torrent's metadata is still not retrieved.

### Describe alternatives you've considered

Manually removing the torrents from Transmission UI.

### Anything else?

This is probably related to this check here, but i don't know if removing it is enough.

https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs#L46-L50

**Comment by scheduld** [comment]
Yeah, i just added the on grab event as side note. it is alright

**Comment by markus101** [comment]
This is where it was added: https://github.com/Sonarr/Sonarr/pull/1032

Not sure if we've improved things in `OsPath` to avoid reintroducing that issue or it will need additional changes there.
