### ISSUE TITLE
Configurable items per page on activity queue screen

### ISSUE THREAD

**Issue by PearsonFlyer** [Sonarr/Sonarr#7035]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Items per page is locked at 20 in Sonarr's activity queue, but is adjustable in Radarr's activity queue.

### Describe the solution you'd like

Moving this option over from radarr: 
![image](https://github.com/user-attachments/assets/4e891a8f-a574-4930-8b66-03057c02d6b1)

### Describe alternatives you've considered

None

### Anything else?

This option exists in radarr for all 3 activity menu items (queue, history, and blocklist).

**Comment by markus101** [comment]
This is a regression from the TypeScript conversion, we've definitely had page size for those previously.
