### ISSUE TITLE
Feature Request: Optional NLog Structured Logging

### ISSUE THREAD

**Issue by kylelaverty** [Sonarr/Sonarr#7045]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Many modern logging frameworks such as [Seq](https://datalust.co/seq) and logging wrappers like [Dozzle](https://dozzle.dev/) support both standard text-based logs as well as structured JSON logs. These structured logs allow for better filtering and sorting than is usually offered by traditional text-based logs.

Currently, the logs that come out of Sonarr, and by extension, the *Arr suite that are based on it, can be hard to review and diagnose issues in. 

### Describe the solution you'd like

Ideally, this would be a configuration read into the application via IConfiguration. The default could continue to be text but a new json option would be added.

Something like SONARR_LOGGING_FORMAT=TEXT/JSON

This would allow people using containers to add the environment variable to their setup. For the initial release, it would not need to be in the UI since this is a highly technical setting.

From doing research it looks like this could be accomplished by a switch statement swapping out the default console layout for a JsonLayout, defined [here](https://github.com/NLog/NLog/wiki/JsonLayout). I have done this in the past using a method like:

```csharp
private static JsonLayout CreateJsonLayout()
{
    var layout = new JsonLayout
    {
        IncludeAllProperties = true,
        Attributes =
        {
            new JsonAttribute("date", "${longdate}"),
            new JsonAttribute("level", "${level:upperCase=true}"),
            new JsonAttribute("logger", "${logger}"),
            new JsonAttribute("message", "${message}"),
            new JsonAttribute("exception", "${onexception:${exception:format=ToString}}"),
        },
    };

    return layout;
}
```

### Describe alternatives you've considered

Log scrappers could be used to ingest the logs, reformat them and then spit them back out in a structured format. However, these scrappers are prone to issues when new message formats appear.

### Anything else?

I did see an existing issue that seemed to be about a similar thing: #6890 but it was focused on the multiline nature of the logs and the response before it was closed noted that was how the logs looked. My recommendation is related to better logging practices overall. While changes could be made to each log call to add better context and details (parameterizing the calls), simply reformatting the output is a good first step.

**Comment by markus101** [comment]
While JSON log files are useful for tools, they are not be useful for human review, which is necessary for bug reports and support requests and we're not going to review logs from screenshots from tools or JSON logs.

If we added JSON logging as a separate output then at best you're logging to file twice and then parsing that into your tool of choice. A solution would be to use syslog for logging, which is already supported or potentially a UDP option, but then you'd need to deal with consuming those in some way.

Seems to me that structured log files is a way to solve the problem, but probably not the best way to do it.

**Comment by kylelaverty** [comment]
Since it would be a configurable thing, could someone not switch it back to `TEXT` if they were having an issue? One of the steps for noting an issue is turning logging up a level and reproducing it. Which needs people to change the logging configuration anyway. It seems that it would not be that bad and since `JSON` wouldn't be something the average user would need unless they had a medium or high-complexity (multiple instances/several containers/etc.) layout and were trying to aggregate logs anyway it should also limit any issues.

If you still wanted the ability to easily look at them, CLEF could be implemented instead ([details](https://github.com/paulem/nlog-layouts-clef)) and it can be uploaded to a Seq instance for sorting/filtering or other analysis. 

At the end of the day, I am not involved in any debugging of this project I can't say for sure what would work for you. The log's current state just makes it more difficult to deal with long logs, multi-line logs or interconnected logs in a distributed environment like containers where a tool like Seq or Dozzle is being used to aggregate the logs.

I appreciate your feedback on this.

**Comment by Thirrian** [comment]
My $0.02 is that log scrapers are easy to implement if you have them ignore any line that doesn't start with a timestamp.
Lines that don't are stack traces, but you do get the initial error in the tool that consumes the log files.

Given the amount of support requests that ignore the instructions to provide debug logs, I don't see the additional instruction to change the output format of the logs and reproduce the issue go particularly well.

**Comment by markus101** [comment]
Seems like the team is OK with this being a console logging option, you'll want to use an environment variable to configure it, otherwise there will be some early logging (before the config file is read) that will be in the wrong format.
