### ISSUE TITLE
Remove specials from table view episode count

### ISSUE THREAD

**Issue by sanderaido** [Sonarr/Sonarr#7046]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

In the Series table view, `Episode count` column sums all episodes and specials of the show, whether they are monitored or not, while the `Episodes` progress bar shows only monitored episodes. 

For example Rick & Morty currently has 7 seasons with 71 episodes, but the total Episode count is 184 since it apparently has 113 specials. I don't have the specials even monitored or downloaded. I want to use the episode count column to assess whether the show has any upcoming seasons/episodes or if I have any unmonitored seasons hiding.

### Describe the solution you'd like

There could be an option to show only total show episodes, discarding specials. Maybe rename the column to `Total episode count` and add a new one with only `Episode count`. Or maybe show the number in the current column as `71 + 113` (episodes + specials)

### Describe alternatives you've considered

N/A

**Comment by PearsonFlyer** [comment]
That is not correct.
![image](https://github.com/user-attachments/assets/b01aa735-aa40-4cb7-9237-ced7f6d3f0cf)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by sanderaido** [comment]
> That is not correct. ![image](https://private-user-images.githubusercontent.com/15488393/354013059-b01aa735-aa40-4cb7-9237-ced7f6d3f0cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NjYzMzUsIm5iZiI6MTcyMjQ2NjAzNSwicGF0aCI6Ii8xNTQ4ODM5My8zNTQwMTMwNTktYjAxYWE3MzUtYWE0MC00Y2I3LTkyMzctY2VkN2Y2ZDNmMGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIyNDcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmOTNhYzYyZDYzNzBjZmRmNzdjOTdiYmE3N2RkOTE2YWE5ZGRmNDcxOWU1ZTg0NWFkYTIzOTRjNTU4MjNkMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VMf3F34Y6N1CAztUQ3a5QDcJhmUVexINctQ6VwH3JsA)

But you didn't use the "Episode count" column. I see you have the "Season" column and "Episodes" column, not the "Episode count" column
<img width="773" alt="image" src="https://github.com/user-attachments/assets/a134c1ff-b9d1-4a52-a400-bbce0abb6e92">

**Comment by markus101** [comment]
>  if I have any unmonitored seasons hiding.

Use a filter (Seasons Monitored), to do this, we don't have plans to add another column or split this information within the same column.

**Comment by sanderaido** [comment]
That only solves a small subset of the problem. If I have unmonitored some older seasons on purpose but they still exist, the Episode bar stays correct but it's still impossible to find any mismatch at a glance between actual released/announced episode count and actual episode count on disk. 

But thanks for the info about this not being in plans, good to know at least
