### ISSUE TITLE
Perform read-write check for move imports prior to initiating move imports, or don't delete successful copy

### ISSUE THREAD

**Issue by edrock200** [Sonarr/Sonarr#7053]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

If you have a read only source directory to import media from, and you manually import from said directory, Sonarr/Radarr will perform the following sequence of actions:
1. Delete existing episode from library if it exists
2. Copy new version of the episode from source to destination
3. Attempt to delete the source, which fails, then sonarr deletes the destination copy it just copied over as well

### Describe the solution you'd like

Either 1. *arr's perform rw check on source dir prior to starting, and fail if rw isn't possible or 2. If after the file is copied, and it cannot delete the source file, leave the copied file in place.

### Describe alternatives you've considered

Being cognizant of not selecting "Move" when importing from read-only sources, but as *arr's remember the last selection, and some imports are moves from read-write sources, this is an easy mistake to make.

### Anything else?

Steps to reproduce:
1. Create read-only source with an episode file in it.
2. Have a version of same episode already in sonarr library
3. Perform a manual import from source dir, set it to "Move" and import
4. Note that both the existing episode and the newly copied one are deleted at the destination when the move fails.

**Comment by edrock200** [comment]
@markus101 because I believed it was working as is intended, unless you are saying it's supposed to restore the file it deleted that it's replacing?

**Comment by markus101** [comment]
No, it is not supposed to restore the file it deleted.

**Comment by edrock200** [comment]
> No, it is not supposed to restore the file it deleted.

So am I incorrect that this would be a feature request vs a bug?

**Comment by markus101** [comment]
As a feature request, we're not going to test whether the source of an import is read-only as it can incorrectly fail and would cause other issues. If you're importing from a read-only file system expect errors trying to move files.

As a bug I'm interested in why we're copying a file then failing later (presumably deleting the file). We'll reopen if adequate information can be pulled from the logs.

**Comment by edrock200** [comment]
> As a feature request, we're not going to test whether the source of an import is read-only as it can incorrectly fail and would cause other issues. If you're importing from a read-only file system expect errors trying to move files.
> 
> As a bug I'm interested in why we're copying a file then failing later (presumably deleting the file). We'll reopen if adequate information can be pulled from the logs.

I see what you mean. I think it's because in a move the delete doesn't happen until the data is copied. Thanks for explaining. Makes sense.
