### ISSUE TITLE
releases rejected due size error after last update

### ISSUE THREAD

**Issue by kibble1** [Sonarr/Sonarr#706]
after the last update (2.0.0.3357) releases are being rejected.
eg: My Quality Def for SDTV = 125MB to 1GB & 251MB to 2GB
an SDTV Release was rejected stating "369.7MB is larger than the max allowed 33.3MB

![issue1](https://cloud.githubusercontent.com/assets/13425185/8814235/06ebcec8-2fbf-11e5-9488-dd853d2b9fd4.png)
![issue3](https://cloud.githubusercontent.com/assets/13425185/8814236/06ed7782-2fbf-11e5-82a4-4832df97721f.png)
![issue2](https://cloud.githubusercontent.com/assets/13425185/8814237/06edb97c-2fbf-11e5-9688-bb23aa7da943.png)

**Comment by markus101** [comment]
Please use our forums for support.

Size is based off the run time, this series has a runtime of 1 minute and will need to be fixed on TheTVDB (you can create an account and fix it).
