### ISSUE TITLE
Search for missing episodes on timer

### ISSUE THREAD

**Issue by jorgecardoso220** [Sonarr/Sonarr#7064]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I don´t know why but the RSS Feed never finds the episodes for the TV Shows i want, even if they are recent.

### Describe the solution you'd like

Everyday, on a programmable hour, Sonarr performs a search to all the episodes in the Wanted Section.

### Describe alternatives you've considered

At this point i have no alternetive other than manually searching for episodes every day.

**Comment by thezoggy** [comment]
just think of how horrible this would be for indexers..   
you should ideally look at why rss isnt working with your setup compared to it working for everyone else..  join sonarr discord for more help on the matter.

and finally, there are already 3rd party scripts to do what your asking

**Comment by augustuen** [comment]
This will never happen. Searching for episodes would be a ton of API hits to indexers which would highly increase the risk of Sonarr getting banned from those indexers.

If releases aren't being picked up from your RSS feeds, that's a support issue. I suggest you join us over in the Sonarr discord (most popular) , or the Sonarr forum if you prefer that format.

**Comment by bakerboy448** [comment]
Upgradinatorr does this in a more sane manner

https://wiki.servarr.com/useful-tools#drazzilbs-userscripts

https://wiki.servarr.com/useful-tools#just-a-bunch-of-starr-scripts

**Comment by markus101** [comment]
We do not have plans for periodic searches at this time. Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support related to RSS not finding releases.
