### ISSUE TITLE
Ability to redownload poster

### ISSUE THREAD

**Issue by Makhuta** [Sonarr/Sonarr#7067]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When the series receives poster (or  any other image like fanart etc.) after it was added Sonarr doesn't update them to the new one.

### Describe the solution you'd like

I understand that it could be hard or maybe even impossible to do the image updates automatically so just the button or some option to redownload images (deleting the old ones and download them again) would be nice.

### Describe alternatives you've considered

Currently the only way to change the poster/images is to physically delete the old file (poster.png or else) and press **Refresh and Scan** this will download the missing images, but when you want to do it for multiple items it can be quite tedious.

**Comment by markus101** [comment]
Sonarr already downloads images if the file size of the file on disk is different from the size reported by TheTVDB if two images have exactly the same number of bytes that could cause it to not fetch the updated image, though that should be rare.

We do not have plans to add a button to forcibly redownload images at this time.

If you have an example series where an updated image isn't downloading and can provide trace logs and the file on disk we can look and see why it didn't update.
