### ISSUE TITLE
Images Stop Loading, need to clear cache to force login page to appear

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#707]
It appears that the authentication cookie is expiring, but Sonarr is not prompting the user to login again until they clear the cache. This is even happening after reloading the page or force reloading it. It may be limited to Firefox (I haven't seen this behaviour in Chrome).

Ideally it would be nice to extend the authentication cookie when the page is actively being used, we could increase the time that "Remember me" remembers the user for as well.

**Comment by Morten242** [comment]
I have noticed being suddenly logged out in chrome, but the login page still loads.

**Comment by markus101** [comment]
In v3 the forms auth cookie will be refreshed to address this.
