### ISSUE TITLE
Sonarr unable to parse specific TV series

### ISSUE THREAD

**Issue by ShawnHardwick** [Sonarr/Sonarr#7070]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Wanted to see if anyone else is familiar with this issue or if its user error. I've checked Github for similar issues to no avail. 

I use the `api/v3/parse` endpoint in Sonarr to retrieve the original language of series based on filename syntax `{Series Title} - S{season:00}E{episode:00} - {Episode Title}`. So far this has worked wonderfully except for one particular series, https://thetvdb.com/series/ef. It shows up as Ef – a Tale of ... in Sonarr and names the files as Ef – a Tale of . - S02E12 - Forever. 

![image](https://github.com/user-attachments/assets/719d75a9-5f55-474a-a35f-cb60a30896e7)

The odd part is that I can't figure out what title parameter to pass into parse API endpoint for it to return the correct series information. If I follow my normal convention, this would be a command like this:
`curl "http://192.168.1.3:8989/api/v3/parse?apikey=REDACTED&title=Ef – a Tale of ... - S01E01"`
(URI encoding here does not help)

I thought this might be related to the ending periods which are regex'ed out by the title parsing as shown below in the API response:
```
  "parsedEpisodeInfo": {
    "releaseTitle": "Ef – a Tale of ... - S01E01",
    "seriesTitle": "Ef – a Tale of",
    "seriesTitleInfo": {
      "title": "Ef – a Tale of",
      "titleWithoutYear": "Ef – a Tale of",
      "year": 0
    },
```
However, I've not run into this issue with other titles that end in periods.

Also tried using the "Test Parsing" function in the Sonarr UI:
![image](https://github.com/user-attachments/assets/cea6e707-fa4d-4e5e-a424-68dd315a15ca)

Values that I've tried
- `ef`
- `ef - a tale of`
- `ef - a tale of .`
- `ef - a tale of ...`

### Expected Behavior

TV series information returned.

### Steps To Reproduce

- Add `ef - a Tale of...` TV series to Sonarr library
- Use Sonarr 'test parsing' function to retrieve series information

### Environment

```markdown
- Sonarr: 4.0.8.1874
```

### What branch are you running?

Main

### Trace Logs?

2024-08-05 17:23:56.9|Trace|Http|Req: 1358796 [GET] /api/v3/parse?apikey=(removed)&title=ef%20a%20tale%20of%20-%20S01E01 (from 192.168.1.4 Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.22621.3880)
2024-08-05 17:23:56.9|Debug|Parser|Parsing string 'ef a tale of - S01E01'
2024-08-05 17:23:56.9|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)(?:[-_. ]|$)
2024-08-05 17:23:56.9|Debug|Parser|Episode Parsed. ef a tale of - S01E01 
2024-08-05 17:23:56.9|Debug|Parser|Languages parsed: Unknown
2024-08-05 17:23:56.9|Debug|QualityParser|Trying to parse quality for 'ef a tale of - S01E01'
2024-08-05 17:23:56.9|Debug|Parser|Quality parsed: Unknown v1
2024-08-05 17:23:56.9|Debug|Parser|Release Group parsed: 
2024-08-05 17:23:56.9|Debug|ParsingService|No matching series ef a tale of
2024-08-05 17:23:56.9|Debug|AggregateLanguages|Unable to aggregate languages, using parsed values: Unknown
2024-08-05 17:23:56.9|Trace|Http|Res: 1358796 [GET] /api/v3/parse?apikey=(removed)&title=ef%20a%20tale%20of%20-%20S01E01: 200.OK (16 ms)
2024-08-05 17:23:56.9|Debug|Api|[GET] /api/v3/parse?apikey=(removed)&title=ef%20a%20tale%20of%20-%20S01E01: 200.OK (16 ms)

**Comment by thezoggy** [comment]
works fine for me in develop, have you tried upgrading to latest code?

**Comment by ShawnHardwick** [comment]
I just tested on a fresh instance of Sonarr using `develop` which is version 4.0.8.2008.

I still reproduce the issue. Is there something you are doing different?
![image](https://github.com/user-attachments/assets/c9de29b3-a1ac-4cfe-a55e-c913bf366156)

**Comment by thezoggy** [comment]
Use actual release name, so parser regex will work correctly

**Comment by ShawnHardwick** [comment]
My understanding of this is:

The release title for the series is `Ef – a Tale of ...` which is exactly what shows up in Sonarr and TheTVDB.

Each season has their own season name as `Ef - a Tale of Memories` and `Ef - a Tale of Melodies`. Using these season names will work, but using the release title I mentioned before does not.

I'm using the `ellipsis` here because I believe that is what is expected by Sonarr. This is also the title that it uses to rename the files as well.

**Comment by thezoggy** [comment]
the series title on tvdb is `Ef – a Tale of ...` which yes works fine for parsing (but no actual releases use it). the 'test parsing' is meant to test actual release names on how they would be parsed out..

but sure lets throw random fake names in there in a loose naming format, it still works fine

![firefox_2024-08-08_01-14-42](https://github.com/user-attachments/assets/02f23123-0d19-43fe-b7b6-576de3da74f8)

![firefox_2024-08-08_01-15-21](https://github.com/user-attachments/assets/7030ee48-a102-43e8-bd07-5f1ce3d31876)

come join sonarr discord and we can talk more..

**Comment by thezoggy** [comment]
to close loop, issue is that ... is getting stripped on parse thus the cleaned name doesnt end up matching the series, thus 'unknown' language is shown as it doesnt know the series.. this is purely cosmetic however since actual name does match or releases for this series do use names that are already added as alias. but to be nice added xem alias that should solve this. waiting on cache to clear to validate

**Comment by markus101** [comment]
Closing since this is resolved via an alias.
