### ISSUE TITLE
Add Custom Script support before a download starts

### ISSUE THREAD

**Issue by wallagix** [Sonarr/Sonarr#7072]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I am hosting a download client on a separat server, that sleeps on idle. Sonarr runs on a different mashine that is always on. When a download gets added to the queue, the downloader is not accessable. I wrote a custom script, that wakes the server, waits some time and remounts the drives so everzthing is accessable. The script does not get triggered, becaus the downloader is not accessable in the first place.

### Describe the solution you'd like

Add an additional signal for custom scripts, that is emitted when a new download gets pushed to the queue. 

### Describe alternatives you've considered

Alternatively add an advanced entry for the downloader. Here the mac address could be supported to send a WOL package, when a download is in the queue. Could be called "remote downloader"

**Comment by joley-gh** [comment]
To solve the issue, i used the api to check periodically if something is in the queue. If something is found, the server gets a signal and wakes up.

**Comment by markus101** [comment]
More notifications events could be nice to have, but this isn't something we're going to commit to doing at this time.

**Comment by wallagix** [comment]
> But why the download client isn't always running?
> 
> While personally I consider this request is very fishy for possible not seeding, I think you can implement a proxy that would ping and wait till the client is up before sending the original request.

I‘m not torrenting…
I let a small efficient pc handle the monitoring and the big, power hungry server does the heavy lifting. Sure, I could also host the downloader on the smaller pc. But then I need to move the content over the Network again. 

I use the api now to check for the queue and start the Server accordingly. Using a proxy is also a nice idea, going with the api seemed simpler for now.
