### ISSUE TITLE
Filter by Containing Quality

### ISSUE THREAD

**Issue by daftblazer** [Sonarr/Sonarr#7087]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I cannot find a way to filter shows so that I can only see shows that contain episodes that are Web-DL quality. I manually upgrade my Web-DL episodes so it would be easier if I know what shows need to be upgraded

### Describe the solution you'd like

Add a option for a custom filter for "Episode Contains | Does Not Contain Quality [Web-DL | BluRay]

### Describe alternatives you've considered

I've tried doing this with history but it doesn't give me a good overview

### Anything else?

I'd just like to be able to filter shows so I can see which ones aren't fully BluRay releases. Maybe even adding custom color coding for the "missing, continuing and finished" line under the show poster to see quality

**Comment by markus101** [comment]
It's not currently possible, you can use Wanted: Cutoff Unmet to do this, but filtering is minimal and will be covered by https://github.com/Sonarr/Sonarr/issues/3657
