### ISSUE TITLE
Option to re-analyze media files for Series or Season

### ISSUE THREAD

**Issue by ns-mglaske** [Sonarr/Sonarr#7088]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have a number of media that were included from previous installs that don't list the media quality / resolution / release groups, and have to manually update them.

### Describe the solution you'd like

I would like a manual option to re-analyze existing media files (mostly imported from previous installs), on the Series and Season sections (like preview rename).

### Describe alternatives you've considered

Deleting and reimporting, but this is a lot of work. :)

**Comment by markus101** [comment]
Quality and release group information comes from the filename only, if Sonarr doesn't have that in it's database it's either not present in the filename or stored in a manner that Sonarr cannot parse it so you'd only be able to do that manually.

Resolution is in media info, but it alone won't alter the quality drastically.

**Comment by ns-mglaske** [comment]
True.  I was looking for something that would re-evaluate the filenames and run mediainfo to update those details on request.  For instance, if you change the quality settings, then re-run this option, to update the details.  

My specific use case is that I'd like to alter the settings so that the filenames reflect more accurately the details for some external tools I have.  Picking up the release group would be excellent also.

On that same idea, it would also be helpful to have a filename tag for resolution alone, since that's a critical part of identifying the exact type of media.  In tags, we have Quality and Quality Full, but no specific resolution tag.  So as I can set the Quality tag on the filename, for some of the lower resolution ones, the format changes from NNNp to SDTV or DVD, and I know I can change those in the quality definitions, it's not definitive that SDTV is 480p.

**Comment by markus101** [comment]
> For instance, if you change the quality settings, then re-run this option, to update the details.

Sounds like you just want to rename the files, nothing needs to be rescanned if all you do is change the settings as nothing in settings affects that functionality outside of analyzing files which would happen on rescan automatically. If the file name or size changes it gets reprocessed, which includes updating media info.

Closing as we don't have plans to force rescan media info from files.
