### ISSUE TITLE
Fix mixing and matching between 1000 and 1024 bytes in a KB

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#709]
In the UI we seem to be using 1000, but when calculating the maximum allowed size we use 1024 to convert from maxSize in MB to maximum number of bytes (https://github.com/Sonarr/Sonarr/blob/fac6b05bb48c0d1ef35bd26418fc6b5c5f5eb370/src/NzbDrone.Core/Fluent.cs#L23), then later convert it back for logging using 1000 (https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Common/Extensions/Int64Extensions.cs)

**Comment by kmcc049** [comment]
Hi I tried to sign the contributor agreement but it gave me a helpful error 'We're sorry, but something went wrong.'  on attempting to submit. Is it ok if I take on this one? Do you prefer 1024 everywhere? RSSParser.cs (https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Indexers/RssParser.cs#L305) also seems to use either 1000 or 1024 dependent on a parameter but the code always seems to use true when invoking that method. Do you want the option taken out of this?

**Comment by markus101** [comment]
I think it makes sense to leave the option, there may be a case where we want to override it later. I think 1024 makes the most sense and seems to be what we're partially using in the UI, though it looks a bit messy in https://github.com/Sonarr/Sonarr/blob/develop/src/UI/Settings/Quality/Definition/QualityDefinitionItemView.js#L66-L92

**Comment by thezoggy** [comment]
well where does the size come into play.. when it queries indexers and 'sees' the size? pretty sure thats always 1024.. so i say just use that..  now in the gui if someone has a pref to represent filesizes because they prefer 1000 you could prob just add a toggle in the settings>ui to change the value outcome cosmetically pretty easily with your js lib too

**Comment by markus101** [comment]
The problem is 1000 and 1024 are getting mixed and matched in different places, so its more about making them all the same. We're just going to make 1024 and not offer an option to make it simple and consistent.

**Comment by kmcc049** [comment]
I've had a look over the ui and backend, only place where it seems to really happen is in the two places mentioned. Although the QulaityDefinitionView code does look a bit weird initially it does make sense. Couldn't see anywhere in the UI code where 1000 was being used for MB representation

**Comment by markus101** [comment]
Do these calls to filesize use the proper numbering? I thought they may be using 1000 instead of 1024, but I didn't look too deep.

https://github.com/Sonarr/Sonarr/blob/develop/src/UI/Settings/Quality/Definition/QualityDefinitionItemView.js#L85-L86

**Comment by kmcc049** [comment]
Now I feel silly, you are right! we pass parameter of 1 to filesize and it then defaults all the parameters. The default in filesize is to use base its 10 array so it will get displayed that way. Theres a helper method here https://github.com/Sonarr/Sonarr/blob/develop/src/UI/Shared/FormatHelpers.js that calls filesize correctly but has the wrong rounding(rounds to 1 dp) so I'll a parameter to set the rounding on the helper and use that.
We also call filessize with a 1 as the second parameter here https://github.com/Sonarr/Sonarr/blob/develop/src/UI/Activity/Queue/TimeleftCell.js so i'll take a look and see what its information source is.
I'm not familiar with using gulp for the UI, so im probably missing something that is standard here, but where are your tests and how do I run them for the front end? 

In the backend we take the number as it is set in the model for QualityDefinitionView and multiply it by 1024*1024 in the decision engine later on, which is consistent and what I followed through earlier.

**Comment by kmcc049** [comment]
not sure if I did this right but I made a pull request here

**Comment by kmcc049** [comment]
Hey, I've updated as per feedback did you want to check the pull again, https://github.com/Sonarr/Sonarr/pull/768 please?
