### ISSUE TITLE
Quality Definitions - Size Limit - middle label alignment

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#7102]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The middle label alignment gets adjusted depending on the left most label..  when it shouldnt. 
The left/right columns are fixed, so I'd expect the middle to be as well... this becomes really obvious when you have things set to "Unlimited" but different min values, 

sonarr (light) example
![firefox_2024-08-16_00-43-02](https://github.com/user-attachments/assets/25e04858-e466-4bba-a22e-c488600cbbf8)

radarr (dark) example:
![firefox_2024-08-16_00-39-02](https://github.com/user-attachments/assets/1189e0af-5ee5-4cd1-8215-fdf9fb3929a3)

### Expected Behavior

left label width shouldnt matter

### Environment

```markdown
- OS: Unraid
- Sonarr: 4.0.8.2158
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox 129.01
- Database: sqlite3
```

### What branch are you running?

Develop

### Trace Logs?

gui bug, no logs needed..  

### Anything else?

screenshot above

**Comment by markus101** [comment]
Not something we're going to address ahead of limits in profiles.
