### ISSUE TITLE
libcurl not available on synology and osx

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#711]
I already knew about osx missing it, coz well... I didn't add it yet. First wanted to see how the other platforms fared.

But apparently syno doesn't have the libcurl.so.3 to .so.4 symlink. However, they're looking into bundling libcurl.so.4 in the syno package. But that also requires some certificates, so may take some time.

We're probably better off changing the dllmap to libcurl.so.4, on ubuntu .4 exists.
At the same time we need to grab the 32bit libcurl.so.4.dylib somewhere and get it included in the package.

**Comment by Dr-Bean** [comment]
I can't reply in the forum topic with max 3 replies..., so fyi, a new Sonarr package was released for Synology containing a [bundled libcurl+certificates](https://github.com/SynoCommunity/spksrc/issues/1798).
If I'm not mistaken, your develop branch already contains the corrected libcurl symlink with https://github.com/Sonarr/Sonarr/commit/7eeabd7ca361077743e313f3d787f2244a7d2f7f?

**Comment by Taloth** [comment]
Yup, dev should be linked with version 4 now.

**Comment by Mirx** [comment]
Just to update, downloading the new Synology package, and then altering "/var/packages/nzbdrone/target/share/NzbDrone/CurlSharp.dll.config" to "dllmap os="linux" dll="libcurl.dll" target="libcurl.so.4" does the trick. The manual alteration was needed because I'm on the master branch.

**Comment by Taloth** [comment]
Excellent, I'll close the issue then. Tnx for you help.
