### ISSUE TITLE
Add option in custom formats to decrease the score of multi audio releases 

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#7120]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently we have the original language preset that works great. But I would prefer an option to download only original language and ignore releases with multiple languages

### Describe the solution you'd like

Currently we have the original language preset that works great. But I would prefer an option to download only original language and ignore releases with multiple releases

### Describe alternatives you've considered

I tried using multi as block but some of the trackers like avistaz list all the language in the search results so sonarr know what the languages are but it is not in the filename so is not blocked

### Anything else?
![Screenshot from 2024-08-19 16-36-42](https://github.com/user-attachments/assets/2088ab1b-6a9e-4965-9328-0007e9ba9281)

**Comment by Dnkhatri** [comment]
> you mean https://trash-guides.info/Sonarr/Tips/How-to-setup-language-custom-formats/#language-original-only ?

Can you point to me where it does what I am asking I might have missed it

**Comment by Dnkhatri** [comment]
> I just tried this out, and sadly it looks like I was under the wrong impression. 
> 
> Regarding your request now I'm thinking if adding a new specification with the number of languages is going to lead to bad configurations or not...
What I want is to just ignore any release that has language apart from original

**Comment by Dnkhatri** [comment]
@markus101 
Thks for the fix
How do I use this option? Use it as an ignore if match rule

**Comment by markus101** [comment]
Probably the easiest is Original Language with Except Language true and then give it a negative score to give it a lower preference.
