### ISSUE TITLE
Sometimes nzb downloads from nzbgeek get truncated on mono with https 

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#713]
Just the built in Webclient. Problem could be the chucked transfer encoding.

**Comment by Taloth** [comment]
My first attempt at a small test case resulted in failure, no reproduction yet.

**Comment by jknight2014** [comment]
Hello, Taloth. I am able to reproduce this error. I grabbed the log ends from SAB and Sonarr. 

SAB: http://pastebin.com/8wdfR58f
Sonarr: http://pastebin.com/e2wKVwMV

When I first started using nzbgeek there was no problem. Then Random ones would fail if I did something like add a whole season. Now all fail.

**Comment by sporkman** [comment]
I can fairly reliably repeat this as well.  Adding a full season always triggers it, manually searching for more than 2 or 3 shows triggers it.

**Comment by Taloth** [comment]
Fixed in mono 4.2.1 (https://github.com/mono/mono/commit/754395be235ee67df917421d3f86e3ff2458ee81 and [bugzilla link](https://bugzilla.xamarin.com/show_bug.cgi?id=23792))
