### ISSUE TITLE
string search - uk/europe naming scheme

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#714]
noticed tonight that releases were not showing up in sonarr but show up in other apps when sonarr searches by string.. notice it only does the tvdb name and S##E## format. This means that for certain indexers it may never find a release (because exception name isnt used or in uk ep format)... granted theres only a few groups that even use this format anymore.. 

from 2011 standards:

```
  ▐░▌   - Releases are to be named in the format:                           ▐░▌
  ▐░▌     - Show.Name.S00E00.SOURCE.XviD-Group                              ▐░▌
  ▐░▌     - Show.Name.Part0.SOURCE.XviD-Group                               ▐░▌
  ▐░▌     - Show.Name.2008.00.00.SOURCE.XviD-Group                          ▐░▌
  ▐░▌     - Show.Name.S03E04-E05.SOURCE.XviD-Group                          ▐░▌
  ▐░▌     - Show_Name.0x00.SOURCE.XviD-Group                                ▐░▌
  ▐░▌     - Show_Name.Part_Zero.SOURCE.XviD-Group                           ▐░▌
  ▐░▌     - Show_Name.3x04_3x05.SOURCE.XviD-Group         
```

some example releases:
`The_Interceptor.1x07.720p_HDTV_x264-FoV`
`Top_Gear.22x08.720p_HDTV_x264-FoV`

I would say search in S##E## first - if no releases returned, then fall back to #x## format after a brief delay so you dont hammer.

**Comment by thezoggy** [comment]
and to note about when to fall back to `#x##` format if you just dont want to waste some api hits.. apply some logic based off the show's network..  have a set of networks that will trigger the fallback.. for example 'bbc two' would be one.
top gear -- http://skyhook.sonarr.tv/v1/tvdb/shows/en/74608

**Comment by bakerboy448** [comment]
This bug/issue seems stale.  Please check and see if it is still an issue on the recent v3 builds.  If it is an issue please open a new GHI with logs and full detail.
