### ISSUE TITLE
rtorrent download client not connecting

### ISSUE THREAD

**Issue by nytemyst** [Sonarr/Sonarr#715]
Host : seedboxurl/username/rutorrent
port : tried 80/443/blank
URL Base : RPC2
Use SSL : yes

Table logs say this

Invalid request Validation failed: 
 -- must be valid Host without http://

Using Version 2.0.0.3357 on a Windows Server 2008 r2

**Comment by markus101** [comment]
Please use our forums for support.

Your host is wrong, `/username/rutorrent` should be part of URL Base.
