### ISSUE TITLE
Option to disable authorization

### ISSUE THREAD

**Issue by kuba-orlik** [Sonarr/Sonarr#7153]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I am running my own  access control  proxy and it conflicts with Sonar's own built-in authorization that is now force-enabled.

### Describe the solution you'd like

It would be good to have an option to disable authorization.

Alternatively, it would be good to have the option to whitelist certain IP addresses (as I could then whitelist the IP of the access proxy that I'm using)

### Describe alternatives you've considered

Logging in only from my local network, as Sonarr allows disabling auth on local addresses

**Comment by augustuen** [comment]
Disabling authentication from the UI was removed for a reason. You can still disable it by editing the config file directly.

The option to disable authentication won't be added back in.

**Comment by markus101** [comment]
Authentication, not authorization, https://github.com/Sonarr/Sonarr/issues?q=sort:updated-desc+is:issue+disable+authentication+is:closed

And also on the [wiki](https://wiki.servarr.com/sonarr/faq-v4#forced-authentication)
