### ISSUE TITLE
make a difference between dubbed and subtitled for non english languages

### ISSUE THREAD

**Issue by sdesbure** [Sonarr/Sonarr#716]
Hello,
I think it would make sense to make a difference between dubbed episodes and subtitled episodes.
For example, in french, the first one is "FR or FRENCH" and the second one is "VOST or VOSTFR". a change in [line 204 of parser.cs](https://github.com/Sonarr/Sonarr/blob/30ab5bc17f20cfce19cf322a0bfb9634faf8a870/src/NzbDrone.Core/Parser/Parser.cs#L204) would probably make it (and putting two types of languages like french_dubbed and french_st) 
but I'm not sure :sweat_smile:

**Comment by markus101** [comment]
The proper way to handle this is to treat audio and subtitle language separately, which is discussed a bit here, though hasn't seen much traction: https://github.com/Sonarr/Sonarr/issues/280
