### ISSUE TITLE
Sonarr forgets parameters on restart

### ISSUE THREAD

**Issue by mafredri** [Sonarr/Sonarr#717]
Hi, I've noticed a weird issue with Sonarr where command line parameters are forgotten (`data` in this case) when triggering a restart through the lifecycle-hooks in the web-ui. There is no problem when updating Sonarr and it is restarted as part of an update:

Before restart: `mono NzbDrone.exe --data=/path/to/sonarr/config`

After restart: `mono --debug NzbDrone.exe --restart --nobrowser`

I've tried looking through the code but couldn't find a reason for this happening :/.

**Comment by Taloth** [comment]
That's why --data isn't officially supported in production environments.

**Comment by mafredri** [comment]
Any chance it will be? I would like to be able to use it reliably on a Sonarr port for a NAS system.

**Comment by Taloth** [comment]
Not anytime soon.

**Comment by mafredri** [comment]
Too bad, I guess I'll have to work around this by shadowing the mono executable to apply it during a restart :/.

Just one question, why different procedures during an update and a restart?

**Comment by markus101** [comment]
@mafredri not a lot to it, just different processes.

**Comment by Napsterbater** [comment]
Can this be looked into again? Still happens on Sonarr 3.0

Was about to open the below bug and lucked across this.


## Bug Report

Restarting Sonarr via Web UI when using custom data/install directory via --data= command line causes the newly started sonarr instance to revert to default data directory.

### System Information/Logs

**Sonarr Version:**
3.0.3.610
**Operating System:**
Windows Server 2016 Build 14393
**.net Framework (Windows) or mono (macOS/Linux) Version:**
4.7
**Link to Log Files (debug or trace):**
N/A
**Browser (for UI bugs):**
N/A
