### ISSUE TITLE
Links dialog no longer working

### ISSUE THREAD

**Issue by BeardMatt** [Sonarr/Sonarr#7176]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If you select and series in sonarr (/series/showname) and hover over the links, the dialog box goes away before it's possible to click on anything.
![links](https://github.com/user-attachments/assets/6a343936-0d1d-43bb-bee2-d162fd6c0d71)

### Expected Behavior

The dialog should not close when moving the mouse.

### Steps To Reproduce

In sonarr, click on SERIES => (pick tv show) => hover mouse over LINKS option for TV series (that links to IMDB, etc. for show) and try moving the mouse to click on an option.

### Environment

```markdown
- OS: linux/docker/ubuntu
- Sonarr: 4.0.9.2332
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: chrome Version 128.0.6613.120 (Official Build) (64-bit)
- Database: N/A
```

### What branch are you running?

Develop

### Trace Logs?

.

### Anything else?

nothing else.

**Comment by markus101** [comment]
Will be fixed when https://github.com/Sonarr/Sonarr/pull/7172 lands

**Comment by BeardMatt** [comment]
Thanks Markus
