### ISSUE TITLE
Anime and Newznab

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#718]
Newznab searching for anime works when the series is set to anime and the release is a 2 digit absolute number, if the releases are numbered with 3 digits searches under 100 won't work properly. If the initial search yields no results we should fallback to 3 digit searching (or just always do it and use another API call). We could also look at supporting Rage ID searches, but thats not likely to work for all indexers.

**Comment by lad1337** [comment]
+1

**Comment by M0UL** [comment]
+1

**Comment by Taloth** [comment]
related https://github.com/Sonarr/Sonarr/issues/1125

**Comment by markus101** [comment]
Closing in favour of the linked episode since it's more active.
