### ISSUE TITLE
Colon replacer and general renaming issue - win 11

### ISSUE THREAD

**Issue by Justin1521** [Sonarr/Sonarr#7183]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When downloading episodes with a colon, sonarr will move the file with the torrent name but stop at the colon. It then shows as a “file” type with 0 bytes. I have tried the different options for the colon to no avail. Interesting note is if set to remove colon or checking the renaming box, sonarr will not attempt to move the file at all. 

### Expected Behavior

I expect sonarr to move the file with the correct type and size, and to rename the file while replacing the colon with its intended preset of dash/space. 

### Steps To Reproduce

1. Find show with colon in the torrent name
2. Monitor and search for a episode 
3. Open root directory and navigate to the episode
4. Episode will show name up to colon with 0 bytes

### Environment

```markdown
- OS: win 11
- Sonarr: 4.0.9.2244
- Docker Install: no
- Using Reverse Proxy: no
- Browser: microsoft edge
- Database: dont know
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/user-attachments/files/16901514/sonarr.trace.txt)

### Anything else?

https://github.com/user-attachments/assets/51d3010d-d4de-457f-80bc-0264a1d4bb71

**Comment by markus101** [comment]
What renaming settings are you using?

> [user-attachments/assets/51d3010d-d4de-457f-80bc-0264a1d4bb71](https://github.com/user-attachments/assets/51d3010d-d4de-457f-80bc-0264a1d4bb71)

Win + Shift + S is your friend, no one needs to see a cockeyed picture of your monitor.

**Comment by Justin1521** [comment]
![Screenshot 2024-09-05 at 9 21 18 PM](https://github.com/user-attachments/assets/e9060232-440a-4320-a162-985d4e52cad2)

Sorry about the original pic. Hope this is better.
