### ISSUE TITLE
I2PSnark as a download Client

### ISSUE THREAD

**Issue by LuposX** [Sonarr/Sonarr#7187]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I would be nice to automate the process of torrenting over the [I2P](https://geti2p.net/en/) network.

### Describe the solution you'd like

I propose to add [I2PSnark](https://github.com/i2p/i2p.i2p/tree/master/apps/i2psnark) as a download client to Sonarr.

### Describe alternatives you've considered

It is already possible to use qBitTorrent to achieve the same effect, since it already supports I2P.

**Comment by markus101** [comment]
I don't see any API documentation, but came across https://www.reddit.com/r/i2p/comments/1e1ia1u/i2psnark_to_prowlarr/ which has some examples on how to implement it by mimicking Transmission's API.

We're not going to implement direct support at this time.
