### ISSUE TITLE
Feature Request: Add Enable/Disable Checkbox for Settings > Connections Entries

### ISSUE THREAD

**Issue by comrade-meowski** [Sonarr/Sonarr#7188]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

N/A

### Describe the solution you'd like

Could we have an "enable" checkbox for configured entries in Settings > Connections please? 

It would be very useful to have exactly the same functionality as available in Settings > Download Clients where the configurations can be left in place when not in use and enabled/disabled as required. Currently the only option is to delete the configured Connections entry when not in use and then recreate it or put up with perpetual health warnings from Sonarr. 

### Describe alternatives you've considered

N/A

**Comment by markus101** [comment]
You just need to uncheck the actions, unlike download clients that didn't have any enabled/disabled state.

No plans to add an extra toggle for that.

**Comment by comrade-meowski** [comment]
Inelegant but fair enough - thanks for your response.
