### ISSUE TITLE
Option to edit Title for Episode with TBA Title when importing manually

### ISSUE THREAD

**Issue by Tama47** [Sonarr/Sonarr#7189]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When an episode has a TBA title, I either have to wait for it to have a title and automatically import, or I manually import and have to rename the files later.

### Describe the solution you'd like

An option to manually enter the Episode Title when I click the human icon, so that the imported files have the correct name.

### Describe alternatives you've considered

Manually renaming the files myself.

**Comment by markus101** [comment]
It's definitely an interesting idea, but the implementation would be messy without larger changes.

At this time it's not something we're going to commit to, but will tag for reconsideration in the future.
