### ISSUE TITLE
Gotify : add options for phones

### ISSUE THREAD

**Issue by home-local** [Sonarr/Sonarr#7190]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

At the moment with gotify if you tick to add the image, it will not be displayed on mobile notifications but will display an ‘obj’ icon.
![{A929B6A5-0D7F-4E64-88A0-4C90F804E45A}](https://github.com/user-attachments/assets/d5d91c94-f91a-43c8-afa3-04682fbd69df)

### Describe the solution you'd like

In gotify, you can add parameters to the message so that an image and a link are sent to Android.
At the moment, sonarr only sends markdown, but by adding extra parameters, you can add an image and a url.

`{
	"title": "New Import",
	"message": "NAME OF MOVIE",
	"priority": 5,
	"extras":
	{
		"client::notification":
		{
			"bigImageUrl": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Big_Buck_Bunny_thumbnail_vlc.png",
			"click":
			{
				"url": "https://www.imdb.com/"
			}
		},
		"client::display":
		{
			"contentType": "text/markdown"
		}
	}
}`

Here is a final example 
![{EE1DA4E9-7427-4321-BCD4-D25C870979AD}](https://github.com/user-attachments/assets/68e728fd-3580-4cbf-9bf3-85c149d5133a)

And ideally there should be an option to enable or disable markdown because in the gotify doc it's recommended to use text/plain for greater security, that doesn't prevent the image from being sent via the ‘bigImageUrl’ option for phones because markdown is just used to display the image on the gotify web page.

Thank you if you have time to add it.

### Describe alternatives you've considered

-

**Comment by markus101** [comment]
Is Gotify going to add support for `bigImageUrl` on other clients?

Markdown is only used so that images can be embedded, but from what I see in their docs that is the only way to include images for anything that isn't Android.  The same would be true for links, which means any link or image being included needs to include markdown to be supported on multiple platforms.

**Comment by home-local** [comment]
I see that you've already added the option, I tried to do it on radarr but it would be better if I let you do it, as you've implemented more options than I have.
Tell me if I should close the pr?

**Comment by QuarkZ26** [comment]
Is this supposed to be working at this point? I'm still not getting the actual image on notifications, though Radarr seems to be working fine.
