### ISSUE TITLE
Treat zipx files as archived files

### ISSUE THREAD

**Issue by Betonhaus** [Sonarr/Sonarr#7191]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Right now there seems to be a virus campaign where torrent uploads appear to be a proper tv episode but instead contain malware hidden in a "zipx" file. Right now Sonarr will hang on import, requiring the user to manually intervene

### Describe the solution you'd like

when an import fails due to unrecognized file format "zipx", automatically delete and blacklist the torrent and search again

### Describe alternatives you've considered

manually deleting, blacklisting, and searching again
recheck your indexers as one may have gone bad

### Anything else?

perhaps pop up a warning, and/or lower the priority of the indexer that the file came from.

**Comment by markus101** [comment]
Sonarr does not remove downloads that it does not handle importing for. You may be able to set something up in your download client to automatically cancel them when files with that extension are found.

**Comment by Betonhaus** [comment]
I should point out that this is literally downloads that Sonarr chose from the indexers and sent to the download client itself. The entire origin of the file was Sonarr intending to import it, and therefore Sonarr should be responsible for recognizing that it downloaded a bad file and retrying, let alone the fact that it should recognize that it downloaded a virus that could be potentially dangerous for the user.

**Comment by thezoggy** [comment]
sonarr doesnt actually download though and doesnt know it would be bad. 
the downloader itself should reject it if an unwanted extension is found. set your downloader to do that. so sonarr would know its 'bad'. 

then additionally, user should report bad things to their indexer so they can take it down / do the needful to filter out such things. but I'm assuming this is happening on a public site that lacks moderation or the barrier to entry for spam/malware/etc is high... which then i would say just avoid using said site or again do the proper steps for your downloader to avoid such things.
