### ISSUE TITLE
Sonarr looks for wrong libssl on FreeBSD 14.1-RELEASE

### ISSUE THREAD

**Issue by Viper780** [Sonarr/Sonarr#7198]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When starting sonarr on FreeBSD 14.1 it crashes with the Info 

`No usable version of libssl was found
Abort`

### Expected Behavior

It will start as it did unter FreeBSD 13.3

### Environment

```markdown
- OS: 14.1-RELEASE-p4 
- Sonarr: sonarr-4.0.9.2244 (installed with pkg)
- Docker Install: No
- Using Reverse Proxy: No
- Browser: -
- Database: sqlite3-3.46.1,1
```

### What branch are you running?

Main

### Trace Logs?

No WebUI to to activate traces

### Anything else?

Found a similar issue here https://github.com/Sonarr/Sonarr/issues/6859 but no resolution
The mentioned rc script has this workaround already implemented

**Comment by mvanbaak** [comment]
I'm unable to replicate this:

```
root@sonarr:~ # freebsd-version -ru
14.1-RELEASE
14.1-RELEASE-p4
root@sonarr:~ # pkg info
bash-5.2.32                    GNU Project's Bourne Again SHell
ca_root_nss-3.93_2             Root certificate bundle from the Mozilla Project
gettext-runtime-0.22.5         GNU gettext runtime libraries and programs
icu-74.2_1,1                   International Components for Unicode (from IBM)
indexinfo-0.3.1                Utility to regenerate the GNU info page index
krb5-1.21.3                    MIT implementation of RFC 4120 network authentication service
libedit-3.1.20240808,1         Command line editor library
libiconv-1.17_1                Character set conversion library
libinotify-20240724            Kevent based inotify compatible library
libunwind-20240221             Generic stack unwinding library
mktorrent-1.1_1                Command-line utility for creating BitTorrent metainfo files
pkg-1.21.3                     Package manager
readline-8.2.10                Library for editing command lines as they are typed
sonarr-4.0.9.2244              PVR for Usenet and BitTorrent users
sqlite3-3.46.0,1               SQL database engine in a C library
ssmtp-2.64_7                   Extremely simple MTA to get mail off the system to a mail hub
vim-console-8.2.3273_1         Improved version of the vi editor (console only)
zip-3.0_2                      Create/update ZIP files compatible with PKZIP
```

and sonarr info:
```
Version 4.0.9.2244
Package Version 4.0.9.2244 by michiel@vanbaak.eu
.NET Yes (6.0.13)
Database Sqlite 3.46.0
Database Migration 211
AppData Directory /usr/local/sonarr
Startup Directory /usr/local/share/sonarr/bin
Mode Console
Uptime 00:03:56
```

What you can try is install the package `openssl111`. This should not be needed if you use the sonarr package as this has a fix in the rc script to tell the sonarr process to use a newer openssl, but see if it makes your sonarr start again.

**Comment by Viper780** [comment]
I've just spun up a new jail and tested it again.

the problem only occurs when I'm activating SSL.

Than there is the error `Invalid SSL certificate file or password` 
but the same certificate and password is working on FreeBSD 13.3

but also the traces are not very helpful
`024-09-10 14:18:50.7|Trace|SonarrErrorPipeline|Handling Exception
2024-09-10 14:18:50.8|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- SslCertPath: Invalid SSL certificate file or password`

**Comment by bakerboy448** [comment]
fwiw there's really 0 need to SSL Starrs

if external access - use a reverse proxy.

......if you're that concerned about intranetwork communication being listened to - thus needing SSL for LAN - you likely have other network securing to work through.

**Comment by Viper780** [comment]
> fwiw there's really 0 need to SSL Starrs
Thats on so many levels wrong.
 
> if external access - use a reverse proxy.
enhances complexity and leaves the communication between reverse proxy and the service itself unencrypted 

> ......if you're that concerned about intranetwork communication being listened to - thus needing SSL for LAN - you likely have other network securing to work through.
It seems you need a good network and security engineer that gives you some tutoring.

Your knowledge seems to be stuck in the 90ies.
I recommend to read up about Zero Trust and  modern Security Models (like the NIST Guide about ZT https://csrc.nist.gov/pubs/sp/800/207/final )

In a private Network you can't archive a real secure Zone 

> Certainly seems like a jail / FreeBSD bug and not a sonarr bug though....
Maybe - hard to tell from my point, what is your conclusion what it is a FreeBSD Bug and has nothing todo with .net or sonarr?

I found out that under FreeBSD 14 and the latest sonarr Version it isn't enough to use the certificate and privatekey to generate the pfx file - you also need to include the fullchain.

But there is no Information about any of that and also the error message is sloppy (at best)

**Comment by bakerboy448** [comment]
Any actual trace logs that show the stacktrace and context where it's failing rather than just a tiny snippet of the error with no context?  

Also per as noted in the wiki in the template ?that was ignored? - the UI is not required to get and provide tracelogs. Not sure why you opened a bug report without required logs and not looking at the resources on how to get and gather logs.

> Trace Logs (https://wiki.servarr.com/sonarr/troubleshooting#logging-and-log-files)

> [Open the trace log file (sonarr.trace.txt) via the UI or the log file](https://wiki.servarr.com/sonarr/troubleshooting#standard-logs-location) on the filesystem and find the relevant context

Not obvious from the single line error with no context if it ends up as a dotnet issue or a sonarr issue

**Comment by markus101** [comment]
Instead of complaining about the quality of the logging, provide the requested information. Your belief that the UI is required to access logging is incorrect and failing to read the linked wiki article and following the instructions on how to provide the required logs is in your words, sloppy (at best). That said, in this particular instance trace logs likely wouldn't have provided (much) more information, but that is up for us to determine based on the logs.

The information provided in the log is generic, because there is no information available for Sonarr to interpret, though we can provide the original exception message for you to interpret, but that message can vary, be it an invalid PFX file leading to `Unspecified error` or something more useful if the provided password is wrong (`The specified network password is not correct.`).

**Comment by Viper780** [comment]
> Instead of complaining about the quality of the logging, provide the requested information. Your belief that the UI is required to access logging is incorrect and failing to read the linked wiki article and following the instructions on how to provide the required logs is in your words, sloppy (at best).

I did read the wiki and I can't find a hint on how to enable Trace Logs without starting up sonarr and activate it in the UI.


> That said, in this particular instance trace logs likely wouldn't have provided (much) more information, but that is up for us to determine based on the logs.

You are Sure? I pasted the only line of the tracelog referencing the SSL Issue in here: https://github.com/Sonarr/Sonarr/issues/7198#issuecomment-2340974870


> The information provided in the log is generic, because there is no information available for Sonarr to interpret, though we can provide the original exception message for you to interpret, but that message can vary, be it an invalid PFX file leading to `Unspecified error` or something more useful if the provided password is wrong (`The specified network password is not correct.`).

That would be very helpful and removes the guessing if something with the password is wrong

**Comment by bakerboy448** [comment]
> > I did read the wiki and I can't find a hint on how to enable Trace Logs without starting up sonarr and activate it in the UI.

Impossible given Step 1 on the wiki

> [Turn Logging up to Trace (Settings => General => Log Level or Edit The Config File)](https://wiki.servarr.com/sonarr/troubleshooting#tracedebug-logs)

which links to

> If you're unable to access the UI to set the logging level you can do so by editing config.xml in the AppData directory by setting the LogLevel value to Debug or Trace instead of Info.

**Comment by Viper780** [comment]
tried it but it didn't wrote a debug and trace file.

But I did provided a trace even before you entered this Issue

**Comment by mvanbaak** [comment]
> Certainly seems like a jail / FreeBSD bug and not a sonarr bug though....

Just for future readers: This is _NOT_ a jail/FreeBSD bug, but sonarr spitting out an error message that does not point out the problem.
