### ISSUE TITLE
Requesting support for S3 object storage

### ISSUE THREAD

**Issue by bernardgut** [Sonarr/Sonarr#7200]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Anyone who has libraries 30TB+ or bigger cannot use your software suite because, well 30TB+ devices dont really exist. So such a library is unmountable. It turns out distributed object storage such as Minio is what is used for big data. *Arr suite should therefore support S3 protocol natively.

### Describe the solution you'd like

same as https://github.com/Sonarr/Sonarr/issues/4891

### Describe alternatives you've considered

There are no realistic alternatives for really large datasets (50TB+)

### Anything else?

same as https://github.com/Sonarr/Sonarr/issues/4891

**Comment by Thirrian** [comment]
I guess my NAS doesn't exist then, welp. Where to stay with my data now...

**Comment by bernardgut** [comment]
Not everyone wants to use NFS. Its old slow and insecure. Even the Kubernetes upstream doesn't recommend using the NFS CSI driver. Sure you can use that. Nobody prevents you. But why not just support the 2024 standard for large datasets, which is S3 protocol ?

**Comment by addisonbabcock** [comment]
If it's not possible to store more than 30TB on a single volume then how does Amazon do it? This seems like a very strange point to make when many sonarr users (myself included) have libraries in the hundreds of terabytes stored locally.

**Comment by bernardgut** [comment]
well volmes on amazon are backed by ceph. Nobody using Sonarr as the time/money to deploy Ceph at home. In the meantime we still want to support very large datasets without spending ludicrous amounts of money. Its either NFS or S3. So why not support both ?

**Comment by markus101** [comment]
We do not have plans to support S3 storage, it would require a lot of changes and continued support for a very limited number of users that would use it directly.
