### ISSUE TITLE
importing file never ends.

### ISSUE THREAD

**Issue by moreje** [Sonarr/Sonarr#7202]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have 8 finished downlods that are blocked into waiting list . 
one of them is blocked in "import in progress" state
the file is actually already copied in its destination and it seems that Sonarr does not release this file to process another one

### Expected Behavior

Sonarr should release the process and skip to another file

### Environment

```markdown
- OS: linux
- Sonarr: 4.0.9.2342
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: 
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

[tracesonarr.txt](https://github.com/user-attachments/files/16983403/tracesonarr.txt)

**Comment by stevietv** [comment]
is a support issue being dealt with on discord.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
