### ISSUE TITLE
Make forward and backward arrows move through filtered shows

### ISSUE THREAD

**Issue by roadhazard** [Sonarr/Sonarr#7204]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

When I click on 'Filter' and select 'Monitored Only', all my monitored shows are displayed. When I click on the first one, I'm taken into the show. Now, if I click the right arrow in the top, right:

![image](https://github.com/user-attachments/assets/426b7d4b-b038-43bd-b945-d593bc133ee4)

... I'm taken to the next show but not the next FILTERED show. If I set a filter and click on the first show in that filtered view , and am using those forward/backward arrows to navigate, I'd like to be taken to the next FILTERED show.

Hope this makes sense. If not, I can add more detail.

### Describe alternatives you've considered

Can't think of any.

### Anything else?

In this example, 'B90 Strikes Back' is unmonitored. If I switch the view to show me 'Monitored Only', 'B90' will drop from the list. If I click on '90 Day Fiance' and when viewing that, click the right arrow in the top right, I'll be taken to 'B90' instead of the next monitored show, '90 Day Fiance: Before the 90 Days'.

![image](https://github.com/user-attachments/assets/092e4481-f51a-4e32-8436-598dd8cf2cc9)

**Comment by markus101** [comment]
Filtering only applies to the series list. At this time we do not have plans to extend it to other places.
