### ISSUE TITLE
Manually match torrent while it's still downloading

### ISSUE THREAD

**Issue by MrDemocracy** [Sonarr/Sonarr#7210]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes an episode is matched to the wrong season or not matched to a series at all. This can cause it to not get imported when if finishes downloading, or cause it overwrite an existing episode. The only way to deal with this currently that I know of, is to wait for the download to finish and then correct the mistake.

### Describe the solution you'd like

Make it possible to manually match the torrent to the correct show or season while it's still downloading on the activity queue page in a similar way to how manual importing works when automatic import is not possible.

### Describe alternatives you've considered

It may be possible to alter the release name regex to handle these cases that get matched incorrectly, but would still be an issue for incorrect release names so it might still be worth it having a way to correct them manually before the download is able to finish and it gets imported automatically.

**Comment by markus101** [comment]
Given the complexities involved to do this, especially with season packs, this is not something we're going to commit to doing at this time.
