### ISSUE TITLE
Unable to Save Existing Quality Profile - Must contain all qualities - Missing 576p

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#7227]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Unable to modify existing quality profiles due to missing quality

### Expected Behavior

new qualities should be properly added to user's existing profiles and not require user to recreate all profiles from scratch - this even impacts duplicated/cloned profiles

### Environment

```markdown
- OS: ubuntu 22.04
- Sonarr: 4.0.9.2386
- Docker Install: yes
- Using Reverse Proxy:  yes, n/a
- Browser: n/a
- Database: 
Postgresql 16.4
Migration 214
```

### What branch are you running?

Develop

### Trace Logs?

https://logs.notifiarr.com/?bdbae68e77144f33#6aCtrBbTsCZv5mdXB3aQ7sLVuiVUJEScNZrDdXbTnEJU

### Anything else?

![image](https://github.com/user-attachments/assets/f7d8db99-58c5-42c4-bc37-2fe20c089d64)

Profile json dump from API - https://logs.notifiarr.com/?1049109872fc8420#3mQMwP59x1TCBbLVKt2gH6Fz49bWzTqpx3UtFskcwQid

Database csv export of QualityProfiles table - https://logs.notifiarr.com/?06c96bf4f52006d4#UqTisUuRbTRVAGDgPd6AJFat4KciBSHCN9GKe14bM1E

Perhaps already will be fixed by https://github.com/Sonarr/Sonarr/pull/7220 or the fix can be added to that PR

**Comment by markus101** [comment]
Already fixed that #7220
