### ISSUE TITLE
Don't Overwrite Date if only Subsecond value has changed

### ISSUE THREAD

**Issue by rxbrad** [Sonarr/Sonarr#7228]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

> **EDIT** (tldr; summary of me fumbling with this Issue ticket):  The ask would be for Sonarr not to update timestamps if the only change would be to set the nanoseconds back to zero (and to pick a random nonzero nanosecond entry for the initial import/rename).  Because `snapraid touch` assigns a different random nanosecond to the timestamp every time it undoes Sonarr's zero-nanosecond timestamp, it breaks parity with every SnapRAID sync and forces a full re-sync of TV shows.

When assigning timestamps to episodes based on airdate, the timestamp recorded does not include subseconds.  SnapRAID, for example, uses a timestamp's subseconds to calculate parity.

People using Sonarr + SnapRAID are forced to update the timestamps of every TV episode immediately prior to each SnapRAID sync to avoid hours of unneeded parity calculations.  Afterwards, Sonarr goes through and updates the timestamps of each file once again, to zero subseconds.

### Expected Behavior

When Sonarr updates a timestamp, the timestamp should be recorded to have nonzero subseconds.

### Environment

```markdown
- OS: Docker container: linuxserver/sonarr:develop
- Sonarr: 4.0.9.2386
- Docker Install: debian
- Using Reverse Proxy: No
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/user-attachments/files/17063738/sonarr.trace.txt)

**Comment by markus101** [comment]
> SnapRAID, for example, uses a timestamp's subseconds to calculate parity.

Does SnapRAID change the subseconds after it calculates parity for a particular file? Thus when Sonarr checks for equality of the timestamp on the file it sees the differences and overwrites it?

**Comment by rxbrad** [comment]
SnapRAID reports an error on files missing subsecond accuracy, so `snapraid touch` (this sets all files' subseconds to zero) needs to be run to complete a sync without error.

Sonarr then scrubs the subseconds from the timestamp when it checks for equality.

The two programs keep changing timestamps back and forth in order to maintain SnapRAID parity...

**Comment by markus101** [comment]
Right, but if Sonarr imports a new file that SnapRAID hasn't processed before and sets the timestamp of the file (subsecond would be zero), what happens? Does SnapRAID complain? Or does it only care in subsequent parity checks?

I'm trying to understand whether it only matters when comparing the timestamp when reprocessing already imported files or we always need to care about subseconds when setting the value, even for files that SnapRAID has never processed. I assume it's being set by SnapRAID at some point during the parity calculation process otherwise files that truly had the modification land on 0 would be a forever problem.

**Comment by rxbrad** [comment]
Okay, I'm sorry....  I'm dumb....  `snapraid touch` apparently does not create a zero-subsecond entry.  It AVOIDS it.

Here's is a freshly-Sonarr-dated timestamp list, which SnapRAID complains about...
```
$ ls '/srv/mergerfs/datapool1/TV/Secret Invasion/Season 1/' --time-style='+%d-%m-%Y %H:%M:%S.%N' -l
total 7493064
-rw-rw-r-- 1 dockeruser users 1748567510 21-06-2023 03:00:00.000000000 'Secret Invasion (2023) - S01E01 - Resurrection h265 8bit AC3 5.1 WEBDL-1080p Sonarr.mkv'
-rw-rw-r-- 1 dockeruser users 1633259894 28-06-2023 03:00:00.000000000 'Secret Invasion (2023) - S01E02 - Promises h265 8bit AC3 5.1 WEBDL-1080p Sonarr.mkv'
-rw-rw-r-- 1 dockeruser users 1152008416 05-07-2023 03:00:00.000000000 'Secret Invasion (2023) - S01E03 - Betrayed h265 8bit AC3 5.1 WEBDL-1080p Sonarr.mkv'
-rw-rw-r-- 1 dockeruser users 1076108288 12-07-2023 03:00:00.000000000 'Secret Invasion (2023) - S01E04 - Beloved h265 8bit AC3 5.1 WEBDL-1080p Sonarr.mkv'
-rw-rw-r-- 1 dockeruser users 1035391572 19-07-2023 03:00:00.000000000 'Secret Invasion (2023) - S01E05 - Harvest h265 8bit AC3 5.1 WEBDL-1080p Sonarr.mkv'
-rw-rw-r-- 1 dockeruser users 1027520043 26-07-2023 03:00:00.000000000 'Secret Invasion (2023) - S01E06 - Home h265 8bit AC3 5.1 WEBDL-1080p Sonarr.mkv'
```

And here is the same list after `snapraid touch`:
```
ls '/srv/mergerfs/datapool1/TV/Secret Invasion/Season 1/' --time-style='+%d-%m-%Y %H:%M:%S.%N' -l
total 7493064
-rw-rw-r-- 1 dockeruser users 1748567510 21-06-2023 03:00:00.092953022 'Secret Invasion (2023) - S01E01 - Resurrection h265 8bit AC3 5.1 WEBDL-1080p Sonarr.mkv'
-rw-rw-r-- 1 dockeruser users 1633259894 28-06-2023 03:00:00.705116895 'Secret Invasion (2023) - S01E02 - Promises h265 8bit AC3 5.1 WEBDL-1080p Sonarr.mkv'
-rw-rw-r-- 1 dockeruser users 1152008416 05-07-2023 03:00:00.424472913 'Secret Invasion (2023) - S01E03 - Betrayed h265 8bit AC3 5.1 WEBDL-1080p Sonarr.mkv'
-rw-rw-r-- 1 dockeruser users 1076108288 12-07-2023 03:00:00.799443993 'Secret Invasion (2023) - S01E04 - Beloved h265 8bit AC3 5.1 WEBDL-1080p Sonarr.mkv'
-rw-rw-r-- 1 dockeruser users 1035391572 19-07-2023 03:00:00.053698972 'Secret Invasion (2023) - S01E05 - Harvest h265 8bit AC3 5.1 WEBDL-1080p Sonarr.mkv'
-rw-rw-r-- 1 dockeruser users 1027520043 26-07-2023 03:00:00.107342166 'Secret Invasion (2023) - S01E06 - Home h265 8bit AC3 5.1 WEBDL-1080p Sonarr.mkv'
```

And here is a Radarr timestamp:
```
$ ls '/srv/mergerfs/datapool1/Movies/2 Fast 2 Furious (2003)/'  --time-style='+%d-%m-%Y %H:%M:%S.%N' -l
total 7459724
-rw-rw-r-- 1 dockeruser users 7638749726 04-06-2003 20:00:00.726177187 '2 Fast 2 Furious (2003) {tmdb-584} [Bluray-2160p][HDR10][DTS-X 7.1][x265 10bit]-PHOCiS.mkv'

```

**Comment by markus101** [comment]
I think the difference with Radarr is in how it compares the date stamps, which also fixes another issue that has mostly gone unnoticed (or ignored) where DST changing causes things to update because the time has changed.
