### ISSUE TITLE
Can't click checkbox when adding path

### ISSUE THREAD

**Issue by godofgrunts** [Sonarr/Sonarr#723]
Linux cthulhu 4.1.3-1-ARCH #1 SMP PREEMPT Wed Jul 22 20:37:12 CEST 2015 x86_64 GNU/Linux

Mozilla Firefox 39.0

About

Version
    2.0.0.3212
Mono Version
    4.0.2 (Stable 4.0.2.5/c99aa0c Mon Jul 13 18:57:35 UTC 2015)
AppData directory
    /var/lib/sonarr
Startup directory
    /usr/lib/sonarr

Steps to reproduce:

Navigate to http://localhost:8989/addseries

Click "Import Existing Series On Disk"

Click the browse icon

Browse to desired path (/mnt/new/media/Cartoons/)

Try to click green check box (I can't) http://i.imgur.com/2nEppcv.png

ls -l
drwxr-xr-x  9 777 root 4096 Aug  3 00:25 Cartoons

**Comment by markus101** [comment]
Please use the forums for support.

Check your log files for errors and update Sonarr you're running an old version.

**Comment by godofgrunts** [comment]
I was being retarded anyway. Issue was with directory permissions.
