### ISSUE TITLE
Add REST API Endpoints for ImportList Series Management

### ISSUE THREAD

**Issue by jacksonblankenship** [Sonarr/Sonarr#7230]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, Sonarr lacks REST API endpoints to manage `ImportList` series. This functionality exists in Radarr for managing `ImportListMovies` (via `/api/v3/importlist/movie`), but Sonarr does not provide a similar set of endpoints for series. This gap in the API limits programmatic access to `ImportList` items and prevents automation workflows that rely on managing these series via API calls.

### Describe the solution you'd like

I would like to see REST API endpoints added to Sonarr for `ImportList` series management, similar to Radarr’s existing endpoints for movies. Specifically, the following endpoints should be added:

- **GET /api/v3/importlist/series**: Retrieve all series from the import list.
- **POST /api/v3/importlist/series**: Add series to the import list.

These endpoints would mirror the functionality provided in Radarr’s API for movies (e.g., `/api/v3/importlist/movie`) and allow users to manage series in Sonarr’s import lists programmatically.

### Describe alternatives you've considered

The only current alternative is manually managing import lists via the Sonarr UI. Another potential workaround would be to script interactions with Sonarr’s database directly, but this is risky and not user-friendly. Having these REST API endpoints would make it much easier to automate and integrate with external tools or scripts.

### Anything else?

Here are links to Radarr’s existing API documentation that describes the equivalent functionality for movies:

- [GET /api/v3/importlist/movie](https://radarr.video/docs/api/#/ImportListMovies/get_api_v3_importlist_movie)
- [POST /api/v3/importlist/movie](https://radarr.video/docs/api/#/ImportListMovies/post_api_v3_importlist_movie)

Providing the same functionality in Sonarr would streamline API workflows and align Sonarr’s capabilities with Radarr’s API.

**Comment by markus101** [comment]
This would be added as part of https://github.com/Sonarr/Sonarr/issues/5481
