### ISSUE TITLE
Custom Format - Media Probe Info

### ISSUE THREAD

**Issue by kingy444** [Sonarr/Sonarr#7238]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I dont store the value of the codec in the filename, and dont really want to. But Sonarr does know if a file is x264 or x265 internally.

### Describe the solution you'd like

Have a custom format that can use this internal database data to score your content, and prevent download loops

### Describe alternatives you've considered

putting the codec in the filename, but this doesnt serve much purpose when this can be probed from the media (and is currently)

**Comment by markus101** [comment]
This is part of https://github.com/Sonarr/Sonarr/issues/5598
