### ISSUE TITLE
Ensure Column Header Visibility

### ISSUE THREAD

**Issue by mdstricklin** [Sonarr/Sonarr#7248]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When you scroll down the list, the headers of columns disappear.
![image](https://github.com/user-attachments/assets/9c76155b-aa5a-41e1-ba35-cc2d4963429e)
![image](https://github.com/user-attachments/assets/0a72c31c-3359-4a86-928c-fb9361f50319)

### Describe the solution you'd like

I would like the column headers to stick to the top of the screen as you scroll through the list. Basically, it'd be nice for it to act like the "Freeze Panes" feature in Microsoft Excel.

### Describe alternatives you've considered

No alternatives.

### Anything else?

Thanks for consideration!

**Comment by markus101** [comment]
We've looked into it before (https://github.com/Sonarr/Sonarr/issues/5901), it's not something we're going to commit to doing at this time.

**Comment by mdstricklin** [comment]
Unfortunate, but understandable I suppose. Would love to see it given further consideration in the future! This is a huge QOL improvement, especially when your primary view is as a table and you've got most of the columns selected.
