### ISSUE TITLE
Sonarr won't import when import path has a trailing space in the path

### ISSUE THREAD

**Issue by edrock200** [Sonarr/Sonarr#7251]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Attempting to import a particular item doesn't import. Stays purple in queue, but gives import error in logs/events
Pertinent log error:
[v4.0.9.2421] System.ArgumentException: value [/mnt/imports/torrents/qbit924/Shrimad Ramayan (2024) S01E150-158 1080p WEB-DL x264 AAC 2.0 ESub-JA ]  is not a valid *nix path. paths must start with / (Parameter 'path')

### Expected Behavior

Sees path as valid path and imports, or turns item yellow in queue

### Steps To Reproduce

I'm not sure why it's triggering on just this particular item so I can't say how to reproduce. 

*Edit* Won't import when path has a trailing space

### Environment

```markdown
- OS: Ubuntu 18.04
- Sonarr: 4.0.9.2421
- Docker Install: yes
- Using Reverse Proxy: yes nginx
- Browser: latest Chrome x64 windows
- Database: Sqlite 3.45.3
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.trace.6.txt](https://github.com/user-attachments/files/17158363/sonarr.trace.6.txt)

### Anything else?

Thanks in advance.

**Comment by markus101** [comment]
Looks like there is a trailing space in that path.

**Comment by edrock200** [comment]
Oh interesting. Didn't catch that, thank you. Should that prevent importing though?

**Comment by markus101** [comment]
Nope, just pointing out it doesn't have anything to do with the leading slash, though that's the most common reason.

**Comment by edrock200** [comment]
Thank you @markus101 !
