### ISSUE TITLE
Add 'BEN THE MAN' to list of parseable groups

### ISSUE THREAD

**Issue by VampiricAlien** [Sonarr/Sonarr#7255]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Release group "BEN THE MAN" unable to be parsed due to tag containing spaces in the name "BEN THE MAN".

`S02E05 2160p  WEB-DL DV HDR ENG DDP5.1 Atmos H265 MP4 BEN THE MAN`
`S02E05 2160p  WEB-DL DV HDR ENG DDP5.1 Atmos H265 MP4-BEN THE MAN` This shows BEN as group

If the title contains "mp4-BEN THE MAN" you can use custom formats as BEN is parsed as the release group.

### Describe the solution you'd like

parse release group BEN THE MAN

### Describe alternatives you've considered

Used Custom formats, not successful.

**Comment by markus101** [comment]
Why wouldn’t it be added? The request is for `Ben the Man`, not `Ben the Men`…
