### ISSUE TITLE
Layout/Window settings saved to the application

### ISSUE THREAD

**Issue by ObviousViking** [Sonarr/Sonarr#7261]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The issue is resetting the views, sorting, custom columns etc when accessing sonarr on a new browser.

### Describe the solution you'd like

Id like things such as the series view and custom columns when viewing series (audio languages, subtitle language etc) be saved as a setting in the tool rather than in the cookie 

### Describe alternatives you've considered

There is no other way to do this that im aware of

**Comment by markus101** [comment]
At this time we do not have plans to move these settings to the backend.  It's possible this changes int he future, but not something we're committing to at this time.
