### ISSUE TITLE
[Feature Request] uTorrent change file location

### ISSUE THREAD

**Issue by ChaosTherum** [Sonarr/Sonarr#727]
Would it be possible to set the file location in uTorrent so that once the files have been organized they can still be seeded. I'm not sure if the api has the ability to change the file location but if this could be done that would be great.

**Comment by markus101** [comment]
Sonarr will either copy or hard link (depending on your settings) when the torrent is still seeding. If the torrent has finished it will be moved. We have no plans to move the file and update uTorrent to seed from a new location as hardlinking allows that already.
