### ISSUE TITLE
Can't talk to download client if emoji in firename

### ISSUE THREAD

**Issue by 0xSnib** [Sonarr/Sonarr#7278]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Unable to communicate with Transmission. Cannot combine OsPaths of different platforms ('/shared/Unsorted/TV' + 'American.Dad.S18E01.Who.Smarted.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[TGx]+\u2b50')

The file release is American.Dad.S18E01.Who.Smarted.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[TGx]⭐️

### Expected Behavior

For Sonarr to ignore emojis in releases, to strip/sanitise the emoji when adding the download or to rename it

### Steps To Reproduce

Add a show that has a stupidly named release available for it

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 
- Docker Install: No
- Using Reverse Proxy: Yes (but isn't related)
- Browser: Arc
- Database: 

Version
4.0.9.2244
.NET
Yes (6.0.13)
Database
Sqlite 3.40.1
Database Migration
211
AppData Directory
/var/lib/sonarr
Startup Directory
/opt/Sonarr
Mode
Console
```

### What branch are you running?

Main

### Trace Logs?

Atttached

**Comment by markus101** [comment]
You're missing some critical information here, such as trace logs and what client you're using, but this is the same issue as https://github.com/Sonarr/Sonarr/issues/7270
