### ISSUE TITLE
Allow mass import (and editing / updating) of custom formats from external sources

### ISSUE THREAD

**Issue by zdzielinski** [Sonarr/Sonarr#7283]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The current method for importing custom formats is to copy and paste json content one format at a time. This is incredibly slow if you have any large amount of custom formats to import, such as from the [trash guides collection of custom formats](https://trash-guides.info/Sonarr/sonarr-collection-of-custom-formats/). This problem also extends to editing existing custom formats.

The ability to mass import custom formats at a time would prove extraordinarily useful. Along with this, allowing the easy ability to edit your custom formats (in the case of updates to existing formats from upstream sources) would prove equally as useful.

### Describe the solution you'd like

Allow the import of many custom formats. One possibility is to allow importing ndjson instead of singular json. This would let upstream sites (such as trash guides) post "master lists" of custom formats for users to simply copy and paste. If importing a second time, all existing custom formats should be overridden, allowing the easy updating of existing custom formats from said master lists.

### Describe alternatives you've considered

N/A

**Comment by augustuen** [comment]
I suggest you just go set up Recyclarr or Notifiarr which will sync both custom formats and scores from the TRaSH guide.

**Comment by markus101** [comment]
As mentioned this is possible with Recyclarr or Notifiarr. At this time we do not have plans to implement our own version of that.

**Comment by zdzielinski** [comment]
Ah I missed that! Thank you all, appreciate the guidance.
