### ISSUE TITLE
 Allow mass import (and editing / updating) of quality profile custom format scores

### ISSUE THREAD

**Issue by zdzielinski** [Sonarr/Sonarr#7284]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

[Related issue 7283](https://github.com/Sonarr/Sonarr/issues/7283)

This issue is similar to the above listed issue, so some verbiage is avoided here for duplicity sake.

The concept is similar however, if a user is following a standard guide for custom formats, and scoring those formats thereof; it becomes an arduous task to manually score each format that may be attached to a quality profile. The ability to "import" scores in a similar method to how custom formats are currently imported would be useful.

### Describe the solution you'd like

I envision an import button within a given quality profile that might take json content, which would map custom formats to scores. An upstream provider (such as trash guides) could provide that json as a copy paste document, making the import of standardized scoring much easier. Non existent or duplicate imports should be handled gracefully, as to allow users an individual import experience without much editing or debugging.

### Describe alternatives you've considered

N/A

**Comment by markus101** [comment]
As mentioned on #7283 this is possible with Recyclarr or Notifiarr. At this time we do not have plans to implement our own version of that.
