### ISSUE TITLE
Grabbing wrong torrent in interactive search

### ISSUE THREAD

**Issue by shifoc** [Sonarr/Sonarr#7288]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

![image](https://github.com/user-attachments/assets/dd6262be-4900-4016-bf6d-4da10a8f34e8)
Clicking on the button (add to queue) of the second row is grabbing the one from the first row 

### Expected Behavior

grab the correct torrent

### Environment

```markdown
- OS: Windows 10
- Sonarr: 4.0.9.2513
- Docker Install: no
- Using Reverse Proxy: no
- Browser: Chrome
- Database: Sqlite 3.36.0
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.trace.txt](https://github.com/user-attachments/files/17317322/sonarr.trace.txt)

**Comment by markus101** [comment]
Why do you have the same indexer added multiple times?

Looks like because of the duplication the items end up having the same unique identifier and leads to the wrong one being updated after grabbing.

**Comment by shifoc** [comment]
ok thanks
