### ISSUE TITLE
Add support for Hungarian language in Profiles

### ISSUE THREAD

**Issue by gurabli** [Sonarr/Sonarr#729]
Please add Hungarian language, thanks!

**Comment by markus101** [comment]
What language tags do they use? Just `HUNDUB` and `HUN`?

**Comment by gurabli** [comment]
It is mainly HUN (or Hun) and HUNDUB (or Hundun).
For dual dub it is ENG.HUN.

**Comment by Mirx** [comment]
I tried implementing this in pull request #731
