### ISSUE TITLE
Add an option "disable file rename" in Manual Import wizard

### ISSUE THREAD

**Issue by dausruddin** [Sonarr/Sonarr#7294]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes I just want to use the original file name for some reasons. Doing this on and off from settings is not an ideal solution.

Why I want to rename:
* bad name on the original file
* have some extra information that wasn't on original name, such as codec,  audio channel, etc
* want a consistent naming

Why I don't want to rename:
* keep the history of the file, especially on rare or hard-to-find content
* easier to reuse in another application, such as torrent client in case I want to reseed.
* retain some information which I don't want to have on other files.

### Describe the solution you'd like

Have a switch in Manual Import wizard that allow me to rename or not rename the files.

### Describe alternatives you've considered

Adding a tick box to where checked means rename, and unchecked means don't rename.

**Comment by Thirrian** [comment]
https://github.com/Sonarr/Sonarr/issues?q=is%3Aissue+is%3Aopen+rename+sort%3Aupdated-desc

https://github.com/Sonarr/Sonarr/issues/6484
