### ISSUE TITLE
Check Audio before import

### ISSUE THREAD

**Issue by Hello-World-Traveler** [Sonarr/Sonarr#7298]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

A few downloads was processed by sonarr without audio attached,

### Describe the solution you'd like

Sonarr to check for audio before importing and if audio is not found sonarr doesn't auto import and warns the admin of the error.

### Describe alternatives you've considered

None

**Comment by markus101** [comment]
Was it actually a video file or some sort of junk/spam file?

The ffprobe output that Sonarr had for this at import time would be useful to see exactly what we could compare against.

**Comment by Hello-World-Traveler** [comment]
A video file. I wasn't aware of it having no audio until months later when I want to watch it.

Video was fine but no audio track. There was a proper release days after but settings didn't allow upgrade.

solution:  sonarr checks for video and audio and removes a file if one isn't found.

**Comment by markus101** [comment]
Which release was this?

**Comment by Hello-World-Traveler** [comment]
I mean, when I went back and did a manual search I found that there was a redo file (updated download with both audio and video)

**Comment by markus101** [comment]
Yes, I understand that. I want to know what the release name was so I can check the media information from the file to see if this check would be feasible. Considering how rare this is, it may not be worth the effort at this time.

**Comment by Hello-World-Traveler** [comment]
I don't have that information, best I can give you is 720p AVC and under 400mb, I don't think that is much help.

At the time I did check sonarr for audio, there wasn't any.  Option for minium audio size?
