### ISSUE TITLE
Sonarr not parsing version number from quality

### ISSUE THREAD

**Issue by reese2778** [Sonarr/Sonarr#7302]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr isn't able to parse version number when it's a part of quality. For example when parsing: 
`[MTBB] Mushoku Tensei Jobless Reincarnation (2021) - S02E02 - 027 - The Forest in the Dead of Night [WEBDL-1080p v2][x264][AAC].mkv`
Sonarr doesn't parse the `v2`
![test-parse-version](https://github.com/user-attachments/assets/ab801128-b283-488c-8b0e-8e61ae8bb11b)

### Expected Behavior

Sonarr should parse the version number from the quality, since that's how Sonarr writes it when renaming

### Environment

```markdown
- OS: Unraid
- Sonarr: 4.0.9.2513
- Docker Install: Yes
Using the lscr.io docker image
```

### What branch are you running?

Develop

### Trace Logs?

[log](https://gist.github.com/reese2778/68a97b93313116b7653f64759b5ae9e7)

**Comment by thezoggy** [comment]
it doesnt look like thats even a valid release name by a group.. as mtbb does something like `[MTBB] Mushoku Tensei S2 - 14 (WEB 1080p) [8279A57D]`. so this is something your doing manually with your naming scheme?

**Comment by bakerboy448** [comment]
Sonarr's naming would not output `WEBDL-1080p v2` either it'd be PROPER not v2

**Comment by reese2778** [comment]
> it doesnt look like thats even a valid release name by a group.. as mtbb does something like `[MTBB] Mushoku Tensei S2 - 02v2 (WEB 1080p) [C1246C07]`. which is parsed correctly.
> 
> so this is something your doing manually with your naming scheme? can you share your naming scheme?

This is after being renamed by Sonarr, I meant to specify that, my bad.
Here's my anime naming format `{[ReleaseGroup] }{Series TitleYear} - S{season:00}E{episode:00} - {absolute:000} - {Episode CleanTitle} [{Custom Format:Uncensored }{Custom Formats:-Uncensored }{Quality Full}]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec}]`

**Comment by reese2778** [comment]
> Sonarr's naming would not output `WEBDL-1080p v2` either it'd be PROPER not v2

Sonarr does output that, when importing a file labeled as v2, however it seems to only properly parse the v2 when it's included as part of the episode number, like `S02E02v2`. Which results in it not being able to parse version from files it's renamed
