### ISSUE TITLE
Typo bug in custom format sonarr for the parameter size

### ISSUE THREAD

**Issue by Sad1que** [Sonarr/Sonarr#7307]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Typo bug in custom format sonarr for the parameter size. 

![image](https://github.com/user-attachments/assets/926323d0-17ee-478f-bb50-b8d1c673384d)

### Expected Behavior

It should be written "Taille minimum" instead of "Taille maximum" (in french at least)

### Steps To Reproduce

Change language to french in Sonarr. Go to custom format and create a new one. Select the size parameter

### Environment

```markdown
- OS: Windows server 2022 
- Sonarr: 4.0.9.2244 - 26/08/2024
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Firerox
- Database: Sqlite 3.36.0
```

### What branch are you running?

Main

### Trace Logs?

N/A

**Comment by stevietv** [comment]
Translations are user supplied and can be edited here: https://translate.servarr.com
All contributions there are welcome!
