### ISSUE TITLE
##x## search doesn't work at series level (and hence at show level). Only works per episode.

### ISSUE THREAD

**Issue by KaiStarkk** [Sonarr/Sonarr#7309]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The title format `##x##` (e.g. `04x19` for season 4, episode 19) was common in the late 2000s.

For some reason these are working when searched at the episode level, but the search at the series (and hence show) level, does not work. I've double checked to make sure I didn't have the 'season pack' filter set.

### Expected Behavior

Standard series should search for S##E## as well as ##x##

### Environment

```markdown
- OS: Debian Linux
- Sonarr: 4.0.9.2244
- Docker Install: No
- Using Reverse Proxy: Yes (tested both)
- Browser: Tested Chrome and FF
- Database: Default
```

### What branch are you running?

Main

### Trace Logs?

The attached trace demonstrates a search at show level, series level, and then individual episode level. Items only are found when searching by episode.
[sonarr.trace.txt](https://github.com/user-attachments/files/17444423/sonarr.trace.txt)

**Comment by stevietv** [comment]
As you can see here, Sonarr does not search by SxxExx format, but by parameterised searches, the naming is not relevant:

Season Search:

`2024-10-19 16:36:37.9|Trace|HttpClient|Res: HTTP/2.0 [GET] https://prowlarr.kai.systems/4/api?t=tvsearch&cat=5050,5040,5045&extended=1&apikey=(removed)&offset=0&limit=100&q=Vanderpump%20Rules&season=11: 200.OK (268 bytes) (44 ms)`

Episode Search: 

`2024-10-19 16:37:08.1|Trace|HttpClient|Res: HTTP/2.0 [GET] https://prowlarr.kai.systems/4/api?t=tvsearch&cat=5050,5040,5045&extended=1&apikey=(removed)&offset=0&limit=100&q=Vanderpump%20Rules&season=11&ep=19: 200.OK (21738 bytes) (879 ms)`

The episode search is returning results that the season search is not, that means your indexer is not returning the results for the individual episodes in a season search.
I also noted in your trace that your season searches only went to one indexer and the individual episode search went to two indexers so you may have configured something strangely.

Anyway, Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by KaiStarkk** [comment]
Thanks noted. I've removed the trace now, if you wouldn't mind also please removing the domain from the quote (if possible)
