### ISSUE TITLE
UI affordance for "Monitor New"

### ISSUE THREAD

**Issue by KaiStarkk** [Sonarr/Sonarr#7311]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The setting "Monitor New Items" is very useful, and is something I think most people enable when "up-to-date" on a show.
By contrast, when still catching up on a show that is ongoing (e.g. watching Season 3, but the latest is Season 9), it seems common to have this flag turned off -- however "Monitored" is still set on, so that Sonarr finds the series you're currently looking for (e.g. getting Season 4 ready).

It would be great to have an affordance for this existing setting.

### Describe the solution you'd like

The best place would be the table view on the Series dashboard.

Mockup example:

![image](https://github.com/user-attachments/assets/4bbedc40-a477-4e33-9b30-26db28d2d0cf)

(Icons based on [nounproject/upcoming-6208922](https://thenounproject.com/icon/upcoming-6208922/))

### Describe alternatives you've considered

The alternative is to use Unmonitored/Monitored status to organize series, but this misses out on leveraging the existing flag.

**Comment by markus101** [comment]
I've explored some options on iconography for this, but opted for a new column that will show it.
