### ISSUE TITLE
Video file does not import from SABNZBD if destination folder in Video Library contains an apostrophe

### ISSUE THREAD

**Issue by Frono** [Sonarr/Sonarr#7312]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I get log failure of permissions issue in destination directory if the destination directory has an apostrophe.

EX.  /Video/Ned's Burgers

I will get a permission error like:
System.UnauthorizedAccessException: Access to the path '/Video/Ned's Burgers/Season 03/Ned's Burgers - S03E99 - Wattaburger -1080p.mkv' is denied.

When I changed the name of the library to /Video/Neds Burgers and changed the name of the directory on the Video drive the existing SABNZBD file imported without issue...

I'm guessing the extra ticks inside the path are making it fail...

### Expected Behavior

It appears the searcher is trying to import the filename in ticks, with a tick in the center of the filename so.

### Steps To Reproduce

See above

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.9.2244
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Various
- Database:
```

### What branch are you running?

Main

### Trace Logs?

let me know if these are still needed. it is pretty reproducable. I can change the names back and run them if necessary.

**Comment by bakerboy448** [comment]
Trace logs are required not optional....

**Comment by Frono** [comment]
It is odd. After Telling Sonarr to rename the home directory for the show (removing the apostrophe) and at the next prompt telling it I would rename my own files. Then manually removing the apostrophe from the show directory on the unix mounted cifs share. It imported the show from SABNZBD, but instead of adding it to the new directory without the apostrophe, It recreated the show directory with the apostrophe/season XX/showfile(also with apostrophe in show file title). So it seems to fail a pre-write test if there is a show folder with an apostrophe in it. Which if the directory/file string in the error message above is entirely contained within apostrophe's an extra unescaped apostrophe or two in the middle of the string could definitely be a problem. However, it appears one that may be addressed in the actual file move code, as it did create the directories with the apostrophes intact on move...   It appears the trap for file copy error is failing, but the copy itself doesn't...

**Comment by Frono** [comment]
> What filesystem do you use?
> 
> You need to share trace logs as per the [guide here](https://wiki.servarr.com/sonarr/troubleshooting#logging-and-log-files) so the devs can see more about the error than `UnauthorizedAccessException`.
> 
> Feel free to redact any sensitive data before posting.

CIFS share from Linux file server, Sonarr is on an Ubuntu 22.04 platform.
I'd included the entire log error line, but did not include the rest of the details. I've included them now. Hope it helps. Now that I know the idiosyncracy in the code I can fix any others via manual workaround. I was just trying to let y'all know about the issue as it creeps up reasonably often, causing manual imports. I'm guessing that the original libraries created by Medusa didn't care. When I moved to sonarr, it appears to have imported the libraries, but the file creation test does not like the extra characters.

**Comment by bakerboy448** [comment]
Those are not the trace logs the guide requires.

Is NOBRL enabled for the share as noted as being required in the FAQ and QuickStart?

**Comment by markus101** [comment]
Closing as there are unanswered questions and we are unable to replicate, if you have additional questions, please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr).
