### ISSUE TITLE
Improve Deluge Client API Usage

### ISSUE THREAD

**Issue by zakkarry** [Sonarr/Sonarr#7318]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Missing functionality and API Usage improvements for Deluge's client implementation

### Describe the solution you'd like

1. https://github.com/Sonarr/Sonarr/blob/86446a768627b98909389eac230720fcd00cb127/src/NzbDrone.Core/Download/Clients/Deluge/DelugeProxy.cs#L52-L73

You can use {"method":"system.listMethods","params":[],"id":0} even when unauthenticated to the web daemon to get the available methods. By doing this, you can check for daemon.get_version or daemon.info, and determine the version without a failing RPC call.
Should assume 2.x as 1.x has not been updated at all recently, and should not even be used. Whether this is removed/deprecated is up to the team to decide. Some seedbox providers only provide 1.x, unfortunately, but should definitely not be doing this for a variety of reasons.

This can also be used to determine if label.* methods are available, rather than listing the plugins outright, I don't see any other reason why plugin listing is used.

Return is a string[] with methods listed (core.* daemon.* label.* web.* etc)

2. https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs#L215-L246

Assumes that the label is the only source for move_completed_path to be set, this can be set globally as well.

Using web.get_torrent_status will return an JSON object in result, this will return that torrents specific move_completed_path and move_completed values.

Relying on the label for this alone is not reliable, and for specific torrent information, web.get_torrent_status can give specifics, which after being stored
do not need to be polled for repeatedly. 

state will be "Moving" upon completion and once finished will return to "Seeding" or "Paused" depending on add_paused settings.

3. ~~https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs#L168-L188~~

~~https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/Clients/Deluge/DelugeTorrentStatus.cs~~

~~State of "Moving" should be accounted for and treated as "Downloading" perhaps - as this state, in my opinion, should not start an import until complete~~

4. https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs#L132-L142

This error would often be associated with a desync of the web daemon/plugin and the RPC daemon. Simply reconnecting the WebUI to the RPC daemon will remedy this.

Issuing a web.disconnect and then https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/Clients/Deluge/DelugeProxy.cs#L353 calling this should fix the issue.

We experienced this with cross-seed, and I wrote a script to accomplish a simple reconnect.

5. https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs#L38-L55

Using this https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/Clients/Deluge/DelugeProxy.cs#L176

label.get_labels can be used to get all current labels. If a label is missing it can be added back. an error for "Unknown Label" will return RPC_FAIL - ("code: 4" where a bad method will return "code: 2") 
<hr>
To summarize the reasoning behind these changes:

1. isnt really critical, but would be a better approach - avoids relying on failures to get version information
2. definitely would be better and more comprehensive way to do this - default completed paths can be set globally, this currently does not address that
3. ~~needs to be done for 2 to work properly - "Moving" state is currently not accounted for at all.~~
4. this was something @markus101 and I spoke about before, there is a function you could extract for connecting the web daemon, just needs web.disconnect for these errors to "fix" themselves
5. would just result in less errors and more concise logging as to issues, i think this would then only happen if label plugin was unloaded from deluge after startup?

### Describe alternatives you've considered

N/A

### Anything else?

If any assistance is needed in testing or API usage, examples or responses, I can help with that. Just let me know here or on Discord.

**Comment by markus101** [comment]
2. This method is not operating on a specific torrent and already takes global settings into account, I don't think there is anything extra to do here
5. That would require labels to be cached or fetched each time a torrent is added, if a label is present when tested then fails later because it was removed then I think the error is appropriate.

**Comment by zakkarry** [comment]
2. Perhaps I'm mistaken, but I read it as it checks the global settings first, and then in an else if checks the label. This means if global settings are present, label settings that would override the global settings per torrent/label would never be checked and set?

5. If checking present labels everytime a torrent is added is too often for your liking, I would suggest perhaps maybe checking only at startup or during the health check task? Either way it's a pretty trivial API call, and low cost even if you did it everytime. This is somewhat edge-case anyway as you shouldn't expect a user to delete the label used, but also don't want it to break importing if they do so.

**Comment by markus101** [comment]
2 - It checks Sonarr's internal settings (that are applied to the torrent), then the label and finally the global settings, so we should be good there.

5 - If they do delete the label then the import will still succeed, it just won't be moved from the initial category. Checking that the correct categories exist in a health check would be a little more involved, I'm going to skip this for now and see about adding it later.

**Comment by zakkarry** [comment]
Alright, thanks for the clarification. Both sounds fair.

**Comment by zakkarry** [comment]
Looking at the commit you just referenced [here](https://github.com/Sonarr/Sonarr/commit/0c4d796e9aba4ac351d08dcba74e272541f68655#diff-c1d1da8fa869931de1ec0a7e8224c2c472d8e7f9d17962c7f0b8d5a541c940a9R199-R201) - What do you think of reconnecting the daemon silently, and only if the bad torrents persist after reconnecting warning?

In all likelihood, the reconnect will resolve these issues. It would take a special kind of messed-up torrent to trigger this otherwise. Although I must admit you are far more experienced in the shit torrents users can report than me, even with cross-seed taken into account.

Alternative perspective, if this reconnect occurs after ignoring, and then the torrents are resolved, if this error then disappears that would accomplish mostly the same effect - although if the user saw it before it refreshed the queue and resolved it could send a new user down a rabbit hole perhaps?

Not entirely sure, just some thoughts. As I've told you I'm not familiar with the codebase or that versed in C#. If I'm sounding a fool just ignore me :D

**Comment by markus101** [comment]
I did consider that, but with it being a warning and if it's fixed automatically it should be pretty infrequent. If it's not fixed automatically then Sonarr would either need to know if it happened previously or continue to retry.

I did change it a bit:
- Skip it warning the first time it happens
- Only try reconnecting if it hasn't tried previously
- Updated the logging a bit to explain the issue better and indicate repeated failures are a concern
- Resets after successful checks, so it can try reconnecting again in the future and adjust the logging

With these changes it wont try to spam reconnect and won't log if the reconnect is successful (so someone doesn't chase an already resolved problem) and won't have to reprocess items multiple times in a single refresh.

**Comment by zakkarry** [comment]
That was going to be my followup concern after you replied with your thoughts on the reconnecting behavior, we had previously discussed the session deleting but I'm not sure I included it here now that I double-checked my OP.

Upon exiting or reconnecting, the following command should be sent to remove latent sessions from persisting.

auth.delete_session

Accepts an empty array, similar to other non param accepting RPC calls.

You can see my usage [here](https://github.com/zakkarry/deluge-mover/blob/master/deluge-mover.py#L321-L322)
