### ISSUE TITLE
Ignore sizes for specific indexers

### ISSUE THREAD

**Issue by frbuccoliero** [Sonarr/Sonarr#7320]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some indexers I use don't return a correct file size (but a fixed 512MB), this results in Sonarr skipping them for not respecting the format minimum size.

### Describe the solution you'd like

I'd like to have a toggle in indexer card to disable file size checks for items coming from that indexer.

### Describe alternatives you've considered

Alternatives include manually turning lowering the minimum size for THAT specific quality profile, but it's not a viable solution generally because the items might be of any quality profile.

**Comment by markus101** [comment]
This something indexers should resolve and not some thing we're going to commit to doing.
