### ISSUE TITLE
Have the calendar show episodes further into the future.

### ISSUE THREAD

**Issue by arcticfoxwpg** [Sonarr/Sonarr#7337]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It looks like the calendar only shows around 3 weeks in the future, so I have to go to Trakt which shows several months.

### Describe the solution you'd like

Have the calendar show episodes further into the future like Trakt.

### Describe alternatives you've considered

N/A

**Comment by markus101** [comment]
The calendar shows whatever information is available from TheTVDB, the information will need to be added there to show up.
