### ISSUE TITLE
Language support for Series Title

### ISSUE THREAD

**Issue by yy306525121** [Sonarr/Sonarr#7342]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

in series list page and media management page, title can not support convert chinese

### Describe the solution you'd like

like radarr support {Movie CleanTitle:CN}

### Describe alternatives you've considered

like radarr support {Movie CleanTitle:CN}

**Comment by markus101** [comment]
>  I have searched the existing open and closed issues

You didn't even need to search, you just needed to look at the first issue as it was currently at the top.

https://github.com/Sonarr/Sonarr/issues/269
