### ISSUE TITLE
Download theme music for Kodi/Jellyfin

### ISSUE THREAD

**Issue by ColinHebert** [Sonarr/Sonarr#7349]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This is similar to #5030

Currently when using Jellyfin, themes can be downloaded with the [Jellyfin-plugin-theme](https://github.com/danieladov/jellyfin-plugin-themesongs/), **which uses TVDB's** ID to download the MP3:

```c#
var tvdb = serie.GetProviderId(MetadataProvider.Tvdb);
var themeSongPath = Path.Join(serie.Path, "theme.mp3");
var link = $"http://tvthemes.plexapp.com/{tvdb}.mp3";
using var client = new WebClient();
client.DownloadFile(link, themeSongPath);
````

### Describe the solution you'd like

Ideally Sonarr would manage that bit of metadata, similarly to the thumbnails, etc.

### Describe alternatives you've considered

The plugin I've mentionned does the trick. Though I prefer for Sonarr to be the only program that manages my media library, other tools have read-only access.

If Sonarr can handle the theme song, then [Jellyfin](https://jellyfin.org/docs/general/server/media/shows#theme-music), [Plex](https://support.plex.tv/articles/200220717-local-media-assets-tv-shows/#toc-3), [Emby](https://emby.media/support/articles/Theme-Songs-Videos.html), and some custom themes on [Kodi](https://kodi.wiki/view/Add-on:Check_MP3_Theme) all benefit from it.

**Comment by augustuen** [comment]
This is well beyond the scope of Sonarr, and probably won't happen for many years (if ever)

**Comment by ColinHebert** [comment]
I can see that line of thinking, though how is it different from the other types of metadata-media sonarr already handles (poster, fanart, banner)?

**Comment by markus101** [comment]
The difference is that metadata is already available to Sonarr, theme music is not.

this isn’t something we’re going to implement in the foreseeable future.
