### ISSUE TITLE
Interactive search from dashboard.

### ISSUE THREAD

**Issue by KaiStarkk** [Sonarr/Sonarr#7350]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When needing to manually search a number of titles, it requires navigating in and out of each series.

### Describe the solution you'd like

It would be preferable to have the interactive search button on the dashboard as an option, e.g.:

![image](https://github.com/user-attachments/assets/eca4a5e7-95db-4b54-a743-cd001bfb35ef)

Allowing for something like this on the table view:

![image](https://github.com/user-attachments/assets/b47cbee4-5e94-45fd-a953-0564b75c238f)

### Describe alternatives you've considered

The current workaround is to open in multiple tabs and work through them manually.

**Comment by stevietv** [comment]
we don't have an interactive search button for series level, only for season level.

**Comment by markus101** [comment]
As Stevie said this is not something we have implemented and is not something we’re going to add.
