### ISSUE TITLE
Initial State there is no Stop option

### ISSUE THREAD

**Issue by luizfeliperc** [Sonarr/Sonarr#7353]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

qBittorrent version 5.x.x has disabled the option to pause torrents in the seeding limits window. As a result, Sonarr lost the option to start the paused torrent.
Every torrent that passes through sonarr will start automatically as there is no pause option in qbittorrent

![image](https://github.com/user-attachments/assets/61a683bd-cba2-4bf9-9408-1ab618179169)
![image](https://github.com/user-attachments/assets/58f5f10f-1e6a-4df9-8edc-45f912bdde1b)

### Describe the solution you'd like

Include the stop torrent option in Initial State, or change it like Radarr instead, removing the pause option and leaving only start, force start and stop.

### Describe alternatives you've considered

Include the stop torrent option in Initial State, or change it like Radarr instead, removing the pause option and leaving only start, force start and stop.

**Comment by PearsonFlyer** [comment]
Are you running the latest develop version of Sonarr?

**Comment by luizfeliperc** [comment]
> Are you running the latest develop version of Sonarr?

![image](https://github.com/user-attachments/assets/0ce105e5-74f7-4cfa-83e4-1adcb6424b22)

**Comment by bakerboy448** [comment]
You have trace logs of this not working or are only assuming based on the UI?

https://github.com/Sonarr/Sonarr/pull/7313

**Comment by markus101** [comment]
Either downgrade to bit 4.x and wait for this to hit main or switch to develop builds.

**Comment by luizfeliperc** [comment]
I use Ultra.CC services and their latest update is 4.0.10.2544

Thanks guys, I'll get in touch with Ultra and see if they can make the latest version available for update
