### ISSUE TITLE
Non-existing release group added to parsing

### ISSUE THREAD

**Issue by planetrocky** [Sonarr/Sonarr#7365]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Does not parse the release group "BEN THE MEN"

### Expected Behavior

Parse the release group "BEN THE MEN"

### Steps To Reproduce

#7255 caused the fault

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.10.2544-ls258
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Brave
- Database: Postgres
```

### What branch are you running?

Main

### Trace Logs?

#7255 introduced this bug

### Anything else?

#7255 introduced this bug

**Comment by markus101** [comment]
If you’d like to make a feature request please choose and fill out the correct template.

All requested information must be provided, links to other issues are not logs.

**Comment by markus101** [comment]
Example posted in original issue https://github.com/Sonarr/Sonarr/issues/7255#issuecomment-2456260330
