### ISSUE TITLE
Improve Sabnzbd History Retention Checking - Support Checking for Remove to Archive and Max Count Options

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#7373]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

https://github.com/Sonarr/Sonarr/blob/4e9ef57e3d8c923f765b3337279a0cf4e93d6068/src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs#L281-L296

Previously we only check for deleting and retaining for X days. If users archive or remove after X jobs it appears no warning is indicated to the Sonarr user nor a healthcheck

Appears this likely no longer functions with Sab 4.3's changes to retention as the api has materially changed

partial excerpt from logs
```
history_retention":"","history_retention_option":"all-delete","history_retention_number":1
```

### Describe the solution you'd like

Sonarr should 1) fail download client validation and 2) throw a healthcheck for archival as well not only removals

![image](https://github.com/user-attachments/assets/63437898-cd36-41ab-be34-81316e153f3d)

### Describe alternatives you've considered

User error and having the download client removing downloads without any warning or notice in Sonarr

### Anything else?

https://discord.com/channels/492590071455940612/1304087206972882944

**Comment by markus101** [comment]
So `history_retention` is gone and replaced with two different options, yay, breaking API changes...
