### ISSUE TITLE
Show Series Title Above The Poster In The UI.

### ISSUE THREAD

**Issue by AziRizvi** [Sonarr/Sonarr#7379]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

In Sonarr we have the ability to display the series title under the poster, can an option please be implemented to display the series title above the poster and make the title text a little bolder like you can see in the image below?

![brave_FVkN8Spl4g](https://github.com/user-attachments/assets/ad49b4f5-5971-40d5-8a83-ae056a8a058b)

### Describe the solution you'd like

An option to display the series title above the poster in the UI and a secondary option to make the series title text a little bolder to make it stand-out.

Thank you!

### Describe alternatives you've considered

I've considered writing a ViolentMonkey script to modify the text property and have it displayed in the style and manner I want but that would be less than efficient, a native option to do this would be much better and make the UI more customizable I guess.

**Comment by markus101** [comment]
Not something we’re going to commit to doing at this time, if someone is interested in opening a PR then we would review it.
