### ISSUE TITLE
Add "Manual Import" Button to [Series] Page (Same as Radarr has)

### ISSUE THREAD

**Issue by damnsanga** [Sonarr/Sonarr#7380]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It would be handy if a "Manual Import" button could be added to the top of the [Series] Page.

Radarr has a similar feature on its equivalent [Movie] Page

### Describe the solution you'd like

On the WebUI, add a "Manual Import" Button to the top menu of the [Series] Page

### Describe alternatives you've considered

.

### Anything else?

.

**Comment by bakerboy448** [comment]
Isn't this the same Manage Episodes?

**Comment by markus101** [comment]
I assume they mean at the top of the series list, we've talked about adding it before, but between other differences in Sonarr and Radarr and what we already show there it's not something we're have plans to add at this time.
