### ISSUE TITLE
Send Instance Name in Notifications (Pushover)

### ISSUE THREAD

**Issue by 0x0054** [Sonarr/Sonarr#7391]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have multiple instances of Sonarr running: Normal, Anime and HDR. I'm using Pushover to send notifications and currently have 3 pushover apps for normal notifications and 3 for emergency notifications (which have a different priority and aren't silent). I have to use this because in the notifications send by Sonarr there is no way to know which instance is sending the notifications.

### Describe the solution you'd like

A toggle in the notification (connect) settings that sends the instance name with the regular title. So for example instead of this:
`Episode Downloaded
From Sonarr on 2024-12-31 at 16:35
Series Name - 1x01 - Episode Title [WEBDL-1080p]`

After the toggle it would send this:
`SonarrAnime - Episode Downloaded
From Sonarr on 2024-12-31 at 16:35
Series Name - 1x01 - Episode Title [WEBDL-1080p]`

Where `SonarrAnime` is my instance name.

In the title of the notification would work best I think, because then you can easily see which instance it came from even if you only see the title (ie in phone notifications).

### Describe alternatives you've considered

Like I mentioned above I'm currently using multiple Pushover "apps" (which are basically channels) for each instance. I'm not sure if there is another simple alternative other than just sending the instance name with the regular title of the notification.

### Anything else?

I titled this request with Pushover because I'm using that but I think this could also be useful for other notification channels, ie Telegram, ntfy.sh etc.

**Comment by markus101** [comment]
This would fall under https://github.com/Sonarr/Sonarr/issues/328
