### ISSUE TITLE
Include additional data with failed commands

### ISSUE THREAD

**Issue by kingy444** [Sonarr/Sonarr#7398]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I am currently doing pre-processing on video files and trying to move the sorting into Sonarr. I ran into a problem where the file refused to sort.

Enabling debug settings advised why but the json return is not so helpful

```
2024-11-20 07:38:13.2|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Not an upgrade for existing episode file(s). Existing quality: WEBDL-720p. New Quality HDTV-720p.
2024-11-20 07:38:13.2|Debug|DownloadedEpisodesCommandService|Failed to import
```

```json
{
    "name":  "DownloadedEpisodesScan",
    "commandName":  "Downloaded Episodes Scan",
    "message":  "Failed to import",
    "body":  {
                 "path":  "****",
                 "importMode":  "move",
                 "requiresDiskAccess":  true,
                 "isLongRunning":  true,
                 "sendUpdatesToClient":  true,
                 "updateScheduledTask":  true,
                 "isExclusive":  false,
                 "name":  "DownloadedEpisodesScan",
                 "trigger":  "manual",
                 "suppressMessages":  true
             },
    "priority":  "normal",
    "status":  "completed",
    "result":  "unsuccessful",
    "queued":  "2024-11-20T22:43:36Z",
    "started":  "2024-11-20T22:43:36Z",
    "ended":  "2024-11-20T22:43:36Z",
    "duration":  "00:00:00.1637925",
    "trigger":  "manual",
    "stateChangeTime":  "2024-11-20T22:43:36Z",
    "sendUpdatesToClient":  true,
    "updateScheduledTask":  true,
    "id":  765286
}
```

### Describe the solution you'd like

There are 2 seperate things i would like to request to improve what happens here
1. Add the reasoning of the failure (ImportDecisionMaker) to the output of the API message so you can tell why the import failed. 

I'm indifferent about how, but personally maybe a new field for `extendedMessage` or similar that could be used for other information that is useful to the end user (in other api calls) without affecting other services that may simple check for `Failed to import` as the error message 

2. Add an additional field to the api call to enable a `forced` import - which would ignore all logic and overwrite existing files

### Describe alternatives you've considered

Making additional calls to the library to determine if the file exists myself and then deleting the file via those methods. I think the above is cleaner as it enables Sonarr to still apply its logic by default

**Comment by markus101** [comment]
1. This may be hard to achieve since it comes from logging alone.
2. Definitely not happening with this task, if you want to force something to overwrite despite being a lesser quality use Manual Import

**Comment by kingy444** [comment]
thankd for the quick response - main reason for 2 was so that 1 could be captured and then a decision made (in my own script) whether to do the import again based on the error output
Ill take a look at manual Import - assume i can achieve the same with that endpoint

**Comment by markus101** [comment]
At this time we're not going to extend the response to include additional information for failed tasks. If you want to have better tracking of imports the Manual Import end points would be better and as mentioned allow overwriting of existing files even if the file to be imported is not an upgrade.
