### ISSUE TITLE
Activity queue doesn't clear

### ISSUE THREAD

**Issue by alvitali** [Sonarr/Sonarr#7399]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Certain files are stuck in the activity queue after having been imported, with the error:
 
`One or more episodes expected in this release were not imported or missing from the release

Smiling.Friends.S01E01.1080p.WEBRip.x265-RARBG.mp4
Episode file already imported at 11/21/2024 06:27:12
Smiling.Friends.S01E02.1080p.WEBRip.x265-RARBG.mp4
Episode file already imported at 11/21/2024 06:27:13
Smiling.Friends.S01E03.1080p.WEBRip.x265-RARBG.mp4
Episode file already imported at 11/21/2024 06:27:14
Smiling.Friends.S01E04.1080p.WEBRip.x265-RARBG.mp4
Episode file already imported at 11/21/2024 06:27:15
Smiling.Friends.S01E05.1080p.WEBRip.x265-RARBG.mp4
Episode file already imported at 11/21/2024 06:27:16
Smiling.Friends.S01E06.1080p.WEBRip.x265-RARBG.mp4
Episode file already imported at 11/21/2024 06:27:17
Smiling.Friends.S01E07.1080p.WEBRip.x265-RARBG.mp4
Episode file already imported at 11/21/2024 06:27:18
Smiling.Friends.S01E08.1080p.WEBRip.x265-RARBG.mp4
Episode file already imported at 11/21/2024 06:27:19`

These exact files were already imported (multiple times by now), however they still show up in the activity queue. This is the case for several seasons of my tv shows.

### Expected Behavior

Clearing the activity queue after importing the files, and not having them show up after the successful import

### Environment

```markdown
- OS: Debian 12
- Sonarr: Sonarr 4.0.10.2544
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: -
- Database: Sqlite 3.45.3
```

### What branch are you running?

Main

### Trace Logs?

Trace logs from trying to re-import the files again:

[sonarr.trace.txt](https://github.com/user-attachments/files/17840593/sonarr.trace.txt)

### Anything else?

Trace logs reported for one of the affected files"
`2024-11-21 06:53:06.2|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Episode file already imported at 03/12/2024 05:36:58`

<img width="1286" alt="Screenshot 2024-11-21 at 06 45 09" src="https://github.com/user-attachments/assets/9bd1e182-ca07-44c7-87cb-5055d6443b4c">

<img width="1286" alt="Screenshot 2024-11-21 at 06 48 39" src="https://github.com/user-attachments/assets/316e88a9-e3e8-4a1b-bf11-dd01339ca5a2">

**Comment by stevietv** [comment]
Indeed, there is no episode file for S01E09 in that release, so its not a complete season pack.
