### ISSUE TITLE
Address already in use. This can happen if another instance of Sonarr is already running another application is using the same port (default: 8989) or the user has insufficient permissions

### ISSUE THREAD

**Issue by ezraholm50** [Sonarr/Sonarr#740]
Hey guys i searched for this in other issues but could not find any, im sorry if there is another issue. Awsome application sonarr i love it! Works great, im fine tuning it right now, but i keep getting this error

Address already in use. This can happen if another instance of Sonarr is already running another application is using the same port (default: 8989) or the user has insufficient permissions

There is no other instance running, port set to 8888, no other app running on that one. Which files should have which permissions? Cause i cant recall having issues with permissions other then with the storage location.

Version
    2.0.0.3357
Mono Version
    3.10.0 (tarball Wed Nov 5 12:50:04 UTC 2014)
Ubuntu
    14.04

Thanks alot, kind regards,

Ezra

**Comment by markus101** [comment]
Please use our forums for support.

You could try running as root to see if you're able to launch it that way. If you open a thread on the forums with logs of the startup process we may be able to help further.
