### ISSUE TITLE
Add Mid-season and Season Finale Indicators to Calendar

### ISSUE THREAD

**Issue by tldm-gh** [Sonarr/Sonarr#7404]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

There exists an icon in the calendar to indicate a season premier, I think adding in additional symbols to the calendar to indicate season breaks/season final would be great addition.
![image](https://github.com/user-attachments/assets/370ebce9-5922-42ab-a881-2e547f255966)

### Describe the solution you'd like

Mid season finale (Pause symbol) 
Season finale (Stop Symbol)
Series finale (checkered flag or something)

### Describe alternatives you've considered

n/a

**Comment by stevietv** [comment]
Series and season finale already exists, press the options at top right

**Comment by tldm-gh** [comment]
> Series and season finale already exists, press the options at top right

Thank you, I had a good look in the general settings, but missed this settings menu.
