### ISSUE TITLE
Scan series from calendar

### ISSUE THREAD

**Issue by tldm-gh** [Sonarr/Sonarr#7405]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

First up, I don't use Sonarr to source files, I handle all that externally, Sonarr is just used to keep track of what is new/missing.

Now sonar runs periodically scans on the directory where the files are stored, but more often that not, when I view the calender it hasn't scanned the directory yet for the days episodes that have been added so they show up as missing.

Now I can manually open each series and refresh and scan, but this can be quite time consuming.

### Describe the solution you'd like

I'd really like a button in the calendar (for each episode instance) that I press to rescan for that episode 
![image](https://github.com/user-attachments/assets/f570c78f-e47a-490f-9378-d33251c4e47f)

### Describe alternatives you've considered

Refresh button could also be in the more details tab for each episode

**Comment by stevietv** [comment]
If you're not using Sonarr for its intended purpose, then maybe you should consider just pressing Update All on the top of the Series page before viewing your calendar

**Comment by tldm-gh** [comment]
> If you're not using Sonarr for its intended purpose, then maybe you should consider just pressing Update All on the top of the Series page before viewing your calendar

With a large library, a full scan can time quite a considerable time.
