### ISSUE TITLE
Customize search keyword language and format

### ISSUE THREAD

**Issue by ryanrain2016** [Sonarr/Sonarr#7406]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some indexers have non-standard naming conventions for episode numbers, using local languages for naming, or omitting season numbers for single season episodes. For example, using a Chinese indexer to name S01EP01 as [第1集]. Or the name only includes the local language of the series, without English. In this situation, Sonarr is unable to retrieve the corresponding episode，even if there BE the exactly wanted episodes there. Being able to customize the naming format of search keywords can effectively solve this problem. Using placeholders for season and episode numbers to customize search keywords, instead of using fixed S01EP01 for retrieval, can effectively improve retrieval capabilities.

### Describe the solution you'd like

Maybe a config for the indexer named Customize search keyword provided. eg: 第{episode:00}集。And a search language selection for the name of the episodes.

### Describe alternatives you've considered

when searching for the episodes with an indexer. Read the name of episodes in selected language and format the keyword before send to indexer.

**Comment by markus101** [comment]
Bogdan is correct this is something that should be done in Prowlarr/Jackett definitions, we do not currently have plans to add customization to queries in Sonarr.
