### ISSUE TITLE
/opt/NzbDrone/Microsoft.AspNet.SignalR.Core.dll Warning : 0 : SignalR exception thrown by Task: System.AggregateException: One or more errors occurred ---> 

### ISSUE THREAD

**Issue by ezraholm50** [Sonarr/Sonarr#741]
/opt/NzbDrone/Microsoft.AspNet.SignalR.Core.dll Warning : 0 : SignalR exception thrown by Task: System.AggregateException: One or more errors occurred ---> System.ObjectDisposedException: The object was used after being disposed. at System.Net.ResponseStream.Write (System.Byte[] buffer, Int32 offset, Int32 count) [0x00000] in <filename unknown>:0 at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write (System.Byte[] buffer, Int32 offset, Int32 count) [0x00000] in <filename unknown>:0 --- End of inner exception stack trace --- --> (Inner exception 0) System.ObjectDisposedException: The object was used after being disposed. at System.Net.ResponseStream.Write (System.Byte[] buffer, Int32 offset, Int32 count) [0x00000] in <filename unknown>:0 at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write (System.Byte[] buffer, Int32 offset, Int32 count) [0x00000] in <filename unknown>:0 

Version
    2.0.0.3357
Mono Version
    3.10.0 (tarball Wed Nov 5 12:50:04 UTC 2014)
Ubuntu
    14.04

Anyone knows how to get rid of this?
Sonarr also seems to shutdown very often so i just set a cron job every 30 mins to run it... pretty crappy workaround but it works.

Thanks for this great app, kind regards,

Ezra

**Comment by Taloth** [comment]
Hey Ezra, In all likeliness you're crashes are caused by an older linux kernel. Please refer to

https://forums.sonarr.tv/t/native-mono-crashes-kernel-fix-released/4985

You can ignore those SignalR errors, it's SignalR's way of saying that a browser session disappeared at an unexpected time.

**Comment by ezraholm50** [comment]
Hey Taloth, thanks alot i will just ignore is. And i will find out what it is about the kernel, i do think inhave all the latest kernels, every update is automated but ill check thanks again. Great app! Thanks
