### ISSUE TITLE
Visual glitch with ellipses for custom filters

### ISSUE THREAD

**Issue by d-Rickyy-b** [Sonarr/Sonarr#7413]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

This issue might be an upstream bug for the react-middle-truncate library - but you know better than me. 

The edit dialog for custom filters shows a visual glitch for certain selections such as `Apple TV+` or `Nippon TV`. The names are displayed with an ellipsis in the middle but the end part (TV+ or TV) repeated. So `Apple TV+` becomes `Apple TV+...TV+` and `Nippon TV` becomes `Nippon TV...TV`.

![image](https://github.com/user-attachments/assets/8e8dfd94-9472-4f42-a062-7c165caeb498)

What's interesting is that both names have a length of exactly **10 characters**. Which is also the number for start/end values for the truncation library:

https://github.com/Sonarr/Sonarr/blob/ca0bb14027f3409014e7cf9ffa8e04e577001d77/frontend/src/Components/Form/Tag/TagInputTag.tsx#L61

Also might be noteworthy: When I change the viewport size via the developer tools, with each pixel I de/increase the size the bug alternates between being visible and being invisible. This issue seems to be only reproducible in **MS Edge** and not in Firefox. I did not test other browsers.

### Expected Behavior

The custom filter shows the right name - e.g. `Apple TV+`

### Steps To Reproduce

1. In the series overview page, go to filters (top right) > Custom filters
2. Add custom filter
3. Use filter "Network",  "contains"
4. Select "Apple TV+" from the list

### Environment

```markdown
- OS: Debian 6.1.112-1
- Sonarr: 4.0.10.2544
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Edge 130.0.2849.80
- Database: Sqlite 3.45.3
```

### What branch are you running?

Main

### Trace Logs?

N/A

**Comment by markus101** [comment]
I was able to reproduce in Arc, seems like an odd bug in calculating the text size in `react-middle-truncate`, I'll replace it with something that doesn't melt down the same way.
