### ISSUE TITLE
Provide XMLTV EPG for other applications to use

### ISSUE THREAD

**Issue by viggy96** [Sonarr/Sonarr#7416]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Right now, its difficult to get accurate EPG data for shows that are from multiple countries, to have this information available to applications like Jellyfin.

### Describe the solution you'd like

It would be great if Sonarr could provide an XMLTV EPG, for other applications to use, such as Jellyfin.
Note, that I am NOT asking for direct access to Skyhook, which I am aware is closed source, and is exclusively for Sonarr's use.  The feature I envision is purely local, provided by the local Sonarr instance, so no additional Skyhook calls would be made. It would be available via a URL, API key required. Then, other applications could add it as they would any other XMLTV EPG source.

### Describe alternatives you've considered

Using SchedulesDirect might seem to be a solution at first, but it doesn't work very well in my experience, especially for libraries that have shows that are from many different regions.

**Comment by markus101** [comment]
Unfortunately this is not something we're going to implement in Sonarr.
