### ISSUE TITLE
Episode ordering by alpha rather than natural

### ISSUE THREAD

**Issue by Bandit** [Sonarr/Sonarr#7423]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sorts episodes by alpha (e.g. 10, 7, 8, 9)

### Expected Behavior

Sorts episodes by natural (e.g. 7, 8, 9, 10)

### Environment

```markdown
- OS: Docker, so I guess Linux?
- Sonarr: 4.0.11.2680
- Docker Install: Yes (4.0.11.2680-ls260 by linuxserver.io)
- Using Reverse Proxy: No
- Browser: Arc for Windows (11)
- Database: Sqlite 3.45.3 (migration 215)
```

### What branch are you running?

Main

### Trace Logs?

Are logs actually useful for this? Seems like a frontend problem

### Anything else?

![image](https://github.com/user-attachments/assets/7a426802-1f4e-447e-84e2-ad7a09b61882)

Seems like this is a regression since I don't remember it being an issue previously

**Comment by Neptunespace** [comment]
Do not click on Title to short, click on the # and you will get back to normal

**Comment by markus101** [comment]
Title has never been naturally sorted, at this time there are no plans to.
