### ISSUE TITLE
Prevent grabbing season packs if full season hasnt aired

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#743]
Sometimes specials look like season packs to Sonarr and it will grab one and screw up other geabs in the season. If we did a check to make sure all the episodes have aired then we could prevent this issue before it occurs.

**Comment by thezoggy** [comment]
as per our discussion, how we did it in sb: `Added check to only consider a full season pack if the last episode in the season airdate is older than 7 days or if the last aired ep is older than 'today'.`
