### ISSUE TITLE
.NET 6 is EOL

### ISSUE THREAD

**Issue by paulmiro** [Sonarr/Sonarr#7442]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr currently uses .NET 6, which has reached End of Support on November 12, 2024 ([source](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)).
Some package managers (for example [Nix](https://nixos.org/)) will flag this as a security issue and refuse to install the package unless all the EOL dependencies are explicitly allowed.

### Expected Behavior

N/A

### Steps To Reproduce

N/A

### Environment

```markdown
- OS: NixOS 25.05.20241119.23e89b7 (Warbler) x86_64
- Sonarr: 4.0.10.2544
- Docker Install: No
- Using Reverse Proxy: Irrelevant
- Browser: Irrelevant
- Database: Irrelevant
```

### What branch are you running?

Main

### Trace Logs?

N/A

### Anything else?

Issue on nixpkgs for reference: https://github.com/NixOS/nixpkgs/issues/360592

**Comment by PearsonFlyer** [comment]
Duplicate of https://github.com/Sonarr/Sonarr/pull/6776

**Comment by markus101** [comment]
Moving to .net 8 will be part of v5

**Comment by GGG-KILLER** [comment]
At least one issue should be kept open so people can follow it.

And is there an ETA for v5? This is blocking our removal of .NET 6 on nixpkgs/NixOS: https://github.com/NixOS/nixpkgs/issues/326335

**Comment by Stunkymonkey** [comment]
@GGG-KILLER I guess we can only follow #7443
