### ISSUE TITLE
Separate Search from Unmonitor on Wanted: Missing

### ISSUE THREAD

**Issue by dietrichmd** [Sonarr/Sonarr#7449]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The unmonitor selection button is between two search buttons, causing accidental unmonitoring of episodes.

### Describe the solution you'd like

Please swap the Unmonitor Selected button and the Search All button.  Too many times I have accidentally unmonitored numerous episodes because of a shaky hand or other such reason.

### Describe alternatives you've considered

na

**Comment by stevietv** [comment]
something like this might make more sense you mean?

current:
![image](https://github.com/user-attachments/assets/29ac0b1f-3f7c-49b7-a07d-ef8f5086eca6)

proposed:
![image](https://github.com/user-attachments/assets/6a5f6bf0-3724-4d85-b24c-4bfa8f842c51)

**Comment by dietrichmd** [comment]
More like this:

![sonarr_proposed](https://github.com/user-attachments/assets/d804c610-1e81-4f01-9c43-1f6971d8eeff)

**Comment by stevietv** [comment]
I don't like the how the words look in that example, the way it splits two lines, 1 line, then two lines again.

I can see the logic in moving the search button though!

**Comment by markus101** [comment]
Grouping search like that looks weird because "selected" items are disabled. I think Stevie's proposal makes the most sense.

**Comment by dietrichmd** [comment]
howso?  That does nothing to prevent the accidental click of the Unmonitor selected button.  If the two line/one line thing is an eyesore, just put "all" on it's own line, so Search is lined up and Selected and All are lined up.

**Comment by markus101** [comment]
Moving "all" to it's own line is not a viable solution, the wrapping is handled automatically based on the space required for the text and there are translations.

If the separator is the issue then just re-order things and move the separator

![image](https://github.com/user-attachments/assets/dd2594ee-f7d5-4731-8af5-96ead5dbf9d6)

Keeps "selected" actions beside each other, moves search together and adds separation between unmonitor and search.

**Comment by dietrichmd** [comment]
That new option works fine :)

**Comment by dietrichmd** [comment]
> what about having a dynamic Search All / Search selected button, like we have on series overview

That would be even better!
