### ISSUE TITLE
Manual import modal dialog doesn't scroll

### ISSUE THREAD

**Issue by deceze** [Sonarr/Sonarr#745]
In case the modal dialog for manually importing files is longer than the screen height, it doesn't scroll. There's an `overflow-y: auto` missing on one of the modal wrappers. This means the actual form submission button at the end can't be reached. I'm relatively sure this worked before.

**Comment by markus101** [comment]
I was able to reproduce it once, but it was fine after a refresh. Looking at the DOM when it did happen it appears bootstrap wasn't applying the `modal-open` class to the body so scrolling was broken. We're on the latest version of Bootstrap (3.3.5) already and I took a quick look if this was a known issue, but didn't see anything.

Are you able to consistently reproduce it?
Which version of Sonarr?
Which browser?
Which OS are you using to access the UI?

**Comment by deceze** [comment]
Yes, I'm able to reproduce quite reliably. I'm using OS X Yosemite and tried in both Safari and Chrome.  
Note that I'm talking about the actual file selection dialog ("file-episode association dialog"?). The file browser screen seems to work just fine.

I've set Sonarr to auto-update and it's on the latest mainstream release (forgot to look at the version number, mid-July release...?).

**Comment by thezoggy** [comment]
are you trying to scroll with with touch? mouse? gesture?

**Comment by deceze** [comment]
Regular trackpad/mouse scrolling on a laptop.

It works fine if you hack in an `overflow-y: auto` on one of the wrapping modal divs using the web inspector. Let me know if you need me to be more specific with this and I'll look it up again.

**Comment by thezoggy** [comment]
try this,
 * navigate to http://getbootstrap.com/javascript/#modals
 * resize browser to force this modal to show scroll (so like 800x600 resolution)
 * click `launch demo modal` 

see if that shows the same problem

**Comment by thezoggy** [comment]
markus, note that there have been a few bootstrap 3.3.5 bugs addressed with modals,
https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aopen+milestone%3Av3.3.6+modal

**Comment by deceze** [comment]
The sample modals on getbootstrap.com are working fine for me.

**Comment by thezoggy** [comment]
@deceze well thats good to hear, so maybe they fixed it with 3.3.6 (which is what your testing on their website since it runs off latest)

**Comment by rafaelmagu** [comment]
@deceze which wrapping div did you attach the overflow to? I'm seeing the same issue and I attached it to a few different ones, but no luck.

**Comment by kendersec** [comment]
same issue here with Chrome 45.0.2454.46 beta on OSX Yosemite

**Comment by thezoggy** [comment]
sadly osx does scrolling differently (due to ios/gestures) try two finger or three finger scroll..

**Comment by deceze** [comment]
Interestingly I became unable to reproduce the issue as well for a bit, but now I've got it again. After going through the motions and selecting the series, season and episode for a couple of files (each of which opens and closes a new modal dialog), the main dialog gets stuck.

Adding `overflow-y: auto` to the `#page > .page-container > .container-fluid > div#modal-region` element makes it unstick.

**Comment by markus101** [comment]
The issue is when you use the file browser to locate the folder, when that modal is closed the `modal-open` class is removed from the body and the manual import screen loses its scrolling.

Two workarounds:

- Use auto-complete to select the path instead of the file browser
- Close and reopen the modal after selecting the path and choosing which action to take and re-select the path from the recently used list

**Comment by WACOMalt** [comment]
I get this issue even when only using the autocomplete dropdowns on series, season and episode a few times. I never open a file browser.

**Comment by Fma965** [comment]
I also have this issue.

**Comment by whiteatom** [comment]
Same issue.. manually adding the overflow-y made it work.
