### ISSUE TITLE
Click the path to copy

### ISSUE THREAD

**Issue by Magn5405** [Sonarr/Sonarr#7452]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It would be nice to be able to click the path to copy it, as it can be tedious to select it.

### Describe the solution you'd like

If you click the path on a series page, it will copy it to the clipboard.

### Describe alternatives you've considered

A button next to the path to copy

**Comment by markus101** [comment]
You can triple click to select it all. No plans at this time to add auto-copy to clipboard on click.
