### ISSUE TITLE
Romanian profile missing

### ISSUE THREAD

**Issue by robertcezar** [Sonarr/Sonarr#7453]
If that's the case then it's a duplicate of https://github.com/Sonarr/Sonarr/issues/269

Closing, but will reopen if @barrelltitor can confirm what they are looking for and can provide a variety of examples.

_Originally posted by @markus101 in https://github.com/Sonarr/Sonarr/issues/5494#issuecomment-1480408446_
            
Still no romanian profile. I'm happy to provide any other details to make this happen.

![Screenshot 2024-12-04 090327](https://github.com/user-attachments/assets/c97a6960-583f-447e-96c5-4c1beb90f82f)

**Comment by stevietv** [comment]
language profiles are part of Sonarr v3 and no longer in Sonarr v4. Please update your sonarr and make use of Language custom formats.
