### ISSUE TITLE
Do not redownload failed if new interactive search already running

### ISSUE THREAD

**Issue by Royal2000H** [Sonarr/Sonarr#7454]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

If a download fails, Sonarr will search again for the item automatically (assuming that option is on). This is true even if you're already doing a new interactive search for another release and currently browsing the results.

### Describe the solution you'd like

If something was downloaded with auto search and failed, but the user is already doing a new interactive search for the episode because they saw it's failing, do not do a new auto search while the user is actively browsing the results.

### Describe alternatives you've considered

This is different than the completed #5580 which gave the option to not redownload something that failed if it was downloaded with interactive search. For this request, this is a failure due to auto search that now has a new interactive window open.

**Comment by markus101** [comment]
If you see it failing and want to handle it manually you should just cancel it and handle the search. The background task doesn't know that you started a new interactive search and no plans to link that all up given the limited crossover.

**Comment by Royal2000H** [comment]
> If you see it failing and want to handle it manually you should just cancel it and handle the search. 

By "just cancel it", what do you mean? Cancel the download in the downloader app? Or is there a way to cancel the search in sonarr that I'm not seeing/understanding?

> The background task doesn't know that you started a new interactive search and no plans to link that all up given the limited crossover.

Got it, I envisioned a solution where starting an interactive search on the episode puts a tag on that episode that prevents the background task from searching. But I understand if that doesn't work with the workflow, makes sense. Thanks for your response.

**Comment by markus101** [comment]
In Activity: Queue you can click the `x` to remove then tell Sonarr to remove + blacklist and not search.
