### ISSUE TITLE
Move the + icon for new items in settings from bottom of list to top of list

### ISSUE THREAD

**Issue by rg9400** [Sonarr/Sonarr#7457]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, if you have many Indexers or Custom Formats, you need to scroll all the way to the bottom of the list to click the + icon to add a new item into the list. This is inconvenient.

![image](https://github.com/user-attachments/assets/65e6e560-7213-4c7f-835c-f87b98a1d68c)

### Describe the solution you'd like

Move the + icon to the top of the list in this type of layout so that it can be easily accessed regardless of the number of items in the setting.

### Describe alternatives you've considered

I just scroll to the bottom of the list of 100 CFs each time I want to add a new one. It's not a huge deal, but figured it could be improved.

**Comment by markus101** [comment]
No plans to move this at this time, potentially makes sense if things are redesigned, but top or bottom you're likely to have some reason to want it at the top or the bottom depending whether you're at the top or bottom.
