### ISSUE TITLE
Remove previous release from download client on upgrade

### ISSUE THREAD

**Issue by Kladki** [Sonarr/Sonarr#7458]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Ideally, releases should be seeded as long as possible. However, once a new release is grabbed, I don't really want to keep the files from the previous release anymore.

### Describe the solution you'd like

Sonarr should be able to remove a previous release (and files) from the download client when an upgrade is imported.

There is a similar locked issue #370, which was closed because of HnR concerns. This can be addressed by checking for the  "Freeleech" tag, and have no restrictions for minimum seed time/ratio if it does have that tag. If it doesn't, then the settings for that indexer can be used to specify a minimum seed ratio and/or time before a release can be removed from the download client.

### Describe alternatives you've considered

Setting a constant ratio and/or seed time before removing, but this causes releases being removed too far before/after a new release is grabbed. This also means that for releases that never get an upgrade, it doesn't get seeded indefinitely.

Keep release indefinitely. This just ends up with you having lots of lower quality files on your disk, which you will eventually need to manually clean up.

**Comment by markus101** [comment]
At the time we do not have plans to remove other quality releases when queuing new items. HnR is still a concern, but with seeding limits configured Sonarr can remove items that meet those goals and in some cases other tools can be used to manage them.
