### ISSUE TITLE
Sonarr on remote machine

### ISSUE THREAD

**Issue by ipsq** [Sonarr/Sonarr#746]
Hello,

I think my use case of Sonarr is quite different from the documented ways so I'm asking for some help. I'm running Deluge, SABnzbd, Filebot and Plex on a machine with a lot of Hard drive space. Since I can't install mono there, I'm running Sonarr on a standalone VPS with 10GB SSD storage. Now my question is, can Sonarr still function if it doesn't sort, rename and import any files but instructs the Download clients to download and let filebot handle the rest (Renaming, moving, updating plex etc.)?

Thanks in advance.

**Comment by markus101** [comment]
Please use our forums for support.

Sonarr will treat the files as missing until it sees them on disk, properly sorted, so your sorting script should notify Sonarr to rescan the appropriate series folder.
