### ISSUE TITLE
Wait for entire season to be complete prior to download with the option for a buffer

### ISSUE THREAD

**Issue by ravtakhar** [Sonarr/Sonarr#7483]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I am looking to have episodes per season to have consistent bitrate and resolution from the same provider. Currently when downloading individual episodes there is the risk of pulling episodes from different publishers. My users typically do not watch a season until all episodes are available.

### Describe the solution you'd like

I would like the ability to set series to only search to download when the season is complete with the ability to set a buffer of how many days to wait until attempting a download. This will provide the ability for Sonarr to query for a season pack prior to attempting to download individual episodes.

### Describe alternatives you've considered

Currently, I have gone through every series and disabled monitoring. However, now I am forced to keep track of when the entire season is complete prior to going in and clicking 'search' manually.

### Anything else?

An alternative solution may be allowing us set a quality to upgrade until a season pack is available.

**Comment by markus101** [comment]
This is already possible. You can use a Custom Format for single episodes and by giving it a negative score in your Quality Profile(s) they won't be grabbed automatically because they'll be below the minimum allowed score, which is 0 by default.

**Comment by ravtakhar** [comment]
The issue with this approach is that once the season is over and there are no season packs available (based on my requirements), I would still like to download individual episodes.

**Comment by markus101** [comment]
If there are no season packs then you're pretty much going to be stuck with manually managing it then. Your best choice to not miss things would be allow everything, prefer season packs, then individual files will be replaced by season packs at some point.

This is the problem with pretty much any solution where you want to wait for the season to end before trying to decide what you want.

**Comment by ravtakhar** [comment]
Thanks I will try your suggestion. I was able successfully configure Sonarr to only pull season packs but I have a show that is set for completion at the end of this week. I hope it will go through and download the entire season if it's able to find a pack.
