### ISSUE TITLE
Add the ability to receive "On File Upgrade" notifications when "On Import Complete" is enabled

### ISSUE THREAD

**Issue by d-Rickyy-b** [Sonarr/Sonarr#7484]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently you can only enable notifications for "On File Upgrade" events when "On File Import" is also enabled. From a logical point of view it should also be possible to enable "On File Upgrade" notifications if I enabled the "On Import Complete" notifications.

There was a short discussion here on discord about this: https://discord.com/channels/383686866005917708/383688189941907459/1312889054966321182
 
I am not sure if this counts as a bug or just a missing feature, so I created a feature request.

### Describe the solution you'd like

Give the user the possibility to enable "On File Upgrade" notifications when only "On Import Complete" is enabled (instead of "On File Import").

### Describe alternatives you've considered

N/A

**Comment by bakerboy448** [comment]
On Import Complete has no relation to On File Upgrade nor On File Import

Release level vs. File Level

**Comment by markus101** [comment]
This is the expected behaviour. `On File Import` and `On File Upgrade` are file level events, `On Import Complete` is for the entire release (when all episodes are imported) and is sent regardless of it being a new download or an upgrade (or a mix).

**Comment by d-Rickyy-b** [comment]
> On Import Complete is for the entire release (when all episodes are imported) and is sent regardless of it being a new download or an upgrade (or a mix).

So you are saying that "On Import" already covers both import and upgrade? Because I do want to receive update notifications for single files without receiving the "initial" import notification of each file individually.

Sadly these triggers aren't well documented as of now: https://wiki.servarr.com/sonarr/settings#connections

**Comment by markus101** [comment]
`On Import Complete` is triggered for any download that is imported, single episodes, multi-episodes, season packs, 1 file, 10 files or 50 files, you'll get one notification that the all the files have been imported.

If you want a notification per file then you want the file events, `On File Import` and `On File Upgrade`.
