### ISSUE TITLE
Clicking on an episode in the calendar does not do anything

### ISSUE THREAD

**Issue by shifoc** [Sonarr/Sonarr#7486]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Clicking on an episode in the calendar does not do anything

### Expected Behavior

Clicking on an episode in the calendar should open the modal

### Environment

```markdown
- OS: Windows 10
- Sonarr: 4.0.11.2762
- Docker Install: no
- Using Reverse Proxy: no
- Browser: Chrome
- Database: Sqlite 3.36.0
```

### What branch are you running?

Develop

### Trace Logs?

no error in logs

**Comment by CummingCowGirl** [comment]
Nice to see this has already been addressed. Any ETA on when it will be ready for sonarr-develop? Thanks
