### ISSUE TITLE
Filter for Custom Formats not working correctly.

### ISSUE THREAD

**Issue by Milincho** [Sonarr/Sonarr#7491]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Titles are not filtered correctly for Custom Formats.

I don't know why but I can't filter out titles with "DV" for my SDR Custom Format.

A title with "DV" in its name gets recognized as 'SDR':
![image](https://github.com/user-attachments/assets/0012e046-0aa0-4a84-a25b-e90b40d5e82f)

Despite the words "DV" specifically being negated for that 'SDR' Custom Format:
![image](https://github.com/user-attachments/assets/8f2666b1-30ef-47e1-987b-a238f72f9e0f)

### Expected Behavior

Word "DV" getting properly recognized.

### Environment

```markdown
- OS: Windows 11 24H2
- Sonarr: 4.0.11.2680
- Docker Install: 
- Using Reverse Proxy: No
- Browser: Chrome Version 131.0.6778.140 (Official Build) (64-bit)
- Database:
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.debug.txt](https://github.com/user-attachments/files/18143333/sonarr.debug.txt)
[sonarr.trace.txt](https://github.com/user-attachments/files/18143334/sonarr.trace.txt)
[sonarr.txt](https://github.com/user-attachments/files/18143335/sonarr.txt)

**Comment by bakerboy448** [comment]
GitHub is not for support.

(Not Z) OR (Not X) OR (NOT Y)  thus any must be true.

Review the UI and wiki for how to use required between the same formats for what you're trying to achieve or utilize TRaSH Guides

**Comment by Milincho** [comment]
Sorry, didn't realize I had to set 'Required' for each negated condition.

Thanks for the tips. 👍🏻
