### ISSUE TITLE
Interactive import auto-fill in order

### ISSUE THREAD

**Issue by DiegoGuidaF** [Sonarr/Sonarr#7492]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When I download a season-pack or for any other reason download a series manually (not via Sonarr) I usually end up importing it through the interactive import. More specifically I do `Wanted` --> `Missing` --> `Manual Import`.

Usually I find that most episodes are imported correctly except for one of them which I need to fix (sometimes it is a Special episode or one not properly detected). This means that I not only need to fix/skip that single episode, but all the ones below that one. See screenshot below for an example
![image](https://github.com/user-attachments/assets/39b05368-0225-4c62-bfed-022fe8ce50b1)
In the screenshot above I fixed the issue for that single episode (currently pointing to S0E1) but now I need to go through all the ones below to just add +1 to the episode that it is pointing to.

### Describe the solution you'd like

It would be amazing if I could just press a button on an episode and it would automatically just add +1 to all the episodes below it starting with the episode number of the one clicked.
I am unsure how the UI would look, I have a couple suggestions but maybe someone has a better idea:
* In more detail: Have a button on the right side of each episode, when pressing it a popup warning what will happen and the user would need to confirm. The popup would mention the currently selected episode number and maybe an example of how the following episode would look like. On confirm, all the episodes below the one selected (not including it) would be pointing to the next one. So for example if clicking on S01E04, the following episode would be automatically pointing to S01E05, the next one to S01E06 **regardless** of the episode they were previously pointing to.

### Describe alternatives you've considered

None

**Comment by markus101** [comment]
You can select the episodes you want to update and mass assign them under `Select....`. No plans to add functionality to increase/decrease by some other value.
