### ISSUE TITLE
Display TVDB 'critical to story' tag in specials

### ISSUE THREAD

**Issue by GR3ee3N** [Sonarr/Sonarr#7495]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

If you want to determine whether any special episodes are 'critical to the story', you currently need to visit the TVDB website, navigate to Seasons -> Specials, and check for the 'critical to story' tag.

### Describe the solution you'd like

It would be incredibly helpful if Sonarr displayed the 'critical to story' tag for episodes, just like it already does for tags such as 'Series Finale', 'Season Finale', and 'Midseason Finale'. This feature would make identifying relevant specials much faster and more convenient.

### Describe alternatives you've considered

-

**Comment by markus101** [comment]
We'll need at least one example series to see how this information is made available.

**Comment by GR3ee3N** [comment]
This one has plenty of is's specials tagged

https://www.thetvdb.com/series/that-time-i-got-reincarnated-as-a-slime/seasons/official/0

**Comment by markus101** [comment]
While this information is available in the API it's only available when fetching individual episodes from the API, which is not feasible at this time.
