### ISSUE TITLE
Adding Root Folder in Series Edit page results in Error and Not Adding

### ISSUE THREAD

**Issue by qsuicide** [Sonarr/Sonarr#7497]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Adding a new root folder directly in the Edit popup on the Series page appears like it works, but then the folder isnt actually added as a root folder, and the dropdown box just returns to No Change. 

small snippet of code in the logs
`2024-12-17 11:56:05.7|Warn|SonarrErrorPipeline|Invalid request Validation failed:
 -- Path: Invalid Path: '{path}'
2024-12-17 11:56:05.7|Trace|Http|Res: 13531 [POST] /api/v3/rootFolder: 400.BadRequest (2 ms)`

image of Root Folder screen (from Series, Library Import). At this point I have not manually added a root folder on this page, only through Series Edit page, and the error shows at the bottom already. 
![image](https://github.com/user-attachments/assets/0f20f843-6578-4055-a488-94740b68bfdf)

#support was able to reproduce the issue. image provided by StevieTV
![image](https://github.com/user-attachments/assets/8731903a-58cb-4cc2-b062-22edad5525c9)

### Expected Behavior

Expect that the Root Folder is added correctly and useable from the Series Edit page. 

### Steps To Reproduce

Try it ;) Pick series and go to that series page. Click Edit to bring up the popup, click on the Root Folder Change button (looks like two folders), and then 'Add a New Path' at the bottom. This will create the issue. 

### Environment

```markdown
- OS: Ubuntu Server 24
- Sonarr: 4.0.11.2762
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.44.2
```

### What branch are you running?

Develop

### Trace Logs?

`2024-12-17 11:56:05.7|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Invalid Path: '{path}'
2024-12-17 11:56:05.7|Trace|Http|Res: 13531 [POST] /api/v3/rootFolder: 400.BadRequest (2 ms)`

**Comment by markus101** [comment]
Fixed by https://github.com/Sonarr/Sonarr/pull/7496

**Comment by stevietv** [comment]
sorry @qsuicide -I asked you to raise this issue, but then took a look at a fix already!

**Comment by qsuicide** [comment]
lol no problem. i got pulled away from my PC mid issue. glad its all fixed :)
