### ISSUE TITLE
Manual Torrent Adding

### ISSUE THREAD

**Issue by waldnercharles** [Sonarr/Sonarr#750]
Currently if I want to add a .torrent manually I need to add it through my torrent client. Then if I want the show to appear as downloaded in Sonarr I need to manually scan the drone factory folder, where my torrents download to. I would do automatic, but for some reason the automated scan crashes Sonarr most of the time.

It would be nice to be able to add the .torrent file through Sonarr to skip the middle man and be one step closer to removing the drone factor folder altogether.

**Comment by markus101** [comment]
Set the download to use the same label and Sonarr will process it as long as it can figure out which series/episode it is (same as it needs to to import any download).

**Comment by waldnercharles** [comment]
Thanks for the tip! I'll try that. 

It would still be nice to have an "Add Torrent" button somewhere that adds the torrent with the proper category for you.

**Comment by markus101** [comment]
That seems like a job for a browser plugin more than Sonarr. If you can find it via manual search you can add it to Sonarr and it will set the category, but an arbitrary add torrent button doesn't seem too useful to me.

**Comment by waldnercharles** [comment]
The manual search only searches available indexers. Not to mention certain indexers don't support anime or vice versa, even when readily available through the site.

I suppose a browser plugin could do the same thing, but so could my transmission webui if i set the default label to whatever Sonarr uses, (except currently mine is blank.)

Either way, I know that something else can do it, but it would still prove useful to me.

I guess the real question is if I implement this, would a pull request be welcomed by others?

**Comment by kayone** [comment]
I really appreciate that you are asking before putting the effort and actually doing a PR, it makes us feel pretty bad when we have to turn down PRs.
 
to be honest I really don't think this would be something we would want added. I don't think it adds much value and might just confuse/complicate the UI. I just don't see why you would go to sonarr's UI instead of whatever torrent client you use to add a torrent.

**Comment by markus101** [comment]
Not sure which browser you use, but for Chrome I use the Remote Transmission ++ plugin which sees the torrent download and lets me choose the download path and send the torrent to. The result is a pretty seamless integration and you don't need to copy and paste.

**Comment by waldnercharles** [comment]
Thank you for the add-on recommendation. I'll hold off on doing a PR for now unless a suitable compromise can be thought of.
