### ISSUE TITLE
Unable to communicate with Download Client after indexer is removed

### ISSUE THREAD

**Issue by LaurinSorgend** [Sonarr/Sonarr#7508]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I Test rTorrent in the download Clients section it passes it but then It shows me this Health message.

### Expected Behavior

I expected rTorrent to work as I didn't change any settings and it worked previously

### Environment

```markdown
- OS: Ubunutu
- Sonarr: 4.0.11.2784
- Docker Install: Yes
- Using Reverse Proxy: No
- Database: Sqlite 3.47.1
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/user-attachments/files/18218073/sonarr.trace.txt)

**Comment by bakerboy448** [comment]
Indexer selected download client and you deleted the indexer?
