### ISSUE TITLE
Add Import List - MyAnimeList broken

### ISSUE THREAD

**Issue by Jhonny0007** [Sonarr/Sonarr#7510]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When adding a MyAnimeList - list, the authenticate button opens a new tab with a http/404 code. 

https://services.sonarr.tv/v1/oauth/myanimelist/authorize?state=https%3A%2F%2FREDACTED%2Foauth.html&redirect_uri=https%3A%2F%2Fservices.sonarr.tv%2Fv1%2Foauth%2Fmyanimelist%2Fauth

### Expected Behavior

Open a window to authenticate with myanimelist.

### Steps To Reproduce

Click Settings in the Menue => Import Lists => add => MyAnimeList => Authenticate

### Environment

```markdown
- OS: Debian 11
- Sonarr: 4.0.11.2680
- Docker Install: kubernetes/cri-o
- Using Reverse Proxy: nginx-ingress
- Browser: Edge
- Database: Sqlite 3.45.3
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/user-attachments/files/18219322/sonarr.trace.txt)

**Comment by markus101** [comment]
This is resolved now, no update to Sonarr required.
