### ISSUE TITLE
Import List Sync updating series not reflected in the UI

### ISSUE THREAD

**Issue by funforgiven** [Sonarr/Sonarr#7511]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When the Import List runs, it correctly retrieves series from AniList. However, it does not unmonitor or apply tags to series based on the selected Clean Library Level option.

### Expected Behavior

When the Clean Library Level option is configured, Sonarr should unmonitor or tag series accordingly during the AniList import process.

### Steps To Reproduce

1. Add an AniList import list to Sonarr.
2. Set Clean Library Level to Keep and Unmonitor Series
3. Verify that anime series are correctly imported from AniList.
4. Remove an anime from your AniList.
5. Run the import again and observe that while Sonarr detects the changes, it does not unmonitor or apply tags based on the selected Clean Library Level option.

### Environment

```markdown
- OS: TrueNAS ElectricEel-24.10.0
- Sonarr: 4.0.11.2784
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Brave v1.73.104
- Database: Sqlite 3.47.1
```

### What branch are you running?

Develop

### Trace Logs?

https://privatebin.net/?b35dfbcdcc2579a6#4G6cf1xMyfZgBDYRJpGg4JKHLDaRhnJGCHaQaAT98956

### Anything else?

I also tried this with Simkl and it is not working for me.

Here are my AniList Import List settings:
![image](https://github.com/user-attachments/assets/82ff3372-13fc-4897-8532-881b829ef266)
![image](https://github.com/user-attachments/assets/15c0b124-2cc8-4196-8835-e8160f2fea38)

**Comment by markus101** [comment]
The items are being unmonitored, but the UI isn't updating the reflect the changes, manually reloading the page will show the correct information, assuming other edits haven't reverted them.

**Comment by funforgiven** [comment]
I am not sure about that. I refreshed it, even checked it on different devices. There are series that are not in my list for more than 6 months but they are still monitored. I have 56 shows monitored, 0 shows unmonitored. Yet, AniList is my only import list at the moment and it only returns 27 shows. I am not sure why 29 series that are not in my import list are still monitored.

**Comment by markus101** [comment]
Sonarr tracks which items were added from each import list, when an item is removed from the list it removes that reference and no longer updates the series tags/monitored status after that first update. This prevents Sonarr from marking an item as removed when it fails to sync with an import list or a series is added outside of the list.

**Comment by funforgiven** [comment]
Sorry for responding to a closed issue but this fix was not really about my problem. There are no series added manually or with any other list. I only have a single import list and I never add anything manually.

I just tried with a brand new Sonarr instance and a brand new AniList account, did not trigger the import manually, moved animes to completed in AniList except one after the first import, waited for 12 hours.
Completed anime is not ticked in import list settings, it actually gets only 1 anime from my list as it should but nothing is unmonitored.

**Comment by markus101** [comment]
Do you see the same behaviour if the item is completely removed from the list instead of just moved to Completed?

**Comment by funforgiven** [comment]
Yes, I also suspected that case and tried it but it did not work too.

**Comment by markus101** [comment]
Opened another PR to address the other problem here.

**Comment by funforgiven** [comment]
It makes sense. Thanks for the follow-up.
