### ISSUE TITLE
Adding more Loading Messages

### ISSUE THREAD

**Issue by Hello-World-Traveler** [Sonarr/Sonarr#7514]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

https://github.com/Sonarr/Sonarr/blob/develop/frontend/src/Components/Loading/LoadingMessage.tsxLoading/LoadingMessage.js I don't think has been updated in a few years.

I've put together a list that can be copied and pasted.

```
'Hello, IT... Have you tried forcing an unexpected reboot?'
'To infinity... and your next episode!'
'If this takes too long, try turning it off and on again.'
'Are we there yet?'
'Loading faster than a caffeinated coder on a deadline.'
'Doing all the heavy lifting'
'Please wait while we serve our master'
'Did you see this ludicrous display last night?'
'Warming up the flux capacitor for time travel to your favorite show.'
'Why do programmers prefer dark mode? Because light attracts bugs!'
'Definitely not a virus!'
'You seem like a nice person?'
'Patience! This is difficult, hehe.'
'Welcome to Sonarr, may I take your order?'
'Just a sec! Our server is doing yoga to stay flexible'
'Fetching your shows... Please do not feed the server.'
'Calculating the odds of finding that missing episode.'
'We're on it! Just like a cat on a keyboard.'
```
There isn't any plans to add more to the list atm however with copy and paste should take a few minutes.
I really like the loading messages, sadly they are getting more stale over time. 

### Describe alternatives you've considered

None?

### Anything else?

It would be nice if some messages was used.

**Comment by markus101** [comment]
Not something we’re going to commit to do, but we may revisit in b5.
