### ISSUE TITLE
Disabling analytics does not work

### ISSUE THREAD

**Issue by cohesive-flight** [Sonarr/Sonarr#7518]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When analytics is disabled, Sonarr still establishes a connection to sentry.sonarr.tv and sends analytics to it.

### Expected Behavior

When disabled, there should be no attempt to query, connect or send analytics to sentry.sonarr.tv.

### Steps To Reproduce

1. Disable analytics
2. Restart Sonarr
3. Monitor DNS queries

### Environment

```markdown
- OS: Debian 12
- Sonarr: 4.0.11.2680
- Docker Install: Yes (hotio), but also tested this with the native version
- Using Reverse Proxy: Yes, but not with the native version
- Browser: Firefox 113
- Database: Sqlite 3.44.2 (Docker) and Sqlite 3.40.1 (native)
```

### What branch are you running?

Main

### Trace Logs?

This bug doesn't appear in the trace logs, but I used mitmproxy to verify that it is sending analytics based on the HTTP request below:

```
POST /api/8/envelope/ HTTP/1.1
Host: sentry.sonarr.tv
X-Sentry-Auth: Sentry sentry_version=7,sentry_client=sentry.dotnet/4.0.2,sentry_key=e2adcbe52caf46aeaebb6b1dcdfe10a1
Accept: application/json
Accept-Encoding: gzip, deflate, br
Content-Length: 438

{"sdk":{"name":"sentry.dotnet","version":"4.0.2"},"sent_at":"2024-12-25T00:15:30.9632286+00:00"}
{"type":"session","length":308}
{"sid":"b15c6dbbf8d9e7a2ca5bcdf77e3f4ba","did":"057fddc4-2b45-4680-9313-89263179d7a9","init":false,"started":"2024-12-25T00:13:13.6511561+00:00","timestamp":"2024-12-25T00:14:38.6126016+00:00","seq":1,"duration":439,"errors":0,"status":"abnormal","attrs":{"release":"4.0.11.2680-main","environment":"main"}}
```

### Anything else?

This bug also occurs with Prowlarr, and most likely with every other *arr service if Sonarr is used as base.

**Comment by bakerboy448** [comment]
url seems to tie to register sentry https://github.com/Sonarr/Sonarr/blob/1c30ecd66dd0fd1dafaf9ab0e41a11a54eaac132/src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs#L68

not technically analytics but probably nice to avoid if analytics is off

**Comment by Taloth** [comment]
The actual problem is that approx year ago with some refactoring the AutoSessionTracking feature flag gets used by the SentrySdk _before_ ReconfigureLogging has a chance to turn of sentry entirely based on the analytics settings. It should be fixed now.
