### ISSUE TITLE
First Letter of Series renaming token

### ISSUE THREAD

**Issue by danielfaulknor** [Sonarr/Sonarr#752]
Is there any way to get the first letter of a series as a variable? I'm seeing a need to split up my media as I run out of space on various drives.

If not, consider this a feature request :)

**Comment by markus101** [comment]
The series folder format is only used when creating a series for a new folder (not importing an existing series).

How do you plan to utilize this?

**Comment by danielfaulknor** [comment]
I would symlink letters of series names onto different RAID arrays/storage devices, as I don't want to buy a big lot of larger storage each time I run out of space.
I'm happy to do the initial sort but it would be nice if sonarr would then put series into the correct folder as it downloads.
I suppose I could link Series folders but that's even more work

**Comment by hr1232** [comment]
Is there a timeframe for this feature yet?

I have a library of well over 1000 tv shows and while they all fit into one filesystem on my nas, fileservice performance is quite poor when opening that directory.

Please make a variable available containing the series' the first letter so Sonarr can automatically sort series into subdirectories as it has always been the best practice for directories with that much information in them.....

**Comment by danielfaulknor** [comment]
Bumping this because I just had to delete a massive amount of content to free up space :(

**Comment by markus101** [comment]
One thing to consider with this is currently the root folder is assumed to be the parent of the series folder, if the series folder format allows `A/Archer` we'll need to know how to get to the correct folder.

**Comment by hr1232** [comment]
@markus101

Should not really make a difference. If you set the series directory with something like

$targetdir = $root.'/'.$subdir

there is not really any difference between

$subdir = 'Archer'

and

$subdir = 'A/Archer'

It is just a matter of providing a variable Luke $first for and allowing for a slash to be used in the directory name at any position but the first vor last.

I would suggest "stealing" the code from headphones. They have it working perfectly. There it is no problem to have an album directory like

E/Elton John/Goodbye Yellow Brick Road (1973)

**Comment by hr1232** [comment]
Just to be clear, the root folder can stay the parent oft the series folder. The series folder just contains a slash....

**Comment by markus101** [comment]
Creating the folder isn't the problem. The problem could arise if Sonarr assumes the parent of `C:\TV\A\Archer` (`A`) is the root folder, instead of `C:\TV\Archer`. I'm not sure it's a problem, but something to be aware of.

**Comment by hr1232** [comment]
You are thinking about this way to complicated. Seems I have to be Mord clear:

The root folder can stay the parent oft the series folder. The series folder just contains a slash. Everything else is not the business of sonarr because it will be handled by the OS.

**Comment by markus101** [comment]
I understand what you're trying to say, but a single folder cannot have a slash in it.

Sonarr stores a single path for a series, which is the root folder + series folder format when the series was added. After it's set the user is free to edit any part of the path or use the series editor to change the root folder which would build a new path using the root folder and the series folder name (the last folder in the path). That works right now because you can't use slashes in the series folder format, if you could that wouldn't work.

You can't assume the current series folder format matches the saved path for the series folder because settings change and those changes aren't applied to the saved paths. Storing the root folder separately from the series folder may work.

**Comment by hr1232** [comment]
You obviously do not und erstand me. You are thinking of things that are not sonarr's job.

Stop thinking of it as a single folder. Instead think of it as the path below the root. As it is only needed to "build" the series directory, it is completely irrelevant whether vor not there is a slash in it.

When the series directory is built it is saved as a whole into the database. You do not have to care about how many subdirs it has. That's the job of the OS.

Only think you have to look at is the function that creates the folder as you will have to create it recursively. Depending on how you make that API call it is perhaps already done.

**Comment by markus101** [comment]
Like I said, creating the folder is _NOT_ the problem. My Concerns have nothing to do with that.

**Comment by hr1232** [comment]
Your concerns are completely irrelevant. 

The only place where the difference between a folder and a path are actually relevant is the creation of the folder which might fail if sonarr asumes that the patent exists.

After that it is just a path to an existing folder. Nobody cares about wether or not it is directly in the root dir as they are not seperated anywhy.

**Comment by markus101** [comment]
False.

It matters when changing the root folder from Series Editor, which may not matter to you, but it does matter. It may also be assumed to be a single folder in other places, changes would need to be made there.

**Comment by hr1232** [comment]
As I have already changed the folders manually and later on had to move the entire thing to a different filesystem (i.e. change the root) i repeat: your concerns are irrelevant.

My sonarr has been running with an first letter intermediate path for about a year now and everything is working fine (except for the fact that i manually have to change the folder name for every new series).

The only thing that might have to be changed is the creation of the folder. And of course the additional var has to be added to media management.

**Comment by Taloth** [comment]
Please let me interject.

The concern that markus raised is that in several location in our code Sonarr assumes that the parent of a series path _IS_ the root path. You may not have encountered issues with it, but that doesn't mean they aren't there.
It'll likely lead to unintended behavior in various locations, such as the recycle bin, rootfolder health check, Series Mass Editor and possibly others. Which means we'd have to verify each one individually and fix that behavior.

The problem isn't about what's technically possible, it's that your proposed change isn't as straight forward as might appear initially.

**Comment by markus101** [comment]
This is done in the v3 work.
