### ISSUE TITLE
Reject Import if Audio Language is Wrong

### ISSUE THREAD

**Issue by hughesjs** [Sonarr/Sonarr#7523]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Oftentimes, sonarr will grab a release wich turns out to be in the wrong language.

Today's example would be Squid Game where it's pulled Korean and French for some episodes rather than Korean and English. It's even more common with Anime, even though I have tags set up to prioritise releases that are dubbed and English.

### Describe the solution you'd like

When Sonarr goes to import a file, it should parse the video container for the list of languages present. If it doesn't contain a required language, it should reject the release, delete the file, blacklist it, and then try again.

This should obviously be optional.

### Describe alternatives you've considered

Tried using tags to prioritise releases with the right languages but this doesn't always work.

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/issues/5598 could be used to prevent importing based on CF being lower than expected once it's available, but we do not have plans to automatically delete/blocklist files that aren't able to be imported automatically at this time.

**Comment by hughesjs** [comment]
@markus101 Yep, I think you're right, that could do it. Are there any docs that describe how these options interact?

<img width="593" alt="image" src="https://github.com/user-attachments/assets/74e771f3-86a4-42f6-b4d2-387f2f0cfc11" />

For instance, I'd rather a blueray 1080p was replaced by a web 1080p if it had a better CF score
