### ISSUE TITLE
Sonarr stopped working with rtorrent when they switched from xmlrpc-c to tinyxml2

### ISSUE THREAD

**Issue by radhoo2k10** [Sonarr/Sonarr#7530]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Under activity the status of the torrent is shown as paused even if the torrent is downloading/finished. 

According to Simonc56 this is due to:
"But this issue is about sonarr.
To my opinion radarr/sonarr can't read the is_active value of torrents because of integers being declared as 32bit values with <i4> tag (with tinyxml2) instead of 64bits values with <i8> tag (with xmlrpc-c). Test needed.

last commit setting the <i4> tag : https://github.com/kannibalox/rtorrent/commit/532bfb2e6b74f574c40ca7aac08c5896cec039a9

If the <i4> tag is indeed the cause of the pause issue, I think it's a bug in radarr/sonarr because <i4> is a correct tag and is correctly read by other clients."

https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/419#issuecomment-2565273045

### Expected Behavior

to show the correct status on torrents

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.11.2680
- Docker Install: yes
- Using Reverse Proxy:  no
```

### What branch are you running?

Main

### Trace Logs?

2024-12-29 19:58:57.6|Debug|RTorrent|Retrieved metadata of 0 torrents in client

**Comment by stickz** [comment]
This is not the proper place to fix this problem. We can't have `xmlrpc-c` on i8 and `tinyxml2` on i4. We need to fix it from the rTorrent repository. rTorrent currently allows both to be used, therefore we must follow the same standard.

Yes, we should eventually switch to i4, but not until we depreciate `xmlrpc-c` in favour of `tinyxml2`.

**Comment by radhoo2k10** [comment]
closing issue
