### ISSUE TITLE
Delete associated files

### ISSUE THREAD

**Issue by Emmanuel147** [Sonarr/Sonarr#756]
When Sonarr finds and replaces a file with a better quality, Sonarr deletes the old file. But it leaves associated files behind. Now I have to check all updated series for leftover *.nfo, *.vsmeta, *.srt and *.sub files. It would be nice to have the option to remove associated files to.

**Comment by markus101** [comment]
Deletion won't happen until Sonarr tracks the files. Thennit will happen automatically.

https://github.com/Sonarr/Sonarr/issues/459

**Comment by j2ghz** [comment]
How about deleting all files matching `<video file being deleted>.*`?

**Comment by thezoggy** [comment]
i suggested they just follow how sb does it.. delete files that match the video file (matching from right side not left - so you catch .en.srt and not just .srt) it looses the need to track all files / uneeded complexity

**Comment by Emmanuel147** [comment]
@markus101: When will Sonarr track all associated files?

@thezoggy: Would be the best option in my opinion.

**Comment by markus101** [comment]
We don't provide ETAs, but its not something we're actively working on.

Deleting matching files might be a suitable interim solution though.

**Comment by foux** [comment]
Any news on this one?

**Comment by NLJM** [comment]
I would love to have this option. My series folders keep getting cluttered with subtitle files from replaced episodes.

**Comment by markus101** [comment]
This is now taken care of with the extra file support added a few months ago.
