### ISSUE TITLE
SQLite brings Sonarr down when using a docker volume as the datadir

### ISSUE THREAD

**Issue by Coaxial** [Sonarr/Sonarr#757]
When running Sonarr inside a Docker container, with Sonarr's data directory set to a docker volume that is pointing to a directory on the host's filesystem, then Sonarr crashes with an Epic Fail and a SQLite I/O error trace.

If you launch Sonarr still in a container but with the data dir as a normal directory (i.e. not a volume), then Sonarr runs fine but you lose the app's state and data every time you restart the container. Losing state in this case is normal docker behaviour, this is expected.

It doesn't seem to be a permission issue because if I log into the container and try to write & read files to the volume, everything is fine. Using a volume as the datadir seems to be what crashes Sonarr every time.

Here are the Dockerfile and docker-compose.yml I used, with docker 1.8.1 on Mac OS X 10.10.5:
[Dockerfile](https://github.com/Coaxial/docker-vcr/blob/e0ef94e53b2960c778ba84e31f2ecc06ecb4527a/sonarr/Dockerfile)
[docker-compose.yml](https://github.com/Coaxial/docker-vcr/blob/e0ef94e53b2960c778ba84e31f2ecc06ecb4527a/docker-compose.yml)

Browse at this commit (following commits also crash but they were various experiments): https://github.com/Coaxial/docker-vcr/tree/e0ef94e53b2960c778ba84e31f2ecc06ecb4527a

Note: I'm launching the apps with
```
docker-compose rm -f # To kill and remove any previously running/stopped containers
docker-compose build
docker-compose up
```

**Comment by Coaxial** [comment]
Crash full output with --debug:

```
[Info] Bootstrap: Starting Sonarr - /opt/NzbDrone/NzbDrone.exe - Version 2.0.0.3435
[Debug] ProcessProvider: Found 0 processes with the name: NzbDrone.Console
[Debug] ProcessProvider: Found 1 processes with the name: NzbDrone
[Debug] ProcessProvider:  - [153] NzbDrone
[Info] MigrationLogger: *** Migrating data source=/root/.config/NzbDrone/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***


[Fatal] ConsoleApp: EPIC FAIL!

System.Data.SQLite.SQLiteException: disk I/O error
disk I/O error
  at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, UInt32 timeoutMS, System.String& strRemain) [0x00000] in <filename unknown>:0
  at System.Data.SQLite.SQLiteCommand.BuildNextCommand () [0x00000] in <filename unknown>:0

Press any key to exit...
```

**Comment by Coaxial** [comment]
Nevermind, it seemed to be a permissions problem!

**Comment by ammmze** [comment]
Got any tips for what files had permission issues?

**Comment by Coaxial** [comment]
@ammmze If I remember correctly, it was due to the host's directory permisions. You can't change permissions from within the container for external, shared paths. You have to make sure the GID/UID match on the host's filesystem with the user and group that will be doing the writing within your container.

**Comment by morberg** [comment]
Hm. Just had this problem, but couldn't find a way to solve it without reverting to a data directory within the docker machine. Tried to change permissions to no avail.

Input on how to solve this or things to try would be appreciated.

**Comment by whispy** [comment]
@coaxial any tips?

**Comment by dasjestyr** [comment]
Same problem, an actual fix would be helpful
