### ISSUE TITLE
Partial Backlog Searches - Limited number of episodes

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#761]
If we combine the last search time for an episode (https://github.com/Sonarr/Sonarr/issues/420) and a daily backlog search we could limit the number of episodes searched for daily, we'd need to impose a sane maximum in the event someone decided to set it to 1 million (Dr. Evil voice), but then Sonarr could search for a small number of episodes periodically and find missing episodes.

**Comment by thezoggy** [comment]
i would think sensible limits would be dependent of episode wanted vs number of series with ep wanted. doesnt make sense to backlog 5000 episodes for the same show (Starve all other shows).. thus if the ep amount for a show is greater than the amount of series that have ep wanted.. limit those greatly. now if theres 5000 series with 1 ep each.. you need to limit a different way. now you could also just exclude all things with airdate of today+ from this count.. so someone backlogging a lot of stuff doesnt just waste all their indexers hit for old stuff...
the problem with doing partial stuff is what about season packs.. 

i would think a fairly simple approach is just to limit backlog for a season for a show each time.. (not saying search for a season pack specifically.. but a lot of peoples backlog would be in fact for the whole season...) and mark it internally that this was searched for (each ep in the season gets a 1) then next time you move to the next season (previous season gets marked with 0 to reset, this next season gets marked with 1).. that way you know where you left off / easy to count later on..  then you can just grab ep wanted with that 'tally' to get an amount of stuff wanted.. then work through that however..

**Comment by bakerboy448** [comment]
closing; refer to #3067
