### ISSUE TITLE
Added torrents are not getting imported properly (rTorrent)

### ISSUE THREAD

**Issue by dahlSTROM** [Sonarr/Sonarr#762]
Hi!

I'm not sure if this problem is related to the fact that I'm remotely connecting to rTorrent, but it's probably worth mentioning it. Anyways, Sonarr successfully adds the torrents to my download client but for some reason doesn't import them to the queue, which results in all episodes being listed as "missing from disk" even though they've just been downloaded.

Debug log: http://pastebin.com/TNwKJKYS

Version: 2.0.0.3357
Mono Version: 4.0.3 (Stable 4.0.3.20/d6946b4 Tue Aug 4 09:43:57 UTC 2015)

rTorrent (test is successful):
![8b7b3999a6c0bca4f521e50284adffad](https://cloud.githubusercontent.com/assets/1389407/9437118/af1e974c-4a54-11e5-8e22-8a22391fac95.png)

**Comment by markus101** [comment]
Please use the forums for support.

You will need to setup a Remote Path Mapping to import from a Remote tTorrent setup.

**Comment by dahlSTROM** [comment]
I just thought I'd let you know that there seems to be a bug when using slashes in the category. I changed it from 'TV/Sonarr' to 'TV-Sonarr' and now everything works as expected.
