### ISSUE TITLE
Age when grabbed should not be a negative value

### ISSUE THREAD

**Issue by aptalca** [Sonarr/Sonarr#763]
I have the minimum age set to 30 min. 
Last night I noticed that the gui showed it would start downloading in 1 and a half hours. I was confused.

Then I realized that when the article was added, the age showed up as a negative number.

![capture2](https://cloud.githubusercontent.com/assets/541623/9440163/04783ffa-4a3b-11e5-89eb-fd58f1d1edc1.JPG)

Thanks

**Comment by markus101** [comment]
Womble's doesn't include a timezone with their timestamps, but the timezone is actually something other than UTC, this is something they need to fix.
