### ISSUE TITLE
Torrent BlackHole not respecting options to not delete files

### ISSUE THREAD

**Issue by aedomsan** [Sonarr/Sonarr#764]
2.0.0.3357
When using the blackhole method of download processing, despite having renames on and "remove files" off, it will delete the files occasionally

**Comment by markus101** [comment]
This is expected, Blackhole (Usenet and Torrent) and Drone Factory move files; they don't copy or hardlink files.

**Comment by aedomsan** [comment]
Do you think it would be possible to make this clearer inside the interface at all, because that seems like an exception to the norm, where every other download client option respects that option.
