### ISSUE TITLE
Show marked as "Ended" before last episode airs

### ISSUE THREAD

**Issue by aptalca** [Sonarr/Sonarr#766]
I just noticed that the show Falling Skies was marked in the UI as ended. However there is still one more episode scheduled for next sunday (I know, it's just my OCD kicking in :-)

<img width="147" alt="capture16" src="https://cloud.githubusercontent.com/assets/541623/9504087/7dc563dc-4c08-11e5-8f14-ce5ed820b383.PNG">

**Comment by thezoggy** [comment]
the data comes from tvdb..
http://thetvdb.com/?tab=series&id=205281&lid=7

currently has it as continuing.. thus your sonarr instance should update to reflect the current data..
and yes sonarr caches this info in skyhook:
http://skyhook.sonarr.tv/v1/tvdb/shows/en/205281

which has it as continuing there as well. thus at one point someone changed it to ended on tvdb.. then someone changed it back. so nothing to do and even if its wrongly changed.. sonarr doesnt really do anything differently for atleast a month..

**Comment by aptalca** [comment]
Thanks for the clarification. I was very confused because I checked tvdb as well as tvrage (not sure where sonarr got the info from) but both were showing it as continuing. It makes sense that someone changed it and sonarr cached it before someone else changed it back, lol
