### ISSUE TITLE
Support for partial episode numbers

### ISSUE THREAD

**Issue by tylermac** [Sonarr/Sonarr#771]
There are some cartoons that have two shows in a single episode. The tvdb will number each of these separately, however others will number them with a letter postfix.

The episode detection pattern could pick these up, maybe with a toggle for specific shows. So if I download `Adventure Time S01E10` and `Adventure Time S01E05a`, they can both be matched the same.

For example:

1. 01a
2. 01b
3. 02a
4. 02b
5. 03a

**Comment by markus101** [comment]
We currently have no plans to supporting split or A/B episodes, it adds a lot of complication for a limited number of occurrences.

**Comment by thezoggy** [comment]
yeah, split episodes are pretty much only used for kid shows.. which are almost never ripped how any scraper has them....  so even in your case.. if support was added it would cause ep conflicts..
