### ISSUE TITLE
Sonarr No Longer Autostarts on Windows 10

### ISSUE THREAD

**Issue by twistymcgee** [Sonarr/Sonarr#775]
I had Windows 8.1 with Sonarr installed and starting automatically on boot. I upgraded to Windows 10 and now Sonarr does not start on boot like it used to. I have to manually start it and then everything will work fine.

**Comment by markus101** [comment]
Please use our forums for support.

Knowing how its supposed to start with Windows (service or startup folder) would be required in your post. If Service check the event log for any errors.
