### ISSUE TITLE
Post processing python script

### ISSUE THREAD

**Issue by mdhiggins** [Sonarr/Sonarr#780]
I'm trying to adapt my script (sickbeard_mp4_automator) for use with Sonarr's new custom post processing script support, but having some trouble getting things to work and was wondering if there are any sample python scripts. The relevant issue with the early sample script is here:

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/286

Any help pointing me in the right direction would be appreciated

**Comment by markus101** [comment]
The only examples are here: https://github.com/Sonarr/Sonarr/wiki/Custom-Post-Processing-Scripts#specific-usage-tips

The user from the GHI posted on our forums as well after being directed there from here. https://forums.sonarr.tv/t/custom-scripts-error-on-win-7/6843

If you're having a specific issue please post on the forums as we use our forums for support.
