### ISSUE TITLE
can't update show Goede tijden slechte tijden

### ISSUE THREAD

**Issue by jixxed** [Sonarr/Sonarr#786]
the show does exist in thetvdb:
http://www.thetvdb.com/?tab=series&id=104271

error:
Error occurred while executing task RefreshSeries: HTTP request failed: [404:NotFound] [GET] at [http://skyhook.sonarr.tv/v1/tvdb/shows/en/104271]

response:
{"message":"NotFound","description":"thetvdb.com does not have a series with the tvdbid 104271, it may have been removed."}

**Comment by markus101** [comment]
Please use our forums for support next time.

Their API (and the site) don't have English information for this series. Sonarr requires English information for the series to exist on TheTVDB. If this series was previously working its likely that they removed non-English information from the English information and its caused this issue.

You may be able to add the English information for the series.
