### ISSUE TITLE
How do you uninstall on Windows?

### ISSUE THREAD

**Issue by mabasic** [Sonarr/Sonarr#787]
I have found the program in `C:\VTRoot`

Going to delete that folder and see what happens...

**Comment by markus101** [comment]
Remove from add/remove programs and remove `C:\ProgramData\NzbDrone`

**Comment by anakaine** [comment]
Removing from add\remove programs alone does not work, and the service will still be run at boot. 

Suggest that uninstall options include removing the service and deleting program folders rather than leaving a mess.

**Comment by esantelises** [comment]
To remove service:
Go to C:\ProgramData\NzbDrone\bin run serviceunistall them delete C:\ProgramData\NzbDrone.
[reference here] (https://www.reddit.com/r/usenet/comments/32v84y/sonarr_still_pulling_torrents_after_uninstall/)
