### ISSUE TITLE
Improve api docs Series Lookup

### ISSUE THREAD

**Issue by Hellowlol** [Sonarr/Sonarr#790]
https://github.com/Sonarr/Sonarr/wiki/Series-Lookup is missing a post example. Any change that could be added?

**Comment by markus101** [comment]
There is no POST, its how the UI searches for new series.

**Comment by Hellowlol** [comment]
Ah, sorry. I ment to write the addOption in api/series

**Comment by markus101** [comment]
Sorry for the delay, I'll put something together for that, in the mean time the easiest would be to inspect the calls from the WebUI to the server for that.

**Comment by Hellowlol** [comment]
Np, I have a already added that to htpc manager since it was requested but it's nice to have the api docs up to date. Thanks!
