### ISSUE TITLE
Option to start torrent in 'Paused' state

### ISSUE THREAD

**Issue by xInsertx** [Sonarr/Sonarr#795]
Self explanatory. Useful feature.

I know this is supported on deluge / transmission / qbittorrent / utorrent

**Comment by Taloth** [comment]
afaik, you can configure deluge to add in paused state by default.

**Comment by Popupkiller** [comment]
What if you don't want everything to be added as paused?

**Comment by jeremysherriff** [comment]
Hmm. I've just added a feature request in the forum for this in Transmission, as it has been implemented in qBittorrent and appeared to be an oversight for Transmission. Transmission has a new(ish) API, I wonder if it couldn't be done before but can now?
