### ISSUE TITLE
Automatically detect series type

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#796]
We might be able to use the genre (or other heuristics) to determine if the series is a daily series when it is being added, we could use this to automatically set the series type when were adding the series (let the user override it of course) to make things a bit easier.

It would be great if we did this for daily shows and anime.

**Comment by markus101** [comment]
This sounds like a good job for Skyhook to do it once.

**Comment by Taloth** [comment]
Agreed! Excellent idea.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted

Great idea...but simple enough for users, no?
