### ISSUE TITLE
Sample files being detected as Proper

### ISSUE THREAD

**Issue by Neoburner** [Sonarr/Sonarr#797]
Not too sure if it's a big issue, sample files contained in a previous file import were being identified as the primary file in Sonarr

Doing a mass Org and Rename to the files took that sample file and renamed it, wasn't until I looked back after going through 500+ episodes I had noticed!

Sonarr Ver. 2.0.0.3357
master branch

**Comment by markus101** [comment]
Please use the forums for support next time.

Sonarr uses the run time of the file to determine if it its a sample, the run time limit changes based on the run time of the series (a longer series run time allows a for a longer sample file), but this check is skipped completely for sorted files (Sonarr assumes sorted files are all wanted/not specials/etc). In this case this sample file (and any others) will need to be cleaned up manually).
