### ISSUE TITLE
Import folders with metadata in title

### ISSUE THREAD

**Issue by smitetierlist** [Sonarr/Sonarr#798]
I just tried to import a lot of series I already have. Unfortunately sonarr doesn't recognize a single series. It seems the problem is that my series folders are named like

```
Series Name (imdb id)

Example  
The Good Wife (tt1442462)
```

AFAIK all imdb id's are in the format `tt[0-9]{7}`. Maybe we can just strip IMDB id's from the title - if we can't find any result for it?

**Comment by markus101** [comment]
This has been done on the skyhook side and will take effect once it's updated.
