### ISSUE TITLE
Cutoff Unmet episodes are downloaded when the existing file was already removed

### ISSUE THREAD

**Issue by Tjiet** [Sonarr/Sonarr#801]
Using a Media profile as follows:

Name:
HD

Qualities:
1st. WEBDL-1080p
2nd. HDTV-1080p
3rd. WEBDL-720p
4th. HDTV-720p

1. An episode is downloaded in the HDTV-720p quality, the episode is watched on Plex.
2. The file is deleted within the Plex app (file deleted from filesystem)
3. The Cutoff checker does a download of quality 1, 2 or 3 (whichever comes first/available)
4. A new file is placed on the filesystem, thus making the episode unwatched again.

Solution:
Before processing the episode cutoff it needs to check if the file is deleted (filescan) this way when the episode is watched it is marked as watched and deleted in Sonarr.

This happens when some series get other qualities before the file scanner runs.

**Comment by markus101** [comment]
You will need to tell Sonarr to rescan the series folder so it will see the file is deleted, Sonarr won't check if the file exists when its deciding if release is wanted because it tracks the files internally (the reason why it needs to be updated).

**Comment by Tjiet** [comment]
You mean manually rescan the series after watched and deleted ?

**Comment by markus101** [comment]
That or have something hit Sonarr's API to do it automatically.
