### ISSUE TITLE
Advanced Options toggle while edit indexer/notification is open

### ISSUE THREAD

**Issue by smitetierlist** [Sonarr/Sonarr#802]
See, I'm interested in non-english episodes. So the categories 5030 and 5040 are almost useless. It needs to be 5020 (foreign content) usually.

It took me a good amount of time to recognize I have do enable the advanced option in the settings while the indexer is a popup/overlay. 

**For me** this was a bad user experience. Just a short heads-up here tho.

**Comment by markus101** [comment]
This is something we're looking at addressing in some UI work we are doing.

**Comment by markus101** [comment]
Will be fixed in v3.
