### ISSUE TITLE
Better handling of notification tasks when manually importing...

### ISSUE THREAD

**Issue by xInsertx** [Sonarr/Sonarr#803]
I noticed when doing a large manual import plex was not happy being notified to refresh a 100 times before the import was finished. Also the 100 notifications for pushbullet was alot of fun.... 
For message notifications can we either:
a) choose to enable/disable notifications for manual import
b) do a combined notification or group them?
c) Simple message saying Manual import completed ( 11 of 11) or ( 9 of 11 ) if any failed

For Plex / Emby / Synology tell the library to update/refresh at the end of the import not for each file.

**Comment by markus101** [comment]
It doesn't apply only to manual import and its something we have in the list already.

https://github.com/Sonarr/Sonarr/issues/363
