### ISSUE TITLE
Posters need to be shown at 500px resized on retina screens

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#804]
Webui needs to switch to 500px posters instead of 250px on retina screens

**Comment by jakepusateri** [comment]
Looking at making a PR for this that adds srcset attributes to posters. What does the 'suboptimal' tag mean? That it shouldn't actually be done?

**Comment by markus101** [comment]
`suboptimal` means its not a `bug` and not an `enhancement`. If we weren't going to do it there wouldn't be an open GHI.
