### ISSUE TITLE
Synology Download Station support

### ISSUE THREAD

**Issue by boyahr** [Sonarr/Sonarr#810]
You've probably been asked its support before, but I don't know if you don't want to add it or have other reasons not to support it.  Anyway, could you please (re)consider adding the Download Station to sonarr ?  It's the only thing I miss from Sickrage.

Thanks for your awesome work

**Comment by markus101** [comment]
This is already in the list: https://github.com/Sonarr/Sonarr/issues/347

Right there at the bottom:

https://github.com/Sonarr/Sonarr/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+synology
