### ISSUE TITLE
drone factory lsof

### ISSUE THREAD

**Issue by Kija** [Sonarr/Sonarr#814]
I am sending new files to the drone factory directory through ftp, and some times transfers can be slow.
I'd like to make sure files aren't moved before the end of the ftp transfer.
Some sort of open file check before moving any files would be great.
Maybe just adding an .ignore extension to unfinished files would work.

**Comment by markus101** [comment]
Drone Factory is not recommended, use Remote Path Mapping and mount the file system locally with something like SSHFS and Sonarr will import it. If the extension is not known for to be a video file (`.ignore` for example), Sonarr won't import it, so you should be able to handle this case automatically by having your client set the extension, we're not going to handle this in a customized way within Sonarr though.

**Comment by Taloth** [comment]
Related: https://github.com/Sonarr/Sonarr/issues/282
