### ISSUE TITLE
how to use TorrentRssIndexer ?

### ISSUE THREAD

**Issue by hemantmits** [Sonarr/Sonarr#820]
Can someone please explain how to use TorrentRssIndexer ?
I have following rss feed link
 `https://kat.cr/usearch/user:SCSA420/?rss=1`
How do I add it with some series search preference ( say WWE )?
Can I do it or my understanding of rss feed usage in Sonarr is wrong?
I tried google but can only find much information.

**Comment by markus101** [comment]
Please use the forums for support.

You would use the proper KAT integration with Sonarr. Adding an RSS feed doesn't let Sonarr download things it doesn't know about (it needs the information available on TheTVDB to match it). You'll need to use another application to do this.

**Comment by hemantmits** [comment]
Thanks for quick reply. 
I will post it on forum.
