### ISSUE TITLE
Does not show on launch on OS X 

### ISSUE THREAD

**Issue by tomtclai** [Sonarr/Sonarr#821]
Title. 
Brief discussion at https://github.com/victorpimentel/TVShows/issues/78#issuecomment-144799664

I can still access Sonarr by going to http://localhost:8989 on a browser. But it causes confusion for new users

**Comment by markus101** [comment]
This has always been the case for OS X and Linux, on Windows it only opens the browser if the tray icon is used.

**Comment by jefbarn** [comment]
Sonarr-Menu adds this functionality.
https://github.com/jefbarn/Sonarr-Menu/

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
