### ISSUE TITLE
Run pragma integrity_check on db

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#822]
Sometimes we get odd exceptions in Sonarr that eventually get traced to DB corruption. Either some flashcard, or OSX or something else.
It might be a good idea to run the Sonarr bootstrap in several phases, one that inits and signal service startup to windows, two that verifies and compacts db, three startup UI.

**Comment by bakerboy448** [comment]
@Taloth slight bump here;  plans for this or close?

**Comment by markus101** [comment]
Going to close this one out and tag for future review.
