### ISSUE TITLE
Moving Torrents

### ISSUE THREAD

**Issue by L33B0B** [Sonarr/Sonarr#823]
Sonarr all of a sudden is having trubble moving torrents i get. i have to a forced import for each one.. any reason why? i've just updated to the latest develop version incase there was an issue with it. but its made no difference. The server can see the location it needs to move it from and too with no issues when browsing to them. and has correct privlages to both locations..
Any ideas?

**Comment by markus101** [comment]
Please use our forums for support.

Check debug logs to see why its not importing.
