### ISSUE TITLE
Add option to influence grabbing of season packs

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#825]
Sometimes users prefer to disable season packs particularly via torrents, preferring to wait for single episodes on usenet instead. Mostly due to season packs be more prevalent on torrents over usenet, but also due to seeding requirements.
Of course this only applies for older seasons, since for current seasons the user likely has one or more episodes, blocking the season pack.

There are various ways we could affect this behavior, per indexer, in the delay profile, standard profile etc.

Personally it feels like a 1% feature, but there seem to be some valid concerns.

**Comment by markus101** [comment]
Another use case for this would be shows that are released in dumps, usually available within a few days, so it would be advantageous to wait a few days for the full season pack and to grab that, especially on sites that group full seasons up after they are released (ie BTN).

**Comment by harroguk** [comment]
The specific problem I encountered is that I added an old TV Show and the searcher grabbed some of the individual episodes that were available (via a combination of NZB and torrents) but as some individual episodes were not available. I then had to manually go in and download a season pack anyway.

Essentially when a series is added it should (IMO) do a search prioritising Season Packs. After that search is concluded it should proceed to search based on episodes again.

**Comment by mattmac24** [comment]
Are there any thoughts on implementing this?

**Comment by haljordan2814** [comment]
I definitely need the option of not downloading any season packs at all. I use a VPS which has very limited local disk space. All content is instantly shipped off to the cloud via rclone. This system works fantastically with any size individual episode file, but crumbles under the weight of large season packs. Basically I need to be able to tell sonarr to never look for season packs.  Thanks for active development on Sonarr.

**Comment by systemmonkey42** [comment]
I'm having a high failure rate with massive season packs which either exceed my quote, fill my disk, or fail due to nzb missing blocks.

I would love a button to simply turn off season packs...  Additional options to do so per show, or per season (defaulting to the global settings) would be _nice_, but essentially overkill.

A single kill switch for season downloads would suit me perfectly.

**Comment by markus101** [comment]
Size seems to be the reason why most people want to prevent season packs from being grabbed, you'll be able to set a maximum download size on the indexer settings page that prevents any release larger than that limit from being grabbed. As of this post it's not yet available in the stable release, but will be in the next release (whenever that is).

More information in: https://github.com/Sonarr/Sonarr/issues/1996

**Comment by 12nick12** [comment]
I would also love a button to turn off or not prefer season packs. 7/10 times they don't work.

**Comment by mcmasterp** [comment]
I also would prefer this as the seasons don't seem reliable and I end up having to interactively search and download each episode from usenet
