### ISSUE TITLE
Ignore latest season during add-series if all episodes aired over 1 year ago

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#826]
If they all aired over a year ago its likely the same season won't be used for new episodes, even in split seasons.

This could cause issues with a series that used the same season number for a split season that happened over 1 year apart and the new episodes weren't listed.

**Comment by markus101** [comment]
This should also apply to season pass (same logic) and 1 year is probably too crazy. 90 days would handle almost everything and even 30 days would handle most without causing future episodes to be ignored.

**Comment by markus101** [comment]
Suits takes a mid season break for about 4 months (Sept - Jan) and Breaking bad took and almost 1 year break in the final season.  This is edge casey at the very least.

**Comment by antigravity83** [comment]
Ok great thank you for the update.
