### ISSUE TITLE
Previous and Next buttons on series details page

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#827]
This would provide a way to cycle through series while on the series details page for a specific series. The order would be alphabetical by `sortTitle`, not the order returned from the sever or as sorted on the series list page.

**Comment by lcmullins** [comment]
Yes, please....

**Comment by kelemvor33** [comment]
Yes please.  Would really love this.

**Comment by lcmullins** [comment]
+1  Could really use this feature.  Thanks for your consideration.

**Comment by markus101** [comment]
Will be added in v3.
