### ISSUE TITLE
Inline search for log

### ISSUE THREAD

**Issue by naaronne** [Sonarr/Sonarr#828]
Looking to be able to index and search the sonarr log from within the application.  It would be nice to use keywords when troubleshooting or just looking around.

![image](https://cloud.githubusercontent.com/assets/10212075/10268361/1d651b5a-6a84-11e5-8150-6dae5224b38a.png)

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR

Just use any text editor to search the actual log files....most use cases of searching will need trace or debug anyway
also Cntrl-F exists
