### ISSUE TITLE
API Wanted missing, date parameter doesn't work

### ISSUE THREAD

**Issue by raspdealer** [Sonarr/Sonarr#829]
Based on that : https://github.com/Sonarr/Sonarr/wiki/Wanted-Missing

With that request : 
`http://192.168.1.116:8989/api/wanted/missing?page=1&pageSize=10&sortKey=series.date&apikey=f74f89a1dfc049c696db0e3ac4a296dc`

I get this error : 
 ` "message": "Instance property 'date' is not defined for type 'NzbDrone.Core.Tv.Series'",
  "description": "System.ArgumentException: Instance property 'date' is not defined for type 'NzbDrone.Core.Tv.Series'\nat System.Linq.Expressions.Expression.Property `

title parameter works fine.

**Comment by markus101** [comment]
It should be `airDateUtc` I've updated the docs.
