### ISSUE TITLE
API Command : Refresh Series error

### ISSUE THREAD

**Issue by raspdealer** [Sonarr/Sonarr#830]
Hi,

The title is clear.
Here is my request and result.
X-Api-Key is in header and works in GET queries

<img width="702" alt="command" src="https://cloud.githubusercontent.com/assets/3975358/10269943/d6eaae96-6ae3-11e5-826e-c3a5c658a391.PNG">

**Comment by Taloth** [comment]
Please don't spam GH with these kind of things. Use the forum for support requests.

Might I suggest you just use the dev console to the calls that the UI does on the API to see if you're encoding requests correctly?
