### ISSUE TITLE
Sonnar Epic fail

### ISSUE THREAD

**Issue by firman13** [Sonarr/Sonarr#831]
Here is the log

15-10-5 09:36:37.1|Info|Bootstrap|Starting Sonarr - /Applications/Sonarr.app/Contents/MacOS/NzbDrone.exe - Version 2.0.0.3357
15-10-5 09:36:39.5|Debug|ProcessProvider|Found 0 processes with the name: NzbDrone.Console
15-10-5 09:36:41.1|Debug|ProcessProvider|Found 0 processes with the name: NzbDrone
15-10-5 09:36:41.3|Info|MigrationLogger|**\* Migrating data source=/Users/firman/.config/NzbDrone/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Truncate;pooling=True;version=3;Full FSync=True ***
15-10-5 09:36:41.5|Debug|MigrationLogger|Took: 00:00:00.2195699
15-10-5 09:36:41.5|Info|MigrationLogger|**\* Migrating data source=/Users/firman/.config/NzbDrone/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Truncate;pooling=True;version=3;Full FSync=True ***
15-10-5 09:36:41.6|Fatal|ConsoleApp|EPIC FAIL!

System.Data.SQLite.SQLiteException: database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, UInt32 timeoutMS, System.String& strRemain) in <filename unknown>:line 0
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand () in <filename unknown>:line 0

What is happening? Sonarr will not boot now on my OS X with El Capitan

**Comment by markus101** [comment]
Not sure why this is just showing up now, but for anyone that stumbles across it.

https://wiki.servarr.com/en/sonarr/faq#i-am-getting-an-error-database-disk-image-is-malformed

**Comment by stevietv** [comment]
And perhaps a good time to update from v2 :)
