### ISSUE TITLE
Detection of multiple episodes in one file across season boundry

### ISSUE THREAD

**Issue by omega1970** [Sonarr/Sonarr#834]
Hello,

It seems the parsing of a double episode that goes over to the next season is not detected from the file name.

Episode naming setting: Range / Prefixed Range
Episode name: Star.Trek-.The.Next.Generation.S03E26-S04E01.The.Best.of.Both.Worlds.mkv

In both cases only S03E26 is detected correctly and S04E01 shows up as missing.

Can you have a look at this?

EDIT: Using Sonarr v2.0.0.3357

**Comment by markus101** [comment]
This is expected, Sonarr will only track files that exist in one season. We do not have plans at this time to support this rare scenario.
