### ISSUE TITLE
IPv6 Support on mono

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#835]
Looks like IPv6 works on Windows, but doesn't on OS X (and possibly other systems running mono).

**Comment by revellion** [comment]
Any changes in this?

**Comment by karolaug** [comment]
It si still not working. Would be nice to have Sonarr listen on ipv6.

**Comment by crcarlin** [comment]
Is this a problem with Sonarr or with mono? I'd like to dig into it a bit, but I'm not sure which end to focus on.

**Comment by markus101** [comment]
Not sure, we're planning to change the webserver so we're not tied to http.sys on Windows and mono's implementation of that on other platforms (not sure when that will be though).

**Comment by crcarlin** [comment]
Well, I'd first ask what this comment meant. It sounded like "AddressFamily.InterNetwork || AddressFamily.InterNetworkV6" needed to be turned on except for an issue happening in 2014.
 
[https://github.com/Sonarr/Sonarr/pull/120#r18356178](https://github.com/Sonarr/Sonarr/pull/120#r18356178)


Buuuuuuuuuut, other than that, I hate to say it, but glancing at the xamarin bugtracker, there are a few IPv6 issues that haven't been updated in a long time. I'm guessing it's a problem on their end.

[see here](https://bugzilla.xamarin.com/buglist.cgi?bug_status=NEW&bug_status=CONFIRMED&bug_status=ASSIGNED&bug_status=IN_PROGRESS&bug_status=NEEDINFO&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=REOPENED&bug_status=CLOSED&f0=OP&f1=OP&f2=product&f3=component&f4=alias&f5=short_desc&f7=content&f8=CP&f9=CP&j1=OR&o2=substring&o3=substring&o4=substring&o5=substring&o6=substring&o7=matches&query_format=advanced&short_desc=ipv6&short_desc_type=allwordssubstr&v2=ipv6&v3=ipv6&v4=ipv6&v5=ipv6&v6=ipv6&v7=%22ipv6%22)

**Comment by markus101** [comment]
Looks like that's only for binding to a specific IPv6 address, but using a wildcard also listens on IPV6.

Good to know about the open issues, may be nothing for us to do here.

**Comment by phit42** [comment]
For whatever strange reason, using the wildcard <BindAddress>*</BindAddress> worked for quite some time to listen on IPV6 on a Synology DSM (in a local network and with SSL turned off), but recently stopped working. I can see that mono is only listening on "tcp        0      0 0.0.0.0:8989            0.0.0.0:*" , but not on "tcp6       0      0 :::8989                  :::*" anymore.

**Comment by Astan92** [comment]
I'm not sure if this is related but I am hosting jackett on a server that only has an IPv6 address. When trying to add a Torznab indexer from it I am getting this error in the logs.

`[v2.0.0.4949] System.ArgumentException: Uri didn't match expected pattern: http://[IPv6 ADDRESS]:PORT/api/v2.0/indexers/INDEXER/results/torznab/api?t=caps&apikey=(removed)  at NzbDrone.Common.Http.HttpUri.P$
  at NzbDrone.Common.Http.HttpUri..ctor (System.String uri) [0x00016] in <c1f685cfea004829ae7197374125cdfd>:0
  at NzbDrone.Common.Http.HttpRequest..ctor (System.String url, NzbDrone.Common.Http.HttpAccept httpAccept) [0x00006] in <c1f685cfea004829ae7197374125cdfd>:0
  at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities (NzbDrone.Core.Indexers.Newznab.NewznabSettings indexerSettings) [0x0005c] in <e8ad39d438bc4c448bfbd968b0f74ec6>:0
  at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider+<>c__DisplayClass4_0.<GetCapabilities>b__0 () [0x00000] in <e8ad39d438bc4c448bfbd968b0f74ec6>:0
  at NzbDrone.Common.Cache.Cached`1[T].Get (System.String key, System.Func`1[TResult] function, System.Nullable`1[T] lifeTime) [0x0006a] in <c1f685cfea004829ae7197374125cdfd>:0
  at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities (NzbDrone.Core.Indexers.Newznab.NewznabSettings indexerSettings) [0x00046] in <e8ad39d438bc4c448bfbd968b0f74ec6>:0
  at NzbDrone.Core.Indexers.Torznab.Torznab.get_PageSize () [0x0000c] in <e8ad39d438bc4c448bfbd968b0f74ec6>:0
  at NzbDrone.Core.Indexers.Torznab.Torznab.GetRequestGenerator () [0x0000b] in <e8ad39d438bc4c448bfbd968b0f74ec6>:0
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00007] in <e8ad39d438bc4c448bfbd968b0f74ec6>:0
`

**Comment by crcarlin** [comment]
Ah! Looks like there was some movement on IPv6 in Mono in March.

I should revisit this to see if it binds on my server.

https://bugzilla.xamarin.com/show_bug.cgi?id=40969

(Sorry this doesn't directly address your comment, Astan92, but it means the playing field has shifted since last time I looked into this)

**Comment by Piottreck** [comment]
If I am not mistaken what you linked is only a fix for Mac OS.

**Comment by crcarlin** [comment]
Just to give an update (partly for my own reference):

BindAddress of * still doesn't bind to IPv6. The log shows OwinHostController listening on http://*:8081/

Specifying the IPv6 address manually does bind to IPv6, but connecting returns only an invalid host message with nothing in the logbook. But, this makes me think IPv6 would work if the wildcard binding was passed correctly.

I've read that + is a wildcard to capture IPv6 as well, so manually editing config.xml to have BindAddress of + gives the following.
> Info|OwinHostController|Listening on the following URLs:
> Info|OwinHostController|  http://+:8081/
> Info|OwinHostController|  http://localhost:8081/
> NancyBootstrapper|Starting Web Server
> Fatal|ConsoleApp|Address already in use. This can happen if another instance of Sonarr is already running another application is using the same port (default: 8989) or the user has insufficient permissions

Could this be failing because localhost is trying to bind what + already bound? Where does the localhost bind come from? The exact same thing happens if I replace + with [::], so maybe the localhost addition is shooting something in the foot?

Sonarr 2.0.0.5054
Ubuntu 16.04.3 LTS
Mono 4.2.1.102-0xamarin1

**Comment by comnam90** [comment]
How are we getting on with IPv6 Support?

**Comment by satmandu** [comment]
Does this work?

I can't get a AAAA only record to work in the bind address field in the settings window.

I get this error message: "Valid IP4 address or '*' for all interfaces"

**Comment by samip5** [comment]
Okey. This issue is still persisting.

Sonarr container has internal port 8989 exposed on host as 27021, but it gives just Bad Request error.

You can get Sonarr to listen on v6 by manually editing config.xml's BindAddress in this format: <BindAddress>[2001:DB8:1::1]</BindAddress> but the attached image is the result.

https://user-images.githubusercontent.com/1703002/102705823-60b50080-4294-11eb-9fe6-3b587849ad08.png

**Comment by christopher2505** [comment]
I'm running Sonarr with Docker and also can't accesss it over the ipv6 address. 

My error messages are: 

`Bad Request (Invalid url: http://[2001:8989/)`
or 
`Bad Request (Invalid url: http://[fe80:8989/sonarr)`

Radarr with the same setup is not showing this error.

**Comment by bakerboy448** [comment]
@christopher2505 that does not look like a valid IP6

also posts effective to "me too" are highly frowned upon

**Comment by samip5** [comment]
I have a strong believe that this is just related to the webserver Sonarr uses under mono as Radarr does not use mono, and thus does not have the issue. The error also related to the webserver to my eye.

@bakerboy448 The error message even with valid v6, does not output the full address for whatever reason.

**Comment by christopher2505** [comment]
@bakerboy448 
I'm accessing it with a valid ipv6 address. 
This error message is cutting away parts of it. I postet to give the hint with radarr and help other find this post when searching the error message.

**Comment by satmandu** [comment]
Isn't this still a mono issue? IIRC this was going to be hopefully resolved at some point by trying to use the Linux distributions of .Net  in lieu of using mono, no?

**Comment by falahati** [comment]
we also cant add any connection (indexer, download client, etc) using ipv6 simple due to the fact that the validation for ipv6 addresses fail on frontend. this should be an easy fix

**Comment by bakerboy448** [comment]
Not an easy fix when mono has issues with ipv6; seems you ignored the thread

regardless this should get resolved with the switch to .net6 which is slowly in the works...TBD eventually...

**Comment by falahati** [comment]
@bakerboy448 meant the validation fix should be easy; in fact, the comment was in comparison to the other ipv6 issues discussed here.

**Comment by TheWidowLicker** [comment]
> Figured I'd write a reply for people like me that are googling the issue looking for a solution. Ipv6 works, at least on debian stretch with "Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1)", but only if you do it a particular way.
> 
> First, what _WON'T_ work is if you change the line in config.xml from `<BindAddress>*</BindAddress>` to e.g `<BindAddress>fdda:bfbf:b:f::123</BindAddress>` doing so causes sonarr to crash on startup.
> 
> What will work is creating a AAAA record on a domain you own and using that domain name. Do that and everything works fine. Meaning you set bind address to for example `<BindAddress>AAAAonly.example.com</BindAddress>`. If you do that sonarr will successfully be bound to the ipv6 address pointed to by AAAAonly. Note if the domain name has an A and AAAA record then it doesn't seem to work, but again errors on startup.
> 
> The same goes for using the webgui to configure the sabnzbdplus connection. If you enter a specific ipv6 address in the host field you get the error "must be valid Host without http://". But enter a domain name with only an AAAA record (e.g AAAAonly.example.com) and everything works hunky-dory.
> 
> For the developers: When attempting to startup with bindadress set to either `fdda:bfbf:b:f::123` or `[fdda:bfbf:b:f::123]` the console output is
> 
> ```
> [Info] OwinHostController: Listening on the following URLs:
> [Info] OwinHostController:   http://fdda:bfbf:b:f::123:8083/
> [Info] OwinHostController:   http://localhost:8083/
> [Info] NancyBootstrapper: Starting Web Server
> 
> 
> [Fatal] ConsoleApp: EPIC FAIL!
> 
> [v2.0.0.5228] System.ArgumentException: Invalid port.
>   at NzbDrone.Host.Owin.OwinAppFactory.CreateApp (System.Collections.Generic.List`1[T] urls) [0x000a0] in <9b2a95f0b2a841b1ab89c8a2a5967336>:0
>   at NzbDrone.Host.Owin.OwinHostController.StartServer () [0x0009c] in <9b2a95f0b2a841b1ab89c8a2a5967336>:0
>   at NzbDrone.Host.NzbDroneServiceFactory.Start () [0x00042] in <9b2a95f0b2a841b1ab89c8a2a5967336>:0
>   at NzbDrone.Host.Router.Route (NzbDrone.Host.ApplicationModes applicationModes) [0x0007b] in <9b2a95f0b2a841b1ab89c8a2a5967336>:0
>   at NzbDrone.Host.Bootstrap.Start (NzbDrone.Host.ApplicationModes applicationModes, NzbDrone.Common.EnvironmentInfo.StartupContext startupContext) [0x00047] in <9b2a95f0b2a841b1ab89c8a2a5967336>:0
>   at NzbDrone.Host.Bootstrap.Start (NzbDrone.Common.EnvironmentInfo.StartupContext startupContext, NzbDrone.Host.IUserAlert userAlert, System.Action`1[T] startCallback) [0x00075] in <9b2a95f0b2a841b1ab89c8a2a5967336>:0
>   at NzbDrone.Console.ConsoleApp.Main (System.String[] args) [0x0002f] in <749f1419727b4f628034fdacb2834eb4>:0
> 
> Press enter to exit...
> ```
> 
> Starting with a bindadress set to a domain name with only a AAAA record works fine and I can access sonar using AAAAonly.example.com:8083 for example `curl -v http://AAAAonly.example.com`
> 
> ```
> *   Trying fdda:bfbf:b:f::123...
> * TCP_NODELAY set
> * Connected to AAAAonly.example.com (fdda:bfbf:b:f::123) port 8083 (#0)
> > GET / HTTP/1.1
> > Host: AAAAonly.example.com:8083
> > User-Agent: curl/7.61.0
> > Accept: */*
> >
> < HTTP/1.1 401 Unauthorized
> < X-ApplicationVersion: 2.0.0.5228
> < Cache-Control: no-cache, no-store, must-revalidate
> < Pragma: no-cache
> < Expires: 0
> < WWW-Authenticate: Basic realm="Sonarr"
> < Content-Type: text/html
> < Server: Mono-HTTPAPI/1.0`
> < Date: Sun, 02 Sep 2018 14:08:09 GMT
> < Content-Length: 0
> < Keep-Alive: timeout=15,max=100
> <
> * Connection #0 to host AAAAonly.example.com left intact```
> ```

Spent hours trying to get this to work and this solved it.
Setup an AAAA record in my domain. used that in the bind address and all was good.
Terrible to have to do it but there you go. Maybe setup a 1 off duckdns AAAA record an bind to that

**Comment by joachimtingvold** [comment]
I tried to fix this using the hostname-workaround described above. I did the following;

1. Add custom script to `/config/custom-cont-init.d` (assumes you're using the `linuxserver/sonarr` image, with the following content;
```
#!/bin/bash
apt install -y net-tools
get_ipv6_cmd="ifconfig eth0 | grep inet6 | grep -v fe80 | head -1 | awk '{ print \$2 }'"
ipv6_count=$(bash -c "$get_ipv6_cmd" | wc -l | perl -wple 's,\s+,,g')
if [ "$ipv6_count" -eq 1 ]; then
  echo "$(bash -c "$get_ipv6_cmd") ipv6.local" >> /etc/hosts
fi
```
2. The custom scripts adds host entry with IPv6 address only to `/etc/hosts`:
```
root@aac30aacacb4:/# grep ipv6 /etc/hosts
fd10:255:2::2 ipv6.local
```
3. Added `<BindAddress>ipv6.local</BindAddress>` to `config.xml`
4. Sonarr now binds successfully to IPv6:
```
root@aac30aacacb4:/# netstat -aln
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp6       0      0 ::1:8989                :::*                    LISTEN
tcp6       0      0 fd10:255:2::2:8989      :::*                    LISTEN
```

However, I still get the "Bad Request" error;

![image](https://user-images.githubusercontent.com/359918/154813326-fc343d9d-e55a-4383-b737-a6ed59c7ae28.png)

... which is probably because I'm trying to access the website using the IPv6 address of the Docker host (which Sonarr can't interpret in terms of the URL used).

If I then add a local entry in `/etc/hosts` for the IPv6 address of the Docker host, the error changes to "Invalid host";

![image](https://user-images.githubusercontent.com/359918/154813423-a58b939f-f839-4124-83cb-1683ee363d7d.png)

Changing the local entry in `/etc/hosts` to match that used as `BindAddress`, it works;

![image](https://user-images.githubusercontent.com/359918/154813473-21394c72-b415-48ea-b4e2-4767e9dca184.png)

It works. But it's ugly. All the other *arr applications works just fine with IPv6, as a comparison.

**Comment by joachimtingvold** [comment]
Adding to the above; after setting `BindAddress` in `config.xml` manually, you can never save the "Settings -> General" page via the GUI anymore, as it results in 400 Bad Request:

```
[
  {
    "propertyName": "BindAddress",
    "errorMessage": "Must contain wildcard (*) or a valid IPv4 Address",
    "attemptedValue": "ipv6.local",
    "severity": "error",
    "errorCode": "PredicateValidator",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Bind Address",
      "propertyValue": "ipv6.local"
    }
  }
]
```

Could we at least fix these things on the Sonarr side, regardless of what the status of IPv6-support in Mono is?

**Comment by bakerboy448** [comment]
There's nothing to fix since it's not supported on not-windows and with v4/dotnet coming eventually - it doesn't particularly make sense for the additional effort to specifically and conditionally support ipv6 on windows which would then need to be reverted.

Dev Time is precious as it is.

**Comment by markus101** [comment]
This will come with the switch from mono to dotnet in v4.
