### ISSUE TITLE
Release is not matched to an episode correctly

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#836]
Looks straight forward but the episode isn't matching:

![image](https://cloud.githubusercontent.com/assets/413544/10300270/0e8c1392-6ba9-11e5-8027-89e7a98288f9.png)

We should also show a better error message and `1.0 GB` is greater than maximum allowed `0 B`

**Comment by markus101** [comment]
I can no longer reproduce this issue, if it happens again we'll need to investigate.

**Comment by LindsayCole** [comment]
Happens to me with Metalocalypse.

**Comment by asyba** [comment]
Happens to me with Doctor Who (2005)	0x148	The Husbands of River Song

**Comment by aaronwinning** [comment]
same issue happens to me with the above doctor who episode as well :(
