### ISSUE TITLE
Blackhole doesn't treat previous grab as meeting cutoff

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#837]
Normally Sonarr relies on the queue to determine if the cutoff has been met by an item in the queue, but with blackhole it doesn't have a queue to track, in this scenario Sonarr should use its history to see if the history if the cutoff has been met, until it knows otherwise (failed or completed).

**Comment by Taloth** [comment]
Would write a spec with a temporary block that checks if there's a recent history grab event without DownloadId.
