### ISSUE TITLE
Torrents showing as no seeds and therefore not auto downloading

### ISSUE THREAD

**Issue by Fma965** [Sonarr/Sonarr#840]
![screen](http://i.imgur.com/WGaUEWX.png)
![screen](http://i.imgur.com/AvYGJNM.png)

Sorry forgot to mention this only happens on Kickass.to

**Comment by markus101** [comment]
Please use the forums for support. There are a few threads on this topic already. This is a KAT issue, though we will be releasing a workaround.

**Comment by Fma965** [comment]
Thanks for your help, i did search google but didn't find much results, i see now your forums have a few duplicate threads about this issue.
