### ISSUE TITLE
Wrong episode count Season unmonitored but episodes not 

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#845]
Monitored episodes in unmonitored seasons count toward series episode count.

**Comment by markus101** [comment]
How is the count wrong?

Season monitoring is a toggle for all episodes in the season, not its own state that we track. Its also used when adding new episodes to a season, if the season is not monitored the new episodes are not monitored, if it is the new episodes are monitored.

Monitored episodes are still counted in the episode count for the series and the season as well.

**Comment by Taloth** [comment]
Fixed by 7af7c2003e31eca094d2383fde826e49edf10d6a
Or actually, that puts the specials in Wanted too.
