### ISSUE TITLE
Sonarr grabbing lower quality dupes while higher quality episodes being imported

### ISSUE THREAD

**Issue by sea3pea0** [Sonarr/Sonarr#847]
I am using remote path mapping with an sshfs mount and it takes a while for episodes to be copied over WAN. While the copying is taking place, Sonarr will continue to grab the same episode while the copying is taking place. For example, Sonarr grabbed Limitless.S01E03.1080p.HDTV.X264-DIMENSION which is a 4.05gb episode and while that file was in the process of being imported Sonarr grabbed Limitless.S01E03.The.Legend.of.Marcos.Ramos.1080p.WEB-DL.DD5.1.H.264-CtrlHD which is a 1.58gb file. Sonarr finished importing first one and then later recycled it and replaced it with the 1.58gb file. In other words Sonarr downgraded from the episode 1080p to 1080-webdl. I'm using the default HD-All profile with the cutoff being 720p-HDTV. This is not an isolated case, this happens regularly and causes a lot of unnecessary data transfer. It would be great if there were a solution to prevent this scenario from happening. 

Here's some more info about my setup: I am using Sonarr Ver. 2.0.0.3501 develop. I am using rTorrent on a remote machine across WAN. I have an sshfs mount. I have remote paths mapped to the Synology box Sonarr is running on.

**Comment by markus101** [comment]
Closing.

1. WEBDL 1080p is higher than HDTV 1080p
2. As discussed on IRC, items aren't in the queue, so Sonarr doesn't know its downloading.
