### ISSUE TITLE
Indexer download delay (minimum age) is handled incorrectly

### ISSUE THREAD

**Issue by aptalca** [Sonarr/Sonarr#848]
Hi,

I noticed that lately the indexer download delay is handled incorrectly. I'm using version 2.0.0.3357 in an ubuntu based docker.

Below are some screenshots taken in succession. The first one shows the minimum age set to 30 min. The second shows the manual search window identifying the age of the release as 52 min. Yet, the 3rd screenshot shows the download being delayed for another 20+ min.

Any ideas why sonarr still delays it even though the age is over the minimum limit? Please let me know if you need any logs or other info.

Thanks

![capture10](https://cloud.githubusercontent.com/assets/541623/10384927/7fac20f8-6e10-11e5-83d9-c2f9221c5d8b.JPG)
![capture11](https://cloud.githubusercontent.com/assets/541623/10384928/853f806e-6e10-11e5-8177-60a066030e3c.JPG)
![capture12](https://cloud.githubusercontent.com/assets/541623/10384933/8edbf364-6e10-11e5-9840-348f8bcaf5ab.JPG)

PS, the log only shows that during the RSS sync at 22:18, one report became pending. I don't know how it got delayed until 23:19

```
15-10-8 21:48:07.7|Info|RssSyncService|Starting RSS Sync
15-10-8 21:48:10.1|Info|DownloadDecisionMaker|Processing 400 releases
15-10-8 21:48:12.0|Info|RssSyncService|RSS Sync Completed. Reports found: 400, Reports grabbed: 0
15-10-8 22:18:38.6|Info|RssSyncService|Starting RSS Sync
15-10-8 22:18:41.0|Info|DownloadDecisionMaker|Processing 400 releases
15-10-8 22:18:42.9|Info|RssSyncService|RSS Sync Completed. Reports found: 400, Reports grabbed: 0, Reports pending: 1
15-10-8 22:49:09.6|Info|RssSyncService|Starting RSS Sync
15-10-8 22:49:12.0|Info|DownloadDecisionMaker|Processing 401 releases
15-10-8 22:49:14.0|Info|RssSyncService|RSS Sync Completed. Reports found: 401, Reports grabbed: 0, Reports pending: 1
```

**Comment by markus101** [comment]
Please use the forums for support.

Check for a delay profile with a long delay, if there is still a concern open a thread on the forums with debug logs of an RSS sync with a delayed item.
