### ISSUE TITLE
Change episode wanted state based on download percentage

### ISSUE THREAD

**Issue by the0neWhoKnocks** [Sonarr/Sonarr#851]
My setup isn't a typical one. Basically I have nzbget process my files into an "unwatched" directory which isn't the main library directory that Sonarr watches. If iI go to Calendar it always says the files reached 100% but it doesn't remove the wanted status. 

Is there a way to tell Sonarr via a config option or the API to remove the wanted status once the nzb is sent to my client or the file percentage has reached 100%?

I've been searching posts and forums for a while and haven't found anything useful yet. Any help or suggestions would be appreciated.

**Comment by markus101** [comment]
This is what you're looking for: https://github.com/Sonarr/Sonarr/issues/329
