### ISSUE TITLE
Date Parsing Issue?

### ISSUE THREAD

**Issue by Gerk** [Sonarr/Sonarr#853]
Version: 2.0.0.3357
Mono Version: 4.0.3 ((detached/d6946b4 Wed Jul 29 14:46:23 EDT 2015)

Series:  Gold Rush, Season 6
Sonarr thinks S06E03 is 9 days in the past, thetvdb shows correct (in the future) date.  Not sure if this is just something odd with my system or if it's having ahard time parsing 10-30-2015 for some reason.

![screen shot 2015-10-13 at 8 47 00 am](https://cloud.githubusercontent.com/assets/172505/10455130/84a435f8-7187-11e5-8403-12346d869f1a.png)

![screen shot 2015-10-13 at 8 47 15 am](https://cloud.githubusercontent.com/assets/172505/10455134/89762cee-7187-11e5-85ec-a7fedc5898d0.png)

**Comment by markus101** [comment]
Looks like it was cached data in our proxy, refreshing the series should fix that up.

**Comment by Gerk** [comment]
Perfect, that solved it thx.
