### ISSUE TITLE
rename bulk episodes have bad ux

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#858]
![sonarr151](http://zoggy.net/sonarr151.png)

so you put newest ep up top, which is good as most likely that is what people want to rename.. but it defaults to all checked, so if you want to uncheck all then only do the top few episodes in this case.. you have to scroll to the bottom.. uncheck all.. then scroll to top to check off what i want.. then scroll back down to do rename. quite a bad ux

this really comes into play when a season has a lot of episodes / theres a lot of episode differences (daily shows are the worst at that)

also to note, you show the tool tip for the checkbox, which besides being offset, get in the way for you to click on multiple checkboxes as you end up clicking on the tooltips instead

**Comment by markus101** [comment]
This has been addressed in v3 work.
