### ISSUE TITLE
activity vs queue - out of sync at times

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#859]
sometimes I'll fetch an ep because sonarr just hasn't gotten it yet.. only to find out sonarr and I both grabbed the ep around the same time.. or if one is grabbed but flagged as duplicate or blacklisted.. etc there seems to be a delay between activity and the queue.. where you see this sort of issue:

![sonarr149](http://zoggy.net/sonarr149.png)

**Comment by markus101** [comment]
This should be handled better in v3, though there is a short delay between it being queued and the UI reflecting that. We can re-evaluate once v3 lands.
