### ISSUE TITLE
[Naming] Add foreign Series/Episode title as variable

### ISSUE THREAD

**Issue by smitetierlist** [Sonarr/Sonarr#862]
Basically title.

I'm not 100% sure if this functionality is already there but it seems it's not.

My Episode title format is like

    S{season:00}E{episode:00} - {Episode Title} ({Quality Title} {MediaInfo Full})

And I would love to do it like this:

    S{season:00}E{episode:00} - {Episode Title:de,en} ({Quality Title} {MediaInfo Full})

Try to set the german title. Use english as fallback language.

**Comment by markus101** [comment]
Sonarr only has the English information for series, if foreign languages are supported Sonarr will only have the information in that language it won't have both English and the other language, so this isn't going to be possible.
