### ISSUE TITLE
ep airing date change to just time for day of events

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#863]
recent change to ep airing the day of, with **Show Relative Dates**
![sonarr146](http://zoggy.net/sonarr146.png)

this change affects those that DO and DONT use `Show Relative Dates`.. is this on purpose?

**Comment by markus101** [comment]
Yes this was intentional, personally the date seems a lot less important when its airing today, regardless of using relative dates vs actual dates. Can you elaborate on your concern here?

**Comment by thezoggy** [comment]
I dont like relative dates.. So it was just shocking to see the data change from one thing to another.. Not constant. I'll be on IRC in a few we can talk about this more

-----Original Message-----
