### ISSUE TITLE
organize calendar key

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#865]
calendar key, move 'unmonitor' to the same row.. so you keep the 2x grid.
also, possibly add one for 'specials'? that you you can have 2x2x2x2

![sonarr139](http://zoggy.net/sonarr139.png)

**Comment by markus101** [comment]
4 columns with 2 rows in each?

**Comment by thezoggy** [comment]
Yes.. If width permits 

-----Original Message-----

**Comment by markus101** [comment]
Will take a look at this for v3.
