### ISSUE TITLE
manual search - handling lots of releases

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#868]
think this was a bug on nzbgeeks part (doesnt happen anymore), but they returned the same result for the whole api result.. so 100 of the same release.. really brought to light how crappy the manual search modal can be when there is a lot of releases. 

![sonarr133](http://zoggy.net/sonarr133.png)

besides making the manual search modal take forever, you had no sensible way to filter/collapse/hide the data.. thus you just had to scroll quite a bit

**Comment by markus101** [comment]
Dupe of https://github.com/Sonarr/Sonarr/issues/375
