### ISSUE TITLE
Error while searching serie episodes Rid

### ISSUE THREAD

**Issue by willem1509** [Sonarr/Sonarr#873]
Hi,

I am having issues lately with my setup of Sonarr in combination with spotweb. (it has worked properly for months). Sonarr searches for an episode and i get this in the logfiles:

An error occurred while processing feed. http://127.0.0.1/spotweb/api?t=tvsearch&cat=5040&extended=1&apikey=<removed>&offset=0&limit=100&rid=38517&season=1&ep=1: Newznab error detected: No such item

I think the wrong error is caused by searching for the RID instead of the name of the serie. It has went well for months but last week it suddenly stopped..

**Comment by Taloth** [comment]
Obviously not our problem, spotweb needs to be adjusted to use the new nn+ standard. (which supports tvdbid= & tvmazeid=).
I mentioned an alternative in this thread, but that will only work for Sonarr, not other apps:

https://forums.sonarr.tv/t/error-while-searching-serie-episodes-rid/7625
