### ISSUE TITLE
4k Quality Definitions

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#876]
4k is coming/already here so we should add the applicable quality settings, possible rejig the default ordering as well, is source or resolution more important?

**Comment by MarkPash** [comment]
Yes, please add WEB-DL 2160p.

**Comment by m1lkman** [comment]
I vote for resolution, 4096 x 2160 vs 3840 X 2160 etc..

**Comment by markus101** [comment]
Is there content that is actually being released as 4k (4096x2160) vs UHD (3840x2160)? I'm only seeing 2160p content and even that is all adult content.

**Comment by MarkPash** [comment]
Yes there is content in UHD, though I haven't seen any in 4096 x 2160.
The content I have seen is WEB sourced (NF), you can probably guess where it is sourced.

**Comment by markus101** [comment]
How is it labeled? (minus the series title), my quick searches are coming up empty.

**Comment by MarkPash** [comment]
Series.Name.S01E01.Episode.Name.2160p.NF.WEBRip.DD5.1.x264-iON.mkv

**Comment by thezoggy** [comment]
![sonarr162](http://zoggy.net/sonarr162.png)

**Comment by whitecollar17** [comment]
![4k](https://cloud.githubusercontent.com/assets/2944704/10993431/fd008818-846e-11e5-835b-66c310810b3d.png)

**Comment by Dahlgren** [comment]
More and more TV series are now appearing in 2160p from either Netflix or Amazon

**Comment by cold12** [comment]
https://torrentfreak.com/pirates-can-now-rip-4k-content-from-netflix-and-amazon-151127/

Would love to see some support for this as it's coming!

**Comment by Dahlgren** [comment]
Yes, it's quite a hassle as it is now since they are mostly identified as webdl 480p or in some cases hdtv 720p. I'd be happy to fix whatever more is needed for my pull request.

**Comment by whitecollar17** [comment]
+1

**Comment by thezoggy** [comment]
could just add ignore word 2160p to prevent them

**Comment by dazedcrazy** [comment]
Has there been any more movement on this?

**Comment by srod** [comment]
I'll be happy to see a 4K quality too !
We now have a lot of content.

**Comment by Dahlgren** [comment]
#923 is merged so it should be part of the next release I hope!

**Comment by srod** [comment]
Great news, thank you !

**Comment by Leafar3456** [comment]
Awesome, looking forward to it.

**Comment by markus101** [comment]
Closing as this was merged to develop already.
