### ISSUE TITLE
APT repo is missing "Origin", preventing automatic updates

### ISSUE THREAD

**Issue by modest** [Sonarr/Sonarr#877]
Hey folks,
Sonarr's APT repository doesn't list an Origin in the **Release** file.

http://apt.sonarr.tv/dists/master/Release :

```
Origin: . master
Label: . master
Codename: master
Date: Tue, 20 Oct 2015 01:38:39 UTC
Architectures: amd64 armhf i386 powerpc ppc64el s390x
Components: main
Description: Generated by aptly
MD5Sum:
 a17cea568213871af924013a007668fc    60138 main/binary-armhf/Packages.bz2
 61bc19f8751337ced983beb62e170506   598112 main/binary-ppc64el/Packages
…
```

This prevents [enabling automatic updates](https://help.ubuntu.com/lts/serverguide/automatic-updates.html) for Sonarr.  To enable automatic updates, the server admin must list the `Origin` of your repo in the config file.  But you don't got no Origin.

It looks like you can just pass an `-origin="Sonarr"` flag to `aptly publish repo foo`
http://www.aptly.info/doc/aptly/publish/repo/

Help lazy, irresponsible sysadmins like myself by adding 6 characters to support blind auto-updates that don't usually break everything.

**Comment by Taloth** [comment]
Should've picked this up much earlier, but I guess we can do it while we reconfigure the repositories for v3.0.

**Comment by markus101** [comment]
Bintray does this automatically, which will be used for v3 unless something changes.
