### ISSUE TITLE
Renamer acting odd, no longer fast

### ISSUE THREAD

**Issue by gcoan** [Sonarr/Sonarr#879]
I have a couple of series that I usually manually add episodes too. I add them to the series/season folder, hit update series button, then the renamer button.  All of this used to happen immediately.

Since the latest update its taking forever.  What seems to happen now is, instead of a simple rename, Sonarr (on my macmini) seems to copy/cache the file on my NAS (file storage) while doing the rename. I see these files that say "partial" until the rename is finished and also a ton of bandwidth between the mini and the NAS.  Neither of these behaviors happened before the update, the files would simply and quickly be renamed.  

I'm not sure if this behavior is happening with auto-downloads because I generally don't watch them process.

**Comment by gcoan** [comment]
I'm not sure if its related but the paths to my Media Storage no longer show up in System.  I swear the mount points used to show up in "Disk Space."  If I unmount the two shares Sonarr will tell me they are missing in the "Health" pane.  Didn't mounts used to be in the Disk Space section?

![mount](https://cloud.githubusercontent.com/assets/1191140/10619433/adb58ea8-7743-11e5-873f-03604ad0ec98.png)

**Comment by Taloth** [comment]
Some features were added to better deal with truncated file transfers (problem with mono+CIFS). And evidently none of the 2000+ users on the dev branch ran into problems in the last 3+ months.
I was expecting someone to run into issues, but 2 days, that's fast ;)

Sonarr will attempt to make a backup via hardlink, but if hardlink isn't available it has to copy, at least for imports. Renaming is a bit of a different story, but that's for later discussion.

You'll have to enable trace level logging and capture renames *and* imports. Trace is important here, coz I need to see the exact steps the mover takes.

I suggest you post the relevant parts of the log on an private expiring pastebin.

**Comment by markus101** [comment]
Changes to this were included in the last release.
