### ISSUE TITLE
Won't start after update. Ubuntu server 

### ISSUE THREAD

**Issue by morriscode** [Sonarr/Sonarr#884]
Last lines in the log file : 

15-10-20 19:22:27.3|Info|InstallUpdateService|Downloading update 2.0.0.3530
15-10-20 19:22:59.3|Info|InstallUpdateService|Verifying update package
15-10-20 19:22:59.5|Info|InstallUpdateService|Update package verified successfully
15-10-20 19:22:59.5|Info|InstallUpdateService|Extracting Update package
15-10-20 19:23:00.1|Info|InstallUpdateService|Update package extracted successfully
15-10-20 19:23:00.1|Info|BackupService|Starting Backup
15-10-20 19:23:01.3|Info|InstallUpdateService|Preparing client
15-10-20 19:23:01.3|Info|InstallUpdateService|Starting update client /tmp/nzbdrone_update/NzbDrone.Update.exe
15-10-20 19:23:01.3|Info|InstallUpdateService|Sonarr will restart shortly.

uname -a : 3.16.0-46-generic #62~14.04.1-Ubuntu SMP Tue Aug 11 16:27:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Not sure why it tried to run a .exe file...
I tried to start it manually
morriscode@tvbox:/tmp/nzbdrone_update$ sudo service nzbdrone start
Starting NzbDrone
morriscode@tvbox:/tmp/nzbdrone_update$ sudo service nzbdrone status
 * nzbdrone is not running

Any idears?

**Comment by markus101** [comment]
Please use the forums for support.

You will need to check the update file to see if the update failed and check the log files to see why its failing to start. A permissions issue could cause the update to fail and be unable to recover.
