### ISSUE TITLE
Profile per Season

### ISSUE THREAD

**Issue by smitetierlist** [Sonarr/Sonarr#887]
I think it's not possible to set a profile for a season of a show yet. I would really love to see this feature tho.

Why? Example: Simpsons

I want to grab new episodes in `any` quality. I want to grab episodes between season [last] and season [hd start] in `hd` quality and episodes before season [hd start] in any quality again.

**Comment by markus101** [comment]
Dupe of: https://github.com/Sonarr/Sonarr/issues/319
