### ISSUE TITLE
[Feature Request] Extend regex per profile

### ISSUE THREAD

**Issue by smitetierlist** [Sonarr/Sonarr#890]
Problem:

The current regex is not recognizing (some) foreign episodes because keywords like `german` are missing.
But there are releases tagged without `german` but with `videomann` which is a release group which only releases german episodes.

So I would like to *whitelist* the word `videomann` to accept releases with this word in their title.

Possible Solution:

Add an advanced field per profile to add whitelist words - or similiar.

**Comment by markus101** [comment]
`videomann` is already treated as German.

https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Parser/Parser.cs#L215

And you can already make a term mandatory in the release name for a specific series via release restrictions and a tag applied to the series and release restriction.
