### ISSUE TITLE
Custom Post Processing Scripts documentation problems

### ISSUE THREAD

**Issue by djurodrljaca** [Sonarr/Sonarr#891]
This page needs to be updated: https://github.com/Sonarr/Sonarr/wiki/Custom-Post-Processing-Scripts

There are a few issues with it:
1) The separator was changed from a dot to an underscore character in one of the last releases.

2) The env. var. names are converted to lowercase when the process is started. This happens because StringDictionary is used and according to its documentation:

The key is handled in a case-insensitive manner; it is translated to lowercase before it is added to the string dictionary.

https://msdn.microsoft.com/en-us/library/system.collections.specialized.stringdictionary.add%28v=vs.110%29.aspx

3) There are some missing env. variables in the page for "On Download/On Upgrade":
- sonarr_episodefile_sourcepath
- sonarr_episodefile_sourcefolder

**Comment by markus101** [comment]
Its a wiki and can be updated by anyone.
