### ISSUE TITLE
Indexers unavailable due to failures

### ISSUE THREAD

**Issue by xetrok** [Sonarr/Sonarr#894]
When connectivity is dropped for an extended period of time, indexers are 'disabled'.
Upon connectivity restoration no searches will run successfully UNLESS you 'test' each indexer manually.
Can we please have a task separate to health check on a shorter time span to check connectivity and recheck indexers.

**Comment by Taloth** [comment]
Dupe https://github.com/Sonarr/Sonarr/issues/751
