### ISSUE TITLE
Torrents with incorrect dictionaries

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#895]
Some torrents don't follow the standard when it comes to dictionary encoding.

Internally monoTorrent has a flag, but it means we have to jump through a few hoops to load the torrent.

https://github.com/Sonarr/Sonarr/blob/develop/src/MonoTorrent/Torrent.cs#L705-L707

Need to dupe that code and call `BEncodedDictionary.Decode(new RawReader(stream, false))` Ugly hacks.

**Comment by markus101** [comment]
I can't recall ever running into a case where this was a problem, should we close this out?

**Comment by Taloth** [comment]
It has definitely happened, that's why this issue was added. But I can't find a relevant reference on the forum.
I'm ok with closing it.
