### ISSUE TITLE
[Calendar] Release date is correct, time is wrong

### ISSUE THREAD

**Issue by smitetierlist** [Sonarr/Sonarr#897]
Not sure if I get it 100% correct.

Series have a profile and a profile have a language. So the calendar shows the transmission of the episode in the selected language?

I know The Walking Dead is always aired on sunday in the US. Air date for germany is always one day later. So the episodes for TWD are correctly placed on monday in my calendar.

I guess the displayed time is the time when the episode is shown in TV. Right?
Then the actual problem is, that the displayed time is not correct. 

Edit:

I realised not all dates are correct tho. American Horror Story for example seems to show the US date.

**Comment by Taloth** [comment]
The series airs at 9pm on sunday EST, translate that to european time (6 hours timezone difference) and you get 3am on monday. So the shown time in Sonarr is correct.

American Horror Story airs at 10pm in America, thats 4am next day in Europe.

So everything looks fine.
