### ISSUE TITLE
Current Linux SSL instructions fail due to obsolete crypto

### ISSUE THREAD

**Issue by pdoconnell** [Sonarr/Sonarr#904]
Following the instructions here (https://github.com/Sonarr/Sonarr/wiki/SSL) generates the following error when opening the url:

Chrome 48:
SSL server probably obsolete.

ERR_SSL_FALLBACK_BEYOND_MINIMUM_VERSION

Microsoft Edge:
![image](https://cloud.githubusercontent.com/assets/1457595/10838941/5a46a356-7e9b-11e5-971f-7116f35450c5.png)

This happens regardless of whether the certificate path is in the trust (certmgr --add -c Trust <CA Cert>)

**Comment by markus101** [comment]
This is a limitation of mono. AFAIK they didn't support intermediate certificates until recently and last I saw they didn't support newer TLS connections on the client side.

**Comment by pdoconnell** [comment]
If that is true, should the documentation even suggest using HTTPS for now? It is either said to be bad, or doesn't even allow loading of the site in Chrome. It creates a negative teaching moment, telling them to click through security errors.

**Comment by markus101** [comment]
I'd expect that most people that go through setting up HTTPS for Sonarr would already understand the security errors, its not part of the basic setup. I don't think we suggest or recommend to setup HTTPS, do we?

**Comment by jdfalk** [comment]
As security best practices most people are trained to just reflexively follow certain rules. If the bar is green then it's safe and secure, if it's red it's scary and unsafe. https://googleonlinesecurity.blogspot.com/2015/10/simplifying-page-security-icon-in-chrome.html if you see Chrome is changing its notifications and the reason given is that so users understand secure vs insecure. Shouldn't you try to set yourself apart and move to SSL by default?

**Comment by markus101** [comment]
If you're only accessing Sonarr on a LAN that you control (not public WIFI) accessing Sonarr is overkill, if someone can intercept that traffic that means they have access to you're network and you're screwed. Accessig it remotely over HTTPS is a good, but it comes at an added cost, in time and cost (assuming you're going for green = secure).

If Sonarr shipped with SSL enabled out of the box there are considerable hurdles to over come:

- Self signed certs
- Acessing a site by a different URL than the cert is signed for

You end up needing infrastructure in place to deal with the certificate signing and generating many certificates for one installation to deal with both problems. Then your web server needs to support SNI to deal with the multiple hostnames. Having that many certificates costs a lot money, money that a free open source project doesn't have or at least we don't.

I don't see this being feasible for us long or short term.

**Comment by mrala** [comment]
With [Let's Encrypt](https://letsencrypt.org/2015/12/03/entering-public-beta.html) recently entering public beta, would it be worth considering a possible solution for this issue?

**Comment by markus101** [comment]
Let's Encrypt solves part of the problem (making it easier to get a signed, trusted certificate), but i t doesn't solve the issues with what IPs/hostnames Sonarr could be listening on and ensuring the certificate can handle them all.

Could we take advantage of Let's Encrypt in Sonarr, probably, but I don't see this being a worthwhile endeavor until mono has better support for new ciphers and even then I think we'd focus on other areas of improvement.
