### ISSUE TITLE
Option for Kodi Metadata to set date added to the episode aired date

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#908]
This would allow Kodi's recently updated section to remain unaltered when Sonarr imports files for a previous season or upgrades an episode (turns recently added into recently aired).

**Comment by thezoggy** [comment]
the user can just do this using advancedsettings... change dateadded

```
    <dateadded>1</dateadded> <!-- 0 results in using the current datetime when adding a video;
                                 1 (default) results in prefering to use the files mtime (if it's valid) and only using the file's ctime if the mtime isn't valid;
                                 2 results in using the newer datetime of the file's mtime and ctime -->
```

http://kodi.wiki/view/Advancedsettings.xml#videolibrary
