### ISSUE TITLE
Which Synology architectures are supported?

### ISSUE THREAD

**Issue by snurbnacnud** [Sonarr/Sonarr#909]
This weekend a friend of mine pointed me to sonarr.tv, and I was pleasantly surprised to read that a synology package is available. However, the package does not show up in the package center on my device. I have a DS-413

Which architectures are supported? I could not find this in the FAQ or install documentation.

Best regards!

**Comment by markus101** [comment]
x86 and ARM are both supported, QorIQ is not supported, which looks like in in the DS-413.

QorIQ is not supported because mono doesn't work correctly on it.

**Comment by piejanssens** [comment]
It is now: https://github.com/SynoCommunity/spksrc/issues/3470#issuecomment-468365359

**Comment by Taloth** [comment]
If you have a qoriq device, let us know. I'm somewhat skeptical since qoriq isn't ppc/ppc64, it's based on a 32bit chip with a bunch of 64-bit instructions missing.
