### ISSUE TITLE
Minimum age sometimes waiting too long

### ISSUE THREAD

**Issue by aelberling** [Sonarr/Sonarr#910]
I've set my minimum age option in the indexers tab to 55 min. some shows will show up in the activity tab and tell me they are waiting till a certain time, but when i do a manual search the NZB has an age of multiple hours. the age varies from 65 min with a wait time of 10 min, to age of 2.2 hours with another 30min wait from discovery.

**Comment by markus101** [comment]
Please open a thread on the forums with debug logs of an RSS Sync with a pending release not being grabbed.
