### ISSUE TITLE
Ability to send Upgrade notifications if Download notifications are disabled

### ISSUE THREAD

**Issue by pironic** [Sonarr/Sonarr#912]
Minor cosmetic bug:
When adding a webhook under connect menu, the "on download" toggle button toggles the view of the subsequent buttons erroneously.

![image](https://cloud.githubusercontent.com/assets/541154/10923462/4096e8b6-823e-11e5-9813-1c81c1ac7775.png)

![image](https://cloud.githubusercontent.com/assets/541154/10923488/7685b0ec-823e-11e5-8cc6-8297f8872b0a.png)

**Comment by markus101** [comment]
This is expected, it doesn't toggle them on if they were previously off, it just shows them and their default value is enabled.

**Comment by pironic** [comment]
If that's the case, how do you have the webhook alert for only upgrade or rename? The issue is that they remove the option for those two when the notify for download is disabled.

**Comment by markus101** [comment]
You can't. I could see us separating On Rename from that toggle, but On Upgrade is closely related to On Download so I don't see them being separated.

Why do you want those to trigger, but not the On Download?

**Comment by pironic** [comment]
I do like the ability to know when an upgrade happened, and in this case I use it with my pebble watch to alert me, but I use a different notifier method for download. Being able to break out the method for each type of alert is ideal, for me. 

It's not that it's a must, but I do have this set up in my sabnzbd this way, and it would be nice to be consistent.

**Comment by pironic** [comment]
I only just realized this is not an Upgrade of Sonarr, but an upgrade of the episode itself. 

The ability to send upgrade notices would be nice, but this is super confusing... i'll close this one.
