### ISSUE TITLE
Synology Indexer no longer syncs with Video Station

### ISSUE THREAD

**Issue by NMe84** [Sonarr/Sonarr#916]
Some time after September 15th the previously working connection with synoindex seems to have broken. There was a minor DSM update that week but so far I can't find anything that seems related in any change logs. I will spend some time this weekend trying to reproduce this issue on the command line and keep this ticket up to date with any info I find.

**Comment by royduin** [comment]
Any updates on this? I'm having the same issue

**Comment by Taloth** [comment]
No, I don't have access to a diskstation, but I think @margaale might be interested in investigating.

Iirc there's another issue https://github.com/Sonarr/Sonarr/issues/577 about synoindex too.

**Comment by margaale** [comment]
Hey, sure, count me in. I'm gonna start inspecting the code and if i need help i'll get back here. Any data is appreciated...

**Comment by margaale** [comment]
First question, why is the synology indexer under Notifications namespace? :-P (Pretty basic question, just warming up)

**Comment by markus101** [comment]
Because it's a connection (as it's named in the UI), the namespaces we chosen before the UI was done and if we're getting technical, Sonarr is notifying Synology Indexer so it will update.

**Comment by Taloth** [comment]
Background info: we invoke the cmdline synoindex utility to notify it of added/removed/renamed files.
It worked for video station, but for dlna it didn't work coz it didn't automatically add directories.
Then alter, with a DSM update it appeared to have broken even further.

So basically, the entire logic of synoindex needs to be re-evaluated and tested, preferably while fixing the directory issue as well (see issue https://github.com/Sonarr/Sonarr/issues/577 and the forum link for more info).

If synoindex is obsolete, and there's a syno api that works better, then I'm all for it.

**Comment by margaale** [comment]
Actually there is, but is not documented at all

**Comment by fazuw** [comment]
Has there been any progress on this issue. Would like to know since i am having the same issue (My files get imported successfully but don't show up in the DSVideo app and dlna).

**Comment by arette** [comment]
I'm actually ok with it just working on Video Station and supported clients as I only use when I'm away from home.  I'm investigating an issue where notifications quit working in Radarr but are still working fine in Sonarr (& Lidarr now too for that matter).  I use kodi around the house so I just maintain both databases and to hell with sub-par dlna clients

**Comment by arette** [comment]
@NMe84 are you running Sonarr in a docker container on your Synology?  I only ask because that's how I'm running it and everything appears to be working fine on DSM 6.1.3-15152 Update 5 (released 9/21/2017).  Of course, I also have to use a package that allows the docker containers to reach the synology indexer in /usr/syno/bin/synoindex (https://github.com/racklin/simple-synoindex-server).

**Comment by NMe84** [comment]
@arette: at the time I posted this, Synology didn't have a Docker package yet. I'm just running Mono and Sonarr natively. I have no clue of the issue is still there, because I don't actually use synoindex, I just noticed and reported the issue. 😃

**Comment by Michi491** [comment]
Usig sonarr in docker here

**Comment by bakerboy448** [comment]
This bug/issue seems stale.  Please check and see if it is still an issue on the recent v3 builds.  If it is an issue please open a new GHI with logs and full detail.

Docker uses appears fine.
