### ISSUE TITLE
Profiles: Size per playtime

### ISSUE THREAD

**Issue by chmuibk** [Sonarr/Sonarr#920]
Related to #613 I suggest making the size limits not according to the file of the episode, as this means that a 20min show and a 50min show end up with the same limits, but choose the size limits according to e.g. $ MB per 10min playtime.

Is this something feasible and worth implementing?

**Comment by markus101** [comment]
Size limits are are based on the number of episodes AND the run time (as shown in the UI with 30/60 minute examples).
