### ISSUE TITLE
First error message encountered on failed Kodi connection is invalid version

### ISSUE THREAD

**Issue by Gremlyn** [Sonarr/Sonarr#927]
I was attempting to connect Sonarr and Kodi and the test kept failing. After checking the logs I saw the error message was:

    Unable to send test message: Version received from XBMC is invalid, please correct your settings.: Version received from XBMC is invalid, please correct your settings.

A little Googling turned up that the password might be a problem, and having seen this before when symbols are contained in the password, I changed the password to be symboless and it worked.

Really there are two issues, one being the inability to use passwords with symbols, and the other being that error output isn't correct for the error condition.

I'm not a C# programmer, otherwise I'd make an effort to fix this myself, but I would propose that before checking for the version number that a check be done to see if valid JSON was retrieved from the attempt in the first place.
https://github.com/Sonarr/Sonarr/blob/master/src/NzbDrone.Core/Notifications/Xbmc/XbmcService.cs

**Comment by markus101** [comment]
Looking at the code that must be over 4 years old or pretty close, definitely from v1, cleaned it up a bit, will have a fix in develop shortly.
