### ISSUE TITLE
Don't send notifications for Manual Import

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#933]
The user probably doesn't need to get a notification via their configured notification channels if they manually imported an episode, so we could make it optional for manual imports, which would require us to know that when importing the episode.

**Comment by stevenolsen** [comment]
Thanks for considering this option. I really appreciate it.

**Comment by holyoaked** [comment]
While on the subject of notifications -

Right now, when a season pack is added to Sonarr it will send a notification for each episode within the season pack. It's very irritating suddenly getting (for example) 24 notifications at once. Can't Sonarr tell when a season pack is downloaded, and thus condense the 24 notifications into one?

**Comment by markus101** [comment]
@holyoaked that's a completely separate issue: https://github.com/Sonarr/Sonarr/issues/363

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted
