### ISSUE TITLE
Can we suggest a new indexer? Filelist.ro

### ISSUE THREAD

**Issue by aaomidi** [Sonarr/Sonarr#936]
Basically the title.

I'd be willing to provide the dev an invite to filelist.ro if need be.

**Comment by markus101** [comment]
Is there an API or just RSS?

**Comment by aaomidi** [comment]
There is an RSS, but it does not have a pubDate.

**Comment by aaomidi** [comment]
I did find this: https://github.com/outkastm/Filelist.ro

**Comment by markus101** [comment]
That indicates that they are using screen scraping to find releases, which we will not do in Sonarr, but it is supported in [Jackett] (https://github.com/Jackett/Jackett).
