### ISSUE TITLE
Remotely grab completed files from seedbox

### ISSUE THREAD

**Issue by jnyl42** [Sonarr/Sonarr#937]
I am trying to add a Transmission instance on a remote seedbox (whatbox).  It uploads great but Sonarr can't retrieve it after completion.  People are using mounting software like sshfs but those are platform-dependent and unreliable.  Can you add functionality to auto-download the completed file via ssh/ftp/sftp?  Kind of like Remote Path Mappings, but instead of translating Remote to Local links, it would translate Remote to FTP, for example, and then Sonarr could request those without extra filesystem manipulation on the host machine.  It seems like this would work for remote nzbs also.

Thanks for all your work, Sonarr is amazing.

**Comment by jnyl42** [comment]
Here's what I'd like to do, ideally:

![ideally](https://cloud.githubusercontent.com/assets/9988173/11161176/ba518758-8a2a-11e5-9d90-073234d9cb6e.png)

**Comment by Taloth** [comment]
This is pretty much covered by issue https://github.com/Sonarr/Sonarr/issues/282. FTP isn't specifically mentioned, but you can see how it would be a similar implementation.

**Comment by dougmorin** [comment]
I'm not sure exactly that #282 covers what what @jnyl42 was asking.  I'm running into the same issue right now, and there are only bandaids.
