### ISSUE TITLE
Sonarr can't fine new TV

### ISSUE THREAD

**Issue by Sparrow2123** [Sonarr/Sonarr#939]
Hey,

When I try to add a new TV show into Sonarr, it just's says can't find what you're looking for, this is on lots of TV shows I try, please let me know if you need any logs or info etc, thanks!
I'm running windows 7, recently upgraded to Win 10 and then back again, and a fresh install of Sonarr to try and solve the issue.

Thanks! :)

**Comment by Pupwiz** [comment]
I am having the same problem today windows 10 64 bit and the latest stable version of sonarr

**Comment by markus101** [comment]
Please use the forums for support:

https://forums.sonarr.tv/t/cant-add-a-new-series/8066
