### ISSUE TITLE
Indexer Resquest - ExtraTorrent

### ISSUE THREAD

**Issue by schmas** [Sonarr/Sonarr#945]
Hi,

Just requesting a new torrent indexer:
http://extratorrent.cc/

Thanks

**Comment by markus101** [comment]
Do they have an API? I see API docs for uploading, but if they don't have an API we can use for searching it won't be added.

**Comment by duramato** [comment]
@markus101 They do have RSS feeds that work also for searching ,maybe you could use them ?

**Comment by markus101** [comment]
So they do, that might work, we'll need to discuss if we want to add it.

Example feed:
http://emtorrent.com/rss.xml?type=search&cid=8&search=30+rock+s01e01

**Comment by uzegonemad** [comment]
+1. I've used it almost daily to fill the void on older missing episodes that my existing indexers can't pick up.

That said, it's also not really a hassle for me to download & upload a torrent file to transmission in those cases. My existing indexers are picking up new episodes without issue.

**Comment by JigSawFr** [comment]
If private, request it to Jackett :)

**Comment by uzegonemad** [comment]
@JigSawFr It's public and feeds are available.

**Comment by brimur** [comment]
Im new to Sonarr but before I moved to it I used SB. Maybe this will help, maybe it wont but this is the extratorrent searcher from SB... https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/providers/extratorrent.py

**Comment by duramato** [comment]
@brimur maybe it was me who wrote that lol , that why i suggested the use of the rss feed...

**Comment by moofa** [comment]
+1 I'd like to raise this proposal again. Please give it serious consideration. It is ettv's tracker so pretty much every show release is there, and it's faster/more consistent than KAT.

**Comment by onkelandy** [comment]
Would also love to see that indexer as it has a lot to offer. Thanks!

**Comment by Taloth** [comment]
Guys, I mailed the extratorrents admins, they fixed the rss content-type, so you should now be able to use the Torrent RSS indexer. But only for new releases on the rss feed, not backlog seaching.

The search capability on extratorrents is only a wildcard text search. In that sense it isn't in an complete indexer. And is harder to implement reliably in Sonarr. (One would have to query the site for the multiple S01E01, daily, 1x01 etc formats that are out there.)

In my email I explained this problem, they made a note of it, but the extratorrents devs are of course just as busy as we are, so I'm not expecting a solution on the short term.

I'll obviously leave this github issue open, but I won't implement the api for now. At least you got the rss feed now.

**Comment by uzegonemad** [comment]
@Taloth thanks so much!

**Comment by moofa** [comment]
Thanks @markus101 and @Taloth for the updates. A little off-topic, but a public tracker just as reliable as ExtraTorrent is EZTV at eztv.ag ; so I was wondering if implementing EZTV's tracker is a better alternative at this point? Cheers again!

**Comment by EionRobb** [comment]
Don't suppose there's any updates from the extratorrent devs about the episode search api?

**Comment by jimaek** [comment]
With Kickass down I think extratorrent is now more important.

**Comment by grillba** [comment]
Use the Torrent RSS feed and add this as the Full RSS Feel URL

http://extratorrent.cc/rss.xml?cid=20&type=last

**Comment by Mike43110** [comment]
https://zooqle.com/help/api.html

Will this be of any use?

**Comment by markus101** [comment]
>https://zooqle.com/help/api.html

> Will this be of any use?

No, their API is useless for Sonarr. Also this is about ExtraTorrent. See https://github.com/Sonarr/Sonarr/issues/1392 for Zooqle...
