### ISSUE TITLE
Restrict Repack upgrades to the same release group

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#946]
If a repack comes out Sonarr should only upgrade to it if the original file is from the same release group, a proper should apply to any release group, but what can happen with internal releases is a scene release comes out (no issues) and later a repack for an internal release comes out and Sonarr happily upgrades to it.

Proper: Fix for another release groups mistake
Repack: Fix for same release groups mistake

**Comment by aptalca** [comment]
Just had this issue with x-files 

Already had the regular/official scene release, a day later a repack for an internal came out, and sonarr replaced the original with the internal repack.

Along the same lines, perhaps sonarr should pay attention to whether proper releases match the original in terms of whether they are internal or not.

For instance, let's say there is a regular scene release and an internal. Sonarr downloads the internal. Later, a proper may come out for the original release by a different group. In the current state, Sonarr would replace the existing internal (which is probably just fine) with the proper. Perhaps Sonarr should not replace the internal with a non-internal proper.

**Comment by scootied** [comment]
Just had the same problem with the X-Files again (ref aptalca above). Code for the same release name + proper should fix the issue.

**Comment by NMe84** [comment]
A proper is always something that another group releases to fix another group's release. Repacks are fixes a group makes for their own releases. Same-group logic would need to only apply to repacks, not propers. The whole point of propers is that they are released by another group.

**Comment by Taloth** [comment]
@markus101 Do we really want to spend effort on this? Especially since p2p won't give a rats ass about repack/proper, nor does scene care about p2p.
It downloaded another release due to a conflict with an iNTERNAL, so what? If that's such a big issue, disable upgrading to propers.
Otherwise you're gonna have a discussion about what's better, official release or iNTERNAL.

**Comment by markus101** [comment]
I think its worth it for a repack, same as we do for anime (only get v2 if v1 was from the same release group), for a proper, I don't think we change anything.

Of course the complication comes with proper vs repack, since we don't differentiate in code between the two.

**Comment by Toxic-Waste-** [comment]
Saw this happening today with DareDevil, first sonarr downloaded "Marvels.Daredevil.S02E13.720p.WEBRip.x264-SKGTV". Later this night, he got a proper "Marvels.Daredevil.S02E13.PROPER.720p.WEBRip.x264-FREAK-Obfuscated" as new episode. As far as I can tell, there is nothing wrong with the first download that he got. (actually the second release is a lot worse imo, but that's a scene issue and not sonarr)

is this the intended use of the proper download of sonarr? it seems the releasegroups are messing around a bit with them sometimes..
