### ISSUE TITLE
Better support for calendar view left open more than a day

### ISSUE THREAD

**Issue by pjnagel** [Sonarr/Sonarr#947]
On the calendar view, the "today" button is disabled unless one moves the calendar to a different month/week/day than the one currently displayed.

This is a problem when the calendar view is left open overnight, because by the next day the calendar is displaying yesterday's information, and there is no easy way to refresh it. One can reload the browser tab, but that refreshes much more sluggishly than just clicking today does.

The ideal would be javascript that automatically refreshes the view at midnight.

But in the absence of such niceties, the simplest solution would be just to never disable the "today" button, because even though the button was not relevant when the page was first rendered, it may become relevant in a while when the midnight comes.

**Comment by markus101** [comment]
Given the nature of the calendar I don't think auto refreshing makes sense, while you may be viewing yesterday when it ticks midnight, you may not want to be abruptly moved to today. We will be making the today button always active in v3.

Closing this as work has begun for this change already.
