### ISSUE TITLE
Study the possibilities to use Core CLR

### ISSUE THREAD

**Issue by GuillaumeLebeau** [Sonarr/Sonarr#948]
.NET Core and ASP.NET 5 RC have been announced yesterday, the 18th of november, and it would be great if Sonarr could migrate to this new platform which run under Windows, Linux and OSX. This release is "Go Live", meaning apps can be deployed into production and Microsoft Support can give help if needed.

**Comment by markus101** [comment]
We were planning to upgrade to .net 4.5 for v3, but will consider other options, but Sonarr doesn't use ASP.Net. We are interested in .net Core and what it has to offer, so its something we'll look at for v3.

**Comment by GuillaumeLebeau** [comment]
You're right I make a mistake in the title. I would like to point essentially the release of the RC of .NET Core. It's a great news that you are interested by this new Framework and I wish you good luck for all the work you have planned to do for v3 and big thanks for all you have already done.

**Comment by tidusjar** [comment]
Please note that .Net 4.5 is no longer supported by MS.
http://blogs.msdn.com/b/dotnet/archive/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1.aspx

So it would be better to upgrade to .NET 4.5.2

**Comment by joshuata** [comment]
I have been looking into this and as far as I can tell all dependencies are now available on .NET Standard/Core. 

Is there anything I can do to kickstart work on this issue?

**Comment by tidusjar** [comment]
NancyFx can run on .Net Core now, but there are a lot of breaking changes (it would be a simple upgrade nuget package).

It's quite a lot of work, especially around any areas using reflection as the API's have moved around quite a bit. 
I'd suggest to wait until .Net Standard 2.0 has a stable release as it will be more performant and 10x more API's available (you guys probably already know this).

https://github.com/dotnet/core/blob/master/roadmap.md

**Comment by jbpaux** [comment]
.Net Core 2.0/.Net Standard 2.0 is now available in general availability :)

**Comment by markus101** [comment]
As of right now signalR is not supported in aspnetcore 2.0, it will be supported in 2.1 though.

I've played with Kestrel (aspnetcore self host web server) and have it working using .net 4.6.1 + Nancy (API), but we'd need to look at everything NzbDrone.Mono provides to see if that will work with .net core 2.0.

**Comment by jbpaux** [comment]
it is available now ! https://blogs.msdn.microsoft.com/webdev/2017/09/14/announcing-signalr-for-asp-net-core-2-0/

**Comment by LordVeovis** [comment]
@jbpaux "available" in alpha yes on their dev nuget repository. Not feature complete, API interface not stabilized yes, and some bugs.

**Comment by roly445** [comment]
I don't know if this helps you at all? [](https://icanhasdot.net/result?github=Sonarr~2FSonarr)

**Comment by Mantene** [comment]
Jackett just made the switch to dotnet core and it is wonderful. No more Mono with Sonarr would be a dream come true.

**Comment by Taloth** [comment]
Gentlemen, please do not post on this subject again. Being suggested, over and over again, to use dotnet core isn't particularly constructive.
We'll decide if and when we want to work on supporting dotnet core as platform since we're uniquely qualified to assess the effort and consequences of such an endeavor for Sonarr.

**Comment by markus101** [comment]
dotnet will be used in v4, mono will be no more.
