### ISSUE TITLE
Renaming is slow

### ISSUE THREAD

**Issue by msh100** [Sonarr/Sonarr#950]
on Linux, renaming is noticeably slow. 

On top of an encrypted filesystem, you can see that it takes time to rename a file and I suspect this is because the file is read (unencrypted) and then written again (encrypted again) in a different location rather than just using the system rename functions.

**Comment by markus101** [comment]
Please use the forums for support.

We'll need to know which OS, which Filesystem and which Sonarr and mono versions you're using. Also make sure you're running the latest version of Sonarr and test again as there was a fix in the latest release for slow renaming on some setups.
