### ISSUE TITLE
Add current status to monitored icon

### ISSUE THREAD

**Issue by uzegonemad** [Sonarr/Sonarr#951]
I'm an idiot and get confused by the monitored/unmonitored icons. I think it would be beneficial to add the current status to the icon tooltip. Like...

Old:
<img width="297" alt="screen shot 2015-11-20 at 5 16 32 pm" src="https://cloud.githubusercontent.com/assets/430255/11314373/a118fcd2-8faa-11e5-8cb8-4552c97396b1.png">

New:
<img width="293" alt="screen shot 2015-11-20 at 5 16 50 pm" src="https://cloud.githubusercontent.com/assets/430255/11314376/a7247ba6-8faa-11e5-839d-3eaf2ebce2e1.png">

**Comment by markus101** [comment]
I've been thinking about this as well, mainly because of the differences in text colour.

**Comment by Toxic-Waste-** [comment]
+1, I'm confused every time honestly

**Comment by lcmullins** [comment]
+1, Same here.  Thank you for your consideration.

**Comment by Fastjur** [comment]
+1, Was actually about to open a feature request for this until I saw it was already on github. It would be nice to add this for not only series, but also seasons and episodes. It still confuses me!

**Comment by dkisselev** [comment]
+1

I think the tooltip text should just be replaced with what will happen when the button is clicked (instead of explaining that it will toggle),

ie,

> Monitor this season

and

> Stop monitoring this season

**Comment by tomsommer** [comment]
+1 - or change the icon, it's very non-obvious what it means

**Comment by RustyF** [comment]
+1 how about having a slightly different icon, i.e. with a little badge to indicate its monitored.

**Comment by markus101** [comment]
This is addressed in the v3 UI. No ETA on it's release at this time.

**Comment by sebastienbarre** [comment]
For sure, still confusing to this day.

**Comment by bakerboy448** [comment]
@sebastienbarre how is it confusing?

There is absolutely nothing I can see is confusing about this.

![image](https://user-images.githubusercontent.com/55419169/94511045-df425a80-01dd-11eb-9433-065bad8343db.png)
![image](https://user-images.githubusercontent.com/55419169/94511065-eb2e1c80-01dd-11eb-8db3-5e9bf1b34bd6.png)

**Comment by sebastienbarre** [comment]
Well look at that, time flies, I was still on 2.0 :)

**Comment by markus101** [comment]
> which indicates to me that 2.x is being updated

Only critical fixes to keep things working.

> but that fix was not back-ported.

Virtually nothing will be back ported, it's a completely different UI.

> This is addressed in the v3 UI. No ETA on it's release at this time.

This is why the issue was closed, if it was being backported it would be as indicated as such.

**Comment by bakerboy448** [comment]
For what it’s worth v3 is and has been in a very stable beta.

Regardless v2 is critical break/fix only
