### ISSUE TITLE
Hitting esc in modal with path dropdown open

### ISSUE THREAD

**Issue by uzegonemad** [Sonarr/Sonarr#952]
This is more of a request/discussion than a bug report.

When I open up the remote path mappings modal and start typing a path in "Local Path," a path picker pops up. Out of habit, I keep pressing the esc key to close it, but it closes the BS modal instead, which is default functionality.

Do you think it would make sense to close the path picker when esc is hit, and then if esc is hit again, to close the modal?

**Comment by markus101** [comment]
This will be fixed in v3.
