### ISSUE TITLE
BindAddress localhost/127.0.0.1 not working

### ISSUE THREAD

**Issue by lifeofguenter** [Sonarr/Sonarr#957]
In the `config.xml` I can not set localhost or 127.0.0.1 as BindAddress.

Localhost will actually resolve to 0.0.0.0 and 127.0.0.1 will give me the following error (even though 100% nothing is running on that IP:Port!):

> Address already in use. This can happen if another instance of Sonarr is already running another application is using the same port (default: 8989) or the user has insufficient permissions

**Comment by markus101** [comment]
Windows won't let Sonarr bind to 127.0.0.1 and the default binding is to localhost, so Sonarr automatically will bind to 0.0.0.0.

The bind address doesn't work the way it was intended to unfortunately, it doesn't bind to a specific IP, but instead listens for those hostnames, its something we're looking into.

**Comment by Ardakilic** [comment]
I'm having this exact same issue on Debian Jessie. Any solutions found ? I'm reverse proxying with nginx, so I am planning to bind only to localhost.

**Comment by SebHeuze** [comment]
Hi, 
Same here both 127.0.0.1 or localhost I have : 
[Info] OwinHostController:   http://127.0.0.1:8990/
[Info] OwinHostController:   http://localhost:8990/
and Address already in use
