### ISSUE TITLE
[Warn] StaticResourceModule: Couldn't find handler for /username/sonarr/Content/Images/background/logo.png

### ISSUE THREAD

**Issue by backslash05** [Sonarr/Sonarr#961]
I have installed mono and Sonarr but when I try to open via web browser i get a lot of these errors.

[Warn] StaticResourceModule: Couldn't find handler for /username/sonarr/Content/Images/background/logo.png

I am trying to run on my seedbox.

**Comment by backslash05** [comment]
[Info] HousekeepingService: Running housecleaning tasks
[Info] SceneMappingService: Updating Scene mappings
[Info] Database: Vacuuming Log database
[Info] Database: Log database compressed
[Info] Database: Vacuuming Main database
[Info] Database: Main database compressed
[Warn] StaticResourceModule: Couldn't find handler for /username/sonarr/Content/Images/background/logo.png
[Warn] StaticResourceModule: Couldn't find handler for /username/sonarr/Content/fonts/opensans-regular.woff
[Warn] StaticResourceModule: Couldn't find handler for /username/sonarr/Content/fonts/opensans-light.woff
[Warn] StaticResourceModule: Couldn't find handler for /username/sonarr/Content/fonts/opensans-regular.ttf
[Warn] StaticResourceModule: Couldn't find handler for /username/sonarr/Content/fonts/opensans-light.ttf
[Info] RssSyncService: Starting RSS Sync
[Warn] FetchAndParseRssService: No available indexers. check your configuration.
[Info] DownloadDecisionMaker: No results found
[Info] RssSyncService: RSS Sync Completed. Reports found: 0, Reports grabbed: 0

**Comment by kayone** [comment]
It seems like the ui files are missing from your file system. can you check if those files actually exist in the file system.

**Comment by markus101** [comment]
If you're still having issues, please open a thread on the forums.
