### ISSUE TITLE
Sonarr breaks Synology DSM hibernation

### ISSUE THREAD

**Issue by meoz** [Sonarr/Sonarr#963]
Hi,

I've installed Sonarr on my DSM 6.0 beta, it's working great. Only thing is that some Sonarr processes are preventing the Synology from going into hibernation when there is no download activity. Is there some setting to uncheck or some other workaround to stop Sonarr from keeping the Synology disks awake ?

**Comment by markus101** [comment]
Sonarr doesn't do anything to explicitly keep them awake, it will write logs as required and will rescan the disk every 12 hours when it refreshes the series. The only other thing would be Drone Factory, which would be every minute by default, but shouldn't be used.

**Comment by meoz** [comment]
I'm not sure why Sonarr is keeping the disks spinning all the time. The disks go into hibernation as they shoud when I stop running Sonarr. Looking on the System-> Tasks page one could assume that the frequent intervals checks of one1 minute or only a few hours could be the causing disk activity and thus preventing hibernation. Is there a way to change the interval for 'Check for Finished Download' ?

| Name                        | Interval   | Last Execution    | Next Execution   |
|-----------------------------|------------|-------------------|------------------|
| Application Update          | 6 hours    | a few seconds ago | in 6 hours       |
| Backup                      | 7 days     | 6 days ago        | in a day         |
| Check For Finished Download | 1 minute   | a few seconds ago | in a few seconds |
| Check Health                | 6 hours    | a few seconds ago | in 6 hours       |
| Downloaded Episodes Scan    | disabled   | a day ago         | -                |
| Housekeeping                | 1 day      | a few seconds ago | in a day         |
| Messaging Cleanup           | 5 minutes  | a few seconds ago | in 5 minutes     |
| Refresh Series              | 12 hours   | a few seconds ago | in 12 hours      |
| Rss Sync                    | 15 minutes | a few seconds ago | in 15 minutes    |
| Update Scene Mapping        | 3 hours    | a few seconds ago | in 3 hours       |

**Comment by markus101** [comment]
No, those are integral to the operation of Sonarr, if you could put Sonarr's App Data Folder in a different location thats not on one of the disks the logs would be written there and it should hibernate, that would be a job for the plugin to tell Sonarr though.

**Comment by jamesfairhurst** [comment]
This is an issue for me too, would be really useful to have a setting for the log file location so that it doesn't affect hibernation. Sickbeard has something similar and with the NAS you can plug in a USB memory stick and write to log files there whilst still keeping hibernation.

Hopefully something that can be added in the future if it's a relatively simple change?

**Comment by JigSawFr** [comment]
Hum, mount Sonarr with Docker and map logs files/directory to USB :)

**Comment by meoz** [comment]
Should be not too big of a change to make the intervals customizable. I don't see the need to have Sonarr every minute check my disks for finished downloads. Not everybody is downloading 24 hours a day at a constant rate.

**Comment by markus101** [comment]
Not sure if the Synology Package can have an option on where to host Sonarr's AppData folder (its not maintained by our team), which can be controlled with the `-data=/path` parameter, since that controls where Sonarr keeps its settings as well as logs (both file and database), but that is the solution that would be best here.
