### ISSUE TITLE
Prevent Grabbing if Episode Hasn't aired

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#969]
Fakes are a problem on public sites that we support, if the episode hasn't aired yet preventing the download would prevent the fake.

If we add it it should be opt-in as there are many legitimate releases before the air date and this also adds yet another thing that will prevent an episode from being grabbed (support hell).

**Comment by kayone** [comment]
how about this case, today is 20th, episode aired on 15th and we find a release today (20th) from 10th? would we still not download it?

**Comment by markus101** [comment]
Correct, it would not be downloaded because it was released before the air date.

**Comment by thezoggy** [comment]
maybe offer the toggle per indexer? that way you can turn it on for those crappy public torrent sites..

**Comment by bjeanes** [comment]
Can I propose at least doing this for shows marked "daily" (which I also use for some weekly shows like Last Week Tonight). Those shows have enough regularity and are recorded mostly live that a pre-release is always going to be a fake. The occasional fake Elementary or similar doesn't bother me but with Last Week Tonight I keep getting episode for the *next* week but it's really some random episode from Season 1, for example.

**Comment by bjeanes** [comment]
If you do have an option to prevent pre-release fetching, it could be per-show and opt-in. That way certain problem shows can be excluded.

**Comment by magne4000** [comment]
Any news on this? Lately I had many fakes downloaded because this feature doesn't exists

**Comment by Devian50** [comment]
I would like an update as well. I personally have had Sonarr somehow deciding a file it downloaded while looking for a special episode aired Friday was actually a main season episode that airs in over a month, which then causes it to download the other two special episodes again as main season episodes. The show's main season hasn't even started airing yet and won't for another month.

**Comment by killerz298** [comment]
I have this issue with the new Ducktales. Sonarr keeps grabbing a scene release which is 1 episode number off for some reason and it imports it as the next episode which has not aired. I have to constantly fix this.

**Comment by dejected1** [comment]
I too have this issue with the new ducktales. Came here to post for this reason actually.  Enabling this per show or per indexer seems ideal. i wouldn't mind a global option either.

**Comment by aeonsablaze** [comment]
I would also quite like this feature. Particularly on a per show basis.

**Comment by kelemvor33** [comment]
Came here about this specific issue.  Got a download for an episode that Sonarr shows doesn't air for another 12 days.  Since it knows it hasn't aired yet, it should be smart enough to know that the files isn't legit and skip it.

**Comment by thezoggy** [comment]
shows get ripped early all the time. most of us enjoy getting stuff early..  @kelemvor33 was your issue 'spam' on a public torrent site?

**Comment by kanine** [comment]
Looks like a workaround can be put in place with the Queue API. I'll tag shows where this happens with something like 'preventEarly' but I think it would be a useful feature to incorporate, especially if a release is more than say 14 days earlier than an Air Date.

**Comment by tlc** [comment]
I am using torrents not usenet.  I'm getting "future" episodes of a nightly news show.  It is not because of fakes it is because of bad episode matching.  For example,

these were downloaded as 9/10/2020 episodes
[redacted] - 2020-09-03 - September 3, 2020 WEBDL-1080p.mkv 
[redacted].2020.09.03.1080p.MNBC.WEBRip.AAC2.0.H264-doosh[rarbg]

similar mistakes were downloaded as 9/11/2020 episodes
[redacted] - 2020-09-04 - September 4, 2020 WEBDL-1080p.mkv
[redacted].2020.09.04.1080p.MNBC.WEBRip.AAC2.0.H264-doosh[rarbg]

**Comment by markus101** [comment]
Unrelated to this issue then, open a thread on the forums or subreddit for support.

**Comment by bakerboy448** [comment]
Using less crappy indexers that don't have fakes.

episodes air "before" release all the time and valid releases are pushed out (NBC and CBS series air in Canada earlier than the US frequently)

**Comment by markus101** [comment]
There has been a lot of demand for this as of late, especially with fake/malicious releases. Our plan is to support this via Release Profiles, which will have two settings.

First Setting: A way to turn it on/off, naming TBD (something like Do Not Download Before Air Date), but it also needs to support skipping that release profile, so it'd be a drop down with 3 options:

- Skip/Ignore: Skip this profile while making this decision (allows for finer tuning), this will be the default setting.
- Enforced: This setting is enable and enforced
- Not Enforced: This setting is not enabled

Second setting: A way to configure a grace period, in hours, so for example you could create a profile that allows downloads up to 24h before the air date for those series that air earlier than the date on TheTVDB in some markets.

How these settings are applied:

1. Find all release profiles with matching tags  and enforcing air date
2. Apply lowest grace period to release
3. If nothing applies find any profile without tags and enforcing air date
4. Apply lowest grace period to release
5. If nothing applies treat like it does now

With two settings and a way to ignore/skip a profile it will be possible to apply a profile globally, then have a separate profile apply to a single series or a group of series without having to tag every series with a tag.

Our goal will be to have this available in v5.

**Comment by markus101** [comment]
With the addition of `Excluded Tags` it's not necessary to have an option to skip release profiles, nor is it necessary to have a preference between Tagged and Untagged release profiles.

Two settings:
1. Checkbox to enable/disable, default will be disabled
2. Grace period in days, negative value to allow grabbing before air date, positive to prevent grabbing until days after air date and 0 to use the air date as-is.

How it works:

1. Get all release profiles for tags/indexers
2. Sort release profiles (`Do not Grab Before Air Date` enabled then highest grace period)
3. Use first release profile to limit grabs
