### ISSUE TITLE
settings>indexers>restrictions: only bottom line works

### ISSUE THREAD

**Issue by gac123** [Sonarr/Sonarr#970]
I had 2 lines:
top line: 4 items 'must contain', 0 items 'must not contain'
bottom line: 6 items 'must contain', 1 item 'must not contain'

when I was looking at the available releases, those flagged as ignore, the popup listed only those in the bottom line of the 'must contain' list, 6 items
-> the other 4 'must contain' items of the first were not listed, so it seems only the bottom line works
but I don't know if the same happens for the 'must not contain'

**Comment by markus101** [comment]
This is expected each restriction must contain (at least one of the matching words to be accepted, for must not contain the name must not contain any of the terms. In you case with two different restrictions applied at least one term matched in the first restriction and none in the second restriction so only the second restriction was listed.

**Comment by gac123** [comment]
Not really as expected, if you have the option to [add] multiple restrictions, then I would expect those restrictions are [add]ed up:

restriction 1: must: A, B, C not: D, E, F
restriction 2: must: G, H, I not: J, K, L

so all releases must at least contain A, B, C, G, H, I and of those must not contain D, E, F, J, K, L

**Comment by gac123** [comment]
Just to be clear; to continue the example and what I came across:

I had a list of releases and of those matched restriction 1, it was an 'A' release and didn't contain D, E, F, J, K, L but the app didn't find any matches.

It was only when I combined restriction 1 and 2 that it did work.

So then there is no point in having multiple restrictions if only the (as it seems now) last in that list (restriction 2) is applied.

**Comment by markus101** [comment]
Within a restriction it Must Contain A or B or C and Not D or E or F and Must Contain G or H or I and Not J or K or L. The description for these fields indicates that the release must contain or not contain at least one of the terms to be accepted or rejected.

If you want the release to require A, B and C then you need to create 3 different restrictions, this was the easiest way to achieve a system where you can mix OR and AND rules without too much complication.

**Comment by gac123** [comment]
ok, if I understand correctly, each restriction (including 'must contain' ORs and 'must not' ORs) between eachother is an AND operation.

Thanks for defogging :)

**Comment by markus101** [comment]
Yeah, exactly. If one restriction includes must contain and must not contain then both rules need to be true (includes at least one must contain and none of the must not contain terms).
