### ISSUE TITLE
Unable to search for Anime series

### ISSUE THREAD

**Issue by antakar** [Sonarr/Sonarr#972]
an not search for an episode without an absolute episode number Parameter name: AbsoluteEpisodeNumber	

	CommandExecutor	Error occurred while executing task SeasonSearch: Can not search for an episode without an absolute episode number Parameter name: AbsoluteEpisodeNumber	23:46
	CommandExecutor	Error occurred while executing task SeasonSearch: Can not search for an episode without an absolute episode number Parameter name: AbsoluteEpisodeNumber	23:46
	Database	Main database compressed	23:45
	Database	Vacuuming Main database	23:45
	Database	Log database compressed	23:45
	Database	Vacuuming Log database	23:44
	HousekeepingService	Running housecleaning tasks	23:44
	CommandExecutor	Error occurred while executing task SeasonSearch: Can not search for an episode without an absolute episode number Parameter name: AbsoluteEpisodeNumber	23:43
	MetadataService	Series folder does not exist, skipping metadata creation	23:42
	MediaCoverService	Downloading Poster for [71863][Lupin III] http://thetvdb.com/banners/posters/71863-4.jpg	23:42
	MediaCoverService	Downloading Banner for [71863][Lupin III] http://thetvdb.com/banners/graphical/71863-g5.jpg	23:42
	EpisodeSearchService	Completed missing search for 254 episodes. 0 reports downloaded.	23:42
	EpisodeSearchService	Unable to search for missing episodes in season 3 of [62]: Can not search for an episode without an absolute episode number Parameter name: AbsoluteEpisodeNumber	23:42
	EpisodeSearchService	Unable to search for missing episodes in season 2 of [62]: Can not search for an episode without an absolute episode number Parameter name: AbsoluteEpisodeNumber	23:42
	EpisodeSearchService	Unable to search for missing episodes in season 1 of [62]: Can not search for an episode without an absolute episode number Parameter name: AbsoluteEpisodeNumber	23:42
	EpisodeSearchService	Unable to search for missing episodes in season 4 of [62]: Can not search for an episode without an absolute episode number Parameter name: AbsoluteEpisodeNumber	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 24]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 23]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 22]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 21]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 20]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 19]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 18]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 17]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 16]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 15]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 14]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 13]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 12]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 11]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 10]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 09]	23:42
	DownloadDecisionMaker	No results found	23:42
	NzbSearchService	Searching 4 indexers for [Lupin III : 08]	23:42

    1 / 223

Total records: 11,109
Details
Message

Error occurred while executing task SeasonSearch: Can not search for an episode without an absolute episode number
Parameter name: AbsoluteEpisodeNumber

Exception

System.ArgumentOutOfRangeException: Can not search for an episode without an absolute episode number
Parameter name: AbsoluteEpisodeNumber
  at NzbDrone.Core.IndexerSearch.NzbSearchService.SearchAnime (NzbDrone.Core.Tv.Series series, NzbDrone.Core.Tv.Episode episode) [0x00079] in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:202 
  at NzbDrone.Core.IndexerSearch.NzbSearchService.SearchAnimeSeason (NzbDrone.Core.Tv.Series series, System.Collections.Generic.List`1 episodes) [0x00017] in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:225 
  at NzbDrone.Core.IndexerSearch.NzbSearchService.SeasonSearch (Int32 seriesId, Int32 seasonNumber, Boolean missingOnly) [0x00050] in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:95 
  at NzbDrone.Core.IndexerSearch.SeasonSearchService.Execute (NzbDrone.Core.IndexerSearch.SeasonSearchCommand message) [0x00000] in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\IndexerSearch\SeasonSearchService.cs:25 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[SeasonSearchCommand] (NzbDrone.Core.IndexerSearch.SeasonSearchCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x0008a] in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:77 

Sonarr Ver. 2.0.0.3594

**Comment by markus101** [comment]
Please use the forums for support, but this is intended behaviour.
