### ISSUE TITLE
iCal - Specify Number of Days in the future to request

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#974]
Right now we let the user specify the start and end dates, but its not obvious and a hard end date sucks for subscribing in another application.

Instead we should let the user specify how many days into the future to show and expose that option in the UI to make it discoverable.

**Comment by kayone** [comment]
I think I had a better idea, but not sure if iCal or the library we use can support it, what if we had some sane default, and allowed overriding it using querystrings, we could even have a modal popup when getting the ical link that lets the user generate the querystrings in the url

**Comment by markus101** [comment]
What if I told you that was my idea?

Right now we can override it to a specific date, but a range is better for all.
