### ISSUE TITLE
Order/Priority between series - used by torrent client

### ISSUE THREAD

**Issue by eranor** [Sonarr/Sonarr#975]
Hi. I have a proposal for an enhancement.

I think it would be useful to be able to set an order/priority between series.
When they new episodes are aired and/or are requested for download,
they would be in that same order in the torrent client, not in the one the 
crawler grabbed them.

**Comment by markus101** [comment]
This adds a lot of complication for minimal gains, we have some ideas to improve series priority based on tags, but we won't do it at a per series level.
