### ISSUE TITLE
Missing Series Folder when intentionally deleted

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#976]
This comes up enough that it warrants some additional consideration I think, right now if the series folder is missing we don't rescan the series and subsequently treat the files as missing, this saves users that have disconnected network or USB drives from Sonarr forgetting about their episodes and possibly them being automatically ignored.

This behaviour isn't obvious to everyone, especially new users and they will often rescan the series manually a few times and not realize why its failing, there are a few things we could do here:
1. Make it more obvious, UI messaging, logging, etc
2. Add an option to skip this behaviour (yuck!)
3. Ignore the series folder missing when doing a manual refresh (from the UI or API)
4. Check for sibling folders of the series folder and use them to determine if we should rescan the series folder

`1` Seems like a good idea, but would also be complicated
`3` I like this idea, but it requires manual interaction
`4` Any major issues with this one? I think I like it the best, it would fail if things are symlinked and the series folder is actually missing, but there are siblings still there, but that seems like an acceptable trade-off

**Comment by kayone** [comment]
we can do what plex does, mark them as unavailable. that way it's obvious what's happening and we aren't removing stuff from the DB either.

**Comment by kayone** [comment]
1. this one is my favorite, tell the user what is happening, and let them decide what to do.
2. I don't like this because people that would get confused by this behaviour most likely won't know about this setting anyways.
3. it's still as destructive as automatic scan
4.I don't mind this, just feels too magical. how many of siblings are we gonna check? what if they delete two folders? what if they intentionally delete half of their series?

**Comment by ZaLiTHkA** [comment]
Keeping within the mentality of not breaking the existing concepts across a few different pages, what about assigning this "status" a new series status colour?

Currently we have "continuing", "ended", "missing - monitored", "missing - not monitored"; so what about another called "unavailable" with a dark grey progress bar? This way the bar and the numbers could still reflect the last known count, while the physical file availability is clear to see. Naturally, this same colour would work on the individual season tags as well.

This begs one question in my mind though: will people expect the individual file rows in each season panel to reflect their individual availability as well, or will the availability check behind this not go that far? For the record, I don't think it should.

What about checking availability by seeing if there is any physical file that matches the chosen episode naming pattern. On the first match, the folder is considered "available" and the normal processes continue. If nothing matches after a short timeout, then the show is marked as "unavailable".

**Comment by markus101** [comment]
Option 4 was implemented, closing this out.
