### ISSUE TITLE
Update SSL Doc for Linux to Include Details About User

### ISSUE THREAD

**Issue by AngellusMortis** [Sonarr/Sonarr#978]
I found on the [forums](https://forums.sonarr.tv/t/improving-ssl-documentation-mono-linux/3266) that the `httpcfg` command must be ran as the user that is running the sonarr process. This saved me a lot of time and issues. 

The [documentation for SSL](https://github.com/Sonarr/Sonarr/wiki/SSL) should be updated with this information so other users will not encounter the same issue. 

EDIT: Is this the [proper repo](https://github.com/M0dM/SonarrDocTest) for the documentation? If so, I can update the doc and submit a pull request.

**Comment by markus101** [comment]
Its a github wiki you just need to click edit on the page and can make changes. Updated it, but feel free to tweak it.
