### ISSUE TITLE
Configurable episodes per page 

### ISSUE THREAD

**Issue by thedrip** [Sonarr/Sonarr#980]
Results page for Activity > Queue is quite long (100+), but results page for
Activity > History, Activity Blacklist, Wanted > Missing, Wanted > Unmet are all very short at 15 lines. Ends up with dozens or hundreds of pages of results.

Possible to add a results per page config item to the UI config page?

**Comment by markus101** [comment]
> Results page for Activity > Queue is quite long (100+)

Are you on an old version? Its been 15 per page since July.

This is something we've talked about, not sure if it should be a global setting for all pages or per page though.

**Comment by thedrip** [comment]
A pull down on the results page to choose 10/50/100/all would work in place of configurable. For me a global length defined would be good. Either way, my end wish is more results, less pages.

**Comment by Danthekilla** [comment]
Something like a 15/30/60/200 dropdown at the bottom of each page would be great!

Anything that lets me see more than 15 at a time, I have 850 pages to go though currently and if I click the search all button deluge and sonarr both choke and die.

**Comment by markus101** [comment]
This is addressed in the v3 UI work.

**Comment by CrimsonCastel** [comment]
So did this ever happen? I now have 4,638 items that I want to go through, and going through them 15 at a time is unrealistic.

And if I click the search all button deluge and sonarr both choke and die.
