### ISSUE TITLE
Deluge Labelplus addin support

### ISSUE THREAD

**Issue by saitoh183** [Sonarr/Sonarr#986]
Would it be possible to add support for Labelplus  addin? It is a lot more flexible then the standard label    and most people that use deluge, also use this adding for managing labels. It works side by side with the default label but has alot more options. The biggest features are that it also allows you to set torrent seeding ratio to 0 if needed and autolabel rules

![image](https://cloud.githubusercontent.com/assets/1534197/11688212/2c9240f4-9e59-11e5-88a1-64aef8e4fc48.png)

![image](https://cloud.githubusercontent.com/assets/1534197/11688223/42be0278-9e59-11e5-8acc-8ef95d393756.png)

![image](https://cloud.githubusercontent.com/assets/1534197/11688283/adaa1bbc-9e59-11e5-8724-611019bde7b8.png)

![image](https://cloud.githubusercontent.com/assets/1534197/11688311/d8b53f3a-9e59-11e5-8d71-7b97701098d2.png)

**Comment by markus101** [comment]
What does Sonarr need to do to use it?
Can it be used over the HTTP API?

We'll need API information for it in order to consider it (how we can set the label and filter on that label) to consider it.

**Comment by saitoh183** [comment]
I dont know if it has a API but here is the link to Git...maybe you can see for yourself

https://github.com/ratanakvlun/deluge-labelplus

**Comment by raspdealer** [comment]
But if you link Sonarr to a label, and this label automanaged and linked to a labelplus one? it doesnt work?

**Comment by saitoh183** [comment]
its not consistent...in the latest version of LBplus, you can set the criteria to link it to a normal label but i found that it doesnt always work when a torrent is auto added from a external source.

**Comment by raspdealer** [comment]
ok.

**Comment by cron410** [comment]
+1

**Comment by KristupasSavickas** [comment]
Digging inside the LabelPlus code I found the API methods exposed by the RPC server. A few methods of a particular interest: [set_torrent_labels](https://github.com/ratanakvlun/deluge-labelplus/blob/master/labelplus/core/core.py#L711) and [add_label](https://github.com/ratanakvlun/deluge-labelplus/blob/master/labelplus/core/core.py#L595). 

Anyway, I'm having a hard time trying to think of a way that label hierarchy could be represented inside Sonarr and translated into API calls without much hustle. Qbittorrent uses grandparent/parent/child scheme, but I don't think this works with LabelPlus. Maybe It would be a good idea to submit a pull request to LabelPlus that would add support for a similar naming scheme?

**Comment by KristupasSavickas** [comment]
After more research I found out there is some kind of built in support for specifying full label hierarchy with LabelPlus, but I'm not sure if it's exposed in the API.

I found a temporary workaround that seems to be working with no problems whatsoever:
1. Enable both Label and LabelPlus plugins.
2. Set category option on Sonarr (I'll use tv-sonarr).
3. Create a tv-sonarr label back on Deluge (make it has no options set, you'll set them with LabelPlus).
4. Create a LabelPlus label. (I'll use media/tv/sonarr).
5. Right click on the LabelPlus label, go to label options and then to autolabel tab.
6. Add a rule that would map your Label plugin label to your LabelPlus label like this:
![screenshot_20180807_195440](https://user-images.githubusercontent.com/1362643/43790623-cc26e36a-9a7b-11e8-8c30-6ab993673a64.png)

**Comment by cron410** [comment]
Never got that to work last time I tried.

**Comment by saitoh183** [comment]
Yeah it doesnt always work. But i found that you get the most consistent results with Contain and not matching cases

**Comment by jtpavlock** [comment]
[this might be a fix](https://forum.deluge-torrent.org/viewtopic.php?f=9&t=42629&start=150#p228463) (for labelplus) as it looks like the labelplus repo is sadly inactive now.

**Comment by nilankadesilva** [comment]
> After more research I found out there is some kind of built in support for specifying full label hierarchy with LabelPlus, but I'm not sure if it's exposed in the API.
> 
> I found a temporary workaround that seems to be working with no problems whatsoever:
> 
>     1. Enable both Label and LabelPlus plugins.
> 
>     2. Set category option on Sonarr (I'll use tv-sonarr).
> 
>     3. Create a tv-sonarr label back on Deluge (make it has no options set, you'll set them with LabelPlus).
> 
>     4. Create a LabelPlus label. (I'll use media/tv/sonarr).
> 
>     5. Right click on the LabelPlus label, go to label options and then to autolabel tab.
> 
>     6. Add a rule that would map your Label plugin label to your LabelPlus label like this:
>        ![screenshot_20180807_195440](https://user-images.githubusercontent.com/1362643/43790623-cc26e36a-9a7b-11e8-8c30-6ab993673a64.png)

This worked for me, many thanks! Just gotta play with the autolabel matching ;)

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR

and

This bug/issue seems stale.  Please check and see if it is still an issue on the recent v3 builds.
