### ISSUE TITLE
720p mp4 are being marked as SDTV in series

### ISSUE THREAD

**Issue by onedr0p** [Sonarr/Sonarr#987]
I've been remuxing my mkvs as mp4 and I noticed that sonarr doesn't display them as being 720p.

![got](https://cloud.githubusercontent.com/assets/213795/11693879/41ffaa14-9e75-11e5-9cd1-ee6e2bcf5352.PNG)

**Comment by markus101** [comment]
You need to make sure the quality it part of the filename or Sonarr uses the extension to determine it, which for mp4 is SDTV.

At least until, https://github.com/Sonarr/Sonarr/issues/448 is implemented.

**Comment by onedr0p** [comment]
Thanks for the fast reply, I'l make sure to include the quality in the filename.

**Comment by JigSawFr** [comment]
Same problem for other "SCENE" release marked as DVD quality but it's 720P

**Comment by markus101** [comment]
@JigSawFr sounds like they are badly named. That issue is only loosely related (and this one is closed), if you have examples open up a new issue.

**Comment by JigSawFr** [comment]
@markus101 Yeah, no problem, i will bring you examples ;)

**Comment by JigSawFr** [comment]
@markus101 Sorry for disturbing you, but i think it's not a good idea to duplicate this issue.
So i think it's a misconfiguration problem or name/provider related issue.

For example:

```
Name:
The.Walking.Dead.S05E16.BDRip.x264-DEMAND
Source:
/medias/series/The.Walking.Dead.S05.BDRip.x264-DEMAND/The.Walking.Dead.S05E16.BDRip.x264-DEMAND.mkv
Imported To:
/medias/sonarr-series/The Walking Dead/Saison 5/The Walking Dead - S05E16 - Conquer DVD.mkv
```

So, as you can see RLZ is a SD, so it's normal.

But Provider recognize it as a 720P Bluray, yes it's a Bluray RIP but not in 720.. it's 480P.

```
» MKV / x264 / Bluray / SD / Scene	5.69 GB	167	53	2
» The.Walking.Dead.S05.BluRay.AAC2.0.x264-DEMAND	
```

So, i can copy it to open an issue for BroadCastTheNet Provider if you want.
A quick fix i think is to set minimum size for a 720P episode for 30/60min.

**Comment by markus101** [comment]
This is definitely a separate issue, I don't understand fully what your issue is, but I don't see any relation between your issue and this GHI. Sonarr correctly used the file name to set the quality on import. Not sure what you mean the provider recognized it as 720p Bluray (unless you mean when it was parsing the results), but you can set a minimum size in the quality settings.

**Comment by JigSawFr** [comment]
@markus101 yes i've done that and it's working properly, SD BRRIP is recognized as a 720P RIP but now is rejected due to size, i answered here to help @onedr0p ;)
