### ISSUE TITLE
Sonarr can't find Victoria's Secret Fashion Show

### ISSUE THREAD

**Issue by hennning** [Sonarr/Sonarr#988]
So, this year's episode of Victoria's Secret Fashion Show has aired but Sonarr can't find it.
I know that it exists on my tracker.

15-12-9 19:49:43.9|Info|NzbSearchService|Searching 1 indexers for [The Victoria's Secret Fashion Show : 2015-12-08
15-12-9 19:49:43.9|Debug|BroadcastheNet|Downloading Feed http://api.btnapps.net/
15-12-9 19:49:44.1|Debug|NzbSearchService|Total of 0 reports were found for [The Victoria's Secret Fashion Show : 2015-12-08 from 1 indexers
15-12-9 19:49:44.1|Info|DownloadDecisionMaker|No results found
15-12-9 19:49:44.1|Info|EpisodeSearchService|Episode search completed. 0 reports downloaded.
15-12-9 19:49:46.5|Info|NzbSearchService|Searching 1 indexers for [The Victoria's Secret Fashion Show : 2015-12-08
15-12-9 19:49:46.5|Debug|BroadcastheNet|Downloading Feed http://api.btnapps.net/
15-12-9 19:49:46.7|Debug|NzbSearchService|Total of 0 reports were found for [The Victoria's Secret Fashion Show : 2015-12-08 from 1 indexers
15-12-9 19:49:46.7|Info|DownloadDecisionMaker|No results found

**Comment by markus101** [comment]
Please use the forums for support.

Because its not named in a way that Sonarr will find it, it doesn't use a date, just a year. We do not have plans at this time to support this naming convention for once a year shows.
