### ISSUE TITLE
Anime "One-Punch Man" not finding episodes correctly possibly due to name of files

### ISSUE THREAD

**Issue by deeznut69** [Sonarr/Sonarr#989]
Anime: One Punch Man 

Cannot find episode on torrent or nzb due to naming possibly. Episode exists but cannot retrieve 

TV says show is called "One-Punch Man" where the episode file is listed as "One Punch Man"

Log below:
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 01]	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 01]	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 01]	12:15am
	SeasonSearchService	Season search completed. 0 reports downloaded.	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 12]	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 11]	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 10]	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 09]	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 08]	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 07]	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 06]	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 05]	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 04]	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 03]	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 02]	12:15am
	DownloadDecisionMaker	No results found	12:15am
	NzbSearchService	Searching 2 indexers for [One-Punch Man : 01]	12:15am
	Database	Log database compressed	12:15am
	Database	Vacuuming Log database	12:15am

    1 / 1

Total records: 33

**Comment by markus101** [comment]
Please use the forums for support and include debug logs of search issue.
