### ISSUE TITLE
Don't overwrite metadata files after creation

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#991]
Emby watched statuses are nuked () and people that use something else to process them (convert MPAA ratings to another system), lose those changes.

Simple solution is to write once and never again, this would solve both issues and be similar to how Kodi/Plex behave in terms of getting metadata.

**Comment by kayone** [comment]
Ideally we could even get smarter, where we surgically updated certain parts, episode name, number, description etc.

**Comment by randomevents** [comment]
I have a suggestion because I (wrongly) assumed this is the way it already worked until the other day; If a show or season is flagged as Unmonitored, then don't update the metadata files. It's a simple check, and can be ignored if the user triggers a scan and refresh. DVD order issues aside (it's not a hard problem to work around), it's the retroactive adjustments from TheTVDB that are such a pain in the ass.

**Comment by markus101** [comment]
I don't think we want to conflate the unmonitored flag with turning off other functionality. I don't think it will be obvious to the user and turning off metadata seems like could go a step further and stop getting data from TheTVDB, which seems really extreme.

Why keep the series in Sonarr if you don't want it alter anything? With in unmonitored it wouldn't upgrade any files either.

**Comment by randomevents** [comment]
Couldn't (un)monitor upgrade files also read as (un)monitor metadata changes? Which is how I understood it; if I didn't want new files, why would I want new metadata? It's also seems like it would be a shame to have to clutter up the UI/

There's plenty of examples; manually editting NFOs from previous seasons (with another tool like media companion), another horrible act of violence messing up story order. The forum tiffs between the mods and editors at the TheTVDB that mess up the metadata but don't trigger file upgrades when the file is at the max, etc etc. It's especially horrible with cartoons, there's alot of fixes to be made between tvdb and the scene, and it doesn't help that theXEM isn't letting anyone sign up to do edits, so a lot of stuff doesn't get done.

Sure it's easy enough to remove dead shows, but I think like it or not, your team has made a great enough product that many people use it as a tv show media manager for all their stuff.

**Comment by markus101** [comment]
Unmonitor stops season searching and RSS from automatically grabbing results, but you could search for one episode or do a manual search and Sonarr would import it even if it was unmonitored.

> There's plenty of examples; manually editting NFOs from previous seasons (with another tool like media companion), another horrible act of violence messing up story order.

Aired vs DVD ordering?

TheTVDB issues are going to be ever present, seems weird to stop updating the metadata files, but have the Sonarr UI have a different representation of it, feels like it's asking for it to be confusing.

TheTVDB vs scene numbering is a problem, especially with p2p groups mixing and matching which numbering they follow. As for getting access to thexem.de it's closed for good reason, a high percentage of the changes being made there were completely wrong or had no reason to be there, wasting moderation time, but if you know what you're doing and are willing to help out, reach out to them on IRC #xem on freenode.

**Comment by randomevents** [comment]
> There's plenty of examples; manually editting NFOs from previous seasons (with another tool like media companion)

Fixing bad descriptions and art on locked shows. Sometimes the mods are willing to open it up for a moment or make the change themselves, sometimes they're not.

I tried reaching out for a couple of months last season to no avail, it #xem was always pretty silent

**Comment by bakerboy448** [comment]
This bug/issue seems stale.  Please check and see if it is still an issue on the recent v3 builds.  If it is an issue please open a new GHI with logs and full detail.
