### ISSUE TITLE
Remove TitansOf.TV from indexers / add MoreThan.TV and or FreshOn.TV

### ISSUE THREAD

**Issue by DirtyCajunRice** [Sonarr/Sonarr#992]
Site is down for good... Possibly add MoreThan.TV?

**Comment by markus101** [comment]
We can definitely remove Titans, but unless MoreThan/FreshON have proper APIs they will not be added. They're part of Jackett which is usually a good indication that they don't have an API.

**Comment by DirtyCajunRice** [comment]
Ok. Understood on the second part. thanks on the first part.
