### ISSUE TITLE
Episodes missing even though they exist on disk

### ISSUE THREAD

**Issue by SirStevo** [Sonarr/Sonarr#995]
I recently installed a NAS device. Before migrating series onto the NAS, they were on a local disk and I had no issues. Since moving the data to the NAS, a lot of episodes are not picked up and Sonarr initiates a download of these episodes. Even if I rescan the folders, they do not get detected by Sonarr.

**Comment by markus101** [comment]
Please use the forums for support.

Include a debug log of a series refresh and let us know which files aren't processing.
